# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs -mtriple=aie2 -run-pass=aie-pseudobranches %s -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -verify-machineinstrs -mtriple=aie2p -run-pass=aie-pseudobranches %s -o - | FileCheck --check-prefix=AIE2P %s
# RUN: llc -verify-machineinstrs -mtriple=aie2ps -run-pass=aie-pseudobranches %s -o - | FileCheck --check-prefix=AIE2PS %s

---
name:            test_jnz
alignment:       16
body:             |
  ; AIE2-LABEL: name: test_jnz
  ; AIE2: bb.0 (align 16):
  ; AIE2-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   JNZ $r6, %bb.1
  ; AIE2-NEXT:   DelayedSchedBarrier
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1 (align 16):
  ;
  ; AIE2P-LABEL: name: test_jnz
  ; AIE2P: bb.0 (align 16):
  ; AIE2P-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   JNZ $r6, %bb.1
  ; AIE2P-NEXT:   DelayedSchedBarrier
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1 (align 16):
  ;
  ; AIE2PS-LABEL: name: test_jnz
  ; AIE2PS: bb.0 (align 16):
  ; AIE2PS-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   JNZ $r6, %bb.1
  ; AIE2PS-NEXT:   DelayedSchedBarrier
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.1 (align 16):
  bb.0 (align 16):
    PseudoJNZ $r6, %bb.1
  bb.1 (align 16):
...

---
name:            test_jz
alignment:       16
body:             |
  ; AIE2-LABEL: name: test_jz
  ; AIE2: bb.0 (align 16):
  ; AIE2-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   JZ $r6, %bb.1
  ; AIE2-NEXT:   DelayedSchedBarrier
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1 (align 16):
  ;
  ; AIE2P-LABEL: name: test_jz
  ; AIE2P: bb.0 (align 16):
  ; AIE2P-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   JZ $r6, %bb.1
  ; AIE2P-NEXT:   DelayedSchedBarrier
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1 (align 16):
  ;
  ; AIE2PS-LABEL: name: test_jz
  ; AIE2PS: bb.0 (align 16):
  ; AIE2PS-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   JZ $r6, %bb.1
  ; AIE2PS-NEXT:   DelayedSchedBarrier
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.1 (align 16):
  bb.0 (align 16):
    PseudoJZ $r6, %bb.1
  bb.1 (align 16):
...

---
name:            test_jnzd
alignment:       16
body:             |
  bb.0 (align 16):
    ; AIE2-LABEL: name: test_jnzd
    ; AIE2: $r6 = JNZD $r6, $p2, implicit-def $srcarry
    ; AIE2-NEXT: DelayedSchedBarrier
    ;
    ; AIE2P-LABEL: name: test_jnzd
    ; AIE2P: $r6 = JNZD $r6, $p2, implicit-def $srcarry
    ; AIE2P-NEXT: DelayedSchedBarrier
    ;
    ; AIE2PS-LABEL: name: test_jnzd
    ; AIE2PS: $r6 = JNZD $r6, $p2, implicit-def $srcarry
    ; AIE2PS-NEXT: DelayedSchedBarrier
    $r6 = PseudoJNZD $r6, $p2, implicit-def $srcarry
...

---
name:            test_j_imm
alignment:       16
body:             |
  ; AIE2-LABEL: name: test_j_imm
  ; AIE2: bb.0 (align 16):
  ; AIE2-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   J_jump_imm %bb.1
  ; AIE2-NEXT:   DelayedSchedBarrier
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1 (align 16):
  ;
  ; AIE2P-LABEL: name: test_j_imm
  ; AIE2P: bb.0 (align 16):
  ; AIE2P-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   J_lng %bb.1
  ; AIE2P-NEXT:   DelayedSchedBarrier
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1 (align 16):
  ;
  ; AIE2PS-LABEL: name: test_j_imm
  ; AIE2PS: bb.0 (align 16):
  ; AIE2PS-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   J_lng %bb.1
  ; AIE2PS-NEXT:   DelayedSchedBarrier
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.1 (align 16):
  bb.0 (align 16):
    PseudoJ_jump_imm %bb.1
  bb.1 (align 16):
...

---
name:            test_j_ind
alignment:       16
body:             |
  bb.0 (align 16):
    ; AIE2-LABEL: name: test_j_ind
    ; AIE2: J_jump_ind $p2
    ; AIE2-NEXT: DelayedSchedBarrier
    ;
    ; AIE2P-LABEL: name: test_j_ind
    ; AIE2P: J_alumv_or $p2
    ; AIE2P-NEXT: DelayedSchedBarrier
    ;
    ; AIE2PS-LABEL: name: test_j_ind
    ; AIE2PS: J_alumv_or $p2
    ; AIE2PS-NEXT: DelayedSchedBarrier
    PseudoJ_jump_ind $p2
...

---
name:            test_ret
alignment:       16
body:             |
  bb.0 (align 16):
    ; AIE2-LABEL: name: test_ret
    ; AIE2: RET implicit $lr
    ; AIE2-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    ;
    ; AIE2P-LABEL: name: test_ret
    ; AIE2P: RET implicit $lr
    ; AIE2P-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    ;
    ; AIE2PS-LABEL: name: test_ret
    ; AIE2PS: RET implicit $lr
    ; AIE2PS-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name:            test_jl
alignment:       16
body:             |
  bb.0 (align 16):
    ; AIE2-LABEL: name: test_jl
    ; AIE2: JL 128, implicit-def $lr
    ; AIE2-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    ; AIE2-NEXT: JL_IND $p2, implicit-def $lr
    ; AIE2-NEXT: DelayedSchedBarrier implicit-def dead $r0, implicit $r2, implicit $r3
    ;
    ; AIE2P-LABEL: name: test_jl
    ; AIE2P: JL_lng 128, implicit-def $lr
    ; AIE2P-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    ; AIE2P-NEXT: JL_alumv_or $p2, implicit-def $lr
    ; AIE2P-NEXT: DelayedSchedBarrier implicit-def dead $r0, implicit $r2, implicit $r3
    ;
    ; AIE2PS-LABEL: name: test_jl
    ; AIE2PS: JL_lng 128, implicit-def $lr
    ; AIE2PS-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    ; AIE2PS-NEXT: JL_alumv_or $p2, implicit-def $lr
    ; AIE2PS-NEXT: DelayedSchedBarrier implicit-def dead $r0, implicit $r2, implicit $r3
    PseudoJL 128, implicit-def $lr, implicit $r0, implicit $r1
    PseudoJL_IND $p2, implicit-def $lr, implicit-def dead $r0, implicit $r2, implicit $r3
...

---
name:            test_multi
alignment:       16
body:             |
  ; AIE2-LABEL: name: test_multi
  ; AIE2: bb.0 (align 16):
  ; AIE2-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   JL_IND $p2, implicit-def $lr
  ; AIE2-NEXT:   DelayedSchedBarrier implicit $r2, implicit $r3
  ; AIE2-NEXT:   JZ $r6, %bb.1
  ; AIE2-NEXT:   DelayedSchedBarrier
  ; AIE2-NEXT:   JNZ $r6, %bb.2
  ; AIE2-NEXT:   DelayedSchedBarrier
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1 (align 16):
  ; AIE2-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2 (align 16):
  ;
  ; AIE2P-LABEL: name: test_multi
  ; AIE2P: bb.0 (align 16):
  ; AIE2P-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   JL_alumv_or $p2, implicit-def $lr
  ; AIE2P-NEXT:   DelayedSchedBarrier implicit $r2, implicit $r3
  ; AIE2P-NEXT:   JZ $r6, %bb.1
  ; AIE2P-NEXT:   DelayedSchedBarrier
  ; AIE2P-NEXT:   JNZ $r6, %bb.2
  ; AIE2P-NEXT:   DelayedSchedBarrier
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1 (align 16):
  ; AIE2P-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.2 (align 16):
  ;
  ; AIE2PS-LABEL: name: test_multi
  ; AIE2PS: bb.0 (align 16):
  ; AIE2PS-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   JL_alumv_or $p2, implicit-def $lr
  ; AIE2PS-NEXT:   DelayedSchedBarrier implicit $r2, implicit $r3
  ; AIE2PS-NEXT:   JZ $r6, %bb.1
  ; AIE2PS-NEXT:   DelayedSchedBarrier
  ; AIE2PS-NEXT:   JNZ $r6, %bb.2
  ; AIE2PS-NEXT:   DelayedSchedBarrier
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.1 (align 16):
  ; AIE2PS-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.2 (align 16):
  bb.0 (align 16):
    PseudoJL_IND $p2, implicit-def $lr, implicit $r2, implicit $r3
    PseudoJZ $r6, %bb.1
    PseudoJNZ $r6, %bb.2
  bb.1 (align 16):
  bb.2 (align 16):
...
