# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs -mtriple=aie2ps -run-pass=postrapseudos %s -o - | FileCheck %s

# Check that copies between 64-bit L registers (eL) and 64-bit G sub-tile shift
# registers (eGGe/eGGo) are expanded by lowering each 32-bit half through the
# corresponding GPR<->gl/gh moves.

---
name:            copy_l_to_g
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: copy_l_to_g
    ; CHECK: $gl0 = MOV_alu_mv_mv_mv_g_mv_r_to_gl $r2
    ; CHECK-NEXT: $gh0 = MOV_alu_mv_mv_mv_g_mv_r_to_gh $r3
    ; CHECK-NEXT: $gl2 = MOV_alu_mv_mv_mv_g_mv_r_to_gl $r6
    ; CHECK-NEXT: $gh2 = MOV_alu_mv_mv_mv_g_mv_r_to_gh $r7
    $g0 = COPY $l1
    $g2 = COPY $l3
...

---
name:            copy_g_to_l
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: copy_g_to_l
    ; CHECK: $r2 = MOV_alu_mv_mv_mv_g_mv_gl_to_r $gl0
    ; CHECK-NEXT: $r3 = MOV_alu_mv_mv_mv_g_mv_gh_to_r $gh0
    ; CHECK-NEXT: $r6 = MOV_alu_mv_mv_mv_g_mv_gl_to_r $gl2
    ; CHECK-NEXT: $r7 = MOV_alu_mv_mv_mv_g_mv_gh_to_r $gh2
    $l1 = COPY $g0
    $l3 = COPY $g2
...
