# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -enable-misched -run-pass=machine-scheduler %s -o - | FileCheck %s

# Verify pre-RA scheduling will interleave the load and stores.

--- |
  define void @mix(ptr %p0, ptr %p1) {
  entry:
    ret void
  }
...

---
name: mix
tracksRegLiveness: true
body: |
  bb.0.entry:
  liveins: $p0, $p1
    ; CHECK-LABEL: name: mix
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:er = LDA_dms_lda_idx_imm [[COPY]], 0 :: (load (s32) from %ir.p0)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY [[COPY]]
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm1:%[0-9]+]]:er = LDA_dms_lda_idx_imm [[COPY1]], 0 :: (load (s32) from %ir.p0)
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:ep_as_32bit = MOVXM_lng_cg -524284
    ; CHECK-NEXT: ST_TM [[LDA_dms_lda_idx_imm]], [[MOVXM_lng_cg]] :: (store (s32) into custom "TileMemory", addrspace 15)
    ; CHECK-NEXT: [[MOVXM_lng_cg1:%[0-9]+]]:ep_as_32bit = MOVXM_lng_cg -524280
    ; CHECK-NEXT: ST_TM [[LDA_dms_lda_idx_imm1]], [[MOVXM_lng_cg1]] :: (store (s32) into custom "TileMemory", addrspace 15)
    %100:ep = COPY $p0
    %200:er = LDA_dms_lda_idx_imm %100, 0 :: (load (s32) from %ir.p0)
    %300:ep_as_32bit = MOVXM_lng_cg -524284
    ST_TM %200, %300 :: (store (s32) into custom "TileMemory")

    %101:ep = COPY %100
    %201:er = LDA_dms_lda_idx_imm %101, 0 :: (load (s32) from %ir.p0)
    %301:ep_as_32bit = MOVXM_lng_cg -524280
    ST_TM %201, %301 :: (store (s32) into custom "TileMemory")
...
