# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -enable-misched -run-pass=machine-scheduler --aie-prera-func-unit-depth=20 %s -o - | FileCheck %s

# An example that shows the limitation of botom-up pre-RA scheduling.
# LDA is moved all the way to the top because it can never reserve R_WA_PORT,
# as it is taken by all the MOVAs already.

---
name: mix
tracksRegLiveness: true
body: |
  bb.0.entry:
  liveins: $p0, $p1
    ; CHECK-LABEL: name: mix
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: dead [[LDA_dms_lda_idx_imm:%[0-9]+]]:er = LDA_dms_lda_idx_imm [[COPY]], 0 :: (load (s32))
    ; CHECK-NEXT: dead [[MOVA_lda_cg:%[0-9]+]]:er = MOVA_lda_cg 1
    ; CHECK-NEXT: dead [[MOVA_lda_cg1:%[0-9]+]]:er = MOVA_lda_cg 1
    ; CHECK-NEXT: dead [[MOVA_lda_cg2:%[0-9]+]]:er = MOVA_lda_cg 1
    ; CHECK-NEXT: dead [[MOVA_lda_cg3:%[0-9]+]]:er = MOVA_lda_cg 1
    ; CHECK-NEXT: dead [[MOVA_lda_cg4:%[0-9]+]]:er = MOVA_lda_cg 1
    ; CHECK-NEXT: dead [[MOVA_lda_cg5:%[0-9]+]]:er = MOVA_lda_cg 1
    ; CHECK-NEXT: dead [[MOVA_lda_cg6:%[0-9]+]]:er = MOVA_lda_cg 1
    ; CHECK-NEXT: dead [[MOVA_lda_cg7:%[0-9]+]]:er = MOVA_lda_cg 1
    %100:ep = COPY $p0
    %10:er = MOVA_lda_cg 1
    %10:er = MOVA_lda_cg 1
    %10:er = MOVA_lda_cg 1
    %10:er = MOVA_lda_cg 1
    %10:er = MOVA_lda_cg 1
    %10:er = MOVA_lda_cg 1
    %10:er = MOVA_lda_cg 1
    %10:er = MOVA_lda_cg 1
    %200:er = LDA_dms_lda_idx_imm %100, 0 :: (load (s32))
...
