# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -enable-misched -run-pass=machine-scheduler %s -o - | FileCheck %s

# Make sure the Multi-Slot Instr. are not materialize during Pre-RA scheduler.

--- |
  define void @mix(ptr %p0, ptr %p1) {
  entry:
    ret void
  }
...

---
name: mix
tracksRegLiveness: true
body: |
  bb.0.entry:
  liveins: $p0, $p1, $m1, $r1, $s1
    ; CHECK-LABEL: name: mix
    ; CHECK: liveins: $p0, $p1, $m1, $r1, $s1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $p1 = PADD_mod_pseudo $p1, $m1
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, $m1
    ; CHECK-NEXT: $m1 = MOV_PD_imm10_pseudo 0
    ; CHECK-NEXT: $p0 = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $r1 = MOV_RLC_imm10_pseudo 0
    ; CHECK-NEXT: $s1 = MOV_S_imm10_pseudo 0
    ; CHECK-NEXT: $r1 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: $m1 = MOV_PD_imm11_pseudo 0
    %100:ep = COPY $p0
    ; Following multi-slot instr should NOT be materialize after Pre-RA scheduler
    $p1 = PADD_mod_pseudo $p1, $m1
    $p0 = PADD_mod_pseudo $p0, $m1
    $m1 = MOV_PD_imm10_pseudo 0
    $p0 = MOV_scalar_imm10_pseudo 0
    $r1 = MOV_RLC_imm10_pseudo 0
    $s1 = MOV_S_imm10_pseudo 0
    $r1 = MOV_RLC_imm11_pseudo 0
    $m1 = MOV_PD_imm11_pseudo 0
...
