# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

# There is only one X register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.
---
name:            test_512_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $p0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11

    ; CHECK-LABEL: name: test_512_scarce_regs
    ; CHECK: liveins: $bmll0, $p0, $r0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x0 = COPY $bmll0
    ; CHECK-NEXT: VST_X_SPILL killed renamable $x0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: $x0 = COPY $x1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $x0, implicit $x1, implicit $x2, implicit $x3, implicit $x4, implicit $x5, implicit $x6, implicit $x7, implicit $x8, implicit $x9, implicit $x10, implicit $x11
    ; CHECK-NEXT: renamable $x0 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $x0
    %0:vec512 = COPY $bmll0 ; -> only $x0 is available

    $x0 = COPY $x1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $x0, implicit $x1, implicit $x2, implicit $x3, implicit $x4, implicit $x5, implicit $x6, implicit $x7, implicit $x8, implicit $x9, implicit $x10, implicit $x11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_512_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: test_512_caller_saved
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_X_SPILL $x0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $x0 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $x0
    %0:vec512 = COPY $x0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...


# There is only one Y register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.
---
name:            test_1024_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $p0, $y1, $y2, $y3, $y4, $y5

    ; CHECK-LABEL: name: test_1024_scarce_regs
    ; CHECK: liveins: $cml0, $p0, $r0, $y1, $y2, $y3, $y4, $y5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $y0 = COPY $cml0
    ; CHECK-NEXT: VST_Y_SPILL killed renamable $y0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: $y0 = COPY $y3
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $y0, implicit $y1, implicit $y2, implicit $y3, implicit $y4, implicit $y5
    ; CHECK-NEXT: renamable $y0 = VLDA_Y_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $y0
    %0:vec1024 = COPY $cml0 ; -> only $y0 is available

    $y0 = COPY $y3
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $y0, implicit $y1, implicit $y2, implicit $y3, implicit $y4, implicit $y5

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_1024_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y2

    ; CHECK-LABEL: name: test_1024_caller_saved
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_Y_SPILL $y2, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $y0 = VLDA_Y_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $y0
    %0:vec1024 = COPY $y2
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...
