# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

---
name:            test_1024_fifo_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $p0, $lf1

    ; CHECK-LABEL: name: test_1024_fifo_scarce_regs
    ; CHECK: liveins: $cml0, $lf1, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lf0 = COPY $cml0
    ; CHECK-NEXT: renamable $y0 = COPY killed renamable $lf0
    ; CHECK-NEXT: VST_Y_SPILL killed renamable $y0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: $lf0 = COPY $lf1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    ; CHECK-NEXT: renamable $y0 = VLDA_Y_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: renamable $lf0 = COPY killed renamable $y0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lf0
    %0:eldfiforeg = COPY $cml0 ; -> only $lf0 is available

    $lf0 = COPY $lf1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_1024_fifo_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $lf0

    ; CHECK-LABEL: name: test_1024_fifo_caller_saved
    ; CHECK: liveins: $lf0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $y0 = COPY $lf0
    ; CHECK-NEXT: VST_Y_SPILL killed renamable $y0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $y0 = VLDA_Y_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: renamable $lf0 = COPY killed renamable $y0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lf0
    %0:eldfiforeg = COPY $lf0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...



---
name:            test_1024_fifo_sf_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $p0, $y1

    ; CHECK-LABEL: name: test_1024_fifo_sf_scarce_regs
    ; CHECK: liveins: $cml0, $p0, $r0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $sf = COPY $cml0
    ; CHECK-NEXT: renamable $y0 = COPY killed renamable $sf
    ; CHECK-NEXT: VST_Y_SPILL killed renamable $y0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: $sf = COPY $y1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $sf
    ; CHECK-NEXT: renamable $y0 = VLDA_Y_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: renamable $sf = COPY killed renamable $y0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $sf
    %0:mstfifo = COPY $cml0 ; -> only $sf is available

    $sf = COPY $y1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $sf
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_1024_fifo_sf_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $sf

    ; CHECK-LABEL: name: test_1024_fifo_sf_caller_saved
    ; CHECK: liveins: $sf
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $y0 = COPY $sf
    ; CHECK-NEXT: VST_Y_SPILL killed renamable $y0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $y0 = VLDA_Y_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: renamable $sf = COPY killed renamable $y0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $sf
    %0:mstfifo = COPY $sf
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...


---
name:            test_512_fifo_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $lf0

    ; CHECK-LABEL: name: test_512_fifo_caller_saved
    ; CHECK: liveins: $lf0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lfh0 = COPY $lfl0
    ; CHECK-NEXT: renamable $x0 = COPY killed renamable $lfh0
    ; CHECK-NEXT: VST_X_SPILL killed renamable $x0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $x0 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: renamable $lfh0 = COPY killed renamable $x0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lfh0
    %0:eldfifohreg = COPY $lfl0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_512_fifo_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $p0, $lf1

    ; CHECK-LABEL: name: test_512_fifo_scarce_regs
    ; CHECK: liveins: $bmll0, $lf1, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lfl0 = COPY $bmll0
    ; CHECK-NEXT: renamable $x0 = COPY killed renamable $lfl0
    ; CHECK-NEXT: VST_X_SPILL killed renamable $x0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: $lfl0 = COPY $lfl1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    ; CHECK-NEXT: renamable $x0 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: renamable $lfl0 = COPY killed renamable $x0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lfl0
    %0:eldfifolreg = COPY $bmll0 ; -> only $lfl0 is available

    $lfl0 = COPY $lfl1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    PseudoRET implicit $lr, implicit %0
...


---
name:            test_extra_fifo_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $lfl0

    ; CHECK-LABEL: name: test_extra_fifo_caller_saved
    ; CHECK: liveins: $lfl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lfe = COPY $lfl0
    ; CHECK-NEXT: renamable $x0 = COPY killed renamable $lfe
    ; CHECK-NEXT: VST_X_SPILL killed renamable $x0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $x0 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: renamable $lfe = COPY killed renamable $x0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lfe
    %0:mfifoextra = COPY $lfl0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_extra_fifo_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $p0, $lf1

    ; CHECK-LABEL: name: test_extra_fifo_scarce_regs
    ; CHECK: liveins: $bmll0, $lf1, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lfe = COPY $bmll0
    ; CHECK-NEXT: renamable $x0 = COPY killed renamable $lfe
    ; CHECK-NEXT: VST_X_SPILL killed renamable $x0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: $lfe = COPY $lfl1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $lfe, implicit $lf1
    ; CHECK-NEXT: renamable $x0 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: renamable $lfe = COPY killed renamable $x0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lfe
    %0:mfifoextra = COPY $bmll0 ; -> only $lfe is available

    $lfe = COPY $lfl1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $lfe, implicit $lf1
    PseudoRET implicit $lr, implicit %0
...
