# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -start-before=greedy -stop-after=prologepilog %s -o - | FileCheck %s

# Test: When both GPRs of a pair need saving and function has calls,
# we save the L register (1 store) instead of 2 separate GPR stores.

---
name:            test_l_with_call
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
frameInfo:
  hasCalls:        true
fixedStack:
  - { id: 0, type: default, offset: 0, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '' }
body:             |
  bb.1.entry:
    liveins: $l0, $l4, $l5, $l6, $l7, $r11

    ; CHECK-LABEL: name: test_l_with_call
    ; CHECK: liveins: $l0, $l4, $l5, $l6, $l7, $r11, $l7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $lr, -44, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: ST_dml_sts_scalar_spill killed $l7, -56, implicit $sp :: (store (s64) into %stack.2)
    ; CHECK-NEXT: renamable $r3 = LDA_dms_lda_scalar_spill -64, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $r3, -48, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: renamable $l7 = COPY $l0
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: $r1 = LDA_dms_lda_scalar_spill -48, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $l7 = LDA_dml_lda_scalar_L_spill -56, implicit $sp :: (load (s64) from %stack.2)
    ; CHECK-NEXT: $lr = LDA_dms_lda_scalar_spill -44, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $r1, implicit killed renamable $l7, implicit $l4, implicit $r11, implicit $l5, implicit $l6
    %0:er = LDA_dms_lda_scalar_spill %fixed-stack.0, implicit $sp
    %1:el = COPY $l0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0, implicit %1, implicit $l4, implicit $r11, implicit $l5, implicit $l6
...


---
name:            test_l_no_call
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
fixedStack:
  - { id: 0, type: default, offset: 0, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '' }
body:             |
  bb.1.entry:
    liveins: $l0, $l4, $l6, $l7, $r11, $l1, $l2, $l3, $l9, $l10, $l11, $l12, $l13, $l14, $l15

    ; CHECK-LABEL: name: test_l_no_call
    ; CHECK: liveins: $l0, $l1, $l2, $l3, $l4, $l6, $l7, $l9, $l10, $l11, $l12, $l13, $l14, $l15, $r11, $r8, $r9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r16 = PseudoMove killed $r8
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $r9, -60, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: renamable $r17 = LDA_dms_lda_scalar_spill -64, implicit $sp
    ; CHECK-NEXT: renamable $l4 = KILL $l0
    ; CHECK-NEXT: $r9 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $r8 = PseudoMove killed $r16
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $r17, implicit killed renamable $l4, implicit $l0, implicit $r11, implicit $l5, implicit $l6, implicit $l7, implicit $l1, implicit $l2, implicit $l3, implicit $l9, implicit $l10, implicit $l11, implicit $l12, implicit $l13, implicit $l14, implicit $l15
    %0:er = LDA_dms_lda_scalar_spill %fixed-stack.0, implicit $sp
    %2:el = COPY $l0
    %1:el = KILL $l0
    PseudoRET implicit $lr, implicit %0, implicit %1, implicit $l0, implicit $r11, implicit $l5, implicit $l6, implicit $l7, implicit $l1, implicit $l2, implicit $l3, implicit $l9, implicit $l10, implicit $l11, implicit $l12, implicit $l13, implicit $l14, implicit $l15
...

