# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

# There is only one register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.

---
name:            test_e_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $el0, $r0, $p0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11

    ; CHECK-LABEL: name: test_e_scarce_regs
    ; CHECK: liveins: $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $el0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_E_SPILL $el0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $e0 = COPY $e1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $e0, implicit $e1, implicit $e2, implicit $e3, implicit $e4, implicit $e5, implicit $e6, implicit $e7, implicit $e8, implicit $e9, implicit $e10, implicit $e11
    ; CHECK-NEXT: renamable $el0 = VLDA_E_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $el0
    %0:mes = COPY $el0 ; -> only $e0 is available

    $e0 = COPY $e1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $e0, implicit $e1, implicit $e2, implicit $e3, implicit $e4, implicit $e5, implicit $e6, implicit $e7, implicit $e8, implicit $e9, implicit $e10, implicit $e11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_e_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $e0

    ; CHECK-LABEL: name: test_e_caller_saved
    ; CHECK: liveins: $e0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $el0 = COPY $e0
    ; CHECK-NEXT: VST_E_SPILL killed renamable $el0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $el0 = VLDA_E_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $el0
    %0:mes = COPY $e0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_ee_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $e0, $r0, $p0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11

    ; CHECK-LABEL: name: test_ee_scarce_regs
    ; CHECK: liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_EE_SPILL $e0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: $e0 = COPY $e1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $e0, implicit $e1, implicit $e2, implicit $e3, implicit $e4, implicit $e5, implicit $e6, implicit $e7, implicit $e8, implicit $e9, implicit $e10, implicit $e11
    ; CHECK-NEXT: renamable $e0 = VLDA_EE_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $e0
    %0:mees = COPY $e0 ; -> only $e0 is available

    $e0 = COPY $e1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $e0, implicit $e1, implicit $e2, implicit $e3, implicit $e4, implicit $e5, implicit $e6, implicit $e7, implicit $e8, implicit $e9, implicit $e10, implicit $e11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_ee_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $e0

    ; CHECK-LABEL: name: test_ee_caller_saved
    ; CHECK: liveins: $e0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_EE_SPILL $e0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $e0 = VLDA_EE_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $e0
    %0:mees = COPY $e0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_f_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $fl0, $r0, $p0, $f1, $f2, $f3, $f4, $f5, $f6, $f7, $f8, $f9, $f10, $f11

    ; CHECK-LABEL: name: test_f_scarce_regs
    ; CHECK: liveins: $f1, $f2, $f3, $f4, $f5, $f6, $f7, $f8, $f9, $f10, $f11, $fl0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_F_SPILL $fl0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: $f0 = COPY $f1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $f0, implicit $f1, implicit $f2, implicit $f3, implicit $f4, implicit $f5, implicit $f6, implicit $f7, implicit $f8, implicit $f9, implicit $f10, implicit $f11
    ; CHECK-NEXT: renamable $fl0 = VLDA_F_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $fl0
    %0:mfs = COPY $fl0 ; -> only $f0 is available

    $f0 = COPY $f1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $f0, implicit $f1, implicit $f2, implicit $f3, implicit $f4, implicit $f5, implicit $f6, implicit $f7, implicit $f8, implicit $f9, implicit $f10, implicit $f11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_f_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $f0

    ; CHECK-LABEL: name: test_f_caller_saved
    ; CHECK: liveins: $f0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $fl0 = COPY $f0
    ; CHECK-NEXT: VST_F_SPILL killed renamable $fl0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $fl0 = VLDA_F_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $fl0
    %0:mfs = COPY $f0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_ff_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $f0, $r0, $p0, $f1, $f2, $f3, $f4, $f5, $f6, $f7, $f8, $f9, $f10, $f11

    ; CHECK-LABEL: name: test_ff_scarce_regs
    ; CHECK: liveins: $f0, $f1, $f2, $f3, $f4, $f5, $f6, $f7, $f8, $f9, $f10, $f11, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_FF_SPILL $f0, %stack.0, implicit $sp :: (store (s128) into %stack.0)
    ; CHECK-NEXT: $f0 = COPY $f1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $f0, implicit $f1, implicit $f2, implicit $f3, implicit $f4, implicit $f5, implicit $f6, implicit $f7, implicit $f8, implicit $f9, implicit $f10, implicit $f11
    ; CHECK-NEXT: renamable $f0 = VLDA_FF_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $f0
    %0:mffs = COPY $f0 ; -> only $f0 is available

    $f0 = COPY $f1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $f0, implicit $f1, implicit $f2, implicit $f3, implicit $f4, implicit $f5, implicit $f6, implicit $f7, implicit $f8, implicit $f9, implicit $f10, implicit $f11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_ff_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $f0

    ; CHECK-LABEL: name: test_ff_caller_saved
    ; CHECK: liveins: $f0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_FF_SPILL $f0, %stack.0, implicit $sp :: (store (s128) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $f0 = VLDA_FF_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $f0
    %0:mffs = COPY $f0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_g_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $gl0, $r0, $p0, $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11

    ; CHECK-LABEL: name: test_g_scarce_regs
    ; CHECK: liveins: $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $gl0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_G_SPILL $gl0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $g0 = COPY $g1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $g0, implicit $g1, implicit $g2, implicit $g3, implicit $g4, implicit $g5, implicit $g6, implicit $g7, implicit $g8, implicit $g9, implicit $g10, implicit $g11
    ; CHECK-NEXT: renamable $gl0 = VLDA_G_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $gl0
    %0:mgs = COPY $gl0 ; -> only $g0 is available

    $g0 = COPY $g1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $g0, implicit $g1, implicit $g2, implicit $g3, implicit $g4, implicit $g5, implicit $g6, implicit $g7, implicit $g8, implicit $g9, implicit $g10, implicit $g11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_g_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $g0

    ; CHECK-LABEL: name: test_g_caller_saved
    ; CHECK: liveins: $g0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $gl0 = COPY $g0
    ; CHECK-NEXT: VST_G_SPILL killed renamable $gl0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $gl0 = VLDA_G_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $gl0
    %0:mgs = COPY $g0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_gg_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $g0, $r0, $p0, $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11

    ; CHECK-LABEL: name: test_gg_scarce_regs
    ; CHECK: liveins: $g0, $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_GG_SPILL $g0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: $g0 = COPY $g1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $g0, implicit $g1, implicit $g2, implicit $g3, implicit $g4, implicit $g5, implicit $g6, implicit $g7, implicit $g8, implicit $g9, implicit $g10, implicit $g11
    ; CHECK-NEXT: renamable $g0 = VLDA_GG_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $g0
    %0:mggs = COPY $g0 ; -> only $g0 is available

    $g0 = COPY $g1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $g0, implicit $g1, implicit $g2, implicit $g3, implicit $g4, implicit $g5, implicit $g6, implicit $g7, implicit $g8, implicit $g9, implicit $g10, implicit $g11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_gg_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $g0

    ; CHECK-LABEL: name: test_gg_caller_saved
    ; CHECK: liveins: $g0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_GG_SPILL $g0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $g0 = VLDA_GG_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $g0
    %0:mggs = COPY $g0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_eg_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $egl0, $r0, $p0, $eg1, $eg2, $eg3, $eg4, $eg5, $eg6, $eg7, $eg8, $eg9, $eg10, $eg11

    ; CHECK-LABEL: name: test_eg_scarce_regs
    ; CHECK: liveins: $eg1, $eg2, $eg3, $eg4, $eg5, $eg6, $eg7, $eg8, $eg9, $eg10, $eg11, $egl0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_EG_SPILL $egl0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: $eg0 = COPY $eg1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $eg0, implicit $eg1, implicit $eg2, implicit $eg3, implicit $eg4, implicit $eg5, implicit $eg6, implicit $eg7, implicit $eg8, implicit $eg9, implicit $eg10, implicit $eg11
    ; CHECK-NEXT: renamable $egl0 = VLDA_EG_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $egl0
    %0:megs = COPY $egl0 ; -> only $eg0 is available

    $eg0 = COPY $eg1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $eg0, implicit $eg1, implicit $eg2, implicit $eg3, implicit $eg4, implicit $eg5, implicit $eg6, implicit $eg7, implicit $eg8, implicit $eg9, implicit $eg10, implicit $eg11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_eg_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eg0

    ; CHECK-LABEL: name: test_eg_caller_saved
    ; CHECK: liveins: $eg0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $egl0 = COPY $eg0
    ; CHECK-NEXT: VST_EG_SPILL killed renamable $egl0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $egl0 = VLDA_EG_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $egl0
    %0:megs = COPY $eg0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_eg2_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eg0, $r0, $p0, $eg1, $eg2, $eg3, $eg4, $eg5, $eg6, $eg7, $eg8, $eg9, $eg10, $eg11

    ; CHECK-LABEL: name: test_eg2_scarce_regs
    ; CHECK: liveins: $eg0, $eg1, $eg2, $eg3, $eg4, $eg5, $eg6, $eg7, $eg8, $eg9, $eg10, $eg11, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_EG2_SPILL $eg0, %stack.0, implicit $sp :: (store (s128) into %stack.0)
    ; CHECK-NEXT: $eg0 = COPY $eg1
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $eg0, implicit $eg1, implicit $eg2, implicit $eg3, implicit $eg4, implicit $eg5, implicit $eg6, implicit $eg7, implicit $eg8, implicit $eg9, implicit $eg10, implicit $eg11
    ; CHECK-NEXT: renamable $eg0 = VLDA_EG2_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $eg0
    %0:meg2s = COPY $eg0 ; -> only $eg0 is available

    $eg0 = COPY $eg1
    ST_dms_sts_scalar_st_idx_imm $r0, $p0, 0, implicit $eg0, implicit $eg1, implicit $eg2, implicit $eg3, implicit $eg4, implicit $eg5, implicit $eg6, implicit $eg7, implicit $eg8, implicit $eg9, implicit $eg10, implicit $eg11

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_eg2_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eg0

    ; CHECK-LABEL: name: test_eg2_caller_saved
    ; CHECK: liveins: $eg0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_EG2_SPILL $eg0, %stack.0, implicit $sp :: (store (s128) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: renamable $eg0 = VLDA_EG2_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $eg0
    %0:meg2s = COPY $eg0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...
