; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: opt -S -mtriple=aie2ps -passes=loop-unroll %s -o - | FileCheck %s

; Verify that we can unroll a specific loop idiom detected in AIE2PSTargetTransformInfo

; ModuleID = 'ElemDiv.ll'

; Function Attrs: mustprogress noinline
define weak_odr dso_local void @ElemDiv(ptr noalias %ifm1, ptr noalias %ifm2, ptr noalias %ofm, ptr nonnull align 64 dereferenceable(64) %params) {
; CHECK-LABEL: define weak_odr dso_local void @ElemDiv(
; CHECK-SAME: ptr noalias [[IFM1:%.*]], ptr noalias [[IFM2:%.*]], ptr noalias [[OFM:%.*]], ptr nonnull align 64 dereferenceable(64) [[PARAMS:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PARAMS]], align 64, !tbaa [[TBAA4:![0-9]+]]
; CHECK-NEXT:    [[DIV4:%.*]] = lshr i32 [[TMP0]], 6
; CHECK-NEXT:    [[LHS_INC_I:%.*]] = getelementptr inbounds i8, ptr [[PARAMS]], i20 32
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[LHS_INC_I]], align 32, !tbaa [[TBAA11:![0-9]+]]
; CHECK-NEXT:    [[IDX_EXT_I_I:%.*]] = trunc i32 [[TMP1]] to i20
; CHECK-NEXT:    [[RHS_INC_I:%.*]] = getelementptr inbounds i8, ptr [[PARAMS]], i20 36
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[RHS_INC_I]], align 4, !tbaa [[TBAA12:![0-9]+]]
; CHECK-NEXT:    [[IDX_EXT_I14_I:%.*]] = trunc i32 [[TMP2]] to i20
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[LSR_IV38:%.*]] = phi i32 [ [[DIV4]], [[ENTRY:%.*]] ], [ [[LSR_IV_NEXT39:%.*]], [[BLOCK_EXIT:%.*]] ]
; CHECK-NEXT:    [[P_IN1_0_IN14:%.*]] = phi ptr [ [[IFM1]], [[ENTRY]] ], [ [[ADD_PTR_I_I:%.*]], [[BLOCK_EXIT]] ]
; CHECK-NEXT:    [[P_IN2_0_IN13:%.*]] = phi ptr [ [[IFM2]], [[ENTRY]] ], [ [[ADD_PTR_I15_I:%.*]], [[BLOCK_EXIT]] ]
; CHECK-NEXT:    [[P_OUT_0_IN12:%.*]] = phi ptr [ [[OFM]], [[ENTRY]] ], [ [[ADD_PTR_I17_I:%.*]], [[BLOCK_EXIT]] ]
; CHECK-NEXT:    [[P_IN1_0:%.*]] = addrspacecast ptr [[P_IN1_0_IN14]] to ptr addrspace(5)
; CHECK-NEXT:    [[P_IN2_0:%.*]] = addrspacecast ptr [[P_IN2_0_IN13]] to ptr addrspace(6)
; CHECK-NEXT:    [[TMP3:%.*]] = load <32 x bfloat>, ptr addrspace(5) [[P_IN1_0]], align 64, !tbaa [[TBAA13:![0-9]+]]
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[P_IN1_0]], i20 64
; CHECK-NEXT:    [[TMP4:%.*]] = load <32 x bfloat>, ptr addrspace(5) [[ARRAYIDX1]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[TMP5:%.*]] = load <32 x bfloat>, ptr addrspace(6) [[P_IN2_0]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds i8, ptr addrspace(6) [[P_IN2_0]], i20 64
; CHECK-NEXT:    [[TMP6:%.*]] = load <32 x bfloat>, ptr addrspace(6) [[ARRAYIDX3]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[TMP7:%.*]] = tail call noundef <32 x float> @llvm.aie2ps.v32bf16.to.v32accfloat(<32 x bfloat> [[TMP5]])
; CHECK-NEXT:    [[BC7:%.*]] = shufflevector <32 x float> [[TMP7]], <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    br label [[FOR_BODY1:%.*]]
; CHECK:       for.body1:
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <16 x float> [[BC7]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = tail call noundef float @llvm.aie2ps.inv(float [[TMP8]])
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <16 x float> [[BC7]], i32 1
; CHECK-NEXT:    [[TMP11:%.*]] = tail call noundef float @llvm.aie2ps.inv(float [[TMP10]])
; CHECK-NEXT:    [[TMP12:%.*]] = bitcast float [[TMP9]] to i32
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[TMP12]], i64 0
; CHECK-NEXT:    [[TMP14:%.*]] = bitcast float [[TMP11]] to i32
; CHECK-NEXT:    [[TMP15:%.*]] = bitcast <2 x i32> [[TMP13]] to i64
; CHECK-NEXT:    [[CONV3:%.*]] = zext i32 [[TMP14]] to i64
; CHECK-NEXT:    [[SHL6:%.*]] = shl nuw i64 [[CONV3]], 32
; CHECK-NEXT:    [[OR:%.*]] = or disjoint i64 [[SHL6]], [[TMP15]]
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast i64 [[OR]] to <2 x i32>
; CHECK-NEXT:    [[VECINIT30:%.*]] = shufflevector <2 x i32> [[TMP16]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[TMP17:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vshift.I512.I512(<16 x i32> poison, <16 x i32> [[VECINIT30]], i32 0, i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractelement <16 x float> [[BC7]], i32 2
; CHECK-NEXT:    [[TMP19:%.*]] = tail call noundef float @llvm.aie2ps.inv(float [[TMP18]])
; CHECK-NEXT:    [[TMP20:%.*]] = extractelement <16 x float> [[BC7]], i32 3
; CHECK-NEXT:    [[TMP21:%.*]] = tail call noundef float @llvm.aie2ps.inv(float [[TMP20]])
; CHECK-NEXT:    [[TMP22:%.*]] = bitcast float [[TMP19]] to i32
; CHECK-NEXT:    [[TMP23:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[TMP22]], i64 0
; CHECK-NEXT:    [[TMP24:%.*]] = bitcast float [[TMP21]] to i32
; CHECK-NEXT:    [[TMP25:%.*]] = bitcast <2 x i32> [[TMP23]] to i64
; CHECK-NEXT:    [[CONV3_1:%.*]] = zext i32 [[TMP24]] to i64
; CHECK-NEXT:    [[SHL6_1:%.*]] = shl nuw i64 [[CONV3_1]], 32
; CHECK-NEXT:    [[OR_1:%.*]] = or disjoint i64 [[SHL6_1]], [[TMP25]]
; CHECK-NEXT:    [[TMP26:%.*]] = bitcast i64 [[OR_1]] to <2 x i32>
; CHECK-NEXT:    [[VECINIT30_1:%.*]] = shufflevector <2 x i32> [[TMP26]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[TMP27:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vshift.I512.I512(<16 x i32> [[TMP17]], <16 x i32> [[VECINIT30_1]], i32 0, i32 8)
; CHECK-NEXT:    [[ADD_PTR_I_I]] = getelementptr inbounds i8, ptr [[P_IN1_0_IN14]], i20 [[IDX_EXT_I_I]]
; CHECK-NEXT:    [[TMP28:%.*]] = bitcast <16 x i32> [[TMP27]] to <16 x float>
; CHECK-NEXT:    [[TMP29:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP28]])
; CHECK-NEXT:    br label [[BLOCK_EXIT]]
; CHECK:       block.exit:
; CHECK-NEXT:    [[TMP30:%.*]] = addrspacecast ptr [[P_OUT_0_IN12]] to ptr addrspace(7)
; CHECK-NEXT:    [[ADD_PTR_I15_I]] = getelementptr inbounds i8, ptr [[P_IN2_0_IN13]], i20 [[IDX_EXT_I14_I]]
; CHECK-NEXT:    [[TMP31:%.*]] = bitcast <16 x bfloat> [[TMP29]] to <8 x i32>
; CHECK-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[TMP27]] to <16 x float>
; CHECK-NEXT:    [[TMP33:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP32]])
; CHECK-NEXT:    [[TMP34:%.*]] = bitcast <16 x bfloat> [[TMP29]] to <8 x i32>
; CHECK-NEXT:    [[SHUFFLE2:%.*]] = shufflevector <8 x i32> [[TMP31]], <8 x i32> [[TMP34]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP35:%.*]] = bitcast <16 x i32> [[SHUFFLE2]] to <32 x bfloat>
; CHECK-NEXT:    [[TMP36:%.*]] = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat> [[TMP4]], <32 x bfloat> [[TMP35]], i32 828)
; CHECK-NEXT:    [[TMP37:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float> [[TMP36]])
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(7) [[TMP30]], i20 64
; CHECK-NEXT:    [[ADD_PTR_I17_I]] = getelementptr inbounds i8, ptr [[P_OUT_0_IN12]], i20 128
; CHECK-NEXT:    [[LSR_IV_NEXT39]] = add nsw i32 [[LSR_IV38]], -1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[LSR_IV_NEXT39]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]]
;
entry:
  %0 = load i32, ptr %params, align 64, !tbaa !4
  %div4 = lshr i32 %0, 6
  %lhs_inc.i = getelementptr inbounds i8, ptr %params, i20 32
  %1 = load i32, ptr %lhs_inc.i, align 32, !tbaa !11
  %idx.ext.i.i = trunc i32 %1 to i20
  %rhs_inc.i = getelementptr inbounds i8, ptr %params, i20 36
  %2 = load i32, ptr %rhs_inc.i, align 4, !tbaa !12
  %idx.ext.i14.i = trunc i32 %2 to i20
  br label %for.body

for.cond.cleanup:                                 ; preds = %block.exit
  ret void

for.body:                                         ; preds = %block.exit, %entry
  %lsr.iv38 = phi i32 [ %div4, %entry ], [ %lsr.iv.next39, %block.exit ]
  %p_in1.0.in14 = phi ptr [ %ifm1, %entry ], [ %add.ptr.i.i, %block.exit ]
  %p_in2.0.in13 = phi ptr [ %ifm2, %entry ], [ %add.ptr.i15.i, %block.exit ]
  %p_out.0.in12 = phi ptr [ %ofm, %entry ], [ %add.ptr.i17.i, %block.exit ]
  %p_in1.0 = addrspacecast ptr %p_in1.0.in14 to ptr addrspace(5)
  %p_in2.0 = addrspacecast ptr %p_in2.0.in13 to ptr addrspace(6)
  %3 = load <32 x bfloat>, ptr addrspace(5) %p_in1.0, align 64, !tbaa !13
  %arrayidx1 = getelementptr inbounds i8, ptr addrspace(5) %p_in1.0, i20 64
  %4 = load <32 x bfloat>, ptr addrspace(5) %arrayidx1, align 64, !tbaa !13
  %5 = load <32 x bfloat>, ptr addrspace(6) %p_in2.0, align 64, !tbaa !13
  %arrayidx3 = getelementptr inbounds i8, ptr addrspace(6) %p_in2.0, i20 64
  %6 = load <32 x bfloat>, ptr addrspace(6) %arrayidx3, align 64, !tbaa !13
  %7 = tail call noundef <32 x float> @llvm.aie2ps.v32bf16.to.v32accfloat(<32 x bfloat> %5)
  %bc7 = shufflevector <32 x float> %7, <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  br label %for.body1

; Loop to be detected by TTI and unrolled.
for.body1:                   ; preds = %for.body1, %for.body
  %lsr.iv = phi i32 [ %lsr.iv.next, %for.body1 ], [ 0, %for.body ]
  %outv.sroa = phi <16 x i32> [ poison, %for.body ], [ %18, %for.body1 ]
  %8 = add i32 %lsr.iv, 1
  %9 = extractelement <16 x float> %bc7, i32 %lsr.iv
  %10 = tail call noundef float @llvm.aie2ps.inv(float %9)
  %11 = extractelement <16 x float> %bc7, i32 %8
  %12 = tail call noundef float @llvm.aie2ps.inv(float %11)
  %13 = bitcast float %10 to i32
  %14 = insertelement <2 x i32> <i32 poison, i32 0>, i32 %13, i64 0
  %15 = bitcast float %12 to i32
  %16 = bitcast <2 x i32> %14 to i64
  %conv3 = zext i32 %15 to i64
  %shl6 = shl nuw i64 %conv3, 32
  %or = or disjoint i64 %shl6, %16
  %17 = bitcast i64 %or to <2 x i32>
  %vecinit30 = shufflevector <2 x i32> %17, <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  %18 = tail call noundef <16 x i32> @llvm.aie2ps.vshift.I512.I512(<16 x i32> %outv.sroa, <16 x i32> %vecinit30, i32 0, i32 8)
  %lsr.iv.next = add nuw nsw i32 %lsr.iv, 2
  %exitcond = icmp eq i32 %lsr.iv.next, 4
  br i1 %exitcond, label %block2.exit, label %for.body1, !llvm.loop !14

block2.exit: ; preds = %for.body1
  %add.ptr.i.i = getelementptr inbounds i8, ptr %p_in1.0.in14, i20 %idx.ext.i.i
  %19 = bitcast <16 x i32> %18 to <16 x float>
  %20 = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> %19)
  %bc = shufflevector <32 x float> %7, <32 x float> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  br label %block.exit

block.exit: ; preds = %block2.exit
  %64 = addrspacecast ptr %p_out.0.in12 to ptr addrspace(7)
  %add.ptr.i15.i = getelementptr inbounds i8, ptr %p_in2.0.in13, i20 %idx.ext.i14.i
  %65 = bitcast <16 x bfloat> %20 to <8 x i32>
  %66 = bitcast <16 x i32> %18 to <16 x float>
  %67 = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> %66)
  %68 = bitcast <16 x bfloat> %20 to <8 x i32>
  %shuffle2 = shufflevector <8 x i32> %65, <8 x i32> %68, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %69 = bitcast <16 x i32> %shuffle2 to <32 x bfloat>
  %70 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat> %4, <32 x bfloat> %69, i32 828)
  %71 = tail call noundef <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float> %70)
  %arrayidx = getelementptr inbounds i8, ptr addrspace(7) %64, i20 64
  %add.ptr.i17.i = getelementptr inbounds i8, ptr %p_out.0.in12, i20 128
  %lsr.iv.next39 = add nsw i32 %lsr.iv38, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next39, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

; Function Attrs: mustprogress noinline
define weak_odr dso_local void @ElemDiv_store(ptr noalias %ifm1, ptr noalias %ifm2, ptr noalias %ofm, ptr nonnull align 64 dereferenceable(64) %params) {
; CHECK-LABEL: define weak_odr dso_local void @ElemDiv_store(
; CHECK-SAME: ptr noalias [[IFM1:%.*]], ptr noalias [[IFM2:%.*]], ptr noalias [[OFM:%.*]], ptr nonnull align 64 dereferenceable(64) [[PARAMS:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PARAMS]], align 64, !tbaa [[TBAA4]]
; CHECK-NEXT:    [[DIV4:%.*]] = lshr i32 [[TMP0]], 6
; CHECK-NEXT:    [[LHS_INC_I:%.*]] = getelementptr inbounds i8, ptr [[PARAMS]], i20 32
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[LHS_INC_I]], align 32, !tbaa [[TBAA11]]
; CHECK-NEXT:    [[IDX_EXT_I_I:%.*]] = trunc i32 [[TMP1]] to i20
; CHECK-NEXT:    [[RHS_INC_I:%.*]] = getelementptr inbounds i8, ptr [[PARAMS]], i20 36
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[RHS_INC_I]], align 4, !tbaa [[TBAA12]]
; CHECK-NEXT:    [[IDX_EXT_I14_I:%.*]] = trunc i32 [[TMP2]] to i20
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[LSR_IV38:%.*]] = phi i32 [ [[DIV4]], [[ENTRY:%.*]] ], [ [[LSR_IV_NEXT39:%.*]], [[BLOCK_EXIT:%.*]] ]
; CHECK-NEXT:    [[P_IN1_0_IN14:%.*]] = phi ptr [ [[IFM1]], [[ENTRY]] ], [ [[ADD_PTR_I_I:%.*]], [[BLOCK_EXIT]] ]
; CHECK-NEXT:    [[P_IN2_0_IN13:%.*]] = phi ptr [ [[IFM2]], [[ENTRY]] ], [ [[ADD_PTR_I15_I:%.*]], [[BLOCK_EXIT]] ]
; CHECK-NEXT:    [[P_OUT_0_IN12:%.*]] = phi ptr [ [[OFM]], [[ENTRY]] ], [ [[ADD_PTR_I17_I:%.*]], [[BLOCK_EXIT]] ]
; CHECK-NEXT:    [[P_IN1_0:%.*]] = addrspacecast ptr [[P_IN1_0_IN14]] to ptr addrspace(5)
; CHECK-NEXT:    [[P_IN2_0:%.*]] = addrspacecast ptr [[P_IN2_0_IN13]] to ptr addrspace(6)
; CHECK-NEXT:    [[TMP3:%.*]] = load <32 x bfloat>, ptr addrspace(5) [[P_IN1_0]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[P_IN1_0]], i20 64
; CHECK-NEXT:    [[TMP4:%.*]] = load <32 x bfloat>, ptr addrspace(5) [[ARRAYIDX1]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[TMP5:%.*]] = load <32 x bfloat>, ptr addrspace(6) [[P_IN2_0]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds i8, ptr addrspace(6) [[P_IN2_0]], i20 64
; CHECK-NEXT:    [[TMP6:%.*]] = load <32 x bfloat>, ptr addrspace(6) [[ARRAYIDX3]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[TMP7:%.*]] = tail call noundef <32 x float> @llvm.aie2ps.v32bf16.to.v32accfloat(<32 x bfloat> [[TMP5]])
; CHECK-NEXT:    [[BC7:%.*]] = shufflevector <32 x float> [[TMP7]], <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    br label [[FOR_BODY1:%.*]]
; CHECK:       for.body1:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i32 [ [[LSR_IV_NEXT:%.*]], [[FOR_BODY1]] ], [ 0, [[FOR_BODY]] ]
; CHECK-NEXT:    [[OUTV_SROA:%.*]] = phi <16 x i32> [ poison, [[FOR_BODY]] ], [ [[TMP18:%.*]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[LSR_IV]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <16 x float> [[BC7]], i32 [[LSR_IV]]
; CHECK-NEXT:    [[TMP10:%.*]] = tail call noundef float @llvm.aie2ps.inv(float [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <16 x float> [[BC7]], i32 [[TMP8]]
; CHECK-NEXT:    [[TMP12:%.*]] = tail call noundef float @llvm.aie2ps.inv(float [[TMP11]])
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast float [[TMP10]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[TMP13]], i64 0
; CHECK-NEXT:    [[TMP15:%.*]] = bitcast float [[TMP12]] to i32
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast <2 x i32> [[TMP14]] to i64
; CHECK-NEXT:    [[CONV3:%.*]] = zext i32 [[TMP15]] to i64
; CHECK-NEXT:    [[SHL6:%.*]] = shl nuw i64 [[CONV3]], 32
; CHECK-NEXT:    [[OR:%.*]] = or disjoint i64 [[SHL6]], [[TMP16]]
; CHECK-NEXT:    [[TMP17:%.*]] = bitcast i64 [[OR]] to <2 x i32>
; CHECK-NEXT:    [[VECINIT30:%.*]] = shufflevector <2 x i32> [[TMP17]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[TMP18]] = tail call noundef <16 x i32> @llvm.aie2ps.vshift.I512.I512(<16 x i32> [[OUTV_SROA]], <16 x i32> [[VECINIT30]], i32 0, i32 8)
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add nuw nsw i32 [[LSR_IV]], 2
; CHECK-NEXT:    store <32 x bfloat> [[TMP6]], ptr [[P_OUT_0_IN12]], align 64, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LSR_IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[BLOCK2_EXIT:%.*]], label [[FOR_BODY1]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       block2.exit:
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi <16 x i32> [ [[TMP18]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[ADD_PTR_I_I]] = getelementptr inbounds i8, ptr [[P_IN1_0_IN14]], i20 [[IDX_EXT_I_I]]
; CHECK-NEXT:    [[TMP19:%.*]] = bitcast <16 x i32> [[DOTLCSSA]] to <16 x float>
; CHECK-NEXT:    [[TMP20:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP19]])
; CHECK-NEXT:    [[BC:%.*]] = shufflevector <32 x float> [[TMP7]], <32 x float> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    br label [[BLOCK_EXIT]]
; CHECK:       block.exit:
; CHECK-NEXT:    [[TMP21:%.*]] = addrspacecast ptr [[P_OUT_0_IN12]] to ptr addrspace(7)
; CHECK-NEXT:    [[ADD_PTR_I15_I]] = getelementptr inbounds i8, ptr [[P_IN2_0_IN13]], i20 [[IDX_EXT_I14_I]]
; CHECK-NEXT:    [[TMP22:%.*]] = bitcast <16 x bfloat> [[TMP20]] to <8 x i32>
; CHECK-NEXT:    [[TMP23:%.*]] = bitcast <16 x i32> [[DOTLCSSA]] to <16 x float>
; CHECK-NEXT:    [[TMP24:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP23]])
; CHECK-NEXT:    [[TMP25:%.*]] = bitcast <16 x bfloat> [[TMP20]] to <8 x i32>
; CHECK-NEXT:    [[SHUFFLE2:%.*]] = shufflevector <8 x i32> [[TMP22]], <8 x i32> [[TMP25]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP26:%.*]] = bitcast <16 x i32> [[SHUFFLE2]] to <32 x bfloat>
; CHECK-NEXT:    [[TMP27:%.*]] = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat> [[TMP4]], <32 x bfloat> [[TMP26]], i32 828)
; CHECK-NEXT:    [[TMP28:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float> [[TMP27]])
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(7) [[TMP21]], i20 64
; CHECK-NEXT:    [[ADD_PTR_I17_I]] = getelementptr inbounds i8, ptr [[P_OUT_0_IN12]], i20 128
; CHECK-NEXT:    [[LSR_IV_NEXT39]] = add nsw i32 [[LSR_IV38]], -1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[LSR_IV_NEXT39]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]]
;
entry:
  %0 = load i32, ptr %params, align 64, !tbaa !4
  %div4 = lshr i32 %0, 6
  %lhs_inc.i = getelementptr inbounds i8, ptr %params, i20 32
  %1 = load i32, ptr %lhs_inc.i, align 32, !tbaa !11
  %idx.ext.i.i = trunc i32 %1 to i20
  %rhs_inc.i = getelementptr inbounds i8, ptr %params, i20 36
  %2 = load i32, ptr %rhs_inc.i, align 4, !tbaa !12
  %idx.ext.i14.i = trunc i32 %2 to i20
  br label %for.body

for.cond.cleanup:                                 ; preds = %block.exit
  ret void

for.body:                                         ; preds = %block.exit, %entry
  %lsr.iv38 = phi i32 [ %div4, %entry ], [ %lsr.iv.next39, %block.exit ]
  %p_in1.0.in14 = phi ptr [ %ifm1, %entry ], [ %add.ptr.i.i, %block.exit ]
  %p_in2.0.in13 = phi ptr [ %ifm2, %entry ], [ %add.ptr.i15.i, %block.exit ]
  %p_out.0.in12 = phi ptr [ %ofm, %entry ], [ %add.ptr.i17.i, %block.exit ]
  %p_in1.0 = addrspacecast ptr %p_in1.0.in14 to ptr addrspace(5)
  %p_in2.0 = addrspacecast ptr %p_in2.0.in13 to ptr addrspace(6)
  %3 = load <32 x bfloat>, ptr addrspace(5) %p_in1.0, align 64, !tbaa !13
  %arrayidx1 = getelementptr inbounds i8, ptr addrspace(5) %p_in1.0, i20 64
  %4 = load <32 x bfloat>, ptr addrspace(5) %arrayidx1, align 64, !tbaa !13
  %5 = load <32 x bfloat>, ptr addrspace(6) %p_in2.0, align 64, !tbaa !13
  %arrayidx3 = getelementptr inbounds i8, ptr addrspace(6) %p_in2.0, i20 64
  %6 = load <32 x bfloat>, ptr addrspace(6) %arrayidx3, align 64, !tbaa !13
  %7 = tail call noundef <32 x float> @llvm.aie2ps.v32bf16.to.v32accfloat(<32 x bfloat> %5)
  %bc7 = shufflevector <32 x float> %7, <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  br label %for.body1

; Loop to be detected by TTI but not unrolled because of the store.
for.body1:                   ; preds = %for.body1, %for.body
  %lsr.iv = phi i32 [ %lsr.iv.next, %for.body1 ], [ 0, %for.body ]
  %outv.sroa = phi <16 x i32> [ poison, %for.body ], [ %18, %for.body1 ]
  %8 = add i32 %lsr.iv, 1
  %9 = extractelement <16 x float> %bc7, i32 %lsr.iv
  %10 = tail call noundef float @llvm.aie2ps.inv(float %9)
  %11 = extractelement <16 x float> %bc7, i32 %8
  %12 = tail call noundef float @llvm.aie2ps.inv(float %11)
  %13 = bitcast float %10 to i32
  %14 = insertelement <2 x i32> <i32 poison, i32 0>, i32 %13, i64 0
  %15 = bitcast float %12 to i32
  %16 = bitcast <2 x i32> %14 to i64
  %conv3 = zext i32 %15 to i64
  %shl6 = shl nuw i64 %conv3, 32
  %or = or disjoint i64 %shl6, %16
  %17 = bitcast i64 %or to <2 x i32>
  %vecinit30 = shufflevector <2 x i32> %17, <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  %18 = tail call noundef <16 x i32> @llvm.aie2ps.vshift.I512.I512(<16 x i32> %outv.sroa, <16 x i32> %vecinit30, i32 0, i32 8)
  %lsr.iv.next = add nuw nsw i32 %lsr.iv, 2
  store <32 x bfloat> %6, ptr %p_out.0.in12, align 64, !tbaa !13
  %exitcond = icmp eq i32 %lsr.iv.next, 4
  br i1 %exitcond, label %block2.exit, label %for.body1, !llvm.loop !14

block2.exit: ; preds = %for.body1
  %add.ptr.i.i = getelementptr inbounds i8, ptr %p_in1.0.in14, i20 %idx.ext.i.i
  %19 = bitcast <16 x i32> %18 to <16 x float>
  %20 = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> %19)
  %bc = shufflevector <32 x float> %7, <32 x float> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  br label %block.exit

block.exit: ; preds = %block2.exit
  %64 = addrspacecast ptr %p_out.0.in12 to ptr addrspace(7)
  %add.ptr.i15.i = getelementptr inbounds i8, ptr %p_in2.0.in13, i20 %idx.ext.i14.i
  %65 = bitcast <16 x bfloat> %20 to <8 x i32>
  %66 = bitcast <16 x i32> %18 to <16 x float>
  %67 = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> %66)
  %68 = bitcast <16 x bfloat> %20 to <8 x i32>
  %shuffle2 = shufflevector <8 x i32> %65, <8 x i32> %68, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %69 = bitcast <16 x i32> %shuffle2 to <32 x bfloat>
  %70 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat> %4, <32 x bfloat> %69, i32 828)
  %71 = tail call noundef <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float> %70)
  %arrayidx = getelementptr inbounds i8, ptr addrspace(7) %64, i20 64
  %add.ptr.i17.i = getelementptr inbounds i8, ptr %p_out.0.in12, i20 128
  %lsr.iv.next39 = add nsw i32 %lsr.iv38, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next39, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}


; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat>, <32 x bfloat>, i32)

; Function Attrs: nounwind memory(none)
declare <32 x float> @llvm.aie2ps.v32bf16.to.v32accfloat(<32 x bfloat>)

; Function Attrs: nounwind memory(none)
declare float @llvm.aie2ps.inv(float)

; Function Attrs: nounwind memory(none)
declare <16 x i32> @llvm.aie2ps.vshift.I512.I512(<16 x i32>, <16 x i32>, i32, i32)

; Function Attrs: nounwind memory(inaccessiblemem: read)
declare <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float>)

; Function Attrs: nounwind memory(inaccessiblemem: read)
declare <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float>)

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 19.0.0git (/scratch/llvm-aie/clang 90bd3402b6ba6a328d84bfa0fe2fc4a06af67eca)"}
!4 = !{!5, !6, i64 0}
!5 = !{!"_ZTS27elementwise_binary_params_tI12div_params_tI8bfloat16EE", !6, i64 0, !7, i64 4, !7, i64 5, !7, i64 6, !7, i64 7, !7, i64 8, !7, i64 9, !9, i64 10, !7, i64 12, !7, i64 13, !9, i64 14, !6, i64 16, !6, i64 20, !6, i64 24, !10, i64 28, !6, i64 32, !6, i64 36}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C++ TBAA"}
!9 = !{!"short", !7, i64 0}
!10 = !{!"_ZTS12div_params_tI8bfloat16E"}
!11 = !{!5, !6, i64 32}
!12 = !{!5, !6, i64 36}
!13 = !{!7, !7, i64 0}
!14 = distinct !{!14, !15}
!15 = !{!"llvm.loop.mustprogress"}
!16 = distinct !{!16, !15}
;.
; CHECK: [[TBAA4]] = !{[[META5:![0-9]+]], [[META6:![0-9]+]], i64 0}
; CHECK: [[META5]] = !{!"_ZTS27elementwise_binary_params_tI12div_params_tI8bfloat16EE", [[META6]], i64 0, [[META7:![0-9]+]], i64 4, [[META7]], i64 5, [[META7]], i64 6, [[META7]], i64 7, [[META7]], i64 8, [[META7]], i64 9, [[META9:![0-9]+]], i64 10, [[META7]], i64 12, [[META7]], i64 13, [[META9]], i64 14, [[META6]], i64 16, [[META6]], i64 20, [[META6]], i64 24, [[META10:![0-9]+]], i64 28, [[META6]], i64 32, [[META6]], i64 36}
; CHECK: [[META6]] = !{!"int", [[META7]], i64 0}
; CHECK: [[META7]] = !{!"omnipotent char", [[META8:![0-9]+]], i64 0}
; CHECK: [[META8]] = !{!"Simple C++ TBAA"}
; CHECK: [[META9]] = !{!"short", [[META7]], i64 0}
; CHECK: [[META10]] = !{!"_ZTS12div_params_tI8bfloat16E"}
; CHECK: [[TBAA11]] = !{[[META5]], [[META6]], i64 32}
; CHECK: [[TBAA12]] = !{[[META5]], [[META6]], i64 36}
; CHECK: [[TBAA13]] = !{[[META7]], [[META7]], i64 0}
; CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META15:![0-9]+]]}
; CHECK: [[META15]] = !{!"llvm.loop.mustprogress"}
;.
