# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

# An REL followed by a load must keep the load outside the lock's core-resume
# window. Each function issues the same REL and the same load, once in a single
# block and once split by an MBB border, so the REL-to-load distance can be
# compared across the border.

#
# The *_rev_* functions cover the reverse direction: a memory op in the
# predecessor and the REL alone in the successor (isolated so it anchors at
# the successor's first cycle). The backward stall window is carried across
# the border, so the memory op is held back from the lock.
#
# The *_diamond function (where present) branches to two successors, one with a
# load and one without, so the lock's exit spacing is the max over successors.
# The *_reg_load_* function uses the register-localID lock form.
---
name:            rel_load_same_mbb
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p1, $r0
    ; CHECK-LABEL: name: rel_load_same_mbb
    ; CHECK: liveins: $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r6 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 4
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
    REL_mLockId_imm 0, $r0
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            rel_load_mbb_border
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: rel_load_mbb_border
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   REL_mLockId_imm 0, killed $r0
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r6 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 4
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1
    liveins: $p1, $r0
    REL_mLockId_imm 0, $r0
    DelayedSchedBarrier

  bb.1:
    liveins: $p1
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            load_rel_rev_same_mbb
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p1, $r0
    ; CHECK-LABEL: name: load_rel_rev_same_mbb
    ; CHECK: liveins: $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    ; CHECK-NEXT: $r7 = LDA_dms_lda_scalar_ld_idx_imm $p1, 8
    ; CHECK-NEXT: $r8 = LDA_dms_lda_scalar_ld_idx_imm $p1, 12
    ; CHECK-NEXT: $r9 = LDA_dms_lda_scalar_ld_idx_imm $p1, 16
    ; CHECK-NEXT: $r10 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 20
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    $r7 = LDA_dms_lda_scalar_ld_idx_imm $p1, 8
    $r8 = LDA_dms_lda_scalar_ld_idx_imm $p1, 12
    $r9 = LDA_dms_lda_scalar_ld_idx_imm $p1, 16
    $r10 = LDA_dms_lda_scalar_ld_idx_imm $p1, 20
    REL_mLockId_imm 0, $r0
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            load_rel_rev_mbb_border
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: load_rel_rev_mbb_border
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
  ; CHECK-NEXT:   $r7 = LDA_dms_lda_scalar_ld_idx_imm $p1, 8
  ; CHECK-NEXT:   $r8 = LDA_dms_lda_scalar_ld_idx_imm $p1, 12
  ; CHECK-NEXT:   $r9 = LDA_dms_lda_scalar_ld_idx_imm $p1, 16
  ; CHECK-NEXT:   $r10 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 20
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   REL_mLockId_imm 0, killed $r0
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1
    liveins: $p1, $r0
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    $r7 = LDA_dms_lda_scalar_ld_idx_imm $p1, 8
    $r8 = LDA_dms_lda_scalar_ld_idx_imm $p1, 12
    $r9 = LDA_dms_lda_scalar_ld_idx_imm $p1, 16
    $r10 = LDA_dms_lda_scalar_ld_idx_imm $p1, 20
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2
    liveins: $r0
    REL_mLockId_imm 0, $r0
    DelayedSchedBarrier

  bb.2:
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            rel_diamond
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: rel_diamond
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p1, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JNZ $r1, %bb.2
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   REL_mLockId_imm 0, killed $r0
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   J_lng %bb.3
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   $r6 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 4
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r7 = ADD_add_r_ri killed $r1, 1, implicit-def $srcarry
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $p1, $r0, $r1
    REL_mLockId_imm 0, $r0
    JNZ $r1, %bb.2
    DelayedSchedBarrier

  bb.1:
    successors: %bb.3
    liveins: $p1
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    J_lng %bb.3
    DelayedSchedBarrier

  bb.2:
    successors: %bb.3
    liveins: $r1
    $r7 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
    DelayedSchedBarrier

  bb.3:
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            rel_reg_load_mbb_border
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: rel_reg_load_mbb_border
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p1, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   REL_mLockId_reg killed $r0, killed $r1
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r6 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 4
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1
    liveins: $p1, $r0, $r1
    REL_mLockId_reg $r0, $r1
    DelayedSchedBarrier

  bb.1:
    liveins: $p1
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    RET implicit $lr
    DelayedSchedBarrier
...
