# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2ps -run-pass=postmisched %s -o - | FileCheck %s

# We are testing whether maxlatencyfinder deals with unscheduled blocks
# to reduce MaxLatency by looking at the possible edges
# We use a multi block loop, whose latch will find the header unscheduled
# The block holds the interesting case of a multi-output instruction, one
# with a short latency, one with a long one. The consumers are given depth
# by dependence chains

---
name:            test
alignment:       16
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r2 = ADD_alu_r_rr $r0, $r0, implicit-def $srcarry
  ; CHECK-NEXT:   JNZ $r0, %bb.3
  ; CHECK-NEXT:   $r2 = ADD_alu_r_rr killed $r2, $r2, implicit-def $srcarry
  ; CHECK-NEXT:   $r2 = ADD_alu_r_rr killed $r2, $r2, implicit-def $srcarry
  ; CHECK-NEXT:   $r2 = ADD_alu_r_rr killed $r2, $r2, implicit-def $srcarry
  ; CHECK-NEXT:   $r2 = ADD_alu_r_rr killed $r2, $r2, implicit-def $srcarry
  ; CHECK-NEXT:   BUNDLE implicit-def $p0, implicit-def $r2, implicit-def $srcarry, implicit killed $p0, implicit killed $r1 {
  ; CHECK-NEXT:     $p0 = PADDA_pstm_nrm_imm killed $p0, 4
  ; CHECK-NEXT:     $r2 = ADD_alu_r_rr killed $r1, $r1, implicit-def $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JNZ $r0, %bb.1
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $p0, implicit-def $r3, implicit-def $srcarry, implicit killed $p0, implicit $r0 {
  ; CHECK-NEXT:     $r1, $p0 = LDA_dms_lda_scalar_ld_pstm_nrm_imm killed $p0, 4
  ; CHECK-NEXT:     $r3 = ADD_alu_r_rr $r0, $r0, implicit-def $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml2, $cml3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    successors: %bb.1
    liveins:
  bb.1:
    successors: %bb.2, %bb.3
    liveins: $r0,$r1,$p0
    $p0 = PADDA_pstm_nrm_imm $p0, 4
    $r2 = ADD_alu_r_rr $r0, $r0, implicit-def $srcarry
    $r2 = ADD_alu_r_rr $r2, $r2, implicit-def $srcarry
    $r2 = ADD_alu_r_rr $r2, $r2, implicit-def $srcarry
    $r2 = ADD_alu_r_rr $r2, $r2, implicit-def $srcarry
    $r2 = ADD_alu_r_rr $r2, $r2, implicit-def $srcarry
    $r2 = ADD_alu_r_rr $r1, $r1, implicit-def $srcarry
    JNZ $r0, %bb.3
    DelayedSchedBarrier

  bb.2:
    successors: %bb.3
    liveins: $p0

  bb.3:
    successors: %bb.1, %bb.4
    liveins: $r0,$p0
    $r1, $p0 = LDA_dms_lda_scalar_ld_pstm_nrm_imm $p0, 4
    $r3 = ADD_alu_r_rr $r0, $r0, implicit-def $srcarry
    JNZ $r0, %bb.1
    DelayedSchedBarrier

  bb.4:
    liveins: $cml0, $cml1, $cml2, $cml3
    RET implicit $lr
    DelayedSchedBarrier
...
