# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2p -run-pass=prologepilog %s -o - | FileCheck --check-prefix=AIE2P %s
# RUN: llc -verify-machineinstrs --march=aie2ps -run-pass=prologepilog %s -o - | FileCheck --check-prefix=AIE2PS %s

# Note that the "offset" field in the stack slots does not matter anymore,
# as the FI operands have already been translated to raw offsets.

---
name:            test_d
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_d
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $m1 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2P-NEXT: $dn1 = LDA_dms_lda_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2P-NEXT: $dj1 = LDA_dms_lda_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2P-NEXT: $dc1 = LDA_dms_lda_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2P-NEXT: ST_dms_sts_spill $m1, -48, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2P-NEXT: ST_dms_sts_spill $dn1, -44, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj1, -40, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2P-NEXT: ST_dms_sts_spill $dc1, -36, implicit $sp :: (store (s32) into %stack.1 + 12)
    ;
    ; AIE2PS-LABEL: name: test_d
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $m1 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2PS-NEXT: $dn1 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2PS-NEXT: $dj1 = LDA_dms_lda_scalar_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2PS-NEXT: $dc1 = LDA_dms_lda_scalar_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $m1, -48, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dn1, -44, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj1, -40, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dc1, -36, implicit $sp :: (store (s32) into %stack.1 + 12)
    $d1 = LDA_D_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0, align 4)
    ST_D_SPILL $d1, %stack.1, implicit $sp :: (store (s128) into %stack.1, align 4)
...

# Only some lanes are liveout/livein when reloading/spilling. Make sure no
# unnecessary instructions are generated.
---
name:            test_d_partial
tracksRegLiveness: true
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_d_partial
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $dj1 = LDA_dms_lda_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2P-NEXT: $dj2 = COPY $dj1
    ; AIE2P-NEXT: ST_dms_sts_spill $dj2, -40, implicit $sp :: (store (s32) into %stack.1 + 8)
    ;
    ; AIE2PS-LABEL: name: test_d_partial
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $dj1 = LDA_dms_lda_scalar_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2PS-NEXT: $dj2 = COPY $dj1
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj2, -40, implicit $sp :: (store (s32) into %stack.1 + 8)
    $d1 = LDA_D_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0, align 4)
    $dj2 = COPY $dj1
    ST_D_SPILL $d2, %stack.1, implicit $sp :: (store (s128) into %stack.1, align 4)
...

# No reg liveness is tracked, all spill instructions are generated.
---
name:            test_d_partial_notrack
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_d_partial_notrack
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $m1 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2P-NEXT: $dn1 = LDA_dms_lda_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2P-NEXT: $dj1 = LDA_dms_lda_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2P-NEXT: $dc1 = LDA_dms_lda_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2P-NEXT: $dj2 = COPY $dj1
    ; AIE2P-NEXT: ST_dms_sts_spill $m2, -48, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2P-NEXT: ST_dms_sts_spill $dn2, -44, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj2, -40, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2P-NEXT: ST_dms_sts_spill $dc2, -36, implicit $sp :: (store (s32) into %stack.1 + 12)
    ;
    ; AIE2PS-LABEL: name: test_d_partial_notrack
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $m1 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2PS-NEXT: $dn1 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2PS-NEXT: $dj1 = LDA_dms_lda_scalar_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2PS-NEXT: $dc1 = LDA_dms_lda_scalar_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2PS-NEXT: $dj2 = COPY $dj1
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $m2, -48, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dn2, -44, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj2, -40, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dc2, -36, implicit $sp :: (store (s32) into %stack.1 + 12)
    $d1 = LDA_D_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0, align 4)
    $dj2 = COPY $dj1
    ST_D_SPILL $d2, %stack.1, implicit $sp :: (store (s128) into %stack.1, align 4)
...

# The load/stores are ordered (here, volatile) and cannot be removed.
# Make sure the right undef attributes are added.
---
name:            test_d_volatile
tracksRegLiveness: true
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_d_volatile
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $m1 = LDA_dms_lda_spill -64, implicit $sp :: (volatile load (s32) from %stack.0)
    ; AIE2P-NEXT: $dn1 = LDA_dms_lda_spill -60, implicit $sp :: (volatile load (s32) from %stack.0 + 4)
    ; AIE2P-NEXT: $dj1 = LDA_dms_lda_spill -56, implicit $sp :: (volatile load (s32) from %stack.0 + 8)
    ; AIE2P-NEXT: $dc1 = LDA_dms_lda_spill -52, implicit $sp :: (volatile load (s32) from %stack.0 + 12)
    ; AIE2P-NEXT: $dj2 = COPY $dj1
    ; AIE2P-NEXT: ST_dms_sts_spill undef $m2, -48, implicit $sp :: (volatile store (s32) into %stack.1)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $dn2, -44, implicit $sp :: (volatile store (s32) into %stack.1 + 4)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj2, -40, implicit $sp :: (volatile store (s32) into %stack.1 + 8)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $dc2, -36, implicit $sp :: (volatile store (s32) into %stack.1 + 12)
    ;
    ; AIE2PS-LABEL: name: test_d_volatile
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $m1 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (volatile load (s32) from %stack.0)
    ; AIE2PS-NEXT: $dn1 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (volatile load (s32) from %stack.0 + 4)
    ; AIE2PS-NEXT: $dj1 = LDA_dms_lda_scalar_spill -56, implicit $sp :: (volatile load (s32) from %stack.0 + 8)
    ; AIE2PS-NEXT: $dc1 = LDA_dms_lda_scalar_spill -52, implicit $sp :: (volatile load (s32) from %stack.0 + 12)
    ; AIE2PS-NEXT: $dj2 = COPY $dj1
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $m2, -48, implicit $sp :: (volatile store (s32) into %stack.1)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $dn2, -44, implicit $sp :: (volatile store (s32) into %stack.1 + 4)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj2, -40, implicit $sp :: (volatile store (s32) into %stack.1 + 8)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $dc2, -36, implicit $sp :: (volatile store (s32) into %stack.1 + 12)
    $d1 = LDA_D_SPILL %stack.0, implicit $sp :: (volatile load (s128) from %stack.0, align 4)
    $dj2 = COPY $dj1
    ST_D_SPILL $d2, %stack.1, implicit $sp :: (volatile store (s128) into %stack.1, align 4)
...

---
name:            test_ds
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_ds
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $m1 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2P-NEXT: $dn1 = LDA_dms_lda_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2P-NEXT: $dj1 = LDA_dms_lda_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2P-NEXT: $dc1 = LDA_dms_lda_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2P-NEXT: $m5 = LDA_dms_lda_spill -48, implicit $sp :: (load (s32) from %stack.0 + 16)
    ; AIE2P-NEXT: $dn5 = LDA_dms_lda_spill -44, implicit $sp :: (load (s32) from %stack.0 + 20)
    ; AIE2P-NEXT: $dj5 = LDA_dms_lda_spill -40, implicit $sp :: (load (s32) from %stack.0 + 24)
    ; AIE2P-NEXT: $dc5 = LDA_dms_lda_spill -36, implicit $sp :: (load (s32) from %stack.0 + 28)
    ; AIE2P-NEXT: ST_dms_sts_spill $m1, -32, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2P-NEXT: ST_dms_sts_spill $dn1, -28, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj1, -24, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2P-NEXT: ST_dms_sts_spill $dc1, -20, implicit $sp :: (store (s32) into %stack.1 + 12)
    ; AIE2P-NEXT: ST_dms_sts_spill $m5, -16, implicit $sp :: (store (s32) into %stack.1 + 16)
    ; AIE2P-NEXT: ST_dms_sts_spill $dn5, -12, implicit $sp :: (store (s32) into %stack.1 + 20)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj5, -8, implicit $sp :: (store (s32) into %stack.1 + 24)
    ; AIE2P-NEXT: ST_dms_sts_spill $dc5, -4, implicit $sp :: (store (s32) into %stack.1 + 28)
    ;
    ; AIE2PS-LABEL: name: test_ds
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $m1 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2PS-NEXT: $dn1 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2PS-NEXT: $dj1 = LDA_dms_lda_scalar_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2PS-NEXT: $dc1 = LDA_dms_lda_scalar_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2PS-NEXT: $m5 = LDA_dms_lda_scalar_spill -48, implicit $sp :: (load (s32) from %stack.0 + 16)
    ; AIE2PS-NEXT: $dn5 = LDA_dms_lda_scalar_spill -44, implicit $sp :: (load (s32) from %stack.0 + 20)
    ; AIE2PS-NEXT: $dj5 = LDA_dms_lda_scalar_spill -40, implicit $sp :: (load (s32) from %stack.0 + 24)
    ; AIE2PS-NEXT: $dc5 = LDA_dms_lda_scalar_spill -36, implicit $sp :: (load (s32) from %stack.0 + 28)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $m1, -32, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dn1, -28, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj1, -24, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dc1, -20, implicit $sp :: (store (s32) into %stack.1 + 12)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $m5, -16, implicit $sp :: (store (s32) into %stack.1 + 16)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dn5, -12, implicit $sp :: (store (s32) into %stack.1 + 20)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj5, -8, implicit $sp :: (store (s32) into %stack.1 + 24)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dc5, -4, implicit $sp :: (store (s32) into %stack.1 + 28)
    $d1_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
    ST_DS_SPILL $d1_3d, %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
...

# Only some lanes are liveout/livein when reloading/spilling. Make sure no
# unnecessary instructions are generated.
---
name:            test_ds_partial
tracksRegLiveness: true
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_ds_partial
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $dj5 = LDA_dms_lda_spill -40, implicit $sp :: (load (s32) from %stack.0 + 24)
    ; AIE2P-NEXT: $dj6 = COPY $dj5
    ; AIE2P-NEXT: ST_dms_sts_spill $dj6, -8, implicit $sp :: (store (s32) into %stack.1 + 24)
    ;
    ; AIE2PS-LABEL: name: test_ds_partial
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $dj5 = LDA_dms_lda_scalar_spill -40, implicit $sp :: (load (s32) from %stack.0 + 24)
    ; AIE2PS-NEXT: $dj6 = COPY $dj5
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj6, -8, implicit $sp :: (store (s32) into %stack.1 + 24)
    $d1_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
    $dj6 = COPY $dj5
    ST_DS_SPILL $d2_3d, %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
...

# No reg liveness is tracked, all spill instructions are generated.
---
name:            test_ds_partial_notrack
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_ds_partial_notrack
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $m1 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2P-NEXT: $dn1 = LDA_dms_lda_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2P-NEXT: $dj1 = LDA_dms_lda_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2P-NEXT: $dc1 = LDA_dms_lda_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2P-NEXT: $m5 = LDA_dms_lda_spill -48, implicit $sp :: (load (s32) from %stack.0 + 16)
    ; AIE2P-NEXT: $dn5 = LDA_dms_lda_spill -44, implicit $sp :: (load (s32) from %stack.0 + 20)
    ; AIE2P-NEXT: $dj5 = LDA_dms_lda_spill -40, implicit $sp :: (load (s32) from %stack.0 + 24)
    ; AIE2P-NEXT: $dc5 = LDA_dms_lda_spill -36, implicit $sp :: (load (s32) from %stack.0 + 28)
    ; AIE2P-NEXT: $dj6 = COPY $dj5
    ; AIE2P-NEXT: ST_dms_sts_spill $m2, -32, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2P-NEXT: ST_dms_sts_spill $dn2, -28, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj2, -24, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2P-NEXT: ST_dms_sts_spill $dc2, -20, implicit $sp :: (store (s32) into %stack.1 + 12)
    ; AIE2P-NEXT: ST_dms_sts_spill $m6, -16, implicit $sp :: (store (s32) into %stack.1 + 16)
    ; AIE2P-NEXT: ST_dms_sts_spill $dn6, -12, implicit $sp :: (store (s32) into %stack.1 + 20)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj6, -8, implicit $sp :: (store (s32) into %stack.1 + 24)
    ; AIE2P-NEXT: ST_dms_sts_spill $dc6, -4, implicit $sp :: (store (s32) into %stack.1 + 28)
    ;
    ; AIE2PS-LABEL: name: test_ds_partial_notrack
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $m1 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2PS-NEXT: $dn1 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.0 + 4)
    ; AIE2PS-NEXT: $dj1 = LDA_dms_lda_scalar_spill -56, implicit $sp :: (load (s32) from %stack.0 + 8)
    ; AIE2PS-NEXT: $dc1 = LDA_dms_lda_scalar_spill -52, implicit $sp :: (load (s32) from %stack.0 + 12)
    ; AIE2PS-NEXT: $m5 = LDA_dms_lda_scalar_spill -48, implicit $sp :: (load (s32) from %stack.0 + 16)
    ; AIE2PS-NEXT: $dn5 = LDA_dms_lda_scalar_spill -44, implicit $sp :: (load (s32) from %stack.0 + 20)
    ; AIE2PS-NEXT: $dj5 = LDA_dms_lda_scalar_spill -40, implicit $sp :: (load (s32) from %stack.0 + 24)
    ; AIE2PS-NEXT: $dc5 = LDA_dms_lda_scalar_spill -36, implicit $sp :: (load (s32) from %stack.0 + 28)
    ; AIE2PS-NEXT: $dj6 = COPY $dj5
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $m2, -32, implicit $sp :: (store (s32) into %stack.1)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dn2, -28, implicit $sp :: (store (s32) into %stack.1 + 4)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj2, -24, implicit $sp :: (store (s32) into %stack.1 + 8)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dc2, -20, implicit $sp :: (store (s32) into %stack.1 + 12)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $m6, -16, implicit $sp :: (store (s32) into %stack.1 + 16)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dn6, -12, implicit $sp :: (store (s32) into %stack.1 + 20)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj6, -8, implicit $sp :: (store (s32) into %stack.1 + 24)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dc6, -4, implicit $sp :: (store (s32) into %stack.1 + 28)
    $d1_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
    $dj6 = COPY $dj5
    ST_DS_SPILL $d2_3d, %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
...

# The load/stores are ordered (here, volatile) and cannot be removed.
# Make sure the right undef attributes are added.
---
name:            test_ds_volatile
tracksRegLiveness: true
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; AIE2P-LABEL: name: test_ds_volatile
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $m1 = LDA_dms_lda_spill -64, implicit $sp :: (volatile load (s32) from %stack.0)
    ; AIE2P-NEXT: $dn1 = LDA_dms_lda_spill -60, implicit $sp :: (volatile load (s32) from %stack.0 + 4)
    ; AIE2P-NEXT: $dj1 = LDA_dms_lda_spill -56, implicit $sp :: (volatile load (s32) from %stack.0 + 8)
    ; AIE2P-NEXT: $dc1 = LDA_dms_lda_spill -52, implicit $sp :: (volatile load (s32) from %stack.0 + 12)
    ; AIE2P-NEXT: $m5 = LDA_dms_lda_spill -48, implicit $sp :: (volatile load (s32) from %stack.0 + 16)
    ; AIE2P-NEXT: $dn5 = LDA_dms_lda_spill -44, implicit $sp :: (volatile load (s32) from %stack.0 + 20)
    ; AIE2P-NEXT: $dj5 = LDA_dms_lda_spill -40, implicit $sp :: (volatile load (s32) from %stack.0 + 24)
    ; AIE2P-NEXT: $dc5 = LDA_dms_lda_spill -36, implicit $sp :: (volatile load (s32) from %stack.0 + 28)
    ; AIE2P-NEXT: $dj6 = COPY $dj5
    ; AIE2P-NEXT: ST_dms_sts_spill undef $m2, -32, implicit $sp :: (volatile store (s32) into %stack.1)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $dn2, -28, implicit $sp :: (volatile store (s32) into %stack.1 + 4)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $dj2, -24, implicit $sp :: (volatile store (s32) into %stack.1 + 8)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $dc2, -20, implicit $sp :: (volatile store (s32) into %stack.1 + 12)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $m6, -16, implicit $sp :: (volatile store (s32) into %stack.1 + 16)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $dn6, -12, implicit $sp :: (volatile store (s32) into %stack.1 + 20)
    ; AIE2P-NEXT: ST_dms_sts_spill $dj6, -8, implicit $sp :: (volatile store (s32) into %stack.1 + 24)
    ; AIE2P-NEXT: ST_dms_sts_spill undef $dc6, -4, implicit $sp :: (volatile store (s32) into %stack.1 + 28)
    ;
    ; AIE2PS-LABEL: name: test_ds_volatile
    ; AIE2PS: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: $m1 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (volatile load (s32) from %stack.0)
    ; AIE2PS-NEXT: $dn1 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (volatile load (s32) from %stack.0 + 4)
    ; AIE2PS-NEXT: $dj1 = LDA_dms_lda_scalar_spill -56, implicit $sp :: (volatile load (s32) from %stack.0 + 8)
    ; AIE2PS-NEXT: $dc1 = LDA_dms_lda_scalar_spill -52, implicit $sp :: (volatile load (s32) from %stack.0 + 12)
    ; AIE2PS-NEXT: $m5 = LDA_dms_lda_scalar_spill -48, implicit $sp :: (volatile load (s32) from %stack.0 + 16)
    ; AIE2PS-NEXT: $dn5 = LDA_dms_lda_scalar_spill -44, implicit $sp :: (volatile load (s32) from %stack.0 + 20)
    ; AIE2PS-NEXT: $dj5 = LDA_dms_lda_scalar_spill -40, implicit $sp :: (volatile load (s32) from %stack.0 + 24)
    ; AIE2PS-NEXT: $dc5 = LDA_dms_lda_scalar_spill -36, implicit $sp :: (volatile load (s32) from %stack.0 + 28)
    ; AIE2PS-NEXT: $dj6 = COPY $dj5
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $m2, -32, implicit $sp :: (volatile store (s32) into %stack.1)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $dn2, -28, implicit $sp :: (volatile store (s32) into %stack.1 + 4)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $dj2, -24, implicit $sp :: (volatile store (s32) into %stack.1 + 8)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $dc2, -20, implicit $sp :: (volatile store (s32) into %stack.1 + 12)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $m6, -16, implicit $sp :: (volatile store (s32) into %stack.1 + 16)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $dn6, -12, implicit $sp :: (volatile store (s32) into %stack.1 + 20)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill $dj6, -8, implicit $sp :: (volatile store (s32) into %stack.1 + 24)
    ; AIE2PS-NEXT: ST_dms_sts_scalar_spill undef $dc6, -4, implicit $sp :: (volatile store (s32) into %stack.1 + 28)
    $d1_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (volatile load (s256) from %stack.0, align 4)
    $dj6 = COPY $dj5
    ST_DS_SPILL $d2_3d, %stack.1, implicit $sp :: (volatile store (s256) into %stack.1, align 4)
...
