# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple=aie2p --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s --check-prefix=AIE2P

# There is only one eDJ (MOD) register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.

# %0 isn't used by "real" instructions directly, greedy assumes the reg class
# would not benefit from enlarging, and prefers spilling.
---
  name:            spill_to_mem
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7

    ; AIE2-LABEL: name: spill_to_mem
    ; AIE2: liveins: $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: ST_dms_spill $dj0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; AIE2-NEXT: $dj0 = COPY $dj1
    ; AIE2-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7
    ; AIE2-NEXT: renamable $dj0 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit killed renamable $dj0
    ;
    ; AIE2P-LABEL: name: spill_to_mem
    ; AIE2P: liveins: $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: ST_dms_sts_spill $dj0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; AIE2P-NEXT: $dj0 = COPY $dj1
    ; AIE2P-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7
    ; AIE2P-NEXT: renamable $dj0 = LDA_dms_lda_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit killed renamable $dj0
      %0:edj = COPY $dj0 ; -> only $dj0 is available

      $dj0 = COPY $dj1
      ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7

      PseudoRET implicit $lr, implicit %0
...

# %0 is used by "real" instructions, but those impose no strict constraints
# on the current reg class. Greedy prefers spilling, because splitting is
# "similar to spilling", only without the extra COPY instructions.
---
  name:            spill_to_mem2
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7

    ; AIE2-LABEL: name: spill_to_mem2
    ; AIE2: liveins: $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: renamable $dj0 = LDA_dms_lda_idx_imm $p0, 0
    ; AIE2-NEXT: ST_dms_spill killed renamable $dj0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; AIE2-NEXT: $dj0 = COPY $dj1
    ; AIE2-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7
    ; AIE2-NEXT: renamable $dj0 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2-NEXT: ST_dms_sts_idx_imm killed renamable $dj0, $p0, 4
    ;
    ; AIE2P-LABEL: name: spill_to_mem2
    ; AIE2P: liveins: $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: renamable $dj0 = LDA_dms_lda_idx_imm $p0, 0
    ; AIE2P-NEXT: ST_dms_sts_spill killed renamable $dj0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; AIE2P-NEXT: $dj0 = COPY $dj1
    ; AIE2P-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7
    ; AIE2P-NEXT: renamable $dj0 = LDA_dms_lda_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; AIE2P-NEXT: ST_dms_sts_idx_imm killed renamable $dj0, $p0, 4
      %0:edj_as_32bit = LDA_dms_lda_idx_imm $p0, 0 ; -> only $dj0 is available

      $dj0 = COPY $dj1
      ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7

      ST_dms_sts_idx_imm %0, $p0, 4
...

# %0 is used by a real/non-COPY instruction that has a constrained class
# compared to spill_eDJ_to_eR. Here, greedy favors splitting over spilling.
---
  name:            spill_to_reg
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $r0, $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7

    ; AIE2-LABEL: name: spill_to_reg
    ; AIE2: liveins: $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $p0, $r0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: renamable $r1 = COPY $dj0
    ; AIE2-NEXT: $dj0 = COPY $dj1
    ; AIE2-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7
    ; AIE2-NEXT: renamable $dj0 = COPY killed renamable $r1
    ; AIE2-NEXT: ST_dms_sts_idx $r0, $p0, killed renamable $dj0
    ;
    ; AIE2P-LABEL: name: spill_to_reg
    ; AIE2P: liveins: $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $p0, $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: renamable $r1 = COPY $dj0
    ; AIE2P-NEXT: $dj0 = COPY $dj1
    ; AIE2P-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7
    ; AIE2P-NEXT: renamable $dj0 = COPY killed renamable $r1
    ; AIE2P-NEXT: ST_dms_sts_idx $r0, $p0, killed renamable $dj0
      %0:edj = COPY $dj0 ; -> only $dj0 is available

      $dj0 = COPY $dj1
      ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7

      ST_dms_sts_idx $r0, $p0, %0
...
