# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# Independent OLP epilogues may reuse a replacement physical register when
# their candidate live ranges do not overlap.
# RUN: llc -mtriple=aie2ps --aie-olp-war-rename \
# RUN:   --aie-enable-epilogue-reg-rewrite --start-before=greedy \
# RUN:   --stop-after=virtregrewriter %s -o - | FileCheck %s

---
name:            independent_olp_epilogues
alignment:       16
legalized:       true
isSSA:           false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: independent_olp_epilogues
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x0 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $x2 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $r8 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $dm1 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $dm0 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $dm2 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $r5 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $r1 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $r7 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $r3 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $r1, $r3, $r5, $r7, $r8, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $r1, $r3, $r5, $r7, $r8, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJNZ renamable $r5, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.4(0x04000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $r1, $r3, $r5, $r7, $r8, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead renamable $dm1 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm1, renamable $x0, renamable $x2, renamable $r8
  ; CHECK-NEXT:   renamable $dm3 = VMAC_vmac_vmul_cm_core_X_X renamable $dm0, renamable $x0, renamable $x2, renamable $r8
  ; CHECK-NEXT:   renamable $dm1 = COPY killed renamable $dm3
  ; CHECK-NEXT:   PseudoJNZ renamable $r7, %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $r1, $r3, $r8, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.5(0x7c000000), %bb.6(0x04000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $r1, $r3, $r8, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJNZ renamable $r1, %bb.5
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.4(0x7c000000), %bb.7(0x04000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $r1, $r3, $r8, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead renamable $dm2 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm2, renamable $x0, renamable $x2, renamable $r8
  ; CHECK-NEXT:   renamable $dm3 = VMAC_vmac_vmul_cm_core_X_X renamable $dm0, renamable $x0, renamable $x2, renamable $r8
  ; CHECK-NEXT:   renamable $dm2 = COPY killed renamable $dm3
  ; CHECK-NEXT:   PseudoJNZ renamable $r3, %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $r8, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead renamable $dm1 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm1, renamable $x0, renamable $x2, renamable $r8
  ; CHECK-NEXT:   dead renamable $dm1 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm2, renamable $x0, renamable $x2, renamable $r8
  ; CHECK-NEXT:   dead renamable $dm0 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm0, killed renamable $x0, killed renamable $x2, killed renamable $r8
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    %0:vec512 = IMPLICIT_DEF
    %1:vec512 = IMPLICIT_DEF
    %2:mrv8 = IMPLICIT_DEF
    %3:acc2048 = IMPLICIT_DEF
    %4:acc2048 = IMPLICIT_DEF
    %5:acc2048 = IMPLICIT_DEF
    %6:er = IMPLICIT_DEF
    %7:er = IMPLICIT_DEF
    %8:er = IMPLICIT_DEF
    %9:er = IMPLICIT_DEF
    PseudoJ_jump_imm %bb.1

  ; First OLP prologue.
  bb.1:
    successors: %bb.2
    PseudoJ_jump_imm %bb.2

  ; First OLP steady state.
  bb.2:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    PseudoJNZ %6, %bb.2
    PseudoJ_jump_imm %bb.3

  ; First OLP epilogue.
  bb.3:
    successors: %bb.1(0x7c000000), %bb.4(0x04000000)
    dead %10:acc2048 = VMAC_vmac_vmul_cm_core_X_X %3, %0, %1, %2
    %3:acc2048 = VMAC_vmac_vmul_cm_core_X_X %4, %0, %1, %2
    PseudoJNZ %8, %bb.1
    PseudoJ_jump_imm %bb.4

  ; Second OLP prologue.
  bb.4:
    successors: %bb.5
    PseudoJ_jump_imm %bb.5

  ; Second OLP steady state.
  bb.5:
    successors: %bb.5(0x7c000000), %bb.6(0x04000000)
    PseudoJNZ %7, %bb.5
    PseudoJ_jump_imm %bb.6

  ; Second OLP epilogue.
  bb.6:
    successors: %bb.4(0x7c000000), %bb.7(0x04000000)
    dead %11:acc2048 = VMAC_vmac_vmul_cm_core_X_X %5, %0, %1, %2
    %5:acc2048 = VMAC_vmac_vmul_cm_core_X_X %4, %0, %1, %2
    PseudoJNZ %9, %bb.4
    PseudoJ_jump_imm %bb.7

  bb.7:
    dead %12:acc2048 = VMAC_vmac_vmul_cm_core_X_X %3, %0, %1, %2
    dead %13:acc2048 = VMAC_vmac_vmul_cm_core_X_X %5, %0, %1, %2
    dead %14:acc2048 = VMAC_vmac_vmul_cm_core_X_X %4, %0, %1, %2
    PseudoRET implicit $lr
...
