# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# A definition that also reads its old value cannot be renamed: the repair
# copy is inserted only after the instruction has executed.
# RUN: llc -mtriple=aie2ps --aie-olp-war-rename \
# RUN:   --aie-enable-epilogue-reg-rewrite --start-before=greedy \
# RUN:   --stop-after=aie-epilogue-reg-rewriter %s -o - | FileCheck %s

---
name:            reject_same_instruction_use_and_def
alignment:       16
legalized:       true
isSSA:           false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: reject_same_instruction_use_and_def
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:mrv8 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:acc2048 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:er = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF5:%[0-9]+]]:er = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJNZ [[DEF4]], %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.4(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_X_X [[DEF3]], [[DEF]], [[DEF1]], [[DEF2]]
  ; CHECK-NEXT:   PseudoJNZ [[DEF5]], %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit [[DEF3]]
  bb.0:
    successors: %bb.1
    %0:vec512 = IMPLICIT_DEF
    %1:vec512 = IMPLICIT_DEF
    %2:mrv8 = IMPLICIT_DEF
    %3:acc2048 = IMPLICIT_DEF
    %4:er = IMPLICIT_DEF
    %5:er = IMPLICIT_DEF
    PseudoJ_jump_imm %bb.1

  ; OLP prologue and outer-loop header.
  bb.1:
    successors: %bb.2
    PseudoJ_jump_imm %bb.2

  ; OLP steady-state inner loop.
  bb.2:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    PseudoJNZ %4, %bb.2
    PseudoJ_jump_imm %bb.3

  ; OLP epilogue and outer-loop latch.
  bb.3:
    successors: %bb.1(0x7c000000), %bb.4(0x04000000)
    %3:acc2048 = VMAC_vmac_vmul_cm_core_X_X %3, %0, %1, %2
    PseudoJNZ %5, %bb.1
    PseudoJ_jump_imm %bb.4

  bb.4:
    PseudoRET implicit $lr, implicit %3
...
