; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; Trampoline MBBs from splitting the cold critical edge of a diamond whose
; cold-arm PHI incoming is poison. PHI elimination materializes the poison as
; an IMPLICIT_DEF in the trampoline.
;
; @removable_trampoline: the cold arm passes the pointer unchanged, so the
; trampoline holds only the IMPLICIT_DEF and a coalescable copy. Once the
; IMPLICIT_DEF is hoisted into the predecessor, the trampoline is branch-only
; and folded away.
;
; @required_trampoline: the cold arm advances the pointer by 64; this real
; work must execute only on the cold edge, so the trampoline stays.
;
; @no_trampoline: no pointer PHI, no critical edge: the IMPLICIT_DEF lands in
; the entry block.
;
; RUN: llc -mtriple=aie2ps -stop-after=phi-node-elimination %s -o - \
; RUN:   | FileCheck %s

target triple = "aie2ps-none-unknown-elf"

define <16 x i32> @removable_trampoline(i1 %cond, ptr addrspace(6) %p) {
  ; CHECK-LABEL: name: removable_trampoline
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:mlockid_reg = COPY killed $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY killed $p0
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:mlockid_reg = XOR killed [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:mlockid_reg = AND killed [[XOR]], killed [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJZ killed [[AND]], %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ep = COPY killed [[COPY1]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.hot:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVXM_lng_cg:%[0-9]+]]:em_as_32bit = MOVXM_lng_cg 1024
  ; CHECK-NEXT:   [[VLD_x_pstm_nrm_pseudo:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_pseudo1:%[0-9]+]]:ep = VLD_x_pstm_nrm_pseudo killed [[COPY1]], killed [[MOVXM_lng_cg]] :: (load (<16 x s32>) from %ir.p, addrspace 6)
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ep = COPY killed [[VLD_x_pstm_nrm_pseudo1]]
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vec512 = COPY killed [[VLD_x_pstm_nrm_pseudo]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.join:
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:vec512 = COPY killed [[DEF]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:ep = COPY killed [[COPY2]]
  ; CHECK-NEXT:   [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo killed [[COPY4]], 0 :: (load (<16 x s32>) from %ir.ptr, addrspace 6)
  ; CHECK-NEXT:   [[VADD_32_:%[0-9]+]]:vec512 = VADD_32 killed [[COPY3]], killed [[VLD_x_idx_imm_pseudo]], implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   $x0 = COPY killed [[VADD_32_]]
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $x0
entry:
  br i1 %cond, label %hot, label %join

hot:
  %loaded = load <16 x i32>, ptr addrspace(6) %p
  %p_hot = getelementptr i8, ptr addrspace(6) %p, i32 1024
  br label %join

join:
  %ptr = phi ptr addrspace(6) [ %p, %entry ], [ %p_hot, %hot ]
  %acc = phi <16 x i32> [ poison, %entry ], [ %loaded, %hot ]
  %tail = load <16 x i32>, ptr addrspace(6) %ptr
  %res = add <16 x i32> %acc, %tail
  ret <16 x i32> %res
}

define <16 x i32> @required_trampoline(i1 %cond, ptr addrspace(6) %p) {
  ; CHECK-LABEL: name: required_trampoline
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:mlockid_reg = COPY killed $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY killed $p0
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:mlockid_reg = XOR killed [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:mlockid_reg = AND killed [[XOR]], killed [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJZ killed [[AND]], %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo killed [[COPY1]], 64
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ep = COPY killed [[PADD_imm_pseudo]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.hot:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (load (<16 x s32>) from %ir.p_adj, addrspace 6)
  ; CHECK-NEXT:   [[MOVXM_lng_cg:%[0-9]+]]:em_as_32bit = MOVXM_lng_cg 1088
  ; CHECK-NEXT:   [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo killed [[COPY1]], killed [[MOVXM_lng_cg]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ep = COPY killed [[PADD_mod_pseudo]]
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vec512 = COPY killed [[VLD_x_idx_imm_pseudo]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.join:
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:vec512 = COPY killed [[DEF]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:ep = COPY killed [[COPY2]]
  ; CHECK-NEXT:   [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo killed [[COPY4]], 0 :: (load (<16 x s32>) from %ir.ptr, addrspace 6)
  ; CHECK-NEXT:   [[VADD_32_:%[0-9]+]]:vec512 = VADD_32 killed [[COPY3]], killed [[VLD_x_idx_imm_pseudo1]], implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   $x0 = COPY killed [[VADD_32_]]
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $x0
entry:
  %p_adj = getelementptr i8, ptr addrspace(6) %p, i32 64
  br i1 %cond, label %hot, label %join

hot:
  %loaded = load <16 x i32>, ptr addrspace(6) %p_adj
  %p_hot = getelementptr i8, ptr addrspace(6) %p_adj, i32 1024
  br label %join

join:
  %ptr = phi ptr addrspace(6) [ %p_adj, %entry ], [ %p_hot, %hot ]
  %acc = phi <16 x i32> [ poison, %entry ], [ %loaded, %hot ]
  %tail = load <16 x i32>, ptr addrspace(6) %ptr
  %res = add <16 x i32> %acc, %tail
  ret <16 x i32> %res
}

define <16 x i32> @no_trampoline(i1 %cond, ptr addrspace(6) %p) {
  ; CHECK-LABEL: name: no_trampoline
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:mlockid_reg = COPY killed $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY killed $p0
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:mlockid_reg = XOR killed [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:mlockid_reg = AND killed [[XOR]], killed [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ killed [[AND]], %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.hot:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (load (<16 x s32>) from %ir.p, addrspace 6)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vec512 = COPY killed [[VLD_x_idx_imm_pseudo]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.join:
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:vec512 = COPY killed [[DEF]]
  ; CHECK-NEXT:   [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo killed [[COPY1]], 0 :: (load (<16 x s32>) from %ir.p, addrspace 6)
  ; CHECK-NEXT:   [[VADD_32_:%[0-9]+]]:vec512 = VADD_32 killed [[COPY2]], killed [[VLD_x_idx_imm_pseudo1]], implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   $x0 = COPY killed [[VADD_32_]]
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $x0
entry:
  br i1 %cond, label %hot, label %join

hot:
  %loaded = load <16 x i32>, ptr addrspace(6) %p
  br label %join

join:
  %acc = phi <16 x i32> [ poison, %entry ], [ %loaded, %hot ]
  %tail = load <16 x i32>, ptr addrspace(6) %p
  %res = add <16 x i32> %acc, %tail
  ret <16 x i32> %res
}
