# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2ps -verify-machineinstrs --start-before=greedy --stop-after=virtregrewriter %s -o - | FileCheck %s

---
# 10 live eCML: 4 mem spills.
name:            spill_acc_overflow_to_cmh
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: spill_acc_overflow_to_cmh
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r13, $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.1, implicit $sp :: (store (s1024) into %stack.1, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.2, implicit $sp :: (store (s1024) into %stack.2, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.3, implicit $sp :: (store (s1024) into %stack.3, align 64)
  ; CHECK-NEXT:   renamable $cml4 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml5 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml6 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml7 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml1 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml4, $cml5, $cml6, $cml7, $r13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $cml2 = VLDA_CM_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.1, implicit $sp :: (load (s1024) from %stack.1, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.2, implicit $sp :: (load (s1024) from %stack.2, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.3, implicit $sp :: (load (s1024) from %stack.3, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml4, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml5, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml6, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml7, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml0, $r13
  ; CHECK-NEXT:   dead renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml1, $r13
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1, $r13

    %0:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %1:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %2:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %3:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %4:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %5:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %6:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %7:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %8:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %9:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13

  bb.1:
    successors: %bb.1(0x80000000)
    liveins: $r13

    %10:ecml = VADD_vacc_half %0, %1, $r13
    %11:ecml = VADD_vacc_half %10, %2, $r13
    %12:ecml = VADD_vacc_half %11, %3, $r13
    %13:ecml = VADD_vacc_half %12, %4, $r13
    %14:ecml = VADD_vacc_half %13, %5, $r13
    %15:ecml = VADD_vacc_half %14, %6, $r13
    %16:ecml = VADD_vacc_half %15, %7, $r13
    %17:ecml = VADD_vacc_half %16, %8, $r13
    %18:ecml = VADD_vacc_half %17, %9, $r13
    PseudoJ_jump_imm %bb.1
...

# 12 spills.
---
name:            spill_acc_exhaust_to_memory
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: spill_acc_exhaust_to_memory
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r13, $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.1, implicit $sp :: (store (s1024) into %stack.1, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.2, implicit $sp :: (store (s1024) into %stack.2, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.3, implicit $sp :: (store (s1024) into %stack.3, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.4, implicit $sp :: (store (s1024) into %stack.4, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.5, implicit $sp :: (store (s1024) into %stack.5, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.6, implicit $sp :: (store (s1024) into %stack.6, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.7, implicit $sp :: (store (s1024) into %stack.7, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.8, implicit $sp :: (store (s1024) into %stack.8, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.9, implicit $sp :: (store (s1024) into %stack.9, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.10, implicit $sp :: (store (s1024) into %stack.10, align 64)
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   VST_CM_SPILL killed renamable $cml0, %stack.11, implicit $sp :: (store (s1024) into %stack.11, align 64)
  ; CHECK-NEXT:   renamable $cml4 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml5 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml6 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml7 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml0 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT:   renamable $cml1 = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml4, $cml5, $cml6, $cml7, $r13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $cml2 = VLDA_CM_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.1, implicit $sp :: (load (s1024) from %stack.1, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.2, implicit $sp :: (load (s1024) from %stack.2, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.3, implicit $sp :: (load (s1024) from %stack.3, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.4, implicit $sp :: (load (s1024) from %stack.4, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.5, implicit $sp :: (load (s1024) from %stack.5, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.6, implicit $sp :: (load (s1024) from %stack.6, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.7, implicit $sp :: (load (s1024) from %stack.7, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.8, implicit $sp :: (load (s1024) from %stack.8, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.9, implicit $sp :: (load (s1024) from %stack.9, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.10, implicit $sp :: (load (s1024) from %stack.10, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml3 = VLDA_CM_SPILL %stack.11, implicit $sp :: (load (s1024) from %stack.11, align 64)
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, killed renamable $cml3, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml4, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml5, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml6, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml7, $r13
  ; CHECK-NEXT:   renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml0, $r13
  ; CHECK-NEXT:   dead renamable $cml2 = VADD_vacc_half killed renamable $cml2, renamable $cml1, $r13
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1, $r13

    %0:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %1:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %2:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %3:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %4:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %5:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %6:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %7:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %8:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %9:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %10:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %11:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %12:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %13:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %14:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %15:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %16:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13
    %17:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X $x0, $x1, $r13

  bb.1:
    successors: %bb.1(0x80000000)
    liveins: $r13

    %18:ecml = VADD_vacc_half %0, %1, $r13
    %19:ecml = VADD_vacc_half %18, %2, $r13
    %20:ecml = VADD_vacc_half %19, %3, $r13
    %21:ecml = VADD_vacc_half %20, %4, $r13
    %22:ecml = VADD_vacc_half %21, %5, $r13
    %23:ecml = VADD_vacc_half %22, %6, $r13
    %24:ecml = VADD_vacc_half %23, %7, $r13
    %25:ecml = VADD_vacc_half %24, %8, $r13
    %26:ecml = VADD_vacc_half %25, %9, $r13
    %27:ecml = VADD_vacc_half %26, %10, $r13
    %28:ecml = VADD_vacc_half %27, %11, $r13
    %29:ecml = VADD_vacc_half %28, %12, $r13
    %30:ecml = VADD_vacc_half %29, %13, $r13
    %31:ecml = VADD_vacc_half %30, %14, $r13
    %32:ecml = VADD_vacc_half %31, %15, $r13
    %33:ecml = VADD_vacc_half %32, %16, $r13
    %34:ecml = VADD_vacc_half %33, %17, $r13
    PseudoJ_jump_imm %bb.1

...
