# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -O2 -mtriple=aie2ps -verify-machineinstrs -run-pass=aie-split-instrs-replace %s -o - | FileCheck %s

# TEST COVERAGE STRATEGY:
# =======================
# This file tests the AIE split instruction REPLACEMENT phase, which converts
# _split pseudo instructions back to their original forms by merging sub-registers.
#
# COVERAGE: 15/185 instructions (8.1%) - Representative Sampling Approach
#
# This file uses REPRESENTATIVE SAMPLING rather than exhaustive coverage because:
# 1. The replacement mechanism is generic across instruction categories
# 2. Testing 1-2 instructions per opidx category validates the mechanism works
# 3. Exhaustive coverage would add ~170 more tests with diminishing returns
# 4. The companion file split-instrs-create.mir has 100% coverage (185/185)
#
# TESTED INSTRUCTIONS (15 total):
# 2D Instructions (9):
#   - opidx=3: PADDA_2D, PADDB_2D, PADDS_2D
#   - opidx=4: LDA_2D_dms_lda_scalar, VLDA_2D_dmw_lda_w, ST_2D_dms_sts_g, ST_2D_dmv_sts_f
#   - opidx=5: VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0
#   - opidx=8: VLD_POP_512_2D_pseudo
#
# 3D Instructions (6):
#   - opidx=4: PADDA_3D, PADDB_3D, PADDS_3D
#   - opidx=5: LDA_3D_dms_lda_scalar
#   - opidx=6: VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0
#   - opidx=9: VLD_POP_512_3D_pseudo
#
# NON-TESTED INSTRUCTIONS (170 total):
# These instructions are not tested here but ARE tested in split-instrs-create.mir:
#
# 2D opidx=4 (44 instructions): Most load/store variants including:
#   LDA_2D_dml_lda_scalar_L/F, LDA_2D_dml_lda2_scalar_*, LDA_2D_dmv_lda_*,
#   LDA_2D_s16/s8/u16/u8, LDA_TM_2D, VLDA_2D_128, VLDA_2D_CONV_*, VLDA_2D_dmx_lda_*,
#   VLDB_2D_*, VLD_2D_*_pseudo, ST_2D_*, VST_2D_128_*, VST_2D_CONV_*, VST_2D_PACK_*,
#   VST_2D_dmw/dmx_sts_*
#
# 2D opidx=5 (17 instructions): UPS/SRS variants:
#   VLDA_2D_UPS_* (7 variants), VST_2D_CONV_bf8/fp8_fp32, VST_2D_SRS_* (8 variants)
#
# 2D opidx=8 (16 instructions): POP/FLUSH variants:
#   VLDB/VLDA_POP_2D_dmx_*, VLD_POP_640/768_2D_pseudo, VLDB/VLDA_POP_s_2D,
#   VLDB/VLDA_POP_mx4_2D, VLD_POP_mx4/s_2D_pseudo, VST_FLUSH_2D, VST_FLUSH_d_2D
#
# 3D opidx=4 (1 instruction): PADD_3D_pseudo
#
# 3D opidx=5 (53 instructions): Most load/store variants (similar to 2D)
#
# 3D opidx=6 (17 instructions): UPS/SRS variants (similar to 2D but for 3D)
#
# 3D opidx=9 (16 instructions): POP/FLUSH variants (similar to 2D but for 3D)
#
# VALIDATION STRATEGY:
# The combination of split-instrs-create.mir (100% coverage) and this file
# (representative sampling) provides complete validation:
# - split-instrs-create.mir: Validates ALL instructions can be split correctly
# - split-instrs-replace.mir: Validates the replacement mechanism works for each category
# =======================


---
name:            PADDA_2D_unused_livein
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $dc4, $dj4, $dn4, $m4, $p0, $r0

    ; CHECK-LABEL: name: PADDA_2D_unused_livein
    ; CHECK: liveins: $d4:0x0000000040001C00, $dc4, $dj4, $dn4, $m4, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m4 = COPY $r0
    ; CHECK-NEXT: $p0, $dc4 = PADDA_2D killed $p0, $d4
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
    renamable $m4 = COPY $r0
    $p0, $dc4 = PADDA_2D_split killed $p0, killed $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
...

# Verify how liveins are rewritten when the sub-regs are defined in different
# BBs. Currently, we only update liveins in the the "use MBB".
---
name:            PADDA_2D_sources_in_multi_bb
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: PADDA_2D_sources_in_multi_bb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2, $r3, $r4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $m4 = COPY $r0
  ; CHECK-NEXT:   renamable $dn4 = COPY $r1
  ; CHECK-NEXT:   renamable $dc4 = COPY $r3
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r4, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $m4, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $r2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $m4, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $dc4
  ; CHECK-NEXT:   renamable $dc4 = COPY killed renamable $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $d4:0x0000000040001C00, $dc4, $dj4, $dn4, $m4, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p0, $dc4 = PADDA_2D killed $p0, $d4
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
  bb.0.entry:
    successors: %bb.2, %bb.1
    liveins: $p0, $r0, $r1, $r2, $r3, $r4

    renamable $m4 = COPY $r0
    renamable $dn4 = COPY $r1
    renamable $dc4 = COPY $r3
    PseudoJNZ killed renamable $r4, %bb.2

  bb.1:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $m4, $p0
    renamable $dj4 = COPY killed renamable $r2
    PseudoJ_jump_imm %bb.3

  bb.2:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $m4, $p0
    renamable $dj4 = COPY killed renamable $dc4
    renamable $dc4 = COPY killed renamable $r2

  bb.3:
    liveins: $dc4, $dj4, $dn4, $m4, $p0
    $p0, $dc4 = PADDA_2D_split killed $p0, killed $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
...

# Verify how liveins are rewritten when the sub-regs are defined in different
# BBs. Currently, we only update liveins in the the "use MBB".
---
name:            PADDA_3D_sources_in_multi_bb
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: PADDA_3D_sources_in_multi_bb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2, $r3, $r4, $m0, $dn0, $dj0, $dc0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dn4 = COPY $r1
  ; CHECK-NEXT:   renamable $dc4 = COPY $r3
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r4, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $r2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $dc4
  ; CHECK-NEXT:   renamable $dc4 = COPY killed renamable $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $dc0, $dc4, $dj0, $dj4, $dn0, $dn4, $m0, $p0, $d0_3d:0x3800000040001C00
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p0, $dc0, $dc4 = PADDA_3D killed $p0, $d0_3d
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
  bb.0.entry:
    successors: %bb.2, %bb.1
    liveins: $p0, $r0, $r1, $r2, $r3, $r4, $m0, $dn0, $dj0, $dc0
    renamable $dn4 = COPY $r1
    renamable $dc4 = COPY $r3
    PseudoJNZ killed renamable $r4, %bb.2

  bb.1:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
    renamable $dj4 = COPY killed renamable $r2
    PseudoJ_jump_imm %bb.3

  bb.2:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
    renamable $dj4 = COPY killed renamable $dc4
    renamable $dc4 = COPY killed renamable $r2

  bb.3:
    liveins: $dc4, $dj4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
    $p0, $dc0, $dc4 = PADDA_3D_split killed $p0, killed $m0, killed $dn0, killed $dj0, killed $dc0, killed undef $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
...

---
name:            test_split_2D_opIdx3
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $dc4, $dj4, $dn4, $m4, $p0, $r0

    ; CHECK-LABEL: name: test_split_2D_opIdx3
    ; CHECK: liveins: $d4:0x0000000040001C00, $dc4, $dj4, $dn4, $m4, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p0, $dc4 = PADDA_2D killed $p0, $d4
    ; CHECK-NEXT: $p0, $dc4 = PADDB_2D killed $p0, $d4
    ; CHECK-NEXT: $p0, $dc4 = PADDS_2D killed $p0, $d4
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
    $p0, $dc4 = PADDA_2D_split killed $p0, $m4, $dn4, $dj4, killed $dc4
    $p0, $dc4 = PADDB_2D_split killed $p0, $m4, $dn4, $dj4, killed $dc4
    $p0, $dc4 = PADDS_2D_split killed $p0, killed $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
...

---
name:            test_split_2D_opIdx4
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d1, $p0

    ; CHECK-LABEL: name: test_split_2D_opIdx4
    ; CHECK: liveins: $d1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r4, $p0, $dc1 = LDA_2D_dms_lda_scalar killed $p0, $d1
    ; CHECK-NEXT: $wl0, dead $p0, dead $dc1 = VLDA_2D_dmw_lda_w killed $p0, $d1
    $r4, $p0, $dc1 = LDA_2D_dms_lda_scalar_split killed $p0, $m1, $dn1, $dj1, $dc1
    $wl0, dead $p0, dead $dc1 = VLDA_2D_dmw_lda_w_split killed $p0, $m1, $dn1, $dj1, $dc1
...

---
name:            test_split_2D_opIdx5
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d1, $p0, $s0

    ; CHECK-LABEL: name: test_split_2D_opIdx5
    ; CHECK: liveins: $d1, $p0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $bmhh0, dead $p0, dead $dc1 = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s0, killed $p0, $d1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $bmhh0, dead $p0, dead $dc1 = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_split $s0, killed $p0, $m1, $dn1, $dj1, $dc1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0

...

---
name:            test_split_2D_opIdx8
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: test_split_2D_opIdx8
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m0 = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dn0 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p1, 0 :: (load (s20), align 4)
    ; CHECK-NEXT: renamable $r24 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dj0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dc0 = COPY renamable $dn0
    ; CHECK-NEXT: $x0, dead $p0, dead $lf0, dead $r24, dead $dc0 = VLD_POP_512_2D_pseudo killed $p0, undef $lf0, $r24, $d0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $x0
    renamable $m0 = MOV_PD_imm11_pseudo 0
    renamable $dn0 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p1, 0 :: (load (s20), align 4)
    renamable $r24 = MOV_RLC_imm11_pseudo 0
    renamable $dj0 = COPY renamable $m0
    renamable $dc0 = COPY renamable $dn0
    $x0, dead $p0, dead $lf0, dead $r24, dead $dc0 = VLD_POP_512_2D_pseudo_split killed $p0, undef $lf0, $r24, killed $m0, killed $dn0, killed $dj0, killed $dc0, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit killed renamable $x0
...

---
name:            test_split_3D_opIdx4
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $dc4, $dj4, $dn4, $p0, $m0, $dn0, $dj0, $dc0

    ; CHECK-LABEL: name: test_split_3D_opIdx4
    ; CHECK: liveins: $dc0, $dc4, $dj0, $dj4, $dn0, $dn4, $m0, $p0, $d0_3d:0x3800000040001C00
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p0, $dc0, $dc4 = PADDA_3D killed $p0, $d0_3d
    ; CHECK-NEXT: $p0, $dc0, $dc4 = PADDB_3D killed $p0, $d0_3d
    ; CHECK-NEXT: $p0, $dc0, $dc4 = PADDS_3D killed $p0, $d0_3d
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
    $p0, $dc0, $dc4 = PADDA_3D_split killed $p0, $m0, $dn0, $dj0, $dc0, undef $m4, $dn4, $dj4, $dc4
    $p0, $dc0, $dc4 = PADDB_3D_split killed $p0, $m0, $dn0, $dj0, $dc0, undef $m4, $dn4, $dj4, $dc4
    $p0, $dc0, $dc4 = PADDS_3D_split killed $p0, killed $m0, killed $dn0, killed $dj0, killed $dc0, killed undef $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
...

---
name:            test_split_3D_opIdx5
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d1_3d

    ; CHECK-LABEL: name: test_split_3D_opIdx5
    ; CHECK: liveins: $p0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r4, dead $p0, dead $dc1, dead $dc5 = LDA_3D_dms_lda_scalar killed $p0, $d1_3d
    $r4, dead $p0, dead $dc1, dead $dc5 = LDA_3D_dms_lda_scalar_split killed $p0, $m1, $dn1, $dj1, $dc1, undef $m5, $dn5, $dj5, $dc5
...

---
name:            test_split_3D_opIdx6
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $s0, $d1_3d

    ; CHECK-LABEL: name: test_split_3D_opIdx6
    ; CHECK: liveins: $p0, $s0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $dm0, dead $p0, dead $dc1, dead $dc5 = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0 $s0, killed $p0, $d1_3d, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    dead $dm0, dead $p0, dead $dc1, dead $dc5 = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0_split $s0, killed $p0, $m1, $dn1, $dj1, $dc1, undef $m5, $dn5, $dj5, $dc5, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0

...

---
name:            test_split_3D_opIdx9
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_split_3D_opIdx9
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m0 = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dj4 = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: renamable $r24 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dj0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dn0 = COPY renamable $dj4
    ; CHECK-NEXT: renamable $dc0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dc4 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dn4 = COPY renamable $dn0
    ; CHECK-NEXT: $x0, dead $p0, dead $lf0, dead $r24, dead $dc0, dead $dc4 = VLD_POP_512_3D_pseudo killed $p0, undef $lf0, $r24, $d0_3d
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $x0
    renamable $m0 = MOV_PD_imm11_pseudo 0
    renamable $dj4 = MOV_PD_imm11_pseudo 128
    renamable $r24 = MOV_RLC_imm11_pseudo 0
    renamable $dj0 = COPY renamable $m0
    renamable $dn0 = COPY renamable $dj4
    renamable $dc0 = COPY renamable $m0
    renamable $dc4 = COPY renamable $m0
    renamable $dn4 = COPY renamable $dn0
    $x0, dead $p0, dead $lf0, dead $r24, dead $dc0, dead $dc4 = VLD_POP_512_3D_pseudo_split killed $p0, undef $lf0, $r24, killed $m0, killed $dn0, killed $dj0, killed $dc0, undef $m4, killed $dn4, killed $dj4, killed $dc4, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit killed renamable $x0
...
