# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -O2 -mtriple=aie2ps -verify-machineinstrs -run-pass=aie-split-instrs-create %s -o - | FileCheck %s

# Verify that instructions are successfully rewritten into _split instructions
# that expose sub-registers.

---
name:            test_split_2D_opIdx3
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1
    ; CHECK-LABEL: name: test_split_2D_opIdx3
    ; CHECK: liveins: $p0, $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = PADDA_2D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = PADDB_2D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = PADDS_2D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:ed = PADD_2D_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    %20:ep = COPY $p0
    %100:ed = COPY $d1
    %20:ep, %100.sub_dim_count:ed = PADDA_2D killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = PADDB_2D killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = PADDS_2D killed %20, killed %100
    dead %20:ep, dead %100.sub_dim_count:ed = PADD_2D_pseudo killed %20, killed %100
...

---
name:            test_split_2D_opIdx4
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1
    ; CHECK-LABEL: name: test_split_2D_opIdx4
    ; CHECK: liveins: $p0, $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: $r4, [[COPY]]:ep, [[COPY1]].sub_dim_count:ed = LDA_2D_dms_lda_scalar_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: $wl0, [[COPY]]:ep, [[COPY1]].sub_dim_count:ed = VLDA_2D_dmw_lda_w_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dms_lda_g_split:%[0-9]+]]:mga, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dms_lda_g_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dmv_lda_f_split:%[0-9]+]]:mffa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dmv_lda_f_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = ST_2D_dms_sts_g_split [[LDA_2D_dms_lda_g_split]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:ed = ST_2D_dmv_sts_f_split [[LDA_2D_dmv_lda_f_split]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    %20:ep = COPY $p0
    %100:ed = COPY $d1
    $r4, %20:ep, %100.sub_dim_count:ed = LDA_2D_dms_lda_scalar killed %20, killed %100
    $wl0, %20:ep, %100.sub_dim_count:ed = VLDA_2D_dmw_lda_w killed %20, killed %100
    %30:mga, %20:ep, %100.sub_dim_count:ed = LDA_2D_dms_lda_g killed %20, killed %100
    %40:mffa, %20:ep, %100.sub_dim_count:ed = LDA_2D_dmv_lda_f killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = ST_2D_dms_sts_g %30, killed %20, killed %100
    dead %20:ep, dead %100.sub_dim_count:ed = ST_2D_dmv_sts_f %40, killed %20, killed %100
...

---
name:            test_split_2D_opIdx4_loads_comprehensive
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1
    ; CHECK-LABEL: name: test_split_2D_opIdx4_loads_comprehensive
    ; CHECK: liveins: $p0, $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[LDA_2D_dml_lda_scalar_L_split:%[0-9]+]]:el, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dml_lda_scalar_L_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dml_lda_scalar_F_split:%[0-9]+]]:mfa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dml_lda_scalar_F_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dml_lda2_scalar_EE_split:%[0-9]+]]:meea, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dml_lda2_scalar_EE_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dml_lda2_scalar_EG_split:%[0-9]+]]:mega, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dml_lda2_scalar_EG_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dml_lda2_scalar_GG_split:%[0-9]+]]:mgga, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dml_lda2_scalar_GG_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dmv_lda_feg_split:%[0-9]+]]:mfega, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dmv_lda_feg_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_dmv_lda_eg2_split:%[0-9]+]]:meg2a, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_dmv_lda_eg2_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_s16_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_s16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_s8_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_s8_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_u16_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_u16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_2D_u8_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_2D_u8_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[LDA_TM_2D_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = LDA_TM_2D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDA_2D_128_split:%[0-9]+]]:mwa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_128_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDA_2D_CONV_fp32_bf16_dmw_lda_ups_bf16_split:%[0-9]+]]:mbma, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_CONV_fp32_bf16_dmw_lda_ups_bf16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_f16_split:%[0-9]+]]:mcma, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_f16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDA_2D_CONV_fp32_fp16_split:%[0-9]+]]:mcma, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_CONV_fp32_fp16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDA_2D_dmw_lda_feg2_split:%[0-9]+]]:mfeg2a, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_dmw_lda_feg2_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDA_2D_dmx_lda_bm_split:%[0-9]+]]:mbm_ld, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_dmx_lda_bm_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDA_2D_dmx_lda_x_split:%[0-9]+]]:mxa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_dmx_lda_x_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDB_2D_128_split:%[0-9]+]]:mwb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDB_2D_128_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign0_split:%[0-9]+]]:mxb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign0_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1_split:%[0-9]+]]:mxb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: [[VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign0_split:%[0-9]+]]:ey, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign0_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1_split:%[0-9]+]]:ey, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: [[VLDB_2D_dmw_ldb_split:%[0-9]+]]:mwb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDB_2D_dmw_ldb_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLDB_2D_dmx_ldb_x_split:%[0-9]+]]:mxb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDB_2D_dmx_ldb_x_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLD_2D_128_pseudo_split:%[0-9]+]]:mwa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLD_2D_128_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[VLD_2D_w_pseudo_split:%[0-9]+]]:vec256, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLD_2D_w_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: dead [[VLD_2D_x_pseudo_split:%[0-9]+]]:vec512, dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:ed = VLD_2D_x_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    %20:ep = COPY $p0
    %100:ed = COPY $d1
    %1:el, %20:ep, %100.sub_dim_count:ed = LDA_2D_dml_lda_scalar_L killed %20, killed %100
    %2:mfa, %20:ep, %100.sub_dim_count:ed = LDA_2D_dml_lda_scalar_F killed %20, killed %100
    %3:meea, %20:ep, %100.sub_dim_count:ed = LDA_2D_dml_lda2_scalar_EE killed %20, killed %100
    %4:mega, %20:ep, %100.sub_dim_count:ed = LDA_2D_dml_lda2_scalar_EG killed %20, killed %100
    %5:mgga, %20:ep, %100.sub_dim_count:ed = LDA_2D_dml_lda2_scalar_GG killed %20, killed %100
    %6:mfega, %20:ep, %100.sub_dim_count:ed = LDA_2D_dmv_lda_feg killed %20, killed %100
    %7:meg2a, %20:ep, %100.sub_dim_count:ed = LDA_2D_dmv_lda_eg2 killed %20, killed %100
    %8:mra, %20:ep, %100.sub_dim_count:ed = LDA_2D_s16 killed %20, killed %100
    %9:mra, %20:ep, %100.sub_dim_count:ed = LDA_2D_s8 killed %20, killed %100
    %10:mra, %20:ep, %100.sub_dim_count:ed = LDA_2D_u16 killed %20, killed %100
    %11:mra, %20:ep, %100.sub_dim_count:ed = LDA_2D_u8 killed %20, killed %100
    %12:mra, %20:ep, %100.sub_dim_count:ed = LDA_TM_2D killed %20, killed %100
    %13:mwa, %20:ep, %100.sub_dim_count:ed = VLDA_2D_128 killed %20, killed %100
    %14:mbma, %20:ep, %100.sub_dim_count:ed = VLDA_2D_CONV_fp32_bf16_dmw_lda_ups_bf16 killed %20, killed %100
    %15:mcma, %20:ep, %100.sub_dim_count:ed = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_f16 killed %20, killed %100
    %16:mcma, %20:ep, %100.sub_dim_count:ed = VLDA_2D_CONV_fp32_fp16 killed %20, killed %100
    %17:mfeg2a, %20:ep, %100.sub_dim_count:ed = VLDA_2D_dmw_lda_feg2 killed %20, killed %100
    %18:mbm_ld, %20:ep, %100.sub_dim_count:ed = VLDA_2D_dmx_lda_bm killed %20, killed %100
    %19:mxa, %20:ep, %100.sub_dim_count:ed = VLDA_2D_dmx_lda_x killed %20, killed %100
    %21:mwb, %20:ep, %100.sub_dim_count:ed = VLDB_2D_128 killed %20, killed %100
    %22:mxb, %20:ep, %100.sub_dim_count:ed = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign0 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign0
    %23:mxb, %20:ep, %100.sub_dim_count:ed = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign1
    %24:ey, %20:ep, %100.sub_dim_count:ed = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign0 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign0
    %25:ey, %20:ep, %100.sub_dim_count:ed = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign1
    %26:mwb, %20:ep, %100.sub_dim_count:ed = VLDB_2D_dmw_ldb killed %20, killed %100
    %27:mxb, %20:ep, %100.sub_dim_count:ed = VLDB_2D_dmx_ldb_x killed %20, killed %100
    %28:mwa, %20:ep, %100.sub_dim_count:ed = VLD_2D_128_pseudo killed %20, killed %100
    %29:vec256, %20:ep, %100.sub_dim_count:ed = VLD_2D_w_pseudo killed %20, killed %100
    dead %30:vec512, dead %20:ep, dead %100.sub_dim_count:ed = VLD_2D_x_pseudo killed %20, killed %100
...

---
name:            test_split_2D_opIdx4_stores_comprehensive
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1, $eg0, $x0, $y0, $feg2, $x8, $r4, $bmhh0, $bmhh1, $cml0, $l0
    ; CHECK-LABEL: name: test_split_2D_opIdx4_stores_comprehensive
    ; CHECK: liveins: $p0, $d1, $eg0, $x0, $y0, $feg2, $x8, $r4, $bmhh0, $bmhh1, $cml0, $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:meg2s = COPY $eg0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mfegs = COPY $fegl0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mws_128b = COPY $wl0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mbms = COPY $bmhh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mcms = COPY $cml0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mxs = COPY $x0
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ey = COPY $y0
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mfeg2s = COPY $feg2
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mws = COPY $wl1
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mbms_v16w32 = COPY $bmhh1
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mxs_split = COPY $x8
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mrs = COPY $r4
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = ST_2D_dml_sts_scalar_split [[COPY2]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = ST_2D_dms_sts_scalar_split [[COPY3]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = ST_2D_s16_split [[COPY15]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = ST_2D_s8_split [[COPY15]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = ST_TM_2D_split [[COPY15]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_128_dmv_sts_eg_split [[COPY4]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_128_dmv_sts_feg_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_128_dmv_sts_w_split [[COPY6]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16_split [[COPY7]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16_split [[COPY8]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_fp16_fp32_split [[COPY8]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmw_sts_pack_packSign0_split [[COPY9]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmw_sts_pack_packSign1_split [[COPY9]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmx_sts_pack_packSign0_split [[COPY10]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmx_sts_pack_packSign1_split [[COPY10]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_dmw_sts_feg2_split [[COPY11]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_dmw_sts_w_split [[COPY12]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_dmx_sts_bm_split [[COPY13]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_dmx_sts_x_split [[COPY14]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count
    %20:ep = COPY $p0
    %100:ed = COPY $d1
    %1:el = COPY $l0
    %2:er = COPY $r4
    %3:meg2s = COPY $eg0
    %4:mfegs = COPY $fegl0
    %5:mws_128b = COPY $wl0
    %6:mbms = COPY $bmhh0
    %7:mcms = COPY $cml0
    %8:mxs = COPY $x0
    %9:ey = COPY $y0
    %10:mfeg2s = COPY $feg2
    %11:mws = COPY $wl1
    %12:mbms_v16w32 = COPY $bmhh1
    %13:mxs_split = COPY $x8
    %14:mrs = COPY $r4
    %20:ep, %100.sub_dim_count:ed = ST_2D_dml_sts_scalar %1, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = ST_2D_dms_sts_scalar %2, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = ST_2D_s16 %14, killed %20, killed %100, implicit-def $pe2_ads, implicit $pe2_ads
    %20:ep, %100.sub_dim_count:ed = ST_2D_s8 %14, killed %20, killed %100, implicit-def $pe2_ads, implicit $pe2_ads
    %20:ep, %100.sub_dim_count:ed = ST_TM_2D %14, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = VST_2D_128_dmv_sts_eg %3, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = VST_2D_128_dmv_sts_feg %4, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = VST_2D_128_dmv_sts_w %5, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16 %6, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16 %7, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:ed = VST_2D_CONV_fp16_fp32 %7, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:ed = VST_2D_PACK_dmw_sts_pack_packSign0 %8, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %20:ep, %100.sub_dim_count:ed = VST_2D_PACK_dmw_sts_pack_packSign1 %8, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign1
    %20:ep, %100.sub_dim_count:ed = VST_2D_PACK_dmx_sts_pack_packSign0 %9, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %20:ep, %100.sub_dim_count:ed = VST_2D_PACK_dmx_sts_pack_packSign1 %9, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign1
    %20:ep, %100.sub_dim_count:ed = VST_2D_dmw_sts_feg2 %10, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = VST_2D_dmw_sts_w %11, killed %20, killed %100
    %20:ep, %100.sub_dim_count:ed = VST_2D_dmx_sts_bm %12, killed %20, killed %100
    dead %20:ep, dead %100.sub_dim_count:ed = VST_2D_dmx_sts_x %13, killed %20, killed %100
...

---
name:            test_split_2D_opIdx5
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1, $s0, $cml0, $bmhh0
    ; CHECK-LABEL: name: test_split_2D_opIdx5
    ; CHECK: liveins: $p0, $d1, $s0, $cml0, $bmhh0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mbmm = COPY $bmhh0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mcmm = COPY $cml0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:edm = COPY $dm0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_split:%[0-9]+]]:mbmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_split:%[0-9]+]]:mbmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_split:%[0-9]+]]:edm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_split:%[0-9]+]]:edm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf8_fp32_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_fp8_fp32_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0_split [[COPY2]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1_split [[COPY2]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0_split [[COPY4]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1_split [[COPY4]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep = COPY $p0
    %100:ed = COPY $d1
    %1:mbmm = COPY $bmhh0
    %2:mcmm = COPY $cml0
    %3:edm = COPY $dm0
    %4:es = COPY $s0
    %5:mbmm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %6:mbmm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %7:mcmm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %8:mcmm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %9:mcmm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %10:mcmm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %11:edm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %12:edm, %20:ep, %100.sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %20:ep, %100.sub_dim_count:ed = VST_2D_CONV_bf8_fp32 %2, %4, killed %20, killed %100, implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:ed = VST_2D_CONV_fp8_fp32 %2, %4, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0 %1, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %20:ep, %100.sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1 %1, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep, %100.sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %20:ep, %100.sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep, %100.sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0 %3, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %20:ep, %100.sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1 %3, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep, %100.sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    dead %20:ep, dead %100.sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
...

---
name:            test_split_2D_opIdx8
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: test_split_2D_opIdx8
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:ed = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:ed = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (load (s20), align 4)
    ; CHECK-NEXT: undef [[COPY1:%[0-9]+]].sub_ptr:epsrfldf = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]].sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:ed = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = COPY [[MOV_PD_imm11_pseudo]].sub_dim_size
    ; CHECK-NEXT: [[VLD_POP_512_2D_pseudo_split:%[0-9]+]]:vec512, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLD_POP_512_2D_pseudo_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_2D_pseudo_split]]
    %2:ep = COPY $p1
    undef %13.sub_mod:ed = MOV_PD_imm11_pseudo 0
    %13.sub_dim_size:ed = LDA_dms_lda_scalar_ld_idx_imm %2, 0 :: (load (s20), align 4)
    undef %16.sub_ptr:epsrfldf = COPY $p0
    %16.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %13.sub_dim_stride:ed = COPY %13.sub_mod
    %13.sub_dim_count:ed = COPY %13.sub_dim_size
    %7:vec512, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLD_POP_512_2D_pseudo %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %7
...

---
name:            test_split_2D_opIdx8_mx4
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: test_split_2D_opIdx8_mx4
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:ed = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:ed = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (load (s20), align 4)
    ; CHECK-NEXT: undef [[COPY1:%[0-9]+]].sub_ptr:epsrfldf = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]].sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:ed = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = COPY [[MOV_PD_imm11_pseudo]].sub_dim_size
    ; CHECK-NEXT: [[VLDA_POP_mx4_2D_split:%[0-9]+]]:mfexa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDA_POP_mx4_2D_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLD_POP_mx4_2D_pseudo_split:%[0-9]+]]:mfexa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLD_POP_mx4_2D_pseudo_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_s_2D_pseudo_split:%[0-9]+]]:mexa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLD_POP_s_2D_pseudo_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_mx4_2D_split]], implicit [[VLD_POP_mx4_2D_pseudo_split]], implicit [[VLD_POP_s_2D_pseudo_split]]
    %2:ep = COPY $p1
    undef %13.sub_mod:ed = MOV_PD_imm11_pseudo 0
    %13.sub_dim_size:ed = LDA_dms_lda_scalar_ld_idx_imm %2, 0 :: (load (s20), align 4)
    undef %16.sub_ptr:epsrfldf = COPY $p0
    %16.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %13.sub_dim_stride:ed = COPY %13.sub_mod
    %13.sub_dim_count:ed = COPY %13.sub_dim_size
    %7:mfexa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDA_POP_mx4_2D implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %8:mfexa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLD_POP_mx4_2D_pseudo implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %9:mexa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLD_POP_s_2D_pseudo implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9
...
---
name:            test_split_2D_opIdx8_pop_flush_comprehensive
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $sfh, $p2, $r26
    ; CHECK-LABEL: name: test_split_2D_opIdx8_pop_flush_comprehensive
    ; CHECK: liveins: $p0, $p1, $sfh, $p2, $r26
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:ed = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:ed = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (load (s20), align 4)
    ; CHECK-NEXT: undef [[COPY1:%[0-9]+]].sub_ptr:epsrfldf = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]].sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:ed = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = COPY [[MOV_PD_imm11_pseudo]].sub_dim_size
    ; CHECK-NEXT: [[VLDB_POP_2D_dmx_ldb_fifo_x_split:%[0-9]+]]:mxb, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDB_POP_2D_dmx_ldb_fifo_x_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDB_POP_2D_dmx_ldb_fifo_ex_bfp16_split:%[0-9]+]]:mexb, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDB_POP_2D_dmx_ldb_fifo_ex_bfp16_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDB_POP_2D_dmx_ldb_fifo_fex_bfp13_split:%[0-9]+]]:mfexb, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDB_POP_2D_dmx_ldb_fifo_fex_bfp13_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_2D_dmx_lda_fifo_x_split:%[0-9]+]]:mxa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDA_POP_2D_dmx_lda_fifo_x_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_2D_dmx_lda_fifo_ex_bfp16_split:%[0-9]+]]:mexa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDA_POP_2D_dmx_lda_fifo_ex_bfp16_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_2D_dmx_lda_fifo_fex_bfp13_split:%[0-9]+]]:mfexa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDA_POP_2D_dmx_lda_fifo_fex_bfp13_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLD_POP_640_2D_pseudo_split:%[0-9]+]]:mexa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLD_POP_640_2D_pseudo_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_768_2D_pseudo_split:%[0-9]+]]:mfexb, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLD_POP_768_2D_pseudo_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count
    ; CHECK-NEXT: [[VLDB_POP_s_2D_split:%[0-9]+]]:mexb, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDB_POP_s_2D_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_s_2D_split:%[0-9]+]]:mexa, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDA_POP_s_2D_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDB_POP_mx4_2D_split:%[0-9]+]]:mfexb, dead [[COPY1:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY1:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY1:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VLDB_POP_mx4_2D_split [[COPY1]].sub_ptr, undef [[COPY1]].sub_fifo, [[COPY1]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mstfifo = COPY $sfh
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mpfs = COPY $p2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mr26_fifo_st = COPY $r26
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mstfifo, [[COPY3:%[0-9]+]]:mpfs, [[COPY4:%[0-9]+]]:mr26_fifo_st, [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VST_FLUSH_2D_split [[COPY2]], [[COPY3]], [[COPY4]], [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_of
    ; CHECK-NEXT: dead [[COPY2:%[0-9]+]]:mstfifo, dead [[COPY3:%[0-9]+]]:mpfs, dead [[COPY4:%[0-9]+]]:mr26_fifo_st, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = VST_FLUSH_d_2D_split [[COPY2]], [[COPY3]], [[COPY4]], [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, implicit-def $srfifo_of
    %2:ep = COPY $p1
    undef %13.sub_mod:ed = MOV_PD_imm11_pseudo 0
    %13.sub_dim_size:ed = LDA_dms_lda_scalar_ld_idx_imm %2, 0 :: (load (s20), align 4)
    undef %16.sub_ptr:epsrfldf = COPY $p0
    %16.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %13.sub_dim_stride:ed = COPY %13.sub_mod
    %13.sub_dim_count:ed = COPY %13.sub_dim_size
    %1:mxb, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDB_POP_2D_dmx_ldb_fifo_x implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %3:mexb, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDB_POP_2D_dmx_ldb_fifo_ex_bfp16 implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %4:mfexb, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDB_POP_2D_dmx_ldb_fifo_fex_bfp13 implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %5:mxa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDA_POP_2D_dmx_lda_fifo_x implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %6:mexa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDA_POP_2D_dmx_lda_fifo_ex_bfp16 implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %10:mfexa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDA_POP_2D_dmx_lda_fifo_fex_bfp13 implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %11:mexa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLD_POP_640_2D_pseudo implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %12:mfexb, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLD_POP_768_2D_pseudo implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %14:mexb, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDB_POP_s_2D implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %15:mexa, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDA_POP_s_2D implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %17:mfexb, dead %16.sub_ptr:epsrfldf, dead %16.sub_fifo:epsrfldf, dead %16.sub_avail:epsrfldf, dead %13.sub_dim_count:ed = VLDB_POP_mx4_2D implicit-def $srfifo_uf, %16.sub_ptr, undef %16.sub_fifo, %16.sub_avail, %13
    %18:mstfifo = COPY $sfh
    %19:mpfs = COPY $p2
    %20:mr26_fifo_st = COPY $r26
    %18:mstfifo, %19:mpfs, %20:mr26_fifo_st, %13.sub_dim_count:ed = VST_FLUSH_2D %18, %19, %20, %13, implicit-def $srfifo_of
    dead %18:mstfifo, dead %19:mpfs, dead %20:mr26_fifo_st, dead %13.sub_dim_count:ed = VST_FLUSH_d_2D %18, %19, %20, %13, implicit-def $srfifo_of
...

---
name:            test_split_3D_opIdx4_padd_pseudo
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1_3d
    ; CHECK-LABEL: name: test_split_3D_opIdx4_padd_pseudo
    ; CHECK: liveins: $p0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:eds, dead [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    %20:ep = COPY $p0
    %100:eds = COPY $d1_3d
    dead %20:ep, dead %100.sub_dim_count:eds, dead %100.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo killed %20, killed %100
...

# In particular, pay attention to undef for sub_hi_dim_then_sub_mod.
---
name:            test_split_3D_opIdx4
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1_3d
    ; CHECK-LABEL: name: test_split_3D_opIdx4
    ; CHECK: liveins: $p0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADDA_3D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADDB_3D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:eds, dead [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADDS_3D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    %20:ep = COPY $p0
    %100:eds = COPY $d1_3d
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = PADDA_3D killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = PADDB_3D killed %20, killed %100
    dead %20:ep, dead %100.sub_dim_count:eds, dead %100.sub_hi_dim_then_sub_dim_count:eds = PADDS_3D killed %20, killed %100
...
---
name:            test_split_3D_opIdx5
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1_3d
    ; CHECK-LABEL: name: test_split_3D_opIdx5
    ; CHECK: liveins: $p0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: $r4, [[COPY]]:ep, [[COPY1]].sub_dim_count:eds, [[COPY1]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dms_lda_scalar_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dms_lda_g_split:%[0-9]+]]:mga, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dms_lda_g_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dmv_lda_f_split:%[0-9]+]]:mffa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_f_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dms_sts_g_split [[LDA_3D_dms_lda_g_split]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:eds, dead [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dmv_sts_f_split [[LDA_3D_dmv_lda_f_split]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    %20:ep = COPY $p0
    %100:eds = COPY $d1_3d
    $r4, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dms_lda_scalar killed %20, killed %100
    %30:mga, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dms_lda_g killed %20, killed %100
    %40:mffa, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_f killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = ST_3D_dms_sts_g %30, killed %20, killed %100
    dead %20:ep, dead %100.sub_dim_count:eds, dead %100.sub_hi_dim_then_sub_dim_count:eds = ST_3D_dmv_sts_f %40, killed %20, killed %100
...

---
name:            test_split_3D_opIdx6
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1_3d, $s0
    ; CHECK-LABEL: name: test_split_3D_opIdx6
    ; CHECK: liveins: $p0, $d1_3d, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: [[VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0_split:%[0-9]+]]:edm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0_split $s0, [[COPY]], [[COPY1]].sub_mod, [[COPY1]].sub_dim_size, [[COPY1]].sub_dim_stride, [[COPY1]].sub_dim_count, undef [[COPY1]].sub_hi_dim_then_sub_mod, [[COPY1]].sub_hi_dim_then_sub_dim_size, [[COPY1]].sub_hi_dim_then_sub_dim_stride, [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %20:ep = COPY $p0
    %100:eds = COPY $d1_3d
    %0:edm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0 $s0, %20, %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
...

---
name:            test_split_3D_opIdx6_comprehensive
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1_3d, $s0, $cml0, $bmhh0
    ; CHECK-LABEL: name: test_split_3D_opIdx6_comprehensive
    ; CHECK: liveins: $p0, $d1_3d, $s0, $cml0, $bmhh0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mbmm = COPY $bmhh0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mcmm = COPY $cml0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:edm = COPY $dm0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign0_split:%[0-9]+]]:mbmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign0_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1_split:%[0-9]+]]:mbmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign0_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign0_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign1_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign0_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign0_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign1_split:%[0-9]+]]:mcmm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1_split:%[0-9]+]]:edm, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf8_fp32_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_fp8_fp32_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0_split [[COPY2]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1_split [[COPY2]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0_split [[COPY4]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1_split [[COPY4]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:eds, dead [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1_split [[COPY3]], [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep = COPY $p0
    %100:eds = COPY $d1_3d
    %1:mbmm = COPY $bmhh0
    %2:mcmm = COPY $cml0
    %3:edm = COPY $dm0
    %4:es = COPY $s0
    %5:mbmm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign0 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %6:mbmm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %7:mcmm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign0 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %8:mcmm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %9:mcmm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign0 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %10:mcmm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %11:edm, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1 %4, killed %20, killed %100, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf8_fp32 %2, %4, killed %20, killed %100, implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_fp8_fp32 %2, %4, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0 %1, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1 %1, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0 %3, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1 %3, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    dead %20:ep, dead %100.sub_dim_count:eds, dead %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1 %2, %4, killed %20, killed %100, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
...
---
name:            test_split_3D_opIdx5_loads_comprehensive
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1_3d
    ; CHECK-LABEL: name: test_split_3D_opIdx5_loads_comprehensive
    ; CHECK: liveins: $p0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: [[LDA_3D_dml_lda_scalar_L_split:%[0-9]+]]:el, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda_scalar_L_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dml_lda_scalar_F_split:%[0-9]+]]:mfa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda_scalar_F_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dml_lda2_scalar_EE_split:%[0-9]+]]:meea, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_EE_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dml_lda2_scalar_EG_split:%[0-9]+]]:mega, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_EG_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dml_lda2_scalar_GG_split:%[0-9]+]]:mgga, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_GG_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dmv_lda_feg_split:%[0-9]+]]:mfega, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_feg_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_dmv_lda_eg2_split:%[0-9]+]]:meg2a, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_eg2_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_s16_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_s16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_s8_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_s8_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_u16_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_u16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_3D_u8_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_u8_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[LDA_TM_3D_split:%[0-9]+]]:mra, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = LDA_TM_3D_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_128_split:%[0-9]+]]:mwa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_128_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_3D_128_pseudo_split:%[0-9]+]]:mwa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_3D_128_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_CONV_fp32_bf16_dmw_lda_ups_bf16_split:%[0-9]+]]:mbma, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_bf16_dmw_lda_ups_bf16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_CONV_fp32_bf16_dmx_lda_ups_f16_split:%[0-9]+]]:mcma, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_bf16_dmx_lda_ups_f16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_CONV_fp32_fp16_split:%[0-9]+]]:mcma, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_fp16_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_dmw_lda_w_split:%[0-9]+]]:mwa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmw_lda_w_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_dmw_lda_feg2_split:%[0-9]+]]:mfeg2a, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmw_lda_feg2_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_dmx_lda_bm_split:%[0-9]+]]:mbm_ld, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_bm_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDA_3D_dmx_lda_x_split:%[0-9]+]]:mxa, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_x_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDB_3D_128_split:%[0-9]+]]:mwb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_128_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_split:%[0-9]+]]:mxb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_split:%[0-9]+]]:mxb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_split:%[0-9]+]]:ey, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_split:%[0-9]+]]:ey, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: [[VLDB_3D_dmw_ldb_split:%[0-9]+]]:mwb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmw_ldb_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDB_3D_dmx_ldb_x_split:%[0-9]+]]:mxb, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmx_ldb_x_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_3D_w_pseudo_split:%[0-9]+]]:vec256, [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_3D_w_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: dead [[VLD_3D_x_pseudo_split:%[0-9]+]]:vec512, dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:eds, dead [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_3D_x_pseudo_split killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    %20:ep = COPY $p0
    %100:eds = COPY $d1_3d
    %1:el, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda_scalar_L killed %20, killed %100
    %2:mfa, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda_scalar_F killed %20, killed %100
    %3:meea, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_EE killed %20, killed %100
    %4:mega, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_EG killed %20, killed %100
    %5:mgga, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_GG killed %20, killed %100
    %6:mfega, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_feg killed %20, killed %100
    %7:meg2a, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_eg2 killed %20, killed %100
    %8:mra, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_s16 killed %20, killed %100
    %9:mra, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_s8 killed %20, killed %100
    %10:mra, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_u16 killed %20, killed %100
    %11:mra, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_3D_u8 killed %20, killed %100
    %12:mra, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = LDA_TM_3D killed %20, killed %100
    %13:mwa, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_128 killed %20, killed %100
    %14:mwa, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLD_3D_128_pseudo killed %20, killed %100
    %15:mbma, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_bf16_dmw_lda_ups_bf16 killed %20, killed %100
    %16:mcma, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_bf16_dmx_lda_ups_f16 killed %20, killed %100
    %17:mcma, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_fp16 killed %20, killed %100
    %18:mwa, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmw_lda_w killed %20, killed %100
    %19:mfeg2a, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmw_lda_feg2 killed %20, killed %100
    %21:mbm_ld, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_bm killed %20, killed %100
    %22:mxa, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_x killed %20, killed %100
    %23:mwb, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_128 killed %20, killed %100
    %24:mxb, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign0
    %25:mxb, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign1
    %26:ey, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign0
    %27:ey, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 killed %20, killed %100, implicit $crunpacksize, implicit $unpacksign1
    %28:mwb, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmw_ldb killed %20, killed %100
    %29:mxb, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmx_ldb_x killed %20, killed %100
    %30:vec256, %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VLD_3D_w_pseudo killed %20, killed %100
    dead %31:vec512, dead %20:ep, dead %100.sub_dim_count:eds, dead %100.sub_hi_dim_then_sub_dim_count:eds = VLD_3D_x_pseudo killed %20, killed %100
...

---
name:            test_split_3D_opIdx5_stores_comprehensive
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1_3d, $eg0, $x0, $y0, $feg2, $x8, $r4, $bmhh0, $bmhh1, $cml0, $l0
    ; CHECK-LABEL: name: test_split_3D_opIdx5_stores_comprehensive
    ; CHECK: liveins: $p0, $d1_3d, $eg0, $x0, $y0, $feg2, $x8, $r4, $bmhh0, $bmhh1, $cml0, $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:meg2s = COPY $eg0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mfegs = COPY $fegl0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mws_128b = COPY $wl0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mbms = COPY $bmhh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mcms = COPY $cml0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mxs = COPY $x0
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ey = COPY $y0
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mfeg2s = COPY $feg2
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mws = COPY $wl1
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mbms_v16w32 = COPY $bmhh1
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mxs_split = COPY $x8
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mrs = COPY $r4
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dml_sts_scalar_split [[COPY2]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dms_sts_scalar_split [[COPY3]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_s16_split [[COPY15]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_s8_split [[COPY15]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_TM_3D_split [[COPY15]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_eg_split [[COPY4]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_feg_split [[COPY5]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_w_split [[COPY6]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16_split [[COPY7]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16_split [[COPY8]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_fp16_fp32_split [[COPY8]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmw_sts_pack_packSign0_split [[COPY9]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmw_sts_pack_packSign1_split [[COPY9]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmx_sts_pack_packSign0_split [[COPY10]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmx_sts_pack_packSign1_split [[COPY10]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count, implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmw_sts_w_split [[COPY12]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmw_sts_feg2_split [[COPY11]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep, [[COPY1:%[0-9]+]].sub_dim_count:eds, [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmx_sts_bm_split [[COPY13]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:ep, dead [[COPY1:%[0-9]+]].sub_dim_count:eds, dead [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmx_sts_x_split [[COPY14]], killed [[COPY]], killed [[COPY1]].sub_mod, killed [[COPY1]].sub_dim_size, killed [[COPY1]].sub_dim_stride, killed [[COPY1]].sub_dim_count, killed undef [[COPY1]].sub_hi_dim_then_sub_mod, killed [[COPY1]].sub_hi_dim_then_sub_dim_size, killed [[COPY1]].sub_hi_dim_then_sub_dim_stride, killed [[COPY1]].sub_hi_dim_then_sub_dim_count
    %20:ep = COPY $p0
    %100:eds = COPY $d1_3d
    %1:el = COPY $l0
    %2:er = COPY $r4
    %3:meg2s = COPY $eg0
    %4:mfegs = COPY $fegl0
    %5:mws_128b = COPY $wl0
    %6:mbms = COPY $bmhh0
    %7:mcms = COPY $cml0
    %8:mxs = COPY $x0
    %9:ey = COPY $y0
    %10:mfeg2s = COPY $feg2
    %11:mws = COPY $wl1
    %12:mbms_v16w32 = COPY $bmhh1
    %13:mxs_split = COPY $x8
    %14:mrs = COPY $r4
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = ST_3D_dml_sts_scalar %1, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = ST_3D_dms_sts_scalar %2, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = ST_3D_s16 %14, killed %20, killed %100, implicit-def $pe2_ads, implicit $pe2_ads
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = ST_3D_s8 %14, killed %20, killed %100, implicit-def $pe2_ads, implicit $pe2_ads
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = ST_TM_3D %14, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_eg %3, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_feg %4, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_w %5, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16 %6, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16 %7, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_fp16_fp32 %7, killed %20, killed %100, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmw_sts_pack_packSign0 %8, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmw_sts_pack_packSign1 %8, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign1
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmx_sts_pack_packSign0 %9, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmx_sts_pack_packSign1 %9, killed %20, killed %100, implicit $crpacksize, implicit $crsat, implicit $packsign1
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmw_sts_w %11, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmw_sts_feg2 %10, killed %20, killed %100
    %20:ep, %100.sub_dim_count:eds, %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmx_sts_bm %12, killed %20, killed %100
    dead %20:ep, dead %100.sub_dim_count:eds, dead %100.sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmx_sts_x %13, killed %20, killed %100
...

---
---
name:            test_split_3D_opIdx9
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_split_3D_opIdx9
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:eds = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: undef [[COPY:%[0-9]+]].sub_ptr:epsrfldf = COPY $p0
    ; CHECK-NEXT: [[COPY:%[0-9]+]].sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_dim_size
    ; CHECK-NEXT: [[VLD_POP_512_3D_pseudo_split:%[0-9]+]]:vec512, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_512_3D_pseudo_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_3D_pseudo_split]]
    undef %12.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %12.sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 128
    undef %18.sub_ptr:epsrfldf = COPY $p0
    %18.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %12.sub_dim_stride:eds = COPY %12.sub_mod
    %12.sub_dim_size:eds = COPY %12.sub_hi_dim_then_sub_dim_stride
    %12.sub_dim_count:eds = COPY %12.sub_mod
    %12.sub_hi_dim_then_sub_dim_count:eds = COPY %12.sub_mod
    %12.sub_hi_dim_then_sub_dim_size:eds = COPY %12.sub_dim_size
    %5:vec512, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_512_3D_pseudo %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %5
...

---
name:            test_split_3D_opIdx9_pop_comprehensive
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_split_3D_opIdx9_pop_comprehensive
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:eds = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: undef [[COPY:%[0-9]+]].sub_ptr:epsrfldf = COPY $p0
    ; CHECK-NEXT: [[COPY:%[0-9]+]].sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_dim_size
    ; CHECK-NEXT: [[VLDB_POP_3D_dmx_ldb_fifo_x_split:%[0-9]+]]:mxb, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_x_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDB_POP_3D_dmx_ldb_fifo_ex_bfp16_split:%[0-9]+]]:mexb, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_ex_bfp16_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDB_POP_3D_dmx_ldb_fifo_fex_bfp13_split:%[0-9]+]]:mfexb, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_fex_bfp13_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_3D_dmx_lda_fifo_x_split:%[0-9]+]]:mxa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_x_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_3D_dmx_lda_fifo_ex_bfp16_split:%[0-9]+]]:mexa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_ex_bfp16_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_3D_dmx_lda_fifo_fex_bfp13_split:%[0-9]+]]:mfexa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_fex_bfp13_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLD_POP_640_3D_pseudo_split:%[0-9]+]]:mexa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_640_3D_pseudo_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_768_3D_pseudo_split:%[0-9]+]]:mfexb, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_768_3D_pseudo_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLDB_POP_s_3D_split:%[0-9]+]]:mexb, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_s_3D_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLDA_POP_s_3D_split:%[0-9]+]]:mexa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_s_3D_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: dead [[VLDB_POP_mx4_3D_split:%[0-9]+]]:mfexb, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_mx4_3D_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    undef %12.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %12.sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 128
    undef %18.sub_ptr:epsrfldf = COPY $p0
    %18.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %12.sub_dim_stride:eds = COPY %12.sub_mod
    %12.sub_dim_size:eds = COPY %12.sub_hi_dim_then_sub_dim_stride
    %12.sub_dim_count:eds = COPY %12.sub_mod
    %12.sub_hi_dim_then_sub_dim_count:eds = COPY %12.sub_mod
    %12.sub_hi_dim_then_sub_dim_size:eds = COPY %12.sub_dim_size
    %1:mxb, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_x implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %2:mexb, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_ex_bfp16 implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %3:mfexb, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_fex_bfp13 implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %4:mxa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_x implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %5:mexa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_ex_bfp16 implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %6:mfexa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_fex_bfp13 implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %7:mexa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_640_3D_pseudo implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %8:mfexb, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_768_3D_pseudo implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %9:mexb, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_s_3D implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %10:mexa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_s_3D implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    dead %11:mfexb, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_mx4_3D implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
...

---
name:            test_split_3D_opIdx9_mx4
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $sfh, $p2, $r26

    ; CHECK-LABEL: name: test_split_3D_opIdx9_mx4
    ; CHECK: liveins: $p0, $sfh, $p2, $r26
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:eds = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: undef [[COPY:%[0-9]+]].sub_ptr:epsrfldf = COPY $p0
    ; CHECK-NEXT: [[COPY:%[0-9]+]].sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_dim_size
    ; CHECK-NEXT: [[VLDA_POP_mx4_3D_split:%[0-9]+]]:mfexa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_mx4_3D_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[VLD_POP_mx4_3D_pseudo_split:%[0-9]+]]:mfexa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_mx4_3D_pseudo_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_s_3D_pseudo_split:%[0-9]+]]:mexa, dead [[COPY:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY:%[0-9]+]].sub_avail:epsrfldf, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_s_3D_pseudo_split [[COPY]].sub_ptr, undef [[COPY]].sub_fifo, [[COPY]].sub_avail, [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mstfifo = COPY $sfh
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mpfs = COPY $p2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mr26_fifo_st = COPY $r26
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mstfifo, [[COPY2:%[0-9]+]]:mpfs, [[COPY3:%[0-9]+]]:mr26_fifo_st, [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_3D_split [[COPY1]], [[COPY2]], [[COPY3]], [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_of
    ; CHECK-NEXT: dead [[COPY1:%[0-9]+]]:mstfifo, dead [[COPY2:%[0-9]+]]:mpfs, dead [[COPY3:%[0-9]+]]:mr26_fifo_st, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds, dead [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_d_3D_split [[COPY1]], [[COPY2]], [[COPY3]], [[MOV_PD_imm11_pseudo]].sub_mod, [[MOV_PD_imm11_pseudo]].sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_dim_count, undef [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_mod, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_of
    undef %12.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %12.sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 128
    undef %18.sub_ptr:epsrfldf = COPY $p0
    %18.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %12.sub_dim_stride:eds = COPY %12.sub_mod
    %12.sub_dim_size:eds = COPY %12.sub_hi_dim_then_sub_dim_stride
    %12.sub_dim_count:eds = COPY %12.sub_mod
    %12.sub_hi_dim_then_sub_dim_count:eds = COPY %12.sub_mod
    %12.sub_hi_dim_then_sub_dim_size:eds = COPY %12.sub_dim_size
    %5:mfexa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_mx4_3D implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %6:mfexa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_mx4_3D_pseudo implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %7:mexa, dead %18.sub_ptr:epsrfldf, dead %18.sub_fifo:epsrfldf, dead %18.sub_avail:epsrfldf, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_s_3D_pseudo implicit-def $srfifo_uf, %18.sub_ptr, undef %18.sub_fifo, %18.sub_avail, %12
    %8:mstfifo = COPY $sfh
    %9:mpfs = COPY $p2
    %10:mr26_fifo_st = COPY $r26
    %8:mstfifo, %9:mpfs, %10:mr26_fifo_st, %12.sub_dim_count:eds, %12.sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_3D %8, %9, %10, %12, implicit-def $srfifo_of
    dead %8:mstfifo, dead %9:mpfs, dead %10:mr26_fifo_st, dead %12.sub_dim_count:eds, dead %12.sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_d_3D %8, %9, %10, %12, implicit-def $srfifo_of
...
