; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -O2 -mtriple=aie2ps %s -o - | FileCheck %s
;
; Regression test for AIESuperRegRewriter: when a composite super-register
; is coalesced across control flow such that only some sub-lanes are live on
; an incoming path, the full-copy decomposition must still emit a reaching
; definition (IMPLICIT_DEF) for the dead sub-lanes and mark uses of dead
; sub-lanes as undef. Otherwise the machine verifier reports:
;   "Virtual register defs don't dominate all uses".
; Reduced from a real compile failure using llvm-reduce.
;
; FileCheck verifies that after aie-superreg-rewrite the decomposed
; PADD_2D_pseudo_split in the loop.a path has its dead-sublane operands
; correctly marked undef (previously they had no reaching definition and
; tripped the verifier).

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2ps-none-unknown-elf"

declare { ptr, i20 } @llvm.aie2ps.add.2d(ptr, i20, i20, i20, i20) #0
declare { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #1

define void @test_dead_sublane_dom() {
; CHECK-LABEL: test_dead_sublane_dom:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #1; nopb ; nopxm ; nops
; CHECK-NEXT:    jnz r1, #.LBB0_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mova r24, #0; mov m1, #1 // Delay Slot 3
; CHECK-NEXT:    mova dj4, #0; vbcst.32 x0, r24 // Delay Slot 2
; CHECK-NEXT:    mova p0, #0; movs dc4, dj4; vmov x1, x0 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    jnz r1, #.LBB0_3
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    mov dc4, dj4 // Delay Slot 1
; CHECK-NEXT:  .LBB0_2: // %loop.b
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov m0, dj4
; CHECK-NEXT:    movs dj0, m1; mov dn0, dj4
; CHECK-NEXT:    movs dc0, dj4; mov dn4, dj4
; CHECK-NEXT:    movs p1, p0; mov r25, r24
; CHECK-NEXT:    vldb.pop.3d x2, [p1, lf1, r25, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    j #.LBB0_2
; CHECK-NEXT:    vmov lfl1, x0 // Delay Slot 5
; CHECK-NEXT:    vmov lfh1, x1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    mov dc4, dc0 // Delay Slot 1
; CHECK-NEXT:  .LBB0_3: // %loop.a
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; nopb ; nops ; j #.LBB0_3; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mova p0, #0 // Delay Slot 2
; CHECK-NEXT:    paddb.2d [p0], d0 // Delay Slot 1
entry:
  switch i8 3, label %loop.a [
    i8 0, label %loop.a
    i8 2, label %loop.a
    i8 1, label %loop.b
    i8 3, label %loop.b
  ]

loop.a:
  %iv.a = phi i32 [ %inc.a, %loop.a ], [ 0, %entry ], [ 0, %entry ], [ 0, %entry ]
  %iv.a.t = trunc i32 %iv.a to i20
  %add2d = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr null, i20 0, i20 0, i20 0, i20 %iv.a.t)
  %add2d.idx = extractvalue { ptr, i20 } %add2d, 1
  %inc.a = zext i20 %add2d.idx to i32
  %add2d.ptr = extractvalue { ptr, i20 } %add2d, 0
  br label %loop.a

loop.b:
  %iv.b = phi i32 [ %inc.b, %loop.b ], [ 0, %entry ], [ 0, %entry ]
  %iv.b.t = trunc i32 %iv.b to i20
  %ld0 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) null, <32 x i32> zeroinitializer, i32 0, i20 0, i20 0, i20 0, i20 1, i20 0, i20 %iv.b.t, i20 0)
  %ld0.vec = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %ld0, 0
  %ld0.idx = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %ld0, 4
  %ld1 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) null, <32 x i32> zeroinitializer, i32 0, i20 1, i20 0, i20 0, i20 0, i20 0, i20 0, i20 0)
  %inc.b = zext i20 %ld0.idx to i32
  br label %loop.b
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
