# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            pop_unaligned_2d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_unaligned_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDB_POP_2D_dmx_ldb_fifo_x:%[0-9]+]]:vec512, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:ed = VLDB_POP_2D_dmx_ldb_fifo_x [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_2D_dmx_ldb_fifo_x]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %12:ed = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count
    %7:vec512, %8:eps, %9:eldfiforeg, %10:mrf2a, %11:edc = VLDB_POP_2D_dmx_ldb_fifo_x %0, %1, %2, %12, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %10, implicit %11

...
---
name:            pop_unaligned_3d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_unaligned_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDB_POP_3D_dmx_ldb_fifo_x:%[0-9]+]]:vec512, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_x [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_3D_dmx_ldb_fifo_x]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:vec512, %11:eps, %12:eldfiforeg, %13:mrf2a, %14:edcl, %15:edch = VLDB_POP_3D_dmx_ldb_fifo_x %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

