# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_pop_normal_vlda
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24
    ; CHECK-LABEL: name: test_pop_normal_vlda
    ; CHECK: liveins: $p0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2a = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE]].sub_ptr:epsrfldf, [[REG_SEQUENCE]].sub_fifo:epsrfldf, [[REG_SEQUENCE]].sub_avail:epsrfldf = VLDA_POP_dmx_lda_fifo_x_normal_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex0, [[REG_SEQUENCE1]].sub_ptr:epsrfldf, [[REG_SEQUENCE1]].sub_fifo:epsrfldf, [[REG_SEQUENCE1]].sub_avail:epsrfldf = VLDA_POP_dmx_lda_fifo_ex_bfp16_normal_pop [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $fex0, [[REG_SEQUENCE2]].sub_ptr:epsrfldf, [[REG_SEQUENCE2]].sub_fifo:epsrfldf, [[REG_SEQUENCE2]].sub_avail:epsrfldf = VLDA_POP_dmx_lda_fifo_fex_bfp13_normal_pop [[REG_SEQUENCE2]].sub_ptr, [[REG_SEQUENCE2]].sub_fifo, [[REG_SEQUENCE2]].sub_avail, implicit-def $srfifo_uf
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2a = COPY $r24
    $x0, %3:eps, %4:eldfiforeg, %5:mref2a = VLDA_POP_dmx_lda_fifo_x_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    $ex0, %6:eps, %7:eldfiforeg, %8:mref2a = VLDA_POP_dmx_lda_fifo_ex_bfp16_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    $fex0, %9:eps, %10:eldfiforeg, %11:mref2a = VLDA_POP_dmx_lda_fifo_fex_bfp13_normal_pop %0, %1, %2, implicit-def $srfifo_uf

...
---
name:            test_pop_normal_vldb
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24
    ; CHECK-LABEL: name: test_pop_normal_vldb
    ; CHECK: liveins: $p0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2b = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE]].sub_ptr:epsrfldf, [[REG_SEQUENCE]].sub_fifo:epsrfldf, [[REG_SEQUENCE]].sub_avail:epsrfldf = VLDB_POP_dmx_ldb_fifo_x_normal_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex0, [[REG_SEQUENCE1]].sub_ptr:epsrfldf, [[REG_SEQUENCE1]].sub_fifo:epsrfldf, [[REG_SEQUENCE1]].sub_avail:epsrfldf = VLDB_POP_dmx_ldb_fifo_ex_bfp16_normal_pop [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $fex0, [[REG_SEQUENCE2]].sub_ptr:epsrfldf, [[REG_SEQUENCE2]].sub_fifo:epsrfldf, [[REG_SEQUENCE2]].sub_avail:epsrfldf = VLDB_POP_dmx_ldb_fifo_fex_bfp13_normal_pop [[REG_SEQUENCE2]].sub_ptr, [[REG_SEQUENCE2]].sub_fifo, [[REG_SEQUENCE2]].sub_avail, implicit-def $srfifo_uf
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2b = COPY $r24
    $x0, %3:eps, %4:eldfiforeg, %5:mref2b = VLDB_POP_dmx_ldb_fifo_x_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    $ex0, %6:eps, %7:eldfiforeg, %8:mref2b = VLDB_POP_dmx_ldb_fifo_ex_bfp16_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    $fex0, %9:eps, %10:eldfiforeg, %11:mref2b = VLDB_POP_dmx_ldb_fifo_fex_bfp13_normal_pop %0, %1, %2, implicit-def $srfifo_uf

...
---
name:            test_pop_normal_pseudo
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24
    ; CHECK-LABEL: name: test_pop_normal_pseudo
    ; CHECK: liveins: $p0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2a = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE]].sub_ptr:epsrfldf, [[REG_SEQUENCE]].sub_fifo:epsrfldf, [[REG_SEQUENCE]].sub_avail:epsrfldf = VLD_POP_512_normal_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex0, [[REG_SEQUENCE1]].sub_ptr:epsrfldf, [[REG_SEQUENCE1]].sub_fifo:epsrfldf, [[REG_SEQUENCE1]].sub_avail:epsrfldf = VLD_POP_640_normal_pop_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $fex0, [[REG_SEQUENCE2]].sub_ptr:epsrfldf, [[REG_SEQUENCE2]].sub_fifo:epsrfldf, [[REG_SEQUENCE2]].sub_avail:epsrfldf = VLD_POP_768_normal_pop_pseudo [[REG_SEQUENCE2]].sub_ptr, [[REG_SEQUENCE2]].sub_fifo, [[REG_SEQUENCE2]].sub_avail, implicit-def $srfifo_uf
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2a = COPY $r24
    $x0, %3:eps, %4:eldfiforeg, %5:mref2a = VLD_POP_512_normal_pop_pseudo %0, %1, %2, implicit-def $srfifo_uf
    $ex0, %6:eps, %7:eldfiforeg, %8:mref2a = VLD_POP_640_normal_pop_pseudo %0, %1, %2, implicit-def $srfifo_uf
    $fex0, %9:eps, %10:eldfiforeg, %11:mref2a = VLD_POP_768_normal_pop_pseudo %0, %1, %2, implicit-def $srfifo_uf

...
