# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vst_2d_srs_2x
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d1, $s0, $bmll0, $cml0
    ; CHECK-LABEL: name: test_vst_2d_srs_2x
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0_:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, [[COPY2]], [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1_:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, [[COPY2]], [[COPY]], [[COPY4]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, [[COPY2]], [[COPY]], [[COPY5]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY6]].sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, [[COPY2]], [[COPY]], [[COPY6]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %0:ep = COPY $p0
    %1:ed = COPY $d1
    %2:es = COPY $s0
    %100:ep, %101:edc = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %110:ep, %111:edc = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %120:ep, %121:edc = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %130:ep, %131:edc = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1

...
---
name:            test_vst_2d_srs_4x
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d1, $s0, $cml0, $dm0
    ; CHECK-LABEL: name: test_vst_2d_srs_4x
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0 $cml0, [[COPY2]], [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1 $cml0, [[COPY2]], [[COPY]], [[COPY4]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0_:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0 $dm0, [[COPY2]], [[COPY]], [[COPY5]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1_:%[0-9]+]]:ep, [[COPY6]].sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1 $dm0, [[COPY2]], [[COPY]], [[COPY6]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %0:ep = COPY $p0
    %1:ed = COPY $d1
    %2:es = COPY $s0
    %100:ep, %101:edc = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %110:ep, %111:edc = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %120:ep, %121:edc = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0 $dm0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %130:ep, %131:edc = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1 $dm0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1

...
---
name:            test_vst_3d_srs_2x
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d, $s0, $bmll0, $cml0
    ; CHECK-LABEL: name: test_vst_3d_srs_2x
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0_:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, [[COPY2]], [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1_:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, [[COPY2]], [[COPY]], [[COPY4]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, [[COPY2]], [[COPY]], [[COPY5]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, [[COPY2]], [[COPY]], [[COPY6]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %0:ep = COPY $p0
    %1:eds = COPY $d0_3d
    %2:es = COPY $s0
    %100:ep, %101:edcl, %102:edch = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %110:ep, %111:edcl, %112:edch = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %120:ep, %121:edcl, %122:edch = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %130:ep, %131:edcl, %132:edch = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1

...
---
name:            test_vst_3d_srs_4x
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d, $s0, $cml0, $dm0
    ; CHECK-LABEL: name: test_vst_3d_srs_4x
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0 $cml0, [[COPY2]], [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1 $cml0, [[COPY2]], [[COPY]], [[COPY4]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0_:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0 $dm0, [[COPY2]], [[COPY]], [[COPY5]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1_:%[0-9]+]]:ep, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1 $dm0, [[COPY2]], [[COPY]], [[COPY6]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %0:ep = COPY $p0
    %1:eds = COPY $d0_3d
    %2:es = COPY $s0
    %100:ep, %101:edcl, %102:edch = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %110:ep, %111:edcl, %112:edch = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1 $cml0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %120:ep, %121:edcl, %122:edch = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0 $dm0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %130:ep, %131:edcl, %132:edch = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1 $dm0, %2, %0, %1, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1

...
