# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            pop_unaligned_2d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_unaligned_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_512_2D_pseudo:%[0-9]+]]:vec512, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:ed = VLD_POP_512_2D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_2D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %12:ed = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count
    %7:vec512, %8:eps, %9:eldfiforeg, %10:mrf2a, %11:edc = VLD_POP_512_2D_pseudo %0, %1, %2, %12, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %10, implicit %11

...
---
name:            pop_unaligned_3d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_unaligned_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_512_3D_pseudo:%[0-9]+]]:vec512, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_512_3D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_3D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:vec512, %11:eps, %12:eldfiforeg, %13:mrf2a, %14:edcl, %15:edch = VLD_POP_512_3D_pseudo %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            st_flush_2d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: st_flush_2d
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_FLUSH_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_2D2:%[0-9]+]]:mr26_fifo_st, [[COPY:%[0-9]+]].sub_dim_count:ed = VST_FLUSH_2D [[DEF1]], [[DEF]], [[DEF2]], [[COPY]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_2D1]], implicit [[VST_FLUSH_2D]], implicit [[VST_FLUSH_2D2]], implicit [[COPY]].sub_dim_count
    %0:mpfs = IMPLICIT_DEF
    %1:mstfifo = IMPLICIT_DEF
    %2:mr26_fifo_st = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %11:ed = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count
    %8:mstfifo, %7:mpfs, %9:mr26_fifo_st, %10:edc = VST_FLUSH_2D %1, %0, %2, %11, implicit-def $srfifo_of
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %10

...
---
name:            st_flush_2d_conv
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: st_flush_2d_conv
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_FLUSH_d_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_2D2:%[0-9]+]]:mr26_fifo_st, [[COPY:%[0-9]+]].sub_dim_count:ed = VST_FLUSH_d_2D [[DEF1]], [[DEF]], [[DEF2]], [[COPY]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_d_2D1]], implicit [[VST_FLUSH_d_2D]], implicit [[VST_FLUSH_d_2D2]], implicit [[COPY]].sub_dim_count
    %0:mpfs = IMPLICIT_DEF
    %1:mstfifo = IMPLICIT_DEF
    %2:mr26_fifo_st = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %11:ed = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count
    %8:mstfifo, %7:mpfs, %9:mr26_fifo_st, %10:edc = VST_FLUSH_d_2D %1, %0, %2, %11, implicit-def $srfifo_of
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %10

...
---
name:            st_flush_3d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: st_flush_3d
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_FLUSH_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_3D2:%[0-9]+]]:mr26_fifo_st, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_3D [[DEF1]], [[DEF]], [[DEF2]], [[COPY]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_3D1]], implicit [[VST_FLUSH_3D]], implicit [[VST_FLUSH_3D2]], implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:mpfs = IMPLICIT_DEF
    %1:mstfifo = IMPLICIT_DEF
    %2:mr26_fifo_st = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %15:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %11:mstfifo, %10:mpfs, %12:mr26_fifo_st, %13:edcl, %14:edch = VST_FLUSH_3D %1, %0, %2, %15, implicit-def $srfifo_of
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14

...
---
name:            st_flush_3d_conv
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: st_flush_3d_conv
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_FLUSH_d_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_3D2:%[0-9]+]]:mr26_fifo_st, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_d_3D [[DEF1]], [[DEF]], [[DEF2]], [[COPY]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_d_3D1]], implicit [[VST_FLUSH_d_3D]], implicit [[VST_FLUSH_d_3D2]], implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:mpfs = IMPLICIT_DEF
    %1:mstfifo = IMPLICIT_DEF
    %2:mr26_fifo_st = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %15:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %11:mstfifo, %10:mpfs, %12:mr26_fifo_st, %13:edcl, %14:edch = VST_FLUSH_d_3D %1, %0, %2, %15, implicit-def $srfifo_of
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14

...
