# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vmul_bfp16
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $ewl5, $ey2, $ewh4, $ey0, $ey1, $ewh3, $r15, $ewh0, $dm4, $ewl9, $ey3, $ewh10, $r8, $dm3, $ewl7, $ewh9, $r14, $dm5, $dm0, $ewl4, $ewh5, $dm1, $dm6, $ewl0, $ewh6, $r10, $ewl6, $ewh7
    ; CHECK-LABEL: name: test_vmul_bfp16
    ; CHECK: liveins: $d0_3d, $ewl5, $ey2, $ewh4, $ey0, $ey1, $ewh3, $r15, $ewh0, $dm4, $ewl9, $ey3, $ewh10, $r8, $dm3, $ewl7, $ewh9, $r14, $dm5, $dm0, $ewl4, $ewh5, $dm1, $dm6, $ewl0, $ewh6, $r10, $ewl6, $ewh7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mewlv_bis = COPY $ewl5
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mewlv_bis = COPY $ewl4
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mewlv_bis = COPY $ewl7
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mewlv_bis = COPY $ewl0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mewlv_bis = COPY $ewl6
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mewhv = COPY $ewh5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mewhv = COPY $ewh4
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mewhv = COPY $ewh7
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mewhv = COPY $ewh0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mewhv = COPY $ewh6
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY]], %subreg.sub_bfp320_lo, [[COPY5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: $dm3 = VMUL_f_vmul_bfp16 [[REG_SEQUENCE]].sub_bfp320_lo, $ey2, $ey2, [[REG_SEQUENCE]].sub_bfp320_hi, $r10, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY1]], %subreg.sub_bfp320_lo, [[COPY6]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: $dm7 = VNEGMUL_f_vmul_bfp16 [[REG_SEQUENCE1]].sub_bfp320_lo, $ey0, $ey1, [[REG_SEQUENCE1]].sub_bfp320_hi, $r15, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY3]], %subreg.sub_bfp320_lo, [[COPY8]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: $dm2 = VMAC_f_vmac_bfp16 $dm4, [[REG_SEQUENCE2]].sub_bfp320_lo, $ey2, $ey3, [[REG_SEQUENCE2]].sub_bfp320_hi, $r8, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp320_lo, [[COPY7]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: $dm5 = VMSC_f_vmac_bfp16 $dm3, [[REG_SEQUENCE3]].sub_bfp320_lo, $ey1, $ey0, [[REG_SEQUENCE3]].sub_bfp320_hi, $r14, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY]], %subreg.sub_bfp320_lo, [[COPY5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: $dm5 = VADDMAC_f_vaddmac_bfp16 $dm5, $dm0, [[REG_SEQUENCE4]].sub_bfp320_lo, $ey2, $ey2, [[REG_SEQUENCE4]].sub_bfp320_hi, $r14, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY4]], %subreg.sub_bfp320_lo, [[COPY9]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: $dm1 = VADDMSC_f_vaddmac_bfp16 $dm1, $dm6, [[REG_SEQUENCE5]].sub_bfp320_lo, $ey1, $ey2, [[REG_SEQUENCE5]].sub_bfp320_hi, $r10, implicit-def $srfpflags, implicit $crfpmask
    %0:mewlv_bis = COPY $ewl5
    %1:mewlv_bis = COPY $ewl4
    %2:mewlv_bis = COPY $ewl7
    %3:mewlv_bis = COPY $ewl0
    %4:mewlv_bis = COPY $ewl6
    %10:mewhv = COPY $ewh5
    %11:mewhv = COPY $ewh4
    %12:mewhv = COPY $ewh7
    %13:mewhv = COPY $ewh0
    %14:mewhv = COPY $ewh6
    $dm3 = VMUL_f_vmul_bfp16 %0, $ey2, $ey2, %10, $r10, implicit-def $srfpflags, implicit $crfpmask
    $dm7 = VNEGMUL_f_vmul_bfp16 %1, $ey0, $ey1, %11, $r15, implicit-def $srfpflags, implicit $crfpmask
    $dm2 = VMAC_f_vmac_bfp16 $dm4, %3, $ey2, $ey3, %13, $r8, implicit-def $srfpflags, implicit $crfpmask
    $dm5 = VMSC_f_vmac_bfp16 $dm3, %2, $ey1, $ey0, %12, $r14, implicit-def $srfpflags, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bfp16 $dm5, $dm0, %0, $ey2, $ey2, %10, $r14, implicit-def $srfpflags, implicit $crfpmask
    $dm1 = VADDMSC_f_vaddmac_bfp16 $dm1, $dm6, %4, $ey1, $ey2, %14, $r10, implicit-def $srfpflags, implicit $crfpmask

...
