# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vst_3d_basic
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d, $wl0, $x0, $bmll0, $eg0, $feg0, $feg1
    ; CHECK-LABEL: name: test_vst_3d_basic
    ; CHECK: liveins: $p0, $d0_3d, $wl0, $x0, $bmll0, $eg0, $feg0, $feg1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_128_dmv_sts_eg:%[0-9]+]]:ep, [[COPY2:%[0-9]+]].sub_dim_count:eds, [[COPY2:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_eg $eg0, [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_128_dmv_sts_feg:%[0-9]+]]:ep, [[COPY3:%[0-9]+]].sub_dim_count:eds, [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_feg $fegl0, [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_128_dmv_sts_w:%[0-9]+]]:ep, [[COPY4:%[0-9]+]].sub_dim_count:eds, [[COPY4:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_128_dmv_sts_w $wl0, [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_dmw_sts_feg2_:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:eds, [[COPY5:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmw_sts_feg2 $feg1, [[COPY]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_dmw_sts_w:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:eds, [[COPY6:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmw_sts_w $wl0, [[COPY]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_dmx_sts_x:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:eds, [[COPY7:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmx_sts_x $x0, [[COPY]], [[COPY7]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_dmx_sts_bm:%[0-9]+]]:ep, [[COPY8:%[0-9]+]].sub_dim_count:eds, [[COPY8:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_dmx_sts_bm $bmll0, [[COPY]], [[COPY8]]
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    %100:ep, %101:edcl, %102:edch = VST_3D_128_dmv_sts_eg $eg0, %0, %10
    %140:ep, %141:edcl, %142:edch = VST_3D_128_dmv_sts_feg $fegl0, %0, %10
    %150:ep, %151:edcl, %152:edch = VST_3D_128_dmv_sts_w $wl0, %0, %10
    %160:ep, %161:edcl, %162:edch = VST_3D_dmw_sts_feg2 $feg1, %0, %10
    %110:ep, %111:edcl, %112:edch = VST_3D_dmw_sts_w $wl0, %0, %10
    %120:ep, %121:edcl, %122:edch = VST_3D_dmx_sts_x $x0, %0, %10
    %130:ep, %131:edcl, %132:edch = VST_3D_dmx_sts_bm $bmll0, %0, %10
...
---
name:            test_vst_3d_conv
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $p0, $s0,$bmll0, $cml0, $cml1, $cml2, $cml3
    ; CHECK-LABEL: name: test_vst_3d_conv
    ; CHECK: liveins: $d0_3d, $p0, $s0, $bmll0, $cml0, $cml1, $cml2, $cml3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16_:%[0-9]+]]:ep, [[COPY3:%[0-9]+]].sub_dim_count:eds, [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16 $bmll0, [[COPY]], [[COPY3]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16_:%[0-9]+]]:ep, [[COPY4:%[0-9]+]].sub_dim_count:eds, [[COPY4:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16 $cml0, [[COPY]], [[COPY4]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_CONV_fp16_fp32_:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:eds, [[COPY5:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_fp16_fp32 $cml1, [[COPY]], [[COPY5]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_CONV_fp8_fp32_:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:eds, [[COPY6:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_fp8_fp32 $cml2, [[COPY1]], [[COPY]], [[COPY6]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_CONV_bf8_fp32_:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:eds, [[COPY7:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf8_fp32 $cml3, [[COPY1]], [[COPY]], [[COPY7]], implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %0:ep = COPY $p0
    %1:es = COPY $s0
    %10:eds = COPY $d0_3d
    %100:ep, %101:edcl, %102:edch = VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16 $bmll0, %0, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %110:ep, %111:edcl, %112:edch = VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16 $cml0, %0, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %120:ep, %121:edcl, %122:edch = VST_3D_CONV_fp16_fp32 $cml1, %0, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %140:ep, %141:edcl, %142:edch = VST_3D_CONV_fp8_fp32 $cml2, %1, %0, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    %150:ep, %151:edcl, %152:edch = VST_3D_CONV_bf8_fp32 $cml3, %1, %0, %10, implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
...
---
name:            test_vst_3d_pack
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d, $x0, $y0
    ; CHECK-LABEL: name: test_vst_3d_pack
    ; CHECK: liveins: $p0, $d0_3d, $x0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign0_:%[0-9]+]]:ep, [[COPY2:%[0-9]+]].sub_dim_count:eds, [[COPY2:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmw_sts_pack_packSign0 $x0, [[COPY]], [[COPY2]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign1_:%[0-9]+]]:ep, [[COPY3:%[0-9]+]].sub_dim_count:eds, [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmw_sts_pack_packSign1 $x0, [[COPY]], [[COPY3]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign0_:%[0-9]+]]:ep, [[COPY4:%[0-9]+]].sub_dim_count:eds, [[COPY4:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmx_sts_pack_packSign0 $y0, [[COPY]], [[COPY4]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign1_:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:eds, [[COPY5:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_PACK_dmx_sts_pack_packSign1 $y0, [[COPY]], [[COPY5]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    %100:ep, %101:edcl, %102:edch = VST_3D_PACK_dmw_sts_pack_packSign0 $x0, %0, %10, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %110:ep, %111:edcl, %112:edch = VST_3D_PACK_dmw_sts_pack_packSign1 $x0, %0, %10, implicit $crpacksize, implicit $crsat, implicit $packsign1
    %120:ep, %121:edcl, %122:edch = VST_3D_PACK_dmx_sts_pack_packSign0 $y0, %0, %10, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %130:ep, %131:edcl, %132:edch = VST_3D_PACK_dmx_sts_pack_packSign1 $y0, %0, %10, implicit $crpacksize, implicit $crsat, implicit $packsign1
...
