# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            pop_s_normal
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_s_normal
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLD_POP_s_normal_pop_pseudo:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_POP_s_normal_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_s_normal_pop_pseudo]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:mexa, %4:eps, %5:eldfiforeg, %6:mrf2a = VLD_POP_s_normal_pop_pseudo %0, %1, %2, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %3, implicit %4, implicit %5, implicit %6

...
---
name:            pop_s_fifo_1d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_s_fifo_1d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLD_POP_s_fifo_1d_pop_pseudo:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_POP_s_fifo_1d_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_s_fifo_1d_pop_pseudo]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mexa, %5:eps, %6:eldfiforeg, %7:mrf2a = VLD_POP_s_fifo_1d_pop_pseudo %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            pop_s_2d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_s_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_s_2D_pseudo:%[0-9]+]]:mexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:ed = VLD_POP_s_2D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_s_2D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %12:ed = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count
    %7:mexa, %8:eps, %9:eldfiforeg, %10:mrf2a, %11:edc = VLD_POP_s_2D_pseudo %0, %1, %2, %12, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %10, implicit %11

...
---
name:            pop_s_3d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_s_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_s_3D_pseudo:%[0-9]+]]:mexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_s_3D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_s_3D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mexa, %11:eps, %12:eldfiforeg, %13:mrf2a, %14:edcl, %15:edch = VLD_POP_s_3D_pseudo %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            pop_mx4_normal
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_mx4_normal
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLD_POP_mx4_normal_pop_pseudo:%[0-9]+]]:mfexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_POP_mx4_normal_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_mx4_normal_pop_pseudo]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:mfexa, %4:eps, %5:eldfiforeg, %6:mrf2a = VLD_POP_mx4_normal_pop_pseudo %0, %1, %2, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %3, implicit %4, implicit %5, implicit %6

...
---
name:            pop_mx4_fifo_1d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_mx4_fifo_1d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLD_POP_mx4_fifo_1d_pop_pseudo:%[0-9]+]]:mfexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_POP_mx4_fifo_1d_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_mx4_fifo_1d_pop_pseudo]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mfexa, %5:eps, %6:eldfiforeg, %7:mrf2a = VLD_POP_mx4_fifo_1d_pop_pseudo %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            pop_mx4_2d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_mx4_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_mx4_2D_pseudo:%[0-9]+]]:mfexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:ed = VLD_POP_mx4_2D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_mx4_2D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %12:ed = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count
    %7:mfexa, %8:eps, %9:eldfiforeg, %10:mrf2a, %11:edc = VLD_POP_mx4_2D_pseudo %0, %1, %2, %12, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %10, implicit %11

...
---
name:            pop_mx4_3d
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_mx4_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_mx4_3D_pseudo:%[0-9]+]]:mfexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_mx4_3D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_mx4_3D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mrf2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mfexa, %11:eps, %12:eldfiforeg, %13:mrf2a, %14:edcl, %15:edch = VLD_POP_mx4_3D_pseudo %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            pop_vlda_s_normal
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_vlda_s_normal
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDA_POP_s_normal_pop:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_POP_s_normal_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_s_normal_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:mexa, %4:eps, %5:eldfiforeg, %6:mref2a = VLDA_POP_s_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %3, implicit %4, implicit %5, implicit %6

...
---
name:            pop_vldb_s_normal
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_vldb_s_normal
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDB_POP_s_normal_pop:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_POP_s_normal_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_s_normal_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:mexa, %4:eps, %5:eldfiforeg, %6:mref2b = VLDB_POP_s_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %3, implicit %4, implicit %5, implicit %6

...
---
name:            pop_vlda_mx4_normal
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_vlda_mx4_normal
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDA_POP_mx4_normal_pop:%[0-9]+]]:mfexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_POP_mx4_normal_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_mx4_normal_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:mfexa, %4:eps, %5:eldfiforeg, %6:mref2a = VLDA_POP_mx4_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %3, implicit %4, implicit %5, implicit %6

...
---
name:            pop_vldb_mx4_normal
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: pop_vldb_mx4_normal
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDB_POP_mx4_normal_pop:%[0-9]+]]:mfexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_POP_mx4_normal_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_mx4_normal_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:mfexa, %4:eps, %5:eldfiforeg, %6:mref2b = VLDB_POP_mx4_normal_pop %0, %1, %2, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %3, implicit %4, implicit %5, implicit %6

...
