# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_st_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d, $l0, $r4, $r0, $f0
    ; CHECK-LABEL: name: test_st_3d
    ; CHECK: liveins: $p0, $d0_3d, $l0, $r4, $r0, $f0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_dml_sts_scalar:%[0-9]+]]:ep, [[COPY2:%[0-9]+]].sub_dim_count:eds, [[COPY2:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dml_sts_scalar $l0, [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_dms_sts_scalar:%[0-9]+]]:ep, [[COPY3:%[0-9]+]].sub_dim_count:eds, [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dms_sts_scalar $r4, [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_s16_:%[0-9]+]]:ep, [[COPY4:%[0-9]+]].sub_dim_count:eds, [[COPY4:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_s16 $r4, [[COPY]], [[COPY4]], implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_s8_:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:eds, [[COPY5:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_s8 $r4, [[COPY]], [[COPY5]], implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_TM_3D:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:eds, [[COPY6:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_TM_3D $r0, [[COPY]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_dmv_sts_f:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:eds, [[COPY7:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dmv_sts_f $f0, [[COPY]], [[COPY7]]
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    %100:ep, %101:edcl, %102:edch = ST_3D_dml_sts_scalar $l0, %0, %10
    %110:ep, %111:edcl, %112:edch = ST_3D_dms_sts_scalar $r4, %0, %10
    %120:ep, %121:edcl, %122:edch = ST_3D_s16 $r4, %0, %10, implicit-def $pe2_ads, implicit $pe2_ads
    %130:ep, %131:edcl, %132:edch = ST_3D_s8 $r4, %0, %10, implicit-def $pe2_ads, implicit $pe2_ads
    %140:ep, %141:edcl, %142:edch = ST_TM_3D $r0, %0, %10
    %150:ep, %151:edcl, %152:edch = ST_3D_dmv_sts_f $f0, %0, %10
...
