# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_lda_3d_basic
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d
    ; CHECK-LABEL: name: test_lda_3d_basic
    ; CHECK: liveins: $p0, $d0_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $l0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda_scalar_L [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $r4, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dms_lda_scalar [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $r4, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_s16 [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $r4, %11:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_s8 [[COPY]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $r4, %14:ep, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_u16 [[COPY]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $r4, %17:ep, [[COPY7]].sub_dim_count:eds, [[COPY7]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_u8 [[COPY]], [[COPY7]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $r0, %20:ep, [[COPY8]].sub_dim_count:eds, [[COPY8]].sub_hi_dim_then_sub_dim_count:eds = LDA_TM_3D [[COPY]], [[COPY8]]
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $l0, %100:ep, %101:edcl, %102:edch = LDA_3D_dml_lda_scalar_L %0, %10
    $r4, %110:ep, %111:edcl, %112:edch = LDA_3D_dms_lda_scalar %0, %10
    $r4, %120:ep, %121:edcl, %122:edch = LDA_3D_s16 %0, %10
    $r4, %130:ep, %131:edcl, %132:edch = LDA_3D_s8 %0, %10
    $r4, %140:ep, %141:edcl, %142:edch = LDA_3D_u16 %0, %10
    $r4, %150:ep, %151:edcl, %152:edch = LDA_3D_u8 %0, %10
    $r0, %160:ep, %161:edcl, %162:edch = LDA_TM_3D %0, %10
...
