# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_fill_vlda
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24
    ; CHECK-LABEL: name: test_fill_vlda
    ; CHECK: liveins: $p0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2a = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_FILL [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2a = COPY $r24
    %3:eps, %4:eldfiforeg, %5:mref2a = VLDA_FILL %0, %1, %2

...
---
name:            test_fill_vldb
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24
    ; CHECK-LABEL: name: test_fill_vldb
    ; CHECK: liveins: $p0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2b = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_FILL [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2b = COPY $r24
    %3:eps, %4:eldfiforeg, %5:mref2b = VLDB_FILL %0, %1, %2

...
---
name:            test_fill_pseudo
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24
    ; CHECK-LABEL: name: test_fill_pseudo
    ; CHECK: liveins: $p0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2a = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_FILL_512_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2a = COPY $r24
    %3:eps, %4:eldfiforeg, %5:mref2a = VLD_FILL_512_pseudo %0, %1, %2

...
---
name:            test_fillx
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-LABEL: name: test_fillx
    ; CHECK: liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2b = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_FILLX $r30, $r30, [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $lfe, implicit $lfe
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2b = COPY $r24
    %3:eps, %4:eldfiforeg, %5:mref2b = VLDB_FILLX $r30, $r30, %0, %1, %2, implicit-def $lfe, implicit $lfe

...
---
name:            test_popx
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-LABEL: name: test_popx
    ; CHECK: liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mref2b = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE]].sub_ptr:epsrfldf, [[REG_SEQUENCE]].sub_fifo:epsrfldf, [[REG_SEQUENCE]].sub_avail:epsrfldf = VLDB_POPX $r30, $r30, [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe
    %0:eps = COPY $p0
    %1:eldfiforeg = COPY $lf0
    %2:mref2b = COPY $r24
    $x0, %3:eps, %4:eldfiforeg, %5:mref2b = VLDB_POPX $r30, $r30, %0, %1, %2, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe

...
