# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vlda_3d_basic
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d
    ; CHECK-LABEL: name: test_vlda_3d_basic
    ; CHECK: liveins: $p0, $d0_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_128 [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $feg0, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmw_lda_feg2 [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmw_lda_w [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x0, %11:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_x [[COPY]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $bmll0, %14:ep, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_bm [[COPY]], [[COPY6]]
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $wl0, %100:ep, %101:edcl, %102:edch = VLDA_3D_128 %0, %10
    $feg0, %110:ep, %111:edcl, %112:edch = VLDA_3D_dmw_lda_feg2 %0, %10
    $wl0, %120:ep, %121:edcl, %122:edch = VLDA_3D_dmw_lda_w %0, %10
    $x0, %130:ep, %131:edcl, %132:edch = VLDA_3D_dmx_lda_x %0, %10
    $bmll0, %140:ep, %141:edcl, %142:edch = VLDA_3D_dmx_lda_bm %0, %10
...
---
name:            test_vlda_3d_conv_ups
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d
    ; CHECK-LABEL: name: test_vlda_3d_conv_ups
    ; CHECK: liveins: $p0, $d0_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $bmll0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_bf16_dmw_lda_ups_bf16 [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cml0, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_bf16_dmx_lda_ups_f16 [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cml1, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_CONV_fp32_fp16 [[COPY]], [[COPY4]]
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $bmll0, %100:ep, %101:edcl, %102:edch = VLDA_3D_CONV_fp32_bf16_dmw_lda_ups_bf16 %0, %10
    $cml0, %110:ep, %111:edcl, %112:edch = VLDA_3D_CONV_fp32_bf16_dmx_lda_ups_f16 %0, %10
    $cml1, %120:ep, %121:edcl, %122:edch = VLDA_3D_CONV_fp32_fp16 %0, %10
...
---
name:            test_vlda_3d_ups_missing
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d, $s0
    ; CHECK-LABEL: name: test_vlda_3d_ups_missing
    ; CHECK: liveins: $p0, $d0_3d, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $bmll0, %3:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign0 [[COPY2]], [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $bmll1, %6:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1 [[COPY2]], [[COPY]], [[COPY4]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cmh0, %9:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign0 [[COPY2]], [[COPY]], [[COPY5]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cmh1, %12:ep, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign1 [[COPY2]], [[COPY]], [[COPY6]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cmh2, %15:ep, [[COPY7]].sub_dim_count:eds, [[COPY7]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign0 [[COPY2]], [[COPY]], [[COPY7]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cmh3, %18:ep, [[COPY8]].sub_dim_count:eds, [[COPY8]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign1 [[COPY2]], [[COPY]], [[COPY8]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $dm0, %21:ep, [[COPY9]].sub_dim_count:eds, [[COPY9]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0 [[COPY2]], [[COPY]], [[COPY9]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $dm1, %24:ep, [[COPY10]].sub_dim_count:eds, [[COPY10]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1 [[COPY2]], [[COPY]], [[COPY10]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %0:ep = COPY $p0
    %1:eds = COPY $d0_3d
    %2:es = COPY $s0
    $bmll0, %100:ep, %101:edcl, %102:edch = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign0 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $bmll1, %110:ep, %111:edcl, %112:edch = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cmh0, %120:ep, %121:edcl, %122:edch = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign0 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cmh1, %130:ep, %131:edcl, %132:edch = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign1 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cmh2, %160:ep, %161:edcl, %162:edch = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign0 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cmh3, %170:ep, %171:edcl, %172:edch = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign1 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $dm0, %180:ep, %181:edcl, %182:edch = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $dm1, %190:ep, %191:edcl, %192:edch = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1 %2, %0, %1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
...
