# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vlda_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-LABEL: name: test_vlda_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %6:ep, [[COPY5]].sub_dim_count:ed = VLDA_2D_128 [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %8:ep, [[COPY6]].sub_dim_count:ed = VLDA_2D_dmw_lda_w [[COPY4]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x0, %10:ep, [[COPY7]].sub_dim_count:ed = VLDA_2D_dmx_lda_x [[COPY4]], [[COPY7]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $bmll0, %12:ep, [[COPY8]].sub_dim_count:ed = VLDA_2D_dmx_lda_bm [[COPY4]], [[COPY8]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $feg0, %14:ep, [[COPY9]].sub_dim_count:ed = VLDA_2D_dmw_lda_feg2 [[COPY4]], [[COPY9]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $wl0, %100:ep, %101:edc = VLDA_2D_128 %4, %10
    $wl0, %120:ep, %121:edc = VLDA_2D_dmw_lda_w %4, %10
    $x0, %130:ep, %131:edc = VLDA_2D_dmx_lda_x %4, %10
    $bmll0, %150:ep, %151:edc = VLDA_2D_dmx_lda_bm %4, %10
    $feg0, %160:ep, %161:edc = VLDA_2D_dmw_lda_feg2 %4, %10
...
---
name:            test_vlda_2d_conv_ups
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-LABEL: name: test_vlda_2d_conv_ups
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cml1, %6:ep, [[COPY5]].sub_dim_count:ed = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_f16 [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cml0, %8:ep, [[COPY6]].sub_dim_count:ed = VLDA_2D_CONV_fp32_fp16 [[COPY4]], [[COPY6]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $cml1, %100:ep, %101:edc = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_f16 %4, %10
    $cml0, %120:ep, %121:edc = VLDA_2D_CONV_fp32_fp16 %4, %10
...
---
name:            test_vlda_2d_ups
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $s0
    ; CHECK-LABEL: name: test_vlda_2d_ups
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $bmll0, [[COPY4]]:ep, [[COPY6]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 [[COPY5]], [[COPY4]], [[COPY6]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $bmll1, %8:ep, [[COPY7]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 [[COPY5]], [[COPY4]], [[COPY7]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cmh0, %10:ep, [[COPY8]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 [[COPY5]], [[COPY4]], [[COPY8]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cmh1, %12:ep, [[COPY9]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1 [[COPY5]], [[COPY4]], [[COPY9]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cml0, %14:ep, [[COPY10]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 [[COPY5]], [[COPY4]], [[COPY10]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cml1, %16:ep, [[COPY11]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1 [[COPY5]], [[COPY4]], [[COPY11]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $dm2, %18:ep, [[COPY12]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 [[COPY5]], [[COPY4]], [[COPY12]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $dm3, %20:ep, [[COPY13]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 [[COPY5]], [[COPY4]], [[COPY13]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $bmll0, %22:ep, [[COPY14]].sub_dim_count:ed = VLDA_2D_CONV_fp32_bf16_dmw_lda_ups_bf16 [[COPY4]], [[COPY14]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %5:es = COPY $s0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $bmll0, %4:ep, %101:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $bmll1, %110:ep, %111:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cmh0, %120:ep, %121:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cmh1, %130:ep, %131:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cml0, %160:ep, %161:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cml1, %170:ep, %171:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $dm2, %180:ep, %181:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $dm3, %190:ep, %191:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 %5, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $bmll0, %200:ep, %201:edc = VLDA_2D_CONV_fp32_bf16_dmw_lda_ups_bf16 %4, %10
...
