# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_2d_scalar_loads
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-LABEL: name: test_2d_scalar_loads
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $l0, %6:ep, [[COPY5]].sub_dim_count:ed = LDA_2D_dml_lda_scalar_L [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $r4, %8:ep, [[COPY6]].sub_dim_count:ed = LDA_2D_dms_lda_scalar [[COPY4]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $r4, %10:ep, [[COPY7]].sub_dim_count:ed = LDA_2D_s16 [[COPY4]], [[COPY7]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $r4, %12:ep, [[COPY8]].sub_dim_count:ed = LDA_2D_s8 [[COPY4]], [[COPY8]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $r4, %14:ep, [[COPY9]].sub_dim_count:ed = LDA_2D_u16 [[COPY4]], [[COPY9]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $r4, %16:ep, [[COPY10]].sub_dim_count:ed = LDA_2D_u8 [[COPY4]], [[COPY10]]
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $r0, %18:ep, [[COPY11]].sub_dim_count:ed = LDA_TM_2D [[COPY4]], [[COPY11]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $l0, %100:ep, %101:edc = LDA_2D_dml_lda_scalar_L %4, %10
    $r4, %110:ep, %111:edc = LDA_2D_dms_lda_scalar %4, %10
    $r4, %120:ep, %121:edc = LDA_2D_s16 %4, %10
    $r4, %130:ep, %131:edc = LDA_2D_s8 %4, %10
    $r4, %140:ep, %141:edc = LDA_2D_u16 %4, %10
    $r4, %150:ep, %151:edc = LDA_2D_u8 %4, %10
    $r0, %160:ep, %161:edc = LDA_TM_2D %4, %10
...
