# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vst_2d_basic
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $wl0, $x0, $bmll0, $eg0, $feg0, $feg1
    ; CHECK-LABEL: name: test_vst_2d_basic
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $wl0, $x0, $bmll0, $eg0, $feg0, $feg1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_128_dmv_sts_eg:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:ed = VST_2D_128_dmv_sts_eg $eg0, [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_128_dmv_sts_feg:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:ed = VST_2D_128_dmv_sts_feg $fegl0, [[COPY4]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_128_dmv_sts_w:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:ed = VST_2D_128_dmv_sts_w $wl0, [[COPY4]], [[COPY7]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_dmw_sts_feg2_:%[0-9]+]]:ep, [[COPY8:%[0-9]+]].sub_dim_count:ed = VST_2D_dmw_sts_feg2 $feg1, [[COPY4]], [[COPY8]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_dmw_sts_w:%[0-9]+]]:ep, [[COPY9:%[0-9]+]].sub_dim_count:ed = VST_2D_dmw_sts_w $wl0, [[COPY4]], [[COPY9]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_dmx_sts_x:%[0-9]+]]:ep, [[COPY10:%[0-9]+]].sub_dim_count:ed = VST_2D_dmx_sts_x $x0, [[COPY4]], [[COPY10]]
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_dmx_sts_bm:%[0-9]+]]:ep, [[COPY11:%[0-9]+]].sub_dim_count:ed = VST_2D_dmx_sts_bm $bmll0, [[COPY4]], [[COPY11]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %100:ep, %101:edc = VST_2D_128_dmv_sts_eg $eg0, %4, %10
    %140:ep, %141:edc = VST_2D_128_dmv_sts_feg $fegl0, %4, %10
    %150:ep, %151:edc = VST_2D_128_dmv_sts_w $wl0, %4, %10
    %160:ep, %161:edc = VST_2D_dmw_sts_feg2 $feg1, %4, %10
    %110:ep, %111:edc = VST_2D_dmw_sts_w $wl0, %4, %10
    %120:ep, %121:edc = VST_2D_dmx_sts_x $x0, %4, %10
    %130:ep, %131:edc = VST_2D_dmx_sts_bm $bmll0, %4, %10
...
---
name:            test_vst_2d_conv
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $s0,$bmll0, $cml0, $cml1, $cml2, $cml3
    ; CHECK-LABEL: name: test_vst_2d_conv
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $s0, $bmll0, $cml0, $cml1, $cml2, $cml3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16_:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16 $bmll0, [[COPY4]], [[COPY6]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16_:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16 $cml0, [[COPY4]], [[COPY7]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_CONV_fp16_fp32_:%[0-9]+]]:ep, [[COPY8:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_fp16_fp32 $cml1, [[COPY4]], [[COPY8]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_CONV_fp8_fp32_:%[0-9]+]]:ep, [[COPY9:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_fp8_fp32 $cml2, [[COPY5]], [[COPY4]], [[COPY9]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_CONV_bf8_fp32_:%[0-9]+]]:ep, [[COPY10:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf8_fp32 $cml3, [[COPY5]], [[COPY4]], [[COPY10]], implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %5:es = COPY $s0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %100:ep, %101:edc = VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16 $bmll0, %4, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %110:ep, %111:edc = VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16 $cml0, %4, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %120:ep, %121:edc = VST_2D_CONV_fp16_fp32 $cml1, %4, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    %140:ep, %141:edc = VST_2D_CONV_fp8_fp32 $cml2, %5, %4, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    %150:ep, %151:edc = VST_2D_CONV_bf8_fp32 $cml3, %5, %4, %10, implicit-def $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
...
---
name:            test_vst_2d_pack
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $x0, $y0
    ; CHECK-LABEL: name: test_vst_2d_pack
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $x0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_PACK_dmw_sts_pack_packSign0_:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmw_sts_pack_packSign0 $x0, [[COPY4]], [[COPY5]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_PACK_dmw_sts_pack_packSign1_:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmw_sts_pack_packSign1 $x0, [[COPY4]], [[COPY6]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_PACK_dmx_sts_pack_packSign0_:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmx_sts_pack_packSign0 $y0, [[COPY4]], [[COPY7]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_PACK_dmx_sts_pack_packSign1_:%[0-9]+]]:ep, [[COPY8:%[0-9]+]].sub_dim_count:ed = VST_2D_PACK_dmx_sts_pack_packSign1 $y0, [[COPY4]], [[COPY8]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %100:ep, %101:edc = VST_2D_PACK_dmw_sts_pack_packSign0 $x0, %4, %10, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %110:ep, %111:edc = VST_2D_PACK_dmw_sts_pack_packSign1 $x0, %4, %10, implicit $crpacksize, implicit $crsat, implicit $packsign1
    %120:ep, %121:edc = VST_2D_PACK_dmx_sts_pack_packSign0 $y0, %4, %10, implicit $crpacksize, implicit $crsat, implicit $packsign0
    %130:ep, %131:edc = VST_2D_PACK_dmx_sts_pack_packSign1 $y0, %4, %10, implicit $crpacksize, implicit $crsat, implicit $packsign1
...
---
name:            test_vst_2d_new_feg2
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $feg0
    %0:em = COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %100:ep, %101:edc = VST_2D_dmw_sts_feg2 $feg0, %4, %10
...
