# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vlda_3d_pop_ex_bfp16
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_3d_pop_ex_bfp16
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDA_POP_3D_dmx_lda_fifo_ex_bfp16_:%[0-9]+]]:mexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_ex_bfp16 [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_3D_dmx_lda_fifo_ex_bfp16_]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mexa, %11:eps, %12:eldfiforeg, %13:mref2a, %14:edcl, %15:edch = VLDA_POP_3D_dmx_lda_fifo_ex_bfp16 %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vlda_3d_pop_fex_bfp13
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_3d_pop_fex_bfp13
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDA_POP_3D_dmx_lda_fifo_fex_bfp13_:%[0-9]+]]:mfexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_3D_dmx_lda_fifo_fex_bfp13 [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_3D_dmx_lda_fifo_fex_bfp13_]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mfexa, %11:eps, %12:eldfiforeg, %13:mref2a, %14:edcl, %15:edch = VLDA_POP_3D_dmx_lda_fifo_fex_bfp13 %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vldb_3d_pop_ex_bfp16
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_3d_pop_ex_bfp16
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDB_POP_3D_dmx_ldb_fifo_ex_bfp16_:%[0-9]+]]:mexb, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_ex_bfp16 [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_3D_dmx_ldb_fifo_ex_bfp16_]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mexb, %11:eps, %12:eldfiforeg, %13:mref2b, %14:edcl, %15:edch = VLDB_POP_3D_dmx_ldb_fifo_ex_bfp16 %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vldb_3d_pop_fex_bfp13
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_3d_pop_fex_bfp13
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDB_POP_3D_dmx_ldb_fifo_fex_bfp13_:%[0-9]+]]:mfexb, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_3D_dmx_ldb_fifo_fex_bfp13 [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_3D_dmx_ldb_fifo_fex_bfp13_]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mfexb, %11:eps, %12:eldfiforeg, %13:mref2b, %14:edcl, %15:edch = VLDB_POP_3D_dmx_ldb_fifo_fex_bfp13 %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vlda_3d_pop_s
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_3d_pop_s
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDA_POP_s_3D:%[0-9]+]]:mexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_s_3D [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_s_3D]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mexa, %11:eps, %12:eldfiforeg, %13:mref2a, %14:edcl, %15:edch = VLDA_POP_s_3D %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vldb_3d_pop_s
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_3d_pop_s
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDB_POP_s_3D:%[0-9]+]]:mexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_s_3D [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_s_3D]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mexa, %11:eps, %12:eldfiforeg, %13:mref2b, %14:edcl, %15:edch = VLDB_POP_s_3D %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vlda_3d_pop_mx4
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_3d_pop_mx4
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDA_POP_mx4_3D:%[0-9]+]]:mfexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_mx4_3D [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_mx4_3D]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mfexa, %11:eps, %12:eldfiforeg, %13:mref2a, %14:edcl, %15:edch = VLDA_POP_mx4_3D %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vldb_3d_pop_mx4
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_3d_pop_mx4
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLDB_POP_mx4_3D:%[0-9]+]]:mfexb, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_mx4_3D [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_mx4_3D]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mfexb, %11:eps, %12:eldfiforeg, %13:mref2b, %14:edcl, %15:edch = VLDB_POP_mx4_3D %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vld_3d_pop_640
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vld_3d_pop_640
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_640_3D_pseudo:%[0-9]+]]:mexa, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_640_3D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_640_3D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mexa, %11:eps, %12:eldfiforeg, %13:mref2a, %14:edcl, %15:edch = VLD_POP_640_3D_pseudo %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
---
name:            test_vld_3d_pop_768
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vld_3d_pop_768
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eds = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_768_3D_pseudo:%[0-9]+]]:mfexb, [[REG_SEQUENCE1:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE1:%[0-9]+]].sub_avail:epsrfldf, [[COPY:%[0-9]+]].sub_dim_count:eds, [[COPY:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_768_3D_pseudo [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_768_3D_pseudo]], implicit [[REG_SEQUENCE1]].sub_ptr, implicit [[REG_SEQUENCE1]].sub_fifo, implicit [[REG_SEQUENCE1]].sub_avail, implicit [[COPY]].sub_dim_count, implicit [[COPY]].sub_hi_dim_then_sub_dim_count
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:edn = IMPLICIT_DEF
    %5:edc = IMPLICIT_DEF
    %6:edj = IMPLICIT_DEF
    %7:edn = IMPLICIT_DEF
    %8:edc = IMPLICIT_DEF
    %9:edj = IMPLICIT_DEF
    %16:eds = REG_SEQUENCE %3, %subreg.sub_mod, %4, %subreg.sub_dim_size, %6, %subreg.sub_dim_stride, %5, %subreg.sub_dim_count, %7, %subreg.sub_hi_dim_then_sub_dim_size, %9, %subreg.sub_hi_dim_then_sub_dim_stride, %8, %subreg.sub_hi_dim_then_sub_dim_count
    %10:mfexb, %11:eps, %12:eldfiforeg, %13:mref2a, %14:edcl, %15:edch = VLD_POP_768_3D_pseudo %0, %1, %2, %16, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...
