# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vld_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-LABEL: name: test_vld_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %6:ep, [[COPY5]].sub_dim_count:ed = VLD_2D_128_pseudo [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %8:ep, [[COPY6]].sub_dim_count:ed = VLD_2D_w_pseudo [[COPY4]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x0, %10:ep, [[COPY7]].sub_dim_count:ed = VLD_2D_x_pseudo [[COPY4]], [[COPY7]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $wl0, %110:ep, %111:edc = VLD_2D_128_pseudo %4, %10
    $wl0, %140:ep, %141:edc = VLD_2D_w_pseudo %4, %10
    $x0, %170:ep, %171:edc = VLD_2D_x_pseudo %4, %10
...
