# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vldb_3d_basic
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d
    ; CHECK-LABEL: name: test_vldb_3d_basic
    ; CHECK: liveins: $p0, $d0_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wh0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_128 [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wh0, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmw_ldb [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x1, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmx_ldb_x [[COPY]], [[COPY4]]
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $wh0, %100:ep, %101:edcl, %102:edch = VLDB_3D_128 %0, %10
    $wh0, %110:ep, %111:edcl, %112:edch = VLDB_3D_dmw_ldb %0, %10
    $x1, %120:ep, %121:edcl, %122:edch = VLDB_3D_dmx_ldb_x %0, %10
...
---
name:            test_vldb_3d_unpack
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d
    ; CHECK-LABEL: name: test_vldb_3d_unpack
    ; CHECK: liveins: $p0, $d0_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x0, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 [[COPY]], [[COPY3]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $y0, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 [[COPY]], [[COPY4]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $y0, %11:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 [[COPY]], [[COPY5]], implicit $crunpacksize, implicit $unpacksign1
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $x0, %100:ep, %101:edcl, %102:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 %0, %10, implicit $crunpacksize, implicit $unpacksign0
    $x0, %110:ep, %111:edcl, %112:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 %0, %10, implicit $crunpacksize, implicit $unpacksign1
    $y0, %120:ep, %121:edcl, %122:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 %0, %10, implicit $crunpacksize, implicit $unpacksign0
    $y0, %130:ep, %131:edcl, %132:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 %0, %10, implicit $crunpacksize, implicit $unpacksign1
...
