# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_st_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $l0, $r4, $f0
    ; CHECK-LABEL: name: test_st_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $l0, $r4, $f0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_dml_sts_scalar:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:ed = ST_2D_dml_sts_scalar $l0, [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_dms_sts_scalar:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:ed = ST_2D_dms_sts_scalar $r4, [[COPY4]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_s16_:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:ed = ST_2D_s16 $r4, [[COPY4]], [[COPY7]], implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_s8_:%[0-9]+]]:ep, [[COPY8:%[0-9]+]].sub_dim_count:ed = ST_2D_s8 $r4, [[COPY4]], [[COPY8]], implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_TM_2D:%[0-9]+]]:ep, [[COPY9:%[0-9]+]].sub_dim_count:ed = ST_TM_2D $r0, [[COPY4]], [[COPY9]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_dmv_sts_f:%[0-9]+]]:ep, [[COPY10:%[0-9]+]].sub_dim_count:ed = ST_2D_dmv_sts_f $f0, [[COPY4]], [[COPY10]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %100:ep, %101:edc = ST_2D_dml_sts_scalar $l0, %4, %10
    %110:ep, %111:edc = ST_2D_dms_sts_scalar $r4, %4, %10
    %120:ep, %121:edc = ST_2D_s16 $r4, %4, %10, implicit-def $pe2_ads, implicit $pe2_ads
    %130:ep, %131:edc = ST_2D_s8 $r4, %4, %10, implicit-def $pe2_ads, implicit $pe2_ads
    %140:ep, %141:edc = ST_TM_2D $r0, %4, %10
    %150:ep, %151:edc = ST_2D_dmv_sts_f $f0, %4, %10
...
