# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vlda_1d_pop_x
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_1d_pop_x
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop:%[0-9]+]]:mxa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mxa, %5:eps, %6:eldfiforeg, %7:mref2a = VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vlda_1d_pop_ex_bfp16
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_1d_pop_ex_bfp16
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDA_POP_dmx_lda_fifo_ex_bfp16_fifo_1d_pop:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_POP_dmx_lda_fifo_ex_bfp16_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_dmx_lda_fifo_ex_bfp16_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mexa, %5:eps, %6:eldfiforeg, %7:mref2a = VLDA_POP_dmx_lda_fifo_ex_bfp16_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vlda_1d_pop_fex_bfp13
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_1d_pop_fex_bfp13
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDA_POP_dmx_lda_fifo_fex_bfp13_fifo_1d_pop:%[0-9]+]]:mfexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_POP_dmx_lda_fifo_fex_bfp13_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_dmx_lda_fifo_fex_bfp13_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mfexa, %5:eps, %6:eldfiforeg, %7:mref2a = VLDA_POP_dmx_lda_fifo_fex_bfp13_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vldb_1d_pop_x
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_1d_pop_x
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDB_POP_dmx_ldb_fifo_x_fifo_1d_pop:%[0-9]+]]:mxb, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_POP_dmx_ldb_fifo_x_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_dmx_ldb_fifo_x_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mxb, %5:eps, %6:eldfiforeg, %7:mref2b = VLDB_POP_dmx_ldb_fifo_x_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vldb_1d_pop_ex_bfp16
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_1d_pop_ex_bfp16
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDB_POP_dmx_ldb_fifo_ex_bfp16_fifo_1d_pop:%[0-9]+]]:mexb, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_POP_dmx_ldb_fifo_ex_bfp16_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_dmx_ldb_fifo_ex_bfp16_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mexb, %5:eps, %6:eldfiforeg, %7:mref2b = VLDB_POP_dmx_ldb_fifo_ex_bfp16_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vldb_1d_pop_fex_bfp13
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_1d_pop_fex_bfp13
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDB_POP_dmx_ldb_fifo_fex_bfp13_fifo_1d_pop:%[0-9]+]]:mfexb, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_POP_dmx_ldb_fifo_fex_bfp13_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_dmx_ldb_fifo_fex_bfp13_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mfexb, %5:eps, %6:eldfiforeg, %7:mref2b = VLDB_POP_dmx_ldb_fifo_fex_bfp13_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vlda_1d_pop_s
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_1d_pop_s
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDA_POP_s_fifo_1d_pop:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_POP_s_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_s_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mexa, %5:eps, %6:eldfiforeg, %7:mref2a = VLDA_POP_s_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vldb_1d_pop_s
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_1d_pop_s
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDB_POP_s_fifo_1d_pop:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_POP_s_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_s_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mexa, %5:eps, %6:eldfiforeg, %7:mref2b = VLDB_POP_s_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vlda_1d_pop_mx4
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vlda_1d_pop_mx4
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDA_POP_mx4_fifo_1d_pop:%[0-9]+]]:mfexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_POP_mx4_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_POP_mx4_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mfexa, %5:eps, %6:eldfiforeg, %7:mref2a = VLDA_POP_mx4_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vldb_1d_pop_mx4
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vldb_1d_pop_mx4
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLDB_POP_mx4_fifo_1d_pop:%[0-9]+]]:mfexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_POP_mx4_fifo_1d_pop [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POP_mx4_fifo_1d_pop]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mfexa, %5:eps, %6:eldfiforeg, %7:mref2b = VLDB_POP_mx4_fifo_1d_pop %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vld_1d_pop_512
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vld_1d_pop_512
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLD_POP_512_fifo_1d_pop_pseudo:%[0-9]+]]:mxa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_POP_512_fifo_1d_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_fifo_1d_pop_pseudo]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2a = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mxa, %5:eps, %6:eldfiforeg, %7:mref2b = VLD_POP_512_fifo_1d_pop_pseudo %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vld_1d_pop_640
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vld_1d_pop_640
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLD_POP_640_fifo_1d_pop_pseudo:%[0-9]+]]:mexa, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_POP_640_fifo_1d_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_640_fifo_1d_pop_pseudo]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mexa, %5:eps, %6:eldfiforeg, %7:mref2b = VLD_POP_640_fifo_1d_pop_pseudo %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
---
name:            test_vld_1d_pop_768
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vld_1d_pop_768
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mref2b = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[DEF]], %subreg.sub_ptr, [[DEF1]], %subreg.sub_fifo, [[DEF2]], %subreg.sub_avail
    ; CHECK-NEXT: [[VLD_POP_768_fifo_1d_pop_pseudo:%[0-9]+]]:mfexb, [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLD_POP_768_fifo_1d_pop_pseudo [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_768_fifo_1d_pop_pseudo]], implicit [[REG_SEQUENCE]].sub_ptr, implicit [[REG_SEQUENCE]].sub_fifo, implicit [[REG_SEQUENCE]].sub_avail
    %0:eps = IMPLICIT_DEF
    %1:eldfiforeg = IMPLICIT_DEF
    %2:mref2b = IMPLICIT_DEF
    %3:em = IMPLICIT_DEF
    %4:mfexb, %5:eps, %6:eldfiforeg, %7:mref2b = VLD_POP_768_fifo_1d_pop_pseudo %0, %1, %2, %3, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit %4, implicit %5, implicit %6, implicit %7

...
