# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_lda_2d_dml_variants
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d1
    ; CHECK-LABEL: name: test_lda_2d_dml_variants
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dml_lda_scalar_F:%[0-9]+]]:mfa, [[LDA_2D_dml_lda_scalar_F1:%[0-9]+]]:ep, [[COPY2]].sub_dim_count:ed = LDA_2D_dml_lda_scalar_F [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dml_lda2_scalar_EE:%[0-9]+]]:meea, [[LDA_2D_dml_lda2_scalar_EE1:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:ed = LDA_2D_dml_lda2_scalar_EE [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dml_lda2_scalar_EG:%[0-9]+]]:mega, [[LDA_2D_dml_lda2_scalar_EG1:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:ed = LDA_2D_dml_lda2_scalar_EG [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dml_lda2_scalar_GG:%[0-9]+]]:mgga, [[LDA_2D_dml_lda2_scalar_GG1:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:ed = LDA_2D_dml_lda2_scalar_GG [[COPY]], [[COPY5]]
    %0:ep = COPY $p0
    %1:ed = COPY $d1
    %100:mfa, %101:ep, %102:edc = LDA_2D_dml_lda_scalar_F %0, %1
    %110:meea, %111:ep, %112:edc = LDA_2D_dml_lda2_scalar_EE %0, %1
    %120:mega, %121:ep, %122:edc = LDA_2D_dml_lda2_scalar_EG %0, %1
    %130:mgga, %131:ep, %132:edc = LDA_2D_dml_lda2_scalar_GG %0, %1

...
---
name:            test_lda_2d_dms_dmv_variants
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d1
    ; CHECK-LABEL: name: test_lda_2d_dms_dmv_variants
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dms_lda_g:%[0-9]+]]:mga, [[LDA_2D_dms_lda_g1:%[0-9]+]]:ep, [[COPY2]].sub_dim_count:ed = LDA_2D_dms_lda_g [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dmv_lda_f:%[0-9]+]]:mffa, [[LDA_2D_dmv_lda_f1:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:ed = LDA_2D_dmv_lda_f [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dmv_lda_feg:%[0-9]+]]:mfega, [[LDA_2D_dmv_lda_feg1:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:ed = LDA_2D_dmv_lda_feg [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_2D_dmv_lda_eg2:%[0-9]+]]:meg2a, [[LDA_2D_dmv_lda_eg21:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:ed = LDA_2D_dmv_lda_eg2 [[COPY]], [[COPY5]]
    %0:ep = COPY $p0
    %1:ed = COPY $d1
    %100:mga, %101:ep, %102:edc = LDA_2D_dms_lda_g %0, %1
    %110:mffa, %111:ep, %112:edc = LDA_2D_dmv_lda_f %0, %1
    %120:mfega, %121:ep, %122:edc = LDA_2D_dmv_lda_feg %0, %1
    %130:meg2a, %131:ep, %132:edc = LDA_2D_dmv_lda_eg2 %0, %1

...
---
name:            test_lda_3d_dml_variants
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d
    ; CHECK-LABEL: name: test_lda_3d_dml_variants
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dml_lda_scalar_F:%[0-9]+]]:mfa, [[LDA_3D_dml_lda_scalar_F1:%[0-9]+]]:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda_scalar_F [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dml_lda2_scalar_EE:%[0-9]+]]:meea, [[LDA_3D_dml_lda2_scalar_EE1:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_EE [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dml_lda2_scalar_EG:%[0-9]+]]:mega, [[LDA_3D_dml_lda2_scalar_EG1:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_EG [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dml_lda2_scalar_GG:%[0-9]+]]:mgga, [[LDA_3D_dml_lda2_scalar_GG1:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dml_lda2_scalar_GG [[COPY]], [[COPY5]]
    %0:ep = COPY $p0
    %1:eds = COPY $d0_3d
    %100:mfa, %101:ep, %102:edcl, %103:edch = LDA_3D_dml_lda_scalar_F %0, %1
    %110:meea, %111:ep, %112:edcl, %113:edch = LDA_3D_dml_lda2_scalar_EE %0, %1
    %120:mega, %121:ep, %122:edcl, %123:edch = LDA_3D_dml_lda2_scalar_EG %0, %1
    %130:mgga, %131:ep, %132:edcl, %133:edch = LDA_3D_dml_lda2_scalar_GG %0, %1

...
---
name:            test_lda_3d_dms_dmv_variants
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d
    ; CHECK-LABEL: name: test_lda_3d_dms_dmv_variants
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dms_lda_g:%[0-9]+]]:mga, [[LDA_3D_dms_lda_g1:%[0-9]+]]:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dms_lda_g [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dmv_lda_f:%[0-9]+]]:mffa, [[LDA_3D_dmv_lda_f1:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_f [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dmv_lda_feg:%[0-9]+]]:mfega, [[LDA_3D_dmv_lda_feg1:%[0-9]+]]:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_feg [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[LDA_3D_dmv_lda_eg2:%[0-9]+]]:meg2a, [[LDA_3D_dmv_lda_eg21:%[0-9]+]]:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = LDA_3D_dmv_lda_eg2 [[COPY]], [[COPY5]]
    %0:ep = COPY $p0
    %1:eds = COPY $d0_3d
    %100:mga, %101:ep, %102:edcl, %103:edch = LDA_3D_dms_lda_g %0, %1
    %110:mffa, %111:ep, %112:edcl, %113:edch = LDA_3D_dmv_lda_f %0, %1
    %120:mfega, %121:ep, %122:edcl, %123:edch = LDA_3D_dmv_lda_feg %0, %1
    %130:meg2a, %131:ep, %132:edcl, %133:edch = LDA_3D_dmv_lda_eg2 %0, %1

...
---
name:            test_st_2d_dml_dms_variants
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d1, $l0, $gl0
    ; CHECK-LABEL: name: test_st_2d_dml_dms_variants
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_2D_dml_sts_scalar:%[0-9]+]]:ep, [[COPY2]].sub_dim_count:ed = ST_2D_dml_sts_scalar $l0, [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ed = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_2D_dms_sts_g:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:ed = ST_2D_dms_sts_g $gl0, [[COPY]], [[COPY3]]
    %0:ep = COPY $p0
    %1:ed = COPY $d1
    %100:ep, %101:edc = ST_2D_dml_sts_scalar $l0, %0, %1
    %110:ep, %111:edc = ST_2D_dms_sts_g $gl0, %0, %1

...
---
name:            test_st_3d_dml_dms_variants
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d0_3d, $l0, $gl0
    ; CHECK-LABEL: name: test_st_3d_dml_dms_variants
    ; CHECK: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_dml_sts_scalar:%[0-9]+]]:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dml_sts_scalar $l0, [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_dms_sts_g:%[0-9]+]]:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dms_sts_g $gl0, [[COPY]], [[COPY3]]
    %0:ep = COPY $p0
    %1:eds = COPY $d0_3d
    %100:ep, %101:edcl, %102:edch = ST_3D_dml_sts_scalar $l0, %0, %1
    %110:ep, %111:edcl, %112:edch = ST_3D_dms_sts_g $gl0, %0, %1

...
