# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# NOTE: Example file for Write After Write Register Renaming in Loop test
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# Basic test for the WAW register renaming pass. Check AIE2 tests for more coverage.

# RUN: llc -mtriple=aie2ps -verify-machineinstrs --start-before=greedy --stop-after=virtregrewriter %s -o - | FileCheck %s

# Make sure VLD and VMAX define different X registers.
---
name:            simple_waw_replacement
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: simple_waw_replacement
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ST_R_SPILL $p0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
  ; CHECK-NEXT:   VST_X_SPILL $x0, %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   ST_R_SPILL $p1, %stack.2, implicit $sp :: (store (s32) into %stack.2)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $d0, $d2, $p0, $p1, $p2, $d1_3d
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $p0 = LDA_R_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
  ; CHECK-NEXT:   renamable $x0, renamable $p0 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p0, 64
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $p0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
  ; CHECK-NEXT:   renamable $x2 = VLDA_X_SPILL %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   renamable $x0, $r16 = VMAX_LT_16_vaddSign1 killed renamable $x0, killed renamable $x2, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $p0 = LDA_R_SPILL %stack.2, implicit $sp :: (load (s32) from %stack.2)
  ; CHECK-NEXT:   renamable $p0 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x0, killed renamable $p0, 64
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $p0, %stack.2, implicit $sp :: (store (s32) into %stack.2)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
  successors: %bb.1
  liveins: $r0, $p0, $p1, $x0
    %0:ep = COPY $p0
    %1:vec512 = COPY $x0
    %2:ep = COPY $p1
  bb.1:
    successors: %bb.1
    liveins: $p0, $p1, $p2, $d0, $d1_3d, $d2
    %10:vec512, %0:ep = VLDA_dmx_lda_x_ld_pstm_nrm_imm %0, 64
    %11:vec512, $r16 = VMAX_LT_16_vaddSign1 %10, %1, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
    %2:ep = VST_dmx_sts_x_st_pstm_nrm_imm %11, %2, 64
    PseudoRET implicit $lr
...
