# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# Cross-bank copies (e.g., pointer to GPR) should not prevent the destination
# virtual register from being a WAW renaming candidate. These copies can never
# be folded and always require an actual data-move instruction, so excluding
# them from renaming is overly conservative.

# RUN: llc -mtriple=aie2ps -verify-machineinstrs --start-before=greedy --stop-after=virtregrewriter \
# RUN:   --aie-gpr-realloc %s -o - | FileCheck %s

# The loop body copies the same pointer register into a GPR, then masks it
# with AND. Without the fix, getVRegWithCopies marks %0 as "used in a copy"
# because the COPY instruction is detected -- even though source (ep_as_32bit)
# and destination (mlockid_reg) are in different register banks. This blocks
# the WAW renamer from diversifying the physical register.
---
name:            cross_bank_copy_gpr_renaming
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: cross_bank_copy_gpr_renaming
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LoopStart $r0, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r1, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = COPY renamable $p0
  ; CHECK-NEXT:   renamable $r2 = AND killed renamable $r0, renamable $r1
  ; CHECK-NEXT:   renamable $r4 = COPY renamable $p0
  ; CHECK-NEXT:   renamable $r6 = AND killed renamable $r4, renamable $r1
  ; CHECK-NEXT:   renamable $r16 = AND killed renamable $r2, killed renamable $r6
  ; CHECK-NEXT:   dead renamable $r18 = AND killed renamable $r16, renamable $r1
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_1120>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
  successors: %bb.1
  liveins: $r0, $p0, $r1
    %10:ep_as_32bit = COPY $p0
    %11:mlockid_reg = COPY $r1
    LoopStart $r0, 0
  bb.1:
    successors: %bb.1, %bb.2
    liveins: $x0
    %0:mlockid_reg = COPY %10
    %1:mlockid_reg = AND %0, %11
    %2:mlockid_reg = COPY %10
    %3:mlockid_reg = AND %2, %11
    %4:mlockid_reg = AND %1, %3
    dead %5:mlockid_reg = AND %4, %11
    PseudoLoopEnd <mcsymbol .L_1120>, %bb.1, implicit $ls, implicit $le
  bb.2:
    PseudoRET implicit $lr
...

# Same-bank copies (GPR -> GPR) should still be protected from renaming
# to preserve copy-folding opportunities.
---
name:            same_bank_copy_not_renamed
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: same_bank_copy_not_renamed
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LoopStart $r0, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r1, $r2, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = COPY renamable $r1
  ; CHECK-NEXT:   renamable $r0 = AND killed renamable $r0, renamable $r2
  ; CHECK-NEXT:   renamable $r4 = COPY renamable $r1
  ; CHECK-NEXT:   renamable $r4 = AND killed renamable $r4, renamable $r2
  ; CHECK-NEXT:   renamable $r6 = AND killed renamable $r0, killed renamable $r4
  ; CHECK-NEXT:   dead renamable $r16 = AND killed renamable $r6, renamable $r2
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_1120>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
  successors: %bb.1
  liveins: $r0, $r1, $r2
    %10:mlockid_reg = COPY $r1
    %11:mlockid_reg = COPY $r2
    LoopStart $r0, 0
  bb.1:
    successors: %bb.1, %bb.2
    liveins: $x0
    %0:mlockid_reg = COPY %10
    %1:mlockid_reg = AND %0, %11
    %2:mlockid_reg = COPY %10
    %3:mlockid_reg = AND %2, %11
    %4:mlockid_reg = AND %1, %3
    dead %5:mlockid_reg = AND %4, %11
    PseudoLoopEnd <mcsymbol .L_1120>, %bb.1, implicit $ls, implicit $le
  bb.2:
    PseudoRET implicit $lr
...
