# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: load_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_s32
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[LDA_ind_GPR:%[0-9]+]]:gpr = LDA_ind_GPR [[COPY]] :: (load (s32))
    ; CHECK-NEXT: $r0 = COPY [[LDA_ind_GPR]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = G_LOAD %0 :: (load (s32), align 4)
    $r0 = COPY %1
...

---
name: load_ext_s8
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_ext_s8
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[LDA_s8_ind:%[0-9]+]]:gpr0_7 = LDA_s8_ind [[COPY]] :: (load (s8))
    ; CHECK-NEXT: $r0 = COPY [[LDA_s8_ind]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = G_LOAD %0 :: (load (s8), align 1)
    $r0 = COPY %1
...

---
name: load_ext_s16
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_ext_s16
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[LDA_s16_ind:%[0-9]+]]:gpr0_7 = LDA_s16_ind [[COPY]] :: (load (s16))
    ; CHECK-NEXT: $r0 = COPY [[LDA_s16_ind]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = G_LOAD %0 :: (load (s16), align 2)
    $r0 = COPY %1
...

---
name: load_p0_ptr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_p0_ptr
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[LDA_ind_PTR:%[0-9]+]]:ptr = LDA_ind_PTR [[COPY]]
    ; CHECK-NEXT: $p0 = COPY [[LDA_ind_PTR]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = G_LOAD %0 :: (load (p0), align 4)
    $p0 = COPY %1
...

---
name: load_p0_gpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_p0_gpr
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[LDA_ind_GPR:%[0-9]+]]:gpr = LDA_ind_GPR [[COPY]] :: (load (p0), align 4)
    ; CHECK-NEXT: $p0 = COPY [[LDA_ind_GPR]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(p0) = G_LOAD %0 :: (load (p0), align 4)
    $p0 = COPY %1
...

---
name: load_p0_ptr_as_32bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_p0_ptr_as_32bits
    ; CHECK: [[COPY:%[0-9]+]]:gprptrmod_and_ptr = COPY $p0
    ; CHECK-NEXT: [[LDA_ind_PTR:%[0-9]+]]:ptr = LDA_ind_PTR [[COPY]]
    ; CHECK-NEXT: $p0 = COPY [[LDA_ind_PTR]]
    %0:gprptrmod_and_ptr(p0) = COPY $p0
    %1:ptrregbank(p0) = G_LOAD %0 :: (load (p0), align 4)
    $p0 = COPY %1
...

---
name: load_s20
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_s20
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[LDA_ind_MOD:%[0-9]+]]:mod = LDA_ind_MOD [[COPY]] :: (load (s20), align 4)
    ; CHECK-NEXT: $m1 = COPY [[LDA_ind_MOD]]
    ; CHECK-NEXT: [[LDA_ind_MOD1:%[0-9]+]]:mod = LDA_ind_MOD [[COPY]] :: (load (s20), align 4)
    ; CHECK-NEXT: $m2 = COPY [[LDA_ind_MOD1]]
    %0:ptrregbank(p0) = COPY $p0
    %1:modregbank(s20) = G_LOAD %0 :: (load (s20), align 4)
    $m1 = COPY %1
    %2:mod(s20) = G_LOAD %0 :: (load (s20), align 4)
    $m2 = COPY %2
...
