# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: store_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; CHECK-LABEL: name: store_s32
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: ST_ind_GPR [[COPY1]], [[COPY]] :: (store (s32))
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s32))
...

---
name: store_s8
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; CHECK-LABEL: name: store_s8
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: ST_s8_ind [[COPY1]], [[COPY]] :: (store (s8))
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s8))
...

---
name: store_s16
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; CHECK-LABEL: name: store_s16
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: ST_s16_ind [[COPY1]], [[COPY]] :: (store (s16))
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s16))
...

---
name: store_p0_ptr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: store_p0_ptr
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptr = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:msclst_ptr = COPY [[COPY1]]
    ; CHECK-NEXT: ST_ind_PTR [[COPY2]], [[COPY]] :: (store (p0), align 4)
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    G_STORE %1, %0 :: (store (p0))
...

---
name: store_p0_gpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: store_p0_gpr
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptr = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr = COPY [[COPY1]]
    ; CHECK-NEXT: ST_ind_GPR [[COPY2]], [[COPY]] :: (store (p0), align 4)
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %1
    G_STORE %2, %0 :: (store (p0))
...

---
name: store_s20
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $m0, $m6, $m7, $p0
    ; CHECK-LABEL: name: store_s20
    ; CHECK: liveins: $m0, $m6, $m7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mod = COPY $m6
    ; CHECK-NEXT: ST_ind_MOD [[COPY1]], [[COPY]] :: (store (s20), align 4)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mod = COPY $m0
    ; CHECK-NEXT: ST_ind_MOD [[COPY2]], [[COPY]] :: (store (s20), align 4)
    %0:ptrregbank(p0) = COPY $p0
    %1:modregbank(s20) = COPY $m6
    G_STORE %1, %0 :: (store (s20))
    %2:mod(s20) = COPY $m0
    G_STORE %2, %0 :: (store (s20))
...
