# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: ptr_add
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $r6
    ; CHECK-LABEL: name: ptr_add
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr = COPY [[COPY]]
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY2]], [[COPY1]]
    ; CHECK-NEXT: $p0 = COPY [[ADD]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r6
    %2:gprregbank(s20) = G_TRUNC %1
    %3:gprregbank(p0) = COPY %0(p0)
    %4:gprregbank(p0) = G_PTR_ADD %3, %2
    $p0 = COPY %4
...

---
name: ptr_add_s20_on_ptr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: ptr_add_s20_on_ptr
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptr = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mod = COPY [[COPY1]]
    ; CHECK-NEXT: [[PADDA_nrm:%[0-9]+]]:ptr = PADDA_nrm [[COPY]], [[COPY2]]
    ; CHECK-NEXT: $p0 = COPY [[PADDA_nrm]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(s20) = COPY $p1
    %2:modregbank(s20) = COPY %1
    %3:ptrregbank(p0) = G_PTR_ADD %0, %2
    $p0 = COPY %3
...

---
name: ptr_add_s20_on_ptr_as_32bit
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: ptr_add_s20_on_ptr_as_32bit
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprptrmod_and_ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptr = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mod = COPY [[COPY1]]
    ; CHECK-NEXT: [[PADDA_nrm:%[0-9]+]]:ptr = PADDA_nrm [[COPY]], [[COPY2]]
    ; CHECK-NEXT: $p0 = COPY [[PADDA_nrm]]
    %0:gprptrmod_and_ptr(p0) = COPY $p0
    %1:ptrregbank(s20) = COPY $p1
    %2:modregbank(s20) = COPY %1
    %3:ptrregbank(p0) = G_PTR_ADD %0, %2
    $p0 = COPY %3
...
