# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name: COPY_ptr_mod_cb
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: COPY_ptr_mod_cb
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: $m0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: $cs0 = COPY [[COPY]](p0)
    %0:_(p0) = COPY $p0
    $m0 = COPY %0
    $cs0 = COPY %0
...

---
name: COPY_mod_ptr_cs
legalized: true

body: |
  bb.0:
    liveins: $m0
    ; CHECK-LABEL: name: COPY_mod_ptr_cs
    ; CHECK: [[COPY:%[0-9]+]]:modregbank(p0) = COPY $m0
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: $cs0 = COPY [[COPY]](p0)
    %0:_(p0) = COPY $m0
    $p0 = COPY %0
    $cs0 = COPY %0
...

---
name: COPY_cs_ptr_mod
legalized: true

body: |
  bb.0:
    liveins: $cs0
    ; CHECK-LABEL: name: COPY_cs_ptr_mod
    ; CHECK: [[COPY:%[0-9]+]]:cbregbank(p0) = COPY $cs0
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: $m0 = COPY [[COPY]](p0)
    %0:_(p0) = COPY $cs0
    $p0 = COPY %0
    $m0 = COPY %0
...
