# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name: COPY_gpr
legalized: true

body: |
  bb.0:
    liveins: $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7, $r8, $r9, $r10, $r11, $r12, $r13, $r14, $r15
    ; CHECK-LABEL: name: COPY_gpr
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(s32) = COPY $r5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:gprregbank(s32) = COPY $r7
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:gprregbank(s32) = COPY $r8
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:gprregbank(s32) = COPY $r9
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:gprregbank(s32) = COPY $r10
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:gprregbank(s32) = COPY $r11
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:gprregbank(s32) = COPY $r12
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:gprregbank(s32) = COPY $r13
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:gprregbank(s32) = COPY $r14
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:gprregbank(s32) = COPY $r15
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:gprregbank(p0) = COPY $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY]](s32)
    ; CHECK-NEXT: $r1 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: $r2 = COPY [[COPY2]](s32)
    ; CHECK-NEXT: $r3 = COPY [[COPY3]](s32)
    ; CHECK-NEXT: $r4 = COPY [[COPY4]](s32)
    ; CHECK-NEXT: $r5 = COPY [[COPY5]](s32)
    ; CHECK-NEXT: $r6 = COPY [[COPY6]](s32)
    ; CHECK-NEXT: $r7 = COPY [[COPY7]](s32)
    ; CHECK-NEXT: $r8 = COPY [[COPY8]](s32)
    ; CHECK-NEXT: $r9 = COPY [[COPY9]](s32)
    ; CHECK-NEXT: $r10 = COPY [[COPY10]](s32)
    ; CHECK-NEXT: $r11 = COPY [[COPY11]](s32)
    ; CHECK-NEXT: $r12 = COPY [[COPY12]](s32)
    ; CHECK-NEXT: $r13 = COPY [[COPY13]](s32)
    ; CHECK-NEXT: $r14 = COPY [[COPY14]](s32)
    ; CHECK-NEXT: $r15 = COPY [[COPY15]](s32)
    ; CHECK-NEXT: $sp = COPY [[COPY16]](p0)
    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(s32) = COPY $r2
    %3:_(s32) = COPY $r3
    %4:_(s32) = COPY $r4
    %5:_(s32) = COPY $r5
    %6:_(s32) = COPY $r6
    %7:_(s32) = COPY $r7
    %8:_(s32) = COPY $r8
    %9:_(s32) = COPY $r9
    %10:_(s32) = COPY $r10
    %11:_(s32) = COPY $r11
    %12:_(s32) = COPY $r12
    %13:_(s32) = COPY $r13
    %14:_(s32) = COPY $r14
    %15:_(s32) = COPY $r15
    %100:_(p0) = COPY $sp
    $r0 = COPY %0
    $r1 = COPY %1
    $r2 = COPY %2
    $r3 = COPY %3
    $r4 = COPY %4
    $r5 = COPY %5
    $r6 = COPY %6
    $r7 = COPY %7
    $r8 = COPY %8
    $r9 = COPY %9
    $r10 = COPY %10
    $r11 = COPY %11
    $r12 = COPY %12
    $r13 = COPY %13
    $r14 = COPY %14
    $r15 = COPY %15
    $sp = COPY %100
...

---
name: COPY_ptr
legalized: true

body: |
  bb.0:
    liveins: $p0, $p1, $p2, $p3, $p4, $p5, $p6, $p7
    ; CHECK-LABEL: name: COPY_ptr
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ptrregbank(p0) = COPY $p2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ptrregbank(p0) = COPY $p3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ptrregbank(p0) = COPY $p4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ptrregbank(p0) = COPY $p5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ptrregbank(p0) = COPY $p6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ptrregbank(p0) = COPY $p7
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: $p1 = COPY [[COPY1]](p0)
    ; CHECK-NEXT: $p2 = COPY [[COPY2]](p0)
    ; CHECK-NEXT: $p3 = COPY [[COPY3]](p0)
    ; CHECK-NEXT: $p4 = COPY [[COPY4]](p0)
    ; CHECK-NEXT: $p5 = COPY [[COPY5]](p0)
    ; CHECK-NEXT: $p6 = COPY [[COPY6]](p0)
    ; CHECK-NEXT: $p7 = COPY [[COPY7]](p0)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(p0) = COPY $p2
    %3:_(p0) = COPY $p3
    %4:_(p0) = COPY $p4
    %5:_(p0) = COPY $p5
    %6:_(p0) = COPY $p6
    %7:_(p0) = COPY $p7
    $p0 = COPY %0
    $p1 = COPY %1
    $p2 = COPY %2
    $p3 = COPY %3
    $p4 = COPY %4
    $p5 = COPY %5
    $p6 = COPY %6
    $p7 = COPY %7
...

---
name: COPY_mod
legalized: true

body: |
  bb.0:
    liveins: $m0, $m1, $m2, $m3, $m4, $m5, $m6, $m7
    ; CHECK-LABEL: name: COPY_mod
    ; CHECK: [[COPY:%[0-9]+]]:modregbank(p0) = COPY $m0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:modregbank(p0) = COPY $m1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:modregbank(p0) = COPY $m2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:modregbank(p0) = COPY $m3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:modregbank(p0) = COPY $m4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:modregbank(p0) = COPY $m5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:modregbank(p0) = COPY $m6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:modregbank(p0) = COPY $m7
    ; CHECK-NEXT: $m0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: $m1 = COPY [[COPY1]](p0)
    ; CHECK-NEXT: $m2 = COPY [[COPY2]](p0)
    ; CHECK-NEXT: $m3 = COPY [[COPY3]](p0)
    ; CHECK-NEXT: $m4 = COPY [[COPY4]](p0)
    ; CHECK-NEXT: $m5 = COPY [[COPY5]](p0)
    ; CHECK-NEXT: $m6 = COPY [[COPY6]](p0)
    ; CHECK-NEXT: $m7 = COPY [[COPY7]](p0)
    %0:_(p0) = COPY $m0
    %1:_(p0) = COPY $m1
    %2:_(p0) = COPY $m2
    %3:_(p0) = COPY $m3
    %4:_(p0) = COPY $m4
    %5:_(p0) = COPY $m5
    %6:_(p0) = COPY $m6
    %7:_(p0) = COPY $m7
    $m0 = COPY %0
    $m1 = COPY %1
    $m2 = COPY %2
    $m3 = COPY %3
    $m4 = COPY %4
    $m5 = COPY %5
    $m6 = COPY %6
    $m7 = COPY %7
...

---
name: COPY_cb
legalized: true

body: |
  bb.0:
    liveins: $cs0, $cs1, $cs2, $cs3, $cs4, $cs5, $cs6, $cs7
    ; CHECK-LABEL: name: COPY_cb
    ; CHECK: [[COPY:%[0-9]+]]:cbregbank(p0) = COPY $cs0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:cbregbank(p0) = COPY $cs1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:cbregbank(p0) = COPY $cs2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:cbregbank(p0) = COPY $cs3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:cbregbank(p0) = COPY $cs4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:cbregbank(p0) = COPY $cs5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:cbregbank(p0) = COPY $cs6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:cbregbank(p0) = COPY $cs7
    ; CHECK-NEXT: $cs0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: $cs1 = COPY [[COPY1]](p0)
    ; CHECK-NEXT: $cs2 = COPY [[COPY2]](p0)
    ; CHECK-NEXT: $cs3 = COPY [[COPY3]](p0)
    ; CHECK-NEXT: $cs4 = COPY [[COPY4]](p0)
    ; CHECK-NEXT: $cs5 = COPY [[COPY5]](p0)
    ; CHECK-NEXT: $cs6 = COPY [[COPY6]](p0)
    ; CHECK-NEXT: $cs7 = COPY [[COPY7]](p0)
    %0:_(p0) = COPY $cs0
    %1:_(p0) = COPY $cs1
    %2:_(p0) = COPY $cs2
    %3:_(p0) = COPY $cs3
    %4:_(p0) = COPY $cs4
    %5:_(p0) = COPY $cs5
    %6:_(p0) = COPY $cs6
    %7:_(p0) = COPY $cs7
    $cs0 = COPY %0
    $cs1 = COPY %1
    $cs2 = COPY %2
    $cs3 = COPY %3
    $cs4 = COPY %4
    $cs5 = COPY %5
    $cs6 = COPY %6
    $cs7 = COPY %7
...
