# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -march=aie2p %topdown-multi -run-pass=postmisched %s -o - | FileCheck %s

# Check 6 cycle latency for DONE at region end.
---
name:            done
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: done
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   SCHED_BARRIER
  ; CHECK-NEXT:   DONE
  ; CHECK-NEXT:   SCHED_BARRIER
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   JL_lng 0, implicit-def $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier csr_aie2p
  bb.0.entry:
    SCHED_BARRIER
    DONE
    SCHED_BARRIER
  bb.1:
    JL_lng 0, implicit-def $lr
    DelayedSchedBarrier csr_aie2p
...
