# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p %s --start-before=postmisched  -o - | FileCheck %s

# This should keep the event ordering related to the pipelined loop.

--- |
  define void @keep_event_order(ptr noalias nocapture readonly %a, ptr noalias nocapture writeonly %c, i32 noundef %factor, i32 noundef %N) {
  ; CHECK-LABEL: keep_event_order:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    event #0
  ; CHECK-NEXT:    event #1
  ; CHECK-NEXT:    event #0
  ; CHECK-NEXT:    event #1
  ; CHECK-NEXT:    event #0
  ; CHECK-NEXT:    vldb x2, [p0], #64
  ; CHECK-NEXT:    vldb x2, [p0], #64
  ; CHECK-NEXT:    vldb x2, [p0], #64
  ; CHECK-NEXT:    vldb x2, [p0], #64; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    mova r2, #-5; vldb x2, [p0], #64; movxm le, #.L_LEnd0
  ; CHECK-NEXT:    vldb x2, [p0], #64; lshl r1, r1, r2; vbcst.16 x0, r0
  ; CHECK-NEXT:    mova r0, #824; vldb x2, [p0], #64; nops ; nopx ; add.nc lc, r1, #-13; nopv
  ; CHECK-NEXT:    nopa ; vldb x2, [p0], #64; nops ; nopxm ; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    nopa ; vldb x2, [p0], #64; nops ; nopxm ; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    nopa ; vldb x2, [p0], #64; nops ; nopxm ; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    nopa ; vldb x2, [p0], #64; nops ; nopxm ; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    mova r3, #0; vldb x2, [p0], #64; nops ; nopx ; mov crsrsmode, #0; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    nopa ; vldb x2, [p0], #64; nops ; nopx ; mov s0, r3; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; vldb x2, [p0], #64; vst.srs.2x cml0, s0, srssign1, [p1], #64; nopxm ; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
  ; CHECK-NEXT:    nopa ; nopb ; vst.srs.2x cml0, s0, srssign1, [p1], #64; nopxm ; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64; nopx ; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64; vmul dm0, y1, y0,r0
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64
  ; CHECK-NEXT:    vst.srs.2x cml0, s0, srssign1, [p1], #64; ret lr
  ; CHECK-NEXT:    event #1 // Delay Slot 5
  ; CHECK-NEXT:    event #0 // Delay Slot 4
  ; CHECK-NEXT:    event #1 // Delay Slot 3
  ; CHECK-NEXT:    event #0 // Delay Slot 2
  ; CHECK-NEXT:    event #1 // Delay Slot 1
  entry:
    tail call void @llvm.aie2p.event(i32 0)
    tail call void @llvm.aie2p.event(i32 1)
    tail call void @llvm.aie2p.event(i32 0)
    tail call void @llvm.aie2p.event(i32 1)
    tail call void @llvm.aie2p.event(i32 0)
    %div9 = lshr i32 %N, 5
    %conv = trunc i32 %factor to i16
    %splat.splatinsert = insertelement <32 x i16> poison, i16 %conv, i64 0
    %splat.splat = shufflevector <32 x i16> %splat.splatinsert, <32 x i16> poison, <32 x i32> zeroinitializer
    %0 = bitcast <32 x i16> %splat.splat to <16 x i32>
    %shuffle = shufflevector <16 x i32> %0, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
    %1 = bitcast <32 x i32> %shuffle to <64 x i16>
    call void @llvm.set.loop.iterations.i32(i32 %div9)
    br label %for.body

  for.cond.cleanup:                                 ; preds = %for.body
    tail call void @llvm.aie2p.event(i32 1)
    tail call void @llvm.aie2p.event(i32 0)
    tail call void @llvm.aie2p.event(i32 1)
    tail call void @llvm.aie2p.event(i32 0)
    tail call void @llvm.aie2p.event(i32 1)
    ret void

  for.body:                                         ; preds = %entry, %for.body
    %pA1.07 = phi ptr [ %a, %entry ], [ %add.ptr, %for.body ]
    %pC1.06 = phi ptr [ %c, %entry ], [ %add.ptr1, %for.body ]
    %2 = load <16 x i32>, ptr %pA1.07, align 64
    %add.ptr = getelementptr inbounds i8, ptr %pA1.07, i20 64
    %shuffle1 = shufflevector <16 x i32> %2, <16 x i32> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
    %3 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mul.conf(<32 x i32> %shuffle1, <64 x i16> %1, i32 824)
    %shuffle2 = shufflevector <32 x i64> %3, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
    %4 = bitcast <16 x i64> %shuffle2 to <32 x i32>
    %5 = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> %4, i32 0, i32 1)
    store <32 x i16> %5, ptr %pC1.06, align 64
    %add.ptr1 = getelementptr inbounds i8, ptr %pC1.06, i20 64
    %6 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %6, label %for.body, label %for.cond.cleanup, !llvm.loop !12
  }

  ; Function Attrs: nounwind
  declare void @llvm.aie2p.event(i32)

  ; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
  declare <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mul.conf(<32 x i32>, <64 x i16>, i32)

  ; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
  declare void @llvm.assume(i1 noundef)

  ; Function Attrs: nofree nounwind memory(inaccessiblemem: read)
  declare <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32>, i32, i32)

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare void @llvm.set.loop.iterations.i32(i32)

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare i1 @llvm.loop.decrement.i32(i32)

  !12 = distinct !{!12, !13, !14}
  !13 = !{!"llvm.loop.mustprogress"}
  !14 = !{!"llvm.loop.itercount.range", i64 16}

...
---
name:            keep_event_order
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $r0, $r1

    EVENT_event0
    EVENT_event1
    EVENT_event0
    EVENT_event1
    renamable $r2 = MOV_RLC_imm11_pseudo -5
    renamable $r3 = MOV_RLC_imm11_pseudo 0
    renamable $r1 = LSHL killed renamable $r1, killed renamable $r2
    renamable $x0 = VBCST_16 killed renamable $r0
    renamable $r0 = MOV_RLC_imm11_pseudo 824
    EVENT_event0
    $lc = ADD_NC_mv_add_ri $r1, 0
    $ls = MOVXM %bb.1
    $le = MOVXM <mcsymbol .L_LEnd0>
    $s0 = MOV_alu_mv_mv_mv_scl killed $r3
    $crsrsmode = MOV_scalar_imm11_pseudo 0

  bb.1.for.body (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p0, $p1, $r0, $s0, $y0:0x0000000000000003

    renamable $x2, renamable $p0 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p0, 64 :: (load (<16 x s32>) from %ir.pA1.07)
    renamable $dm0 = VMUL_vmul_cm_core_Y_Y renamable $y1, renamable $y0, renamable $r0
    renamable $p1 = VST_SRS_2x_dm_sts_srs_cm_pstm_nrm_imm_srsSign1 killed renamable $cml0, renamable $s0, killed renamable $p1, 64, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into %ir.pC1.06)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2.for.cond.cleanup:
    EVENT_event1
    EVENT_event0
    EVENT_event1
    EVENT_event0
    EVENT_event1
    RET implicit $lr
    DelayedSchedBarrier

...
