# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Test that the FuncArgCopyEdges mutator does not create cycles when
# multiple func-arg COPYs define virtual registers in the same small
# register class (e.g. ePS = {p0, p1}). Without the fix, the mutator
# would add edges in both directions between the two COPYs, creating
# a cycle that makes the scheduler hang.
#
# RUN: llc -O2 -mtriple=aie2p -run-pass=machine-scheduler %s -o - | FileCheck %s

---
name:            test_no_cycle_between_func_arg_copies
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
    bb.0.entry:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: test_no_cycle_between_func_arg_copies
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY [[COPY]]
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_idx_imm [[COPY1]], 0 :: (load (s20), align 4)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eps = COPY $p1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ep = COPY [[COPY2]]
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm1:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_idx_imm [[COPY3]], 0 :: (load (s20), align 4)
    ; CHECK-NEXT: dead [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 42
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LDA_dms_lda_idx_imm]], implicit [[LDA_dms_lda_idx_imm1]]
    %0:eps = COPY $p0
    %1:eps = COPY $p1
    %2:ep = COPY %0
    %3:ep = COPY %1
    %4:er = MOV_RLC_imm11_pseudo 42
    %5:ep_as_32bit = LDA_dms_lda_idx_imm %2, 0 :: (load (s20))
    %6:ep_as_32bit = LDA_dms_lda_idx_imm %3, 0 :: (load (s20))
    PseudoRET implicit $lr, implicit %5, implicit %6
...
