# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2p -run-pass=postmisched %s -issue-limit=6 -o - | FileCheck %s

# Tests the MOV slot bypass (MOV_Bypass)
# This is particular looks at bypasses behavior for the wl and wh register
# files. Most instructions involved in MOV_Bypass use X registers, but some
# like VCONV, VEXP2 and VTANH actually use W registers. For those, we have to
# make sure that the bypass isn't used for WH registers, as it isn't supported in HW.

---
name:            bypass_wl_from_x_with_vmov
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wl_from_x_with_vmov
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: $wh0 = VMOV_alu_mv_mv_w killed $wl0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $wh0 = VMOV_alu_mv_mv_w $wl0
...

---
name:            bypass_wh_from_x_with_vmov
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wh_from_x_with_vmov
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: $wl0 = VMOV_alu_mv_mv_w killed $wh0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $wl0 = VMOV_alu_mv_mv_w $wh0
...

---
name:            bypass_wl_from_x_with_vconv
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wl_from_x_with_vconv
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: $bmll0 = VCONV_fp32_bf16_mv_ups_wbf killed $wl0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $bmll0 = VCONV_fp32_bf16_mv_ups_wbf $wl0
...

---
name:            bypass_wh_from_x_with_vconv
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wh_from_x_with_vconv
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmll0 = VCONV_fp32_bf16_mv_ups_wbf killed $wh0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $bmll0 = VCONV_fp32_bf16_mv_ups_wbf $wh0
...

---
name:            bypass_wl_to_x
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wl_to_x
    ; CHECK: $wl0 = VMOV_alu_mv_mv_w killed $wl2
    ; CHECK-NEXT: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: NOP
    $wl0 = VMOV_alu_mv_mv_w $wl2
    $x0 = VBAND $x0, $x4
...

---
name:            bypass_wh_to_x
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wh_to_x
    ; CHECK: $wh0 = VMOV_alu_mv_mv_w killed $wh2
    ; CHECK-NEXT: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: NOP
    $wh0 = VMOV_alu_mv_mv_w $wh2
    $x0 = VBAND $x0, $x4
...

---
name:            bypass_wl
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wl
    ; CHECK: $wl1 = VMOV_alu_mv_mv_w killed $wh0
    ; CHECK-NEXT: $wl0 = VMOV_alu_mv_mv_w killed $wl1
    ; CHECK-NEXT: NOP
    $wl1 = VMOV_alu_mv_mv_w $wh0
    $wl0 = VMOV_alu_mv_mv_w $wl1
...

---
name:            bypass_wh
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wh
    ; CHECK: $wh1 = VMOV_alu_mv_mv_w killed $wh0
    ; CHECK-NEXT: $wl0 = VMOV_alu_mv_mv_w killed $wh1
    ; CHECK-NEXT: NOP
    $wh1 = VMOV_alu_mv_mv_w $wh0
    $wl0 = VMOV_alu_mv_mv_w $wh1
...

---
name:            bypass_x
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_x
    ; CHECK: $x1 = VMOV_alu_mv_mv_x killed $x2
    ; CHECK-NEXT: $x0 = VMOV_alu_mv_mv_x killed $x1
    ; CHECK-NEXT: NOP
    $x1 = VMOV_alu_mv_mv_x $x2
    $x0 = VMOV_alu_mv_mv_x $x1
...

---
name:            no_bypass_vmov_x_cm
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_vmov_x_cm
    ; CHECK: $bmll1 = VMOV_alu_mv_mv_x killed $bmll0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmll2 = VMOV_alu_mv_mv_x killed $bmll1
    ; CHECK-NEXT: NOP
    $bmll1 = VMOV_alu_mv_mv_x $bmll0
    $bmll2 = VMOV_alu_mv_mv_x $bmll1
...
---
name:            bypass_wl_from_x_with_vtanh
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wl_from_x_with_vtanh
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: $wl0 = VTANH killed $bmll0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $wl0 = VTANH $bmll0
...

---
name:            bypass_wh_from_x_with_vtanh
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wh_from_x_with_vtanh
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: $wh0 = VTANH killed $bmll0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $wh0 = VTANH $bmll0
...
---
name:            bypass_wl_from_x_with_vexp2
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wl_from_x_with_vexp2
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: $wl0 = VEXP2 killed $bmll0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $wl0 = VEXP2 $bmll0
...

---
name:            bypass_wh_from_x_with_vexp2
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_wh_from_x_with_vexp2
    ; CHECK: $x0 = VBAND killed $x0, killed $x4
    ; CHECK-NEXT: $wh0 = VEXP2 killed $bmll0
    ; CHECK-NEXT: NOP
    $x0 = VBAND $x0, $x4
    $wh0 = VEXP2 $bmll0
...

---
name:            bypass_x_with_vmov
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_x_with_vmov
    ; CHECK: $x3 = VMOV_alu_mv_mv_x killed $x2
    ; CHECK-NEXT: $cml1 = VCONV_fp32_bf16_mv_ups_xbf killed $x3
    ; CHECK-NEXT: NOP
    $x3 = VMOV_alu_mv_mv_x $x2
    $cml1 = VCONV_fp32_bf16_mv_ups_xbf $x3
...
