; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; unit test for the loop iteration metadata conversion to assumptions
;
; NOTE: Example File to reverse inlined GEP
;
; RUN: opt -S -passes='outline-gep' -verify-each -o -  < %s | FileCheck %s

%struct.gemm_bfp16_params = type { i32, i32, i32, i32, i32, i32, [8 x i8], i32, [28 x i8] }
@param = external dso_local global %struct.gemm_bfp16_params, align 32


define hidden fastcc void @_ZL23setup_gemm_bfp16_paramsR17gemm_bfp16_paramsPKv(ptr nocapture readonly %lp) {
; CHECK-LABEL: @_ZL23setup_gemm_bfp16_paramsR17gemm_bfp16_paramsPKv(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LP:%.*]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr @param, align 32
; CHECK-NEXT:    [[REVERSE_ARRAYIDX:%.*]] = getelementptr inbounds [[STRUCT_GEMM_BFP16_PARAMS:%.*]], ptr @param, i20 0, i32 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[REVERSE_ARRAYIDX]], align 4
; CHECK-NEXT:    [[REVERSE_ARRAYIDX1:%.*]] = getelementptr inbounds [[STRUCT_GEMM_BFP16_PARAMS]], ptr @param, i20 0, i32 1
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[REVERSE_ARRAYIDX1]], align 4
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[LP]], i20 4
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX1]], align 4
; CHECK-NEXT:    [[REVERSE_ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr getelementptr inbounds ([[STRUCT_GEMM_BFP16_PARAMS]], ptr @param, i20 0, i32 7), i20 13
; CHECK-NEXT:    tail call void @llvm.memset.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) [[REVERSE_ARRAYIDX2]], i8 0, i32 7, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i32, ptr %lp, align 4
  store i32 %0, ptr @param, align 32
  %1 = load i32, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 2), align 4
  store i32 %1, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 1), align 4
  %arrayidx1 = getelementptr inbounds i8, ptr %lp, i20 4
  %2 = load i32, ptr %arrayidx1, align 4
  tail call void @llvm.memset.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) getelementptr inbounds (i8, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 7), i20 13), i8 0, i32 7, i1 false)
  ret void
}
