; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -mtriple=aie2ps -O2 %s -o - | FileCheck %s

; The outer unpad loop is a multi-block loop around an inner hardware loop.
; It currently reaches the backend as a software decrement and branch.

define void @buffer_unpad_outer_loop(ptr noalias %ifm, ptr noalias %ofm, ptr %layer_params) {
; CHECK-LABEL: buffer_unpad_outer_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda r0, [p2, #8]; nopb ; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    jz r0, #.LBB0_6
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %outer.header.preheader
; CHECK-NEXT:    lda r4, [p2, #4]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r2, [p2, #0]
; CHECK-NEXT:    lda p0, [p0, #0]
; CHECK-NEXT:    lda p1, [p1, #0]; movx r16, #0; mov r6, #0
; CHECK-NEXT:  .LBB0_2: // %outer.header
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_4 Depth 2
; CHECK-NEXT:    nopa ; nopb ; jz r4, #.LBB0_5
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.3: // %inner.preheader
; CHECK-NEXT:    // in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    add.nc lc, r4, #0
; CHECK-NEXT:    movxm ls, #.LBB0_4
; CHECK-NEXT:    mova r18, #0; nopb ; nops ; movxm le, #.L_LEnd0; nopv
; CHECK-NEXT:  .LBB0_4: // %inner
; CHECK-NEXT:    // Parent Loop BB0_2 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; nopb ; nops ; add r20, r6, r18; nopm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; add r22, r16, r18; mov dj0, r20; nopv
; CHECK-NEXT:    lda.s8 r20, [p0, dj0]; nopb ; nops ; nopx ; mov dj0, r22; nopv
; CHECK-NEXT:    st.s8 r20, [p1, dj0]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nopxm
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; nops ; add r18, r18, #1; nopm ; nopv
; CHECK-NEXT:  .LBB0_5: // %outer.latch
; CHECK-NEXT:    // in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    nopa ; nopb ; add r0, r0, #-1; nopm
; CHECK-NEXT:    jnz r0, #.LBB0_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    add r16, r16, r4 // Delay Slot 2
; CHECK-NEXT:    add r6, r6, r2 // Delay Slot 1
; CHECK-NEXT:  .LBB0_6: // %exit
; CHECK-NEXT:    nopa ; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %ifm_stride = load i32, ptr %layer_params, align 4
  %ofm_extent.ptr = getelementptr inbounds nuw i8, ptr %layer_params, i20 4
  %ofm_extent = load i32, ptr %ofm_extent.ptr, align 4
  %outer_count.ptr = getelementptr inbounds nuw i8, ptr %layer_params, i20 8
  %outer_count = load i32, ptr %outer_count.ptr, align 4
  %ifm.base = load ptr, ptr %ifm, align 4
  %ofm.base = load ptr, ptr %ofm, align 4
  %outer.empty = icmp eq i32 %outer_count, 0
  br i1 %outer.empty, label %exit, label %outer.header

outer.header:
  %outer.iv = phi i32 [ %outer_count, %entry ], [ %outer.iv.next, %outer.latch ]
  %ifm.offset = phi i32 [ 0, %entry ], [ %ifm.offset.next, %outer.latch ]
  %ofm.offset = phi i32 [ 0, %entry ], [ %ofm.offset.next, %outer.latch ]
  %inner.empty = icmp eq i32 %ofm_extent, 0
  br i1 %inner.empty, label %outer.latch, label %inner.preheader

inner.preheader:
  call void @llvm.set.loop.iterations.i32(i32 %ofm_extent)
  br label %inner

inner:
  %inner.iv = phi i32 [ 0, %inner.preheader ], [ %inner.iv.next, %inner ]
  %ifm.index = add i32 %ifm.offset, %inner.iv
  %ofm.index = add i32 %ofm.offset, %inner.iv
  %ifm.as = addrspacecast ptr %ifm.base to ptr addrspace(5)
  %ofm.as = addrspacecast ptr %ofm.base to ptr addrspace(6)
  %ifm.index.i20 = trunc i32 %ifm.index to i20
  %ifm.ptr = getelementptr inbounds nuw i8, ptr addrspace(5) %ifm.as,
                                      i20 %ifm.index.i20
  %value = load i8, ptr addrspace(5) %ifm.ptr, align 1
  %ofm.index.i20 = trunc i32 %ofm.index to i20
  %ofm.ptr = getelementptr inbounds nuw i8, ptr addrspace(6) %ofm.as,
                                      i20 %ofm.index.i20
  store i8 %value, ptr addrspace(6) %ofm.ptr, align 1
  %inner.cont = call i1 @llvm.loop.decrement.i32(i32 1)
  %inner.iv.next = add i32 %inner.iv, 1
  br i1 %inner.cont, label %inner, label %outer.latch, !llvm.loop !1

outer.latch:
  %ofm.offset.next = add i32 %ofm.offset, %ofm_extent
  %ifm.offset.next = add i32 %ifm.offset, %ifm_stride
  %outer.iv.next = add i32 %outer.iv, -1
  %outer.done = icmp eq i32 %outer.iv.next, 0
  br i1 %outer.done, label %exit, label %outer.header, !llvm.loop !0

exit:
  ret void
}

declare void @llvm.set.loop.iterations.i32(i32)
declare i1 @llvm.loop.decrement.i32(i32)

!0 = distinct !{!0, !2}
!1 = distinct !{!1, !2}
!2 = !{!"llvm.loop.mustprogress"}
