; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2ps %s -o - | FileCheck %s
; RUN: llc -mtriple=aie2ps -aie-outer-loop-pipelining-split-prologue=false %s -o - | FileCheck --check-prefix=NO-PROLOGUE-SPLIT %s
; RUN: llc -mtriple=aie2ps -aie-outer-loop-hw-loop=false %s -o - | FileCheck --check-prefix=NO-JNZD %s

; Test outer-loop pipeliner in a end-to-end fashion

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { ptr, i20 } @llvm.aie2ps.add.2d(ptr, i20, i20, i20, i20) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32>, <16 x i32>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64>, <32 x i64>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16>, i32, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16>, <32 x i16>, <64 x i32>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8>, <64 x i8>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32>, i32, i32) #1

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare void @llvm.set.loop.iterations.i32(i32) #2

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare i1 @llvm.loop.decrement.i32(i32) #2

; Function Attrs: mustprogress noinline
define dso_local void @gemm(i32 %0, ptr addrspace(5) %1, ptr addrspace(5) %2, ptr %p_psum, ptr %p_c, ptr %p_bias, i20 %3, i20 %4, i20 %5, i20 %6, i20 %7, i20 %idx.ext.i, i20 %8, i20 %9, i20 %10, i20 %11, i20 %12, i32 %13, i32 %14, i32 %15, i32 %16, i32 %or23.i.i.i.i, <64 x i8> %17, i32 %18, i32 %19, i32 %20, i32 %21, i32 %22, i32 %or22.i.i.i.i, i32 %conv166, i32 %conv.i.i.i.i, i20 %idx.ext.i478, i20 %23, i20 %24, i20 %25, i20 %26, i20 %27, i20 %28) #3 {
; CHECK-LABEL: gemm:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    paddxm [sp], #64; nopxm
; CHECK-NEXT:    st p6, [sp, #-64] // 4-byte Folded Spill
; CHECK-NEXT:    mova m0, #-68; mov p6, sp
; CHECK-NEXT:    padda [p6], m0
; CHECK-NEXT:    lda dj0, [p6], #-4
; CHECK-NEXT:    lda dj4, [p6], #-4
; CHECK-NEXT:    lda dn0, [p6], #-4
; CHECK-NEXT:    lda dn4, [p6], #-4
; CHECK-NEXT:    lda m4, [p6], #-4
; CHECK-NEXT:    lda m1, [p6], #-4
; CHECK-NEXT:    lda dj1, [p6], #-4
; CHECK-NEXT:    lda dj5, [p6], #-4
; CHECK-NEXT:    lda dn1, [p6], #-4
; CHECK-NEXT:    lda dn5, [p6], #-4
; CHECK-NEXT:    lda r16, [p6], #-4
; CHECK-NEXT:    lda r18, [p6], #-4
; CHECK-NEXT:    lda r20, [p6], #-4
; CHECK-NEXT:    lda r8, [p6], #-4
; CHECK-NEXT:    lda r17, [p6], #-4
; CHECK-NEXT:    lda r19, [p6], #-4
; CHECK-NEXT:    lda m5, [p6], #-4; vldb.128 wl4, [p4, #0]; add r0, r0, #-1; mov dc2, #0
; CHECK-NEXT:    mova dc0, #0; vldb.128 wl6, [p4, #16]; movx r22, #0; mov r21, r8
; CHECK-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p2], #64; vldb x8, [p1], m4; movxm ls, #.LBB0_2
; CHECK-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p2], #64; movxm le, #.L_LEnd1
; CHECK-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p2], #64; or r23, r10, r10; vbcst.32 x2, r22
; CHECK-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p2], #64; movs dc1, dc0; or r10, r5, r5; mov s0, r22
; CHECK-NEXT:    lda m2, [p6], #-4; movs dc5, dc0; movx r22, #15; addm.nc r5, r0, #-1
; CHECK-NEXT:    lda dj2, [p6], #-4; vldb.3d x10, [p1], d1; vsel.32 x4, x2, x4, r22
; CHECK-NEXT:    lda dn2, [p6], #-4; movx crupsmode, #0; vsel.32 x2, x2, x6, r22
; CHECK-NEXT:    lda m3, [p6], #-4; vshuffle x6, x8, x0, r1
; CHECK-NEXT:    lda dj3, [p6, #0]; vshuffle x1, x6, x0, r2
; CHECK-NEXT:    lda dn3, [p6, #-4]; movxm p6, #.LBB0_1
; CHECK-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p2], #64; mov s1, r17
; CHECK-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p2], #64; vldb x6, [p0], #64; or r24, r12, r12; mov srssign0, r19; movs dc4, dc0
; CHECK-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p2], #64; movs m0, p5; movx r12, #776; vshuffle x8, x10, x0, r3
; CHECK-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p2], #64; vldb.3d x8, [p0], d0; movx crsrsmode, #0; vshuffle x10, x8, x0, r4; movs dc3, dc2
; CHECK-NEXT:  .LBB0_1: // %for.body
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_2 Depth 2
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; nopx ; movs m0, p5
; CHECK-NEXT:    vlda.3d x7, [p1], d1
; CHECK-NEXT:    vldb x5, [p0], #64; vmul dm4, x0, x4, r12
; CHECK-NEXT:    vlda.3d x3, [p0], d0
; CHECK-NEXT:    movs m0, p5; vldb x9, [p1], m4; vaddmac dm3, dm3, dm4, x6, x1, r10
; CHECK-NEXT:    vlda.3d x7, [p1], d1; vmul dm4, x0, x2, r12
; CHECK-NEXT:    vldb x5, [p0], #64; vaddmac dm2, dm2, dm4, x8, x1, r10
; CHECK-NEXT:    vlda.3d x3, [p0], d0; vshuffle x1, x9, x0, r7; vaddmac dm1, dm1, dm4, x6, x10, r10
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; add.nc lc, r6, #-3; vshuffle x10, x1, x0, r16; vaddmac dm0, dm0, dm4, x8, x10, r10
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; nopv
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  .LBB0_2: // %for.body100
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; nopx ; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:  .L_LEnd1:
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  // %bb.3: // %for.cond.cleanup99
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    nopa ; paddb.2d [p4], d3; movs m0, p5; nopx ; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vldb.128 wl1, [p4, #16]; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vldb.128 wl10, [p4, #0]; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:    vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p2], #64; vldb x3, [p1], m4; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p2], #64; vldb.3d x5, [p1], d1; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p2], #64; vldb x6, [p0], #64; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p2], #64; vldb.3d x8, [p0], d0; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p2], #64; vsel.32 x2, x2, x1, r22; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p2], #64; vsel.32 x4, x4, x10, r22; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p2], #64
; CHECK-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p2], #64; jnzd r5, r5, p6; vshuffle x10, x3, x0, r1
; CHECK-NEXT:    vst.srs.4x dm3, s1, srssign0, [p3], #64; vshuffle x1, x10, x0, r2 // Delay Slot 5
; CHECK-NEXT:    vst.srs.4x dm2, s1, srssign0, [p3], m5; vshuffle x10, x5, x0, r3 // Delay Slot 4
; CHECK-NEXT:    vst.srs.4x dm1, s1, srssign0, [p3], #64; vshuffle x10, x10, x0, r4 // Delay Slot 3
; CHECK-NEXT:    vst.2d.srs.4x dm0, s1, srssign0, [p3], d2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.4: // %cooldown.entry
; CHECK-NEXT:    vldb x3, [p1], m4
; CHECK-NEXT:    vlda.3d x1, [p1], d1; vmul dm4, x0, x4, r12
; CHECK-NEXT:    vldb x10, [p0], #64; mov m0, p5
; CHECK-NEXT:    vlda.3d x8, [p0], d0; vaddmac dm3, dm3, dm4, x6, x1, r10
; CHECK-NEXT:    vldb x3, [p1], m4; vmul dm4, x0, x2, r12
; CHECK-NEXT:    vlda.3d x1, [p1], d1; movxm ls, #.LBB0_5; vaddmac dm2, dm2, dm4, x8, x1, r10
; CHECK-NEXT:    vldb x10, [p0], #64; movxm le, #.L_LEnd0; vaddmac dm1, dm1, dm4, x6, x10, r10
; CHECK-NEXT:    vlda.3d x8, [p0], d0; vshuffle x6, x3, x0, r7; vaddmac dm0, dm0, dm4, x8, x10, r10
; CHECK-NEXT:    nopa ; vldb x3, [p1], m4; nops ; add.nc lc, r6, #-3; vshuffle x4, x6, x0, r16; nopv
; CHECK-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; nopv
; CHECK-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; movx srssign0, #0; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:  .LBB0_5: // %for.body100.cd
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; vldb x3, [p1], m4; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; CHECK-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; CHECK-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; nopx ; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:  // %bb.6: // %cooldown.exit
; CHECK-NEXT:    lda p6, [sp, #-64]; nopb ; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8 // 4-byte Folded Reload
; CHECK-NEXT:    paddxm [sp], #-64; nopb ; nops ; movx crsrsmode, #0; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; CHECK-NEXT:    or r12, r24, r24; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:    or r10, r23, r23; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:    vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; CHECK-NEXT:    vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; CHECK-NEXT:    vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:    mov s0, r17; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:    mov srssign0, r19; vmac dm1, dm1, x10, x0, r8
; CHECK-NEXT:    vmac dm0, dm0, x8, x0, r8
; CHECK-NEXT:    mov r8, r21
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.srs.4x dm3, s0, srssign0, [p3], #64
; CHECK-NEXT:    vst.srs.4x dm2, s0, srssign0, [p3], m5; ret lr
; CHECK-NEXT:    vst.srs.4x dm1, s0, srssign0, [p3, #0] // Delay Slot 5
; CHECK-NEXT:    vst.srs.4x dm0, s0, srssign0, [p3, #64]; movx srssign0, #0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
;
; NO-PROLOGUE-SPLIT-LABEL: gemm:
; NO-PROLOGUE-SPLIT:       // %bb.0: // %newFuncRoot
; NO-PROLOGUE-SPLIT-NEXT:    paddxm [sp], #64; nopxm
; NO-PROLOGUE-SPLIT-NEXT:    st p6, [sp, #-64] // 4-byte Folded Spill
; NO-PROLOGUE-SPLIT-NEXT:    mova m0, #-68; mov p6, sp
; NO-PROLOGUE-SPLIT-NEXT:    padda [p6], m0
; NO-PROLOGUE-SPLIT-NEXT:    lda dj0, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda dj4, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda dn0, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda dn4, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda m4, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda m1, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda dj1, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda dj5, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda dn1, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda dn5, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda r16, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda r18, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda r20, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda r8, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda r17, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda r19, [p6], #-4
; NO-PROLOGUE-SPLIT-NEXT:    lda m5, [p6], #-4; mov r21, r8
; NO-PROLOGUE-SPLIT-NEXT:    lda m3, [p6], #-4; movx r22, #0; mov dc0, #0
; NO-PROLOGUE-SPLIT-NEXT:    lda dj3, [p6], #-4; movxm ls, #.LBB0_2
; NO-PROLOGUE-SPLIT-NEXT:    lda dn3, [p6], #-4; movxm le, #.L_LEnd1
; NO-PROLOGUE-SPLIT-NEXT:    lda m7, [p6], #-4; vbcst.32 x4, r22
; NO-PROLOGUE-SPLIT-NEXT:    lda dj7, [p6, #0]; vldb.128 wl2, [p4, #0]; movs m2, p5; mov s0, r22
; NO-PROLOGUE-SPLIT-NEXT:    lda dn7, [p6, #-4]; vldb x10, [p1], m4; mov p6, p2
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p6], #64; vldb.128 wl8, [p4, #16]; or r24, r12, r12; mov dc1, dc0; movs dc2, dc0
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p6], #64; vldb x6, [p0], #64; add r0, r0, #-1; mov dn2, dn0; movs dc5, dc0
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p6], #64; vldb.3d x3, [p1], d1; or r23, r10, r10; mov dj2, dj0; movs dc6, dc0
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p6], #64; movs dj6, dj4; or r10, r5, r5; mov dn6, dn4
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p6], #64; vldb.3d x1, [p0], d2; movx r22, #15; addm.nc r5, r0, #-1
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p6], #64; movx r12, #776; vsel.32 x2, x4, x2, r22
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p6, #64]; movx crupsmode, #0; vshuffle x10, x10, x0, r1
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p6, #0]; vshuffle x10, x10, x0, r2; vmul dm4, x0, x2, r12
; NO-PROLOGUE-SPLIT-NEXT:    st p7, [sp, #-60]; vsel.32 x4, x4, x8, r22 // 4-byte Folded Spill
; NO-PROLOGUE-SPLIT-NEXT:    mova dc3, #0; movs p7, p2; vshuffle x8, x3, x0, r3; vaddmac dm3, dm3, dm4, x6, x10, r10
; NO-PROLOGUE-SPLIT-NEXT:    movs dc7, dc3; vshuffle x8, x8, x0, r4; vmul dm4, x0, x4, r12
; NO-PROLOGUE-SPLIT-NEXT:    mova dj2, #512; movs dc0, dc2; mov s1, r17; vaddmac dm2, dm2, dm4, x1, x10, r10
; NO-PROLOGUE-SPLIT-NEXT:    mova m6, #576; movs dc4, dc6; mov srssign0, r19; vaddmac dm1, dm1, dm4, x6, x8, r10
; NO-PROLOGUE-SPLIT-NEXT:    movs m2, dj2; movx crsrsmode, #0; mov p6, p2; vaddmac dm0, dm0, dm4, x1, x8, r10
; NO-PROLOGUE-SPLIT-NEXT:  .LBB0_1: // %for.body
; NO-PROLOGUE-SPLIT-NEXT:    // =>This Loop Header: Depth=1
; NO-PROLOGUE-SPLIT-NEXT:    // Child Loop BB0_2 Depth 2
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; nopxm ; nopv
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x7, [p1], d1
; NO-PROLOGUE-SPLIT-NEXT:    vldb x5, [p0], #64
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x3, [p0], d0
; NO-PROLOGUE-SPLIT-NEXT:    vldb x9, [p1], m4; movs m0, p5
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x7, [p1], d1
; NO-PROLOGUE-SPLIT-NEXT:    vldb x5, [p0], #64
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x3, [p0], d0; vshuffle x1, x9, x0, r7
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; add.nc lc, r6, #-3; vshuffle x10, x1, x0, r16; nopv
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; nopv
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x3, [p0], d0; paddb [p6], m2; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:  .LBB0_2: // %for.body100
; NO-PROLOGUE-SPLIT-NEXT:    // Parent Loop BB0_1 Depth=1
; NO-PROLOGUE-SPLIT-NEXT:    // => This Inner Loop Header: Depth=2
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; nopx ; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:  .L_LEnd1:
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:  // %bb.3: // %for.cond.cleanup99
; NO-PROLOGUE-SPLIT-NEXT:    // in Loop: Header=BB0_1 Depth=1
; NO-PROLOGUE-SPLIT-NEXT:    vlda x1, [p1], m4; paddb.2d [p4], d7; movs p2, p7; nopx ; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    padda [p2], m6; vldb x8, [p0], #64; movs m0, p5; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb.3d x10, [p0], d0; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb.3d x5, [p1], d1; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p2], #64; vldb.128 wl6, [p4, #0]; nopx ; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p7, dj2]; vldb.128 wl3, [p4, #16]; movs p7, p6; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p2], #64; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p2], #64; vmac dm2, dm2, x3, x10, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p2], #64; vmac dm1, dm1, x5, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p2], #64; vmac dm0, dm0, x3, x6, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p2, #64]
; NO-PROLOGUE-SPLIT-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p2, #0]; vsel.32 x2, x2, x6, r22
; NO-PROLOGUE-SPLIT-NEXT:    vst.srs.4x dm3, s1, srssign0, [p3], #64; vshuffle x6, x1, x0, r1
; NO-PROLOGUE-SPLIT-NEXT:    vst.srs.4x dm2, s1, srssign0, [p3], m5; vshuffle x6, x6, x0, r2; vmul dm4, x0, x2, r12
; NO-PROLOGUE-SPLIT-NEXT:    vst.srs.4x dm1, s1, srssign0, [p3], #64; vsel.32 x4, x4, x3, r22
; NO-PROLOGUE-SPLIT-NEXT:    vst.2d.srs.4x dm0, s1, srssign0, [p3], d3; vshuffle x1, x5, x0, r3; vaddmac dm3, dm3, dm4, x8, x6, r10
; NO-PROLOGUE-SPLIT-NEXT:    movxm p2, #.LBB0_1; vaddmac dm2, dm2, dm4, x10, x6, r10
; NO-PROLOGUE-SPLIT-NEXT:    jnzd r5, r5, p2; vshuffle x6, x1, x0, r4; vmul dm4, x0, x4, r12
; NO-PROLOGUE-SPLIT-NEXT:    nop // Delay Slot 5
; NO-PROLOGUE-SPLIT-NEXT:    vaddmac dm1, dm1, dm4, x8, x6, r10 // Delay Slot 4
; NO-PROLOGUE-SPLIT-NEXT:    vaddmac dm0, dm0, dm4, x10, x6, r10 // Delay Slot 3
; NO-PROLOGUE-SPLIT-NEXT:    nop // Delay Slot 2
; NO-PROLOGUE-SPLIT-NEXT:    nop // Delay Slot 1
; NO-PROLOGUE-SPLIT-NEXT:  // %bb.4: // %cooldown.entry
; NO-PROLOGUE-SPLIT-NEXT:    vldb x3, [p1], m4
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x1, [p1], d1
; NO-PROLOGUE-SPLIT-NEXT:    vldb x10, [p0], #64; mov m0, p5
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x8, [p0], d0
; NO-PROLOGUE-SPLIT-NEXT:    vldb x3, [p1], m4
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x1, [p1], d1; movxm ls, #.LBB0_5
; NO-PROLOGUE-SPLIT-NEXT:    vldb x10, [p0], #64; movxm le, #.L_LEnd0
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x8, [p0], d0; vshuffle x6, x3, x0, r7
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x3, [p1], m4; nops ; add.nc lc, r6, #-3; vshuffle x4, x6, x0, r16; nopv
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; nopv
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; movx srssign0, #0; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:  .LBB0_5: // %for.body100.cd
; NO-PROLOGUE-SPLIT-NEXT:    // =>This Inner Loop Header: Depth=1
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x3, [p1], m4; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; NO-PROLOGUE-SPLIT-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:  .L_LEnd0:
; NO-PROLOGUE-SPLIT-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; nopx ; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:  // %bb.6: // %cooldown.exit
; NO-PROLOGUE-SPLIT-NEXT:    lda p7, [sp, #-60]; nopb ; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8 // 4-byte Folded Reload
; NO-PROLOGUE-SPLIT-NEXT:    lda p6, [sp, #-64]; nopb ; movx crsrsmode, #0; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8 // 4-byte Folded Reload
; NO-PROLOGUE-SPLIT-NEXT:    paddxm [sp], #-64; or r12, r24, r24; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:    or r10, r23, r23; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:    vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; NO-PROLOGUE-SPLIT-NEXT:    vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; NO-PROLOGUE-SPLIT-NEXT:    vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:    mov s0, r17; vmac dm2, dm2, x8, x4, r8
; NO-PROLOGUE-SPLIT-NEXT:    mov srssign0, r19; vmac dm1, dm1, x10, x0, r8
; NO-PROLOGUE-SPLIT-NEXT:    vmac dm0, dm0, x8, x0, r8
; NO-PROLOGUE-SPLIT-NEXT:    mov r8, r21
; NO-PROLOGUE-SPLIT-NEXT:    nop
; NO-PROLOGUE-SPLIT-NEXT:    vst.srs.4x dm3, s0, srssign0, [p3], #64
; NO-PROLOGUE-SPLIT-NEXT:    vst.srs.4x dm2, s0, srssign0, [p3], m5; ret lr
; NO-PROLOGUE-SPLIT-NEXT:    vst.srs.4x dm1, s0, srssign0, [p3, #0] // Delay Slot 5
; NO-PROLOGUE-SPLIT-NEXT:    vst.srs.4x dm0, s0, srssign0, [p3, #64]; movx srssign0, #0 // Delay Slot 4
; NO-PROLOGUE-SPLIT-NEXT:    nop // Delay Slot 3
; NO-PROLOGUE-SPLIT-NEXT:    nop // Delay Slot 2
; NO-PROLOGUE-SPLIT-NEXT:    nop // Delay Slot 1
;
; NO-JNZD-LABEL: gemm:
; NO-JNZD:       // %bb.0: // %newFuncRoot
; NO-JNZD-NEXT:    paddxm [sp], #64; nopb ; nops ; nopxm ; nopv
; NO-JNZD-NEXT:    st p6, [sp, #-64]; nopx // 4-byte Folded Spill
; NO-JNZD-NEXT:    mova m0, #-68; mov p6, sp
; NO-JNZD-NEXT:    padda [p6], m0
; NO-JNZD-NEXT:    lda dj0, [p6], #-4
; NO-JNZD-NEXT:    lda dj4, [p6], #-4
; NO-JNZD-NEXT:    lda dn0, [p6], #-4
; NO-JNZD-NEXT:    lda dn4, [p6], #-4
; NO-JNZD-NEXT:    lda m4, [p6], #-4
; NO-JNZD-NEXT:    lda m1, [p6], #-4
; NO-JNZD-NEXT:    lda dj1, [p6], #-4
; NO-JNZD-NEXT:    lda dj5, [p6], #-4
; NO-JNZD-NEXT:    lda dn1, [p6], #-4
; NO-JNZD-NEXT:    lda dn5, [p6], #-4
; NO-JNZD-NEXT:    lda r16, [p6], #-4
; NO-JNZD-NEXT:    lda r18, [p6], #-4
; NO-JNZD-NEXT:    lda r20, [p6], #-4
; NO-JNZD-NEXT:    lda r8, [p6], #-4
; NO-JNZD-NEXT:    lda r17, [p6], #-4
; NO-JNZD-NEXT:    lda r19, [p6], #-4
; NO-JNZD-NEXT:    lda m5, [p6], #-4; mov dc2, #0
; NO-JNZD-NEXT:    mova dc0, #0; vldb.128 wl4, [p4, #0]
; NO-JNZD-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p2], #64; vldb.128 wl6, [p4, #16]; movxm ls, #.LBB0_2
; NO-JNZD-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p2], #64; vldb x8, [p1], m4; movx r24, #0; mov r21, r8
; NO-JNZD-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p2], #64; movxm le, #.L_LEnd1
; NO-JNZD-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p2], #64; vbcst.32 x2, r24
; NO-JNZD-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p2], #64; movs dc1, dc0; mov dc5, dc0
; NO-JNZD-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p2], #64; vldb.3d x1, [p1], d1; movx r24, #15; mov s0, r24
; NO-JNZD-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p2], #64; movx crupsmode, #0; vsel.32 x4, x2, x4, r24
; NO-JNZD-NEXT:    lda m2, [p6], #-4; vsel.32 x2, x2, x6, r24
; NO-JNZD-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p2], #64; or r23, r10, r10; vshuffle x8, x8, x0, r1
; NO-JNZD-NEXT:    lda dj2, [p6], #-4; or r25, r12, r12; vshuffle x10, x8, x0, r2
; NO-JNZD-NEXT:    lda dn2, [p6], #-4; vldb x6, [p0], #64; movx r22, #1; mov s1, r17; movs dc4, dc0
; NO-JNZD-NEXT:    lda m3, [p6], #-4; movs m0, p5; movx r12, #776; mov srssign0, r19
; NO-JNZD-NEXT:    lda dj3, [p6, #0]; vldb.3d x8, [p0], d0; or r10, r5, r5; vshuffle x1, x1, x0, r3
; NO-JNZD-NEXT:    lda dn3, [p6, #-4]; movs dc3, dc2; movx crsrsmode, #0; vshuffle x1, x1, x0, r4
; NO-JNZD-NEXT:  .LBB0_1: // %for.body
; NO-JNZD-NEXT:    // =>This Loop Header: Depth=1
; NO-JNZD-NEXT:    // Child Loop BB0_2 Depth 2
; NO-JNZD-NEXT:    movs m0, p5; vldb x9, [p1], m4; nopx
; NO-JNZD-NEXT:    vlda.3d x7, [p1], d1; vmul dm4, x0, x4, r12
; NO-JNZD-NEXT:    vldb x5, [p0], #64
; NO-JNZD-NEXT:    vlda.3d x3, [p0], d0; vaddmac dm3, dm3, dm4, x6, x10, r10
; NO-JNZD-NEXT:    movs m0, p5; vldb x9, [p1], m4; vmul dm4, x0, x2, r12
; NO-JNZD-NEXT:    vlda.3d x7, [p1], d1; vaddmac dm2, dm2, dm4, x8, x10, r10
; NO-JNZD-NEXT:    vldb x5, [p0], #64; vaddmac dm1, dm1, dm4, x6, x1, r10
; NO-JNZD-NEXT:    vlda.3d x3, [p0], d0; vshuffle x1, x9, x0, r7; vaddmac dm0, dm0, dm4, x8, x1, r10
; NO-JNZD-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; add.nc lc, r6, #-3; vshuffle x10, x1, x0, r16; nopv
; NO-JNZD-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; nopv
; NO-JNZD-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-JNZD-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; NO-JNZD-NEXT:  .LBB0_2: // %for.body100
; NO-JNZD-NEXT:    // Parent Loop BB0_1 Depth=1
; NO-JNZD-NEXT:    // => This Inner Loop Header: Depth=2
; NO-JNZD-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; nopx ; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; NO-JNZD-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; NO-JNZD-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-JNZD-NEXT:  .L_LEnd1:
; NO-JNZD-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; NO-JNZD-NEXT:  // %bb.3: // %for.cond.cleanup99
; NO-JNZD-NEXT:    // in Loop: Header=BB0_1 Depth=1
; NO-JNZD-NEXT:    nopa ; paddb.2d [p4], d3; movs m0, p5; add r0, r0, #-1; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; NO-JNZD-NEXT:    nopa ; vldb.128 wl1, [p4, #16]; nops ; ne r26, r0, r22; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; NO-JNZD-NEXT:    vldb.128 wl10, [p4, #0]; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-JNZD-NEXT:    vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; NO-JNZD-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p2], #64; vldb x3, [p1], m4; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; NO-JNZD-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p2], #64; vldb.3d x5, [p1], d1; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; NO-JNZD-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p2], #64; vldb x6, [p0], #64; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; NO-JNZD-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p2], #64; vldb.3d x8, [p0], d0; vmac dm2, dm2, x3, x10, r8
; NO-JNZD-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p2], #64; vsel.32 x2, x2, x1, r24; vmac dm1, dm1, x5, x6, r8
; NO-JNZD-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p2], #64; vsel.32 x4, x4, x10, r24; vmac dm0, dm0, x3, x6, r8
; NO-JNZD-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p2], #64
; NO-JNZD-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p2], #64; vshuffle x10, x3, x0, r1
; NO-JNZD-NEXT:    vst.srs.4x dm3, s1, srssign0, [p3], #64; vshuffle x1, x5, x0, r3
; NO-JNZD-NEXT:    vst.srs.4x dm2, s1, srssign0, [p3], m5; vshuffle x10, x10, x0, r2
; NO-JNZD-NEXT:    vst.srs.4x dm1, s1, srssign0, [p3], #64; vshuffle x1, x1, x0, r4
; NO-JNZD-NEXT:    vst.2d.srs.4x dm0, s1, srssign0, [p3], d2; jnz r26, #.LBB0_1
; NO-JNZD-NEXT:    nop // Delay Slot 5
; NO-JNZD-NEXT:    nop // Delay Slot 4
; NO-JNZD-NEXT:    nop // Delay Slot 3
; NO-JNZD-NEXT:    nop // Delay Slot 2
; NO-JNZD-NEXT:    nop // Delay Slot 1
; NO-JNZD-NEXT:  // %bb.4: // %cooldown.entry
; NO-JNZD-NEXT:    vldb x3, [p1], m4; vmul dm4, x0, x4, r12
; NO-JNZD-NEXT:    vlda.3d x1, [p1], d1
; NO-JNZD-NEXT:    vldb x10, [p0], #64; mov m0, p5; vaddmac dm3, dm3, dm4, x6, x10, r10
; NO-JNZD-NEXT:    vlda.3d x8, [p0], d0; vmul dm4, x0, x2, r12
; NO-JNZD-NEXT:    vldb x3, [p1], m4; vaddmac dm2, dm2, dm4, x8, x10, r10
; NO-JNZD-NEXT:    vlda.3d x1, [p1], d1; movxm ls, #.LBB0_5; vaddmac dm1, dm1, dm4, x6, x1, r10
; NO-JNZD-NEXT:    vldb x10, [p0], #64; movxm le, #.L_LEnd0; vaddmac dm0, dm0, dm4, x8, x1, r10
; NO-JNZD-NEXT:    vlda.3d x8, [p0], d0; vshuffle x6, x3, x0, r7
; NO-JNZD-NEXT:    nopa ; vldb x3, [p1], m4; nops ; add.nc lc, r6, #-3; vshuffle x4, x6, x0, r16; nopv
; NO-JNZD-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; nopv
; NO-JNZD-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-JNZD-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; movx srssign0, #0; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; NO-JNZD-NEXT:  .LBB0_5: // %for.body100.cd
; NO-JNZD-NEXT:    // =>This Inner Loop Header: Depth=1
; NO-JNZD-NEXT:    nopa ; vldb x3, [p1], m4; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; NO-JNZD-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; NO-JNZD-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-JNZD-NEXT:  .L_LEnd0:
; NO-JNZD-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; nopx ; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; NO-JNZD-NEXT:  // %bb.6: // %cooldown.exit
; NO-JNZD-NEXT:    lda p6, [sp, #-64]; nopb ; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8 // 4-byte Folded Reload
; NO-JNZD-NEXT:    paddxm [sp], #-64; nopb ; nops ; movx crsrsmode, #0; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; NO-JNZD-NEXT:    or r12, r25, r25; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-JNZD-NEXT:    or r10, r23, r23; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; NO-JNZD-NEXT:    vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; NO-JNZD-NEXT:    vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; NO-JNZD-NEXT:    vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; NO-JNZD-NEXT:    mov s0, r17; vmac dm2, dm2, x8, x4, r8
; NO-JNZD-NEXT:    mov srssign0, r19; vmac dm1, dm1, x10, x0, r8
; NO-JNZD-NEXT:    vmac dm0, dm0, x8, x0, r8
; NO-JNZD-NEXT:    mov r8, r21
; NO-JNZD-NEXT:    nop
; NO-JNZD-NEXT:    vst.srs.4x dm3, s0, srssign0, [p3], #64
; NO-JNZD-NEXT:    vst.srs.4x dm2, s0, srssign0, [p3], m5; ret lr
; NO-JNZD-NEXT:    vst.srs.4x dm1, s0, srssign0, [p3, #0] // Delay Slot 5
; NO-JNZD-NEXT:    vst.srs.4x dm0, s0, srssign0, [p3, #64]; movx srssign0, #0 // Delay Slot 4
; NO-JNZD-NEXT:    nop // Delay Slot 3
; NO-JNZD-NEXT:    nop // Delay Slot 2
; NO-JNZD-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %for.body

for.body:                                         ; preds = %newFuncRoot, %for.cond.cleanup99
  %lsr.iv806 = phi i32 [ %0, %newFuncRoot ], [ %lsr.iv.next807, %for.cond.cleanup99 ]
  %p_mat_a.0766 = phi ptr addrspace(5) [ %1, %newFuncRoot ], [ %137, %for.cond.cleanup99 ]
  %p_mat_b.0765 = phi ptr addrspace(5) [ %2, %newFuncRoot ], [ %136, %for.cond.cleanup99 ]
  %p_psum_in.0.in764 = phi ptr [ %p_psum, %newFuncRoot ], [ %add.ptr.i370, %for.cond.cleanup99 ]
  %p_mat_c.0.in763 = phi ptr [ %p_c, %newFuncRoot ], [ %147, %for.cond.cleanup99 ]
  %p_bias_in.0.in762 = phi ptr [ %p_bias, %newFuncRoot ], [ %152, %for.cond.cleanup99 ]
  %iterator_mat_a_cnt0.0761 = phi i32 [ 0, %newFuncRoot ], [ %113, %for.cond.cleanup99 ]
  %iterator_mat_a_cnt1.0760 = phi i32 [ 0, %newFuncRoot ], [ %115, %for.cond.cleanup99 ]
  %iterator_mat_b_cnt0.0759 = phi i32 [ 0, %newFuncRoot ], [ %122, %for.cond.cleanup99 ]
  %iterator_mat_b_cnt1.0758 = phi i32 [ 0, %newFuncRoot ], [ %124, %for.cond.cleanup99 ]
  %iterator_mat_c_cnt0.0757 = phi i32 [ 0, %newFuncRoot ], [ %146, %for.cond.cleanup99 ]
  %iterator_psum_out_cnt0.0756 = phi i32 [ 0, %newFuncRoot ], [ %151, %for.cond.cleanup99 ]
  %B0.sroa.0.0755 = phi <8 x i32> [ zeroinitializer, %newFuncRoot ], [ %shuffle1.i.i.i.i.i, %for.cond.cleanup99 ]
  %B1.sroa.0.0754 = phi <8 x i32> [ zeroinitializer, %newFuncRoot ], [ %shuffle1.i.i.i.i.i306, %for.cond.cleanup99 ]
  %p_psum_in.0768 = addrspacecast ptr %p_psum_in.0.in764 to ptr addrspace(7)
  %p_bias_in.0 = addrspacecast ptr %p_bias_in.0.in762 to ptr addrspace(6)
  %29 = load <4 x i32>, ptr addrspace(6) %p_bias_in.0, align 16, !tbaa !4
  %shuffle.i.i.i.i.i = shufflevector <4 x i32> %29, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i = shufflevector <8 x i32> %shuffle.i.i.i.i.i, <8 x i32> %B0.sroa.0.0755, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i = getelementptr inbounds nuw i8, ptr %p_bias_in.0.in762, i20 16
  %add.ptr.ascast.i = addrspacecast ptr %add.ptr.i to ptr addrspace(6)
  %30 = load <4 x i32>, ptr addrspace(6) %add.ptr.ascast.i, align 16, !tbaa !4
  %shuffle.i.i.i.i.i305 = shufflevector <4 x i32> %30, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i306 = shufflevector <8 x i32> %shuffle.i.i.i.i.i305, <8 x i32> %B1.sroa.0.0754, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %31 = load <32 x i16>, ptr addrspace(5) %p_mat_a.0766, align 64, !tbaa !4, !noalias !7
  %32 = addrspacecast ptr addrspace(5) %p_mat_a.0766 to ptr
  %add.ptr.i309 = getelementptr inbounds nuw i8, ptr %32, i20 64
  %add.ptr.ascast.i310 = addrspacecast ptr %add.ptr.i309 to ptr addrspace(5)
  %33 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i310, align 64, !tbaa !4, !noalias !14
  %34 = trunc nuw i32 %iterator_mat_a_cnt0.0761 to i20
  %35 = trunc nuw i32 %iterator_mat_a_cnt1.0760 to i20
  %36 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i309, i20 %3, i20 %4, i20 %5, i20 %6, i20 %34, i20 %7, i20 %35)
  %37 = extractvalue { ptr, i20, i20 } %36, 1
  %38 = zext i20 %37 to i32
  %39 = extractvalue { ptr, i20, i20 } %36, 2
  %40 = zext i20 %39 to i32
  %41 = load <16 x i32>, ptr addrspace(5) %p_mat_b.0765, align 64, !tbaa !4, !noalias !21
  %42 = addrspacecast ptr addrspace(5) %p_mat_b.0765 to ptr
  %add.ptr.i313 = getelementptr inbounds i8, ptr %42, i20 %idx.ext.i
  %add.ptr.ascast.i314 = addrspacecast ptr %add.ptr.i313 to ptr addrspace(5)
  %43 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i314, align 64, !tbaa !4, !noalias !28
  %44 = trunc nuw i32 %iterator_mat_b_cnt0.0759 to i20
  %45 = trunc nuw i32 %iterator_mat_b_cnt1.0758 to i20
  %46 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i313, i20 %8, i20 %9, i20 %10, i20 %11, i20 %44, i20 %12, i20 %45)
  %47 = extractvalue { ptr, i20, i20 } %46, 1
  %48 = zext i20 %47 to i32
  %49 = extractvalue { ptr, i20, i20 } %46, 2
  %50 = zext i20 %49 to i32
  %51 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %41, <16 x i32> poison, i32 %13)
  %52 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %51, <16 x i32> poison, i32 %14)
  %53 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %43, <16 x i32> poison, i32 %15)
  %54 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %53, <16 x i32> poison, i32 %16)
  %55 = load <32 x i16>, ptr addrspace(7) %p_psum_in.0768, align 64, !tbaa !4, !noalias !35
  %arrayidx.i.i.i.i.i.i.i.i.i.i = getelementptr inbounds nuw i8, ptr addrspace(7) %p_psum_in.0768, i20 64
  %56 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i, align 64, !tbaa !4, !noalias !35
  %57 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %55, i32 0, i32 range(i32 0, 2) 1)
  %58 = bitcast <32 x i32> %57 to <16 x i64>
  %59 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %56, i32 0, i32 range(i32 0, 2) 1)
  %60 = bitcast <32 x i32> %59 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %58, <16 x i64> %60, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i352 = getelementptr inbounds nuw i8, ptr %p_psum_in.0.in764, i20 128
  %add.ptr.ascast.i353 = addrspacecast ptr %add.ptr.i352 to ptr addrspace(7)
  %61 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i353, align 64, !tbaa !4, !noalias !42
  %arrayidx.i.i.i.i.i.i.i.i.i.i354 = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i353, i20 64
  %62 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i354, align 64, !tbaa !4, !noalias !42
  %63 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %61, i32 0, i32 range(i32 0, 2) 1)
  %64 = bitcast <32 x i32> %63 to <16 x i64>
  %65 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %62, i32 0, i32 range(i32 0, 2) 1)
  %66 = bitcast <32 x i32> %65 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i357 = shufflevector <16 x i64> %64, <16 x i64> %66, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i358 = getelementptr inbounds nuw i8, ptr %p_psum_in.0.in764, i20 256
  %add.ptr.ascast.i359 = addrspacecast ptr %add.ptr.i358 to ptr addrspace(7)
  %67 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i359, align 64, !tbaa !4, !noalias !49
  %arrayidx.i.i.i.i.i.i.i.i.i.i360 = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i359, i20 64
  %68 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i360, align 64, !tbaa !4, !noalias !49
  %69 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %67, i32 0, i32 range(i32 0, 2) 1)
  %70 = bitcast <32 x i32> %69 to <16 x i64>
  %71 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %68, i32 0, i32 range(i32 0, 2) 1)
  %72 = bitcast <32 x i32> %71 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i363 = shufflevector <16 x i64> %70, <16 x i64> %72, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i364 = getelementptr inbounds nuw i8, ptr %p_psum_in.0.in764, i20 384
  %add.ptr.ascast.i365 = addrspacecast ptr %add.ptr.i364 to ptr addrspace(7)
  %73 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i365, align 64, !tbaa !4, !noalias !56
  %arrayidx.i.i.i.i.i.i.i.i.i.i366 = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i365, i20 64
  %74 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i366, align 64, !tbaa !4, !noalias !56
  %75 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %73, i32 0, i32 range(i32 0, 2) 1)
  %76 = bitcast <32 x i32> %75 to <16 x i64>
  %77 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %74, i32 0, i32 range(i32 0, 2) 1)
  %78 = bitcast <32 x i32> %77 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i369 = shufflevector <16 x i64> %76, <16 x i64> %78, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %79 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i to <64 x i32>
  %80 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i357 to <64 x i32>
  %81 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i363 to <64 x i32>
  %82 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i369 to <64 x i32>
  %83 = bitcast <16 x i32> %52 to <32 x i16>
  %84 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %31, <32 x i16> %83, <64 x i32> %79, i32 %or23.i.i.i.i)
  %85 = bitcast <64 x i32> %84 to <32 x i64>
  %86 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %33, <32 x i16> %83, <64 x i32> %80, i32 %or23.i.i.i.i)
  %87 = bitcast <64 x i32> %86 to <32 x i64>
  %88 = bitcast <16 x i32> %54 to <32 x i16>
  %89 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %31, <32 x i16> %88, <64 x i32> %81, i32 %or23.i.i.i.i)
  %90 = bitcast <64 x i32> %89 to <32 x i64>
  %91 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %33, <32 x i16> %88, <64 x i32> %82, i32 %or23.i.i.i.i)
  %92 = bitcast <64 x i32> %91 to <32 x i64>
  %shuffle.i.i.i.i.i9.i.i.i.i = shufflevector <8 x i32> %shuffle1.i.i.i.i.i, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %93 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i to <64 x i8>
  %94 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %17, <64 x i8> %93, i32 776)
  %95 = bitcast <64 x i32> %94 to <32 x i64>
  %96 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %85, <32 x i64> %95, i32 0)
  %97 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %87, <32 x i64> %95, i32 0)
  %shuffle.i.i.i.i.i9.i.i.i.i465 = shufflevector <8 x i32> %shuffle1.i.i.i.i.i306, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %98 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i465 to <64 x i8>
  %99 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %17, <64 x i8> %98, i32 776)
  %100 = bitcast <64 x i32> %99 to <32 x i64>
  %101 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %90, <32 x i64> %100, i32 0)
  %102 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %92, <32 x i64> %100, i32 0)
  %103 = bitcast <32 x i64> %96 to <64 x i32>
  %104 = bitcast <32 x i64> %97 to <64 x i32>
  %105 = bitcast <32 x i64> %101 to <64 x i32>
  %106 = bitcast <32 x i64> %102 to <64 x i32>
  %p_mat_a.1.in735 = extractvalue { ptr, i20, i20 } %36, 0
  %p_mat_a.1736 = addrspacecast ptr %p_mat_a.1.in735 to ptr addrspace(5)
  %p_mat_b.1.in737 = extractvalue { ptr, i20, i20 } %46, 0
  %p_mat_b.1738 = addrspacecast ptr %p_mat_b.1.in737 to ptr addrspace(5)
  call void @llvm.set.loop.iterations.i32(i32 %18)
  br label %for.body100

for.body100:                                      ; preds = %for.body100, %for.body
  %p_mat_b.1751 = phi ptr addrspace(5) [ %p_mat_b.1738, %for.body ], [ %p_mat_b.1, %for.body100 ]
  %p_mat_b.1.in750 = phi ptr [ %p_mat_b.1.in737, %for.body ], [ %p_mat_b.1.in, %for.body100 ]
  %p_mat_a.1749 = phi ptr addrspace(5) [ %p_mat_a.1736, %for.body ], [ %p_mat_a.1, %for.body100 ]
  %p_mat_a.1.in748 = phi ptr [ %p_mat_a.1.in735, %for.body ], [ %p_mat_a.1.in, %for.body100 ]
  %iterator_mat_a_cnt0.1746 = phi i32 [ %38, %for.body ], [ %113, %for.body100 ]
  %iterator_mat_a_cnt1.1745 = phi i32 [ %40, %for.body ], [ %115, %for.body100 ]
  %iterator_mat_b_cnt0.1744 = phi i32 [ %48, %for.body ], [ %122, %for.body100 ]
  %iterator_mat_b_cnt1.1743 = phi i32 [ %50, %for.body ], [ %124, %for.body100 ]
  %Ci3.sroa.0.0742 = phi <64 x i32> [ %106, %for.body ], [ %134, %for.body100 ]
  %Ci2.sroa.0.0741 = phi <64 x i32> [ %105, %for.body ], [ %133, %for.body100 ]
  %Ci1.sroa.0.0740 = phi <64 x i32> [ %104, %for.body ], [ %131, %for.body100 ]
  %Ci0.sroa.0.0739 = phi <64 x i32> [ %103, %for.body ], [ %130, %for.body100 ]
  %107 = load <32 x i16>, ptr addrspace(5) %p_mat_a.1749, align 64, !tbaa !4, !noalias !63
  %add.ptr.i485 = getelementptr inbounds nuw i8, ptr %p_mat_a.1.in748, i20 64
  %add.ptr.ascast.i486 = addrspacecast ptr %add.ptr.i485 to ptr addrspace(5)
  %108 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i486, align 64, !tbaa !4, !noalias !70
  %109 = trunc nuw i32 %iterator_mat_a_cnt0.1746 to i20
  %110 = trunc nuw i32 %iterator_mat_a_cnt1.1745 to i20
  %111 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i485, i20 %3, i20 %4, i20 %5, i20 %6, i20 %109, i20 %7, i20 %110)
  %112 = extractvalue { ptr, i20, i20 } %111, 1
  %113 = zext i20 %112 to i32
  %114 = extractvalue { ptr, i20, i20 } %111, 2
  %115 = zext i20 %114 to i32
  %116 = load <16 x i32>, ptr addrspace(5) %p_mat_b.1751, align 64, !tbaa !4, !noalias !77
  %add.ptr.i490 = getelementptr inbounds i8, ptr %p_mat_b.1.in750, i20 %idx.ext.i
  %add.ptr.ascast.i491 = addrspacecast ptr %add.ptr.i490 to ptr addrspace(5)
  %117 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i491, align 64, !tbaa !4, !noalias !84
  %118 = trunc nuw i32 %iterator_mat_b_cnt0.1744 to i20
  %119 = trunc nuw i32 %iterator_mat_b_cnt1.1743 to i20
  %120 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i490, i20 %8, i20 %9, i20 %10, i20 %11, i20 %118, i20 %12, i20 %119)
  %121 = extractvalue { ptr, i20, i20 } %120, 1
  %122 = zext i20 %121 to i32
  %123 = extractvalue { ptr, i20, i20 } %120, 2
  %124 = zext i20 %123 to i32
  %125 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %116, <16 x i32> poison, i32 %19)
  %126 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %125, <16 x i32> poison, i32 %20)
  %127 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %117, <16 x i32> poison, i32 %21)
  %128 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %127, <16 x i32> poison, i32 %22)
  %129 = bitcast <16 x i32> %126 to <32 x i16>
  %130 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %107, <32 x i16> %129, <64 x i32> %Ci0.sroa.0.0739, i32 %or22.i.i.i.i)
  %131 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %108, <32 x i16> %129, <64 x i32> %Ci1.sroa.0.0740, i32 %or22.i.i.i.i)
  %132 = bitcast <16 x i32> %128 to <32 x i16>
  %133 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %107, <32 x i16> %132, <64 x i32> %Ci2.sroa.0.0741, i32 %or22.i.i.i.i)
  %134 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %108, <32 x i16> %132, <64 x i32> %Ci3.sroa.0.0742, i32 %or22.i.i.i.i)
  %p_mat_a.1.in = extractvalue { ptr, i20, i20 } %111, 0
  %p_mat_a.1 = addrspacecast ptr %p_mat_a.1.in to ptr addrspace(5)
  %p_mat_b.1.in = extractvalue { ptr, i20, i20 } %120, 0
  %p_mat_b.1 = addrspacecast ptr %p_mat_b.1.in to ptr addrspace(5)
  %135 = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %135, label %for.body100, label %for.cond.cleanup99, !llvm.loop !91

for.cond.cleanup99:                               ; preds = %for.body100
  %136 = addrspacecast ptr %p_mat_b.1.in to ptr addrspace(5)
  %137 = addrspacecast ptr %p_mat_a.1.in to ptr addrspace(5)
  %138 = addrspacecast ptr %p_mat_c.0.in763 to ptr addrspace(6)
  %add.ptr.i370 = getelementptr inbounds nuw i8, ptr %p_psum_in.0.in764, i20 512
  %139 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %130, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %139, ptr addrspace(6) %138, align 64, !tbaa !4
  %add.ptr.i475 = getelementptr inbounds nuw i8, ptr %p_mat_c.0.in763, i20 64
  %add.ptr.ascast.i476 = addrspacecast ptr %add.ptr.i475 to ptr addrspace(6)
  %140 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %131, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %140, ptr addrspace(6) %add.ptr.ascast.i476, align 64, !tbaa !4
  %add.ptr.i479 = getelementptr inbounds i8, ptr %add.ptr.i475, i20 %idx.ext.i478
  %add.ptr.ascast.i480 = addrspacecast ptr %add.ptr.i479 to ptr addrspace(6)
  %141 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %133, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %141, ptr addrspace(6) %add.ptr.ascast.i480, align 64, !tbaa !4
  %add.ptr.i482 = getelementptr inbounds nuw i8, ptr %add.ptr.i479, i20 64
  %add.ptr.ascast.i483 = addrspacecast ptr %add.ptr.i482 to ptr addrspace(6)
  %142 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %134, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %142, ptr addrspace(6) %add.ptr.ascast.i483, align 64, !tbaa !4
  %143 = trunc nuw i32 %iterator_mat_c_cnt0.0757 to i20
  %144 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr nonnull %add.ptr.i482, i20 %23, i20 %24, i20 %25, i20 %143)
  %145 = extractvalue { ptr, i20 } %144, 1
  %146 = zext i20 %145 to i32
  %147 = extractvalue { ptr, i20 } %144, 0
  %148 = trunc nuw i32 %iterator_psum_out_cnt0.0756 to i20
  %149 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr nonnull %p_bias_in.0.in762, i20 %26, i20 %27, i20 %28, i20 %148)
  %150 = extractvalue { ptr, i20 } %149, 1
  %151 = zext i20 %150 to i32
  %152 = extractvalue { ptr, i20 } %149, 0
  %lsr.iv.next807 = add nsw i32 %lsr.iv806, -1
  %exitcond777.not = icmp eq i32 %lsr.iv.next807, 0
  br i1 %exitcond777.not, label %for.cond.cleanup, label %for.body, !llvm.loop !94

for.cond.cleanup:                                 ; preds = %for.cond.cleanup99
  br label %for.cond.cleanup.ret.exitStub

for.cond.cleanup.ret.exitStub:                    ; preds = %for.cond.cleanup
  ret void
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #2 = { nocallback noduplicate nofree nosync nounwind willreturn }
attributes #3 = { mustprogress noinline "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 21.0.0git"}
!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{!8, !10, !12}
!8 = distinct !{!8, !9, !"A: %agg.result"}
!9 = distinct !{!9, !"A"}
!10 = distinct !{!10, !11, !"B: %agg.result"}
!11 = distinct !{!11, !"B"}
!12 = distinct !{!12, !13, !"C: %agg.result"}
!13 = distinct !{!13, !"C"}
!14 = !{!15, !17, !19}
!15 = distinct !{!15, !16, !"A: %agg.result"}
!16 = distinct !{!16, !"A"}
!17 = distinct !{!17, !18, !"B: %agg.result"}
!18 = distinct !{!18, !"B"}
!19 = distinct !{!19, !20, !"C: %agg.result"}
!20 = distinct !{!20, !"C"}
!21 = !{!22, !24, !26}
!22 = distinct !{!22, !23, !"A: %agg.result"}
!23 = distinct !{!23, !"A"}
!24 = distinct !{!24, !25, !"B: %agg.result"}
!25 = distinct !{!25, !"B"}
!26 = distinct !{!26, !27, !"C: %agg.result"}
!27 = distinct !{!27, !"C"}
!28 = !{!29, !31, !33}
!29 = distinct !{!29, !30, !"A: %agg.result"}
!30 = distinct !{!30, !"A"}
!31 = distinct !{!31, !32, !"B: %agg.result"}
!32 = distinct !{!32, !"B"}
!33 = distinct !{!33, !34, !"C: %agg.result"}
!34 = distinct !{!34, !"C"}
!35 = !{!36, !38, !40}
!36 = distinct !{!36, !37, !"D: %agg.result"}
!37 = distinct !{!37, !"D"}
!38 = distinct !{!38, !39, !"E: %agg.result"}
!39 = distinct !{!39, !"E"}
!40 = distinct !{!40, !41, !"F: %agg.result"}
!41 = distinct !{!41, !"F"}
!42 = !{!43, !45, !47}
!43 = distinct !{!43, !44, !"D: %agg.result"}
!44 = distinct !{!44, !"D"}
!45 = distinct !{!45, !46, !"E: %agg.result"}
!46 = distinct !{!46, !"E"}
!47 = distinct !{!47, !48, !"F: %agg.result"}
!48 = distinct !{!48, !"F"}
!49 = !{!50, !52, !54}
!50 = distinct !{!50, !51, !"D: %agg.result"}
!51 = distinct !{!51, !"D"}
!52 = distinct !{!52, !53, !"E: %agg.result"}
!53 = distinct !{!53, !"E"}
!54 = distinct !{!54, !55, !"F: %agg.result"}
!55 = distinct !{!55, !"F"}
!56 = !{!57, !59, !61}
!57 = distinct !{!57, !58, !"D: %agg.result"}
!58 = distinct !{!58, !"D"}
!59 = distinct !{!59, !60, !"E: %agg.result"}
!60 = distinct !{!60, !"E"}
!61 = distinct !{!61, !62, !"F: %agg.result"}
!62 = distinct !{!62, !"F"}
!63 = !{!64, !66, !68}
!64 = distinct !{!64, !65, !"A: %agg.result"}
!65 = distinct !{!65, !"A"}
!66 = distinct !{!66, !67, !"B: %agg.result"}
!67 = distinct !{!67, !"B"}
!68 = distinct !{!68, !69, !"C: %agg.result"}
!69 = distinct !{!69, !"C"}
!70 = !{!71, !73, !75}
!71 = distinct !{!71, !72, !"A: %agg.result"}
!72 = distinct !{!72, !"A"}
!73 = distinct !{!73, !74, !"B: %agg.result"}
!74 = distinct !{!74, !"B"}
!75 = distinct !{!75, !76, !"C: %agg.result"}
!76 = distinct !{!76, !"C"}
!77 = !{!78, !80, !82}
!78 = distinct !{!78, !79, !"A: %agg.result"}
!79 = distinct !{!79, !"A"}
!80 = distinct !{!80, !81, !"B: %agg.result"}
!81 = distinct !{!81, !"B"}
!82 = distinct !{!82, !83, !"C: %agg.result"}
!83 = distinct !{!83, !"C"}
!84 = !{!85, !87, !89}
!85 = distinct !{!85, !86, !"A: %agg.result"}
!86 = distinct !{!86, !"A"}
!87 = distinct !{!87, !88, !"B: %agg.result"}
!88 = distinct !{!88, !"B"}
!89 = distinct !{!89, !90, !"C: %agg.result"}
!90 = distinct !{!90, !"C"}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.mustprogress"}
!93 = !{!"llvm.loop.itercount.range", i64 4}
!94 = distinct !{!94, !92, !95, !96}
!95 = !{!"llvm.loop.itercount.range", i64 2}
!96 = !{!"llvm.loop.hint.aie-enable-outer-loop-pipelining", i64 1}
