; NOTE: Assertions have been autogenerated by utils/update_ore_test_checks.py UTC_ARGS: --update-llc-checks
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; Isolated from Gemm_int8_4 gemm_generic<(out_mode_t)0, signed char, true>.
; The pre-OLP input exercises outer-loop and post-pipelining together.
;
; RUN: llc -mtriple=aie2ps --aie-enable-outer-loop-pipelining -o - %s | FileCheck %s
; RUN: llc -mtriple=aie2ps --aie-enable-outer-loop-pipelining -pass-remarks-output=- -pass-remarks-filter='pipeliner' %s -o /dev/null | FileCheck %s --check-prefix=REMARKS

%"struct.std::__1::array" = type { [7 x %"struct.std::__1::array.28"] }
%"struct.std::__1::array.28" = type { [2 x i32] }

@_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE = external dso_local local_unnamed_addr constant %"struct.std::__1::array", align 4

; Function Attrs: mustprogress noinline
define dso_local void @gemm_int8_psum_0_v2(ptr noalias %p_a, ptr noalias %p_b, ptr noalias %p_c, ptr noalias %p_bias, ptr noalias %p_psum, ptr nonnull align 32 dereferenceable(160) %param) local_unnamed_addr #3 {
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            schedule
; REMARKS-NEXT: Function:        gemm_int8_psum_0_v2
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Unable to find schedule
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            schedule
; REMARKS-NEXT: Function:        gemm_int8_psum_0_v2
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Unable to find schedule
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            canPipelineLoop
; REMARKS-NEXT: Function:        gemm_int8_psum_0_v2
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          'Not a single basic block: '
; REMARKS-NEXT:   - NumBlocks:       '3'
; REMARKS-NEXT: ...
; REMARKS: --- !Missed
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            canPipelineLoop
; REMARKS-NEXT: Function:        gemm_int8_psum_0_v2
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Failed to pipeline loop
; REMARKS-NEXT: ...
; REMARKS: --- !Passed
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            schedule
; REMARKS-NEXT: Function:        gemm_int8_psum_0_v2
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Schedule found
; REMARKS-NEXT:   - Pipeliner:       postpipeliner
; REMARKS-NEXT:   - II:              '4'
; REMARKS-NEXT:   - NS:              '4'
; REMARKS-NEXT:   - Loop:            bb.2.steady.stage1.inner.for.body143
; REMARKS-NEXT:   - Prologue:        bb.1.steady.stage1.top
; REMARKS-NEXT:   - PrologueBundles: '12'
; REMARKS-NEXT:   - Epilogue:        bb.3.steady.stage1.bottom.and.stage0.top
; REMARKS-NEXT:   - EpilogueBundles: '27'
; REMARKS-NEXT: ...
; REMARKS: --- !Passed
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            schedule
; REMARKS-NEXT: Function:        gemm_int8_psum_0_v2
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Schedule found
; REMARKS-NEXT:   - Pipeliner:       postpipeliner
; REMARKS-NEXT:   - II:              '4'
; REMARKS-NEXT:   - NS:              '4'
; REMARKS-NEXT:   - Loop:            bb.5.lastiter.stage1.inner.for.body143
; REMARKS-NEXT:   - Prologue:        bb.4.lastiter.stage1.top
; REMARKS-NEXT:   - PrologueBundles: '12'
; REMARKS-NEXT:   - Epilogue:        bb.6.lastiter.stage1.bottom
; REMARKS-NEXT:   - EpilogueBundles: '19'
; REMARKS-NEXT: ...
; CHECK-LABEL: gemm_int8_psum_0_v2:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    paddxm [sp], #64
; CHECK-NEXT:    vlda bmll5, [p4], #64; mov dj0, #37
; CHECK-NEXT:    lda.u8 r2, [p5, dj0]
; CHECK-NEXT:    vlda bmlh5, [p4], #64; mov m0, #48
; CHECK-NEXT:    vlda.ups.2x bmll3, s0, upssign1, [p3, #0]; paddb [p5], m0; mov m2, #-44
; CHECK-NEXT:    lda.u8 r20, [p5], m2
; CHECK-NEXT:    vlda bmhl5, [p4], #64
; CHECK-NEXT:    lda r3, [p5], m0
; CHECK-NEXT:    vlda bmhh5, [p4], #64; movx r22, #0; mov m0, #24
; CHECK-NEXT:    lda.s8 r6, [p5], m0; mov s0, r22
; CHECK-NEXT:    vlda bmll2, [p4], #64; movx crupsmode, #0
; CHECK-NEXT:    lda m0, [p5], #-8
; CHECK-NEXT:    vlda bmlh2, [p4], #64
; CHECK-NEXT:    lda dn0, [p5], #-8
; CHECK-NEXT:    vlda bmhl2, [p4], #64
; CHECK-NEXT:    lda dj0, [p5], #12
; CHECK-NEXT:    vlda bmhh2, [p4], #64
; CHECK-NEXT:    lda dn4, [p5], #-8
; CHECK-NEXT:    vlda bmll1, [p4], #64; mov m1, #-48
; CHECK-NEXT:    lda dj4, [p5], m1
; CHECK-NEXT:    vlda bmlh1, [p4], #64; mov m1, #80
; CHECK-NEXT:    lda m4, [p5], m1
; CHECK-NEXT:    vlda bmhl1, [p4], #64
; CHECK-NEXT:    lda m1, [p5], #-8
; CHECK-NEXT:    lda dn1, [p5], #-8
; CHECK-NEXT:    lda dj1, [p5], #12; st p6, [sp, #-64]; movxm p6, ##_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE // 4-byte Folded Spill
; CHECK-NEXT:    lda dn5, [p5], #-8; sub r4, r22, r2
; CHECK-NEXT:    lda dj5, [p5], m2; and r27, r2, r4
; CHECK-NEXT:    mova m2, #15; clz r2, r27; mov r17, #32
; CHECK-NEXT:    lda.u8 r1, [p5], m2; sel.eqz r2, r17, r2, r27; mov r4, #31
; CHECK-NEXT:    mova m2, #-47; sub r2, r4, r2
; CHECK-NEXT:    lda.u8 r21, [p5], m2; movx r4, #3; mov m3, #46
; CHECK-NEXT:    lda r5, [p5], m3; lshl r2, r2, r4; mov m2, #-29
; CHECK-NEXT:    lda.u8 r7, [p5], #-1; mov m3, r2
; CHECK-NEXT:    lda.u8 r0, [p5], m2; paddb [p6], m3
; CHECK-NEXT:    lda r24, [p6, #4]
; CHECK-NEXT:    lda r26, [p6, #0]; movxm p6, ##_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE
; CHECK-NEXT:    padda [p6], m3
; CHECK-NEXT:    lda r28, [p6, #0]; mov m2, #84
; CHECK-NEXT:    lda m5, [p5], m2; movx crsrsmode, #0; mov r23, r8
; CHECK-NEXT:    lda r30, [p6, #4]; eqz r17, r20; mov dc2, #0
; CHECK-NEXT:    lda m2, [p5], #-4; movxm p6, ##_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE
; CHECK-NEXT:    lda dn2, [p5], #-4; paddb [p6], m3; movx r20, #1; mov m6, #32
; CHECK-NEXT:    lda r2, [p6, #0]; ne r19, r1, r20; mov s0, r6
; CHECK-NEXT:    lda r4, [p6, #4]; vldb x6, [p1], m4; movxm p6, ##_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE
; CHECK-NEXT:    mova r5, #768; add r1, r5, #-1; mov r27, r21
; CHECK-NEXT:    lda dj2, [p5], m6; vsrs.2x wl4, bmll3, s0, srssign1; sel.eqz r8, r22, r5, r27; mov dc0, #0
; CHECK-NEXT:    lda m3, [p5], #-4; movs dc1, dc0; add r5, r3, #-1; vbcst.32 x2, r22
; CHECK-NEXT:    lda dn3, [p5, #0]; movs dc5, dc0; movx r3, #16; vbcst.16 x0, r17
; CHECK-NEXT:    lda dj3, [p5, #-4]; vldb.3d x8, [p1], d1; movxm p5, #.LBB0_1
; CHECK-NEXT:    vlda bmhh1, [p4], #64; vshift x10, x4, x0, r3
; CHECK-NEXT:    vlda bmll0, [p4], #64; vshuffle x6, x6, x0, r26
; CHECK-NEXT:    vlda bmlh0, [p4], #64; movx r17, #15; addm.nc r5, r5, #-1
; CHECK-NEXT:    padda [p6], m3; or r25, r10, r10; vsel.32 x4, x2, x4, r17
; CHECK-NEXT:    vlda bmhl0, [p4], #64; vldb x6, [p0], #64; or r29, r12, r12; vsel.32 x2, x2, x10, r17
; CHECK-NEXT:    vlda bmhh0, [p4], #64; movs dc4, dc0; movx r12, #776; vshuffle x10, x6, x0, r24
; CHECK-NEXT:    lda r16, [p6, #0]; vldb.3d x8, [p0], d0; nez r20, r7; vshuffle x8, x8, x0, r28
; CHECK-NEXT:    lda r18, [p6, #4]; movs dc3, dc2; or r10, r8, r19; vshuffle x1, x8, x0, r30
; CHECK-NEXT:  .LBB0_1: // %steady.stage1.top
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_2 Depth 2
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopx ; vmul dm4, x0, x4, r12
; CHECK-NEXT:    vldb x5, [p0], #64
; CHECK-NEXT:    vlda.3d x3, [p0], d0; vaddmac dm5, dm5, dm4, x6, x10, r10
; CHECK-NEXT:    vldb x9, [p1], m4; vmul dm4, x0, x2, r12
; CHECK-NEXT:    vlda.3d x7, [p1], d1; movxm ls, #.LBB0_2; vaddmac dm2, dm2, dm4, x8, x10, r10
; CHECK-NEXT:    vldb x5, [p0], #64; movxm le, #.L_LEnd1; vaddmac dm1, dm1, dm4, x6, x1, r10
; CHECK-NEXT:    vlda.3d x3, [p0], d0; vshuffle x1, x9, x0, r2; vaddmac dm0, dm0, dm4, x8, x1, r10
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; nops ; add.nc lc, r1, #-3; vshuffle x10, x1, x0, r4; nopv
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r16; nopv
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r2; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  .LBB0_2: // %steady.stage1.inner.for.body143
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; nops ; nopx ; vshuffle x10, x1, x0, r4; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r16; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:  .L_LEnd1:
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r2; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  // %bb.3: // %steady.stage1.bottom.and.stage0.top
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    vlda x1, [p1], m4; paddb.2d [p3], d3; nops ; nopx ; vshuffle x10, x1, x0, r4; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r16; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vlda.ups.2x bmll4, s0, upssign1, [p3, #0]; nopx ; vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:    vshuffle x1, x9, x0, r2; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    vldb.3d x3, [p1], d1; vshuffle x10, x1, x0, r4; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vldb x6, [p0], #64; vshuffle x8, x7, x0, r16; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vlda bmll5, [p4], #64; vldb.3d x8, [p0], d0; vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:    vlda bmlh5, [p4], #64; mov s0, r22; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    vlda bmhl5, [p4], #64; mov s0, r0; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda bmhh5, [p4], #64; mov srssign0, r20; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vlda bmll2, [p4], #64
; CHECK-NEXT:    vlda bmlh2, [p4], #64
; CHECK-NEXT:    vlda bmhl2, [p4], #64; vst.srs.4x dm5, s0, srssign0, [p2], #64
; CHECK-NEXT:    vlda bmhh2, [p4], #64; vst.srs.4x dm2, s0, srssign0, [p2], m5
; CHECK-NEXT:    vlda bmll1, [p4], #64; vst.srs.4x dm1, s0, srssign0, [p2], #64
; CHECK-NEXT:    vlda bmlh1, [p4], #64; vst.2d.srs.4x dm0, s0, srssign0, [p2], d2; movx srssign0, #0; mov s0, r6
; CHECK-NEXT:    vlda bmhl1, [p4], #64; vsrs.2x wl10, bmll4, s0, srssign1
; CHECK-NEXT:    vlda bmhh1, [p4], #64
; CHECK-NEXT:    vlda bmll0, [p4], #64
; CHECK-NEXT:    vlda bmlh0, [p4], #64
; CHECK-NEXT:    vlda bmhl0, [p4], #64; vsel.32 x4, x4, x10, r17
; CHECK-NEXT:    vlda bmhh0, [p4], #64; jnzd r5, r5, p5; vshift x10, x10, x0, r3
; CHECK-NEXT:    vsel.32 x2, x2, x10, r17 // Delay Slot 5
; CHECK-NEXT:    vshuffle x10, x1, x0, r26 // Delay Slot 4
; CHECK-NEXT:    vshuffle x1, x3, x0, r28 // Delay Slot 3
; CHECK-NEXT:    vshuffle x10, x10, x0, r24 // Delay Slot 2
; CHECK-NEXT:    vshuffle x1, x1, x0, r30 // Delay Slot 1
; CHECK-NEXT:  // %bb.4: // %lastiter.stage1.top
; CHECK-NEXT:    vldb x9, [p1], m4
; CHECK-NEXT:    vlda.3d x7, [p1], d1; vmul dm4, x0, x4, r12
; CHECK-NEXT:    vldb x5, [p0], #64
; CHECK-NEXT:    vlda.3d x3, [p0], d0; vaddmac dm5, dm5, dm4, x6, x10, r10
; CHECK-NEXT:    vldb x9, [p1], m4; vmul dm4, x0, x2, r12
; CHECK-NEXT:    vlda.3d x7, [p1], d1; movxm ls, #.LBB0_5; vaddmac dm2, dm2, dm4, x8, x10, r10
; CHECK-NEXT:    vldb x5, [p0], #64; movxm le, #.L_LEnd0; vaddmac dm1, dm1, dm4, x6, x1, r10
; CHECK-NEXT:    vlda.3d x3, [p0], d0; vshuffle x1, x9, x0, r2; vaddmac dm0, dm0, dm4, x8, x1, r10
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; nops ; add.nc lc, r1, #-3; vshuffle x10, x1, x0, r4; nopv
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r16; nopv
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r2; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  .LBB0_5: // %lastiter.stage1.inner.for.body143
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; nops ; nopx ; vshuffle x10, x1, x0, r4; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r16; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r2; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  // %bb.6: // %lastiter.stage1.bottom
; CHECK-NEXT:    lda p6, [sp, #-64]; nopb ; nops ; nopx ; vshuffle x10, x1, x0, r4; vmac dm1, dm1, x5, x6, r8 // 4-byte Folded Reload
; CHECK-NEXT:    paddxm [sp], #-64; nopb ; nops ; movx crsrsmode, #0; vshuffle x8, x7, x0, r16; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    or r12, r29, r29; vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:    or r10, r25, r25; vshuffle x1, x9, x0, r2; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    vshuffle x10, x1, x0, r4; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vshuffle x8, x7, x0, r16; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vshuffle x6, x8, x0, r18; vmac dm5, dm5, x5, x10, r8
; CHECK-NEXT:    mov s0, r0; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    mov srssign0, r20; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    mov r8, r23
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.srs.4x dm5, s0, srssign0, [p2], #64
; CHECK-NEXT:    vst.srs.4x dm2, s0, srssign0, [p2], m5; ret lr
; CHECK-NEXT:    vst.srs.4x dm1, s0, srssign0, [p2, #0] // Delay Slot 5
; CHECK-NEXT:    vst.srs.4x dm0, s0, srssign0, [p2, #64]; movx srssign0, #0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %bias_zero_flag = getelementptr inbounds i8, ptr %param, i20 48
  %0 = load i8, ptr %bias_zero_flag, align 16, !tbaa !4
  %tobool.not = icmp eq i8 %0, 0
  %conv = zext i1 %tobool.not to i16
  %splat.splatinsert.i.i.i.i.i = insertelement <32 x i16> poison, i16 %conv, i64 0
  %splat.splat.i.i.i.i.i = shufflevector <32 x i16> %splat.splatinsert.i.i.i.i.i, <32 x i16> poison, <32 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %1 = bitcast <32 x i16> %splat.splat.i.i.i.i.i to <16 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i = shufflevector <16 x i32> %1, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %outer_count = getelementptr inbounds i8, ptr %param, i20 4
  %2 = load i32, ptr %outer_count, align 4, !tbaa !9
  %bias_init_shift = getelementptr inbounds i8, ptr %param, i20 52
  %3 = load i8, ptr %bias_init_shift, align 4, !tbaa !10
  %conv2 = sext i8 %3 to i32
  %iterator_mat_a_incr2 = getelementptr inbounds i8, ptr %param, i20 76
  %4 = load i32, ptr %iterator_mat_a_incr2, align 4, !tbaa !11
  %iterator_mat_a_wrap0 = getelementptr inbounds i8, ptr %param, i20 68
  %5 = load i32, ptr %iterator_mat_a_wrap0, align 4, !tbaa !12
  %iterator_mat_a_incr0 = getelementptr inbounds i8, ptr %param, i20 60
  %6 = load i32, ptr %iterator_mat_a_incr0, align 4, !tbaa !13
  %iterator_mat_a_wrap1 = getelementptr inbounds i8, ptr %param, i20 72
  %7 = load i32, ptr %iterator_mat_a_wrap1, align 8, !tbaa !14
  %iterator_mat_a_incr1 = getelementptr inbounds i8, ptr %param, i20 64
  %8 = load i32, ptr %iterator_mat_a_incr1, align 32, !tbaa !15
  %9 = trunc i32 %4 to i20
  %10 = trunc i32 %6 to i20
  %11 = trunc i32 %8 to i20
  %12 = trunc i32 %5 to i20
  %13 = trunc i32 %7 to i20
  %incB1 = getelementptr inbounds i8, ptr %param, i20 16
  %14 = load i32, ptr %incB1, align 16, !tbaa !16
  %idx.ext.i = trunc i32 %14 to i20
  %iterator_mat_b_incr2 = getelementptr inbounds i8, ptr %param, i20 96
  %15 = load i32, ptr %iterator_mat_b_incr2, align 32, !tbaa !17
  %iterator_mat_b_wrap0 = getelementptr inbounds i8, ptr %param, i20 88
  %16 = load i32, ptr %iterator_mat_b_wrap0, align 8, !tbaa !18
  %iterator_mat_b_incr0 = getelementptr inbounds i8, ptr %param, i20 80
  %17 = load i32, ptr %iterator_mat_b_incr0, align 16, !tbaa !19
  %iterator_mat_b_wrap1 = getelementptr inbounds i8, ptr %param, i20 92
  %18 = load i32, ptr %iterator_mat_b_wrap1, align 4, !tbaa !20
  %iterator_mat_b_incr1 = getelementptr inbounds i8, ptr %param, i20 84
  %19 = load i32, ptr %iterator_mat_b_incr1, align 4, !tbaa !21
  %20 = trunc i32 %15 to i20
  %21 = trunc i32 %17 to i20
  %22 = trunc i32 %19 to i20
  %23 = trunc i32 %16 to i20
  %24 = trunc i32 %18 to i20
  %mat_b_Imode_0 = getelementptr inbounds i8, ptr %param, i20 37
  %25 = load i8, ptr %mat_b_Imode_0, align 1, !tbaa !22
  %conv24 = zext i8 %25 to i32
  %psum_in = getelementptr inbounds i8, ptr %param, i20 40
  %26 = load i8, ptr %psum_in, align 8, !tbaa !23
  %tobool84 = icmp ne i8 %26, 1
  %ifm_sign = getelementptr inbounds i8, ptr %param, i20 55
  %27 = load i8, ptr %ifm_sign, align 1, !tbaa !24
  %tobool101.not = icmp eq i8 %27, 0
  %loadedv8.i.i = zext i1 %tobool84 to i32
  %or22.i.i.i.i = select i1 %tobool101.not, i32 0, i32 768
  %or25.i.i.i.i = or disjoint i32 %or22.i.i.i.i, %loadedv8.i.i
  %shuffle.i.i.i.i.i.i.i.i.i566 = shufflevector <8 x i32> %shuffle.i.i.i.i.i.i.i.i.i, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %28 = bitcast <16 x i32> %shuffle.i.i.i.i.i.i.i.i.i566 to <64 x i8>
  %inner_count = getelementptr inbounds i8, ptr %param, i20 8
  %29 = load i32, ptr %inner_count, align 8, !tbaa !25
  %out_sign = getelementptr inbounds i8, ptr %param, i20 54
  %30 = load i8, ptr %out_sign, align 2, !tbaa !26
  %tobool208 = icmp ne i8 %30, 0
  %shift_out = getelementptr inbounds i8, ptr %param, i20 53
  %31 = load i8, ptr %shift_out, align 1, !tbaa !27
  %conv209 = zext i8 %31 to i32
  %conv.i.i.i.i = zext i1 %tobool208 to i32
  %incC1 = getelementptr inbounds i8, ptr %param, i20 24
  %32 = load i32, ptr %incC1, align 8, !tbaa !28
  %idx.ext.i586 = trunc i32 %32 to i20
  %iterator_mat_c_incr1 = getelementptr inbounds i8, ptr %param, i20 108
  %33 = load i32, ptr %iterator_mat_c_incr1, align 4, !tbaa !29
  %iterator_mat_c_wrap0 = getelementptr inbounds i8, ptr %param, i20 104
  %34 = load i32, ptr %iterator_mat_c_wrap0, align 8, !tbaa !30
  %iterator_mat_c_incr0 = getelementptr inbounds i8, ptr %param, i20 100
  %35 = load i32, ptr %iterator_mat_c_incr0, align 4, !tbaa !31
  %36 = trunc i32 %33 to i20
  %37 = trunc i32 %35 to i20
  %38 = trunc i32 %34 to i20
  %iterator_psum_out_incr1 = getelementptr inbounds i8, ptr %param, i20 132
  %39 = load i32, ptr %iterator_psum_out_incr1, align 4, !tbaa !32
  %iterator_psum_out_wrap0 = getelementptr inbounds i8, ptr %param, i20 128
  %40 = load i32, ptr %iterator_psum_out_wrap0, align 32, !tbaa !33
  %iterator_psum_out_incr0 = getelementptr inbounds i8, ptr %param, i20 124
  %41 = load i32, ptr %iterator_psum_out_incr0, align 4, !tbaa !34
  %42 = trunc i32 %39 to i20
  %43 = trunc i32 %41 to i20
  %44 = trunc i32 %40 to i20
  %sub.i.i.i.i = sub nsw i32 0, %conv24
  %and.i.i.i.i = and i32 %conv24, %sub.i.i.i.i
  %and.i.i.i.i.fr = freeze i32 %and.i.i.i.i
  %cmpz = icmp eq i32 %and.i.i.i.i.fr, 0
  br i1 %cmpz, label %cond.end, label %cond.false

cond.false:                                       ; preds = %entry
  %45 = tail call noundef range(i32 0, 33) i32 @llvm.ctlz.i32(i32 %and.i.i.i.i.fr, i1 true)
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %entry
  %ctz = phi i32 [ 32, %entry ], [ %45, %cond.false ]
  %sub2.i.i.i.i = sub nsw i32 31, %ctz
  %46 = trunc nsw i32 %sub2.i.i.i.i to i20
  %arrayidx.i.i.i.i = getelementptr inbounds [7 x %"struct.std::__1::array.28"], ptr @_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE, i20 0, i20 %46
  %47 = load i32, ptr %arrayidx.i.i.i.i, align 4, !tbaa !35, !noalias !36
  %arrayidx.i23.i.i.i = getelementptr inbounds i8, ptr %arrayidx.i.i.i.i, i20 4
  %48 = load i32, ptr %arrayidx.i23.i.i.i, align 4, !tbaa !35, !noalias !36
  %sub.i.i.i.i394 = sub nsw i32 0, %conv24
  %and.i.i.i.i395 = and i32 %conv24, %sub.i.i.i.i394
  %and.i.i.i.i395.fr = freeze i32 %and.i.i.i.i395
  %cmpz956 = icmp eq i32 %and.i.i.i.i395.fr, 0
  br i1 %cmpz956, label %cond.end955, label %cond.false954

cond.false954:                                    ; preds = %cond.end
  %49 = tail call noundef range(i32 0, 33) i32 @llvm.ctlz.i32(i32 %and.i.i.i.i395.fr, i1 true)
  br label %cond.end955

cond.end955:                                      ; preds = %cond.false954, %cond.end
  %ctz957 = phi i32 [ 32, %cond.end ], [ %49, %cond.false954 ]
  %sub2.i.i.i.i396 = sub nsw i32 31, %ctz957
  %50 = trunc nsw i32 %sub2.i.i.i.i396 to i20
  %arrayidx.i.i.i.i397 = getelementptr inbounds [7 x %"struct.std::__1::array.28"], ptr @_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE, i20 0, i20 %50
  %51 = load i32, ptr %arrayidx.i.i.i.i397, align 4, !tbaa !35, !noalias !43
  %arrayidx.i23.i.i.i402 = getelementptr inbounds i8, ptr %arrayidx.i.i.i.i397, i20 4
  %52 = load i32, ptr %arrayidx.i23.i.i.i402, align 4, !tbaa !35, !noalias !43
  %sub.i.i.i.i620 = sub nsw i32 0, %conv24
  %and.i.i.i.i621 = and i32 %conv24, %sub.i.i.i.i620
  %and.i.i.i.i621.fr = freeze i32 %and.i.i.i.i621
  %cmpz960 = icmp eq i32 %and.i.i.i.i621.fr, 0
  br i1 %cmpz960, label %cond.end959, label %cond.false958

cond.false958:                                    ; preds = %cond.end955
  %53 = tail call noundef range(i32 0, 33) i32 @llvm.ctlz.i32(i32 %and.i.i.i.i621.fr, i1 true)
  br label %cond.end959

cond.end959:                                      ; preds = %cond.false958, %cond.end955
  %ctz961 = phi i32 [ 32, %cond.end955 ], [ %53, %cond.false958 ]
  %sub2.i.i.i.i622 = sub nsw i32 31, %ctz961
  %54 = trunc nsw i32 %sub2.i.i.i.i622 to i20
  %arrayidx.i.i.i.i623 = getelementptr inbounds [7 x %"struct.std::__1::array.28"], ptr @_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE, i20 0, i20 %54
  %55 = load i32, ptr %arrayidx.i.i.i.i623, align 4, !tbaa !35, !noalias !50
  %arrayidx.i23.i.i.i628 = getelementptr inbounds i8, ptr %arrayidx.i.i.i.i623, i20 4
  %56 = load i32, ptr %arrayidx.i23.i.i.i628, align 4, !tbaa !35, !noalias !50
  %sub.i.i.i.i655 = sub nsw i32 0, %conv24
  %and.i.i.i.i656 = and i32 %conv24, %sub.i.i.i.i655
  %and.i.i.i.i656.fr = freeze i32 %and.i.i.i.i656
  %cmpz964 = icmp eq i32 %and.i.i.i.i656.fr, 0
  br i1 %cmpz964, label %cond.end963, label %cond.false962

cond.false962:                                    ; preds = %cond.end959
  %57 = tail call noundef range(i32 0, 33) i32 @llvm.ctlz.i32(i32 %and.i.i.i.i656.fr, i1 true)
  br label %cond.end963

cond.end963:                                      ; preds = %cond.false962, %cond.end959
  %ctz965 = phi i32 [ 32, %cond.end959 ], [ %57, %cond.false962 ]
  %58 = addrspacecast ptr %p_a to ptr addrspace(5)
  %59 = addrspacecast ptr %p_b to ptr addrspace(5)
  %sub2.i.i.i.i657 = sub nsw i32 31, %ctz965
  %60 = trunc nsw i32 %sub2.i.i.i.i657 to i20
  %arrayidx.i.i.i.i658 = getelementptr inbounds [7 x %"struct.std::__1::array.28"], ptr @_ZN3aie6detail19transpose_bits_implILj8EaLj64EE13shuffle_modesE, i20 0, i20 %60
  %61 = load i32, ptr %arrayidx.i.i.i.i658, align 4, !tbaa !35, !noalias !57
  %arrayidx.i23.i.i.i663 = getelementptr inbounds i8, ptr %arrayidx.i.i.i.i658, i20 4
  %62 = load i32, ptr %arrayidx.i23.i.i.i663, align 4, !tbaa !35, !noalias !57
  %63 = add i32 %29, -1
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.cond.cleanup142
  ret void

for.body:                                         ; preds = %for.cond.cleanup142, %cond.end963
  %lsr.iv952 = phi i32 [ %2, %cond.end963 ], [ %lsr.iv.next953, %for.cond.cleanup142 ]
  %p_mat_a.0914 = phi ptr addrspace(5) [ %58, %cond.end963 ], [ %137, %for.cond.cleanup142 ]
  %p_mat_b.0912 = phi ptr addrspace(5) [ %59, %cond.end963 ], [ %136, %for.cond.cleanup142 ]
  %p_mat_c.0.in911 = phi ptr [ %p_c, %cond.end963 ], [ %147, %for.cond.cleanup142 ]
  %p_psum_in.0.in910 = phi ptr [ %p_psum, %cond.end963 ], [ %add.ptr.i481, %for.cond.cleanup142 ]
  %p_bias_in.0.in909 = phi ptr [ %p_bias, %cond.end963 ], [ %152, %for.cond.cleanup142 ]
  %iterator_mat_a_cnt0.0908 = phi i32 [ 0, %cond.end963 ], [ %159, %for.cond.cleanup142 ]
  %iterator_mat_a_cnt1.0907 = phi i32 [ 0, %cond.end963 ], [ %161, %for.cond.cleanup142 ]
  %iterator_mat_b_cnt0.0906 = phi i32 [ 0, %cond.end963 ], [ %168, %for.cond.cleanup142 ]
  %iterator_mat_b_cnt1.0905 = phi i32 [ 0, %cond.end963 ], [ %170, %for.cond.cleanup142 ]
  %iterator_mat_c_cnt0.0904 = phi i32 [ 0, %cond.end963 ], [ %146, %for.cond.cleanup142 ]
  %iterator_psum_out_cnt0.0903 = phi i32 [ 0, %cond.end963 ], [ %151, %for.cond.cleanup142 ]
  %B0.sroa.0.0902 = phi <8 x i32> [ zeroinitializer, %cond.end963 ], [ %shuffle1.i.i.i.i.i, %for.cond.cleanup142 ]
  %B1.sroa.0.0901 = phi <8 x i32> [ zeroinitializer, %cond.end963 ], [ %shuffle1.i.i.i.i.i369, %for.cond.cleanup142 ]
  %p_bias_in.0 = addrspacecast ptr %p_bias_in.0.in909 to ptr addrspace(6)
  %64 = load <16 x i16>, ptr addrspace(6) %p_bias_in.0, align 32, !tbaa !64, !noalias !65
  %65 = tail call noundef <16 x i32> @llvm.aie2ps.acc32.v16.I256.ups(<16 x i16> %64, i32 0, i32 range(i32 0, 2) 1)
  %66 = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> %65, i32 %conv2, i32 range(i32 0, 2) 1)
  %67 = bitcast <16 x i16> %66 to <8 x i32>
  %shuffle1.i.i.i.i.i = shufflevector <8 x i32> %67, <8 x i32> %B0.sroa.0.0902, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %shuffle1.i.i.i.i.i.i = shufflevector <8 x i32> %67, <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %shuffle.i.i.i.i.i368 = shufflevector <4 x i32> %shuffle1.i.i.i.i.i.i, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i369 = shufflevector <8 x i32> %shuffle.i.i.i.i.i368, <8 x i32> %B1.sroa.0.0901, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %68 = load <32 x i16>, ptr addrspace(5) %p_mat_a.0914, align 64, !tbaa !64, !noalias !72
  %69 = addrspacecast ptr addrspace(5) %p_mat_a.0914 to ptr
  %add.ptr.i = getelementptr inbounds i8, ptr %69, i20 64
  %add.ptr.ascast.i = addrspacecast ptr %add.ptr.i to ptr addrspace(5)
  %70 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i, align 64, !tbaa !64, !noalias !79
  %71 = trunc i32 %iterator_mat_a_cnt0.0908 to i20
  %72 = trunc i32 %iterator_mat_a_cnt1.0907 to i20
  %73 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i, i20 %9, i20 %10, i20 %11, i20 %12, i20 %71, i20 %13, i20 %72)
  %74 = extractvalue { ptr, i20, i20 } %73, 1
  %75 = zext i20 %74 to i32
  %76 = extractvalue { ptr, i20, i20 } %73, 2
  %77 = zext i20 %76 to i32
  %78 = load <16 x i32>, ptr addrspace(5) %p_mat_b.0912, align 64, !tbaa !64, !noalias !86
  %79 = addrspacecast ptr addrspace(5) %p_mat_b.0912 to ptr
  %add.ptr.i372 = getelementptr inbounds i8, ptr %79, i20 %idx.ext.i
  %add.ptr.ascast.i373 = addrspacecast ptr %add.ptr.i372 to ptr addrspace(5)
  %80 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i373, align 64, !tbaa !64, !noalias !93
  %81 = trunc i32 %iterator_mat_b_cnt0.0906 to i20
  %82 = trunc i32 %iterator_mat_b_cnt1.0905 to i20
  %83 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i372, i20 %20, i20 %21, i20 %22, i20 %23, i20 %81, i20 %24, i20 %82)
  %84 = extractvalue { ptr, i20, i20 } %83, 1
  %85 = zext i20 %84 to i32
  %86 = extractvalue { ptr, i20, i20 } %83, 2
  %87 = zext i20 %86 to i32
  %88 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %78, <16 x i32> poison, i32 %47)
  %89 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %88, <16 x i32> poison, i32 %48)
  %90 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %80, <16 x i32> poison, i32 %51)
  %91 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %90, <16 x i32> poison, i32 %52)
  %92 = load <8 x i64>, ptr %p_psum_in.0.in910, align 64, !tbaa !64, !noalias !100
  %add.ptr.i411 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 64
  %93 = load <8 x i64>, ptr %add.ptr.i411, align 64, !tbaa !64, !noalias !107
  %add.ptr.i414 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 128
  %shuffle6.i.i.i.i.i = shufflevector <8 x i64> %92, <8 x i64> %93, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %94 = load <8 x i64>, ptr %add.ptr.i414, align 64, !tbaa !64, !noalias !114
  %add.ptr.i418 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 192
  %shuffle1.i.i.i.i.i421 = shufflevector <8 x i64> %94, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i.i.i.i = shufflevector <32 x i64> %shuffle6.i.i.i.i.i, <32 x i64> %shuffle1.i.i.i.i.i421, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %95 = load <8 x i64>, ptr %add.ptr.i418, align 64, !tbaa !64, !noalias !121
  %add.ptr.i422 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 256
  %shuffle1.i.i.i.i.i425 = shufflevector <8 x i64> %95, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i.i.i.i = shufflevector <32 x i64> %shuffle11.i.i.i.i.i, <32 x i64> %shuffle1.i.i.i.i.i425, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %96 = load <8 x i64>, ptr %add.ptr.i422, align 64, !tbaa !64, !noalias !128
  %add.ptr.i426 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 320
  %97 = load <8 x i64>, ptr %add.ptr.i426, align 64, !tbaa !64, !noalias !135
  %add.ptr.i431 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 384
  %shuffle6.i.i.i.i.i435 = shufflevector <8 x i64> %96, <8 x i64> %97, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %98 = load <8 x i64>, ptr %add.ptr.i431, align 64, !tbaa !64, !noalias !142
  %add.ptr.i436 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 448
  %shuffle1.i.i.i.i.i439 = shufflevector <8 x i64> %98, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i.i.i.i440 = shufflevector <32 x i64> %shuffle6.i.i.i.i.i435, <32 x i64> %shuffle1.i.i.i.i.i439, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %99 = load <8 x i64>, ptr %add.ptr.i436, align 64, !tbaa !64, !noalias !149
  %add.ptr.i441 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 512
  %shuffle1.i.i.i.i.i444 = shufflevector <8 x i64> %99, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i.i.i.i445 = shufflevector <32 x i64> %shuffle11.i.i.i.i.i440, <32 x i64> %shuffle1.i.i.i.i.i444, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %100 = load <8 x i64>, ptr %add.ptr.i441, align 64, !tbaa !64, !noalias !156
  %add.ptr.i446 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 576
  %101 = load <8 x i64>, ptr %add.ptr.i446, align 64, !tbaa !64, !noalias !163
  %add.ptr.i451 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 640
  %shuffle6.i.i.i.i.i455 = shufflevector <8 x i64> %100, <8 x i64> %101, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %102 = load <8 x i64>, ptr %add.ptr.i451, align 64, !tbaa !64, !noalias !170
  %add.ptr.i456 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 704
  %shuffle1.i.i.i.i.i459 = shufflevector <8 x i64> %102, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i.i.i.i460 = shufflevector <32 x i64> %shuffle6.i.i.i.i.i455, <32 x i64> %shuffle1.i.i.i.i.i459, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %103 = load <8 x i64>, ptr %add.ptr.i456, align 64, !tbaa !64, !noalias !177
  %add.ptr.i461 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 768
  %shuffle1.i.i.i.i.i464 = shufflevector <8 x i64> %103, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i.i.i.i465 = shufflevector <32 x i64> %shuffle11.i.i.i.i.i460, <32 x i64> %shuffle1.i.i.i.i.i464, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %104 = load <8 x i64>, ptr %add.ptr.i461, align 64, !tbaa !64, !noalias !184
  %add.ptr.i466 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 832
  %105 = load <8 x i64>, ptr %add.ptr.i466, align 64, !tbaa !64, !noalias !191
  %add.ptr.i471 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 896
  %shuffle6.i.i.i.i.i475 = shufflevector <8 x i64> %104, <8 x i64> %105, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %106 = load <8 x i64>, ptr %add.ptr.i471, align 64, !tbaa !64, !noalias !198
  %add.ptr.i476 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 960
  %shuffle1.i.i.i.i.i479 = shufflevector <8 x i64> %106, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle11.i.i.i.i.i480 = shufflevector <32 x i64> %shuffle6.i.i.i.i.i475, <32 x i64> %shuffle1.i.i.i.i.i479, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %107 = load <8 x i64>, ptr %add.ptr.i476, align 64, !tbaa !64, !noalias !205
  %shuffle1.i.i.i.i.i484 = shufflevector <8 x i64> %107, <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle12.i.i.i.i.i485 = shufflevector <32 x i64> %shuffle11.i.i.i.i.i480, <32 x i64> %shuffle1.i.i.i.i.i484, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  %108 = bitcast <32 x i64> %shuffle12.i.i.i.i.i to <64 x i32>
  %109 = bitcast <32 x i64> %shuffle12.i.i.i.i.i445 to <64 x i32>
  %110 = bitcast <32 x i64> %shuffle12.i.i.i.i.i465 to <64 x i32>
  %111 = bitcast <32 x i64> %shuffle12.i.i.i.i.i485 to <64 x i32>
  %112 = bitcast <16 x i32> %89 to <32 x i16>
  %113 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %68, <32 x i16> %112, <64 x i32> %108, i32 %or25.i.i.i.i)
  %114 = bitcast <64 x i32> %113 to <32 x i64>
  %115 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %70, <32 x i16> %112, <64 x i32> %109, i32 %or25.i.i.i.i)
  %116 = bitcast <64 x i32> %115 to <32 x i64>
  %117 = bitcast <16 x i32> %91 to <32 x i16>
  %118 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %68, <32 x i16> %117, <64 x i32> %110, i32 %or25.i.i.i.i)
  %119 = bitcast <64 x i32> %118 to <32 x i64>
  %120 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %70, <32 x i16> %117, <64 x i32> %111, i32 %or25.i.i.i.i)
  %121 = bitcast <64 x i32> %120 to <32 x i64>
  %shuffle.i.i.i.i.i9.i.i.i.i = shufflevector <8 x i32> %shuffle1.i.i.i.i.i, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %122 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i to <64 x i8>
  %123 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %28, <64 x i8> %122, i32 776)
  %124 = bitcast <64 x i32> %123 to <32 x i64>
  %125 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %114, <32 x i64> %124, i32 0)
  %126 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %116, <32 x i64> %124, i32 0)
  %shuffle.i.i.i.i.i9.i.i.i.i573 = shufflevector <8 x i32> %shuffle1.i.i.i.i.i369, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %127 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i573 to <64 x i8>
  %128 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %28, <64 x i8> %127, i32 776)
  %129 = bitcast <64 x i32> %128 to <32 x i64>
  %130 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %119, <32 x i64> %129, i32 0)
  %131 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %121, <32 x i64> %129, i32 0)
  %132 = bitcast <32 x i64> %125 to <64 x i32>
  %133 = bitcast <32 x i64> %126 to <64 x i32>
  %134 = bitcast <32 x i64> %130 to <64 x i32>
  %135 = bitcast <32 x i64> %131 to <64 x i32>
  %p_mat_a.1.in883 = extractvalue { ptr, i20, i20 } %73, 0
  %p_mat_a.1884 = addrspacecast ptr %p_mat_a.1.in883 to ptr addrspace(5)
  %p_mat_b.1.in885 = extractvalue { ptr, i20, i20 } %83, 0
  %p_mat_b.1886 = addrspacecast ptr %p_mat_b.1.in885 to ptr addrspace(5)
  call void @llvm.set.loop.iterations.i32(i32 %63)
  br label %for.body143

for.cond.cleanup142:                              ; preds = %for.body143
  %136 = addrspacecast ptr %p_mat_b.1.in to ptr addrspace(5)
  %137 = addrspacecast ptr %p_mat_a.1.in to ptr addrspace(5)
  %138 = addrspacecast ptr %p_mat_c.0.in911 to ptr addrspace(6)
  %add.ptr.i481 = getelementptr inbounds i8, ptr %p_psum_in.0.in910, i20 1024
  %139 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %176, i32 %conv209, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %139, ptr addrspace(6) %138, align 64, !tbaa !64
  %add.ptr.i583 = getelementptr inbounds i8, ptr %p_mat_c.0.in911, i20 64
  %add.ptr.ascast.i584 = addrspacecast ptr %add.ptr.i583 to ptr addrspace(6)
  %140 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %177, i32 %conv209, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %140, ptr addrspace(6) %add.ptr.ascast.i584, align 64, !tbaa !64
  %add.ptr.i587 = getelementptr inbounds i8, ptr %add.ptr.i583, i20 %idx.ext.i586
  %add.ptr.ascast.i588 = addrspacecast ptr %add.ptr.i587 to ptr addrspace(6)
  %141 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %179, i32 %conv209, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %141, ptr addrspace(6) %add.ptr.ascast.i588, align 64, !tbaa !64
  %add.ptr.i590 = getelementptr inbounds i8, ptr %add.ptr.i587, i20 64
  %add.ptr.ascast.i591 = addrspacecast ptr %add.ptr.i590 to ptr addrspace(6)
  %142 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %180, i32 %conv209, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %142, ptr addrspace(6) %add.ptr.ascast.i591, align 64, !tbaa !64
  %143 = trunc i32 %iterator_mat_c_cnt0.0904 to i20
  %144 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr nonnull %add.ptr.i590, i20 %36, i20 %37, i20 %38, i20 %143)
  %145 = extractvalue { ptr, i20 } %144, 1
  %146 = zext i20 %145 to i32
  %147 = extractvalue { ptr, i20 } %144, 0
  %148 = trunc i32 %iterator_psum_out_cnt0.0903 to i20
  %149 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr %p_bias_in.0.in909, i20 %42, i20 %43, i20 %44, i20 %148)
  %150 = extractvalue { ptr, i20 } %149, 1
  %151 = zext i20 %150 to i32
  %152 = extractvalue { ptr, i20 } %149, 0
  %lsr.iv.next953 = add nsw i32 %lsr.iv952, -1
  %exitcond923.not = icmp eq i32 %lsr.iv.next953, 0
  br i1 %exitcond923.not, label %for.cond.cleanup, label %for.body, !llvm.loop !212

for.body143:                                      ; preds = %for.body143, %for.body
  %p_mat_b.1899 = phi ptr addrspace(5) [ %p_mat_b.1886, %for.body ], [ %p_mat_b.1, %for.body143 ]
  %p_mat_b.1.in898 = phi ptr [ %p_mat_b.1.in885, %for.body ], [ %p_mat_b.1.in, %for.body143 ]
  %p_mat_a.1897 = phi ptr addrspace(5) [ %p_mat_a.1884, %for.body ], [ %p_mat_a.1, %for.body143 ]
  %p_mat_a.1.in896 = phi ptr [ %p_mat_a.1.in883, %for.body ], [ %p_mat_a.1.in, %for.body143 ]
  %iterator_mat_a_cnt0.1894 = phi i32 [ %75, %for.body ], [ %159, %for.body143 ]
  %iterator_mat_a_cnt1.1893 = phi i32 [ %77, %for.body ], [ %161, %for.body143 ]
  %iterator_mat_b_cnt0.1892 = phi i32 [ %85, %for.body ], [ %168, %for.body143 ]
  %iterator_mat_b_cnt1.1891 = phi i32 [ %87, %for.body ], [ %170, %for.body143 ]
  %Ci3.sroa.0.0890 = phi <64 x i32> [ %135, %for.body ], [ %180, %for.body143 ]
  %Ci2.sroa.0.0889 = phi <64 x i32> [ %134, %for.body ], [ %179, %for.body143 ]
  %Ci1.sroa.0.0888 = phi <64 x i32> [ %133, %for.body ], [ %177, %for.body143 ]
  %Ci0.sroa.0.0887 = phi <64 x i32> [ %132, %for.body ], [ %176, %for.body143 ]
  %153 = load <32 x i16>, ptr addrspace(5) %p_mat_a.1897, align 64, !tbaa !64, !noalias !216
  %add.ptr.i593 = getelementptr inbounds i8, ptr %p_mat_a.1.in896, i20 64
  %add.ptr.ascast.i594 = addrspacecast ptr %add.ptr.i593 to ptr addrspace(5)
  %154 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i594, align 64, !tbaa !64, !noalias !223
  %155 = trunc i32 %iterator_mat_a_cnt0.1894 to i20
  %156 = trunc i32 %iterator_mat_a_cnt1.1893 to i20
  %157 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i593, i20 %9, i20 %10, i20 %11, i20 %12, i20 %155, i20 %13, i20 %156)
  %158 = extractvalue { ptr, i20, i20 } %157, 1
  %159 = zext i20 %158 to i32
  %160 = extractvalue { ptr, i20, i20 } %157, 2
  %161 = zext i20 %160 to i32
  %162 = load <16 x i32>, ptr addrspace(5) %p_mat_b.1899, align 64, !tbaa !64, !noalias !230
  %add.ptr.i598 = getelementptr inbounds i8, ptr %p_mat_b.1.in898, i20 %idx.ext.i
  %add.ptr.ascast.i599 = addrspacecast ptr %add.ptr.i598 to ptr addrspace(5)
  %163 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i599, align 64, !tbaa !64, !noalias !237
  %164 = trunc i32 %iterator_mat_b_cnt0.1892 to i20
  %165 = trunc i32 %iterator_mat_b_cnt1.1891 to i20
  %166 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i598, i20 %20, i20 %21, i20 %22, i20 %23, i20 %164, i20 %24, i20 %165)
  %167 = extractvalue { ptr, i20, i20 } %166, 1
  %168 = zext i20 %167 to i32
  %169 = extractvalue { ptr, i20, i20 } %166, 2
  %170 = zext i20 %169 to i32
  %171 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %162, <16 x i32> poison, i32 %55)
  %172 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %171, <16 x i32> poison, i32 %56)
  %173 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %163, <16 x i32> poison, i32 %61)
  %174 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %173, <16 x i32> poison, i32 %62)
  %175 = bitcast <16 x i32> %172 to <32 x i16>
  %176 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %153, <32 x i16> %175, <64 x i32> %Ci0.sroa.0.0887, i32 %or22.i.i.i.i)
  %177 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %154, <32 x i16> %175, <64 x i32> %Ci1.sroa.0.0888, i32 %or22.i.i.i.i)
  %178 = bitcast <16 x i32> %174 to <32 x i16>
  %179 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %153, <32 x i16> %178, <64 x i32> %Ci2.sroa.0.0889, i32 %or22.i.i.i.i)
  %180 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %154, <32 x i16> %178, <64 x i32> %Ci3.sroa.0.0890, i32 %or22.i.i.i.i)
  %p_mat_a.1.in = extractvalue { ptr, i20, i20 } %157, 0
  %p_mat_a.1 = addrspacecast ptr %p_mat_a.1.in to ptr addrspace(5)
  %p_mat_b.1.in = extractvalue { ptr, i20, i20 } %166, 0
  %p_mat_b.1 = addrspacecast ptr %p_mat_b.1.in to ptr addrspace(5)
  %181 = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %181, label %for.body143, label %for.cond.cleanup142, !llvm.loop !244
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #2 = { nocallback noduplicate nofree nosync nounwind willreturn }
attributes #3 = { mustprogress noinline "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #4 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 21.0.0git (https://gitenterprise.xilinx.com/FaaSApps/llvm-aie af09d5b3af2f0d58db9c9c22306c412336cf29b1)"}
!4 = !{!5, !6, i64 48}
!5 = !{!"_ZTS20gemm_internal_params", !6, i64 0, !6, i64 1, !6, i64 2, !6, i64 3, !8, i64 4, !8, i64 8, !8, i64 12, !8, i64 16, !8, i64 20, !8, i64 24, !8, i64 28, !8, i64 32, !6, i64 36, !6, i64 37, !6, i64 38, !6, i64 39, !6, i64 40, !6, i64 41, !8, i64 44, !6, i64 48, !6, i64 49, !6, i64 50, !6, i64 51, !6, i64 52, !6, i64 53, !6, i64 54, !6, i64 55, !6, i64 56, !8, i64 60, !8, i64 64, !8, i64 68, !8, i64 72, !8, i64 76, !8, i64 80, !8, i64 84, !8, i64 88, !8, i64 92, !8, i64 96, !8, i64 100, !8, i64 104, !8, i64 108, !8, i64 112, !8, i64 116, !8, i64 120, !8, i64 124, !8, i64 128, !8, i64 132}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C++ TBAA"}
!8 = !{!"int", !6, i64 0}
!9 = !{!5, !8, i64 4}
!10 = !{!5, !6, i64 52}
!11 = !{!5, !8, i64 76}
!12 = !{!5, !8, i64 68}
!13 = !{!5, !8, i64 60}
!14 = !{!5, !8, i64 72}
!15 = !{!5, !8, i64 64}
!16 = !{!5, !8, i64 16}
!17 = !{!5, !8, i64 96}
!18 = !{!5, !8, i64 88}
!19 = !{!5, !8, i64 80}
!20 = !{!5, !8, i64 92}
!21 = !{!5, !8, i64 84}
!22 = !{!5, !6, i64 37}
!23 = !{!5, !6, i64 40}
!24 = !{!5, !6, i64 55}
!25 = !{!5, !8, i64 8}
!26 = !{!5, !6, i64 54}
!27 = !{!5, !6, i64 53}
!28 = !{!5, !8, i64 24}
!29 = !{!5, !8, i64 108}
!30 = !{!5, !8, i64 104}
!31 = !{!5, !8, i64 100}
!32 = !{!5, !8, i64 132}
!33 = !{!5, !8, i64 128}
!34 = !{!5, !8, i64 124}
!35 = !{!8, !8, i64 0}
!36 = !{!37, !39, !41}
!37 = distinct !{!37, !38, !"A: %agg.result"}
!38 = distinct !{!38, !"A"}
!39 = distinct !{!39, !40, !"B: %agg.result"}
!40 = distinct !{!40, !"B"}
!41 = distinct !{!41, !42, !"C: %agg.result"}
!42 = distinct !{!42, !"C"}
!43 = !{!44, !46, !48}
!44 = distinct !{!44, !45, !"A: %agg.result"}
!45 = distinct !{!45, !"A"}
!46 = distinct !{!46, !47, !"B: %agg.result"}
!47 = distinct !{!47, !"B"}
!48 = distinct !{!48, !49, !"C: %agg.result"}
!49 = distinct !{!49, !"C"}
!50 = !{!51, !53, !55}
!51 = distinct !{!51, !52, !"A: %agg.result"}
!52 = distinct !{!52, !"A"}
!53 = distinct !{!53, !54, !"B: %agg.result"}
!54 = distinct !{!54, !"B"}
!55 = distinct !{!55, !56, !"C: %agg.result"}
!56 = distinct !{!56, !"C"}
!57 = !{!58, !60, !62}
!58 = distinct !{!58, !59, !"A: %agg.result"}
!59 = distinct !{!59, !"A"}
!60 = distinct !{!60, !61, !"B: %agg.result"}
!61 = distinct !{!61, !"B"}
!62 = distinct !{!62, !63, !"C: %agg.result"}
!63 = distinct !{!63, !"C"}
!64 = !{!6, !6, i64 0}
!65 = !{!66, !68, !70}
!66 = distinct !{!66, !67, !"D: %agg.result"}
!67 = distinct !{!67, !"D"}
!68 = distinct !{!68, !69, !"E: %agg.result"}
!69 = distinct !{!69, !"E"}
!70 = distinct !{!70, !71, !"F: %agg.result"}
!71 = distinct !{!71, !"F"}
!72 = !{!73, !75, !77}
!73 = distinct !{!73, !74, !"A: %agg.result"}
!74 = distinct !{!74, !"A"}
!75 = distinct !{!75, !76, !"B: %agg.result"}
!76 = distinct !{!76, !"B"}
!77 = distinct !{!77, !78, !"C: %agg.result"}
!78 = distinct !{!78, !"C"}
!79 = !{!80, !82, !84}
!80 = distinct !{!80, !81, !"A: %agg.result"}
!81 = distinct !{!81, !"A"}
!82 = distinct !{!82, !83, !"B: %agg.result"}
!83 = distinct !{!83, !"B"}
!84 = distinct !{!84, !85, !"C: %agg.result"}
!85 = distinct !{!85, !"C"}
!86 = !{!87, !89, !91}
!87 = distinct !{!87, !88, !"A: %agg.result"}
!88 = distinct !{!88, !"A"}
!89 = distinct !{!89, !90, !"B: %agg.result"}
!90 = distinct !{!90, !"B"}
!91 = distinct !{!91, !92, !"C: %agg.result"}
!92 = distinct !{!92, !"C"}
!93 = !{!94, !96, !98}
!94 = distinct !{!94, !95, !"A: %agg.result"}
!95 = distinct !{!95, !"A"}
!96 = distinct !{!96, !97, !"B: %agg.result"}
!97 = distinct !{!97, !"B"}
!98 = distinct !{!98, !99, !"C: %agg.result"}
!99 = distinct !{!99, !"C"}
!100 = !{!101, !103, !105}
!101 = distinct !{!101, !102, !"D: %agg.result"}
!102 = distinct !{!102, !"D"}
!103 = distinct !{!103, !104, !"E: %agg.result"}
!104 = distinct !{!104, !"E"}
!105 = distinct !{!105, !106, !"F: %agg.result"}
!106 = distinct !{!106, !"F"}
!107 = !{!108, !110, !112}
!108 = distinct !{!108, !109, !"D: %agg.result"}
!109 = distinct !{!109, !"D"}
!110 = distinct !{!110, !111, !"E: %agg.result"}
!111 = distinct !{!111, !"E"}
!112 = distinct !{!112, !113, !"F: %agg.result"}
!113 = distinct !{!113, !"F"}
!114 = !{!115, !117, !119}
!115 = distinct !{!115, !116, !"D: %agg.result"}
!116 = distinct !{!116, !"D"}
!117 = distinct !{!117, !118, !"E: %agg.result"}
!118 = distinct !{!118, !"E"}
!119 = distinct !{!119, !120, !"F: %agg.result"}
!120 = distinct !{!120, !"F"}
!121 = !{!122, !124, !126}
!122 = distinct !{!122, !123, !"D: %agg.result"}
!123 = distinct !{!123, !"D"}
!124 = distinct !{!124, !125, !"E: %agg.result"}
!125 = distinct !{!125, !"E"}
!126 = distinct !{!126, !127, !"F: %agg.result"}
!127 = distinct !{!127, !"F"}
!128 = !{!129, !131, !133}
!129 = distinct !{!129, !130, !"D: %agg.result"}
!130 = distinct !{!130, !"D"}
!131 = distinct !{!131, !132, !"E: %agg.result"}
!132 = distinct !{!132, !"E"}
!133 = distinct !{!133, !134, !"F: %agg.result"}
!134 = distinct !{!134, !"F"}
!135 = !{!136, !138, !140}
!136 = distinct !{!136, !137, !"D: %agg.result"}
!137 = distinct !{!137, !"D"}
!138 = distinct !{!138, !139, !"E: %agg.result"}
!139 = distinct !{!139, !"E"}
!140 = distinct !{!140, !141, !"F: %agg.result"}
!141 = distinct !{!141, !"F"}
!142 = !{!143, !145, !147}
!143 = distinct !{!143, !144, !"D: %agg.result"}
!144 = distinct !{!144, !"D"}
!145 = distinct !{!145, !146, !"E: %agg.result"}
!146 = distinct !{!146, !"E"}
!147 = distinct !{!147, !148, !"F: %agg.result"}
!148 = distinct !{!148, !"F"}
!149 = !{!150, !152, !154}
!150 = distinct !{!150, !151, !"D: %agg.result"}
!151 = distinct !{!151, !"D"}
!152 = distinct !{!152, !153, !"E: %agg.result"}
!153 = distinct !{!153, !"E"}
!154 = distinct !{!154, !155, !"F: %agg.result"}
!155 = distinct !{!155, !"F"}
!156 = !{!157, !159, !161}
!157 = distinct !{!157, !158, !"D: %agg.result"}
!158 = distinct !{!158, !"D"}
!159 = distinct !{!159, !160, !"E: %agg.result"}
!160 = distinct !{!160, !"E"}
!161 = distinct !{!161, !162, !"F: %agg.result"}
!162 = distinct !{!162, !"F"}
!163 = !{!164, !166, !168}
!164 = distinct !{!164, !165, !"D: %agg.result"}
!165 = distinct !{!165, !"D"}
!166 = distinct !{!166, !167, !"E: %agg.result"}
!167 = distinct !{!167, !"E"}
!168 = distinct !{!168, !169, !"F: %agg.result"}
!169 = distinct !{!169, !"F"}
!170 = !{!171, !173, !175}
!171 = distinct !{!171, !172, !"D: %agg.result"}
!172 = distinct !{!172, !"D"}
!173 = distinct !{!173, !174, !"E: %agg.result"}
!174 = distinct !{!174, !"E"}
!175 = distinct !{!175, !176, !"F: %agg.result"}
!176 = distinct !{!176, !"F"}
!177 = !{!178, !180, !182}
!178 = distinct !{!178, !179, !"D: %agg.result"}
!179 = distinct !{!179, !"D"}
!180 = distinct !{!180, !181, !"E: %agg.result"}
!181 = distinct !{!181, !"E"}
!182 = distinct !{!182, !183, !"F: %agg.result"}
!183 = distinct !{!183, !"F"}
!184 = !{!185, !187, !189}
!185 = distinct !{!185, !186, !"D: %agg.result"}
!186 = distinct !{!186, !"D"}
!187 = distinct !{!187, !188, !"E: %agg.result"}
!188 = distinct !{!188, !"E"}
!189 = distinct !{!189, !190, !"F: %agg.result"}
!190 = distinct !{!190, !"F"}
!191 = !{!192, !194, !196}
!192 = distinct !{!192, !193, !"D: %agg.result"}
!193 = distinct !{!193, !"D"}
!194 = distinct !{!194, !195, !"E: %agg.result"}
!195 = distinct !{!195, !"E"}
!196 = distinct !{!196, !197, !"F: %agg.result"}
!197 = distinct !{!197, !"F"}
!198 = !{!199, !201, !203}
!199 = distinct !{!199, !200, !"D: %agg.result"}
!200 = distinct !{!200, !"D"}
!201 = distinct !{!201, !202, !"E: %agg.result"}
!202 = distinct !{!202, !"E"}
!203 = distinct !{!203, !204, !"F: %agg.result"}
!204 = distinct !{!204, !"F"}
!205 = !{!206, !208, !210}
!206 = distinct !{!206, !207, !"D: %agg.result"}
!207 = distinct !{!207, !"D"}
!208 = distinct !{!208, !209, !"E: %agg.result"}
!209 = distinct !{!209, !"E"}
!210 = distinct !{!210, !211, !"F: %agg.result"}
!211 = distinct !{!211, !"F"}
!212 = distinct !{!212, !213, !214, !215}
!213 = !{!"llvm.loop.mustprogress"}
!214 = !{!"llvm.loop.itercount.range", i64 2}
!215 = !{!"llvm.loop.hint.aie-enable-outer-loop-pipelining", i64 1}
!216 = !{!217, !219, !221}
!217 = distinct !{!217, !218, !"A: %agg.result"}
!218 = distinct !{!218, !"A"}
!219 = distinct !{!219, !220, !"B: %agg.result"}
!220 = distinct !{!220, !"B"}
!221 = distinct !{!221, !222, !"C: %agg.result"}
!222 = distinct !{!222, !"C"}
!223 = !{!224, !226, !228}
!224 = distinct !{!224, !225, !"A: %agg.result"}
!225 = distinct !{!225, !"A"}
!226 = distinct !{!226, !227, !"B: %agg.result"}
!227 = distinct !{!227, !"B"}
!228 = distinct !{!228, !229, !"C: %agg.result"}
!229 = distinct !{!229, !"C"}
!230 = !{!231, !233, !235}
!231 = distinct !{!231, !232, !"A: %agg.result"}
!232 = distinct !{!232, !"A"}
!233 = distinct !{!233, !234, !"B: %agg.result"}
!234 = distinct !{!234, !"B"}
!235 = distinct !{!235, !236, !"C: %agg.result"}
!236 = distinct !{!236, !"C"}
!237 = !{!238, !240, !242}
!238 = distinct !{!238, !239, !"A: %agg.result"}
!239 = distinct !{!239, !"A"}
!240 = distinct !{!240, !241, !"B: %agg.result"}
!241 = distinct !{!241, !"B"}
!242 = distinct !{!242, !243, !"C: %agg.result"}
!243 = distinct !{!243, !"C"}
!244 = distinct !{!244, !213, !245}
!245 = !{!"llvm.loop.itercount.range", i64 4}
