; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2ps %s -o - | FileCheck %s

; Test metadata related to command line option (relax mem deps).

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { ptr, i20 } @llvm.aie2ps.add.2d(ptr, i20, i20, i20, i20) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32>, <16 x i32>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64>, <32 x i64>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16>, i32, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16>, <32 x i16>, <64 x i32>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8>, <64 x i8>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32>, i32, i32) #1

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare void @llvm.set.loop.iterations.i32(i32) #2

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare i1 @llvm.loop.decrement.i32(i32) #2

; Function Attrs: mustprogress noinline
define dso_local void @gemm(i32 %0, ptr addrspace(5) %1, ptr addrspace(5) %2, ptr %p_psum, ptr %p_c, ptr %p_bias, i20 %3, i20 %4, i20 %5, i20 %6, i20 %7, i20 %idx.ext.i, i20 %8, i20 %9, i20 %10, i20 %11, i20 %12, i32 %13, i32 %14, i32 %15, i32 %16, i32 %or23.i.i.i.i, <64 x i8> %17, i32 %18, i32 %19, i32 %20, i32 %21, i32 %22, i32 %or22.i.i.i.i, i32 %conv166, i32 %conv.i.i.i.i, i20 %idx.ext.i478, i20 %23, i20 %24, i20 %25, i20 %26, i20 %27, i20 %28) #3 {
; CHECK-LABEL: gemm:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    paddxm [sp], #64; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    st p6, [sp, #-64]; nopx // 4-byte Folded Spill
; CHECK-NEXT:    mov p6, sp
; CHECK-NEXT:    st p7, [sp, #-60] // 4-byte Folded Spill
; CHECK-NEXT:    mova m0, #-68; mov p7, p2
; CHECK-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p7], #64; paddb [p6], m0
; CHECK-NEXT:    lda dj0, [p6], #-4
; CHECK-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p7], #64
; CHECK-NEXT:    lda dj4, [p6], #-4
; CHECK-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p7], #64; movx r22, #0
; CHECK-NEXT:    lda dn0, [p6], #-4; mov s0, r22
; CHECK-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p7], #64; movx crupsmode, #0
; CHECK-NEXT:    lda dn4, [p6], #-4
; CHECK-NEXT:    lda m4, [p6], #-4
; CHECK-NEXT:    lda m1, [p6], #-4
; CHECK-NEXT:    lda dj1, [p6], #-4
; CHECK-NEXT:    lda dj5, [p6], #-4
; CHECK-NEXT:    lda dn1, [p6], #-4
; CHECK-NEXT:    lda dn5, [p6], #-4
; CHECK-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p7], #64
; CHECK-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p7], #64; mov dc0, #0
; CHECK-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p7, #64]; vldb.128 wl2, [p4, #0]; movxm ls, #.LBB0_2
; CHECK-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p7, #0]; vldb x10, [p1], m4; movxm le, #.L_LEnd1; movs m2, p5
; CHECK-NEXT:    lda r16, [p6], #-4; vldb x6, [p0], #64; movs dc2, dc0; mov dc6, dc0
; CHECK-NEXT:    lda r18, [p6], #-4; vldb.128 wl1, [p4, #16]; movs dc1, dc0; mov dc5, dc0
; CHECK-NEXT:    lda r20, [p6], #-4; vldb.3d x3, [p1], d1; movs dj2, dj0; mov dn2, dn0
; CHECK-NEXT:    lda r8, [p6], #-4; movs dj6, dj4; mov dn6, dn4
; CHECK-NEXT:    lda r17, [p6], #-4; vldb.3d x8, [p0], d2; movx r22, #15; vbcst.32 x4, r22
; CHECK-NEXT:    lda r19, [p6], #-4; or r23, r10, r10; vsel.32 x2, x4, x2, r22
; CHECK-NEXT:    lda m2, [p6], #-4; movx r10, #776; vshuffle x10, x10, x0, r1
; CHECK-NEXT:    lda m3, [p6], #-4; or r24, r12, r12; vshuffle x10, x10, x0, r2; vmul dm4, x0, x2, r10
; CHECK-NEXT:    or r12, r5, r5; vsel.32 x4, x4, x1, r22
; CHECK-NEXT:    lda dj3, [p6], #-4; or r21, r8, r8; vshuffle x1, x3, x0, r3; vaddmac dm3, dm3, dm4, x6, x10, r12
; CHECK-NEXT:    lda dn3, [p6], #-4; movs dc3, dc0; vshuffle x10, x1, x0, r4; vmul dm4, x0, x4, r10
; CHECK-NEXT:    lda m7, [p6], #-4; movs dc7, dc0; mov m5, #512; vaddmac dm2, dm2, dm4, x8, x10, r12
; CHECK-NEXT:    lda dj7, [p6, #0]; nopb ; movs dc0, dc2; add r0, r0, #-1; mov s1, r17; vaddmac dm1, dm1, dm4, x6, x10, r12
; CHECK-NEXT:    lda dn7, [p6, #-4]; nopb ; movs dc4, dc6; movx crsrsmode, #0; mov srssign0, r19; vaddmac dm0, dm0, dm4, x8, x10, r12
; CHECK-NEXT:  .LBB0_1: // %for.body
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_2 Depth 2
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; nopxm ; nopv
; CHECK-NEXT:    vlda.3d x7, [p1], d1
; CHECK-NEXT:    vldb x5, [p0], #64
; CHECK-NEXT:    vlda.3d x3, [p0], d0
; CHECK-NEXT:    vldb x9, [p1], m4; movs m0, p5
; CHECK-NEXT:    vlda.3d x7, [p1], d1
; CHECK-NEXT:    vldb x5, [p0], #64
; CHECK-NEXT:    vlda.3d x3, [p0], d0; vshuffle x1, x9, x0, r7
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; add.nc lc, r6, #-3; vshuffle x10, x1, x0, r16; nopv
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; nopv
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  .LBB0_2: // %for.body100
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; vldb x9, [p1], m4; movs m0, p5; nopx ; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.3d x7, [p1], d1; nopb ; nops ; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    nopa ; vldb x5, [p0], #64; nops ; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:  .L_LEnd1:
; CHECK-NEXT:    vlda.3d x3, [p0], d0; nopb ; nops ; nopx ; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:  // %bb.3: // %for.cond.cleanup99
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    padda [p2], m5; paddb.2d [p4], d7; movs m0, p5; add r0, r0, #-1; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    nopa ; vldb x8, [p0], #64; movs p6, p2; nopx ; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vldb x10, [p1], m4; nopx ; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:    vldb.3d x5, [p1], d1; vshuffle x1, x9, x0, r7; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    vlda.3d x1, [p0], d0; vldb.128 wl6, [p4, #0]; vshuffle x10, x1, x0, r16; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.ups.2x cml3, s0, upssign1, [p6], #64; vldb.128 wl3, [p4, #16]; vshuffle x8, x7, x0, r18; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vlda.ups.2x cmh3, s0, upssign1, [p6], #64; vshuffle x6, x8, x0, r20; vmac dm3, dm3, x5, x10, r8
; CHECK-NEXT:    vlda.ups.2x cml2, s0, upssign1, [p6], #64; vmac dm2, dm2, x3, x10, r8
; CHECK-NEXT:    vlda.ups.2x cmh2, s0, upssign1, [p6], #64; vmac dm1, dm1, x5, x6, r8
; CHECK-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p6], #64; vmac dm0, dm0, x3, x6, r8
; CHECK-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p6], #64
; CHECK-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p6, #64]; vsel.32 x2, x2, x6, r22
; CHECK-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p6, #0]; vst.srs.4x dm3, s1, srssign0, [p3], #64; vshuffle x6, x10, x0, r1
; CHECK-NEXT:    vst.srs.4x dm2, s1, srssign0, [p3], m2; vshuffle x6, x6, x0, r2; vmul dm4, x0, x2, r10
; CHECK-NEXT:    vst.srs.4x dm1, s1, srssign0, [p3], #64; vsel.32 x4, x4, x3, r22
; CHECK-NEXT:    vst.2d.srs.4x dm0, s1, srssign0, [p3], d3; vshuffle x10, x5, x0, r3; vaddmac dm3, dm3, dm4, x8, x6, r12
; CHECK-NEXT:    vshuffle x6, x10, x0, r4; vaddmac dm2, dm2, dm4, x1, x6, r12
; CHECK-NEXT:    jnz r0, #.LBB0_1; vmul dm4, x0, x4, r10
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vaddmac dm1, dm1, dm4, x8, x6, r12 // Delay Slot 4
; CHECK-NEXT:    vaddmac dm0, dm0, dm4, x1, x6, r12 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.4: // %cooldown.entry
; CHECK-NEXT:    vldb x3, [p1], m4
; CHECK-NEXT:    vlda.3d x1, [p1], d1
; CHECK-NEXT:    vldb x10, [p0], #64; mov m0, p5
; CHECK-NEXT:    vlda.3d x8, [p0], d0
; CHECK-NEXT:    vldb x3, [p1], m4
; CHECK-NEXT:    vlda.3d x1, [p1], d1; movxm ls, #.LBB0_5
; CHECK-NEXT:    vldb x10, [p0], #64; movxm le, #.L_LEnd0
; CHECK-NEXT:    vlda.3d x8, [p0], d0; vshuffle x6, x3, x0, r7
; CHECK-NEXT:    nopa ; vldb x3, [p1], m4; nops ; add.nc lc, r6, #-3; vshuffle x4, x6, x0, r16; nopv
; CHECK-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; nopv
; CHECK-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; movx srssign0, #0; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:  .LBB0_5: // %for.body100.cd
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; vldb x3, [p1], m4; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; CHECK-NEXT:    vlda.3d x1, [p1], d1; nopb ; nops ; nopx ; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; CHECK-NEXT:    nopa ; vldb x10, [p0], #64; nops ; nopx ; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    vlda.3d x8, [p0], d0; nopb ; nops ; nopx ; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:  // %bb.6: // %cooldown.exit
; CHECK-NEXT:    lda p7, [sp, #-60]; nopb ; nops ; nopx ; vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8 // 4-byte Folded Reload
; CHECK-NEXT:    lda p6, [sp, #-64]; nopb ; movx crsrsmode, #0; vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8 // 4-byte Folded Reload
; CHECK-NEXT:    paddxm [sp], #-64; or r12, r24, r24; vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:    or r10, r23, r23; vshuffle x6, x3, x0, r7; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:    vshuffle x4, x6, x0, r16; vmac dm1, dm1, x10, x0, r8
; CHECK-NEXT:    vshuffle x2, x1, x0, r18; vmac dm0, dm0, x8, x0, r8
; CHECK-NEXT:    vshuffle x0, x2, x0, r20; vmac dm3, dm3, x10, x4, r8
; CHECK-NEXT:    mov s0, r17; vmac dm2, dm2, x8, x4, r8
; CHECK-NEXT:    mov srssign0, r19; vmac dm1, dm1, x10, x0, r8
; CHECK-NEXT:    vmac dm0, dm0, x8, x0, r8
; CHECK-NEXT:    mov r8, r21
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.srs.4x dm3, s0, srssign0, [p3], #64
; CHECK-NEXT:    vst.srs.4x dm2, s0, srssign0, [p3], m2; ret lr
; CHECK-NEXT:    vst.srs.4x dm1, s0, srssign0, [p3, #0] // Delay Slot 5
; CHECK-NEXT:    vst.srs.4x dm0, s0, srssign0, [p3, #64]; movx srssign0, #0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %for.body.peel.pro

for.body.peel.pro:                                ; preds = %newFuncRoot
  %p_psum_in.0768.peel = addrspacecast ptr %p_psum to ptr addrspace(7)
  %p_bias_in.0.peel = addrspacecast ptr %p_bias to ptr addrspace(6)
  %.peel = load <4 x i32>, ptr addrspace(6) %p_bias_in.0.peel, align 16, !tbaa !4
  %shuffle.i.i.i.i.i.peel = shufflevector <4 x i32> %.peel, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i.peel = shufflevector <8 x i32> %shuffle.i.i.i.i.i.peel, <8 x i32> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i.peel = getelementptr inbounds nuw i8, ptr %p_bias, i20 16
  %add.ptr.ascast.i.peel = addrspacecast ptr %add.ptr.i.peel to ptr addrspace(6)
  %.peel1 = load <4 x i32>, ptr addrspace(6) %add.ptr.ascast.i.peel, align 16, !tbaa !4
  %shuffle.i.i.i.i.i305.peel = shufflevector <4 x i32> %.peel1, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i306.peel = shufflevector <8 x i32> %shuffle.i.i.i.i.i305.peel, <8 x i32> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %.peel2 = load <32 x i16>, ptr addrspace(5) %1, align 64, !tbaa !4, !noalias !7
  %.peel3 = addrspacecast ptr addrspace(5) %1 to ptr
  %add.ptr.i309.peel = getelementptr inbounds nuw i8, ptr %.peel3, i20 64
  %add.ptr.ascast.i310.peel = addrspacecast ptr %add.ptr.i309.peel to ptr addrspace(5)
  %.peel4 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i310.peel, align 64, !tbaa !4, !noalias !14
  %.peel5 = trunc nuw i32 0 to i20
  %.peel6 = trunc nuw i32 0 to i20
  %.peel7 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i309.peel, i20 %3, i20 %4, i20 %5, i20 %6, i20 %.peel5, i20 %7, i20 %.peel6)
  %.peel8 = extractvalue { ptr, i20, i20 } %.peel7, 1
  %.peel9 = zext i20 %.peel8 to i32
  %.peel10 = extractvalue { ptr, i20, i20 } %.peel7, 2
  %.peel11 = zext i20 %.peel10 to i32
  %.peel12 = load <16 x i32>, ptr addrspace(5) %2, align 64, !tbaa !4, !noalias !21
  %.peel13 = addrspacecast ptr addrspace(5) %2 to ptr
  %add.ptr.i313.peel = getelementptr inbounds i8, ptr %.peel13, i20 %idx.ext.i
  %add.ptr.ascast.i314.peel = addrspacecast ptr %add.ptr.i313.peel to ptr addrspace(5)
  %.peel14 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i314.peel, align 64, !tbaa !4, !noalias !28
  %.peel15 = trunc nuw i32 0 to i20
  %.peel16 = trunc nuw i32 0 to i20
  %.peel17 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i313.peel, i20 %8, i20 %9, i20 %10, i20 %11, i20 %.peel15, i20 %12, i20 %.peel16)
  %.peel18 = extractvalue { ptr, i20, i20 } %.peel17, 1
  %.peel19 = zext i20 %.peel18 to i32
  %.peel20 = extractvalue { ptr, i20, i20 } %.peel17, 2
  %.peel21 = zext i20 %.peel20 to i32
  %.peel22 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.peel12, <16 x i32> poison, i32 %13)
  %.peel23 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.peel22, <16 x i32> poison, i32 %14)
  %.peel24 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.peel14, <16 x i32> poison, i32 %15)
  %.peel25 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.peel24, <16 x i32> poison, i32 %16)
  %.peel26 = load <32 x i16>, ptr addrspace(7) %p_psum_in.0768.peel, align 64, !tbaa !4, !noalias !35
  %arrayidx.i.i.i.i.i.i.i.i.i.i.peel = getelementptr inbounds nuw i8, ptr addrspace(7) %p_psum_in.0768.peel, i20 64
  %.peel27 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i.peel, align 64, !tbaa !4, !noalias !35
  %.peel28 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel26, i32 0, i32 range(i32 0, 2) 1)
  %.peel29 = bitcast <32 x i32> %.peel28 to <16 x i64>
  %.peel30 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel27, i32 0, i32 range(i32 0, 2) 1)
  %.peel31 = bitcast <32 x i32> %.peel30 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.peel = shufflevector <16 x i64> %.peel29, <16 x i64> %.peel31, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i352.peel = getelementptr inbounds nuw i8, ptr %p_psum, i20 128
  %add.ptr.ascast.i353.peel = addrspacecast ptr %add.ptr.i352.peel to ptr addrspace(7)
  %.peel32 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i353.peel, align 64, !tbaa !4, !noalias !42
  %arrayidx.i.i.i.i.i.i.i.i.i.i354.peel = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i353.peel, i20 64
  %.peel33 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i354.peel, align 64, !tbaa !4, !noalias !42
  %.peel34 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel32, i32 0, i32 range(i32 0, 2) 1)
  %.peel35 = bitcast <32 x i32> %.peel34 to <16 x i64>
  %.peel36 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel33, i32 0, i32 range(i32 0, 2) 1)
  %.peel37 = bitcast <32 x i32> %.peel36 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i357.peel = shufflevector <16 x i64> %.peel35, <16 x i64> %.peel37, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i358.peel = getelementptr inbounds nuw i8, ptr %p_psum, i20 256
  %add.ptr.ascast.i359.peel = addrspacecast ptr %add.ptr.i358.peel to ptr addrspace(7)
  %.peel38 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i359.peel, align 64, !tbaa !4, !noalias !49
  %arrayidx.i.i.i.i.i.i.i.i.i.i360.peel = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i359.peel, i20 64
  %.peel39 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i360.peel, align 64, !tbaa !4, !noalias !49
  %.peel40 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel38, i32 0, i32 range(i32 0, 2) 1)
  %.peel41 = bitcast <32 x i32> %.peel40 to <16 x i64>
  %.peel42 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel39, i32 0, i32 range(i32 0, 2) 1)
  %.peel43 = bitcast <32 x i32> %.peel42 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i363.peel = shufflevector <16 x i64> %.peel41, <16 x i64> %.peel43, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i364.peel = getelementptr inbounds nuw i8, ptr %p_psum, i20 384
  %add.ptr.ascast.i365.peel = addrspacecast ptr %add.ptr.i364.peel to ptr addrspace(7)
  %.peel44 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i365.peel, align 64, !tbaa !4, !noalias !56
  %arrayidx.i.i.i.i.i.i.i.i.i.i366.peel = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i365.peel, i20 64
  %.peel45 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i366.peel, align 64, !tbaa !4, !noalias !56
  %.peel46 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel44, i32 0, i32 range(i32 0, 2) 1)
  %.peel47 = bitcast <32 x i32> %.peel46 to <16 x i64>
  %.peel48 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.peel45, i32 0, i32 range(i32 0, 2) 1)
  %.peel49 = bitcast <32 x i32> %.peel48 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i369.peel = shufflevector <16 x i64> %.peel47, <16 x i64> %.peel49, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %.peel50 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.peel to <64 x i32>
  %.peel51 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i357.peel to <64 x i32>
  %.peel52 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i363.peel to <64 x i32>
  %.peel53 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i369.peel to <64 x i32>
  %.peel54 = bitcast <16 x i32> %.peel23 to <32 x i16>
  %.peel55 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.peel2, <32 x i16> %.peel54, <64 x i32> %.peel50, i32 %or23.i.i.i.i)
  %.peel56 = bitcast <64 x i32> %.peel55 to <32 x i64>
  %.peel57 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.peel4, <32 x i16> %.peel54, <64 x i32> %.peel51, i32 %or23.i.i.i.i)
  %.peel58 = bitcast <64 x i32> %.peel57 to <32 x i64>
  %.peel59 = bitcast <16 x i32> %.peel25 to <32 x i16>
  %.peel60 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.peel2, <32 x i16> %.peel59, <64 x i32> %.peel52, i32 %or23.i.i.i.i)
  %.peel61 = bitcast <64 x i32> %.peel60 to <32 x i64>
  %.peel62 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.peel4, <32 x i16> %.peel59, <64 x i32> %.peel53, i32 %or23.i.i.i.i)
  %.peel63 = bitcast <64 x i32> %.peel62 to <32 x i64>
  %shuffle.i.i.i.i.i9.i.i.i.i.peel = shufflevector <8 x i32> %shuffle1.i.i.i.i.i.peel, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %.peel64 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i.peel to <64 x i8>
  %.peel65 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %17, <64 x i8> %.peel64, i32 776)
  %.peel66 = bitcast <64 x i32> %.peel65 to <32 x i64>
  %.peel67 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.peel56, <32 x i64> %.peel66, i32 0)
  %.peel68 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.peel58, <32 x i64> %.peel66, i32 0)
  %shuffle.i.i.i.i.i9.i.i.i.i465.peel = shufflevector <8 x i32> %shuffle1.i.i.i.i.i306.peel, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %.peel69 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i465.peel to <64 x i8>
  %.peel70 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %17, <64 x i8> %.peel69, i32 776)
  %.peel71 = bitcast <64 x i32> %.peel70 to <32 x i64>
  %.peel72 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.peel61, <32 x i64> %.peel71, i32 0)
  %.peel73 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.peel63, <32 x i64> %.peel71, i32 0)
  %.peel74 = bitcast <32 x i64> %.peel67 to <64 x i32>
  %.peel75 = bitcast <32 x i64> %.peel68 to <64 x i32>
  %.peel76 = bitcast <32 x i64> %.peel72 to <64 x i32>
  %.peel77 = bitcast <32 x i64> %.peel73 to <64 x i32>
  %p_mat_a.1.in735.peel = extractvalue { ptr, i20, i20 } %.peel7, 0
  %p_mat_a.1736.peel = addrspacecast ptr %p_mat_a.1.in735.peel to ptr addrspace(5)
  %p_mat_b.1.in737.peel = extractvalue { ptr, i20, i20 } %.peel17, 0
  %p_mat_b.1738.peel = addrspacecast ptr %p_mat_b.1.in737.peel to ptr addrspace(5)
  br label %for.body

for.body:                                         ; preds = %for.body.peel.pro, %for.cond.cleanup99
  %lsr.iv806 = phi i32 [ %0, %for.body.peel.pro ], [ %lsr.iv.next807, %for.cond.cleanup99 ]
  %p_mat_a.0766 = phi ptr addrspace(5) [ %1, %for.body.peel.pro ], [ %59, %for.cond.cleanup99 ]
  %p_mat_b.0765 = phi ptr addrspace(5) [ %2, %for.body.peel.pro ], [ %58, %for.cond.cleanup99 ]
  %p_psum_in.0.in764 = phi ptr [ %p_psum, %for.body.peel.pro ], [ %add.ptr.i370, %for.cond.cleanup99 ]
  %p_mat_c.0.in763 = phi ptr [ %p_c, %for.body.peel.pro ], [ %69, %for.cond.cleanup99 ]
  %p_bias_in.0.in762 = phi ptr [ %p_bias, %for.body.peel.pro ], [ %74, %for.cond.cleanup99 ]
  %iterator_mat_a_cnt0.0761 = phi i32 [ 0, %for.body.peel.pro ], [ %35, %for.cond.cleanup99 ]
  %iterator_mat_a_cnt1.0760 = phi i32 [ 0, %for.body.peel.pro ], [ %37, %for.cond.cleanup99 ]
  %iterator_mat_b_cnt0.0759 = phi i32 [ 0, %for.body.peel.pro ], [ %44, %for.cond.cleanup99 ]
  %iterator_mat_b_cnt1.0758 = phi i32 [ 0, %for.body.peel.pro ], [ %46, %for.cond.cleanup99 ]
  %iterator_mat_c_cnt0.0757 = phi i32 [ 0, %for.body.peel.pro ], [ %68, %for.cond.cleanup99 ]
  %iterator_psum_out_cnt0.0756 = phi i32 [ 0, %for.body.peel.pro ], [ %73, %for.cond.cleanup99 ]
  %B0.sroa.0.0755 = phi <8 x i32> [ zeroinitializer, %for.body.peel.pro ], [ %shuffle1.i.i.i.i.i.phi, %for.cond.cleanup99 ]
  %B1.sroa.0.0754 = phi <8 x i32> [ zeroinitializer, %for.body.peel.pro ], [ %shuffle1.i.i.i.i.i306.phi, %for.cond.cleanup99 ]
  %p_psum_in.0768.phi = phi ptr addrspace(7) [ %p_psum_in.0768.peel, %for.body.peel.pro ], [ %p_psum_in.0768.epi, %for.cond.cleanup99 ]
  %p_bias_in.0.phi = phi ptr addrspace(6) [ %p_bias_in.0.peel, %for.body.peel.pro ], [ %p_bias_in.0.epi, %for.cond.cleanup99 ]
  %.phi = phi <4 x i32> [ %.peel, %for.body.peel.pro ], [ %.epi, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i.phi = phi <8 x i32> [ %shuffle.i.i.i.i.i.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i.epi, %for.cond.cleanup99 ]
  %shuffle1.i.i.i.i.i.phi = phi <8 x i32> [ %shuffle1.i.i.i.i.i.peel, %for.body.peel.pro ], [ %shuffle1.i.i.i.i.i.epi, %for.cond.cleanup99 ]
  %add.ptr.i.phi = phi ptr [ %add.ptr.i.peel, %for.body.peel.pro ], [ %add.ptr.i.epi, %for.cond.cleanup99 ]
  %add.ptr.ascast.i.phi = phi ptr addrspace(6) [ %add.ptr.ascast.i.peel, %for.body.peel.pro ], [ %add.ptr.ascast.i.epi, %for.cond.cleanup99 ]
  %.phi155 = phi <4 x i32> [ %.peel1, %for.body.peel.pro ], [ %.epi78, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i305.phi = phi <8 x i32> [ %shuffle.i.i.i.i.i305.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i305.epi, %for.cond.cleanup99 ]
  %shuffle1.i.i.i.i.i306.phi = phi <8 x i32> [ %shuffle1.i.i.i.i.i306.peel, %for.body.peel.pro ], [ %shuffle1.i.i.i.i.i306.epi, %for.cond.cleanup99 ]
  %.phi156 = phi <32 x i16> [ %.peel2, %for.body.peel.pro ], [ %.epi79, %for.cond.cleanup99 ]
  %.phi157 = phi ptr [ %.peel3, %for.body.peel.pro ], [ %.epi80, %for.cond.cleanup99 ]
  %add.ptr.i309.phi = phi ptr [ %add.ptr.i309.peel, %for.body.peel.pro ], [ %add.ptr.i309.epi, %for.cond.cleanup99 ]
  %add.ptr.ascast.i310.phi = phi ptr addrspace(5) [ %add.ptr.ascast.i310.peel, %for.body.peel.pro ], [ %add.ptr.ascast.i310.epi, %for.cond.cleanup99 ]
  %.phi158 = phi <32 x i16> [ %.peel4, %for.body.peel.pro ], [ %.epi81, %for.cond.cleanup99 ]
  %.phi159 = phi i20 [ %.peel5, %for.body.peel.pro ], [ %.epi82, %for.cond.cleanup99 ]
  %.phi160 = phi i20 [ %.peel6, %for.body.peel.pro ], [ %.epi83, %for.cond.cleanup99 ]
  %.phi161 = phi { ptr, i20, i20 } [ %.peel7, %for.body.peel.pro ], [ %.epi84, %for.cond.cleanup99 ]
  %.phi162 = phi i20 [ %.peel8, %for.body.peel.pro ], [ %.epi85, %for.cond.cleanup99 ]
  %.phi163 = phi i32 [ %.peel9, %for.body.peel.pro ], [ %.epi86, %for.cond.cleanup99 ]
  %.phi164 = phi i20 [ %.peel10, %for.body.peel.pro ], [ %.epi87, %for.cond.cleanup99 ]
  %.phi165 = phi i32 [ %.peel11, %for.body.peel.pro ], [ %.epi88, %for.cond.cleanup99 ]
  %.phi166 = phi <16 x i32> [ %.peel12, %for.body.peel.pro ], [ %.epi89, %for.cond.cleanup99 ]
  %.phi167 = phi ptr [ %.peel13, %for.body.peel.pro ], [ %.epi90, %for.cond.cleanup99 ]
  %add.ptr.i313.phi = phi ptr [ %add.ptr.i313.peel, %for.body.peel.pro ], [ %add.ptr.i313.epi, %for.cond.cleanup99 ]
  %add.ptr.ascast.i314.phi = phi ptr addrspace(5) [ %add.ptr.ascast.i314.peel, %for.body.peel.pro ], [ %add.ptr.ascast.i314.epi, %for.cond.cleanup99 ]
  %.phi168 = phi <16 x i32> [ %.peel14, %for.body.peel.pro ], [ %.epi91, %for.cond.cleanup99 ]
  %.phi169 = phi i20 [ %.peel15, %for.body.peel.pro ], [ %.epi92, %for.cond.cleanup99 ]
  %.phi170 = phi i20 [ %.peel16, %for.body.peel.pro ], [ %.epi93, %for.cond.cleanup99 ]
  %.phi171 = phi { ptr, i20, i20 } [ %.peel17, %for.body.peel.pro ], [ %.epi94, %for.cond.cleanup99 ]
  %.phi172 = phi i20 [ %.peel18, %for.body.peel.pro ], [ %.epi95, %for.cond.cleanup99 ]
  %.phi173 = phi i32 [ %.peel19, %for.body.peel.pro ], [ %.epi96, %for.cond.cleanup99 ]
  %.phi174 = phi i20 [ %.peel20, %for.body.peel.pro ], [ %.epi97, %for.cond.cleanup99 ]
  %.phi175 = phi i32 [ %.peel21, %for.body.peel.pro ], [ %.epi98, %for.cond.cleanup99 ]
  %.phi176 = phi <16 x i32> [ %.peel22, %for.body.peel.pro ], [ %.epi99, %for.cond.cleanup99 ]
  %.phi177 = phi <16 x i32> [ %.peel23, %for.body.peel.pro ], [ %.epi100, %for.cond.cleanup99 ]
  %.phi178 = phi <16 x i32> [ %.peel24, %for.body.peel.pro ], [ %.epi101, %for.cond.cleanup99 ]
  %.phi179 = phi <16 x i32> [ %.peel25, %for.body.peel.pro ], [ %.epi102, %for.cond.cleanup99 ]
  %.phi180 = phi <32 x i16> [ %.peel26, %for.body.peel.pro ], [ %.epi103, %for.cond.cleanup99 ]
  %arrayidx.i.i.i.i.i.i.i.i.i.i.phi = phi ptr addrspace(7) [ %arrayidx.i.i.i.i.i.i.i.i.i.i.peel, %for.body.peel.pro ], [ %arrayidx.i.i.i.i.i.i.i.i.i.i.epi, %for.cond.cleanup99 ]
  %.phi181 = phi <32 x i16> [ %.peel27, %for.body.peel.pro ], [ %.epi104, %for.cond.cleanup99 ]
  %.phi182 = phi <32 x i32> [ %.peel28, %for.body.peel.pro ], [ %.epi105, %for.cond.cleanup99 ]
  %.phi183 = phi <16 x i64> [ %.peel29, %for.body.peel.pro ], [ %.epi106, %for.cond.cleanup99 ]
  %.phi184 = phi <32 x i32> [ %.peel30, %for.body.peel.pro ], [ %.epi107, %for.cond.cleanup99 ]
  %.phi185 = phi <16 x i64> [ %.peel31, %for.body.peel.pro ], [ %.epi108, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i.i.i.i.phi = phi <32 x i64> [ %shuffle.i.i.i.i.i.i.i.i.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i.i.i.i.epi, %for.cond.cleanup99 ]
  %add.ptr.i352.phi = phi ptr [ %add.ptr.i352.peel, %for.body.peel.pro ], [ %add.ptr.i352.epi, %for.cond.cleanup99 ]
  %add.ptr.ascast.i353.phi = phi ptr addrspace(7) [ %add.ptr.ascast.i353.peel, %for.body.peel.pro ], [ %add.ptr.ascast.i353.epi, %for.cond.cleanup99 ]
  %.phi186 = phi <32 x i16> [ %.peel32, %for.body.peel.pro ], [ %.epi109, %for.cond.cleanup99 ]
  %arrayidx.i.i.i.i.i.i.i.i.i.i354.phi = phi ptr addrspace(7) [ %arrayidx.i.i.i.i.i.i.i.i.i.i354.peel, %for.body.peel.pro ], [ %arrayidx.i.i.i.i.i.i.i.i.i.i354.epi, %for.cond.cleanup99 ]
  %.phi187 = phi <32 x i16> [ %.peel33, %for.body.peel.pro ], [ %.epi110, %for.cond.cleanup99 ]
  %.phi188 = phi <32 x i32> [ %.peel34, %for.body.peel.pro ], [ %.epi111, %for.cond.cleanup99 ]
  %.phi189 = phi <16 x i64> [ %.peel35, %for.body.peel.pro ], [ %.epi112, %for.cond.cleanup99 ]
  %.phi190 = phi <32 x i32> [ %.peel36, %for.body.peel.pro ], [ %.epi113, %for.cond.cleanup99 ]
  %.phi191 = phi <16 x i64> [ %.peel37, %for.body.peel.pro ], [ %.epi114, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i.i.i.i357.phi = phi <32 x i64> [ %shuffle.i.i.i.i.i.i.i.i357.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i.i.i.i357.epi, %for.cond.cleanup99 ]
  %add.ptr.i358.phi = phi ptr [ %add.ptr.i358.peel, %for.body.peel.pro ], [ %add.ptr.i358.epi, %for.cond.cleanup99 ]
  %add.ptr.ascast.i359.phi = phi ptr addrspace(7) [ %add.ptr.ascast.i359.peel, %for.body.peel.pro ], [ %add.ptr.ascast.i359.epi, %for.cond.cleanup99 ]
  %.phi192 = phi <32 x i16> [ %.peel38, %for.body.peel.pro ], [ %.epi115, %for.cond.cleanup99 ]
  %arrayidx.i.i.i.i.i.i.i.i.i.i360.phi = phi ptr addrspace(7) [ %arrayidx.i.i.i.i.i.i.i.i.i.i360.peel, %for.body.peel.pro ], [ %arrayidx.i.i.i.i.i.i.i.i.i.i360.epi, %for.cond.cleanup99 ]
  %.phi193 = phi <32 x i16> [ %.peel39, %for.body.peel.pro ], [ %.epi116, %for.cond.cleanup99 ]
  %.phi194 = phi <32 x i32> [ %.peel40, %for.body.peel.pro ], [ %.epi117, %for.cond.cleanup99 ]
  %.phi195 = phi <16 x i64> [ %.peel41, %for.body.peel.pro ], [ %.epi118, %for.cond.cleanup99 ]
  %.phi196 = phi <32 x i32> [ %.peel42, %for.body.peel.pro ], [ %.epi119, %for.cond.cleanup99 ]
  %.phi197 = phi <16 x i64> [ %.peel43, %for.body.peel.pro ], [ %.epi120, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i.i.i.i363.phi = phi <32 x i64> [ %shuffle.i.i.i.i.i.i.i.i363.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i.i.i.i363.epi, %for.cond.cleanup99 ]
  %add.ptr.i364.phi = phi ptr [ %add.ptr.i364.peel, %for.body.peel.pro ], [ %add.ptr.i364.epi, %for.cond.cleanup99 ]
  %add.ptr.ascast.i365.phi = phi ptr addrspace(7) [ %add.ptr.ascast.i365.peel, %for.body.peel.pro ], [ %add.ptr.ascast.i365.epi, %for.cond.cleanup99 ]
  %.phi198 = phi <32 x i16> [ %.peel44, %for.body.peel.pro ], [ %.epi121, %for.cond.cleanup99 ]
  %arrayidx.i.i.i.i.i.i.i.i.i.i366.phi = phi ptr addrspace(7) [ %arrayidx.i.i.i.i.i.i.i.i.i.i366.peel, %for.body.peel.pro ], [ %arrayidx.i.i.i.i.i.i.i.i.i.i366.epi, %for.cond.cleanup99 ]
  %.phi199 = phi <32 x i16> [ %.peel45, %for.body.peel.pro ], [ %.epi122, %for.cond.cleanup99 ]
  %.phi200 = phi <32 x i32> [ %.peel46, %for.body.peel.pro ], [ %.epi123, %for.cond.cleanup99 ]
  %.phi201 = phi <16 x i64> [ %.peel47, %for.body.peel.pro ], [ %.epi124, %for.cond.cleanup99 ]
  %.phi202 = phi <32 x i32> [ %.peel48, %for.body.peel.pro ], [ %.epi125, %for.cond.cleanup99 ]
  %.phi203 = phi <16 x i64> [ %.peel49, %for.body.peel.pro ], [ %.epi126, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i.i.i.i369.phi = phi <32 x i64> [ %shuffle.i.i.i.i.i.i.i.i369.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i.i.i.i369.epi, %for.cond.cleanup99 ]
  %.phi204 = phi <64 x i32> [ %.peel50, %for.body.peel.pro ], [ %.epi127, %for.cond.cleanup99 ]
  %.phi205 = phi <64 x i32> [ %.peel51, %for.body.peel.pro ], [ %.epi128, %for.cond.cleanup99 ]
  %.phi206 = phi <64 x i32> [ %.peel52, %for.body.peel.pro ], [ %.epi129, %for.cond.cleanup99 ]
  %.phi207 = phi <64 x i32> [ %.peel53, %for.body.peel.pro ], [ %.epi130, %for.cond.cleanup99 ]
  %.phi208 = phi <32 x i16> [ %.peel54, %for.body.peel.pro ], [ %.epi131, %for.cond.cleanup99 ]
  %.phi209 = phi <64 x i32> [ %.peel55, %for.body.peel.pro ], [ %.epi132, %for.cond.cleanup99 ]
  %.phi210 = phi <32 x i64> [ %.peel56, %for.body.peel.pro ], [ %.epi133, %for.cond.cleanup99 ]
  %.phi211 = phi <64 x i32> [ %.peel57, %for.body.peel.pro ], [ %.epi134, %for.cond.cleanup99 ]
  %.phi212 = phi <32 x i64> [ %.peel58, %for.body.peel.pro ], [ %.epi135, %for.cond.cleanup99 ]
  %.phi213 = phi <32 x i16> [ %.peel59, %for.body.peel.pro ], [ %.epi136, %for.cond.cleanup99 ]
  %.phi214 = phi <64 x i32> [ %.peel60, %for.body.peel.pro ], [ %.epi137, %for.cond.cleanup99 ]
  %.phi215 = phi <32 x i64> [ %.peel61, %for.body.peel.pro ], [ %.epi138, %for.cond.cleanup99 ]
  %.phi216 = phi <64 x i32> [ %.peel62, %for.body.peel.pro ], [ %.epi139, %for.cond.cleanup99 ]
  %.phi217 = phi <32 x i64> [ %.peel63, %for.body.peel.pro ], [ %.epi140, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i9.i.i.i.i.phi = phi <16 x i32> [ %shuffle.i.i.i.i.i9.i.i.i.i.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i9.i.i.i.i.epi, %for.cond.cleanup99 ]
  %.phi218 = phi <64 x i8> [ %.peel64, %for.body.peel.pro ], [ %.epi141, %for.cond.cleanup99 ]
  %.phi219 = phi <64 x i32> [ %.peel65, %for.body.peel.pro ], [ %.epi142, %for.cond.cleanup99 ]
  %.phi220 = phi <32 x i64> [ %.peel66, %for.body.peel.pro ], [ %.epi143, %for.cond.cleanup99 ]
  %.phi221 = phi <32 x i64> [ %.peel67, %for.body.peel.pro ], [ %.epi144, %for.cond.cleanup99 ]
  %.phi222 = phi <32 x i64> [ %.peel68, %for.body.peel.pro ], [ %.epi145, %for.cond.cleanup99 ]
  %shuffle.i.i.i.i.i9.i.i.i.i465.phi = phi <16 x i32> [ %shuffle.i.i.i.i.i9.i.i.i.i465.peel, %for.body.peel.pro ], [ %shuffle.i.i.i.i.i9.i.i.i.i465.epi, %for.cond.cleanup99 ]
  %.phi223 = phi <64 x i8> [ %.peel69, %for.body.peel.pro ], [ %.epi146, %for.cond.cleanup99 ]
  %.phi224 = phi <64 x i32> [ %.peel70, %for.body.peel.pro ], [ %.epi147, %for.cond.cleanup99 ]
  %.phi225 = phi <32 x i64> [ %.peel71, %for.body.peel.pro ], [ %.epi148, %for.cond.cleanup99 ]
  %.phi226 = phi <32 x i64> [ %.peel72, %for.body.peel.pro ], [ %.epi149, %for.cond.cleanup99 ]
  %.phi227 = phi <32 x i64> [ %.peel73, %for.body.peel.pro ], [ %.epi150, %for.cond.cleanup99 ]
  %.phi228 = phi <64 x i32> [ %.peel74, %for.body.peel.pro ], [ %.epi151, %for.cond.cleanup99 ]
  %.phi229 = phi <64 x i32> [ %.peel75, %for.body.peel.pro ], [ %.epi152, %for.cond.cleanup99 ]
  %.phi230 = phi <64 x i32> [ %.peel76, %for.body.peel.pro ], [ %.epi153, %for.cond.cleanup99 ]
  %.phi231 = phi <64 x i32> [ %.peel77, %for.body.peel.pro ], [ %.epi154, %for.cond.cleanup99 ]
  %p_mat_a.1.in735.phi = phi ptr [ %p_mat_a.1.in735.peel, %for.body.peel.pro ], [ %p_mat_a.1.in735.epi, %for.cond.cleanup99 ]
  %p_mat_a.1736.phi = phi ptr addrspace(5) [ %p_mat_a.1736.peel, %for.body.peel.pro ], [ %p_mat_a.1736.epi, %for.cond.cleanup99 ]
  %p_mat_b.1.in737.phi = phi ptr [ %p_mat_b.1.in737.peel, %for.body.peel.pro ], [ %p_mat_b.1.in737.epi, %for.cond.cleanup99 ]
  %p_mat_b.1738.phi = phi ptr addrspace(5) [ %p_mat_b.1738.peel, %for.body.peel.pro ], [ %p_mat_b.1738.epi, %for.cond.cleanup99 ]
  call void @llvm.set.loop.iterations.i32(i32 %18)
  br label %for.body100

for.body100:                                      ; preds = %for.body100, %for.body
  %p_mat_b.1751 = phi ptr addrspace(5) [ %p_mat_b.1738.phi, %for.body ], [ %p_mat_b.1, %for.body100 ]
  %p_mat_b.1.in750 = phi ptr [ %p_mat_b.1.in737.phi, %for.body ], [ %p_mat_b.1.in, %for.body100 ]
  %p_mat_a.1749 = phi ptr addrspace(5) [ %p_mat_a.1736.phi, %for.body ], [ %p_mat_a.1, %for.body100 ]
  %p_mat_a.1.in748 = phi ptr [ %p_mat_a.1.in735.phi, %for.body ], [ %p_mat_a.1.in, %for.body100 ]
  %iterator_mat_a_cnt0.1746 = phi i32 [ %.phi163, %for.body ], [ %35, %for.body100 ]
  %iterator_mat_a_cnt1.1745 = phi i32 [ %.phi165, %for.body ], [ %37, %for.body100 ]
  %iterator_mat_b_cnt0.1744 = phi i32 [ %.phi173, %for.body ], [ %44, %for.body100 ]
  %iterator_mat_b_cnt1.1743 = phi i32 [ %.phi175, %for.body ], [ %46, %for.body100 ]
  %Ci3.sroa.0.0742 = phi <64 x i32> [ %.phi231, %for.body ], [ %56, %for.body100 ]
  %Ci2.sroa.0.0741 = phi <64 x i32> [ %.phi230, %for.body ], [ %55, %for.body100 ]
  %Ci1.sroa.0.0740 = phi <64 x i32> [ %.phi229, %for.body ], [ %53, %for.body100 ]
  %Ci0.sroa.0.0739 = phi <64 x i32> [ %.phi228, %for.body ], [ %52, %for.body100 ]
  %29 = load <32 x i16>, ptr addrspace(5) %p_mat_a.1749, align 64, !tbaa !4, !noalias !63
  %add.ptr.i485 = getelementptr inbounds nuw i8, ptr %p_mat_a.1.in748, i20 64
  %add.ptr.ascast.i486 = addrspacecast ptr %add.ptr.i485 to ptr addrspace(5)
  %30 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i486, align 64, !tbaa !4, !noalias !70
  %31 = trunc nuw i32 %iterator_mat_a_cnt0.1746 to i20
  %32 = trunc nuw i32 %iterator_mat_a_cnt1.1745 to i20
  %33 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i485, i20 %3, i20 %4, i20 %5, i20 %6, i20 %31, i20 %7, i20 %32)
  %34 = extractvalue { ptr, i20, i20 } %33, 1
  %35 = zext i20 %34 to i32
  %36 = extractvalue { ptr, i20, i20 } %33, 2
  %37 = zext i20 %36 to i32
  %38 = load <16 x i32>, ptr addrspace(5) %p_mat_b.1751, align 64, !tbaa !4, !noalias !77
  %add.ptr.i490 = getelementptr inbounds i8, ptr %p_mat_b.1.in750, i20 %idx.ext.i
  %add.ptr.ascast.i491 = addrspacecast ptr %add.ptr.i490 to ptr addrspace(5)
  %39 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i491, align 64, !tbaa !4, !noalias !84
  %40 = trunc nuw i32 %iterator_mat_b_cnt0.1744 to i20
  %41 = trunc nuw i32 %iterator_mat_b_cnt1.1743 to i20
  %42 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i490, i20 %8, i20 %9, i20 %10, i20 %11, i20 %40, i20 %12, i20 %41)
  %43 = extractvalue { ptr, i20, i20 } %42, 1
  %44 = zext i20 %43 to i32
  %45 = extractvalue { ptr, i20, i20 } %42, 2
  %46 = zext i20 %45 to i32
  %47 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %38, <16 x i32> poison, i32 %19)
  %48 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %47, <16 x i32> poison, i32 %20)
  %49 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %39, <16 x i32> poison, i32 %21)
  %50 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %49, <16 x i32> poison, i32 %22)
  %51 = bitcast <16 x i32> %48 to <32 x i16>
  %52 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %29, <32 x i16> %51, <64 x i32> %Ci0.sroa.0.0739, i32 %or22.i.i.i.i)
  %53 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %30, <32 x i16> %51, <64 x i32> %Ci1.sroa.0.0740, i32 %or22.i.i.i.i)
  %54 = bitcast <16 x i32> %50 to <32 x i16>
  %55 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %29, <32 x i16> %54, <64 x i32> %Ci2.sroa.0.0741, i32 %or22.i.i.i.i)
  %56 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %30, <32 x i16> %54, <64 x i32> %Ci3.sroa.0.0742, i32 %or22.i.i.i.i)
  %p_mat_a.1.in = extractvalue { ptr, i20, i20 } %33, 0
  %p_mat_a.1 = addrspacecast ptr %p_mat_a.1.in to ptr addrspace(5)
  %p_mat_b.1.in = extractvalue { ptr, i20, i20 } %42, 0
  %p_mat_b.1 = addrspacecast ptr %p_mat_b.1.in to ptr addrspace(5)
  %57 = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %57, label %for.body100, label %for.cond.cleanup99, !llvm.loop !91

for.cond.cleanup99:                               ; preds = %for.body100
  %58 = addrspacecast ptr %p_mat_b.1.in to ptr addrspace(5)
  %59 = addrspacecast ptr %p_mat_a.1.in to ptr addrspace(5)
  %60 = addrspacecast ptr %p_mat_c.0.in763 to ptr addrspace(6)
  %add.ptr.i370 = getelementptr inbounds nuw i8, ptr %p_psum_in.0.in764, i20 512
  %61 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %52, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %61, ptr addrspace(6) %60, align 64, !tbaa !4
  %add.ptr.i475 = getelementptr inbounds nuw i8, ptr %p_mat_c.0.in763, i20 64
  %add.ptr.ascast.i476 = addrspacecast ptr %add.ptr.i475 to ptr addrspace(6)
  %62 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %53, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %62, ptr addrspace(6) %add.ptr.ascast.i476, align 64, !tbaa !4
  %add.ptr.i479 = getelementptr inbounds i8, ptr %add.ptr.i475, i20 %idx.ext.i478
  %add.ptr.ascast.i480 = addrspacecast ptr %add.ptr.i479 to ptr addrspace(6)
  %63 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %55, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %63, ptr addrspace(6) %add.ptr.ascast.i480, align 64, !tbaa !4
  %add.ptr.i482 = getelementptr inbounds nuw i8, ptr %add.ptr.i479, i20 64
  %add.ptr.ascast.i483 = addrspacecast ptr %add.ptr.i482 to ptr addrspace(6)
  %64 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %56, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %64, ptr addrspace(6) %add.ptr.ascast.i483, align 64, !tbaa !4
  %65 = trunc nuw i32 %iterator_mat_c_cnt0.0757 to i20
  %66 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr nonnull %add.ptr.i482, i20 %23, i20 %24, i20 %25, i20 %65)
  %67 = extractvalue { ptr, i20 } %66, 1
  %68 = zext i20 %67 to i32
  %69 = extractvalue { ptr, i20 } %66, 0
  %70 = trunc nuw i32 %iterator_psum_out_cnt0.0756 to i20
  %71 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr nonnull %p_bias_in.0.in762, i20 %26, i20 %27, i20 %28, i20 %70)
  %72 = extractvalue { ptr, i20 } %71, 1
  %73 = zext i20 %72 to i32
  %74 = extractvalue { ptr, i20 } %71, 0
  %lsr.iv.next807 = add nsw i32 %lsr.iv806, -1
  %exitcond777.not = icmp eq i32 %lsr.iv.next807, 1
  %p_psum_in.0768.epi = addrspacecast ptr %add.ptr.i370 to ptr addrspace(7)
  %p_bias_in.0.epi = addrspacecast ptr %74 to ptr addrspace(6)
  %.epi = load <4 x i32>, ptr addrspace(6) %p_bias_in.0.epi, align 16, !tbaa !4
  %shuffle.i.i.i.i.i.epi = shufflevector <4 x i32> %.epi, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i.epi = shufflevector <8 x i32> %shuffle.i.i.i.i.i.epi, <8 x i32> %shuffle1.i.i.i.i.i.phi, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %add.ptr.i.epi = getelementptr inbounds nuw i8, ptr %74, i20 16
  %add.ptr.ascast.i.epi = addrspacecast ptr %add.ptr.i.epi to ptr addrspace(6)
  %.epi78 = load <4 x i32>, ptr addrspace(6) %add.ptr.ascast.i.epi, align 16, !tbaa !4
  %shuffle.i.i.i.i.i305.epi = shufflevector <4 x i32> %.epi78, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuffle1.i.i.i.i.i306.epi = shufflevector <8 x i32> %shuffle.i.i.i.i.i305.epi, <8 x i32> %shuffle1.i.i.i.i.i306.phi, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  %.epi79 = load <32 x i16>, ptr addrspace(5) %59, align 64, !tbaa !4, !noalias !7
  %.epi80 = addrspacecast ptr addrspace(5) %59 to ptr
  %add.ptr.i309.epi = getelementptr inbounds nuw i8, ptr %.epi80, i20 64
  %add.ptr.ascast.i310.epi = addrspacecast ptr %add.ptr.i309.epi to ptr addrspace(5)
  %.epi81 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i310.epi, align 64, !tbaa !4, !noalias !14
  %.epi82 = trunc nuw i32 %35 to i20
  %.epi83 = trunc nuw i32 %37 to i20
  %.epi84 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i309.epi, i20 %3, i20 %4, i20 %5, i20 %6, i20 %.epi82, i20 %7, i20 %.epi83)
  %.epi85 = extractvalue { ptr, i20, i20 } %.epi84, 1
  %.epi86 = zext i20 %.epi85 to i32
  %.epi87 = extractvalue { ptr, i20, i20 } %.epi84, 2
  %.epi88 = zext i20 %.epi87 to i32
  %.epi89 = load <16 x i32>, ptr addrspace(5) %58, align 64, !tbaa !4, !noalias !21
  %.epi90 = addrspacecast ptr addrspace(5) %58 to ptr
  %add.ptr.i313.epi = getelementptr inbounds i8, ptr %.epi90, i20 %idx.ext.i
  %add.ptr.ascast.i314.epi = addrspacecast ptr %add.ptr.i313.epi to ptr addrspace(5)
  %.epi91 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i314.epi, align 64, !tbaa !4, !noalias !28
  %.epi92 = trunc nuw i32 %44 to i20
  %.epi93 = trunc nuw i32 %46 to i20
  %.epi94 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i313.epi, i20 %8, i20 %9, i20 %10, i20 %11, i20 %.epi92, i20 %12, i20 %.epi93)
  %.epi95 = extractvalue { ptr, i20, i20 } %.epi94, 1
  %.epi96 = zext i20 %.epi95 to i32
  %.epi97 = extractvalue { ptr, i20, i20 } %.epi94, 2
  %.epi98 = zext i20 %.epi97 to i32
  %.epi99 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.epi89, <16 x i32> poison, i32 %13)
  %.epi100 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.epi99, <16 x i32> poison, i32 %14)
  %.epi101 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.epi91, <16 x i32> poison, i32 %15)
  %.epi102 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.epi101, <16 x i32> poison, i32 %16)
  %.epi103 = load <32 x i16>, ptr addrspace(7) %p_psum_in.0768.epi, align 64, !tbaa !4, !noalias !35
  %arrayidx.i.i.i.i.i.i.i.i.i.i.epi = getelementptr inbounds nuw i8, ptr addrspace(7) %p_psum_in.0768.epi, i20 64
  %.epi104 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i.epi, align 64, !tbaa !4, !noalias !35
  %.epi105 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi103, i32 0, i32 range(i32 0, 2) 1)
  %.epi106 = bitcast <32 x i32> %.epi105 to <16 x i64>
  %.epi107 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi104, i32 0, i32 range(i32 0, 2) 1)
  %.epi108 = bitcast <32 x i32> %.epi107 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.epi = shufflevector <16 x i64> %.epi106, <16 x i64> %.epi108, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i352.epi = getelementptr inbounds nuw i8, ptr %add.ptr.i370, i20 128
  %add.ptr.ascast.i353.epi = addrspacecast ptr %add.ptr.i352.epi to ptr addrspace(7)
  %.epi109 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i353.epi, align 64, !tbaa !4, !noalias !42
  %arrayidx.i.i.i.i.i.i.i.i.i.i354.epi = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i353.epi, i20 64
  %.epi110 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i354.epi, align 64, !tbaa !4, !noalias !42
  %.epi111 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi109, i32 0, i32 range(i32 0, 2) 1)
  %.epi112 = bitcast <32 x i32> %.epi111 to <16 x i64>
  %.epi113 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi110, i32 0, i32 range(i32 0, 2) 1)
  %.epi114 = bitcast <32 x i32> %.epi113 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i357.epi = shufflevector <16 x i64> %.epi112, <16 x i64> %.epi114, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i358.epi = getelementptr inbounds nuw i8, ptr %add.ptr.i370, i20 256
  %add.ptr.ascast.i359.epi = addrspacecast ptr %add.ptr.i358.epi to ptr addrspace(7)
  %.epi115 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i359.epi, align 64, !tbaa !4, !noalias !49
  %arrayidx.i.i.i.i.i.i.i.i.i.i360.epi = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i359.epi, i20 64
  %.epi116 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i360.epi, align 64, !tbaa !4, !noalias !49
  %.epi117 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi115, i32 0, i32 range(i32 0, 2) 1)
  %.epi118 = bitcast <32 x i32> %.epi117 to <16 x i64>
  %.epi119 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi116, i32 0, i32 range(i32 0, 2) 1)
  %.epi120 = bitcast <32 x i32> %.epi119 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i363.epi = shufflevector <16 x i64> %.epi118, <16 x i64> %.epi120, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %add.ptr.i364.epi = getelementptr inbounds nuw i8, ptr %add.ptr.i370, i20 384
  %add.ptr.ascast.i365.epi = addrspacecast ptr %add.ptr.i364.epi to ptr addrspace(7)
  %.epi121 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i365.epi, align 64, !tbaa !4, !noalias !56
  %arrayidx.i.i.i.i.i.i.i.i.i.i366.epi = getelementptr inbounds nuw i8, ptr addrspace(7) %add.ptr.ascast.i365.epi, i20 64
  %.epi122 = load <32 x i16>, ptr addrspace(7) %arrayidx.i.i.i.i.i.i.i.i.i.i366.epi, align 64, !tbaa !4, !noalias !56
  %.epi123 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi121, i32 0, i32 range(i32 0, 2) 1)
  %.epi124 = bitcast <32 x i32> %.epi123 to <16 x i64>
  %.epi125 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %.epi122, i32 0, i32 range(i32 0, 2) 1)
  %.epi126 = bitcast <32 x i32> %.epi125 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i369.epi = shufflevector <16 x i64> %.epi124, <16 x i64> %.epi126, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %.epi127 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.epi to <64 x i32>
  %.epi128 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i357.epi to <64 x i32>
  %.epi129 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i363.epi to <64 x i32>
  %.epi130 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i369.epi to <64 x i32>
  %.epi131 = bitcast <16 x i32> %.epi100 to <32 x i16>
  %.epi132 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.epi79, <32 x i16> %.epi131, <64 x i32> %.epi127, i32 %or23.i.i.i.i)
  %.epi133 = bitcast <64 x i32> %.epi132 to <32 x i64>
  %.epi134 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.epi81, <32 x i16> %.epi131, <64 x i32> %.epi128, i32 %or23.i.i.i.i)
  %.epi135 = bitcast <64 x i32> %.epi134 to <32 x i64>
  %.epi136 = bitcast <16 x i32> %.epi102 to <32 x i16>
  %.epi137 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.epi79, <32 x i16> %.epi136, <64 x i32> %.epi129, i32 %or23.i.i.i.i)
  %.epi138 = bitcast <64 x i32> %.epi137 to <32 x i64>
  %.epi139 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.epi81, <32 x i16> %.epi136, <64 x i32> %.epi130, i32 %or23.i.i.i.i)
  %.epi140 = bitcast <64 x i32> %.epi139 to <32 x i64>
  %shuffle.i.i.i.i.i9.i.i.i.i.epi = shufflevector <8 x i32> %shuffle1.i.i.i.i.i.epi, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %.epi141 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i.epi to <64 x i8>
  %.epi142 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %17, <64 x i8> %.epi141, i32 776)
  %.epi143 = bitcast <64 x i32> %.epi142 to <32 x i64>
  %.epi144 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.epi133, <32 x i64> %.epi143, i32 0)
  %.epi145 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.epi135, <32 x i64> %.epi143, i32 0)
  %shuffle.i.i.i.i.i9.i.i.i.i465.epi = shufflevector <8 x i32> %shuffle1.i.i.i.i.i306.epi, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %.epi146 = bitcast <16 x i32> %shuffle.i.i.i.i.i9.i.i.i.i465.epi to <64 x i8>
  %.epi147 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %17, <64 x i8> %.epi146, i32 776)
  %.epi148 = bitcast <64 x i32> %.epi147 to <32 x i64>
  %.epi149 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.epi138, <32 x i64> %.epi148, i32 0)
  %.epi150 = tail call <32 x i64> @llvm.aie2ps.ACC2048.add.conf(<32 x i64> %.epi140, <32 x i64> %.epi148, i32 0)
  %.epi151 = bitcast <32 x i64> %.epi144 to <64 x i32>
  %.epi152 = bitcast <32 x i64> %.epi145 to <64 x i32>
  %.epi153 = bitcast <32 x i64> %.epi149 to <64 x i32>
  %.epi154 = bitcast <32 x i64> %.epi150 to <64 x i32>
  %p_mat_a.1.in735.epi = extractvalue { ptr, i20, i20 } %.epi84, 0
  %p_mat_a.1736.epi = addrspacecast ptr %p_mat_a.1.in735.epi to ptr addrspace(5)
  %p_mat_b.1.in737.epi = extractvalue { ptr, i20, i20 } %.epi94, 0
  %p_mat_b.1738.epi = addrspacecast ptr %p_mat_b.1.in737.epi to ptr addrspace(5)
  br i1 %exitcond777.not, label %cooldown.entry, label %for.body, !llvm.loop !94

cooldown.entry:                                   ; preds = %for.cond.cleanup99
  call void @llvm.set.loop.iterations.i32(i32 %18)
  br label %for.body100.cd

for.body100.cd:                                   ; preds = %cooldown.entry, %for.body100.cd
  %p_mat_b.1751.cd = phi ptr addrspace(5) [ %p_mat_b.1738.epi, %cooldown.entry ], [ %p_mat_b.1.cd, %for.body100.cd ]
  %p_mat_b.1.in750.cd = phi ptr [ %p_mat_b.1.in737.epi, %cooldown.entry ], [ %p_mat_b.1.in.cd, %for.body100.cd ]
  %p_mat_a.1749.cd = phi ptr addrspace(5) [ %p_mat_a.1736.epi, %cooldown.entry ], [ %p_mat_a.1.cd, %for.body100.cd ]
  %p_mat_a.1.in748.cd = phi ptr [ %p_mat_a.1.in735.epi, %cooldown.entry ], [ %p_mat_a.1.in.cd, %for.body100.cd ]
  %iterator_mat_a_cnt0.1746.cd = phi i32 [ %.epi86, %cooldown.entry ], [ %.cd237, %for.body100.cd ]
  %iterator_mat_a_cnt1.1745.cd = phi i32 [ %.epi88, %cooldown.entry ], [ %.cd239, %for.body100.cd ]
  %iterator_mat_b_cnt0.1744.cd = phi i32 [ %.epi96, %cooldown.entry ], [ %.cd246, %for.body100.cd ]
  %iterator_mat_b_cnt1.1743.cd = phi i32 [ %.epi98, %cooldown.entry ], [ %.cd248, %for.body100.cd ]
  %Ci3.sroa.0.0742.cd = phi <64 x i32> [ %.epi154, %cooldown.entry ], [ %.cd258, %for.body100.cd ]
  %Ci2.sroa.0.0741.cd = phi <64 x i32> [ %.epi153, %cooldown.entry ], [ %.cd257, %for.body100.cd ]
  %Ci1.sroa.0.0740.cd = phi <64 x i32> [ %.epi152, %cooldown.entry ], [ %.cd255, %for.body100.cd ]
  %Ci0.sroa.0.0739.cd = phi <64 x i32> [ %.epi151, %cooldown.entry ], [ %.cd254, %for.body100.cd ]
  %.cd = load <32 x i16>, ptr addrspace(5) %p_mat_a.1749.cd, align 64, !tbaa !4, !noalias !63
  %add.ptr.i485.cd = getelementptr inbounds nuw i8, ptr %p_mat_a.1.in748.cd, i20 64
  %add.ptr.ascast.i486.cd = addrspacecast ptr %add.ptr.i485.cd to ptr addrspace(5)
  %.cd232 = load <32 x i16>, ptr addrspace(5) %add.ptr.ascast.i486.cd, align 64, !tbaa !4, !noalias !70
  %.cd233 = trunc nuw i32 %iterator_mat_a_cnt0.1746.cd to i20
  %.cd234 = trunc nuw i32 %iterator_mat_a_cnt1.1745.cd to i20
  %.cd235 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i485.cd, i20 %3, i20 %4, i20 %5, i20 %6, i20 %.cd233, i20 %7, i20 %.cd234)
  %.cd236 = extractvalue { ptr, i20, i20 } %.cd235, 1
  %.cd237 = zext i20 %.cd236 to i32
  %.cd238 = extractvalue { ptr, i20, i20 } %.cd235, 2
  %.cd239 = zext i20 %.cd238 to i32
  %.cd240 = load <16 x i32>, ptr addrspace(5) %p_mat_b.1751.cd, align 64, !tbaa !4, !noalias !77
  %add.ptr.i490.cd = getelementptr inbounds i8, ptr %p_mat_b.1.in750.cd, i20 %idx.ext.i
  %add.ptr.ascast.i491.cd = addrspacecast ptr %add.ptr.i490.cd to ptr addrspace(5)
  %.cd241 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i491.cd, align 64, !tbaa !4, !noalias !84
  %.cd242 = trunc nuw i32 %iterator_mat_b_cnt0.1744.cd to i20
  %.cd243 = trunc nuw i32 %iterator_mat_b_cnt1.1743.cd to i20
  %.cd244 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %add.ptr.i490.cd, i20 %8, i20 %9, i20 %10, i20 %11, i20 %.cd242, i20 %12, i20 %.cd243)
  %.cd245 = extractvalue { ptr, i20, i20 } %.cd244, 1
  %.cd246 = zext i20 %.cd245 to i32
  %.cd247 = extractvalue { ptr, i20, i20 } %.cd244, 2
  %.cd248 = zext i20 %.cd247 to i32
  %.cd249 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.cd240, <16 x i32> poison, i32 %19)
  %.cd250 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.cd249, <16 x i32> poison, i32 %20)
  %.cd251 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.cd241, <16 x i32> poison, i32 %21)
  %.cd252 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %.cd251, <16 x i32> poison, i32 %22)
  %.cd253 = bitcast <16 x i32> %.cd250 to <32 x i16>
  %.cd254 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.cd, <32 x i16> %.cd253, <64 x i32> %Ci0.sroa.0.0739.cd, i32 %or22.i.i.i.i)
  %.cd255 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.cd232, <32 x i16> %.cd253, <64 x i32> %Ci1.sroa.0.0740.cd, i32 %or22.i.i.i.i)
  %.cd256 = bitcast <16 x i32> %.cd252 to <32 x i16>
  %.cd257 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.cd, <32 x i16> %.cd256, <64 x i32> %Ci2.sroa.0.0741.cd, i32 %or22.i.i.i.i)
  %.cd258 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %.cd232, <32 x i16> %.cd256, <64 x i32> %Ci3.sroa.0.0742.cd, i32 %or22.i.i.i.i)
  %p_mat_a.1.in.cd = extractvalue { ptr, i20, i20 } %.cd235, 0
  %p_mat_a.1.cd = addrspacecast ptr %p_mat_a.1.in.cd to ptr addrspace(5)
  %p_mat_b.1.in.cd = extractvalue { ptr, i20, i20 } %.cd244, 0
  %p_mat_b.1.cd = addrspacecast ptr %p_mat_b.1.in.cd to ptr addrspace(5)
  %.cd259 = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %.cd259, label %for.body100.cd, label %cooldown.exit, !llvm.loop !91

cooldown.exit:                                    ; preds = %for.body100.cd
  %.cd260 = addrspacecast ptr %p_mat_b.1.in.cd to ptr addrspace(5)
  %.cd261 = addrspacecast ptr %p_mat_a.1.in.cd to ptr addrspace(5)
  %.cd262 = addrspacecast ptr %69 to ptr addrspace(6)
  %add.ptr.i370.cd = getelementptr inbounds nuw i8, ptr %add.ptr.i370, i20 512
  %.cd263 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %.cd254, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %.cd263, ptr addrspace(6) %.cd262, align 64, !tbaa !4
  %add.ptr.i475.cd = getelementptr inbounds nuw i8, ptr %69, i20 64
  %add.ptr.ascast.i476.cd = addrspacecast ptr %add.ptr.i475.cd to ptr addrspace(6)
  %.cd264 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %.cd255, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %.cd264, ptr addrspace(6) %add.ptr.ascast.i476.cd, align 64, !tbaa !4
  %add.ptr.i479.cd = getelementptr inbounds i8, ptr %add.ptr.i475.cd, i20 %idx.ext.i478
  %add.ptr.ascast.i480.cd = addrspacecast ptr %add.ptr.i479.cd to ptr addrspace(6)
  %.cd265 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %.cd257, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %.cd265, ptr addrspace(6) %add.ptr.ascast.i480.cd, align 64, !tbaa !4
  %add.ptr.i482.cd = getelementptr inbounds nuw i8, ptr %add.ptr.i479.cd, i20 64
  %add.ptr.ascast.i483.cd = addrspacecast ptr %add.ptr.i482.cd to ptr addrspace(6)
  %.cd266 = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> %.cd258, i32 %conv166, i32 range(i32 0, 2) %conv.i.i.i.i)
  store <64 x i8> %.cd266, ptr addrspace(6) %add.ptr.ascast.i483.cd, align 64, !tbaa !4
  %.cd267 = trunc nuw i32 %68 to i20
  %.cd268 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr nonnull %add.ptr.i482.cd, i20 %23, i20 %24, i20 %25, i20 %.cd267)
  %.cd269 = extractvalue { ptr, i20 } %.cd268, 1
  %.cd270 = zext i20 %.cd269 to i32
  %.cd271 = extractvalue { ptr, i20 } %.cd268, 0
  %.cd272 = trunc nuw i32 %73 to i20
  %.cd273 = tail call { ptr, i20 } @llvm.aie2ps.add.2d(ptr nonnull %74, i20 %26, i20 %27, i20 %28, i20 %.cd272)
  %.cd274 = extractvalue { ptr, i20 } %.cd273, 1
  %.cd275 = zext i20 %.cd274 to i32
  %.cd276 = extractvalue { ptr, i20 } %.cd273, 0
  %lsr.iv.next807.cd = add nsw i32 %lsr.iv.next807, -1
  %exitcond777.not.cd = icmp eq i32 %lsr.iv.next807.cd, 0
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %cooldown.exit
  ret void
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #2 = { nocallback noduplicate nofree nosync nounwind willreturn }
attributes #3 = { mustprogress noinline "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 21.0.0git"}
!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{!8, !10, !12}
!8 = distinct !{!8, !9, !"A: %agg.result"}
!9 = distinct !{!9, !"A"}
!10 = distinct !{!10, !11, !"B: %agg.result"}
!11 = distinct !{!11, !"B"}
!12 = distinct !{!12, !13, !"C: %agg.result"}
!13 = distinct !{!13, !"C"}
!14 = !{!15, !17, !19}
!15 = distinct !{!15, !16, !"A: %agg.result"}
!16 = distinct !{!16, !"A"}
!17 = distinct !{!17, !18, !"B: %agg.result"}
!18 = distinct !{!18, !"B"}
!19 = distinct !{!19, !20, !"C: %agg.result"}
!20 = distinct !{!20, !"C"}
!21 = !{!22, !24, !26}
!22 = distinct !{!22, !23, !"A: %agg.result"}
!23 = distinct !{!23, !"A"}
!24 = distinct !{!24, !25, !"B: %agg.result"}
!25 = distinct !{!25, !"B"}
!26 = distinct !{!26, !27, !"C: %agg.result"}
!27 = distinct !{!27, !"C"}
!28 = !{!29, !31, !33}
!29 = distinct !{!29, !30, !"A: %agg.result"}
!30 = distinct !{!30, !"A"}
!31 = distinct !{!31, !32, !"B: %agg.result"}
!32 = distinct !{!32, !"B"}
!33 = distinct !{!33, !34, !"C: %agg.result"}
!34 = distinct !{!34, !"C"}
!35 = !{!36, !38, !40}
!36 = distinct !{!36, !37, !"D: %agg.result"}
!37 = distinct !{!37, !"D"}
!38 = distinct !{!38, !39, !"E: %agg.result"}
!39 = distinct !{!39, !"E"}
!40 = distinct !{!40, !41, !"F: %agg.result"}
!41 = distinct !{!41, !"F"}
!42 = !{!43, !45, !47}
!43 = distinct !{!43, !44, !"D: %agg.result"}
!44 = distinct !{!44, !"D"}
!45 = distinct !{!45, !46, !"E: %agg.result"}
!46 = distinct !{!46, !"E"}
!47 = distinct !{!47, !48, !"F: %agg.result"}
!48 = distinct !{!48, !"F"}
!49 = !{!50, !52, !54}
!50 = distinct !{!50, !51, !"D: %agg.result"}
!51 = distinct !{!51, !"D"}
!52 = distinct !{!52, !53, !"E: %agg.result"}
!53 = distinct !{!53, !"E"}
!54 = distinct !{!54, !55, !"F: %agg.result"}
!55 = distinct !{!55, !"F"}
!56 = !{!57, !59, !61}
!57 = distinct !{!57, !58, !"D: %agg.result"}
!58 = distinct !{!58, !"D"}
!59 = distinct !{!59, !60, !"E: %agg.result"}
!60 = distinct !{!60, !"E"}
!61 = distinct !{!61, !62, !"F: %agg.result"}
!62 = distinct !{!62, !"F"}
!63 = !{!64, !66, !68}
!64 = distinct !{!64, !65, !"A: %agg.result"}
!65 = distinct !{!65, !"A"}
!66 = distinct !{!66, !67, !"B: %agg.result"}
!67 = distinct !{!67, !"B"}
!68 = distinct !{!68, !69, !"C: %agg.result"}
!69 = distinct !{!69, !"C"}
!70 = !{!71, !73, !75}
!71 = distinct !{!71, !72, !"A: %agg.result"}
!72 = distinct !{!72, !"A"}
!73 = distinct !{!73, !74, !"B: %agg.result"}
!74 = distinct !{!74, !"B"}
!75 = distinct !{!75, !76, !"C: %agg.result"}
!76 = distinct !{!76, !"C"}
!77 = !{!78, !80, !82}
!78 = distinct !{!78, !79, !"A: %agg.result"}
!79 = distinct !{!79, !"A"}
!80 = distinct !{!80, !81, !"B: %agg.result"}
!81 = distinct !{!81, !"B"}
!82 = distinct !{!82, !83, !"C: %agg.result"}
!83 = distinct !{!83, !"C"}
!84 = !{!85, !87, !89}
!85 = distinct !{!85, !86, !"A: %agg.result"}
!86 = distinct !{!86, !"A"}
!87 = distinct !{!87, !88, !"B: %agg.result"}
!88 = distinct !{!88, !"B"}
!89 = distinct !{!89, !90, !"C: %agg.result"}
!90 = distinct !{!90, !"C"}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.mustprogress"}
!93 = !{!"llvm.loop.itercount.range", i64 4}
!94 = distinct !{!94, !92, !95}
!95 = !{!"llvm.loop.hint.aie-safe-to-ignore-memory-deps", i64 1}
