; NOTE: Assertions have been autogenerated by utils/update_ore_test_checks.py UTC_ARGS: --update-llc-checks
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2ps %s -o - | FileCheck %s --check-prefix=ASM

; RUN: llc -mtriple=aie2ps -pass-remarks-output=- \
; RUN:   -pass-remarks-filter='pipeliner' %s -o /dev/null | FileCheck %s --check-prefix=REMARKS
; Function Attrs: mustprogress
define weak_odr dso_local void @nested_vmac_loop(ptr noalias %arg, ptr noalias %arg1, ptr noalias %arg2, ptr noalias %arg3, ptr noalias %arg4, ptr nonnull align 32 dereferenceable(200) %arg5) local_unnamed_addr #0 {
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            canPipelineLoop
; REMARKS-NEXT: Function:        nested_vmac_loop
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Disabled by Pragma.
; REMARKS-NEXT: ...
; REMARKS: --- !Missed
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            canPipelineLoop
; REMARKS-NEXT: Function:        nested_vmac_loop
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Failed to pipeline loop
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            canPipelineLoop
; REMARKS-NEXT: Function:        nested_vmac_loop
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          'Not a single basic block: '
; REMARKS-NEXT:   - NumBlocks:       '3'
; REMARKS-NEXT: ...
; REMARKS: --- !Missed
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            canPipelineLoop
; REMARKS-NEXT: Function:        nested_vmac_loop
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Failed to pipeline loop
; REMARKS-NEXT: ...
; REMARKS: --- !Passed
; REMARKS-NEXT: Pass:            pipeliner
; REMARKS-NEXT: Name:            schedule
; REMARKS-NEXT: Function:        nested_vmac_loop
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - String:          Schedule found
; REMARKS-NEXT:   - Pipeliner:       postpipeliner
; REMARKS-NEXT:   - II:              '32'
; REMARKS-NEXT:   - NS:              '2'
; REMARKS-NEXT:   - Loop:            bb.3.bb102
; REMARKS-NEXT:   - Prologue:        bb.2.bb61
; REMARKS-NEXT:   - PrologueBundles: '38'
; REMARKS-NEXT:   - Epilogue:        bb.4.bb90
; REMARKS-NEXT:   - EpilogueBundles: '49'
; REMARKS-NEXT: ...
; ASM-LABEL: nested_vmac_loop:
; ASM:       // %bb.0: // %bb
; ASM-NEXT:    mova dj0, #36; nopx
; ASM-NEXT:    lda r0, [p5, dj0]
; ASM-NEXT:    nop
; ASM-NEXT:    nop
; ASM-NEXT:    nop
; ASM-NEXT:    nop
; ASM-NEXT:    nop
; ASM-NEXT:    movx r2, #0
; ASM-NEXT:    ge r2, r2, r0
; ASM-NEXT:    jnz r2, #.LBB0_5
; ASM-NEXT:    nop // Delay Slot 5
; ASM-NEXT:    nop // Delay Slot 4
; ASM-NEXT:    nop // Delay Slot 3
; ASM-NEXT:    nop // Delay Slot 2
; ASM-NEXT:    mov r5, r8 // Delay Slot 1
; ASM-NEXT:  // %bb.1: // %bb12
; ASM-NEXT:    mova m0, #12
; ASM-NEXT:    padda [p5], m0
; ASM-NEXT:    lda r27, [p5], #-4; mov m0, #184
; ASM-NEXT:    lda r2, [p5], m0; mov dj1, #-144
; ASM-NEXT:    lda m2, [p5, dj1]; mov dj0, #-48
; ASM-NEXT:    lda m0, [p5, dj0]
; ASM-NEXT:    lda m1, [p5, #-20]
; ASM-NEXT:    lda r6, [p5, #0]
; ASM-NEXT:    lda dn5, [p5, #-28]
; ASM-NEXT:    lda dc1, [p5, #-16]
; ASM-NEXT:    lda dj5, [p5, #-24]
; ASM-NEXT:    lda dc5, [p5, #-12]; mov dj0, #-64
; ASM-NEXT:    lda dn0, [p5, dj0]; mov dj1, #-152
; ASM-NEXT:    lda r1, [p5, dj1]
; ASM-NEXT:    mova dj1, #-56
; ASM-NEXT:    lda dn4, [p5, dj1]; mov dj0, #-60
; ASM-NEXT:    lda dj0, [p5, dj0]
; ASM-NEXT:    mova dj1, #-52
; ASM-NEXT:    lda dj4, [p5, dj1]
; ASM-NEXT:    mova dj1, #-36
; ASM-NEXT:    lda dn1, [p5, dj1]
; ASM-NEXT:    mova dj1, #-44; movx r22, #0
; ASM-NEXT:    lda dc0, [p5, dj1]; movx r4, #2; mov r18, #972
; ASM-NEXT:    mova dj1, #-40; lshl r2, r2, r4; mov r3, #0
; ASM-NEXT:    lda dc4, [p5, dj1]; sel.eqz r16, r22, r2, r27; mov r24, r22
; ASM-NEXT:    lda dj1, [p5, #-32]; or r25, r22, r22; mov m3, r16
; ASM-NEXT:    padda [p1], m3; movs p2, p0; eqz r20, r6; mov r4, #22
; ASM-NEXT:    mova r6, #23; movs p5, p4; movx r2, #106; mov p0, p1
; ASM-NEXT:    mova m3, #-288; movs p1, p2; or r16, r20, r18; mov p2, p3
; ASM-NEXT:  .LBB0_2: // %bb61
; ASM-NEXT:    // =>This Loop Header: Depth=1
; ASM-NEXT:    // Child Loop BB0_3 Depth 2
; ASM-NEXT:    vlda bmhh7, [p3, #192]
; ASM-NEXT:    vlda bmhl7, [p3, #128]
; ASM-NEXT:    vlda bmlh7, [p3, #64]
; ASM-NEXT:    vlda bmll7, [p3], m2
; ASM-NEXT:    vlda bmhh3, [p4, #192]
; ASM-NEXT:    vlda bmhl3, [p4, #128]
; ASM-NEXT:    vlda bmlh3, [p4, #64]
; ASM-NEXT:    vlda bmll3, [p4], m2
; ASM-NEXT:    vlda bmhh6, [p3, #192]
; ASM-NEXT:    vlda bmhl6, [p3, #128]
; ASM-NEXT:    vlda bmlh6, [p3, #64]
; ASM-NEXT:    vlda bmll6, [p3], m2
; ASM-NEXT:    vlda bmhh2, [p4, #192]
; ASM-NEXT:    vlda bmhl2, [p4, #128]
; ASM-NEXT:    vlda bmlh2, [p4, #64]
; ASM-NEXT:    vlda bmll2, [p4], m2
; ASM-NEXT:    vlda bmhh5, [p3, #192]
; ASM-NEXT:    vlda bmhl5, [p3, #128]
; ASM-NEXT:    vlda bmlh5, [p3, #64]
; ASM-NEXT:    vlda bmll5, [p3], m2
; ASM-NEXT:    vlda bmhh1, [p4, #192]
; ASM-NEXT:    vlda bmhl1, [p4, #128]
; ASM-NEXT:    vlda bmlh1, [p4, #64]
; ASM-NEXT:    vlda bmll1, [p4], m2
; ASM-NEXT:    vlda bmhh4, [p3, #192]
; ASM-NEXT:    vlda bmhl4, [p3, #128]
; ASM-NEXT:    vlda bmlh4, [p3, #64]
; ASM-NEXT:    vlda bmll4, [p3, #0]
; ASM-NEXT:    vlda bmhh0, [p4, #192]; vldb.fill [p1, lf1, r25]
; ASM-NEXT:    vlda bmhl0, [p4, #128]; vldb.pop ex6, [p1, lf1, r25]
; ASM-NEXT:    vlda bmlh0, [p4, #64]; vldb.pop ex4, [p1, lf1, r25]
; ASM-NEXT:    vlda bmll0, [p4, #0]; vldb.pop ex2, [p1, lf1, r25]
; ASM-NEXT:    vlda.fill [p0, lf0, r24]; vldb.pop ex0, [p1, lf1, r25]
; ASM-NEXT:    vlda.pop ex6, [p0, lf0, r24]
; ASM-NEXT:    vlda.pop ex5, [p0, lf0, r24]
; ASM-NEXT:    vlda.pop ex1, [p0, lf0, r24]; movxm ls, #.LBB0_3
; ASM-NEXT:    vlda.pop ex3, [p0, lf0, r24]; movxm le, #.L_LEnd0
; ASM-NEXT:    add.nc lc, r1, #-1; mov r8, r16
; ASM-NEXT:  .LBB0_3: // %bb102
; ASM-NEXT:    // Parent Loop BB0_2 Depth=1
; ASM-NEXT:    // => This Inner Loop Header: Depth=2
; ASM-NEXT:    nopa ; nopxm
; ASM-NEXT:    nop
; ASM-NEXT:    vshuffle ex10, ex6, ex0, r2
; ASM-NEXT:    vshuffle ex8, ex4, ex0, r2
; ASM-NEXT:    vshuffle ex4, ex6, ex5, r4
; ASM-NEXT:    vshuffle ex6, ex6, ex5, r6
; ASM-NEXT:    padds [p1], m3; or r25, r3, r3; vshuffle ex5, ex1, ex3, r4
; ASM-NEXT:    vldb.fill [p1, lf1, r25]; vshuffle ex7, ex1, ex3, r6
; ASM-NEXT:    vldb.pop ex6, [p1, lf1, r25]; vshuffle ex9, ex0, ex0, r2; vmac.f dm7, dm7, ex10, ey2, ey3, r8
; ASM-NEXT:    vldb.pop ex2, [p1, lf1, r25]
; ASM-NEXT:    vldb.pop ex11, [p1, lf1, r25]; vshuffle ex11, ex2, ex0, r2; vmac.f dm4, dm4, ex9, ey2, ey3, r8
; ASM-NEXT:    vlda.fill [p0, lf0, r24]; vldb.pop.3d ex9, [p1, lf1, r25, d0]
; ASM-NEXT:    vlda.pop ex0, [p0, lf0, r24]; vmac.f dm5, dm5, ex11, ey2, ey3, r8
; ASM-NEXT:    vlda.pop ex5, [p0, lf0, r24]
; ASM-NEXT:    vlda.pop ex1, [p0, lf0, r24]; vmac.f dm6, dm6, ex8, ey2, ey3, r8
; ASM-NEXT:    vlda.pop.3d ex3, [p0, lf0, r24, d1]
; ASM-NEXT:    vshuffle ex10, ex6, ex0, r2
; ASM-NEXT:    vshuffle ex6, ex2, ex0, r2
; ASM-NEXT:    vshuffle ex2, ex11, ex0, r2
; ASM-NEXT:    vshuffle ex9, ex9, ex0, r2
; ASM-NEXT:    nop
; ASM-NEXT:    vshuffle ex4, ex0, ex5, r4
; ASM-NEXT:    vldb.fill [p1, lf1, r25]; vshuffle ex0, ex0, ex5, r6
; ASM-NEXT:    vldb.pop ex6, [p1, lf1, r25]; vshuffle ex5, ex1, ex3, r4
; ASM-NEXT:    vldb.pop ex4, [p1, lf1, r25]; vshuffle ex1, ex1, ex3, r6
; ASM-NEXT:    vldb.pop ex2, [p1, lf1, r25]; vmac.f dm3, dm3, ex10, ey2, ey0, r8
; ASM-NEXT:    vlda.fill [p0, lf0, r24]; vldb.pop ex0, [p1, lf1, r25]
; ASM-NEXT:    vlda.pop ex6, [p0, lf0, r24]; vmac.f dm2, dm2, ex6, ey2, ey0, r8
; ASM-NEXT:    vlda.pop ex5, [p0, lf0, r24]
; ASM-NEXT:    vlda.pop ex1, [p0, lf0, r24]; vmac.f dm0, dm0, ex9, ey2, ey0, r8
; ASM-NEXT:    vlda.pop ex3, [p0, lf0, r24]
; ASM-NEXT:  .L_LEnd0:
; ASM-NEXT:    nopa ; nopb ; nops ; movx r8, #972; nopm ; vmac.f dm1, dm1, ex2, ey2, ey0, r8
; ASM-NEXT:  // %bb.4: // %bb90
; ASM-NEXT:    // in Loop: Header=BB0_2 Depth=1
; ASM-NEXT:    padda [p3], m2; paddb [p4], m2; add r0, r0, #-1; nopm ; nops
; ASM-NEXT:    nop
; ASM-NEXT:    vshuffle ex10, ex6, ex0, r2
; ASM-NEXT:    vshuffle ex8, ex4, ex0, r2
; ASM-NEXT:    vshuffle ex4, ex6, ex5, r4
; ASM-NEXT:    vshuffle ex6, ex6, ex5, r6
; ASM-NEXT:    padds [p1], m3; or r25, r3, r3; vshuffle ex5, ex1, ex3, r4
; ASM-NEXT:    vldb.fill [p1, lf1, r25]; vshuffle ex7, ex1, ex3, r6
; ASM-NEXT:    vldb.pop ex6, [p1, lf1, r25]; vshuffle ex9, ex0, ex0, r2; vmac.f dm7, dm7, ex10, ey2, ey3, r8
; ASM-NEXT:    vldb.pop ex2, [p1, lf1, r25]
; ASM-NEXT:    vldb.pop ex11, [p1, lf1, r25]; vshuffle ex11, ex2, ex0, r2; vmac.f dm4, dm4, ex9, ey2, ey3, r8
; ASM-NEXT:    vlda.fill [p0, lf0, r24]; vldb.pop.3d ex9, [p1, lf1, r25, d0]
; ASM-NEXT:    vlda.pop ex0, [p0, lf0, r24]; vmac.f dm5, dm5, ex11, ey2, ey3, r8
; ASM-NEXT:    vlda.pop ex5, [p0, lf0, r24]
; ASM-NEXT:    vlda.pop ex1, [p0, lf0, r24]; vmac.f dm6, dm6, ex8, ey2, ey3, r8
; ASM-NEXT:    vlda.pop.3d ex3, [p0, lf0, r24, d1]
; ASM-NEXT:    vst bmhh7, [p2, #192]; vshuffle ex10, ex6, ex0, r2
; ASM-NEXT:    vst bmhl7, [p2, #128]; vshuffle ex6, ex2, ex0, r2
; ASM-NEXT:    vst bmlh7, [p2, #64]; vshuffle ex2, ex11, ex0, r2
; ASM-NEXT:    vst bmll7, [p2], m2; vshuffle ex9, ex9, ex0, r2
; ASM-NEXT:    nop
; ASM-NEXT:    vst bmhh6, [p2, #192]; vshuffle ex4, ex0, ex5, r4
; ASM-NEXT:    vst bmhl6, [p2, #128]; vshuffle ex0, ex0, ex5, r6
; ASM-NEXT:    vst bmlh6, [p2, #64]; vshuffle ex5, ex1, ex3, r4
; ASM-NEXT:    vst bmll6, [p2], m2; vshuffle ex1, ex1, ex3, r6
; ASM-NEXT:    vst bmhh5, [p2, #192]; vmac.f dm3, dm3, ex10, ey2, ey0, r8
; ASM-NEXT:    vst bmhl5, [p2, #128]
; ASM-NEXT:    vst bmlh5, [p2, #64]; vmac.f dm2, dm2, ex6, ey2, ey0, r8
; ASM-NEXT:    vst bmll5, [p2], m2
; ASM-NEXT:    vst bmhh4, [p2, #192]; vmac.f dm0, dm0, ex9, ey2, ey0, r8
; ASM-NEXT:    vst bmhl4, [p2, #128]
; ASM-NEXT:    vst bmlh4, [p2, #64]; movx r8, #972; vmac.f dm1, dm1, ex2, ey2, ey0, r8
; ASM-NEXT:    vst bmhh3, [p5, #192]
; ASM-NEXT:    vst bmhl3, [p5, #128]
; ASM-NEXT:    vst bmlh3, [p5, #64]
; ASM-NEXT:    vst bmll3, [p5], m2
; ASM-NEXT:    vst bmhh2, [p5, #192]
; ASM-NEXT:    vst bmhl2, [p5, #128]
; ASM-NEXT:    vst bmlh2, [p5, #64]
; ASM-NEXT:    vst bmll2, [p5], m2
; ASM-NEXT:    vst bmll4, [p2], m2
; ASM-NEXT:    vst bmhh1, [p5, #192]
; ASM-NEXT:    vst bmhl1, [p5, #128]
; ASM-NEXT:    vst bmlh1, [p5, #64]; jnz r0, #.LBB0_2
; ASM-NEXT:    vst bmll1, [p5], m2 // Delay Slot 5
; ASM-NEXT:    vst bmhh0, [p5, #192] // Delay Slot 4
; ASM-NEXT:    vst bmhl0, [p5, #128] // Delay Slot 3
; ASM-NEXT:    vst bmlh0, [p5, #64] // Delay Slot 2
; ASM-NEXT:    vst bmll0, [p5], m2 // Delay Slot 1
; ASM-NEXT:  .LBB0_5: // %bb337
; ASM-NEXT:    ret lr
; ASM-NEXT:    nop // Delay Slot 5
; ASM-NEXT:    nop // Delay Slot 4
; ASM-NEXT:    nop // Delay Slot 3
; ASM-NEXT:    nop // Delay Slot 2
; ASM-NEXT:    mov r8, r5 // Delay Slot 1
bb:
  %getelementptr = getelementptr inbounds nuw i8, ptr %arg5, i20 12
  %load = load i32, ptr %getelementptr, align 4, !tbaa !3
  %getelementptr6 = getelementptr inbounds nuw i8, ptr %arg5, i20 8
  %load7 = load i32, ptr %getelementptr6, align 8
  %getelementptr8 = getelementptr inbounds nuw i8, ptr %arg5, i20 192
  %load9 = load i32, ptr %getelementptr8, align 32, !tbaa !12
  %getelementptr10 = getelementptr inbounds nuw i8, ptr %arg5, i20 36
  %load11 = load i32, ptr %getelementptr10, align 4, !tbaa !13, !noalias !14
  %icmp = icmp sgt i32 %load11, 0
  br i1 %icmp, label %bb12, label %bb337

bb12:                                             ; preds = %bb
  %icmp13 = icmp eq i32 %load9, 0
  %zext = zext i1 %icmp13 to i32
  %icmp14 = icmp eq i32 %load, 0
  %shl = shl i32 %load7, 2
  %select = select i1 %icmp14, i32 0, i32 %shl
  %trunc = trunc i32 %select to i20
  %getelementptr15 = getelementptr inbounds nuw i8, ptr %arg1, i20 %trunc
  %addrspacecast = addrspacecast ptr %getelementptr15 to ptr addrspace(6)
  %addrspacecast16 = addrspacecast ptr %arg to ptr addrspace(5)
  %getelementptr17 = getelementptr inbounds nuw i8, ptr %arg5, i20 48
  %or = or disjoint i32 %zext, 972
  %getelementptr18 = getelementptr inbounds nuw i8, ptr %arg5, i20 40
  %getelementptr19 = getelementptr inbounds nuw i8, ptr %arg5, i20 128
  %getelementptr20 = getelementptr inbounds nuw i8, ptr %arg5, i20 144
  %getelementptr21 = getelementptr inbounds nuw i8, ptr %arg5, i20 148
  %getelementptr22 = getelementptr inbounds nuw i8, ptr %arg5, i20 132
  %getelementptr23 = getelementptr inbounds nuw i8, ptr %arg5, i20 136
  %getelementptr24 = getelementptr inbounds nuw i8, ptr %arg5, i20 152
  %getelementptr25 = getelementptr inbounds nuw i8, ptr %arg5, i20 140
  %getelementptr26 = getelementptr inbounds nuw i8, ptr %arg5, i20 156
  %getelementptr27 = getelementptr inbounds nuw i8, ptr %arg5, i20 172
  %getelementptr28 = getelementptr inbounds nuw i8, ptr %arg5, i20 176
  %getelementptr29 = getelementptr inbounds nuw i8, ptr %arg5, i20 160
  %getelementptr30 = getelementptr inbounds nuw i8, ptr %arg5, i20 164
  %getelementptr31 = getelementptr inbounds nuw i8, ptr %arg5, i20 180
  %getelementptr32 = getelementptr inbounds nuw i8, ptr %arg5, i20 168
  %load33 = load i32, ptr %getelementptr17, align 16, !tbaa !18, !noalias !14
  %load34 = load i32, ptr %getelementptr18, align 8, !tbaa !19, !noalias !14
  %icmp35 = icmp sgt i32 %load34, 2
  tail call void @llvm.assume(i1 %icmp35)
  %load36 = load i32, ptr %getelementptr20, align 16, !tbaa !20, !noalias !14
  %load37 = load i32, ptr %getelementptr19, align 32, !tbaa !21, !noalias !14
  %load38 = load i32, ptr %getelementptr22, align 4, !tbaa !22, !noalias !14
  %load39 = load i32, ptr %getelementptr23, align 8, !tbaa !23, !noalias !14
  %load40 = load i32, ptr %getelementptr25, align 4, !tbaa !24, !noalias !14
  %trunc41 = trunc i32 %load36 to i20
  %trunc42 = trunc i32 %load37 to i20
  %trunc43 = trunc i32 %load38 to i20
  %trunc44 = trunc i32 %load39 to i20
  %trunc45 = trunc i32 %load40 to i20
  %load46 = load i32, ptr %getelementptr27, align 4, !tbaa !20, !noalias !14
  %load47 = load i32, ptr %getelementptr26, align 4, !tbaa !21, !noalias !14
  %load48 = load i32, ptr %getelementptr29, align 32, !tbaa !22, !noalias !14
  %load49 = load i32, ptr %getelementptr30, align 4, !tbaa !23, !noalias !14
  %load50 = load i32, ptr %getelementptr32, align 8, !tbaa !24, !noalias !14
  %trunc51 = trunc i32 %load46 to i20
  %trunc52 = trunc i32 %load47 to i20
  %trunc53 = trunc i32 %load48 to i20
  %trunc54 = trunc i32 %load49 to i20
  %trunc55 = trunc i32 %load50 to i20
  %trunc56 = trunc i32 %load33 to i20
  %load57 = load i32, ptr %getelementptr21, align 4, !noalias !14
  %load58 = load i32, ptr %getelementptr24, align 8, !noalias !14
  %load59 = load i32, ptr %getelementptr28, align 16, !noalias !14
  %load60 = load i32, ptr %getelementptr31, align 4, !noalias !14
  br label %bb61

bb61:                                             ; preds = %bb90, %bb12
  %phi = phi i32 [ %load60, %bb12 ], [ %zext311, %bb90 ]
  %phi62 = phi i32 [ %load59, %bb12 ], [ %zext309, %bb90 ]
  %phi63 = phi i32 [ %load58, %bb12 ], [ %zext257, %bb90 ]
  %phi64 = phi i32 [ %load57, %bb12 ], [ %zext255, %bb90 ]
  %phi65 = phi ptr [ %arg3, %bb12 ], [ %getelementptr91, %bb90 ]
  %phi66 = phi ptr [ %arg4, %bb12 ], [ %getelementptr92, %bb90 ]
  %phi67 = phi ptr [ %arg3, %bb12 ], [ %getelementptr96, %bb90 ]
  %phi68 = phi ptr [ %arg4, %bb12 ], [ %getelementptr100, %bb90 ]
  %phi69 = phi i32 [ 0, %bb12 ], [ %add, %bb90 ]
  %phi70 = phi <32 x i32> [ poison, %bb12 ], [ %extractvalue306, %bb90 ]
  %phi71 = phi i32 [ 0, %bb12 ], [ %extractvalue307, %bb90 ]
  %phi72 = phi <32 x i32> [ poison, %bb12 ], [ %extractvalue252, %bb90 ]
  %phi73 = phi i32 [ 0, %bb12 ], [ %extractvalue253, %bb90 ]
  %phi74 = phi ptr addrspace(6) [ %addrspacecast, %bb12 ], [ %extractvalue305, %bb90 ]
  %phi75 = phi ptr addrspace(5) [ %addrspacecast16, %bb12 ], [ %extractvalue251, %bb90 ]
  %load76 = load <64 x float>, ptr %phi65, align 64, !tbaa !25, !noalias !14
  %getelementptr77 = getelementptr inbounds i8, ptr %phi65, i20 %trunc56
  %load78 = load <64 x float>, ptr %getelementptr77, align 64, !tbaa !25, !noalias !14
  %getelementptr79 = getelementptr inbounds i8, ptr %getelementptr77, i20 %trunc56
  %load80 = load <64 x float>, ptr %getelementptr79, align 64, !tbaa !25, !noalias !14
  %getelementptr81 = getelementptr inbounds i8, ptr %getelementptr79, i20 %trunc56
  %load82 = load <64 x float>, ptr %getelementptr81, align 64, !tbaa !25, !noalias !14
  %load83 = load <64 x float>, ptr %phi66, align 64, !tbaa !25, !noalias !14
  %getelementptr84 = getelementptr inbounds i8, ptr %phi66, i20 %trunc56
  %load85 = load <64 x float>, ptr %getelementptr84, align 64, !tbaa !25, !noalias !14
  %getelementptr86 = getelementptr inbounds i8, ptr %getelementptr84, i20 %trunc56
  %load87 = load <64 x float>, ptr %getelementptr86, align 64, !tbaa !25, !noalias !14
  %getelementptr88 = getelementptr inbounds i8, ptr %getelementptr86, i20 %trunc56
  %load89 = load <64 x float>, ptr %getelementptr88, align 64, !tbaa !25, !noalias !14
  br label %bb102

bb90:                                             ; preds = %bb102
  %getelementptr91 = getelementptr inbounds i8, ptr %getelementptr81, i20 %trunc56
  %getelementptr92 = getelementptr inbounds i8, ptr %getelementptr88, i20 %trunc56
  store <64 x float> %call219, ptr %phi67, align 64, !tbaa !25, !noalias !14
  %getelementptr93 = getelementptr inbounds i8, ptr %phi67, i20 %trunc56
  store <64 x float> %call220, ptr %getelementptr93, align 64, !tbaa !25, !noalias !14
  %getelementptr94 = getelementptr inbounds i8, ptr %getelementptr93, i20 %trunc56
  store <64 x float> %call221, ptr %getelementptr94, align 64, !tbaa !25, !noalias !14
  %getelementptr95 = getelementptr inbounds i8, ptr %getelementptr94, i20 %trunc56
  store <64 x float> %call222, ptr %getelementptr95, align 64, !tbaa !25, !noalias !14
  %getelementptr96 = getelementptr inbounds i8, ptr %getelementptr95, i20 %trunc56
  store <64 x float> %call331, ptr %phi68, align 64, !tbaa !25, !noalias !14
  %getelementptr97 = getelementptr inbounds i8, ptr %phi68, i20 %trunc56
  store <64 x float> %call332, ptr %getelementptr97, align 64, !tbaa !25, !noalias !14
  %getelementptr98 = getelementptr inbounds i8, ptr %getelementptr97, i20 %trunc56
  store <64 x float> %call333, ptr %getelementptr98, align 64, !tbaa !25, !noalias !14
  %getelementptr99 = getelementptr inbounds i8, ptr %getelementptr98, i20 %trunc56
  store <64 x float> %call334, ptr %getelementptr99, align 64, !tbaa !25, !noalias !14
  %getelementptr100 = getelementptr inbounds i8, ptr %getelementptr99, i20 %trunc56
  %add = add nuw nsw i32 %phi69, 1
  %icmp101 = icmp eq i32 %add, %load11
  br i1 %icmp101, label %bb337, label %bb61, !llvm.loop !26

bb102:                                            ; preds = %bb102, %bb61
  %phi103 = phi i32 [ %phi, %bb61 ], [ %zext311, %bb102 ]
  %phi104 = phi i32 [ %phi62, %bb61 ], [ %zext309, %bb102 ]
  %phi105 = phi i32 [ %phi63, %bb61 ], [ %zext257, %bb102 ]
  %phi106 = phi i32 [ %phi64, %bb61 ], [ %zext255, %bb102 ]
  %phi107 = phi <64 x float> [ %load76, %bb61 ], [ %call219, %bb102 ]
  %phi108 = phi <64 x float> [ %load78, %bb61 ], [ %call220, %bb102 ]
  %phi109 = phi <64 x float> [ %load80, %bb61 ], [ %call221, %bb102 ]
  %phi110 = phi <64 x float> [ %load82, %bb61 ], [ %call222, %bb102 ]
  %phi111 = phi <64 x float> [ %load83, %bb61 ], [ %call331, %bb102 ]
  %phi112 = phi <64 x float> [ %load85, %bb61 ], [ %call332, %bb102 ]
  %phi113 = phi <64 x float> [ %load87, %bb61 ], [ %call333, %bb102 ]
  %phi114 = phi <64 x float> [ %load89, %bb61 ], [ %call334, %bb102 ]
  %phi115 = phi i32 [ %or, %bb61 ], [ 972, %bb102 ]
  %phi116 = phi i32 [ 0, %bb61 ], [ %add335, %bb102 ]
  %phi117 = phi <32 x i32> [ %phi70, %bb61 ], [ %extractvalue306, %bb102 ]
  %phi118 = phi i32 [ %phi71, %bb61 ], [ %extractvalue307, %bb102 ]
  %phi119 = phi <32 x i32> [ %phi72, %bb61 ], [ %extractvalue252, %bb102 ]
  %phi120 = phi i32 [ %phi73, %bb61 ], [ %extractvalue253, %bb102 ]
  %phi121 = phi ptr addrspace(6) [ %phi74, %bb61 ], [ %extractvalue305, %bb102 ]
  %phi122 = phi ptr addrspace(5) [ %phi75, %bb61 ], [ %extractvalue251, %bb102 ]
  %call = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) %phi122, <32 x i32> %phi119, i32 %phi120)
  %extractvalue = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %call, 0
  %extractvalue123 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %call, 1
  %extractvalue124 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %call, 2
  %call125 = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5) %extractvalue, <32 x i32> %extractvalue123, i32 %extractvalue124)
  %extractvalue126 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call125, 0
  %extractvalue127 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call125, 1
  %extractvalue128 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call125, 2
  %extractvalue129 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call125, 3
  %extractvalue130 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call125, 4
  %extractvalue131 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call125, 5
  %call132 = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5) %extractvalue126, <32 x i32> %extractvalue127, i32 %extractvalue128)
  %extractvalue133 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call132, 0
  %extractvalue134 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call132, 1
  %extractvalue135 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call132, 2
  %extractvalue136 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call132, 3
  %extractvalue137 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call132, 4
  %extractvalue138 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call132, 5
  %call139 = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5) %extractvalue133, <32 x i32> %extractvalue134, i32 %extractvalue135)
  %extractvalue140 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call139, 0
  %extractvalue141 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call139, 1
  %extractvalue142 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call139, 2
  %extractvalue143 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call139, 3
  %extractvalue144 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call139, 4
  %extractvalue145 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call139, 5
  %call146 = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5) %extractvalue140, <32 x i32> %extractvalue141, i32 %extractvalue142)
  %extractvalue147 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call146, 0
  %extractvalue148 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call146, 1
  %extractvalue149 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call146, 3
  %extractvalue150 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call146, 4
  %extractvalue151 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call146, 5
  %addrspacecast152 = addrspacecast ptr addrspace(5) %extractvalue147 to ptr
  %getelementptr153 = getelementptr inbounds i8, ptr %addrspacecast152, i20 -288
  %addrspacecast154 = addrspacecast ptr %getelementptr153 to ptr addrspace(5)
  %call155 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue129, <2 x i32> %extractvalue130, <2 x i32> %extractvalue131, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue156 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call155, 0
  %extractvalue157 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call155, 1
  %extractvalue158 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call155, 2
  %call159 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue136, <2 x i32> %extractvalue137, <2 x i32> %extractvalue138, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue160 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call159, 0
  %extractvalue161 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call159, 1
  %extractvalue162 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call159, 2
  %call163 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue143, <2 x i32> %extractvalue144, <2 x i32> %extractvalue145, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue164 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call163, 0
  %extractvalue165 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call163, 1
  %extractvalue166 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call163, 2
  %call167 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue149, <2 x i32> %extractvalue150, <2 x i32> %extractvalue151, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue168 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call167, 0
  %extractvalue169 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call167, 1
  %extractvalue170 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call167, 2
  %call171 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) %phi121, <32 x i32> %phi117, i32 %phi118)
  %extractvalue172 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %call171, 0
  %extractvalue173 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %call171, 1
  %extractvalue174 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %call171, 2
  %call175 = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) %extractvalue172, <32 x i32> %extractvalue173, i32 %extractvalue174)
  %extractvalue176 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call175, 0
  %extractvalue177 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call175, 1
  %extractvalue178 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call175, 2
  %extractvalue179 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call175, 3
  %extractvalue180 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call175, 4
  %extractvalue181 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call175, 5
  %call182 = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) %extractvalue176, <32 x i32> %extractvalue177, i32 %extractvalue178)
  %extractvalue183 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call182, 0
  %extractvalue184 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call182, 1
  %extractvalue185 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call182, 2
  %extractvalue186 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call182, 3
  %extractvalue187 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call182, 4
  %extractvalue188 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call182, 5
  %call189 = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) %extractvalue183, <32 x i32> %extractvalue184, i32 %extractvalue185)
  %extractvalue190 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call189, 0
  %extractvalue191 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call189, 1
  %extractvalue192 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call189, 2
  %extractvalue193 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call189, 3
  %extractvalue194 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call189, 4
  %extractvalue195 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call189, 5
  %call196 = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) %extractvalue190, <32 x i32> %extractvalue191, i32 %extractvalue192)
  %extractvalue197 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call196, 0
  %extractvalue198 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call196, 1
  %extractvalue199 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call196, 2
  %extractvalue200 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call196, 3
  %extractvalue201 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call196, 4
  %extractvalue202 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call196, 5
  %call203 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue179, <2 x i32> %extractvalue180, <2 x i32> %extractvalue181, <16 x i32> %extractvalue186, <2 x i32> %extractvalue187, <2 x i32> %extractvalue188, i32 22)
  %extractvalue204 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call203, 0
  %extractvalue205 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call203, 1
  %extractvalue206 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call203, 2
  %call207 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue179, <2 x i32> %extractvalue180, <2 x i32> %extractvalue181, <16 x i32> %extractvalue186, <2 x i32> %extractvalue187, <2 x i32> %extractvalue188, i32 23)
  %extractvalue208 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call207, 0
  %extractvalue209 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call207, 1
  %extractvalue210 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call207, 2
  %call211 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue193, <2 x i32> %extractvalue194, <2 x i32> %extractvalue195, <16 x i32> %extractvalue200, <2 x i32> %extractvalue201, <2 x i32> %extractvalue202, i32 22)
  %extractvalue212 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call211, 0
  %extractvalue213 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call211, 1
  %extractvalue214 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call211, 2
  %call215 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue193, <2 x i32> %extractvalue194, <2 x i32> %extractvalue195, <16 x i32> %extractvalue200, <2 x i32> %extractvalue201, <2 x i32> %extractvalue202, i32 23)
  %extractvalue216 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call215, 0
  %extractvalue217 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call215, 1
  %extractvalue218 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call215, 2
  %call219 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue156, <2 x i32> %extractvalue157, <2 x i32> %extractvalue158, <16 x i32> %extractvalue204, <16 x i32> %extractvalue212, <16 x i32> %extractvalue208, <16 x i32> %extractvalue216, <2 x i32> %extractvalue205, <2 x i32> %extractvalue213, <2 x i32> %extractvalue209, <2 x i32> %extractvalue217, <2 x i32> %extractvalue206, <2 x i32> %extractvalue214, <2 x i32> %extractvalue210, <2 x i32> %extractvalue218, <64 x float> %phi107, i32 %phi115)
  %call220 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue160, <2 x i32> %extractvalue161, <2 x i32> %extractvalue162, <16 x i32> %extractvalue204, <16 x i32> %extractvalue212, <16 x i32> %extractvalue208, <16 x i32> %extractvalue216, <2 x i32> %extractvalue205, <2 x i32> %extractvalue213, <2 x i32> %extractvalue209, <2 x i32> %extractvalue217, <2 x i32> %extractvalue206, <2 x i32> %extractvalue214, <2 x i32> %extractvalue210, <2 x i32> %extractvalue218, <64 x float> %phi108, i32 %phi115)
  %call221 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue164, <2 x i32> %extractvalue165, <2 x i32> %extractvalue166, <16 x i32> %extractvalue204, <16 x i32> %extractvalue212, <16 x i32> %extractvalue208, <16 x i32> %extractvalue216, <2 x i32> %extractvalue205, <2 x i32> %extractvalue213, <2 x i32> %extractvalue209, <2 x i32> %extractvalue217, <2 x i32> %extractvalue206, <2 x i32> %extractvalue214, <2 x i32> %extractvalue210, <2 x i32> %extractvalue218, <64 x float> %phi109, i32 %phi115)
  %call222 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue168, <2 x i32> %extractvalue169, <2 x i32> %extractvalue170, <16 x i32> %extractvalue204, <16 x i32> %extractvalue212, <16 x i32> %extractvalue208, <16 x i32> %extractvalue216, <2 x i32> %extractvalue205, <2 x i32> %extractvalue213, <2 x i32> %extractvalue209, <2 x i32> %extractvalue217, <2 x i32> %extractvalue206, <2 x i32> %extractvalue214, <2 x i32> %extractvalue210, <2 x i32> %extractvalue218, <64 x float> %phi110, i32 %phi115)
  %call223 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) %addrspacecast154, <32 x i32> %extractvalue148, i32 0)
  %extractvalue224 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %call223, 0
  %extractvalue225 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %call223, 1
  %extractvalue226 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %call223, 2
  %call227 = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5) %extractvalue224, <32 x i32> %extractvalue225, i32 %extractvalue226)
  %extractvalue228 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call227, 0
  %extractvalue229 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call227, 1
  %extractvalue230 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call227, 2
  %extractvalue231 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call227, 3
  %extractvalue232 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call227, 4
  %extractvalue233 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call227, 5
  %call234 = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5) %extractvalue228, <32 x i32> %extractvalue229, i32 %extractvalue230)
  %extractvalue235 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call234, 0
  %extractvalue236 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call234, 1
  %extractvalue237 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call234, 2
  %extractvalue238 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call234, 3
  %extractvalue239 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call234, 4
  %extractvalue240 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call234, 5
  %call241 = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5) %extractvalue235, <32 x i32> %extractvalue236, i32 %extractvalue237)
  %extractvalue242 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call241, 0
  %extractvalue243 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call241, 1
  %extractvalue244 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call241, 2
  %extractvalue245 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call241, 3
  %extractvalue246 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call241, 4
  %extractvalue247 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call241, 5
  %trunc248 = trunc i32 %phi106 to i20
  %trunc249 = trunc i32 %phi105 to i20
  %call250 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.3d.BFP640.p5.p5(ptr addrspace(5) %extractvalue242, <32 x i32> %extractvalue243, i32 %extractvalue244, i20 %trunc41, i20 %trunc42, i20 %trunc248, i20 %trunc43, i20 %trunc44, i20 %trunc249, i20 %trunc45)
  %extractvalue251 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 0
  %extractvalue252 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 1
  %extractvalue253 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 2
  %extractvalue254 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 3
  %zext255 = zext i20 %extractvalue254 to i32
  %extractvalue256 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 4
  %zext257 = zext i20 %extractvalue256 to i32
  %extractvalue258 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 5
  %extractvalue259 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 6
  %extractvalue260 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call250, 7
  %call261 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue231, <2 x i32> %extractvalue232, <2 x i32> %extractvalue233, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue262 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call261, 0
  %extractvalue263 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call261, 1
  %extractvalue264 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call261, 2
  %call265 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue238, <2 x i32> %extractvalue239, <2 x i32> %extractvalue240, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue266 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call265, 0
  %extractvalue267 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call265, 1
  %extractvalue268 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call265, 2
  %call269 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue245, <2 x i32> %extractvalue246, <2 x i32> %extractvalue247, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue270 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call269, 0
  %extractvalue271 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call269, 1
  %extractvalue272 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call269, 2
  %call273 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue258, <2 x i32> %extractvalue259, <2 x i32> %extractvalue260, <16 x i32> poison, <2 x i32> poison, <2 x i32> poison, i32 106)
  %extractvalue274 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call273, 0
  %extractvalue275 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call273, 1
  %extractvalue276 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call273, 2
  %call277 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) %extractvalue197, <32 x i32> %extractvalue198, i32 %extractvalue199)
  %extractvalue278 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %call277, 0
  %extractvalue279 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %call277, 1
  %extractvalue280 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %call277, 2
  %call281 = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) %extractvalue278, <32 x i32> %extractvalue279, i32 %extractvalue280)
  %extractvalue282 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call281, 0
  %extractvalue283 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call281, 1
  %extractvalue284 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call281, 2
  %extractvalue285 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call281, 3
  %extractvalue286 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call281, 4
  %extractvalue287 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call281, 5
  %call288 = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) %extractvalue282, <32 x i32> %extractvalue283, i32 %extractvalue284)
  %extractvalue289 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call288, 0
  %extractvalue290 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call288, 1
  %extractvalue291 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call288, 2
  %extractvalue292 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call288, 3
  %extractvalue293 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call288, 4
  %extractvalue294 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call288, 5
  %call295 = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) %extractvalue289, <32 x i32> %extractvalue290, i32 %extractvalue291)
  %extractvalue296 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call295, 0
  %extractvalue297 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call295, 1
  %extractvalue298 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call295, 2
  %extractvalue299 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call295, 3
  %extractvalue300 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call295, 4
  %extractvalue301 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %call295, 5
  %trunc302 = trunc i32 %phi104 to i20
  %trunc303 = trunc i32 %phi103 to i20
  %call304 = tail call { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.3d.BFP640.p6.p6(ptr addrspace(6) %extractvalue296, <32 x i32> %extractvalue297, i32 %extractvalue298, i20 %trunc51, i20 %trunc52, i20 %trunc302, i20 %trunc53, i20 %trunc54, i20 %trunc303, i20 %trunc55)
  %extractvalue305 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 0
  %extractvalue306 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 1
  %extractvalue307 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 2
  %extractvalue308 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 3
  %zext309 = zext i20 %extractvalue308 to i32
  %extractvalue310 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 4
  %zext311 = zext i20 %extractvalue310 to i32
  %extractvalue312 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 5
  %extractvalue313 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 6
  %extractvalue314 = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %call304, 7
  %call315 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue285, <2 x i32> %extractvalue286, <2 x i32> %extractvalue287, <16 x i32> %extractvalue292, <2 x i32> %extractvalue293, <2 x i32> %extractvalue294, i32 22)
  %extractvalue316 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call315, 0
  %extractvalue317 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call315, 1
  %extractvalue318 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call315, 2
  %call319 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue285, <2 x i32> %extractvalue286, <2 x i32> %extractvalue287, <16 x i32> %extractvalue292, <2 x i32> %extractvalue293, <2 x i32> %extractvalue294, i32 23)
  %extractvalue320 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call319, 0
  %extractvalue321 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call319, 1
  %extractvalue322 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call319, 2
  %call323 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue299, <2 x i32> %extractvalue300, <2 x i32> %extractvalue301, <16 x i32> %extractvalue312, <2 x i32> %extractvalue313, <2 x i32> %extractvalue314, i32 22)
  %extractvalue324 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call323, 0
  %extractvalue325 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call323, 1
  %extractvalue326 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call323, 2
  %call327 = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32> %extractvalue299, <2 x i32> %extractvalue300, <2 x i32> %extractvalue301, <16 x i32> %extractvalue312, <2 x i32> %extractvalue313, <2 x i32> %extractvalue314, i32 23)
  %extractvalue328 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call327, 0
  %extractvalue329 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call327, 1
  %extractvalue330 = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } %call327, 2
  %call331 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue262, <2 x i32> %extractvalue263, <2 x i32> %extractvalue264, <16 x i32> %extractvalue316, <16 x i32> %extractvalue324, <16 x i32> %extractvalue320, <16 x i32> %extractvalue328, <2 x i32> %extractvalue317, <2 x i32> %extractvalue325, <2 x i32> %extractvalue321, <2 x i32> %extractvalue329, <2 x i32> %extractvalue318, <2 x i32> %extractvalue326, <2 x i32> %extractvalue322, <2 x i32> %extractvalue330, <64 x float> %phi111, i32 %phi115)
  %call332 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue266, <2 x i32> %extractvalue267, <2 x i32> %extractvalue268, <16 x i32> %extractvalue316, <16 x i32> %extractvalue324, <16 x i32> %extractvalue320, <16 x i32> %extractvalue328, <2 x i32> %extractvalue317, <2 x i32> %extractvalue325, <2 x i32> %extractvalue321, <2 x i32> %extractvalue329, <2 x i32> %extractvalue318, <2 x i32> %extractvalue326, <2 x i32> %extractvalue322, <2 x i32> %extractvalue330, <64 x float> %phi112, i32 %phi115)
  %call333 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue270, <2 x i32> %extractvalue271, <2 x i32> %extractvalue272, <16 x i32> %extractvalue316, <16 x i32> %extractvalue324, <16 x i32> %extractvalue320, <16 x i32> %extractvalue328, <2 x i32> %extractvalue317, <2 x i32> %extractvalue325, <2 x i32> %extractvalue321, <2 x i32> %extractvalue329, <2 x i32> %extractvalue318, <2 x i32> %extractvalue326, <2 x i32> %extractvalue322, <2 x i32> %extractvalue330, <64 x float> %phi113, i32 %phi115)
  %call334 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32> %extractvalue274, <2 x i32> %extractvalue275, <2 x i32> %extractvalue276, <16 x i32> %extractvalue316, <16 x i32> %extractvalue324, <16 x i32> %extractvalue320, <16 x i32> %extractvalue328, <2 x i32> %extractvalue317, <2 x i32> %extractvalue325, <2 x i32> %extractvalue321, <2 x i32> %extractvalue329, <2 x i32> %extractvalue318, <2 x i32> %extractvalue326, <2 x i32> %extractvalue322, <2 x i32> %extractvalue330, <64 x float> %phi114, i32 %phi115)
  %add335 = add nuw nsw i32 %phi116, 1
  %icmp336 = icmp eq i32 %add335, %load34
  br i1 %icmp336, label %bb90, label %bb102, !llvm.loop !29

bb337:                                            ; preds = %bb90, %bb
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf(<16 x i32>, <2 x i32>, <2 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <64 x float>, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5), <32 x i32>, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6), <32 x i32>, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.3d.BFP640.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.3d.BFP640.p6.p6(ptr addrspace(6), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p5.p5(ptr addrspace(5), <32 x i32>, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6), <32 x i32>, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640(<16 x i32>, <2 x i32>, <2 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, i32) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare void @llvm.assume(i1 noundef) #4

attributes #0 = { mustprogress "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #4 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!4, !5, i64 12}
!4 = !{!"params_t", !5, i64 0, !5, i64 4, !5, i64 8, !5, i64 12, !5, i64 16, !5, i64 20, !8, i64 32, !5, i64 192, !5, i64 196}
!5 = !{!"int", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C++ TBAA"}
!8 = !{!"inner_params_t", !5, i64 0, !5, i64 4, !5, i64 8, !9, i64 12, !5, i64 16, !5, i64 20, !5, i64 24, !5, i64 28, !10, i64 32, !10, i64 48, !10, i64 64, !10, i64 80, !11, i64 96, !11, i64 124}
!9 = !{!"bool", !6, i64 0}
!10 = !{!"ap_2d_t", !5, i64 0, !5, i64 4, !5, i64 8, !5, i64 12}
!11 = !{!"ap_3d_t", !5, i64 0, !5, i64 4, !5, i64 8, !5, i64 12, !5, i64 16, !5, i64 20, !5, i64 24}
!12 = !{!4, !5, i64 192}
!13 = !{!8, !5, i64 4}
!14 = !{!15, !17}
!15 = distinct !{!15, !16, !"kernel: %in0"}
!16 = distinct !{!16, !"kernel"}
!17 = distinct !{!17, !16, !"kernel: %in1"}
!18 = !{!8, !5, i64 16}
!19 = !{!8, !5, i64 8}
!20 = !{!11, !5, i64 16}
!21 = !{!11, !5, i64 0}
!22 = !{!11, !5, i64 4}
!23 = !{!11, !5, i64 8}
!24 = !{!11, !5, i64 12}
!25 = !{!6, !6, i64 0}
!26 = distinct !{!26, !27, !28}
!27 = !{!"llvm.loop.mustprogress"}
!28 = !{!"llvm.loop.itercount.range", i64 2}
!29 = distinct !{!29, !27, !30, !31}
!30 = !{!"llvm.loop.itercount.range", i64 3}
!31 = !{!"llvm.loop.pipeline.disable", i1 true}
