; NOTE: Assertions have been autogenerated by utils/update_ore_test_checks.py
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -mtriple=aie2ps %s -o /dev/null -pass-remarks-output=- -pass-remarks-filter='aie-asm-printer' | FileCheck %s --check-prefix REMARKS

; This structure can happen if MachineBlockPlacement moves 
; unconditional fallthrough MBBs apart.
;
;     %loop <--+
;       |      | jnz  backedge    region 0  (per iteration)
;       v      |
;     %latch --+
;       | j           exit jump   region 1  (once)
;       v
;     %exit
;

target triple = "aie2ps-none-unknown-elf"

define void @two_regions(i1 %enter, i1 %c, i1 %d, ptr %p) {
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            aie-asm-printer
; REMARKS-NEXT: Name:            analysis
; REMARKS-NEXT: Function:        two_regions
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - BasicBlock:      entry
; REMARKS-NEXT:   - RegionIndex:     '0'
; REMARKS-NEXT:   - BundleCount:     '8'
; REMARKS-NEXT:   - ByteCount:       '32'
; REMARKS-NEXT:   - Offset:          '0'
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            aie-asm-printer
; REMARKS-NEXT: Name:            analysis
; REMARKS-NEXT: Function:        two_regions
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - BasicBlock:      epilog
; REMARKS-NEXT:   - RegionIndex:     '0'
; REMARKS-NEXT:   - BundleCount:     '8'
; REMARKS-NEXT:   - ByteCount:       '32'
; REMARKS-NEXT:   - Offset:          '32'
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            aie-asm-printer
; REMARKS-NEXT: Name:            analysis
; REMARKS-NEXT: Function:        two_regions
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - BasicBlock:      loop.preheader
; REMARKS-NEXT:   - RegionIndex:     '0'
; REMARKS-NEXT:   - BundleCount:     '3'
; REMARKS-NEXT:   - ByteCount:       '16'
; REMARKS-NEXT:   - Offset:          '64'
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            aie-asm-printer
; REMARKS-NEXT: Name:            analysis
; REMARKS-NEXT: Function:        two_regions
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - BasicBlock:      loop
; REMARKS-NEXT:   - RegionIndex:     '0'
; REMARKS-NEXT:   - BundleCount:     '6'
; REMARKS-NEXT:   - ByteCount:       '30'
; REMARKS-NEXT:   - Offset:          '80'
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            aie-asm-printer
; REMARKS-NEXT: Name:            analysis
; REMARKS-NEXT: Function:        two_regions
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - BasicBlock:      latch
; REMARKS-NEXT:   - RegionIndex:     '0'
; REMARKS-NEXT:   - BundleCount:     '6'
; REMARKS-NEXT:   - ByteCount:       '18'
; REMARKS-NEXT:   - Offset:          '110'
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            aie-asm-printer
; REMARKS-NEXT: Name:            analysis
; REMARKS-NEXT: Function:        two_regions
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - BasicBlock:      latch
; REMARKS-NEXT:   - RegionIndex:     '1'
; REMARKS-NEXT:   - BundleCount:     '6'
; REMARKS-NEXT:   - ByteCount:       '16'
; REMARKS-NEXT:   - Offset:          '128'
; REMARKS-NEXT: ...
; REMARKS: --- !Analysis
; REMARKS-NEXT: Pass:            aie-asm-printer
; REMARKS-NEXT: Name:            analysis
; REMARKS-NEXT: Function:        two_regions
; REMARKS-NEXT: Args:
; REMARKS-NEXT:   - BasicBlock:      exit
; REMARKS-NEXT:   - RegionIndex:     '0'
; REMARKS-NEXT:   - BundleCount:     '6'
; REMARKS-NEXT:   - ByteCount:       '16'
; REMARKS-NEXT:   - Offset:          '144'
; REMARKS-NEXT: ...
entry:
  br i1 %enter, label %loop, label %epilog

epilog:                                           ; preds = %entry, %latch
  store volatile i32 -1, ptr %p
  br i1 %d, label %loop, label %exit

loop:                                             ; preds = %entry, %epilog, %loop
  store volatile i32 1, ptr %p
  br i1 %c, label %latch, label %loop

latch:                                            ; preds = %loop
  store volatile i32 2, ptr %p
  br i1 %d, label %loop, label %epilog

exit:                                             ; preds = %epilog
  ret void
}
