// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4

//===- aie-scl2vec-intrinsic.cpp ---------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O1 %s --target=aie2 -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2
// RUN: %clang -O1 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2P


// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z11test_shiftxDv16_iS_ij(
// AIE2-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z11test_shiftxDv16_iS_ij(
// AIE2P-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_shiftx(v16int32 a, v16int32 b, int step, unsigned int shift) {
  return shiftx(a,b,step,shift);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_shiftxDv32_tS_ij(
// AIE2-SAME: <32 x i16> noundef [[A:%.*]], <32 x i16> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_shiftxDv32_tS_ij(
// AIE2P-SAME: <32 x i16> noundef [[A:%.*]], <32 x i16> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP3]]
//
v32uint16 test_shiftx(v32uint16 a, v32uint16 b, int step, unsigned int shift) {
  return shiftx(a,b,step,shift);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z16test_shift_bytesDv64_aS_j(
// AIE2-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z16test_shift_bytesDv64_aS_j(
// AIE2P-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v64int8 test_shift_bytes(v64int8 a, v64int8 b, unsigned int shift) {
  return shift_bytes(a,b,shift);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z10test_shiftDv64_hS_j(
// AIE2-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[SHIFT_BY:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT_BY]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z10test_shiftDv64_hS_j(
// AIE2P-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[SHIFT_BY:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT_BY]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 test_shift(v64uint8 a, v64uint8 b, unsigned int shift_by) {
   return shift(a,b,shift_by);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest1Dv64_DB8_S0_ij(
// AIE2-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest1Dv64_DB8_S0_ij(
// AIE2P-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v128int4 shiftxTest1(v128int4 a, v128int4 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest2Dv64_aS_ij(
// AIE2-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest2Dv64_aS_ij(
// AIE2P-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v64int8 shiftxTest2(v64int8 a, v64int8 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11shiftxTest3Dv32_sS_ij(
// AIE2-SAME: <32 x i16> noundef [[A:%.*]], <32 x i16> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11shiftxTest3Dv32_sS_ij(
// AIE2P-SAME: <32 x i16> noundef [[A:%.*]], <32 x i16> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP3]]
//
v32int16 shiftxTest3(v32int16 a, v32int16 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z11shiftxTest4Dv16_iS_ij(
// AIE2-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z11shiftxTest4Dv16_iS_ij(
// AIE2P-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 shiftxTest4(v16int32 a, v16int32 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest5Dv64_DU8_S0_ij(
// AIE2-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest5Dv64_DU8_S0_ij(
// AIE2P-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v128uint4 shiftxTest5(v128uint4 a, v128uint4 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest6Dv64_hS_ij(
// AIE2-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11shiftxTest6Dv64_hS_ij(
// AIE2P-SAME: <64 x i8> noundef [[A:%.*]], <64 x i8> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 shiftxTest6(v64uint8 a, v64uint8 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11shiftxTest7Dv32_tS_ij(
// AIE2-SAME: <32 x i16> noundef [[A:%.*]], <32 x i16> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11shiftxTest7Dv32_tS_ij(
// AIE2P-SAME: <32 x i16> noundef [[A:%.*]], <32 x i16> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP3]]
//
v32uint16 shiftxTest7(v32uint16 a, v32uint16 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z11shiftxTest8Dv16_jS_ij(
// AIE2-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z11shiftxTest8Dv16_jS_ij(
// AIE2P-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 shiftxTest8(v16uint32 a, v16uint32 b, int step, unsigned int shift) {
//
  return shiftx(a, b, step, shift);
}

//
// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z11shiftxTest9Dv32_8bfloat16S0_ij(
// AIE2-SAME: <32 x bfloat> noundef [[A:%.*]], <32 x bfloat> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vshift.bf512.bf512(<32 x bfloat> [[A]], <32 x bfloat> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z11shiftxTest9Dv32_8bfloat16S0_ij(
// AIE2P-SAME: <32 x bfloat> noundef [[A:%.*]], <32 x bfloat> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> [[A]], <32 x bfloat> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 shiftxTest9(v32bfloat16 a, v32bfloat16 b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}
// AIE2-LABEL: define dso_local noundef <8 x i64> @_Z12shiftxTest10Dv16_u10__accfloatS_ij(
// AIE2-SAME: <8 x i64> noundef [[A:%.*]], <8 x i64> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i64> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2-NEXT:    ret <8 x i64> [[TMP3]]
//
// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z12shiftxTest10Dv16_u10__accfloatS_ij(
// AIE2P-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16accfloat shiftxTest10(v16accfloat a, v16accfloat b, int step, unsigned int shift) {
  return shiftx(a, b, step, shift);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aic(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aic(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v64int8 test_upd_elem(v64int8 v, int idx, char b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_sis(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_sis(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[V]], i16 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x i16> [[VECINS_I_I]]
//
v32int16 test_upd_elem(v32int16 v, int idx, short b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_iii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_iii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS_I_I]]
//
v16int32 test_upd_elem(v16int32 v, int idx, int b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hih(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hih(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v64uint8 test_upd_elem(v64uint8 v, int idx, unsigned char b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_tit(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_tit(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[V]], i16 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x i16> [[VECINS_I_I]]
//
v32uint16 test_upd_elem(v32uint16 v, int idx, unsigned short b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_jij(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_jij(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS_I_I]]
//
v16uint32 test_upd_elem(v16uint32 v, int idx, unsigned int b) {
  return upd_elem(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z13upd_elemTest1Dv64_aic(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13upd_elemTest1Dv64_aic(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v64int8 upd_elemTest1(v64int8 v, int idx, char b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z13upd_elemTest2Dv32_sis(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13upd_elemTest2Dv32_sis(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[V]], i16 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x i16> [[VECINS_I_I]]
//
v32int16 upd_elemTest2(v32int16 v, int idx, short b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z13upd_elemTest3Dv16_iii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z13upd_elemTest3Dv16_iii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS_I_I]]
//
v16int32 upd_elemTest3(v16int32 v, int idx, int b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z13upd_elemTest4Dv64_hih(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13upd_elemTest4Dv64_hih(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v64uint8 upd_elemTest4(v64uint8 v, int idx, unsigned char b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z13upd_elemTest5Dv32_tit(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13upd_elemTest5Dv32_tit(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[V]], i16 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x i16> [[VECINS_I_I]]
//
v32uint16 upd_elemTest5(v32uint16 v, int idx, unsigned short b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z13upd_elemTest6Dv16_jij(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z13upd_elemTest6Dv16_jij(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS_I_I]]
//
v16uint32 upd_elemTest6(v16uint32 v, int idx, unsigned int b) {
  return upd_elem(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z13upd_elemTest7Dv32_8bfloat16iS_(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vinsert16.bf512(<32 x bfloat> [[V]], i32 [[IDX]], bfloat [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z13upd_elemTest7Dv32_8bfloat16iS_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x bfloat> [[V]], bfloat [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x bfloat> [[VECINS_I_I]]
//
v32bfloat16 upd_elemTest7(v32bfloat16 v, int idx, bfloat16 b) {
  return upd_elem(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest1Dv64_DB8_iS_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest1Dv64_DB8_iS_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v128int4 insertTest1(v128int4 v, int idx, v2int4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest2Dv64_DB8_iDv2_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i16 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest2Dv64_DB8_iDv2_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[TMP0]], i16 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 insertTest2(v128int4 v, int idx, v4int4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest3Dv64_DB8_iDv4_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest3Dv64_DB8_iDv4_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 insertTest3(v128int4 v, int idx, v8int4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest4Dv64_DB8_iDv8_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11insertTest4Dv64_DB8_iDv8_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 insertTest4(v128int4 v, int idx, v16int4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z11insertTest5Dv32_8bfloat16iDv2_S_(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vinsert32.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <2 x bfloat> [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z11insertTest5Dv32_8bfloat16iDv2_S_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert32.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <2 x bfloat> [[B]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 insertTest5(v32bfloat16 v, int idx, v2bfloat16 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iS_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iS_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v128int4 test_insert(v128int4 v, int idx, v2int4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv2_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i16 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv2_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[TMP0]], i16 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 test_insert(v128int4 v, int idx, v4int4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv4_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv4_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 test_insert(v128int4 v, int idx, v8int4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv8_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv8_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 test_insert(v128int4 v, int idx, v16int4 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aic(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aic(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v64int8 test_insert(v64int8 v, int idx, char b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z23test_insert_signed_charDv64_aia(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z23test_insert_signed_charDv64_aia(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v64int8 test_insert_signed_char(v64int8 v, int idx, signed char b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv2_a(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i16 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv2_a(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[TMP0]], i16 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_insert(v64int8 v, int idx, v2int8 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv4_a(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv4_a(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_insert(v64int8 v, int idx, v4int8 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv8_a(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv8_a(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_insert(v64int8 v, int idx, v8int8 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_sis(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = sext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_sis(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[V]], i16 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x i16> [[VECINS_I_I]]
//
v32int16 test_insert(v32int16 v, int idx, short b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_siDv2_s(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_siDv2_s(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_insert(v32int16 v, int idx, v2int16 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_siDv4_s(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_siDv4_s(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_insert(v32int16 v, int idx, v4int16 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iS_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iS_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v128uint4 test_insert(v128uint4 v, int idx, v2uint4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv2_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv2_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = extractelement <2 x i8> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[CONV_I_I]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v128uint4 test_insert(v128uint4 v, int idx, v4uint4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv4_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv4_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = extractelement <4 x i8> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[CONV_I_I]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v128uint4 test_insert(v128uint4 v, int idx, v8uint4 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv8_S_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv8_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v128uint4 test_insert(v128uint4 v, int idx, v16uint4 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hih(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert8.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hih(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
v64uint8 test_insert(v64uint8 v, int idx, unsigned char b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv2_h(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv2_h(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[TMP0]], i16 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_insert(v64uint8 v, int idx, v2uint8 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv4_h(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv4_h(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_insert(v64uint8 v, int idx, v4uint8 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv8_h(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv8_h(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_insert(v64uint8 v, int idx, v8uint8 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tit(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert16.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tit(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i16 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[V]], i16 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x i16> [[VECINS_I_I]]
//
v32uint16 test_insert(v32uint16 v, int idx, unsigned short b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv2_t(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv2_t(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_insert(v32uint16 v, int idx, v2uint16 b) {
  return insert(v, idx, b);
}
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv4_t(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv4_t(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_insert(v32uint16 v, int idx, v4uint16 b) {
  return insert(v, idx, b);
}


// AIE2-LABEL: define dso_local noundef signext i8 @_Z13ext_elemTest1Dv64_aii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i8
// AIE2-NEXT:    ret i8 [[CONV_I]]
//
// AIE2P-LABEL: define dso_local noundef signext i8 @_Z13ext_elemTest1Dv64_aii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <64 x i8> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret i8 [[VECEXT_I_I]]
//
char ext_elemTest1(v64int8 v, int idx, int sign) {
  return ext_elem(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <2 x i8> @_Z13ext_elemTest2Dv64_aii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP1]] to i16
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i16 [[CONV_I]] to <2 x i8>
// AIE2-NEXT:    ret <2 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i8> @_Z13ext_elemTest2Dv64_aii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <32 x i16> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i16 [[VECEXT_I_I]] to <2 x i8>
// AIE2P-NEXT:    ret <2 x i8> [[TMP1]]
//
v2int8 ext_elemTest2(v64int8 v, int idx, int sign) {
  return ext_v2int8(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <4 x i8> @_Z13ext_elemTest3Dv64_aii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <4 x i8> @_Z13ext_elemTest3Dv64_aii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i32 [[VECEXT_I_I]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP1]]
//
v4int8 ext_elemTest3(v64int8 v, int idx, int sign) {
  return ext_v4int8(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <8 x i8> @_Z13ext_elemTest4Dv64_DB8_ii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <8 x i8>
// AIE2-NEXT:    ret <8 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <8 x i8> @_Z13ext_elemTest4Dv64_DB8_ii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINIT2_I_I]] to <8 x i8>
// AIE2P-NEXT:    ret <8 x i8> [[TMP1]]
//
v16int4 ext_elemTest4(v128int4 v, int idx, int sign) {
  return ext_v16int4(v, idx, sign);
}
// AIE2-LABEL: define dso_local noundef <4 x i16> @_Z13ext_elemTest5Dv64_DB8_ii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <4 x i16>
// AIE2-NEXT:    ret <4 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <4 x i16> @_Z13ext_elemTest5Dv64_DB8_ii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINIT2_I_I]] to <4 x i16>
// AIE2P-NEXT:    ret <4 x i16> [[TMP1]]
//
v4int16 ext_elemTest5(v128int4 v, int idx, int sign) {
  return ext_v4int16(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z18test_broadcast_s16s(
// AIE2-SAME: i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 [[CONV_I]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z18test_broadcast_s16s(
// AIE2P-SAME: i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <32 x i16> poison, i16 [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    ret <32 x i16> [[SPLAT_SPLAT_I]]
//
v32int16 test_broadcast_s16 (short b) {
   return  broadcast_s16(b);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z18test_broadcast_s32i(
// AIE2-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z18test_broadcast_s32i(
// AIE2P-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <16 x i32> poison, i32 [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x i32> [[SPLAT_SPLAT_I]]
//
v16int32 test_broadcast_s32 (int b) {
   return  broadcast_s32(b);
}


// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z20test_broadcast_v2s32Dv2_i(
// AIE2-SAME: <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32> [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z20test_broadcast_v2s32Dv2_i(
// AIE2P-SAME: <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINIT30_I_I:%.*]] = shufflevector <2 x i32> [[B]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x i32> [[VECINIT30_I_I]]
//
v16int32 test_broadcast_v2s32 (v2int32 b) {
   return  broadcast_v2s32(b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z26test_broadcast_to_v128int4DB8_(
// AIE2-SAME: i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vbroadcast8.I512(i32 [[CONV_I]])
// AIE2-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z26test_broadcast_to_v128int4DB8_(
// AIE2P-SAME: i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <64 x i8> poison, i8 [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <64 x i8> [[SPLAT_SPLATINSERT_I]], <64 x i8> poison, <64 x i32> zeroinitializer
// AIE2P-NEXT:    ret <64 x i8> [[SPLAT_SPLAT_I]]
//
v128int4 test_broadcast_to_v128int4 (v2int4 b) {
   return  broadcast_to_v128int4(b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z25test_broadcast_to_v64int8Dv2_a(
// AIE2-SAME: <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z25test_broadcast_to_v64int8Dv2_a(
// AIE2P-SAME: <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <32 x i16> poison, i16 [[TMP0]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[SPLAT_SPLAT_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_broadcast_to_v64int8 (v2int8 b) {
   return  broadcast_to_v64int8(b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z26test_broadcast_to_v128int4Dv8_DB8_(
// AIE2-SAME: <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32> [[TMP0]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z26test_broadcast_to_v128int4Dv8_DB8_(
// AIE2P-SAME: <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[VECINIT30_I_I:%.*]] = shufflevector <2 x i32> [[TMP0]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[VECINIT30_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
v128int4 test_broadcast_to_v128int4 (v16int4 b) {
   return  broadcast_to_v128int4(b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z25test_broadcast_to_v64int8Dv8_a(
// AIE2-SAME: <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32> [[TMP0]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z25test_broadcast_to_v64int8Dv8_a(
// AIE2P-SAME: <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[VECINIT30_I_I:%.*]] = shufflevector <2 x i32> [[TMP0]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[VECINIT30_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_broadcast_to_v64int8 (v8int8 b) {
   return  broadcast_to_v64int8(b);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z26test_broadcast_to_v16int32i(
// AIE2-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z26test_broadcast_to_v16int32i(
// AIE2P-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <16 x i32> poison, i32 [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x i32> [[SPLAT_SPLAT_I]]
//
v16int32 test_broadcast_to_v16int32 (int b) {
   return  broadcast_to_v16int32(b);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z26test_broadcast_to_v16int32Dv2_i(
// AIE2-SAME: <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32> [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z26test_broadcast_to_v16int32Dv2_i(
// AIE2P-SAME: <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINIT30_I_I:%.*]] = shufflevector <2 x i32> [[B]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x i32> [[VECINIT30_I_I]]
//
v16int32 test_broadcast_to_v16int32 (v2int32 b) {
   return  broadcast_to_v16int32(b);
}


// AIE2-LABEL: define dso_local noundef <16 x float> @_Z20test_broadcast_floatf(
// AIE2-SAME: float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast float [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP0]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z20test_broadcast_floatf(
// AIE2P-SAME: float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = insertelement <16 x float> poison, float [[B]], i64 0
// AIE2P-NEXT:    [[TMP1:%.*]] = shufflevector <16 x float> [[TMP0]], <16 x float> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x float> [[TMP1]]
//
v16float test_broadcast_float(float b) {
  return broadcast_float(b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z16test_shiftl_elemDv64_ai(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vbroadcast8.I512(i32 [[S]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]], i32 0, i32 1)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[TMP3]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP4]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z16test_shiftl_elemDv64_ai(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[S]] to i8
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <64 x i8> poison, i8 [[CONV_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <64 x i8> [[SPLAT_SPLATINSERT_I_I]], <64 x i8> poison, <64 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[SPLAT_SPLAT_I_I]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 1)
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v64int8 test_shiftl_elem(v64int8 v, int s) {
  return shiftl_elem(v, s);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z16test_shiftl_elemDv16_ii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[S]])
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[V]], <16 x i32> [[TMP0]], i32 0, i32 4)
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z16test_shiftl_elemDv16_ii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[S]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[V]], <16 x i32> [[SPLAT_SPLAT_I_I]], i32 0, i32 4)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_shiftl_elem(v16int32 v, int s) {
  return shiftl_elem(v, s);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z16test_shiftl_elemDv32_tj(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 [[S]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[TMP0]] to <16 x i32>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]], i32 0, i32 2)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[TMP3]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP4]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z16test_shiftl_elemDv32_tj(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[S]] to i16
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <32 x i16> poison, i16 [[CONV_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[SPLAT_SPLAT_I_I]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 2)
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP3]]
//
v32uint16 test_shiftl_elem(v32uint16 v, unsigned int s) {
  return shiftl_elem(v, s);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z16test_shiftr_elemDv32_si(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 [[S]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]], i32 0, i32 62)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[TMP3]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP4]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z16test_shiftr_elemDv32_si(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[S]] to i16
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <32 x i16> poison, i16 [[CONV_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[SPLAT_SPLAT_I_I]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 62)
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP3]]
//
v32int16 test_shiftr_elem(v32int16 v, int s) {
  return shiftr_elem(v, s);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z16test_shiftr_elemDv64_hj(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vbroadcast8.I512(i32 [[S]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]], i32 0, i32 63)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[TMP3]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP4]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z16test_shiftr_elemDv64_hj(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[S]] to i8
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <64 x i8> poison, i8 [[CONV_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <64 x i8> [[SPLAT_SPLATINSERT_I_I]], <64 x i8> poison, <64 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[SPLAT_SPLAT_I_I]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 63)
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 test_shiftr_elem(v64uint8 v, unsigned int s) {
  return shiftr_elem(v, s);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z16test_shiftr_elemDv16_jj(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[S]])
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[V]], i32 0, i32 60)
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z16test_shiftr_elemDv16_jj(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[S]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[SPLAT_SPLAT_I_I]], <16 x i32> [[V]], i32 0, i32 60)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_shiftr_elem(v16uint32 v, unsigned int s) {
  return shiftr_elem(v, s);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z21test_broadcast_one_u8v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vbroadcast8.I512(i32 1)
// AIE2-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z21test_broadcast_one_u8v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <64 x i8> splat (i8 1)
//
v64uint8 test_broadcast_one_u8 () {
   return broadcast_one_u8();
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z22test_broadcast_one_u16v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 1)
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z22test_broadcast_one_u16v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <32 x i16> splat (i16 1)
//
v32uint16 test_broadcast_one_u16 () {
   return broadcast_one_u16();
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z22test_broadcast_one_u32v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 1)
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z22test_broadcast_one_u32v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <16 x i32> splat (i32 1)
//
v16uint32 test_broadcast_one_u32 () {
   return broadcast_one_u32();
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z30test_broadcast_zero_to_v64int8v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vbroadcast8.I512(i32 0)
// AIE2-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z30test_broadcast_zero_to_v64int8v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <64 x i8> zeroinitializer
//
v64uint8 test_broadcast_zero_to_v64int8 () {
   return broadcast_zero_to_v64int8();
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z31test_broadcast_zero_to_v32int16v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 0)
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z31test_broadcast_zero_to_v32int16v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <32 x i16> zeroinitializer
//
v32uint16 test_broadcast_zero_to_v32int16 () {
   return broadcast_zero_to_v32int16();
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z31test_broadcast_zero_to_v16int32v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 0)
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z31test_broadcast_zero_to_v16int32v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <16 x i32> zeroinitializer
//
v16uint32 test_broadcast_zero_to_v16int32 () {
   return broadcast_zero_to_v16int32();
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z31test_broadcast_zero_to_v16floatv(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP1]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z31test_broadcast_zero_to_v16floatv(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <16 x float> zeroinitializer
//
v16float test_broadcast_zero_to_v16float () {
   return broadcast_zero_to_v16float();
}

// AIE2-LABEL: define dso_local noundef <16 x i64> @_Z31test_broadcast_zero_to_v16acc64v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2.vbroadcast.zero.acc1024()
// AIE2-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2P-LABEL: define dso_local inreg noundef <16 x i64> @_Z31test_broadcast_zero_to_v16acc64v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <16 x i64> zeroinitializer
//
v16acc64 test_broadcast_zero_to_v16acc64 () {
   return broadcast_zero_to_v16acc64();
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z19test_broadcast_elemDv32_si(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vextract.broadcast16.I512(<32 x i16> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z19test_broadcast_elemDv32_si(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <32 x i16> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <32 x i16> poison, i16 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    ret <32 x i16> [[SPLAT_SPLAT_I_I]]
//
v32int16 test_broadcast_elem (v32int16 v, int idx) {
   return broadcast_elem(v, idx);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z19test_broadcast_elemDv64_hi(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vextract.broadcast8.I512(<64 x i8> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z19test_broadcast_elemDv64_hi(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <64 x i8> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <64 x i8> poison, i8 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <64 x i8> [[SPLAT_SPLATINSERT_I_I]], <64 x i8> poison, <64 x i32> zeroinitializer
// AIE2P-NEXT:    ret <64 x i8> [[SPLAT_SPLAT_I_I]]
//
v64uint8 test_broadcast_elem (v64uint8 v, int idx) {
   return broadcast_elem(v, idx);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z19test_broadcast_elemDv32_ti(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vextract.broadcast16.I512(<32 x i16> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z19test_broadcast_elemDv32_ti(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <32 x i16> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <32 x i16> poison, i16 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    ret <32 x i16> [[SPLAT_SPLAT_I_I]]
//
v32uint16 test_broadcast_elem (v32uint16 v, int idx) {
   return broadcast_elem(v, idx);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z19test_broadcast_elemDv16_ji(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vextract.broadcast32.I512(<16 x i32> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z19test_broadcast_elemDv16_ji(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x i32> [[SPLAT_SPLAT_I_I]]
//
v16uint32 test_broadcast_elem (v16uint32 v, int idx) {
   return broadcast_elem(v, idx);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z12test_shuffleDv16_iS_j(
// AIE2-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vshuffle(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[MODE]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z12test_shuffleDv16_iS_j(
// AIE2P-SAME: <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[MODE]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_shuffle(v16int32 a,    v16int32 b,    unsigned int mode){
   return shuffle(a,b,mode);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z15test_shuffle_s8ij(
// AIE2-SAME: i32 noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2.vbcst.shuffle8(i32 [[B]], i32 [[M]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z15test_shuffle_s8ij(
// AIE2P-SAME: i32 noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.vbcst.shuffle8(i32 [[B]], i32 [[M]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_shuffle_s8   (int b, unsigned int m) {
   return shuffle_s8(b,m);
}

// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z16test_shuffle_s16ij(
// AIE2-SAME: i32 noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2.vbcst.shuffle16(i32 [[B]], i32 [[M]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z16test_shuffle_s16ij(
// AIE2P-SAME: i32 noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.vbcst.shuffle16(i32 [[B]], i32 [[M]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_shuffle_s16 (int b, unsigned int m) {
   return shuffle_s16(b,m);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z16test_shuffle_s32ij(
// AIE2-SAME: i32 noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbcst.shuffle32(i32 [[B]], i32 [[M]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z16test_shuffle_s32ij(
// AIE2P-SAME: i32 noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vbcst.shuffle32(i32 [[B]], i32 [[M]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_shuffle_s32 (int b, unsigned int m) {
   return shuffle_s32(b,m);
}

// AIE2-LABEL: define dso_local noundef signext i8 @_Z15test_ext_v2int4Dv64_DB8_ii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i8
// AIE2-NEXT:    ret i8 [[CONV_I]]
//
// AIE2P-LABEL: define dso_local noundef signext i8 @_Z15test_ext_v2int4Dv64_DB8_ii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <64 x i8> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret i8 [[VECEXT_I_I]]
//
v2int4 test_ext_v2int4(v128int4 v, int idx, int sign) {
  return ext_v2int4(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef signext i8 @_Z13test_ext_elemDv64_aii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i8
// AIE2-NEXT:    ret i8 [[CONV_I]]
//
// AIE2P-LABEL: define dso_local noundef signext i8 @_Z13test_ext_elemDv64_aii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <64 x i8> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret i8 [[VECEXT_I_I]]
//
char test_ext_elem(v64int8 v, int idx, int sign) {
  return ext_elem(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef signext i8 @_Z18test_ext_elem_idx3Dv64_ai(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> [[V]], i32 3, i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i8
// AIE2-NEXT:    ret i8 [[CONV_I]]
//
// AIE2P-LABEL: define dso_local noundef signext i8 @_Z18test_ext_elem_idx3Dv64_ai(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <64 x i8> [[V]], i64 3
// AIE2P-NEXT:    ret i8 [[VECEXT_I_I]]
//
char test_ext_elem_idx3(v64int8 v, int sign) {
  return ext_elem(v, 3, sign);
}

// AIE2-LABEL: define dso_local noundef <2 x i8> @_Z16test_ext_v2uint8Dv64_hii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP1]] to i16
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i16 [[CONV_I]] to <2 x i8>
// AIE2-NEXT:    ret <2 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i8> @_Z16test_ext_v2uint8Dv64_hii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <32 x i16> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i16 [[VECEXT_I_I]] to <2 x i8>
// AIE2P-NEXT:    ret <2 x i8> [[TMP1]]
//
v2uint8 test_ext_v2uint8(v64uint8 v, int idx, int sign) {
  return ext_v2uint8(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef zeroext i16 @_Z13test_ext_elemDv32_tii(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i16
// AIE2-NEXT:    ret i16 [[CONV_I]]
//
// AIE2P-LABEL: define dso_local noundef zeroext i16 @_Z13test_ext_elemDv32_tii(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <32 x i16> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret i16 [[VECEXT_I_I]]
//
unsigned short test_ext_elem(v32uint16 v, int idx, int sign) {
  return ext_elem(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef zeroext i16 @_Z18test_ext_elem_idx4Dv32_ti(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[V]], i32 4, i32 [[SIGN]])
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i16
// AIE2-NEXT:    ret i16 [[CONV_I]]
//
// AIE2P-LABEL: define dso_local noundef zeroext i16 @_Z18test_ext_elem_idx4Dv32_ti(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <32 x i16> [[V]], i64 4
// AIE2P-NEXT:    ret i16 [[VECEXT_I_I]]
//
unsigned short test_ext_elem_idx4(v32uint16 v, int sign) {
  return ext_elem(v, 4, sign);
}

// AIE2-LABEL: define dso_local noundef <2 x i16> @_Z16test_ext_v2int16Dv32_sii(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x i16>
// AIE2-NEXT:    ret <2 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i16> @_Z16test_ext_v2int16Dv32_sii(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i32 [[VECEXT_I_I]] to <2 x i16>
// AIE2P-NEXT:    ret <2 x i16> [[TMP1]]
//
v2int16 test_ext_v2int16(v32int16 v, int idx, int sign) {
  return ext_v2int16(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef i32 @_Z13test_ext_elemDv16_iii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef i32 @_Z13test_ext_elemDv16_iii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret i32 [[VECEXT_I_I]]
//
int test_ext_elem(v16int32 v, int idx, int sign) {
  return ext_elem(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef i32 @_Z18test_ext_elem_idx5Dv16_ii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[V]], i32 5, i32 [[SIGN]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef i32 @_Z18test_ext_elem_idx5Dv16_ii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[V]], i64 5
// AIE2P-NEXT:    ret i32 [[VECEXT_I_I]]
//
int test_ext_elem_idx5(v16int32 v, int sign) {
  return ext_elem(v, 5, sign);
}

// AIE2-LABEL: define dso_local noundef <4 x i16> @_Z16test_ext_v4int16Dv32_sii(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <4 x i16>
// AIE2-NEXT:    ret <4 x i16> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <4 x i16> @_Z16test_ext_v4int16Dv32_sii(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINIT2_I_I]] to <4 x i16>
// AIE2P-NEXT:    ret <4 x i16> [[TMP1]]
//
v4int16 test_ext_v4int16(v32int16 v, int idx, int sign) {
  return ext_v4int16(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <2 x i32> @_Z16test_ext_v2int32Dv16_iii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    ret <2 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z16test_ext_v2int32Dv16_iii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I]]
//
v2int32 test_ext_v2int32(v16int32 v, int idx, int sign) {
  return ext_v2int32(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <2 x i32> @_Z21test_ext_v2int32_idx4Dv16_ii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[V]], i32 4, i32 [[SIGN]])
// AIE2-NEXT:    ret <2 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z21test_ext_v2int32_idx4Dv16_ii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 8, i32 9>
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I]]
//
v2int32 test_ext_v2int32_idx4(v16int32 v, int sign) {
  return ext_v2int32(v, 4, sign);
}

// AIE2-LABEL: define dso_local noundef <4 x i8> @_Z19test_extract_v8int4Dv64_DB8_ii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <4 x i8> @_Z19test_extract_v8int4Dv64_DB8_ii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i32 [[VECEXT_I_I]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP1]]
//
v8int4 test_extract_v8int4(v128int4 v, int idx, int sign) {
  return ext_v8int4(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <8 x i8> @_Z19test_extract_v8int8Dv64_aii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <8 x i8>
// AIE2-NEXT:    ret <8 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <8 x i8> @_Z19test_extract_v8int8Dv64_aii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINIT2_I_I]] to <8 x i8>
// AIE2P-NEXT:    ret <8 x i8> [[TMP1]]
//
v8int8 test_extract_v8int8(v64int8 v, int idx, int sign) {
  return ext_v8int8(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef i32 @_Z17test_extract_elemDv16_jii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef i32 @_Z17test_extract_elemDv16_jii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret i32 [[VECEXT_I_I]]
//
unsigned int test_extract_elem(v16uint32 v, int idx, int sign) {
  return ext_elem(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef float @_Z23test_extract_elem_floatDv16_fii(
// AIE2-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to float
// AIE2-NEXT:    ret float [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef float @_Z23test_extract_elem_floatDv16_fii(
// AIE2P-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x float> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret float [[VECEXT_I_I]]
//
float test_extract_elem_float(v16float v, int idx, int sign) {
  return extract_elem(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef i32 @_Z22test_extract_elem_idx5Dv16_ji(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[V]], i32 5, i32 [[SIGN]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef i32 @_Z22test_extract_elem_idx5Dv16_ji(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[V]], i64 5
// AIE2P-NEXT:    ret i32 [[VECEXT_I_I]]
//
unsigned int test_extract_elem_idx5(v16uint32 v, int sign) {
  return ext_elem(v, 5, sign);
}

// AIE2-LABEL: define dso_local noundef signext i8 @_Z13test_ext_elemDv64_ai(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> [[V]], i32 [[IDX]], i32 1)
// AIE2-NEXT:    [[CONV_I_I:%.*]] = trunc i32 [[TMP0]] to i8
// AIE2-NEXT:    ret i8 [[CONV_I_I]]
//
// AIE2P-LABEL: define dso_local noundef signext i8 @_Z13test_ext_elemDv64_ai(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <64 x i8> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret i8 [[VECEXT_I_I_I]]
//
char test_ext_elem(v64int8 v, int idx) {
  return ext_elem(v, idx);
}

// AIE2-LABEL: define dso_local noundef <2 x i8> @_Z15test_ext_v2int8Dv64_ai(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[TMP0]], i32 [[IDX]], i32 1)
// AIE2-NEXT:    [[CONV_I_I:%.*]] = trunc i32 [[TMP1]] to i16
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i16 [[CONV_I_I]] to <2 x i8>
// AIE2-NEXT:    ret <2 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i8> @_Z15test_ext_v2int8Dv64_ai(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <32 x i16> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i16 [[VECEXT_I_I_I]] to <2 x i8>
// AIE2P-NEXT:    ret <2 x i8> [[TMP1]]
//
v2int8 test_ext_v2int8(v64int8 v, int idx) {
  return ext_v2int8(v, idx);
}

// AIE2-LABEL: define dso_local noundef <2 x i8> @_Z20test_ext_v2int8_idx2Dv64_a(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[TMP0]], i32 2, i32 1)
// AIE2-NEXT:    [[CONV_I_I:%.*]] = trunc i32 [[TMP1]] to i16
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i16 [[CONV_I_I]] to <2 x i8>
// AIE2-NEXT:    ret <2 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i8> @_Z20test_ext_v2int8_idx2Dv64_a(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <32 x i16> [[TMP0]], i64 2
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i16 [[VECEXT_I_I_I]] to <2 x i8>
// AIE2P-NEXT:    ret <2 x i8> [[TMP1]]
//
v2int8 test_ext_v2int8_idx2(v64int8 v) {
  return ext_v2int8(v, 2);
}

// AIE2-LABEL: define dso_local noundef <2 x i32> @_Z17test_ext_v2uint32Dv16_ji(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[V]], i32 [[IDX]], i32 0)
// AIE2-NEXT:    ret <2 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z17test_ext_v2uint32Dv16_ji(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[MUL_I_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = or disjoint i32 [[MUL_I_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[ADD_I_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I_I]], i32 [[VECEXT1_I_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I_I]]
//
v2uint32 test_ext_v2uint32(v16uint32 v, int idx) {
  return ext_v2uint32(v, idx);
}

// AIE2-LABEL: define dso_local noundef <4 x i8> @_Z20test_extract_v8uint4Dv64_DU8_i(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 0)
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <4 x i8> @_Z20test_extract_v8uint4Dv64_DU8_i(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i32 [[VECEXT_I_I_I_I]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP1]]
//
v8uint4 test_extract_v8uint4(v128uint4 v, int idx) {
  return extract_v8uint4(v, idx);
}

// AIE2-LABEL: define dso_local noundef <4 x i8> @_Z25test_extract_v8uint4_idx1Dv64_DU8_(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[TMP0]], i32 1, i32 0)
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <4 x i8> @_Z25test_extract_v8uint4_idx1Dv64_DU8_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i32 [[VECEXT_I_I_I_I]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP1]]
//
v8uint4 test_extract_v8uint4_idx1(v128uint4 v) {
  return extract_v8uint4(v, 1);
}

// AIE2-LABEL: define dso_local ptr @_Z17test_ext_address1Dv64_ai(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> [[V]], i32 [[IDX]], i32 0)
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// AIE2-NEXT:    ret ptr [[TMP1]]
//
// AIE2P-LABEL: define dso_local ptr @_Z17test_ext_address1Dv64_ai(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <64 x i8> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[CONV_I:%.*]] = sext i8 [[VECEXT_I_I]] to i20
// AIE2P-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// AIE2P-NEXT:    ret ptr [[TMP0]]
//
void * test_ext_address1(v64int8 v, int idx) {
  return ext_address(v, idx);
}

// AIE2-LABEL: define dso_local ptr @_Z17test_ext_address2Dv32_si(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[V]], i32 [[IDX]], i32 0)
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// AIE2-NEXT:    ret ptr [[TMP1]]
//
// AIE2P-LABEL: define dso_local ptr @_Z17test_ext_address2Dv32_si(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <32 x i16> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[CONV_I:%.*]] = sext i16 [[VECEXT_I_I]] to i20
// AIE2P-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// AIE2P-NEXT:    ret ptr [[TMP0]]
//
void * test_ext_address2(v32int16 v, int idx) {
  return ext_address(v, idx);
}

// AIE2-LABEL: define dso_local ptr @_Z17test_ext_address3Dv16_ii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[V]], i32 [[IDX]], i32 0)
// AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// AIE2-NEXT:    ret ptr [[TMP1]]
//
// AIE2P-LABEL: define dso_local ptr @_Z17test_ext_address3Dv16_ii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[VECEXT_I_I]] to i20
// AIE2P-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// AIE2P-NEXT:    ret ptr [[TMP0]]
//
void * test_ext_address3(v16int32 v, int idx) {
  return ext_address(v, idx);
}

/* Test Intrinsic using ACCFLOAT type */

// AIE2-LABEL: define dso_local noundef <8 x i64> @_Z11test_shiftxDv16_u10__accfloatS_ij(
// AIE2-SAME: <8 x i64> noundef [[A:%.*]], <8 x i64> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i64> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2-NEXT:    ret <8 x i64> [[TMP3]]
//
// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z11test_shiftxDv16_u10__accfloatS_ij(
// AIE2P-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16accfloat test_shiftx(v16accfloat a, v16accfloat b, int step, unsigned int shift) {
  return shiftx(a,b,step,shift);
}

// AIE2-LABEL: define dso_local noundef <8 x i64> @_Z16test_shift_bytesDv16_u10__accfloatS_j(
// AIE2-SAME: <8 x i64> noundef [[A:%.*]], <8 x i64> noundef [[B:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i64> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2-NEXT:    ret <8 x i64> [[TMP3]]
//
// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z16test_shift_bytesDv16_u10__accfloatS_j(
// AIE2P-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16accfloat test_shift_bytes(v16accfloat a, v16accfloat b, unsigned int shift) {
  return shift_bytes(a,b,shift);
}

// AIE2-LABEL: define dso_local noundef <8 x i64> @_Z10test_shiftDv16_u10__accfloatS_j(
// AIE2-SAME: <8 x i64> noundef [[A:%.*]], <8 x i64> noundef [[B:%.*]], i32 noundef [[SHIFT_BY:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[MUL_I:%.*]] = shl i32 [[SHIFT_BY]], 2
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <8 x i64> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[MUL_I]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2-NEXT:    ret <8 x i64> [[TMP3]]
//
// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z10test_shiftDv16_u10__accfloatS_j(
// AIE2P-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]], i32 noundef [[SHIFT_BY:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I:%.*]] = shl i32 [[SHIFT_BY]], 2
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[MUL_I]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16accfloat test_shift(v16accfloat a, v16accfloat b, unsigned int shift_by) {
  return shift(a, b, shift_by);
}

// AIE2-LABEL: define dso_local noundef <8 x i64> @_Z29test_broadcast_to_v16accfloatf(
// AIE2-SAME: float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast float [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP0]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <8 x i64>
// AIE2-NEXT:    ret <8 x i64> [[TMP2]]
//
// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z29test_broadcast_to_v16accfloatf(
// AIE2P-SAME: float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = insertelement <16 x float> poison, float [[B]], i64 0
// AIE2P-NEXT:    [[TMP1:%.*]] = shufflevector <16 x float> [[TMP0]], <16 x float> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x float> [[TMP1]]
//
v16accfloat test_broadcast_to_v16accfloat (float b) {
   return  broadcast_to_v16accfloat(b);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z26test_broadcast_to_v16floatf(
// AIE2-SAME: float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast float [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP0]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z26test_broadcast_to_v16floatf(
// AIE2P-SAME: float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = insertelement <16 x float> poison, float [[B]], i64 0
// AIE2P-NEXT:    [[TMP1:%.*]] = shufflevector <16 x float> [[TMP0]], <16 x float> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x float> [[TMP1]]
//
v16float test_broadcast_to_v16float (float b) {
   return  broadcast_to_v16float(b);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_shiftxDv32_8bfloat16S0_ij(
// AIE2-SAME: <32 x bfloat> noundef [[A:%.*]], <32 x bfloat> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vshift.bf512.bf512(<32 x bfloat> [[A]], <32 x bfloat> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_shiftxDv32_8bfloat16S0_ij(
// AIE2P-SAME: <32 x bfloat> noundef [[A:%.*]], <32 x bfloat> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> [[A]], <32 x bfloat> [[B]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_shiftx(v32bfloat16 a, v32bfloat16 b, int step, unsigned int shift) {
    return shiftx(a, b, step, shift);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iS_(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vinsert16.bf512(<32 x bfloat> [[V]], i32 [[IDX]], bfloat [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iS_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x bfloat> [[V]], bfloat [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x bfloat> [[VECINS_I_I]]
//
v32bfloat16 test_insert(v32bfloat16 v, int idx, bfloat16 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iDv2_S_(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vinsert32.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <2 x bfloat> [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iDv2_S_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert32.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <2 x bfloat> [[B]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_insert(v32bfloat16 v, int idx, v2bfloat16 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iDv4_S_(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vinsert64.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <4 x bfloat> [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iDv4_S_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert64.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <4 x bfloat> [[B]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_insert(v32bfloat16 v, int idx, v4bfloat16 b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iy(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[B]] to <4 x bfloat>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vinsert64.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <4 x bfloat> [[TMP0]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP1]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iy(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[B]] to <4 x bfloat>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert64.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <4 x bfloat> [[TMP0]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP1]]
//
v32bfloat16 test_insert(v32bfloat16 v, int idx, unsigned long long b) {
  return insert(v, idx,(v4bfloat16)b);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z29test_broadcast_to_v32bfloat168bfloat16(
// AIE2-SAME: bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z29test_broadcast_to_v32bfloat168bfloat16(
// AIE2P-SAME: bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <32 x bfloat> poison, bfloat [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <32 x bfloat> [[SPLAT_SPLATINSERT_I_I]], <32 x bfloat> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    ret <32 x bfloat> [[SPLAT_SPLAT_I_I]]
//
v32bfloat16 test_broadcast_to_v32bfloat16 (bfloat16 b) { return broadcast_to_v32bfloat16(b); }

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z29test_broadcast_to_v32bfloat16Dv2_8bfloat16(
// AIE2-SAME: <2 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast32.bf512(<2 x bfloat> [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z29test_broadcast_to_v32bfloat16Dv2_8bfloat16(
// AIE2P-SAME: <2 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vbroadcast32.bf512(<2 x bfloat> [[B]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_broadcast_to_v32bfloat16 (v2bfloat16 b) { return broadcast_to_v32bfloat16(b); }

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z29test_broadcast_to_v32bfloat16Dv4_8bfloat16(
// AIE2-SAME: <4 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast64.bf512(<4 x bfloat> [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z29test_broadcast_to_v32bfloat16Dv4_8bfloat16(
// AIE2P-SAME: <4 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vbroadcast64.bf512(<4 x bfloat> [[B]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_broadcast_to_v32bfloat16 (v4bfloat16 b) { return broadcast_to_v32bfloat16(b); }

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z21test_shuffle_bfloat168bfloat16j(
// AIE2-SAME: bfloat noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbcst.shuffle.bf16(bfloat [[B]], i32 [[M]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z21test_shuffle_bfloat168bfloat16j(
// AIE2P-SAME: bfloat noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast bfloat [[B]] to i16
// AIE2P-NEXT:    [[CONV_I:%.*]] = sext i16 [[TMP0]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vbcst.shuffle16(i32 [[CONV_I]], i32 [[M]])
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP2]]
//
v32bfloat16 test_shuffle_bfloat16(bfloat16 b, unsigned int m) {  return shuffle_bfloat16(b,m) ;}


// AIE2-LABEL: define dso_local noundef bfloat @_Z13test_ext_elemDv32_8bfloat16ii(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <32 x i16>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[ELEM_SROA_0_0_EXTRACT_TRUNC_I:%.*]] = trunc i32 [[TMP1]] to i16
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i16 [[ELEM_SROA_0_0_EXTRACT_TRUNC_I]] to bfloat
// AIE2-NEXT:    ret bfloat [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef bfloat @_Z13test_ext_elemDv32_8bfloat16ii(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = extractelement <32 x bfloat> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    ret bfloat [[TMP0]]
//
bfloat16 test_ext_elem(v32bfloat16 v, int idx, int sign) {
  return ext_elem(v, idx, sign);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z19test_broadcast_elemDv32_8bfloat16i(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vextract.broadcast32.bf512(<32 x bfloat> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z19test_broadcast_elemDv32_8bfloat16i(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vextract.broadcast32.bf512(<32 x bfloat> [[V]], i32 [[IDX]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_broadcast_elem (v32bfloat16 v, int idx) {
  return broadcast_elem(v, idx);
}

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z12test_shuffleDv32_8bfloat16S0_j(
// AIE2-SAME: <32 x bfloat> noundef [[A:%.*]], <32 x bfloat> noundef [[B:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vshuffle.bf16(<32 x bfloat> [[A]], <32 x bfloat> [[B]], i32 [[MODE]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z12test_shuffleDv32_8bfloat16S0_j(
// AIE2P-SAME: <32 x bfloat> noundef [[A:%.*]], <32 x bfloat> noundef [[B:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x bfloat> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[MODE]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP3]]
//
v32bfloat16 test_shuffle(v32bfloat16 a, v32bfloat16 b, unsigned int mode) {
  return shuffle(a, b, mode);
}

// AIE2-LABEL: define dso_local noundef <2 x bfloat> @_Z23test_extract_v2bfloat16Dv32_8bfloat16ii(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x bfloat>
// AIE2-NEXT:    ret <2 x bfloat> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <2 x bfloat> @_Z23test_extract_v2bfloat16Dv32_8bfloat16ii(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast i32 [[VECEXT_I_I_I]] to <2 x bfloat>
// AIE2P-NEXT:    ret <2 x bfloat> [[TMP1]]
//
v2bfloat16 test_extract_v2bfloat16(v32bfloat16 v, int idx, int sign) {
   return extract_v2bfloat16(v, idx, sign);
}



// AIE2-LABEL: define dso_local noundef <4 x bfloat> @_Z23test_extract_v4bfloat16Dv32_8bfloat16ii(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <4 x bfloat>
// AIE2-NEXT:    ret <4 x bfloat> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <4 x bfloat> @_Z23test_extract_v4bfloat16Dv32_8bfloat16ii(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = or disjoint i32 [[MUL_I_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I_I]], i32 [[VECEXT1_I_I_I]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINIT2_I_I_I]] to <4 x bfloat>
// AIE2P-NEXT:    ret <4 x bfloat> [[TMP1]]
//
v4bfloat16 test_extract_v4bfloat16(v32bfloat16 v, int idx, int sign) {
   return extract_v4bfloat16(v, idx, sign);
}


// AIE2-LABEL: define dso_local noundef <16 x float> @_Z11test_insertDv16_fif(
// AIE2-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast float [[B]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert32.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z11test_insertDv16_fif(
// AIE2P-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x float> [[V]], float [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <16 x float> [[VECINS_I_I]]
//
v16float test_insert(v16float v, int idx, float b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z12test_shuffleDv16_fS_j(
// AIE2-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshuffle(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[MODE]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z12test_shuffleDv16_fS_j(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[MODE]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16float test_shuffle(v16float a, v16float b, unsigned int mode) { return shuffle(a, b, mode); }

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z12test_shuffleDv16_fj(
// AIE2-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.aie2.v16float()
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[TMP0]] to <16 x i32>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call <16 x i32> @llvm.aie2.vshuffle(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]], i32 [[MODE]])
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[TMP3]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP4]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z12test_shuffleDv16_fj(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> [[TMP0]], <16 x i32> undef, i32 [[MODE]])
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP2]]
//
v16float test_shuffle(v16float a, unsigned int mode) {
  return shuffle(a, mode);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z11test_shiftxDv16_fS_ij(
// AIE2-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z11test_shiftxDv16_fS_ij(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[STEP]], i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16float test_shiftx(v16float a, v16float b, int step, unsigned int shift) {
  return shiftx(a,b,step,shift);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z16test_shift_bytesDv16_fS_j(
// AIE2-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z16test_shift_bytesDv16_fS_j(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[SHIFT]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16float test_shift_bytes(v16float a, v16float b, unsigned int shift) {
  return shift_bytes(a, b, shift);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z10test_shiftDv16_fS_j(
// AIE2-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[SHIFT_BY:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[MUL_I:%.*]] = shl i32 [[SHIFT_BY]], 2
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[MUL_I]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z10test_shiftDv16_fS_j(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], <16 x float> noundef [[B:%.*]], i32 noundef [[SHIFT_BY:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I:%.*]] = shl i32 [[SHIFT_BY]], 2
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 0, i32 [[MUL_I]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
v16float test_shift(v16float a, v16float b, unsigned int shift_by) {
  return shift(a, b, shift_by);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z16test_shiftl_elemDv16_ff(
// AIE2-SAME: <16 x float> noundef [[V:%.*]], float noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast float [[S]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP0]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP2]], <16 x i32> [[TMP1]], i32 0, i32 4)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[TMP3]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP4]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z16test_shiftl_elemDv16_ff(
// AIE2P-SAME: <16 x float> noundef [[V:%.*]], float noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = insertelement <16 x float> poison, float [[S]], i64 0
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[TMP0]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP1]], <16 x i32> [[TMP3]], i32 0, i32 4)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP4]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP5]]
//
v16float test_shiftl_elem(v16float v, float s) {
  return shiftl_elem(v, s);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z16test_shiftr_elemDv16_ff(
// AIE2-SAME: <16 x float> noundef [[V:%.*]], float noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast float [[S]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP0]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call <16 x i32> @llvm.aie2.vshift.I512.I512(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]], i32 0, i32 60)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[TMP3]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP4]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z16test_shiftr_elemDv16_ff(
// AIE2P-SAME: <16 x float> noundef [[V:%.*]], float noundef [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = insertelement <16 x float> poison, float [[S]], i64 0
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[TMP0]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP2]], <16 x i32> [[TMP3]], i32 0, i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP4]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP5]]
//
v16float test_shiftr_elem(v16float v, float s) {
  return shiftr_elem(v,s);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z19test_broadcast_elemDv16_fi(
// AIE2-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vextract.broadcast32.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z19test_broadcast_elemDv16_fi(
// AIE2P-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = or disjoint i32 [[MUL_I_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I_I]], i32 [[VECEXT1_I_I_I]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINIT2_I_I_I]] to <2 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = shufflevector <2 x float> [[TMP1]], <2 x float> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x float> [[TMP2]]
//
v16float test_broadcast_elem (v16float v, int idx) {
   return broadcast_elem(v, idx);
}

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z18test_shuffle_floatfj(
// AIE2-SAME: float noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast float [[B]] to i32
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vbcst.shuffle32(i32 [[TMP0]], i32 [[M]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z18test_shuffle_floatfj(
// AIE2P-SAME: float noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast float [[B]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vbcst.shuffle32(i32 [[TMP0]], i32 [[M]])
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP2]]
//
v16float test_shuffle_float(float b, unsigned int m) {  return shuffle_float(b,m) ;}
// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z15broadcast_Test1c(
// AIE2-SAME: i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i8 [[B]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vbroadcast8.I512(i32 [[CONV_I]])
// AIE2-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z15broadcast_Test1c(
// AIE2P-SAME: i8 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <64 x i8> poison, i8 [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <64 x i8> [[SPLAT_SPLATINSERT_I]], <64 x i8> poison, <64 x i32> zeroinitializer
// AIE2P-NEXT:    ret <64 x i8> [[SPLAT_SPLAT_I]]
//
v64int8 broadcast_Test1(char b) { return broadcast_s8(b); }
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z15broadcast_Test2s(
// AIE2-SAME: i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i16 [[B]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 [[CONV_I]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z15broadcast_Test2s(
// AIE2P-SAME: i16 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <32 x i16> poison, i16 [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    ret <32 x i16> [[SPLAT_SPLAT_I]]
//
v32int16 broadcast_Test2(short b) { return broadcast_s16(b); }
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z15broadcast_Test3i(
// AIE2-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[B]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z15broadcast_Test3i(
// AIE2P-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <16 x i32> poison, i32 [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x i32> [[SPLAT_SPLAT_I]]
//
v16int32 broadcast_Test3(int b) { return broadcast_s32(b); }

// AIE2-LABEL: define dso_local noundef <32 x bfloat> @_Z15broadcast_Test58bfloat16(
// AIE2-SAME: bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat [[B]])
// AIE2-NEXT:    ret <32 x bfloat> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z15broadcast_Test58bfloat16(
// AIE2P-SAME: bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I:%.*]] = insertelement <32 x bfloat> poison, bfloat [[B]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I:%.*]] = shufflevector <32 x bfloat> [[SPLAT_SPLATINSERT_I]], <32 x bfloat> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    ret <32 x bfloat> [[SPLAT_SPLAT_I]]
//
v32bfloat16 broadcast_Test5(bfloat16 b) { return broadcast_bfloat16(b); }

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z23extract_broadcast_Test1Dv64_ai(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vextract.broadcast8.I512(<64 x i8> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z23extract_broadcast_Test1Dv64_ai(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <64 x i8> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <64 x i8> poison, i8 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <64 x i8> [[SPLAT_SPLATINSERT_I_I]], <64 x i8> poison, <64 x i32> zeroinitializer
// AIE2P-NEXT:    ret <64 x i8> [[SPLAT_SPLAT_I_I]]
//
v64int8 extract_broadcast_Test1(v64int8 v, int idx) { return broadcast_elem(v, idx); }
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z23extract_broadcast_Test2Dv32_si(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vextract.broadcast16.I512(<32 x i16> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z23extract_broadcast_Test2Dv32_si(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <32 x i16> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <32 x i16> poison, i16 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <32 x i16> [[SPLAT_SPLATINSERT_I_I]], <32 x i16> poison, <32 x i32> zeroinitializer
// AIE2P-NEXT:    ret <32 x i16> [[SPLAT_SPLAT_I_I]]
//
v32int16 extract_broadcast_Test2(v32int16 v, int idx) { return broadcast_elem(v, idx); }
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z23extract_broadcast_Test3Dv16_ii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vextract.broadcast32.I512(<16 x i32> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z23extract_broadcast_Test3Dv16_ii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[IDX]]
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    ret <16 x i32> [[SPLAT_SPLAT_I_I]]
//
v16int32 extract_broadcast_Test3(v16int32 v, int idx) { return broadcast_elem(v, idx); }
// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z23extract_broadcast_Test4Dv16_ii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vextract.broadcast32.I512(<16 x i32> [[V]], i32 [[IDX]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z23extract_broadcast_Test4Dv16_ii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[MUL_I_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = or disjoint i32 [[MUL_I_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[ADD_I_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I_I]], i32 [[VECEXT1_I_I_I]], i64 1
// AIE2P-NEXT:    [[VECINIT30_I_I:%.*]] = shufflevector <2 x i32> [[VECINIT2_I_I_I]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x i32> [[VECINIT30_I_I]]
//
v16int32 extract_broadcast_Test4(v16int32 v, int idx) { return broadcast_elem_s64(v, idx); }

// AIE2-LABEL: define dso_local noundef <16 x float> @_Z23extract_broadcast_Test5Dv16_fi(
// AIE2-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2.vextract.broadcast32.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP2]]
//
// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z23extract_broadcast_Test5Dv16_fi(
// AIE2P-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = or disjoint i32 [[MUL_I_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I_I]], i32 [[VECEXT1_I_I_I]], i64 1
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINIT2_I_I_I]] to <2 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = shufflevector <2 x float> [[TMP1]], <2 x float> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x float> [[TMP2]]
//
v16float extract_broadcast_Test5(v16float v, int idx) { return broadcast_elem(v, idx); }
