// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2-store-load-TM.cpp -----------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2 -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK,CHECK-AIE2
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK,CHECK-AIE2P
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK,CHECK-AIE2PS

// CHECK-AIE2-LABEL: @_Z12test_read_tmj(
// CHECK-AIE2-NEXT:  entry:
// CHECK-AIE2-NEXT:    [[TMP0:%.*]] = xor i32 [[REGADDR:%.*]], 524288
// CHECK-AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// CHECK-AIE2-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef i32 @llvm.aie2.read.tm(ptr [[TMP1]])
// CHECK-AIE2-NEXT:    ret i32 [[TMP2]]
//
// CHECK-AIE2P-LABEL: @_Z12test_read_tmj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = xor i32 [[REGADDR:%.*]], 524288
// CHECK-AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef i32 @llvm.aie2p.read.tm(ptr [[TMP1]])
// CHECK-AIE2P-NEXT:    ret i32 [[TMP2]]
//
// CHECK-AIE2PS-LABEL: @_Z12test_read_tmj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = xor i32 [[REGADDR:%.*]], 524288
// CHECK-AIE2PS-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef i32 @llvm.aie2ps.read.tm(ptr [[TMP1]])
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP2]]
//
uint32 test_read_tm(uint32 regAddr) {
   return read_tm(regAddr);
}

// CHECK-AIE2-LABEL: @_Z13test_write_tmjj(
// CHECK-AIE2-NEXT:  entry:
// CHECK-AIE2-NEXT:    [[TMP0:%.*]] = xor i32 [[REGADDR:%.*]], 524288
// CHECK-AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// CHECK-AIE2-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2-NEXT:    tail call void @llvm.aie2.write.tm(i32 [[REGVAL:%.*]], ptr [[TMP1]])
// CHECK-AIE2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z13test_write_tmjj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = xor i32 [[REGADDR:%.*]], 524288
// CHECK-AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.write.tm(i32 [[REGVAL:%.*]], ptr [[TMP1]])
// CHECK-AIE2P-NEXT:    ret void
//
// CHECK-AIE2PS-LABEL: @_Z13test_write_tmjj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = xor i32 [[REGADDR:%.*]], 524288
// CHECK-AIE2PS-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.write.tm(i32 [[REGVAL:%.*]], ptr [[TMP1]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_write_tm(uint32 regVal, uint32 regAddr) {
   return write_tm(regVal, regAddr);
}

// CHECK-AIE2-LABEL: @_Z12test_read_tmjj(
// CHECK-AIE2-NEXT:  entry:
// CHECK-AIE2-NEXT:    [[ADD_I:%.*]] = add i32 [[TMADDRSPACESTART:%.*]], [[REGADDR:%.*]]
// CHECK-AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[ADD_I]] to i20
// CHECK-AIE2-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2.read.tm(ptr [[TMP0]])
// CHECK-AIE2-NEXT:    ret i32 [[TMP1]]
//
// CHECK-AIE2P-LABEL: @_Z12test_read_tmjj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[ADD_I:%.*]] = add i32 [[TMADDRSPACESTART:%.*]], [[REGADDR:%.*]]
// CHECK-AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[ADD_I]] to i20
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.read.tm(ptr [[TMP0]])
// CHECK-AIE2P-NEXT:    ret i32 [[TMP1]]
//
// CHECK-AIE2PS-LABEL: @_Z12test_read_tmjj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[ADD_I:%.*]] = add i32 [[TMADDRSPACESTART:%.*]], [[REGADDR:%.*]]
// CHECK-AIE2PS-NEXT:    [[CONV_I:%.*]] = trunc i32 [[ADD_I]] to i20
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.read.tm(ptr [[TMP0]])
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP1]]
//
uint32 test_read_tm(uint32 regAddr, uint32 TMAddrSpaceStart) {
   return read_tm(regAddr, TMAddrSpaceStart);
}

// CHECK-AIE2-LABEL: @_Z13test_write_tmjjj(
// CHECK-AIE2-NEXT:  entry:
// CHECK-AIE2-NEXT:    [[ADD_I:%.*]] = add i32 [[TMADDRSPACESTART:%.*]], [[REGADDR:%.*]]
// CHECK-AIE2-NEXT:    [[CONV_I:%.*]] = trunc i32 [[ADD_I]] to i20
// CHECK-AIE2-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2-NEXT:    tail call void @llvm.aie2.write.tm(i32 [[REGVAL:%.*]], ptr [[TMP0]])
// CHECK-AIE2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z13test_write_tmjjj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[ADD_I:%.*]] = add i32 [[TMADDRSPACESTART:%.*]], [[REGADDR:%.*]]
// CHECK-AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[ADD_I]] to i20
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.write.tm(i32 [[REGVAL:%.*]], ptr [[TMP0]])
// CHECK-AIE2P-NEXT:    ret void
//
// CHECK-AIE2PS-LABEL: @_Z13test_write_tmjjj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[ADD_I:%.*]] = add i32 [[TMADDRSPACESTART:%.*]], [[REGADDR:%.*]]
// CHECK-AIE2PS-NEXT:    [[CONV_I:%.*]] = trunc i32 [[ADD_I]] to i20
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.write.tm(i32 [[REGVAL:%.*]], ptr [[TMP0]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_write_tm(uint32 regVal, uint32 regAddr, uint32 TMAddrSpaceStart) {
   return write_tm(regVal, regAddr, TMAddrSpaceStart);
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
