// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aiev2-srs-intrinsics.cpp ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang %s --target=aie2 -nostdlibinc -S -emit-llvm -nostdlibinc -o - | FileCheck %s
// RUN: %clang %s --target=aie2p -nostdlibinc -S -emit-llvm -nostdlibinc -o - | FileCheck %s -check-prefix=CHECK-AIE2P

template <aie_dm_resource Resource, typename T> struct add_memory_bank { using type = T; };
template <aie_dm_resource Resource, typename T>
using add_memory_bank_t = typename add_memory_bank<Resource, T>::type;
template <aie_dm_resource Resource = aie_dm_resource::none>
__attribute__((always_inline))
void store_v_aligned(bfloat16 *ptr, v32bfloat16 data) {
    using aliased_type = add_memory_bank_t<Resource, aie_dm_resource_set_t<v32bfloat16, aie_dm_resource_get_v<bfloat16>>>;
    *(aliased_type*)ptr = data;
}
// CHECK-LABEL: @_Z20call_aligned_store_vv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[PTR_ADDR_I:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[DATA_ADDR_I:%.*]] = alloca <32 x bfloat>, align 32
// CHECK-NEXT:    [[BUFFER:%.*]] = alloca [32 x bfloat], align 2
// CHECK-NEXT:    [[DATA:%.*]] = alloca <32 x bfloat>, align 32
// CHECK-NEXT:    [[TMP0:%.*]] = call noundef <32 x bfloat> @llvm.aie2.v32bfloat16()
// CHECK-NEXT:    store <32 x bfloat> [[TMP0]], ptr [[DATA]], align 32
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds nuw [32 x bfloat], ptr [[BUFFER]], i32 0, i32 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x bfloat>, ptr [[DATA]], align 32
// CHECK-NEXT:    store ptr [[ARRAYDECAY]], ptr [[PTR_ADDR_I]], align 4
// CHECK-NEXT:    store <32 x bfloat> [[TMP1]], ptr [[DATA_ADDR_I]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = load <32 x bfloat>, ptr [[DATA_ADDR_I]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[PTR_ADDR_I]], align 4
// CHECK-NEXT:    store <32 x bfloat> [[TMP2]], ptr [[TMP3]], align 32
// CHECK-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z20call_aligned_store_vv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[PTR_ADDR_I:%.*]] = alloca ptr, align 4
// CHECK-AIE2P-NEXT:    [[DATA_ADDR_I:%.*]] = alloca <32 x bfloat>, align 64
// CHECK-AIE2P-NEXT:    [[VAL_I:%.*]] = alloca <32 x bfloat>, align 64
// CHECK-AIE2P-NEXT:    [[BUFFER:%.*]] = alloca [32 x bfloat], align 2
// CHECK-AIE2P-NEXT:    [[DATA:%.*]] = alloca <32 x bfloat>, align 64
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = load <32 x bfloat>, ptr [[VAL_I]], align 64
// CHECK-AIE2P-NEXT:    store <32 x bfloat> [[TMP0]], ptr [[DATA]], align 64
// CHECK-AIE2P-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds nuw [32 x bfloat], ptr [[BUFFER]], i32 0, i32 0
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x bfloat>, ptr [[DATA]], align 64
// CHECK-AIE2P-NEXT:    store ptr [[ARRAYDECAY]], ptr [[PTR_ADDR_I]], align 4
// CHECK-AIE2P-NEXT:    store <32 x bfloat> [[TMP1]], ptr [[DATA_ADDR_I]], align 64
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = load <32 x bfloat>, ptr [[DATA_ADDR_I]], align 64
// CHECK-AIE2P-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[PTR_ADDR_I]], align 4
// CHECK-AIE2P-NEXT:    store <32 x bfloat> [[TMP2]], ptr [[TMP3]], align 64
// CHECK-AIE2P-NEXT:    ret void
//
void call_aligned_store_v() {
    bfloat16 buffer[32];
    v32bfloat16 data = undef_v32bfloat16();
    store_v_aligned(buffer, data);
}
