// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-lut-intrinsic.cpp -----------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2 -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-COMMON -check-prefix=AIE2
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-COMMON -check-prefix=AIE2P

// AIE2-LABEL: @_Z19test_load_lut_int32PKvS0_Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> undef, <8 x i32> [[TMP8]], i32 0)
// AIE2-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP9]], <8 x i32> [[TMP10]], i32 1)
// AIE2-NEXT:    ret <16 x i32> [[TMP11]]
//
// AIE2P-LABEL: @_Z19test_load_lut_int32PKvS0_Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    ret <16 x i32> [[SHUFFLE2_I_I_I]]
//
v16int32 test_load_lut_int32(const void *lut1, const void *lut2,
                             v16int32 offset) {
  v16int32 res;
  load_lut_int32(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z22test_load_lut_2x_int32PKvS0_Dv16_iRS1_S2_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2:![0-9]+]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP0]], <8 x i32> [[TMP9]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP10]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP12:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP10]], <8 x i32> [[TMP11]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP12]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP13:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP15:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP13]], <8 x i32> [[TMP15]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP16]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP18:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP16]], <8 x i32> [[TMP17]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP18]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z22test_load_lut_2x_int32PKvS0_Dv16_iRS1_S2_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2:![0-9]+]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_int32(const void *lut1, const void *lut2, v16int32 offset,
                            v16int32 &v1, v16int32 &v2) {
  return load_lut_2x_int32(lut1, lut2, offset, v1, v2);
}

// AIE2-LABEL: @_Z19test_load_lut_int16PKvS0_Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> undef, <8 x i32> [[TMP8]], i32 0)
// AIE2-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP9]], <8 x i32> [[TMP10]], i32 1)
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[TMP11]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP12]]
//
// AIE2P-LABEL: @_Z19test_load_lut_int16PKvS0_Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP7:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP7]]
//
v32int16 test_load_lut_int16(const void *lut1, const void *lut2,
                             v16int32 offset) {
  v32int16 res;
  load_lut_int16(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z22test_load_lut_2x_int16PKvS0_Dv16_iRDv32_sS3_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP0]], <8 x i32> [[TMP9]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP10]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP12:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP10]], <8 x i32> [[TMP11]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP12]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP13:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP15:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.lo(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP13]], <8 x i32> [[TMP15]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP16]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.hi(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP18:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP16]], <8 x i32> [[TMP17]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP18]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z22test_load_lut_2x_int16PKvS0_Dv16_iRDv32_sS3_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_int16(const void *lut1, const void *lut2, v16int32 offset,
                            v32int16 &v1, v32int16 &v2) {
  return load_lut_2x_int16(lut1, lut2, offset, v1, v2);
}

// AIE2-LABEL: @_Z18test_load_lut_int8PKvS0_Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> undef, <8 x i32> [[TMP8]], i32 0)
// AIE2-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP9]], <8 x i32> [[TMP10]], i32 1)
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[TMP11]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP12]]
//
// AIE2P-LABEL: @_Z18test_load_lut_int8PKvS0_Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP7:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP7]]
//
v64int8 test_load_lut_int8(const void *lut1, const void *lut2,
                           v16int32 offset) {
  v64int8 res;
  load_lut_int8(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z21test_load_lut_2x_int8PKvS0_Dv16_iRDv64_aS3_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP0]], <8 x i32> [[TMP9]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP10]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP12:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP10]], <8 x i32> [[TMP11]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP12]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP13:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP15:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.lo(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP13]], <8 x i32> [[TMP15]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP16]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.hi(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP18:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP16]], <8 x i32> [[TMP17]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP18]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z21test_load_lut_2x_int8PKvS0_Dv16_iRDv64_aS3_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_int8(const void *lut1, const void *lut2, v16int32 offset,
                           v64int8 &v1, v64int8 &v2) {
  return load_lut_2x_int8(lut1, lut2, offset, v1, v2);
}

// AIE2-LABEL: @_Z19test_load_lut_int32PKvS0_Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> undef, <8 x i32> [[TMP8]], i32 0)
// AIE2-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP9]], <8 x i32> [[TMP10]], i32 1)
// AIE2-NEXT:    ret <16 x i32> [[TMP11]]
//
// AIE2P-LABEL: @_Z19test_load_lut_int32PKvS0_Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    ret <16 x i32> [[SHUFFLE2_I_I_I]]
//
v16int32 test_load_lut_int32(const void *lut1, const void *lut2,
                             v16uint32 offset) {
  v16int32 res;
  load_lut_int32(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z22test_load_lut_2x_int32PKvS0_Dv16_jRDv16_iS3_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP0]], <8 x i32> [[TMP9]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP10]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP12:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP10]], <8 x i32> [[TMP11]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP12]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP13:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP15:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP13]], <8 x i32> [[TMP15]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP16]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP18:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP16]], <8 x i32> [[TMP17]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP18]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z22test_load_lut_2x_int32PKvS0_Dv16_jRDv16_iS3_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_int32(const void *lut1, const void *lut2,
                            v16uint32 offset, v16int32 &v1, v16int32 &v2) {
  return load_lut_2x_int32(lut1, lut2, offset, v1, v2);
}

// AIE2-LABEL: @_Z19test_load_lut_int16PKvS0_Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> undef, <8 x i32> [[TMP8]], i32 0)
// AIE2-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP9]], <8 x i32> [[TMP10]], i32 1)
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[TMP11]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP12]]
//
// AIE2P-LABEL: @_Z19test_load_lut_int16PKvS0_Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP7:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP7]]
//
v32int16 test_load_lut_int16(const void *lut1, const void *lut2,
                             v16uint32 offset) {
  v32int16 res;
  load_lut_int16(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z22test_load_lut_2x_int16PKvS0_Dv16_jRDv32_sS3_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP0]], <8 x i32> [[TMP9]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP10]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP12:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP10]], <8 x i32> [[TMP11]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP12]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP13:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP15:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.lo(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP13]], <8 x i32> [[TMP15]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP16]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.hi(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP18:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP16]], <8 x i32> [[TMP17]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP18]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z22test_load_lut_2x_int16PKvS0_Dv16_jRDv32_sS3_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_int16(const void *lut1, const void *lut2,
                            v16uint32 offset, v32int16 &v1, v32int16 &v2) {
  return load_lut_2x_int16(lut1, lut2, offset, v1, v2);
}

// AIE2-LABEL: @_Z18test_load_lut_int8PKvS0_Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> undef, <8 x i32> [[TMP8]], i32 0)
// AIE2-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP9]], <8 x i32> [[TMP10]], i32 1)
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[TMP11]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP12]]
//
// AIE2P-LABEL: @_Z18test_load_lut_int8PKvS0_Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP7:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP7]]
//
v64int8 test_load_lut_int8(const void *lut1, const void *lut2,
                           v16uint32 offset) {
  v64int8 res;
  load_lut_int8(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z21test_load_lut_2x_int8PKvS0_Dv16_jRDv64_aS3_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP0]], <8 x i32> [[TMP9]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP10]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP12:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP10]], <8 x i32> [[TMP11]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP12]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP13:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP15:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.lo(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP13]], <8 x i32> [[TMP15]], i32 0)
// AIE2-NEXT:    store <16 x i32> [[TMP16]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.hi(<8 x i32> [[TMP14]])
// AIE2-NEXT:    [[TMP18:%.*]] = tail call <16 x i32> @llvm.aie2.upd.I512.I256(<16 x i32> [[TMP16]], <8 x i32> [[TMP17]], i32 1)
// AIE2-NEXT:    store <16 x i32> [[TMP18]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z21test_load_lut_2x_int8PKvS0_Dv16_jRDv64_aS3_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_int8(const void *lut1, const void *lut2, v16uint32 offset,
                           v64int8 &v1, v64int8 &v2) {
  return load_lut_2x_int8(lut1, lut2, offset, v1, v2);
}

// AIE2-LABEL: @_Z19test_load_lut_floatPKvS0_Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = bitcast <8 x i32> [[TMP8]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> undef, <16 x bfloat> [[TMP9]], i32 0)
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <8 x i32> [[TMP11]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP13:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP10]], <16 x bfloat> [[TMP12]], i32 1)
// AIE2-NEXT:    ret <32 x bfloat> [[TMP13]]
//
// AIE2P-LABEL: @_Z19test_load_lut_floatPKvS0_Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP7:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP7]]
//
v32bfloat16 test_load_lut_float(const void *lut1, const void *lut2,
                                v16int32 offset) {
  v32bfloat16 res;
  load_lut_float(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z22test_load_lut_2x_floatPKvS0_Dv16_iRDv32_u6__bf16S3_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <32 x bfloat>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <8 x i32> [[TMP9]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP10]], i32 0)
// AIE2-NEXT:    store <32 x bfloat> [[TMP11]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP12:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP13:%.*]] = bitcast <8 x i32> [[TMP12]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP11]], <16 x bfloat> [[TMP13]], i32 1)
// AIE2-NEXT:    store <32 x bfloat> [[TMP14]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP15:%.*]] = load <32 x bfloat>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP16]])
// AIE2-NEXT:    [[TMP18:%.*]] = bitcast <8 x i32> [[TMP17]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP19:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP15]], <16 x bfloat> [[TMP18]], i32 0)
// AIE2-NEXT:    store <32 x bfloat> [[TMP19]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP20:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP16]])
// AIE2-NEXT:    [[TMP21:%.*]] = bitcast <8 x i32> [[TMP20]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP22:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP19]], <16 x bfloat> [[TMP21]], i32 1)
// AIE2-NEXT:    store <32 x bfloat> [[TMP22]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z22test_load_lut_2x_floatPKvS0_Dv16_iRDv32_u6__bf16S3_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_float(const void *lut1, const void *lut2, v16int32 offset,
                            v32bfloat16 &v1, v32bfloat16 &v2) {
  return load_lut_2x_float(lut1, lut2, offset, v1, v2);
}

// AIE2-LABEL: @_Z19test_load_lut_floatPKvS0_Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP7:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = bitcast <8 x i32> [[TMP8]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP10:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> undef, <16 x bfloat> [[TMP9]], i32 0)
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP7]])
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <8 x i32> [[TMP11]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP13:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP10]], <16 x bfloat> [[TMP12]], i32 1)
// AIE2-NEXT:    ret <32 x bfloat> [[TMP13]]
//
// AIE2P-LABEL: @_Z19test_load_lut_floatPKvS0_Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP7:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP7]]
//
v32bfloat16 test_load_lut_float(const void *lut1, const void *lut2,
                                v16uint32 offset) {
  v32bfloat16 res;
  load_lut_float(lut1, lut2, offset, res);
  return res;
}

// AIE2-LABEL: @_Z22test_load_lut_2x_floatPKvS0_Dv16_jRDv32_u6__bf16S3_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = load <32 x bfloat>, ptr [[V1:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP2]])
// AIE2-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = zext i20 [[TMP4]] to i32
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP5]])
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP3]], <16 x i32> [[TMP6]], i32 52428)
// AIE2-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP7]], [[OFFSET:%.*]]
// AIE2-NEXT:    [[TMP8:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <8 x i32> [[TMP9]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP11:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP10]], i32 0)
// AIE2-NEXT:    store <32 x bfloat> [[TMP11]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP12:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP8]])
// AIE2-NEXT:    [[TMP13:%.*]] = bitcast <8 x i32> [[TMP12]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP14:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP11]], <16 x bfloat> [[TMP13]], i32 1)
// AIE2-NEXT:    store <32 x bfloat> [[TMP14]], ptr [[V1]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP15:%.*]] = load <32 x bfloat>, ptr [[V2:%.*]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP16:%.*]] = tail call <8 x i32> @llvm.aie2.ext.I256.I512(<16 x i32> [[ADD_I_I_I]], i32 1)
// AIE2-NEXT:    [[TMP17:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[TMP16]])
// AIE2-NEXT:    [[TMP18:%.*]] = bitcast <8 x i32> [[TMP17]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP19:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP15]], <16 x bfloat> [[TMP18]], i32 0)
// AIE2-NEXT:    store <32 x bfloat> [[TMP19]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[TMP20:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[TMP16]])
// AIE2-NEXT:    [[TMP21:%.*]] = bitcast <8 x i32> [[TMP20]] to <16 x bfloat>
// AIE2-NEXT:    [[TMP22:%.*]] = tail call <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP19]], <16 x bfloat> [[TMP21]], i32 1)
// AIE2-NEXT:    store <32 x bfloat> [[TMP22]], ptr [[V2]], align 32, !tbaa [[TBAA2]]
// AIE2-NEXT:    ret void
//
// AIE2P-LABEL: @_Z22test_load_lut_2x_floatPKvS0_Dv16_jRDv32_u6__bf16S3_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load <16 x i32>, ptr [[V1:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = zext i20 [[TMP1]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP2]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP4]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I_I_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add <16 x i32> [[TMP5]], [[OFFSET:%.*]]
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I29_I:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE_I_I29_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I_I]], ptr [[V1]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP8:%.*]] = load <16 x i32>, ptr [[V2:%.*]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[ADD_I_I_I]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I35_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I36_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I35_I]], <16 x i32> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE1_I_I36_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[SHUFFLE1_I_I_I_I]])
// AIE2P-NEXT:    [[SHUFFLE_I_I43_I:%.*]] = shufflevector <8 x i32> [[TMP10]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE2_I_I44_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I36_I]], <16 x i32> [[SHUFFLE_I_I43_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// AIE2P-NEXT:    store <16 x i32> [[SHUFFLE2_I_I44_I]], ptr [[V2]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
void test_load_lut_2x_float(const void *lut1, const void *lut2,
                            v16uint32 offset, v32bfloat16 &v1,
                            v32bfloat16 &v2) {
  return load_lut_2x_float(lut1, lut2, offset, v1, v2);
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-COMMON: {{.*}}
