// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-vadd-intrinsics.cpp --------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2 -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK-COMMON,AIE2
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK-COMMON,AIE2P
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK-COMMON,AIE2PS


// CHECK-COMMON-LABEL: @_Z17test_add_v64uint8Dv64_hS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[ADD_I:%.*]] = add <64 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[ADD_I]]
//
v64uint8 test_add_v64uint8(v64uint8 a, v64uint8 b) { return add(a, b); }

// CHECK-COMMON-LABEL: @_Z17test_sub_v64uint8Dv64_hS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[SUB_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[SUB_I]]
//
v64uint8 test_sub_v64uint8(v64uint8 a, v64uint8 b) { return sub(a, b); }

// AIE2-LABEL: @_Z20test_addsub_v64uint8Dv64_hS_y(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[AS:%.*]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vaddsub8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z20test_addsub_v64uint8Dv64_hS_y(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[AS:%.*]] to <2 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.vaddsub8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_addsub_v64uint8Dv64_hS_y(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast i64 [[AS:%.*]] to <2 x i32>
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.vaddsub8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_addsub_v64uint8(v64uint8 a, v64uint8 b, unsigned long long as) {
  return addsub(a, b, as);
}

// AIE2-LABEL: @_Z21test_neg_gtz_v64uint8Dv64_hRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_neg_gtz_v64uint8Dv64_hRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_neg_gtz_v64uint8Dv64_hRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_neg_gtz_v64uint8(v64uint8 a, unsigned long long &cmp) {
  return neg_gtz(a, cmp);
}

// AIE2-LABEL: @_Z17test_neg_v64uint8Dv64_h(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_neg_v64uint8Dv64_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_neg_v64uint8Dv64_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_neg_v64uint8(v64uint8 a) { return neg(a); }

// AIE2-LABEL: @_Z20test_sub_lt_v64uint8Dv64_hS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_lt_v64uint8Dv64_hS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_lt_v64uint8Dv64_hS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_sub_lt_v64uint8(v64uint8 a, v64uint8 b, unsigned long long &cmp) {
  return sub_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_sub_lt_v64uint8Dv64_hS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_lt_v64uint8Dv64_hS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_lt_v64uint8Dv64_hS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_sub_lt_v64uint8(v64uint8 a, v64uint8 b, bool sgn,
                              unsigned long long &cmp) {
  return sub_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z20test_sub_ge_v64uint8Dv64_hS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_ge_v64uint8Dv64_hS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_ge_v64uint8Dv64_hS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_sub_ge_v64uint8(v64uint8 a, v64uint8 b, unsigned long long &cmp) {
  return sub_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_sub_ge_v64uint8Dv64_hS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_ge_v64uint8Dv64_hS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_ge_v64uint8Dv64_hS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_sub_ge_v64uint8(v64uint8 a, v64uint8 b, bool sgn,
                              unsigned long long &cmp) {
  return sub_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z24test_maxdiff_lt_v64uint8Dv64_hS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z24test_maxdiff_lt_v64uint8Dv64_hS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z24test_maxdiff_lt_v64uint8Dv64_hS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_maxdiff_lt_v64uint8(v64uint8 a, v64uint8 b,
                                  unsigned long long &cmp) {
  return maxdiff_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z24test_maxdiff_lt_v64uint8Dv64_hS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z24test_maxdiff_lt_v64uint8Dv64_hS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z24test_maxdiff_lt_v64uint8Dv64_hS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_maxdiff_lt_v64uint8(v64uint8 a, v64uint8 b, bool sgn,
                                  unsigned long long &cmp) {
  return maxdiff_lt(a, b, sgn, cmp);
}

//
// AIE2-LABEL: @_Z21test_maxdiff_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z21test_maxdiff_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_maxdiff_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_maxdiff_v64uint8(v64uint8 a, v64uint8 b) { return maxdiff(a, b); }

// AIE2-LABEL: @_Z21test_maxdiff_v64uint8Dv64_hS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z21test_maxdiff_v64uint8Dv64_hS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_maxdiff_v64uint8Dv64_hS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_maxdiff_v64uint8(v64uint8 a, v64uint8 b, bool sgn) {
  return maxdiff(a, b, sgn);
}

// AIE2-LABEL: @_Z20test_min_ge_v64uint8Dv64_hS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_min_ge_v64uint8Dv64_hS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_min_ge_v64uint8Dv64_hS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_min_ge_v64uint8(v64uint8 a, v64uint8 b, unsigned long long &cmp) {
  return min_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_min_ge_v64uint8Dv64_hS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_min_ge_v64uint8Dv64_hS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_min_ge_v64uint8Dv64_hS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_min_ge_v64uint8(v64uint8 a, v64uint8 b, bool sgn,
                              unsigned long long &cmp) {
  return min_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_min_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_min_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_min_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_min_v64uint8(v64uint8 a, v64uint8 b) { return min(a, b); }

// AIE2-LABEL: @_Z17test_min_v64uint8Dv64_hS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_min_v64uint8Dv64_hS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_min_v64uint8Dv64_hS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_min_v64uint8(v64uint8 a, v64uint8 b, bool sgn) {
  return min(a, b, sgn);
}

// AIE2-LABEL: @_Z20test_max_lt_v64uint8Dv64_hS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_max_lt_v64uint8Dv64_hS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_max_lt_v64uint8Dv64_hS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_max_lt_v64uint8(v64uint8 a, v64uint8 b, unsigned long long &cmp) {
  return max_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_max_lt_v64uint8Dv64_hS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_max_lt_v64uint8Dv64_hS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_max_lt_v64uint8Dv64_hS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_max_lt_v64uint8(v64uint8 a, v64uint8 b, bool sgn,
                              unsigned long long &cmp) {
  return max_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_max_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_max_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_max_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_max_v64uint8(v64uint8 a, v64uint8 b) { return max(a, b); }

// AIE2-LABEL: @_Z17test_max_v64uint8Dv64_hS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_max_v64uint8Dv64_hS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_max_v64uint8Dv64_hS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_max_v64uint8(v64uint8 a, v64uint8 b, bool sgn) {
  return max(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z18test_band_v64uint8Dv64_hS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <64 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[AND_I]]
//
v64uint8 test_band_v64uint8(v64uint8 a, v64uint8 b) { return band(a, b); }

// CHECK-COMMON-LABEL: @_Z17test_bor_v64uint8Dv64_hS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <64 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[OR_I]]
//
v64uint8 test_bor_v64uint8(v64uint8 a, v64uint8 b) { return bor(a, b); }

// AIE2-LABEL: @_Z22test_bneg_ltz_v64uint8Dv64_hRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    store i64 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA2:![0-9]+]]
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z22test_bneg_ltz_v64uint8Dv64_hRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    store i64 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA2:![0-9]+]]
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_bneg_ltz_v64uint8Dv64_hRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    store i64 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA2:![0-9]+]]
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_bneg_ltz_v64uint8(v64uint8 a, unsigned long long &cmp) {
  return bneg_ltz(a, cmp);
}

// AIE2-LABEL: @_Z22test_bneg_ltz_v64uint8Dv64_hbRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    br i1 [[SGN:%.*]], label [[_ZL8BNEG_LTZDV64_HBRY_EXIT:%.*]], label [[IF_THEN_I:%.*]]
// AIE2:       if.then.i:
// AIE2-NEXT:    store i64 0, ptr [[CMP]], align 4, !tbaa [[TBAA2]]
// AIE2-NEXT:    br label [[_ZL8BNEG_LTZDV64_HBRY_EXIT]]
// AIE2:       _ZL8bneg_ltzDv64_hbRy.exit:
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_bneg_ltz_v64uint8Dv64_hbRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    br i1 [[SGN:%.*]], label [[_ZL8BNEG_LTZDV64_HBRY_EXIT:%.*]], label [[IF_THEN_I:%.*]]
// AIE2P:       if.then.i:
// AIE2P-NEXT:    store i64 0, ptr [[CMP]], align 4, !tbaa [[TBAA2]]
// AIE2P-NEXT:    br label [[_ZL8BNEG_LTZDV64_HBRY_EXIT]]
// AIE2P:       _ZL8bneg_ltzDv64_hbRy.exit:
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_bneg_ltz_v64uint8Dv64_hbRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    br i1 [[SGN:%.*]], label [[_ZL8BNEG_LTZDV64_HBRY_EXIT:%.*]], label [[IF_THEN_I:%.*]]
// AIE2PS:       if.then.i:
// AIE2PS-NEXT:    store i64 0, ptr [[CMP]], align 4, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    br label [[_ZL8BNEG_LTZDV64_HBRY_EXIT]]
// AIE2PS:       _ZL8bneg_ltzDv64_hbRy.exit:
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_bneg_ltz_v64uint8(v64uint8 a, bool sgn, unsigned long long &cmp) {
  return bneg_ltz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z18test_bneg_v64uint8Dv64_h(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_bneg_v64uint8Dv64_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_bneg_v64uint8Dv64_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_bneg_v64uint8(v64uint8 a) { return bneg(a); }

// AIE2-LABEL: @_Z18test_bxor_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[B:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP1]], [[A:%.*]]
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A]])
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// AIE2-NEXT:    [[AND_I7_I:%.*]] = and <64 x i8> [[TMP3]], [[B]]
// AIE2-NEXT:    [[OR_I_I:%.*]] = or <64 x i8> [[AND_I7_I]], [[AND_I_I]]
// AIE2-NEXT:    ret <64 x i8> [[OR_I_I]]
//
// AIE2P-LABEL: @_Z18test_bxor_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[B:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP1]], [[A:%.*]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// AIE2P-NEXT:    [[AND_I7_I:%.*]] = and <64 x i8> [[TMP3]], [[B]]
// AIE2P-NEXT:    [[OR_I_I:%.*]] = or <64 x i8> [[AND_I7_I]], [[AND_I_I]]
// AIE2P-NEXT:    ret <64 x i8> [[OR_I_I]]
//
// AIE2PS-LABEL: @_Z18test_bxor_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[B:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP1]], [[A:%.*]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// AIE2PS-NEXT:    [[AND_I7_I:%.*]] = and <64 x i8> [[TMP3]], [[B]]
// AIE2PS-NEXT:    [[OR_I_I:%.*]] = or <64 x i8> [[AND_I7_I]], [[AND_I_I]]
// AIE2PS-NEXT:    ret <64 x i8> [[OR_I_I]]
//
v64uint8 test_bxor_v64uint8(v64uint8 a, v64uint8 b) { return bxor(a, b); }

// AIE2-LABEL: @_Z21test_abs_gtz_v64uint8Dv64_hRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_abs_gtz_v64uint8Dv64_hRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_abs_gtz_v64uint8Dv64_hRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_abs_gtz_v64uint8(v64uint8 a, unsigned long long &cmp) {
  return abs_gtz(a, cmp);
}

//
// AIE2-LABEL: @_Z21test_abs_gtz_v64uint8Dv64_hbRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_abs_gtz_v64uint8Dv64_hbRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_abs_gtz_v64uint8Dv64_hbRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_abs_gtz_v64uint8(v64uint8 a, bool sgn, unsigned long long &cmp) {
  return abs_gtz(a, sgn, cmp);
}

//
// CHECK-COMMON-LABEL: @_Z17test_abs_v64uint8Dv64_h(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    ret <64 x i8> [[A:%.*]]
//
v64uint8 test_abs_v64uint8(v64uint8 a) { return abs(a); }

// AIE2-LABEL: @_Z17test_abs_v64uint8Dv64_hb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_abs_v64uint8Dv64_hb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_abs_v64uint8Dv64_hb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_abs_v64uint8(v64uint8 a, bool sgn) { return abs(a, sgn); }

// AIE2-LABEL: @_Z16test_lt_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_lt_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_lt_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_lt_v64uint8(v64uint8 a, v64uint8 b) { return lt(a, b); }

// AIE2-LABEL: @_Z16test_ge_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_ge_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_ge_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_ge_v64uint8(v64uint8 a, v64uint8 b) { return ge(a, b); }

// AIE2-LABEL: @_Z16test_le_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_le_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_le_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_le_v64uint8(v64uint8 a, v64uint8 b) { return le(a, b); }

// AIE2-LABEL: @_Z16test_gt_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_gt_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_gt_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_gt_v64uint8(v64uint8 a, v64uint8 b) { return gt(a, b); }

// AIE2-LABEL: @_Z16test_lt_v64uint8Dv64_hS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_lt_v64uint8Dv64_hS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_lt_v64uint8Dv64_hS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_lt_v64uint8(v64uint8 a, v64uint8 b, bool sgn) {
  return lt(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_ge_v64uint8Dv64_hS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_ge_v64uint8Dv64_hS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_ge_v64uint8Dv64_hS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_ge_v64uint8(v64uint8 a, v64uint8 b, bool sgn) {
  return ge(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_le_v64uint8Dv64_hS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_le_v64uint8Dv64_hS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_le_v64uint8Dv64_hS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_le_v64uint8(v64uint8 a, v64uint8 b, bool sgn) {
  return le(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_gt_v64uint8Dv64_hS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_gt_v64uint8Dv64_hS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_gt_v64uint8Dv64_hS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_gt_v64uint8(v64uint8 a, v64uint8 b, bool sgn) {
  return gt(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z17test_ltz_v64uint8Dv64_h(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    ret i64 0
//
unsigned long long test_ltz_v64uint8(v64uint8 a) { return ltz(a); }

// AIE2-LABEL: @_Z17test_ltz_v64uint8Dv64_hb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i64 [[TMP2]], i64 0
// AIE2-NEXT:    ret i64 [[SPEC_SELECT_I]]
//
// AIE2P-LABEL: @_Z17test_ltz_v64uint8Dv64_hb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2P-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i64 [[TMP2]], i64 0
// AIE2P-NEXT:    ret i64 [[SPEC_SELECT_I]]
//
// AIE2PS-LABEL: @_Z17test_ltz_v64uint8Dv64_hb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2PS-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i64 [[TMP2]], i64 0
// AIE2PS-NEXT:    ret i64 [[SPEC_SELECT_I]]
//
unsigned long long test_ltz_v64uint8(v64uint8 a, bool sgn) {
  return ltz(a, sgn);
}

// AIE2-LABEL: @_Z17test_gtz_v64uint8Dv64_h(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
// AIE2P-LABEL: @_Z17test_gtz_v64uint8Dv64_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2P-NEXT:    ret i64 [[TMP2]]
//
// AIE2PS-LABEL: @_Z17test_gtz_v64uint8Dv64_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_gtz_v64uint8(v64uint8 a) { return gtz(a); }

// AIE2-LABEL: @_Z17test_gtz_v64uint8Dv64_hb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
// AIE2P-LABEL: @_Z17test_gtz_v64uint8Dv64_hb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2P-NEXT:    ret i64 [[TMP2]]
//
// AIE2PS-LABEL: @_Z17test_gtz_v64uint8Dv64_hb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_gtz_v64uint8(v64uint8 a, bool sgn) {
  return gtz(a, sgn);
}

// AIE2-LABEL: @_Z17test_eqz_v64uint8Dv64_h(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.veqz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_eqz_v64uint8Dv64_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.veqz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_eqz_v64uint8Dv64_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_eqz_v64uint8(v64uint8 a) { return eqz(a); }

// AIE2-LABEL: @_Z16test_eq_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.veqz8(<64 x i8> [[SUB_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_eq_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.veqz8(<64 x i8> [[SUB_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_eq_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[SUB_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_eq_v64uint8(v64uint8 a, v64uint8 b) { return eq(a, b); }

// AIE2-LABEL: @_Z16test_ne_v64uint8Dv64_hS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.veqz8(<64 x i8> [[SUB_I_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    [[NOT_I:%.*]] = xor i64 [[TMP1]], -1
// AIE2-NEXT:    ret i64 [[NOT_I]]
//
// AIE2P-LABEL: @_Z16test_ne_v64uint8Dv64_hS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.veqz8(<64 x i8> [[SUB_I_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    [[NOT_I:%.*]] = xor i64 [[TMP1]], -1
// AIE2P-NEXT:    ret i64 [[NOT_I]]
//
// AIE2PS-LABEL: @_Z16test_ne_v64uint8Dv64_hS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[SUB_I_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    [[XOR_I:%.*]] = xor i64 [[TMP1]], -1
// AIE2PS-NEXT:    ret i64 [[XOR_I]]
//
unsigned long long test_ne_v64uint8(v64uint8 a, v64uint8 b) { return ne(a, b); }

// AIE2-LABEL: @_Z17test_sel_v64uint8Dv64_hS_y(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vsel8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_sel_v64uint8Dv64_hS_y(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.vsel8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_sel_v64uint8Dv64_hS_y(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.vsel8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_sel_v64uint8(v64uint8 a, v64uint8 b, unsigned long long s) {
  return sel(a, b, s);
}

// CHECK-COMMON-LABEL: @_Z16test_add_v64int8Dv64_aS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[ADD_I:%.*]] = add <64 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[ADD_I]]
//
v64int8 test_add_v64int8(v64int8 a, v64int8 b) { return add(a, b); }

// CHECK-COMMON-LABEL: @_Z16test_sub_v64int8Dv64_aS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[SUB_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[SUB_I]]
//
v64int8 test_sub_v64int8(v64int8 a, v64int8 b) { return sub(a, b); }

// AIE2-LABEL: @_Z19test_addsub_v64int8Dv64_aS_y(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[AS:%.*]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vaddsub8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z19test_addsub_v64int8Dv64_aS_y(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[AS:%.*]] to <2 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.vaddsub8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z19test_addsub_v64int8Dv64_aS_y(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast i64 [[AS:%.*]] to <2 x i32>
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.vaddsub8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_addsub_v64int8(v64int8 a, v64int8 b, unsigned long long as) {
  return addsub(a, b, as);
}

// AIE2-LABEL: @_Z20test_neg_gtz_v64int8Dv64_aRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_neg_gtz_v64int8Dv64_aRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_neg_gtz_v64int8Dv64_aRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_neg_gtz_v64int8(v64int8 a, unsigned long long &cmp) {
  return neg_gtz(a, cmp);
}

// AIE2-LABEL: @_Z16test_neg_v64int8Dv64_a(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_neg_v64int8Dv64_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_neg_v64int8Dv64_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vneg.gtz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_neg_v64int8(v64int8 a) { return neg(a); }

// AIE2-LABEL: @_Z19test_sub_lt_v64int8Dv64_aS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_sub_lt_v64int8Dv64_aS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_sub_lt_v64int8Dv64_aS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_sub_lt_v64int8(v64int8 a, v64int8 b, unsigned long long &cmp) {
  return sub_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z19test_sub_lt_v64int8Dv64_aS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_sub_lt_v64int8Dv64_aS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_sub_lt_v64int8Dv64_aS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_sub_lt_v64int8(v64int8 a, v64int8 b, bool sgn,
                            unsigned long long &cmp) {
  return sub_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z19test_sub_ge_v64int8Dv64_aS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_sub_ge_v64int8Dv64_aS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_sub_ge_v64int8Dv64_aS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_sub_ge_v64int8(v64int8 a, v64int8 b, unsigned long long &cmp) {
  return sub_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z19test_sub_ge_v64int8Dv64_aS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_sub_ge_v64int8Dv64_aS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_sub_ge_v64int8Dv64_aS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vsub.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_sub_ge_v64int8(v64int8 a, v64int8 b, bool sgn,
                            unsigned long long &cmp) {
  return sub_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z23test_maxdiff_lt_v64int8Dv64_aS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z23test_maxdiff_lt_v64int8Dv64_aS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z23test_maxdiff_lt_v64int8Dv64_aS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_maxdiff_lt_v64int8(v64int8 a, v64int8 b, unsigned long long &cmp) {
  return maxdiff_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z23test_maxdiff_lt_v64int8Dv64_aS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z23test_maxdiff_lt_v64int8Dv64_aS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z23test_maxdiff_lt_v64int8Dv64_aS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_maxdiff_lt_v64int8(v64int8 a, v64int8 b, bool sgn,
                                unsigned long long &cmp) {
  return maxdiff_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z20test_maxdiff_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z20test_maxdiff_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_maxdiff_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_maxdiff_v64int8(v64int8 a, v64int8 b) { return maxdiff(a, b); }

// AIE2-LABEL: @_Z20test_maxdiff_v64int8Dv64_aS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z20test_maxdiff_v64int8Dv64_aS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_maxdiff_v64int8Dv64_aS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmaxdiff.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_maxdiff_v64int8(v64int8 a, v64int8 b, bool sgn) {
  return maxdiff(a, b, sgn);
}

// AIE2-LABEL: @_Z19test_min_ge_v64int8Dv64_aS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_min_ge_v64int8Dv64_aS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_min_ge_v64int8Dv64_aS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_min_ge_v64int8(v64int8 a, v64int8 b, unsigned long long &cmp) {
  return min_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z19test_min_ge_v64int8Dv64_aS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_min_ge_v64int8Dv64_aS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_min_ge_v64int8Dv64_aS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_min_ge_v64int8(v64int8 a, v64int8 b, bool sgn,
                            unsigned long long &cmp) {
  return min_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z16test_min_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_min_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_min_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_min_v64int8(v64int8 a, v64int8 b) { return min(a, b); }

// AIE2-LABEL: @_Z16test_min_v64int8Dv64_aS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_min_v64int8Dv64_aS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_min_v64int8Dv64_aS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.ge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_min_v64int8(v64int8 a, v64int8 b, bool sgn) {
  return min(a, b, sgn);
}

// AIE2-LABEL: @_Z19test_max_lt_v64int8Dv64_aS_Ry(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_max_lt_v64int8Dv64_aS_Ry(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_max_lt_v64int8Dv64_aS_Ry(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_max_lt_v64int8(v64int8 a, v64int8 b, unsigned long long &cmp) {
  return max_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z19test_max_lt_v64int8Dv64_aS_bRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z19test_max_lt_v64int8Dv64_aS_bRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_max_lt_v64int8Dv64_aS_bRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_max_lt_v64int8(v64int8 a, v64int8 b, bool sgn,
                            unsigned long long &cmp) {
  return max_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z16test_max_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_max_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_max_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_max_v64int8(v64int8 a, v64int8 b) { return max(a, b); }

// AIE2-LABEL: @_Z16test_max_v64int8Dv64_aS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_max_v64int8Dv64_aS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_max_v64int8Dv64_aS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.lt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_max_v64int8(v64int8 a, v64int8 b, bool sgn) {
  return max(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z17test_band_v64int8Dv64_aS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <64 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[AND_I]]
//
v64int8 test_band_v64int8(v64int8 a, v64int8 b) { return band(a, b); }

// CHECK-COMMON-LABEL: @_Z16test_bor_v64int8Dv64_aS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <64 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <64 x i8> [[OR_I]]
//
v64int8 test_bor_v64int8(v64int8 a, v64int8 b) { return bor(a, b); }

// AIE2-LABEL: @_Z21test_bneg_ltz_v64int8Dv64_aRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_bneg_ltz_v64int8Dv64_aRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_bneg_ltz_v64int8Dv64_aRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_bneg_ltz_v64int8(v64int8 a, unsigned long long &cmp) {
  return bneg_ltz(a, cmp);
}

// AIE2-LABEL: @_Z21test_bneg_ltz_v64int8Dv64_abRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    br i1 [[SGN:%.*]], label [[_ZL8BNEG_LTZDV64_ABRY_EXIT:%.*]], label [[IF_THEN_I:%.*]]
// AIE2:       if.then.i:
// AIE2-NEXT:    store i64 0, ptr [[CMP]], align 4, !tbaa [[TBAA2]]
// AIE2-NEXT:    br label [[_ZL8BNEG_LTZDV64_ABRY_EXIT]]
// AIE2:       _ZL8bneg_ltzDv64_abRy.exit:
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_bneg_ltz_v64int8Dv64_abRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    br i1 [[SGN:%.*]], label [[_ZL8BNEG_LTZDV64_ABRY_EXIT:%.*]], label [[IF_THEN_I:%.*]]
// AIE2P:       if.then.i:
// AIE2P-NEXT:    store i64 0, ptr [[CMP]], align 4, !tbaa [[TBAA2]]
// AIE2P-NEXT:    br label [[_ZL8BNEG_LTZDV64_ABRY_EXIT]]
// AIE2P:       _ZL8bneg_ltzDv64_abRy.exit:
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_bneg_ltz_v64int8Dv64_abRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    br i1 [[SGN:%.*]], label [[_ZL8BNEG_LTZDV64_ABRY_EXIT:%.*]], label [[IF_THEN_I:%.*]]
// AIE2PS:       if.then.i:
// AIE2PS-NEXT:    store i64 0, ptr [[CMP]], align 4, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    br label [[_ZL8BNEG_LTZDV64_ABRY_EXIT]]
// AIE2PS:       _ZL8bneg_ltzDv64_abRy.exit:
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_bneg_ltz_v64int8(v64int8 a, bool sgn, unsigned long long &cmp) {
  return bneg_ltz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_bneg_v64int8Dv64_a(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_bneg_v64int8Dv64_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_bneg_v64int8Dv64_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_bneg_v64int8(v64int8 a) { return bneg(a); }

// AIE2-LABEL: @_Z17test_bxor_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[B:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP1]], [[A:%.*]]
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A]])
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// AIE2-NEXT:    [[AND_I7_I:%.*]] = and <64 x i8> [[TMP3]], [[B]]
// AIE2-NEXT:    [[OR_I_I:%.*]] = or <64 x i8> [[AND_I7_I]], [[AND_I_I]]
// AIE2-NEXT:    ret <64 x i8> [[OR_I_I]]
//
// AIE2P-LABEL: @_Z17test_bxor_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[B:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP1]], [[A:%.*]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// AIE2P-NEXT:    [[AND_I7_I:%.*]] = and <64 x i8> [[TMP3]], [[B]]
// AIE2P-NEXT:    [[OR_I_I:%.*]] = or <64 x i8> [[AND_I7_I]], [[AND_I_I]]
// AIE2P-NEXT:    ret <64 x i8> [[OR_I_I]]
//
// AIE2PS-LABEL: @_Z17test_bxor_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[B:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP1]], [[A:%.*]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// AIE2PS-NEXT:    [[AND_I7_I:%.*]] = and <64 x i8> [[TMP3]], [[B]]
// AIE2PS-NEXT:    [[OR_I_I:%.*]] = or <64 x i8> [[AND_I7_I]], [[AND_I_I]]
// AIE2PS-NEXT:    ret <64 x i8> [[OR_I_I]]
//
v64int8 test_bxor_v64int8(v64int8 a, v64int8 b) { return bxor(a, b); }

// AIE2-LABEL: @_Z20test_abs_gtz_v64int8Dv64_aRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_abs_gtz_v64int8Dv64_aRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_abs_gtz_v64int8Dv64_aRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_abs_gtz_v64int8(v64int8 a, unsigned long long &cmp) {
  return abs_gtz(a, cmp);
}

// AIE2-LABEL: @_Z20test_abs_gtz_v64int8Dv64_abRy(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_abs_gtz_v64int8Dv64_abRy(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_abs_gtz_v64int8Dv64_abRy(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    store <2 x i32> [[TMP1]], ptr [[CMP:%.*]], align 8
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_abs_gtz_v64int8(v64int8 a, bool sgn, unsigned long long &cmp) {
  return abs_gtz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z16test_abs_v64int8Dv64_a(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_abs_v64int8Dv64_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_abs_v64int8Dv64_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_abs_v64int8(v64int8 a) { return abs(a); }

// AIE2-LABEL: @_Z16test_abs_v64int8Dv64_ab(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_abs_v64int8Dv64_ab(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_abs_v64int8Dv64_ab(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 0
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_abs_v64int8(v64int8 a, bool sgn) { return abs(a, sgn); }

// AIE2-LABEL: @_Z15test_lt_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_lt_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_lt_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_lt_v64int8(v64int8 a, v64int8 b) { return lt(a, b); }

// AIE2-LABEL: @_Z15test_ge_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_ge_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_ge_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_ge_v64int8(v64int8 a, v64int8 b) { return ge(a, b); }

// AIE2-LABEL: @_Z15test_le_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_le_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_le_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_le_v64int8(v64int8 a, v64int8 b) { return le(a, b); }

// AIE2-LABEL: @_Z15test_gt_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_gt_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_gt_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_gt_v64int8(v64int8 a, v64int8 b) { return gt(a, b); }

// AIE2-LABEL: @_Z15test_lt_v64int8Dv64_aS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_lt_v64int8Dv64_aS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_lt_v64int8Dv64_aS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_lt_v64int8(v64int8 a, v64int8 b, bool sgn) {
  return lt(a, b, sgn);
}

// AIE2-LABEL: @_Z15test_ge_v64int8Dv64_aS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_ge_v64int8Dv64_aS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_ge_v64int8Dv64_aS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_ge_v64int8(v64int8 a, v64int8 b, bool sgn) {
  return ge(a, b, sgn);
}

// AIE2-LABEL: @_Z15test_le_v64int8Dv64_aS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_le_v64int8Dv64_aS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_le_v64int8Dv64_aS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vge8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_le_v64int8(v64int8 a, v64int8 b, bool sgn) {
  return le(a, b, sgn);
}

// AIE2-LABEL: @_Z15test_gt_v64int8Dv64_aS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_gt_v64int8Dv64_aS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_gt_v64int8Dv64_aS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.vlt8(<64 x i8> [[B:%.*]], <64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_gt_v64int8(v64int8 a, v64int8 b, bool sgn) {
  return gt(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_ltz_v64int8Dv64_a(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
// AIE2P-LABEL: @_Z16test_ltz_v64int8Dv64_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2P-NEXT:    ret i64 [[TMP2]]
//
// AIE2PS-LABEL: @_Z16test_ltz_v64int8Dv64_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_ltz_v64int8(v64int8 a) { return ltz(a); }

// AIE2-LABEL: @_Z16test_ltz_v64int8Dv64_ab(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i64 [[TMP2]], i64 0
// AIE2-NEXT:    ret i64 [[SPEC_SELECT_I]]
//
// AIE2P-LABEL: @_Z16test_ltz_v64int8Dv64_ab(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2P-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i64 [[TMP2]], i64 0
// AIE2P-NEXT:    ret i64 [[SPEC_SELECT_I]]
//
// AIE2PS-LABEL: @_Z16test_ltz_v64int8Dv64_ab(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vbneg.ltz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2PS-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i64 [[TMP2]], i64 0
// AIE2PS-NEXT:    ret i64 [[SPEC_SELECT_I]]
//
unsigned long long test_ltz_v64int8(v64int8 a, bool sgn) { return ltz(a, sgn); }

// AIE2-LABEL: @_Z16test_gtz_v64int8Dv64_a(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
// AIE2P-LABEL: @_Z16test_gtz_v64int8Dv64_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2P-NEXT:    ret i64 [[TMP2]]
//
// AIE2PS-LABEL: @_Z16test_gtz_v64int8Dv64_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_gtz_v64int8(v64int8 a) { return gtz(a); }

// AIE2-LABEL: @_Z16test_gtz_v64int8Dv64_ab(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
// AIE2P-LABEL: @_Z16test_gtz_v64int8Dv64_ab(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2p.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2P-NEXT:    ret i64 [[TMP2]]
//
// AIE2PS-LABEL: @_Z16test_gtz_v64int8Dv64_ab(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vabs.gtz8(<64 x i8> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_gtz_v64int8(v64int8 a, bool sgn) { return gtz(a, sgn); }

// AIE2-LABEL: @_Z16test_eqz_v64int8Dv64_a(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.veqz8(<64 x i8> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_eqz_v64int8Dv64_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.veqz8(<64 x i8> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_eqz_v64int8Dv64_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_eqz_v64int8(v64int8 a) { return eqz(a); }

// AIE2-LABEL: @_Z15test_eq_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.veqz8(<64 x i8> [[SUB_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
// AIE2P-LABEL: @_Z15test_eq_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.veqz8(<64 x i8> [[SUB_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    ret i64 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_eq_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[SUB_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_eq_v64int8(v64int8 a, v64int8 b) { return eq(a, b); }

// AIE2-LABEL: @_Z15test_ne_v64int8Dv64_aS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.veqz8(<64 x i8> [[SUB_I_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    [[NOT_I:%.*]] = xor i64 [[TMP1]], -1
// AIE2-NEXT:    ret i64 [[NOT_I]]
//
// AIE2P-LABEL: @_Z15test_ne_v64int8Dv64_aS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2p.veqz8(<64 x i8> [[SUB_I_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2P-NEXT:    [[NOT_I:%.*]] = xor i64 [[TMP1]], -1
// AIE2P-NEXT:    ret i64 [[NOT_I]]
//
// AIE2PS-LABEL: @_Z15test_ne_v64int8Dv64_aS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I_I:%.*]] = sub <64 x i8> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[SUB_I_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2PS-NEXT:    [[XOR_I:%.*]] = xor i64 [[TMP1]], -1
// AIE2PS-NEXT:    ret i64 [[XOR_I]]
//
unsigned long long test_ne_v64int8(v64int8 a, v64int8 b) { return ne(a, b); }

// AIE2-LABEL: @_Z16test_sel_v64int8Dv64_aS_y(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2.vsel8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2P-LABEL: @_Z16test_sel_v64int8Dv64_aS_y(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.vsel8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_sel_v64int8Dv64_aS_y(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.vsel8(<64 x i8> [[A:%.*]], <64 x i8> [[B:%.*]], <2 x i32> [[TMP0]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_sel_v64int8(v64int8 a, v64int8 b, unsigned long long s) {
  return sel(a, b, s);
}

// CHECK-COMMON-LABEL: @_Z18test_add_v32uint16Dv32_tS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[ADD_I:%.*]] = add <32 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[ADD_I]]
//
v32uint16 test_add_v32uint16(v32uint16 a, v32uint16 b) { return add(a, b); }

// CHECK-COMMON-LABEL: @_Z18test_sub_v32uint16Dv32_tS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[SUB_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[SUB_I]]
//
v32uint16 test_sub_v32uint16(v32uint16 a, v32uint16 b) { return sub(a, b); }

// AIE2-LABEL: @_Z21test_addsub_v32uint16Dv32_tS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vaddsub16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[AS:%.*]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: @_Z21test_addsub_v32uint16Dv32_tS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.vaddsub16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[AS:%.*]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z21test_addsub_v32uint16Dv32_tS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.vaddsub16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[AS:%.*]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_addsub_v32uint16(v32uint16 a, v32uint16 b, unsigned int as) {
  return addsub(a, b, as);
}

// AIE2-LABEL: @_Z22test_neg_gtz_v32uint16Dv32_tRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_neg_gtz_v32uint16Dv32_tRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_neg_gtz_v32uint16Dv32_tRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_neg_gtz_v32uint16(v32uint16 a, unsigned int &cmp) {
  return neg_gtz(a, cmp);
}

// AIE2-LABEL: @_Z18test_neg_v32uint16Dv32_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_neg_v32uint16Dv32_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_neg_v32uint16Dv32_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_neg_v32uint16(v32uint16 a) { return neg(a); }

// AIE2-LABEL: @_Z21test_sub_lt_v32uint16Dv32_tS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_lt_v32uint16Dv32_tS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_lt_v32uint16Dv32_tS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_sub_lt_v32uint16(v32uint16 a, v32uint16 b, unsigned int &cmp) {
  return sub_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_sub_lt_v32uint16Dv32_tS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_lt_v32uint16Dv32_tS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_lt_v32uint16Dv32_tS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_sub_lt_v32uint16(v32uint16 a, v32uint16 b, bool sgn,
                                unsigned int &cmp) {
  return sub_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z21test_sub_ge_v32uint16Dv32_tS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_ge_v32uint16Dv32_tS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_ge_v32uint16Dv32_tS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_sub_ge_v32uint16(v32uint16 a, v32uint16 b, unsigned int &cmp) {
  return sub_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_sub_ge_v32uint16Dv32_tS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_ge_v32uint16Dv32_tS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_ge_v32uint16Dv32_tS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_sub_ge_v32uint16(v32uint16 a, v32uint16 b, bool sgn,
                                unsigned int &cmp) {
  return sub_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z25test_maxdiff_lt_v32uint16Dv32_tS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z25test_maxdiff_lt_v32uint16Dv32_tS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z25test_maxdiff_lt_v32uint16Dv32_tS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_maxdiff_lt_v32uint16(v32uint16 a, v32uint16 b,
                                    unsigned int &cmp) {
  return maxdiff_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z25test_maxdiff_lt_v32uint16Dv32_tS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z25test_maxdiff_lt_v32uint16Dv32_tS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z25test_maxdiff_lt_v32uint16Dv32_tS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_maxdiff_lt_v32uint16(v32uint16 a, v32uint16 b, bool sgn,
                                    unsigned int &cmp) {
  return maxdiff_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z22test_maxdiff_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z22test_maxdiff_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_maxdiff_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_maxdiff_v32uint16(v32uint16 a, v32uint16 b) {
  return maxdiff(a, b);
}

// AIE2-LABEL: @_Z22test_maxdiff_v32uint16Dv32_tS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z22test_maxdiff_v32uint16Dv32_tS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_maxdiff_v32uint16Dv32_tS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_maxdiff_v32uint16(v32uint16 a, v32uint16 b, bool sgn) {
  return maxdiff(a, b, sgn);
}

// AIE2-LABEL: @_Z21test_min_ge_v32uint16Dv32_tS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_min_ge_v32uint16Dv32_tS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_min_ge_v32uint16Dv32_tS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_min_ge_v32uint16(v32uint16 a, v32uint16 b, unsigned int &cmp) {
  return min_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_min_ge_v32uint16Dv32_tS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_min_ge_v32uint16Dv32_tS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_min_ge_v32uint16Dv32_tS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_min_ge_v32uint16(v32uint16 a, v32uint16 b, bool sgn,
                                unsigned int &cmp) {
  return min_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z18test_min_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_min_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_min_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_min_v32uint16(v32uint16 a, v32uint16 b) { return min(a, b); }

// AIE2-LABEL: @_Z18test_min_v32uint16Dv32_tS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_min_v32uint16Dv32_tS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_min_v32uint16Dv32_tS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_min_v32uint16(v32uint16 a, v32uint16 b, bool sgn) {
  return min(a, b, sgn);
}

// AIE2-LABEL: @_Z21test_max_lt_v32uint16Dv32_tS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_max_lt_v32uint16Dv32_tS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_max_lt_v32uint16Dv32_tS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_max_lt_v32uint16(v32uint16 a, v32uint16 b, unsigned int &cmp) {
  return max_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_max_lt_v32uint16Dv32_tS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_max_lt_v32uint16Dv32_tS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_max_lt_v32uint16Dv32_tS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_max_lt_v32uint16(v32uint16 a, v32uint16 b, bool sgn,
                                unsigned int &cmp) {
  return max_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z18test_max_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_max_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_max_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_max_v32uint16(v32uint16 a, v32uint16 b) { return max(a, b); }

// AIE2-LABEL: @_Z18test_max_v32uint16Dv32_tS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_max_v32uint16Dv32_tS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_max_v32uint16Dv32_tS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_max_v32uint16(v32uint16 a, v32uint16 b, bool sgn) {
  return max(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z19test_band_v32uint16Dv32_tS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <32 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[AND_I]]
//
v32uint16 test_band_v32uint16(v32uint16 a, v32uint16 b) { return band(a, b); }

// CHECK-COMMON-LABEL: @_Z18test_bor_v32uint16Dv32_tS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <32 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[OR_I]]
//
v32uint16 test_bor_v32uint16(v32uint16 a, v32uint16 b) { return bor(a, b); }

// AIE2-LABEL: @_Z23test_bneg_ltz_v32uint16Dv32_tRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    store i32 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6:![0-9]+]]
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z23test_bneg_ltz_v32uint16Dv32_tRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    store i32 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6:![0-9]+]]
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z23test_bneg_ltz_v32uint16Dv32_tRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    store i32 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6:![0-9]+]]
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_bneg_ltz_v32uint16(v32uint16 a, unsigned int &cmp) {
  return bneg_ltz(a, cmp);
}

// AIE2-LABEL: @_Z23test_bneg_ltz_v32uint16Dv32_tbRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z23test_bneg_ltz_v32uint16Dv32_tbRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z23test_bneg_ltz_v32uint16Dv32_tbRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_bneg_ltz_v32uint16(v32uint16 a, bool sgn, unsigned int &cmp) {
  return bneg_ltz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z19test_bneg_v32uint16Dv32_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z19test_bneg_v32uint16Dv32_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z19test_bneg_v32uint16Dv32_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_bneg_v32uint16(v32uint16 a) { return bneg(a); }

// AIE2-LABEL: @_Z19test_bxor_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[B:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    [[AND_I_I:%.*]] = and <32 x i16> [[TMP1]], [[A:%.*]]
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A]])
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP2]], 0
// AIE2-NEXT:    [[AND_I7_I:%.*]] = and <32 x i16> [[TMP3]], [[B]]
// AIE2-NEXT:    [[OR_I_I:%.*]] = or <32 x i16> [[AND_I7_I]], [[AND_I_I]]
// AIE2-NEXT:    ret <32 x i16> [[OR_I_I]]
//
// AIE2P-LABEL: @_Z19test_bxor_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[B:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[AND_I_I:%.*]] = and <32 x i16> [[TMP1]], [[A:%.*]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[AND_I7_I:%.*]] = and <32 x i16> [[TMP3]], [[B]]
// AIE2P-NEXT:    [[OR_I_I:%.*]] = or <32 x i16> [[AND_I7_I]], [[AND_I_I]]
// AIE2P-NEXT:    ret <32 x i16> [[OR_I_I]]
//
// AIE2PS-LABEL: @_Z19test_bxor_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[B:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and <32 x i16> [[TMP1]], [[A:%.*]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[AND_I7_I:%.*]] = and <32 x i16> [[TMP3]], [[B]]
// AIE2PS-NEXT:    [[OR_I_I:%.*]] = or <32 x i16> [[AND_I7_I]], [[AND_I_I]]
// AIE2PS-NEXT:    ret <32 x i16> [[OR_I_I]]
//
v32uint16 test_bxor_v32uint16(v32uint16 a, v32uint16 b) { return bxor(a, b); }

// AIE2-LABEL: @_Z22test_abs_gtz_v32uint16Dv32_tRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_abs_gtz_v32uint16Dv32_tRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_abs_gtz_v32uint16Dv32_tRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_abs_gtz_v32uint16(v32uint16 a, unsigned int &cmp) {
  return abs_gtz(a, cmp);
}

// AIE2-LABEL: @_Z22test_abs_gtz_v32uint16Dv32_tbRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_abs_gtz_v32uint16Dv32_tbRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_abs_gtz_v32uint16Dv32_tbRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_abs_gtz_v32uint16(v32uint16 a, bool sgn, unsigned int &cmp) {
  return abs_gtz(a, sgn, cmp);
}

// CHECK-COMMON-LABEL: @_Z18test_abs_v32uint16Dv32_t(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    ret <32 x i16> [[A:%.*]]
//
v32uint16 test_abs_v32uint16(v32uint16 a) { return abs(a); }

// AIE2-LABEL: @_Z18test_abs_v32uint16Dv32_tb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_abs_v32uint16Dv32_tb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_abs_v32uint16Dv32_tb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_abs_v32uint16(v32uint16 a, bool sgn) { return abs(a, sgn); }

// AIE2-LABEL: @_Z17test_lt_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_lt_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_lt_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v32uint16(v32uint16 a, v32uint16 b) { return lt(a, b); }

// AIE2-LABEL: @_Z17test_ge_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_ge_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_ge_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v32uint16(v32uint16 a, v32uint16 b) { return ge(a, b); }

// AIE2-LABEL: @_Z17test_le_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_le_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_le_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v32uint16(v32uint16 a, v32uint16 b) { return le(a, b); }

// AIE2-LABEL: @_Z17test_gt_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_gt_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_gt_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v32uint16(v32uint16 a, v32uint16 b) { return gt(a, b); }

// AIE2-LABEL: @_Z17test_lt_v32uint16Dv32_tS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_lt_v32uint16Dv32_tS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_lt_v32uint16Dv32_tS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v32uint16(v32uint16 a, v32uint16 b, bool sgn) {
  return lt(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_ge_v32uint16Dv32_tS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_ge_v32uint16Dv32_tS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_ge_v32uint16Dv32_tS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v32uint16(v32uint16 a, v32uint16 b, bool sgn) {
  return ge(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_le_v32uint16Dv32_tS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_le_v32uint16Dv32_tS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_le_v32uint16Dv32_tS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v32uint16(v32uint16 a, v32uint16 b, bool sgn) {
  return le(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_gt_v32uint16Dv32_tS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_gt_v32uint16Dv32_tS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_gt_v32uint16Dv32_tS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v32uint16(v32uint16 a, v32uint16 b, bool sgn) {
  return gt(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z18test_ltz_v32uint16Dv32_t(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    ret i32 0
//
unsigned int test_ltz_v32uint16(v32uint16 a) { return ltz(a); }

// AIE2-LABEL: @_Z18test_ltz_v32uint16Dv32_tb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2P-LABEL: @_Z18test_ltz_v32uint16Dv32_tb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2PS-LABEL: @_Z18test_ltz_v32uint16Dv32_tb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
unsigned int test_ltz_v32uint16(v32uint16 a, bool sgn) { return ltz(a, sgn); }

// AIE2-LABEL: @_Z18test_gtz_v32uint16Dv32_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_gtz_v32uint16Dv32_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_gtz_v32uint16Dv32_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v32uint16(v32uint16 a) { return gtz(a); }

// AIE2-LABEL: @_Z18test_gtz_v32uint16Dv32_tb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_gtz_v32uint16Dv32_tb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_gtz_v32uint16Dv32_tb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v32uint16(v32uint16 a, bool sgn) { return gtz(a, sgn); }

// AIE2-LABEL: @_Z18test_eqz_v32uint16Dv32_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z18test_eqz_v32uint16Dv32_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z18test_eqz_v32uint16Dv32_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eqz_v32uint16(v32uint16 a) { return eqz(a); }

// AIE2-LABEL: @_Z17test_eq_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz16(<32 x i16> [[SUB_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_eq_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz16(<32 x i16> [[SUB_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_eq_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz16(<32 x i16> [[SUB_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eq_v32uint16(v32uint16 a, v32uint16 b) { return eq(a, b); }

// AIE2-LABEL: @_Z17test_ne_v32uint16Dv32_tS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz16(<32 x i16> [[SUB_I_I_I]])
// AIE2-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2-NEXT:    ret i32 [[NOT_I]]
//
// AIE2P-LABEL: @_Z17test_ne_v32uint16Dv32_tS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz16(<32 x i16> [[SUB_I_I_I]])
// AIE2P-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2P-NEXT:    ret i32 [[NOT_I]]
//
// AIE2PS-LABEL: @_Z17test_ne_v32uint16Dv32_tS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz16(<32 x i16> [[SUB_I_I_I]])
// AIE2PS-NEXT:    [[XOR_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2PS-NEXT:    ret i32 [[XOR_I]]
//
unsigned int test_ne_v32uint16(v32uint16 a, v32uint16 b) { return ne(a, b); }

// AIE2-LABEL: @_Z18test_sel_v32uint16Dv32_tS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[S:%.*]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: @_Z18test_sel_v32uint16Dv32_tS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[S:%.*]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z18test_sel_v32uint16Dv32_tS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[S:%.*]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_sel_v32uint16(v32uint16 a, v32uint16 b, unsigned int s) {
  return sel(a, b, s);
}

// CHECK-COMMON-LABEL: @_Z17test_add_v32int16Dv32_sS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[ADD_I:%.*]] = add <32 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[ADD_I]]
//
v32int16 test_add_v32int16(v32int16 a, v32int16 b) { return add(a, b); }

// CHECK-COMMON-LABEL: @_Z17test_sub_v32int16Dv32_sS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[SUB_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[SUB_I]]
//
v32int16 test_sub_v32int16(v32int16 a, v32int16 b) { return sub(a, b); }

// AIE2-LABEL: @_Z20test_addsub_v32int16Dv32_sS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vaddsub16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[AS:%.*]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: @_Z20test_addsub_v32int16Dv32_sS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.vaddsub16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[AS:%.*]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_addsub_v32int16Dv32_sS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.vaddsub16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[AS:%.*]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_addsub_v32int16(v32int16 a, v32int16 b, unsigned int as) {
  return addsub(a, b, as);
}

// AIE2-LABEL: @_Z21test_neg_gtz_v32int16Dv32_sRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_neg_gtz_v32int16Dv32_sRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_neg_gtz_v32int16Dv32_sRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_neg_gtz_v32int16(v32int16 a, unsigned int &cmp) {
  return neg_gtz(a, cmp);
}

// AIE2-LABEL: @_Z17test_neg_v32int16Dv32_s(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_neg_v32int16Dv32_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_neg_v32int16Dv32_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vneg.gtz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_neg_v32int16(v32int16 a) { return neg(a); }

// AIE2-LABEL: @_Z20test_sub_lt_v32int16Dv32_sS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_lt_v32int16Dv32_sS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_lt_v32int16Dv32_sS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_sub_lt_v32int16(v32int16 a, v32int16 b, unsigned int &cmp) {
  return sub_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_sub_lt_v32int16Dv32_sS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_lt_v32int16Dv32_sS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_lt_v32int16Dv32_sS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_sub_lt_v32int16(v32int16 a, v32int16 b, bool sgn,
                              unsigned int &cmp) {
  return sub_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z20test_sub_ge_v32int16Dv32_sS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_ge_v32int16Dv32_sS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_ge_v32int16Dv32_sS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_sub_ge_v32int16(v32int16 a, v32int16 b, unsigned int &cmp) {
  return sub_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_sub_ge_v32int16Dv32_sS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_ge_v32int16Dv32_sS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_ge_v32int16Dv32_sS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vsub.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_sub_ge_v32int16(v32int16 a, v32int16 b, bool sgn,
                              unsigned int &cmp) {
  return sub_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z24test_maxdiff_lt_v32int16Dv32_sS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z24test_maxdiff_lt_v32int16Dv32_sS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z24test_maxdiff_lt_v32int16Dv32_sS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_maxdiff_lt_v32int16(v32int16 a, v32int16 b, unsigned int &cmp) {
  return maxdiff_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z24test_maxdiff_lt_v32int16Dv32_sS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z24test_maxdiff_lt_v32int16Dv32_sS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z24test_maxdiff_lt_v32int16Dv32_sS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_maxdiff_lt_v32int16(v32int16 a, v32int16 b, bool sgn,
                                  unsigned int &cmp) {
  return maxdiff_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z21test_maxdiff_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z21test_maxdiff_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_maxdiff_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_maxdiff_v32int16(v32int16 a, v32int16 b) { return maxdiff(a, b); }

// AIE2-LABEL: @_Z21test_maxdiff_v32int16Dv32_sS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z21test_maxdiff_v32int16Dv32_sS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_maxdiff_v32int16Dv32_sS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmaxdiff.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_maxdiff_v32int16(v32int16 a, v32int16 b, bool sgn) {
  return maxdiff(a, b, sgn);
}

// AIE2-LABEL: @_Z20test_min_ge_v32int16Dv32_sS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_min_ge_v32int16Dv32_sS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_min_ge_v32int16Dv32_sS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_min_ge_v32int16(v32int16 a, v32int16 b, unsigned int &cmp) {
  return min_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_min_ge_v32int16Dv32_sS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_min_ge_v32int16Dv32_sS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_min_ge_v32int16Dv32_sS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_min_ge_v32int16(v32int16 a, v32int16 b, bool sgn,
                              unsigned int &cmp) {
  return min_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_min_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_min_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_min_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_min_v32int16(v32int16 a, v32int16 b) { return min(a, b); }

// AIE2-LABEL: @_Z17test_min_v32int16Dv32_sS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_min_v32int16Dv32_sS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_min_v32int16Dv32_sS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmin.ge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_min_v32int16(v32int16 a, v32int16 b, bool sgn) {
  return min(a, b, sgn);
}

// AIE2-LABEL: @_Z20test_max_lt_v32int16Dv32_sS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_max_lt_v32int16Dv32_sS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_max_lt_v32int16Dv32_sS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_max_lt_v32int16(v32int16 a, v32int16 b, unsigned int &cmp) {
  return max_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_max_lt_v32int16Dv32_sS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_max_lt_v32int16Dv32_sS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_max_lt_v32int16Dv32_sS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_max_lt_v32int16(v32int16 a, v32int16 b, bool sgn,
                              unsigned int &cmp) {
  return max_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_max_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_max_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_max_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_max_v32int16(v32int16 a, v32int16 b) { return max(a, b); }

// AIE2-LABEL: @_Z17test_max_v32int16Dv32_sS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_max_v32int16Dv32_sS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_max_v32int16Dv32_sS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vmax.lt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_max_v32int16(v32int16 a, v32int16 b, bool sgn) {
  return max(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z18test_band_v32int16Dv32_sS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <32 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[AND_I]]
//
v32int16 test_band_v32int16(v32int16 a, v32int16 b) { return band(a, b); }

// CHECK-COMMON-LABEL: @_Z17test_bor_v32int16Dv32_sS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <32 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <32 x i16> [[OR_I]]
//
v32int16 test_bor_v32int16(v32int16 a, v32int16 b) { return bor(a, b); }

// AIE2-LABEL: @_Z22test_bneg_ltz_v32int16Dv32_sRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_bneg_ltz_v32int16Dv32_sRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_bneg_ltz_v32int16Dv32_sRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_bneg_ltz_v32int16(v32int16 a, unsigned int &cmp) {
  return bneg_ltz(a, cmp);
}

// AIE2-LABEL: @_Z22test_bneg_ltz_v32int16Dv32_sbRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_bneg_ltz_v32int16Dv32_sbRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_bneg_ltz_v32int16Dv32_sbRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_bneg_ltz_v32int16(v32int16 a, bool sgn, unsigned int &cmp) {
  return bneg_ltz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z18test_bneg_v32int16Dv32_s(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_bneg_v32int16Dv32_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_bneg_v32int16Dv32_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_bneg_v32int16(v32int16 a) { return bneg(a); }

// AIE2-LABEL: @_Z18test_bxor_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[B:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    [[AND_I_I:%.*]] = and <32 x i16> [[TMP1]], [[A:%.*]]
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A]])
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP2]], 0
// AIE2-NEXT:    [[AND_I7_I:%.*]] = and <32 x i16> [[TMP3]], [[B]]
// AIE2-NEXT:    [[OR_I_I:%.*]] = or <32 x i16> [[AND_I7_I]], [[AND_I_I]]
// AIE2-NEXT:    ret <32 x i16> [[OR_I_I]]
//
// AIE2P-LABEL: @_Z18test_bxor_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[B:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[AND_I_I:%.*]] = and <32 x i16> [[TMP1]], [[A:%.*]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[AND_I7_I:%.*]] = and <32 x i16> [[TMP3]], [[B]]
// AIE2P-NEXT:    [[OR_I_I:%.*]] = or <32 x i16> [[AND_I7_I]], [[AND_I_I]]
// AIE2P-NEXT:    ret <32 x i16> [[OR_I_I]]
//
// AIE2PS-LABEL: @_Z18test_bxor_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[B:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and <32 x i16> [[TMP1]], [[A:%.*]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[AND_I7_I:%.*]] = and <32 x i16> [[TMP3]], [[B]]
// AIE2PS-NEXT:    [[OR_I_I:%.*]] = or <32 x i16> [[AND_I7_I]], [[AND_I_I]]
// AIE2PS-NEXT:    ret <32 x i16> [[OR_I_I]]
//
v32int16 test_bxor_v32int16(v32int16 a, v32int16 b) { return bxor(a, b); }

// AIE2-LABEL: @_Z21test_abs_gtz_v32int16Dv32_sRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_abs_gtz_v32int16Dv32_sRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_abs_gtz_v32int16Dv32_sRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_abs_gtz_v32int16(v32int16 a, unsigned int &cmp) {
  return abs_gtz(a, cmp);
}

// AIE2-LABEL: @_Z21test_abs_gtz_v32int16Dv32_sbRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_abs_gtz_v32int16Dv32_sbRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_abs_gtz_v32int16Dv32_sbRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_abs_gtz_v32int16(v32int16 a, bool sgn, unsigned int &cmp) {
  return abs_gtz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_abs_v32int16Dv32_s(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_abs_v32int16Dv32_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_abs_v32int16Dv32_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_abs_v32int16(v32int16 a) { return abs(a); }

// AIE2-LABEL: @_Z17test_abs_v32int16Dv32_sb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_abs_v32int16Dv32_sb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_abs_v32int16Dv32_sb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_abs_v32int16(v32int16 a, bool sgn) { return abs(a, sgn); }

// AIE2-LABEL: @_Z16test_lt_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_lt_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_lt_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v32int16(v32int16 a, v32int16 b) { return lt(a, b); }

// AIE2-LABEL: @_Z16test_ge_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_ge_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_ge_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v32int16(v32int16 a, v32int16 b) { return ge(a, b); }

// AIE2-LABEL: @_Z16test_le_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_le_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_le_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v32int16(v32int16 a, v32int16 b) { return le(a, b); }

// AIE2-LABEL: @_Z16test_gt_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_gt_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_gt_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v32int16(v32int16 a, v32int16 b) { return gt(a, b); }

// AIE2-LABEL: @_Z16test_lt_v32int16Dv32_sS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_lt_v32int16Dv32_sS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_lt_v32int16Dv32_sS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v32int16(v32int16 a, v32int16 b, bool sgn) {
  return lt(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_ge_v32int16Dv32_sS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_ge_v32int16Dv32_sS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_ge_v32int16Dv32_sS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v32int16(v32int16 a, v32int16 b, bool sgn) {
  return ge(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_le_v32int16Dv32_sS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_le_v32int16Dv32_sS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_le_v32int16Dv32_sS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v32int16(v32int16 a, v32int16 b, bool sgn) {
  return le(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_gt_v32int16Dv32_sS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_gt_v32int16Dv32_sS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_gt_v32int16Dv32_sS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt16(<32 x i16> [[B:%.*]], <32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v32int16(v32int16 a, v32int16 b, bool sgn) {
  return gt(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_ltz_v32int16Dv32_s(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_ltz_v32int16Dv32_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_ltz_v32int16Dv32_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_ltz_v32int16(v32int16 a) { return ltz(a); }

// AIE2-LABEL: @_Z17test_ltz_v32int16Dv32_sb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2P-LABEL: @_Z17test_ltz_v32int16Dv32_sb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2PS-LABEL: @_Z17test_ltz_v32int16Dv32_sb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vbneg.ltz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
unsigned int test_ltz_v32int16(v32int16 a, bool sgn) { return ltz(a, sgn); }

// AIE2-LABEL: @_Z17test_gtz_v32int16Dv32_s(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_gtz_v32int16Dv32_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_gtz_v32int16Dv32_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v32int16(v32int16 a) { return gtz(a); }

// AIE2-LABEL: @_Z17test_gtz_v32int16Dv32_sb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_gtz_v32int16Dv32_sb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2p.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_gtz_v32int16Dv32_sb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <32 x i16>, i32 } @llvm.aie2ps.vabs.gtz16(<32 x i16> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x i16>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v32int16(v32int16 a, bool sgn) { return gtz(a, sgn); }

// AIE2-LABEL: @_Z17test_eqz_v32int16Dv32_s(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz16(<32 x i16> [[A:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_eqz_v32int16Dv32_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz16(<32 x i16> [[A:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_eqz_v32int16Dv32_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz16(<32 x i16> [[A:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eqz_v32int16(v32int16 a) { return eqz(a); }

// AIE2-LABEL: @_Z16test_eq_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz16(<32 x i16> [[SUB_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_eq_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz16(<32 x i16> [[SUB_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_eq_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz16(<32 x i16> [[SUB_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eq_v32int16(v32int16 a, v32int16 b) { return eq(a, b); }

// AIE2-LABEL: @_Z16test_ne_v32int16Dv32_sS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz16(<32 x i16> [[SUB_I_I_I]])
// AIE2-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2-NEXT:    ret i32 [[NOT_I]]
//
// AIE2P-LABEL: @_Z16test_ne_v32int16Dv32_sS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz16(<32 x i16> [[SUB_I_I_I]])
// AIE2P-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2P-NEXT:    ret i32 [[NOT_I]]
//
// AIE2PS-LABEL: @_Z16test_ne_v32int16Dv32_sS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I_I:%.*]] = sub <32 x i16> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz16(<32 x i16> [[SUB_I_I_I]])
// AIE2PS-NEXT:    [[XOR_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2PS-NEXT:    ret i32 [[XOR_I]]
//
unsigned int test_ne_v32int16(v32int16 a, v32int16 b) { return ne(a, b); }

// AIE2-LABEL: @_Z17test_sel_v32int16Dv32_sS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[S:%.*]])
// AIE2-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_sel_v32int16Dv32_sS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[S:%.*]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_sel_v32int16Dv32_sS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[S:%.*]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_sel_v32int16(v32int16 a, v32int16 b, unsigned int s) {
  return sel(a, b, s);
}

// CHECK-COMMON-LABEL: @_Z18test_add_v16uint32Dv16_jS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[ADD_I:%.*]] = add <16 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[ADD_I]]
//
v16uint32 test_add_v16uint32(v16uint32 a, v16uint32 b) { return add(a, b); }

// CHECK-COMMON-LABEL: @_Z18test_sub_v16uint32Dv16_jS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[SUB_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[SUB_I]]
//
v16uint32 test_sub_v16uint32(v16uint32 a, v16uint32 b) { return sub(a, b); }

// AIE2-LABEL: @_Z21test_addsub_v16uint32Dv16_jS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vaddsub32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[AS:%.*]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z21test_addsub_v16uint32Dv16_jS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vaddsub32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[AS:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z21test_addsub_v16uint32Dv16_jS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vaddsub32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[AS:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_addsub_v16uint32(v16uint32 a, v16uint32 b, unsigned int as) {
  return addsub(a, b, as);
}

// AIE2-LABEL: @_Z22test_neg_gtz_v16uint32Dv16_jRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_neg_gtz_v16uint32Dv16_jRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_neg_gtz_v16uint32Dv16_jRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_neg_gtz_v16uint32(v16uint32 a, unsigned int &cmp) {
  return neg_gtz(a, cmp);
}

// AIE2-LABEL: @_Z18test_neg_v16uint32Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_neg_v16uint32Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_neg_v16uint32Dv16_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_neg_v16uint32(v16uint32 a) { return neg(a); }

// AIE2-LABEL: @_Z21test_sub_lt_v16uint32Dv16_jS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_lt_v16uint32Dv16_jS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_lt_v16uint32Dv16_jS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_sub_lt_v16uint32(v16uint32 a, v16uint32 b, unsigned int &cmp) {
  return sub_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_sub_lt_v16uint32Dv16_jS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_lt_v16uint32Dv16_jS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_lt_v16uint32Dv16_jS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_sub_lt_v16uint32(v16uint32 a, v16uint32 b, bool sgn,
                                unsigned int &cmp) {
  return sub_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z21test_sub_ge_v16uint32Dv16_jS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_ge_v16uint32Dv16_jS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_ge_v16uint32Dv16_jS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_sub_ge_v16uint32(v16uint32 a, v16uint32 b, unsigned int &cmp) {
  return sub_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_sub_ge_v16uint32Dv16_jS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_sub_ge_v16uint32Dv16_jS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_sub_ge_v16uint32Dv16_jS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_sub_ge_v16uint32(v16uint32 a, v16uint32 b, bool sgn,
                                unsigned int &cmp) {
  return sub_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z25test_maxdiff_lt_v16uint32Dv16_jS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z25test_maxdiff_lt_v16uint32Dv16_jS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z25test_maxdiff_lt_v16uint32Dv16_jS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_maxdiff_lt_v16uint32(v16uint32 a, v16uint32 b,
                                    unsigned int &cmp) {
  return maxdiff_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z25test_maxdiff_lt_v16uint32Dv16_jS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z25test_maxdiff_lt_v16uint32Dv16_jS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z25test_maxdiff_lt_v16uint32Dv16_jS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_maxdiff_lt_v16uint32(v16uint32 a, v16uint32 b, bool sgn,
                                    unsigned int &cmp) {
  return maxdiff_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z22test_maxdiff_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z22test_maxdiff_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_maxdiff_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_maxdiff_v16uint32(v16uint32 a, v16uint32 b) {
  return maxdiff(a, b);
}

// AIE2-LABEL: @_Z22test_maxdiff_v16uint32Dv16_jS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z22test_maxdiff_v16uint32Dv16_jS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_maxdiff_v16uint32Dv16_jS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_maxdiff_v16uint32(v16uint32 a, v16uint32 b, bool sgn) {
  return maxdiff(a, b, sgn);
}

// AIE2-LABEL: @_Z21test_min_ge_v16uint32Dv16_jS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_min_ge_v16uint32Dv16_jS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_min_ge_v16uint32Dv16_jS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_min_ge_v16uint32(v16uint32 a, v16uint32 b, unsigned int &cmp) {
  return min_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_min_ge_v16uint32Dv16_jS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_min_ge_v16uint32Dv16_jS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_min_ge_v16uint32Dv16_jS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_min_ge_v16uint32(v16uint32 a, v16uint32 b, bool sgn,
                                unsigned int &cmp) {
  return min_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z18test_min_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_min_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_min_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_min_v16uint32(v16uint32 a, v16uint32 b) { return min(a, b); }

// AIE2-LABEL: @_Z18test_min_v16uint32Dv16_jS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_min_v16uint32Dv16_jS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_min_v16uint32Dv16_jS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_min_v16uint32(v16uint32 a, v16uint32 b, bool sgn) {
  return min(a, b, sgn);
}

// AIE2-LABEL: @_Z21test_max_lt_v16uint32Dv16_jS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_max_lt_v16uint32Dv16_jS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_max_lt_v16uint32Dv16_jS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_max_lt_v16uint32(v16uint32 a, v16uint32 b, unsigned int &cmp) {
  return max_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z21test_max_lt_v16uint32Dv16_jS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_max_lt_v16uint32Dv16_jS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_max_lt_v16uint32Dv16_jS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_max_lt_v16uint32(v16uint32 a, v16uint32 b, bool sgn,
                                unsigned int &cmp) {
  return max_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z18test_max_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_max_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_max_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_max_v16uint32(v16uint32 a, v16uint32 b) { return max(a, b); }

// AIE2-LABEL: @_Z18test_max_v16uint32Dv16_jS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_max_v16uint32Dv16_jS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_max_v16uint32Dv16_jS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_max_v16uint32(v16uint32 a, v16uint32 b, bool sgn) {
  return max(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z19test_band_v16uint32Dv16_jS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <16 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[AND_I]]
//
v16uint32 test_band_v16uint32(v16uint32 a, v16uint32 b) { return band(a, b); }

// CHECK-COMMON-LABEL: @_Z18test_bor_v16uint32Dv16_jS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <16 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[OR_I]]
//
v16uint32 test_bor_v16uint32(v16uint32 a, v16uint32 b) { return bor(a, b); }

// AIE2-LABEL: @_Z23test_bneg_ltz_v16uint32Dv16_jRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    store i32 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z23test_bneg_ltz_v16uint32Dv16_jRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    store i32 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z23test_bneg_ltz_v16uint32Dv16_jRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    store i32 0, ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_bneg_ltz_v16uint32(v16uint32 a, unsigned int &cmp) {
  return bneg_ltz(a, cmp);
}

// AIE2-LABEL: @_Z23test_bneg_ltz_v16uint32Dv16_jbRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z23test_bneg_ltz_v16uint32Dv16_jbRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z23test_bneg_ltz_v16uint32Dv16_jbRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_bneg_ltz_v16uint32(v16uint32 a, bool sgn, unsigned int &cmp) {
  return bneg_ltz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z19test_bneg_v16uint32Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z19test_bneg_v16uint32Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z19test_bneg_v16uint32Dv16_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_bneg_v16uint32(v16uint32 a) { return bneg(a); }

// AIE2-LABEL: @_Z19test_bxor_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[B:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    [[AND_I_I:%.*]] = and <16 x i32> [[TMP1]], [[A:%.*]]
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A]])
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2-NEXT:    [[AND_I7_I:%.*]] = and <16 x i32> [[TMP3]], [[B]]
// AIE2-NEXT:    [[OR_I_I:%.*]] = or <16 x i32> [[AND_I7_I]], [[AND_I_I]]
// AIE2-NEXT:    ret <16 x i32> [[OR_I_I]]
//
// AIE2P-LABEL: @_Z19test_bxor_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[B:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[AND_I_I:%.*]] = and <16 x i32> [[TMP1]], [[A:%.*]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[AND_I7_I:%.*]] = and <16 x i32> [[TMP3]], [[B]]
// AIE2P-NEXT:    [[OR_I_I:%.*]] = or <16 x i32> [[AND_I7_I]], [[AND_I_I]]
// AIE2P-NEXT:    ret <16 x i32> [[OR_I_I]]
//
// AIE2PS-LABEL: @_Z19test_bxor_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[B:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and <16 x i32> [[TMP1]], [[A:%.*]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[AND_I7_I:%.*]] = and <16 x i32> [[TMP3]], [[B]]
// AIE2PS-NEXT:    [[OR_I_I:%.*]] = or <16 x i32> [[AND_I7_I]], [[AND_I_I]]
// AIE2PS-NEXT:    ret <16 x i32> [[OR_I_I]]
//
v16uint32 test_bxor_v16uint32(v16uint32 a, v16uint32 b) { return bxor(a, b); }

// AIE2-LABEL: @_Z22test_abs_gtz_v16uint32Dv16_jRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_abs_gtz_v16uint32Dv16_jRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_abs_gtz_v16uint32Dv16_jRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_abs_gtz_v16uint32(v16uint32 a, unsigned int &cmp) {
  return abs_gtz(a, cmp);
}

// AIE2-LABEL: @_Z22test_abs_gtz_v16uint32Dv16_jbRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_abs_gtz_v16uint32Dv16_jbRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_abs_gtz_v16uint32Dv16_jbRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_abs_gtz_v16uint32(v16uint32 a, bool sgn, unsigned int &cmp) {
  return abs_gtz(a, sgn, cmp);
}

// CHECK-COMMON-LABEL: @_Z18test_abs_v16uint32Dv16_j(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    ret <16 x i32> [[A:%.*]]
//
v16uint32 test_abs_v16uint32(v16uint32 a) { return abs(a); }

// AIE2-LABEL: @_Z18test_abs_v16uint32Dv16_jb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_abs_v16uint32Dv16_jb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_abs_v16uint32Dv16_jb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_abs_v16uint32(v16uint32 a, bool sgn) { return abs(a, sgn); }

// AIE2-LABEL: @_Z17test_lt_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_lt_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_lt_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v16uint32(v16uint32 a, v16uint32 b) { return lt(a, b); }

// AIE2-LABEL: @_Z17test_ge_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_ge_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_ge_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v16uint32(v16uint32 a, v16uint32 b) { return ge(a, b); }

// AIE2-LABEL: @_Z17test_le_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_le_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_le_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v16uint32(v16uint32 a, v16uint32 b) { return le(a, b); }

// AIE2-LABEL: @_Z17test_gt_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 0)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_gt_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 0)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_gt_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v16uint32(v16uint32 a, v16uint32 b) { return gt(a, b); }

// AIE2-LABEL: @_Z17test_lt_v16uint32Dv16_jS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_lt_v16uint32Dv16_jS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_lt_v16uint32Dv16_jS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v16uint32(v16uint32 a, v16uint32 b, bool sgn) {
  return lt(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_ge_v16uint32Dv16_jS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_ge_v16uint32Dv16_jS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_ge_v16uint32Dv16_jS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v16uint32(v16uint32 a, v16uint32 b, bool sgn) {
  return ge(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_le_v16uint32Dv16_jS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_le_v16uint32Dv16_jS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_le_v16uint32Dv16_jS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v16uint32(v16uint32 a, v16uint32 b, bool sgn) {
  return le(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_gt_v16uint32Dv16_jS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_gt_v16uint32Dv16_jS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_gt_v16uint32Dv16_jS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v16uint32(v16uint32 a, v16uint32 b, bool sgn) {
  return gt(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z18test_ltz_v16uint32Dv16_j(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    ret i32 0
//
unsigned int test_ltz_v16uint32(v16uint32 a) { return ltz(a); }

// AIE2-LABEL: @_Z18test_ltz_v16uint32Dv16_jb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2P-LABEL: @_Z18test_ltz_v16uint32Dv16_jb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2PS-LABEL: @_Z18test_ltz_v16uint32Dv16_jb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
unsigned int test_ltz_v16uint32(v16uint32 a, bool sgn) { return ltz(a, sgn); }

// AIE2-LABEL: @_Z18test_gtz_v16uint32Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_gtz_v16uint32Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_gtz_v16uint32Dv16_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v16uint32(v16uint32 a) { return gtz(a); }

// AIE2-LABEL: @_Z18test_gtz_v16uint32Dv16_jb(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_gtz_v16uint32Dv16_jb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_gtz_v16uint32Dv16_jb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v16uint32(v16uint32 a, bool sgn) { return gtz(a, sgn); }

// AIE2-LABEL: @_Z18test_eqz_v16uint32Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z18test_eqz_v16uint32Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z18test_eqz_v16uint32Dv16_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eqz_v16uint32(v16uint32 a) { return eqz(a); }

// AIE2-LABEL: @_Z17test_eq_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz32(<16 x i32> [[SUB_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_eq_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz32(<16 x i32> [[SUB_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_eq_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz32(<16 x i32> [[SUB_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eq_v16uint32(v16uint32 a, v16uint32 b) { return eq(a, b); }

// AIE2-LABEL: @_Z17test_ne_v16uint32Dv16_jS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz32(<16 x i32> [[SUB_I_I_I]])
// AIE2-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2-NEXT:    ret i32 [[NOT_I]]
//
// AIE2P-LABEL: @_Z17test_ne_v16uint32Dv16_jS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz32(<16 x i32> [[SUB_I_I_I]])
// AIE2P-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2P-NEXT:    ret i32 [[NOT_I]]
//
// AIE2PS-LABEL: @_Z17test_ne_v16uint32Dv16_jS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz32(<16 x i32> [[SUB_I_I_I]])
// AIE2PS-NEXT:    [[XOR_I:%.*]] = xor i32 [[TMP0]], 65535
// AIE2PS-NEXT:    ret i32 [[XOR_I]]
//
unsigned int test_ne_v16uint32(v16uint32 a, v16uint32 b) { return ne(a, b); }

// AIE2-LABEL: @_Z18test_sel_v16uint32Dv16_jS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[S:%.*]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z18test_sel_v16uint32Dv16_jS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[S:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z18test_sel_v16uint32Dv16_jS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[S:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_sel_v16uint32(v16uint32 a, v16uint32 b, unsigned int s) {
  return sel(a, b, s);
}

// CHECK-COMMON-LABEL: @_Z17test_add_v16int32Dv16_iS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[ADD_I:%.*]] = add <16 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[ADD_I]]
//
v16int32 test_add_v16int32(v16int32 a, v16int32 b) { return add(a, b); }

// CHECK-COMMON-LABEL: @_Z17test_sub_v16int32Dv16_iS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[SUB_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[SUB_I]]
//
v16int32 test_sub_v16int32(v16int32 a, v16int32 b) { return sub(a, b); }

// AIE2-LABEL: @_Z20test_addsub_v16int32Dv16_iS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vaddsub32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[AS:%.*]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z20test_addsub_v16int32Dv16_iS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vaddsub32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[AS:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_addsub_v16int32Dv16_iS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vaddsub32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[AS:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_addsub_v16int32(v16int32 a, v16int32 b, unsigned int as) {
  return addsub(a, b, as);
}

// AIE2-LABEL: @_Z21test_neg_gtz_v16int32Dv16_iRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_neg_gtz_v16int32Dv16_iRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_neg_gtz_v16int32Dv16_iRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_neg_gtz_v16int32(v16int32 a, unsigned int &cmp) {
  return neg_gtz(a, cmp);
}

// AIE2-LABEL: @_Z17test_neg_v16int32Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_neg_v16int32Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_neg_v16int32Dv16_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vneg.gtz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_neg_v16int32(v16int32 a) { return neg(a); }

// AIE2-LABEL: @_Z20test_sub_lt_v16int32Dv16_iS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_lt_v16int32Dv16_iS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_lt_v16int32Dv16_iS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_sub_lt_v16int32(v16int32 a, v16int32 b, unsigned int &cmp) {
  return sub_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_sub_lt_v16int32Dv16_iS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_lt_v16int32Dv16_iS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_lt_v16int32Dv16_iS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_sub_lt_v16int32(v16int32 a, v16int32 b, bool sgn,
                              unsigned int &cmp) {
  return sub_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z20test_sub_ge_v16int32Dv16_iS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_ge_v16int32Dv16_iS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_ge_v16int32Dv16_iS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_sub_ge_v16int32(v16int32 a, v16int32 b, unsigned int &cmp) {
  return sub_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_sub_ge_v16int32Dv16_iS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_sub_ge_v16int32Dv16_iS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_sub_ge_v16int32Dv16_iS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vsub.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_sub_ge_v16int32(v16int32 a, v16int32 b, bool sgn,
                              unsigned int &cmp) {
  return sub_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z24test_maxdiff_lt_v16int32Dv16_iS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z24test_maxdiff_lt_v16int32Dv16_iS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z24test_maxdiff_lt_v16int32Dv16_iS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_maxdiff_lt_v16int32(v16int32 a, v16int32 b, unsigned int &cmp) {
  return maxdiff_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z24test_maxdiff_lt_v16int32Dv16_iS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z24test_maxdiff_lt_v16int32Dv16_iS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z24test_maxdiff_lt_v16int32Dv16_iS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_maxdiff_lt_v16int32(v16int32 a, v16int32 b, bool sgn,
                                  unsigned int &cmp) {
  return maxdiff_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z21test_maxdiff_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z21test_maxdiff_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_maxdiff_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_maxdiff_v16int32(v16int32 a, v16int32 b) { return maxdiff(a, b); }

// AIE2-LABEL: @_Z21test_maxdiff_v16int32Dv16_iS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z21test_maxdiff_v16int32Dv16_iS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_maxdiff_v16int32Dv16_iS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmaxdiff.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_maxdiff_v16int32(v16int32 a, v16int32 b, bool sgn) {
  return maxdiff(a, b, sgn);
}

// AIE2-LABEL: @_Z20test_min_ge_v16int32Dv16_iS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_min_ge_v16int32Dv16_iS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_min_ge_v16int32Dv16_iS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_min_ge_v16int32(v16int32 a, v16int32 b, unsigned int &cmp) {
  return min_ge(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_min_ge_v16int32Dv16_iS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_min_ge_v16int32Dv16_iS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_min_ge_v16int32Dv16_iS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_min_ge_v16int32(v16int32 a, v16int32 b, bool sgn,
                              unsigned int &cmp) {
  return min_ge(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_min_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_min_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_min_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_min_v16int32(v16int32 a, v16int32 b) { return min(a, b); }

// AIE2-LABEL: @_Z17test_min_v16int32Dv16_iS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_min_v16int32Dv16_iS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_min_v16int32Dv16_iS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmin.ge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_min_v16int32(v16int32 a, v16int32 b, bool sgn) {
  return min(a, b, sgn);
}

// AIE2-LABEL: @_Z20test_max_lt_v16int32Dv16_iS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_max_lt_v16int32Dv16_iS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_max_lt_v16int32Dv16_iS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_max_lt_v16int32(v16int32 a, v16int32 b, unsigned int &cmp) {
  return max_lt(a, b, cmp);
}

// AIE2-LABEL: @_Z20test_max_lt_v16int32Dv16_iS_bRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_max_lt_v16int32Dv16_iS_bRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_max_lt_v16int32Dv16_iS_bRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_max_lt_v16int32(v16int32 a, v16int32 b, bool sgn,
                              unsigned int &cmp) {
  return max_lt(a, b, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_max_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_max_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_max_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_max_v16int32(v16int32 a, v16int32 b) { return max(a, b); }

// AIE2-LABEL: @_Z17test_max_v16int32Dv16_iS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_max_v16int32Dv16_iS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_max_v16int32Dv16_iS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vmax.lt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_max_v16int32(v16int32 a, v16int32 b, bool sgn) {
  return max(a, b, sgn);
}

// CHECK-COMMON-LABEL: @_Z18test_band_v16int32Dv16_iS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <16 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[AND_I]]
//
v16int32 test_band_v16int32(v16int32 a, v16int32 b) { return band(a, b); }

// CHECK-COMMON-LABEL: @_Z17test_bor_v16int32Dv16_iS_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <16 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-COMMON-NEXT:    ret <16 x i32> [[OR_I]]
//
v16int32 test_bor_v16int32(v16int32 a, v16int32 b) { return bor(a, b); }

// AIE2-LABEL: @_Z22test_bneg_ltz_v16int32Dv16_iRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_bneg_ltz_v16int32Dv16_iRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_bneg_ltz_v16int32Dv16_iRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_bneg_ltz_v16int32(v16int32 a, unsigned int &cmp) {
  return bneg_ltz(a, cmp);
}

// AIE2-LABEL: @_Z22test_bneg_ltz_v16int32Dv16_ibRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z22test_bneg_ltz_v16int32Dv16_ibRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_bneg_ltz_v16int32Dv16_ibRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    store i32 [[SPEC_SELECT_I]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_bneg_ltz_v16int32(v16int32 a, bool sgn, unsigned int &cmp) {
  return bneg_ltz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z18test_bneg_v16int32Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z18test_bneg_v16int32Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z18test_bneg_v16int32Dv16_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_bneg_v16int32(v16int32 a) { return bneg(a); }

// AIE2-LABEL: @_Z18test_bxor_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[B:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    [[AND_I_I:%.*]] = and <16 x i32> [[TMP1]], [[A:%.*]]
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A]])
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2-NEXT:    [[AND_I7_I:%.*]] = and <16 x i32> [[TMP3]], [[B]]
// AIE2-NEXT:    [[OR_I_I:%.*]] = or <16 x i32> [[AND_I7_I]], [[AND_I_I]]
// AIE2-NEXT:    ret <16 x i32> [[OR_I_I]]
//
// AIE2P-LABEL: @_Z18test_bxor_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[B:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[AND_I_I:%.*]] = and <16 x i32> [[TMP1]], [[A:%.*]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[AND_I7_I:%.*]] = and <16 x i32> [[TMP3]], [[B]]
// AIE2P-NEXT:    [[OR_I_I:%.*]] = or <16 x i32> [[AND_I7_I]], [[AND_I_I]]
// AIE2P-NEXT:    ret <16 x i32> [[OR_I_I]]
//
// AIE2PS-LABEL: @_Z18test_bxor_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[B:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and <16 x i32> [[TMP1]], [[A:%.*]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[AND_I7_I:%.*]] = and <16 x i32> [[TMP3]], [[B]]
// AIE2PS-NEXT:    [[OR_I_I:%.*]] = or <16 x i32> [[AND_I7_I]], [[AND_I_I]]
// AIE2PS-NEXT:    ret <16 x i32> [[OR_I_I]]
//
v16int32 test_bxor_v16int32(v16int32 a, v16int32 b) { return bxor(a, b); }

// AIE2-LABEL: @_Z21test_abs_gtz_v16int32Dv16_iRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_abs_gtz_v16int32Dv16_iRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_abs_gtz_v16int32Dv16_iRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_abs_gtz_v16int32(v16int32 a, unsigned int &cmp) {
  return abs_gtz(a, cmp);
}

// AIE2-LABEL: @_Z21test_abs_gtz_v16int32Dv16_ibRj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2P-LABEL: @_Z21test_abs_gtz_v16int32Dv16_ibRj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_abs_gtz_v16int32Dv16_ibRj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_abs_gtz_v16int32(v16int32 a, bool sgn, unsigned int &cmp) {
  return abs_gtz(a, sgn, cmp);
}

// AIE2-LABEL: @_Z17test_abs_v16int32Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_abs_v16int32Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_abs_v16int32Dv16_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_abs_v16int32(v16int32 a) { return abs(a); }

// AIE2-LABEL: @_Z17test_abs_v16int32Dv16_ib(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_abs_v16int32Dv16_ib(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret <16 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_abs_v16int32Dv16_ib(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_abs_v16int32(v16int32 a, bool sgn) { return abs(a, sgn); }

// AIE2-LABEL: @_Z16test_lt_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_lt_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_lt_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v16int32(v16int32 a, v16int32 b) { return lt(a, b); }

// AIE2-LABEL: @_Z16test_ge_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_ge_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_ge_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v16int32(v16int32 a, v16int32 b) { return ge(a, b); }

// AIE2-LABEL: @_Z16test_le_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_le_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_le_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v16int32(v16int32 a, v16int32 b) { return le(a, b); }

// AIE2-LABEL: @_Z16test_gt_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 1)
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_gt_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 1)
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_gt_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v16int32(v16int32 a, v16int32 b) { return gt(a, b); }

// AIE2-LABEL: @_Z16test_lt_v16int32Dv16_iS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_lt_v16int32Dv16_iS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_lt_v16int32Dv16_iS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v16int32(v16int32 a, v16int32 b, bool sgn) {
  return lt(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_ge_v16int32Dv16_iS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_ge_v16int32Dv16_iS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_ge_v16int32Dv16_iS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[CONV_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v16int32(v16int32 a, v16int32 b, bool sgn) {
  return ge(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_le_v16int32Dv16_iS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_le_v16int32Dv16_iS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_le_v16int32Dv16_iS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vge32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v16int32(v16int32 a, v16int32 b, bool sgn) {
  return le(a, b, sgn);
}

// AIE2-LABEL: @_Z16test_gt_v16int32Dv16_iS_b(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_gt_v16int32Dv16_iS_b(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_gt_v16int32Dv16_iS_b(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vlt32(<16 x i32> [[B:%.*]], <16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v16int32(v16int32 a, v16int32 b, bool sgn) {
  return gt(a, b, sgn);
}

// AIE2-LABEL: @_Z17test_ltz_v16int32Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_ltz_v16int32Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_ltz_v16int32Dv16_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_ltz_v16int32(v16int32 a) { return ltz(a); }

// AIE2-LABEL: @_Z17test_ltz_v16int32Dv16_ib(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2P-LABEL: @_Z17test_ltz_v16int32Dv16_ib(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2P-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
// AIE2PS-LABEL: @_Z17test_ltz_v16int32Dv16_ib(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vbneg.ltz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[SPEC_SELECT_I_I:%.*]] = select i1 [[SGN:%.*]], i32 [[TMP1]], i32 0
// AIE2PS-NEXT:    ret i32 [[SPEC_SELECT_I_I]]
//
unsigned int test_ltz_v16int32(v16int32 a, bool sgn) { return ltz(a, sgn); }

// AIE2-LABEL: @_Z17test_gtz_v16int32Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_gtz_v16int32Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_gtz_v16int32Dv16_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v16int32(v16int32 a) { return gtz(a); }

// AIE2-LABEL: @_Z17test_gtz_v16int32Dv16_ib(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z17test_gtz_v16int32Dv16_ib(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z17test_gtz_v16int32Dv16_ib(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[CONV_I_I:%.*]] = zext i1 [[SGN:%.*]] to i32
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2ps.vabs.gtz32(<16 x i32> [[A:%.*]], i32 [[CONV_I_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_gtz_v16int32(v16int32 a, bool sgn) { return gtz(a, sgn); }

// AIE2-LABEL: @_Z17test_eqz_v16int32Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz32(<16 x i32> [[A:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_eqz_v16int32Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz32(<16 x i32> [[A:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_eqz_v16int32Dv16_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz32(<16 x i32> [[A:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eqz_v16int32(v16int32 a) { return eqz(a); }

// AIE2-LABEL: @_Z16test_eq_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz32(<16 x i32> [[SUB_I_I]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z16test_eq_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz32(<16 x i32> [[SUB_I_I]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z16test_eq_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz32(<16 x i32> [[SUB_I_I]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_eq_v16int32(v16int32 a, v16int32 b) { return eq(a, b); }

// AIE2-LABEL: @_Z16test_ne_v16int32Dv16_iS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[SUB_I_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.veqz32(<16 x i32> [[SUB_I_I_I]])
// AIE2-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2-NEXT:    ret i32 [[NOT_I]]
//
// AIE2P-LABEL: @_Z16test_ne_v16int32Dv16_iS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SUB_I_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.veqz32(<16 x i32> [[SUB_I_I_I]])
// AIE2P-NEXT:    [[NOT_I:%.*]] = xor i32 [[TMP0]], -1
// AIE2P-NEXT:    ret i32 [[NOT_I]]
//
// AIE2PS-LABEL: @_Z16test_ne_v16int32Dv16_iS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SUB_I_I_I:%.*]] = sub <16 x i32> [[A:%.*]], [[B:%.*]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz32(<16 x i32> [[SUB_I_I_I]])
// AIE2PS-NEXT:    [[XOR_I:%.*]] = xor i32 [[TMP0]], 65535
// AIE2PS-NEXT:    ret i32 [[XOR_I]]
//
unsigned int test_ne_v16int32(v16int32 a, v16int32 b) { return ne(a, b); }

// AIE2-LABEL: @_Z17test_sel_v16int32Dv16_iS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[S:%.*]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_sel_v16int32Dv16_iS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[S:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_sel_v16int32Dv16_iS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[S:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_sel_v16int32(v16int32 a, v16int32 b, unsigned int s) {
  return sel(a, b, s);
}

// AIE2-LABEL: @_Z20test_sel_v32bfloat16Dv32_8bfloat16S0_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <32 x i16>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x bfloat> [[B:%.*]] to <32 x i16>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <32 x i16> @llvm.aie2.vsel16(<32 x i16> [[TMP0]], <32 x i16> [[TMP1]], i32 [[S:%.*]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <32 x bfloat>
// AIE2-NEXT:    ret <32 x bfloat> [[TMP3]]
//
// AIE2P-LABEL: @_Z20test_sel_v32bfloat16Dv32_8bfloat16S0_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x bfloat> [[B:%.*]] to <32 x i16>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[TMP0]], <32 x i16> [[TMP1]], i32 [[S:%.*]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP3]]
//
// AIE2PS-LABEL: @_Z20test_sel_v32bfloat16Dv32_8bfloat16S0_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <32 x i16>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x bfloat> [[B:%.*]] to <32 x i16>
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[TMP0]], <32 x i16> [[TMP1]], i32 [[S:%.*]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP3]]
//
v32bfloat16 test_sel_v32bfloat16(v32bfloat16 a, v32bfloat16 b, unsigned int s) {
  return sel(a, b, s);
}

// AIE2-LABEL: @_Z17test_sel_v16floatDv16_fS_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B:%.*]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[S:%.*]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2P-LABEL: @_Z17test_sel_v16floatDv16_fS_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[S:%.*]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2PS-LABEL: @_Z17test_sel_v16floatDv16_fS_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[TMP0]], <16 x i32> [[TMP1]], i32 [[S:%.*]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP3]]
//
v16float test_sel_v16float(v16float a, v16float b, unsigned int s) {
  return sel(a, b, s);
}

// AIE2-LABEL: @_Z19test_lt_v32bfloat16Dv32_8bfloat16S0_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z19test_lt_v32bfloat16Dv32_8bfloat16S0_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_lt_v32bfloat16Dv32_8bfloat16S0_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_lt_v32bfloat16(v32bfloat16 a, v32bfloat16 b) {
  return lt(a, b);
}

// AIE2-LABEL: @_Z19test_ge_v32bfloat16Dv32_8bfloat16S0_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z19test_ge_v32bfloat16Dv32_8bfloat16S0_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_ge_v32bfloat16Dv32_8bfloat16S0_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ge_v32bfloat16(v32bfloat16 a, v32bfloat16 b) {
  return ge(a, b);
}

// AIE2-LABEL: @_Z19test_le_v32bfloat16Dv32_8bfloat16S0_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z19test_le_v32bfloat16Dv32_8bfloat16S0_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_le_v32bfloat16Dv32_8bfloat16S0_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_le_v32bfloat16(v32bfloat16 a, v32bfloat16 b) {
  return le(a, b);
}

// AIE2-LABEL: @_Z19test_gt_v32bfloat16Dv32_8bfloat16S0_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2-NEXT:    ret i32 [[TMP0]]
//
// AIE2P-LABEL: @_Z19test_gt_v32bfloat16Dv32_8bfloat16S0_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_gt_v32bfloat16Dv32_8bfloat16S0_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gt_v32bfloat16(v32bfloat16 a, v32bfloat16 b) {
  return gt(a, b);
}

// AIE2-LABEL: @_Z20test_ltz_v32bfloat16Dv32_8bfloat16(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 32768)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <32 x bfloat>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[TMP1]])
// AIE2-NEXT:    ret i32 [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_ltz_v32bfloat16Dv32_8bfloat16(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> splat (bfloat 0xR8000))
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ltz_v32bfloat16Dv32_8bfloat16(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[A:%.*]], <32 x bfloat> splat (bfloat 0xR8000))
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_ltz_v32bfloat16(v32bfloat16 a) {
  return ltz(a);
}

// AIE2-LABEL: @_Z20test_gtz_v32bfloat16Dv32_8bfloat16(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 0)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <32 x bfloat>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[TMP1]], <32 x bfloat> [[A:%.*]])
// AIE2-NEXT:    ret i32 [[TMP2]]
//
// AIE2P-LABEL: @_Z20test_gtz_v32bfloat16Dv32_8bfloat16(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> zeroinitializer, <32 x bfloat> [[A:%.*]])
// AIE2P-NEXT:    ret i32 [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_gtz_v32bfloat16Dv32_8bfloat16(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> zeroinitializer, <32 x bfloat> [[A:%.*]])
// AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_gtz_v32bfloat16(v32bfloat16 a) {
  return gtz(a);
}

// AIE2-LABEL: @_Z20test_eqz_v32bfloat16Dv32_8bfloat16(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <32 x i16>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2.veqz16(<32 x i16> [[TMP0]])
// AIE2-NEXT:    ret i32 [[TMP1]]
//
// AIE2P-LABEL: @_Z20test_eqz_v32bfloat16Dv32_8bfloat16(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.veqz16(<32 x i16> [[TMP0]])
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_eqz_v32bfloat16Dv32_8bfloat16(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <32 x bfloat> @llvm.fabs.v32bf16(<32 x bfloat> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x bfloat> [[TMP0]] to <32 x i16>
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef i32 @llvm.aie2ps.veqz16(<32 x i16> [[TMP1]])
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
unsigned int test_eqz_v32bfloat16(v32bfloat16 a) {
  return eqz(a);
}

// AIE2-LABEL: @_Z19test_eq_v32bfloat16Dv32_8bfloat16S0_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[A]], <32 x bfloat> [[B]])
// AIE2-NEXT:    [[AND_I:%.*]] = and i32 [[TMP1]], [[TMP0]]
// AIE2-NEXT:    ret i32 [[AND_I]]
//
// AIE2P-LABEL: @_Z19test_eq_v32bfloat16Dv32_8bfloat16S0_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[A]], <32 x bfloat> [[B]])
// AIE2P-NEXT:    [[AND_I:%.*]] = and i32 [[TMP1]], [[TMP0]]
// AIE2P-NEXT:    ret i32 [[AND_I]]
//
// AIE2PS-LABEL: @_Z19test_eq_v32bfloat16Dv32_8bfloat16S0_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[B:%.*]], <32 x bfloat> [[A:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[A]], <32 x bfloat> [[B]])
// AIE2PS-NEXT:    [[AND_I:%.*]] = and i32 [[TMP1]], [[TMP0]]
// AIE2PS-NEXT:    ret i32 [[AND_I]]
//
unsigned int test_eq_v32bfloat16(v32bfloat16 a, v32bfloat16 b) {
  return eq(a, b);
}

// AIE2-LABEL: @_Z19test_ne_v32bfloat16Dv32_8bfloat16S0_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[B]], <32 x bfloat> [[A]])
// AIE2-NEXT:    [[OR_I:%.*]] = or i32 [[TMP1]], [[TMP0]]
// AIE2-NEXT:    ret i32 [[OR_I]]
//
// AIE2P-LABEL: @_Z19test_ne_v32bfloat16Dv32_8bfloat16S0_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[B]], <32 x bfloat> [[A]])
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[TMP1]], [[TMP0]]
// AIE2P-NEXT:    ret i32 [[OR_I]]
//
// AIE2PS-LABEL: @_Z19test_ne_v32bfloat16Dv32_8bfloat16S0_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[B]], <32 x bfloat> [[A]])
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[TMP1]], [[TMP0]]
// AIE2PS-NEXT:    ret i32 [[OR_I]]
//
unsigned int test_ne_v32bfloat16(v32bfloat16 a, v32bfloat16 b) {
  return ne(a, b);
}

// AIE2-LABEL: @_Z7test_ltDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP1]], <8 x i64> [[TMP2]], i32 28)
// AIE2-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP3]])
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP4]], i32 0)
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[TMP5]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    ret i32 [[TMP6]]
//
// AIE2P-LABEL: @_Z7test_ltDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    ret i32 [[TMP10]]
//
// AIE2PS-LABEL: @_Z7test_ltDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    ret i32 [[TMP10]]
//
unsigned int test_lt(v16float v1, v16float v2) {
  return lt(v1, v2);
}

// AIE2-LABEL: @_Z11test_max_ltDv16_fS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP1]], <8 x i64> [[TMP2]], i32 28)
// AIE2-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP3]])
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP4]], i32 0)
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[TMP5]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    store i32 [[TMP6]], ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2-NEXT:    [[TMP7:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2-NEXT:    [[TMP8:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP7]], <16 x i32> [[TMP8]], i32 [[TMP6]])
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[TMP9]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP10]]
//
// AIE2P-LABEL: @_Z11test_max_ltDv16_fS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    store i32 [[TMP10]], ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[TMP10]])
// AIE2P-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP14]]
//
// AIE2PS-LABEL: @_Z11test_max_ltDv16_fS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    store i32 [[TMP10]], ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP13:%.*]] = tail call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[TMP10]])
// AIE2PS-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP14]]
//
v16float test_max_lt(v16float v1, v16float v2, unsigned int &cmp) {
  return max_lt(v1, v2, cmp);
}

// AIE2-LABEL: @_Z8test_maxDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP1]], <8 x i64> [[TMP2]], i32 28)
// AIE2-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP3]])
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP4]], i32 0)
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[TMP5]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    [[TMP7:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2-NEXT:    [[TMP8:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP7]], <16 x i32> [[TMP8]], i32 [[TMP6]])
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[TMP9]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP10]]
//
// AIE2P-LABEL: @_Z8test_maxDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[TMP10]])
// AIE2P-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP14]]
//
// AIE2PS-LABEL: @_Z8test_maxDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP13:%.*]] = tail call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[TMP10]])
// AIE2PS-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP14]]
//
v16float test_max(v16float v1, v16float v2) {
  return max(v1, v2);
}

// AIE2-LABEL: @_Z7test_geDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP1]], <8 x i64> [[TMP2]], i32 28)
// AIE2-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP3]])
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP4]], i32 0)
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[TMP5]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    [[AND_I:%.*]] = and i32 [[TMP6]], 65535
// AIE2-NEXT:    ret i32 [[AND_I]]
//
// AIE2P-LABEL: @_Z7test_geDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    [[AND_I:%.*]] = and i32 [[TMP10]], 65535
// AIE2P-NEXT:    ret i32 [[AND_I]]
//
// AIE2PS-LABEL: @_Z7test_geDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    [[AND_I:%.*]] = and i32 [[TMP10]], 65535
// AIE2PS-NEXT:    ret i32 [[AND_I]]
//
unsigned int test_ge(v16float v1, v16float v2) {
  return ge(v1, v2);
}

// AIE2-LABEL: @_Z11test_min_geDv16_fS_Rj(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP1]], <8 x i64> [[TMP2]], i32 28)
// AIE2-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP3]])
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP4]], i32 0)
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[TMP5]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP6]], 65535
// AIE2-NEXT:    store i32 [[AND_I_I]], ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2-NEXT:    [[TMP7:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2-NEXT:    [[TMP8:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP7]], <16 x i32> [[TMP8]], i32 [[AND_I_I]])
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[TMP9]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP10]]
//
// AIE2P-LABEL: @_Z11test_min_geDv16_fS_Rj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP10]], 65535
// AIE2P-NEXT:    store i32 [[AND_I_I]], ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[TMP10]])
// AIE2P-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP14]]
//
// AIE2PS-LABEL: @_Z11test_min_geDv16_fS_Rj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP10]], 65535
// AIE2PS-NEXT:    store i32 [[AND_I_I]], ptr [[CMP:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP13:%.*]] = tail call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[AND_I_I]])
// AIE2PS-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP14]]
//
v16float test_min_ge(v16float v1, v16float v2, unsigned int &cmp) {
  return min_ge(v1, v2, cmp);
}

// AIE2-LABEL: @_Z8test_minDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP1]], <8 x i64> [[TMP2]], i32 28)
// AIE2-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP3]])
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP4]], i32 0)
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[TMP5]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP6]], 65535
// AIE2-NEXT:    [[TMP7:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2-NEXT:    [[TMP8:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP7]], <16 x i32> [[TMP8]], i32 [[AND_I_I]])
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[TMP9]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP10]]
//
// AIE2P-LABEL: @_Z8test_minDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[TMP10]])
// AIE2P-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP14]]
//
// AIE2PS-LABEL: @_Z8test_minDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[TMP9]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP10]], 65535
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP13:%.*]] = tail call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[TMP11]], <16 x i32> [[TMP12]], i32 [[AND_I_I]])
// AIE2PS-NEXT:    [[TMP14:%.*]] = bitcast <16 x i32> [[TMP13]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP14]]
//
v16float test_min(v16float v1, v16float v2) {
  return min(v1,v2);
}

// AIE2-LABEL: @_Z7test_gtDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP1]], <8 x i64> [[TMP2]], i32 28)
// AIE2-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP3]])
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP4]], i32 0)
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[TMP0]], <32 x bfloat> [[TMP5]])
// AIE2-NEXT:    ret i32 [[TMP6]]
//
// AIE2P-LABEL: @_Z7test_gtDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> zeroinitializer, <32 x bfloat> [[TMP9]])
// AIE2P-NEXT:    ret i32 [[TMP10]]
//
// AIE2PS-LABEL: @_Z7test_gtDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V2:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP3]], i32 60)
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[TMP4]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP5]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <16 x bfloat> [[TMP7]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> zeroinitializer, <32 x bfloat> [[TMP9]])
// AIE2PS-NEXT:    ret i32 [[TMP10]]
//
unsigned int test_gt(v16float v1, v16float v2) {
  return gt(v1, v2);
}

// AIE2-LABEL: @_Z8test_absDv16_f(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V1:%.*]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[TMP0]], i32 1)
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP1]], 0
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP3]]
//
// AIE2P-LABEL: @_Z8test_absDv16_f(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.fabs.v16f32(<16 x float> [[V1:%.*]])
// AIE2P-NEXT:    ret <16 x float> [[TMP0]]
//
// AIE2PS-LABEL: @_Z8test_absDv16_f(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.fabs.v16f32(<16 x float> [[V1:%.*]])
// AIE2PS-NEXT:    ret <16 x float> [[TMP0]]
//
v16float test_abs(v16float v1) { return abs(v1); }

// AIE2-LABEL: @_Z12test_min_absDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[TMP0]], i32 1)
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP1]], 0
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP4]], <8 x i64> [[TMP5]], i32 28)
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP6]])
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP3]], <16 x bfloat> [[TMP7]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[TMP8]], <32 x bfloat> [[TMP3]])
// AIE2-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP9]], 65535
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP10]], <16 x i32> [[TMP0]], i32 [[AND_I_I]])
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[TMP11]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP12]]
//
// AIE2P-LABEL: @_Z12test_min_absDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP1]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP5]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP4]], <64 x float> [[TMP6]], i32 60)
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x float> [[TMP7]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP8]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP9]])
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x bfloat> [[TMP10]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP11]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[TMP12]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    [[TMP14:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2P-NEXT:    [[TMP15:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[TMP14]], <16 x i32> [[TMP0]], i32 [[TMP13]])
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <16 x i32> [[TMP15]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP16]]
//
// AIE2PS-LABEL: @_Z12test_min_absDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.fabs.v16f32(<16 x float> [[V2:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[TMP0]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP5:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP2]], <64 x float> [[TMP4]], i32 60)
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[TMP5]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP6]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP7:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x bfloat> [[TMP8]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP11:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[TMP10]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP11]], 65535
// AIE2PS-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP13:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[TMP12]], <16 x i32> [[TMP13]], i32 [[AND_I_I]])
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <16 x i32> [[TMP14]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP15]]
//
v16float test_min_abs(v16float v1, v16float v2) {
  return min_abs(v1, v2);
}

// AIE2-LABEL: @_Z12test_max_absDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[TMP0]], i32 1)
// AIE2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP1]], 0
// AIE2-NEXT:    [[TMP3:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP4]], <8 x i64> [[TMP5]], i32 28)
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP6]])
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP3]], <16 x bfloat> [[TMP7]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[TMP8]], <32 x bfloat> [[TMP3]])
// AIE2-NEXT:    [[TMP10:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2-NEXT:    [[TMP11:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP10]], <16 x i32> [[TMP0]], i32 [[TMP9]])
// AIE2-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[TMP11]] to <16 x float>
// AIE2-NEXT:    ret <16 x float> [[TMP12]]
//
// AIE2P-LABEL: @_Z12test_max_absDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP1]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP5]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP4]], <64 x float> [[TMP6]], i32 60)
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x float> [[TMP7]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP8]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP9]])
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x bfloat> [[TMP10]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP11]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[TMP12]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    [[TMP14:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2P-NEXT:    [[TMP15:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[TMP14]], <16 x i32> [[TMP0]], i32 [[TMP13]])
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <16 x i32> [[TMP15]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP16]]
//
// AIE2PS-LABEL: @_Z12test_max_absDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.fabs.v16f32(<16 x float> [[V2:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[TMP0]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP5:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP2]], <64 x float> [[TMP4]], i32 60)
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[TMP5]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP6]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP7:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x bfloat> [[TMP8]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP11:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[TMP10]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    [[TMP12:%.*]] = bitcast <16 x float> [[V1]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP13:%.*]] = bitcast <16 x float> [[V2]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[TMP12]], <16 x i32> [[TMP13]], i32 [[TMP11]])
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <16 x i32> [[TMP14]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP15]]
//
v16float test_max_abs(v16float v1, v16float v2) {
  return max_abs(v1, v2);
}

// AIE2-LABEL: @_Z11test_ge_absDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[TMP1]], i32 1)
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP3]] to <8 x i64>
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP4]], <8 x i64> [[TMP5]], i32 28)
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP6]])
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP7]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef i32 @llvm.aie2.vgebf16(<32 x bfloat> [[TMP8]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    [[AND_I:%.*]] = and i32 [[TMP9]], 65535
// AIE2-NEXT:    ret i32 [[AND_I]]
//
// AIE2P-LABEL: @_Z11test_ge_absDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP1]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP5]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP4]], <64 x float> [[TMP6]], i32 60)
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x float> [[TMP7]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP8]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP9]])
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x bfloat> [[TMP10]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP11]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef i32 @llvm.aie2p.vgebf16(<32 x bfloat> [[TMP12]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    [[AND_I:%.*]] = and i32 [[TMP13]], 65535
// AIE2P-NEXT:    ret i32 [[AND_I]]
//
// AIE2PS-LABEL: @_Z11test_ge_absDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.fabs.v16f32(<16 x float> [[V2:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[TMP0]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP5:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP2]], <64 x float> [[TMP4]], i32 60)
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[TMP5]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP6]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP7:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x bfloat> [[TMP8]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP11:%.*]] = tail call noundef i32 @llvm.aie2ps.vgebfloat16(<32 x bfloat> [[TMP10]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    [[AND_I:%.*]] = and i32 [[TMP11]], 65535
// AIE2PS-NEXT:    ret i32 [[AND_I]]
//
unsigned int test_ge_abs(v16float v1, v16float v2) {
  return ge_abs(v1, v2);
}

// AIE2-LABEL: @_Z11test_lt_absDv16_fS_(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.vbroadcast16.bf512(bfloat 0xR0000)
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2.vabs.gtz32(<16 x i32> [[TMP1]], i32 1)
// AIE2-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP2]], 0
// AIE2-NEXT:    [[TMP4:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP3]] to <8 x i64>
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <8 x i64> @llvm.aie2.sub.accfloat(<8 x i64> [[TMP4]], <8 x i64> [[TMP5]], i32 28)
// AIE2-NEXT:    [[TMP7:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16accfloat.to.v16bf16(<8 x i64> [[TMP6]])
// AIE2-NEXT:    [[TMP8:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.upd.bf512.bf256(<32 x bfloat> [[TMP0]], <16 x bfloat> [[TMP7]], i32 0)
// AIE2-NEXT:    [[TMP9:%.*]] = tail call noundef i32 @llvm.aie2.vltbf16(<32 x bfloat> [[TMP8]], <32 x bfloat> [[TMP0]])
// AIE2-NEXT:    ret i32 [[TMP9]]
//
// AIE2P-LABEL: @_Z11test_lt_absDv16_fS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V2:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, i32 } @llvm.aie2p.vabs.gtz32(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, i32 } [[TMP1]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
// AIE2P-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP5]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.sub.conf(<64 x float> [[TMP4]], <64 x float> [[TMP6]], i32 60)
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x float> [[TMP7]] to <32 x i64>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP8]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[TMP9]])
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <16 x bfloat> [[TMP10]] to <8 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP11]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP12:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    [[TMP13:%.*]] = tail call noundef i32 @llvm.aie2p.vltbf16(<32 x bfloat> [[TMP12]], <32 x bfloat> zeroinitializer)
// AIE2P-NEXT:    ret i32 [[TMP13]]
//
// AIE2PS-LABEL: @_Z11test_lt_absDv16_fS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.fabs.v16f32(<16 x float> [[V2:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[V1:%.*]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[TMP0]] to <8 x i64>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I4_I_I:%.*]] = shufflevector <8 x i64> [[TMP3]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE1_I_I4_I_I]] to <64 x float>
// AIE2PS-NEXT:    [[TMP5:%.*]] = tail call noundef <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP2]], <64 x float> [[TMP4]], i32 60)
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[TMP5]] to <32 x i64>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i64> [[TMP6]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP7:%.*]] = bitcast <8 x i64> [[SHUFFLE_I_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <16 x bfloat> [[TMP8]] to <8 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <16 x i32> [[SHUFFLE1_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    [[TMP11:%.*]] = tail call noundef i32 @llvm.aie2ps.vltbfloat16(<32 x bfloat> [[TMP10]], <32 x bfloat> zeroinitializer)
// AIE2PS-NEXT:    ret i32 [[TMP11]]
//
unsigned int test_lt_abs(v16float v1, v16float v2) {
  return lt_abs(v1, v2);
}
