// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-addr-intrinsic.cpp ---------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O1 %s --target=aie2 -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-COMMON -check-prefix=AIE2
// RUN: %clang -O1 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-COMMON -check-prefix=AIE2P

// CHECK-COMMON-LABEL: @_Z14test_dims_2d_tjii(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T:%.*]] poison, i32 [[SIZE1:%.*]], 0
// CHECK-COMMON-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T]] [[DOTFCA_0_INSERT]], i32 [[INC1:%.*]], 1
// CHECK-COMMON-NEXT:    [[DOTFCA_2_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T]] [[DOTFCA_1_INSERT]], i32 [[INC2:%.*]], 2
// CHECK-COMMON-NEXT:    [[DOTFCA_3_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T]] [[DOTFCA_2_INSERT]], i32 0, 3
// CHECK-COMMON-NEXT:    ret [[STRUCT_DIMS_2D_T]] [[DOTFCA_3_INSERT]]
//
dims_2d_t test_dims_2d_t (unsigned int size1, int inc1, int inc2) {
  return dims_2d_t(size1,inc1, inc2);
}

// CHECK-COMMON-LABEL: @_Z15test2_dims_2d_tjiii(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T:%.*]] poison, i32 [[SIZE1:%.*]], 0
// CHECK-COMMON-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T]] [[DOTFCA_0_INSERT]], i32 [[INC1:%.*]], 1
// CHECK-COMMON-NEXT:    [[DOTFCA_2_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T]] [[DOTFCA_1_INSERT]], i32 [[INC2:%.*]], 2
// CHECK-COMMON-NEXT:    [[DOTFCA_3_INSERT:%.*]] = insertvalue [[STRUCT_DIMS_2D_T]] [[DOTFCA_2_INSERT]], i32 [[COUNT1:%.*]], 3
// CHECK-COMMON-NEXT:    ret [[STRUCT_DIMS_2D_T]] [[DOTFCA_3_INSERT]]
//
dims_2d_t test2_dims_2d_t (unsigned int size1, int inc1, int inc2, addr_t count1){
  return dims_2d_t(size1,inc1, inc2, count1);
}

// CHECK-COMMON-LABEL: @_Z14test_dims_3d_tjijii(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    store i32 [[SIZE1:%.*]], ptr [[AGG_RESULT:%.*]], align 4, !tbaa [[TBAA2:![0-9]+]]
// CHECK-COMMON-NEXT:    [[INC12_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 4
// CHECK-COMMON-NEXT:    store i32 [[INC1:%.*]], ptr [[INC12_I]], align 4, !tbaa [[TBAA7:![0-9]+]]
// CHECK-COMMON-NEXT:    [[NUM2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 8
// CHECK-COMMON-NEXT:    store i32 [[SIZE2:%.*]], ptr [[NUM2_I]], align 4, !tbaa [[TBAA8:![0-9]+]]
// CHECK-COMMON-NEXT:    [[INC23_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 12
// CHECK-COMMON-NEXT:    store i32 [[INC2:%.*]], ptr [[INC23_I]], align 4, !tbaa [[TBAA9:![0-9]+]]
// CHECK-COMMON-NEXT:    [[INC34_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 16
// CHECK-COMMON-NEXT:    store i32 [[INC3:%.*]], ptr [[INC34_I]], align 4, !tbaa [[TBAA10:![0-9]+]]
// CHECK-COMMON-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 20
// CHECK-COMMON-NEXT:    store i32 0, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA11:![0-9]+]]
// CHECK-COMMON-NEXT:    [[COUNT2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 24
// CHECK-COMMON-NEXT:    store i32 0, ptr [[COUNT2_I]], align 4, !tbaa [[TBAA12:![0-9]+]]
// CHECK-COMMON-NEXT:    ret void
//
dims_3d_t test_dims_3d_t  (unsigned int size1, int inc1, unsigned int size2, int inc2, int inc3) {
  return dims_3d_t(size1,inc1,size2, inc2,inc3);
}

// CHECK-COMMON-LABEL: @_Z15test2_dims_3d_tjijiiii(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    store i32 [[SIZE1:%.*]], ptr [[AGG_RESULT:%.*]], align 4, !tbaa [[TBAA2]]
// CHECK-COMMON-NEXT:    [[INC12_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 4
// CHECK-COMMON-NEXT:    store i32 [[INC1:%.*]], ptr [[INC12_I]], align 4, !tbaa [[TBAA7]]
// CHECK-COMMON-NEXT:    [[NUM2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 8
// CHECK-COMMON-NEXT:    store i32 [[SIZE2:%.*]], ptr [[NUM2_I]], align 4, !tbaa [[TBAA8]]
// CHECK-COMMON-NEXT:    [[INC23_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 12
// CHECK-COMMON-NEXT:    store i32 [[INC2:%.*]], ptr [[INC23_I]], align 4, !tbaa [[TBAA9]]
// CHECK-COMMON-NEXT:    [[INC34_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 16
// CHECK-COMMON-NEXT:    store i32 [[INC3:%.*]], ptr [[INC34_I]], align 4, !tbaa [[TBAA10]]
// CHECK-COMMON-NEXT:    [[COUNT15_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 20
// CHECK-COMMON-NEXT:    store i32 [[COUNT1:%.*]], ptr [[COUNT15_I]], align 4, !tbaa [[TBAA11]]
// CHECK-COMMON-NEXT:    [[COUNT26_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i20 24
// CHECK-COMMON-NEXT:    store i32 [[COUNT2:%.*]], ptr [[COUNT26_I]], align 4, !tbaa [[TBAA12]]
// CHECK-COMMON-NEXT:    ret void
//
dims_3d_t test2_dims_3d_t (unsigned int size1, int inc1, unsigned int size2, int inc2, int inc3, addr_t count1, addr_t count2) {
  return dims_3d_t(size1,inc1,size2, inc2,inc3,count1, count2);
}


// CHECK-COMMON-LABEL: @_Z14test_byte_incrPDv32_si(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[IDX_EXT_I:%.*]] = trunc i32 [[INCR:%.*]] to i20
// CHECK-COMMON-NEXT:    [[ADD_PTR_I:%.*]] = getelementptr inbounds i8, ptr [[A:%.*]], i20 [[IDX_EXT_I]]
// CHECK-COMMON-NEXT:    ret ptr [[ADD_PTR_I]]
//
v32int16* test_byte_incr(v32int16* a, int incr){
   return byte_incr(a,incr);
}

// AIE2-LABEL: @_Z15test_add_2d_ptrPDv16_iiiRii(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13:![0-9]+]]
// AIE2-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2-NEXT:    ret ptr [[TMP8]]
//
// AIE2P-LABEL: @_Z15test_add_2d_ptrPDv16_iiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2P-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13:![0-9]+]]
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2P-NEXT:    ret ptr [[TMP8]]
//
v16int32* test_add_2d_ptr(v16int32* a, int off, int size1, addr_t& count1, int inc1){
    return add_2d_ptr(a,off,size1,count1,inc1);
}

// AIE2-LABEL: @_Z15test_add_2d_ptrPKDv16_iiiRii(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2-NEXT:    ret ptr [[TMP8]]
//
// AIE2P-LABEL: @_Z15test_add_2d_ptrPKDv16_iiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2P-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2P-NEXT:    ret ptr [[TMP8]]
//
const v16int32* test_add_2d_ptr(const v16int32* a, int off, int size1, addr_t& count1, int inc1){
    return add_2d_ptr(a,off,size1,count1,inc1);
}

// AIE2-LABEL: @_Z16test_add_2d_bytePDv16_iiiRii(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2-NEXT:    ret ptr [[TMP8]]
//
// AIE2P-LABEL: @_Z16test_add_2d_bytePDv16_iiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2P-NEXT:    ret ptr [[TMP8]]
//
v16int32* test_add_2d_byte(v16int32* a, int off, int size1, addr_t& count1, int inc1){
    return add_2d_byte(a,off,size1,count1,inc1);
}

// AIE2-LABEL: @_Z16test_add_2d_bytePKDv16_iiiRii(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2-NEXT:    ret ptr [[TMP8]]
//
// AIE2P-LABEL: @_Z16test_add_2d_bytePKDv16_iiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP4]])
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = zext i20 [[TMP6]] to i32
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i20 } [[TMP5]], 0
// AIE2P-NEXT:    ret ptr [[TMP8]]
//
const v16int32* test_add_2d_byte(const v16int32* a, int off, int size1, addr_t& count1, int inc1){
    return add_2d_byte(a,off,size1,count1,inc1);
}

// AIE2-LABEL: @_Z15test_add_2d_ptrPDv16_iR9dims_2d_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 8
// AIE2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA14:![0-9]+]]
// AIE2-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA16:![0-9]+]]
// AIE2-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA17:![0-9]+]]
// AIE2-NEXT:    [[MUL_I_I:%.*]] = shl i32 [[TMP0]], 6
// AIE2-NEXT:    [[TMP3:%.*]] = trunc i32 [[MUL_I_I]] to i20
// AIE2-NEXT:    [[MUL1_I_I:%.*]] = shl i32 [[TMP2]], 6
// AIE2-NEXT:    [[TMP4:%.*]] = trunc i32 [[MUL1_I_I]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2-NEXT:    [[TMP6:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP7:%.*]] = trunc i32 [[TMP6]] to i20
// AIE2-NEXT:    [[TMP8:%.*]] = tail call { ptr, i20 } @llvm.aie2.add.2d(ptr [[A:%.*]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP5]], i20 [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 1
// AIE2-NEXT:    [[TMP10:%.*]] = zext i20 [[TMP9]] to i32
// AIE2-NEXT:    store i32 [[TMP10]], ptr [[COUNT1_I]], align 4
// AIE2-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 0
// AIE2-NEXT:    ret ptr [[TMP11]]
//
// AIE2P-LABEL: @_Z15test_add_2d_ptrPDv16_iR9dims_2d_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 8
// AIE2P-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA14:![0-9]+]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA16:![0-9]+]]
// AIE2P-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2P-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA17:![0-9]+]]
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl i32 [[TMP0]], 6
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[MUL_I_I]] to i20
// AIE2P-NEXT:    [[MUL1_I_I:%.*]] = shl i32 [[TMP2]], 6
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[MUL1_I_I]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[TMP6]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr [[A:%.*]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP5]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP10:%.*]] = zext i20 [[TMP9]] to i32
// AIE2P-NEXT:    store i32 [[TMP10]], ptr [[COUNT1_I]], align 4
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 0
// AIE2P-NEXT:    ret ptr [[TMP11]]
//
v16int32* test_add_2d_ptr(v16int32* a, dims_2d_t &params){
  return add_2d_ptr(a,params);
}

// AIE2-LABEL: @_Z16test_add_2d_bytePDv16_iR9dims_2d_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 8
// AIE2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA14]]
// AIE2-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA16]]
// AIE2-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA17]]
// AIE2-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP0]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP2]] to i20
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2-NEXT:    [[TMP6:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP7:%.*]] = trunc i32 [[TMP6]] to i20
// AIE2-NEXT:    [[TMP8:%.*]] = tail call { ptr, i20 } @llvm.aie2.add.2d(ptr [[A:%.*]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP5]], i20 [[TMP7]])
// AIE2-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 1
// AIE2-NEXT:    [[TMP10:%.*]] = zext i20 [[TMP9]] to i32
// AIE2-NEXT:    store i32 [[TMP10]], ptr [[COUNT1_I]], align 4
// AIE2-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 0
// AIE2-NEXT:    ret ptr [[TMP11]]
//
// AIE2P-LABEL: @_Z16test_add_2d_bytePDv16_iR9dims_2d_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 8
// AIE2P-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA14]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA16]]
// AIE2P-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2P-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA17]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP0]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP2]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[TMP6]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr [[A:%.*]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP5]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP10:%.*]] = zext i20 [[TMP9]] to i32
// AIE2P-NEXT:    store i32 [[TMP10]], ptr [[COUNT1_I]], align 4
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i20 } [[TMP8]], 0
// AIE2P-NEXT:    ret ptr [[TMP11]]
//
v16int32* test_add_2d_byte(v16int32* a, dims_2d_t &params){
    return add_2d_byte(a,params);
}

// AIE2-LABEL: @_Z15test_add_3d_ptrPDv16_iR9dims_3d_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[INC3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 16
// AIE2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC3_I]], align 4, !tbaa [[TBAA10]]
// AIE2-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 20
// AIE2-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA7]]
// AIE2-NEXT:    [[NUM2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 8
// AIE2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[NUM2_I]], align 4, !tbaa [[TBAA8]]
// AIE2-NEXT:    [[COUNT2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 24
// AIE2-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA9]]
// AIE2-NEXT:    [[MUL_I_I:%.*]] = shl i32 [[TMP0]], 6
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[MUL_I_I]] to i20
// AIE2-NEXT:    [[MUL1_I_I:%.*]] = shl i32 [[TMP2]], 6
// AIE2-NEXT:    [[TMP6:%.*]] = trunc i32 [[MUL1_I_I]] to i20
// AIE2-NEXT:    [[MUL2_I_I:%.*]] = shl i32 [[TMP4]], 6
// AIE2-NEXT:    [[TMP7:%.*]] = trunc i32 [[MUL2_I_I]] to i20
// AIE2-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2-NEXT:    [[TMP11:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT2_I]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// AIE2-NEXT:    [[TMP14:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2.add.3d(ptr [[A:%.*]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]])
// AIE2-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 1
// AIE2-NEXT:    [[TMP16:%.*]] = zext i20 [[TMP15]] to i32
// AIE2-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 2
// AIE2-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2-NEXT:    store i32 [[TMP16]], ptr [[COUNT1_I]], align 4
// AIE2-NEXT:    store i32 [[TMP18]], ptr [[COUNT2_I]], align 4
// AIE2-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 0
// AIE2-NEXT:    ret ptr [[TMP19]]
//
// AIE2P-LABEL: @_Z15test_add_3d_ptrPDv16_iR9dims_3d_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[INC3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 16
// AIE2P-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC3_I]], align 4, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 20
// AIE2P-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[NUM2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 8
// AIE2P-NEXT:    [[TMP3:%.*]] = load i32, ptr [[NUM2_I]], align 4, !tbaa [[TBAA8]]
// AIE2P-NEXT:    [[COUNT2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 24
// AIE2P-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA9]]
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl i32 [[TMP0]], 6
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[MUL_I_I]] to i20
// AIE2P-NEXT:    [[MUL1_I_I:%.*]] = shl i32 [[TMP2]], 6
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[MUL1_I_I]] to i20
// AIE2P-NEXT:    [[MUL2_I_I:%.*]] = shl i32 [[TMP4]], 6
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[MUL2_I_I]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT2_I]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr [[A:%.*]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]])
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 1
// AIE2P-NEXT:    [[TMP16:%.*]] = zext i20 [[TMP15]] to i32
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 2
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[COUNT1_I]], align 4
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT2_I]], align 4
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 0
// AIE2P-NEXT:    ret ptr [[TMP19]]
//
v16int32* test_add_3d_ptr(v16int32* a, dims_3d_t &params){
  return add_3d_ptr(a,params);
}

// AIE2-LABEL: @_Z16test_add_3d_bytePDv16_iR9dims_3d_t(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[INC3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 16
// AIE2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC3_I]], align 4, !tbaa [[TBAA10]]
// AIE2-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA2]]
// AIE2-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 20
// AIE2-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA7]]
// AIE2-NEXT:    [[NUM2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 8
// AIE2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[NUM2_I]], align 4, !tbaa [[TBAA8]]
// AIE2-NEXT:    [[COUNT2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 24
// AIE2-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA9]]
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP0]] to i20
// AIE2-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP2]] to i20
// AIE2-NEXT:    [[TMP7:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2-NEXT:    [[TMP11:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT2_I]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// AIE2-NEXT:    [[TMP14:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2.add.3d(ptr [[A:%.*]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]])
// AIE2-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 1
// AIE2-NEXT:    [[TMP16:%.*]] = zext i20 [[TMP15]] to i32
// AIE2-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 2
// AIE2-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2-NEXT:    store i32 [[TMP16]], ptr [[COUNT1_I]], align 4
// AIE2-NEXT:    store i32 [[TMP18]], ptr [[COUNT2_I]], align 4
// AIE2-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 0
// AIE2-NEXT:    ret ptr [[TMP19]]
//
// AIE2P-LABEL: @_Z16test_add_3d_bytePDv16_iR9dims_3d_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[INC3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS:%.*]], i20 16
// AIE2P-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INC3_I]], align 4, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[PARAMS]], align 4, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[COUNT1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 20
// AIE2P-NEXT:    [[INC1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 4
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INC1_I]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[NUM2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 8
// AIE2P-NEXT:    [[TMP3:%.*]] = load i32, ptr [[NUM2_I]], align 4, !tbaa [[TBAA8]]
// AIE2P-NEXT:    [[COUNT2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 24
// AIE2P-NEXT:    [[INC2_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PARAMS]], i20 12
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[INC2_I]], align 4, !tbaa [[TBAA9]]
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP0]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP2]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP1]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT1_I]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[TMP3]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT2_I]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr [[A:%.*]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]])
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 1
// AIE2P-NEXT:    [[TMP16:%.*]] = zext i20 [[TMP15]] to i32
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 2
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[COUNT1_I]], align 4
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT2_I]], align 4
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, i20, i20 } [[TMP14]], 0
// AIE2P-NEXT:    ret ptr [[TMP19]]
//
v16int32* test_add_3d_byte(v16int32* a, dims_3d_t &params){
    return add_3d_byte(a,params);
}


// AIE2-LABEL: @_Z15test_add_3d_ptrPDv16_iiiRiiiS1_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2-NEXT:    [[MUL2_I:%.*]] = shl i32 [[INC2:%.*]], 6
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[MUL2_I]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2-NEXT:    ret ptr [[TMP14]]
//
// AIE2P-LABEL: @_Z15test_add_3d_ptrPDv16_iiiRiiiS1_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2P-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2P-NEXT:    [[MUL2_I:%.*]] = shl i32 [[INC2:%.*]], 6
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[MUL2_I]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2P-NEXT:    ret ptr [[TMP14]]
//
v16int32* test_add_3d_ptr(v16int32* a, int off, int size1, addr_t& count1, int inc1, int size2, addr_t& count2, int inc2){
    return add_3d_ptr(a,off,size1,count1,inc1,size2,count2,inc2);
}

// AIE2-LABEL: @_Z15test_add_3d_ptrPKDv16_iiiRiiiS2_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2-NEXT:    [[MUL2_I:%.*]] = shl i32 [[INC2:%.*]], 6
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[MUL2_I]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2-NEXT:    ret ptr [[TMP14]]
//
// AIE2P-LABEL: @_Z15test_add_3d_ptrPKDv16_iiiRiiiS2_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I:%.*]] = shl i32 [[OFF:%.*]], 6
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[MUL_I]] to i20
// AIE2P-NEXT:    [[MUL1_I:%.*]] = shl i32 [[INC1:%.*]], 6
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[MUL1_I]] to i20
// AIE2P-NEXT:    [[MUL2_I:%.*]] = shl i32 [[INC2:%.*]], 6
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[MUL2_I]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2P-NEXT:    ret ptr [[TMP14]]
//
const v16int32* test_add_3d_ptr(const v16int32* a, int off, int size1, addr_t& count1, int inc1, int size2, addr_t& count2, int inc2){
    return add_3d_ptr(a,off,size1,count1,inc1,size2,count2,inc2);
}

// AIE2-LABEL: @_Z16test_add_3d_bytePDv16_iiiRiiiS1_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2-NEXT:    ret ptr [[TMP14]]
//
// AIE2P-LABEL: @_Z16test_add_3d_bytePDv16_iiiRiiiS1_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2P-NEXT:    ret ptr [[TMP14]]
//
v16int32* test_add_3d_byte(v16int32* a, int off, int size1, addr_t& count1, int inc1, int size2, addr_t& count2, int inc2){
    return add_3d_byte(a,off,size1,count1,inc1,size2,count2,inc2);
}

// AIE2-LABEL: @_Z16test_add_3d_bytePKDv16_iiiRiiiS2_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2-NEXT:    [[TMP2:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2-NEXT:    ret ptr [[TMP14]]
//
// AIE2P-LABEL: @_Z16test_add_3d_bytePKDv16_iiiRiiiS2_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA13]]
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr [[A:%.*]], i20 [[TMP0]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP8]])
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 2
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i20, i20 } [[TMP9]], 0
// AIE2P-NEXT:    ret ptr [[TMP14]]
//
const v16int32* test_add_3d_byte(const v16int32* a, int off, int size1, addr_t& count1, int inc1, int size2, addr_t& count2, int inc2){
    return add_3d_byte(a,off,size1,count1,inc1,size2,count2,inc2);
}
// AIE2-LABEL: @_Z17test_load_4x16_loDv8_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.lo(<8 x i32> [[ADDR:%.*]])
// AIE2-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_load_4x16_loDv8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.lo(<8 x i32> [[ADDR:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_load_4x16_lo(v8int32 addr) {
  return load_4x16_lo(addr);
}
// AIE2-LABEL: @_Z17test_load_4x16_hiDv8_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x16.hi(<8 x i32> [[ADDR:%.*]])
// AIE2-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_load_4x16_hiDv8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x16.hi(<8 x i32> [[ADDR:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_load_4x16_hi(v8int32 addr) {
  return load_4x16_hi(addr);
}
// AIE2-LABEL: @_Z17test_load_4x32_loDv8_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.lo(<8 x i32> [[ADDR:%.*]])
// AIE2-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_load_4x32_loDv8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.lo(<8 x i32> [[ADDR:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_load_4x32_lo(v8int32 addr) {
  return load_4x32_lo(addr);
}
// AIE2-LABEL: @_Z17test_load_4x32_hiDv8_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x32.hi(<8 x i32> [[ADDR:%.*]])
// AIE2-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_load_4x32_hiDv8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x32.hi(<8 x i32> [[ADDR:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_load_4x32_hi(v8int32 addr) {
  return load_4x32_hi(addr);
}
// AIE2-LABEL: @_Z17test_load_4x64_loDv8_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.lo(<8 x i32> [[ADDR:%.*]])
// AIE2-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_load_4x64_loDv8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.lo(<8 x i32> [[ADDR:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_load_4x64_lo(v8int32 addr) {
  return load_4x64_lo(addr);
}
// AIE2-LABEL: @_Z17test_load_4x64_hiDv8_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2.load.4x64.hi(<8 x i32> [[ADDR:%.*]])
// AIE2-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2P-LABEL: @_Z17test_load_4x64_hiDv8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.load.4x64.hi(<8 x i32> [[ADDR:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_load_4x64_hi(v8int32 addr) {
  return load_4x64_hi(addr);
}

// AIE2-LABEL: @_Z16test_lut_pointerPKvS0_Dv16_i(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    ret <16 x i32> [[ADD_I]]
//
// AIE2P-LABEL: @_Z16test_lut_pointerPKvS0_Dv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    ret <16 x i32> [[ADD_I]]
//
v16int32 test_lut_pointer(const void *lut1, const void *lut2, v16int32 offset) {
  return lut_pointer(lut1, lut2, offset);
}


// AIE2-LABEL: @_Z25test_lut_pointer_unsignedPKvS0_Dv16_j(
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2-NEXT:    [[TMP4:%.*]] = zext i20 [[TMP3]] to i32
// AIE2-NEXT:    [[TMP5:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 [[TMP4]])
// AIE2-NEXT:    [[TMP6:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vsel32(<16 x i32> [[TMP2]], <16 x i32> [[TMP5]], i32 52428)
// AIE2-NEXT:    [[ADD_I:%.*]] = add <16 x i32> [[TMP6]], [[OFFSET:%.*]]
// AIE2-NEXT:    ret <16 x i32> [[ADD_I]]
//
// AIE2P-LABEL: @_Z25test_lut_pointer_unsignedPKvS0_Dv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[LUT1:%.*]] to i20
// AIE2P-NEXT:    [[TMP1:%.*]] = zext i20 [[TMP0]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[LUT2:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = zext i20 [[TMP2]] to i32
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I3_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP3]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I4_I:%.*]] = shufflevector <16 x i32> [[SPLAT_SPLATINSERT_I3_I]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[SPLAT_SPLAT_I_I]], <16 x i32> [[SPLAT_SPLAT_I4_I]], i32 52428)
// AIE2P-NEXT:    [[ADD_I:%.*]] = add <16 x i32> [[TMP4]], [[OFFSET:%.*]]
// AIE2P-NEXT:    ret <16 x i32> [[ADD_I]]
//
v16uint32 test_lut_pointer_unsigned(const void *lut1, const void *lut2, v16uint32 offset) {
  return lut_pointer(lut1, lut2, offset);
}

