// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// ----- aie-memset.cpp -----------------------------------------------------///
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
// --------------------------------------------------------------------------///

// RUN: %clang --target=aie2p-none-unknown-elf -O2 -S -emit-llvm %s -o - | FileCheck %s -check-prefix=DEFAULT
// RUN: %clang --target=aie2p-none-unknown-elf -O2 -S -fbuiltin -emit-llvm %s -o - | FileCheck %s -check-prefix=FBUILTIN
// RUN: %clang --target=aie2p-none-unknown-elf -O2 -S -fno-builtin -emit-llvm %s -o - | FileCheck %s -check-prefix=FNO-BUILTIN


// DEFAULT-LABEL: define dso_local ptr @_Z10aie_memsetPvii(
// DEFAULT-SAME: ptr returned writeonly [[PTR:%.*]], i32 noundef [[C:%.*]], i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// DEFAULT-NEXT:  entry:
// DEFAULT-NEXT:    [[CMP4:%.*]] = icmp sgt i32 [[N]], 0
// DEFAULT-NEXT:    br i1 [[CMP4]], label [[WHILE_BODY_LR_PH:%.*]], label [[WHILE_END:%.*]]
// DEFAULT:       while.body.lr.ph:
// DEFAULT-NEXT:    [[CONV:%.*]] = trunc i32 [[C]] to i8
// DEFAULT-NEXT:    br label [[WHILE_BODY:%.*]]
// DEFAULT:       while.body:
// DEFAULT-NEXT:    [[P_CHAR_06:%.*]] = phi ptr [ [[PTR]], [[WHILE_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_BODY]] ]
// DEFAULT-NEXT:    [[N_ADDR_05:%.*]] = phi i32 [ [[N]], [[WHILE_BODY_LR_PH]] ], [ [[DEC:%.*]], [[WHILE_BODY]] ]
// DEFAULT-NEXT:    store i8 [[CONV]], ptr [[P_CHAR_06]], align 1, !tbaa [[TBAA2:![0-9]+]]
// DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr [[P_CHAR_06]], i20 1
// DEFAULT-NEXT:    [[DEC]] = add nsw i32 [[N_ADDR_05]], -1
// DEFAULT-NEXT:    [[CMP:%.*]] = icmp samesign ugt i32 [[N_ADDR_05]], 1
// DEFAULT-NEXT:    br i1 [[CMP]], label [[WHILE_BODY]], label [[WHILE_END]], !llvm.loop [[LOOP5:![0-9]+]]
// DEFAULT:       while.end:
// DEFAULT-NEXT:    ret ptr [[PTR]]
//
// FBUILTIN-LABEL: define dso_local ptr @_Z10aie_memsetPvii(
// FBUILTIN-SAME: ptr returned writeonly [[PTR:%.*]], i32 noundef [[C:%.*]], i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// FBUILTIN-NEXT:  entry:
// FBUILTIN-NEXT:    [[CMP4:%.*]] = icmp sgt i32 [[N]], 0
// FBUILTIN-NEXT:    br i1 [[CMP4]], label [[WHILE_BODY_LR_PH:%.*]], label [[WHILE_END:%.*]]
// FBUILTIN:       while.body.lr.ph:
// FBUILTIN-NEXT:    [[CONV:%.*]] = trunc i32 [[C]] to i8
// FBUILTIN-NEXT:    [[TMP0:%.*]] = trunc i32 [[N]] to i20
// FBUILTIN-NEXT:    tail call void @llvm.memset.p0.i20(ptr align 1 [[PTR]], i8 [[CONV]], i20 [[TMP0]], i1 false), !tbaa [[TBAA2:![0-9]+]]
// FBUILTIN-NEXT:    br label [[WHILE_END]]
// FBUILTIN:       while.end:
// FBUILTIN-NEXT:    ret ptr [[PTR]]
//
// FNO-BUILTIN-LABEL: define dso_local ptr @_Z10aie_memsetPvii(
// FNO-BUILTIN-SAME: ptr returned writeonly [[PTR:%.*]], i32 noundef [[C:%.*]], i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// FNO-BUILTIN-NEXT:  entry:
// FNO-BUILTIN-NEXT:    [[CMP4:%.*]] = icmp sgt i32 [[N]], 0
// FNO-BUILTIN-NEXT:    br i1 [[CMP4]], label [[WHILE_BODY_LR_PH:%.*]], label [[WHILE_END:%.*]]
// FNO-BUILTIN:       while.body.lr.ph:
// FNO-BUILTIN-NEXT:    [[CONV:%.*]] = trunc i32 [[C]] to i8
// FNO-BUILTIN-NEXT:    br label [[WHILE_BODY:%.*]]
// FNO-BUILTIN:       while.body:
// FNO-BUILTIN-NEXT:    [[P_CHAR_06:%.*]] = phi ptr [ [[PTR]], [[WHILE_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_BODY]] ]
// FNO-BUILTIN-NEXT:    [[N_ADDR_05:%.*]] = phi i32 [ [[N]], [[WHILE_BODY_LR_PH]] ], [ [[DEC:%.*]], [[WHILE_BODY]] ]
// FNO-BUILTIN-NEXT:    store i8 [[CONV]], ptr [[P_CHAR_06]], align 1, !tbaa [[TBAA2:![0-9]+]]
// FNO-BUILTIN-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr [[P_CHAR_06]], i20 1
// FNO-BUILTIN-NEXT:    [[DEC]] = add nsw i32 [[N_ADDR_05]], -1
// FNO-BUILTIN-NEXT:    [[CMP:%.*]] = icmp samesign ugt i32 [[N_ADDR_05]], 1
// FNO-BUILTIN-NEXT:    br i1 [[CMP]], label [[WHILE_BODY]], label [[WHILE_END]], !llvm.loop [[LOOP5:![0-9]+]]
// FNO-BUILTIN:       while.end:
// FNO-BUILTIN-NEXT:    ret ptr [[PTR]]
//
void  *aie_memset(void *ptr, int c, int n){
  unsigned char *p_char = (unsigned char *) ptr;
  while(n > 0){
      *p_char = c;
      p_char++;
      n--;
  }
  return ptr;
}
//.
// DEFAULT: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// DEFAULT: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// DEFAULT: [[META4]] = !{!"Simple C++ TBAA"}
// DEFAULT: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]]}
// DEFAULT: [[META6]] = !{!"llvm.loop.mustprogress"}
//.
// FBUILTIN: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// FBUILTIN: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// FBUILTIN: [[META4]] = !{!"Simple C++ TBAA"}
//.
// FNO-BUILTIN: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// FNO-BUILTIN: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// FNO-BUILTIN: [[META4]] = !{!"Simple C++ TBAA"}
// FNO-BUILTIN: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]]}
// FNO-BUILTIN: [[META6]] = !{!"llvm.loop.mustprogress"}
//.
