// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-set-mode.cpp ----------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2 -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-AIEV2
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-AIE2P

// CHECK-AIEV2-LABEL: @_Z16test_set_satmodej(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 9, i32 [[VAL:%.*]])
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z16test_set_satmodej(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[VAL:%.*]])
// CHECK-AIE2P-NEXT:    ret void
//
void test_set_satmode (unsigned int val) {
  return set_satmode(val);
}

// CHECK-AIEV2-LABEL: @_Z12test_set_satv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 9, i32 1)
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z12test_set_satv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 1)
// CHECK-AIE2P-NEXT:    ret void
//
void test_set_sat () {
  return set_sat();
}

// CHECK-AIEV2-LABEL: @_Z15test_set_symsatv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 9, i32 3)
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z15test_set_symsatv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 3)
// CHECK-AIE2P-NEXT:    ret void
//
void test_set_symsat () {
  return set_symsat();
}

// CHECK-AIEV2-LABEL: @_Z12test_clr_satv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 9, i32 0)
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z12test_clr_satv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 0)
// CHECK-AIE2P-NEXT:    ret void
//
void test_clr_sat () {
  return clr_sat();
}

// CHECK-AIEV2-LABEL: @_Z12test_set_rndj(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 6, i32 [[VAL:%.*]])
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z12test_set_rndj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[VAL:%.*]])
// CHECK-AIE2P-NEXT:    ret void
//
void test_set_rnd (unsigned int val) {
  return set_rnd(val);
}

// CHECK-AIEV2-LABEL: @_Z22test_set_fpmulmac_maskj(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 3, i32 [[VAL:%.*]])
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z22test_set_fpmulmac_maskj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 2, i32 [[VAL:%.*]])
// CHECK-AIE2P-NEXT:    ret void
//
void test_set_fpmulmac_mask (unsigned int val) {
  return set_fpmulmac_mask(val);
}

// CHECK-AIEV2-LABEL: @_Z20test_set_fp2int_maskj(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 2, i32 [[VAL:%.*]])
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z20test_set_fp2int_maskj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 3, i32 [[VAL:%.*]])
// CHECK-AIE2P-NEXT:    ret void
//
void test_set_fp2int_mask (unsigned int val) {
  return set_fp2int_mask(val);
}

// CHECK-AIEV2-LABEL: @_Z19test_set_fp2bf_maskj(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    tail call void @llvm.aie2.set.ctrl.reg(i32 1, i32 [[VAL:%.*]])
// CHECK-AIEV2-NEXT:    ret void
//
// CHECK-AIE2P-LABEL: @_Z19test_set_fp2bf_maskj(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 4, i32 [[VAL:%.*]])
// CHECK-AIE2P-NEXT:    ret void
//
void test_set_fp2bf_mask (unsigned int val) {
  return set_fp2bf_mask(val);
}

// CHECK-AIEV2-LABEL: @_Z16test_get_satmodev(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.get.ctrl.reg(i32 9)
// CHECK-AIEV2-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2P-LABEL: @_Z16test_get_satmodev(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_satmode() { return get_satmode(); }

// CHECK-AIEV2-LABEL: @_Z12test_get_satv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.get.ctrl.reg(i32 9)
// CHECK-AIEV2-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2P-LABEL: @_Z12test_get_satv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_sat() { return get_sat(); }

// CHECK-AIEV2-LABEL: @_Z12test_get_rndv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.get.ctrl.reg(i32 6)
// CHECK-AIEV2-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2P-LABEL: @_Z12test_get_rndv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_rnd() { return get_rnd(); }

// CHECK-AIEV2-LABEL: @_Z22test_get_fpmulmac_maskv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.get.ctrl.reg(i32 3)
// CHECK-AIEV2-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2P-LABEL: @_Z22test_get_fpmulmac_maskv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 2)
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fpmulmac_mask() {
  return get_fpmulmac_mask();
}

// CHECK-AIEV2-LABEL: @_Z20test_get_fp2int_maskv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.get.ctrl.reg(i32 2)
// CHECK-AIEV2-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2P-LABEL: @_Z20test_get_fp2int_maskv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 3)
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fp2int_mask() {
  return get_fp2int_mask();
}

// CHECK-AIEV2-LABEL: @_Z19test_get_fp2bf_maskv(
// CHECK-AIEV2-NEXT:  entry:
// CHECK-AIEV2-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2.get.ctrl.reg(i32 1)
// CHECK-AIEV2-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2P-LABEL: @_Z19test_get_fp2bf_maskv(
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 4)
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fp2bf_mask() {
  return get_fp2bf_mask();
}
