// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- bitint.cpp -----------------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
//RUN: %clang --target=aie -S -emit-llvm %s -o - | FileCheck %s
//RUN: %clang --target=aie2 -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s
//
// CHECK-LABEL: @_Z12bitint2_testDU2_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i2 [[VAL:%.*]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP0]] to i2
// CHECK-NEXT:    ret i2 [[LOADEDV]]
//
uint2_t bitint2_test(uint2_t val) {
  return val;
}

// CHECK-LABEL: @_Z12bitint4_testDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i4 [[VAL:%.*]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP0]] to i4
// CHECK-NEXT:    ret i4 [[LOADEDV]]
//
uint4_t bitint4_test(uint4_t val) {
  return val;
}
// CHECK-LABEL: @_Z12bitint6_testDU6_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i6 [[VAL:%.*]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP0]] to i6
// CHECK-NEXT:    ret i6 [[LOADEDV]]
//
uint6_t bitint6_test(uint6_t val) {
  return val;
}
