// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals all --version 5
// --- peel-aie-hint.c ------------------------------------------------------///
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
// --------------------------------------------------------------------------///

// Verify that loop metadata survives loop peeling and that
// iteration counts are adjusted correctly.

// RUN: %clang --target=aie2ps -O2 -mllvm --unroll-force-peel-count=2 -S -emit-llvm %s -o - | FileCheck %s

// CHECK-LABEL: define dso_local i32 @bool_hint_peel(
// CHECK-SAME: i32 noundef [[N:%.*]], ptr readonly captures(none) [[P:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[FOR_BODY_PEEL_NEXT6:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = icmp sgt i32 [[N]], 27
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// CHECK-NEXT:    [[ARRAYIDX_PEEL8:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i20 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX_PEEL8]], align 4, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[P]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ADD_PEEL9:%.*]] = add nsw i32 [[TMP1]], [[TMP2]]
// CHECK-NEXT:    br label %[[FOR_BODY:.*]]
// CHECK:       [[FOR_COND_CLEANUP:.*]]:
// CHECK-NEXT:    ret i32 [[ADD:%.*]]
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    [[I_05:%.*]] = phi i32 [ 2, %[[FOR_BODY_PEEL_NEXT6]] ], [ [[INC:%.*]], %[[FOR_BODY]] ]
// CHECK-NEXT:    [[S_04:%.*]] = phi i32 [ [[ADD_PEEL9]], %[[FOR_BODY_PEEL_NEXT6]] ], [ [[ADD]], %[[FOR_BODY]] ]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[I_05]] to i20
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[P]], i20 [[TMP3]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ADD]] = add nsw i32 [[TMP4]], [[S_04]]
// CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_05]], 1
// CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[N]]
// CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
//
int bool_hint_peel(int n, int *p) {
  int s = 0;
  #pragma clang loop min_iteration_count(28)
  #pragma clang loop max_iteration_count(37)
  for (int i = 0; i < n; i++) {
    s += p[i];
  }
  return s;
}

// CHECK-LABEL: define dso_local i32 @int_hint_peel(
// CHECK-SAME: i32 noundef [[N:%.*]], ptr readonly captures(none) [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[FOR_BODY_PEEL_NEXT6:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = icmp sgt i32 [[N]], 27
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// CHECK-NEXT:    [[ARRAYIDX_PEEL8:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i20 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX_PEEL8]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[P]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ADD_PEEL9:%.*]] = add nsw i32 [[TMP1]], [[TMP2]]
// CHECK-NEXT:    br label %[[FOR_BODY:.*]]
// CHECK:       [[FOR_COND_CLEANUP:.*]]:
// CHECK-NEXT:    ret i32 [[ADD:%.*]]
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    [[I_05:%.*]] = phi i32 [ 2, %[[FOR_BODY_PEEL_NEXT6]] ], [ [[INC:%.*]], %[[FOR_BODY]] ]
// CHECK-NEXT:    [[S_04:%.*]] = phi i32 [ [[ADD_PEEL9]], %[[FOR_BODY_PEEL_NEXT6]] ], [ [[ADD]], %[[FOR_BODY]] ]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[I_05]] to i20
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[P]], i20 [[TMP3]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ADD]] = add nsw i32 [[TMP4]], [[S_04]]
// CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_05]], 1
// CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[N]]
// CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
//
int int_hint_peel(int n, int *p) {
  int s = 0;
  #pragma clang loop min_iteration_count(28)
  #pragma clang loop max_iteration_count(37)
  for (int i = 0; i < n; i++) {
    s += p[i];
  }
  return s;
}

// CHECK-LABEL: define dso_local i32 @multi_hint_peel(
// CHECK-SAME: i32 noundef [[N:%.*]], ptr readonly captures(none) [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[FOR_BODY_PEEL_NEXT6:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = icmp sgt i32 [[N]], 27
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// CHECK-NEXT:    [[ARRAYIDX_PEEL8:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i20 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX_PEEL8]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[P]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ADD_PEEL9:%.*]] = add nsw i32 [[TMP1]], [[TMP2]]
// CHECK-NEXT:    br label %[[FOR_BODY:.*]]
// CHECK:       [[FOR_COND_CLEANUP:.*]]:
// CHECK-NEXT:    ret i32 [[ADD:%.*]]
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    [[I_05:%.*]] = phi i32 [ 2, %[[FOR_BODY_PEEL_NEXT6]] ], [ [[INC:%.*]], %[[FOR_BODY]] ]
// CHECK-NEXT:    [[S_04:%.*]] = phi i32 [ [[ADD_PEEL9]], %[[FOR_BODY_PEEL_NEXT6]] ], [ [[ADD]], %[[FOR_BODY]] ]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[I_05]] to i20
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[P]], i20 [[TMP3]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ADD]] = add nsw i32 [[TMP4]], [[S_04]]
// CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_05]], 1
// CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[N]]
// CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
//
int multi_hint_peel(int n, int *p) {
  int s = 0;
  #pragma clang loop min_iteration_count(28)
  #pragma clang loop max_iteration_count(37)
  for (int i = 0; i < n; i++) {
    s += p[i];
  }
  return s;
}
//.
// CHECK: attributes #[[ATTR0]] = { nofree norecurse nosync nounwind memory(argmem: read) "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
//.
// CHECK: [[META0:![0-9]+]] = !{i32 1, !"wchar_size", i32 4}
// CHECK: [[META1:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META7:![0-9]+]], [[META8:![0-9]+]], [[META9:![0-9]+]]}
// CHECK: [[META7]] = !{!"llvm.loop.peeled.count", i32 2}
// CHECK: [[META8]] = !{!"llvm.loop.itercount.range", i32 26, i32 35}
// CHECK: [[META9]] = !{!"llvm.loop.unroll.disable"}
// CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META7]], [[META8]], [[META9]]}
// CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META7]], [[META8]], [[META9]]}
//.
