# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p --aie-loop-min-tripcount=4 --aie-addrspace-none-is-safe=0 %s \
# RUN:   --start-before=postmisched -o - | FileCheck %s --check-prefix=CONSERVATIVE
# RUN: llc --mtriple=aie2p --aie-loop-min-tripcount=4 --aie-addrspace-none-is-safe=1 %s \
# RUN:   --start-before=postmisched -o - | FileCheck %s --check-prefix=OPTIMISTIC


--- |
  define void @convert_bf16_to_bfp16(ptr noalias %in, ptr noalias %out, ptr nonnull align 64 dereferenceable(64) %params) {
  ; CONSERVATIVE-LABEL: convert_bf16_to_bfp16:
  ; CONSERVATIVE:         .p2align 4
  ; CONSERVATIVE-NEXT:  // %bb.0: // %entry
  ; CONSERVATIVE-NEXT:    lda r0, [p2, #0]
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    jz r0, #.LBB0_4
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 5
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 4
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 3
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 2
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 1
  ; CONSERVATIVE-NEXT:  // %bb.1:
  ; CONSERVATIVE-NEXT:    mova m0, #12; mov p3, p2
  ; CONSERVATIVE-NEXT:    padda [p3], m0
  ; CONSERVATIVE-NEXT:    lda m0, [p3], #-4
  ; CONSERVATIVE-NEXT:    lda m1, [p3], #-4
  ; CONSERVATIVE-NEXT:    lda dn0, [p3, #0]
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    mova dj0, #0
  ; CONSERVATIVE-NEXT:    mova r24, #0; mov dj1, dj0
  ; CONSERVATIVE-NEXT:    mov r26, r24
  ; CONSERVATIVE-NEXT:    vldb.fill.512 [p0, lf0, r24]; mov dc1, dj0
  ; CONSERVATIVE-NEXT:    vldb.pop.512 x0, [p0, lf0, r24]; mov dn1, dn0
  ; CONSERVATIVE-NEXT:    vldb.pop.512.2d x2, [p0, lf0, r24, d1]
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    vldb.fill.512 [p0, lf0, r24]
  ; CONSERVATIVE-NEXT:    vldb.pop.512 x0, [p0, lf0, r24]; mov p2, p1
  ; CONSERVATIVE-NEXT:    vldb.pop.512.2d x2, [p0, lf0, r24, d1]; add.nc lc, r0, #-3
  ; CONSERVATIVE-NEXT:    movxm ls, #.LBB0_2
  ; CONSERVATIVE-NEXT:    nopa ; vldb.fill.512 [p0, lf0, r24]; nops ; movxm le, #.L_LEnd0; nopv
  ; CONSERVATIVE-NEXT:    nopa ; vldb.pop.512 x0, [p0, lf0, r24]; nops ; nopx ; vconv.fp32.bf16 cml0, x0; nopv
  ; CONSERVATIVE-NEXT:    nopa ; vldb.pop.512.2d x2, [p0, lf0, r24, d1]; nops ; nopx ; vconv.fp32.bf16 cmh0, x2; nopv
  ; CONSERVATIVE-NEXT:    nopa ; nopb ; nops ; nopx ; mov dc0, dj0; nopv
  ; CONSERVATIVE-NEXT:    .p2align 4
  ; CONSERVATIVE-NEXT:  .LBB0_2: // =>This Inner Loop Header: Depth=1
  ; CONSERVATIVE-NEXT:    nopa ; vldb.fill.512 [p0, lf0, r24]; vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]; nopxm ; nopv
  ; CONSERVATIVE-NEXT:    nopa ; vldb.pop.512 x0, [p0, lf0, r24]; vst.flush.512.conv [p2, sf, r26]; nopx ; vconv.fp32.bf16 cml0, x0; nopv
  ; CONSERVATIVE-NEXT:    nopa ; vldb.pop.512.2d x2, [p0, lf0, r24, d1]; vst.flush.512.conv.2d [p2, sf, r26, d0]; nopx ; vconv.fp32.bf16 cmh0, x2; nopv
  ; CONSERVATIVE-NEXT:  .L_LEnd0:
  ; CONSERVATIVE-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CONSERVATIVE-NEXT:  // %bb.3:
  ; CONSERVATIVE-NEXT:    vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]
  ; CONSERVATIVE-NEXT:    vst.flush.512.conv [p2, sf, r26]; vconv.fp32.bf16 cml0, x0
  ; CONSERVATIVE-NEXT:    vst.flush.512.conv.2d [p2, sf, r26, d0]; vconv.fp32.bf16 cmh0, x2
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]
  ; CONSERVATIVE-NEXT:    vst.flush.512.conv [p2, sf, r26]; vconv.fp32.bf16 cml0, x0
  ; CONSERVATIVE-NEXT:    vst.flush.512.conv.2d [p2, sf, r26, d0]; vconv.fp32.bf16 cmh0, x2
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]
  ; CONSERVATIVE-NEXT:    vst.flush.512.conv [p2, sf, r26]
  ; CONSERVATIVE-NEXT:    vst.flush.512.conv.2d [p2, sf, r26, d0]
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    nop
  ; CONSERVATIVE-NEXT:    .p2align 4
  ; CONSERVATIVE-NEXT:  .LBB0_4:
  ; CONSERVATIVE-NEXT:    nopa ; ret lr
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 5
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 4
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 3
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 2
  ; CONSERVATIVE-NEXT:    nop // Delay Slot 1
  ;
  ; OPTIMISTIC-LABEL: convert_bf16_to_bfp16:
  ; OPTIMISTIC:         .p2align 4
  ; OPTIMISTIC-NEXT:  // %bb.0: // %entry
  ; OPTIMISTIC-NEXT:    lda r0, [p2, #0]
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    jz r0, #.LBB0_4
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 5
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 4
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 3
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 2
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 1
  ; OPTIMISTIC-NEXT:  // %bb.1:
  ; OPTIMISTIC-NEXT:    mova m0, #12; mov p3, p2
  ; OPTIMISTIC-NEXT:    padda [p3], m0
  ; OPTIMISTIC-NEXT:    lda m0, [p3], #-4
  ; OPTIMISTIC-NEXT:    lda m1, [p3], #-4
  ; OPTIMISTIC-NEXT:    lda dn0, [p3, #0]
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    mova dj0, #0
  ; OPTIMISTIC-NEXT:    mova r24, #0; mov dj1, dj0
  ; OPTIMISTIC-NEXT:    mov r26, r24
  ; OPTIMISTIC-NEXT:    vldb.fill.512 [p0, lf0, r24]; mov dc1, dj0
  ; OPTIMISTIC-NEXT:    vldb.pop.512 x0, [p0, lf0, r24]; mov dn1, dn0
  ; OPTIMISTIC-NEXT:    vldb.pop.512.2d x2, [p0, lf0, r24, d1]
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    vldb.fill.512 [p0, lf0, r24]
  ; OPTIMISTIC-NEXT:    vldb.pop.512 x0, [p0, lf0, r24]; mov p2, p1
  ; OPTIMISTIC-NEXT:    vldb.pop.512.2d x2, [p0, lf0, r24, d1]; add.nc lc, r0, #-3
  ; OPTIMISTIC-NEXT:    movxm ls, #.LBB0_2
  ; OPTIMISTIC-NEXT:    nopa ; vldb.fill.512 [p0, lf0, r24]; nops ; movxm le, #.L_LEnd0; nopv
  ; OPTIMISTIC-NEXT:    nopa ; vldb.pop.512 x0, [p0, lf0, r24]; nops ; nopx ; vconv.fp32.bf16 cml0, x0; nopv
  ; OPTIMISTIC-NEXT:    nopa ; vldb.pop.512.2d x2, [p0, lf0, r24, d1]; nops ; nopx ; vconv.fp32.bf16 cmh0, x2; nopv
  ; OPTIMISTIC-NEXT:    nopa ; nopb ; nops ; nopx ; mov dc0, dj0; nopv
  ; OPTIMISTIC-NEXT:    .p2align 4
  ; OPTIMISTIC-NEXT:  .LBB0_2: // =>This Inner Loop Header: Depth=1
  ; OPTIMISTIC-NEXT:    nopa ; vldb.fill.512 [p0, lf0, r24]; vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]; nopxm ; nopv
  ; OPTIMISTIC-NEXT:    nopa ; vldb.pop.512 x0, [p0, lf0, r24]; vst.flush.512.conv [p2, sf, r26]; nopx ; vconv.fp32.bf16 cml0, x0; nopv
  ; OPTIMISTIC-NEXT:    nopa ; vldb.pop.512.2d x2, [p0, lf0, r24, d1]; vst.flush.512.conv.2d [p2, sf, r26, d0]; nopx ; vconv.fp32.bf16 cmh0, x2; nopv
  ; OPTIMISTIC-NEXT:  .L_LEnd0:
  ; OPTIMISTIC-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; OPTIMISTIC-NEXT:  // %bb.3:
  ; OPTIMISTIC-NEXT:    vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]
  ; OPTIMISTIC-NEXT:    vst.flush.512.conv [p2, sf, r26]; vconv.fp32.bf16 cml0, x0
  ; OPTIMISTIC-NEXT:    vst.flush.512.conv.2d [p2, sf, r26, d0]; vconv.fp32.bf16 cmh0, x2
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]
  ; OPTIMISTIC-NEXT:    vst.flush.512.conv [p2, sf, r26]; vconv.fp32.bf16 cml0, x0
  ; OPTIMISTIC-NEXT:    vst.flush.512.conv.2d [p2, sf, r26, d0]; vconv.fp32.bf16 cmh0, x2
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    vst.push.576.conv.bfp16ebs8.fp32 dm0, [p2, sf, r26]
  ; OPTIMISTIC-NEXT:    vst.flush.512.conv [p2, sf, r26]
  ; OPTIMISTIC-NEXT:    vst.flush.512.conv.2d [p2, sf, r26, d0]
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    nop
  ; OPTIMISTIC-NEXT:    .p2align 4
  ; OPTIMISTIC-NEXT:  .LBB0_4:
  ; OPTIMISTIC-NEXT:    nopa ; ret lr
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 5
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 4
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 3
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 2
  ; OPTIMISTIC-NEXT:    nop // Delay Slot 1
  entry:
    ret void
  }
...
---
name:            convert_bf16_to_bfp16
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.3(0x30000000), %bb.1(0x50000000)
    liveins: $p0, $p1, $p2

    renamable $r0 = LDA_dms_lda_idx_imm $p2, 0 :: (dereferenceable load (s32) from %ir.params, align 64)
    JZ renamable $r0, %bb.3
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p1, $p2, $plfr0:0x0000000000400000, $r0

    $p3 = MOV_alu_mv_mv_mv_scl $p2
    $p2 = MOV_alu_mv_mv_mv_scl $p1
    renamable $m0 = MOV_PD_imm11_pseudo 12
    renamable $dj0 = MOV_PD_imm11_pseudo 0
    renamable $p3 = nuw PADD_mod_pseudo killed renamable $p3, killed renamable $m0
    $dj1 = MOV_alu_mv_mv_mv_scl $dj0
    renamable $m0, renamable $p3 = LDA_dms_lda_pstm_nrm_imm killed renamable $p3, -4 :: (dereferenceable load (s20) from %ir.params, align 4)
    renamable $m1, renamable $p3 = LDA_dms_lda_pstm_nrm_imm killed renamable $p3, -4 :: (dereferenceable load (s20) from %ir.params, align 4)
    renamable $dn0 = LDA_dms_lda_idx_imm killed renamable $p3, 0 :: (dereferenceable load (s20) from %ir.params, align 4)
    renamable $r24 = MOV_RLC_imm11_pseudo 0
    $dn1 = MOV_alu_mv_mv_mv_scl killed $dn0
    $dc0 = MOV_alu_mv_mv_mv_scl $dj0
    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.2
    $le = MOVXM <mcsymbol .L_LEnd0>
    $dc1 = MOV_alu_mv_mv_mv_scl $dj0
    renamable $sf = IMPLICIT_DEF
    $r26 = MOV_alu_mv_mv_mv_scl $r24

  bb.2 (align 16):
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $sf, $d0:0x0000000000200E00, $d1:0x0000000000200E00, $p2, $plfr0:0x0000000000484040, $r26

    $p0, $lf0, $r24 = VLDB_FILL_512 $p0, $lf0, $r24 :: (load unknown-size from %ir.in, align 1)
    $x0, $p0, $lf0, $r24 = VLDB_POP_512_normal_pop $p0, $lf0, $r24, implicit-def $srfifo_uf :: (load unknown-size from %ir.in, align 1)
    $x2, $p0, $lf0, $r24, $dc1 = VLDB_POP_512_2D $p0, $lf0, $r24, $d1, implicit-def $srfifo_uf :: (load unknown-size from %ir.in, align 1)
    renamable $cml0 = VCONV_fp32_bf16_mv_ups_xbf killed renamable $x0
    renamable $cmh0 = VCONV_fp32_bf16_mv_ups_xbf killed renamable $x2
    renamable $sf, renamable $p2, renamable $r26 = VST_PUSH_576_CONV_bfp16ebs8_fp32 killed renamable $sf, killed renamable $dm0, killed renamable $p2, killed renamable $r26, implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd :: (store unknown-size into %ir.out, align 4)
    renamable $sf, renamable $p2, renamable $r26 = VST_FLUSH_512_CONV_normal_flush killed renamable $sf, killed renamable $p2, killed renamable $r26, implicit-def $srfifo_of :: (store unknown-size into %ir.out, align 4)
    $sf, $p2, $r26, $dc0 = VST_FLUSH_512_CONV_2D killed $sf, killed $p2, killed $r26, $d0, implicit-def $srfifo_of :: (store unknown-size into %ir.out, align 4)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2

  bb.3 (align 16):
    RET implicit $lr
    DelayedSchedBarrier

...
