# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -O2 --run-pass=postmisched --aie-loop-min-tripcount=16 %s -o - | FileCheck %s

# Test to verify that a release lock instruction in the epilogue
# is not moved before store instructions from the loop.
# The release should maintain proper ordering with respect to stores.

# A lock instruction should wait for core stall cycles after Ld/St instruction.
---
name:            store_release
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: store_release
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0, $r18, $m0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $lc, implicit killed $p0, implicit $r0 {
  ; CHECK-NEXT:     $x0, $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed $p0, 64
  ; CHECK-NEXT:     $lc = ADD_NC_mv_add_ri $r0, -2
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   $ls = MOVXM %bb.2
  ; CHECK-NEXT:   $le = MOVXM <mcsymbol .L_LEnd0>
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   $x0 = VADD_16 killed $x0, $x0
  ; CHECK-NEXT:   $x0 = VADD_16 killed $x0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0, $m0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $p1, implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit killed $x0, implicit killed $p1 {
  ; CHECK-NEXT:     $p1 = VST_dmx_sts_x_pstm_nrm_imm $x0, killed $p1, 64
  ; CHECK-NEXT:     $x0 = VADD_16 killed $x0, $x0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $p0, $p1, $r18
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p1 = VST_dmx_sts_x_pstm_nrm_imm $x0, killed $p1, 64
  ; CHECK-NEXT:   $p1 = VST_dmx_sts_x_pstm_nrm_imm killed $x0, killed $p1, 64
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   REL_mLockId_imm 49, killed renamable $r18
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $r0, $r18, $m0

    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.2
    $le = MOVXM <mcsymbol .L_LEnd0>
    $x0, $p0 = VLD_x_pstm_nrm_imm_pseudo $p0, 64

  bb.1:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p0, $p1, $r0, $m0, $x0

    $x0 = VADD_16 $x0, $x0
    $p1 = VST_dmx_sts_x_pstm_nrm_imm $x0, $p1, 64
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2:
    liveins: $p0, $p1, $r18
    REL_mLockId_imm 49, renamable $r18
    RET implicit $lr
    DelayedSchedBarrier
...
