# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -verify-machineinstrs --mtriple=aie2p -O2 \
# RUN:   --start-before=postmisched %s \
# RUN:   -o - | FileCheck %s


# derived from GEMM_Bfp16_opt_0

--- |
  define dso_local void @gemm(ptr addrspace(5) noalias nocapture writeonly %d, ptr addrspace(6) noalias nocapture readonly %s, i32 noundef %n) local_unnamed_addr {
  ; CHECK-LABEL: gemm:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh4, [p7, #64]; vldb x2, [p6, #64]; nops ; nopx ; mov p5, p6; nopv
  ; CHECK-NEXT:    padda [p5], m4; vldb.3d x0, [p6], d0; nopx ; mov p3, p7; nops
  ; CHECK-NEXT:    vlda.3d.conv.fp32.bf16 cml4, [p7], d1; vldb x6, [p5, #0]
  ; CHECK-NEXT:    vldb x4, [p5, #64]
  ; CHECK-NEXT:    paddb [p3], m5
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vshuffle x8, x0, x2, r0
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex2, dm4; vshuffle x9, x0, x2, r1
  ; CHECK-NEXT:    vshuffle x0, x4, x6, r0
  ; CHECK-NEXT:    vshuffle x1, x4, x6, r1; vmul.f dm4, y4, y5, r2
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cml4, [p3, #0]; add.nc lc, r0, #-1; vmul.f dm4, y0, y5, r2
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh4, [p3, #64]; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    nopa ; nopb ; movxm le, #.L_LEnd0; nops
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh4, [p7, #64]; vldb x2, [p6, #64]; vconv.bfp16ebs8.fp32 ex3, dm4; nopx ; mov p5, p6; nopv
  ; CHECK-NEXT:    padda [p5], m4; vldb.3d x0, [p6], d0; nops ; nopx ; mov p3, p7; nopv
  ; CHECK-NEXT:    vlda.3d.conv.fp32.bf16 cml4, [p7], d1; vldb x6, [p5, #0]; nopx ; vconv.bfp16ebs8.fp32 ex5, dm4
  ; CHECK-NEXT:    vldb x4, [p5, #64]
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex7, dm4; paddb [p3], m5; vmac.f dm3, dm3, ex2, ex3, r3
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vmac.f dm2, dm2, ex2, ex5, r3
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vshuffle x8, x0, x2, r0; vmac.f dm1, dm1, ex7, ex3, r3
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex2, dm4; vshuffle x9, x0, x2, r1; vmac.f dm0, dm0, ex7, ex5, r3
  ; CHECK-NEXT:    vshuffle x0, x4, x6, r0
  ; CHECK-NEXT:    vshuffle x1, x4, x6, r1; vmul.f dm4, y4, y5, r2
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cml4, [p3, #0]; vmul.f dm4, y0, y5, r2
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh4, [p3, #64]
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  // %bb.2:
  ; CHECK-NEXT:    nopa ; nopb ; vconv.bfp16ebs8.fp32 ex3, dm4; nopxm ; nopv
  ; CHECK-NEXT:    nopx
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex5, dm4
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex7, dm4; vmac.f dm3, dm3, ex2, ex3, r3
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vmac.f dm2, dm2, ex2, ex5, r3
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vmac.f dm1, dm1, ex7, ex3, r3
  ; CHECK-NEXT:    vmac.f dm0, dm0, ex7, ex5, r3
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    %cmp5 = icmp sgt i32 %n, 0
    br i1 %cmp5, label %for.body.preheader, label %for.cond.cleanup

  for.body.preheader:                               ; preds = %entry
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %for.body

  for.body:                                         ; preds = %for.body.preheader, %for.body
    %d.addr.07 = phi ptr addrspace(5) [ %incdec.ptr, %for.body ], [ %d, %for.body.preheader ]
    %s.addr.06 = phi ptr addrspace(6) [ %incdec.ptr1, %for.body ], [ %s, %for.body.preheader ]
    %0 = load i32, ptr addrspace(6) %s.addr.06, align 4
    %add = add nsw i32 %0, 1
    store i32 %add, ptr addrspace(5) %d.addr.07, align 4
    %incdec.ptr = getelementptr inbounds i32, ptr addrspace(5) %d.addr.07, i20 1
    %incdec.ptr1 = getelementptr inbounds i32, ptr addrspace(6) %s.addr.06, i20 1
    %1 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %1, label %for.body, label %for.cond.cleanup, !llvm.loop !0

  for.cond.cleanup:                                 ; preds = %for.body, %entry
    ret void

  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1, !2}
  !1 = !{!"llvm.loop.mustprogress"}
  !2 = !{!"llvm.loop.itercount.range", i64 10}

...
---
name:            gemm
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.2
    liveins: $p0, $p1, $r0

    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.2
    $le = MOVXM <mcsymbol .L_LEnd0>

  bb.2.for.body (align 16):
    successors: %bb.2, %bb.3
    liveins: $dc0, $dc1, $dc2, $dc3, $dc4, $dc5, $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj7, $dm0:0x000000001800000C, $dm1:0x000000001800000C, $dm2:0x000000001800000C, $dm3:0x000000001800000C, $dn0, $dn1, $dn2, $dn4, $dn5, $m0, $m1, $m2, $m3, $m4, $m5, $p0, $p1, $p2, $p4, $p6, $p7, $r0, $r1, $r2, $r3, $r4, $r8, $y5:0x0000000000000033, $d0_3d:0x0003C00000200E00, $d1_3d:0x0003C00000200E00, $dn3

    $p5 = MOV_alu_mv_mv_mv_scl $p6
    $x2 = VLD_x_idx_imm_pseudo $p6, 64 :: (load (<16 x s32>))
    $x0, $p6, $dc0, $dc4 = VLD_3D_x_pseudo $p6, $d0_3d :: (load (<16 x s32>))
    $p3 = MOV_alu_mv_mv_mv_scl $p7
    $cmh4 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm $p7, 64 :: (load (<32 x s16>))
    $cml4, $p7, $dc1, $dc5 = VLDA_3D_CONV_fp32_bf16_dmx_lda_ups_bf $p7, $d1_3d :: (load (<32 x s16>))
    $p5 = PADD_mod_pseudo $p5, $m4
    $x6 = VLD_x_idx_imm_pseudo $p5, 0 :: (load (<16 x s32>))
    $x4 = VLD_x_idx_imm_pseudo $p5, 64 :: (load (<16 x s32>))
    $x8 = VSHUFFLE_vec_shuffle_x $x0, $x2, $r0
    $x9 = VSHUFFLE_vec_shuffle_x $x0, $x2, $r1
    $ex2 = VCONV_bfp16ebs8_fp32 $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y $y4, $y5, $r2, implicit-def $srfpflags, implicit $crfpmask
    $x0 = VSHUFFLE_vec_shuffle_x $x4, $x6, $r0
    $x1 = VSHUFFLE_vec_shuffle_x $x4, $x6, $r1
    $ex3 = VCONV_bfp16ebs8_fp32 $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y $y0, $y5, $r2, implicit-def $srfpflags, implicit $crfpmask
    $p3 = PADD_mod_pseudo $p3, $m5
    $ex5 = VCONV_bfp16ebs8_fp32 $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    $cml4 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm $p3, 0 :: (load (<32 x s16>))
    $cmh4 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm $p3, 64 :: (load (<32 x s16>))
    $ex7 = VCONV_bfp16ebs8_fp32 $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    $dm3 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX $dm3, $ex2, $ex3, $r3, implicit-def $srfpflags, implicit $crfpmask
    $dm2 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX $dm2, $ex2, $ex5, $r3, implicit-def $srfpflags, implicit $crfpmask
    $dm1 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX $dm1, $ex7, $ex3, $r3, implicit-def $srfpflags, implicit $crfpmask
    $dm0 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX $dm0, $ex7, $ex5, $r3, implicit-def $srfpflags, implicit $crfpmask

    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2

  bb.3 (align 16):
    RET implicit $lr
    DelayedSchedBarrier

...
