; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

; This test checks postpipelining for aie2p considering AA analysis
; related to virtual unroll, when we have pairs of memory operations
; in IR, in such a way that they represent a big memory load or store.
; In this case, all the memory operations should trace back to source
; intrinsic padd and to the respective phi node.
; This test (loop body) contains a load -> vadd -> store pattern, where both
; memory operations are using the same base pointer.

; RUN: llc -O2 -mtriple=aie2p %s -o - | FileCheck %s
define void @reduceMeanTemplated(ptr noalias %ifm, ptr addrspace(6) noalias %ofm) {
; CHECK-LABEL: reduceMeanTemplated:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova dj2, #128; nopb ; nopxm ; nops
; CHECK-NEXT:    mova m0, #0; movs p3, p1; mov dj1, dj2
; CHECK-NEXT:    movs p2, p1; mov dj0, m0
; CHECK-NEXT:    movs m1, m0; mov dj4, m0
; CHECK-NEXT:    movs dc0, m0; mov dn0, m0
; CHECK-NEXT:    movs dc4, m0; mov dn4, m0
; CHECK-NEXT:    vlda bmlh3, [p1, #64]; paddb.3d [p0], d0; movs dn1, m0; mov dc1, m0
; CHECK-NEXT:    vlda.2d bmll3, [p1], d1
; CHECK-NEXT:    vclr dm0
; CHECK-NEXT:    vlda bmlh3, [p1, #64]; paddb.3d [p0], d0
; CHECK-NEXT:    vlda.2d bmll3, [p1], d1; movx r0, #0
; CHECK-NEXT:    mova r1, #1; movxm ls, #.LBB0_1; vadd.f dm4, dm3, dm0, r0
; CHECK-NEXT:    vlda bmlh3, [p1, #64]; paddb.3d [p0], d0; movxm le, #.L_LEnd0
; CHECK-NEXT:    vlda.2d bmll3, [p1], d1; nopb ; nops ; nopx ; add.nc lc, r1, #-4; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; vadd.f dm4, dm3, dm0, r0
; CHECK-NEXT:    vlda bmlh3, [p1, #64]; paddb.3d [p0], d0; movs dc2, m0; nopx ; vbcst.32 x0, r0; nopv
; CHECK-NEXT:    vlda.2d bmll3, [p1], d1; nopb ; movs m2, m0; nopx ; mov dn2, m0; nopv
; CHECK-NEXT:    nopa ; nopb ; vst.2d bmll4, [p2], d2; nopxm ; vadd.f dm4, dm3, dm0, r0
; CHECK-NEXT:  .LBB0_1: // %for.body68
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda bmlh3, [p1, #64]; paddb.3d [p0], d0; vst x0, [p3, #0]; nopxm ; nopv
; CHECK-NEXT:    vlda.2d bmll3, [p1], d1; nopb ; movs p3, p2; nopxm ; nopv
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; vst.2d bmll4, [p2], d2; nopxm ; vadd.f dm4, dm3, dm0, r0
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup67
; CHECK-NEXT:    vst x0, [p3, #0]; nopx
; CHECK-NEXT:    movs p3, p2
; CHECK-NEXT:    vst.2d bmll4, [p2], d2; vadd.f dm4, dm3, dm0, r0
; CHECK-NEXT:    vst x0, [p3, #0]
; CHECK-NEXT:    movs p3, p2
; CHECK-NEXT:    vst.2d bmll4, [p2], d2
; CHECK-NEXT:    vst x0, [p3, #0]
; CHECK-NEXT:    movs p3, p2
; CHECK-NEXT:    vst.2d bmll4, [p2], d2
; CHECK-NEXT:    vst x0, [p3, #0]
; CHECK-NEXT:    movs p3, p2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  call void @llvm.set.loop.iterations.i32(i32 1)
  br label %for.body68

for.cond.cleanup67:                               ; preds = %for.body68
  ret void

for.body68:                                       ; preds = %for.body68, %entry
  %p_in_group.sroa.0.0.in103 = phi ptr [ %ifm, %entry ], [ %16, %for.body68 ]
  %p_out_group.sroa.0.1102 = phi ptr addrspace(6) [ %ofm, %entry ], [ %8, %for.body68 ]
  %p_out_save_group.sroa.0.1101 = phi ptr addrspace(6) [ %ofm, %entry ], [ %28, %for.body68 ]
  %count0_group.sroa.0.0100 = phi i32 [ 0, %entry ], [ %6, %for.body68 ]
  %count1_group.sroa.0.099 = phi i32 [ 0, %entry ], [ %26, %for.body68 ]
  %i_ptr_addr_count1.098 = phi i32 [ 0, %entry ], [ %13, %for.body68 ]
  %i_ptr_addr_count2.097 = phi i32 [ 0, %entry ], [ %15, %for.body68 ]
  %0 = load <16 x float>, ptr addrspace(6) %p_out_group.sroa.0.1102, align 64
  %arrayidx.i.i.i.i.i.i.i.i62 = getelementptr i8, ptr addrspace(6) %p_out_group.sroa.0.1102, i20 64
  %1 = load <16 x float>, ptr addrspace(6) %arrayidx.i.i.i.i.i.i.i.i62, align 64
  %2 = addrspacecast ptr addrspace(6) %p_out_group.sroa.0.1102 to ptr
  %3 = trunc i32 %count0_group.sroa.0.0100 to i20
  %4 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr %2, i20 0, i20 128, i20 0, i20 %3)
  %5 = extractvalue { ptr, i20 } %4, 1
  %6 = zext i20 %5 to i32
  %7 = extractvalue { ptr, i20 } %4, 0
  %8 = addrspacecast ptr %7 to ptr addrspace(6)
  %9 = trunc i32 %i_ptr_addr_count1.098 to i20
  %10 = trunc i32 %i_ptr_addr_count2.097 to i20
  %11 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr %p_in_group.sroa.0.0.in103, i20 0, i20 0, i20 0, i20 0, i20 %9, i20 0, i20 %10)
  %12 = extractvalue { ptr, i20, i20 } %11, 1
  %13 = zext i20 %12 to i32
  %14 = extractvalue { ptr, i20, i20 } %11, 2
  %15 = zext i20 %14 to i32
  %16 = extractvalue { ptr, i20, i20 } %11, 0
  %shuffle.i.uncasted.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x float> %0, <16 x float> %1, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %17 = bitcast <32 x float> %shuffle.i.uncasted.i.i.i.i.i.i.i.i.i.i.i to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %17, <16 x i64> zeroinitializer, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %18 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %19 = tail call <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %18, <64 x float> zeroinitializer, i32 0)
  %20 = bitcast <64 x float> %19 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %20, <32 x i64> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %21 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i to <32 x i32>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i32> %21, <32 x i32> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <16 x i32> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i, ptr addrspace(6) %p_out_save_group.sroa.0.1101, align 64
  store <16 x i32> zeroinitializer, ptr addrspace(6) %p_out_save_group.sroa.0.1101, align 64
  %22 = addrspacecast ptr addrspace(6) %p_out_save_group.sroa.0.1101 to ptr
  %23 = trunc i32 %count1_group.sroa.0.099 to i20
  %24 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr %22, i20 0, i20 128, i20 0, i20 %23)
  %25 = extractvalue { ptr, i20 } %24, 1
  %26 = zext i20 %25 to i32
  %27 = extractvalue { ptr, i20 } %24, 0
  %28 = addrspacecast ptr %27 to ptr addrspace(6)
  %29 = call i1 @llvm.loop.decrement.i32(i32 0)
  br i1 %29, label %for.body68, label %for.cond.cleanup67, !llvm.loop !0
}

; Function Attrs: nounwind memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float>, <64 x float>, i32) #1

; Function Attrs: nounwind memory(none)
declare { ptr, i20 } @llvm.aie2p.add.2d(ptr, i20, i20, i20, i20) #0

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare void @llvm.set.loop.iterations.i32(i32) #2

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare i1 @llvm.loop.decrement.i32(i32) #2

; uselistorder directives
uselistorder ptr @llvm.aie2p.add.2d, { 1, 0 }

attributes #0 = { nounwind memory(none) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #2 = { nocallback noduplicate nofree nosync nounwind willreturn }

!0 = distinct !{!0, !1, !2, !3}
!1 = !{!"llvm.loop.mustprogress"}
!2 = !{!"llvm.loop.itercount.range", i64 8}
!3 = !{!"llvm.loop.pipeline.disable", i1 true}
