# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -verify-machineinstrs --mtriple=aie2p %s \
# RUN:     --start-before=postmisched \
# RUN:     -o - | FileCheck %s

# This is a simple example of a speculative stage. The first stage gets a load,
# which is side-effect free. It can run in NS=4 * II=3
# We have two identical copies, one with MinIterCount=4, which should
# take the normal 4 stage pipeline and one with MinIterCount=3,
# where the peeling modulo extractor should kick in.

--- |
  define dso_local void @vmax_fourstage(ptr noalias nocapture readonly %a, ptr noalias nocapture writeonly %c, i32 noundef %factor, i32 noundef %N) local_unnamed_addr {
  ; CHECK-LABEL: vmax_fourstage:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    vlda x1, [p0, #64]; nopb ; nopxm ; nops
  ; CHECK-NEXT:    vlda x2, [p0], #128
  ; CHECK-NEXT:    add.nc lc, r1, #-3
  ; CHECK-NEXT:    vlda x1, [p0, #64]; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    vlda x2, [p0], #128; nopb ; nops ; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x1, [p0, #64]; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x2, [p0], #128; nopb ; nops ; nopx ; vbcst.32 x0, r0; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vshuffle x3, x1, x2, r10; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda x1, [p0, #64]; nopb ; nops ; nopx ; vmax_lt.32 x0, r16, x0, x3, vaddsign1; nopv
  ; CHECK-NEXT:    vlda x2, [p0], #128; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vshuffle x3, x1, x2, r10; nopv
  ; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
  ; CHECK-NEXT:    nops ; vmax_lt.32 x0, r16, x0, x3, vaddsign1
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    ret lr; vshuffle x3, x1, x2, r10
  ; CHECK-NEXT:    vmax_lt.32 x0, r16, x0, x3, vaddsign1 // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    vshuffle x3, x1, x2, r10 // Delay Slot 3
  ; CHECK-NEXT:    vmax_lt.32 x0, r16, x0, x3, vaddsign1 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    call void @llvm.set.loop.iterations.i32(i32 16)
    br label %for.body

  for.body:                                         ; preds = %for.body, %entry
    %ptr = phi ptr [ %a, %entry ], [ %add.ptr, %for.body ]
    %add.ptr = getelementptr inbounds i8, ptr %ptr, i20 64
    %6 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %6, label %for.body, label %for.cond.cleanup, !llvm.loop !12

  for.cond.cleanup:                                 ; preds = %for.body
    ret void
  }

  define dso_local void @vmax_threestage(ptr noalias nocapture readonly %a, ptr noalias nocapture writeonly %c, i32 noundef %factor, i32 noundef %N) local_unnamed_addr {
  ; CHECK-LABEL: vmax_threestage:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    vlda x1, [p0, #64]; add.nc lc, r1, #-2
  ; CHECK-NEXT:    vlda x2, [p0], #128; movxm ls, #.LBB1_1
  ; CHECK-NEXT:    nopa ; nopb ; nops ; movxm le, #.L_LEnd1; nopv
  ; CHECK-NEXT:    vlda x1, [p0, #64]; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x2, [p0], #128; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x1, [p0, #64]; nopb ; nops ; nopx ; vbcst.32 x0, r0; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB1_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda x2, [p0], #128; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vshuffle x3, x1, x2, r10; nopv
  ; CHECK-NEXT:  .L_LEnd1:
  ; CHECK-NEXT:    vlda x1, [p0, #64]; nopb ; nops ; nopx ; vmax_lt.32 x0, r16, x0, x3, vaddsign1; nopv
  ; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
  ; CHECK-NEXT:    nopa ; nopxm
  ; CHECK-NEXT:    ret lr; vshuffle x3, x1, x2, r10
  ; CHECK-NEXT:    vmax_lt.32 x0, r16, x0, x3, vaddsign1 // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    vshuffle x3, x1, x2, r10 // Delay Slot 3
  ; CHECK-NEXT:    vmax_lt.32 x0, r16, x0, x3, vaddsign1 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    call void @llvm.set.loop.iterations.i32(i32 16)
    br label %for.body

  for.body:                                         ; preds = %for.body, %entry
    %ptr = phi ptr [ %a, %entry ], [ %add.ptr, %for.body ]
    %add.ptr = getelementptr inbounds i8, ptr %ptr, i20 64
    %6 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %6, label %for.body, label %for.cond.cleanup, !llvm.loop !14

  for.cond.cleanup:                                 ; preds = %for.body
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !12 = distinct !{!12, !13}
  !13 = !{!"llvm.loop.itercount.range", i64 4}
  !14 = distinct !{!14, !15}
  !15 = !{!"llvm.loop.itercount.range", i64 3}

...
---
name:            vmax_fourstage
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $r0, $r1

    $x0 = VBCST_32 $r0
    $lc = ADD_NC_mv_add_ri $r1, 0
    $ls = MOVXM %bb.1
    $le = MOVXM <mcsymbol .L_LEnd0>

  bb.1.for.body (align 16):
    successors: %bb.1, %bb.2
    liveins: $p0, $x0, $r10

    $x1 = VLDA_dmx_lda_x_idx_imm $p0, 64 :: (load (<16 x s32>) from %ir.ptr)
    $x2, $p0 = VLDA_dmx_lda_x_pstm_nrm_imm $p0, 128 :: (load (<16 x s32>) from %ir.ptr)
    $x3 = VSHUFFLE_vec_shuffle_x $x1, $x2, $r10
    $x0, $r16 = VMAX_LT_32_vaddSign1 $x0, $x3, implicit $vaddsign1
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2.for.cond.cleanup:
    RET implicit $lr
    DelayedSchedBarrier
...
---
name:            vmax_threestage
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $r0, $r1

    $x0 = VBCST_32 $r0
    $lc = ADD_NC_mv_add_ri $r1, 0
    $ls = MOVXM %bb.1
    $le = MOVXM <mcsymbol .L_LEnd1>

  bb.1.for.body (align 16):
    successors: %bb.1, %bb.2
    liveins: $p0, $x0, $r10

    $x1 = VLDA_dmx_lda_x_idx_imm $p0, 64 :: (load (<16 x s32>) from %ir.ptr)
    $x2, $p0 = VLDA_dmx_lda_x_pstm_nrm_imm $p0, 128 :: (load (<16 x s32>) from %ir.ptr)
    $x3 = VSHUFFLE_vec_shuffle_x $x1, $x2, $r10
    $x0, $r16 = VMAX_LT_32_vaddSign1 $x0, $x3, implicit $vaddsign1
    PseudoLoopEnd <mcsymbol .L_LEnd1>, %bb.1, implicit $ls, implicit $le

  bb.2.for.cond.cleanup:
    RET implicit $lr
    DelayedSchedBarrier
...
