# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc --mtriple=aie2p  %s --start-before=postmisched -o - | FileCheck %s

--- |

  @a = dso_local local_unnamed_addr global [6 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5, i32 6], align 4
  @b = dso_local local_unnamed_addr global [7 x i32] [i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 -12], align 4

  ; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
  define dso_local noundef i32 @_Z3sumiPi(i32 noundef %n, ptr nocapture readonly %vector) local_unnamed_addr #0 {
  ; CHECK-LABEL: _Z3sumiPi:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    mova r2, #0; nopb ; nopxm
  ; CHECK-NEXT:    ge r0, r2, r1
  ; CHECK-NEXT:    jnz r0, #.LBB0_4
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  ; CHECK-NEXT:  // %bb.1:
  ; CHECK-NEXT:    mova r0, #0; nopb ; nops ; movx r3, #2; nopm ; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_2: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; nopb ; nops ; lshl r4, r2, r3; nopm ; nopv
  ; CHECK-NEXT:    mov dj0, r4
  ; CHECK-NEXT:    lda r4, [p0, dj0]; add r2, r2, #1
  ; CHECK-NEXT:    eq r5, r1, r2
  ; CHECK-NEXT:    jz r5, #.LBB0_2
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    add r0, r4, r0 // Delay Slot 1
  ; CHECK-NEXT:  // %bb.3: // %for.cond.cleanup
  ; CHECK-NEXT:    nopa ; ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_4:
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    mova r0, #0 // Delay Slot 1
  entry:
    %cmp4 = icmp sgt i32 %n, 0
    br i1 %cmp4, label %for.body.preheader, label %for.cond.cleanup

  for.body.preheader:                               ; preds = %entry
    br label %for.body

  for.cond.cleanup:                                 ; preds = %for.body, %entry
    %sum.0.lcssa = phi i32 [ 0, %entry ], [ %add, %for.body ]
    ret i32 %sum.0.lcssa

  for.body:                                         ; preds = %for.body.preheader, %for.body
    %i.06 = phi i32 [ %inc, %for.body ], [ 0, %for.body.preheader ]
    %sum.05 = phi i32 [ %add, %for.body ], [ 0, %for.body.preheader ]
    %0 = trunc i32 %i.06 to i20
    %arrayidx = getelementptr inbounds i32, ptr %vector, i20 %0
    %1 = load i32, ptr %arrayidx, align 4, !tbaa !2
    %add = add nsw i32 %1, %sum.05
    %inc = add nuw nsw i32 %i.06, 1
    %exitcond.not = icmp eq i32 %n, %inc
    br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !6
  }

  ; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: none, inaccessiblemem: none)
  define dso_local noundef i32 @main() local_unnamed_addr #1 {
  ; CHECK-LABEL: main:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    nopa ; nopb ; nops ; movxm p1, ##a; nopv
  ; CHECK-NEXT:    movxm p0, ##b
  ; CHECK-NEXT:    movxm ls, #.LBB1_1
  ; CHECK-NEXT:    movxm le, #.L_LEnd1
  ; CHECK-NEXT:    mova r4, #0; movx r3, #2
  ; CHECK-NEXT:    lshl r5, r4, r3
  ; CHECK-NEXT:    mov dj0, r5
  ; CHECK-NEXT:    lda r6, [p1, dj0]; add r4, r4, #1; mov r1, #6
  ; CHECK-NEXT:    lshl r5, r4, r3; add.nc lc, r1, #-3
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; mov dj0, r5; nopv
  ; CHECK-NEXT:    lda r6, [p1, dj0]; nopb ; nops ; add r4, r4, #1; nopm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; lshl r5, r4, r3; nopm ; nopv
  ; CHECK-NEXT:    mova r0, #0; nopb ; nops ; movx r2, #7; mov dj0, r5; nopv
  ; CHECK-NEXT:    lda r6, [p1, dj0]; nopb ; nops ; add r4, r4, #1; mov r1, #0; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB1_1: // %for.body.i
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; nopb ; nops ; lshl r5, r4, r3; nopm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; add r1, r6, r1; mov dj0, r5; nopv
  ; CHECK-NEXT:  .L_LEnd1:
  ; CHECK-NEXT:    lda r6, [p1, dj0]; nopb ; nops ; add r4, r4, #1; nopm ; nopv
  ; CHECK-NEXT:  // %bb.2: // %for.body.i2.preheader
  ; CHECK-NEXT:    mova r2, #2; nopb ; nops ; movx r3, #0; add.nc lc, r2, #-3; nopv
  ; CHECK-NEXT:    add r1, r6, r1
  ; CHECK-NEXT:    movxm ls, #.LBB1_3
  ; CHECK-NEXT:    movxm le, #.L_LEnd0
  ; CHECK-NEXT:    nopa ; nopb ; nops ; add r1, r6, r1; nopm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; add r1, r6, r1; nopm ; nopv
  ; CHECK-NEXT:    nopa ; lshl r4, r0, r2; nopm
  ; CHECK-NEXT:    mov dj0, r4
  ; CHECK-NEXT:    lda r5, [p0, dj0]; add r0, r0, #1
  ; CHECK-NEXT:    lshl r4, r0, r2
  ; CHECK-NEXT:    mov dj0, r4
  ; CHECK-NEXT:    lda r5, [p0, dj0]; add r0, r0, #1
  ; CHECK-NEXT:    lshl r4, r0, r2
  ; CHECK-NEXT:    mov dj0, r4
  ; CHECK-NEXT:    lda r5, [p0, dj0]; add r0, r0, #1
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB1_3: // %for.body.i2
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; nopb ; nops ; lshl r4, r0, r2; nopm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; add r3, r5, r3; mov dj0, r4; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    lda r5, [p0, dj0]; nopb ; nops ; add r0, r0, #1; nopm ; nopv
  ; CHECK-NEXT:  // %bb.4: // %_Z3sumiPi.exit9
  ; CHECK-NEXT:    nopa ; nopxm
  ; CHECK-NEXT:    add r3, r5, r3
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    add r3, r5, r3
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    add r3, r5, r3
  ; CHECK-NEXT:    add r0, r3, r1
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    call void @llvm.set.loop.iterations.i32(i32 6)
    br label %for.body.i

  for.body.i:                                       ; preds = %for.body.i, %entry
    %i.06.i = phi i32 [ %inc.i, %for.body.i ], [ 0, %entry ]
    %sum.05.i = phi i32 [ %add.i, %for.body.i ], [ 0, %entry ]
    %0 = trunc i32 %i.06.i to i20
    %arrayidx.i = getelementptr inbounds i32, ptr @a, i20 %0
    %1 = load i32, ptr %arrayidx.i, align 4, !tbaa !2
    %add.i = add nsw i32 %1, %sum.05.i
    %inc.i = add nuw nsw i32 %i.06.i, 1
    %2 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %2, label %for.body.i, label %for.body.i2.preheader, !llvm.loop !6

  for.body.i2.preheader:                            ; preds = %for.body.i
    call void @llvm.set.loop.iterations.i32(i32 7)
    br label %for.body.i2

  for.body.i2:                                      ; preds = %for.body.i2.preheader, %for.body.i2
    %i.06.i3 = phi i32 [ %inc.i7, %for.body.i2 ], [ 0, %for.body.i2.preheader ]
    %sum.05.i4 = phi i32 [ %add.i6, %for.body.i2 ], [ 0, %for.body.i2.preheader ]
    %3 = trunc i32 %i.06.i3 to i20
    %arrayidx.i5 = getelementptr inbounds i32, ptr @b, i20 %3
    %4 = load i32, ptr %arrayidx.i5, align 4, !tbaa !2
    %add.i6 = add nsw i32 %4, %sum.05.i4
    %inc.i7 = add nuw nsw i32 %i.06.i3, 1
    %5 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %5, label %for.body.i2, label %_Z3sumiPi.exit9, !llvm.loop !6

  _Z3sumiPi.exit9:                                  ; preds = %for.body.i2
    %add = add nsw i32 %add.i6, %add.i
    ret i32 %add
  }

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare void @llvm.set.loop.iterations.i32(i32) #2

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare i1 @llvm.loop.decrement.i32(i32) #2

  attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
  attributes #1 = { mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: none, inaccessiblemem: none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
  attributes #2 = { nocallback noduplicate nofree nosync nounwind willreturn }

  !llvm.module.flags = !{!0}
  !llvm.ident = !{!1}

  !0 = !{i32 1, !"wchar_size", i32 4}
  !1 = !{!"clang version 19.0.0git (git@gitenterprise.xilinx.com:XRLabs/llvm-aie.git 8a43b06df4a3906c547c42a23ccf7edd48c72fc7)"}
  !2 = !{!3, !3, i64 0}
  !3 = !{!"int", !4, i64 0}
  !4 = !{!"omnipotent char", !5, i64 0}
  !5 = !{!"Simple C++ TBAA"}
  !6 = distinct !{!6, !7, !8}
  !7 = !{!"llvm.loop.mustprogress"}
  !8 = !{!"llvm.loop.unroll.disable"}

...
---
name:            _Z3sumiPi
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: true
registers:       []
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x50000000), %bb.4(0x30000000)
    liveins: $p0, $r1

    renamable $r2 = MOV_RLC_imm11_pseudo 0
    renamable $r0 = GE renamable $r2, renamable $r1
    JNZ killed renamable $r0, %bb.4
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p0, $r1, $r2

    renamable $r3 = MOV_RLC_imm11_pseudo 2
    renamable $r0 = MOV_RLC_imm11_pseudo 0

  bb.2.for.body (align 16):
    successors: %bb.3(0x04000000), %bb.2(0x7c000000)
    liveins: $p0, $r0, $r1, $r2, $r3

    renamable $r4 = LSHL renamable $r2, renamable $r3
    $dj0 = MOV_scalar_pseudo killed $r4
    renamable $r4 = LDA_dms_lda_idx renamable $p0, killed renamable $dj0 :: (load (s32) from %ir.arrayidx, !tbaa !2)
    renamable $r2 = nuw nsw ADD_add_r_ri killed renamable $r2, 1, implicit-def dead $srcarry
    renamable $r5 = EQ renamable $r1, renamable $r2
    renamable $r0 = nsw ADD_alu_r_rr killed renamable $r4, killed renamable $r0, implicit-def dead $srcarry
    JZ killed renamable $r5, %bb.2
    DelayedSchedBarrier

  bb.3.for.cond.cleanup:
    successors:
    liveins: $r0

    RET implicit $lr
    DelayedSchedBarrier implicit $r0

  bb.4 (align 16):
    renamable $r0 = MOV_RLC_imm11_pseudo 0
    RET implicit $lr
    DelayedSchedBarrier implicit $r0

...
---
name:            main
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: true
registers:       []
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)

    renamable $r1 = MOV_RLC_imm11_pseudo 6
    renamable $p1 = MOVXM target-flags(aie2p-global) @a
    renamable $r2 = MOV_RLC_imm11_pseudo 7
    renamable $p0 = MOVXM target-flags(aie2p-global) @b
    renamable $r0 = MOV_RLC_imm11_pseudo 0
    $lc = ADD_NC_mv_add_ri $r1, 0
    $ls = MOVXM %bb.1
    $le = MOVXM <mcsymbol .L_LEnd1>
    renamable $r3 = MOV_RLC_imm11_pseudo 2
    renamable $r4 = MOV_RLC_imm11_pseudo 0
    renamable $r1 = MOV_RLC_imm11_pseudo 0

  bb.1.for.body.i (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p0, $p1, $r0, $r1, $r2, $r3, $r4

    renamable $r5 = LSHL renamable $r4, renamable $r3
    $dj0 = MOV_scalar_pseudo killed $r5
    renamable $r6 = LDA_dms_lda_idx renamable $p1, killed renamable $dj0 :: (load (s32) from %ir.arrayidx.i, !tbaa !2)
    renamable $r1 = nsw ADD_alu_r_rr killed renamable $r6, killed renamable $r1, implicit-def dead $srcarry
    renamable $r4 = nuw nsw ADD_add_r_ri killed renamable $r4, 1, implicit-def dead $srcarry
    PseudoLoopEnd <mcsymbol .L_LEnd1>, %bb.1

  bb.2.for.body.i2.preheader:
    successors: %bb.3(0x80000000)
    liveins: $p0, $r0, $r1, $r2

    $lc = ADD_NC_mv_add_ri $r2, 0
    $ls = MOVXM %bb.3
    $le = MOVXM <mcsymbol .L_LEnd0>
    renamable $r2 = MOV_RLC_imm11_pseudo 2
    renamable $r3 = MOV_RLC_imm11_pseudo 0

  bb.3.for.body.i2 (align 16):
    successors: %bb.3(0x7c000000), %bb.4(0x04000000)
    liveins: $p0, $r0, $r1, $r2, $r3

    renamable $r4 = LSHL renamable $r0, renamable $r2
    $dj0 = MOV_scalar_pseudo killed $r4
    renamable $r5 = LDA_dms_lda_idx renamable $p0, killed renamable $dj0 :: (load (s32) from %ir.arrayidx.i5, !tbaa !2)
    renamable $r3 = nsw ADD_alu_r_rr killed renamable $r5, killed renamable $r3, implicit-def dead $srcarry
    renamable $r0 = nuw nsw ADD_add_r_ri killed renamable $r0, 1, implicit-def dead $srcarry
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3

  bb.4._Z3sumiPi.exit9:
    liveins: $r1, $r3

    renamable $r0 = nsw ADD_alu_r_rr killed renamable $r3, killed renamable $r1, implicit-def dead $srcarry
    RET implicit $lr
    DelayedSchedBarrier implicit $r0

...
