# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates


# This is a case that fits in II=2, but where the solver fails to find the
# schedule if it doesn't take the conflict between XM and X and M into account.
# We deliberately select one fixed heuristic that doesn't find it either
# in order to not short-circuit the solver -- perhaps we should have a
# --runsolver-first option.
# Please ignore the uselessness of the code -- I know it is mainly
# loop invariant, but that is not the subject of this test.

# REQUIRES: enable_z3_solver
# RUN: llc -verify-machineinstrs --mtriple=aie2p -O2 %s \
# RUN:   --start-before=postmisched \
# RUN:   --aie-postpipeliner-heuristic-runs=1 \
# RUN:   --aie-postpipeliner-heuristic=3 \
# RUN:   -o - | FileCheck %s

--- |
  define dso_local void @movxm(ptr addrspace(5) noalias nocapture writeonly %d, ptr addrspace(6) noalias nocapture readonly %s, i32 noundef %n) local_unnamed_addr {
  ; CHECK-LABEL: movxm:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    add.nc lc, r0, #-1
  ; CHECK-NEXT:    movxm ls, #.LBB0_1
  ; CHECK-NEXT:    movxm le, #.L_LEnd0
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; mov r2, #4; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; movxm r1, #1234567; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; nopb ; nops ; or r3, r1, r2; mov r2, #4; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; st r3, [p0, #0]; movxm r1, #1234567; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  // %bb.2:
  ; CHECK-NEXT:    nopa ; nopb ; or r3, r1, r2; nopm ; nops
  ; CHECK-NEXT:    st r3, [p0, #0]
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    %cmp5 = icmp sgt i32 %n, 0
    br i1 %cmp5, label %for.body.preheader, label %for.cond.cleanup

  for.body.preheader:                               ; preds = %entry
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %for.body

  for.body:                                         ; preds = %for.body.preheader, %for.body
    %d.addr.07 = phi ptr addrspace(5) [ %incdec.ptr, %for.body ], [ %d, %for.body.preheader ]
    %s.addr.06 = phi ptr addrspace(6) [ %incdec.ptr1, %for.body ], [ %s, %for.body.preheader ]
    %0 = load i32, ptr addrspace(6) %s.addr.06, align 4
    %add = add nsw i32 %0, 1
    store i32 %add, ptr addrspace(5) %d.addr.07, align 4
    %incdec.ptr = getelementptr inbounds i32, ptr addrspace(5) %d.addr.07, i20 1
    %incdec.ptr1 = getelementptr inbounds i32, ptr addrspace(6) %s.addr.06, i20 1
    %1 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %1, label %for.body, label %for.cond.cleanup, !llvm.loop !0

  for.cond.cleanup:                                 ; preds = %for.body, %entry
    ret void

  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1, !2, !3}
  !1 = !{!"llvm.loop.mustprogress"}
  !2 = !{!"llvm.loop.itercount.range", i64 8}
  !3 = !{!"llvm.loop.pipeline.initiationinterval", i64 2}
...
---
name:            movxm
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.2
    liveins: $p0, $r0

    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.2
    $le = MOVXM <mcsymbol .L_LEnd0>

  bb.2.for.body (align 16):
    successors: %bb.2, %bb.3
    liveins: $p0
    $r1 = MOVXM 1234567
    $r2 = MOV_alu_mv_mv_mv_cg 4
    $r3 = OR $r1, $r2
    ST_dms_sts_idx_imm $r3, $p0, 0
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2

  bb.3 (align 16):
    RET implicit $lr
    DelayedSchedBarrier

...
