; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

; RUN: opt -S -passes=sroa < %s | FileCheck %s

; Test that SROA preserves pointer types instead of converting to [3 x i8]
; when the alloca has mixed uses that would normally trigger the fallback.
; AIE2P uses 20-bit pointers (3 bytes), and 24-bit integers are not legal.

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"

; Test: This demonstrates the bug where SROA converts pointer alloca to [3 x i8]
; when there are mixed pointer types (ptr vs ptr addrspace(5)).
; WITHOUT the SROA fix: Creates alloca [3 x i8] (BUG - type mismatch prevents promotion)
; WITH the SROA fix: Should preserve pointer type and allow promotion
define <64 x i8> @test_popx_with_mixed_types(ptr addrspace(5) %input) {
; CHECK-LABEL: @test_popx_with_mixed_types(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[P_IN_SROA_0:%.*]] = alloca [3 x i8], align 4
; CHECK-NEXT:    store ptr addrspace(5) [[INPUT:%.*]], ptr [[P_IN_SROA_0]], align 4
; CHECK-NEXT:    [[P_IN_SROA_0_0_P_IN_SROA_0_0_PTR1:%.*]] = load ptr addrspace(5), ptr [[P_IN_SROA_0]], align 4
; CHECK-NEXT:    [[RESULT:%.*]] = call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p5(ptr addrspace(5) [[P_IN_SROA_0_0_P_IN_SROA_0_0_PTR1]], <32 x i32> zeroinitializer, i32 0, <16 x i32> zeroinitializer, i32 63)
; CHECK-NEXT:    [[UPDATED_PTR_AS0:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[RESULT]], 1
; CHECK-NEXT:    [[UPDATED_PTR_AS5:%.*]] = addrspacecast ptr [[UPDATED_PTR_AS0]] to ptr addrspace(5)
; CHECK-NEXT:    store ptr addrspace(5) [[UPDATED_PTR_AS5]], ptr [[P_IN_SROA_0]], align 4
; CHECK-NEXT:    [[P_IN_SROA_0_0_P_IN_SROA_0_0_PTR2:%.*]] = load ptr, ptr [[P_IN_SROA_0]], align 4
; CHECK-NEXT:    [[DATA:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[RESULT]], 0
; CHECK-NEXT:    ret <64 x i8> [[DATA]]
;
entry:
  %p_in = alloca ptr addrspace(5), align 4
  store ptr addrspace(5) %input, ptr %p_in, align 4

  ; Load as ptr addrspace(5)
  %ptr1 = load ptr addrspace(5), ptr %p_in, align 4

  ; Call popx intrinsic
  %result = call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p5(ptr addrspace(5) %ptr1, <32 x i32> zeroinitializer, i32 0, <16 x i32> zeroinitializer, i32 63)

  ; Extract updated pointer (in default address space)
  %updated_ptr_as0 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %result, 1

  ; Cast to address space 5
  %updated_ptr_as5 = addrspacecast ptr %updated_ptr_as0 to ptr addrspace(5)

  ; Store back (different type than load!)
  store ptr addrspace(5) %updated_ptr_as5, ptr %p_in, align 4

  ; Load again with potentially different type
  %ptr2 = load ptr, ptr %p_in, align 4

  ; Extract data
  %data = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %result, 0
  ret <64 x i8> %data
}

declare { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p5(ptr addrspace(5), <32 x i32>, i32, <16 x i32>, i32)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20)
