# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-regclass-constrainer %s -verify-machineinstrs -o - | FileCheck %s

# This test verifies how classes containing reserved registers are constrained before register allocation

---
name: constrain_ercr
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $r0
    ; CHECK-LABEL: name: constrain_ercr
    ; CHECK: liveins: $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $crsat
    ; CHECK-NEXT: $crsat = COPY [[COPY1]]
    ; CHECK-NEXT: [[VPACK_S4_S8_:%[0-9]+]]:vec256 = VPACK_S4_S8 [[COPY]], implicit $crsat
    ; CHECK-NEXT: $crsat = COPY [[COPY2]]
    ; CHECK-NEXT: $wl0 = COPY [[VPACK_S4_S8_]]
    %0:vec512 = COPY $x0
    %1:er = COPY $r0
    %2:ercr = COPY $crsat
    $crsat = COPY %1
    %3:vec256 = VPACK_S4_S8 %0, implicit $crsat
    $crsat = COPY %2
    $wl0 = COPY %3
...

---
name: constrain_erlc
tracksRegLiveness: true
body:             |
  bb.1:
    ; CHECK-LABEL: name: constrain_erlc
    ; CHECK: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 100
    ; CHECK-NEXT: $r0 = COPY [[MOV_RLC_imm10_pseudo]]
    %0:erlc = MOV_RLC_imm10_pseudo 100
    $r0 = COPY %0
...

---
name: constrain_mldacg
tracksRegLiveness: true
body:             |
  bb.1:
    ; CHECK-LABEL: name: constrain_mldacg
    ; CHECK: [[MOVA_lda_cg:%[0-9]+]]:msclms = MOVA_lda_cg 100
    ; CHECK-NEXT: $r0 = COPY [[MOVA_lda_cg]]
    %0:mldacg = MOVA_lda_cg 100
    $r0 = COPY %0
...

---
name: constrain_mldacg_with_fp_taken
tracksRegLiveness: true
frameInfo:
  isFrameAddressTaken: true
body:             |
  bb.1:
    ; CHECK-LABEL: name: constrain_mldacg_with_fp_taken
    ; CHECK: [[MOVA_lda_cg:%[0-9]+]]:msclms_fp_taken = MOVA_lda_cg 100
    ; CHECK-NEXT: $r0 = COPY [[MOVA_lda_cg]]
    %0:mldacg = MOVA_lda_cg 100
    $r0 = COPY %0
...

---
name: constrain_mldascl
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: constrain_mldascl
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:msclms = LDA_dms_lda_idx_imm $p0, 0
    ; CHECK-NEXT: $r0 = COPY [[LDA_dms_lda_idx_imm]]
    %0:mldascl = LDA_dms_lda_idx_imm $p0, 0
    $r0 = COPY %0
...

---
name: constrain_mldascl_with_fp_taken
tracksRegLiveness: true
frameInfo:
  isFrameAddressTaken: true
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: constrain_mldascl_with_fp_taken
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:msclms_fp_taken = LDA_dms_lda_idx_imm $p0, 0
    ; CHECK-NEXT: $r0 = COPY [[LDA_dms_lda_idx_imm]]
    %0:mldascl = LDA_dms_lda_idx_imm $p0, 0
    $r0 = COPY %0
...

---
name: constrain_mmvscldst
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0
    ; CHECK-LABEL: name: constrain_mmvscldst
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_mv_scl:%[0-9]+]]:msclms = MOV_mv_scl $r0
    ; CHECK-NEXT: $r0 = COPY [[MOV_mv_scl]]
    %0:mmvscldst = MOV_mv_scl $r0
    $r0 = COPY %0
...


