# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

# AIE2-specific tests for stack alignment with callee-saved registers.
# These tests use csr_aie2 which is AIE2-specific.
#
# Shared tests (no CSR dependencies) are in:
#   llvm/test/CodeGen/AIE/ra/stack-alignment-callee-save.mir

# RUN: llc --march=aie2 --verify-machineinstrs -run-pass=regallocfast -run-pass=prologepilog -o - %s \
# RUN:   | FileCheck %s

#------------------------------------------------------------------------------
# Test: Callee-saved spills via function call
# Stack: 32-byte aligned, CSR: r16-r23
#------------------------------------------------------------------------------

---
name:            callee_save_via_call
alignment:       32
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p1


    ; CHECK-LABEL: name: callee_save_via_call
    ; CHECK: liveins: $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_spill killed $lr, -28, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: ST_dms_spill $p1, -32, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2, implicit-def $lr
    ; CHECK-NEXT: $p1 = LDA_dms_spill -32, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $lr = LDA_dms_spill -28, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p1
    %0:ep = COPY $p1
    PseudoJL 32, csr_aie2, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

#------------------------------------------------------------------------------
# Test: Callee-saved stack spill without function call
# All non-callee-saved GPRs (r0-r15, r24-r31) are blocked to force stack spill.
# AIE2 callee-saved: r16-r23
#------------------------------------------------------------------------------

---
name:            callee_save_stack_spill_no_call
alignment:       32
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7, $r8, $r9, $r10, $r11, $r12, $r13, $r14, $r15, $r24, $r25, $r26, $r27, $r28, $r29, $r30, $r31


    ; CHECK-LABEL: name: callee_save_stack_spill_no_call
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7, $r8, $r9, $r10, $r11, $r12, $r13, $r14, $r15, $r24, $r25, $r26, $r27, $r28, $r29, $r30, $r31, $r16
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_spill killed $r16, -32, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $r16 = IMPLICIT_DEF
    ; CHECK-NEXT: $r16 = LDA_dms_spill -32, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed $r16, implicit killed $r0, implicit killed $r1, implicit killed $r2, implicit killed $r3, implicit killed $r4, implicit killed $r5, implicit killed $r6, implicit killed $r7, implicit killed $r8, implicit killed $r9, implicit killed $r10, implicit killed $r11, implicit killed $r12, implicit killed $r13, implicit killed $r14, implicit killed $r15, implicit killed $r24, implicit killed $r25, implicit killed $r26, implicit killed $r27, implicit killed $r28, implicit killed $r29, implicit killed $r30, implicit killed $r31
    $r16 = IMPLICIT_DEF
    PseudoRET implicit $lr, implicit $r16, implicit $r0, implicit $r1, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit $r6, implicit $r7, implicit $r8, implicit $r9, implicit $r10, implicit $r11, implicit $r12, implicit $r13, implicit $r14, implicit $r15, implicit $r24, implicit $r25, implicit $r26, implicit $r27, implicit $r28, implicit $r29, implicit $r30, implicit $r31
...
