# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
#
# Unit tests for AIEStackSlotMinimization pass (AIE2 target).

# RUN: llc -mtriple=aie2 --verify-machineinstrs \
# RUN:     -run-pass=aie-spill-slot-opt -o - %s | FileCheck %s

# RUN: llc -mtriple=aie2 --verify-machineinstrs \
# RUN:     -run-pass=aie-spill-slot-opt,prologepilog -o - %s | \
# RUN:     FileCheck %s --check-prefix=STACK

---
# Test 1: Q register spill should preserve 16-byte size (not increase to 32 bytes)
# Regression test: Q register spills use 16 bytes (s128), but TRI->getSpillSize()
# returns 32 bytes for the Q register class. The pass must preserve the original
# 16-byte size from the MachineMemOperand.
# (Original: stack-slot-min-q-spill.mir)
name: q_spill_preserve_size
alignment: 16
tracksRegLiveness: true
noPhis: true
isSSA: false
noVRegs: true
stack:
  - { id: 0, type: spill-slot, size: 16, alignment: 16 }
body: |

  bb.0.entry:
    liveins: $q0

    ; CHECK-LABEL: name: q_spill_preserve_size
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dmv_sts_q_ag_spill killed $q0, %stack.0, implicit $sp :: (store (s128) into %stack.0)
    ; CHECK-NEXT: $r0 = MOVA_lda_cg 0
    ; CHECK-NEXT: $q1 = LDA_dmv_lda_q_ag_spill %stack.0, implicit $sp :: (load (s128) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $q1
    ;
    ; STACK-LABEL: name: q_spill_preserve_size
    ; STACK: liveins: $q0
    ; STACK-NEXT: {{  $}}
    ; STACK-NEXT: frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
    ; STACK-NEXT: ST_dmv_sts_q_ag_spill killed $q0, -32, implicit $sp :: (store (s128) into %stack.0)
    ; STACK-NEXT: $r0 = MOVA_lda_cg 0
    ; STACK-NEXT: $q1 = LDA_dmv_lda_q_ag_spill -32, implicit $sp :: (load (s128) from %stack.0)
    ; STACK-NEXT: frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
    ; STACK-NEXT: PseudoRET implicit $lr, implicit $q1
    ST_dmv_sts_q_ag_spill killed $q0, %stack.0, implicit $sp :: (store (s128) into %stack.0)
    $r0 = MOVA_lda_cg 0
    $q1 = LDA_dmv_lda_q_ag_spill %stack.0, implicit $sp :: (load (s128) from %stack.0)

    PseudoRET implicit $lr, implicit $q1
...

---
# Test 2: Register renaming - different physical registers accessing same FI
# When different physical registers access the same FI at offset 0,
# only ONE stack slot should be created (not duplicates).
# Scenario: X11 spilled to FI=0, X6 reloaded from FI=0 (register renaming)
# (Original: stack-slot-min-register-rename.mir)
name: register_rename_same_slot
alignment: 16
tracksRegLiveness: true
noPhis: true
isSSA: false
noVRegs: true
stack:
  - { id: 0, type: spill-slot, size: 64, alignment: 32 }
body: |
  ; CHECK-LABEL: name: register_rename_same_slot
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   VST_dmw_sts_w_ag_spill killed $wl11, %stack.1, implicit $sp :: (store (s256) into %stack.1)
  ; CHECK-NEXT:   VST_dmw_sts_w_ag_spill killed $wh11, %stack.2, implicit $sp :: (store (s256) into %stack.2)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $wl11 = VLDA_dmw_lda_w_ag_spill %stack.1, implicit $sp :: (load (s256) from %stack.1)
  ; CHECK-NEXT:   $r0 = COPY $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $wl6 = VLDA_dmw_lda_w_ag_spill %stack.1, implicit $sp :: (load (s256) from %stack.1)
  ; CHECK-NEXT:   $r1 = COPY $wl6
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1
  ;
  ; STACK-LABEL: name: register_rename_same_slot
  ; STACK: bb.0.entry:
  ; STACK-NEXT:   successors: %bb.1(0x80000000)
  ; STACK-NEXT:   liveins: $x11
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   frame-setup PADD_sp_imm_pseudo 64, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   VST_dmw_sts_w_ag_spill killed $wl11, -64, implicit $sp :: (store (s256) into %stack.1)
  ; STACK-NEXT:   VST_dmw_sts_w_ag_spill killed $wh11, -32, implicit $sp :: (store (s256) into %stack.2)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.1:
  ; STACK-NEXT:   successors: %bb.2(0x80000000)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   $wl11 = VLDA_dmw_lda_w_ag_spill -64, implicit $sp :: (load (s256) from %stack.1)
  ; STACK-NEXT:   $r0 = COPY $wl11
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.2:
  ; STACK-NEXT:   liveins: $r0
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   $wl6 = VLDA_dmw_lda_w_ag_spill -64, implicit $sp :: (load (s256) from %stack.1)
  ; STACK-NEXT:   $r1 = COPY $wl6
  ; STACK-NEXT:   frame-destroy PADD_sp_imm_pseudo -64, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1

  bb.0.entry:
    successors: %bb.1
    liveins: $x11

    VST_X_SPILL killed $x11, %stack.0, implicit $sp :: (store (s512) into %stack.0, align 32)

  bb.1:
    successors: %bb.2

    $x11 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0, align 32)
    $r0 = COPY $wl11

  bb.2:
    liveins: $r0

    $x6 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0, align 32)
    $r1 = COPY $wl6
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...
