# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass=postmisched --aie-bottomup-cycles=2 %s -o - | FileCheck %s

# partial store does a late read of its source register in E7.
# That causes a large anti latency with early writers
---
name:            anti_dep
alignment:       16
body:             |
  bb.0.entry:
    liveins: $r0, $p0
    ; CHECK-LABEL: name: anti_dep
    ; CHECK: liveins: $r0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_S16_ag_idx_imm killed $r0, killed $p0, 2
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOVXM_lng_cg 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    ST_S16_ag_idx_imm $r0, $p0, 2
    $r0 = MOVXM_lng_cg 0
    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...
