# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass=postmisched --aie-bottomup-cycles=2 %s -o - | FileCheck %s

---
name:            data_dep_2c
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $p1, $r6, $r7, $r8, $r9
    ; CHECK-LABEL: name: data_dep_2c
    ; CHECK: liveins: $p0, $p1, $r6, $r7, $r8, $r9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r12 = MUL_mul_r_rr killed $r6, killed $r7
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r13 = ADD killed $r12, killed $r8, implicit-def $srcarry
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r13
    $r12 = MUL_mul_r_rr $r6, $r7
    $r13 = ADD $r12, $r8, implicit-def $srcarry
    RET implicit $lr
    DelayedSchedBarrier implicit $r13
...

---
name:            data_dep_7c
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p1
    ; CHECK-LABEL: name: data_dep_7c
    ; CHECK: liveins: $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r7 = MOV_mv_scl killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r7
    $r6 = LDA_dms_lda_idx_imm $p1, 4
    $r7 = MOV_mv_scl $r6
    RET implicit $lr
    DelayedSchedBarrier implicit $r7
...

---
name:            data_chain_3
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p1
    ; CHECK-LABEL: name: data_chain_3
    ; CHECK: liveins: $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r6 = ADD killed $r6, $r6, implicit-def $srcarry
    ; CHECK-NEXT: $r7 = MOV_mv_scl killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r7
    $r6 = LDA_dms_lda_idx_imm $p1, 4
    $r6 = ADD $r6, $r6, implicit-def $srcarry
    $r7 = MOV_mv_scl $r6
    RET implicit $lr
    DelayedSchedBarrier implicit $r7
...

---
name:            data_chain_4
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p1
    ; CHECK-LABEL: name: data_chain_4
    ; CHECK: liveins: $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r6 = ADD killed $r6, $r6, implicit-def $srcarry
    ; CHECK-NEXT: $r6 = ADD killed $r6, $r6, implicit-def $srcarry
    ; CHECK-NEXT: $r7 = MOV_mv_scl killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r7
    $r6 = LDA_dms_lda_idx_imm $p1, 4
    $r6 = ADD $r6, $r6, implicit-def $srcarry
    $r6 = ADD $r6, $r6, implicit-def $srcarry
    $r7 = MOV_mv_scl $r6
    RET implicit $lr
    DelayedSchedBarrier implicit $r7
...

---
name:            data_chain_5
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p1
    ; CHECK-LABEL: name: data_chain_5
    ; CHECK: liveins: $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: $r6 = ADD killed $r6, $r6, implicit-def $srcarry
    ; CHECK-NEXT: $r6 = ADD killed $r6, $r6, implicit-def $srcarry
    ; CHECK-NEXT: $r6 = ADD killed $r6, $r6, implicit-def $srcarry
    ; CHECK-NEXT: $r7 = MOV_mv_scl killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r7
    $r6 = LDA_dms_lda_idx_imm $p1, 4
    $r6 = ADD $r6, $r6, implicit-def $srcarry
    $r6 = ADD $r6, $r6, implicit-def $srcarry
    $r6 = ADD $r6, $r6, implicit-def $srcarry
    $r7 = MOV_mv_scl $r6
    RET implicit $lr
    DelayedSchedBarrier implicit $r7
...
