# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass=postmisched --aie-bottomup-cycles=2 %s -o - | FileCheck %s

# Functions with a single "real instruction", which produces dead outputs.
# Make sure instruction latencies are still respected with ExitSU (DelayedSchedBarrier).

---
name:            single_inst_1c
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r6
    ; CHECK-LABEL: name: single_inst_1c
    ; CHECK: liveins: $r0, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r7 = MOV_mv_scl killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    $r7 = MOV_mv_scl $r6
    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...

---
name:            single_inst_2c
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r6, $r7, $r0
    ; CHECK-LABEL: name: single_inst_2c
    ; CHECK: liveins: $r6, $r7, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r12 = MUL_mul_r_rr killed $r6, killed $r7
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    $r12 = MUL_mul_r_rr $r6, $r7
    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...

---
name:            single_inst_7c
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p1, $r0
    ; CHECK-LABEL: name: single_inst_7c
    ; CHECK: liveins: $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    $r6 = LDA_dms_lda_idx_imm $p1, 4
    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...
