# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=aie-machine-alignment %s -verify-machineinstrs -o - | FileCheck %s

---
name:            zol_elongated_preheader_plus_4_LoopBundles_ge112bytes
alignment:       16
body:             |
  ; CHECK-LABEL: name: zol_elongated_preheader_plus_4_LoopBundles_ge112bytes
  ; CHECK: bb.0.entry (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     $ls = MOVXM %bb.1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     $le = MOVXM <mcsymbol .L_LEnd0>
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     $x3, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 killed $p0, $d0_3d, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:     $lc = ADD_NC_mv_add_ri killed $r7, -3
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     $crunpacksize = MOV_alu_mv_mv_mv_cg 1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     $x1, $p3, $dc2 = VLDA_2D_dmx_lda_x killed $p3, $d2 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $x6, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     renamable $r0 = MOVX_alu_cg 794
  ; CHECK-NEXT:     $m1 = MOV_alu_mv_mv_mv_scl internal $r0
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     renamable $r16 = MOVA -1
  ; CHECK-NEXT:     renamable $x8, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:     renamable $x2 = VBCST_16 undef renamable $r0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     renamable $m3 = MOVA 8
  ; CHECK-NEXT:     renamable $x10, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     renamable $r19 = MOVX_alu_cg 6
  ; CHECK-NEXT:     renamable $x5 = VADD_16 killed renamable $x6, killed renamable $x1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     renamable $r23 = MOVA 16
  ; CHECK-NEXT:     $x3, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 killed $p0, $d0_3d, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     renamable $r22 = MOVX_alu_cg 32
  ; CHECK-NEXT:     renamable $x7 = VADD_16 killed renamable $x5, killed renamable $x8
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     renamable $r17 = MOVA 255
  ; CHECK-NEXT:     $p2 = MOVS $p1
  ; CHECK-NEXT:     renamable $r7 = MOVX_alu_cg 8
  ; CHECK-NEXT:     $crunpacksize = MOV_alu_mv_mv_mv_cg 1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     $x1, $p3, $dc2 = VLDA_2D_dmx_lda_x killed $p3, $d2 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $x6, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     renamable $x9 = VADD_16 killed renamable $x7, killed renamable $x10
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     renamable $x8, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     renamable $x11 = VADD_16 killed renamable $x9, killed renamable $x3
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     renamable $x10, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     renamable $x5 = VADD_16 killed renamable $x6, killed renamable $x1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     $p2, $dc1 = VST_2D_dmx_sts_x killed $x11, killed $p2, $d1 :: (store (<32 x s16>))
  ; CHECK-NEXT:     $x3, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 killed $p0, $d0_3d, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
  ; CHECK-NEXT:     renamable $x7 = VADD_16 killed renamable $x5, killed renamable $x8
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $crunpacksize {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:     $crunpacksize = MOV_alu_mv_mv_mv_cg 1
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   BUNDLE implicit $lr {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $x0
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0

    BUNDLE {
      $ls = MOVXM %bb.1
    }
    BUNDLE {
      $le = MOVXM <mcsymbol .L_LEnd0>
    }
    BUNDLE {
      $x3, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 killed $p0, $d0_3d, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
      $lc = ADD_NC_mv_add_ri killed $r7, -3
    }
    BUNDLE {
      $crunpacksize = MOV_alu_mv_mv_mv_cg 1
    }
    BUNDLE {
      $x1, $p3, $dc2 = VLDA_2D_dmx_lda_x killed $p3, $d2 :: (load (<32 x s16>))
      renamable $x6, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1  :: (load (<32 x s8>))
      NOPS
      renamable $r0 = MOVX_alu_cg 794
      $m1 = MOV_alu_mv_mv_mv_scl internal $r0
      NOPV
    }
    BUNDLE  {
      renamable $r16 = MOVA -1
      renamable $x8, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1  :: (load (<32 x s8>))
      NOPX
      renamable $x2 = VBCST_16 undef renamable $r0
    }
    BUNDLE {
      renamable $m3 = MOVA 8
      renamable $x10, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
      renamable $r19 = MOVX_alu_cg 6
      renamable $x5 = VADD_16 killed renamable $x6, killed renamable $x1
    }
    BUNDLE {
      renamable $r23 = MOVA 16
      $x3, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 killed $p0, $d0_3d, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
      renamable $r22 = MOVX_alu_cg 32
      renamable $x7 = VADD_16 killed renamable $x5, killed renamable $x8
    }
    BUNDLE {
      renamable $r17 = MOVA 255
      $p2 = MOVS $p1
      renamable $r7 = MOVX_alu_cg 8
      $crunpacksize = MOV_alu_mv_mv_mv_cg 1
    }

  bb.1 (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)

    BUNDLE {
      $x1, $p3, $dc2 = VLDA_2D_dmx_lda_x killed $p3, $d2 :: (load (<32 x s16>))
      renamable $x6, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
      renamable $x9 = VADD_16 killed renamable $x7, killed renamable $x10
    }
    BUNDLE {
      renamable $x8, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
      renamable $x11 = VADD_16 killed renamable $x9, killed renamable $x3
    }
    BUNDLE {
      renamable $x10, renamable $p0 = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 killed renamable $p0, renamable $m4, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
      renamable $x5 = VADD_16 killed renamable $x6, killed renamable $x1
    }
    BUNDLE {
      $p2, $dc1 = VST_2D_dmx_sts_x killed $x11, killed $p2, $d1 :: (store (<32 x s16>))
      $x3, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 killed $p0, $d0_3d, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
      renamable $x7 = VADD_16 killed renamable $x5, killed renamable $x8
    }
    BUNDLE implicit-def $crunpacksize {
      NOPA
      NOPB
      NOPS
      NOPX
      $crunpacksize = MOV_alu_mv_mv_mv_cg 1
      NOPV
    }
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
  bb.2:
    BUNDLE implicit $lr {
      RET implicit $lr
    }
    DelayedSchedBarrier implicit killed $x0

...

...
