# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p --start-before=postmisched %s -o - | FileCheck %s

# This test checks if loop bundles need elonagation if when the number of bundles
# in the loop is less than 7, and the combined size of the elongated preheader and
# the original loop bundles is at least 112 bytes.
#
# Note: Edge latency is adjusted based on the number of loop bundles using this condition:
# if (ZOLBundlesCount < ZOLSupport->LoopSetupDistance)
#     EdgeLatency = std::max(EdgeLatency, ZOLSupport->LoopSetupDistance + 1 - ZOLBundlesCount);

--- |

  define <32 x i16> @zol_elongated_preheader_plus_NumOfLoopBundles_ge112bytes(i32 %n, ptr %p) {
  ; CHECK-LABEL: zol_elongated_preheader_plus_NumOfLoopBundles_ge112bytes:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    nopa ; nopb ; nops ; add r0, r0, #-1; nopm ; nopv
  ; CHECK-NEXT:    vldb x6, [p0], #0; add.nc lc, r0, #-3
  ; CHECK-NEXT:    vldb x0, [p0], #64; add r0, r0, #-1
  ; CHECK-NEXT:    vlda x2, [p0], #64
  ; CHECK-NEXT:    vldb x1, [p0], #128; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    vldb x0, [p0], #64; add r0, r0, #-1
  ; CHECK-NEXT:    vlda x2, [p0], #64; nopb ; nops ; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    nopa ; vldb x1, [p0], #128; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; vldb x0, [p0], #64; nops ; add r0, r0, #-1; nopm ; nopv
  ; CHECK-NEXT:    vlda x2, [p0], #64; nopb ; nops ; nopx ; vadd.16 x4, x6, x0; nopv
  ; CHECK-NEXT:    nopa ; vldb x1, [p0], #128; nops ; nopxm ; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; vldb x0, [p0], #64; nops ; add r0, r0, #-1; vadd.16 x6, x4, x1; nopv
  ; CHECK-NEXT:    vlda x2, [p0], #64; nopb ; nops ; nopx ; vadd.16 x4, x6, x0; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; vldb x1, [p0], #128; nops ; nopxm ; nopv
  ; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vadd.16 x6, x4, x1; nopv
  ; CHECK-NEXT:    nopx ; vadd.16 x4, x6, x0
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vadd.16 x6, x4, x1
  ; CHECK-NEXT:    ret lr; vadd.16 x4, x6, x0
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    vadd.16 x6, x4, x1 // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    vmov x0, x6 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %for.body

  for.body:                                         ; preds = %for.body, %entry
    %lsr.iv = phi i32 [ %lsr.iv.next, %for.body ], [ %n, %entry ]
    %s.04 = phi <32 x i16> [ undef, %entry ], [ %s.next, %for.body ]
    %p.addr.03 = phi ptr [ %p, %entry ], [ %incdec.ptr1, %for.body ]
    %v0 = load <32 x i16>, ptr %p.addr.03, align 64
    %s1 = add <32 x i16> %s.04, %v0
    %p.addr.1 = getelementptr inbounds i8, ptr %p.addr.03, i32 64
    %v1 = load <32 x i16>, ptr %p.addr.1, align 64
    %s2 = add <32 x i16> %s1, %v1
    %incdec.ptr1 = getelementptr inbounds i8, ptr %p.addr.03, i32 128
    %exitcond.not = icmp eq i32 %lsr.iv, 1
    %s.next = select i1 %exitcond.not, <32 x i16> %s2, <32 x i16> %s2
    %lsr.iv.next = add i32 %lsr.iv, -1
    %0 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %0, label %for.body, label %for.cond.cleanup, !llvm.loop !0

  for.cond.cleanup:                                 ; preds = %for.body
    ret <32 x i16> %s2
  }

  declare void @llvm.set.loop.iterations.i32(i32) #0

  declare i1 @llvm.loop.decrement.i32(i32) #0

  attributes #0 = { nocallback noduplicate nofree nosync nounwind willreturn }

  !0 = distinct !{!0, !1, !2, !3}
  !1 = !{!"llvm.loop.mustprogress"}
  !2 = !{!"llvm.loop.itercount.range", i64 10}
  !3 = !{!"llvm.loop.unroll.disable"}

...
---
name:            zol_elongated_preheader_plus_NumOfLoopBundles_ge112bytes
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0

    renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.1
    $le = MOVXM <mcsymbol .L_LEnd0>
    renamable $x6, renamable $p0 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p0, 0 :: (load (<32 x s16>) from %ir.p.addr.03)
    NOPB
    NOPA
    NOPS
    NOPXM
    NOPV

  bb.1.for.body (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p0, $r0, $x6

    renamable $x0, renamable $p0 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p0, 64 :: (load (<32 x s16>) from %ir.p.addr.03)
    renamable $x2, renamable $p0 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p0, 64 :: (load (<32 x s16>) from %ir.p.addr.1)
    renamable $x1, renamable $p0 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p0, 128 :: (load (<32 x s16>) from %ir.p.addr.1)
    renamable $x4 = VADD_16 killed renamable $x6, killed renamable $x0
    renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    renamable $x6 = VADD_16 killed renamable $x4, killed renamable $x1
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2.for.cond.cleanup:
    liveins: $x6

    $x0 = VMOV_alu_mv_mv_x killed $x6
    RET implicit $lr
    DelayedSchedBarrier implicit $x0

...
