# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -run-pass=postmisched --issue-limit=1 %s -o - | FileCheck %s

---
name:            write_E1_read_E7
alignment:       16
body:             |
  bb.0.entry:
    liveins: $r0, $p0
    ; CHECK-LABEL: name: write_E1_read_E7
    ; CHECK: liveins: $r0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_s16_idx_imm killed $r0, killed $p0, 2, implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOVXM 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $r0 = MOVXM 0
    ST_s16_idx_imm $r0, $p0, 2, implicit-def $pe2_ads, implicit $pe2_ads
...
