# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2 -run-pass=postrapseudos %s -o - | FileCheck %s

# The test make sure that multi-slot pseudo instr. are not expanded by expandPostRAPseudo(..)

---
name:            padd
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: padd
    ; CHECK: $p0 = PADD_mod_pseudo $p0, $m0
    ; CHECK-NEXT: $p1 = PADD_mod_pseudo $p1, $m1
    ; CHECK-NEXT: $p2 = PADD_mod_pseudo $p2, $m2
    $p0 = PADD_mod_pseudo $p0, $m0
    $p1 = PADD_mod_pseudo $p1, $m1
    $p2 = PADD_mod_pseudo $p2, $m2
...

---
name:            padd_imm
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: padd_imm
    ; CHECK: $p0 = PADD_imm9_pseudo $p0, 4
    ; CHECK-NEXT: $p1 = PADD_imm9_pseudo $p1, -4
    ; CHECK-NEXT: $p1 = PADD_imm9_pseudo $p1, 100
    ; CHECK-NEXT: $p1 = PADD_imm9_pseudo $p1, -100
    ; CHECK-NEXT: $p2 = PADD_imm9_pseudo $p2, 1020
    $p0 = PADD_imm9_pseudo $p0, 4
    $p1 = PADD_imm9_pseudo $p1, -4
    $p1 = PADD_imm9_pseudo $p1, 100
    $p1 = PADD_imm9_pseudo $p1, -100
    $p2 = PADD_imm9_pseudo $p2, 1020
...

---
name:            padd_sp_imm
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: padd_sp_imm
    ; CHECK: PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PADD_sp_imm_pseudo -65536, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PADD_sp_imm_pseudo 65504, implicit-def $sp, implicit $sp
    PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
    PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
    PADD_sp_imm_pseudo -65536, implicit-def $sp, implicit $sp
    PADD_sp_imm_pseudo 65504, implicit-def $sp, implicit $sp
...
