# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2 -run-pass=aie-pseudobranches %s -o - | FileCheck %s

---
name:            test_jnz
alignment:       16
body:             |
  ; CHECK-LABEL: name: test_jnz
  ; CHECK: bb.0 (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JNZ $r6, %bb.1
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (align 16):
  bb.0 (align 16):
    PseudoJNZ $r6, %bb.1
  bb.1 (align 16):
...

---
name:            test_jz
alignment:       16
body:             |
  ; CHECK-LABEL: name: test_jz
  ; CHECK: bb.0 (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JZ $r6, %bb.1
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (align 16):
  bb.0 (align 16):
    PseudoJZ $r6, %bb.1
  bb.1 (align 16):
...

---
name:            test_jnzd
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_jnzd
    ; CHECK: $r6 = JNZD $r6, $p2, implicit-def $srcarry
    ; CHECK-NEXT: DelayedSchedBarrier
    $r6 = PseudoJNZD $r6, $p2, implicit-def $srcarry
...

---
name:            test_j_imm
alignment:       16
body:             |
  ; CHECK-LABEL: name: test_j_imm
  ; CHECK: bb.0 (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   J_jump_imm %bb.1
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (align 16):
  bb.0 (align 16):
    PseudoJ_jump_imm %bb.1
  bb.1 (align 16):
...

---
name:            test_j_ind
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_j_ind
    ; CHECK: J_jump_ind $p2
    ; CHECK-NEXT: DelayedSchedBarrier
    PseudoJ_jump_ind $p2
...

---
name:            test_ret
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_ret
    ; CHECK: RET implicit $lr
    ; CHECK-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name:            test_jl
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_jl
    ; CHECK: JL 128, implicit-def $lr
    ; CHECK-NEXT: DelayedSchedBarrier implicit $r0, implicit $r1
    ; CHECK-NEXT: JL_IND $p2, implicit-def $lr
    ; CHECK-NEXT: DelayedSchedBarrier implicit-def dead $r0, implicit $r2, implicit $r3
    PseudoJL 128, implicit-def $lr, implicit $r0, implicit $r1
    PseudoJL_IND $p2, implicit-def $lr, implicit-def dead $r0, implicit $r2, implicit $r3
...

---
name:            test_jl_regmask
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_jl_regmask
    ; CHECK: JL 128, implicit-def $lr
    ; CHECK-NEXT: DelayedSchedBarrier csr_aie2, implicit $r1
    ; CHECK-NEXT: JL_IND $p2, implicit-def $lr
    ; CHECK-NEXT: DelayedSchedBarrier CustomRegMask($lr,$l1,$l2,$l3,$p6,$p7,$r18,$r19,$r20,$r21,$r22,$r23), implicit $r3
    PseudoJL 128, csr_aie2, implicit-def $lr, implicit $r1
    PseudoJL_IND $p2, CustomRegMask($lr,$l1,$l2,$l3,$p6,$p7,$r18,$r19,$r20,$r21,$r22,$r23), implicit-def $lr, implicit $r3
...

---
name:            test_multi
alignment:       16
body:             |
  ; CHECK-LABEL: name: test_multi
  ; CHECK: bb.0 (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JL_IND $p2, implicit-def $lr
  ; CHECK-NEXT:   DelayedSchedBarrier implicit $r2, implicit $r3
  ; CHECK-NEXT:   JZ $r6, %bb.1
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT:   JNZ $r6, %bb.2
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (align 16):
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (align 16):
  bb.0 (align 16):
    PseudoJL_IND $p2, implicit-def $lr, implicit $r2, implicit $r3
    PseudoJZ $r6, %bb.1
    PseudoJNZ $r6, %bb.2
  bb.1 (align 16):
  bb.2 (align 16):
...
