# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2 -run-pass=postrapseudos %s -o - | FileCheck %s

---
name:            pseudoMov_GPR
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: pseudoMov_GPR
    ; CHECK: $r1 = MOV_SCL_pseudo $r0
    $r1 = PseudoMove $r0
...

---
name:            pseudoMov_non_GPR
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: pseudoMov_non_GPR
    ; CHECK: $r1 = MOV_mv_scl $p0
    ; CHECK-NEXT: $p0 = MOV_mv_scl $r1
    ; CHECK-NEXT: $p1 = MOV_mv_scl $p0
    ; CHECK-NEXT: $r1 = MOV_mv_scl $s0
    ; CHECK-NEXT: $s0 = MOV_mv_scl $r1
    ; CHECK-NEXT: $s1 = MOV_mv_scl $s0
    $r1 = PseudoMove $p0
    $p0 = PseudoMove $r1
    $p1 = PseudoMove $p0
    $r1 = PseudoMove $s0
    $s0 = PseudoMove $r1
    $s1 = PseudoMove $s0
...

---
name:            COPY_GPR
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: COPY_GPR
    ; CHECK: $r1 = MOV_SCL_pseudo $r0
    $r1 = COPY $r0
...

---
name:            COPY_non_GPR
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: COPY_non_GPR
    ; CHECK: $r1 = MOV_mv_scl $p0
    ; CHECK-NEXT: $p0 = MOV_mv_scl $r1
    ; CHECK-NEXT: $p1 = MOV_mv_scl $p0
    ; CHECK-NEXT: $r1 = MOV_mv_scl $s0
    ; CHECK-NEXT: $s0 = MOV_mv_scl $r1
    ; CHECK-NEXT: $s1 = MOV_mv_scl $s0
    $r1 = COPY $p0
    $p0 = COPY $r1
    $p1 = COPY $p0
    $r1 = COPY $s0
    $s0 = COPY $r1
    $s1 = COPY $s0
...
