# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2 -run-pass=postrapseudos %s -o - | FileCheck %s

---
name:            _Z22test_sparse_pop_set_lo_4
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: _Z22test_sparse_pop_set_lo_4
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_POP_4 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx0 = PSEUDO_VLD_SPARSE_POP_4_set_low killed renamable $p1
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            _Z22test_sparse_peek_set_lo_4
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: _Z22test_sparse_peek_set_lo_4
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_PEEK_4 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx0 = PSEUDO_VLD_SPARSE_PEEK_4_set_low killed renamable $p1
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            Z31test_sparse_pop_and_get_pointer_4
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_pop_and_get_pointer_4
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_POP_4 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: $dn0 = MOV_mv_scl $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dn0, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $dn0, renamable $qx0 = PSEUDO_VLD_SPARSE_POP_4_and_get_pointer killed renamable $p1
  ST_dms_sts_idx_imm $dn0, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            Z31test_sparse_reset_4
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_reset_4
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: renamable $p1 = VLDB_SPARSE_RESET_4 killed renamable $p1, implicit-def $srsparse_of, implicit-def dead $dp, implicit killed $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0) , align 4)
  renamable $p1 = VLDB_SPARSE_RESET_4 killed renamable $p1, implicit-def $srsparse_of, implicit-def dead $dp, implicit killed $dp
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr
...

---
name:            Z31test_sparse_fill_4
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_fill_4
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: renamable $p1 = VLDB_SPARSE_FILL_4 killed renamable $p1, implicit-def $srsparse_of, implicit killed $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1 = VLDB_SPARSE_FILL_4 killed renamable $p1, implicit-def $srsparse_of, implicit killed $dp
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr
...

---
name:            _Z25test_sparse_pop_insert_hi_4
body:             |
  bb.0:
  liveins: $p0, $q2, $x2
    ; CHECK-LABEL: name: _Z25test_sparse_pop_insert_hi_4
    ; CHECK: liveins: $p0, $q2, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwh2 = VLDB_SPARSE_POP_4 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: $x0 = VMOV_mv_x $x2
    ; CHECK-NEXT: $q0 = VMOV_mv_w killed $q2
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed $x0, implicit killed $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx2 = PSEUDO_VLD_SPARSE_POP_4_insert_hi killed renamable $p1, killed renamable $qx2
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  $x0 = COPY renamable $x2
  $q0 = COPY killed renamable $q2
  PseudoRET implicit $lr, implicit killed $x0, implicit killed $q0
...




---
name:            _Z22test_sparse_pop_set_lo_8
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: _Z22test_sparse_pop_set_lo_8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_POP_8 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx0 = PSEUDO_VLD_SPARSE_POP_8_set_low killed renamable $p1
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            _Z22test_sparse_peek_set_lo_8
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: _Z22test_sparse_peek_set_lo_8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_PEEK_8 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx0 = PSEUDO_VLD_SPARSE_PEEK_8_set_low killed renamable $p1
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            Z31test_sparse_pop_and_get_pointer_8
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_pop_and_get_pointer_8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_POP_8 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: $dn0 = MOV_mv_scl $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dn0, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $dn0, renamable $qx0 = PSEUDO_VLD_SPARSE_POP_8_and_get_pointer killed renamable $p1
  ST_dms_sts_idx_imm $dn0, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            Z31test_sparse_reset_8
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_reset_8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: renamable $p1 = VLDB_SPARSE_RESET_8 killed renamable $p1, implicit-def $srsparse_of, implicit-def dead $dp, implicit killed $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0) , align 4)
  renamable $p1 = VLDB_SPARSE_RESET_8 killed renamable $p1, implicit-def $srsparse_of, implicit-def dead $dp, implicit killed $dp
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr
...

---
name:            Z31test_sparse_fill_8
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_fill_8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: renamable $p1 = VLDB_SPARSE_FILL_8 killed renamable $p1, implicit-def $srsparse_of, implicit killed $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1 = VLDB_SPARSE_FILL_8 killed renamable $p1, implicit-def $srsparse_of, implicit killed $dp
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr
...

---
name:            _Z25test_sparse_pop_insert_hi_8
body:             |
  bb.0:
  liveins: $p0, $q2, $x2
    ; CHECK-LABEL: name: _Z25test_sparse_pop_insert_hi_8
    ; CHECK: liveins: $p0, $q2, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwh2 = VLDB_SPARSE_POP_8 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: $x0 = VMOV_mv_x $x2
    ; CHECK-NEXT: $q0 = VMOV_mv_w killed $q2
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed $x0, implicit killed $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx2 = PSEUDO_VLD_SPARSE_POP_8_insert_hi killed renamable $p1, killed renamable $qx2
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  $x0 = COPY renamable $x2
  $q0 = COPY killed renamable $q2
  PseudoRET implicit $lr, implicit killed $x0, implicit killed $q0
...


---
name:            _Z22test_sparse_pop_set_lo_16
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: _Z22test_sparse_pop_set_lo_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_POP_16 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx0 = PSEUDO_VLD_SPARSE_POP_16_set_low killed renamable $p1
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            _Z22test_sparse_peek_set_lo_16
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: _Z22test_sparse_peek_set_lo_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_PEEK_16 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx0 = PSEUDO_VLD_SPARSE_PEEK_16_set_low killed renamable $p1
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            Z31test_sparse_pop_and_get_pointer_16
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_pop_and_get_pointer_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwl0 = VLDB_SPARSE_POP_16 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: $dn0 = MOV_mv_scl $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dn0, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $dn0, renamable $qx0 = PSEUDO_VLD_SPARSE_POP_16_and_get_pointer killed renamable $p1
  ST_dms_sts_idx_imm $dn0, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr, implicit $x0, implicit $q0
...

---
name:            Z31test_sparse_reset_16
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_reset_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: renamable $p1 = VLDB_SPARSE_RESET_16 killed renamable $p1, implicit-def $srsparse_of, implicit-def dead $dp, implicit killed $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0) , align 4)
  renamable $p1 = VLDB_SPARSE_RESET_16 killed renamable $p1, implicit-def $srsparse_of, implicit-def dead $dp, implicit killed $dp
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr
...

---
name:            Z31test_sparse_fill_16
body:             |
  bb.0:
  liveins: $p0
    ; CHECK-LABEL: name: Z31test_sparse_fill_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: renamable $p1 = VLDB_SPARSE_FILL_16 killed renamable $p1, implicit-def $srsparse_of, implicit killed $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1 = VLDB_SPARSE_FILL_16 killed renamable $p1, implicit-def $srsparse_of, implicit killed $dp
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  PseudoRET implicit $lr
...

---
name:            _Z25test_sparse_pop_insert_hi_16
body:             |
  bb.0:
  liveins: $p0, $q2, $x2
    ; CHECK-LABEL: name: _Z25test_sparse_pop_insert_hi_16
    ; CHECK: liveins: $p0, $q2, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p1, $qwh2 = VLDB_SPARSE_POP_16 $p1, implicit-def $srsparse_of, implicit-def $srcompr_uf, implicit-def $dp, implicit $dp
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
    ; CHECK-NEXT: $x0 = VMOV_mv_x $x2
    ; CHECK-NEXT: $q0 = VMOV_mv_w killed $q2
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed $x0, implicit killed $q0
  renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (dereferenceable load (p0), align 4)
  renamable $p1, renamable $qx2 = PSEUDO_VLD_SPARSE_POP_16_insert_hi killed renamable $p1, killed renamable $qx2
  ST_dms_sts_idx_imm killed renamable $p1, killed renamable $p0, 0 :: (store (p0), align 4)
  $x0 = COPY renamable $x2
  $q0 = COPY killed renamable $q2
  PseudoRET implicit $lr, implicit killed $x0, implicit killed $q0
...

