; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 --mtriple=aie2ps %s -o - --stop-before=irtranslator | \
; RUN:   FileCheck %s

; We have float operations in the loop body, and we check whether ZOL loops
; were created by looking for the hallmark intrinsics

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local float @factorial(i32 noundef %n) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %p = phi float [ 1.000000e+00, %entry ], [ %mul, %for.body ]
  %f = phi float [ 1.000000e+00, %entry ], [ %add, %for.body ]
  %mul = fmul float %p, %f
  %add = fadd float %f, 1.000000e+00
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret float %mul
}

; We have uitofp in the loop body, and we check whether ZOL loops
; were created by looking for the hallmark intrinsics

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local float @uitofpConv(i32 noundef %n, i32 %idx, <16 x float> %init) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %20 = phi <16 x float> [ %init, %entry ], [ %vecins.i.i.i.i.i, %for.body ]
  %conv = uitofp i32 %idx to float
  %vecins.i.i.i.i.i = insertelement <16 x float> %20, float %conv, i32 %idx
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret float %conv
}

; We have sitofp in the loop body, and we check whether ZOL loops
; were created by looking for the hallmark intrinsics

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local float @sitofpConv(i32 noundef %n, i32 %idx, <16 x float> %init) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %20 = phi <16 x float> [ %init, %entry ], [ %vecins.i.i.i.i.i, %for.body ]
  %conv = sitofp i32 %idx to float
  %vecins.i.i.i.i.i = insertelement <16 x float> %20, float %conv, i32 %idx
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret float %conv
}

; Integer sdiv/udiv/srem/urem lower to __divsi3/__udivsi3/__modsi3/__umodsi3
; libcalls; none must form a ZOL.

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local i32 @sdiv_test(i32 noundef %n, i32 %d) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi i32 [ 0, %entry ], [ %q, %for.body ]
  %q = sdiv i32 %acc, %d
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret i32 %q
}

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local i32 @udiv_test(i32 noundef %n, i32 %d) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi i32 [ 0, %entry ], [ %q, %for.body ]
  %q = udiv i32 %acc, %d
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret i32 %q
}

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local i32 @srem_test(i32 noundef %n, i32 %d) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi i32 [ 0, %entry ], [ %r, %for.body ]
  %r = srem i32 %acc, %d
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret i32 %r
}

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local i32 @urem_test(i32 noundef %n, i32 %d) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi i32 [ 0, %entry ], [ %r, %for.body ]
  %r = urem i32 %acc, %d
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret i32 %r
}

; A scalar i64 mul lowers to a __muldi3 libcall, so no ZOL must be formed.

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local i64 @mul_i64_test(i32 noundef %n, i64 %y) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi i64 [ 1, %entry ], [ %m, %for.body ]
  %m = mul i64 %acc, %y
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret i64 %m
}

; frem lowers to a fmodf libcall, so no ZOL must be formed.

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local float @frem_test(i32 noundef %n, float %y) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi float [ 1.000000e+00, %entry ], [ %r, %for.body ]
  %r = frem float %acc, %y
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret float %r
}

; f64 fmin/fmax lower to fmin/fmax libcalls, so no ZOL must be formed.

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local double @fmin_f64_test(i32 noundef %n, double %y) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi double [ 0.000000e+00, %entry ], [ %m, %for.body ]
  %m = call double @llvm.minnum.f64(double %acc, double %y)
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret double %m
}

; CHECK-NOT: llvm.set.loop.iterations
; CHECK-NOT: llvm.loop.decrement

define dso_local double @fmax_f64_test(i32 noundef %n, double %y) local_unnamed_addr {
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %acc = phi double [ 0.000000e+00, %entry ], [ %m, %for.body ]
  %m = call double @llvm.maxnum.f64(double %acc, double %y)
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0

for.cond.cleanup:                                 ; preds = %for.body
  ret double %m
}

declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.mustprogress"}
!2 = !{!"llvm.loop.itercount.range", i64 10}
