# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck -check-prefixes=CHECK,AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck -check-prefixes=CHECK,AIE2PS %s

---
name:            vconcat_v8s64_v4s64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:

    ; CHECK-LABEL: name: vconcat_v8s64_v4s64
    ; CHECK: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[DEF]], %subreg.sub_256_lo, [[DEF1]], %subreg.sub_256_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    %1:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    %2:vregbank(<8 x s64>) = G_CONCAT_VECTORS %0(<4 x s64>), %1(<4 x s64>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vconcat_1024_acc32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: vconcat_1024_acc32
    ; AIE2P: [[DEF:%[0-9]+]]:mwbfsrs = IMPLICIT_DEF
    ; AIE2P-NEXT: [[DEF1:%[0-9]+]]:mwbfsrs = IMPLICIT_DEF
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[DEF]], %subreg.sub_512_acc_lo, [[DEF1]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: vconcat_1024_acc32
    ; AIE2PS: [[DEF:%[0-9]+]]:mmvbmsrc = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[DEF1:%[0-9]+]]:mmvbmsrc = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[DEF]], %subreg.sub_512_acc_lo, [[DEF1]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    ;
    %0:accregbank(<16 x s32>) = G_IMPLICIT_DEF
    %1:accregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:accregbank(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vconcat_2048_acc64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vconcat_2048_acc64
    ; CHECK: [[DEF:%[0-9]+]]:ecml = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:ecmh = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[DEF]], %subreg.sub_1024_acc_lo, [[DEF1]], %subreg.sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %1:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %2:accregbank(<32 x s64>) = G_CONCAT_VECTORS %0(<16 x s64>), %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vconcat_2048_acc32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vconcat_2048_acc32
    ; CHECK: [[DEF:%[0-9]+]]:ecml = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:ecmh = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[DEF]], %subreg.sub_1024_acc_lo, [[DEF1]], %subreg.sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    %1:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    %2:accregbank(<64 x s32>) = G_CONCAT_VECTORS %0(<32 x s32>), %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %2
...
---
name:            vconcat_v4i16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r1, $r2

    ; AIE2P-LABEL: name: vconcat_v4i16
    ; AIE2P: liveins: $r1, $r2
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mrz = COPY $r1
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:mrz = COPY $r2
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[COPY]], %subreg.sub_l_even, [[COPY1]], %subreg.sub_l_odd
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    ; 
    ; AIE2PS-LABEL: name: vconcat_v4i16
    ; AIE2PS: liveins: $r1, $r2
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ere = COPY $r1
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ero = COPY $r2
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[COPY]], %subreg.sub_l_even, [[COPY1]], %subreg.sub_l_odd
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    ; 
    %0:gprregbank(<2 x s16>) = COPY $r1
    %1:gprregbank(<2 x s16>) = COPY $r2
    %2:gprregbank(<4 x s16>) = G_CONCAT_VECTORS %0(<2 x s16>), %1(<2 x s16>)
    PseudoRET implicit $lr, implicit %2
...
---
name:            vconcat_v8i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r1, $r2

    ; AIE2P-LABEL: name: vconcat_v8i8
    ; AIE2P: liveins: $r1, $r2
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mrz = COPY $r1
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:mrz = COPY $r2
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[COPY]], %subreg.sub_l_even, [[COPY1]], %subreg.sub_l_odd
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: vconcat_v8i8
    ; AIE2PS: liveins: $r1, $r2
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ere = COPY $r1
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ero = COPY $r2
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[COPY]], %subreg.sub_l_even, [[COPY1]], %subreg.sub_l_odd
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    ;
    %0:gprregbank(<4 x s8>) = COPY $r1
    %1:gprregbank(<4 x s8>) = COPY $r2
    %2:gprregbank(<8 x s8>) = G_CONCAT_VECTORS %0(<4 x s8>), %1(<4 x s8>)
    PseudoRET implicit $lr, implicit %2
...
