# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie-postlegalizer-custom-combiner -verify-machineinstrs -o - %s | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-postlegalizer-custom-combiner -verify-machineinstrs -o - %s | FileCheck %s

# AIE2P/AIE2PS maxVecBitSize=2048: split 2048-bit concat+stores into two 1024-bit stores.

---
name:            split_concat_store_2048
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $y0, $y1
    ; CHECK-LABEL: name: split_concat_store_2048
    ; CHECK: liveins: $p0, $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY $y1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: G_STORE [[COPY2]](<32 x s32>), [[PTR_ADD]](p0) :: (store (<32 x s32>) into unknown-address + 128)
    ; CHECK-NEXT: G_STORE [[COPY1]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>))
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %3:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    G_STORE %3(<64 x s32>), %0(p0) :: (store (<64 x s32>), align 128)
...
---
name:            split_concat_offset_store_2048
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $y0, $y1
    ; CHECK-LABEL: name: split_concat_offset_store_2048
    ; CHECK: liveins: $p0, $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY $y1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[COPY2]](<32 x s32>), [[PTR_ADD1]](p0) :: (store (<32 x s32>) into unknown-address + 128)
    ; CHECK-NEXT: G_STORE [[COPY1]](<32 x s32>), [[PTR_ADD]](p0) :: (store (<32 x s32>))
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %3:_(s20) = G_CONSTANT i20 64
    %4:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    G_AIE_OFFSET_STORE %4(<64 x s32>), %0(p0), %3(s20) :: (store (<64 x s32>), align 128)
...
---
name:            split_concat_postinc_store_2048
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $y0, $y1
    ; CHECK-LABEL: name: split_concat_postinc_store_2048
    ; CHECK: liveins: $p0, $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY $y1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[COPY2]](<32 x s32>), [[PTR_ADD]](p0) :: (store (<32 x s32>) into unknown-address + 128)
    ; CHECK-NEXT: G_STORE [[COPY1]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>))
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: $p1 = COPY [[PTR_ADD1]](p0)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %3:_(s20) = G_CONSTANT i20 256
    %4:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    %5:_(p0) = G_AIE_POSTINC_STORE %4(<64 x s32>), %0(p0), %3(s20) :: (store (<64 x s32>), align 128)
    $p1 = COPY %5(p0)
...
---
# Negative: 1024-bit concat store is below AIE2P/AIE2PS threshold (2048).
name:            no_split_concat_store_1024
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $x0, $x2
    ; CHECK-LABEL: name: no_split_concat_store_1024
    ; CHECK: liveins: $p0, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY1]](<16 x s32>), [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: G_STORE [[CONCAT_VECTORS]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>))
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    G_STORE %3(<32 x s32>), %0(p0) :: (store (<32 x s32>), align 128)
...
---
# Negative: 2048-bit concat store with multi-use prevents splitting.
name:            no_split_concat_store_2048_multi_use
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $y0, $y1
    ; CHECK-LABEL: name: no_split_concat_store_2048_multi_use
    ; CHECK: liveins: $p0, $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY $y1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[COPY1]](<32 x s32>), [[COPY2]](<32 x s32>)
    ; CHECK-NEXT: G_STORE [[CONCAT_VECTORS]](<64 x s32>), [[COPY]](p0) :: (store (<64 x s32>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<64 x s32>) = COPY [[CONCAT_VECTORS]](<64 x s32>)
    ; CHECK-NEXT: G_STORE [[COPY3]](<64 x s32>), [[COPY]](p0) :: (store (<64 x s32>), align 128)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %3:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    G_STORE %3(<64 x s32>), %0(p0) :: (store (<64 x s32>), align 128)
    %4:_(<64 x s32>) = COPY %3(<64 x s32>)
    G_STORE %4(<64 x s32>), %0(p0) :: (store (<64 x s32>), align 128)
...
---
# Negative: 2048-bit offset store with multi-use prevents splitting.
name:            no_split_concat_offset_store_2048_multi_use
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $y0, $y1
    ; CHECK-LABEL: name: no_split_concat_offset_store_2048_multi_use
    ; CHECK: liveins: $p0, $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY $y1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[COPY1]](<32 x s32>), [[COPY2]](<32 x s32>)
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[CONCAT_VECTORS]](<64 x s32>), [[COPY]](p0), [[C]](s20) :: (store (<64 x s32>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<64 x s32>) = COPY [[CONCAT_VECTORS]](<64 x s32>)
    ; CHECK-NEXT: G_STORE [[COPY3]](<64 x s32>), [[COPY]](p0) :: (store (<64 x s32>), align 128)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %3:_(s20) = G_CONSTANT i20 64
    %4:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    G_AIE_OFFSET_STORE %4(<64 x s32>), %0(p0), %3(s20) :: (store (<64 x s32>), align 128)
    %5:_(<64 x s32>) = COPY %4(<64 x s32>)
    G_STORE %5(<64 x s32>), %0(p0) :: (store (<64 x s32>), align 128)
...
---
# Negative: 2048-bit postinc store with multi-use prevents splitting.
name:            no_split_concat_postinc_store_2048_multi_use
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $y0, $y1
    ; CHECK-LABEL: name: no_split_concat_postinc_store_2048_multi_use
    ; CHECK: liveins: $p0, $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY $y1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[COPY1]](<32 x s32>), [[COPY2]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:_(p0) = G_AIE_POSTINC_STORE [[CONCAT_VECTORS]](<64 x s32>), [[COPY]], [[C]](s20) :: (store (<64 x s32>), align 128)
    ; CHECK-NEXT: $p1 = COPY [[AIE_POSTINC_STORE]](p0)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<64 x s32>) = COPY [[CONCAT_VECTORS]](<64 x s32>)
    ; CHECK-NEXT: G_STORE [[COPY3]](<64 x s32>), [[COPY]](p0) :: (store (<64 x s32>), align 128)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %3:_(s20) = G_CONSTANT i20 256
    %4:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    %5:_(p0) = G_AIE_POSTINC_STORE %4(<64 x s32>), %0(p0), %3(s20) :: (store (<64 x s32>), align 128)
    $p1 = COPY %5(p0)
    %6:_(<64 x s32>) = COPY %4(<64 x s32>)
    G_STORE %6(<64 x s32>), %0(p0) :: (store (<64 x s32>), align 128)
...
