; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --print-fixed-stack
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s
; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

; 256-bit vector types

define void @callee_v8int32(<8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
  ; CHECK-LABEL: name: callee_v8int32
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -32, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1 (%ir-block.25):
  ; CHECK-NEXT:   liveins: $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
                             <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
                             <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
                             <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
                             <8 x i32>) {
  ret void
}

define void @callee_v16int16(<16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
  ; CHECK-LABEL: name: callee_v16int16
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -64, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -32, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1 (%ir-block.26):
  ; CHECK-NEXT:   liveins: $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s16>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s16>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s16>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<16 x s16>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<16 x s16>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s16>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<16 x s16>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<16 x s16>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<16 x s16>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<16 x s16>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<16 x s16>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s16>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<16 x s16>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<16 x s16>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<16 x s16>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<16 x s16>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<16 x s16>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<16 x s16>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<16 x s16>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<16 x s16>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<16 x s16>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<16 x s16>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<16 x s16>) = COPY $wh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s16>) from %fixed-stack.1)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<16 x s16>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   PseudoRET implicit $lr
                              <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
                              <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
                              <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
                              <16 x i16>, <16 x i16>) {
  ret void
}

define void @callee_v32int8(<32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
  ; CHECK-LABEL: name: callee_v32int8
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -64, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -32, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1 (%ir-block.26):
  ; CHECK-NEXT:   liveins: $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<32 x s8>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<32 x s8>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<32 x s8>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<32 x s8>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<32 x s8>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<32 x s8>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<32 x s8>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<32 x s8>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<32 x s8>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<32 x s8>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<32 x s8>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<32 x s8>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<32 x s8>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<32 x s8>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<32 x s8>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<32 x s8>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<32 x s8>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<32 x s8>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<32 x s8>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<32 x s8>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<32 x s8>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<32 x s8>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<32 x s8>) = COPY $wh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<32 x s8>) from %fixed-stack.1)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<32 x s8>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   PseudoRET implicit $lr
                            <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
                            <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
                            <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
                            <32 x i8>, <32 x i8>) {
  ret void
}

define void @callee_v8float(<8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
  ; CHECK-LABEL: name: callee_v8float
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -32, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1 (%ir-block.25):
  ; CHECK-NEXT:   liveins: $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
                            <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
                            <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
                            <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
                            <8 x float>) {
  ret void
}
