; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s
; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

; The cml0 reg is used by the result type, and it overlaps with bmll0.
; Therefore, inreg %a0 cannot be passed in bml0
define inreg <16 x i64> @retcc_reserved_bm(<8 x i64> inreg %a0) {
  ; CHECK-LABEL: name: retcc_reserved_bm
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $bmll1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll1
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; CHECK-NEXT:   $cml0 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $cml0
  ret <16 x i64> zeroinitializer
}

; The cml0 reg is used by the result type.
; Therefore, %a1 cannot be passed in cml0
define inreg <16 x i64> @retcc_reserved_cm(<16 x i64> inreg %a1) {
  ; CHECK-LABEL: name: retcc_reserved_cm
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $cml1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml1
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; CHECK-NEXT:   $cml0 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $cml0
  ret <16 x i64> zeroinitializer
}

; The dm0 reg is used by the result type.
; Therefore, %a1 cannot be passed in dm0
define inreg <32 x i64> @retcc_reserved_dm(<32 x i64> inreg %a1) {
  ; CHECK-LABEL: name: retcc_reserved_dm
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $dm1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm1
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; CHECK-NEXT:   $dm0 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $dm0
  ret <32 x i64> zeroinitializer
}
