; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --print-fixed-stack
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s --check-prefixes=AIE2P,CHECK
; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s --check-prefixes=AIE2PS,CHECK


define void @callee_v8int64(<8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg,
  ; AIE2P-LABEL: name: callee_v8int64
  ; AIE2P: fixedStack:
  ; AIE2P-NEXT:   - { id: 0, type: default, offset: -64, size: 64, alignment: 64, stack-id: default, 
  ; AIE2P-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; AIE2P-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; AIE2P: bb.1 (%ir-block.21):
  ; AIE2P-NEXT:   liveins: $bmhh0, $bmhh1, $bmhh2, $bmhh3, $bmhh4, $bmhl0, $bmhl1, $bmhl2, $bmhl3, $bmhl4, $bmlh0, $bmlh1, $bmlh2, $bmlh3, $bmlh4, $bmll0, $bmll1, $bmll2, $bmll3, $bmll4
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY $bmll1
  ; AIE2P-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s64>) = COPY $bmll2
  ; AIE2P-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s64>) = COPY $bmll3
  ; AIE2P-NEXT:   [[COPY4:%[0-9]+]]:_(<8 x s64>) = COPY $bmll4
  ; AIE2P-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl0
  ; AIE2P-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl1
  ; AIE2P-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl2
  ; AIE2P-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl3
  ; AIE2P-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl4
  ; AIE2P-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh0
  ; AIE2P-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh1
  ; AIE2P-NEXT:   [[COPY12:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh2
  ; AIE2P-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh3
  ; AIE2P-NEXT:   [[COPY14:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh4
  ; AIE2P-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s64>) = COPY $bmhh0
  ; AIE2P-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s64>) = COPY $bmhh1
  ; AIE2P-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s64>) = COPY $bmhh2
  ; AIE2P-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s64>) = COPY $bmhh3
  ; AIE2P-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s64>) = COPY $bmhh4
  ; AIE2P-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; AIE2P-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s64>) from %fixed-stack.0)
  ; AIE2P-NEXT:   PseudoRET implicit $lr
  ;
  ; AIE2PS-LABEL: name: callee_v8int64
  ; AIE2PS: fixedStack:
  ; AIE2PS: bb.1 (%ir-block.21):
  ; AIE2PS-NEXT:   liveins: $bmhl0, $bmhl1, $bmhl2, $bmhl3, $bmhl4, $bmhl5, $bmhl6, $bmhl7, $bmlh0, $bmlh1, $bmlh2, $bmlh3, $bmll0, $bmll1, $bmll2, $bmll3, $bmll4, $bmll5, $bmll6, $bmll7, $x0
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
  ; AIE2PS-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY $bmll1
  ; AIE2PS-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s64>) = COPY $bmll2
  ; AIE2PS-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s64>) = COPY $bmll3
  ; AIE2PS-NEXT:   [[COPY4:%[0-9]+]]:_(<8 x s64>) = COPY $bmll4
  ; AIE2PS-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s64>) = COPY $bmll5
  ; AIE2PS-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s64>) = COPY $bmll6
  ; AIE2PS-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s64>) = COPY $bmll7
  ; AIE2PS-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl0
  ; AIE2PS-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl1
  ; AIE2PS-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl2
  ; AIE2PS-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl3
  ; AIE2PS-NEXT:   [[COPY12:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl4
  ; AIE2PS-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl5
  ; AIE2PS-NEXT:   [[COPY14:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl6
  ; AIE2PS-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s64>) = COPY $bmhl7
  ; AIE2PS-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh0
  ; AIE2PS-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh1
  ; AIE2PS-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh2
  ; AIE2PS-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s64>) = COPY $bmlh3
  ; AIE2PS-NEXT:   [[COPY20:%[0-9]+]]:_(<8 x s64>) = COPY $x0
  ; AIE2PS-NEXT:   PseudoRET implicit $lr
                             <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg,
                             <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg,
                             <8 x i64> inreg, <8 x i64> inreg, <8 x i64>) {
  ret void
}

define void @callee_v16int64(<16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg,
  ; AIE2P-LABEL: name: callee_v16int64
  ; AIE2P: fixedStack:
  ; AIE2P-NEXT:   - { id: 0, type: default, offset: -128, size: 128, alignment: 64, stack-id: default, 
  ; AIE2P-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; AIE2P-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; AIE2P: bb.1 (%ir-block.11):
  ; AIE2P-NEXT:   liveins: $cmh0, $cmh1, $cmh2, $cmh3, $cmh4, $cml0, $cml1, $cml2, $cml3, $cml4
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s64>) = COPY $cml1
  ; AIE2P-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s64>) = COPY $cml2
  ; AIE2P-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s64>) = COPY $cml3
  ; AIE2P-NEXT:   [[COPY4:%[0-9]+]]:_(<16 x s64>) = COPY $cml4
  ; AIE2P-NEXT:   [[COPY5:%[0-9]+]]:_(<16 x s64>) = COPY $cmh0
  ; AIE2P-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s64>) = COPY $cmh1
  ; AIE2P-NEXT:   [[COPY7:%[0-9]+]]:_(<16 x s64>) = COPY $cmh2
  ; AIE2P-NEXT:   [[COPY8:%[0-9]+]]:_(<16 x s64>) = COPY $cmh3
  ; AIE2P-NEXT:   [[COPY9:%[0-9]+]]:_(<16 x s64>) = COPY $cmh4
  ; AIE2P-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; AIE2P-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s64>) from %fixed-stack.0, align 64)
  ; AIE2P-NEXT:   PseudoRET implicit $lr
  ;
  ; AIE2PS-LABEL: name: callee_v16int64
  ; AIE2PS: fixedStack:
  ; AIE2PS: bb.1 (%ir-block.11):
  ; AIE2PS-NEXT:   liveins: $cmh0, $cmh1, $cml0, $cml1, $cml2, $cml3, $cml4, $cml5, $cml6, $cml7, $y2
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
  ; AIE2PS-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s64>) = COPY $cml1
  ; AIE2PS-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s64>) = COPY $cml2
  ; AIE2PS-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s64>) = COPY $cml3
  ; AIE2PS-NEXT:   [[COPY4:%[0-9]+]]:_(<16 x s64>) = COPY $cml4
  ; AIE2PS-NEXT:   [[COPY5:%[0-9]+]]:_(<16 x s64>) = COPY $cml5
  ; AIE2PS-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s64>) = COPY $cml6
  ; AIE2PS-NEXT:   [[COPY7:%[0-9]+]]:_(<16 x s64>) = COPY $cml7
  ; AIE2PS-NEXT:   [[COPY8:%[0-9]+]]:_(<16 x s64>) = COPY $cmh0
  ; AIE2PS-NEXT:   [[COPY9:%[0-9]+]]:_(<16 x s64>) = COPY $cmh1
  ; AIE2PS-NEXT:   [[COPY10:%[0-9]+]]:_(<16 x s64>) = COPY $y2
  ; AIE2PS-NEXT:   PseudoRET implicit $lr
                             <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg,
                             <16 x i64> inreg, <16 x i64>) {
  ret void
}

define void @callee_v32int64(<32 x i64> inreg, <32 x i64> inreg, <32 x i64> inreg, <32 x i64> inreg, <32 x i64> inreg,
  ; CHECK-LABEL: name: callee_v32int64
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -256, size: 256, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1 (%ir-block.6):
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $dm3, $dm4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<32 x s64>) = COPY $dm1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<32 x s64>) = COPY $dm2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<32 x s64>) = COPY $dm3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<32 x s64>) = COPY $dm4
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<32 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<32 x s64>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   PseudoRET implicit $lr
                             <32 x i64>) {
  ret void
}
