; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck -DVER=p %s --check-prefixes=AIE2P
; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck -DVER=ps %s --check-prefixes=AIE2PS

declare void @callee_v8int64(<8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg,
                             <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg,
                             <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg, <8 x i64> inreg,
                             <8 x i64> inreg)
define void @call_v8int64() {
  ; AIE2P-LABEL: name: call_v8int64
  ; AIE2P: bb.1 (%ir-block.0):
  ; AIE2P-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; AIE2P-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; AIE2P-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   $bmll0 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmll1 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmll2 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmll3 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmll4 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhl0 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhl1 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhl2 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhl3 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhl4 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmlh0 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmlh1 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmlh2 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmlh3 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmlh4 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhh0 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhh1 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhh2 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   $bmhh3 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2P-NEXT:   PseudoJL @callee_v8int64, csr_aie2p, implicit-def $lr, implicit $bmll0, implicit $bmll1, implicit $bmll2, implicit $bmll3, implicit $bmll4, implicit $bmhl0, implicit $bmhl1, implicit $bmhl2, implicit $bmhl3, implicit $bmhl4, implicit $bmlh0, implicit $bmlh1, implicit $bmlh2, implicit $bmlh3, implicit $bmlh4, implicit $bmhh0, implicit $bmhh1, implicit $bmhh2, implicit $bmhh3
  ; AIE2P-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   PseudoRET implicit $lr
  ;
  ; AIE2PS-LABEL: name: call_v8int64
  ; AIE2PS: bb.1 (%ir-block.0):
  ; AIE2PS-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; AIE2PS-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; AIE2PS-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   $bmll0 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmll1 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmll2 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmll3 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmll4 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmll5 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmll6 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmll7 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl0 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl1 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl2 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl3 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl4 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl5 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl6 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmhl7 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmlh0 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmlh1 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   $bmlh2 = COPY [[BUILD_VECTOR]](<8 x s64>)
  ; AIE2PS-NEXT:   PseudoJL @callee_v8int64, csr_aie2ps, implicit-def $lr, implicit $bmll0, implicit $bmll1, implicit $bmll2, implicit $bmll3, implicit $bmll4, implicit $bmll5, implicit $bmll6, implicit $bmll7, implicit $bmhl0, implicit $bmhl1, implicit $bmhl2, implicit $bmhl3, implicit $bmhl4, implicit $bmhl5, implicit $bmhl6, implicit $bmhl7, implicit $bmlh0, implicit $bmlh1, implicit $bmlh2
  ; AIE2PS-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   PseudoRET implicit $lr
  call void @callee_v8int64(<8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer,
                            <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer,
                            <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer, <8 x i64> inreg zeroinitializer,
                            <8 x i64> inreg zeroinitializer)
  ret void
}

declare void @callee_v16int64(<16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg,
                             <16 x i64> inreg, <16 x i64> inreg, <16 x i64> inreg,
                             <16 x i64> inreg)
define void @call_v16int64() {
  ; AIE2P-LABEL: name: call_v16int64
  ; AIE2P: bb.1 (%ir-block.0):
  ; AIE2P-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; AIE2P-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; AIE2P-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   $cml0 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cml1 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cml2 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cml3 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cml4 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cmh0 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cmh1 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cmh2 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cmh3 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   $cmh4 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2P-NEXT:   PseudoJL @callee_v16int64, csr_aie2p, implicit-def $lr, implicit $cml0, implicit $cml1, implicit $cml2, implicit $cml3, implicit $cml4, implicit $cmh0, implicit $cmh1, implicit $cmh2, implicit $cmh3, implicit $cmh4
  ; AIE2P-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   PseudoRET implicit $lr
  ;
  ; AIE2PS-LABEL: name: call_v16int64
  ; AIE2PS: bb.1 (%ir-block.0):
  ; AIE2PS-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; AIE2PS-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; AIE2PS-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   $cml0 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cml1 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cml2 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cml3 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cml4 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cml5 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cml6 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cml7 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cmh0 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   $cmh1 = COPY [[BUILD_VECTOR]](<16 x s64>)
  ; AIE2PS-NEXT:   PseudoJL @callee_v16int64, csr_aie2ps, implicit-def $lr, implicit $cml0, implicit $cml1, implicit $cml2, implicit $cml3, implicit $cml4, implicit $cml5, implicit $cml6, implicit $cml7, implicit $cmh0, implicit $cmh1
  ; AIE2PS-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   PseudoRET implicit $lr
  call void @callee_v16int64(<16 x i64> inreg zeroinitializer, <16 x i64> inreg zeroinitializer, <16 x i64> inreg zeroinitializer, <16 x i64> inreg zeroinitializer, <16 x i64> inreg zeroinitializer, <16 x i64> inreg zeroinitializer,
                            <16 x i64> inreg zeroinitializer, <16 x i64> inreg zeroinitializer, <16 x i64> inreg zeroinitializer,
                            <16 x i64> inreg zeroinitializer)
  ret void
}

; Add check for
declare void @callee_v32int64(<32 x i64> inreg, <32 x i64> inreg, <32 x i64> inreg,
                              <32 x i64> inreg, <32 x i64> inreg)
define void @call_v32int64() {
  ; AIE2P-LABEL: name: call_v32int64
  ; AIE2P: bb.1 (%ir-block.0):
  ; AIE2P-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; AIE2P-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; AIE2P-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   $dm0 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2P-NEXT:   $dm1 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2P-NEXT:   $dm2 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2P-NEXT:   $dm3 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2P-NEXT:   $dm4 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2P-NEXT:   PseudoJL @callee_v32int64, csr_aie2p, implicit-def $lr, implicit $dm0, implicit $dm1, implicit $dm2, implicit $dm3, implicit $dm4
  ; AIE2P-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   PseudoRET implicit $lr
  ;
  ; AIE2PS-LABEL: name: call_v32int64
  ; AIE2PS: bb.1 (%ir-block.0):
  ; AIE2PS-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; AIE2PS-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64), [[C]](s64)
  ; AIE2PS-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   $dm0 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2PS-NEXT:   $dm1 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2PS-NEXT:   $dm2 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2PS-NEXT:   $dm3 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2PS-NEXT:   $dm4 = COPY [[BUILD_VECTOR]](<32 x s64>)
  ; AIE2PS-NEXT:   PseudoJL @callee_v32int64, csr_aie2ps, implicit-def $lr, implicit $dm0, implicit $dm1, implicit $dm2, implicit $dm3, implicit $dm4
  ; AIE2PS-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   PseudoRET implicit $lr
  call void @callee_v32int64(<32 x i64> inreg zeroinitializer, <32 x i64> inreg zeroinitializer, <32 x i64>  inreg zeroinitializer,
                            <32 x i64> inreg zeroinitializer, <32 x i64> inreg zeroinitializer)
  ret void
}

