; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2 %s -o - | FileCheck %s

define dso_local noundef signext i8 @_Z11test_selectbcc(i1 noundef zeroext %sel, i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_selectbcc:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r27, r1 // Delay Slot 3
; CHECK-NEXT:    sel.nez r0, r2, r3, r27 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cond.i = select i1 %sel, i8 %a, i8 %b
  ret i8 %cond.i
}

define dso_local noundef signext i16 @_Z11test_selectbss(i1 noundef zeroext %sel, i16 noundef signext %a, i16 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_selectbss:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r27, r1 // Delay Slot 3
; CHECK-NEXT:    sel.nez r0, r2, r3, r27 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cond.i = select i1 %sel, i16 %a, i16 %b
  ret i16 %cond.i
}

define dso_local noundef i32 @_Z11test_selectbii(i1 noundef zeroext %sel, i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_selectbii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r27, r1 // Delay Slot 3
; CHECK-NEXT:    sel.nez r0, r2, r3, r27 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cond.i = select i1 %sel, i32 %a, i32 %b
  ret i32 %cond.i
}

define dso_local ptr @_Z11test_selectbPvS_(i1 noundef zeroext %sel, ptr readnone %a, ptr readnone %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_selectbPvS_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; ret lr ; nopm
; CHECK-NEXT:    or r27, r0, r0; mov r0, p1 // Delay Slot 5
; CHECK-NEXT:    mov r1, p2 // Delay Slot 4
; CHECK-NEXT:    sel.nez r0, r0, r1, r27 // Delay Slot 3
; CHECK-NEXT:    mov p0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cond.i = select i1 %sel, ptr %a, ptr %b
  ret ptr %cond.i
}
