; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc < %s  --issue-limit=1 -verify-machineinstrs -mtriple=aie2 \
; RUN:   | FileCheck %s
define dso_local void @_Z12pass_v2int32x(i64 noundef %a) local_unnamed_addr #0 {
; CHECK-LABEL: _Z12pass_v2int32x:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret void
}

define dso_local noundef i64 @_Z14return_v2int32v() local_unnamed_addr #0 {
; CHECK-LABEL: _Z14return_v2int32v:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mova r0, #100 // Delay Slot 3
; CHECK-NEXT:    mova r1, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret i64 100
}

define dso_local noundef i64 @_Z19pass_return_int64_t(i64 noundef %a) local_unnamed_addr #0 {
; CHECK-LABEL: _Z19pass_return_int64_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; CHECK-NEXT:    mova r1, #100 // Delay Slot 5
; CHECK-NEXT:    add r0, r2, r1 // Delay Slot 4
; CHECK-NEXT:    ltu r1, r0, r1 // Delay Slot 3
; CHECK-NEXT:    add r1, r3, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %add = add nsw i64 %a, 100
  ret i64 %add
}
