; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2 %s -o - | FileCheck %s

%class.bfloat16 = type { bfloat }

define dso_local noundef float @bfloat16_to_float_test(%class.bfloat16 %bf.coerce) {
; CHECK-LABEL: bfloat16_to_float_test:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mova r0, #16; extend.u16 r1, r1 // Delay Slot 2
; CHECK-NEXT:    lshl r0, r1, r0 // Delay Slot 1
entry:
  %bf.coerce.fca.0.extract = extractvalue %class.bfloat16 %bf.coerce, 0
  %0 = bitcast bfloat %bf.coerce.fca.0.extract to i16
  %conv2.i = zext i16 %0 to i32
  %shl.i = shl nuw i32 %conv2.i, 16
  %1 = bitcast i32 %shl.i to float
  ret float %1
}
