; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; Test instruction selection of insertelement <4 x i8> chains (build_vector)
; that pack 4 byte loads into a 32-bit word with a scalar store.
;
; RUN: llc -O2 -mtriple=aie2ps --issue-limit=1 %s -o - | FileCheck %s

; Build <4 x i8> from 4 byte loads via separate pointers, then scalar store.
define void @build_v4i8_from_ptrs(ptr nocapture readonly %p0, ptr nocapture readonly %p1, ptr nocapture readonly %p2, ptr nocapture readonly %p3, ptr nocapture writeonly %dst) {
; CHECK-LABEL: build_v4i8_from_ptrs:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda.u8 r0, [p1, #0]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    lda.u8 r2, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda.s8 r4, [p2, #0]
; CHECK-NEXT:    lda.s8 r6, [p3, #0]
; CHECK-NEXT:    mova r16, #8
; CHECK-NEXT:    movx r29, #2
; CHECK-NEXT:    lshl r0, r0, r16
; CHECK-NEXT:    or r0, r2, r0
; CHECK-NEXT:    vinsert.32 x0, x0, #0, r0
; CHECK-NEXT:    vinsert.8 x0, x0, r29, r4
; CHECK-NEXT:    mova r29, #3
; CHECK-NEXT:    vinsert.8 x0, x0, r29, r6
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vextract.32 r0, x0, #0, vaddsign1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    st r0, [p4, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = load i8, ptr %p0, align 1
  %vecinit = insertelement <4 x i8> poison, i8 %0, i64 0
  %1 = load i8, ptr %p1, align 1
  %vecinit1 = insertelement <4 x i8> %vecinit, i8 %1, i64 1
  %2 = load i8, ptr %p2, align 1
  %vecinit2 = insertelement <4 x i8> %vecinit1, i8 %2, i64 2
  %3 = load i8, ptr %p3, align 1
  %vecinit3 = insertelement <4 x i8> %vecinit2, i8 %3, i64 3
  store <4 x i8> %vecinit3, ptr %dst, align 4
  ret void
}

; Build <4 x i8> from scalar function arguments (no loads), then scalar store.
define void @build_v4i8_from_scalars(i8 %a, i8 %b, i8 %c, i8 %d, ptr nocapture writeonly %dst) {
; CHECK-LABEL: build_v4i8_from_scalars:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; extend.u8 r4, r1; nopm
; CHECK-NEXT:    extend.u8 r0, r0
; CHECK-NEXT:    mova r6, #8
; CHECK-NEXT:    mova r29, #2
; CHECK-NEXT:    lshl r4, r4, r6
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    vinsert.32 x0, x0, #0, r0
; CHECK-NEXT:    vinsert.8 x0, x0, r29, r2
; CHECK-NEXT:    mova r29, #3
; CHECK-NEXT:    vinsert.8 x0, x0, r29, r3
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vextract.32 r0, x0, #0, vaddsign1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    st r0, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecinit = insertelement <4 x i8> poison, i8 %a, i64 0
  %vecinit1 = insertelement <4 x i8> %vecinit, i8 %b, i64 1
  %vecinit2 = insertelement <4 x i8> %vecinit1, i8 %c, i64 2
  %vecinit3 = insertelement <4 x i8> %vecinit2, i8 %d, i64 3
  store <4 x i8> %vecinit3, ptr %dst, align 4
  ret void
}
