# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2 -start-after=irtranslator -stop-after=virtregrewriter %s -o - | FileCheck %s

# l0 is used and not preserved by JL, make sure its original value is preserved
# through another CSR.
---
name:            l0_arg
calleeSavedRegisters: [ '$lr', '$r20', '$r21', '$r22', '$r23', '$p6', '$p7' ]
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $l0

    ; CHECK-LABEL: name: l0_arg
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $l1 = COPY $l0
    ; CHECK-NEXT: $l0 = COPY renamable $l1
    ; CHECK-NEXT: PseudoJL 0, CustomRegMask($lr,$l1,$l2,$l3,$p6,$p7,$r18,$r19,$r20,$r21,$r22,$r23), implicit-def $lr, implicit $l0
    ; CHECK-NEXT: $l0 = COPY killed renamable $l1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l0
    %0:el = COPY $l0
    $l0 = COPY %0
    PseudoJL 0, CustomRegMask($lr,$l1,$l2,$l3,$p6,$p7,$r18,$r19,$r20,$r21,$r22,$r23), implicit-def $lr, implicit $l0
    $l0 = COPY %0
    PseudoRET implicit $lr, implicit $l0
...

# l0 is re-defined by JL (and not part of its preserved regmask), make sure its
# original value is preserved through another CSR.
---
name:            l0_return_arg
calleeSavedRegisters: [ '$lr', '$r20', '$r21', '$r22', '$r23', '$p6', '$p7' ]
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $l0

    ; CHECK-LABEL: name: l0_return_arg
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $l1 = COPY $l0
    ; CHECK-NEXT: PseudoJL 0, CustomRegMask($lr,$l1,$l2,$l3,$p6,$p7,$r18,$r19,$r20,$r21,$r22,$r23), implicit-def $lr, implicit-def dead $l0
    ; CHECK-NEXT: $l0 = COPY killed renamable $l1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l0
    %0:el = COPY $l0
    PseudoJL 0, CustomRegMask($lr,$l1,$l2,$l3,$p6,$p7,$r18,$r19,$r20,$r21,$r22,$r23), implicit-def $lr, implicit-def $l0
    $l0 = COPY %0
    PseudoRET implicit $lr, implicit $l0
...
