; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2 -global-isel -verify-machineinstrs -o - < %s | FileCheck %s


define i128 @test_i128(i128 %q) {
; CHECK-LABEL: test_i128:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov q0, q2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret i128 %q
}

define i128 @test_i128_spill(i128 %q) {
; CHECK-LABEL: test_i128_spill:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; jl #f; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    paddb [sp], #32 // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-16] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    st q2, [sp, #-32] // 16-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    nopb ; lda lr, [sp, #-16]; nops ; nopxm ; nopv // 4-byte Folded Reload
; CHECK-NEXT:    nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda q0, [sp, #-32] // 16-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddb [sp], #-32 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  call void @f()
  ret i128 %q
}

declare void @f()
