; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 -global-isel -verify-machineinstrs -o - < %s | FileCheck %s

; Verify 64-bit types are passed in the right registers after casting.

define i64 @test_i64(<2 x i32> %x) {
; CHECK-LABEL: test_i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    or r0, r16, r16; mov r1, r17 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cast = bitcast <2 x i32> %x to i64
  ret i64 %cast
}

define <2 x i32> @test_v2i32(i64 %x) {
; CHECK-LABEL: test_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    or r16, r0, r0; mov r17, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cast = bitcast i64 %x to <2 x i32>
  ret <2 x i32> %cast
}
