; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 -global-isel -verify-machineinstrs -o - < %s | FileCheck %s

; NOTE: both versions for the second operand of the builtin are covered by CLZ

define i32 @f(i32 %x) {
; CHECK-LABEL: f:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    clz r0, r1 // Delay Slot 1
entry:
  %0 = call i32 @llvm.ctlz.i32(i32 %x, i1 true)
  ret i32 %0
}

declare i32 @llvm.ctlz.i32(i32, i1 immarg)
