# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2 -run-pass detect-dead-lanes -o - %s | FileCheck %s

---
name: vec512
body: |
  bb.0:
    liveins: $wl0, $wh0
    ; CHECK-LABEL: name: vec512
    ; CHECK: liveins: $wl0, $wh0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY]], %subreg.sub_256_lo, [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vec256 = COPY $wl0
    %2:vec256 = COPY $wh0
    %3:vec512 = REG_SEQUENCE %1, %subreg.sub_256_lo, %2, %subreg.sub_256_hi
    $x0 = COPY %3
    PseudoRET implicit $lr, implicit $x0
...

---
name: vec1024
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vec1024
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[COPY]], %subreg.sub_512_lo, [[COPY1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y2 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vec512 = COPY $x0
    %2:vec512 = COPY $x1
    %3:vec1024 = REG_SEQUENCE %1, %subreg.sub_512_lo, %2, %subreg.sub_512_hi
    $y2 = COPY %3
    PseudoRET implicit $lr, implicit $y2
...

---
name: acc512
body: |
  bb.0:
    liveins: $amll0, $amlh0
    ; CHECK-LABEL: name: acc512
    ; CHECK: liveins: $amll0, $amlh0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc256 = COPY $amll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc256 = COPY $amlh0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc512 = REG_SEQUENCE [[COPY]], %subreg.sub_256_lo, [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $bml0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:acc256 = COPY $amll0
    %2:acc256 = COPY $amlh0
    %3:acc512 = REG_SEQUENCE %1, %subreg.sub_256_lo, %2, %subreg.sub_256_hi
    $bml0 = COPY %3
    PseudoRET implicit $lr, implicit $x0
...

---
name: acc1024
body: |
  bb.0:
    liveins: $bml0, $bmh0

    ; CHECK-LABEL: name: acc1024
    ; CHECK: liveins: $bml0, $bmh0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmh0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[COPY]], %subreg.sub_512_lo, [[COPY1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $cm0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %1:acc512 = COPY $bml0
    %2:acc512 = COPY $bmh0
    %3:acc1024 = REG_SEQUENCE %1, %subreg.sub_512_lo, %2, %subreg.sub_512_hi
    $cm0 = COPY %3
    PseudoRET implicit $lr, implicit $cm0
...
