; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -O2 -mtriple=aie2 %s -o - | FileCheck %s

define bfloat @test_fadd_bfloat(bfloat %a, bfloat %b) {
; CHECK-LABEL: test_fadd_bfloat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r16, #0; nops ; movx r0, #16; mov r3, r16; nopv
; CHECK-NEXT:    lshl r1, r1, r0; mov r29, r16
; CHECK-NEXT:    lshl r0, r2, r0; vinsert.32 x0, x0, r29, r1
; CHECK-NEXT:    vinsert.32 x2, x0, r29, r0
; CHECK-NEXT:    mova r0, #28; vmov bmh0, x0
; CHECK-NEXT:    vmov bmh1, x2; vadd.f bmh0, bmh0, bmh1, r0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 wl0, bmh0; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vextract.s16 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %fadd = fadd bfloat %a, %b
  ret bfloat %fadd
}

define float @test_fadd_float(float %a, float %b) {
; CHECK-LABEL: test_fadd_float:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r16, #0; nopx ; mov r3, r16
; CHECK-NEXT:    mov r29, r16
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r1
; CHECK-NEXT:    vinsert.32 x2, x0, r29, r2
; CHECK-NEXT:    mova r0, #28; vmov bmh0, x0
; CHECK-NEXT:    vmov bmh1, x2; vadd.f bmh0, bmh0, bmh1, r0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vmov x0, bmh0 // Delay Slot 5
; CHECK-NEXT:    vextract.s32 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %fadd = fadd float %a, %b
  ret float %fadd
}

define double @test_fadd_double(double %a, double %b) {
; CHECK-LABEL: test_fadd_double:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; jl #__adddf3; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    paddb [sp], #32 // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-32] // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddb [sp], #-32 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %fadd = fadd double %a, %b
  ret double %fadd
}
