; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -O2 -mtriple=aie2 %s -o - | FileCheck %s

define bfloat @test_frem_bfloat(bfloat %a, bfloat %b) {
; CHECK-LABEL: test_frem_bfloat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; jl #fmodf
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    paddb [sp], #32 // Delay Slot 4
; CHECK-NEXT:    mova r0, #16; st lr, [sp, #-32] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    st r16, [sp, #-28]; lshl r1, r1, r0 // 4-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    lshl r2, r2, r0 // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-32] // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova r16, #0
; CHECK-NEXT:    mov r29, r16
; CHECK-NEXT:    lda r16, [sp, #-28]; vinsert.32 x0, x0, r29, r0 // 4-byte Folded Reload
; CHECK-NEXT:    ret lr ; vmov bmh0, x0
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vconv.bf16.fp32 wl0, bmh0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddb [sp], #-32; vextract.s16 r0, x0, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %frem = frem bfloat %a, %b
  ret bfloat %frem
}

define float @test_frem_float(float %a, float %b) {
; CHECK-LABEL: test_frem_float:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; jl #fmodf; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    paddb [sp], #32 // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-32] // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddb [sp], #-32 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %frem = frem float %a, %b
  ret float %frem
}

define double @test_frem_double(double %a, double %b) {
; CHECK-LABEL: test_frem_double:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; jl #fmod; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    paddb [sp], #32 // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-32] // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddb [sp], #-32 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %frem = frem double %a, %b
  ret double %frem
}
