# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass postrapseudos -verify-machineinstrs -o - %s | FileCheck %s

# Verify AIE2InstrInfo.cpp: copyPhysReg()

---
name:     test_copy_d
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_d
    ; CHECK: $m1 = MOV_mv_scl $m2
    ; CHECK-NEXT: $dn1 = MOV_mv_scl $dn2
    ; CHECK-NEXT: $dj1 = MOV_mv_scl $dj2
    ; CHECK-NEXT: $dc1 = MOV_mv_scl $dc2
  $d1 = COPY $d2
...

---
name:     test_copy_ds
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ds
    ; CHECK: $dc1 = MOV_mv_scl $dc2
    ; CHECK-NEXT: $dn1 = MOV_mv_scl $dn2
    ; CHECK-NEXT: $dj1 = MOV_mv_scl $dj2
    ; CHECK-NEXT: $m1 = MOV_mv_scl $m2
    ; CHECK-NEXT: $dc5 = MOV_mv_scl $dc6
    ; CHECK-NEXT: $dn5 = MOV_mv_scl $dn6
    ; CHECK-NEXT: $dj5 = MOV_mv_scl $dj6
  $d1_3d = COPY $d2_3d
...

---
name:     test_copy_w
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_w
    ; CHECK: $wh0 = VMOV_mv_w $wh1
    ; CHECK-NEXT: $wl1 = VMOV_mv_w $wh2
    ; CHECK-NEXT: $wh11 = VMOV_mv_w $wl10
    ; CHECK-NEXT: $wl1 = VMOV_mv_w $amhh8
    ; CHECK-NEXT: $wh5 = VMOV_mv_w $amlh4
    ; CHECK-NEXT: $amll0 = VMOV_mv_w $wl5
    ; CHECK-NEXT: $amhl7 = VMOV_mv_w $wh3
    ; CHECK-NEXT: $amhl7 = VMOV_mv_w $amhh8
    ; CHECK-NEXT: $amll2 = VMOV_mv_w $amhl4
    ; CHECK-NEXT: $amlh1 = VMOV_mv_w $amll3
  $wh0 = COPY $wh1
  $wl1 = COPY $wh2
  $wh11 = COPY $wl10
  $wl1 = COPY $amhh8
  $wh5 = COPY $amlh4
  $amll0 = COPY $wl5
  $amhl7 = COPY $wh3
  $amhl7 = COPY $amhh8
  $amll2 = COPY $amhl4
  $amlh1 = COPY $amll3
...

---
name:             test_copy_x
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_x
    ; CHECK: $x1 = VMOV_mv_x $x4
    ; CHECK-NEXT: $x2 = VMOV_mv_x $x3
    ; CHECK-NEXT: $x10 = VMOV_mv_x $x8
    ; CHECK-NEXT: $x3 = VMOV_mv_x $bml0
    ; CHECK-NEXT: $x4 = VMOV_mv_x $bmh3
    ; CHECK-NEXT: $x11 = VMOV_mv_x $bmh8
    ; CHECK-NEXT: $bmh2 = VMOV_mv_x $x1
    ; CHECK-NEXT: $bml1 = VMOV_mv_x $x2
    ; CHECK-NEXT: $bmh5 = VMOV_mv_x $x9
    ; CHECK-NEXT: $bml3 = VMOV_mv_x $bml0
    ; CHECK-NEXT: $bmh4 = VMOV_mv_x $bmh3
    ; CHECK-NEXT: $bml1 = VMOV_mv_x $bmh8
  $x1 = COPY $x4
  $x2 = COPY $x3
  $x10 = COPY $x8
  $x3 = COPY $bml0
  $x4 = COPY $bmh3
  $x11 = COPY $bmh8
  $bmh2 = COPY $x1
  $bml1 = COPY $x2
  $bmh5 = COPY $x9
  $bml3 = COPY $bml0
  $bmh4 = COPY $bmh3
  $bml1 = COPY $bmh8
...

---
name:             test_copy_cm
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_cm
    ; CHECK: $cm1 = VMOV_mv_cm $cm4
    ; CHECK-NEXT: $cm2 = VMOV_mv_cm $cm3
    ; CHECK-NEXT: $cm0 = VMOV_mv_cm $cm8
  $cm1 = COPY $cm4
  $cm2 = COPY $cm3
  $cm0 = COPY $cm8
...

---
name:            test_copy_y
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_y
    ; CHECK: $x4 = VMOV_mv_x $x8
    ; CHECK-NEXT: $x5 = VMOV_mv_x $x9
    ; CHECK-NEXT: $x6 = VMOV_mv_x $x10
    ; CHECK-NEXT: $x7 = VMOV_mv_x $x11
  $y2 = COPY $y4
  $y3 = COPY $y5
...

---
name:            test_copy_y_cm
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_y_cm
    ; CHECK: $x4 = VMOV_mv_x $bml0
    ; CHECK-NEXT: $x5 = VMOV_mv_x $bmh0
    ; CHECK-NEXT: $bml1 = VMOV_mv_x $x10
    ; CHECK-NEXT: $bmh1 = VMOV_mv_x $x11
  $y2  = COPY $cm0
  $cm1 = COPY $y5
...

---
name:            test_copy_l
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_l
    ; CHECK: $r18 = MOV_mv_scl $r20
    ; CHECK-NEXT: $r19 = MOV_mv_scl $r21
  $l1 = COPY $l2
...

---
name:            test_copy_qx
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_qx
    ; CHECK: $x0 = VMOV_mv_x $x1
    ; CHECK-NEXT: $q0 = VMOV_mv_w $q1
  $qx0 = COPY $qx1
...
