; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2 %s --issue-limit=1 -o - | FileCheck %s

define <16 x float> @test_broadcast_float(float %b) {
; CHECK-LABEL: test_broadcast_float:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast float %b to i32
  %1 = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 %0)
  %2 = bitcast <16 x i32> %1 to <16 x float>
  ret <16 x float> %2
}

define float @test_extract_elem_floatv16(<16 x float> %v, i32 %idx, i32 %sign) {
; CHECK-LABEL: test_extract_elem_floatv16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov r3, r16
; CHECK-NEXT:    mov r16, r1
; CHECK-NEXT:    mov crVaddSign, r2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vextract.d32 r0, x0, r16 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crVaddSign, #0 // Delay Slot 3
; CHECK-NEXT:    mov r16, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x float> %v to <16 x i32>
  %1 = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> %0, i32 %idx, i32 %sign)
  %2 = bitcast i32 %1 to float
  ret float %2
}

declare <16 x i32> @llvm.aie2.vbroadcast32.I512(i32)
declare i32 @llvm.aie2.vextract.elem32.I512(<16 x i32>, i32, i32)
