; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 --mtriple=aie2 --filetype=asm -o - %s | FileCheck %s

define void @test(i8 %a, i32 %b) {
; CHECK-LABEL: test:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova p0, #0
; CHECK-NEXT:    st.s8 r3, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova r2, #1; eqz r1, r1
; CHECK-NEXT:    xor r3, r1, r2
; CHECK-NEXT:    lshl r3, r3, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.s8 r1, [p0, #0]
; CHECK-NEXT:    mova r3, #0; extend.u8 r0, r0
; CHECK-NEXT:    ltu r0, r3, r0
; CHECK-NEXT:    and r1, r1, r0
; CHECK-NEXT:    xor r1, r1, r2
; CHECK-NEXT:    lshl r1, r1, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.s16 r0, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    xor r0, r0, r2 // Delay Slot 4
; CHECK-NEXT:    lshl r0, r0, r2 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp0 = icmp eq i32 %b, 0
  %sel0 = select i1 %cmp0, i8 0, i8 2
  store i8 %sel0, ptr null, align 32
  %cmp1 = icmp ugt i8 %a, 0
  %sel1 = select i1 %cmp0, i1 %cmp1, i1 false
  %sel2 = select i1 %sel1, i8 0, i8 2
  store i8 %sel2, ptr null, align 2
  %sel3 = select i1 %cmp1, i16 0, i16 2
  store i16 %sel3, ptr null, align 2
  ret void
}
