; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2 %s -o - | FileCheck %s


define dso_local noundef <64 x i8> @_Z17test_broadcast_s8c(i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z17test_broadcast_s8c:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.8 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i = sext i8 %b to i32
  %0 = tail call <64 x i8> @llvm.aie2.vbroadcast8.I512(i32 %conv.i)
  ret <64 x i8> %0
}

define dso_local noundef <32 x i16> @_Z18test_broadcast_s16s(i16 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z18test_broadcast_s16s:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.16 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i = sext i16 %b to i32
  %0 = tail call <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 %conv.i)
  ret <32 x i16> %0
}

define dso_local noundef <16 x i32> @_Z18test_broadcast_s32i(i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z18test_broadcast_s32i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <16 x i32> @llvm.aie2.vbroadcast32.I512(i32 %b)
  ret <16 x i32> %0
}

define dso_local noundef <16 x i32> @_Z27test_broadcast_to_v16uint32y(i64 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: _Z27test_broadcast_to_v16uint32y:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    or r24, r0, r0; mov r25, r1 // Delay Slot 3
; CHECK-NEXT:    vbcst.64 x0, r25:r24 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast i64 %b to <2 x i32>
  %1 = tail call <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32> %0)
  ret <16 x i32> %1
}


declare <64 x i8> @llvm.aie2.vbroadcast8.I512(i32) #1
declare <32 x i16> @llvm.aie2.vbroadcast16.I512(i32) #1
declare <16 x i32> @llvm.aie2.vbroadcast32.I512(i32) #1
declare <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32>) #1
