; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2 --issue-limit=1 %s -o - | FileCheck %s

define dso_local noundef signext i32 @_Z15test_ext_v2int4Dv16_iii(<16 x i32> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr #0 {
; CHECK-LABEL: _Z15test_ext_v2int4Dv16_iii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov r1, r16
; CHECK-NEXT:    mova r16, #63
; CHECK-NEXT:    mov crVaddSign, r2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vextract.d8 r0, x0, r16 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crVaddSign, #0 // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x i32> %v to <64 x i8>
  %1 = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> %0, i32 63, i32 %sign)
  ret i32 %1
}


define dso_local noundef signext i32 @_Z15test_ext_v4int4Dv16_iii(<16 x i32> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr #0 {
; CHECK-LABEL: _Z15test_ext_v4int4Dv16_iii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov r1, r16
; CHECK-NEXT:    mova r16, #50
; CHECK-NEXT:    mov crVaddSign, r2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vextract.d16 r0, x0, r16 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crVaddSign, #0 // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x i32> %v to <32 x i16>
  %1 = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> %0, i32 50, i32 %sign)
  ret i32 %1
}


define dso_local noundef i32 @_Z15test_ext_v8int4Dv16_iii(<16 x i32> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr #0 {
; CHECK-LABEL: _Z15test_ext_v8int4Dv16_iii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov r1, r16
; CHECK-NEXT:    mova r16, #10
; CHECK-NEXT:    mov crVaddSign, r2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vextract.d32 r0, x0, r16 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crVaddSign, #0 // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> %v, i32 10, i32 %sign)
  ret i32 %0
}


define dso_local noundef signext i32 @_Z21test_ext_v2int4_sign1Dv16_ii(<16 x i32> noundef %v, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_ext_v2int4_sign1Dv16_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r1, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r16, #6 // Delay Slot 5
; CHECK-NEXT:    vextract.s8 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x i32> %v to <64 x i8>
  %1 = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> %0, i32 6, i32 1)
  ret i32 %1
}


define dso_local noundef signext i32 @_Z21test_ext_v4int4_sign1Dv16_ii(<16 x i32> noundef %v, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_ext_v4int4_sign1Dv16_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r1, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r16, #5 // Delay Slot 5
; CHECK-NEXT:    vextract.s16 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x i32> %v to <32 x i16>
  %1 = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> %0, i32 5, i32 1)
  ret i32 %1
}


define dso_local noundef i32 @_Z21test_ext_v8int4_sign1Dv16_ii(<16 x i32> noundef %v, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_ext_v8int4_sign1Dv16_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r1, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r16, #1 // Delay Slot 5
; CHECK-NEXT:    vextract.s32 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> %v, i32 1, i32 1)
  ret i32 %0
}


define dso_local noundef signext i32 @_Z21test_ext_v2int4_sign0Dv16_ii(<16 x i32> noundef %v, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_ext_v2int4_sign0Dv16_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r1, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r16, #16 // Delay Slot 5
; CHECK-NEXT:    vextract.d8 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x i32> %v to <64 x i8>
  %1 = tail call i32 @llvm.aie2.vextract.elem8.I512(<64 x i8> %0, i32 16, i32 0)
  ret i32 %1
}


define dso_local noundef signext i32 @_Z21test_ext_v4int4_sign0Dv16_ii(<16 x i32> noundef %v, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_ext_v4int4_sign0Dv16_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r1, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r16, #51 // Delay Slot 5
; CHECK-NEXT:    vextract.d16 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x i32> %v to <32 x i16>
  %1 = tail call i32 @llvm.aie2.vextract.elem16.I512(<32 x i16> %0, i32 51, i32 0)
  ret i32 %1
}


define dso_local noundef i32 @_Z21test_ext_v8int4_sign0Dv16_ii(<16 x i32> noundef %v, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_ext_v8int4_sign0Dv16_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r1, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r16, #41 // Delay Slot 5
; CHECK-NEXT:    vextract.d32 r0, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r16, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call i32 @llvm.aie2.vextract.elem32.I512(<16 x i32> %v, i32 41, i32 0)
  ret i32 %0
}

define dso_local noundef <8 x i8> @_Z16test_ext_v16int4Dv64_DB8_ii(<64 x i8> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr #0 {
; CHECK-LABEL: _Z16test_ext_v16int4Dv64_DB8_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r16, #1; nopb ; nopxm
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mov crVaddSign, r1 // Delay Slot 5
; CHECK-NEXT:    vextract.d64 r17:r16, x0, r16 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov crVaddSign, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> %0, i32 1, i32 %sign)
  %2 = bitcast <2 x i32> %1 to <8 x i8>
  ret <8 x i8> %2
}

define dso_local noundef i64 @_Z12test_ext_u64Dv16_iii(<16 x i32> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr #0 {
; CHECK-LABEL: _Z12test_ext_u64Dv16_iii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r4, r16; nops
; CHECK-NEXT:    mov r16, r2
; CHECK-NEXT:    mov crVaddSign, r3
; CHECK-NEXT:    vextract.d64 r25:r24, x0, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mov crVaddSign, #0 // Delay Slot 5
; CHECK-NEXT:    mov r16, r4 // Delay Slot 4
; CHECK-NEXT:    mov r0, r24 // Delay Slot 3
; CHECK-NEXT:    mov r1, r25 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> %v, i32 %idx, i32 %sign)
  %1 = bitcast <2 x i32> %0 to i64
  ret i64 %1
}

declare i32 @llvm.aie2.vextract.elem8.I512(<64 x i8>, i32, i32) #1
declare i32 @llvm.aie2.vextract.elem16.I512(<32 x i16>, i32, i32) #1
declare i32 @llvm.aie2.vextract.elem32.I512(<16 x i32>, i32, i32) #1
declare <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32>, i32, i32) #1
