; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 --issue-limit=1 -verify-machineinstrs -o - < %s \
; RUN:   | FileCheck %s
define  <16 x i64> @_Z18test_mul_4x16_16x8v() {
; CHECK-LABEL: _Z18test_mul_4x16_16x8v:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r0, #0; nops ; nopxm ; nopv
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vmul cm0, x0, x0, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <64 x i8> @llvm.aie2.v64int8()
  %1 = tail call <16 x i32> @llvm.aie2.v16int32()
  %2 = tail call <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8> %0, <16 x i32> %1, i32 0)
  ret <16 x i64> %2
}


define  <16 x i64> @_Z26test_mul_conv_8x8_4ch_confDv64_aDv64_h(<64 x i8> noundef %a, <64 x i8> noundef %b)  {
; CHECK-LABEL: _Z26test_mul_conv_8x8_4ch_confDv64_aDv64_h:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; movxm r0, #2408; nopv
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vmul cm0, x0, x2, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %b to <16 x i32>
  %1 = tail call <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8> %a, <16 x i32> %0, i32 2408)
  ret <16 x i64> %1
}

define  <16 x i64> @_Z3mulDv32_tS_(<32 x i16> noundef %a, <32 x i16> noundef %b)  {
; CHECK-LABEL: _Z3mulDv32_tS_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r0, #56; nops ; nopxm ; nopv
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vmul cm0, x0, x2, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x i16> %a to <64 x i8>
  %1 = bitcast <32 x i16> %b to <16 x i32>
  %2 = tail call <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8> %0, <16 x i32> %1, i32 56)
  ret <16 x i64> %2
}

define <16 x i64> @_Z16test_mul_2x8_8x8v() {
; CHECK-LABEL: _Z16test_mul_2x8_8x8v:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r0, #274; nops ; nopxm ; nopv
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vmul cm0, x0, x0, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <32 x i16> @llvm.aie2.v32int16()
  %1 = tail call <64 x i8> @llvm.aie2.v64int8()
  %2 = bitcast <32 x i16> %0 to <64 x i8>
  %3 = bitcast <64 x i8> %1 to <16 x i32>
  %4 = tail call <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8> %2, <16 x i32> %3, i32 274)
  ret <16 x i64> %4
}

define  <16 x i64> @_Z18test_mul_elem_32_2iDv64_hi(i32 noundef %sgn_x, <64 x i8> noundef %b, i32 noundef %sgn_y)  {
; CHECK-LABEL: _Z18test_mul_elem_32_2iDv64_hi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r2, #9; nops ; movx r4, #40; mov r3, #8; nopv
; CHECK-NEXT:    lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vmul cm0, x0, x0, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <64 x i8> @llvm.aie2.v64int8()
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or11.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or17.i.i = or i32 %or11.i.i, 40
  %1 = bitcast <64 x i8> %b to <16 x i32>
  %2 = tail call <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8> %0, <16 x i32> %1, i32 %or17.i.i)
  ret <16 x i64> %2
}

declare <32 x i16> @llvm.aie2.v32int16()
declare <64 x i8> @llvm.aie2.v64int8()
declare <16 x i32> @llvm.aie2.v16int32()
declare <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8>, <16 x i32>, i32)
