; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 --issue-limit=1 -verify-machineinstrs -o - < %s \
; RUN:   | FileCheck %s

define dso_local noundef <16 x i64> @test_vneg_acc32(<16 x i64> noundef %acc) local_unnamed_addr #0 {
; CHECK-LABEL: test_vneg_acc32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r0, #0; nops ; nopxm ; nopv
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vneg cm0, cm1, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <16 x i64> @llvm.aie2.ACC1024.acc32.neg.conf(<16 x i64> %acc, i32 0)
  ret <16 x i64> %0
}

define dso_local noundef <16 x i64> @test_vneg_acc64(<16 x i64> noundef %acc) local_unnamed_addr #0 {
; CHECK-LABEL: test_vneg_acc64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r0, #2; nops ; nopxm ; nopv
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vneg cm0, cm1, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <16 x i64> @llvm.aie2.ACC1024.acc64.neg.conf(<16 x i64> %acc, i32 2)
  ret <16 x i64> %0
}

declare <16 x i64> @llvm.aie2.ACC1024.acc32.neg.conf(<16 x i64>, i32) #1
declare <16 x i64> @llvm.aie2.ACC1024.acc64.neg.conf(<16 x i64>, i32) #1
