; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2 %s -o - | FileCheck %s

define dso_local noundef <64 x i8> @_Z17test_neg_v64uint8Dv64_h(<64 x i8> noundef %a) local_unnamed_addr #0 {
; CHECK-LABEL: _Z17test_neg_v64uint8Dv64_h:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vneg_gtz8 x0, r25:r24, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call { <64 x i8>, <2 x i32> } @llvm.aie2.vneg.gtz8(<64 x i8> %a)
  %1 = extractvalue { <64 x i8>, <2 x i32> } %0, 0
  ret <64 x i8> %1
}

define dso_local noundef <32 x i16> @_Z18test_neg_v32uint16Dv32_t(<32 x i16> noundef %a) local_unnamed_addr #0 {
; CHECK-LABEL: _Z18test_neg_v32uint16Dv32_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vneg_gtz16 x0, r16, x2 // Delay Slot 4
; CHECK-NEXT:    or r0, r16, r16 // Delay Slot 3
; CHECK-NEXT:    mov r16, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call { <32 x i16>, i32 } @llvm.aie2.vneg.gtz16(<32 x i16> %a)
  %1 = extractvalue { <32 x i16>, i32 } %0, 0
  ret <32 x i16> %1
}

define dso_local noundef <16 x i32> @_Z18test_neg_v16uint32Dv16_j(<16 x i32> noundef %a) local_unnamed_addr #0 {
; CHECK-LABEL: _Z18test_neg_v16uint32Dv16_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vneg_gtz32 x0, r16, x2 // Delay Slot 4
; CHECK-NEXT:    or r0, r16, r16 // Delay Slot 3
; CHECK-NEXT:    mov r16, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call { <16 x i32>, i32 } @llvm.aie2.vneg.gtz32(<16 x i32> %a)
  %1 = extractvalue { <16 x i32>, i32 } %0, 0
  ret <16 x i32> %1
}

declare { <64 x i8>, <2 x i32> } @llvm.aie2.vneg.gtz8(<64 x i8>) #1
declare { <32 x i16>, i32 } @llvm.aie2.vneg.gtz16(<32 x i16>) #1
declare { <16 x i32>, i32 } @llvm.aie2.vneg.gtz32(<16 x i32>) #1
