; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
;RUN: llc -O2 -mtriple=aie2 --issue-limit=1 %s -o - | FileCheck %s

define dso_local noundef <16 x i64> @test_negadd_acc(<16 x i64> noundef %acc1, <16 x i64> noundef %acc2) local_unnamed_addr #0 {
; CHECK-LABEL: test_negadd_acc:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopb ; mova r0, #0; nops ; nopxm ; nopv
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vnegadd cm0, cm1, cm2, r0 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <16 x i64> @llvm.aie2.negadd.acc(<16 x i64> %acc1, <16 x i64> %acc2, i32 0)
  ret <16 x i64> %0
}

declare <16 x i64> @llvm.aie2.negadd.acc(<16 x i64>, <16 x i64>, i32) #1
