; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -O2 -mtriple=aie2p %s -o - | FileCheck %s --check-prefix=AIE2P

declare i10 @llvm.bitreverse.i10(i10)

define i10 @test_bitreverse_i10(i10 %a) {
; AIE2P-LABEL: test_bitreverse_i10:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    mova r0, #24; nopxm
; AIE2P-NEXT:    mova r2, #-24; lshl r0, r1, r0
; AIE2P-NEXT:    lshl r2, r1, r2
; AIE2P-NEXT:    or r0, r2, r0
; AIE2P-NEXT:    movxm r2, #65280
; AIE2P-NEXT:    mova r3, #8; and r4, r1, r2
; AIE2P-NEXT:    lshl r3, r4, r3
; AIE2P-NEXT:    mova r3, #-8; or r0, r0, r3
; AIE2P-NEXT:    lshl r1, r1, r3
; AIE2P-NEXT:    and r1, r1, r2
; AIE2P-NEXT:    or r0, r0, r1
; AIE2P-NEXT:    movxm r1, #-252645136
; AIE2P-NEXT:    mova r4, #4; and r2, r0, r1
; AIE2P-NEXT:    mova r3, #-4; lshl r0, r0, r4
; AIE2P-NEXT:    lshl r2, r2, r3
; AIE2P-NEXT:    and r0, r0, r1
; AIE2P-NEXT:    movxm r1, #-858993460
; AIE2P-NEXT:    or r0, r2, r0
; AIE2P-NEXT:    mova r4, #2; and r2, r0, r1
; AIE2P-NEXT:    mova r3, #-2; lshl r0, r0, r4
; AIE2P-NEXT:    lshl r2, r2, r3
; AIE2P-NEXT:    and r0, r0, r1
; AIE2P-NEXT:    movxm r1, #-1431655766
; AIE2P-NEXT:    or r0, r2, r0
; AIE2P-NEXT:    mova r2, #1; and r3, r0, r1
; AIE2P-NEXT:    lshl r0, r0, r2
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    mova r1, #-23; and r0, r0, r1 // Delay Slot 5
; AIE2P-NEXT:    mova r2, #-22; lshl r1, r3, r1 // Delay Slot 4
; AIE2P-NEXT:    lshl r0, r0, r2 // Delay Slot 3
; AIE2P-NEXT:    or r0, r1, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %result = call i10 @llvm.bitreverse.i10(i10 %a)
  ret i10 %result
}
