# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-cluster-base-address  %s -verify-machineinstrs -o - | FileCheck %s

# Address Chaining test across multiple MBBs.


---
name:            dominatingReplacement
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: dominatingReplacement
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p3
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 -1
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C4]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD1]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C6]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD2]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD2]], [[C8]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD3]](p0) :: (store (s32))

  bb.0.entry:
    successors: %bb.1
    liveins: $p3
    %0:_(p0) = COPY $p3
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s20) = G_CONSTANT i20 5
    %4:_(p0) = G_PTR_ADD %0:_, %3:_(s20)
    G_STORE %2:_(s32), %4:_(p0) :: (store (s32))
    %7:_(s20) = G_CONSTANT i20 4
    %8:_(p0) = G_PTR_ADD %0:_, %7:_(s20)
    G_STORE %2:_(s32), %8:_(p0) :: (store (s32))
    G_BR %bb.1

  bb.1:
    %12:_(s20) = G_CONSTANT i20 19
    %13:_(p0) = G_PTR_ADD %0:_, %12:_(s20)
    G_STORE %2:_(s32), %13:_(p0) :: (store (s32))
    %14:_(s20) = G_CONSTANT i20 42
    %15:_(p0) = G_PTR_ADD %0:_, %14:_(s20)
    G_STORE %2:_(s32), %15:_(p0) :: (store (s32))

...

# Insert PHI nodes to collect the original pointer and the updated path.
#
#        Def InputPtr + Mod
#        /         \
# InputPtr mod    InputPtr mod
#         \       /
#      orig Inputptr Use
---
name:            DivergingModifications
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: DivergingModifications
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %InputPtr:_(p0) = COPY $p3
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD %InputPtr, [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 -2
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C3]](s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[PTR_ADD1]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BRCOND [[COPY]](s32), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C5]](s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[PTR_ADD2]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 -1
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD2]], [[C7]](s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[PTR_ADD3]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C9]](s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[PTR_ADD4]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
  ; CHECK-NEXT:   [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 -2
  ; CHECK-NEXT:   [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD4]], [[C11]](s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[PTR_ADD5]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
  ; CHECK-NEXT:   [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C13]](s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[PTR_ADD6]](p0) :: (store (s32))

  bb.0:
    successors: %bb.2, %bb.1
    liveins: $r0, $p3
    %InputPtr:_(p0) = COPY $p3
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s20) = G_CONSTANT i20 4
    %4:_(p0) = G_PTR_ADD %InputPtr:_, %3:_(s20)
    G_STORE %2:_(s32), %4:_(p0) :: (store (s32))
    %5:_(s20) = G_CONSTANT i20 2
    %6:_(p0) = G_PTR_ADD %InputPtr:_, %5:_(s20)
    G_STORE %2:_(s32), %6:_(p0) :: (store (s32))
    G_BRCOND %1:_(s32), %bb.2
    G_BR %bb.1

  bb.1:
    successors: %bb.3
    %7:_(s20) = G_CONSTANT i20 5
    %8:_(p0) = G_PTR_ADD %InputPtr:_, %7:_(s20)
    G_STORE %2:_(s32), %8:_(p0) :: (store (s32))
    %9:_(s20) = G_CONSTANT i20 4
    %10:_(p0) = G_PTR_ADD %InputPtr:_, %9:_(s20)
    G_STORE %2:_(s32), %10:_(p0) :: (store (s32))
    G_BR %bb.3


  bb.2:
    successors: %bb.3
    %11:_(s20) = G_CONSTANT i20 4
    %12:_(p0) = G_PTR_ADD %InputPtr:_, %11:_(s20)
    G_STORE %2:_(s32), %12:_(p0) :: (store (s32))
    %13:_(s20) = G_CONSTANT i20 2
    %14:_(p0) = G_PTR_ADD %InputPtr:_, %13:_(s20)
    G_STORE %2:_(s32), %14:_(p0) :: (store (s32))
    G_BR %bb.3

  bb.3:
    %15:_(s20) = G_CONSTANT i20 19
    %16:_(p0) = G_PTR_ADD %InputPtr:_, %15:_(s20)
    G_STORE %2:_(s32), %16:_(p0) :: (store (s32))

...

# Ptr updated before and inside of the Loop. Updated Pointer is used after loop.

---
name:            ModInLoopAndLaterModUse
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ModInLoopAndLaterModUse
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p3
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
  ; CHECK-NEXT:   %LoopBound:_(s32) = G_CONSTANT i32 5
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 -1
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C4]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD1]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %Idx:_(s32) = G_PHI %Inc(s32), %bb.1, [[C1]](s32), %bb.0
  ; CHECK-NEXT:   %InPtr:_(p0) = G_PHI %LoopPtrMod(p0), %bb.1, [[COPY]](p0), %bb.0
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD %InPtr, [[C5]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD2]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 -13
  ; CHECK-NEXT:   %LoopPtrMod:_(p0) = G_PTR_ADD [[PTR_ADD2]], [[C7]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), %LoopPtrMod(p0) :: (store (s32))
  ; CHECK-NEXT:   %Inc:_(s32) = G_ADD %Idx, [[C]]
  ; CHECK-NEXT:   %BR_SEL:_(s1) = G_ICMP intpred(sle), %Idx(s32), %LoopBound
  ; CHECK-NEXT:   G_BRCOND %BR_SEL(s1), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD %LoopPtrMod, [[C2]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD3]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 -1
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C9]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD4]](p0) :: (store (s32))

  bb.0.entry:
    successors: %bb.1
    liveins: $p3
    %0:_(p0) = COPY $p3
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s20) = G_CONSTANT i20 5
    %LoopBound = G_CONSTANT i32 5
    %4:_(p0) = G_PTR_ADD %0:_, %3:_(s20)
    G_STORE %2:_(s32), %4:_(p0) :: (store (s32))
    %7:_(s20) = G_CONSTANT i20 4
    %8:_(p0) = G_PTR_ADD %0:_, %7:_(s20)
    G_STORE %2:_(s32), %8:_(p0) :: (store (s32))
    G_BR %bb.1

  bb.1:
    successors: %bb.1, %bb.2
    %Idx:_(s32) = G_PHI %Inc, %bb.1, %2, %bb.0
    %InPtr:_(p0) = G_PHI %LoopPtrMod, %bb.1, %0, %bb.0
    %12:_(s20) = G_CONSTANT i20 19
    %13:_(p0) = G_PTR_ADD %InPtr:_, %12:_(s20)
    G_STORE %2:_(s32), %13:_(p0) :: (store (s32))
    %14:_(s20) = G_CONSTANT i20 6
    %LoopPtrMod:_(p0) = G_PTR_ADD %InPtr:_, %14:_(s20)
    G_STORE %2:_(s32), %LoopPtrMod:_(p0) :: (store (s32))
    %Inc:_(s32) = G_ADD %Idx:_(s32), %1:_(s32)
    %BR_SEL:_(s1) = G_ICMP intpred(sle), %Idx:_(s32), %LoopBound:_(s32)
    G_BRCOND %BR_SEL, %bb.1
    G_BR %bb.2

  bb.2:
    %16:_(p0) = G_PTR_ADD %LoopPtrMod:_, %3:_(s20)
    G_STORE %2:_(s32), %16:_(p0) :: (store (s32))
    %17:_(s20) = G_CONSTANT i20 4
    %18:_(p0) = G_PTR_ADD %LoopPtrMod:_, %17:_(s20)
    G_STORE %2:_(s32), %18:_(p0) :: (store (s32))

...

# Ptr updated in loop, but Original Ptr is used after the loop.

#        bb.0
#       /    \
# mod  1      2 mod
#       \    /
#         3
#       /  \
#  mod 4    |
#      \   /
#  mod   5
---
name:            phiInsertion0
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: phiInsertion0
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $p3, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p3
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32))
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[LOAD]], [[C]]
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32))
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:_(s32) = G_AND [[LOAD1]], [[C3]]
  ; CHECK-NEXT:   G_BRCOND [[COPY1]](s32), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C5]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), [[PTR_ADD2]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD2]], [[C7]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), [[PTR_ADD3]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
  ; CHECK-NEXT:   [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 -8
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C9]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), [[PTR_ADD4]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %B12:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
  ; CHECK-NEXT:   %B13:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C10]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), %B13(p0) :: (store (s32))
  ; CHECK-NEXT:   %B14:_(s20) = G_CONSTANT i20 20
  ; CHECK-NEXT:   [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   %B15:_(p0) = G_PTR_ADD %B13, [[C11]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), %B15(p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BRCOND [[COPY1]](s32), %bb.4
  ; CHECK-NEXT:   G_BR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %B412:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
  ; CHECK-NEXT:   %B413:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C12]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), %B413(p0) :: (store (s32))
  ; CHECK-NEXT:   %B414:_(s20) = G_CONSTANT i20 20
  ; CHECK-NEXT:   [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   %B415:_(p0) = G_PTR_ADD %B413, [[C13]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), %B415(p0) :: (store (s32))
  ; CHECK-NEXT:   %B416:_(s20) = G_CONSTANT i20 12
  ; CHECK-NEXT:   [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 -8
  ; CHECK-NEXT:   %B417:_(p0) = G_PTR_ADD %B415, [[C14]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), %B417(p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   %B512:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
  ; CHECK-NEXT:   %B513:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C15]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), %B513(p0) :: (store (s32))
  ; CHECK-NEXT:   %B514:_(s20) = G_CONSTANT i20 20
  ; CHECK-NEXT:   [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   %B515:_(p0) = G_PTR_ADD %B513, [[C16]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), %B515(p0) :: (store (s32))
  bb.0:
    successors: %bb.2, %bb.1
    liveins: $p3, $r0
    %0:_(p0) = COPY $p3
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_CONSTANT i20 5
    %4:_(p0) = G_PTR_ADD %0:_, %3:_(s20)
    %5:_(s32) = G_LOAD %4:_(p0) :: (dereferenceable load (s32))
    %6:_(s32) = G_ADD %5:_, %1:_
    G_STORE %6:_(s32), %4:_(p0) :: (store (s32))
    %7:_(s20) = G_CONSTANT i20 4
    %8:_(p0) = G_PTR_ADD %0:_, %7:_(s20)
    %9:_(s32) = G_LOAD %8:_(p0) :: (dereferenceable load (s32))
    %10:_(s32) = G_CONSTANT i32 255
    %11:_(s32) = G_AND %9:_, %10:_
    G_BRCOND %2:_(s32), %bb.2
    G_BR %bb.1

  bb.1:
    successors: %bb.3
    %12:_(s20) = G_CONSTANT i20 19
    %13:_(p0) = G_PTR_ADD %0:_, %12:_(s20)
    G_STORE %2:_(s32), %13:_(p0) :: (store (s32))
    %14:_(s20) = G_CONSTANT i20 20
    %15:_(p0) = G_PTR_ADD %0:_, %14:_(s20)
    G_STORE %2:_(s32), %15:_(p0) :: (store (s32))
    %16:_(s20) = G_CONSTANT i20 12
    %17:_(p0) = G_PTR_ADD %0:_, %16:_(s20)
    G_STORE %2:_(s32), %17:_(p0) :: (store (s32))
    G_BR %bb.3

  bb.2:
    successors: %bb.3
    %B12:_(s20) = G_CONSTANT i20 19
    %B13:_(p0) = G_PTR_ADD %0:_, %B12:_(s20)
    G_STORE %2:_(s32), %B13:_(p0) :: (store (s32))
    %B14:_(s20) = G_CONSTANT i20 20
    %B15:_(p0) = G_PTR_ADD %0:_, %B14:_(s20)
    G_STORE %2:_(s32), %B15:_(p0) :: (store (s32))
    G_BR %bb.3

  bb.3:
    successors: %bb.4, %bb.5
    G_BRCOND %2:_(s32), %bb.4
    G_BR %bb.5

  bb.4:
    successors: %bb.5
    %B412:_(s20) = G_CONSTANT i20 19
    %B413:_(p0) = G_PTR_ADD %0:_, %B412:_(s20)
    G_STORE %2:_(s32), %B413:_(p0) :: (store (s32))
    %B414:_(s20) = G_CONSTANT i20 20
    %B415:_(p0) = G_PTR_ADD %0:_, %B414:_(s20)
    G_STORE %2:_(s32), %B415:_(p0) :: (store (s32))
    %B416:_(s20) = G_CONSTANT i20 12
    %B417:_(p0) = G_PTR_ADD %0:_, %B416:_(s20)
    G_STORE %2:_(s32), %B417:_(p0) :: (store (s32))
    G_BR %bb.5

  bb.5:
    %B512:_(s20) = G_CONSTANT i20 19
    %B513:_(p0) = G_PTR_ADD %0:_, %B512:_(s20)
    G_STORE %2:_(s32), %B513:_(p0) :: (store (s32))
    %B514:_(s20) = G_CONSTANT i20 20
    %B515:_(p0) = G_PTR_ADD %0:_, %B514:_(s20)
    G_STORE %2:_(s32), %B515:_(p0) :: (store (s32))


...

# Non constant in the G_PTR_ADD chain.
---
name:            NonConstPtrAdd
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: NonConstPtrAdd
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY1]](s32)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY1]](s32), [[PTR_ADD2]](p0) :: (store (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit [[PTR_ADD]](p0), implicit [[LOAD]](s32), implicit [[LOAD1]](s32)
  bb.0:
      successors: %bb.1
      liveins: $p0, $r0
      %0:_(p0) = COPY $p0
      %1:_(s32) = COPY $r0
      %2:_(s20) = G_CONSTANT i20 64
      %3:_(s20) = G_TRUNC %1:_(s32)
      %4:_(p0) = G_PTR_ADD %0, %3
      %5:_(s32) = G_LOAD %4(p0) :: (load (s32))
      %6:_(p0) = G_PTR_ADD %0, %3
      %7:_(s32) = G_LOAD %6(p0) :: (load (s32))

  bb.1:
    %12:_(s20) = G_CONSTANT i20 19
    %13:_(p0) = G_PTR_ADD %0:_, %12:_(s20)
    G_STORE %1:_(s32), %13:_(p0) :: (store (s32))
    PseudoRET implicit $lr, implicit %4(p0), implicit %5(s32), implicit %7(s32)
...

# Properly handle Phi nodes and the occurrence of multiple phi nodes.
---
name:            MultiPhiNodes
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: MultiPhiNodes
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(p0) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:_(s20) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[DEF]], [[DEF2]](s20)
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[DEF]], [[DEF2]](s20)
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(p0) = G_PHI [[DEF]](p0), %bb.1, %6(p0), %bb.3
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(p0) = G_PHI [[DEF]](p0), %bb.1, [[PHI1]](p0), %bb.3
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BRCOND [[DEF1]](s32), %bb.2
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    liveins: $p0, $p1, $p2, $p3
    %0:_(p0) = G_IMPLICIT_DEF
    %1:_(s32) = G_IMPLICIT_DEF
    %2:_(s20) = G_IMPLICIT_DEF
    G_BR %bb.1

  bb.1:
    successors: %bb.2

    %3:_(p0) = G_PTR_ADD %0:_, %2:_(s20)
    %4:_(p0) = G_PTR_ADD %0:_, %2:_(s20)
    G_BR %bb.2

  bb.2:
    successors: %bb.3

    %5:_(p0) = G_PHI %0:_(p0), %bb.1, %6:_(p0), %bb.3
    %6:_(p0) = G_PHI %0:_(p0), %bb.1, %6:_(p0), %bb.3
    G_BR %bb.3

  bb.3:
    successors: %bb.4, %bb.2

    G_BRCOND %1:_(s32), %bb.2
    G_BR %bb.4

  bb.4:

    PseudoRET implicit $lr
...

# Pointer updates in loop with diverging control flow.

---
name:            PtrUpdateDivergingControlFlow
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: PtrUpdateDivergingControlFlow
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(p0) = G_IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[C1]]
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:_(s32) = G_AND [[XOR]], [[C1]]
  ; CHECK-NEXT:   G_BRCOND [[AND]](s32), %bb.3
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[DEF]], [[C2]](s20)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (volatile dereferenceable load (s32))
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C4]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (volatile dereferenceable load (s32))
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C5]]
  ; CHECK-NEXT:   G_BRCOND [[AND1]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[DEF]], [[C6]](s20)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (volatile dereferenceable load (s32))
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD2]], [[C8]](s20)
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (volatile dereferenceable load (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[DEF]](p0) :: (volatile dereferenceable load (s32))
  ; CHECK-NEXT:   [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[DEF]], [[C9]](s20)
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (volatile dereferenceable load (s32))
  ; CHECK-NEXT:   $r0 = COPY [[C]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  bb.1:
    successors: %bb.2
    liveins: $r1

    %2:_(s32) = COPY $r1
    %0:_(s32) = G_CONSTANT i32 0
    %3:_(p0) = G_IMPLICIT_DEF

  bb.2:

    successors: %bb.3, %bb.4
    %30:_(s32) = G_CONSTANT i32 1
    %29:_(s32) = G_XOR %2, %30
    %26:_(s32) = G_AND %29, %30
    G_BRCOND %26(s32), %bb.4
    G_BR %bb.3

  bb.3:

    successors: %bb.2, %bb.5
    %7:_(s20) = G_CONSTANT i20 28
    %8:_(p0) = nuw G_PTR_ADD %3, %7(s20)
    %18:_(s32) = G_LOAD %8(p0) :: (volatile dereferenceable load (s32))
    %33:_(s20) = G_CONSTANT i20 32
    %19:_(p0) = G_PTR_ADD %3, %33(s20)
    %21:_(s32) = G_LOAD %19(p0) :: (volatile dereferenceable load (s32) )
    %31:_(s32) = G_CONSTANT i32 1
    %17:_(s32) = G_AND %2, %31
    G_BRCOND %17(s32), %bb.2
    G_BR %bb.5

  bb.4:

    successors: %bb.5
    %4:_(s20) = G_CONSTANT i20 28
    %5:_(p0) = nuw G_PTR_ADD %3, %4(s20)
    %22:_(s32) = G_LOAD %5(p0) :: (volatile dereferenceable load (s32) )
    %32:_(s20) = G_CONSTANT i20 32
    %23:_(p0) = G_PTR_ADD %3, %32(s20)
    %25:_(s32) = G_LOAD %23(p0) :: (volatile dereferenceable load (s32) )

  bb.5:
    %13:_(s32) = G_LOAD %3(p0) :: (volatile dereferenceable load (s32) )
    %15:_(s20) = G_CONSTANT i20 4
    %14:_(p0) = G_PTR_ADD %3, %15(s20)
    %16:_(s32) = G_LOAD %14(p0) :: (volatile dereferenceable load (s32) )
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
