# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -start-before=aie-cluster-base-address -stop-after=postmisched --issue-limit=6 --aie-chain-addr-scl-ldst=true %s -verify-machineinstrs -o - | FileCheck %s



# The store offsets exceed the immediate range of half scalar load/store requiring moves to materialize them
# Occupying the A slot with the loads forces the immediate moves to be hidden in the MOV slot, making chaining less profitable
---
name:            prevent_unprofitable_chaining
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: prevent_unprofitable_chaining
  ; CHECK: bb.0 (align 16):
  ; CHECK-NEXT:   liveins: $p0, $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r0, renamable $p0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 96)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   renamable $r0 = MOVA 0
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $dj0, implicit $p1 {
  ; CHECK-NEXT:     renamable $r1 = LDA_dms_lda_idx_imm renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:     renamable $dj0 = MOV_alu_mv_mv_mv_cg 16
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_s16_idx killed renamable $r1, renamable $p0, killed renamable $dj0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 80)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $dj0, implicit $p1 {
  ; CHECK-NEXT:     renamable $r1 = LDA_dms_lda_idx_imm renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:     renamable $dj0 = MOV_alu_mv_mv_mv_cg 32
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_s16_idx killed renamable $r1, renamable $p0, killed renamable $dj0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 64, align 32)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $dj0, implicit $p1 {
  ; CHECK-NEXT:     renamable $r1 = LDA_dms_lda_idx_imm renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:     renamable $dj0 = MOV_alu_mv_mv_mv_cg 64
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_s16_idx killed renamable $r1, renamable $p0, killed renamable $dj0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 48)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $dj0, implicit killed $p1 {
  ; CHECK-NEXT:     renamable $r1 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:     renamable $dj0 = MOV_alu_mv_mv_mv_cg 96
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_s16_idx killed renamable $r1, renamable $p0, killed renamable $dj0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 32)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r0, killed renamable $p0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  bb.0:
    liveins: $p0, $p1
    %0:_(p0) = COPY $p0
    %101:_(p0) = COPY $p1
    %8:_(s32) = G_CONSTANT i32 0
    G_STORE %8:_(s32), %0:_(p0) :: (store (s16) into stack - 96)
    %1:_(s20) = G_CONSTANT i20 16
    %2:_(p0) = G_PTR_ADD %0:_, %1:_(s20)
    %81:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %81:_(s32), %2:_(p0) :: (store (s16) into stack - 80)
    %4:_(s20) = G_CONSTANT i20 32
    %5:_(p0) = G_PTR_ADD %0:_, %4:_(s20)
    %82:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %82:_(s32), %5:_(p0) :: (store (s16) into  stack - 64, align 32)
    %6:_(s20) = G_CONSTANT i20 64
    %7:_(p0) = G_PTR_ADD %0:_, %6:_(s20)
    %83:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %83:_(s32), %7:_(p0) :: (store (s16) into stack - 48)
    %9:_(s20) = G_CONSTANT i20 96
    %10:_(p0) = G_PTR_ADD %0:_, %9:_(s20)
    %84:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %84:_(s32), %10:_(p0) :: (store (s16) into stack - 32)
  bb.1:
    G_STORE %8:_(s32), %0:_(p0) :: (store (s16) into unknown-address)
...

# The store offsets fit the immediate range of half scalar load/store
---
name:            allow_profitable_chaining
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: allow_profitable_chaining
  ; CHECK: bb.0 (align 16):
  ; CHECK-NEXT:   liveins: $p0, $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r0, renamable $p0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 96)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   renamable $r0 = MOVA 0
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r1, renamable $p0, 4, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 80)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r1, renamable $p0, 4, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 64, align 32)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r1, renamable $p0, 8, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 48)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (load (s32))
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r1, renamable $p0, 12, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into stack - 32)
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   ST_s16_idx_imm killed renamable $r0, killed renamable $p0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  bb.0:
    liveins: $p0, $p1
    %0:_(p0) = COPY $p0
    %101:_(p0) = COPY $p1
    %8:_(s32) = G_CONSTANT i32 0
    G_STORE %8:_(s32), %0:_(p0) :: (store (s16) into stack - 96)
    %1:_(s20) = G_CONSTANT i20 4
    %2:_(p0) = G_PTR_ADD %0:_, %1:_(s20)
    %81:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %81:_(s32), %2:_(p0) :: (store (s16) into stack - 80)
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(p0) = G_PTR_ADD %0:_, %4:_(s20)
    %82:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %82:_(s32), %5:_(p0) :: (store (s16) into  stack - 64, align 32)
    %6:_(s20) = G_CONSTANT i20 8
    %7:_(p0) = G_PTR_ADD %0:_, %6:_(s20)
    %83:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %83:_(s32), %7:_(p0) :: (store (s16) into stack - 48)
    %9:_(s20) = G_CONSTANT i20 12
    %10:_(p0) = G_PTR_ADD %0:_, %9:_(s20)
    %84:_(s32) = G_LOAD %101:_(p0) :: (load (s32) from unknown-address)
    G_STORE %84:_(s32), %10:_(p0) :: (store (s16) into stack - 32)
  bb.1:
    G_STORE %8:_(s32), %0:_(p0) :: (store (s16) into unknown-address)
...

