# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-cluster-base-address  %s -verify-machineinstrs -o - | FileCheck %s

# Address Chaining test across multiple MBBs.

# Decouple Load that feeds into a conditional jump, so that it can be scheduled
# as early is possible and not delay the branch decision.
---
name:            DecoupleCondJumpLoad
legalized: true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: DecoupleCondJumpLoad
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32))
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[PTR_ADD]], [[C3]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32))
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (dereferenceable load (s32))
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT:   %BR_SEL:_(s1) = G_ICMP intpred(sle), [[LOAD2]](s32), [[C4]]
  ; CHECK-NEXT:   G_BRCOND %BR_SEL(s1), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit [[LOAD]](s32), implicit [[LOAD1]](s32), implicit [[LOAD3]](s32)
  bb.0.entry:
    liveins: $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 4
    %2:_(s20) = G_CONSTANT i20 8
    %3:_(s20) = G_CONSTANT i20 12
    %4:_(p0) = nuw G_PTR_ADD %0, %1(s20)
    %5:_(s32) = G_LOAD %4(p0) :: (dereferenceable load (s32))
    %6:_(p0) = nuw G_PTR_ADD %0, %2(s20)
    %7:_(s32) = G_LOAD %6(p0) :: (dereferenceable load (s32))
    %8:_(p0) = nuw G_PTR_ADD %0, %3(s20)
    %9:_(s32) = G_LOAD %8(p0) :: (dereferenceable load (s32))
    %10:_(s32) = G_CONSTANT i32 4
    %BR_SEL:_(s1) = G_ICMP intpred(sle), %9:_(s32), %10:_(s32)
    G_BRCOND %BR_SEL, %bb.1
    G_BR %bb.2

  bb.1:

    G_BR %bb.2

  bb.2:
    %11:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32))
    PseudoRET implicit $lr, implicit %5, implicit %7, implicit %11
...
