# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=aie-cluster-base-address %s -verify-machineinstrs -o - | FileCheck %s

# Tests for AIEClusterBaseAddress's cross-MBB chain reuse
# (PtrChainEndTracker).

# ---------------------------------------------------------------------
# Cross-MBB reroot must not fire when the shared live-in base still has
# a non-chain consumer (here a direct G_LOAD/G_STORE on %base) in the
# dominated MBB. Rerooting would force RA to save and restore the
# live-in.
# ---------------------------------------------------------------------
---
name:            crossBlockLiveInBaseHasNonChainUse
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: crossBlockLiveInBaseHasNonChainUse
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %base:_(p0) = COPY $p3
  ; CHECK-NEXT:   %zero:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   %off_a1:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   %a1:_(p0) = G_PTR_ADD %base, %off_a1(s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a1(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_a2:_(s20) = G_CONSTANT i20 68
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   %a2:_(p0) = G_PTR_ADD %a1, [[C]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a2(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_a3:_(s20) = G_CONSTANT i20 72
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   %a3:_(p0) = G_PTR_ADD %a2, [[C1]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a3(p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   %v:_(s32) = G_LOAD %base(p0) :: (load (s32))
  ; CHECK-NEXT:   G_STORE %v(s32), %base(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_b1:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   %b1:_(p0) = G_PTR_ADD %base, %off_b1(s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %b1(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_b2:_(s20) = G_CONSTANT i20 132
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   %b2:_(p0) = G_PTR_ADD %b1, [[C2]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %b2(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_b3:_(s20) = G_CONSTANT i20 136
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   %b3:_(p0) = G_PTR_ADD %b2, [[C3]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %b3(p0) :: (store (s32))
  bb.0:
    successors: %bb.1
    liveins: $p3

    %base:_(p0) = COPY $p3
    %zero:_(s32) = G_CONSTANT i32 0

    %off_a1:_(s20) = G_CONSTANT i20 64
    %a1:_(p0) = G_PTR_ADD %base:_, %off_a1:_(s20)
    G_STORE %zero:_(s32), %a1:_(p0) :: (store (s32))

    %off_a2:_(s20) = G_CONSTANT i20 68
    %a2:_(p0) = G_PTR_ADD %base:_, %off_a2:_(s20)
    G_STORE %zero:_(s32), %a2:_(p0) :: (store (s32))

    %off_a3:_(s20) = G_CONSTANT i20 72
    %a3:_(p0) = G_PTR_ADD %base:_, %off_a3:_(s20)
    G_STORE %zero:_(s32), %a3:_(p0) :: (store (s32))

    G_BR %bb.1

  bb.1:
    %v:_(s32) = G_LOAD %base:_(p0) :: (load (s32))
    G_STORE %v:_(s32), %base:_(p0) :: (store (s32))

    %off_b1:_(s20) = G_CONSTANT i20 128
    %b1:_(p0) = G_PTR_ADD %base:_, %off_b1:_(s20)
    G_STORE %zero:_(s32), %b1:_(p0) :: (store (s32))

    %off_b2:_(s20) = G_CONSTANT i20 132
    %b2:_(p0) = G_PTR_ADD %base:_, %off_b2:_(s20)
    G_STORE %zero:_(s32), %b2:_(p0) :: (store (s32))

    %off_b3:_(s20) = G_CONSTANT i20 136
    %b3:_(p0) = G_PTR_ADD %base:_, %off_b3:_(s20)
    G_STORE %zero:_(s32), %b3:_(p0) :: (store (s32))
...

# ---------------------------------------------------------------------
# Dominator publishes chain tail at %base + 512. Dominated MBB chain on
# %base has leading offset 3840. Clusterer reroots head to
# G_PTR_ADD %a3, 3328 -- drops a base-materialisation and shrinks the
# padda constant.
# ---------------------------------------------------------------------
---
name:            crossBlockRerootLargerOffset
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: crossBlockRerootLargerOffset
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %base:_(p0) = COPY $p3
  ; CHECK-NEXT:   %zero:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   %off_a1:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   %a1:_(p0) = G_PTR_ADD %base, %off_a1(s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a1(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_a2:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   %a2:_(p0) = G_PTR_ADD %a1, [[C]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a2(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_a3:_(s20) = G_CONSTANT i20 512
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   %a3:_(p0) = G_PTR_ADD %a2, [[C1]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a3(p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   %off_b1:_(s20) = G_CONSTANT i20 3840
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 3328
  ; CHECK-NEXT:   %b1:_(p0) = G_PTR_ADD %a3, [[C2]](s20)
  ; CHECK-NEXT:   %v0:_(s32) = G_LOAD %b1(p0) :: (load (s32))
  ; CHECK-NEXT:   G_STORE %v0(s32), %b1(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_b2:_(s20) = G_CONSTANT i20 3968
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 3456
  ; CHECK-NEXT:   %b2:_(p0) = G_PTR_ADD %a3, [[C3]](s20)
  ; CHECK-NEXT:   %v1:_(s32) = G_LOAD %b2(p0) :: (load (s32))
  ; CHECK-NEXT:   G_STORE %v1(s32), %b2(p0) :: (store (s32))
  bb.0:
    successors: %bb.1
    liveins: $p3

    %base:_(p0) = COPY $p3
    %zero:_(s32) = G_CONSTANT i32 0

    %off_a1:_(s20) = G_CONSTANT i20 128
    %a1:_(p0) = G_PTR_ADD %base:_, %off_a1:_(s20)
    G_STORE %zero:_(s32), %a1:_(p0) :: (store (s32))

    %off_a2:_(s20) = G_CONSTANT i20 256
    %a2:_(p0) = G_PTR_ADD %base:_, %off_a2:_(s20)
    G_STORE %zero:_(s32), %a2:_(p0) :: (store (s32))

    %off_a3:_(s20) = G_CONSTANT i20 512
    %a3:_(p0) = G_PTR_ADD %base:_, %off_a3:_(s20)
    G_STORE %zero:_(s32), %a3:_(p0) :: (store (s32))

    G_BR %bb.1

  bb.1:
    %off_b1:_(s20) = G_CONSTANT i20 3840
    %b1:_(p0) = G_PTR_ADD %base:_, %off_b1:_(s20)
    %v0:_(s32) = G_LOAD %b1:_(p0) :: (load (s32))
    G_STORE %v0:_(s32), %b1:_(p0) :: (store (s32))

    %off_b2:_(s20) = G_CONSTANT i20 3968
    %b2:_(p0) = G_PTR_ADD %base:_, %off_b2:_(s20)
    %v1:_(s32) = G_LOAD %b2:_(p0) :: (load (s32))
    G_STORE %v1:_(s32), %b2:_(p0) :: (store (s32))
...

# ---------------------------------------------------------------------
# Dominator publishes chain tail at %base + 512. Dominated chain head
# needs %base + 256 (smaller than tail). Head reroots to
# G_PTR_ADD %a2, -256. Proves the offset-fit guard accepts negative
# offsets (padda encodes them via scaled immediates).
# ---------------------------------------------------------------------
---
name:            crossBlockNegativeRerootMultiAdd
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: crossBlockNegativeRerootMultiAdd
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %base:_(p0) = COPY $p3
  ; CHECK-NEXT:   %zero:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   %off_a1:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   %a1:_(p0) = G_PTR_ADD %base, %off_a1(s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a1(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_a2:_(s20) = G_CONSTANT i20 512
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   %a2:_(p0) = G_PTR_ADD %a1, [[C]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a2(p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   %off_b1:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -256
  ; CHECK-NEXT:   %b1:_(p0) = G_PTR_ADD %a2, [[C1]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %b1(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_b2:_(s20) = G_CONSTANT i20 384
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   %b2:_(p0) = G_PTR_ADD %b1, [[C2]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %b2(p0) :: (store (s32))
  bb.0:
    successors: %bb.1
    liveins: $p3

    %base:_(p0) = COPY $p3
    %zero:_(s32) = G_CONSTANT i32 0

    %off_a1:_(s20) = G_CONSTANT i20 256
    %a1:_(p0) = G_PTR_ADD %base:_, %off_a1:_(s20)
    G_STORE %zero:_(s32), %a1:_(p0) :: (store (s32))

    %off_a2:_(s20) = G_CONSTANT i20 512
    %a2:_(p0) = G_PTR_ADD %base:_, %off_a2:_(s20)
    G_STORE %zero:_(s32), %a2:_(p0) :: (store (s32))

    G_BR %bb.1

  bb.1:
    %off_b1:_(s20) = G_CONSTANT i20 256
    %b1:_(p0) = G_PTR_ADD %base:_, %off_b1:_(s20)
    G_STORE %zero:_(s32), %b1:_(p0) :: (store (s32))

    %off_b2:_(s20) = G_CONSTANT i20 384
    %b2:_(p0) = G_PTR_ADD %base:_, %off_b2:_(s20)
    G_STORE %zero:_(s32), %b2:_(p0) :: (store (s32))
...

# ---------------------------------------------------------------------
# Dominator publishes chain tail at %base + 512. Dominated MBB has a
# single G_PTR_ADD %base, 256. Phase 2 reroots it independently of
# chain-length (head becomes G_PTR_ADD %a2, -256).
# ---------------------------------------------------------------------
---
name:            crossBlockSmallerOffsetSingleAdd
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: crossBlockSmallerOffsetSingleAdd
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %base:_(p0) = COPY $p3
  ; CHECK-NEXT:   %zero:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   %off_a1:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   %a1:_(p0) = G_PTR_ADD %base, %off_a1(s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a1(p0) :: (store (s32))
  ; CHECK-NEXT:   %off_a2:_(s20) = G_CONSTANT i20 512
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 384
  ; CHECK-NEXT:   %a2:_(p0) = G_PTR_ADD %a1, [[C]](s20)
  ; CHECK-NEXT:   G_STORE %zero(s32), %a2(p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   %off_b1:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -256
  ; CHECK-NEXT:   %b1:_(p0) = G_PTR_ADD %a2, [[C1]](s20)
  ; CHECK-NEXT:   %v0:_(s32) = G_LOAD %b1(p0) :: (load (s32))
  ; CHECK-NEXT:   G_STORE %v0(s32), %b1(p0) :: (store (s32))
  bb.0:
    successors: %bb.1
    liveins: $p3

    %base:_(p0) = COPY $p3
    %zero:_(s32) = G_CONSTANT i32 0

    %off_a1:_(s20) = G_CONSTANT i20 128
    %a1:_(p0) = G_PTR_ADD %base:_, %off_a1:_(s20)
    G_STORE %zero:_(s32), %a1:_(p0) :: (store (s32))

    %off_a2:_(s20) = G_CONSTANT i20 512
    %a2:_(p0) = G_PTR_ADD %base:_, %off_a2:_(s20)
    G_STORE %zero:_(s32), %a2:_(p0) :: (store (s32))

    G_BR %bb.1

  bb.1:
    %off_b1:_(s20) = G_CONSTANT i20 256
    %b1:_(p0) = G_PTR_ADD %base:_, %off_b1:_(s20)
    %v0:_(s32) = G_LOAD %b1:_(p0) :: (load (s32))
    G_STORE %v0:_(s32), %b1:_(p0) :: (store (s32))
...

# ---------------------------------------------------------------------
# Dominator MBB contains G_AIE_POSTINC_LOAD %pre, step(=32), producing
# %post = %pre + 32 live across the dominated MBB. PtrChainEndTracker
# only registers tails of constant-offset ptr-add chains it built;
# POSTINC post-pointer defs are invisible to it. Leaf G_PTR_ADD %pre,
# 32 is left as-is.
# ---------------------------------------------------------------------
---
name:            postincLoadCEqStepGap
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: postincLoadCEqStepGap
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre, [[C2]](s20) :: (load (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %step:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), %adjusted(p0) :: (store (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 32

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre(p0), %4(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 32
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    G_STORE %2(s32), %adjusted(p0) :: (store (s32))
    PseudoRET implicit $lr, implicit %adjusted(p0)
...

# ---------------------------------------------------------------------
# Same POSTINC setup as above. Dominated leaf is G_PTR_ADD %pre, 96
# with step 32; clusterer leaves it on %pre.
# ---------------------------------------------------------------------
---
name:            postincLoadCGtStepGap
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: postincLoadCGtStepGap
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre, [[C2]](s20) :: (load (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %offset:_(s20) = G_CONSTANT i20 96
  ; CHECK-NEXT:   %adjusted:_(p0) = G_PTR_ADD %pre, %offset(s20)
  ; CHECK-NEXT:   G_STORE [[C]](s32), %adjusted(p0) :: (store (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 32

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre(p0), %4(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %offset:_(s20) = G_CONSTANT i20 96
    %adjusted:_(p0) = G_PTR_ADD %pre, %offset(s20)
    G_STORE %2(s32), %adjusted(p0) :: (store (s32))
    PseudoRET implicit $lr, implicit %adjusted(p0)
...
