# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -run-pass=aie2p-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_concat_unpad_fusion_4ops_to_2ops
legalized: false
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $q0, $q1

    ; CHECK-LABEL: name: test_concat_unpad_fusion_4ops_to_2ops
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<4 x s32>), [[COPY1]](<4 x s32>), [[DEF]](<4 x s32>), [[DEF]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[CONCAT_VECTORS]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<4 x s32>) = COPY $q0
    %1:_(<4 x s32>) = COPY $q1
    %2:_(<4 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>), %2(<4 x s32>), %2(<4 x s32>)
    %4:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %3(<16 x s32>)
    $wl0 = COPY %4(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0
...
