# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name:            G_CONSTANT
legalized:       false
body:             |
  bb.1:
    ; CHECK-LABEL: name: G_CONSTANT
    ; CHECK: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: $m0 = COPY [[C]](s20)
    %1:_(s32) = G_CONSTANT i32 7
    %8:_(s20) = G_TRUNC %1
    $m0 = COPY %8
...

---
name:            G_LOAD_with_G_PTR_ADD_use
legalized:       false
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: G_LOAD_with_G_PTR_ADD_use
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[LOAD]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_LOAD %0:_(p0) :: (load (s32))
    %8:_(s20) = G_TRUNC %1
    %9:_(p0) = G_PTR_ADD %0, %8
    $p0 = COPY %9
...

---
name:            G_LOAD_with_G_STORE_use
legalized:       false
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: G_LOAD_with_G_STORE_use
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
    ; CHECK-NEXT: G_STORE [[LOAD]](s20), [[COPY]](p0) :: (store (s20), align 4)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_LOAD %0:_(p0) :: (load (s32))
    %8:_(s20) = G_TRUNC %1
    G_STORE %8, %0 :: (store (s20))
...

# Since G_ADD will be legalized after to s30, there is no advantage on narrowing.

---
name:            G_LOAD_with_G_ADD_use
legalized:       false
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: G_LOAD_with_G_ADD_use
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32))
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[LOAD]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s20) = G_ADD [[TRUNC]], [[C]]
    ; CHECK-NEXT: $m0 = COPY [[ADD]](s20)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_LOAD %0:_(p0) :: (load (s32))
    %8:_(s20) = G_TRUNC %1
    %9:_(s20) = G_CONSTANT i20 1
    %10:_(s20) = G_ADD %8, %9
    $m0 = COPY %10
...

---
name:            G_LOAD_with_G_PHI_use
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: G_LOAD_with_G_PHI_use
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   %one:_(s32) = G_CONSTANT i32 2
  ; CHECK-NEXT:   %cmp:_(s1) = G_ICMP intpred(sle), [[COPY]](s32), %one
  ; CHECK-NEXT:   G_BRCOND %cmp(s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %phi2:_(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY1]](p0) :: (load (s20), align 4)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   %phi:_(s20) = G_PHI %phi2(s20), %bb.1, [[LOAD]](s20), %bb.2
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %phi(s20)
  bb.1.entry:
    liveins: $r0, $r1, $p0

    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(p0) = COPY $p0
    %one:_(s32) = G_CONSTANT i32 2
    %cmp:_(s1) = G_ICMP intpred(sgt), %0(s32), %one
    G_BRCOND %cmp(s1), %bb.2
    G_BR %bb.3

  bb.2:
    %phi2:_(s20) = G_CONSTANT i20 1
    G_BR %bb.4

  bb.3:
    %3:_(s32) = G_LOAD %2:_(p0) :: (load (s32))
    %phi3:_(s20) = G_TRUNC %3

  bb.4:
    %phi:_(s20) = G_PHI %phi2(s20), %bb.2, %phi3(s20), %bb.3
    PseudoRET implicit $lr, implicit %phi
...

---
name:            G_LOAD_with_G_INTRINSIC_use
legalized:       false
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: G_LOAD_with_G_INTRINSIC_use
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(p0), [[INT1:%[0-9]+]]:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2.add.2d), [[COPY]](p0), [[LOAD]](s20), [[C]](s20), [[C1]](s20), [[C2]](s20)
    ; CHECK-NEXT: $p0 = COPY [[INT]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_LOAD %0:_(p0) :: (load (s32))
    %8:_(s20) = G_TRUNC %1
    %2:_(s20) = G_CONSTANT i20 128
    %3:_(s20) = G_CONSTANT i20 0
    %4:_(s20) = G_CONSTANT i20 32
    %5:_(p0), %9:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2.add.2d), %0:_(p0), %8:_(s20), %2:_(s20), %3:_(s20), %4:_(s20)
    $p0 = COPY %5
...

# Here, we test multiple uses of the load. When all users are truncations to s20, which are used by
# other s20 instructions (as s20 operands), we should combine.

---
name:             G_LOAD_with_multiple_uses
legalized:       false
body:             |
  ; CHECK-LABEL: name: G_LOAD_with_multiple_uses
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[C]](p0) :: (load (s20) from `ptr null`, align 32)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.3
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p0), [[INT1:%[0-9]+]]:_(<32 x s32>), [[INT2:%[0-9]+]]:_(s32), [[INT3:%[0-9]+]]:_(s20), [[INT4:%[0-9]+]]:_(s20), [[INT5:%[0-9]+]]:_(<64 x s8>), [[INT6:%[0-9]+]]:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), [[C1]](p0), [[DEF]](<32 x s32>), [[C2]](s32), [[C3]](s20), [[C3]](s20), [[LOAD]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[INT7:%[0-9]+]]:_(p0), [[INT8:%[0-9]+]]:_(<32 x s32>), [[INT9:%[0-9]+]]:_(s32), [[INT10:%[0-9]+]]:_(s20), [[INT11:%[0-9]+]]:_(s20), [[INT12:%[0-9]+]]:_(<64 x s8>), [[INT13:%[0-9]+]]:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), [[C1]](p0), [[DEF]](<32 x s32>), [[C2]](s32), [[C3]](s20), [[C3]](s20), [[LOAD]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.4(0x40000000), %bb.3(0x40000000)
    liveins: $r0

    %1:_(s32) = COPY $r0
    %0:_(s1) = G_TRUNC %1(s32)
    %3:_(p0) = G_CONSTANT i20 0
    %12:_(p0) = G_CONSTANT i20 0
    %14:_(s32) = G_CONSTANT i32 0
    %13:_(<32 x s32>) = G_IMPLICIT_DEF;
    %15:_(s20) = G_CONSTANT i20 0
    %2:_(s32) = G_LOAD %3(p0) :: (load (s32) from `ptr null`, align 32)
    G_BRCOND %0(s1), %bb.4
    G_BR %bb.3

  bb.2:
    PseudoRET implicit $lr

  bb.3:
    successors: %bb.2(0x80000000)

    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %8:_(s20), %9:_(s20), %10:_(<64 x s8>), %11:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), %12(p0), %13(<32 x s32>), %14(s32), %15(s20), %15(s20), %4(s20), %15(s20), %15(s20), %15(s20), %15(s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    G_BR %bb.2

  bb.4:
    successors: %bb.2(0x80000000)

    %16:_(s20) = G_TRUNC %2(s32)
    %17:_(p0), %18:_(<32 x s32>), %19:_(s32), %20:_(s20), %21:_(s20), %22:_(<64 x s8>), %23:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), %12(p0), %13(<32 x s32>), %14(s32), %15(s20), %15(s20), %16(s20), %15(s20), %15(s20), %15(s20), %15(s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    G_BR %bb.2

...

# Here, we test multiple uses of the load. However, we have a non-s20 user.

---
name:             G_LOAD_with_multiple_uses_one_non_trunc_negative
legalized:       false
body:             |
  ; CHECK-LABEL: name: G_LOAD_with_multiple_uses_one_non_trunc_negative
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[C]](p0) :: (load (s32) from `ptr null`, align 32)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.3
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s20) = G_TRUNC [[LOAD]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p0), [[INT1:%[0-9]+]]:_(<32 x s32>), [[INT2:%[0-9]+]]:_(s32), [[INT3:%[0-9]+]]:_(s20), [[INT4:%[0-9]+]]:_(s20), [[INT5:%[0-9]+]]:_(<64 x s8>), [[INT6:%[0-9]+]]:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), [[C1]](p0), [[DEF]](<32 x s32>), [[C2]](s32), [[C3]](s20), [[C3]](s20), [[TRUNC1]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[INT7:%[0-9]+]]:_(p0), [[INT8:%[0-9]+]]:_(<32 x s32>), [[INT9:%[0-9]+]]:_(s32), [[INT10:%[0-9]+]]:_(s20), [[INT11:%[0-9]+]]:_(s20), [[INT12:%[0-9]+]]:_(<64 x s8>), [[INT13:%[0-9]+]]:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), [[C1]](p0), [[DEF]](<32 x s32>), [[LOAD]](s32), [[C3]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20), [[C3]](s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.4(0x40000000), %bb.3(0x40000000)
    liveins: $r0

    %1:_(s32) = COPY $r0
    %0:_(s1) = G_TRUNC %1(s32)
    %3:_(p0) = G_CONSTANT i20 0
    %12:_(p0) = G_CONSTANT i20 0
    %14:_(s32) = G_CONSTANT i32 0
    %13:_(<32 x s32>) = G_IMPLICIT_DEF;
    %15:_(s20) = G_CONSTANT i20 0
    %2:_(s32) = G_LOAD %3(p0) :: (load (s32) from `ptr null`, align 32)
    G_BRCOND %0(s1), %bb.4
    G_BR %bb.3

  bb.2:
    PseudoRET implicit $lr

  bb.3:
    successors: %bb.2(0x80000000)

    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %8:_(s20), %9:_(s20), %10:_(<64 x s8>), %11:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), %12(p0), %13(<32 x s32>), %14(s32), %15(s20), %15(s20), %4(s20), %15(s20), %15(s20), %15(s20), %15(s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    G_BR %bb.2

  bb.4:
    successors: %bb.2(0x80000000)

    %17:_(p0), %18:_(<32 x s32>), %19:_(s32), %20:_(s20), %21:_(s20), %22:_(<64 x s8>), %23:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), %12(p0), %13(<32 x s32>), %2(s32), %15(s20), %15(s20), %15(s20), %15(s20), %15(s20), %15(s20), %15(s20) :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    G_BR %bb.2

...

---
name:            G_LOAD_with_G_INTTOPTR_use
legalized:       false
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: G_LOAD_with_G_INTTOPTR_use
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p0 = COPY [[LOAD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s24) = G_LOAD %0:_(p0) :: (dereferenceable load (s24), align 4)
    %2:_(s20) = G_TRUNC %1
    %3:_(p0) = G_INTTOPTR %2
    $p0 = COPY %3
...
