# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass=aie-postlegalizer-custom-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=aie2p -run-pass=aie-postlegalizer-custom-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=aie2ps -run-pass=aie-postlegalizer-custom-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_insert_extract_s32_vector
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_insert_extract_s32_vector
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src_vec:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %result:_(<16 x s32>) = COPY %src_vec(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %result(<16 x s32>)
    %src_vec:_(<16 x s32>) = COPY $x0
    %idx:_(s32) = G_CONSTANT i32 0
    %undef_vec:_(<16 x s32>) = G_IMPLICIT_DEF
    %extracted_elt:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %src_vec, %idx
    %result:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt, %idx
    PseudoRET implicit $lr, implicit %result
...
---
name: test_insert_extract_s16_vector
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_insert_extract_s16_vector
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src_vec:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: %result:_(<32 x s16>) = COPY %src_vec(<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %result(<32 x s16>)
    %src_vec:_(<32 x s16>) = COPY $x0
    %idx:_(s32) = G_CONSTANT i32 0
    %undef_vec:_(<32 x s16>) = G_IMPLICIT_DEF
    %extracted_elt:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %src_vec, %idx
    %result:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt, %idx
    PseudoRET implicit $lr, implicit %result
...
---
name: test_same_constant_non_zero
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: test_same_constant_non_zero
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src_vec:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %result:_(<16 x s32>) = COPY %src_vec(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %result(<16 x s32>)
    %src_vec:_(<16 x s32>) = COPY $x0
    %idx:_(s32) = G_CONSTANT i32 5
    %undef_vec:_(<16 x s32>) = G_IMPLICIT_DEF
    %extracted_elt:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %src_vec, %idx
    %result:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt, %idx
    PseudoRET implicit $lr, implicit %result
...
---
name: test_same_register_dynamic_index
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r0, $x0
    ; CHECK-LABEL: name: test_same_register_dynamic_index
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src_vec:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %result:_(<16 x s32>) = COPY %src_vec(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %result(<16 x s32>)
    %idx:_(s32) = COPY $r0
    %src_vec:_(<16 x s32>) = COPY $x0
    %undef_vec:_(<16 x s32>) = G_IMPLICIT_DEF
    %extracted_elt:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %src_vec, %idx
    %result:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt, %idx
    PseudoRET implicit $lr, implicit %result
...
---
name: test_no_combine_different_constants
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: test_no_combine_different_constants
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src_vec:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %idx1:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %idx2:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: %undef_vec:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: %extracted_elt:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %src_vec(<16 x s32>), %idx1(s32)
    ; CHECK-NEXT: %result:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt(s32), %idx2(s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %result(<16 x s32>)
    %src_vec:_(<16 x s32>) = COPY $x0
    %idx1:_(s32) = G_CONSTANT i32 1
    %idx2:_(s32) = G_CONSTANT i32 2
    %undef_vec:_(<16 x s32>) = G_IMPLICIT_DEF
    %extracted_elt:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %src_vec, %idx1
    %result:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt, %idx2
    PseudoRET implicit $lr, implicit %result
...
---
name: test_no_combine_type_mismatch
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: test_no_combine_type_mismatch
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src_vec:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %idx:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: %undef_vec:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: %extracted_elt:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %src_vec(<16 x s32>), %idx(s32)
    ; CHECK-NEXT: %result:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt(s32), %idx(s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %result(<32 x s16>)
    %src_vec:_(<16 x s32>) = COPY $x0
    %idx:_(s32) = G_CONSTANT i32 0
    %undef_vec:_(<32 x s16>) = G_IMPLICIT_DEF
    %extracted_elt:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %src_vec, %idx
    %result:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT %undef_vec, %extracted_elt, %idx
    PseudoRET implicit $lr, implicit %result
...
