# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie2-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name:            implicit_phi
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: implicit_phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:_(s1) = G_XOR [[TRUNC]], [[C2]]
  ; CHECK-NEXT:   G_BRCOND [[XOR]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s20) = G_PHI [[C3]](s20), %bb.1, [[C1]](s20), %bb.0
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p0), [[INT1:%[0-9]+]]:_(s20), [[INT2:%[0-9]+]]:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), [[C]](p0), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[PHI]](s20), [[C1]](s20), [[C1]](s20), [[C1]](s20)
  ; CHECK-NEXT:   $p0 = COPY [[INT]](p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $p0
  bb.1:
    successors: %bb.2(0x40000000), %bb.3(0x40000000)
    liveins: $r1

    %2:_(s32) = COPY $r1
    %1:_(s1) = G_TRUNC %2(s32)
    %0:_(s32) = G_CONSTANT i32 0
    %9:_(p0) = G_CONSTANT i20 0
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_IMPLICIT_DEF
    %21:_(s1) = G_CONSTANT i1 true
    %22:_(s1) = G_XOR %1, %21
    G_BRCOND %22(s1), %bb.3
    G_BR %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    %26:_(s20) = G_CONSTANT i20 0

  bb.3:
    %23:_(s20) = G_PHI %26(s20), %bb.2, %11(s20), %bb.1
    %6:_(p0), %7:_(s20), %8:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %9(p0), %10(s20), %10(s20), %10(s20), %23(s20), %10(s20), %10(s20), %10(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0

...
