# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass=aie-postlegalizer-final-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_postincload_ptradd_with_trunc
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: test_postincload_ptradd_with_trunc
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:_(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:_(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; CHECK-NEXT: $p0 = COPY [[AIE_POSTINC_LOAD1]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(s20) = G_TRUNC %1(s32)
    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(<16 x s32>), %6:_(p0) = G_AIE_POSTINC_LOAD %0, %3(s20) :: (load (<16 x s32>))
    %7:_(p0) = G_PTR_ADD %6, %4(s20)
    $x0 = COPY %5(<16 x s32>)
    $p0 = COPY %7(p0)
    PseudoRET implicit $lr, implicit $x0, implicit $p0
...
---
name: test_postincload_ptradd_no_trunc_should_not_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $m1
    ; CHECK-LABEL: name: test_postincload_ptradd_no_trunc_should_not_combine
    ; CHECK: liveins: $p0, $m0, $m1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s20) = COPY $m1
    ; CHECK-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:_(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:_(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[COPY1]](s20) :: (load (<16 x s32>))
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[AIE_POSTINC_LOAD1]], [[COPY2]](s20)
    ; CHECK-NEXT: $x0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = COPY $m0
    %2:_(s20) = COPY $m1
    %3:_(<16 x s32>), %4:_(p0) = G_AIE_POSTINC_LOAD %0, %1(s20) :: (load (<16 x s32>))
    %5:_(p0) = G_PTR_ADD %4, %2(s20)
    $x0 = COPY %3(<16 x s32>)
    $p0 = COPY %5(p0)
    PseudoRET implicit $lr, implicit $x0, implicit $p0
...
---
name: test_postincload_ptradd_multiple_uses_should_not_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: test_postincload_ptradd_multiple_uses_should_not_combine
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s20) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:_(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:_(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<16 x s32>))
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[AIE_POSTINC_LOAD1]], [[TRUNC1]](s20)
    ; CHECK-NEXT: $x0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; CHECK-NEXT: $p0 = COPY [[AIE_POSTINC_LOAD1]](p0)
    ; CHECK-NEXT: $p1 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $p0, implicit $p1
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(s20) = G_TRUNC %1(s32)
    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(<16 x s32>), %6:_(p0) = G_AIE_POSTINC_LOAD %0, %3(s20) :: (load (<16 x s32>))
    %7:_(p0) = G_PTR_ADD %6, %4(s20)
    $x0 = COPY %5(<16 x s32>)
    $p0 = COPY %6(p0)
    $p1 = COPY %7(p0)
    PseudoRET implicit $lr, implicit $x0, implicit $p0, implicit $p1
...
---
name: test_postincstore_ptradd_multiple_uses_should_not_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $x0
    ; CHECK-LABEL: name: test_postincstore_ptradd_multiple_uses_should_not_combine
    ; CHECK: liveins: $p0, $r0, $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s20) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:_(p0) = G_AIE_POSTINC_STORE [[COPY3]](<16 x s32>), [[COPY]], [[TRUNC]](s20) :: (store (<16 x s32>))
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[AIE_POSTINC_STORE]], [[TRUNC1]](s20)
    ; CHECK-NEXT: $p0 = COPY [[AIE_POSTINC_STORE]](p0)
    ; CHECK-NEXT: $p1 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0, implicit $p1
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %10:_(<16 x s32>) = COPY $x0
    %3:_(s20) = G_TRUNC %1(s32)
    %4:_(s20) = G_TRUNC %2(s32)
    %6:_(p0) = G_AIE_POSTINC_STORE %10, %0, %3(s20) :: (store (<16 x s32>))
    %7:_(p0) = G_PTR_ADD %6, %4(s20)
    $p0 = COPY %6(p0)
    $p1 = COPY %7(p0)
    PseudoRET implicit $lr, implicit $p0, implicit $p1
...
---
name: test_postincstore_ptradd_with_trunc
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $x0
    ; CHECK-LABEL: name: test_postincstore_ptradd_with_trunc
    ; CHECK: liveins: $p0, $r0, $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:_(p0) = G_AIE_POSTINC_STORE [[COPY3]](<16 x s32>), [[COPY]], [[TRUNC]](s20) :: (store (<16 x s32>))
    ; CHECK-NEXT: $p0 = COPY [[AIE_POSTINC_STORE]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %8:_(<16 x s32>) = COPY $x0
    %3:_(s20) = G_TRUNC %1(s32)
    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(p0) = G_AIE_POSTINC_STORE %8(<16 x s32>), %0, %3(s20) :: (store (<16 x s32>))
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
