# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -run-pass=aie2p-postlegalizer-custom-combiner -global-isel %s -verify-machineinstrs -o - | FileCheck %s

# Test the combine_cse_vector_ops combiner which performs Common Subexpression Elimination
# for duplicate G_CONCAT_VECTORS operations with identical operands.
# The combiner replaces duplicate concatenations with a COPY from the earlier result.

# POSITIVE: Simple duplicate concat - two identical G_CONCAT_VECTORS
# The second concat should be replaced with a COPY from the first concat's result.
---
name:            test_cse_simple_duplicate_concat
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1

    ; CHECK-LABEL: name: test_cse_simple_duplicate_concat
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y1 = COPY [[COPY2]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0, implicit $y1
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    $y0 = COPY %2(<32 x s32>)
    $y1 = COPY %3(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0, implicit $y1

...

# POSITIVE: Duplicate concat with intermediate operations
# The duplicate concat appears after some other operations, but should still be eliminated.
---
name:            test_cse_duplicate_concat_with_intermediate_ops
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1, $x2

    ; CHECK-LABEL: name: test_cse_duplicate_concat_with_intermediate_ops
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[FADD:%[0-9]+]]:_(<32 x s32>) = G_FADD [[CONCAT_VECTORS]], [[CONCAT_VECTORS]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y0 = COPY [[FADD]](<32 x s32>)
    ; CHECK-NEXT: $y1 = COPY [[COPY2]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0, implicit $y1
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    %4:_(<32 x s32>) = G_FADD %3(<32 x s32>), %3(<32 x s32>)
    %5:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    $y0 = COPY %4(<32 x s32>)
    $y1 = COPY %5(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0, implicit $y1

...

# POSITIVE: Multiple duplicate concats in sequence
# Three identical concats - the second and third should both be replaced with COPYs.
---
name:            test_cse_multiple_duplicate_concats
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1

    ; CHECK-LABEL: name: test_cse_multiple_duplicate_concats
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<32 x s32>) = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y1 = COPY [[COPY2]](<32 x s32>)
    ; CHECK-NEXT: $y2 = COPY [[COPY3]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0, implicit $y1, implicit $y2
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    %4:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    $y0 = COPY %2(<32 x s32>)
    $y1 = COPY %3(<32 x s32>)
    $y2 = COPY %4(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0, implicit $y1, implicit $y2

...

# NEGATIVE: Different first operand
# The concats have different first operands, so CSE should not apply.
---
name:            test_cse_negative_different_first_operand
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1, $x2

    ; CHECK-LABEL: name: test_cse_negative_different_first_operand
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY2]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: $y0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y1 = COPY [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0, implicit $y1
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    %4:_(<32 x s32>) = G_CONCAT_VECTORS %2(<16 x s32>), %1(<16 x s32>)
    $y0 = COPY %3(<32 x s32>)
    $y1 = COPY %4(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0, implicit $y1

...

# NEGATIVE: Different second operand
# The concats have different second operands, so CSE should not apply.
---
name:            test_cse_negative_different_second_operand
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1, $x2

    ; CHECK-LABEL: name: test_cse_negative_different_second_operand
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: $y0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y1 = COPY [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0, implicit $y1
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    %4:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %2(<16 x s32>)
    $y0 = COPY %3(<32 x s32>)
    $y1 = COPY %4(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0, implicit $y1

...

# NEGATIVE: Both operands different
# The concats have completely different operands, so CSE should not apply.
---
name:            test_cse_negative_both_operands_different
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1, $x2, $x3

    ; CHECK-LABEL: name: test_cse_negative_both_operands_different
    ; CHECK: liveins: $x0, $x1, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x3
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY2]](<16 x s32>), [[COPY3]](<16 x s32>)
    ; CHECK-NEXT: $y0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: $y1 = COPY [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0, implicit $y1
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<16 x s32>) = COPY $x3
    %4:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    %5:_(<32 x s32>) = G_CONCAT_VECTORS %2(<16 x s32>), %3(<16 x s32>)
    $y0 = COPY %4(<32 x s32>)
    $y1 = COPY %5(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0, implicit $y1

...
