# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_pad_pad_fusion_4_to_16
legalized: false
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $q0


    ; CHECK-LABEL: name: test_pad_pad_fusion_4_to_16
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<4 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<4 x s32>) = COPY $q0
    %1:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF %0(<4 x s32>)
    %2:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF %1(<8 x s32>)
    $x0 = COPY %2(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name: test_unpad_unpad_fusion_16_to_4
legalized: false
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_unpad_unpad_fusion_16_to_4
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $q0 = COPY [[AIE_UNPAD_VECTOR]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $q0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    %2:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %1(<8 x s32>)
    $q0 = COPY %2(<4 x s32>)
    PseudoRET implicit $lr, implicit $q0
...
---
name: test_no_fusion_pad_different_operation
legalized: false
tracksRegLiveness: true
body: |
  bb.0:

    ; CHECK-LABEL: name: test_no_fusion_pad_different_operation
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $q0 = COPY [[DEF]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $q0
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    %1:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF %0(<4 x s32>)
    %2:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %1(<8 x s32>)
    $q0 = COPY %2(<4 x s32>)
    PseudoRET implicit $lr, implicit $q0
...
