# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner %s \
# RUN:         -verify-machineinstrs -o - | FileCheck %s

# Tests for PAD/UNPAD combiners that eliminate redundant padding operations

---
name:            test_pad_unpad_to_copy
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0


    ; CHECK-LABEL: name: test_pad_unpad_to_copy
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF %0(<8 x s32>)
    %2:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %1(<16 x s32>)
    $wl0 = COPY %2(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...

---
name:            test_unpad_pad_to_copy
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_unpad_pad_to_copy
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    %2:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF %1(<8 x s32>)
    $x0 = COPY %2(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_pad_unpad_with_intermediate_use
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0, $x1


    ; CHECK-LABEL: name: test_pad_unpad_with_intermediate_use
    ; CHECK: liveins: $wl0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<16 x s32>) = G_ADD [[COPY1]], [[AIE_PAD_VECTOR_UNDEF]]
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[ADD]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<8 x s32>) = COPY $wl0
    %9:_(<16 x s32>) = COPY $x1
    %1:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF %0(<8 x s32>)
    %10:_(<16 x s32>) = G_ADD %9, %1
    %2:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %1(<16 x s32>)
    $wl0 = COPY %2(<8 x s32>)
    $x0 = COPY %10(<16 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
