# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s


...
---
name:            broadcast_shl_by_0
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_0
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<64 x s8>) = G_SHL %0, %2(<64 x s8>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_1
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_1
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<64 x s8>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<64 x s8>) = G_SHL %0, %2(<64 x s8>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_2
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_2
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<64 x s8>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD]], [[ADD]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD1]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 2
    %2:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<64 x s8>) = G_SHL %0, %2(<64 x s8>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_3
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_3
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<64 x s8>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD]], [[ADD]]
    ; CHECK-NEXT: [[ADD2:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD1]], [[ADD1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD2]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 3
    %2:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<64 x s8>) = G_SHL %0, %2(<64 x s8>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_4
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_4
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<64 x s8>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD]], [[ADD]]
    ; CHECK-NEXT: [[ADD2:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD1]], [[ADD1]]
    ; CHECK-NEXT: [[ADD3:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD2]], [[ADD2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD3]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 4
    %2:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<64 x s8>) = G_SHL %0, %2(<64 x s8>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_5
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_5
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<64 x s8>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD]], [[ADD]]
    ; CHECK-NEXT: [[ADD2:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD1]], [[ADD1]]
    ; CHECK-NEXT: [[ADD3:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD2]], [[ADD2]]
    ; CHECK-NEXT: [[ADD4:%[0-9]+]]:_(<64 x s8>) = G_ADD [[ADD3]], [[ADD3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD4]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 5
    %2:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<64 x s8>) = G_SHL %0, %2(<64 x s8>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_8
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_8
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<32 x s16>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD]], [[ADD]]
    ; CHECK-NEXT: [[ADD2:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD1]], [[ADD1]]
    ; CHECK-NEXT: [[ADD3:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD2]], [[ADD2]]
    ; CHECK-NEXT: [[ADD4:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD3]], [[ADD3]]
    ; CHECK-NEXT: [[ADD5:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD4]], [[ADD4]]
    ; CHECK-NEXT: [[ADD6:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD5]], [[ADD5]]
    ; CHECK-NEXT: [[ADD7:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD6]], [[ADD6]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD7]](<32 x s16>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 8
    %2:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<32 x s16>) = G_SHL %0, %2(<32 x s16>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_9
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_9
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<32 x s16>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD]], [[ADD]]
    ; CHECK-NEXT: [[ADD2:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD1]], [[ADD1]]
    ; CHECK-NEXT: [[ADD3:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD2]], [[ADD2]]
    ; CHECK-NEXT: [[ADD4:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD3]], [[ADD3]]
    ; CHECK-NEXT: [[ADD5:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD4]], [[ADD4]]
    ; CHECK-NEXT: [[ADD6:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD5]], [[ADD5]]
    ; CHECK-NEXT: [[ADD7:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD6]], [[ADD6]]
    ; CHECK-NEXT: [[ADD8:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD7]], [[ADD7]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD8]](<32 x s16>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 9
    %2:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<32 x s16>) = G_SHL %0, %2(<32 x s16>)
    PseudoRET implicit $lr, implicit %3

...

...
---
name:            broadcast_shl_by_9_bitcast
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: broadcast_shl_by_9_bitcast
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<32 x s16>) = G_ADD [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD]], [[ADD]]
    ; CHECK-NEXT: [[ADD2:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD1]], [[ADD1]]
    ; CHECK-NEXT: [[ADD3:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD2]], [[ADD2]]
    ; CHECK-NEXT: [[ADD4:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD3]], [[ADD3]]
    ; CHECK-NEXT: [[ADD5:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD4]], [[ADD4]]
    ; CHECK-NEXT: [[ADD6:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD5]], [[ADD5]]
    ; CHECK-NEXT: [[ADD7:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD6]], [[ADD6]]
    ; CHECK-NEXT: [[ADD8:%[0-9]+]]:_(<32 x s16>) = G_ADD [[ADD7]], [[ADD7]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[ADD8]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<64 x s8>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 9
    %2:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<32 x s16>) = G_SHL %0, %2(<32 x s16>)
    %4:_(<64 x s8>) = G_BITCAST %3:_(<32 x s16>)
    PseudoRET implicit $lr, implicit %4

...

