# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s

---
name:            combine_to_s16
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: combine_to_s16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: G_STORE [[C1]](s16), [[PTR_ADD]](p0) :: (store (s16), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %82:_(s8) = G_CONSTANT i8 0
    %89:_(s20) = G_CONSTANT i20 72
    %90:_(p0) = nuw G_PTR_ADD %84, %89(s20)
    G_STORE %82(s8), %90(p0) :: (store (s8), align 4)
    %91:_(s20) = G_CONSTANT i20 73
    %92:_(p0) = nuw G_PTR_ADD %84, %91(s20)
    G_STORE %82(s8), %92(p0) :: (store (s8))
    PseudoRET implicit $lr

...

---
name:            combine_to_s32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: combine_to_s32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %82:_(s16) = G_CONSTANT i16 0
    %89:_(s20) = G_CONSTANT i20 72
    %90:_(p0) = nuw G_PTR_ADD %84, %89(s20)
    G_STORE %82(s16), %90(p0) :: (store (s16), align 4)
    %91:_(s20) = G_CONSTANT i20 74
    %92:_(p0) = nuw G_PTR_ADD %84, %91(s20)
    G_STORE %82(s16), %92(p0) :: (store (s16))
    PseudoRET implicit $lr

...

---
name:            combine_to_s32_mixed
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: combine_to_s32_mixed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %82:_(s8) = G_CONSTANT i8 0
    %13:_(s16) = G_CONSTANT i16 0
    %89:_(s20) = G_CONSTANT i20 72
    %90:_(p0) = nuw G_PTR_ADD %84, %89(s20)
    G_STORE %82(s8), %90(p0) :: (store (s8), align 4)
    %91:_(s20) = G_CONSTANT i20 73
    %92:_(p0) = nuw G_PTR_ADD %84, %91(s20)
    G_STORE %13(s16), %92(p0) :: (store (s16))
    %95:_(s20) = G_CONSTANT i20 75
    %96:_(p0) = nuw G_PTR_ADD %84, %95(s20)
    G_STORE %82(s8), %96(p0) :: (store (s8))
    PseudoRET implicit $lr

...

---
name:            combine_to_vector
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: combine_to_vector
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: G_STORE [[AIE_UNPAD_VECTOR]](<4 x s32>), [[PTR_ADD]](p0) :: (store (<4 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %193:_(s16) = G_CONSTANT i16 0
    %82:_(s8) = G_CONSTANT i8 0
    %85:_(s20) = G_CONSTANT i20 64
    %86:_(p0) = nuw G_PTR_ADD %84, %85(s20)
    %95:_(s20) = G_CONSTANT i20 80
    %96:_(p0) = nuw G_PTR_ADD %84, %95(s20)
    G_STORE %0(s32), %96(p0) :: (store (s32), align 16)
    %97:_(s20) = G_CONSTANT i20 84
    %98:_(p0) = nuw G_PTR_ADD %84, %97(s20)
    G_STORE %0(s32), %98(p0) :: (store (s32))
    %99:_(s20) = G_CONSTANT i20 88
    %100:_(p0) = nuw G_PTR_ADD %84, %99(s20)
    G_STORE %0(s32), %100(p0) :: (store (s32), align 8)
    %101:_(s20) = G_CONSTANT i20 92
    %102:_(p0) = nuw G_PTR_ADD %84, %101(s20)
    G_STORE %0(s32), %102(p0) :: (store (s32))
    %103:_(s20) = G_CONSTANT i20 96
    %104:_(p0) = nuw G_PTR_ADD %84, %103(s20)
    PseudoRET implicit $lr
...

---
name:            combine_to_vector_leftover
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: combine_to_vector_leftover
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: G_STORE [[AIE_UNPAD_VECTOR]](<4 x s32>), [[PTR_ADD]](p0) :: (store (<4 x s32>))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s16), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 16, align 16)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %193:_(s16) = G_CONSTANT i16 0
    %82:_(s8) = G_CONSTANT i8 0
    %85:_(s20) = G_CONSTANT i20 64
    %86:_(p0) = nuw G_PTR_ADD %84, %85(s20)
    %95:_(s20) = G_CONSTANT i20 80
    %96:_(p0) = nuw G_PTR_ADD %84, %95(s20)
    G_STORE %0(s32), %96(p0) :: (store (s32), align 16)
    %97:_(s20) = G_CONSTANT i20 84
    %98:_(p0) = nuw G_PTR_ADD %84, %97(s20)
    G_STORE %0(s32), %98(p0) :: (store (s32))
    %99:_(s20) = G_CONSTANT i20 88
    %100:_(p0) = nuw G_PTR_ADD %84, %99(s20)
    G_STORE %0(s32), %100(p0) :: (store (s32), align 8)
    %101:_(s20) = G_CONSTANT i20 92
    %102:_(p0) = nuw G_PTR_ADD %84, %101(s20)
    G_STORE %0(s32), %102(p0) :: (store (s32))
    %103:_(s20) = G_CONSTANT i20 96
    %104:_(p0) = nuw G_PTR_ADD %84, %103(s20)
    G_STORE %82(s8), %104(p0) :: (store (s8), align 32)
    %105:_(s20) = G_CONSTANT i20 97
    %106:_(p0) = nuw G_PTR_ADD %84, %105(s20)
    G_STORE %82(s8), %106(p0) :: (store (s8))
    PseudoRET implicit $lr
...

# Negative test cases:

---
name:            no_combine_avoid_combiner_loop
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: no_combine_avoid_combiner_loop
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s8), [[PTR_ADD]](p0) :: (store (s8), align 4)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 73
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s16), [[PTR_ADD1]](p0) :: (store (s6))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %82:_(s8) = G_CONSTANT i8 0
    %13:_(s16) = G_CONSTANT i16 0
    %89:_(s20) = G_CONSTANT i20 72
    %90:_(p0) = nuw G_PTR_ADD %84, %89(s20)
    G_STORE %82(s8), %90(p0) :: (store (s8), align 4)
    %91:_(s20) = G_CONSTANT i20 73
    %92:_(p0) = nuw G_PTR_ADD %84, %91(s20)
    G_STORE %13(s16), %92(p0) :: (store (s6))
    PseudoRET implicit $lr

...

---
name:            no_combine_to_s32_load
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: no_combine_to_s32_load
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s16), [[PTR_ADD]](p0) :: (store (s16), align 4)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY1]](p0) :: (load (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 74
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s16), [[PTR_ADD1]](p0) :: (store (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    %84:_(p0) = COPY $p0
    %85:_(p0) = COPY $p1
    %0:_(s32) = G_CONSTANT i32 0
    %82:_(s16) = G_CONSTANT i16 0
    %89:_(s20) = G_CONSTANT i20 72
    %90:_(p0) = nuw G_PTR_ADD %84, %89(s20)
    G_STORE %82(s16), %90(p0) :: (store (s16), align 4)
    %4:_(s32) = G_LOAD %85 :: (load (s32))
    %91:_(s20) = G_CONSTANT i20 74
    %92:_(p0) = nuw G_PTR_ADD %84, %91(s20)
    G_STORE %82(s16), %92(p0) :: (store (s16))
    PseudoRET implicit $lr, implicit %4

...


---
name:            no_combine_to_s32_side_effects
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1


    ; CHECK-LABEL: name: no_combine_to_s32_side_effects
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s16), [[PTR_ADD]](p0) :: (store (s16), align 4)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), [[DEF]](<32 x s16>), [[C]](s32), [[C]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 74
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s16), [[PTR_ADD1]](p0) :: (store (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<32 x s32>)
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %82:_(s16) = G_CONSTANT i16 0
    %89:_(s20) = G_CONSTANT i20 72
    %90:_(p0) = nuw G_PTR_ADD %84, %89(s20)
    G_STORE %82(s16), %90(p0) :: (store (s16), align 4)
    %1:_(<32 x s16>) = G_IMPLICIT_DEF
    %8:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %1(<32 x s16>), %0(s32), %0(s32)
    %91:_(s20) = G_CONSTANT i20 74
    %92:_(p0) = nuw G_PTR_ADD %84, %91(s20)
    G_STORE %82(s16), %92(p0) :: (store (s16))
    PseudoRET implicit $lr, implicit %8

...

---
name:            no_combine_to_s32_non_sequential
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0


    ; CHECK-LABEL: name: no_combine_to_s32_non_sequential
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s16), [[PTR_ADD]](p0) :: (store (s16), align 4)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s16), [[PTR_ADD1]](p0) :: (store (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %84:_(p0) = COPY $p0
    %0:_(s32) = G_CONSTANT i32 0
    %82:_(s16) = G_CONSTANT i16 0
    %89:_(s20) = G_CONSTANT i20 72
    %90:_(p0) = nuw G_PTR_ADD %84, %89(s20)
    G_STORE %82(s16), %90(p0) :: (store (s16), align 4)
    %91:_(s20) = G_CONSTANT i20 76
    %92:_(p0) = nuw G_PTR_ADD %84, %91(s20)
    G_STORE %82(s16), %92(p0) :: (store (s16))
    PseudoRET implicit $lr

...
