# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Cover the load-into-pointer fold: a G_LOAD producing s20 whose only
# users are G_INTTOPTR (to p0) should fold to a G_LOAD producing p0
# directly. Pattern observed in the for.body block of
# SoftMaxRowMajor_int8_0.ll, where a reloaded pointer is materialized as
# G_LOAD(s20) + G_INTTOPTR and forces an extra integer->pointer move
# unless folded.
#
# RUN: llc -mtriple aie2  -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
# Canonical case: single G_INTTOPTR user. Should fold load to p0.
name: load_s20_single_inttoptr
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_s20_single_inttoptr
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p0 = COPY [[LOAD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_LOAD %0:_(p0) :: (dereferenceable load (s20), align 4)
    %2:_(p0) = G_INTTOPTR %1
    $p0 = COPY %2
...

---
# Two G_INTTOPTR users to the same p0 type (matches the kernel pattern
# where the loaded pointer is consumed in two successor blocks).
name: load_s20_two_inttoptr_users
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: load_s20_two_inttoptr_users
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p0 = COPY [[LOAD]](p0)
    ; CHECK-NEXT: $p1 = COPY [[LOAD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_LOAD %0:_(p0) :: (dereferenceable load (s20), align 4)
    %2:_(p0) = G_INTTOPTR %1
    %3:_(p0) = G_INTTOPTR %1
    $p0 = COPY %2
    $p1 = COPY %3
...

---
# Negative case: one user is a G_STORE of the s20 value. The load must
# remain s20 because not every user is G_INTTOPTR.
name: load_s20_inttoptr_and_store_no_fold
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: load_s20_inttoptr_and_store_no_fold
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[LOAD]](s20)
    ; CHECK-NEXT: G_STORE [[LOAD]](s20), [[COPY1]](p0) :: (store (s20), align 4)
    ; CHECK-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s20) = G_LOAD %0:_(p0) :: (dereferenceable load (s20), align 4)
    %3:_(p0) = G_INTTOPTR %2
    G_STORE %2, %1 :: (store (s20), align 4)
    $p0 = COPY %3
...

---
# Compose with combine_trunc_load: a load of s24 truncated to s20 then
# G_INTTOPTR. Trunc-load narrows to G_LOAD(s20) first, then this combine
# folds to G_LOAD(p0).
name: load_s24_trunc_inttoptr
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_s24_trunc_inttoptr
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: $p0 = COPY [[LOAD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s24) = G_LOAD %0:_(p0) :: (dereferenceable load (s24), align 4)
    %2:_(s20) = G_TRUNC %1
    %3:_(p0) = G_INTTOPTR %2
    $p0 = COPY %3
...

---
# Dead load (no non-debug users): must not match.
name: load_s20_dead_no_match
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_s20_dead_no_match
    ; CHECK: liveins: $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_LOAD %0:_(p0) :: (dereferenceable load (s20), align 4)
...
