# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -O0 -run-pass=aie2-prelegalizer-combiner -global-isel %s -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple=aie2p -O0 -run-pass=aie2p-prelegalizer-combiner -global-isel %s -o - | FileCheck %s --check-prefix=AIE2P

---
name:            test_s16_to_s32_align4
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_to_s32_align4
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_s16_to_s32_align4
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s8_to_s32_align4
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s8_to_s32_align4
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<64 x s8>)
    ;
    ; AIE2P-LABEL: name: test_s8_to_s32_align4
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<64 x s8>)
    %0:_(p0) = COPY $p0
    %1:_(<64 x s8>) = G_LOAD %0(p0) :: (dereferenceable load (<64 x s8>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s8_to_s16_align2
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s8_to_s16_align2
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 2)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[LOAD]](<32 x s16>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<64 x s8>)
    ;
    ; AIE2P-LABEL: name: test_s8_to_s16_align2
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 2)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[LOAD]](<32 x s16>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<64 x s8>)
    %0:_(p0) = COPY $p0
    %1:_(<64 x s8>) = G_LOAD %0(p0) :: (dereferenceable load (<64 x s8>), align 2)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s16_to_s64_align8
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_to_s64_align8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 8)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_s16_to_s64_align8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 8)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 8)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s8_to_s64_align8
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s8_to_s64_align8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 8)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<64 x s8>)
    ;
    ; AIE2P-LABEL: name: test_s8_to_s64_align8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 8)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<64 x s8>)
    %0:_(p0) = COPY $p0
    %1:_(<64 x s8>) = G_LOAD %0(p0) :: (dereferenceable load (<64 x s8>), align 8)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_already_aligned_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_already_aligned_not_combined
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_already_aligned_not_combined
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 64)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_align1_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_align1_not_combined
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 1)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_align1_not_combined
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 1)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 1)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s32_vector_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s32_vector_not_combined
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s32>)
    ;
    ; AIE2P-LABEL: name: test_s32_vector_not_combined
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s32>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_scalar_load_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_scalar_load_not_combined
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s16), align 4)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s16)
    ;
    ; AIE2P-LABEL: name: test_scalar_load_not_combined
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p0) :: (dereferenceable load (s16), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s16)
    %0:_(p0) = COPY $p0
    %1:_(s16) = G_LOAD %0(p0) :: (dereferenceable load (s16), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_small_vector_s16_to_s32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_small_vector_s16_to_s32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<4 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s16>) = G_BITCAST [[LOAD]](<4 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<8 x s16>)
    ;
    ; AIE2P-LABEL: name: test_small_vector_s16_to_s32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<4 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s16>) = G_BITCAST [[LOAD]](<4 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<8 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_medium_vector_s16_to_s32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_medium_vector_s16_to_s32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s16>) = G_BITCAST [[LOAD]](<8 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s16>)
    ;
    ; AIE2P-LABEL: name: test_medium_vector_s16_to_s32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s16>) = G_BITCAST [[LOAD]](<8 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s16>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s16_align2_not_promoted_to_s32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_align2_not_promoted_to_s32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_s16_align2_not_promoted_to_s32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 2)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_large_s8_vector_align4
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_large_s8_vector_align4
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<128 x s8>) = G_BITCAST [[LOAD]](<32 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<128 x s8>)
    ;
    ; AIE2P-LABEL: name: test_large_s8_vector_align4
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<128 x s8>) = G_BITCAST [[LOAD]](<32 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<128 x s8>)
    %0:_(p0) = COPY $p0
    %1:_(<128 x s8>) = G_LOAD %0(p0) :: (dereferenceable load (<128 x s8>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s16_align4_different_sizes
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_align4_different_sizes
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<2 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<4 x s16>) = G_BITCAST [[LOAD]](<2 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<4 x s16>)
    ;
    ; AIE2P-LABEL: name: test_s16_align4_different_sizes
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<2 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<4 x s16>) = G_BITCAST [[LOAD]](<2 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<4 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<4 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<4 x s16>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s8_small_vector_align2
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s8_small_vector_align2
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s16>), align 2)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s8>) = G_BITCAST [[LOAD]](<8 x s16>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s8>)
    ;
    ; AIE2P-LABEL: name: test_s8_small_vector_align2
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s16>), align 2)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s8>) = G_BITCAST [[LOAD]](<8 x s16>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s8>)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s8>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s8>), align 2)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_multiple_uses_of_load
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1

    ; AIE2-LABEL: name: test_multiple_uses_of_load
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2-NEXT: G_STORE [[BITCAST]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_multiple_uses_of_load
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2P-NEXT: G_STORE [[BITCAST]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    G_STORE %2(<32 x s16>), %1(p0) :: (store (<32 x s16>))
    PseudoRET implicit $lr, implicit %2
...
---
name:            test_s16_16elem_to_s32_align4
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_16elem_to_s32_align4
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s16>) = G_BITCAST [[LOAD]](<8 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s16>)
    ;
    ; AIE2P-LABEL: name: test_s16_16elem_to_s32_align4
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s16>) = G_BITCAST [[LOAD]](<8 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s16>)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s16>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_s8_32elem_to_s32_align4
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s8_32elem_to_s32_align4
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s8>) = G_BITCAST [[LOAD]](<8 x s32>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s8>)
    ;
    ; AIE2P-LABEL: name: test_s8_32elem_to_s32_align4
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s8>) = G_BITCAST [[LOAD]](<8 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s8>)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s8>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s8>), align 4)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_load_store_same_alignment_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1

    ; AIE2-LABEL: name: test_load_store_same_alignment_not_combined
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 4)
    ; AIE2-NEXT: G_STORE [[LOAD]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>), align 4)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_load_store_same_alignment_not_combined
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<32 x s16>), align 4)
    ; AIE2P-NEXT: G_STORE [[LOAD]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    G_STORE %2(<32 x s16>), %1(p0) :: (store (<32 x s16>), align 4)
    PseudoRET implicit $lr
...
---
name:            test_load_store_different_alignment_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1

    ; AIE2-LABEL: name: test_load_store_different_alignment_combined
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2-NEXT: G_STORE [[BITCAST]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_load_store_different_alignment_combined
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2P-NEXT: G_STORE [[BITCAST]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    G_STORE %2(<32 x s16>), %1(p0) :: (store (<32 x s16>), align 2)
    PseudoRET implicit $lr
...
---
name:            test_load_only_for_extracts_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_load_only_for_extracts_not_combined
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (load (s16))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_only_for_extracts_not_combined
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (load (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    %2:_(s32) = G_CONSTANT i32 5
    %3:_(s16) = G_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    %4:_(s32) = G_ZEXT %3(s16)
    PseudoRET implicit $lr, implicit %4(s32)
...
---
name:            test_load_with_mixed_uses_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1

    ; AIE2-LABEL: name: test_load_with_mixed_uses_combined
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; AIE2-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<32 x s16>), [[C]](s32)
    ; AIE2-NEXT: G_STORE [[BITCAST]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[EVEC]](s16)
    ;
    ; AIE2P-LABEL: name: test_load_with_mixed_uses_combined
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<16 x s32>), align 4)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[LOAD]](<16 x s32>)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; AIE2P-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<32 x s16>), [[C]](s32)
    ; AIE2P-NEXT: G_STORE [[BITCAST]](<32 x s16>), [[COPY1]](p0) :: (store (<32 x s16>))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[EVEC]](s16)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    %3:_(s32) = G_CONSTANT i32 5
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %2(<32 x s16>), %3(s32)
    G_STORE %2(<32 x s16>), %1(p0) :: (store (<32 x s16>))
    PseudoRET implicit $lr, implicit %4(s16)
...
