# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie2-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: inttoptr_constant_p0_s20
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: inttoptr_constant_p0_s20
    ; CHECK: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
    ; CHECK-NEXT: $p6 = COPY [[C]](p0)
    %0:_(s20) = G_CONSTANT i20 0
    %1:_(p0) = G_INTTOPTR %0
    $p6 = COPY %1
...

---
name: inttoptr_constant_p0_trunc_s32
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: inttoptr_constant_p0_trunc_s32
    ; CHECK: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
    ; CHECK-NEXT: $p6 = COPY [[C]](p0)
    %0:_(s32) = G_CONSTANT i32 0
    %1:_(s20) = G_TRUNC %0
    %2:_(p0) = G_INTTOPTR %1
    $p6 = COPY %2
...

---
name: inttoptr_constant_p0_s32
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: inttoptr_constant_p0_s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[C]](s32)
    ; CHECK-NEXT: $p6 = COPY [[INTTOPTR]](p0)
    %0:_(s32) = G_CONSTANT i32 0
    %1:_(p0) = G_INTTOPTR %0
    $p6 = COPY %1
...
