# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie2-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s


---
name:            G_LOAD_zext_G_STORE
legalized:       false
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: G_LOAD_zext_G_STORE
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
    ; CHECK-NEXT: G_STORE [[LOAD]](s20), [[COPY]](p0) :: (store (s20), align 4)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_LOAD %0:_(p0) :: (load (s20))
    %8:_(s32) = G_ZEXT %1
    G_STORE %8, %0 :: (store (s32))
...

---
name:            G_LOAD_zext_G_STORE_multiple_uses
legalized:       false
body:             |
  bb.1:
    liveins: $p0
    ; CHECK-LABEL: name: G_LOAD_zext_G_STORE_multiple_uses
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[LOAD]](s20)
    ; CHECK-NEXT: G_STORE [[ZEXT]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: $r0 = COPY [[ZEXT]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_LOAD %0:_(p0) :: (load (s20))
    %8:_(s32) = G_ZEXT %1
    G_STORE %8, %0 :: (store (s32))
    $r0 = COPY %8
...
