# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass=aie-postlegalizer-final-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_chained_ptradd_with_trunc_first_dominates
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: test_chained_ptradd_with_trunc_first_dominates
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(s20) = G_TRUNC %1(s32)
    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
name: test_chained_ptradd_with_trunc_second_dominates
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: test_chained_ptradd_with_trunc_second_dominates
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %4:_(s20) = G_TRUNC %2(s32)
    %3:_(s20) = G_TRUNC %1(s32)
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
name: test_chained_ptradd_no_trunc_should_not_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $m1
    ; CHECK-LABEL: name: test_chained_ptradd_no_trunc_should_not_combine
    ; CHECK: liveins: $p0, $m0, $m1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s20) = COPY $m1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[COPY1]](s20)
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[COPY2]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD1]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = COPY $m0
    %2:_(s20) = COPY $m1
    %3:_(p0) = G_PTR_ADD %0, %1(s20)
    %4:_(p0) = G_PTR_ADD %3, %2(s20)
    $p0 = COPY %4(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
name: test_chained_ptradd_multiple_uses_does_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: test_chained_ptradd_multiple_uses_does_combine
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s20) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC1]](s20)
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: $p1 = COPY [[PTR_ADD1]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0, implicit $p1
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(s20) = G_TRUNC %1(s32)
    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %5(p0)
    $p1 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0, implicit $p1
...
---
name: test_chained_ptradd_zextload_trunc
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: test_chained_ptradd_zextload_trunc
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s20) = G_ZEXTLOAD [[COPY1]](p0) :: (load (s16))
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[ZEXTLOAD]](s20)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ZEXT]], [[COPY2]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_ZEXTLOAD %1(p0) :: (load (s16))
    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
name: test_chained_ptradd_trunc_zextload
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: test_chained_ptradd_trunc_zextload
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s20) = G_ZEXTLOAD [[COPY1]](p0) :: (load (s16))
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[ZEXTLOAD]](s20)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY2]], [[ZEXT]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_TRUNC %2(s32)
    %4:_(s20) = G_ZEXTLOAD %1(p0) :: (load (s16))
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
name: test_chained_ptradd_zextload_zextload
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $p2
    ; CHECK-LABEL: name: test_chained_ptradd_zextload_zextload
    ; CHECK: liveins: $p0, $p1, $p2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY $p2
    ; CHECK-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s20) = G_ZEXTLOAD [[COPY1]](p0) :: (load (s16))
    ; CHECK-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s20) = G_ZEXTLOAD [[COPY2]](p0) :: (load (s16))
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[ZEXTLOAD]](s20)
    ; CHECK-NEXT: [[ZEXT1:%[0-9]+]]:_(s32) = G_ZEXT [[ZEXTLOAD1]](s20)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ADD]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(p0) = COPY $p2
    %3:_(s20) = G_ZEXTLOAD %1(p0) :: (load (s16))
    %4:_(s20) = G_ZEXTLOAD %2(p0) :: (load (s16))
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
name: test_chained_ptradd_zextload_wrong_size_no_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: test_chained_ptradd_zextload_wrong_size_no_combine
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s20) = G_ZEXTLOAD [[COPY1]](p0) :: (load (s8))
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[ZEXTLOAD]](s20)
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD1]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_ZEXTLOAD %1(p0) :: (load (s8))
    %4:_(s20) = G_TRUNC %2(s32)
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
# Test that chained G_PTR_ADDs in different basic blocks are NOT combined.
# The guard `MI.getParent() != FirstPtrAddMI->getParent()` prevents combining
# PADDs across block boundaries to avoid de-hoisting ADDs into loops.
name: test_chained_ptradd_cross_block_no_combine
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: test_chained_ptradd_cross_block_no_combine
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY1]](s32)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s20) = G_TRUNC [[COPY2]](s32)
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[TRUNC1]](s20)
  ; CHECK-NEXT:   $p0 = COPY [[PTR_ADD1]](p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $p0
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0, $r1
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(s20) = G_TRUNC %1(s32)
    %5:_(p0) = G_PTR_ADD %0, %3(s20)
    G_BR %bb.1

  bb.1:
    %4:_(s20) = G_TRUNC %2(s32)
    %6:_(p0) = G_PTR_ADD %5, %4(s20)
    $p0 = COPY %6(p0)
    PseudoRET implicit $lr, implicit $p0
...
