# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -O0 -run-pass=aie2-prelegalizer-combiner -global-isel %s -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple=aie2p -O0 -run-pass=aie2p-prelegalizer-combiner -global-isel %s -o - | FileCheck %s --check-prefix=AIE2P

---
name:            test_unaligned_vec_load_to_byte_loads
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_unaligned_vec_load_to_byte_loads
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8))
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_unaligned_vec_load_to_byte_loads
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8))
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 1)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 4
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s8)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %23:_(s32) = G_CONSTANT i32 2
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %18, implicit %156
...
---
name:            test_aligned_load_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_aligned_load_not_combined
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 4)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    ;
    ; AIE2P-LABEL: name: test_aligned_load_not_combined
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 4)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 4)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 4
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s8)
    PseudoRET implicit $lr, implicit %18
...
---
name:            test_load_with_other_uses_not_combined
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1

    ; AIE2-LABEL: name: test_load_with_other_uses_not_combined
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s16>), align 2)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s8>) = G_BITCAST [[LOAD]](<8 x s16>)
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; AIE2-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[BITCAST]](<16 x s8>)
    ; AIE2-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; AIE2-NEXT: G_STORE [[LOAD]](<8 x s16>), [[COPY1]](p0) :: (store (<8 x s16>))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_with_other_uses_not_combined
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s16>) = G_LOAD [[COPY]](p0) :: (dereferenceable load (<8 x s16>), align 2)
    ; AIE2P-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s8>) = G_BITCAST [[LOAD]](<8 x s16>)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; AIE2P-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[BITCAST]](<16 x s8>)
    ; AIE2P-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; AIE2P-NEXT: G_STORE [[LOAD]](<8 x s16>), [[COPY1]](p0) :: (store (<8 x s16>))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 4
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s8)
    G_STORE %14(<8 x s16>), %1(p0) :: (store (<8 x s16>))
    PseudoRET implicit $lr, implicit %18
...
---
name:            test_plain_extract_without_zext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_plain_extract_without_zext
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_plain_extract_without_zext
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s32>), align 2)
    %17:_(s32) = G_CONSTANT i32 5
    %16:_(s32) = G_EXTRACT_VECTOR_ELT %14(<8 x s32>), %17(s32)
    PseudoRET implicit $lr, implicit %16
...
---
name:            test_direct_pad_s8_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_direct_pad_s8_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_direct_pad_s8_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<16 x s8>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s8>), align 2)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %14(<16 x s8>)
    %23:_(s32) = G_CONSTANT i32 5
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_direct_pad_s16_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_direct_pad_s16_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_direct_pad_s16_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 1)
    %158:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF %14(<8 x s16>)
    %23:_(s32) = G_CONSTANT i32 3
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<32 x s16>), %23(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_direct_pad_s32_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_direct_pad_s32_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_direct_pad_s32_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<4 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<4 x s32>), align 2)
    %158:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF %14(<4 x s32>)
    %23:_(s32) = G_CONSTANT i32 2
    %156:_(s32) = G_EXTRACT_VECTOR_ELT %158(<16 x s32>), %23(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_sext_extract_s8
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_sext_extract_s8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_sext_extract_s8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %23:_(s32) = G_CONSTANT i32 3
    %156:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_sext_extract_s16
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_sext_extract_s16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_sext_extract_s16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<4 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<4 x s32>), align 1)
    %15:_(<8 x s16>) = G_BITCAST %14(<4 x s32>)
    %158:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF %15(<8 x s16>)
    %23:_(s32) = G_CONSTANT i32 4
    %156:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %158(<32 x s16>), %23(s32)
    PseudoRET implicit $lr, implicit %156

...
---
name:            test_multiple_extracts_from_same_load
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_multiple_extracts_from_same_load
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; AIE2-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8))
    ; AIE2-NEXT: [[ZEXTLOAD2:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD2]], 8
    ; AIE2-NEXT: [[ASSERT_ZEXT1:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2-NEXT: [[ASSERT_ZEXT2:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ASSERT_ZEXT1]](s32), implicit [[ASSERT_ZEXT2]](s32)
    ;
    ; AIE2P-LABEL: name: test_multiple_extracts_from_same_load
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8))
    ; AIE2P-NEXT: [[ZEXTLOAD2:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD2]], 8
    ; AIE2P-NEXT: [[ASSERT_ZEXT1:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2P-NEXT: [[ASSERT_ZEXT2:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ASSERT_ZEXT1]](s32), implicit [[ASSERT_ZEXT2]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 0
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s8)
    %19:_(s32) = G_CONSTANT i32 5
    %20:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %19(s32)
    %21:_(s32) = G_ZEXT %20(s8)
    %22:_(s32) = G_CONSTANT i32 10
    %23:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %22(s32)
    %24:_(s32) = G_ZEXT %23(s8)
    PseudoRET implicit $lr, implicit %18, implicit %21, implicit %24
...
---
name:            test_extract_with_pad_vector
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_extract_with_pad_vector
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_extract_with_pad_vector
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %23:_(s32) = G_CONSTANT i32 7
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_mixed_plain_and_zext_extracts
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_mixed_plain_and_zext_extracts
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; AIE2-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8))
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_mixed_plain_and_zext_extracts
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8))
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 1
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s8)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %23:_(s32) = G_CONSTANT i32 8
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %18, implicit %156
...
---
name:            test_s8_extract_from_align2_load
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s8_extract_from_align2_load
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s8_extract_from_align2_load
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD1]], 8
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 4
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s8)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %23:_(s32) = G_CONSTANT i32 2
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %18, implicit %156
...
---
name:            test_s16_extract_unaligned
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_extract_unaligned
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 16
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    ;
    ; AIE2P-LABEL: name: test_s16_extract_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 16
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<4 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<4 x s32>), align 1)
    %15:_(<8 x s16>) = G_BITCAST %14(<4 x s32>)
    %17:_(s32) = G_CONSTANT i32 2
    %16:_(s16) = G_EXTRACT_VECTOR_ELT %15(<8 x s16>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s16)
    PseudoRET implicit $lr, implicit %18
...
---
name:            test_s16_direct_vector_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_direct_vector_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 16
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    ;
    ; AIE2P-LABEL: name: test_s16_direct_vector_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 1)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 16
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 1)
    %17:_(s32) = G_CONSTANT i32 3
    %16:_(s16) = G_EXTRACT_VECTOR_ELT %14(<8 x s16>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s16)
    PseudoRET implicit $lr, implicit %18
...
---
name:            test_s32_extract_from_bitcast
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s32_extract_from_bitcast
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s32_extract_from_bitcast
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<4 x s64>) = G_LOAD %0(p0) :: (dereferenceable load (<4 x s64>), align 2)
    %15:_(<8 x s32>) = G_BITCAST %14(<4 x s64>)
    %17:_(s32) = G_CONSTANT i32 3
    %16:_(s32) = G_EXTRACT_VECTOR_ELT %15(<8 x s32>), %17(s32)
    PseudoRET implicit $lr, implicit %16
...
---
name:            test_s32_direct_vector_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s32_direct_vector_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s32_direct_vector_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s32>), align 2)
    %17:_(s32) = G_CONSTANT i32 5
    %16:_(s32) = G_EXTRACT_VECTOR_ELT %14(<8 x s32>), %17(s32)
    PseudoRET implicit $lr, implicit %16
...
---
name:            test_s16_32elem_direct_zext_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_32elem_direct_zext_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 4)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s16_32elem_direct_zext_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    %17:_(s32) = G_CONSTANT i32 10
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %14(<32 x s16>), %17(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_s16_32elem_direct_sext_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_32elem_direct_sext_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s16_32elem_direct_sext_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    %17:_(s32) = G_CONSTANT i32 15
    %156:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %14(<32 x s16>), %17(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_s16_32elem_bitcast_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s16_32elem_bitcast_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 4)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    ;
    ; AIE2P-LABEL: name: test_s16_32elem_bitcast_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 4)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ASSERT_ZEXT]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<32 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<32 x s16>), align 4)
    %15:_(<64 x s8>) = G_BITCAST %14(<32 x s16>)
    %17:_(s32) = G_CONSTANT i32 12
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<64 x s8>), %17(s32)
    %18:_(s32) = G_ZEXT %16(s8)
    PseudoRET implicit $lr, implicit %18
...
---
name:            test_s32_16elem_direct_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s32_16elem_direct_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s32_16elem_direct_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<16 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s32>), align 4)
    %17:_(s32) = G_CONSTANT i32 7
    %16:_(s32) = G_EXTRACT_VECTOR_ELT %14(<16 x s32>), %17(s32)
    PseudoRET implicit $lr, implicit %16
...
---
name:            test_s32_16elem_bitcast_zext_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s32_16elem_bitcast_zext_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s32_16elem_bitcast_zext_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<16 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s32>), align 4)
    %15:_(<32 x s16>) = G_BITCAST %14(<16 x s32>)
    %17:_(s32) = G_CONSTANT i32 9
    %156:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %15(<32 x s16>), %17(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_s32_16elem_bitcast_sext_extract
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_s32_16elem_bitcast_sext_extract
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 4)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_s32_16elem_bitcast_sext_extract
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<16 x s32>) = G_LOAD %0(p0) :: (dereferenceable load (<16 x s32>), align 4)
    %15:_(<32 x s16>) = G_BITCAST %14(<16 x s32>)
    %17:_(s32) = G_CONSTANT i32 12
    %156:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %15(<32 x s16>), %17(s32)
    PseudoRET implicit $lr, implicit %156
...
---
name:            test_load_dedup_same_offset_zext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_load_dedup_same_offset_zext
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_dedup_same_offset_zext
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %17:_(s32) = G_CONSTANT i32 4
    %16:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %17(s32)
    %19:_(s32) = G_CONSTANT i32 4
    %18:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %19(s32)
    PseudoRET implicit $lr, implicit %16, implicit %18
...
---
name:            test_load_dedup_same_offset_sext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_load_dedup_same_offset_sext
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16))
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32), implicit [[SEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_dedup_same_offset_sext
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[SEXTLOAD]](s32), implicit [[SEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %158:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 3
    %16:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %158(<32 x s16>), %17(s32)
    %19:_(s32) = G_CONSTANT i32 3
    %18:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %158(<32 x s16>), %19(s32)
    PseudoRET implicit $lr, implicit %16, implicit %18
...
---
name:            test_load_dedup_reuse_plain_load_for_zext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_load_dedup_reuse_plain_load_for_zext
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[ZEXTLOAD]](s32)
    ; AIE2-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[TRUNC]](s8), implicit [[ASSERT_ZEXT]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_dedup_reuse_plain_load_for_zext
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[ZEXTLOAD]](s32)
    ; AIE2P-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[ZEXTLOAD]], 8
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[TRUNC]](s8), implicit [[ASSERT_ZEXT]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %17:_(s32) = G_CONSTANT i32 2
    %16:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %17(s32)
    %19:_(s32) = G_CONSTANT i32 2
    %18:_(s8) = G_EXTRACT_VECTOR_ELT %15(<16 x s8>), %19(s32)
    %20:_(s32) = G_ZEXT %18(s8)
    PseudoRET implicit $lr, implicit %16, implicit %20
...
---
name:            test_load_dedup_stops_at_store
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $r0

    ; AIE2-LABEL: name: test_load_dedup_stops_at_store
    ; AIE2: liveins: $p0, $r0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2-NEXT: G_STORE [[TRUNC]](s8), [[PTR_ADD1]](p0) :: (store (s8), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_dedup_stops_at_store
    ; AIE2P: liveins: $p0, $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[TRUNC]](s8), [[PTR_ADD1]](p0) :: (store (s8), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %17:_(s32) = G_CONSTANT i32 4
    %16:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %17(s32)
    %20:_(s8) = G_TRUNC %1(s32)
    %21:_(s20) = G_CONSTANT i20 4
    %22:_(p0) = G_PTR_ADD %0, %21(s20)
    G_STORE %20(s8), %22(p0) :: (store (s8), align 2)
    %23:_(s32) = G_CONSTANT i32 4
    %24:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %16, implicit %24
...
---
name:            test_load_dedup_different_base_pointers
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1

    ; AIE2-LABEL: name: test_load_dedup_different_base_pointers
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[C1]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD1]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_dedup_different_base_pointers
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[C1]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD1:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD1]](s32)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %17:_(s32) = G_CONSTANT i32 4
    %16:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %17(s32)
    %20:_(<8 x s16>) = G_LOAD %1(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %21:_(<16 x s8>) = G_BITCAST %20(<8 x s16>)
    %22:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %21(<16 x s8>)
    %23:_(s32) = G_CONSTANT i32 4
    %24:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %22(<64 x s8>), %23(s32)
    PseudoRET implicit $lr, implicit %16, implicit %24
...
---
name:            test_load_dedup_with_ptr_add_same_base_same_offset
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_load_dedup_with_ptr_add_same_base_same_offset
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_dedup_with_ptr_add_same_base_same_offset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %14:_(<8 x s16>) = G_LOAD %0(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %2:_(s20) = G_CONSTANT i20 10
    %17:_(s32) = G_CONSTANT i32 14
    %16:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %17(s32)
    %19:_(s32) = G_CONSTANT i32 14
    %18:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %19(s32)
    PseudoRET implicit $lr, implicit %16, implicit %18
...
---
name:            test_load_dedup_with_ptr_add_same_base_same_offset_parent_offset
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; AIE2-LABEL: name: test_load_dedup_with_ptr_add_same_base_same_offset_parent_offset
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    ;
    ; AIE2P-LABEL: name: test_load_dedup_with_ptr_add_same_base_same_offset_parent_offset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[PTR_ADD]](p0) :: (dereferenceable load (s8), align 2)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ZEXTLOAD]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %2:_(s20) = G_CONSTANT i20 8
    %3:_(p0) = G_PTR_ADD %0, %2(s20)
    %14:_(<8 x s16>) = G_LOAD %3(p0) :: (dereferenceable load (<8 x s16>), align 2)
    %15:_(<16 x s8>) = G_BITCAST %14(<8 x s16>)
    %158:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF %15(<16 x s8>)
    %17:_(s32) = G_CONSTANT i32 14
    %16:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %17(s32)
    %19:_(s32) = G_CONSTANT i32 14
    %18:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %158(<64 x s8>), %19(s32)
    PseudoRET implicit $lr, implicit %16, implicit %18
...
