# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p  -run-pass=aie-prelegalizer-combiner -verify-machineinstrs -o - %s  | FileCheck %s
# RUN: llc -mtriple aie2p  -start-before=aie-prelegalizer-combiner \
# RUN:      -stop-after=legalizer -verify-machineinstrs -o - %s  | FileCheck %s --check-prefix=LEGALIZED
# RUN: llc -mtriple aie2ps  -run-pass=aie-prelegalizer-combiner -verify-machineinstrs -o - %s  | FileCheck %s

---
name:            just_realign
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: just_realign
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32), align 8)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C1]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s16), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: G_STORE [[C4]](s8), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: just_realign
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32), align 8)
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C1]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C4]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    G_STORE %1(s32), %0(p0) :: (store (s32), align 8)
    %4:_(s20) = G_TRUNC %3(s32)
    G_MEMSET %0(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            just_realign_ptr_add
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: just_realign_ptr_add
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C2]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C3]](s16), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: G_STORE [[C5]](s8), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: just_realign_ptr_add
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C5]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    %5:_(s20) = G_CONSTANT i20 48
    %6:_(p0) = G_PTR_ADD %0, %5
    G_STORE %1(s32), %6(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    G_MEMSET %0(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            just_realign_ptr_add_to_memset
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: just_realign_ptr_add_to_memset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C2]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C3]](s16), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: G_STORE [[C5]](s8), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: just_realign_ptr_add_to_memset
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C5]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    G_STORE %1(s32), %0(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    %5:_(s20) = G_CONSTANT i20 48
    %6:_(p0) = G_PTR_ADD %0, %5
    G_MEMSET %6(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            cant_prove_alignment_1
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: cant_prove_alignment_1
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C]](s8), [[COPY]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s8), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s8), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 2)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s8), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s8), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s8), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s8), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: cant_prove_alignment_1
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 2)
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; LEGALIZED-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4)
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; LEGALIZED-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; LEGALIZED-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    %4:_(s20) = G_TRUNC %3(s32)
    G_MEMSET %0(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            cant_prove_alignment_2
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: cant_prove_alignment_2
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[C]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C2]](s8), [[COPY]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s8), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 1)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s8), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 2)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s8), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 3)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s8), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 4)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s8), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 5)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s8), [[PTR_ADD6]](p0) :: (store (s8) into unknown-address + 6)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: cant_prove_alignment_2
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[COPY]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 1)
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 2)
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; LEGALIZED-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 3)
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; LEGALIZED-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 4)
    ; LEGALIZED-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; LEGALIZED-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 5)
    ; LEGALIZED-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; LEGALIZED-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD6]](p0) :: (store (s8) into unknown-address + 6)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    %5:_(s20) = G_CONSTANT i20 45
    %6:_(p0) = G_PTR_ADD %0, %5
    G_STORE %1(s32), %6(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    G_MEMSET %0(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            cant_prove_alignment_3
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: cant_prove_alignment_3
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32), align 2)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[COPY]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 2)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: cant_prove_alignment_3
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY [[C]](s32)
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; LEGALIZED-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY1]], [[C1]](s32)
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; LEGALIZED-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p0) :: (store (s16))
    ; LEGALIZED-NEXT: G_STORE [[LSHR]](s32), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 2)
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[COPY]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 1)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 2)
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; LEGALIZED-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4)
    ; LEGALIZED-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; LEGALIZED-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; LEGALIZED-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; LEGALIZED-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    G_STORE %1(s32), %0(p0) :: (store (s32), align 2)
    %4:_(s20) = G_TRUNC %3(s32)
    G_MEMSET %0(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            peel_3_bytes
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: peel_3_bytes
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C3]](s16), [[PTR_ADD1]](p0) :: (store (s16))
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C6]](s32), [[PTR_ADD2]](p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: peel_3_bytes
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD1]](p0) :: (store (s16))
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C6]](s32), [[PTR_ADD2]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    G_STORE %1(s32), %0(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    %5:_(s20) = G_CONSTANT i20 45
    %6:_(p0) = G_PTR_ADD %0, %5
    G_MEMSET %6(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            peel_3_bytes_initialize_1
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: peel_3_bytes_initialize_1
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 1
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 257
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C3]](s16), [[PTR_ADD1]](p0) :: (store (s16))
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 16843009
    ; CHECK-NEXT: G_STORE [[C6]](s32), [[PTR_ADD2]](p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: peel_3_bytes_initialize_1
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 257
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD1]](p0) :: (store (s16))
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 16843009
    ; LEGALIZED-NEXT: G_STORE [[C6]](s32), [[PTR_ADD2]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 1
    %3:_(s32) = G_CONSTANT i32 7
    G_STORE %1(s32), %0(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    %5:_(s20) = G_CONSTANT i20 45
    %6:_(p0) = G_PTR_ADD %0, %5
    G_MEMSET %6(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            peel_3_bytes_initialize_minus_7
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: peel_3_bytes_initialize_minus_7
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 -7
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 -1543
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C3]](s16), [[PTR_ADD1]](p0) :: (store (s16))
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 -101058055
    ; CHECK-NEXT: G_STORE [[C6]](s32), [[PTR_ADD2]](p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: peel_3_bytes_initialize_minus_7
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -7
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1543
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD1]](p0) :: (store (s16))
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 -101058055
    ; LEGALIZED-NEXT: G_STORE [[C6]](s32), [[PTR_ADD2]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 -7
    %3:_(s32) = G_CONSTANT i32 7
    G_STORE %1(s32), %0(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    %5:_(s20) = G_CONSTANT i20 45
    %6:_(p0) = G_PTR_ADD %0, %5
    G_MEMSET %6(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            peel_3_bytes_minimum
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: peel_3_bytes_minimum
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[C3]](s16), [[PTR_ADD1]](p0) :: (store (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: peel_3_bytes_minimum
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C3]](s32), [[PTR_ADD1]](p0) :: (store (s16))
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 3
    G_STORE %1(s32), %0(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    %5:_(s20) = G_CONSTANT i20 45
    %6:_(p0) = G_PTR_ADD %0, %5
    G_MEMSET %6(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            peel_2_bytes
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: peel_2_bytes
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[C2]](s16), [[PTR_ADD]](p0) :: (store (s16))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C4]](s32), [[PTR_ADD1]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: G_STORE [[C5]](s8), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 4, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: peel_2_bytes
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C2]](s32), [[PTR_ADD]](p0) :: (store (s16))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C4]](s32), [[PTR_ADD1]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C5]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 4, align 4)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 7
    G_STORE %1(s32), %0(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    %5:_(s20) = G_CONSTANT i20 46
    %6:_(p0) = G_PTR_ADD %0, %5
    G_MEMSET %6(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            peel_1_byte
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: peel_1_byte
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 47
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[C1]](s8), [[PTR_ADD]](p0) :: (store (s8))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_STORE [[C4]](s32), [[PTR_ADD1]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: G_STORE [[C4]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    ;
    ; LEGALIZED-LABEL: name: peel_1_byte
    ; LEGALIZED: liveins: $p0
    ; LEGALIZED-NEXT: {{  $}}
    ; LEGALIZED-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; LEGALIZED-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C]](s32), [[COPY]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 47
    ; LEGALIZED-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s8))
    ; LEGALIZED-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; LEGALIZED-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; LEGALIZED-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; LEGALIZED-NEXT: G_STORE [[C4]](s32), [[PTR_ADD1]](p0) :: (store (s32))
    ; LEGALIZED-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; LEGALIZED-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; LEGALIZED-NEXT: G_STORE [[C4]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 4)
    ; LEGALIZED-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s32) = G_CONSTANT i32 9
    G_STORE %1(s32), %0(p0) :: (store (s32), align 4)
    %4:_(s20) = G_TRUNC %3(s32)
    %5:_(s20) = G_CONSTANT i20 47
    %6:_(p0) = G_PTR_ADD %0, %5
    G_MEMSET %6(p0), %2(s8), %4(s20), 1 :: (store (s8))
    PseudoRET implicit $lr

...
