# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-postlegalizer-custom-combiner --aie-greedy-address-combines %s -verify-machineinstrs -o - | FileCheck %s

# Without the aie-greedy-address-combines flag we would not combine in this
# example because there is a use of the original pointer after the insertion
# point of the combine.
---
name:            load_to_postinc
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_to_postinc
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[C]](s32)
    ; CHECK-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:_(s32), [[AIE_POSTINC_LOAD1:%[0-9]+]]:_(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (s32))
    ; CHECK-NEXT: $r0 = COPY [[AIE_POSTINC_LOAD]](s32)
    ; CHECK-NEXT: $p0 = COPY [[AIE_POSTINC_LOAD1]](p0)
    ; CHECK-NEXT: $p1 = COPY [[COPY]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 24
    %2:_(s20) = G_TRUNC %1
    %3:_(s32) = G_LOAD %0 :: (load (s32))
    %4:_(p0) = G_PTR_ADD %0, %2
    $r0 = COPY %3
    $p0 = COPY %4
    $p1 = COPY %0
...
