# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
---
name:            test_combine_trunc_undef
body:             |
  bb.1:
    ; CHECK-LABEL: name: test_combine_trunc_undef
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    %0:_(s64) = G_IMPLICIT_DEF
    %1:_(s32) = G_TRUNC %0(s64)
    $r0 = COPY %1(s32)
...
---
name:            test_combine_trunc_undef_vec
body:             |
  bb.1:
    ; CHECK-LABEL: name: test_combine_trunc_undef_vec
    ; CHECK: [[DEF:%[0-9]+]]:_(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $l0 = COPY [[DEF]](<2 x s32>)
    %0:_(<2 x s64>) = G_IMPLICIT_DEF
    %1:_(<2 x s32>) = G_TRUNC %0(<2 x s64>)
    $l0 = COPY %1(<2 x s32>)
...
---
name:            test_combine_trunc_anyext_s32_s20
body:             |
  bb.1:
  liveins: $m0
    ; CHECK-LABEL: name: test_combine_trunc_anyext_s32_s20
    ; CHECK: liveins: $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[COPY]](s20)
    ; CHECK-NEXT: $r0 = COPY [[ANYEXT]](s32)
    %0:_(s20) = COPY $m0
    %1:_(s64) = G_ANYEXT %0(s20)
    %2:_(s32) = G_TRUNC %1(s64)
    $r0 = COPY %2(s32)
...
---
name:            test_combine_trunc_anyext_s32_s16_vec
body:             |
  bb.1:
  liveins: $r0
    ; CHECK-LABEL: name: test_combine_trunc_anyext_s32_s16_vec
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s16>) = COPY $r0
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(<2 x s32>) = G_ANYEXT [[COPY]](<2 x s16>)
    ; CHECK-NEXT: $l0 = COPY [[ANYEXT]](<2 x s32>)
    %0:_(<2 x s16>) = COPY $r0
    %1:_(<2 x s64>) = G_ANYEXT %0(<2 x s16>)
    %2:_(<2 x s32>) = G_TRUNC %1(<2 x s64>)
    $l0 = COPY %2(<2 x s32>)
...
---
name:            test_combine_trunc_sext_s32_s20
body:             |
  bb.1:
  liveins: $m0
    ; CHECK-LABEL: name: test_combine_trunc_sext_s32_s20
    ; CHECK: liveins: $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[COPY]](s20)
    ; CHECK-NEXT: $r0 = COPY [[SEXT]](s32)
    %0:_(s20) = COPY $m0
    %1:_(s64) = G_SEXT %0(s20)
    %2:_(s32) = G_TRUNC %1(s64)
    $r0 = COPY %2(s32)
...
---
name:            test_combine_trunc_zext_s32_s20
body:             |
  bb.1:
  liveins: $m0
    ; CHECK-LABEL: name: test_combine_trunc_zext_s32_s20
    ; CHECK: liveins: $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[COPY]](s20)
    ; CHECK-NEXT: $r0 = COPY [[ZEXT]](s32)
    %0:_(s20) = COPY $m0
    %1:_(s64) = G_ZEXT %0(s20)
    %2:_(s32) = G_TRUNC %1(s64)
    $r0 = COPY %2(s32)
...
---
name:            test_combine_trunc_anyext_s32_s32
body:             |
  bb.1:
  liveins: $r0
    ; CHECK-LABEL: name: test_combine_trunc_anyext_s32_s32
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    %0:_(s32) = COPY $r0
    %1:_(s64) = G_ANYEXT %0(s32)
    %2:_(s32) = G_TRUNC %1(s64)
    $r1 = COPY %2(s32)
...
---
name:            test_combine_trunc_anyext_s32_s64
body:             |
  bb.1:
  liveins: $l0
    ; CHECK-LABEL: name: test_combine_trunc_anyext_s32_s64
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK-NEXT: $r0 = COPY [[TRUNC]](s32)
    %0:_(s64) = COPY $l0
    %1:_(s128) = G_ANYEXT %0(s64)
    %2:_(s32) = G_TRUNC %1(s128)
    $r0 = COPY %2(s32)
...
---
name:            test_combine_trunc_anyext_s32_s20_multi_use
body:             |
  bb.1:
  liveins: $m0
    ; CHECK-LABEL: name: test_combine_trunc_anyext_s32_s20_multi_use
    ; CHECK: liveins: $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[COPY]](s20)
    ; CHECK-NEXT: [[ANYEXT1:%[0-9]+]]:_(s32) = G_ANYEXT [[COPY]](s20)
    ; CHECK-NEXT: $r0 = COPY [[ANYEXT1]](s32)
    ; CHECK-NEXT: $l0 = COPY [[ANYEXT]](s64)
    %0:_(s20) = COPY $m0
    %1:_(s64) = G_ANYEXT %0(s20)
    %2:_(s32) = G_TRUNC %1(s64)
    $r0 = COPY %2(s32)
    $l0 = COPY %1(s64)
...
---
name:            test_combine_trunc_zext_s32_s20_through_s64_multi_use
body:             |
  bb.1:
  liveins: $m0
    ; CHECK-LABEL: name: test_combine_trunc_zext_s32_s20_through_s64_multi_use
    ; CHECK: liveins: $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s64) = G_ZEXT [[COPY]](s20)
    ; CHECK-NEXT: [[ZEXT1:%[0-9]+]]:_(s32) = G_ZEXT [[COPY]](s20)
    ; CHECK-NEXT: $r0 = COPY [[ZEXT1]](s32)
    ; CHECK-NEXT: $l0 = COPY [[ZEXT]](s64)
    %0:_(s20) = COPY $m0
    %1:_(s64) = G_ZEXT %0(s20)
    %2:_(s32) = G_TRUNC %1(s64)
    $r0 = COPY %2(s32)
    $l0 = COPY %1(s64)
...
---
name:            test_combine_trunc_zext_s32_s20_multi_use
body:             |
  bb.1:
  liveins: $m0
    ; CHECK-LABEL: name: test_combine_trunc_zext_s32_s20_multi_use
    ; CHECK: liveins: $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[COPY]](s20)
    ; CHECK-NEXT: $m1 = COPY [[COPY]](s20)
    ; CHECK-NEXT: $r0 = COPY [[ZEXT]](s32)
    %0:_(s20) = COPY $m0
    %1:_(s32) = G_ZEXT %0(s20)
    %2:_(s20) = G_TRUNC %1(s32)
    $m1 = COPY %2(s20)
    $r0 = COPY %1(s32)
...

