# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner %s \
# RUN:         -verify-machineinstrs -o - | FileCheck %s

# Tests for VSHIFT chain combiner that optimizes VSHIFT sequences into
# CONCAT operations with usage-aware padding (UNDEF vs zeros).

---
name:            test_vshift_chain_basic
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_basic
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    $x0 = COPY %6(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_vsel_partial
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1


    ; CHECK-LABEL: name: test_vshift_chain_vsel_partial
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[COPY]], [[COPY1]], [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(s32) = G_CONSTANT i32 16
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %3, %2(s32)
    %5:_(s32) = G_CONSTANT i32 48
    %6:_(<16 x s32>) = G_IMPLICIT_DEF
    %7:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %6, %4, %5(s32)
    %8:_(s32) = G_CONSTANT i32 15
    %9:_(<16 x s32>) = G_AIE_VSEL %7, %1, %8(s32)
    $x0 = COPY %9(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_vsel_needs_zeros
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1


    ; CHECK-LABEL: name: test_vshift_chain_vsel_needs_zeros
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 61184
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[CONCAT_VECTORS]], [[COPY1]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(s32) = G_CONSTANT i32 16
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %3, %2(s32)
    %5:_(s32) = G_CONSTANT i32 48
    %6:_(<16 x s32>) = G_IMPLICIT_DEF
    %7:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %6, %4, %5(s32)
    %8:_(s32) = G_CONSTANT i32 61184
    %9:_(<16 x s32>) = G_AIE_VSEL %7, %1, %8(s32)
    $x0 = COPY %9(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_negative
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_negative
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[COPY]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 10
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 30
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    $x0 = COPY %6(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_unmerge_first_half
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_unmerge_first_half
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    %7:_(<8 x s32>), %8:_(<8 x s32>) = G_UNMERGE_VALUES %6(<16 x s32>)
    $wl0 = COPY %7(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...

---
name:            test_vshift_chain_unmerge_second_half
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_unmerge_second_half
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[UV1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    %7:_(<8 x s32>), %8:_(<8 x s32>) = G_UNMERGE_VALUES %6(<16 x s32>)
    $wl0 = COPY %8(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...

---
name:            test_vshift_chain_extract_lower
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_extract_lower
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    %7:_(s32) = G_CONSTANT i32 3
    %8:_(s32) = G_EXTRACT_VECTOR_ELT %6(<16 x s32>), %7(s32)
    $r0 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            test_vshift_chain_extract_upper
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_extract_upper
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    %7:_(s32) = G_CONSTANT i32 12
    %8:_(s32) = G_EXTRACT_VECTOR_ELT %6(<16 x s32>), %7(s32)
    $r0 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            test_vshift_chain_extract_non_constant
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $r0


    ; CHECK-LABEL: name: test_vshift_chain_extract_non_constant
    ; CHECK: liveins: $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<16 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<16 x s32>) = COPY $x0
    %9:_(s32) = COPY $r0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    %8:_(s32) = G_EXTRACT_VECTOR_ELT %6(<16 x s32>), %9(s32)
    $r0 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            test_vshift_chain_unmerge_both_used
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_unmerge_both_used
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    %7:_(<8 x s32>), %8:_(<8 x s32>) = G_UNMERGE_VALUES %6(<16 x s32>)
    %9:_(<16 x s32>) = G_CONCAT_VECTORS %7, %8
    $x0 = COPY %9(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_bitcast_use
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_vshift_chain_bitcast_use
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[BITCAST]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    %7:_(<32 x s16>) = G_BITCAST %6(<16 x s32>)
    $x0 = COPY %7(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
