# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=aie2ps -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

# Test: aie_reassoc_ptradd combiner
# This combiner folds chained G_PTR_ADDs with constant offsets, but ONLY when
# the intermediate pointer (LHS of root) has exactly one use. This prevents
# breaking addressing mode opportunities for loops.

---
# Single-use case: intermediate pointer has one use → SHOULD fold
# G_PTR_ADD(G_PTR_ADD(base, 64), 32) → G_PTR_ADD(base, 96)
name: test_single_use_should_fold
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: test_single_use_should_fold
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(p0) = G_PTR_ADD %0, %1(s20)
    %3:_(s20) = G_CONSTANT i20 32
    %4:_(p0) = G_PTR_ADD %2, %3(s20)
    $p0 = COPY %4(p0)
    PseudoRET implicit $lr, implicit $p0
...
---
# Multi-use case: intermediate pointer has multiple uses → should NOT fold
# This preserves the intermediate pointer for use in addressing modes.
name: test_multi_use_should_not_fold
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: test_multi_use_should_not_fold
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C1]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: $p1 = COPY [[PTR_ADD1]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0, implicit $p1
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(p0) = G_PTR_ADD %0, %1(s20)
    %3:_(s20) = G_CONSTANT i20 32
    %4:_(p0) = G_PTR_ADD %2, %3(s20)
    $p0 = COPY %2(p0)    ; extra use of %2 (intermediate pointer)
    $p1 = COPY %4(p0)
    PseudoRET implicit $lr, implicit $p0, implicit $p1
...
---
# Multi-use with load: intermediate pointer used by load → should NOT fold
# This is the key case we want to protect for loop addressing modes.
name: test_multi_use_with_load_should_not_fold
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: test_multi_use_with_load_should_not_fold
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C1]](s20)
    ; CHECK-NEXT: $r0 = COPY [[LOAD]](s32)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD1]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(p0) = G_PTR_ADD %0, %1(s20)
    %5:_(s32) = G_LOAD %2(p0) :: (load (s32))   ; uses %2
    %3:_(s20) = G_CONSTANT i20 32
    %4:_(p0) = G_PTR_ADD %2, %3(s20)            ; also uses %2
    $r0 = COPY %5(s32)
    $p0 = COPY %4(p0)
    PseudoRET implicit $lr, implicit $r0, implicit $p0
...
---
# Non-constant offset: should NOT fold (only constant folding applies)
name: test_non_constant_offset_no_fold
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $m1
    ; CHECK-LABEL: name: test_non_constant_offset_no_fold
    ; CHECK: liveins: $p0, $m0, $m1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s20) = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s20) = COPY $m1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[COPY1]](s20)
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[COPY2]](s20)
    ; CHECK-NEXT: $p0 = COPY [[PTR_ADD1]](p0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = COPY $m0
    %2:_(s20) = COPY $m1
    %3:_(p0) = G_PTR_ADD %0, %1(s20)
    %4:_(p0) = G_PTR_ADD %3, %2(s20)
    $p0 = COPY %4(p0)
    PseudoRET implicit $lr, implicit $p0
...
