# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple=aie2 -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: xor_msb_s8_to_add
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: xor_msb_s8_to_add
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 128
    ; CHECK-NEXT: [[BROADCAST:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<64 x s8>) = G_ADD [[COPY]], [[BROADCAST]]
    ; CHECK-NEXT: $x0 = COPY [[ADD]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 128
    %2:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<64 x s8>) = G_XOR %0, %2
    $x0 = COPY %3(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: xor_msb_s16_to_add
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: xor_msb_s16_to_add
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32768
    ; CHECK-NEXT: [[BROADCAST:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<32 x s16>) = G_ADD [[COPY]], [[BROADCAST]]
    ; CHECK-NEXT: $x0 = COPY [[ADD]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 32768
    %2:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<32 x s16>) = G_XOR %0, %2
    $x0 = COPY %3(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: xor_msb_s32_to_add
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: xor_msb_s32_to_add
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2147483648
    ; CHECK-NEXT: [[BROADCAST:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(<16 x s32>) = G_ADD [[COPY]], [[BROADCAST]]
    ; CHECK-NEXT: $x0 = COPY [[ADD]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 -2147483648
    %2:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<16 x s32>) = G_XOR %0, %2
    $x0 = COPY %3(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: xor_non_msb_no_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: xor_non_msb_no_combine
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[BROADCAST:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<32 x s16>) = G_XOR [[COPY]], [[BROADCAST]]
    ; CHECK-NEXT: $x0 = COPY [[XOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 255
    %2:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %3:_(<32 x s16>) = G_XOR %0, %2
    $x0 = COPY %3(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
