# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_flatten_concat_and_pad
legalized: false
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $q0, $q1, $q2

    ; CHECK-LABEL: name: test_flatten_concat_and_pad
    ; CHECK: liveins: $q0, $q1, $q2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<4 x s32>) = COPY $q2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<4 x s32>), [[COPY1]](<4 x s32>), [[COPY2]](<4 x s32>), [[DEF]](<4 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<4 x s32>) = COPY $q0
    %1:_(<4 x s32>) = COPY $q1
    %2:_(<4 x s32>) = COPY $q2
    %3:_(<8 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>)
    %4:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF %2(<4 x s32>)
    %5:_(<16 x s32>) = G_CONCAT_VECTORS %3(<8 x s32>), %4(<8 x s32>)
    $x0 = COPY %5(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name: test_flatten_pad_and_concat_reverse_order
legalized: false
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $q0, $q1, $q2

    ; CHECK-LABEL: name: test_flatten_pad_and_concat_reverse_order
    ; CHECK: liveins: $q0, $q1, $q2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<4 x s32>) = COPY $q2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<4 x s32>), [[DEF]](<4 x s32>), [[COPY1]](<4 x s32>), [[COPY2]](<4 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<4 x s32>) = COPY $q0
    %1:_(<4 x s32>) = COPY $q1
    %2:_(<4 x s32>) = COPY $q2
    %3:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF %0(<4 x s32>)
    %4:_(<8 x s32>) = G_CONCAT_VECTORS %1(<4 x s32>), %2(<4 x s32>)
    %5:_(<16 x s32>) = G_CONCAT_VECTORS %3(<8 x s32>), %4(<8 x s32>)
    $x0 = COPY %5(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name: test_flatten_two_nested_concats_reject
legalized: false
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $q0, $q1, $q2, $q3

    ; CHECK-LABEL: name: test_flatten_two_nested_concats_reject
    ; CHECK: liveins: $q0, $q1, $q2, $q3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<4 x s32>) = COPY $q2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<4 x s32>) = COPY $q3
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s32>) = G_CONCAT_VECTORS [[COPY]](<4 x s32>), [[COPY1]](<4 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<8 x s32>) = G_CONCAT_VECTORS [[COPY2]](<4 x s32>), [[COPY3]](<4 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<8 x s32>), [[CONCAT_VECTORS1]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[CONCAT_VECTORS2]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<4 x s32>) = COPY $q0
    %1:_(<4 x s32>) = COPY $q1
    %2:_(<4 x s32>) = COPY $q2
    %3:_(<4 x s32>) = COPY $q3
    %4:_(<8 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>)
    %5:_(<8 x s32>) = G_CONCAT_VECTORS %2(<4 x s32>), %3(<4 x s32>)
    %6:_(<16 x s32>) = G_CONCAT_VECTORS %4(<8 x s32>), %5(<8 x s32>)
    $x0 = COPY %6(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name: test_no_flatten_mismatched_subvector_types
legalized: false
tracksRegLiveness: true
body: |
  bb.0:

    ; CHECK-LABEL: name: test_no_flatten_mismatched_subvector_types
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<4 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s32>) = G_CONCAT_VECTORS [[DEF1]](<2 x s32>), [[DEF2]](<2 x s32>), [[DEF3]](<2 x s32>), [[DEF4]](<2 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<8 x s32>), [[CONCAT_VECTORS]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[CONCAT_VECTORS1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    %1:_(<4 x s32>) = G_IMPLICIT_DEF
    %2:_(<2 x s32>) = G_IMPLICIT_DEF
    %3:_(<2 x s32>) = G_IMPLICIT_DEF
    %4:_(<2 x s32>) = G_IMPLICIT_DEF
    %5:_(<2 x s32>) = G_IMPLICIT_DEF
    %6:_(<8 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>)
    %7:_(<8 x s32>) = G_CONCAT_VECTORS %2(<2 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(<2 x s32>)
    %8:_(<16 x s32>) = G_CONCAT_VECTORS %6(<8 x s32>), %7(<8 x s32>)
    $x0 = COPY %8(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
