# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -run-pass=aie-postlegalizer-custom-combiner -global-isel %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple=aie2ps -run-pass=aie-postlegalizer-custom-combiner -global-isel %s -verify-machineinstrs -o - | FileCheck %s

# Check that the combiner correctly optimizes a simple extract→broadcast→extract pattern.
# The broadcast is fed by an extract from position 0, and only position 0 is extracted
# from the broadcast result. The combiner should replace the broadcast with a COPY of
# the source vector, eliminating the unnecessary broadcast operation.
---
name:            test_broadcast_extract_to_copy_simple
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_broadcast_extract_to_copy_simple
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY [[COPY]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY1]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %1(s32)
    %3:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %2(s32)
    %4:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %3(<32 x s16>), %1(s32)
    $r0 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0

...

# Check that the combiner handles patterns with G_FMUL operations (whitelisted in mayMIShiftElements).
# Similar to the FADD test, but using G_FMUL to verify the whitelist includes this operation.
---
name:            test_broadcast_extract_with_fmul
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1


    ; CHECK-LABEL: name: test_broadcast_extract_with_fmul
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s16>) = COPY [[COPY]](<32 x s16>)
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(<32 x s16>) = G_FMUL [[COPY2]], [[COPY1]]
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[FMUL]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x1
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %2(s32)
    %4:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %3(s32)
    %5:_(<32 x s16>) = G_FMUL %4, %1
    %6:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %5(<32 x s16>), %2(s32)
    $r0 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0

...

# Check that the combiner handles patterns with G_FSUB operations (whitelisted in mayMIShiftElements).
# Similar to the FADD test, but using G_FSUB to verify the whitelist includes this operation.
---
name:            test_broadcast_extract_with_fsub
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1


    ; CHECK-LABEL: name: test_broadcast_extract_with_fsub
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s16>) = COPY [[COPY]](<32 x s16>)
    ; CHECK-NEXT: [[FSUB:%[0-9]+]]:_(<32 x s16>) = G_FSUB [[COPY2]], [[COPY1]]
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[FSUB]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x1
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %2(s32)
    %4:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %3(s32)
    %5:_(<32 x s16>) = G_FSUB %4, %1
    %6:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %5(<32 x s16>), %2(s32)
    $r0 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0

...

# Check that the combiner handles patterns with aie2p_v32accfloat_to_v32bf16 intrinsic.
# This intrinsic is whitelisted in mayMIShiftElements because it doesn't shift elements.
# The intrinsic converts accumulator floats (<32 x s32>) to bfloat16 (<32 x s16>).
---
name:            test_broadcast_extract_with_v32accfloat_to_v32bf16
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: test_broadcast_extract_with_v32accfloat_to_v32bf16
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY1]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v32accfloat.to.v32bf16), [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<16 x s32>), %1(s32)
    %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %2(s32)
    %8:_(<32 x s32>) = G_CONCAT_VECTORS %3(<16 x s32>), %3(<16 x s32>)
    %4:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v32accfloat.to.v32bf16), %8(<32 x s32>)
    %5:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %1(s32)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

# Check that the combiner handles complex chains with AIE2P intrinsics and unmerge operations.
# The broadcast flows through a G_INTRINSIC_W_SIDE_EFFECTS (bf.mul.conf) that transforms
# the type from <32 x s16> to <32 x s32>, then G_UNMERGE_VALUES extracts the first part,
# and we extract from position 0. The combiner should apply because the intrinsic is in
# the whitelist (mayMIShiftElements) and only the first unmerge output is used.
---
name:            test_broadcast_extract_with_intrinsic
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2, $x0

    ; CHECK-LABEL: name: test_broadcast_extract_with_intrinsic
    ; CHECK: liveins: $r1, $r2, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s16>) = COPY [[COPY1]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 60
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mul.conf), [[COPY2]](<32 x s16>), [[AIE_BROADCAST_VECTOR]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[INT]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %8:_(s32) = G_CONSTANT i32 0
    %50:_(<32 x s16>) = COPY $x0
    %200:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %50(<32 x s16>), %8(s32)
    %10:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %200(s32)
    %12:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %14:_(s32) = G_CONSTANT i32 60
    %13:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mul.conf), %10(<32 x s16>), %12(<32 x s16>), %14(s32)
    %15:_(<16 x s32>), %16:_(<16 x s32>) = G_UNMERGE_VALUES %13(<32 x s32>)
    %6:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %15(<16 x s32>), %8(s32)
    $r0 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0

...

# Check that the combiner handles patterns with G_FADD operations through concat/unmerge chains.
# The broadcast is in the first position of concat operations, flows through G_FADD (which is
# in the whitelist), then unmerge extracts the first part, and we extract from position 0.
# The combiner should apply the optimization.
---
name:            test_broadcast_extract_fmul
alignment:       1
exposesReturnsTwice: false
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r6, $r7, $x0

    ; CHECK-LABEL: name: test_broadcast_extract_fmul
    ; CHECK: liveins: $r6, $r7, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r7
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY2]](<16 x s32>), [[COPY3]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY3]](<16 x s32>), [[COPY3]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s32>), [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[COPY4]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY4]](<16 x s32>), [[COPY4]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS3]](<32 x s32>), [[CONCAT_VECTORS4]](<32 x s32>)
    ; CHECK-NEXT: [[FADD:%[0-9]+]]:_(<64 x s32>) = G_FADD [[CONCAT_VECTORS2]], [[CONCAT_VECTORS5]]
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s32>), [[UV1:%[0-9]+]]:_(<32 x s32>) = G_UNMERGE_VALUES [[FADD]](<64 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[UV]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %3:_(s32) = G_CONSTANT i32 0
    %50:_(<16 x s32>) = COPY $x0
    %200:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %50(<16 x s32>), %3(s32)
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %200(s32)
    %6:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %7:_(<16 x s32>) = COPY %4(<16 x s32>)
    %16:_(<32 x s32>) = G_CONCAT_VECTORS %5(<16 x s32>), %7(<16 x s32>)
    %17:_(<32 x s32>) = G_CONCAT_VECTORS %7(<16 x s32>), %7(<16 x s32>)
    %8:_(<64 x s32>) = G_CONCAT_VECTORS %16(<32 x s32>), %17(<32 x s32>)
    %9:_(<16 x s32>) = COPY %4(<16 x s32>)
    %18:_(<32 x s32>) = G_CONCAT_VECTORS %6(<16 x s32>), %9(<16 x s32>)
    %19:_(<32 x s32>) = G_CONCAT_VECTORS %9(<16 x s32>), %9(<16 x s32>)
    %10:_(<64 x s32>) = G_CONCAT_VECTORS %18(<32 x s32>), %19(<32 x s32>)
    %11:_(<64 x s32>) = G_FADD %8, %10
    %20:_(<32 x s32>), %21:_(<32 x s32>) = G_UNMERGE_VALUES %11(<64 x s32>)
    %12:_(<16 x s32>), %13:_(<16 x s32>) = G_UNMERGE_VALUES %20(<32 x s32>)
    %2:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %12(<16 x s32>), %3(s32)
    $r0 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0

...

# NEGATIVE: Check that the combiner rejects patterns where the initial extraction is from position 1.
# The broadcast source is extracted from position 1 (not position 0), so the combiner's check
# for "ExtractIdx->Value.getZExtValue() != 0" should reject this pattern.
---
name:            test_broadcast_extract_negative_not_position_zero
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_broadcast_extract_negative_not_position_zero
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[SEXT_INREG]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %1(s32)
    %3:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %2(s32)
    %4:_(s32) = G_CONSTANT i32 0
    %5:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %3(<32 x s16>), %4(s32)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

# NEGATIVE: Check that the combiner rejects patterns with G_BITCAST in the use chain.
# After the broadcast, there's a G_BITCAST which may require access to lanes beyond position 0.
# The combiner's check "if (Opcode == TargetOpcode::G_BITCAST) return false" should reject this.
---
name:            test_broadcast_extract_negative_bitcast
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_broadcast_extract_negative_bitcast
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[BITCAST]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %1(s32)
    %3:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %2(s32)
    %4:_(<16 x s32>) = G_BITCAST %3(<32 x s16>)
    %5:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %1(s32)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

# NEGATIVE: Check that the combiner rejects patterns with type mismatch.
# The extract source is <16 x s32> but the broadcast destination is <32 x s16>.
# Even though both are 512 bits, the types don't match exactly, so the combiner's
# check "if (ExtractSrcVecTy != BroadcastDstTy)" should reject this.
---
name:            test_broadcast_extract_negative_type_mismatch
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_broadcast_extract_negative_type_mismatch
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[SEXT_INREG]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<16 x s32>), %1(s32)
    %3:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %2(s32)
    %4:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %3(<32 x s16>), %1(s32)
    $r0 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0

...

# NEGATIVE: Check that the combiner rejects patterns with multiple different extracts.
# The broadcast is used to extract from both position 0 AND position 1, meaning we need
# more than just the first element. The combiner's single-use check "!MRI.hasOneUse(Reg)"
# should reject this because the broadcast has two extract uses.
---
name:            test_broadcast_extract_negative_multiple_extracts
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_broadcast_extract_negative_multiple_extracts
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY [[SEXT_INREG]](s32)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[ADD]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %1(s32)
    %3:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %2(s32)
    %4:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %3(<32 x s16>), %1(s32)
    %5:_(s32) = G_CONSTANT i32 1
    %6:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %3(<32 x s16>), %5(s32)
    %7:_(s32) = G_ADD %4, %6
    $r0 = COPY %7(s32)
    PseudoRET implicit $lr, implicit $r0

...

# NEGATIVE: Check that the combiner rejects patterns where broadcast is not the first concat operand.
# The G_CONCAT_VECTORS has G_IMPLICIT_DEF as the first operand and the broadcast as the second.
# The combiner's check "if (UserMI->getOperand(1).getReg() != Reg) return false" should reject
# this because the broadcast must be in position 0 of the concat for the optimization to be valid.
---
name:            test_broadcast_extract_negative_concat_not_first
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r7, $x0

    ; CHECK-LABEL: name: test_broadcast_extract_negative_concat_not_first
    ; CHECK: liveins: $r7, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r7
    %1:_(<16 x s32>) = COPY $x0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<16 x s32>), %2(s32)
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %3(s32)
    %6:_(<32 x s32>) = G_CONCAT_VECTORS %4(<16 x s32>), %5(<16 x s32>)
    %7:_(<16 x s32>), %8:_(<16 x s32>) = G_UNMERGE_VALUES %6(<32 x s32>)
    %9:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %7(<16 x s32>), %2(s32)
    $r0 = COPY %9(s32)
    PseudoRET implicit $lr, implicit $r0

...

# NEGATIVE: Check that the combiner rejects patterns where we extract from the second unmerge output.
# The G_UNMERGE_VALUES produces two outputs, but we extract from the second one (%16) instead
# of the first (%15). The combiner's check "if (OpCount && !MRI.use_empty(DefReg)) return false"
# should reject this because only the first unmerge output should be used.
---
name:            test_broadcast_extract_negative_second_unmerge
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2, $x0


    ; CHECK-LABEL: name: test_broadcast_extract_negative_second_unmerge
    ; CHECK: liveins: $r1, $r2, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY1]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 60
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mul.conf), [[AIE_BROADCAST_VECTOR]](<32 x s16>), [[AIE_BROADCAST_VECTOR1]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[INT]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %8:_(s32) = G_CONSTANT i32 0
    %50:_(<32 x s16>) = COPY $x0
    %200:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %50(<32 x s16>), %8(s32)
    %10:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %200(s32)
    %12:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %14:_(s32) = G_CONSTANT i32 60
    %13:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mul.conf), %10(<32 x s16>), %12(<32 x s16>), %14(s32)
    %15:_(<16 x s32>), %16:_(<16 x s32>) = G_UNMERGE_VALUES %13(<32 x s32>)
    %6:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %16(<16 x s32>), %8(s32)
    $r0 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0

...

# NEGATIVE: Check that the combiner rejects patterns where the first unmerge output has multiple uses.
# The first unmerge output (%15) is both extracted from AND returned implicitly by PseudoRET.
# The combiner's check "if (OpCount == 0 && !MRI.hasOneUse(DefReg)) return false" should reject
# this because the first unmerge output must have exactly one use.
---
name:            test_broadcast_extract_negative_first_unmerge_multiple_uses
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2, $x0


    ; CHECK-LABEL: name: test_broadcast_extract_negative_first_unmerge_multiple_uses
    ; CHECK: liveins: $r1, $r2, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY1]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 60
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mul.conf), [[AIE_BROADCAST_VECTOR]](<32 x s16>), [[AIE_BROADCAST_VECTOR1]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[INT]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit [[UV]](<16 x s32>)
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r2
    %8:_(s32) = G_CONSTANT i32 0
    %50:_(<32 x s16>) = COPY $x0
    %200:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %50(<32 x s16>), %8(s32)
    %10:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %200(s32)
    %12:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    %14:_(s32) = G_CONSTANT i32 60
    %13:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mul.conf), %10(<32 x s16>), %12(<32 x s16>), %14(s32)
    %15:_(<16 x s32>), %16:_(<16 x s32>) = G_UNMERGE_VALUES %13(<32 x s32>)
    %6:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %15(<16 x s32>), %8(s32)
    $r0 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0, implicit %15

...
