# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

...
---
name:            Retype_phi_with_cse
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: Retype_phi_with_cse
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 16
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[C]](p0) :: (load (s20), align 4)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:_(s1) = G_XOR [[TRUNC]], [[C4]]
  ; CHECK-NEXT:   G_BRCOND [[XOR]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s20) = G_PHI %10(s20), %bb.1, [[LOAD]](s20), %bb.0
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s20) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[ADD]](s20)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[PHI]](s20), [[C2]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.1
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(s20) = G_PHI %15(s20), %bb.2, [[LOAD]](s20), %bb.0
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:_(s20) = G_ADD [[PHI1]], [[C1]]
  ; CHECK-NEXT:   [[ZEXT1:%[0-9]+]]:_(s32) = G_ZEXT [[ADD1]](s20)
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[ADD1]](s20), [[C3]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP1]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:_(s32) = G_PHI [[ZEXT]](s32), %bb.1, [[ZEXT1]](s32), %bb.2
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit [[PHI2]](s32)
  bb.0:
    successors: %bb.4, %bb.5
    liveins: $r0

    %1:_(s32) = COPY $r0
    %0:_(s1) = G_TRUNC %1(s32)
    %3:_(p0) = G_CONSTANT i20 16
    %30:_(s20) = G_CONSTANT i20 1
    %40:_(s20) = G_CONSTANT i20 7
    %41:_(s20) = G_CONSTANT i20 8
    %2:_(s32) = G_LOAD %3(p0) :: (load (s32))
    G_BRCOND %0(s1), %bb.4
    G_BR %bb.5

  bb.4:
    successors: %bb.4(0x40000000), %bb.6(0x40000000)

    %20:_(s32) = G_PHI %29(s32), %bb.4, %2(s32), %bb.0
    %23:_(s20) = G_TRUNC %20(s32)
    %55:_(s20) = G_ADD %23, %30
    %29:_(s32) = G_ZEXT %55
    %60:_(s1) = G_ICMP intpred(ne), %23, %40
    G_BRCOND %60(s1), %bb.4
    G_BR %bb.6

  bb.5:
    successors: %bb.5(0x40000000), %bb.6(0x40000000)

    %4:_(s32) = G_PHI %50(s32), %bb.5, %2(s32), %bb.0
    %5:_(s20) = G_TRUNC %4(s32)
    %35:_(s20) = G_ADD %5, %30
    %50:_(s32) = G_ZEXT %35
    %61:_(s1) = G_ICMP intpred(ne), %35, %41
    G_BRCOND %61(s1), %bb.5
    G_BR %bb.6

  bb.6:
    %47:_(s32) = G_PHI %29(s32), %bb.4, %50(s32), %bb.5
    PseudoRET implicit $lr, implicit %47
...
