# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s \
# RUN:         -verify-machineinstrs -o - | FileCheck %s

# Tests for VSHIFT chain combiner that recognizes legalization patterns
# and simplifies them to COPY operations.

---
name:            test_vshift_chain_basic
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0

    ; CHECK-LABEL: name: test_vshift_chain_basic
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[AIE_PAD_VECTOR_UNDEF]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    %3:_(s32) = G_CONSTANT i32 16
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %2, %4, %3(s32)
    %6:_(s32) = G_CONSTANT i32 48
    %7:_(<16 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %7, %5, %6(s32)
    $x0 = COPY %8(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_with_copy
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0

    ; CHECK-LABEL: name: test_vshift_chain_with_copy
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[AIE_PAD_VECTOR_UNDEF]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    %3:_(s32) = G_CONSTANT i32 16
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %2, %4, %3(s32)
    %6:_(<16 x s32>) = COPY %5(<16 x s32>)
    %7:_(s32) = G_CONSTANT i32 48
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %9:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %8, %6, %7(s32)
    $x0 = COPY %9(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_negative_wrong_shifts
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0

    ; CHECK-LABEL: name: test_vshift_chain_negative_wrong_shifts
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[AIE_PAD_VECTOR_UNDEF]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    %3:_(s32) = G_CONSTANT i32 10
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %2, %4, %3(s32)
    %6:_(s32) = G_CONSTANT i32 30
    %7:_(<16 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %7, %5, %6(s32)
    $x0 = COPY %8(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_negative_no_concat
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_vshift_chain_negative_no_concat
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[COPY]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 16
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %0, %2, %1(s32)
    %4:_(s32) = G_CONSTANT i32 48
    %5:_(<16 x s32>) = G_IMPLICIT_DEF
    %6:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %5, %3, %4(s32)
    $x0 = COPY %6(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_negative_concat_not_undef
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0, $wl1

    ; CHECK-LABEL: name: test_vshift_chain_negative_concat_not_undef
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[CONCAT_VECTORS]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = COPY $wl1
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    %3:_(s32) = G_CONSTANT i32 16
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %2, %4, %3(s32)
    %6:_(s32) = G_CONSTANT i32 48
    %7:_(<16 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %7, %5, %6(s32)
    $x0 = COPY %8(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_negative_shift_src_not_undef
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0, $x0

    ; CHECK-LABEL: name: test_vshift_chain_negative_shift_src_not_undef
    ; CHECK: liveins: $wl0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[AIE_PAD_VECTOR_UNDEF]], [[COPY1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<8 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %2(<8 x s32>)
    %4:_(s32) = G_CONSTANT i32 16
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %3, %1, %4(s32)
    %6:_(s32) = G_CONSTANT i32 48
    %7:_(<16 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %7, %5, %6(s32)
    $x0 = COPY %8(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_vshift_chain_used_with_unmerge
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0

    ; CHECK-LABEL: name: test_vshift_chain_used_with_unmerge
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[AIE_PAD_VECTOR_UNDEF]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: $wl1 = COPY [[UV1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wl1
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    %3:_(s32) = G_CONSTANT i32 16
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %2, %4, %3(s32)
    %6:_(s32) = G_CONSTANT i32 48
    %7:_(<16 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %7, %5, %6(s32)
    %9:_(<8 x s32>), %10:_(<8 x s32>) = G_UNMERGE_VALUES %8(<16 x s32>)
    $wl0 = COPY %9(<8 x s32>)
    $wl1 = COPY %10(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0, implicit $wl1

...

---
name:            test_vshift_chain_multiple_uses
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0

    ; CHECK-LABEL: name: test_vshift_chain_multiple_uses
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[AIE_PAD_VECTOR_UNDEF]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: $x1 = COPY [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $x1
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    %3:_(s32) = G_CONSTANT i32 16
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %2, %4, %3(s32)
    %6:_(s32) = G_CONSTANT i32 48
    %7:_(<16 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %7, %5, %6(s32)
    $x0 = COPY %8(<16 x s32>)
    $x1 = COPY %2(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0, implicit $x1

...

---
name:            test_vshift_chain_invalid_shift
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $wl0

    ; CHECK-LABEL: name: test_vshift_chain_invalid_shift
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[AIE_PAD_VECTOR_UNDEF]], [[DEF]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 49
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF1]], [[AIE_VSHIFT_RIGHT]], [[C1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_VSHIFT_RIGHT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    %3:_(s32) = G_CONSTANT i32 16
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %2, %4, %3(s32)
    %6:_(s32) = G_CONSTANT i32 49
    %7:_(<16 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %7, %5, %6(s32)
    $x0 = COPY %8(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
