# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s \
# RUN:         -verify-machineinstrs -o - | FileCheck %s

# Tests for UNPAD/UNMERGE combiner that unifies redundant vector splitting operations

---
name:            test_unpad_dominates_unmerge
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_unpad_dominates_unmerge
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: $wl1 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: $wl2 = COPY [[UV1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wl1, implicit $wl2
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    %2:_(<8 x s32>), %3:_(<8 x s32>) = G_UNMERGE_VALUES %0(<16 x s32>)
    $wl0 = COPY %1(<8 x s32>)
    $wl1 = COPY %2(<8 x s32>)
    $wl2 = COPY %3(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0, implicit $wl1, implicit $wl2

...

---
name:            test_unmerge_dominates_unpad
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_unmerge_dominates_unpad
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: $wl1 = COPY [[UV1]](<8 x s32>)
    ; CHECK-NEXT: $wl2 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wl1, implicit $wl2
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<8 x s32>), %2:_(<8 x s32>) = G_UNMERGE_VALUES %0(<16 x s32>)
    %3:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    $wl0 = COPY %1(<8 x s32>)
    $wl1 = COPY %2(<8 x s32>)
    $wl2 = COPY %3(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0, implicit $wl1, implicit $wl2

...

---
name:            test_type_mismatch_no_combine_4way
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_type_mismatch_no_combine_4way
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    %2:_(<4 x s32>), %3:_(<4 x s32>), %4:_(<4 x s32>), %5:_(<4 x s32>) = G_UNMERGE_VALUES %0(<16 x s32>)
    $wl0 = COPY %1(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...

---
name:            test_4way_unmerge_unpad_dominates
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_4way_unmerge_unpad_dominates
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>), [[UV2:%[0-9]+]]:_(<4 x s32>), [[UV3:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $q0 = COPY [[UV]](<4 x s32>)
    ; CHECK-NEXT: $q1 = COPY [[UV]](<4 x s32>)
    ; CHECK-NEXT: $q2 = COPY [[UV1]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $q0, implicit $q1, implicit $q2
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    %2:_(<4 x s32>), %3:_(<4 x s32>), %4:_(<4 x s32>), %5:_(<4 x s32>) = G_UNMERGE_VALUES %0(<16 x s32>)
    $q0 = COPY %1(<4 x s32>)
    $q1 = COPY %2(<4 x s32>)
    $q2 = COPY %3(<4 x s32>)
    PseudoRET implicit $lr, implicit $q0, implicit $q1, implicit $q2

...

---
name:            test_different_sources_no_combine
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1

    ; CHECK-LABEL: name: test_different_sources_no_combine
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: $wl1 = COPY [[AIE_UNPAD_VECTOR1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wl1
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    %3:_(<8 x s32>), %4:_(<8 x s32>) = G_UNMERGE_VALUES %1(<16 x s32>)
    $wl0 = COPY %2(<8 x s32>)
    $wl1 = COPY %3(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0, implicit $wl1

...

---
name:            test_type_mismatch_no_combine
legalized:       false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_type_mismatch_no_combine
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %0(<16 x s32>)
    %2:_(<4 x s32>), %3:_(<4 x s32>), %4:_(<4 x s32>), %5:_(<4 x s32>) = G_UNMERGE_VALUES %0(<16 x s32>)
    $wl0 = COPY %1(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
