# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-postlegalizer-custom-combiner %s -verify-machineinstrs -o - | FileCheck %s

# Test for combine_offset_load_store_ptradd

# Case 1: Can be combined.

---
name:            combine_offset_load_ptradd_const
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: combine_offset_load_ptradd_const
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<16 x s16>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_OFFSET_LOAD]](<16 x s16>)
    %1:_(p0) = COPY $p0
    %293:_(s20) = G_CONSTANT i20 32
    %67:_(s20) = G_CONSTANT i20 64
    %68:_(p0) = nuw G_PTR_ADD %1, %67(s20)
    %295:_(<16 x s16>) = G_AIE_OFFSET_LOAD %68(p0), %293(s20)
    $wl0 = COPY %295:_(<16 x s16>)
...

# Case 2: Can't be combined.

---
name:            combine_offset_load_ptradd_reg
body:             |
  bb.0:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: combine_offset_load_ptradd_reg
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[COPY1]], [[TRUNC]](s20)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<16 x s16>) = G_AIE_OFFSET_LOAD [[PTR_ADD]](p0), [[C]](s20)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_OFFSET_LOAD]](<16 x s16>)
    %0:_(s32) = COPY $r0
    %1:_(p0) = COPY $p0
    %7:_(s20) = G_TRUNC %0(s32)
    %293:_(s20) = G_CONSTANT i20 32
    %67:_(s20) = G_CONSTANT i20 64
    %68:_(p0) = nuw G_PTR_ADD %1, %7(s20)
    %295:_(<16 x s16>) = G_AIE_OFFSET_LOAD %68(p0), %293(s20)
    $wl0 = COPY %295:_(<16 x s16>)
...

# Case 3: Can be combined (shared G_PTR_ADD).

---
name:            combine_offset_load_ptradd_reg_shared
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: combine_offset_load_ptradd_reg_shared
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<16 x s16>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C1]](s20)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD1:%[0-9]+]]:_(<16 x s16>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_OFFSET_LOAD]](<16 x s16>)
    ; CHECK-NEXT: $wl1 = COPY [[AIE_OFFSET_LOAD1]](<16 x s16>)
    %1:_(p0) = COPY $p0
    %293:_(s20) = G_CONSTANT i20 32
    %294:_(s20) = G_CONSTANT i20 32
    %68:_(p0) = nuw G_PTR_ADD %1, %294(s20)
    %295:_(<16 x s16>) = G_AIE_OFFSET_LOAD %68(p0), %293(s20)
    %296:_(<16 x s16>) = G_AIE_OFFSET_LOAD %1(p0), %294(s20)
    $wl0 = COPY %295:_(<16 x s16>)
    $wl1 = COPY %296:_(<16 x s16>)
...

# Case 4: Can be combined.

---
name:            combine_offset_store_ptradd_const
body:             |
  bb.0:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: combine_offset_store_ptradd_const
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[COPY]](<16 x s16>), [[COPY1]](p0), [[C]](s20)
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(p0) = COPY $p0
    %293:_(s20) = G_CONSTANT i20 32
    %67:_(s20) = G_CONSTANT i20 64
    %68:_(p0) = nuw G_PTR_ADD %1, %67(s20)
    G_AIE_OFFSET_STORE %0, %68, %293
...
