# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner -aie2prelegalizercombiner-only-enable-rule="combine_globalval_offset" %s -verify-machineinstrs -o - | FileCheck -DVER=2 %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner -aie2pprelegalizercombiner-only-enable-rule="combine_globalval_offset" %s -verify-machineinstrs -o - | FileCheck -DVER=2p %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner -aie2psprelegalizercombiner-only-enable-rule="combine_globalval_offset" %s -verify-machineinstrs -o - | FileCheck -DVER=2ps %s --check-prefix=AIE2PS
--- |

  %struct.anon = type { i32, i32, i8, i32, i32, i8, i32, i32, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i32, i32, i32, i32, i8, i32, i32, i8, i32, i8, i8, i8, i8 }

  @X = internal global %struct.anon zeroinitializer, align 4

  define dso_local noundef i32 @global_value_opt_offset(i32 noundef %x) {
  entry:
    %x.addr = alloca i32, align 4
    store i32 %x, ptr %x.addr, align 4
    %0 = load i32, ptr @X, align 4
    %1 = load i32, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 1), align 4
    %add = add nsw i32 %0, %1
    %2 = load i8, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 5), align 4
    %conv = sext i8 %2 to i32
    %add1 = add nsw i32 %add, %conv
    %3 = load i8, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 8), align 4
    %conv2 = sext i8 %3 to i32
    %add3 = add nsw i32 %add1, %conv2
    %4 = load i32, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 6), align 4
    %add4 = add nsw i32 %add3, %4
    %5 = load i8, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 38), align 1
    %conv5 = sext i8 %5 to i32
    %add6 = add nsw i32 %add4, %conv5
    %6 = load i8, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 33), align 4
    %conv7 = sext i8 %6 to i32
    %add8 = add nsw i32 %add6, %conv7
    %7 = load i32, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 26), align 4
    %add9 = add nsw i32 %add8, %7
    %8 = load i8, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 16), align 4
    %conv10 = sext i8 %8 to i32
    %add11 = add nsw i32 %add9, %conv10
    %9 = load i32, ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 27), align 4
    %add12 = add nsw i32 %add11, %9
    ret i32 %add12
  }

...
---
name:            global_value_opt_offset
legalized:       false
regBankSelected: false
stack:
  - { id: 0, name: x.addr, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1.entry:
    liveins: $r1

    ; AIE2-LABEL: name: global_value_opt_offset
    ; AIE2: liveins: $r1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2-NEXT: [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE target-flags(aie2-global) @X + 20
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 -20
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[GV]], [[C]](s20)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C1]](s20)
    ; AIE2-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C2]](s20)
    ; AIE2-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C3]](s20)
    ; AIE2-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C4]](s20)
    ; AIE2-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 91
    ; AIE2-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C5]](s20)
    ; AIE2-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C6]](s20)
    ; AIE2-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; AIE2-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C7]](s20)
    ; AIE2-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C8]](s20)
    ; AIE2-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C9]](s20)
    ; AIE2-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x.addr
    ; AIE2-NEXT: G_STORE [[COPY]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x.addr)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32) from @X)
    ; AIE2-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 1)`)
    ; AIE2-NEXT: [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[LOAD]], [[LOAD1]]
    ; AIE2-NEXT: [[LOAD2:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD2]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 5)`, align 4)
    ; AIE2-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[LOAD2]](s8)
    ; AIE2-NEXT: [[ADD1:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD]], [[SEXT]]
    ; AIE2-NEXT: [[LOAD3:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD3]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 8)`, align 4)
    ; AIE2-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[LOAD3]](s8)
    ; AIE2-NEXT: [[ADD2:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD1]], [[SEXT1]]
    ; AIE2-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 6)`)
    ; AIE2-NEXT: [[ADD3:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD2]], [[LOAD4]]
    ; AIE2-NEXT: [[LOAD5:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD5]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 38)`)
    ; AIE2-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[LOAD5]](s8)
    ; AIE2-NEXT: [[ADD4:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD3]], [[SEXT2]]
    ; AIE2-NEXT: [[LOAD6:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD6]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 33)`, align 4)
    ; AIE2-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[LOAD6]](s8)
    ; AIE2-NEXT: [[ADD5:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD4]], [[SEXT3]]
    ; AIE2-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 26)`)
    ; AIE2-NEXT: [[ADD6:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD5]], [[LOAD7]]
    ; AIE2-NEXT: [[LOAD8:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD8]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 16)`, align 4)
    ; AIE2-NEXT: [[SEXT4:%[0-9]+]]:_(s32) = G_SEXT [[LOAD8]](s8)
    ; AIE2-NEXT: [[ADD7:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD6]], [[SEXT4]]
    ; AIE2-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 27)`)
    ; AIE2-NEXT: [[ADD8:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD7]], [[LOAD9]]
    ; AIE2-NEXT: $r0 = COPY [[ADD8]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: global_value_opt_offset
    ; AIE2P: liveins: $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2P-NEXT: [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE target-flags(aie2p-global) @X + 20
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 -20
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[GV]], [[C]](s20)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C1]](s20)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C2]](s20)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C3]](s20)
    ; AIE2P-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C4]](s20)
    ; AIE2P-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 91
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C5]](s20)
    ; AIE2P-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C6]](s20)
    ; AIE2P-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; AIE2P-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C7]](s20)
    ; AIE2P-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2P-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C8]](s20)
    ; AIE2P-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2P-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C9]](s20)
    ; AIE2P-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x.addr
    ; AIE2P-NEXT: G_STORE [[COPY]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x.addr)
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32) from @X)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 1)`)
    ; AIE2P-NEXT: [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[LOAD]], [[LOAD1]]
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD2]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 5)`, align 4)
    ; AIE2P-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[LOAD2]](s8)
    ; AIE2P-NEXT: [[ADD1:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD]], [[SEXT]]
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD3]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 8)`, align 4)
    ; AIE2P-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[LOAD3]](s8)
    ; AIE2P-NEXT: [[ADD2:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD1]], [[SEXT1]]
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 6)`)
    ; AIE2P-NEXT: [[ADD3:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD2]], [[LOAD4]]
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD5]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 38)`)
    ; AIE2P-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[LOAD5]](s8)
    ; AIE2P-NEXT: [[ADD4:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD3]], [[SEXT2]]
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD6]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 33)`, align 4)
    ; AIE2P-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[LOAD6]](s8)
    ; AIE2P-NEXT: [[ADD5:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD4]], [[SEXT3]]
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 26)`)
    ; AIE2P-NEXT: [[ADD6:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD5]], [[LOAD7]]
    ; AIE2P-NEXT: [[LOAD8:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD8]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 16)`, align 4)
    ; AIE2P-NEXT: [[SEXT4:%[0-9]+]]:_(s32) = G_SEXT [[LOAD8]](s8)
    ; AIE2P-NEXT: [[ADD7:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD6]], [[SEXT4]]
    ; AIE2P-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 27)`)
    ; AIE2P-NEXT: [[ADD8:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD7]], [[LOAD9]]
    ; AIE2P-NEXT: $r0 = COPY [[ADD8]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: global_value_opt_offset
    ; AIE2PS: liveins: $r1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2PS-NEXT: [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE target-flags(aie2ps-global) @X + 20
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 -20
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[GV]], [[C]](s20)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C1]](s20)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C2]](s20)
    ; AIE2PS-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2PS-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C3]](s20)
    ; AIE2PS-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C4]](s20)
    ; AIE2PS-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 91
    ; AIE2PS-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C5]](s20)
    ; AIE2PS-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2PS-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C6]](s20)
    ; AIE2PS-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; AIE2PS-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C7]](s20)
    ; AIE2PS-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2PS-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C8]](s20)
    ; AIE2PS-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2PS-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C9]](s20)
    ; AIE2PS-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x.addr
    ; AIE2PS-NEXT: G_STORE [[COPY]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x.addr)
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32) from @X)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 1)`)
    ; AIE2PS-NEXT: [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[LOAD]], [[LOAD1]]
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD2]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 5)`, align 4)
    ; AIE2PS-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[LOAD2]](s8)
    ; AIE2PS-NEXT: [[ADD1:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD]], [[SEXT]]
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD3]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 8)`, align 4)
    ; AIE2PS-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[LOAD3]](s8)
    ; AIE2PS-NEXT: [[ADD2:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD1]], [[SEXT1]]
    ; AIE2PS-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 6)`)
    ; AIE2PS-NEXT: [[ADD3:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD2]], [[LOAD4]]
    ; AIE2PS-NEXT: [[LOAD5:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD5]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 38)`)
    ; AIE2PS-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[LOAD5]](s8)
    ; AIE2PS-NEXT: [[ADD4:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD3]], [[SEXT2]]
    ; AIE2PS-NEXT: [[LOAD6:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD6]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 33)`, align 4)
    ; AIE2PS-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[LOAD6]](s8)
    ; AIE2PS-NEXT: [[ADD5:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD4]], [[SEXT3]]
    ; AIE2PS-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 26)`)
    ; AIE2PS-NEXT: [[ADD6:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD5]], [[LOAD7]]
    ; AIE2PS-NEXT: [[LOAD8:%[0-9]+]]:_(s8) = G_LOAD [[PTR_ADD8]](p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 16)`, align 4)
    ; AIE2PS-NEXT: [[SEXT4:%[0-9]+]]:_(s32) = G_SEXT [[LOAD8]](s8)
    ; AIE2PS-NEXT: [[ADD7:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD6]], [[SEXT4]]
    ; AIE2PS-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 27)`)
    ; AIE2PS-NEXT: [[ADD8:%[0-9]+]]:_(s32) = nsw G_ADD [[ADD7]], [[LOAD9]]
    ; AIE2PS-NEXT: $r0 = COPY [[ADD8]](s32)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(s32) = COPY $r1
    %4:_(p0) = G_GLOBAL_VALUE @X
    %7:_(s20) = G_CONSTANT i20 4
    %6:_(p0) = G_PTR_ADD %4, %7(s20)
    %11:_(s20) = G_CONSTANT i20 20
    %10:_(p0) = G_PTR_ADD %4, %11(s20)
    %16:_(s20) = G_CONSTANT i20 32
    %15:_(p0) = G_PTR_ADD %4, %16(s20)
    %21:_(s20) = G_CONSTANT i20 24
    %20:_(p0) = G_PTR_ADD %4, %21(s20)
    %25:_(s20) = G_CONSTANT i20 91
    %24:_(p0) = G_PTR_ADD %4, %25(s20)
    %30:_(s20) = G_CONSTANT i20 80
    %29:_(p0) = G_PTR_ADD %4, %30(s20)
    %35:_(s20) = G_CONSTANT i20 52
    %34:_(p0) = G_PTR_ADD %4, %35(s20)
    %39:_(s20) = G_CONSTANT i20 40
    %38:_(p0) = G_PTR_ADD %4, %39(s20)
    %44:_(s20) = G_CONSTANT i20 56
    %43:_(p0) = G_PTR_ADD %4, %44(s20)
    %2:_(p0) = G_FRAME_INDEX %stack.0.x.addr
    G_STORE %1(s32), %2(p0) :: (store (s32) into %ir.x.addr)
    %3:_(s32) = G_LOAD %4(p0) :: (dereferenceable load (s32) from @X)
    %5:_(s32) = G_LOAD %6(p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 1)`)
    %8:_(s32) = nsw G_ADD %3, %5
    %9:_(s8) = G_LOAD %10(p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 5)`, align 4)
    %12:_(s32) = G_SEXT %9(s8)
    %13:_(s32) = nsw G_ADD %8, %12
    %14:_(s8) = G_LOAD %15(p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 8)`, align 4)
    %17:_(s32) = G_SEXT %14(s8)
    %18:_(s32) = nsw G_ADD %13, %17
    %19:_(s32) = G_LOAD %20(p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 6)`)
    %22:_(s32) = nsw G_ADD %18, %19
    %23:_(s8) = G_LOAD %24(p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 38)`)
    %26:_(s32) = G_SEXT %23(s8)
    %27:_(s32) = nsw G_ADD %22, %26
    %28:_(s8) = G_LOAD %29(p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 33)`, align 4)
    %31:_(s32) = G_SEXT %28(s8)
    %32:_(s32) = nsw G_ADD %27, %31
    %33:_(s32) = G_LOAD %34(p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 26)`)
    %36:_(s32) = nsw G_ADD %32, %33
    %37:_(s8) = G_LOAD %38(p0) :: (dereferenceable load (s8) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 16)`, align 4)
    %40:_(s32) = G_SEXT %37(s8)
    %41:_(s32) = nsw G_ADD %36, %40
    %42:_(s32) = G_LOAD %43(p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds (%struct.anon, ptr @X, i32 0, i32 27)`)
    %0:_(s32) = nsw G_ADD %41, %42
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
