# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

---
name:            vpush_int64_512
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 64, alignment: 32 }
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: vpush_int64_512
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[MOV_RLC_imm11_pseudo]], %subreg.sub_l_even, [[MOV_RLC_imm11_pseudo1]], %subreg.sub_l_odd
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VPUSH_hi_64_:%[0-9]+]]:vec512 = VPUSH_hi_64 [[DEF]], [[REG_SEQUENCE]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_64_]]
    ;
    ; AIE2PS-LABEL: name: vpush_int64_512
    ; AIE2PS: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[MOV_RLC_imm11_pseudo]], %subreg.sub_l_even, [[MOV_RLC_imm11_pseudo1]], %subreg.sub_l_odd
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[VPUSH_hi_64_:%[0-9]+]]:vec512 = VPUSH_hi_64 [[DEF]], [[REG_SEQUENCE]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_64_]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:gprregbank(s32) = G_CONSTANT i32 0
    %2:gprregbank(s64) = G_MERGE_VALUES %0, %1
    %3:vregbank(<8 x s64>) = G_IMPLICIT_DEF
    %4:vregbank(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI %3, %2(s64)
    PseudoRET implicit $lr, implicit %4
...
