# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s

---
name:            test_xor_v64s8
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.0:
    liveins: $x2, $x4

    ; AIE2-LABEL: name: test_xor_v64s8
    ; AIE2: liveins: $x2, $x4
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2-NEXT: [[VBNEG_LTZ_S32_:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_S32_1:%[0-9]+]]:ers8 = VBNEG_LTZ_S32 [[COPY]]
    ; AIE2-NEXT: [[VBAND:%[0-9]+]]:vec512 = VBAND [[VBNEG_LTZ_S32_]], [[COPY1]]
    ; AIE2-NEXT: [[VBNEG_LTZ_S32_2:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_S32_3:%[0-9]+]]:ers8 = VBNEG_LTZ_S32 [[COPY1]]
    ; AIE2-NEXT: [[VBAND1:%[0-9]+]]:mxm = VBAND [[VBNEG_LTZ_S32_2]], [[COPY]]
    ; AIE2-NEXT: [[VBOR:%[0-9]+]]:vec512 = VBOR [[VBAND1]], [[VBAND]]
    ; AIE2-NEXT: $x0 = COPY [[VBOR]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-LABEL: name: test_xor_v64s8
    ; AIE2P: liveins: $x2, $x4
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2P-NEXT: [[VBNEG_LTZ_s32_:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_s32_1:%[0-9]+]]:mr16_vcompare = VBNEG_LTZ_s32 [[COPY]]
    ; AIE2P-NEXT: [[VBAND:%[0-9]+]]:vec512 = VBAND [[VBNEG_LTZ_s32_]], [[COPY1]]
    ; AIE2P-NEXT: [[VBNEG_LTZ_s32_2:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_s32_3:%[0-9]+]]:mr16_vcompare = VBNEG_LTZ_s32 [[COPY1]]
    ; AIE2P-NEXT: [[VBAND1:%[0-9]+]]:mxm = VBAND [[VBNEG_LTZ_s32_2]], [[COPY]]
    ; AIE2P-NEXT: [[VBOR:%[0-9]+]]:vec512 = VBOR [[VBAND1]], [[VBAND]]
    ; AIE2P-NEXT: $x0 = COPY [[VBOR]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vregbank(<64 x s8>) = COPY $x2
    %1:vregbank(<64 x s8>) = COPY $x4
    %2:vregbank(<64 x s8>) = G_XOR %1, %0
    $x0 = COPY %2(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            test_xor_v32s16
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.0:
    liveins: $x2, $x4

    ; AIE2-LABEL: name: test_xor_v32s16
    ; AIE2: liveins: $x2, $x4
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2-NEXT: [[VBNEG_LTZ_S32_:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_S32_1:%[0-9]+]]:ers8 = VBNEG_LTZ_S32 [[COPY]]
    ; AIE2-NEXT: [[VBAND:%[0-9]+]]:vec512 = VBAND [[VBNEG_LTZ_S32_]], [[COPY1]]
    ; AIE2-NEXT: [[VBNEG_LTZ_S32_2:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_S32_3:%[0-9]+]]:ers8 = VBNEG_LTZ_S32 [[COPY1]]
    ; AIE2-NEXT: [[VBAND1:%[0-9]+]]:mxm = VBAND [[VBNEG_LTZ_S32_2]], [[COPY]]
    ; AIE2-NEXT: [[VBOR:%[0-9]+]]:vec512 = VBOR [[VBAND1]], [[VBAND]]
    ; AIE2-NEXT: $x0 = COPY [[VBOR]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-LABEL: name: test_xor_v32s16
    ; AIE2P: liveins: $x2, $x4
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2P-NEXT: [[VBNEG_LTZ_s32_:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_s32_1:%[0-9]+]]:mr16_vcompare = VBNEG_LTZ_s32 [[COPY]]
    ; AIE2P-NEXT: [[VBAND:%[0-9]+]]:vec512 = VBAND [[VBNEG_LTZ_s32_]], [[COPY1]]
    ; AIE2P-NEXT: [[VBNEG_LTZ_s32_2:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_s32_3:%[0-9]+]]:mr16_vcompare = VBNEG_LTZ_s32 [[COPY1]]
    ; AIE2P-NEXT: [[VBAND1:%[0-9]+]]:mxm = VBAND [[VBNEG_LTZ_s32_2]], [[COPY]]
    ; AIE2P-NEXT: [[VBOR:%[0-9]+]]:vec512 = VBOR [[VBAND1]], [[VBAND]]
    ; AIE2P-NEXT: $x0 = COPY [[VBOR]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vregbank(<32 x s16>) = COPY $x2
    %1:vregbank(<32 x s16>) = COPY $x4
    %2:vregbank(<32 x s16>) = G_XOR %1, %0
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            test_xor_v16s32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.0:
    liveins: $x2, $x4

    ; AIE2-LABEL: name: test_xor_v16s32
    ; AIE2: liveins: $x2, $x4
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2-NEXT: [[VBNEG_LTZ_S32_:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_S32_1:%[0-9]+]]:ers8 = VBNEG_LTZ_S32 [[COPY]]
    ; AIE2-NEXT: [[VBAND:%[0-9]+]]:vec512 = VBAND [[VBNEG_LTZ_S32_]], [[COPY1]]
    ; AIE2-NEXT: [[VBNEG_LTZ_S32_2:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_S32_3:%[0-9]+]]:ers8 = VBNEG_LTZ_S32 [[COPY1]]
    ; AIE2-NEXT: [[VBAND1:%[0-9]+]]:mxm = VBAND [[VBNEG_LTZ_S32_2]], [[COPY]]
    ; AIE2-NEXT: [[VBOR:%[0-9]+]]:vec512 = VBOR [[VBAND1]], [[VBAND]]
    ; AIE2-NEXT: $x0 = COPY [[VBOR]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-LABEL: name: test_xor_v16s32
    ; AIE2P: liveins: $x2, $x4
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2P-NEXT: [[VBNEG_LTZ_s32_:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_s32_1:%[0-9]+]]:mr16_vcompare = VBNEG_LTZ_s32 [[COPY]]
    ; AIE2P-NEXT: [[VBAND:%[0-9]+]]:vec512 = VBAND [[VBNEG_LTZ_s32_]], [[COPY1]]
    ; AIE2P-NEXT: [[VBNEG_LTZ_s32_2:%[0-9]+]]:mxm, dead [[VBNEG_LTZ_s32_3:%[0-9]+]]:mr16_vcompare = VBNEG_LTZ_s32 [[COPY1]]
    ; AIE2P-NEXT: [[VBAND1:%[0-9]+]]:mxm = VBAND [[VBNEG_LTZ_s32_2]], [[COPY]]
    ; AIE2P-NEXT: [[VBOR:%[0-9]+]]:vec512 = VBOR [[VBAND1]], [[VBAND]]
    ; AIE2P-NEXT: $x0 = COPY [[VBOR]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vregbank(<16 x s32>) = COPY $x2
    %1:vregbank(<16 x s32>) = COPY $x4
    %2:vregbank(<16 x s32>) = G_XOR %1, %0
    $x0 = COPY %2(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
