# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1 %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2PS %s

---
name: mul_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE1-LABEL: name: mul_s32
    ; AIE1: liveins: $r6, $r7
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r7
    ; AIE1-NEXT: [[MUL:%[0-9]+]]:gpr = MUL [[COPY]], [[COPY1]]
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[MUL]]
    ;
    ; AIE2-LABEL: name: mul_s32
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2-NEXT: [[MUL_mul_r_rr:%[0-9]+]]:er = MUL_mul_r_rr [[COPY]], [[COPY1]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[MUL_mul_r_rr]]
    ;
    ; AIE2P-LABEL: name: mul_s32
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2P-NEXT: [[MUL:%[0-9]+]]:er = MUL [[COPY]], [[COPY1]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[MUL]]
    ;
    ; AIE2PS-LABEL: name: mul_s32
    ; AIE2PS: liveins: $r6, $r7
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r7
    ; AIE2PS-NEXT: [[MUL:%[0-9]+]]:mlockid_reg = MUL [[COPY]], [[COPY1]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[MUL]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_MUL %0, %1
    PseudoRET implicit $lr, implicit %2
...
