# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefix=AIE2 -DER=er %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefix=AIE2P -DER=er %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefix=AIE2PS -DER=mlockid_reg %s

---
name: post-inc-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ;AIE2-LABEL: name:            post-inc-load

    ;AIE2: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2-NEXT: [[COPY_1:%[0-9]+]]:em = COPY $m0
    ;AIE2-NEXT: [[MOV__4:%[0-9]+]]:em = MOV_PD_imm10_pseudo 3
    ;AIE2-NEXT: [[LDA__6:%[0-9]+]]:er, [[LDA__7:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s32))
    ;AIE2-NEXT: [[LDA__8:%[0-9]+]]:er, [[LDA__9:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[LDA__7]], 28 :: (load (s32))
    ;AIE2-NEXT: [[LDA__10:%[0-9]+]]:er, [[LDA__11:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY_0]], -32 :: (load (s32))
    ;AIE2-NEXT: [[LDA__12:%[0-9]+]]:er, [[LDA__13:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY_0]], [[MOV__4]] :: (load (s32))
    ;AIE2-NEXT: [[LDA__14:%[0-9]+]]:er, [[LDA__15:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY_0]], 32 :: (load (s32))
    ;AIE2-NEXT: [[LDA__16:%[0-9]+]]:ep_as_32bit, [[LDA__17:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (p0), align 4)
    ;AIE2-NEXT: [[LDA__18:%[0-9]+]]:ep_as_32bit, [[LDA__19:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY_0]], 28 :: (load (p0), align 4)
    ;AIE2-NEXT: [[LDA__20:%[0-9]+]]:ep_as_32bit, [[LDA__21:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY_0]], -32 :: (load (p0), align 4)
    ;AIE2-NEXT: [[LDA__22:%[0-9]+]]:ep_as_32bit, [[LDA__23:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY_0]], [[MOV__4]] :: (load (p0), align 4)
    ;AIE2-NEXT: [[LDA__24:%[0-9]+]]:ep_as_32bit, [[LDA__25:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY_0]], 32 :: (load (p0), align 4)
    ;AIE2-NEXT: PseudoRET implicit $lr, implicit [[LDA__6]], implicit [[LDA__8]], implicit [[LDA__10]], implicit [[LDA__12]], implicit [[LDA__14]], implicit [[LDA__16]], implicit [[LDA__18]], implicit [[LDA__20]], implicit [[LDA__22]], implicit [[LDA__24]]
    ;
    ; AIE2P-LABEL: name: post-inc-load
    ; AIE2P: liveins: $p0, $m0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 3
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm1:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY]], [[COPY1]] :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm_imm:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[LDA_dms_lda_pstm_nrm1]], 28 :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm_imm2:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY]], -32 :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm2:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm3:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm4:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm5:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm6:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm7:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY]], [[COPY1]] :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm_imm4:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY]], 28 :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm_imm6:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm_imm7:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm_imm [[COPY]], -32 :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm8:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm9:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_pstm_nrm10:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm11:%[0-9]+]]:ep = LDA_dms_lda_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (p0), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LDA_dms_lda_pstm_nrm]], implicit [[LDA_dms_lda_pstm_nrm_imm]], implicit [[LDA_dms_lda_pstm_nrm_imm2]], implicit [[LDA_dms_lda_pstm_nrm2]], implicit [[LDA_dms_lda_pstm_nrm4]], implicit [[LDA_dms_lda_pstm_nrm6]], implicit [[LDA_dms_lda_pstm_nrm_imm4]], implicit [[LDA_dms_lda_pstm_nrm_imm6]], implicit [[LDA_dms_lda_pstm_nrm8]], implicit [[LDA_dms_lda_pstm_nrm10]]
    ;
    ; AIE2PS-LABEL: name: post-inc-load
    ; AIE2PS: liveins: $p0, $m0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 3
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm1:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm [[COPY]], [[COPY1]] :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm_imm:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm_imm [[LDA_dms_lda_pstm_nrm1]], 28 :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm_imm2:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm_imm [[COPY]], -32 :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm2:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm3:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm4:%[0-9]+]]:er, [[LDA_dms_lda_pstm_nrm5:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm6:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm7:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm [[COPY]], [[COPY1]] :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm_imm4:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm_imm [[COPY]], 28 :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm_imm6:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm_imm7:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm_imm [[COPY]], -32 :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm8:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm9:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_pstm_nrm10:%[0-9]+]]:ep_as_32bit, [[LDA_dms_lda_pstm_nrm11:%[0-9]+]]:ep = LDA_dms_lda_scalar_ld_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (p0), align 4)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA_dms_lda_pstm_nrm]], implicit [[LDA_dms_lda_pstm_nrm_imm]], implicit [[LDA_dms_lda_pstm_nrm_imm2]], implicit [[LDA_dms_lda_pstm_nrm2]], implicit [[LDA_dms_lda_pstm_nrm4]], implicit [[LDA_dms_lda_pstm_nrm6]], implicit [[LDA_dms_lda_pstm_nrm_imm4]], implicit [[LDA_dms_lda_pstm_nrm_imm6]], implicit [[LDA_dms_lda_pstm_nrm8]], implicit [[LDA_dms_lda_pstm_nrm10]]
    ;
    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %6:modregbank(s20) = G_CONSTANT i20 28
    %7:modregbank(s20) = G_CONSTANT i20 -32
    %71:modregbank(s20) = G_CONSTANT i20 3
    %72:modregbank(s20) = G_CONSTANT i20 32
    %8:gprregbank(s32), %11:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %5 :: (load (s32))
    %9:gprregbank(s32), %12:ptrregbank(p0) = G_AIE_POSTINC_LOAD %11, %6 :: (load (s32))
    %10:gprregbank(s32), %13:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (s32))
    %20:gprregbank(s32), %130:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %71 :: (load (s32))
    %30:gprregbank(s32), %131:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %72 :: (load (s32))
    %40:ptrregbank(p0), %151:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %5 :: (load (p0))
    %50:ptrregbank(p0), %152:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %6 :: (load (p0))
    %60:ptrregbank(p0), %153:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (p0))
    %70:ptrregbank(p0), %154:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %71 :: (load (p0))
    %80:ptrregbank(p0), %155:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %72 :: (load (p0))
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %20, implicit %30, implicit %40, implicit %50, implicit %60, implicit %70, implicit %80
...

---
name: post-inc-load-ext-s8-s16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ;AIE2-LABEL: name: post-inc-load-ext-s8-s16

    ;AIE2: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2-NEXT: [[COPY_1:%[0-9]+]]:em = COPY $m0
    ;AIE2-NEXT: [[MOV__4:%[0-9]+]]:em = MOV_PD_imm10_pseudo 8
    ;AIE2-NEXT: [[LDA__6:%[0-9]+]]:er, [[LDA__7:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s8))
    ;AIE2-NEXT: [[LDA__8:%[0-9]+]]:er, [[LDA__9:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm_imm [[LDA__7]], 7 :: (load (s8))
    ;AIE2-NEXT: [[LDA__10:%[0-9]+]]:er, [[LDA__11:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm_imm [[COPY_0]], -8 :: (load (s8))
    ;AIE2-NEXT: [[LDA__12:%[0-9]+]]:er, [[LDA__13:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm [[COPY_0]], [[MOV__4]] :: (load (s8))
    ;AIE2-NEXT: [[LDA__14:%[0-9]+]]:er, [[LDA__15:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm_imm [[COPY_0]], -1 :: (load (s8))
    ;AIE2-NEXT: [[MOV__16:%[0-9]+]]:em = MOV_PD_imm10_pseudo 14
    ;AIE2-NEXT: [[MOV__17:%[0-9]+]]:em = MOV_PD_imm10_pseudo -16
    ;AIE2-NEXT: [[MOV__18:%[0-9]+]]:em = MOV_PD_imm10_pseudo 16
    ;AIE2-NEXT: [[LDA__20:%[0-9]+]]:er, [[LDA__21:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__22:%[0-9]+]]:er, [[LDA__23:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[LDA__7]], [[MOV__16]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__24:%[0-9]+]]:er, [[LDA__25:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[COPY_0]], [[MOV__17]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__26:%[0-9]+]]:er, [[LDA__27:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[COPY_0]], [[MOV__18]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__28:%[0-9]+]]:er, [[LDA__29:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm_imm [[COPY_0]], 5 :: (load (s16))
    ;AIE2-NEXT: PseudoRET implicit $lr, implicit [[LDA__6]], implicit [[LDA__8]], implicit [[LDA__10]], implicit [[LDA__12]], implicit [[LDA__14]], implicit [[LDA__20]], implicit [[LDA__22]], implicit [[LDA__24]], implicit [[LDA__26]], implicit [[LDA__28]]

    ; AIE2P-LABEL: name: post-inc-load-ext-s8-s16
    ; AIE2P: liveins: $p0, $m0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[COPY1]] :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 7 :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -8 :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm_imm4:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -1 :: (load (s8))
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[COPY1]] :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 14 :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[COPY]], -16 :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm4:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm5:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LDA_s8_pstm_nrm]], implicit [[LDA_s8_pstm_nrm_imm]], implicit [[LDA_s8_pstm_nrm_imm2]], implicit [[LDA_s8_pstm_nrm2]], implicit [[LDA_s8_pstm_nrm_imm4]], implicit [[LDA_s16_pstm_nrm]], implicit [[LDA_s16_pstm_nrm_imm]], implicit [[LDA_s16_pstm_nrm_imm2]], implicit [[LDA_s16_pstm_nrm2]], implicit [[LDA_s16_pstm_nrm4]]
    ;
    ; AIE2PS-LABEL: name: post-inc-load-ext-s8-s16
    ; AIE2PS: liveins: $p0, $m0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[COPY1]] :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 7 :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -8 :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm_imm4:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -1 :: (load (s8))
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[COPY1]] :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 14 :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[COPY]], -16 :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm4:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm5:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA_s8_pstm_nrm]], implicit [[LDA_s8_pstm_nrm_imm]], implicit [[LDA_s8_pstm_nrm_imm2]], implicit [[LDA_s8_pstm_nrm2]], implicit [[LDA_s8_pstm_nrm_imm4]], implicit [[LDA_s16_pstm_nrm]], implicit [[LDA_s16_pstm_nrm_imm]], implicit [[LDA_s16_pstm_nrm_imm2]], implicit [[LDA_s16_pstm_nrm2]], implicit [[LDA_s16_pstm_nrm4]]

    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %6:modregbank(s20) = G_CONSTANT i20 7
    %7:modregbank(s20) = G_CONSTANT i20 -8
    %71:modregbank(s20) = G_CONSTANT i20 8
    %72:modregbank(s20) = G_CONSTANT i20 -1
    %8:gprregbank(s32), %11:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %5 :: (load (s8))
    %9:gprregbank(s32), %12:ptrregbank(p0) = G_AIE_POSTINC_LOAD %11, %6 :: (load (s8))
    %10:gprregbank(s32), %13:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (s8))
    %20:gprregbank(s32), %130:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %71 :: (load (s8))
    %30:gprregbank(s32), %131:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %72 :: (load (s8))
    %60:modregbank(s20) = G_CONSTANT i20 14
    %70:modregbank(s20) = G_CONSTANT i20 -16
    %710:modregbank(s20) = G_CONSTANT i20 16
    %720:modregbank(s20) = G_CONSTANT i20 5
    %80:gprregbank(s32), %116:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %5 :: (load (s16))
    %90:gprregbank(s32), %126:ptrregbank(p0) = G_AIE_POSTINC_LOAD %11, %60 :: (load (s16))
    %100:gprregbank(s32), %136:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %70 :: (load (s16))
    %200:gprregbank(s32), %137:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %710 :: (load (s16))
    %300:gprregbank(s32), %138:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %720 :: (load (s16))
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %20, implicit %30, implicit %80, implicit %90, implicit %100, implicit %200, implicit %300
...


---
name: post-inc-hbzext-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ;AIE2-LABEL: name:            post-inc-hbzext-load

    ;AIE2: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2-NEXT: [[COPY_1:%[0-9]+]]:em = COPY $m0
    ;AIE2-NEXT: [[MOV__4:%[0-9]+]]:em = MOV_PD_imm10_pseudo 8
    ;AIE2-NEXT: [[LDA__6:%[0-9]+]]:er, [[LDA__7:%[0-9]+]]:ep = LDA_U8_ag_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s8))
    ;AIE2-NEXT: [[LDA__8:%[0-9]+]]:er, [[LDA__9:%[0-9]+]]:ep = LDA_U8_ag_pstm_nrm_imm [[LDA__7]], 7 :: (load (s8))
    ;AIE2-NEXT: [[LDA__10:%[0-9]+]]:er, [[LDA__11:%[0-9]+]]:ep = LDA_U8_ag_pstm_nrm_imm [[COPY_0]], -8 :: (load (s8))
    ;AIE2-NEXT: [[LDA__12:%[0-9]+]]:er, [[LDA__13:%[0-9]+]]:ep = LDA_U8_ag_pstm_nrm [[COPY_0]], [[MOV__4]] :: (load (s8))
    ;AIE2-NEXT: [[LDA__14:%[0-9]+]]:er, [[LDA__15:%[0-9]+]]:ep = LDA_U8_ag_pstm_nrm_imm [[COPY_0]], -1 :: (load (s8))
    ;AIE2-NEXT: [[MOV__16:%[0-9]+]]:em = MOV_PD_imm10_pseudo 14
    ;AIE2-NEXT: [[MOV__17:%[0-9]+]]:em = MOV_PD_imm10_pseudo -16
    ;AIE2-NEXT: [[MOV__18:%[0-9]+]]:em = MOV_PD_imm10_pseudo 16
    ;AIE2-NEXT: [[LDA__20:%[0-9]+]]:er, [[LDA__21:%[0-9]+]]:ep = LDA_U16_ag_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__22:%[0-9]+]]:er, [[LDA__23:%[0-9]+]]:ep = LDA_U16_ag_pstm_nrm [[LDA__7]], [[MOV__16]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__24:%[0-9]+]]:er, [[LDA__25:%[0-9]+]]:ep = LDA_U16_ag_pstm_nrm [[COPY_0]], [[MOV__17]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__26:%[0-9]+]]:er, [[LDA__27:%[0-9]+]]:ep = LDA_U16_ag_pstm_nrm [[COPY_0]], [[MOV__18]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__28:%[0-9]+]]:er, [[LDA__29:%[0-9]+]]:ep = LDA_U16_ag_pstm_nrm_imm [[COPY_0]], 5 :: (load (s16))
    ;AIE2-NEXT: PseudoRET implicit $lr, implicit [[LDA__6]], implicit [[LDA__8]], implicit [[LDA__10]], implicit [[LDA__12]], implicit [[LDA__14]], implicit [[LDA__20]], implicit [[LDA__22]], implicit [[LDA__24]], implicit [[LDA__26]], implicit [[LDA__28]]

    ; AIE2P-LABEL: name: post-inc-hbzext-load
    ; AIE2P: liveins: $p0, $m0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2P-NEXT: [[LDA_u8_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm1:%[0-9]+]]:ep = LDA_u8_pstm_nrm [[COPY]], [[COPY1]] :: (load (s8))
    ; AIE2P-NEXT: [[LDA_u8_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_u8_pstm_nrm_imm [[LDA_u8_pstm_nrm1]], 7 :: (load (s8))
    ; AIE2P-NEXT: [[LDA_u8_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_u8_pstm_nrm_imm [[COPY]], -8 :: (load (s8))
    ; AIE2P-NEXT: [[LDA_u8_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm3:%[0-9]+]]:ep = LDA_u8_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; AIE2P-NEXT: [[LDA_u8_pstm_nrm_imm4:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_u8_pstm_nrm_imm [[COPY]], -1 :: (load (s8))
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2P-NEXT: [[LDA_u16_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm1:%[0-9]+]]:ep = LDA_u16_pstm_nrm [[COPY]], [[COPY1]] :: (load (s16))
    ; AIE2P-NEXT: [[LDA_u16_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_u16_pstm_nrm_imm [[LDA_u8_pstm_nrm1]], 14 :: (load (s16))
    ; AIE2P-NEXT: [[LDA_u16_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_u16_pstm_nrm_imm [[COPY]], -16 :: (load (s16))
    ; AIE2P-NEXT: [[LDA_u16_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm3:%[0-9]+]]:ep = LDA_u16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; AIE2P-NEXT: [[LDA_u16_pstm_nrm4:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm5:%[0-9]+]]:ep = LDA_u16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LDA_u8_pstm_nrm]], implicit [[LDA_u8_pstm_nrm_imm]], implicit [[LDA_u8_pstm_nrm_imm2]], implicit [[LDA_u8_pstm_nrm2]], implicit [[LDA_u8_pstm_nrm_imm4]], implicit [[LDA_u16_pstm_nrm]], implicit [[LDA_u16_pstm_nrm_imm]], implicit [[LDA_u16_pstm_nrm_imm2]], implicit [[LDA_u16_pstm_nrm2]], implicit [[LDA_u16_pstm_nrm4]]
    ;
    ; AIE2PS-LABEL: name: post-inc-hbzext-load
    ; AIE2PS: liveins: $p0, $m0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2PS-NEXT: [[LDA_u8_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm1:%[0-9]+]]:ep = LDA_u8_pstm_nrm [[COPY]], [[COPY1]] :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_u8_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_u8_pstm_nrm_imm [[LDA_u8_pstm_nrm1]], 7 :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_u8_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_u8_pstm_nrm_imm [[COPY]], -8 :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_u8_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm3:%[0-9]+]]:ep = LDA_u8_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_u8_pstm_nrm_imm4:%[0-9]+]]:[[ER]], [[LDA_u8_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_u8_pstm_nrm_imm [[COPY]], -1 :: (load (s8))
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2PS-NEXT: [[LDA_u16_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm1:%[0-9]+]]:ep = LDA_u16_pstm_nrm [[COPY]], [[COPY1]] :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_u16_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_u16_pstm_nrm_imm [[LDA_u8_pstm_nrm1]], 14 :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_u16_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_u16_pstm_nrm_imm [[COPY]], -16 :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_u16_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm3:%[0-9]+]]:ep = LDA_u16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_u16_pstm_nrm4:%[0-9]+]]:[[ER]], [[LDA_u16_pstm_nrm5:%[0-9]+]]:ep = LDA_u16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA_u8_pstm_nrm]], implicit [[LDA_u8_pstm_nrm_imm]], implicit [[LDA_u8_pstm_nrm_imm2]], implicit [[LDA_u8_pstm_nrm2]], implicit [[LDA_u8_pstm_nrm_imm4]], implicit [[LDA_u16_pstm_nrm]], implicit [[LDA_u16_pstm_nrm_imm]], implicit [[LDA_u16_pstm_nrm_imm2]], implicit [[LDA_u16_pstm_nrm2]], implicit [[LDA_u16_pstm_nrm4]]

    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %6:modregbank(s20) = G_CONSTANT i20 7
    %7:modregbank(s20) = G_CONSTANT i20 -8
    %71:modregbank(s20) = G_CONSTANT i20 8
    %72:modregbank(s20) = G_CONSTANT i20 -1
    %8:gprregbank(s32), %11:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %5 :: (load (s8))
    %9:gprregbank(s32), %12:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %11, %6 :: (load (s8))
    %10:gprregbank(s32), %13:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %7 :: (load (s8))
    %20:gprregbank(s32), %130:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %71 :: (load (s8))
    %30:gprregbank(s32), %131:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %72 :: (load (s8))
    %60:modregbank(s20) = G_CONSTANT i20 14
    %70:modregbank(s20) = G_CONSTANT i20 -16
    %710:modregbank(s20) = G_CONSTANT i20 16
    %720:modregbank(s20) = G_CONSTANT i20 5
    %80:gprregbank(s32), %116:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %5 :: (load (s16))
    %90:gprregbank(s32), %126:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %11, %60 :: (load (s16))
    %100:gprregbank(s32), %136:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %70 :: (load (s16))
    %200:gprregbank(s32), %137:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %710 :: (load (s16))
    %300:gprregbank(s32), %138:ptrregbank(p0) = G_AIE_POSTINC_ZEXTLOAD %0, %720 :: (load (s16))
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %20, implicit %30, implicit %80, implicit %90, implicit %100, implicit %200, implicit %300
...

---
name: post-inc-hbsext-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ;AIE2-LABEL: name:            post-inc-hbsext-load

    ;AIE2: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2-NEXT: [[COPY_1:%[0-9]+]]:em = COPY $m0
    ;AIE2-NEXT: [[MOV__4:%[0-9]+]]:em = MOV_PD_imm10_pseudo 8
    ;AIE2-NEXT: [[LDA__6:%[0-9]+]]:er, [[LDA__7:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s8))
    ;AIE2-NEXT: [[LDA__8:%[0-9]+]]:er, [[LDA__9:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm_imm [[LDA__7]], 7 :: (load (s8))
    ;AIE2-NEXT: [[LDA__10:%[0-9]+]]:er, [[LDA__11:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm_imm [[COPY_0]], -8 :: (load (s8))
    ;AIE2-NEXT: [[LDA__12:%[0-9]+]]:er, [[LDA__13:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm [[COPY_0]], [[MOV__4]] :: (load (s8))
    ;AIE2-NEXT: [[LDA__14:%[0-9]+]]:er, [[LDA__15:%[0-9]+]]:ep = LDA_S8_ag_pstm_nrm_imm [[COPY_0]], -1 :: (load (s8))
    ;AIE2-NEXT: [[MOV__16:%[0-9]+]]:em = MOV_PD_imm10_pseudo 14
    ;AIE2-NEXT: [[MOV__17:%[0-9]+]]:em = MOV_PD_imm10_pseudo -16
    ;AIE2-NEXT: [[MOV__18:%[0-9]+]]:em = MOV_PD_imm10_pseudo 16
    ;AIE2-NEXT: [[LDA__20:%[0-9]+]]:er, [[LDA__21:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__22:%[0-9]+]]:er, [[LDA__23:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[LDA__7]], [[MOV__16]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__24:%[0-9]+]]:er, [[LDA__25:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[COPY_0]], [[MOV__17]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__26:%[0-9]+]]:er, [[LDA__27:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm [[COPY_0]], [[MOV__18]] :: (load (s16))
    ;AIE2-NEXT: [[LDA__28:%[0-9]+]]:er, [[LDA__29:%[0-9]+]]:ep = LDA_S16_ag_pstm_nrm_imm [[COPY_0]], 5 :: (load (s16))
    ;AIE2-NEXT: PseudoRET implicit $lr, implicit [[LDA__6]], implicit [[LDA__8]], implicit [[LDA__10]], implicit [[LDA__12]], implicit [[LDA__14]], implicit [[LDA__20]], implicit [[LDA__22]], implicit [[LDA__24]], implicit [[LDA__26]], implicit [[LDA__28]]

    ; AIE2P-LABEL: name: post-inc-hbsext-load
    ; AIE2P: liveins: $p0, $m0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[COPY1]] :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 7 :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -8 :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; AIE2P-NEXT: [[LDA_s8_pstm_nrm_imm4:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -1 :: (load (s8))
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[COPY1]] :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 14 :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[COPY]], -16 :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; AIE2P-NEXT: [[LDA_s16_pstm_nrm4:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm5:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LDA_s8_pstm_nrm]], implicit [[LDA_s8_pstm_nrm_imm]], implicit [[LDA_s8_pstm_nrm_imm2]], implicit [[LDA_s8_pstm_nrm2]], implicit [[LDA_s8_pstm_nrm_imm4]], implicit [[LDA_s16_pstm_nrm]], implicit [[LDA_s16_pstm_nrm_imm]], implicit [[LDA_s16_pstm_nrm_imm2]], implicit [[LDA_s16_pstm_nrm2]], implicit [[LDA_s16_pstm_nrm4]]
    ;
    ; AIE2PS-LABEL: name: post-inc-hbsext-load
    ; AIE2PS: liveins: $p0, $m0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[COPY1]] :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 7 :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -8 :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm3:%[0-9]+]]:ep = LDA_s8_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; AIE2PS-NEXT: [[LDA_s8_pstm_nrm_imm4:%[0-9]+]]:[[ER]], [[LDA_s8_pstm_nrm_imm5:%[0-9]+]]:ep = LDA_s8_pstm_nrm_imm [[COPY]], -1 :: (load (s8))
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[COPY1]] :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm_imm:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm1:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[LDA_s8_pstm_nrm1]], 14 :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm_imm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm_imm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm_imm [[COPY]], -16 :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm2:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm3:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; AIE2PS-NEXT: [[LDA_s16_pstm_nrm4:%[0-9]+]]:[[ER]], [[LDA_s16_pstm_nrm5:%[0-9]+]]:ep = LDA_s16_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA_s8_pstm_nrm]], implicit [[LDA_s8_pstm_nrm_imm]], implicit [[LDA_s8_pstm_nrm_imm2]], implicit [[LDA_s8_pstm_nrm2]], implicit [[LDA_s8_pstm_nrm_imm4]], implicit [[LDA_s16_pstm_nrm]], implicit [[LDA_s16_pstm_nrm_imm]], implicit [[LDA_s16_pstm_nrm_imm2]], implicit [[LDA_s16_pstm_nrm2]], implicit [[LDA_s16_pstm_nrm4]]

    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %6:modregbank(s20) = G_CONSTANT i20 7
    %7:modregbank(s20) = G_CONSTANT i20 -8
    %71:modregbank(s20) = G_CONSTANT i20 8
    %72:modregbank(s20) = G_CONSTANT i20 -1
    %8:gprregbank(s32), %11:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %5 :: (load (s8))
    %9:gprregbank(s32), %12:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %11, %6 :: (load (s8))
    %10:gprregbank(s32), %13:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %7 :: (load (s8))
    %20:gprregbank(s32), %130:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %71 :: (load (s8))
    %30:gprregbank(s32), %131:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %72 :: (load (s8))
    %60:modregbank(s20) = G_CONSTANT i20 14
    %70:modregbank(s20) = G_CONSTANT i20 -16
    %710:modregbank(s20) = G_CONSTANT i20 16
    %720:modregbank(s20) = G_CONSTANT i20 5
    %80:gprregbank(s32), %116:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %5 :: (load (s16))
    %90:gprregbank(s32), %126:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %11, %60 :: (load (s16))
    %100:gprregbank(s32), %136:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %70 :: (load (s16))
    %200:gprregbank(s32), %137:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %710 :: (load (s16))
    %300:gprregbank(s32), %138:ptrregbank(p0) = G_AIE_POSTINC_SEXTLOAD %0, %720 :: (load (s16))
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %20, implicit %30, implicit %80, implicit %90, implicit %100, implicit %200, implicit %300
...
