# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefixes=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefixes=AIE2P %s

---
name: and_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE-LABEL: name: and_s32
    ; AIE: liveins: $r6, $r7
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r7
    ; AIE-NEXT: [[AND:%[0-9]+]]:gpr = AND [[COPY]], [[COPY1]]
    ; AIE-NEXT: PseudoRET implicit $lr, implicit [[AND]]
    ;
    ; AIE2-LABEL: name: and_s32
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2-NEXT: [[AND:%[0-9]+]]:er = AND [[COPY]], [[COPY1]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[AND]]
    ;
    ; AIE2P-LABEL: name: and_s32
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2P-NEXT: [[AND:%[0-9]+]]:er = AND [[COPY]], [[COPY1]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[AND]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_AND %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: and_mask_255_to_zext8
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE-LABEL: name: and_mask_255_to_zext8
    ; AIE: liveins: $r6
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE-NEXT: [[ZE8_:%[0-9]+]]:gpr = ZE8 [[COPY]]
    ; AIE-NEXT: PseudoRET implicit $lr, implicit [[ZE8_]]
    ;
    ; AIE2-LABEL: name: and_mask_255_to_zext8
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[EXTENDu8_:%[0-9]+]]:er = EXTENDu8 [[COPY]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[EXTENDu8_]]
    ;
    ; AIE2P-LABEL: name: and_mask_255_to_zext8
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[EXTEND_u8_:%[0-9]+]]:er = EXTEND_u8 [[COPY]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[EXTEND_u8_]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 255
    %2:gprregbank(s32) = G_AND %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: and_mask_65535_to_zext16
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE-LABEL: name: and_mask_65535_to_zext16
    ; AIE: liveins: $r6
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE-NEXT: [[ZE16_:%[0-9]+]]:gpr = ZE16 [[COPY]]
    ; AIE-NEXT: PseudoRET implicit $lr, implicit [[ZE16_]]
    ;
    ; AIE2-LABEL: name: and_mask_65535_to_zext16
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[EXTENDu16_:%[0-9]+]]:er = EXTENDu16 [[COPY]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[EXTENDu16_]]
    ;
    ; AIE2P-LABEL: name: and_mask_65535_to_zext16
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[EXTEND_u16_:%[0-9]+]]:er = EXTEND_u16 [[COPY]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[EXTEND_u16_]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 65535
    %2:gprregbank(s32) = G_AND %0, %1
    PseudoRET implicit $lr, implicit %2
...
