# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK,AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK,AIE2PS

---
name:            VEC256_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_maxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_w_idx_imm_pseudo:%[0-9]+]]:vec256 = VLD_w_idx_imm_pseudo [[COPY]], 224 :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLD_w_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 224
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC256_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_minOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_w_idx_imm_pseudo:%[0-9]+]]:vec256 = VLD_w_idx_imm_pseudo [[COPY]], -256 :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLD_w_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -256
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC256_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_overMaxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[VLD_w_idx_pseudo:%[0-9]+]]:vec256 = VLD_w_idx_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLD_w_idx_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 256
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC256_LOAD_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_outOfMinRangeOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -288
    ; CHECK-NEXT: [[VLD_w_idx_pseudo:%[0-9]+]]:vec256 = VLD_w_idx_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLD_w_idx_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -288
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC512_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_maxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 448 :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLD_x_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            VEC512_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_minOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], -512 :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLD_x_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            VEC512_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_overMaxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[VLD_x_idx_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLD_x_idx_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            VEC512_LOAD_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_outOfMinRangeOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; CHECK-NEXT: [[VLD_x_idx_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLD_x_idx_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            ACC512_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC512_LOAD_maxOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 448 :: (load (<8 x s64>))
    ; AIE2P-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx_imm]]
    ;
    ; AIE2PS-LABEL: name: ACC512_LOAD_maxOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 448 :: (load (<8 x s64>))
    ; AIE2PS-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_ld_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            ACC512_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC512_LOAD_minOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -512 :: (load (<8 x s64>))
    ; AIE2P-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx_imm]]
    ;
    ; AIE2PS-LABEL: name: ACC512_LOAD_minOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], -512 :: (load (<8 x s64>))
    ; AIE2PS-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_ld_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            ACC512_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC512_LOAD_overMaxOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>))
    ; AIE2P-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx]]
    ;
    ; AIE2PS-LABEL: name: ACC512_LOAD_overMaxOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>))
    ; AIE2PS-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_ld_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            ACC512_LOAD_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC512_LOAD_outOfMinRangeOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>))
    ; AIE2P-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx]]
    ;
    ; AIE2PS-LABEL: name: ACC512_LOAD_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>))
    ; AIE2PS-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_ld_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            VEC256_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; AIE2P-LABEL: name: VEC256_STORE_maxOffset
    ; AIE2P: liveins: $p0, $wl0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: VST_dmw_sts_w_idx_imm [[COPY]], [[COPY1]], 224 :: (store (<8 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC256_STORE_maxOffset
    ; AIE2PS: liveins: $p0, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: VST_dmw_sts_w_st_idx_imm [[COPY]], [[COPY1]], 224 :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 224
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC256_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; AIE2P-LABEL: name: VEC256_STORE_minOffset
    ; AIE2P: liveins: $p0, $wl0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: VST_dmw_sts_w_idx_imm [[COPY]], [[COPY1]], -256 :: (store (<8 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC256_STORE_minOffset
    ; AIE2PS: liveins: $p0, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: VST_dmw_sts_w_st_idx_imm [[COPY]], [[COPY1]], -256 :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -256
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC256_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; AIE2P-LABEL: name: VEC256_STORE_overMaxOffset
    ; AIE2P: liveins: $p0, $wl0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; AIE2P-NEXT: VST_dmw_sts_w_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC256_STORE_overMaxOffset
    ; AIE2PS: liveins: $p0, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; AIE2PS-NEXT: VST_dmw_sts_w_st_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 256
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC256_STORE_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; AIE2P-LABEL: name: VEC256_STORE_outOfMinRangeOffset
    ; AIE2P: liveins: $p0, $wl0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -288
    ; AIE2P-NEXT: VST_dmw_sts_w_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC256_STORE_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -288
    ; AIE2PS-NEXT: VST_dmw_sts_w_st_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -288
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC512_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; AIE2P-LABEL: name: VEC512_STORE_maxOffset
    ; AIE2P: liveins: $p0, $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY]], [[COPY1]], 448 :: (store (<16 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC512_STORE_maxOffset
    ; AIE2PS: liveins: $p0, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY]], [[COPY1]], 448 :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            VEC512_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; AIE2P-LABEL: name: VEC512_STORE_minOffset
    ; AIE2P: liveins: $p0, $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY]], [[COPY1]], -512 :: (store (<16 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC512_STORE_minOffset
    ; AIE2PS: liveins: $p0, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY]], [[COPY1]], -512 :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            VEC512_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; AIE2P-LABEL: name: VEC512_STORE_overMaxOffset
    ; AIE2P: liveins: $p0, $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: VST_dmx_sts_x_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC512_STORE_overMaxOffset
    ; AIE2PS: liveins: $p0, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            VEC512_STORE_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; AIE2P-LABEL: name: VEC512_STORE_outOfMinRangeOffset
    ; AIE2P: liveins: $p0, $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: VST_dmx_sts_x_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>))
    ;
    ; AIE2PS-LABEL: name: VEC512_STORE_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            ACC512_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; AIE2P-LABEL: name: ACC512_STORE_maxOffset
    ; AIE2P: liveins: $bmll0, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY]], [[COPY1]], 448 :: (store (<8 x s64>))
    ;
    ; AIE2PS-LABEL: name: ACC512_STORE_maxOffset
    ; AIE2PS: liveins: $bmll0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY]], [[COPY1]], 448 :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...

---
name:            ACC512_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; AIE2P-LABEL: name: ACC512_STORE_minOffset
    ; AIE2P: liveins: $bmll0, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY]], [[COPY1]], -512 :: (store (<8 x s64>))
    ;
    ; AIE2PS-LABEL: name: ACC512_STORE_minOffset
    ; AIE2PS: liveins: $bmll0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY]], [[COPY1]], -512 :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...

---
name:            ACC512_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; AIE2P-LABEL: name: ACC512_STORE_overMaxOffset
    ; AIE2P: liveins: $bmll0, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>))
    ;
    ; AIE2PS-LABEL: name: ACC512_STORE_overMaxOffset
    ; AIE2PS: liveins: $bmll0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...

---
name:            ACC512_STORE_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; AIE2P-LABEL: name: ACC512_STORE_outOfMinRangeOffset
    ; AIE2P: liveins: $bmll0, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>))
    ;
    ; AIE2PS-LABEL: name: ACC512_STORE_outOfMinRangeOffset
    ; AIE2PS: liveins: $bmll0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...

---
name:            VEC1024_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC1024_LOAD_maxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 384 :: (load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 448 :: (load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 384
    %0:vregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $y0 = COPY %0:vregbank(<32 x s32>)
...

---
name:            VEC1024_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC1024_LOAD_minOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], -448 :: (load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], -384 :: (load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -448
    %0:vregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $y0 = COPY %0:vregbank(<32 x s32>)
...

---
name:            VEC1024_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC1024_LOAD_overMaxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY]], 448
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[PADD_imm_pseudo]], 0 :: (load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[PADD_imm_pseudo]], 64 :: (load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    %0:vregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $y0 = COPY %0:vregbank(<32 x s32>)
...

---
name:            VEC1024_LOAD_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC1024_LOAD_outOfMinRangeOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; CHECK-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]]
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[PADD_mod_pseudo]], 0 :: (load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[PADD_mod_pseudo]], 64 :: (load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    %0:vregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $y0 = COPY %0:vregbank(<32 x s32>)
...

---
name:            VEC1024_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $lfl0
    ; AIE2P-LABEL: name: VEC1024_STORE_maxOffset
    ; AIE2P: liveins: $p0, $lfl0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY2]], [[COPY1]], 384 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY3]], [[COPY1]], 448 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: VEC1024_STORE_maxOffset
    ; AIE2PS: liveins: $p0, $lfl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY2]], [[COPY1]], 384 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY3]], [[COPY1]], 448 :: (store (<16 x s32>) into unknown-address + 64)
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 384
    G_AIE_OFFSET_STORE %0:vregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            VEC1024_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $y0
    ; AIE2P-LABEL: name: VEC1024_STORE_minOffset
    ; AIE2P: liveins: $p0, $y0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY2]], [[COPY1]], -512 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY3]], [[COPY1]], -448 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: VEC1024_STORE_minOffset
    ; AIE2PS: liveins: $p0, $y0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY2]], [[COPY1]], -512 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY3]], [[COPY1]], -448 :: (store (<16 x s32>) into unknown-address + 64)
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    G_AIE_OFFSET_STORE %0:vregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            VEC1024_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $y0
    ; AIE2P-LABEL: name: VEC1024_STORE_overMaxOffset
    ; AIE2P: liveins: $p0, $y0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY1]], 448
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY2]], [[PADD_imm_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY3]], [[PADD_imm_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: VEC1024_STORE_overMaxOffset
    ; AIE2PS: liveins: $p0, $y0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY1]], 448
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY2]], [[PADD_imm_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY3]], [[PADD_imm_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:vregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            VEC1024_STORE_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $y0
    ; AIE2P-LABEL: name: VEC1024_STORE_outOfMinRangeOffset
    ; AIE2P: liveins: $p0, $y0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY1]], [[MOV_PD_imm11_pseudo]]
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY2]], [[PADD_mod_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY3]], [[PADD_mod_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: VEC1024_STORE_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0, $y0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY1]], [[MOV_PD_imm11_pseudo]]
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY2]], [[PADD_mod_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY3]], [[PADD_mod_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    G_AIE_OFFSET_STORE %0:vregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            ACC1024_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC1024_LOAD_maxOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 384 :: (load (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 448 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC1024_LOAD_maxOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 384 :: (load (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 448 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 384
    %0:accregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $cml0 = COPY %0:accregbank(<32 x s32>)
...

---
name:            ACC1024_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC1024_LOAD_minOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -448 :: (load (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -384 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC1024_LOAD_minOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], -448 :: (load (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], -384 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -448
    %0:accregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $cml0 = COPY %0:accregbank(<32 x s32>)
...

---
name:            ACC1024_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC1024_LOAD_overMaxOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY]], 448
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_imm_pseudo]], 0 :: (load (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_imm_pseudo]], 64 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC1024_LOAD_overMaxOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY]], 448
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_imm_pseudo]], 0 :: (load (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_imm_pseudo]], 64 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    %0:accregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $cml0 = COPY %0:accregbank(<32 x s32>)
...

---
name:            ACC1024_LOAD_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC1024_LOAD_outOfMinRangeOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]]
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_mod_pseudo]], 0 :: (load (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_mod_pseudo]], 64 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC1024_LOAD_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]]
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_mod_pseudo]], 0 :: (load (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_mod_pseudo]], 64 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    %0:accregbank(<32 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s32>))
    $cml0 = COPY %0:accregbank(<32 x s32>)
...

---
name:            ACC1024_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $cml0
    ; AIE2P-LABEL: name: ACC1024_STORE_maxOffset
    ; AIE2P: liveins: $p0, $cml0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY1]], 384 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY1]], 448 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: ACC1024_STORE_maxOffset
    ; AIE2PS: liveins: $p0, $cml0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY1]], 384 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY1]], 448 :: (store (<16 x s32>) into unknown-address + 64)
    %0:accregbank(<32 x s32>) = COPY $cml0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 384
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            ACC1024_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $cml0
    ; AIE2P-LABEL: name: ACC1024_STORE_minOffset
    ; AIE2P: liveins: $p0, $cml0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY1]], -512 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY1]], -448 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: ACC1024_STORE_minOffset
    ; AIE2PS: liveins: $p0, $cml0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY1]], -512 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY1]], -448 :: (store (<16 x s32>) into unknown-address + 64)
    %0:accregbank(<32 x s32>) = COPY $cml0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            ACC1024_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $cml0
    ; AIE2P-LABEL: name: ACC1024_STORE_overMaxOffset
    ; AIE2P: liveins: $p0, $cml0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY1]], 448
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[PADD_imm_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[PADD_imm_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: ACC1024_STORE_overMaxOffset
    ; AIE2PS: liveins: $p0, $cml0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY1]], 448
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[PADD_imm_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[PADD_imm_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    %0:accregbank(<32 x s32>) = COPY $cml0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            ACC1024_STORE_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $cml0
    ; AIE2P-LABEL: name: ACC1024_STORE_outOfMinRangeOffset
    ; AIE2P: liveins: $p0, $cml0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY1]], [[MOV_PD_imm11_pseudo]]
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[PADD_mod_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[PADD_mod_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: ACC1024_STORE_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0, $cml0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY1]], [[MOV_PD_imm11_pseudo]]
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[PADD_mod_pseudo]], 0 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[PADD_mod_pseudo]], 64 :: (store (<16 x s32>) into unknown-address + 64)
    %0:accregbank(<32 x s32>) = COPY $cml0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s32>))
...

---
name:            ACC2048_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC2048_LOAD_maxOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 256 :: (load (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 320 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 384 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 448 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC2048_LOAD_maxOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 256 :: (load (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 320 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 384 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 448 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 256
    %0:accregbank(<32 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s64>))
    $dm0 = COPY %0:accregbank(<32 x s64>)
...

---
name:            ACC2048_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC2048_LOAD_minOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -320 :: (load (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -256 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -192 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -128 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC2048_LOAD_minOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], -320 :: (load (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], -256 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], -192 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], -128 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -320
    %0:accregbank(<32 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s64>))
    $dm0 = COPY %0:accregbank(<32 x s64>)
...

---
name:            ACC2048_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC2048_LOAD_overMaxOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY]], 320
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_imm_pseudo]], 0 :: (load (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_imm_pseudo]], 64 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_imm_pseudo]], 128 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_imm_pseudo]], 192 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC2048_LOAD_overMaxOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY]], 320
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_imm_pseudo]], 0 :: (load (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_imm_pseudo]], 64 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_imm_pseudo]], 128 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_imm_pseudo]], 192 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 320
    %0:accregbank(<32 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s64>))
    $dm0 = COPY %0:accregbank(<32 x s64>)
...

---
name:            ACC2048_LOAD_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: ACC2048_LOAD_outOfMinRangeOffset
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]]
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_mod_pseudo]], 0 :: (load (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_mod_pseudo]], 64 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_mod_pseudo]], 128 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[PADD_mod_pseudo]], 192 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: ACC2048_LOAD_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[MOV_PD_imm11_pseudo]]
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_mod_pseudo]], 0 :: (load (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_mod_pseudo]], 64 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_mod_pseudo]], 128 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[PADD_mod_pseudo]], 192 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    %0:accregbank(<32 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<32 x s64>))
    $dm0 = COPY %0:accregbank(<32 x s64>)
...

---
name:            ACC2048_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0
    ; AIE2P-LABEL: name: ACC2048_STORE_maxOffset
    ; AIE2P: liveins: $p0, $dm0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY1]], 256 :: (store (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY1]], 320 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[COPY1]], 384 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY5]], [[COPY1]], 448 :: (store (<8 x s64>) into unknown-address + 192)
    ;
    ; AIE2PS-LABEL: name: ACC2048_STORE_maxOffset
    ; AIE2PS: liveins: $p0, $dm0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY1]], 256 :: (store (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY1]], 320 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[COPY1]], 384 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY5]], [[COPY1]], 448 :: (store (<8 x s64>) into unknown-address + 192)
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 256
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s64>))
...

---
name:            ACC2048_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0
    ; AIE2P-LABEL: name: ACC2048_STORE_minOffset
    ; AIE2P: liveins: $p0, $dm0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY1]], -512 :: (store (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY1]], -448 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[COPY1]], -384 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY5]], [[COPY1]], -320 :: (store (<8 x s64>) into unknown-address + 192)
    ;
    ; AIE2PS-LABEL: name: ACC2048_STORE_minOffset
    ; AIE2PS: liveins: $p0, $dm0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY1]], -512 :: (store (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY1]], -448 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[COPY1]], -384 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY5]], [[COPY1]], -320 :: (store (<8 x s64>) into unknown-address + 192)
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s64>))
...

---
name:            ACC2048_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0
    ; AIE2P-LABEL: name: ACC2048_STORE_overMaxOffset
    ; AIE2P: liveins: $p0, $dm0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY1]], 320
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[PADD_imm_pseudo]], 0 :: (store (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[PADD_imm_pseudo]], 64 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[PADD_imm_pseudo]], 128 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY5]], [[PADD_imm_pseudo]], 192 :: (store (<8 x s64>) into unknown-address + 192)
    ;
    ; AIE2PS-LABEL: name: ACC2048_STORE_overMaxOffset
    ; AIE2PS: liveins: $p0, $dm0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[PADD_imm_pseudo:%[0-9]+]]:ep = PADD_imm_pseudo [[COPY1]], 320
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[PADD_imm_pseudo]], 0 :: (store (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[PADD_imm_pseudo]], 64 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[PADD_imm_pseudo]], 128 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY5]], [[PADD_imm_pseudo]], 192 :: (store (<8 x s64>) into unknown-address + 192)
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 320
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s64>))
...

---
name:            ACC2048_STORE_outOfMinRangeOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0
    ; AIE2P-LABEL: name: ACC2048_STORE_outOfMinRangeOffset
    ; AIE2P: liveins: $p0, $dm0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2P-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY1]], [[MOV_PD_imm11_pseudo]]
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[PADD_mod_pseudo]], 0 :: (store (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[PADD_mod_pseudo]], 64 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[PADD_mod_pseudo]], 128 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY5]], [[PADD_mod_pseudo]], 192 :: (store (<8 x s64>) into unknown-address + 192)
    ;
    ; AIE2PS-LABEL: name: ACC2048_STORE_outOfMinRangeOffset
    ; AIE2PS: liveins: $p0, $dm0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo -576
    ; AIE2PS-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY1]], [[MOV_PD_imm11_pseudo]]
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[PADD_mod_pseudo]], 0 :: (store (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[PADD_mod_pseudo]], 64 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[PADD_mod_pseudo]], 128 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY5]], [[PADD_mod_pseudo]], 192 :: (store (<8 x s64>) into unknown-address + 192)
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    G_AIE_OFFSET_STORE %0:accregbank(<32 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<32 x s64>))
...
