# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefixes=CHECK,AIE2P -DER=er %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefixes=CHECK,AIE2PS -DER=mlockid_reg %s



---
name: pre-inc-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0, $r1
    ; AIE2P-LABEL: name: pre-inc-store
    ; AIE2P: liveins: $p0, $p1, $r0, $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 10
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], -32 :: (store (s32))
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 28 :: (store (s32))
    ; AIE2P-NEXT: ST_dms_sts_idx [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:edj = COPY [[COPY2]]
    ; AIE2P-NEXT: ST_dms_sts_idx [[COPY2]], [[COPY]], [[COPY3]] :: (store (s32))
    ; AIE2P-NEXT: ST_dms_sts_idx [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (store (s32))
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 16 :: (store (s32))
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY1]], [[COPY]], 16 :: (store (p0), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr

    ; AIE2PS-LABEL: name: pre-inc-store
    ; AIE2PS: liveins: $p0, $p1, $r0, $r1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 10
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY2]], [[COPY]], -32 :: (store (s32))
    ; AIE2PS-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY2]], [[COPY]], 28 :: (store (s32))
    ; AIE2PS-NEXT: ST_dms_sts_scalar_st_idx [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:edj = COPY [[COPY2]]
    ; AIE2PS-NEXT: ST_dms_sts_scalar_st_idx [[COPY2]], [[COPY]], [[COPY3]] :: (store (s32))
    ; AIE2PS-NEXT: ST_dms_sts_scalar_st_idx [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (store (s32))
    ; AIE2PS-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY2]], [[COPY]], 16 :: (store (s32))
    ; AIE2PS-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY1]], [[COPY]], 16 :: (store (p0), align 4)
    ; AIE2PS-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %8:ptrregbank(p0) = COPY $p1
    %1:modregbank(s20) = G_CONSTANT i20 -32
    %2:modregbank(s20) = G_CONSTANT i20 28
    %3:modregbank(s20) = G_CONSTANT i20 32
    %5:modregbank(s20) = G_CONSTANT i20 10
    %6:modregbank(s20) = G_CONSTANT i20 16
    %4:gprregbank(s32) = COPY $r0
    G_AIE_OFFSET_STORE %4, %0, %1 :: (store (s32))
    G_AIE_OFFSET_STORE %4, %0, %2 :: (store (s32))
    G_AIE_OFFSET_STORE %4, %0, %3 :: (store (s32))
    G_AIE_OFFSET_STORE %4, %0, %4 :: (store (s32))
    G_AIE_OFFSET_STORE %4, %0, %5 :: (store (s32))
    G_AIE_OFFSET_STORE %4, %0, %6 :: (store (s32))
    G_AIE_OFFSET_STORE %8, %0, %6 :: (store (p0))
    PseudoRET implicit $lr
...

---
name: pre-inc-hb-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: pre-inc-hb-store
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:[[ER]] = COPY $r0
    ; CHECK-NEXT: ST_s16_idx_imm [[COPY1]], [[COPY]], -16, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; CHECK-NEXT: ST_s16_idx_imm [[COPY1]], [[COPY]], 14, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; CHECK-NEXT: ST_s16_idx [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY [[COPY1]]
    ; CHECK-NEXT: ST_s16_idx [[COPY1]], [[COPY]], [[COPY2]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; CHECK-NEXT: ST_s16_idx [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; CHECK-NEXT: ST_s16_idx_imm [[COPY1]], [[COPY]], -2, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 8
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: ST_s8_idx_imm [[COPY1]], [[COPY]], -8, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: ST_s8_idx_imm [[COPY1]], [[COPY]], 7, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: ST_s8_idx [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo2]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:edj = COPY [[COPY3]]
    ; CHECK-NEXT: ST_s8_idx [[COPY1]], [[COPY]], [[COPY4]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: ST_s8_idx_imm [[COPY1]], [[COPY]], 4, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: ST_s8_idx_imm [[COPY1]], [[COPY]], -1, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s20) = G_CONSTANT i20 -16
    %2:modregbank(s20) = G_CONSTANT i20 14
    %3:modregbank(s20) = G_CONSTANT i20 5
    %5:modregbank(s20) = G_CONSTANT i20 16
    %6:modregbank(s20) = G_CONSTANT i20 -2
    %4:gprregbank(s32) = COPY $r0
    G_AIE_OFFSET_STORE %4, %0, %1 :: (store (s16))
    G_AIE_OFFSET_STORE %4, %0, %2 :: (store (s16))
    G_AIE_OFFSET_STORE %4, %0, %3 :: (store (s16))
    G_AIE_OFFSET_STORE %4, %0, %4 :: (store (s16))
    G_AIE_OFFSET_STORE %4, %0, %5 :: (store (s16))
    G_AIE_OFFSET_STORE %4, %0, %6 :: (store (s16))
    %10:gprregbank(s20) = G_CONSTANT i20 -8
    %20:modregbank(s20) = G_CONSTANT i20 7
    %30:modregbank(s20) = G_CONSTANT i20 8
    %50:modregbank(s20) = G_CONSTANT i20 4
    %60:modregbank(s20) = G_CONSTANT i20 -1
    %40:gprregbank(s32) = COPY $r0
    G_AIE_OFFSET_STORE %4, %0, %10 :: (store (s8))
    G_AIE_OFFSET_STORE %4, %0, %20 :: (store (s8))
    G_AIE_OFFSET_STORE %4, %0, %30 :: (store (s8))
    G_AIE_OFFSET_STORE %4, %0, %40 :: (store (s8))
    G_AIE_OFFSET_STORE %4, %0, %50 :: (store (s8))
    G_AIE_OFFSET_STORE %4, %0, %60 :: (store (s8))
    PseudoRET implicit $lr
...
