# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS


---
name:            _512bit_extract_64bit
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0

    ; AIE2P-LABEL: name: _512bit_extract_64bit
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VEXTRACT_64_vec_extract_imm_vaddSign1_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_imm_vaddSign1 [[COPY]], 1, implicit $vaddsign1
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_imm_vaddSign1_]]
    ;
    ; AIE2PS-LABEL: name: _512bit_extract_64bit
    ; AIE2PS: liveins: $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[VEXTRACT_64_vec_extract_imm_vaddSign1_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_imm_vaddSign1 [[COPY]], 1, implicit $vaddsign1
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_imm_vaddSign1_]]
    %1:vregbank(<8 x s64>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:            _512bit_extract_64bit_dyn
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0, $r0

    ; AIE2P-LABEL: name: _512bit_extract_64bit_dyn
    ; AIE2P: liveins: $x0, $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[VEXTRACT_64_vec_extract_r_vaddSign1_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_r_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_r_vaddSign1_]]
    ;
    ; AIE2PS-LABEL: name: _512bit_extract_64bit_dyn
    ; AIE2PS: liveins: $x0, $r0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r0
    ; AIE2PS-NEXT: [[VEXTRACT_64_vec_extract_r_vaddSign1_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_r_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_r_vaddSign1_]]
    %1:vregbank(<8 x s64>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %0:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:            _512bit_extract_64bit_accregbank
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; AIE2P-LABEL: name: _512bit_extract_64bit_accregbank
    ; AIE2P: liveins: $bmll0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:mxm = COPY [[COPY]]
    ; AIE2P-NEXT: [[VEXTRACT_64_vec_extract_imm_vaddSign1_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_imm_vaddSign1 [[COPY1]], 1, implicit $vaddsign1
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_imm_vaddSign1_]]
    ;
    ; AIE2PS-LABEL: name: _512bit_extract_64bit_accregbank
    ; AIE2PS: liveins: $bmll0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mxm = COPY [[COPY]]
    ; AIE2PS-NEXT: [[VEXTRACT_64_vec_extract_imm_vaddSign1_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_imm_vaddSign1 [[COPY1]], 1, implicit $vaddsign1
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_imm_vaddSign1_]]
    %1:accregbank(<8 x s64>) = COPY $bmll0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:            _512bit_extract_64bit_unsigned
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0
    ; AIE2P-LABEL: name: _512bit_extract_64bit_unsigned
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VEXTRACT_64_vec_extract_imm_vaddSign0_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_imm_vaddSign0 [[COPY]], 1, implicit $vaddsign0
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_imm_vaddSign0_]]
    ;
    ; AIE2PS-LABEL: name: _512bit_extract_64bit_unsigned
    ; AIE2PS: liveins: $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[VEXTRACT_64_vec_extract_imm_vaddSign0_:%[0-9]+]]:el = VEXTRACT_64_vec_extract_imm_vaddSign0 [[COPY]], 1, implicit $vaddsign0
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VEXTRACT_64_vec_extract_imm_vaddSign0_]]
    %1:vregbank(<8 x s64>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:gprregbank(s64) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
