# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2PS %s

---
name: global_value_ptr
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; AIE2-LABEL: name: global_value_ptr
    ; AIE2: [[MOVXM_lng_cg:%[0-9]+]]:ep_as_32bit = MOVXM_lng_cg target-flags(aie2-global) &x
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[MOVXM_lng_cg]]
    ;
    ; AIE2P-LABEL: name: global_value_ptr
    ; AIE2P: [[MOVXM:%[0-9]+]]:ep_as_32bit = MOVXM target-flags(aie2p-global) &x
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[MOVXM]]
    ;
    ; AIE2PS-LABEL: name: global_value_ptr
    ; AIE2PS: [[MOVXM_lng_cg:%[0-9]+]]:ep_as_32bit = MOVXM_lng_cg target-flags(aie2ps-global) &x
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[MOVXM_lng_cg]]
    %0:ptrregbank(p0) = G_GLOBAL_VALUE &x
    PseudoRET implicit $lr, implicit %0
...

---
name: global_value_gpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; AIE2-LABEL: name: global_value_gpr
    ; AIE2: [[MOVXM_lng_cg:%[0-9]+]]:er = MOVXM_lng_cg target-flags(aie2-global) &x
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[MOVXM_lng_cg]]
    ;
    ; AIE2P-LABEL: name: global_value_gpr
    ; AIE2P: [[MOVXM:%[0-9]+]]:er = MOVXM target-flags(aie2p-global) &x
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[MOVXM]]
    ;
    ; AIE2PS-LABEL: name: global_value_gpr
    ; AIE2PS: [[MOVXM_lng_cg:%[0-9]+]]:er = MOVXM_lng_cg target-flags(aie2ps-global) &x
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[MOVXM_lng_cg]]
    %0:gprregbank(p0) = G_GLOBAL_VALUE &x
    PseudoRET implicit $lr, implicit %0
...
