# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s -check-prefix=AIE2PS

---
name:            test_sub_v64s8
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.0:
    liveins: $x2, $x4

    ; CHECK-LABEL: name: test_sub_v64s8
    ; CHECK: liveins: $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[VSUB_8_:%[0-9]+]]:vec512 = VSUB_8 [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VSUB_8_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2PS-LABEL: name: test_sub_v64s8
    ; AIE2PS: liveins: $x2, $x4
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2PS-NEXT: [[VSUB_8_:%[0-9]+]]:vec512 = VSUB_8 [[COPY1]], [[COPY]], implicit $crbf8conf, implicit $crfp8conf
    ; AIE2PS-NEXT: $x0 = COPY [[VSUB_8_]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vregbank(<64 x s8>) = COPY $x2
    %1:vregbank(<64 x s8>) = COPY $x4
    %2:vregbank(<64 x s8>) = G_SUB %1, %0
    $x0 = COPY %2(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            test_sub_v32s16
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.0:
    liveins: $x2, $x4

    ; CHECK-LABEL: name: test_sub_v32s16
    ; CHECK: liveins: $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[VSUB_16_:%[0-9]+]]:vec512 = VSUB_16 [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VSUB_16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2PS-LABEL: name: test_sub_v32s16
    ; AIE2PS: liveins: $x2, $x4
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2PS-NEXT: [[VSUB_16_:%[0-9]+]]:vec512 = VSUB_16 [[COPY1]], [[COPY]], implicit $crbf8conf, implicit $crfp8conf
    ; AIE2PS-NEXT: $x0 = COPY [[VSUB_16_]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vregbank(<32 x s16>) = COPY $x2
    %1:vregbank(<32 x s16>) = COPY $x4
    %2:vregbank(<32 x s16>) = G_SUB %1, %0
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            test_sub_v16s32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.0:
    liveins: $x2, $x4

    ; CHECK-LABEL: name: test_sub_v16s32
    ; CHECK: liveins: $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[VSUB_32_:%[0-9]+]]:vec512 = VSUB_32 [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VSUB_32_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2PS-LABEL: name: test_sub_v16s32
    ; AIE2PS: liveins: $x2, $x4
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2PS-NEXT: [[VSUB_32_:%[0-9]+]]:vec512 = VSUB_32 [[COPY1]], [[COPY]], implicit $crbf8conf, implicit $crfp8conf
    ; AIE2PS-NEXT: $x0 = COPY [[VSUB_32_]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vregbank(<16 x s32>) = COPY $x2
    %1:vregbank(<16 x s32>) = COPY $x4
    %2:vregbank(<16 x s32>) = G_SUB %1, %0
    $x0 = COPY %2(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
