# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P

---
name: phi_s32
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  ; AIE2-LABEL: name: phi_s32
  ; AIE2: bb.0:
  ; AIE2-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2-NEXT:   liveins: $r6, $r7, $r8
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r6
  ; AIE2-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r7
  ; AIE2-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r8
  ; AIE2-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  ; AIE2-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2:
  ; AIE2-NEXT:   [[PHI:%[0-9]+]]:er = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2-NEXT:   $r0 = COPY [[PHI]]
  ;
  ; AIE2P-LABEL: name: phi_s32
  ; AIE2P: bb.0:
  ; AIE2P-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2P-NEXT:   liveins: $r6, $r7, $r8
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r6
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r7
  ; AIE2P-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r8
  ; AIE2P-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1:
  ; AIE2P-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.2:
  ; AIE2P-NEXT:   [[PHI:%[0-9]+]]:er = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2P-NEXT:   $r0 = COPY [[PHI]]
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $r6, $r7, $r8
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = COPY $r8
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:gprregbank(s32) = G_ICMP intpred(eq), %2, %3
    G_BRCOND %4, %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

    %5:gprregbank(s32) = COPY %1
    G_BR %bb.2

  bb.2:
    %6:gprregbank(s32) = G_PHI %0, %bb.0, %5, %bb.1
    $r0 = COPY %6
...

---
name: phi_p0
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  ; AIE2-LABEL: name: phi_p0
  ; AIE2: bb.0:
  ; AIE2-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2-NEXT:   liveins: $p0, $p1, $r6
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; AIE2-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p1
  ; AIE2-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r6
  ; AIE2-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  ; AIE2-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2:
  ; AIE2-NEXT:   [[PHI:%[0-9]+]]:ep = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2-NEXT:   $p0 = COPY [[PHI]]
  ;
  ; AIE2P-LABEL: name: phi_p0
  ; AIE2P: bb.0:
  ; AIE2P-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2P-NEXT:   liveins: $p0, $p1, $r6
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p1
  ; AIE2P-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r6
  ; AIE2P-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1:
  ; AIE2P-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.2:
  ; AIE2P-NEXT:   [[PHI:%[0-9]+]]:ep = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2P-NEXT:   $p0 = COPY [[PHI]]
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $p0, $p1, $r6

    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r6
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:gprregbank(s32) = G_ICMP intpred(eq), %2, %3
    G_BRCOND %4, %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

    %5:ptrregbank(p0) = COPY %1
    G_BR %bb.2

  bb.2:
    %6:ptrregbank(p0) = G_PHI %0, %bb.0, %5, %bb.1
    $p0 = COPY %6
...

---
name: phi_s20
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  ; AIE2-LABEL: name: phi_s20
  ; AIE2: bb.0:
  ; AIE2-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2-NEXT:   liveins: $dj0, $m1, $r8
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[COPY:%[0-9]+]]:mdm = COPY $dj0
  ; AIE2-NEXT:   [[COPY1:%[0-9]+]]:mdm = COPY $m1
  ; AIE2-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r8
  ; AIE2-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  ; AIE2-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2:
  ; AIE2-NEXT:   [[PHI:%[0-9]+]]:mdm = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2-NEXT:   $m2 = COPY [[PHI]]
  ;
  ; AIE2P-LABEL: name: phi_s20
  ; AIE2P: bb.0:
  ; AIE2P-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2P-NEXT:   liveins: $dj0, $m1, $r8
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:mdm = COPY $dj0
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:mdm = COPY $m1
  ; AIE2P-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r8
  ; AIE2P-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1:
  ; AIE2P-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.2:
  ; AIE2P-NEXT:   [[PHI:%[0-9]+]]:mdm = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2P-NEXT:   $m2 = COPY [[PHI]]
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $dj0, $m1, $r8
    %0:modregbank(s20) = COPY $dj0
    %1:modregbank(s20) = COPY $m1
    %2:gprregbank(s32) = COPY $r8
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:gprregbank(s32) = G_ICMP intpred(eq), %2, %3
    G_BRCOND %4, %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

    %5:modregbank(s20) = COPY %1
    G_BR %bb.2

  bb.2:
    %6:modregbank(s20) = G_PHI %0:modregbank(s20), %bb.0, %5:modregbank(s20), %bb.1
    $m2 = COPY %6
...

---
name: phi_s20_gpr
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  ; AIE2-LABEL: name: phi_s20_gpr
  ; AIE2: bb.0:
  ; AIE2-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2-NEXT:   liveins: $dj0, $m1, $r8
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[COPY:%[0-9]+]]:er = COPY $dj0
  ; AIE2-NEXT:   [[COPY1:%[0-9]+]]:mdm = COPY $m1
  ; AIE2-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r8
  ; AIE2-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  ; AIE2-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2:
  ; AIE2-NEXT:   [[PHI:%[0-9]+]]:mdm = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2-NEXT:   $m2 = COPY [[PHI]]
  ;
  ; AIE2P-LABEL: name: phi_s20_gpr
  ; AIE2P: bb.0:
  ; AIE2P-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; AIE2P-NEXT:   liveins: $dj0, $m1, $r8
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:er = COPY $dj0
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:mdm = COPY $m1
  ; AIE2P-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r8
  ; AIE2P-NEXT:   PseudoJZ [[COPY2]], %bb.1
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1:
  ; AIE2P-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   PseudoJ_jump_imm %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.2:
  ; AIE2P-NEXT:   [[PHI:%[0-9]+]]:mdm = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; AIE2P-NEXT:   $m2 = COPY [[PHI]]
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $dj0, $m1, $r8
    %0:gprregbank(s20) = COPY $dj0
    %1:modregbank(s20) = COPY $m1
    %2:gprregbank(s32) = COPY $r8
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:gprregbank(s32) = G_ICMP intpred(eq), %2, %3
    G_BRCOND %4, %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

    %5:modregbank(s20) = COPY %1
    G_BR %bb.2

  bb.2:
    %6:modregbank(s20) = G_PHI %0:gprregbank(s20), %bb.0, %5:modregbank(s20), %bb.1
    $m2 = COPY %6
...
