# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

---
name:            test_v32int8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: test_v32int8
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: VST_dmw_sts_w_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<32 x s8>))
    ;
    ; AIE2PS-LABEL: name: test_v32int8
    ; AIE2PS: liveins: $p0, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: VST_dmw_sts_w_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<32 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<32 x s8>) = COPY $wl0
    G_STORE %1(<32 x s8>), %0(p0) :: (store (<32 x s8>))
...

---
name:            test_v16int16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: test_v16int16
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: VST_dmw_sts_w_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<16 x s16>))
    ;
    ; AIE2PS-LABEL: name: test_v16int16
    ; AIE2PS: liveins: $p0, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: VST_dmw_sts_w_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s16>) = COPY $wl0
    G_STORE %1(<16 x s16>), %0(p0) :: (store (<16 x s16>))
...

---
name:            test_v8int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: test_v8int32
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: VST_dmw_sts_w_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<8 x s32>))
    ;
    ; AIE2PS-LABEL: name: test_v8int32
    ; AIE2PS: liveins: $p0, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: VST_dmw_sts_w_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<8 x s32>))
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<8 x s32>) = COPY $wl0
    G_STORE %1(<8 x s32>), %0(p0) :: (store (<8 x s32>))
...

---
name:            test_v64int8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: test_v64int8
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<64 x s8>))
    ;
    ; AIE2PS-LABEL: name: test_v64int8
    ; AIE2PS: liveins: $p0, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<64 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<64 x s8>) = COPY $x0
    G_STORE %1(<64 x s8>), %0(p0) :: (store (<64 x s8>))
...

---
name:            test_v32int16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: test_v32int16
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<32 x s16>))
    ;
    ; AIE2PS-LABEL: name: test_v32int16
    ; AIE2PS: liveins: $p0, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<32 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<32 x s16>) = COPY $x0
    G_STORE %1(<32 x s16>), %0(p0) :: (store (<32 x s16>))
...

---
name:            test_v16int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: test_v16int32
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<16 x s32>))
    ;
    ; AIE2PS-LABEL: name: test_v16int32
    ; AIE2PS: liveins: $p0, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<16 x s32>))
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = COPY $x0
    G_STORE %1(<16 x s32>), %0(p0) :: (store (<16 x s32>))
...

---
name:            test_v64int16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $y0
    ; CHECK-LABEL: name: test_v64int16
    ; CHECK: liveins: $p0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<32 x s16>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<32 x s16>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: test_v64int16
    ; AIE2PS: liveins: $p0, $y0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<32 x s16>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_lo
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<32 x s16>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<64 x s16>) = COPY $y0
    G_STORE %1(<64 x s16>), %0(p0) :: (store (<64 x s16>))
...

---
name:            test_v32int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $y0
    ; CHECK-LABEL: name: test_v32int32
    ; CHECK: liveins: $p0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: test_v32int32
    ; AIE2PS: liveins: $p0, $y0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_lo
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<32 x s32>) = COPY $y0
    G_STORE %1(<32 x s32>), %0(p0) :: (store (<32 x s32>))
...

---
name:            test_v128int8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $y0
    ; CHECK-LABEL: name: test_v128int8
    ; CHECK: liveins: $p0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<64 x s8>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<64 x s8>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: test_v128int8
    ; AIE2PS: liveins: $p0, $y0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<64 x s8>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[COPY1]].sub_512_lo
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<64 x s8>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<128 x s8>) = COPY $y0
    G_STORE %1(<128 x s8>), %0(p0) :: (store (<128 x s8>))
...

---
name:            test_v16acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; CHECK-LABEL: name: test_v16acc32
    ; CHECK: liveins: $bmll0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<8 x s64>))
    ;
    ; AIE2PS-LABEL: name: test_v16acc32
    ; AIE2PS: liveins: $bmll0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<8 x s64>))
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    G_STORE %1(<8 x s64>), %0(p0) :: (store (<8 x s64>))
...

---
name:            test_v8acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; CHECK-LABEL: name: test_v8acc64
    ; CHECK: liveins: $bmll0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<8 x s64>))
    ;
    ; AIE2PS-LABEL: name: test_v8acc64
    ; AIE2PS: liveins: $bmll0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<8 x s64>))
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    G_STORE %1(<8 x s64>), %0(p0) :: (store (<8 x s64>))
...

---
name:            test_v32acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0
    ; CHECK-LABEL: name: test_v32acc32
    ; CHECK: liveins: $cml0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: test_v32acc32
    ; AIE2PS: liveins: $cml0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<32 x s32>) = COPY $cml0
    G_STORE %1(<32 x s32>), %0(p0) :: (store (<32 x s32>))
...

---
name:            test_v16acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0
    ; CHECK-LABEL: name: test_v16acc64
    ; CHECK: liveins: $cml0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<8 x s64>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<8 x s64>) into unknown-address + 64)
    ;
    ; AIE2PS-LABEL: name: test_v16acc64
    ; AIE2PS: liveins: $cml0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<8 x s64>), align 128)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<8 x s64>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<16 x s64>) = COPY $cml0
    G_STORE %1(<16 x s64>), %0(p0) :: (store (<16 x s64>))
...

---
name:            test_v64acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0
    ; CHECK-LABEL: name: test_v64acc32
    ; CHECK: liveins: $dm0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY]], 192 :: (store (<16 x s32>), align 256)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY]], 128 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<16 x s32>) into unknown-address + 128, align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY5]], [[COPY]], 0 :: (store (<16 x s32>) into unknown-address + 192)
    ;
    ; AIE2PS-LABEL: name: test_v64acc32
    ; AIE2PS: liveins: $dm0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY]], 192 :: (store (<16 x s32>), align 256)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY]], 128 :: (store (<16 x s32>) into unknown-address + 64)
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<16 x s32>) into unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY5]], [[COPY]], 0 :: (store (<16 x s32>) into unknown-address + 192)
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<64 x s32>) = COPY $dm0
    G_STORE %1(<64 x s32>), %0(p0) :: (store (<64 x s32>))
...

---
name:            test_v32acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0
    ; CHECK-LABEL: name: test_v32acc64
    ; CHECK: liveins: $dm0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY2]], [[COPY]], 192 :: (store (<8 x s64>), align 256)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY3]], [[COPY]], 128 :: (store (<8 x s64>) into unknown-address + 64)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY5]], [[COPY]], 0 :: (store (<8 x s64>) into unknown-address + 192)
    ;
    ; AIE2PS-LABEL: name: test_v32acc64
    ; AIE2PS: liveins: $dm0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY2]], [[COPY]], 192 :: (store (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY3]], [[COPY]], 128 :: (store (<8 x s64>) into unknown-address + 64)
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<8 x s64>) into unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY1]].sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY5]], [[COPY]], 0 :: (store (<8 x s64>) into unknown-address + 192)
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<32 x s64>) = COPY $dm0
    G_STORE %1(<32 x s64>), %0(p0) :: (store (<32 x s64>))
...

