# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK,AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK,AIE2PS

---
name:            test_v32int8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v32int8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_w_idx_imm_pseudo:%[0-9]+]]:vec256 = VLD_w_idx_imm_pseudo [[COPY]], 0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $wl0 = COPY [[VLD_w_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<32 x s8>) = G_LOAD %1(p0) :: (load (<32 x s8>))
    $wl0 = COPY %0(<32 x s8>)
...

---
name:            test_v16int16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v16int16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_w_idx_imm_pseudo:%[0-9]+]]:vec256 = VLD_w_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $wl0 = COPY [[VLD_w_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<16 x s16>) = G_LOAD %1(p0) :: (load (<16 x s16>))
    $wl0 = COPY %0(<16 x s16>)
...

---
name:            test_v8int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v8int32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_w_idx_imm_pseudo:%[0-9]+]]:vec256 = VLD_w_idx_imm_pseudo [[COPY]], 0 :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLD_w_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<8 x s32>) = G_LOAD %1(p0) :: (load (<8 x s32>))
    $wl0 = COPY %0(<8 x s32>)
...

---
name:            test_v64int8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v64int8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<64 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLD_x_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<64 x s8>) = G_LOAD %1(p0) :: (load (<64 x s8>))
    $x0 = COPY %0(<64 x s8>)
...

---
name:            test_v32int16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v32int16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $x0 = COPY [[VLD_x_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<32 x s16>) = G_LOAD %1(p0) :: (load (<32 x s16>))
    $x0 = COPY %0(<32 x s16>)
...

---
name:            test_v16int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v16int32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLD_x_idx_imm_pseudo]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<16 x s32>) = G_LOAD %1(p0) :: (load (<16 x s32>))
    $x0 = COPY %0(<16 x s32>)
...

---
name:            test_v64int16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v64int16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 64 :: (load (<32 x s16>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<32 x s16>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<64 x s16>) = G_LOAD %1(p0) :: (load (<64 x s16>))
    $y0 = COPY %0(<64 x s16>)
...

---
name:            test_v32int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v32int32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 64 :: (load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>))
    $y0 = COPY %0(<32 x s32>)
...

---
name:            test_v128int8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v128int8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 64 :: (load (<64 x s8>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<64 x s8>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(<128 x s8>) = G_LOAD %1(p0) :: (load (<128 x s8>))
    $y0 = COPY %0(<128 x s8>)
...

---
name:            test_v16acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: test_v16acc32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 0 :: (load (<8 x s64>))
    ; AIE2P-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx_imm]]
    ;
    ; AIE2PS-LABEL: name: test_v16acc32
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 0 :: (load (<8 x s64>))
    ; AIE2PS-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_ld_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %0:accregbank(<8 x s64>) = G_LOAD %1(p0) :: (load (<8 x s64>))
    $bmll0 = COPY %0(<8 x s64>)
...

---
name:            test_v8acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: test_v8acc64
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 0 :: (load (<8 x s64>))
    ; AIE2P-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx_imm]]
    ;
    ; AIE2PS-LABEL: name: test_v8acc64
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 0 :: (load (<8 x s64>))
    ; AIE2PS-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_ld_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %0:accregbank(<8 x s64>) = G_LOAD %1(p0) :: (load (<8 x s64>))
    $bmll0 = COPY %0(<8 x s64>)
...

---
name:            test_v32acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: test_v32acc32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 64 :: (load (<16 x s32>), align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 0 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: test_v32acc32
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 64 :: (load (<16 x s32>), align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 0 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %0:accregbank(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>))
    $cml0 = COPY %0(<32 x s32>)
...

---
name:            test_v16acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: test_v16acc64
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 64 :: (load (<8 x s64>), align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 0 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: test_v16acc64
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 64 :: (load (<8 x s64>), align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 0 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %0:accregbank(<16 x s64>) = G_LOAD %1(p0) :: (load (<16 x s64>))
    $cml0 = COPY %0(<16 x s64>)
...

---
name:            test_v64acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: test_v64acc32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 192 :: (load (<16 x s32>), align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 128 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 64 :: (load (<16 x s32>) from unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 0 :: (load (<16 x s32>) from unknown-address + 192)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: test_v64acc32
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 192 :: (load (<16 x s32>), align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 128 :: (load (<16 x s32>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 64 :: (load (<16 x s32>) from unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 0 :: (load (<16 x s32>) from unknown-address + 192)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %0:accregbank(<64 x s32>) = G_LOAD %1(p0) :: (load (<64 x s32>))
    $dm0 = COPY %0(<64 x s32>)
...

---
name:            test_v32acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2P-LABEL: name: test_v32acc64
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 192 :: (load (<8 x s64>), align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 128 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 64 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 0 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2PS-LABEL: name: test_v32acc64
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 192 :: (load (<8 x s64>), align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 128 :: (load (<8 x s64>) from unknown-address + 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 64 :: (load (<8 x s64>) from unknown-address + 128, align 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 0 :: (load (<8 x s64>) from unknown-address + 192)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    %1:ptrregbank(p0) = COPY $p0
    %0:accregbank(<32 x s64>) = G_LOAD %1(p0) :: (load (<32 x s64>))
    $dm0 = COPY %0(<32 x s64>)
...
