# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            inttoptr_gpr_gpr
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: inttoptr_gpr_gpr
    ; CHECK: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s20) = G_TRUNC %0
    %2:gprregbank(p0) = G_INTTOPTR %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            inttoptr_ptr_ptr
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: inttoptr_ptr_ptr
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:ptrregbank(s20) = COPY $p0
    %1:ptrregbank(p0) = G_INTTOPTR %0
    PseudoRET implicit $lr, implicit %1
...

---
name:            inttoptr_gpr_ptr
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: inttoptr_gpr_ptr
    ; CHECK: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]]
    %0:ptrregbank(s20) = COPY $p0
    %1:gprregbank(p0) = G_INTTOPTR %0
    PseudoRET implicit $lr, implicit %1
...

---
name:            inttoptr_ptr_gpr
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: inttoptr_ptr_gpr
    ; CHECK: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptr = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s20) = G_TRUNC %0
    %2:ptrregbank(p0) = G_INTTOPTR %1
    PseudoRET implicit $lr, implicit %2
...
