# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1 %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2PS %s

---
name: add_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE1-LABEL: name: add_s32
    ; AIE1: liveins: $r6, $r7
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r7
    ; AIE1-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    ;
    ; AIE2-LABEL: name: add_s32
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2-NEXT: [[ADD:%[0-9]+]]:er = ADD [[COPY]], [[COPY1]], implicit-def dead $srcarry
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    ;
    ; AIE2P-LABEL: name: add_s32
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2P-NEXT: [[ADD_alu_r_rr:%[0-9]+]]:er = ADD_alu_r_rr [[COPY]], [[COPY1]], implicit-def dead $srcarry
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ADD_alu_r_rr]]
    ;
    ; AIE2PS-LABEL: name: add_s32
    ; AIE2PS: liveins: $r6, $r7
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r7
    ; AIE2PS-NEXT: [[ADD_alu_r_rr:%[0-9]+]]:mlockid_reg = ADD_alu_r_rr [[COPY]], [[COPY1]], implicit-def dead $srcarry
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[ADD_alu_r_rr]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_umax
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE1-LABEL: name: add_s32_const_umax
    ; AIE1: liveins: $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 63
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[ADDI]]
    ;
    ; AIE2-LABEL: name: add_s32_const_umax
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[COPY]], 63, implicit-def dead $srcarry
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    ;
    ; AIE2P-LABEL: name: add_s32_const_umax
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[COPY]], 63, implicit-def dead $srcarry
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    ;
    ; AIE2PS-LABEL: name: add_s32_const_umax
    ; AIE2PS: liveins: $r6
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[ADD_add_r_ri:%[0-9]+]]:mlockid_reg = ADD_add_r_ri [[COPY]], 63, implicit-def dead $srcarry
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 63
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_smax
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE1-LABEL: name: add_s32_const_smax
    ; AIE1: liveins: $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], -64
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[ADDI]]
    ;
    ; AIE2-LABEL: name: add_s32_const_smax
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[COPY]], -64, implicit-def dead $srcarry
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    ;
    ; AIE2P-LABEL: name: add_s32_const_smax
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[COPY]], -64, implicit-def dead $srcarry
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    ;
    ; AIE2PS-LABEL: name: add_s32_const_smax
    ; AIE2PS: liveins: $r6
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[ADD_add_r_ri:%[0-9]+]]:mlockid_reg = ADD_add_r_ri [[COPY]], -64, implicit-def dead $srcarry
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 -64
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_umax_plus_1
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE1-LABEL: name: add_s32_const_umax_plus_1
    ; AIE1: liveins: $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 64
    ; AIE1-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[MOV_U20_]]
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    ;
    ; AIE2-LABEL: name: add_s32_const_umax_plus_1
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 64
    ; AIE2-NEXT: [[ADD:%[0-9]+]]:er = ADD [[COPY]], [[MOV_RLC_imm10_pseudo]], implicit-def dead $srcarry
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    ;
    ; AIE2P-LABEL: name: add_s32_const_umax_plus_1
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 64
    ; AIE2P-NEXT: [[ADD_alu_r_rr:%[0-9]+]]:er = ADD_alu_r_rr [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srcarry
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ADD_alu_r_rr]]
    ;
    ; AIE2PS-LABEL: name: add_s32_const_umax_plus_1
    ; AIE2PS: liveins: $r6
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 64
    ; AIE2PS-NEXT: [[ADD_alu_r_rr:%[0-9]+]]:mlockid_reg = ADD_alu_r_rr [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srcarry
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[ADD_alu_r_rr]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 64
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_smax_minus_one
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE1-LABEL: name: add_s32_const_smax_minus_one
    ; AIE1: liveins: $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[MOV_S12_:%[0-9]+]]:gpr = MOV_S12 -65
    ; AIE1-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[MOV_S12_]]
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    ;
    ; AIE2-LABEL: name: add_s32_const_smax_minus_one
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo -65
    ; AIE2-NEXT: [[ADD:%[0-9]+]]:er = ADD [[COPY]], [[MOV_RLC_imm10_pseudo]], implicit-def dead $srcarry
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    ;
    ; AIE2P-LABEL: name: add_s32_const_smax_minus_one
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -65
    ; AIE2P-NEXT: [[ADD_alu_r_rr:%[0-9]+]]:er = ADD_alu_r_rr [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srcarry
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ADD_alu_r_rr]]
    ;
    ; AIE2PS-LABEL: name: add_s32_const_smax_minus_one
    ; AIE2PS: liveins: $r6
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo -65
    ; AIE2PS-NEXT: [[ADD_alu_r_rr:%[0-9]+]]:mlockid_reg = ADD_alu_r_rr [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srcarry
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[ADD_alu_r_rr]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 -65
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...
