# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefixes=CHECK,AIE2P -DER=er %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefixes=CHECK,AIE2PS -DER=mlockid_reg %s

---
name: pre-inc-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $m0
    ; AIE2P-LABEL: name: pre-inc-load
    ; AIE2P: liveins: $p0, $p1, $m0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -3
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -36
    ; AIE2P-NEXT: [[LDA_dms_lda_idx:%[0-9]+]]:er = LDA_dms_lda_idx [[COPY]], [[COPY1]] :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:er = LDA_dms_lda_idx_imm [[COPY]], 28 :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_idx_imm1:%[0-9]+]]:er = LDA_dms_lda_idx_imm [[COPY]], -32 :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_idx1:%[0-9]+]]:er = LDA_dms_lda_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_idx2:%[0-9]+]]:er = LDA_dms_lda_idx [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s32))
    ; AIE2P-NEXT: [[LDA_dms_lda_idx3:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_idx [[COPY]], [[COPY1]] :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_idx_imm2:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_idx_imm [[COPY]], 28 :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_idx_imm3:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_idx_imm [[COPY]], -32 :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_idx4:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (p0), align 4)
    ; AIE2P-NEXT: [[LDA_dms_lda_idx5:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_idx [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (p0), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LDA_dms_lda_idx]], implicit [[LDA_dms_lda_idx_imm]], implicit [[LDA_dms_lda_idx_imm1]], implicit [[LDA_dms_lda_idx1]], implicit [[LDA_dms_lda_idx2]], implicit [[LDA_dms_lda_idx3]], implicit [[LDA_dms_lda_idx_imm2]], implicit [[LDA_dms_lda_idx_imm3]], implicit [[LDA_dms_lda_idx4]], implicit [[LDA_dms_lda_idx5]]

    ; AIE2PS-LABEL: name: pre-inc-load
    ; AIE2PS: liveins: $p0, $p1, $m0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -3
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -36
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx [[COPY]], [[COPY1]] :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 28 :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx_imm1:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], -32 :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx1:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx2:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s32))
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx3:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_scalar_ld_idx [[COPY]], [[COPY1]] :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx_imm2:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 28 :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx_imm3:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], -32 :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx4:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_scalar_ld_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (p0), align 4)
    ; AIE2PS-NEXT: [[LDA_dms_lda_idx5:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_scalar_ld_idx [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (p0), align 4)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA_dms_lda_idx]], implicit [[LDA_dms_lda_idx_imm]], implicit [[LDA_dms_lda_idx_imm1]], implicit [[LDA_dms_lda_idx1]], implicit [[LDA_dms_lda_idx2]], implicit [[LDA_dms_lda_idx3]], implicit [[LDA_dms_lda_idx_imm2]], implicit [[LDA_dms_lda_idx_imm3]], implicit [[LDA_dms_lda_idx4]], implicit [[LDA_dms_lda_idx5]]

    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %6:modregbank(s20) = G_CONSTANT i20 28
    %7:modregbank(s20) = G_CONSTANT i20 -32
    %71:modregbank(s20) = G_CONSTANT i20 -3
    %72:modregbank(s20) = G_CONSTANT i20 -36
    %8:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %5 :: (load (s32))
    %9:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %6 :: (load (s32))
    %10:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %7 :: (load (s32))
    %11:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %71 :: (load (s32))
    %12:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %72 :: (load (s32))
    %80:ptrregbank(p0)= G_AIE_OFFSET_LOAD %0, %5 :: (load (p0))
    %90:ptrregbank(p0) = G_AIE_OFFSET_LOAD %0, %6 :: (load (p0))
    %100:ptrregbank(p0) = G_AIE_OFFSET_LOAD %0, %7 :: (load (p0))
    %110:ptrregbank(p0) = G_AIE_OFFSET_LOAD %0, %71 :: (load (p0))
    %120:ptrregbank(p0) = G_AIE_OFFSET_LOAD %0, %72 :: (load (p0))
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11, implicit %12, implicit %80, implicit %90, implicit %100, implicit %110, implicit %120
...

---
name: pre-inc-hb-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ; CHECK-LABEL: name: pre-inc-hb-load
    ; CHECK: liveins: $p0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 8
    ; CHECK-NEXT: [[LDA_s8_idx:%[0-9]+]]:[[ER]] = LDA_s8_idx [[COPY]], [[COPY1]] :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx_imm:%[0-9]+]]:[[ER]] = LDA_s8_idx_imm [[COPY]], 7 :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx_imm1:%[0-9]+]]:[[ER]] = LDA_s8_idx_imm [[COPY]], -8 :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx_imm2:%[0-9]+]]:[[ER]] = LDA_s8_idx_imm [[COPY]], -1 :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx1:%[0-9]+]]:[[ER]] = LDA_s8_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -18
    ; CHECK-NEXT: [[LDA_s16_idx:%[0-9]+]]:[[ER]] = LDA_s16_idx [[COPY]], [[COPY1]] :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx_imm:%[0-9]+]]:[[ER]] = LDA_s16_idx_imm [[COPY]], 14 :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx_imm1:%[0-9]+]]:[[ER]] = LDA_s16_idx_imm [[COPY]], -16 :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx1:%[0-9]+]]:[[ER]] = LDA_s16_idx [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx2:%[0-9]+]]:[[ER]] = LDA_s16_idx [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LDA_s8_idx]], implicit [[LDA_s8_idx_imm]], implicit [[LDA_s8_idx_imm1]], implicit [[LDA_s8_idx_imm2]], implicit [[LDA_s8_idx1]], implicit [[LDA_s16_idx]], implicit [[LDA_s16_idx_imm]], implicit [[LDA_s16_idx_imm1]], implicit [[LDA_s16_idx1]], implicit [[LDA_s16_idx2]]

    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %60:modregbank(s20) = G_CONSTANT i20 7
    %61:modregbank(s20) = G_CONSTANT i20 -8
    %62:modregbank(s20) = G_CONSTANT i20 -1
    %63:modregbank(s20) = G_CONSTANT i20 8
    %80:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %5 :: (load (s8))
    %90:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %60 :: (load (s8))
    %100:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %61 :: (load (s8))
    %110:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %62 :: (load (s8))
    %120:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %63 :: (load (s8))
    %70:modregbank(s20) = G_CONSTANT i20 14
    %71:modregbank(s20) = G_CONSTANT i20 -16
    %72:modregbank(s20) = G_CONSTANT i20 1
    %73:modregbank(s20) = G_CONSTANT i20 -18
    %130:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %5 :: (load (s16))
    %140:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %70 :: (load (s16))
    %150:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %71 :: (load (s16))
    %160:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %72 :: (load (s16))
    %170:gprregbank(s32) = G_AIE_OFFSET_LOAD %0, %73 :: (load (s16))
    PseudoRET implicit $lr, implicit %80, implicit %90, implicit %100, implicit %110, implicit %120, implicit %130, implicit %140, implicit %150, implicit %160, implicit %170
...



---
name: pre-inc-hb-sextload
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ; CHECK-LABEL: name: pre-inc-hb-sextload
    ; CHECK: liveins: $p0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 8
    ; CHECK-NEXT: [[LDA_s8_idx:%[0-9]+]]:[[ER]] = LDA_s8_idx [[COPY]], [[COPY1]] :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx_imm:%[0-9]+]]:[[ER]] = LDA_s8_idx_imm [[COPY]], 7 :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx_imm1:%[0-9]+]]:[[ER]] = LDA_s8_idx_imm [[COPY]], -8 :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx_imm2:%[0-9]+]]:[[ER]] = LDA_s8_idx_imm [[COPY]], -1 :: (load (s8))
    ; CHECK-NEXT: [[LDA_s8_idx1:%[0-9]+]]:[[ER]] = LDA_s8_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -18
    ; CHECK-NEXT: [[LDA_s16_idx:%[0-9]+]]:[[ER]] = LDA_s16_idx [[COPY]], [[COPY1]] :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx_imm:%[0-9]+]]:[[ER]] = LDA_s16_idx_imm [[COPY]], 14 :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx_imm1:%[0-9]+]]:[[ER]] = LDA_s16_idx_imm [[COPY]], -16 :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx1:%[0-9]+]]:[[ER]] = LDA_s16_idx [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; CHECK-NEXT: [[LDA_s16_idx2:%[0-9]+]]:[[ER]] = LDA_s16_idx [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LDA_s8_idx]], implicit [[LDA_s8_idx_imm]], implicit [[LDA_s8_idx_imm1]], implicit [[LDA_s8_idx_imm2]], implicit [[LDA_s8_idx1]], implicit [[LDA_s16_idx]], implicit [[LDA_s16_idx_imm]], implicit [[LDA_s16_idx_imm1]], implicit [[LDA_s16_idx1]], implicit [[LDA_s16_idx2]]
    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %60:modregbank(s20) = G_CONSTANT i20 7
    %61:modregbank(s20) = G_CONSTANT i20 -8
    %62:modregbank(s20) = G_CONSTANT i20 -1
    %63:modregbank(s20) = G_CONSTANT i20 8
    %80:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %5 :: (load (s8))
    %90:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %60 :: (load (s8))
    %100:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %61 :: (load (s8))
    %110:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %62 :: (load (s8))
    %120:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %63 :: (load (s8))
    %70:modregbank(s20) = G_CONSTANT i20 14
    %71:modregbank(s20) = G_CONSTANT i20 -16
    %72:modregbank(s20) = G_CONSTANT i20 1
    %73:modregbank(s20) = G_CONSTANT i20 -18
    %130:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %5 :: (load (s16))
    %140:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %70 :: (load (s16))
    %150:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %71 :: (load (s16))
    %160:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %72 :: (load (s16))
    %170:gprregbank(s32) = G_AIE_OFFSET_SEXTLOAD %0, %73 :: (load (s16))
    PseudoRET implicit $lr, implicit %80, implicit %90, implicit %100, implicit %110, implicit %120, implicit %130, implicit %140, implicit %150, implicit %160, implicit %170
...

---
name: pre-inc-hb-zextload
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ; CHECK-LABEL: name: pre-inc-hb-zextload
    ; CHECK: liveins: $p0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 8
    ; CHECK-NEXT: [[LDA_u8_idx:%[0-9]+]]:[[ER]] = LDA_u8_idx [[COPY]], [[COPY1]] :: (load (s8))
    ; CHECK-NEXT: [[LDA_u8_idx_imm:%[0-9]+]]:[[ER]] = LDA_u8_idx_imm [[COPY]], 7 :: (load (s8))
    ; CHECK-NEXT: [[LDA_u8_idx_imm1:%[0-9]+]]:[[ER]] = LDA_u8_idx_imm [[COPY]], -8 :: (load (s8))
    ; CHECK-NEXT: [[LDA_u8_idx_imm2:%[0-9]+]]:[[ER]] = LDA_u8_idx_imm [[COPY]], -1 :: (load (s8))
    ; CHECK-NEXT: [[LDA_u8_idx1:%[0-9]+]]:[[ER]] = LDA_u8_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s8))
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -18
    ; CHECK-NEXT: [[LDA_u16_idx:%[0-9]+]]:[[ER]] = LDA_u16_idx [[COPY]], [[COPY1]] :: (load (s16))
    ; CHECK-NEXT: [[LDA_u16_idx_imm:%[0-9]+]]:[[ER]] = LDA_u16_idx_imm [[COPY]], 14 :: (load (s16))
    ; CHECK-NEXT: [[LDA_u16_idx_imm1:%[0-9]+]]:[[ER]] = LDA_u16_idx_imm [[COPY]], -16 :: (load (s16))
    ; CHECK-NEXT: [[LDA_u16_idx1:%[0-9]+]]:[[ER]] = LDA_u16_idx [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (load (s16))
    ; CHECK-NEXT: [[LDA_u16_idx2:%[0-9]+]]:[[ER]] = LDA_u16_idx [[COPY]], [[MOV_PD_imm11_pseudo2]] :: (load (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LDA_u8_idx]], implicit [[LDA_u8_idx_imm]], implicit [[LDA_u8_idx_imm1]], implicit [[LDA_u8_idx_imm2]], implicit [[LDA_u8_idx1]], implicit [[LDA_u16_idx]], implicit [[LDA_u16_idx_imm]], implicit [[LDA_u16_idx_imm1]], implicit [[LDA_u16_idx1]], implicit [[LDA_u16_idx2]]
    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %60:modregbank(s20) = G_CONSTANT i20 7
    %61:modregbank(s20) = G_CONSTANT i20 -8
    %62:modregbank(s20) = G_CONSTANT i20 -1
    %63:modregbank(s20) = G_CONSTANT i20 8
    %80:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %5 :: (load (s8))
    %90:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %60 :: (load (s8))
    %100:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %61 :: (load (s8))
    %110:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %62 :: (load (s8))
    %120:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %63 :: (load (s8))
    %70:modregbank(s20) = G_CONSTANT i20 14
    %71:modregbank(s20) = G_CONSTANT i20 -16
    %72:modregbank(s20) = G_CONSTANT i20 1
    %73:modregbank(s20) = G_CONSTANT i20 -18
    %130:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %5 :: (load (s16))
    %140:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %70 :: (load (s16))
    %150:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %71 :: (load (s16))
    %160:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %72 :: (load (s16))
    %170:gprregbank(s32) = G_AIE_OFFSET_ZEXTLOAD %0, %73 :: (load (s16))
    PseudoRET implicit $lr, implicit %80, implicit %90, implicit %100, implicit %110, implicit %120, implicit %130, implicit %140, implicit %150, implicit %160, implicit %170
...
