# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefix=AIE2 -DER=er %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefix=AIE2P -DER=er %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck -check-prefix=AIE2PS  -DER=mlockid_reg %s


---
name: post-inc-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0, $r1
    ;AIE2-LABEL: name:            post-inc-store

    ;AIE2: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2-NEXT: [[COPY_1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ;AIE2-NEXT: [[MOV__5:%[0-9]+]]:em = MOV_PD_imm10_pseudo 2
    ;AIE2-NEXT: [[COPY_7:%[0-9]+]]:er = COPY $r0
    ;AIE2-NEXT: [[ST_d_8:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_7]], [[COPY_0]], 28 :: (store (s32))
    ;AIE2-NEXT: [[ST_d_9:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_7]], [[COPY_0]], -32 :: (store (s32))
    ;AIE2-NEXT: [[ST_d_10:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_7]], [[COPY_0]], 32 :: (store (s32))
    ;AIE2-NEXT: [[COPY_21:%[0-9]+]]:em = COPY [[COPY_7]]
    ;AIE2-NEXT: [[ST_d_11:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY_7]], [[COPY_0]], [[COPY_21]] :: (store (s32))
    ;AIE2-NEXT: [[ST_d_12:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY_7]], [[COPY_0]], [[MOV__5]] :: (store (s32))
    ;AIE2-NEXT: [[ST_d_13:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_7]], [[COPY_0]], 4 :: (store (s32))
    ;AIE2-NEXT: [[ST_d_14:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_1]], [[COPY_0]], 28 :: (store (p0), align 4)
    ;AIE2-NEXT: [[ST_d_15:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_1]], [[COPY_0]], -32 :: (store (p0), align 4)
    ;AIE2-NEXT: [[ST_d_16:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_1]], [[COPY_0]], 32 :: (store (p0), align 4)
    ;AIE2-NEXT: [[COPY_20:%[0-9]+]]:em = COPY [[COPY_7]]
    ;AIE2-NEXT: [[ST_d_17:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY_1]], [[COPY_0]], [[COPY_20]] :: (store (p0), align 4)
    ;AIE2-NEXT: [[ST_d_18:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY_1]], [[COPY_0]], [[MOV__5]] :: (store (p0), align 4)
    ;AIE2-NEXT: [[ST_d_19:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY_1]], [[COPY_0]], 4 :: (store (p0), align 4)
    ;AIE2-NEXT: PseudoRET implicit $lr


    ; AIE2P-LABEL: name: post-inc-store
    ; AIE2P: liveins: $p0, $p1, $r0, $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 2
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm_imm:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY2]], [[COPY]], 28 :: (store (s32))
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm_imm1:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY2]], [[COPY]], -32 :: (store (s32))
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY2]]
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm1:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY2]], [[COPY]], [[COPY3]] :: (store (s32))
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm2:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (store (s32))
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm_imm2:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY2]], [[COPY]], 4 :: (store (s32))
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm_imm3:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY1]], [[COPY]], 28 :: (store (p0), align 4)
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm_imm4:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY1]], [[COPY]], -32 :: (store (p0), align 4)
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm3:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo]] :: (store (p0), align 4)
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:em = COPY [[COPY2]]
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm4:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY1]], [[COPY]], [[COPY4]] :: (store (p0), align 4)
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm5:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (store (p0), align 4)
    ; AIE2P-NEXT: [[ST_dms_sts_pstm_nrm_imm5:%[0-9]+]]:ep = ST_dms_sts_pstm_nrm_imm [[COPY1]], [[COPY]], 4 :: (store (p0), align 4)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2PS-LABEL: name: post-inc-store
    ; AIE2PS: liveins: $p0, $p1, $r0, $r1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 2
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm_imm:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm_imm [[COPY2]], [[COPY]], 28 :: (store (s32))
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm_imm1:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm_imm [[COPY2]], [[COPY]], -32 :: (store (s32))
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY2]]
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm1:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm [[COPY2]], [[COPY]], [[COPY3]] :: (store (s32))
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm2:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (store (s32))
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm_imm2:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm_imm [[COPY2]], [[COPY]], 4 :: (store (s32))
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm_imm3:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm_imm [[COPY1]], [[COPY]], 28 :: (store (p0), align 4)
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm_imm4:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm_imm [[COPY1]], [[COPY]], -32 :: (store (p0), align 4)
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm3:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo]] :: (store (p0), align 4)
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:em = COPY [[COPY2]]
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm4:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm [[COPY1]], [[COPY]], [[COPY4]] :: (store (p0), align 4)
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm5:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo1]] :: (store (p0), align 4)
    ; AIE2PS-NEXT: [[ST_dms_sts_pstm_nrm_imm5:%[0-9]+]]:ep = ST_dms_sts_scalar_st_pstm_nrm_imm [[COPY1]], [[COPY]], 4 :: (store (p0), align 4)
    ; AIE2PS-NEXT: PseudoRET implicit $lr

    %0:ptrregbank(p0) = COPY $p0
    %8:ptrregbank(p0) = COPY $p1
    %1:modregbank(s20) = G_CONSTANT i20 28
    %2:modregbank(s20) = G_CONSTANT i20 -32
    %3:modregbank(s20) = G_CONSTANT i20 32
    %5:modregbank(s20) = G_CONSTANT i20 2
    %6:modregbank(s20) = G_CONSTANT i20 4
    %4:gprregbank(s32) = COPY $r0
    %80:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %1 :: (store (s32))
    %81:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %2 :: (store (s32))
    %82:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %3 :: (store (s32))
    %83:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %4 :: (store (s32))
    %84:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %5 :: (store (s32))
    %85:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %6 :: (store (s32))
    %86:ptrregbank(p0) = G_AIE_POSTINC_STORE %8, %0, %1 :: (store (p0))
    %87:ptrregbank(p0) = G_AIE_POSTINC_STORE %8, %0, %2 :: (store (p0))
    %88:ptrregbank(p0) = G_AIE_POSTINC_STORE %8, %0, %3 :: (store (p0))
    %89:ptrregbank(p0) = G_AIE_POSTINC_STORE %8, %0, %4 :: (store (p0))
    %90:ptrregbank(p0) = G_AIE_POSTINC_STORE %8, %0, %5 :: (store (p0))
    %91:ptrregbank(p0) = G_AIE_POSTINC_STORE %8, %0, %6 :: (store (p0))
    PseudoRET implicit $lr
...

---
name: post-inc-hb-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ;AIE2-LABEL: name:            post-inc-hb-store

    ;AIE2: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2-NEXT: [[MOV__3:%[0-9]+]]:em = MOV_PD_imm10_pseudo 8
    ;AIE2-NEXT: [[COPY_6:%[0-9]+]]:er = COPY $r0
    ;AIE2-NEXT: [[ST_S_7:%[0-9]+]]:ep = ST_S8_ag_pstm_nrm_imm [[COPY_6]], [[COPY_0]], -8 :: (store (s8))
    ;AIE2-NEXT: [[ST_S_8:%[0-9]+]]:ep = ST_S8_ag_pstm_nrm_imm [[COPY_6]], [[COPY_0]], 7 :: (store (s8))
    ;AIE2-NEXT: [[ST_S_9:%[0-9]+]]:ep = ST_S8_ag_pstm_nrm [[COPY_6]], [[COPY_0]], [[MOV__3]] :: (store (s8))
    ;AIE2-NEXT: [[COPY_26:%[0-9]+]]:em = COPY [[COPY_6]]
    ;AIE2-NEXT: [[ST_S_10:%[0-9]+]]:ep = ST_S8_ag_pstm_nrm [[COPY_6]], [[COPY_0]], [[COPY_26]] :: (store (s8))
    ;AIE2-NEXT: [[ST_S_11:%[0-9]+]]:ep = ST_S8_ag_pstm_nrm_imm [[COPY_6]], [[COPY_0]], 1 :: (store (s8))
    ;AIE2-NEXT: [[ST_S_12:%[0-9]+]]:ep = ST_S8_ag_pstm_nrm_imm [[COPY_6]], [[COPY_0]], -4 :: (store (s8))
    ;AIE2-NEXT: [[MOV__13:%[0-9]+]]:er = MOV_RLC_imm10_pseudo -16
    ;AIE2-NEXT: [[MOV__14:%[0-9]+]]:em = MOV_PD_imm10_pseudo 14
    ;AIE2-NEXT: [[MOV__15:%[0-9]+]]:em = MOV_PD_imm10_pseudo 16
    ;AIE2-NEXT: [[COPY_25:%[0-9]+]]:em = COPY [[MOV__13]]
    ;AIE2-NEXT: [[ST_S_18:%[0-9]+]]:ep = ST_S16_ag_pstm_nrm [[COPY_6]], [[COPY_0]], [[COPY_25]] :: (store (s16))
    ;AIE2-NEXT: [[ST_S_19:%[0-9]+]]:ep = ST_S16_ag_pstm_nrm [[COPY_6]], [[COPY_0]], [[MOV__14]] :: (store (s16))
    ;AIE2-NEXT: [[ST_S_20:%[0-9]+]]:ep = ST_S16_ag_pstm_nrm [[COPY_6]], [[COPY_0]], [[MOV__15]] :: (store (s16))
    ;AIE2-NEXT: [[COPY_24:%[0-9]+]]:em = COPY [[COPY_6]]
    ;AIE2-NEXT: [[ST_S_21:%[0-9]+]]:ep = ST_S16_ag_pstm_nrm [[COPY_6]], [[COPY_0]], [[COPY_24]] :: (store (s16))
    ;AIE2-NEXT: [[ST_S_22:%[0-9]+]]:ep = ST_S16_ag_pstm_nrm_imm [[COPY_6]], [[COPY_0]], 5 :: (store (s16))
    ;AIE2-NEXT: [[ST_S_23:%[0-9]+]]:ep = ST_S16_ag_pstm_nrm_imm [[COPY_6]], [[COPY_0]], -2 :: (store (s16))
    ;AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: post-inc-hb-store
    ; AIE2P: liveins: $p0, $r0, $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:[[ER]] = COPY $r0
    ; AIE2P-NEXT: [[ST_s8_pstm_nrm_imm:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], -8, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2P-NEXT: [[ST_s8_pstm_nrm_imm1:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], 7, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2P-NEXT: [[ST_s8_pstm_nrm:%[0-9]+]]:ep = ST_s8_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[ST_s8_pstm_nrm1:%[0-9]+]]:ep = ST_s8_pstm_nrm [[COPY1]], [[COPY]], [[COPY2]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2P-NEXT: [[ST_s8_pstm_nrm_imm2:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], 1, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2P-NEXT: [[ST_s8_pstm_nrm_imm3:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], -4, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2P-NEXT: [[ST_s16_pstm_nrm_imm:%[0-9]+]]:ep = ST_s16_pstm_nrm_imm [[COPY1]], [[COPY]], -16, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2P-NEXT: [[ST_s16_pstm_nrm_imm1:%[0-9]+]]:ep = ST_s16_pstm_nrm_imm [[COPY1]], [[COPY]], 14, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2P-NEXT: [[ST_s16_pstm_nrm:%[0-9]+]]:ep = ST_s16_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[ST_s16_pstm_nrm1:%[0-9]+]]:ep = ST_s16_pstm_nrm [[COPY1]], [[COPY]], [[COPY3]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2P-NEXT: [[ST_s16_pstm_nrm2:%[0-9]+]]:ep = ST_s16_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo2]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2P-NEXT: [[ST_s16_pstm_nrm_imm2:%[0-9]+]]:ep = ST_s16_pstm_nrm_imm [[COPY1]], [[COPY]], -2, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2P-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2PS-LABEL: name: post-inc-hb-store
    ; AIE2PS: liveins: $p0, $r0, $r1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 8
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:[[ER]] = COPY $r0
    ; AIE2PS-NEXT: [[ST_s8_pstm_nrm_imm:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], -8, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2PS-NEXT: [[ST_s8_pstm_nrm_imm1:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], 7, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2PS-NEXT: [[ST_s8_pstm_nrm:%[0-9]+]]:ep = ST_s8_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[ST_s8_pstm_nrm1:%[0-9]+]]:ep = ST_s8_pstm_nrm [[COPY1]], [[COPY]], [[COPY2]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2PS-NEXT: [[ST_s8_pstm_nrm_imm2:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], 1, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2PS-NEXT: [[ST_s8_pstm_nrm_imm3:%[0-9]+]]:ep = ST_s8_pstm_nrm_imm [[COPY1]], [[COPY]], -4, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 5
    ; AIE2PS-NEXT: [[ST_s16_pstm_nrm_imm:%[0-9]+]]:ep = ST_s16_pstm_nrm_imm [[COPY1]], [[COPY]], -16, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2PS-NEXT: [[ST_s16_pstm_nrm_imm1:%[0-9]+]]:ep = ST_s16_pstm_nrm_imm [[COPY1]], [[COPY]], 14, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2PS-NEXT: [[ST_s16_pstm_nrm:%[0-9]+]]:ep = ST_s16_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[ST_s16_pstm_nrm1:%[0-9]+]]:ep = ST_s16_pstm_nrm [[COPY1]], [[COPY]], [[COPY3]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2PS-NEXT: [[ST_s16_pstm_nrm2:%[0-9]+]]:ep = ST_s16_pstm_nrm [[COPY1]], [[COPY]], [[MOV_PD_imm11_pseudo2]], implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2PS-NEXT: [[ST_s16_pstm_nrm_imm2:%[0-9]+]]:ep = ST_s16_pstm_nrm_imm [[COPY1]], [[COPY]], -2, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16))
    ; AIE2PS-NEXT: PseudoRET implicit $lr

    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s20) = G_CONSTANT i20 -8
    %2:modregbank(s20) = G_CONSTANT i20 7
    %3:modregbank(s20) = G_CONSTANT i20 8
    %5:modregbank(s20) = G_CONSTANT i20 1
    %6:modregbank(s20) = G_CONSTANT i20 -4
    %4:gprregbank(s32) = COPY $r0
    %80:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %1 :: (store (s8))
    %81:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %2 :: (store (s8))
    %82:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %3 :: (store (s8))
    %83:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %4 :: (store (s8))
    %84:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %5 :: (store (s8))
    %85:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %6 :: (store (s8))
    %10:gprregbank(s20) = G_CONSTANT i20 -16
    %20:modregbank(s20) = G_CONSTANT i20 14
    %30:modregbank(s20) = G_CONSTANT i20 16
    %50:modregbank(s20) = G_CONSTANT i20 5
    %60:modregbank(s20) = G_CONSTANT i20 -2
    %86:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %10 :: (store (s16))
    %87:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %20 :: (store (s16))
    %88:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %30 :: (store (s16))
    %89:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %4 :: (store (s16))
    %90:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %50 :: (store (s16))
    %91:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %60 :: (store (s16))
    PseudoRET implicit $lr
...
