# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s
---
name: v8s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v8s32
    ; AIE2: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v8s32
    ; AIE2P: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<8 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<8 x s32>)
...

---
name: v16s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v16s16
    ; AIE2: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v16s16
    ; AIE2P: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<16 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<16 x s16>)
...

---
name: v32s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v32s8
    ; AIE2: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v32s8
    ; AIE2P: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<32 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<32 x s8>)
...

---
name: v16s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v16s32
    ; AIE2: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v16s32
    ; AIE2P: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<16 x s32>)
...

---
name: v32s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v32s16
    ; AIE2: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v32s16
    ; AIE2P: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<32 x s16>)
...

---
name: v64s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v64s8
    ; AIE2: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v64s8
    ; AIE2P: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<64 x s8>)
...

---
name: acc512
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: acc512
    ; AIE2: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: acc512
    ; AIE2P: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:accregbank(<8 x s64>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<8 x s64>)
...

---
name: v32s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v32s32
    ; AIE2: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v32s32
    ; AIE2P: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<32 x s32>)
...

---
name: v64s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v64s16
    ; AIE2: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v64s16
    ; AIE2P: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<64 x s16>)
...

---
name: v128s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: v128s8
    ; AIE2: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: v128s8
    ; AIE2P: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<128 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<128 x s8>)
...

---
name: acc1024
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; AIE2-LABEL: name: acc1024
    ; AIE2: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    ;
    ; AIE2P-LABEL: name: acc1024
    ; AIE2P: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<16 x s64>)
...
