# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefixes CHECK,AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefixes CHECK,AIE2PS %s

---
name:            trunc_gpr_gpr
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: trunc_gpr_gpr
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: $p1 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s20) = G_TRUNC %0
    $p1 = COPY %1
    PseudoRET implicit $lr, implicit %1
...

---
name:            trunc_gpr_ptr
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: trunc_gpr_ptr
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY [[COPY]]
    ; CHECK-NEXT: $p1 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]]
    %0:gprregbank(s32) = COPY $r6
    %1:ptrregbank(s20) = G_TRUNC %0
    $p1 = COPY %1
    PseudoRET implicit $lr, implicit %1
...

---
name:            v16s32_trunc_v16s64_acc1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v16s32_trunc_v16s64_acc1024
    ; AIE2P: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    ;
    ; AIE2PS-LABEL: name: v16s32_trunc_v16s64_acc1024
    ; AIE2PS: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 24
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v16s32AccBnk_trunc_v16s64_acc1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v16s32AccBnk_trunc_v16s64_acc1024
    ; AIE2P: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_bm:%[0-9]+]]:mbmsm = VSHUFFLE_vec_shuffle_bm [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_bm]]
    ;
    ; AIE2PS-LABEL: name: v16s32AccBnk_trunc_v16s64_acc1024
    ; AIE2PS: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 24
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_bm:%[0-9]+]]:mbmsm = VSHUFFLE_vec_shuffle_bm [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_bm]]
    %1:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %0:accregbank(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v32s16_trunc_v32s32_acc1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v32s16_trunc_v32s32_acc1024
    ; AIE2P: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    ;
    ; AIE2PS-LABEL: name: v32s16_trunc_v32s32_acc1024
    ; AIE2PS: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 26
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<32 x s16>) = G_TRUNC %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v8s32_trunc_v8s64_acc512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v8s32_trunc_v8s64_acc512
    ; AIE2P: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mxm = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:mxn = COPY [[DEF]]
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[COPY2]]
    ;
    ; AIE2PS-LABEL: name: v8s32_trunc_v8s64_acc512
    ; AIE2PS: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 24
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mxm = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mxn = COPY [[DEF]]
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:mwla = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[COPY2]]
    %1:accregbank(<8 x s64>) = G_IMPLICIT_DEF
    %0:vregbank(<8 x s32>) = G_TRUNC %1(<8 x s64>)
    PseudoRET implicit $lr, implicit %0

...
---
name:            v16s16_trunc_v16s32_acc512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v16s16_trunc_v16s32_acc512
    ; AIE2P: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mxm = COPY [[DEF]]
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:mxn = COPY [[DEF]]
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[COPY2]]
    ;
    ; AIE2PS-LABEL: name: v16s16_trunc_v16s32_acc512
    ; AIE2PS: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 26
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mxm = COPY [[DEF]]
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mxn = COPY [[DEF]]
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:mwla = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[COPY2]]
    %1:accregbank(<16 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s16>) = G_TRUNC %1(<16 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v16s32_trunc_v16s64_vec1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v16s32_trunc_v16s64_vec1024
    ; AIE2P: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    ;
    ; AIE2PS-LABEL: name: v16s32_trunc_v16s64_vec1024
    ; AIE2PS: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 24
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:vregbank(<16 x s64>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v32s16_trunc_v32s32_vec1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v32s16_trunc_v32s32_vec1024
    ; AIE2P: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    ;
    ; AIE2PS-LABEL: name: v32s16_trunc_v32s32_vec1024
    ; AIE2PS: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 26
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<32 x s16>) = G_TRUNC %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v64s8_trunc_v64s16_vec1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v64s8_trunc_v64s16_vec1024
    ; AIE2P: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    ;
    ; AIE2PS-LABEL: name: v64s8_trunc_v64s16_vec1024
    ; AIE2PS: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 28
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    %0:vregbank(<64 x s8>) = G_TRUNC %1(<64 x s16>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v16s16_trunc_v16s32_vec512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v16s16_trunc_v16s32_vec512
    ; AIE2P: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    ;
    ; AIE2PS-LABEL: name: v16s16_trunc_v16s32_vec512
    ; AIE2PS: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 26
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mwla = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s16>) = G_TRUNC %1(<16 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v32s8_trunc_v32s16_vec512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; AIE2P-LABEL: name: v32s8_trunc_v32s16_vec512
    ; AIE2P: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; AIE2P-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    ;
    ; AIE2PS-LABEL: name: v32s8_trunc_v32s16_vec512
    ; AIE2PS: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 28
    ; AIE2PS-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mwla = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %1:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    %0:vregbank(<32 x s8>) = G_TRUNC %1(<32 x s16>)
    PseudoRET implicit $lr, implicit %0
...
