# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1 %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s

---
name:            test_brjt
legalized:       true
regBankSelected: true
body:             |
  bb.0:
    liveins: $p0
    ; AIE1-LABEL: name: test_brjt
    ; AIE1: liveins: $p0
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:ptr = COPY $p0
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:mcb = COPY [[COPY]]
    ; AIE1-NEXT: JA [[COPY1]]
    ;
    ; AIE2-LABEL: name: test_brjt
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: PseudoJ_jump_ind [[COPY]]
    ;
    ; AIE2P-LABEL: name: test_brjt
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: PseudoJ_jump_ind [[COPY]]
    %0:ptrregbank(p0) = COPY $p0
    G_BRINDIRECT %0(p0)

...
