# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=COMMON --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=COMMON --check-prefix=AIE2P

---
name:            _512bit_extract_16bit_zext
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0

    ; AIE2-LABEL: name: _512bit_extract_16bit_zext
    ; AIE2: liveins: $x0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:ers4 = MOV_RLC_imm10_pseudo 1
    ; AIE2-NEXT: [[VEXTRACT_D16_:%[0-9]+]]:er = VEXTRACT_D16 [[COPY]], [[MOV_RLC_imm10_pseudo]], implicit $crvaddsign
    ; AIE2-NEXT: $r0 = COPY [[VEXTRACT_D16_]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: _512bit_extract_16bit_zext
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VEXTRACT_16_vec_extract_imm_vaddSign0_:%[0-9]+]]:er = VEXTRACT_16_vec_extract_imm_vaddSign0 [[COPY]], 1, implicit $vaddsign0
    ; AIE2P-NEXT: $r0 = COPY [[VEXTRACT_16_vec_extract_imm_vaddSign0_]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %3:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            _512bit_extract_16bit_sext
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0

    ; AIE2-LABEL: name: _512bit_extract_16bit_sext
    ; AIE2: liveins: $x0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:ers4 = MOV_RLC_imm10_pseudo 1
    ; AIE2-NEXT: [[VEXTRACT_S16_:%[0-9]+]]:er = VEXTRACT_S16 [[COPY]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: $r0 = COPY [[VEXTRACT_S16_]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: _512bit_extract_16bit_sext
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VEXTRACT_16_vec_extract_imm_vaddSign1_:%[0-9]+]]:er = VEXTRACT_16_vec_extract_imm_vaddSign1 [[COPY]], 1, implicit $vaddsign1
    ; AIE2P-NEXT: $r0 = COPY [[VEXTRACT_16_vec_extract_imm_vaddSign1_]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %3:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            _512bit_extract_8bit_sext
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0

    ; AIE2-LABEL: name: _512bit_extract_8bit_sext
    ; AIE2: liveins: $x0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:ers4 = MOV_RLC_imm10_pseudo 1
    ; AIE2-NEXT: [[VEXTRACT_S8_:%[0-9]+]]:er = VEXTRACT_S8 [[COPY]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: $r0 = COPY [[VEXTRACT_S8_]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: _512bit_extract_8bit_sext
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VEXTRACT_8_vec_extract_imm_vaddSign1_:%[0-9]+]]:er = VEXTRACT_8_vec_extract_imm_vaddSign1 [[COPY]], 1, implicit $vaddsign1
    ; AIE2P-NEXT: $r0 = COPY [[VEXTRACT_8_vec_extract_imm_vaddSign1_]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %3:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<64 x s8>), %2(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            _512bit_extract_8bit_zext
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0

    ; AIE2-LABEL: name: _512bit_extract_8bit_zext
    ; AIE2: liveins: $x0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:ers4 = MOV_RLC_imm10_pseudo 1
    ; AIE2-NEXT: [[VEXTRACT_D8_:%[0-9]+]]:er = VEXTRACT_D8 [[COPY]], [[MOV_RLC_imm10_pseudo]], implicit $crvaddsign
    ; AIE2-NEXT: $r0 = COPY [[VEXTRACT_D8_]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: _512bit_extract_8bit_zext
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VEXTRACT_8_vec_extract_imm_vaddSign0_:%[0-9]+]]:er = VEXTRACT_8_vec_extract_imm_vaddSign0 [[COPY]], 1, implicit $vaddsign0
    ; AIE2P-NEXT: $r0 = COPY [[VEXTRACT_8_vec_extract_imm_vaddSign0_]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %3:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %1(<64 x s8>), %2(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            _512bit_extract_32bit
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0

    ; AIE2-LABEL: name: _512bit_extract_32bit
    ; AIE2: liveins: $x0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:ers4 = MOV_RLC_imm10_pseudo 1
    ; AIE2-NEXT: [[VEXTRACT_S32_:%[0-9]+]]:er = VEXTRACT_S32 [[COPY]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: $r0 = COPY [[VEXTRACT_S32_]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: _512bit_extract_32bit
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VEXTRACT_32_vec_extract_imm_vaddSign1_:%[0-9]+]]:er = VEXTRACT_32_vec_extract_imm_vaddSign1 [[COPY]], 1, implicit $vaddsign1
    ; AIE2P-NEXT: $r0 = COPY [[VEXTRACT_32_vec_extract_imm_vaddSign1_]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<16 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            extract_32bit_v2int32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0

    ; COMMON-LABEL: name: extract_32bit_v2int32
    ; COMMON: liveins: $l0
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:er = COPY [[COPY]].sub_l_even
    ; COMMON-NEXT: $r0 = COPY [[COPY1]]
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(<2 x s32>) = COPY $l0
    %5:gprregbank(s64) = G_BITCAST %1(<2 x s32>)
    %3:gprregbank(s32) = G_TRUNC %5(s64)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
