# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s

---

name:            br
legalized:       true
regBankSelected: true

body: |
  ; AIE-LABEL: name: br
  ; AIE: bb.0:
  ; AIE-NEXT:   successors: %bb.1(0x80000000)
  ; AIE-NEXT: {{  $}}
  ; AIE-NEXT:   PseudoBR %bb.1
  ; AIE-NEXT: {{  $}}
  ; AIE-NEXT: bb.1:
  ;
  ; AIE2-LABEL: name: br
  ; AIE2: bb.0:
  ; AIE2-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   PseudoJ_jump_imm %bb.1
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  bb.0:
    G_BR %bb.1

  bb.1:

...
