# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P

---
name:            vshift_v64i8
legalized:       true
regBankSelected: true
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: vshift_v64i8
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VSHIFT:%[0-9]+]]:vec512 = VSHIFT [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHIFT]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %2:vregbank(<64 x s8>) = G_AIE_VSHIFT_RIGHT %1, %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
...
---
name:            vshift_v32i16
legalized:       true
regBankSelected: true
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: vshift_v32i16
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VSHIFT:%[0-9]+]]:vec512 = VSHIFT [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHIFT]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    %2:vregbank(<32 x s16>) = G_AIE_VSHIFT_RIGHT %1, %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
...
---
name:            vshift_v16i32
legalized:       true
regBankSelected: true
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: vshift_v16i32
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VSHIFT:%[0-9]+]]:vec512 = VSHIFT [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHIFT]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<16 x s32>) = G_AIE_VSHIFT_RIGHT %1, %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
...
---
name:            vshift_v8i64
legalized:       true
regBankSelected: true
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: vshift_v8i64
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VSHIFT:%[0-9]+]]:vec512 = VSHIFT [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VSHIFT]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:vregbank(<8 x s64>) = G_IMPLICIT_DEF
    %2:vregbank(<8 x s64>) = G_AIE_VSHIFT_RIGHT %1, %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
...
