# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

---
name:            vpush_int32_512
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 64, alignment: 32 }
body:             |
  bb.0.entry:
    ; AIE2-LABEL: name: vpush_int32_512
    ; AIE2: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 12
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2-NEXT: [[VPUSH_HI_32_:%[0-9]+]]:vec512 = VPUSH_HI_32 [[DEF]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_HI_32_]]
    ;
    ; AIE2P-LABEL: name: vpush_int32_512
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VPUSH_hi_32_:%[0-9]+]]:vec512 = VPUSH_hi_32 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_32_]]
    ;
    ; AIE2PS-LABEL: name: vpush_int32_512
    ; AIE2PS: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 12
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[VPUSH_hi_32_:%[0-9]+]]:vec512 = VPUSH_hi_32 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_32_]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
...


---
name:            vpush_int16_512
legalized: true
regBankSelected: true
stack:
  - { id: 0, name: "", size: 64, alignment: 32}
body:             |
  bb.0.entry:
    ; AIE2-LABEL: name: vpush_int16_512
    ; AIE2: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 12
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2-NEXT: [[VPUSH_HI_16_:%[0-9]+]]:vec512 = VPUSH_HI_16 [[DEF]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_HI_16_]]
    ;
    ; AIE2P-LABEL: name: vpush_int16_512
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VPUSH_hi_16_:%[0-9]+]]:vec512 = VPUSH_hi_16 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_16_]]
    ;
    ; AIE2PS-LABEL: name: vpush_int16_512
    ; AIE2PS: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 12
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[VPUSH_hi_16_:%[0-9]+]]:vec512 = VPUSH_hi_16 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_16_]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    %2:vregbank(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vpush_int8_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 64, alignment: 32}
body:             |
  bb.0.entry:
    ; AIE2-LABEL: name: vpush_int8_512
    ; AIE2: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 12
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2-NEXT: [[VPUSH_HI_8_:%[0-9]+]]:vec512 = VPUSH_HI_8 [[DEF]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_HI_8_]]
    ;
    ; AIE2P-LABEL: name: vpush_int8_512
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 12
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VPUSH_hi_8_:%[0-9]+]]:vec512 = VPUSH_hi_8 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_8_]]
    ;
    ; AIE2PS-LABEL: name: vpush_int8_512
    ; AIE2PS: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 12
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[VPUSH_hi_8_:%[0-9]+]]:vec512 = VPUSH_hi_8 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_8_]]
    %0:gprregbank(s32) = G_CONSTANT i32 12
    %1:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %2:vregbank(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vpush_int32_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 32, alignment: 32 }
body:             |
  bb.0.entry:
    ; AIE2-LABEL: name: vpush_int32_256
    ; AIE2: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2-NEXT: [[VPUSH_HI_32_:%[0-9]+]]:vec512 = VPUSH_HI_32 [[DEF]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_HI_32_]]
    ;
    ; AIE2P-LABEL: name: vpush_int32_256
    ; AIE2P: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VPUSH_hi_32_:%[0-9]+]]:vec512 = VPUSH_hi_32 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_32_]]
    ;
    ; AIE2PS-LABEL: name: vpush_int32_256
    ; AIE2PS: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 0
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2PS-NEXT: [[VPUSH_hi_32_:%[0-9]+]]:vec512 = VPUSH_hi_32 [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VPUSH_hi_32_]]
    %0:gprregbank(s32) = G_CONSTANT i32 0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI %1, %0(s32)
    PseudoRET implicit $lr, implicit %2
