# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

---
name:            llvm_start_loop_iterations_static
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r0
    ; AIE2-LABEL: name: llvm_start_loop_iterations_static
    ; AIE2: liveins: $r0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 9
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[MOV_RLC_imm10_pseudo]]
    ;
    ; AIE2P-LABEL: name: llvm_start_loop_iterations_static
    ; AIE2P: liveins: $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 9
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[MOV_RLC_imm11_pseudo]]
    ;
    ; AIE2PS-LABEL: name: llvm_start_loop_iterations_static
    ; AIE2PS: liveins: $r0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 9
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[MOV_RLC_imm11_pseudo]]
    %0:gprregbank(s32) = G_CONSTANT i32 10
    %1:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.start.loop.iterations), %0(s32)
    PseudoRET implicit $lr, implicit %1
...


---
name:            llvm_start_loop_iterations_dynamic
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r0
    ; AIE2-LABEL: name: llvm_start_loop_iterations_dynamic
    ; AIE2: liveins: $r0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; AIE2-NEXT: [[ADD_NC:%[0-9]+]]:er = ADD_NC [[COPY]], -1
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[ADD_NC]]
    ;
    ; AIE2P-LABEL: name: llvm_start_loop_iterations_dynamic
    ; AIE2P: liveins: $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[ADD_NC_mv_add_ri:%[0-9]+]]:er = ADD_NC_mv_add_ri [[COPY]], -1
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[ADD_NC_mv_add_ri]]
    ;
    ; AIE2PS-LABEL: name: llvm_start_loop_iterations_dynamic
    ; AIE2PS: liveins: $r0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; AIE2PS-NEXT: [[ADDM_NC_mv_add_ri:%[0-9]+]]:er = ADDM_NC_mv_add_ri [[COPY]], -1
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[ADDM_NC_mv_add_ri]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.start.loop.iterations), %0(s32)
    PseudoRET implicit $lr, implicit %1
...
