# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

---
name:            llvm_loop_decrement_reg
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r0
    ; AIE2-LABEL: name: llvm_loop_decrement_reg
    ; AIE2: successors: %bb.0(0x80000000)
    ; AIE2-NEXT: liveins: $r0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; AIE2-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:ep_as_32bit = MOVXM_lng_cg %bb.0
    ; AIE2-NEXT: [[LoopDec:%[0-9]+]]:er = LoopDec [[COPY]], implicit-def $srcarry
    ; AIE2-NEXT: LoopJNZ [[LoopDec]], [[MOVXM_lng_cg]]
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: llvm_loop_decrement_reg
    ; AIE2P: successors: %bb.0(0x80000000)
    ; AIE2P-NEXT: liveins: $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[MOVXM:%[0-9]+]]:ep_as_32bit = MOVXM %bb.0
    ; AIE2P-NEXT: [[LoopDec:%[0-9]+]]:er = LoopDec [[COPY]], implicit-def $srcarry
    ; AIE2P-NEXT: LoopJNZ [[LoopDec]], [[MOVXM]]
    ; AIE2P-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2PS-LABEL: name: llvm_loop_decrement_reg
    ; AIE2PS: successors: %bb.0(0x80000000)
    ; AIE2PS-NEXT: liveins: $r0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:ep_as_32bit = MOVXM_lng_cg %bb.0
    ; AIE2PS-NEXT: [[LoopDec:%[0-9]+]]:er = LoopDec [[COPY]], implicit-def $srcarry
    ; AIE2PS-NEXT: LoopJNZ [[LoopDec]], [[MOVXM_lng_cg]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = G_CONSTANT i32 0
    %1:gprregbank(s32) = G_CONSTANT i32 1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement.reg), %2(s32), %1(s32)
    %4:gprregbank(s32) = G_ICMP intpred(ne), %3(s32), %0
    G_BRCOND %4(s32), %bb.0
    PseudoRET implicit $lr
...
