# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name: constant_s32_gpr_class_min_signed_12_bits_minus_one
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_class_min_signed_12_bits_minus_one
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 1046527
    ; CHECK-NEXT: [[MOVT_S12_:%[0-9]+]]:gpr = MOVT_S12 [[MOV_U20_]], 4095
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOVT_S12_]]
    %0:gpr(s32) = G_CONSTANT i32 -2049
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_gpr_class_min_signed_12_bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_class_min_signed_12_bits
    ; CHECK: [[MOV_S12_:%[0-9]+]]:gpr = MOV_S12 -2048
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_S12_]]
    %0:gpr(s32) = G_CONSTANT i32 -2048
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_gpr_class_max_signed_12_bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_class_max_signed_12_bits
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 2047
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:gpr(s32) = G_CONSTANT i32 2047
    PseudoRET implicit $lr, implicit %0
...


---
name: constant_s32_gpr_max_20_bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_max_20_bits
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 1048575
    ; CHECK-NEXT: [[MOVT_S12_:%[0-9]+]]:gpr = MOVT_S12 [[MOV_U20_]], 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOVT_S12_]]
    %0:gprregbank(s32) = G_CONSTANT i32 1048575
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_gpr_class_max_20_bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_class_max_20_bits
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 1048575
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:gpr(s32) = G_CONSTANT i32 1048575
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_mrcm_class_max_20_bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_mrcm_class_max_20_bits
    ; CHECK: [[MOV_U20_:%[0-9]+]]:mrcm = MOV_U20 1048575
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:mrcm(s32) = G_CONSTANT i32 1048575
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_gpr_class_min_signed_20_bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_class_min_signed_20_bits
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 524288
    ; CHECK-NEXT: [[MOVT_S12_:%[0-9]+]]:gpr = MOVT_S12 [[MOV_U20_]], 4095
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOVT_S12_]]
    %0:gpr(s32) = G_CONSTANT i32 -524288
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_gpr_class_max_signed_20_bits
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_class_max_signed_20_bits
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 524287
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:gpr(s32) = G_CONSTANT i32 524287
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_gpr_max_20_bits_plus_one
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_max_20_bits_plus_one
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[MOVT_S12_:%[0-9]+]]:gpr = MOVT_S12 [[MOV_U20_]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOVT_S12_]]
    %0:gprregbank(s32) = G_CONSTANT i32 1048576
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_gpr_class_max_20_bits_plus_one
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_gpr_class_max_20_bits_plus_one
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[MOVT_S12_:%[0-9]+]]:gpr = MOVT_S12 [[MOV_U20_]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOVT_S12_]]
    %0:gpr(s32) = G_CONSTANT i32 1048576
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s32_mrcm_class_max_20_bits_plus_one
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s32_mrcm_class_max_20_bits_plus_one
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[MOVT_S12_:%[0-9]+]]:gpr = MOVT_S12 [[MOV_U20_]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOVT_S12_]]
    %0:mrcm(s32) = G_CONSTANT i32 1048576
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_p0_ptr
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_p0_ptr
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gprptrmod_and_ptr = MOV_U20 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:ptrregbank(p0) = G_CONSTANT i20 0
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_p0_ptr_class
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_p0_ptr_class
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gprptrmod_and_ptr = MOV_U20 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:ptr(p0) = G_CONSTANT i20 0
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_p0_gpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_p0_gpr
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:gprregbank(p0) = G_CONSTANT i20 0
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_p0_gpr_class
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: constant_p0_gpr_class
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:gpr(p0) = G_CONSTANT i20 0
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s20
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s20
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 5
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:gprregbank(s20) = G_CONSTANT i20 5
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_s20_gpr_class
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: constant_s20_gpr_class
    ; CHECK: [[MOV_U20_I20_:%[0-9]+]]:gpr = MOV_U20_I20 5
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_I20_]]
    %0:gpr(s20) = G_CONSTANT i20 5
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_i20_to_p0
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: constant_i20_to_p0
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gprptrmod_and_ptr = MOV_U20 5
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:ptrregbank(s20) = G_CONSTANT i20 5
    PseudoRET implicit $lr, implicit %0
...

---
name: constant_i20_to_ptr_class
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: constant_i20_to_ptr_class
    ; CHECK: [[MOV_U20_:%[0-9]+]]:gprptrmod_and_ptr = MOV_U20 5
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_U20_]]
    %0:ptr(s20) = G_CONSTANT i20 5
    PseudoRET implicit $lr, implicit %0
...
