# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc --mtriple=aie2 --run-pass=instruction-select %s -o -  | FileCheck --check-prefix=AIE2 %s
# RUN: llc --mtriple=aie2p --run-pass=instruction-select %s -o -  | FileCheck  --check-prefix=AIE2P %s
# RUN: llc --mtriple=aie2ps --run-pass=instruction-select %s -o -  | FileCheck  --check-prefix=AIE2PS %s

---
name:            shouldMatch
alignment:       16
legalized:       true
regBankSelected: true
selected:        false
tracksRegLiveness: true
body:             |
  ; AIE2-LABEL: name: shouldMatch
  ; AIE2: bb.0.entry:
  ; AIE2-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; AIE2-NEXT:   liveins: $r0, $r1
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[COPY:%[0-9]+]]:er27 = COPY $r0
  ; AIE2-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r1
  ; AIE2-NEXT:   [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 2
  ; AIE2-NEXT:   [[MOV_RLC_imm10_pseudo1:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 3
  ; AIE2-NEXT:   PseudoJZ [[COPY]], %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  ; AIE2-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   PseudoJNZ [[COPY1]], %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2:
  ; AIE2-NEXT:   [[SELEQZ:%[0-9]+]]:er = SELEQZ [[MOV_RLC_imm10_pseudo]], [[MOV_RLC_imm10_pseudo1]], [[COPY]]
  ; AIE2-NEXT:   [[SELNEZ:%[0-9]+]]:er = SELNEZ [[MOV_RLC_imm10_pseudo1]], [[MOV_RLC_imm10_pseudo]], [[COPY]]
  ; AIE2-NEXT:   PseudoRET implicit $lr, implicit [[SELEQZ]], implicit [[SELNEZ]]
  ;
  ; AIE2P-LABEL: name: shouldMatch
  ; AIE2P: bb.0.entry:
  ; AIE2P-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; AIE2P-NEXT:   liveins: $r0, $r1
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:mr27_select = COPY $r0
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r1
  ; AIE2P-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
  ; AIE2P-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 3
  ; AIE2P-NEXT:   PseudoJZ [[COPY]], %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1:
  ; AIE2P-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   PseudoJNZ [[COPY1]], %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.2:
  ; AIE2P-NEXT:   [[SEL_EQZ:%[0-9]+]]:er = SEL_EQZ [[MOV_RLC_imm11_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[COPY]]
  ; AIE2P-NEXT:   [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]], [[COPY]]
  ; AIE2P-NEXT:   PseudoRET implicit $lr, implicit [[SEL_EQZ]], implicit [[SEL_NEZ]]
  ;
  ; AIE2PS-LABEL: name: shouldMatch
  ; AIE2PS: bb.0.entry:
  ; AIE2PS-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; AIE2PS-NEXT:   liveins: $r0, $r1
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   [[COPY:%[0-9]+]]:mr27_select = COPY $r0
  ; AIE2PS-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r1
  ; AIE2PS-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 2
  ; AIE2PS-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 3
  ; AIE2PS-NEXT:   PseudoJZ [[COPY]], %bb.2
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.1:
  ; AIE2PS-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   PseudoJNZ [[COPY1]], %bb.2
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.2:
  ; AIE2PS-NEXT:   [[SEL_EQZ:%[0-9]+]]:mlockid_reg = SEL_EQZ [[MOV_RLC_imm11_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[COPY]]
  ; AIE2PS-NEXT:   [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]], [[COPY]]
  ; AIE2PS-NEXT:   PseudoRET implicit $lr, implicit [[SEL_EQZ]], implicit [[SEL_NEZ]]
  bb.1.entry:
    liveins: $r0, $r1

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %6:gprregbank(s32) = G_CONSTANT i32 2
    %9:gprregbank(s32) = G_CONSTANT i32 3
    %22:gprregbank(s32) = G_ICMP intpred(eq), %0(s32), %2
    G_BRCOND %22(s32), %bb.3

  bb.2:
    %20:gprregbank(s32) = G_ICMP intpred(ne), %1(s32), %2
    G_BRCOND %20(s32), %bb.3

  bb.3:
    %18:gprregbank(s32) = G_ICMP intpred(eq), %0(s32), %2
    %8:gprregbank(s32) = G_SELECT %18(s32), %6, %9
    %16:gprregbank(s32) = G_ICMP intpred(ne), %0(s32), %2
    %11:gprregbank(s32) = G_SELECT %16(s32), %9, %6
    PseudoRET implicit $lr, implicit %8, implicit %11
...
---
name:            shouldNotMatch
alignment:       16
legalized:       true
regBankSelected: true
selected:        false
tracksRegLiveness: true
body:             |
  ; AIE2-LABEL: name: shouldNotMatch
  ; AIE2: bb.0.entry:
  ; AIE2-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; AIE2-NEXT:   liveins: $r0, $r1
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; AIE2-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r1
  ; AIE2-NEXT:   [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 1
  ; AIE2-NEXT:   [[MOV_RLC_imm10_pseudo1:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 2
  ; AIE2-NEXT:   [[MOV_RLC_imm10_pseudo2:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 3
  ; AIE2-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY]], [[MOV_RLC_imm10_pseudo]]
  ; AIE2-NEXT:   PseudoJNZ [[EQ]], %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  ; AIE2-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[NE:%[0-9]+]]:er = NE [[COPY1]], [[MOV_RLC_imm10_pseudo]]
  ; AIE2-NEXT:   PseudoJNZ [[NE]], %bb.2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2:
  ; AIE2-NEXT:   [[EQ1:%[0-9]+]]:er27 = EQ [[COPY]], [[MOV_RLC_imm10_pseudo]]
  ; AIE2-NEXT:   [[SELNEZ:%[0-9]+]]:er = SELNEZ [[MOV_RLC_imm10_pseudo1]], [[MOV_RLC_imm10_pseudo2]], [[EQ1]]
  ; AIE2-NEXT:   [[NE1:%[0-9]+]]:er27 = NE [[COPY]], [[MOV_RLC_imm10_pseudo]]
  ; AIE2-NEXT:   [[SELNEZ1:%[0-9]+]]:er = SELNEZ [[MOV_RLC_imm10_pseudo2]], [[MOV_RLC_imm10_pseudo1]], [[NE1]]
  ; AIE2-NEXT:   PseudoRET implicit $lr, implicit [[SELNEZ]], implicit [[SELNEZ1]]
  ;
  ; AIE2P-LABEL: name: shouldNotMatch
  ; AIE2P: bb.0.entry:
  ; AIE2P-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; AIE2P-NEXT:   liveins: $r0, $r1
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; AIE2P-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r1
  ; AIE2P-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 1
  ; AIE2P-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
  ; AIE2P-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 3
  ; AIE2P-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2P-NEXT:   PseudoJNZ [[EQ]], %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.1:
  ; AIE2P-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   [[NE:%[0-9]+]]:er = NE [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2P-NEXT:   PseudoJNZ [[NE]], %bb.2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT: bb.2:
  ; AIE2P-NEXT:   [[EQ1:%[0-9]+]]:mr27_select = EQ [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2P-NEXT:   [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo2]], [[EQ1]]
  ; AIE2P-NEXT:   [[NE1:%[0-9]+]]:mr27_select = NE [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2P-NEXT:   [[SEL_NEZ1:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo2]], [[MOV_RLC_imm11_pseudo1]], [[NE1]]
  ; AIE2P-NEXT:   PseudoRET implicit $lr, implicit [[SEL_NEZ]], implicit [[SEL_NEZ1]]
  ;
  ; AIE2PS-LABEL: name: shouldNotMatch
  ; AIE2PS: bb.0.entry:
  ; AIE2PS-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; AIE2PS-NEXT:   liveins: $r0, $r1
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
  ; AIE2PS-NEXT:   [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r1
  ; AIE2PS-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 1
  ; AIE2PS-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 2
  ; AIE2PS-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 3
  ; AIE2PS-NEXT:   [[EQ:%[0-9]+]]:mlockid_reg = EQ [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2PS-NEXT:   PseudoJNZ [[EQ]], %bb.2
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.1:
  ; AIE2PS-NEXT:   successors: %bb.2(0x80000000)
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   [[NE:%[0-9]+]]:mlockid_reg = NE [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2PS-NEXT:   PseudoJNZ [[NE]], %bb.2
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT: bb.2:
  ; AIE2PS-NEXT:   [[EQ1:%[0-9]+]]:mr27_select = EQ [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2PS-NEXT:   [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo2]], [[EQ1]]
  ; AIE2PS-NEXT:   [[NE1:%[0-9]+]]:mr27_select = NE [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; AIE2PS-NEXT:   [[SEL_NEZ1:%[0-9]+]]:mlockid_reg = SEL_NEZ [[MOV_RLC_imm11_pseudo2]], [[MOV_RLC_imm11_pseudo1]], [[NE1]]
  ; AIE2PS-NEXT:   PseudoRET implicit $lr, implicit [[SEL_NEZ]], implicit [[SEL_NEZ1]]
  bb.1.entry:
    liveins: $r0, $r1

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %6:gprregbank(s32) = G_CONSTANT i32 2
    %9:gprregbank(s32) = G_CONSTANT i32 3
    %22:gprregbank(s32) = G_ICMP intpred(eq), %0(s32), %2
    G_BRCOND %22(s32), %bb.3

  bb.2:
    %20:gprregbank(s32) = G_ICMP intpred(ne), %1(s32), %2
    G_BRCOND %20(s32), %bb.3

  bb.3:
    %18:gprregbank(s32) = G_ICMP intpred(eq), %0(s32), %2
    %8:gprregbank(s32) = G_SELECT %18(s32), %6, %9
    %16:gprregbank(s32) = G_ICMP intpred(ne), %0(s32), %2
    %11:gprregbank(s32) = G_SELECT %16(s32), %9, %6
    PseudoRET implicit $lr, implicit %8, implicit %11
...
