# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: ashr_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: ashr_s32
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r7
    ; CHECK-NEXT: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[MOV_U20_]], [[COPY1]]
    ; CHECK-NEXT: [[ASHL:%[0-9]+]]:gpr = ASHL [[COPY]], [[SUB]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ASHL]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ASHR %0, %1
    PseudoRET implicit $lr, implicit %2
...

# FIXME: instead of inverting the sign bit of the constant, the negated constant should be materialized
# in the first place
---
name: ashr_const
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: ashr_const
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 16
    ; CHECK-NEXT: [[MOV_U20_1:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[MOV_U20_1]], [[MOV_U20_]]
    ; CHECK-NEXT: [[ASHL:%[0-9]+]]:gpr = ASHL [[COPY]], [[SUB]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ASHL]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 16
    %2:gprregbank(s32) = G_ASHR %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: ashr_const_negative
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: ashr_const_negative
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[MOV_S12_:%[0-9]+]]:gpr = MOV_S12 -16
    ; CHECK-NEXT: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[MOV_U20_]], [[MOV_S12_]]
    ; CHECK-NEXT: [[ASHL:%[0-9]+]]:gpr = ASHL [[COPY]], [[SUB]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ASHL]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 -16
    %2:gprregbank(s32) = G_ASHR %0, %1
    PseudoRET implicit $lr, implicit %2
...
