# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1 %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s

---
name:            test_jumptable
legalized:       true
regBankSelected: true
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.1' ]
body:             |
  ; AIE1-LABEL: name: test_jumptable
  ; AIE1: bb.0:
  ; AIE1-NEXT:   successors: %bb.1(0x80000000)
  ; AIE1-NEXT: {{  $}}
  ; AIE1-NEXT:   [[MOV_U20_:%[0-9]+]]:gprptrmod_and_ptr = MOV_U20 %jump-table.0
  ; AIE1-NEXT:   $p0 = COPY [[MOV_U20_]]
  ; AIE1-NEXT: {{  $}}
  ; AIE1-NEXT: bb.1:
  ; AIE2-LABEL: name: test_jumptable
  ; AIE2: bb.0:
  ; AIE2-NEXT:   successors: %bb.1(0x80000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[MOVXM_lng_cg:%[0-9]+]]:ep_as_32bit = MOVXM_lng_cg %jump-table.0
  ; AIE2-NEXT:   $p0 = COPY [[MOVXM_lng_cg]]
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.1:
  bb.0:
    successors: %bb.1(0x80000000)

    %0:ptrregbank(p0) = G_JUMP_TABLE %jump-table.0
    $p0 = COPY %0(p0)

  bb.1:

...
