# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s

---
name: select_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7, $r8
    ; AIE2-LABEL: name: select_s32
    ; AIE2: liveins: $r6, $r7, $r8
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r8
    ; AIE2-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2-NEXT: $r0 = COPY [[SELNEZ]]
    ;
    ; AIE2P-LABEL: name: select_s32
    ; AIE2P: liveins: $r6, $r7, $r8
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r8
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2P-NEXT: $r0 = COPY [[SEL_NEZ]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = COPY $r8
    %3:gprregbank(s32) = G_SELECT %0, %1, %2
    $r0 = COPY %3
...

---
name: select_p0
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1, $r6
    ; AIE2-LABEL: name: select_p0
    ; AIE2: liveins: $p0, $p1, $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p1
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; AIE2-NEXT: [[COPY4:%[0-9]+]]:er = COPY [[COPY2]]
    ; AIE2-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY3]], [[COPY4]], [[COPY]]
    ; AIE2-NEXT: $p0 = COPY [[SELNEZ]]
    ;
    ; AIE2P-LABEL: name: select_p0
    ; AIE2P: liveins: $p0, $p1, $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p1
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:er = COPY [[COPY2]]
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY3]], [[COPY4]], [[COPY]]
    ; AIE2P-NEXT: $p0 = COPY [[SEL_NEZ]]
    %0:gprregbank(s32) = COPY $r6
    %1:ptrregbank(p0) = COPY $p0
    %2:ptrregbank(p0) = COPY $p1
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(p0) = COPY %2
    %5:gprregbank(p0) = G_SELECT %0, %3, %4
    $p0 = COPY %5
...

---
name: select_v512
legalized: true
regBankSelected: true
body: |
  bb.1.entry:
    liveins: $r0, $x2, $x4
    ; AIE2-LABEL: name: select_v512
    ; AIE2: liveins: $r0, $x2, $x4
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2-NEXT: [[ADD_add_r_ri:%[0-9]+]]:ers8 = ADD_add_r_ri [[COPY]], -1, implicit-def dead $srcarry
    ; AIE2-NEXT: [[VSEL_32_:%[0-9]+]]:vec512 = VSEL_32 [[COPY1]], [[COPY2]], [[ADD_add_r_ri]]
    ; AIE2-NEXT: $x0 = COPY [[VSEL_32_]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-LABEL: name: select_v512
    ; AIE2P: liveins: $r0, $x2, $x4
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x4
    ; AIE2P-NEXT: [[ADD_add_r_ri:%[0-9]+]]:ers16 = ADD_add_r_ri [[COPY]], -1, implicit-def dead $srcarry
    ; AIE2P-NEXT: [[VSEL_32_:%[0-9]+]]:vec512 = VSEL_32 [[COPY1]], [[COPY2]], [[ADD_add_r_ri]]
    ; AIE2P-NEXT: $x0 = COPY [[VSEL_32_]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $x0
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %2:vregbank(<16 x s32>) = COPY $x2
    %3:vregbank(<16 x s32>) = COPY $x4
    %0:vregbank(<16 x s32>) = G_SELECT %5:gprregbank(s32), %2:vregbank, %3:vregbank
    $x0 = COPY %0:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
