# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck %s --check-prefixes=CHECK,AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck %s --check-prefixes=CHECK,AIE2PS

---
name: post-inc-vector-load-w
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: post-inc-vector-load-w
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_pseudo:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_pseudo1:%[0-9]+]]:ep = VLD_w_pstm_nrm_pseudo [[COPY]], [[COPY2]] :: (load (<16 x s16>))
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_imm_pseudo:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_imm_pseudo1:%[0-9]+]]:ep = VLD_w_pstm_nrm_imm_pseudo [[VLD_w_pstm_nrm_pseudo1]], 224 :: (load (<16 x s16>))
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_imm_pseudo2:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_imm_pseudo3:%[0-9]+]]:ep = VLD_w_pstm_nrm_imm_pseudo [[VLD_w_pstm_nrm_imm_pseudo1]], -256 :: (load (<16 x s16>))
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_imm_pseudo4:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_imm_pseudo5:%[0-9]+]]:ep = VLD_w_pstm_nrm_imm_pseudo [[VLD_w_pstm_nrm_imm_pseudo3]], 0 :: (load (<16 x s16>))
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_pseudo2:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_pseudo3:%[0-9]+]]:ep = VLD_w_pstm_nrm_pseudo [[VLD_w_pstm_nrm_imm_pseudo5]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s16>))
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_pseudo4:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_pseudo5:%[0-9]+]]:ep = VLD_w_pstm_nrm_pseudo [[VLD_w_pstm_nrm_pseudo3]], [[MOV_PD_imm11_pseudo1]] :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_w_pstm_nrm_pseudo4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 224
    %9:modregbank(s20) = G_CONSTANT i20 -256
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 16
    %12:modregbank(s20) = G_CONSTANT i20 256
    %13:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %14:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %15:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %16:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %17:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %18:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    PseudoRET implicit $lr, implicit %18
...

---
name: post-inc-vector-store-w
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $wl0
    ; AIE2P-LABEL: name: post-inc-vector-store-w
    ; AIE2P: liveins: $p0, $r0, $r1, $wl0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2P-NEXT: [[VST_dmw_sts_w_pstm_nrm:%[0-9]+]]:ep = VST_dmw_sts_w_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]] :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[VST_dmw_sts_w_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmw_sts_w_pstm_nrm_imm [[COPY3]], [[VST_dmw_sts_w_pstm_nrm]], 224 :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[VST_dmw_sts_w_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmw_sts_w_pstm_nrm_imm [[COPY3]], [[VST_dmw_sts_w_pstm_nrm_imm]], -256 :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[VST_dmw_sts_w_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmw_sts_w_pstm_nrm_imm [[COPY3]], [[VST_dmw_sts_w_pstm_nrm_imm1]], 0 :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[VST_dmw_sts_w_pstm_nrm1:%[0-9]+]]:ep = VST_dmw_sts_w_pstm_nrm [[COPY3]], [[VST_dmw_sts_w_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[VST_dmw_sts_w_pstm_nrm2:%[0-9]+]]:ep = VST_dmw_sts_w_pstm_nrm [[COPY3]], [[VST_dmw_sts_w_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<8 x s32>))
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VST_dmw_sts_w_pstm_nrm2]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-store-w
    ; AIE2PS: liveins: $p0, $r0, $r1, $wl0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: [[VST_dmw_sts_w_st_pstm_nrm:%[0-9]+]]:ep = VST_dmw_sts_w_st_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]] :: (store (<8 x s32>))
    ; AIE2PS-NEXT: [[VST_dmw_sts_w_st_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmw_sts_w_st_pstm_nrm_imm [[COPY3]], [[VST_dmw_sts_w_st_pstm_nrm]], 224 :: (store (<8 x s32>))
    ; AIE2PS-NEXT: [[VST_dmw_sts_w_st_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmw_sts_w_st_pstm_nrm_imm [[COPY3]], [[VST_dmw_sts_w_st_pstm_nrm_imm]], -256 :: (store (<8 x s32>))
    ; AIE2PS-NEXT: [[VST_dmw_sts_w_st_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmw_sts_w_st_pstm_nrm_imm [[COPY3]], [[VST_dmw_sts_w_st_pstm_nrm_imm1]], 0 :: (store (<8 x s32>))
    ; AIE2PS-NEXT: [[VST_dmw_sts_w_st_pstm_nrm1:%[0-9]+]]:ep = VST_dmw_sts_w_st_pstm_nrm [[COPY3]], [[VST_dmw_sts_w_st_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    ; AIE2PS-NEXT: [[VST_dmw_sts_w_st_pstm_nrm2:%[0-9]+]]:ep = VST_dmw_sts_w_st_pstm_nrm [[COPY3]], [[VST_dmw_sts_w_st_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<8 x s32>))
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VST_dmw_sts_w_st_pstm_nrm2]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 224
    %9:modregbank(s20) = G_CONSTANT i20 -256
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 16
    %12:modregbank(s20) = G_CONSTANT i20 256
    %13:vregbank(<8 x s32>) = COPY $wl0
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<8 x s32>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %19, %8 :: (store (<8 x s32>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %20, %9 :: (store (<8 x s32>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %21, %10 :: (store (<8 x s32>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %22, %11 :: (store (<8 x s32>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %23, %12 :: (store (<8 x s32>))
    PseudoRET implicit $lr, implicit %24
...


---
name: post-inc-vector-load-w-512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: post-inc-vector-load-w-512
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_pseudo:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_pseudo1:%[0-9]+]]:ep = VLD_x_pstm_nrm_pseudo [[COPY]], [[COPY2]] :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_imm_pseudo:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_imm_pseudo1:%[0-9]+]]:ep = VLD_x_pstm_nrm_imm_pseudo [[VLD_x_pstm_nrm_pseudo1]], 448 :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_imm_pseudo2:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_imm_pseudo3:%[0-9]+]]:ep = VLD_x_pstm_nrm_imm_pseudo [[VLD_x_pstm_nrm_imm_pseudo1]], -512 :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_imm_pseudo4:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_imm_pseudo5:%[0-9]+]]:ep = VLD_x_pstm_nrm_imm_pseudo [[VLD_x_pstm_nrm_imm_pseudo3]], 0 :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_pseudo2:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_pseudo3:%[0-9]+]]:ep = VLD_x_pstm_nrm_pseudo [[VLD_x_pstm_nrm_imm_pseudo5]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_pseudo4:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_pseudo5:%[0-9]+]]:ep = VLD_x_pstm_nrm_pseudo [[VLD_x_pstm_nrm_pseudo3]], [[MOV_PD_imm11_pseudo1]] :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_x_pstm_nrm_pseudo4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>) from stack - 64)
    %14:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>) from stack - 64)
    %15:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>) from stack - 64)
    %16:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>) from stack - 64)
    %17:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>) from stack - 64)
    %18:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>) from stack - 64)
    PseudoRET implicit $lr, implicit %18
...

---
name: post-inc-vector-load-bm-512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; AIE2P-LABEL: name: post-inc-vector-load-bm-512
    ; AIE2P: liveins: $p0, $r0, $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[COPY]], [[COPY2]] :: (load (<8 x s64>) from stack - 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm1]], 448 :: (load (<8 x s64>) from stack - 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm1]], -512 :: (load (<8 x s64>) from stack - 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm3]], 0 :: (load (<8 x s64>) from stack - 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[VLDA_dmx_lda_bm_pstm_nrm_imm5]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>) from stack - 64)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[VLDA_dmx_lda_bm_pstm_nrm3]], [[MOV_PD_imm11_pseudo1]] :: (load (<8 x s64>) from stack - 64)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VLDA_dmx_lda_bm_pstm_nrm4]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-load-bm-512
    ; AIE2PS: liveins: $p0, $r0, $r1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[COPY]], [[COPY2]] :: (load (<8 x s64>) from stack - 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm1]], 448 :: (load (<8 x s64>) from stack - 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1]], -512 :: (load (<8 x s64>) from stack - 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3]], 0 :: (load (<8 x s64>) from stack - 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>) from stack - 64)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[VLDA_dmx_lda_bm_ld_pstm_nrm3]], [[MOV_PD_imm11_pseudo1]] :: (load (<8 x s64>) from stack - 64)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VLDA_dmx_lda_bm_ld_pstm_nrm4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:accregbank(<8 x s64>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<8 x s64>) from stack - 64)
    %14:accregbank(<8 x s64>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<8 x s64>) from stack - 64)
    %15:accregbank(<8 x s64>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<8 x s64>) from stack - 64)
    %16:accregbank(<8 x s64>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<8 x s64>) from stack - 64)
    %17:accregbank(<8 x s64>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<8 x s64>) from stack - 64)
    %18:accregbank(<8 x s64>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<8 x s64>) from stack - 64)
    PseudoRET implicit $lr, implicit %18
...

---
name: post-inc-vector-store-w-512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $x0
    ; AIE2P-LABEL: name: post-inc-vector-store-w-512
    ; AIE2P: liveins: $p0, $r0, $r1, $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_x_pstm_nrm]], 448 :: (store (<16 x s32>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_x_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_x_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm [[COPY3]], [[VST_dmx_sts_x_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm [[COPY3]], [[VST_dmx_sts_x_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack - 64)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_x_pstm_nrm2]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-store-w-512
    ; AIE2PS: liveins: $p0, $r0, $r1, $x0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_x_st_pstm_nrm]], 448 :: (store (<16 x s32>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_x_st_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_x_st_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm [[COPY3]], [[VST_dmx_sts_x_st_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm [[COPY3]], [[VST_dmx_sts_x_st_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack - 64)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_x_st_pstm_nrm2]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:vregbank(<16 x s32>) = COPY $x0
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<16 x s32>) into stack - 64)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %19, %8 :: (store (<16 x s32>) into stack - 64)
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %20, %9 :: (store (<16 x s32>) into stack - 64)
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %21, %10 :: (store (<16 x s32>) into stack - 64)
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %22, %11 :: (store (<16 x s32>) into stack - 64)
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %23, %12 :: (store (<16 x s32>) into stack - 64)
    PseudoRET implicit $lr, implicit %24
...

---
name: post-inc-vector-store-bm-512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; AIE2P-LABEL: name: post-inc-vector-store-bm-512
    ; AIE2P: liveins: $p0, $r0, $r1, $bmll0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]] :: (store (<8 x s64>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_bm_pstm_nrm]], 448 :: (store (<8 x s64>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_bm_pstm_nrm_imm]], -512 :: (store (<8 x s64>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_bm_pstm_nrm_imm1]], 0 :: (store (<8 x s64>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY3]], [[VST_dmx_sts_bm_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>) into stack - 64)
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY3]], [[VST_dmx_sts_bm_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<8 x s64>) into stack - 64)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_bm_pstm_nrm2]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-store-bm-512
    ; AIE2PS: liveins: $p0, $r0, $r1, $bmll0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY $bmll0
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]] :: (store (<8 x s64>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_bm_st_pstm_nrm]], 448 :: (store (<8 x s64>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_bm_st_pstm_nrm_imm]], -512 :: (store (<8 x s64>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY3]], [[VST_dmx_sts_bm_st_pstm_nrm_imm1]], 0 :: (store (<8 x s64>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY3]], [[VST_dmx_sts_bm_st_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>) into stack - 64)
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY3]], [[VST_dmx_sts_bm_st_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<8 x s64>) into stack - 64)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_bm_st_pstm_nrm2]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:accregbank(<8 x s64>) = COPY $bmll0
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<8 x s64>) into stack - 64)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %19, %8 :: (store (<8 x s64>) into stack - 64)
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %20, %9 :: (store (<8 x s64>) into stack - 64)
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %21, %10 :: (store (<8 x s64>) into stack - 64)
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %22, %11 :: (store (<8 x s64>) into stack - 64)
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %23, %12 :: (store (<8 x s64>) into stack - 64)
    PseudoRET implicit $lr, implicit %24
...

---
name: post-inc-vector-load-vreg-1024
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: post-inc-vector-load-vreg-1024
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_pseudo:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_pseudo1:%[0-9]+]]:ep = VLD_x_pstm_nrm_pseudo [[COPY]], [[COPY2]] :: (load (<16 x s32>) from stack, align 128)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_pstm_nrm_pseudo]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[VLD_x_pstm_nrm_pseudo1]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_imm_pseudo:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_imm_pseudo1:%[0-9]+]]:ep = VLD_x_pstm_nrm_imm_pseudo [[VLD_x_pstm_nrm_pseudo1]], 448 :: (load (<16 x s32>) from stack, align 128)
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_pstm_nrm_imm_pseudo]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo2:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[VLD_x_pstm_nrm_imm_pseudo1]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_imm_pseudo2:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_imm_pseudo3:%[0-9]+]]:ep = VLD_x_pstm_nrm_imm_pseudo [[VLD_x_pstm_nrm_imm_pseudo1]], -512 :: (load (<16 x s32>) from stack, align 128)
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_pstm_nrm_imm_pseudo2]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo2]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo3:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[VLD_x_pstm_nrm_imm_pseudo3]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_imm_pseudo4:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_imm_pseudo5:%[0-9]+]]:ep = VLD_x_pstm_nrm_imm_pseudo [[VLD_x_pstm_nrm_imm_pseudo3]], 0 :: (load (<16 x s32>) from stack, align 128)
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_pstm_nrm_imm_pseudo4]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo3]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo4:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[VLD_x_pstm_nrm_imm_pseudo5]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_pseudo2:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_pseudo3:%[0-9]+]]:ep = VLD_x_pstm_nrm_pseudo [[VLD_x_pstm_nrm_imm_pseudo5]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>) from stack, align 128)
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_pstm_nrm_pseudo2]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo4]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo5:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[VLD_x_pstm_nrm_pseudo3]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; CHECK-NEXT: [[VLD_x_pstm_nrm_pseudo4:%[0-9]+]]:vec512, [[VLD_x_pstm_nrm_pseudo5:%[0-9]+]]:ep = VLD_x_pstm_nrm_pseudo [[VLD_x_pstm_nrm_pseudo3]], [[MOV_PD_imm11_pseudo1]] :: (load (<16 x s32>) from stack, align 128)
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_pstm_nrm_pseudo4]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo5]], %subreg.sub_512_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE5]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:vregbank(<32 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s32>) from stack - 64)
    %14:vregbank(<32 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s32>) from stack - 64)
    %15:vregbank(<32 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s32>) from stack - 64)
    %16:vregbank(<32 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s32>) from stack - 64)
    %17:vregbank(<32 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s32>) from stack - 64)
    %18:vregbank(<32 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s32>) from stack - 64)
    PseudoRET implicit $lr, implicit %18
...

---
name: post-inc-vector-store-vreg-1024
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $y0
    ; AIE2P-LABEL: name: post-inc-vector-store-vreg-1024
    ; AIE2P: liveins: $p0, $r0, $r1, $y0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm [[COPY5]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY6]], [[VST_dmx_sts_x_pstm_nrm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY7:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm_imm [[COPY7]], [[VST_dmx_sts_x_pstm_nrm]], 448 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY8:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY8]], [[VST_dmx_sts_x_pstm_nrm_imm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY9:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm_imm [[COPY9]], [[VST_dmx_sts_x_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY10:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY10]], [[VST_dmx_sts_x_pstm_nrm_imm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY11:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm_imm [[COPY11]], [[VST_dmx_sts_x_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY12:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY12]], [[VST_dmx_sts_x_pstm_nrm_imm2]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY13:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm [[COPY13]], [[VST_dmx_sts_x_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY14:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2P-NEXT: VST_dmx_sts_x_idx_imm [[COPY14]], [[VST_dmx_sts_x_pstm_nrm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY15:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_x_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_x_pstm_nrm [[COPY15]], [[VST_dmx_sts_x_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_x_pstm_nrm2]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-store-vreg-1024
    ; AIE2PS: liveins: $p0, $r0, $r1, $y0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY $y0
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm [[COPY5]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY6]], [[VST_dmx_sts_x_st_pstm_nrm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY7:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm_imm [[COPY7]], [[VST_dmx_sts_x_st_pstm_nrm]], 448 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY8:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY8]], [[VST_dmx_sts_x_st_pstm_nrm_imm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY9:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm_imm [[COPY9]], [[VST_dmx_sts_x_st_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY10:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY10]], [[VST_dmx_sts_x_st_pstm_nrm_imm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY11:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm_imm [[COPY11]], [[VST_dmx_sts_x_st_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY12:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY12]], [[VST_dmx_sts_x_st_pstm_nrm_imm2]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY13:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm [[COPY13]], [[VST_dmx_sts_x_st_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY14:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; AIE2PS-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY14]], [[VST_dmx_sts_x_st_pstm_nrm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY15:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_x_st_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_x_st_pstm_nrm [[COPY15]], [[VST_dmx_sts_x_st_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_x_st_pstm_nrm2]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:vregbank(<32 x s32>) = COPY $y0
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<32 x s32>) into stack - 64)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %19, %8 :: (store (<32 x s32>) into stack - 64)
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %20, %9 :: (store (<32 x s32>) into stack - 64)
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %21, %10 :: (store (<32 x s32>) into stack - 64)
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %22, %11 :: (store (<32 x s32>) into stack - 64)
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %23, %12 :: (store (<32 x s32>) into stack - 64)
    PseudoRET implicit $lr, implicit %24
...

---
name: post-inc-vector-load-acc-1024
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; AIE2P-LABEL: name: post-inc-vector-load-acc-1024
    ; AIE2P: liveins: $p0, $r0, $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[COPY]], [[COPY2]] :: (load (<16 x s32>) from stack, align 128)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm1]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm1]], 448 :: (load (<16 x s32>) from stack, align 128)
    ; AIE2P-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm1]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm1]], -512 :: (load (<16 x s32>) from stack, align 128)
    ; AIE2P-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm_imm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm3]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm3]], 0 :: (load (<16 x s32>) from stack, align 128)
    ; AIE2P-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm_imm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm4:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm5]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[VLDA_dmx_lda_bm_pstm_nrm_imm5]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>) from stack, align 128)
    ; AIE2P-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm4]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm5:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm3]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[VLDA_dmx_lda_bm_pstm_nrm3]], [[MOV_PD_imm11_pseudo1]] :: (load (<16 x s32>) from stack, align 128)
    ; AIE2P-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm5]], %subreg.sub_512_acc_hi
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE5]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-load-acc-1024
    ; AIE2PS: liveins: $p0, $r0, $r1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[COPY]], [[COPY2]] :: (load (<16 x s32>) from stack, align 128)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm1]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm1]], 448 :: (load (<16 x s32>) from stack, align 128)
    ; AIE2PS-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1]], -512 :: (load (<16 x s32>) from stack, align 128)
    ; AIE2PS-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3]], 0 :: (load (<16 x s32>) from stack, align 128)
    ; AIE2PS-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm4:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>) from stack, align 128)
    ; AIE2PS-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm4]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm5:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm3]], 64 :: (load (<16 x s32>) from stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[VLDA_dmx_lda_bm_ld_pstm_nrm3]], [[MOV_PD_imm11_pseudo1]] :: (load (<16 x s32>) from stack, align 128)
    ; AIE2PS-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:acc1024 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm5]], %subreg.sub_512_acc_hi
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE5]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:accregbank(<32 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s32>) from stack - 64)
    %14:accregbank(<32 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s32>) from stack - 64)
    %15:accregbank(<32 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s32>) from stack - 64)
    %16:accregbank(<32 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s32>) from stack - 64)
    %17:accregbank(<32 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s32>) from stack - 64)
    %18:accregbank(<32 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s32>) from stack - 64)
    PseudoRET implicit $lr, implicit %18
...

---
name: post-inc-vector-store-acc-1024
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $cml0
    ; AIE2P-LABEL: name: post-inc-vector-store-acc-1024
    ; AIE2P: liveins: $p0, $r0, $r1, $cml0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY5]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY6:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY6]], [[VST_dmx_sts_bm_pstm_nrm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY7:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY7]], [[VST_dmx_sts_bm_pstm_nrm]], 448 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY8]], [[VST_dmx_sts_bm_pstm_nrm_imm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY9]], [[VST_dmx_sts_bm_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY10:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY10]], [[VST_dmx_sts_bm_pstm_nrm_imm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY11:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY11]], [[VST_dmx_sts_bm_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY12]], [[VST_dmx_sts_bm_pstm_nrm_imm2]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY13]], [[VST_dmx_sts_bm_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: [[COPY14:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY14]], [[VST_dmx_sts_bm_pstm_nrm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2P-NEXT: [[COPY15:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY15]], [[VST_dmx_sts_bm_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_bm_pstm_nrm2]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-store-acc-1024
    ; AIE2PS: liveins: $p0, $r0, $r1, $cml0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc1024 = COPY $cml0
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[COPY]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY5]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY6:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY6]], [[VST_dmx_sts_bm_st_pstm_nrm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY7:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY7]], [[VST_dmx_sts_bm_st_pstm_nrm]], 448 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY8]], [[VST_dmx_sts_bm_st_pstm_nrm_imm]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY9]], [[VST_dmx_sts_bm_st_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY10:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY10]], [[VST_dmx_sts_bm_st_pstm_nrm_imm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY11:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY11]], [[VST_dmx_sts_bm_st_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY12]], [[VST_dmx_sts_bm_st_pstm_nrm_imm2]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY13]], [[VST_dmx_sts_bm_st_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: [[COPY14:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY14]], [[VST_dmx_sts_bm_st_pstm_nrm1]], 64 :: (store (<16 x s32>) into stack - 64, basealign 128)
    ; AIE2PS-NEXT: [[COPY15:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY15]], [[VST_dmx_sts_bm_st_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack, align 128)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_bm_st_pstm_nrm2]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:accregbank(<32 x s32>) = COPY $cml0
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<32 x s32>) into stack - 64)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %19, %8 :: (store (<32 x s32>) into stack - 64)
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %20, %9 :: (store (<32 x s32>) into stack - 64)
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %21, %10 :: (store (<32 x s32>) into stack - 64)
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %22, %11 :: (store (<32 x s32>) into stack - 64)
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %23, %12 :: (store (<32 x s32>) into stack - 64)
    PseudoRET implicit $lr, implicit %24
...
---
name: post-inc-vector-load-acc-2048
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; AIE2P-LABEL: name: post-inc-vector-load-acc-2048
    ; AIE2P: liveins: $p0, $r0, $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[COPY]], [[COPY2]] :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm2]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm1]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm1]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm4:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm1]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm5:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm1]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm1]], 448 :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm5]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm4]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm6:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm1]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm7:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm1]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm8:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm1]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm1]], -512 :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm_imm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm8]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm7]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm6]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm9:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm3]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm10:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm3]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm11:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm3]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm_imm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm_imm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm3]], 0 :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm_imm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm11]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm10]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm9]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm12:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm5]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm13:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm5]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm14:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm_imm5]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[VLDA_dmx_lda_bm_pstm_nrm_imm5]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm14]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm13]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm12]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm15:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm3]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm16:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm3]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_idx_imm17:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[VLDA_dmx_lda_bm_pstm_nrm3]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2P-NEXT: [[VLDA_dmx_lda_bm_pstm_nrm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_pstm_nrm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_pstm_nrm [[VLDA_dmx_lda_bm_pstm_nrm3]], [[MOV_PD_imm11_pseudo1]] :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_pstm_nrm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm17]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_idx_imm16]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_idx_imm15]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE5]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-load-acc-2048
    ; AIE2PS: liveins: $p0, $r0, $r1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm1:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm2:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[COPY]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[COPY]], [[COPY2]] :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm2]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm1]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm3:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm1]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm4:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm1]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm5:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm1]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm1]], 448 :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm5]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm4]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm3]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm6:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm7:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm8:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm1]], -512 :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm8]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm7]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm6]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm9:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm10:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm11:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm3]], 0 :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm11]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm10]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm9]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm12:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm13:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm14:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm2:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm3:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[VLDA_dmx_lda_bm_ld_pstm_nrm_imm5]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm2]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm14]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm13]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm12]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm15:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm3]], 192 :: (load (<16 x s32>) from stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm16:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm3]], 128 :: (load (<16 x s32>) from stack, align 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_idx_imm17:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_ld_idx_imm [[VLDA_dmx_lda_bm_ld_pstm_nrm3]], 64 :: (load (<16 x s32>) from stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[VLDA_dmx_lda_bm_ld_pstm_nrm4:%[0-9]+]]:acc512, [[VLDA_dmx_lda_bm_ld_pstm_nrm5:%[0-9]+]]:ep = VLDA_dmx_lda_bm_ld_pstm_nrm [[VLDA_dmx_lda_bm_ld_pstm_nrm3]], [[MOV_PD_imm11_pseudo1]] :: (load (<16 x s32>) from stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:acc2048 = REG_SEQUENCE [[VLDA_dmx_lda_bm_ld_pstm_nrm4]], %subreg.sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm17]], %subreg.sub_512_acc_hi, [[VLDA_dmx_lda_bm_ld_idx_imm16]], %subreg.sub_1024_acc_hi_then_sub_512_acc_lo, [[VLDA_dmx_lda_bm_ld_idx_imm15]], %subreg.sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE5]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:accregbank(<64 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<64 x s32>) from stack - 64)
    %14:accregbank(<64 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<64 x s32>) from stack - 64)
    %15:accregbank(<64 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<64 x s32>) from stack - 64)
    %16:accregbank(<64 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<64 x s32>) from stack - 64)
    %17:accregbank(<64 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<64 x s32>) from stack - 64)
    %18:accregbank(<64 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<64 x s32>) from stack - 64)
    PseudoRET implicit $lr, implicit %18
...

---
name: post-inc-vector-store-acc-2048
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $dm0
    ; AIE2P-LABEL: name: post-inc-vector-store-acc-2048
    ; AIE2P: liveins: $p0, $r0, $r1, $dm0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2P-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY4]], [[COPY]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY5]], [[COPY]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2P-NEXT: [[COPY6:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY6]], [[COPY]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2P-NEXT: [[COPY7:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY7]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY8]], [[VST_dmx_sts_bm_pstm_nrm]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2P-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY9]], [[VST_dmx_sts_bm_pstm_nrm]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2P-NEXT: [[COPY10:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY10]], [[VST_dmx_sts_bm_pstm_nrm]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2P-NEXT: [[COPY11:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY11]], [[VST_dmx_sts_bm_pstm_nrm]], 448 :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY12]], [[VST_dmx_sts_bm_pstm_nrm_imm]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2P-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY13]], [[VST_dmx_sts_bm_pstm_nrm_imm]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2P-NEXT: [[COPY14:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY14]], [[VST_dmx_sts_bm_pstm_nrm_imm]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2P-NEXT: [[COPY15:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY15]], [[VST_dmx_sts_bm_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[COPY16:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY16]], [[VST_dmx_sts_bm_pstm_nrm_imm1]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2P-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY17]], [[VST_dmx_sts_bm_pstm_nrm_imm1]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2P-NEXT: [[COPY18:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY18]], [[VST_dmx_sts_bm_pstm_nrm_imm1]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2P-NEXT: [[COPY19:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm_imm [[COPY19]], [[VST_dmx_sts_bm_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[COPY20:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY20]], [[VST_dmx_sts_bm_pstm_nrm_imm2]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2P-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY21]], [[VST_dmx_sts_bm_pstm_nrm_imm2]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2P-NEXT: [[COPY22:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY22]], [[VST_dmx_sts_bm_pstm_nrm_imm2]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2P-NEXT: [[COPY23:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY23]], [[VST_dmx_sts_bm_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: [[COPY24:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY24]], [[VST_dmx_sts_bm_pstm_nrm1]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2P-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY25]], [[VST_dmx_sts_bm_pstm_nrm1]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2P-NEXT: [[COPY26:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2P-NEXT: VST_dmx_sts_bm_idx_imm [[COPY26]], [[VST_dmx_sts_bm_pstm_nrm1]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2P-NEXT: [[COPY27:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2P-NEXT: [[VST_dmx_sts_bm_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_bm_pstm_nrm [[COPY27]], [[VST_dmx_sts_bm_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_bm_pstm_nrm2]]
    ;
    ; AIE2PS-LABEL: name: post-inc-vector-store-acc-2048
    ; AIE2PS: liveins: $p0, $r0, $r1, $dm0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; AIE2PS-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm0
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY4]], [[COPY]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY5]], [[COPY]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2PS-NEXT: [[COPY6:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY6]], [[COPY]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY7:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY7]], [[COPY]], [[COPY2]] :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY8]], [[VST_dmx_sts_bm_st_pstm_nrm]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY9]], [[VST_dmx_sts_bm_st_pstm_nrm]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2PS-NEXT: [[COPY10:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY10]], [[VST_dmx_sts_bm_st_pstm_nrm]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY11:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY11]], [[VST_dmx_sts_bm_st_pstm_nrm]], 448 :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY12]], [[VST_dmx_sts_bm_st_pstm_nrm_imm]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY13]], [[VST_dmx_sts_bm_st_pstm_nrm_imm]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2PS-NEXT: [[COPY14:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY14]], [[VST_dmx_sts_bm_st_pstm_nrm_imm]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY15:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm1:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY15]], [[VST_dmx_sts_bm_st_pstm_nrm_imm]], -512 :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[COPY16:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY16]], [[VST_dmx_sts_bm_st_pstm_nrm_imm1]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY17]], [[VST_dmx_sts_bm_st_pstm_nrm_imm1]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2PS-NEXT: [[COPY18:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY18]], [[VST_dmx_sts_bm_st_pstm_nrm_imm1]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY19:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm2:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY19]], [[VST_dmx_sts_bm_st_pstm_nrm_imm1]], 0 :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[COPY20:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY20]], [[VST_dmx_sts_bm_st_pstm_nrm_imm2]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY21]], [[VST_dmx_sts_bm_st_pstm_nrm_imm2]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2PS-NEXT: [[COPY22:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY22]], [[VST_dmx_sts_bm_st_pstm_nrm_imm2]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY23:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm1:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY23]], [[VST_dmx_sts_bm_st_pstm_nrm_imm2]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: [[COPY24:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY24]], [[VST_dmx_sts_bm_st_pstm_nrm1]], 192 :: (store (<16 x s32>) into stack - 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_1024_acc_hi_then_sub_512_acc_lo
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY25]], [[VST_dmx_sts_bm_st_pstm_nrm1]], 128 :: (store (<16 x s32>) into stack, align 256)
    ; AIE2PS-NEXT: [[COPY26:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_hi
    ; AIE2PS-NEXT: VST_dmx_sts_bm_st_idx_imm [[COPY26]], [[VST_dmx_sts_bm_st_pstm_nrm1]], 64 :: (store (<16 x s32>) into stack + 64, basealign 256)
    ; AIE2PS-NEXT: [[COPY27:%[0-9]+]]:acc512 = COPY [[COPY3]].sub_512_acc_lo
    ; AIE2PS-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm2:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY27]], [[VST_dmx_sts_bm_st_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]] :: (store (<16 x s32>) into stack + 128, align 128, basealign 256)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[VST_dmx_sts_bm_st_pstm_nrm2]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 448
    %9:modregbank(s20) = G_CONSTANT i20 -512
    %10:modregbank(s20) = G_CONSTANT i20 0
    %11:modregbank(s20) = G_CONSTANT i20 32
    %12:modregbank(s20) = G_CONSTANT i20 512
    %13:accregbank(<64 x s32>) = COPY $dm0
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<64 x s32>) into stack - 64)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %19, %8 :: (store (<64 x s32>) into stack - 64)
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %20, %9 :: (store (<64 x s32>) into stack - 64)
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %21, %10 :: (store (<64 x s32>) into stack - 64)
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %22, %11 :: (store (<64 x s32>) into stack - 64)
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %13, %23, %12 :: (store (<64 x s32>) into stack - 64)
    PseudoRET implicit $lr, implicit %24
...
