# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name:            v8s32
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v8s32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec256 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec256 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec256 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $wl0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<8 x s32>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    %val_2:vregbank(<8 x s32>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<8 x s32>) = G_PHI %val_2(<8 x s32>), %bb.1, %val_1(<8 x s32>), %bb.0
    $wl0 = COPY %phi
...

---
name:            v16s16
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v16s16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec256 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec256 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec256 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $wl0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<16 x s16>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<16 x s16>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<16 x s16>) = G_PHI %val_2(<16 x s16>), %bb.1, %val_1(<16 x s16>), %bb.0
    $wl0 = COPY %phi
...

---
name:            v32s8
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v32s8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec256 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec256 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec256 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $wl0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<32 x s8>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<32 x s8>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<32 x s8>) = G_PHI %val_2(<32 x s8>), %bb.1, %val_1(<32 x s8>), %bb.0
    $wl0 = COPY %phi
...
---
name:            v16s32
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v16s32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec512 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $x0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<16 x s32>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<16 x s32>) = G_PHI %val_2(<16 x s32>), %bb.1, %val_1(<16 x s32>), %bb.0
    $x0 = COPY %phi
...

---
name:            v32s16
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v32s16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec512 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $x0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<32 x s16>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<32 x s16>) = G_PHI %val_2(<32 x s16>), %bb.1, %val_1(<32 x s16>), %bb.0
    $x0 = COPY %phi
...

---
name:            v64s8
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v64s8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec512 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec512 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $x0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<64 x s8>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<64 x s8>) = G_PHI %val_2(<64 x s8>), %bb.1, %val_1(<64 x s8>), %bb.0
    $x0 = COPY %phi
...

---
name:            acc512
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: acc512
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:acc512 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:acc512 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:acc512 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $x0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:accregbank(<8 x s64>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:accregbank(<8 x s64>) = G_IMPLICIT_DEF
  bb.2:
    %phi:accregbank(<8 x s64>) = G_PHI %val_2(<8 x s64>), %bb.1, %val_1(<8 x s64>), %bb.0
    $x0 = COPY %phi
...

---
name:            v32s32
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v32s32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec1024 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec1024 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $y2 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<32 x s32>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<32 x s32>) = G_PHI %val_2(<32 x s32>), %bb.1, %val_1(<32 x s32>), %bb.0
    $y2 = COPY %phi
...

---
name:            v64s16
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v64s16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec1024 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec1024 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $y2 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<64 x s16>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<64 x s16>) = G_PHI %val_2(<64 x s16>), %bb.1, %val_1(<64 x s16>), %bb.0
    $y2 = COPY %phi
...

---
name:            v128s8
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v128s8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec1024 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec1024 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $y2 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<128 x s8>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:vregbank(<128 x s8>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<128 x s8>) = G_PHI %val_2(<128 x s8>), %bb.1, %val_1(<128 x s8>), %bb.0
    $y2 = COPY %phi
...

---
name:            acc1024
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: acc1024
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:acc1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:acc1024 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:acc1024 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $y2 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:accregbank(<16 x s64>) = G_IMPLICIT_DEF
  bb.2:
    %phi:accregbank(<16 x s64>) = G_PHI %val_2(<16 x s64>), %bb.1, %val_1(<16 x s64>), %bb.0
    $y2 = COPY %phi
...
