# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s -check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s -check-prefix=AIE2PS

---
name:            sel_char
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: sel_char
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; CHECK-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[SELNEZ]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: sel_char
    ; AIE2P: liveins: $r1, $r2, $r3
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2P-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: sel_char
    ; AIE2PS: liveins: $r1, $r2, $r3
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY $r3
    ; AIE2PS-NEXT: [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2PS-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %4:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %6:gprregbank(s32) = COPY $r2
    %7:gprregbank(s32) = G_ASSERT_SEXT %6:gprregbank, 8
    %8:gprregbank(s32) = COPY $r3
    %9:gprregbank(s32) = G_ASSERT_SEXT %8:gprregbank, 8
    %13:gprregbank(s32) = G_SELECT %5:gprregbank(s32), %7:gprregbank, %9:gprregbank
    $r0 = COPY %13:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            sel_uchar
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: sel_uchar
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; CHECK-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[SELNEZ]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: sel_uchar
    ; AIE2P: liveins: $r1, $r2, $r3
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2P-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: sel_uchar
    ; AIE2PS: liveins: $r1, $r2, $r3
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY $r3
    ; AIE2PS-NEXT: [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2PS-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %4:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %6:gprregbank(s32) = COPY $r2
    %7:gprregbank(s32) = G_ASSERT_ZEXT %6:gprregbank, 8
    %8:gprregbank(s32) = COPY $r3
    %9:gprregbank(s32) = G_ASSERT_ZEXT %8:gprregbank, 8
    %13:gprregbank(s32) = G_SELECT %5:gprregbank(s32), %7:gprregbank, %9:gprregbank
    $r0 = COPY %13:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            sel_short
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: sel_short
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; CHECK-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[SELNEZ]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: sel_short
    ; AIE2P: liveins: $r1, $r2, $r3
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2P-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: sel_short
    ; AIE2PS: liveins: $r1, $r2, $r3
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY $r3
    ; AIE2PS-NEXT: [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2PS-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %4:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %6:gprregbank(s32) = COPY $r2
    %7:gprregbank(s32) = G_ASSERT_SEXT %6:gprregbank, 16
    %8:gprregbank(s32) = COPY $r3
    %9:gprregbank(s32) = G_ASSERT_SEXT %8:gprregbank, 16
    %13:gprregbank(s32) = G_SELECT %5:gprregbank(s32), %7:gprregbank, %9:gprregbank
    $r0 = COPY %13:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            sel_ushort
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: sel_ushort
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; CHECK-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[SELNEZ]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: sel_ushort
    ; AIE2P: liveins: $r1, $r2, $r3
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2P-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: sel_ushort
    ; AIE2PS: liveins: $r1, $r2, $r3
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY $r3
    ; AIE2PS-NEXT: [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2PS-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %4:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %6:gprregbank(s32) = COPY $r2
    %7:gprregbank(s32) = G_ASSERT_ZEXT %6:gprregbank, 16
    %8:gprregbank(s32) = COPY $r3
    %9:gprregbank(s32) = G_ASSERT_ZEXT %8:gprregbank, 16
    %13:gprregbank(s32) = G_SELECT %5:gprregbank(s32), %7:gprregbank, %9:gprregbank
    $r0 = COPY %13:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            sel_int
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1, $r2, $r3
    ; CHECK-LABEL: name: sel_int
    ; CHECK: liveins: $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; CHECK-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[SELNEZ]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: sel_int
    ; AIE2P: liveins: $r1, $r2, $r3
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r3
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2P-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: sel_int
    ; AIE2PS: liveins: $r1, $r2, $r3
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r1
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY $r3
    ; AIE2PS-NEXT: [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; AIE2PS-NEXT: $r0 = COPY [[SEL_NEZ]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %4:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %2:gprregbank(s32) = COPY $r2
    %3:gprregbank(s32) = COPY $r3
    %0:gprregbank(s32) = G_SELECT %5:gprregbank(s32), %2:gprregbank, %3:gprregbank
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            sel_vptr
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p1, $p2, $r0
    ; CHECK-LABEL: name: sel_vptr
    ; CHECK: liveins: $p1, $p2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er27 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY [[COPY2]]
    ; CHECK-NEXT: [[SELNEZ:%[0-9]+]]:er = SELNEZ [[COPY3]], [[COPY4]], [[COPY]]
    ; CHECK-NEXT: $p0 = COPY [[SELNEZ]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $p0
    ;
    ; AIE2P-LABEL: name: sel_vptr
    ; AIE2P: liveins: $p1, $p2, $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p2
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:er = COPY [[COPY2]]
    ; AIE2P-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY3]], [[COPY4]], [[COPY]]
    ; AIE2P-NEXT: $p0 = COPY [[SEL_NEZ]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $p0
    ;
    ; AIE2PS-LABEL: name: sel_vptr
    ; AIE2PS: liveins: $p1, $p2, $r0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p2
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:mlockid_reg = COPY [[COPY1]]
    ; AIE2PS-NEXT: [[COPY4:%[0-9]+]]:mlockid_reg = COPY [[COPY2]]
    ; AIE2PS-NEXT: [[SEL_NEZ:%[0-9]+]]:mlockid_reg = SEL_NEZ [[COPY3]], [[COPY4]], [[COPY]]
    ; AIE2PS-NEXT: $p0 = COPY [[SEL_NEZ]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $p0
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %2:ptrregbank(p0) = COPY $p1
    %3:ptrregbank(p0) = COPY $p2
    %8:gprregbank(p0) = COPY %2:ptrregbank(p0)
    %9:gprregbank(p0) = COPY %3:ptrregbank(p0)
    %0:gprregbank(p0) = G_SELECT %5:gprregbank(s32), %8:gprregbank, %9:gprregbank
    $p0 = COPY %0:gprregbank(p0)
    PseudoRET implicit $lr, implicit $p0
...
