# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1 %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s

---
name: sext_inreg_s32_8
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE1-LABEL: name: sext_inreg_s32_8
    ; AIE1: liveins: $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[SE8_:%[0-9]+]]:gpr = SE8 [[COPY]]
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[SE8_]]
    ;
    ; AIE2-LABEL: name: sext_inreg_s32_8
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[EXTENDs8_:%[0-9]+]]:er = EXTENDs8 [[COPY]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[EXTENDs8_]]
    ;
    ; AIE2P-LABEL: name: sext_inreg_s32_8
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[EXTEND_s8_:%[0-9]+]]:er = EXTEND_s8 [[COPY]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[EXTEND_s8_]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_SEXT_INREG %0, 8
    PseudoRET implicit $lr, implicit %1
...

---
name: sext_inreg_s32_16
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; AIE1-LABEL: name: sext_inreg_s32_16
    ; AIE1: liveins: $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE1-NEXT: [[SE16_:%[0-9]+]]:gpr = SE16 [[COPY]]
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit [[SE16_]]
    ;
    ; AIE2-LABEL: name: sext_inreg_s32_16
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[EXTENDs16_:%[0-9]+]]:er = EXTENDs16 [[COPY]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[EXTENDs16_]]
    ;
    ; AIE2P-LABEL: name: sext_inreg_s32_16
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[EXTEND_s16_:%[0-9]+]]:er = EXTEND_s16 [[COPY]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[EXTEND_s16_]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_SEXT_INREG %0, 16
    PseudoRET implicit $lr, implicit %1
...
