# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS


---
name:            spill_load_256
legalized:       true
regBankSelected: true
stack:
  - { id: 0, name: "", offset: 0, size: 64, alignment: 64 }
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2-LABEL: name: spill_load_256
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[VLDA_dmw_lda_w_ag_spill:%[0-9]+]]:vec256 = VLDA_dmw_lda_w_ag_spill %stack.0, implicit $sp :: (load (<8 x s32>))
    ; AIE2-NEXT: $wl0 = COPY [[VLDA_dmw_lda_w_ag_spill]]
    ;
    ; AIE2P-LABEL: name: spill_load_256
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[VLDA_dmw_lda_w_spill:%[0-9]+]]:vec256 = VLDA_dmw_lda_w_spill %stack.0, implicit $sp :: (load (<8 x s32>))
    ; AIE2P-NEXT: $wl0 = COPY [[VLDA_dmw_lda_w_spill]]
    ;
    ; AIE2PS-LABEL: name: spill_load_256
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[VLDA_W_SPILL:%[0-9]+]]:vec256 = VLDA_W_SPILL %stack.0, implicit $sp :: (load (<8 x s32>))
    ; AIE2PS-NEXT: $wl0 = COPY [[VLDA_W_SPILL]]
    %1:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    %0:vregbank(<8 x s32>) = G_LOAD %1(p0) :: (load (<8 x s32>))
    $wl0 = COPY %0(<8 x s32>)
...

---
name:            spill_store_256
legalized:       true
regBankSelected: true
stack:
  - { id: 0, name: "", offset: 0, size: 64, alignment: 64 }
body:             |
  bb.1.entry:
    liveins: $wl0, $p0
    ; AIE2-LABEL: name: spill_store_256
    ; AIE2: liveins: $wl0, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2-NEXT: VST_dmw_sts_w_ag_spill [[COPY]], %stack.0, implicit $sp :: (store (<8 x s32>))
    ;
    ; AIE2P-LABEL: name: spill_store_256
    ; AIE2P: liveins: $wl0, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2P-NEXT: VST_dmw_sts_w_spill [[COPY]], %stack.0, implicit $sp :: (store (<8 x s32>))
    ;
    ; AIE2PS-LABEL: name: spill_store_256
    ; AIE2PS: liveins: $wl0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; AIE2PS-NEXT: VST_W_SPILL [[COPY]], %stack.0, implicit $sp :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    G_STORE %0(<8 x s32>), %1(p0) :: (store (<8 x s32>))
...

---
name:            spill_load_512
legalized:       true
regBankSelected: true
stack:
  - { id: 0, name: "", offset: 0, size: 64, alignment: 64 }
body:             |
  bb.1.entry:
    liveins: $p0
    ; AIE2-LABEL: name: spill_load_512
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[PseudoFI:%[0-9]+]]:ep = PseudoFI %stack.0, implicit $sp
    ; AIE2-NEXT: [[VLD_idx_imm_3x32_pseudo:%[0-9]+]]:vec256 = VLD_idx_imm_3x32_pseudo [[PseudoFI]], 32 :: (load (<8 x s32>) from unknown-address + 32)
    ; AIE2-NEXT: [[VLD_idx_imm_3x32_pseudo1:%[0-9]+]]:vec256 = VLD_idx_imm_3x32_pseudo [[PseudoFI]], 0 :: (load (<8 x s32>), align 64)
    ; AIE2-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[VLD_idx_imm_3x32_pseudo1]], %subreg.sub_256_lo, [[VLD_idx_imm_3x32_pseudo]], %subreg.sub_256_hi
    ; AIE2-NEXT: $x0 = COPY [[REG_SEQUENCE]]
    ;
    ; AIE2P-LABEL: name: spill_load_512
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[VLDA_dmx_lda_x_spill:%[0-9]+]]:vec512 = VLDA_dmx_lda_x_spill %stack.0, implicit $sp :: (load (<16 x s32>))
    ; AIE2P-NEXT: $x0 = COPY [[VLDA_dmx_lda_x_spill]]
    ;
    ; AIE2PS-LABEL: name: spill_load_512
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[VLDA_X_SPILL:%[0-9]+]]:vec512 = VLDA_X_SPILL %stack.0, implicit $sp :: (load (<16 x s32>))
    ; AIE2PS-NEXT: $x0 = COPY [[VLDA_X_SPILL]]
    %1:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    %0:vregbank(<16 x s32>) = G_LOAD %1(p0) :: (load (<16 x s32>))
    $x0 = COPY %0(<16 x s32>)
...

---
name:            spill_store_512
legalized:       true
regBankSelected: true
stack:
  - { id: 0, name: "", offset: 0, size: 64, alignment: 64 }
body:             |
  bb.1.entry:
    liveins: $x0, $p0
    ; AIE2-LABEL: name: spill_store_512
    ; AIE2: liveins: $x0, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2-NEXT: [[PseudoFI:%[0-9]+]]:ep = PseudoFI %stack.0, implicit $sp
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; AIE2-NEXT: VST_dmw_sts_w_ag_idx_imm [[COPY2]], [[PseudoFI]], 32 :: (store (<8 x s32>) into unknown-address + 32)
    ; AIE2-NEXT: VST_dmw_sts_w_ag_idx_imm [[COPY1]], [[PseudoFI]], 0 :: (store (<8 x s32>), align 64)
    ;
    ; AIE2P-LABEL: name: spill_store_512
    ; AIE2P: liveins: $x0, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: VST_dmx_sts_x_spill [[COPY]], %stack.0, implicit $sp :: (store (<16 x s32>))
    ;
    ; AIE2PS-LABEL: name: spill_store_512
    ; AIE2PS: liveins: $x0, $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2PS-NEXT: VST_X_SPILL [[COPY]], %stack.0, implicit $sp :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    G_STORE %0(<16 x s32>), %1(p0) :: (store (<16 x s32>))
...
