# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefixes=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck --check-prefixes=AIE2P %s

---
name: or_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE-LABEL: name: or_s32
    ; AIE: liveins: $r6, $r7
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r7
    ; AIE-NEXT: [[OR:%[0-9]+]]:gpr = OR [[COPY]], [[COPY1]]
    ; AIE-NEXT: PseudoRET implicit $lr, implicit [[OR]]
    ;
    ; AIE2-LABEL: name: or_s32
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2-NEXT: [[OR:%[0-9]+]]:er = OR [[COPY]], [[COPY1]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[OR]]
    ;
    ; AIE2P-LABEL: name: or_s32
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2P-NEXT: [[OR:%[0-9]+]]:er = OR [[COPY]], [[COPY1]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[OR]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_OR %0, %1
    PseudoRET implicit $lr, implicit %2
...
