# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -start-before=instruction-select -stop-after=machine-cse %s -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -start-before=instruction-select -stop-after=machine-cse %s -o - | FileCheck %s -check-prefix=AIE2PS


---
name:            test_mac
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins:  $r0, $r1, $r2

    ; CHECK-LABEL: name: test_mac
    ; CHECK: liveins: $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: %acc:er = COPY $r2
    ; CHECK-NEXT: [[MAC:%[0-9]+]]:er = MAC %acc, [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MAC]]
    ;
    ; AIE2PS-LABEL: name: test_mac
    ; AIE2PS: liveins: $r0, $r1, $r2
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r1
    ; AIE2PS-NEXT: %acc:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[MAC:%[0-9]+]]:mlockid_reg = MAC %acc, [[COPY]], [[COPY1]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[MAC]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %acc:gprregbank(s32) = COPY $r2
    %3:gprregbank(s32) = G_MUL %0, %1
    %4:gprregbank(s32) = G_ADD %acc, %3

    PseudoRET implicit $lr, implicit %4
...

---
name:            test_mac_commutative_add
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins:  $r0, $r1, $r2

    ; CHECK-LABEL: name: test_mac_commutative_add
    ; CHECK: liveins: $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: %acc:er = COPY $r2
    ; CHECK-NEXT: [[MAC:%[0-9]+]]:er = MAC %acc, [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MAC]]
    ;
    ; AIE2PS-LABEL: name: test_mac_commutative_add
    ; AIE2PS: liveins: $r0, $r1, $r2
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r1
    ; AIE2PS-NEXT: %acc:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[MAC:%[0-9]+]]:mlockid_reg = MAC %acc, [[COPY]], [[COPY1]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[MAC]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %acc:gprregbank(s32) = COPY $r2
    %3:gprregbank(s32) = G_MUL %0, %1
    %4:gprregbank(s32) = G_ADD %3, %acc

    PseudoRET implicit $lr, implicit %4
...

---
name:            test_mac_commutative_mul
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins:  $r0, $r1, $r2

    ; CHECK-LABEL: name: test_mac_commutative_mul
    ; CHECK: liveins: $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: %acc:er = COPY $r2
    ; CHECK-NEXT: [[MAC:%[0-9]+]]:er = MAC %acc, [[COPY1]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MAC]]
    ;
    ; AIE2PS-LABEL: name: test_mac_commutative_mul
    ; AIE2PS: liveins: $r0, $r1, $r2
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r1
    ; AIE2PS-NEXT: %acc:mlockid_reg = COPY $r2
    ; AIE2PS-NEXT: [[MAC:%[0-9]+]]:mlockid_reg = MAC %acc, [[COPY1]], [[COPY]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[MAC]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %acc:gprregbank(s32) = COPY $r2
    %3:gprregbank(s32) = G_MUL %1, %0
    %4:gprregbank(s32) = G_ADD %acc, %3

    PseudoRET implicit $lr, implicit %4
...
