# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

---
name: lshr_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: lshr_s32
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $r7
    ; CHECK-NEXT: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[MOV_U20_]], [[COPY1]]
    ; CHECK-NEXT: [[LSHL:%[0-9]+]]:gpr = LSHL [[COPY]], [[SUB]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2-LABEL: name: lshr_s32
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 0
    ; AIE2-NEXT: [[SUB:%[0-9]+]]:er = SUB [[MOV_RLC_imm10_pseudo]], [[COPY1]], implicit-def dead $srcarry
    ; AIE2-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[COPY]], [[SUB]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2P-LABEL: name: lshr_s32
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; AIE2P-NEXT: [[SUB:%[0-9]+]]:er = SUB [[MOV_RLC_imm11_pseudo]], [[COPY1]], implicit-def dead $srcarry
    ; AIE2P-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[COPY]], [[SUB]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2PS-LABEL: name: lshr_s32
    ; AIE2PS: liveins: $r6, $r7
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r7
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 0
    ; AIE2PS-NEXT: [[SUB:%[0-9]+]]:mlockid_reg = SUB [[MOV_RLC_imm11_pseudo]], [[COPY1]], implicit-def dead $srcarry
    ; AIE2PS-NEXT: [[LSHL:%[0-9]+]]:mlockid_reg = LSHL [[COPY]], [[SUB]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_LSHR %0, %1
    PseudoRET implicit $lr, implicit %2
...

# FIXME: instead of inverting the sign bit of the constant, the negated constant should be materialized
# in the first place
---
name: lshr_const
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: lshr_const
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 16
    ; CHECK-NEXT: [[MOV_U20_1:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[MOV_U20_1]], [[MOV_U20_]]
    ; CHECK-NEXT: [[LSHL:%[0-9]+]]:gpr = LSHL [[COPY]], [[SUB]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2-LABEL: name: lshr_const
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo -16
    ; AIE2-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[COPY]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2P-LABEL: name: lshr_const
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -16
    ; AIE2P-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2PS-LABEL: name: lshr_const
    ; AIE2PS: liveins: $r6
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo -16
    ; AIE2PS-NEXT: [[LSHL:%[0-9]+]]:mlockid_reg = LSHL [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 16
    %2:gprregbank(s32) = G_LSHR %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: lshr_const_negative
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: lshr_const_negative
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $r6
    ; CHECK-NEXT: [[MOV_S12_:%[0-9]+]]:gpr = MOV_S12 -16
    ; CHECK-NEXT: [[MOV_U20_:%[0-9]+]]:gpr = MOV_U20 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[MOV_U20_]], [[MOV_S12_]]
    ; CHECK-NEXT: [[LSHL:%[0-9]+]]:gpr = LSHL [[COPY]], [[SUB]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2-LABEL: name: lshr_const_negative
    ; AIE2: liveins: $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 16
    ; AIE2-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[COPY]], [[MOV_RLC_imm10_pseudo]]
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2P-LABEL: name: lshr_const_negative
    ; AIE2P: liveins: $r6
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 16
    ; AIE2P-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    ;
    ; AIE2PS-LABEL: name: lshr_const_negative
    ; AIE2PS: liveins: $r6
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r6
    ; AIE2PS-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 16
    ; AIE2PS-NEXT: [[LSHL:%[0-9]+]]:mlockid_reg = LSHL [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LSHL]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 -16
    %2:gprregbank(s32) = G_LSHR %0, %1
    PseudoRET implicit $lr, implicit %2
...
