; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; unit test for the loop iteration metadata conversion to assumptions
;
; NOTE: Example File to reverse inlined GEP
;

; RUN: llc -mtriple aie2 --stop-after=irtranslator -verify-machineinstrs -o - %s | FileCheck %s
; RUN: llc -mtriple aie2p --stop-after=irtranslator -verify-machineinstrs -o - %s | FileCheck %s

%struct.gemm_bfp16_params = type { i32, i32, i32, i32, i32, i32, [8 x i8], i32, [28 x i8] }
@param = external dso_local global %struct.gemm_bfp16_params, align 32


define hidden fastcc void @InlineGeps(ptr nocapture readonly %lp) {
  ; CHECK-LABEL: name: InlineGeps
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE @param
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw G_PTR_ADD [[GV]], [[C]](s20)
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32) from %ir.lp)
  ; CHECK-NEXT:   G_STORE [[LOAD]](s32), [[GV]](p0) :: (store (s32) into @param, align 32)
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw nusw G_PTR_ADD [[GV]], [[C3]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32) from %ir.reverse.arrayidx)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw nusw G_PTR_ADD [[GV]], [[C4]](s20)
  ; CHECK-NEXT:   G_STORE [[LOAD1]](s32), [[PTR_ADD2]](p0) :: (store (s32) into %ir.reverse.arrayidx1)
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = nuw nusw G_PTR_ADD [[COPY]], [[C4]](s20)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from %ir.arrayidx1)
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = nuw nusw G_PTR_ADD [[PTR_ADD]], [[C5]](s20)
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[C2]](s32)
  ; CHECK-NEXT:   G_MEMSET [[PTR_ADD4]](p0), [[C1]](s8), [[TRUNC]](s20), 1 :: (store (s8) into %ir.reverse.arrayidx2)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %0 = load i32, ptr %lp, align 4
  store i32 %0, ptr @param, align 32
  %1 = load i32, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 2), align 4
  store i32 %1, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 1), align 4
  %arrayidx1 = getelementptr inbounds i8, ptr %lp, i20 4
  %2 = load i32, ptr %arrayidx1, align 4
  tail call void @llvm.memset.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) getelementptr inbounds (i8, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 7), i20 13), i8 0, i32 7, i1 false)
  ret void
}

; Check non inbound gep

define hidden fastcc void @NonInboundGepCheck(ptr nocapture readonly %lp) {
  ; CHECK-LABEL: name: NonInboundGepCheck
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE @param
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[GV]], [[C]](s20)
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32) from %ir.lp)
  ; CHECK-NEXT:   G_STORE [[LOAD]](s32), [[GV]](p0) :: (store (s32) into @param, align 32)
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[GV]], [[C3]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32) from %ir.reverse.arrayidx)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[GV]], [[C4]](s20)
  ; CHECK-NEXT:   G_STORE [[LOAD1]](s32), [[PTR_ADD2]](p0) :: (store (s32) into %ir.reverse.arrayidx1)
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from %ir.arrayidx1)
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C5]](s20)
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[C2]](s32)
  ; CHECK-NEXT:   G_MEMSET [[PTR_ADD4]](p0), [[C1]](s8), [[TRUNC]](s20), 1 :: (store (s8) into %ir.reverse.arrayidx2)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %0 = load i32, ptr %lp, align 4
  store i32 %0, ptr @param, align 32
  %1 = load i32, ptr getelementptr (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 2), align 4
  store i32 %1, ptr getelementptr (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 1), align 4
  %arrayidx1 = getelementptr i8, ptr %lp, i20 4
  %2 = load i32, ptr %arrayidx1, align 4
  tail call void @llvm.memset.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) getelementptr (i8, ptr getelementptr (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 7), i20 13), i8 0, i32 7, i1 false)
  ret void
}

; Check existing geps

define hidden fastcc void @ExistingGEP(ptr nocapture readonly %lp, i1 %cmp109.not.i.i) {
  ; CHECK-LABEL: name: ExistingGEP
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY1]](s32)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.bb.1:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from %ir.sunkaddr)
  ; CHECK-NEXT:   G_STORE [[LOAD]](s32), [[PTR_ADD]](p0) :: (store (s32) into %ir.sunkaddr)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.bb.2:
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from %ir.sunkaddr1)
  ; CHECK-NEXT:   G_STORE [[LOAD1]](s32), [[PTR_ADD1]](p0) :: (store (s32) into %ir.sunkaddr1)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %arrayidx1 = getelementptr i8, ptr %lp, i20 4
  br i1 %cmp109.not.i.i, label %bb.1, label %bb.2

bb.1:
  %2 = load i32, ptr %arrayidx1, align 4
  store i32 %2, ptr %arrayidx1, align 4
  ret void

bb.2:
  %3 = load i32, ptr %arrayidx1, align 4
  store i32 %3, ptr %arrayidx1, align 4
  ret void
}

; add unit-test for diverging control flows

define i32 @divergingControlflow(i1 %cmp109.not.i.i) {
  ; CHECK-LABEL: name: divergingControlflow
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE @param
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.3
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.common.ret:
  ; CHECK-NEXT:   $r0 = COPY [[C]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.if.end304.i.i:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw nusw G_PTR_ADD [[GV]], [[C1]](s20)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load (s32) from %ir.reverse.arrayidx)
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.func_23.exit.i:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw nusw G_PTR_ADD [[GV]], [[C2]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (dereferenceable load (s32) from %ir.reverse.arrayidx1)
  ; CHECK-NEXT:   G_BR %bb.2
entry:
  br i1 %cmp109.not.i.i, label %if.end304.i.i, label %func_23.exit.i

common.ret:                                       ; preds = %func_23.exit.i, %if.end304.i.i
  ret i32 0

if.end304.i.i:                                    ; preds = %entry
  %0 = load i32, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 2), align 4
  br label %common.ret

func_23.exit.i:                                   ; preds = %entry
  %1 = load i32, ptr getelementptr inbounds (%struct.gemm_bfp16_params, ptr @param, i20 0, i32 2), align 4
  br label %common.ret
}

; test GEP in PHI
; Sanity Check for gep outlining pass
; This is problematic when creating gep user at user position instead of
; at the position of global constants during IRTranslator

define i32 @GepInPhi() {
  ; CHECK-LABEL: name: GepInPhi
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(p0) = G_CONSTANT i20 12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.land.lhs.true.i:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(p0) = G_PHI [[C2]](p0), %bb.1, [[C]](p0), %bb.2
  ; CHECK-NEXT:   G_STORE [[C]](p0), [[PHI]](p0) :: (store (p0) into %ir.l_608.0.i, align 4)
  ; CHECK-NEXT:   G_BR %bb.2
entry:
  br label %land.lhs.true.i

land.lhs.true.i:                                  ; preds = %land.lhs.true.i, %entry
  %l_608.0.i = phi ptr [ getelementptr inbounds ([4 x ptr], ptr null, i20 0, i20 3), %entry ], [ null, %land.lhs.true.i ]
  store ptr null, ptr %l_608.0.i, align 4
  br label %land.lhs.true.i
}
