# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1 %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s

---
name:            fmul_float
body:             |
  bb.1:
    liveins: $r6, $r7

    ; AIE1-LABEL: name: fmul_float
    ; AIE1: liveins: $r6, $r7
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: JAL &__mulsf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit-def $r0
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2-LABEL: name: fmul_float
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: PseudoJL &__mulsf3, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: fmul_float
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: PseudoJL &__mulsf3, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(s32) = COPY $r6
    %2:_(s32) = COPY $r7
    %0:_(s32) = G_FMUL %1, %2
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0
...
---
name:            fmul_double
body:             |
  bb.1:
    liveins: $r6, $r7, $r8, $r9

    ; AIE1-LABEL: name: fmul_double
    ; AIE1: liveins: $r6, $r7, $r8, $r9
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: $r8 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: $r9 = COPY [[COPY3]](s32)
    ; AIE1-NEXT: JAL &__muldf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit $r8, implicit $r9, implicit-def $r0, implicit-def $r1
    ; AIE1-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE1-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2-LABEL: name: fmul_double
    ; AIE2: liveins: $r6, $r7, $r8, $r9
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2-NEXT: PseudoJL &__muldf3, csr_aie2, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2P-LABEL: name: fmul_double
    ; AIE2P: liveins: $r6, $r7, $r8, $r9
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2P-NEXT: PseudoJL &__muldf3, csr_aie2p, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2P-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %3:_(s32) = COPY $r6
    %4:_(s32) = COPY $r7
    %1:_(s64) = G_MERGE_VALUES %3(s32), %4(s32)
    %5:_(s32) = COPY $r8
    %6:_(s32) = COPY $r9
    %2:_(s64) = G_MERGE_VALUES %5(s32), %6(s32)
    %0:_(s64) = G_FMUL %1, %2
    %7:_(s32), %8:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %7(s32)
    $r1 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name:            fdiv_float
body:             |
  bb.1:
    liveins: $r6, $r7

    ; AIE1-LABEL: name: fdiv_float
    ; AIE1: liveins: $r6, $r7
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: JAL &__divsf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit-def $r0
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2-LABEL: name: fdiv_float
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: PseudoJL &__divsf3, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: fdiv_float
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: PseudoJL &__divsf3, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(s32) = COPY $r6
    %2:_(s32) = COPY $r7
    %0:_(s32) = G_FDIV %1, %2
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0
...
---
name:            fdiv_double
body:             |
  bb.1:
    liveins: $r6, $r7, $r8, $r9

    ; AIE1-LABEL: name: fdiv_double
    ; AIE1: liveins: $r6, $r7, $r8, $r9
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: $r8 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: $r9 = COPY [[COPY3]](s32)
    ; AIE1-NEXT: JAL &__divdf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit $r8, implicit $r9, implicit-def $r0, implicit-def $r1
    ; AIE1-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE1-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2-LABEL: name: fdiv_double
    ; AIE2: liveins: $r6, $r7, $r8, $r9
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2-NEXT: PseudoJL &__divdf3, csr_aie2, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2P-LABEL: name: fdiv_double
    ; AIE2P: liveins: $r6, $r7, $r8, $r9
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2P-NEXT: PseudoJL &__divdf3, csr_aie2p, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2P-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %3:_(s32) = COPY $r6
    %4:_(s32) = COPY $r7
    %1:_(s64) = G_MERGE_VALUES %3(s32), %4(s32)
    %5:_(s32) = COPY $r8
    %6:_(s32) = COPY $r9
    %2:_(s64) = G_MERGE_VALUES %5(s32), %6(s32)
    %0:_(s64) = G_FDIV %1, %2
    %7:_(s32), %8:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %7(s32)
    $r1 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name:            fadd_float
body:             |
  bb.1:
    liveins: $r6, $r7

    ; AIE1-LABEL: name: fadd_float
    ; AIE1: liveins: $r6, $r7
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: JAL &__addsf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit-def $r0
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2-LABEL: name: fadd_float
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: PseudoJL &__addsf3, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: fadd_float
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: PseudoJL &__addsf3, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(s32) = COPY $r6
    %2:_(s32) = COPY $r7
    %0:_(s32) = G_FADD %1, %2
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0
...
---
name:            fadd_double
body:             |
  bb.1:
    liveins: $r6, $r7, $r8, $r9

    ; AIE1-LABEL: name: fadd_double
    ; AIE1: liveins: $r6, $r7, $r8, $r9
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: $r8 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: $r9 = COPY [[COPY3]](s32)
    ; AIE1-NEXT: JAL &__adddf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit $r8, implicit $r9, implicit-def $r0, implicit-def $r1
    ; AIE1-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE1-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2-LABEL: name: fadd_double
    ; AIE2: liveins: $r6, $r7, $r8, $r9
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2-NEXT: PseudoJL &__adddf3, csr_aie2, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2P-LABEL: name: fadd_double
    ; AIE2P: liveins: $r6, $r7, $r8, $r9
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2P-NEXT: PseudoJL &__adddf3, csr_aie2p, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2P-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %3:_(s32) = COPY $r6
    %4:_(s32) = COPY $r7
    %1:_(s64) = G_MERGE_VALUES %3(s32), %4(s32)
    %5:_(s32) = COPY $r8
    %6:_(s32) = COPY $r9
    %2:_(s64) = G_MERGE_VALUES %5(s32), %6(s32)
    %0:_(s64) = G_FADD %1, %2
    %7:_(s32), %8:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %7(s32)
    $r1 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name:            fsub_float
body:             |
  bb.1:
    liveins: $r6, $r7

    ; AIE1-LABEL: name: fsub_float
    ; AIE1: liveins: $r6, $r7
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: JAL &__subsf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit-def $r0
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2-LABEL: name: fsub_float
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: PseudoJL &__subsf3, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: fsub_float
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: PseudoJL &__subsf3, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(s32) = COPY $r6
    %2:_(s32) = COPY $r7
    %0:_(s32) = G_FSUB %1, %2
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0
...
---
name:            fsub_double
body:             |
  bb.1:
    liveins: $r6, $r7, $r8, $r9

    ; AIE1-LABEL: name: fsub_double
    ; AIE1: liveins: $r6, $r7, $r8, $r9
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: $r8 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: $r9 = COPY [[COPY3]](s32)
    ; AIE1-NEXT: JAL &__subdf3, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit $r8, implicit $r9, implicit-def $r0, implicit-def $r1
    ; AIE1-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE1-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2-LABEL: name: fsub_double
    ; AIE2: liveins: $r6, $r7, $r8, $r9
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2-NEXT: PseudoJL &__subdf3, csr_aie2, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2P-LABEL: name: fsub_double
    ; AIE2P: liveins: $r6, $r7, $r8, $r9
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2P-NEXT: PseudoJL &__subdf3, csr_aie2p, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2P-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %3:_(s32) = COPY $r6
    %4:_(s32) = COPY $r7
    %1:_(s64) = G_MERGE_VALUES %3(s32), %4(s32)
    %5:_(s32) = COPY $r8
    %6:_(s32) = COPY $r9
    %2:_(s64) = G_MERGE_VALUES %5(s32), %6(s32)
    %0:_(s64) = G_FSUB %1, %2
    %7:_(s32), %8:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %7(s32)
    $r1 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name:            frem_float
body:             |
  bb.1:
    liveins: $r6, $r7

    ; AIE1-LABEL: name: frem_float
    ; AIE1: liveins: $r6, $r7
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: JAL &fmodf, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit-def $r0
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2-LABEL: name: frem_float
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: PseudoJL &fmodf, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: frem_float
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r1 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r2 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: PseudoJL &fmodf, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(s32) = COPY $r6
    %2:_(s32) = COPY $r7
    %0:_(s32) = G_FREM %1, %2
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0
...
---
name:            frem_double
body:             |
  bb.1:
    liveins: $r6, $r7, $r8, $r9

    ; AIE1-LABEL: name: frem_double
    ; AIE1: liveins: $r6, $r7, $r8, $r9
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE1-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r6 = COPY [[COPY]](s32)
    ; AIE1-NEXT: $r7 = COPY [[COPY1]](s32)
    ; AIE1-NEXT: $r8 = COPY [[COPY2]](s32)
    ; AIE1-NEXT: $r9 = COPY [[COPY3]](s32)
    ; AIE1-NEXT: JAL &fmod, csr_aie1, implicit-def $lr, implicit $r6, implicit $r7, implicit $r8, implicit $r9, implicit-def $r0, implicit-def $r1
    ; AIE1-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE1-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE1-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE1-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE1-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE1-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2-LABEL: name: frem_double
    ; AIE2: liveins: $r6, $r7, $r8, $r9
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2-NEXT: PseudoJL &fmod, csr_aie2, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2P-LABEL: name: frem_double
    ; AIE2P: liveins: $r6, $r7, $r8, $r9
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2P-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r2 = COPY [[COPY]](s32)
    ; AIE2P-NEXT: $r3 = COPY [[COPY1]](s32)
    ; AIE2P-NEXT: $r4 = COPY [[COPY2]](s32)
    ; AIE2P-NEXT: $r5 = COPY [[COPY3]](s32)
    ; AIE2P-NEXT: PseudoJL &fmod, csr_aie2p, implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY $r0
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY $r1
    ; AIE2P-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: $r0 = COPY [[COPY4]](s32)
    ; AIE2P-NEXT: $r1 = COPY [[COPY5]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %3:_(s32) = COPY $r6
    %4:_(s32) = COPY $r7
    %1:_(s64) = G_MERGE_VALUES %3(s32), %4(s32)
    %5:_(s32) = COPY $r8
    %6:_(s32) = COPY $r9
    %2:_(s64) = G_MERGE_VALUES %5(s32), %6(s32)
    %0:_(s64) = G_FREM %1, %2
    %7:_(s32), %8:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %7(s32)
    $r1 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...
