# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_implicit_def_s1
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_s1
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    %0:_(s1) = G_IMPLICIT_DEF
    %1:_(s32) = G_ANYEXT %0
    $r0 = COPY %1
...

---
name: test_implicit_def_s7
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_s7
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    %0:_(s7) = G_IMPLICIT_DEF
    %1:_(s32) = G_ANYEXT %0
    $r0 = COPY %1
...

---
name: test_implicit_def_s8
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_s8
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    %0:_(s8) = G_IMPLICIT_DEF
    %1:_(s32) = G_ANYEXT %0
    $r0 = COPY %1
...

---
name: test_implicit_def_s16
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_s16
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    %0:_(s16) = G_IMPLICIT_DEF
    %1:_(s32) = G_ANYEXT %0
    $r0 = COPY %1
...

---
name: test_implicit_def_s20
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_s20
    ; CHECK: [[DEF:%[0-9]+]]:_(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $m0 = COPY [[DEF]](s20)
    %0:_(s20) = G_IMPLICIT_DEF
    $m0 = COPY %0
...

---
name: test_implicit_def_s32
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_s32
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    %0:_(s32) = G_IMPLICIT_DEF
    $r0 = COPY %0
...

---
name: test_implicit_def_48
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_48
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    ; CHECK-NEXT: $r1 = COPY [[DEF]](s32)
    %0:_(s48) = G_IMPLICIT_DEF
    %1:_(s64) = G_ANYEXT %0
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %1(s64)
    $r0 = COPY %2
    $r1 = COPY %3
...

---
name: test_implicit_def_s64
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_s64
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]](s32)
    ; CHECK-NEXT: $r1 = COPY [[DEF]](s32)
    %0:_(s64) = G_IMPLICIT_DEF
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %2
    $r1 = COPY %3
...

---
name: test_implicit_def_p0
body: |
  bb.0:
    ; CHECK-LABEL: name: test_implicit_def_p0
    ; CHECK: [[DEF:%[0-9]+]]:_(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $p0 = COPY [[DEF]](p0)
    %0:_(p0) = G_IMPLICIT_DEF
    $p0 = COPY %0
...
