# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN:  llc --mtriple=aie2 --run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
# RUN:  llc --mtriple=aie2p --run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
# RUN:  llc --mtriple=aie2ps --run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

# Standard legalization: upper == 0 ? 32 + clz(lower) : clz(upper)
---
name:            clzll
body:             |
  bb.1.entry:
    liveins: $r1, $r2

    ; CHECK-LABEL: name: clzll
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[C]]
    ; CHECK-NEXT: [[CTLZ:%[0-9]+]]:_(s32) = G_CTLZ [[COPY]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[CTLZ]], [[C1]]
    ; CHECK-NEXT: [[CTLZ1:%[0-9]+]]:_(s32) = G_CTLZ [[COPY1]](s32)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[ADD]], [[CTLZ1]]
    ; CHECK-NEXT: $r0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(s32) = COPY $r1
    %3:_(s32) = COPY $r2
    %1:_(s64) = G_MERGE_VALUES %2(s32), %3(s32)
    %4:_(s64) = G_CTLZ %1(s64)
    %0:_(s32) = G_TRUNC %4(s64)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
