# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_select_vec64
body: |
  bb.0:
    liveins: $l0, $r6
    ; CHECK-LABEL: name: test_select_vec64
    ; CHECK: liveins: $l0, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ne), [[C]](s32), [[COPY]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s8>), [[UV1:%[0-9]+]]:_(<4 x s8>) = G_UNMERGE_VALUES [[COPY1]](<8 x s8>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<4 x s8>), [[UV3:%[0-9]+]]:_(<4 x s8>) = G_UNMERGE_VALUES [[COPY2]](<8 x s8>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[UV]](<4 x s8>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(s32) = G_BITCAST [[UV2]](<4 x s8>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[BITCAST]], [[BITCAST1]]
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<4 x s8>) = G_BITCAST [[SELECT]](s32)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(s32) = G_BITCAST [[UV1]](<4 x s8>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(s32) = G_BITCAST [[UV3]](<4 x s8>)
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[BITCAST3]], [[BITCAST4]]
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<4 x s8>) = G_BITCAST [[SELECT1]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s8>) = G_CONCAT_VECTORS [[BITCAST2]](<4 x s8>), [[BITCAST5]](<4 x s8>)
    ; CHECK-NEXT: PseudoRET implicit [[CONCAT_VECTORS]](<8 x s8>), implicit $lr
    %0:_(s32) = G_CONSTANT i32 0
    %1:_(s32) = COPY $r6
    %2:_(s1) = G_ICMP intpred(ne), %0, %1
    %3:_(<8 x s8>) = COPY $l0
    %4:_(<8 x s8>) = COPY $l0
    %5:_(<8 x s8>) = G_SELECT %2, %3, %4
    PseudoRET implicit %5, implicit $lr
...
