# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

# A <2 x s8> keeps its two elements packed in the low half of a GPR, so the
# bitcast to and from s16 is free while splitting, building, extracting from
# and extending it are not.

---
name:            unmerge_v4s8_into_v2s8
body:             |
  bb.0:
    liveins: $r0

    ; CHECK-LABEL: name: unmerge_v4s8_into_v2s8
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY]](<4 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[BITCAST]], [[C]](s32)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[BITCAST]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[LSHR]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC1]](s16)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST2]](<2 x s8>)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST3]](s16)
    ; CHECK-NEXT: [[ANYEXT1:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST4]](s16)
    ; CHECK-NEXT: $r0 = COPY [[ANYEXT]](s32)
    ; CHECK-NEXT: $r1 = COPY [[ANYEXT1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(<4 x s8>) = COPY $r0
    %1:_(<2 x s8>), %2:_(<2 x s8>) = G_UNMERGE_VALUES %0(<4 x s8>)
    %3:_(s16) = G_BITCAST %1(<2 x s8>)
    %4:_(s16) = G_BITCAST %2(<2 x s8>)
    %5:_(s32) = G_ANYEXT %3(s16)
    %6:_(s32) = G_ANYEXT %4(s16)
    $r0 = COPY %5(s32)
    $r1 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name:            bitcast_v2s8_to_s16
body:             |
  bb.0:
    liveins: $r0

    ; CHECK-LABEL: name: bitcast_v2s8_to_s16
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY]](<4 x s8>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[BITCAST]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST2]](s16)
    ; CHECK-NEXT: $r0 = COPY [[ANYEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<4 x s8>) = COPY $r0
    %1:_(<2 x s8>), %2:_(<2 x s8>) = G_UNMERGE_VALUES %0(<4 x s8>)
    %3:_(s16) = G_BITCAST %1(<2 x s8>)
    %4:_(s32) = G_ANYEXT %3(s16)
    $r0 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            bitcast_s16_to_v2s8
body:             |
  bb.0:
    liveins: $r0

    ; CHECK-LABEL: name: bitcast_s16_to_v2s8
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST]](<2 x s8>)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST1]](s16)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<4 x s8>) = G_BITCAST [[ANYEXT]](s32)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(s32) = G_BITCAST [[BITCAST2]](<4 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[BITCAST3]], [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[LSHR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r0
    %1:_(s16) = G_TRUNC %0(s32)
    %2:_(<2 x s8>) = G_BITCAST %1(s16)
    %3:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %2(<2 x s8>), %3(s32)
    %5:_(s32) = G_ANYEXT %4(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            extract_v2s8_dynamic
body:             |
  bb.0:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: extract_v2s8_dynamic
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY]](<4 x s8>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[BITCAST]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST2]](s16)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<4 x s8>) = G_BITCAST [[ANYEXT]](s32)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(s32) = G_BITCAST [[BITCAST3]](<4 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND]], [[C]](s32)
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[BITCAST4]], [[SHL]](s32)
    ; CHECK-NEXT: $r0 = COPY [[LSHR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<4 x s8>) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(<2 x s8>), %3:_(<2 x s8>) = G_UNMERGE_VALUES %0(<4 x s8>)
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %2(<2 x s8>), %1(s32)
    %5:_(s32) = G_ANYEXT %4(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            build_vector_v2s8
body:             |
  bb.0:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: build_vector_v2s8
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[C]], [[AND]]
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[C2]](s32)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[OR]], [[SHL]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[OR1]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST]](<2 x s8>)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST1]](s16)
    ; CHECK-NEXT: $r0 = COPY [[ANYEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(s8) = G_TRUNC %0(s32)
    %3:_(s8) = G_TRUNC %1(s32)
    %4:_(<2 x s8>) = G_BUILD_VECTOR %2(s8), %3(s8)
    %5:_(s16) = G_BITCAST %4(<2 x s8>)
    %6:_(s32) = G_ANYEXT %5(s16)
    $r0 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name:            zext_v2s8_to_v2s16
body:             |
  bb.0:
    liveins: $r0

    ; CHECK-LABEL: name: zext_v2s8_to_v2s16
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY]](<4 x s8>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[BITCAST]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST2]](s16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ANYEXT]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16711680
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SHL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[ANYEXT]], [[C2]]
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; CHECK-NEXT: $r0 = COPY [[BITCAST3]](<2 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<4 x s8>) = COPY $r0
    %1:_(<2 x s8>), %2:_(<2 x s8>) = G_UNMERGE_VALUES %0(<4 x s8>)
    %3:_(<2 x s16>) = G_ZEXT %1(<2 x s8>)
    $r0 = COPY %3(<2 x s16>)
    PseudoRET implicit $lr, implicit $r0
...
