# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

---
name: load_v2s8_align2
body: |
  bb.0:
    liveins: $p0
    ; AIE2-LABEL: name: load_v2s8_align2
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16))
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[LOAD]](s32)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2-NEXT: [[BITCAST1:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST]](<2 x s8>)
    ; AIE2-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST1]](s16)
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ANYEXT]], [[C]](s32)
    ; AIE2-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[ANYEXT]], [[SHL]]
    ; AIE2-NEXT: [[BITCAST2:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; AIE2-NEXT: $r0 = COPY [[BITCAST2]](<2 x s16>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: load_v2s8_align2
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16))
    ; AIE2PS-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[LOAD]](s32)
    ; AIE2PS-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2PS-NEXT: [[BITCAST1:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST]](<2 x s8>)
    ; AIE2PS-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST1]](s16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2PS-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ANYEXT]], [[C]](s32)
    ; AIE2PS-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[ANYEXT]], [[SHL]]
    ; AIE2PS-NEXT: [[BITCAST2:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; AIE2PS-NEXT: $r0 = COPY [[BITCAST2]](<2 x s16>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(p0) = COPY $p0
    %1:_(<2 x s8>) = G_LOAD %0(p0) :: (load (<2 x s8>), align 2)
    %2:_(<2 x s16>) = G_ANYEXT %1(<2 x s8>)
    $r0 = COPY %2(<2 x s16>)
    PseudoRET implicit $lr, implicit $r0
...

---
name: load_v2s8_align1
body: |
  bb.0:
    liveins: $p0
    ; AIE2-LABEL: name: load_v2s8_align1
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (load (s8))
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[LOAD]], [[C1]](s32)
    ; AIE2-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[ZEXTLOAD]]
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[OR]](s32)
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2-NEXT: [[BITCAST1:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST]](<2 x s8>)
    ; AIE2-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST1]](s16)
    ; AIE2-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[ANYEXT]], [[C1]](s32)
    ; AIE2-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[ANYEXT]], [[SHL1]]
    ; AIE2-NEXT: [[BITCAST2:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR1]](s32)
    ; AIE2-NEXT: $r0 = COPY [[BITCAST2]](<2 x s16>)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: load_v2s8_align1
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p0) :: (load (s8))
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2PS-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[LOAD]], [[C1]](s32)
    ; AIE2PS-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[ZEXTLOAD]]
    ; AIE2PS-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[OR]](s32)
    ; AIE2PS-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2PS-NEXT: [[BITCAST1:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST]](<2 x s8>)
    ; AIE2PS-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST1]](s16)
    ; AIE2PS-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[ANYEXT]], [[C1]](s32)
    ; AIE2PS-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[ANYEXT]], [[SHL1]]
    ; AIE2PS-NEXT: [[BITCAST2:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR1]](s32)
    ; AIE2PS-NEXT: $r0 = COPY [[BITCAST2]](<2 x s16>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(p0) = COPY $p0
    %1:_(<2 x s8>) = G_LOAD %0(p0) :: (load (<2 x s8>), align 1)
    %2:_(<2 x s16>) = G_ANYEXT %1(<2 x s8>)
    $r0 = COPY %2(<2 x s16>)
    PseudoRET implicit $lr, implicit $r0
...

---
name: store_v2s8_align2
body: |
  bb.0:
    liveins: $p0, $r0
    ; AIE2-LABEL: name: store_v2s8_align2
    ; AIE2: liveins: $p0, $r0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $r0
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[BITCAST]], [[C]](s32)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65280
    ; AIE2-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[LSHR]], [[C1]]
    ; AIE2-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; AIE2-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; AIE2-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[OR]](s32)
    ; AIE2-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; AIE2-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST2]](s16)
    ; AIE2-NEXT: G_STORE [[ANYEXT]](s32), [[COPY]](p0) :: (store (s16))
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2PS-LABEL: name: store_v2s8_align2
    ; AIE2PS: liveins: $p0, $r0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $r0
    ; AIE2PS-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2PS-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[BITCAST]], [[C]](s32)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65280
    ; AIE2PS-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[LSHR]], [[C1]]
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; AIE2PS-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; AIE2PS-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; AIE2PS-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[OR]](s32)
    ; AIE2PS-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2PS-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; AIE2PS-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST2]](s16)
    ; AIE2PS-NEXT: G_STORE [[ANYEXT]](s32), [[COPY]](p0) :: (store (s16))
    ; AIE2PS-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<2 x s16>) = COPY $r0
    %2:_(<2 x s8>) = G_TRUNC %1(<2 x s16>)
    G_STORE %2(<2 x s8>), %0(p0) :: (store (<2 x s8>), align 2)
    PseudoRET implicit $lr
...

---
name: store_v2s8_align1
body: |
  bb.0:
    liveins: $p0, $r0
    ; AIE2-LABEL: name: store_v2s8_align1
    ; AIE2: liveins: $p0, $r0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $r0
    ; AIE2-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[BITCAST]], [[C]](s32)
    ; AIE2-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65280
    ; AIE2-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[LSHR]], [[C1]]
    ; AIE2-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; AIE2-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; AIE2-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[OR]](s32)
    ; AIE2-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; AIE2-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST2]](s16)
    ; AIE2-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; AIE2-NEXT: [[AND2:%[0-9]+]]:_(s32) = G_AND [[ANYEXT]], [[C3]]
    ; AIE2-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[AND2]], [[C]](s32)
    ; AIE2-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2-NEXT: G_STORE [[ANYEXT]](s32), [[COPY]](p0) :: (store (s8))
    ; AIE2-NEXT: G_STORE [[LSHR1]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2PS-LABEL: name: store_v2s8_align1
    ; AIE2PS: liveins: $p0, $r0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $r0
    ; AIE2PS-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2PS-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[BITCAST]], [[C]](s32)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65280
    ; AIE2PS-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[LSHR]], [[C1]]
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; AIE2PS-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; AIE2PS-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; AIE2PS-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[OR]](s32)
    ; AIE2PS-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s8>) = G_BITCAST [[TRUNC]](s16)
    ; AIE2PS-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<2 x s8>)
    ; AIE2PS-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[BITCAST2]](s16)
    ; AIE2PS-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; AIE2PS-NEXT: [[AND2:%[0-9]+]]:_(s32) = G_AND [[ANYEXT]], [[C3]]
    ; AIE2PS-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[AND2]], [[C]](s32)
    ; AIE2PS-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2PS-NEXT: G_STORE [[ANYEXT]](s32), [[COPY]](p0) :: (store (s8))
    ; AIE2PS-NEXT: G_STORE [[LSHR1]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; AIE2PS-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<2 x s16>) = COPY $r0
    %2:_(<2 x s8>) = G_TRUNC %1(<2 x s16>)
    G_STORE %2(<2 x s8>), %0(p0) :: (store (<2 x s8>), align 1)
    PseudoRET implicit $lr
...
