# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: v8s32
body: |
  bb.0:
    ; CHECK-LABEL: name: v8s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<8 x s32>)
    %0:_(<8 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v16s16
body: |
  bb.0:
    ; CHECK-LABEL: name: v16s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<16 x s16>)
    %0:_(<16 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v32s8
body: |
  bb.0:
    ; CHECK-LABEL: name: v32s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<32 x s8>)
    %0:_(<32 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v16s32
body: |
  bb.0:
    ; CHECK-LABEL: name: v16s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<16 x s32>)
    %0:_(<16 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v32s16
body: |
  bb.0:
    ; CHECK-LABEL: name: v32s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<32 x s16>)
    %0:_(<32 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v64s8
body: |
  bb.0:
    ; CHECK-LABEL: name: v64s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<64 x s8>)
    %0:_(<64 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v32s32
body: |
  bb.0:
    ; CHECK-LABEL: name: v32s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<32 x s32>)
    %0:_(<32 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v64s16
body: |
  bb.0:
    ; CHECK-LABEL: name: v64s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<64 x s16>)
    %0:_(<64 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v128s8
body: |
  bb.0:
    ; CHECK-LABEL: name: v128s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<128 x s8>)
    %0:_(<128 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: acc256
body: |
  bb.0:
    ; CHECK-LABEL: name: acc256
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<4 x s64>)
    %0:_(<4 x s64>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: acc512
body: |
  bb.0:
    ; CHECK-LABEL: name: acc512
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<8 x s64>)
    %0:_(<8 x s64>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: acc1024
body: |
  bb.0:
    ; CHECK-LABEL: name: acc1024
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<16 x s64>)
    %0:_(<16 x s64>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...
