# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: v8s32
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: v8s32
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<8 x s32>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $wl0 = COPY [[FREEZE]](<8 x s32>)
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: v16s16
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: v16s16
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<16 x s16>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $wl0 = COPY [[FREEZE]](<16 x s16>)
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(<16 x s16>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: v32s8
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: v32s8
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<32 x s8>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $wl0 = COPY [[FREEZE]](<32 x s8>)
    %0:_(<32 x s8>) = COPY $wl0
    %1:_(<32 x s8>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: acc256
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: acc256
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s64>) = COPY $wl0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<4 x s64>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $wl0 = COPY [[FREEZE]](<4 x s64>)
    %0:_(<4 x s64>) = COPY $wl0
    %1:_(<4 x s64>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: v16s32
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: v16s32
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<16 x s32>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[FREEZE]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: v32s16
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: v32s16
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<32 x s16>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[FREEZE]](<32 x s16>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: v64s8
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: v64s8
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<64 x s8>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[FREEZE]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(<64 x s8>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: acc512
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: acc512
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $x0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<8 x s64>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[FREEZE]](<8 x s64>)
    %0:_(<8 x s64>) = COPY $x0
    %1:_(<8 x s64>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: v32s32
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: v32s32
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<32 x s32>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $y2 = COPY [[FREEZE]](<32 x s32>)
    %0:_(<32 x s32>) = COPY $y2
    %1:_(<32 x s32>) = G_FREEZE %0
    $y2 = COPY %1
...

---
name: v64s16
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: v64s16
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<64 x s16>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $y2 = COPY [[FREEZE]](<64 x s16>)
    %0:_(<64 x s16>) = COPY $y2
    %1:_(<64 x s16>) = G_FREEZE %0
    $y2 = COPY %1
...

---
name: v128s8
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: v128s8
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<128 x s8>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $y2 = COPY [[FREEZE]](<128 x s8>)
    %0:_(<128 x s8>) = COPY $y2
    %1:_(<128 x s8>) = G_FREEZE %0
    $y2 = COPY %1
...

---
name: acc1024
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: acc1024
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $y2
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<16 x s64>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $y2 = COPY [[FREEZE]](<16 x s64>)
    %0:_(<16 x s64>) = COPY $y2
    %1:_(<16 x s64>) = G_FREEZE %0
    $y2 = COPY %1
...
