# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_inttoptr_s20_to_p0
body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: test_inttoptr_s20_to_p0
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    %0:_(s32) = COPY $r6
    %1:_(s20) = G_TRUNC %0
    %2:_(p0) = G_INTTOPTR %1
    $p0 = COPY %2
...

---
name: test_inttoptr_s32_to_p0
body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: test_inttoptr_s32_to_p0
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    %0:_(s32) = COPY $r6
    %1:_(p0) = G_INTTOPTR %0
    $p0 = COPY %1
...
