# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -check-prefixes=CHECK,AIE2
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -check-prefixes=CHECK,AIE2P
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -check-prefixes=CHECK,AIE2P

---
name:            test_v32int8
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[COPY]](p0) :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s8>) = G_LOAD %1(p0) :: (load (<32 x s8>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32uint8
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32uint8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[COPY]](p0) :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s8>) = G_LOAD %1(p0) :: (load (<32 x s8>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v16int16
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16int16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[COPY]](p0) :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s16>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s16>) = G_LOAD %1(p0) :: (load (<16 x s16>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v16uint16
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16uint16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[COPY]](p0) :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s16>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s16>) = G_LOAD %1(p0) :: (load (<16 x s16>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v8int32
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8int32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (load (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<8 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<8 x s32>) = G_LOAD %1(p0) :: (load (<8 x s32>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v8uint32
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8uint32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (load (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<8 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<8 x s32>) = G_LOAD %1(p0) :: (load (<8 x s32>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v64int8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64int8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[COPY]](p0) :: (load (<64 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<64 x s8>)
    ;
    ; AIE2P-LABEL: name: test_v64int8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[COPY]](p0) :: (load (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD]](p0) :: (load (<32 x s8>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[LOAD]](<32 x s8>), [[LOAD1]](<32 x s8>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<64 x s8>) = G_LOAD %1(p0) :: (load (<64 x s8>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v64uint8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64uint8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[COPY]](p0) :: (load (<64 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<64 x s8>)
    ;
    ; AIE2P-LABEL: name: test_v64uint8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[COPY]](p0) :: (load (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD]](p0) :: (load (<32 x s8>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[LOAD]](<32 x s8>), [[LOAD1]](<32 x s8>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<64 x s8>) = G_LOAD %1(p0) :: (load (<64 x s8>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32int16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32int16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (load (<32 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_v32int16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[COPY]](p0) :: (load (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD]](p0) :: (load (<16 x s16>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[LOAD]](<16 x s16>), [[LOAD1]](<16 x s16>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s16>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s16>) = G_LOAD %1(p0) :: (load (<32 x s16>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32uint16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32uint16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY]](p0) :: (load (<32 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s16>)
    ;
    ; AIE2P-LABEL: name: test_v32uint16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[COPY]](p0) :: (load (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD]](p0) :: (load (<16 x s16>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[LOAD]](<16 x s16>), [[LOAD1]](<16 x s16>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s16>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s16>) = G_LOAD %1(p0) :: (load (<32 x s16>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v16int32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v16int32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (load (<16 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s32>)
    ;
    ; AIE2P-LABEL: name: test_v16int32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (load (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD]](p0) :: (load (<8 x s32>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[LOAD]](<8 x s32>), [[LOAD1]](<8 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s32>) = G_LOAD %1(p0) :: (load (<16 x s32>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v16uint32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v16uint32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (load (<16 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s32>)
    ;
    ; AIE2P-LABEL: name: test_v16uint32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (load (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD]](p0) :: (load (<8 x s32>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[LOAD]](<8 x s32>), [[LOAD1]](<8 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s32>) = G_LOAD %1(p0) :: (load (<16 x s32>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v128int8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v128int8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<128 x s8>) = G_LOAD [[COPY]](p0) :: (load (<128 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<128 x s8>)
    ;
    ; AIE2P-LABEL: name: test_v128int8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[COPY]](p0) :: (load (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD]](p0) :: (load (<32 x s8>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<32 x s8>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<32 x s8>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[LOAD]](<32 x s8>), [[LOAD1]](<32 x s8>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[LOAD2]](<32 x s8>), [[LOAD3]](<32 x s8>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<64 x s8>), [[CONCAT_VECTORS1]](<64 x s8>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<128 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<128 x s8>) = G_LOAD %1(p0) :: (load (<128 x s8>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v128uint8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v128uint8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<128 x s8>) = G_LOAD [[COPY]](p0) :: (load (<128 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<128 x s8>)
    ;
    ; AIE2P-LABEL: name: test_v128uint8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[COPY]](p0) :: (load (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD]](p0) :: (load (<32 x s8>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<32 x s8>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<32 x s8>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<32 x s8>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[LOAD]](<32 x s8>), [[LOAD1]](<32 x s8>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[LOAD2]](<32 x s8>), [[LOAD3]](<32 x s8>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<64 x s8>), [[CONCAT_VECTORS1]](<64 x s8>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<128 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<128 x s8>) = G_LOAD %1(p0) :: (load (<128 x s8>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v64int16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64int16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<64 x s16>) = G_LOAD [[COPY]](p0) :: (load (<64 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<64 x s16>)
    ;
    ; AIE2P-LABEL: name: test_v64int16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[COPY]](p0) :: (load (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD]](p0) :: (load (<16 x s16>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<16 x s16>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<16 x s16>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[LOAD]](<16 x s16>), [[LOAD1]](<16 x s16>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[LOAD2]](<16 x s16>), [[LOAD3]](<16 x s16>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s16>), [[CONCAT_VECTORS1]](<32 x s16>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<64 x s16>)
    %1:_(p0) = COPY $p0
    %0:_(<64 x s16>) = G_LOAD %1(p0) :: (load (<64 x s16>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v64uint16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64uint16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<64 x s16>) = G_LOAD [[COPY]](p0) :: (load (<64 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<64 x s16>)
    ;
    ; AIE2P-LABEL: name: test_v64uint16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[COPY]](p0) :: (load (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD]](p0) :: (load (<16 x s16>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<16 x s16>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<16 x s16>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[LOAD]](<16 x s16>), [[LOAD1]](<16 x s16>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[LOAD2]](<16 x s16>), [[LOAD3]](<16 x s16>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s16>), [[CONCAT_VECTORS1]](<32 x s16>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<64 x s16>)
    %1:_(p0) = COPY $p0
    %0:_(<64 x s16>) = G_LOAD %1(p0) :: (load (<64 x s16>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32int32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32int32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s32>) = G_LOAD [[COPY]](p0) :: (load (<32 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s32>)
    ;
    ; AIE2P-LABEL: name: test_v32int32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (load (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD]](p0) :: (load (<8 x s32>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<8 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<8 x s32>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[LOAD]](<8 x s32>), [[LOAD1]](<8 x s32>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[LOAD2]](<8 x s32>), [[LOAD3]](<8 x s32>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s32>), [[CONCAT_VECTORS1]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<32 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32uint32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32uint32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s32>) = G_LOAD [[COPY]](p0) :: (load (<32 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s32>)
    ;
    ; AIE2P-LABEL: name: test_v32uint32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[COPY]](p0) :: (load (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD]](p0) :: (load (<8 x s32>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<8 x s32>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<8 x s32>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[LOAD]](<8 x s32>), [[LOAD1]](<8 x s32>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[LOAD2]](<8 x s32>), [[LOAD3]](<8 x s32>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s32>), [[CONCAT_VECTORS1]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<32 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v8acc32
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8acc32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[COPY]](p0) :: (load (<4 x s64>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<4 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<4 x s64>) = G_LOAD %1(p0) :: (load (<4 x s64>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v4acc64
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v4acc64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[COPY]](p0) :: (load (<4 x s64>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<4 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<4 x s64>) = G_LOAD %1(p0) :: (load (<4 x s64>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v16acc32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v16acc32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s64>) = G_LOAD [[COPY]](p0) :: (load (<8 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<8 x s64>)
    ;
    ; AIE2P-LABEL: name: test_v16acc32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[COPY]](p0) :: (load (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD]](p0) :: (load (<4 x s64>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[LOAD]](<4 x s64>), [[LOAD1]](<4 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<8 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<8 x s64>) = G_LOAD %1(p0) :: (load (<8 x s64>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v8acc64
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v8acc64
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<8 x s64>) = G_LOAD [[COPY]](p0) :: (load (<8 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<8 x s64>)
    ;
    ; AIE2P-LABEL: name: test_v8acc64
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[COPY]](p0) :: (load (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD]](p0) :: (load (<4 x s64>) from unknown-address + 32)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[LOAD]](<4 x s64>), [[LOAD1]](<4 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<8 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<8 x s64>) = G_LOAD %1(p0) :: (load (<8 x s64>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32acc32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32acc32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s64>) = G_LOAD [[COPY]](p0) :: (load (<16 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s64>)
    ;
    ; AIE2P-LABEL: name: test_v32acc32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[COPY]](p0) :: (load (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD]](p0) :: (load (<4 x s64>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<4 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<4 x s64>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[LOAD]](<4 x s64>), [[LOAD1]](<4 x s64>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[LOAD2]](<4 x s64>), [[LOAD3]](<4 x s64>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<8 x s64>), [[CONCAT_VECTORS1]](<8 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<16 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s64>) = G_LOAD %1(p0) :: (load (<16 x s64>), align 32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v16acc64
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v16acc64
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s64>) = G_LOAD [[COPY]](p0) :: (load (<16 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<16 x s64>)
    ;
    ; AIE2P-LABEL: name: test_v16acc64
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[COPY]](p0) :: (load (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD]](p0) :: (load (<4 x s64>) from unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<4 x s64>) from unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(<4 x s64>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<4 x s64>) from unknown-address + 96)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[LOAD]](<4 x s64>), [[LOAD1]](<4 x s64>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[LOAD2]](<4 x s64>), [[LOAD3]](<4 x s64>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<8 x s64>), [[CONCAT_VECTORS1]](<8 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<16 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s64>) = G_LOAD %1(p0) :: (load (<16 x s64>), align 32)
    PseudoRET implicit $lr, implicit %0

...
