# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_shuffle_vec_256_32bit
body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: test_shuffle_vec_256_32bit
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY3]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY4]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY5]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY6]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY7]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS8:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY8]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS8]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS9:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY9]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS9]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS10:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY10]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS10]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS11:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY11]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS11]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS12:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY12]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS12]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS13:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY13]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS13]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS14:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY14]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS14]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS15:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY15]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS15]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF1]], [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>)
    %0:_(<8 x s32>) = G_IMPLICIT_DEF
    %1:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<8 x s32>), %0(<8 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %1
...

---
name: test_shuffle_vec_256_to_512_16bit
body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: test_shuffle_vec_256_to_512_16bit
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY1]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 16
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY2]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<32 x s16>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 16
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY3]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<32 x s16>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 16
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY4]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<32 x s16>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 16
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY5]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<32 x s16>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 16
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY6]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<32 x s16>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 16
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY7]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<32 x s16>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 16
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS8:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY8]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS8]](<32 x s16>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 16
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS9:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY9]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS9]](<32 x s16>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 16
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS10:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY10]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS10]](<32 x s16>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 16
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS11:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY11]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS11]](<32 x s16>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 16
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS12:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY12]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS12]](<32 x s16>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 16
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS13:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY13]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS13]](<32 x s16>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 16
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS14:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY14]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS14]](<32 x s16>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 16
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS15:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY15]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS15]](<32 x s16>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 16
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS16:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY16]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS16]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT16:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT16]], 16
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS17:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY17]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS17]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT17:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT17]], 16
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS18:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY18]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS18]](<32 x s16>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT18:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT18]], 16
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS19:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY19]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS19]](<32 x s16>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT19:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT19]], 16
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS20:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY20]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS20]](<32 x s16>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT20:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT20]], 16
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS21:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY21]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS21]](<32 x s16>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT21:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT21]], 16
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS22:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY22]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS22]](<32 x s16>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT22:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT22]], 16
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS23:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY23]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS23]](<32 x s16>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT23:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT23]], 16
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS24:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY24]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS24]](<32 x s16>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT24:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT24]], 16
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS25:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY25]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS25]](<32 x s16>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT25:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT25]], 16
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS26:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY26]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS26]](<32 x s16>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT26:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT26]], 16
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS27:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY27]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS27]](<32 x s16>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT27:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT27]], 16
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS28:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY28]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS28]](<32 x s16>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT28:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT28]], 16
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS29:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY29]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS29]](<32 x s16>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT29:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT29]], 16
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS30:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY30]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS30]](<32 x s16>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT30:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT30]], 16
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS31:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF1]](<16 x s16>), [[COPY31]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS31]](<32 x s16>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT31:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT31]], 16
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF2]], [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[ASSERT_SEXT1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[ASSERT_SEXT2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[ASSERT_SEXT3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[ASSERT_SEXT4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[ASSERT_SEXT5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[ASSERT_SEXT6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[ASSERT_SEXT7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[ASSERT_SEXT8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[ASSERT_SEXT9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[ASSERT_SEXT10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[ASSERT_SEXT11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[ASSERT_SEXT12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[ASSERT_SEXT13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[ASSERT_SEXT14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[ASSERT_SEXT15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[ASSERT_SEXT16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[ASSERT_SEXT17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[ASSERT_SEXT18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[ASSERT_SEXT19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[ASSERT_SEXT20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[ASSERT_SEXT21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[ASSERT_SEXT22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[ASSERT_SEXT23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[ASSERT_SEXT24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[ASSERT_SEXT25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[ASSERT_SEXT26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[ASSERT_SEXT27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[ASSERT_SEXT28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[ASSERT_SEXT29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[ASSERT_SEXT30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[ASSERT_SEXT31]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_ADD_VECTOR_ELT_HI31]](<32 x s16>)
    %0:_(<16 x s16>) = G_IMPLICIT_DEF
    %1:_(<16 x s16>) = G_IMPLICIT_DEF
    %2:_(<32 x s16>) = G_SHUFFLE_VECTOR %0(<16 x s16>), %1(<16 x s16>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %2
...

---
name: test_shuffle_vec_256_to_512_8bit
body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: test_shuffle_vec_256_to_512_8bit
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY1]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<64 x s8>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 8
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY2]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<64 x s8>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 8
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY3]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<64 x s8>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 8
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY4]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 8
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY5]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 8
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY6]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 8
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY7]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<64 x s8>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 8
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS8:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY8]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS8]](<64 x s8>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 8
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS9:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY9]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS9]](<64 x s8>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 8
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS10:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY10]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS10]](<64 x s8>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 8
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS11:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY11]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS11]](<64 x s8>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 8
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS12:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY12]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS12]](<64 x s8>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 8
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS13:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY13]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS13]](<64 x s8>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 8
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS14:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY14]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS14]](<64 x s8>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 8
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS15:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY15]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS15]](<64 x s8>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 8
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS16:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY16]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS16]](<64 x s8>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT16:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT16]], 8
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS17:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY17]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS17]](<64 x s8>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT17:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT17]], 8
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS18:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY18]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS18]](<64 x s8>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT18:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT18]], 8
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS19:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY19]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS19]](<64 x s8>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT19:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT19]], 8
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS20:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY20]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS20]](<64 x s8>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT20:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT20]], 8
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS21:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY21]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS21]](<64 x s8>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT21:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT21]], 8
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS22:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY22]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS22]](<64 x s8>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT22:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT22]], 8
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS23:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY23]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS23]](<64 x s8>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT23:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT23]], 8
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS24:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY24]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS24]](<64 x s8>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT24:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT24]], 8
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS25:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY25]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS25]](<64 x s8>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT25:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT25]], 8
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS26:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY26]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS26]](<64 x s8>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT26:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT26]], 8
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS27:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY27]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS27]](<64 x s8>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT27:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT27]], 8
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS28:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY28]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS28]](<64 x s8>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT28:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT28]], 8
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS29:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY29]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS29]](<64 x s8>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT29:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT29]], 8
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS30:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY30]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS30]](<64 x s8>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT30:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT30]], 8
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS31:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY31]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS31]](<64 x s8>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT31:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT31]], 8
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS32:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY32]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT32:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS32]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT32:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT32]], 8
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS33:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY33]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT33:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS33]](<64 x s8>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT33:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT33]], 8
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS34:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY34]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT34:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS34]](<64 x s8>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT34:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT34]], 8
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS35:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY35]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT35:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS35]](<64 x s8>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT35:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT35]], 8
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS36:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY36]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT36:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS36]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT36:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT36]], 8
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS37:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY37]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT37:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS37]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT37:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT37]], 8
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS38:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY38]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT38:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS38]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT38:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT38]], 8
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS39:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY39]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT39:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS39]](<64 x s8>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT39:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT39]], 8
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS40:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY40]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT40:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS40]](<64 x s8>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT40:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT40]], 8
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS41:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY41]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT41:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS41]](<64 x s8>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT41:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT41]], 8
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS42:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY42]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT42:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS42]](<64 x s8>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT42:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT42]], 8
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS43:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY43]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT43:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS43]](<64 x s8>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT43:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT43]], 8
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS44:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY44]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT44:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS44]](<64 x s8>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT44:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT44]], 8
    ; CHECK-NEXT: [[COPY45:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS45:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY45]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT45:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS45]](<64 x s8>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT45:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT45]], 8
    ; CHECK-NEXT: [[COPY46:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS46:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY46]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT46:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS46]](<64 x s8>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT46:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT46]], 8
    ; CHECK-NEXT: [[COPY47:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS47:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY47]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT47:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS47]](<64 x s8>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT47:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT47]], 8
    ; CHECK-NEXT: [[COPY48:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS48:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY48]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT48:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS48]](<64 x s8>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT48:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT48]], 8
    ; CHECK-NEXT: [[COPY49:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS49:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY49]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT49:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS49]](<64 x s8>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT49:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT49]], 8
    ; CHECK-NEXT: [[COPY50:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS50:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY50]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT50:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS50]](<64 x s8>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT50:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT50]], 8
    ; CHECK-NEXT: [[COPY51:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS51:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY51]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT51:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS51]](<64 x s8>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT51:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT51]], 8
    ; CHECK-NEXT: [[COPY52:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS52:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY52]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT52:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS52]](<64 x s8>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT52:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT52]], 8
    ; CHECK-NEXT: [[COPY53:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS53:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY53]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT53:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS53]](<64 x s8>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT53:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT53]], 8
    ; CHECK-NEXT: [[COPY54:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS54:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY54]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT54:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS54]](<64 x s8>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT54:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT54]], 8
    ; CHECK-NEXT: [[COPY55:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS55:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY55]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT55:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS55]](<64 x s8>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT55:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT55]], 8
    ; CHECK-NEXT: [[COPY56:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS56:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY56]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT56:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS56]](<64 x s8>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT56:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT56]], 8
    ; CHECK-NEXT: [[COPY57:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS57:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY57]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT57:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS57]](<64 x s8>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT57:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT57]], 8
    ; CHECK-NEXT: [[COPY58:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS58:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY58]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT58:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS58]](<64 x s8>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT58:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT58]], 8
    ; CHECK-NEXT: [[COPY59:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS59:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY59]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT59:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS59]](<64 x s8>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT59:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT59]], 8
    ; CHECK-NEXT: [[COPY60:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS60:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY60]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT60:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS60]](<64 x s8>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT60:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT60]], 8
    ; CHECK-NEXT: [[COPY61:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS61:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY61]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT61:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS61]](<64 x s8>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT61:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT61]], 8
    ; CHECK-NEXT: [[COPY62:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS62:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY62]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT62:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS62]](<64 x s8>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT62:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT62]], 8
    ; CHECK-NEXT: [[COPY63:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS63:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY63]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT63:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS63]](<64 x s8>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT63:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT63]], 8
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF2]], [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[ASSERT_SEXT1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[ASSERT_SEXT2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[ASSERT_SEXT3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[ASSERT_SEXT4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[ASSERT_SEXT5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[ASSERT_SEXT6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[ASSERT_SEXT7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[ASSERT_SEXT8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[ASSERT_SEXT9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[ASSERT_SEXT10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[ASSERT_SEXT11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[ASSERT_SEXT12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[ASSERT_SEXT13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[ASSERT_SEXT14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[ASSERT_SEXT15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[ASSERT_SEXT16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[ASSERT_SEXT17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[ASSERT_SEXT18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[ASSERT_SEXT19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[ASSERT_SEXT20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[ASSERT_SEXT21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[ASSERT_SEXT22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[ASSERT_SEXT23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[ASSERT_SEXT24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[ASSERT_SEXT25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[ASSERT_SEXT26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[ASSERT_SEXT27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[ASSERT_SEXT28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[ASSERT_SEXT29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[ASSERT_SEXT30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[ASSERT_SEXT31]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI32:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI31]], [[ASSERT_SEXT32]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI33:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI32]], [[ASSERT_SEXT33]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI34:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI33]], [[ASSERT_SEXT34]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI35:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI34]], [[ASSERT_SEXT35]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI36:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI35]], [[ASSERT_SEXT36]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI37:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI36]], [[ASSERT_SEXT37]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI38:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI37]], [[ASSERT_SEXT38]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI39:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI38]], [[ASSERT_SEXT39]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI40:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI39]], [[ASSERT_SEXT40]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI41:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI40]], [[ASSERT_SEXT41]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI42:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI41]], [[ASSERT_SEXT42]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI43:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI42]], [[ASSERT_SEXT43]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI44:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI43]], [[ASSERT_SEXT44]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI45:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI44]], [[ASSERT_SEXT45]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI46:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI45]], [[ASSERT_SEXT46]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI47:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI46]], [[ASSERT_SEXT47]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI48:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI47]], [[ASSERT_SEXT48]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI49:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI48]], [[ASSERT_SEXT49]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI50:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI49]], [[ASSERT_SEXT50]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI51:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI50]], [[ASSERT_SEXT51]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI52:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI51]], [[ASSERT_SEXT52]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI53:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI52]], [[ASSERT_SEXT53]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI54:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI53]], [[ASSERT_SEXT54]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI55:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI54]], [[ASSERT_SEXT55]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI56:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI55]], [[ASSERT_SEXT56]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI57:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI56]], [[ASSERT_SEXT57]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI58:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI57]], [[ASSERT_SEXT58]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI59:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI58]], [[ASSERT_SEXT59]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI60:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI59]], [[ASSERT_SEXT60]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI61:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI60]], [[ASSERT_SEXT61]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI62:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI61]], [[ASSERT_SEXT62]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI63:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI62]], [[ASSERT_SEXT63]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_ADD_VECTOR_ELT_HI63]](<64 x s8>)
    %0:_(<32 x s8>) = G_IMPLICIT_DEF
    %1:_(<32 x s8>) = G_IMPLICIT_DEF
    %2:_(<64 x s8>) = G_SHUFFLE_VECTOR %0(<32 x s8>), %1(<32 x s8>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63)
    PseudoRET implicit $lr, implicit %2
...

---
name: test_shuffle_vec_128_to_256_32bit
body: |
  bb.0:
    ; CHECK-LABEL: name: test_shuffle_vec_128_to_256_32bit
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[DEF]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI7]](<16 x s32>)
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[COPY3]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[COPY4]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[COPY5]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[COPY6]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[COPY7]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[DEF2]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF1]], [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV3]](<8 x s32>)
    %0:_(s32) = G_CONSTANT i32 42
    %1:_(<4 x s32>) = G_BUILD_VECTOR %0(s32), %0(s32), %0(s32), %0(s32)
    %2:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<4 x s32>), %1(<4 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %2
...

---
name: test_shuffle_vec_512_to_1024_32bit
body: |
  bb.0:
    ; CHECK-LABEL: name: test_shuffle_vec_512_to_1024_32bit
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY]], [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[AIE_SEXT_EXTRACT_VECTOR_ELT16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[AIE_SEXT_EXTRACT_VECTOR_ELT17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[AIE_SEXT_EXTRACT_VECTOR_ELT18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[AIE_SEXT_EXTRACT_VECTOR_ELT19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[AIE_SEXT_EXTRACT_VECTOR_ELT20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[AIE_SEXT_EXTRACT_VECTOR_ELT21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[AIE_SEXT_EXTRACT_VECTOR_ELT22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[AIE_SEXT_EXTRACT_VECTOR_ELT23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[AIE_SEXT_EXTRACT_VECTOR_ELT24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[AIE_SEXT_EXTRACT_VECTOR_ELT25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[AIE_SEXT_EXTRACT_VECTOR_ELT26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[AIE_SEXT_EXTRACT_VECTOR_ELT27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[AIE_SEXT_EXTRACT_VECTOR_ELT28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[AIE_SEXT_EXTRACT_VECTOR_ELT29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[AIE_SEXT_EXTRACT_VECTOR_ELT30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[AIE_SEXT_EXTRACT_VECTOR_ELT31]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI31]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %0:_(<16 x s32>) = G_IMPLICIT_DEF
    %1:_(<32 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %0(<16 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %1
...

# ShuffleVec also concatenates constants into vectors

---
name: test_shuffle_vec_16_to_32
body: |
  bb.0:
    ; CHECK-LABEL: name: test_shuffle_vec_16_to_32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[C2]], [[C1]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[C]], [[C1]](s32)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[OR]], [[SHL]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<2 x s16>)
    %0:_(s16) = G_CONSTANT i16 8
    %1:_(s16) = G_CONSTANT i16 16
    %2:_(<2 x s16>) = G_SHUFFLE_VECTOR %0(s16), %1(s16), shufflemask(1, 0)
    PseudoRET implicit $lr, implicit %2
...

# AArch64 supports transforming the same type dst and src, so we do here as well. It has a different
# behaviour in that it enlarges the size of the destination vector, shuffles the bigger vector and
# throws out the higher order numbers. This is similar to AIE's ShuffleVec instruction.

---
name: test_canonised_256_to_512_32bit
body: |
  bb.0:
    ; CHECK-LABEL: name: test_canonised_256_to_512_32bit
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY3]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY4]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY5]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY6]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY7]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF1]], [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI7]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<8 x s32>)
    %0:_(<8 x s32>) = G_IMPLICIT_DEF
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<8 x s32>) = G_SHUFFLE_VECTOR %0(<8 x s32>), %0(<8 x s32>), shufflemask(0, 1, 2, 3, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %2
...

---
name: test_shuffle_64bit_to_32bit
body: |
  bb.0:
    ; CHECK-LABEL: name: test_shuffle_64bit_to_32bit
    ; CHECK: [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s64) = G_BITCAST [[COPY]](<8 x s8>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[UV1]], [[C2]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[LSHR]], [[SHL]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C3]](s32)
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[UV3]], [[C3]](s32)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[LSHR1]], [[SHL1]]
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[UV4]], [[C2]](s32)
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[UV5]], [[C1]](s32)
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[LSHR2]], [[SHL2]]
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[UV9]], [[C1]](s32)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR4:%[0-9]+]]:_(s32) = G_LSHR [[UV11]], [[C3]](s32)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR5:%[0-9]+]]:_(s32) = G_LSHR [[UV13]], [[C2]](s32)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<64 x s8>) = COPY [[DEF1]](<64 x s8>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[BITCAST]](s64)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY [[TRUNC]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY2]], [[COPY3]](s32)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[COPY4]](s32)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY [[OR1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[COPY5]](s32)
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(s32) = COPY [[OR2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[COPY6]](s32)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(s32) = COPY [[UV7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[COPY7]](s32)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(s32) = COPY [[LSHR3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[COPY8]](s32)
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(s32) = COPY [[LSHR4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[COPY9]](s32)
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(s32) = COPY [[LSHR5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[COPY10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[DEF]](s32)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[COPY11]](s32)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[COPY12]](s32)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[COPY13]](s32)
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[COPY14]](s32)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[COPY15]](s32)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[COPY16]](s32)
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[COPY17]](s32)
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[COPY18]](s32)
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[COPY19]](s32)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[COPY20]](s32)
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[COPY21]](s32)
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[COPY22]](s32)
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[COPY23]](s32)
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[COPY24]](s32)
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[COPY25]](s32)
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[COPY26]](s32)
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[COPY27]](s32)
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[COPY28]](s32)
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[COPY29]](s32)
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[COPY30]](s32)
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[COPY31]](s32)
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[COPY32]](s32)
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[COPY33]](s32)
    ; CHECK-NEXT: [[UV14:%[0-9]+]]:_(<32 x s8>), [[UV15:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI31]](<64 x s8>)
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF2]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[UV15]](<32 x s8>), [[COPY34]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:_(<64 x s8>) = COPY [[DEF1]](<64 x s8>)
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:_(s32) = COPY [[TRUNC]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI32:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY35]], [[COPY36]](s32)
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI33:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI32]], [[COPY37]](s32)
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:_(s32) = COPY [[OR1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI34:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI33]], [[COPY38]](s32)
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:_(s32) = COPY [[OR2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI35:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI34]], [[COPY39]](s32)
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:_(s32) = COPY [[UV7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI36:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI35]], [[COPY40]](s32)
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:_(s32) = COPY [[LSHR3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI37:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI36]], [[COPY41]](s32)
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:_(s32) = COPY [[LSHR4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI38:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI37]], [[COPY42]](s32)
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:_(s32) = COPY [[LSHR5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI39:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI38]], [[COPY43]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI40:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI39]], [[DEF3]](s32)
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI41:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI40]], [[COPY44]](s32)
    ; CHECK-NEXT: [[COPY45:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI42:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI41]], [[COPY45]](s32)
    ; CHECK-NEXT: [[COPY46:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI43:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI42]], [[COPY46]](s32)
    ; CHECK-NEXT: [[COPY47:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI44:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI43]], [[COPY47]](s32)
    ; CHECK-NEXT: [[COPY48:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI45:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI44]], [[COPY48]](s32)
    ; CHECK-NEXT: [[COPY49:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI46:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI45]], [[COPY49]](s32)
    ; CHECK-NEXT: [[COPY50:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI47:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI46]], [[COPY50]](s32)
    ; CHECK-NEXT: [[COPY51:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI48:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI47]], [[COPY51]](s32)
    ; CHECK-NEXT: [[COPY52:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI49:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI48]], [[COPY52]](s32)
    ; CHECK-NEXT: [[COPY53:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI50:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI49]], [[COPY53]](s32)
    ; CHECK-NEXT: [[COPY54:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI51:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI50]], [[COPY54]](s32)
    ; CHECK-NEXT: [[COPY55:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI52:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI51]], [[COPY55]](s32)
    ; CHECK-NEXT: [[COPY56:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI53:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI52]], [[COPY56]](s32)
    ; CHECK-NEXT: [[COPY57:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI54:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI53]], [[COPY57]](s32)
    ; CHECK-NEXT: [[COPY58:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI55:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI54]], [[COPY58]](s32)
    ; CHECK-NEXT: [[COPY59:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI56:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI55]], [[COPY59]](s32)
    ; CHECK-NEXT: [[COPY60:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI57:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI56]], [[COPY60]](s32)
    ; CHECK-NEXT: [[COPY61:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI58:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI57]], [[COPY61]](s32)
    ; CHECK-NEXT: [[COPY62:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI59:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI58]], [[COPY62]](s32)
    ; CHECK-NEXT: [[COPY63:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI60:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI59]], [[COPY63]](s32)
    ; CHECK-NEXT: [[COPY64:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI61:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI60]], [[COPY64]](s32)
    ; CHECK-NEXT: [[COPY65:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI62:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI61]], [[COPY65]](s32)
    ; CHECK-NEXT: [[COPY66:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI63:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI62]], [[COPY66]](s32)
    ; CHECK-NEXT: [[UV16:%[0-9]+]]:_(<32 x s8>), [[UV17:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI63]](<64 x s8>)
    ; CHECK-NEXT: [[COPY67:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF2]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[UV17]](<32 x s8>), [[COPY67]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 8
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY68:%[0-9]+]]:_(<64 x s8>) = COPY [[DEF1]](<64 x s8>)
    ; CHECK-NEXT: [[COPY69:%[0-9]+]]:_(s32) = COPY [[TRUNC]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI64:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY68]], [[COPY69]](s32)
    ; CHECK-NEXT: [[COPY70:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI65:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI64]], [[COPY70]](s32)
    ; CHECK-NEXT: [[COPY71:%[0-9]+]]:_(s32) = COPY [[OR1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI66:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI65]], [[COPY71]](s32)
    ; CHECK-NEXT: [[COPY72:%[0-9]+]]:_(s32) = COPY [[OR2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI67:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI66]], [[COPY72]](s32)
    ; CHECK-NEXT: [[COPY73:%[0-9]+]]:_(s32) = COPY [[UV7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI68:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI67]], [[COPY73]](s32)
    ; CHECK-NEXT: [[COPY74:%[0-9]+]]:_(s32) = COPY [[LSHR3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI69:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI68]], [[COPY74]](s32)
    ; CHECK-NEXT: [[COPY75:%[0-9]+]]:_(s32) = COPY [[LSHR4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI70:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI69]], [[COPY75]](s32)
    ; CHECK-NEXT: [[COPY76:%[0-9]+]]:_(s32) = COPY [[LSHR5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI71:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI70]], [[COPY76]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI72:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI71]], [[DEF4]](s32)
    ; CHECK-NEXT: [[COPY77:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI73:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI72]], [[COPY77]](s32)
    ; CHECK-NEXT: [[COPY78:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI74:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI73]], [[COPY78]](s32)
    ; CHECK-NEXT: [[COPY79:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI75:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI74]], [[COPY79]](s32)
    ; CHECK-NEXT: [[COPY80:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI76:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI75]], [[COPY80]](s32)
    ; CHECK-NEXT: [[COPY81:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI77:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI76]], [[COPY81]](s32)
    ; CHECK-NEXT: [[COPY82:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI78:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI77]], [[COPY82]](s32)
    ; CHECK-NEXT: [[COPY83:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI79:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI78]], [[COPY83]](s32)
    ; CHECK-NEXT: [[COPY84:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI80:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI79]], [[COPY84]](s32)
    ; CHECK-NEXT: [[COPY85:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI81:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI80]], [[COPY85]](s32)
    ; CHECK-NEXT: [[COPY86:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI82:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI81]], [[COPY86]](s32)
    ; CHECK-NEXT: [[COPY87:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI83:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI82]], [[COPY87]](s32)
    ; CHECK-NEXT: [[COPY88:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI84:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI83]], [[COPY88]](s32)
    ; CHECK-NEXT: [[COPY89:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI85:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI84]], [[COPY89]](s32)
    ; CHECK-NEXT: [[COPY90:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI86:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI85]], [[COPY90]](s32)
    ; CHECK-NEXT: [[COPY91:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI87:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI86]], [[COPY91]](s32)
    ; CHECK-NEXT: [[COPY92:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI88:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI87]], [[COPY92]](s32)
    ; CHECK-NEXT: [[COPY93:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI89:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI88]], [[COPY93]](s32)
    ; CHECK-NEXT: [[COPY94:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI90:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI89]], [[COPY94]](s32)
    ; CHECK-NEXT: [[COPY95:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI91:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI90]], [[COPY95]](s32)
    ; CHECK-NEXT: [[COPY96:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI92:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI91]], [[COPY96]](s32)
    ; CHECK-NEXT: [[COPY97:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI93:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI92]], [[COPY97]](s32)
    ; CHECK-NEXT: [[COPY98:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI94:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI93]], [[COPY98]](s32)
    ; CHECK-NEXT: [[COPY99:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI95:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI94]], [[COPY99]](s32)
    ; CHECK-NEXT: [[UV18:%[0-9]+]]:_(<32 x s8>), [[UV19:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI95]](<64 x s8>)
    ; CHECK-NEXT: [[COPY100:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF2]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[UV19]](<32 x s8>), [[COPY100]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 8
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI96:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF1]], [[TRUNC]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI97:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI96]], [[OR]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI98:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI97]], [[OR1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI99:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI98]], [[OR2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI100:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI99]], [[UV7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI101:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI100]], [[LSHR3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI102:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI101]], [[LSHR4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI103:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI102]], [[LSHR5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI104:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI103]], [[DEF5]](s32)
    ; CHECK-NEXT: [[COPY101:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI105:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI104]], [[COPY101]](s32)
    ; CHECK-NEXT: [[COPY102:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI106:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI105]], [[COPY102]](s32)
    ; CHECK-NEXT: [[COPY103:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI107:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI106]], [[COPY103]](s32)
    ; CHECK-NEXT: [[COPY104:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI108:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI107]], [[COPY104]](s32)
    ; CHECK-NEXT: [[COPY105:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI109:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI108]], [[COPY105]](s32)
    ; CHECK-NEXT: [[COPY106:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI110:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI109]], [[COPY106]](s32)
    ; CHECK-NEXT: [[COPY107:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI111:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI110]], [[COPY107]](s32)
    ; CHECK-NEXT: [[COPY108:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI112:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI111]], [[COPY108]](s32)
    ; CHECK-NEXT: [[COPY109:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI113:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI112]], [[COPY109]](s32)
    ; CHECK-NEXT: [[COPY110:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI114:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI113]], [[COPY110]](s32)
    ; CHECK-NEXT: [[COPY111:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI115:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI114]], [[COPY111]](s32)
    ; CHECK-NEXT: [[COPY112:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI116:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI115]], [[COPY112]](s32)
    ; CHECK-NEXT: [[COPY113:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI117:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI116]], [[COPY113]](s32)
    ; CHECK-NEXT: [[COPY114:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI118:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI117]], [[COPY114]](s32)
    ; CHECK-NEXT: [[COPY115:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI119:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI118]], [[COPY115]](s32)
    ; CHECK-NEXT: [[COPY116:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI120:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI119]], [[COPY116]](s32)
    ; CHECK-NEXT: [[COPY117:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI121:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI120]], [[COPY117]](s32)
    ; CHECK-NEXT: [[COPY118:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI122:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI121]], [[COPY118]](s32)
    ; CHECK-NEXT: [[COPY119:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI123:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI122]], [[COPY119]](s32)
    ; CHECK-NEXT: [[COPY120:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI124:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI123]], [[COPY120]](s32)
    ; CHECK-NEXT: [[COPY121:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI125:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI124]], [[COPY121]](s32)
    ; CHECK-NEXT: [[COPY122:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI126:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI125]], [[COPY122]](s32)
    ; CHECK-NEXT: [[COPY123:%[0-9]+]]:_(s32) = COPY [[DEF5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI127:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI126]], [[COPY123]](s32)
    ; CHECK-NEXT: [[UV20:%[0-9]+]]:_(<32 x s8>), [[UV21:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI127]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[UV21]](<32 x s8>), [[DEF2]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 8
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ASSERT_SEXT]], [[C7]]
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[ASSERT_SEXT1]], [[C7]]
    ; CHECK-NEXT: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[C1]](s32)
    ; CHECK-NEXT: [[OR3:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL3]]
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT [[DEF6]], [[OR3]](s32), [[C]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_INSERT_VECTOR_ELT]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT1:%[0-9]+]]:_(<64 x s8>) = G_AIE_INSERT_VECTOR_ELT [[BITCAST1]], [[ASSERT_SEXT2]](s32), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT2:%[0-9]+]]:_(<64 x s8>) = G_AIE_INSERT_VECTOR_ELT [[AIE_INSERT_VECTOR_ELT1]], [[ASSERT_SEXT3]](s32), [[C6]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_INSERT_VECTOR_ELT2]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[BITCAST2]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<4 x s8>) = G_BITCAST [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST3]](<4 x s8>)
    %0:_(<8 x s8>) = COPY $l0
    %1:_(<8 x s8>) = COPY $l0
    %2:_(<4 x s8>) = G_SHUFFLE_VECTOR %0:_(<8 x s8>), %1:_, shufflemask(0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...


