# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -o - -verify-machineinstrs | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -o - -verify-machineinstrs | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -o - -verify-machineinstrs | FileCheck %s

---
name: test_dyn_alloca_size_in_reg
body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: test_dyn_alloca_size_in_reg
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $sp
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[TRUNC]](s20)
    ; CHECK-NEXT: $sp = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: $p0 = COPY [[COPY2]](p0)
    %0:_(s32) = COPY $r6
    %1:_(s20) = G_TRUNC %0(s32)
    %2:_(p0) = G_DYN_STACKALLOC %1(s20), 0
    $p0 = COPY %2(p0)
...

---
name: test_dyn_alloca_constant_size
body: |
  bb.0:
    ; CHECK-LABEL: name: test_dyn_alloca_constant_size
    ; CHECK: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $sp
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY [[COPY]](p0)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: $sp = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: $p0 = COPY [[COPY1]](p0)
    %0:_(s32) = G_CONSTANT i32 10
    %1:_(s20) = G_TRUNC %0(s32)
    %2:_(p0) = G_DYN_STACKALLOC %1(s20), 0
    $p0 = COPY %2(p0)
...
