# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: fconstant_s32_pos_1_0
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_pos_1_0
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1065353216
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float 1.0
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s32_neg_1234_984375
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_neg_1234_984375
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -996515968
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float -1234.984375
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s32_neg_6_25985339871e18
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_neg_6_25985339871e18
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -559038737
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float -6259853398707798016.0
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s32_pos_1_14437421182e-28
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_pos_1_14437421182e-28
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 286331153
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float 1.1443742118159063574371315176369871297420676412893991713559671552502550184726715087890625E-28
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s32_pos_0
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_pos_0
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float 0.0
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s32_neg_0
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_neg_0
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2147483648
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float -0.0
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

# inf, -inf, nan has to be represented using hex.
# For some reasons, LLVM uses double to represent float literals.
# Read this post to find out more https://lists.llvm.org/pipermail/llvm-dev/2011-April/039794.html

---
name: fconstant_s32_nan
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_nan
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2147483647
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float 0x7FFFFFFFE0000000
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s32_pos_inf
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_pos_inf
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2139095040
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float 0x7FF0000000000000
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s32_neg_inf
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s32_neg_inf
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -8388608
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = G_FCONSTANT float 0xFFF0000000000000
    $r0 = COPY %0
    PseudoRET implicit $lr, implicit $r0
...

---
name: fconstant_s64_pos_1_0
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_pos_1_0
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1072693248
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double 1.0
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name: fconstant_s64_neg_1234_984375
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_neg_1234_984375
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1064088592
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double -1234.984375
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name: fconstant_s64_0xdeadbeefdeadbeef
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_0xdeadbeefdeadbeef
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -559038737
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double -11885959257070703919456148548634952473978443067058088068735782929309736813972578700672499550706563985665902827478594040486485110859701652414158340096.0
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name: fconstant_s64_pos_0
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_pos_0
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double 0.0
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name: fconstant_s64_neg_0
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_neg_0
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2147483648
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double -0.0
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name: fconstant_s64_nan
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_nan
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2146959360
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name: fconstant_s64_pos_inf
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_pos_inf
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2146435072
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double 0x7FF0000000000000
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
name: fconstant_s64_neg_inf
body: |
  bb.0:
    ; CHECK-LABEL: name: fconstant_s64_neg_inf
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1048576
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r1 = COPY [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %0:_(s64) = G_FCONSTANT double 0xFFF0000000000000
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %1(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
