# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2S %s

---
name: smax_s32
body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE-LABEL: name: smax_s32
    ; AIE: liveins: $r6, $r7
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY]](s32), [[COPY1]]
    ; AIE-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2-LABEL: name: smax_s32
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY]](s32), [[COPY1]]
    ; AIE2-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE2-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2P-LABEL: name: smax_s32
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY]](s32), [[COPY1]]
    ; AIE2P-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE2P-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2S-LABEL: name: smax_s32
    ; AIE2S: liveins: $r6, $r7
    ; AIE2S-NEXT: {{  $}}
    ; AIE2S-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2S-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2S-NEXT: [[SMAX:%[0-9]+]]:_(s32) = G_SMAX [[COPY]], [[COPY1]]
    ; AIE2S-NEXT: $r0 = COPY [[SMAX]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s32) = G_SMAX %0, %1
    $r0 = COPY %2(s32)
...

---
name: smax_8
body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE-LABEL: name: smax_8
    ; AIE: liveins: $r6, $r7
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 8
    ; AIE-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 8
    ; AIE-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[SEXT_INREG]](s32), [[SEXT_INREG1]]
    ; AIE-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2-LABEL: name: smax_8
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 8
    ; AIE2-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 8
    ; AIE2-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[SEXT_INREG]](s32), [[SEXT_INREG1]]
    ; AIE2-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE2-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2P-LABEL: name: smax_8
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 8
    ; AIE2P-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 8
    ; AIE2P-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[SEXT_INREG]](s32), [[SEXT_INREG1]]
    ; AIE2P-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE2P-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2S-LABEL: name: smax_8
    ; AIE2S: liveins: $r6, $r7
    ; AIE2S-NEXT: {{  $}}
    ; AIE2S-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2S-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2S-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 8
    ; AIE2S-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 8
    ; AIE2S-NEXT: [[SMAX:%[0-9]+]]:_(s32) = G_SMAX [[SEXT_INREG]], [[SEXT_INREG1]]
    ; AIE2S-NEXT: $r0 = COPY [[SMAX]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s8) = G_TRUNC %0(s32)
    %3:_(s8) = G_TRUNC %1(s32)
    %4:_(s8) = G_SMAX %2, %3
    %5:_(s32) = G_ANYEXT %4(s8)
    $r0 = COPY %5(s32)
...

---
name: smax_16
body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE-LABEL: name: smax_16
    ; AIE: liveins: $r6, $r7
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; AIE-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; AIE-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[SEXT_INREG]](s32), [[SEXT_INREG1]]
    ; AIE-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2-LABEL: name: smax_16
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; AIE2-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; AIE2-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[SEXT_INREG]](s32), [[SEXT_INREG1]]
    ; AIE2-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE2-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2P-LABEL: name: smax_16
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; AIE2P-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; AIE2P-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[SEXT_INREG]](s32), [[SEXT_INREG1]]
    ; AIE2P-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[COPY]], [[COPY1]]
    ; AIE2P-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2S-LABEL: name: smax_16
    ; AIE2S: liveins: $r6, $r7
    ; AIE2S-NEXT: {{  $}}
    ; AIE2S-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2S-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2S-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; AIE2S-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; AIE2S-NEXT: [[SMAX:%[0-9]+]]:_(s32) = G_SMAX [[SEXT_INREG]], [[SEXT_INREG1]]
    ; AIE2S-NEXT: $r0 = COPY [[SMAX]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s16) = G_TRUNC %0(s32)
    %3:_(s16) = G_TRUNC %1(s32)
    %4:_(s16) = G_SMAX %2, %3
    %5:_(s32) = G_ANYEXT %4(s16)
    $r0 = COPY %5(s32)
...

---
name: smax_17
body: |
  bb.0:
    liveins: $r6, $r7
    ; AIE-LABEL: name: smax_17
    ; AIE: liveins: $r6, $r7
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; AIE-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; AIE-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SHL1]], [[C]](s32)
    ; AIE-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ASHR]](s32), [[ASHR1]]
    ; AIE-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[ASHR]], [[ASHR1]]
    ; AIE-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2-LABEL: name: smax_17
    ; AIE2: liveins: $r6, $r7
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; AIE2-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE2-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; AIE2-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE2-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SHL1]], [[C]](s32)
    ; AIE2-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ASHR]](s32), [[ASHR1]]
    ; AIE2-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[ASHR]], [[ASHR1]]
    ; AIE2-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2P-LABEL: name: smax_17
    ; AIE2P: liveins: $r6, $r7
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; AIE2P-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE2P-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; AIE2P-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE2P-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SHL1]], [[C]](s32)
    ; AIE2P-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ASHR]](s32), [[ASHR1]]
    ; AIE2P-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[ASHR]], [[ASHR1]]
    ; AIE2P-NEXT: $r0 = COPY [[SELECT]](s32)
    ;
    ; AIE2S-LABEL: name: smax_17
    ; AIE2S: liveins: $r6, $r7
    ; AIE2S-NEXT: {{  $}}
    ; AIE2S-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2S-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2S-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; AIE2S-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE2S-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; AIE2S-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE2S-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SHL1]], [[C]](s32)
    ; AIE2S-NEXT: [[SMAX:%[0-9]+]]:_(s32) = G_SMAX [[ASHR]], [[ASHR1]]
    ; AIE2S-NEXT: $r0 = COPY [[SMAX]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s17) = G_TRUNC %0(s32)
    %3:_(s17) = G_TRUNC %1(s32)
    %4:_(s17) = G_SMAX %2, %3
    %5:_(s32) = G_ANYEXT %4(s17)
    $r0 = COPY %5(s32)
...

---
name: smax_64
body: |
  bb.0:
    liveins: $r6, $r7, $r8, $r9
    ; AIE-LABEL: name: smax_64
    ; AIE: liveins: $r6, $r7, $r8, $r9
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[COPY]](s32), [[COPY2]]
    ; AIE-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY1]](s32), [[COPY3]]
    ; AIE-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[COPY3]]
    ; AIE-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY]], [[COPY2]]
    ; AIE-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY1]], [[COPY3]]
    ; AIE-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE-NEXT: $r1 = COPY [[SELECT2]](s32)
    ;
    ; AIE2-LABEL: name: smax_64
    ; AIE2: liveins: $r6, $r7, $r8, $r9
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[COPY]](s32), [[COPY2]]
    ; AIE2-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY1]](s32), [[COPY3]]
    ; AIE2-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[COPY3]]
    ; AIE2-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE2-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY]], [[COPY2]]
    ; AIE2-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY1]], [[COPY3]]
    ; AIE2-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE2-NEXT: $r1 = COPY [[SELECT2]](s32)
    ;
    ; AIE2P-LABEL: name: smax_64
    ; AIE2P: liveins: $r6, $r7, $r8, $r9
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2P-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[COPY]](s32), [[COPY2]]
    ; AIE2P-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY1]](s32), [[COPY3]]
    ; AIE2P-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[COPY3]]
    ; AIE2P-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE2P-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY]], [[COPY2]]
    ; AIE2P-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY1]], [[COPY3]]
    ; AIE2P-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE2P-NEXT: $r1 = COPY [[SELECT2]](s32)
    ;
    ; AIE2S-LABEL: name: smax_64
    ; AIE2S: liveins: $r6, $r7, $r8, $r9
    ; AIE2S-NEXT: {{  $}}
    ; AIE2S-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2S-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2S-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2S-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2S-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[COPY]](s32), [[COPY2]]
    ; AIE2S-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY1]](s32), [[COPY3]]
    ; AIE2S-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[COPY3]]
    ; AIE2S-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE2S-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY]], [[COPY2]]
    ; AIE2S-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[COPY1]], [[COPY3]]
    ; AIE2S-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE2S-NEXT: $r1 = COPY [[SELECT2]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s32) = COPY $r8
    %3:_(s32) = COPY $r9
    %4:_(s64) = G_MERGE_VALUES %0(s32), %1(s32)
    %5:_(s64) = G_MERGE_VALUES %2(s32), %3(s32)
    %6:_(s64) = G_SMAX %4, %5
    %7:_(s32), %8:_(s32) = G_UNMERGE_VALUES %6(s64)
    $r0 = COPY %7(s32)
    $r1 = COPY %8(s32)
...

---
name: smax_48
body: |
  bb.0:
    liveins: $r6, $r7, $r8, $r9
    ; AIE-LABEL: name: smax_48
    ; AIE: liveins: $r6, $r7, $r8, $r9
    ; AIE-NEXT: {{  $}}
    ; AIE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; AIE-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY]], [[C]](s32)
    ; AIE-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL1]], [[LSHR]]
    ; AIE-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[SHL]], [[C]](s32)
    ; AIE-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[OR]], [[C]](s32)
    ; AIE-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[LSHR1]], [[SHL2]]
    ; AIE-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[OR]], [[C]](s32)
    ; AIE-NEXT: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[COPY2]], [[C]](s32)
    ; AIE-NEXT: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[COPY3]], [[C]](s32)
    ; AIE-NEXT: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[COPY2]], [[C]](s32)
    ; AIE-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[SHL4]], [[LSHR2]]
    ; AIE-NEXT: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[SHL3]], [[C]](s32)
    ; AIE-NEXT: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[OR2]], [[C]](s32)
    ; AIE-NEXT: [[OR3:%[0-9]+]]:_(s32) = G_OR [[LSHR3]], [[SHL5]]
    ; AIE-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[OR2]], [[C]](s32)
    ; AIE-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[OR1]](s32), [[OR3]]
    ; AIE-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ASHR]](s32), [[ASHR1]]
    ; AIE-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[ASHR]](s32), [[ASHR1]]
    ; AIE-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[OR1]], [[OR3]]
    ; AIE-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[ASHR]], [[ASHR1]]
    ; AIE-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE-NEXT: $r1 = COPY [[SELECT2]](s32)
    ;
    ; AIE2-LABEL: name: smax_48
    ; AIE2: liveins: $r6, $r7, $r8, $r9
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; AIE2-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE2-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE2-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY]], [[C]](s32)
    ; AIE2-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL1]], [[LSHR]]
    ; AIE2-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[SHL]], [[C]](s32)
    ; AIE2-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[OR]], [[C]](s32)
    ; AIE2-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[LSHR1]], [[SHL2]]
    ; AIE2-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[OR]], [[C]](s32)
    ; AIE2-NEXT: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[COPY2]], [[C]](s32)
    ; AIE2-NEXT: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[COPY3]], [[C]](s32)
    ; AIE2-NEXT: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[COPY2]], [[C]](s32)
    ; AIE2-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[SHL4]], [[LSHR2]]
    ; AIE2-NEXT: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[SHL3]], [[C]](s32)
    ; AIE2-NEXT: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[OR2]], [[C]](s32)
    ; AIE2-NEXT: [[OR3:%[0-9]+]]:_(s32) = G_OR [[LSHR3]], [[SHL5]]
    ; AIE2-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[OR2]], [[C]](s32)
    ; AIE2-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[OR1]](s32), [[OR3]]
    ; AIE2-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ASHR]](s32), [[ASHR1]]
    ; AIE2-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[ASHR]](s32), [[ASHR1]]
    ; AIE2-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE2-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[OR1]], [[OR3]]
    ; AIE2-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[ASHR]], [[ASHR1]]
    ; AIE2-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE2-NEXT: $r1 = COPY [[SELECT2]](s32)
    ;
    ; AIE2P-LABEL: name: smax_48
    ; AIE2P: liveins: $r6, $r7, $r8, $r9
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; AIE2P-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE2P-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE2P-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY]], [[C]](s32)
    ; AIE2P-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL1]], [[LSHR]]
    ; AIE2P-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[SHL]], [[C]](s32)
    ; AIE2P-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[OR]], [[C]](s32)
    ; AIE2P-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[LSHR1]], [[SHL2]]
    ; AIE2P-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[OR]], [[C]](s32)
    ; AIE2P-NEXT: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[COPY2]], [[C]](s32)
    ; AIE2P-NEXT: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[COPY3]], [[C]](s32)
    ; AIE2P-NEXT: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[COPY2]], [[C]](s32)
    ; AIE2P-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[SHL4]], [[LSHR2]]
    ; AIE2P-NEXT: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[SHL3]], [[C]](s32)
    ; AIE2P-NEXT: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[OR2]], [[C]](s32)
    ; AIE2P-NEXT: [[OR3:%[0-9]+]]:_(s32) = G_OR [[LSHR3]], [[SHL5]]
    ; AIE2P-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[OR2]], [[C]](s32)
    ; AIE2P-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[OR1]](s32), [[OR3]]
    ; AIE2P-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ASHR]](s32), [[ASHR1]]
    ; AIE2P-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[ASHR]](s32), [[ASHR1]]
    ; AIE2P-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE2P-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[OR1]], [[OR3]]
    ; AIE2P-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[ASHR]], [[ASHR1]]
    ; AIE2P-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE2P-NEXT: $r1 = COPY [[SELECT2]](s32)
    ;
    ; AIE2S-LABEL: name: smax_48
    ; AIE2S: liveins: $r6, $r7, $r8, $r9
    ; AIE2S-NEXT: {{  $}}
    ; AIE2S-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; AIE2S-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; AIE2S-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r8
    ; AIE2S-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r9
    ; AIE2S-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; AIE2S-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; AIE2S-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[COPY1]], [[C]](s32)
    ; AIE2S-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY]], [[C]](s32)
    ; AIE2S-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL1]], [[LSHR]]
    ; AIE2S-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[SHL]], [[C]](s32)
    ; AIE2S-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[OR]], [[C]](s32)
    ; AIE2S-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[LSHR1]], [[SHL2]]
    ; AIE2S-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[OR]], [[C]](s32)
    ; AIE2S-NEXT: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[COPY2]], [[C]](s32)
    ; AIE2S-NEXT: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[COPY3]], [[C]](s32)
    ; AIE2S-NEXT: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[COPY2]], [[C]](s32)
    ; AIE2S-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[SHL4]], [[LSHR2]]
    ; AIE2S-NEXT: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[SHL3]], [[C]](s32)
    ; AIE2S-NEXT: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[OR2]], [[C]](s32)
    ; AIE2S-NEXT: [[OR3:%[0-9]+]]:_(s32) = G_OR [[LSHR3]], [[SHL5]]
    ; AIE2S-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[OR2]], [[C]](s32)
    ; AIE2S-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[OR1]](s32), [[OR3]]
    ; AIE2S-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ASHR]](s32), [[ASHR1]]
    ; AIE2S-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[ASHR]](s32), [[ASHR1]]
    ; AIE2S-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[ICMP]], [[ICMP1]]
    ; AIE2S-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[OR1]], [[OR3]]
    ; AIE2S-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[SELECT]](s32), [[ASHR]], [[ASHR1]]
    ; AIE2S-NEXT: $r0 = COPY [[SELECT1]](s32)
    ; AIE2S-NEXT: $r1 = COPY [[SELECT2]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s32) = COPY $r8
    %3:_(s32) = COPY $r9
    %4:_(s64) = G_MERGE_VALUES %0(s32), %1(s32)
    %5:_(s64) = G_MERGE_VALUES %2(s32), %3(s32)
    %6:_(s48) = G_TRUNC %4(s64)
    %7:_(s48) = G_TRUNC %5(s64)
    %8:_(s48) = G_SMAX %6, %7
    %9:_(s64) = G_ANYEXT %8(s48)
    %10:_(s32), %11:_(s32) = G_UNMERGE_VALUES %9(s64)
    $r0 = COPY %10(s32)
    $r1 = COPY %11(s32)
...
