# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_s256_store
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_s256_store
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s256) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](s256), [[COPY]](p0) :: (store (s256))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s256) = G_IMPLICIT_DEF
    G_STORE %1(s256), %0(p0) :: (store (s256))
    PseudoRET implicit $lr
...

---
name:            test_s256_load
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_s256_load
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:_(p0) = COPY $p0
    %0:_(s256) = G_LOAD %1(p0) :: (load (s256))
    PseudoRET implicit $lr
...
