# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -check-prefixes=CHECK,AIE2
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -check-prefixes=CHECK,AIE2P

---
name:            test_v32int8
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<32 x s8>), [[COPY]](p0) :: (store (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s8>), %0(p0) :: (store (<32 x s8>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v32uint8
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32uint8
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<32 x s8>), [[COPY]](p0) :: (store (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s8>), %0(p0) :: (store (<32 x s8>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v16int16
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16int16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<16 x s16>), [[COPY]](p0) :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s16>), %0(p0) :: (store (<16 x s16>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v16uint16
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16uint16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<16 x s16>), [[COPY]](p0) :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s16>), %0(p0) :: (store (<16 x s16>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v8int32
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8int32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s32>), %0(p0) :: (store (<8 x s32>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v8uint32
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8uint32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s32>), %0(p0) :: (store (<8 x s32>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v64int8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64int8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<64 x s8>), [[COPY]](p0) :: (store (<64 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v64int8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[DEF]](<64 x s8>)
    ; AIE2P-NEXT: G_STORE [[UV]](<32 x s8>), [[COPY]](p0) :: (store (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<32 x s8>), [[PTR_ADD]](p0) :: (store (<32 x s8>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s8>), %0(p0) :: (store (<64 x s8>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v64uint8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64uint8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<64 x s8>), [[COPY]](p0) :: (store (<64 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v64uint8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[DEF]](<64 x s8>)
    ; AIE2P-NEXT: G_STORE [[UV]](<32 x s8>), [[COPY]](p0) :: (store (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<32 x s8>), [[PTR_ADD]](p0) :: (store (<32 x s8>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s8>), %0(p0) :: (store (<64 x s8>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v32int16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32int16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<32 x s16>), [[COPY]](p0) :: (store (<32 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v32int16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[DEF]](<32 x s16>)
    ; AIE2P-NEXT: G_STORE [[UV]](<16 x s16>), [[COPY]](p0) :: (store (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<16 x s16>), [[PTR_ADD]](p0) :: (store (<16 x s16>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s16>), %0(p0) :: (store (<32 x s16>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v32uint16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32uint16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<32 x s16>), [[COPY]](p0) :: (store (<32 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v32uint16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[DEF]](<32 x s16>)
    ; AIE2P-NEXT: G_STORE [[UV]](<16 x s16>), [[COPY]](p0) :: (store (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<16 x s16>), [[PTR_ADD]](p0) :: (store (<16 x s16>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s16>), %0(p0) :: (store (<32 x s16>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v16int32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v16int32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<16 x s32>), [[COPY]](p0) :: (store (<16 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v16int32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[DEF]](<16 x s32>)
    ; AIE2P-NEXT: G_STORE [[UV]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s32>), %0(p0) :: (store (<16 x s32>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v16uint32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v16uint32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<16 x s32>), [[COPY]](p0) :: (store (<16 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v16uint32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[DEF]](<16 x s32>)
    ; AIE2P-NEXT: G_STORE [[UV]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s32>), %0(p0) :: (store (<16 x s32>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v128int8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v128int8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<128 x s8>), [[COPY]](p0) :: (store (<128 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v128int8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[DEF]](<128 x s8>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<32 x s8>), [[UV3:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[UV]](<64 x s8>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<32 x s8>), [[UV5:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[UV1]](<64 x s8>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<32 x s8>), [[COPY]](p0) :: (store (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<32 x s8>), [[PTR_ADD]](p0) :: (store (<32 x s8>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<32 x s8>), [[PTR_ADD1]](p0) :: (store (<32 x s8>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<32 x s8>), [[PTR_ADD2]](p0) :: (store (<32 x s8>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<128 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<128 x s8>), %0(p0) :: (store (<128 x s8>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v128uint8
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v128uint8
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<128 x s8>), [[COPY]](p0) :: (store (<128 x s8>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v128uint8
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[DEF]](<128 x s8>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<32 x s8>), [[UV3:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[UV]](<64 x s8>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<32 x s8>), [[UV5:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[UV1]](<64 x s8>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<32 x s8>), [[COPY]](p0) :: (store (<32 x s8>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<32 x s8>), [[PTR_ADD]](p0) :: (store (<32 x s8>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<32 x s8>), [[PTR_ADD1]](p0) :: (store (<32 x s8>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<32 x s8>), [[PTR_ADD2]](p0) :: (store (<32 x s8>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<128 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<128 x s8>), %0(p0) :: (store (<128 x s8>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v64int16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64int16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<64 x s16>), [[COPY]](p0) :: (store (<64 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v64int16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[DEF]](<64 x s16>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<16 x s16>), [[UV3:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[UV]](<32 x s16>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<16 x s16>), [[UV5:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[UV1]](<32 x s16>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<16 x s16>), [[COPY]](p0) :: (store (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<16 x s16>), [[PTR_ADD]](p0) :: (store (<16 x s16>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<16 x s16>), [[PTR_ADD1]](p0) :: (store (<16 x s16>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<16 x s16>), [[PTR_ADD2]](p0) :: (store (<16 x s16>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s16>), %0(p0) :: (store (<64 x s16>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v64uint16
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v64uint16
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<64 x s16>), [[COPY]](p0) :: (store (<64 x s16>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v64uint16
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[DEF]](<64 x s16>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<16 x s16>), [[UV3:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[UV]](<32 x s16>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<16 x s16>), [[UV5:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[UV1]](<32 x s16>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<16 x s16>), [[COPY]](p0) :: (store (<16 x s16>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<16 x s16>), [[PTR_ADD]](p0) :: (store (<16 x s16>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<16 x s16>), [[PTR_ADD1]](p0) :: (store (<16 x s16>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<16 x s16>), [[PTR_ADD2]](p0) :: (store (<16 x s16>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s16>), %0(p0) :: (store (<64 x s16>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v32int32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32int32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v32int32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[DEF]](<32 x s32>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[UV]](<16 x s32>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<8 x s32>), [[UV5:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[UV1]](<16 x s32>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<8 x s32>), [[PTR_ADD2]](p0) :: (store (<8 x s32>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s32>), %0(p0) :: (store (<32 x s32>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v32uint32
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2-LABEL: name: test_v32uint32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v32uint32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[DEF]](<32 x s32>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[UV]](<16 x s32>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<8 x s32>), [[UV5:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[UV1]](<16 x s32>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<8 x s32>), [[PTR_ADD2]](p0) :: (store (<8 x s32>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s32>), %0(p0) :: (store (<32 x s32>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v8acc32
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v8acc32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<4 x s64>), [[COPY]](p0) :: (store (<4 x s64>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<4 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<4 x s64>), %0(p0) :: (store (<4 x s64>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v4acc64
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v4acc64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<4 x s64>), [[COPY]](p0) :: (store (<4 x s64>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<4 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<4 x s64>), %0(p0) :: (store (<4 x s64>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v16acc32
body:             |
  bb.1.entry:
    liveins:  $p0

    ; AIE2-LABEL: name: test_v16acc32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<8 x s64>), [[COPY]](p0) :: (store (<8 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v16acc32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[DEF]](<8 x s64>)
    ; AIE2P-NEXT: G_STORE [[UV]](<4 x s64>), [[COPY]](p0) :: (store (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<4 x s64>), [[PTR_ADD]](p0) :: (store (<4 x s64>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s64>), %0(p0) :: (store (<8 x s64>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v8acc64
body:             |
  bb.1.entry:
    liveins:  $p0

    ; AIE2-LABEL: name: test_v8acc64
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<8 x s64>), [[COPY]](p0) :: (store (<8 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v8acc64
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[DEF]](<8 x s64>)
    ; AIE2P-NEXT: G_STORE [[UV]](<4 x s64>), [[COPY]](p0) :: (store (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV1]](<4 x s64>), [[PTR_ADD]](p0) :: (store (<4 x s64>) into unknown-address + 32)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s64>), %0(p0) :: (store (<8 x s64>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v32acc32
body:             |
  bb.1.entry:
    liveins:  $p0

    ; AIE2-LABEL: name: test_v32acc32
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<16 x s64>), [[COPY]](p0) :: (store (<16 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v32acc32
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[DEF]](<16 x s64>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<4 x s64>), [[UV3:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[UV]](<8 x s64>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<4 x s64>), [[UV5:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[UV1]](<8 x s64>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<4 x s64>), [[COPY]](p0) :: (store (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<4 x s64>), [[PTR_ADD]](p0) :: (store (<4 x s64>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<4 x s64>), [[PTR_ADD1]](p0) :: (store (<4 x s64>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<4 x s64>), [[PTR_ADD2]](p0) :: (store (<4 x s64>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s64>), %0(p0) :: (store (<16 x s64>), align 32)
    PseudoRET implicit $lr

...
---
name:            test_v16acc64
body:             |
  bb.1.entry:
    liveins:  $p0

    ; AIE2-LABEL: name: test_v16acc64
    ; AIE2: liveins: $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2-NEXT: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2-NEXT: G_STORE [[DEF]](<16 x s64>), [[COPY]](p0) :: (store (<16 x s64>), align 32)
    ; AIE2-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2P-LABEL: name: test_v16acc64
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[DEF]](<16 x s64>)
    ; AIE2P-NEXT: [[UV2:%[0-9]+]]:_(<4 x s64>), [[UV3:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[UV]](<8 x s64>)
    ; AIE2P-NEXT: [[UV4:%[0-9]+]]:_(<4 x s64>), [[UV5:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[UV1]](<8 x s64>)
    ; AIE2P-NEXT: G_STORE [[UV2]](<4 x s64>), [[COPY]](p0) :: (store (<4 x s64>))
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: G_STORE [[UV3]](<4 x s64>), [[PTR_ADD]](p0) :: (store (<4 x s64>) into unknown-address + 32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: G_STORE [[UV4]](<4 x s64>), [[PTR_ADD1]](p0) :: (store (<4 x s64>) into unknown-address + 64)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: G_STORE [[UV5]](<4 x s64>), [[PTR_ADD2]](p0) :: (store (<4 x s64>) into unknown-address + 96)
    ; AIE2P-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s64>), %0(p0) :: (store (<16 x s64>), align 32)
    PseudoRET implicit $lr

...
