# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_freeze_s1
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_s1
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[FREEZE]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s1) = G_TRUNC %0
    %2:_(s1) = G_FREEZE %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_freeze_s7
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_s7
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[FREEZE]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s7) = G_TRUNC %0
    %2:_(s7) = G_FREEZE %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_freeze_s8
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_s8
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[FREEZE]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s8) = G_TRUNC %0
    %2:_(s8) = G_FREEZE %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_freeze_s16
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[FREEZE]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_FREEZE %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_freeze_s32
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[FREEZE]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = G_FREEZE %0
    $r0 = COPY %1
...

---
name: test_freeze_s48
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_s48
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: [[FREEZE1:%[0-9]+]]:_(s32) = G_FREEZE [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[FREEZE]](s32)
    ; CHECK-NEXT: $r1 = COPY [[FREEZE1]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s64) = G_MERGE_VALUES %0(s32), %1(s32)
    %3:_(s48) = G_TRUNC %2
    %4:_(s48) = G_FREEZE %3
    %5:_(s64) = G_ANYEXT %4
    %6:_(s32), %7:_(s32) = G_UNMERGE_VALUES %5(s64)
    $r0 = COPY %6
    $r1 = COPY %7
...

---
name: test_freeze_s64
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r7
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: [[FREEZE1:%[0-9]+]]:_(s32) = G_FREEZE [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[FREEZE]](s32)
    ; CHECK-NEXT: $r1 = COPY [[FREEZE1]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s64) = G_MERGE_VALUES %0(s32), %1(s32)
    %3:_(s64) = G_FREEZE %2
    %4:_(s32), %5:_(s32) = G_UNMERGE_VALUES %3(s64)
    $r0 = COPY %4
    $r1 = COPY %5
...

---
name: test_freeze_p0
body: |
  bb.0:
    ; CHECK-LABEL: name: test_freeze_p0
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(p0) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $p0 = COPY [[FREEZE]](p0)
    %0:_(p0) = COPY $p0
    %1:_(p0) = G_FREEZE %0
    $p0 = COPY %1
...
