# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_constant_s32
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    %0:_(s32) = G_CONSTANT i32 5
    $r0 = COPY %0
...
---
name:            test_constant_s64
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s64
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[C1]](s32)
    %0:_(s64) = G_CONSTANT i64 5
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0
    $r0 = COPY %1
    $r0 = COPY %2

...

---
name:            test_constant_s1
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s1
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[C]](s32)
    %0:_(s1) = G_CONSTANT i1 0
    %1:_(s32) = G_ANYEXT %0
    PseudoRET implicit $lr, implicit %1
...

---
name:            test_constant_s7
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s7
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    %0:_(s7) = G_CONSTANT i7 5
    %1:_(s32) = G_ANYEXT %0
    $r0 = COPY %1
...

---
name:            test_constant_s8
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s8
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    %0:_(s8) = G_CONSTANT i8 5
    %1:_(s32) = G_ANYEXT %0
    $r0 = COPY %1
...

---
name:            test_constant_s16
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s16
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    %0:_(s16) = G_CONSTANT i16 5
    %1:_(s32) = G_ANYEXT %0
    $r0 = COPY %1
...

---
name: test_constant_p0
body: |
  bb.0:

    ; CHECK-LABEL: name: test_constant_p0
    ; CHECK: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
    ; CHECK-NEXT: $p0 = COPY [[C]](p0)
    %0:_(p0) = G_CONSTANT i20 0
    $p0 = COPY %0
...

---
name:            test_constant_s20
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s20
    ; CHECK: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY [[C]](s20)
    %0:_(s20) = G_CONSTANT i20 5
    %1:_(s20) = COPY %0
...

---
name:            test_constant_i20_to_p0
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_i20_to_p0
    ; CHECK: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY [[C]](p0)
    %0:_(p0) = G_CONSTANT i20 5
    %1:_(p0) = COPY %0
...
