# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_xor_v64s8
alignment:       16
body:             |
  bb.1:
    liveins: $x2, $x4

    ; CHECK-LABEL: name: test_xor_v64s8
    ; CHECK: liveins: $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x4
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<64 x s8>) = G_XOR [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[XOR]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<64 x s8>) = COPY $x2
    %2:_(<64 x s8>) = COPY $x4
    %0:_(<64 x s8>) = G_XOR %2, %1
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_xor_v32s16
alignment:       16
body:             |
  bb.1:
    liveins: $x2, $x4

    ; CHECK-LABEL: name: test_xor_v32s16
    ; CHECK: liveins: $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x4
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<32 x s16>) = G_XOR [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[XOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s16>) = COPY $x2
    %2:_(<32 x s16>) = COPY $x4
    %0:_(<32 x s16>) = G_XOR %2, %1
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            test_xor_v16s32
alignment:       16
body:             |
  bb.1:
    liveins: $x2, $x4

    ; CHECK-LABEL: name: test_xor_v16s32
    ; CHECK: liveins: $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x4
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<16 x s32>) = G_XOR [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[XOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s32>) = COPY $x2
    %2:_(<16 x s32>) = COPY $x4
    %0:_(<16 x s32>) = G_XOR %2, %1
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            test_xor_s8_1024
alignment:       16
body:             |
  bb.1:
    liveins: $y2, $y4

    ; CHECK-LABEL: name: test_xor_s8_1024
    ; CHECK: liveins: $y2, $y4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<128 x s8>) = COPY $y4
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY1]](<128 x s8>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<64 x s8>), [[UV3:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY]](<128 x s8>)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<64 x s8>) = G_XOR [[UV]], [[UV2]]
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(<64 x s8>) = G_XOR [[UV1]], [[UV3]]
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[XOR]](<64 x s8>), [[XOR1]](<64 x s8>)
    ; CHECK-NEXT: $y3 = COPY [[CONCAT_VECTORS]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y3
    %1:_(<128 x s8>) = COPY $y2
    %2:_(<128 x s8>) = COPY $y4
    %0:_(<128 x s8>) = G_XOR %2, %1
    $y3 = COPY %0(<128 x s8>)
    PseudoRET implicit $lr, implicit $y3

...

---
name:            test_xor_s8_256
alignment:       16
body:             |
  bb.1:
    liveins: $wh2, $wh4
    ; CHECK-LABEL: name: test_xor_s8_256
    ; CHECK: liveins: $wh2, $wh4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wh2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s8>) = COPY $wh4
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[COPY1]](<32 x s8>), [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[COPY]](<32 x s8>), [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<64 x s8>) = G_XOR [[CONCAT_VECTORS]], [[CONCAT_VECTORS1]]
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[XOR]](<64 x s8>)
    ; CHECK-NEXT: $wh0 = COPY [[UV]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wh0
    %1:_(<32 x s8>) = COPY $wh2
    %2:_(<32 x s8>) = COPY $wh4
    %0:_(<32 x s8>) = G_XOR %2, %1
    $wh0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wh0
...
---
name:            test_xor_s16_1024
alignment:       16
body:             |
  bb.1:
    liveins: $y2, $y4
    ; CHECK-LABEL: name: test_xor_s16_1024
    ; CHECK: liveins: $y2, $y4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s16>) = COPY $y4
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY1]](<64 x s16>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<32 x s16>), [[UV3:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY]](<64 x s16>)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<32 x s16>) = G_XOR [[UV]], [[UV2]]
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(<32 x s16>) = G_XOR [[UV1]], [[UV3]]
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[XOR]](<32 x s16>), [[XOR1]](<32 x s16>)
    ; CHECK-NEXT: $y3 = COPY [[CONCAT_VECTORS]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y3
    %1:_(<64 x s16>) = COPY $y2
    %2:_(<64 x s16>) = COPY $y4
    %0:_(<64 x s16>) = G_XOR %2, %1
    $y3 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y3

...
---
name:            test_xor_s16_256
alignment:       16
body:             |
  bb.1:
    liveins: $wh2, $wh4
    ; CHECK-LABEL: name: test_xor_s16_256
    ; CHECK: liveins: $wh2, $wh4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wh2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s16>) = COPY $wh4
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[COPY1]](<16 x s16>), [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[COPY]](<16 x s16>), [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<32 x s16>) = G_XOR [[CONCAT_VECTORS]], [[CONCAT_VECTORS1]]
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[XOR]](<32 x s16>)
    ; CHECK-NEXT: $wh0 = COPY [[UV]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wh0
    %1:_(<16 x s16>) = COPY $wh2
    %2:_(<16 x s16>) = COPY $wh4
    %0:_(<16 x s16>) = G_XOR %2, %1
    $wh0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wh0

...
---
name:            test_xor_s32_1024
alignment:       16
body:             |
  bb.1:
    liveins: $y2, $y4
    ; CHECK-LABEL: name: test_xor_s32_1024
    ; CHECK: liveins: $y2, $y4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $y4
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[COPY1]](<32 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<16 x s32>) = G_XOR [[UV]], [[UV2]]
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(<16 x s32>) = G_XOR [[UV1]], [[UV3]]
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[XOR]](<16 x s32>), [[XOR1]](<16 x s32>)
    ; CHECK-NEXT: $y3 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y3
    %1:_(<32 x s32>) = COPY $y2
    %2:_(<32 x s32>) = COPY $y4
    %0:_(<32 x s32>) = G_XOR %2, %1
    $y3 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $y3

...
---
name:            test_xor_s32_256
alignment:       16
body:             |
  bb.1:
    liveins: $wh2, $wh4
    ; CHECK-LABEL: name: test_xor_s32_256
    ; CHECK: liveins: $wh2, $wh4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY1]](<8 x s32>), [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<16 x s32>) = G_XOR [[CONCAT_VECTORS]], [[CONCAT_VECTORS1]]
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[XOR]](<16 x s32>)
    ; CHECK-NEXT: $wh0 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wh0
    %1:_(<8 x s32>) = COPY $wh2
    %2:_(<8 x s32>) = COPY $wh4
    %0:_(<8 x s32>) = G_XOR %2, %1
    $wh0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wh0

...
