# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            insert_v2i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l1, $r4

    ; CHECK-LABEL: name: insert_v2i32
    ; CHECK: liveins: $l1, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $l1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r4
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](<2 x s32>)
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[UV]](s32), [[COPY1]](s32)
    ; CHECK-NEXT: $l0 = COPY [[BUILD_VECTOR]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l0
    %1:_(<2 x s32>) = COPY $l1
    %2:_(s32) = COPY $r4
    %3:_(s32) = G_CONSTANT i32 1
    %0:_(<2 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $l0 = COPY %0(<2 x s32>)
    PseudoRET implicit $lr, implicit $l0

...
---
name:            insert_v2i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l1, $r4, $r5

    ; CHECK-LABEL: name: insert_v2i32_dyn
    ; CHECK: liveins: $l1, $r4, $r5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $l1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r4
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r5
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](<2 x s32>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[COPY2]](s32), [[UV]], [[COPY1]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[COPY2]](s32), [[COPY1]], [[UV1]]
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[SELECT]](s32), [[SELECT1]](s32)
    ; CHECK-NEXT: $l0 = COPY [[BUILD_VECTOR]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l0
    %1:_(<2 x s32>) = COPY $l1
    %2:_(s32) = COPY $r4
    %3:_(s32) = COPY $r5
    %0:_(<2 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $l0 = COPY %0(<2 x s32>)
    PseudoRET implicit $lr, implicit $l0

...
---
name:            insert_v32i8
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $wl2

    ; CHECK-LABEL: name: insert_v32i8
    ; CHECK: liveins: $r0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[COPY]](<32 x s8>), [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<64 x s8>) = G_AIE_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_INSERT_VECTOR_ELT]](<64 x s8>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<32 x s8>) = COPY $wl2
    %3:_(s32) = COPY $r0
    %2:_(s8) = G_TRUNC %3(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %0:_(<32 x s8>) = G_INSERT_VECTOR_ELT %1, %2(s8), %4(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            insert_v32i8_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $wl2

    ; CHECK-LABEL: name: insert_v32i8_dyn
    ; CHECK: liveins: $r0, $r1, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[COPY]](<32 x s8>), [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<64 x s8>) = G_AIE_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_INSERT_VECTOR_ELT]](<64 x s8>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<32 x s8>) = COPY $wl2
    %4:_(s32) = COPY $r0
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(s32) = COPY $r1
    %0:_(<32 x s8>) = G_INSERT_VECTOR_ELT %1, %2(s8), %3(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            insert_v16i16
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $wl2

    ; CHECK-LABEL: name: insert_v16i16
    ; CHECK: liveins: $r0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[COPY]](<16 x s16>), [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[AIE_INSERT_VECTOR_ELT]](<32 x s16>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s16>) = COPY $wl2
    %3:_(s32) = COPY $r0
    %2:_(s16) = G_TRUNC %3(s32)
    %4:_(s32) = G_CONSTANT i32 11
    %0:_(<16 x s16>) = G_INSERT_VECTOR_ELT %1, %2(s16), %4(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            insert_v16i16_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $wl2

    ; CHECK-LABEL: name: insert_v16i16_dyn
    ; CHECK: liveins: $r0, $r1, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[COPY]](<16 x s16>), [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[AIE_INSERT_VECTOR_ELT]](<32 x s16>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s16>) = COPY $wl2
    %4:_(s32) = COPY $r0
    %2:_(s16) = G_TRUNC %4(s32)
    %3:_(s32) = COPY $r1
    %0:_(<16 x s16>) = G_INSERT_VECTOR_ELT %1, %2(s16), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            insert_v8i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $wl2

    ; CHECK-LABEL: name: insert_v8i32
    ; CHECK: liveins: $r0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_INSERT_VECTOR_ELT]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<8 x s32>) = COPY $wl2
    %2:_(s32) = COPY $r0
    %3:_(s32) = G_CONSTANT i32 7
    %0:_(<8 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            insert_v8i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $wl2

    ; CHECK-LABEL: name: insert_v8i32_dyn
    ; CHECK: liveins: $r0, $r1, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_INSERT_VECTOR_ELT]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<8 x s32>) = COPY $wl2
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<8 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            insert_v64i8
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $x2

    ; CHECK-LABEL: name: insert_v64i8
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<64 x s8>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_INSERT_VECTOR_ELT]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<64 x s8>) = COPY $x2
    %3:_(s32) = COPY $r0
    %2:_(s8) = G_TRUNC %3(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %0:_(<64 x s8>) = G_INSERT_VECTOR_ELT %1, %2(s8), %4(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            insert_v64i8_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $x2

    ; CHECK-LABEL: name: insert_v64i8_dyn
    ; CHECK: liveins: $r0, $r1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<64 x s8>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_INSERT_VECTOR_ELT]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<64 x s8>) = COPY $x2
    %4:_(s32) = COPY $r0
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(s32) = COPY $r1
    %0:_(<64 x s8>) = G_INSERT_VECTOR_ELT %1, %2(s8), %3(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            insert_v32i16
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $x2

    ; CHECK-LABEL: name: insert_v32i16
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_INSERT_VECTOR_ELT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s16>) = COPY $x2
    %3:_(s32) = COPY $r0
    %2:_(s16) = G_TRUNC %3(s32)
    %4:_(s32) = G_CONSTANT i32 11
    %0:_(<32 x s16>) = G_INSERT_VECTOR_ELT %1, %2(s16), %4(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            insert_v32i16_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $x2

    ; CHECK-LABEL: name: insert_v32i16_dyn
    ; CHECK: liveins: $r0, $r1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_INSERT_VECTOR_ELT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s16>) = COPY $x2
    %4:_(s32) = COPY $r0
    %2:_(s16) = G_TRUNC %4(s32)
    %3:_(s32) = COPY $r1
    %0:_(<32 x s16>) = G_INSERT_VECTOR_ELT %1, %2(s16), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            insert_v16i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $x2

    ; CHECK-LABEL: name: insert_v16i32
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_INSERT_VECTOR_ELT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s32>) = COPY $x2
    %2:_(s32) = COPY $r0
    %3:_(s32) = G_CONSTANT i32 7
    %0:_(<16 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            insert_v16i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $x2

    ; CHECK-LABEL: name: insert_v16i32_dyn
    ; CHECK: liveins: $r0, $r1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_INSERT_VECTOR_ELT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s32>) = COPY $x2
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            insert_v128i8
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $y3

    ; CHECK-LABEL: name: insert_v128i8
    ; CHECK: liveins: $r0, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY]](<128 x s8>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<64 x s8>) = G_AIE_INSERT_VECTOR_ELT [[UV]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[AIE_INSERT_VECTOR_ELT]](<64 x s8>), [[UV1]](<64 x s8>)
    ; CHECK-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<128 x s8>) = COPY $y3
    %3:_(s32) = COPY $r0
    %2:_(s8) = G_TRUNC %3(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %0:_(<128 x s8>) = G_INSERT_VECTOR_ELT %1, %2(s8), %4(s32)
    $y2 = COPY %0(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            insert_v128i8_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $y3

    ; CHECK-LABEL: name: insert_v128i8_dyn
    ; CHECK: liveins: $r0, $r1, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: G_STORE [[COPY]](<128 x s8>), [[FRAME_INDEX]](p0) :: (store (<128 x s8>) into %stack.0)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 127
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[AND]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[MUL]], [[C2]](s32)
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C2]](s32)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ASHR]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[FRAME_INDEX]], [[TRUNC]](s20)
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[PTR_ADD]](p0) :: (store (s8))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<128 x s8>) = G_LOAD [[FRAME_INDEX]](p0) :: (load (<128 x s8>))
    ; CHECK-NEXT: $y2 = COPY [[LOAD]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<128 x s8>) = COPY $y3
    %4:_(s32) = COPY $r0
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(s32) = COPY $r1
    %0:_(<128 x s8>) = G_INSERT_VECTOR_ELT %1, %2(s8), %3(s32)
    $y2 = COPY %0(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            insert_v64i16
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $y3

    ; CHECK-LABEL: name: insert_v64i16
    ; CHECK: liveins: $r0, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY]](<64 x s16>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<32 x s16>) = G_AIE_INSERT_VECTOR_ELT [[UV]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[AIE_INSERT_VECTOR_ELT]](<32 x s16>), [[UV1]](<32 x s16>)
    ; CHECK-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<64 x s16>) = COPY $y3
    %3:_(s32) = COPY $r0
    %2:_(s16) = G_TRUNC %3(s32)
    %4:_(s32) = G_CONSTANT i32 11
    %0:_(<64 x s16>) = G_INSERT_VECTOR_ELT %1, %2(s16), %4(s32)
    $y2 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            insert_v64i16_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $y3

    ; CHECK-LABEL: name: insert_v64i16_dyn
    ; CHECK: liveins: $r0, $r1, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: G_STORE [[COPY]](<64 x s16>), [[FRAME_INDEX]](p0) :: (store (<64 x s16>) into %stack.0)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[AND]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[MUL]], [[C2]](s32)
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C2]](s32)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ASHR]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[FRAME_INDEX]], [[TRUNC]](s20)
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[PTR_ADD]](p0) :: (store (s16))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<64 x s16>) = G_LOAD [[FRAME_INDEX]](p0) :: (load (<64 x s16>))
    ; CHECK-NEXT: $y2 = COPY [[LOAD]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<64 x s16>) = COPY $y3
    %4:_(s32) = COPY $r0
    %2:_(s16) = G_TRUNC %4(s32)
    %3:_(s32) = COPY $r1
    %0:_(<64 x s16>) = G_INSERT_VECTOR_ELT %1, %2(s16), %3(s32)
    $y2 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            insert_v32i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $y3

    ; CHECK-LABEL: name: insert_v32i32
    ; CHECK: liveins: $r0, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<16 x s32>) = G_AIE_INSERT_VECTOR_ELT [[UV]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_INSERT_VECTOR_ELT]](<16 x s32>), [[UV1]](<16 x s32>)
    ; CHECK-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<32 x s32>) = COPY $y3
    %2:_(s32) = COPY $r0
    %3:_(s32) = G_CONSTANT i32 7
    %0:_(<32 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $y2 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            insert_v32i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0, $r1, $y3

    ; CHECK-LABEL: name: insert_v32i32_dyn
    ; CHECK: liveins: $r0, $r1, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: G_STORE [[COPY]](<32 x s32>), [[FRAME_INDEX]](p0) :: (store (<32 x s32>) into %stack.0)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[AND]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[MUL]], [[C2]](s32)
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C2]](s32)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[ASHR]](s32)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[FRAME_INDEX]], [[TRUNC]](s20)
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[PTR_ADD]](p0) :: (store (s32))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (load (<32 x s32>))
    ; CHECK-NEXT: $y2 = COPY [[LOAD]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<32 x s32>) = COPY $y3
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INSERT_VECTOR_ELT %1, %2(s32), %3(s32)
    $y2 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $y2

...
