# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            select_vec_256
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: select_vec_256
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY1]](<32 x s8>)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF1]](<32 x s8>), [[COPY2]](<32 x s8>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<64 x s8>) = G_SELECT [[AND]](s32), [[CONCAT_VECTORS]], [[CONCAT_VECTORS1]]
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[SELECT]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](<32 x s8>)
    %0:_(s32) = COPY $r0
    %1:_(s1) = G_TRUNC %0:_(s32)
    %2:_(<32 x s8>) = G_IMPLICIT_DEF
    %3:_(<32 x s8>) = G_IMPLICIT_DEF
    %4:_(<32 x s8>) = G_SELECT %1:_(s1), %2(<32 x s8>), %3(<32 x s8>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            select_vec_512
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: select_vec_512
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<64 x s8>) = G_SELECT [[AND]](s32), [[DEF]], [[DEF1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SELECT]](<64 x s8>)
    %0:_(s32) = COPY $r0
    %1:_(s1) = G_TRUNC %0:_(s32)
    %2:_(<64 x s8>) = G_IMPLICIT_DEF
    %3:_(<64 x s8>) = G_IMPLICIT_DEF
    %4:_(<64 x s8>) = G_SELECT %1:_(s1), %2(<64 x s8>), %3(<64 x s8>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            select_vec_1024
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: select_vec_1024
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[DEF]](<64 x s16>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<32 x s16>), [[UV3:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[DEF1]](<64 x s16>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<32 x s16>) = G_SELECT [[AND]](s32), [[UV]], [[UV2]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(<32 x s16>) = G_SELECT [[AND]](s32), [[UV1]], [[UV3]]
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[SELECT]](<32 x s16>), [[SELECT1]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s16>)
    %0:_(s32) = COPY $r0
    %1:_(s1) = G_TRUNC %0:_(s32)
    %2:_(<64 x s16>) = G_IMPLICIT_DEF
    %3:_(<64 x s16>) = G_IMPLICIT_DEF
    %4:_(<64 x s16>) = G_SELECT %1:_(s1), %2(<64 x s16>), %3(<64 x s16>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            select_acc_256
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: select_acc_256
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY1]](<4 x s64>)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF1]](<4 x s64>), [[COPY2]](<4 x s64>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[CONCAT_VECTORS]](<8 x s64>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[CONCAT_VECTORS1]](<8 x s64>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[AND]](s32), [[BITCAST]], [[BITCAST1]]
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[BITCAST2]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](<4 x s64>)
    %0:_(s32) = COPY $r0
    %1:_(s1) = G_TRUNC %0:_(s32)
    %2:_(<4 x s64>) = G_IMPLICIT_DEF
    %3:_(<4 x s64>) = G_IMPLICIT_DEF
    %4:_(<4 x s64>) = G_SELECT %1:_(s1), %2(<4 x s64>), %3(<4 x s64>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            select_acc_512
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: select_acc_512
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[DEF]](<8 x s64>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[DEF1]](<8 x s64>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[AND]](s32), [[BITCAST]], [[BITCAST1]]
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST2]](<8 x s64>)
    %0:_(s32) = COPY $r0
    %1:_(s1) = G_TRUNC %0:_(s32)
    %2:_(<8 x s64>) = G_IMPLICIT_DEF
    %3:_(<8 x s64>) = G_IMPLICIT_DEF
    %4:_(<8 x s64>) = G_SELECT %1:_(s1), %2(<8 x s64>), %3(<8 x s64>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            select_acc_1024
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: select_acc_1024
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[DEF]](<16 x s64>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[DEF1]](<16 x s64>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[BITCAST]](<32 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[BITCAST1]](<32 x s32>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[AND]](s32), [[UV]], [[UV2]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[AND]](s32), [[UV1]], [[UV3]]
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[SELECT]](<16 x s32>), [[SELECT1]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST2]](<16 x s64>)
    %0:_(s32) = COPY $r0
    %1:_(s1) = G_TRUNC %0:_(s32)
    %2:_(<16 x s64>) = G_IMPLICIT_DEF
    %3:_(<16 x s64>) = G_IMPLICIT_DEF
    %4:_(<16 x s64>) = G_SELECT %1:_(s1), %2(<16 x s64>), %3(<16 x s64>)
    PseudoRET implicit $lr, implicit %4
...


