# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -verify-machineinstrs -run-pass=aie-postlegalizer-custom-combiner -o - %s  | FileCheck %s

---
name:            test_sext_extract_from_broadcast
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: test_sext_extract_from_broadcast
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]](s32)
    %0:_(s32) = COPY $r0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(s32) = G_CONSTANT i32 5
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<16 x s32>), %2(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_zext_extract_from_broadcast
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: test_zext_extract_from_broadcast
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]](s32)
    %0:_(s32) = COPY $r0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %1(<16 x s32>), %2(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_broadcast_with_multiple_extracts
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: test_broadcast_with_multiple_extracts
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD]](s32), implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %0:_(s32) = COPY $r0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(s32) = G_CONSTANT i32 3
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<16 x s32>), %2(s32)
    %4:_(s32) = G_CONSTANT i32 7
    %5:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<16 x s32>), %4(s32)
    %6:_(s32) = G_ADD %3, %5
    PseudoRET implicit $lr, implicit %6, implicit %1
...

---
name:            test_s16_vector_extract_from_broadcast
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: test_s16_vector_extract_from_broadcast
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SEXT_INREG]](s32)
    %0:_(s32) = COPY $r0
    %1:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(s32) = G_CONSTANT i32 5
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    PseudoRET implicit $lr, implicit %3
...
---
name:            test_s16_vector_zext_extract_from_broadcast
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: test_s16_vector_zext_extract_from_broadcast
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AND]](s32)
    %0:_(s32) = COPY $r0
    %1:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(s32) = G_CONSTANT i32 5
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    PseudoRET implicit $lr, implicit %3
...
---
name:            test_s8_vector_sext_extract_from_broadcast
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: test_s8_vector_sext_extract_from_broadcast
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 8
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SEXT_INREG]](s32)
    %0:_(s32) = COPY $r0
    %1:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(s32) = G_CONSTANT i32 7
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<64 x s8>), %2(s32)
    PseudoRET implicit $lr, implicit %3
...
---
name:            test_s8_vector_zext_extract_from_broadcast
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: test_s8_vector_zext_extract_from_broadcast
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AND]](s32)
    %0:_(s32) = COPY $r0
    %1:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(s32) = G_CONSTANT i32 7
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %1(<64 x s8>), %2(s32)
    PseudoRET implicit $lr, implicit %3
...
