# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2p -run-pass=aie2p-postlegalizer-custom-combiner -verify-machineinstrs %s -o - | FileCheck %s


---
name:              VEXTBCST_ZEXT_CHAIN
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $r6
    ; CHECK-LABEL: name: VEXTBCST_ZEXT_CHAIN
    ; CHECK: liveins: $p0, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[LOAD]](<16 x s32>), [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[AIE_ZEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %ptr:_(p0) = COPY $p0
    %4:_(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %483:_(s32) = COPY $r6
    %484:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %483(s32)
    %485:_(s32) = G_ASSERT_SEXT %484, 16
    %486:_(s32) = G_ASSERT_ZEXT %485, 16
    %487:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %486(s32)
    PseudoRET implicit $lr, implicit %487
...

---
name:              VEXTBCST_SEXT_CHAIN
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $r6
    ; CHECK-LABEL: name: VEXTBCST_SEXT_CHAIN
    ; CHECK: liveins: $p0, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[LOAD]](<16 x s32>), [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %ptr:_(p0) = COPY $p0
    %4:_(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %483:_(s32) = COPY $r6
    %484:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %483(s32)
    %485:_(s32) = G_ASSERT_ZEXT %484, 16
    %486:_(s32) = G_ASSERT_SEXT %485, 16
    %487:_(s32) = G_ASSERT_ZEXT %486, 16
    %488:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %487(s32)
    PseudoRET implicit $lr, implicit %488
...
