# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner  %s -o - | FileCheck %s

---
name:              G_PHI_s20
legalized:         false
tracksRegLiveness: true
body:             |
  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)

    %0:_(p0) = G_CONSTANT i20 0
    %1:_(s20) = G_CONSTANT i20 0
    %2:_(s32) = G_CONSTANT i32 20
    %3:_(s32) = G_CONSTANT i32 0
    G_STORE %2(s32), %0(p0) :: (store (s32))

  bb.1:
    successors: %bb.1(0x80000000); %bb.1(100.00%)

    %4:_(s20) = G_PHI %2(s32), %bb.0, %9(s20), %bb.1
    %8:_(p0), %9:_(s20), %10:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2.add.3d), %0(p0), %1(s20), %1(s20), %1(s20), %1(s20), %4(s20), %1(s20), %1(s20)
    G_BR %bb.1
...

---
name:              G_PHI_s32
legalized:         false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: G_PHI_s32
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[C]](s32), %bb.0, %3(s32), %bb.1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nuw nsw G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   $r0 = COPY [[ADD]](s32)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)

    %1:_(s20) = G_CONSTANT i20 0
    %3:_(s32) = G_CONSTANT i32 10

  bb.1:
    successors: %bb.1(0x80000000); %bb.1(100.00%)

    %4:_(s32) = G_PHI %1(s20), %bb.0, %9(s32), %bb.1
    %9:_(s32) = nuw nsw G_ADD %4, %3
    $r0 = COPY %9
    G_BR %bb.1
...
