# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s  --check-prefix=AIE2P
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner  %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2PS

--- |
  @data = dso_local local_unnamed_addr global [2 x i32] [i32 10, i32 20], align 4

  define dso_local noundef i32 @_Z7getDatav() {
  entry:
    %0 = load i32, ptr getelementptr inbounds ([2 x i32], ptr @data, i20 0, i20 1), align 4
    ret i32 %0
  }
...
---
name:            _Z7getDatav
legalized:       false
body:             |
  bb.1.entry:
    ; AIE2-LABEL: name: _Z7getDatav
    ; AIE2: [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE target-flags(aie2-global) @data + 4
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[GV]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds ([2 x i32], ptr @data, i20 0, i20 1)`)
    ; AIE2-NEXT: $r0 = COPY [[LOAD]](s32)
    ; AIE2-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2P-LABEL: name: _Z7getDatav
    ; AIE2P: [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE target-flags(aie2p-global) @data + 4
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[GV]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds ([2 x i32], ptr @data, i20 0, i20 1)`)
    ; AIE2P-NEXT: $r0 = COPY [[LOAD]](s32)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; AIE2PS-LABEL: name: _Z7getDatav
    ; AIE2PS: [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE target-flags(aie2ps-global) @data + 4
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[GV]](p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds ([2 x i32], ptr @data, i20 0, i20 1)`)
    ; AIE2PS-NEXT: $r0 = COPY [[LOAD]](s32)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(p0) = G_GLOBAL_VALUE @data
    %3:_(s20) = G_CONSTANT i20 4
    %1:_(p0) = G_PTR_ADD %2, %3(s20)
    %0:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from `ptr getelementptr inbounds ([2 x i32], ptr @data, i20 0, i20 1)`)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
