# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s

# Tests for combine_alternating_build_vector.
#
# Supported patterns:
#   2 x s8  -> s16  (packed into i16, broadcast into <N/2  x s16>)
#   4 x s8  -> s32  (packed into i32, broadcast into <N/4  x s32>)
#   2 x s16 -> s32  (packed into i32, broadcast into <N/2  x s32>)

# ---------------------------------------------------------------------------- #
# 2 x s8 patterns
# ---------------------------------------------------------------------------- #

---
name:            alternating_2xs8_v64i8
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: alternating_2xs8_v64i8
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: $x0 = COPY [[BITCAST]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(s8) = G_CONSTANT i8 1
    %1:_(s8) = G_CONSTANT i8 0
    %2:_(<64 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8)
    $x0 = COPY %2(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            alternating_2xs8_v32i8
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: alternating_2xs8_v32i8
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s8>) = G_BITCAST [[AIE_UNPAD_VECTOR]](<16 x s16>)
    ; CHECK-NEXT: $wl0 = COPY [[BITCAST]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(s8) = G_CONSTANT i8 1
    %1:_(s8) = G_CONSTANT i8 0
    %2:_(<32 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8)
    $wl0 = COPY %2(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...

---
name:            alternating_2xs8_v16i8
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: alternating_2xs8_v16i8
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s8>) = G_BITCAST [[AIE_UNPAD_VECTOR]](<8 x s16>)
    ; CHECK-NEXT: %idx:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[BITCAST]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), %idx(s32)
    ; CHECK-NEXT: %ext:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY %ext(s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s8) = G_CONSTANT i8 1
    %1:_(s8) = G_CONSTANT i8 0
    %2:_(<16 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8)
    %idx:_(s32) = G_CONSTANT i32 0
    %elt:_(s8) = G_EXTRACT_VECTOR_ELT %2(<16 x s8>), %idx(s32)
    %ext:_(s32) = G_ZEXT %elt(s8)
    $r0 = COPY %ext(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            alternating_2xs8_v64i8_noncst
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: alternating_2xs8_v64i8_noncst
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %tmp0:_(s32) = COPY $r0
    ; CHECK-NEXT: %tmp1:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC %tmp0(s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC %tmp1(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 8
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s16) = G_ANYEXT [[TRUNC1]](s8)
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s16) = G_SHL [[ANYEXT]], [[C]](s16)
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s16) = G_ZEXT [[TRUNC]](s8)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s16) = G_OR [[SHL]], [[ZEXT]]
    ; CHECK-NEXT: [[ANYEXT1:%[0-9]+]]:_(s32) = G_ANYEXT [[OR]](s16)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[ANYEXT1]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: $x0 = COPY [[BITCAST]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %tmp0:_(s32) = COPY $r0
    %tmp1:_(s32) = COPY $r1
    %0:_(s8) = G_TRUNC %tmp0(s32)
    %1:_(s8) = G_TRUNC %tmp1(s32)
    %2:_(<64 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8)
    $x0 = COPY %2(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...

# ---------------------------------------------------------------------------- #
# 4 x s8 patterns
# ---------------------------------------------------------------------------- #

# --- 4 x s8: <64 x s8> (512-bit) with constants ---
# Packed = 1 | (2 << 8) | (3 << 16) | (4 << 24) = 0x04030201 = 67305985
---
name:            alternating_4xs8_v64i8
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: alternating_4xs8_v64i8
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 67305985
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[BITCAST]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(s8) = G_CONSTANT i8 1
    %1:_(s8) = G_CONSTANT i8 2
    %2:_(s8) = G_CONSTANT i8 3
    %3:_(s8) = G_CONSTANT i8 4
    %4:_(<64 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8)
    $x0 = COPY %4(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...

# --- 4 x s8: non-constant arbitrary values in <64 x s8> ---
---
name:            alternating_4xs8_v64i8_noncst
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $r2, $r3
    ; CHECK-LABEL: name: alternating_4xs8_v64i8_noncst
    ; CHECK: liveins: $r0, $r1, $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %tmp0:_(s32) = COPY $r0
    ; CHECK-NEXT: %tmp1:_(s32) = COPY $r1
    ; CHECK-NEXT: %tmp2:_(s32) = COPY $r2
    ; CHECK-NEXT: %tmp3:_(s32) = COPY $r3
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC %tmp0(s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC %tmp1(s32)
    ; CHECK-NEXT: [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC %tmp2(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[TRUNC2]](s8)
    ; CHECK-NEXT: [[ZEXT1:%[0-9]+]]:_(s32) = G_ZEXT [[TRUNC1]](s8)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL %tmp3, [[C2]](s32)
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[ZEXT]], [[C1]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[SHL1]]
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[ZEXT1]], [[C]](s32)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[OR]], [[SHL2]]
    ; CHECK-NEXT: [[ZEXT2:%[0-9]+]]:_(s32) = G_ZEXT [[TRUNC]](s8)
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[OR1]], [[ZEXT2]]
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[OR2]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[BITCAST]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %tmp0:_(s32) = COPY $r0
    %tmp1:_(s32) = COPY $r1
    %tmp2:_(s32) = COPY $r2
    %tmp3:_(s32) = COPY $r3
    %0:_(s8) = G_TRUNC %tmp0(s32)
    %1:_(s8) = G_TRUNC %tmp1(s32)
    %2:_(s8) = G_TRUNC %tmp2(s32)
    %3:_(s8) = G_TRUNC %tmp3(s32)
    %4:_(<64 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8), %0(s8), %1(s8), %2(s8), %3(s8)
    $x0 = COPY %4(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...

# ---------------------------------------------------------------------------- #
# 2 x s16 patterns
# ---------------------------------------------------------------------------- #

# --- 2 x s16: <32 x s16> (512-bit) with constants ---
# Packed = 1 | (2 << 16) = 0x00020001 = 131073
---
name:            alternating_2xs16_v32i16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: alternating_2xs16_v32i16
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 131073
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[BITCAST]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(s16) = G_CONSTANT i16 1
    %1:_(s16) = G_CONSTANT i16 2
    %2:_(<32 x s16>) = G_BUILD_VECTOR %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16)
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...

# --- 2 x s16: <16 x s16> (256-bit) with constants ---
---
name:            alternating_2xs16_v16i16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: alternating_2xs16_v16i16
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 131073
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s16>) = G_BITCAST [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[BITCAST]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(s16) = G_CONSTANT i16 1
    %1:_(s16) = G_CONSTANT i16 2
    %2:_(<16 x s16>) = G_BUILD_VECTOR %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16)
    $wl0 = COPY %2(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...

# --- 2 x s16: <8 x s16> (128-bit, minimum size); result extracted to scalar ---
---
name:            alternating_2xs16_v8i16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: alternating_2xs16_v8i16
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 131073
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s16>) = G_BITCAST [[AIE_UNPAD_VECTOR]](<4 x s32>)
    ; CHECK-NEXT: %idx:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[BITCAST]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), %idx(s32)
    ; CHECK-NEXT: %ext:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY %ext(s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s16) = G_CONSTANT i16 1
    %1:_(s16) = G_CONSTANT i16 2
    %2:_(<8 x s16>) = G_BUILD_VECTOR %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16)
    %idx:_(s32) = G_CONSTANT i32 0
    %elt:_(s16) = G_EXTRACT_VECTOR_ELT %2(<8 x s16>), %idx(s32)
    %ext:_(s32) = G_ZEXT %elt(s16)
    $r0 = COPY %ext(s32)
    PseudoRET implicit $lr, implicit $r0

...

# --- 2 x s16: non-constant arbitrary values in <32 x s16> ---
---
name:            alternating_2xs16_v32i16_noncst
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: alternating_2xs16_v32i16_noncst
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %tmp0:_(s32) = COPY $r0
    ; CHECK-NEXT: %tmp1:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC %tmp0(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL %tmp1, [[C]](s32)
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[TRUNC]](s16)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[SHL]], [[ZEXT]]
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[OR]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[BITCAST]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %tmp0:_(s32) = COPY $r0
    %tmp1:_(s32) = COPY $r1
    %0:_(s16) = G_TRUNC %tmp0(s32)
    %1:_(s16) = G_TRUNC %tmp1(s32)
    %2:_(<32 x s16>) = G_BUILD_VECTOR %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16), %0(s16), %1(s16)
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...

# ---------------------------------------------------------------------------- #
# Negative tests: the combine should NOT fire
# ---------------------------------------------------------------------------- #

# --- Negative: <8 x s8> (64-bit) is below the 128-bit minimum ---
---
name:            no_combine_v8i8_too_small
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: no_combine_v8i8_too_small
    ; CHECK: [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s8>) = G_BUILD_VECTOR [[C]](s8), [[C1]](s8), [[C]](s8), [[C1]](s8), [[C]](s8), [[C1]](s8), [[C]](s8), [[C1]](s8)
    ; CHECK-NEXT: $l0 = COPY [[BUILD_VECTOR]](<8 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l0
    %0:_(s8) = G_CONSTANT i8 1
    %1:_(s8) = G_CONSTANT i8 0
    %2:_(<8 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8), %0(s8), %1(s8)
    $l0 = COPY %2(<8 x s8>)
    PseudoRET implicit $lr, implicit $l0

...

# --- Negative: <64 x s8> all-same (pure splat); matchSplatVector fires instead ---
---
name:            no_combine_v64i8_splat
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: no_combine_v64i8_splat
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_BROADCAST_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(s8) = G_CONSTANT i8 42
    %1:_(<64 x s8>) = G_BUILD_VECTOR %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8), %0(s8)
    $x0 = COPY %1(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...

# --- Negative: <64 x s8> period=3 pattern (unsupported, no clean period-2/4) ---
---
name:            no_combine_v64i8_non_periodic
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $r2
    ; CHECK-LABEL: name: no_combine_v64i8_non_periodic
    ; CHECK: liveins: $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %tmp0:_(s32) = COPY $r0
    ; CHECK-NEXT: %tmp1:_(s32) = COPY $r1
    ; CHECK-NEXT: %tmp2:_(s32) = COPY $r2
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC %tmp0(s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC %tmp1(s32)
    ; CHECK-NEXT: [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC %tmp2(s32)
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_BUILD_VECTOR [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC]](s8)
    ; CHECK-NEXT: $x0 = COPY [[BUILD_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %tmp0:_(s32) = COPY $r0
    %tmp1:_(s32) = COPY $r1
    %tmp2:_(s32) = COPY $r2
    %0:_(s8) = G_TRUNC %tmp0(s32)
    %1:_(s8) = G_TRUNC %tmp1(s32)
    %2:_(s8) = G_TRUNC %tmp2(s32)
    %3:_(<64 x s8>) = G_BUILD_VECTOR %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8), %1(s8), %2(s8), %0(s8)
    $x0 = COPY %3(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
