# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner  %s -verify-machineinstrs -o - | FileCheck %s

...

# Only one Src Node (G_LOAD) for G_PTR_ADD that is narrowed to S20 type, intermediate G_TRUNC is removed
---
name:            G_LOAD
legalized:       false
body:             |
  ; CHECK-LABEL: name: G_LOAD
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[C]](p0) :: (load (s20), align 4)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[LOAD]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000); %bb.2(100.00%)
    liveins: $p0
    %0:_(p0) = COPY $p0
    %2:_(p0) = G_CONSTANT i20 0
    %7:_(s32) = G_CONSTANT i32 0
    %1:_(s32) = G_LOAD %2:_(p0) :: (load (s32))

  bb.2:
    successors: %bb.2(0x80000000); %bb.2(100.00%)

    %3:_(s20) = G_TRUNC %1:_(s32)
    %4:_(p0) = G_PTR_ADD %0:_, %3:_(s20)
    G_STORE %7:_(s32), %4:_(p0) :: (store (s32))
    G_BR %bb.2
...


# Only one Src Node (G_LOAD) for G_PTR_ADD. Multiple use of G_LOAD one of which is G_ADD which is legal for s32 type only. Optimization is rejected for this case
---
name:            G_LOAD_Multiple_Use_Neg_ADD
legalized:       false
body:             |
  ; CHECK-LABEL: name: G_LOAD_Multiple_Use_Neg_ADD
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 100
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[C]](p0) :: (load (s32))
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[LOAD]], [[C1]]
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), %5(p0) :: (store (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[LOAD]](s32)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000); %bb.2(100.00%)
    liveins: $p0
    %0:_(p0) = COPY $p0
    %2:_(p0) = G_CONSTANT i20 0
    %7:_(s32) = G_CONSTANT i32 100
    %1:_(s32) = G_LOAD %2:_(p0) :: (load (s32))
    %8:_(s32) = G_ADD %1:_(s32), %7:_(s32)
    G_STORE %8:_(s32), %4:_(p0) :: (store (s32))

  bb.2:
    successors: %bb.2(0x80000000); %bb.2(100.00%)

    %3:_(s20) = G_TRUNC %1:_(s32)
    %4:_(p0) = G_PTR_ADD %0:_, %3:_(s20)
    G_STORE %7:_(s32), %4:_(p0) :: (store (s32))
    G_BR %bb.2
...

# Only one Src Node (G_LOAD) for G_PTR_ADD. Multiple use of G_LOAD in G_STORE & G_PTR_ADD
---
name:            G_LOAD_Multiple_Use_PTR_ADD_and_G_STORE
legalized:       false
body:             |
  ; CHECK-LABEL: name: G_LOAD_Multiple_Use_PTR_ADD_and_G_STORE
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 100
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[C]](p0) :: (load (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[LOAD]](s32)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_STORE [[LOAD]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000); %bb.2(100.00%)
    liveins: $p0
    %0:_(p0) = COPY $p0
    %2:_(p0) = G_CONSTANT i20 0
    %7:_(s32) = G_CONSTANT i32 100
    %1:_(s32) = G_LOAD %2:_(p0) :: (load (s32))

  bb.2:
    successors: %bb.2(0x80000000); %bb.2(100.00%)

    %3:_(s20) = G_TRUNC %1:_(s32)
    %4:_(p0) = G_PTR_ADD %0:_, %3:_(s20)
    G_STORE %7:_(s32), %4:_(p0) :: (store (s32))
    G_STORE %1:_(s32), %4:_(p0) :: (store (s32))
    G_BR %bb.2
...

# Only one Src Node (G_LOAD) for G_PTR_ADD. Multiple use of G_LOAD one of which is G_SELECT which is legal for s32 type only. Optimization is rejected for this case
---
name:            G_LOAD_Multiple_Use_Neg_SELECT
legalized:       false
body:             |
  ; CHECK-LABEL: name: G_LOAD_Multiple_Use_Neg_SELECT
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY1]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 100
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[C]](p0) :: (load (s32))
  ; CHECK-NEXT:   [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[TRUNC]](s1), [[LOAD]], [[C1]]
  ; CHECK-NEXT:   G_STORE [[SELECT]](s32), %7(p0) :: (store (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s20) = G_TRUNC [[LOAD]](s32)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[TRUNC1]](s20)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[PTR_ADD]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000); %bb.2(100.00%)
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %9:_(s32) = COPY $r0
    %10:_(s1) = G_TRUNC %9:_(s32)
    %2:_(p0) = G_CONSTANT i20 0
    %7:_(s32) = G_CONSTANT i32 100
    %1:_(s32) = G_LOAD %2:_(p0) :: (load (s32))
    %8:_(s32) = G_SELECT %10:_(s1), %1:_(s32), %7:_(s32)
    G_STORE %8:_(s32), %4:_(p0) :: (store (s32))

  bb.2:
    successors: %bb.2(0x80000000); %bb.2(100.00%)

    %3:_(s20) = G_TRUNC %1:_(s32)
    %4:_(p0) = G_PTR_ADD %0:_, %3:_(s20)
    G_STORE %7:_(s32), %4:_(p0) :: (store (s32))
    G_BR %bb.2
...

# Here G_SUB is non native consumer s20, however its consumes an operand that fits in s20.
---
name:              G_PHI_G_CONSTANT_s20
legalized:         false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: G_PHI_G_CONSTANT_s20
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   G_STORE [[C2]](s32), [[C]](p0) :: (store (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s20) = G_PHI [[C3]](s20), %bb.0, %9(s20), %bb.1
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[PHI]](s20)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[C4]], [[ZEXT]]
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p0), [[INT1:%[0-9]+]]:_(s20), [[INT2:%[0-9]+]]:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2.add.3d), [[C]](p0), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[PHI]](s20), [[C1]](s20), [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[INT]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_BR %bb.1
  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    %0:_(p0) = G_CONSTANT i20 0
    %1:_(s20) = G_CONSTANT i20 0
    %2:_(s32) = G_CONSTANT i32 20
    %3:_(s32) = G_CONSTANT i32 0
    G_STORE %2(s32), %0(p0) :: (store (s32))
  bb.1:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    %4:_(s32) = G_PHI %2(s32), %bb.0, %5(s32), %bb.1
    %7:_(s20) = G_TRUNC %4(s32)
    %6:_(s32) = nsw G_SUB %3, %4
    %8:_(p0), %9:_(s20), %10:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2.add.3d), %0(p0), %1(s20), %1(s20), %1(s20), %1(s20), %7(s20), %1(s20), %1(s20)
    G_STORE %6(s32), %8(p0) :: (store (s32))
    %5:_(s32) = G_ZEXT %9(s20)
    G_BR %bb.1
...

# Negative test case: G_CONSTANT value cannot fit in s20 register
---
name:              neg_G_PHI_G_CONSTANT_s20
legalized:         false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: neg_G_PHI_G_CONSTANT_s20
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1048577
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   G_STORE [[C2]](s32), [[C]](p0) :: (store (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[C2]](s32), %bb.0, %5(s32), %bb.1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[PHI]](s32)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[C3]], [[PHI]]
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p0), [[INT1:%[0-9]+]]:_(s20), [[INT2:%[0-9]+]]:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2.add.3d), [[C]](p0), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[TRUNC]](s20), [[C1]](s20), [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[INT]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[INT1]](s20)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    %0:_(p0) = G_CONSTANT i20 0
    %1:_(s20) = G_CONSTANT i20 0
    %2:_(s32) = G_CONSTANT i32 1048577
    %3:_(s32) = G_CONSTANT i32 0
    G_STORE %2(s32), %0(p0) :: (store (s32))
  bb.1:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    %4:_(s32) = G_PHI %2(s32), %bb.0, %5(s32), %bb.1
    %7:_(s20) = G_TRUNC %4(s32)
    %6:_(s32) = nsw G_SUB %3, %4
    %8:_(p0), %9:_(s20), %10:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2.add.3d), %0(p0), %1(s20), %1(s20), %1(s20), %1(s20), %7(s20), %1(s20), %1(s20)
    G_STORE %6(s32), %8(p0) :: (store (s32))
    %5:_(s32) = G_ZEXT %9(s20)
    G_BR %bb.1
...
