# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner -global-isel -verify-machineinstrs %s -o - | FileCheck %s

# This should test the implementation of AIEBaseInstrInfo::isExtendLikelyToBeFolded
# Check that we block the propagation the G_ZEXT to the sources of the phi operand with s20 type.
---
name:            block_zext_icst_through_phi
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: block_zext_icst_through_phi
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   %one:_(s32) = G_CONSTANT i32 2
  ; CHECK-NEXT:   %cmp:_(s1) = G_ICMP intpred(sle), [[COPY]](s32), %one
  ; CHECK-NEXT:   G_BRCOND %cmp(s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cst20_4:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cst20_10:_(s20) = G_CONSTANT i20 10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   %phi:_(s20) = G_PHI %cst20_4(s20), %bb.1, %cst20_10(s20), %bb.2
  ; CHECK-NEXT:   %ext:_(s32) = G_ZEXT %phi(s20)
  ; CHECK-NEXT:   $r0 = COPY %ext(s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  bb.1.entry:
    liveins: $r0, $r1

    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %one:_(s32) = G_CONSTANT i32 2
    %cmp:_(s1) = G_ICMP intpred(sgt), %0(s32), %one
    G_BRCOND %cmp(s1), %bb.2
    G_BR %bb.3

  bb.2:
    %cst20_4:_(s20) = G_CONSTANT i20 4
    G_BR %bb.4

  bb.3:
    %cst20_10:_(s20) = G_CONSTANT i20 10

  bb.4:
    %phi:_(s20) = G_PHI %cst20_4(s20), %bb.2, %cst20_10(s20), %bb.3
    %ext:_(s32) = G_ZEXT %phi
    $r0 = COPY %ext(s32)
    PseudoRET implicit $lr, implicit $r0
...

# Check that we allow the propagation the G_SEXT to the sources of the phi operand with s20 type.
---
name:            allow_sext_icst_through_phi
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: allow_sext_icst_through_phi
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   %one:_(s32) = G_CONSTANT i32 2
  ; CHECK-NEXT:   %cmp:_(s1) = G_ICMP intpred(sle), [[COPY]](s32), %one
  ; CHECK-NEXT:   G_BRCOND %cmp(s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   %ext:_(s32) = G_PHI [[C]](s32), %bb.1, [[C1]](s32), %bb.2
  ; CHECK-NEXT:   $r0 = COPY %ext(s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  bb.1.entry:
    liveins: $r0, $r1

    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %one:_(s32) = G_CONSTANT i32 2
    %cmp:_(s1) = G_ICMP intpred(sgt), %0(s32), %one
    G_BRCOND %cmp(s1), %bb.2
    G_BR %bb.3

  bb.2:
    %cst20_4:_(s20) = G_CONSTANT i20 4
    G_BR %bb.4

  bb.3:
    %cst20_10:_(s20) = G_CONSTANT i20 10

  bb.4:
    %phi:_(s20) = G_PHI %cst20_4(s20), %bb.2, %cst20_10(s20), %bb.3
    %ext:_(s32) = G_SEXT %phi
    $r0 = COPY %ext(s32)
    PseudoRET implicit $lr, implicit $r0
...
