# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie2-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie2ps-prelegalizer-combiner  %s -verify-machineinstrs -o - | FileCheck %s

---
name:            extract_v8i8_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: extract_v8i8_signext
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s8) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[EVEC]](s8)
    ; CHECK-NEXT: $r0 = COPY [[SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<8 x s8>) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 1
    %0:_(s8) = G_EXTRACT_VECTOR_ELT %1(<8 x s8>), %2(s32)
    %5:_(s32) = G_SEXT %0(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v8i8_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: extract_v8i8_zeroext
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s8) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[EVEC]](s8)
    ; CHECK-NEXT: $r0 = COPY [[SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<8 x s8>) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 1
    %0:_(s8) = G_EXTRACT_VECTOR_ELT %1(<8 x s8>), %2(s32)
    %5:_(s32) = G_SEXT %0(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v8i8_dyn
alignment:       16
body:             |
  bb.1.entry:
    liveins: $l0, $r1
    ; CHECK-LABEL: name: extract_v8i8_dyn
    ; CHECK: liveins: $l0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s8) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s8>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[EVEC]](s8)
    ; CHECK-NEXT: $r0 = COPY [[ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<8 x s8>) = COPY $l0
    %2:_(s32) = COPY $r1
    %0:_(s8) = G_EXTRACT_VECTOR_ELT %1(<8 x s8>), %2(s32)
    %5:_(s32) = G_ZEXT %0(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v4i16_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: extract_v4i16_signext
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s16>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[EVEC]](s16)
    ; CHECK-NEXT: $r0 = COPY [[SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<4 x s16>) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 1
    %0:_(s16) = G_EXTRACT_VECTOR_ELT %1(<4 x s16>), %2(s32)
    %5:_(s32) = G_SEXT %0(s16)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v4i16_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: extract_v4i16_zeroext
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s16>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[EVEC]](s16)
    ; CHECK-NEXT: $r0 = COPY [[SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<4 x s16>) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 1
    %0:_(s16) = G_EXTRACT_VECTOR_ELT %1(<4 x s16>), %2(s32)
    %5:_(s32) = G_SEXT %0(s16)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v4i16_dyn
alignment:       16
body:             |
  bb.1.entry:
    liveins: $l0, $r1
    ; CHECK-LABEL: name: extract_v4i16_dyn
    ; CHECK: liveins: $l0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s16>) = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s16>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[EVEC]](s16)
    ; CHECK-NEXT: $r0 = COPY [[ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<4 x s16>) = COPY $l0
    %2:_(s32) = COPY $r1
    %0:_(s16) = G_EXTRACT_VECTOR_ELT %1(<4 x s16>), %2(s32)
    %5:_(s32) = G_ZEXT %0(s16)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v2i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $l0

    ; CHECK-LABEL: name: extract_v2i32
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<2 x s32>) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<2 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v2i32_dyn
alignment:       16
body:             |
  bb.1.entry:
    liveins: $l0, $r1

    ; CHECK-LABEL: name: extract_v2i32_dyn
    ; CHECK: liveins: $l0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<2 x s32>) = COPY $l0
    %2:_(s32) = COPY $r1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<2 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v16i8_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v16i8_signext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_AIE_UNPAD_VECTOR [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(<32 x s8>) = COPY $wl0
    %1:_(<16 x s8>), %3:_(<16 x s8>) = G_UNMERGE_VALUES %2(<32 x s8>)
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(s8) = G_EXTRACT_VECTOR_ELT %1(<16 x s8>), %4(s32)
    %5:_(s32) = G_SEXT %0(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            extract_v16i8_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v16i8_zeroext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_AIE_UNPAD_VECTOR [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(<32 x s8>) = COPY $wl0
    %1:_(<16 x s8>), %3:_(<16 x s8>) = G_UNMERGE_VALUES %2(<32 x s8>)
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(s8) = G_EXTRACT_VECTOR_ELT %1(<16 x s8>), %4(s32)
    %5:_(s32) = G_ZEXT %0(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            extract_v16i8_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r1, $wl0

    ; CHECK-LABEL: name: extract_v16i8_dyn
    ; CHECK: liveins: $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_AIE_UNPAD_VECTOR [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %3:_(<32 x s8>) = COPY $wl0
    %1:_(<16 x s8>), %4:_(<16 x s8>) = G_UNMERGE_VALUES %3(<32 x s8>)
    %2:_(s32) = COPY $r1
    %0:_(s8) = G_EXTRACT_VECTOR_ELT %1(<16 x s8>), %2(s32)
    %5:_(s32) = G_ZEXT %0(s8)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            extract_v8i16_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v8i16_signext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s16>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(<16 x s16>) = COPY $wl0
    %1:_(<8 x s16>), %3:_(<8 x s16>) = G_UNMERGE_VALUES %2(<16 x s16>)
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(s16) = G_EXTRACT_VECTOR_ELT %1(<8 x s16>), %4(s32)
    %5:_(s32) = G_SEXT %0(s16)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            extract_v8i16_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v8i16_zeroext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s16>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(<16 x s16>) = COPY $wl0
    %1:_(<8 x s16>), %3:_(<8 x s16>) = G_UNMERGE_VALUES %2(<16 x s16>)
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(s16) = G_EXTRACT_VECTOR_ELT %1(<8 x s16>), %4(s32)
    %5:_(s32) = G_ZEXT %0(s16)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            extract_v8i16_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r1, $wl0

    ; CHECK-LABEL: name: extract_v8i16_dyn
    ; CHECK: liveins: $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s16>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %3:_(<16 x s16>) = COPY $wl0
    %1:_(<8 x s16>), %4:_(<8 x s16>) = G_UNMERGE_VALUES %3(<16 x s16>)
    %2:_(s32) = COPY $r1
    %0:_(s16) = G_EXTRACT_VECTOR_ELT %1(<8 x s16>), %2(s32)
    %5:_(s32) = G_SEXT %0(s16)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            extract_v4i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v4i32
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_UNPAD_VECTOR]](<4 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(<8 x s32>) = COPY $wl0
    %1:_(<4 x s32>), %3:_(<4 x s32>) = G_UNMERGE_VALUES %2(<8 x s32>)
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<4 x s32>), %4(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            extract_v4i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r1, $wl0

    ; CHECK-LABEL: name: extract_v4i32_dyn
    ; CHECK: liveins: $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_UNPAD_VECTOR]](<4 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %3:_(<8 x s32>) = COPY $wl0
    %1:_(<4 x s32>), %4:_(<4 x s32>) = G_UNMERGE_VALUES %3(<8 x s32>)
    %2:_(s32) = COPY $r1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<4 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i8_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v32i8_signext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s8>) = COPY $wl0
    %2:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<32 x s8>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i8_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v32i8_zeroext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s8>) = COPY $wl0
    %2:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<32 x s8>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i8_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $wl0

    ; CHECK-LABEL: name: extract_v32i8_dyn
    ; CHECK: liveins: $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s8>) = COPY $wl0
    %2:_(s32) = COPY $r1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<32 x s8>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v16i16_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v16i16_signext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = G_CONSTANT i32 11
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<16 x s16>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v16i16_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v16i16_zeroext
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = G_CONSTANT i32 11
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<16 x s16>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v16i16_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $wl0

    ; CHECK-LABEL: name: extract_v16i16_dyn
    ; CHECK: liveins: $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = COPY $r1
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<16 x s16>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v8i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: extract_v8i32
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<8 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v8i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $wl0

    ; CHECK-LABEL: name: extract_v8i32_dyn
    ; CHECK: liveins: $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(s32) = COPY $r1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<8 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i8_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: extract_v64i8_signext
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<64 x s8>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i8_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: extract_v64i8_zeroext
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[COPY]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<64 x s8>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i8_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $x0

    ; CHECK-LABEL: name: extract_v64i8_dyn
    ; CHECK: liveins: $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<64 x s8>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(s32) = COPY $r1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<64 x s8>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i16_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: extract_v32i16_signext
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = G_CONSTANT i32 11
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i16_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: extract_v32i16_zeroext
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = G_CONSTANT i32 11
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i16_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $x0

    ; CHECK-LABEL: name: extract_v32i16_dyn
    ; CHECK: liveins: $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[COPY1]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r1
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<32 x s16>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v16i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: extract_v16i32
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<16 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v16i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $x0

    ; CHECK-LABEL: name: extract_v16i32_dyn
    ; CHECK: liveins: $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(s32) = COPY $r1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<16 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v128i8_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y2

    ; CHECK-LABEL: name: extract_v128i8_signext
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY]](<128 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<128 x s8>) = COPY $y2
    %2:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<128 x s8>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v128i8_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y2

    ; CHECK-LABEL: name: extract_v128i8_zeroext
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY]](<128 x s8>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<128 x s8>) = COPY $y2
    %2:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<128 x s8>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v128i8_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $y2

    ; CHECK-LABEL: name: extract_v128i8_dyn
    ; CHECK: liveins: $r1, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY]](<128 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 64
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(slt), [[COPY1]](s32), [[C]]
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<64 x s8>) = G_SELECT [[ICMP]](s1), [[UV]], [[UV1]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR [[ICMP]], [[C1]]
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[XOR]](s1)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXT]], [[C2]](s32)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[SHL]]
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[SELECT]](<64 x s8>), [[SUB]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<128 x s8>) = COPY $y2
    %2:_(s32) = COPY $r1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %1(<128 x s8>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i16_signext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y2

    ; CHECK-LABEL: name: extract_v64i16_signext
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY]](<64 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s16>) = COPY $y2
    %2:_(s32) = G_CONSTANT i32 11
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<64 x s16>), %2(s32)
    %3:_(s32) = G_SEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i16_zeroext
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y2

    ; CHECK-LABEL: name: extract_v64i16_zeroext
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY]](<64 x s16>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s16>) = COPY $y2
    %2:_(s32) = G_CONSTANT i32 11
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<64 x s16>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i16_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $y2

    ; CHECK-LABEL: name: extract_v64i16_dyn
    ; CHECK: liveins: $r1, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY]](<64 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(slt), [[COPY1]](s32), [[C]]
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<32 x s16>) = G_SELECT [[ICMP]](s1), [[UV]], [[UV1]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR [[ICMP]], [[C1]]
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[XOR]](s1)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXT]], [[C2]](s32)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[SHL]]
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[SELECT]](<32 x s16>), [[SUB]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s16>) = COPY $y2
    %2:_(s32) = COPY $r1
    %4:_(s16) = G_EXTRACT_VECTOR_ELT %1(<64 x s16>), %2(s32)
    %3:_(s32) = G_ZEXT %4
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y2

    ; CHECK-LABEL: name: extract_v32i32
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s32>) = COPY $y2
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<32 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r1, $y2

    ; CHECK-LABEL: name: extract_v32i32_dyn
    ; CHECK: liveins: $r1, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<32 x s32>) = COPY $y2
    %2:_(s32) = COPY $r1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<32 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            test0
legalized:       false
body:             |
  bb.0.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: test0
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_ZEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %0(<16 x s16>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test1
legalized:       false
body:             |
  bb.0.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: test1
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<16 x s16>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test2
legalized:       false
body:             |
  bb.0.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: test2
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s8>) = COPY $wl0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s8>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test3
legalized:       false
body:             |
  bb.0.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: test3
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_ZEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s8>) = COPY $wl0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %0(<32 x s8>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test0_512bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0

    ; CHECK-LABEL: name: test0_512bit
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_ZEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test1_512bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0

    ; CHECK-LABEL: name: test1_512bit
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test2_512bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0

    ; CHECK-LABEL: name: test2_512bit
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<64 x s8>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test3_512bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0

    ; CHECK-LABEL: name: test3_512bit
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[COPY]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_ZEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<64 x s8>) = COPY $x0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %0(<64 x s8>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test0_1024bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $y2

    ; CHECK-LABEL: name: test0_1024bit
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY]](<64 x s16>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_ZEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<64 x s16>) = COPY $y2
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %0(<64 x s16>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test1_1024bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $y2

    ; CHECK-LABEL: name: test1_1024bit
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[COPY]](<64 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<64 x s16>) = COPY $y2
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<64 x s16>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test2_1024bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $y2

    ; CHECK-LABEL: name: test2_1024bit
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY]](<128 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<128 x s8>) = COPY $y2
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<128 x s8>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test3_1024bit
legalized:       false
body:             |
  bb.0.entry:
    liveins: $y2

    ; CHECK-LABEL: name: test3_1024bit
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[COPY]](<128 x s8>)
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_ZEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(<128 x s8>) = COPY $y2
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %0(<128 x s8>), %1(s32)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_v2int32
legalized:       false
body:             |
  bb.1.entry:
    liveins: $l0

    ; CHECK-LABEL: name: test_v2int32
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s32>), [[C1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: $r1 = COPY [[EVEC1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<2 x s32>) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_EXTRACT_VECTOR_ELT %1(<2 x s32>), %2(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %5:_(s32) = G_EXTRACT_VECTOR_ELT %1(<2 x s32>), %4(s32)
    $r0 = COPY %3(s32)
    $r1 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name: test_extract_32_0
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_extract_32_0
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s8) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s8)
    ; CHECK-NEXT: $r2 = COPY [[ANYEXT]](s32)
    %0:_(<4 x s8>) = COPY $r0
    %5:_(s32) = G_CONSTANT i32 0
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %0(<4 x s8>), %5(s32)
    %1:_(s32) = G_ANYEXT %4(s8)
    $r2 = COPY %1(s32)
...

---
name: test_extract_32_1
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_extract_32_1
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s8) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s8)
    ; CHECK-NEXT: $r2 = COPY [[ANYEXT]](s32)
    %0:_(<4 x s8>) = COPY $r0
    %5:_(s32) = G_CONSTANT i32 1
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %0(<4 x s8>), %5(s32)
    %1:_(s32) = G_ANYEXT %4(s8)
    $r2 = COPY %1(s32)
...

---
name: test_extract_32_2
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_extract_32_2
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s8) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s8)
    ; CHECK-NEXT: $r2 = COPY [[ANYEXT]](s32)
    %0:_(<4 x s8>) = COPY $r0
    %5:_(s32) = G_CONSTANT i32 2
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %0(<4 x s8>), %5(s32)
    %1:_(s32) = G_ANYEXT %4(s8)
    $r2 = COPY %1(s32)
...

---
name: test_extract_32_3
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_extract_32_3
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s8) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s8)
    ; CHECK-NEXT: $r2 = COPY [[ANYEXT]](s32)
    %0:_(<4 x s8>) = COPY $r0
    %5:_(s32) = G_CONSTANT i32 3
    %4:_(s8) = G_EXTRACT_VECTOR_ELT %0(<4 x s8>), %5(s32)
    %1:_(s32) = G_ANYEXT %4(s8)
    $r2 = COPY %1(s32)
...

---
name: test_extract_16bit
body: |
  bb.1.entry:
    ; CHECK-LABEL: name: test_extract_16bit
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
  %0:_(s8) = G_CONSTANT i8 42
  %1:_(<2 x s8>) = G_BUILD_VECTOR %0(s8), %0(s8)
  %2:_(s32) = G_CONSTANT i32 0
  %3:_(s8) = G_EXTRACT_VECTOR_ELT %1(<2 x s8>), %2(s32)
  %4:_(s32) = G_ANYEXT %3(s8)
  $r0 = COPY %4(s32)
...
---
name: test_extract_128bit
body: |
  bb.1.entry:
    ; CHECK-LABEL: name: test_extract_128bit
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 68
    ; CHECK-NEXT: $r0 = COPY [[C]](s32)
    %0:_(s32) = G_CONSTANT i32 65
    %1:_(s32) = G_CONSTANT i32 77
    %2:_(s32) = G_CONSTANT i32 68
    %3:_(s32) = G_CONSTANT i32 33
    %4:_(<4 x s32>) = G_BUILD_VECTOR %0(s32), %1(s32), %2(s32), %3(s32)
    %5:_(s32) = G_CONSTANT i32 2
    %6:_(s32) = G_EXTRACT_VECTOR_ELT %4(<4 x s32>), %5(s32)
    $r0 = COPY %6(s32)
...
