# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Test that G_SHUFFLE_VECTOR with a scalar source (from <1 x i64>) is handled
# in the prelegalizer combiner. The <1 x i64> type is lowered to scalar s64 in
# GlobalISel. The combiner now properly handles scalar sources by:
# - matchShuffleToVecBroadcast: treats scalar as 1-element source
# - matchShuffleToVecEltBroadcast: broadcasts scalar directly when index is 0
#
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

# Test matchShuffleToVecBroadcast with scalar s64 source (64-bit).
# The s64 is broadcast by bitcasting to <2 x s32>, broadcasting, and concatenating.
---
name: shuffle_vector_scalar_src_s64
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l0

    ; CHECK-LABEL: name: shuffle_vector_scalar_src_s64
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[COPY]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<8 x s64>), [[AIE_BROADCAST_VECTOR]](<8 x s64>), [[AIE_BROADCAST_VECTOR]](<8 x s64>), [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s64>)
    %0:_(s64) = COPY $l0
    %1:_(s64) = G_IMPLICIT_DEF
    %2:_(<32 x s64>) = G_SHUFFLE_VECTOR %0(s64), %1, shufflemask(0, 0, 0, 0, 0, 0, 0, 0, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef)
    PseudoRET implicit $lr, implicit %2
...

# Test matchShuffleToVecBroadcast with scalar s32 source (32-bit).
# The s32 is directly broadcast to the target vector size.
---
name: shuffle_vector_scalar_src_s32
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0

    ; CHECK-LABEL: name: shuffle_vector_scalar_src_s32
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %0:_(s32) = COPY $r0
    %1:_(s32) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(s32), %1, shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    PseudoRET implicit $lr, implicit %2
...

# Test matchShuffleToVecEltBroadcast with scalar s32 source and element 0.
# When the mask has a unique index of 0 and source is scalar, we broadcast directly.
# The broadcast goes to the minimum vector size (<16 x s32>) then unpads.
---
name: shuffle_vector_scalar_src_s32_elt0
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0

    ; CHECK-LABEL: name: shuffle_vector_scalar_src_s32_elt0
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %0:_(s32) = COPY $r0
    %1:_(s32) = G_IMPLICIT_DEF
    %2:_(<8 x s32>) = G_SHUFFLE_VECTOR %0(s32), %1, shufflemask(0, 0, 0, 0, undef, undef, undef, undef)
    PseudoRET implicit $lr, implicit %2
...

# Test scalar s64 broadcast to a smaller target vector <8 x s64>.
---
name: shuffle_vector_scalar_s64_to_8xs64
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l0

    ; CHECK-LABEL: name: shuffle_vector_scalar_s64_to_8xs64
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[COPY]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    %0:_(s64) = COPY $l0
    %1:_(s64) = G_IMPLICIT_DEF
    %2:_(<8 x s64>) = G_SHUFFLE_VECTOR %0(s64), %1, shufflemask(0, 0, 0, 0, 0, 0, 0, 0)
    PseudoRET implicit $lr, implicit %2
...

# Test scalar source in second operand position (splat index > 0).
# When both sources are scalar and we splat from the second one.
---
name: shuffle_vector_second_src_scalar
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l0, $l1

    ; CHECK-LABEL: name: shuffle_vector_second_src_scalar
    ; CHECK: liveins: $l0, $l1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $l1
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[COPY]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    %0:_(s64) = COPY $l0
    %1:_(s64) = COPY $l1
    %2:_(<8 x s64>) = G_SHUFFLE_VECTOR %0(s64), %1, shufflemask(1, 1, 1, 1, 1, 1, 1, 1)
    PseudoRET implicit $lr, implicit %2
...
