# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_inttoptr
legalized: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: test_inttoptr
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:ptrregbank(s20) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:ptrregbank(p0) = G_INTTOPTR [[TRUNC]](s20)
    ; CHECK-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    ; GREEDY-LABEL: name: test_inttoptr
    ; GREEDY: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; GREEDY-NEXT: [[TRUNC:%[0-9]+]]:ptrregbank(s20) = G_TRUNC [[COPY]](s32)
    ; GREEDY-NEXT: [[INTTOPTR:%[0-9]+]]:ptrregbank(p0) = G_INTTOPTR [[TRUNC]](s20)
    ; GREEDY-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    %0:_(s32) = COPY $r6
    %1:_(s20) = G_TRUNC %0
    %2:_(p0) = G_INTTOPTR %1
    $p0 = COPY %2
...

---
name: test_inttoptr_ptr_regs
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: test_inttoptr_ptr_regs
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(s20) = COPY $p0
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:ptrregbank(p0) = G_INTTOPTR [[COPY]](s20)
    ; CHECK-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    ; GREEDY-LABEL: name: test_inttoptr_ptr_regs
    ; GREEDY: [[COPY:%[0-9]+]]:ptrregbank(s20) = COPY $p0
    ; GREEDY-NEXT: [[INTTOPTR:%[0-9]+]]:ptrregbank(p0) = G_INTTOPTR [[COPY]](s20)
    ; GREEDY-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    %0:_(s20) = COPY $p0
    %1:_(p0) = G_INTTOPTR %0
    $p0 = COPY %1
...
