# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

---
name: load_s32
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_s32
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[COPY]](p0) :: (load (s32))
    ; CHECK-NEXT: $r0 = COPY [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_LOAD %0 :: (load (s32), align 4)
    $r0 = COPY %1
...

---
name: load_ext_s8
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_ext_s8
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[COPY]](p0) :: (load (s8))
    ; CHECK-NEXT: $r0 = COPY [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_LOAD %0 :: (load (s8), align 1)
    $r0 = COPY %1
...

---
name: load_ext_s16
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_ext_s16
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[COPY]](p0) :: (load (s16))
    ; CHECK-NEXT: $r0 = COPY [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_LOAD %0 :: (load (s16), align 2)
    $r0 = COPY %1
...

---
name: load_p0
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_p0
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:ptrregbank(p0) = G_LOAD [[COPY]](p0) :: (load (p0), align 4)
    ; CHECK-NEXT: $p0 = COPY [[LOAD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(p0) = G_LOAD %0 :: (load (p0), align 4)
    $p0 = COPY %1
...

---
name: load_s20
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_s20
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:modregbank(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
    ; CHECK-NEXT: $m0 = COPY [[LOAD]](s20)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_LOAD %0 :: (load (s20), align 4)
    $m0 = COPY %1
...
