# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple=aie2ps -run-pass=regbankselect %s -verify-machineinstrs -o - | FileCheck %s

---
name: phi_acc_512bit_used_by_accumulator
legalized: true
tracksRegLiveness: true

body: |
  ; CHECK-LABEL: name: phi_acc_512bit_used_by_accumulator
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:accregbank(<16 x s32>) = G_PHI [[AIE_BROADCAST_VECTOR]](<16 x s32>), %bb.0, [[AIE_BROADCAST_VECTOR]](<16 x s32>), %bb.0
  ; CHECK-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<32 x s32>) = G_CONCAT_VECTORS [[PHI]](<16 x s32>), [[PHI]](<16 x s32>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.add.conf), [[CONCAT_VECTORS]](<32 x s32>), [[CONCAT_VECTORS]](<32 x s32>), 60
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:accregbank(<16 x s32>), [[UV1:%[0-9]+]]:accregbank(<16 x s32>) = G_UNMERGE_VALUES [[INT]](<32 x s32>)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  bb.0:
    successors: %bb.1
    %0:_(s32) = G_CONSTANT i32 0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)

  bb.1:
    successors: %bb.2
    %2:_(<16 x s32>) = G_PHI %1(<16 x s32>), %bb.0, %1(<16 x s32>), %bb.0
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %2(<16 x s32>), %2(<16 x s32>)
    %4:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.add.conf), %3(<32 x s32>), %3(<32 x s32>), 60
    %5:_(<16 x s32>), %6:_(<16 x s32>) = G_UNMERGE_VALUES %4(<32 x s32>)

  bb.2:
...

---
name: phi_vec_512bit_no_accumulator_use
legalized: true
tracksRegLiveness: true

body: |
  ; CHECK-LABEL: name: phi_vec_512bit_no_accumulator_use
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:vregbank(<16 x s32>) = G_PHI [[AIE_BROADCAST_VECTOR]](<16 x s32>), %bb.0, [[AIE_BROADCAST_VECTOR]](<16 x s32>), %bb.0
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:vregbank(<16 x s32>) = G_ADD [[PHI]], [[PHI]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  bb.0:
    successors: %bb.1
    %0:_(s32) = G_CONSTANT i32 0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)

  bb.1:
    successors: %bb.2
    %2:_(<16 x s32>) = G_PHI %1(<16 x s32>), %bb.0, %1(<16 x s32>), %bb.0
    %3:_(<16 x s32>) = G_ADD %2, %2

  bb.2:
...

---
name: phi_acc_1024bit_used_by_accumulator
legalized: true
tracksRegLiveness: true

body: |
  ; CHECK-LABEL: name: phi_acc_1024bit_used_by_accumulator
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:accregbank(<32 x s32>) = G_PHI [[CONCAT_VECTORS]](<32 x s32>), %bb.0, [[CONCAT_VECTORS]](<32 x s32>), %bb.0
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.add.conf), [[PHI]](<32 x s32>), [[PHI]](<32 x s32>), 60
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  bb.0:
    successors: %bb.1
    %0:_(s32) = G_CONSTANT i32 0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %1(<16 x s32>)

  bb.1:
    successors: %bb.2
    %3:_(<32 x s32>) = G_PHI %2(<32 x s32>), %bb.0, %2(<32 x s32>), %bb.0
    %4:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.add.conf), %3(<32 x s32>), %3(<32 x s32>), 60

  bb.2:
...

---
name: phi_small_vector_default_behavior
legalized: true
tracksRegLiveness: true

body: |
  ; CHECK-LABEL: name: phi_small_vector_default_behavior
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vregbank(<8 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:vregbank(<8 x s32>) = G_PHI [[DEF]](<8 x s32>), %bb.0, [[DEF]](<8 x s32>), %bb.0
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:vregbank(<8 x s32>) = G_ADD [[PHI]], [[PHI]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  bb.0:
    successors: %bb.1
    %0:_(<8 x s32>) = G_IMPLICIT_DEF

  bb.1:
    successors: %bb.2
    %1:_(<8 x s32>) = G_PHI %0(<8 x s32>), %bb.0, %0(<8 x s32>), %bb.0
    %2:_(<8 x s32>) = G_ADD %1, %1

  bb.2:
...
