# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1 %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE1GREEDY %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2 %s

---
name: ptr_add
legalized: true

body: |
  bb.0:
    liveins: $p0, $r6
    ; AIE1-LABEL: name: ptr_add
    ; AIE1: liveins: $p0, $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; AIE1-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:gprregbank(p0) = COPY [[COPY]](p0)
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s20) = COPY [[TRUNC]](s20)
    ; AIE1-NEXT: [[PTR_ADD:%[0-9]+]]:gprregbank(p0) = G_PTR_ADD [[COPY2]], [[COPY3]](s20)
    ; AIE1-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; AIE1GREEDY-LABEL: name: ptr_add
    ; AIE1GREEDY: liveins: $p0, $r6
    ; AIE1GREEDY-NEXT: {{  $}}
    ; AIE1GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; AIE1GREEDY-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; AIE1GREEDY-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; AIE1GREEDY-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; AIE2-LABEL: name: ptr_add
    ; AIE2: liveins: $p0, $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; AIE2-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r6
    %2:_(s20) = G_TRUNC %1
    %3:_(p0) = G_PTR_ADD %0, %2
    $p0 = COPY %3
...

---
name: ptr_add_s20_on_ptr
legalized: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; AIE1-LABEL: name: ptr_add_s20_on_ptr
    ; AIE1: liveins: $p0, $p1
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(s20) = COPY $p1
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:gprregbank(p0) = COPY [[COPY]](p0)
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s20) = COPY [[COPY1]](s20)
    ; AIE1-NEXT: [[PTR_ADD:%[0-9]+]]:gprregbank(p0) = G_PTR_ADD [[COPY2]], [[COPY3]](s20)
    ; AIE1-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; AIE1GREEDY-LABEL: name: ptr_add_s20_on_ptr
    ; AIE1GREEDY: liveins: $p0, $p1
    ; AIE1GREEDY-NEXT: {{  $}}
    ; AIE1GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(s20) = COPY $p1
    ; AIE1GREEDY-NEXT: [[COPY2:%[0-9]+]]:modregbank(s20) = COPY [[COPY1]](s20)
    ; AIE1GREEDY-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[COPY2]](s20)
    ; AIE1GREEDY-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    ; AIE2-LABEL: name: ptr_add_s20_on_ptr
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(s20) = COPY $p1
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:modregbank(s20) = COPY [[COPY1]](s20)
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[COPY2]](s20)
    ; AIE2-NEXT: $p0 = COPY [[PTR_ADD]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s20) = COPY $p1
    %2:_(p0) = G_PTR_ADD %0, %1
    $p0 = COPY %2
...

---
name: ptr_add_then_load
legalized: true

body: |
  bb.0:
    liveins: $p0, $r6
    ; AIE1-LABEL: name: ptr_add_then_load
    ; AIE1: liveins: $p0, $r6
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; AIE1-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:gprregbank(p0) = COPY [[COPY]](p0)
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s20) = COPY [[TRUNC]](s20)
    ; AIE1-NEXT: [[PTR_ADD:%[0-9]+]]:gprregbank(p0) = G_PTR_ADD [[COPY2]], [[COPY3]](s20)
    ; AIE1-NEXT: [[COPY4:%[0-9]+]]:ptrregbank(p0) = COPY [[PTR_ADD]](p0)
    ; AIE1-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[COPY4]](p0) :: (load (s32))
    ; AIE1-NEXT: $r6 = COPY [[LOAD]](s32)
    ; AIE1GREEDY-LABEL: name: ptr_add_then_load
    ; AIE1GREEDY: liveins: $p0, $r6
    ; AIE1GREEDY-NEXT: {{  $}}
    ; AIE1GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; AIE1GREEDY-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; AIE1GREEDY-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; AIE1GREEDY-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
    ; AIE1GREEDY-NEXT: $r6 = COPY [[LOAD]](s32)
    ; AIE2-LABEL: name: ptr_add_then_load
    ; AIE2: liveins: $p0, $r6
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; AIE2-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[TRUNC]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
    ; AIE2-NEXT: $r6 = COPY [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r6
    %2:_(s20) = G_TRUNC %1
    %3:_(p0) = G_PTR_ADD %0, %2
    %4:_(s32) = G_LOAD %3(p0) :: (load (s32), align 4)
    $r6 = COPY %4
...


---
name: ptr_add_s20_then_load
legalized: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; AIE1-LABEL: name: ptr_add_s20_then_load
    ; AIE1: liveins: $p0, $p1
    ; AIE1-NEXT: {{  $}}
    ; AIE1-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(s20) = COPY $p1
    ; AIE1-NEXT: [[COPY2:%[0-9]+]]:gprregbank(p0) = COPY [[COPY]](p0)
    ; AIE1-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s20) = COPY [[COPY1]](s20)
    ; AIE1-NEXT: [[PTR_ADD:%[0-9]+]]:gprregbank(p0) = G_PTR_ADD [[COPY2]], [[COPY3]](s20)
    ; AIE1-NEXT: [[COPY4:%[0-9]+]]:ptrregbank(p0) = COPY [[PTR_ADD]](p0)
    ; AIE1-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[COPY4]](p0) :: (load (s32))
    ; AIE1-NEXT: $r6 = COPY [[LOAD]](s32)
    ; AIE1GREEDY-LABEL: name: ptr_add_s20_then_load
    ; AIE1GREEDY: liveins: $p0, $p1
    ; AIE1GREEDY-NEXT: {{  $}}
    ; AIE1GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE1GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(s20) = COPY $p1
    ; AIE1GREEDY-NEXT: [[COPY2:%[0-9]+]]:modregbank(s20) = COPY [[COPY1]](s20)
    ; AIE1GREEDY-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[COPY2]](s20)
    ; AIE1GREEDY-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
    ; AIE1GREEDY-NEXT: $r6 = COPY [[LOAD]](s32)
    ; AIE2-LABEL: name: ptr_add_s20_then_load
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(s20) = COPY $p1
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:modregbank(s20) = COPY [[COPY1]](s20)
    ; AIE2-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[COPY]], [[COPY2]](s20)
    ; AIE2-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32))
    ; AIE2-NEXT: $r6 = COPY [[LOAD]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s20) = COPY $p1
    %2:_(p0) = G_PTR_ADD %0, %1
    %3:_(s32) = G_LOAD %2(p0) :: (load (s32), align 4)
    $r6 = COPY %3
...
