# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

---
name: store_s32
legalized: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; CHECK-LABEL: name: store_s32
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p0) :: (store (s32))
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s32))
...

---
name: store_s8
legalized: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; CHECK-LABEL: name: store_s8
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p0) :: (store (s8))
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s8))
...

---
name: store_s16
legalized: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; CHECK-LABEL: name: store_s16
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p0) :: (store (s16))
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s16))
...

---
name: test_store_p0
legalized: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: test_store_p0
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: G_STORE [[COPY1]](p0), [[COPY]](p0) :: (store (p0), align 4)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    G_STORE %1, %0 :: (store (p0))
...

---
name: store_s20
legalized: true

body: |
  bb.0:
    liveins: $m6, $p0
    ; CHECK-LABEL: name: store_s20
    ; CHECK: liveins: $m6, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:modregbank(s20) = COPY $m6
    ; CHECK-NEXT: G_STORE [[COPY1]](s20), [[COPY]](p0) :: (store (s20), align 4)
    %0:_(p0) = COPY $p0
    %1:_(s20) = COPY $m6
    G_STORE %1, %0 :: (store (s20))
...

---
name: store_s20_from_gpr
legalized: true

body: |
  bb.0:
    liveins: $r1, $p0
    ; CHECK-LABEL: name: store_s20_from_gpr
    ; CHECK: liveins: $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: G_STORE [[TRUNC]](s20), [[COPY]](p0) :: (store (s20), align 4)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r1
    %2:_(s20) = G_TRUNC %1
    G_STORE %2, %0 :: (store (s20))
...
