# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
---
name: test_constant_s20.
legalized: true
body: |
  bb.0:
    ; CHECK-LABEL: name: test_constant_s20.
    ; CHECK: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ;
    ; GREEDY-LABEL: name: test_constant_s20.
    ; GREEDY: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    %0:_(s20) = G_CONSTANT i20 5
...

---
name: test_const_inttoptr
legalized: true

body: |
  bb.0:
    liveins:
    ; CHECK-LABEL: name: test_const_inttoptr
    ; CHECK: [[C:%[0-9]+]]:ptrregbank(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:ptrregbank(p0) = G_INTTOPTR [[C]](s20)
    ; CHECK-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    ;
    ; GREEDY-LABEL: name: test_const_inttoptr
    ; GREEDY: [[C:%[0-9]+]]:ptrregbank(s20) = G_CONSTANT i20 100
    ; GREEDY-NEXT: [[INTTOPTR:%[0-9]+]]:ptrregbank(p0) = G_INTTOPTR [[C]](s20)
    ; GREEDY-NEXT: $p0 = COPY [[INTTOPTR]](p0)
    %0:_(s20) = G_CONSTANT i20 100
    %2:_(p0) = G_INTTOPTR %0
    $p0 = COPY %2
...

---
name: test_const_zext
legalized: true

body: |
  bb.0:
    liveins:
    ; CHECK-LABEL: name: test_const_zext
    ; CHECK: [[C:%[0-9]+]]:gprregbank(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:modregbank(s20) = COPY [[C]](s20)
    ; CHECK-NEXT: [[ZEXT:%[0-9]+]]:gprregbank(s32) = G_ZEXT [[COPY]](s20)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:modregbank(s20) = COPY [[C]](s20)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:gprregbank(s32) = G_SEXT [[COPY1]](s20)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:modregbank(s20) = COPY [[C]](s20)
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:gprregbank(s32) = G_ANYEXT [[COPY2]](s20)
    ; CHECK-NEXT: $r0 = COPY [[ZEXT]](s32)
    ; CHECK-NEXT: $r1 = COPY [[SEXT]](s32)
    ; CHECK-NEXT: $r2 = COPY [[ANYEXT]](s32)
    ;
    ; GREEDY-LABEL: name: test_const_zext
    ; GREEDY: [[C:%[0-9]+]]:gprregbank(s20) = G_CONSTANT i20 100
    ; GREEDY-NEXT: [[ZEXT:%[0-9]+]]:gprregbank(s32) = G_ZEXT [[C]](s20)
    ; GREEDY-NEXT: [[SEXT:%[0-9]+]]:gprregbank(s32) = G_SEXT [[C]](s20)
    ; GREEDY-NEXT: [[ANYEXT:%[0-9]+]]:gprregbank(s32) = G_ANYEXT [[C]](s20)
    ; GREEDY-NEXT: $r0 = COPY [[ZEXT]](s32)
    ; GREEDY-NEXT: $r1 = COPY [[SEXT]](s32)
    ; GREEDY-NEXT: $r2 = COPY [[ANYEXT]](s32)
    %0:_(s20) = G_CONSTANT i20 100
    %2:_(s32) = G_ZEXT %0
    %3:_(s32) = G_SEXT %0
    %4:_(s32) = G_ANYEXT %0
    $r0 = COPY %2
    $r1 = COPY %3
    $r2 = COPY %4
...
