# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
---
name:            test_sparsity_t_store
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0, $q0

    ; CHECK-LABEL: name: test_sparsity_t_store
    ; CHECK: liveins: $p0, $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(s128) = COPY $q0
    ; CHECK-NEXT: G_STORE [[COPY1]](s128), [[COPY]](p0) :: (store (s128))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s128) = COPY $q0
    G_STORE %1(s128), %0(p0) :: (store (s128))
    PseudoRET implicit $lr
...

---
name:            test_sparsity_t_load
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_sparsity_t_load
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(s128) = G_LOAD [[COPY]](p0) :: (load (s128))
    ; CHECK-NEXT: $q0 = COPY [[LOAD]](s128)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $q0
    %1:_(p0) = COPY $p0
    %0:_(s128) = G_LOAD %1(p0) :: (load (s128))
    $q0 = COPY %0(s128)
    PseudoRET implicit $lr, implicit $q0
...
