# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2-GREEDY %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2-FAST %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P-GREEDY %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=AIE2P-FAST %s
---
name:            vconcat_1024_32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; AIE2-GREEDY-LABEL: name: vconcat_1024_32
    ; AIE2-GREEDY: liveins: $x0, $x2
    ; AIE2-GREEDY-NEXT: {{  $}}
    ; AIE2-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; AIE2-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x2
    ; AIE2-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; AIE2-GREEDY-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2-GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2-FAST-LABEL: name: vconcat_1024_32
    ; AIE2-FAST: liveins: $x0, $x2
    ; AIE2-FAST-NEXT: {{  $}}
    ; AIE2-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; AIE2-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x2
    ; AIE2-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; AIE2-FAST-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2-FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2P-GREEDY-LABEL: name: vconcat_1024_32
    ; AIE2P-GREEDY: liveins: $x0, $x2
    ; AIE2P-GREEDY-NEXT: {{  $}}
    ; AIE2P-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; AIE2P-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x2
    ; AIE2P-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; AIE2P-GREEDY-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2P-GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2P-FAST-LABEL: name: vconcat_1024_32
    ; AIE2P-FAST: liveins: $x0, $x2
    ; AIE2P-FAST-NEXT: {{  $}}
    ; AIE2P-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; AIE2P-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x2
    ; AIE2P-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; AIE2P-FAST-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2P-FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    $y2 = COPY %3(<32 x s32>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            vconcat_512_32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $wl2, $wl4

    ; AIE2-GREEDY-LABEL: name: vconcat_512_32
    ; AIE2-GREEDY: liveins: $wl2, $wl4
    ; AIE2-GREEDY-NEXT: {{  $}}
    ; AIE2-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl2
    ; AIE2-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl4
    ; AIE2-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; AIE2-GREEDY-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2-GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2-FAST-LABEL: name: vconcat_512_32
    ; AIE2-FAST: liveins: $wl2, $wl4
    ; AIE2-FAST-NEXT: {{  $}}
    ; AIE2-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl2
    ; AIE2-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl4
    ; AIE2-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; AIE2-FAST-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2-FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-GREEDY-LABEL: name: vconcat_512_32
    ; AIE2P-GREEDY: liveins: $wl2, $wl4
    ; AIE2P-GREEDY-NEXT: {{  $}}
    ; AIE2P-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl2
    ; AIE2P-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl4
    ; AIE2P-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; AIE2P-GREEDY-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2P-GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-FAST-LABEL: name: vconcat_512_32
    ; AIE2P-FAST: liveins: $wl2, $wl4
    ; AIE2P-FAST-NEXT: {{  $}}
    ; AIE2P-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl2
    ; AIE2P-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl4
    ; AIE2P-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; AIE2P-FAST-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2P-FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<8 x s32>) = COPY $wl2
    %2:_(<8 x s32>) = COPY $wl4
    %3:_(<16 x s32>) = G_CONCAT_VECTORS %1(<8 x s32>), %2(<8 x s32>)
    $x0 = COPY %3(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            vconcat_512_16
legalized:       true
body:             |
  bb.1.entry:
    liveins: $wl2, $wl4

    ; AIE2-GREEDY-LABEL: name: vconcat_512_16
    ; AIE2-GREEDY: liveins: $wl2, $wl4
    ; AIE2-GREEDY-NEXT: {{  $}}
    ; AIE2-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl2
    ; AIE2-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl4
    ; AIE2-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<16 x s16>)
    ; AIE2-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<16 x s16>)
    ; AIE2-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2-GREEDY-NEXT: $x0 = COPY [[BITCAST2]](<32 x s16>)
    ; AIE2-GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2-FAST-LABEL: name: vconcat_512_16
    ; AIE2-FAST: liveins: $wl2, $wl4
    ; AIE2-FAST-NEXT: {{  $}}
    ; AIE2-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl2
    ; AIE2-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl4
    ; AIE2-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<16 x s16>)
    ; AIE2-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<16 x s16>)
    ; AIE2-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2-FAST-NEXT: $x0 = COPY [[BITCAST2]](<32 x s16>)
    ; AIE2-FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-GREEDY-LABEL: name: vconcat_512_16
    ; AIE2P-GREEDY: liveins: $wl2, $wl4
    ; AIE2P-GREEDY-NEXT: {{  $}}
    ; AIE2P-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl2
    ; AIE2P-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl4
    ; AIE2P-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<16 x s16>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<16 x s16>)
    ; AIE2P-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2P-GREEDY-NEXT: $x0 = COPY [[BITCAST2]](<32 x s16>)
    ; AIE2P-GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-FAST-LABEL: name: vconcat_512_16
    ; AIE2P-FAST: liveins: $wl2, $wl4
    ; AIE2P-FAST-NEXT: {{  $}}
    ; AIE2P-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl2
    ; AIE2P-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl4
    ; AIE2P-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<16 x s16>)
    ; AIE2P-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<16 x s16>)
    ; AIE2P-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2P-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2P-FAST-NEXT: $x0 = COPY [[BITCAST2]](<32 x s16>)
    ; AIE2P-FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s16>) = COPY $wl2
    %2:_(<16 x s16>) = COPY $wl4
    %3:_(<8 x s32>) = G_BITCAST %1(<16 x s16>)
    %4:_(<8 x s32>) = G_BITCAST %2(<16 x s16>)
    %6:_(<16 x s32>) = G_CONCAT_VECTORS %3(<8 x s32>), %4(<8 x s32>)
    %0:_(<32 x s16>) = G_BITCAST %6(<16 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            vconcat_1024_16
legalized:       true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; AIE2-GREEDY-LABEL: name: vconcat_1024_16
    ; AIE2-GREEDY: liveins: $x0, $x2
    ; AIE2-GREEDY-NEXT: {{  $}}
    ; AIE2-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; AIE2-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; AIE2-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<32 x s16>)
    ; AIE2-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<32 x s16>)
    ; AIE2-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2-GREEDY-NEXT: $y2 = COPY [[BITCAST2]](<64 x s16>)
    ; AIE2-GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2-FAST-LABEL: name: vconcat_1024_16
    ; AIE2-FAST: liveins: $x0, $x2
    ; AIE2-FAST-NEXT: {{  $}}
    ; AIE2-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; AIE2-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; AIE2-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<32 x s16>)
    ; AIE2-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<32 x s16>)
    ; AIE2-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2-FAST-NEXT: $y2 = COPY [[BITCAST2]](<64 x s16>)
    ; AIE2-FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2P-GREEDY-LABEL: name: vconcat_1024_16
    ; AIE2P-GREEDY: liveins: $x0, $x2
    ; AIE2P-GREEDY-NEXT: {{  $}}
    ; AIE2P-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; AIE2P-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; AIE2P-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<32 x s16>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<32 x s16>)
    ; AIE2P-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2P-GREEDY-NEXT: $y2 = COPY [[BITCAST2]](<64 x s16>)
    ; AIE2P-GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2P-FAST-LABEL: name: vconcat_1024_16
    ; AIE2P-FAST: liveins: $x0, $x2
    ; AIE2P-FAST-NEXT: {{  $}}
    ; AIE2P-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; AIE2P-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; AIE2P-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<32 x s16>)
    ; AIE2P-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<32 x s16>)
    ; AIE2P-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2P-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s16>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2P-FAST-NEXT: $y2 = COPY [[BITCAST2]](<64 x s16>)
    ; AIE2P-FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x2
    %3:_(<16 x s32>) = G_BITCAST %1(<32 x s16>)
    %4:_(<16 x s32>) = G_BITCAST %2(<32 x s16>)
    %6:_(<32 x s32>) = G_CONCAT_VECTORS %3(<16 x s32>), %4(<16 x s32>)
    %0:_(<64 x s16>) = G_BITCAST %6(<32 x s32>)
    $y2 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            vconcat_512_8
legalized:       true
body:             |
  bb.1.entry:
    liveins: $wl2, $wl4

    ; AIE2-GREEDY-LABEL: name: vconcat_512_8
    ; AIE2-GREEDY: liveins: $wl2, $wl4
    ; AIE2-GREEDY-NEXT: {{  $}}
    ; AIE2-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl2
    ; AIE2-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl4
    ; AIE2-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<32 x s8>)
    ; AIE2-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<32 x s8>)
    ; AIE2-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2-GREEDY-NEXT: $x0 = COPY [[BITCAST2]](<64 x s8>)
    ; AIE2-GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2-FAST-LABEL: name: vconcat_512_8
    ; AIE2-FAST: liveins: $wl2, $wl4
    ; AIE2-FAST-NEXT: {{  $}}
    ; AIE2-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl2
    ; AIE2-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl4
    ; AIE2-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<32 x s8>)
    ; AIE2-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<32 x s8>)
    ; AIE2-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2-FAST-NEXT: $x0 = COPY [[BITCAST2]](<64 x s8>)
    ; AIE2-FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-GREEDY-LABEL: name: vconcat_512_8
    ; AIE2P-GREEDY: liveins: $wl2, $wl4
    ; AIE2P-GREEDY-NEXT: {{  $}}
    ; AIE2P-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl2
    ; AIE2P-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl4
    ; AIE2P-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<32 x s8>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<32 x s8>)
    ; AIE2P-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2P-GREEDY-NEXT: $x0 = COPY [[BITCAST2]](<64 x s8>)
    ; AIE2P-GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2P-FAST-LABEL: name: vconcat_512_8
    ; AIE2P-FAST: liveins: $wl2, $wl4
    ; AIE2P-FAST-NEXT: {{  $}}
    ; AIE2P-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl2
    ; AIE2P-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl4
    ; AIE2P-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY]](<32 x s8>)
    ; AIE2P-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[COPY1]](<32 x s8>)
    ; AIE2P-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[BITCAST1]](<8 x s32>)
    ; AIE2P-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<64 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<16 x s32>)
    ; AIE2P-FAST-NEXT: $x0 = COPY [[BITCAST2]](<64 x s8>)
    ; AIE2P-FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s8>) = COPY $wl2
    %2:_(<32 x s8>) = COPY $wl4
    %3:_(<8 x s32>) = G_BITCAST %1(<32 x s8>)
    %4:_(<8 x s32>) = G_BITCAST %2(<32 x s8>)
    %6:_(<16 x s32>) = G_CONCAT_VECTORS %3(<8 x s32>), %4(<8 x s32>)
    %0:_(<64 x s8>) = G_BITCAST %6(<16 x s32>)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            vconcat_1024_8
legalized:       true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; AIE2-GREEDY-LABEL: name: vconcat_1024_8
    ; AIE2-GREEDY: liveins: $x0, $x2
    ; AIE2-GREEDY-NEXT: {{  $}}
    ; AIE2-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; AIE2-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; AIE2-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<64 x s8>)
    ; AIE2-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; AIE2-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<128 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2-GREEDY-NEXT: $y2 = COPY [[BITCAST2]](<128 x s8>)
    ; AIE2-GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2-FAST-LABEL: name: vconcat_1024_8
    ; AIE2-FAST: liveins: $x0, $x2
    ; AIE2-FAST-NEXT: {{  $}}
    ; AIE2-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; AIE2-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; AIE2-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<64 x s8>)
    ; AIE2-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; AIE2-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<128 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2-FAST-NEXT: $y2 = COPY [[BITCAST2]](<128 x s8>)
    ; AIE2-FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2P-GREEDY-LABEL: name: vconcat_1024_8
    ; AIE2P-GREEDY: liveins: $x0, $x2
    ; AIE2P-GREEDY-NEXT: {{  $}}
    ; AIE2P-GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; AIE2P-GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; AIE2P-GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<64 x s8>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; AIE2P-GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2P-GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<128 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2P-GREEDY-NEXT: $y2 = COPY [[BITCAST2]](<128 x s8>)
    ; AIE2P-GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; AIE2P-FAST-LABEL: name: vconcat_1024_8
    ; AIE2P-FAST: liveins: $x0, $x2
    ; AIE2P-FAST-NEXT: {{  $}}
    ; AIE2P-FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; AIE2P-FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; AIE2P-FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<64 x s8>)
    ; AIE2P-FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; AIE2P-FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<16 x s32>), [[BITCAST1]](<16 x s32>)
    ; AIE2P-FAST-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<128 x s8>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; AIE2P-FAST-NEXT: $y2 = COPY [[BITCAST2]](<128 x s8>)
    ; AIE2P-FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x2
    %3:_(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %4:_(<16 x s32>) = G_BITCAST %2(<64 x s8>)
    %6:_(<32 x s32>) = G_CONCAT_VECTORS %3(<16 x s32>), %4(<16 x s32>)
    %0:_(<128 x s8>) = G_BITCAST %6(<32 x s32>)
    $y2 = COPY %0(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2

...
