# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_select_s32
legalized: true
body: |
  bb.0:
    liveins: $r6, $r7, $r8
    ; CHECK-LABEL: name: test_select_s32
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r7
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r8
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprregbank(s32) = G_SELECT [[COPY]](s32), [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $r0 = COPY [[SELECT]](s32)
    %0:_(s32) = COPY $r6
    %1:_(s32) = COPY $r7
    %2:_(s32) = COPY $r8
    %3:_(s32) = G_SELECT %0, %1, %2
    $r0 = COPY %3
...

---
name: test_select_p0
legalized: true
body: |
  bb.0:
    liveins: $p0, $p1, $r6
    ; CHECK-LABEL: name: test_select_p0
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(p0) = COPY [[COPY2]](p0)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprregbank(p0) = G_SELECT [[COPY]](s32), [[COPY3]], [[COPY4]]
    ; CHECK-NEXT: $p0 = COPY [[SELECT]](p0)
    %0:_(s32) = COPY $r6
    %1:_(p0) = COPY $p0
    %2:_(p0) = COPY $p1
    %3:_(p0) = G_SELECT %0, %1, %2
    $p0 = COPY %3
...
