# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates


# RUN: llc -mtriple aie2 -run-pass=aie2-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck --check-prefix=COMMON %s
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck --check-prefix=COMMON %s


# Positive Test:
# Incoming Concat Values from the same MBB (bb.0), backedge is the same MBB as the PHI node
---
name:            ReferenceConcatUnmergePattern
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: ReferenceConcatUnmergePattern
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<32 x s32>) = G_PHI [[CONCAT_VECTORS]](<32 x s32>), %bb.0, %10(<32 x s32>), %bb.1
  ; COMMON-NEXT:   G_STORE [[PHI]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF3:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.1:

    %7:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %8(<16 x s32>), %bb.1
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %10(<16 x s32>), %bb.1
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %7(<16 x s32>), %9(<16 x s32>)
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr


...

# Positive Test:
# Incoming Concat Values from the same MBB (bb.0), backedge is a different MBB as the PHI node
---
name:            BackedgeDifferentMBB
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: BackedgeDifferentMBB
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.2(0x80000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<32 x s32>) = G_PHI [[CONCAT_VECTORS]](<32 x s32>), %bb.0, %10(<32 x s32>), %bb.2
  ; COMMON-NEXT:   G_STORE [[PHI]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF3:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.3
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.3:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.1:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.2:
    %7:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.1, %8(<16 x s32>), %bb.3
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.1, %10(<16 x s32>), %bb.3
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %7(<16 x s32>), %9(<16 x s32>)
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))

    bb.3:
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.2
    G_BR %bb.4

  bb.4:
    PseudoRET implicit $lr

...

# Positive Test:
# Multiple Unmerges feeding the phi node
---
name:            MultipleUnmerge
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: MultipleUnmerge
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<32 x s32>) = G_PHI [[CONCAT_VECTORS]](<32 x s32>), %bb.0, %10(<32 x s32>), %bb.1
  ; COMMON-NEXT:   G_STORE [[PHI]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF3:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.1:

    %7:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %8(<16 x s32>), %bb.1
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %12(<16 x s32>), %bb.1
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %7(<16 x s32>), %9(<16 x s32>)
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %11:_(<16 x s32>), %12:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Positive Test:
# empty MBB as concat phi target
---
name:            EmptyMBBConcatPHI
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: EmptyMBBConcatPHI
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $p0, $p1, $p2, $r0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.2(0x80000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<32 x s32>) = G_PHI [[CONCAT_VECTORS]](<32 x s32>), %bb.1, %10(<32 x s32>), %bb.2
  ; COMMON-NEXT:   G_STORE [[PHI]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF3:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.2
  ; COMMON-NEXT:   G_BR %bb.3
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.3:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.1:
    liveins: $p0, $p1, $p2, $r0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.2:

  bb.3:

    %7:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.2, %8(<16 x s32>), %bb.3
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.2, %10(<16 x s32>), %bb.3
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %7(<16 x s32>), %9(<16 x s32>)
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.3
    G_BR %bb.4

  bb.4:
    PseudoRET implicit $lr

...

# Positive Test:
# 4 vector unmerge/concat
---
name:            v4_Pattern
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: v4_Pattern
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF3:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[DEF1]](<8 x s32>), [[DEF2]](<8 x s32>), [[DEF3]](<8 x s32>)
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<32 x s32>) = G_PHI [[CONCAT_VECTORS]](<32 x s32>), %bb.0, %18(<32 x s32>), %bb.1
  ; COMMON-NEXT:   [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[PHI]](<32 x s32>)
  ; COMMON-NEXT:   G_STORE [[BITCAST]](<16 x s64>), %ptr(p0) :: (store (<16 x s64>))
  ; COMMON-NEXT:   [[DEF4:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF5:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<8 x s32>) = G_IMPLICIT_DEF
    %4:_(<8 x s32>) = G_IMPLICIT_DEF
    %5:_(<8 x s32>) = G_IMPLICIT_DEF
    %6:_(<8 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.1:

    %7:_(<8 x s32>) = G_PHI %3(<8 x s32>), %bb.0, %8(<8 x s32>), %bb.1
    %9:_(<8 x s32>) = G_PHI %4(<8 x s32>), %bb.0, %10(<8 x s32>), %bb.1
    %11:_(<8 x s32>) = G_PHI %5(<8 x s32>), %bb.0, %12(<8 x s32>), %bb.1
    %13:_(<8 x s32>) = G_PHI %6(<8 x s32>), %bb.0, %14(<8 x s32>), %bb.1
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %7(<8 x s32>), %9(<8 x s32>), %11(<8 x s32>), %13(<8 x s32>)
    %16:_(<16 x s64>) = G_BITCAST %15(<32 x s32>)
    G_STORE %16(<16 x s64>), %ptr(p0) :: (store (<16 x s64>))
    %17:_(<16 x s64>) = G_IMPLICIT_DEF
    %18:_(<32 x s32>) = G_BITCAST %17(<16 x s64>)
    %8:_(<8 x s32>), %10:_(<8 x s32>), %12:_(<8 x s32>), %14:_(<8 x s32>) = G_UNMERGE_VALUES %18(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Negative Test:
# not a loop.
---
name:            PhiDoesNotDominateUnmerges
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: PhiDoesNotDominateUnmerges
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; COMMON-NEXT:   liveins: $p0, $p1, $p2, $r0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY1]], [[C]]
  ; COMMON-NEXT:   G_BRCOND [[XOR]](s32), %bb.3
  ; COMMON-NEXT:   G_BR %bb.1
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.2(0x80000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   successors: %bb.3(0x80000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.3:
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, [[DEF1]](<16 x s32>), %bb.2
  ; COMMON-NEXT:   [[PHI1:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, [[DEF1]](<16 x s32>), %bb.2
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[PHI1]](<16 x s32>), [[PHI]](<16 x s32>)
  ; COMMON-NEXT:   G_STORE [[CONCAT_VECTORS]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $p0, $p1, $p2, $r0

    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(<32 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>), %4:_(<16 x s32>) = G_UNMERGE_VALUES %2(<32 x s32>)
    G_BRCOND %1(s32), %bb.1
    G_BR %bb.3

  bb.1:
    %12:_(<32 x s32>) = G_IMPLICIT_DEF
    %13:_(<16 x s32>), %14:_(<16 x s32>) = G_UNMERGE_VALUES %12(<32 x s32>)

  bb.2:

  bb.3:
    %5:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %13(<16 x s32>), %bb.2
    %6:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %14(<16 x s32>), %bb.2
    %35:_(<32 x s32>) = G_CONCAT_VECTORS %6(<16 x s32>), %5(<16 x s32>)
    G_STORE %35(<32 x s32>), %0(p0) :: (store (<32 x s32>))
    PseudoRET implicit $lr

...

# Negative Test:
# PHI is after Unmerge
---
name:            PHIAfterUnmerge
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: PHIAfterUnmerge
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $p0, $p1, $p2, $r0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, %4(<16 x s32>), %bb.4
  ; COMMON-NEXT:   [[PHI1:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.4
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[PHI]](<16 x s32>), [[PHI1]](<16 x s32>)
  ; COMMON-NEXT:   G_STORE [[CONCAT_VECTORS]](<32 x s32>), [[COPY1]](p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   G_BRCOND [[COPY]](s32), %bb.3
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   successors: %bb.4(0x80000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_BR %bb.4
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.3:
  ; COMMON-NEXT:   successors: %bb.4(0x80000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.4:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.5(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI2:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF1]](<16 x s32>), %bb.2, [[DEF2]](<16 x s32>), %bb.3
  ; COMMON-NEXT:   [[PHI3:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF1]](<16 x s32>), %bb.2, [[DEF2]](<16 x s32>), %bb.3
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[COPY]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.5
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.5:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.1:
    liveins: $p0, $p1, $p2, $r0

    %0:_(s32) = COPY $r0
    %1:_(p0) = COPY $p0
    %33:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.2:

    %5:_(<16 x s32>) = G_PHI %33(<16 x s32>), %bb.1, %60(<16 x s32>), %bb.5
    %6:_(<16 x s32>) = G_PHI %33(<16 x s32>), %bb.1, %61(<16 x s32>), %bb.5
    %7:_(<32 x s32>) = G_CONCAT_VECTORS %5(<16 x s32>), %6(<16 x s32>)
    G_STORE %7(<32 x s32>), %1(p0) :: (store (<32 x s32>))
    %27:_(<32 x s32>) = G_IMPLICIT_DEF

    G_BRCOND %0(s32), %bb.4
    G_BR %bb.3

  bb.3:
    %30:_(<16 x s32>), %31:_(<16 x s32>) = G_UNMERGE_VALUES %27(<32 x s32>)
    G_BR %bb.5

  bb.4:
    %40:_(<16 x s32>), %41:_(<16 x s32>) = G_UNMERGE_VALUES %27(<32 x s32>)

  bb.5:
    %60:_(<16 x s32>) = G_PHI %30(<16 x s32>), %bb.3, %40(<16 x s32>), %bb.4
    %61:_(<16 x s32>) = G_PHI %31(<16 x s32>), %bb.3, %41(<16 x s32>), %bb.4
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %0(s32)
    G_BRCOND %19(s1), %bb.2
    G_BR %bb.6

  bb.6:
    PseudoRET implicit $lr

...

# Negative Test:
# Unmerge parts are from the same source (SameUnmerge)
---
name:            UnmergeSameComponents
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: UnmergeSameComponents
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, %SameUnmerge(<16 x s32>), %bb.1
  ; COMMON-NEXT:   [[PHI1:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF1]](<16 x s32>), %bb.0, %SameUnmerge(<16 x s32>), %bb.1
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[PHI]](<16 x s32>), [[PHI1]](<16 x s32>)
  ; COMMON-NEXT:   G_STORE [[CONCAT_VECTORS]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   %SameUnmerge:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.1:

    %7:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %SameUnmerge(<16 x s32>), %bb.1
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %SameUnmerge(<16 x s32>), %bb.1
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %7(<16 x s32>), %9(<16 x s32>)
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %SameUnmerge:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Negative Test:
# Usage of the subvectors besides the concat
---
name:            MultipleUsesOfPHIReg
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: MultipleUsesOfPHIReg
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   %MultiUse:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.1
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF1]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.1
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS %MultiUse(<16 x s32>), [[PHI]](<16 x s32>)
  ; COMMON-NEXT:   G_STORE %MultiUse(<16 x s32>), %ptr(p0) :: (store (<16 x s32>))
  ; COMMON-NEXT:   G_STORE [[CONCAT_VECTORS]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.1:

    %MultiUse:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %8(<16 x s32>), %bb.1
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %10(<16 x s32>), %bb.1
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %MultiUse(<16 x s32>), %9(<16 x s32>)
    G_STORE %MultiUse(<16 x s32>), %ptr(p0) :: (store (<16 x s32>))
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Negative Test:
# Different Unmerge Sources
---
name:            DifferentUnmergeSources
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: DifferentUnmergeSources
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   %MultiUse:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.1
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF1]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.1
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS %MultiUse(<16 x s32>), [[PHI]](<16 x s32>)
  ; COMMON-NEXT:   G_STORE %MultiUse(<16 x s32>), %ptr(p0) :: (store (<16 x s32>))
  ; COMMON-NEXT:   G_STORE [[CONCAT_VECTORS]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.1:

    %MultiUse:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %8(<16 x s32>), %bb.1
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %12(<16 x s32>), %bb.1
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %MultiUse(<16 x s32>), %9(<16 x s32>)
    G_STORE %MultiUse(<16 x s32>), %ptr(p0) :: (store (<16 x s32>))
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %18:_(<32 x s32>) = G_IMPLICIT_DEF
    %11:_(<16 x s32>), %12:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Negative Test
# PHI node with 3 MBBs with Multiple Unmerge Sources
---
name:            ThreeMBBPHIMultipleUnmergeSources
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: ThreeMBBPHIMultipleUnmergeSources
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x80000000)
  ; COMMON-NEXT:   liveins: $r0, $p0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   %ptr:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY]](s32)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.1, %7(<16 x s32>), %bb.2
  ; COMMON-NEXT:   [[PHI1:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF1]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.1, %7(<16 x s32>), %bb.2
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[PHI]](<16 x s32>), [[PHI1]](<16 x s32>)
  ; COMMON-NEXT:   G_STORE [[CONCAT_VECTORS]](<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; COMMON-NEXT:   G_BRCOND [[INT]](s1), %bb.1
  ; COMMON-NEXT:   G_BR %bb.2
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[DEF3:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_BRCOND [[COPY]](s32), %bb.1
  ; COMMON-NEXT:   G_BR %bb.3
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.3:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $r0, $p0

    %0:_(s32) = COPY $r0
    %ptr:_(p0) = COPY $p0
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), %0(s32)

  bb.1:

    %7:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %8(<16 x s32>), %bb.1,  %11(<16 x s32>), %bb.2
    %9:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %10(<16 x s32>), %bb.1, %12(<16 x s32>), %bb.2
    %15:_(<32 x s32>) = G_CONCAT_VECTORS %7(<16 x s32>), %9(<16 x s32>)
    G_STORE %15(<32 x s32>), %ptr(p0) :: (store (<32 x s32>))
    %17:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %17(<32 x s32>)
    %19:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), %2(s32)
    G_BRCOND %19(s1), %bb.1
    G_BR %bb.2

  bb.2:
    %27:_(<32 x s32>) = G_IMPLICIT_DEF
    %11:_(<16 x s32>), %12:_(<16 x s32>) = G_UNMERGE_VALUES %27(<32 x s32>)
    G_BRCOND %0(s32), %bb.1
    G_BR %bb.3

  bb.3:
    PseudoRET implicit $lr


...

# Negative Test:
# PHI node with 3 MBBs with Multiple dominating Sources
---
name:            ThreeMBBPHIMultipleDominatingMBBs
alignment:       16
tracksRegLiveness: true
body:             |
  ; COMMON-LABEL: name: ThreeMBBPHIMultipleDominatingMBBs
  ; COMMON: bb.0:
  ; COMMON-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; COMMON-NEXT:   liveins: $p0, $p1, $p2, $r0
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; COMMON-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; COMMON-NEXT:   [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; COMMON-NEXT:   [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY1]], [[C]]
  ; COMMON-NEXT:   G_BRCOND [[XOR]](s32), %bb.2
  ; COMMON-NEXT:   G_BR %bb.1
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.1:
  ; COMMON-NEXT:   successors: %bb.2(0x80000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.2:
  ; COMMON-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, [[DEF1]](<16 x s32>), %bb.1, %9(<16 x s32>), %bb.2
  ; COMMON-NEXT:   [[PHI1:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF]](<16 x s32>), %bb.0, [[DEF1]](<16 x s32>), %bb.1, %9(<16 x s32>), %bb.2
  ; COMMON-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[PHI1]](<16 x s32>), [[PHI]](<16 x s32>)
  ; COMMON-NEXT:   G_STORE [[CONCAT_VECTORS]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>))
  ; COMMON-NEXT:   [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; COMMON-NEXT:   G_BRCOND [[COPY1]](s32), %bb.2
  ; COMMON-NEXT:   G_BR %bb.3
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT: bb.3:
  ; COMMON-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $p0, $p1, $p2, $r0

    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(<32 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>), %4:_(<16 x s32>) = G_UNMERGE_VALUES %2(<32 x s32>)
    G_BRCOND %1(s32), %bb.1
    G_BR %bb.2

  bb.1:
    %12:_(<32 x s32>) = G_IMPLICIT_DEF
    %13:_(<16 x s32>), %14:_(<16 x s32>) = G_UNMERGE_VALUES %12(<32 x s32>)

  bb.2:
    %5:_(<16 x s32>) = G_PHI %3(<16 x s32>), %bb.0, %13(<16 x s32>), %bb.1, %16(<16 x s32>), %bb.2
    %6:_(<16 x s32>) = G_PHI %4(<16 x s32>), %bb.0, %14(<16 x s32>), %bb.1, %17(<16 x s32>), %bb.2
    %35:_(<32 x s32>) = G_CONCAT_VECTORS %6(<16 x s32>), %5(<16 x s32>)
    G_STORE %35(<32 x s32>), %0(p0) :: (store (<32 x s32>))
    %15:_(<32 x s32>) = G_IMPLICIT_DEF
    %16:_(<16 x s32>), %17:_(<16 x s32>) = G_UNMERGE_VALUES %15(<32 x s32>)
    G_BRCOND %1(s32), %bb.2
    G_BR %bb.3

  bb.3:
    PseudoRET implicit $lr

...
