# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps %topdown-multi -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

---
name:            acq_vs_load
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: acq_vs_load
    ; CHECK: $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    ; CHECK-NEXT: $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    ; CHECK-NEXT: $r6 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    ACQ_mLockId_imm 0, $r0
    $r6 = LDA_dms_lda_scalar_ld_idx_imm $p1, 4
    $r6 = LDA_dms_lda_scalar_ld_idx_imm killed $p1, 4
...

---
name:            acq_vs_store
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: acq_vs_store
    ; CHECK: ST_dms_sts_scalar_st_idx_imm $r6, $p0, 0
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r6, $p0, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r6, $p0, 0
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm killed $r6, killed $p0, 4
    ; CHECK-NEXT: NOP
    ST_dms_sts_scalar_st_idx_imm $r6, $p0, 0
    ST_dms_sts_scalar_st_idx_imm $r6, $p0, 4
    ACQ_mLockId_imm 0, $r0
    ST_dms_sts_scalar_st_idx_imm $r6, $p0, 0
    ST_dms_sts_scalar_st_idx_imm killed $r6, killed $p0, 4
...
