# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps %topdown-multi -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

# Loads and stores should finish before a lock is taken or released

---
name:            load-acq
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: load-acq
    ; CHECK: renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_COND_mLockId_imm 0, $r0, $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_COND_mLockId_reg $r0, killed $r1, killed $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    ACQ_mLockId_imm 0, $r0
    renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    ACQ_mLockId_reg $r0, $r1
    renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    ACQ_COND_mLockId_imm 0, $r0, $r23
    renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    ACQ_COND_mLockId_reg $r0, $r1, $r23

    RET implicit $lr
    DelayedSchedBarrier implicit $r0

...
---
name:            store-acq
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: store-acq
    ; CHECK: ST_dms_sts_scalar_st_idx_imm killed renamable $r12, renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm killed renamable $r13, killed renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm killed renamable $r14, renamable $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_COND_mLockId_imm 0, $r0, $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm killed renamable $r15, killed renamable $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_COND_mLockId_reg killed $r0, killed $r1, killed $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
    ST_dms_sts_scalar_st_idx_imm killed renamable $r12, killed renamable $p0, 0
    ACQ_mLockId_imm 0, $r0
    ST_dms_sts_scalar_st_idx_imm killed renamable $r13, killed renamable $p0, 0
    ACQ_mLockId_reg $r0, $r1
    ST_dms_sts_scalar_st_idx_imm killed renamable $r14, renamable $p1, 0
    ACQ_COND_mLockId_imm 0, $r0, $r23
    ST_dms_sts_scalar_st_idx_imm killed renamable $r15, killed renamable $p1, 0
    ACQ_COND_mLockId_reg $r0, $r1, $r23
    RET implicit $lr
    DelayedSchedBarrier

...

---
name:            load-rel
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: load-rel
    ; CHECK: renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_reg $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_COND_mLockId_imm 0, $r0, $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_COND_mLockId_reg $r0, killed $r1, killed $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    REL_mLockId_imm 0, $r0
    renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    REL_mLockId_reg $r0, $r1
    renamable $r13 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    REL_COND_mLockId_imm 0, $r0, $r23
    renamable $r14 = LDA_dms_lda_scalar_ld_idx_imm killed renamable $p0, 0
    REL_COND_mLockId_reg $r0, $r1, $r23

    RET implicit $lr
    DelayedSchedBarrier implicit $r0

...
---
name:            store-rel
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: store-rel
    ; CHECK: ST_dms_sts_scalar_st_idx_imm killed renamable $r12, renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm killed renamable $r13, killed renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_reg $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm killed renamable $r14, renamable $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_COND_mLockId_imm 0, $r0, $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm killed renamable $r15, killed renamable $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_COND_mLockId_reg killed $r0, killed $r1, killed $r23
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
    ST_dms_sts_scalar_st_idx_imm killed renamable $r12, killed renamable $p0, 0
    REL_mLockId_imm 0, $r0
    ST_dms_sts_scalar_st_idx_imm killed renamable $r13, killed renamable $p0, 0
    REL_mLockId_reg $r0, $r1
    ST_dms_sts_scalar_st_idx_imm killed renamable $r14, killed renamable $p1, 0
    REL_COND_mLockId_imm 0, $r0, $r23
    ST_dms_sts_scalar_st_idx_imm killed renamable $r15, killed renamable $p1, 0
    REL_COND_mLockId_reg $r0, $r1, $r23
    RET implicit $lr
    DelayedSchedBarrier

...
