# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s

# Make sure DONE stays in place

---
name:            done
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: done
    ; CHECK: $r0 = LDA_dms_lda_scalar_ld_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm $r0, killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DONE
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    $r0 = LDA_dms_lda_scalar_ld_idx_imm $p0, 0
    ST_dms_sts_scalar_st_idx_imm $r0, $p1, 0
    DONE
    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...

# Check 6 cycle latency for DONE at region end.
---
name:            done_latency
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: done_latency
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   SCHED_BARRIER
  ; CHECK-NEXT:   DONE
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   SCHED_BARRIER
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   JL_lng 0, implicit-def $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier csr_aie2ps
  bb.0.entry:
    SCHED_BARRIER
    DONE
    SCHED_BARRIER
  bb.1:
    JL_lng 0, implicit-def $lr
    DelayedSchedBarrier csr_aie2ps
...
