# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass=postmisched %s -o - | FileCheck %s

# Tests the MOV slot bypass (MV_Bypass) for VMOV_alu_mv_mv_mv_x (128-bit moves).
# Bypass is available between X registers, but not for CM (coefficient memory)
# registers like BMLL, BMLH, BMHL, BMHH.

---
name:            bypass_x
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_x
    ; CHECK: $x1 = VMOV_alu_mv_mv_mv_x killed $x2
    ; CHECK-NEXT: $x0 = VMOV_alu_mv_mv_mv_x killed $x1
    ; CHECK-NEXT: NOP
    $x1 = VMOV_alu_mv_mv_mv_x $x2
    $x0 = VMOV_alu_mv_mv_mv_x $x1
...

---
name:            no_bypass_vmov_mv_x_cm
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_vmov_mv_x_cm
    ; CHECK: $bmll1 = VMOV_alu_mv_mv_mv_x killed $bmll0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmll2 = VMOV_alu_mv_mv_mv_x killed $bmll1
    ; CHECK-NEXT: NOP
    $bmll1 = VMOV_alu_mv_mv_mv_x $bmll0
    $bmll2 = VMOV_alu_mv_mv_mv_x $bmll1
...

---
name:            no_bypass_vmov_mv_x_cm_bmlh
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_vmov_mv_x_cm_bmlh
    ; CHECK: $bmlh1 = VMOV_alu_mv_mv_mv_x killed $bmlh0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmlh2 = VMOV_alu_mv_mv_mv_x killed $bmlh1
    ; CHECK-NEXT: NOP
    $bmlh1 = VMOV_alu_mv_mv_mv_x $bmlh0
    $bmlh2 = VMOV_alu_mv_mv_mv_x $bmlh1
...

---
name:            no_bypass_vmov_mv_x_cm_bmhl
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_vmov_mv_x_cm_bmhl
    ; CHECK: $bmhl1 = VMOV_alu_mv_mv_mv_x killed $bmhl0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmhl2 = VMOV_alu_mv_mv_mv_x killed $bmhl1
    ; CHECK-NEXT: NOP
    $bmhl1 = VMOV_alu_mv_mv_mv_x $bmhl0
    $bmhl2 = VMOV_alu_mv_mv_mv_x $bmhl1
...

---
name:            no_bypass_vmov_mv_x_cm_bmhh
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_vmov_mv_x_cm_bmhh
    ; CHECK: $bmhh1 = VMOV_alu_mv_mv_mv_x killed $bmhh0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmhh2 = VMOV_alu_mv_mv_mv_x killed $bmhh1
    ; CHECK-NEXT: NOP
    $bmhh1 = VMOV_alu_mv_mv_mv_x $bmhh0
    $bmhh2 = VMOV_alu_mv_mv_mv_x $bmhh1
...

---
name:            no_bypass_vmov_mv_x_from_cm_to_x
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_vmov_mv_x_from_cm_to_x
    ; CHECK: $bmll1 = VMOV_alu_mv_mv_mv_x killed $bmll0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VMOV_alu_mv_mv_mv_x killed $bmll1
    ; CHECK-NEXT: NOP
    $bmll1 = VMOV_alu_mv_mv_mv_x $bmll0
    $x0 = VMOV_alu_mv_mv_mv_x $bmll1
...
