; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2ps -O2 -o - %s | FileCheck %s

; Regression: post-RA scheduler emits 2 NOPs in the entry block after the
; cross-MBB ptr-add chain reuse pass converts an idx-load on the load
; chain into a pstm post-inc, extending the chain and serialising what
; used to be a parallel base read.
;
; Reference (pre-reuse) entry block: 1 NOP
;   lda r2, [p2], #4       ; pstm
;   lda r0, [p2], #4       ; pstm
;   lda r4, [p2], #8       ; pstm
;   lda r6, [p2], #4       ; pstm
;   lda r18, [p2, #0]      ; idx     <-- parallel base read, no chain
;   lda r1, [p1, #12]
;   nop
;   lda r16, [p2, #4]      ; idx     <-- parallel base read, no chain
;
; Regressed (cur) entry block: 2 NOPs
;   lda r1, [p1, #12]
;   lda r2, [p1], #4       ; pstm
;   lda r0, [p1], #4       ; pstm
;   lda r4, [p1], #8       ; pstm
;   lda r6, [p1], #4       ; pstm
;   lda r18, [p1], #4      ; pstm    <-- was idx in ref; chain extended
;   nop
;   nop                                <-- two filler cycles
;   lda r16, [p1, #0]      ; idx     <-- only surviving idx, blocked

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2ps-none-unknown-elf"

define void @setup(ptr noalias nonnull align 64 dereferenceable(72) %params, ptr noalias %rtps_void) local_unnamed_addr align 2 {
; CHECK-LABEL: setup:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda r1, [p1, #12]; nopxm
; CHECK-NEXT:    lda r2, [p1], #4
; CHECK-NEXT:    lda r0, [p1], #4
; CHECK-NEXT:    lda r4, [p1], #8
; CHECK-NEXT:    lda r6, [p1], #4
; CHECK-NEXT:    lda r18, [p1], #4
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r16, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r2, [p0], #4
; CHECK-NEXT:    st r0, [p0], #4
; CHECK-NEXT:    st r4, [p0], #4; mul r20, r18, r6
; CHECK-NEXT:    st r1, [p0], #4; jz r1, #.LBB0_2
; CHECK-NEXT:    st r6, [p0], #4 // Delay Slot 5
; CHECK-NEXT:    st r18, [p0], #4; mul r20, r20, r16 // Delay Slot 4
; CHECK-NEXT:    st r16, [p0], #8 // Delay Slot 3
; CHECK-NEXT:    mova r3, #0; st r20, [p0], #8 // Delay Slot 2
; CHECK-NEXT:    st r3, [p0, #0] // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %sw.work
; CHECK-NEXT:    mova r20, #-5
; CHECK-NEXT:    mova r22, #16; lshl r20, r4, r20
; CHECK-NEXT:    lshl r20, r20, r22
; CHECK-NEXT:    mova r24, #32; movxm r22, #-65536
; CHECK-NEXT:    mova m0, #8; add r20, r20, r22; mov p2, p0
; CHECK-NEXT:    padda [p2], m0; or r20, r20, r24
; CHECK-NEXT:    st r20, [p2], #-12
; CHECK-NEXT:    st r18, [p2], #20; mul r2, r0, r2
; CHECK-NEXT:    st r16, [p2], #4
; CHECK-NEXT:    st r2, [p2], #-8; mul r0, r4, r0
; CHECK-NEXT:    st r20, [p2], #-24
; CHECK-NEXT:    st r0, [p2, #0]
; CHECK-NEXT:    st r6, [p2, #16]
; CHECK-NEXT:  .LBB0_2: // %sw.epilog
; CHECK-NEXT:    mova m0, #4; nopx
; CHECK-NEXT:    padda [p1], m0
; CHECK-NEXT:    lda r0, [p1], #4; mov dj0, #30
; CHECK-NEXT:    st.s8 r0, [p0, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda.s16 r0, [p1, #0]; mov dj0, #28
; CHECK-NEXT:    st.s16 r0, [p0, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r0, [p1, #4]; mov dj0, #31
; CHECK-NEXT:    st.s8 r0, [p0, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = load i32, ptr %rtps_void, align 4
  store i32 %0, ptr %params, align 64
  %arrayidx1 = getelementptr inbounds i8, ptr %rtps_void, i20 4
  %1 = load i32, ptr %arrayidx1, align 4
  %sv_channel = getelementptr inbounds i8, ptr %params, i20 4
  store i32 %1, ptr %sv_channel, align 4
  %arrayidx2 = getelementptr inbounds i8, ptr %rtps_void, i20 8
  %2 = load i32, ptr %arrayidx2, align 4
  %sv_width = getelementptr inbounds i8, ptr %params, i20 8
  store i32 %2, ptr %sv_width, align 8
  %arrayidx3 = getelementptr inbounds i8, ptr %rtps_void, i20 12
  %3 = load i32, ptr %arrayidx3, align 4
  %reduce_axis = getelementptr inbounds i8, ptr %params, i20 12
  store i32 %3, ptr %reduce_axis, align 4
  %arrayidx4 = getelementptr inbounds i8, ptr %rtps_void, i20 16
  %4 = load i32, ptr %arrayidx4, align 4
  %loop_num_height = getelementptr inbounds i8, ptr %params, i20 16
  store i32 %4, ptr %loop_num_height, align 16
  %arrayidx5 = getelementptr inbounds i8, ptr %rtps_void, i20 20
  %5 = load i32, ptr %arrayidx5, align 4
  %loop_num_channel = getelementptr inbounds i8, ptr %params, i20 20
  store i32 %5, ptr %loop_num_channel, align 4
  %arrayidx6 = getelementptr inbounds i8, ptr %rtps_void, i20 24
  %6 = load i32, ptr %arrayidx6, align 4
  %loop_num_width = getelementptr inbounds i8, ptr %params, i20 24
  store i32 %6, ptr %loop_num_width, align 8
  %mul = mul i32 %5, %4
  %mul10 = mul i32 %mul, %6
  %all_loop_num = getelementptr inbounds i8, ptr %params, i20 32
  store i32 %mul10, ptr %all_loop_num, align 32
  %curr_depth_iter = getelementptr inbounds i8, ptr %params, i20 40
  store i32 0, ptr %curr_depth_iter, align 8
  %cmp = icmp eq i32 %3, 0
  br i1 %cmp, label %sw.epilog, label %sw.work

sw.work:
  %i_ptr_inc1 = getelementptr inbounds i8, ptr %params, i20 48
  %div248 = lshr i32 %2, 5
  %t7 = trunc i32 %div248 to i16
  %conv = add i16 %t7, -1
  %v8 = insertelement <2 x i16> <i16 32, i16 poison>, i16 %conv, i32 1
  store <2 x i16> %v8, ptr %i_ptr_inc1, align 16
  %loop_width = getelementptr inbounds i8, ptr %params, i20 36
  store i32 %5, ptr %loop_width, align 4
  %loop_width57 = getelementptr inbounds i8, ptr %params, i20 56
  store i32 %6, ptr %loop_width57, align 4
  %mul60 = mul i32 %1, %0
  %output_size61 = getelementptr inbounds i8, ptr %params, i20 60
  store i32 %mul60, ptr %output_size61, align 4
  %i_ptr_inc1105 = getelementptr inbounds i8, ptr %params, i20 52
  store <2 x i16> %v8, ptr %i_ptr_inc1105, align 4
  %mul119 = mul i32 %2, %1
  %output_size120 = getelementptr inbounds i8, ptr %params, i20 28
  store i32 %mul119, ptr %output_size120, align 4
  %loop_width122 = getelementptr inbounds i8, ptr %params, i20 44
  store i32 %4, ptr %loop_width122, align 4
  br label %sw.epilog

sw.epilog:
  %add.ptr = getelementptr inbounds i8, ptr %rtps_void, i20 28
  %v30 = load i32, ptr %add.ptr, align 4
  %conv.i = trunc i32 %v30 to i8
  %op_params.i = getelementptr inbounds i8, ptr %params, i20 68
  %shift_out.i = getelementptr inbounds i8, ptr %params, i20 70
  store i8 %conv.i, ptr %shift_out.i, align 2
  %arrayidx1.i = getelementptr inbounds i8, ptr %rtps_void, i20 32
  %v31 = load i16, ptr %arrayidx1.i, align 2
  store i16 %v31, ptr %op_params.i, align 4
  %arrayidx3.i = getelementptr inbounds i8, ptr %rtps_void, i20 36
  %v32 = load i32, ptr %arrayidx3.i, align 4
  %conv4.i = trunc i32 %v32 to i8
  %scale_shift.i = getelementptr inbounds i8, ptr %params, i20 71
  store i8 %conv4.i, ptr %scale_shift.i, align 1
  ret void
}
