# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2ps --issue-limit=6 --run-pass=postmisched \
# RUN:   --aie-latency-margin=0 \
# RUN:   --aie-loop-aware=false %s -o - | FileCheck %s

# We whould not trust successors if we have a call
---
name:            callConflict
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: callConflict
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r1 = LDA_dms_lda_scalar_ld_idx_imm killed $p0, 0
  ; CHECK-NEXT:   JL_lng 32, implicit-def $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $r2, $r3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r0 = OR killed $r2, $r3
  ; CHECK-NEXT:   $r0 = AND killed $r0, $r3
  ; CHECK-NEXT:   $r1 = OR $r0, $r3
  ; CHECK-NEXT:   $r1 = AND $r0, killed $r1
  ; CHECK-NEXT:   $r1 = OR killed $r1, killed $r0
  ; CHECK-NEXT:   $r1 = AND killed $r1, $r3
  ; CHECK-NEXT:   $r0 = OR killed $r1, killed $r3
  bb.0:
    successors: %bb.1
    liveins: $p0
    $r1 =  LDA_dms_lda_scalar_ld_idx_imm $p0, 0
    JL_lng  32, implicit-def $lr
    DelayedSchedBarrier
  bb.1:
    successors:
    liveins: $r2, $r3
    $r0 = OR $r2, $r3
    $r0 = AND $r0, $r3
    $r1 = OR $r0, $r3
    $r1 = AND $r0, $r1
    $r1 = OR $r1, $r0
    $r1 = AND $r1, $r3
    $r0 = OR $r1, $r3
...
