# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 --issue-limit=6 -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

# Streams should finish before a lock is taken or released

---
name:            scalar_stream_acq
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: scalar_stream_acq
    ; CHECK: renamable $r2 = MOV_mv_ss2scl implicit-def $srss0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_scl2ms_doTlast_reg killed renamable $r3, killed renamable $r28
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg $r0, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r3 = MOV_mv_ss2scl implicit-def $srss0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    renamable $r2 = MOV_mv_ss2scl implicit-def $srss0
    ACQ_mLockId_imm 0, $r0
    MOV_mv_scl2ms_doTlast_reg renamable $r3, killed renamable $r28
    ACQ_mLockId_reg $r0, $r1
    renamable $r3 = MOV_mv_ss2scl implicit-def $srss0

    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...

---
name:            scalar_stream_rel
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: scalar_stream_rel
    ; CHECK: renamable $r2 = MOV_mv_ss2scl implicit-def $srss0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_scl2ms_doTlast_reg killed renamable $r3, killed renamable $r28
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_reg $r0, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r3 = MOV_mv_ss2scl implicit-def $srss0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    renamable $r2 = MOV_mv_ss2scl implicit-def $srss0
    REL_mLockId_imm 0, $r0
    MOV_mv_scl2ms_doTlast_reg renamable $r3, killed renamable $r28
    REL_mLockId_reg $r0, $r1
    renamable $r3 = MOV_mv_ss2scl implicit-def $srss0

    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...

---
name:            cascade_stream_acq
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: cascade_stream_acq
    ; CHECK: $bml2 = VMOV_mv_scd implicit $crscden
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VMOV_mv_mcd killed $bml0, implicit $crmcden
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg killed $r0, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml4 = VMOV_mv_scd implicit $crscden
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $bml2 = VMOV_mv_scd implicit $crscden
    ACQ_mLockId_imm 0, $r0
    VMOV_mv_mcd $bml0, implicit $crmcden
    ACQ_mLockId_reg $r0, $r1
    $bml4 = VMOV_mv_scd implicit $crscden
...

---
name:            cascade_stream_rel
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: cascade_stream_rel
    ; CHECK: $bml2 = VMOV_mv_scd implicit $crscden
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VMOV_mv_mcd killed $bml0, implicit $crmcden
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml4 = VMOV_mv_scd implicit $crscden
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $bml2 = VMOV_mv_scd implicit $crscden
    REL_mLockId_imm 0, $r0
    VMOV_mv_mcd $bml0, implicit $crmcden
    REL_mLockId_imm 0, $r0
    $bml4 = VMOV_mv_scd implicit $crscden
...

---
name:            ACQ_II_MOV_PH_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ACQ_II_MOV_PH_B
    ; CHECK: MOV_mv_ph2ms $r0, 1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_ph2ms $r0, 1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg $r0, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_ph2ms killed $r0, 1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_mv_ph2ms $r0, 1
    ACQ_mLockId_imm 0, $r0
    MOV_mv_ph2ms $r0, 1
    ACQ_mLockId_reg $r0, $r1
    MOV_mv_ph2ms $r0, 1
...

---
name:            REL_II_MOV_PH_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: REL_II_MOV_PH_B
    ; CHECK: MOV_mv_ph2ms $r0, 1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_ph2ms $r0, 1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_ph2ms killed $r0, 1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_mv_ph2ms $r0, 1
    REL_mLockId_imm 0, $r0
    MOV_mv_ph2ms $r0, 1
    REL_mLockId_imm 0, $r0
    MOV_mv_ph2ms $r0, 1
...

---
name:            ACQ_II_MOV_PH_NB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ACQ_II_MOV_PH_NB
    ; CHECK: MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg killed $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms killed $r1, 1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    ACQ_mLockId_imm 0, $r0
    MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    ACQ_mLockId_reg $r0, $r1
    MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
...

---
name:            REL_II_MOV_PH_NB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: REL_II_MOV_PH_NB
    ; CHECK: MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms killed $r1, 1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_ph2ms $r1, 1, implicit-def $srms0
...

---
name:            ACQ_II_MOV_PH_NB_TLAST_REG
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ACQ_II_MOV_PH_NB_TLAST_REG
    ; CHECK: MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg killed $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms_doTlast_reg killed $r1, 1, killed $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    ACQ_mLockId_imm 0, $r0
    MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    ACQ_mLockId_reg $r0, $r1
    MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
...

---
name:            REL_II_MOV_PH_NB_TLAST_REG
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: REL_II_MOV_PH_NB_TLAST_REG
    ; CHECK: MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_ph2ms_doTlast_reg killed $r1, 1, killed $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_ph2ms_doTlast_reg $r1, 1, $r28, implicit-def $srms0
...


---
name:            ACQ_II_MOV_CPH_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ACQ_II_MOV_CPH_B
    ; CHECK: MOV_mv_cph2ms $m0, 1, 2, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_cph2ms $m0, 1, 2, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg $r0, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_cph2ms killed $m0, 1, 2, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_mv_cph2ms $m0, 1, 2, $r0
    ACQ_mLockId_imm 0, $r0
    MOV_mv_cph2ms $m0, 1, 2, $r0
    ACQ_mLockId_reg $r0, $r1
    MOV_mv_cph2ms $m0, 1, 2, $r0
...

---
name:            REL_II_MOV_CPH_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: REL_II_MOV_CPH_B
    ; CHECK: MOV_mv_cph2ms $m0, 1, 2, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_cph2ms $m0, 1, 2, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_mv_cph2ms killed $m0, 1, 2, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_mv_cph2ms $m0, 1, 2, $r0
    REL_mLockId_imm 0, $r0
    MOV_mv_cph2ms $m0, 1, 2, $r0
    REL_mLockId_imm 0, $r0
    MOV_mv_cph2ms $m0, 1, 2, $r0
...
---
name:            ACQ_II_MOV_CPH_NB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ACQ_II_MOV_CPH_NB
    ; CHECK: MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg killed $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms killed $m1, 1, 2, killed $r1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    ACQ_mLockId_imm 0, $r0
    MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    ACQ_mLockId_reg $r0, $r1
    MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
...

---
name:            REL_II_MOV_CPH_NB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: REL_II_MOV_CPH_NB
    ; CHECK: MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms killed $m1, 1, 2, killed $r1, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_cph2ms $m1, 1, 2, $r1, implicit-def $srms0
...

---
name:            ACQ_II_MOV_CPH_NB_TLAST_REG
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ACQ_II_MOV_CPH_NB_TLAST_REG
    ; CHECK: MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ACQ_mLockId_reg killed $r0, $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms_doTlast_reg killed $m1, 1, 2, killed $r1, killed $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    ACQ_mLockId_imm 0, $r0
    MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    ACQ_mLockId_reg $r0, $r1
    MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
...

---
name:            REL_II_MOV_CPH_NB_TLAST_REG
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: REL_II_MOV_CPH_NB_TLAST_REG
    ; CHECK: MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: MOV_NB_mv_cph2ms_doTlast_reg killed $m1, 1, 2, killed $r1, killed $r28, implicit-def $srms0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
    REL_mLockId_imm 0, $r0
    MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r1, $r28, implicit-def $srms0
...
