# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            call
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: call
    ; CHECK: JL 0, implicit-def $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier csr_aie2, implicit-def $r0
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r0 = ADD_add_r_ri killed renamable $r0, 1, implicit-def $srcarry
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $r0
    JL 0, implicit-def $lr
    DelayedSchedBarrier csr_aie2, implicit-def $r0
    renamable $r0 = ADD_add_r_ri killed renamable $r0, 1, implicit-def $srcarry
    RET implicit $lr
    DelayedSchedBarrier implicit $r0
...
