# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# RUN: llc --start-before=postmisched -mtriple=aie2 %s -o - | FileCheck %s

# Regression test: a load that defines a call's argument register must not be
# scheduled into that call's delay slots. AIE2 is an in-order exposed-pipeline
# machine with no interlocks; a scalar load has a multi-cycle def latency while
# a jl has only 5 delay slots, so a load in the call's delay shadow leaves the
# argument register stale when the callee reads it (a silent miscompile).
#
# This test feeds the post-RA scheduler (postmisched) directly. The int->float
# kernel calls the soft-float helper __floatsisf, whose integer argument is in
# r1. Verify the r1-defining load is emitted before the call, not in its delay
# slots.

--- |
  ; ModuleID = 'llvm/test/CodeGen/AIE/aie2/schedule/call-arg-not-in-delay-slot.mir'
  source_filename = "llvm/test/CodeGen/AIE/aie2/schedule/call-arg-not-in-delay-slot.mir"
  target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
  target triple = "aie2"

  define void @add_one(ptr %input, ptr %output, i32 %tile_size) {
  ; CHECK-LABEL: add_one:
  ; CHECK:       // %bb.0: // %entry
  ; CHECK-NEXT:    paddb [sp], #128; nopxm
  ; CHECK-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill
  ; CHECK-NEXT:    st r18, [sp, #-52] // 4-byte Folded Spill
  ; CHECK-NEXT:    st r16, [sp, #-60] // 4-byte Folded Spill
  ; CHECK-NEXT:    mova r17, #0; st r17, [sp, #-56] // 4-byte Folded Spill
  ; CHECK-NEXT:    ge r0, r17, r0; mov r16, r0
  ; CHECK-NEXT:    st r19, [sp, #-48]; jnz r0, #.LBB0_3 // 4-byte Folded Spill
  ; CHECK-NEXT:    st r20, [sp, #-44] // 4-byte Folded Spill Delay Slot 5
  ; CHECK-NEXT:    st r21, [sp, #-40] // 4-byte Folded Spill Delay Slot 4
  ; CHECK-NEXT:    st r22, [sp, #-36] // 4-byte Folded Spill Delay Slot 3
  ; CHECK-NEXT:    st p6, [sp, #-32] // 4-byte Folded Spill Delay Slot 2
  ; CHECK-NEXT:    st p7, [sp, #-28] // 4-byte Folded Spill Delay Slot 1
  ; CHECK-NEXT:  // %bb.1:
  ; CHECK-NEXT:    mova r18, #0; movxm r0, #1065353216
  ; CHECK-NEXT:    mov r29, r18
  ; CHECK-NEXT:    vinsert.32 x0, x0, r29, r0
  ; CHECK-NEXT:    vmov bmh0, x0
  ; CHECK-NEXT:    mov p6, p0
  ; CHECK-NEXT:    vst amhl0, [sp, #-128]; mov p7, p1 // 32-byte Folded Spill
  ; CHECK-NEXT:    mova r20, #28; vst amhh0, [sp, #-96]; movx r19, #2; mov r21, r18 // 32-byte Folded Spill
  ; CHECK-NEXT:  .LBB0_2: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; lshl r0, r17, r19
  ; CHECK-NEXT:    mov dj0, r0
  ; CHECK-NEXT:    lda r1, [p6, dj0]
  ; CHECK-NEXT:    jl #__floatsisf
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    mov r22, r0 // Delay Slot 1
  ; CHECK-NEXT:    vlda amhl1, [sp, #-128]; nopb ; nopxm ; nops // 32-byte Folded Reload
  ; CHECK-NEXT:    vlda amhh1, [sp, #-96] // 32-byte Folded Reload
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    mov r29, r21
  ; CHECK-NEXT:    vinsert.32 x0, x0, r29, r0
  ; CHECK-NEXT:    vmov bmh0, x0; vadd.f bmh1, bmh0, bmh1, r20
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    jl #__fixsfsi
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    vmov x2, bmh1 // Delay Slot 3
  ; CHECK-NEXT:    vextract.s32 r1, x2, r18 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  ; CHECK-NEXT:    nopa ; nopb ; add r17, r17, #1
  ; CHECK-NEXT:    eq r1, r16, r17
  ; CHECK-NEXT:    jz r1, #.LBB0_2
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    mov dj0, r22 // Delay Slot 2
  ; CHECK-NEXT:    st r0, [p7, dj0] // Delay Slot 1
  ; CHECK-NEXT:  .LBB0_3: // %for.cond.cleanup
  ; CHECK-NEXT:    lda p7, [sp, #-28]; nopb ; nopxm // 4-byte Folded Reload
  ; CHECK-NEXT:    lda p6, [sp, #-32] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda r22, [sp, #-36] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda r21, [sp, #-40] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda r20, [sp, #-44] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda r19, [sp, #-48] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda r18, [sp, #-52] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda r17, [sp, #-56] // 4-byte Folded Reload
  ; CHECK-NEXT:    lda r16, [sp, #-60] // 4-byte Folded Reload
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    paddb [sp], #-128 // Delay Slot 1
  entry:
    %cmp6 = icmp sgt i32 %tile_size, 0
    br i1 %cmp6, label %for.body.preheader, label %for.cond.cleanup

  for.body.preheader:                               ; preds = %entry
    br label %for.body

  for.cond.cleanup:                                 ; preds = %for.body, %entry
    ret void

  for.body:                                         ; preds = %for.body.preheader, %for.body
    %i.07 = phi i32 [ %inc, %for.body ], [ 0, %for.body.preheader ]
    %arrayidx = getelementptr inbounds i32, ptr %input, i32 %i.07
    %0 = load i32, ptr %arrayidx, align 4
    %conv = sitofp i32 %0 to float
    %add = fadd float %conv, 1.000000e+00
    %conv1 = fptosi float %add to i32
    %arrayidx2 = getelementptr inbounds i32, ptr %output, i32 %i.07
    store i32 %conv1, ptr %arrayidx2, align 4
    %inc = add nuw nsw i32 %i.07, 1
    %exitcond.not = icmp eq i32 %tile_size, %inc
    br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
  }

...
---
name:            add_one
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: true
registers:       []
liveins:         []
calleeSavedRegisters: [ '$lr', '$r16', '$r17', '$r18', '$r19', '$r20',
                        '$r21', '$r22', '$r23', '$p6', '$p7' ]
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       128
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    true
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: true
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, name: '', type: spill-slot, offset: 32, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 3, name: '', type: spill-slot, offset: 64, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$lr', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 4, name: '', type: spill-slot, offset: 68, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r16', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 5, name: '', type: spill-slot, offset: 72, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r17', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 6, name: '', type: spill-slot, offset: 76, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r18', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 7, name: '', type: spill-slot, offset: 80, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r19', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 8, name: '', type: spill-slot, offset: 84, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r20', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 9, name: '', type: spill-slot, offset: 88, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r21', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 10, name: '', type: spill-slot, offset: 92, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r22', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 11, name: '', type: spill-slot, offset: 96, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$p6', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 12, name: '', type: spill-slot, offset: 100, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$p7', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.0.entry:
    successors: %bb.1(0x50000000), %bb.3(0x30000000)
    liveins: $p0, $p1, $r0, $r16, $r17, $r18, $r19, $r20, $r21, $r22, $p6, $p7

    frame-setup PADD_sp_imm_pseudo 128, implicit-def $sp, implicit $sp
    ST_dms_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.3)
    ST_dms_spill killed $r16, -60, implicit $sp :: (store (s32) into %stack.4)
    ST_dms_spill killed $r17, -56, implicit $sp :: (store (s32) into %stack.5)
    ST_dms_spill killed $r18, -52, implicit $sp :: (store (s32) into %stack.6)
    ST_dms_spill killed $r19, -48, implicit $sp :: (store (s32) into %stack.7)
    ST_dms_spill killed $r20, -44, implicit $sp :: (store (s32) into %stack.8)
    ST_dms_spill killed $r21, -40, implicit $sp :: (store (s32) into %stack.9)
    ST_dms_spill killed $r22, -36, implicit $sp :: (store (s32) into %stack.10)
    ST_dms_spill killed $p6, -32, implicit $sp :: (store (s32) into %stack.11)
    ST_dms_spill killed $p7, -28, implicit $sp :: (store (s32) into %stack.12)
    renamable $r17 = MOV_RLC_imm10_pseudo 0
    $r16 = MOV_SCL_pseudo $r0
    renamable $r0 = GE renamable $r17, $r0
    JNZ killed renamable $r0, %bb.3
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p0, $p1, $r16, $r17

    $p6 = MOV_mv_scl $p0
    $p7 = MOV_mv_scl $p1
    renamable $r0 = MOVXM_lng_cg 1065353216
    renamable $r18 = MOV_RLC_imm10_pseudo 0
    $r29 = MOV_SCL_pseudo $r18
    $r21 = MOV_SCL_pseudo $r18
    renamable $x0 = VINSERT_32 undef renamable $x0, killed renamable $r29, killed renamable $r0
    renamable $r19 = MOV_RLC_imm10_pseudo 2
    $bmh0 = VMOV_mv_x killed $x0
    VST_dmw_sts_am_ag_spill killed renamable $amhl0, -128, implicit $sp :: (store (s256) into %stack.1)
    VST_dmw_sts_am_ag_spill killed renamable $amhh0, -96, implicit $sp :: (store (s256) into %stack.2)
    renamable $r20 = MOV_RLC_imm10_pseudo 28

  bb.2.for.body:
    successors: %bb.3(0x04000000), %bb.2(0x7c000000)
    liveins: $p6, $p7, $r16, $r17, $r18, $r19, $r20, $r21

    renamable $r0 = LSHL renamable $r17, renamable $r19
    $dj0 = MOV_mv_scl $r0
    renamable $r1 = LDA_dms_lda_idx renamable $p6, renamable $dj0 :: (load (s32) from %ir.arrayidx)
    $r22 = MOV_SCL_pseudo $r0
    JL &__floatsisf, implicit-def $lr
    DelayedSchedBarrier csr_aie2, implicit $r1, implicit-def $r0
    $r29 = MOV_SCL_pseudo $r21
    renamable $x0 = VINSERT_32 undef renamable $x0, killed renamable $r29, killed renamable $r0
    $bmh0 = VMOV_mv_x killed $x0
    renamable $amhl1 = VLDA_dmw_lda_am_ag_spill -128, implicit $sp :: (load (s256) from %stack.1)
    renamable $amhh1 = VLDA_dmw_lda_am_ag_spill -96, implicit $sp :: (load (s256) from %stack.2)
    renamable $bmh1 = VADD_F killed renamable $bmh0, killed renamable $bmh1, renamable $r20, implicit-def dead $srfpflags, implicit $crfpmask
    $x2 = VMOV_mv_x killed $bmh1
    renamable $r1 = VEXTRACT_S32 killed renamable $x2, renamable $r18
    JL &__fixsfsi, implicit-def $lr
    DelayedSchedBarrier csr_aie2, implicit $r1, implicit-def $r0
    renamable $r17 = nuw nsw ADD_add_r_ri killed renamable $r17, 1, implicit-def dead $srcarry
    renamable $r1 = EQ renamable $r16, renamable $r17
    $dj0 = MOV_mv_scl killed $r22
    ST_dms_sts_idx killed renamable $r0, renamable $p7, killed renamable $dj0 :: (store (s32) into %ir.arrayidx2)
    JZ killed renamable $r1, %bb.2
    DelayedSchedBarrier

  bb.3.for.cond.cleanup:
    $p7 = LDA_dms_spill -28, implicit $sp :: (load (s32) from %stack.12)
    $p6 = LDA_dms_spill -32, implicit $sp :: (load (s32) from %stack.11)
    $r22 = LDA_dms_spill -36, implicit $sp :: (load (s32) from %stack.10)
    $r21 = LDA_dms_spill -40, implicit $sp :: (load (s32) from %stack.9)
    $r20 = LDA_dms_spill -44, implicit $sp :: (load (s32) from %stack.8)
    $r19 = LDA_dms_spill -48, implicit $sp :: (load (s32) from %stack.7)
    $r18 = LDA_dms_spill -52, implicit $sp :: (load (s32) from %stack.6)
    $r17 = LDA_dms_spill -56, implicit $sp :: (load (s32) from %stack.5)
    $r16 = LDA_dms_spill -60, implicit $sp :: (load (s32) from %stack.4)
    $lr = LDA_dms_spill -64, implicit $sp :: (load (s32) from %stack.3)
    frame-destroy PADD_sp_imm_pseudo -128, implicit-def $sp, implicit $sp
    RET implicit $lr
    DelayedSchedBarrier

...
