# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2  -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s

# mul has late use of GPR write port
---
name:            mix
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: mix
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r12 = MUL_mul_r_rr $r0, $r0
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   $r13 = CLB $r0
  ; CHECK-NEXT:   $r14 = CLB $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r12 = MUL_mul_r_rr $r1, $r1
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   $r13 = CLZ killed $r0
  ; CHECK-NEXT:   $r14 = CLZ killed $r1
  bb.0.entry:
    liveins: $r0, $r1
    $r12 = MUL_mul_r_rr $r0, $r0
    $r13 = CLB $r0
    $r14 = CLB $r1
  bb.1:
    liveins: $r0, $r1
    $r12 = MUL_mul_r_rr $r1, $r1
    $r13 = CLZ $r0
    $r14 = CLZ $r1
...
