# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2 -run-pass=postmisched %s -o - | FileCheck %s


# This is an explicit test for the optimized slot conflict detection
# On aie2, this centers around XM conflicting with X and M, but not with others.
# also, X should not conflict with M
# The code below generates two bundles, one lda + lng, one alu + mv

---
name:            f
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: f
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r1 = MOVX_alu_cg 1
  ; CHECK-NEXT:   $r2 = MOVXM_lng_cg 12345
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r1 = MOV_mv_scl $r0
  ; CHECK-NEXT:   $r2 = MOVXM_lng_cg 12345
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $r2 {
  ; CHECK-NEXT:     $r1 = MOVA_lda_cg 2
  ; CHECK-NEXT:     $r2 = MOVXM_lng_cg 12345
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $r2, implicit killed $r0 {
  ; CHECK-NEXT:     $r1 = MOVX_alu_cg 1
  ; CHECK-NEXT:     $r2 = MOV_mv_scl killed $r0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $r1, implicit killed $r2
  bb.0:
    liveins: $r0
    $r1 = MOVX_alu_cg 1
    $r2 = MOVXM_lng_cg 12345

  bb.1:
    liveins: $r0
    $r1 = MOV_mv_scl $r0
    $r2 = MOVXM_lng_cg 12345

  bb.2:
    liveins: $r0
    $r1 = MOVA_lda_cg 2
    $r2 = MOVXM_lng_cg 12345

  bb.3:
    liveins: $r0
    $r1 = MOVX_alu_cg 1
    $r2 = MOV_mv_scl $r0

    RET implicit $lr
    DelayedSchedBarrier implicit $r1, implicit $r2
...
