# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s
# RUN: llc -mtriple=aie2 -run-pass=postmisched %topdown-multi-negative-lat %s -o - | FileCheck %s --check-prefix=CHECK-NEG-LAT

---
name:            test_inputs
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r2, $r12, $r31, $p1
    ; CHECK-LABEL: name: test_inputs
    ; CHECK: liveins: $r0, $r2, $r12, $r31, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r31 = LDA_dms_lda_idx_imm $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: BUNDLE implicit-def $r0, implicit-def $r12, implicit-def $r31, implicit $p1, implicit killed $r31, implicit killed $r2 {
    ; CHECK-NEXT:   $r0 = LDA_dms_lda_idx_imm $p1, 4
    ; CHECK-NEXT:   $r12, $r31 = DIVS killed $r31, internal $r0, killed $r2
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: BUNDLE implicit-def $r2, implicit-def $r12, implicit-def $r31, implicit killed $p1, implicit killed $r31, implicit $r0 {
    ; CHECK-NEXT:   $r2 = LDA_dms_lda_idx_imm killed $p1, 8
    ; CHECK-NEXT:   $r12, $r31 = DIVS killed $r31, $r0, internal $r2
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r12, $r31 = DIVS killed $r31, killed $r0, killed $r2
    ; CHECK-NEG-LAT-LABEL: name: test_inputs
    ; CHECK-NEG-LAT: liveins: $r0, $r2, $r12, $r31, $p1
    ; CHECK-NEG-LAT-NEXT: {{  $}}
    ; CHECK-NEG-LAT: $r31 = LDA_dms_lda_idx_imm $p1, 0
    ; CHECK-NEG-LAT-NEXT: $r0 = LDA_dms_lda_idx_imm $p1, 4
    ; CHECK-NEG-LAT-NEXT: $r2 = LDA_dms_lda_idx_imm killed $p1, 8
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: $r12, $r31 = DIVS killed $r31, $r0, $r2
    ; CHECK-NEG-LAT-NEXT: $r12, $r31 = DIVS killed $r31, $r0, $r2
    ; CHECK-NEG-LAT-NEXT: $r12, $r31 = DIVS killed $r31, killed $r0, killed $r2
    $r31 = LDA_dms_lda_idx_imm $p1, 0
    $r12, $r31 = DIVS  $r31, $r0, $r2
    $r0 = LDA_dms_lda_idx_imm $p1, 4
    $r12, $r31 = DIVS  $r31, $r0, $r2
    $r2 = LDA_dms_lda_idx_imm $p1, 8
    $r12, $r31 = DIVS  $r31, $r0, $r2
...


---
name:            test_outputs
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r2, $r12, $r31, $p1
    ; CHECK-LABEL: name: test_outputs
    ; CHECK: liveins: $r0, $r2, $r12, $r31, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r12, $r31 = DIVS killed $r31, $r0, $r2
    ; CHECK-NEXT: BUNDLE implicit-def $r12, implicit-def $r31, implicit killed $r12, implicit $p1, implicit killed $r31, implicit killed $r0, implicit killed $r2 {
    ; CHECK-NEXT:   ST_dms_sts_idx_imm killed $r12, $p1, 0
    ; CHECK-NEXT:   $r12, $r31 = DIVS killed $r31, killed $r0, killed $r2
    ; CHECK-NEXT: }
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r31, killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEG-LAT-LABEL: name: test_outputs
    ; CHECK-NEG-LAT: liveins: $r0, $r2, $r12, $r31, $p1
    ; CHECK-NEG-LAT-NEXT: {{  $}}
    ; CHECK-NEG-LAT: $r12, $r31 = DIVS killed $r31, $r0, $r2
    ; CHECK-NEG-LAT-NEXT: BUNDLE implicit-def $r12, implicit-def $r31, implicit killed $r12, implicit $p1, implicit killed $r31, implicit killed $r0, implicit killed $r2 {
    ; CHECK-NEG-LAT-NEXT: ST_dms_sts_idx_imm killed $r12, $p1, 0
    ; CHECK-NEG-LAT-NEXT: $r12, $r31 = DIVS killed $r31, killed $r0, killed $r2
    ; CHECK-NEG-LAT-NEXT: }
    ; CHECK-NEG-LAT-NEXT: ST_dms_sts_idx_imm killed $r31, killed $p1, 0
    ; CHECK-NEG-LAT-NEXT: NOP
    $r12, $r31 = DIVS  $r31, $r0, $r2
    ST_dms_sts_idx_imm $r12, $p1, 0
    $r12, $r31 = DIVS  $r31, $r0, $r2
    ST_dms_sts_idx_imm $r31, $p1, 0
...
