# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name: mix
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: mix
    ; CHECK: $r6 = LDA_dms_lda_idx_imm killed $p0, 4
    ; CHECK-NEXT: $r7 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MUL_mul_r_rr killed $r6, killed $r7
    ; CHECK-NEXT: NOP
    $r6 = LDA_dms_lda_idx_imm $p0, 4
    $r7 = LDA_dms_lda_idx_imm $p1, 4
    $r0 = MUL_mul_r_rr $r6, $r7

...
