# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            ag_idx_imm
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ag_idx_imm
    ; CHECK: $amll0 = VLDA_dmw_lda_am_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p1, 0
    ; CHECK-NEXT: NOP
    $amll0 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
    VST_dmw_sts_am_ag_idx_imm $amll0, $p1, 0
...

---
name:            ag_spill
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ag_spill
    ; CHECK: $amll0 = VLDA_dmw_lda_am_ag_spill 0, implicit $sp
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_spill killed $amll0, 0, implicit $sp
    ; CHECK-NEXT: NOP
    $amll0 = VLDA_dmw_lda_am_ag_spill 0, implicit $sp
    VST_dmw_sts_am_ag_spill $amll0, 0, implicit $sp
...
