# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s
# RUN: llc -march=aie2 -run-pass=postmisched %topdown-multi-negative-lat %s -o - | FileCheck %s --check-prefix=CHECK-NEG-LAT

# This test shows how ordered load/stores are handled.
# In most cases, we just need to keep them one cycle appart, but for example
# VST.SRS stores 2 cycles later than a normal VST, so we need to have the two
# stores 3 cycles apart, instead of the normal 1 cycle.

# Note that in AIE2, all load instructions have the same behavior and read
# memory in E5. Therefore, we'll only test using LDA_dms_lda_idx_imm and
# VLDB_dmw_ldb_ag_idx_imm as representatives.

# Test organization: VST_PACK against
# - E5  loads (LDA_dms_lda_idx_imm and VLDB_dmw_ldb_ag_idx_imm)
# - E5  stores (ST_dms_sts_idx_imm)
# - E7  stores (VST_SRS_D8_S32_ag_idx_imm or VST_CONV_BF16_FP32_ag_idx_imm)
# - E11 stores (ST_S8_ag_idx_imm)


# !!! TODO !!! Uncomment post-inc tests when the instructions are defined


# Tests II_VST_PACK, II_VST_POSTINC_PACK, II_VST_2D_PACK, II_VST_3D_PACK
# against E5 loads.
---
name:            PACK_STORE_E5_LOAD_E5
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: PACK_STORE_E5_LOAD_E5
    ; CHECK: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEXT:   $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEXT:   $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEXT:   $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEXT:   $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEG-LAT-LABEL: name: PACK_STORE_E5_LOAD_E5
    ; CHECK-NEG-LAT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEG-LAT-NEXT: $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEG-LAT-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEG-LAT-NEXT: }
    ; CHECK-NEG-LAT-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEG-LAT-NEXT: $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEG-LAT-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEG-LAT-NEXT: }
    ; CHECK-NEG-LAT-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEG-LAT-NEXT: $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEG-LAT-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEG-LAT-NEXT: }
    ; CHECK-NEG-LAT-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEG-LAT-NEXT: $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEG-LAT-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEG-LAT-NEXT: }
    ; CHECK-NEG-LAT-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: BUNDLE implicit-def $r2, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEG-LAT-NEXT: $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    ; CHECK-NEG-LAT-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEG-LAT-NEXT: }
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $p2, $dc0 = VST_2D_PACK_D4_D8 $p2, $d0, $x0, implicit $crsat, implicit $crpacksign
    $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 $p3, $d1_3d, $x0, implicit $crsat, implicit $crpacksign
    $r2 = LDA_dms_lda_idx_imm $p0, 0 :: (load (s32), addrspace 6)
    $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

# Tests II_VST_PACK, II_VST_POSTINC_PACK, II_VST_2D_PACK, II_VST_3D_PACK
# against E5 stores.
---
name:            PACK_STORE_E5_STORE_E5
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: PACK_STORE_E5_STORE_E5
    ; CHECK: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r2, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEG-LAT-LABEL: name: PACK_STORE_E5_STORE_E5
    ; CHECK-NEG-LAT: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_dms_sts_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_dms_sts_idx_imm killed $r2, killed $p0, 0
    ; CHECK-NEG-LAT-NEXT: NOP
    ST_dms_sts_idx_imm $r2, $p0, 0
    VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ST_dms_sts_idx_imm $r2, $p0, 0
    $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ST_dms_sts_idx_imm $r2, $p0, 0
    $p2, $dc0 = VST_2D_PACK_D4_D8 $p2, $d0, $x0, implicit $crsat, implicit $crpacksign
    ST_dms_sts_idx_imm $r2, $p0, 0
    $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 $p3, $d1_3d, $x0, implicit $crsat, implicit $crpacksign
    ST_dms_sts_idx_imm $r2, $p0, 0
...

# Tests II_VST_PACK, II_VST_POSTINC_PACK, II_VST_2D_PACK, II_VST_3D_PACK
# against E7 stores.
---
name:            PACK_STORE_E5_STORE_E7
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: PACK_STORE_E5_STORE_E7
    ; CHECK: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEG-LAT-LABEL: name: PACK_STORE_E5_STORE_E7
    ; CHECK-NEG-LAT: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEG-LAT-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEG-LAT-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEG-LAT-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: VST_SRS_D8_S32_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEG-LAT-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p2, $dc0 = VST_2D_PACK_D4_D8 $p2, $d0, $x0, implicit $crsat, implicit $crpacksign
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 $p3, $d1_3d, $x0, implicit $crsat, implicit $crpacksign
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...


# Tests II_VST_PACK, II_VST_POSTINC_PACK, II_VST_2D_PACK, II_VST_3D_PACK
# against E11 stores.
---
name:            PACK_STORE_E5_STORE_E11
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: PACK_STORE_E5_STORE_E11
    ; CHECK: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: ST_S8_ag_idx_imm killed $r2, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEG-LAT-LABEL: name: PACK_STORE_E5_STORE_E11
    ; CHECK-NEG-LAT: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm killed $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: $p2, $dc0 = VST_2D_PACK_D4_D8 killed $p2, killed $d0, $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_S8_ag_idx_imm $r2, $p0, 0
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 killed $p3, killed $d1_3d, killed $x0, implicit $crsat, implicit $crpacksign
    ; CHECK-NEG-LAT-NEXT: ST_S8_ag_idx_imm killed $r2, killed $p0, 0
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ; CHECK-NEG-LAT-NEXT: NOP
    ST_S8_ag_idx_imm $r2, $p0, 0
    VST_PACK_D4_D8_ag_idx_imm $p0, 0, $x0, implicit $crsat, implicit $crpacksign
    ST_S8_ag_idx_imm $r2, $p0, 0
    $p1 = VST_PACK_D4_D8_ag_pstm_nrm_imm $p1, 0, $x0, implicit $crsat, implicit $crpacksign
    ST_S8_ag_idx_imm $r2, $p0, 0
    $p2, $dc0 = VST_2D_PACK_D4_D8 $p2, $d0, $x0, implicit $crsat, implicit $crpacksign
    ST_S8_ag_idx_imm $r2, $p0, 0
    $p3, $dc1, $dc5 = VST_3D_PACK_D4_D8 $p3, $d1_3d, $x0, implicit $crsat, implicit $crpacksign
    ST_S8_ag_idx_imm $r2, $p0, 0
...
