# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -issue-limit=6 -o - | FileCheck %s

# Note the NOP in the first cycle. There is a one-cycle dep between the
# instructions. This pushes VST in the second cycle. Given that meta
# instructions aren't emitted, a NOP is required.
---
name:            IMPLICIT_DEF_RAW
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: IMPLICIT_DEF_RAW
    ; CHECK: NOP
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $wl0 = IMPLICIT_DEF
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...

---
name:            IMPLICIT_DEF_WAR
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: IMPLICIT_DEF_WAR
    ; CHECK: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: NOP
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
    $wl0 = IMPLICIT_DEF
...

---
name:            IMPLICIT_DEF_WAW
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: IMPLICIT_DEF_WAW
    ; CHECK: NOP
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: $wl0 = VMOV_mv_w killed $wh0
    ; CHECK-NEXT: NOP
    $wl0 = IMPLICIT_DEF
    $wl0 = VMOV_mv_w $wh0
...

---
name:            IMPLICIT_DEF_WAW_reversed
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: IMPLICIT_DEF_WAW_reversed
    ; CHECK: $wl0 = VMOV_mv_w killed $wh0
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: NOP
    $wl0 = VMOV_mv_w $wh0
    $wl0 = IMPLICIT_DEF
...

---
name:            IMPLICIT_DEF_WAW_double
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: IMPLICIT_DEF_WAW_double
    ; CHECK: NOP
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = IMPLICIT_DEF
    $wl0 = IMPLICIT_DEF
    $x0 = IMPLICIT_DEF
...

---
name:            KILL_RAW
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: KILL_RAW
    ; CHECK: $wl0 = VMOV_mv_w killed $wh0
    ; CHECK-NEXT: KILL killed $wl0
    ; CHECK-NEXT: NOP
    $wl0 = VMOV_mv_w $wh0
    KILL $wl0
...

---
name:            KILL_WAR
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: KILL_WAR
    ; CHECK: $wl0 = VMOV_mv_w killed $wh0
    ; CHECK-NEXT: KILL killed $wl0
    ; CHECK-NEXT: NOP
    KILL $wl0
    $wl0 = VMOV_mv_w $wh0
...
