# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -issue-limit=6 -o - | FileCheck %s

---
name:            latency_mov_d1
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_mov_d1
    ; CHECK: $r6 = MOV_mv_cg 10
    ; CHECK-NEXT: $r7 = MOV_D1 killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r7, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r6 = MOV_mv_cg 10
    $r7  = MOV_D1 $r6
    ST_dms_sts_idx_imm $r7, $p0, 0
...
---
name:            latency_mov_d2
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_mov_d2
    ; CHECK: $r6 = MOV_mv_cg 10
    ; CHECK-NEXT: $r7 = MOV_D2 killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r7, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r6 = MOV_mv_cg 10
    $r7  = MOV_D2 $r6
    ST_dms_sts_idx_imm $r7, $p0, 0
...

---
name:            latency_mov_d3
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_mov_d3
    ; CHECK: $r6 = MOV_mv_cg 10
    ; CHECK-NEXT: $r7 = MOV_D3 killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r7, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r6 = MOV_mv_cg 10
    $r7  = MOV_D3 $r6
    ST_dms_sts_idx_imm $r7, $p0, 0
...
---
name:            latency_mov_d4
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_mov_d4
    ; CHECK: $r6 = MOV_mv_cg 10
    ; CHECK-NEXT: $r7 = MOV_D4 killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r7, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r6 = MOV_mv_cg 10
    $r7  = MOV_D4 $r6
    ST_dms_sts_idx_imm $r7, $p0, 0
...

---
name:            latency_mov_d5
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_mov_d5
    ; CHECK: $r6 = MOV_mv_cg 10
    ; CHECK-NEXT: $r7 = MOV_D5 killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r7, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r6 = MOV_mv_cg 10
    $r7  = MOV_D5 $r6
    ST_dms_sts_idx_imm $r7, $p0, 0
...
---
name:            latency_mov_d6
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_mov_d6
    ; CHECK: $r6 = MOV_mv_cg 10
    ; CHECK-NEXT: $r7 = MOV_D6 killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r7, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r6 = MOV_mv_cg 10
    $r7  = MOV_D6 $r6
    ST_dms_sts_idx_imm $r7, $p0, 0
...
