# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s
# Overview of tested part word store Itineraries:
# II_STHB:          LOAD  E5
#                   STORE E11
# II_STHB_2D:       LOAD  E5
#                   STORE E11
# II_STHB_3D:       LOAD  E5
#                   STORE E11

# Overview of Itineraries tested:
# II_VST_CONV:         STORE E7
# II_VST_CONV_POSTINC  STORE E7
# II_VST_2D_CONV       STORE E7
# II_VST_3D_CONV       STORE E7

# TODO: Update the tests with MMOs once alias analysis is supported
# for part-word stores.

---
name:            II_STHB_II_VST_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_CONV
    ; CHECK: ST_S16_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_CONV_BF16_FP32_ag_idx_imm killed $p0, 0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S16_ag_idx_imm $r0, $p0, 0
    VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_CONV_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_CONV_II_STHB
    ; CHECK: VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S16_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ST_S16_ag_idx_imm $r0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_CONV
    ; CHECK: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_CONV_BF16_FP32_ag_idx_imm killed $p0, 0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
    VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_STHB_3D_II_VST_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_CONV
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_CONV_BF16_FP32_ag_idx_imm killed $p0, 0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
    VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_CONV_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_CONV_II_STHB_2D
    ; CHECK: VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
...
---
name:            II_VST_CONV_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_CONV_II_STHB_3D
    ; CHECK: VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_CONV_BF16_FP32_ag_idx_imm $p0, 0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
...

---
name:            II_STHB_II_VST_CONV_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_CONV_POSTINC
    ; CHECK: ST_S16_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm killed $p0, killed $m3, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S16_ag_idx_imm $r0, $p0, 0
    $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm $p0, $m3, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            VST_CONV_POSTINC_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VST_CONV_POSTINC_II_STHB
    ; CHECK: $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm killed $p0, killed $m3, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S16_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm $p0, $m3, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ST_S16_ag_idx_imm $r0, $p0, 0
...


---
name:            II_STHB_2D_II_VST_CONV_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_CONV_POSTINC
    ; CHECK: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm killed $p0, killed $m3, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
    $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm $p0, $m3, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...
---
name:            II_STHB_3D_II_VST_CONV_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_CONV_POSTINC
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm killed $p0, killed $m3, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
    $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm $p0, $m3, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            VST_CONV_POSTINC_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VST_CONV_POSTINC_II_STHB_2D
    ; CHECK: $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm killed $p0, killed $m3, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm $p0, $m3, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
...
---
name:            VST_CONV_POSTINC_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VST_CONV_POSTINC_II_STHB_3D
    ; CHECK: $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm killed $p0, killed $m3, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_CONV_BF16_FP32_ag_pstm_nrm $p0, $m3, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
...

---
name:            II_STHB_II_VST_2D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_2D_CONV
    ; CHECK: ST_S16_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_CONV_2D_BF16_FP32 killed $p0, killed $d0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S16_ag_idx_imm $r0, $p0, 0
    $p0, $dc0 = VST_CONV_2D_BF16_FP32 $p0, $d0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_2D_CONV_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_2D_CONV_II_STHB
    ; CHECK: $p0, $dc0 = VST_CONV_2D_BF16_FP32 killed $p0, killed $d0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S16_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = VST_CONV_2D_BF16_FP32 $p0, $d0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ST_S16_ag_idx_imm $r0, $p0, 0
...


---
name:            II_STHB_2D_II_VST_2D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_2D_CONV
    ; CHECK: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_CONV_2D_BF16_FP32 killed $p0, killed $d0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
    $p0, $dc0 = VST_CONV_2D_BF16_FP32 $p0, $d0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_2D_CONV_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_2D_CONV_II_STHB_2D
    ; CHECK: $p0, $dc0 = VST_CONV_2D_BF16_FP32 killed $p0, $d0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = VST_CONV_2D_BF16_FP32 $p0, $d0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
...

---
name:            II_STHB_3D_II_VST_2D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_2D_CONV
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_CONV_2D_BF16_FP32 killed $p0, killed $d0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
    $p0, $dc0 = VST_CONV_2D_BF16_FP32 $p0, $d0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_2D_CONV_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_2D_CONV_II_STHB_3D
    ; CHECK: $p0, $dc0 = VST_CONV_2D_BF16_FP32 killed $p0, $d0, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = VST_CONV_2D_BF16_FP32 $p0, $d0, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
...

---
name:            II_STHB_II_VST_3D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_3D_CONV
    ; CHECK: ST_S16_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 killed $p0, killed $d0_3d, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S16_ag_idx_imm $r0, $p0, 0
    $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 $p0, $d0_3d, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_3D_CONV_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_3D_CONV_II_STHB
    ; CHECK: $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 killed $p0, killed $d0_3d, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S16_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 $p0, $d0_3d, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ST_S16_ag_idx_imm $r0, $p0, 0
...


---
name:            II_STHB_2D_II_VST_3D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_3D_CONV
    ; CHECK: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 killed $p0, killed $d0_3d, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
    $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 $p0, $d0_3d, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_3D_CONV_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_3D_CONV_II_STHB_2D
    ; CHECK: $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 killed $p0, $d0_3d, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S16 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 $p0, $d0_3d, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0 = ST_2D_S16 $r0, $p0, $d0
...


---
name:            II_STHB_3D_II_VST_3D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_3D_CONV
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 killed $p0, killed $d0_3d, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
    $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 $p0, $d0_3d, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            II_VST_3D_CONV_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_3D_CONV_II_STHB_3D
    ; CHECK: $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 killed $p0, $d0_3d, killed $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S16 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 $p0, $d0_3d, $bml0, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $p0, $dc0, $dc4 = ST_3D_S16 $r0, $p0, $d0_3d
...
