# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

# Due to the read-modify-write nature of part word store operations we need to
# be very careful with any memory operations during this time. Due to missing
# alias analysis we can currently not ensure that any other read or write
# accesses the same memory region during the critical section of the part word
# store. For now we will enforce a hard stop of all memory operations during
# the critical section with IsPartWordStore and AvoidPartWordStore in the
# Itineraries.

# Overview of tested part word store Itineraries:
# II_STHB:          LOAD  E5
#                   STORE E11
# II_STHB_POST_1D:  LOAD  E5
#                   STORE E11
# II_STHB_2D:       LOAD  E5
#                   STORE E11
# II_STHB_3D:       LOAD  E5
#                   STORE E11

# Overview of Itineraries tested:
# II_VST_SRS:         STORE E7
# II_VST_POSTINC_SRS: STORE E7
# II_VST_2D_SRS:      STORE E7
# II_VST_3D_SRS:      STORE E7

# Therefore when the part word store goes first we need 4 NOP instructions
# before the VST_SRS instruction and when the part word store goes second we
# need 2 NOP instructions after VST_SRS.

# TODO: Update the tests with MMOs once alias analysis is supported
# for part-word stores.

---
name:            II_STHB_II_VST_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_SRS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_SRS_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_SRS_II_STHB
    ; CHECK: VST_SRS_D8_S32_ag_idx_imm $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S8_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ST_S8_ag_idx_imm $r0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_SRS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_SRS_II_STHB_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_SRS_II_STHB_POST_1D
    ; CHECK: VST_SRS_D8_S32_ag_idx_imm $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_SRS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_SRS_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_SRS_II_STHB_2D
    ; CHECK: VST_SRS_D8_S32_ag_idx_imm $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
...

---
name:            II_STHB_3D_II_VST_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_SRS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_SRS_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_SRS_II_STHB_3D
    ; CHECK: VST_SRS_D8_S32_ag_idx_imm $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
...

---
name:            II_STHB_II_VST_POSTINC_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_POSTINC_SRS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_POSTINC_SRS_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_POSTINC_SRS_II_STHB
    ; CHECK: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S8_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ST_S8_ag_idx_imm $r0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_POSTINC_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_POSTINC_SRS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_POSTINC_SRS_II_STHB_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_POSTINC_SRS_II_STHB_POST_1D
    ; CHECK: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_POSTINC_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_POSTINC_SRS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_POSTINC_SRS_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_POSTINC_SRS_II_STHB_2D
    ; CHECK: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
...

---
name:            II_STHB_3D_II_VST_POSTINC_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_POSTINC_SRS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_POSTINC_SRS_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_POSTINC_SRS_II_STHB_3D
    ; CHECK: $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm killed $p0, 0, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_SRS_D16_S32_ag_pstm_nrm_imm $p0, 0, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
...

---
name:            II_STHB_II_VST_2D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_2D_SRS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_STHB_II_VST_3D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_3D_SRS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_2D_SRS_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_2D_SRS_II_STHB
    ; CHECK: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S8_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ST_S8_ag_idx_imm $r0, $p0, 0
...

---
name:            II_VST_3D_SRS_II_STHB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_3D_SRS_II_STHB
    ; CHECK: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_S8_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ST_S8_ag_idx_imm $r0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_2D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_2D_SRS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_STHB_POST_1D_II_VST_3D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_3D_SRS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_2D_SRS_II_STHB_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_2D_SRS_II_STHB_POST_1D
    ; CHECK: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
...

---
name:            II_VST_3D_SRS_II_STHB_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_3D_SRS_II_STHB_POST_1D
    ; CHECK: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
...


---
name:            II_STHB_2D_II_VST_2D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_2D_SRS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_STHB_2D_II_VST_3D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_3D_SRS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_2D_SRS_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_2D_SRS_II_STHB_2D
    ; CHECK: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
...

---
name:            II_VST_3D_SRS_II_STHB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_3D_SRS_II_STHB_2D
    ; CHECK: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
...


---
name:            II_STHB_3D_II_VST_2D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_2D_SRS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_STHB_3D_II_VST_3D_SRS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_3D_SRS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            II_VST_2D_SRS_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_2D_SRS_II_STHB_3D
    ; CHECK: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
...

---
name:            II_VST_3D_SRS_II_STHB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_VST_3D_SRS_II_STHB_3D
    ; CHECK: $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 killed $p0, killed $d3_3d, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc3, $dc7 = VST_3D_SRS_D16_S32 $p0, $d3_3d, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
...
