# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

# Due to the read-modify-write nature of part word store operations we need to
# be very careful with any memory operations during this time. Due to missing
# alias analysis we can currently not ensure that any other read or write
# accesses the same memory region during the critical section of the part word
# store. For now we will enforce a hard stop of all memory operations during
# the critical section with IsPartWordStore and AvoidPartWordStore in the
# Itineraries.

# Overview of tested part word store Itineraries:
# II_STHB:          LOAD  E5
#                   STORE E11
# II_STHB_POST_1D:  LOAD  E5
#                   STORE E11
# II_STHB_2D:       LOAD  E5
#                   STORE E11
# II_STHB_3D:       LOAD  E5
#                   STORE E11

# Overview of Itineraries tested:
# II_LDA:               LOAD  E5
# II_LDA_POST_1D:       LOAD  E5
# II_ST:                STORE E5
# II_ST_POST_1D:        STORE E5
# II_VLDA_UPS:          LOAD  E5
# II_VLDA_W:            LOAD  E5
# II_VLDB:              LOAD  E5
# II_LDA_Q:             LOAD  E5
# II_VLDA_AM:           LOAD  E5
# II_VST_PACK:          STORE E5
# II_VST_W:             STORE E5
# II_VST_AM:            STORE E5
# II_VLDA_2D_UPS:       LOAD  E5
# II_VLDA_3D_UPS:       LOAD  E5
# II_VLDA_POSTINC_UPS:  LOAD  E5
# II_VLDA_2D_W:         LOAD  E5
# II_VLDA_3D_W:         LOAD  E5
# II_VLDA_POSTINC_W:    LOAD  E5
# II_VLDB_2D:           LOAD  E5
# II_VLDB_3D:           LOAD  E5
# II_VLDB_POSTINC:      LOAD  E5
# II_LDA_POSTINC_Q:     LOAD  E5
# II_VLDA_2D_AM:        LOAD  E5
# II_VLDA_3D_AM:        LOAD  E5
# II_VLDA_POSTINC_AM:   LOAD  E5
# II_VST_2D_W:          STORE E5
# II_VST_3D_W:          STORE E5
# II_VST_POSTINC_W:     STORE E5
# II_VST_2D_AM:         STORE E5
# II_VST_3D_AM:         STORE E5
# II_VST_POSTINC_AM:    STORE E5
# II_VLDB_UNPACK:       LOAD E5
# II_VLDB_UNPACK_POSTINC: LOAD E5
# II_VLDB_UNPACK_2D:    LOAD E5
# II_VLDB_UNPACK_3D:    LOAD E5


# The part word store goes first, therefore we need 6 additional NOP
# instructions after the part word store.

# TODO: Update the tests with MMOs once alias analysis is supported
# for part-word stores.

---
name:            II_STHB_II_LDA
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_LDA
    ; CHECK: ST_S8_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = LDA_S8_ag_idx_imm killed $p5, -4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $r0 = LDA_S8_ag_idx_imm $p5, -4
...

---
name:            II_STHB_POST_1D_II_LDA
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_LDA
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = LDA_S8_ag_idx_imm killed $p5, -4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $r0 = LDA_S8_ag_idx_imm $p5, -4
...

---
name:            II_STHB_2D_II_LDA
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_LDA
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = LDA_S8_ag_idx_imm killed $p5, -4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $r0 = LDA_S8_ag_idx_imm $p5, -4
...

---
name:            II_STHB_3D_II_LDA
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_LDA
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = LDA_S8_ag_idx_imm killed $p5, -4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $r0 = LDA_S8_ag_idx_imm $p5, -4
...

---
name:            II_STHB_II_LDA_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_LDA_POST_1D
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0, $p0 = LDA_dms_lda_pstm_nrm_imm killed $p0, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $r0, $p0 = LDA_dms_lda_pstm_nrm_imm $p0, 4
...

---
name:            II_STHB_POST_1D_II_LDA_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_LDA_POST_1D
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0, $p0 = LDA_dms_lda_pstm_nrm_imm killed $p0, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $r0, $p0 = LDA_dms_lda_pstm_nrm_imm $p0, 4
...

---
name:            II_STHB_2D_II_LDA_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_LDA_POST_1D
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0, $p0 = LDA_dms_lda_pstm_nrm_imm killed $p0, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $r0, $p0 = LDA_dms_lda_pstm_nrm_imm $p0, 4
...

---
name:            II_STHB_3D_II_LDA_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_LDA_POST_1D
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0, $p0 = LDA_dms_lda_pstm_nrm_imm killed $p0, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $r0, $p0 = LDA_dms_lda_pstm_nrm_imm $p0, 4
...

---
name:            II_STHB_II_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_ST
    ; CHECK: ST_S8_ag_idx_imm $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r0, killed $p1, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    ST_dms_sts_idx_imm $r0, $p1, 0
...

---
name:            II_STHB_POST_1D_II_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_ST
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r0, killed $p1, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    ST_dms_sts_idx_imm $r0, $p1, 0
...

---
name:            II_STHB_2D_II_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_ST
    ; CHECK: $p0, $dc0 = ST_2D_S8 $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r0, killed $p1, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    ST_dms_sts_idx_imm $r0, $p1, 0
...

---
name:            II_STHB_3D_II_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_ST
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r0, killed $p1, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    ST_dms_sts_idx_imm $r0, $p1, 0
...
---
name:            II_STHB_II_ST_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_ST_POST_1D
    ; CHECK: ST_S8_ag_idx_imm $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dms_sts_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0 = ST_dms_sts_pstm_nrm_imm $r0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_ST_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_ST_POST_1D
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dms_sts_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0 = ST_dms_sts_pstm_nrm_imm $r0, $p0, 0
...

---
name:            II_STHB_2D_II_ST_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_ST_POST_1D
    ; CHECK: $p0, $dc0 = ST_2D_S8 $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dms_sts_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0 = ST_dms_sts_pstm_nrm_imm $r0, $p0, 0
...

---
name:            II_STHB_3D_II_ST_POST_1D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_ST_POST_1D
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dms_sts_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0 = ST_dms_sts_pstm_nrm_imm $r0, $p0, 0
...

---
name:            II_STHB_II_VLDA_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_UPS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_POST_1D_II_VLDA_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_UPS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_2D_II_VLDA_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_UPS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_3D_II_VLDA_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_UPS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_II_VLDA_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDA_dmw_lda_w_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDA_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDA_dmw_lda_w_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0
...


---
name:            II_STHB_2D_II_VLDA_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDA_dmw_lda_w_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDA_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDA_dmw_lda_w_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0
...

---
name:            II_STHB_II_VLDB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0 = VLDB_dmw_ldb_ag_idx_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0 = VLDB_dmw_ldb_ag_idx_imm $p0, 0
...

---
name:            II_STHB_2D_II_VLDB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0 = VLDB_dmw_ldb_ag_idx_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0 = VLDB_dmw_ldb_ag_idx_imm $p0, 0
...



---
name:            II_STHB_II_VLDB_UNPACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_UNPACK
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VLDB_UNPACK_S8_S4_ag_idx killed $p0, killed $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $x0 = VLDB_UNPACK_S8_S4_ag_idx $p0, $dj0
...

---
name:            II_STHB_POST_1D_II_VLDB_UNPACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_UNPACK
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VLDB_UNPACK_S8_S4_ag_idx killed $p0, killed $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, $dj0
    $x0 = VLDB_UNPACK_S8_S4_ag_idx $p0, $dj0
...

---
name:            II_STHB_2D_II_VLDB_UNPACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_UNPACK
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VLDB_UNPACK_S8_S4_ag_idx killed $p0, killed $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $x0 = VLDB_UNPACK_S8_S4_ag_idx $p0, $dj0
...

---
name:            II_STHB_3D_II_VLDB_UNPACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_UNPACK
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VLDB_UNPACK_S8_S4_ag_idx killed $p0, killed $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $x0 = VLDB_UNPACK_S8_S4_ag_idx $p0, $dj0
...



---
name:            II_STHB_II_VLDB_UNPACK_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_UNPACK_POSTINC
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm killed $p0, killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm $p0, $m0
...

---
name:            II_STHB_POST_1D_II_VLDB_UNPACK_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_UNPACK_POSTINC
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, killed $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm killed $p0, killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, $dj0
    $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm $p0, $m0
...

---
name:            II_STHB_2D_II_VLDB_UNPACK_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_UNPACK_POSTINC
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm killed $p0, killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm $p0, $m0
...

---
name:            II_STHB_3D_II_VLDB_UNPACK_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_UNPACK_POSTINC
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm killed $p0, killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $x0, $p0 = VLDB_UNPACK_S8_S4_ag_pstm_nrm $p0, $m0
...



---
name:            II_STHB_II_VLDB_UNPACK_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_UNPACK_2D
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 $p0, $d0
...

---
name:            II_STHB_POST_1D_II_VLDB_UNPACK_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_UNPACK_2D
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, $dj0
    $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 $p0, $d0
...

---
name:            II_STHB_2D_II_VLDB_UNPACK_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_UNPACK_2D
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 $p0, $d0
...

---
name:            II_STHB_3D_II_VLDB_UNPACK_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_UNPACK_2D
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $x0, $p0, $dc0 = VLDB_2D_UNPACK_S8_S4 $p0, $d0
...




---
name:            II_STHB_II_VLDB_UNPACK_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_UNPACK_3D
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_VLDB_UNPACK_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_UNPACK_3D
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, $dj0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, $dj0
    $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 $p0, $d0_3d
...

---
name:            II_STHB_2D_II_VLDB_UNPACK_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_UNPACK_3D
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 $p0, $d0_3d
...

---
name:            II_STHB_3D_II_VLDB_UNPACK_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_UNPACK_3D
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $x0, $p0, $dc0, $dc4 = VLDB_3D_UNPACK_S8_S4 $p0, $d0_3d
...

---
name:            II_STHB_II_VLDA_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0 = VLDA_dmw_lda_am_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $amll0 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDA_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0 = VLDA_dmw_lda_am_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $amll0 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
...

---
name:            II_STHB_2D_II_VLDA_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0 = VLDA_dmw_lda_am_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $amll0 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDA_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0 = VLDA_dmw_lda_am_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $amll0 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
...

---
name:            II_STHB_II_VLDA_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_CONV
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDA_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_CONV
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm $p0, 0
...

---
name:            II_STHB_2D_II_VLDA_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_CONV
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDA_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_CONV
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bml0 = VLDA_CONV_FP32_BF16_ag_idx_imm $p0, 0
...

---
name:            II_STHB_II_VLDA_CONV_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_CONV_POSTINC
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDA_CONV_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_CONV_POSTINC
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_2D_II_VLDA_CONV_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_CONV_POSTINC
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDA_CONV_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_CONV_POSTINC
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bml0, $p0 = VLDA_CONV_FP32_BF16_pstm_nrm_imm $p0, 0
...


---
name:            II_STHB_II_VLDA_2D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_2D_CONV
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 killed $p0, killed $d4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 $p0, $d4
...

---
name:            II_STHB_POST_1D_II_VLDA_2D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_2D_CONV
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 killed $p0, killed $d4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 $p0, $d4
...

---
name:            II_STHB_2D_II_VLDA_2D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_2D_CONV
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 killed $p0, killed $d4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 $p0, $d4
...

---
name:            II_STHB_3D_II_VLDA_2D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_2D_CONV
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 killed $p0, killed $d4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bmh0, $p0, $dc4 = VLDA_2D_CONV_FP32_BF16 $p0, $d4
...


---
name:            II_STHB_II_VLDA_3D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_3D_CONV
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_VLDA_3D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_3D_CONV
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 $p0, $d0_3d
...

---
name:            II_STHB_2D_II_VLDA_3D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_3D_CONV
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 $p0, $d0_3d
...

---
name:            II_STHB_3D_II_VLDA_3D_CONV
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_3D_CONV
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_CONV_FP32_BF16 $p0, $d0_3d
...

---
name:            II_STHB_II_VST_PACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_PACK
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_PACK_S4_S8_ag_idx_imm killed $p0, 0, killed $x0, implicit $crsat
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    VST_PACK_S4_S8_ag_idx_imm $p0, 0, $x0, implicit $crsat
...

---
name:            II_STHB_POST_1D_II_VST_PACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_PACK
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_PACK_S4_S8_ag_idx_imm killed $p0, 0, killed $x0, implicit $crsat
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    VST_PACK_S4_S8_ag_idx_imm $p0, 0, $x0, implicit $crsat
...

---
name:            II_STHB_2D_II_VST_PACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_PACK
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_PACK_S4_S8_ag_idx_imm killed $p0, 0, killed $x0, implicit $crsat
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    VST_PACK_S4_S8_ag_idx_imm $p0, 0, $x0, implicit $crsat
...

---
name:            II_STHB_3D_II_VST_PACK
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_PACK
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_PACK_S4_S8_ag_idx_imm killed $p0, 0, killed $x0, implicit $crsat
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    VST_PACK_S4_S8_ag_idx_imm $p0, 0, $x0, implicit $crsat
...

---
name:            II_STHB_II_VST_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...

---
name:            II_STHB_3D_II_VST_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...

---
name:            II_STHB_II_VST_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            II_STHB_3D_II_VST_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            II_STHB_II_VLDA_POSTINC_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_POSTINC_UPS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_POST_1D_II_VLDA_POSTINC_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_POSTINC_UPS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_2D_II_VLDA_POSTINC_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_POSTINC_UPS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_3D_II_VLDA_POSTINC_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_POSTINC_UPS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_II_VLDA_2D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_2D_UPS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 killed $s0, killed $p0, killed $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 $s0, $p0, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_II_VLDA_3D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_3D_UPS
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 killed $s0, killed $p0, killed $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 $s0, $p0, $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_POST_1D_II_VLDA_2D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_2D_UPS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 killed $s0, killed $p0, killed $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 $s0, $p0, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_POST_1D_II_VLDA_3D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_3D_UPS
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 killed $s0, killed $p0, killed $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 $s0, $p0, $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_2D_II_VLDA_2D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_2D_UPS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 killed $s0, killed $p0, killed $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 $s0, $p0, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_2D_II_VLDA_3D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_3D_UPS
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 killed $s0, killed $p0, killed $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 $s0, $p0, $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_3D_II_VLDA_2D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_2D_UPS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 killed $s0, killed $p0, killed $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 $s0, $p0, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_3D_II_VLDA_3D_UPS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_3D_UPS
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 killed $s0, killed $p0, killed $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 $s0, $p0, $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
...

---
name:            II_STHB_II_VLDA_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_POSTINC_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDA_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_POSTINC_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_2D_II_VLDA_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_POSTINC_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDA_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_POSTINC_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0, $p0 = VLDA_dmw_lda_w_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_II_VLDA_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_2D_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w $p0, $d0
...

---
name:            II_STHB_II_VLDA_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_3D_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_VLDA_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_2D_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w $p0, $d0
...

---
name:            II_STHB_POST_1D_II_VLDA_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_3D_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w $p0, $d0_3d
...

---
name:            II_STHB_2D_II_VLDA_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_2D_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w $p0, $d0
...

---
name:            II_STHB_2D_II_VLDA_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_3D_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w $p0, $d0_3d
...

---
name:            II_STHB_3D_II_VLDA_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_2D_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0, $p0, $dc0 = VLDA_2D_dmw_lda_w $p0, $d0
...

---
name:            II_STHB_3D_II_VLDA_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_3D_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_w $p0, $d0_3d
...

---
name:            II_STHB_II_VLDB_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_POSTINC
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDB_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_POSTINC
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_2D_II_VLDB_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_POSTINC
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDB_POSTINC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_POSTINC
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0, $p0 = VLDB_dmw_ldb_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_II_VLDB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_2D
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDB_2D killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0, $p0, $dc0 = VLDB_2D $p0, $d0
...

---
name:            II_STHB_II_VLDB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_3D
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDB_3D killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0, $p0, $dc0, $dc4 = VLDB_3D $p0, $d0_3d
...

---
name:            II_STHB_II_VLDB_4X
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDB_4X
    ; CHECK: ST_S8_ag_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_4x32_HI killed $wh10
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $wl0 = VLDB_4x32_HI $wh10
...

---
name:            II_STHB_POST_1D_II_VLDB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_2D
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDB_2D killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0, $p0, $dc0 = VLDB_2D $p0, $d0
...

---
name:            II_STHB_POST_1D_II_VLDB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_3D
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDB_3D killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0, $p0, $dc0, $dc4 = VLDB_3D $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_VLDB_4X
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDB_4X
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_4x64_HI killed $wh10
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $wl0 = VLDB_4x64_HI $wh10
...


---
name:            II_STHB_2D_II_VLDB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_2D
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDB_2D killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0, $p0, $dc0 = VLDB_2D $p0, $d0
...

---
name:            II_STHB_2D_II_VLDB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_3D
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDB_3D killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0, $p0, $dc0, $dc4 = VLDB_3D $p0, $d0_3d
...

---
name:            II_STHB_2D_II_VLDB_4X
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDB_4X
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_4x64_HI killed $wh10
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $wl0 = VLDB_4x64_HI $wh10
...

---
name:            II_STHB_3D_II_VLDB_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_2D
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0 = VLDB_2D killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0, $p0, $dc0 = VLDB_2D $p0, $d0
...

---
name:            II_STHB_3D_II_VLDB_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_3D
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0, $p0, $dc0, $dc4 = VLDB_3D killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0, $p0, $dc0, $dc4 = VLDB_3D $p0, $d0_3d
...

---
name:            II_STHB_3D_II_VLDB_4X
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDB_4X
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VLDB_4x64_HI killed $wh10
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $wl0 = VLDB_4x64_HI $wh10
...

---
name:            II_STHB_II_VLDA_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_POSTINC_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_VLDA_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_POSTINC_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_2D_II_VLDA_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_POSTINC_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_3D_II_VLDA_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_POSTINC_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $amll0, $p0 = VLDA_dmw_lda_am_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_II_VLDA_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_2D_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am $p0, $d0
...

---
name:            II_STHB_II_VLDA_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VLDA_3D_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_VLDA_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_2D_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am $p0, $d0
...

---
name:            II_STHB_POST_1D_II_VLDA_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VLDA_3D_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am $p0, $d0_3d
...

---
name:            II_STHB_2D_II_VLDA_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_2D_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am $p0, $d0
...

---
name:            II_STHB_2D_II_VLDA_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VLDA_3D_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am $p0, $d0_3d
...


---
name:            II_STHB_3D_II_VLDA_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_2D_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $amll0, $p0, $dc0 = VLDA_2D_dmw_lda_am $p0, $d0
...

---
name:            II_STHB_3D_II_VLDA_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VLDA_3D_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $amll0, $p0, $dc0, $dc4 = VLDA_3D_dmw_lda_am $p0, $d0_3d
...

---
name:            II_STHB_II_VST_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_POSTINC_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm $wl0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_POSTINC_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm $wl0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_POSTINC_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm $wl0, $p0, 0
...

---
name:            II_STHB_3D_II_VST_POSTINC_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_POSTINC_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0 = VST_dmw_sts_w_ag_pstm_nrm_imm $wl0, $p0, 0
...

---
name:            II_STHB_II_VST_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_2D_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_w killed $wl0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0, $dc0 = VST_2D_dmw_sts_w $wl0, $p0, $d0
...

---
name:            II_STHB_II_VST_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_3D_W
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_w killed $wl0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_w $wl0, $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_VST_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_2D_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_w killed $wl0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0, $dc0 = VST_2D_dmw_sts_w $wl0, $p0, $d0
...

---
name:            II_STHB_POST_1D_II_VST_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_3D_W
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_w killed $wl0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_w $wl0, $p0, $d0_3d
...

---
name:            II_STHB_2D_II_VST_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_2D_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_w killed $wl0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0, $dc0 = VST_2D_dmw_sts_w $wl0, $p0, $d0
...

---
name:            II_STHB_2D_II_VST_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_3D_W
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_w killed $wl0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_w $wl0, $p0, $d0_3d
...

---
name:            II_STHB_3D_II_VST_2D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_2D_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_w killed $wl0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0, $dc0 = VST_2D_dmw_sts_w $wl0, $p0, $d0
...

---
name:            II_STHB_3D_II_VST_3D_W
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_3D_W
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_w killed $wl0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_w $wl0, $p0, $d0_3d
...

---
name:            II_STHB_II_VST_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_POSTINC_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm $amll0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_POSTINC_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm $amll0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_POSTINC_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm $amll0, $p0, 0
...

---
name:            II_STHB_3D_II_VST_POSTINC_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_POSTINC_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0 = VST_dmw_sts_am_ag_pstm_nrm_imm $amll0, $p0, 0
...

---
name:            II_STHB_II_VST_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_2D_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_am killed $amll0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0, $dc0 = VST_2D_dmw_sts_am $amll0, $p0, $d0
...

---
name:            II_STHB_II_VST_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_VST_3D_AM
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_am killed $amll0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_am $amll0, $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_VST_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_2D_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_am killed $amll0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0, $dc0 = VST_2D_dmw_sts_am $amll0, $p0, $d0
...

---
name:            II_STHB_POST_1D_II_VST_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_3D_AM
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_am killed $amll0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_am $amll0, $p0, $d0_3d
...


---
name:            II_STHB_2D_II_VST_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_2D_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_am killed $amll0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0, $dc0 = VST_2D_dmw_sts_am $amll0, $p0, $d0
...

---
name:            II_STHB_2D_II_VST_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_3D_AM
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_am killed $amll0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_am $amll0, $p0, $d0_3d
...


---
name:            II_STHB_3D_II_VST_2D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_2D_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_dmw_sts_am killed $amll0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0, $dc0 = VST_2D_dmw_sts_am $amll0, $p0, $d0
...

---
name:            II_STHB_3D_II_VST_3D_AM
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_3D_AM
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_dmw_sts_am killed $amll0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0, $dc0, $dc4 = VST_3D_dmw_sts_am $amll0, $p0, $d0_3d
...

---
name:            II_STHB_II_LDA_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_LDA_Q
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0 = LDA_dmv_lda_q_ag_spill killed $p0, implicit $sp
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $q0 = LDA_dmv_lda_q_ag_spill $p0, implicit $sp
...

---
name:            II_STHB_POST_1D_II_LDA_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_LDA_Q
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0 = LDA_dmv_lda_q_ag_spill killed $p0, implicit $sp
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $q0 = LDA_dmv_lda_q_ag_spill $p0, implicit $sp
...

---
name:            II_STHB_2D_II_LDA_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_LDA_Q
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0 = LDA_dmv_lda_q_ag_spill killed $p0, implicit $sp
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $q0 = LDA_dmv_lda_q_ag_spill $p0, implicit $sp
...

---
name:            II_STHB_3D_II_LDA_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_LDA_Q
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0 = LDA_dmv_lda_q_ag_spill killed $p0, implicit $sp
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $q0 = LDA_dmv_lda_q_ag_spill $p0, implicit $sp
...

---
name:            II_STHB_II_II_LDA_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_II_LDA_POSTINC_Q
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_POST_1D_II_LDA_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_LDA_POSTINC_Q
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_2D_II_LDA_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_LDA_POSTINC_Q
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm $p0, 0
...

---
name:            II_STHB_3D_II_LDA_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_LDA_POSTINC_Q
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $q0, $p0 = LDA_dmv_lda_q_ag_pstm_nrm_imm $p0, 0
...


---
name:            II_STHB_II_II_LDA_2D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_II_LDA_2D_Q
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0 = LDA_2D_dmv_lda_q killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $q0, $p0, $dc0 = LDA_2D_dmv_lda_q $p0, $d0
...

---
name:            II_STHB_POST_1D_II_LDA_2D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_LDA_2D_Q
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0 = LDA_2D_dmv_lda_q killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $q0, $p0, $dc0 = LDA_2D_dmv_lda_q $p0, $d0
...

---
name:            II_STHB_2D_II_LDA_2D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_LDA_2D_Q
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0 = LDA_2D_dmv_lda_q killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $q0, $p0, $dc0 = LDA_2D_dmv_lda_q $p0, $d0
...

---
name:            II_STHB_3D_II_LDA_2D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_LDA_2D_Q
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0 = LDA_2D_dmv_lda_q killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $q0, $p0, $dc0 = LDA_2D_dmv_lda_q $p0, $d0
...


---
name:            II_STHB_II_II_LDA_3D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_II_LDA_3D_Q
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q $p0, $d0_3d
...

---
name:            II_STHB_POST_1D_II_LDA_3D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_LDA_3D_Q
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q $p0, $d0_3d
...

---
name:            II_STHB_2D_II_LDA_3D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_LDA_3D_Q
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q $p0, $d0_3d
...

---
name:            II_STHB_3D_II_LDA_3D_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_LDA_3D_Q
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $q0, $p0, $dc0, $dc4 = LDA_3D_dmv_lda_q $p0, $d0_3d
...

---
name:            II_STHB_II_ST_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_ST_Q
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dmv_sts_q_ag_idx_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    ST_dmv_sts_q_ag_idx_imm $q0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_VST_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_VST_Q
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dmv_sts_q_ag_idx_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    ST_dmv_sts_q_ag_idx_imm $q0, $p0, 0
...

---
name:            II_STHB_2D_II_VST_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_VST_Q
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dmv_sts_q_ag_idx_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    ST_dmv_sts_q_ag_idx_imm $q0, $p0, 0
...

---
name:            II_STHB_3D_II_VST_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_VST_Q
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dmv_sts_q_ag_idx_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    ST_dmv_sts_q_ag_idx_imm $q0, $p0, 0
...
---
name:            II_STHB_II_ST_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_II_ST_POSTINC_Q
    ; CHECK: ST_S8_ag_idx_imm killed $r0, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ST_S8_ag_idx_imm $r0, $p0, 0
    $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm $q0, $p0, 0
...

---
name:            II_STHB_POST_1D_II_ST_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_POST_1D_II_ST_POSTINC_Q
    ; CHECK: $p0 = ST_S8_ag_pstm_nrm_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0 = ST_S8_ag_pstm_nrm_imm $r0, $p0, 0
    $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm $q0, $p0, 0
...


---
name:            II_STHB_2D_II_ST_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_2D_II_ST_POSTINC_Q
    ; CHECK: $p0, $dc0 = ST_2D_S8 killed $r0, killed $p0, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0 = ST_2D_S8 $r0, $p0, $d0
    $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm $q0, $p0, 0
...

---
name:            II_STHB_3D_II_ST_POSTINC_Q
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: II_STHB_3D_II_ST_POSTINC_Q
    ; CHECK: $p0, $dc0, $dc4 = ST_3D_S8 killed $r0, killed $p0, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm killed $q0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $p0, $dc0, $dc4 = ST_3D_S8 $r0, $p0, $d0_3d
    $p0 = ST_dmv_sts_q_ag_pstm_nrm_imm $q0, $p0, 0
...
