# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2  -run-pass=postmisched %s -o - | FileCheck %s

---
name:            padda_mod
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $r6, $m0
    ; CHECK-LABEL: name: padda_mod
    ; CHECK: liveins: $p1, $r6, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1 = PADDA_lda_ptr_inc_idx killed $p1, killed $m0
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1 = PADDA_lda_ptr_inc_idx $p1, $m0
    $r6 = LDA_dms_lda_idx_imm $p1, 4
...

---
name:            paddb_mod
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $r6, $m1
    ; CHECK-LABEL: name: paddb_mod
    ; CHECK: liveins: $p1, $r6, $m1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1 = PADDB_ldb_ptr_inc_nospill_nrm killed $p1, killed $m1
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1 = PADDB_ldb_ptr_inc_nospill_nrm $p1, $m1
    $r6 = LDA_dms_lda_idx_imm $p1, 4
...

---
name:            padds_mod
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $r6, $m0
    ; CHECK-LABEL: name: padds_mod
    ; CHECK: liveins: $p1, $r6, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1 = PADDS_st_ptr_inc_idx killed $p1, killed $m0
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1 = PADDS_st_ptr_inc_idx $p1, $m0
    $r6 = LDA_dms_lda_idx_imm $p1, 4
...

---
name:            padd_mod
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $r6, $m1, $m2
    ; CHECK-LABEL: name: padd_mod
    ; CHECK: liveins: $p1, $r6, $m1, $m2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1 = PADDA_lda_ptr_inc_idx killed $p1, $m1
    ; CHECK-NEXT: $p1 = PADDB_ldb_ptr_inc_nospill_nrm killed $p1, killed $m2
    ; CHECK-NEXT: $p1 = PADDA_lda_ptr_inc_idx killed $p1, $m1
    ; CHECK-NEXT: $p1 = PADDS_st_ptr_inc_idx killed $p1, killed $m1
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1 = PADDA_lda_ptr_inc_idx $p1, $m1
    $p1 = PADDB_ldb_ptr_inc_nospill_nrm $p1, $m2
    $p1 = PADDA_lda_ptr_inc_idx $p1, $m1
    $p1 = PADDS_st_ptr_inc_idx $p1, $m1
    $r6 = LDA_dms_lda_idx_imm $p1, 4
...

---
name:            padda_imm
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $r6
    ; CHECK-LABEL: name: padda_imm
    ; CHECK: liveins: $p1, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1 = PADDA_lda_ptr_inc_idx_imm killed $p1, 4
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1 = PADDA_lda_ptr_inc_idx_imm $p1, 4
    $r6 = LDA_dms_lda_idx_imm $p1, 4
...

---
name:            padds_imm
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $r6
    ; CHECK-LABEL: name: padds_imm
    ; CHECK: liveins: $p1, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1 = PADDS_st_ptr_inc_idx_imm killed $p1, 4
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1 = PADDS_st_ptr_inc_idx_imm $p1, 4
    $r6 = LDA_dms_lda_idx_imm $p1, 4
...

---
name:            paddb_imm9x4
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $r6
    ; CHECK-LABEL: name: paddb_imm9x4
    ; CHECK: liveins: $p1, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1 = PADDB_ldb_ptr_inc_nrm_imm killed $p1, 1020
    ; CHECK-NEXT: $p1 = PADDB_ldb_ptr_inc_nrm_imm killed $p1, -1024
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1 = PADDB_ldb_ptr_inc_nrm_imm $p1, 1020
    $p1 = PADDB_ldb_ptr_inc_nrm_imm $p1, -1024
    $r6 = LDA_dms_lda_idx_imm $p1, 4
...
