# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            test
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $d3
    ; CHECK-LABEL: name: test
    ; CHECK: liveins: $p1, $d3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p1, $dc3 = PADDA_2D killed $p1, $d3
    ; CHECK-NEXT: $p1, $dc3 = PADDA_2D killed $p1, $d3
    ; CHECK-NEXT: $p1, $dc3 = PADDB_2D killed $p1, $d3
    ; CHECK-NEXT: $p1, $dc3 = PADDB_2D killed $p1, $d3
    ; CHECK-NEXT: $p1, $dc3 = PADDS_2D killed $p1, $d3
    ; CHECK-NEXT: $p1, $dc3 = PADDS_2D killed $p1, killed $d3
    ; CHECK-NEXT: $r6 = LDA_dms_lda_idx_imm killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p1, $dc3 = PADDA_2D $p1, $d3
    $p1, $dc3 = PADDA_2D $p1, $d3
    $p1, $dc3 = PADDB_2D $p1, $d3
    $p1, $dc3 = PADDB_2D $p1, $d3
    $p1, $dc3 = PADDS_2D $p1, $d3
    $p1, $dc3 = PADDS_2D $p1, $d3
    $r6 = LDA_dms_lda_idx_imm $p1, 0
...
