# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name: mix
stack:
  - { id: 0, name: "", offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: "", offset: 0, size: 4, alignment: 4 }
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: mix
    ; CHECK: $r6 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: ST_dms_spill killed $r6, %stack.1, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: NOP
    $r6 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ST_dms_spill killed $r6, %stack.1, implicit $sp :: (store (s32) into %stack.1)

...
