# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc %topdown-multi --mtriple=aie2 --run-pass=postmisched %s -o - | FileCheck %s


---
name:            store_barrier_load
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: store_barrier_load
    ; CHECK: ST_dms_sts_idx_imm killed $r17, $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: SCHED_BARRIER
    ; CHECK-NEXT: $r0 = LDA_dms_lda_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ST_dms_sts_idx_imm $r17, $p0, 0
    SCHED_BARRIER
    $r0 = LDA_dms_lda_idx_imm $p0, 0
...

---
name:            load_barrier_store
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: load_barrier_store
    ; CHECK: $r0 = LDA_dms_lda_idx_imm killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: SCHED_BARRIER
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r17, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r0 = LDA_dms_lda_idx_imm $p1, 0
    SCHED_BARRIER
    ST_dms_sts_idx_imm $r17, $p0, 0
...

---
name:            done_barrier_load
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: done_barrier_load
    ; CHECK: DONE
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: SCHED_BARRIER
    ; CHECK-NEXT: $r0 = LDA_dms_lda_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    DONE
    SCHED_BARRIER
    $r0 = LDA_dms_lda_idx_imm $p0, 0
...

---
name:            done_barrier_store
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: done_barrier_store
    ; CHECK: DONE
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: SCHED_BARRIER
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r17, killed $p0, 0
    ; CHECK-NEXT: NOP
    DONE
    SCHED_BARRIER
    ST_dms_sts_idx_imm $r17, $p0, 0
...
