# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc %topdown-multi --mtriple=aie2 --run-pass=postmisched %s -o - | FileCheck %s

---
name:            just_meta
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: just_meta
    ; CHECK: $wl0 = IMPLICIT_DEF
    $wl0 = IMPLICIT_DEF
---

name:            meta_plus_standalone
alignment:       16
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    $wl0 = IMPLICIT_DEF
    ST_dms_sts_idx_imm $r0, $p0, 0
...

---
name:            standalone_plus_meta
alignment:       16
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: standalone_plus_meta
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r0, killed $p0, 0
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: NOP
    ST_dms_sts_idx_imm $r0, $p0, 0
    $wl0 = IMPLICIT_DEF
...

---
name:            meta_plus_bundle
alignment:       16
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: meta_plus_bundle
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r0, $p0, 0 {
    ; CHECK-NEXT:   $r0 = ABS killed $r0, implicit-def $srcarry
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: NOP
    $wl0 = IMPLICIT_DEF
    ST_dms_sts_idx_imm $r0, $p0, 0
    $r0 = ABS $r0, implicit-def $srcarry
...

---
name:            meta_in_bundle
alignment:       16
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: meta_in_bundle
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 0 {
    ; CHECK-NEXT:   $r0 = ABS killed $r0, implicit-def $srcarry
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: NOP
    $r0 = ABS $r0, implicit-def $srcarry
    $wl0 = IMPLICIT_DEF
    ST_dms_sts_idx_imm $r1, $p0, 0
...

---
name:            bundle_plus_meta
alignment:       16
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: bundle_plus_meta
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 0 {
    ; CHECK-NEXT:   $r0 = ABS killed $r0, implicit-def $srcarry
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: NOP
    ST_dms_sts_idx_imm $r1, $p0, 0
    $r0 = ABS $r0, implicit-def $srcarry
    $wl0 = IMPLICIT_DEF
...


---
name:            nop_replacing_meta
alignment:       16
body:             |
  bb.1.entry:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: nop_replacing_meta
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = LDA_dms_lda_idx_imm killed $p0, 0
    ; CHECK-NEXT: $wl0 = IMPLICIT_DEF
    ; CHECK-NEXT: $wl1 = IMPLICIT_DEF
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $r0 = LDA_dms_lda_idx_imm $p0, 0
    $wl0 = IMPLICIT_DEF
    $wl1 = IMPLICIT_DEF
...
