# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

# NOTE: Accumulator inputs are read in E3, and ouput is written in E5

---
name:            bypass_output
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_output
    ; CHECK: $cm0 = VADD killed $cm4, killed $cm2, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm0 = VSUB killed $cm0, killed $cm1, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $cm0 = VADD $cm4, $cm2, $r5
    $cm0 = VSUB $cm0, $cm1, $r1
...

---
name:            bypass_acc_input1
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_acc_input1
    ; CHECK: $cm0 = VNEGADD killed $cm1, killed $cm2, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm3 = VNEGSUB killed $cm0, killed $cm4, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $cm0 = VNEGADD $cm1, $cm2, $r5
    $cm3 = VNEGSUB $cm0, $cm4, $r1
...

---
name:            bypass_acc_input2
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass_acc_input2
    ; CHECK: $cm0 = VSUB killed $cm2, killed $cm1, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm3 = VADD killed $cm5, killed $cm0, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $cm0 = VSUB $cm2, $cm1, $r5
    $cm3 = VADD $cm5, $cm0, $r1
...

---
name:            no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass
    ; CHECK: $cm0 = VNEGSUB killed $cm1, killed $cm2, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $cm0 = VNEGSUB $cm1, $cm2, $r5
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...
