# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            vaddmac_f_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vaddmac_f_sched
    ; CHECK: $r5 = OR killed $r5, killed $r2
    ; CHECK-NEXT: $bml0 = VADDMAC_F_vmac_bm_core_dense killed $bml0, killed $bml2, killed $x3, killed $x4, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $r5 = OR $r5, $r2
    $bml0 = VADDMAC_F_vmac_bm_core_dense $bml0, $bml2, $x3, $x4, $r5, implicit-def $srfpflags, implicit $crfpmask
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            vaddmac_f_acc_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vaddmac_f_acc_sched
    ; CHECK: $amll2 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml0 = VADDMAC_F_vmac_bm_core_dense killed $bml0, killed $bml2, killed $x3, killed $x4, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $amll2 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
    $bml0 = VADDMAC_F_vmac_bm_core_dense $bml0, $bml2, $x3, $x4, $r5, implicit-def $srfpflags, implicit $crfpmask
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            vaddmsc_f_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vaddmsc_f_sched
    ; CHECK: $x3 = VEXTBCST_32_mExtractIdxImm killed $x1, 9
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bmh0 = VADDMSC_F_vmac_bm_core_dense killed $bmh0, killed $bml2, killed $x3, killed $x4, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amhh0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $x3 = VEXTBCST_32_mExtractIdxImm  $x1, 9
    $bmh0 = VADDMSC_F_vmac_bm_core_dense $bmh0, $bml2, $x3, $x4, $r5, implicit-def $srfpflags, implicit $crfpmask
    VST_dmw_sts_am_ag_idx_imm $amhh0, $p0, 0
...
