# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass
    ; CHECK: $cm0 = VADDMAC_vmac_bm_core_dense killed $cm0, killed $cm2, killed $x3, killed $x4, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm0 = VSUBMSC_vmac_bm_core_dense killed $cm0, killed $cm1, killed $x1, killed $x2, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $cm0 = VADDMAC_vmac_bm_core_dense $cm0, $cm2, $x3, $x4, $r5
    $cm0 = VSUBMSC_vmac_bm_core_dense $cm0, $cm1, $x1, $x2, $r1
...

---
name:            no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass
    ; CHECK: $cm0 = VSUBMAC_vmac_bm_core_dense killed $cm0, killed $cm2, killed $x3, killed $x4, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $cm0 = VSUBMAC_vmac_bm_core_dense $cm0, $cm2, $x3, $x4, $r5
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...
