# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s


---
name:            vclr_bf_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vclr_bf_sched
    ; CHECK: $bml0 = VCLR_vclr_BF implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $bml0 = VCLR_vclr_BF implicit-def $srfpflags, implicit $crfpmask
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            vclr_sched_no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vclr_sched_no_bypass
    ; CHECK: $cm0 = VCLR_vclr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $cm0 = VCLR_vclr
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            vclr_sched_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vclr_sched_bypass
    ; CHECK: $cm0 = VCLR_vclr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm0 = VNEGMAC_vmac_cm_core_dense killed $cm0, killed $x0, killed $x1, killed $r1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $cm0 = VCLR_vclr
    $cm0 = VNEGMAC_vmac_cm_core_dense $cm0, $x0, $x1, $r1
...
