# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s


---
name:            vlt_bf_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vlt_bf_sched
    ; CHECK: $r16 = VLT_BF16 killed $x0, killed $x5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r3 = AND killed $r16, killed $r2
    $r16 = VLT_BF16 $x0, $x5
    $r3 = AND $r16, $r2
...

---
name:            vge_bf_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vge_bf_sched
    ; CHECK: $r19 = VGE_BF16 killed $x3, killed $x4
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r3 = OR killed $r16, killed $r19
    $r19 = VGE_BF16 $x3, $x4
    $r3 = OR $r16, $r19
...

---
name:            bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass
    ; CHECK: $x0 = VPUSH_LO_32 killed $r3, killed $x11
    ; CHECK-NEXT: $r19 = VGE_BF16 killed $x0, killed $x4
    ; CHECK-NEXT: NOP
    $x0 = VPUSH_LO_32  $r3,  $x11
    $r19 = VGE_BF16 $x0, $x4
...
