# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            latency_w
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_w
    ; CHECK: $wl0 = VCONV_BF16_FP32 killed $bml0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VADD_8 killed $x0, killed $x1
    ; CHECK-NEXT: NOP
    $wl0 = VCONV_BF16_FP32 $bml0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    $x0 = VADD_8 $x0, $x1
...

---
name:            latency_bm
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_bm
    ; CHECK: $bml0 = VCONV_FP32_BF16 killed $wl0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VCONV_BF16_FP32 killed $bml0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: NOP
    $bml0 = VCONV_FP32_BF16 $wl0
    $wl0 = VCONV_BF16_FP32 $bml0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
...
