# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s

# VEXTBCST
---
name:            bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass
    ; CHECK: $x0 = VEXTBCST_8_mRm killed $x3, killed $r9
    ; CHECK-NEXT: $x1 = VEXTBCST_16_mRm $x0, killed $r12
    ; CHECK-NEXT: $x2 = VEXTBCST_32_mRm $x1, killed $r19
    ; CHECK-NEXT: $x3 = VEXTBCST_64_mExtractIdxImm $x2, 12
    ; CHECK-NEXT: $r0 = VEXTRACT_S32 killed $x0, $r16
    ; CHECK-NEXT: $r1 = VEXTRACT_S32 killed $x1, $r16
    ; CHECK-NEXT: $l2 = VEXTRACT_S64 killed $x2, $r16
    ; CHECK-NEXT: $r3 = VEXTRACT_S32 killed $x3, killed $r16
    ; CHECK-NEXT: NOP
    $x0 = VEXTBCST_8_mRm $x3, $r9
    $r0 = VEXTRACT_S32 $x0,  $r16
    $x1 = VEXTBCST_16_mRm $x0, $r12
    $r1 = VEXTRACT_S32 $x1,  $r16
    $x2 = VEXTBCST_32_mRm  $x1, $r19
    $l2 = VEXTRACT_S64 $x2,  $r16
    $x3 = VEXTBCST_64_mExtractIdxImm  $x2, 12
    $r3 = VEXTRACT_S32 $x3,  $r16
...

---
name:            no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass
    ; CHECK: $x2 = VEXTBCST_32_mExtractIdxImm killed $x1, 9
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl2, killed $p0, 0
    ; CHECK-NEXT: NOP
    $x2 = VEXTBCST_32_mExtractIdxImm  $x1, 9
    VST_dmw_sts_w_ag_idx_imm $wl2, $p0, 0
...
