# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            latency_x_am
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_x_am
    ; CHECK: $x0 = VFLOOR_S32_BF16_mFl2FxSrc_AM killed $amll3, killed $s0, implicit-def $srf2iflags, implicit $crf2imask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VSHIFT killed $x0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
  $x0 = VFLOOR_S32_BF16_mFl2FxSrc_AM $amll3, $s0, implicit-def $srf2iflags, implicit $crf2imask
  $x0 = VSHIFT $x0, $x1, $r0
...

---
name:            latency_x_w
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_x_w
    ; CHECK: $x1 = VFLOOR_S32_BF16_mFl2FxSrc_W killed $wl2, killed $s1, implicit-def $srf2iflags, implicit $crf2imask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VSHIFT killed $x0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
  $x1 = VFLOOR_S32_BF16_mFl2FxSrc_W $wl2, $s1, implicit-def $srf2iflags, implicit $crf2imask
  $x0 = VSHIFT $x0, $x1, $r0
...
