# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass
    ; CHECK: $x0 = VINSERT_8 killed $x0, $r29, $r0
    ; CHECK-NEXT: $r1 = VEXTRACT_S8 $x0, $r16
    ; CHECK-NEXT: $x0 = VINSERT_16 killed $x0, $r29, $r0
    ; CHECK-NEXT: $r1 = VEXTRACT_S16 $x0, $r16
    ; CHECK-NEXT: $x0 = VINSERT_32 killed $x0, $r29, killed $r0
    ; CHECK-NEXT: $r1 = VEXTRACT_S32 $x0, $r16
    ; CHECK-NEXT: $x0 = VINSERT_64 killed $x0, killed $r29, $l0
    ; CHECK-NEXT: $l0 = VEXTRACT_S64 killed $x0, killed $r16
    ; CHECK-NEXT: NOP
    $x0 = VINSERT_8 $x0, $r29, $r0
    $r1 = VEXTRACT_S8  $x0, $r16
    $x0 = VINSERT_16 $x0, $r29, $r0
    $r1 = VEXTRACT_S16  $x0, $r16
    $x0 = VINSERT_32 $x0, $r29, $r0
    $r1 = VEXTRACT_S32  $x0, $r16
    $x0 = VINSERT_64 $x0, $r29, $l0
    $l0 = VEXTRACT_S64  $x0, $r16
...

---
name:            no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass
    ; CHECK: $x0 = VINSERT_8 killed $x0, killed $r29, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $x0 = VINSERT_8 $x0, $r29, $r0
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...
