# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s


---
name:            output_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: output_bypass
    ; CHECK: $cm2 = VMOV_D killed $cm1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm3 = VNEG killed $cm2, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $cm2 = VMOV_D $cm1
    $cm3 = VNEG $cm2, $r5
...

---
name:            output_no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: output_no_bypass
    ; CHECK: $cm0 = VMOV_D killed $cm1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $cm0 = VMOV_D $cm1
    VST_dmw_sts_am_ag_idx_imm $amll0, $p0, 0
...

---
name:            input
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: input
    ; CHECK: $amll0 = VLDA_dmw_lda_am_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm1 = VMOV_D killed $cm0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $amll0 = VLDA_dmw_lda_am_ag_idx_imm $p0, 0
    $cm1 = VMOV_D $cm0
...
