# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -issue-limit=6 -o - | FileCheck %s

# Tests the VMOV latencies, with and without bypasses.

---
name:            vmov_wl
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vmov_wl
    ; CHECK: $wl2 = VMOV_mv_w killed $wl0
    ; CHECK-NEXT: $wl4 = VMOV_mv_w killed $wl2
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl4, killed $p0, 0
    ; CHECK-NEXT: NOP
    $wl2 = VMOV_mv_w $wl0
    $wl4 = VMOV_mv_w $wl2
    VST_dmw_sts_w_ag_idx_imm $wl4, $p0, 0
...

---
name:            vmov_wh
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vmov_wh
    ; CHECK: $wh2 = VMOV_mv_w killed $wh0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wh4 = VMOV_mv_w killed $wh2
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wh4, killed $p0, 0
    ; CHECK-NEXT: NOP
    $wh2 = VMOV_mv_w $wh0
    $wh4 = VMOV_mv_w $wh2
    VST_dmw_sts_w_ag_idx_imm $wh4, $p0, 0
...

---
name:            vmov_x
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vmov_x
    ; CHECK: $x2 = VMOV_mv_x killed $x0
    ; CHECK-NEXT: $x4 = VMOV_mv_x killed $x2
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wh4, killed $p0, 0
    ; CHECK-NEXT: NOP
    $x2 = VMOV_mv_x $x0
    $x4 = VMOV_mv_x $x2
    VST_dmw_sts_w_ag_idx_imm $wh4, $p0, 0
...
