# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            vmulf_vnegmulf_latency_bm
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vmulf_vnegmulf_latency_bm
    ; CHECK: $bml0 = VMUL_F_vmac_bm_core_dense $x0, $x1, $r0, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $bml1 = VNEGMUL_F_vmac_bm_core_dense killed $x0, killed $x1, killed $r0, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: $p1, $dc5 = VST_2D_SRS_D16_S32 killed $p1, killed $d5, killed $bml1, killed $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $bml0 = VMUL_F_vmac_bm_core_dense $x0, $x1, $r0, implicit-def $srfpflags, implicit $crfpmask
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $bml1 = VNEGMUL_F_vmac_bm_core_dense $x0, $x1, $r0, implicit-def $srfpflags, implicit $crfpmask
    $p1, $dc5 = VST_2D_SRS_D16_S32 $p1, $d5, $bml1, $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            vmacf_vmscf_latency_bm
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vmacf_vmscf_latency_bm
    ; CHECK: $bml0 = VMAC_F_vmac_bm_core_dense killed $bml0, $x0, $x1, $r1, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $bml1 = VMSC_F_vmac_bm_core_dense killed $bml1, killed $x0, killed $x1, killed $r1, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $p0, $dc7 = VST_2D_SRS_D16_S32 killed $p0, killed $d7, killed $bml0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: $p1, $dc5 = VST_2D_SRS_D16_S32 killed $p1, killed $d5, killed $bml1, killed $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $bml0 = VMAC_F_vmac_bm_core_dense $bml0, $x0, $x1, $r1, implicit-def $srfpflags, implicit $crfpmask
    $p0, $dc7 = VST_2D_SRS_D16_S32 $p0, $d7, $bml0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $bml1 = VMSC_F_vmac_bm_core_dense $bml1, $x0, $x1, $r1, implicit-def $srfpflags, implicit $crfpmask
    $p1, $dc5 = VST_2D_SRS_D16_S32 $p1, $d5, $bml1, $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...
