# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s


---
name:            vneg_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vneg_sched
    ; CHECK: $cm0 = VADD killed $cm4, killed $cm2, $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm2 = VNEG killed $cm0, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm6 = VADD $cm2, killed $cm3, killed $r6
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll2, killed $p0, 0
    ; CHECK-NEXT: NOP
    $cm0 = VADD $cm4, $cm2, $r5
    $cm2 = VNEG $cm0, $r5
    $cm6 = VADD $cm2, $cm3, $r6
    VST_dmw_sts_am_ag_idx_imm $amll2, $p0, 0
...

---
name:            vneg_sched_no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vneg_sched_no_bypass
    ; CHECK: $bml0 = VADD_F killed $bml4, killed $bml2, $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm2 = VNEG killed $cm0, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll2, killed $p0, 0
    ; CHECK-NEXT: NOP
    $bml0 = VADD_F killed $bml4, killed $bml2, $r5, implicit-def $srfpflags, implicit $crfpmask
    $cm2 = VNEG $cm0, $r5
    VST_dmw_sts_am_ag_idx_imm $amll2, $p0, 0
...
