# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s


---
name:            vneg_f_sched
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vneg_f_sched
    ; CHECK: $cm0 = VADD killed $cm4, killed $cm2, $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $bml2 = VNEG_F killed $bml0, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_am_ag_idx_imm killed $amll2, killed $p0, 0
    ; CHECK-NEXT: NOP
    $cm0 = VADD $cm4, $cm2, $r5
    $bml2 = VNEG_F $bml0, $r5, implicit-def $srfpflags, implicit $crfpmask
    VST_dmw_sts_am_ag_idx_imm $amll2, $p0, 0
...
