# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 %topdown-single -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

---
name:            vpack_w_out
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vpack_w_out
    ; CHECK: $wl0 = VPACK_D8_D16 killed $x2, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl2 = VMOV_mv_w killed $wl0
    ; CHECK-NEXT: NOP
    $wl0 = VPACK_D8_D16 $x2, implicit $crsat, implicit $crpacksign
    $wl2 = VMOV_mv_w $wl0
...

---
name:            vpack_crsat_in
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vpack_crsat_in
    ; CHECK: $crsat = VEXTRACT_S32 killed $x2, killed $r16
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl2 = VPACK_D8_D16 killed $x4, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: $crsat = MOVXM_lng_cg 0
    $crsat = VEXTRACT_S32 $x2, $r16
    $wl2 = VPACK_D8_D16 $x4, implicit $crsat, implicit $crpacksign
    $crsat = MOVXM_lng_cg 0
...

---
name:            vpack_x_in
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vpack_x_in
    ; CHECK: $wl2 = VLDA_dmw_lda_w_ag_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VPACK_D8_D16 killed $x2, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: NOP
    $wl2 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0
    $wl0 = VPACK_D8_D16 $x2, implicit $crsat, implicit $crpacksign
...

---
name:            vpack_crpacksign_in
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vpack_crpacksign_in
    ; CHECK: $crpacksign = VEXTRACT_S32 $x2, killed $r16
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VPACK_D8_D16 killed $x2, implicit $crsat, implicit $crpacksign
    ; CHECK-NEXT: NOP
    $crpacksign = VEXTRACT_S32 $x2, $r16
    $wl0 = VPACK_D8_D16 $x2, implicit $crsat, implicit $crpacksign
...
