# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

# VPUSH
---
name:            bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass
    ; CHECK: $x0 = VPUSH_LO_32 killed $r3, killed $x1
    ; CHECK-NEXT: $x9 = VPUSH_LO_64 killed $l3, killed $x0
    ; CHECK-NEXT: $x6 = VPUSH_HI_8 killed $x9, $r8
    ; CHECK-NEXT: $x5 = VPUSH_HI_16 killed $x6, killed $r8
    ; CHECK-NEXT: $x10 = VMOV_mv_x killed $x5
    ; CHECK-NEXT: NOP
    $x0 = VPUSH_LO_32 $r3,  $x1
    $x9 = VPUSH_LO_64 $l3,  $x0
    $x6 = VPUSH_HI_8  $x9,  $r8
    $x5 = VPUSH_HI_16 $x6,  $r8
    $x10 = VMOV_mv_x $x5
...

---
name:            no_bypass_lo
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_lo
    ; CHECK: $x5 = VPUSH_LO_64 killed $l3, killed $x0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl5, killed $p2, 0
    ; CHECK-NEXT: NOP
    $x5 = VPUSH_LO_64 $l3,  $x0
    VST_dmw_sts_w_ag_idx_imm $wl5, $p2, 0
...

---
name:            no_bypass_hi
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_hi
    ; CHECK: $x6 = VPUSH_HI_8 killed $x9, killed $r8
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl6, killed $p2, 0
    ; CHECK-NEXT: NOP
    $x6 = VPUSH_HI_8  $x9,  $r8
    VST_dmw_sts_w_ag_idx_imm $wl6, $p2, 0
...
