# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: bypass
    ; CHECK: $x0 = VSHIFT_ALIGN killed $x0, killed $s0, killed $x1, killed $r0
    ; CHECK-NEXT: $r1 = VEXTRACT_S8 killed $x0, killed $r16
    ; CHECK-NEXT: NOP
    $x0 = VSHIFT_ALIGN $x0, $s0, $x1, $r0
    $r1 = VEXTRACT_S8  $x0, $r16
...

---
name:            no_bypass
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass
    ; CHECK: $x0 = VSHIFT_ALIGN killed $x0, killed $s0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $x0 = VSHIFT_ALIGN $x0, $s0, $x1, $r0
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...

---
name:            no_bypass_1
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: no_bypass_1
    ; CHECK: $wh1 = VLDA_dmw_lda_w_ag_idx_imm killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VSHIFT_ALIGN killed $x0, killed $s0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_ag_idx_imm killed $wl0, killed $p0, 0
    ; CHECK-NEXT: NOP
    $wh1 = VLDA_dmw_lda_w_ag_idx_imm $p1, 0
    $x0 = VSHIFT_ALIGN $x0, $s0, $x1, $r0
    VST_dmw_sts_w_ag_idx_imm $wl0, $p0, 0
...
