# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            latency_w
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_w
    ; CHECK: $wl0 = VSRS_D8_S32_mv_w_srs killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VADD_8 killed $x0, killed $x1
    ; CHECK-NEXT: NOP
    $wl0 = VSRS_D8_S32_mv_w_srs $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $x0 = VADD_8 $x0, $x1
...

---
name:            latency_x
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_x
    ; CHECK: $x0 = VSRS_D16_S32_mv_x_srs killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $x0 = VADD_8 killed $x0, killed $x1
    ; CHECK-NEXT: NOP
    $x0 = VSRS_D16_S32_mv_x_srs $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $x0 = VADD_8 $x0, $x1
...
