# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 --issue-limit=1 -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

---
name:            vunpack
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vunpack
    ; CHECK: $x0 = VUNPACK_D16_D8 killed $wh1, implicit $crunpacksign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r1 = VEXTRACT_S8 killed $x0, $r16
    ; CHECK-NEXT: $x0 = VUNPACK_D8_D4 killed $wl4, implicit $crunpacksign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r1 = VEXTRACT_S16 killed $x0, $r16
    ; CHECK-NEXT: $x0 = VUNPACK_S16_S8 killed $wh5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r1 = VEXTRACT_S32 killed $x0, killed $r16
    ; CHECK-NEXT: NOP
    $x0 = VUNPACK_D16_D8  $wh1, implicit $crunpacksign
    $r1 = VEXTRACT_S8  $x0, $r16
    $x0 = VUNPACK_D8_D4 $wl4, implicit $crunpacksign
    $r1 = VEXTRACT_S16  $x0, $r16
    $x0 = VUNPACK_S16_S8 $wh5,
    $r1 = VEXTRACT_S32  $x0, $r16
...
