# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

---
name:            latency_w2c
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_w2c
    ; CHECK: $cm7 = VUPS_S64_D16_mv_ups_w2c killed $wh3, killed $s2, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VSRS_D8_S32_mv_w_srs killed $cm7, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $cm7 = VUPS_S64_D16_mv_ups_w2c $wh3, $s2, implicit-def $srups_of, implicit $crsat, implicit $crupssign
  $wl0 = VSRS_D8_S32_mv_w_srs $cm7, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            latency_w2b
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_w2b
    ; CHECK: $bml1 = VUPS_S64_D32_mv_ups_w2b killed $wh6, $s2, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wl0 = VSRS_D8_S32_mv_w_srs killed $cm1, killed $s2, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml1 = VUPS_S64_D32_mv_ups_w2b $wh6, $s2, implicit-def $srups_of, implicit $crsat, implicit $crupssign
  $wl0 = VSRS_D8_S32_mv_w_srs $cm1, $s2, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            latency_x2c
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: latency_x2c
    ; CHECK: $cm8 = VUPS_S64_D32_mv_ups_x2c killed $x2, killed $s2, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $wh7 = VSRS_D8_S32_mv_w_srs killed $cm8, killed $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $cm8 = VUPS_S64_D32_mv_ups_x2c $x2, $s2, implicit-def $srups_of, implicit $crsat, implicit $crupssign
  $wh7 = VSRS_D8_S32_mv_w_srs $cm8, $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...
