; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc < %s -verify-machineinstrs -mtriple=aie2ps | FileCheck %s
; ModuleID = 't.cpp'
source_filename = "t.cpp"
target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2ps"

%struct.v64mx9 = type <{ <16 x i32>, <2 x i32>, <2 x i32> }>
%struct.v256mx9 = type { <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> }
%struct.v128mx6 = type { <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 }
%struct.v256mx6 = type { <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32, i32, i32, i32, i32 }

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(inaccessiblemem: read)
define dso_local inreg noundef <64 x float> @test_mul_4x16_16x16T6v64mx97v256mx9(%struct.v64mx9 %a.coerce, %struct.v256mx9 %b.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test_mul_4x16_16x16T6v64mx97v256mx9:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    paddxm [sp], #64; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r8, #972; nopb ; st r9:r8, [sp, #-64] // 8-byte Folded Spill
; CHECK-NEXT:    vmul.f dm0, ex0, ey2, ey3, r8
; CHECK-NEXT:    lda r9:r8, [sp, #-64] // 8-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 1
entry:
  %0 = extractvalue %struct.v64mx9 %a.coerce, 0
  %1 = extractvalue %struct.v64mx9 %a.coerce, 1
  %2 = extractvalue %struct.v64mx9 %a.coerce, 2
  %3 = extractvalue %struct.v256mx9 %b.coerce, 0
  %4 = extractvalue %struct.v256mx9 %b.coerce, 1
  %5 = extractvalue %struct.v256mx9 %b.coerce, 2
  %6 = extractvalue %struct.v256mx9 %b.coerce, 3
  %7 = extractvalue %struct.v256mx9 %b.coerce, 4
  %8 = extractvalue %struct.v256mx9 %b.coerce, 5
  %9 = extractvalue %struct.v256mx9 %b.coerce, 6
  %10 = extractvalue %struct.v256mx9 %b.coerce, 7
  %11 = extractvalue %struct.v256mx9 %b.coerce, 8
  %12 = extractvalue %struct.v256mx9 %b.coerce, 9
  %13 = extractvalue %struct.v256mx9 %b.coerce, 10
  %14 = extractvalue %struct.v256mx9 %b.coerce, 11
  %15 = tail call noundef <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mul.conf(<16 x i32> %0, <2 x i32> %1, <2 x i32> %2, <16 x i32> %3, <16 x i32> %4, <16 x i32> %5, <16 x i32> %6, <2 x i32> %7, <2 x i32> %8, <2 x i32> %9, <2 x i32> %10, <2 x i32> %11, <2 x i32> %12, <2 x i32> %13, <2 x i32> %14, i32 972)
  ret <64 x float> %15
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(inaccessiblemem: read)
define dso_local inreg noundef <64 x float> @test_mul_4x16_16x16T7v128mx67v256mx6(%struct.v128mx6 %a.coerce, %struct.v256mx6 %b.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test_mul_4x16_16x16T7v128mx67v256mx6:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    paddxm [sp], #64; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r8, #772; nopb ; st r9:r8, [sp, #-64] // 8-byte Folded Spill
; CHECK-NEXT:    lda r9:r8, [sp, #-64]; vmul.f dm0, fex0, fey1, r8 // 8-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 1
entry:
  %0 = extractvalue %struct.v128mx6 %a.coerce, 0
  %1 = extractvalue %struct.v128mx6 %a.coerce, 1
  %2 = extractvalue %struct.v128mx6 %a.coerce, 2
  %3 = extractvalue %struct.v128mx6 %a.coerce, 3
  %4 = extractvalue %struct.v128mx6 %a.coerce, 4
  %5 = extractvalue %struct.v128mx6 %a.coerce, 5
  %6 = extractvalue %struct.v128mx6 %a.coerce, 6
  %7 = extractvalue %struct.v128mx6 %a.coerce, 7
  %8 = extractvalue %struct.v256mx6 %b.coerce, 0
  %9 = extractvalue %struct.v256mx6 %b.coerce, 1
  %10 = extractvalue %struct.v256mx6 %b.coerce, 2
  %11 = extractvalue %struct.v256mx6 %b.coerce, 3
  %12 = extractvalue %struct.v256mx6 %b.coerce, 4
  %13 = extractvalue %struct.v256mx6 %b.coerce, 5
  %14 = extractvalue %struct.v256mx6 %b.coerce, 6
  %15 = extractvalue %struct.v256mx6 %b.coerce, 7
  %16 = extractvalue %struct.v256mx6 %b.coerce, 8
  %17 = extractvalue %struct.v256mx6 %b.coerce, 9
  %18 = extractvalue %struct.v256mx6 %b.coerce, 10
  %19 = extractvalue %struct.v256mx6 %b.coerce, 11
  %20 = extractvalue %struct.v256mx6 %b.coerce, 12
  %21 = extractvalue %struct.v256mx6 %b.coerce, 13
  %22 = extractvalue %struct.v256mx6 %b.coerce, 14
  %23 = extractvalue %struct.v256mx6 %b.coerce, 15
  %24 = tail call noundef <64 x float> @llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.mul.conf(<8 x i32> %0, <8 x i32> %1, <2 x i32> %2, <2 x i32> %3, i32 %4, i32 %5, i32 %6, i32 %7, <8 x i32> %8, <8 x i32> %9, <8 x i32> %10, <8 x i32> %11, <2 x i32> %12, <2 x i32> %13, <2 x i32> %14, <2 x i32> %15, i32 %16, i32 %17, i32 %18, i32 %19, i32 %20, i32 %21, i32 %22, i32 %23, i32 772)
  ret <64 x float> %24
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x float> @llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mul.conf(<16 x i32>, <2 x i32>, <2 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, i32) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x float> @llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.mul.conf(<8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32, i32, i32, i32, i32, i32) #1

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(inaccessiblemem: read) "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"wchar_size", i32 4}
