; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2ps %s -o - | FileCheck %s

define dso_local noundef <64 x i8> @_Z21test_get_scd_v128int4i(i32 noundef %en)  {
; CHECK-LABEL: _Z21test_get_scd_v128int4i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov x0, scd // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 %en)
  %1 = bitcast <16 x i32> %0 to <64 x i8>
  ret <64 x i8> %1
}


define dso_local inreg noundef <16 x i32> @_Z21test_get_scd_v16acc32i(i32 noundef %en)  {
; CHECK-LABEL: _Z21test_get_scd_v16acc32i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov bmll0, scd // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 %en)
  ret <16 x i32> %0
}


define dso_local inreg noundef <32 x i32> @_Z24test_get_scd_v32acc32_loi(i32 noundef %en)  {
; CHECK-LABEL: _Z24test_get_scd_v32acc32_loi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov.0 cml0, scd // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.lo(i32 %en)
  ret <32 x i32> %0
}


define dso_local inreg noundef <32 x i32> @_Z24test_get_scd_v32acc32_hii(i32 noundef %en)  {
; CHECK-LABEL: _Z24test_get_scd_v32acc32_hii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov.1 cml0, scd // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.hi(i32 %en)
  ret <32 x i32> %0
}


define dso_local inreg noundef <64 x i32> @_Z23test_get_scd_v64acc32_0i(i32 noundef %en)  {
; CHECK-LABEL: _Z23test_get_scd_v64acc32_0i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    movx crscden, #0 // Delay Slot 4
; CHECK-NEXT:    vmov.0 dm0, scd // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <64 x i32> @llvm.aie2ps.scd.ACC2048(i32 %en, i32 0)
  ret <64 x i32> %0
}


define dso_local inreg noundef <64 x i32> @_Z23test_get_scd_v64acc32_1i(i32 noundef %en)  {
; CHECK-LABEL: _Z23test_get_scd_v64acc32_1i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov.1 dm0, scd // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <64 x i32> @llvm.aie2ps.scd.ACC2048(i32 %en, i32 1)
  ret <64 x i32> %0
}


define dso_local inreg noundef <64 x i32> @_Z23test_get_scd_v64acc32_2i(i32 noundef %en)  {
; CHECK-LABEL: _Z23test_get_scd_v64acc32_2i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    movx crscden, #2 // Delay Slot 4
; CHECK-NEXT:    vmov.2 dm0, scd // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <64 x i32> @llvm.aie2ps.scd.ACC2048(i32 %en, i32 2)
  ret <64 x i32> %0
}


define dso_local inreg noundef <64 x i32> @_Z23test_get_scd_v64acc32_3i(i32 noundef %en)  {
; CHECK-LABEL: _Z23test_get_scd_v64acc32_3i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    movx crscden, #3 // Delay Slot 4
; CHECK-NEXT:    vmov.3 dm0, scd // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <64 x i32> @llvm.aie2ps.scd.ACC2048(i32 %en, i32 3)
  ret <64 x i32> %0
}


define dso_local inreg noundef <32 x i32> @_Z28test_get_scd_expand_v32acc32ii(i32 noundef %en, i32 noundef %pos)  {
; CHECK-LABEL: _Z28test_get_scd_expand_v32acc32ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    or r31, r1, r1; mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov dm0, scd, r31 // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.ACC1024(i32 %en, i32 %pos)
  ret <32 x i32> %0
}


define dso_local inreg noundef <64 x i32> @_Z28test_get_scd_expand_v64acc32ii(i32 noundef %en, i32 noundef %pos)  {
; CHECK-LABEL: _Z28test_get_scd_expand_v64acc32ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    or r31, r1, r1; mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov dm0, scd, r31 // Delay Slot 3
; CHECK-NEXT:    movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <64 x i32> @llvm.aie2ps.scd.expand.ACC2048(i32 %en, i32 %pos)
  ret <64 x i32> %0
}

define dso_local inreg noundef <32 x i32> @_Z33test_get_scd_expand_v32acc32_incriRi(i32 noundef %en, ptr nocapture nonnull align 4 dereferenceable(4) %pos) {
; CHECK-LABEL: _Z33test_get_scd_expand_v32acc32_incriRi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda r31, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov dm0, scd, r31++ // Delay Slot 3
; CHECK-NEXT:    st r31, [p0, #0]; movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = load i20, ptr %pos, align 4
  %1 = inttoptr i20 %0 to ptr
  %2 = tail call { <16 x i64>, i32 } @llvm.aie2ps.scd.expand.ACC1024.incr(i32 %en, ptr %1)
  %3 = extractvalue { <16 x i64>, i32 } %2, 1
  store i32 %3, ptr %pos, align 4
  %4 = extractvalue { <16 x i64>, i32 } %2, 0
  %5 = bitcast <16 x i64> %4 to <32 x i32>
  ret <32 x i32> %5
}

define dso_local inreg noundef <64 x i32> @_Z33test_get_scd_expand_v64acc32_incriRi(i32 noundef %en, ptr nocapture nonnull align 4 dereferenceable(4) %pos) {
; CHECK-LABEL: _Z33test_get_scd_expand_v64acc32_incriRi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda r31, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov crscden, r0 // Delay Slot 4
; CHECK-NEXT:    vmov dm0, scd, r31++ // Delay Slot 3
; CHECK-NEXT:    st r31, [p0, #0]; movx crscden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = load i20, ptr %pos, align 4
  %1 = inttoptr i20 %0 to ptr
  %2 = tail call { <32 x i64>, i32 } @llvm.aie2ps.scd.expand.ACC2048.incr(i32 %en, ptr %1)
  %3 = extractvalue { <32 x i64>, i32 } %2, 1
  store i32 %3, ptr %pos, align 4
  %4 = extractvalue { <32 x i64>, i32 } %2, 0
  %5 = bitcast <32 x i64> %4 to <64 x i32>
  ret <64 x i32> %5
}

define dso_local void @_Z12test_put_mcdDv64_DB8_i(<64 x i8> noundef %a, i32 noundef %en)  {
; CHECK-LABEL: _Z12test_put_mcdDv64_DB8_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crmcden, r0 // Delay Slot 3
; CHECK-NEXT:    vmov mcd, x0; movx crmcden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %a to <16 x i32>
  tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> %0, i32 %en)
  ret void
}


define dso_local void @_Z12test_put_mcdDv8_u7__acc64i(<8 x i64> inreg noundef %a, i32 noundef %en)  {
; CHECK-LABEL: _Z12test_put_mcdDv8_u7__acc64i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crmcden, r0 // Delay Slot 3
; CHECK-NEXT:    vmov mcd, bmll0; movx crmcden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> %a, i32 %en)
  ret void
}

declare <16 x i32> @llvm.aie2ps.scd.read.vec(i32)
declare <16 x i32> @llvm.aie2ps.scd.read.acc32(i32)
declare <32 x i32> @llvm.aie2ps.scd.expand.lo(i32)
declare <32 x i32> @llvm.aie2ps.scd.expand.hi(i32)
declare <64 x i32> @llvm.aie2ps.scd.ACC2048(i32, i32)
declare <32 x i32> @llvm.aie2ps.scd.expand.ACC1024(i32, i32)
declare <64 x i32> @llvm.aie2ps.scd.expand.ACC2048(i32, i32)
declare { <16 x i64>, i32 } @llvm.aie2ps.scd.expand.ACC1024.incr(i32, ptr)
declare { <32 x i64>, i32 } @llvm.aie2ps.scd.expand.ACC2048.incr(i32, ptr)
declare void @llvm.aie2ps.mcd.write.vec(<16 x i32>, i32)
declare void @llvm.aie2ps.mcd.write.acc32(<8 x i64>, i32)
