# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass postmisched -verify-machineinstrs -o - %s | FileCheck %s

# AIE2PS has an activity monitor for MAC instructions. That was leading to all
# MAC instructions having the side-effect flag being set. That is not necessary.
# Make sure that other instructions can move past MAC instructions.

---
name:            test
body:             |
  bb.0.entry:
    liveins: $dm0, $x0, $x1, $r8, $p0, $p1

    ; CHECK-LABEL: name: test
    ; CHECK: liveins: $dm0, $x0, $x1, $r8, $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $wl0 = VLDA_dmw_lda_w_ld_idx_imm killed renamable $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: BUNDLE implicit-def $dm0, implicit-def $cml0, implicit-def $bmll0, implicit-def $bmlh0, implicit-def $cmh0, implicit-def $bmhl0, implicit-def $bmhh0, implicit $lr, implicit killed $dm0, implicit $x0, implicit killed $x1, implicit killed $r8 {
    ; CHECK-NEXT:   RET implicit $lr
    ; CHECK-NEXT:   renamable $dm0 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm0, renamable $x0, killed renamable $x1, killed renamable $r8
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: VST_dmw_sts_w_st_idx_imm killed renamable $wl0, killed renamable $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
    renamable $dm0 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm0, killed renamable $x0, killed renamable $x1, killed renamable $r8
    renamable $wl0 = VLDA_dmw_lda_w_ld_idx_imm renamable killed $p0, 0
    VST_dmw_sts_w_st_idx_imm killed renamable $wl0, renamable killed $p1, 0
    RET implicit $lr
    DelayedSchedBarrier
...
