# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass=postmisched %s -o - | FileCheck %s

---
name:            fifo_pop_then_read_srfifo_uf
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24, $m0

    ; CHECK-LABEL: name: fifo_pop_then_read_srfifo_uf
    ; CHECK: liveins: $p0, $lf0, $r24, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $ex0, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_ex_bfp16_fifo_1d_pop killed $p0, killed $lf0, killed $r24, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: $ex0, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_ex_bfp16_fifo_1d_pop killed $p0, killed $lf0, killed $r24, killed $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed $r0, implicit killed $ex0
    $ex0, $p0, $lf0, $r24 = VLD_POP_640_fifo_1d_pop_pseudo $p0, $lf0, $r24, $m0, implicit-def $srfifo_uf
    $ex0, $p0, $lf0, $r24 = VLD_POP_640_fifo_1d_pop_pseudo $p0, $lf0, $r24, $m0, implicit-def $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    $r0 = MOV_alu_mv_mv_mv_r_sc $srfifo_uf
    PseudoRET implicit $lr, implicit $r0, implicit $ex0
...
