# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass postmisched -verify-machineinstrs -o - %s | FileCheck %s

# Verify the scalar bypass of the MV slot in AIE2PS
# Make sure there is no bypass between VLT and VSEL when going from L to R registers or viceversa

---
name:            test_l_to_r
body:             |
  bb.0.entry:
    liveins: $x2, $x4, $x6, $x8

    ; CHECK-LABEL: name: test_l_to_r
    ; CHECK: liveins: $x2, $x4, $x6, $x8
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $l8 = VLT_8_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $x0 = VSEL_16 killed renamable $x6, killed renamable $x8, killed renamable $r16, implicit $crbf8conf, implicit $crfp8conf
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $x0
    renamable $l8 = VLT_8_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit killed $vaddsign1
    renamable $x0 = VSEL_16 killed renamable $x6, killed renamable $x8, killed renamable $r16, implicit $crbf8conf, implicit $crfp8conf
    RET implicit $lr
    DelayedSchedBarrier implicit $x0
...

---
name:            test_l_to_l
body:             |
  bb.0.entry:
    liveins: $x2, $x4, $x6, $x8

    ; CHECK-LABEL: name: test_l_to_l
    ; CHECK: liveins: $x2, $x4, $x6, $x8
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $l0 = VLT_8_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
    ; CHECK-NEXT: renamable $x0 = VSEL_8 killed renamable $x6, killed renamable $x8, killed renamable $l0, implicit $crbf8conf, implicit $crfp8conf
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $x0
    renamable $l0 = VLT_8_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit killed $vaddsign1
    renamable $x0 = VSEL_8 killed renamable $x6, killed renamable $x8, killed renamable $l0, implicit $crbf8conf, implicit $crfp8conf
    RET implicit $lr
    DelayedSchedBarrier implicit $x0
...

---
name:            test_r_to_r
body:             |
  bb.0.entry:
    liveins: $x2, $x4, $x6, $x8

    ; CHECK-LABEL: name: test_r_to_r
    ; CHECK: liveins: $x2, $x4, $x6, $x8
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r16 = VLT_16_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
    ; CHECK-NEXT: renamable $x0 = VSEL_16 killed renamable $x6, killed renamable $x8, killed renamable $r16, implicit $crbf8conf, implicit $crfp8conf
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $x0
    renamable $r16 = VLT_16_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit killed $vaddsign1
    renamable $x0 = VSEL_16 killed renamable $x6, killed renamable $x8, killed renamable $r16, implicit $crbf8conf, implicit $crfp8conf
    RET implicit $lr
    DelayedSchedBarrier implicit $x0
...

---
name:            test_r_to_l
body:             |
  bb.0.entry:
    liveins: $x2, $x4, $x6, $x8

    ; CHECK-LABEL: name: test_r_to_l
    ; CHECK: liveins: $x2, $x4, $x6, $x8
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: renamable $r16 = VLT_16_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
    ; CHECK-NEXT: renamable $r17 = MOVA 0
    ; CHECK-NEXT: renamable $x0 = VSEL_8 killed renamable $x6, killed renamable $x8, killed renamable $l8, implicit $crbf8conf, implicit $crfp8conf
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier implicit killed $x0
    renamable $r17 = MOV_RLC_imm11_pseudo 0
    renamable $r16 = VLT_16_vaddSign1 killed renamable $x2, killed renamable $x4, implicit $crbf8conf, implicit $crfp8conf, implicit killed $vaddsign1
    renamable $x0 = VSEL_8 killed renamable $x6, killed renamable $x8, killed renamable $l8, implicit $crbf8conf, implicit $crfp8conf
    RET implicit $lr
    DelayedSchedBarrier implicit $x0
...
