# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass postrapseudos -verify-machineinstrs -o - %s | FileCheck %s

# Verify AIE2PSInstrInfo.cpp: copyPhysReg()

---
name:     test_copy_r
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r
    ; CHECK: $r0 = MOV_OR_pseudo $r1
  $r0 = COPY $r1
...

---
name:     test_copy_p
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_p
    ; CHECK: $p0 = MOV_scalar_pseudo $p1
  $p0 = COPY $p1
...

---
name:     test_copy_r_to_p
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r_to_p
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_scl $p1
    ; CHECK-NEXT: $p0 = MOV_scalar_pseudo $r1
  $r0 = COPY $p1
  $p0 = COPY $r1
...

---
name:     test_copy_sc
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_sc
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_r_sc $crsat
    ; CHECK-NEXT: $crrnd = MOV_alu_mv_mv_mv_sc_r $r1
  $r0 = COPY $crsat
  $crrnd = COPY $r1
...

---
name:     test_copy_d
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_d
    ; CHECK: $m1 = MOV_scalar_pseudo $m2
    ; CHECK-NEXT: $dn1 = MOV_scalar_pseudo $dn2
    ; CHECK-NEXT: $dj1 = MOV_scalar_pseudo $dj2
    ; CHECK-NEXT: $dc1 = MOV_scalar_pseudo $dc2
  $d1 = COPY $d2
...

---
name:     test_copy_ds
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ds
    ; CHECK: $m1 = MOV_scalar_pseudo $m2
    ; CHECK-NEXT: $dn1 = MOV_scalar_pseudo $dn2
    ; CHECK-NEXT: $dj1 = MOV_scalar_pseudo $dj2
    ; CHECK-NEXT: $dc1 = MOV_scalar_pseudo $dc2
    ; CHECK-NEXT: $m5 = MOV_scalar_pseudo $m6
    ; CHECK-NEXT: $dn5 = MOV_scalar_pseudo $dn6
    ; CHECK-NEXT: $dj5 = MOV_scalar_pseudo $dj6
    ; CHECK-NEXT: $dc5 = MOV_scalar_pseudo $dc6
  $d1_3d = COPY $d2_3d
...

---
name:            test_copy_l
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_l
    ; CHECK: $r2 = MOV_OR_pseudo $r4
    ; CHECK-NEXT: $r3 = MOV_OR_pseudo $r5
  $l1 = COPY $l2
...

---
name:            test_copy_l_to_e
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_l_to_e
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_r_to_el $r2
    ; CHECK-NEXT: $eh0 = MOV_alu_mv_mv_mv_e_mv_r_to_eh $r3
  $e0 = COPY $l1
...

---
name:            test_copy_e_to_l
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_e_to_l
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_e_mv_el_to_r $el1
    ; CHECK-NEXT: $r1 = MOV_alu_mv_mv_mv_e_mv_eh_to_r $eh1
  $l0 = COPY $e1
...

---
name:            test_copy_l_to_g
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_l_to_g
    ; CHECK: $gl0 = MOV_alu_mv_mv_mv_g_mv_r_to_gl $r2
    ; CHECK-NEXT: $gh0 = MOV_alu_mv_mv_mv_g_mv_r_to_gh $r3
    ; CHECK-NEXT: $r0 = MOV_alu_mv_mv_mv_g_mv_gl_to_r $gl1
    ; CHECK-NEXT: $r1 = MOV_alu_mv_mv_mv_g_mv_gh_to_r $gh1
  $g0 = COPY $l1
  $l0 = COPY $g1
...

---
name:            test_copy_exp_to_exp
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_exp_to_exp
    ; CHECK: $e0 = VMOV_alu_mv_mv_mv_ee $e1
    ; CHECK-NEXT: $e5 = VMOV_alu_mv_mv_mv_ee $e4
  $e0 = COPY $e1
  $e5 = COPY $e4
...

---
name:            test_copy_eh_to_eh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eh_to_eh
    ; CHECK: $eh0 = MOV_alu_mv_mv_mv_e_mv_eh_to_eh $eh1
  $eh0 = COPY $eh1
...

---
name:            test_copy_el_to_el
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_el_to_el
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_el_to_el $el1
  $el0 = COPY $el1
...

---
name:            test_copy_eh_to_el
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eh_to_el
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_eh_to_el $eh1
  $el0 = COPY $eh1
...

---
name:            test_copy_el_to_eh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_el_to_eh
    ; CHECK: $eh0 = MOV_alu_mv_mv_mv_e_mv_el_to_eh $el1
  $eh0 = COPY $el1
...

---
name:            test_copy_eh_to_r
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eh_to_r
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_e_mv_eh_to_r $eh1
  $r0 = COPY $eh1
...

---
name:            test_copy_r_to_eh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r_to_eh
    ; CHECK: $eh0 = MOV_alu_mv_mv_mv_e_mv_r_to_eh $r1
  $eh0 = COPY $r1
...

---
name:            test_copy_el_to_r
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_el_to_r
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_e_mv_el_to_r $el1
  $r0 = COPY $el1
...

---
name:            test_copy_r_to_el
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r_to_el
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_r_to_el $r1
  $el0 = COPY $r1
...

---
name:            test_copy_gh_to_gh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_gh_to_gh
    ; CHECK: $gh0 = MOV_alu_mv_mv_mv_g_mv_gh_to_gh $gh1
  $gh0 = COPY $gh1
...

---
name:            test_copy_gl_to_gl
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_gl_to_gl
    ; CHECK: $gl0 = MOV_alu_mv_mv_mv_g_mv_gl_to_gl $gl1
  $gl0 = COPY $gl1
...

---
name:            test_copy_gh_to_gl
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_gh_to_gl
    ; CHECK: $gl0 = MOV_alu_mv_mv_mv_g_mv_gh_to_gl $gh1
  $gl0 = COPY $gh1
...

---
name:            test_copy_gl_to_gh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_gl_to_gh
    ; CHECK: $gh0 = MOV_alu_mv_mv_mv_g_mv_gl_to_gh $gl1
  $gh0 = COPY $gl1
...

---
name:            test_copy_gh_to_r
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_gh_to_r
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_g_mv_gh_to_r $gh1
  $r0 = COPY $gh1
...

---
name:            test_copy_r_to_gh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r_to_gh
    ; CHECK: $gh0 = MOV_alu_mv_mv_mv_g_mv_r_to_gh $r1
  $gh0 = COPY $r1
...

---
name:            test_copy_gl_to_r
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_gl_to_r
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_g_mv_gl_to_r $gl1
  $r0 = COPY $gl1
...

---
name:            test_copy_r_to_gl
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r_to_gl
    ; CHECK: $gl0 = MOV_alu_mv_mv_mv_g_mv_r_to_gl $r1
  $gl0 = COPY $r1
...

---
name:     test_copy_f
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_f
    ; CHECK: $fh0 = VMOV_alu_mv_mv_mv_f $fh1
    ; CHECK-NEXT: $fl1 = VMOV_alu_mv_mv_mv_f $fh2
    ; CHECK-NEXT: $fh11 = VMOV_alu_mv_mv_mv_f $fl10
  $fh0 = COPY $fh1
  $fl1 = COPY $fh2
  $fh11 = COPY $fl10
...

---
name:     test_copy_w
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_w
    ; CHECK: $wh0 = VMOV_alu_mv_mv_mv_w $wh1
    ; CHECK-NEXT: $wl1 = VMOV_alu_mv_mv_mv_w $wh2
    ; CHECK-NEXT: $wh11 = VMOV_alu_mv_mv_mv_w $wl10
  $wh0 = COPY $wh1
  $wl1 = COPY $wh2
  $wh11 = COPY $wl10
...

---
name:             test_copy_x
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_x
    ; CHECK: $x1 = VMOV_alu_mv_mv_mv_x $x4
    ; CHECK-NEXT: $x2 = VMOV_alu_mv_mv_mv_x $x3
    ; CHECK-NEXT: $x10 = VMOV_alu_mv_mv_mv_x $x8
    ; CHECK-NEXT: $x3 = VMOV_alu_mv_mv_mv_x $bmll0
    ; CHECK-NEXT: $x4 = VMOV_alu_mv_mv_mv_x $bmhh3
    ; CHECK-NEXT: $bmhh2 = VMOV_alu_mv_mv_mv_x $x1
    ; CHECK-NEXT: $bmll1 = VMOV_alu_mv_mv_mv_x $x2
    ; CHECK-NEXT: $bmll3 = VMOV_alu_mv_mv_mv_x $bmll0
    ; CHECK-NEXT: $bmhh4 = VMOV_alu_mv_mv_mv_x $bmhh3
  $x1 = COPY $x4
  $x2 = COPY $x3
  $x10 = COPY $x8
  $x3 = COPY $bmll0
  $x4 = COPY $bmhh3
  $bmhh2 = COPY $x1
  $bmll1 = COPY $x2
  $bmll3 = COPY $bmll0
  $bmhh4 = COPY $bmhh3
...

---
name:             test_copy_cml
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_cml
    ; CHECK: $cml1 = VMOV_alu_mv_mv_mv_cm $cml4
    ; CHECK-NEXT: $cml2 = VMOV_alu_mv_mv_mv_cm $cml3
  $cml1 = COPY $cml4
  $cml2 = COPY $cml3
...

---
name:             test_copy_cm
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_cm
    ; CHECK: $cml1 = VMOV_alu_mv_mv_mv_cm $cml0
    ; CHECK-NEXT: $cmh1 = VMOV_alu_mv_mv_mv_cm $cmh0
    ; CHECK-NEXT: $cmh3 = VMOV_alu_mv_mv_mv_cm $cml2
    ; CHECK-NEXT: $cml3 = VMOV_alu_mv_mv_mv_cm $cmh2
  $cml1 = COPY $cml0
  $cmh1 = COPY $cmh0
  $cmh3 = COPY $cml2
  $cml3 = COPY $cmh2
...

---
name:             test_copy_dm
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_dm
    ; CHECK: $dm1 = VMOV_D_vmov $dm2
    ; CHECK-NEXT: $dm2 = VMOV_D_vmov $dm3
  $dm1 = COPY $dm2
  $dm2 = COPY $dm3
...

---
name:            test_copy_y
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_y
    ; CHECK: $x4 = VMOV_alu_mv_mv_mv_x $x8
    ; CHECK-NEXT: $x5 = VMOV_alu_mv_mv_mv_x $x9
    ; CHECK-NEXT: $x6 = VMOV_alu_mv_mv_mv_x $x10
    ; CHECK-NEXT: $x7 = VMOV_alu_mv_mv_mv_x $x11
  $y2 = COPY $y4
  $y3 = COPY $y5
...

---
name:             test_copy_lf0
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_lf0
    ; CHECK: $lfl1 = VMOV_alu_mv_mv_mv_x $x4
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_mv_x $lfl1
    ; CHECK-NEXT: $x10 = VMOV_alu_mv_mv_mv_x $lfh1
    ; CHECK-NEXT: $bmhh2 = VMOV_alu_mv_mv_mv_x $lfl0
    ; CHECK-NEXT: $lfl0 = VMOV_alu_mv_mv_mv_x $bmhh2
    ; CHECK-NEXT: $x10 = VMOV_alu_mv_mv_mv_x $lfe
    ; CHECK-NEXT: $bmhh2 = VMOV_alu_mv_mv_mv_x $lfe
    ; CHECK-NEXT: $lfe = VMOV_alu_mv_mv_mv_x $bmhh2
    ; CHECK-NEXT: $lfe = VMOV_alu_mv_mv_mv_x $lfl1
  $lfl1 = COPY $x4
  $lfh0 = COPY $lfl1
  $x10 = COPY $lfh1
  $bmhh2 = COPY $lfl0
  $lfl0 = COPY $bmhh2
  $x10 = COPY $lfe
  $bmhh2 = COPY $lfe
  $lfe = COPY $bmhh2
  $lfe = COPY $lfl1
...

---
name:            test_copy_lf
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_lf
    ; CHECK: $bmll1 = VMOV_alu_mv_mv_mv_x $lfl0
    ; CHECK-NEXT: $bmlh1 = VMOV_alu_mv_mv_mv_x $lfh0
    ; CHECK-NEXT: $lfl0 = VMOV_alu_mv_mv_mv_x $bmll1
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_mv_x $bmlh1
    ; CHECK-NEXT: $lfl1 = VMOV_alu_mv_mv_mv_x $lfl0
    ; CHECK-NEXT: $lfh1 = VMOV_alu_mv_mv_mv_x $lfh0
    ; CHECK-NEXT: $lfl0 = VMOV_alu_mv_mv_mv_x $x6
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_mv_x $x7
    ; CHECK-NEXT: $x6 = VMOV_alu_mv_mv_mv_x $lfl0
    ; CHECK-NEXT: $x7 = VMOV_alu_mv_mv_mv_x $lfh0
  $cml1 = COPY $lf0
  $lf0 = COPY $cml1
  $lf1 = COPY $lf0
  $lf0 = COPY $y3
  $y3 = COPY $lf0
...

---
name:            test_copy_y_cml
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_y_cml
    ; CHECK: $x4 = VMOV_alu_mv_mv_mv_x $bmll0
    ; CHECK-NEXT: $x5 = VMOV_alu_mv_mv_mv_x $bmlh0
    ; CHECK-NEXT: $bmll1 = VMOV_alu_mv_mv_mv_x $x10
    ; CHECK-NEXT: $bmlh1 = VMOV_alu_mv_mv_mv_x $x11
  $y2  = COPY $cml0
  $cml1 = COPY $y5
...

---
name:            test_copy_ff
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ff
    ; CHECK: $f0 = VMOV_alu_mv_mv_mv_ff $f1
    ; CHECK-NEXT: $f3 = VMOV_alu_mv_mv_mv_ff $f2
    ; CHECK-NEXT: $f4 = VMOV_alu_mv_mv_mv_ff $f6
    ; CHECK-NEXT: $f5 = VMOV_alu_mv_mv_mv_ff $f7
  $f0 = COPY $f1
  $f3 = COPY $f2
  $f4 = COPY $f6
  $f5 = COPY $f7
...

---
name:            test_copy_gg
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_gg
    ; CHECK: $g0 = VMOV_alu_mv_mv_mv_gg $g1
    ; CHECK-NEXT: $g3 = VMOV_alu_mv_mv_mv_gg $g2
    ; CHECK-NEXT: $g4 = VMOV_alu_mv_mv_mv_gg $g6
    ; CHECK-NEXT: $g5 = VMOV_alu_mv_mv_mv_gg $g7
  $g0 = COPY $g1
  $g3 = COPY $g2
  $g4 = COPY $g6
  $g5 = COPY $g7
...

---
name:            test_copy_ew
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ew
    ; CHECK: $ewl0 = VMOV_alu_mv_mv_mv_egw $ewl1
    ; CHECK-NEXT: $ewh1 = VMOV_alu_mv_mv_mv_egw $ewh2
    ; CHECK-NEXT: $ewh3 = VMOV_alu_mv_mv_mv_egw $ewl4
    ; CHECK-NEXT: $ewl5 = VMOV_alu_mv_mv_mv_egw $ewh6
  $ewl0 = COPY $ewl1
  $ewh1 = COPY $ewh2
  $ewh3 = COPY $ewl4
  $ewl5 = COPY $ewh6
...

---
name:            test_copy_ex
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ex
    ; CHECK: $ex0 = VMOV_alu_mv_mv_mv_egx $ex1
    ; CHECK-NEXT: $ex2 = VMOV_alu_mv_mv_mv_egx $ex3
  $ex0 = COPY $ex1
  $ex2 = COPY $ex3
...

---
name:            test_copy_ey
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ey
    ; CHECK: $ex0 = VMOV_alu_mv_mv_mv_egx $ex2
    ; CHECK-NEXT: $ex1 = VMOV_alu_mv_mv_mv_egx $ex3
    ; CHECK-NEXT: $ex10 = VMOV_alu_mv_mv_mv_egx $ex8
    ; CHECK-NEXT: $ex11 = VMOV_alu_mv_mv_mv_egx $ex9
  $ey0 = COPY $ey1
  $ey5 = COPY $ey4
...

---
name:            test_copy_few
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_few
    ; CHECK: $fewl0 = VMOV_alu_mv_mv_mv_few $fewl1
    ; CHECK-NEXT: $fewh1 = VMOV_alu_mv_mv_mv_few $fewh2
    ; CHECK-NEXT: $fewh3 = VMOV_alu_mv_mv_mv_few $fewl4
    ; CHECK-NEXT: $fewl5 = VMOV_alu_mv_mv_mv_few $fewh6
  $fewl0 = COPY $fewl1
  $fewh1 = COPY $fewh2
  $fewh3 = COPY $fewl4
  $fewl5 = COPY $fewh6
...

---
name:            test_copy_fex
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_fex
    ; CHECK: $fex0 = VMOV_alu_mv_mv_mv_fex $fex1
    ; CHECK-NEXT: $fex2 = VMOV_alu_mv_mv_mv_fex $fex3
  $fex0 = COPY $fex1
  $fex2 = COPY $fex3
...

---
name:            test_copy_fey
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_fey
    ; CHECK: $fex0 = VMOV_alu_mv_mv_mv_fex $fex2
    ; CHECK-NEXT: $fex1 = VMOV_alu_mv_mv_mv_fex $fex3
    ; CHECK-NEXT: $fex10 = VMOV_alu_mv_mv_mv_fex $fex8
    ; CHECK-NEXT: $fex11 = VMOV_alu_mv_mv_mv_fex $fex9
  $fey0 = COPY $fey1
  $fey5 = COPY $fey4
...

---
name:            test_copy_eg
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eg
    ; CHECK: $egl1 = VMOV_alu_mv_mv_mv_eg $egh0
    ; CHECK-NEXT: $egh1 = VMOV_alu_mv_mv_mv_eg $egl0
    ; CHECK-NEXT: $egh2 = VMOV_alu_mv_mv_mv_eg $egh3
    ; CHECK-NEXT: $egl2 = VMOV_alu_mv_mv_mv_eg $egl3
  $egl1 = COPY $egh0
  $egh1 = COPY $egl0
  $egh2 = COPY $egh3
  $egl2 = COPY $egl3
...

---
name:            test_copy_eg2
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eg2
    ; CHECK: $eg1 = VMOV_alu_mv_mv_mv_eg2 $eg0
  $eg1 = COPY $eg0
...

---
name:            test_copy_eg2_w
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eg2_w
    ; CHECK: $eg0 = VMOV_alu_mv_mv_mv_w_to_eg2 $wh0
    ; CHECK-NEXT: $wl0 = VMOV_alu_mv_mv_mv_eg2_to_w $eg1
  $eg0 = COPY $wh0
  $wl0 = COPY $eg1
...

---
name:            test_copy_f_l
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_f_l
    ; CHECK: $l0 = VMOV_alu_mv_mv_mv_f_to_l $fl0
    ; CHECK-NEXT: $l1 = VMOV_alu_mv_mv_mv_f_to_l $fh1
    ; CHECK-NEXT: $fl2 = VMOV_alu_mv_mv_mv_l_to_f $l2
    ; CHECK-NEXT: $fh3 = VMOV_alu_mv_mv_mv_l_to_f $l3
  $l0 = COPY $fl0
  $l1 = COPY $fh1
  $fl2 = COPY $l2
  $fh3 = COPY $l3
...

---
name:            test_copy_sf_to_lf
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_sf_to_lf
    ; CHECK: $lfl0 = VMOV_alu_mv_mv_mv_x $sfl
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_mv_x $sfh
  $lf0 = COPY $sf
...

---
name:            test_copy_vec_to_fifo
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_vec_to_fifo
    ; CHECK: $lfl0 = VMOV_alu_mv_mv_mv_x $x0
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_mv_x $x1
  $lf0 = COPY $y0
...

---
name:            test_copy_fifo_to_vec
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_fifo_to_vec
    ; CHECK: $x0 = VMOV_alu_mv_mv_mv_x $lfl0
    ; CHECK-NEXT: $x1 = VMOV_alu_mv_mv_mv_x $lfh0
  $y0 = COPY $lf0
...

---
name:            test_copy_acc_to_fifo
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_acc_to_fifo
    ; CHECK: $lfl0 = VMOV_alu_mv_mv_mv_x $bmll0
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_mv_x $bmlh0
  $lf0 = COPY $cml0
...

---
name:            test_copy_fifo_to_acc
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_fifo_to_acc
    ; CHECK: $bmll0 = VMOV_alu_mv_mv_mv_x $lfl0
    ; CHECK-NEXT: $bmlh0 = VMOV_alu_mv_mv_mv_x $lfh0
  $cml0 = COPY $lf0
...

---
name:            test_copy_plfr
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_plfr
    ; CHECK: $lfl1 = VMOV_alu_mv_mv_mv_x $lfl0
    ; CHECK-NEXT: $lfh1 = VMOV_alu_mv_mv_mv_x $lfh0
    ; CHECK-NEXT: $r25 = MOV_OR_pseudo $r24
    ; CHECK-NEXT: $p1 = MOV_scalar_pseudo $p0
  $plfr1 = COPY $plfr0
...
