# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc --march=aie2ps -run-pass=regallocfast --run-pass=prologepilog %s -o - | FileCheck %s

---
name:            test_eP
alignment:       64
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1

    ; CHECK-LABEL: name: test_eP
    ; CHECK: liveins: $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $lr, -60, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: ST_dms_sts_scalar_spill $p1, -64, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: $p1 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $lr = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p1
    %0:ep = COPY $p1
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...
---
name:            test_eBMLL
alignment:       64
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; CHECK-LABEL: name: test_eBMLL
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmll0, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: $bmll0 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $lr = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $bmll0
    %0:ebmll = COPY $bmll0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...
---
name:            test_mWm
alignment:       64
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0

    ; CHECK-LABEL: name: test_mWm
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $lr, -32, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: VST_dmw_sts_w_spill $wl0, -64, implicit $sp :: (store (s256) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: $wl0 = VLDA_dmw_lda_w_spill -64, implicit $sp :: (load (s256) from %stack.0)
    ; CHECK-NEXT: $lr = LDA_dms_lda_scalar_spill -32, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $wl0
    %0:mwm = COPY $wl0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...
---
name:            test_mXa
alignment:       64
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $e0

    ; CHECK-LABEL: name: test_mXa
    ; CHECK: liveins: $e0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: renamable $x0 = COPY killed $e0
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x0, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: $x0 = VLDA_dmx_lda_x_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $lr = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $x0
    %0:mxa = COPY $e0
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...
---
name:            test_mix
alignment:       64
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p1, $dc5, $bmll0, $wl0, $e0

    ; CHECK-LABEL: name: test_mix
    ; CHECK: liveins: $p1, $dc5, $bmll0, $wl0, $e0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 192, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $lr, -24, implicit $sp :: (store (s32) into %stack.5)
    ; CHECK-NEXT: ST_dms_sts_scalar_spill $p1, -32, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmll0, -192, implicit $sp :: (store (s512) into %stack.1)
    ; CHECK-NEXT: VST_dmw_sts_w_spill $wl0, -64, implicit $sp :: (store (s256) into %stack.2)
    ; CHECK-NEXT: renamable $x0 = COPY killed $e0
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x0, -128, implicit $sp :: (store (s512) into %stack.3)
    ; CHECK-NEXT: ST_dms_sts_scalar_spill $dc5, -28, implicit $sp :: (store (s32) into %stack.4)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: $dc5 = LDA_dms_lda_scalar_spill -28, implicit $sp :: (load (s32) from %stack.4)
    ; CHECK-NEXT: $x2 = VLDA_dmx_lda_x_spill -128, implicit $sp :: (load (s512) from %stack.3)
    ; CHECK-NEXT: $wl0 = VLDA_dmw_lda_w_spill -64, implicit $sp :: (load (s256) from %stack.2)
    ; CHECK-NEXT: $bmll0 = VLDA_dmx_lda_bm_spill -192, implicit $sp :: (load (s512) from %stack.1)
    ; CHECK-NEXT: $p1 = LDA_dms_lda_scalar_spill -32, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $lr = LDA_dms_lda_scalar_spill -24, implicit $sp :: (load (s32) from %stack.5)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -192, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p1, implicit killed renamable $bmll0, implicit killed renamable $wl0, implicit killed renamable $x2, implicit killed renamable $dc5
    %0:ep = COPY $p1
    %1:ebmll = COPY $bmll0
    %2:mwm = COPY $wl0
    %3:mxa = COPY $e0
    %4:edc = COPY $dc5
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    PseudoRET implicit $lr, implicit %0, implicit %1, implicit %2, implicit %3, implicit %4
...
