# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=amdgcn -run-pass=amdgpu-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: inttoptr_constant_p0_s64
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: inttoptr_constant_p0_s64
    ; CHECK: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
    ; CHECK-NEXT: $vgpr0_vgpr1 = COPY [[C]](p0)
    %0:_(s64) = G_CONSTANT i64 0
    %1:_(p0) = G_INTTOPTR %0
    $vgpr0_vgpr1 = COPY %1
...

---
name: inttoptr_constant_nonintegral
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: inttoptr_constant_nonintegral
    ; CHECK: [[C:%[0-9]+]]:_(s160) = G_CONSTANT i160 0
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p7) = G_INTTOPTR [[C]](s160)
    ; CHECK-NEXT: SI_RETURN implicit [[INTTOPTR]](p7)
    %0:_(s160) = G_CONSTANT i160 0
    %1:_(p7) = G_INTTOPTR %0
    SI_RETURN implicit %1
...


---
name: inttoptr_constant_trunc_p2_s64
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: inttoptr_constant_trunc_p2_s64
    ; CHECK: [[C:%[0-9]+]]:_(p2) = G_CONSTANT i32 0
    ; CHECK-NEXT: $vgpr0 = COPY [[C]](p2)
    %0:_(s64) = G_CONSTANT i64 0
    %1:_(s32) = G_TRUNC %0
    %2:_(p2) = G_INTTOPTR %1
    $vgpr0 = COPY %2
...
