# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1010 -run-pass=amdgpu-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck -check-prefix=GCN %s

---
name: sext_trunc_s32_s16_s32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0

    ; GCN-LABEL: name: sext_trunc_s32_s16_s32
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(s32) = COPY $vgpr0
    ; GCN-NEXT: %assert:_(s32) = G_ASSERT_SEXT %var, 16
    ; GCN-NEXT: $vgpr0 = COPY %assert(s32)
    %var:_(s32) = COPY $vgpr0
    %assert:_(s32) = G_ASSERT_SEXT %var, 16
    %trunc:_(s16) = G_TRUNC %assert(s32)
    %sext:_(s32) = G_SEXT %trunc(s16)
    $vgpr0 = COPY %sext(s32)
...

---
name: sext_trunc_s32_s16_s32_unknown_high_bits
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0

    ; GCN-LABEL: name: sext_trunc_s32_s16_s32_unknown_high_bits
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(s32) = COPY $vgpr0
    ; GCN-NEXT: %trunc:_(s16) = G_TRUNC %var(s32)
    ; GCN-NEXT: %sext:_(s32) = G_SEXT %trunc(s16)
    ; GCN-NEXT: $vgpr0 = COPY %sext(s32)
    %var:_(s32) = COPY $vgpr0
    %trunc:_(s16) = G_TRUNC %var(s32)
    %sext:_(s32) = G_SEXT %trunc(s16)
    $vgpr0 = COPY %sext(s32)
...

---
name: sext_trunc_s64_s16_s32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GCN-LABEL: name: sext_trunc_s64_s16_s32
    ; GCN: liveins: $vgpr0_vgpr1
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(s64) = COPY $vgpr0_vgpr1
    ; GCN-NEXT: %assert:_(s64) = G_ASSERT_SEXT %var, 32
    ; GCN-NEXT: %trunc:_(s16) = G_TRUNC %assert(s64)
    ; GCN-NEXT: %sext:_(s32) = G_SEXT %trunc(s16)
    ; GCN-NEXT: $vgpr0 = COPY %sext(s32)
    %var:_(s64) = COPY $vgpr0_vgpr1
    %assert:_(s64) = G_ASSERT_SEXT %var, 32
    %trunc:_(s16) = G_TRUNC %assert(s64)
    %sext:_(s32) = G_SEXT %trunc(s16)
    $vgpr0 = COPY %sext(s32)
...

---
name: sext_trunc_s32_s16_s64
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0

    ; GCN-LABEL: name: sext_trunc_s32_s16_s64
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(s32) = COPY $vgpr0
    ; GCN-NEXT: %assert:_(s32) = G_ASSERT_SEXT %var, 16
    ; GCN-NEXT: %trunc:_(s16) = G_TRUNC %assert(s32)
    ; GCN-NEXT: %sext:_(s64) = G_SEXT %trunc(s16)
    ; GCN-NEXT: $vgpr0_vgpr1 = COPY %sext(s64)
    %var:_(s32) = COPY $vgpr0
    %assert:_(s32) = G_ASSERT_SEXT %var, 16
    %trunc:_(s16) = G_TRUNC %assert(s32)
    %sext:_(s64) = G_SEXT %trunc(s16)
    $vgpr0_vgpr1 = COPY %sext(s64)
...

---
name: sext_trunc_v2s32_v2s16_v2s32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GCN-LABEL: name: sext_trunc_v2s32_v2s16_v2s32
    ; GCN: liveins: $vgpr0_vgpr1
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(<2 x s32>) = COPY $vgpr0_vgpr1
    ; GCN-NEXT: %assert:_(<2 x s32>) = G_ASSERT_SEXT %var, 16
    ; GCN-NEXT: $vgpr0_vgpr1 = COPY %assert(<2 x s32>)
    %var:_(<2 x s32>) = COPY $vgpr0_vgpr1
    %assert:_(<2 x s32>) = G_ASSERT_SEXT %var, 16
    %trunc:_(<2 x s16>) = G_TRUNC %assert(<2 x s32>)
    %sext:_(<2 x s32>) = G_SEXT %trunc(<2 x s16>)
    $vgpr0_vgpr1 = COPY %sext(<2 x s32>)
...

---
name: sext_trunc_v2s32_v2s16_v2s32_unknown_high_bits
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GCN-LABEL: name: sext_trunc_v2s32_v2s16_v2s32_unknown_high_bits
    ; GCN: liveins: $vgpr0_vgpr1
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(<2 x s32>) = COPY $vgpr0_vgpr1
    ; GCN-NEXT: %trunc:_(<2 x s16>) = G_TRUNC %var(<2 x s32>)
    ; GCN-NEXT: %sext:_(<2 x s32>) = G_SEXT %trunc(<2 x s16>)
    ; GCN-NEXT: $vgpr0_vgpr1 = COPY %sext(<2 x s32>)
    %var:_(<2 x s32>) = COPY $vgpr0_vgpr1
    %trunc:_(<2 x s16>) = G_TRUNC %var(<2 x s32>)
    %sext:_(<2 x s32>) = G_SEXT %trunc(<2 x s16>)
    $vgpr0_vgpr1 = COPY %sext(<2 x s32>)
...

---
name: sext_trunc_v2s64_v2s16_v2s32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3

    ; GCN-LABEL: name: sext_trunc_v2s64_v2s16_v2s32
    ; GCN: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GCN-NEXT: %assert:_(<2 x s64>) = G_ASSERT_SEXT %var, 32
    ; GCN-NEXT: %trunc:_(<2 x s16>) = G_TRUNC %assert(<2 x s64>)
    ; GCN-NEXT: %sext:_(<2 x s32>) = G_SEXT %trunc(<2 x s16>)
    ; GCN-NEXT: $vgpr0_vgpr1 = COPY %sext(<2 x s32>)
    %var:_(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    %assert:_(<2 x s64>) = G_ASSERT_SEXT %var, 32
    %trunc:_(<2 x s16>) = G_TRUNC %assert(<2 x s64>)
    %sext:_(<2 x s32>) = G_SEXT %trunc(<2 x s16>)
    $vgpr0_vgpr1 = COPY %sext(<2 x s32>)
...

---
name: sext_trunc_v2s32_v2s16_v2s64
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GCN-LABEL: name: sext_trunc_v2s32_v2s16_v2s64
    ; GCN: liveins: $vgpr0_vgpr1
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %var:_(<2 x s32>) = COPY $vgpr0_vgpr1
    ; GCN-NEXT: %assert:_(<2 x s32>) = G_ASSERT_SEXT %var, 16
    ; GCN-NEXT: %trunc:_(<2 x s16>) = G_TRUNC %assert(<2 x s32>)
    ; GCN-NEXT: %sext:_(<2 x s64>) = G_SEXT %trunc(<2 x s16>)
    ; GCN-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = COPY %sext(<2 x s64>)
    %var:_(<2 x s32>) = COPY $vgpr0_vgpr1
    %assert:_(<2 x s32>) = G_ASSERT_SEXT %var, 16
    %trunc:_(<2 x s16>) = G_TRUNC %assert(<2 x s32>)
    %sext:_(<2 x s64>) = G_SEXT %trunc(<2 x s16>)
    $vgpr0_vgpr1_vgpr2_vgpr3 = COPY %sext(<2 x s64>)
...
