; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --tool sed --version 5
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -mtriple=aie2ps -O2 -aie-enable-outer-loop-pipelining=false \
; RUN:     -stop-after=aie-outer-loop-pipeliner \
; RUN:     -o - %s | sed 's/^  //' | FileCheck %s
;
;   llvm/utils/update_test_checks.py --tool=sed \
;     llvm/test/CodeGen/AIE/aie2ps/outer-loop-pipeliner/outer-loop-pipelining-peel-first-liveout.ll
;
; Exit live-outs: values defined in the bottom block (pointer updates) are
; used after the loop exits. The exit PHIs must be correctly remapped through
; the epilogue block so that stage-1 values (ptr-updates from steady bottom)
; and stage-0 values (from epilogue clones) flow correctly to the exit.

declare void @llvm.set.loop.iterations.i32(i32)
declare i1 @llvm.loop.decrement.i32(i32)

define ptr @peel_first_liveout(ptr noalias %src, ptr noalias %dst, i32 %N, i32 %M) {
; CHECK-LABEL: define ptr @peel_first_liveout(
; CHECK-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]], i32 [[N:%.*]], i32 [[M:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[N]], 1
; CHECK-NEXT:    br i1 [[CMP]], label %[[OUTER_HEADER_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[OUTER_HEADER_PREHEADER]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER:.*]]
; CHECK:       [[OUTER_HEADER]]:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i32 [ [[N]], %[[OUTER_HEADER_PREHEADER]] ], [ [[LSR_IV_NEXT:%.*]], %[[OUTER_LATCH:.*]] ]
; CHECK-NEXT:    [[SRC_PTR_STEADY:%.*]] = phi ptr [ [[SRC_NEXT1_STEADY:%.*]], %[[OUTER_LATCH]] ], [ [[SRC]], %[[OUTER_HEADER_PREHEADER]] ]
; CHECK-NEXT:    [[DST_PTR_STEADY:%.*]] = phi ptr [ [[DST_NEXT2_STEADY:%.*]], %[[OUTER_LATCH]] ], [ [[DST]], %[[OUTER_HEADER_PREHEADER]] ]
; CHECK-NEXT:    [[VAL_STEADY:%.*]] = load i32, ptr [[SRC_PTR_STEADY]], align 4
; CHECK-NEXT:    call void @llvm.set.loop.iterations.i32(i32 [[M]])
; CHECK-NEXT:    br label %[[INNER_HEADER:.*]]
; CHECK:       [[INNER_HEADER]]:
; CHECK-NEXT:    [[ACC_STEADY:%.*]] = phi i32 [ 0, %[[OUTER_HEADER]] ], [ [[ACC_NEXT_STEADY:%.*]], %[[INNER_HEADER]] ]
; CHECK-NEXT:    [[ACC_NEXT_STEADY]] = add i32 [[ACC_STEADY]], [[VAL_STEADY]]
; CHECK-NEXT:    [[INNER_COND_FIRSTITER:%.*]] = call i1 @llvm.loop.decrement.i32(i32 1)
; CHECK-NEXT:    br i1 [[INNER_COND_FIRSTITER]], label %[[INNER_HEADER]], label %[[OUTER_LATCH]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[OUTER_LATCH]]:
; CHECK-NEXT:    store i32 [[ACC_NEXT_STEADY]], ptr [[DST_PTR_STEADY]], align 4
; CHECK-NEXT:    [[SRC_NEXT1_STEADY]] = getelementptr inbounds i8, ptr [[SRC_PTR_STEADY]], i32 4
; CHECK-NEXT:    [[DST_NEXT2_STEADY]] = getelementptr inbounds i8, ptr [[DST_PTR_STEADY]], i32 4
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i32 [[LSR_IV]], -1
; CHECK-NEXT:    [[OUTER_COND:%.*]] = icmp eq i32 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[OUTER_COND]], label %[[EXIT]], label %[[OUTER_HEADER]], !llvm.loop [[LOOP2:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[DST_FINAL:%.*]] = phi ptr [ [[DST]], %[[ENTRY]] ], [ [[DST_NEXT2_STEADY]], %[[OUTER_LATCH]] ]
; CHECK-NEXT:    ret ptr [[DST_FINAL]]
;
entry:
  %cmp = icmp sgt i32 %N, 1
  br i1 %cmp, label %outer.header, label %exit

outer.header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %outer.latch ]
  %src.ptr = phi ptr [ %src, %entry ], [ %src.next, %outer.latch ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %outer.latch ]
  %val = load i32, ptr %src.ptr, align 4
  call void @llvm.set.loop.iterations.i32(i32 %M)
  br label %inner.header

inner.header:
  %acc = phi i32 [ 0, %outer.header ], [ %acc.next, %inner.header ]
  %acc.next = add i32 %acc, %val
  %inner.cond = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %inner.cond, label %inner.header, label %outer.latch, !llvm.loop !1

outer.latch:
  %result = phi i32 [ %acc.next, %inner.header ]
  store i32 %result, ptr %dst.ptr, align 4
  %src.next = getelementptr inbounds i32, ptr %src.ptr, i32 1
  %dst.next = getelementptr inbounds i32, ptr %dst.ptr, i32 1
  %i.next = add nuw i32 %i, 1
  %outer.cond = icmp eq i32 %i.next, %N
  br i1 %outer.cond, label %exit, label %outer.header, !llvm.loop !0

exit:
  ; Live-out: the final dst pointer after the loop
  %dst.final = phi ptr [ %dst, %entry ], [ %dst.next, %outer.latch ]
  ret ptr %dst.final
}

!0 = distinct !{!0, !2, !3}
!1 = distinct !{!1, !2}
!2 = !{!"llvm.loop.mustprogress"}
!3 = !{!"llvm.loop.itercount.range", i32 2}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP2]] = distinct !{[[LOOP2]], [[META1]], [[META3:![0-9]+]]}
; CHECK: [[META3]] = !{!"llvm.loop.itercount.range", i32 2}
;.
