# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=aie-machine-alignment %s -verify-machineinstrs -o - | FileCheck %s
---

name:   pad-14
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pad-14
    ; CHECK: BUNDLE {
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   $p0 = PADDA_lda_ptr_inc_idx $p0, $m0
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT:   NOPXM
    ; CHECK-NEXT:   NOPV
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOPX
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   JL 32, implicit-def $lr
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    ; CHECK-NEXT: DelayedSchedBarrier csr_aie2
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   EVENT 0
    ; CHECK-NEXT:   NOPM
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   RET implicit $lr
    ; CHECK-NEXT: }
    ; CHECK-NEXT: DelayedSchedBarrier
  BUNDLE {
    $p0 = PADDA_lda_ptr_inc_idx $p0, $m0
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    JL 32, implicit-def $lr
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  BUNDLE {
    NOP
  }
  DelayedSchedBarrier csr_aie2
  BUNDLE {
    EVENT 0
  }
  BUNDLE {
    RET implicit $lr
  }
    DelayedSchedBarrier
...
