# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=postmisched %topdown-multi %s -verify-machineinstrs -o - | FileCheck %s
# The test is adding scheduler margin of 7-cycles afer the start block

---
name:            scheduler_margin_loopstart
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: scheduler_margin_loopstart
    ; CHECK: BUNDLE implicit-def $r1, implicit-def $r2, implicit-def $lc, implicit killed $p0, implicit killed $r0 {
    ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm killed renamable $p0, 0
    ; CHECK-NEXT:   renamable $r2 = MOVX_alu_cg 0
    ; CHECK-NEXT:   $lc = ADD_NC killed $r0, 0
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $ls = MOVXM_lng_cg 0
    ; CHECK-NEXT: $le = MOVXM_lng_cg <mcsymbol .L_1120>
    ; CHECK-NEXT: renamable $r3 = MOV_mv_cg 2
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
      renamable $r1 = LDA_dms_lda_idx_imm renamable $p0, 0
      renamable $r2 = MOVX_alu_cg 0
      renamable $r3 = MOV_mv_cg 2
      $lc = ADD_NC $r0, 0
      $ls = MOVXM_lng_cg 0
      $le = MOVXM_lng_cg <mcsymbol .L_1120>
...
