# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=aie-machine-alignment %s -verify-machineinstrs -o - | FileCheck %s
---
name:            zol_112bytes_constraint
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: zol_112bytes_constraint
    ; CHECK: BUNDLE implicit-def $r1, implicit-def $r2, implicit-def $lc, implicit $p0, implicit $r0 {
    ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm renamable $p0, 0
    ; CHECK-NEXT:   renamable $r2 = MOVX_alu_cg 0
    ; CHECK-NEXT:   $lc = MOV_mv_scl $r0
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def $ls {
    ; CHECK-NEXT:   $ls = MOVXM_lng_cg 0
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def $le {
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT:   $le = MOVXM_lng_cg <mcsymbol .L_1120>
    ; CHECK-NEXT:   NOPV
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def $r3 {
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT:   NOPX
    ; CHECK-NEXT:   renamable $r3 = MOV_mv_cg 2
    ; CHECK-NEXT:   NOPV
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT:   NOPXM
    ; CHECK-NEXT:   NOPV
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT:   NOPXM
    ; CHECK-NEXT:   NOPV
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT:   NOPXM
    ; CHECK-NEXT:   NOPV
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT:   NOPXM
    ; CHECK-NEXT:   NOPV
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOPA
    ; CHECK-NEXT:   NOPB
    ; CHECK-NEXT:   NOPXM
    ; CHECK-NEXT:   NOPS
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE {
    ; CHECK-NEXT:   NOP
    ; CHECK-NEXT: }
    BUNDLE implicit-def $r1, implicit-def $r2, implicit-def $lc, implicit $p0, implicit $r0 {
      renamable $r1 = LDA_dms_lda_idx_imm renamable $p0, 0
      renamable $r2 = MOVX_alu_cg 0
      $lc = MOV_mv_scl $r0
    }
    BUNDLE implicit-def $ls {
      $ls = MOVXM_lng_cg 0
    }
    BUNDLE implicit-def $le {
      $le = MOVXM_lng_cg <mcsymbol .L_1120>
    }
    BUNDLE implicit-def $r3 {
      renamable $r3 = MOV_mv_cg 2
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }

...
