# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5

# Note: Unit test for pre scheduler behavior changes when using composite register classes
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=machine-scheduler %s -o - | FileCheck %s


---
name:            machine-scheduler-stable-schedule-with-composite-ignore-reg-classes
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: machine-scheduler-stable-schedule-with-composite-ignore-reg-classes
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:erf2 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   undef [[VBCST_32_:%[0-9]+]].sub_512_lo:vec1024 = VBCST_32 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:eds = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[VBCST_32_:%[0-9]+]].sub_512_hi:vec1024 = COPY [[VBCST_32_]].sub_512_lo
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[MOV_PD_imm11_pseudo]].sub_dim_stride
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:eldfiforeg = COPY [[VBCST_32_]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]]:eps = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   undef [[COPY2:%[0-9]+]].sub_ptr:epsrfldf = COPY [[MOV_PD_imm11_pseudo1]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]].sub_fifo:epsrfldf = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]].sub_avail:epsrfldf = COPY [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   dead [[VLD_POP_576_3D_pseudo:%[0-9]+]]:vec576, dead [[COPY2:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY2:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY2:%[0-9]+]].sub_avail:epsrfldf, dead [[COPY1:%[0-9]+]].sub_dim_count:eds, dead [[COPY1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo [[COPY2]].sub_ptr, [[COPY2]].sub_fifo, [[COPY2]].sub_avail, [[COPY1]], implicit-def $srfifo_uf :: (load unknown-size, align 1)
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    %7:eps = MOV_PD_imm11_pseudo 0
    %9:erf2 = MOV_RLC_imm11_pseudo 0
    undef %8.sub_512_lo:vec1024 = VBCST_32 %9
    %8.sub_512_hi:vec1024 = COPY %8.sub_512_lo
    undef %14.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %12:eldfiforeg = COPY %8
    %14.sub_dim_stride:eds = COPY %14.sub_mod
    %14.sub_dim_size:eds = COPY %14.sub_mod
    %14.sub_dim_count:eds = COPY %14.sub_mod
    %14.sub_hi_dim_then_sub_dim_size:eds = COPY %14.sub_mod
    %14.sub_hi_dim_then_sub_dim_count:eds = COPY %14.sub_mod
    %14.sub_hi_dim_then_sub_dim_stride:eds = COPY %14.sub_dim_stride

  bb.1:
    successors: %bb.1(0x80000000)

    undef %22.sub_ptr:epsrfldf = COPY %7
    %22.sub_fifo:epsrfldf = COPY %12
    %22.sub_avail:epsrfldf = COPY %9
    %23:eds = COPY %14
    dead %13:vec576, dead %22.sub_ptr:epsrfldf, dead %22.sub_fifo:epsrfldf, dead %22.sub_avail:epsrfldf, dead %23.sub_dim_count:eds, dead %23.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo %22.sub_ptr, %22.sub_fifo, %22.sub_avail, %23, implicit-def $srfifo_uf :: (load unknown-size)
    PseudoJ_jump_imm %bb.1

...
