# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# CHECK lines automatically generated using update_encodings.py
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc %llcflags --filetype=obj -o %t
# RUN: llvm-objdump --triple=aie2ps -dr --no-print-imm-hex %t | FileCheck %s
# TODO: llc %llcflags --filetype=asm -o %t2
# TODO: llvm-mc -triple aie2ps -filetype=obj -o %t %t2
# TODO: llvm-objdump --triple=aie2ps -dr --no-print-imm-hex %t | FileCheck %s
#
# Test file automatically generated using generate_instr_info_test.py
# * Automatically generated file, do not edit! *

---
name:      test
alignment:    16
body:      |
  bb.0 (align 16):
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm3, $dm2, $x2, $ex3, $r14, implicit-def $srsparse_of
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm7, $dm3, $x11, $ex9, $r8, implicit-def $srsparse_of
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm2, $dm4, $x0, $ex7, $r10, implicit-def $srsparse_of
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm0, $dm7, $x5, $ex2, $r11, implicit-def $srsparse_of
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm6, $dm0, $x8, $ex0, $r15, implicit-def $srsparse_of
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm5, $dm6, $x6, $ex6, $r9, implicit-def $srsparse_of
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm4, $dm1, $x10, $ex11, $r13, implicit-def $srsparse_of
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm1, $dm5, $x1, $ex4, $r12, implicit-def $srsparse_of
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm3, $dm2, $x7, $ex5, $r14, implicit-def $srsparse_of
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm7, $dm3, $x4, $ex10, $r8, implicit-def $srsparse_of
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm2, $dm4, $x3, $ex1, $r10, implicit-def $srsparse_of
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_QX $dm0, $dm7, $x9, $ex8, $r11, implicit-def $srsparse_of

    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm0, $dm5, $x1, $ey0, $r14, implicit-def $srsparse_of
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm6, $dm2, $x11, $ey5, $r15, implicit-def $srsparse_of
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm7, $dm1, $x6, $ey2, $r13, implicit-def $srsparse_of
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm4, $dm0, $x5, $ey1, $r8, implicit-def $srsparse_of
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm2, $dm7, $x9, $ey3, $r11, implicit-def $srsparse_of
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm3, $dm3, $x7, $ey4, $r10, implicit-def $srsparse_of
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm5, $dm6, $x2, $ey0, $r12, implicit-def $srsparse_of
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm1, $dm4, $x0, $ey5, $r9, implicit-def $srsparse_of
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm0, $dm5, $x8, $ey2, $r14, implicit-def $srsparse_of
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm6, $dm2, $x3, $ey1, $r15, implicit-def $srsparse_of
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm7, $dm1, $x10, $ey3, $r13, implicit-def $srsparse_of
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_QY $dm4, $dm0, $x4, $ey4, $r8, implicit-def $srsparse_of

    $dm3 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm3, $dm6, $x4, $r12, $r12
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm1, $dm4, $x6, $r4, $r9
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm2, $dm3, $x2, $r2, $r14
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm4, $dm0, $x10, $r5, $r10
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm6, $dm2, $x9, $r11, $r11
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm0, $dm1, $x11, $r9, $r13
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm5, $dm5, $x1, $r7, $r8
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm7, $dm7, $x3, $r15, $r15
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm3, $dm6, $x5, $r10, $r12
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm1, $dm4, $x0, $r6, $r9
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm2, $dm3, $x8, $r8, $r14
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm4, $dm0, $x7, $r3, $r10
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm6, $dm2, $x4, $r1, $r11
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm0, $dm1, $x6, $r14, $r13
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm5, $dm5, $x2, $r0, $r8
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_R $dm7, $dm7, $x10, $r13, $r15

    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm7, $dm7, $x11, $x3, $r12
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm1, $dm1, $x6, $x6, $r8
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm6, $dm6, $x9, $x5, $r14
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm2, $dm2, $x5, $x2, $r13
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm4, $dm4, $x7, $x10, $r10
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm5, $dm5, $x3, $x1, $r11
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm3, $dm3, $x2, $x11, $r9
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm0, $dm0, $x0, $x4, $r15
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm7, $dm7, $x1, $x8, $r12
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm1, $dm1, $x8, $x9, $r8
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm6, $dm6, $x4, $x0, $r14
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_X $dm2, $dm2, $x10, $x7, $r13

    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm7, $dm1, $x3, $y0, $r14
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm2, $dm6, $x2, $y4, $r13
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm1, $dm4, $x9, $y2, $r9
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm4, $dm7, $x10, $y5, $r12
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm5, $dm5, $x1, $y1, $r10
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm6, $dm0, $x0, $y3, $r8
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm3, $dm3, $x4, $y0, $r15
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm0, $dm2, $x5, $y4, $r11
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm7, $dm1, $x6, $y2, $r14
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm2, $dm6, $x11, $y5, $r13
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm1, $dm4, $x7, $y1, $r9
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_X_Y $dm4, $dm7, $x8, $y3, $r12

    $dm4 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm4, $dm6, $y3, $ex8, $r10, implicit-def $srsparse_of
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm6, $dm1, $y2, $ex3, $r11, implicit-def $srsparse_of
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm3, $dm2, $y5, $ex0, $r8, implicit-def $srsparse_of
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm5, $dm5, $y0, $ex10, $r14, implicit-def $srsparse_of
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm7, $dm3, $y4, $ex7, $r9, implicit-def $srsparse_of
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm0, $dm0, $y1, $ex11, $r15, implicit-def $srsparse_of
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm1, $dm4, $y3, $ex5, $r13, implicit-def $srsparse_of
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm2, $dm7, $y2, $ex1, $r12, implicit-def $srsparse_of
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm4, $dm6, $y5, $ex2, $r10, implicit-def $srsparse_of
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm6, $dm1, $y0, $ex9, $r11, implicit-def $srsparse_of
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm3, $dm2, $y4, $ex6, $r8, implicit-def $srsparse_of
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_Y_QX $dm5, $dm5, $y1, $ex4, $r14, implicit-def $srsparse_of

    $dm7 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm7, $dm3, $y3, $r9, $r10
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm6, $dm0, $y2, $r7, $r12
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm0, $dm2, $y4, $r4, $r15
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm1, $dm1, $y1, $r11, $r8
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm4, $dm5, $y5, $r14, $r13
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm5, $dm7, $y0, $r0, $r14
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm3, $dm6, $y3, $r3, $r11
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm2, $dm4, $y2, $r6, $r9
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm7, $dm3, $y4, $r8, $r10
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm6, $dm0, $y1, $r15, $r12
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm0, $dm2, $y5, $r13, $r15
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm1, $dm1, $y0, $r2, $r8
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm4, $dm5, $y3, $r5, $r13
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm5, $dm7, $y2, $r12, $r14
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm3, $dm6, $y4, $r10, $r11
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_Y_R $dm2, $dm4, $y1, $r1, $r9

    $dm6 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm6, $dm1, $y5, $x8, $r10
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm4, $dm2, $y2, $x9, $r11
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm2, $dm7, $y0, $x3, $r9
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm0, $dm5, $y3, $x5, $r8
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm5, $dm6, $y1, $x11, $r13
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm1, $dm0, $y4, $x2, $r12
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm3, $dm4, $y5, $x1, $r15
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm7, $dm3, $y2, $x6, $r14
    $dm6 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm6, $dm1, $y0, $x10, $r10
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm4, $dm2, $y3, $x0, $r11
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm2, $dm7, $y1, $x4, $r9
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_Y_X $dm0, $dm5, $y4, $x7, $r8

    $dm6 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm6, $dm4, $y3, $y3, $r14
    $dm4 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm4, $dm3, $y2, $y4, $r11
    $dm0 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm0, $dm2, $y0, $y0, $r8
    $dm5 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm5, $dm1, $y1, $y1, $r13
    $dm2 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm2, $dm7, $y4, $y2, $r15
    $dm1 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm1, $dm0, $y5, $y5, $r10
    $dm7 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm7, $dm5, $y3, $y3, $r9
    $dm3 = VADDMAC_vaddmac_vmul_cm_core_Y_Y $dm3, $dm6, $y2, $y4, $r12

    $cml7 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml7, $cml4, $x8, $ex2, $r9, implicit-def $srsparse_of
    $cml4 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml4, $cml6, $x11, $ex5, $r15, implicit-def $srsparse_of
    $cml5 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml5, $cml2, $x5, $ex7, $r12, implicit-def $srsparse_of
    $cml2 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml2, $cml5, $x4, $ex6, $r11, implicit-def $srsparse_of
    $cml6 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml6, $cml0, $x6, $ex10, $r13, implicit-def $srsparse_of
    $cml3 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml3, $cml1, $x7, $ex9, $r10, implicit-def $srsparse_of
    $cml0 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml0, $cml3, $x2, $ex11, $r14, implicit-def $srsparse_of
    $cml1 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml1, $cml7, $x9, $ex8, $r8, implicit-def $srsparse_of
    $cml7 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml7, $cml4, $x0, $ex0, $r9, implicit-def $srsparse_of
    $cml4 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml4, $cml6, $x10, $ex1, $r15, implicit-def $srsparse_of
    $cml5 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml5, $cml2, $x3, $ex3, $r12, implicit-def $srsparse_of
    $cml2 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_QX $cml2, $cml5, $x1, $ex4, $r11, implicit-def $srsparse_of

    $cml1 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml1, $cml3, $x6, $r1, $r11
    $cml0 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml0, $cml2, $x7, $r12, $r13
    $cml2 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml2, $cml1, $x5, $r6, $r12
    $cml6 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml6, $cml4, $x4, $r13, $r8
    $cml7 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml7, $cml5, $x2, $r3, $r10
    $cml5 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml5, $cml7, $x11, $r8, $r14
    $cml3 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml3, $cml6, $x0, $r9, $r15
    $cml4 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml4, $cml0, $x9, $r14, $r9
    $cml1 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml1, $cml3, $x3, $r7, $r11
    $cml0 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml0, $cml2, $x8, $r4, $r13
    $cml2 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml2, $cml1, $x1, $r2, $r12
    $cml6 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml6, $cml4, $x10, $r5, $r8
    $cml7 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml7, $cml5, $x6, $r10, $r10
    $cml5 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml5, $cml7, $x7, $r11, $r14
    $cml3 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml3, $cml6, $x5, $r15, $r15
    $cml4 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_R $cml4, $cml0, $x4, $r0, $r9

    $cml6 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml6, $cml5, $x1, $x0, $r12
    $cml1 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml1, $cml6, $x8, $x5, $r15
    $cml5 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml5, $cml2, $x6, $x8, $r14
    $cml0 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml0, $cml3, $x10, $x1, $r8
    $cml7 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml7, $cml0, $x2, $x11, $r10
    $cml2 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml2, $cml1, $x3, $x2, $r11
    $cml3 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml3, $cml7, $x0, $x4, $r9
    $cml4 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml4, $cml4, $x7, $x6, $r13
    $cml6 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml6, $cml5, $x4, $x9, $r12
    $cml1 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml1, $cml6, $x5, $x7, $r15
    $cml5 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml5, $cml2, $x11, $x3, $r14
    $cml0 = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X $cml0, $cml3, $x9, $x10, $r8

    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm0, $r31, $x8, $ex0, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm3, $r31, $x11, $ex10, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm5, $r31, $x6, $ex1, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm1, $r31, $x10, $ex11, $r10, implicit-def $srsparse_of, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm2, $r31, $x4, $ex4, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm6, $r31, $x3, $ex7, $r12, implicit-def $srsparse_of, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm4, $r31, $x2, $ex6, $r8, implicit-def $srsparse_of, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm7, $r31, $x5, $ex2, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm0, $r31, $x0, $ex5, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm3, $r31, $x9, $ex8, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm5, $r31, $x1, $ex9, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QX $dm1, $r31, $x7, $ex3, $r10, implicit-def $srsparse_of, implicit $crscden

    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm7, $r31, $x11, $ey5, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm3, $r31, $x5, $ey1, $r10, implicit-def $srsparse_of, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm0, $r31, $x6, $ey0, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm2, $r31, $x10, $ey3, $r8, implicit-def $srsparse_of, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm4, $r31, $x9, $ey2, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm5, $r31, $x1, $ey4, $r12, implicit-def $srsparse_of, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm1, $r31, $x7, $ey5, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm6, $r31, $x8, $ey1, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm7, $r31, $x4, $ey0, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm3, $r31, $x2, $ey3, $r10, implicit-def $srsparse_of, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm0, $r31, $x3, $ey2, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_QY $dm2, $r31, $x0, $ey4, $r8, implicit-def $srsparse_of, implicit $crscden

    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm7, $r31, $x6, $r3, $r11, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm6, $r31, $x2, $r4, $r10, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm0, $r31, $x9, $r9, $r15, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm3, $r31, $x10, $r12, $r13, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm4, $r31, $x1, $r13, $r8, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm1, $r31, $x0, $r14, $r9, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm5, $r31, $x11, $r15, $r12, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm2, $r31, $x3, $r7, $r14, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm7, $r31, $x4, $r6, $r11, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm6, $r31, $x8, $r1, $r10, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm0, $r31, $x5, $r0, $r15, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm3, $r31, $x7, $r5, $r13, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm4, $r31, $x6, $r2, $r8, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm1, $r31, $x2, $r10, $r9, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm5, $r31, $x9, $r11, $r12, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_R $dm2, $r31, $x10, $r8, $r14, implicit $crscden

    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm1, $r31, $x1, $x10, $r8, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm4, $r31, $x2, $x7, $r15, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm3, $r31, $x5, $x1, $r13, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm2, $r31, $x8, $x0, $r11, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm0, $r31, $x6, $x8, $r9, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm6, $r31, $x11, $x11, $r10, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm5, $r31, $x7, $x9, $r14, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm7, $r31, $x10, $x6, $r12, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm1, $r31, $x3, $x3, $r8, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm4, $r31, $x9, $x5, $r15, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm3, $r31, $x0, $x4, $r13, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_X $dm2, $r31, $x4, $x2, $r11, implicit $crscden

    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm0, $r31, $x2, $y3, $r13, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm7, $r31, $x7, $y5, $r11, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm3, $r31, $x6, $y1, $r8, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm6, $r31, $x1, $y4, $r14, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm4, $r31, $x10, $y0, $r9, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm2, $r31, $x0, $y2, $r12, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm5, $r31, $x9, $y3, $r10, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm1, $r31, $x5, $y5, $r15, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm0, $r31, $x11, $y1, $r13, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm7, $r31, $x3, $y4, $r11, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm3, $r31, $x8, $y0, $r8, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_X_Y $dm6, $r31, $x4, $y2, $r14, implicit $crscden

    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm0, $r31, $y4, $ex2, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm7, $r31, $y3, $ex0, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm3, $r31, $y5, $ex8, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm1, $r31, $y0, $ex1, $r8, implicit-def $srsparse_of, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm2, $r31, $y1, $ex3, $r12, implicit-def $srsparse_of, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm5, $r31, $y2, $ex10, $r10, implicit-def $srsparse_of, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm6, $r31, $y4, $ex4, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm4, $r31, $y3, $ex5, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm0, $r31, $y5, $ex7, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm7, $r31, $y0, $ex6, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm3, $r31, $y1, $ex11, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_QX $dm1, $r31, $y2, $ex9, $r8, implicit-def $srsparse_of, implicit $crscden

    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm3, $r31, $y4, $r8, $r12, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm7, $r31, $y3, $r4, $r11, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm1, $r31, $y5, $r9, $r13, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm5, $r31, $y0, $r1, $r10, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm2, $r31, $y2, $r14, $r15, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm0, $r31, $y1, $r5, $r9, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm6, $r31, $y4, $r2, $r14, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm4, $r31, $y3, $r15, $r8, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm3, $r31, $y5, $r3, $r12, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm7, $r31, $y0, $r0, $r11, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm1, $r31, $y2, $r13, $r13, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm5, $r31, $y1, $r12, $r10, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm2, $r31, $y4, $r6, $r15, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm0, $r31, $y3, $r11, $r9, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm6, $r31, $y5, $r7, $r14, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_R $dm4, $r31, $y0, $r10, $r8, implicit $crscden

    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm7, $r31, $y3, $x10, $r12, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm0, $r31, $y5, $x7, $r15, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm4, $r31, $y4, $x0, $r14, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm6, $r31, $y2, $x11, $r13, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm5, $r31, $y0, $x1, $r9, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm2, $r31, $y1, $x9, $r10, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm1, $r31, $y3, $x8, $r8, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm3, $r31, $y5, $x5, $r11, implicit $crscden
    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm7, $r31, $y4, $x6, $r12, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm0, $r31, $y2, $x3, $r15, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm4, $r31, $y0, $x2, $r14, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_X $dm6, $r31, $y1, $x4, $r13, implicit $crscden

    $dm2, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm0, $r31, $y4, $y3, $r8, implicit $crscden
    $dm5, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm7, $r31, $y1, $y2, $r9, implicit $crscden
    $dm0, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm2, $r31, $y3, $y5, $r10, implicit $crscden
    $dm4, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm4, $r31, $y5, $y0, $r13, implicit $crscden
    $dm6, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm1, $r31, $y0, $y4, $r11, implicit $crscden
    $dm7, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm6, $r31, $y2, $y1, $r14, implicit $crscden
    $dm3, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm5, $r31, $y4, $y3, $r15, implicit $crscden
    $dm1, $r31 = VADDMAC_vaddmac_scd_add_scd_incr_vmul_cm_core_Y_Y $dm3, $r31, $y1, $y2, $r12, implicit $crscden

    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm0, $r31, $x1, $ex9, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm6, $r31, $x8, $ex4, $r12, implicit-def $srsparse_of, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm7, $r31, $x2, $ex1, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm3, $r31, $x5, $ex8, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm4, $r31, $x9, $ex0, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm5, $r31, $x11, $ex3, $r10, implicit-def $srsparse_of, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm2, $r31, $x0, $ex2, $r8, implicit-def $srsparse_of, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm1, $r31, $x7, $ex7, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm0, $r31, $x4, $ex11, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm6, $r31, $x3, $ex5, $r12, implicit-def $srsparse_of, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm7, $r31, $x10, $ex10, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QX $dm3, $r31, $x6, $ex6, $r13, implicit-def $srsparse_of, implicit $crscden

    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm0, $r31, $x1, $ey3, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm6, $r31, $x7, $ey1, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm2, $r31, $x8, $ey2, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm5, $r31, $x10, $ey4, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm4, $r31, $x6, $ey0, $r8, implicit-def $srsparse_of, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm7, $r31, $x9, $ey5, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm1, $r31, $x4, $ey3, $r10, implicit-def $srsparse_of, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm3, $r31, $x3, $ey1, $r12, implicit-def $srsparse_of, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm0, $r31, $x0, $ey2, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm6, $r31, $x5, $ey4, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm2, $r31, $x11, $ey0, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_QY $dm5, $r31, $x2, $ey5, $r15, implicit-def $srsparse_of, implicit $crscden

    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm7, $r31, $x1, $r6, $r12, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm6, $r31, $x11, $r10, $r10, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm3, $r31, $x7, $r4, $r13, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm4, $r31, $x2, $r5, $r14, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm0, $r31, $x3, $r11, $r9, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm2, $r31, $x0, $r12, $r15, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm1, $r31, $x5, $r13, $r8, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm5, $r31, $x10, $r2, $r11, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm7, $r31, $x9, $r15, $r12, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm6, $r31, $x8, $r7, $r10, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm3, $r31, $x4, $r1, $r13, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm4, $r31, $x6, $r0, $r14, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm0, $r31, $x1, $r9, $r9, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm2, $r31, $x11, $r8, $r15, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm1, $r31, $x7, $r3, $r8, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_R $dm5, $r31, $x2, $r14, $r11, implicit $crscden

    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm2, $r31, $x1, $x8, $r11, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm6, $r31, $x10, $x3, $r12, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm4, $r31, $x8, $x7, $r13, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm5, $r31, $x9, $x5, $r9, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm7, $r31, $x11, $x4, $r15, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm3, $r31, $x3, $x0, $r10, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm1, $r31, $x5, $x6, $r8, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm0, $r31, $x6, $x1, $r14, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm2, $r31, $x7, $x2, $r11, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm6, $r31, $x0, $x10, $r12, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm4, $r31, $x4, $x9, $r13, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_X $dm5, $r31, $x2, $x11, $r9, implicit $crscden

    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm7, $r31, $x7, $y2, $r11, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm2, $r31, $x2, $y1, $r13, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm6, $r31, $x10, $y3, $r10, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm4, $r31, $x4, $y0, $r8, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm1, $r31, $x11, $y5, $r15, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm0, $r31, $x9, $y4, $r14, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm5, $r31, $x0, $y2, $r12, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm3, $r31, $x3, $y1, $r9, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm7, $r31, $x5, $y3, $r11, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm2, $r31, $x6, $y0, $r13, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm6, $r31, $x1, $y5, $r10, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_X_Y $dm4, $r31, $x8, $y4, $r8, implicit $crscden

    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm3, $r31, $y4, $ex0, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm1, $r31, $y1, $ex1, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm7, $r31, $y3, $ex8, $r8, implicit-def $srsparse_of, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm4, $r31, $y0, $ex5, $r11, implicit-def $srsparse_of, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm2, $r31, $y2, $ex6, $r10, implicit-def $srsparse_of, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm0, $r31, $y5, $ex2, $r14, implicit-def $srsparse_of, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm5, $r31, $y4, $ex3, $r13, implicit-def $srsparse_of, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm6, $r31, $y1, $ex11, $r12, implicit-def $srsparse_of, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm3, $r31, $y3, $ex9, $r15, implicit-def $srsparse_of, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm1, $r31, $y0, $ex10, $r9, implicit-def $srsparse_of, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm7, $r31, $y2, $ex7, $r8, implicit-def $srsparse_of, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_QX $dm4, $r31, $y5, $ex4, $r11, implicit-def $srsparse_of, implicit $crscden

    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm4, $r31, $y3, $r15, $r8, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm2, $r31, $y2, $r14, $r12, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm7, $r31, $y1, $r4, $r14, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm5, $r31, $y5, $r0, $r9, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm6, $r31, $y4, $r7, $r11, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm1, $r31, $y0, $r12, $r13, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm3, $r31, $y3, $r5, $r15, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm0, $r31, $y2, $r2, $r10, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm4, $r31, $y1, $r8, $r8, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm2, $r31, $y5, $r11, $r12, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm7, $r31, $y4, $r3, $r14, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm5, $r31, $y0, $r1, $r9, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm6, $r31, $y3, $r6, $r11, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm1, $r31, $y2, $r10, $r13, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm3, $r31, $y1, $r9, $r15, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_R $dm0, $r31, $y5, $r13, $r10, implicit $crscden

    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm4, $r31, $y1, $x3, $r12, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm5, $r31, $y5, $x6, $r10, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm1, $r31, $y0, $x8, $r9, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm3, $r31, $y4, $x4, $r14, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm2, $r31, $y2, $x2, $r15, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm6, $r31, $y3, $x9, $r11, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm0, $r31, $y1, $x7, $r13, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm7, $r31, $y5, $x10, $r8, implicit $crscden
    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm4, $r31, $y0, $x11, $r12, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm5, $r31, $y4, $x1, $r10, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm1, $r31, $y2, $x0, $r9, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_X $dm3, $r31, $y3, $x5, $r14, implicit $crscden

    $dm2 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm0, $r31, $y2, $y2, $r11, implicit $crscden
    $dm4 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm2, $r31, $y0, $y3, $r8, implicit $crscden
    $dm3 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm3, $r31, $y5, $y5, $r13, implicit $crscden
    $dm5 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm1, $r31, $y4, $y0, $r14, implicit $crscden
    $dm0 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm6, $r31, $y1, $y1, $r12, implicit $crscden
    $dm7 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm7, $r31, $y3, $y4, $r9, implicit $crscden
    $dm1 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm4, $r31, $y2, $y2, $r10, implicit $crscden
    $dm6 = VADDMAC_vaddmac_scd_add_scd_noincr_vmul_cm_core_Y_Y $dm5, $r31, $y0, $y3, $r15, implicit $crscden

    $cml3, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml4, $r31, $x4, $ex4, $r14, implicit-def $srsparse_of, implicit $crscden
    $cml0, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml5, $r31, $x7, $ex7, $r15, implicit-def $srsparse_of, implicit $crscden
    $cml6, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml7, $r31, $x2, $ex3, $r8, implicit-def $srsparse_of, implicit $crscden
    $cml4, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml0, $r31, $x1, $ex6, $r13, implicit-def $srsparse_of, implicit $crscden
    $cml5, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml1, $r31, $x8, $ex5, $r11, implicit-def $srsparse_of, implicit $crscden
    $cml2, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml2, $r31, $x5, $ex0, $r10, implicit-def $srsparse_of, implicit $crscden
    $cml7, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml3, $r31, $x10, $ex1, $r9, implicit-def $srsparse_of, implicit $crscden
    $cml1, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml6, $r31, $x6, $ex9, $r12, implicit-def $srsparse_of, implicit $crscden
    $cml3, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml4, $r31, $x9, $ex10, $r14, implicit-def $srsparse_of, implicit $crscden
    $cml0, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml5, $r31, $x0, $ex2, $r15, implicit-def $srsparse_of, implicit $crscden
    $cml6, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml7, $r31, $x3, $ex11, $r8, implicit-def $srsparse_of, implicit $crscden
    $cml4, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_QX $cml0, $r31, $x11, $ex8, $r13, implicit-def $srsparse_of, implicit $crscden

    $cml4, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml4, $r31, $x3, $r15, $r10, implicit $crscden
    $cml5, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml3, $r31, $x4, $r0, $r14, implicit $crscden
    $cml0, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml5, $r31, $x11, $r8, $r11, implicit $crscden
    $cml7, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml7, $r31, $x5, $r14, $r9, implicit $crscden
    $cml3, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml1, $r31, $x2, $r3, $r8, implicit $crscden
    $cml6, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml2, $r31, $x0, $r2, $r12, implicit $crscden
    $cml2, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml6, $r31, $x7, $r11, $r15, implicit $crscden
    $cml1, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml0, $r31, $x9, $r10, $r13, implicit $crscden
    $cml4, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml4, $r31, $x10, $r4, $r10, implicit $crscden
    $cml5, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml3, $r31, $x8, $r13, $r14, implicit $crscden
    $cml0, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml5, $r31, $x1, $r12, $r11, implicit $crscden
    $cml7, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml7, $r31, $x6, $r1, $r9, implicit $crscden
    $cml3, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml1, $r31, $x3, $r9, $r8, implicit $crscden
    $cml6, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml2, $r31, $x4, $r5, $r12, implicit $crscden
    $cml2, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml6, $r31, $x11, $r6, $r15, implicit $crscden
    $cml1, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_R $cml0, $r31, $x5, $r7, $r13, implicit $crscden

    $cml2, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml0, $r31, $x2, $x7, $r10, implicit $crscden
    $cml5, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml7, $r31, $x6, $x1, $r13, implicit $crscden
    $cml4, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml5, $r31, $x11, $x2, $r14, implicit $crscden
    $cml7, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml3, $r31, $x1, $x6, $r15, implicit $crscden
    $cml0, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml6, $r31, $x0, $x5, $r9, implicit $crscden
    $cml3, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml1, $r31, $x7, $x9, $r12, implicit $crscden
    $cml6, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml2, $r31, $x4, $x3, $r11, implicit $crscden
    $cml1, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml4, $r31, $x3, $x8, $r8, implicit $crscden
    $cml2, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml0, $r31, $x8, $x0, $r10, implicit $crscden
    $cml5, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml7, $r31, $x5, $x10, $r13, implicit $crscden
    $cml4, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml5, $r31, $x10, $x11, $r14, implicit $crscden
    $cml7, $r31 = VADDMAC_vaddmac_scd_half_add_scd_incr_half_vmul_cm_half_core_X_X $cml3, $r31, $x9, $x4, $r15, implicit $crscden

    $cml1 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml3, $r31, $x5, $ex11, $r8, implicit-def $srsparse_of, implicit $crscden
    $cml5 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml2, $r31, $x7, $ex8, $r11, implicit-def $srsparse_of, implicit $crscden
    $cml2 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml5, $r31, $x0, $ex10, $r12, implicit-def $srsparse_of, implicit $crscden
    $cml3 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml1, $r31, $x11, $ex0, $r10, implicit-def $srsparse_of, implicit $crscden
    $cml7 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml4, $r31, $x9, $ex9, $r9, implicit-def $srsparse_of, implicit $crscden
    $cml0 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml7, $r31, $x4, $ex1, $r15, implicit-def $srsparse_of, implicit $crscden
    $cml4 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml6, $r31, $x10, $ex6, $r13, implicit-def $srsparse_of, implicit $crscden
    $cml6 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml0, $r31, $x3, $ex2, $r14, implicit-def $srsparse_of, implicit $crscden
    $cml1 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml3, $r31, $x1, $ex3, $r8, implicit-def $srsparse_of, implicit $crscden
    $cml5 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml2, $r31, $x2, $ex5, $r11, implicit-def $srsparse_of, implicit $crscden
    $cml2 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml5, $r31, $x8, $ex4, $r12, implicit-def $srsparse_of, implicit $crscden
    $cml3 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_QX $cml1, $r31, $x6, $ex7, $r10, implicit-def $srsparse_of, implicit $crscden

    $cml4 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml2, $r31, $x3, $r1, $r13, implicit $crscden
    $cml3 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml4, $r31, $x4, $r4, $r12, implicit $crscden
    $cml0 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml7, $r31, $x11, $r9, $r14, implicit $crscden
    $cml5 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml6, $r31, $x7, $r5, $r10, implicit $crscden
    $cml2 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml1, $r31, $x8, $r3, $r15, implicit $crscden
    $cml6 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml5, $r31, $x5, $r10, $r8, implicit $crscden
    $cml1 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml0, $r31, $x0, $r14, $r11, implicit $crscden
    $cml7 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml3, $r31, $x6, $r7, $r9, implicit $crscden
    $cml4 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml2, $r31, $x10, $r0, $r13, implicit $crscden
    $cml3 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml4, $r31, $x2, $r15, $r12, implicit $crscden
    $cml0 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml7, $r31, $x1, $r11, $r14, implicit $crscden
    $cml5 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml6, $r31, $x9, $r2, $r10, implicit $crscden
    $cml2 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml1, $r31, $x3, $r13, $r15, implicit $crscden
    $cml6 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml5, $r31, $x4, $r8, $r8, implicit $crscden
    $cml1 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml0, $r31, $x11, $r12, $r11, implicit $crscden
    $cml7 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_R $cml3, $r31, $x7, $r6, $r9, implicit $crscden

    $cml5 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml3, $r31, $x4, $x5, $r12, implicit $crscden
    $cml1 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml2, $r31, $x7, $x10, $r9, implicit $crscden
    $cml2 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml1, $r31, $x3, $x6, $r8, implicit $crscden
    $cml6 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml4, $r31, $x2, $x9, $r11, implicit $crscden
    $cml4 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml7, $r31, $x10, $x4, $r10, implicit $crscden
    $cml0 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml5, $r31, $x9, $x7, $r15, implicit $crscden
    $cml7 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml6, $r31, $x5, $x2, $r14, implicit $crscden
    $cml3 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml0, $r31, $x0, $x8, $r13, implicit $crscden
    $cml5 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml3, $r31, $x8, $x3, $r12, implicit $crscden
    $cml1 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml2, $r31, $x6, $x1, $r9, implicit $crscden
    $cml2 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml1, $r31, $x1, $x11, $r8, implicit $crscden
    $cml6 = VADDMAC_vaddmac_scd_half_add_scd_noincr_half_vmul_cm_half_core_X_X $cml4, $r31, $x11, $x0, $r11, implicit $crscden

    $dm5 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm5, $dm1, $x9, $ey3, $r8, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm0, $dm6, $x4, $ey0, $r14, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm4, $dm0, $x10, $ey5, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm2, $dm7, $x11, $ey1, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm1, $dm4, $x8, $ey2, $r13, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm3 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm3, $dm3, $x0, $ey4, $r15, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm6, $dm5, $x3, $ey3, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm7, $dm2, $x6, $ey0, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm5, $dm1, $x5, $ey5, $r8, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm0, $dm6, $x1, $ey1, $r14, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm4, $dm0, $x2, $ey2, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_QY $dm2, $dm7, $x7, $ey4, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $dm7 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm7, $dm1, $x6, $x6, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm1, $dm7, $x10, $x10, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm6, $dm3, $x3, $x11, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm5, $dm6, $x8, $x2, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm4, $dm2, $x1, $x4, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm3 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm3, $dm4, $x5, $x8, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm2, $dm5, $x9, $x0, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm0, $dm0, $x0, $x3, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm7, $dm1, $x4, $x1, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm1, $dm7, $x7, $x9, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm6, $dm3, $x11, $x7, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X $dm5, $dm6, $x2, $x5, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $dm3 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm3, $dm1, $y5, $r7, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm2, $dm6, $y3, $r15, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm5, $dm0, $y1, $r0, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm6, $dm2, $y4, $r4, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm4, $dm4, $y0, $r11, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm0, $dm5, $y2, $r12, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm1, $dm7, $y5, $r3, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm7, $dm3, $y3, $r9, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm3 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm3, $dm1, $y1, $r8, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm2, $dm6, $y4, $r2, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm5, $dm0, $y0, $r10, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm6, $dm2, $y2, $r6, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm4, $dm4, $y5, $r13, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm0, $dm5, $y3, $r14, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm1, $dm7, $y1, $r1, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R $dm7, $dm3, $y4, $r5, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $dm4 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm4, $dm5, $y0, $y4, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm7, $dm7, $y5, $y1, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm1, $dm0, $y1, $y3, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm0, $dm3, $y4, $y0, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm5, $dm6, $y2, $y5, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm2, $dm2, $y3, $y2, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm3 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm3, $dm4, $y0, $y4, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y $dm6, $dm1, $y5, $y1, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $cml0 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml0, $cml7, $x3, $r5, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml2 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml2, $cml2, $x2, $r15, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml6 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml6, $cml1, $x8, $r12, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml5 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml5, $cml5, $x11, $r8, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml4 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml4, $cml6, $x10, $r13, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml1 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml1, $cml4, $x5, $r6, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml7 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml7, $cml3, $x4, $r7, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml3 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml3, $cml0, $x6, $r0, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml0 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml0, $cml7, $x1, $r10, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml2 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml2, $cml2, $x9, $r14, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml6 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml6, $cml1, $x7, $r11, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml5 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml5, $cml5, $x0, $r4, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml4 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml4, $cml6, $x3, $r1, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml1 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml1, $cml4, $x2, $r3, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml7 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml7, $cml3, $x8, $r2, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml3 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R $cml3, $cml0, $x11, $r9, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $cml6 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml6, $cml6, $x4, $y2, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml5 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml5, $cml2, $x7, $y3, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml7 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml7, $cml4, $x5, $y4, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml1 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml1, $cml0, $x1, $y0, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml3 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml3, $cml1, $x8, $y5, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml2 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml2, $cml3, $x10, $y1, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml0 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml0, $cml7, $x0, $y2, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml4 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml4, $cml5, $x9, $y3, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml6 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml6, $cml6, $x11, $y4, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml5 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml5, $cml2, $x2, $y0, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml7 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml7, $cml4, $x6, $y5, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml1 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y $cml1, $cml0, $x3, $y1, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $cml0 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml0, $cml2, $y3, $ey4, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml5 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml5, $cml0, $y4, $ey1, $r14, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml3 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml3, $cml7, $y1, $ey5, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml2 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml2, $cml6, $y0, $ey0, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml4 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml4, $cml1, $y2, $ey3, $r8, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml7 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml7, $cml3, $y5, $ey2, $r15, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml1 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml1, $cml4, $y3, $ey4, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml6 = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_Y_QY $cml6, $cml5, $y4, $ey1, $r13, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $cml0 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml0, $cml4, $x6, $x9, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml4 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml4, $cml1, $x3, $x8, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml7 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml7, $cml2, $x9, $x1, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml1 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml1, $cml6, $x10, $x10, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml6 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml6, $cml7, $x5, $x3, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml5 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml5, $cml5, $x2, $x6, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml2 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml2, $cml0, $x0, $x11, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml3 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml3, $cml3, $x11, $x0, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml0 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml0, $cml4, $x4, $x7, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml4 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml4, $cml1, $x1, $x5, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml7 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml7, $cml2, $x8, $x2, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    $cml1 = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X $cml1, $cml6, $x7, $x4, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask

    $dm1, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm5, $r31, $x3, $ey3, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm0, $r31, $x9, $ey4, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm3, $r31, $x0, $ey2, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm7, $r31, $x10, $ey1, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm1, $r31, $x2, $ey5, $r8, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm2, $r31, $x1, $ey0, $r14, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm4, $r31, $x11, $ey3, $r15, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm6, $r31, $x5, $ey4, $r13, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm5, $r31, $x7, $ey2, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm0, $r31, $x8, $ey1, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm3, $r31, $x4, $ey5, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_QY $dm7, $r31, $x6, $ey0, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm6, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm0, $r31, $x8, $x6, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm4, $r31, $x1, $x8, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm2, $r31, $x5, $x2, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm7, $r31, $x6, $x5, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm5, $r31, $x2, $x1, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm3, $r31, $x10, $x0, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm6, $r31, $x7, $x4, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm1, $r31, $x9, $x11, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm0, $r31, $x11, $x10, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm4, $r31, $x4, $x7, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm2, $r31, $x3, $x3, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_X_X $dm7, $r31, $x0, $x9, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm5, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm4, $r31, $y2, $r5, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm7, $r31, $y4, $r2, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm5, $r31, $y3, $r7, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm2, $r31, $y1, $r12, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm0, $r31, $y0, $r15, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm1, $r31, $y5, $r1, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm3, $r31, $y2, $r3, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm6, $r31, $y4, $r10, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm4, $r31, $y3, $r11, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm7, $r31, $y1, $r13, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm5, $r31, $y0, $r4, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm2, $r31, $y5, $r14, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm0, $r31, $y2, $r6, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm1, $r31, $y4, $r0, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm3, $r31, $y3, $r9, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_R $dm6, $r31, $y1, $r8, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm2, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm5, $r31, $y5, $y5, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm4, $r31, $y4, $y1, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm1, $r31, $y3, $y0, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm2, $r31, $y0, $y4, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm6, $r31, $y2, $y2, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm0, $r31, $y1, $y3, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm7, $r31, $y5, $y5, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bf_scd_add_scd_incr_vmul_bf_core_Y_Y $dm3, $r31, $y4, $y1, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm7 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm5, $r31, $x11, $ey1, $r15, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm0, $r31, $x9, $ey0, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm4, $r31, $x4, $ey2, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm1, $r31, $x8, $ey3, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm2, $r31, $x2, $ey4, $r14, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm7, $r31, $x6, $ey5, $r13, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm6, $r31, $x3, $ey1, $r8, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm3, $r31, $x5, $ey0, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm5, $r31, $x10, $ey2, $r15, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm0, $r31, $x7, $ey3, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm4, $r31, $x0, $ey4, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_QY $dm1, $r31, $x1, $ey5, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm3 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm4, $r31, $x6, $x2, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm5, $r31, $x3, $x8, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm2, $r31, $x2, $x10, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm1, $r31, $x8, $x1, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm3, $r31, $x10, $x11, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm7, $r31, $x4, $x5, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm6, $r31, $x1, $x0, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm0, $r31, $x0, $x4, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm4, $r31, $x7, $x3, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm5, $r31, $x9, $x7, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm2, $r31, $x5, $x9, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_X_X $dm1, $r31, $x11, $x6, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm0 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm3, $r31, $y0, $r4, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm5, $r31, $y4, $r3, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm4, $r31, $y5, $r8, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm6, $r31, $y2, $r11, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm7, $r31, $y1, $r1, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm1, $r31, $y3, $r5, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm2, $r31, $y0, $r2, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm0, $r31, $y4, $r15, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm3, $r31, $y5, $r6, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm4 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm5, $r31, $y2, $r9, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm4, $r31, $y1, $r12, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm6, $r31, $y3, $r7, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm7, $r31, $y0, $r0, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm1, $r31, $y4, $r13, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm2, $r31, $y5, $r14, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_R $dm0, $r31, $y2, $r10, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm4 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm7, $r31, $y2, $y4, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm6, $r31, $y3, $y0, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm0, $r31, $y4, $y3, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm3, $r31, $y0, $y5, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm4, $r31, $y1, $y2, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm6 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm2, $r31, $y5, $y1, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm5, $r31, $y2, $y4, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $dm1 = VADDMAC_f_vaddmac_bf_scd_add_scd_noincr_vmul_bf_core_Y_Y $dm1, $r31, $y3, $y0, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml6, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml0, $r31, $x10, $r8, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml5, $r31, $x8, $r9, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml2, $r31, $x7, $r0, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml4, $r31, $x6, $r3, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml7, $r31, $x2, $r5, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml3, $r31, $x1, $r2, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml1, $r31, $x0, $r4, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml6, $r31, $x11, $r15, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml0, $r31, $x3, $r1, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml5, $r31, $x9, $r7, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml2, $r31, $x4, $r12, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml4, $r31, $x5, $r6, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml7, $r31, $x10, $r10, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml3, $r31, $x8, $r13, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml1, $r31, $x7, $r11, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_R $cml6, $r31, $x6, $r14, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml2, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml2, $r31, $x6, $y1, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml5, $r31, $x7, $y4, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml0, $r31, $x10, $y3, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml7, $r31, $x0, $y0, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml1, $r31, $x11, $y2, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml6, $r31, $x1, $y5, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml3, $r31, $x3, $y1, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml4, $r31, $x9, $y4, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml2, $r31, $x5, $y3, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml5, $r31, $x8, $y0, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml0, $r31, $x2, $y2, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_X_Y $cml7, $r31, $x4, $y5, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml0, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml7, $r31, $y1, $ey1, $r15, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml5, $r31, $y2, $ey0, $r14, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml0, $r31, $y4, $ey5, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml4, $r31, $y3, $ey3, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml1, $r31, $y5, $ey4, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml2, $r31, $y0, $ey2, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml6, $r31, $y1, $ey1, $r13, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_core_Y_QY $cml3, $r31, $y2, $ey0, $r8, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml4, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml0, $r31, $x1, $x1, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml6, $r31, $x10, $x7, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml2, $r31, $x4, $x6, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml4, $r31, $x11, $x10, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml7, $r31, $x8, $x3, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml5, $r31, $x5, $x0, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml3, $r31, $x2, $x11, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml1, $r31, $x0, $x2, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml0, $r31, $x9, $x9, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml6, $r31, $x3, $x8, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml2, $r31, $x6, $x5, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0, $r31 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_incr_half_vmul_bf_half_core_X_X $cml4, $r31, $x7, $x4, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml7 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml3, $r31, $x2, $r14, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml7, $r31, $x3, $r11, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml6, $r31, $x0, $r7, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml5, $r31, $x7, $r2, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml4, $r31, $x11, $r13, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml0, $r31, $x8, $r4, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml1, $r31, $x6, $r1, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml2, $r31, $x5, $r8, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml3, $r31, $x1, $r12, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml7, $r31, $x10, $r5, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml6, $r31, $x9, $r3, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml5, $r31, $x4, $r0, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml4, $r31, $x2, $r10, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml0, $r31, $x3, $r6, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml1, $r31, $x0, $r9, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_R $cml2, $r31, $x7, $r15, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml0 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml7, $r31, $x10, $y3, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml6, $r31, $x8, $y2, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml1, $r31, $x0, $y0, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml2, $r31, $x4, $y5, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml0, $r31, $x1, $y1, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml5, $r31, $x7, $y4, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml4, $r31, $x11, $y3, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml3, $r31, $x6, $y2, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml7, $r31, $x2, $y0, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml6, $r31, $x5, $y5, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml1, $r31, $x9, $y1, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_X_Y $cml2, $r31, $x3, $y4, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml6 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml1, $r31, $y3, $ey1, $r15, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml3, $r31, $y5, $ey3, $r14, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml0, $r31, $y1, $ey0, $r11, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml5, $r31, $y0, $ey2, $r9, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml4, $r31, $y4, $ey4, $r13, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml7, $r31, $y2, $ey5, $r12, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml6, $r31, $y3, $ey1, $r8, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_core_Y_QY $cml2, $r31, $y5, $ey3, $r10, implicit-def $srfpflags, implicit-def $srsparse_of, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $cml3 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml2, $r31, $x10, $x10, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml1, $r31, $x11, $x1, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml6, $r31, $x2, $x0, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml4, $r31, $x1, $x8, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml1 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml5, $r31, $x6, $x2, $r14, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml6 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml0, $r31, $x3, $x4, $r10, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml5 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml3, $r31, $x8, $x11, $r15, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml7 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml7, $r31, $x5, $x3, $r11, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml3 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml2, $r31, $x4, $x5, $r12, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml4 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml1, $r31, $x9, $x7, $r8, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml2 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml6, $r31, $x0, $x6, $r13, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden
    $cml0 = VADDMAC_f_vaddmac_bf_scd_half_add_scd_noincr_half_vmul_bf_half_core_X_X $cml4, $r31, $x7, $x9, $r9, implicit-def $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, implicit $crscden

    $dm5 = VADDMAC_f_vaddmac_bfp13 $dm5, $dm1, $fex0, $fey5, $r10, implicit-def $srfpflags, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bfp13 $dm4, $dm2, $fex7, $fey2, $r14, implicit-def $srfpflags, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bfp13 $dm7, $dm3, $fex8, $fey0, $r12, implicit-def $srfpflags, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bfp13 $dm1, $dm7, $fex10, $fey3, $r11, implicit-def $srfpflags, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bfp13 $dm0, $dm6, $fex3, $fey4, $r8, implicit-def $srfpflags, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bfp13 $dm6, $dm0, $fex9, $fey1, $r15, implicit-def $srfpflags, implicit $crfpmask
    $dm3 = VADDMAC_f_vaddmac_bfp13 $dm3, $dm4, $fex5, $fey5, $r9, implicit-def $srfpflags, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bfp13 $dm2, $dm5, $fex1, $fey2, $r13, implicit-def $srfpflags, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bfp13 $dm5, $dm1, $fex6, $fey0, $r10, implicit-def $srfpflags, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bfp13 $dm4, $dm2, $fex11, $fey3, $r14, implicit-def $srfpflags, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bfp13 $dm7, $dm3, $fex2, $fey4, $r12, implicit-def $srfpflags, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bfp13 $dm1, $dm7, $fex4, $fey1, $r11, implicit-def $srfpflags, implicit $crfpmask

    $dm5, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm3, $r31, $fex2, $fey4, $r10, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm0, $r31, $fex10, $fey3, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm1, $r31, $fex1, $fey1, $r13, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm7, $r31, $fex9, $fey5, $r12, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm4, $r31, $fex8, $fey2, $r9, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm5, $r31, $fex11, $fey0, $r14, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm2, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm6, $r31, $fex5, $fey4, $r11, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm3, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm2, $r31, $fex0, $fey3, $r8, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm3, $r31, $fex4, $fey1, $r10, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm0, $r31, $fex6, $fey5, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm1, $r31, $fex7, $fey2, $r13, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_incr $dm7, $r31, $fex3, $fey0, $r12, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden

    $dm6 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm6, $r31, $fex3, $fey0, $r13, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm4, $r31, $fex0, $fey3, $r9, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm5, $r31, $fex10, $fey4, $r10, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm3, $r31, $fex4, $fey1, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm0, $r31, $fex2, $fey2, $r14, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm1, $r31, $fex7, $fey5, $r11, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm4 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm2, $r31, $fex5, $fey0, $r8, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm1 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm7, $r31, $fex6, $fey3, $r12, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm6 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm6, $r31, $fex8, $fey4, $r13, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm4, $r31, $fex9, $fey1, $r9, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm5, $r31, $fex1, $fey2, $r10, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bfp13_scd_add_scd_noincr $dm3, $r31, $fex11, $fey5, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden

    $dm5 = VADDMAC_f_vaddmac_bfp16 $dm5, $dm0, $ewl5, $ey2, $ey2, $ewh5, $r14, implicit-def $srfpflags, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bfp16 $dm2, $dm4, $ewl11, $ey0, $ey0, $ewh11, $r8, implicit-def $srfpflags, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bfp16 $dm4, $dm1, $ewl6, $ey1, $ey3, $ewh6, $r12, implicit-def $srfpflags, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bfp16 $dm1, $dm7, $ewl7, $ey3, $ey1, $ewh7, $r11, implicit-def $srfpflags, implicit $crfpmask
    $dm0 = VADDMAC_f_vaddmac_bfp16 $dm0, $dm2, $ewl2, $ey2, $ey2, $ewh2, $r9, implicit-def $srfpflags, implicit $crfpmask
    $dm6 = VADDMAC_f_vaddmac_bfp16 $dm6, $dm5, $ewl1, $ey0, $ey0, $ewh1, $r15, implicit-def $srfpflags, implicit $crfpmask
    $dm7 = VADDMAC_f_vaddmac_bfp16 $dm7, $dm6, $ewl0, $ey1, $ey3, $ewh0, $r13, implicit-def $srfpflags, implicit $crfpmask
    $dm3 = VADDMAC_f_vaddmac_bfp16 $dm3, $dm3, $ewl3, $ey3, $ey1, $ewh3, $r10, implicit-def $srfpflags, implicit $crfpmask
    $dm5 = VADDMAC_f_vaddmac_bfp16 $dm5, $dm0, $ewl10, $ey2, $ey2, $ewh10, $r14, implicit-def $srfpflags, implicit $crfpmask
    $dm2 = VADDMAC_f_vaddmac_bfp16 $dm2, $dm4, $ewl8, $ey0, $ey0, $ewh8, $r8, implicit-def $srfpflags, implicit $crfpmask
    $dm4 = VADDMAC_f_vaddmac_bfp16 $dm4, $dm1, $ewl9, $ey1, $ey3, $ewh9, $r12, implicit-def $srfpflags, implicit $crfpmask
    $dm1 = VADDMAC_f_vaddmac_bfp16 $dm1, $dm7, $ewl4, $ey3, $ey1, $ewh4, $r11, implicit-def $srfpflags, implicit $crfpmask

    $dm3, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm4, $r31, $ewl7, $ey2, $ey1, $ewh7, $r8, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm6, $r31, $ewl8, $ey0, $ey2, $ewh8, $r9, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm5, $r31, $ewl0, $ey1, $ey3, $ewh0, $r14, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm2, $r31, $ewl2, $ey3, $ey0, $ewh2, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm5, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm3, $r31, $ewl4, $ey2, $ey1, $ewh4, $r13, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm4, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm7, $r31, $ewl6, $ey0, $ey2, $ewh6, $r12, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm2, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm1, $r31, $ewl9, $ey1, $ey3, $ewh9, $r10, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm1, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm0, $r31, $ewl3, $ey3, $ey0, $ewh3, $r11, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm3, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm4, $r31, $ewl11, $ey2, $ey1, $ewh11, $r8, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm0, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm6, $r31, $ewl10, $ey0, $ey2, $ewh10, $r9, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm6, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm5, $r31, $ewl1, $ey1, $ey3, $ewh1, $r14, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm7, $r31 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_incr $dm2, $r31, $ewl5, $ey3, $ey0, $ewh5, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden

    $dm1 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm2, $r31, $ewl3, $ey3, $ey3, $ewh3, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm5, $r31, $ewl1, $ey2, $ey2, $ewh1, $r8, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm1, $r31, $ewl7, $ey1, $ey1, $ewh7, $r11, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm4, $r31, $ewl5, $ey0, $ey0, $ewh5, $r12, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm0 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm3, $r31, $ewl8, $ey3, $ey3, $ewh8, $r14, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm7 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm0, $r31, $ewl6, $ey2, $ey2, $ewh6, $r10, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm4 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm7, $r31, $ewl9, $ey1, $ey1, $ewh9, $r13, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm6 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm6, $r31, $ewl4, $ey0, $ey0, $ewh4, $r9, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm1 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm2, $r31, $ewl10, $ey3, $ey3, $ewh10, $r15, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm3 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm5, $r31, $ewl2, $ey2, $ey2, $ewh2, $r8, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm5 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm1, $r31, $ewl0, $ey1, $ey1, $ewh0, $r11, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
    $dm2 = VADDMAC_f_vaddmac_bfp16_scd_add_scd_noincr $dm4, $r31, $ewl11, $ey0, $ey0, $ewh11, $r12, implicit-def $srfpflags, implicit $crfpmask, implicit $crscden
...

# CHECK: 0: 10 92 8d cc vaddmac dm3, dm3, dm2, x2, ex3, r14
# CHECK: 4: 10 9a e5 1e vaddmac dm7, dm7, dm3, x11, ex9, r8
# CHECK: 8: 10 a2 1d 48 vaddmac dm2, dm2, dm4, x0, ex7, r10
# CHECK: c: 10 ba 49 61 vaddmac dm0, dm0, dm7, x5, ex2, r11
# CHECK: 10: 10 82 01 fa vaddmac dm6, dm6, dm0, x8, ex0, r15
# CHECK: 14: 10 b2 99 35 vaddmac dm5, dm5, dm6, x6, ex6, r9
# CHECK: 18: 10 8a ad b2 vaddmac dm4, dm4, dm1, x10, ex11, r13
# CHECK: 1c: 10 aa 51 84 vaddmac dm1, dm1, dm5, x1, ex4, r12
# CHECK: 20: 10 92 d5 cd vaddmac dm3, dm3, dm2, x7, ex5, r14
# CHECK: 24: 10 9a 29 1d vaddmac dm7, dm7, dm3, x4, ex10, r8
# CHECK: 28: 10 a2 c5 48 vaddmac dm2, dm2, dm4, x3, ex1, r10
# CHECK: 2c: 10 ba 61 62 vaddmac dm0, dm0, dm7, x9, ex8, r11
# CHECK: 30: 10 6a 40 c0 vaddmac dm0, dm0, dm5, x1, ey0, r14
# CHECK: 34: 10 52 e8 fa vaddmac dm6, dm6, dm2, x11, ey5, r15
# CHECK: 38: 10 4a 90 bd vaddmac dm7, dm7, dm1, x6, ey2, r13
# CHECK: 3c: 10 42 48 11 vaddmac dm4, dm4, dm0, x5, ey1, r8
# CHECK: 40: 10 7a 58 6a vaddmac dm2, dm2, dm7, x9, ey3, r11
# CHECK: 44: 10 5a e0 4d vaddmac dm3, dm3, dm3, x7, ey4, r10
# CHECK: 48: 10 72 80 94 vaddmac dm5, dm5, dm6, x2, ey0, r12
# CHECK: 4c: 10 62 28 24 vaddmac dm1, dm1, dm4, x0, ey5, r9
# CHECK: 50: 10 6a 10 c2 vaddmac dm0, dm0, dm5, x8, ey2, r14
# CHECK: 54: 10 52 c8 f8 vaddmac dm6, dm6, dm2, x3, ey1, r15
# CHECK: 58: 10 4a 98 be vaddmac dm7, dm7, dm1, x10, ey3, r13
# CHECK: 5c: 10 42 20 11 vaddmac dm4, dm4, dm0, x4, ey4, r8
# CHECK: 60: 10 32 32 8d vaddmac dm3, dm3, dm6, x4, r12, r12
# CHECK: 64: 10 22 92 25 vaddmac dm1, dm1, dm4, x6, r4, r9
# CHECK: 68: 10 1a 8a c8 vaddmac dm2, dm2, dm3, x2, r2, r14
# CHECK: 6c: 10 02 96 52 vaddmac dm4, dm4, dm0, x10, r5, r10
# CHECK: 70: 10 12 6e 7a vaddmac dm6, dm6, dm2, x9, r11, r11
# CHECK: 74: 10 0a e6 a2 vaddmac dm0, dm0, dm1, x11, r9, r13
# CHECK: 78: 10 2a 5e 14 vaddmac dm5, dm5, dm5, x1, r7, r8
# CHECK: 7c: 10 3a fe fc vaddmac dm7, dm7, dm7, x3, r15, r15
# CHECK: 80: 10 32 6a 8d vaddmac dm3, dm3, dm6, x5, r10, r12
# CHECK: 84: 10 22 1a 24 vaddmac dm1, dm1, dm4, x0, r6, r9
# CHECK: 88: 10 1a 22 ca vaddmac dm2, dm2, dm3, x8, r8, r14
# CHECK: 8c: 10 02 ce 51 vaddmac dm4, dm4, dm0, x7, r3, r10
# CHECK: 90: 10 12 06 79 vaddmac dm6, dm6, dm2, x4, r1, r11
# CHECK: 94: 10 0a ba a1 vaddmac dm0, dm0, dm1, x6, r14, r13
# CHECK: 98: 10 2a 82 14 vaddmac dm5, dm5, dm5, x2, r0, r8
# CHECK: 9c: 10 3a b6 fe vaddmac dm7, dm7, dm7, x10, r13, r15
# CHECK: a0: 10 3a cc 9e vaddmac dm7, dm7, dm7, x11, x3, r12
# CHECK: a4: 10 0a 98 05 vaddmac dm1, dm1, dm1, x6, x6, r8
# CHECK: a8: 10 32 54 da vaddmac dm6, dm6, dm6, x9, x5, r14
# CHECK: ac: 10 12 48 a9 vaddmac dm2, dm2, dm2, x5, x2, r13
# CHECK: b0: 10 22 e8 51 vaddmac dm4, dm4, dm4, x7, x10, r10
# CHECK: b4: 10 2a c4 74 vaddmac dm5, dm5, dm5, x3, x1, r11
# CHECK: b8: 10 1a ac 2c vaddmac dm3, dm3, dm3, x2, x11, r9
# CHECK: bc: 10 02 10 e0 vaddmac dm0, dm0, dm0, x0, x4, r15
# CHECK: c0: 10 3a 60 9c vaddmac dm7, dm7, dm7, x1, x8, r12
# CHECK: c4: 10 0a 24 06 vaddmac dm1, dm1, dm1, x8, x9, r8
# CHECK: c8: 10 32 00 d9 vaddmac dm6, dm6, dm6, x4, x0, r14
# CHECK: cc: 10 12 9c aa vaddmac dm2, dm2, dm2, x10, x7, r13
# CHECK: d0: 10 ca c3 dc vaddmac dm7, dm7, dm1, x3, y0, r14
# CHECK: d4: 10 f2 a3 a8 vaddmac dm2, dm2, dm6, x2, y4, r13
# CHECK: d8: 10 e2 53 26 vaddmac dm1, dm1, dm4, x9, y2, r9
# CHECK: dc: 10 fa ab 92 vaddmac dm4, dm4, dm7, x10, y5, r12
# CHECK: e0: 10 ea 4b 54 vaddmac dm5, dm5, dm5, x1, y1, r10
# CHECK: e4: 10 c2 1b 18 vaddmac dm6, dm6, dm0, x0, y3, r8
# CHECK: e8: 10 da 03 ed vaddmac dm3, dm3, dm3, x4, y0, r15
# CHECK: ec: 10 d2 63 61 vaddmac dm0, dm0, dm2, x5, y4, r11
# CHECK: f0: 10 ca 93 dd vaddmac dm7, dm7, dm1, x6, y2, r14
# CHECK: f4: 10 f2 eb aa vaddmac dm2, dm2, dm6, x11, y5, r13
# CHECK: f8: 10 e2 cb 25 vaddmac dm1, dm1, dm4, x7, y1, r9
# CHECK: fc: 10 fa 1b 92 vaddmac dm4, dm4, dm7, x8, y3, r12
# CHECK: 100: 10 72 e1 51 vaddmac dm4, dm4, dm6, y3, ex8, r10
# CHECK: 104: 10 4a 4d 79 vaddmac dm6, dm6, dm1, y2, ex3, r11
# CHECK: 108: 10 52 c1 0e vaddmac dm3, dm3, dm2, y5, ex0, r8
# CHECK: 10c: 10 6a 69 d4 vaddmac dm5, dm5, dm5, y0, ex10, r14
# CHECK: 110: 10 5a 5d 3e vaddmac dm7, dm7, dm3, y4, ex7, r9
# CHECK: 114: 10 42 ed e0 vaddmac dm0, dm0, dm0, y1, ex11, r15
# CHECK: 118: 10 62 d5 a5 vaddmac dm1, dm1, dm4, y3, ex5, r13
# CHECK: 11c: 10 7a 45 89 vaddmac dm2, dm2, dm7, y2, ex1, r12
# CHECK: 120: 10 72 c9 52 vaddmac dm4, dm4, dm6, y5, ex2, r10
# CHECK: 124: 10 4a 65 78 vaddmac dm6, dm6, dm1, y0, ex9, r11
# CHECK: 128: 10 52 59 0e vaddmac dm3, dm3, dm2, y4, ex6, r8
# CHECK: 12c: 10 6a d1 d4 vaddmac dm5, dm5, dm5, y1, ex4, r14
# CHECK: 130: 10 5a a5 5d vaddmac dm7, dm7, dm3, y3, r9, r10
# CHECK: 134: 10 42 1d 99 vaddmac dm6, dm6, dm0, y2, r7, r12
# CHECK: 138: 10 52 11 e2 vaddmac dm0, dm0, dm2, y4, r4, r15
# CHECK: 13c: 10 4a ad 04 vaddmac dm1, dm1, dm1, y1, r11, r8
# CHECK: 140: 10 6a b9 b2 vaddmac dm4, dm4, dm5, y5, r14, r13
# CHECK: 144: 10 7a 01 d4 vaddmac dm5, dm5, dm7, y0, r0, r14
# CHECK: 148: 10 72 8d 6d vaddmac dm3, dm3, dm6, y3, r3, r11
# CHECK: 14c: 10 62 19 29 vaddmac dm2, dm2, dm4, y2, r6, r9
# CHECK: 150: 10 5a 21 5e vaddmac dm7, dm7, dm3, y4, r8, r10
# CHECK: 154: 10 42 bd 98 vaddmac dm6, dm6, dm0, y1, r15, r12
# CHECK: 158: 10 52 b5 e2 vaddmac dm0, dm0, dm2, y5, r13, r15
# CHECK: 15c: 10 4a 09 04 vaddmac dm1, dm1, dm1, y0, r2, r8
# CHECK: 160: 10 6a 95 b1 vaddmac dm4, dm4, dm5, y3, r5, r13
# CHECK: 164: 10 7a 31 d5 vaddmac dm5, dm5, dm7, y2, r12, r14
# CHECK: 168: 10 72 29 6e vaddmac dm3, dm3, dm6, y4, r10, r11
# CHECK: 16c: 10 62 85 28 vaddmac dm2, dm2, dm4, y1, r1, r9
# CHECK: 170: 10 4a e3 5a vaddmac dm6, dm6, dm1, y5, x8, r10
# CHECK: 174: 10 52 67 71 vaddmac dm4, dm4, dm2, y2, x9, r11
# CHECK: 178: 10 7a 4f 28 vaddmac dm2, dm2, dm7, y0, x3, r9
# CHECK: 17c: 10 6a d7 01 vaddmac dm0, dm0, dm5, y3, x5, r8
# CHECK: 180: 10 72 ef b4 vaddmac dm5, dm5, dm6, y1, x11, r13
# CHECK: 184: 10 42 4b 86 vaddmac dm1, dm1, dm0, y4, x2, r12
# CHECK: 188: 10 62 c7 ee vaddmac dm3, dm3, dm4, y5, x1, r15
# CHECK: 18c: 10 5a 5b dd vaddmac dm7, dm7, dm3, y2, x6, r14
# CHECK: 190: 10 4a 6b 58 vaddmac dm6, dm6, dm1, y0, x10, r10
# CHECK: 194: 10 52 c3 71 vaddmac dm4, dm4, dm2, y3, x0, r11
# CHECK: 198: 10 7a d3 28 vaddmac dm2, dm2, dm7, y1, x4, r9
# CHECK: 19c: 10 6a 5f 02 vaddmac dm0, dm0, dm5, y4, x7, r8
# CHECK: 1a0: 10 62 9a d9 vaddmac dm6, dm6, dm4, y3, y3, r14
# CHECK: 1a4: 10 5a 22 71 vaddmac dm4, dm4, dm3, y2, y4, r11
# CHECK: 1a8: 10 52 02 00 vaddmac dm0, dm0, dm2, y0, y0, r8
# CHECK: 1ac: 10 4a 8a b4 vaddmac dm5, dm5, dm1, y1, y1, r13
# CHECK: 1b0: 10 7a 12 ea vaddmac dm2, dm2, dm7, y4, y2, r15
# CHECK: 1b4: 10 42 aa 46 vaddmac dm1, dm1, dm0, y5, y5, r10
# CHECK: 1b8: 10 6a 9a 3d vaddmac dm7, dm7, dm5, y3, y3, r9
# CHECK: 1bc: 10 72 22 8d vaddmac dm3, dm3, dm6, y2, y4, r12
# CHECK: 1c0: 10 a2 0a 3e vaddmac cml7, cml7, cml4, x8, ex2,r9
# CHECK: 1c4: 10 b2 d6 f2 vaddmac cml4, cml4, cml6, x11, ex5,r15
# CHECK: 1c8: 10 92 5e 95 vaddmac cml5, cml5, cml2, x5, ex7,r12
# CHECK: 1cc: 10 aa 1a 69 vaddmac cml2, cml2, cml5, x4, ex6,r11
# CHECK: 1d0: 10 82 aa b9 vaddmac cml6, cml6, cml0, x6, ex10,r13
# CHECK: 1d4: 10 8a e6 4d vaddmac cml3, cml3, cml1, x7, ex9,r10
# CHECK: 1d8: 10 9a ae c0 vaddmac cml0, cml0, cml3, x2, ex11,r14
# CHECK: 1dc: 10 ba 62 06 vaddmac cml1, cml1, cml7, x9, ex8,r8
# CHECK: 1e0: 10 a2 02 3c vaddmac cml7, cml7, cml4, x0, ex0,r9
# CHECK: 1e4: 10 b2 86 f2 vaddmac cml4, cml4, cml6, x10, ex1,r15
# CHECK: 1e8: 10 92 ce 94 vaddmac cml5, cml5, cml2, x3, ex3,r12
# CHECK: 1ec: 10 aa 52 68 vaddmac cml2, cml2, cml5, x1, ex4,r11
# CHECK: 1f0: 10 da 85 65 vaddmac cml1, cml1, cml3, x6, r1,r11
# CHECK: 1f4: 10 d2 f1 a1 vaddmac cml0, cml0, cml2, x7, r12,r13
# CHECK: 1f8: 10 ca 59 89 vaddmac cml2, cml2, cml1, x5, r6,r12
# CHECK: 1fc: 10 e2 35 19 vaddmac cml6, cml6, cml4, x4, r13,r8
# CHECK: 200: 10 ea 8d 5c vaddmac cml7, cml7, cml5, x2, r3,r10
# CHECK: 204: 10 fa e1 d6 vaddmac cml5, cml5, cml7, x11, r8,r14
# CHECK: 208: 10 f2 25 ec vaddmac cml3, cml3, cml6, x0, r9,r15
# CHECK: 20c: 10 c2 79 32 vaddmac cml4, cml4, cml0, x9, r14,r9
# CHECK: 210: 10 da dd 64 vaddmac cml1, cml1, cml3, x3, r7,r11
# CHECK: 214: 10 d2 11 a2 vaddmac cml0, cml0, cml2, x8, r4,r13
# CHECK: 218: 10 ca 49 88 vaddmac cml2, cml2, cml1, x1, r2,r12
# CHECK: 21c: 10 e2 95 1a vaddmac cml6, cml6, cml4, x10, r5,r8
# CHECK: 220: 10 ea a9 5d vaddmac cml7, cml7, cml5, x6, r10,r10
# CHECK: 224: 10 fa ed d5 vaddmac cml5, cml5, cml7, x7, r11,r14
# CHECK: 228: 10 f2 7d ed vaddmac cml3, cml3, cml6, x5, r15,r15
# CHECK: 22c: 10 c2 01 31 vaddmac cml4, cml4, cml0, x4, r0,r9
# CHECK: 230: 10 ea 40 98 vaddmac cml6, cml6, cml5, x1, x0,r12
# CHECK: 234: 10 f2 14 e6 vaddmac cml1, cml1, cml6, x8, x5,r15
# CHECK: 238: 10 d2 a0 d5 vaddmac cml5, cml5, cml2, x6, x8,r14
# CHECK: 23c: 10 da 84 02 vaddmac cml0, cml0, cml3, x10, x1,r8
# CHECK: 240: 10 c2 ac 5c vaddmac cml7, cml7, cml0, x2, x11,r10
# CHECK: 244: 10 ca c8 68 vaddmac cml2, cml2, cml1, x3, x2,r11
# CHECK: 248: 10 fa 10 2c vaddmac cml3, cml3, cml7, x0, x4,r9
# CHECK: 24c: 10 e2 d8 b1 vaddmac cml4, cml4, cml4, x7, x6,r13
# CHECK: 250: 10 ea 24 99 vaddmac cml6, cml6, cml5, x4, x9,r12
# CHECK: 254: 10 f2 5c e5 vaddmac cml1, cml1, cml6, x5, x7,r15
# CHECK: 258: 10 d2 cc d6 vaddmac cml5, cml5, cml2, x11, x3,r14
# CHECK: 25c: 10 da 68 02 vaddmac cml0, cml0, cml3, x9, x10,r8
# CHECK: 260: 10 84 01 62 vaddmac dm0, dm0, scd[r31++], x8, ex0, r11
# CHECK: 264: 10 9c e9 fe vaddmac dm7, dm3, scd[r31++], x11, ex10, r15
# CHECK: 268: 10 ac 85 39 vaddmac dm6, dm5, scd[r31++], x6, ex1, r9
# CHECK: 26c: 10 8c ad 4a vaddmac dm2, dm1, scd[r31++], x10, ex11, r10
# CHECK: 270: 10 94 11 d1 vaddmac dm4, dm2, scd[r31++], x4, ex4, r14
# CHECK: 274: 10 b4 dd 8c vaddmac dm3, dm6, scd[r31++], x3, ex7, r12
# CHECK: 278: 10 a4 99 04 vaddmac dm1, dm4, scd[r31++], x2, ex6, r8
# CHECK: 27c: 10 bc 49 b5 vaddmac dm5, dm7, scd[r31++], x5, ex2, r13
# CHECK: 280: 10 84 15 60 vaddmac dm0, dm0, scd[r31++], x0, ex5, r11
# CHECK: 284: 10 9c 61 fe vaddmac dm7, dm3, scd[r31++], x9, ex8, r15
# CHECK: 288: 10 ac 65 38 vaddmac dm6, dm5, scd[r31++], x1, ex9, r9
# CHECK: 28c: 10 8c cd 49 vaddmac dm2, dm1, scd[r31++], x7, ex3, r10
# CHECK: 290: 10 7c e8 be vaddmac dm7, dm7, scd[r31++], x11, ey5, r13
# CHECK: 294: 10 5c 48 49 vaddmac dm2, dm3, scd[r31++], x5, ey1, r10
# CHECK: 298: 10 44 80 c1 vaddmac dm0, dm0, scd[r31++], x6, ey0, r14
# CHECK: 29c: 10 54 98 12 vaddmac dm4, dm2, scd[r31++], x10, ey3, r8
# CHECK: 2a0: 10 64 50 26 vaddmac dm1, dm4, scd[r31++], x9, ey2, r9
# CHECK: 2a4: 10 6c 60 8c vaddmac dm3, dm5, scd[r31++], x1, ey4, r12
# CHECK: 2a8: 10 4c e8 79 vaddmac dm6, dm1, scd[r31++], x7, ey5, r11
# CHECK: 2ac: 10 74 08 f6 vaddmac dm5, dm6, scd[r31++], x8, ey1, r15
# CHECK: 2b0: 10 7c 00 bd vaddmac dm7, dm7, scd[r31++], x4, ey0, r13
# CHECK: 2b4: 10 5c 98 48 vaddmac dm2, dm3, scd[r31++], x2, ey3, r10
# CHECK: 2b8: 10 44 d0 c0 vaddmac dm0, dm0, scd[r31++], x3, ey2, r14
# CHECK: 2bc: 10 54 20 10 vaddmac dm4, dm2, scd[r31++], x0, ey4, r8
# CHECK: 2c0: 10 3c 8e 7d vaddmac dm7, dm7, scd[r31++], x6, r3, r11
# CHECK: 2c4: 10 34 92 4c vaddmac dm3, dm6, scd[r31++], x2, r4, r10
# CHECK: 2c8: 10 04 66 fa vaddmac dm6, dm0, scd[r31++], x9, r9, r15
# CHECK: 2cc: 10 1c b2 aa vaddmac dm2, dm3, scd[r31++], x10, r12, r13
# CHECK: 2d0: 10 24 76 14 vaddmac dm5, dm4, scd[r31++], x1, r13, r8
# CHECK: 2d4: 10 0c 3a 20 vaddmac dm0, dm1, scd[r31++], x0, r14, r9
# CHECK: 2d8: 10 2c fe 92 vaddmac dm4, dm5, scd[r31++], x11, r15, r12
# CHECK: 2dc: 10 14 de c4 vaddmac dm1, dm2, scd[r31++], x3, r7, r14
# CHECK: 2e0: 10 3c 1a 7d vaddmac dm7, dm7, scd[r31++], x4, r6, r11
# CHECK: 2e4: 10 34 06 4e vaddmac dm3, dm6, scd[r31++], x8, r1, r10
# CHECK: 2e8: 10 04 42 f9 vaddmac dm6, dm0, scd[r31++], x5, r0, r15
# CHECK: 2ec: 10 1c d6 a9 vaddmac dm2, dm3, scd[r31++], x7, r5, r13
# CHECK: 2f0: 10 24 8a 15 vaddmac dm5, dm4, scd[r31++], x6, r2, r8
# CHECK: 2f4: 10 0c aa 20 vaddmac dm0, dm1, scd[r31++], x2, r10, r9
# CHECK: 2f8: 10 2c 6e 92 vaddmac dm4, dm5, scd[r31++], x9, r11, r12
# CHECK: 2fc: 10 14 a2 c6 vaddmac dm1, dm2, scd[r31++], x10, r8, r14
# CHECK: 300: 10 0c 68 04 vaddmac dm1, dm1, scd[r31++], x1, x10, r8
# CHECK: 304: 10 24 9c e0 vaddmac dm0, dm4, scd[r31++], x2, x7, r15
# CHECK: 308: 10 1c 44 ad vaddmac dm3, dm3, scd[r31++], x5, x1, r13
# CHECK: 30c: 10 14 00 72 vaddmac dm4, dm2, scd[r31++], x8, x0, r11
# CHECK: 310: 10 04 a0 3d vaddmac dm7, dm0, scd[r31++], x6, x8, r9
# CHECK: 314: 10 34 ec 56 vaddmac dm5, dm6, scd[r31++], x11, x11, r10
# CHECK: 318: 10 2c e4 c9 vaddmac dm2, dm5, scd[r31++], x7, x9, r14
# CHECK: 31c: 10 3c 98 9a vaddmac dm6, dm7, scd[r31++], x10, x6, r12
# CHECK: 320: 10 0c cc 04 vaddmac dm1, dm1, scd[r31++], x3, x3, r8
# CHECK: 324: 10 24 54 e2 vaddmac dm0, dm4, scd[r31++], x9, x5, r15
# CHECK: 328: 10 1c 10 ac vaddmac dm3, dm3, scd[r31++], x0, x4, r13
# CHECK: 32c: 10 14 08 71 vaddmac dm4, dm2, scd[r31++], x4, x2, r11
# CHECK: 330: 10 c4 9b b4 vaddmac dm5, dm0, scd[r31++], x2, y3, r13
# CHECK: 334: 10 fc eb 79 vaddmac dm6, dm7, scd[r31++], x7, y5, r11
# CHECK: 338: 10 dc 8b 01 vaddmac dm0, dm3, scd[r31++], x6, y1, r8
# CHECK: 33c: 10 f4 63 c4 vaddmac dm1, dm6, scd[r31++], x1, y4, r14
# CHECK: 340: 10 e4 83 2a vaddmac dm2, dm4, scd[r31++], x10, y0, r9
# CHECK: 344: 10 d4 13 90 vaddmac dm4, dm2, scd[r31++], x0, y2, r12
# CHECK: 348: 10 ec 5b 4e vaddmac dm3, dm5, scd[r31++], x9, y3, r10
# CHECK: 34c: 10 cc 6b fd vaddmac dm7, dm1, scd[r31++], x5, y5, r15
# CHECK: 350: 10 c4 cb b6 vaddmac dm5, dm0, scd[r31++], x11, y1, r13
# CHECK: 354: 10 fc e3 78 vaddmac dm6, dm7, scd[r31++], x3, y4, r11
# CHECK: 358: 10 dc 03 02 vaddmac dm0, dm3, scd[r31++], x8, y0, r8
# CHECK: 35c: 10 f4 13 c5 vaddmac dm1, dm6, scd[r31++], x4, y2, r14
# CHECK: 360: 10 44 49 3e vaddmac dm7, dm0, scd[r31++], y4, ex2, r9
# CHECK: 364: 10 7c c1 f9 vaddmac dm6, dm7, scd[r31++], y3, ex0, r15
# CHECK: 368: 10 5c e1 6a vaddmac dm2, dm3, scd[r31++], y5, ex8, r11
# CHECK: 36c: 10 4c 45 00 vaddmac dm0, dm1, scd[r31++], y0, ex1, r8
# CHECK: 370: 10 54 cd 90 vaddmac dm4, dm2, scd[r31++], y1, ex3, r12
# CHECK: 374: 10 6c 69 45 vaddmac dm1, dm5, scd[r31++], y2, ex10, r10
# CHECK: 378: 10 74 51 ce vaddmac dm3, dm6, scd[r31++], y4, ex4, r14
# CHECK: 37c: 10 64 d5 b5 vaddmac dm5, dm4, scd[r31++], y3, ex5, r13
# CHECK: 380: 10 44 dd 3e vaddmac dm7, dm0, scd[r31++], y5, ex7, r9
# CHECK: 384: 10 7c 59 f8 vaddmac dm6, dm7, scd[r31++], y0, ex6, r15
# CHECK: 388: 10 5c ed 68 vaddmac dm2, dm3, scd[r31++], y1, ex11, r11
# CHECK: 38c: 10 4c 65 01 vaddmac dm0, dm1, scd[r31++], y2, ex9, r8
# CHECK: 390: 10 5c 21 8e vaddmac dm3, dm3, scd[r31++], y4, r8, r12
# CHECK: 394: 10 7c 91 79 vaddmac dm6, dm7, scd[r31++], y3, r4, r11
# CHECK: 398: 10 4c a5 b2 vaddmac dm4, dm1, scd[r31++], y5, r9, r13
# CHECK: 39c: 10 6c 05 40 vaddmac dm0, dm5, scd[r31++], y0, r1, r10
# CHECK: 3a0: 10 54 39 e5 vaddmac dm1, dm2, scd[r31++], y2, r14, r15
# CHECK: 3a4: 10 44 95 3c vaddmac dm7, dm0, scd[r31++], y1, r5, r9
# CHECK: 3a8: 10 74 09 ca vaddmac dm2, dm6, scd[r31++], y4, r2, r14
# CHECK: 3ac: 10 64 bd 15 vaddmac dm5, dm4, scd[r31++], y3, r15, r8
# CHECK: 3b0: 10 5c 8d 8e vaddmac dm3, dm3, scd[r31++], y5, r3, r12
# CHECK: 3b4: 10 7c 01 78 vaddmac dm6, dm7, scd[r31++], y0, r0, r11
# CHECK: 3b8: 10 4c 35 b1 vaddmac dm4, dm1, scd[r31++], y2, r13, r13
# CHECK: 3bc: 10 6c b1 40 vaddmac dm0, dm5, scd[r31++], y1, r12, r10
# CHECK: 3c0: 10 54 19 e6 vaddmac dm1, dm2, scd[r31++], y4, r6, r15
# CHECK: 3c4: 10 44 ad 3d vaddmac dm7, dm0, scd[r31++], y3, r11, r9
# CHECK: 3c8: 10 74 9d ca vaddmac dm2, dm6, scd[r31++], y5, r7, r14
# CHECK: 3cc: 10 64 29 14 vaddmac dm5, dm4, scd[r31++], y0, r10, r8
# CHECK: 3d0: 10 7c eb 89 vaddmac dm2, dm7, scd[r31++], y3, x10, r12
# CHECK: 3d4: 10 44 df fe vaddmac dm7, dm0, scd[r31++], y5, x7, r15
# CHECK: 3d8: 10 64 43 d6 vaddmac dm5, dm4, scd[r31++], y4, x0, r14
# CHECK: 3dc: 10 74 6f ad vaddmac dm3, dm6, scd[r31++], y2, x11, r13
# CHECK: 3e0: 10 6c 47 24 vaddmac dm1, dm5, scd[r31++], y0, x1, r9
# CHECK: 3e4: 10 54 e7 40 vaddmac dm0, dm2, scd[r31++], y1, x9, r10
# CHECK: 3e8: 10 4c e3 19 vaddmac dm6, dm1, scd[r31++], y3, x8, r8
# CHECK: 3ec: 10 5c d7 72 vaddmac dm4, dm3, scd[r31++], y5, x5, r11
# CHECK: 3f0: 10 7c 5b 8a vaddmac dm2, dm7, scd[r31++], y4, x6, r12
# CHECK: 3f4: 10 44 4f fd vaddmac dm7, dm0, scd[r31++], y2, x3, r15
# CHECK: 3f8: 10 64 4b d4 vaddmac dm5, dm4, scd[r31++], y0, x2, r14
# CHECK: 3fc: 10 74 d3 ac vaddmac dm3, dm6, scd[r31++], y1, x4, r13
# CHECK: 400: 10 44 1a 0a vaddmac dm2, dm0, scd[r31++], y4, y3, r8
# CHECK: 404: 10 7c 92 34 vaddmac dm5, dm7, scd[r31++], y1, y2, r9
# CHECK: 408: 10 54 aa 41 vaddmac dm0, dm2, scd[r31++], y3, y5, r10
# CHECK: 40c: 10 64 82 b2 vaddmac dm4, dm4, scd[r31++], y5, y0, r13
# CHECK: 410: 10 4c 22 78 vaddmac dm6, dm1, scd[r31++], y0, y4, r11
# CHECK: 414: 10 74 0a dd vaddmac dm7, dm6, scd[r31++], y2, y1, r14
# CHECK: 418: 10 6c 1a ee vaddmac dm3, dm5, scd[r31++], y4, y3, r15
# CHECK: 41c: 10 5c 92 84 vaddmac dm1, dm3, scd[r31++], y1, y2, r12
# CHECK: 420: 10 83 65 3c vaddmac dm7, dm0, scd[r31], x1, ex9, r9
# CHECK: 424: 10 b3 11 86 vaddmac dm1, dm6, scd[r31], x8, ex4, r12
# CHECK: 428: 10 bb 85 74 vaddmac dm5, dm7, scd[r31], x2, ex1, r11
# CHECK: 42c: 10 9b 61 a1 vaddmac dm0, dm3, scd[r31], x5, ex8, r13
# CHECK: 430: 10 a3 41 f2 vaddmac dm4, dm4, scd[r31], x9, ex0, r15
# CHECK: 434: 10 ab cd 5a vaddmac dm6, dm5, scd[r31], x11, ex3, r10
# CHECK: 438: 10 93 09 0c vaddmac dm3, dm2, scd[r31], x0, ex2, r8
# CHECK: 43c: 10 8b dd c9 vaddmac dm2, dm1, scd[r31], x7, ex7, r14
# CHECK: 440: 10 83 2d 3d vaddmac dm7, dm0, scd[r31], x4, ex11, r9
# CHECK: 444: 10 b3 d5 84 vaddmac dm1, dm6, scd[r31], x3, ex5, r12
# CHECK: 448: 10 bb a9 76 vaddmac dm5, dm7, scd[r31], x10, ex10, r11
# CHECK: 44c: 10 9b 99 a1 vaddmac dm0, dm3, scd[r31], x6, ex6, r13
# CHECK: 450: 10 43 58 cc vaddmac dm3, dm0, scd[r31], x1, ey3, r14
# CHECK: 454: 10 73 c8 71 vaddmac dm4, dm6, scd[r31], x7, ey1, r11
# CHECK: 458: 10 53 10 a2 vaddmac dm0, dm2, scd[r31], x8, ey2, r13
# CHECK: 45c: 10 6b a0 e6 vaddmac dm1, dm5, scd[r31], x10, ey4, r15
# CHECK: 460: 10 63 80 1d vaddmac dm7, dm4, scd[r31], x6, ey0, r8
# CHECK: 464: 10 7b 68 3a vaddmac dm6, dm7, scd[r31], x9, ey5, r9
# CHECK: 468: 10 4b 18 55 vaddmac dm5, dm1, scd[r31], x4, ey3, r10
# CHECK: 46c: 10 5b c8 88 vaddmac dm2, dm3, scd[r31], x3, ey1, r12
# CHECK: 470: 10 43 10 cc vaddmac dm3, dm0, scd[r31], x0, ey2, r14
# CHECK: 474: 10 73 60 71 vaddmac dm4, dm6, scd[r31], x5, ey4, r11
# CHECK: 478: 10 53 c0 a2 vaddmac dm0, dm2, scd[r31], x11, ey0, r13
# CHECK: 47c: 10 6b a8 e4 vaddmac dm1, dm5, scd[r31], x2, ey5, r15
# CHECK: 480: 10 3b 5a 94 vaddmac dm5, dm7, scd[r31], x1, r6, r12
# CHECK: 484: 10 33 ea 52 vaddmac dm4, dm6, scd[r31], x11, r10, r10
# CHECK: 488: 10 1b d2 b9 vaddmac dm6, dm3, scd[r31], x7, r4, r13
# CHECK: 48c: 10 23 96 dc vaddmac dm7, dm4, scd[r31], x2, r5, r14
# CHECK: 490: 10 03 ee 20 vaddmac dm0, dm0, scd[r31], x3, r11, r9
# CHECK: 494: 10 13 32 e8 vaddmac dm2, dm2, scd[r31], x0, r12, r15
# CHECK: 498: 10 0b 76 0d vaddmac dm3, dm1, scd[r31], x5, r13, r8
# CHECK: 49c: 10 2b 8a 66 vaddmac dm1, dm5, scd[r31], x10, r2, r11
# CHECK: 4a0: 10 3b 7e 96 vaddmac dm5, dm7, scd[r31], x9, r15, r12
# CHECK: 4a4: 10 33 1e 52 vaddmac dm4, dm6, scd[r31], x8, r7, r10
# CHECK: 4a8: 10 1b 06 b9 vaddmac dm6, dm3, scd[r31], x4, r1, r13
# CHECK: 4ac: 10 23 82 dd vaddmac dm7, dm4, scd[r31], x6, r0, r14
# CHECK: 4b0: 10 03 66 20 vaddmac dm0, dm0, scd[r31], x1, r9, r9
# CHECK: 4b4: 10 13 e2 ea vaddmac dm2, dm2, scd[r31], x11, r8, r15
# CHECK: 4b8: 10 0b ce 0d vaddmac dm3, dm1, scd[r31], x7, r3, r8
# CHECK: 4bc: 10 2b ba 64 vaddmac dm1, dm5, scd[r31], x2, r14, r11
# CHECK: 4c0: 10 13 60 7c vaddmac dm7, dm2, scd[r31], x1, x8, r11
# CHECK: 4c4: 10 33 8c 96 vaddmac dm5, dm6, scd[r31], x10, x3, r12
# CHECK: 4c8: 10 23 1c b2 vaddmac dm4, dm4, scd[r31], x8, x7, r13
# CHECK: 4cc: 10 2b 54 2a vaddmac dm2, dm5, scd[r31], x9, x5, r9
# CHECK: 4d0: 10 3b d0 fa vaddmac dm6, dm7, scd[r31], x11, x4, r15
# CHECK: 4d4: 10 1b c0 4c vaddmac dm3, dm3, scd[r31], x3, x0, r10
# CHECK: 4d8: 10 0b 58 05 vaddmac dm1, dm1, scd[r31], x5, x6, r8
# CHECK: 4dc: 10 03 84 c1 vaddmac dm0, dm0, scd[r31], x6, x1, r14
# CHECK: 4e0: 10 13 c8 7d vaddmac dm7, dm2, scd[r31], x7, x2, r11
# CHECK: 4e4: 10 33 28 94 vaddmac dm5, dm6, scd[r31], x0, x10, r12
# CHECK: 4e8: 10 23 24 b1 vaddmac dm4, dm4, scd[r31], x4, x9, r13
# CHECK: 4ec: 10 2b ac 28 vaddmac dm2, dm5, scd[r31], x2, x11, r9
# CHECK: 4f0: 10 fb d3 71 vaddmac dm4, dm7, scd[r31], x7, y2, r11
# CHECK: 4f4: 10 d3 8b b4 vaddmac dm5, dm2, scd[r31], x2, y1, r13
# CHECK: 4f8: 10 f3 9b 5e vaddmac dm7, dm6, scd[r31], x10, y3, r10
# CHECK: 4fc: 10 e3 03 09 vaddmac dm2, dm4, scd[r31], x4, y0, r8
# CHECK: 500: 10 cb eb e6 vaddmac dm1, dm1, scd[r31], x11, y5, r15
# CHECK: 504: 10 c3 63 da vaddmac dm6, dm0, scd[r31], x9, y4, r14
# CHECK: 508: 10 eb 13 80 vaddmac dm0, dm5, scd[r31], x0, y2, r12
# CHECK: 50c: 10 db cb 2c vaddmac dm3, dm3, scd[r31], x3, y1, r9
# CHECK: 510: 10 fb 5b 71 vaddmac dm4, dm7, scd[r31], x5, y3, r11
# CHECK: 514: 10 d3 83 b5 vaddmac dm5, dm2, scd[r31], x6, y0, r13
# CHECK: 518: 10 f3 6b 5c vaddmac dm7, dm6, scd[r31], x1, y5, r10
# CHECK: 51c: 10 e3 23 0a vaddmac dm2, dm4, scd[r31], x8, y4, r8
# CHECK: 520: 10 5b 41 fe vaddmac dm7, dm3, scd[r31], y4, ex0, r15
# CHECK: 524: 10 4b c5 38 vaddmac dm6, dm1, scd[r31], y1, ex1, r9
# CHECK: 528: 10 7b e1 01 vaddmac dm0, dm7, scd[r31], y3, ex8, r8
# CHECK: 52c: 10 63 55 6c vaddmac dm3, dm4, scd[r31], y0, ex5, r11
# CHECK: 530: 10 53 59 51 vaddmac dm4, dm2, scd[r31], y2, ex6, r10
# CHECK: 534: 10 43 c9 c6 vaddmac dm1, dm0, scd[r31], y5, ex2, r14
# CHECK: 538: 10 6b 4d b6 vaddmac dm5, dm5, scd[r31], y4, ex3, r13
# CHECK: 53c: 10 73 ed 88 vaddmac dm2, dm6, scd[r31], y1, ex11, r12
# CHECK: 540: 10 5b e5 fd vaddmac dm7, dm3, scd[r31], y3, ex9, r15
# CHECK: 544: 10 4b 69 38 vaddmac dm6, dm1, scd[r31], y0, ex10, r9
# CHECK: 548: 10 7b 5d 01 vaddmac dm0, dm7, scd[r31], y2, ex7, r8
# CHECK: 54c: 10 63 d1 6e vaddmac dm3, dm4, scd[r31], y5, ex4, r11
# CHECK: 550: 10 63 bd 0d vaddmac dm3, dm4, scd[r31], y3, r15, r8
# CHECK: 554: 10 53 39 9d vaddmac dm7, dm2, scd[r31], y2, r14, r12
# CHECK: 558: 10 7b 91 c8 vaddmac dm2, dm7, scd[r31], y1, r4, r14
# CHECK: 55c: 10 6b 81 3a vaddmac dm6, dm5, scd[r31], y5, r0, r9
# CHECK: 560: 10 73 1d 76 vaddmac dm5, dm6, scd[r31], y4, r7, r11
# CHECK: 564: 10 4b 31 a0 vaddmac dm0, dm1, scd[r31], y0, r12, r13
# CHECK: 568: 10 5b 95 e5 vaddmac dm1, dm3, scd[r31], y3, r5, r15
# CHECK: 56c: 10 43 09 51 vaddmac dm4, dm0, scd[r31], y2, r2, r10
# CHECK: 570: 10 63 a1 0c vaddmac dm3, dm4, scd[r31], y1, r8, r8
# CHECK: 574: 10 53 ad 9e vaddmac dm7, dm2, scd[r31], y5, r11, r12
# CHECK: 578: 10 7b 0d ca vaddmac dm2, dm7, scd[r31], y4, r3, r14
# CHECK: 57c: 10 6b 05 38 vaddmac dm6, dm5, scd[r31], y0, r1, r9
# CHECK: 580: 10 73 99 75 vaddmac dm5, dm6, scd[r31], y3, r6, r11
# CHECK: 584: 10 4b 29 a1 vaddmac dm0, dm1, scd[r31], y2, r10, r13
# CHECK: 588: 10 5b a5 e4 vaddmac dm1, dm3, scd[r31], y1, r9, r15
# CHECK: 58c: 10 43 b5 52 vaddmac dm4, dm0, scd[r31], y5, r13, r10
# CHECK: 590: 10 63 cf 88 vaddmac dm2, dm4, scd[r31], y1, x3, r12
# CHECK: 594: 10 6b db 56 vaddmac dm5, dm5, scd[r31], y5, x6, r10
# CHECK: 598: 10 4b 63 30 vaddmac dm4, dm1, scd[r31], y0, x8, r9
# CHECK: 59c: 10 5b 53 c6 vaddmac dm1, dm3, scd[r31], y4, x4, r14
# CHECK: 5a0: 10 53 4b fd vaddmac dm7, dm2, scd[r31], y2, x2, r15
# CHECK: 5a4: 10 73 e7 61 vaddmac dm0, dm6, scd[r31], y3, x9, r11
# CHECK: 5a8: 10 43 df ac vaddmac dm3, dm0, scd[r31], y1, x7, r13
# CHECK: 5ac: 10 7b eb 1a vaddmac dm6, dm7, scd[r31], y5, x10, r8
# CHECK: 5b0: 10 63 6f 88 vaddmac dm2, dm4, scd[r31], y0, x11, r12
# CHECK: 5b4: 10 6b 47 56 vaddmac dm5, dm5, scd[r31], y4, x1, r10
# CHECK: 5b8: 10 4b 43 31 vaddmac dm4, dm1, scd[r31], y2, x0, r9
# CHECK: 5bc: 10 5b d7 c5 vaddmac dm1, dm3, scd[r31], y3, x5, r14
# CHECK: 5c0: 10 43 12 69 vaddmac dm2, dm0, scd[r31], y2, y2, r11
# CHECK: 5c4: 10 53 1a 10 vaddmac dm4, dm2, scd[r31], y0, y3, r8
# CHECK: 5c8: 10 5b aa ae vaddmac dm3, dm3, scd[r31], y5, y5, r13
# CHECK: 5cc: 10 4b 02 d6 vaddmac dm5, dm1, scd[r31], y4, y0, r14
# CHECK: 5d0: 10 73 8a 80 vaddmac dm0, dm6, scd[r31], y1, y1, r12
# CHECK: 5d4: 10 7b a2 3d vaddmac dm7, dm7, scd[r31], y3, y4, r9
# CHECK: 5d8: 10 63 12 45 vaddmac dm1, dm4, scd[r31], y2, y2, r10
# CHECK: 5dc: 10 6b 1a f8 vaddmac dm6, dm5, scd[r31], y0, y3, r15
# CHECK: 5e0: 10 a4 12 cd vaddmac cml3, cml4, scd[r31++], x4, ex4, r14
# CHECK: 5e4: 10 ac de e1 vaddmac cml0, cml5, scd[r31++], x7, ex7, r15
# CHECK: 5e8: 10 bc 8e 18 vaddmac cml6, cml7, scd[r31++], x2, ex3, r8
# CHECK: 5ec: 10 84 5a b0 vaddmac cml4, cml0, scd[r31++], x1, ex6, r13
# CHECK: 5f0: 10 8c 16 76 vaddmac cml5, cml1, scd[r31++], x8, ex5, r11
# CHECK: 5f4: 10 94 42 49 vaddmac cml2, cml2, scd[r31++], x5, ex0, r10
# CHECK: 5f8: 10 9c 86 3e vaddmac cml7, cml3, scd[r31++], x10, ex1, r9
# CHECK: 5fc: 10 b4 a6 85 vaddmac cml1, cml6, scd[r31++], x6, ex9, r12
# CHECK: 600: 10 a4 6a ce vaddmac cml3, cml4, scd[r31++], x9, ex10, r14
# CHECK: 604: 10 ac 0a e0 vaddmac cml0, cml5, scd[r31++], x0, ex2, r15
# CHECK: 608: 10 bc ee 18 vaddmac cml6, cml7, scd[r31++], x3, ex11, r8
# CHECK: 60c: 10 84 e2 b2 vaddmac cml4, cml0, scd[r31++], x11, ex8, r13
# CHECK: 610: 10 e4 fd 50 vaddmac cml4, cml4, scd[r31++], x3, r15, r10
# CHECK: 614: 10 dc 01 d5 vaddmac cml5, cml3, scd[r31++], x4, r0, r14
# CHECK: 618: 10 ec e1 62 vaddmac cml0, cml5, scd[r31++], x11, r8, r11
# CHECK: 61c: 10 fc 79 3d vaddmac cml7, cml7, scd[r31++], x5, r14, r9
# CHECK: 620: 10 cc 8d 0c vaddmac cml3, cml1, scd[r31++], x2, r3, r8
# CHECK: 624: 10 d4 09 98 vaddmac cml6, cml2, scd[r31++], x0, r2, r12
# CHECK: 628: 10 f4 ed e9 vaddmac cml2, cml6, scd[r31++], x7, r11, r15
# CHECK: 62c: 10 c4 69 a6 vaddmac cml1, cml0, scd[r31++], x9, r10, r13
# CHECK: 630: 10 e4 91 52 vaddmac cml4, cml4, scd[r31++], x10, r4, r10
# CHECK: 634: 10 dc 35 d6 vaddmac cml5, cml3, scd[r31++], x8, r13, r14
# CHECK: 638: 10 ec 71 60 vaddmac cml0, cml5, scd[r31++], x1, r12, r11
# CHECK: 63c: 10 fc 85 3d vaddmac cml7, cml7, scd[r31++], x6, r1, r9
# CHECK: 640: 10 cc e5 0c vaddmac cml3, cml1, scd[r31++], x3, r9, r8
# CHECK: 644: 10 d4 15 99 vaddmac cml6, cml2, scd[r31++], x4, r5, r12
# CHECK: 648: 10 f4 d9 ea vaddmac cml2, cml6, scd[r31++], x11, r6, r15
# CHECK: 64c: 10 c4 5d a5 vaddmac cml1, cml0, scd[r31++], x5, r7, r13
# CHECK: 650: 10 c4 9c 48 vaddmac cml2, cml0, scd[r31++], x2, x7, r10
# CHECK: 654: 10 fc 84 b5 vaddmac cml5, cml7, scd[r31++], x6, x1, r13
# CHECK: 658: 10 ec c8 d2 vaddmac cml4, cml5, scd[r31++], x11, x2, r14
# CHECK: 65c: 10 dc 58 fc vaddmac cml7, cml3, scd[r31++], x1, x6, r15
# CHECK: 660: 10 f4 14 20 vaddmac cml0, cml6, scd[r31++], x0, x5, r9
# CHECK: 664: 10 cc e4 8d vaddmac cml3, cml1, scd[r31++], x7, x9, r12
# CHECK: 668: 10 d4 0c 79 vaddmac cml6, cml2, scd[r31++], x4, x3, r11
# CHECK: 66c: 10 e4 e0 04 vaddmac cml1, cml4, scd[r31++], x3, x8, r8
# CHECK: 670: 10 c4 00 4a vaddmac cml2, cml0, scd[r31++], x8, x0, r10
# CHECK: 674: 10 fc 68 b5 vaddmac cml5, cml7, scd[r31++], x5, x10, r13
# CHECK: 678: 10 ec ac d2 vaddmac cml4, cml5, scd[r31++], x10, x11, r14
# CHECK: 67c: 10 dc 50 fe vaddmac cml7, cml3, scd[r31++], x9, x4, r15
# CHECK: 680: 10 9b 6e 05 vaddmac cml1, cml3, scd[r31], x5, ex11, r8
# CHECK: 684: 10 93 e2 75 vaddmac cml5, cml2, scd[r31], x7, ex8, r11
# CHECK: 688: 10 ab 2a 88 vaddmac cml2, cml5, scd[r31], x0, ex10, r12
# CHECK: 68c: 10 8b c2 4e vaddmac cml3, cml1, scd[r31], x11, ex0, r10
# CHECK: 690: 10 a3 66 3e vaddmac cml7, cml4, scd[r31], x9, ex9, r9
# CHECK: 694: 10 bb 06 e1 vaddmac cml0, cml7, scd[r31], x4, ex1, r15
# CHECK: 698: 10 b3 9a b2 vaddmac cml4, cml6, scd[r31], x10, ex6, r13
# CHECK: 69c: 10 83 ca d8 vaddmac cml6, cml0, scd[r31], x3, ex2, r14
# CHECK: 6a0: 10 9b 4e 04 vaddmac cml1, cml3, scd[r31], x1, ex3, r8
# CHECK: 6a4: 10 93 96 74 vaddmac cml5, cml2, scd[r31], x2, ex5, r11
# CHECK: 6a8: 10 ab 12 8a vaddmac cml2, cml5, scd[r31], x8, ex4, r12
# CHECK: 6ac: 10 8b 9e 4d vaddmac cml3, cml1, scd[r31], x6, ex7, r10
# CHECK: 6b0: 10 d3 c5 b0 vaddmac cml4, cml2, scd[r31], x3, r1, r13
# CHECK: 6b4: 10 e3 11 8d vaddmac cml3, cml4, scd[r31], x4, r4, r12
# CHECK: 6b8: 10 fb e5 c2 vaddmac cml0, cml7, scd[r31], x11, r9, r14
# CHECK: 6bc: 10 f3 d5 55 vaddmac cml5, cml6, scd[r31], x7, r5, r10
# CHECK: 6c0: 10 cb 0d ea vaddmac cml2, cml1, scd[r31], x8, r3, r15
# CHECK: 6c4: 10 eb 69 19 vaddmac cml6, cml5, scd[r31], x5, r10, r8
# CHECK: 6c8: 10 c3 39 64 vaddmac cml1, cml0, scd[r31], x0, r14, r11
# CHECK: 6cc: 10 db 9d 3d vaddmac cml7, cml3, scd[r31], x6, r7, r9
# CHECK: 6d0: 10 d3 81 b2 vaddmac cml4, cml2, scd[r31], x10, r0, r13
# CHECK: 6d4: 10 e3 bd 8c vaddmac cml3, cml4, scd[r31], x2, r15, r12
# CHECK: 6d8: 10 fb 6d c0 vaddmac cml0, cml7, scd[r31], x1, r11, r14
# CHECK: 6dc: 10 f3 49 56 vaddmac cml5, cml6, scd[r31], x9, r2, r10
# CHECK: 6e0: 10 cb f5 e8 vaddmac cml2, cml1, scd[r31], x3, r13, r15
# CHECK: 6e4: 10 eb 21 19 vaddmac cml6, cml5, scd[r31], x4, r8, r8
# CHECK: 6e8: 10 c3 f1 66 vaddmac cml1, cml0, scd[r31], x11, r12, r11
# CHECK: 6ec: 10 db d9 3d vaddmac cml7, cml3, scd[r31], x7, r6, r9
# CHECK: 6f0: 10 db 14 95 vaddmac cml5, cml3, scd[r31], x4, x5, r12
# CHECK: 6f4: 10 d3 e8 25 vaddmac cml1, cml2, scd[r31], x7, x10, r9
# CHECK: 6f8: 10 cb d8 08 vaddmac cml2, cml1, scd[r31], x3, x6, r8
# CHECK: 6fc: 10 e3 a4 78 vaddmac cml6, cml4, scd[r31], x2, x9, r11
# CHECK: 700: 10 fb 90 52 vaddmac cml4, cml7, scd[r31], x10, x4, r10
# CHECK: 704: 10 eb 5c e2 vaddmac cml0, cml5, scd[r31], x9, x7, r15
# CHECK: 708: 10 f3 48 dd vaddmac cml7, cml6, scd[r31], x5, x2, r14
# CHECK: 70c: 10 c3 20 ac vaddmac cml3, cml0, scd[r31], x0, x8, r13
# CHECK: 710: 10 db 0c 96 vaddmac cml5, cml3, scd[r31], x8, x3, r12
# CHECK: 714: 10 d3 84 25 vaddmac cml1, cml2, scd[r31], x6, x1, r9
# CHECK: 718: 10 cb 6c 08 vaddmac cml2, cml1, scd[r31], x1, x11, r8
# CHECK: 71c: 10 e3 c0 7a vaddmac cml6, cml4, scd[r31], x11, x0, r11
# CHECK: 720: 10 4a 5c 16 vaddmac.f dm5, dm5, dm1, x9, ey3, r8
# CHECK: 724: 10 72 04 c1 vaddmac.f dm0, dm0, dm6, x4, ey0, r14
# CHECK: 728: 10 42 ac 92 vaddmac.f dm4, dm4, dm0, x10, ey5, r12
# CHECK: 72c: 10 7a cc 4a vaddmac.f dm2, dm2, dm7, x11, ey1, r10
# CHECK: 730: 10 62 14 a6 vaddmac.f dm1, dm1, dm4, x8, ey2, r13
# CHECK: 734: 10 5a 24 ec vaddmac.f dm3, dm3, dm3, x0, ey4, r15
# CHECK: 738: 10 6a dc 38 vaddmac.f dm6, dm6, dm5, x3, ey3, r9
# CHECK: 73c: 10 52 84 7d vaddmac.f dm7, dm7, dm2, x6, ey0, r11
# CHECK: 740: 10 4a 6c 15 vaddmac.f dm5, dm5, dm1, x5, ey5, r8
# CHECK: 744: 10 72 4c c0 vaddmac.f dm0, dm0, dm6, x1, ey1, r14
# CHECK: 748: 10 42 94 90 vaddmac.f dm4, dm4, dm0, x2, ey2, r12
# CHECK: 74c: 10 7a e4 49 vaddmac.f dm2, dm2, dm7, x7, ey4, r10
# CHECK: 750: 10 0a 99 bd vaddmac.f dm7, dm7, dm1, x6, x6, r13
# CHECK: 754: 10 3a a9 26 vaddmac.f dm1, dm1, dm7, x10, x10, r9
# CHECK: 758: 10 1a ed f8 vaddmac.f dm6, dm6, dm3, x3, x11, r15
# CHECK: 75c: 10 32 09 16 vaddmac.f dm5, dm5, dm6, x8, x2, r8
# CHECK: 760: 10 12 51 90 vaddmac.f dm4, dm4, dm2, x1, x4, r12
# CHECK: 764: 10 22 61 cd vaddmac.f dm3, dm3, dm4, x5, x8, r14
# CHECK: 768: 10 2a 41 6a vaddmac.f dm2, dm2, dm5, x9, x0, r11
# CHECK: 76c: 10 02 0d 40 vaddmac.f dm0, dm0, dm0, x0, x3, r10
# CHECK: 770: 10 0a 05 bd vaddmac.f dm7, dm7, dm1, x4, x1, r13
# CHECK: 774: 10 3a e5 25 vaddmac.f dm1, dm1, dm7, x7, x9, r9
# CHECK: 778: 10 1a dd fa vaddmac.f dm6, dm6, dm3, x11, x7, r15
# CHECK: 77c: 10 32 95 14 vaddmac.f dm5, dm5, dm6, x2, x5, r8
# CHECK: 780: 10 4a de ce vaddmac.f dm3, dm3, dm1, y5, r7, r14
# CHECK: 784: 10 72 fe 09 vaddmac.f dm2, dm2, dm6, y3, r15, r8
# CHECK: 788: 10 42 c2 b4 vaddmac.f dm5, dm5, dm0, y1, r0, r13
# CHECK: 78c: 10 52 52 fa vaddmac.f dm6, dm6, dm2, y4, r4, r15
# CHECK: 790: 10 62 6e 30 vaddmac.f dm4, dm4, dm4, y0, r11, r9
# CHECK: 794: 10 6a 72 81 vaddmac.f dm0, dm0, dm5, y2, r12, r12
# CHECK: 798: 10 7a ce 46 vaddmac.f dm1, dm1, dm7, y5, r3, r10
# CHECK: 79c: 10 5a e6 7d vaddmac.f dm7, dm7, dm3, y3, r9, r11
# CHECK: 7a0: 10 4a e2 cc vaddmac.f dm3, dm3, dm1, y1, r8, r14
# CHECK: 7a4: 10 72 4a 0a vaddmac.f dm2, dm2, dm6, y4, r2, r8
# CHECK: 7a8: 10 42 6a b4 vaddmac.f dm5, dm5, dm0, y0, r10, r13
# CHECK: 7ac: 10 52 5a f9 vaddmac.f dm6, dm6, dm2, y2, r6, r15
# CHECK: 7b0: 10 62 f6 32 vaddmac.f dm4, dm4, dm4, y5, r13, r9
# CHECK: 7b4: 10 6a fa 81 vaddmac.f dm0, dm0, dm5, y3, r14, r12
# CHECK: 7b8: 10 7a c6 44 vaddmac.f dm1, dm1, dm7, y1, r1, r10
# CHECK: 7bc: 10 5a 56 7e vaddmac.f dm7, dm7, dm3, y4, r5, r11
# CHECK: 7c0: 10 6a 26 70 vaddmac.f dm4, dm4, dm5, y0, y4, r11
# CHECK: 7c4: 10 7a 8e fe vaddmac.f dm7, dm7, dm7, y5, y1, r15
# CHECK: 7c8: 10 42 9e c4 vaddmac.f dm1, dm1, dm0, y1, y3, r14
# CHECK: 7cc: 10 5a 06 42 vaddmac.f dm0, dm0, dm3, y4, y0, r10
# CHECK: 7d0: 10 72 2e 15 vaddmac.f dm5, dm5, dm6, y2, y5, r8
# CHECK: 7d4: 10 52 96 a9 vaddmac.f dm2, dm2, dm2, y3, y2, r13
# CHECK: 7d8: 10 62 26 2c vaddmac.f dm3, dm3, dm4, y0, y4, r9
# CHECK: 7dc: 10 4a 8e 9a vaddmac.f dm6, dm6, dm1, y5, y1, r12
# CHECK: 7e0: 10 3a d7 c0 vaddmac.f cml0, cml0, cml7, x3, r5, r14
# CHECK: 7e4: 10 12 bf a8 vaddmac.f cml2, cml2, cml2, x2, r15, r13
# CHECK: 7e8: 10 0a 33 7a vaddmac.f cml6, cml6, cml1, x8, r12, r11
# CHECK: 7ec: 10 2a e3 96 vaddmac.f cml5, cml5, cml5, x11, r8, r12
# CHECK: 7f0: 10 32 b7 32 vaddmac.f cml4, cml4, cml6, x10, r13, r9
# CHECK: 7f4: 10 22 5b 45 vaddmac.f cml1, cml1, cml4, x5, r6, r10
# CHECK: 7f8: 10 1a 1f fd vaddmac.f cml7, cml7, cml3, x4, r7, r15
# CHECK: 7fc: 10 02 83 0d vaddmac.f cml3, cml3, cml0, x6, r0, r8
# CHECK: 800: 10 3a 6b c0 vaddmac.f cml0, cml0, cml7, x1, r10, r14
# CHECK: 804: 10 12 7b aa vaddmac.f cml2, cml2, cml2, x9, r14, r13
# CHECK: 808: 10 0a ef 79 vaddmac.f cml6, cml6, cml1, x7, r11, r11
# CHECK: 80c: 10 2a 13 94 vaddmac.f cml5, cml5, cml5, x0, r4, r12
# CHECK: 810: 10 32 c7 30 vaddmac.f cml4, cml4, cml6, x3, r1, r9
# CHECK: 814: 10 22 8f 44 vaddmac.f cml1, cml1, cml4, x2, r3, r10
# CHECK: 818: 10 1a 0b fe vaddmac.f cml7, cml7, cml3, x8, r2, r15
# CHECK: 81c: 10 02 e7 0e vaddmac.f cml3, cml3, cml0, x11, r9, r8
# CHECK: 820: 10 b2 13 59 vaddmac.f cml6, cml6, cml6, x4, y2, r10
# CHECK: 824: 10 92 db b5 vaddmac.f cml5, cml5, cml2, x7, y3, r13
# CHECK: 828: 10 a2 63 9d vaddmac.f cml7, cml7, cml4, x5, y4, r12
# CHECK: 82c: 10 82 43 c4 vaddmac.f cml1, cml1, cml0, x1, y0, r14
# CHECK: 830: 10 8a 2b 0e vaddmac.f cml3, cml3, cml1, x8, y5, r8
# CHECK: 834: 10 9a 8b 2a vaddmac.f cml2, cml2, cml3, x10, y1, r9
# CHECK: 838: 10 ba 13 60 vaddmac.f cml0, cml0, cml7, x0, y2, r11
# CHECK: 83c: 10 aa 5b f2 vaddmac.f cml4, cml4, cml5, x9, y3, r15
# CHECK: 840: 10 b2 e3 5a vaddmac.f cml6, cml6, cml6, x11, y4, r10
# CHECK: 844: 10 92 83 b4 vaddmac.f cml5, cml5, cml2, x2, y0, r13
# CHECK: 848: 10 a2 ab 9d vaddmac.f cml7, cml7, cml4, x6, y5, r12
# CHECK: 84c: 10 82 cb c4 vaddmac.f cml1, cml1, cml0, x3, y1, r14
# CHECK: 850: 10 52 a3 61 vaddmac.f cml0, cml0, cml2, y3, ey4, r11
# CHECK: 854: 10 42 0b d6 vaddmac.f cml5, cml5, cml0, y4, ey1, r14
# CHECK: 858: 10 7a ab 8c vaddmac.f cml3, cml3, cml7, y1, ey5, r12
# CHECK: 85c: 10 72 03 28 vaddmac.f cml2, cml2, cml6, y0, ey0, r9
# CHECK: 860: 10 4a 1b 11 vaddmac.f cml4, cml4, cml1, y2, ey3, r8
# CHECK: 864: 10 5a 93 fe vaddmac.f cml7, cml7, cml3, y5, ey2, r15
# CHECK: 868: 10 62 a3 45 vaddmac.f cml1, cml1, cml4, y3, ey4, r10
# CHECK: 86c: 10 6a 0b ba vaddmac.f cml6, cml6, cml5, y4, ey1, r13
# CHECK: 870: 10 e2 a6 41 vaddmac.f cml0, cml0, cml4, x6, x9, r10
# CHECK: 874: 10 ca e2 d0 vaddmac.f cml4, cml4, cml1, x3, x8, r14
# CHECK: 878: 10 d2 46 1e vaddmac.f cml7, cml7, cml2, x9, x1, r8
# CHECK: 87c: 10 f2 aa a6 vaddmac.f cml1, cml1, cml6, x10, x10, r13
# CHECK: 880: 10 fa 4e 79 vaddmac.f cml6, cml6, cml7, x5, x3, r11
# CHECK: 884: 10 ea 9a f4 vaddmac.f cml5, cml5, cml5, x2, x6, r15
# CHECK: 888: 10 c2 2e 28 vaddmac.f cml2, cml2, cml0, x0, x11, r9
# CHECK: 88c: 10 da c2 8e vaddmac.f cml3, cml3, cml3, x11, x0, r12
# CHECK: 890: 10 e2 1e 41 vaddmac.f cml0, cml0, cml4, x4, x7, r10
# CHECK: 894: 10 ca 56 d0 vaddmac.f cml4, cml4, cml1, x1, x5, r14
# CHECK: 898: 10 d2 0a 1e vaddmac.f cml7, cml7, cml2, x8, x2, r8
# CHECK: 89c: 10 f2 d2 a5 vaddmac.f cml1, cml1, cml6, x7, x4, r13
# CHECK: 8a0: 10 6c dc 24 vaddmac.f dm1, dm5, scd[r31++], x3, ey3, r9
# CHECK: 8a4: 10 44 64 72 vaddmac.f dm4, dm0, scd[r31++], x9, ey4, r11
# CHECK: 8a8: 10 5c 14 54 vaddmac.f dm5, dm3, scd[r31++], x0, ey2, r10
# CHECK: 8ac: 10 7c 8c 82 vaddmac.f dm0, dm7, scd[r31++], x10, ey1, r12
# CHECK: 8b0: 10 4c ac 18 vaddmac.f dm6, dm1, scd[r31++], x2, ey5, r8
# CHECK: 8b4: 10 54 44 dc vaddmac.f dm7, dm2, scd[r31++], x1, ey0, r14
# CHECK: 8b8: 10 64 dc ea vaddmac.f dm2, dm4, scd[r31++], x11, ey3, r15
# CHECK: 8bc: 10 74 64 ad vaddmac.f dm3, dm6, scd[r31++], x5, ey4, r13
# CHECK: 8c0: 10 6c d4 25 vaddmac.f dm1, dm5, scd[r31++], x7, ey2, r9
# CHECK: 8c4: 10 44 0c 72 vaddmac.f dm4, dm0, scd[r31++], x8, ey1, r11
# CHECK: 8c8: 10 5c 2c 55 vaddmac.f dm5, dm3, scd[r31++], x4, ey5, r10
# CHECK: 8cc: 10 7c 84 81 vaddmac.f dm0, dm7, scd[r31++], x6, ey0, r12
# CHECK: 8d0: 10 04 19 7a vaddmac.f dm6, dm0, scd[r31++], x8, x6, r11
# CHECK: 8d4: 10 24 61 34 vaddmac.f dm5, dm4, scd[r31++], x1, x8, r9
# CHECK: 8d8: 10 14 49 5d vaddmac.f dm7, dm2, scd[r31++], x5, x2, r10
# CHECK: 8dc: 10 3c 95 89 vaddmac.f dm2, dm7, scd[r31++], x6, x5, r12
# CHECK: 8e0: 10 2c 85 cc vaddmac.f dm3, dm5, scd[r31++], x2, x1, r14
# CHECK: 8e4: 10 1c 81 f2 vaddmac.f dm4, dm3, scd[r31++], x10, x0, r15
# CHECK: 8e8: 10 34 d1 a1 vaddmac.f dm0, dm6, scd[r31++], x7, x4, r13
# CHECK: 8ec: 10 0c 6d 06 vaddmac.f dm1, dm1, scd[r31++], x9, x11, r8
# CHECK: 8f0: 10 04 e9 7a vaddmac.f dm6, dm0, scd[r31++], x11, x10, r11
# CHECK: 8f4: 10 24 1d 35 vaddmac.f dm5, dm4, scd[r31++], x4, x7, r9
# CHECK: 8f8: 10 14 cd 5c vaddmac.f dm7, dm2, scd[r31++], x3, x3, r10
# CHECK: 8fc: 10 3c 25 88 vaddmac.f dm2, dm7, scd[r31++], x0, x9, r12
# CHECK: 900: 10 64 56 95 vaddmac.f dm5, dm4, scd[r31++], y2, r5, r12
# CHECK: 904: 10 7c 4a ba vaddmac.f dm6, dm7, scd[r31++], y4, r2, r13
# CHECK: 908: 10 6c de fd vaddmac.f dm7, dm5, scd[r31++], y3, r7, r15
# CHECK: 90c: 10 54 f2 20 vaddmac.f dm0, dm2, scd[r31++], y1, r12, r9
# CHECK: 910: 10 44 7e 50 vaddmac.f dm4, dm0, scd[r31++], y0, r15, r10
# CHECK: 914: 10 4c c6 6e vaddmac.f dm3, dm1, scd[r31++], y5, r1, r11
# CHECK: 918: 10 5c 4e 05 vaddmac.f dm1, dm3, scd[r31++], y2, r3, r8
# CHECK: 91c: 10 74 6a ca vaddmac.f dm2, dm6, scd[r31++], y4, r10, r14
# CHECK: 920: 10 64 ee 95 vaddmac.f dm5, dm4, scd[r31++], y3, r11, r12
# CHECK: 924: 10 7c f6 b8 vaddmac.f dm6, dm7, scd[r31++], y1, r13, r13
# CHECK: 928: 10 6c 52 fc vaddmac.f dm7, dm5, scd[r31++], y0, r4, r15
# CHECK: 92c: 10 54 fa 22 vaddmac.f dm0, dm2, scd[r31++], y5, r14, r9
# CHECK: 930: 10 44 5a 51 vaddmac.f dm4, dm0, scd[r31++], y2, r6, r10
# CHECK: 934: 10 4c 42 6e vaddmac.f dm3, dm1, scd[r31++], y4, r0, r11
# CHECK: 938: 10 5c e6 05 vaddmac.f dm1, dm3, scd[r31++], y3, r9, r8
# CHECK: 93c: 10 74 e2 c8 vaddmac.f dm2, dm6, scd[r31++], y1, r8, r14
# CHECK: 940: 10 6c ae 2a vaddmac.f dm2, dm5, scd[r31++], y5, y5, r9
# CHECK: 944: 10 64 0e 1e vaddmac.f dm7, dm4, scd[r31++], y4, y1, r8
# CHECK: 948: 10 4c 86 d1 vaddmac.f dm4, dm1, scd[r31++], y3, y0, r14
# CHECK: 94c: 10 54 26 8c vaddmac.f dm3, dm2, scd[r31++], y0, y4, r12
# CHECK: 950: 10 74 16 65 vaddmac.f dm1, dm6, scd[r31++], y2, y2, r11
# CHECK: 954: 10 44 9e b8 vaddmac.f dm6, dm0, scd[r31++], y1, y3, r13
# CHECK: 958: 10 7c ae e2 vaddmac.f dm0, dm7, scd[r31++], y5, y5, r15
# CHECK: 95c: 10 5c 0e 56 vaddmac.f dm5, dm3, scd[r31++], y4, y1, r10
# CHECK: 960: 10 6b cc fe vaddmac.f dm7, dm5, scd[r31], x11, ey1, r15
# CHECK: 964: 10 43 44 4a vaddmac.f dm2, dm0, scd[r31], x9, ey0, r10
# CHECK: 968: 10 63 14 61 vaddmac.f dm0, dm4, scd[r31], x4, ey2, r11
# CHECK: 96c: 10 4b 1c 36 vaddmac.f dm5, dm1, scd[r31], x8, ey3, r9
# CHECK: 970: 10 53 a4 cc vaddmac.f dm3, dm2, scd[r31], x2, ey4, r14
# CHECK: 974: 10 7b ac b9 vaddmac.f dm6, dm7, scd[r31], x6, ey5, r13
# CHECK: 978: 10 73 cc 10 vaddmac.f dm4, dm6, scd[r31], x3, ey1, r8
# CHECK: 97c: 10 5b 44 85 vaddmac.f dm1, dm3, scd[r31], x5, ey0, r12
# CHECK: 980: 10 6b 94 fe vaddmac.f dm7, dm5, scd[r31], x10, ey2, r15
# CHECK: 984: 10 43 dc 49 vaddmac.f dm2, dm0, scd[r31], x7, ey3, r10
# CHECK: 988: 10 63 24 60 vaddmac.f dm0, dm4, scd[r31], x0, ey4, r11
# CHECK: 98c: 10 4b 6c 34 vaddmac.f dm5, dm1, scd[r31], x1, ey5, r9
# CHECK: 990: 10 23 89 ad vaddmac.f dm3, dm4, scd[r31], x6, x2, r13
# CHECK: 994: 10 2b e1 00 vaddmac.f dm0, dm5, scd[r31], x3, x8, r8
# CHECK: 998: 10 13 a9 28 vaddmac.f dm2, dm2, scd[r31], x2, x10, r9
# CHECK: 99c: 10 0b 05 d2 vaddmac.f dm4, dm1, scd[r31], x8, x1, r14
# CHECK: 9a0: 10 1b ad e6 vaddmac.f dm1, dm3, scd[r31], x10, x11, r15
# CHECK: 9a4: 10 3b 15 5d vaddmac.f dm7, dm7, scd[r31], x4, x5, r10
# CHECK: 9a8: 10 33 41 74 vaddmac.f dm5, dm6, scd[r31], x1, x0, r11
# CHECK: 9ac: 10 03 11 98 vaddmac.f dm6, dm0, scd[r31], x0, x4, r12
# CHECK: 9b0: 10 23 cd ad vaddmac.f dm3, dm4, scd[r31], x7, x3, r13
# CHECK: 9b4: 10 2b 5d 02 vaddmac.f dm0, dm5, scd[r31], x9, x7, r8
# CHECK: 9b8: 10 13 65 29 vaddmac.f dm2, dm2, scd[r31], x5, x9, r9
# CHECK: 9bc: 10 0b d9 d2 vaddmac.f dm4, dm1, scd[r31], x11, x6, r14
# CHECK: 9c0: 10 5b 52 e0 vaddmac.f dm0, dm3, scd[r31], y0, r4, r15
# CHECK: 9c4: 10 6b 4e 32 vaddmac.f dm4, dm5, scd[r31], y4, r3, r9
# CHECK: 9c8: 10 63 e2 96 vaddmac.f dm5, dm4, scd[r31], y5, r8, r12
# CHECK: 9cc: 10 73 6e b9 vaddmac.f dm6, dm6, scd[r31], y2, r11, r13
# CHECK: 9d0: 10 7b c6 c8 vaddmac.f dm2, dm7, scd[r31], y1, r1, r14
# CHECK: 9d4: 10 4b d6 6d vaddmac.f dm3, dm1, scd[r31], y3, r5, r11
# CHECK: 9d8: 10 53 4a 44 vaddmac.f dm1, dm2, scd[r31], y0, r2, r10
# CHECK: 9dc: 10 43 7e 1e vaddmac.f dm7, dm0, scd[r31], y4, r15, r8
# CHECK: 9e0: 10 5b da e2 vaddmac.f dm0, dm3, scd[r31], y5, r6, r15
# CHECK: 9e4: 10 6b 66 31 vaddmac.f dm4, dm5, scd[r31], y2, r9, r9
# CHECK: 9e8: 10 63 f2 94 vaddmac.f dm5, dm4, scd[r31], y1, r12, r12
# CHECK: 9ec: 10 73 de b9 vaddmac.f dm6, dm6, scd[r31], y3, r7, r13
# CHECK: 9f0: 10 7b 42 c8 vaddmac.f dm2, dm7, scd[r31], y0, r0, r14
# CHECK: 9f4: 10 4b 76 6e vaddmac.f dm3, dm1, scd[r31], y4, r13, r11
# CHECK: 9f8: 10 53 fa 46 vaddmac.f dm1, dm2, scd[r31], y5, r14, r10
# CHECK: 9fc: 10 43 6a 1d vaddmac.f dm7, dm0, scd[r31], y2, r10, r8
# CHECK: a00: 10 7b 26 91 vaddmac.f dm4, dm7, scd[r31], y2, y4, r12
# CHECK: a04: 10 73 86 5d vaddmac.f dm7, dm6, scd[r31], y3, y0, r10
# CHECK: a08: 10 43 1e 6e vaddmac.f dm3, dm0, scd[r31], y4, y3, r11
# CHECK: a0c: 10 5b 2e 28 vaddmac.f dm2, dm3, scd[r31], y0, y5, r9
# CHECK: a10: 10 63 96 f4 vaddmac.f dm5, dm4, scd[r31], y1, y2, r15
# CHECK: a14: 10 53 8e da vaddmac.f dm6, dm2, scd[r31], y5, y1, r14
# CHECK: a18: 10 6b 26 01 vaddmac.f dm0, dm5, scd[r31], y2, y4, r8
# CHECK: a1c: 10 4b 86 a5 vaddmac.f dm1, dm1, scd[r31], y3, y0, r13
# CHECK: a20: 10 04 a3 da vaddmac.f cml6, cml0, scd[r31++], x10, r8, r14
# CHECK: a24: 10 2c 27 4a vaddmac.f cml2, cml5, scd[r31++], x8, r9, r10
# CHECK: a28: 10 14 c3 f5 vaddmac.f cml5, cml2, scd[r31++], x7, r0, r15
# CHECK: a2c: 10 24 8f 81 vaddmac.f cml0, cml4, scd[r31++], x6, r3, r12
# CHECK: a30: 10 3c 97 1c vaddmac.f cml7, cml7, scd[r31++], x2, r5, r8
# CHECK: a34: 10 1c 4b 2c vaddmac.f cml3, cml3, scd[r31++], x1, r2, r9
# CHECK: a38: 10 0c 13 a4 vaddmac.f cml1, cml1, scd[r31++], x0, r4, r13
# CHECK: a3c: 10 34 ff 72 vaddmac.f cml4, cml6, scd[r31++], x11, r15, r11
# CHECK: a40: 10 04 c7 d8 vaddmac.f cml6, cml0, scd[r31++], x3, r1, r14
# CHECK: a44: 10 2c 5f 4a vaddmac.f cml2, cml5, scd[r31++], x9, r7, r10
# CHECK: a48: 10 14 33 f5 vaddmac.f cml5, cml2, scd[r31++], x4, r12, r15
# CHECK: a4c: 10 24 5b 81 vaddmac.f cml0, cml4, scd[r31++], x5, r6, r12
# CHECK: a50: 10 3c ab 1e vaddmac.f cml7, cml7, scd[r31++], x10, r10, r8
# CHECK: a54: 10 1c 37 2e vaddmac.f cml3, cml3, scd[r31++], x8, r13, r9
# CHECK: a58: 10 0c ef a5 vaddmac.f cml1, cml1, scd[r31++], x7, r11, r13
# CHECK: a5c: 10 34 bb 71 vaddmac.f cml4, cml6, scd[r31++], x6, r14, r11
# CHECK: a60: 10 94 8b 09 vaddmac.f cml2, cml2, scd[r31++], x6, y1, r8
# CHECK: a64: 10 ac e3 61 vaddmac.f cml0, cml5, scd[r31++], x7, y4, r11
# CHECK: a68: 10 84 9b c6 vaddmac.f cml1, cml0, scd[r31++], x10, y3, r14
# CHECK: a6c: 10 bc 03 58 vaddmac.f cml6, cml7, scd[r31++], x0, y0, r10
# CHECK: a70: 10 8c d3 2e vaddmac.f cml3, cml1, scd[r31++], x11, y2, r9
# CHECK: a74: 10 b4 6b 9c vaddmac.f cml7, cml6, scd[r31++], x1, y5, r12
# CHECK: a78: 10 9c cb f0 vaddmac.f cml4, cml3, scd[r31++], x3, y1, r15
# CHECK: a7c: 10 a4 63 b6 vaddmac.f cml5, cml4, scd[r31++], x9, y4, r13
# CHECK: a80: 10 94 5b 09 vaddmac.f cml2, cml2, scd[r31++], x5, y3, r8
# CHECK: a84: 10 ac 03 62 vaddmac.f cml0, cml5, scd[r31++], x8, y0, r11
# CHECK: a88: 10 84 93 c4 vaddmac.f cml1, cml0, scd[r31++], x2, y2, r14
# CHECK: a8c: 10 bc 2b 59 vaddmac.f cml6, cml7, scd[r31++], x4, y5, r10
# CHECK: a90: 10 7c 8b e0 vaddmac.f cml0, cml7, scd[r31++], y1, ey1, r15
# CHECK: a94: 10 6c 03 d1 vaddmac.f cml4, cml5, scd[r31++], y2, ey0, r14
# CHECK: a98: 10 44 2b 3a vaddmac.f cml6, cml0, scd[r31++], y4, ey5, r9
# CHECK: a9c: 10 64 9b 5d vaddmac.f cml7, cml4, scd[r31++], y3, ey3, r10
# CHECK: aa0: 10 4c a3 66 vaddmac.f cml1, cml1, scd[r31++], y5, ey4, r11
# CHECK: aa4: 10 54 13 8c vaddmac.f cml3, cml2, scd[r31++], y0, ey2, r12
# CHECK: aa8: 10 74 8b a8 vaddmac.f cml2, cml6, scd[r31++], y1, ey1, r13
# CHECK: aac: 10 5c 03 15 vaddmac.f cml5, cml3, scd[r31++], y2, ey0, r8
# CHECK: ab0: 10 c4 46 90 vaddmac.f cml4, cml0, scd[r31++], x1, x1, r12
# CHECK: ab4: 10 f4 9e be vaddmac.f cml7, cml6, scd[r31++], x10, x7, r13
# CHECK: ab8: 10 d4 1a d9 vaddmac.f cml6, cml2, scd[r31++], x4, x6, r14
# CHECK: abc: 10 e4 ea 02 vaddmac.f cml0, cml4, scd[r31++], x11, x10, r8
# CHECK: ac0: 10 fc 0e ea vaddmac.f cml2, cml7, scd[r31++], x8, x3, r15
# CHECK: ac4: 10 ec 42 4d vaddmac.f cml3, cml5, scd[r31++], x5, x0, r10
# CHECK: ac8: 10 dc ae 74 vaddmac.f cml5, cml3, scd[r31++], x2, x11, r11
# CHECK: acc: 10 cc 0a 24 vaddmac.f cml1, cml1, scd[r31++], x0, x2, r9
# CHECK: ad0: 10 c4 66 92 vaddmac.f cml4, cml0, scd[r31++], x9, x9, r12
# CHECK: ad4: 10 f4 e2 bc vaddmac.f cml7, cml6, scd[r31++], x3, x8, r13
# CHECK: ad8: 10 d4 96 d9 vaddmac.f cml6, cml2, scd[r31++], x6, x5, r14
# CHECK: adc: 10 e4 d2 01 vaddmac.f cml0, cml4, scd[r31++], x7, x4, r8
# CHECK: ae0: 10 1b bb 3c vaddmac.f cml7, cml3, scd[r31], x2, r14, r9
# CHECK: ae4: 10 3b ef 58 vaddmac.f cml6, cml7, scd[r31], x3, r11, r10
# CHECK: ae8: 10 33 1f e0 vaddmac.f cml0, cml6, scd[r31], x0, r7, r15
# CHECK: aec: 10 2b cb 11 vaddmac.f cml4, cml5, scd[r31], x7, r2, r8
# CHECK: af0: 10 23 f7 ca vaddmac.f cml2, cml4, scd[r31], x11, r13, r14
# CHECK: af4: 10 03 13 76 vaddmac.f cml5, cml0, scd[r31], x8, r4, r11
# CHECK: af8: 10 0b 87 a5 vaddmac.f cml1, cml1, scd[r31], x6, r1, r13
# CHECK: afc: 10 13 63 8d vaddmac.f cml3, cml2, scd[r31], x5, r8, r12
# CHECK: b00: 10 1b 73 3c vaddmac.f cml7, cml3, scd[r31], x1, r12, r9
# CHECK: b04: 10 3b 97 5a vaddmac.f cml6, cml7, scd[r31], x10, r5, r10
# CHECK: b08: 10 33 4f e2 vaddmac.f cml0, cml6, scd[r31], x9, r3, r15
# CHECK: b0c: 10 2b 03 11 vaddmac.f cml4, cml5, scd[r31], x4, r0, r8
# CHECK: b10: 10 23 ab c8 vaddmac.f cml2, cml4, scd[r31], x2, r10, r14
# CHECK: b14: 10 03 db 74 vaddmac.f cml5, cml0, scd[r31], x3, r6, r11
# CHECK: b18: 10 0b 27 a4 vaddmac.f cml1, cml1, scd[r31], x0, r9, r13
# CHECK: b1c: 10 13 ff 8d vaddmac.f cml3, cml2, scd[r31], x7, r15, r12
# CHECK: b20: 10 bb 9b a2 vaddmac.f cml0, cml7, scd[r31], x10, y3, r13
# CHECK: b24: 10 b3 13 72 vaddmac.f cml4, cml6, scd[r31], x8, y2, r11
# CHECK: b28: 10 8b 03 9c vaddmac.f cml7, cml1, scd[r31], x0, y0, r12
# CHECK: b2c: 10 93 2b 35 vaddmac.f cml5, cml2, scd[r31], x4, y5, r9
# CHECK: b30: 10 83 4b f8 vaddmac.f cml6, cml0, scd[r31], x1, y1, r15
# CHECK: b34: 10 ab e3 0d vaddmac.f cml3, cml5, scd[r31], x7, y4, r8
# CHECK: b38: 10 a3 db c6 vaddmac.f cml1, cml4, scd[r31], x11, y3, r14
# CHECK: b3c: 10 9b 93 49 vaddmac.f cml2, cml3, scd[r31], x6, y2, r10
# CHECK: b40: 10 bb 83 a0 vaddmac.f cml0, cml7, scd[r31], x2, y0, r13
# CHECK: b44: 10 b3 6b 71 vaddmac.f cml4, cml6, scd[r31], x5, y5, r11
# CHECK: b48: 10 8b 4b 9e vaddmac.f cml7, cml1, scd[r31], x9, y1, r12
# CHECK: b4c: 10 93 e3 34 vaddmac.f cml5, cml2, scd[r31], x3, y4, r9
# CHECK: b50: 10 4b 8b f9 vaddmac.f cml6, cml1, scd[r31], y3, ey1, r15
# CHECK: b54: 10 5b 9b de vaddmac.f cml7, cml3, scd[r31], y5, ey3, r14
# CHECK: b58: 10 43 83 6c vaddmac.f cml3, cml0, scd[r31], y1, ey0, r11
# CHECK: b5c: 10 6b 13 24 vaddmac.f cml1, cml5, scd[r31], y0, ey2, r9
# CHECK: b60: 10 63 23 aa vaddmac.f cml2, cml4, scd[r31], y4, ey4, r13
# CHECK: b64: 10 7b 2b 91 vaddmac.f cml4, cml7, scd[r31], y2, ey5, r12
# CHECK: b68: 10 73 8b 01 vaddmac.f cml0, cml6, scd[r31], y3, ey1, r8
# CHECK: b6c: 10 53 9b 56 vaddmac.f cml5, cml2, scd[r31], y5, ey3, r10
# CHECK: b70: 10 d3 aa 8e vaddmac.f cml3, cml2, scd[r31], x10, x10, r12
# CHECK: b74: 10 cb c6 12 vaddmac.f cml4, cml1, scd[r31], x11, x1, r8
# CHECK: b78: 10 f3 82 a8 vaddmac.f cml2, cml6, scd[r31], x2, x0, r13
# CHECK: b7c: 10 e3 62 20 vaddmac.f cml0, cml4, scd[r31], x1, x8, r9
# CHECK: b80: 10 eb 8a c5 vaddmac.f cml1, cml5, scd[r31], x6, x2, r14
# CHECK: b84: 10 c3 d2 58 vaddmac.f cml6, cml0, scd[r31], x3, x4, r10
# CHECK: b88: 10 db 2e f6 vaddmac.f cml5, cml3, scd[r31], x8, x11, r15
# CHECK: b8c: 10 fb 4e 7d vaddmac.f cml7, cml7, scd[r31], x5, x3, r11
# CHECK: b90: 10 d3 16 8d vaddmac.f cml3, cml2, scd[r31], x4, x5, r12
# CHECK: b94: 10 cb 5e 12 vaddmac.f cml4, cml1, scd[r31], x9, x7, r8
# CHECK: b98: 10 f3 1a a8 vaddmac.f cml2, cml6, scd[r31], x0, x6, r13
# CHECK: b9c: 10 e3 e6 21 vaddmac.f cml0, cml4, scd[r31], x7, x9, r9
# CHECK: ba0: 10 8a 2f 54 vaddmac.f dm5, dm5, dm1, fex0, fey5, r10
# CHECK: ba4: 10 92 d7 d1 vaddmac.f dm4, dm4, dm2, fex7, fey2, r14
# CHECK: ba8: 10 9a 07 9e vaddmac.f dm7, dm7, dm3, fex8, fey0, r12
# CHECK: bac: 10 ba 9f 66 vaddmac.f dm1, dm1, dm7, fex10, fey3, r11
# CHECK: bb0: 10 b2 e7 00 vaddmac.f dm0, dm0, dm6, fex3, fey4, r8
# CHECK: bb4: 10 82 4f fa vaddmac.f dm6, dm6, dm0, fex9, fey1, r15
# CHECK: bb8: 10 a2 6f 2d vaddmac.f dm3, dm3, dm4, fex5, fey5, r9
# CHECK: bbc: 10 aa 57 a8 vaddmac.f dm2, dm2, dm5, fex1, fey2, r13
# CHECK: bc0: 10 8a 87 55 vaddmac.f dm5, dm5, dm1, fex6, fey0, r10
# CHECK: bc4: 10 92 df d2 vaddmac.f dm4, dm4, dm2, fex11, fey3, r14
# CHECK: bc8: 10 9a a7 9c vaddmac.f dm7, dm7, dm3, fex2, fey4, r12
# CHECK: bcc: 10 ba 0f 65 vaddmac.f dm1, dm1, dm7, fex4, fey1, r11
# CHECK: bd0: 10 9c a7 54 vaddmac.f dm5, dm3, scd[r31++], fex2, fey4, r10
# CHECK: bd4: 10 84 9f fa vaddmac.f dm6, dm0, scd[r31++], fex10, fey3, r15
# CHECK: bd8: 10 8c 4f a0 vaddmac.f dm0, dm1, scd[r31++], fex1, fey1, r13
# CHECK: bdc: 10 bc 6f 86 vaddmac.f dm1, dm7, scd[r31++], fex9, fey5, r12
# CHECK: be0: 10 a4 17 3e vaddmac.f dm7, dm4, scd[r31++], fex8, fey2, r9
# CHECK: be4: 10 ac c7 d2 vaddmac.f dm4, dm5, scd[r31++], fex11, fey0, r14
# CHECK: be8: 10 b4 67 69 vaddmac.f dm2, dm6, scd[r31++], fex5, fey4, r11
# CHECK: bec: 10 94 1f 0c vaddmac.f dm3, dm2, scd[r31++], fex0, fey3, r8
# CHECK: bf0: 10 9c 0f 55 vaddmac.f dm5, dm3, scd[r31++], fex4, fey1, r10
# CHECK: bf4: 10 84 af f9 vaddmac.f dm6, dm0, scd[r31++], fex6, fey5, r15
# CHECK: bf8: 10 8c d7 a1 vaddmac.f dm0, dm1, scd[r31++], fex7, fey2, r13
# CHECK: bfc: 10 bc c7 84 vaddmac.f dm1, dm7, scd[r31++], fex3, fey0, r12
# CHECK: c00: 10 b3 c7 b8 vaddmac.f dm6, dm6, scd[r31], fex3, fey0, r13
# CHECK: c04: 10 a3 1f 20 vaddmac.f dm0, dm4, scd[r31], fex0, fey3, r9
# CHECK: c08: 10 ab a7 5e vaddmac.f dm7, dm5, scd[r31], fex10, fey4, r10
# CHECK: c0c: 10 9b 0f f5 vaddmac.f dm5, dm3, scd[r31], fex4, fey1, r15
# CHECK: c10: 10 83 97 cc vaddmac.f dm3, dm0, scd[r31], fex2, fey2, r14
# CHECK: c14: 10 8b ef 69 vaddmac.f dm2, dm1, scd[r31], fex7, fey5, r11
# CHECK: c18: 10 93 47 11 vaddmac.f dm4, dm2, scd[r31], fex5, fey0, r8
# CHECK: c1c: 10 bb 9f 85 vaddmac.f dm1, dm7, scd[r31], fex6, fey3, r12
# CHECK: c20: 10 b3 27 ba vaddmac.f dm6, dm6, scd[r31], fex8, fey4, r13
# CHECK: c24: 10 a3 4f 22 vaddmac.f dm0, dm4, scd[r31], fex9, fey1, r9
# CHECK: c28: 10 ab 57 5c vaddmac.f dm7, dm5, scd[r31], fex1, fey2, r10
# CHECK: c2c: 10 9b ef f6 vaddmac.f dm5, dm3, scd[r31], fex11, fey5, r15
# CHECK: c30: 10 82 68 d5 vaddmac.f dm5, dm5, dm0, ex5, ey2, ey2, r14
# CHECK: c34: 10 a2 c0 0a vaddmac.f dm2, dm2, dm4, ex11, ey0, ey0, r8
# CHECK: c38: 10 8a 9c 91 vaddmac.f dm4, dm4, dm1, ex6, ey1, ey3, r12
# CHECK: c3c: 10 ba f4 65 vaddmac.f dm1, dm1, dm7, ex7, ey3, ey1, r11
# CHECK: c40: 10 92 a8 20 vaddmac.f dm0, dm0, dm2, ex2, ey2, ey2, r9
# CHECK: c44: 10 aa 40 f8 vaddmac.f dm6, dm6, dm5, ex1, ey0, ey0, r15
# CHECK: c48: 10 b2 1c bc vaddmac.f dm7, dm7, dm6, ex0, ey1, ey3, r13
# CHECK: c4c: 10 9a f4 4c vaddmac.f dm3, dm3, dm3, ex3, ey3, ey1, r10
# CHECK: c50: 10 82 a8 d6 vaddmac.f dm5, dm5, dm0, ex10, ey2, ey2, r14
# CHECK: c54: 10 a2 00 0a vaddmac.f dm2, dm2, dm4, ex8, ey0, ey0, r8
# CHECK: c58: 10 8a 5c 92 vaddmac.f dm4, dm4, dm1, ex9, ey1, ey3, r12
# CHECK: c5c: 10 ba 34 65 vaddmac.f dm1, dm1, dm7, ex4, ey3, ey1, r11
# CHECK: c60: 10 a4 e4 0d vaddmac.f dm3, dm4, scd[r31++], ex7, ey2, ey1, r8
# CHECK: c64: 10 b4 08 22 vaddmac.f dm0, dm6, scd[r31++], ex8, ey0, ey2, r9
# CHECK: c68: 10 ac 1c d8 vaddmac.f dm6, dm5, scd[r31++], ex0, ey1, ey3, r14
# CHECK: c6c: 10 94 b0 fc vaddmac.f dm7, dm2, scd[r31++], ex2, ey3, ey0, r15
# CHECK: c70: 10 9c 24 b5 vaddmac.f dm5, dm3, scd[r31++], ex4, ey2, ey1, r13
# CHECK: c74: 10 bc 88 91 vaddmac.f dm4, dm7, scd[r31++], ex6, ey0, ey2, r12
# CHECK: c78: 10 8c 5c 4a vaddmac.f dm2, dm1, scd[r31++], ex9, ey1, ey3, r10
# CHECK: c7c: 10 84 f0 64 vaddmac.f dm1, dm0, scd[r31++], ex3, ey3, ey0, r11
# CHECK: c80: 10 a4 e4 0e vaddmac.f dm3, dm4, scd[r31++], ex11, ey2, ey1, r8
# CHECK: c84: 10 b4 88 22 vaddmac.f dm0, dm6, scd[r31++], ex10, ey0, ey2, r9
# CHECK: c88: 10 ac 5c d8 vaddmac.f dm6, dm5, scd[r31++], ex1, ey1, ey3, r14
# CHECK: c8c: 10 94 70 fd vaddmac.f dm7, dm2, scd[r31++], ex5, ey3, ey0, r15
# CHECK: c90: 10 93 fc e4 vaddmac.f dm1, dm2, scd[r31], ex3, ey3, ey3, r15
# CHECK: c94: 10 ab 68 0c vaddmac.f dm3, dm5, scd[r31], ex1, ey2, ey2, r8
# CHECK: c98: 10 8b d4 75 vaddmac.f dm5, dm1, scd[r31], ex7, ey1, ey1, r11
# CHECK: c9c: 10 a3 40 89 vaddmac.f dm2, dm4, scd[r31], ex5, ey0, ey0, r12
# CHECK: ca0: 10 9b 3c c2 vaddmac.f dm0, dm3, scd[r31], ex8, ey3, ey3, r14
# CHECK: ca4: 10 83 a8 5d vaddmac.f dm7, dm0, scd[r31], ex6, ey2, ey2, r10
# CHECK: ca8: 10 bb 54 b2 vaddmac.f dm4, dm7, scd[r31], ex9, ey1, ey1, r13
# CHECK: cac: 10 b3 00 39 vaddmac.f dm6, dm6, scd[r31], ex4, ey0, ey0, r9
# CHECK: cb0: 10 93 bc e6 vaddmac.f dm1, dm2, scd[r31], ex10, ey3, ey3, r15
# CHECK: cb4: 10 ab a8 0c vaddmac.f dm3, dm5, scd[r31], ex2, ey2, ey2, r8
# CHECK: cb8: 10 8b 14 74 vaddmac.f dm5, dm1, scd[r31], ex0, ey1, ey1, r11
# CHECK: cbc: 10 a3 c0 8a vaddmac.f dm2, dm4, scd[r31], ex11, ey0, ey0, r12
