# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie -run-pass=postrapseudos %s -o - | FileCheck %s

---
name:            test_384
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_384
    ; CHECK: WVST_SPIL_AM_LO_I48 $aml1, -64, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: WVST_SPIL_AM_HI_I48 $aml1, -32, implicit $sp :: (store (s512) into %stack.0)
    I384_STORE $aml1, -64, implicit $sp :: (store (s512) into %stack.0)
...

---
name:            test_512
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_512
    ; CHECK: WVST_SPIL $wr0, -64, implicit $sp :: (store (s256) into %stack.0, align 64)
    ; CHECK-NEXT: WVST_SPIL $wr1, -32, implicit $sp :: (store (s256) into %stack.0 + 32, basealign 64)
    I512_STORE $xa, -64, implicit $sp :: (store (s512) into %stack.0)
...

---
name:            test_768
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 128 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_768
    ; CHECK: WVST_SPIL_AM_LO_I48 $aml1, -128, implicit $sp :: (store (s512) into %stack.0, align 128)
    ; CHECK-NEXT: WVST_SPIL_AM_HI_I48 $aml1, -96, implicit $sp :: (store (s512) into %stack.0, align 128)
    ; CHECK-NEXT: WVST_SPIL_AM_LO_I48 $amh1, -64, implicit $sp :: (store (s512) into %stack.0 + 64, basealign 128)
    ; CHECK-NEXT: WVST_SPIL_AM_HI_I48 $amh1, -32, implicit $sp :: (store (s512) into %stack.0 + 64, basealign 128)
    I768_STORE $bm1, -128, implicit $sp :: (store (s1024) into %stack.0)
...

---
name:            test_1024
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 128 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_1024
    ; CHECK: WVST_SPIL $wr0, -128, implicit $sp :: (store (s256) into %stack.0, align 128)
    ; CHECK-NEXT: WVST_SPIL $wr1, -96, implicit $sp :: (store (s256) into %stack.0 + 32, basealign 128)
    ; CHECK-NEXT: WVST_SPIL $wr2, -64, implicit $sp :: (store (s256) into %stack.0 + 64, align 64, basealign 128)
    ; CHECK-NEXT: WVST_SPIL $wr3, -32, implicit $sp :: (store (s256) into %stack.0 + 96, basealign 128)
    I1024_STORE $ya, -128, implicit $sp :: (store (s1024) into %stack.0)
...

---
name:            test_undef
alignment:       16
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_undef
    ; CHECK: WVST_SPIL undef $wr0, -64, implicit $sp
    ; CHECK-NEXT: WVST_SPIL undef $wr1, -32, implicit $sp
    I512_STORE undef $xa, -64, implicit $sp
...
