; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc %s -o - | FileCheck %s
;
; AvgPool2D bf16 inner loop extracted from AvgPool2D_bfloat16_0.ll.
; 72-instruction loop body with data shuffles, shifts, and VMACs.
; The post-pipeliner should find II=36 (NS=2) for the inner loop
; with MinTripCount=3.

source_filename = "Work/aie/0_0/src/0_0.cc"
target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2ps-none-unknown-elf"

$_Z9avgpool2dILh1E8bfloat16Qsr5mllib5utilsE11is_one_of_vIT0_ahS0_7float16EEvPS1_S3_R25avgpool2d_internal_paramsIS1_E = comdat any

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float>) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32>, <16 x i32>, i32) #1

; Function Attrs: mustprogress noinline
define weak_odr dso_local void @_Z9avgpool2dILh1E8bfloat16Qsr5mllib5utilsE11is_one_of_vIT0_ahS0_7float16EEvPS1_S3_R25avgpool2d_internal_paramsIS1_E(ptr noalias %ifm_ptr, ptr noalias %ofm_ptr, ptr nonnull align 64 dereferenceable(64) %avgpool2d_params) local_unnamed_addr #2 comdat {
; CHECK-LABEL: _Z9avgpool2dILh1E8bfloat16Qsr5mllib5utilsE11is_one_of_vIT0_ahS0_7float16EEvPS1_S3_R25avgpool2d_internal_paramsIS1_E:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    paddxm [sp], #64; nopb ; nopx
; CHECK-NEXT:    lda.u8 r0, [p2, #0]; st p6, [sp, #-44]; mov m0, #46 // 4-byte Folded Spill
; CHECK-NEXT:    mova m0, #-42; paddb [p2], m0; st p7, [sp, #-40] // 4-byte Folded Spill
; CHECK-NEXT:    lda.s16 r2, [p2], m0; st r10, [sp, #-52] // 4-byte Folded Spill
; CHECK-NEXT:    st r9:r8, [sp, #-64] // 8-byte Folded Spill
; CHECK-NEXT:    st lr, [sp, #-56] // 4-byte Folded Spill
; CHECK-NEXT:    st r12, [sp, #-48]; jl #__floatsisf // 4-byte Folded Spill
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    movxm r8, #50332476 // Delay Slot 3
; CHECK-NEXT:    movs p6, p0; vbcst.16 x0, r2 // Delay Slot 2
; CHECK-NEXT:    mova r10, #1; movs p7, p1; add r1, r0, #-2; mov r9, p2 // Delay Slot 1
; CHECK-NEXT:    nopa ; nopb ; nopx ; vinsert.32 x2, x0, #0, r0
; CHECK-NEXT:    vmov bmll0, x2
; CHECK-NEXT:    mova m0, #24; mov p0, r9
; CHECK-NEXT:    lda.u16 r26, [p0], m0; vconv.bf16.fp32 wl2, bmll0
; CHECK-NEXT:    lda.s16 r22, [p0], #12
; CHECK-NEXT:    lda.s8 r2, [p0], #1; movxm r12, #50331708
; CHECK-NEXT:    lda.s8 r4, [p0], #-8; vmul.f cml0, x0, x2, r12
; CHECK-NEXT:    lda.s8 r6, [p0], #1
; CHECK-NEXT:    lda.s8 r16, [p0], #1
; CHECK-NEXT:    lda.s8 r18, [p0], #1; vldb x4, [p6], #64
; CHECK-NEXT:    lda.s8 r20, [p0], #1; vldb x6, [p6], #64
; CHECK-NEXT:    lda.s8 r24, [p0], #1; vldb x8, [p6], #64
; CHECK-NEXT:    lda.s8 r28, [p0], #1; vldb x10, [p6], #64; mov m1, r22
; CHECK-NEXT:    vlda x7, [p6], m1; vconv.bf16.fp32 x2, cml0; movxm ls, #.LBB0_1
; CHECK-NEXT:    vlda x10, [p6], #64; mov m0, #-9
; CHECK-NEXT:    lda.s8 r30, [p0], m0; movxm le, #.L_LEnd0
; CHECK-NEXT:    lda.s16 r1, [p0], #-6; vextbcst.16 x2, x2, #0
; CHECK-NEXT:    lshl r0, r6, r10; vshuffle x1, x4, x6, r2
; CHECK-NEXT:    lshl r6, r16, r10; vshuffle x3, x4, x6, r4
; CHECK-NEXT:    lshl r16, r18, r10; vshuffle x5, x8, x10, r2; vmul.f cml2, x1, x0, r8
; CHECK-NEXT:    lshl r18, r20, r10; vshuffle x9, x8, x10, r4
; CHECK-NEXT:    vlda x5, [p6], #64; vshift x8, x3, x5, r18
; CHECK-NEXT:    vlda x9, [p6], #64; lshl r20, r24, r10; vshift x11, x3, x5, r0
; CHECK-NEXT:    movs m2, r1; vldb x8, [p6], #64; vshift x11, x11, x9, r20; vmul.f cml0, x8, x0, r8
; CHECK-NEXT:    vlda x6, [p6], m2; vshift x4, x1, x3, r6
; CHECK-NEXT:    vshift x6, x3, x5, r16
; CHECK-NEXT:    lda m0, [p0], #-8; vldb x8, [p6], #64; lshl r22, r28, r10; vshift x3, x1, x3, r0; vmac.f cml1, cml0, x11, x0, r8
; CHECK-NEXT:    lda dn0, [p0], #-8; lshl r24, r30, r10; vshift x4, x4, x5, r22
; CHECK-NEXT:    lda dj0, [p0], #12; vshift x6, x6, x7, r24; vmac.f cml3, cml2, x3, x0, r8
; CHECK-NEXT:    lda dn4, [p0, #0]; vshuffle x7, x10, x5, r2
; CHECK-NEXT:    lda dj4, [p0, #-8]; vshuffle x11, x10, x5, r4; vmac.f cml4, cml1, x6, x2, r8
; CHECK-NEXT:    vshuffle x1, x9, x8, r2; vmac.f cml5, cml3, x4, x2, r8
; CHECK-NEXT:    vshuffle x10, x9, x8, r4
; CHECK-NEXT:    vlda x1, [p6], #64; vshift x9, x11, x1, r18
; CHECK-NEXT:    mova dc0, #0; vldb x7, [p6], #64; vshift x5, x11, x1, r0; vmac.f cml7, cml5, x7, x0, r8
; CHECK-NEXT:    vlda x10, [p6], #64; vshift x5, x5, x10, r20; vmac.f cml6, cml4, x9, x0, r8
; CHECK-NEXT:    movs dc4, dc0; vshift x4, x7, x11, r6
; CHECK-NEXT:    vldb.3d x4, [p6], d0; vshift x3, x11, x1, r16
; CHECK-NEXT:    vshift x11, x7, x11, r0; vmac.f cml6, cml6, x5, x0, r8
; CHECK-NEXT:    vshift x4, x4, x1, r22
; CHECK-NEXT:    vshift x3, x3, x6, r24; vmac.f cml7, cml7, x11, x0, r8
; CHECK-NEXT:    vshuffle x6, x8, x1, r2
; CHECK-NEXT:    vshuffle x5, x8, x1, r4; vmac.f cml6, cml6, x3, x2, r8
; CHECK-NEXT:    vshuffle x9, x7, x10, r2; vmac.f cml7, cml7, x4, x2, r8
; CHECK-NEXT:    add.nc lc, r26, #-1; vshift x8, x5, x9, r18
; CHECK-NEXT:  .LBB0_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; vldb x4, [p6], #64; nopx ; vshuffle x11, x7, x10, r4; nops
; CHECK-NEXT:    vldb x6, [p6], #64; vshift x1, x6, x5, r0; vmac.f cml7, cml7, x6, x2, r8
; CHECK-NEXT:    vldb x8, [p6], #64; vshift x7, x5, x9, r0; vmac.f cml6, cml6, x8, x2, r8
; CHECK-NEXT:    vldb x10, [p6], #64; vshift x7, x7, x11, r20
; CHECK-NEXT:    vlda x7, [p6], m1; vshift x3, x6, x5, r6; vmac.f cml7, cml7, x1, x2, r8
; CHECK-NEXT:    vlda x10, [p6], #64; vshift x10, x5, x9, r16; vmac.f cml6, cml6, x7, x2, r8
; CHECK-NEXT:    vshift x10, x10, x4, r24
; CHECK-NEXT:    vshift x3, x3, x9, r22
; CHECK-NEXT:    vshuffle x1, x4, x6, r2; vmac.f cml6, cml6, x10, x2, r8
; CHECK-NEXT:    vshuffle x3, x4, x6, r4; vmac.f cml7, cml7, x3, x2, r8
; CHECK-NEXT:    vshuffle x5, x8, x10, r2; vmul.f cml2, x1, x0, r8
; CHECK-NEXT:    vshuffle x9, x8, x10, r4
; CHECK-NEXT:    vlda x5, [p6], #64; vshift x8, x3, x5, r18
; CHECK-NEXT:    vlda x9, [p6], #64; vshift x11, x3, x5, r0
; CHECK-NEXT:    vldb x8, [p6], #64; vshift x11, x11, x9, r20; vmul.f cml0, x8, x0, r8
; CHECK-NEXT:    vlda x6, [p6], m2; vshift x4, x1, x3, r6
; CHECK-NEXT:    vst.conv.bf16.fp32 cml7, [p7], #64; vshift x6, x3, x5, r16
; CHECK-NEXT:    vst.conv.bf16.fp32 cml6, [p7], #64; vldb x8, [p6], #64; vshift x3, x1, x3, r0; vmac.f cml1, cml0, x11, x0, r8
; CHECK-NEXT:    vshift x4, x4, x5, r22
; CHECK-NEXT:    vshift x6, x6, x7, r24; vmac.f cml3, cml2, x3, x0, r8
; CHECK-NEXT:    vshuffle x7, x10, x5, r2
; CHECK-NEXT:    vshuffle x11, x10, x5, r4; vmac.f cml4, cml1, x6, x2, r8
; CHECK-NEXT:    vshuffle x1, x9, x8, r2; vmac.f cml5, cml3, x4, x2, r8
; CHECK-NEXT:    vshuffle x10, x9, x8, r4
; CHECK-NEXT:    vlda x1, [p6], #64; vshift x9, x11, x1, r18
; CHECK-NEXT:    vldb x7, [p6], #64; vshift x5, x11, x1, r0; vmac.f cml7, cml5, x7, x0, r8
; CHECK-NEXT:    vlda x10, [p6], #64; vshift x5, x5, x10, r20; vmac.f cml6, cml4, x9, x0, r8
; CHECK-NEXT:    vshift x4, x7, x11, r6
; CHECK-NEXT:    vldb.3d x4, [p6], d0; vshift x3, x11, x1, r16
; CHECK-NEXT:    vshift x11, x7, x11, r0; vmac.f cml6, cml6, x5, x0, r8
; CHECK-NEXT:    vshift x4, x4, x1, r22
; CHECK-NEXT:    vshift x3, x3, x6, r24; vmac.f cml7, cml7, x11, x0, r8
; CHECK-NEXT:    vshuffle x6, x8, x1, r2
; CHECK-NEXT:    vshuffle x5, x8, x1, r4; vmac.f cml6, cml6, x3, x2, r8
; CHECK-NEXT:    vshuffle x9, x7, x10, r2; vmac.f cml7, cml7, x4, x2, r8
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vshift x8, x5, x9, r18; nopv
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
; CHECK-NEXT:    lda lr, [sp, #-56]; vshuffle x11, x7, x10, r4 // 4-byte Folded Reload
; CHECK-NEXT:    lda p6, [sp, #-44]; vshift x1, x6, x5, r0; vmac.f cml7, cml7, x6, x2, r8 // 4-byte Folded Reload
; CHECK-NEXT:    lda r12, [sp, #-48]; vshift x7, x5, x9, r0; vmac.f cml6, cml6, x8, x2, r8 // 4-byte Folded Reload
; CHECK-NEXT:    lda r10, [sp, #-52]; vshift x7, x7, x11, r20 // 4-byte Folded Reload
; CHECK-NEXT:    lda r9:r8, [sp, #-64]; vshift x3, x6, x5, r6; vmac.f cml7, cml7, x1, x2, r8 // 8-byte Folded Reload
; CHECK-NEXT:    vshift x10, x5, x9, r16; vmac.f cml6, cml6, x7, x2, r8
; CHECK-NEXT:    vshift x10, x10, x4, r24
; CHECK-NEXT:    vshift x3, x3, x9, r22
; CHECK-NEXT:    vmac.f cml6, cml6, x10, x2, r8
; CHECK-NEXT:    vmac.f cml7, cml7, x3, x2, r8
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda p7, [sp, #-40] // 4-byte Folded Reload
; CHECK-NEXT:    paddxm [sp], #-64
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vst.conv.bf16.fp32 cml7, [p7], #64 // Delay Slot 4
; CHECK-NEXT:    vst.conv.bf16.fp32 cml6, [p7], #64 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %div_factor1 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 46
  %0 = load bfloat, ptr %div_factor1, align 2, !tbaa !4
  %splat.splatinsert.i.i.i.i.i.i = insertelement <32 x bfloat> poison, bfloat %0, i64 0
  %splat.splat.i.i.i.i.i.i = shufflevector <32 x bfloat> %splat.splatinsert.i.i.i.i.i.i, <32 x bfloat> poison, <32 x i32> zeroinitializer
  %1 = load i8, ptr %avgpool2d_params, align 64, !tbaa !8
  %conv = zext i8 %1 to i32
  %sub = add nsw i32 %conv, -2
  %conv2 = sitofp i32 %sub to bfloat
  %unpromotion = fmul bfloat %0, %conv2
  %splat.splatinsert.i.i.i.i.i.i278 = insertelement <32 x bfloat> poison, bfloat %unpromotion, i64 0
  %splat.splat.i.i.i.i.i.i279 = shufflevector <32 x bfloat> %splat.splatinsert.i.i.i.i.i.i278, <32 x bfloat> poison, <32 x i32> zeroinitializer
  %outer_loop_count = getelementptr inbounds i8, ptr %avgpool2d_params, i20 4
  %2 = load i16, ptr %outer_loop_count, align 4, !tbaa !12
  %conv4 = zext i16 %2 to i32
  %inc_Ky = getelementptr inbounds i8, ptr %avgpool2d_params, i20 28
  %3 = load i16, ptr %inc_Ky, align 4, !tbaa !13
  %idx.ext.i = sext i16 %3 to i20
  %shfl_0 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 40
  %4 = load i8, ptr %shfl_0, align 8, !tbaa !14
  %conv17 = sext i8 %4 to i32
  %shfl_1 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 41
  %5 = load i8, ptr %shfl_1, align 1, !tbaa !15
  %conv22 = sext i8 %5 to i32
  %shft_1 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 33
  %6 = load i8, ptr %shft_1, align 1, !tbaa !16
  %conv37 = sext i8 %6 to i32
  %mul.i.i.i = shl nsw i32 %conv37, 1
  %shft_2 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 34
  %7 = load i8, ptr %shft_2, align 2, !tbaa !17
  %conv42 = sext i8 %7 to i32
  %mul.i.i.i315 = shl nsw i32 %conv42, 1
  %shft_3 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 35
  %8 = load i8, ptr %shft_3, align 1, !tbaa !18
  %conv44 = sext i8 %8 to i32
  %mul.i.i.i331 = shl nsw i32 %conv44, 1
  %shft_4 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 36
  %9 = load i8, ptr %shft_4, align 4, !tbaa !19
  %conv46 = sext i8 %9 to i32
  %mul.i.i.i347 = shl nsw i32 %conv46, 1
  %shft_5 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 37
  %10 = load i8, ptr %shft_5, align 1, !tbaa !20
  %conv48 = sext i8 %10 to i32
  %mul.i.i.i363 = shl nsw i32 %conv48, 1
  %shft_6 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 38
  %11 = load i8, ptr %shft_6, align 2, !tbaa !21
  %conv50 = sext i8 %11 to i32
  %mul.i.i.i379 = shl nsw i32 %conv50, 1
  %shft_7 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 39
  %12 = load i8, ptr %shft_7, align 1, !tbaa !22
  %conv52 = sext i8 %12 to i32
  %mul.i.i.i395 = shl nsw i32 %conv52, 1
  %inc_A_0 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 30
  %13 = load i16, ptr %inc_A_0, align 2, !tbaa !23
  %idx.ext.i421 = sext i16 %13 to i20
  %iterator_incr2 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 24
  %14 = load i32, ptr %iterator_incr2, align 8, !tbaa !24
  %iterator_wrap0 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 16
  %15 = load i32, ptr %iterator_wrap0, align 16, !tbaa !25
  %iterator_incr0 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 8
  %16 = load i32, ptr %iterator_incr0, align 8, !tbaa !26
  %iterator_wrap1 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 20
  %17 = load i32, ptr %iterator_wrap1, align 4, !tbaa !27
  %iterator_incr1 = getelementptr inbounds i8, ptr %avgpool2d_params, i20 12
  %18 = load i32, ptr %iterator_incr1, align 4, !tbaa !28
  %19 = trunc i32 %14 to i20
  %20 = trunc i32 %16 to i20
  %21 = trunc i32 %18 to i20
  %22 = trunc i32 %15 to i20
  %23 = trunc i32 %17 to i20
  call void @llvm.set.loop.iterations.i32(i32 %conv4)
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body, %entry
  %input_ptr.0.in986 = phi ptr [ %ifm_ptr, %entry ], [ %114, %for.body ]
  %output_ptr.0.in985 = phi ptr [ %ofm_ptr, %entry ], [ %add.ptr.i726, %for.body ]
  %iterator_cnt0.0984 = phi i32 [ 0, %entry ], [ %111, %for.body ]
  %iterator_cnt1.0983 = phi i32 [ 0, %entry ], [ %113, %for.body ]
  %output_ptr.0988 = addrspacecast ptr %output_ptr.0.in985 to ptr addrspace(5)
  %input_ptr.0 = addrspacecast ptr %input_ptr.0.in986 to ptr addrspace(5)
  %24 = load <16 x i32>, ptr addrspace(5) %input_ptr.0, align 64, !tbaa !29, !noalias !30
  %add.ptr.i = getelementptr inbounds i8, ptr %input_ptr.0.in986, i20 64
  %add.ptr.ascast.i = addrspacecast ptr %add.ptr.i to ptr addrspace(5)
  %25 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i, align 64, !tbaa !29, !noalias !37
  %add.ptr.i280 = getelementptr inbounds i8, ptr %input_ptr.0.in986, i20 128
  %add.ptr.ascast.i281 = addrspacecast ptr %add.ptr.i280 to ptr addrspace(5)
  %26 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i281, align 64, !tbaa !29, !noalias !44
  %add.ptr.i282 = getelementptr inbounds i8, ptr %input_ptr.0.in986, i20 192
  %add.ptr.ascast.i283 = addrspacecast ptr %add.ptr.i282 to ptr addrspace(5)
  %27 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i283, align 64, !tbaa !29, !noalias !51
  %add.ptr.i284 = getelementptr inbounds i8, ptr %input_ptr.0.in986, i20 256
  %add.ptr.ascast.i285 = addrspacecast ptr %add.ptr.i284 to ptr addrspace(5)
  %28 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i285, align 64, !tbaa !29, !noalias !58
  %add.ptr.i286 = getelementptr inbounds i8, ptr %add.ptr.i284, i20 %idx.ext.i
  %add.ptr.ascast.i287 = addrspacecast ptr %add.ptr.i286 to ptr addrspace(5)
  %29 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %24, <16 x i32> %25, i32 range(i32 -128, 128) %conv17)
  %30 = bitcast <16 x i32> %29 to <32 x bfloat>
  %31 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %24, <16 x i32> %25, i32 range(i32 -128, 128) %conv22)
  %32 = bitcast <16 x i32> %31 to <32 x bfloat>
  %33 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %26, <16 x i32> %27, i32 range(i32 -128, 128) %conv17)
  %34 = bitcast <16 x i32> %33 to <32 x bfloat>
  %35 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %26, <16 x i32> %27, i32 range(i32 -128, 128) %conv22)
  %36 = bitcast <16 x i32> %35 to <32 x bfloat>
  %37 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %30, <32 x bfloat> %32, i32 0, i32 %mul.i.i.i)
  %38 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %32, <32 x bfloat> %34, i32 0, i32 %mul.i.i.i)
  %39 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %30, <32 x bfloat> %32, i32 0, i32 %mul.i.i.i315)
  %40 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %32, <32 x bfloat> %34, i32 0, i32 %mul.i.i.i331)
  %41 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %32, <32 x bfloat> %34, i32 0, i32 %mul.i.i.i347)
  %42 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %38, <32 x bfloat> %36, i32 0, i32 %mul.i.i.i363)
  %43 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %39, <32 x bfloat> %34, i32 0, i32 %mul.i.i.i379)
  %44 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %40, <32 x bfloat> %28, i32 0, i32 %mul.i.i.i395)
  %45 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat> %30, <32 x bfloat> %splat.splat.i.i.i.i.i.i, i32 50332476)
  %46 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %37, <32 x bfloat> %splat.splat.i.i.i.i.i.i, <32 x float> %45, i32 50332476)
  %47 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %43, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %46, i32 50332476)
  %48 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat> %41, <32 x bfloat> %splat.splat.i.i.i.i.i.i, i32 50332476)
  %49 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %42, <32 x bfloat> %splat.splat.i.i.i.i.i.i, <32 x float> %48, i32 50332476)
  %50 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %44, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %49, i32 50332476)
  %51 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i287, align 64, !tbaa !29, !noalias !65
  %add.ptr.i413 = getelementptr inbounds i8, ptr %add.ptr.i286, i20 64
  %add.ptr.ascast.i414 = addrspacecast ptr %add.ptr.i413 to ptr addrspace(5)
  %52 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i414, align 64, !tbaa !29, !noalias !72
  %add.ptr.i415 = getelementptr inbounds i8, ptr %add.ptr.i286, i20 128
  %add.ptr.ascast.i416 = addrspacecast ptr %add.ptr.i415 to ptr addrspace(5)
  %53 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i416, align 64, !tbaa !29, !noalias !79
  %add.ptr.i417 = getelementptr inbounds i8, ptr %add.ptr.i286, i20 192
  %add.ptr.ascast.i418 = addrspacecast ptr %add.ptr.i417 to ptr addrspace(5)
  %54 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i418, align 64, !tbaa !29, !noalias !86
  %add.ptr.i419 = getelementptr inbounds i8, ptr %add.ptr.i286, i20 256
  %add.ptr.ascast.i420 = addrspacecast ptr %add.ptr.i419 to ptr addrspace(5)
  %55 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i420, align 64, !tbaa !29, !noalias !93
  %add.ptr.i422 = getelementptr inbounds i8, ptr %add.ptr.i419, i20 %idx.ext.i421
  %add.ptr.ascast.i423 = addrspacecast ptr %add.ptr.i422 to ptr addrspace(5)
  %56 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %51, <16 x i32> %52, i32 range(i32 -128, 128) %conv17)
  %57 = bitcast <16 x i32> %56 to <32 x bfloat>
  %58 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %51, <16 x i32> %52, i32 range(i32 -128, 128) %conv22)
  %59 = bitcast <16 x i32> %58 to <32 x bfloat>
  %60 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %53, <16 x i32> %54, i32 range(i32 -128, 128) %conv17)
  %61 = bitcast <16 x i32> %60 to <32 x bfloat>
  %62 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %53, <16 x i32> %54, i32 range(i32 -128, 128) %conv22)
  %63 = bitcast <16 x i32> %62 to <32 x bfloat>
  %64 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %57, <32 x bfloat> %59, i32 0, i32 %mul.i.i.i)
  %65 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %59, <32 x bfloat> %61, i32 0, i32 %mul.i.i.i)
  %66 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %57, <32 x bfloat> %59, i32 0, i32 %mul.i.i.i315)
  %67 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %59, <32 x bfloat> %61, i32 0, i32 %mul.i.i.i331)
  %68 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %59, <32 x bfloat> %61, i32 0, i32 %mul.i.i.i347)
  %69 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %65, <32 x bfloat> %63, i32 0, i32 %mul.i.i.i363)
  %70 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %66, <32 x bfloat> %61, i32 0, i32 %mul.i.i.i379)
  %71 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %67, <32 x bfloat> %55, i32 0, i32 %mul.i.i.i395)
  %72 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %57, <32 x bfloat> %splat.splat.i.i.i.i.i.i, <32 x float> %47, i32 50332476)
  %73 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %64, <32 x bfloat> %splat.splat.i.i.i.i.i.i, <32 x float> %72, i32 50332476)
  %74 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %70, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %73, i32 50332476)
  %75 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %68, <32 x bfloat> %splat.splat.i.i.i.i.i.i, <32 x float> %50, i32 50332476)
  %76 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %69, <32 x bfloat> %splat.splat.i.i.i.i.i.i, <32 x float> %75, i32 50332476)
  %77 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %71, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %76, i32 50332476)
  %78 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i423, align 64, !tbaa !29, !noalias !100
  %add.ptr.i570 = getelementptr inbounds i8, ptr %add.ptr.i422, i20 64
  %add.ptr.ascast.i571 = addrspacecast ptr %add.ptr.i570 to ptr addrspace(5)
  %79 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i571, align 64, !tbaa !29, !noalias !107
  %add.ptr.i572 = getelementptr inbounds i8, ptr %add.ptr.i422, i20 128
  %add.ptr.ascast.i573 = addrspacecast ptr %add.ptr.i572 to ptr addrspace(5)
  %80 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i573, align 64, !tbaa !29, !noalias !114
  %add.ptr.i574 = getelementptr inbounds i8, ptr %add.ptr.i422, i20 192
  %add.ptr.ascast.i575 = addrspacecast ptr %add.ptr.i574 to ptr addrspace(5)
  %81 = load <16 x i32>, ptr addrspace(5) %add.ptr.ascast.i575, align 64, !tbaa !29, !noalias !121
  %add.ptr.i576 = getelementptr inbounds i8, ptr %add.ptr.i422, i20 256
  %add.ptr.ascast.i577 = addrspacecast ptr %add.ptr.i576 to ptr addrspace(5)
  %82 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i577, align 64, !tbaa !29, !noalias !128
  %83 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %78, <16 x i32> %79, i32 range(i32 -128, 128) %conv17)
  %84 = bitcast <16 x i32> %83 to <32 x bfloat>
  %85 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %78, <16 x i32> %79, i32 range(i32 -128, 128) %conv22)
  %86 = bitcast <16 x i32> %85 to <32 x bfloat>
  %87 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %80, <16 x i32> %81, i32 range(i32 -128, 128) %conv17)
  %88 = bitcast <16 x i32> %87 to <32 x bfloat>
  %89 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %80, <16 x i32> %81, i32 range(i32 -128, 128) %conv22)
  %90 = bitcast <16 x i32> %89 to <32 x bfloat>
  %91 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %84, <32 x bfloat> %86, i32 0, i32 %mul.i.i.i)
  %92 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %86, <32 x bfloat> %88, i32 0, i32 %mul.i.i.i)
  %93 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %84, <32 x bfloat> %86, i32 0, i32 %mul.i.i.i315)
  %94 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %86, <32 x bfloat> %88, i32 0, i32 %mul.i.i.i331)
  %95 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %86, <32 x bfloat> %88, i32 0, i32 %mul.i.i.i347)
  %96 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %92, <32 x bfloat> %90, i32 0, i32 %mul.i.i.i363)
  %97 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %93, <32 x bfloat> %88, i32 0, i32 %mul.i.i.i379)
  %98 = tail call noundef <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat> %94, <32 x bfloat> %82, i32 0, i32 %mul.i.i.i395)
  %99 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %84, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %74, i32 50332476)
  %100 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %91, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %99, i32 50332476)
  %101 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %97, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %100, i32 50332476)
  %102 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %95, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %77, i32 50332476)
  %103 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %96, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %102, i32 50332476)
  %104 = tail call noundef <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat> %98, <32 x bfloat> %splat.splat.i.i.i.i.i.i279, <32 x float> %103, i32 50332476)
  %105 = tail call noundef <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float> %101)
  store <32 x bfloat> %105, ptr addrspace(5) %output_ptr.0988, align 64, !tbaa !29
  %add.ptr.i724 = getelementptr inbounds i8, ptr %output_ptr.0.in985, i20 64
  %add.ptr.ascast.i725 = addrspacecast ptr %add.ptr.i724 to ptr addrspace(5)
  %106 = tail call noundef <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float> %104)
  store <32 x bfloat> %106, ptr addrspace(5) %add.ptr.ascast.i725, align 64, !tbaa !29
  %add.ptr.i726 = getelementptr inbounds i8, ptr %output_ptr.0.in985, i20 128
  %107 = trunc i32 %iterator_cnt0.0984 to i20
  %108 = trunc i32 %iterator_cnt1.0983 to i20
  %109 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %add.ptr.i576, i20 %19, i20 %20, i20 %21, i20 %22, i20 %107, i20 %23, i20 %108)
  %110 = extractvalue { ptr, i20, i20 } %109, 1
  %111 = zext i20 %110 to i32
  %112 = extractvalue { ptr, i20, i20 } %109, 2
  %113 = zext i20 %112 to i32
  %114 = extractvalue { ptr, i20, i20 } %109, 0
  %115 = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %115, label %for.body, label %for.cond.cleanup, !llvm.loop !135
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x bfloat> @llvm.aie2ps.vshift.bf512.bf512(<32 x bfloat>, <32 x bfloat>, i32, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf(<32 x bfloat>, <32 x bfloat>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x float> @llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf(<32 x bfloat>, <32 x bfloat>, <32 x float>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #1

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare void @llvm.set.loop.iterations.i32(i32) #3

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare i1 @llvm.loop.decrement.i32(i32) #3

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { mustprogress noinline "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #3 = { nocallback noduplicate nofree nosync nounwind willreturn }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 21.0.0git (https://gitenterprise.xilinx.com/FaaSApps/llvm-aie 94899d95096e3c6765e4f7627e7211408721aaf6)"}
!4 = !{!5, !5, i64 0}
!5 = !{!"__bf16", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C++ TBAA"}
!8 = !{!9, !6, i64 0}
!9 = !{!"_ZTS25avgpool2d_internal_paramsI8bfloat16E", !6, i64 0, !6, i64 1, !6, i64 2, !10, i64 4, !11, i64 8, !11, i64 12, !11, i64 16, !11, i64 20, !11, i64 24, !10, i64 28, !10, i64 30, !6, i64 32, !6, i64 33, !6, i64 34, !6, i64 35, !6, i64 36, !6, i64 37, !6, i64 38, !6, i64 39, !6, i64 40, !6, i64 41, !10, i64 42, !6, i64 44, !5, i64 46, !6, i64 48}
!10 = !{!"short", !6, i64 0}
!11 = !{!"int", !6, i64 0}
!12 = !{!9, !10, i64 4}
!13 = !{!9, !10, i64 28}
!14 = !{!9, !6, i64 40}
!15 = !{!9, !6, i64 41}
!16 = !{!9, !6, i64 33}
!17 = !{!9, !6, i64 34}
!18 = !{!9, !6, i64 35}
!19 = !{!9, !6, i64 36}
!20 = !{!9, !6, i64 37}
!21 = !{!9, !6, i64 38}
!22 = !{!9, !6, i64 39}
!23 = !{!9, !10, i64 30}
!24 = !{!9, !11, i64 24}
!25 = !{!9, !11, i64 16}
!26 = !{!9, !11, i64 8}
!27 = !{!9, !11, i64 20}
!28 = !{!9, !11, i64 12}
!29 = !{!6, !6, i64 0}
!30 = !{!31, !33, !35}
!31 = distinct !{!31, !32, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!32 = distinct !{!32, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!33 = distinct !{!33, !34, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!34 = distinct !{!34, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!35 = distinct !{!35, !36, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!36 = distinct !{!36, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!37 = !{!38, !40, !42}
!38 = distinct !{!38, !39, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!39 = distinct !{!39, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!40 = distinct !{!40, !41, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!41 = distinct !{!41, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!42 = distinct !{!42, !43, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!43 = distinct !{!43, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!44 = !{!45, !47, !49}
!45 = distinct !{!45, !46, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!46 = distinct !{!46, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!47 = distinct !{!47, !48, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!48 = distinct !{!48, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!49 = distinct !{!49, !50, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!50 = distinct !{!50, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!51 = !{!52, !54, !56}
!52 = distinct !{!52, !53, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!53 = distinct !{!53, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!54 = distinct !{!54, !55, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!55 = distinct !{!55, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!56 = distinct !{!56, !57, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!57 = distinct !{!57, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!58 = !{!59, !61, !63}
!59 = distinct !{!59, !60, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!60 = distinct !{!60, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!61 = distinct !{!61, !62, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!62 = distinct !{!62, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!63 = distinct !{!63, !64, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!64 = distinct !{!64, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!65 = !{!66, !68, !70}
!66 = distinct !{!66, !67, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!67 = distinct !{!67, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!68 = distinct !{!68, !69, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!69 = distinct !{!69, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!70 = distinct !{!70, !71, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!71 = distinct !{!71, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!72 = !{!73, !75, !77}
!73 = distinct !{!73, !74, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!74 = distinct !{!74, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!75 = distinct !{!75, !76, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!76 = distinct !{!76, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!77 = distinct !{!77, !78, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!78 = distinct !{!78, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!79 = !{!80, !82, !84}
!80 = distinct !{!80, !81, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!81 = distinct !{!81, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!82 = distinct !{!82, !83, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!83 = distinct !{!83, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!84 = distinct !{!84, !85, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!85 = distinct !{!85, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!86 = !{!87, !89, !91}
!87 = distinct !{!87, !88, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!88 = distinct !{!88, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!89 = distinct !{!89, !90, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!90 = distinct !{!90, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!91 = distinct !{!91, !92, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!92 = distinct !{!92, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!93 = !{!94, !96, !98}
!94 = distinct !{!94, !95, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!95 = distinct !{!95, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!96 = distinct !{!96, !97, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!97 = distinct !{!97, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!98 = distinct !{!98, !99, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!99 = distinct !{!99, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!100 = !{!101, !103, !105}
!101 = distinct !{!101, !102, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!102 = distinct !{!102, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!103 = distinct !{!103, !104, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!104 = distinct !{!104, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!105 = distinct !{!105, !106, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!106 = distinct !{!106, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!107 = !{!108, !110, !112}
!108 = distinct !{!108, !109, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!109 = distinct !{!109, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!110 = distinct !{!110, !111, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!111 = distinct !{!111, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!112 = distinct !{!112, !113, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!113 = distinct !{!113, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!114 = !{!115, !117, !119}
!115 = distinct !{!115, !116, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!116 = distinct !{!116, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!117 = distinct !{!117, !118, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!118 = distinct !{!118, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!119 = distinct !{!119, !120, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!120 = distinct !{!120, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!121 = !{!122, !124, !126}
!122 = distinct !{!122, !123, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!123 = distinct !{!123, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!124 = distinct !{!124, !125, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!125 = distinct !{!125, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!126 = distinct !{!126, !127, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!127 = distinct !{!127, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!128 = !{!129, !131, !133}
!129 = distinct !{!129, !130, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
!130 = distinct !{!130, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
!131 = distinct !{!131, !132, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
!132 = distinct !{!132, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
!133 = distinct !{!133, !134, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
!134 = distinct !{!134, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
!135 = distinct !{!135, !136, !137}
!136 = !{!"llvm.loop.mustprogress"}
!137 = !{!"llvm.loop.itercount.range", i64 3}
