; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; Baseline test: loop that loads 4 bytes from separate pointers, packs them
; into a 32-bit word via build_vector <4 x i8>, and does a scalar store.
; Checks that the postpipeliner can schedule this loop.
;
; RUN: llc -O2 -mtriple=aie2ps %s -o - | FileCheck %s

define void @build_v4i8_loop(ptr noalias %p0, ptr noalias %p1, ptr noalias %p2, ptr noalias %p3, ptr noalias %dst) {
; CHECK-LABEL: build_v4i8_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #32; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    lda.u8 r6, [p1], #1; nopb ; movxm ls, #.LBB0_1
; CHECK-NEXT:    lda.u8 r2, [p0], #1; movxm le, #.L_LEnd0
; CHECK-NEXT:    lda.s8 r4, [p2], #1; add.nc lc, r1, #-1; mov r0, #8
; CHECK-NEXT:  .LBB0_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lda.s8 r16, [p3], #1; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; lshl r6, r6, r0; nopm ; nopv
; CHECK-NEXT:    or r6, r2, r6
; CHECK-NEXT:    movx r29, #2; vinsert.32 x0, x0, #0, r6
; CHECK-NEXT:    mova r29, #3; vinsert.8 x2, x0, r29, r4
; CHECK-NEXT:    vinsert.8 x4, x2, r29, r16
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda.u8 r6, [p1], #1; vextract.32 r16, x4, #0, vaddsign1
; CHECK-NEXT:    lda.u8 r2, [p0], #1
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    lda.s8 r4, [p2], #1; nopb ; st r16, [p4], #4; nopxm ; nopv
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    lda.s8 r16, [p3], #1; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lshl r0, r6, r0
; CHECK-NEXT:    or r0, r2, r0
; CHECK-NEXT:    movx r29, #2; vinsert.32 x0, x0, #0, r0
; CHECK-NEXT:    mova r29, #3; vinsert.8 x0, x0, r29, r4
; CHECK-NEXT:    ret lr; vinsert.8 x0, x0, r29, r16
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vextract.32 r0, x0, #0, vaddsign1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    st r0, [p4], #4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  br label %for.body

for.body:
  %i = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %a0 = phi ptr [ %p0, %entry ], [ %a0.next, %for.body ]
  %a1 = phi ptr [ %p1, %entry ], [ %a1.next, %for.body ]
  %a2 = phi ptr [ %p2, %entry ], [ %a2.next, %for.body ]
  %a3 = phi ptr [ %p3, %entry ], [ %a3.next, %for.body ]
  %out = phi ptr [ %dst, %entry ], [ %out.next, %for.body ]

  %b0 = load i8, ptr %a0, align 1
  %b1 = load i8, ptr %a1, align 1
  %b2 = load i8, ptr %a2, align 1
  %b3 = load i8, ptr %a3, align 1

  %v0 = insertelement <4 x i8> poison, i8 %b0, i64 0
  %v1 = insertelement <4 x i8> %v0, i8 %b1, i64 1
  %v2 = insertelement <4 x i8> %v1, i8 %b2, i64 2
  %v3 = insertelement <4 x i8> %v2, i8 %b3, i64 3

  store <4 x i8> %v3, ptr %out, align 4

  %a0.next = getelementptr inbounds i8, ptr %a0, i20 1
  %a1.next = getelementptr inbounds i8, ptr %a1, i20 1
  %a2.next = getelementptr inbounds i8, ptr %a2, i20 1
  %a3.next = getelementptr inbounds i8, ptr %a3, i20 1
  %out.next = getelementptr inbounds i8, ptr %out, i20 4

  %inc = add nuw nsw i32 %i, 1
  %exitcond = icmp eq i32 %inc, 32
  br i1 %exitcond, label %for.exit, label %for.body, !llvm.loop !0

for.exit:
  ret void
}

!0 = distinct !{!0, !1, !2, !3}
!1 = !{!"llvm.loop.mustprogress"}
!2 = !{!"llvm.loop.itercount.range", i64 32}
!3 = !{!"llvm.loop.unroll.disable"}
