# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Postpipeliner test with MOV r29 pre-expanded to MOVX (ALU slot).
# This avoids the multi-slot materializer assigning MOVA (LDA slot)
# which would give ResMII=5 instead of 4. With both MOVs on ALU:
# LDA=4, ALU=4, MV=4 → ResMII=4, and the postpipeliner achieves II=4.
#
# RUN: llc --mtriple=aie2ps -O2 --start-before=postmisched %s -o - | FileCheck %s
--- |
  source_filename = "build-vector-v4i8-loop-postpipeliner-movx.mir"
  target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
  target triple = "aie2ps"

  define void @build_v4i8_loop(ptr noalias %p0, ptr noalias %p1, ptr noalias %p2, ptr noalias %p3, ptr noalias %dst) {
  ; CHECK-LABEL: build_v4i8_loop:
  ; CHECK:       // %bb.0: // %entry
  ; CHECK-NEXT:    lda.u8 r4, [p1], #1
  ; CHECK-NEXT:    lda.u8 r2, [p0], #1
  ; CHECK-NEXT:    lda.s8 r6, [p2], #1
  ; CHECK-NEXT:    lda.s8 r16, [p3], #1; movx r1, #32
  ; CHECK-NEXT:    lda.u8 r4, [p1], #1; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    lda.u8 r2, [p0], #1; movxm le, #.L_LEnd0
  ; CHECK-NEXT:    lda.s8 r6, [p2], #1; add.nc lc, r1, #-4; mov r0, #8
  ; CHECK-NEXT:    lda.s8 r16, [p3], #1; nopb ; lshl r18, r4, r0
  ; CHECK-NEXT:    lda.u8 r4, [p1], #1; or r20, r2, r18
  ; CHECK-NEXT:    lda.u8 r2, [p0], #1; movx r29, #2; vinsert.32 x0, x0, #0, r20
  ; CHECK-NEXT:    lda.s8 r6, [p2], #1; movx r29, #3; vinsert.8 x2, x0, r29, r6
  ; CHECK-NEXT:    lda.s8 r16, [p3], #1; lshl r18, r4, r0; vinsert.8 x4, x2, r29, r16
  ; CHECK-NEXT:    lda.u8 r4, [p1], #1; or r20, r2, r18
  ; CHECK-NEXT:    lda.u8 r2, [p0], #1; movx r29, #2; vinsert.32 x0, x0, #0, r20
  ; CHECK-NEXT:    lda.s8 r6, [p2], #1; movx r29, #3; vinsert.8 x2, x0, r29, r6
  ; CHECK-NEXT:    lda.s8 r16, [p3], #1; lshl r18, r4, r0; vinsert.8 x4, x2, r29, r16
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    lda.u8 r4, [p1], #1; or r20, r2, r18; vextract.32 r22, x4, #0, vaddsign1
  ; CHECK-NEXT:    lda.u8 r2, [p0], #1; movx r29, #2; vinsert.32 x0, x0, #0, r20
  ; CHECK-NEXT:    lda.s8 r6, [p2], #1; st r22, [p4], #4; movx r29, #3; vinsert.8 x2, x0, r29, r6
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    lda.s8 r16, [p3], #1; nopb ; nops ; lshl r18, r4, r0; vinsert.8 x4, x2, r29, r16; nopv
  ; CHECK-NEXT:  // %bb.2: // %for.exit
  ; CHECK-NEXT:    nopa ; nopb ; or r20, r2, r18; vextract.32 r22, x4, #0, vaddsign1
  ; CHECK-NEXT:    movx r29, #2; vinsert.32 x0, x0, #0, r20
  ; CHECK-NEXT:    st r22, [p4], #4; movx r29, #3; vinsert.8 x2, x0, r29, r6
  ; CHECK-NEXT:    lshl r18, r4, r0; vinsert.8 x4, x2, r29, r16
  ; CHECK-NEXT:    or r20, r2, r18; vextract.32 r22, x4, #0, vaddsign1
  ; CHECK-NEXT:    movx r29, #2; vinsert.32 x0, x0, #0, r20
  ; CHECK-NEXT:    st r22, [p4], #4; movx r29, #3; vinsert.8 x2, x0, r29, r6
  ; CHECK-NEXT:    vinsert.8 x4, x2, r29, r16
  ; CHECK-NEXT:    vextract.32 r22, x4, #0, vaddsign1
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    st r22, [p4], #4
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vextract.32 r22, x4, #0, vaddsign1
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    st r22, [p4], #4
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    call void @llvm.set.loop.iterations.i32(i32 32)
    br label %for.body

  for.body:                                         ; preds = %for.body, %entry
    %a0 = phi ptr [ %p0, %entry ], [ %a0.next, %for.body ]
    %a1 = phi ptr [ %p1, %entry ], [ %a1.next, %for.body ]
    %a2 = phi ptr [ %p2, %entry ], [ %a2.next, %for.body ]
    %a3 = phi ptr [ %p3, %entry ], [ %a3.next, %for.body ]
    %out = phi ptr [ %dst, %entry ], [ %out.next, %for.body ]
    %b0 = load i8, ptr %a0, align 1
    %b1 = load i8, ptr %a1, align 1
    %b2 = load i8, ptr %a2, align 1
    %b3 = load i8, ptr %a3, align 1
    %v0 = insertelement <4 x i8> poison, i8 %b0, i64 0
    %v1 = insertelement <4 x i8> %v0, i8 %b1, i64 1
    %v2 = insertelement <4 x i8> %v1, i8 %b2, i64 2
    %v3 = insertelement <4 x i8> %v2, i8 %b3, i64 3
    store <4 x i8> %v3, ptr %out, align 4
    %a0.next = getelementptr inbounds i8, ptr %a0, i20 1
    %a1.next = getelementptr inbounds i8, ptr %a1, i20 1
    %a2.next = getelementptr inbounds i8, ptr %a2, i20 1
    %a3.next = getelementptr inbounds i8, ptr %a3, i20 1
    %out.next = getelementptr inbounds i8, ptr %out, i20 4
    %0 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %0, label %for.body, label %for.exit, !llvm.loop !0

  for.exit:                                         ; preds = %for.body
    ret void
  }

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare void @llvm.set.loop.iterations.i32(i32) #0

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare i1 @llvm.loop.decrement.i32(i32) #0

  attributes #0 = { nocallback noduplicate nofree nosync nounwind willreturn }

  !0 = distinct !{!0, !1, !2, !3}
  !1 = !{!"llvm.loop.mustprogress"}
  !2 = !{!"llvm.loop.itercount.range", i64 32}
  !3 = !{!"llvm.loop.unroll.disable"}

...
---
name:            build_v4i8_loop
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: true
registers:       []
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: true
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $p2, $p3, $p4

    renamable $r1 = MOV_RLC_imm11_pseudo 32
    $lc = ADD_NC_add_lc_ri $r1, 0
    MOVXM_lng_cg_ls_abs %bb.1, implicit-def $ls
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le
    renamable $r0 = MOV_RLC_imm11_pseudo 8

  bb.1.for.body:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p0, $p1, $p2, $p3, $p4, $r0

    renamable $r2, renamable $p0 = LDA_u8_pstm_nrm_imm killed renamable $p0, 1 :: (load (s8) from %ir.a0)
    renamable $r4, renamable $p1 = LDA_u8_pstm_nrm_imm killed renamable $p1, 1 :: (load (s8) from %ir.a1)
    renamable $r6, renamable $p2 = LDA_s8_pstm_nrm_imm killed renamable $p2, 1 :: (load (s8) from %ir.a2)
    renamable $r16, renamable $p3 = LDA_s8_pstm_nrm_imm killed renamable $p3, 1 :: (load (s8) from %ir.a3)
    renamable $r18 = LSHL killed renamable $r4, renamable $r0
    renamable $r20 = OR killed renamable $r2, killed renamable $r18
    renamable $x0 = VINSERT_32_mIdxImm0 undef renamable $x0, killed renamable $r20
    renamable $r29 = MOVX_alu_cg_or 2
    renamable $x2 = VINSERT_8_mR29_insert killed renamable $x0, killed renamable $r29, killed renamable $r6
    renamable $r29 = MOVX_alu_cg_or 3
    renamable $x4 = VINSERT_8_mR29_insert killed renamable $x2, killed renamable $r29, killed renamable $r16
    renamable $r22 = VEXTRACT_32_vec_extract_imm_vaddSign1 killed renamable $x4, 0, implicit $vaddsign1
    renamable $p4 = ST_dms_sts_scalar_st_pstm_nrm_imm killed renamable $r22, killed renamable $p4, 4 :: (store (s32) into %ir.out)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2.for.exit:
    RET implicit $lr
    DelayedSchedBarrier

...
