# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2ps -run-pass=postmisched %s -o - 2>&1 | FileCheck %s
#
# Loop for.body266.i (bb.8) from Conv2D_bf16_OC8_AIE2ps_0.ll.
# 15 instructions: 1 POPX + 3 normal pops + 2 weight loads + 4 shuffles
#                  + 4 VMACs + PADD_3D.
# The post-pipeliner should find II=5 (NS=3) for this loop.

--- |
  target triple = "aie2ps"

  define void @conv2d_inner_loop() !dbg !3 {
  entry:
    br label %for.body208.i
  for.body208.i:
    call void @llvm.set.loop.iterations.i32(i32 0)
    br label %for.body266.i, !dbg !5
  for.body266.i:
    %dec = call i1 @llvm.loop.decrement.i32(i32 1), !dbg !5
    br i1 %dec, label %for.body266.i, label %for.cond.cleanup265.i, !dbg !5, !llvm.loop !6
  for.cond.cleanup265.i:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !llvm.dbg.cu = !{!0}
  !llvm.module.flags = !{!2}
  !0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: NoDebug)
  !1 = !DIFile(filename: "conv2d_bf16.h", directory: "")
  !2 = !{i32 2, !"Debug Info Version", i32 3}
  !3 = distinct !DISubprogram(name: "conv2d_bf16", scope: !1, file: !1, line: 2834, type: !4, scopeLine: 2834, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0)
  !4 = !DISubroutineType(types: !{})
  !5 = !DILocation(line: 2834, column: 17, scope: !3)
  !6 = distinct !{!6, !7}
  !7 = !{!"llvm.loop.itercount.range", i64 4}
...
---
name:            conv2d_inner_loop
alignment:       16
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
body:             |
  ; CHECK-LABEL: name: conv2d_inner_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml2, $cml3, $m4, $m5, $p1, $r5, $r8, $r10, $r12, $r18, $r30, $x0, $x2, $d1_3d, $p0, $lf0, $r24, $lfe
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body208.i:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml2, $cml3, $m4, $m5, $p1, $r5, $r8, $r10, $r12, $r18, $r30, $x0, $x2, $d1_3d, $p0, $lf0, $r24, $lfe
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $x5, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, killed $p0, killed $lf0, killed $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $lfe, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:   $x3, $p0, $lf0, $r24 = VLDA_POP_dmx_lda_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:   $x6, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:   BUNDLE implicit-def $x10, implicit-def $wl10, implicit-def $wh10, implicit-def $p1, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $srfifo_uf, implicit killed $p1, implicit killed $p0, implicit killed $lf0, implicit killed $r24, debug-location !6 {
  ; CHECK-NEXT:     renamable $x10, renamable $p1 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p1, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $x1, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x11, implicit-def $wl11, implicit-def $wh11, implicit-def $p1, implicit-def $p0, implicit-def $dc1, implicit-def $dc5, implicit killed $p1, implicit killed $p0, implicit $d1_3d, debug-location !6 {
  ; CHECK-NEXT:     renamable $x11, renamable $p1 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p1, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $p0, $dc1, $dc5 = PADDS_3D killed $p0, $d1_3d, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x5, implicit-def $wl5, implicit-def $wh5, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit-def $lc, implicit $r30, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit killed $lfe, implicit killed $r5, debug-location !6 {
  ; CHECK-NEXT:     $x5, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, killed $p0, killed $lf0, killed $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $lfe, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     $lc = ADD_NC_add_lc_ri killed $r5, -2, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x3, implicit-def $wl3, implicit-def $wh3, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $srfifo_uf, implicit-def $ls, implicit killed $p0, implicit killed $lf0, implicit killed $r24, debug-location !6 {
  ; CHECK-NEXT:     $x3, $p0, $lf0, $r24 = VLDA_POP_dmx_lda_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     MOVXM_lng_cg_ls_abs %bb.2, implicit-def $ls, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $srfifo_uf, implicit-def $le, implicit killed $p0, implicit killed $lf0, implicit killed $r24, debug-location !6 {
  ; CHECK-NEXT:     $x6, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x10, implicit-def $wl10, implicit-def $wh10, implicit-def $p1, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $srfifo_uf, implicit killed $p1, implicit killed $p0, implicit killed $lf0, implicit killed $r24, debug-location !6 {
  ; CHECK-NEXT:     renamable $x10, renamable $p1 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p1, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $x1, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x11, implicit-def $wl11, implicit-def $wh11, implicit-def $p1, implicit-def $p0, implicit-def $dc1, implicit-def $dc5, implicit-def $x7, implicit-def $wl7, implicit-def $wh7, implicit killed $p1, implicit killed $p0, implicit $d1_3d, implicit killed $x5, implicit killed $x3, implicit $r18, debug-location !6 {
  ; CHECK-NEXT:     renamable $x11, renamable $p1 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p1, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $p0, $dc1, $dc5 = PADDS_3D killed $p0, $d1_3d, debug-location !6
  ; CHECK-NEXT:     renamable $x7 = VSHUFFLE_vec_shuffle_x killed renamable $x5, killed renamable $x3, renamable $r18, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.body266.i:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT:   liveins: $lfe, $cml0, $cml1, $cml2, $cml3, $dc1, $dc5, $p1, $r8, $r12, $r18, $r30, $d1_3d, $p0, $lf0, $r24
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x5, implicit-def $wl5, implicit-def $wh5, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit $r30, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit killed $lfe, implicit killed $x3, implicit $r12, debug-location !6 {
  ; CHECK-NEXT:     $x5, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, killed $p0, killed $lf0, killed $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $lfe, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     renamable $x4 = VSHUFFLE_vec_shuffle_x internal renamable $x5, killed renamable $x3, renamable $r12, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x3, implicit-def $wl3, implicit-def $wh3, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $srfifo_uf, implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit-def $cml3, implicit-def $bmll3, implicit-def $bmlh3, implicit-def dead $srfpflags, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit killed $x6, implicit $x1, implicit $r18, implicit killed $cml3, implicit killed $x7, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     $x3, $p0, $lf0, $r24 = VLDA_POP_dmx_lda_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     renamable $x8 = VSHUFFLE_vec_shuffle_x killed renamable $x6, renamable $x1, renamable $r18, debug-location !6
  ; CHECK-NEXT:     $cml3 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml3, killed $x7, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $srfifo_uf, implicit-def $cml2, implicit-def $bmll2, implicit-def $bmlh2, implicit-def dead $srfpflags, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit killed $x1, implicit $r12, implicit killed $cml2, implicit killed $x4, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     $x6, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     renamable $x6 = VSHUFFLE_vec_shuffle_x internal renamable $x6, killed renamable $x1, renamable $r12, debug-location !6
  ; CHECK-NEXT:     $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, killed $x4, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x10, implicit-def $wl10, implicit-def $wh10, implicit-def $p1, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $srfifo_uf, implicit-def $cml1, implicit-def $bmll1, implicit-def $bmlh1, implicit-def dead $srfpflags, implicit killed $p1, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit killed $cml1, implicit killed $x8, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x10, renamable $p1 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p1, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $x1, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_x_normal_pop killed $p0, killed $lf0, killed $r24, implicit-def $srfifo_uf, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x8, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x11, implicit-def $wl11, implicit-def $wh11, implicit-def $p1, implicit-def $p0, implicit-def $dc1, implicit-def $dc5, implicit-def $x7, implicit-def $wl7, implicit-def $wh7, implicit-def $cml0, implicit-def $bmll0, implicit-def $bmlh0, implicit-def dead $srfpflags, implicit killed $p1, implicit killed $p0, implicit $d1_3d, implicit killed $x5, implicit killed $x3, implicit $r18, implicit killed $cml0, implicit killed $x6, implicit killed $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x11, renamable $p1 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p1, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $p0, $dc1, $dc5 = PADDS_3D killed $p0, $d1_3d, debug-location !6
  ; CHECK-NEXT:     renamable $x7 = VSHUFFLE_vec_shuffle_x killed renamable $x5, killed renamable $x3, renamable $r18, debug-location !6
  ; CHECK-NEXT:     $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x6, killed $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, debug-location !6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.cond.cleanup265.i:
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml2, $cml3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x4 = VSHUFFLE_vec_shuffle_x renamable $x5, renamable $x3, renamable $r12, debug-location !6
  ; CHECK-NEXT:   BUNDLE implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit-def $cml3, implicit-def $bmll3, implicit-def $bmlh3, implicit-def dead $srfpflags, implicit $x6, implicit $x1, implicit $r18, implicit killed $cml3, implicit killed $x7, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x6, renamable $x1, renamable $r18, debug-location !6
  ; CHECK-NEXT:     $cml3 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml3, killed $x7, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $cml2, implicit-def $bmll2, implicit-def $bmlh2, implicit-def dead $srfpflags, implicit killed $x6, implicit $x1, implicit $r12, implicit killed $cml2, implicit killed $x4, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x6 = VSHUFFLE_vec_shuffle_x killed renamable $x6, renamable $x1, renamable $r12, debug-location !6
  ; CHECK-NEXT:     $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, killed $x4, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x8, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   BUNDLE implicit-def $x7, implicit-def $wl7, implicit-def $wh7, implicit-def $cml0, implicit-def $bmll0, implicit-def $bmlh0, implicit-def dead $srfpflags, implicit $x5, implicit $x3, implicit $r18, implicit killed $cml0, implicit $x6, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x7 = VSHUFFLE_vec_shuffle_x renamable $x5, renamable $x3, renamable $r18, debug-location !6
  ; CHECK-NEXT:     $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, $x6, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   renamable $x4 = VSHUFFLE_vec_shuffle_x killed renamable $x5, killed renamable $x3, renamable $r12, debug-location !6
  ; CHECK-NEXT:   BUNDLE implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit-def $cml3, implicit-def $bmll3, implicit-def $bmlh3, implicit-def dead $srfpflags, implicit $x6, implicit $x1, implicit killed $r18, implicit killed $cml3, implicit killed $x7, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x6, renamable $x1, killed renamable $r18, debug-location !6
  ; CHECK-NEXT:     $cml3 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml3, killed $x7, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $cml2, implicit-def $bmll2, implicit-def $bmlh2, implicit-def dead $srfpflags, implicit killed $x6, implicit killed $x1, implicit killed $r12, implicit killed $cml2, implicit killed $x4, implicit $y5, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x6 = VSHUFFLE_vec_shuffle_x killed renamable $x6, killed renamable $x1, killed renamable $r12, debug-location !6
  ; CHECK-NEXT:     $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, killed $x4, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x8, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x6, killed $y5, killed $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $cml0, $cml1, $cml2, $cml3, $m4, $m5, $p1, $r5, $r8, $r10, $r12, $r18, $r30, $x0, $x2, $d1_3d, $p0, $lf0, $r24, $lfe

  bb.1.for.body208.i:
    successors: %bb.2(0x80000000)
    liveins: $cml0, $cml1, $cml2, $cml3, $m4, $m5, $p1, $r5, $r8, $r10, $r12, $r18, $r30, $x0, $x2, $d1_3d, $p0, $lf0, $r24, $lfe

    $lc = ADD_NC_add_lc_ri $r5, 0, debug-location !5
    MOVXM_lng_cg_ls_abs %bb.2, implicit-def $ls, debug-location !5
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le, debug-location !5

  bb.2.for.body266.i:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $lfe, $cml0, $cml1, $cml2, $cml3, $dc1, $dc5, $p1, $r8, $r12, $r18, $r30, $d1_3d, $p0, $lf0, $r24

    $x5, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, $p0, $lf0, $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe, debug-location !5 :: (load unknown-size, align 1)
    $x3, $p0, $lf0, $r24 = VLD_POP_512_normal_pop_pseudo $p0, $lf0, $r24, implicit-def $srfifo_uf, debug-location !5 :: (load unknown-size, align 1)
    $x6, $p0, $lf0, $r24 = VLD_POP_512_normal_pop_pseudo $p0, $lf0, $r24, implicit-def $srfifo_uf, debug-location !5 :: (load unknown-size, align 1)
    renamable $x10, renamable $p1 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p1, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    $x1, $p0, $lf0, $r24 = VLD_POP_512_normal_pop_pseudo $p0, $lf0, $r24, implicit-def $srfifo_uf, debug-location !5 :: (load unknown-size, align 1)
    renamable $x11, renamable $p1 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p1, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x7 = VSHUFFLE_vec_shuffle_x renamable $x5, renamable $x3, renamable $r18, debug-location !5
    renamable $x4 = VSHUFFLE_vec_shuffle_x killed renamable $x5, killed renamable $x3, renamable $r12, debug-location !5
    $cml3 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml3, killed $x7, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x6, renamable $x1, renamable $r18, debug-location !5
    renamable $x6 = VSHUFFLE_vec_shuffle_x killed renamable $x6, killed renamable $x1, renamable $r12, debug-location !5
    $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, killed $x4, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x8, $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x6, killed $y5, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $p0, $dc1, $dc5 = PADD_3D_pseudo $p0, $d1_3d, debug-location !5
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, debug-location !5

  bb.3.for.cond.cleanup265.i:
    liveins: $cml0, $cml1, $cml2, $cml3

    RET implicit $lr
    DelayedSchedBarrier
...
