# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2ps -O2 --start-before=postmisched %s -o - | FileCheck %s
#
# Conv2D fp16 inner loop with tight MinTripCount (4).
# 14 instructions: 1 POPX + 1 PADDB + 1 VLDB_POP + 4 weight loads (VLDA)
#                  + 2 shuffles + 4 VMACs + PADDB_3D.
# Materialize groups all weight loads on VLDA and all data
# loads on VLDB, eliminating memory bank conflicts.

--- |
  target triple = "aie2ps"

  define void @conv2d_fp16_inner_loop() !dbg !3 {
  ; CHECK-LABEL: conv2d_fp16_inner_loop:
  ; CHECK:       // %bb.0: // %entry
  ; CHECK-NEXT:  .LBB0_1: // %preheader
  ; CHECK-NEXT:    nopa ; vldb.popx x1, [p0, lf0, r24]; nops ; nopxm ; nopv
  ; CHECK-NEXT:    paddb [p0], m6
  ; CHECK-NEXT:    vldb.pop x10, [p0, lf0, r24, m6]; mov p5, p1
  ; CHECK-NEXT:    vlda x8, [p5], #64; paddb.3d [p0], d1
  ; CHECK-NEXT:    vlda x9, [p5], #64; vldb.popx x1, [p0, lf0, r24]
  ; CHECK-NEXT:    vlda x6, [p5], #64; paddb [p0], m6
  ; CHECK-NEXT:    vlda x7, [p5], #64; vldb.pop x10, [p0, lf0, r24, m6]; add.nc lc, r18, #-3
  ; CHECK-NEXT:    vlda x8, [p5], #64; paddb.3d [p0], d1; movxm ls, #.LBB0_2
  ; CHECK-NEXT:    vlda x9, [p5], #64; vldb.popx x1, [p0, lf0, r24]; nops ; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    vlda x6, [p5], #64; paddb [p0], m6; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x7, [p5], #64; vldb.pop x10, [p0, lf0, r24, m6]; nops ; nopx ; vshuffle x3, x1, x10, r22; nopv
  ; CHECK-NEXT:    vlda x8, [p5], #64; paddb.3d [p0], d1; nops ; nopx ; vshuffle x4, x1, x10, r20; nopv
  ; CHECK-NEXT:  .LBB0_2: // %loop_body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda x9, [p5], #64; vldb.popx x1, [p0, lf0, r24]; nops ; nopxm ; vmac.f cml5, cml5, x3, y4, r10
  ; CHECK-NEXT:    vlda x6, [p5], #64; paddb [p0], m6; nops ; nopxm ; vmac.f cml3, cml3, x4, y4, r10
  ; CHECK-NEXT:    vlda x7, [p5], #64; vldb.pop x10, [p0, lf0, r24, m6]; nops ; nopx ; vshuffle x3, x1, x10, r22; vmac.f cml1, cml1, x3, y3, r10
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    vlda x8, [p5], #64; paddb.3d [p0], d1; nops ; nopx ; vshuffle x4, x1, x10, r20; vmac.f cml0, cml0, x4, y3, r10
  ; CHECK-NEXT:  // %bb.3: // %exit
  ; CHECK-NEXT:    vlda x9, [p5], #64; nopb ; nopxm ; vmac.f cml5, cml5, x3, y4, r10
  ; CHECK-NEXT:    vlda x6, [p5], #64; vmac.f cml3, cml3, x4, y4, r10
  ; CHECK-NEXT:    vlda x7, [p5], #64; vshuffle x3, x1, x10, r22; vmac.f cml1, cml1, x3, y3, r10
  ; CHECK-NEXT:    vshuffle x4, x1, x10, r20; vmac.f cml0, cml0, x4, y3, r10
  ; CHECK-NEXT:    vmac.f cml5, cml5, x3, y4, r10
  ; CHECK-NEXT:    vmac.f cml3, cml3, x4, y4, r10
  ; CHECK-NEXT:    vshuffle x3, x1, x10, r22; vmac.f cml1, cml1, x3, y3, r10
  ; CHECK-NEXT:    vshuffle x4, x1, x10, r20; vmac.f cml0, cml0, x4, y3, r10
  ; CHECK-NEXT:    vmac.f cml5, cml5, x3, y4, r10
  ; CHECK-NEXT:    vmac.f cml3, cml3, x4, y4, r10
  ; CHECK-NEXT:    vmac.f cml1, cml1, x3, y3, r10
  ; CHECK-NEXT:    vmac.f cml0, cml0, x4, y3, r10
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    br label %preheader
  preheader:
    call void @llvm.set.loop.iterations.i32(i32 0)
    br label %loop_body, !dbg !5
  loop_body:
    %dec = call i1 @llvm.loop.decrement.i32(i32 1), !dbg !5
    br i1 %dec, label %loop_body, label %exit, !dbg !5, !llvm.loop !6
  exit:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !llvm.dbg.cu = !{!0}
  !llvm.module.flags = !{!2}
  !0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: NoDebug)
  !1 = !DIFile(filename: "conv2d_bf16.h", directory: "")
  !2 = !{i32 2, !"Debug Info Version", i32 3}
  !3 = distinct !DISubprogram(name: "conv2d_fp16", scope: !1, file: !1, line: 1, type: !4, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0)
  !4 = !DISubroutineType(types: !{})
  !5 = !DILocation(line: 1, column: 1, scope: !3)
  !6 = distinct !{!6, !7}
  !7 = !{!"llvm.loop.itercount.range", i64 4}
...
---
name:            conv2d_fp16_inner_loop
alignment:       16
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
body:             |
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $cml0, $cml1, $cml3, $cml5, $m6, $p1, $p5, $r10, $r18, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24, $lfe

  bb.1.preheader:
    successors: %bb.2(0x80000000)
    liveins: $cml0, $cml1, $cml3, $cml5, $m6, $p1, $p5, $r10, $r18, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24, $lfe

    $lc = ADD_NC_add_lc_ri $r18, 0, debug-location !5
    MOVXM_lng_cg_ls_abs %bb.2, implicit-def $ls, debug-location !5
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le, debug-location !5
    $p5 = MOV_scalar_pseudo $p1

  bb.2.loop_body:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $lfe, $cml0, $cml1, $cml3, $cml5, $m6, $p1, $p5, $r10, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24

    $x1, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, $p0, $lf0, $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe, debug-location !5 :: (load unknown-size, align 1)
    renamable $p0 = PADDB_pstm_nrm renamable $p0, renamable $m6, debug-location !5
    $x10, $p0, $lf0, $r24 = VLDB_POP_dmx_ldb_fifo_x_fifo_1d_pop $p0, $lf0, $r24, $m6, implicit-def $srfifo_uf, debug-location !5 :: (load unknown-size, align 1)
    renamable $x8, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x9, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x6, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x7, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x3 = VSHUFFLE_vec_shuffle_x renamable $x1, renamable $x10, renamable $r22, debug-location !5
    renamable $x4 = VSHUFFLE_vec_shuffle_x killed renamable $x1, killed renamable $x10, renamable $r20, debug-location !5
    $cml5 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml5, $x3, $y4, $r10, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml3 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml3, $x4, killed $y4, $r10, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x3, $y3, $r10, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x4, killed $y3, $r10, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $p0, $dc1, $dc5 = PADDB_3D $p0, $d1_3d, debug-location !5
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, implicit $ls, implicit $le, debug-location !5

  bb.3.exit:
    RET implicit $lr
    DelayedSchedBarrier
...
