# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2ps -run-pass=postmisched %s -o - 2>&1 | FileCheck %s
#
# Loop for.body79.i (bb.7) from Conv2D_bf16_0.ll.
# 14 instructions: 1 POPX + 1 PADD_mod + 1 FIFO 1D pop + 4 weight loads
#                  + 2 shuffles + 4 VMACs + PADD_3D.
# MII = 4 (ResMII = RecMII = 4), but the post-pipeliner achieves II = 5.
# The test verifies that multi-slot pseudos are materialized correctly:
#   VLD_POP_512_fifo_1d_pop_pseudo -> VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop
#   VLD_x_pstm_nrm_imm_pseudo     -> 2x VLDA + 2x VLDB
#   PADD_mod_pseudo                -> PADDS_pstm_nrm
#   PADD_3D_pseudo                 -> PADDS_3D

--- |
  target triple = "aie2ps"

  define void @conv2d_bf16_fifo_1d_pop() !dbg !3 {
  entry:
    br label %for.body.i
  for.body.i:
    call void @llvm.set.loop.iterations.i32(i32 0)
    br label %for.body79.i, !dbg !5
  for.body79.i:
    %dec = call i1 @llvm.loop.decrement.i32(i32 1), !dbg !5
    br i1 %dec, label %for.body79.i, label %for.cond.cleanup78.i, !dbg !5, !llvm.loop !6
  for.cond.cleanup78.i:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !llvm.dbg.cu = !{!0}
  !llvm.module.flags = !{!2}
  !0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: NoDebug)
  !1 = !DIFile(filename: "conv2d_bf16.h", directory: "")
  !2 = !{i32 2, !"Debug Info Version", i32 3}
  !3 = distinct !DISubprogram(name: "conv2d_bf16", scope: !1, file: !1, line: 2535, type: !4, scopeLine: 2535, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0)
  !4 = !DISubroutineType(types: !{})
  !5 = !DILocation(line: 2535, column: 13, scope: !3)
  !6 = distinct !{!6, !7}
  !7 = !{!"llvm.loop.itercount.range", i64 4}
...
---
name:            conv2d_bf16_fifo_1d_pop
alignment:       16
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
body:             |
  ; CHECK-LABEL: name: conv2d_bf16_fifo_1d_pop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml2, $cml5, $m6, $p1, $p5, $r8, $r18, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24, $lfe
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body.i:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml2, $cml5, $m6, $p1, $p5, $r8, $r18, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24, $lfe
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $x1, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, killed $p0, killed $lf0, killed $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $lfe, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:   renamable $p0 = PADDS_pstm_nrm killed renamable $p0, renamable $m6, debug-location !6
  ; CHECK-NEXT:   BUNDLE implicit-def $x10, implicit-def $wl10, implicit-def $wh10, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit-def $p5, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit $m6, implicit killed $p5, debug-location !6 {
  ; CHECK-NEXT:     $x10, $p0, $lf0, $r24 = VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop killed $p0, killed $lf0, killed $r24, $m6, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     renamable $x8, renamable $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   $p0, $dc1, $dc5 = PADDS_3D killed $p0, $d1_3d, debug-location !6
  ; CHECK-NEXT:   renamable $x9, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:   renamable $x6, renamable $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:   BUNDLE implicit-def $x7, implicit-def $wl7, implicit-def $wh7, implicit-def $p5, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $p5, implicit $r30, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit killed $lfe, debug-location !6 {
  ; CHECK-NEXT:     renamable $x7, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $x1, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, killed $p0, killed $lf0, killed $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $lfe, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $p0, implicit-def $lc, implicit killed $p0, implicit $m6, implicit killed $r18, debug-location !6 {
  ; CHECK-NEXT:     renamable $p0 = PADDS_pstm_nrm killed renamable $p0, renamable $m6, debug-location !6
  ; CHECK-NEXT:     $lc = ADD_NC_add_lc_ri killed $r18, -2, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x10, implicit-def $wl10, implicit-def $wh10, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit-def $p5, implicit-def $ls, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit $m6, implicit killed $p5, debug-location !6 {
  ; CHECK-NEXT:     $x10, $p0, $lf0, $r24 = VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop killed $p0, killed $lf0, killed $r24, $m6, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     renamable $x8, renamable $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     MOVXM_lng_cg_ls_abs %bb.2, implicit-def $ls, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $p0, implicit-def $dc1, implicit-def $dc5, implicit-def $le, implicit killed $p0, implicit $d1_3d, debug-location !6 {
  ; CHECK-NEXT:     $p0, $dc1, $dc5 = PADDS_3D killed $p0, $d1_3d, debug-location !6
  ; CHECK-NEXT:     MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x9, implicit-def $wl9, implicit-def $wh9, implicit-def $p5, implicit-def $x3, implicit-def $wl3, implicit-def $wh3, implicit killed $p5, implicit $x1, implicit $x10, implicit $r22, debug-location !6 {
  ; CHECK-NEXT:     renamable $x9, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     renamable $x3 = VSHUFFLE_vec_shuffle_x renamable $x1, renamable $x10, renamable $r22, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p5, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p5, implicit killed $x1, implicit killed $x10, implicit $r20, debug-location !6 {
  ; CHECK-NEXT:     renamable $x6, renamable $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     renamable $x4 = VSHUFFLE_vec_shuffle_x killed renamable $x1, killed renamable $x10, renamable $r20, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.body79.i:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT:   liveins: $lfe, $cml0, $cml1, $cml2, $cml5, $dc1, $dc5, $m6, $p5, $r8, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x7, implicit-def $wl7, implicit-def $wh7, implicit-def $p5, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit-def $cml5, implicit-def $bmll5, implicit-def $bmlh5, implicit-def dead $srfpflags, implicit killed $p5, implicit $r30, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit killed $lfe, implicit killed $cml5, implicit $x3, implicit $y4, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x7, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $x1, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, killed $p0, killed $lf0, killed $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $lfe, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     $cml5 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml5, $x3, $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $p0, implicit-def $cml2, implicit-def $bmll2, implicit-def $bmlh2, implicit-def dead $srfpflags, implicit killed $p0, implicit $m6, implicit killed $cml2, implicit $x4, implicit killed $y4, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $p0 = PADDS_pstm_nrm killed renamable $p0, renamable $m6, debug-location !6
  ; CHECK-NEXT:     $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, $x4, killed $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x10, implicit-def $wl10, implicit-def $wh10, implicit-def $p0, implicit-def $lf0, implicit-def $lfl0, implicit-def $lfh0, implicit-def $r24, implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit-def $p5, implicit-def $cml1, implicit-def $bmll1, implicit-def $bmlh1, implicit-def dead $srfpflags, implicit killed $p0, implicit killed $lf0, implicit killed $r24, implicit $m6, implicit killed $p5, implicit killed $cml1, implicit killed $x3, implicit $y3, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     $x10, $p0, $lf0, $r24 = VLDA_POP_dmx_lda_fifo_x_fifo_1d_pop killed $p0, killed $lf0, killed $r24, $m6, debug-location !6 :: (load unknown-size, align 1)
  ; CHECK-NEXT:     renamable $x8, renamable $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x3, $y3, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $p0, implicit-def $dc1, implicit-def $dc5, implicit-def $cml0, implicit-def $bmll0, implicit-def $bmlh0, implicit-def dead $srfpflags, implicit killed $p0, implicit $d1_3d, implicit killed $cml0, implicit killed $x4, implicit killed $y3, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     $p0, $dc1, $dc5 = PADDS_3D killed $p0, $d1_3d, debug-location !6
  ; CHECK-NEXT:     $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x4, killed $y3, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x9, implicit-def $wl9, implicit-def $wh9, implicit-def $p5, implicit-def $x3, implicit-def $wl3, implicit-def $wh3, implicit killed $p5, implicit $x1, implicit $x10, implicit $r22, debug-location !6 {
  ; CHECK-NEXT:     renamable $x9, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     renamable $x3 = VSHUFFLE_vec_shuffle_x renamable $x1, renamable $x10, renamable $r22, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p5, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p5, implicit killed $x1, implicit killed $x10, implicit $r20, debug-location !6 {
  ; CHECK-NEXT:     renamable $x6, renamable $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     renamable $x4 = VSHUFFLE_vec_shuffle_x killed renamable $x1, killed renamable $x10, renamable $r20, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, debug-location !6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.cond.cleanup78.i:
  ; CHECK-NEXT:   liveins: $cml0, $cml1, $cml2, $cml5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x7, implicit-def $wl7, implicit-def $wh7, implicit-def $p5, implicit-def $cml5, implicit-def $bmll5, implicit-def $bmlh5, implicit-def dead $srfpflags, implicit killed $p5, implicit killed $cml5, implicit $x3, implicit $y4, implicit $r8, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6 {
  ; CHECK-NEXT:     renamable $x7, renamable $p5 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p5, 64, debug-location !6 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:     $cml5 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml5, $x3, $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, $x4, $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x3, $y3, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x4, $y3, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   renamable $x3 = VSHUFFLE_vec_shuffle_x renamable $x1, renamable $x10, killed renamable $r22, debug-location !6
  ; CHECK-NEXT:   renamable $x4 = VSHUFFLE_vec_shuffle_x killed renamable $x1, killed renamable $x10, killed renamable $r20, debug-location !6
  ; CHECK-NEXT:   $cml5 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml5, $x3, $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, $x4, killed $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x3, $y3, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x4, killed $y3, killed $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !6
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $cml0, $cml1, $cml2, $cml5, $m6, $p1, $p5, $r8, $r18, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24, $lfe

  bb.1.for.body.i:
    successors: %bb.2(0x80000000)
    liveins: $cml0, $cml1, $cml2, $cml5, $m6, $p1, $p5, $r8, $r18, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24, $lfe

    $lc = ADD_NC_add_lc_ri $r18, 0, debug-location !5
    MOVXM_lng_cg_ls_abs %bb.2, implicit-def $ls, debug-location !5
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le, debug-location !5

  bb.2.for.body79.i:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $lfe, $cml0, $cml1, $cml2, $cml5, $dc1, $dc5, $m6, $p5, $r8, $r20, $r22, $r30, $d1_3d, $p0, $lf0, $r24

    $x1, $p0, $lf0, $r24 = VLDB_POPX $r30, $r30, $p0, $lf0, $r24, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe, debug-location !5 :: (load unknown-size, align 1)
    renamable $p0 = PADD_mod_pseudo renamable $p0, renamable $m6, debug-location !5
    $x10, $p0, $lf0, $r24 = VLD_POP_512_fifo_1d_pop_pseudo $p0, $lf0, $r24, $m6, debug-location !5 :: (load unknown-size, align 1)
    renamable $x8, renamable $p5 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x9, renamable $p5 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x6, renamable $p5 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x7, renamable $p5 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p5, 64, debug-location !5 :: (load (<16 x s32>), addrspace 6)
    renamable $x3 = VSHUFFLE_vec_shuffle_x renamable $x1, renamable $x10, renamable $r22, debug-location !5
    renamable $x4 = VSHUFFLE_vec_shuffle_x killed renamable $x1, killed renamable $x10, renamable $r20, debug-location !5
    $cml5 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml5, $x3, $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml2 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml2, $x4, killed $y4, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml1 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml1, killed $x3, $y3, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $cml0 = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y killed $cml0, killed $x4, killed $y3, $r8, implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask, debug-location !5
    $p0, $dc1, $dc5 = PADD_3D_pseudo $p0, $d1_3d, debug-location !5
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, debug-location !5

  bb.3.for.cond.cleanup78.i:
    liveins: $cml0, $cml1, $cml2, $cml5

    RET implicit $lr
    DelayedSchedBarrier
...
