# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2ps -O2 --start-before=postmisched %s -o - | FileCheck %s
#
# Two MaxPool2D bf16 inner loops with FIFO fill/pop pairs.
# Extracted from MaxPool2dVariant_bf16_2.
#
# Loop 1 (5 instructions, itercount=6):
#   VLD_FILL, VLD_POP_3D, VLD, VMAX_LT, VST
#
# Loop 2 (6 instructions, itercount=6):
#   VLD_FILL, VLD_POP_3D, VLD, VSEL, VMAX_LT, VST
#
# Both loops have ResMII=RecMII=2.
#
# VLD_FILL_512_pseudo modifies persistent hardware FIFO state; peeling it as a
# speculative first stage without its matching POP creates an unbalanced
# prologue that corrupts data across outer loop iterations.
#
# The postpipeliner achieves II=2 for both loops by peeling the FILL
# as side-effect-free (NSEF=1), reducing NStages enough to fit the
# minimum trip count.

--- |
  target triple = "aie2ps"

  define void @maxpool_fifo_5instr(ptr addrspace(5) noalias %ifm, ptr addrspace(6) noalias %ofm_load, ptr addrspace(6) noalias %ofm_write, i32 %n) {
  ; CHECK-LABEL: maxpool_fifo_5instr:
  ; CHECK:       // %bb.0: // %preheader
  ; CHECK-NEXT:    vldb.fill [p0, lf0, r24]; mov p6, p1
  ; CHECK-NEXT:    vlda x4, [p6], #64; vldb.pop.3d x6, [p0, lf0, r24, d0]; nopx
  ; CHECK-NEXT:    vldb.fill [p0, lf0, r24]; add.nc lc, r2, #-5
  ; CHECK-NEXT:    vlda x4, [p6], #64; vldb.pop.3d x6, [p0, lf0, r24, d0]; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    nopa ; vldb.fill [p0, lf0, r24]; nops ; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    vlda x4, [p6], #64; vldb.pop.3d x6, [p0, lf0, r24, d0]; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; vldb.fill [p0, lf0, r24]; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x4, [p6], #64; vldb.pop.3d x6, [p0, lf0, r24, d0]; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; vldb.fill [p0, lf0, r24]; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x4, [p6], #64; vldb.pop.3d x6, [p0, lf0, r24, d0]; movs p7, p2; nopx ; vmax_lt.bf16 x2, r16, x4, x6; nopv
  ; CHECK-NEXT:  .LBB0_1: // %loop_body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; vldb.fill [p0, lf0, r24]; nops ; nopxm ; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    vlda x4, [p6], #64; vldb.pop.3d x6, [p0, lf0, r24, d0]; vst x2, [p7], #64; nopx ; vmax_lt.bf16 x2, r16, x4, x6; nopv
  ; CHECK-NEXT:  // %bb.2: // %exit
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vst x2, [p7], #64; vmax_lt.bf16 x2, r16, x4, x6
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vst x2, [p7], #64; vmax_lt.bf16 x2, r16, x4, x6
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vst x2, [p7], #64; ret lr; vmax_lt.bf16 x2, r16, x4, x6
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    vst x2, [p7], #64; vmax_lt.bf16 x2, r16, x4, x6 // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    vst x2, [p7], #64 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  preheader:
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %loop_body
  loop_body:
    %dec = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %dec, label %loop_body, label %exit, !llvm.loop !0
  exit:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1}
  !1 = !{!"llvm.loop.itercount.range", i64 6}
...
---
name:            maxpool_fifo_5instr
tracksRegLiveness: true
body:             |
  bb.0.preheader:
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $p2, $r2, $plfr0:0x0000000022000040, $d0_3d:0x3800000040001C00, $crbf8conf, $crfp8conf

    $lc = ADD_NC_add_lc_ri $r2, 0
    MOVXM_lng_cg_ls_abs %bb.1, implicit-def $ls
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le
    $p6 = MOV_scalar_pseudo $p1
    $p7 = MOV_scalar_pseudo $p2

  bb.1.loop_body:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $dc0, $dc4, $p1, $p2, $p6, $p7, $r2, $plfr0:0x00000000A2000040, $d0_3d:0x3800000040001C00

    $p0, $lf0, $r24 = VLD_FILL_512_pseudo $p0, $lf0, $r24 :: (load unknown-size from %ir.ifm, align 1)
    $x6, $p0, $lf0, $r24, $dc0, $dc4 = VLD_POP_512_3D_pseudo $p0, $lf0, $r24, $d0_3d, implicit-def $srfifo_uf :: (load unknown-size from %ir.ifm, align 1)
    renamable $x4, renamable $p6 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p6, 64 :: (load (<32 x s16>) from %ir.ofm_load, addrspace 6)
    renamable $x2, dead renamable $r16 = VMAX_LT_bf16 killed renamable $x4, killed renamable $x6, implicit $crbf8conf, implicit $crfp8conf
    renamable $p7 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x2, killed renamable $p7, 64 :: (store (<32 x s16>) into %ir.ofm_write, addrspace 6)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2.exit:
    liveins: $p6, $p7
    RET implicit $lr
    DelayedSchedBarrier
...

