# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# REQUIRES: enable_z3_solver

# RUN: llc -mtriple=aie2ps -O2 --start-before=postmisched %s \
# RUN:   --aie-postpipeliner-heuristic-runs=1 \
# RUN:   --aie-postpipeliner-solver \
# RUN:   -o - | FileCheck %s

# MaxPool2D inner loop (10 instructions) with VSEL.
# Similar to the 9-instr variant but with an extra VSEL_8 between
# VSHIFT and VMAX_LT_8 in the compute chain.
# The Z3 solver finds a solution at II=4 NS=4 but it fails
# CheckFixedSchedule due to pipeline resource hazards.
# Without the retry mechanism the heuristic falls back to II=7.

--- |
  target triple = "aie2ps"

  define void @maxpool_inner_10instr(ptr addrspace(5) noalias %data, ptr addrspace(6) noalias %weights, ptr addrspace(7) noalias %out, i32 %n) {
  ; CHECK-LABEL: maxpool_inner_10instr:
  ; CHECK:       // %bb.0: // %preheader
  ; CHECK-NEXT:    nopa ; nopb ; nopx ; mov p0, p6; nops
  ; CHECK-NEXT:    movs p3, p1; vldb wh9, [p0, #32]; mov p5, p6
  ; CHECK-NEXT:    vlda wl7, [p3], #32; vldb.3d wl9, [p5], d0; mov r24, p0
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    movs p0, p5
  ; CHECK-NEXT:    vldb wh9, [p0, #32]; and r26, r24, r18
  ; CHECK-NEXT:    vlda wl7, [p3], #32; vldb.3d wl9, [p5], d0; add.nc lc, r2, #-3; mov r24, p0
  ; CHECK-NEXT:    movxm ls, #.LBB0_1
  ; CHECK-NEXT:    nopa ; nopb ; movs p0, p5; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    nopa ; vldb wh9, [p0, #32]; nops ; and r26, r24, r18; vshift x5, x9, x0, r26; nopv
  ; CHECK-NEXT:    vlda wl7, [p3], #32; vldb.3d wl9, [p5], d0; nops ; nopx ; mov r24, p0; nopv
  ; CHECK-NEXT:    nopa ; nopb ; movs p4, p2; nopx ; vsel.8 x3, x0, x5, r5:r4; nopv
  ; CHECK-NEXT:    nopa ; nopb ; movs p0, p5; nopx ; vmax_lt.8 x1, r17:r16, x7, x3, vaddsign1; nopv
  ; CHECK-NEXT:  .LBB0_1: // %loop_body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; vldb wh9, [p0, #32]; and r26, r24, r18; vshift x5, x9, x0, r26; nops
  ; CHECK-NEXT:    vlda wl7, [p3], #32; vldb.3d wl9, [p5], d0; mov r24, p0
  ; CHECK-NEXT:    vst wl1, [p4], #32; vsel.8 x3, x0, x5, r5:r4
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; movs p0, p5; nopx ; vmax_lt.8 x1, r17:r16, x7, x3, vaddsign1; nopv
  ; CHECK-NEXT:  // %bb.2: // %exit
  ; CHECK-NEXT:    nopa ; and r26, r24, r18; vshift x5, x9, x0, r26
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vst wl1, [p4], #32; vsel.8 x3, x0, x5, r5:r4
  ; CHECK-NEXT:    vmax_lt.8 x1, r17:r16, x7, x3, vaddsign1
  ; CHECK-NEXT:    vshift x5, x9, x0, r26
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vst wl1, [p4], #32; vsel.8 x3, x0, x5, r5:r4
  ; CHECK-NEXT:    vmax_lt.8 x1, r17:r16, x7, x3, vaddsign1
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vst wl1, [p4], #32
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  preheader:
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %loop_body
  loop_body:
    %data.phi = phi ptr addrspace(5) [ %data, %preheader ], [ %data.phi, %loop_body ]
    %weights.phi = phi ptr addrspace(6) [ %weights, %preheader ], [ %weights.phi, %loop_body ]
    %out.phi = phi ptr addrspace(7) [ %out, %preheader ], [ %out.phi, %loop_body ]
    %dec = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %dec, label %loop_body, label %exit, !llvm.loop !0
  exit:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1}
  !1 = !{!"llvm.loop.itercount.range", i64 4}
...
---
name:            maxpool_inner_10instr
tracksRegLiveness: true
body:             |
  bb.0.preheader:
    successors: %bb.1(0x80000000)
    liveins: $p1, $p2, $p6, $r2, $r6, $r18, $r22, $x0:0x0000000000000003, $l2:0x000000000C000000, $d0_3d:0x3800000040001C00, $crbf8conf, $crfp8conf, $vaddsign1

    $lc = ADD_NC_add_lc_ri $r2, 0
    MOVXM_lng_cg_ls_abs %bb.1, implicit-def $ls
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le
    $p3 = MOV_scalar_pseudo $p1
    $p4 = MOV_scalar_pseudo $p2
    $p0 = MOV_scalar_pseudo $p6
    $p5 = MOV_scalar_pseudo $p6

  bb.1.loop_body:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $dc0, $dc4, $dj0, $dj4, $dn0, $dn4, $l2:0x000000000C000000, $m0, $m1, $p0, $p1, $p2, $p3, $p4, $p5, $p6, $r0, $r2, $r6, $r18, $r22, $x0:0x0000000000000003, $d0_3d:0x3800000040001C00

    renamable $wh9 = VLD_w_idx_imm_pseudo renamable $p0, 32 :: (load (<8 x s32>) from %ir.data.phi, addrspace 5)
    $wl9, $p5, $dc0, $dc4 = VLD_3D_w_pseudo killed $p5, $d0_3d :: (load (<8 x s32>) from %ir.data.phi, addrspace 5)
    renamable $wl7, renamable $p3 = VLD_w_pstm_nrm_imm_pseudo killed renamable $p3, 32 :: (load (<8 x s32>) from %ir.weights.phi, addrspace 6)
    $r24 = MOV_alu_mv_mv_mv_scl killed $p0
    renamable $r26 = AND killed renamable $r24, renamable $r18
    renamable $x5 = VSHIFT killed renamable $x9, undef renamable $x0, killed renamable $r26
    renamable $x3 = VSEL_8 renamable $x0, killed renamable $x5, renamable $l2, implicit $crbf8conf, implicit $crfp8conf
    renamable $x1, dead renamable $l8 = VMAX_LT_8_vaddSign1 renamable $x7, killed renamable $x3, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
    renamable $p4 = VST_dmw_sts_w_st_pstm_nrm_imm killed renamable $wl1, killed renamable $p4, 32 :: (store (<8 x s32>) into %ir.out.phi, addrspace 6)
    $p0 = MOV_scalar_pseudo $p5
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2.exit:
    liveins: $p3, $p4
    RET implicit $lr
    DelayedSchedBarrier
...
