# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# REQUIRES: enable_z3_solver

# RUN: llc -mtriple=aie2ps -O2 --start-before=postmisched %s \
# RUN:   --aie-postpipeliner-target-ii=4 \
# RUN:   -o - | FileCheck %s

# MaxPool2D inner loop (9 instructions) without VSEL.
# Locks in the --aie-postpipeliner-target-ii=4 path: the post-pipeliner
# starts directly at II=4, skips heuristics, and runs only the Z3 solver
# at that II (no fallback to other IIs).

--- |
  target triple = "aie2ps"

  define void @maxpool_inner_9instr(ptr addrspace(5) noalias %data, ptr addrspace(6) noalias %weights, ptr addrspace(7) noalias %out, i32 %n) {
  ; CHECK-LABEL: maxpool_inner_9instr:
  ; CHECK:       // %bb.0: // %preheader
  ; CHECK-NEXT:    nopa ; nopb ; movs p5, p1; nopx ; mov p7, p0; nopv
  ; CHECK-NEXT:    vlda wl3, [p5], #32; vldb.3d wl5, [p7], d0; nops ; nopx ; mov p3, p0; nopv
  ; CHECK-NEXT:    vldb wh5, [p3, #32]
  ; CHECK-NEXT:    movxm ls, #.LBB0_1
  ; CHECK-NEXT:    add.nc lc, r2, #-2; mov r22, p3
  ; CHECK-NEXT:    vlda wl3, [p5], #32; vldb.3d wl5, [p7], d0; movs p3, p7; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    nopa ; vldb wh5, [p3, #32]; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; and r24, r22, r20; nopm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; movs p6, p2; nopx ; mov r22, p3; nopv
  ; CHECK-NEXT:  .LBB0_1: // %loop_body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda wl3, [p5], #32; vldb.3d wl5, [p7], d0; movs p3, p7; nopx ; vshift x1, x5, x0, r24; nopv
  ; CHECK-NEXT:    nopa ; vldb wh5, [p3, #32]; nops ; nopx ; vmax_lt.8 x10, r17:r16, x3, x1, vaddsign1; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; and r24, r22, r20; nopm ; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; vst wl10, [p6], #32; nopx ; mov r22, p3; nopv
  ; CHECK-NEXT:  // %bb.2: // %exit
  ; CHECK-NEXT:    movs p3, p7; vshift x1, x5, x0, r24
  ; CHECK-NEXT:    vmax_lt.8 x10, r17:r16, x3, x1, vaddsign1
  ; CHECK-NEXT:    and r24, r22, r20
  ; CHECK-NEXT:    vst wl10, [p6], #32
  ; CHECK-NEXT:    vshift x1, x5, x0, r24
  ; CHECK-NEXT:    vmax_lt.8 x10, r17:r16, x3, x1, vaddsign1
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vst wl10, [p6], #32
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  preheader:
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %loop_body
  loop_body:
    %data.phi = phi ptr addrspace(5) [ %data, %preheader ], [ %data.phi, %loop_body ]
    %weights.phi = phi ptr addrspace(6) [ %weights, %preheader ], [ %weights.phi, %loop_body ]
    %out.phi = phi ptr addrspace(7) [ %out, %preheader ], [ %out.phi, %loop_body ]
    %dec = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %dec, label %loop_body, label %exit, !llvm.loop !0
  exit:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1}
  !1 = !{!"llvm.loop.itercount.range", i64 4}
...
---
name:            maxpool_inner_9instr
tracksRegLiveness: true
body:             |
  bb.0.preheader:
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $p2, $p5, $p6, $p7, $r2, $r20, $x0:0x0000000000000003, $d0_3d:0x3800000040001C00, $crbf8conf, $crfp8conf, $vaddsign1

    $lc = ADD_NC_add_lc_ri $r2, 0
    MOVXM_lng_cg_ls_abs %bb.1, implicit-def $ls
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le
    $p5 = MOV_scalar_pseudo $p1
    $p6 = MOV_scalar_pseudo $p2
    $p3 = MOV_scalar_pseudo $p0
    $p7 = MOV_scalar_pseudo $p0

  bb.1.loop_body:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $dc0, $dc1, $dc4, $dj0, $dj1, $dj4, $dn0, $dn1, $dn4, $l2:0x0000000008000000, $m0, $m1, $p0, $p1, $p2, $p3, $p4, $p5, $p6, $p7, $r0, $r1, $r2, $r4, $r6, $r20, $x0:0x0000000000000003, $d0_3d:0x3800000040001C00

    renamable $wh5 = VLD_w_idx_imm_pseudo renamable $p3, 32 :: (load (<8 x s32>) from %ir.data.phi, addrspace 5)
    $wl5, $p7, $dc0, $dc4 = VLD_3D_w_pseudo killed $p7, $d0_3d :: (load (<8 x s32>) from %ir.data.phi, addrspace 5)
    renamable $wl3, renamable $p5 = VLD_w_pstm_nrm_imm_pseudo killed renamable $p5, 32 :: (load (<8 x s32>) from %ir.weights.phi, addrspace 6)
    $r22 = MOV_alu_mv_mv_mv_scl killed $p3
    renamable $r24 = AND killed renamable $r22, renamable $r20
    renamable $x1 = VSHIFT killed renamable $x5, undef renamable $x0, killed renamable $r24
    renamable $x10, dead renamable $l8 = VMAX_LT_8_vaddSign1 renamable $x3, killed renamable $x1, implicit $crbf8conf, implicit $crfp8conf, implicit $vaddsign1
    renamable $p6 = VST_dmw_sts_w_st_pstm_nrm_imm killed renamable $wl10, killed renamable $p6, 32 :: (store (<8 x s32>) into %ir.out.phi, addrspace 6)
    $p3 = MOV_scalar_pseudo $p7
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2.exit:
    liveins: $p5, $p6
    RET implicit $lr
    DelayedSchedBarrier
...
