# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2ps -O2 --start-before=postmisched %s -o - | FileCheck %s

# This test checks that MaxlatencyFinder also sees the latencies induced by
# the prologue instructions that were injected in the current block's successor
# We are looking at a predecessor of the preheader block. It loads a pointer that
# is used by the first instruction of the loop, which also appears first in the
# prologue. If the Free instructions in the preheader don't fill out the
# required latency, maxlatency should account for it.


--- |
  target triple = "aie2ps"

  define void @test(ptr addrspace(5) noalias %data, ptr addrspace(6) noalias %weights, ptr addrspace(7) noalias %out, i32 %n) {
  ; CHECK-LABEL: test:
  ; CHECK:       // %bb.0: // %entry
  ; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopxm ; nops
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:  // %bb.1: // %preheader
  ; CHECK-NEXT:    add.nc lc, r2, #-3
  ; CHECK-NEXT:    movxm ls, #.LBB0_2
  ; CHECK-NEXT:    vlda x0, [p0], #64; nopb ; nops ; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x0, [p0], #64; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vlda x0, [p0], #64; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:  .LBB0_2: // %loop_body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda x0, [p0], #64; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; vst x0, [p1], #64; nopxm ; nopv
  ; CHECK-NEXT:  // %bb.3: // %exit
  ; CHECK-NEXT:    nopa ; nopb ; nopxm
  ; CHECK-NEXT:    vst x0, [p1], #64; ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    vst x0, [p1], #64 // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    vst x0, [p1], #64 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    br label %preheader

  preheader:
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %loop_body
  loop_body:
    %data.phi = phi ptr addrspace(5) [ %data, %preheader ], [ %data.phi, %loop_body ]
    %weights.phi = phi ptr addrspace(6) [ %weights, %preheader ], [ %weights.phi, %loop_body ]
    %out.phi = phi ptr addrspace(7) [ %out, %preheader ], [ %out.phi, %loop_body ]
    %dec = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %dec, label %loop_body, label %exit, !llvm.loop !0
  exit:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1}
  !1 = !{!"llvm.loop.itercount.range", i64 4}
...
---
name:            test
tracksRegLiveness: true
body:             |
  bb.0.entry:
    successors: %bb.1
    liveins: $p0
    $p0 = LDA_dms_lda_scalar_ld_idx_imm $p0, 0

  bb.1.preheader:
    successors: %bb.2
    liveins: $p0, $p1, $r2

    $lc = ADD_NC_add_lc_ri $r2, 0
    MOVXM_lng_cg_ls_abs %bb.2, implicit-def $ls
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le

  bb.2.loop_body:
    successors: %bb.2, %bb.3
    liveins: $p0, $p1
    $x0, $p0 = VLDA_dmx_lda_x_ld_pstm_nrm_imm $p0, 64 :: (load (<8 x s32>) from %ir.data.phi, addrspace 5)
    $p1 = VST_dmx_sts_x_st_pstm_nrm_imm $x0, $p1, 64 :: (store (<8 x s32>) into %ir.out.phi, addrspace 6)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, implicit $ls, implicit $le

  bb.3.exit:
    liveins: $p5, $p6
    RET implicit $lr
    DelayedSchedBarrier
...
