# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

# Unit tests for stack alignment with callee-saved registers and GPR spills.
# Tests that work identically on both AIE2 and AIE2P targets.
#
# Target-specific tests (using CSR names) are in:
# - aie2/ra/stack-alignment-callee-save.mir
# - aie2p/ra/stack-alignment-callee-save.mir
#
# Stack alignment: AIE2P uses 64 bytes, AIE2 uses 32 bytes
# Callee-saved regs: AIE2P uses r8-r15, AIE2 uses r16-r23

# RUN: llc --march=aie2p --verify-machineinstrs -run-pass=prologepilog -o - %s \
# RUN:   | FileCheck %s --check-prefixes=AIE2P

# RUN: llc --march=aie2 --verify-machineinstrs -run-pass=prologepilog -o - %s \
# RUN:   | FileCheck %s --check-prefixes=AIE2

#------------------------------------------------------------------------------
# Test 1: Only single GPR (4-byte) spill slots (no calls, no callee-saved)
# All have 4-byte alignment. Stack should be properly aligned per target.
#------------------------------------------------------------------------------

---
name:            single_gpr_spills_only
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
  - { id: 1, type: spill-slot, size: 4, alignment: 4 }
  - { id: 2, type: spill-slot, size: 4, alignment: 4 }
body:             |
  bb.0:

    ; AIE2P-LABEL: name: single_gpr_spills_only
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2-LABEL: name: single_gpr_spills_only
    ; AIE2: frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: PseudoRET implicit $lr
    PseudoRET implicit $lr
...

#------------------------------------------------------------------------------
# Test 2: Mixed alignment spill slots
# Tests orderFrameObjects optimization with different alignments.
#------------------------------------------------------------------------------

---
name:            mixed_alignment_spills
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
  - { id: 1, type: spill-slot, size: 32, alignment: 32 }
  - { id: 2, type: spill-slot, size: 4, alignment: 4 }
body:             |
  bb.0:

    ; AIE2P-LABEL: name: mixed_alignment_spills
    ; AIE2P: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; AIE2P-NEXT: PseudoRET implicit $lr
    ;
    ; AIE2-LABEL: name: mixed_alignment_spills
    ; AIE2: frame-setup PADD_sp_imm_pseudo 64, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: frame-destroy PADD_sp_imm_pseudo -64, implicit-def $sp, implicit $sp
    ; AIE2-NEXT: PseudoRET implicit $lr
    PseudoRET implicit $lr
...
