; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie --issue-limit=1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define float @fmuladd_s(float %a, float %b, float %c) nounwind {
; CHECK-LABEL:  fmuladd_s:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 cl0, #0
; CHECK-NEXT:    mov.u20 cl1, #274960
; CHECK-NEXT:    movt.s12 cl0, #9
; CHECK-NEXT:    movt.s12 cl1, #1893
; CHECK-NEXT:    mov.u20 r15, #0
; CHECK-NEXT:    vshl0.32 wr2, r8
; CHECK-NEXT:    vshl0.32 wr0, r6
; CHECK-NEXT:    vshl0.32 wc0, r7
; CHECK-NEXT:    vfpmac wr2, r0, wr2, ya, r15, cl1, wc0, #0, cl1, #0, cl0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vext.32 r0, vl2[#0]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = fmul float %a, %b
  %2 = fadd float %1, %c
  ret float %2
}
define float @fmuladd2_s(float %a, float %b, float %c) nounwind {
; CHECK-LABEL:  fmuladd2_s:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 cl0, #0
; CHECK-NEXT:    mov.u20 cl1, #274960
; CHECK-NEXT:    movt.s12 cl0, #9
; CHECK-NEXT:    movt.s12 cl1, #1893
; CHECK-NEXT:    mov.u20 r15, #0
; CHECK-NEXT:    vshl0.32 wr2, r8
; CHECK-NEXT:    vshl0.32 wr0, r6
; CHECK-NEXT:    vshl0.32 wc0, r7
; CHECK-NEXT:    vfpmac wr2, r0, wr2, ya, r15, cl1, wc0, #0, cl1, #0, cl0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vext.32 r0, vl2[#0]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = fmul float %a, %b
  %2 = fadd float %c, %1
  ret float %2
}
define float @fmulsub_s(float %a, float %b, float %c) nounwind {
; CHECK-LABEL:  fmulsub_s:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 cl1, #0
; CHECK-NEXT:    mov cl2, cl1
; CHECK-NEXT:    mov.u20 cl0, #274960
; CHECK-NEXT:    movt.s12 cl0, #1893
; CHECK-NEXT:    movt.s12 cl2, #9
; CHECK-NEXT:    mov.u20 r15, #0
; CHECK-NEXT:    vshl0.32 wr0, r6
; CHECK-NEXT:    vshl0.32 wc0, r7
; CHECK-NEXT:    vfpmul wr2, r0, ya, r15, cl0, wc0, #0, cl0, #0, cl2
; CHECK-NEXT:    movt.s12 cl1, #11
; CHECK-NEXT:    mov.u20 r15, #0
; CHECK-NEXT:    vshl0.32 wr0, r8
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vfpmac wr2, r0, wr2, ya, r15, cl0, wc0, #0, cl0, #1, cl1
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vext.32 r0, vl2[#0]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = fmul float %a, %b
  %2 = fsub float %1, %c
  ret float %2
}
define float @fmulsub2_s(float %a, float %b, float %c) nounwind {
; CHECK-LABEL:  fmulsub2_s:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 cl0, #0
; CHECK-NEXT:    mov.u20 cl1, #274960
; CHECK-NEXT:    movt.s12 cl0, #9
; CHECK-NEXT:    movt.s12 cl1, #1893
; CHECK-NEXT:    mov.u20 r15, #0
; CHECK-NEXT:    vshl0.32 wr2, r8
; CHECK-NEXT:    vshl0.32 wr0, r6
; CHECK-NEXT:    vshl0.32 wc0, r7
; CHECK-NEXT:    vfpmac wr2, r0, wr2, ya, r15, cl1, wc0, #0, cl1, #1, cl0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vext.32 r0, vl2[#0]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = fmul float %a, %b
  %2 = fsub float %c, %1
  ret float %2
}
