; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p < %s | FileCheck %s

define void @test_commit_block_schedule(i1 %0) {
; CHECK-LABEL: test_commit_block_schedule:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #0; nopb ; nopx
; CHECK-NEXT:    vbcst.32 x0, r1
; CHECK-NEXT:    vmov bmll0, x0
; CHECK-NEXT:    mova r3, #1; vbcst.16 x0, r1
; CHECK-NEXT:    mova r2, #10; and r0, r0, r3; vmov bmlh0, bmll0
; CHECK-NEXT:  .LBB0_1: // %for.body41
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_2 Depth 2
; CHECK-NEXT:    nopa ; nopx ; add.nc lc, r2, #0
; CHECK-NEXT:    movxm ls, #.LBB0_2
; CHECK-NEXT:    nopa ; nopb ; nops ; movxm le, #.L_LEnd0; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vmov cml2, cml0; nopv
; CHECK-NEXT:  .LBB0_2: // %for.body54
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; vmac.f dm2, dm2, x0, x0, r1
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  // %bb.3: // %for.cond.cleanup53
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    nopa ; nopb ; nopxm ; vmac.f dm1, dm2, x0, x0, r1
; CHECK-NEXT:    jnz r0, #.LBB0_1
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vconv.bf16.fp32 x2, cml2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    j #.LBB0_1
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  br label %for.body34

for.body34:                                       ; preds = %for.cond.cleanup53, %entry
  br label %for.body41

for.body41:                                       ; preds = %for.cond.cleanup53, %for.body34
  call void @llvm.set.loop.iterations.i32(i32 10)
  br label %for.body54

for.cond.cleanup53:                               ; preds = %for.body54
  %1 = tail call <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> zeroinitializer, <32 x bfloat> zeroinitializer, <32 x float> %3, i32 0)
  %2 = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %3)
  br i1 %0, label %for.body34, label %for.body41

for.body54:                                       ; preds = %for.body54, %for.body41
  %acc_sum.sroa.0.4.in82 = phi <32 x float> [ zeroinitializer, %for.body41 ], [ %3, %for.body54 ]
  %3 = tail call <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> zeroinitializer, <32 x bfloat> zeroinitializer, <32 x float> %acc_sum.sroa.0.4.in82, i32 0)
  %4 = call i1 @llvm.loop.decrement.i32(i32 0)
  br i1 %4, label %for.body54, label %for.cond.cleanup53, !llvm.loop !0

; uselistorder directives
  uselistorder <32 x float> %3, { 2, 1, 0 }
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat>, <32 x bfloat>, <32 x float>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float>) #0

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare void @llvm.set.loop.iterations.i32(i32) #1

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare i1 @llvm.loop.decrement.i32(i32) #1

; uselistorder directives
uselistorder ptr @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf, { 1, 0 }

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #1 = { nocallback noduplicate nofree nosync nounwind willreturn }

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.mustprogress"}
!2 = !{!"llvm.loop.itercount.range", i32 32}
