; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie --issue-limit=1 < %s | FileCheck %s
define dso_local i32 @_Z5test8Piii(i32* %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: _Z5test8Piii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda r12, [p0]
; CHECK-NEXT:    mul r13, r6, r8
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mul r14, r12, r7
; CHECK-NEXT:    mul r12, r12, r6
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    add r13, r14, r13
; CHECK-NEXT:    mul r14, r6, r7
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    add r12, r12, r14
; CHECK-NEXT:    add r0, r12, r13
; CHECK:         ret lr
entry:
  %0 = load i32, i32* %a, align 4
  %mul = mul nsw i32 %0, %b
  %mul2 = mul nsw i32 %b, %c
  %mul3 = mul nsw i32 %0, %c
  %mul4 = mul nsw i32 %b, %d
  %add = add nsw i32 %mul, %mul2
  %add2 = add nsw i32 %mul3, %mul4
  %add3 = add nsw i32 %add, %add2
  ret i32 %add3
}
