; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie < %s | FileCheck %s
; RUN: llc -mtriple=aie -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=aie < %s | FileCheck %s

define i32 @muli(i32 %a, i32 %b, i32 %c) nounwind {
; CHECK-LABEL: muli:
; CHECK:        mul     r12, r7, r7
; CHECK-NEXT:        mul     r13, r6, r6
; CHECK-NEXT:        nop
; CHECK-NEXT:        nop
; CHECK-NEXT:        add     r12, r13, r12
; CHECK-NEXT:        mul     r13, r8, r8
; CHECK-NEXT:        nop
; CHECK-NEXT:        nop
; CHECK-NEXT:        add     r0, r12, r13
; CHECK-NEXT:        ret lr

  %1 = add i32 %a, 7
  %2 = mul i32 %a, %a
  %3 = mul i32 %b, %b
  %4 = mul i32 %c, %c
  %5 = add i32 %2, %3
  %6 = add i32 %5, %4
  ret i32 %6
}
