# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2 --start-before=postmisched \
# RUN:     %s -o - | FileCheck %s

# Pointer hazard recognition test: vldb wh2, [p0, #32] should not be packed with vldb wl2, [p0], #64
# because this will lead to wait cycles.

--- |
  define void @_Z16scale_vectorizedPsS_ii(ptr noalias nocapture readonly %a, ptr noalias nocapture writeonly %c, i32 noundef %factor, i32 noundef %N) {
  ; CHECK-LABEL: _Z16scale_vectorizedPsS_ii:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    nopa ; event #0; nopm
  ; CHECK-NEXT:    vldb wh2, [p0, #32]
  ; CHECK-NEXT:    vlda wl2, [p0], #64
  ; CHECK-NEXT:    vldb wh2, [p0, #32]
  ; CHECK-NEXT:    vlda wl2, [p0], #64
  ; CHECK-NEXT:    mova r2, #-5; vldb wh2, [p0, #32]; vbcst.16 x0, r0
  ; CHECK-NEXT:    vlda wl2, [p0], #64; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    mova r0, #824; vldb wh2, [p0, #32]; movxm le, #.L_LEnd0
  ; CHECK-NEXT:    vlda wl2, [p0], #64; lshl r1, r1, r2
  ; CHECK-NEXT:    vldb wh2, [p0, #32]; nopa ; nops ; nopx ; add.nc lc, r1, #-7; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:    nopb ; vlda wl2, [p0], #64; nops ; nopxm ; nopv
  ; CHECK-NEXT:    vldb wh2, [p0, #32]; nopa ; nops ; nopxm ; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:    nopb ; vlda wl2, [p0], #64; nops ; movx r3, #0; nopm ; nopv
  ; CHECK-NEXT:    vldb wh2, [p0, #32]; nopa ; nops ; nopx ; mov s0, r3; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:    nopb ; vlda wl2, [p0], #64; vst.srs.s16.s32 bmh0, s0, [p1, #32]; nopxm ; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vldb wh2, [p0, #32]; nopa ; vst.srs.s16.s32 bml0, s0, [p1], #64; nopxm ; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopb ; vlda wl2, [p0], #64; vst.srs.s16.s32 bmh0, s0, [p1, #32]; nopxm ; nopv
  ; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
  ; CHECK-NEXT:    vst.srs.s16.s32 bml0, s0, [p1], #64; nopx ; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:    vst.srs.s16.s32 bmh0, s0, [p1, #32]
  ; CHECK-NEXT:    vst.srs.s16.s32 bml0, s0, [p1], #64; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:    vst.srs.s16.s32 bmh0, s0, [p1, #32]
  ; CHECK-NEXT:    vst.srs.s16.s32 bml0, s0, [p1], #64; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:    vst.srs.s16.s32 bmh0, s0, [p1, #32]
  ; CHECK-NEXT:    vst.srs.s16.s32 bml0, s0, [p1], #64; vmul cm0, x2, x0, r0
  ; CHECK-NEXT:    vst.srs.s16.s32 bmh0, s0, [p1, #32]
  ; CHECK-NEXT:    vst.srs.s16.s32 bml0, s0, [p1], #64
  ; CHECK-NEXT:    vst.srs.s16.s32 bmh0, s0, [p1, #32]
  ; CHECK-NEXT:    vst.srs.s16.s32 bml0, s0, [p1], #64; ret lr
  ; CHECK-NEXT:    vst.srs.s16.s32 bmh0, s0, [p1, #32] // Delay Slot 5
  ; CHECK-NEXT:    vst.srs.s16.s32 bml0, s0, [p1], #64 // Delay Slot 4
  ; CHECK-NEXT:    event #1 // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    tail call void @llvm.aie2.event(i32 0)
    %div8 = lshr i32 %N, 5
    %0 = tail call noundef <32 x i16> @llvm.aie2.v32int16()
    %1 = tail call noundef <32 x i16> @llvm.aie2.vbroadcast16.I512(i32 %factor)
    %2 = bitcast <32 x i16> %1 to <16 x i32>
    %3 = tail call noundef <16 x i64> @llvm.aie2.v32acc32()
    call void @llvm.set.loop.iterations.i32(i32 %div8)
    br label %for.body

  for.cond.cleanup:                                 ; preds = %for.body
    tail call void @llvm.aie2.event(i32 1)
    ret void

  for.body:                                         ; preds = %for.body, %entry
    %pA1.06 = phi ptr [ %a, %entry ], [ %add.ptr, %for.body ]
    %pC1.05 = phi ptr [ %c, %entry ], [ %add.ptr1, %for.body ]
    %4 = load <64 x i8>, ptr %pA1.06, align 32, !tbaa !2, !noalias !5
    %add.ptr = getelementptr inbounds i8, ptr %pA1.06, i20 64
    %5 = tail call noundef <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8> %4, <16 x i32> %2, i32 824)
    %6 = tail call noundef <32 x i16> @llvm.aie2.I512.v32.acc32.srs(<16 x i64> %5, i32 0, i32 1)
    store <32 x i16> %6, ptr %pC1.05, align 32, !tbaa !2
    %add.ptr1 = getelementptr inbounds i8, ptr %pC1.05, i20 64
    %7 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %7, label %for.body, label %for.cond.cleanup, !llvm.loop !12
  }

  declare void @llvm.aie2.event(i32) #1

  declare <16 x i64> @llvm.aie2.v32acc32() #2

  declare <16 x i64> @llvm.aie2.I512.I512.acc32.mul.conf(<64 x i8>, <16 x i32>, i32) #2

  declare void @llvm.assume(i1 noundef) #3

  declare <32 x i16> @llvm.aie2.vbroadcast16.I512(i32) #2

  declare <32 x i16> @llvm.aie2.v32int16() #2

  declare <32 x i16> @llvm.aie2.I512.v32.acc32.srs(<16 x i64>, i32, i32) #4

  declare void @llvm.set.loop.iterations.i32(i32) #5

  declare i1 @llvm.loop.decrement.i32(i32) #5

  !llvm.linker.options = !{}
  !llvm.module.flags = !{!0}
  !llvm.ident = !{!1}

  !0 = !{i32 1, !"wchar_size", i32 4}
  !1 = !{!"clang version 19.0.0git"}
  !2 = !{!3, !3, i64 0}
  !3 = !{!"omnipotent char", !4, i64 0}
  !4 = !{!"Simple C++ TBAA"}
  !5 = !{!6, !8, !10}
  !6 = distinct !{!6, !7, !"_ZN3aie6detail18load_vector_helperIsLj32EL15aie_dm_resource0EE3runEPKs: %agg.result"}
  !7 = distinct !{!7, !"_ZN3aie6detail18load_vector_helperIsLj32EL15aie_dm_resource0EE3runEPKs"}
  !8 = distinct !{!8, !9, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EsEEDaPKT1_: %agg.result"}
  !9 = distinct !{!9, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EsEEDaPKT1_"}
  !10 = distinct !{!10, !11, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEsEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS4_: %agg.result"}
  !11 = distinct !{!11, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEsEENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS4_"}
  !12 = distinct !{!12, !13, !14}
  !13 = !{!"llvm.loop.mustprogress"}
  !14 = !{!"llvm.loop.itercount.range", i64 16}

...
---
name:            _Z16scale_vectorizedPsS_ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: true
registers:       []
liveins:         []
calleeSavedRegisters: [ '$lr', '$r16', '$r17', '$r18', '$r19', '$r20',
                        '$r21', '$r22', '$r23', '$p6', '$p7' ]
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $r0, $r1

    renamable $r2 = MOV_RLC_imm10_pseudo -5
    renamable $r3 = MOV_RLC_imm10_pseudo 0
    renamable $r1 = LSHL killed renamable $r1, killed renamable $r2
    renamable $x0 = VBCST_16 killed renamable $r0
    renamable $r0 = MOV_RLC_imm11_pseudo 824
    EVENT 0
    $lc = ADD_NC $r1, 0
    $ls = MOVXM_lng_cg %bb.1
    $le = MOVXM_lng_cg <mcsymbol .L_LEnd0>
    $s0 = MOV_mv_scl killed $r3

  bb.1.for.body (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p0, $p1, $r0, $s0, $x0

    renamable $wh2 = VLD_idx_imm_3x32_pseudo renamable $p0, 32 :: (load (<32 x s8>) from %ir.pA1.06 + 32, !tbaa !2, !noalias !5)
    renamable $wl2, renamable $p0 = VLD_pstm_imm_4x32_pseudo killed renamable $p0, 64 :: (load (<32 x s8>) from %ir.pA1.06, !tbaa !2, !noalias !5)
    renamable $cm0 = VMUL_vmac_cm_core_dense killed renamable $x2, renamable $x0, renamable $r0
    VST_SRS_S16_S32_ag_idx_imm renamable $p1, 32, renamable $bmh0, renamable $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into %ir.pC1.05 + 32, !tbaa !2)
    renamable $p1 = VST_SRS_S16_S32_ag_pstm_nrm_imm killed renamable $p1, 64, killed renamable $bml0, renamable $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into %ir.pC1.05, !tbaa !2)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2.for.cond.cleanup:
    EVENT 1
    RET implicit $lr
    DelayedSchedBarrier

...
