# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2p -run-pass=postrapseudos %s -o - | FileCheck %s

# Note that the "offset" field in the stack slots does not matter anymore,
# as the FI operands have already been translated to raw offsets.

---
name:            test_vec64
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 8, alignment: 4 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_vec64
    ; CHECK: $r2 = LDA_dms_lda_spill -16, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $r3 = LDA_dms_lda_spill -12, implicit $sp :: (load (s32) from %stack.0 + 4)
    $l1 = VLDA_L_SPILL -16, implicit $sp :: (load (s64) from %stack.0, align 4)
...

---
name:            test_vec1024
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_vec1024
    ; CHECK: $x6 = VLDA_dmx_lda_x_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $x7 = VLDA_dmx_lda_x_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    $y3 = VLDA_Y_SPILL -128, implicit $sp :: (load (s1024) from %stack.0, align 64)
...

---
name:            test_acc1024
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_acc1024
    ; CHECK: $bmll3 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $bmlh3 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    $cml3 = VLDA_CM_SPILL -128, implicit $sp :: (load (s1024) from %stack.0, align 64)
...


---
name:            test_acc2048
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_acc2048
    ; CHECK: $bmll3 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $bmlh3 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    ; CHECK-NEXT: $bmhl3 = VLDA_dmx_lda_bm_spill 0, implicit $sp :: (load (s512) from %stack.0 + 128)
    ; CHECK-NEXT: $bmhh3 = VLDA_dmx_lda_bm_spill 64, implicit $sp :: (load (s512) from %stack.0 + 192)
    $dm3 = VLDA_DM_SPILL -128, implicit $sp :: (load (s2048) from %stack.0, align 64)
...

---
name:            test_fifo_ld
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_ld
    ; CHECK: $lfl0 = VLDA_dmx_lda_fifohl_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $lfh0 = VLDA_dmx_lda_fifohl_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    $lf0 = VLDA_FIFO_SPILL -128, implicit $sp :: (load (s1024) from %stack.0, align 64)
...

---
name:            test_fifo_sf
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_sf
    ; CHECK: $sfl = VLDA_dmx_lda_fifohl_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $sfh = VLDA_dmx_lda_fifohl_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    $sf = VLDA_FIFO_SPILL -128, implicit $sp :: (load (s1024) from %stack.0, align 64)
...

---
name:            test_fifo_plfr
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 136, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_plfr
    ; CHECK: $lfl0 = VLDA_dmx_lda_fifohl_spill -136, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $lfh0 = VLDA_dmx_lda_fifohl_spill -72, implicit $sp :: (load (s512) from %stack.0 + 64)
    ; CHECK-NEXT: $r24 = LDA_dms_lda_spill -8, implicit $sp :: (load (s32) from %stack.0 + 128, align 64)
    ; CHECK-NEXT: $p0 = LDA_dms_lda_spill -4, implicit $sp :: (load (s32) from %stack.0 + 132, basealign 64)
    $plfr0 = VLDA_PLFR_SPILL -136, implicit $sp :: (load (s1088) from %stack.0, align 64)
...

