# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2p -run-pass=postrapseudos %s -o - | FileCheck %s

# Note that the "offset" field in the stack slots does not matter anymore,
# as the FI operands have already been translated to raw offsets.

---
name:            test_vec64
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 8, alignment: 4 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_vec64
    ; CHECK: ST_dms_sts_spill $r2, -16, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: ST_dms_sts_spill $r3, -12, implicit $sp :: (store (s32) into %stack.0 + 4)
    VST_L_SPILL $l1, -16, implicit $sp :: (store (s64) into %stack.0, align 4)
...


---
name:            test_vec1024
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_vec1024
    ; CHECK: VST_dmx_sts_x_spill $x6, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x7, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    VST_Y_SPILL $y3, -128, implicit $sp :: (store (s1024) into %stack.0, align 64)
...

---
name:            test_acc1024
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_acc1024
    ; CHECK: VST_dmx_sts_bm_spill $bmll3, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmlh3, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    VST_CM_SPILL $cml3, -128, implicit $sp :: (store (s1024) into %stack.0, align 64)
...

---
name:            test_acc2048
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_acc2048
    ; CHECK: VST_dmx_sts_bm_spill $bmll3, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmlh3, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmhl3, 0, implicit $sp :: (store (s512) into %stack.0 + 128)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmhh3, 64, implicit $sp :: (store (s512) into %stack.0 + 192)
    VST_DM_SPILL $dm3, -128, implicit $sp :: (store (s1024) into %stack.0, align 64)
...

---
name:            test_fifo_lf
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_lf
    ; CHECK: VST_dmx_sts_fifohl_spill $lfl1, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $lfh1, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    VST_FIFO_SPILL $lf1, -128, implicit $sp :: (store (s1024) into %stack.0, align 64)
...

---
name:            test_fifo_sf
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_sf
    ; CHECK: VST_dmx_sts_fifohl_spill $sfl, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $sfh, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    VST_FIFO_SPILL $sf, -128, implicit $sp :: (store (s1024) into %stack.0, align 64)
...

---
name:            test_fifo_plfr
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 136, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_plfr
    ; CHECK: VST_dmx_sts_fifohl_spill $lfl0, -136, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $lfh0, -72, implicit $sp :: (store (s512) into %stack.0 + 64)
    ; CHECK-NEXT: ST_dms_sts_spill $p0, -8, implicit $sp :: (store (s32) into %stack.0 + 128, align 64)
    ; CHECK-NEXT: ST_dms_sts_spill $r24, -4, implicit $sp :: (store (s32) into %stack.0 + 132, basealign 64)
    VST_PLFR_SPILL $plfr0, -136, implicit $sp :: (store (s1076) into %stack.0, align 64)
...


