# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s


# II_VADDMACf accesses CM_WA write port in cycle 6, VMUL in cycle 5
# The scheduler needs to insert an additional NOP such that the
# two instructions don't access the same port in the same cycle

---
name:            E6_VADDMACf_E5_VMUL_CM_WA_PORT
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E6_VADDMACf_E5_VMUL_CM_WA_PORT
    ; CHECK: $bml2 = VADDMAC_F_vmac_bm_core_dense killed $bml2, killed $bml5, killed $x3, killed $x4, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm0 = VMUL_vmac_cm_core_dense killed $x0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml2 = VADDMAC_F_vmac_bm_core_dense $bml2, $bml5, $x3, $x4, $r5, implicit-def $srfpflags, implicit $crfpmask
  $cm0 = VMUL_vmac_cm_core_dense $x0, $x1, $r0
...

---
name:            E6_VADDMACf_E5_VMULf_CM_WA_PORT
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E6_VADDMACf_E5_VMULf_CM_WA_PORT
    ; CHECK: $bml2 = VADDMAC_F_vmac_bm_core_dense killed $bml2, killed $bml5, killed $x3, killed $x4, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm4 = VMUL_vmac_cm_core_dense killed $x0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml2 = VADDMAC_F_vmac_bm_core_dense $bml2, $bml5, $x3, $x4, $r5, implicit-def $srfpflags, implicit $crfpmask
  $cm4 = VMUL_vmac_cm_core_dense $x0, $x1, $r0
...

---
name:            E6_VCLRf_E5_VMULf_CM_WA_PORT
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E6_VCLRf_E5_VMULf_CM_WA_PORT
    ; CHECK: $bml2 = VCLR_vclr_BF implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm3 = VMUL_vmac_cm_core_dense killed $x0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml2 = VCLR_vclr_BF implicit-def $srfpflags, implicit $crfpmask
  $cm3 = VMUL_vmac_cm_core_dense $x0, $x1, $r0
...

---
name:            E6_VADDMACf_E5_VCLRf_CM_WA_PORT
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E6_VADDMACf_E5_VCLRf_CM_WA_PORT
    ; CHECK: $bml2 = VADDMAC_F_vmac_bm_core_dense killed $bml2, killed $bml5, killed $x3, killed $x4, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm3 = VCLR_vclr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml2 = VADDMAC_F_vmac_bm_core_dense $bml2, $bml5, $x3, $x4, $r5, implicit-def $srfpflags, implicit $crfpmask
  $cm3 = VCLR_vclr
...

---
name:            E6_VNEGf_E5_VMUL_CM_WA_PORT
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E6_VNEGf_E5_VMUL_CM_WA_PORT
    ; CHECK: $bml2 = VNEG_F killed $bml2, killed $r5, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm2 = VMUL_vmac_cm_core_dense killed $x0, killed $x1, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml2 = VNEG_F $bml2, $r5, implicit-def $srfpflags, implicit $crfpmask
  $cm2 = VMUL_vmac_cm_core_dense $x0, $x1, $r0
...

---
name:            E5_VNEG_E6_VMUL_F_CM_WA_PORT
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E5_VNEG_E6_VMUL_F_CM_WA_PORT
    ; CHECK: $bml2 = VMUL_F_vmac_bm_core_dense killed $x0, killed $x1, killed $r0, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm3 = VNEG killed $cm3, killed $r5
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml2 = VMUL_F_vmac_bm_core_dense $x0, $x1, $r0, implicit-def $srfpflags, implicit $crfpmask
  $cm3 = VNEG $cm3, $r5
...

---
name:            E5_VMOV_D_E6_VMUL_F_CM_WA_PORT
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E5_VMOV_D_E6_VMUL_F_CM_WA_PORT
    ; CHECK: $bml2 = VMUL_F_vmac_bm_core_dense killed $x0, killed $x1, killed $r0, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $cm4 = VMOV_D killed $cm3
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $bml2 = VMUL_F_vmac_bm_core_dense $x0, $x1, $r0, implicit-def $srfpflags, implicit $crfpmask
  $cm4 = VMOV_D $cm3
...
