# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - | FileCheck %s

# This test checks that we are scheduling mulislot loads from differnt banks in on VLIW bundle.

---
name:            VLDA_VLDB_same_bankA
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankA
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

---
name:            VLDA_VLDB_same_bankB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankB
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_same_bankC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankC
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_same_bankD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_same_bankAB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankAB
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLDA_VLDB_same_bankAC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankAC
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
...

---
name:            VLDA_VLDB_same_bankAD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankAD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
...

---
name:            VLDA_VLDB_same_bankBC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankBC
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
...

---
name:            VLDA_VLDB_same_bankBD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankBD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
...

---
name:            VLDA_VLDB_same_bankCD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_same_bankCD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
...

---
name:            VLDA_VLDB_different_bank_A_and_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_A_and_B
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_different_bank_A_and_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_A_and_C
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_different_bank_A_and_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_A_and_D
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_different_bank_B_and_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_B_and_C
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_different_bank_B_and_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_B_and_D
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_different_bank_C_and_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_C_and_D
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...


---
name:            VLDA_VLDB_different_bank_A_B_C_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_A_B_C_D
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def $wh1, implicit-def $wh2, implicit killed $p0 {
    ; CHECK-NEXT:   $wh1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT:   $wh2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
    $wh1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
    $wh2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...


---
name:            VLDA_VLDB_different_bank_AB_A
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_A
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

---
name:            VLDA_VLDB_different_bank_AB_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_B
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_different_bank_AB_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_C
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...


---
name:            VLDA_VLDB_different_bank_AB_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_D
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_different_bank_AC_A
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_A
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

---
name:            VLDA_VLDB_different_bank_AC_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_B
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_different_bank_AC_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_C
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_different_bank_AC_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_D
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_different_bank_AD_A
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AD_A
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

---
name:            VLDA_VLDB_different_bank_AD_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AD_B
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_different_bank_AD_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AD_C
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_different_bank_AD_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AD_D
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_different_bank_BC_A
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BC_A
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

---
name:            VLDA_VLDB_different_bank_BC_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BC_B
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_different_bank_BC_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BC_C
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_different_bank_BC_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BC_D
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_different_bank_BD_A
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BD_A
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

---
name:            VLDA_VLDB_different_bank_BD_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BD_B
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_different_bank_BD_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BD_C
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_different_bank_BD_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BD_D
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...

---
name:            VLDA_VLDB_different_bank_CD_A
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_CD_A
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
...

---
name:            VLDA_VLDB_different_bank_CD_B
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_CD_B
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
...

---
name:            VLDA_VLDB_different_bank_CD_C
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_CD_C
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
...

---
name:            VLDA_VLDB_different_bank_CD_D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_CD_D
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...


---
name:            VLDA_VLDB_different_bank_AB_AC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_AC
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
...

---
name:            VLDA_VLDB_different_bank_AB_AD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_AD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
...

---
name:            VLDA_VLDB_different_bank_AB_BC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_BC
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
...


---
name:            VLDA_VLDB_different_bank_AB_BD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_BD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
...

---
name:            VLDA_VLDB_different_bank_AB_CD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AB_CD
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 9)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
...

---
name:            VLDA_VLDB_different_bank_AC_AD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_AD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
...

---
name:            VLDA_VLDB_different_bank_AC_BC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_BC
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
...

---
name:            VLDA_VLDB_different_bank_AC_BD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_BD
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
...

---
name:            VLDA_VLDB_different_bank_AC_CD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AC_CD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 10)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 10)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
...

---
name:            VLDA_VLDB_different_bank_AD_BC
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AD_BC
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit killed $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
...

---
name:            VLDA_VLDB_different_bank_AD_BD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AD_BD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
...

---
name:            VLDA_VLDB_different_bank_AD_CD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_AD_CD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 11)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 11)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
...

---
name:            VLDA_VLDB_different_bank_BC_BD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BC_BD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 13)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 13)
...

---
name:            VLDA_VLDB_different_bank_BC_CD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_BC_CD
    ; CHECK: $wl1 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 12)
    ; CHECK-NEXT: $wl2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 12)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 14)
...



---
name:            VLDA_VLDB_different_bank_ABCD
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLDA_VLDB_different_bank_ABCD
    ; CHECK: BUNDLE implicit-def $wl1, implicit-def $wl2, implicit $p0 {
    ; CHECK-NEXT:   $wl1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 5)
    ; CHECK-NEXT:   $wl2 = VLDB_dmw_ldb_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 6)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def $wh1, implicit-def $wh2, implicit killed $p0 {
    ; CHECK-NEXT:   $wh1 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0 :: (load (<8 x s32>), addrspace 7)
    ; CHECK-NEXT:   $wh2 = VLDB_dmw_ldb_ag_idx_imm killed $p0, 0 :: (load (<8 x s32>), addrspace 8)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 5)
    $wl2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 6)
    $wh1 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 7)
    $wh2 = VLD_idx_imm_3x32_pseudo $p0, 0 :: (load (<8 x s32>), addrspace 8)
...
