# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -verify-machineinstrs -run-pass=postmisched %topdown-multi --verify-machineinstrs %s -o - | FileCheck %s

# Several slots conflict on reading pointers/modifiers in E1
# They can never be bundled together
# Note that indirect J, JL, JNZD are currently
# scheduling boundaries, so can not be bundled anyway
# We add an explicit test to check that bundling is active
---
name:            check_bundling
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: check_bundling
    ; CHECK: BUNDLE implicit-def $r3, implicit-def $srcarry, implicit-def $r1, implicit killed $r4, implicit killed $r5, implicit killed $m0 {
    ; CHECK-NEXT:   $r3 = ADD killed $r4, killed $r5, implicit-def $srcarry
    ; CHECK-NEXT:   $r1 = MOV_mv_scl killed $m0
    ; CHECK-NEXT: }
  $r1 = MOV_mv_scl $m0
  $r3 = ADD $r4, $r5, implicit-def $srcarry
...
---
name:            E1_MOV_SCL_E1_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_SCL_E1_ST
    ; CHECK: ST_dms_sts_idx_imm killed $m3, killed $p1, 0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $dj0
  $r1 = MOV_mv_scl $dj0
  ST_dms_sts_idx_imm $m3, $p1, 0
...

---
name:            E1_MOV_SCL_E1_ST_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_SCL_E1_ST_2D
    ; CHECK: $p1, $dc0 = ST_2D_dms_sts killed $m3, killed $p1, $d0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $dj0
  $r1 = MOV_mv_scl $dj0
  $p1, $dc0 = ST_2D_dms_sts $m3, $p1, $d0
...

---
name:            E1_MOV_SCL_E1_ST_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_SCL_E1_ST_3D
    ; CHECK: $p1, $dc0, $dc4 = ST_3D_dms_sts killed $m3, killed $p1, $d0_3d
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $dj0
  $r1 = MOV_mv_scl $dj0
  $p1, $dc0, $dc4 = ST_3D_dms_sts $m3, $p1, $d0_3d
...

---
name:            E1_MOV_SCL_E1_JL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_SCL_E1_JL
    ; CHECK: $r1 = MOV_mv_scl $m0
    ; CHECK-NEXT: JL_IND killed $p1, implicit-def $lr
    ; CHECK-NEXT: $r1 = MOV_mv_scl $m0
    ; CHECK-NEXT: $r1 = MOV_mv_scl $m0
    ; CHECK-NEXT: $r1 = MOV_mv_scl $m0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
  $r1 = MOV_mv_scl $m0
  $r1 = MOV_mv_scl $m0
  $r1 = MOV_mv_scl $m0
  $r1 = MOV_mv_scl $m0
  $r1 = MOV_mv_scl $m0
  JL_IND $p1, implicit-def $lr
  DelayedSchedBarrier
...

---
name:            E1_MOV_D1_E1_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D1_E1_ST
    ; CHECK: $r1 = MOV_D1 killed $dj0
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $m3, killed $p1, 0
    ; CHECK-NEXT: NOP
  $r1 = MOV_D1 $dj0
  ST_dms_sts_idx_imm $m3, $p1, 0
...

---
name:            E1_MOV_D2_E1_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D2_E1_ST
    ; CHECK: $r1 = MOV_D2 killed $dj0
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $m3, killed $p1, 0
    ; CHECK-NEXT: NOP
  $r1 = MOV_D2 $dj0
  ST_dms_sts_idx_imm $m3, $p1, 0
...

---
name:            E1_MOV_D3_E1_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D3_E1_ST
    ; CHECK: $r1 = MOV_D3 killed $dj0
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $m3, killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D3 $dj0
  ST_dms_sts_idx_imm $m3, $p1, 0
...

---
name:            E1_MOV_D4_E1_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D4_E1_ST
    ; CHECK: $r1 = MOV_D4 killed $dj0
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $m3, killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D4 $dj0
  ST_dms_sts_idx_imm $m3, $p1, 0
...

---
name:            E1_MOV_D5_E1_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D5_E1_ST
    ; CHECK: $r1 = MOV_D5 killed $dj0
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $m3, killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D5 $dj0
  ST_dms_sts_idx_imm $m3, $p1, 0
...

---
name:            E1_MOV_D6_E1_ST
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D6_E1_ST
    ; CHECK: $r1 = MOV_D6 killed $dj0
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $m3, killed $p1, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D6 $dj0
  ST_dms_sts_idx_imm $m3, $p1, 0
...

---
name:            E1_MOV_D1_E1_ST_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D1_E1_ST_2D
    ; CHECK: $r1 = MOV_D1 $dj0
    ; CHECK-NEXT: $p1, $dc0 = ST_2D_dms_sts killed $m3, killed $p1, killed $d0
    ; CHECK-NEXT: NOP
  $r1 = MOV_D1 $dj0
  $p1, $dc0 = ST_2D_dms_sts $m3, $p1, $d0
...
---
name:            E1_MOV_D2_E1_ST_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D2_E1_ST_2D
    ; CHECK: $r1 = MOV_D2 $dj0
    ; CHECK-NEXT: $p1, $dc0 = ST_2D_dms_sts killed $m3, killed $p1, killed $d0
    ; CHECK-NEXT: NOP
  $r1 = MOV_D2 $dj0
  $p1, $dc0 = ST_2D_dms_sts $m3, $p1, $d0
...
---
name:            E1_MOV_D3_E1_ST_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D3_E1_ST_2D
    ; CHECK: $r1 = MOV_D3 $dj0
    ; CHECK-NEXT: $p1, $dc0 = ST_2D_dms_sts killed $m3, killed $p1, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D3 $dj0
  $p1, $dc0 = ST_2D_dms_sts $m3, $p1, $d0
...
---
name:            E1_MOV_D4_E1_ST_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D4_E1_ST_2D
    ; CHECK: $r1 = MOV_D4 $dj0
    ; CHECK-NEXT: $p1, $dc0 = ST_2D_dms_sts killed $m3, killed $p1, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D4 $dj0
  $p1, $dc0 = ST_2D_dms_sts $m3, $p1, $d0
...
---
name:            E1_MOV_D5_E1_ST_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D5_E1_ST_2D
    ; CHECK: $r1 = MOV_D5 $dj0
    ; CHECK-NEXT: $p1, $dc0 = ST_2D_dms_sts killed $m3, killed $p1, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D5 $dj0
  $p1, $dc0 = ST_2D_dms_sts $m3, $p1, $d0
...
---
name:            E1_MOV_D6_E1_ST_2D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D6_E1_ST_2D
    ; CHECK: $r1 = MOV_D6 $dj0
    ; CHECK-NEXT: $p1, $dc0 = ST_2D_dms_sts killed $m3, killed $p1, killed $d0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D6 $dj0
  $p1, $dc0 = ST_2D_dms_sts $m3, $p1, $d0
...
---
name:            E1_MOV_D1_E1_ST_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D1_E1_ST_3D
    ; CHECK: $r1 = MOV_D1 $dj0
    ; CHECK-NEXT: $p1, $dc0, $dc4 = ST_3D_dms_sts killed $m3, killed $p1, killed $d0_3d
    ; CHECK-NEXT: NOP
  $r1 = MOV_D1 $dj0
  $p1, $dc0, $dc4 = ST_3D_dms_sts $m3, $p1, $d0_3d
...
---
name:            E1_MOV_D2_E1_ST_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D2_E1_ST_3D
    ; CHECK: $r1 = MOV_D2 $dj0
    ; CHECK-NEXT: $p1, $dc0, $dc4 = ST_3D_dms_sts killed $m3, killed $p1, killed $d0_3d
    ; CHECK-NEXT: NOP
  $r1 = MOV_D2 $dj0
  $p1, $dc0, $dc4 = ST_3D_dms_sts $m3, $p1, $d0_3d
...
---
name:            E1_MOV_D3_E1_ST_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D3_E1_ST_3D
    ; CHECK: $r1 = MOV_D3 $dj0
    ; CHECK-NEXT: $p1, $dc0, $dc4 = ST_3D_dms_sts killed $m3, killed $p1, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D3 $dj0
  $p1, $dc0, $dc4 = ST_3D_dms_sts $m3, $p1, $d0_3d
...
---
name:            E1_MOV_D4_E1_ST_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D4_E1_ST_3D
    ; CHECK: $r1 = MOV_D4 $dj0
    ; CHECK-NEXT: $p1, $dc0, $dc4 = ST_3D_dms_sts killed $m3, killed $p1, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D4 $dj0
  $p1, $dc0, $dc4 = ST_3D_dms_sts $m3, $p1, $d0_3d
...
---
name:            E1_MOV_D5_E1_ST_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D5_E1_ST_3D
    ; CHECK: $r1 = MOV_D5 $dj0
    ; CHECK-NEXT: $p1, $dc0, $dc4 = ST_3D_dms_sts killed $m3, killed $p1, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D5 $dj0
  $p1, $dc0, $dc4 = ST_3D_dms_sts $m3, $p1, $d0_3d
...
---
name:            E1_MOV_D6_E1_ST_3D
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D6_E1_ST_3D
    ; CHECK: $r1 = MOV_D6 $dj0
    ; CHECK-NEXT: $p1, $dc0, $dc4 = ST_3D_dms_sts killed $m3, killed $p1, killed $d0_3d
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  $r1 = MOV_D6 $dj0
  $p1, $dc0, $dc4 = ST_3D_dms_sts $m3, $p1, $d0_3d
...
---
name:            E1_MOV_D1_E1_JL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D1_E1_JL
    ; CHECK: $r1 = MOV_D1 $m0
    ; CHECK-NEXT: JL_IND killed $p1, implicit-def $lr
    ; CHECK-NEXT: $r1 = MOV_D1 $m0
    ; CHECK-NEXT: $r1 = MOV_D1 $m0
    ; CHECK-NEXT: $r1 = MOV_D1 $m0
    ; CHECK-NEXT: $r1 = MOV_D1 killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
  $r1 = MOV_D1 $m0
  $r1 = MOV_D1 $m0
  $r1 = MOV_D1 $m0
  $r1 = MOV_D1 $m0
  $r1 = MOV_D1 $m0
  JL_IND $p1, implicit-def $lr
  DelayedSchedBarrier
...
---
name:            E1_MOV_D2_E1_JL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D2_E1_JL
    ; CHECK: $r1 = MOV_D2 $m0
    ; CHECK-NEXT: $r1 = MOV_D2 $m0
    ; CHECK-NEXT: JL_IND killed $p1, implicit-def $lr
    ; CHECK-NEXT: $r1 = MOV_D2 $m0
    ; CHECK-NEXT: $r1 = MOV_D2 $m0
    ; CHECK-NEXT: $r1 = MOV_D2 killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
  $r1 = MOV_D2 $m0
  $r1 = MOV_D2 $m0
  $r1 = MOV_D2 $m0
  $r1 = MOV_D2 $m0
  $r1 = MOV_D2 $m0
  JL_IND $p1, implicit-def $lr
  DelayedSchedBarrier
...
---
name:            E1_MOV_D3_E1_JL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D3_E1_JL
    ; CHECK: $r1 = MOV_D3 $m0
    ; CHECK-NEXT: $r1 = MOV_D3 $m0
    ; CHECK-NEXT: $r1 = MOV_D3 $m0
    ; CHECK-NEXT: JL_IND killed $p1, implicit-def $lr
    ; CHECK-NEXT: $r1 = MOV_D3 $m0
    ; CHECK-NEXT: $r1 = MOV_D3 killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
  $r1 = MOV_D3 $m0
  $r1 = MOV_D3 $m0
  $r1 = MOV_D3 $m0
  $r1 = MOV_D3 $m0
  $r1 = MOV_D3 $m0
  JL_IND $p1, implicit-def $lr
  DelayedSchedBarrier
...
---
name:            E1_MOV_D4_E1_JL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D4_E1_JL
    ; CHECK: $r1 = MOV_D4 $m0
    ; CHECK-NEXT: $r1 = MOV_D4 $m0
    ; CHECK-NEXT: $r1 = MOV_D4 $m0
    ; CHECK-NEXT: $r1 = MOV_D4 $m0
    ; CHECK-NEXT: JL_IND killed $p1, implicit-def $lr
    ; CHECK-NEXT: $r1 = MOV_D4 killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
  $r1 = MOV_D4 $m0
  $r1 = MOV_D4 $m0
  $r1 = MOV_D4 $m0
  $r1 = MOV_D4 $m0
  $r1 = MOV_D4 $m0
  JL_IND $p1, implicit-def $lr
  DelayedSchedBarrier
...
---
name:            E1_MOV_D5_E1_JL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D5_E1_JL
    ; CHECK: $r1 = MOV_D5 $m0
    ; CHECK-NEXT: $r1 = MOV_D5 $m0
    ; CHECK-NEXT: $r1 = MOV_D5 $m0
    ; CHECK-NEXT: $r1 = MOV_D5 $m0
    ; CHECK-NEXT: $r1 = MOV_D5 killed $m0
    ; CHECK-NEXT: JL_IND killed $p1, implicit-def $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
  $r1 = MOV_D5 $m0
  $r1 = MOV_D5 $m0
  $r1 = MOV_D5 $m0
  $r1 = MOV_D5 $m0
  $r1 = MOV_D5 $m0
  JL_IND $p1, implicit-def $lr
  DelayedSchedBarrier
...
---
name:            E1_MOV_D6_E1_JL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_MOV_D6_E1_JL
    ; CHECK: $r1 = MOV_D6 $m0
    ; CHECK-NEXT: $r1 = MOV_D6 $m0
    ; CHECK-NEXT: $r1 = MOV_D6 $m0
    ; CHECK-NEXT: $r1 = MOV_D6 $m0
    ; CHECK-NEXT: $r1 = MOV_D6 killed $m0
    ; CHECK-NEXT: JL_IND killed $p1, implicit-def $lr
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
  $r1 = MOV_D6 $m0
  $r1 = MOV_D6 $m0
  $r1 = MOV_D6 $m0
  $r1 = MOV_D6 $m0
  $r1 = MOV_D6 $m0
  JL_IND $p1, implicit-def $lr
  DelayedSchedBarrier
...

---
name:            E1_II_MOV_SCL_E1_II_ST_MS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_II_MOV_SCL_E1_II_ST_MS
    ; CHECK: MOV_mv_scl2ms killed $m3
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $dj0
    ; CHECK-NEXT: NOP
  $r1 = MOV_mv_scl $dj0
  MOV_mv_scl2ms $m3
...

---
name:            E1_II_MOV_SCL_E1_II_ST_MS_NB
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_II_MOV_SCL_E1_II_ST_MS_NB
    ; CHECK: MOV_NB_mv_scl2ms killed $m3, implicit-def $srms0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $dj0
    ; CHECK-NEXT: NOP
  $r1 = MOV_mv_scl $dj0
  MOV_NB_mv_scl2ms $m3, implicit-def $srms0
...

---
name:            E1_II_MOV_SCL_E1_II_ST_MS_NB_TLAST_REG
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_II_MOV_SCL_E1_II_ST_MS_NB_TLAST_REG
    ; CHECK: MOV_NB_mv_scl2ms_doTlast_reg killed $m3, killed $r28, implicit-def $srms0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $dj0
    ; CHECK-NEXT: NOP
  $r1 = MOV_mv_scl $dj0
  MOV_NB_mv_scl2ms_doTlast_reg $m3, $r28, implicit-def $srms0
...

# This tests that we can't bundle the stream instruction which is in the S slot with an M slot instruction
# because of the slot conflict on reading pointers/modifiers in E1.
---
name:            E1_II_MOV_CPH_B_E1_II_MOV_SCL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_II_MOV_CPH_B_E1_II_MOV_SCL
    ; CHECK: MOV_mv_cph2ms killed $m2, 1, 2, killed $r0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  MOV_mv_cph2ms $m2, 1, 2, $r0
  $r1 = MOV_mv_scl $m0
...

---
name:            E1_II_MOV_CPH_NB_E1_II_MOV_SCL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_II_MOV_CPH_NB_E1_II_MOV_SCL
    ; CHECK: MOV_NB_mv_cph2ms killed $m1, 1, 2, killed $r2, implicit-def $srms0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  MOV_NB_mv_cph2ms $m1, 1, 2, $r2, implicit-def $srms0
  $r1 = MOV_mv_scl $m0
...

---
name:            E1_II_MOV_CPH_NB_TLAST_REG_E1_II_MOV_SCL
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E1_II_MOV_CPH_NB_TLAST_REG_E1_II_MOV_SCL
    ; CHECK: MOV_NB_mv_cph2ms_doTlast_reg killed $m1, 1, 2, killed $r2, killed $r28, implicit-def $srms0
    ; CHECK-NEXT: $r1 = MOV_mv_scl killed $m0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
  MOV_NB_mv_cph2ms_doTlast_reg $m1, 1, 2, $r2, $r28, implicit-def $srms0
  $r1 = MOV_mv_scl $m0
...

---
name:            mova_to_dj_movx_to_R_mov_to_P
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: mova_to_dj_movx_to_R_mov_to_P
    ; CHECK: BUNDLE implicit-def $dj1, implicit-def $r2, implicit-def $p0 {
    ; CHECK-NEXT:   $dj1 = MOVA_lda_cg 0
    ; CHECK-NEXT:   $r2 = MOVX_alu_cg 1
    ; CHECK-NEXT:   $p0 = MOV_mv_cg 0
    ; CHECK-NEXT: }
    $p0 = MOV_mv_cg 0
    $r2 = MOVX_alu_cg 1
    $dj1 = MOVA_lda_cg 0
...

---
name:            ldaPost_to_P
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ldaPost_to_P
    ; CHECK: BUNDLE implicit-def $p2, implicit-def $p0, implicit-def $r1, implicit-def $r2, implicit killed $p0, implicit killed $m0, implicit $r4 {
    ; CHECK-NEXT:   $p2, $p0 = LDA_dms_lda_pstm_nrm killed $p0, killed $m0
    ; CHECK-NEXT:   $r1 = MOVX_alu_cg 0
    ; CHECK-NEXT:   $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $dc0 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl killed $r4
    $p2, $p0 = LDA_dms_lda_pstm_nrm $p0, $m0
    $r1 = MOVX_alu_cg 0
    $dc0 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
...

---
name:            ldaPostImm_to_P
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: ldaPostImm_to_P
    ; CHECK: BUNDLE implicit-def $p1, implicit-def $p0, implicit-def $r1, implicit-def $r2, implicit killed $p0, implicit $r4 {
    ; CHECK-NEXT:   $p1, $p0 = LDA_dms_lda_pstm_nrm_imm killed $p0, 0
    ; CHECK-NEXT:   $r1 = MOVX_alu_cg 0
    ; CHECK-NEXT:   $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $dc0 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r2 = MOV_mv_scl killed $r4
    $p1, $p0 = LDA_dms_lda_pstm_nrm_imm $p0, 0
    $r1 = MOVX_alu_cg 0
    $dc0 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
    $r2 = MOV_mv_scl $r4
...

---
name:            lda2DPost_to_P
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: lda2DPost_to_P
    ; CHECK: BUNDLE implicit-def $p2, implicit-def $p0, implicit-def $dc0, implicit-def $r1, implicit-def $m2, implicit killed $p0, implicit killed $d0, implicit $r4 {
    ; CHECK-NEXT:   $p2, $p0, $dc0 = LDA_2D_dms_lda killed $p0, killed $d0
    ; CHECK-NEXT:   $r1 = MOVX_alu_cg 0
    ; CHECK-NEXT:   $m2 = MOV_mv_scl $r4
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $m2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $m2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $m2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $m2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $m2 = MOV_mv_scl $r4
    ; CHECK-NEXT: $m0 = MOV_mv_scl $r4
    ; CHECK-NEXT: $m2 = MOV_mv_scl killed $r4
    $p2, $p0, $dc0 = LDA_2D_dms_lda $p0, $d0
    $r1 = MOVX_alu_cg 0
    $m0 = MOV_mv_scl $r4
    $m2 = MOV_mv_scl $r4
    $m2 = MOV_mv_scl $r4
    $m2 = MOV_mv_scl $r4
    $m2 = MOV_mv_scl $r4
    $m2 = MOV_mv_scl $r4
    $m2 = MOV_mv_scl $r4
    $m2 = MOV_mv_scl $r4
...

---
name:            lda3DPost_to_P
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: lda3DPost_to_P
    ; CHECK: BUNDLE implicit-def $p2, implicit-def $p0, implicit-def $dc0, implicit-def $dc4, implicit-def $r1, implicit-def $p1, implicit killed $p0, implicit killed $d0_3d, implicit $r4 {
    ; CHECK-NEXT:   $p2, $p0, $dc0, $dc4 = LDA_3D_dms_lda killed $p0, killed $d0_3d
    ; CHECK-NEXT:   $r1 = MOVX_alu_cg 0
    ; CHECK-NEXT:   $p1 = MOV_mv_scl $r4
    ; CHECK-NEXT: }
    ; CHECK-NEXT: $p1 = MOV_mv_scl $r4
    ; CHECK-NEXT: $p1 = MOV_mv_scl $r4
    ; CHECK-NEXT: $p1 = MOV_mv_scl $r4
    ; CHECK-NEXT: $p1 = MOV_mv_scl $r4
    ; CHECK-NEXT: $p1 = MOV_mv_scl $r4
    ; CHECK-NEXT: $r0 = MOV_mv_scl $r4
    ; CHECK-NEXT: $p1 = MOV_mv_scl $r4
    ; CHECK-NEXT: $p1 = MOV_mv_scl killed $r4
    $p2, $p0, $dc0, $dc4 = LDA_3D_dms_lda $p0, $d0_3d
    $r1 = MOVX_alu_cg 0
    $r0 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
    $p1 = MOV_mv_scl $r4
...
