# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s

# MUL_mul_r_rr accesses WX write port in cycle 2, MOVX_alu_cg in cycle 1
# The scheduler needs to insert an additional NOP such that the
# two instructions don't access the same port in the same cycle
#
---
name:            E2_MUL_E1_MOVX_alu_cg
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E2_MUL_E1_MOVX_alu_cg
    ; CHECK: $r2 = MUL_mul_r_rr killed $r1, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r3 = MOVX_alu_cg 10
    $r2 = MUL_mul_r_rr $r1, $r0
    $r3 = MOVX_alu_cg 10
...

# MUL_mul_r_rr accesses WX write port in cycle 2, DIVS in cycle 1
# The scheduler needs to insert an additional NOP such that the
# two instructions don't access the same port in the same cycle
---
name:            E2_MUL_E1_DIVS
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: E2_MUL_E1_DIVS
    ; CHECK: BUNDLE implicit-def $r2, implicit-def $r4, implicit killed $r1, implicit killed $r0, implicit killed $r6 {
    ; CHECK-NEXT:   $r2 = MUL_mul_r_rr killed $r1, killed $r0
    ; CHECK-NEXT:   $r4 = MOV_mv_scl killed $r6
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r3, $r31 = DIVS killed $r31, killed $r4, killed $r5
    $r2 = MUL_mul_r_rr $r1, $r0
    $r4 = MOV_mv_scl $r6
    $r3, $r31 = DIVS  $r31, $r4, $r5
...
