# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %topdown-multi --verify-machineinstrs %s -o - | FileCheck %s
# Structural Conflicts - Upper half of the SRS
# VSRS/VST.SRS with CM input register E1 - both access this stage at E1, no
# VLIW packing should happen

---
name:            upper_srs
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: upper_srs
    ; CHECK: VST_SRS_S16_S64_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: $wh7 = VSRSM_D16_S32 killed $bml8, killed $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    VST_SRS_S16_S64_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $wh7 = VSRSM_D16_S32 $bml8, $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...

---
name:            upper_srs_post_inc
alignment:       16
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: upper_srs_post_inc
    ; CHECK: $p0 = VST_SRS_S16_S64_ag_pstm_nrm_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: $wh7 = VSRSM_D16_S32 killed $bmh4, killed $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0 = VST_SRS_S16_S64_ag_pstm_nrm_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $wh7 = VSRSM_D16_S32 $bmh4, $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
...
