# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p  -run-pass=aie-prelegalizer-combiner -verify-machineinstrs -o - %s  | FileCheck %s

---
name:            test1_single_use_acc_to_vec
alignment:       16
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: test1_single_use_acc_to_vec
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[COPY]](<16 x s64>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s32>)
    %0:_(<16 x s64>) = COPY $cml0
    %3:_(<32 x s32>) = G_BITCAST %0(<16 x s64>)
    %4:_(<16 x s32>), %5:_(<16 x s32>) = G_UNMERGE_VALUES %3(<32 x s32>)
   PseudoRET implicit $lr, implicit %4
...

---
name:            test2_single_use_two_umerges_acc_to_vec
alignment:       16
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $dm0
    ; CHECK-LABEL: name: test2_single_use_two_umerges_acc_to_vec
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s64>), [[UV1:%[0-9]+]]:_(<16 x s64>) = G_UNMERGE_VALUES [[COPY]](<32 x s64>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s64>), [[UV3:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV]](<16 x s64>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV2]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s32>)
    %0:_(<32 x s64>) = COPY $dm0
    %1:_(<16 x s64>), %2:_(<16 x s64>) = G_UNMERGE_VALUES %0(<32 x s64>)
    %3:_(<32 x s32>) = G_BITCAST %1(<16 x s64>)
    %4:_(<16 x s32>), %5:_(<16 x s32>) = G_UNMERGE_VALUES %3(<32 x s32>)
   PseudoRET implicit $lr, implicit %4
...

---
name:            test3_single_use_return_all_acc_to_vec
alignment:       16
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: test3_single_use_return_all_acc_to_vec
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[COPY]](<16 x s64>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV]](<8 x s64>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV1]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s32>), implicit [[BITCAST1]](<16 x s32>)
    %0:_(<16 x s64>) = COPY $cml0
    %3:_(<32 x s32>) = G_BITCAST %0(<16 x s64>)
    %4:_(<16 x s32>), %5:_(<16 x s32>) = G_UNMERGE_VALUES %3(<32 x s32>)
   PseudoRET implicit $lr, implicit %4, implicit %5
...

---
name:            test4_multiple_uses_acc_to_vec_neg
alignment:       16
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: test4_multiple_uses_acc_to_vec_neg
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[COPY]](<16 x s64>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[BITCAST]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](<16 x s32>), implicit [[BITCAST]](<32 x s32>)
    %0:_(<16 x s64>) = COPY $cml0
    %3:_(<32 x s32>) = G_BITCAST %0(<16 x s64>)
    %4:_(<16 x s32>), %5:_(<16 x s32>) = G_UNMERGE_VALUES %3(<32 x s32>)
   PseudoRET implicit $lr, implicit %4, implicit %3
...

---
name:            test5_single_use_vec_to_acc
alignment:       16
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $y0
    ; CHECK-LABEL: name: test5_single_use_vec_to_acc
    ; CHECK: liveins: $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[UV]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<8 x s64>)
    %0:_(<32 x s32>) = COPY $y0
    %3:_(<16 x s64>) = G_BITCAST %0(<32 x s32>)
    %4:_(<8 x s64>), %5:_(<8 x s64>) = G_UNMERGE_VALUES %3(<16 x s64>)
   PseudoRET implicit $lr, implicit %4
...

---
name:            test6_single_use_scalar_to_acc_neg
alignment:       16
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $y0
    ; CHECK-LABEL: name: test6_single_use_scalar_to_acc_neg
    ; CHECK: liveins: $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s1024) = COPY $y0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[COPY]](s1024)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[BITCAST]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](<8 x s64>)
    %0:_(s1024) = COPY $y0
    %3:_(<16 x s64>) = G_BITCAST %0(s1024)
    %4:_(<8 x s64>), %5:_(<8 x s64>) = G_UNMERGE_VALUES %3(<16 x s64>)
   PseudoRET implicit $lr, implicit %4
...

---
name:            test7_single_use_vec_to_scalar_no_effect
alignment:       16
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $y0
    ; CHECK-LABEL: name: test7_single_use_vec_to_scalar_no_effect
    ; CHECK: liveins: $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s1024) = G_BITCAST [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s512) = G_TRUNC [[BITCAST]](s1024)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[TRUNC]](s512)
    %0:_(<32 x s32>) = COPY $y0
    %3:_(s1024) = G_BITCAST %0(<32 x s32>)
    %4:_(s512), %5:_(s512) = G_UNMERGE_VALUES %3(s1024)
   PseudoRET implicit $lr, implicit %4
...
