# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p  -run-pass=aie-prelegalizer-combiner -verify-machineinstrs -o - %s  | FileCheck %s

---
name:            test1_single_use_vec_to_acc
alignment:       16
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test1_single_use_vec_to_acc
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:_(<64 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(<8 x s64>) = G_PHI [[DEF]](<8 x s64>), %bb.0, %14(<8 x s64>), %bb.1
  ; CHECK-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[PHI]](<8 x s64>), [[DEF]](<8 x s64>), [[DEF]](<8 x s64>), [[DEF]](<8 x s64>)
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(<64 x s32>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s64>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[BITCAST]](<64 x s32>), [[DEF1]](<64 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[BITCAST1:%[0-9]+]]:_(<32 x s64>) = G_BITCAST [[INT]](<64 x s32>)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(<16 x s64>), [[UV1:%[0-9]+]]:_(<16 x s64>) = G_UNMERGE_VALUES [[BITCAST1]](<32 x s64>)
  ; CHECK-NEXT:   [[UV2:%[0-9]+]]:_(<8 x s64>), [[UV3:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV]](<16 x s64>)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)

    %3:_(<8 x s64>) = G_IMPLICIT_DEF
    %7:_(<64 x s32>) = G_IMPLICIT_DEF
    %9:_(s32) = G_CONSTANT i32 1
    %18:_(<8 x s64>) = G_IMPLICIT_DEF
    %15:_(<16 x s32>) = G_IMPLICIT_DEF

  bb.2:
    successors: %bb.2(0x80000000)

    %0:_(<16 x s32>) = G_PHI %15(<16 x s32>), %bb.1, %12(<16 x s32>), %bb.2
    %1:_(<8 x s64>) = G_BITCAST %0(<16 x s32>)
    %21:_(<32 x s64>) = G_CONCAT_VECTORS %1(<8 x s64>), %3(<8 x s64>), %3(<8 x s64>), %3(<8 x s64>)
    %5:_(<64 x s32>) = G_BITCAST %21(<32 x s64>)
    %6:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %5(<64 x s32>), %7(<64 x s32>), %9(s32)
    %175:_(<32 x s64>) = G_BITCAST %6(<64 x s32>)
    %176:_(<16 x s64>), %284:_(<16 x s64>) = G_UNMERGE_VALUES %175(<32 x s64>)
    %286:_(<8 x s64>), %287:_(<8 x s64>) = G_UNMERGE_VALUES %176(<16 x s64>)
    %12:_(<16 x s32>) = G_BITCAST %286(<8 x s64>)
    G_BR %bb.2

...

---
name:            test2_multiple_uses_vec_to_acc
alignment:       16
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test2_multiple_uses_vec_to_acc
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:_(<64 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF2]](<16 x s32>), %bb.0, %6(<16 x s32>), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(<16 x s32>) = G_PHI [[DEF2]](<16 x s32>), %bb.0, %8(<16 x s32>), %bb.1
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[PHI]](<16 x s32>)
  ; CHECK-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s64>), [[DEF]](<8 x s64>), [[DEF]](<8 x s64>), [[DEF]](<8 x s64>)
  ; CHECK-NEXT:   [[BITCAST1:%[0-9]+]]:_(<64 x s32>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s64>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[BITCAST1]](<64 x s32>), [[DEF1]](<64 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[BITCAST2:%[0-9]+]]:_(<32 x s64>) = G_BITCAST [[INT]](<64 x s32>)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(<16 x s64>), [[UV1:%[0-9]+]]:_(<16 x s64>) = G_UNMERGE_VALUES [[BITCAST2]](<32 x s64>)
  ; CHECK-NEXT:   [[UV2:%[0-9]+]]:_(<8 x s64>), [[UV3:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV]](<16 x s64>)
  ; CHECK-NEXT:   [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV2]](<8 x s64>)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(<16 x s32>) = G_ADD [[PHI1]], [[PHI]]
  ; CHECK-NEXT:   G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)

    %3:_(<8 x s64>) = G_IMPLICIT_DEF
    %7:_(<64 x s32>) = G_IMPLICIT_DEF
    %9:_(s32) = G_CONSTANT i32 1
    %18:_(<8 x s64>) = G_IMPLICIT_DEF
    %15:_(<16 x s32>) = G_IMPLICIT_DEF

  bb.2:
    successors: %bb.2(0x80000000)

    %0:_(<16 x s32>) = G_PHI %15(<16 x s32>), %bb.1, %12(<16 x s32>), %bb.2
    %10:_(<16 x s32>) = G_PHI %15(<16 x s32>), %bb.1, %120(<16 x s32>), %bb.2
    %1:_(<8 x s64>) = G_BITCAST %0(<16 x s32>)
    %21:_(<32 x s64>) = G_CONCAT_VECTORS %1(<8 x s64>), %3(<8 x s64>), %3(<8 x s64>), %3(<8 x s64>)
    %5:_(<64 x s32>) = G_BITCAST %21(<32 x s64>)
    %6:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %5(<64 x s32>), %7(<64 x s32>), %9(s32)
    %175:_(<32 x s64>) = G_BITCAST %6(<64 x s32>)
    %176:_(<16 x s64>), %284:_(<16 x s64>) = G_UNMERGE_VALUES %175(<32 x s64>)
    %286:_(<8 x s64>), %287:_(<8 x s64>) = G_UNMERGE_VALUES %176(<16 x s64>)
    %12:_(<16 x s32>) = G_BITCAST %286(<8 x s64>)
    %120:_(<16 x s32>) = G_ADD %10(<16 x s32>), %0(<16 x s32>)
    G_BR %bb.2

...

