# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple=aie2p -run-pass=aie2p-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: vsel_all_zeros_to_copy
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_all_zeros_to_copy
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY %src1(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<16 x s32>) = COPY $x0
    %src2:_(<16 x s32>) = COPY $x1
    %sel:_(s32) = G_CONSTANT i32 0
    %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $x0 = COPY %dst(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_all_ones_to_copy
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_all_ones_to_copy
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src2:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: $x0 = COPY %src2(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<16 x s32>) = COPY $x0
    %src2:_(<16 x s32>) = COPY $x1
    %sel:_(s32) = G_CONSTANT i32 65535  ; 0xFFFF - all 16 bits set
    %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $x0 = COPY %dst(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_half_and_half_0xFF00
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_half_and_half_0xFF00
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %src2:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %src1(<16 x s32>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES %src2(<16 x s32>)
    ; CHECK-NEXT: %dst:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY %dst(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<16 x s32>) = COPY $x0
    %src2:_(<16 x s32>) = COPY $x1
    %sel:_(s32) = G_CONSTANT i32 65280  ; 0xFF00 - upper 8 bits set
    %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $x0 = COPY %dst(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_half_and_half_0x00FF
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_half_and_half_0x00FF
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %src2:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES %src1(<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR %src2(<16 x s32>)
    ; CHECK-NEXT: %dst:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: $x0 = COPY %dst(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<16 x s32>) = COPY $x0
    %src2:_(<16 x s32>) = COPY $x1
    %sel:_(s32) = G_CONSTANT i32 255  ; 0x00FF - lower 8 bits set
    %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $x0 = COPY %dst(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_8_elements_all_zeros
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: vsel_8_elements_all_zeros
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: $wl0 = COPY %src1(<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %src1:_(<8 x s32>) = COPY $wl0
    %src2:_(<8 x s32>) = COPY $wl1
    %sel:_(s32) = G_CONSTANT i32 0
    %dst:_(<8 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $wl0 = COPY %dst(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name: vsel_8_elements_all_ones
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: vsel_8_elements_all_ones
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src2:_(<8 x s32>) = COPY $wl1
    ; CHECK-NEXT: $wl0 = COPY %src2(<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %src1:_(<8 x s32>) = COPY $wl0
    %src2:_(<8 x s32>) = COPY $wl1
    %sel:_(s32) = G_CONSTANT i32 255  ; 0xFF - all 8 bits set
    %dst:_(<8 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $wl0 = COPY %dst(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name: vsel_8_elements_half_0xF0
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: vsel_8_elements_half_0xF0
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: %src2:_(<8 x s32>) = COPY $wl1
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %src1(<8 x s32>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES %src2(<8 x s32>)
    ; CHECK-NEXT: %dst:_(<8 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[UV1]](<4 x s32>)
    ; CHECK-NEXT: $wl0 = COPY %dst(<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %src1:_(<8 x s32>) = COPY $wl0
    %src2:_(<8 x s32>) = COPY $wl1
    %sel:_(s32) = G_CONSTANT i32 240  ; 0xF0 - upper 4 bits set
    %dst:_(<8 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $wl0 = COPY %dst(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name: vsel_8_elements_half_0x0F
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: vsel_8_elements_half_0x0F
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: %src2:_(<8 x s32>) = COPY $wl1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES %src1(<8 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %src2(<8 x s32>)
    ; CHECK-NEXT: %dst:_(<8 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[UV1]](<4 x s32>)
    ; CHECK-NEXT: $wl0 = COPY %dst(<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %src1:_(<8 x s32>) = COPY $wl0
    %src2:_(<8 x s32>) = COPY $wl1
    %sel:_(s32) = G_CONSTANT i32 15  ; 0x0F - lower 4 bits set
    %dst:_(<8 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $wl0 = COPY %dst(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name: vsel_32_elements_all_zeros
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_32_elements_all_zeros
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY %src1(<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<32 x s16>) = COPY $x0
    %src2:_(<32 x s16>) = COPY $x1
    %sel:_(s32) = G_CONSTANT i32 0
    %dst:_(<32 x s16>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $x0 = COPY %dst(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_32_elements_half_0xFFFF0000
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_32_elements_half_0xFFFF0000
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: %src2:_(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR %src1(<32 x s16>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES %src2(<32 x s16>)
    ; CHECK-NEXT: %dst:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<16 x s16>), [[UV1]](<16 x s16>)
    ; CHECK-NEXT: $x0 = COPY %dst(<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<32 x s16>) = COPY $x0
    %src2:_(<32 x s16>) = COPY $x1
    %sel:_(s64) = G_CONSTANT i64 4294901760  ; 0xFFFF0000 - upper 16 bits set
    %dst:_(<32 x s16>) = G_AIE_VSEL %src1, %src2, %sel(s64)
    $x0 = COPY %dst(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_32_elements_half_0x0000FFFF
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_32_elements_half_0x0000FFFF
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: %src2:_(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES %src1(<32 x s16>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR %src2(<32 x s16>)
    ; CHECK-NEXT: %dst:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<16 x s16>), [[UV1]](<16 x s16>)
    ; CHECK-NEXT: $x0 = COPY %dst(<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<32 x s16>) = COPY $x0
    %src2:_(<32 x s16>) = COPY $x1
    %sel:_(s64) = G_CONSTANT i64 65535  ; 0x0000FFFF - lower 16 bits set
    %dst:_(<32 x s16>) = G_AIE_VSEL %src1, %src2, %sel(s64)
    $x0 = COPY %dst(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_non_constant_mask_no_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: vsel_non_constant_mask_no_combine
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %src2:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: %sel:_(s32) = COPY $r0
    ; CHECK-NEXT: %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    ; CHECK-NEXT: $x0 = COPY %dst(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<16 x s32>) = COPY $x0
    %src2:_(<16 x s32>) = COPY $x1
    %sel:_(s32) = COPY $r0
    %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $x0 = COPY %dst(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_non_contiguous_pattern_no_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vsel_non_contiguous_pattern_no_combine
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: %src2:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: %sel:_(s32) = G_CONSTANT i32 61680
    ; CHECK-NEXT: %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    ; CHECK-NEXT: $x0 = COPY %dst(<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %src1:_(<16 x s32>) = COPY $x0
    %src2:_(<16 x s32>) = COPY $x1
    %sel:_(s32) = G_CONSTANT i32 61680  ; 0xF0F0 - alternating pattern
    %dst:_(<16 x s32>) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $x0 = COPY %dst(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name: vsel_scalar_type_no_combine
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: vsel_scalar_type_no_combine
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %src1:_(s32) = COPY $r0
    ; CHECK-NEXT: %src2:_(s32) = COPY $r1
    ; CHECK-NEXT: %sel:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %dst:_(s32) = G_AIE_VSEL %src1, %src2, %sel(s32)
    ; CHECK-NEXT: $r0 = COPY %dst(s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %src1:_(s32) = COPY $r0
    %src2:_(s32) = COPY $r1
    %sel:_(s32) = G_CONSTANT i32 1
    %dst:_(s32) = G_AIE_VSEL %src1, %src2, %sel(s32)
    $r0 = COPY %dst(s32)
    PseudoRET implicit $lr, implicit $r0

...
