# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie2p-postlegalizer-custom-combiner %s \
# RUN:         -verify-machineinstrs -o - | FileCheck %s --check-prefix=ENABLE-COMBINE
# RUN: llc -mtriple aie2p -run-pass=aie2p-postlegalizer-custom-combiner %s \
# RUN:         --aie-postinc-combine-move-multiple-instr=false -verify-machineinstrs \
# RUN:         -o - | FileCheck %s --check-prefix=DISABLE-COMBINE


# Move multiple independent instuction below the PADDx to enable post-inc combine
# In this case, we cannot move %6 = G_LOAD down & above PADD_3D, because the instructions between them depend on %6 = G_LOAD.
# However, we can move the dependent instructions chain of  virtual reg %6 below PADD_3D, if they are independent,
# thus allowing us to perform POST_INC_LOAD.
---
name:            post_inc_load
legalized:       false
body:             |
    bb.1.entry:
        liveins: $p0
    ; ENABLE-COMBINE-LABEL: name: post_inc_load
    ; ENABLE-COMBINE: liveins: $p0
    ; ENABLE-COMBINE-NEXT: {{  $}}
    ; ENABLE-COMBINE-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $p0
    ; ENABLE-COMBINE-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
    ; ENABLE-COMBINE-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; ENABLE-COMBINE-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; ENABLE-COMBINE-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C2]](s32)
    ; ENABLE-COMBINE-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[COPY]](s20)
    ; ENABLE-COMBINE-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<32 x s16>) = G_AIE_OFFSET_LOAD [[INTTOPTR]](p0), [[C1]](s20) :: (load (<32 x s16>), align 32, addrspace 6)
    ; ENABLE-COMBINE-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[AIE_OFFSET_LOAD]](<32 x s16>)
    ; ENABLE-COMBINE-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:_(<32 x s16>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:_ = G_AIE_POSTINC_3D_LOAD [[INTTOPTR]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (load (<32 x s16>), align 32, addrspace 6)
    ; ENABLE-COMBINE-NEXT: [[INT1:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[AIE_POSTINC_3D_LOAD]](<32 x s16>)
    ; ENABLE-COMBINE-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[INT1]](<32 x s32>), [[INT]](<32 x s32>)
    ; ENABLE-COMBINE-NEXT: [[INT2:%[0-9]+]]:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[AIE_BROADCAST_VECTOR]](<64 x s32>), [[CONCAT_VECTORS]](<64 x s32>), [[C2]](s32)
    ; ENABLE-COMBINE-NEXT: PseudoRET implicit $lr, implicit [[AIE_POSTINC_3D_LOAD1]](p0), implicit [[CONCAT_VECTORS]](<64 x s32>)
    ;
    ; DISABLE-COMBINE-LABEL: name: post_inc_load
    ; DISABLE-COMBINE: liveins: $p0
    ; DISABLE-COMBINE-NEXT: {{  $}}
    ; DISABLE-COMBINE-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $p0
    ; DISABLE-COMBINE-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
    ; DISABLE-COMBINE-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; DISABLE-COMBINE-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; DISABLE-COMBINE-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C2]](s32)
    ; DISABLE-COMBINE-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[COPY]](s20)
    ; DISABLE-COMBINE-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[INTTOPTR]](p0) :: (load (<32 x s16>), align 32, addrspace 6)
    ; DISABLE-COMBINE-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[LOAD]](<32 x s16>)
    ; DISABLE-COMBINE-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<32 x s16>) = G_AIE_OFFSET_LOAD [[INTTOPTR]](p0), [[C1]](s20) :: (load (<32 x s16>), align 32, addrspace 6)
    ; DISABLE-COMBINE-NEXT: [[INT1:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[AIE_OFFSET_LOAD]](<32 x s16>)
    ; DISABLE-COMBINE-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[INT]](<32 x s32>), [[INT1]](<32 x s32>)
    ; DISABLE-COMBINE-NEXT: [[INT2:%[0-9]+]]:_(p0), [[INT3:%[0-9]+]]:_(s20), [[INT4:%[0-9]+]]:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), [[INTTOPTR]](p0), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20)
    ; DISABLE-COMBINE-NEXT: [[INT5:%[0-9]+]]:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[AIE_BROADCAST_VECTOR]](<64 x s32>), [[CONCAT_VECTORS]](<64 x s32>), [[C2]](s32)
    ; DISABLE-COMBINE-NEXT: PseudoRET implicit $lr, implicit [[INT2]](p0), implicit [[CONCAT_VECTORS]](<64 x s32>)
        %0:_(s20) = COPY $p0
        %1:_(s20) = G_CONSTANT i20 0
        %2:_(s20) = G_CONSTANT i20 64
        %3:_(s32) = G_CONSTANT i32 0
        %4:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR %3:_(s32)
        %5:_(p0) = G_INTTOPTR %0:_(s20)
        %6:_(<32 x s16>) = G_LOAD %5:_(p0) :: (load (<32 x s16>), align 32, addrspace 6)
        %7:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), %6:_(<32 x s16>)
        %8:_(p0) = G_PTR_ADD %5:_, %2:_(s20)
        %9:_(<32 x s16>) = G_LOAD %8:_(p0) :: (load (<32 x s16>), align 32, addrspace 6)
        %10:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), %9:_(<32 x s16>)
        %11:_(<64 x s32>) = G_CONCAT_VECTORS %7:_(<32 x s32>), %10:_(<32 x s32>)
        %12:_(p0), %13:_(s20), %14:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %5:_(p0), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20)
        %15:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %4:_(<64 x s32>), %11:_(<64 x s32>), %3:_(s32)
        PseudoRET implicit $lr, implicit %12, implicit %11
...

---
name:            post_inc_load_side_effect
legalized:       false
body:             |
    bb.1.entry:
        liveins: $p0
    ; ENABLE-COMBINE-LABEL: name: post_inc_load_side_effect
    ; ENABLE-COMBINE: liveins: $p0
    ; ENABLE-COMBINE-NEXT: {{  $}}
    ; ENABLE-COMBINE-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $p0
    ; ENABLE-COMBINE-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
    ; ENABLE-COMBINE-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; ENABLE-COMBINE-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; ENABLE-COMBINE-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C2]](s32)
    ; ENABLE-COMBINE-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[COPY]](s20)
    ; ENABLE-COMBINE-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<32 x s16>) = G_AIE_OFFSET_LOAD [[INTTOPTR]](p0), [[C1]](s20) :: (load (<32 x s16>), align 32, addrspace 6)
    ; ENABLE-COMBINE-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[AIE_OFFSET_LOAD]](<32 x s16>)
    ; ENABLE-COMBINE-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:_(<32 x s16>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:_ = G_AIE_POSTINC_3D_LOAD [[INTTOPTR]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (load (<32 x s16>), align 32, addrspace 6)
    ; ENABLE-COMBINE-NEXT: [[INT1:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[AIE_POSTINC_3D_LOAD]](<32 x s16>)
    ; ENABLE-COMBINE-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[INT1]](<32 x s32>), [[INT]](<32 x s32>)
    ; ENABLE-COMBINE-NEXT: [[INT2:%[0-9]+]]:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[AIE_BROADCAST_VECTOR]](<64 x s32>), [[CONCAT_VECTORS]](<64 x s32>), [[C2]](s32)
    ; ENABLE-COMBINE-NEXT: PseudoRET implicit $lr, implicit [[AIE_POSTINC_3D_LOAD1]](p0), implicit [[CONCAT_VECTORS]](<64 x s32>)
    ;
    ; DISABLE-COMBINE-LABEL: name: post_inc_load_side_effect
    ; DISABLE-COMBINE: liveins: $p0
    ; DISABLE-COMBINE-NEXT: {{  $}}
    ; DISABLE-COMBINE-NEXT: [[COPY:%[0-9]+]]:_(s20) = COPY $p0
    ; DISABLE-COMBINE-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
    ; DISABLE-COMBINE-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; DISABLE-COMBINE-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; DISABLE-COMBINE-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C2]](s32)
    ; DISABLE-COMBINE-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[COPY]](s20)
    ; DISABLE-COMBINE-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[INTTOPTR]](p0) :: (load (<32 x s16>), align 32, addrspace 6)
    ; DISABLE-COMBINE-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[LOAD]](<32 x s16>)
    ; DISABLE-COMBINE-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<32 x s16>) = G_AIE_OFFSET_LOAD [[INTTOPTR]](p0), [[C1]](s20) :: (load (<32 x s16>), align 32, addrspace 6)
    ; DISABLE-COMBINE-NEXT: [[INT1:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), [[AIE_OFFSET_LOAD]](<32 x s16>)
    ; DISABLE-COMBINE-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[INT]](<32 x s32>), [[INT1]](<32 x s32>)
    ; DISABLE-COMBINE-NEXT: [[INT2:%[0-9]+]]:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[AIE_BROADCAST_VECTOR]](<64 x s32>), [[CONCAT_VECTORS]](<64 x s32>), [[C2]](s32)
    ; DISABLE-COMBINE-NEXT: [[INT3:%[0-9]+]]:_(p0), [[INT4:%[0-9]+]]:_(s20), [[INT5:%[0-9]+]]:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), [[INTTOPTR]](p0), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20), [[C]](s20)
    ; DISABLE-COMBINE-NEXT: PseudoRET implicit $lr, implicit [[INT3]](p0), implicit [[CONCAT_VECTORS]](<64 x s32>)
        %0:_(s20) = COPY $p0
        %1:_(s20) = G_CONSTANT i20 0
        %2:_(s20) = G_CONSTANT i20 64
        %3:_(s32) = G_CONSTANT i32 0
        %4:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR %3:_(s32)
        %5:_(p0) = G_INTTOPTR %0:_(s20)
        %6:_(<32 x s16>) = G_LOAD %5:_(p0) :: (load (<32 x s16>), align 32, addrspace 6)
        %7:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), %6:_(<32 x s16>)
        %8:_(p0) = G_PTR_ADD %5:_, %2:_(s20)
        %9:_(<32 x s16>) = G_LOAD %8:_(p0) :: (load (<32 x s16>), align 32, addrspace 6)
        %10:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v32bf16.to.v32accfloat), %9:_(<32 x s16>)
        %11:_(<64 x s32>) = G_CONCAT_VECTORS %7:_(<32 x s32>), %10:_(<32 x s32>)
        %15:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %4:_(<64 x s32>), %11:_(<64 x s32>), %3:_(s32)
        %12:_(p0), %13:_(s20), %14:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %5:_(p0), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20)
        PseudoRET implicit $lr, implicit %12, implicit %11
...


# Move multiple independent instuction below the PADDx to enable post-inc combine
# In this case, we cannot move %local_load_0 = G_LOAD down & above PADD_3D, because the instructions between them depend on %local_load_0 = G_LOAD.
# However, we can move the dependent instructions chain of virtual reg %local_load_0 below PADD_3D, if they are independent,  thus allowing us to
# perform POST_INC_LOAD.

# This test has G_PHI as one of the Use in its instructions chain of virtual reg %local_load_0
# %local_load_0 is used by %x_add:_(s32) = G_ADD, and %x_add is used by %s32_from_phi:_(s32) = G_PHI
# We do not get into a infinite loop while computing dependent instructions chain since we check if the distance of Def to Use < Def - PTR_XXX
# Since the distance is calculate in forward direction G_PHI will always lie ahead of PTR_XXX
---
name:              post_inc_load_with_PHI
legalized:         false
tracksRegLiveness: true
body:             |
  ; ENABLE-COMBINE-LABEL: name: post_inc_load_with_PHI
  ; ENABLE-COMBINE: bb.0.entry:
  ; ENABLE-COMBINE-NEXT:   successors: %bb.1(0x80000000)
  ; ENABLE-COMBINE-NEXT: {{  $}}
  ; ENABLE-COMBINE-NEXT:   %dummy_ptr:_(p0) = G_CONSTANT i20 0
  ; ENABLE-COMBINE-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; ENABLE-COMBINE-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; ENABLE-COMBINE-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; ENABLE-COMBINE-NEXT: {{  $}}
  ; ENABLE-COMBINE-NEXT: bb.1:
  ; ENABLE-COMBINE-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; ENABLE-COMBINE-NEXT: {{  $}}
  ; ENABLE-COMBINE-NEXT:   %ptr_from_phi:_(p0) = G_PHI %dummy_ptr(p0), %bb.0, %mod_ptr(p0), %bb.1
  ; ENABLE-COMBINE-NEXT:   %s32_from_phi:_(s32) = G_PHI [[C]](s32), %bb.0, %x_add(s32), %bb.1
  ; ENABLE-COMBINE-NEXT:   %local_load_2:_(s32) = G_AIE_OFFSET_LOAD %ptr_from_phi(p0), [[C2]](s20) :: (load (s32))
  ; ENABLE-COMBINE-NEXT:   %add:_(s32) = G_ADD %s32_from_phi, %local_load_2
  ; ENABLE-COMBINE-NEXT:   %local_load_0:_(s32), %mod_ptr:_(p0), %13:_(s20), %14:_ = G_AIE_POSTINC_3D_LOAD %ptr_from_phi, [[C1]], [[C1]], [[C1]], [[C1]], [[C1]], [[C1]], [[C1]] :: (load (s32))
  ; ENABLE-COMBINE-NEXT:   %add_0:_(s32) = G_ADD %local_load_0, [[C]]
  ; ENABLE-COMBINE-NEXT:   %x_add:_(s32) = G_ADD %add, %local_load_0
  ; ENABLE-COMBINE-NEXT:   G_BRCOND %mod_ptr(p0), %bb.1
  ; ENABLE-COMBINE-NEXT:   G_BR %bb.2
  ; ENABLE-COMBINE-NEXT: {{  $}}
  ; ENABLE-COMBINE-NEXT: bb.2:
  ; ENABLE-COMBINE-NEXT:   PseudoRET implicit $lr, implicit %add_0(s32)
  ;
  ; DISABLE-COMBINE-LABEL: name: post_inc_load_with_PHI
  ; DISABLE-COMBINE: bb.0.entry:
  ; DISABLE-COMBINE-NEXT:   successors: %bb.1(0x80000000)
  ; DISABLE-COMBINE-NEXT: {{  $}}
  ; DISABLE-COMBINE-NEXT:   %dummy_ptr:_(p0) = G_CONSTANT i20 0
  ; DISABLE-COMBINE-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; DISABLE-COMBINE-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; DISABLE-COMBINE-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; DISABLE-COMBINE-NEXT: {{  $}}
  ; DISABLE-COMBINE-NEXT: bb.1:
  ; DISABLE-COMBINE-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; DISABLE-COMBINE-NEXT: {{  $}}
  ; DISABLE-COMBINE-NEXT:   %ptr_from_phi:_(p0) = G_PHI %dummy_ptr(p0), %bb.0, %mod_ptr(p0), %bb.1
  ; DISABLE-COMBINE-NEXT:   %s32_from_phi:_(s32) = G_PHI [[C]](s32), %bb.0, %x_add(s32), %bb.1
  ; DISABLE-COMBINE-NEXT:   %local_load_0:_(s32) = G_LOAD %ptr_from_phi(p0) :: (load (s32))
  ; DISABLE-COMBINE-NEXT:   %add_0:_(s32) = G_ADD %local_load_0, [[C]]
  ; DISABLE-COMBINE-NEXT:   %local_load_2:_(s32) = G_AIE_OFFSET_LOAD %ptr_from_phi(p0), [[C2]](s20) :: (load (s32))
  ; DISABLE-COMBINE-NEXT:   %add:_(s32) = G_ADD %s32_from_phi, %local_load_2
  ; DISABLE-COMBINE-NEXT:   %x_add:_(s32) = G_ADD %add, %local_load_0
  ; DISABLE-COMBINE-NEXT:   %mod_ptr:_(p0), %13:_(s20), %14:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %ptr_from_phi(p0), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[C1]](s20), [[C1]](s20)
  ; DISABLE-COMBINE-NEXT:   G_BRCOND %mod_ptr(p0), %bb.1
  ; DISABLE-COMBINE-NEXT:   G_BR %bb.2
  ; DISABLE-COMBINE-NEXT: {{  $}}
  ; DISABLE-COMBINE-NEXT: bb.2:
  ; DISABLE-COMBINE-NEXT:   PseudoRET implicit $lr, implicit %add_0(s32)
    bb.0.entry:
        successors: %bb.1(0x80000000); %bb.1(100.00%)
        %dummy_ptr:_(p0) = G_CONSTANT i20 0
        %1:_(s32) = G_CONSTANT i32 0
        %2:_(s20) = G_CONSTANT i20 0
        %3:_(s20) = G_CONSTANT i20 0
    bb.1:
        successors: %bb.1(0x40000000), %bb.2(0x40000000); %bb.1(50.00%), %bb.2(50.00%)
        %ptr_from_phi:_(p0) = G_PHI %dummy_ptr:_(p0), %bb.0, %mod_ptr:_(p0), %bb.1
        %s32_from_phi:_(s32) = G_PHI %1:_(s32), %bb.0, %x_add:_(s32), %bb.1
        %local_load_0:_(s32) = G_LOAD %ptr_from_phi:_(p0) :: (load (s32))
        %add_0:_(s32) = G_ADD %local_load_0:_, %1:_
        %temp:_(p0) = G_PTR_ADD %ptr_from_phi:_, %3:_(s20)
        %local_load_2:_(s32) = G_LOAD %temp:_(p0) :: (load (s32))
        %add:_(s32) = G_ADD %s32_from_phi:_, %local_load_2:_
        %x_add:_(s32) = G_ADD %add:_, %local_load_0:_
        %mod_ptr:_(p0), %13:_(s20), %14:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %ptr_from_phi:_(p0), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20)
        G_BRCOND %mod_ptr:_(p0), %bb.1
        G_BR %bb.2
    bb.2:
        PseudoRET implicit $lr, implicit %add_0:_(s32)
...
