# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -start-before=instruction-select -stop-after=phi-node-elimination %s -verify-machineinstrs -o - | FileCheck %s

---
name:            v4s32
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v4s32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $q1, $q2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_1:vec128 = COPY killed $q1
  ; CHECK-NEXT:   %val_2:vec128 = COPY killed $q2
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vec128 = COPY killed %val_1
  ; CHECK-NEXT:   PseudoJNZ undef %cond:er, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vec128 = COPY killed %val_2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec128 = COPY killed [[COPY]]
  ; CHECK-NEXT:   $q0 = COPY killed %phi
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $q0
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $q1, $q2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<4 x s32>) = COPY $q1
    %val_2:vregbank(<4 x s32>) = COPY $q2
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    $q1 = COPY %val_2
    %val_3:vregbank(<4 x s32>) = COPY %val_2
  bb.2:
    %phi:vregbank(<4 x s32>) = G_PHI %val_3(<4 x s32>), %bb.1, %val_1(<4 x s32>), %bb.0
    $q0 = COPY %phi
    PseudoRET implicit $lr, implicit $q0
...
---
name:            v8s16
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v8s16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $q1, $q2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_1:vec128 = COPY killed $q1
  ; CHECK-NEXT:   %val_2:vec128 = COPY killed $q2
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vec128 = COPY killed %val_1
  ; CHECK-NEXT:   PseudoJNZ undef %cond:er, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vec128 = COPY killed %val_2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec128 = COPY killed [[COPY]]
  ; CHECK-NEXT:   $q0 = COPY killed %phi
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $q0
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $q1, $q2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<8 x s16>) = COPY $q1
    %val_2:vregbank(<8 x s16>) = COPY $q2
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    $q1 = COPY %val_2
    %val_3:vregbank(<8 x s16>) = COPY %val_2
  bb.2:
    %phi:vregbank(<8 x s16>) = G_PHI %val_3(<8 x s16>), %bb.1, %val_1(<8 x s16>), %bb.0
    $q0 = COPY %phi
    PseudoRET implicit $lr, implicit $q0
...
---
name:            v16s8
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v16s8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $q1, $q2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_1:vec128 = COPY killed $q1
  ; CHECK-NEXT:   %val_2:vec128 = COPY killed $q2
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vec128 = COPY killed %val_1
  ; CHECK-NEXT:   PseudoJNZ undef %cond:er, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vec128 = COPY killed %val_2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec128 = COPY killed [[COPY]]
  ; CHECK-NEXT:   $q0 = COPY killed %phi
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $q0
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $q1, $q2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<16 x s8>) = COPY $q1
    %val_2:vregbank(<16 x s8>) = COPY $q2
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    $q1 = COPY %val_2
    %val_3:vregbank(<16 x s8>) = COPY %val_2
  bb.2:
    %phi:vregbank(<16 x s8>) = G_PHI %val_3(<16 x s8>), %bb.1, %val_1(<16 x s8>), %bb.0
    $q0 = COPY %phi
    PseudoRET implicit $lr, implicit $q0
...


---
name:            v4s16
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v4s16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $l1, $l2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_1:el = COPY killed $l1
  ; CHECK-NEXT:   %val_2:el = COPY killed $l2
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:el = COPY killed %val_1
  ; CHECK-NEXT:   PseudoJNZ undef %cond:er, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:el = COPY killed %val_2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:el = COPY killed [[COPY]]
  ; CHECK-NEXT:   $l0 = COPY killed %phi
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $l0
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $l1, $l2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:gprregbank(<4 x s16>) = COPY $l1
    %val_2:gprregbank(<4 x s16>) = COPY $l2
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    $l1 = COPY %val_2
    %val_3:gprregbank(<4 x s16>) = COPY %val_2
  bb.2:
    %phi:gprregbank(<4 x s16>) = G_PHI %val_3(<4 x s16>), %bb.1, %val_1(<4 x s16>), %bb.0
    $l0 = COPY %phi
    PseudoRET implicit $lr, implicit $l0
...
---
name:            v2s32
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v2s32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $l1, $l2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_1:el = COPY killed $l1
  ; CHECK-NEXT:   %val_2:el = COPY killed $l2
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:el = COPY killed %val_1
  ; CHECK-NEXT:   PseudoJNZ undef %cond:er, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:el = COPY killed %val_2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:el = COPY killed [[COPY]]
  ; CHECK-NEXT:   $l0 = COPY killed %phi
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $l0
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $l1, $l2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:gprregbank(<2 x s32>) = COPY $l1
    %val_2:gprregbank(<2 x s32>) = COPY $l2
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    $l1 = COPY %val_2
    %val_3:gprregbank(<2 x s32>) = COPY %val_2
  bb.2:
    %phi:gprregbank(<2 x s32>) = G_PHI %val_3(<2 x s32>), %bb.1, %val_1(<2 x s32>), %bb.0
    $l0 = COPY %phi
    PseudoRET implicit $lr, implicit $l0
...
---
name:            v8s8
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v8s8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $l1, $l2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_1:el = COPY killed $l1
  ; CHECK-NEXT:   %val_2:el = COPY killed $l2
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:el = COPY killed %val_1
  ; CHECK-NEXT:   PseudoJNZ undef %cond:er, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:el = COPY killed %val_2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:el = COPY killed [[COPY]]
  ; CHECK-NEXT:   $l0 = COPY killed %phi
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed $l0
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $l1, $l2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:gprregbank(<8 x s8>) = COPY $l1
    %val_2:gprregbank(<8 x s8>) = COPY $l2
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    $l1 = COPY %val_2
    %val_3:gprregbank(<8 x s8>) = COPY %val_2
  bb.2:
    %phi:gprregbank(<8 x s8>) = G_PHI %val_3(<8 x s8>), %bb.1, %val_1(<8 x s8>), %bb.0
    $l0 = COPY %phi
    PseudoRET implicit $lr, implicit $l0
...
