# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie2p-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie2p-postlegalizer-custom-combiner -o - %s \
# RUN:   | FileCheck %s
# RUN: llc --mtriple=aie2ps -verify-machineinstrs \
# RUN:  --start-before=aie2ps-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie2ps-postlegalizer-custom-combiner -o - %s \
# RUN:   | FileCheck %s


# Eliminate unnecessary G_PTR_ADD chains

---
name:            ptr-add-imm-chain
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: ptr-add-imm-chain
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 192
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[C1]](s32), [[COPY]](p0), [[C]](s20) :: (store (s32))
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[C1]](s32), [[COPY]](p0), [[C2]](s20) :: (store (s32))
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[C1]](s32), [[COPY]](p0), [[C3]](s20) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s20) = G_CONSTANT i20 128
    %10:_(s20) = G_CONSTANT i20 192
    %3:_(s32) = G_CONSTANT i32 192
    %4:_(p0) = G_PTR_ADD %0, %1(s20)
    %5:_(p0) = G_PTR_ADD %0, %2(s20)
    %6:_(p0) = G_PTR_ADD %0, %10(s20)
    G_STORE %3(s32), %4(p0) :: (store (s32))
    G_STORE %3(s32), %5(p0) :: (store (s32))
    G_STORE %3(s32), %6(p0) :: (store (s32))
    PseudoRET implicit $lr
...
