# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDB_UNPACK_I512_I8_I4_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_signed
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s8>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s8>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I512_I16_I8_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_signed
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s8>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s8>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I1024_I8_I4_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_signed
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s16>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I1024_I16_I8_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_signed
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s16>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I512_I8_I4_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_unsigned
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s8>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s8>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I512_I16_I8_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_unsigned
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s8>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s8>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I1024_I8_I4_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_unsigned
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s16>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I1024_I16_I8_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_unsigned
    ; CHECK: liveins: $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s16>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I512_I8_I4_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_dynamic
    ; CHECK: liveins: $p0, $r1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s8>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s8>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r0
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I512_I16_I8_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s8>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s8>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r0
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I1024_I8_I4_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_dynamic
    ; CHECK: liveins: $p0, $r1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s16>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r0
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDB_UNPACK_I1024_I16_I8_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %25:vregbank(<32 x s16>), %8:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<32 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r0
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...
