# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            vconcat_v8s64_v4s64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:

    ; CHECK-LABEL: name: vconcat_v8s64_v4s64
    ; CHECK: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[DEF]], %subreg.sub_256_lo, [[DEF1]], %subreg.sub_256_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    %1:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    %2:vregbank(<8 x s64>) = G_CONCAT_VECTORS %0(<4 x s64>), %1(<4 x s64>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vconcat_1024_acc32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vconcat_1024_acc32
    ; CHECK: [[DEF:%[0-9]+]]:mwbfsrs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mwbfsrs = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[DEF]], %subreg.sub_512_acc_lo, [[DEF1]], %subreg.sub_512_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:accregbank(<16 x s32>) = G_IMPLICIT_DEF
    %1:accregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:accregbank(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vconcat_2048_acc64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vconcat_2048_acc64
    ; CHECK: [[DEF:%[0-9]+]]:ecml = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:ecmh = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[DEF]], %subreg.sub_1024_acc_lo, [[DEF1]], %subreg.sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %1:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %2:accregbank(<32 x s64>) = G_CONCAT_VECTORS %0(<16 x s64>), %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            vconcat_2048_acc32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: vconcat_2048_acc32
    ; CHECK: [[DEF:%[0-9]+]]:ecml = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:ecmh = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[DEF]], %subreg.sub_1024_acc_lo, [[DEF1]], %subreg.sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    %1:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    %2:accregbank(<64 x s32>) = G_CONCAT_VECTORS %0(<32 x s32>), %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %2
...
