# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_icmp_V16S32_slt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_slt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_32_vaddSign1_:%[0-9]+]]:ers16 = VLT_32_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[VLT_32_vaddSign1_]]
    ; CHECK-NEXT: $r0 = COPY [[COPY2]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(slt), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_ult
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_ult
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_32_vaddSign0_:%[0-9]+]]:ers16 = VLT_32_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[VLT_32_vaddSign0_]]
    ; CHECK-NEXT: $r0 = COPY [[COPY2]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ult), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_sle
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_sle
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_32_:%[0-9]+]]:vec512 = VSUB_32 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_32_:%[0-9]+]]:ers16 = VEQZ_32 [[VSUB_32_]]
    ; CHECK-NEXT: [[VLT_32_vaddSign1_:%[0-9]+]]:ers16 = VLT_32_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: [[OR:%[0-9]+]]:er = OR [[VLT_32_vaddSign1_]], [[VEQZ_32_]]
    ; CHECK-NEXT: $r0 = COPY [[OR]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(sle), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_ule
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_ule
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_32_:%[0-9]+]]:vec512 = VSUB_32 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_32_:%[0-9]+]]:ers16 = VEQZ_32 [[VSUB_32_]]
    ; CHECK-NEXT: [[VLT_32_vaddSign0_:%[0-9]+]]:ers16 = VLT_32_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: [[OR:%[0-9]+]]:er = OR [[VLT_32_vaddSign0_]], [[VEQZ_32_]]
    ; CHECK-NEXT: $r0 = COPY [[OR]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ule), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_sge
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_sge
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_32_vaddSign1_:%[0-9]+]]:ers16 = VGE_32_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[VGE_32_vaddSign1_]]
    ; CHECK-NEXT: $r0 = COPY [[COPY2]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(sge), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_uge
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_uge
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_32_vaddSign0_:%[0-9]+]]:ers16 = VGE_32_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[VGE_32_vaddSign0_]]
    ; CHECK-NEXT: $r0 = COPY [[COPY2]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(uge), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_sgt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_sgt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[VGE_32_vaddSign1_:%[0-9]+]]:ers16 = VGE_32_vaddSign1 [[COPY1]], [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[VGE_32_vaddSign1_]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $r0 = COPY [[XOR]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(sgt), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_ugt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_ugt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[VGE_32_vaddSign0_:%[0-9]+]]:ers16 = VGE_32_vaddSign0 [[COPY1]], [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[VGE_32_vaddSign0_]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $r0 = COPY [[XOR]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ugt), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_eq
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_eq
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_32_:%[0-9]+]]:vec512 = VSUB_32 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_32_:%[0-9]+]]:ers16 = VEQZ_32 [[VSUB_32_]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[VEQZ_32_]]
    ; CHECK-NEXT: $r0 = COPY [[COPY2]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(eq), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V16S32_ne
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V16S32_ne
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[VSUB_32_:%[0-9]+]]:vec512 = VSUB_32 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_32_:%[0-9]+]]:ers16 = VEQZ_32 [[VSUB_32_]]
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[VEQZ_32_]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $r0 = COPY [[XOR]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), %0, %1
    %4:gprregbank(<32 x s1>) = COPY %2
    $r0 = COPY %4
...

---
name: test_icmp_V32S16_slt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_slt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_16_vaddSign1_:%[0-9]+]]:ers16 = VLT_16_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: $r0 = COPY [[VLT_16_vaddSign1_]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(slt), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_ult
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_ult
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_16_vaddSign0_:%[0-9]+]]:ers16 = VLT_16_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: $r0 = COPY [[VLT_16_vaddSign0_]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ult), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_sle
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_sle
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_16_:%[0-9]+]]:vec512 = VSUB_16 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_16_:%[0-9]+]]:ers16 = VEQZ_16 [[VSUB_16_]]
    ; CHECK-NEXT: [[VLT_16_vaddSign1_:%[0-9]+]]:ers16 = VLT_16_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: [[OR:%[0-9]+]]:er = OR [[VLT_16_vaddSign1_]], [[VEQZ_16_]]
    ; CHECK-NEXT: $r0 = COPY [[OR]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(sle), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_ule
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_ule
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_16_:%[0-9]+]]:vec512 = VSUB_16 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_16_:%[0-9]+]]:ers16 = VEQZ_16 [[VSUB_16_]]
    ; CHECK-NEXT: [[VLT_16_vaddSign0_:%[0-9]+]]:ers16 = VLT_16_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: [[OR:%[0-9]+]]:er = OR [[VLT_16_vaddSign0_]], [[VEQZ_16_]]
    ; CHECK-NEXT: $r0 = COPY [[OR]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ule), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_sge
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_sge
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_16_vaddSign1_:%[0-9]+]]:ers16 = VGE_16_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: $r0 = COPY [[VGE_16_vaddSign1_]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(sge), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_uge
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_uge
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_16_vaddSign0_:%[0-9]+]]:ers16 = VGE_16_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: $r0 = COPY [[VGE_16_vaddSign0_]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(uge), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_sgt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_sgt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[VGE_16_vaddSign1_:%[0-9]+]]:ers16 = VGE_16_vaddSign1 [[COPY1]], [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[VGE_16_vaddSign1_]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $r0 = COPY [[XOR]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(sgt), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_ugt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_ugt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[VGE_16_vaddSign0_:%[0-9]+]]:ers16 = VGE_16_vaddSign0 [[COPY1]], [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[VGE_16_vaddSign0_]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $r0 = COPY [[XOR]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ugt), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_eq
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_eq
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_16_:%[0-9]+]]:vec512 = VSUB_16 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_16_:%[0-9]+]]:ers16 = VEQZ_16 [[VSUB_16_]]
    ; CHECK-NEXT: $r0 = COPY [[VEQZ_16_]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(eq), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V32S16_ne
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V32S16_ne
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[VSUB_16_:%[0-9]+]]:vec512 = VSUB_16 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_16_:%[0-9]+]]:ers16 = VEQZ_16 [[VSUB_16_]]
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[VEQZ_16_]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $r0 = COPY [[XOR]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V64S8_slt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_slt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_8_vaddSign1_:%[0-9]+]]:el = VLT_8_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: $l0 = COPY [[VLT_8_vaddSign1_]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(slt), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_ult
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_ult
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_8_vaddSign0_:%[0-9]+]]:el = VLT_8_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: $l0 = COPY [[VLT_8_vaddSign0_]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ult), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_sle
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_sle
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_8_vaddSign1_:%[0-9]+]]:el = VLT_8_vaddSign1 [[COPY1]], [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: [[VLT_8_vaddSign1_1:%[0-9]+]]:el = VLT_8_vaddSign1 [[COPY1]], [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY [[VLT_8_vaddSign1_1]].sub_l_odd
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:mlockid_reg = XOR [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mlockid_reg = COPY [[VLT_8_vaddSign1_]].sub_l_even
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:mlockid_reg = XOR [[COPY3]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[XOR1]], %subreg.sub_l_even, [[XOR]], %subreg.sub_l_odd
    ; CHECK-NEXT: $l0 = COPY [[REG_SEQUENCE]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(sle), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_ule
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_ule
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VLT_8_vaddSign0_:%[0-9]+]]:el = VLT_8_vaddSign0 [[COPY1]], [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: [[VLT_8_vaddSign0_1:%[0-9]+]]:el = VLT_8_vaddSign0 [[COPY1]], [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY [[VLT_8_vaddSign0_1]].sub_l_odd
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:mlockid_reg = XOR [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mlockid_reg = COPY [[VLT_8_vaddSign0_]].sub_l_even
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:mlockid_reg = XOR [[COPY3]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[XOR1]], %subreg.sub_l_even, [[XOR]], %subreg.sub_l_odd
    ; CHECK-NEXT: $l0 = COPY [[REG_SEQUENCE]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ule), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_sge
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_sge
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_8_vaddSign1_:%[0-9]+]]:el = VGE_8_vaddSign1 [[COPY]], [[COPY1]], implicit $vaddsign1
    ; CHECK-NEXT: $l0 = COPY [[VGE_8_vaddSign1_]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(sge), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_uge
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_uge
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_8_vaddSign0_:%[0-9]+]]:el = VGE_8_vaddSign0 [[COPY]], [[COPY1]], implicit $vaddsign0
    ; CHECK-NEXT: $l0 = COPY [[VGE_8_vaddSign0_]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(uge), %0, %1
    $l0 = COPY %2
...


---
name: test_icmp_V64S8_sgt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_sgt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_8_vaddSign1_:%[0-9]+]]:el = VGE_8_vaddSign1 [[COPY1]], [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: [[VGE_8_vaddSign1_1:%[0-9]+]]:el = VGE_8_vaddSign1 [[COPY1]], [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY [[VGE_8_vaddSign1_1]].sub_l_odd
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:mlockid_reg = XOR [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mlockid_reg = COPY [[VGE_8_vaddSign1_]].sub_l_even
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:mlockid_reg = XOR [[COPY3]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[XOR1]], %subreg.sub_l_even, [[XOR]], %subreg.sub_l_odd
    ; CHECK-NEXT: $l0 = COPY [[REG_SEQUENCE]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(sgt), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_ugt
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_ugt
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VGE_8_vaddSign0_:%[0-9]+]]:el = VGE_8_vaddSign0 [[COPY1]], [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: [[VGE_8_vaddSign0_1:%[0-9]+]]:el = VGE_8_vaddSign0 [[COPY1]], [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY [[VGE_8_vaddSign0_1]].sub_l_odd
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:mlockid_reg = XOR [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mlockid_reg = COPY [[VGE_8_vaddSign0_]].sub_l_even
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:mlockid_reg = XOR [[COPY3]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[XOR1]], %subreg.sub_l_even, [[XOR]], %subreg.sub_l_odd
    ; CHECK-NEXT: $l0 = COPY [[REG_SEQUENCE]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ugt), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_eq
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_eq
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_8_:%[0-9]+]]:vec512 = VSUB_8 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_8_:%[0-9]+]]:el = VEQZ_8 [[VSUB_8_]]
    ; CHECK-NEXT: $l0 = COPY [[VEQZ_8_]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(eq), %0, %1
    $l0 = COPY %2
...

---
name: test_icmp_V64S8_ne
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_icmp_V64S8_ne
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[VSUB_8_:%[0-9]+]]:vec512 = VSUB_8 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_8_:%[0-9]+]]:el = VEQZ_8 [[VSUB_8_]]
    ; CHECK-NEXT: [[VSUB_8_1:%[0-9]+]]:vec512 = VSUB_8 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[VEQZ_8_1:%[0-9]+]]:el = VEQZ_8 [[VSUB_8_1]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY [[VEQZ_8_1]].sub_l_odd
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:mlockid_reg = XOR [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mlockid_reg = COPY [[VEQZ_8_]].sub_l_even
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:mlockid_reg = XOR [[COPY3]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:el = REG_SEQUENCE [[XOR1]], %subreg.sub_l_even, [[XOR]], %subreg.sub_l_odd
    ; CHECK-NEXT: $l0 = COPY [[REG_SEQUENCE]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = COPY $x1
    %2:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), %0, %1
    $l0 = COPY %2
...

