# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VEC256_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_maxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_dmw_lda_w_idx_imm:%[0-9]+]]:vec256 = VLDA_dmw_lda_w_idx_imm [[COPY]], 224 :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLDA_dmw_lda_w_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 224
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC256_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_minOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_dmw_lda_w_idx_imm:%[0-9]+]]:vec256 = VLDA_dmw_lda_w_idx_imm [[COPY]], -256 :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLDA_dmw_lda_w_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -256
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC256_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_overMaxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[VLDA_dmw_lda_w_idx:%[0-9]+]]:vec256 = VLDA_dmw_lda_w_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLDA_dmw_lda_w_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 256
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC256_LOAD_overMinOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC256_LOAD_overMinOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -288
    ; CHECK-NEXT: [[VLDA_dmw_lda_w_idx:%[0-9]+]]:vec256 = VLDA_dmw_lda_w_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s32>))
    ; CHECK-NEXT: $wl0 = COPY [[VLDA_dmw_lda_w_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -288
    %0:vregbank(<8 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s32>))
    $wl0 = COPY %0:vregbank(<8 x s32>)
...

---
name:            VEC512_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_maxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_dmx_lda_x_idx_imm:%[0-9]+]]:vec512 = VLDA_dmx_lda_x_idx_imm [[COPY]], 448 :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLDA_dmx_lda_x_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            VEC512_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_minOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_dmx_lda_x_idx_imm:%[0-9]+]]:vec512 = VLDA_dmx_lda_x_idx_imm [[COPY]], -512 :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLDA_dmx_lda_x_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            VEC512_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_overMaxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[VLDA_dmx_lda_x_idx:%[0-9]+]]:vec512 = VLDA_dmx_lda_x_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLDA_dmx_lda_x_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            VEC512_LOAD_overMinOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEC512_LOAD_overMinOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; CHECK-NEXT: [[VLDA_dmx_lda_x_idx:%[0-9]+]]:vec512 = VLDA_dmx_lda_x_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[VLDA_dmx_lda_x_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    %0:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<16 x s32>))
    $x0 = COPY %0:vregbank(<16 x s32>)
...

---
name:            ACC512_LOAD_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: ACC512_LOAD_maxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], 448 :: (load (<8 x s64>))
    ; CHECK-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            ACC512_LOAD_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: ACC512_LOAD_minOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_dmx_lda_bm_idx_imm:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx_imm [[COPY]], -512 :: (load (<8 x s64>))
    ; CHECK-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx_imm]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            ACC512_LOAD_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: ACC512_LOAD_overMaxOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[VLDA_dmx_lda_bm_idx:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>))
    ; CHECK-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            ACC512_LOAD_overMinOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: ACC512_LOAD_overMinOffset
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; CHECK-NEXT: [[VLDA_dmx_lda_bm_idx:%[0-9]+]]:acc512 = VLDA_dmx_lda_bm_idx [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (<8 x s64>))
    ; CHECK-NEXT: $bmll0 = COPY [[VLDA_dmx_lda_bm_idx]]
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    %0:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %2:modregbank(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:accregbank(<8 x s64>)
...

---
name:            VEC256_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: VEC256_STORE_maxOffset
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: VST_dmw_sts_w_idx_imm [[COPY]], [[COPY1]], 224 :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 224
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC256_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: VEC256_STORE_minOffset
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: VST_dmw_sts_w_idx_imm [[COPY]], [[COPY1]], -256 :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -256
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC256_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: VEC256_STORE_overMaxOffset
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: VST_dmw_sts_w_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 256
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC256_STORE_overMinOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $wl0
    ; CHECK-LABEL: name: VEC256_STORE_overMinOffset
    ; CHECK: liveins: $p0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -288
    ; CHECK-NEXT: VST_dmw_sts_w_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s32>))
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -288
    G_AIE_OFFSET_STORE %0:vregbank(<8 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s32>))
...

---
name:            VEC512_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: VEC512_STORE_maxOffset
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY]], [[COPY1]], 448 :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            VEC512_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: VEC512_STORE_minOffset
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[COPY]], [[COPY1]], -512 :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            VEC512_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: VEC512_STORE_overMaxOffset
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: VST_dmx_sts_x_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            VEC512_STORE_overMinOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: VEC512_STORE_overMinOffset
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; CHECK-NEXT: VST_dmx_sts_x_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<16 x s32>))
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    G_AIE_OFFSET_STORE %0:vregbank(<16 x s32>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<16 x s32>))
...

---
name:            ACC512_STORE_maxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; CHECK-LABEL: name: ACC512_STORE_maxOffset
    ; CHECK: liveins: $bmll0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY]], [[COPY1]], 448 :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...

---
name:            ACC512_STORE_minOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; CHECK-LABEL: name: ACC512_STORE_minOffset
    ; CHECK: liveins: $bmll0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: VST_dmx_sts_bm_idx_imm [[COPY]], [[COPY1]], -512 :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -512
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...

---
name:            ACC512_STORE_overMaxOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; CHECK-LABEL: name: ACC512_STORE_overMaxOffset
    ; CHECK: liveins: $bmll0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: VST_dmx_sts_bm_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 512
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...

---
name:            ACC512_STORE_overMinOffset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0
    ; CHECK-LABEL: name: ACC512_STORE_overMinOffset
    ; CHECK: liveins: $bmll0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -576
    ; CHECK-NEXT: VST_dmx_sts_bm_idx [[COPY]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:ptrregbank(p0) = COPY $p0
    %2:modregbank(s20) = G_CONSTANT i20 -576
    G_AIE_OFFSET_STORE %0:accregbank(<8 x s64>), %1:ptrregbank(p0), %2:modregbank(s20) :: (store (<8 x s64>))
...
