# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

# Tests for combining VMAC + VADD -> VADDMAC patterns

---
name:            test_vaddmac_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_X_X
    ; CHECK: liveins: $x0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMAC_vmul_cm_core_X_X]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), %0(<16 x s32>), %1(<32 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_Y_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_Y_Y
    ; CHECK: liveins: $y0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMAC_vmul_cm_core_Y_Y]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.mac.conf), %0(<32 x s32>), %1(<64 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_X_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_X_Y
    ; CHECK: liveins: $x0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMAC_vmul_cm_core_X_Y]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.mac.conf), %0(<16 x s32>), %1(<64 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_Y_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_Y_X
    ; CHECK: liveins: $y0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_Y_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMAC_vmul_cm_core_Y_X]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.mac.conf), %0(<32 x s32>), %1(<32 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_bf16_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_bf16_X_X
    ; CHECK: liveins: $x0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VADD_f_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_f_vmac_cm2_add_reg [[VMAC_f_vmac_bf_vmul_bf_core_X_X]], [[COPY3]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADD_f_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.mac.conf), %0(<32 x s16>), %1(<32 x s16>), %2(<64 x s32>), %4(s32)
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %6(<64 x s32>), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_bf16_Y_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_bf16_Y_Y
    ; CHECK: liveins: $y0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VADD_f_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_f_vmac_cm2_add_reg [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y]], [[COPY3]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADD_f_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<64 x s16>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.mac.conf), %0(<64 x s16>), %1(<64 x s16>), %2(<64 x s32>), %4(s32)
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %6(<64 x s32>), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_X_X
    ; CHECK: liveins: $x0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VMSC_vmul_cm_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMSC_vmul_cm_core_X_X]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.msc.conf), %0(<16 x s32>), %1(<32 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_Y_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_Y_Y
    ; CHECK: liveins: $y0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_vmul_cm_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMSC_vmul_cm_core_Y_Y]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.msc.conf), %0(<32 x s32>), %1(<64 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_X_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_X_Y
    ; CHECK: liveins: $x0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMSC_vmul_cm_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMSC_vmul_cm_core_X_Y]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.msc.conf), %0(<16 x s32>), %1(<64 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_Y_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_Y_X
    ; CHECK: liveins: $y0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VMSC_vmul_cm_core_Y_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VMSC_vmul_cm_core_Y_X]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s32>) = COPY $y0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<32 x s64>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.msc.conf), %0(<32 x s32>), %1(<32 x s16>), %2(<32 x s64>), %4(s32)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %6(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_bf16_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_bf16_X_X
    ; CHECK: liveins: $x0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VADD_f_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_f_vmac_cm2_add_reg [[VMSC_f_vmac_bf_vmul_bf_core_X_X]], [[COPY3]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADD_f_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.msc.conf), %0(<32 x s16>), %1(<32 x s16>), %2(<64 x s32>), %4(s32)
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %6(<64 x s32>), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_bf16_Y_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_bf16_Y_Y
    ; CHECK: liveins: $y0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VADD_f_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_f_vmac_cm2_add_reg [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y]], [[COPY3]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADD_f_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<64 x s16>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.msc.conf), %0(<64 x s16>), %1(<64 x s16>), %2(<64 x s32>), %4(s32)
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %6(<64 x s32>), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...
