# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P

---
name:            512bit_const_idx_s64_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0, $r0
    ; AIE2P-LABEL: name: 512bit_const_idx_s64_elt
    ; AIE2P: liveins: $x0, $r0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:el = COPY $l0
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 8
    ; AIE2P-NEXT: [[VINSERT_64_mR29_insert:%[0-9]+]]:vec512 = VINSERT_64_mR29_insert [[COPY]], [[MOV_RLC_imm11_pseudo]], [[COPY1]]
    ; AIE2P-NEXT: $x3 = COPY [[VINSERT_64_mR29_insert]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $x3
    %0:vregbank(<8 x s64>) = COPY $x0
    %1:gprregbank(s64) = COPY $l0
    %2:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<8 x s64>) = G_AIE_INSERT_VECTOR_ELT %0:vregbank, %1:gprregbank(s64), %2:gprregbank(s32)
    $x3 = COPY %3:vregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $x3
...


---
name:            512bit_dyn_idx_s64_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; AIE2P-LABEL: name: 512bit_dyn_idx_s64_elt
    ; AIE2P: liveins: $x0, $r0, $r1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:el = COPY $l0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:mr29_insert = COPY $r1
    ; AIE2P-NEXT: [[VINSERT_64_mR29_insert:%[0-9]+]]:vec512 = VINSERT_64_mR29_insert [[COPY]], [[COPY2]], [[COPY1]]
    ; AIE2P-NEXT: $x3 = COPY [[VINSERT_64_mR29_insert]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $x3
    %0:vregbank(<8 x s64>) = COPY $x0
    %1:gprregbank(s64) = COPY $l0
    %2:gprregbank(s32) = COPY $r1
    %3:vregbank(<8 x s64>) = G_AIE_INSERT_VECTOR_ELT %0:vregbank, %1:gprregbank(s64), %2:gprregbank(s32)
    $x3 = COPY %3:vregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $x3
...
