# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: xor_s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: xor_s32
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[XOR]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_XOR %0, %1
    PseudoRET implicit $lr, implicit %2
...
---
name: xor_v2s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: xor_v2s16
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[XOR]]
    %0:gprregbank(<2 x s16>) = COPY $r6
    %1:gprregbank(<2 x s16>) = COPY $r7
    %2:gprregbank(<2 x s16>) = G_XOR %0, %1
    PseudoRET implicit $lr, implicit %2
...
---
name: xor_v4s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: xor_v4s8
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:er = XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[XOR]]
    %0:gprregbank(<4 x s8>) = COPY $r6
    %1:gprregbank(<4 x s8>) = COPY $r7
    %2:gprregbank(<4 x s8>) = G_XOR %0, %1
    PseudoRET implicit $lr, implicit %2
...
