# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_UPS_2x_BM_v16_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v16_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_BM_v8_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v8_acc64_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_CM_v16_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v16_acc64_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_CM_v32_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v32_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_CM_v32_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v32_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_CM_v16_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v16_acc64_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_DM_v32_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v32_acc64_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_DM_v64_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v64_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_BM_v16_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v16_acc32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_BM_v8_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v8_acc64_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_CM_v16_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v16_acc64_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_CM_v32_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v32_acc32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_CM_v32_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v32_acc32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_CM_v16_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v16_acc64_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_DM_v32_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v32_acc64_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_DM_v64_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v64_acc32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_BM_v16_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v16_acc32_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_BM_v8_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v8_acc64_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_CM_v16_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v16_acc64_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_CM_v32_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v32_acc32_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_CM_v32_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v32_acc32_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_2x_CM_v16_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v16_acc64_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_DM_v32_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v32_acc64_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VST_UPS_4x_DM_v64_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v64_acc32_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s32>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s32>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %5:vregbank(<16 x s32>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...
