# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            ld_fill
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: ld_fill
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:erf2 = VLD_FILL_512_pseudo [[DEF]], [[DEF1]], [[DEF2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_FILL_512_pseudo]], implicit [[VLD_FILL_512_pseudo1]], implicit [[VLD_FILL_512_pseudo2]]
    %2:modregbank(s20) = G_IMPLICIT_DEF
    %4:ptrregbank(p0) = G_IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = G_IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9
...

---
name:            ld_fillx
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: ld_fillx
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:fifo512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:mr30_fifo_step_e1 = IMPLICIT_DEF
    ; CHECK-NEXT: $lfe = COPY [[DEF3]]
    ; CHECK-NEXT: [[VLDB_FILLX_512_:%[0-9]+]]:eps, [[VLDB_FILLX_512_1:%[0-9]+]]:eldfiforeg, [[VLDB_FILLX_512_2:%[0-9]+]]:erf2 = VLDB_FILLX_512 [[DEF4]], [[DEF4]], [[DEF]], [[DEF1]], [[DEF2]], implicit-def $lfe, implicit $lfe
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mfifoextra = COPY $lfe
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_FILLX_512_]], implicit [[VLDB_FILLX_512_1]], implicit [[VLDB_FILLX_512_2]], implicit [[COPY]]
    %2:modregbank(s20) = G_IMPLICIT_DEF
    %4:ptrregbank(p0) = G_IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = G_IMPLICIT_DEF
    %10:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %11:gprregbank(s32) = G_IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32), %12:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fillx), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32), %10:fiforegbank(<16 x s32>), %11:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %12
...

---
name:            ld_popx
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: ld_popx
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:fifo512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:mr30_fifo_step_e1 = IMPLICIT_DEF
    ; CHECK-NEXT: $lfe = COPY [[DEF3]]
    ; CHECK-NEXT: [[VLDB_POPX_512_:%[0-9]+]]:vec512, [[VLDB_POPX_512_1:%[0-9]+]]:eps, [[VLDB_POPX_512_2:%[0-9]+]]:eldfiforeg, [[VLDB_POPX_512_3:%[0-9]+]]:erf2 = VLDB_POPX_512 [[DEF4]], [[DEF4]], [[DEF]], [[DEF1]], [[DEF2]], implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mfifoextra = COPY $lfe
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POPX_512_]], implicit [[VLDB_POPX_512_1]], implicit [[VLDB_POPX_512_2]], implicit [[VLDB_POPX_512_3]], implicit [[COPY]]
    %3:modregbank(s20) = G_IMPLICIT_DEF
    %5:ptrregbank(p0) = G_IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %7:gprregbank(s32) = G_IMPLICIT_DEF
    %12:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %13:gprregbank(s32) = G_IMPLICIT_DEF
    %8:vregbank(<64 x s8>), %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32), %14:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.popx), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %12:fiforegbank(<16 x s32>), %13:gprregbank(s32)
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11, implicit %14
...

---
name:            pop_unaligned
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_512_normal_pop_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_normal_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_normal_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_normal_pop_pseudo3:%[0-9]+]]:erf2 = VLD_POP_512_normal_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_normal_pop_pseudo]], implicit [[VLD_POP_512_normal_pop_pseudo1]], implicit [[VLD_POP_512_normal_pop_pseudo2]], implicit [[VLD_POP_512_normal_pop_pseudo3]]
    %3:modregbank(s20) = G_IMPLICIT_DEF
    %5:ptrregbank(p0) = G_IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %7:gprregbank(s32) = G_IMPLICIT_DEF
    %8:vregbank(<64 x s8>), %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.unaligned), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32)
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11
...

---
name:            pop_544
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_544
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_544_normal_pop_pseudo:%[0-9]+]]:vec576, [[VLD_POP_544_normal_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_544_normal_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_544_normal_pop_pseudo3:%[0-9]+]]:erf2 = VLD_POP_544_normal_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_544_normal_pop_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_544_normal_pop_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_544_normal_pop_pseudo1]], implicit [[VLD_POP_544_normal_pop_pseudo2]], implicit [[VLD_POP_544_normal_pop_pseudo3]], implicit [[COPY]], implicit [[COPY1]]
    %14:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %15:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %6:ptrregbank(p0) = G_IMPLICIT_DEF
    %7:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %8:gprregbank(s32) = G_IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32), %12:vregbank(<64 x s8>), %13:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.bfp16), %6:ptrregbank(p0), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32), %14:vregbank(<64 x s8>), %15:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %9, implicit %10, implicit %11, implicit %12, implicit %13
...

---
name:            pop_576
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_576
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_576_normal_pop_pseudo:%[0-9]+]]:vec576, [[VLD_POP_576_normal_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_576_normal_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_576_normal_pop_pseudo3:%[0-9]+]]:erf2 = VLD_POP_576_normal_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_576_normal_pop_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_576_normal_pop_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_576_normal_pop_pseudo1]], implicit [[VLD_POP_576_normal_pop_pseudo2]], implicit [[VLD_POP_576_normal_pop_pseudo3]], implicit [[COPY]], implicit [[COPY1]]
    %14:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %15:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %6:ptrregbank(p0) = G_IMPLICIT_DEF
    %7:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %8:gprregbank(s32) = G_IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32), %12:vregbank(<64 x s8>), %13:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.bfp16), %6:ptrregbank(p0), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32), %14:vregbank(<64 x s8>), %15:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %9, implicit %10, implicit %11, implicit %12, implicit %13
...

---
name:            pop_unaligned_1d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned_1d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_512_fifo_1d_pop_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_fifo_1d_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_fifo_1d_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_fifo_1d_pop_pseudo3:%[0-9]+]]:erf2 = VLD_POP_512_fifo_1d_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_fifo_1d_pop_pseudo]], implicit [[VLD_POP_512_fifo_1d_pop_pseudo1]], implicit [[VLD_POP_512_fifo_1d_pop_pseudo2]], implicit [[VLD_POP_512_fifo_1d_pop_pseudo3]]
    %6:ptrregbank(p0) = G_IMPLICIT_DEF
    %7:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %8:gprregbank(s32) = G_IMPLICIT_DEF
    %9:modregbank(s20) = G_IMPLICIT_DEF
    %10:vregbank(<64 x s8>), %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.1d.unaligned), %6:ptrregbank(p0), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32), %9:modregbank(s20)
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13
...

---
name:            pop_544_1d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_544_1d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_544_fifo_1d_pop_pseudo:%[0-9]+]]:vec576, [[VLD_POP_544_fifo_1d_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_544_fifo_1d_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_544_fifo_1d_pop_pseudo3:%[0-9]+]]:erf2 = VLD_POP_544_fifo_1d_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_544_fifo_1d_pop_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_544_fifo_1d_pop_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_544_fifo_1d_pop_pseudo1]], implicit [[VLD_POP_544_fifo_1d_pop_pseudo2]], implicit [[VLD_POP_544_fifo_1d_pop_pseudo3]], implicit [[COPY]], implicit [[COPY1]]
    %16:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %17:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %7:ptrregbank(p0) = G_IMPLICIT_DEF
    %8:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %9:gprregbank(s32) = G_IMPLICIT_DEF
    %10:modregbank(s20) = G_IMPLICIT_DEF
    %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32), %14:vregbank(<64 x s8>), %15:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.1d.bfp16), %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32), %10:modregbank(s20), %16:vregbank(<64 x s8>), %17:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...

---
name:            pop_576_1d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_576_1d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_576_fifo_1d_pop_pseudo:%[0-9]+]]:vec576, [[VLD_POP_576_fifo_1d_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_576_fifo_1d_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_576_fifo_1d_pop_pseudo3:%[0-9]+]]:erf2 = VLD_POP_576_fifo_1d_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[DEF3]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_576_fifo_1d_pop_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_576_fifo_1d_pop_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_576_fifo_1d_pop_pseudo1]], implicit [[VLD_POP_576_fifo_1d_pop_pseudo2]], implicit [[VLD_POP_576_fifo_1d_pop_pseudo3]], implicit [[COPY]], implicit [[COPY1]]
    %16:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %17:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %7:ptrregbank(p0) = G_IMPLICIT_DEF
    %8:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %9:gprregbank(s32) = G_IMPLICIT_DEF
    %10:modregbank(s20) = G_IMPLICIT_DEF
    %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32), %14:vregbank(<64 x s8>), %15:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.1d.bfp16), %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32), %10:modregbank(s20), %16:vregbank(<64 x s8>), %17:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15
...

---
name:            pop_unaligned_2d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_512_2D_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_2D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_2D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_2D_pseudo3:%[0-9]+]]:erf2, [[VLD_POP_512_2D_pseudo4:%[0-9]+]]:edc = VLD_POP_512_2D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_2D_pseudo]], implicit [[VLD_POP_512_2D_pseudo1]], implicit [[VLD_POP_512_2D_pseudo2]], implicit [[VLD_POP_512_2D_pseudo3]], implicit [[VLD_POP_512_2D_pseudo4]]
    %9:ptrregbank(p0) = G_IMPLICIT_DEF
    %10:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %11:gprregbank(s32) = G_IMPLICIT_DEF
    %12:modregbank(s20) = G_IMPLICIT_DEF
    %13:modregbank(s20) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %17:vregbank(<64 x s8>), %18:ptrregbank(p0), %19:fiforegbank(<32 x s32>), %20:gprregbank(s32), %21:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.2d.unaligned), %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32), %12:modregbank(s20), %13:modregbank(s20), %15:modregbank(s20), %16:modregbank(s20)
    PseudoRET implicit $lr, implicit %17, implicit %18, implicit %19, implicit %20, implicit %21

...

---
name:            pop_544_2d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_544_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_544_2D_pseudo:%[0-9]+]]:vec576, [[VLD_POP_544_2D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_544_2D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_544_2D_pseudo3:%[0-9]+]]:erf2, [[VLD_POP_544_2D_pseudo4:%[0-9]+]]:edc = VLD_POP_544_2D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_544_2D_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_544_2D_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]], implicit [[COPY1]], implicit [[VLD_POP_544_2D_pseudo1]], implicit [[VLD_POP_544_2D_pseudo2]], implicit [[VLD_POP_544_2D_pseudo3]], implicit [[VLD_POP_544_2D_pseudo4]]
    %24:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %25:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %10:ptrregbank(p0) = G_IMPLICIT_DEF
    %11:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %12:gprregbank(s32) = G_IMPLICIT_DEF
    %13:modregbank(s20) = G_IMPLICIT_DEF
    %14:modregbank(s20) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %17:modregbank(s20) = G_IMPLICIT_DEF
    %18:ptrregbank(p0), %19:fiforegbank(<32 x s32>), %20:gprregbank(s32), %21:modregbank(s20), %22:vregbank(<64 x s8>), %23:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.2d.bfp16), %10:ptrregbank(p0), %11:fiforegbank(<32 x s32>), %12:gprregbank(s32), %13:modregbank(s20), %14:modregbank(s20), %16:modregbank(s20), %17:modregbank(s20), %24:vregbank(<64 x s8>), %25:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %22, implicit %23, implicit %18, implicit %19, implicit %20, implicit %21

...

---
name:            pop_576_2d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_576_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_576_2D_pseudo:%[0-9]+]]:vec576, [[VLD_POP_576_2D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_576_2D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_576_2D_pseudo3:%[0-9]+]]:erf2, [[VLD_POP_576_2D_pseudo4:%[0-9]+]]:edc = VLD_POP_576_2D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_576_2D_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_576_2D_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]], implicit [[COPY1]], implicit [[VLD_POP_576_2D_pseudo1]], implicit [[VLD_POP_576_2D_pseudo2]], implicit [[VLD_POP_576_2D_pseudo3]], implicit [[VLD_POP_576_2D_pseudo4]]
    %24:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %25:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %10:ptrregbank(p0) = G_IMPLICIT_DEF
    %11:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %12:gprregbank(s32) = G_IMPLICIT_DEF
    %13:modregbank(s20) = G_IMPLICIT_DEF
    %14:modregbank(s20) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %17:modregbank(s20) = G_IMPLICIT_DEF
    %18:ptrregbank(p0), %19:fiforegbank(<32 x s32>), %20:gprregbank(s32), %21:modregbank(s20), %22:vregbank(<64 x s8>), %23:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.2d.bfp16), %10:ptrregbank(p0), %11:fiforegbank(<32 x s32>), %12:gprregbank(s32), %13:modregbank(s20), %14:modregbank(s20), %16:modregbank(s20), %17:modregbank(s20), %24:vregbank(<64 x s8>), %25:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %22, implicit %23, implicit %18, implicit %19, implicit %20, implicit %21

...

---
name:            pop_unaligned_3d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_512_3D_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_3D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_3D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_3D_pseudo3:%[0-9]+]]:erf2, [[VLD_POP_512_3D_pseudo4:%[0-9]+]]:edcl, [[VLD_POP_512_3D_pseudo5:%[0-9]+]]:edch = VLD_POP_512_3D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_3D_pseudo]], implicit [[VLD_POP_512_3D_pseudo1]], implicit [[VLD_POP_512_3D_pseudo2]], implicit [[VLD_POP_512_3D_pseudo3]], implicit [[VLD_POP_512_3D_pseudo4]], implicit [[VLD_POP_512_3D_pseudo5]]
    %12:ptrregbank(p0) = G_IMPLICIT_DEF
    %13:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %14:gprregbank(s32) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %18:modregbank(s20) = G_IMPLICIT_DEF
    %19:modregbank(s20) = G_IMPLICIT_DEF
    %20:modregbank(s20) = G_IMPLICIT_DEF
    %22:modregbank(s20) = G_IMPLICIT_DEF
    %23:modregbank(s20) = G_IMPLICIT_DEF
    %24:vregbank(<64 x s8>), %25:ptrregbank(p0), %26:fiforegbank(<32 x s32>), %27:gprregbank(s32), %28:modregbank(s20), %29:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.3d.unaligned), %12:ptrregbank(p0), %13:fiforegbank(<32 x s32>), %14:gprregbank(s32), %15:modregbank(s20), %16:modregbank(s20), %18:modregbank(s20), %19:modregbank(s20), %20:modregbank(s20), %22:modregbank(s20), %23:modregbank(s20)
    PseudoRET implicit $lr, implicit %24, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29
...

---
name:            pop_544_3d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_544_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_544_3D_pseudo:%[0-9]+]]:vec576, [[VLD_POP_544_3D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_544_3D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_544_3D_pseudo3:%[0-9]+]]:erf2, [[VLD_POP_544_3D_pseudo4:%[0-9]+]]:edcl, [[VLD_POP_544_3D_pseudo5:%[0-9]+]]:edch = VLD_POP_544_3D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_544_3D_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_544_3D_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF9]], implicit [[VLD_POP_544_3D_pseudo1]], implicit [[VLD_POP_544_3D_pseudo2]], implicit [[VLD_POP_544_3D_pseudo3]], implicit [[VLD_POP_544_3D_pseudo4]], implicit [[VLD_POP_544_3D_pseudo5]]
    %32:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %33:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %13:ptrregbank(p0) = G_IMPLICIT_DEF
    %14:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %15:gprregbank(s32) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %17:modregbank(s20) = G_IMPLICIT_DEF
    %19:modregbank(s20) = G_IMPLICIT_DEF
    %20:modregbank(s20) = G_IMPLICIT_DEF
    %21:modregbank(s20) = G_IMPLICIT_DEF
    %23:modregbank(s20) = G_IMPLICIT_DEF
    %24:modregbank(s20) = G_IMPLICIT_DEF
    %25:ptrregbank(p0), %26:fiforegbank(<32 x s32>), %27:gprregbank(s32), %28:modregbank(s20), %29:modregbank(s20), %30:vregbank(<64 x s8>), %31:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.3d.bfp16), %13:ptrregbank(p0), %14:fiforegbank(<32 x s32>), %15:gprregbank(s32), %16:modregbank(s20), %17:modregbank(s20), %19:modregbank(s20), %20:modregbank(s20), %21:modregbank(s20), %23:modregbank(s20), %24:modregbank(s20), %32:vregbank(<64 x s8>), %33:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %24, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29
...

---
name:            pop_576_3d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_576_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_576_3D_pseudo:%[0-9]+]]:vec576, [[VLD_POP_576_3D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_576_3D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_576_3D_pseudo3:%[0-9]+]]:erf2, [[VLD_POP_576_3D_pseudo4:%[0-9]+]]:edcl, [[VLD_POP_576_3D_pseudo5:%[0-9]+]]:edch = VLD_POP_576_3D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY [[VLD_POP_576_3D_pseudo]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY [[VLD_POP_576_3D_pseudo]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]], implicit [[COPY1]], implicit [[VLD_POP_576_3D_pseudo1]], implicit [[VLD_POP_576_3D_pseudo2]], implicit [[VLD_POP_576_3D_pseudo3]], implicit [[VLD_POP_576_3D_pseudo4]], implicit [[VLD_POP_576_3D_pseudo5]]
    %32:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %33:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %13:ptrregbank(p0) = G_IMPLICIT_DEF
    %14:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %15:gprregbank(s32) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %17:modregbank(s20) = G_IMPLICIT_DEF
    %19:modregbank(s20) = G_IMPLICIT_DEF
    %20:modregbank(s20) = G_IMPLICIT_DEF
    %21:modregbank(s20) = G_IMPLICIT_DEF
    %23:modregbank(s20) = G_IMPLICIT_DEF
    %24:modregbank(s20) = G_IMPLICIT_DEF
    %25:ptrregbank(p0), %26:fiforegbank(<32 x s32>), %27:gprregbank(s32), %28:modregbank(s20), %29:modregbank(s20), %30:vregbank(<64 x s8>), %31:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), %13:ptrregbank(p0), %14:fiforegbank(<32 x s32>), %15:gprregbank(s32), %16:modregbank(s20), %17:modregbank(s20), %19:modregbank(s20), %20:modregbank(s20), %21:modregbank(s20), %23:modregbank(s20), %24:modregbank(s20), %32:vregbank(<64 x s8>), %33:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %30, implicit %31, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29

...
