# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            512bit_splat_vector_64bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: 512bit_splat_vector_64bit_elt
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VBCST_64_:%[0-9]+]]:vec512 = VBCST_64 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VBCST_64_]]
    %0:gprregbank(<2 x s32>) = COPY $l0
    %1:vregbank(<8 x s64>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(<2 x s32>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            512bit_16x32_splat_vector_64bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: 512bit_16x32_splat_vector_64bit_elt
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VBCST_64_:%[0-9]+]]:vec512 = VBCST_64 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VBCST_64_]]
    %0:gprregbank(<2 x s32>) = COPY $l0
    %1:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(<2 x s32>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            512bit_32x16_splat_vector_64bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: 512bit_32x16_splat_vector_64bit_elt
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VBCST_64_:%[0-9]+]]:vec512 = VBCST_64 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VBCST_64_]]
    %0:gprregbank(<4 x s16>) = COPY $l0
    %1:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(<4 x s16>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            512bit_64x8_splat_vector_64bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: 512bit_64x8_splat_vector_64bit_elt
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VBCST_64_:%[0-9]+]]:vec512 = VBCST_64 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VBCST_64_]]
    %0:gprregbank(<8 x s8>) = COPY $l0
    %1:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(<8 x s8>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            512bit_32x16_splat_vector_32bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: 512bit_32x16_splat_vector_32bit_elt
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VBCST_32_:%[0-9]+]]:vec512 = VBCST_32 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VBCST_32_]]
    %0:gprregbank(<2 x s16>) = COPY $r0
    %1:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(<2 x s16>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            512bit_splat_vector_32bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: 512bit_splat_vector_32bit_elt
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VBCST_32_:%[0-9]+]]:vec512 = VBCST_32 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VBCST_32_]]
    %0:gprregbank(<4 x s8>) = COPY $r0
    %1:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(<4 x s8>)
    PseudoRET implicit $lr, implicit %1
...
