# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_shuffle
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e1, $e2, $r0, $x1, $x2

    ; CHECK-LABEL: name: test_shuffle
    ; CHECK: liveins: $e1, $e2, $r0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY $e2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexn = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_ex:%[0-9]+]]:mexm = VSHUFFLE_vec_shuffle_ex [[REG_SEQUENCE]], [[REG_SEQUENCE1]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[VSHUFFLE_vec_shuffle_ex]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:expvec64 = COPY [[VSHUFFLE_vec_shuffle_ex]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY5]], implicit [[COPY6]]
    %2:vregbank(<64 x s8>) = COPY $x1
    %3:gprregbank(<8 x s8>) = COPY $e1
    %4:vregbank(<64 x s8>) = COPY $x2
    %5:gprregbank(<8 x s8>) = COPY $e2
    %6:gprregbank(s32) = COPY $r0
    %7:vregbank(<64 x s8>), %8:gprregbank(<8 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle.576.bfp16), %2(<64 x s8>), %3(<8 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8

...
---
name:            test_shuffle_imlicitdef
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e1, $e2, $r0, $x1, $x2

    ; CHECK-LABEL: name: test_shuffle_imlicitdef
    ; CHECK: liveins: $e1, $e2, $r0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:expvec64 = IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexm = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexn = REG_SEQUENCE [[DEF]], %subreg.sub_bfp16_x, [[DEF1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_ex:%[0-9]+]]:mexm = VSHUFFLE_vec_shuffle_ex [[REG_SEQUENCE]], [[REG_SEQUENCE1]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY [[VSHUFFLE_vec_shuffle_ex]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:expvec64 = COPY [[VSHUFFLE_vec_shuffle_ex]].sub_bfp16_e
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY3]], implicit [[COPY4]]
    %2:vregbank(<64 x s8>) = COPY $x1
    %3:gprregbank(<8 x s8>) = COPY $e1
    %4:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    %5:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = COPY $r0
    %7:vregbank(<64 x s8>), %8:gprregbank(<8 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle.576.bfp16), %2(<64 x s8>), %3(<8 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8

...
