# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name:            test_get_scd_v128int4
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v128int4
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[VMOV_lda_mv_scd_x:%[0-9]+]]:vec512 = VMOV_lda_mv_scd_x implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $x0 = COPY [[VMOV_lda_mv_scd_x]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(s32) = COPY $r0
    %2:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.read.vec), %1(s32)
    %0:vregbank(<64 x s8>) = G_BITCAST %2(<16 x s32>)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            test_get_scd_v16acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v16acc32
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[VMOV_lda_mv_scd_bm:%[0-9]+]]:acc512 = VMOV_lda_mv_scd_bm implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $bmll0 = COPY [[VMOV_lda_mv_scd_bm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:gprregbank(s32) = COPY $r0
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.read.acc32), %1(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_get_scd_v32acc32_lo
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v32acc32_lo
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[VMOV_0_mv_scd_cm:%[0-9]+]]:acc1024 = VMOV_0_mv_scd_cm implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $cml0 = COPY [[VMOV_0_mv_scd_cm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:gprregbank(s32) = COPY $r0
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.lo), %1(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_get_scd_v32acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v32acc32
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[VMOV_1_mv_scd_cm:%[0-9]+]]:acc1024 = VMOV_1_mv_scd_cm implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $cml0 = COPY [[VMOV_1_mv_scd_cm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:gprregbank(s32) = COPY $r0
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.hi), %1(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_get_scd_v64acc32_0
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v64acc32_0
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VMOV_0_mv_scd_dm_imm:%[0-9]+]]:acc2048 = VMOV_0_mv_scd_dm_imm implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $dm0 = COPY [[VMOV_0_mv_scd_dm_imm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_get_scd_v64acc32_1
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v64acc32_1
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[VMOV_1_mv_scd_dm_imm:%[0-9]+]]:acc2048 = VMOV_1_mv_scd_dm_imm implicit $crscden
    ; CHECK-NEXT: $dm0 = COPY [[VMOV_1_mv_scd_dm_imm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_get_scd_v64acc32_2
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v64acc32_2
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 2
    ; CHECK-NEXT: [[VMOV_2_:%[0-9]+]]:acc2048 = VMOV_2 implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $dm0 = COPY [[VMOV_2_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = G_CONSTANT i32 2
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_get_scd_v64acc32_3
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: test_get_scd_v64acc32_3
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 3
    ; CHECK-NEXT: [[VMOV_3_:%[0-9]+]]:acc2048 = VMOV_3 implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $dm0 = COPY [[VMOV_3_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = G_CONSTANT i32 3
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_get_scd_expand_v32acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: test_get_scd_expand_v32acc32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mr31_scd = COPY [[COPY1]]
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[VMOV_lda_mv_scd_dm_reg:%[0-9]+]]:acc2048 = VMOV_lda_mv_scd_dm_reg [[COPY2]], implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc1024 = COPY [[VMOV_lda_mv_scd_dm_reg]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = COPY $r1
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.ACC1024), %1(s32), %2(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_get_scd_expand_v64acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: test_get_scd_expand_v64acc32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mr31_scd = COPY [[COPY1]]
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[VMOV_lda_mv_scd_dm_reg:%[0-9]+]]:acc2048 = VMOV_lda_mv_scd_dm_reg [[COPY2]], implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $dm0 = COPY [[VMOV_lda_mv_scd_dm_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = COPY $r1
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_put_mcd
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0

    ; CHECK-LABEL: name: test_put_mcd
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crmcden = COPY [[COPY1]]
    ; CHECK-NEXT: VMOV_st_mv_mcd_x [[COPY]], implicit $crmcden
    ; CHECK-NEXT: $crmcden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:gprregbank(s32) = COPY $r0
    %2:vregbank(<16 x s32>) = G_BITCAST %0(<64 x s8>)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.mcd.write.vec), %2(<16 x s32>), %1(s32)
    PseudoRET implicit $lr

...
---
name:            test_put_mcd_acc
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0

    ; CHECK-LABEL: name: test_put_mcd_acc
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crmcden = COPY [[COPY1]]
    ; CHECK-NEXT: VMOV_st_mv_mcd_bm [[COPY]], implicit $crmcden
    ; CHECK-NEXT: $crmcden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.mcd.write.acc32), %0(<8 x s64>), %1(s32)
    PseudoRET implicit $lr

...
---
name:            test_get_ss
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_get_ss
    ; CHECK: [[MOV_lda:%[0-9]+]]:er = MOV_lda implicit-def $srss0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $srss0
    ; CHECK-NEXT: $r0 = COPY [[MOV_lda]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32), %2:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.get.ss)
    $r0 = COPY %1(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_get_ss_nb
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: test_get_ss_nb
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_nb_lda:%[0-9]+]]:er = MOV_nb_lda implicit-def $srss0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $srss0
    ; CHECK-NEXT: [[AND:%[0-9]+]]:er = AND [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: ST_s8_idx_imm [[AND]], [[COPY1]], 0, implicit-def dead $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: [[EXTEND_u8_:%[0-9]+]]:er = EXTEND_u8 [[COPY2]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo -1
    ; CHECK-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[EXTEND_u8_]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:er = AND [[LSHL]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: ST_s8_idx_imm [[AND1]], [[COPY]], 0, implicit-def dead $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: $r0 = COPY [[MOV_nb_lda]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:ptrregbank(p0) = COPY $p0
    %2:ptrregbank(p0) = COPY $p1
    %20:gprregbank(s32) = G_CONSTANT i32 1
    %3:gprregbank(s32), %4:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.get.ss.nb)
    %19:gprregbank(s32) = G_AND %4, %20
    G_STORE %19(s32), %2(p0) :: (store (s8))
    %21:gprregbank(s32) = G_CONSTANT i32 255
    %14:gprregbank(s32) = G_AND %4, %21
    %15:gprregbank(s32) = G_LSHR %14, %20(s32)
    %13:gprregbank(s32) = G_AND %15, %20
    G_STORE %13(s32), %1(p0) :: (store (s8))
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_put_ms
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: test_put_ms
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr28_tlast = COPY $r1
    ; CHECK-NEXT: MOV_st_mMStream_tlast_reg [[COPY]], [[COPY1]], implicit-def $srms0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.put.ms), %0(s32), %1(s32)
    PseudoRET implicit $lr

...
---
name:            test_put_ms_nb
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0

    ; CHECK-LABEL: name: test_put_ms_nb
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: MOV_nb_st_mMStream_tlast_imm [[COPY]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: [[NEZ:%[0-9]+]]:er = NEZ [[COPY2]]
    ; CHECK-NEXT: ST_s8_idx_imm [[NEZ]], [[COPY1]], 0, implicit-def dead $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(<2 x s16>) = COPY $r0
    %1:ptrregbank(p0) = COPY $p0
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:gprregbank(s32) = G_BITCAST %0(<2 x s16>)
    %3:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.put.ms.nb), %2(s32), %4(s32)
    %8:gprregbank(s32) = G_ICMP intpred(ne), %3(s32), %4
    G_STORE %8(s32), %1(p0) :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            _Z33test_get_scd_expand_v32acc32_incriRi
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0

    ; CHECK-LABEL: name: _Z33test_get_scd_expand_v32acc32_incriRi
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:magusrc_and_mdm = LDA_dms_lda_idx_imm [[COPY1]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY [[LDA_dms_lda_idx_imm]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mr31_scd = COPY [[COPY2]]
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[VMOV_lda_mv_scd_dm_dyn:%[0-9]+]]:acc2048, [[VMOV_lda_mv_scd_dm_dyn1:%[0-9]+]]:mr31_divs = VMOV_lda_mv_scd_dm_dyn [[COPY3]], implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc1024 = COPY [[VMOV_lda_mv_scd_dm_dyn]].sub_1024_acc_lo
    ; CHECK-NEXT: ST_dms_sts_idx_imm [[VMOV_lda_mv_scd_dm_dyn1]], [[COPY1]], 0 :: (store (s32))
    ; CHECK-NEXT: $cml0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:gprregbank(s32) = COPY $r0
    %2:ptrregbank(p0) = COPY $p0
    %3:modregbank(s20) = G_LOAD %2(p0) :: (dereferenceable load (s20))
    %7:ptrregbank(s20) = COPY %3(s20)
    %4:ptrregbank(p0) = G_INTTOPTR %7(s20)
    %5:accregbank(<16 x s64>), %6:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.ACC1024.incr), %1(s32), %4(p0)
    G_STORE %6(s32), %2(p0) :: (store (s32))
    %0:accregbank(<32 x s32>) = G_BITCAST %5(<16 x s64>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z33test_get_scd_expand_v64acc32_incriRi
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0

    ; CHECK-LABEL: name: _Z33test_get_scd_expand_v64acc32_incriRi
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[LDA_dms_lda_idx_imm:%[0-9]+]]:magusrc_and_mdm = LDA_dms_lda_idx_imm [[COPY1]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY [[LDA_dms_lda_idx_imm]]
    ; CHECK-NEXT: $crscden = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mr31_scd = COPY [[COPY2]]
    ; CHECK-NEXT: [[VMOV_lda_mv_scd_dm_dyn:%[0-9]+]]:acc2048, [[VMOV_lda_mv_scd_dm_dyn1:%[0-9]+]]:mr31_divs = VMOV_lda_mv_scd_dm_dyn [[COPY3]], implicit $crscden
    ; CHECK-NEXT: $crscden = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: ST_dms_sts_idx_imm [[VMOV_lda_mv_scd_dm_dyn1]], [[COPY1]], 0 :: (store (s32))
    ; CHECK-NEXT: $dm0 = COPY [[VMOV_lda_mv_scd_dm_dyn]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:gprregbank(s32) = COPY $r0
    %2:ptrregbank(p0) = COPY $p0
    %3:modregbank(s20) = G_LOAD %2(p0) :: (dereferenceable load (s20))
    %7:ptrregbank(s20) = COPY %3(s20)
    %4:ptrregbank(p0) = G_INTTOPTR %7(s20)
    %5:accregbank(<32 x s64>), %6:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.ACC2048.incr), %1(s32), %4(p0)
    G_STORE %6(s32), %2(p0) :: (store (s32))
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z14test_put_ms_nbDv2_tiRb
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1

    ; CHECK-LABEL: name: _Z14test_put_ms_nbDv2_tiRb
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr28_tlast = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: MOV_nb_st_mMStream_tlast_reg [[COPY]], [[COPY1]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: [[NEZ:%[0-9]+]]:er = NEZ [[COPY3]]
    ; CHECK-NEXT: ST_s8_idx_imm [[NEZ]], [[COPY2]], 0, implicit-def dead $pe2_ads, implicit $pe2_ads :: (store (s8))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(<2 x s16>) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:ptrregbank(p0) = COPY $p0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %3:gprregbank(s32) = G_BITCAST %0(<2 x s16>)
    %4:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.put.ms.nb), %3(s32), %1(s32)
    %9:gprregbank(s32) = G_ICMP intpred(ne), %4(s32), %5
    G_STORE %9(s32), %2(p0) :: (store (s8))
    PseudoRET implicit $lr

...
---
name:            _Z11test_put_msDv8_ti
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: _Z11test_put_msDv8_ti
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: MOV_tlast [[MOV_RLC_imm11_pseudo]], implicit-def $srms0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:gprregbank(s32) = G_CONSTANT i32 0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.put.ms), %1(s32), %2(s32)
    PseudoRET implicit $lr

...
---
name:            _Z14test_put_ms_nbfiRb
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0

    ; CHECK-LABEL: name: _Z14test_put_ms_nbfiRb
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: MOV_nb_tlast [[COPY]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:gprregbank(s32) = G_CONSTANT i32 1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.put.ms.nb), %2(s32), %1(s32)
    PseudoRET implicit $lr

...
