# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_PACK_512_I8_I16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_signed
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: VST_PACK_dmw_sts_pack_idx_imm_packSign1 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<32 x s16>) = COPY $x0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %0:vregbank(<32 x s16>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<32 x s8>), %2:ptrregbank(p0) :: (store (<32 x s8>))
    PseudoRET implicit $lr
...
# Note: The output of intrinsic(@llvm.aie2p.pack.I512.I4.I8) must be of type <64 x s4>
# but we don't lower any vector element type less than 8-bit from the front end
# because the clang vector types do not support element types smaller than a byte.
# So the return type is changed from <64 x s4> to <32 x s8>.
---
name:            VST_PACK_512_I4_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_signed
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: VST_PACK_dmw_sts_pack_idx_imm_packSign1 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<64 x s8>) = COPY $x0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %0:vregbank(<64 x s8>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<32 x s8>), %2:ptrregbank(p0) :: (store (<32 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_1024_I8_I16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_signed
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: VST_PACK_dmx_sts_pack_idx_imm_packSign1 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<64 x s16>) = COPY $y0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %0:vregbank(<64 x s16>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<64 x s8>), %2:ptrregbank(p0) :: (store (<64 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_1024_I4_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_signed
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: VST_PACK_dmx_sts_pack_idx_imm_packSign1 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<128 x s8>) = COPY $y0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %0:vregbank(<128 x s8>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<64 x s8>), %2:ptrregbank(p0) :: (store (<64 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_512_I8_I16_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_unsigned
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<32 x s16>) = COPY $x0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %0:vregbank(<32 x s16>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<32 x s8>), %2:ptrregbank(p0) :: (store (<32 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_512_I4_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_unsigned
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<64 x s8>) = COPY $x0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %0:vregbank(<64 x s8>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<32 x s8>), %2:ptrregbank(p0) :: (store (<32 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_1024_I8_I16_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_unsigned
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: VST_PACK_dmx_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<64 x s16>) = COPY $y0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %0:vregbank(<64 x s16>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<64 x s8>), %2:ptrregbank(p0) :: (store (<64 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_1024_I4_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_unsigned
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: VST_PACK_dmx_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<128 x s8>) = COPY $y0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %0:vregbank(<128 x s8>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<64 x s8>), %2:ptrregbank(p0) :: (store (<64 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_512_I8_I16_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_dynamic
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<32 x s16>) = COPY $x0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %0:vregbank(<32 x s16>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<32 x s8>), %2:ptrregbank(p0) :: (store (<32 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_512_I4_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<64 x s8>) = COPY $x0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %0:vregbank(<64 x s8>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<32 x s8>), %2:ptrregbank(p0) :: (store (<32 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_1024_I8_I16_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_dynamic
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: VST_PACK_dmx_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<64 x s16>) = COPY $y0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %0:vregbank(<64 x s16>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<64 x s8>), %2:ptrregbank(p0) :: (store (<64 x s8>))
    PseudoRET implicit $lr
...

---
name:            VST_PACK_1024_I4_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: VST_PACK_dmx_sts_pack_idx_imm_packSign0 [[COPY]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vregbank(<128 x s8>) = COPY $y0
    %2:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %0:vregbank(<128 x s8>), %6:gprregbank(s32)
    G_STORE %5:vregbank(<64 x s8>), %2:ptrregbank(p0) :: (store (<64 x s8>))
    PseudoRET implicit $lr
...
