# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            Read_TM
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: Read_TM
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDA_TM_idx_imm:%[0-9]+]]:er = LDA_TM_idx_imm %2:ep, 0 :: (volatile load (s32) from custom "TileMemory")
    ; CHECK-NEXT: $r0 = COPY [[LDA_TM_idx_imm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:ptrregbank(p0) = COPY $p0
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.read.tm), %5:ptrregbank(p0)
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...


---
name:            Write_TM
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: Write_TM
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_TM_idx_imm %1:er, %2:ep, 0 :: (store (s32) into custom "TileMemory")
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:ptrregbank(p0) = COPY $p0
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.write.tm), %0:gprregbank(s32), %5:ptrregbank(p0)
    PseudoRET implicit $lr
...
