# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s --check-prefix=AIE2P


---
name:            test_concat_128_4x32
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0
    ; AIE2P-LABEL: name: test_concat_128_4x32
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[DEF1:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 48
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:ers16 = MOV_RLC_imm11_pseudo 15
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY [[DEF]]
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY]], %subreg.sub_256_lo
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[DEF1]]
    ; AIE2P-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY1]], %subreg.sub_256_lo
    ; AIE2P-NEXT: [[DEF2:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VSHIFT:%[0-9]+]]:vec512 = VSHIFT [[DEF2]], [[REG_SEQUENCE1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: [[VSEL_32_:%[0-9]+]]:vec512 = VSEL_32 [[VSHIFT]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo1]]
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[VSEL_32_]].sub_256_lo
    ; AIE2P-NEXT: $wl0 = COPY [[COPY2]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<4 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<4 x s32>) = G_IMPLICIT_DEF
    %7:vregbank(<8 x s32>) = G_CONCAT_VECTORS %1:vregbank(<4 x s32>), %2:vregbank(<4 x s32>)
    $wl0 = COPY %7:vregbank(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            test_concat_128_16x8
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $x0
    ; AIE2P-LABEL: name: test_concat_128_16x8
    ; AIE2P: liveins: $x0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[DEF1:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 48
    ; AIE2P-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:ers16 = MOV_RLC_imm11_pseudo 15
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY [[DEF]]
    ; AIE2P-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY]], %subreg.sub_256_lo
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[DEF1]]
    ; AIE2P-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY1]], %subreg.sub_256_lo
    ; AIE2P-NEXT: [[DEF2:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; AIE2P-NEXT: [[VSHIFT:%[0-9]+]]:vec512 = VSHIFT [[DEF2]], [[REG_SEQUENCE1]], [[MOV_RLC_imm11_pseudo]]
    ; AIE2P-NEXT: [[VSEL_32_:%[0-9]+]]:vec512 = VSEL_32 [[VSHIFT]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo1]]
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[VSEL_32_]].sub_256_lo
    ; AIE2P-NEXT: $wl0 = COPY [[COPY2]]
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<8 x s16>) = G_IMPLICIT_DEF
    %2:vregbank(<8 x s16>) = G_IMPLICIT_DEF
    %7:vregbank(<16 x s16>) = G_CONCAT_VECTORS %1:vregbank(<8 x s16>), %2:vregbank(<8 x s16>)
    $wl0 = COPY %7:vregbank(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

