# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VEXTBCST_32_bf_mRm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_32_bf_mRm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VEXTBCST_32_vec_extract_broadcast_r]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vextract.broadcast32.bf512), %1:vregbank(<32 x s16>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VEXTBCST_32_bf_mExtractIdxImm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_32_bf_mExtractIdxImm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: $x0 = COPY [[VEXTBCST_32_vec_extract_broadcast_imm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vextract.broadcast32.bf512), %1:vregbank(<32 x s16>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...
---
name:            VEXTBCST_128_vec_extract_broadcast_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_128_vec_extract_broadcast_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_128_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_128_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VEXTBCST_128_vec_extract_broadcast_r]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %0:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vextract.broadcast128.I512), %1:vregbank(<16 x s32>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name:            VEXTBCST_128_vec_extract_broadcast_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_128_vec_extract_broadcast_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_128_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_128_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: $x0 = COPY [[VEXTBCST_128_vec_extract_broadcast_imm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vextract.broadcast128.I512), %1:vregbank(<16 x s32>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name:            VEXTBCST_32_extract_subvec_broadcast_64xs8_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_32_extract_subvec_broadcast_64xs8_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_imm]]
    %1:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %4:gprregbank(<4 x s8>) = G_AIE_EXTRACT_SUBVECTOR %1(<64 x s8>), %3(s32)
    %5:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %4(<4 x s8>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_32_extract_subvec_broadcast_32xs16_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_32_extract_subvec_broadcast_32xs16_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_imm]]
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %4:gprregbank(<2 x s16>) = G_AIE_EXTRACT_SUBVECTOR %1(<32 x s16>), %3(s32)
    %5:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %4(<2 x s16>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_64xs8_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_64xs8_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_imm]]
    %1:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %4:gprregbank(<8 x s8>) = G_AIE_EXTRACT_SUBVECTOR %1(<64 x s8>), %3(s32)
    %5:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %4(<8 x s8>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_32xs16_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_32xs16_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_imm]]
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %4:gprregbank(<4 x s16>) = G_AIE_EXTRACT_SUBVECTOR %1(<32 x s16>), %3(s32)
    %5:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %4(<4 x s16>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_16xs32_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_16xs32_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_imm]]
    %1:vregbank(<16 x s32>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %4:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %1(<16 x s32>), %3(s32)
    %5:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %4(<2 x s32>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_8xs64_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_8xs64_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_imm]]
    %1:vregbank(<8 x s64>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %4:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %1(<8 x s64>), %3(s32)
    %5:vregbank(<8 x s64>) = G_AIE_BROADCAST_VECTOR %4(<2 x s32>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_32_extract_subvec_broadcast_64xs8_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_32_extract_subvec_broadcast_64xs8_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_r]]
    %1:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(<4 x s8>) = G_AIE_EXTRACT_SUBVECTOR %1(<64 x s8>), %3(s32)
    %5:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %4(<4 x s8>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_32_extract_subvec_broadcast_32xs16_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_32_extract_subvec_broadcast_32xs16_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_r]]
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(<2 x s16>) = G_AIE_EXTRACT_SUBVECTOR %1(<32 x s16>), %3(s32)
    %5:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %4(<2 x s16>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_64xs8_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_64xs8_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_r]]
    %1:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(<8 x s8>) = G_AIE_EXTRACT_SUBVECTOR %1(<64 x s8>), %3(s32)
    %5:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %4(<8 x s8>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_32xs16_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_32xs16_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_r]]
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(<4 x s16>) = G_AIE_EXTRACT_SUBVECTOR %1(<32 x s16>), %3(s32)
    %5:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %4(<4 x s16>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_16xs32_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_16xs32_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_r]]
    %1:vregbank(<16 x s32>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %1(<16 x s32>), %3(s32)
    %5:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %4(<2 x s32>)
    PseudoRET implicit $lr, implicit %5
...
---
name:            VEXTBCST_64_extract_subvec_broadcast_8xs64_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_64_extract_subvec_broadcast_8xs64_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_64_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_64_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_64_vec_extract_broadcast_r]]
    %1:vregbank(<8 x s64>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %1(<8 x s64>), %3(s32)
    %5:vregbank(<8 x s64>) = G_AIE_BROADCAST_VECTOR %4(<2 x s32>)
    PseudoRET implicit $lr, implicit %5
...

---
name:              VEXTBCST_8_extract_i32_imm
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEXTBCST_8_extract_i32_imm
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<64 x s8>))
    ; CHECK-NEXT: [[VEXTBCST_8_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_8_vec_extract_broadcast_imm [[VLD_x_idx_imm_pseudo]], 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_8_vec_extract_broadcast_imm]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<64 x s8>) = G_LOAD %ptr(p0) :: (load (<64 x s8>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<64 x s8>), %3(s32)
    %7:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<64 x s8>)
...

---
name:              VEXTBCST_8_extract_i32_ZEXT_imm
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEXTBCST_8_extract_i32_ZEXT_imm
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<64 x s8>))
    ; CHECK-NEXT: [[VEXTBCST_8_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_8_vec_extract_broadcast_imm [[VLD_x_idx_imm_pseudo]], 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_8_vec_extract_broadcast_imm]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<64 x s8>) = G_LOAD %ptr(p0) :: (load (<64 x s8>))
    %5:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %4(<64 x s8>), %3(s32)
    %7:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<64 x s8>)
...


---
name:              VEXTBCST_8_extract_i32_r
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r4
    ; CHECK-LABEL: name: VEXTBCST_8_extract_i32_r
    ; CHECK: liveins: $p0, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r4
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<64 x s8>))
    ; CHECK-NEXT: [[VEXTBCST_8_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_8_vec_extract_broadcast_r [[VLD_x_idx_imm_pseudo]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_8_vec_extract_broadcast_r]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = COPY $r4
    %4:vregbank(<64 x s8>) = G_LOAD %ptr(p0) :: (load (<64 x s8>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<64 x s8>), %3(s32)
    %7:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<64 x s8>)
...

---
name:              VEXTBCST_8_extract_i32_ZEXT_r
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r4
    ; CHECK-LABEL: name: VEXTBCST_8_extract_i32_ZEXT_r
    ; CHECK: liveins: $p0, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r4
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<64 x s8>))
    ; CHECK-NEXT: [[VEXTBCST_8_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_8_vec_extract_broadcast_r [[VLD_x_idx_imm_pseudo]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_8_vec_extract_broadcast_r]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = COPY $r4
    %4:vregbank(<64 x s8>) = G_LOAD %ptr(p0) :: (load (<64 x s8>))
    %5:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %4(<64 x s8>), %3(s32)
    %7:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<64 x s8>)
...

---
name:              VEXTBCST_16_extract_i32_imm
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEXTBCST_16_extract_i32_imm
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: [[VEXTBCST_16_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_16_vec_extract_broadcast_imm [[VLD_x_idx_imm_pseudo]], 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_16_vec_extract_broadcast_imm]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_LOAD %ptr(p0) :: (load (<32 x s16>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<32 x s16>)
...

---
name:              VEXTBCST_16_extract_i32_ZEXT_imm
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEXTBCST_16_extract_i32_ZEXT_imm
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: [[VEXTBCST_16_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_16_vec_extract_broadcast_imm [[VLD_x_idx_imm_pseudo]], 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_16_vec_extract_broadcast_imm]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_LOAD %ptr(p0) :: (load (<32 x s16>))
    %5:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<32 x s16>)
...

---
name:              VEXTBCST_16_extract_i32_r
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r2
    ; CHECK-LABEL: name: VEXTBCST_16_extract_i32_r
    ; CHECK: liveins: $p0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: [[VEXTBCST_16_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_16_vec_extract_broadcast_r [[VLD_x_idx_imm_pseudo]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_16_vec_extract_broadcast_r]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = COPY $r2
    %4:vregbank(<32 x s16>) = G_LOAD %ptr(p0) :: (load (<32 x s16>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<32 x s16>)
...

---
name:              VEXTBCST_16_extract_i32_ZEXT_r
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r2
    ; CHECK-LABEL: name: VEXTBCST_16_extract_i32_ZEXT_r
    ; CHECK: liveins: $p0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: [[VEXTBCST_16_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_16_vec_extract_broadcast_r [[VLD_x_idx_imm_pseudo]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_16_vec_extract_broadcast_r]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = COPY $r2
    %4:vregbank(<32 x s16>) = G_LOAD %ptr(p0) :: (load (<32 x s16>))
    %5:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %5(s32)
    PseudoRET implicit $lr, implicit %7(<32 x s16>)
...

---
name:              VEXTBCST_32_extract_i32_imm
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEXTBCST_32_extract_i32_imm
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_imm [[VLD_x_idx_imm_pseudo]], 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_imm]]
    %ptr:ptrregbank(p0) = COPY $p0
    %4:vregbank(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %483:gprregbank(s32) = G_CONSTANT i32 0
    %484:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %483(s32)
    %485:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %484(s32)
    PseudoRET implicit $lr, implicit %485(<16 x s32>)
...

---
name:              VEXTBCST_32_extract_i32_ZEXT_imm
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VEXTBCST_32_extract_i32_ZEXT_imm
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_imm [[VLD_x_idx_imm_pseudo]], 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_imm]]
    %ptr:ptrregbank(p0) = COPY $p0
    %4:vregbank(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %483:gprregbank(s32) = G_CONSTANT i32 0
    %484:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %483(s32)
    %485:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %484(s32)
    PseudoRET implicit $lr, implicit %485(<16 x s32>)
...

---
name:              VEXTBCST_32_extract_i32_r
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r6
    ; CHECK-LABEL: name: VEXTBCST_32_extract_i32_r
    ; CHECK: liveins: $p0, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_r [[VLD_x_idx_imm_pseudo]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_r]]
    %ptr:ptrregbank(p0) = COPY $p0
    %4:vregbank(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %483:gprregbank(s32) = COPY $r6
    %484:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %483(s32)
    %485:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %484(s32)
    PseudoRET implicit $lr, implicit %485(<16 x s32>)
...

---
name:              VEXTBCST_32_extract_i32_ZEXT_r
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r6
    ; CHECK-LABEL: name: VEXTBCST_32_extract_i32_ZEXT_r
    ; CHECK: liveins: $p0, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[VEXTBCST_32_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_32_vec_extract_broadcast_r [[VLD_x_idx_imm_pseudo]], [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCST_32_vec_extract_broadcast_r]]
    %ptr:ptrregbank(p0) = COPY $p0
    %4:vregbank(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %483:gprregbank(s32) = COPY $r6
    %484:gprregbank(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %483(s32)
    %485:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %484(s32)
    PseudoRET implicit $lr, implicit %485(<16 x s32>)
...
