# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie-preisel-combiner,instruction-select -verify-machineinstrs %s -o - | FileCheck %s

...

---
name:              vextbcstshfl_16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<32 x s16>))
    ; CHECK-NEXT: [[VEXTBCSTSHFL_16_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_16 [[VLD_x_idx_imm_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_16_]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_LOAD %ptr(p0) :: (load (<32 x s16>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %5(s32)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %8(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

# Unlike the tests above where the second vshuffle operand is a direct
# G_IMPLICIT_DEF, the following tests use a COPY of G_IMPLICIT_DEF through
# fiforegbank. This cross-bank copy is the pattern produced by the legalizer
# and prevents ISel from recognizing the operand as undef.
#
# 16-bit variant with cross-bank COPY of G_IMPLICIT_DEF.
---
name:              vextbcstshfl_16_copy_undef
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x2, $r0
    ; CHECK-LABEL: name: vextbcstshfl_16_copy_undef
    ; CHECK: liveins: $x2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VEXTBCSTSHFL_16_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_16 [[COPY]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_16_]]
    %0:vregbank(<32 x s16>) = COPY $x2
    %1:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<16 x s32>) = COPY %1(<16 x s32>)
    %3:gprregbank(s32) = G_CONSTANT i32 28
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<32 x s16>), %4(s32)
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %5(s32)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %8(<16 x s32>), %2(<16 x s32>), %3(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

---
name:              vextbcstshfl_32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo %ptr, 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCSTSHFL_32_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_32 [[VLD_x_idx_imm_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_32_]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_LOAD %ptr(p0) :: (load (<16 x s32>))
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %3(s32)
    %6:gprregbank(<2 x s16>) = G_BITCAST %5(s32)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast32.bf512), %6(<2 x s16>)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %8(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

# 32-bit variant with cross-bank COPY of G_IMPLICIT_DEF.
---
name:              vextbcstshfl_32_copy_undef
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x2, $r0
    ; CHECK-LABEL: name: vextbcstshfl_32_copy_undef
    ; CHECK: liveins: $x2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VEXTBCSTSHFL_32_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_32 [[COPY]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_32_]]
    %0:vregbank(<16 x s32>) = COPY $x2
    %1:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<16 x s32>) = COPY %1(<16 x s32>)
    %3:gprregbank(s32) = G_CONSTANT i32 28
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %0(<16 x s32>), %4(s32)
    %6:gprregbank(<2 x s16>) = G_BITCAST %5(s32)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast32.bf512), %6(<2 x s16>)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %8(<16 x s32>), %2(<16 x s32>), %3(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...


---
name:              vextbcstshfl_64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCSTSHFL_64_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_64 [[VLD_x_idx_imm_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_64_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_LOAD %0(p0) :: (load (<16 x s32>))
    %5:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %4(<16 x s32>), %3(s32)
    %6:gprregbank(<4 x s16>) = G_BITCAST %5(<2 x s32>)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast64.bf512), %6(<4 x s16>)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %8(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

# 64-bit variant with cross-bank COPY of G_IMPLICIT_DEF.
---
name:              vextbcstshfl_64_copy_undef
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x2, $r0
    ; CHECK-LABEL: name: vextbcstshfl_64_copy_undef
    ; CHECK: liveins: $x2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VEXTBCSTSHFL_64_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_64 [[COPY]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_64_]]
    %0:vregbank(<16 x s32>) = COPY $x2
    %1:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<16 x s32>) = COPY %1(<16 x s32>)
    %3:gprregbank(s32) = G_CONSTANT i32 28
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %5:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %0(<16 x s32>), %4(s32)
    %6:gprregbank(<4 x s16>) = G_BITCAST %5(<2 x s32>)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast64.bf512), %6(<4 x s16>)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %8(<16 x s32>), %2(<16 x s32>), %3(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

---
name:              vextbcstshfl_128
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_128
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCSTSHFL_128_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_128 [[VLD_x_idx_imm_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_128_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_LOAD %0(p0) :: (load (<16 x s32>))
    %5:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vextract.broadcast128.I512), %4(<16 x s32>), %3(s32)
    %6:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %5(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %6(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

# 128-bit variant with cross-bank COPY of G_IMPLICIT_DEF.
---
name:              vextbcstshfl_128_copy_undef
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_128_copy_undef
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY]], 0 :: (load (<16 x s32>))
    ; CHECK-NEXT: [[VEXTBCSTSHFL_128_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_128 [[VLD_x_idx_imm_pseudo]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_128_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:vregbank(<16 x s32>) = COPY %1(<16 x s32>)
    %3:gprregbank(s32) = G_CONSTANT i32 28
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s32>) = G_LOAD %0(p0) :: (load (<16 x s32>))
    %6:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vextract.broadcast128.I512), %5(<16 x s32>), %4(s32)
    %7:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %6(<16 x s32>), %2(<16 x s32>), %3(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %7(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...
