# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test__sqrtf
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: test__sqrtf
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[SQRT_mRx:%[0-9]+]]:er = SQRT_mRx [[COPY]], implicit-def dead $srfpnlf, implicit $crfpnlfmask
    ; CHECK-NEXT: $r0 = COPY [[SQRT_mRx]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = COPY $r1
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.sqrtf), %1(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_invf
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: test_invf
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[INV_mRx:%[0-9]+]]:er = INV_mRx [[COPY]], implicit-def dead $srfpnlf, implicit $crfpnlfmask
    ; CHECK-NEXT: $r0 = COPY [[INV_mRx]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = COPY $r1
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.inv), %1(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_invsqrtf
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: test_invsqrtf
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[INVSQRT_mRx:%[0-9]+]]:er = INVSQRT_mRx [[COPY]], implicit-def dead $srfpnlf, implicit $crfpnlfmask
    ; CHECK-NEXT: $r0 = COPY [[INVSQRT_mRx]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = COPY $r1
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.invsqrt), %1(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
