# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDA_UPS_2x_acc32_v16_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_:%[0-9]+]]:acc512, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc64_v8_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v8_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_:%[0-9]+]]:acc512, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc64_v16_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v16_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc32_v32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v32_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc32_v32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v32_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc64_v16_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v16_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc64_v32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v32_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc32_v64_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_signed
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc32_v16_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:acc512, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc64_v8_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v8_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:acc512, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc64_v16_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v16_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc32_v32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v32_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc32_v32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v32_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc64_v16_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v16_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc64_v32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v32_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc32_v64_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_unsigned
    ; CHECK: liveins: $p0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc32_v16_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:acc512, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc64_v8_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v8_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:acc512, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc64_v16_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v16_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc32_v32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v32_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s16>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s16>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc32_v32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v32_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_2x_acc64_v16_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v16_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc64_v32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v32_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

---
name:            VLDA_UPS_4x_acc32_v64_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_dynamic
    ; CHECK: liveins: $p0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 [[COPY3]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %25:vregbank(<16 x s32>), %5:ptrregbank(p0), %6:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...
