# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name:            lsrs_sign_unsigned_VEC256_ACC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0

    ; CHECK-LABEL: name: lsrs_sign_unsigned_VEC256_ACC512_acc32
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            lsrs_sign_signed_VEC256_ACC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0

    ; CHECK-LABEL: name: lsrs_sign_signed_VEC256_ACC512_acc32
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign1_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            lsrs_sign_dynamic_VEC256_ACC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $r1

    ; CHECK-LABEL: name: lsrs_sign_dynamic_VEC256_ACC512_acc32
    ; CHECK: liveins: $bmll0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            lsrs_sign_unsigned_VEC256_ACC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0

    ; CHECK-LABEL: name: lsrs_sign_unsigned_VEC256_ACC512_acc64
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %1(<8 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            lsrs_sign_signed_VEC256_ACC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0

    ; CHECK-LABEL: name: lsrs_sign_signed_VEC256_ACC512_acc64
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign1_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %1(<8 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            lsrs_sign_dynamic_VEC256_ACC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $r1

    ; CHECK-LABEL: name: lsrs_sign_dynamic_VEC256_ACC512_acc64
    ; CHECK: liveins: $bmll0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %1(<8 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            ssrs_sign_unsigned_VEC256_ACC1024_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: ssrs_sign_unsigned_VEC256_ACC1024_acc32
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign0_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            ssrs_sign_signed_VEC256_ACC1024_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: ssrs_sign_signed_VEC256_ACC1024_acc32
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign1_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            ssrs_sign_dynamic_VEC256_ACC1024_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1

    ; CHECK-LABEL: name: ssrs_sign_dynamic_VEC256_ACC1024_acc32
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign0_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            ssrs_sign_unsigned_VEC256_ACC1024_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: ssrs_sign_unsigned_VEC256_ACC1024_acc64
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign0_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            ssrs_sign_signed_VEC256_ACC1024_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: ssrs_sign_signed_VEC256_ACC1024_acc64
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign1_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            ssrs_sign_dynamic_VEC256_ACC1024_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1

    ; CHECK-LABEL: name: ssrs_sign_dynamic_VEC256_ACC1024_acc64
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign0_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            lsrs_acc32_vec512_acc1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: lsrs_acc32_vec512_acc1024
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 63
    ; CHECK-NEXT: [[AND:%[0-9]+]]:er = AND [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[AND]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign1_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %3:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 1
    %6:gprregbank(s32) = G_CONSTANT i32 63
    %4:gprregbank(s32) = G_AND %3, %6
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %1(<32 x s32>), %4(s32), %5(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            lsrs_sign_unsigned_VEC512_ACC1024_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: lsrs_sign_unsigned_VEC512_ACC1024_acc32
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            lsrs_sign_signed_VEC512_ACC1024_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: lsrs_sign_signed_VEC512_ACC1024_acc32
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign1_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            lsrs_sign_dynamic_VEC512_ACC1024_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1

    ; CHECK-LABEL: name: lsrs_sign_dynamic_VEC512_ACC1024_acc32
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            lsrs_sign_unsigned_VEC512_ACC1024_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: lsrs_sign_unsigned_VEC512_ACC1024_acc64
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            lsrs_sign_signed_VEC512_ACC1024_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0

    ; CHECK-LABEL: name: lsrs_sign_signed_VEC512_ACC1024_acc64
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign1_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            lsrs_sign_dynamic_VEC512_ACC1024_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1

    ; CHECK-LABEL: name: lsrs_sign_dynamic_VEC512_ACC1024_acc64
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            ssrs_sign_unsigned_VEC512_ACC2048_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r0

    ; CHECK-LABEL: name: ssrs_sign_unsigned_VEC512_ACC2048_acc32
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_x_srs_dm_srsSign0_:%[0-9]+]]:vec512 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_4x_mv_x_srs_dm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<64 x s32>) = COPY $dm0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %1(<64 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            ssrs_sign_signed_VEC512_ACC2048_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r0

    ; CHECK-LABEL: name: ssrs_sign_signed_VEC512_ACC2048_acc32
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_x_srs_dm_srsSign1_:%[0-9]+]]:vec512 = VSRS_4x_mv_x_srs_dm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $x0 = COPY [[VSRS_4x_mv_x_srs_dm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<64 x s32>) = COPY $dm0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %1(<64 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            ssrs_sign_dynamic_VEC512_ACC2048_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r0, $r1

    ; CHECK-LABEL: name: ssrs_sign_dynamic_VEC512_ACC2048_acc32
    ; CHECK: liveins: $dm0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_x_srs_dm_srsSign0_:%[0-9]+]]:vec512 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_4x_mv_x_srs_dm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<64 x s32>) = COPY $dm0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %1(<64 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            ssrs_sign_unsigned_VEC512_ACC2048_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r0

    ; CHECK-LABEL: name: ssrs_sign_unsigned_VEC512_ACC2048_acc64
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_x_srs_dm_srsSign0_:%[0-9]+]]:vec512 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_4x_mv_x_srs_dm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s64>) = COPY $dm0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %1(<32 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            ssrs_sign_signed_VEC512_ACC2048_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r0

    ; CHECK-LABEL: name: ssrs_sign_signed_VEC512_ACC2048_acc64
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_x_srs_dm_srsSign1_:%[0-9]+]]:vec512 = VSRS_4x_mv_x_srs_dm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $x0 = COPY [[VSRS_4x_mv_x_srs_dm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s64>) = COPY $dm0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %1(<32 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            ssrs_sign_dynamic_VEC512_ACC2048_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: ssrs_sign_dynamic_VEC512_ACC2048_acc64
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:acc2048 = IMPLICIT_DEF
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY]]
    ; CHECK-NEXT: [[VSRS_4x_mv_x_srs_dm_srsSign0_:%[0-9]+]]:vec512 = VSRS_4x_mv_x_srs_dm_srsSign0 [[DEF]], [[COPY2]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_4x_mv_x_srs_dm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = COPY $r1
    %3:accregbank(<32 x s64>) = G_IMPLICIT_DEF
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %3(<32 x s64>), %1(s32), %2(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            test_to_v16bfloat16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; CHECK-LABEL: name: test_to_v16bfloat16
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_w_srs_bf:%[0-9]+]]:vec256 = VCONV_bf16_fp32_mv_w_srs_bf [[COPY]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: $wl0 = COPY [[VCONV_bf16_fp32_mv_w_srs_bf]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v16accfloat.to.v16bf16), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
...
---
name:            test_to_v32bfloat16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0

    ; CHECK-LABEL: name: test_to_v32bfloat16
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_x_srs_bf:%[0-9]+]]:vec512 = VCONV_bf16_fp32_mv_x_srs_bf [[COPY]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: $x0 = COPY [[VCONV_bf16_fp32_mv_x_srs_bf]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v32accfloat.to.v32bf16), %1(<32 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
