# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_SRS_2x_v16_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v8_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v8_acc64_signed
    ; CHECK: liveins: $bmll0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v32_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc32_signed
    ; CHECK: liveins: $cml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v16_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v16_acc64_signed
    ; CHECK: liveins: $cml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v32_acc32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $cml0
    ; CHECK-LABEL: name: VST_SRS_2x_v32_acc32_signed
    ; CHECK: liveins: $p0, $m0, $r1, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_2x_v16_acc64_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $cml0
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc64_signed
    ; CHECK: liveins: $p0, $m0, $r1, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_4x_v64_acc32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $dm0
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_signed
    ; CHECK: liveins: $p0, $m0, $r1, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<32 x s64>) = COPY $dm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_4x_v32_acc64_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $dm0
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc64_signed
    ; CHECK: liveins: $p0, $m0, $r1, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign1 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign1 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign1 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<32 x s64>) = COPY $dm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_2x_v16_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v8_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v8_acc64_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v32_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc32_unsigned
    ; CHECK: liveins: $cml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v16_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v16_acc64_unsigned
    ; CHECK: liveins: $cml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v32_acc32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $cml0
    ; CHECK-LABEL: name: VST_SRS_2x_v32_acc32_unsigned
    ; CHECK: liveins: $p0, $m0, $r1, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_2x_v16_acc64_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $cml0
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc64_unsigned
    ; CHECK: liveins: $p0, $m0, $r1, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_4x_v64_acc32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $dm0
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_unsigned
    ; CHECK: liveins: $p0, $m0, $r1, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<32 x s64>) = COPY $dm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_4x_v32_acc64_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $dm0
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc64_unsigned
    ; CHECK: liveins: $p0, $m0, $r1, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY4]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<32 x s64>) = COPY $dm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_2x_v16_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v8_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v8_acc64_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v32_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc32_dynamic
    ; CHECK: liveins: $cml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v16_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v16_acc64_dynamic
    ; CHECK: liveins: $cml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -256, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 224, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v32_acc32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $cml0
    ; CHECK-LABEL: name: VST_SRS_2x_v32_acc32_dynamic
    ; CHECK: liveins: $p0, $m0, $r1, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_2x_v16_acc64_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $cml0
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc64_dynamic
    ; CHECK: liveins: $p0, $m0, $r1, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_4x_v64_acc32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $dm0
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_dynamic
    ; CHECK: liveins: $p0, $m0, $r1, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<32 x s64>) = COPY $dm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_4x_v32_acc64_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $dm0
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc64_dynamic
    ; CHECK: liveins: $p0, $m0, $r1, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY5]], [[COPY]], [[COPY1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY6]], [[COPY]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY7]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY8]], [[COPY]], -512, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY2]], [[COPY9]], [[COPY]], 448, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_srsSign0 [[COPY2]], [[COPY10]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>) into stack - 64)
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:accregbank(<32 x s64>) = COPY $dm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %100:accregbank(<32 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...
