# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name: v4s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v4s32
    ; CHECK: [[DEF:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<4 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<4 x s32>)
...

---
name: v8s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v8s16
    ; CHECK: [[DEF:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<8 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<8 x s16>)
...

---
name: v16s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v16s8
    ; CHECK: [[DEF:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<16 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<16 x s8>)
...

---
name: acc256
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: acc256
    ; CHECK: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]]
    %0:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<4 x s64>)
...

---
name: acc2048
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: acc2048
    ; CHECK: [[DEF:%[0-9]+]]:acc2048 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:acc2048 = IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]], implicit [[DEF1]]
    %0:accregbank(<32 x s64>) = G_IMPLICIT_DEF
    %1:accregbank(<64 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0(<32 x s64>), implicit %1(<64 x s32>)
...
