# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            _Z8test_addDv64_u7__acc32S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2

    ; CHECK-LABEL: name: _Z8test_addDv64_u7__acc32S_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %3:accregbank(<32 x s64>) = G_BITCAST %1(<64 x s32>)
    %4:accregbank(<32 x s64>) = G_BITCAST %2(<64 x s32>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %3(<32 x s64>), %4(<32 x s64>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_addDv64_u10__accfloatS_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2

    ; CHECK-LABEL: name: _Z8test_addDv64_u10__accfloatS_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADD_f_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_f_vmac_cm2_add_reg [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADD_f_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %1(<64 x s32>), %2(<64 x s32>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_u6__bf16S_Dv64_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3

    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_u6__bf16S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:acc2048 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_Y_Y [[COPY2]], [[DEF]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:accregbank(<64 x s32>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %5(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_8x8_8x8Dv128_hS_Dv64_u7__acc32S0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3

    ; CHECK-LABEL: name: _Z19test_addmac_8x8_8x8Dv128_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_vmac_cm2_add_reg_vmul_cm_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.addmac.conf), %5(<32 x s32>), %6(<64 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_u6__bf16S_Dv64_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3

    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_u6__bf16S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_64Dv64_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3

    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_u6__bf16S_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_8x8_8x8Dv128_hS_Dv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3

    ; CHECK-LABEL: name: _Z16test_mac_8x8_8x8Dv128_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 8
    %4:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %6:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.mac.conf), %4(<32 x s32>), %5(<64 x s16>), %6(<32 x s64>), %8(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %7(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_8x8_8x8Dv128_hS_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3

    ; CHECK-LABEL: name: _Z16test_mul_8x8_8x8Dv128_hS_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMUL_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMUL_vmul_cm_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %6:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.mul.conf), %3(<32 x s32>), %4(<64 x s16>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_8x8_8x8Dv128_hDv64_hDv64_u7__acc32S1_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2

    ; CHECK-LABEL: name: _Z19test_addmac_8x8_8x8Dv128_hDv64_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VADDMAC_vmac_cm2_add_reg_vmul_cm_core_Y_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.addmac.conf), %5(<32 x s32>), %6(<32 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_8x8_8x8Dv128_hDv64_hDv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $y2

    ; CHECK-LABEL: name: _Z16test_mac_8x8_8x8Dv128_hDv64_hDv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_Y_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 8
    %4:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %5:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %6:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.mac.conf), %4(<32 x s32>), %5(<32 x s16>), %6(<32 x s64>), %8(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %7(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_8x8_8x8Dv128_hDv64_h
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2

    ; CHECK-LABEL: name: _Z16test_mul_8x8_8x8Dv128_hDv64_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMUL_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VMUL_vmul_cm_core_Y_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %6:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.mul.conf), %3(<32 x s32>), %4(<32 x s16>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_8x8_8x8Dv64_hDv128_hDv64_u7__acc32S1_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2

    ; CHECK-LABEL: name: _Z19test_addmac_8x8_8x8Dv64_hDv128_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.addmac.conf), %5(<16 x s32>), %6(<64 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_8x8_8x8Dv64_hDv128_hDv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $y2

    ; CHECK-LABEL: name: _Z16test_mac_8x8_8x8Dv64_hDv128_hDv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 8
    %4:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %6:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.mac.conf), %4(<16 x s32>), %5(<64 x s16>), %6(<32 x s64>), %8(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %7(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_8x8_8x8Dv64_hDv128_h
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2

    ; CHECK-LABEL: name: _Z16test_mul_8x8_8x8Dv64_hDv128_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMUL_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMUL_vmul_cm_core_X_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %6:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.mul.conf), %3(<16 x s32>), %4(<64 x s16>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_addmac_elem_16_2Dv32_tS_Dv16_u7__acc64S0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2

    ; CHECK-LABEL: name: _Z21test_addmac_elem_16_2Dv32_tS_Dv16_u7__acc64S0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 90
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY3]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_X:%[0-9]+]]:edm = VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_X [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<16 x s64>) = COPY $cml1
    %4:accregbank(<16 x s64>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 90
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC1024.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s64>), %4(<16 x s64>), %5(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_u6__bf16S_Dv32_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_u6__bf16S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMAC_f_vmac_bf_vmul_bf_core_X_X [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY [[VMAC_f_vmac_bf_vmul_bf_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_u6__bf16S_Dv32_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_u6__bf16S_Dv32_u10__accfloatS0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY3]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X:%[0-9]+]]:edm = VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_32Dv32_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_u6__bf16S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY [[VMUL_f_vmul_bf_vmul_bf_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmac_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vmac_cm2_add_reg_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.addmac.conf), %5(<16 x s32>), %6(<32 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv32_u6__bf16S_Dv64_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv32_u6__bf16S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv32_u6__bf16S_Dv64_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv32_u6__bf16S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_64Dv32_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv32_u6__bf16S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_8x8_8x8Dv64_hS_Dv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mac_8x8_8x8Dv64_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMAC_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VMAC_vmul_cm_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 8
    %4:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %6:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), %4(<16 x s32>), %5(<32 x s16>), %6(<32 x s64>), %8(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %7(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_16Dv32_u6__bf16S_Dv16_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll1, $bmll2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmac_elem_16Dv32_u6__bf16S_Dv16_u10__accfloatS0_
    ; CHECK: liveins: $bmll1, $bmll2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ebmll = COPY $bmll1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ebmll = COPY $bmll2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY3]], %subreg.sub_512_acc_lo
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_512_acc_lo
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X:%[0-9]+]]:edm = VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ebmll = COPY [[VADDMAC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<16 x s32>) = COPY $bmll1
    %4:accregbank(<16 x s32>) = COPY $bmll2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s32>), %4(<16 x s32>), %5(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z16test_mac_elem_16Dv32_u6__bf16S_Dv16_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mac_elem_16Dv32_u6__bf16S_Dv16_u10__accfloat
    ; CHECK: liveins: $bmll1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ebmll = COPY $bmll1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_512_acc_lo
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMAC_f_vmac_bf_vmul_bf_core_X_X [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ebmll = COPY [[VMAC_f_vmac_bf_vmul_bf_core_X_X]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<16 x s32>) = COPY $bmll1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s32>), %4(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z16test_mul_elem_16Dv32_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mul_elem_16Dv32_u6__bf16S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ebmll = COPY [[VMUL_f_vmul_bf_vmul_bf_core_X_X]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z16test_mul_elem_16Dv32_u6__bf16iS_i
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_mul_elem_16Dv32_u6__bf16iS_i
    ; CHECK: liveins: $r0, $r1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 9
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[LSHL:%[0-9]+]]:er = LSHL [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[LSHL1:%[0-9]+]]:er = LSHL [[COPY3]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: [[OR:%[0-9]+]]:er = OR [[LSHL]], [[LSHL1]]
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:er = OR [[OR]], [[MOV_RLC_imm11_pseudo2]]
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY2]], [[OR1]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ebmll = COPY [[VMUL_f_vmul_bf_vmul_bf_core_X_X]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:vregbank(<32 x s16>) = COPY $x2
    %4:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = G_CONSTANT i32 9
    %7:gprregbank(s32) = G_CONSTANT i32 8
    %10:gprregbank(s32) = G_CONSTANT i32 60
    %6:gprregbank(s32) = G_SHL %2, %5(s32)
    %8:gprregbank(s32) = G_SHL %4, %7(s32)
    %9:gprregbank(s32) = G_OR %6, %8
    %11:gprregbank(s32) = G_OR %9, %10
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.mul.conf), %1(<32 x s16>), %3(<32 x s16>), %11(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z8test_negDv64_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1

    ; CHECK-LABEL: name: _Z8test_negDv64_u10__accfloat
    ; CHECK: liveins: $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEG_f:%[0-9]+]]:acc2048 = VNEG_f [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEG_f]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.neg.conf), %1(<64 x s32>), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_subDv64_u7__acc32S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2

    ; CHECK-LABEL: name: _Z8test_subDv64_u7__acc32S_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VSUB_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VSUB_vmac_cm2_add_reg [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VSUB_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %3:accregbank(<32 x s64>) = G_BITCAST %1(<64 x s32>)
    %4:accregbank(<32 x s64>) = G_BITCAST %2(<64 x s32>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.sub.conf), %3(<32 x s64>), %4(<32 x s64>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_negDv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1

    ; CHECK-LABEL: name: _Z8test_negDv64_u7__acc32
    ; CHECK: liveins: $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VNEG:%[0-9]+]]:acc2048 = VNEG [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:accregbank(<32 x s64>) = G_BITCAST %1(<64 x s32>)
    %3:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.neg.conf), %2(<32 x s64>), %4(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %3(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_subDv64_u10__accfloatS_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2

    ; CHECK-LABEL: name: _Z8test_subDv64_u10__accfloatS_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VSUB_f_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VSUB_f_vmac_cm2_add_reg [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VSUB_f_vmac_cm2_add_reg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.sub.conf), %1(<64 x s32>), %2(<64 x s32>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_8x8_8x8Dv128_hS_Dv64_u7__acc32S0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3

    ; CHECK-LABEL: name: _Z19test_addmsc_8x8_8x8Dv128_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_vmac_cm2_add_reg_vmul_cm_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.addmsc.conf), %5(<32 x s32>), %6(<64 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_u6__bf16S_Dv64_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3

    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_u6__bf16S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_u6__bf16S_Dv64_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3

    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_u6__bf16S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3

    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_u6__bf16S_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_8x8_8x8Dv128_hS_Dv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3

    ; CHECK-LABEL: name: _Z16test_msc_8x8_8x8Dv128_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_vmul_cm_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 8
    %4:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %6:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.msc.conf), %4(<32 x s32>), %5(<64 x s16>), %6(<32 x s64>), %8(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %7(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_8x8_8x8Dv128_hS_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3

    ; CHECK-LABEL: name: _Z19test_negmul_8x8_8x8Dv128_hS_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VNEGMUL_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VNEGMUL_vmul_cm_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %6:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.negmul.conf), %3(<32 x s32>), %4(<64 x s16>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_8x8_8x8Dv128_hDv64_hDv64_u7__acc32S1_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2

    ; CHECK-LABEL: name: _Z19test_addmsc_8x8_8x8Dv128_hDv64_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VADDMSC_vmac_cm2_add_reg_vmul_cm_core_Y_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.addmsc.conf), %5(<32 x s32>), %6(<32 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_8x8_8x8Dv128_hDv64_h
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2

    ; CHECK-LABEL: name: _Z19test_negmul_8x8_8x8Dv128_hDv64_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VNEGMUL_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VNEGMUL_vmul_cm_core_Y_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %6:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.negmul.conf), %3(<32 x s32>), %4(<32 x s16>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_8x8_8x8Dv64_hDv128_hDv64_u7__acc32S1_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2

    ; CHECK-LABEL: name: _Z19test_addmsc_8x8_8x8Dv64_hDv128_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.addmsc.conf), %5(<16 x s32>), %6(<64 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_8x8_8x8Dv64_hDv128_hDv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $y2

    ; CHECK-LABEL: name: _Z16test_msc_8x8_8x8Dv64_hDv128_hDv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMSC_vmul_cm_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 8
    %4:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %6:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.msc.conf), %4(<16 x s32>), %5(<64 x s16>), %6(<32 x s64>), %8(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %7(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_8x8_8x8Dv64_hDv128_h
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2

    ; CHECK-LABEL: name: _Z19test_negmul_8x8_8x8Dv64_hDv128_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VNEGMUL_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VNEGMUL_vmul_cm_core_X_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %6:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I1024.ACC2048.negmul.conf), %3(<16 x s32>), %4(<64 x s16>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_addmsc_elem_16_2Dv32_tS_Dv16_u7__acc64S0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2

    ; CHECK-LABEL: name: _Z21test_addmsc_elem_16_2Dv32_tS_Dv16_u7__acc64S0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 90
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY3]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_X:%[0-9]+]]:edm = VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_X [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<16 x s64>) = COPY $cml1
    %4:accregbank(<16 x s64>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 90
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC1024.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s64>), %4(<16 x s64>), %5(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_u6__bf16S_Dv32_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_u6__bf16S_Dv32_u10__accfloatS0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY3]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X:%[0-9]+]]:edm = VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_u6__bf16S_Dv32_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_u6__bf16S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMSC_f_vmac_bf_vmul_bf_core_X_X [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY [[VMSC_f_vmac_bf_vmul_bf_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_u6__bf16S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VNEGMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z18test_msc_elem_16_2Dv32_tS_Dv16_u7__acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2

    ; CHECK-LABEL: name: _Z18test_msc_elem_16_2Dv32_tS_Dv16_u7__acc64
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 90
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_1024_acc_lo
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_X_X:%[0-9]+]]:edm = VMSC_vmul_cm_core_X_X [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY [[VMSC_vmul_cm_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<16 x s64>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 90
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC1024.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s64>), %4(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z21test_negmul_elem_16_2Dv32_tS_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z21test_negmul_elem_16_2Dv32_tS_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 90
    ; CHECK-NEXT: [[VNEGMUL_vmul_cm_core_X_X:%[0-9]+]]:edm = VNEGMUL_vmul_cm_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY [[VNEGMUL_vmul_cm_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: $cml0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 90
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC1024.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmsc_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vmac_cm2_add_reg_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 8
    %5:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %7:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:accregbank(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.addmsc.conf), %5(<16 x s32>), %6(<32 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv32_u6__bf16S_Dv64_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv32_u6__bf16S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv32_u6__bf16S_Dv64_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv32_u6__bf16S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv32_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv32_u6__bf16S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_8x8_8x8Dv64_hS_Dv64_u7__acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_msc_8x8_8x8Dv64_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VMSC_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VMSC_vmul_cm_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 8
    %4:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %6:accregbank(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.msc.conf), %4(<16 x s32>), %5(<32 x s16>), %6(<32 x s64>), %8(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %7(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_8x8_8x8Dv64_hS_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z19test_negmul_8x8_8x8Dv64_hS_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: [[VNEGMUL_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VNEGMUL_vmul_cm_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %6:gprregbank(s32) = G_CONSTANT i32 8
    %3:vregbank(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %4:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.negmul.conf), %3(<16 x s32>), %4(<32 x s16>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_16Dv32_u6__bf16S_Dv16_u10__accfloatS0_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll1, $bmll2, $x0, $x2

    ; CHECK-LABEL: name: _Z19test_addmsc_elem_16Dv32_u6__bf16S_Dv16_u10__accfloatS0_
    ; CHECK: liveins: $bmll1, $bmll2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ebmll = COPY $bmll1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ebmll = COPY $bmll2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY3]], %subreg.sub_512_acc_lo
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_512_acc_lo
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X:%[0-9]+]]:edm = VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ebmll = COPY [[VADDMSC_f_vaddmac_bf_vmac_cm2_add_reg_vmul_bf_core_X_X]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<16 x s32>) = COPY $bmll1
    %4:accregbank(<16 x s32>) = COPY $bmll2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s32>), %4(<16 x s32>), %5(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z16test_msc_elem_16Dv32_u6__bf16S_Dv16_u10__accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll1, $x0, $x2

    ; CHECK-LABEL: name: _Z16test_msc_elem_16Dv32_u6__bf16S_Dv16_u10__accfloat
    ; CHECK: liveins: $bmll1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ebmll = COPY $bmll1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY2]], %subreg.sub_512_acc_lo
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMSC_f_vmac_bf_vmul_bf_core_X_X [[REG_SEQUENCE]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ebmll = COPY [[VMSC_f_vmac_bf_vmul_bf_core_X_X]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<16 x s32>) = COPY $bmll1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s32>), %4(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z19test_negmul_elem_16Dv32_u6__bf16S_
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: _Z19test_negmul_elem_16Dv32_u6__bf16S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VNEGMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ebmll = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
