# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_PACK_512_I8_I16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_signed
    ; CHECK: liveins: $p0, $m0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_1]], -256, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_1]], 224, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:vregbank(<64 x s8>) = COPY $x0
    %101:vregbank(<32 x s16>) = G_BITCAST %100:vregbank(<64 x s8>)
    %200:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %105:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %106:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %107:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %108:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<32 x s8>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<32 x s8>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<32 x s8>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<32 x s8>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<32 x s8>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<32 x s8>))
...

---
name:            VST_PACK_512_I4_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_signed
    ; CHECK: liveins: $p0, $m0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_1]], -256, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_1]], 224, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign1_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:vregbank(<64 x s8>) = COPY $x0
    %200:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %104:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %105:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %106:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %107:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %108:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<64 x s4>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<64 x s4>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<64 x s4>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<64 x s4>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<64 x s4>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<64 x s4>))
...

---
name:            VST_PACK_1024_I8_I16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_signed
    ; CHECK: liveins: $p0, $m0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_1]], -512, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_1]], 448, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:vregbank(<64 x s16>) = COPY $y0
    %200:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %104:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %105:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %106:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %107:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %108:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<64 x s8>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<64 x s8>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<64 x s8>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<64 x s8>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<64 x s8>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<64 x s8>))
...

---
name:            VST_PACK_1024_I4_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_signed
    ; CHECK: liveins: $p0, $m0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_1]], -512, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_1]], 448, implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign1_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign1 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign1_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<128 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:vregbank(<128 x s8>) = COPY $y0
    %200:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %104:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %105:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %106:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %107:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %108:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<128 x s4>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<128 x s4>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<128 x s4>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<128 x s4>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<128 x s4>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<128 x s4>))
...

---
name:            VST_PACK_512_I8_I16_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_unsigned
    ; CHECK: liveins: $p0, $m0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1]], -256, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1]], 224, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:vregbank(<64 x s8>) = COPY $x0
    %101:vregbank(<32 x s16>) = G_BITCAST %100:vregbank(<64 x s8>)
    %200:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %105:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %106:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %107:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %108:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<32 x s8>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<32 x s8>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<32 x s8>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<32 x s8>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<32 x s8>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<32 x s8>))
...

---
name:            VST_PACK_512_I4_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_unsigned
    ; CHECK: liveins: $p0, $m0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1]], -256, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1]], 224, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:vregbank(<64 x s8>) = COPY $x0
    %200:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %104:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %105:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %106:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %107:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %108:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<64 x s4>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<64 x s4>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<64 x s4>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<64 x s4>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<64 x s4>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<64 x s4>))
...

---
name:            VST_PACK_1024_I8_I16_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_unsigned
    ; CHECK: liveins: $p0, $m0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1]], -512, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1]], 448, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:vregbank(<64 x s16>) = COPY $y0
    %200:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %104:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %105:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %106:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %107:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %108:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<64 x s8>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<64 x s8>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<64 x s8>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<64 x s8>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<64 x s8>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<64 x s8>))
...

---
name:            VST_PACK_1024_I4_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_unsigned
    ; CHECK: liveins: $p0, $m0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1]], -512, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1]], 448, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:vregbank(<128 x s8>) = COPY $y0
    %200:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %104:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %105:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %106:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %107:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %108:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<128 x s4>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<128 x s4>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<128 x s4>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<128 x s4>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<128 x s4>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<128 x s4>))
...


---
name:            VST_PACK_512_I8_I16_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $x0, $r0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_dynamic
    ; CHECK: liveins: $p0, $m0, $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1]], -256, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1]], 224, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:vregbank(<64 x s8>) = COPY $x0
    %101:vregbank(<32 x s16>) = G_BITCAST %100:vregbank(<64 x s8>)
    %200:gprregbank(s32) = COPY $r0
    %103:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %105:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %106:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %107:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %108:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %101:vregbank(<32 x s16>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<32 x s8>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<32 x s8>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<32 x s8>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<32 x s8>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<32 x s8>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<32 x s8>))
...

---
name:            VST_PACK_512_I4_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $x0, $r0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_dynamic
    ; CHECK: liveins: $p0, $m0, $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_1]], -256, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_1]], 224, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmw_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmw_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmw_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:vregbank(<64 x s8>) = COPY $x0
    %200:gprregbank(s32) = COPY $r0
    %103:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %104:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %105:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %106:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %107:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %108:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<64 x s4>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<64 x s4>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<64 x s4>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<64 x s4>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<64 x s4>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<64 x s4>))
...

---
name:            VST_PACK_1024_I8_I16_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $y0, $r0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_dynamic
    ; CHECK: liveins: $p0, $m0, $y0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1]], -512, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1]], 448, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:vregbank(<64 x s16>) = COPY $y0
    %200:gprregbank(s32) = COPY $r0
    %103:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %104:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %105:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %106:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %107:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %108:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<64 x s8>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<64 x s8>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<64 x s8>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<64 x s8>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<64 x s8>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<64 x s8>))
...

---
name:            VST_PACK_1024_I4_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0, $y0, $r0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_dynamic
    ; CHECK: liveins: $p0, $m0, $y0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[COPY]], [[COPY1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_]], [[MOV_PD_imm11_pseudo]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_1]], -512, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_1]], 448, implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VST_PACK_dmx_sts_pack_pstm_nrm_packSign0_2:%[0-9]+]]:ep = VST_PACK_dmx_sts_pack_pstm_nrm_packSign0 [[COPY2]], [[VST_PACK_dmx_sts_pack_pstm_nrm_imm_packSign0_2]], [[MOV_PD_imm11_pseudo1]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %100:vregbank(<128 x s8>) = COPY $y0
    %200:gprregbank(s32) = COPY $r0
    %103:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %104:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %105:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %106:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %107:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %108:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %200:gprregbank(s32)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<128 x s4>))
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %19, %8 :: (store (<128 x s4>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %20, %9 :: (store (<128 x s4>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %21, %10 :: (store (<128 x s4>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<128 x s4>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %23, %12 :: (store (<128 x s4>))
...
