# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDB_UNPACK_I512_I8_I4_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_signed
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_1]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_3]], -256, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_3]], 224, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_4]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %26:vregbank(<32 x s8>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s8>))
    %27:vregbank(<32 x s8>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s8>))
    %28:vregbank(<32 x s8>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s8>))
    %29:vregbank(<32 x s8>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s8>))
    %30:vregbank(<32 x s8>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s8>))
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %26:vregbank(<32 x s8>), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %27:vregbank(<32 x s8>), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %28:vregbank(<32 x s8>), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %29:vregbank(<32 x s8>), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %30:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I16_I8_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_signed
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_1]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_3]], -256, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_3]], 224, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_4]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %26:vregbank(<32 x s8>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s8>))
    %27:vregbank(<32 x s8>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s8>))
    %28:vregbank(<32 x s8>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s8>))
    %29:vregbank(<32 x s8>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s8>))
    %30:vregbank(<32 x s8>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s8>))
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %26:vregbank(<32 x s8>), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %27:vregbank(<32 x s8>), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %28:vregbank(<32 x s8>), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %29:vregbank(<32 x s8>), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %30:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I8_I4_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_signed
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_1]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_3]], -512, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_3]], 448, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_4]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %25:vregbank(<32 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s16>))
    %26:vregbank(<32 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s16>))
    %27:vregbank(<32 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s16>))
    %28:vregbank(<32 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s16>))
    %29:vregbank(<32 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s16>))
    %30:vregbank(<32 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s16>))
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    %104:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %26:vregbank(<32 x s16>), %102:gprregbank(s32)
    %105:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %27:vregbank(<32 x s16>), %102:gprregbank(s32)
    %106:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %28:vregbank(<32 x s16>), %102:gprregbank(s32)
    %107:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %29:vregbank(<32 x s16>), %102:gprregbank(s32)
    %108:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %30:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I16_I8_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_signed
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_1]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_3]], -512, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_3]], 448, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_4]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %25:vregbank(<32 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s16>))
    %26:vregbank(<32 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s16>))
    %27:vregbank(<32 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s16>))
    %28:vregbank(<32 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s16>))
    %29:vregbank(<32 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s16>))
    %30:vregbank(<32 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s16>))
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    %104:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %26:vregbank(<32 x s16>), %102:gprregbank(s32)
    %105:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %27:vregbank(<32 x s16>), %102:gprregbank(s32)
    %106:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %28:vregbank(<32 x s16>), %102:gprregbank(s32)
    %107:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %29:vregbank(<32 x s16>), %102:gprregbank(s32)
    %108:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %30:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I8_I4_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_unsigned
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %26:vregbank(<32 x s8>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s8>))
    %27:vregbank(<32 x s8>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s8>))
    %28:vregbank(<32 x s8>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s8>))
    %29:vregbank(<32 x s8>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s8>))
    %30:vregbank(<32 x s8>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s8>))
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %26:vregbank(<32 x s8>), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %27:vregbank(<32 x s8>), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %28:vregbank(<32 x s8>), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %29:vregbank(<32 x s8>), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %30:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I16_I8_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_unsigned
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %26:vregbank(<32 x s8>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s8>))
    %27:vregbank(<32 x s8>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s8>))
    %28:vregbank(<32 x s8>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s8>))
    %29:vregbank(<32 x s8>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s8>))
    %30:vregbank(<32 x s8>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s8>))
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %26:vregbank(<32 x s8>), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %27:vregbank(<32 x s8>), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %28:vregbank(<32 x s8>), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %29:vregbank(<32 x s8>), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %30:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I8_I4_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_unsigned
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %25:vregbank(<32 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s16>))
    %26:vregbank(<32 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s16>))
    %27:vregbank(<32 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s16>))
    %28:vregbank(<32 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s16>))
    %29:vregbank(<32 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s16>))
    %30:vregbank(<32 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s16>))
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    %104:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %26:vregbank(<32 x s16>), %102:gprregbank(s32)
    %105:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %27:vregbank(<32 x s16>), %102:gprregbank(s32)
    %106:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %28:vregbank(<32 x s16>), %102:gprregbank(s32)
    %107:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %29:vregbank(<32 x s16>), %102:gprregbank(s32)
    %108:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %30:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I16_I8_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_unsigned
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %25:vregbank(<32 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s16>))
    %26:vregbank(<32 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s16>))
    %27:vregbank(<32 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s16>))
    %28:vregbank(<32 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s16>))
    %29:vregbank(<32 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s16>))
    %30:vregbank(<32 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s16>))
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    %104:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %26:vregbank(<32 x s16>), %102:gprregbank(s32)
    %105:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %27:vregbank(<32 x s16>), %102:gprregbank(s32)
    %106:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %28:vregbank(<32 x s16>), %102:gprregbank(s32)
    %107:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %29:vregbank(<32 x s16>), %102:gprregbank(s32)
    %108:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %30:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I8_I4_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %26:vregbank(<32 x s8>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s8>))
    %27:vregbank(<32 x s8>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s8>))
    %28:vregbank(<32 x s8>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s8>))
    %29:vregbank(<32 x s8>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s8>))
    %30:vregbank(<32 x s8>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s8>))
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %26:vregbank(<32 x s8>), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %27:vregbank(<32 x s8>), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %28:vregbank(<32 x s8>), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %29:vregbank(<32 x s8>), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %30:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I16_I8_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_3]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %26:vregbank(<32 x s8>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s8>))
    %27:vregbank(<32 x s8>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s8>))
    %28:vregbank(<32 x s8>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s8>))
    %29:vregbank(<32 x s8>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s8>))
    %30:vregbank(<32 x s8>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s8>))
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %26:vregbank(<32 x s8>), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %27:vregbank(<32 x s8>), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %28:vregbank(<32 x s8>), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %29:vregbank(<32 x s8>), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %30:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I8_I4_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %25:vregbank(<32 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s16>))
    %26:vregbank(<32 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s16>))
    %27:vregbank(<32 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s16>))
    %28:vregbank(<32 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s16>))
    %29:vregbank(<32 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s16>))
    %30:vregbank(<32 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s16>))
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    %104:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %26:vregbank(<32 x s16>), %102:gprregbank(s32)
    %105:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %27:vregbank(<32 x s16>), %102:gprregbank(s32)
    %106:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %28:vregbank(<32 x s16>), %102:gprregbank(s32)
    %107:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %29:vregbank(<32 x s16>), %102:gprregbank(s32)
    %108:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %30:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I16_I8_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_1]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_1]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_3]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_3]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_5:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0 [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign0_4]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_unpackSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %25:vregbank(<32 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s16>))
    %26:vregbank(<32 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<32 x s16>))
    %27:vregbank(<32 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<32 x s16>))
    %28:vregbank(<32 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<32 x s16>))
    %29:vregbank(<32 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<32 x s16>))
    %30:vregbank(<32 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<32 x s16>))
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<32 x s16>), %102:gprregbank(s32)
    %104:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %26:vregbank(<32 x s16>), %102:gprregbank(s32)
    %105:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %27:vregbank(<32 x s16>), %102:gprregbank(s32)
    %106:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %28:vregbank(<32 x s16>), %102:gprregbank(s32)
    %107:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %29:vregbank(<32 x s16>), %102:gprregbank(s32)
    %108:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %30:vregbank(<32 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

# We can combine with a store in between.
---
name:            VLDB_POSTINC_UNPACK_STORE_between
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $m1, $m2, $r0, $wl0, $p1
    ; CHECK-LABEL: name: VLDB_POSTINC_UNPACK_STORE_between
    ; CHECK: liveins: $p0, $m0, $m1, $m2, $r0, $wl0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[COPY]], [[COPY3]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: VST_dmw_sts_w_idx_imm [[COPY4]], [[COPY1]], 0 :: (store (<32 x s8>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %20:ptrregbank(p0) = COPY $p1
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %80:vregbank(<32 x s8>) = COPY $wl0
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    G_STORE %80:vregbank(<32 x s8>), %20:ptrregbank(p0) :: (store (<32 x s8>))
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...

# We combine if we use the resulting pointer (not the loaded data).
---
name:            VLD_UNPACK_use_ptr
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLD_UNPACK_use_ptr
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $m1 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ep = COPY $m1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_unpackSign1_]], implicit [[COPY3]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    $m1 = COPY %19:ptrregbank(p0)
    %12:ptrregbank(p0) = COPY $m1
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %12
...
