# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            v16s32_trunc_v16s64_acc1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v16s32_trunc_v16s64_acc1024
    ; CHECK: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v16s32AccBnk_trunc_v16s64_acc1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v16s32AccBnk_trunc_v16s64_acc1024
    ; CHECK: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_bm:%[0-9]+]]:mbmsm = VSHUFFLE_vec_shuffle_bm [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_bm]]
    %1:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    %0:accregbank(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v32s16_trunc_v32s32_acc1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v32s16_trunc_v32s32_acc1024
    ; CHECK: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec1024 = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exe = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY3]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<32 x s16>) = G_TRUNC %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v8s32_trunc_v8s64_acc512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v8s32_trunc_v8s64_acc512
    ; CHECK: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mxm = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mxn = COPY [[DEF]]
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY2]]
    %1:accregbank(<8 x s64>) = G_IMPLICIT_DEF
    %0:vregbank(<8 x s32>) = G_TRUNC %1(<8 x s64>)
    PseudoRET implicit $lr, implicit %0

...
---
name:            v16s16_trunc_v16s32_acc512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v16s16_trunc_v16s32_acc512
    ; CHECK: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mxm = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mxn = COPY [[DEF]]
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY2]]
    %1:accregbank(<16 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s16>) = G_TRUNC %1(<16 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v16s32_trunc_v16s64_vec1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v16s32_trunc_v16s64_vec1024
    ; CHECK: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:vregbank(<16 x s64>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v32s16_trunc_v32s32_vec1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v32s16_trunc_v32s32_vec1024
    ; CHECK: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<32 x s16>) = G_TRUNC %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v64s8_trunc_v64s16_vec1024
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v64s8_trunc_v64s16_vec1024
    ; CHECK: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:exo = COPY [[DEF]].sub_512_hi
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[DEF]].sub_512_lo
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:vec512 = VSHUFFLE_vec_shuffle_x [[COPY1]], [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VSHUFFLE_vec_shuffle_x]]
    %1:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    %0:vregbank(<64 x s8>) = G_TRUNC %1(<64 x s16>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v16s16_trunc_v16s32_vec512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v16s16_trunc_v16s32_vec512
    ; CHECK: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %0:vregbank(<16 x s16>) = G_TRUNC %1(<16 x s32>)
    PseudoRET implicit $lr, implicit %0
...
---
name:            v32s8_trunc_v32s16_vec512
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v32s8_trunc_v32s16_vec512
    ; CHECK: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_x:%[0-9]+]]:mshflxdst = VSHUFFLE_vec_shuffle_x [[DEF]], [[DEF]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ewl = COPY [[VSHUFFLE_vec_shuffle_x]].sub_256_lo
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %1:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    %0:vregbank(<32 x s8>) = G_TRUNC %1(<32 x s16>)
    PseudoRET implicit $lr, implicit %0
...

