# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: select_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7, $r8
    ; CHECK-LABEL: name: select_s32
    ; CHECK: liveins: $r6, $r7, $r8
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r8
    ; CHECK-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY1]], [[COPY2]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[SEL_NEZ]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = COPY $r8
    %3:gprregbank(s32) = G_SELECT %0, %1, %2
    $r0 = COPY %3
...

---
name: select_p0
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1, $r6
    ; CHECK-LABEL: name: select_p0
    ; CHECK: liveins: $p0, $p1, $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mr27_select = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY [[COPY2]]
    ; CHECK-NEXT: [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[COPY3]], [[COPY4]], [[COPY]]
    ; CHECK-NEXT: $p0 = COPY [[SEL_NEZ]]
    %0:gprregbank(s32) = COPY $r6
    %1:ptrregbank(p0) = COPY $p0
    %2:ptrregbank(p0) = COPY $p1
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(p0) = COPY %2
    %5:gprregbank(p0) = G_SELECT %0, %3, %4
    $p0 = COPY %5
...

