# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VINSERT_32_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x2
    ; CHECK-LABEL: name: VINSERT_32_bf
    ; CHECK: liveins: $r0, $r1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[VINSERT_32_mR29_insert:%[0-9]+]]:vec512 = VINSERT_32_mR29_insert [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_32_mR29_insert]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(<2 x s16>) = COPY $r1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vinsert32.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<2 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VINSERT_64_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0, $r0, $x2
    ; CHECK-LABEL: name: VINSERT_64_bf
    ; CHECK: liveins: $l0, $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VINSERT_64_mR29_insert:%[0-9]+]]:vec512 = VINSERT_64_mR29_insert [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_64_mR29_insert]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(<4 x s16>) = COPY $l0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.vinsert64.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<4 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VINSERT_accfloat
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll1, $r0
    ; CHECK-LABEL: name: VINSERT_accfloat
    ; CHECK: liveins: $bmll1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]]
    ; CHECK-NEXT: [[VINSERT_32_mR29_insert:%[0-9]+]]:mxm = VINSERT_32_mR29_insert [[COPY2]], [[MOV_RLC_imm11_pseudo]], [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY [[VINSERT_32_mR29_insert]]
    ; CHECK-NEXT: $bmll0 = COPY [[COPY3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:accregbank(<8 x s64>) = COPY $bmll1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.vinsert32.accfloat), %1:accregbank(<8 x s64>), %3:gprregbank(s32), %2:gprregbank(s32)
    $bmll0 = COPY %0:accregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $bmll0
...
