# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VNEG_GTZ8
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x2
    ; CHECK-LABEL: name: VNEG_GTZ8
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VNEG_GTZ_8_:%[0-9]+]]:vec512, [[VNEG_GTZ_8_1:%[0-9]+]]:ml8m = VNEG_GTZ_8 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VNEG_GTZ_8_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s8>) = COPY $x2
    %2:vregbank(<64 x s8>), %3:gprregbank(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vneg.gtz8), %1:vregbank(<64 x s8>)
    $x0 = COPY %2:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VNEG_GTZ16
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x2
    ; CHECK-LABEL: name: VNEG_GTZ16
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VNEG_GTZ_16_:%[0-9]+]]:vec512, [[VNEG_GTZ_16_1:%[0-9]+]]:mr16_vcompare = VNEG_GTZ_16 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VNEG_GTZ_16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:vregbank(<32 x s16>), %3:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vneg.gtz16), %1:vregbank(<32 x s16>)
    $x0 = COPY %2:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VNEG_GTZ32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x2
    ; CHECK-LABEL: name: VNEG_GTZ32
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VNEG_GTZ_32_:%[0-9]+]]:vec512, [[VNEG_GTZ_32_1:%[0-9]+]]:mr16_vcompare = VNEG_GTZ_32 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VNEG_GTZ_32_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %2:vregbank(<16 x s32>), %3:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vneg.gtz32), %1:vregbank(<16 x s32>)
    $x0 = COPY %2:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
