# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

...
---
name:            test_fix2float
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: test_fix2float
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ms2 = COPY [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[MOV_alu_mv_alu_fx2flt:%[0-9]+]]:er = MOV_alu_mv_alu_fx2flt [[COPY]], [[COPY1]], implicit-def dead $srfpcnvfx2fl, implicit $crfpcnvfx2flmask
    ; CHECK-NEXT: $r0 = COPY [[MOV_alu_mv_alu_fx2flt]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.fx2flt), %1(s32), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_float2fix
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: test_float2fix
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ms3 = COPY [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[MOV_alu_mv_alu_flt2fx:%[0-9]+]]:er = MOV_alu_mv_alu_flt2fx [[COPY]], [[COPY1]], implicit-def dead $srfpcnvfl2fx, implicit $crfpcnvfl2fxmask
    ; CHECK-NEXT: $r0 = COPY [[MOV_alu_mv_alu_flt2fx]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.flt2fx), %1(s32), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
