# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -start-before=instruction-select -stop-after=machine-cse %s -o - | FileCheck %s


---
name:            test_fmul_1024
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y1
    ; CHECK-LABEL: name: test_fmul_1024
    ; CHECK: liveins: $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:edm = VMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecmh = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y]].sub_1024_acc_hi
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_x_srs_bf:%[0-9]+]]:exo = VCONV_bf16_fp32_mv_x_srs_bf [[COPY2]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y]].sub_1024_acc_lo
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_x_srs_bf1:%[0-9]+]]:exe = VCONV_bf16_fp32_mv_x_srs_bf [[COPY3]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VCONV_bf16_fp32_mv_x_srs_bf1]], %subreg.sub_512_lo, [[VCONV_bf16_fp32_mv_x_srs_bf]], %subreg.sub_512_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %0:vregbank(<64 x s16>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y1
    %2:vregbank(<64 x s16>) = G_FMUL %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_fmul_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_fmul_512
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:edm = VMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY [[VMUL_f_vmul_bf_vmul_bf_core_X_X]].sub_1024_acc_lo
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_x_srs_bf:%[0-9]+]]:vec512 = VCONV_bf16_fp32_mv_x_srs_bf [[COPY2]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VCONV_bf16_fp32_mv_x_srs_bf]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x1
    %2:vregbank(<32 x s16>) = G_FMUL %0, %1
    PseudoRET implicit $lr, implicit %2
...
