# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_mul_8x8_8x8T
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e0, $e1, $x0, $x1

    ; CHECK-LABEL: name: test_mul_8x8_8x8T
    ; CHECK: liveins: $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexw = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VMUL_f_vmul_bfp_vmul_bfp_core_EX_EX:%[0-9]+]]:acc2048 = VMUL_f_vmul_bfp_vmul_bfp_core_EX_EX [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bfp_vmul_bfp_core_EX_EX]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x1
    %4:gprregbank(<8 x s8>) = COPY $e1
    %6:gprregbank(s32) = G_CONSTANT i32 780
    %5:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %6(s32)
    $dm0 = COPY %5(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_negmul_8x8_8x8T
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e0, $e1, $x0, $x1

    ; CHECK-LABEL: name: test_negmul_8x8_8x8T
    ; CHECK: liveins: $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexw = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bfp_vmul_bfp_core_EX_EX:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bfp_vmul_bfp_core_EX_EX [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bfp_vmul_bfp_core_EX_EX]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x1
    %4:gprregbank(<8 x s8>) = COPY $e1
    %6:gprregbank(s32) = G_CONSTANT i32 780
    %5:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %6(s32)
    $dm0 = COPY %5(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_mac_8x8_8x8TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true

body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e1, $x0, $x1

    ; CHECK-LABEL: name: test_mac_8x8_8x8TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexw = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX:%[0-9]+]]:acc2048 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX [[COPY4]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x1
    %4:gprregbank(<8 x s8>) = COPY $e1
    %5:accregbank(<64 x s32>) = COPY $dm1
    %7:gprregbank(s32) = G_CONSTANT i32 780
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %7(s32)
    $dm0 = COPY %6(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_msc_8x8_8x8TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e1, $x0, $x1

    ; CHECK-LABEL: name: test_msc_8x8_8x8TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexw = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VMSC_f_vmac_bfp_vmul_bfp_core_EX_EX:%[0-9]+]]:acc2048 = VMSC_f_vmac_bfp_vmul_bfp_core_EX_EX [[COPY4]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bfp_vmul_bfp_core_EX_EX]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x1
    %4:gprregbank(<8 x s8>) = COPY $e1
    %5:accregbank(<64 x s32>) = COPY $dm1
    %7:gprregbank(s32) = G_CONSTANT i32 780
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %7(s32)
    $dm0 = COPY %6(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmac_8x8_8x8TDv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e1, $x0, $x1

    ; CHECK-LABEL: name: test_addmac_8x8_8x8TDv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexw = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EX:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EX [[COPY4]], [[COPY5]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EX]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x1
    %4:gprregbank(<8 x s8>) = COPY $e1
    %5:accregbank(<64 x s32>) = COPY $dm1
    %6:accregbank(<64 x s32>) = COPY $dm2
    %8:gprregbank(s32) = G_CONSTANT i32 780
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %6(<64 x s32>), %8(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmsc_8x8_8x8TDv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e1, $x0, $x1

    ; CHECK-LABEL: name: test_addmsc_8x8_8x8TDv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mexw = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EX:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EX [[COPY4]], [[COPY5]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EX]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x1
    %4:gprregbank(<8 x s8>) = COPY $e1
    %5:accregbank(<64 x s32>) = COPY $dm1
    %6:accregbank(<64 x s32>) = COPY $dm2
    %8:gprregbank(s32) = G_CONSTANT i32 780
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %6(<64 x s32>), %8(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_mul_4x8_8x16T
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e0, $e2, $e3, $x0, $x2, $x3

    ; CHECK-LABEL: name: test_mul_4x8_8x16T
    ; CHECK: liveins: $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:exe = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exo = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eehe = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eeho = COPY $e3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 972
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eey = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY4]], %subreg.sub_bfp16_e, [[COPY3]], %subreg.sub_bfp576_hi_bfp16_x, [[COPY5]], %subreg.sub_bfp576_hi_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VMUL_f_vmul_bfp_vmul_bfp_core_EX_EY:%[0-9]+]]:acc2048 = VMUL_f_vmul_bfp_vmul_bfp_core_EX_EY [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bfp_vmul_bfp_core_EX_EY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x2
    %4:vregbank(<64 x s8>) = COPY $x3
    %5:gprregbank(<8 x s8>) = COPY $e2
    %6:gprregbank(<8 x s8>) = COPY $e3
    %8:gprregbank(s32) = G_CONSTANT i32 972
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %8(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_negmul_4x8_8x16T
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e0, $e2, $e3, $x0, $x2, $x3

    ; CHECK-LABEL: name: test_negmul_4x8_8x16T
    ; CHECK: liveins: $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:exe = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exo = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eehe = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eeho = COPY $e3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 972
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eey = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY4]], %subreg.sub_bfp16_e, [[COPY3]], %subreg.sub_bfp576_hi_bfp16_x, [[COPY5]], %subreg.sub_bfp576_hi_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bfp_vmul_bfp_core_EX_EY:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bfp_vmul_bfp_core_EX_EY [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bfp_vmul_bfp_core_EX_EY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x2
    %4:vregbank(<64 x s8>) = COPY $x3
    %5:gprregbank(<8 x s8>) = COPY $e2
    %6:gprregbank(<8 x s8>) = COPY $e3
    %8:gprregbank(s32) = G_CONSTANT i32 972
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %8(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_mac_4x8_8x16TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3

    ; CHECK-LABEL: name: test_mac_4x8_8x16TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:exe = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exo = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eehe = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eeho = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 972
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eey = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY4]], %subreg.sub_bfp16_e, [[COPY3]], %subreg.sub_bfp576_hi_bfp16_x, [[COPY5]], %subreg.sub_bfp576_hi_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VMAC_f_vmac_bfp_vmul_bfp_core_EX_EY:%[0-9]+]]:acc2048 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EY [[COPY6]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bfp_vmul_bfp_core_EX_EY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x2
    %4:vregbank(<64 x s8>) = COPY $x3
    %5:gprregbank(<8 x s8>) = COPY $e2
    %6:gprregbank(<8 x s8>) = COPY $e3
    %7:accregbank(<64 x s32>) = COPY $dm1
    %9:gprregbank(s32) = G_CONSTANT i32 972
    %8:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %9(s32)
    $dm0 = COPY %8(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_msc_4x8_8x16TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3

    ; CHECK-LABEL: name: test_msc_4x8_8x16TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:exe = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exo = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eehe = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eeho = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 972
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eey = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY4]], %subreg.sub_bfp16_e, [[COPY3]], %subreg.sub_bfp576_hi_bfp16_x, [[COPY5]], %subreg.sub_bfp576_hi_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VMSC_f_vmac_bfp_vmul_bfp_core_EX_EY:%[0-9]+]]:acc2048 = VMSC_f_vmac_bfp_vmul_bfp_core_EX_EY [[COPY6]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bfp_vmul_bfp_core_EX_EY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x2
    %4:vregbank(<64 x s8>) = COPY $x3
    %5:gprregbank(<8 x s8>) = COPY $e2
    %6:gprregbank(<8 x s8>) = COPY $e3
    %7:accregbank(<64 x s32>) = COPY $dm1
    %9:gprregbank(s32) = G_CONSTANT i32 972
    %8:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %9(s32)
    $dm0 = COPY %8(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmac_4x8_8x16TDv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3

    ; CHECK-LABEL: name: test_addmac_4x8_8x16TDv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:exe = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exo = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eehe = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eeho = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 972
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eey = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY4]], %subreg.sub_bfp16_e, [[COPY3]], %subreg.sub_bfp576_hi_bfp16_x, [[COPY5]], %subreg.sub_bfp576_hi_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EY:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EY [[COPY6]], [[COPY7]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x2
    %4:vregbank(<64 x s8>) = COPY $x3
    %5:gprregbank(<8 x s8>) = COPY $e2
    %6:gprregbank(<8 x s8>) = COPY $e3
    %7:accregbank(<64 x s32>) = COPY $dm1
    %8:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 972
    %9:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %8(<64 x s32>), %10(s32)
    $dm0 = COPY %9(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmsc_4x8_8x16TDv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3

    ; CHECK-LABEL: name: test_addmsc_4x8_8x16TDv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:exe = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:exo = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eehe = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:expvec64_with_sub_hi_exp_in_eeho = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 972
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eey = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY4]], %subreg.sub_bfp16_e, [[COPY3]], %subreg.sub_bfp576_hi_bfp16_x, [[COPY5]], %subreg.sub_bfp576_hi_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mexv = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EY:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EY [[COPY6]], [[COPY7]], [[REG_SEQUENCE1]], [[REG_SEQUENCE]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bfp_vmac_cm2_add_reg_vmul_bfp_core_EX_EY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:vregbank(<64 x s8>) = COPY $x2
    %4:vregbank(<64 x s8>) = COPY $x3
    %5:gprregbank(<8 x s8>) = COPY $e2
    %6:gprregbank(<8 x s8>) = COPY $e3
    %7:accregbank(<64 x s32>) = COPY $dm1
    %8:accregbank(<64 x s32>) = COPY $dm2
    %10:gprregbank(s32) = G_CONSTANT i32 972
    %9:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %8(<64 x s32>), %10(s32)
    $dm0 = COPY %9(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
