# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

# The VLDB.UNPACK combine in selectG_AIE_LOAD_UNPACK must only fire when the
# def feeding the unpack is an actual load. Here the unpack consumes the result
# of an SRS narrowing intrinsic (the lowering of acc.to_vector<int8>()), which
# reports mayLoad() but carries no memory operand. Previously the combine path
# called getLoadStoreSize() on it and dereferenced a non-existent memoperand,
# crashing instruction-select. It must instead fall back to the normal VUNPACK
# selection.

---
name:            unpack_of_srs_not_load
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: unpack_of_srs_not_load
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 8
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:es = COPY [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign1_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign1 [[DEF]], [[COPY1]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign1_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign1 [[VSRS_4x_mv_w_srs_cm_srsSign1_]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: VST_dmx_sts_x_idx_imm [[VUNPACK_mv_unpack_w_unpackSign1_]], [[COPY]], 0 :: (store (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 8
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %4:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    %5:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %4(<32 x s8>), %3(s32)
    G_STORE %5(<32 x s16>), %0(p0) :: (store (<32 x s16>))
    PseudoRET implicit $lr
...
