# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_UPS_2x_BM_v16_acc32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v16_acc32_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1 [[COPY8]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1 [[COPY9]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_4]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_BM_v8_acc64_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v8_acc64_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1 [[COPY8]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1 [[COPY9]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_4]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_CM_v16_acc64_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v16_acc64_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1 [[COPY8]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1 [[COPY9]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_4]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_CM_v32_acc32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v32_acc32_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1 [[COPY8]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1 [[COPY9]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign1_4]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_CM_v32_acc32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v32_acc32_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1 [[COPY8]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1 [[COPY9]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_4]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_CM_v16_acc64_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v16_acc64_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1 [[COPY8]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1 [[COPY9]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign1_4]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_DM_v32_acc64_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v32_acc64_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1 [[COPY8]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1 [[COPY9]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_4]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_DM_v64_acc32_signed
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v64_acc32_signed
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1 [[COPY5]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1 [[COPY6]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1 [[COPY7]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1 [[COPY8]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1 [[COPY9]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign1_4]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_BM_v16_acc32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v16_acc32_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_BM_v8_acc64_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v8_acc64_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_CM_v16_acc64_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v16_acc64_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_CM_v32_acc32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v32_acc32_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_CM_v32_acc32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v32_acc32_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_CM_v16_acc64_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v16_acc64_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_DM_v32_acc64_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v32_acc64_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_DM_v64_acc32_unsigned
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v64_acc32_unsigned
    ; CHECK: liveins: $p0, $r0, $r1, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY4]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY5]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_BM_v16_acc32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v16_acc32_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY10]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_BM_v8_acc64_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_BM_v8_acc64_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0 [[COPY10]], [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v8.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_CM_v16_acc64_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v16_acc64_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY10]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_CM_v32_acc32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_CM_v32_acc32_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_3]], 224, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0 [[COPY10]], [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_5]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_imm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_pstm_nrm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %25:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s16>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %26:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s16>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %27:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s16>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %28:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s16>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %29:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s16>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %30:vregbank(<16 x s16>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_CM_v32_acc32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v32_acc32_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY10]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_2x_CM_v16_acc64_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_2x_CM_v16_acc64_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc1024, [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0 [[COPY10]], [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v16.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_DM_v32_acc64_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v32_acc64_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY10]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc64.v32.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VST_UPS_4x_DM_v64_acc32_dynamic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-LABEL: name: VST_UPS_4x_DM_v64_acc32_dynamic
    ; CHECK: liveins: $p0, $r0, $r1, $r2, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 224
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY5]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY6]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_1]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY7]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_1]], [[MOV_PD_imm11_pseudo]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY8]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_3]], -256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0 [[COPY9]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_3]], [[MOV_PD_imm11_pseudo1]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_5:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0 [[COPY10]], [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_5]], 256, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $upssign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_2]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_upsSign0_4]], implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign0_4]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r2
    %25:vregbank(<16 x s32>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>))
    %103:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %25:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>), %20:ptrregbank(p0) = G_AIE_POSTINC_LOAD %19, %8 :: (load (<16 x s32>))
    %104:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %26:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>), %21:ptrregbank(p0) = G_AIE_POSTINC_LOAD %20, %9 :: (load (<16 x s32>))
    %105:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %27:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>), %22:ptrregbank(p0) = G_AIE_POSTINC_LOAD %21, %10 :: (load (<16 x s32>))
    %106:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %28:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>), %23:ptrregbank(p0) = G_AIE_POSTINC_LOAD %22, %11 :: (load (<16 x s32>))
    %107:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %29:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>), %24:ptrregbank(p0) = G_AIE_POSTINC_LOAD %23, %12 :: (load (<16 x s32>))
    %108:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v64.I512.ups), %30:vregbank(<16 x s32>), %101:gprregbank(s32), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...
