# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            copy_512bit_acc
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $bmll0
    ; CHECK-LABEL: name: copy_512bit_acc
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:accregbank(<8 x s64>) = COPY $bmll0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_1024bit_acc
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: copy_1024bit_acc
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:accregbank(<16 x s64>) = COPY $cml0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_2048bit_acc
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: copy_2048bit_acc
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:accregbank(<32 x s64>) = COPY $dm0
    PseudoRET implicit $lr, implicit %0
...
