# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_v32x16_fifo
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $lfl0, $p0
    ; CHECK-LABEL: name: test_v32x16_fifo
    ; CHECK: liveins: $lfl0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fifo512 = COPY $lfl0
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<32 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %1:fiforegbank(<32 x s16>) = COPY $lfl0
    G_STORE %1(<32 x s16>), %0(p0) :: (store (<32 x s16>))
...

---
name:            test_v16x32_fifo
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $lfl0, $p0
    ; CHECK-LABEL: name: test_v16x32_fifo
    ; CHECK: liveins: $lfl0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fifo512 = COPY $lfl0
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY1]], [[COPY]], 0 :: (store (<16 x s32>))
    %0:ptrregbank(p0) = COPY $p0
    %1:fiforegbank(<16 x s32>) = COPY $lfl0
    G_STORE %1(<16 x s32>), %0(p0) :: (store (<16 x s32>))
...

---
name:            test_v16x32_fifo_FI
legalized:       true
regBankSelected: true
stack:
  - { id: 0, name: "", offset: 0, size: 64, alignment: 64 }
body:             |
  bb.1.entry:
    liveins: $lfl0, $p0
    ; CHECK-LABEL: name: test_v16x32_fifo_FI
    ; CHECK: liveins: $lfl0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fifo512 = COPY $lfl0
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill [[COPY]], %stack.0, implicit $sp :: (store (<16 x s32>))
    %0:fiforegbank(<16 x s32>) = COPY $lfl0
    %1:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    G_STORE %0(<16 x s32>), %1(p0) :: (store (<16 x s32>))
...

---
name:            test_v32x32_fifo
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $lf0, $p0
    ; CHECK-LABEL: name: test_v32x32_fifo
    ; CHECK: liveins: $lf0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fifo1024 = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:fifo512 = COPY [[COPY1]].sub_hi_fifo
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:fifo512 = COPY [[COPY1]].sub_lo_fifo
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:fiforegbank(<32 x s32>) = COPY $lf0
    G_STORE %1(<32 x s32>), %0(p0) :: (store (<32 x s32>))
...


---
name:            test_v64x16_fifo
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $lf0, $p0
    ; CHECK-LABEL: name: test_v64x16_fifo
    ; CHECK: liveins: $lf0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fifo1024 = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:fifo512 = COPY [[COPY1]].sub_hi_fifo
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<32 x s16>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:fifo512 = COPY [[COPY1]].sub_lo_fifo
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<32 x s16>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:fiforegbank(<64 x s16>) = COPY $lf0
    G_STORE %1(<64 x s16>), %0(p0) :: (store (<64 x s16>))
...

---
name:            test_v128x8_fifo
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $lf0, $p0
    ; CHECK-LABEL: name: test_v128x8_fifo
    ; CHECK: liveins: $lf0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fifo1024 = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:fifo512 = COPY [[COPY1]].sub_hi_fifo
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY2]], [[COPY]], 64 :: (store (<64 x s8>), align 128)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:fifo512 = COPY [[COPY1]].sub_lo_fifo
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm [[COPY3]], [[COPY]], 0 :: (store (<64 x s8>) into unknown-address + 64)
    %0:ptrregbank(p0) = COPY $p0
    %1:fiforegbank(<128 x s8>) = COPY $lf0
    G_STORE %1(<128 x s8>), %0(p0) :: (store (<128 x s8>))
...
