# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name:            VABS_GTZ8
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x2
    ; CHECK-LABEL: name: VABS_GTZ8
    ; CHECK: liveins: $p0, $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $vaddsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VABS_GTZ_8_vaddSign0_:%[0-9]+]]:vec512, [[VABS_GTZ_8_vaddSign0_1:%[0-9]+]]:ml8m = VABS_GTZ_8_vaddSign0 [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: $vaddsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_8_vaddSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s8>) = COPY $x2
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %3:ptrregbank(p0) = COPY $p0
    %7:vregbank(<64 x s8>), %8:gprregbank(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz8), %1:vregbank(<64 x s8>), %5:gprregbank(s32)
    $x0 = COPY %7:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ8_SIGN0
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VABS_GTZ8_SIGN0
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VABS_GTZ_8_vaddSign0_:%[0-9]+]]:vec512, [[VABS_GTZ_8_vaddSign0_1:%[0-9]+]]:ml8m = VABS_GTZ_8_vaddSign0 [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_8_vaddSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s8>) = COPY $x2
    %2:ptrregbank(p0) = COPY $p0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %3:vregbank(<64 x s8>), %4:gprregbank(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz8), %1:vregbank(<64 x s8>), %5:gprregbank(s32)
    $x0 = COPY %3:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ8_SIGN1
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VABS_GTZ8_SIGN1
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VABS_GTZ_8_vaddSign1_:%[0-9]+]]:vec512, [[VABS_GTZ_8_vaddSign1_1:%[0-9]+]]:ml8m = VABS_GTZ_8_vaddSign1 [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_8_vaddSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s8>) = COPY $x2
    %2:ptrregbank(p0) = COPY $p0
    %5:gprregbank(s32) = G_CONSTANT i32 1
    %3:vregbank(<64 x s8>), %4:gprregbank(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz8), %1:vregbank(<64 x s8>), %5:gprregbank(s32)
    $x0 = COPY %3:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ16
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x2
    ; CHECK-LABEL: name: VABS_GTZ16
    ; CHECK: liveins: $p0, $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $vaddsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VABS_GTZ_16_vaddSign0_:%[0-9]+]]:vec512, [[VABS_GTZ_16_vaddSign0_1:%[0-9]+]]:mr16_vcompare = VABS_GTZ_16_vaddSign0 [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: $vaddsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_16_vaddSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %3:ptrregbank(p0) = COPY $p0
    %7:vregbank(<32 x s16>), %8:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz16), %1:vregbank(<32 x s16>), %5:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ16_SIGN0
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VABS_GTZ16_SIGN0
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VABS_GTZ_16_vaddSign0_:%[0-9]+]]:vec512, [[VABS_GTZ_16_vaddSign0_1:%[0-9]+]]:mr16_vcompare = VABS_GTZ_16_vaddSign0 [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_16_vaddSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:ptrregbank(p0) = COPY $p0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %3:vregbank(<32 x s16>), %4:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz16), %1:vregbank(<32 x s16>), %5:gprregbank(s32)
    $x0 = COPY %3:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ16_SIGN1
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VABS_GTZ16_SIGN1
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VABS_GTZ_16_vaddSign1_:%[0-9]+]]:vec512, [[VABS_GTZ_16_vaddSign1_1:%[0-9]+]]:mr16_vcompare = VABS_GTZ_16_vaddSign1 [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_16_vaddSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:ptrregbank(p0) = COPY $p0
    %5:gprregbank(s32) = G_CONSTANT i32 1
    %3:vregbank(<32 x s16>), %4:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz16), %1:vregbank(<32 x s16>), %5:gprregbank(s32)
    $x0 = COPY %3:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x2
    ; CHECK-LABEL: name: VABS_GTZ32
    ; CHECK: liveins: $p0, $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $vaddsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VABS_GTZ_32_vaddSign0_:%[0-9]+]]:vec512, [[VABS_GTZ_32_vaddSign0_1:%[0-9]+]]:mr16_vcompare = VABS_GTZ_32_vaddSign0 [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: $vaddsign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_32_vaddSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4:gprregbank, 1
    %3:ptrregbank(p0) = COPY $p0
    %7:vregbank(<16 x s32>), %8:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz32), %1:vregbank(<16 x s32>), %5:gprregbank(s32)
    $x0 = COPY %7:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ32_SIGN0
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VABS_GTZ32_SIGN0
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VABS_GTZ_32_vaddSign0_:%[0-9]+]]:vec512, [[VABS_GTZ_32_vaddSign0_1:%[0-9]+]]:mr16_vcompare = VABS_GTZ_32_vaddSign0 [[COPY]], implicit $vaddsign0
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_32_vaddSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %2:ptrregbank(p0) = COPY $p0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %3:vregbank(<16 x s32>), %4:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz32), %1:vregbank(<16 x s32>), %5:gprregbank(s32)
    $x0 = COPY %3:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VABS_GTZ32_SIGN1
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VABS_GTZ32_SIGN1
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VABS_GTZ_32_vaddSign1_:%[0-9]+]]:vec512, [[VABS_GTZ_32_vaddSign1_1:%[0-9]+]]:mr16_vcompare = VABS_GTZ_32_vaddSign1 [[COPY]], implicit $vaddsign1
    ; CHECK-NEXT: $x0 = COPY [[VABS_GTZ_32_vaddSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %2:ptrregbank(p0) = COPY $p0
    %5:gprregbank(s32) = G_CONSTANT i32 1
    %3:vregbank(<16 x s32>), %4:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2p.vabs.gtz32), %1:vregbank(<16 x s32>), %5:gprregbank(s32)
    $x0 = COPY %3:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
