# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_PACK_512_I8_I16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_signed
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign1_:%[0-9]+]]:ep, [[VST_3D_PACK_dmw_sts_pack_packSign1_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmw_sts_pack_packSign1_2:%[0-9]+]]:edch = VST_3D_PACK_dmw_sts_pack_packSign1 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<32 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<32 x s16>) = COPY $x0
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %100:vregbank(<32 x s16>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<32 x s8>))
...

---
name:            VST_PACK_512_I4_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_signed
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign1_:%[0-9]+]]:ep, [[VST_3D_PACK_dmw_sts_pack_packSign1_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmw_sts_pack_packSign1_2:%[0-9]+]]:edch = VST_3D_PACK_dmw_sts_pack_packSign1 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<64 x s8>) = COPY $x0
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %104:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<64 x s4>))
...

---
name:            VST_PACK_1024_I8_I16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_signed
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign1_:%[0-9]+]]:ep, [[VST_3D_PACK_dmx_sts_pack_packSign1_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmx_sts_pack_packSign1_2:%[0-9]+]]:edch = VST_3D_PACK_dmx_sts_pack_packSign1 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<64 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<64 x s16>) = COPY $y0
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %104:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<64 x s8>))
...

---
name:            VST_PACK_1024_I4_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_signed
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign1_:%[0-9]+]]:ep, [[VST_3D_PACK_dmx_sts_pack_packSign1_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmx_sts_pack_packSign1_2:%[0-9]+]]:edch = VST_3D_PACK_dmx_sts_pack_packSign1 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign1 :: (store (<128 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<128 x s8>) = COPY $y0
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %104:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<128 x s4>))
...

---
name:            VST_PACK_512_I8_I16_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_unsigned
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmw_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmw_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmw_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<32 x s16>) = COPY $x0
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %100:vregbank(<32 x s16>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<32 x s8>))
...

---
name:            VST_PACK_512_I4_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_unsigned
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmw_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmw_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmw_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<64 x s8>) = COPY $x0
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %104:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<64 x s4>))
...

---
name:            VST_PACK_1024_I8_I16_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_unsigned
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmx_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmx_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmx_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<64 x s16>) = COPY $y0
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %104:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<64 x s8>))
...

---
name:            VST_PACK_1024_I4_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_unsigned
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmx_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmx_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmx_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<128 x s8>) = COPY $y0
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %104:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<128 x s4>))
...


---
name:            VST_PACK_512_I8_I16_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I8_I16_dynamic
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmw_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmw_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmw_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<32 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<32 x s16>) = COPY $x0
    %102:gprregbank(s32) = COPY $r0
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I8.I16), %100:vregbank(<32 x s16>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<32 x s8>))
...

---
name:            VST_PACK_512_I4_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $x0
    ; CHECK-LABEL: name: VST_PACK_512_I4_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmw_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmw_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmw_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmw_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<64 x s8>) = COPY $x0
    %102:gprregbank(s32) = COPY $r0
    %104:vregbank(<64 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I512.I4.I8), %100:vregbank(<64 x s8>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<64 x s4>))
...

---
name:            VST_PACK_1024_I8_I16_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I8_I16_dynamic
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmx_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmx_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmx_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<64 x s8>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<64 x s16>) = COPY $y0
    %102:gprregbank(s32) = COPY $r0
    %104:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I8.I16), %100:vregbank(<64 x s16>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<64 x s8>))
...

---
name:            VST_PACK_1024_I4_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $y0
    ; CHECK-LABEL: name: VST_PACK_1024_I4_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VST_3D_PACK_dmx_sts_pack_packSign0_:%[0-9]+]]:ep, [[VST_3D_PACK_dmx_sts_pack_packSign0_1:%[0-9]+]]:edcl, [[VST_3D_PACK_dmx_sts_pack_packSign0_2:%[0-9]+]]:edch = VST_3D_PACK_dmx_sts_pack_packSign0 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit $crpacksize, implicit $crsat, implicit $packsign0 :: (store (<128 x s4>))
    ; CHECK-NEXT: $packsign0 = MOV_scalar_imm11_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:vregbank(<128 x s8>) = COPY $y0
    %102:gprregbank(s32) = COPY $r0
    %104:vregbank(<128 x s4>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.pack.I1024.I4.I8), %100:vregbank(<128 x s8>), %102:gprregbank(s32)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %104, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<128 x s4>))
...
