# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name:            test_fifo_st_push
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $x0
    ; CHECK-LABEL: name: test_fifo_st_push
    ; CHECK: liveins: $p0, $p1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_512_:%[0-9]+]]:mstfifo, [[VST_PUSH_512_1:%[0-9]+]]:mpfs, [[VST_PUSH_512_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_512 [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:ptrregbank(p0) = COPY $p1
    %3:modregbank(s20) = G_CONSTANT i20 128
    %5:ptrregbank(p0) = IMPLICIT_DEF
    %6:vregbank(<16 x s32>) = G_BITCAST %1:vregbank(<64 x s8>)
    %7:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %8:gprregbank(s32) = IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.512.bfp16), %5:ptrregbank(p0), %6:vregbank(<16 x s32>), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: test_fifo_st_flush
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_512_normal_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_normal_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_normal_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_512_normal_flush [[DEF1]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:modregbank(s20) = G_CONSTANT i20 128
    %4:ptrregbank(p0) = IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %6:gprregbank(s32) = IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush_1d_byte
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: test_fifo_st_flush_1d_byte
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_512_fifo_1d_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_fifo_1d_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_fifo_1d_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_512_fifo_1d_flush [[DEF1]], [[DEF]], [[DEF2]], [[DEF3]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:modregbank(s20) = G_CONSTANT i20 128
    %5:ptrregbank(p0) = IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %7:gprregbank(s32) = IMPLICIT_DEF
    %8:modregbank(s20) = IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush_2d_byte
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; CHECK-LABEL: name: test_fifo_st_flush_2d_byte
    ; CHECK: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_512_CONV_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_CONV_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_CONV_2D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_512_CONV_2D3:%[0-9]+]]:edc = VST_FLUSH_512_CONV_2D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:modregbank(s20) = G_CONSTANT i20 128
    %8:ptrregbank(p0) = IMPLICIT_DEF
    %9:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %10:gprregbank(s32) = IMPLICIT_DEF
    %11:modregbank(s20) = IMPLICIT_DEF
    %12:modregbank(s20) = IMPLICIT_DEF
    %13:gprregbank(s32) = IMPLICIT_DEF
    %14:modregbank(s20) = IMPLICIT_DEF
    %15:modregbank(s20) = IMPLICIT_DEF
    %16:ptrregbank(p0), %17:fiforegbank(<32 x s32>), %18:gprregbank(s32), %19:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d.conv), %8:ptrregbank(p0), %9:fiforegbank(<32 x s32>), %10:gprregbank(s32), %11:modregbank(s20), %12:modregbank(s20), %14:modregbank(s20), %15:modregbank(s20)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush_3d_byte
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; CHECK-LABEL: name: test_fifo_st_flush_3d_byte
    ; CHECK: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_512_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_3D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_512_3D3:%[0-9]+]]:edcl, [[VST_FLUSH_512_3D4:%[0-9]+]]:edch = VST_FLUSH_512_3D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:gprregbank(s32) = COPY $r3
    %7:ptrregbank(p0) = COPY $p3
    %8:gprregbank(s32) = COPY $r4
    %9:modregbank(s20) = G_CONSTANT i20 128
    %11:ptrregbank(p0) = IMPLICIT_DEF
    %12:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %13:gprregbank(s32) = IMPLICIT_DEF
    %14:modregbank(s20) = IMPLICIT_DEF
    %15:modregbank(s20) = IMPLICIT_DEF
    %16:gprregbank(s32) = IMPLICIT_DEF
    %17:modregbank(s20) = IMPLICIT_DEF
    %18:modregbank(s20) = IMPLICIT_DEF
    %19:modregbank(s20) = IMPLICIT_DEF
    %20:gprregbank(s32) = IMPLICIT_DEF
    %21:modregbank(s20) = IMPLICIT_DEF
    %22:modregbank(s20) = IMPLICIT_DEF
    %23:ptrregbank(p0), %24:fiforegbank(<32 x s32>), %25:gprregbank(s32), %26:modregbank(s20), %27:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d), %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32), %14:modregbank(s20), %15:modregbank(s20), %17:modregbank(s20), %18:modregbank(s20), %19:modregbank(s20), %21:modregbank(s20), %22:modregbank(s20)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush_conv
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: test_fifo_st_flush_conv
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_512_CONV_normal_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_CONV_normal_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_CONV_normal_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_512_CONV_normal_flush [[DEF1]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:modregbank(s20) = G_CONSTANT i20 128
    %4:ptrregbank(p0) = IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %6:gprregbank(s32) = IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.conv), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush_conv_1d_byte
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: test_fifo_st_flush_conv_1d_byte
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_512_CONV_fifo_1d_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_CONV_fifo_1d_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_CONV_fifo_1d_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_512_CONV_fifo_1d_flush [[DEF1]], [[DEF]], [[DEF2]], [[DEF3]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:modregbank(s20) = G_CONSTANT i20 128
    %5:ptrregbank(p0) = IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %7:gprregbank(s32) = IMPLICIT_DEF
    %8:modregbank(s20) = IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d.conv), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush_conv_2d_byte
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; CHECK-LABEL: name: test_fifo_st_flush_conv_2d_byte
    ; CHECK: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_512_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_2D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_512_2D3:%[0-9]+]]:edc = VST_FLUSH_512_2D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:modregbank(s20) = G_CONSTANT i20 128
    %8:ptrregbank(p0) = IMPLICIT_DEF
    %9:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %10:gprregbank(s32) = IMPLICIT_DEF
    %11:modregbank(s20) = IMPLICIT_DEF
    %12:modregbank(s20) = IMPLICIT_DEF
    %13:gprregbank(s32) = IMPLICIT_DEF
    %14:modregbank(s20) = IMPLICIT_DEF
    %15:modregbank(s20) = IMPLICIT_DEF
    %16:ptrregbank(p0), %17:fiforegbank(<32 x s32>), %18:gprregbank(s32), %19:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d), %8:ptrregbank(p0), %9:fiforegbank(<32 x s32>), %10:gprregbank(s32), %11:modregbank(s20), %12:modregbank(s20), %14:modregbank(s20), %15:modregbank(s20)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush_conv_3d_byte
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; CHECK-LABEL: name: test_fifo_st_flush_conv_3d_byte
    ; CHECK: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_512_CONV_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_512_CONV_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_512_CONV_3D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_512_CONV_3D3:%[0-9]+]]:edcl, [[VST_FLUSH_512_CONV_3D4:%[0-9]+]]:edch = VST_FLUSH_512_CONV_3D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:gprregbank(s32) = COPY $r3
    %7:ptrregbank(p0) = COPY $p3
    %8:gprregbank(s32) = COPY $r4
    %9:modregbank(s20) = G_CONSTANT i20 128
    %11:ptrregbank(p0) = IMPLICIT_DEF
    %12:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %13:gprregbank(s32) = IMPLICIT_DEF
    %14:modregbank(s20) = IMPLICIT_DEF
    %15:modregbank(s20) = IMPLICIT_DEF
    %16:gprregbank(s32) = IMPLICIT_DEF
    %17:modregbank(s20) = IMPLICIT_DEF
    %18:modregbank(s20) = IMPLICIT_DEF
    %19:modregbank(s20) = IMPLICIT_DEF
    %20:gprregbank(s32) = IMPLICIT_DEF
    %21:modregbank(s20) = IMPLICIT_DEF
    %22:modregbank(s20) = IMPLICIT_DEF
    %23:ptrregbank(p0), %24:fiforegbank(<32 x s32>), %25:gprregbank(s32), %26:modregbank(s20), %27:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d.conv), %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32), %14:modregbank(s20), %15:modregbank(s20), %17:modregbank(s20), %18:modregbank(s20), %19:modregbank(s20), %21:modregbank(s20), %22:modregbank(s20)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_push_576
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e0, $p0, $p1, $x0
    ; CHECK-LABEL: name: test_fifo_st_push_576
    ; CHECK: liveins: $e0, $p0, $p1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:el = COPY $e0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec576 = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VST_PUSH_576_:%[0-9]+]]:mstfifo, [[VST_PUSH_576_1:%[0-9]+]]:mpfs, [[VST_PUSH_576_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_576 [[DEF1]], [[REG_SEQUENCE]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:ptrregbank(p0) = COPY $p1
    %4:modregbank(s20) = G_CONSTANT i20 128
    %6:ptrregbank(p0) = IMPLICIT_DEF
    %7:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %8:gprregbank(s32) = IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.576.bfp16), %6:ptrregbank(p0), %1:vregbank(<64 x s8>), %2:gprregbank(<8 x s8>), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_push_544
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $e0, $p0, $p1, $x0
    ; CHECK-LABEL: name: test_fifo_st_push_544
    ; CHECK: liveins: $e0, $p0, $p1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:el = COPY $e0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec576 = REG_SEQUENCE [[COPY]], %subreg.sub_bfp16_x, [[COPY1]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: [[VST_PUSH_544_:%[0-9]+]]:mstfifo, [[VST_PUSH_544_1:%[0-9]+]]:mpfs, [[VST_PUSH_544_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_544 [[DEF1]], [[REG_SEQUENCE]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(<8 x s8>) = COPY $e0
    %3:ptrregbank(p0) = COPY $p1
    %4:modregbank(s20) = G_CONSTANT i20 128
    %6:ptrregbank(p0) = IMPLICIT_DEF
    %7:fiforegbank(<32 x s32>) = IMPLICIT_DEF
    %8:gprregbank(s32) = IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.544.bfp16), %6:ptrregbank(p0), %1:vregbank(<64 x s8>), %2:gprregbank(<8 x s8>), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32)
    PseudoRET implicit $lr
...

