# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_SRS_2x_v16_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v8_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v8_acc64_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v32_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc32_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v16_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v16_acc64_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v32_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v32_acc32_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_2x_v16_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc64_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_4x_v64_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_signed
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_4x_v32_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc64_signed
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_2x_v16_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v8_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v8_acc64_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v32_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc32_unsigned
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v16_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v16_acc64_unsigned
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v32_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v32_acc32_unsigned
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_2x_v16_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc64_unsigned
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_4x_v64_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_unsigned
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_4x_v32_acc64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc64_unsigned
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_2x_v16_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v8_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v8_acc64_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v8.acc64.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v32_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc32_dynamic
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v16_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v16_acc64_dynamic
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v32_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v32_acc32_dynamic
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_2x_v16_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc64_dynamic
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s32>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_4x_v64_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_dynamic
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_4x_v32_acc64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc64_dynamic
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>))
    ; CHECK-NEXT: $srssign0 = MOV_scalar_imm11_pseudo 0
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc64.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...
