# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDB_UNPACK_I512_I8_I4_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_signed
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], -256, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 224, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s16>))
    %103:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<16 x s16>), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s16>))
    %104:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %26:vregbank(<16 x s16>), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s16>))
    %105:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %27:vregbank(<16 x s16>), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s16>))
    %106:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %28:vregbank(<16 x s16>), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s16>))
    %107:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %29:vregbank(<16 x s16>), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s16>))
    %108:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %30:vregbank(<16 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I16_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_signed
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], -256, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 224, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s16>))
    %103:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<16 x s16>), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s16>))
    %104:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %26:vregbank(<16 x s16>), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s16>))
    %105:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %27:vregbank(<16 x s16>), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s16>))
    %106:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %28:vregbank(<16 x s16>), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s16>))
    %107:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %29:vregbank(<16 x s16>), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s16>))
    %108:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %30:vregbank(<16 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I8_I4_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_signed
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], -512, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 448, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s32>))
    %103:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<16 x s32>), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s32>))
    %104:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %26:vregbank(<16 x s32>), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s32>))
    %105:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %27:vregbank(<16 x s32>), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s32>))
    %106:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %28:vregbank(<16 x s32>), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s32>))
    %107:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %29:vregbank(<16 x s32>), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s32>))
    %108:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %30:vregbank(<16 x s32>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I16_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_signed
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], -512, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 448, implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s32>))
    %103:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<16 x s32>), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s32>))
    %104:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %26:vregbank(<16 x s32>), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s32>))
    %105:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %27:vregbank(<16 x s32>), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s32>))
    %106:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %28:vregbank(<16 x s32>), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s32>))
    %107:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %29:vregbank(<16 x s32>), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s32>))
    %108:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %30:vregbank(<16 x s32>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I8_I4_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_unsigned
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s16>))
    %103:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<16 x s16>), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s16>))
    %104:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %26:vregbank(<16 x s16>), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s16>))
    %105:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %27:vregbank(<16 x s16>), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s16>))
    %106:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %28:vregbank(<16 x s16>), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s16>))
    %107:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %29:vregbank(<16 x s16>), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s16>))
    %108:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %30:vregbank(<16 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I16_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_unsigned
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s16>))
    %103:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<16 x s16>), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s16>))
    %104:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %26:vregbank(<16 x s16>), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s16>))
    %105:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %27:vregbank(<16 x s16>), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s16>))
    %106:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %28:vregbank(<16 x s16>), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s16>))
    %107:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %29:vregbank(<16 x s16>), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s16>))
    %108:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %30:vregbank(<16 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I8_I4_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_unsigned
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s32>))
    %103:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<16 x s32>), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s32>))
    %104:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %26:vregbank(<16 x s32>), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s32>))
    %105:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %27:vregbank(<16 x s32>), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s32>))
    %106:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %28:vregbank(<16 x s32>), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s32>))
    %107:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %29:vregbank(<16 x s32>), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s32>))
    %108:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %30:vregbank(<16 x s32>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I16_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_unsigned
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %25:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s32>))
    %103:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<16 x s32>), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s32>))
    %104:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %26:vregbank(<16 x s32>), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s32>))
    %105:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %27:vregbank(<16 x s32>), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s32>))
    %106:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %28:vregbank(<16 x s32>), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s32>))
    %107:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %29:vregbank(<16 x s32>), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s32>))
    %108:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %30:vregbank(<16 x s32>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I8_I4_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %102:gprregbank(s32) = COPY $r1
    %25:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s16>))
    %103:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %25:vregbank(<16 x s16>), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s16>))
    %104:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %26:vregbank(<16 x s16>), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s16>))
    %105:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %27:vregbank(<16 x s16>), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s16>))
    %106:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %28:vregbank(<16 x s16>), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s16>))
    %107:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %29:vregbank(<16 x s16>), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s16>))
    %108:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %30:vregbank(<16 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I512_I16_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -256, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 224, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %12:modregbank(s20) = G_CONSTANT i20 256
    %102:gprregbank(s32) = COPY $r1
    %25:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s16>))
    %103:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %25:vregbank(<16 x s16>), %102:gprregbank(s32)
    %26:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s16>))
    %104:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %26:vregbank(<16 x s16>), %102:gprregbank(s32)
    %27:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s16>))
    %105:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %27:vregbank(<16 x s16>), %102:gprregbank(s32)
    %28:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s16>))
    %106:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %28:vregbank(<16 x s16>), %102:gprregbank(s32)
    %29:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s16>))
    %107:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %29:vregbank(<16 x s16>), %102:gprregbank(s32)
    %30:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s16>))
    %108:vregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %30:vregbank(<16 x s16>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I8_I4_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %102:gprregbank(s32) = COPY $r1
    %25:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s32>))
    %103:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %25:vregbank(<16 x s32>), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s32>))
    %104:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %26:vregbank(<16 x s32>), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s32>))
    %105:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %27:vregbank(<16 x s32>), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s32>))
    %106:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %28:vregbank(<16 x s32>), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s32>))
    %107:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %29:vregbank(<16 x s32>), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s32>))
    %108:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %30:vregbank(<16 x s32>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...

---
name:            VLDB_UNPACK_I1024_I16_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], -512, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 448, implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0 [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit $crunpacksize, implicit $unpacksign0 :: (load (<16 x s32>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_1]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_2]], implicit [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign0_2]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 32
    %10:modregbank(s20) = G_CONSTANT i20 -512
    %11:modregbank(s20) = G_CONSTANT i20 448
    %12:modregbank(s20) = G_CONSTANT i20 512
    %102:gprregbank(s32) = COPY $r1
    %25:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %7 :: (load (<16 x s32>))
    %103:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %25:vregbank(<16 x s32>), %102:gprregbank(s32)
    %26:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %8 :: (load (<16 x s32>))
    %104:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %26:vregbank(<16 x s32>), %102:gprregbank(s32)
    %27:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %9 :: (load (<16 x s32>))
    %105:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %27:vregbank(<16 x s32>), %102:gprregbank(s32)
    %28:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %10 :: (load (<16 x s32>))
    %106:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %28:vregbank(<16 x s32>), %102:gprregbank(s32)
    %29:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %11 :: (load (<16 x s32>))
    %107:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %29:vregbank(<16 x s32>), %102:gprregbank(s32)
    %30:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %0, %12 :: (load (<16 x s32>))
    %108:vregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %30:vregbank(<16 x s32>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %104, implicit %105, implicit %106, implicit %107, implicit %108
...
