# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDB_UNPACK_I512_I8_I4_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I512_I16_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I8_I4_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I512_I16_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I8_I4_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_dynamic
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I512_I16_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_dynamic
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I16.I8), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I8_I4_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_dynamic
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I8.I4), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_COPY
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_COPY
    ; CHECK: liveins: $p0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: $crunpacksize = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = COPY $m0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<32 x s8>))
    %9:vregbank(<32 x s8>) = COPY %5
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.unpack.I512.I8.I4), %9:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

