# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            v2s32
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v2s32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0, $l1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:el = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:el = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:el = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $l0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0, $l1
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    %val_2:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
  bb.2:
    %phi:gprregbank(<2 x s32>) = G_PHI %val_2(<2 x s32>), %bb.1, %val_1(<2 x s32>), %bb.0
    $l0 = COPY %phi
...

---
name:            v4s16
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v4s16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0, $l1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:el = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:el = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:el = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $l0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0, $l1
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:gprregbank(<4 x s16>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    %val_2:gprregbank(<4 x s16>) = G_IMPLICIT_DEF
  bb.2:
    %phi:gprregbank(<4 x s16>) = G_PHI %val_2(<4 x s16>), %bb.1, %val_1(<4 x s16>), %bb.0
    $l0 = COPY %phi
...

---
name:            v8s8
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v8s8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0, $l1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:el = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:el = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:el = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $l0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0, $l1
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    %val_2:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
  bb.2:
    %phi:gprregbank(<8 x s8>) = G_PHI %val_2(<8 x s8>), %bb.1, %val_1(<8 x s8>), %bb.0
    $l0 = COPY %phi
...

---
name:            v4s32
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v4s32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $q1, $q2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec128 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec128 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec128 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $q0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $q1, $q2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<4 x s32>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    %val_2:vregbank(<4 x s32>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<4 x s32>) = G_PHI %val_2(<4 x s32>), %bb.1, %val_1(<4 x s32>), %bb.0
    $q0 = COPY %phi
...
---
name:            v8s16
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v8s16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $q1, $q2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec128 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec128 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec128 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $q0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $q1, $q2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<8 x s16>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    %val_2:vregbank(<8 x s16>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<8 x s16>) = G_PHI %val_2(<8 x s16>), %bb.1, %val_1(<8 x s16>), %bb.0
    $q0 = COPY %phi
...
---
name:            v16s8
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: v16s8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $q1, $q2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:vec128 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:vec128 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:vec128 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $q0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $q1, $q2
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:vregbank(<16 x s8>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    successors: %bb.2(0x80000000)
    %val_2:vregbank(<16 x s8>) = G_IMPLICIT_DEF
  bb.2:
    %phi:vregbank(<16 x s8>) = G_PHI %val_2(<16 x s8>), %bb.1, %val_1(<16 x s8>), %bb.0
    $q0 = COPY %phi
...
