# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_unmerge_512_to_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $x0
    ; CHECK-LABEL: name: test_unmerge_512_to_256
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]], implicit [[COPY2]]
    %0:vregbank(<2 x s256>) = COPY $x0
    %1:vregbank(s256), %2:vregbank(s256) = G_UNMERGE_VALUES %0(<2 x s256>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:            test_unmerge_1024_to_512_vec
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $y2
    ; CHECK-LABEL: name: test_unmerge_1024_to_512_vec
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]], implicit [[COPY2]]
    %0:vregbank(<2 x s512>) = COPY $y2
    %1:vregbank(s512), %2:vregbank(s512) = G_UNMERGE_VALUES %0(<2 x s512>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...


---
name:            test_unmerge_1024_to_512_acc
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $cml0
    ; CHECK-LABEL: name: test_unmerge_1024_to_512_acc
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY [[COPY]].sub_512_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]], implicit [[COPY2]]
    %0:accregbank(<2 x s512>) = COPY $cml0
    %1:accregbank(s512), %2:accregbank(s512) = G_UNMERGE_VALUES %0(<2 x s512>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:            test_unmerge_2048_to_1024
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_2048_to_1024
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]], implicit [[COPY2]]
    %0:accregbank(<2 x s1024>) = COPY $dm0
    %1:accregbank(s1024), %2:accregbank(s1024) = G_UNMERGE_VALUES %0(<2 x s1024>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...
---
name:            test_unmerge_2048_to_1024_vector
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_2048_to_1024_vector
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]], implicit [[COPY2]]
    %0:accregbank(<64 x s32>) = COPY $dm0
    %1:accregbank(<32 x s32>), %2:accregbank(<32 x s32>) = G_UNMERGE_VALUES %0(<64 x s32>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...
---
name:            test_unmerge_8xs256_to_4xs256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_8xs256_to_4xs256
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY2]], implicit [[COPY1]]
    %0:accregbank(<8 x s256>) = COPY $dm0
    %2:accregbank(<4 x s256>), %1:accregbank(<4 x s256>) = G_UNMERGE_VALUES %0(<8 x s256>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...
---
name:            test_unmerge_4xs512_to_2xs512_vector
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_4xs512_to_2xs512_vector
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY [[COPY]].sub_1024_acc_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY2]], implicit [[COPY1]]
    %0:accregbank(<4 x s512>) = COPY $dm0
    %2:accregbank(<2 x s512>), %1:accregbank(<2 x s512>) = G_UNMERGE_VALUES %0(<4 x s512>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...
---
name:            test_unmerge_4xs256_to_2xs256_vector
legalized:       true
regBankSelected: true
tracksRegLiveness: true
stack:
  - { id: 0, name: "", size: 128, alignment: 32 }
body:             |
  bb.0.entry:
    liveins: $y2
    ; CHECK-LABEL: name: test_unmerge_4xs256_to_2xs256_vector
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_512_hi
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY2]], implicit [[COPY1]]
    %0:vregbank(<4 x s256>) = COPY $y2
    %2:vregbank(<2 x s256>), %1:vregbank(<2 x s256>) = G_UNMERGE_VALUES %0(<4 x s256>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...
