; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

; 128-bit vector types

declare void @callee_v4int32(<4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>,
                             <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>,
                             <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>,
                             <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>,
                             <4 x i32>, <4 x i32>)
define void @call_v4int32() {
  ; CHECK-LABEL: name: call_v4int32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32), [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV]](s32), [[UV1]](s32), [[UV2]](s32), [[UV3]](s32), [[DEF]](s32), [[DEF]](s32), [[DEF]](s32), [[DEF]](s32)
  ; CHECK-NEXT:   [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32), [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV4]](s32), [[UV5]](s32), [[UV6]](s32), [[UV7]](s32), [[DEF1]](s32), [[DEF1]](s32), [[DEF1]](s32), [[DEF1]](s32)
  ; CHECK-NEXT:   [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32), [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR3:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV8]](s32), [[UV9]](s32), [[UV10]](s32), [[UV11]](s32), [[DEF2]](s32), [[DEF2]](s32), [[DEF2]](s32), [[DEF2]](s32)
  ; CHECK-NEXT:   [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32), [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR4:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV12]](s32), [[UV13]](s32), [[UV14]](s32), [[UV15]](s32), [[DEF3]](s32), [[DEF3]](s32), [[DEF3]](s32), [[DEF3]](s32)
  ; CHECK-NEXT:   [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32), [[UV18:%[0-9]+]]:_(s32), [[UV19:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR5:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV16]](s32), [[UV17]](s32), [[UV18]](s32), [[UV19]](s32), [[DEF4]](s32), [[DEF4]](s32), [[DEF4]](s32), [[DEF4]](s32)
  ; CHECK-NEXT:   [[UV20:%[0-9]+]]:_(s32), [[UV21:%[0-9]+]]:_(s32), [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF5:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR6:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV20]](s32), [[UV21]](s32), [[UV22]](s32), [[UV23]](s32), [[DEF5]](s32), [[DEF5]](s32), [[DEF5]](s32), [[DEF5]](s32)
  ; CHECK-NEXT:   [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32), [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF6:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR7:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV24]](s32), [[UV25]](s32), [[UV26]](s32), [[UV27]](s32), [[DEF6]](s32), [[DEF6]](s32), [[DEF6]](s32), [[DEF6]](s32)
  ; CHECK-NEXT:   [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32), [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF7:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR8:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV28]](s32), [[UV29]](s32), [[UV30]](s32), [[UV31]](s32), [[DEF7]](s32), [[DEF7]](s32), [[DEF7]](s32), [[DEF7]](s32)
  ; CHECK-NEXT:   [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32), [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF8:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR9:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV32]](s32), [[UV33]](s32), [[UV34]](s32), [[UV35]](s32), [[DEF8]](s32), [[DEF8]](s32), [[DEF8]](s32), [[DEF8]](s32)
  ; CHECK-NEXT:   [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32), [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF9:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR10:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV36]](s32), [[UV37]](s32), [[UV38]](s32), [[UV39]](s32), [[DEF9]](s32), [[DEF9]](s32), [[DEF9]](s32), [[DEF9]](s32)
  ; CHECK-NEXT:   [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32), [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF10:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR11:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV40]](s32), [[UV41]](s32), [[UV42]](s32), [[UV43]](s32), [[DEF10]](s32), [[DEF10]](s32), [[DEF10]](s32), [[DEF10]](s32)
  ; CHECK-NEXT:   [[UV44:%[0-9]+]]:_(s32), [[UV45:%[0-9]+]]:_(s32), [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF11:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR12:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV44]](s32), [[UV45]](s32), [[UV46]](s32), [[UV47]](s32), [[DEF11]](s32), [[DEF11]](s32), [[DEF11]](s32), [[DEF11]](s32)
  ; CHECK-NEXT:   [[UV48:%[0-9]+]]:_(s32), [[UV49:%[0-9]+]]:_(s32), [[UV50:%[0-9]+]]:_(s32), [[UV51:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF12:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR13:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV48]](s32), [[UV49]](s32), [[UV50]](s32), [[UV51]](s32), [[DEF12]](s32), [[DEF12]](s32), [[DEF12]](s32), [[DEF12]](s32)
  ; CHECK-NEXT:   [[UV52:%[0-9]+]]:_(s32), [[UV53:%[0-9]+]]:_(s32), [[UV54:%[0-9]+]]:_(s32), [[UV55:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF13:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR14:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV52]](s32), [[UV53]](s32), [[UV54]](s32), [[UV55]](s32), [[DEF13]](s32), [[DEF13]](s32), [[DEF13]](s32), [[DEF13]](s32)
  ; CHECK-NEXT:   [[UV56:%[0-9]+]]:_(s32), [[UV57:%[0-9]+]]:_(s32), [[UV58:%[0-9]+]]:_(s32), [[UV59:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF14:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR15:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV56]](s32), [[UV57]](s32), [[UV58]](s32), [[UV59]](s32), [[DEF14]](s32), [[DEF14]](s32), [[DEF14]](s32), [[DEF14]](s32)
  ; CHECK-NEXT:   [[UV60:%[0-9]+]]:_(s32), [[UV61:%[0-9]+]]:_(s32), [[UV62:%[0-9]+]]:_(s32), [[UV63:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF15:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR16:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV60]](s32), [[UV61]](s32), [[UV62]](s32), [[UV63]](s32), [[DEF15]](s32), [[DEF15]](s32), [[DEF15]](s32), [[DEF15]](s32)
  ; CHECK-NEXT:   [[UV64:%[0-9]+]]:_(s32), [[UV65:%[0-9]+]]:_(s32), [[UV66:%[0-9]+]]:_(s32), [[UV67:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF16:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR17:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV64]](s32), [[UV65]](s32), [[UV66]](s32), [[UV67]](s32), [[DEF16]](s32), [[DEF16]](s32), [[DEF16]](s32), [[DEF16]](s32)
  ; CHECK-NEXT:   [[UV68:%[0-9]+]]:_(s32), [[UV69:%[0-9]+]]:_(s32), [[UV70:%[0-9]+]]:_(s32), [[UV71:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF17:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR18:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV68]](s32), [[UV69]](s32), [[UV70]](s32), [[UV71]](s32), [[DEF17]](s32), [[DEF17]](s32), [[DEF17]](s32), [[DEF17]](s32)
  ; CHECK-NEXT:   [[UV72:%[0-9]+]]:_(s32), [[UV73:%[0-9]+]]:_(s32), [[UV74:%[0-9]+]]:_(s32), [[UV75:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF18:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR19:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV72]](s32), [[UV73]](s32), [[UV74]](s32), [[UV75]](s32), [[DEF18]](s32), [[DEF18]](s32), [[DEF18]](s32), [[DEF18]](s32)
  ; CHECK-NEXT:   [[UV76:%[0-9]+]]:_(s32), [[UV77:%[0-9]+]]:_(s32), [[UV78:%[0-9]+]]:_(s32), [[UV79:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF19:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR20:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV76]](s32), [[UV77]](s32), [[UV78]](s32), [[UV79]](s32), [[DEF19]](s32), [[DEF19]](s32), [[DEF19]](s32), [[DEF19]](s32)
  ; CHECK-NEXT:   [[UV80:%[0-9]+]]:_(s32), [[UV81:%[0-9]+]]:_(s32), [[UV82:%[0-9]+]]:_(s32), [[UV83:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF20:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR21:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV80]](s32), [[UV81]](s32), [[UV82]](s32), [[UV83]](s32), [[DEF20]](s32), [[DEF20]](s32), [[DEF20]](s32), [[DEF20]](s32)
  ; CHECK-NEXT:   [[UV84:%[0-9]+]]:_(s32), [[UV85:%[0-9]+]]:_(s32), [[UV86:%[0-9]+]]:_(s32), [[UV87:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF21:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR22:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV84]](s32), [[UV85]](s32), [[UV86]](s32), [[UV87]](s32), [[DEF21]](s32), [[DEF21]](s32), [[DEF21]](s32), [[DEF21]](s32)
  ; CHECK-NEXT:   [[UV88:%[0-9]+]]:_(s32), [[UV89:%[0-9]+]]:_(s32), [[UV90:%[0-9]+]]:_(s32), [[UV91:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF22:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR23:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV88]](s32), [[UV89]](s32), [[UV90]](s32), [[UV91]](s32), [[DEF22]](s32), [[DEF22]](s32), [[DEF22]](s32), [[DEF22]](s32)
  ; CHECK-NEXT:   [[UV92:%[0-9]+]]:_(s32), [[UV93:%[0-9]+]]:_(s32), [[UV94:%[0-9]+]]:_(s32), [[UV95:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF23:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR24:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV92]](s32), [[UV93]](s32), [[UV94]](s32), [[UV95]](s32), [[DEF23]](s32), [[DEF23]](s32), [[DEF23]](s32), [[DEF23]](s32)
  ; CHECK-NEXT:   [[UV96:%[0-9]+]]:_(s32), [[UV97:%[0-9]+]]:_(s32), [[UV98:%[0-9]+]]:_(s32), [[UV99:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF24:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR25:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV96]](s32), [[UV97]](s32), [[UV98]](s32), [[UV99]](s32), [[DEF24]](s32), [[DEF24]](s32), [[DEF24]](s32), [[DEF24]](s32)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR25]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into stack - 32)
  ; CHECK-NEXT:   [[UV100:%[0-9]+]]:_(s32), [[UV101:%[0-9]+]]:_(s32), [[UV102:%[0-9]+]]:_(s32), [[UV103:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF25:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR26:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV100]](s32), [[UV101]](s32), [[UV102]](s32), [[UV103]](s32), [[DEF25]](s32), [[DEF25]](s32), [[DEF25]](s32), [[DEF25]](s32)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR26]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into stack - 64)
  ; CHECK-NEXT:   $wl0 = COPY [[BUILD_VECTOR1]](<8 x s32>)
  ; CHECK-NEXT:   $wl2 = COPY [[BUILD_VECTOR2]](<8 x s32>)
  ; CHECK-NEXT:   $wl4 = COPY [[BUILD_VECTOR3]](<8 x s32>)
  ; CHECK-NEXT:   $wl6 = COPY [[BUILD_VECTOR4]](<8 x s32>)
  ; CHECK-NEXT:   $wl8 = COPY [[BUILD_VECTOR5]](<8 x s32>)
  ; CHECK-NEXT:   $wl10 = COPY [[BUILD_VECTOR6]](<8 x s32>)
  ; CHECK-NEXT:   $wl1 = COPY [[BUILD_VECTOR7]](<8 x s32>)
  ; CHECK-NEXT:   $wl3 = COPY [[BUILD_VECTOR8]](<8 x s32>)
  ; CHECK-NEXT:   $wl5 = COPY [[BUILD_VECTOR9]](<8 x s32>)
  ; CHECK-NEXT:   $wl7 = COPY [[BUILD_VECTOR10]](<8 x s32>)
  ; CHECK-NEXT:   $wl9 = COPY [[BUILD_VECTOR11]](<8 x s32>)
  ; CHECK-NEXT:   $wl11 = COPY [[BUILD_VECTOR12]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[BUILD_VECTOR13]](<8 x s32>)
  ; CHECK-NEXT:   $wh2 = COPY [[BUILD_VECTOR14]](<8 x s32>)
  ; CHECK-NEXT:   $wh4 = COPY [[BUILD_VECTOR15]](<8 x s32>)
  ; CHECK-NEXT:   $wh6 = COPY [[BUILD_VECTOR16]](<8 x s32>)
  ; CHECK-NEXT:   $wh8 = COPY [[BUILD_VECTOR17]](<8 x s32>)
  ; CHECK-NEXT:   $wh10 = COPY [[BUILD_VECTOR18]](<8 x s32>)
  ; CHECK-NEXT:   $wh1 = COPY [[BUILD_VECTOR19]](<8 x s32>)
  ; CHECK-NEXT:   $wh3 = COPY [[BUILD_VECTOR20]](<8 x s32>)
  ; CHECK-NEXT:   $wh5 = COPY [[BUILD_VECTOR21]](<8 x s32>)
  ; CHECK-NEXT:   $wh7 = COPY [[BUILD_VECTOR22]](<8 x s32>)
  ; CHECK-NEXT:   $wh9 = COPY [[BUILD_VECTOR23]](<8 x s32>)
  ; CHECK-NEXT:   $wh11 = COPY [[BUILD_VECTOR24]](<8 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v4int32, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v4int32(<4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer,
                            <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer,
                            <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer,
                            <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer,
                            <4 x i32> zeroinitializer, <4 x i32> zeroinitializer)
  ret void
}

declare void @callee_v8int16(<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>,
                             <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>,
                             <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>,
                             <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>,
                             <8 x i16>, <8 x i16>)
define void @call_v8int16() {
  ; CHECK-LABEL: name: call_v8int16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT1:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT2:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT3:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT4:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT5:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT6:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT7:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT8:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT9:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT10:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT11:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT12:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT13:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT14:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT15:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT16:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT17:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT18:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT19:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT20:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT21:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT22:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT23:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[ANYEXT24:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[ANYEXT24]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into stack - 32)
  ; CHECK-NEXT:   [[ANYEXT25:%[0-9]+]]:_(<8 x s32>) = G_ANYEXT [[BUILD_VECTOR]](<8 x s16>)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   G_STORE [[ANYEXT25]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into stack - 64)
  ; CHECK-NEXT:   $wl0 = COPY [[ANYEXT]](<8 x s32>)
  ; CHECK-NEXT:   $wl2 = COPY [[ANYEXT1]](<8 x s32>)
  ; CHECK-NEXT:   $wl4 = COPY [[ANYEXT2]](<8 x s32>)
  ; CHECK-NEXT:   $wl6 = COPY [[ANYEXT3]](<8 x s32>)
  ; CHECK-NEXT:   $wl8 = COPY [[ANYEXT4]](<8 x s32>)
  ; CHECK-NEXT:   $wl10 = COPY [[ANYEXT5]](<8 x s32>)
  ; CHECK-NEXT:   $wl1 = COPY [[ANYEXT6]](<8 x s32>)
  ; CHECK-NEXT:   $wl3 = COPY [[ANYEXT7]](<8 x s32>)
  ; CHECK-NEXT:   $wl5 = COPY [[ANYEXT8]](<8 x s32>)
  ; CHECK-NEXT:   $wl7 = COPY [[ANYEXT9]](<8 x s32>)
  ; CHECK-NEXT:   $wl9 = COPY [[ANYEXT10]](<8 x s32>)
  ; CHECK-NEXT:   $wl11 = COPY [[ANYEXT11]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[ANYEXT12]](<8 x s32>)
  ; CHECK-NEXT:   $wh2 = COPY [[ANYEXT13]](<8 x s32>)
  ; CHECK-NEXT:   $wh4 = COPY [[ANYEXT14]](<8 x s32>)
  ; CHECK-NEXT:   $wh6 = COPY [[ANYEXT15]](<8 x s32>)
  ; CHECK-NEXT:   $wh8 = COPY [[ANYEXT16]](<8 x s32>)
  ; CHECK-NEXT:   $wh10 = COPY [[ANYEXT17]](<8 x s32>)
  ; CHECK-NEXT:   $wh1 = COPY [[ANYEXT18]](<8 x s32>)
  ; CHECK-NEXT:   $wh3 = COPY [[ANYEXT19]](<8 x s32>)
  ; CHECK-NEXT:   $wh5 = COPY [[ANYEXT20]](<8 x s32>)
  ; CHECK-NEXT:   $wh7 = COPY [[ANYEXT21]](<8 x s32>)
  ; CHECK-NEXT:   $wh9 = COPY [[ANYEXT22]](<8 x s32>)
  ; CHECK-NEXT:   $wh11 = COPY [[ANYEXT23]](<8 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v8int16, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v8int16(<8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer,
                            <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer,
                            <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer,
                            <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer, <8 x i16> zeroinitializer,
                            <8 x i16> zeroinitializer, <8 x i16> zeroinitializer)
  ret void
}

declare void @callee_v16int8(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>,
                             <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>,
                             <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>,
                             <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>,
                             <16 x i8>, <16 x i8>)
define void @call_v16int8() {
  ; CHECK-LABEL: name: call_v16int8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_BUILD_VECTOR [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT1:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT2:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT3:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT4:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT5:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT6:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT7:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT8:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT9:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT10:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT11:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT12:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT13:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT14:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT15:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT16:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT17:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT18:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT19:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT20:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT21:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT22:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT23:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[ANYEXT24:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[ANYEXT24]](<16 x s16>), [[PTR_ADD]](p0) :: (store (<16 x s16>) into stack - 32)
  ; CHECK-NEXT:   [[ANYEXT25:%[0-9]+]]:_(<16 x s16>) = G_ANYEXT [[BUILD_VECTOR]](<16 x s8>)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   G_STORE [[ANYEXT25]](<16 x s16>), [[PTR_ADD1]](p0) :: (store (<16 x s16>) into stack - 64)
  ; CHECK-NEXT:   $wl0 = COPY [[ANYEXT]](<16 x s16>)
  ; CHECK-NEXT:   $wl2 = COPY [[ANYEXT1]](<16 x s16>)
  ; CHECK-NEXT:   $wl4 = COPY [[ANYEXT2]](<16 x s16>)
  ; CHECK-NEXT:   $wl6 = COPY [[ANYEXT3]](<16 x s16>)
  ; CHECK-NEXT:   $wl8 = COPY [[ANYEXT4]](<16 x s16>)
  ; CHECK-NEXT:   $wl10 = COPY [[ANYEXT5]](<16 x s16>)
  ; CHECK-NEXT:   $wl1 = COPY [[ANYEXT6]](<16 x s16>)
  ; CHECK-NEXT:   $wl3 = COPY [[ANYEXT7]](<16 x s16>)
  ; CHECK-NEXT:   $wl5 = COPY [[ANYEXT8]](<16 x s16>)
  ; CHECK-NEXT:   $wl7 = COPY [[ANYEXT9]](<16 x s16>)
  ; CHECK-NEXT:   $wl9 = COPY [[ANYEXT10]](<16 x s16>)
  ; CHECK-NEXT:   $wl11 = COPY [[ANYEXT11]](<16 x s16>)
  ; CHECK-NEXT:   $wh0 = COPY [[ANYEXT12]](<16 x s16>)
  ; CHECK-NEXT:   $wh2 = COPY [[ANYEXT13]](<16 x s16>)
  ; CHECK-NEXT:   $wh4 = COPY [[ANYEXT14]](<16 x s16>)
  ; CHECK-NEXT:   $wh6 = COPY [[ANYEXT15]](<16 x s16>)
  ; CHECK-NEXT:   $wh8 = COPY [[ANYEXT16]](<16 x s16>)
  ; CHECK-NEXT:   $wh10 = COPY [[ANYEXT17]](<16 x s16>)
  ; CHECK-NEXT:   $wh1 = COPY [[ANYEXT18]](<16 x s16>)
  ; CHECK-NEXT:   $wh3 = COPY [[ANYEXT19]](<16 x s16>)
  ; CHECK-NEXT:   $wh5 = COPY [[ANYEXT20]](<16 x s16>)
  ; CHECK-NEXT:   $wh7 = COPY [[ANYEXT21]](<16 x s16>)
  ; CHECK-NEXT:   $wh9 = COPY [[ANYEXT22]](<16 x s16>)
  ; CHECK-NEXT:   $wh11 = COPY [[ANYEXT23]](<16 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v16int8, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v16int8(<16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer,
                            <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer,
                            <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer,
                            <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer, <16 x i8> zeroinitializer,
                            <16 x i8> zeroinitializer, <16 x i8> zeroinitializer)
  ret void
}

declare void @callee_v4float(<4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>,
                             <4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>,
                             <4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>,
                             <4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>, <4 x float>,
                             <4 x float>, <4 x float>)
define void @call_v4float() {
  ; CHECK-LABEL: name: call_v4float
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32), [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV]](s32), [[UV1]](s32), [[UV2]](s32), [[UV3]](s32), [[DEF]](s32), [[DEF]](s32), [[DEF]](s32), [[DEF]](s32)
  ; CHECK-NEXT:   [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32), [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV4]](s32), [[UV5]](s32), [[UV6]](s32), [[UV7]](s32), [[DEF1]](s32), [[DEF1]](s32), [[DEF1]](s32), [[DEF1]](s32)
  ; CHECK-NEXT:   [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32), [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR3:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV8]](s32), [[UV9]](s32), [[UV10]](s32), [[UV11]](s32), [[DEF2]](s32), [[DEF2]](s32), [[DEF2]](s32), [[DEF2]](s32)
  ; CHECK-NEXT:   [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32), [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR4:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV12]](s32), [[UV13]](s32), [[UV14]](s32), [[UV15]](s32), [[DEF3]](s32), [[DEF3]](s32), [[DEF3]](s32), [[DEF3]](s32)
  ; CHECK-NEXT:   [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32), [[UV18:%[0-9]+]]:_(s32), [[UV19:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR5:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV16]](s32), [[UV17]](s32), [[UV18]](s32), [[UV19]](s32), [[DEF4]](s32), [[DEF4]](s32), [[DEF4]](s32), [[DEF4]](s32)
  ; CHECK-NEXT:   [[UV20:%[0-9]+]]:_(s32), [[UV21:%[0-9]+]]:_(s32), [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF5:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR6:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV20]](s32), [[UV21]](s32), [[UV22]](s32), [[UV23]](s32), [[DEF5]](s32), [[DEF5]](s32), [[DEF5]](s32), [[DEF5]](s32)
  ; CHECK-NEXT:   [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32), [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF6:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR7:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV24]](s32), [[UV25]](s32), [[UV26]](s32), [[UV27]](s32), [[DEF6]](s32), [[DEF6]](s32), [[DEF6]](s32), [[DEF6]](s32)
  ; CHECK-NEXT:   [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32), [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF7:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR8:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV28]](s32), [[UV29]](s32), [[UV30]](s32), [[UV31]](s32), [[DEF7]](s32), [[DEF7]](s32), [[DEF7]](s32), [[DEF7]](s32)
  ; CHECK-NEXT:   [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32), [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF8:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR9:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV32]](s32), [[UV33]](s32), [[UV34]](s32), [[UV35]](s32), [[DEF8]](s32), [[DEF8]](s32), [[DEF8]](s32), [[DEF8]](s32)
  ; CHECK-NEXT:   [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32), [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF9:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR10:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV36]](s32), [[UV37]](s32), [[UV38]](s32), [[UV39]](s32), [[DEF9]](s32), [[DEF9]](s32), [[DEF9]](s32), [[DEF9]](s32)
  ; CHECK-NEXT:   [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32), [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF10:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR11:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV40]](s32), [[UV41]](s32), [[UV42]](s32), [[UV43]](s32), [[DEF10]](s32), [[DEF10]](s32), [[DEF10]](s32), [[DEF10]](s32)
  ; CHECK-NEXT:   [[UV44:%[0-9]+]]:_(s32), [[UV45:%[0-9]+]]:_(s32), [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF11:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR12:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV44]](s32), [[UV45]](s32), [[UV46]](s32), [[UV47]](s32), [[DEF11]](s32), [[DEF11]](s32), [[DEF11]](s32), [[DEF11]](s32)
  ; CHECK-NEXT:   [[UV48:%[0-9]+]]:_(s32), [[UV49:%[0-9]+]]:_(s32), [[UV50:%[0-9]+]]:_(s32), [[UV51:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF12:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR13:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV48]](s32), [[UV49]](s32), [[UV50]](s32), [[UV51]](s32), [[DEF12]](s32), [[DEF12]](s32), [[DEF12]](s32), [[DEF12]](s32)
  ; CHECK-NEXT:   [[UV52:%[0-9]+]]:_(s32), [[UV53:%[0-9]+]]:_(s32), [[UV54:%[0-9]+]]:_(s32), [[UV55:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF13:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR14:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV52]](s32), [[UV53]](s32), [[UV54]](s32), [[UV55]](s32), [[DEF13]](s32), [[DEF13]](s32), [[DEF13]](s32), [[DEF13]](s32)
  ; CHECK-NEXT:   [[UV56:%[0-9]+]]:_(s32), [[UV57:%[0-9]+]]:_(s32), [[UV58:%[0-9]+]]:_(s32), [[UV59:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF14:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR15:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV56]](s32), [[UV57]](s32), [[UV58]](s32), [[UV59]](s32), [[DEF14]](s32), [[DEF14]](s32), [[DEF14]](s32), [[DEF14]](s32)
  ; CHECK-NEXT:   [[UV60:%[0-9]+]]:_(s32), [[UV61:%[0-9]+]]:_(s32), [[UV62:%[0-9]+]]:_(s32), [[UV63:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF15:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR16:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV60]](s32), [[UV61]](s32), [[UV62]](s32), [[UV63]](s32), [[DEF15]](s32), [[DEF15]](s32), [[DEF15]](s32), [[DEF15]](s32)
  ; CHECK-NEXT:   [[UV64:%[0-9]+]]:_(s32), [[UV65:%[0-9]+]]:_(s32), [[UV66:%[0-9]+]]:_(s32), [[UV67:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF16:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR17:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV64]](s32), [[UV65]](s32), [[UV66]](s32), [[UV67]](s32), [[DEF16]](s32), [[DEF16]](s32), [[DEF16]](s32), [[DEF16]](s32)
  ; CHECK-NEXT:   [[UV68:%[0-9]+]]:_(s32), [[UV69:%[0-9]+]]:_(s32), [[UV70:%[0-9]+]]:_(s32), [[UV71:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF17:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR18:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV68]](s32), [[UV69]](s32), [[UV70]](s32), [[UV71]](s32), [[DEF17]](s32), [[DEF17]](s32), [[DEF17]](s32), [[DEF17]](s32)
  ; CHECK-NEXT:   [[UV72:%[0-9]+]]:_(s32), [[UV73:%[0-9]+]]:_(s32), [[UV74:%[0-9]+]]:_(s32), [[UV75:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF18:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR19:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV72]](s32), [[UV73]](s32), [[UV74]](s32), [[UV75]](s32), [[DEF18]](s32), [[DEF18]](s32), [[DEF18]](s32), [[DEF18]](s32)
  ; CHECK-NEXT:   [[UV76:%[0-9]+]]:_(s32), [[UV77:%[0-9]+]]:_(s32), [[UV78:%[0-9]+]]:_(s32), [[UV79:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF19:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR20:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV76]](s32), [[UV77]](s32), [[UV78]](s32), [[UV79]](s32), [[DEF19]](s32), [[DEF19]](s32), [[DEF19]](s32), [[DEF19]](s32)
  ; CHECK-NEXT:   [[UV80:%[0-9]+]]:_(s32), [[UV81:%[0-9]+]]:_(s32), [[UV82:%[0-9]+]]:_(s32), [[UV83:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF20:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR21:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV80]](s32), [[UV81]](s32), [[UV82]](s32), [[UV83]](s32), [[DEF20]](s32), [[DEF20]](s32), [[DEF20]](s32), [[DEF20]](s32)
  ; CHECK-NEXT:   [[UV84:%[0-9]+]]:_(s32), [[UV85:%[0-9]+]]:_(s32), [[UV86:%[0-9]+]]:_(s32), [[UV87:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF21:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR22:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV84]](s32), [[UV85]](s32), [[UV86]](s32), [[UV87]](s32), [[DEF21]](s32), [[DEF21]](s32), [[DEF21]](s32), [[DEF21]](s32)
  ; CHECK-NEXT:   [[UV88:%[0-9]+]]:_(s32), [[UV89:%[0-9]+]]:_(s32), [[UV90:%[0-9]+]]:_(s32), [[UV91:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF22:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR23:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV88]](s32), [[UV89]](s32), [[UV90]](s32), [[UV91]](s32), [[DEF22]](s32), [[DEF22]](s32), [[DEF22]](s32), [[DEF22]](s32)
  ; CHECK-NEXT:   [[UV92:%[0-9]+]]:_(s32), [[UV93:%[0-9]+]]:_(s32), [[UV94:%[0-9]+]]:_(s32), [[UV95:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF23:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR24:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV92]](s32), [[UV93]](s32), [[UV94]](s32), [[UV95]](s32), [[DEF23]](s32), [[DEF23]](s32), [[DEF23]](s32), [[DEF23]](s32)
  ; CHECK-NEXT:   [[UV96:%[0-9]+]]:_(s32), [[UV97:%[0-9]+]]:_(s32), [[UV98:%[0-9]+]]:_(s32), [[UV99:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF24:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR25:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV96]](s32), [[UV97]](s32), [[UV98]](s32), [[UV99]](s32), [[DEF24]](s32), [[DEF24]](s32), [[DEF24]](s32), [[DEF24]](s32)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR25]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into stack - 32)
  ; CHECK-NEXT:   [[UV100:%[0-9]+]]:_(s32), [[UV101:%[0-9]+]]:_(s32), [[UV102:%[0-9]+]]:_(s32), [[UV103:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x s32>)
  ; CHECK-NEXT:   [[DEF25:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR26:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[UV100]](s32), [[UV101]](s32), [[UV102]](s32), [[UV103]](s32), [[DEF25]](s32), [[DEF25]](s32), [[DEF25]](s32), [[DEF25]](s32)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR26]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into stack - 64)
  ; CHECK-NEXT:   $wl0 = COPY [[BUILD_VECTOR1]](<8 x s32>)
  ; CHECK-NEXT:   $wl2 = COPY [[BUILD_VECTOR2]](<8 x s32>)
  ; CHECK-NEXT:   $wl4 = COPY [[BUILD_VECTOR3]](<8 x s32>)
  ; CHECK-NEXT:   $wl6 = COPY [[BUILD_VECTOR4]](<8 x s32>)
  ; CHECK-NEXT:   $wl8 = COPY [[BUILD_VECTOR5]](<8 x s32>)
  ; CHECK-NEXT:   $wl10 = COPY [[BUILD_VECTOR6]](<8 x s32>)
  ; CHECK-NEXT:   $wl1 = COPY [[BUILD_VECTOR7]](<8 x s32>)
  ; CHECK-NEXT:   $wl3 = COPY [[BUILD_VECTOR8]](<8 x s32>)
  ; CHECK-NEXT:   $wl5 = COPY [[BUILD_VECTOR9]](<8 x s32>)
  ; CHECK-NEXT:   $wl7 = COPY [[BUILD_VECTOR10]](<8 x s32>)
  ; CHECK-NEXT:   $wl9 = COPY [[BUILD_VECTOR11]](<8 x s32>)
  ; CHECK-NEXT:   $wl11 = COPY [[BUILD_VECTOR12]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[BUILD_VECTOR13]](<8 x s32>)
  ; CHECK-NEXT:   $wh2 = COPY [[BUILD_VECTOR14]](<8 x s32>)
  ; CHECK-NEXT:   $wh4 = COPY [[BUILD_VECTOR15]](<8 x s32>)
  ; CHECK-NEXT:   $wh6 = COPY [[BUILD_VECTOR16]](<8 x s32>)
  ; CHECK-NEXT:   $wh8 = COPY [[BUILD_VECTOR17]](<8 x s32>)
  ; CHECK-NEXT:   $wh10 = COPY [[BUILD_VECTOR18]](<8 x s32>)
  ; CHECK-NEXT:   $wh1 = COPY [[BUILD_VECTOR19]](<8 x s32>)
  ; CHECK-NEXT:   $wh3 = COPY [[BUILD_VECTOR20]](<8 x s32>)
  ; CHECK-NEXT:   $wh5 = COPY [[BUILD_VECTOR21]](<8 x s32>)
  ; CHECK-NEXT:   $wh7 = COPY [[BUILD_VECTOR22]](<8 x s32>)
  ; CHECK-NEXT:   $wh9 = COPY [[BUILD_VECTOR23]](<8 x s32>)
  ; CHECK-NEXT:   $wh11 = COPY [[BUILD_VECTOR24]](<8 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v4float, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v4float(<4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer,
                            <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer,
                            <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer,
                            <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer, <4 x float> zeroinitializer,
                            <4 x float> zeroinitializer, <4 x float> zeroinitializer)
  ret void
}
