; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -O2 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o - 2>&1 | FileCheck %s

; TCO expected, caller & callee have same number of arguments & same return type & no arguments are passed over stack
define dso_local noundef i32 @_Z5test0ii(i32 noundef %a, i32 noundef %b) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test0ii
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r1 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   $r2 = COPY [[COPY1]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z4funcii, csr_aie2p, implicit $r1, implicit $r2
entry:
  %call = tail call noundef i32 @_Z4funcii(i32 noundef %a, i32 noundef %b)
  ret i32 %call
}

declare dso_local noundef i32 @_Z4funcii(i32 noundef, i32 noundef) local_unnamed_addr

; TCO expected, callee has one extra arguments & same return type & no arguments are passed over stack
define dso_local noundef i32 @_Z5test1i(i32 noundef %a) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test1i
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[COPY]], [[C]]
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r1 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   $r2 = COPY [[ADD]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z4funcii, csr_aie2p, implicit $r1, implicit $r2
entry:
  %add = add nsw i32 %a, 10
  %call = tail call noundef i32 @_Z4funcii(i32 noundef %a, i32 noundef %add)
  ret i32 %call
}

; TCO expected, callee has one extra arguments & same return type & no arguments are passed over stack
; Also test the case where the caller has a pointer argument
define dso_local void @_Z5test2PPv(ptr nocapture readonly %args) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test2PPv
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load (p0) from %ir.args, align 4)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[LOAD]](p0) :: (load (s32) from %ir.0)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw nusw G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(p0) = G_LOAD [[PTR_ADD]](p0) :: (load (p0) from %ir.arrayidx1, align 4)
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[LOAD2]](p0) :: (load (s32) from %ir.2)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r1 = COPY [[LOAD1]](s32)
  ; CHECK-NEXT:   $r2 = COPY [[LOAD3]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z4funcii, csr_aie2p, implicit $r1, implicit $r2
entry:
  %0 = load ptr, ptr %args, align 4
  %1 = load i32, ptr %0, align 4
  %arrayidx1 = getelementptr inbounds i8, ptr %args, i20 4
  %2 = load ptr, ptr %arrayidx1, align 4
  %3 = load i32, ptr %2, align 4
  %call = tail call noundef i32 @_Z4funcii(i32 noundef %1, i32 noundef %3)
  ret void
}

; TCO expected, caller & callee have same number of arguments & same return type & 1 argument is passed over stack for both caller & callee and the same SF is used
; Caller and callee Stack Arg Area is Same
define dso_local noundef i32 @_Z5test3iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %a7) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test3iiiiiiii
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r3
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $r4
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $r5
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $r6
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $r7
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (s32) from %fixed-stack.1)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   G_STORE [[LOAD]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %fixed-stack.0, align 32)
  ; CHECK-NEXT:   $r1 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   $r2 = COPY [[COPY1]](s32)
  ; CHECK-NEXT:   $r3 = COPY [[COPY2]](s32)
  ; CHECK-NEXT:   $r4 = COPY [[COPY3]](s32)
  ; CHECK-NEXT:   $r5 = COPY [[COPY4]](s32)
  ; CHECK-NEXT:   $r6 = COPY [[COPY5]](s32)
  ; CHECK-NEXT:   $r7 = COPY [[COPY6]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z5func1iiiiiiii, csr_aie2p, implicit $r1, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit $r6, implicit $r7
entry:
  %call = tail call noundef i32 @_Z5func1iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %a7)
  ret i32 %call
}

declare dso_local noundef i32 @_Z5func1iiiiiiii(i32 noundef, i32 noundef, i32 noundef, i32 noundef, i32 noundef, i32 noundef, i32 noundef, i32 noundef) local_unnamed_addr

; TCO expected, caller & callee have same number of arguments & same return type & 2 argument is passed over stack for caller & 1 argument for callee and the same SF is used
; Caller has more Stack Arg Area comapred to callee
define dso_local noundef i32 @_Z5test4iiiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %a7, i32 noundef %a8) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test4iiiiiiiii
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r3
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $r4
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $r5
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $r6
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $r7
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (s32) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[LOAD1]], [[LOAD]]
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[FRAME_INDEX2]](p0) :: (store (s32) into %fixed-stack.0, align 32)
  ; CHECK-NEXT:   $r1 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   $r2 = COPY [[COPY1]](s32)
  ; CHECK-NEXT:   $r3 = COPY [[COPY2]](s32)
  ; CHECK-NEXT:   $r4 = COPY [[COPY3]](s32)
  ; CHECK-NEXT:   $r5 = COPY [[COPY4]](s32)
  ; CHECK-NEXT:   $r6 = COPY [[COPY5]](s32)
  ; CHECK-NEXT:   $r7 = COPY [[COPY6]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z5func1iiiiiiii, csr_aie2p, implicit $r1, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit $r6, implicit $r7
entry:
  %add = add nsw i32 %a8, %a7
  %call = tail call noundef i32 @_Z5func1iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %add)
  ret i32 %call
}

; TCO is NOT expected, caller & callee have same number of arguments & same return type & 0 argument is passed over stack for caller & 1 argument for callee
; Caller has less Stack Arg Area comapred to callee and thus TCO is not expected
; TODO : Extend TCO to support this case
define dso_local noundef i32 @_Z5test5iiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test5iiiiiii
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r3
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $r4
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $r5
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $r6
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $r7
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[COPY6]], [[C]]
  ; CHECK-NEXT:   ADJCALLSTACKUP 4, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -4
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY7]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[PTR_ADD]](p0) :: (store (s32) into stack - 4, basealign 32)
  ; CHECK-NEXT:   $r1 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   $r2 = COPY [[COPY1]](s32)
  ; CHECK-NEXT:   $r3 = COPY [[COPY2]](s32)
  ; CHECK-NEXT:   $r4 = COPY [[COPY3]](s32)
  ; CHECK-NEXT:   $r5 = COPY [[COPY4]](s32)
  ; CHECK-NEXT:   $r6 = COPY [[COPY5]](s32)
  ; CHECK-NEXT:   $r7 = COPY [[COPY6]](s32)
  ; CHECK-NEXT:   PseudoJL @_Z5func1iiiiiiii, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit $r6, implicit $r7, implicit-def $r0
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 4, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r0 = COPY [[COPY8]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %add = add nsw i32 %a6, 10
  %call = tail call noundef i32 @_Z5func1iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %add)
  ret i32 %call
}

; TCO is expected, make sure caller local alloc is destroyed before the callee is called as TCO
define dso_local noundef i32 @_Z12testFunctionv() local_unnamed_addr {
  ; CHECK-LABEL: name: _Z12testFunctionv
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 100
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r0 = COPY [[C]](s32)
  ; CHECK-NEXT:   PseudoJL @_Znwj, csr_aie2p, implicit-def $lr, implicit $r0, implicit-def $p0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[COPY]](p0) :: (volatile store (s32) into %ir.call)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (volatile load (s32) from %ir.call)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r1 = COPY [[LOAD]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z7TCOfunci, csr_aie2p, implicit $r1
entry:
  %call = tail call noalias nonnull dereferenceable(4) ptr @_Znwj(i32 noundef 4)
  store volatile i32 100, ptr %call, align 4
  %0 = load volatile i32, ptr %call, align 4
  %call1 = tail call noundef i32 @_Z7TCOfunci(i32 noundef %0)
  ret i32 %call1
}

declare dso_local nonnull ptr @_Znwj(i32 noundef) local_unnamed_addr
declare dso_local noundef i32 @_Z7TCOfunci(i32 noundef) local_unnamed_addr
