; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

; 256-bit vector types

declare void @callee_v8int32(<8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
                             <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
                             <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
                             <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>,
                             <8 x i32>)
define void @call_v8int32() {
  ; CHECK-LABEL: name: call_v8int32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into stack - 32)
  ; CHECK-NEXT:   $wl0 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl2 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl4 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl6 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl8 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl10 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl1 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl3 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl5 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl7 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl9 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl11 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh2 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh4 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh6 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh8 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh10 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh1 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh3 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh5 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh7 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh9 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh11 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v8int32, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v8int32(<8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer,
                            <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer,
                            <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer,
                            <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer, <8 x i32> zeroinitializer,
                            <8 x i32> zeroinitializer)
  ret void
}

declare void @callee_v16int16(<16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
                              <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
                              <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
                              <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>, <16 x i16>,
                              <16 x i16>)
define void @call_v16int16() {
  ; CHECK-LABEL: name: call_v16int16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
  ; CHECK-NEXT:   ADJCALLSTACKUP 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<16 x s16>), [[PTR_ADD]](p0) :: (store (<16 x s16>) into stack - 32)
  ; CHECK-NEXT:   $wl0 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl2 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl4 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl6 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl8 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl10 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl1 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl3 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl5 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl7 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl9 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wl11 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh0 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh2 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh4 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh6 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh8 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh10 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh1 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh3 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh5 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh7 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh9 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   $wh11 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v8int32, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v8int32(<16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer,
                            <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer,
                            <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer,
                            <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer,
                            <16 x i16> zeroinitializer)
  ret void
}

declare void @callee_v32int8(<32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
                             <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
                             <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
                             <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>, <32 x i8>,
                             <32 x i8>)
define void @call_v32int8() {
  ; CHECK-LABEL: name: call_v32int8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_BUILD_VECTOR [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8)
  ; CHECK-NEXT:   ADJCALLSTACKUP 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<32 x s8>), [[PTR_ADD]](p0) :: (store (<32 x s8>) into stack - 32)
  ; CHECK-NEXT:   $wl0 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl2 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl4 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl6 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl8 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl10 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl1 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl3 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl5 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl7 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl9 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wl11 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh0 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh2 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh4 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh6 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh8 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh10 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh1 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh3 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh5 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh7 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh9 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   $wh11 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   PseudoJL @callee_v8int32, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v8int32(<32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer,
                            <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer,
                            <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer,
                            <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer, <32 x i8> zeroinitializer,
                            <32 x i8> zeroinitializer)
  ret void
}

declare void @callee_v8float(<8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
                            <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
                            <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
                            <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>, <8 x float>,
                            <8 x float>)
define void @call_v8float() {
  ; CHECK-LABEL: name: call_v8float
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -32
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into stack - 32)
  ; CHECK-NEXT:   $wl0 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl2 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl4 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl6 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl8 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl10 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl1 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl3 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl5 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl7 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl9 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wl11 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh2 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh4 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh6 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh8 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh10 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh1 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh3 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh5 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh7 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh9 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   $wh11 = COPY [[BUILD_VECTOR]](<8 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v8float, csr_aie2p, implicit-def $lr, implicit $wl0, implicit $wl2, implicit $wl4, implicit $wl6, implicit $wl8, implicit $wl10, implicit $wl1, implicit $wl3, implicit $wl5, implicit $wl7, implicit $wl9, implicit $wl11, implicit $wh0, implicit $wh2, implicit $wh4, implicit $wh6, implicit $wh8, implicit $wh10, implicit $wh1, implicit $wh3, implicit $wh5, implicit $wh7, implicit $wh9, implicit $wh11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 32, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v8float(<8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer,
                          <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer,
                          <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer,
                          <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer, <8 x float> zeroinitializer,
                          <8 x float> zeroinitializer)
  ret void
}
