; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

declare inreg <4 x i64> @callee_v4int64()
define void @call_v4int64() {
  ; CHECK-LABEL: name: call_v4int64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL @callee_v4int64, csr_aie2p, implicit-def $lr, implicit-def $bmll0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[COPY]](<8 x s64>)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  %res = call inreg <4 x i64> @callee_v4int64()
  ret void
}

declare inreg <8 x i64> @callee_v8int64()
define void @call_v8int64() {
  ; CHECK-LABEL: name: call_v8int64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL @callee_v8int64, csr_aie2p, implicit-def $lr, implicit-def $bmll0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  %res = call inreg <8 x i64> @callee_v8int64()
  ret void
}

declare inreg <16 x i64> @callee_v16int64()
define void @call_v16int64() {
  ; CHECK-LABEL: name: call_v16int64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL @callee_v16int64, csr_aie2p, implicit-def $lr, implicit-def $cml0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  %res = call inreg <16 x i64>  @callee_v16int64()
  ret void
}

declare inreg <32 x i64> @callee_v32int64()
define void @call_v32int64() {
  ; CHECK-LABEL: name: call_v32int64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL @callee_v32int64, csr_aie2p, implicit-def $lr, implicit-def $dm0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  %res = call inreg <32 x i64> @callee_v32int64()
  ret void
}
