; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --print-fixed-stack
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o - 2>&1 | FileCheck %s

%struct.v64bfp16ebs16 = type <{ <64 x i8>, <8 x i8> }>
%struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>
%struct.v128bfp16ebs16 = type  <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>
%struct.v128bfp16ebs8 = type  <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>
%struct.fifo_state_t = type { <32 x i32>, i32, <16 x i32> }

define void @pass_v64bfp16ebs16(%struct.v64bfp16ebs16 %v1) {
  ; CHECK-LABEL: name: pass_v64bfp16ebs16
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v64bfp16ebs16_with_normal_vector(%struct.v64bfp16ebs16 %v1,<64 x i8> %vec1, <8 x i8> %vec2, %struct.v64bfp16ebs16 %v2) {
  ; CHECK-LABEL: name: pass_v64bfp16ebs16_with_normal_vector
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $l0, $x0, $x1, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $l0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v64bfp16ebs16_more_args(%struct.v64bfp16ebs16 %v1, %struct.v64bfp16ebs16 %v2, %struct.v64bfp16ebs16 %v3, %struct.v64bfp16ebs16 %v4, %struct.v64bfp16ebs16 %v5, %struct.v64bfp16ebs16 %v6, %struct.v64bfp16ebs16 %v7, %struct.v64bfp16ebs16 %v8, %struct.v64bfp16ebs16 %v9, %struct.v64bfp16ebs16 %v10, %struct.v64bfp16ebs16 %v11, %struct.v64bfp16ebs16 %v12) {
  ; CHECK-LABEL: name: pass_v64bfp16ebs16_more_args
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<64 x s8>) = COPY $x4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s8>) = COPY $e4
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<64 x s8>) = COPY $x5
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $e5
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<64 x s8>) = COPY $x6
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s8>) = COPY $e6
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<64 x s8>) = COPY $x7
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s8>) = COPY $e7
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<64 x s8>) = COPY $x8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s8>) = COPY $e8
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<64 x s8>) = COPY $x9
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s8>) = COPY $e9
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<64 x s8>) = COPY $x10
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<8 x s8>) = COPY $e10
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<64 x s8>) = COPY $x11
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<8 x s8>) = COPY $e11
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v64bfp16ebs16 @ret_v64bfp16ebs16(%struct.v64bfp16ebs16 %v1) {
  ; CHECK-LABEL: name: ret_v64bfp16ebs16
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e1, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<64 x s8>)
  ; CHECK-NEXT:   $e0 = COPY [[COPY1]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $e0
entry:
  ret %struct.v64bfp16ebs16 %v1
}

define void @pass_v64bfp16ebs8(%struct.v64bfp16ebs8 %v1) {
  ; CHECK-LABEL: name: pass_v64bfp16ebs8
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v64bfp16ebs8_more_args(%struct.v64bfp16ebs8 %v1, %struct.v64bfp16ebs8 %v2, %struct.v64bfp16ebs8 %v3, %struct.v64bfp16ebs8 %v4, %struct.v64bfp16ebs8 %v5, %struct.v64bfp16ebs8 %v6, %struct.v64bfp16ebs8 %v7, %struct.v64bfp16ebs8 %v8, %struct.v64bfp16ebs8 %v9, %struct.v64bfp16ebs8 %v10, %struct.v64bfp16ebs8 %v11) {
  ; CHECK-LABEL: name: pass_v64bfp16ebs8_more_args
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<64 x s8>) = COPY $x4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s8>) = COPY $e4
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<64 x s8>) = COPY $x5
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $e5
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<64 x s8>) = COPY $x6
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s8>) = COPY $e6
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<64 x s8>) = COPY $x7
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s8>) = COPY $e7
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<64 x s8>) = COPY $x8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s8>) = COPY $e8
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<64 x s8>) = COPY $x9
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s8>) = COPY $e9
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<64 x s8>) = COPY $x10
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<8 x s8>) = COPY $e10
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v64bfp16ebs8 @ret_v64bfp16ebs8(%struct.v64bfp16ebs8 %v1) {
  ; CHECK-LABEL: name: ret_v64bfp16ebs8
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e1, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<64 x s8>)
  ; CHECK-NEXT:   $e0 = COPY [[COPY1]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $e0
entry:
  ret %struct.v64bfp16ebs8 %v1
}

define void @pass_v128bfp16ebs16(%struct.v128bfp16ebs16 %v1) {
  ; CHECK-LABEL: name: pass_v128bfp16ebs16
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v128bfp16ebs16_more_args(%struct.v128bfp16ebs16 %v1, %struct.v128bfp16ebs16 %v2, %struct.v128bfp16ebs16 %v3, %struct.v128bfp16ebs16 %v4, %struct.v128bfp16ebs16 %v5, %struct.v128bfp16ebs16 %v6) {
  ; CHECK-LABEL: name: pass_v128bfp16ebs16_more_args
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<64 x s8>) = COPY $x4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<64 x s8>) = COPY $x5
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s8>) = COPY $e4
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $e5
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<64 x s8>) = COPY $x6
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<64 x s8>) = COPY $x7
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<8 x s8>) = COPY $e6
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s8>) = COPY $e7
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<64 x s8>) = COPY $x8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<64 x s8>) = COPY $x9
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s8>) = COPY $e8
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s8>) = COPY $e9
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<64 x s8>) = COPY $x10
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<64 x s8>) = COPY $x11
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<8 x s8>) = COPY $e10
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<8 x s8>) = COPY $e11
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v128bfp16ebs16 @ret_v128bfp16ebs16(%struct.v128bfp16ebs16 %v1) {
  ; CHECK-LABEL: name: ret_v128bfp16ebs16
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e2, $e3, $x2, $x3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<64 x s8>)
  ; CHECK-NEXT:   $x1 = COPY [[COPY1]](<64 x s8>)
  ; CHECK-NEXT:   $e0 = COPY [[COPY2]](<8 x s8>)
  ; CHECK-NEXT:   $e1 = COPY [[COPY3]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x1, implicit $e0, implicit $e1
entry:
  ret %struct.v128bfp16ebs16 %v1
}

define void @pass_v128bfp16ebs8(%struct.v128bfp16ebs8 %v1) {
  ; CHECK-LABEL: name: pass_v128bfp16ebs8
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v128bfp16ebs8_with_normal_vector(%struct.v128bfp16ebs8 %v1, <64 x i8> %vec1, <8 x i8> %vec2, %struct.v128bfp16ebs8 %v2) {
  ; CHECK-LABEL: name: pass_v128bfp16ebs8_with_normal_vector
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e4, $e5, $l0, $x0, $x1, $x2, $x4, $x5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s8>) = COPY $l0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<64 x s8>) = COPY $x4
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<64 x s8>) = COPY $x5
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s8>) = COPY $e4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s8>) = COPY $e5
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v128bfp16ebs8_more_args(%struct.v128bfp16ebs8 %v1, %struct.v128bfp16ebs8 %v2, %struct.v128bfp16ebs8 %v3, %struct.v128bfp16ebs8 %v4, %struct.v128bfp16ebs8 %v5, %struct.v128bfp16ebs8 %v6) {
  ; CHECK-LABEL: name: pass_v128bfp16ebs8_more_args
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<64 x s8>) = COPY $x4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<64 x s8>) = COPY $x5
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s8>) = COPY $e4
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $e5
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<64 x s8>) = COPY $x6
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<64 x s8>) = COPY $x7
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<8 x s8>) = COPY $e6
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s8>) = COPY $e7
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<64 x s8>) = COPY $x8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<64 x s8>) = COPY $x9
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s8>) = COPY $e8
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s8>) = COPY $e9
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<64 x s8>) = COPY $x10
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<64 x s8>) = COPY $x11
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<8 x s8>) = COPY $e10
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<8 x s8>) = COPY $e11
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v128bfp16ebs8 @ret_v128bfp16ebs8(%struct.v128bfp16ebs8 %v1) {
  ; CHECK-LABEL: name: ret_v128bfp16ebs8
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e2, $e3, $x2, $x3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<64 x s8>)
  ; CHECK-NEXT:   $x1 = COPY [[COPY1]](<64 x s8>)
  ; CHECK-NEXT:   $e0 = COPY [[COPY2]](<8 x s8>)
  ; CHECK-NEXT:   $e1 = COPY [[COPY3]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x1, implicit $e0, implicit $e1
entry:
  ret %struct.v128bfp16ebs8 %v1
}

define void @pass_v128bfp16ebs8_stack(<128 x i8> %vec1,<128 x i8> %vec2,<128 x i8> %vec3,<128 x i8> %vec4, %struct.v128bfp16ebs8 %v1,  %struct.v128bfp16ebs8 %v2,  %struct.v128bfp16ebs8 %v3) {
  ; CHECK-LABEL: name: pass_v128bfp16ebs8_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -192, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $x0, $x1, $x2, $x3, $y2, $y3, $y4, $y5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<128 x s8>) = COPY $y3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<128 x s8>) = COPY $y4
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<128 x s8>) = COPY $y5
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.3)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.1, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v128bfp16ebs8 @ret_v128bfp16ebs8_stack(<128 x i8> %vec1,<128 x i8> %vec2,<128 x i8> %vec3,<128 x i8> %vec4, %struct.v128bfp16ebs8 %v1,  %struct.v128bfp16ebs8 %v2,  %struct.v128bfp16ebs8 %v3) {
  ; CHECK-LABEL: name: ret_v128bfp16ebs8_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -248, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -256, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -320, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -384, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -192, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e2, $e3, $x2, $x3, $y2, $y3, $y4, $y5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<128 x s8>) = COPY $y3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<128 x s8>) = COPY $y4
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<128 x s8>) = COPY $y5
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.7)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.5, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.3)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.1, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.0)
  ; CHECK-NEXT:   $x0 = COPY [[LOAD]](<64 x s8>)
  ; CHECK-NEXT:   $x1 = COPY [[LOAD1]](<64 x s8>)
  ; CHECK-NEXT:   $e0 = COPY [[LOAD2]](<8 x s8>)
  ; CHECK-NEXT:   $e1 = COPY [[LOAD3]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x1, implicit $e0, implicit $e1
entry:
  ret %struct.v128bfp16ebs8 %v2
}

define void @pass_v64bfp16ebs8_stack( %struct.v64bfp16ebs8 %v1,  %struct.v64bfp16ebs8 %v2,  %struct.v64bfp16ebs8 %v3, %struct.v64bfp16ebs8 %v4,  %struct.v64bfp16ebs8 %v5,  %struct.v64bfp16ebs8 %v6, %struct.v64bfp16ebs8 %v7,  %struct.v64bfp16ebs8 %v8,  %struct.v64bfp16ebs8 %v9, %struct.v64bfp16ebs8 %v10,  %struct.v64bfp16ebs8 %v11,  %struct.v64bfp16ebs8 %v12,  %struct.v64bfp16ebs8 %v13) {

  ; CHECK-LABEL: name: pass_v64bfp16ebs8_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<64 x s8>) = COPY $x4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s8>) = COPY $e4
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<64 x s8>) = COPY $x5
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $e5
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<64 x s8>) = COPY $x6
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s8>) = COPY $e6
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<64 x s8>) = COPY $x7
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s8>) = COPY $e7
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<64 x s8>) = COPY $x8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s8>) = COPY $e8
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<64 x s8>) = COPY $x9
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s8>) = COPY $e9
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<64 x s8>) = COPY $x10
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<8 x s8>) = COPY $e10
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<64 x s8>) = COPY $x11
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<8 x s8>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.1)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v64bfp16ebs8 @ret_v64bfp16ebs8_stack( %struct.v64bfp16ebs8 %v1,  %struct.v64bfp16ebs8 %v2,  %struct.v64bfp16ebs8 %v3, %struct.v64bfp16ebs8 %v4,  %struct.v64bfp16ebs8 %v5,  %struct.v64bfp16ebs8 %v6, %struct.v64bfp16ebs8 %v7,  %struct.v64bfp16ebs8 %v8,  %struct.v64bfp16ebs8 %v9, %struct.v64bfp16ebs8 %v10,  %struct.v64bfp16ebs8 %v11,  %struct.v64bfp16ebs8 %v12,  %struct.v64bfp16ebs8 %v13) {
  ; CHECK-LABEL: name: ret_v64bfp16ebs8_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -192, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -256, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e2
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s8>) = COPY $x3
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s8>) = COPY $e3
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<64 x s8>) = COPY $x4
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $e4
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<64 x s8>) = COPY $x5
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s8>) = COPY $e5
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<64 x s8>) = COPY $x6
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $e6
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<64 x s8>) = COPY $x7
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s8>) = COPY $e7
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<64 x s8>) = COPY $x8
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s8>) = COPY $e8
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<64 x s8>) = COPY $x9
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s8>) = COPY $e9
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<64 x s8>) = COPY $x10
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s8>) = COPY $e10
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<64 x s8>) = COPY $x11
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<8 x s8>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.3)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.2, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<64 x s8>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<64 x s8>) from %fixed-stack.1)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   $x0 = COPY [[LOAD]](<64 x s8>)
  ; CHECK-NEXT:   $e0 = COPY [[LOAD1]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $e0
entry:
  ret  %struct.v64bfp16ebs8 %v12
}

declare %struct.v64bfp16ebs8 @callee_v64bfp16ebs8e()
define void @call_v64bfp16ebs8() {
  ; CHECK-LABEL: name: call_v64bfp16ebs8
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL @callee_v64bfp16ebs8e, csr_aie2p, implicit-def $lr, implicit-def $x0, implicit-def $e0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %res = call %struct.v64bfp16ebs8 @callee_v64bfp16ebs8e()
  ret void
}

declare %struct.v128bfp16ebs8 @callee_v128bfp16ebs8e()
define void @call_v128bfp16ebs8() {
  ; CHECK-LABEL: name: call_v128bfp16ebs8
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL @callee_v128bfp16ebs8e, csr_aie2p, implicit-def $lr, implicit-def $x0, implicit-def $x1, implicit-def $e0, implicit-def $e1
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $e0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $e1
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %res = call %struct.v128bfp16ebs8 @callee_v128bfp16ebs8e()
  ret void
}

define void @pass_fifo_state_t(%struct.fifo_state_t %v1) {
  ; CHECK-LABEL: name: pass_fifo_state_t
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r0, $x0, $y2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.fifo_state_t @ret_fifo_state_t(%struct.fifo_state_t %v1) {
  ; CHECK-LABEL: name: ret_fifo_state_t
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $x2, $y3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y3
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   $y2 = COPY [[COPY]](<32 x s32>)
  ; CHECK-NEXT:   $r0 = COPY [[COPY1]](s32)
  ; CHECK-NEXT:   $x0 = COPY [[COPY2]](<16 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $y2, implicit $r0, implicit $x0
entry:
  ret %struct.fifo_state_t %v1
}

declare %struct.fifo_state_t @callee_fifo_state_t()
define void @call_fifo_state_t() {
  ; CHECK-LABEL: name: call_fifo_state_t
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL @callee_fifo_state_t, csr_aie2p, implicit-def $lr, implicit-def $y2, implicit-def $r0, implicit-def $x0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %res = call %struct.fifo_state_t @callee_fifo_state_t()
  ret void
}

define void @pass_fifo_state_t_stack(%struct.fifo_state_t %v1, %struct.fifo_state_t %v2, %struct.fifo_state_t %v3, %struct.fifo_state_t %v4) {
  ; CHECK-LABEL: name: pass_fifo_state_t_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -128, size: 128, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r0, $r1, $r2, $r3, $x0, $x1, $x2, $x10, $y2, $y3, $y4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<32 x s32>) = COPY $y3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<32 x s32>) = COPY $y4
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<16 x s32>) = COPY $x10
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<32 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<32 x s32>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(s32) = COPY $r3
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<16 x s32>) = COPY $x1
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}
