; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --print-fixed-stack
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s


define void @callee_v16int32(<16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg,
  ; CHECK-LABEL: name: callee_v16int32
  ; CHECK: fixedStack:
  ; CHECK: bb.1 (%ir-block.21):
  ; CHECK-NEXT:   liveins: $bmhh0, $bmhh1, $bmhh2, $bmhh3, $bmhh4, $bmhl0, $bmhl1, $bmhl2, $bmhl3, $bmhl4, $bmlh0, $bmlh1, $bmlh2, $bmlh3, $bmlh4, $bmll0, $bmll1, $bmll2, $bmll3, $bmll4, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $bmll0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $bmll1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $bmll2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $bmll3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<16 x s32>) = COPY $bmll4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<16 x s32>) = COPY $bmhl0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s32>) = COPY $bmhl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<16 x s32>) = COPY $bmhl2
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<16 x s32>) = COPY $bmhl3
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<16 x s32>) = COPY $bmhl4
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<16 x s32>) = COPY $bmlh0
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<16 x s32>) = COPY $bmlh1
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s32>) = COPY $bmlh2
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<16 x s32>) = COPY $bmlh3
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<16 x s32>) = COPY $bmlh4
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<16 x s32>) = COPY $bmhh0
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<16 x s32>) = COPY $bmhh1
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<16 x s32>) = COPY $bmhh2
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<16 x s32>) = COPY $bmhh3
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<16 x s32>) = COPY $bmhh4
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   PseudoRET implicit $lr
                             <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg,
                             <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg, <16 x i32> inreg,
                             <16 x i32> inreg, <16 x i32> inreg, <16 x i32>) {
  ret void
}

define void @callee_v32int32(<32 x i32> inreg, <32 x i32> inreg, <32 x i32> inreg, <32 x i32> inreg, <32 x i32> inreg, <32 x i32> inreg,
  ; CHECK-LABEL: name: callee_v32int32
  ; CHECK: fixedStack:
  ; CHECK: bb.1 (%ir-block.11):
  ; CHECK-NEXT:   liveins: $cmh0, $cmh1, $cmh2, $cmh3, $cmh4, $cml0, $cml1, $cml2, $cml3, $cml4, $y2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $cml0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<32 x s32>) = COPY $cml1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<32 x s32>) = COPY $cml2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<32 x s32>) = COPY $cml3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<32 x s32>) = COPY $cml4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<32 x s32>) = COPY $cmh0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<32 x s32>) = COPY $cmh1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<32 x s32>) = COPY $cmh2
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<32 x s32>) = COPY $cmh3
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<32 x s32>) = COPY $cmh4
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<32 x s32>) = COPY $y2
  ; CHECK-NEXT:   PseudoRET implicit $lr
                             <32 x i32> inreg, <32 x i32> inreg, <32 x i32> inreg,
                             <32 x i32> inreg, <32 x i32>) {
  ret void
}

define void @callee_v64int32(<64 x i32> inreg, <64 x i32> inreg, <64 x i32> inreg, <64 x i32> inreg, <64 x i32> inreg,
  ; CHECK-LABEL: name: callee_v64int32
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -256, size: 256, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1 (%ir-block.6):
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $dm3, $dm4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s32>) = COPY $dm1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<64 x s32>) = COPY $dm2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<64 x s32>) = COPY $dm3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s32>) = COPY $dm4
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<64 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<64 x s32>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   PseudoRET implicit $lr
                             <64 x i32>) {
  ret void
}
