; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

; 512-bit vector types

declare void @callee_v16int32(<16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>,
                              <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>,
                              <16 x i32>)
define void @call_v16int32() {
  ; CHECK-LABEL: name: call_v16int32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<16 x s32>), [[PTR_ADD]](p0) :: (store (<16 x s32>) into stack - 64, align 32)
  ; CHECK-NEXT:   $x0 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x2 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x4 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x6 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x8 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x10 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x1 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x3 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x5 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x7 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x9 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x11 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v16int32, csr_aie2p, implicit-def $lr, implicit $x0, implicit $x2, implicit $x4, implicit $x6, implicit $x8, implicit $x10, implicit $x1, implicit $x3, implicit $x5, implicit $x7, implicit $x9, implicit $x11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v16int32(<16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer,
                             <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <16 x i32> zeroinitializer,
                             <16 x i32> zeroinitializer)
  ret void
}

declare void @callee_v32int16(<32 x i16>, <32 x i16>, <32 x i16>, <32 x i16>, <32 x i16>, <32 x i16>,
                              <32 x i16>, <32 x i16>, <32 x i16>, <32 x i16>, <32 x i16>, <32 x i16>,
                              <32 x i16>)
define void @call_v32int16() {
  ; CHECK-LABEL: name: call_v32int16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<32 x s16>), [[PTR_ADD]](p0) :: (store (<32 x s16>) into stack - 64, align 32)
  ; CHECK-NEXT:   $x0 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x2 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x4 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x6 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x8 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x10 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x1 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x3 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x5 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x7 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x9 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   $x11 = COPY [[BUILD_VECTOR]](<32 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v32int16, csr_aie2p, implicit-def $lr, implicit $x0, implicit $x2, implicit $x4, implicit $x6, implicit $x8, implicit $x10, implicit $x1, implicit $x3, implicit $x5, implicit $x7, implicit $x9, implicit $x11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v32int16(<32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer,
                             <32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer, <32 x i16> zeroinitializer,
                             <32 x i16> zeroinitializer)
  ret void
}

declare void @callee_v64int8(<64 x i8>, <64 x i8>, <64 x i8>, <64 x i8>, <64 x i8>, <64 x i8>,
                             <64 x i8>, <64 x i8>, <64 x i8>, <64 x i8>, <64 x i8>, <64 x i8>,
                             <64 x i8>)
define void @call_v64int8() {
  ; CHECK-LABEL: name: call_v64int8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_BUILD_VECTOR [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<64 x s8>), [[PTR_ADD]](p0) :: (store (<64 x s8>) into stack - 64, align 32)
  ; CHECK-NEXT:   $x0 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x2 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x4 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x6 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x8 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x10 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x1 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x3 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x5 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x7 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x9 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   $x11 = COPY [[BUILD_VECTOR]](<64 x s8>)
  ; CHECK-NEXT:   PseudoJL @callee_v64int8, csr_aie2p, implicit-def $lr, implicit $x0, implicit $x2, implicit $x4, implicit $x6, implicit $x8, implicit $x10, implicit $x1, implicit $x3, implicit $x5, implicit $x7, implicit $x9, implicit $x11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v64int8(<64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer,
                            <64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer, <64 x i8> zeroinitializer,
                            <64 x i8> zeroinitializer)
  ret void
}

declare void @callee_v16float(<16 x float>, <16 x float>, <16 x float>, <16 x float>, <16 x float>, <16 x float>,
                              <16 x float>, <16 x float>, <16 x float>, <16 x float>, <16 x float>, <16 x float>,
                              <16 x float>)
define void @call_v16float() {
  ; CHECK-LABEL: name: call_v16float
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<16 x s32>), [[PTR_ADD]](p0) :: (store (<16 x s32>) into stack - 64, align 32)
  ; CHECK-NEXT:   $x0 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x2 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x4 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x6 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x8 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x10 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x1 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x3 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x5 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x7 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x9 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $x11 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v16float, csr_aie2p, implicit-def $lr, implicit $x0, implicit $x2, implicit $x4, implicit $x6, implicit $x8, implicit $x10, implicit $x1, implicit $x3, implicit $x5, implicit $x7, implicit $x9, implicit $x11
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 64, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v16float(<16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer,
                             <16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer, <16 x float> zeroinitializer,
                             <16 x float> zeroinitializer)
  ret void
}
