; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

declare void @callee_v16float(<16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg,
                             <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg,
                             <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg, <16 x float> inreg,
                             <16 x float> inreg)
define void @call_v16float() {
  ; CHECK-LABEL: name: call_v16float
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $bmll0 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmll1 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmll2 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmll3 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmll4 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhl0 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhl1 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhl2 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhl3 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhl4 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmlh0 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmlh1 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmlh2 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmlh3 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmlh4 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhh0 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhh1 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhh2 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   $bmhh3 = COPY [[BUILD_VECTOR]](<16 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v16float, csr_aie2p, implicit-def $lr, implicit $bmll0, implicit $bmll1, implicit $bmll2, implicit $bmll3, implicit $bmll4, implicit $bmhl0, implicit $bmhl1, implicit $bmhl2, implicit $bmhl3, implicit $bmhl4, implicit $bmlh0, implicit $bmlh1, implicit $bmlh2, implicit $bmlh3, implicit $bmlh4, implicit $bmhh0, implicit $bmhh1, implicit $bmhh2, implicit $bmhh3
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v16float(<16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer,
                            <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer,
                            <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer, <16 x float> inreg zeroinitializer,
                            <16 x float> inreg zeroinitializer)
  ret void
}

declare void @callee_v32float(<32 x float> inreg, <32 x float> inreg, <32 x float> inreg, <32 x float> inreg, <32 x float> inreg, <32 x float> inreg,
                             <32 x float> inreg, <32 x float> inreg, <32 x float> inreg,
                             <32 x float> inreg)
define void @call_v32float() {
  ; CHECK-LABEL: name: call_v32float
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $cml0 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cml1 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cml2 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cml3 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cml4 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cmh0 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cmh1 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cmh2 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cmh3 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   $cmh4 = COPY [[BUILD_VECTOR]](<32 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v32float, csr_aie2p, implicit-def $lr, implicit $cml0, implicit $cml1, implicit $cml2, implicit $cml3, implicit $cml4, implicit $cmh0, implicit $cmh1, implicit $cmh2, implicit $cmh3, implicit $cmh4
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v32float(<32 x float> inreg zeroinitializer, <32 x float> inreg zeroinitializer, <32 x float> inreg zeroinitializer, <32 x float> inreg zeroinitializer, <32 x float> inreg zeroinitializer, <32 x float> inreg zeroinitializer,
                            <32 x float> inreg zeroinitializer, <32 x float> inreg zeroinitializer, <32 x float> inreg zeroinitializer,
                            <32 x float> inreg zeroinitializer)
  ret void
}

; Add check for
declare void @callee_v64float(<64 x float> inreg, <64 x float> inreg, <64 x float> inreg,
                              <64 x float> inreg, <64 x float> inreg)
define void @call_v64float() {
  ; CHECK-LABEL: name: call_v64float
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32), [[C]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $dm0 = COPY [[BUILD_VECTOR]](<64 x s32>)
  ; CHECK-NEXT:   $dm1 = COPY [[BUILD_VECTOR]](<64 x s32>)
  ; CHECK-NEXT:   $dm2 = COPY [[BUILD_VECTOR]](<64 x s32>)
  ; CHECK-NEXT:   $dm3 = COPY [[BUILD_VECTOR]](<64 x s32>)
  ; CHECK-NEXT:   $dm4 = COPY [[BUILD_VECTOR]](<64 x s32>)
  ; CHECK-NEXT:   PseudoJL @callee_v64float, csr_aie2p, implicit-def $lr, implicit $dm0, implicit $dm1, implicit $dm2, implicit $dm3, implicit $dm4
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
  call void @callee_v64float(<64 x float> inreg zeroinitializer, <64 x float> inreg zeroinitializer, <64 x float>  inreg zeroinitializer,
                            <64 x float> inreg zeroinitializer, <64 x float> inreg zeroinitializer)
  ret void
}

