; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2P
; RUN: llc -mtriple=aie2p -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

; 32-bit vector types



define <2 x i16> @callee_v2int16() {
  ; CHECK-LABEL: name: callee_v2int16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[BUILD_VECTOR]](<2 x s16>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ret <2 x i16> zeroinitializer
}

define <4 x i8> @callee_v4int8() {
  ; CHECK-LABEL: name: callee_v4int8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x s8>) = G_BUILD_VECTOR [[C]](s8), [[C]](s8), [[C]](s8), [[C]](s8)
  ; CHECK-NEXT:   $r0 = COPY [[BUILD_VECTOR]](<4 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ret <4 x i8> zeroinitializer
}

define <2 x bfloat> @callee_v2bf16() {
  ; CHECK-LABEL: name: callee_v2bf16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s16) = G_FCONSTANT bfloat 0xR0000
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[BUILD_VECTOR]](<2 x s16>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ret <2 x bfloat> zeroinitializer
}
