# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

# 256-bit vectors
---
name:            test_v32s8_v16s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s8_v16s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<64 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF2]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<32 x s8>)
    %0:_(<16 x s8>) = G_IMPLICIT_DEF
    %1:_(<16 x s8>) = G_IMPLICIT_DEF
    %2:_(<32 x s8>) = G_CONCAT_VECTORS %0(<16 x s8>), %1(<16 x s8>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v16s16_v8s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v16s16_v8s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<32 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF2]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<16 x s16>)
    %0:_(<8 x s16>) = G_IMPLICIT_DEF
    %1:_(<8 x s16>) = G_IMPLICIT_DEF
    %2:_(<16 x s16>) = G_CONCAT_VECTORS %0(<8 x s16>), %1(<8 x s16>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v8s32_v4s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v8s32_v4s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<4 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF2]], [[AIE_PAD_VECTOR_UNDEF1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[AIE_PAD_VECTOR_UNDEF]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    %1:_(<4 x s32>) = G_IMPLICIT_DEF
    %2:_(<8 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>)
    PseudoRET implicit $lr, implicit %2
...

# 512-bit vectors
---
name:            test_v64s8_v32s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s8_v32s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s8>)
    %0:_(<32 x s8>) = G_IMPLICIT_DEF
    %1:_(<32 x s8>) = G_IMPLICIT_DEF
    %2:_(<64 x s8>) = G_CONCAT_VECTORS %0(<32 x s8>), %1(<32 x s8>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v64s8_v16s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s8_v16s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<64 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF4]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF2]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF3]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF4]], [[BITCAST4]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[BITCAST3]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST5]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<32 x s8>), [[AIE_UNPAD_VECTOR1]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s8>)
    %0:_(<16 x s8>) = G_IMPLICIT_DEF
    %1:_(<16 x s8>) = G_IMPLICIT_DEF
    %2:_(<16 x s8>) = G_IMPLICIT_DEF
    %3:_(<16 x s8>) = G_IMPLICIT_DEF
    %4:_(<64 x s8>) = G_CONCAT_VECTORS %0(<16 x s8>), %1(<16 x s8>), %2(<16 x s8>), %3(<16 x s8>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v32s16_v16s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s16_v16s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s16>)
    %0:_(<16 x s16>) = G_IMPLICIT_DEF
    %1:_(<16 x s16>) = G_IMPLICIT_DEF
    %2:_(<32 x s16>) = G_CONCAT_VECTORS %0(<16 x s16>), %1(<16 x s16>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v32s16_v8s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s16_v8s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<32 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF4]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF2]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF3]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF4]], [[BITCAST4]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[BITCAST3]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST5]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<16 x s16>), [[AIE_UNPAD_VECTOR1]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s16>)
    %0:_(<8 x s16>) = G_IMPLICIT_DEF
    %1:_(<8 x s16>) = G_IMPLICIT_DEF
    %2:_(<8 x s16>) = G_IMPLICIT_DEF
    %3:_(<8 x s16>) = G_IMPLICIT_DEF
    %4:_(<32 x s16>) = G_CONCAT_VECTORS %0(<8 x s16>), %1(<8 x s16>), %2(<8 x s16>), %3(<8 x s16>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v16s32_v8s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v16s32_v8s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<8 x s32>) = G_IMPLICIT_DEF
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v16s32_v4s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v16s32_v4s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<4 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF4]], [[AIE_PAD_VECTOR_UNDEF1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[AIE_PAD_VECTOR_UNDEF]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF4]], [[AIE_PAD_VECTOR_UNDEF3]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[AIE_PAD_VECTOR_UNDEF2]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[AIE_UNPAD_VECTOR1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    %1:_(<4 x s32>) = G_IMPLICIT_DEF
    %2:_(<4 x s32>) = G_IMPLICIT_DEF
    %3:_(<4 x s32>) = G_IMPLICIT_DEF
    %4:_(<16 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>), %2(<4 x s32>), %3(<4 x s32>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v8s64_4s64
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v8s64_4s64
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[DEF1]](<4 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<8 x s64>)
    %0:_(<4 x s64>) = G_IMPLICIT_DEF
    %1:_(<4 x s64>) = G_IMPLICIT_DEF
    %2:_(<8 x s64>) = G_CONCAT_VECTORS %0(<4 x s64>), %1(<4 x s64>)
    PseudoRET implicit $lr, implicit %2
...

# 1024-bit vectors
---
name:            test_v128s8_v64s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v128s8_v64s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[DEF]](<64 x s8>), [[DEF1]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<128 x s8>)
    %0:_(<64 x s8>) = G_IMPLICIT_DEF
    %1:_(<64 x s8>) = G_IMPLICIT_DEF
    %2:_(<128 x s8>) = G_CONCAT_VECTORS %0(<64 x s8>), %1(<64 x s8>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v128s8_v32s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v128s8_v32s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF2]](<32 x s8>), [[DEF3]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<64 x s8>), [[CONCAT_VECTORS1]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<128 x s8>)
    %0:_(<32 x s8>) = G_IMPLICIT_DEF
    %1:_(<32 x s8>) = G_IMPLICIT_DEF
    %2:_(<32 x s8>) = G_IMPLICIT_DEF
    %3:_(<32 x s8>) = G_IMPLICIT_DEF
    %4:_(<128 x s8>) = G_CONCAT_VECTORS %0(<32 x s8>), %1(<32 x s8>), %2(<32 x s8>), %3(<32 x s8>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v128s8_v16s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v128s8_v16s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<64 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF2]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF3]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST4]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[BITCAST3]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST5]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF4:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF4]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF5:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF5]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST6:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF4]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST7:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF5]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST7]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT2]], [[BITCAST6]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST8:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL2]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST8]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF6:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF6]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF7:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF7]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST9:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF6]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST10:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF7]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST10]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT3]], [[BITCAST9]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST11:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL3]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR3:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST11]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<32 x s8>), [[AIE_UNPAD_VECTOR1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR2]](<32 x s8>), [[AIE_UNPAD_VECTOR3]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<64 x s8>), [[CONCAT_VECTORS1]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<128 x s8>)
    %0:_(<16 x s8>) = G_IMPLICIT_DEF
    %1:_(<16 x s8>) = G_IMPLICIT_DEF
    %2:_(<16 x s8>) = G_IMPLICIT_DEF
    %3:_(<16 x s8>) = G_IMPLICIT_DEF
    %4:_(<16 x s8>) = G_IMPLICIT_DEF
    %5:_(<16 x s8>) = G_IMPLICIT_DEF
    %6:_(<16 x s8>) = G_IMPLICIT_DEF
    %7:_(<16 x s8>) = G_IMPLICIT_DEF
    %8:_(<128 x s8>) = G_CONCAT_VECTORS %0(<16 x s8>), %1(<16 x s8>), %2(<16 x s8>), %3(<16 x s8>), %4(<16 x s8>), %5(<16 x s8>), %6(<16 x s8>), %7(<16 x s8>)
    PseudoRET implicit $lr, implicit %8
...

---
name:            test_v64s16_v32s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s16_v32s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[DEF]](<32 x s16>), [[DEF1]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s16>)
    %0:_(<32 x s16>) = G_IMPLICIT_DEF
    %1:_(<32 x s16>) = G_IMPLICIT_DEF
    %2:_(<64 x s16>) = G_CONCAT_VECTORS %0(<32 x s16>), %1(<32 x s16>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v64s16_v16s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s16_v16s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF2]](<16 x s16>), [[DEF3]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s16>), [[CONCAT_VECTORS1]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<64 x s16>)
    %0:_(<16 x s16>) = G_IMPLICIT_DEF
    %1:_(<16 x s16>) = G_IMPLICIT_DEF
    %2:_(<16 x s16>) = G_IMPLICIT_DEF
    %3:_(<16 x s16>) = G_IMPLICIT_DEF
    %4:_(<64 x s16>) = G_CONCAT_VECTORS %0(<16 x s16>), %1(<16 x s16>), %2(<16 x s16>), %3(<16 x s16>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v64s16_v8s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s16_v8s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<32 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF2]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF3]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST4]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[BITCAST3]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST5]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF4:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF4]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF5:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF5]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST6:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF4]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST7:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF5]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST7]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT2]], [[BITCAST6]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST8:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL2]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST8]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF6:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF6]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF7:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF7]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST9:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF6]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST10:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF7]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[BITCAST10]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT3]], [[BITCAST9]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST11:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL3]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR3:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST11]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<16 x s16>), [[AIE_UNPAD_VECTOR1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR2]](<16 x s16>), [[AIE_UNPAD_VECTOR3]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s16>), [[CONCAT_VECTORS1]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<64 x s16>)
    %0:_(<8 x s16>) = G_IMPLICIT_DEF
    %1:_(<8 x s16>) = G_IMPLICIT_DEF
    %2:_(<8 x s16>) = G_IMPLICIT_DEF
    %3:_(<8 x s16>) = G_IMPLICIT_DEF
    %4:_(<8 x s16>) = G_IMPLICIT_DEF
    %5:_(<8 x s16>) = G_IMPLICIT_DEF
    %6:_(<8 x s16>) = G_IMPLICIT_DEF
    %7:_(<8 x s16>) = G_IMPLICIT_DEF
    %8:_(<64 x s16>) = G_CONCAT_VECTORS %0(<8 x s16>), %1(<8 x s16>), %2(<8 x s16>), %3(<8 x s16>), %4(<8 x s16>), %5(<8 x s16>), %6(<8 x s16>), %7(<8 x s16>)
    PseudoRET implicit $lr, implicit %8
...

---
name:            test_v32s32_v16s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s32_v16s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %0:_(<16 x s32>) = G_IMPLICIT_DEF
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %2:_(<32 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v32s32_v8s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s32_v8s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF2]](<8 x s32>), [[DEF3]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s32>), [[CONCAT_VECTORS1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<32 x s32>)
    %0:_(<8 x s32>) = G_IMPLICIT_DEF
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<8 x s32>) = G_IMPLICIT_DEF
    %3:_(<8 x s32>) = G_IMPLICIT_DEF
    %4:_(<32 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>), %2(<8 x s32>), %3(<8 x s32>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v32s32_v4s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s32_v4s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<4 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[AIE_PAD_VECTOR_UNDEF1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[AIE_PAD_VECTOR_UNDEF]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[AIE_PAD_VECTOR_UNDEF3]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[AIE_PAD_VECTOR_UNDEF2]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF4:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF4]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF5:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF5]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[AIE_PAD_VECTOR_UNDEF5]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT2]], [[AIE_PAD_VECTOR_UNDEF4]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL2]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF6:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF6]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF7:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF7]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF8]], [[AIE_PAD_VECTOR_UNDEF7]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT3]], [[AIE_PAD_VECTOR_UNDEF6]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR3:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL3]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[AIE_UNPAD_VECTOR1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR2]](<8 x s32>), [[AIE_UNPAD_VECTOR3]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s32>), [[CONCAT_VECTORS1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<32 x s32>)
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    %1:_(<4 x s32>) = G_IMPLICIT_DEF
    %2:_(<4 x s32>) = G_IMPLICIT_DEF
    %3:_(<4 x s32>) = G_IMPLICIT_DEF
    %4:_(<4 x s32>) = G_IMPLICIT_DEF
    %5:_(<4 x s32>) = G_IMPLICIT_DEF
    %6:_(<4 x s32>) = G_IMPLICIT_DEF
    %7:_(<4 x s32>) = G_IMPLICIT_DEF
    %8:_(<32 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>), %2(<4 x s32>), %3(<4 x s32>), %4(<4 x s32>), %5(<4 x s32>), %6(<4 x s32>), %7(<4 x s32>)
    PseudoRET implicit $lr, implicit %8
...

# 2048-bit vectors
---
name:            test_v256s8_v128s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v256s8_v128s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<256 x s8>) = G_CONCAT_VECTORS [[DEF]](<128 x s8>), [[DEF1]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<256 x s8>)
    %0:_(<128 x s8>) = G_IMPLICIT_DEF
    %1:_(<128 x s8>) = G_IMPLICIT_DEF
    %2:_(<256 x s8>) = G_CONCAT_VECTORS %0(<128 x s8>), %1(<128 x s8>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v256s8_v64s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v256s8_v64s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[DEF]](<64 x s8>), [[DEF1]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[DEF2]](<64 x s8>), [[DEF3]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<256 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<128 x s8>), [[CONCAT_VECTORS1]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<256 x s8>)
    %0:_(<64 x s8>) = G_IMPLICIT_DEF
    %1:_(<64 x s8>) = G_IMPLICIT_DEF
    %2:_(<64 x s8>) = G_IMPLICIT_DEF
    %3:_(<64 x s8>) = G_IMPLICIT_DEF
    %4:_(<256 x s8>) = G_CONCAT_VECTORS %0(<64 x s8>), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s8>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v256s8_v32s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v256s8_v32s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF2]](<32 x s8>), [[DEF3]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF4]](<32 x s8>), [[DEF5]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF6]](<32 x s8>), [[DEF7]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<64 x s8>), [[CONCAT_VECTORS1]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS2]](<64 x s8>), [[CONCAT_VECTORS3]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<256 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS4]](<128 x s8>), [[CONCAT_VECTORS5]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS6]](<256 x s8>)
    %0:_(<32 x s8>) = G_IMPLICIT_DEF
    %1:_(<32 x s8>) = G_IMPLICIT_DEF
    %2:_(<32 x s8>) = G_IMPLICIT_DEF
    %3:_(<32 x s8>) = G_IMPLICIT_DEF
    %4:_(<32 x s8>) = G_IMPLICIT_DEF
    %5:_(<32 x s8>) = G_IMPLICIT_DEF
    %6:_(<32 x s8>) = G_IMPLICIT_DEF
    %7:_(<32 x s8>) = G_IMPLICIT_DEF
    %8:_(<256 x s8>) = G_CONCAT_VECTORS %0(<32 x s8>), %1(<32 x s8>), %2(<32 x s8>), %3(<32 x s8>), %4(<32 x s8>), %5(<32 x s8>), %6(<32 x s8>), %7(<32 x s8>)
    PseudoRET implicit $lr, implicit %8
...

---
name:            test_v256s8_v16s8
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v256s8_v16s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF10:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF11:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF12:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF13:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF14:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF15:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<64 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF16:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF2]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF3]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST4]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[BITCAST3]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST5]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF4:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF4]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF5:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF5]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST6:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF4]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST7:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF5]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST7]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT2]], [[BITCAST6]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST8:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL2]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST8]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF6:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF6]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF7:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF7]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST9:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF6]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST10:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF7]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST10]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT3]], [[BITCAST9]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST11:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL3]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR3:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST11]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF8:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF8]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF9:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF9]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST12:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF8]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST13:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF9]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT4:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST13]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL4:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT4]], [[BITCAST12]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST14:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL4]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR4:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST14]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF10:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF10]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF11:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF11]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST15:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF10]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST16:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF11]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT5:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST16]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL5:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT5]], [[BITCAST15]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST17:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL5]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR5:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST17]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF12:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF12]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF13:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF13]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST18:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF12]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST19:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF13]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT6:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST19]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL6:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT6]], [[BITCAST18]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST20:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL6]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR6:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST20]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF14:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF14]](<16 x s8>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF15:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF15]](<16 x s8>)
    ; CHECK-NEXT: [[BITCAST21:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF14]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST22:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF15]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT7:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST22]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL7:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT7]], [[BITCAST21]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST23:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[AIE_VSEL7]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR7:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST23]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<32 x s8>), [[AIE_UNPAD_VECTOR1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR2]](<32 x s8>), [[AIE_UNPAD_VECTOR3]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR4]](<32 x s8>), [[AIE_UNPAD_VECTOR5]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR6]](<32 x s8>), [[AIE_UNPAD_VECTOR7]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<64 x s8>), [[CONCAT_VECTORS1]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS2]](<64 x s8>), [[CONCAT_VECTORS3]](<64 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<256 x s8>) = G_CONCAT_VECTORS [[CONCAT_VECTORS4]](<128 x s8>), [[CONCAT_VECTORS5]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS6]](<256 x s8>)
    %0:_(<16 x s8>) = G_IMPLICIT_DEF
    %1:_(<16 x s8>) = G_IMPLICIT_DEF
    %2:_(<16 x s8>) = G_IMPLICIT_DEF
    %3:_(<16 x s8>) = G_IMPLICIT_DEF
    %4:_(<16 x s8>) = G_IMPLICIT_DEF
    %5:_(<16 x s8>) = G_IMPLICIT_DEF
    %6:_(<16 x s8>) = G_IMPLICIT_DEF
    %7:_(<16 x s8>) = G_IMPLICIT_DEF
    %8:_(<16 x s8>) = G_IMPLICIT_DEF
    %9:_(<16 x s8>) = G_IMPLICIT_DEF
    %10:_(<16 x s8>) = G_IMPLICIT_DEF
    %11:_(<16 x s8>) = G_IMPLICIT_DEF
    %12:_(<16 x s8>) = G_IMPLICIT_DEF
    %13:_(<16 x s8>) = G_IMPLICIT_DEF
    %14:_(<16 x s8>) = G_IMPLICIT_DEF
    %15:_(<16 x s8>) = G_IMPLICIT_DEF
    %16:_(<256 x s8>) = G_CONCAT_VECTORS %0(<16 x s8>), %1(<16 x s8>), %2(<16 x s8>), %3(<16 x s8>), %4(<16 x s8>), %5(<16 x s8>), %6(<16 x s8>), %7(<16 x s8>), %8(<16 x s8>), %9(<16 x s8>), %10(<16 x s8>), %11(<16 x s8>), %12(<16 x s8>), %13(<16 x s8>), %14(<16 x s8>), %15(<16 x s8>)
    PseudoRET implicit $lr, implicit %16
...

---
name:            test_v128s16_v64s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v128s16_v64s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<128 x s16>) = G_CONCAT_VECTORS [[DEF]](<64 x s16>), [[DEF1]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<128 x s16>)
    %0:_(<64 x s16>) = G_IMPLICIT_DEF
    %1:_(<64 x s16>) = G_IMPLICIT_DEF
    %2:_(<128 x s16>) = G_CONCAT_VECTORS %0(<64 x s16>), %1(<64 x s16>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v128s16_v32s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v128s16_v32s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[DEF]](<32 x s16>), [[DEF1]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[DEF2]](<32 x s16>), [[DEF3]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<128 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<64 x s16>), [[CONCAT_VECTORS1]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<128 x s16>)
    %0:_(<32 x s16>) = G_IMPLICIT_DEF
    %1:_(<32 x s16>) = G_IMPLICIT_DEF
    %2:_(<32 x s16>) = G_IMPLICIT_DEF
    %3:_(<32 x s16>) = G_IMPLICIT_DEF
    %4:_(<128 x s16>) = G_CONCAT_VECTORS %0(<32 x s16>), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s16>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v128s16_v16s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v128s16_v16s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF2]](<16 x s16>), [[DEF3]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF4]](<16 x s16>), [[DEF5]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF6]](<16 x s16>), [[DEF7]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s16>), [[CONCAT_VECTORS1]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS2]](<32 x s16>), [[CONCAT_VECTORS3]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<128 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS4]](<64 x s16>), [[CONCAT_VECTORS5]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS6]](<128 x s16>)
    %0:_(<16 x s16>) = G_IMPLICIT_DEF
    %1:_(<16 x s16>) = G_IMPLICIT_DEF
    %2:_(<16 x s16>) = G_IMPLICIT_DEF
    %3:_(<16 x s16>) = G_IMPLICIT_DEF
    %4:_(<16 x s16>) = G_IMPLICIT_DEF
    %5:_(<16 x s16>) = G_IMPLICIT_DEF
    %6:_(<16 x s16>) = G_IMPLICIT_DEF
    %7:_(<16 x s16>) = G_IMPLICIT_DEF
    %8:_(<128 x s16>) = G_CONCAT_VECTORS %0(<16 x s16>), %1(<16 x s16>), %2(<16 x s16>), %3(<16 x s16>), %4(<16 x s16>), %5(<16 x s16>), %6(<16 x s16>), %7(<16 x s16>)
    PseudoRET implicit $lr, implicit %8
...

---
name:            test_v128s16_v8s16
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v128s16_v8s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF10:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF11:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF12:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF13:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF14:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF15:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF1]](<32 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF16:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[BITCAST]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST2]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF2]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF3]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST4]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[BITCAST3]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST5]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF4:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF4]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF5:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF5]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST6:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF4]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST7:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF5]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST7]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT2]], [[BITCAST6]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST8:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL2]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST8]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF6:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF6]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF7:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF7]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST9:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF6]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST10:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF7]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST10]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT3]], [[BITCAST9]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST11:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL3]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR3:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST11]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF8:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF8]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF9:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF9]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST12:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF8]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST13:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF9]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT4:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST13]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL4:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT4]], [[BITCAST12]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST14:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL4]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR4:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST14]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF10:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF10]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF11:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF11]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST15:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF10]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST16:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF11]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT5:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST16]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL5:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT5]], [[BITCAST15]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST17:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL5]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR5:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST17]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF12:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF12]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF13:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF13]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST18:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF12]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST19:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF13]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT6:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST19]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL6:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT6]], [[BITCAST18]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST20:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL6]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR6:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST20]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF14:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF14]](<8 x s16>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF15:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF15]](<8 x s16>)
    ; CHECK-NEXT: [[BITCAST21:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF14]](<32 x s16>)
    ; CHECK-NEXT: [[BITCAST22:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_PAD_VECTOR_UNDEF15]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT7:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[BITCAST22]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL7:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT7]], [[BITCAST21]], [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST23:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[AIE_VSEL7]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR7:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST23]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<16 x s16>), [[AIE_UNPAD_VECTOR1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR2]](<16 x s16>), [[AIE_UNPAD_VECTOR3]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR4]](<16 x s16>), [[AIE_UNPAD_VECTOR5]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR6]](<16 x s16>), [[AIE_UNPAD_VECTOR7]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s16>), [[CONCAT_VECTORS1]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS2]](<32 x s16>), [[CONCAT_VECTORS3]](<32 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<128 x s16>) = G_CONCAT_VECTORS [[CONCAT_VECTORS4]](<64 x s16>), [[CONCAT_VECTORS5]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS6]](<128 x s16>)
    %0:_(<8 x s16>) = G_IMPLICIT_DEF
    %1:_(<8 x s16>) = G_IMPLICIT_DEF
    %2:_(<8 x s16>) = G_IMPLICIT_DEF
    %3:_(<8 x s16>) = G_IMPLICIT_DEF
    %4:_(<8 x s16>) = G_IMPLICIT_DEF
    %5:_(<8 x s16>) = G_IMPLICIT_DEF
    %6:_(<8 x s16>) = G_IMPLICIT_DEF
    %7:_(<8 x s16>) = G_IMPLICIT_DEF
    %8:_(<8 x s16>) = G_IMPLICIT_DEF
    %9:_(<8 x s16>) = G_IMPLICIT_DEF
    %10:_(<8 x s16>) = G_IMPLICIT_DEF
    %11:_(<8 x s16>) = G_IMPLICIT_DEF
    %12:_(<8 x s16>) = G_IMPLICIT_DEF
    %13:_(<8 x s16>) = G_IMPLICIT_DEF
    %14:_(<8 x s16>) = G_IMPLICIT_DEF
    %15:_(<8 x s16>) = G_IMPLICIT_DEF
    %16:_(<128 x s16>) = G_CONCAT_VECTORS %0(<8 x s16>), %1(<8 x s16>), %2(<8 x s16>), %3(<8 x s16>), %4(<8 x s16>), %5(<8 x s16>), %6(<8 x s16>), %7(<8 x s16>), %8(<8 x s16>), %9(<8 x s16>), %10(<8 x s16>), %11(<8 x s16>), %12(<8 x s16>), %13(<8 x s16>), %14(<8 x s16>), %15(<8 x s16>)
    PseudoRET implicit $lr, implicit %16
...

---
name:            test_v64s32_v32s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s32_v32s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[DEF]](<32 x s32>), [[DEF1]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s32>)
    %0:_(<32 x s32>) = G_IMPLICIT_DEF
    %1:_(<32 x s32>) = G_IMPLICIT_DEF
    %2:_(<64 x s32>) = G_CONCAT_VECTORS %0(<32 x s32>), %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v64s32_v16s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s32_v16s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[DEF2]](<16 x s32>), [[DEF3]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s32>), [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<64 x s32>)
    %0:_(<16 x s32>) = G_IMPLICIT_DEF
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<16 x s32>) = G_IMPLICIT_DEF
    %4:_(<64 x s32>) = G_CONCAT_VECTORS %0(<16 x s32>), %1(<16 x s32>), %2(<16 x s32>), %3(<16 x s32>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v64s32_v8s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s32_v8s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF2]](<8 x s32>), [[DEF3]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF4]](<8 x s32>), [[DEF5]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF6]](<8 x s32>), [[DEF7]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s32>), [[CONCAT_VECTORS1]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS2]](<16 x s32>), [[CONCAT_VECTORS3]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS4]](<32 x s32>), [[CONCAT_VECTORS5]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS6]](<64 x s32>)
    %0:_(<8 x s32>) = G_IMPLICIT_DEF
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<8 x s32>) = G_IMPLICIT_DEF
    %3:_(<8 x s32>) = G_IMPLICIT_DEF
    %4:_(<8 x s32>) = G_IMPLICIT_DEF
    %5:_(<8 x s32>) = G_IMPLICIT_DEF
    %6:_(<8 x s32>) = G_IMPLICIT_DEF
    %7:_(<8 x s32>) = G_IMPLICIT_DEF
    %8:_(<64 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %1(<8 x s32>), %2(<8 x s32>), %3(<8 x s32>), %4(<8 x s32>), %5(<8 x s32>), %6(<8 x s32>), %7(<8 x s32>)
    PseudoRET implicit $lr, implicit %8
...

---
name:            test_v64s32_v4s32
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v64s32_v4s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF10:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF11:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF12:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF13:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF14:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF15:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF1:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF1]](<4 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[DEF16:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF1]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT]], [[AIE_PAD_VECTOR_UNDEF]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF2:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF2]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF3:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF3]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF3]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL1:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT1]], [[AIE_PAD_VECTOR_UNDEF2]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF4:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF4]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF5:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF5]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF5]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL2:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT2]], [[AIE_PAD_VECTOR_UNDEF4]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL2]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF6:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF6]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF7:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF7]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF7]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL3:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT3]], [[AIE_PAD_VECTOR_UNDEF6]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR3:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL3]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF8:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF8]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF9:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF9]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT4:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF9]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL4:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT4]], [[AIE_PAD_VECTOR_UNDEF8]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR4:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL4]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF10:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF10]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF11:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF11]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT5:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF11]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL5:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT5]], [[AIE_PAD_VECTOR_UNDEF10]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR5:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL5]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF12:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF12]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF13:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF13]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT6:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF13]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL6:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT6]], [[AIE_PAD_VECTOR_UNDEF12]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR6:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL6]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF14:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF14]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF15:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF15]](<4 x s32>)
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT7:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[DEF16]], [[AIE_PAD_VECTOR_UNDEF15]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_VSEL7:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[AIE_VSHIFT_RIGHT7]], [[AIE_PAD_VECTOR_UNDEF14]], [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR7:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL7]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[AIE_UNPAD_VECTOR1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR2]](<8 x s32>), [[AIE_UNPAD_VECTOR3]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR4]](<8 x s32>), [[AIE_UNPAD_VECTOR5]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR6]](<8 x s32>), [[AIE_UNPAD_VECTOR7]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s32>), [[CONCAT_VECTORS1]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS2]](<16 x s32>), [[CONCAT_VECTORS3]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS4]](<32 x s32>), [[CONCAT_VECTORS5]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS6]](<64 x s32>)
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    %1:_(<4 x s32>) = G_IMPLICIT_DEF
    %2:_(<4 x s32>) = G_IMPLICIT_DEF
    %3:_(<4 x s32>) = G_IMPLICIT_DEF
    %4:_(<4 x s32>) = G_IMPLICIT_DEF
    %5:_(<4 x s32>) = G_IMPLICIT_DEF
    %6:_(<4 x s32>) = G_IMPLICIT_DEF
    %7:_(<4 x s32>) = G_IMPLICIT_DEF
    %8:_(<4 x s32>) = G_IMPLICIT_DEF
    %9:_(<4 x s32>) = G_IMPLICIT_DEF
    %10:_(<4 x s32>) = G_IMPLICIT_DEF
    %11:_(<4 x s32>) = G_IMPLICIT_DEF
    %12:_(<4 x s32>) = G_IMPLICIT_DEF
    %13:_(<4 x s32>) = G_IMPLICIT_DEF
    %14:_(<4 x s32>) = G_IMPLICIT_DEF
    %15:_(<4 x s32>) = G_IMPLICIT_DEF
    %16:_(<64 x s32>) = G_CONCAT_VECTORS %0(<4 x s32>), %1(<4 x s32>), %2(<4 x s32>), %3(<4 x s32>), %4(<4 x s32>), %5(<4 x s32>), %6(<4 x s32>), %7(<4 x s32>), %8(<4 x s32>), %9(<4 x s32>), %10(<4 x s32>), %11(<4 x s32>), %12(<4 x s32>), %13(<4 x s32>), %14(<4 x s32>), %15(<4 x s32>)
    PseudoRET implicit $lr, implicit %16
...

---
name:            test_v32s64_v16s64
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s64_v16s64
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[DEF]](<16 x s64>), [[DEF1]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s64>)
    %0:_(<16 x s64>) = G_IMPLICIT_DEF
    %1:_(<16 x s64>) = G_IMPLICIT_DEF
    %2:_(<32 x s64>) = G_CONCAT_VECTORS %0(<16 x s64>), %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_v32s64_v8s64
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s64_v8s64
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[DEF]](<8 x s64>), [[DEF1]](<8 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[DEF2]](<8 x s64>), [[DEF3]](<8 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s64>), [[CONCAT_VECTORS1]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<32 x s64>)
    %0:_(<8 x s64>) = G_IMPLICIT_DEF
    %1:_(<8 x s64>) = G_IMPLICIT_DEF
    %2:_(<8 x s64>) = G_IMPLICIT_DEF
    %3:_(<8 x s64>) = G_IMPLICIT_DEF
    %4:_(<32 x s64>) = G_CONCAT_VECTORS %0(<8 x s64>), %1(<8 x s64>), %2(<8 x s64>), %3(<8 x s64>)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_v32s64_v4s64
legalized:       false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_v32s64_v4s64
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[DEF1]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF2]](<4 x s64>), [[DEF3]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF4]](<4 x s64>), [[DEF5]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF6]](<4 x s64>), [[DEF7]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<8 x s64>), [[CONCAT_VECTORS1]](<8 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS2]](<8 x s64>), [[CONCAT_VECTORS3]](<8 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS4]](<16 x s64>), [[CONCAT_VECTORS5]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS6]](<32 x s64>)
    %0:_(<4 x s64>) = G_IMPLICIT_DEF
    %1:_(<4 x s64>) = G_IMPLICIT_DEF
    %2:_(<4 x s64>) = G_IMPLICIT_DEF
    %3:_(<4 x s64>) = G_IMPLICIT_DEF
    %4:_(<4 x s64>) = G_IMPLICIT_DEF
    %5:_(<4 x s64>) = G_IMPLICIT_DEF
    %6:_(<4 x s64>) = G_IMPLICIT_DEF
    %7:_(<4 x s64>) = G_IMPLICIT_DEF
    %8:_(<32 x s64>) = G_CONCAT_VECTORS %0(<4 x s64>), %1(<4 x s64>), %2(<4 x s64>), %3(<4 x s64>), %4(<4 x s64>), %5(<4 x s64>), %6(<4 x s64>), %7(<4 x s64>)
    PseudoRET implicit $lr, implicit %8
...
