# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_bitcast_s256
body:             |
  bb.1.entry:
    liveins: $wl0
    ; CHECK-LABEL: name: test_bitcast_s256
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s256) = G_BITCAST [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s16>) = G_BITCAST [[BITCAST]](s256)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](<16 x s16>)
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(s256) = G_BITCAST %0(<8 x s32>)
    %2:_(<16 x s16>) = G_BITCAST %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_bitcast_s512
body:             |
  bb.1.entry:
    liveins: $wl0
    ; CHECK-LABEL: name: test_bitcast_s512
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s512) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[BITCAST]](s512)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](<32 x s16>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(s512) = G_BITCAST %0(<16 x s32>)
    %2:_(<32 x s16>) = G_BITCAST %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_bitcast_s1024
body:             |
  bb.1.entry:
    liveins: $y2
    ; CHECK-LABEL: name: test_bitcast_s1024
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s1024) = G_BITCAST [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<64 x s16>) = G_BITCAST [[BITCAST]](s1024)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](<64 x s16>)
    %0:_(<32 x s32>) = COPY $y2
    %1:_(s1024) = G_BITCAST %0(<32 x s32>)
    %2:_(<64 x s16>) = G_BITCAST %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_bitcast_s2048
body:             |
  bb.1.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_bitcast_s2048
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s2048) = G_BITCAST [[COPY]](<64 x s32>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<128 x s16>) = G_BITCAST [[BITCAST]](s2048)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](<128 x s16>)
    %0:_(<64 x s32>) = COPY $dm0
    %1:_(s2048) = G_BITCAST %0(<64 x s32>)
    %2:_(<128 x s16>) = G_BITCAST %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_bitcast_s32
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_bitcast_s32
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s1>) = COPY $r0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY]](<32 x s1>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<8 x s4>) = G_BITCAST [[BITCAST]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](<8 x s4>)
    %0:_(<32 x s1>) = COPY $r0
    %1:_(s32) = G_BITCAST %0(<32 x s1>)
    %2:_(<8 x s4>) = G_BITCAST %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_bitcast_s64
body:             |
  bb.1.entry:
    liveins: $l0

    ; CHECK-LABEL: name: test_bitcast_s64
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s1>) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s64) = G_BITCAST [[COPY]](<64 x s1>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s4>) = G_BITCAST [[BITCAST]](s64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](<16 x s4>)
    %0:_(<64 x s1>) = COPY $l0
    %1:_(s64) = G_BITCAST %0(<64 x s1>)
    %2:_(<16 x s4>) = G_BITCAST %1
    PseudoRET implicit $lr, implicit %2
...
