# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
---
name: v4s32
body: |
  bb.0:
    ; CHECK-LABEL: name: v4s32
    ; CHECK: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<4 x s32>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $q0 = COPY [[FREEZE]](<4 x s32>)
    %0:_(<4 x s32>) = COPY $q0
    %1:_(<4 x s32>) = G_FREEZE %0
    $q0 = COPY %1
...

---
name: v8s16
body: |
  bb.0:
    ; CHECK-LABEL: name: v8s16
    ; CHECK: [[COPY:%[0-9]+]]:_(<8 x s16>) = COPY $q0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<8 x s16>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $q0 = COPY [[FREEZE]](<8 x s16>)
    %0:_(<8 x s16>) = COPY $q0
    %1:_(<8 x s16>) = G_FREEZE %0
    $q0 = COPY %1
...

---
name: v16s8
body: |
  bb.0:
    ; CHECK-LABEL: name: v16s8
    ; CHECK: [[COPY:%[0-9]+]]:_(<16 x s8>) = COPY $q0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<16 x s8>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $q0 = COPY [[FREEZE]](<16 x s8>)
    %0:_(<16 x s8>) = COPY $q0
    %1:_(<16 x s8>) = G_FREEZE %0
    $q0 = COPY %1
...

---
name: acc2048_s64
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: acc2048_s64
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<32 x s64>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $dm0 = COPY [[FREEZE]](<32 x s64>)
    %0:_(<32 x s64>) = COPY $dm0
    %1:_(<32 x s64>) = G_FREEZE %0
    $dm0 = COPY %1
...

---
name: acc2048_s32
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: acc2048_s32
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(<64 x s32>) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: $dm0 = COPY [[FREEZE]](<64 x s32>)
    %0:_(<64 x s32>) = COPY $dm0
    %1:_(<64 x s32>) = G_FREEZE %0
    $dm0 = COPY %1
...
