# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
---
name: v4s32
body: |
  bb.0:
    ; CHECK-LABEL: name: v4s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<4 x s32>)
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v8s16
body: |
  bb.0:
    ; CHECK-LABEL: name: v8s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<8 x s16>)
    %0:_(<8 x s16>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...

---
name: v16s8
body: |
  bb.0:
    ; CHECK-LABEL: name: v16s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<16 x s8>)
    %0:_(<16 x s8>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0
...
---
name: acc2048
body: |
  bb.0:
    ; CHECK-LABEL: name: acc2048
    ; CHECK: [[DEF:%[0-9]+]]:_(<32 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<32 x s64>), implicit [[DEF1]](<64 x s32>)
    %0:_(<32 x s64>) = G_IMPLICIT_DEF
    %1:_(<64 x s32>) = G_IMPLICIT_DEF
    PseudoRET implicit $lr, implicit %0, implicit %1
...
