# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -DVER=aie2p
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -DVER=aie2ps

---
name: test_fmul_s16
body: |
  bb.0:
    liveins: $r1, $r2, $p0
    ; CHECK-LABEL: name: test_fmul_s16
    ; CHECK: liveins: $r1, $r2, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY1]](s32)
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(<32 x s16>) = G_FMUL [[AIE_BROADCAST_VECTOR]], [[AIE_BROADCAST_VECTOR1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_ZEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_ZEXT_EXTRACT_VECTOR_ELT [[FMUL]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[AIE_ZEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: $r0 = COPY [[ASSERT_ZEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0(s32)
    %2:_(s32) = COPY $r2
    %3:_(s16) = G_TRUNC %2(s32)
    %4:_(s16) = G_FMUL %1, %3
    %5:_(s32) = G_ANYEXT %4(s16)
    $r0 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name: test_fmul_vec_1024
body: |
  bb.0:
    liveins: $dm0, $dm1
    ; CHECK-LABEL: name: test_fmul_vec_1024
    ; CHECK: liveins: $dm0, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s16>) = COPY $cml1
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(<64 x s16>) = G_FMUL [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $cml0 = COPY [[FMUL]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<64 x s16>) = COPY $cml0
    %1:_(<64 x s16>) = COPY $cml1
    %2:_(<64 x s16>) = G_FMUL %0, %1
    $cml0 = COPY %2(<64 x s16>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fmul_vec_512
body: |
  bb.0:
    liveins: $dm0, $dm1
    ; CHECK-LABEL: name: test_fmul_vec_512
    ; CHECK: liveins: $dm0, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $bmll1
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(<32 x s16>) = G_FMUL [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $bmll0 = COPY [[FMUL]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %0:_(<32 x s16>) = COPY $bmll0
    %1:_(<32 x s16>) = COPY $bmll1
    %2:_(<32 x s16>) = G_FMUL %0, %1
    $bmll0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $bmll0
...


---
name: test_fmul_s32
body: |
  bb.0:
    liveins: $r1, $r2, $p0
    ; CHECK-LABEL: name: test_fmul_s32
    ; CHECK: liveins: $r1, $r2, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    ; CHECK-NEXT: $r2 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoJL &__mulsf3, csr_[[VER]], implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s32) = COPY $r1
    %2:_(s32) = COPY $r2
    %4:_(s32) = G_FMUL %0, %2
    $r0 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name: test_fmul_s64
body: |
  bb.0:
    liveins: $l1, $l2, $p0
    ; CHECK-LABEL: name: test_fmul_s64
    ; CHECK: liveins: $l1, $l2, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $l1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $l2
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; CHECK-NEXT: $r2 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r3 = COPY [[UV1]](s32)
    ; CHECK-NEXT: $r4 = COPY [[UV2]](s32)
    ; CHECK-NEXT: $r5 = COPY [[UV3]](s32)
    ; CHECK-NEXT: PseudoJL &__muldf3, csr_[[VER]], implicit-def $lr, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit-def $r0, implicit-def $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY2]](s32), [[COPY3]](s32)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $l0 = COPY [[MV]](s64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %0:_(s64) = COPY $l1
    %2:_(s64) = COPY $l2
    %4:_(s64) = G_FMUL %0, %2
    $l0 = COPY %4(s64)
    PseudoRET implicit $lr, implicit $r0
...
