# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefixes=CHECK,AIE2P %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefixes=CHECK,AIE2PS %s

---
name:            extract_v4i64
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; CHECK-LABEL: name: extract_v4i64
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s64>) = G_AIE_UNPAD_VECTOR [[COPY]](<8 x s64>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s64>), [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %2:_(<8 x s64>) = COPY $bmll0
    %1:_(<4 x s64>) = G_AIE_UNPAD_VECTOR %2(<8 x s64>)
    %4:_(s32) = G_CONSTANT i32 3
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<4 x s64>), %4(s32)
    %5:_(s32), %6:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %5(s32)
    $r1 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v4i64_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r2

    ; CHECK-LABEL: name: extract_v4i64_dyn
    ; CHECK: liveins: $bmll0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s64>) = G_AIE_UNPAD_VECTOR [[COPY]](<8 x s64>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s64>), [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<8 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %3:_(<8 x s64>) = COPY $bmll0
    %1:_(<4 x s64>) = G_AIE_UNPAD_VECTOR %3(<8 x s64>)
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<4 x s64>), %2(s32)
    %5:_(s32), %6:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %5(s32)
    $r1 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v8i64
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; CHECK-LABEL: name: extract_v8i64
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<8 x s64>) = COPY $bmll0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v8i64_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r2

    ; CHECK-LABEL: name: extract_v8i64_dyn
    ; CHECK: liveins: $bmll0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<8 x s64>) = COPY $bmll0
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v16i64
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0

    ; CHECK-LABEL: name: extract_v16i64
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[COPY]](<16 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV2]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV3]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<16 x s64>) = COPY $cml0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<16 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v16i64_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r2

    ; CHECK-LABEL: name: extract_v16i64_dyn
    ; CHECK: liveins: $cml0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[COPY]](<16 x s64>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[COPY1]](s32), [[C]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV]](<8 x s64>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV1]](<8 x s64>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[BITCAST]], [[BITCAST1]]
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[C1]], [[C]]
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[SELECT1]]
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[BITCAST2]](<8 x s64>), [[SUB]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV2]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV3]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<16 x s64>) = COPY $cml0
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<16 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v64i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: extract_v64i32
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s32>), [[UV1:%[0-9]+]]:_(<32 x s32>) = G_UNMERGE_VALUES [[COPY]](<64 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[UV]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<64 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r1

    ; CHECK-LABEL: name: extract_v64i32_dyn
    ; CHECK: liveins: $dm0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s32>), [[UV1:%[0-9]+]]:_(<32 x s32>) = G_UNMERGE_VALUES [[COPY]](<64 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[UV]](<32 x s32>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<16 x s32>), [[UV5:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[UV1]](<32 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[COPY1]](s32), [[C]]
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[UV4]], [[UV5]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[C1]], [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[COPY1]](s32), [[C1]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP1]](s32), [[UV3]], [[SELECT]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s32), [[C2]], [[SELECT1]]
    ; CHECK-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[COPY1]](s32), [[C2]]
    ; CHECK-NEXT: [[SELECT4:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP2]](s32), [[UV2]], [[SELECT2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[C3]], [[SELECT3]]
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[SELECT5]]
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[SELECT4]](<16 x s32>), [[SUB]](s32)
    ; CHECK-NEXT: $r0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(s32) = COPY $r1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<64 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i64
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: extract_v32i64
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s64>), [[UV1:%[0-9]+]]:_(<16 x s64>) = G_UNMERGE_VALUES [[COPY]](<32 x s64>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s64>), [[UV3:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV]](<16 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV4]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV5]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<32 x s64>) = COPY $dm0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<32 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v32i64_dyn
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r2

    ; CHECK-LABEL: name: extract_v32i64_dyn
    ; CHECK: liveins: $dm0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s64>), [[UV1:%[0-9]+]]:_(<16 x s64>) = G_UNMERGE_VALUES [[COPY]](<32 x s64>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s64>), [[UV3:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV]](<16 x s64>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<8 x s64>), [[UV5:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV1]](<16 x s64>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[COPY1]](s32), [[C]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV4]](<8 x s64>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV5]](<8 x s64>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[BITCAST]], [[BITCAST1]]
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s32), [[C1]], [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[COPY1]](s32), [[C1]]
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV3]](<8 x s64>)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[BITCAST2]](<8 x s64>)
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP1]](s32), [[BITCAST3]], [[BITCAST4]]
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[SELECT2]](<16 x s32>)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s32), [[C2]], [[SELECT1]]
    ; CHECK-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[COPY1]](s32), [[C2]]
    ; CHECK-NEXT: [[BITCAST6:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV2]](<8 x s64>)
    ; CHECK-NEXT: [[BITCAST7:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[BITCAST5]](<8 x s64>)
    ; CHECK-NEXT: [[SELECT4:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP2]](s32), [[BITCAST6]], [[BITCAST7]]
    ; CHECK-NEXT: [[BITCAST8:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[SELECT4]](<16 x s32>)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s32), [[C3]], [[SELECT3]]
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[SELECT5]]
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[BITCAST8]](<8 x s64>), [[SUB]](s32)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV6]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV7]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<32 x s64>) = COPY $dm0
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<32 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            test_s256_2xs256
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0, $r0
    ; CHECK-LABEL: name: test_s256_2xs256
    ; CHECK: liveins: $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s256>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s256), [[UV1:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[COPY]](<2 x s256>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s256) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[UV1]](s256)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[DEF]](s256)
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST1]](<8 x s32>), [[COPY3]](<8 x s32>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[CONCAT_VECTORS]], [[CONCAT_VECTORS1]]
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s256) = G_BITCAST [[UV2]](<8 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C1]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[UV]](s256)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[BITCAST2]](s256)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST3]](<8 x s32>), [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST4]](<8 x s32>), [[COPY4]](<8 x s32>)
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP1]](s32), [[CONCAT_VECTORS2]], [[CONCAT_VECTORS3]]
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<8 x s32>), [[UV5:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[SELECT1]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(s256) = G_BITCAST [[UV4]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST5]](s256)
    %0:_(<2 x s256>) = COPY $x0
    %1:_(s32) = COPY $r0
    %3:_(s256) = G_EXTRACT_VECTOR_ELT %0(<2 x s256>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s512_2xs512
legalized:       false
body:             |
  bb.0.entry:
    liveins: $cml0
    ; CHECK-LABEL: name: test_s512_2xs512
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s512>) = COPY $cml0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s512), [[UV1:%[0-9]+]]:_(s512) = G_UNMERGE_VALUES [[COPY]](<2 x s512>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s512) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV1]](s512)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[DEF]](s512)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[C]](s32), [[BITCAST]], [[BITCAST1]]
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s512) = G_BITCAST [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV]](s512)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[BITCAST2]](s512)
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[C1]](s32), [[BITCAST3]], [[BITCAST4]]
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(s512) = G_BITCAST [[SELECT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST5]](s512)
    %0:_(<2 x s512>) = COPY $cml0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s512) = G_EXTRACT_VECTOR_ELT %0(<2 x s512>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s1024_2xs1024
legalized:       false
body:             |
  bb.0.entry:
    liveins: $dm0, $r0
    ; CHECK-LABEL: name: test_s1024_2xs1024
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s1024>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s1024), [[UV1:%[0-9]+]]:_(s1024) = G_UNMERGE_VALUES [[COPY]](<2 x s1024>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s1024) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[UV1]](s1024)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[DEF]](s1024)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[BITCAST]](<32 x s32>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<16 x s32>), [[UV5:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[BITCAST1]](<32 x s32>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[UV2]], [[UV4]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[UV3]], [[UV5]]
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[SELECT]](<16 x s32>), [[SELECT1]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s1024) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C1]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[UV]](s1024)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[BITCAST2]](s1024)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(<16 x s32>), [[UV7:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[BITCAST3]](<32 x s32>)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(<16 x s32>), [[UV9:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[BITCAST4]](<32 x s32>)
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP1]](s32), [[UV6]], [[UV8]]
    ; CHECK-NEXT: [[SELECT3:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP1]](s32), [[UV7]], [[UV9]]
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[SELECT2]](<16 x s32>), [[SELECT3]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(s1024) = G_BITCAST [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST5]](s1024)
    %0:_(<2 x s1024>) = COPY $dm0
    %1:_(s32) = COPY $r0
    %3:_(s1024) = G_EXTRACT_VECTOR_ELT %0(<2 x s1024>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s256_4xs256
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0, $r0
    ; CHECK-LABEL: name: test_s256_4xs256
    ; CHECK: liveins: $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s256>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<2 x s256>), [[UV1:%[0-9]+]]:_(<2 x s256>) = G_UNMERGE_VALUES [[COPY]](<4 x s256>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s256), [[UV3:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV]](<2 x s256>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s256), [[UV5:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV1]](<2 x s256>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s256) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[UV5]](s256)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[DEF]](s256)
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST]](<8 x s32>), [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST1]](<8 x s32>), [[COPY3]](<8 x s32>)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[CONCAT_VECTORS]], [[CONCAT_VECTORS1]]
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(<8 x s32>), [[UV7:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s256) = G_BITCAST [[UV6]](<8 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C1]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[UV4]](s256)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[BITCAST2]](s256)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST3]](<8 x s32>), [[COPY4]](<8 x s32>)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST4]](<8 x s32>), [[COPY5]](<8 x s32>)
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP1]](s32), [[CONCAT_VECTORS2]], [[CONCAT_VECTORS3]]
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(<8 x s32>), [[UV9:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[SELECT1]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(s256) = G_BITCAST [[UV8]](<8 x s32>)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C2]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST6:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[UV3]](s256)
    ; CHECK-NEXT: [[BITCAST7:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[BITCAST5]](s256)
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST6]](<8 x s32>), [[COPY6]](<8 x s32>)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST7]](<8 x s32>), [[COPY7]](<8 x s32>)
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP2]](s32), [[CONCAT_VECTORS4]], [[CONCAT_VECTORS5]]
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(<8 x s32>), [[UV11:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[SELECT2]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST8:%[0-9]+]]:_(s256) = G_BITCAST [[UV10]](<8 x s32>)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP3:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C3]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST9:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[UV2]](s256)
    ; CHECK-NEXT: [[BITCAST10:%[0-9]+]]:_(<8 x s32>) = G_BITCAST [[BITCAST8]](s256)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST9]](<8 x s32>), [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[BITCAST10]](<8 x s32>), [[COPY8]](<8 x s32>)
    ; CHECK-NEXT: [[SELECT3:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP3]](s32), [[CONCAT_VECTORS6]], [[CONCAT_VECTORS7]]
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(<8 x s32>), [[UV13:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[SELECT3]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST11:%[0-9]+]]:_(s256) = G_BITCAST [[UV12]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST11]](s256)
    %0:_(<4 x s256>) = COPY $y2
    %1:_(s32) = COPY $r0
    %3:_(s256) = G_EXTRACT_VECTOR_ELT %0(<4 x s256>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s512_4xs512
legalized:       false
body:             |
  bb.0.entry:
    liveins: $dm0, $r0
    ; CHECK-LABEL: name: test_s512_4xs512
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s512>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<2 x s512>), [[UV1:%[0-9]+]]:_(<2 x s512>) = G_UNMERGE_VALUES [[COPY]](<4 x s512>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s512), [[UV3:%[0-9]+]]:_(s512) = G_UNMERGE_VALUES [[UV]](<2 x s512>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s512), [[UV5:%[0-9]+]]:_(s512) = G_UNMERGE_VALUES [[UV1]](<2 x s512>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s512) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV5]](s512)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[DEF]](s512)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP]](s32), [[BITCAST]], [[BITCAST1]]
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(s512) = G_BITCAST [[SELECT]](<16 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C1]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST3:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV4]](s512)
    ; CHECK-NEXT: [[BITCAST4:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[BITCAST2]](s512)
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP1]](s32), [[BITCAST3]], [[BITCAST4]]
    ; CHECK-NEXT: [[BITCAST5:%[0-9]+]]:_(s512) = G_BITCAST [[SELECT1]](<16 x s32>)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C2]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST6:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV3]](s512)
    ; CHECK-NEXT: [[BITCAST7:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[BITCAST5]](s512)
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP2]](s32), [[BITCAST6]], [[BITCAST7]]
    ; CHECK-NEXT: [[BITCAST8:%[0-9]+]]:_(s512) = G_BITCAST [[SELECT2]](<16 x s32>)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP3:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C3]](s32), [[COPY1]]
    ; CHECK-NEXT: [[BITCAST9:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[UV2]](s512)
    ; CHECK-NEXT: [[BITCAST10:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[BITCAST8]](s512)
    ; CHECK-NEXT: [[SELECT3:%[0-9]+]]:_(<16 x s32>) = G_SELECT [[ICMP3]](s32), [[BITCAST9]], [[BITCAST10]]
    ; CHECK-NEXT: [[BITCAST11:%[0-9]+]]:_(s512) = G_BITCAST [[SELECT3]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST11]](s512)
    %0:_(<4 x s512>) = COPY $dm0
    %1:_(s32) = COPY $r0
    %3:_(s512) = G_EXTRACT_VECTOR_ELT %0(<4 x s512>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...
---
name:            extract_v2i128_imm
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0
    ; CHECK-LABEL: name: extract_v2i128_imm
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s128>) = COPY $wl0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s8>) = G_BITCAST [[COPY]](<2 x s128>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[BITCAST]](<32 x s8>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY [[AIE_PAD_VECTOR_UNDEF]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_AIE_UNPAD_VECTOR [[COPY1]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(s128) = G_BITCAST [[AIE_UNPAD_VECTOR]](<16 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](s128)
    %2:_(<2 x s128>) = COPY $wl0
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(s128) = G_EXTRACT_VECTOR_ELT %2(<2 x s128>), %4(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:            extract_v2i128_idx
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $wl0, $r0
    ; CHECK-LABEL: name: extract_v2i128_idx
    ; CHECK: liveins: $wl0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s128>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s8>) = G_BITCAST [[COPY]](<2 x s128>)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<64 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[BITCAST]](<32 x s8>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[COPY1]](s32), [[C1]], [[C]]
    ; CHECK-NEXT: [[AIE_SHUFFLE_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_SHUFFLE_VECTOR [[AIE_PAD_VECTOR_UNDEF]], [[DEF]], [[SELECT]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_AIE_UNPAD_VECTOR [[AIE_SHUFFLE_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(s128) = G_BITCAST [[AIE_UNPAD_VECTOR]](<16 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST1]](s128)
    %2:_(<2 x s128>) = COPY $wl0
    %4:_(s32) = COPY $r0
    %0:_(s128) = G_EXTRACT_VECTOR_ELT %2(<2 x s128>), %4(s32)
    PseudoRET implicit $lr, implicit %0
...

---
name:            extract_v8i8
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $l0

    ; CHECK-LABEL: name: extract_v8i8
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s64) = G_BITCAST [[COPY]](<8 x s8>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[UV1]], [[C2]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[LSHR]], [[SHL]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C3]](s32)
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[UV3]], [[C3]](s32)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[LSHR1]], [[SHL1]]
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[UV4]], [[C2]](s32)
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[UV5]], [[C1]](s32)
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[LSHR2]], [[SHL2]]
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[UV9]], [[C1]](s32)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR4:%[0-9]+]]:_(s32) = G_LSHR [[UV11]], [[C3]](s32)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR5:%[0-9]+]]:_(s32) = G_LSHR [[UV13]], [[C2]](s32)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[BITCAST]](s64)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF1]], [[TRUNC]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[OR]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[OR1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[OR2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[UV7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LSHR3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LSHR4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LSHR5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[DEF]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[COPY1]](s32)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[COPY2]](s32)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[COPY3]](s32)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[COPY4]](s32)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[COPY5]](s32)
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[COPY6]](s32)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[COPY7]](s32)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[COPY8]](s32)
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[COPY9]](s32)
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[COPY10]](s32)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[COPY11]](s32)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[COPY12]](s32)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[COPY13]](s32)
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[COPY14]](s32)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[COPY15]](s32)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[COPY16]](s32)
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[COPY17]](s32)
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[COPY18]](s32)
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[COPY19]](s32)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[COPY20]](s32)
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[COPY21]](s32)
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[COPY22]](s32)
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[COPY23]](s32)
    ; CHECK-NEXT: [[UV14:%[0-9]+]]:_(<32 x s8>), [[UV15:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI31]](<64 x s8>)
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[UV15]](<32 x s8>), [[DEF2]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[TRUNC1]](s8)
    %1:_(<8 x s8>) = COPY $l0
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(s8) = G_EXTRACT_VECTOR_ELT %1(<8 x s8>), %4(s32)
    PseudoRET implicit $lr, implicit %0

...
