# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_merge_128
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_merge_128
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r3
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[COPY2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[COPY3]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshift.I512.I512), [[AIE_ADD_VECTOR_ELT_HI3]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI3]](<16 x s32>), [[C]](s32), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[INT]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s128) = G_BITCAST [[AIE_UNPAD_VECTOR]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](s128)
    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(s32) = COPY $r2
    %3:_(s32) = COPY $r3
    %4:_(s128) = G_MERGE_VALUES %0(s32), %1(s32), %2(s32), %3(s32)
    PseudoRET implicit $lr, implicit %4
...

---
name:            test_merge_256
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_merge_256
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[COPY]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI7]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s256) = G_BITCAST [[UV1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](s256)
    %0:_(s32) = COPY $r0
    %1:_(s256) = G_MERGE_VALUES %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32)
    PseudoRET implicit $lr, implicit %1
...

---
name:            test_merge_512
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_merge_512
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[COPY]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s512) = G_BITCAST [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](s512)
    %0:_(s32) = COPY $r0
    %1:_(s512) = G_MERGE_VALUES %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32)
    PseudoRET implicit $lr, implicit %1
...

---
name:            test_merge_1024
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_merge_1024
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s1024) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](s1024)
    %0:_(s32) = COPY $r0
    %1:_(s1024) = G_MERGE_VALUES %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32)
    PseudoRET implicit $lr, implicit %1
...

---
name:            test_merge_2048
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_merge_2048
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s32>), [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(s2048) = G_BITCAST [[CONCAT_VECTORS2]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](s2048)
    %0:_(s32) = COPY $r0
    %1:_(s2048) = G_MERGE_VALUES %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32), %0(s32)
    PseudoRET implicit $lr, implicit %1
...
