# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_v64acc32
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64acc32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<64 x s32>), [[COPY]](p0) :: (store (<64 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s32>), %0(p0) :: (store (<64 x s32>))
    PseudoRET implicit $lr

...
---
name:            test_v32acc64
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32acc64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<32 x s64>), [[COPY]](p0) :: (store (<32 x s64>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s64>), %0(p0) :: (store (<32 x s64>))
    PseudoRET implicit $lr

...

---
name:            test_v16int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<16 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY1]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY2]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<64 x s8>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 8
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY3]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<64 x s8>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 8
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY4]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<64 x s8>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 8
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY5]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 8
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY6]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 8
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY7]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 8
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY8]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<64 x s8>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 8
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS8:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY9]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS8]](<64 x s8>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 8
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS9:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY10]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS9]](<64 x s8>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 8
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS10:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY11]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS10]](<64 x s8>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 8
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS11:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY12]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS11]](<64 x s8>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 8
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS12:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY13]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS12]](<64 x s8>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 8
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS13:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY14]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS13]](<64 x s8>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 8
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS14:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[COPY15]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS14]](<64 x s8>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 8
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[CONCAT_VECTORS15:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>), [[DEF1]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS15]](<64 x s8>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 8
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s8), align 8)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s8) into unknown-address + 7)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT8]](s32), [[PTR_ADD7]](p0) :: (store (s8) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT9]](s32), [[PTR_ADD8]](p0) :: (store (s8) into unknown-address + 9)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT10]](s32), [[PTR_ADD9]](p0) :: (store (s8) into unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT11]](s32), [[PTR_ADD10]](p0) :: (store (s8) into unknown-address + 11)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT12]](s32), [[PTR_ADD11]](p0) :: (store (s8) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT13]](s32), [[PTR_ADD12]](p0) :: (store (s8) into unknown-address + 13)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT14]](s32), [[PTR_ADD13]](p0) :: (store (s8) into unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT15]](s32), [[PTR_ADD14]](p0) :: (store (s8) into unknown-address + 15)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s8>), %0(p0) :: (store (<16 x s8>), align 8)
    PseudoRET implicit $lr
...

---
name:            test_v8int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<8 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[COPY1]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[COPY2]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 16
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[COPY3]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<32 x s16>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 16
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[COPY4]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<32 x s16>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 16
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[COPY5]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<32 x s16>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 16
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[COPY6]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<32 x s16>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 16
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[COPY7]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<32 x s16>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 16
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>), [[DEF1]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<32 x s16>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 16
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s16), align 8)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 2)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s16) into unknown-address + 6)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s16) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s16) into unknown-address + 10)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s16) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s16) into unknown-address + 14)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s16>), %0(p0) :: (store (<8 x s16>), align 8)
    PseudoRET implicit $lr
...

---
name:            test_v4int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v4int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[DEF]](<4 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<8 x s32>), [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<8 x s32>), [[COPY3]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<8 x s32>), [[DEF1]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32), [[COPY]](p0) :: (store (s32), align 8)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<4 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<4 x s32>), %0(p0) :: (store (<4 x s32>), align 8)
    PseudoRET implicit $lr
...

---
name:            test_v32int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY1]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY2]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<64 x s8>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 8
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY3]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<64 x s8>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 8
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY4]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<64 x s8>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 8
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY5]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 8
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY6]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 8
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY7]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 8
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY8]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<64 x s8>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 8
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS8:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY9]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS8]](<64 x s8>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 8
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS9:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY10]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS9]](<64 x s8>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 8
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS10:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY11]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS10]](<64 x s8>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 8
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS11:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY12]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS11]](<64 x s8>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 8
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS12:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY13]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS12]](<64 x s8>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 8
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS13:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY14]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS13]](<64 x s8>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 8
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS14:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY15]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS14]](<64 x s8>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 8
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS15:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY16]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS15]](<64 x s8>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 8
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS16:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY17]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS16]](<64 x s8>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT16:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT16]], 8
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS17:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY18]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS17]](<64 x s8>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT17:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT17]], 8
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS18:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY19]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS18]](<64 x s8>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT18:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT18]], 8
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS19:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY20]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS19]](<64 x s8>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT19:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT19]], 8
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS20:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY21]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS20]](<64 x s8>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT20:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT20]], 8
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS21:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY22]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS21]](<64 x s8>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT21:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT21]], 8
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS22:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY23]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS22]](<64 x s8>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT22:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT22]], 8
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS23:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY24]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS23]](<64 x s8>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT23:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT23]], 8
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS24:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY25]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS24]](<64 x s8>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT24:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT24]], 8
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS25:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY26]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS25]](<64 x s8>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT25:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT25]], 8
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS26:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY27]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS26]](<64 x s8>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT26:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT26]], 8
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS27:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY28]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS27]](<64 x s8>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT27:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT27]], 8
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS28:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY29]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS28]](<64 x s8>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT28:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT28]], 8
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS29:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY30]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS29]](<64 x s8>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT29:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT29]], 8
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS30:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY31]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS30]](<64 x s8>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT30:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT30]], 8
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:_(<32 x s8>) = COPY [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[CONCAT_VECTORS31:%[0-9]+]]:_(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[COPY32]](<32 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS31]](<64 x s8>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT31:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT31]], 8
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s8), align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s8) into unknown-address + 7)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT8]](s32), [[PTR_ADD7]](p0) :: (store (s8) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT9]](s32), [[PTR_ADD8]](p0) :: (store (s8) into unknown-address + 9)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT10]](s32), [[PTR_ADD9]](p0) :: (store (s8) into unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT11]](s32), [[PTR_ADD10]](p0) :: (store (s8) into unknown-address + 11)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT12]](s32), [[PTR_ADD11]](p0) :: (store (s8) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT13]](s32), [[PTR_ADD12]](p0) :: (store (s8) into unknown-address + 13)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT14]](s32), [[PTR_ADD13]](p0) :: (store (s8) into unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT15]](s32), [[PTR_ADD14]](p0) :: (store (s8) into unknown-address + 15)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT16]](s32), [[PTR_ADD15]](p0) :: (store (s8) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT17]](s32), [[PTR_ADD16]](p0) :: (store (s8) into unknown-address + 17)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT18]](s32), [[PTR_ADD17]](p0) :: (store (s8) into unknown-address + 18, align 2)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT19]](s32), [[PTR_ADD18]](p0) :: (store (s8) into unknown-address + 19)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT20]](s32), [[PTR_ADD19]](p0) :: (store (s8) into unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 21
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT21]](s32), [[PTR_ADD20]](p0) :: (store (s8) into unknown-address + 21)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT22]](s32), [[PTR_ADD21]](p0) :: (store (s8) into unknown-address + 22, align 2)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT23]](s32), [[PTR_ADD22]](p0) :: (store (s8) into unknown-address + 23)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT24]](s32), [[PTR_ADD23]](p0) :: (store (s8) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 25
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT25]](s32), [[PTR_ADD24]](p0) :: (store (s8) into unknown-address + 25)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT26]](s32), [[PTR_ADD25]](p0) :: (store (s8) into unknown-address + 26, align 2)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 27
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT27]](s32), [[PTR_ADD26]](p0) :: (store (s8) into unknown-address + 27)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT28]](s32), [[PTR_ADD27]](p0) :: (store (s8) into unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 29
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT29]](s32), [[PTR_ADD28]](p0) :: (store (s8) into unknown-address + 29)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT30]](s32), [[PTR_ADD29]](p0) :: (store (s8) into unknown-address + 30, align 2)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 31
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT31]](s32), [[PTR_ADD30]](p0) :: (store (s8) into unknown-address + 31)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s8>), %0(p0) :: (store (<32 x s8>), align 16)
    PseudoRET implicit $lr
...

---
name:            test_v16int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY1]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY2]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 16
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY3]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<32 x s16>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 16
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY4]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<32 x s16>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 16
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY5]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<32 x s16>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 16
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY6]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<32 x s16>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 16
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY7]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<32 x s16>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 16
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY8]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<32 x s16>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 16
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS8:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY9]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS8]](<32 x s16>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 16
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS9:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY10]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS9]](<32 x s16>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 16
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS10:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY11]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS10]](<32 x s16>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 16
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS11:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY12]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS11]](<32 x s16>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 16
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS12:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY13]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS12]](<32 x s16>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 16
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS13:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY14]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS13]](<32 x s16>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 16
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS14:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY15]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS14]](<32 x s16>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 16
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:_(<16 x s16>) = COPY [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[CONCAT_VECTORS15:%[0-9]+]]:_(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[COPY16]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS15]](<32 x s16>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 16
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s16), align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 2)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s16) into unknown-address + 6)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s16) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s16) into unknown-address + 10)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s16) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s16) into unknown-address + 14)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT8]](s32), [[PTR_ADD7]](p0) :: (store (s16) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT9]](s32), [[PTR_ADD8]](p0) :: (store (s16) into unknown-address + 18)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT10]](s32), [[PTR_ADD9]](p0) :: (store (s16) into unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT11]](s32), [[PTR_ADD10]](p0) :: (store (s16) into unknown-address + 22)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT12]](s32), [[PTR_ADD11]](p0) :: (store (s16) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT13]](s32), [[PTR_ADD12]](p0) :: (store (s16) into unknown-address + 26)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT14]](s32), [[PTR_ADD13]](p0) :: (store (s16) into unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT15]](s32), [[PTR_ADD14]](p0) :: (store (s16) into unknown-address + 30)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s16>), %0(p0) :: (store (<16 x s16>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v8int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY3]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY4]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS4:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY5]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS4]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS5:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY6]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS5]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS6:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY7]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS6]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS7:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[COPY8]](<8 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS7]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s32>), %0(p0) :: (store (<8 x s32>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v64int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 8
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 8
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 8
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 8
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 8
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 8
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 8
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 8
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 8
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 8
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 8
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 8
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 8
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 8
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 8
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT16:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT16]], 8
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT17:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT17]], 8
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT18:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT18]], 8
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT19:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT19]], 8
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT20:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT20]], 8
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT21:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT21]], 8
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT22:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT22]], 8
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT23:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT23]], 8
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT24:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT24]], 8
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT25:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT25]], 8
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT26:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT26]], 8
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT27:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT27]], 8
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT28:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT28]], 8
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT29:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT29]], 8
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT30:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT30]], 8
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT31:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT31]], 8
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT32:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C32]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT32:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT32]], 8
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s32) = G_CONSTANT i32 33
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT33:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C33]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT33:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT33]], 8
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s32) = G_CONSTANT i32 34
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT34:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C34]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT34:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT34]], 8
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s32) = G_CONSTANT i32 35
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT35:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C35]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT35:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT35]], 8
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s32) = G_CONSTANT i32 36
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT36:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C36]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT36:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT36]], 8
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s32) = G_CONSTANT i32 37
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT37:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C37]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT37:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT37]], 8
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s32) = G_CONSTANT i32 38
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT38:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C38]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT38:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT38]], 8
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s32) = G_CONSTANT i32 39
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT39:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C39]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT39:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT39]], 8
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s32) = G_CONSTANT i32 40
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT40:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C40]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT40:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT40]], 8
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s32) = G_CONSTANT i32 41
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT41:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C41]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT41:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT41]], 8
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT42:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C42]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT42:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT42]], 8
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s32) = G_CONSTANT i32 43
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT43:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C43]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT43:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT43]], 8
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s32) = G_CONSTANT i32 44
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT44:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C44]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT44:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT44]], 8
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s32) = G_CONSTANT i32 45
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT45:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C45]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT45:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT45]], 8
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s32) = G_CONSTANT i32 46
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT46:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C46]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT46:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT46]], 8
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s32) = G_CONSTANT i32 47
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT47:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C47]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT47:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT47]], 8
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT48:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C48]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT48:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT48]], 8
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s32) = G_CONSTANT i32 49
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT49:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C49]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT49:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT49]], 8
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT50:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C50]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT50:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT50]], 8
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s32) = G_CONSTANT i32 51
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT51:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C51]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT51:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT51]], 8
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s32) = G_CONSTANT i32 52
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT52:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C52]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT52:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT52]], 8
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s32) = G_CONSTANT i32 53
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT53:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C53]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT53:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT53]], 8
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s32) = G_CONSTANT i32 54
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT54:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C54]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT54:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT54]], 8
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s32) = G_CONSTANT i32 55
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT55:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C55]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT55:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT55]], 8
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s32) = G_CONSTANT i32 56
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT56:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C56]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT56:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT56]], 8
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s32) = G_CONSTANT i32 57
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT57:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C57]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT57:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT57]], 8
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s32) = G_CONSTANT i32 58
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT58:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C58]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT58:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT58]], 8
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s32) = G_CONSTANT i32 59
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT59:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C59]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT59:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT59]], 8
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s32) = G_CONSTANT i32 60
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT60:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C60]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT60:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT60]], 8
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s32) = G_CONSTANT i32 61
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT61:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C61]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT61:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT61]], 8
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s32) = G_CONSTANT i32 62
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT62:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C62]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT62:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT62]], 8
    ; CHECK-NEXT: [[C63:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT63:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<64 x s8>), [[C63]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT63:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT63]], 8
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s8), align 16)
    ; CHECK-NEXT: [[C64:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C64]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; CHECK-NEXT: [[C65:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C65]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C66:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C66]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; CHECK-NEXT: [[C67:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C67]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C68:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C68]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; CHECK-NEXT: [[C69:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C69]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C70:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C70]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s8) into unknown-address + 7)
    ; CHECK-NEXT: [[C71:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C71]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT8]](s32), [[PTR_ADD7]](p0) :: (store (s8) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C72:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C72]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT9]](s32), [[PTR_ADD8]](p0) :: (store (s8) into unknown-address + 9)
    ; CHECK-NEXT: [[C73:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C73]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT10]](s32), [[PTR_ADD9]](p0) :: (store (s8) into unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C74:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C74]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT11]](s32), [[PTR_ADD10]](p0) :: (store (s8) into unknown-address + 11)
    ; CHECK-NEXT: [[C75:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C75]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT12]](s32), [[PTR_ADD11]](p0) :: (store (s8) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C76:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C76]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT13]](s32), [[PTR_ADD12]](p0) :: (store (s8) into unknown-address + 13)
    ; CHECK-NEXT: [[C77:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C77]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT14]](s32), [[PTR_ADD13]](p0) :: (store (s8) into unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C78:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C78]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT15]](s32), [[PTR_ADD14]](p0) :: (store (s8) into unknown-address + 15)
    ; CHECK-NEXT: [[C79:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C79]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT16]](s32), [[PTR_ADD15]](p0) :: (store (s8) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C80:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C80]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT17]](s32), [[PTR_ADD16]](p0) :: (store (s8) into unknown-address + 17)
    ; CHECK-NEXT: [[C81:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C81]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT18]](s32), [[PTR_ADD17]](p0) :: (store (s8) into unknown-address + 18, align 2)
    ; CHECK-NEXT: [[C82:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C82]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT19]](s32), [[PTR_ADD18]](p0) :: (store (s8) into unknown-address + 19)
    ; CHECK-NEXT: [[C83:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C83]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT20]](s32), [[PTR_ADD19]](p0) :: (store (s8) into unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C84:%[0-9]+]]:_(s20) = G_CONSTANT i20 21
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C84]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT21]](s32), [[PTR_ADD20]](p0) :: (store (s8) into unknown-address + 21)
    ; CHECK-NEXT: [[C85:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C85]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT22]](s32), [[PTR_ADD21]](p0) :: (store (s8) into unknown-address + 22, align 2)
    ; CHECK-NEXT: [[C86:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C86]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT23]](s32), [[PTR_ADD22]](p0) :: (store (s8) into unknown-address + 23)
    ; CHECK-NEXT: [[C87:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C87]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT24]](s32), [[PTR_ADD23]](p0) :: (store (s8) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C88:%[0-9]+]]:_(s20) = G_CONSTANT i20 25
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C88]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT25]](s32), [[PTR_ADD24]](p0) :: (store (s8) into unknown-address + 25)
    ; CHECK-NEXT: [[C89:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C89]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT26]](s32), [[PTR_ADD25]](p0) :: (store (s8) into unknown-address + 26, align 2)
    ; CHECK-NEXT: [[C90:%[0-9]+]]:_(s20) = G_CONSTANT i20 27
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C90]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT27]](s32), [[PTR_ADD26]](p0) :: (store (s8) into unknown-address + 27)
    ; CHECK-NEXT: [[C91:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C91]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT28]](s32), [[PTR_ADD27]](p0) :: (store (s8) into unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C92:%[0-9]+]]:_(s20) = G_CONSTANT i20 29
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C92]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT29]](s32), [[PTR_ADD28]](p0) :: (store (s8) into unknown-address + 29)
    ; CHECK-NEXT: [[C93:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C93]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT30]](s32), [[PTR_ADD29]](p0) :: (store (s8) into unknown-address + 30, align 2)
    ; CHECK-NEXT: [[C94:%[0-9]+]]:_(s20) = G_CONSTANT i20 31
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C94]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT31]](s32), [[PTR_ADD30]](p0) :: (store (s8) into unknown-address + 31)
    ; CHECK-NEXT: [[C95:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C95]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT32]](s32), [[PTR_ADD31]](p0) :: (store (s8) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C96:%[0-9]+]]:_(s20) = G_CONSTANT i20 33
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C96]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT33]](s32), [[PTR_ADD32]](p0) :: (store (s8) into unknown-address + 33)
    ; CHECK-NEXT: [[C97:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C97]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT34]](s32), [[PTR_ADD33]](p0) :: (store (s8) into unknown-address + 34, align 2)
    ; CHECK-NEXT: [[C98:%[0-9]+]]:_(s20) = G_CONSTANT i20 35
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C98]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT35]](s32), [[PTR_ADD34]](p0) :: (store (s8) into unknown-address + 35)
    ; CHECK-NEXT: [[C99:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C99]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT36]](s32), [[PTR_ADD35]](p0) :: (store (s8) into unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C100:%[0-9]+]]:_(s20) = G_CONSTANT i20 37
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C100]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT37]](s32), [[PTR_ADD36]](p0) :: (store (s8) into unknown-address + 37)
    ; CHECK-NEXT: [[C101:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C101]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT38]](s32), [[PTR_ADD37]](p0) :: (store (s8) into unknown-address + 38, align 2)
    ; CHECK-NEXT: [[C102:%[0-9]+]]:_(s20) = G_CONSTANT i20 39
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C102]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT39]](s32), [[PTR_ADD38]](p0) :: (store (s8) into unknown-address + 39)
    ; CHECK-NEXT: [[C103:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C103]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT40]](s32), [[PTR_ADD39]](p0) :: (store (s8) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C104:%[0-9]+]]:_(s20) = G_CONSTANT i20 41
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C104]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT41]](s32), [[PTR_ADD40]](p0) :: (store (s8) into unknown-address + 41)
    ; CHECK-NEXT: [[C105:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C105]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT42]](s32), [[PTR_ADD41]](p0) :: (store (s8) into unknown-address + 42, align 2)
    ; CHECK-NEXT: [[C106:%[0-9]+]]:_(s20) = G_CONSTANT i20 43
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C106]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT43]](s32), [[PTR_ADD42]](p0) :: (store (s8) into unknown-address + 43)
    ; CHECK-NEXT: [[C107:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C107]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT44]](s32), [[PTR_ADD43]](p0) :: (store (s8) into unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C108:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C108]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT45]](s32), [[PTR_ADD44]](p0) :: (store (s8) into unknown-address + 45)
    ; CHECK-NEXT: [[C109:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C109]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT46]](s32), [[PTR_ADD45]](p0) :: (store (s8) into unknown-address + 46, align 2)
    ; CHECK-NEXT: [[C110:%[0-9]+]]:_(s20) = G_CONSTANT i20 47
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C110]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT47]](s32), [[PTR_ADD46]](p0) :: (store (s8) into unknown-address + 47)
    ; CHECK-NEXT: [[C111:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C111]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT48]](s32), [[PTR_ADD47]](p0) :: (store (s8) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C112:%[0-9]+]]:_(s20) = G_CONSTANT i20 49
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C112]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT49]](s32), [[PTR_ADD48]](p0) :: (store (s8) into unknown-address + 49)
    ; CHECK-NEXT: [[C113:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C113]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT50]](s32), [[PTR_ADD49]](p0) :: (store (s8) into unknown-address + 50, align 2)
    ; CHECK-NEXT: [[C114:%[0-9]+]]:_(s20) = G_CONSTANT i20 51
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C114]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT51]](s32), [[PTR_ADD50]](p0) :: (store (s8) into unknown-address + 51)
    ; CHECK-NEXT: [[C115:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C115]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT52]](s32), [[PTR_ADD51]](p0) :: (store (s8) into unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C116:%[0-9]+]]:_(s20) = G_CONSTANT i20 53
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C116]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT53]](s32), [[PTR_ADD52]](p0) :: (store (s8) into unknown-address + 53)
    ; CHECK-NEXT: [[C117:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C117]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT54]](s32), [[PTR_ADD53]](p0) :: (store (s8) into unknown-address + 54, align 2)
    ; CHECK-NEXT: [[C118:%[0-9]+]]:_(s20) = G_CONSTANT i20 55
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C118]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT55]](s32), [[PTR_ADD54]](p0) :: (store (s8) into unknown-address + 55)
    ; CHECK-NEXT: [[C119:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C119]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT56]](s32), [[PTR_ADD55]](p0) :: (store (s8) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C120:%[0-9]+]]:_(s20) = G_CONSTANT i20 57
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C120]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT57]](s32), [[PTR_ADD56]](p0) :: (store (s8) into unknown-address + 57)
    ; CHECK-NEXT: [[C121:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C121]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT58]](s32), [[PTR_ADD57]](p0) :: (store (s8) into unknown-address + 58, align 2)
    ; CHECK-NEXT: [[C122:%[0-9]+]]:_(s20) = G_CONSTANT i20 59
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C122]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT59]](s32), [[PTR_ADD58]](p0) :: (store (s8) into unknown-address + 59)
    ; CHECK-NEXT: [[C123:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C123]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT60]](s32), [[PTR_ADD59]](p0) :: (store (s8) into unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C124:%[0-9]+]]:_(s20) = G_CONSTANT i20 61
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C124]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT61]](s32), [[PTR_ADD60]](p0) :: (store (s8) into unknown-address + 61)
    ; CHECK-NEXT: [[C125:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C125]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT62]](s32), [[PTR_ADD61]](p0) :: (store (s8) into unknown-address + 62, align 2)
    ; CHECK-NEXT: [[C126:%[0-9]+]]:_(s20) = G_CONSTANT i20 63
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C126]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT63]](s32), [[PTR_ADD62]](p0) :: (store (s8) into unknown-address + 63)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s8>), %0(p0) :: (store (<64 x s8>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v32int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 16
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 16
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 16
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 16
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 16
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 16
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 16
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 16
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 16
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 16
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 16
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 16
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 16
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 16
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 16
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT16:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT16]], 16
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT17:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT17]], 16
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT18:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT18]], 16
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT19:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT19]], 16
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT20:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT20]], 16
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT21:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT21]], 16
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT22:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT22]], 16
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT23:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT23]], 16
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT24:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT24]], 16
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT25:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT25]], 16
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT26:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT26]], 16
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT27:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT27]], 16
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT28:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT28]], 16
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT29:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT29]], 16
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT30:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT30]], 16
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<32 x s16>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT31:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT31]], 16
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s16), align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 2)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s16) into unknown-address + 6)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s16) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s16) into unknown-address + 10)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s16) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s16) into unknown-address + 14)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT8]](s32), [[PTR_ADD7]](p0) :: (store (s16) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT9]](s32), [[PTR_ADD8]](p0) :: (store (s16) into unknown-address + 18)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT10]](s32), [[PTR_ADD9]](p0) :: (store (s16) into unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT11]](s32), [[PTR_ADD10]](p0) :: (store (s16) into unknown-address + 22)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT12]](s32), [[PTR_ADD11]](p0) :: (store (s16) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT13]](s32), [[PTR_ADD12]](p0) :: (store (s16) into unknown-address + 26)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT14]](s32), [[PTR_ADD13]](p0) :: (store (s16) into unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT15]](s32), [[PTR_ADD14]](p0) :: (store (s16) into unknown-address + 30)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT16]](s32), [[PTR_ADD15]](p0) :: (store (s16) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT17]](s32), [[PTR_ADD16]](p0) :: (store (s16) into unknown-address + 34)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT18]](s32), [[PTR_ADD17]](p0) :: (store (s16) into unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT19]](s32), [[PTR_ADD18]](p0) :: (store (s16) into unknown-address + 38)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT20]](s32), [[PTR_ADD19]](p0) :: (store (s16) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT21]](s32), [[PTR_ADD20]](p0) :: (store (s16) into unknown-address + 42)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT22]](s32), [[PTR_ADD21]](p0) :: (store (s16) into unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT23]](s32), [[PTR_ADD22]](p0) :: (store (s16) into unknown-address + 46)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT24]](s32), [[PTR_ADD23]](p0) :: (store (s16) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT25]](s32), [[PTR_ADD24]](p0) :: (store (s16) into unknown-address + 50)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT26]](s32), [[PTR_ADD25]](p0) :: (store (s16) into unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT27]](s32), [[PTR_ADD26]](p0) :: (store (s16) into unknown-address + 54)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT28]](s32), [[PTR_ADD27]](p0) :: (store (s16) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT29]](s32), [[PTR_ADD28]](p0) :: (store (s16) into unknown-address + 58)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT30]](s32), [[PTR_ADD29]](p0) :: (store (s16) into unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT31]](s32), [[PTR_ADD30]](p0) :: (store (s16) into unknown-address + 62)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s16>), %0(p0) :: (store (<32 x s16>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v16int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s32>), %0(p0) :: (store (<16 x s32>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v128int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v128int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<128 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<64 x s8>), [[UV1:%[0-9]+]]:_(<64 x s8>) = G_UNMERGE_VALUES [[DEF]](<128 x s8>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 8
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 8
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 8
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 8
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 8
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 8
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 8
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 8
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 8
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 8
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 8
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 8
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 8
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 8
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 8
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 8
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT16:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT16]], 8
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT17:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT17]], 8
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT18:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT18]], 8
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT19:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT19]], 8
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT20:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT20]], 8
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT21:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT21]], 8
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT22:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT22]], 8
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT23:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT23]], 8
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT24:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT24]], 8
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT25:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT25]], 8
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT26:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT26]], 8
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT27:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT27]], 8
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT28:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT28]], 8
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT29:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT29]], 8
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT30:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT30]], 8
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT31:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT31]], 8
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT32:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C32]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT32:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT32]], 8
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s32) = G_CONSTANT i32 33
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT33:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C33]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT33:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT33]], 8
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s32) = G_CONSTANT i32 34
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT34:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C34]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT34:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT34]], 8
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s32) = G_CONSTANT i32 35
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT35:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C35]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT35:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT35]], 8
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s32) = G_CONSTANT i32 36
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT36:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C36]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT36:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT36]], 8
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s32) = G_CONSTANT i32 37
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT37:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C37]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT37:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT37]], 8
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s32) = G_CONSTANT i32 38
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT38:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C38]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT38:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT38]], 8
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s32) = G_CONSTANT i32 39
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT39:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C39]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT39:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT39]], 8
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s32) = G_CONSTANT i32 40
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT40:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C40]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT40:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT40]], 8
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s32) = G_CONSTANT i32 41
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT41:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C41]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT41:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT41]], 8
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT42:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C42]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT42:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT42]], 8
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s32) = G_CONSTANT i32 43
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT43:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C43]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT43:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT43]], 8
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s32) = G_CONSTANT i32 44
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT44:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C44]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT44:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT44]], 8
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s32) = G_CONSTANT i32 45
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT45:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C45]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT45:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT45]], 8
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s32) = G_CONSTANT i32 46
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT46:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C46]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT46:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT46]], 8
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s32) = G_CONSTANT i32 47
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT47:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C47]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT47:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT47]], 8
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT48:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C48]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT48:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT48]], 8
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s32) = G_CONSTANT i32 49
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT49:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C49]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT49:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT49]], 8
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT50:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C50]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT50:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT50]], 8
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s32) = G_CONSTANT i32 51
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT51:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C51]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT51:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT51]], 8
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s32) = G_CONSTANT i32 52
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT52:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C52]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT52:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT52]], 8
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s32) = G_CONSTANT i32 53
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT53:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C53]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT53:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT53]], 8
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s32) = G_CONSTANT i32 54
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT54:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C54]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT54:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT54]], 8
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s32) = G_CONSTANT i32 55
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT55:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C55]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT55:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT55]], 8
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s32) = G_CONSTANT i32 56
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT56:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C56]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT56:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT56]], 8
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s32) = G_CONSTANT i32 57
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT57:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C57]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT57:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT57]], 8
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s32) = G_CONSTANT i32 58
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT58:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C58]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT58:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT58]], 8
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s32) = G_CONSTANT i32 59
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT59:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C59]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT59:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT59]], 8
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s32) = G_CONSTANT i32 60
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT60:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C60]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT60:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT60]], 8
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s32) = G_CONSTANT i32 61
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT61:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C61]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT61:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT61]], 8
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s32) = G_CONSTANT i32 62
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT62:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C62]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT62:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT62]], 8
    ; CHECK-NEXT: [[C63:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT63:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<64 x s8>), [[C63]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT63:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT63]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT64:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT64:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT64]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT65:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT65:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT65]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT66:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT66:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT66]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT67:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT67:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT67]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT68:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT68:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT68]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT69:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT69:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT69]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT70:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT70:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT70]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT71:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT71:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT71]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT72:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT72:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT72]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT73:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT73:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT73]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT74:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT74:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT74]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT75:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT75:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT75]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT76:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT76:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT76]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT77:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT77:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT77]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT78:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT78:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT78]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT79:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT79:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT79]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT80:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT80:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT80]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT81:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT81:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT81]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT82:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT82:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT82]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT83:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT83:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT83]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT84:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT84:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT84]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT85:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT85:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT85]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT86:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT86:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT86]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT87:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT87:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT87]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT88:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT88:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT88]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT89:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT89:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT89]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT90:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT90:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT90]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT91:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT91:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT91]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT92:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT92:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT92]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT93:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT93:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT93]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT94:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT94:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT94]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT95:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT95:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT95]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT96:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C32]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT96:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT96]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT97:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C33]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT97:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT97]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT98:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C34]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT98:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT98]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT99:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C35]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT99:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT99]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT100:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C36]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT100:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT100]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT101:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C37]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT101:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT101]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT102:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C38]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT102:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT102]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT103:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C39]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT103:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT103]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT104:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C40]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT104:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT104]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT105:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C41]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT105:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT105]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT106:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C42]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT106:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT106]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT107:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C43]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT107:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT107]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT108:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C44]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT108:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT108]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT109:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C45]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT109:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT109]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT110:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C46]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT110:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT110]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT111:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C47]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT111:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT111]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT112:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C48]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT112:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT112]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT113:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C49]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT113:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT113]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT114:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C50]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT114:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT114]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT115:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C51]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT115:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT115]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT116:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C52]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT116:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT116]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT117:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C53]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT117:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT117]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT118:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C54]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT118:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT118]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT119:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C55]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT119:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT119]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT120:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C56]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT120:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT120]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT121:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C57]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT121:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT121]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT122:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C58]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT122:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT122]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT123:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C59]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT123:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT123]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT124:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C60]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT124:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT124]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT125:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C61]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT125:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT125]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT126:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C62]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT126:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT126]], 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT127:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<64 x s8>), [[C63]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT127:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT127]], 8
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s8), align 16)
    ; CHECK-NEXT: [[C64:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C64]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s8) into unknown-address + 1)
    ; CHECK-NEXT: [[C65:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C65]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s8) into unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C66:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C66]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s8) into unknown-address + 3)
    ; CHECK-NEXT: [[C67:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C67]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s8) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C68:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C68]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s8) into unknown-address + 5)
    ; CHECK-NEXT: [[C69:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C69]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s8) into unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C70:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C70]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s8) into unknown-address + 7)
    ; CHECK-NEXT: [[C71:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C71]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT8]](s32), [[PTR_ADD7]](p0) :: (store (s8) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C72:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C72]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT9]](s32), [[PTR_ADD8]](p0) :: (store (s8) into unknown-address + 9)
    ; CHECK-NEXT: [[C73:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C73]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT10]](s32), [[PTR_ADD9]](p0) :: (store (s8) into unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C74:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C74]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT11]](s32), [[PTR_ADD10]](p0) :: (store (s8) into unknown-address + 11)
    ; CHECK-NEXT: [[C75:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C75]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT12]](s32), [[PTR_ADD11]](p0) :: (store (s8) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C76:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C76]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT13]](s32), [[PTR_ADD12]](p0) :: (store (s8) into unknown-address + 13)
    ; CHECK-NEXT: [[C77:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C77]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT14]](s32), [[PTR_ADD13]](p0) :: (store (s8) into unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C78:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C78]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT15]](s32), [[PTR_ADD14]](p0) :: (store (s8) into unknown-address + 15)
    ; CHECK-NEXT: [[C79:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C79]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT16]](s32), [[PTR_ADD15]](p0) :: (store (s8) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C80:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C80]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT17]](s32), [[PTR_ADD16]](p0) :: (store (s8) into unknown-address + 17)
    ; CHECK-NEXT: [[C81:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C81]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT18]](s32), [[PTR_ADD17]](p0) :: (store (s8) into unknown-address + 18, align 2)
    ; CHECK-NEXT: [[C82:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C82]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT19]](s32), [[PTR_ADD18]](p0) :: (store (s8) into unknown-address + 19)
    ; CHECK-NEXT: [[C83:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C83]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT20]](s32), [[PTR_ADD19]](p0) :: (store (s8) into unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C84:%[0-9]+]]:_(s20) = G_CONSTANT i20 21
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C84]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT21]](s32), [[PTR_ADD20]](p0) :: (store (s8) into unknown-address + 21)
    ; CHECK-NEXT: [[C85:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C85]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT22]](s32), [[PTR_ADD21]](p0) :: (store (s8) into unknown-address + 22, align 2)
    ; CHECK-NEXT: [[C86:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C86]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT23]](s32), [[PTR_ADD22]](p0) :: (store (s8) into unknown-address + 23)
    ; CHECK-NEXT: [[C87:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C87]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT24]](s32), [[PTR_ADD23]](p0) :: (store (s8) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C88:%[0-9]+]]:_(s20) = G_CONSTANT i20 25
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C88]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT25]](s32), [[PTR_ADD24]](p0) :: (store (s8) into unknown-address + 25)
    ; CHECK-NEXT: [[C89:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C89]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT26]](s32), [[PTR_ADD25]](p0) :: (store (s8) into unknown-address + 26, align 2)
    ; CHECK-NEXT: [[C90:%[0-9]+]]:_(s20) = G_CONSTANT i20 27
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C90]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT27]](s32), [[PTR_ADD26]](p0) :: (store (s8) into unknown-address + 27)
    ; CHECK-NEXT: [[C91:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C91]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT28]](s32), [[PTR_ADD27]](p0) :: (store (s8) into unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C92:%[0-9]+]]:_(s20) = G_CONSTANT i20 29
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C92]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT29]](s32), [[PTR_ADD28]](p0) :: (store (s8) into unknown-address + 29)
    ; CHECK-NEXT: [[C93:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C93]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT30]](s32), [[PTR_ADD29]](p0) :: (store (s8) into unknown-address + 30, align 2)
    ; CHECK-NEXT: [[C94:%[0-9]+]]:_(s20) = G_CONSTANT i20 31
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C94]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT31]](s32), [[PTR_ADD30]](p0) :: (store (s8) into unknown-address + 31)
    ; CHECK-NEXT: [[C95:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C95]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT32]](s32), [[PTR_ADD31]](p0) :: (store (s8) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C96:%[0-9]+]]:_(s20) = G_CONSTANT i20 33
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C96]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT33]](s32), [[PTR_ADD32]](p0) :: (store (s8) into unknown-address + 33)
    ; CHECK-NEXT: [[C97:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C97]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT34]](s32), [[PTR_ADD33]](p0) :: (store (s8) into unknown-address + 34, align 2)
    ; CHECK-NEXT: [[C98:%[0-9]+]]:_(s20) = G_CONSTANT i20 35
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C98]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT35]](s32), [[PTR_ADD34]](p0) :: (store (s8) into unknown-address + 35)
    ; CHECK-NEXT: [[C99:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C99]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT36]](s32), [[PTR_ADD35]](p0) :: (store (s8) into unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C100:%[0-9]+]]:_(s20) = G_CONSTANT i20 37
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C100]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT37]](s32), [[PTR_ADD36]](p0) :: (store (s8) into unknown-address + 37)
    ; CHECK-NEXT: [[C101:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C101]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT38]](s32), [[PTR_ADD37]](p0) :: (store (s8) into unknown-address + 38, align 2)
    ; CHECK-NEXT: [[C102:%[0-9]+]]:_(s20) = G_CONSTANT i20 39
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C102]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT39]](s32), [[PTR_ADD38]](p0) :: (store (s8) into unknown-address + 39)
    ; CHECK-NEXT: [[C103:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C103]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT40]](s32), [[PTR_ADD39]](p0) :: (store (s8) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C104:%[0-9]+]]:_(s20) = G_CONSTANT i20 41
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C104]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT41]](s32), [[PTR_ADD40]](p0) :: (store (s8) into unknown-address + 41)
    ; CHECK-NEXT: [[C105:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C105]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT42]](s32), [[PTR_ADD41]](p0) :: (store (s8) into unknown-address + 42, align 2)
    ; CHECK-NEXT: [[C106:%[0-9]+]]:_(s20) = G_CONSTANT i20 43
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C106]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT43]](s32), [[PTR_ADD42]](p0) :: (store (s8) into unknown-address + 43)
    ; CHECK-NEXT: [[C107:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C107]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT44]](s32), [[PTR_ADD43]](p0) :: (store (s8) into unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C108:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C108]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT45]](s32), [[PTR_ADD44]](p0) :: (store (s8) into unknown-address + 45)
    ; CHECK-NEXT: [[C109:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C109]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT46]](s32), [[PTR_ADD45]](p0) :: (store (s8) into unknown-address + 46, align 2)
    ; CHECK-NEXT: [[C110:%[0-9]+]]:_(s20) = G_CONSTANT i20 47
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C110]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT47]](s32), [[PTR_ADD46]](p0) :: (store (s8) into unknown-address + 47)
    ; CHECK-NEXT: [[C111:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C111]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT48]](s32), [[PTR_ADD47]](p0) :: (store (s8) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C112:%[0-9]+]]:_(s20) = G_CONSTANT i20 49
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C112]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT49]](s32), [[PTR_ADD48]](p0) :: (store (s8) into unknown-address + 49)
    ; CHECK-NEXT: [[C113:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C113]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT50]](s32), [[PTR_ADD49]](p0) :: (store (s8) into unknown-address + 50, align 2)
    ; CHECK-NEXT: [[C114:%[0-9]+]]:_(s20) = G_CONSTANT i20 51
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C114]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT51]](s32), [[PTR_ADD50]](p0) :: (store (s8) into unknown-address + 51)
    ; CHECK-NEXT: [[C115:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C115]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT52]](s32), [[PTR_ADD51]](p0) :: (store (s8) into unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C116:%[0-9]+]]:_(s20) = G_CONSTANT i20 53
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C116]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT53]](s32), [[PTR_ADD52]](p0) :: (store (s8) into unknown-address + 53)
    ; CHECK-NEXT: [[C117:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C117]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT54]](s32), [[PTR_ADD53]](p0) :: (store (s8) into unknown-address + 54, align 2)
    ; CHECK-NEXT: [[C118:%[0-9]+]]:_(s20) = G_CONSTANT i20 55
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C118]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT55]](s32), [[PTR_ADD54]](p0) :: (store (s8) into unknown-address + 55)
    ; CHECK-NEXT: [[C119:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C119]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT56]](s32), [[PTR_ADD55]](p0) :: (store (s8) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C120:%[0-9]+]]:_(s20) = G_CONSTANT i20 57
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C120]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT57]](s32), [[PTR_ADD56]](p0) :: (store (s8) into unknown-address + 57)
    ; CHECK-NEXT: [[C121:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C121]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT58]](s32), [[PTR_ADD57]](p0) :: (store (s8) into unknown-address + 58, align 2)
    ; CHECK-NEXT: [[C122:%[0-9]+]]:_(s20) = G_CONSTANT i20 59
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C122]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT59]](s32), [[PTR_ADD58]](p0) :: (store (s8) into unknown-address + 59)
    ; CHECK-NEXT: [[C123:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C123]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT60]](s32), [[PTR_ADD59]](p0) :: (store (s8) into unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C124:%[0-9]+]]:_(s20) = G_CONSTANT i20 61
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C124]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT61]](s32), [[PTR_ADD60]](p0) :: (store (s8) into unknown-address + 61)
    ; CHECK-NEXT: [[C125:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C125]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT62]](s32), [[PTR_ADD61]](p0) :: (store (s8) into unknown-address + 62, align 2)
    ; CHECK-NEXT: [[C126:%[0-9]+]]:_(s20) = G_CONSTANT i20 63
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C126]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT63]](s32), [[PTR_ADD62]](p0) :: (store (s8) into unknown-address + 63)
    ; CHECK-NEXT: [[C127:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD63:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C127]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT64]](s32), [[PTR_ADD63]](p0) :: (store (s8) into unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C128:%[0-9]+]]:_(s20) = G_CONSTANT i20 65
    ; CHECK-NEXT: [[PTR_ADD64:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C128]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT65]](s32), [[PTR_ADD64]](p0) :: (store (s8) into unknown-address + 65)
    ; CHECK-NEXT: [[C129:%[0-9]+]]:_(s20) = G_CONSTANT i20 66
    ; CHECK-NEXT: [[PTR_ADD65:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C129]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT66]](s32), [[PTR_ADD65]](p0) :: (store (s8) into unknown-address + 66, align 2)
    ; CHECK-NEXT: [[C130:%[0-9]+]]:_(s20) = G_CONSTANT i20 67
    ; CHECK-NEXT: [[PTR_ADD66:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C130]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT67]](s32), [[PTR_ADD66]](p0) :: (store (s8) into unknown-address + 67)
    ; CHECK-NEXT: [[C131:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD67:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C131]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT68]](s32), [[PTR_ADD67]](p0) :: (store (s8) into unknown-address + 68, align 4)
    ; CHECK-NEXT: [[C132:%[0-9]+]]:_(s20) = G_CONSTANT i20 69
    ; CHECK-NEXT: [[PTR_ADD68:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C132]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT69]](s32), [[PTR_ADD68]](p0) :: (store (s8) into unknown-address + 69)
    ; CHECK-NEXT: [[C133:%[0-9]+]]:_(s20) = G_CONSTANT i20 70
    ; CHECK-NEXT: [[PTR_ADD69:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C133]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT70]](s32), [[PTR_ADD69]](p0) :: (store (s8) into unknown-address + 70, align 2)
    ; CHECK-NEXT: [[C134:%[0-9]+]]:_(s20) = G_CONSTANT i20 71
    ; CHECK-NEXT: [[PTR_ADD70:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C134]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT71]](s32), [[PTR_ADD70]](p0) :: (store (s8) into unknown-address + 71)
    ; CHECK-NEXT: [[C135:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD71:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C135]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT72]](s32), [[PTR_ADD71]](p0) :: (store (s8) into unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C136:%[0-9]+]]:_(s20) = G_CONSTANT i20 73
    ; CHECK-NEXT: [[PTR_ADD72:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C136]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT73]](s32), [[PTR_ADD72]](p0) :: (store (s8) into unknown-address + 73)
    ; CHECK-NEXT: [[C137:%[0-9]+]]:_(s20) = G_CONSTANT i20 74
    ; CHECK-NEXT: [[PTR_ADD73:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C137]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT74]](s32), [[PTR_ADD73]](p0) :: (store (s8) into unknown-address + 74, align 2)
    ; CHECK-NEXT: [[C138:%[0-9]+]]:_(s20) = G_CONSTANT i20 75
    ; CHECK-NEXT: [[PTR_ADD74:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C138]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT75]](s32), [[PTR_ADD74]](p0) :: (store (s8) into unknown-address + 75)
    ; CHECK-NEXT: [[C139:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD75:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C139]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT76]](s32), [[PTR_ADD75]](p0) :: (store (s8) into unknown-address + 76, align 4)
    ; CHECK-NEXT: [[C140:%[0-9]+]]:_(s20) = G_CONSTANT i20 77
    ; CHECK-NEXT: [[PTR_ADD76:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C140]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT77]](s32), [[PTR_ADD76]](p0) :: (store (s8) into unknown-address + 77)
    ; CHECK-NEXT: [[C141:%[0-9]+]]:_(s20) = G_CONSTANT i20 78
    ; CHECK-NEXT: [[PTR_ADD77:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C141]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT78]](s32), [[PTR_ADD77]](p0) :: (store (s8) into unknown-address + 78, align 2)
    ; CHECK-NEXT: [[C142:%[0-9]+]]:_(s20) = G_CONSTANT i20 79
    ; CHECK-NEXT: [[PTR_ADD78:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C142]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT79]](s32), [[PTR_ADD78]](p0) :: (store (s8) into unknown-address + 79)
    ; CHECK-NEXT: [[C143:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD79:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C143]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT80]](s32), [[PTR_ADD79]](p0) :: (store (s8) into unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C144:%[0-9]+]]:_(s20) = G_CONSTANT i20 81
    ; CHECK-NEXT: [[PTR_ADD80:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C144]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT81]](s32), [[PTR_ADD80]](p0) :: (store (s8) into unknown-address + 81)
    ; CHECK-NEXT: [[C145:%[0-9]+]]:_(s20) = G_CONSTANT i20 82
    ; CHECK-NEXT: [[PTR_ADD81:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C145]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT82]](s32), [[PTR_ADD81]](p0) :: (store (s8) into unknown-address + 82, align 2)
    ; CHECK-NEXT: [[C146:%[0-9]+]]:_(s20) = G_CONSTANT i20 83
    ; CHECK-NEXT: [[PTR_ADD82:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C146]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT83]](s32), [[PTR_ADD82]](p0) :: (store (s8) into unknown-address + 83)
    ; CHECK-NEXT: [[C147:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD83:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C147]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT84]](s32), [[PTR_ADD83]](p0) :: (store (s8) into unknown-address + 84, align 4)
    ; CHECK-NEXT: [[C148:%[0-9]+]]:_(s20) = G_CONSTANT i20 85
    ; CHECK-NEXT: [[PTR_ADD84:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C148]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT85]](s32), [[PTR_ADD84]](p0) :: (store (s8) into unknown-address + 85)
    ; CHECK-NEXT: [[C149:%[0-9]+]]:_(s20) = G_CONSTANT i20 86
    ; CHECK-NEXT: [[PTR_ADD85:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C149]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT86]](s32), [[PTR_ADD85]](p0) :: (store (s8) into unknown-address + 86, align 2)
    ; CHECK-NEXT: [[C150:%[0-9]+]]:_(s20) = G_CONSTANT i20 87
    ; CHECK-NEXT: [[PTR_ADD86:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C150]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT87]](s32), [[PTR_ADD86]](p0) :: (store (s8) into unknown-address + 87)
    ; CHECK-NEXT: [[C151:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD87:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C151]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT88]](s32), [[PTR_ADD87]](p0) :: (store (s8) into unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C152:%[0-9]+]]:_(s20) = G_CONSTANT i20 89
    ; CHECK-NEXT: [[PTR_ADD88:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C152]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT89]](s32), [[PTR_ADD88]](p0) :: (store (s8) into unknown-address + 89)
    ; CHECK-NEXT: [[C153:%[0-9]+]]:_(s20) = G_CONSTANT i20 90
    ; CHECK-NEXT: [[PTR_ADD89:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C153]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT90]](s32), [[PTR_ADD89]](p0) :: (store (s8) into unknown-address + 90, align 2)
    ; CHECK-NEXT: [[C154:%[0-9]+]]:_(s20) = G_CONSTANT i20 91
    ; CHECK-NEXT: [[PTR_ADD90:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C154]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT91]](s32), [[PTR_ADD90]](p0) :: (store (s8) into unknown-address + 91)
    ; CHECK-NEXT: [[C155:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD91:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C155]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT92]](s32), [[PTR_ADD91]](p0) :: (store (s8) into unknown-address + 92, align 4)
    ; CHECK-NEXT: [[C156:%[0-9]+]]:_(s20) = G_CONSTANT i20 93
    ; CHECK-NEXT: [[PTR_ADD92:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C156]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT93]](s32), [[PTR_ADD92]](p0) :: (store (s8) into unknown-address + 93)
    ; CHECK-NEXT: [[C157:%[0-9]+]]:_(s20) = G_CONSTANT i20 94
    ; CHECK-NEXT: [[PTR_ADD93:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C157]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT94]](s32), [[PTR_ADD93]](p0) :: (store (s8) into unknown-address + 94, align 2)
    ; CHECK-NEXT: [[C158:%[0-9]+]]:_(s20) = G_CONSTANT i20 95
    ; CHECK-NEXT: [[PTR_ADD94:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C158]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT95]](s32), [[PTR_ADD94]](p0) :: (store (s8) into unknown-address + 95)
    ; CHECK-NEXT: [[C159:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD95:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C159]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT96]](s32), [[PTR_ADD95]](p0) :: (store (s8) into unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C160:%[0-9]+]]:_(s20) = G_CONSTANT i20 97
    ; CHECK-NEXT: [[PTR_ADD96:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C160]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT97]](s32), [[PTR_ADD96]](p0) :: (store (s8) into unknown-address + 97)
    ; CHECK-NEXT: [[C161:%[0-9]+]]:_(s20) = G_CONSTANT i20 98
    ; CHECK-NEXT: [[PTR_ADD97:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C161]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT98]](s32), [[PTR_ADD97]](p0) :: (store (s8) into unknown-address + 98, align 2)
    ; CHECK-NEXT: [[C162:%[0-9]+]]:_(s20) = G_CONSTANT i20 99
    ; CHECK-NEXT: [[PTR_ADD98:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C162]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT99]](s32), [[PTR_ADD98]](p0) :: (store (s8) into unknown-address + 99)
    ; CHECK-NEXT: [[C163:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD99:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C163]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT100]](s32), [[PTR_ADD99]](p0) :: (store (s8) into unknown-address + 100, align 4)
    ; CHECK-NEXT: [[C164:%[0-9]+]]:_(s20) = G_CONSTANT i20 101
    ; CHECK-NEXT: [[PTR_ADD100:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C164]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT101]](s32), [[PTR_ADD100]](p0) :: (store (s8) into unknown-address + 101)
    ; CHECK-NEXT: [[C165:%[0-9]+]]:_(s20) = G_CONSTANT i20 102
    ; CHECK-NEXT: [[PTR_ADD101:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C165]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT102]](s32), [[PTR_ADD101]](p0) :: (store (s8) into unknown-address + 102, align 2)
    ; CHECK-NEXT: [[C166:%[0-9]+]]:_(s20) = G_CONSTANT i20 103
    ; CHECK-NEXT: [[PTR_ADD102:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C166]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT103]](s32), [[PTR_ADD102]](p0) :: (store (s8) into unknown-address + 103)
    ; CHECK-NEXT: [[C167:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD103:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C167]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT104]](s32), [[PTR_ADD103]](p0) :: (store (s8) into unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C168:%[0-9]+]]:_(s20) = G_CONSTANT i20 105
    ; CHECK-NEXT: [[PTR_ADD104:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C168]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT105]](s32), [[PTR_ADD104]](p0) :: (store (s8) into unknown-address + 105)
    ; CHECK-NEXT: [[C169:%[0-9]+]]:_(s20) = G_CONSTANT i20 106
    ; CHECK-NEXT: [[PTR_ADD105:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C169]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT106]](s32), [[PTR_ADD105]](p0) :: (store (s8) into unknown-address + 106, align 2)
    ; CHECK-NEXT: [[C170:%[0-9]+]]:_(s20) = G_CONSTANT i20 107
    ; CHECK-NEXT: [[PTR_ADD106:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C170]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT107]](s32), [[PTR_ADD106]](p0) :: (store (s8) into unknown-address + 107)
    ; CHECK-NEXT: [[C171:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD107:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C171]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT108]](s32), [[PTR_ADD107]](p0) :: (store (s8) into unknown-address + 108, align 4)
    ; CHECK-NEXT: [[C172:%[0-9]+]]:_(s20) = G_CONSTANT i20 109
    ; CHECK-NEXT: [[PTR_ADD108:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C172]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT109]](s32), [[PTR_ADD108]](p0) :: (store (s8) into unknown-address + 109)
    ; CHECK-NEXT: [[C173:%[0-9]+]]:_(s20) = G_CONSTANT i20 110
    ; CHECK-NEXT: [[PTR_ADD109:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C173]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT110]](s32), [[PTR_ADD109]](p0) :: (store (s8) into unknown-address + 110, align 2)
    ; CHECK-NEXT: [[C174:%[0-9]+]]:_(s20) = G_CONSTANT i20 111
    ; CHECK-NEXT: [[PTR_ADD110:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C174]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT111]](s32), [[PTR_ADD110]](p0) :: (store (s8) into unknown-address + 111)
    ; CHECK-NEXT: [[C175:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD111:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C175]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT112]](s32), [[PTR_ADD111]](p0) :: (store (s8) into unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C176:%[0-9]+]]:_(s20) = G_CONSTANT i20 113
    ; CHECK-NEXT: [[PTR_ADD112:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C176]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT113]](s32), [[PTR_ADD112]](p0) :: (store (s8) into unknown-address + 113)
    ; CHECK-NEXT: [[C177:%[0-9]+]]:_(s20) = G_CONSTANT i20 114
    ; CHECK-NEXT: [[PTR_ADD113:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C177]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT114]](s32), [[PTR_ADD113]](p0) :: (store (s8) into unknown-address + 114, align 2)
    ; CHECK-NEXT: [[C178:%[0-9]+]]:_(s20) = G_CONSTANT i20 115
    ; CHECK-NEXT: [[PTR_ADD114:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C178]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT115]](s32), [[PTR_ADD114]](p0) :: (store (s8) into unknown-address + 115)
    ; CHECK-NEXT: [[C179:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD115:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C179]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT116]](s32), [[PTR_ADD115]](p0) :: (store (s8) into unknown-address + 116, align 4)
    ; CHECK-NEXT: [[C180:%[0-9]+]]:_(s20) = G_CONSTANT i20 117
    ; CHECK-NEXT: [[PTR_ADD116:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C180]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT117]](s32), [[PTR_ADD116]](p0) :: (store (s8) into unknown-address + 117)
    ; CHECK-NEXT: [[C181:%[0-9]+]]:_(s20) = G_CONSTANT i20 118
    ; CHECK-NEXT: [[PTR_ADD117:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C181]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT118]](s32), [[PTR_ADD117]](p0) :: (store (s8) into unknown-address + 118, align 2)
    ; CHECK-NEXT: [[C182:%[0-9]+]]:_(s20) = G_CONSTANT i20 119
    ; CHECK-NEXT: [[PTR_ADD118:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C182]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT119]](s32), [[PTR_ADD118]](p0) :: (store (s8) into unknown-address + 119)
    ; CHECK-NEXT: [[C183:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD119:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C183]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT120]](s32), [[PTR_ADD119]](p0) :: (store (s8) into unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C184:%[0-9]+]]:_(s20) = G_CONSTANT i20 121
    ; CHECK-NEXT: [[PTR_ADD120:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C184]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT121]](s32), [[PTR_ADD120]](p0) :: (store (s8) into unknown-address + 121)
    ; CHECK-NEXT: [[C185:%[0-9]+]]:_(s20) = G_CONSTANT i20 122
    ; CHECK-NEXT: [[PTR_ADD121:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C185]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT122]](s32), [[PTR_ADD121]](p0) :: (store (s8) into unknown-address + 122, align 2)
    ; CHECK-NEXT: [[C186:%[0-9]+]]:_(s20) = G_CONSTANT i20 123
    ; CHECK-NEXT: [[PTR_ADD122:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C186]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT123]](s32), [[PTR_ADD122]](p0) :: (store (s8) into unknown-address + 123)
    ; CHECK-NEXT: [[C187:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD123:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C187]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT124]](s32), [[PTR_ADD123]](p0) :: (store (s8) into unknown-address + 124, align 4)
    ; CHECK-NEXT: [[C188:%[0-9]+]]:_(s20) = G_CONSTANT i20 125
    ; CHECK-NEXT: [[PTR_ADD124:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C188]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT125]](s32), [[PTR_ADD124]](p0) :: (store (s8) into unknown-address + 125)
    ; CHECK-NEXT: [[C189:%[0-9]+]]:_(s20) = G_CONSTANT i20 126
    ; CHECK-NEXT: [[PTR_ADD125:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C189]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT126]](s32), [[PTR_ADD125]](p0) :: (store (s8) into unknown-address + 126, align 2)
    ; CHECK-NEXT: [[C190:%[0-9]+]]:_(s20) = G_CONSTANT i20 127
    ; CHECK-NEXT: [[PTR_ADD126:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C190]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT127]](s32), [[PTR_ADD126]](p0) :: (store (s8) into unknown-address + 127)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<128 x s8>) = G_IMPLICIT_DEF
    G_STORE %1(<128 x s8>), %0(p0) :: (store (<128 x s8>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v64int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s16>), [[UV1:%[0-9]+]]:_(<32 x s16>) = G_UNMERGE_VALUES [[DEF]](<64 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT1:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT1]], 16
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT2:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT2]], 16
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT3:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT3]], 16
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT4:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT4]], 16
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT5:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT5]], 16
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT6:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT6]], 16
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT7:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT7]], 16
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT8:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT8]], 16
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT9:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT9]], 16
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT10:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT10]], 16
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT11:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT11]], 16
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT12:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT12]], 16
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT13:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT13]], 16
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT14:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT14]], 16
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT15:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT15]], 16
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT16:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT16]], 16
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT17:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT17]], 16
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT18:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT18]], 16
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT19:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT19]], 16
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT20:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT20]], 16
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT21:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT21]], 16
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT22:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT22]], 16
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT23:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT23]], 16
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT24:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT24]], 16
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT25:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT25]], 16
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT26:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT26]], 16
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT27:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT27]], 16
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT28:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT28]], 16
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT29:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT29]], 16
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT30:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT30]], 16
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<32 x s16>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT31:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT31]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT32:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT32:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT32]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT33:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT33:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT33]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT34:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C2]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT34:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT34]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT35:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C3]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT35:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT35]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT36:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C4]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT36:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT36]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT37:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C5]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT37:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT37]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT38:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C6]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT38:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT38]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT39:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C7]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT39:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT39]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT40:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C8]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT40:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT40]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT41:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C9]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT41:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT41]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT42:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C10]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT42:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT42]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT43:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C11]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT43:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT43]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT44:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C12]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT44:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT44]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT45:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C13]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT45:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT45]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT46:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C14]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT46:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT46]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT47:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C15]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT47:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT47]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT48:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C16]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT48:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT48]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT49:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C17]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT49:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT49]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT50:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C18]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT50:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT50]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT51:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C19]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT51:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT51]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT52:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C20]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT52:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT52]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT53:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C21]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT53:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT53]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT54:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C22]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT54:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT54]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT55:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C23]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT55:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT55]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT56:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C24]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT56:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT56]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT57:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C25]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT57:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT57]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT58:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C26]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT58:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT58]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT59:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C27]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT59:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT59]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT60:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C28]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT60:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT60]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT61:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C29]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT61:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT61]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT62:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C30]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT62:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT62]], 16
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT63:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<32 x s16>), [[C31]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT63:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT63]], 16
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT]](s32), [[COPY]](p0) :: (store (s16), align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT1]](s32), [[PTR_ADD]](p0) :: (store (s16) into unknown-address + 2)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT2]](s32), [[PTR_ADD1]](p0) :: (store (s16) into unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT3]](s32), [[PTR_ADD2]](p0) :: (store (s16) into unknown-address + 6)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT4]](s32), [[PTR_ADD3]](p0) :: (store (s16) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT5]](s32), [[PTR_ADD4]](p0) :: (store (s16) into unknown-address + 10)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT6]](s32), [[PTR_ADD5]](p0) :: (store (s16) into unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT7]](s32), [[PTR_ADD6]](p0) :: (store (s16) into unknown-address + 14)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT8]](s32), [[PTR_ADD7]](p0) :: (store (s16) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT9]](s32), [[PTR_ADD8]](p0) :: (store (s16) into unknown-address + 18)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT10]](s32), [[PTR_ADD9]](p0) :: (store (s16) into unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT11]](s32), [[PTR_ADD10]](p0) :: (store (s16) into unknown-address + 22)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT12]](s32), [[PTR_ADD11]](p0) :: (store (s16) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT13]](s32), [[PTR_ADD12]](p0) :: (store (s16) into unknown-address + 26)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT14]](s32), [[PTR_ADD13]](p0) :: (store (s16) into unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT15]](s32), [[PTR_ADD14]](p0) :: (store (s16) into unknown-address + 30)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT16]](s32), [[PTR_ADD15]](p0) :: (store (s16) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT17]](s32), [[PTR_ADD16]](p0) :: (store (s16) into unknown-address + 34)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT18]](s32), [[PTR_ADD17]](p0) :: (store (s16) into unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT19]](s32), [[PTR_ADD18]](p0) :: (store (s16) into unknown-address + 38)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT20]](s32), [[PTR_ADD19]](p0) :: (store (s16) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT21]](s32), [[PTR_ADD20]](p0) :: (store (s16) into unknown-address + 42)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT22]](s32), [[PTR_ADD21]](p0) :: (store (s16) into unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT23]](s32), [[PTR_ADD22]](p0) :: (store (s16) into unknown-address + 46)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT24]](s32), [[PTR_ADD23]](p0) :: (store (s16) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT25]](s32), [[PTR_ADD24]](p0) :: (store (s16) into unknown-address + 50)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT26]](s32), [[PTR_ADD25]](p0) :: (store (s16) into unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT27]](s32), [[PTR_ADD26]](p0) :: (store (s16) into unknown-address + 54)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT28]](s32), [[PTR_ADD27]](p0) :: (store (s16) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT29]](s32), [[PTR_ADD28]](p0) :: (store (s16) into unknown-address + 58)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT30]](s32), [[PTR_ADD29]](p0) :: (store (s16) into unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT31]](s32), [[PTR_ADD30]](p0) :: (store (s16) into unknown-address + 62)
    ; CHECK-NEXT: [[C63:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C63]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT32]](s32), [[PTR_ADD31]](p0) :: (store (s16) into unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C64:%[0-9]+]]:_(s20) = G_CONSTANT i20 66
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C64]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT33]](s32), [[PTR_ADD32]](p0) :: (store (s16) into unknown-address + 66)
    ; CHECK-NEXT: [[C65:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C65]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT34]](s32), [[PTR_ADD33]](p0) :: (store (s16) into unknown-address + 68, align 4)
    ; CHECK-NEXT: [[C66:%[0-9]+]]:_(s20) = G_CONSTANT i20 70
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C66]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT35]](s32), [[PTR_ADD34]](p0) :: (store (s16) into unknown-address + 70)
    ; CHECK-NEXT: [[C67:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C67]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT36]](s32), [[PTR_ADD35]](p0) :: (store (s16) into unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C68:%[0-9]+]]:_(s20) = G_CONSTANT i20 74
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C68]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT37]](s32), [[PTR_ADD36]](p0) :: (store (s16) into unknown-address + 74)
    ; CHECK-NEXT: [[C69:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C69]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT38]](s32), [[PTR_ADD37]](p0) :: (store (s16) into unknown-address + 76, align 4)
    ; CHECK-NEXT: [[C70:%[0-9]+]]:_(s20) = G_CONSTANT i20 78
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C70]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT39]](s32), [[PTR_ADD38]](p0) :: (store (s16) into unknown-address + 78)
    ; CHECK-NEXT: [[C71:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C71]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT40]](s32), [[PTR_ADD39]](p0) :: (store (s16) into unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C72:%[0-9]+]]:_(s20) = G_CONSTANT i20 82
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C72]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT41]](s32), [[PTR_ADD40]](p0) :: (store (s16) into unknown-address + 82)
    ; CHECK-NEXT: [[C73:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C73]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT42]](s32), [[PTR_ADD41]](p0) :: (store (s16) into unknown-address + 84, align 4)
    ; CHECK-NEXT: [[C74:%[0-9]+]]:_(s20) = G_CONSTANT i20 86
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C74]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT43]](s32), [[PTR_ADD42]](p0) :: (store (s16) into unknown-address + 86)
    ; CHECK-NEXT: [[C75:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C75]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT44]](s32), [[PTR_ADD43]](p0) :: (store (s16) into unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C76:%[0-9]+]]:_(s20) = G_CONSTANT i20 90
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C76]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT45]](s32), [[PTR_ADD44]](p0) :: (store (s16) into unknown-address + 90)
    ; CHECK-NEXT: [[C77:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C77]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT46]](s32), [[PTR_ADD45]](p0) :: (store (s16) into unknown-address + 92, align 4)
    ; CHECK-NEXT: [[C78:%[0-9]+]]:_(s20) = G_CONSTANT i20 94
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C78]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT47]](s32), [[PTR_ADD46]](p0) :: (store (s16) into unknown-address + 94)
    ; CHECK-NEXT: [[C79:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C79]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT48]](s32), [[PTR_ADD47]](p0) :: (store (s16) into unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C80:%[0-9]+]]:_(s20) = G_CONSTANT i20 98
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C80]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT49]](s32), [[PTR_ADD48]](p0) :: (store (s16) into unknown-address + 98)
    ; CHECK-NEXT: [[C81:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C81]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT50]](s32), [[PTR_ADD49]](p0) :: (store (s16) into unknown-address + 100, align 4)
    ; CHECK-NEXT: [[C82:%[0-9]+]]:_(s20) = G_CONSTANT i20 102
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C82]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT51]](s32), [[PTR_ADD50]](p0) :: (store (s16) into unknown-address + 102)
    ; CHECK-NEXT: [[C83:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C83]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT52]](s32), [[PTR_ADD51]](p0) :: (store (s16) into unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C84:%[0-9]+]]:_(s20) = G_CONSTANT i20 106
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C84]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT53]](s32), [[PTR_ADD52]](p0) :: (store (s16) into unknown-address + 106)
    ; CHECK-NEXT: [[C85:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C85]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT54]](s32), [[PTR_ADD53]](p0) :: (store (s16) into unknown-address + 108, align 4)
    ; CHECK-NEXT: [[C86:%[0-9]+]]:_(s20) = G_CONSTANT i20 110
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C86]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT55]](s32), [[PTR_ADD54]](p0) :: (store (s16) into unknown-address + 110)
    ; CHECK-NEXT: [[C87:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C87]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT56]](s32), [[PTR_ADD55]](p0) :: (store (s16) into unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C88:%[0-9]+]]:_(s20) = G_CONSTANT i20 114
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C88]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT57]](s32), [[PTR_ADD56]](p0) :: (store (s16) into unknown-address + 114)
    ; CHECK-NEXT: [[C89:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C89]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT58]](s32), [[PTR_ADD57]](p0) :: (store (s16) into unknown-address + 116, align 4)
    ; CHECK-NEXT: [[C90:%[0-9]+]]:_(s20) = G_CONSTANT i20 118
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C90]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT59]](s32), [[PTR_ADD58]](p0) :: (store (s16) into unknown-address + 118)
    ; CHECK-NEXT: [[C91:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C91]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT60]](s32), [[PTR_ADD59]](p0) :: (store (s16) into unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C92:%[0-9]+]]:_(s20) = G_CONSTANT i20 122
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C92]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT61]](s32), [[PTR_ADD60]](p0) :: (store (s16) into unknown-address + 122)
    ; CHECK-NEXT: [[C93:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C93]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT62]](s32), [[PTR_ADD61]](p0) :: (store (s16) into unknown-address + 124, align 4)
    ; CHECK-NEXT: [[C94:%[0-9]+]]:_(s20) = G_CONSTANT i20 126
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C94]](s20)
    ; CHECK-NEXT: G_STORE [[ASSERT_SEXT63]](s32), [[PTR_ADD62]](p0) :: (store (s16) into unknown-address + 126)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s16>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s16>), %0(p0) :: (store (<64 x s16>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v32int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[DEF]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT16]](s32), [[PTR_ADD15]](p0) :: (store (s32) into unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT17]](s32), [[PTR_ADD16]](p0) :: (store (s32) into unknown-address + 68)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT18]](s32), [[PTR_ADD17]](p0) :: (store (s32) into unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT19]](s32), [[PTR_ADD18]](p0) :: (store (s32) into unknown-address + 76)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT20]](s32), [[PTR_ADD19]](p0) :: (store (s32) into unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT21]](s32), [[PTR_ADD20]](p0) :: (store (s32) into unknown-address + 84)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT22]](s32), [[PTR_ADD21]](p0) :: (store (s32) into unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT23]](s32), [[PTR_ADD22]](p0) :: (store (s32) into unknown-address + 92)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT24]](s32), [[PTR_ADD23]](p0) :: (store (s32) into unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT25]](s32), [[PTR_ADD24]](p0) :: (store (s32) into unknown-address + 100)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT26]](s32), [[PTR_ADD25]](p0) :: (store (s32) into unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT27]](s32), [[PTR_ADD26]](p0) :: (store (s32) into unknown-address + 108)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT28]](s32), [[PTR_ADD27]](p0) :: (store (s32) into unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT29]](s32), [[PTR_ADD28]](p0) :: (store (s32) into unknown-address + 116)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT30]](s32), [[PTR_ADD29]](p0) :: (store (s32) into unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT31]](s32), [[PTR_ADD30]](p0) :: (store (s32) into unknown-address + 124)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s32>), %0(p0) :: (store (<32 x s32>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v8acc32_unaligned
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v8acc32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY1]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY2]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY3]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY4]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: G_STORE [[UV]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: G_STORE [[UV2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s64)
    ; CHECK-NEXT: G_STORE [[UV4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s64)
    ; CHECK-NEXT: G_STORE [[UV6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<4 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<4 x s64>), %0(p0) :: (store (<4 x s64>), align 16)
    PseudoRET implicit $lr

...
---
name:            test_v4acc64_unaligned
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v4acc64_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY1]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY2]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS1]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY3]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS2]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<4 x s64>) = COPY [[DEF]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS3:%[0-9]+]]:_(<8 x s64>) = G_CONCAT_VECTORS [[DEF]](<4 x s64>), [[COPY4]](<4 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[CONCAT_VECTORS3]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: G_STORE [[UV]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: G_STORE [[UV2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s64)
    ; CHECK-NEXT: G_STORE [[UV4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s64)
    ; CHECK-NEXT: G_STORE [[UV6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C4]](s20)
    ; CHECK-NEXT: G_STORE [[UV7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<4 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<4 x s64>), %0(p0) :: (store (<4 x s64>), align 16)
    PseudoRET implicit $lr

...
---
name:            test_v16acc32_unaligned
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v16acc32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: G_STORE [[UV]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: G_STORE [[UV2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s64)
    ; CHECK-NEXT: G_STORE [[UV4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s64)
    ; CHECK-NEXT: G_STORE [[UV6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s64)
    ; CHECK-NEXT: G_STORE [[UV8]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV9]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s64)
    ; CHECK-NEXT: G_STORE [[UV10]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV11]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s64)
    ; CHECK-NEXT: G_STORE [[UV12]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV13]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s64)
    ; CHECK-NEXT: G_STORE [[UV14]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV15]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s64>), %0(p0) :: (store (<8 x s64>), align 16)
    PseudoRET implicit $lr

...
---
name:            test_v8acc64_unaligned
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v8acc64_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[DEF]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: G_STORE [[UV]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: G_STORE [[UV2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s64)
    ; CHECK-NEXT: G_STORE [[UV4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s64)
    ; CHECK-NEXT: G_STORE [[UV6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s64)
    ; CHECK-NEXT: G_STORE [[UV8]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV9]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s64)
    ; CHECK-NEXT: G_STORE [[UV10]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV11]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s64)
    ; CHECK-NEXT: G_STORE [[UV12]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV13]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s64)
    ; CHECK-NEXT: G_STORE [[UV14]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV15]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<8 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<8 x s64>), %0(p0) :: (store (<8 x s64>), align 16)
    PseudoRET implicit $lr

...
---
name:            test_v32acc32_unaligned
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v32acc32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[DEF]](<16 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: G_STORE [[UV2]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: G_STORE [[UV4]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV5]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s64)
    ; CHECK-NEXT: G_STORE [[UV6]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV7]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s64)
    ; CHECK-NEXT: G_STORE [[UV8]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV9]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s64)
    ; CHECK-NEXT: G_STORE [[UV10]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV11]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s64)
    ; CHECK-NEXT: G_STORE [[UV12]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV13]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s64)
    ; CHECK-NEXT: G_STORE [[UV14]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV15]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s64)
    ; CHECK-NEXT: G_STORE [[UV16]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV17]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[UV18:%[0-9]+]]:_(s32), [[UV19:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s64)
    ; CHECK-NEXT: G_STORE [[UV18]](s32), [[PTR_ADD15]](p0) :: (store (s32) into unknown-address + 64, align 16)
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD15]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV19]](s32), [[PTR_ADD16]](p0) :: (store (s32) into unknown-address + 68)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[UV20:%[0-9]+]]:_(s32), [[UV21:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s64)
    ; CHECK-NEXT: G_STORE [[UV20]](s32), [[PTR_ADD17]](p0) :: (store (s32) into unknown-address + 72, align 8)
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD17]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV21]](s32), [[PTR_ADD18]](p0) :: (store (s32) into unknown-address + 76)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s64)
    ; CHECK-NEXT: G_STORE [[UV22]](s32), [[PTR_ADD19]](p0) :: (store (s32) into unknown-address + 80, align 16)
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD19]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV23]](s32), [[PTR_ADD20]](p0) :: (store (s32) into unknown-address + 84)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s64)
    ; CHECK-NEXT: G_STORE [[UV24]](s32), [[PTR_ADD21]](p0) :: (store (s32) into unknown-address + 88, align 8)
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD21]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV25]](s32), [[PTR_ADD22]](p0) :: (store (s32) into unknown-address + 92)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s64)
    ; CHECK-NEXT: G_STORE [[UV26]](s32), [[PTR_ADD23]](p0) :: (store (s32) into unknown-address + 96, align 16)
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD23]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV27]](s32), [[PTR_ADD24]](p0) :: (store (s32) into unknown-address + 100)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s64)
    ; CHECK-NEXT: G_STORE [[UV28]](s32), [[PTR_ADD25]](p0) :: (store (s32) into unknown-address + 104, align 8)
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD25]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV29]](s32), [[PTR_ADD26]](p0) :: (store (s32) into unknown-address + 108)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s64)
    ; CHECK-NEXT: G_STORE [[UV30]](s32), [[PTR_ADD27]](p0) :: (store (s32) into unknown-address + 112, align 16)
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD27]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV31]](s32), [[PTR_ADD28]](p0) :: (store (s32) into unknown-address + 116)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s64)
    ; CHECK-NEXT: G_STORE [[UV32]](s32), [[PTR_ADD29]](p0) :: (store (s32) into unknown-address + 120, align 8)
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD29]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV33]](s32), [[PTR_ADD30]](p0) :: (store (s32) into unknown-address + 124)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s64>), %0(p0) :: (store (<16 x s64>), align 16)
    PseudoRET implicit $lr

...
---
name:            test_v16acc64_unaligned
body:             |
  bb.1.entry:
    liveins:  $p0

    ; CHECK-LABEL: name: test_v16acc64_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s64>), [[UV1:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[DEF]](<16 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV1]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: G_STORE [[UV2]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: G_STORE [[UV4]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV5]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s64)
    ; CHECK-NEXT: G_STORE [[UV6]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV7]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s64)
    ; CHECK-NEXT: G_STORE [[UV8]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV9]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s64)
    ; CHECK-NEXT: G_STORE [[UV10]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV11]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s64)
    ; CHECK-NEXT: G_STORE [[UV12]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV13]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s64)
    ; CHECK-NEXT: G_STORE [[UV14]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV15]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s64)
    ; CHECK-NEXT: G_STORE [[UV16]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV17]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[UV18:%[0-9]+]]:_(s32), [[UV19:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s64)
    ; CHECK-NEXT: G_STORE [[UV18]](s32), [[PTR_ADD15]](p0) :: (store (s32) into unknown-address + 64, align 16)
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD15]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV19]](s32), [[PTR_ADD16]](p0) :: (store (s32) into unknown-address + 68)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[UV20:%[0-9]+]]:_(s32), [[UV21:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s64)
    ; CHECK-NEXT: G_STORE [[UV20]](s32), [[PTR_ADD17]](p0) :: (store (s32) into unknown-address + 72, align 8)
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD17]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV21]](s32), [[PTR_ADD18]](p0) :: (store (s32) into unknown-address + 76)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s64)
    ; CHECK-NEXT: G_STORE [[UV22]](s32), [[PTR_ADD19]](p0) :: (store (s32) into unknown-address + 80, align 16)
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD19]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV23]](s32), [[PTR_ADD20]](p0) :: (store (s32) into unknown-address + 84)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s64)
    ; CHECK-NEXT: G_STORE [[UV24]](s32), [[PTR_ADD21]](p0) :: (store (s32) into unknown-address + 88, align 8)
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD21]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV25]](s32), [[PTR_ADD22]](p0) :: (store (s32) into unknown-address + 92)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s64)
    ; CHECK-NEXT: G_STORE [[UV26]](s32), [[PTR_ADD23]](p0) :: (store (s32) into unknown-address + 96, align 16)
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD23]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV27]](s32), [[PTR_ADD24]](p0) :: (store (s32) into unknown-address + 100)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s64)
    ; CHECK-NEXT: G_STORE [[UV28]](s32), [[PTR_ADD25]](p0) :: (store (s32) into unknown-address + 104, align 8)
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD25]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV29]](s32), [[PTR_ADD26]](p0) :: (store (s32) into unknown-address + 108)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s64)
    ; CHECK-NEXT: G_STORE [[UV30]](s32), [[PTR_ADD27]](p0) :: (store (s32) into unknown-address + 112, align 16)
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD27]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV31]](s32), [[PTR_ADD28]](p0) :: (store (s32) into unknown-address + 116)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s64)
    ; CHECK-NEXT: G_STORE [[UV32]](s32), [[PTR_ADD29]](p0) :: (store (s32) into unknown-address + 120, align 8)
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD29]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV33]](s32), [[PTR_ADD30]](p0) :: (store (s32) into unknown-address + 124)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<16 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s64>), %0(p0) :: (store (<16 x s64>), align 16)
    PseudoRET implicit $lr

...

---
name:            test_v64acc32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64acc32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s32>), [[UV1:%[0-9]+]]:_(<32 x s32>) = G_UNMERGE_VALUES [[DEF]](<64 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[UV]](<32 x s32>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<16 x s32>), [[UV5:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[UV1]](<32 x s32>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT32:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT33:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT34:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT35:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT36:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT37:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT38:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT39:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT40:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT41:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT42:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT43:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT44:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT45:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT46:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT47:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT48:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT49:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT50:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT51:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT52:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT53:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT54:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT55:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT56:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C8]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT57:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C9]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT58:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C10]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT59:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C11]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT60:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C12]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT61:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C13]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT62:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C14]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT63:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<16 x s32>), [[C15]](s32)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT16]](s32), [[PTR_ADD15]](p0) :: (store (s32) into unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT17]](s32), [[PTR_ADD16]](p0) :: (store (s32) into unknown-address + 68)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT18]](s32), [[PTR_ADD17]](p0) :: (store (s32) into unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT19]](s32), [[PTR_ADD18]](p0) :: (store (s32) into unknown-address + 76)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT20]](s32), [[PTR_ADD19]](p0) :: (store (s32) into unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT21]](s32), [[PTR_ADD20]](p0) :: (store (s32) into unknown-address + 84)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT22]](s32), [[PTR_ADD21]](p0) :: (store (s32) into unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT23]](s32), [[PTR_ADD22]](p0) :: (store (s32) into unknown-address + 92)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT24]](s32), [[PTR_ADD23]](p0) :: (store (s32) into unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT25]](s32), [[PTR_ADD24]](p0) :: (store (s32) into unknown-address + 100)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT26]](s32), [[PTR_ADD25]](p0) :: (store (s32) into unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT27]](s32), [[PTR_ADD26]](p0) :: (store (s32) into unknown-address + 108)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT28]](s32), [[PTR_ADD27]](p0) :: (store (s32) into unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT29]](s32), [[PTR_ADD28]](p0) :: (store (s32) into unknown-address + 116)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT30]](s32), [[PTR_ADD29]](p0) :: (store (s32) into unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT31]](s32), [[PTR_ADD30]](p0) :: (store (s32) into unknown-address + 124)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT32]](s32), [[PTR_ADD31]](p0) :: (store (s32) into unknown-address + 128, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 132
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT33]](s32), [[PTR_ADD32]](p0) :: (store (s32) into unknown-address + 132)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 136
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT34]](s32), [[PTR_ADD33]](p0) :: (store (s32) into unknown-address + 136, align 8)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 140
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT35]](s32), [[PTR_ADD34]](p0) :: (store (s32) into unknown-address + 140)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 144
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT36]](s32), [[PTR_ADD35]](p0) :: (store (s32) into unknown-address + 144, align 16)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 148
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT37]](s32), [[PTR_ADD36]](p0) :: (store (s32) into unknown-address + 148)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 152
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT38]](s32), [[PTR_ADD37]](p0) :: (store (s32) into unknown-address + 152, align 8)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 156
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT39]](s32), [[PTR_ADD38]](p0) :: (store (s32) into unknown-address + 156)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 160
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT40]](s32), [[PTR_ADD39]](p0) :: (store (s32) into unknown-address + 160, align 16)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 164
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT41]](s32), [[PTR_ADD40]](p0) :: (store (s32) into unknown-address + 164)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 168
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT42]](s32), [[PTR_ADD41]](p0) :: (store (s32) into unknown-address + 168, align 8)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 172
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT43]](s32), [[PTR_ADD42]](p0) :: (store (s32) into unknown-address + 172)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 176
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT44]](s32), [[PTR_ADD43]](p0) :: (store (s32) into unknown-address + 176, align 16)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 180
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT45]](s32), [[PTR_ADD44]](p0) :: (store (s32) into unknown-address + 180)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 184
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT46]](s32), [[PTR_ADD45]](p0) :: (store (s32) into unknown-address + 184, align 8)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 188
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT47]](s32), [[PTR_ADD46]](p0) :: (store (s32) into unknown-address + 188)
    ; CHECK-NEXT: [[C63:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C63]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT48]](s32), [[PTR_ADD47]](p0) :: (store (s32) into unknown-address + 192, align 16)
    ; CHECK-NEXT: [[C64:%[0-9]+]]:_(s20) = G_CONSTANT i20 196
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C64]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT49]](s32), [[PTR_ADD48]](p0) :: (store (s32) into unknown-address + 196)
    ; CHECK-NEXT: [[C65:%[0-9]+]]:_(s20) = G_CONSTANT i20 200
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C65]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT50]](s32), [[PTR_ADD49]](p0) :: (store (s32) into unknown-address + 200, align 8)
    ; CHECK-NEXT: [[C66:%[0-9]+]]:_(s20) = G_CONSTANT i20 204
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C66]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT51]](s32), [[PTR_ADD50]](p0) :: (store (s32) into unknown-address + 204)
    ; CHECK-NEXT: [[C67:%[0-9]+]]:_(s20) = G_CONSTANT i20 208
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C67]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT52]](s32), [[PTR_ADD51]](p0) :: (store (s32) into unknown-address + 208, align 16)
    ; CHECK-NEXT: [[C68:%[0-9]+]]:_(s20) = G_CONSTANT i20 212
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C68]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT53]](s32), [[PTR_ADD52]](p0) :: (store (s32) into unknown-address + 212)
    ; CHECK-NEXT: [[C69:%[0-9]+]]:_(s20) = G_CONSTANT i20 216
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C69]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT54]](s32), [[PTR_ADD53]](p0) :: (store (s32) into unknown-address + 216, align 8)
    ; CHECK-NEXT: [[C70:%[0-9]+]]:_(s20) = G_CONSTANT i20 220
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C70]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT55]](s32), [[PTR_ADD54]](p0) :: (store (s32) into unknown-address + 220)
    ; CHECK-NEXT: [[C71:%[0-9]+]]:_(s20) = G_CONSTANT i20 224
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C71]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT56]](s32), [[PTR_ADD55]](p0) :: (store (s32) into unknown-address + 224, align 16)
    ; CHECK-NEXT: [[C72:%[0-9]+]]:_(s20) = G_CONSTANT i20 228
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C72]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT57]](s32), [[PTR_ADD56]](p0) :: (store (s32) into unknown-address + 228)
    ; CHECK-NEXT: [[C73:%[0-9]+]]:_(s20) = G_CONSTANT i20 232
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C73]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT58]](s32), [[PTR_ADD57]](p0) :: (store (s32) into unknown-address + 232, align 8)
    ; CHECK-NEXT: [[C74:%[0-9]+]]:_(s20) = G_CONSTANT i20 236
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C74]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT59]](s32), [[PTR_ADD58]](p0) :: (store (s32) into unknown-address + 236)
    ; CHECK-NEXT: [[C75:%[0-9]+]]:_(s20) = G_CONSTANT i20 240
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C75]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT60]](s32), [[PTR_ADD59]](p0) :: (store (s32) into unknown-address + 240, align 16)
    ; CHECK-NEXT: [[C76:%[0-9]+]]:_(s20) = G_CONSTANT i20 244
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C76]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT61]](s32), [[PTR_ADD60]](p0) :: (store (s32) into unknown-address + 244)
    ; CHECK-NEXT: [[C77:%[0-9]+]]:_(s20) = G_CONSTANT i20 248
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C77]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT62]](s32), [[PTR_ADD61]](p0) :: (store (s32) into unknown-address + 248, align 8)
    ; CHECK-NEXT: [[C78:%[0-9]+]]:_(s20) = G_CONSTANT i20 252
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C78]](s20)
    ; CHECK-NEXT: G_STORE [[AIE_SEXT_EXTRACT_VECTOR_ELT63]](s32), [[PTR_ADD62]](p0) :: (store (s32) into unknown-address + 252)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<64 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<64 x s32>), %0(p0) :: (store (<64 x s32>), align 16)
    PseudoRET implicit $lr

...
---
name:            test_v32acc64_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32acc64_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s64>), [[UV1:%[0-9]+]]:_(<16 x s64>) = G_UNMERGE_VALUES [[DEF]](<32 x s64>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s64>), [[UV3:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV]](<16 x s64>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<8 x s64>), [[UV5:%[0-9]+]]:_(<8 x s64>) = G_UNMERGE_VALUES [[UV1]](<16 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT2:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT3:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT4:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT5:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT6:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT7:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT8:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT9:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT10:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT11:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT12:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT13:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT14:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT15:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV3]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT16:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT17:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT18:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT19:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT20:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT21:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT22:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT23:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV4]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT24:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT25:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT26:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT27:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT28:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT29:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT30:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C6]](s32)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT31:%[0-9]+]]:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV5]](<8 x s64>), [[C7]](s32)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: G_STORE [[UV6]](s32), [[COPY]](p0) :: (store (s32), align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV7]](s32), [[PTR_ADD]](p0) :: (store (s32) into unknown-address + 4)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: G_STORE [[UV8]](s32), [[PTR_ADD1]](p0) :: (store (s32) into unknown-address + 8, align 8)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV9]](s32), [[PTR_ADD2]](p0) :: (store (s32) into unknown-address + 12)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT2]](s64)
    ; CHECK-NEXT: G_STORE [[UV10]](s32), [[PTR_ADD3]](p0) :: (store (s32) into unknown-address + 16, align 16)
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV11]](s32), [[PTR_ADD4]](p0) :: (store (s32) into unknown-address + 20)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT3]](s64)
    ; CHECK-NEXT: G_STORE [[UV12]](s32), [[PTR_ADD5]](p0) :: (store (s32) into unknown-address + 24, align 8)
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV13]](s32), [[PTR_ADD6]](p0) :: (store (s32) into unknown-address + 28)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT4]](s64)
    ; CHECK-NEXT: G_STORE [[UV14]](s32), [[PTR_ADD7]](p0) :: (store (s32) into unknown-address + 32, align 16)
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV15]](s32), [[PTR_ADD8]](p0) :: (store (s32) into unknown-address + 36)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT5]](s64)
    ; CHECK-NEXT: G_STORE [[UV16]](s32), [[PTR_ADD9]](p0) :: (store (s32) into unknown-address + 40, align 8)
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV17]](s32), [[PTR_ADD10]](p0) :: (store (s32) into unknown-address + 44)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[UV18:%[0-9]+]]:_(s32), [[UV19:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT6]](s64)
    ; CHECK-NEXT: G_STORE [[UV18]](s32), [[PTR_ADD11]](p0) :: (store (s32) into unknown-address + 48, align 16)
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV19]](s32), [[PTR_ADD12]](p0) :: (store (s32) into unknown-address + 52)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[UV20:%[0-9]+]]:_(s32), [[UV21:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT7]](s64)
    ; CHECK-NEXT: G_STORE [[UV20]](s32), [[PTR_ADD13]](p0) :: (store (s32) into unknown-address + 56, align 8)
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV21]](s32), [[PTR_ADD14]](p0) :: (store (s32) into unknown-address + 60)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT8]](s64)
    ; CHECK-NEXT: G_STORE [[UV22]](s32), [[PTR_ADD15]](p0) :: (store (s32) into unknown-address + 64, align 16)
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD15]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV23]](s32), [[PTR_ADD16]](p0) :: (store (s32) into unknown-address + 68)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT9]](s64)
    ; CHECK-NEXT: G_STORE [[UV24]](s32), [[PTR_ADD17]](p0) :: (store (s32) into unknown-address + 72, align 8)
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD17]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV25]](s32), [[PTR_ADD18]](p0) :: (store (s32) into unknown-address + 76)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT10]](s64)
    ; CHECK-NEXT: G_STORE [[UV26]](s32), [[PTR_ADD19]](p0) :: (store (s32) into unknown-address + 80, align 16)
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD19]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV27]](s32), [[PTR_ADD20]](p0) :: (store (s32) into unknown-address + 84)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT11]](s64)
    ; CHECK-NEXT: G_STORE [[UV28]](s32), [[PTR_ADD21]](p0) :: (store (s32) into unknown-address + 88, align 8)
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD21]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV29]](s32), [[PTR_ADD22]](p0) :: (store (s32) into unknown-address + 92)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT12]](s64)
    ; CHECK-NEXT: G_STORE [[UV30]](s32), [[PTR_ADD23]](p0) :: (store (s32) into unknown-address + 96, align 16)
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD23]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV31]](s32), [[PTR_ADD24]](p0) :: (store (s32) into unknown-address + 100)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT13]](s64)
    ; CHECK-NEXT: G_STORE [[UV32]](s32), [[PTR_ADD25]](p0) :: (store (s32) into unknown-address + 104, align 8)
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD25]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV33]](s32), [[PTR_ADD26]](p0) :: (store (s32) into unknown-address + 108)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT14]](s64)
    ; CHECK-NEXT: G_STORE [[UV34]](s32), [[PTR_ADD27]](p0) :: (store (s32) into unknown-address + 112, align 16)
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD27]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV35]](s32), [[PTR_ADD28]](p0) :: (store (s32) into unknown-address + 116)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT15]](s64)
    ; CHECK-NEXT: G_STORE [[UV36]](s32), [[PTR_ADD29]](p0) :: (store (s32) into unknown-address + 120, align 8)
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD29]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV37]](s32), [[PTR_ADD30]](p0) :: (store (s32) into unknown-address + 124)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT16]](s64)
    ; CHECK-NEXT: G_STORE [[UV38]](s32), [[PTR_ADD31]](p0) :: (store (s32) into unknown-address + 128, align 16)
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD31]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV39]](s32), [[PTR_ADD32]](p0) :: (store (s32) into unknown-address + 132)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 136
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT17]](s64)
    ; CHECK-NEXT: G_STORE [[UV40]](s32), [[PTR_ADD33]](p0) :: (store (s32) into unknown-address + 136, align 8)
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD33]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV41]](s32), [[PTR_ADD34]](p0) :: (store (s32) into unknown-address + 140)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 144
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT18]](s64)
    ; CHECK-NEXT: G_STORE [[UV42]](s32), [[PTR_ADD35]](p0) :: (store (s32) into unknown-address + 144, align 16)
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD35]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV43]](s32), [[PTR_ADD36]](p0) :: (store (s32) into unknown-address + 148)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 152
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[UV44:%[0-9]+]]:_(s32), [[UV45:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT19]](s64)
    ; CHECK-NEXT: G_STORE [[UV44]](s32), [[PTR_ADD37]](p0) :: (store (s32) into unknown-address + 152, align 8)
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD37]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV45]](s32), [[PTR_ADD38]](p0) :: (store (s32) into unknown-address + 156)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 160
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT20]](s64)
    ; CHECK-NEXT: G_STORE [[UV46]](s32), [[PTR_ADD39]](p0) :: (store (s32) into unknown-address + 160, align 16)
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD39]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV47]](s32), [[PTR_ADD40]](p0) :: (store (s32) into unknown-address + 164)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 168
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[UV48:%[0-9]+]]:_(s32), [[UV49:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT21]](s64)
    ; CHECK-NEXT: G_STORE [[UV48]](s32), [[PTR_ADD41]](p0) :: (store (s32) into unknown-address + 168, align 8)
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD41]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV49]](s32), [[PTR_ADD42]](p0) :: (store (s32) into unknown-address + 172)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 176
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[UV50:%[0-9]+]]:_(s32), [[UV51:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT22]](s64)
    ; CHECK-NEXT: G_STORE [[UV50]](s32), [[PTR_ADD43]](p0) :: (store (s32) into unknown-address + 176, align 16)
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD43]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV51]](s32), [[PTR_ADD44]](p0) :: (store (s32) into unknown-address + 180)
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 184
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; CHECK-NEXT: [[UV52:%[0-9]+]]:_(s32), [[UV53:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT23]](s64)
    ; CHECK-NEXT: G_STORE [[UV52]](s32), [[PTR_ADD45]](p0) :: (store (s32) into unknown-address + 184, align 8)
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD45]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV53]](s32), [[PTR_ADD46]](p0) :: (store (s32) into unknown-address + 188)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: [[UV54:%[0-9]+]]:_(s32), [[UV55:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT24]](s64)
    ; CHECK-NEXT: G_STORE [[UV54]](s32), [[PTR_ADD47]](p0) :: (store (s32) into unknown-address + 192, align 16)
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD47]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV55]](s32), [[PTR_ADD48]](p0) :: (store (s32) into unknown-address + 196)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 200
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: [[UV56:%[0-9]+]]:_(s32), [[UV57:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT25]](s64)
    ; CHECK-NEXT: G_STORE [[UV56]](s32), [[PTR_ADD49]](p0) :: (store (s32) into unknown-address + 200, align 8)
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD49]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV57]](s32), [[PTR_ADD50]](p0) :: (store (s32) into unknown-address + 204)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 208
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: [[UV58:%[0-9]+]]:_(s32), [[UV59:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT26]](s64)
    ; CHECK-NEXT: G_STORE [[UV58]](s32), [[PTR_ADD51]](p0) :: (store (s32) into unknown-address + 208, align 16)
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD51]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV59]](s32), [[PTR_ADD52]](p0) :: (store (s32) into unknown-address + 212)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 216
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: [[UV60:%[0-9]+]]:_(s32), [[UV61:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT27]](s64)
    ; CHECK-NEXT: G_STORE [[UV60]](s32), [[PTR_ADD53]](p0) :: (store (s32) into unknown-address + 216, align 8)
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD53]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV61]](s32), [[PTR_ADD54]](p0) :: (store (s32) into unknown-address + 220)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 224
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: [[UV62:%[0-9]+]]:_(s32), [[UV63:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT28]](s64)
    ; CHECK-NEXT: G_STORE [[UV62]](s32), [[PTR_ADD55]](p0) :: (store (s32) into unknown-address + 224, align 16)
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD55]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV63]](s32), [[PTR_ADD56]](p0) :: (store (s32) into unknown-address + 228)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 232
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: [[UV64:%[0-9]+]]:_(s32), [[UV65:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT29]](s64)
    ; CHECK-NEXT: G_STORE [[UV64]](s32), [[PTR_ADD57]](p0) :: (store (s32) into unknown-address + 232, align 8)
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD57]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV65]](s32), [[PTR_ADD58]](p0) :: (store (s32) into unknown-address + 236)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 240
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: [[UV66:%[0-9]+]]:_(s32), [[UV67:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT30]](s64)
    ; CHECK-NEXT: G_STORE [[UV66]](s32), [[PTR_ADD59]](p0) :: (store (s32) into unknown-address + 240, align 16)
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD59]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV67]](s32), [[PTR_ADD60]](p0) :: (store (s32) into unknown-address + 244)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 248
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: [[UV68:%[0-9]+]]:_(s32), [[UV69:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[AIE_SEXT_EXTRACT_VECTOR_ELT31]](s64)
    ; CHECK-NEXT: G_STORE [[UV68]](s32), [[PTR_ADD61]](p0) :: (store (s32) into unknown-address + 248, align 8)
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD61]], [[C8]](s20)
    ; CHECK-NEXT: G_STORE [[UV69]](s32), [[PTR_ADD62]](p0) :: (store (s32) into unknown-address + 252)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(<32 x s64>) = G_IMPLICIT_DEF
    G_STORE %1(<32 x s64>), %0(p0) :: (store (<32 x s64>), align 16)
    PseudoRET implicit $lr
...


---
name:            test_vec512_32byte_alignment
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_vec512_32byte_alignment
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: G_STORE [[DEF]](<16 x s32>), [[COPY]](p0) :: (store (<16 x s32>), align 32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](p0)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    G_STORE %1(<16 x s32>), %0(p0) :: (store (<16 x s32>), align 32)
    PseudoRET implicit $lr, implicit %0

...
