# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:           test_unmerge_2x256_to_s256
body:             |
  bb.0.entry:
    liveins: $x0
    ; CHECK-LABEL: name: test_unmerge_2x256_to_s256
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s256>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s256), [[UV1:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[COPY]](<2 x s256>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](s256), implicit [[UV1]](s256)
    %0:_(<2 x s256>) = COPY $x0
    %1:_(s256), %2:_(s256) = G_UNMERGE_VALUES %0(<2 x s256>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:           test_unmerge_2x512_to_s512
body:             |
  bb.0.entry:
    liveins: $y2
    ; CHECK-LABEL: name: test_unmerge_2x512_to_s512
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s512>) = COPY $y2
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s512), [[UV1:%[0-9]+]]:_(s512) = G_UNMERGE_VALUES [[COPY]](<2 x s512>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](s512), implicit [[UV1]](s512)
    %0:_(<2 x s512>) = COPY $y2
    %1:_(s512), %2:_(s512) = G_UNMERGE_VALUES %0(<2 x s512>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:           test_unmerge_2x2048_to_s1024
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_2x2048_to_s1024
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s1024>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s1024), [[UV1:%[0-9]+]]:_(s1024) = G_UNMERGE_VALUES [[COPY]](<2 x s1024>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](s1024), implicit [[UV1]](s1024)
    %0:_(<2 x s1024>) = COPY $dm0
    %1:_(s1024), %2:_(s1024) = G_UNMERGE_VALUES %0(<2 x s1024>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:           test_unmerge_4xs256_to_s256
body:             |
  bb.0.entry:
    liveins: $y2
    ; CHECK-LABEL: name: test_unmerge_4xs256_to_s256
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s256>) = COPY $y2
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<2 x s256>), [[UV1:%[0-9]+]]:_(<2 x s256>) = G_UNMERGE_VALUES [[COPY]](<4 x s256>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s256), [[UV3:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV]](<2 x s256>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s256), [[UV5:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV1]](<2 x s256>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV2]](s256), implicit [[UV3]](s256), implicit [[UV4]](s256), implicit [[UV5]](s256)
    %0:_(<4 x s256>) = COPY $y2
    %1:_(s256), %2:_(s256), %3:_(s256), %4:_(s256) = G_UNMERGE_VALUES %0(<4 x s256>)
    PseudoRET implicit $lr, implicit %1, implicit %2, implicit %3, implicit %4
...

---
name:           test_unmerge_4xs512_to_s512
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_4xs512_to_s512
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s512>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<2 x s512>), [[UV1:%[0-9]+]]:_(<2 x s512>) = G_UNMERGE_VALUES [[COPY]](<4 x s512>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s512), [[UV3:%[0-9]+]]:_(s512) = G_UNMERGE_VALUES [[UV]](<2 x s512>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s512), [[UV5:%[0-9]+]]:_(s512) = G_UNMERGE_VALUES [[UV1]](<2 x s512>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV2]](s512), implicit [[UV3]](s512), implicit [[UV4]](s512), implicit [[UV5]](s512)
    %0:_(<4 x s512>) = COPY $dm0
    %1:_(s512), %2:_(s512), %3:_(s512), %4:_(s512) = G_UNMERGE_VALUES %0(<4 x s512>)
    PseudoRET implicit $lr, implicit %1, implicit %2, implicit %3, implicit %4
...

---
name:           test_unmerge_8xs256_to_s256
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_8xs256_to_s256
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s256>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s256>), [[UV1:%[0-9]+]]:_(<4 x s256>) = G_UNMERGE_VALUES [[COPY]](<8 x s256>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<2 x s256>), [[UV3:%[0-9]+]]:_(<2 x s256>) = G_UNMERGE_VALUES [[UV]](<4 x s256>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s256), [[UV5:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV2]](<2 x s256>)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:_(s256), [[UV7:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV3]](<2 x s256>)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(<2 x s256>), [[UV9:%[0-9]+]]:_(<2 x s256>) = G_UNMERGE_VALUES [[UV1]](<4 x s256>)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:_(s256), [[UV11:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV8]](<2 x s256>)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:_(s256), [[UV13:%[0-9]+]]:_(s256) = G_UNMERGE_VALUES [[UV9]](<2 x s256>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV4]](s256), implicit [[UV5]](s256), implicit [[UV6]](s256), implicit [[UV7]](s256), implicit [[UV10]](s256), implicit [[UV11]](s256), implicit [[UV12]](s256), implicit [[UV13]](s256)
    %0:_(<8 x s256>) = COPY $dm0
    %1:_(s256), %2:_(s256), %3:_(s256), %4:_(s256), %5:_(s256), %6:_(s256), %7:_(s256), %8:_(s256) = G_UNMERGE_VALUES %0(<8 x s256>)
    PseudoRET implicit $lr, implicit %1, implicit %2, implicit %3, implicit %4, implicit %5, implicit %6, implicit %7, implicit %8
...
