# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -DVER=aie2p --check-prefixes=CHECK,AIE2P
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s -DVER=aie2ps --check-prefixes=CHECK,AIE2PS

---
name:            test_v64acc32
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64acc32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<64 x s32>) = G_LOAD [[COPY]](p0) :: (load (<64 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<64 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<64 x s32>) = G_LOAD %1(p0) :: (load (<64 x s32>))
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32acc64
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32acc64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s64>) = G_LOAD [[COPY]](p0) :: (load (<32 x s64>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<32 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s64>) = G_LOAD %1(p0) :: (load (<32 x s64>))
    PseudoRET implicit $lr, implicit %0

...

---
name:            test_v2s1024
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v2s1024
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<32 x s64>) = G_LOAD [[COPY]](p0) :: (load (<32 x s64>))
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s1024>) = G_BITCAST [[LOAD]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<2 x s1024>)
    %1:_(p0) = COPY $p0
    %0:_(<2 x s1024>) = G_LOAD %1(p0) :: (load (<2 x s1024>))
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_v4int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v4int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 8)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.[[VER]].vshift.I512.I512), [[AIE_ADD_VECTOR_ELT_HI3]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI3]](<16 x s32>), [[C3]](s32), [[C4]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<4 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<4 x s32>) = G_LOAD %1(p0) :: (load (<4 x s32>), align 8)
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_v16int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v16int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s8), align 8)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s8) from unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s8) from unknown-address + 3)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s8) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s8) from unknown-address + 5)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s8) from unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s8) from unknown-address + 7)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s8) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s8) from unknown-address + 9)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s8) from unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s8) from unknown-address + 11)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s8) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s8) from unknown-address + 13)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s8) from unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s8) from unknown-address + 15)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_ADD_VECTOR_ELT_HI15]](<64 x s8>)
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.[[VER]].vshift.I512.I512), [[BITCAST]](<16 x s32>), [[BITCAST]](<16 x s32>), [[C15]](s32), [[C16]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<64 x s8>) = G_BITCAST [[INT]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_AIE_UNPAD_VECTOR [[BITCAST1]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<16 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s8>) = G_LOAD %1(p0) :: (load (<16 x s8>), align 8)
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_v8int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v8int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16), align 8)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s16) from unknown-address + 2)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s16) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s16) from unknown-address + 6)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s16) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s16) from unknown-address + 10)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s16) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s16) from unknown-address + 14)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[AIE_ADD_VECTOR_ELT_HI7]](<32 x s16>)
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.[[VER]].vshift.I512.I512), [[BITCAST]](<16 x s32>), [[BITCAST]](<16 x s32>), [[C7]](s32), [[C8]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<32 x s16>) = G_BITCAST [[INT]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s16>) = G_AIE_UNPAD_VECTOR [[BITCAST1]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s16>)
    %1:_(p0) = COPY $p0
    %0:_(<8 x s16>) = G_LOAD %1(p0) :: (load (<8 x s16>), align 8)
    PseudoRET implicit $lr, implicit %0
...


---
name:            test_v32int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s8), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s8) from unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s8) from unknown-address + 3)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s8) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s8) from unknown-address + 5)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s8) from unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s8) from unknown-address + 7)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s8) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s8) from unknown-address + 9)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s8) from unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s8) from unknown-address + 11)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s8) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s8) from unknown-address + 13)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s8) from unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s8) from unknown-address + 15)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s8) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s8) from unknown-address + 17)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s8) from unknown-address + 18, align 2)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s8) from unknown-address + 19)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s8) from unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 21
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s8) from unknown-address + 21)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s8) from unknown-address + 22, align 2)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s8) from unknown-address + 23)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s8) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 25
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s8) from unknown-address + 25)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s8) from unknown-address + 26, align 2)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 27
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s8) from unknown-address + 27)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s8) from unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 29
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s8) from unknown-address + 29)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s8) from unknown-address + 30, align 2)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 31
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s8) from unknown-address + 31)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI31]](<64 x s8>)
    ; CHECK-NEXT: $wl0 = COPY [[UV1]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(p0) = COPY $p0
    %0:_(<32 x s8>) = G_LOAD %1(p0) :: (load (<32 x s8>), align 16)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...

---
name:            test_v32int8_unalignedT
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: test_v32int8_unalignedT
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s8), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s8) from unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s8) from unknown-address + 3)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s8) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s8) from unknown-address + 5)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s8) from unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s8) from unknown-address + 7)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s8) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s8) from unknown-address + 9)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s8) from unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s8) from unknown-address + 11)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s8) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s8) from unknown-address + 13)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s8) from unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s8) from unknown-address + 15)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s8) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s8) from unknown-address + 17)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s8) from unknown-address + 18, align 2)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s8) from unknown-address + 19)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s8) from unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 21
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s8) from unknown-address + 21)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s8) from unknown-address + 22, align 2)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s8) from unknown-address + 23)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s8) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 25
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s8) from unknown-address + 25)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s8) from unknown-address + 26, align 2)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 27
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s8) from unknown-address + 27)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s8) from unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 29
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s8) from unknown-address + 29)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s8) from unknown-address + 30, align 2)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 31
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s8) from unknown-address + 31)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s8>), [[UV1:%[0-9]+]]:_(<32 x s8>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI31]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<32 x s8>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s8>) = G_LOAD %1(p0) :: (load (<32 x s8>), align 16)
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_v16int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s16) from unknown-address + 2)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s16) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s16) from unknown-address + 6)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s16) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s16) from unknown-address + 10)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s16) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s16) from unknown-address + 14)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s16) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s16) from unknown-address + 18)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s16) from unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s16) from unknown-address + 22)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s16) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s16) from unknown-address + 26)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s16) from unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s16) from unknown-address + 30)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s16>), [[UV1:%[0-9]+]]:_(<16 x s16>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI15]](<32 x s16>)
    ; CHECK-NEXT: $wl0 = COPY [[UV1]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(p0) = COPY $p0
    %0:_(<16 x s16>) = G_LOAD %1(p0) :: (load (<16 x s16>), align 16)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...

---
name:            test_v8int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v8int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI7]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[UV1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(p0) = COPY $p0
    %0:_(<8 x s32>) = G_LOAD %1(p0) :: (load (<8 x s32>), align 16)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...


---
name:            test_v8acc32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2P-LABEL: name: test_v8acc32_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; AIE2P-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; AIE2P-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD2]](s32), [[LOAD3]](s32)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; AIE2P-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD4]](s32), [[LOAD5]](s32)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; AIE2P-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD6]](s32), [[LOAD7]](s32)
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[MV]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[MV1]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[MV2]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[MV3]](s64)
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI3]](<8 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s64>)
    ;
    ; AIE2PS-LABEL: name: test_v8acc32_unaligned
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64), align 16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from unknown-address + 8)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from unknown-address + 16, align 16)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD2]](p0) :: (load (s64) from unknown-address + 24)
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s64)
    ; AIE2PS-NEXT: [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI3]](<8 x s64>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<4 x s64>) = G_LOAD %1(p0) :: (load (<4 x s64>), align 16)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v4acc64_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2P-LABEL: name: test_v4acc64_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; AIE2P-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; AIE2P-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD2]](s32), [[LOAD3]](s32)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; AIE2P-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD4]](s32), [[LOAD5]](s32)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; AIE2P-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD6]](s32), [[LOAD7]](s32)
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[MV]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[MV1]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[MV2]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[MV3]](s64)
    ; AIE2P-NEXT: [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI3]](<8 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s64>)
    ;
    ; AIE2PS-LABEL: name: test_v4acc64_unaligned
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64), align 16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from unknown-address + 8)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from unknown-address + 16, align 16)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD2]](p0) :: (load (s64) from unknown-address + 24)
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s64)
    ; AIE2PS-NEXT: [[UV:%[0-9]+]]:_(<4 x s64>), [[UV1:%[0-9]+]]:_(<4 x s64>) = G_UNMERGE_VALUES [[AIE_ADD_VECTOR_ELT_HI3]](<8 x s64>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<4 x s64>) = G_LOAD %1(p0) :: (load (<4 x s64>), align 16)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v64int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s8), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s8) from unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s8) from unknown-address + 3)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s8) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s8) from unknown-address + 5)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s8) from unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s8) from unknown-address + 7)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s8) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s8) from unknown-address + 9)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s8) from unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s8) from unknown-address + 11)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s8) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s8) from unknown-address + 13)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s8) from unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s8) from unknown-address + 15)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s8) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s8) from unknown-address + 17)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s8) from unknown-address + 18, align 2)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s8) from unknown-address + 19)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s8) from unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 21
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s8) from unknown-address + 21)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s8) from unknown-address + 22, align 2)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s8) from unknown-address + 23)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s8) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 25
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s8) from unknown-address + 25)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s8) from unknown-address + 26, align 2)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 27
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s8) from unknown-address + 27)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s8) from unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 29
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s8) from unknown-address + 29)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s8) from unknown-address + 30, align 2)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 31
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s8) from unknown-address + 31)
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; CHECK-NEXT: [[LOAD32:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD31]](p0) :: (load (s8) from unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 33
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: [[LOAD33:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD32]](p0) :: (load (s8) from unknown-address + 33)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: [[LOAD34:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD33]](p0) :: (load (s8) from unknown-address + 34, align 2)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 35
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: [[LOAD35:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD34]](p0) :: (load (s8) from unknown-address + 35)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: [[LOAD36:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD35]](p0) :: (load (s8) from unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 37
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: [[LOAD37:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD36]](p0) :: (load (s8) from unknown-address + 37)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: [[LOAD38:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD37]](p0) :: (load (s8) from unknown-address + 38, align 2)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 39
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: [[LOAD39:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD38]](p0) :: (load (s8) from unknown-address + 39)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: [[LOAD40:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD39]](p0) :: (load (s8) from unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 41
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: [[LOAD41:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD40]](p0) :: (load (s8) from unknown-address + 41)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: [[LOAD42:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD41]](p0) :: (load (s8) from unknown-address + 42, align 2)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 43
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: [[LOAD43:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD42]](p0) :: (load (s8) from unknown-address + 43)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: [[LOAD44:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD43]](p0) :: (load (s8) from unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: [[LOAD45:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD44]](p0) :: (load (s8) from unknown-address + 45)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: [[LOAD46:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD45]](p0) :: (load (s8) from unknown-address + 46, align 2)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 47
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: [[LOAD47:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD46]](p0) :: (load (s8) from unknown-address + 47)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: [[LOAD48:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD47]](p0) :: (load (s8) from unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 49
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: [[LOAD49:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD48]](p0) :: (load (s8) from unknown-address + 49)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: [[LOAD50:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD49]](p0) :: (load (s8) from unknown-address + 50, align 2)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 51
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: [[LOAD51:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD50]](p0) :: (load (s8) from unknown-address + 51)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: [[LOAD52:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD51]](p0) :: (load (s8) from unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 53
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: [[LOAD53:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD52]](p0) :: (load (s8) from unknown-address + 53)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: [[LOAD54:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD53]](p0) :: (load (s8) from unknown-address + 54, align 2)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 55
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: [[LOAD55:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD54]](p0) :: (load (s8) from unknown-address + 55)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: [[LOAD56:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD55]](p0) :: (load (s8) from unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 57
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: [[LOAD57:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD56]](p0) :: (load (s8) from unknown-address + 57)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: [[LOAD58:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD57]](p0) :: (load (s8) from unknown-address + 58, align 2)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 59
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: [[LOAD59:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD58]](p0) :: (load (s8) from unknown-address + 59)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: [[LOAD60:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD59]](p0) :: (load (s8) from unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 61
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: [[LOAD61:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD60]](p0) :: (load (s8) from unknown-address + 61)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: [[LOAD62:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD61]](p0) :: (load (s8) from unknown-address + 62, align 2)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 63
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: [[LOAD63:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD62]](p0) :: (load (s8) from unknown-address + 63)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI32:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI31]], [[LOAD32]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI33:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI32]], [[LOAD33]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI34:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI33]], [[LOAD34]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI35:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI34]], [[LOAD35]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI36:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI35]], [[LOAD36]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI37:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI36]], [[LOAD37]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI38:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI37]], [[LOAD38]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI39:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI38]], [[LOAD39]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI40:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI39]], [[LOAD40]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI41:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI40]], [[LOAD41]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI42:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI41]], [[LOAD42]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI43:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI42]], [[LOAD43]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI44:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI43]], [[LOAD44]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI45:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI44]], [[LOAD45]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI46:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI45]], [[LOAD46]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI47:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI46]], [[LOAD47]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI48:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI47]], [[LOAD48]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI49:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI48]], [[LOAD49]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI50:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI49]], [[LOAD50]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI51:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI50]], [[LOAD51]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI52:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI51]], [[LOAD52]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI53:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI52]], [[LOAD53]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI54:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI53]], [[LOAD54]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI55:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI54]], [[LOAD55]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI56:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI55]], [[LOAD56]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI57:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI56]], [[LOAD57]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI58:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI57]], [[LOAD58]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI59:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI58]], [[LOAD59]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI60:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI59]], [[LOAD60]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI61:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI60]], [[LOAD61]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI62:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI61]], [[LOAD62]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI63:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI62]], [[LOAD63]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_ADD_VECTOR_ELT_HI63]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(p0) = COPY $p0
    %0:_(<64 x s8>) = G_LOAD %1(p0) :: (load (<64 x s8>), align 16)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_v32int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s16) from unknown-address + 2)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s16) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s16) from unknown-address + 6)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s16) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s16) from unknown-address + 10)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s16) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s16) from unknown-address + 14)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s16) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s16) from unknown-address + 18)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s16) from unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s16) from unknown-address + 22)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s16) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s16) from unknown-address + 26)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s16) from unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s16) from unknown-address + 30)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s16) from unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s16) from unknown-address + 34)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s16) from unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s16) from unknown-address + 38)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s16) from unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s16) from unknown-address + 42)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s16) from unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s16) from unknown-address + 46)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s16) from unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s16) from unknown-address + 50)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s16) from unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s16) from unknown-address + 54)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s16) from unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s16) from unknown-address + 58)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s16) from unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s16) from unknown-address + 62)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_ADD_VECTOR_ELT_HI31]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(p0) = COPY $p0
    %0:_(<32 x s16>) = G_LOAD %1(p0) :: (load (<32 x s16>), align 16)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_v16int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v16int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(p0) = COPY $p0
    %0:_(<16 x s32>) = G_LOAD %1(p0) :: (load (<16 x s32>), align 16)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...

---
name:            test_v16acc32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2P-LABEL: name: test_v16acc32_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; AIE2P-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; AIE2P-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD2]](s32), [[LOAD3]](s32)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; AIE2P-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD4]](s32), [[LOAD5]](s32)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; AIE2P-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD6]](s32), [[LOAD7]](s32)
    ; AIE2P-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2P-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; AIE2P-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; AIE2P-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD8]](s32), [[LOAD9]](s32)
    ; AIE2P-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2P-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2P-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; AIE2P-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; AIE2P-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD10]](s32), [[LOAD11]](s32)
    ; AIE2P-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2P-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2P-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; AIE2P-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; AIE2P-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD12]](s32), [[LOAD13]](s32)
    ; AIE2P-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2P-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2P-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; AIE2P-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; AIE2P-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD14]](s32), [[LOAD15]](s32)
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[MV]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[MV1]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[MV2]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[MV3]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[MV4]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[MV5]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[MV6]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[MV7]](s64)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>)
    ;
    ; AIE2PS-LABEL: name: test_v16acc32_unaligned
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64), align 16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from unknown-address + 8)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from unknown-address + 16, align 16)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD2]](p0) :: (load (s64) from unknown-address + 24)
    ; AIE2PS-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2PS-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2PS-NEXT: [[LOAD4:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD3]](p0) :: (load (s64) from unknown-address + 32, align 16)
    ; AIE2PS-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2PS-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2PS-NEXT: [[LOAD5:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD4]](p0) :: (load (s64) from unknown-address + 40)
    ; AIE2PS-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2PS-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2PS-NEXT: [[LOAD6:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD5]](p0) :: (load (s64) from unknown-address + 48, align 16)
    ; AIE2PS-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2PS-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2PS-NEXT: [[LOAD7:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD6]](p0) :: (load (s64) from unknown-address + 56)
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s64)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<8 x s64>) = G_LOAD %1(p0) :: (load (<8 x s64>), align 16)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v8acc64_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2P-LABEL: name: test_v8acc64_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; AIE2P-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; AIE2P-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD2]](s32), [[LOAD3]](s32)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; AIE2P-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD4]](s32), [[LOAD5]](s32)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; AIE2P-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD6]](s32), [[LOAD7]](s32)
    ; AIE2P-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2P-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; AIE2P-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; AIE2P-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD8]](s32), [[LOAD9]](s32)
    ; AIE2P-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2P-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2P-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; AIE2P-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; AIE2P-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD10]](s32), [[LOAD11]](s32)
    ; AIE2P-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2P-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2P-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; AIE2P-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; AIE2P-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD12]](s32), [[LOAD13]](s32)
    ; AIE2P-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2P-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2P-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; AIE2P-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; AIE2P-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD14]](s32), [[LOAD15]](s32)
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[MV]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[MV1]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[MV2]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[MV3]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[MV4]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[MV5]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[MV6]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[MV7]](s64)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>)
    ;
    ; AIE2PS-LABEL: name: test_v8acc64_unaligned
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64), align 16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from unknown-address + 8)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from unknown-address + 16, align 16)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD2]](p0) :: (load (s64) from unknown-address + 24)
    ; AIE2PS-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2PS-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2PS-NEXT: [[LOAD4:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD3]](p0) :: (load (s64) from unknown-address + 32, align 16)
    ; AIE2PS-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2PS-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2PS-NEXT: [[LOAD5:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD4]](p0) :: (load (s64) from unknown-address + 40)
    ; AIE2PS-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2PS-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2PS-NEXT: [[LOAD6:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD5]](p0) :: (load (s64) from unknown-address + 48, align 16)
    ; AIE2PS-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2PS-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2PS-NEXT: [[LOAD7:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD6]](p0) :: (load (s64) from unknown-address + 56)
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s64)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<8 x s64>) = G_LOAD %1(p0) :: (load (<8 x s64>), align 16)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v128int8_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v128int8_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s8), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s8) from unknown-address + 1)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s8) from unknown-address + 2, align 2)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s8) from unknown-address + 3)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s8) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s8) from unknown-address + 5)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s8) from unknown-address + 6, align 2)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s8) from unknown-address + 7)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s8) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 9
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s8) from unknown-address + 9)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s8) from unknown-address + 10, align 2)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 11
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s8) from unknown-address + 11)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s8) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 13
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s8) from unknown-address + 13)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s8) from unknown-address + 14, align 2)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 15
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s8) from unknown-address + 15)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s8) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 17
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s8) from unknown-address + 17)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s8) from unknown-address + 18, align 2)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 19
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s8) from unknown-address + 19)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s8) from unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 21
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s8) from unknown-address + 21)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s8) from unknown-address + 22, align 2)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 23
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s8) from unknown-address + 23)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s8) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 25
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s8) from unknown-address + 25)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s8) from unknown-address + 26, align 2)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 27
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s8) from unknown-address + 27)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s8) from unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 29
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s8) from unknown-address + 29)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s8) from unknown-address + 30, align 2)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 31
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s8) from unknown-address + 31)
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; CHECK-NEXT: [[LOAD32:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD31]](p0) :: (load (s8) from unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 33
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: [[LOAD33:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD32]](p0) :: (load (s8) from unknown-address + 33)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: [[LOAD34:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD33]](p0) :: (load (s8) from unknown-address + 34, align 2)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 35
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: [[LOAD35:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD34]](p0) :: (load (s8) from unknown-address + 35)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: [[LOAD36:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD35]](p0) :: (load (s8) from unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 37
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: [[LOAD37:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD36]](p0) :: (load (s8) from unknown-address + 37)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: [[LOAD38:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD37]](p0) :: (load (s8) from unknown-address + 38, align 2)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 39
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: [[LOAD39:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD38]](p0) :: (load (s8) from unknown-address + 39)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: [[LOAD40:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD39]](p0) :: (load (s8) from unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 41
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: [[LOAD41:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD40]](p0) :: (load (s8) from unknown-address + 41)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: [[LOAD42:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD41]](p0) :: (load (s8) from unknown-address + 42, align 2)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 43
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: [[LOAD43:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD42]](p0) :: (load (s8) from unknown-address + 43)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: [[LOAD44:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD43]](p0) :: (load (s8) from unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 45
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: [[LOAD45:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD44]](p0) :: (load (s8) from unknown-address + 45)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: [[LOAD46:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD45]](p0) :: (load (s8) from unknown-address + 46, align 2)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 47
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: [[LOAD47:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD46]](p0) :: (load (s8) from unknown-address + 47)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: [[LOAD48:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD47]](p0) :: (load (s8) from unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 49
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: [[LOAD49:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD48]](p0) :: (load (s8) from unknown-address + 49)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: [[LOAD50:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD49]](p0) :: (load (s8) from unknown-address + 50, align 2)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 51
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: [[LOAD51:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD50]](p0) :: (load (s8) from unknown-address + 51)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: [[LOAD52:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD51]](p0) :: (load (s8) from unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 53
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: [[LOAD53:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD52]](p0) :: (load (s8) from unknown-address + 53)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: [[LOAD54:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD53]](p0) :: (load (s8) from unknown-address + 54, align 2)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 55
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: [[LOAD55:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD54]](p0) :: (load (s8) from unknown-address + 55)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: [[LOAD56:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD55]](p0) :: (load (s8) from unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 57
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: [[LOAD57:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD56]](p0) :: (load (s8) from unknown-address + 57)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: [[LOAD58:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD57]](p0) :: (load (s8) from unknown-address + 58, align 2)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 59
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: [[LOAD59:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD58]](p0) :: (load (s8) from unknown-address + 59)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: [[LOAD60:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD59]](p0) :: (load (s8) from unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 61
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: [[LOAD61:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD60]](p0) :: (load (s8) from unknown-address + 61)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: [[LOAD62:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD61]](p0) :: (load (s8) from unknown-address + 62, align 2)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 63
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: [[LOAD63:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD62]](p0) :: (load (s8) from unknown-address + 63)
    ; CHECK-NEXT: [[C63:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD63:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C63]](s20)
    ; CHECK-NEXT: [[LOAD64:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD63]](p0) :: (load (s8) from unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C64:%[0-9]+]]:_(s20) = G_CONSTANT i20 65
    ; CHECK-NEXT: [[PTR_ADD64:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C64]](s20)
    ; CHECK-NEXT: [[LOAD65:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD64]](p0) :: (load (s8) from unknown-address + 65)
    ; CHECK-NEXT: [[C65:%[0-9]+]]:_(s20) = G_CONSTANT i20 66
    ; CHECK-NEXT: [[PTR_ADD65:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C65]](s20)
    ; CHECK-NEXT: [[LOAD66:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD65]](p0) :: (load (s8) from unknown-address + 66, align 2)
    ; CHECK-NEXT: [[C66:%[0-9]+]]:_(s20) = G_CONSTANT i20 67
    ; CHECK-NEXT: [[PTR_ADD66:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C66]](s20)
    ; CHECK-NEXT: [[LOAD67:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD66]](p0) :: (load (s8) from unknown-address + 67)
    ; CHECK-NEXT: [[C67:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD67:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C67]](s20)
    ; CHECK-NEXT: [[LOAD68:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD67]](p0) :: (load (s8) from unknown-address + 68, align 4)
    ; CHECK-NEXT: [[C68:%[0-9]+]]:_(s20) = G_CONSTANT i20 69
    ; CHECK-NEXT: [[PTR_ADD68:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C68]](s20)
    ; CHECK-NEXT: [[LOAD69:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD68]](p0) :: (load (s8) from unknown-address + 69)
    ; CHECK-NEXT: [[C69:%[0-9]+]]:_(s20) = G_CONSTANT i20 70
    ; CHECK-NEXT: [[PTR_ADD69:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C69]](s20)
    ; CHECK-NEXT: [[LOAD70:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD69]](p0) :: (load (s8) from unknown-address + 70, align 2)
    ; CHECK-NEXT: [[C70:%[0-9]+]]:_(s20) = G_CONSTANT i20 71
    ; CHECK-NEXT: [[PTR_ADD70:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C70]](s20)
    ; CHECK-NEXT: [[LOAD71:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD70]](p0) :: (load (s8) from unknown-address + 71)
    ; CHECK-NEXT: [[C71:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD71:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C71]](s20)
    ; CHECK-NEXT: [[LOAD72:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD71]](p0) :: (load (s8) from unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C72:%[0-9]+]]:_(s20) = G_CONSTANT i20 73
    ; CHECK-NEXT: [[PTR_ADD72:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C72]](s20)
    ; CHECK-NEXT: [[LOAD73:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD72]](p0) :: (load (s8) from unknown-address + 73)
    ; CHECK-NEXT: [[C73:%[0-9]+]]:_(s20) = G_CONSTANT i20 74
    ; CHECK-NEXT: [[PTR_ADD73:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C73]](s20)
    ; CHECK-NEXT: [[LOAD74:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD73]](p0) :: (load (s8) from unknown-address + 74, align 2)
    ; CHECK-NEXT: [[C74:%[0-9]+]]:_(s20) = G_CONSTANT i20 75
    ; CHECK-NEXT: [[PTR_ADD74:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C74]](s20)
    ; CHECK-NEXT: [[LOAD75:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD74]](p0) :: (load (s8) from unknown-address + 75)
    ; CHECK-NEXT: [[C75:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD75:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C75]](s20)
    ; CHECK-NEXT: [[LOAD76:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD75]](p0) :: (load (s8) from unknown-address + 76, align 4)
    ; CHECK-NEXT: [[C76:%[0-9]+]]:_(s20) = G_CONSTANT i20 77
    ; CHECK-NEXT: [[PTR_ADD76:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C76]](s20)
    ; CHECK-NEXT: [[LOAD77:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD76]](p0) :: (load (s8) from unknown-address + 77)
    ; CHECK-NEXT: [[C77:%[0-9]+]]:_(s20) = G_CONSTANT i20 78
    ; CHECK-NEXT: [[PTR_ADD77:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C77]](s20)
    ; CHECK-NEXT: [[LOAD78:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD77]](p0) :: (load (s8) from unknown-address + 78, align 2)
    ; CHECK-NEXT: [[C78:%[0-9]+]]:_(s20) = G_CONSTANT i20 79
    ; CHECK-NEXT: [[PTR_ADD78:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C78]](s20)
    ; CHECK-NEXT: [[LOAD79:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD78]](p0) :: (load (s8) from unknown-address + 79)
    ; CHECK-NEXT: [[C79:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD79:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C79]](s20)
    ; CHECK-NEXT: [[LOAD80:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD79]](p0) :: (load (s8) from unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C80:%[0-9]+]]:_(s20) = G_CONSTANT i20 81
    ; CHECK-NEXT: [[PTR_ADD80:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C80]](s20)
    ; CHECK-NEXT: [[LOAD81:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD80]](p0) :: (load (s8) from unknown-address + 81)
    ; CHECK-NEXT: [[C81:%[0-9]+]]:_(s20) = G_CONSTANT i20 82
    ; CHECK-NEXT: [[PTR_ADD81:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C81]](s20)
    ; CHECK-NEXT: [[LOAD82:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD81]](p0) :: (load (s8) from unknown-address + 82, align 2)
    ; CHECK-NEXT: [[C82:%[0-9]+]]:_(s20) = G_CONSTANT i20 83
    ; CHECK-NEXT: [[PTR_ADD82:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C82]](s20)
    ; CHECK-NEXT: [[LOAD83:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD82]](p0) :: (load (s8) from unknown-address + 83)
    ; CHECK-NEXT: [[C83:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD83:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C83]](s20)
    ; CHECK-NEXT: [[LOAD84:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD83]](p0) :: (load (s8) from unknown-address + 84, align 4)
    ; CHECK-NEXT: [[C84:%[0-9]+]]:_(s20) = G_CONSTANT i20 85
    ; CHECK-NEXT: [[PTR_ADD84:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C84]](s20)
    ; CHECK-NEXT: [[LOAD85:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD84]](p0) :: (load (s8) from unknown-address + 85)
    ; CHECK-NEXT: [[C85:%[0-9]+]]:_(s20) = G_CONSTANT i20 86
    ; CHECK-NEXT: [[PTR_ADD85:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C85]](s20)
    ; CHECK-NEXT: [[LOAD86:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD85]](p0) :: (load (s8) from unknown-address + 86, align 2)
    ; CHECK-NEXT: [[C86:%[0-9]+]]:_(s20) = G_CONSTANT i20 87
    ; CHECK-NEXT: [[PTR_ADD86:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C86]](s20)
    ; CHECK-NEXT: [[LOAD87:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD86]](p0) :: (load (s8) from unknown-address + 87)
    ; CHECK-NEXT: [[C87:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD87:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C87]](s20)
    ; CHECK-NEXT: [[LOAD88:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD87]](p0) :: (load (s8) from unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C88:%[0-9]+]]:_(s20) = G_CONSTANT i20 89
    ; CHECK-NEXT: [[PTR_ADD88:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C88]](s20)
    ; CHECK-NEXT: [[LOAD89:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD88]](p0) :: (load (s8) from unknown-address + 89)
    ; CHECK-NEXT: [[C89:%[0-9]+]]:_(s20) = G_CONSTANT i20 90
    ; CHECK-NEXT: [[PTR_ADD89:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C89]](s20)
    ; CHECK-NEXT: [[LOAD90:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD89]](p0) :: (load (s8) from unknown-address + 90, align 2)
    ; CHECK-NEXT: [[C90:%[0-9]+]]:_(s20) = G_CONSTANT i20 91
    ; CHECK-NEXT: [[PTR_ADD90:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C90]](s20)
    ; CHECK-NEXT: [[LOAD91:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD90]](p0) :: (load (s8) from unknown-address + 91)
    ; CHECK-NEXT: [[C91:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD91:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C91]](s20)
    ; CHECK-NEXT: [[LOAD92:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD91]](p0) :: (load (s8) from unknown-address + 92, align 4)
    ; CHECK-NEXT: [[C92:%[0-9]+]]:_(s20) = G_CONSTANT i20 93
    ; CHECK-NEXT: [[PTR_ADD92:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C92]](s20)
    ; CHECK-NEXT: [[LOAD93:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD92]](p0) :: (load (s8) from unknown-address + 93)
    ; CHECK-NEXT: [[C93:%[0-9]+]]:_(s20) = G_CONSTANT i20 94
    ; CHECK-NEXT: [[PTR_ADD93:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C93]](s20)
    ; CHECK-NEXT: [[LOAD94:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD93]](p0) :: (load (s8) from unknown-address + 94, align 2)
    ; CHECK-NEXT: [[C94:%[0-9]+]]:_(s20) = G_CONSTANT i20 95
    ; CHECK-NEXT: [[PTR_ADD94:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C94]](s20)
    ; CHECK-NEXT: [[LOAD95:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD94]](p0) :: (load (s8) from unknown-address + 95)
    ; CHECK-NEXT: [[C95:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD95:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C95]](s20)
    ; CHECK-NEXT: [[LOAD96:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD95]](p0) :: (load (s8) from unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C96:%[0-9]+]]:_(s20) = G_CONSTANT i20 97
    ; CHECK-NEXT: [[PTR_ADD96:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C96]](s20)
    ; CHECK-NEXT: [[LOAD97:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD96]](p0) :: (load (s8) from unknown-address + 97)
    ; CHECK-NEXT: [[C97:%[0-9]+]]:_(s20) = G_CONSTANT i20 98
    ; CHECK-NEXT: [[PTR_ADD97:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C97]](s20)
    ; CHECK-NEXT: [[LOAD98:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD97]](p0) :: (load (s8) from unknown-address + 98, align 2)
    ; CHECK-NEXT: [[C98:%[0-9]+]]:_(s20) = G_CONSTANT i20 99
    ; CHECK-NEXT: [[PTR_ADD98:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C98]](s20)
    ; CHECK-NEXT: [[LOAD99:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD98]](p0) :: (load (s8) from unknown-address + 99)
    ; CHECK-NEXT: [[C99:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD99:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C99]](s20)
    ; CHECK-NEXT: [[LOAD100:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD99]](p0) :: (load (s8) from unknown-address + 100, align 4)
    ; CHECK-NEXT: [[C100:%[0-9]+]]:_(s20) = G_CONSTANT i20 101
    ; CHECK-NEXT: [[PTR_ADD100:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C100]](s20)
    ; CHECK-NEXT: [[LOAD101:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD100]](p0) :: (load (s8) from unknown-address + 101)
    ; CHECK-NEXT: [[C101:%[0-9]+]]:_(s20) = G_CONSTANT i20 102
    ; CHECK-NEXT: [[PTR_ADD101:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C101]](s20)
    ; CHECK-NEXT: [[LOAD102:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD101]](p0) :: (load (s8) from unknown-address + 102, align 2)
    ; CHECK-NEXT: [[C102:%[0-9]+]]:_(s20) = G_CONSTANT i20 103
    ; CHECK-NEXT: [[PTR_ADD102:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C102]](s20)
    ; CHECK-NEXT: [[LOAD103:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD102]](p0) :: (load (s8) from unknown-address + 103)
    ; CHECK-NEXT: [[C103:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD103:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C103]](s20)
    ; CHECK-NEXT: [[LOAD104:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD103]](p0) :: (load (s8) from unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C104:%[0-9]+]]:_(s20) = G_CONSTANT i20 105
    ; CHECK-NEXT: [[PTR_ADD104:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C104]](s20)
    ; CHECK-NEXT: [[LOAD105:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD104]](p0) :: (load (s8) from unknown-address + 105)
    ; CHECK-NEXT: [[C105:%[0-9]+]]:_(s20) = G_CONSTANT i20 106
    ; CHECK-NEXT: [[PTR_ADD105:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C105]](s20)
    ; CHECK-NEXT: [[LOAD106:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD105]](p0) :: (load (s8) from unknown-address + 106, align 2)
    ; CHECK-NEXT: [[C106:%[0-9]+]]:_(s20) = G_CONSTANT i20 107
    ; CHECK-NEXT: [[PTR_ADD106:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C106]](s20)
    ; CHECK-NEXT: [[LOAD107:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD106]](p0) :: (load (s8) from unknown-address + 107)
    ; CHECK-NEXT: [[C107:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD107:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C107]](s20)
    ; CHECK-NEXT: [[LOAD108:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD107]](p0) :: (load (s8) from unknown-address + 108, align 4)
    ; CHECK-NEXT: [[C108:%[0-9]+]]:_(s20) = G_CONSTANT i20 109
    ; CHECK-NEXT: [[PTR_ADD108:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C108]](s20)
    ; CHECK-NEXT: [[LOAD109:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD108]](p0) :: (load (s8) from unknown-address + 109)
    ; CHECK-NEXT: [[C109:%[0-9]+]]:_(s20) = G_CONSTANT i20 110
    ; CHECK-NEXT: [[PTR_ADD109:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C109]](s20)
    ; CHECK-NEXT: [[LOAD110:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD109]](p0) :: (load (s8) from unknown-address + 110, align 2)
    ; CHECK-NEXT: [[C110:%[0-9]+]]:_(s20) = G_CONSTANT i20 111
    ; CHECK-NEXT: [[PTR_ADD110:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C110]](s20)
    ; CHECK-NEXT: [[LOAD111:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD110]](p0) :: (load (s8) from unknown-address + 111)
    ; CHECK-NEXT: [[C111:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD111:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C111]](s20)
    ; CHECK-NEXT: [[LOAD112:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD111]](p0) :: (load (s8) from unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C112:%[0-9]+]]:_(s20) = G_CONSTANT i20 113
    ; CHECK-NEXT: [[PTR_ADD112:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C112]](s20)
    ; CHECK-NEXT: [[LOAD113:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD112]](p0) :: (load (s8) from unknown-address + 113)
    ; CHECK-NEXT: [[C113:%[0-9]+]]:_(s20) = G_CONSTANT i20 114
    ; CHECK-NEXT: [[PTR_ADD113:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C113]](s20)
    ; CHECK-NEXT: [[LOAD114:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD113]](p0) :: (load (s8) from unknown-address + 114, align 2)
    ; CHECK-NEXT: [[C114:%[0-9]+]]:_(s20) = G_CONSTANT i20 115
    ; CHECK-NEXT: [[PTR_ADD114:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C114]](s20)
    ; CHECK-NEXT: [[LOAD115:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD114]](p0) :: (load (s8) from unknown-address + 115)
    ; CHECK-NEXT: [[C115:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD115:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C115]](s20)
    ; CHECK-NEXT: [[LOAD116:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD115]](p0) :: (load (s8) from unknown-address + 116, align 4)
    ; CHECK-NEXT: [[C116:%[0-9]+]]:_(s20) = G_CONSTANT i20 117
    ; CHECK-NEXT: [[PTR_ADD116:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C116]](s20)
    ; CHECK-NEXT: [[LOAD117:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD116]](p0) :: (load (s8) from unknown-address + 117)
    ; CHECK-NEXT: [[C117:%[0-9]+]]:_(s20) = G_CONSTANT i20 118
    ; CHECK-NEXT: [[PTR_ADD117:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C117]](s20)
    ; CHECK-NEXT: [[LOAD118:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD117]](p0) :: (load (s8) from unknown-address + 118, align 2)
    ; CHECK-NEXT: [[C118:%[0-9]+]]:_(s20) = G_CONSTANT i20 119
    ; CHECK-NEXT: [[PTR_ADD118:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C118]](s20)
    ; CHECK-NEXT: [[LOAD119:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD118]](p0) :: (load (s8) from unknown-address + 119)
    ; CHECK-NEXT: [[C119:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD119:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C119]](s20)
    ; CHECK-NEXT: [[LOAD120:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD119]](p0) :: (load (s8) from unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C120:%[0-9]+]]:_(s20) = G_CONSTANT i20 121
    ; CHECK-NEXT: [[PTR_ADD120:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C120]](s20)
    ; CHECK-NEXT: [[LOAD121:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD120]](p0) :: (load (s8) from unknown-address + 121)
    ; CHECK-NEXT: [[C121:%[0-9]+]]:_(s20) = G_CONSTANT i20 122
    ; CHECK-NEXT: [[PTR_ADD121:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C121]](s20)
    ; CHECK-NEXT: [[LOAD122:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD121]](p0) :: (load (s8) from unknown-address + 122, align 2)
    ; CHECK-NEXT: [[C122:%[0-9]+]]:_(s20) = G_CONSTANT i20 123
    ; CHECK-NEXT: [[PTR_ADD122:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C122]](s20)
    ; CHECK-NEXT: [[LOAD123:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD122]](p0) :: (load (s8) from unknown-address + 123)
    ; CHECK-NEXT: [[C123:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD123:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C123]](s20)
    ; CHECK-NEXT: [[LOAD124:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD123]](p0) :: (load (s8) from unknown-address + 124, align 4)
    ; CHECK-NEXT: [[C124:%[0-9]+]]:_(s20) = G_CONSTANT i20 125
    ; CHECK-NEXT: [[PTR_ADD124:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C124]](s20)
    ; CHECK-NEXT: [[LOAD125:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD124]](p0) :: (load (s8) from unknown-address + 125)
    ; CHECK-NEXT: [[C125:%[0-9]+]]:_(s20) = G_CONSTANT i20 126
    ; CHECK-NEXT: [[PTR_ADD125:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C125]](s20)
    ; CHECK-NEXT: [[LOAD126:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD125]](p0) :: (load (s8) from unknown-address + 126, align 2)
    ; CHECK-NEXT: [[C126:%[0-9]+]]:_(s20) = G_CONSTANT i20 127
    ; CHECK-NEXT: [[PTR_ADD126:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C126]](s20)
    ; CHECK-NEXT: [[LOAD127:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD126]](p0) :: (load (s8) from unknown-address + 127)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI32:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI31]], [[LOAD32]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI33:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI32]], [[LOAD33]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI34:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI33]], [[LOAD34]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI35:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI34]], [[LOAD35]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI36:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI35]], [[LOAD36]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI37:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI36]], [[LOAD37]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI38:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI37]], [[LOAD38]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI39:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI38]], [[LOAD39]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI40:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI39]], [[LOAD40]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI41:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI40]], [[LOAD41]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI42:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI41]], [[LOAD42]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI43:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI42]], [[LOAD43]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI44:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI43]], [[LOAD44]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI45:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI44]], [[LOAD45]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI46:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI45]], [[LOAD46]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI47:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI46]], [[LOAD47]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI48:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI47]], [[LOAD48]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI49:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI48]], [[LOAD49]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI50:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI49]], [[LOAD50]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI51:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI50]], [[LOAD51]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI52:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI51]], [[LOAD52]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI53:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI52]], [[LOAD53]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI54:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI53]], [[LOAD54]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI55:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI54]], [[LOAD55]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI56:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI55]], [[LOAD56]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI57:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI56]], [[LOAD57]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI58:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI57]], [[LOAD58]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI59:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI58]], [[LOAD59]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI60:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI59]], [[LOAD60]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI61:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI60]], [[LOAD61]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI62:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI61]], [[LOAD62]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI63:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI62]], [[LOAD63]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY [[DEF]](<64 x s8>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI64:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[LOAD64]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI65:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI64]], [[LOAD65]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI66:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI65]], [[LOAD66]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI67:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI66]], [[LOAD67]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI68:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI67]], [[LOAD68]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI69:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI68]], [[LOAD69]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI70:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI69]], [[LOAD70]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI71:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI70]], [[LOAD71]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI72:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI71]], [[LOAD72]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI73:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI72]], [[LOAD73]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI74:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI73]], [[LOAD74]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI75:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI74]], [[LOAD75]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI76:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI75]], [[LOAD76]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI77:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI76]], [[LOAD77]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI78:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI77]], [[LOAD78]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI79:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI78]], [[LOAD79]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI80:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI79]], [[LOAD80]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI81:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI80]], [[LOAD81]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI82:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI81]], [[LOAD82]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI83:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI82]], [[LOAD83]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI84:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI83]], [[LOAD84]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI85:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI84]], [[LOAD85]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI86:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI85]], [[LOAD86]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI87:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI86]], [[LOAD87]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI88:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI87]], [[LOAD88]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI89:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI88]], [[LOAD89]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI90:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI89]], [[LOAD90]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI91:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI90]], [[LOAD91]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI92:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI91]], [[LOAD92]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI93:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI92]], [[LOAD93]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI94:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI93]], [[LOAD94]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI95:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI94]], [[LOAD95]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI96:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI95]], [[LOAD96]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI97:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI96]], [[LOAD97]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI98:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI97]], [[LOAD98]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI99:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI98]], [[LOAD99]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI100:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI99]], [[LOAD100]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI101:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI100]], [[LOAD101]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI102:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI101]], [[LOAD102]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI103:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI102]], [[LOAD103]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI104:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI103]], [[LOAD104]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI105:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI104]], [[LOAD105]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI106:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI105]], [[LOAD106]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI107:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI106]], [[LOAD107]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI108:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI107]], [[LOAD108]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI109:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI108]], [[LOAD109]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI110:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI109]], [[LOAD110]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI111:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI110]], [[LOAD111]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI112:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI111]], [[LOAD112]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI113:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI112]], [[LOAD113]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI114:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI113]], [[LOAD114]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI115:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI114]], [[LOAD115]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI116:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI115]], [[LOAD116]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI117:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI116]], [[LOAD117]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI118:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI117]], [[LOAD118]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI119:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI118]], [[LOAD119]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI120:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI119]], [[LOAD120]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI121:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI120]], [[LOAD121]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI122:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI121]], [[LOAD122]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI123:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI122]], [[LOAD123]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI124:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI123]], [[LOAD124]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI125:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI124]], [[LOAD125]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI126:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI125]], [[LOAD126]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI127:%[0-9]+]]:_(<64 x s8>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI126]], [[LOAD127]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI63]](<64 x s8>), [[AIE_ADD_VECTOR_ELT_HI127]](<64 x s8>)
    ; CHECK-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<128 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(p0) = COPY $p0
    %0:_(<128 x s8>) = G_LOAD %1(p0) :: (load (<128 x s8>), align 16)
    $y2 = COPY %0(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2

...

---
name:            test_v64int16_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64int16_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s16) from unknown-address + 2)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s16) from unknown-address + 4, align 4)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s16) from unknown-address + 6)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s16) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 10
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s16) from unknown-address + 10)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s16) from unknown-address + 12, align 4)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 14
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s16) from unknown-address + 14)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s16) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 18
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s16) from unknown-address + 18)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s16) from unknown-address + 20, align 4)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 22
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s16) from unknown-address + 22)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s16) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 26
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s16) from unknown-address + 26)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s16) from unknown-address + 28, align 4)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 30
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s16) from unknown-address + 30)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s16) from unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 34
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s16) from unknown-address + 34)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s16) from unknown-address + 36, align 4)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 38
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s16) from unknown-address + 38)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s16) from unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 42
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s16) from unknown-address + 42)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s16) from unknown-address + 44, align 4)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 46
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s16) from unknown-address + 46)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s16) from unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 50
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s16) from unknown-address + 50)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s16) from unknown-address + 52, align 4)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 54
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s16) from unknown-address + 54)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s16) from unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 58
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s16) from unknown-address + 58)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s16) from unknown-address + 60, align 4)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 62
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s16) from unknown-address + 62)
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; CHECK-NEXT: [[LOAD32:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD31]](p0) :: (load (s16) from unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 66
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: [[LOAD33:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD32]](p0) :: (load (s16) from unknown-address + 66)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: [[LOAD34:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD33]](p0) :: (load (s16) from unknown-address + 68, align 4)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 70
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: [[LOAD35:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD34]](p0) :: (load (s16) from unknown-address + 70)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: [[LOAD36:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD35]](p0) :: (load (s16) from unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 74
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: [[LOAD37:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD36]](p0) :: (load (s16) from unknown-address + 74)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: [[LOAD38:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD37]](p0) :: (load (s16) from unknown-address + 76, align 4)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 78
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: [[LOAD39:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD38]](p0) :: (load (s16) from unknown-address + 78)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: [[LOAD40:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD39]](p0) :: (load (s16) from unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 82
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: [[LOAD41:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD40]](p0) :: (load (s16) from unknown-address + 82)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: [[LOAD42:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD41]](p0) :: (load (s16) from unknown-address + 84, align 4)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 86
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: [[LOAD43:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD42]](p0) :: (load (s16) from unknown-address + 86)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: [[LOAD44:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD43]](p0) :: (load (s16) from unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 90
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: [[LOAD45:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD44]](p0) :: (load (s16) from unknown-address + 90)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: [[LOAD46:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD45]](p0) :: (load (s16) from unknown-address + 92, align 4)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 94
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: [[LOAD47:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD46]](p0) :: (load (s16) from unknown-address + 94)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: [[LOAD48:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD47]](p0) :: (load (s16) from unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 98
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: [[LOAD49:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD48]](p0) :: (load (s16) from unknown-address + 98)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: [[LOAD50:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD49]](p0) :: (load (s16) from unknown-address + 100, align 4)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 102
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: [[LOAD51:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD50]](p0) :: (load (s16) from unknown-address + 102)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: [[LOAD52:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD51]](p0) :: (load (s16) from unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 106
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: [[LOAD53:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD52]](p0) :: (load (s16) from unknown-address + 106)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: [[LOAD54:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD53]](p0) :: (load (s16) from unknown-address + 108, align 4)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 110
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: [[LOAD55:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD54]](p0) :: (load (s16) from unknown-address + 110)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: [[LOAD56:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD55]](p0) :: (load (s16) from unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 114
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: [[LOAD57:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD56]](p0) :: (load (s16) from unknown-address + 114)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: [[LOAD58:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD57]](p0) :: (load (s16) from unknown-address + 116, align 4)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 118
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: [[LOAD59:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD58]](p0) :: (load (s16) from unknown-address + 118)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: [[LOAD60:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD59]](p0) :: (load (s16) from unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 122
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: [[LOAD61:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD60]](p0) :: (load (s16) from unknown-address + 122)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: [[LOAD62:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD61]](p0) :: (load (s16) from unknown-address + 124, align 4)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 126
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: [[LOAD63:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD62]](p0) :: (load (s16) from unknown-address + 126)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI15]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY [[DEF]](<32 x s16>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI32:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[LOAD32]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI33:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI32]], [[LOAD33]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI34:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI33]], [[LOAD34]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI35:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI34]], [[LOAD35]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI36:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI35]], [[LOAD36]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI37:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI36]], [[LOAD37]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI38:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI37]], [[LOAD38]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI39:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI38]], [[LOAD39]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI40:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI39]], [[LOAD40]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI41:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI40]], [[LOAD41]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI42:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI41]], [[LOAD42]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI43:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI42]], [[LOAD43]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI44:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI43]], [[LOAD44]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI45:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI44]], [[LOAD45]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI46:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI45]], [[LOAD46]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI47:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI46]], [[LOAD47]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI48:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI47]], [[LOAD48]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI49:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI48]], [[LOAD49]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI50:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI49]], [[LOAD50]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI51:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI50]], [[LOAD51]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI52:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI51]], [[LOAD52]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI53:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI52]], [[LOAD53]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI54:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI53]], [[LOAD54]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI55:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI54]], [[LOAD55]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI56:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI55]], [[LOAD56]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI57:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI56]], [[LOAD57]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI58:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI57]], [[LOAD58]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI59:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI58]], [[LOAD59]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI60:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI59]], [[LOAD60]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI61:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI60]], [[LOAD61]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI62:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI61]], [[LOAD62]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI63:%[0-9]+]]:_(<32 x s16>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI62]], [[LOAD63]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI31]](<32 x s16>), [[AIE_ADD_VECTOR_ELT_HI63]](<32 x s16>)
    ; CHECK-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<64 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(p0) = COPY $p0
    %0:_(<64 x s16>) = G_LOAD %1(p0) :: (load (<64 x s16>), align 16)
    $y2 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2

...

---
name:            test_v32int32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v32int32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s32) from unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s32) from unknown-address + 68)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s32) from unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s32) from unknown-address + 76)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s32) from unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s32) from unknown-address + 84)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s32) from unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s32) from unknown-address + 92)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s32) from unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s32) from unknown-address + 100)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s32) from unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s32) from unknown-address + 108)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s32) from unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s32) from unknown-address + 116)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s32) from unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s32) from unknown-address + 124)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI31]](<16 x s32>)
    ; CHECK-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:_(p0) = COPY $p0
    %0:_(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>), align 16)
    $y2 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $y2

...

---
name:            test_v32acc32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2P-LABEL: name: test_v32acc32_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; AIE2P-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; AIE2P-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD2]](s32), [[LOAD3]](s32)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; AIE2P-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD4]](s32), [[LOAD5]](s32)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; AIE2P-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD6]](s32), [[LOAD7]](s32)
    ; AIE2P-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2P-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; AIE2P-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; AIE2P-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD8]](s32), [[LOAD9]](s32)
    ; AIE2P-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2P-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2P-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; AIE2P-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; AIE2P-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD10]](s32), [[LOAD11]](s32)
    ; AIE2P-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2P-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2P-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; AIE2P-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; AIE2P-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD12]](s32), [[LOAD13]](s32)
    ; AIE2P-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2P-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2P-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; AIE2P-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; AIE2P-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD14]](s32), [[LOAD15]](s32)
    ; AIE2P-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; AIE2P-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s32) from unknown-address + 64, align 16)
    ; AIE2P-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD15]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s32) from unknown-address + 68)
    ; AIE2P-NEXT: [[MV8:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD16]](s32), [[LOAD17]](s32)
    ; AIE2P-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; AIE2P-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; AIE2P-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s32) from unknown-address + 72, align 8)
    ; AIE2P-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD17]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s32) from unknown-address + 76)
    ; AIE2P-NEXT: [[MV9:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD18]](s32), [[LOAD19]](s32)
    ; AIE2P-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2P-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; AIE2P-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s32) from unknown-address + 80, align 16)
    ; AIE2P-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD19]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s32) from unknown-address + 84)
    ; AIE2P-NEXT: [[MV10:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD20]](s32), [[LOAD21]](s32)
    ; AIE2P-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; AIE2P-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; AIE2P-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s32) from unknown-address + 88, align 8)
    ; AIE2P-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD21]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s32) from unknown-address + 92)
    ; AIE2P-NEXT: [[MV11:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD22]](s32), [[LOAD23]](s32)
    ; AIE2P-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; AIE2P-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s32) from unknown-address + 96, align 16)
    ; AIE2P-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD23]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s32) from unknown-address + 100)
    ; AIE2P-NEXT: [[MV12:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD24]](s32), [[LOAD25]](s32)
    ; AIE2P-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; AIE2P-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; AIE2P-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s32) from unknown-address + 104, align 8)
    ; AIE2P-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD25]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s32) from unknown-address + 108)
    ; AIE2P-NEXT: [[MV13:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD26]](s32), [[LOAD27]](s32)
    ; AIE2P-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; AIE2P-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; AIE2P-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s32) from unknown-address + 112, align 16)
    ; AIE2P-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD27]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s32) from unknown-address + 116)
    ; AIE2P-NEXT: [[MV14:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD28]](s32), [[LOAD29]](s32)
    ; AIE2P-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; AIE2P-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; AIE2P-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s32) from unknown-address + 120, align 8)
    ; AIE2P-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD29]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s32) from unknown-address + 124)
    ; AIE2P-NEXT: [[MV15:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD30]](s32), [[LOAD31]](s32)
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[MV]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[MV1]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[MV2]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[MV3]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[MV4]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[MV5]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[MV6]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[MV7]](s64)
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[MV8]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[MV9]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[MV10]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[MV11]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[MV12]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[MV13]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[MV14]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[MV15]](s64)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI15]](<8 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s64>)
    ;
    ; AIE2PS-LABEL: name: test_v32acc32_unaligned
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64), align 16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from unknown-address + 8)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from unknown-address + 16, align 16)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD2]](p0) :: (load (s64) from unknown-address + 24)
    ; AIE2PS-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2PS-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2PS-NEXT: [[LOAD4:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD3]](p0) :: (load (s64) from unknown-address + 32, align 16)
    ; AIE2PS-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2PS-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2PS-NEXT: [[LOAD5:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD4]](p0) :: (load (s64) from unknown-address + 40)
    ; AIE2PS-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2PS-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2PS-NEXT: [[LOAD6:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD5]](p0) :: (load (s64) from unknown-address + 48, align 16)
    ; AIE2PS-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2PS-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2PS-NEXT: [[LOAD7:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD6]](p0) :: (load (s64) from unknown-address + 56)
    ; AIE2PS-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2PS-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2PS-NEXT: [[LOAD8:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD7]](p0) :: (load (s64) from unknown-address + 64, align 16)
    ; AIE2PS-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; AIE2PS-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; AIE2PS-NEXT: [[LOAD9:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD8]](p0) :: (load (s64) from unknown-address + 72)
    ; AIE2PS-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2PS-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; AIE2PS-NEXT: [[LOAD10:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD9]](p0) :: (load (s64) from unknown-address + 80, align 16)
    ; AIE2PS-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; AIE2PS-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; AIE2PS-NEXT: [[LOAD11:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD10]](p0) :: (load (s64) from unknown-address + 88)
    ; AIE2PS-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2PS-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; AIE2PS-NEXT: [[LOAD12:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD11]](p0) :: (load (s64) from unknown-address + 96, align 16)
    ; AIE2PS-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; AIE2PS-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; AIE2PS-NEXT: [[LOAD13:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD12]](p0) :: (load (s64) from unknown-address + 104)
    ; AIE2PS-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; AIE2PS-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; AIE2PS-NEXT: [[LOAD14:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD13]](p0) :: (load (s64) from unknown-address + 112, align 16)
    ; AIE2PS-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; AIE2PS-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; AIE2PS-NEXT: [[LOAD15:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD14]](p0) :: (load (s64) from unknown-address + 120)
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s64)
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[LOAD8]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s64)
    ; AIE2PS-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI15]](<8 x s64>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s64>) = G_LOAD %1(p0) :: (load (<16 x s64>), align 16)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v16acc64_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2P-LABEL: name: test_v16acc64_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; AIE2P-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; AIE2P-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD2]](s32), [[LOAD3]](s32)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; AIE2P-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD4]](s32), [[LOAD5]](s32)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; AIE2P-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD6]](s32), [[LOAD7]](s32)
    ; AIE2P-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2P-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; AIE2P-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; AIE2P-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD8]](s32), [[LOAD9]](s32)
    ; AIE2P-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2P-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2P-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; AIE2P-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; AIE2P-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD10]](s32), [[LOAD11]](s32)
    ; AIE2P-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2P-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2P-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; AIE2P-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; AIE2P-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD12]](s32), [[LOAD13]](s32)
    ; AIE2P-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2P-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2P-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; AIE2P-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; AIE2P-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD14]](s32), [[LOAD15]](s32)
    ; AIE2P-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; AIE2P-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s32) from unknown-address + 64, align 16)
    ; AIE2P-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD15]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s32) from unknown-address + 68)
    ; AIE2P-NEXT: [[MV8:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD16]](s32), [[LOAD17]](s32)
    ; AIE2P-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; AIE2P-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; AIE2P-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s32) from unknown-address + 72, align 8)
    ; AIE2P-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD17]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s32) from unknown-address + 76)
    ; AIE2P-NEXT: [[MV9:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD18]](s32), [[LOAD19]](s32)
    ; AIE2P-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2P-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; AIE2P-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s32) from unknown-address + 80, align 16)
    ; AIE2P-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD19]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s32) from unknown-address + 84)
    ; AIE2P-NEXT: [[MV10:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD20]](s32), [[LOAD21]](s32)
    ; AIE2P-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; AIE2P-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; AIE2P-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s32) from unknown-address + 88, align 8)
    ; AIE2P-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD21]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s32) from unknown-address + 92)
    ; AIE2P-NEXT: [[MV11:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD22]](s32), [[LOAD23]](s32)
    ; AIE2P-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; AIE2P-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s32) from unknown-address + 96, align 16)
    ; AIE2P-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD23]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s32) from unknown-address + 100)
    ; AIE2P-NEXT: [[MV12:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD24]](s32), [[LOAD25]](s32)
    ; AIE2P-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; AIE2P-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; AIE2P-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s32) from unknown-address + 104, align 8)
    ; AIE2P-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD25]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s32) from unknown-address + 108)
    ; AIE2P-NEXT: [[MV13:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD26]](s32), [[LOAD27]](s32)
    ; AIE2P-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; AIE2P-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; AIE2P-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s32) from unknown-address + 112, align 16)
    ; AIE2P-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD27]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s32) from unknown-address + 116)
    ; AIE2P-NEXT: [[MV14:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD28]](s32), [[LOAD29]](s32)
    ; AIE2P-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; AIE2P-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; AIE2P-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s32) from unknown-address + 120, align 8)
    ; AIE2P-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD29]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s32) from unknown-address + 124)
    ; AIE2P-NEXT: [[MV15:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD30]](s32), [[LOAD31]](s32)
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[MV]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[MV1]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[MV2]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[MV3]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[MV4]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[MV5]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[MV6]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[MV7]](s64)
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[MV8]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[MV9]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[MV10]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[MV11]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[MV12]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[MV13]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[MV14]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[MV15]](s64)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI15]](<8 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s64>)
    ;
    ; AIE2PS-LABEL: name: test_v16acc64_unaligned
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64), align 16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from unknown-address + 8)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from unknown-address + 16, align 16)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD2]](p0) :: (load (s64) from unknown-address + 24)
    ; AIE2PS-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2PS-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2PS-NEXT: [[LOAD4:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD3]](p0) :: (load (s64) from unknown-address + 32, align 16)
    ; AIE2PS-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2PS-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2PS-NEXT: [[LOAD5:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD4]](p0) :: (load (s64) from unknown-address + 40)
    ; AIE2PS-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2PS-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2PS-NEXT: [[LOAD6:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD5]](p0) :: (load (s64) from unknown-address + 48, align 16)
    ; AIE2PS-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2PS-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2PS-NEXT: [[LOAD7:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD6]](p0) :: (load (s64) from unknown-address + 56)
    ; AIE2PS-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2PS-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2PS-NEXT: [[LOAD8:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD7]](p0) :: (load (s64) from unknown-address + 64, align 16)
    ; AIE2PS-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; AIE2PS-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; AIE2PS-NEXT: [[LOAD9:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD8]](p0) :: (load (s64) from unknown-address + 72)
    ; AIE2PS-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2PS-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; AIE2PS-NEXT: [[LOAD10:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD9]](p0) :: (load (s64) from unknown-address + 80, align 16)
    ; AIE2PS-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; AIE2PS-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; AIE2PS-NEXT: [[LOAD11:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD10]](p0) :: (load (s64) from unknown-address + 88)
    ; AIE2PS-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2PS-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; AIE2PS-NEXT: [[LOAD12:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD11]](p0) :: (load (s64) from unknown-address + 96, align 16)
    ; AIE2PS-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; AIE2PS-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; AIE2PS-NEXT: [[LOAD13:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD12]](p0) :: (load (s64) from unknown-address + 104)
    ; AIE2PS-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; AIE2PS-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; AIE2PS-NEXT: [[LOAD14:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD13]](p0) :: (load (s64) from unknown-address + 112, align 16)
    ; AIE2PS-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; AIE2PS-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; AIE2PS-NEXT: [[LOAD15:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD14]](p0) :: (load (s64) from unknown-address + 120)
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s64)
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[LOAD8]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s64)
    ; AIE2PS-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI15]](<8 x s64>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<16 x s64>) = G_LOAD %1(p0) :: (load (<16 x s64>), align 16)
    PseudoRET implicit $lr, implicit %0

...

---
name:            test_v64acc32_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_v64acc32_unaligned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 20
    ; CHECK-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; CHECK-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; CHECK-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 28
    ; CHECK-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; CHECK-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; CHECK-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 36
    ; CHECK-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; CHECK-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; CHECK-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; CHECK-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 44
    ; CHECK-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; CHECK-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; CHECK-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; CHECK-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; CHECK-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; CHECK-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 52
    ; CHECK-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; CHECK-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; CHECK-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; CHECK-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; CHECK-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; CHECK-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 60
    ; CHECK-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; CHECK-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; CHECK-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; CHECK-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s32) from unknown-address + 64, align 16)
    ; CHECK-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 68
    ; CHECK-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; CHECK-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s32) from unknown-address + 68)
    ; CHECK-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; CHECK-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; CHECK-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s32) from unknown-address + 72, align 8)
    ; CHECK-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 76
    ; CHECK-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; CHECK-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s32) from unknown-address + 76)
    ; CHECK-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; CHECK-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; CHECK-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s32) from unknown-address + 80, align 16)
    ; CHECK-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 84
    ; CHECK-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; CHECK-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s32) from unknown-address + 84)
    ; CHECK-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; CHECK-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; CHECK-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s32) from unknown-address + 88, align 8)
    ; CHECK-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 92
    ; CHECK-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; CHECK-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s32) from unknown-address + 92)
    ; CHECK-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; CHECK-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s32) from unknown-address + 96, align 16)
    ; CHECK-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 100
    ; CHECK-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; CHECK-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s32) from unknown-address + 100)
    ; CHECK-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; CHECK-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; CHECK-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s32) from unknown-address + 104, align 8)
    ; CHECK-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 108
    ; CHECK-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; CHECK-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s32) from unknown-address + 108)
    ; CHECK-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; CHECK-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; CHECK-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s32) from unknown-address + 112, align 16)
    ; CHECK-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 116
    ; CHECK-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; CHECK-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s32) from unknown-address + 116)
    ; CHECK-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; CHECK-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; CHECK-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s32) from unknown-address + 120, align 8)
    ; CHECK-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 124
    ; CHECK-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; CHECK-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s32) from unknown-address + 124)
    ; CHECK-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; CHECK-NEXT: [[LOAD32:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD31]](p0) :: (load (s32) from unknown-address + 128, align 16)
    ; CHECK-NEXT: [[C32:%[0-9]+]]:_(s20) = G_CONSTANT i20 132
    ; CHECK-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C32]](s20)
    ; CHECK-NEXT: [[LOAD33:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD32]](p0) :: (load (s32) from unknown-address + 132)
    ; CHECK-NEXT: [[C33:%[0-9]+]]:_(s20) = G_CONSTANT i20 136
    ; CHECK-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C33]](s20)
    ; CHECK-NEXT: [[LOAD34:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD33]](p0) :: (load (s32) from unknown-address + 136, align 8)
    ; CHECK-NEXT: [[C34:%[0-9]+]]:_(s20) = G_CONSTANT i20 140
    ; CHECK-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C34]](s20)
    ; CHECK-NEXT: [[LOAD35:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD34]](p0) :: (load (s32) from unknown-address + 140)
    ; CHECK-NEXT: [[C35:%[0-9]+]]:_(s20) = G_CONSTANT i20 144
    ; CHECK-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C35]](s20)
    ; CHECK-NEXT: [[LOAD36:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD35]](p0) :: (load (s32) from unknown-address + 144, align 16)
    ; CHECK-NEXT: [[C36:%[0-9]+]]:_(s20) = G_CONSTANT i20 148
    ; CHECK-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C36]](s20)
    ; CHECK-NEXT: [[LOAD37:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD36]](p0) :: (load (s32) from unknown-address + 148)
    ; CHECK-NEXT: [[C37:%[0-9]+]]:_(s20) = G_CONSTANT i20 152
    ; CHECK-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C37]](s20)
    ; CHECK-NEXT: [[LOAD38:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD37]](p0) :: (load (s32) from unknown-address + 152, align 8)
    ; CHECK-NEXT: [[C38:%[0-9]+]]:_(s20) = G_CONSTANT i20 156
    ; CHECK-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C38]](s20)
    ; CHECK-NEXT: [[LOAD39:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD38]](p0) :: (load (s32) from unknown-address + 156)
    ; CHECK-NEXT: [[C39:%[0-9]+]]:_(s20) = G_CONSTANT i20 160
    ; CHECK-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C39]](s20)
    ; CHECK-NEXT: [[LOAD40:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD39]](p0) :: (load (s32) from unknown-address + 160, align 16)
    ; CHECK-NEXT: [[C40:%[0-9]+]]:_(s20) = G_CONSTANT i20 164
    ; CHECK-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C40]](s20)
    ; CHECK-NEXT: [[LOAD41:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD40]](p0) :: (load (s32) from unknown-address + 164)
    ; CHECK-NEXT: [[C41:%[0-9]+]]:_(s20) = G_CONSTANT i20 168
    ; CHECK-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C41]](s20)
    ; CHECK-NEXT: [[LOAD42:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD41]](p0) :: (load (s32) from unknown-address + 168, align 8)
    ; CHECK-NEXT: [[C42:%[0-9]+]]:_(s20) = G_CONSTANT i20 172
    ; CHECK-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C42]](s20)
    ; CHECK-NEXT: [[LOAD43:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD42]](p0) :: (load (s32) from unknown-address + 172)
    ; CHECK-NEXT: [[C43:%[0-9]+]]:_(s20) = G_CONSTANT i20 176
    ; CHECK-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C43]](s20)
    ; CHECK-NEXT: [[LOAD44:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD43]](p0) :: (load (s32) from unknown-address + 176, align 16)
    ; CHECK-NEXT: [[C44:%[0-9]+]]:_(s20) = G_CONSTANT i20 180
    ; CHECK-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C44]](s20)
    ; CHECK-NEXT: [[LOAD45:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD44]](p0) :: (load (s32) from unknown-address + 180)
    ; CHECK-NEXT: [[C45:%[0-9]+]]:_(s20) = G_CONSTANT i20 184
    ; CHECK-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C45]](s20)
    ; CHECK-NEXT: [[LOAD46:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD45]](p0) :: (load (s32) from unknown-address + 184, align 8)
    ; CHECK-NEXT: [[C46:%[0-9]+]]:_(s20) = G_CONSTANT i20 188
    ; CHECK-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C46]](s20)
    ; CHECK-NEXT: [[LOAD47:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD46]](p0) :: (load (s32) from unknown-address + 188)
    ; CHECK-NEXT: [[C47:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
    ; CHECK-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C47]](s20)
    ; CHECK-NEXT: [[LOAD48:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD47]](p0) :: (load (s32) from unknown-address + 192, align 16)
    ; CHECK-NEXT: [[C48:%[0-9]+]]:_(s20) = G_CONSTANT i20 196
    ; CHECK-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C48]](s20)
    ; CHECK-NEXT: [[LOAD49:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD48]](p0) :: (load (s32) from unknown-address + 196)
    ; CHECK-NEXT: [[C49:%[0-9]+]]:_(s20) = G_CONSTANT i20 200
    ; CHECK-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C49]](s20)
    ; CHECK-NEXT: [[LOAD50:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD49]](p0) :: (load (s32) from unknown-address + 200, align 8)
    ; CHECK-NEXT: [[C50:%[0-9]+]]:_(s20) = G_CONSTANT i20 204
    ; CHECK-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C50]](s20)
    ; CHECK-NEXT: [[LOAD51:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD50]](p0) :: (load (s32) from unknown-address + 204)
    ; CHECK-NEXT: [[C51:%[0-9]+]]:_(s20) = G_CONSTANT i20 208
    ; CHECK-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C51]](s20)
    ; CHECK-NEXT: [[LOAD52:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD51]](p0) :: (load (s32) from unknown-address + 208, align 16)
    ; CHECK-NEXT: [[C52:%[0-9]+]]:_(s20) = G_CONSTANT i20 212
    ; CHECK-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C52]](s20)
    ; CHECK-NEXT: [[LOAD53:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD52]](p0) :: (load (s32) from unknown-address + 212)
    ; CHECK-NEXT: [[C53:%[0-9]+]]:_(s20) = G_CONSTANT i20 216
    ; CHECK-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C53]](s20)
    ; CHECK-NEXT: [[LOAD54:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD53]](p0) :: (load (s32) from unknown-address + 216, align 8)
    ; CHECK-NEXT: [[C54:%[0-9]+]]:_(s20) = G_CONSTANT i20 220
    ; CHECK-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C54]](s20)
    ; CHECK-NEXT: [[LOAD55:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD54]](p0) :: (load (s32) from unknown-address + 220)
    ; CHECK-NEXT: [[C55:%[0-9]+]]:_(s20) = G_CONSTANT i20 224
    ; CHECK-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C55]](s20)
    ; CHECK-NEXT: [[LOAD56:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD55]](p0) :: (load (s32) from unknown-address + 224, align 16)
    ; CHECK-NEXT: [[C56:%[0-9]+]]:_(s20) = G_CONSTANT i20 228
    ; CHECK-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C56]](s20)
    ; CHECK-NEXT: [[LOAD57:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD56]](p0) :: (load (s32) from unknown-address + 228)
    ; CHECK-NEXT: [[C57:%[0-9]+]]:_(s20) = G_CONSTANT i20 232
    ; CHECK-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C57]](s20)
    ; CHECK-NEXT: [[LOAD58:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD57]](p0) :: (load (s32) from unknown-address + 232, align 8)
    ; CHECK-NEXT: [[C58:%[0-9]+]]:_(s20) = G_CONSTANT i20 236
    ; CHECK-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C58]](s20)
    ; CHECK-NEXT: [[LOAD59:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD58]](p0) :: (load (s32) from unknown-address + 236)
    ; CHECK-NEXT: [[C59:%[0-9]+]]:_(s20) = G_CONSTANT i20 240
    ; CHECK-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C59]](s20)
    ; CHECK-NEXT: [[LOAD60:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD59]](p0) :: (load (s32) from unknown-address + 240, align 16)
    ; CHECK-NEXT: [[C60:%[0-9]+]]:_(s20) = G_CONSTANT i20 244
    ; CHECK-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C60]](s20)
    ; CHECK-NEXT: [[LOAD61:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD60]](p0) :: (load (s32) from unknown-address + 244)
    ; CHECK-NEXT: [[C61:%[0-9]+]]:_(s20) = G_CONSTANT i20 248
    ; CHECK-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C61]](s20)
    ; CHECK-NEXT: [[LOAD62:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD61]](p0) :: (load (s32) from unknown-address + 248, align 8)
    ; CHECK-NEXT: [[C62:%[0-9]+]]:_(s20) = G_CONSTANT i20 252
    ; CHECK-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C62]](s20)
    ; CHECK-NEXT: [[LOAD63:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD62]](p0) :: (load (s32) from unknown-address + 252)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI7]], [[LOAD8]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[LOAD16]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI23]], [[LOAD24]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s32)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI32:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY2]], [[LOAD32]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI33:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI32]], [[LOAD33]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI34:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI33]], [[LOAD34]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI35:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI34]], [[LOAD35]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI36:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI35]], [[LOAD36]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI37:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI36]], [[LOAD37]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI38:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI37]], [[LOAD38]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI39:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI38]], [[LOAD39]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI40:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI39]], [[LOAD40]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI41:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI40]], [[LOAD41]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI42:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI41]], [[LOAD42]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI43:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI42]], [[LOAD43]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI44:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI43]], [[LOAD44]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI45:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI44]], [[LOAD45]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI46:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI45]], [[LOAD46]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI47:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI46]], [[LOAD47]](s32)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI48:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY3]], [[LOAD48]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI49:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI48]], [[LOAD49]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI50:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI49]], [[LOAD50]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI51:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI50]], [[LOAD51]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI52:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI51]], [[LOAD52]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI53:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI52]], [[LOAD53]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI54:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI53]], [[LOAD54]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI55:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI54]], [[LOAD55]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI56:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI55]], [[LOAD56]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI57:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI56]], [[LOAD57]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI58:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI57]], [[LOAD58]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI59:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI58]], [[LOAD59]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI60:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI59]], [[LOAD60]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI61:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI60]], [[LOAD61]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI62:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI61]], [[LOAD62]](s32)
    ; CHECK-NEXT: [[AIE_ADD_VECTOR_ELT_HI63:%[0-9]+]]:_(<16 x s32>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI62]], [[LOAD63]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI15]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI31]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI47]](<16 x s32>), [[AIE_ADD_VECTOR_ELT_HI63]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<32 x s32>), [[CONCAT_VECTORS1]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<64 x s32>)
    %1:_(p0) = COPY $p0
    %0:_(<64 x s32>) = G_LOAD %1(p0) :: (load (<64 x s32>), align 16)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_v32acc64_unaligned
body:             |
  bb.1.entry:
    liveins: $p0

    ; AIE2P-LABEL: name: test_v32acc64_unaligned
    ; AIE2P: liveins: $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2P-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32), align 16)
    ; AIE2P-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
    ; AIE2P-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from unknown-address + 4)
    ; AIE2P-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
    ; AIE2P-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2P-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2P-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD1]](p0) :: (load (s32) from unknown-address + 8, align 8)
    ; AIE2P-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD2]](p0) :: (load (s32) from unknown-address + 12)
    ; AIE2P-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD2]](s32), [[LOAD3]](s32)
    ; AIE2P-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2P-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2P-NEXT: [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD3]](p0) :: (load (s32) from unknown-address + 16, align 16)
    ; AIE2P-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD4]](p0) :: (load (s32) from unknown-address + 20)
    ; AIE2P-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD4]](s32), [[LOAD5]](s32)
    ; AIE2P-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2P-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2P-NEXT: [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD5]](p0) :: (load (s32) from unknown-address + 24, align 8)
    ; AIE2P-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD5]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD6]](p0) :: (load (s32) from unknown-address + 28)
    ; AIE2P-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD6]](s32), [[LOAD7]](s32)
    ; AIE2P-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2P-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2P-NEXT: [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD7]](p0) :: (load (s32) from unknown-address + 32, align 16)
    ; AIE2P-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD7]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD8]](p0) :: (load (s32) from unknown-address + 36)
    ; AIE2P-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD8]](s32), [[LOAD9]](s32)
    ; AIE2P-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2P-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2P-NEXT: [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD9]](p0) :: (load (s32) from unknown-address + 40, align 8)
    ; AIE2P-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD9]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD10]](p0) :: (load (s32) from unknown-address + 44)
    ; AIE2P-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD10]](s32), [[LOAD11]](s32)
    ; AIE2P-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2P-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2P-NEXT: [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD11]](p0) :: (load (s32) from unknown-address + 48, align 16)
    ; AIE2P-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD11]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD12]](p0) :: (load (s32) from unknown-address + 52)
    ; AIE2P-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD12]](s32), [[LOAD13]](s32)
    ; AIE2P-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2P-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2P-NEXT: [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD13]](p0) :: (load (s32) from unknown-address + 56, align 8)
    ; AIE2P-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD13]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD14]](p0) :: (load (s32) from unknown-address + 60)
    ; AIE2P-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD14]](s32), [[LOAD15]](s32)
    ; AIE2P-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2P-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; AIE2P-NEXT: [[LOAD16:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD15]](p0) :: (load (s32) from unknown-address + 64, align 16)
    ; AIE2P-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD15]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD17:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD16]](p0) :: (load (s32) from unknown-address + 68)
    ; AIE2P-NEXT: [[MV8:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD16]](s32), [[LOAD17]](s32)
    ; AIE2P-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; AIE2P-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; AIE2P-NEXT: [[LOAD18:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD17]](p0) :: (load (s32) from unknown-address + 72, align 8)
    ; AIE2P-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD17]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD19:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD18]](p0) :: (load (s32) from unknown-address + 76)
    ; AIE2P-NEXT: [[MV9:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD18]](s32), [[LOAD19]](s32)
    ; AIE2P-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2P-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; AIE2P-NEXT: [[LOAD20:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD19]](p0) :: (load (s32) from unknown-address + 80, align 16)
    ; AIE2P-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD19]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD21:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD20]](p0) :: (load (s32) from unknown-address + 84)
    ; AIE2P-NEXT: [[MV10:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD20]](s32), [[LOAD21]](s32)
    ; AIE2P-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; AIE2P-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; AIE2P-NEXT: [[LOAD22:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD21]](p0) :: (load (s32) from unknown-address + 88, align 8)
    ; AIE2P-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD21]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD23:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD22]](p0) :: (load (s32) from unknown-address + 92)
    ; AIE2P-NEXT: [[MV11:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD22]](s32), [[LOAD23]](s32)
    ; AIE2P-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2P-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; AIE2P-NEXT: [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD23]](p0) :: (load (s32) from unknown-address + 96, align 16)
    ; AIE2P-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD23]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD24]](p0) :: (load (s32) from unknown-address + 100)
    ; AIE2P-NEXT: [[MV12:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD24]](s32), [[LOAD25]](s32)
    ; AIE2P-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; AIE2P-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; AIE2P-NEXT: [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD25]](p0) :: (load (s32) from unknown-address + 104, align 8)
    ; AIE2P-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD25]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD26]](p0) :: (load (s32) from unknown-address + 108)
    ; AIE2P-NEXT: [[MV13:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD26]](s32), [[LOAD27]](s32)
    ; AIE2P-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; AIE2P-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; AIE2P-NEXT: [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD27]](p0) :: (load (s32) from unknown-address + 112, align 16)
    ; AIE2P-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD27]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD28]](p0) :: (load (s32) from unknown-address + 116)
    ; AIE2P-NEXT: [[MV14:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD28]](s32), [[LOAD29]](s32)
    ; AIE2P-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; AIE2P-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; AIE2P-NEXT: [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD29]](p0) :: (load (s32) from unknown-address + 120, align 8)
    ; AIE2P-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD29]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD30]](p0) :: (load (s32) from unknown-address + 124)
    ; AIE2P-NEXT: [[MV15:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD30]](s32), [[LOAD31]](s32)
    ; AIE2P-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; AIE2P-NEXT: [[PTR_ADD31:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; AIE2P-NEXT: [[LOAD32:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD31]](p0) :: (load (s32) from unknown-address + 128, align 16)
    ; AIE2P-NEXT: [[PTR_ADD32:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD31]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD33:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD32]](p0) :: (load (s32) from unknown-address + 132)
    ; AIE2P-NEXT: [[MV16:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD32]](s32), [[LOAD33]](s32)
    ; AIE2P-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 136
    ; AIE2P-NEXT: [[PTR_ADD33:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; AIE2P-NEXT: [[LOAD34:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD33]](p0) :: (load (s32) from unknown-address + 136, align 8)
    ; AIE2P-NEXT: [[PTR_ADD34:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD33]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD35:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD34]](p0) :: (load (s32) from unknown-address + 140)
    ; AIE2P-NEXT: [[MV17:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD34]](s32), [[LOAD35]](s32)
    ; AIE2P-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 144
    ; AIE2P-NEXT: [[PTR_ADD35:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; AIE2P-NEXT: [[LOAD36:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD35]](p0) :: (load (s32) from unknown-address + 144, align 16)
    ; AIE2P-NEXT: [[PTR_ADD36:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD35]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD37:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD36]](p0) :: (load (s32) from unknown-address + 148)
    ; AIE2P-NEXT: [[MV18:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD36]](s32), [[LOAD37]](s32)
    ; AIE2P-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 152
    ; AIE2P-NEXT: [[PTR_ADD37:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; AIE2P-NEXT: [[LOAD38:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD37]](p0) :: (load (s32) from unknown-address + 152, align 8)
    ; AIE2P-NEXT: [[PTR_ADD38:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD37]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD39:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD38]](p0) :: (load (s32) from unknown-address + 156)
    ; AIE2P-NEXT: [[MV19:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD38]](s32), [[LOAD39]](s32)
    ; AIE2P-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 160
    ; AIE2P-NEXT: [[PTR_ADD39:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; AIE2P-NEXT: [[LOAD40:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD39]](p0) :: (load (s32) from unknown-address + 160, align 16)
    ; AIE2P-NEXT: [[PTR_ADD40:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD39]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD41:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD40]](p0) :: (load (s32) from unknown-address + 164)
    ; AIE2P-NEXT: [[MV20:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD40]](s32), [[LOAD41]](s32)
    ; AIE2P-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 168
    ; AIE2P-NEXT: [[PTR_ADD41:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; AIE2P-NEXT: [[LOAD42:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD41]](p0) :: (load (s32) from unknown-address + 168, align 8)
    ; AIE2P-NEXT: [[PTR_ADD42:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD41]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD43:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD42]](p0) :: (load (s32) from unknown-address + 172)
    ; AIE2P-NEXT: [[MV21:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD42]](s32), [[LOAD43]](s32)
    ; AIE2P-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 176
    ; AIE2P-NEXT: [[PTR_ADD43:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; AIE2P-NEXT: [[LOAD44:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD43]](p0) :: (load (s32) from unknown-address + 176, align 16)
    ; AIE2P-NEXT: [[PTR_ADD44:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD43]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD45:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD44]](p0) :: (load (s32) from unknown-address + 180)
    ; AIE2P-NEXT: [[MV22:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD44]](s32), [[LOAD45]](s32)
    ; AIE2P-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 184
    ; AIE2P-NEXT: [[PTR_ADD45:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; AIE2P-NEXT: [[LOAD46:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD45]](p0) :: (load (s32) from unknown-address + 184, align 8)
    ; AIE2P-NEXT: [[PTR_ADD46:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD45]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD47:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD46]](p0) :: (load (s32) from unknown-address + 188)
    ; AIE2P-NEXT: [[MV23:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD46]](s32), [[LOAD47]](s32)
    ; AIE2P-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
    ; AIE2P-NEXT: [[PTR_ADD47:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; AIE2P-NEXT: [[LOAD48:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD47]](p0) :: (load (s32) from unknown-address + 192, align 16)
    ; AIE2P-NEXT: [[PTR_ADD48:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD47]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD49:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD48]](p0) :: (load (s32) from unknown-address + 196)
    ; AIE2P-NEXT: [[MV24:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD48]](s32), [[LOAD49]](s32)
    ; AIE2P-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 200
    ; AIE2P-NEXT: [[PTR_ADD49:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; AIE2P-NEXT: [[LOAD50:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD49]](p0) :: (load (s32) from unknown-address + 200, align 8)
    ; AIE2P-NEXT: [[PTR_ADD50:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD49]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD51:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD50]](p0) :: (load (s32) from unknown-address + 204)
    ; AIE2P-NEXT: [[MV25:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD50]](s32), [[LOAD51]](s32)
    ; AIE2P-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 208
    ; AIE2P-NEXT: [[PTR_ADD51:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; AIE2P-NEXT: [[LOAD52:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD51]](p0) :: (load (s32) from unknown-address + 208, align 16)
    ; AIE2P-NEXT: [[PTR_ADD52:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD51]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD53:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD52]](p0) :: (load (s32) from unknown-address + 212)
    ; AIE2P-NEXT: [[MV26:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD52]](s32), [[LOAD53]](s32)
    ; AIE2P-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 216
    ; AIE2P-NEXT: [[PTR_ADD53:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; AIE2P-NEXT: [[LOAD54:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD53]](p0) :: (load (s32) from unknown-address + 216, align 8)
    ; AIE2P-NEXT: [[PTR_ADD54:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD53]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD55:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD54]](p0) :: (load (s32) from unknown-address + 220)
    ; AIE2P-NEXT: [[MV27:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD54]](s32), [[LOAD55]](s32)
    ; AIE2P-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 224
    ; AIE2P-NEXT: [[PTR_ADD55:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; AIE2P-NEXT: [[LOAD56:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD55]](p0) :: (load (s32) from unknown-address + 224, align 16)
    ; AIE2P-NEXT: [[PTR_ADD56:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD55]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD57:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD56]](p0) :: (load (s32) from unknown-address + 228)
    ; AIE2P-NEXT: [[MV28:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD56]](s32), [[LOAD57]](s32)
    ; AIE2P-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 232
    ; AIE2P-NEXT: [[PTR_ADD57:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; AIE2P-NEXT: [[LOAD58:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD57]](p0) :: (load (s32) from unknown-address + 232, align 8)
    ; AIE2P-NEXT: [[PTR_ADD58:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD57]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD59:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD58]](p0) :: (load (s32) from unknown-address + 236)
    ; AIE2P-NEXT: [[MV29:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD58]](s32), [[LOAD59]](s32)
    ; AIE2P-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 240
    ; AIE2P-NEXT: [[PTR_ADD59:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; AIE2P-NEXT: [[LOAD60:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD59]](p0) :: (load (s32) from unknown-address + 240, align 16)
    ; AIE2P-NEXT: [[PTR_ADD60:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD59]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD61:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD60]](p0) :: (load (s32) from unknown-address + 244)
    ; AIE2P-NEXT: [[MV30:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD60]](s32), [[LOAD61]](s32)
    ; AIE2P-NEXT: [[C31:%[0-9]+]]:_(s20) = G_CONSTANT i20 248
    ; AIE2P-NEXT: [[PTR_ADD61:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C31]](s20)
    ; AIE2P-NEXT: [[LOAD62:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD61]](p0) :: (load (s32) from unknown-address + 248, align 8)
    ; AIE2P-NEXT: [[PTR_ADD62:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD61]], [[C]](s20)
    ; AIE2P-NEXT: [[LOAD63:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD62]](p0) :: (load (s32) from unknown-address + 252)
    ; AIE2P-NEXT: [[MV31:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD62]](s32), [[LOAD63]](s32)
    ; AIE2P-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[MV]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[MV1]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[MV2]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[MV3]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[MV4]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[MV5]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[MV6]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[MV7]](s64)
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[MV8]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[MV9]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[MV10]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[MV11]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[MV12]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[MV13]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[MV14]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[MV15]](s64)
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY2]], [[MV16]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[MV17]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[MV18]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[MV19]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[MV20]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[MV21]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[MV22]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[MV23]](s64)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY3]], [[MV24]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[MV25]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[MV26]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[MV27]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[MV28]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[MV29]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[MV30]](s64)
    ; AIE2P-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[MV31]](s64)
    ; AIE2P-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI15]](<8 x s64>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI23]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI31]](<8 x s64>)
    ; AIE2P-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s64>), [[CONCAT_VECTORS1]](<16 x s64>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<32 x s64>)
    ;
    ; AIE2PS-LABEL: name: test_v32acc64_unaligned
    ; AIE2PS: liveins: $p0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; AIE2PS-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64), align 16)
    ; AIE2PS-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; AIE2PS-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; AIE2PS-NEXT: [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from unknown-address + 8)
    ; AIE2PS-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; AIE2PS-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; AIE2PS-NEXT: [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from unknown-address + 16, align 16)
    ; AIE2PS-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 24
    ; AIE2PS-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; AIE2PS-NEXT: [[LOAD3:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD2]](p0) :: (load (s64) from unknown-address + 24)
    ; AIE2PS-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; AIE2PS-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; AIE2PS-NEXT: [[LOAD4:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD3]](p0) :: (load (s64) from unknown-address + 32, align 16)
    ; AIE2PS-NEXT: [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 40
    ; AIE2PS-NEXT: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C4]](s20)
    ; AIE2PS-NEXT: [[LOAD5:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD4]](p0) :: (load (s64) from unknown-address + 40)
    ; AIE2PS-NEXT: [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 48
    ; AIE2PS-NEXT: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C5]](s20)
    ; AIE2PS-NEXT: [[LOAD6:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD5]](p0) :: (load (s64) from unknown-address + 48, align 16)
    ; AIE2PS-NEXT: [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 56
    ; AIE2PS-NEXT: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s20)
    ; AIE2PS-NEXT: [[LOAD7:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD6]](p0) :: (load (s64) from unknown-address + 56)
    ; AIE2PS-NEXT: [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; AIE2PS-NEXT: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C7]](s20)
    ; AIE2PS-NEXT: [[LOAD8:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD7]](p0) :: (load (s64) from unknown-address + 64, align 16)
    ; AIE2PS-NEXT: [[C8:%[0-9]+]]:_(s20) = G_CONSTANT i20 72
    ; AIE2PS-NEXT: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C8]](s20)
    ; AIE2PS-NEXT: [[LOAD9:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD8]](p0) :: (load (s64) from unknown-address + 72)
    ; AIE2PS-NEXT: [[C9:%[0-9]+]]:_(s20) = G_CONSTANT i20 80
    ; AIE2PS-NEXT: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C9]](s20)
    ; AIE2PS-NEXT: [[LOAD10:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD9]](p0) :: (load (s64) from unknown-address + 80, align 16)
    ; AIE2PS-NEXT: [[C10:%[0-9]+]]:_(s20) = G_CONSTANT i20 88
    ; AIE2PS-NEXT: [[PTR_ADD10:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C10]](s20)
    ; AIE2PS-NEXT: [[LOAD11:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD10]](p0) :: (load (s64) from unknown-address + 88)
    ; AIE2PS-NEXT: [[C11:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; AIE2PS-NEXT: [[PTR_ADD11:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C11]](s20)
    ; AIE2PS-NEXT: [[LOAD12:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD11]](p0) :: (load (s64) from unknown-address + 96, align 16)
    ; AIE2PS-NEXT: [[C12:%[0-9]+]]:_(s20) = G_CONSTANT i20 104
    ; AIE2PS-NEXT: [[PTR_ADD12:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C12]](s20)
    ; AIE2PS-NEXT: [[LOAD13:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD12]](p0) :: (load (s64) from unknown-address + 104)
    ; AIE2PS-NEXT: [[C13:%[0-9]+]]:_(s20) = G_CONSTANT i20 112
    ; AIE2PS-NEXT: [[PTR_ADD13:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s20)
    ; AIE2PS-NEXT: [[LOAD14:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD13]](p0) :: (load (s64) from unknown-address + 112, align 16)
    ; AIE2PS-NEXT: [[C14:%[0-9]+]]:_(s20) = G_CONSTANT i20 120
    ; AIE2PS-NEXT: [[PTR_ADD14:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C14]](s20)
    ; AIE2PS-NEXT: [[LOAD15:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD14]](p0) :: (load (s64) from unknown-address + 120)
    ; AIE2PS-NEXT: [[C15:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; AIE2PS-NEXT: [[PTR_ADD15:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C15]](s20)
    ; AIE2PS-NEXT: [[LOAD16:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD15]](p0) :: (load (s64) from unknown-address + 128, align 16)
    ; AIE2PS-NEXT: [[C16:%[0-9]+]]:_(s20) = G_CONSTANT i20 136
    ; AIE2PS-NEXT: [[PTR_ADD16:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C16]](s20)
    ; AIE2PS-NEXT: [[LOAD17:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD16]](p0) :: (load (s64) from unknown-address + 136)
    ; AIE2PS-NEXT: [[C17:%[0-9]+]]:_(s20) = G_CONSTANT i20 144
    ; AIE2PS-NEXT: [[PTR_ADD17:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C17]](s20)
    ; AIE2PS-NEXT: [[LOAD18:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD17]](p0) :: (load (s64) from unknown-address + 144, align 16)
    ; AIE2PS-NEXT: [[C18:%[0-9]+]]:_(s20) = G_CONSTANT i20 152
    ; AIE2PS-NEXT: [[PTR_ADD18:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C18]](s20)
    ; AIE2PS-NEXT: [[LOAD19:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD18]](p0) :: (load (s64) from unknown-address + 152)
    ; AIE2PS-NEXT: [[C19:%[0-9]+]]:_(s20) = G_CONSTANT i20 160
    ; AIE2PS-NEXT: [[PTR_ADD19:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C19]](s20)
    ; AIE2PS-NEXT: [[LOAD20:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD19]](p0) :: (load (s64) from unknown-address + 160, align 16)
    ; AIE2PS-NEXT: [[C20:%[0-9]+]]:_(s20) = G_CONSTANT i20 168
    ; AIE2PS-NEXT: [[PTR_ADD20:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C20]](s20)
    ; AIE2PS-NEXT: [[LOAD21:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD20]](p0) :: (load (s64) from unknown-address + 168)
    ; AIE2PS-NEXT: [[C21:%[0-9]+]]:_(s20) = G_CONSTANT i20 176
    ; AIE2PS-NEXT: [[PTR_ADD21:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C21]](s20)
    ; AIE2PS-NEXT: [[LOAD22:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD21]](p0) :: (load (s64) from unknown-address + 176, align 16)
    ; AIE2PS-NEXT: [[C22:%[0-9]+]]:_(s20) = G_CONSTANT i20 184
    ; AIE2PS-NEXT: [[PTR_ADD22:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C22]](s20)
    ; AIE2PS-NEXT: [[LOAD23:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD22]](p0) :: (load (s64) from unknown-address + 184)
    ; AIE2PS-NEXT: [[C23:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
    ; AIE2PS-NEXT: [[PTR_ADD23:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C23]](s20)
    ; AIE2PS-NEXT: [[LOAD24:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD23]](p0) :: (load (s64) from unknown-address + 192, align 16)
    ; AIE2PS-NEXT: [[C24:%[0-9]+]]:_(s20) = G_CONSTANT i20 200
    ; AIE2PS-NEXT: [[PTR_ADD24:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C24]](s20)
    ; AIE2PS-NEXT: [[LOAD25:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD24]](p0) :: (load (s64) from unknown-address + 200)
    ; AIE2PS-NEXT: [[C25:%[0-9]+]]:_(s20) = G_CONSTANT i20 208
    ; AIE2PS-NEXT: [[PTR_ADD25:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C25]](s20)
    ; AIE2PS-NEXT: [[LOAD26:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD25]](p0) :: (load (s64) from unknown-address + 208, align 16)
    ; AIE2PS-NEXT: [[C26:%[0-9]+]]:_(s20) = G_CONSTANT i20 216
    ; AIE2PS-NEXT: [[PTR_ADD26:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C26]](s20)
    ; AIE2PS-NEXT: [[LOAD27:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD26]](p0) :: (load (s64) from unknown-address + 216)
    ; AIE2PS-NEXT: [[C27:%[0-9]+]]:_(s20) = G_CONSTANT i20 224
    ; AIE2PS-NEXT: [[PTR_ADD27:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C27]](s20)
    ; AIE2PS-NEXT: [[LOAD28:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD27]](p0) :: (load (s64) from unknown-address + 224, align 16)
    ; AIE2PS-NEXT: [[C28:%[0-9]+]]:_(s20) = G_CONSTANT i20 232
    ; AIE2PS-NEXT: [[PTR_ADD28:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C28]](s20)
    ; AIE2PS-NEXT: [[LOAD29:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD28]](p0) :: (load (s64) from unknown-address + 232)
    ; AIE2PS-NEXT: [[C29:%[0-9]+]]:_(s20) = G_CONSTANT i20 240
    ; AIE2PS-NEXT: [[PTR_ADD29:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C29]](s20)
    ; AIE2PS-NEXT: [[LOAD30:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD29]](p0) :: (load (s64) from unknown-address + 240, align 16)
    ; AIE2PS-NEXT: [[C30:%[0-9]+]]:_(s20) = G_CONSTANT i20 248
    ; AIE2PS-NEXT: [[PTR_ADD30:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C30]](s20)
    ; AIE2PS-NEXT: [[LOAD31:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD30]](p0) :: (load (s64) from unknown-address + 248)
    ; AIE2PS-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[DEF]], [[LOAD]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI1:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI]], [[LOAD1]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI2:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI1]], [[LOAD2]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI3:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI2]], [[LOAD3]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI4:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI3]], [[LOAD4]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI5:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI4]], [[LOAD5]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI6:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI5]], [[LOAD6]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI7:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI6]], [[LOAD7]](s64)
    ; AIE2PS-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI8:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY1]], [[LOAD8]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI9:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI8]], [[LOAD9]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI10:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI9]], [[LOAD10]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI11:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI10]], [[LOAD11]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI12:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI11]], [[LOAD12]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI13:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI12]], [[LOAD13]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI14:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI13]], [[LOAD14]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI15:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI14]], [[LOAD15]](s64)
    ; AIE2PS-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI16:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY2]], [[LOAD16]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI17:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI16]], [[LOAD17]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI18:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI17]], [[LOAD18]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI19:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI18]], [[LOAD19]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI20:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI19]], [[LOAD20]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI21:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI20]], [[LOAD21]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI22:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI21]], [[LOAD22]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI23:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI22]], [[LOAD23]](s64)
    ; AIE2PS-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s64>) = COPY [[DEF]](<8 x s64>)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI24:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[COPY3]], [[LOAD24]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI25:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI24]], [[LOAD25]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI26:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI25]], [[LOAD26]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI27:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI26]], [[LOAD27]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI28:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI27]], [[LOAD28]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI29:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI28]], [[LOAD29]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI30:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI29]], [[LOAD30]](s64)
    ; AIE2PS-NEXT: [[AIE_ADD_VECTOR_ELT_HI31:%[0-9]+]]:_(<8 x s64>) = G_AIE_ADD_VECTOR_ELT_HI [[AIE_ADD_VECTOR_ELT_HI30]], [[LOAD31]](s64)
    ; AIE2PS-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI7]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI15]](<8 x s64>)
    ; AIE2PS-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_ADD_VECTOR_ELT_HI23]](<8 x s64>), [[AIE_ADD_VECTOR_ELT_HI31]](<8 x s64>)
    ; AIE2PS-NEXT: [[CONCAT_VECTORS2:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[CONCAT_VECTORS]](<16 x s64>), [[CONCAT_VECTORS1]](<16 x s64>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS2]](<32 x s64>)
    %1:_(p0) = COPY $p0
    %0:_(<32 x s64>) = G_LOAD %1(p0) :: (load (<32 x s64>), align 16)
    PseudoRET implicit $lr, implicit %0

...
