# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_acc_512
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_acc_512
    ; CHECK: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s64>) = COPY $bmll1
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s32>) = G_BITCAST [[COPY1]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<8 x s64>), implicit [[BITCAST1]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $bmll0
    %1:_(<8 x s64>) = COPY $bmll1
    %2:_(<8 x s64>) = G_BITCAST %0(<16 x s32>)
    %3:_(<16 x s32>) = G_BITCAST %1(<8 x s64>)
    PseudoRET implicit $lr, implicit %2, implicit %3
...
---
name:            test_acc_1024
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_acc_1024
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s64>) = COPY $cml1
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<32 x s32>) = G_BITCAST [[COPY1]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<16 x s64>), implicit [[BITCAST1]](<32 x s32>)
    %0:_(<32 x s32>) = COPY $cml0
    %1:_(<16 x s64>) = COPY $cml1
    %2:_(<16 x s64>) = G_BITCAST %0(<32 x s32>)
    %3:_(<32 x s32>) = G_BITCAST %1(<16 x s64>)
    PseudoRET implicit $lr, implicit %2, implicit %3
...
---
name:            test_acc_2048
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_acc_2048
    ; CHECK: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s64>) = COPY $dm1
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<32 x s64>) = G_BITCAST [[COPY]](<64 x s32>)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<64 x s32>) = G_BITCAST [[COPY1]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<32 x s64>), implicit [[BITCAST1]](<64 x s32>)
    %0:_(<64 x s32>) = COPY $dm0
    %1:_(<32 x s64>) = COPY $dm1
    %2:_(<32 x s64>) = G_BITCAST %0(<64 x s32>)
    %3:_(<64 x s32>) = G_BITCAST %1(<32 x s64>)
    PseudoRET implicit $lr, implicit %2, implicit %3
...
