# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=LEGALIZER %s
# RUN: llc -mtriple aie2p -start-before=legalizer -stop-after=aie-postlegalizer-generic-combiner %s \
# RUN:          -verify-machineinstrs -o - | FileCheck --check-prefix=AFTER-POST-COMBINER %s
# RUN: llc -mtriple aie2ps -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck --check-prefix=LEGALIZER %s

# We have a run line for between legalizer and postcombiner because we are using some legalization
# artifacts that should be removed by combiners (bitcasts, truncs and zexts).

---
name: test_icmp_V16S32
body: |
  bb.0:
    liveins: $x0, $x1
    ; LEGALIZER-LABEL: name: test_icmp_V16S32
    ; LEGALIZER: liveins: $x0, $x1
    ; LEGALIZER-NEXT: {{  $}}
    ; LEGALIZER-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; LEGALIZER-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; LEGALIZER-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:_(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<16 x s32>), [[COPY1]]
    ; LEGALIZER-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[AIE_VECTOR_ICMP]](<32 x s1>)
    ; LEGALIZER-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[BITCAST]], 16
    ; LEGALIZER-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[ASSERT_ZEXT]](s32)
    ; LEGALIZER-NEXT: [[BITCAST1:%[0-9]+]]:_(<16 x s1>) = G_BITCAST [[TRUNC]](s16)
    ; LEGALIZER-NEXT: [[BITCAST2:%[0-9]+]]:_(s16) = G_BITCAST [[BITCAST1]](<16 x s1>)
    ; LEGALIZER-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[BITCAST2]](s16)
    ; LEGALIZER-NEXT: [[BITCAST3:%[0-9]+]]:_(<32 x s1>) = G_BITCAST [[ZEXT]](s32)
    ; LEGALIZER-NEXT: $r0 = COPY [[BITCAST3]](<32 x s1>)
    ;
    ; AFTER-POST-COMBINER-LABEL: name: test_icmp_V16S32
    ; AFTER-POST-COMBINER: liveins: $x0, $x1
    ; AFTER-POST-COMBINER-NEXT: {{  $}}
    ; AFTER-POST-COMBINER-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; AFTER-POST-COMBINER-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; AFTER-POST-COMBINER-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:_(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<16 x s32>), [[COPY1]]
    ; AFTER-POST-COMBINER-NEXT: $r0 = COPY [[AIE_VECTOR_ICMP]](<32 x s1>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s1>) = G_ICMP intpred(ne), %0, %1
    %3:_(s16) = G_BITCAST %2
    %4:_(s32) = G_ZEXT %3
    %5:_(<32 x s1>) = G_BITCAST %4
    $r0 = COPY %5
...

---
name: test_icmp_V32S16
body: |
  bb.0:
    liveins: $x0, $x1
    ; LEGALIZER-LABEL: name: test_icmp_V32S16
    ; LEGALIZER: liveins: $x0, $x1
    ; LEGALIZER-NEXT: {{  $}}
    ; LEGALIZER-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; LEGALIZER-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x1
    ; LEGALIZER-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:_(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<32 x s16>), [[COPY1]]
    ; LEGALIZER-NEXT: [[COPY2:%[0-9]+]]:_(<32 x s1>) = COPY [[AIE_VECTOR_ICMP]](<32 x s1>)
    ; LEGALIZER-NEXT: $r0 = COPY [[COPY2]](<32 x s1>)
    ;
    ; AFTER-POST-COMBINER-LABEL: name: test_icmp_V32S16
    ; AFTER-POST-COMBINER: liveins: $x0, $x1
    ; AFTER-POST-COMBINER-NEXT: {{  $}}
    ; AFTER-POST-COMBINER-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; AFTER-POST-COMBINER-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x1
    ; AFTER-POST-COMBINER-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:_(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<32 x s16>), [[COPY1]]
    ; AFTER-POST-COMBINER-NEXT: $r0 = COPY [[AIE_VECTOR_ICMP]](<32 x s1>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x1
    %2:_(<32 x s1>) = G_ICMP intpred(ne), %0, %1
    $r0 = COPY %2
...

---
name: test_icmp_V64S8
body: |
  bb.0:
    liveins: $x0, $x1
    ; LEGALIZER-LABEL: name: test_icmp_V64S8
    ; LEGALIZER: liveins: $x0, $x1
    ; LEGALIZER-NEXT: {{  $}}
    ; LEGALIZER-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; LEGALIZER-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
    ; LEGALIZER-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:_(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<64 x s8>), [[COPY1]]
    ; LEGALIZER-NEXT: [[COPY2:%[0-9]+]]:_(<64 x s1>) = COPY [[AIE_VECTOR_ICMP]](<64 x s1>)
    ; LEGALIZER-NEXT: $l0 = COPY [[COPY2]](<64 x s1>)
    ;
    ; AFTER-POST-COMBINER-LABEL: name: test_icmp_V64S8
    ; AFTER-POST-COMBINER: liveins: $x0, $x1
    ; AFTER-POST-COMBINER-NEXT: {{  $}}
    ; AFTER-POST-COMBINER-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; AFTER-POST-COMBINER-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
    ; AFTER-POST-COMBINER-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:_(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<64 x s8>), [[COPY1]]
    ; AFTER-POST-COMBINER-NEXT: $l0 = COPY [[AIE_VECTOR_ICMP]](<64 x s1>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(<64 x s8>) = COPY $x1
    %2:_(<64 x s1>) = G_ICMP intpred(ne), %0, %1
    $l0 = COPY %2
...



