# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: s256
body: |
  bb.0:
    ; CHECK-LABEL: name: s256
    ; CHECK: [[COPY:%[0-9]+]]:_(s256) = COPY $wl0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s256) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[FREEZE]](s256)
    %0:_(s256) = COPY $wl0
    %1:_(s256) = G_FREEZE %0
    PseudoRET implicit $lr, implicit %1
...

---
name: s512
body: |
  bb.0:
    ; CHECK-LABEL: name: s512
    ; CHECK: [[COPY:%[0-9]+]]:_(s512) = COPY $x0
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s512) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[FREEZE]](s512)
    %0:_(s512) = COPY $x0
    %1:_(s512) = G_FREEZE %0
    PseudoRET implicit $lr, implicit %1
...

---
name: s1024
body: |
  bb.0:
    ; CHECK-LABEL: name: s1024
    ; CHECK: [[COPY:%[0-9]+]]:_(s1024) = COPY $y2
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s1024) = G_FREEZE [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[FREEZE]](s1024)
    %0:_(s1024) = COPY $y2
    %1:_(s1024) = G_FREEZE %0
    PseudoRET implicit $lr, implicit %1
...
