# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s



---
name:            512bit_s64_val
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0, $r0
    ; CHECK-LABEL: name: 512bit_s64_val
    ; CHECK: liveins: $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<8 x s64>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s64), [[C]](s32)
    ; CHECK-NEXT: $x4 = COPY [[AIE_INSERT_VECTOR_ELT]](<8 x s64>)
    %0:_(<8 x s64>) = COPY $x0
    %1:_(s64) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 5
    %7:_(<8 x s64>) = G_INSERT_VECTOR_ELT %0(<8 x s64>), %1(s64), %2(s32)
    $x4 = COPY %7(<8 x s64>)
...

---
name:            1024bit_s64_val
legalized:       false
body:             |
  bb.0.entry:
    liveins: $y0, $r0
    ; CHECK-LABEL: name: 1024bit_s64_val
    ; CHECK: liveins: $y0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:_(<16 x s64>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s64), [[C]](s32)
    ; CHECK-NEXT: $y4 = COPY [[AIE_INSERT_VECTOR_ELT]](<16 x s64>)
    %0:_(<16 x s64>) = COPY $y0
    %1:_(s64) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 5
    %7:_(<16 x s64>) = G_INSERT_VECTOR_ELT %0(<16 x s64>), %1(s64), %2(s32)
    $y4 = COPY %7(<16 x s64>)
...

