# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=aie-post-select-optimize,dead-mi-elimination %s -verify-machineinstrs -o - | FileCheck %s

# This file tests various post-select combines for aie2p

---
name:            REG_SEQ_of_subreg_copies
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $ex0
    ; CHECK-LABEL: name: REG_SEQ_of_subreg_copies
    ; CHECK: liveins: $ex0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec576 = COPY $ex0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec576 = COPY [[COPY]]
    ; CHECK-NEXT: $ex0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $ex0
    %0:vec576 = COPY $ex0
    %1:vec512 = COPY %0.sub_bfp16_x
    %2:expvec64 = COPY %0.sub_bfp16_e
    %3:vec576 = REG_SEQUENCE %1, %subreg.sub_bfp16_x, %2, %subreg.sub_bfp16_e
    $ex0 = COPY %3
    PseudoRET implicit $lr, implicit $ex0
...

---
name:            dont_REG_SEQ_of_different_sources
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $ex0, $ex1
    ; CHECK-LABEL: name: dont_REG_SEQ_of_different_sources
    ; CHECK: liveins: $ex0, $ex1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec576 = COPY $ex0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec576 = COPY $ex1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:expvec64 = COPY [[COPY1]].sub_bfp16_e
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec576 = REG_SEQUENCE [[COPY2]], %subreg.sub_bfp16_x, [[COPY3]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: $ex0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $ex0
    %0:vec576 = COPY $ex0
    %1:vec576 = COPY $ex1
    %2:vec512 = COPY %0.sub_bfp16_x
    %3:expvec64 = COPY %1.sub_bfp16_e
    %4:vec576 = REG_SEQUENCE %2, %subreg.sub_bfp16_x, %3, %subreg.sub_bfp16_e
    $ex0 = COPY %4
    PseudoRET implicit $lr, implicit $ex0
...
---
name:            dont_REG_SEQ_of_non_subreg
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $ex0
    ; CHECK-LABEL: name: dont_REG_SEQ_of_non_subreg
    ; CHECK: liveins: $ex0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec576 = COPY $ex0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY [[COPY]].sub_bfp16_x
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:expvec64 = COPY $e0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec576 = REG_SEQUENCE [[COPY1]], %subreg.sub_bfp16_x, [[COPY2]], %subreg.sub_bfp16_e
    ; CHECK-NEXT: $ex0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $ex0
    %0:vec576 = COPY $ex0
    %2:vec512 = COPY %0.sub_bfp16_x
    %3:expvec64 = COPY $e0
    %4:vec576 = REG_SEQUENCE %2, %subreg.sub_bfp16_x, %3, %subreg.sub_bfp16_e
    $ex0 = COPY %4
    PseudoRET implicit $lr, implicit $ex0
...
---
name:            do_REG_SEQ_of_subregs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $x0
    ; CHECK-LABEL: name: do_REG_SEQ_of_subregs
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vec512 = COPY $x0
    %2:vec256 = COPY %0.sub_256_lo
    %3:vec256 = COPY %0.sub_256_hi
    %4:vec512 = REG_SEQUENCE %2, %subreg.sub_256_lo, %3, %subreg.sub_256_hi
    $x0 = COPY %4
    PseudoRET implicit $lr, implicit $x0
...
---
name:            dont_REG_SEQ_of_swapped_index
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $x0
    ; CHECK-LABEL: name: dont_REG_SEQ_of_swapped_index
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY2]], %subreg.sub_256_lo, [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vec512 = COPY $x0
    %2:vec256 = COPY %0.sub_256_lo
    %3:vec256 = COPY %0.sub_256_hi
    %4:vec512 = REG_SEQUENCE %3, %subreg.sub_256_lo, %2, %subreg.sub_256_hi
    $x0 = COPY %4
    PseudoRET implicit $lr, implicit $x0
...
---
name:            dont_REG_SEQ_of_equal_index
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $x0
    ; CHECK-LABEL: name: dont_REG_SEQ_of_equal_index
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY1]], %subreg.sub_256_lo, [[COPY2]], %subreg.sub_256_hi
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vec512 = COPY $x0
    %2:vec256 = COPY %0.sub_256_lo
    %3:vec256 = COPY %0.sub_256_lo
    %4:vec512 = REG_SEQUENCE %2, %subreg.sub_256_lo, %3, %subreg.sub_256_hi
    $x0 = COPY %4
    PseudoRET implicit $lr, implicit $x0
...
---
name:            dont_REG_SEQ_of_partial_definition
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $cml0
    ; CHECK-LABEL: name: dont_REG_SEQ_of_partial_definition
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY [[COPY]]
    ; CHECK-NEXT: $dm0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:acc1024 = COPY $cml0
    %1:acc512 = COPY %0.sub_512_acc_lo
    %2:acc2048 = REG_SEQUENCE %1, %subreg.sub_512_acc_lo
    $dm0 = COPY %2
    PseudoRET implicit $lr, implicit $dm0
...
