# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p \
# RUN: -run-pass=dead-mi-elimination,aie-post-select-optimize,dead-mi-elimination \
# RUN: --aie-simplify-crsr-edges=true -verify-machineinstrs %s -o - | FileCheck %s

# Test 1 - Remove identity copies of crfpmask (mCRm Reg class aka Control Register).
# Transform -
# %0 = COPY $crfpmask               |   |    |   %0 = COPY $crfpmask
# $crfpmask = COPY %0               |   |    |   ---------------------------
# %1 = opcode implicit $crfpmask    |   |    |   %1 = opcode implicit $crfpmask
# $crfpmask = COPY %0               |   |    |   ---------------------------
# %2 = opcode implicit $crfpmask    |   |    |   %2 = opcode implicit $crfpmask
# %10 = COPY $crfpmask              |-> to ->|   ---------------------------
# $crfpmask = COPY %10              |   |    |   ---------------------------
# %3 = opcode implicit $crfpmask    |   |    |   %3 = opcode implicit $crfpmask
# $crfpmask = COPY %0               |   |    |   ---------------------------
# %4 = opcode implicit $crfpmask    |   |    |   %4 = opcode implicit $crfpmask
---
name:            crfpmask_multiple
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $crfpmask, $dm3
    ; CHECK-LABEL: name: crfpmask_multiple
    ; CHECK: liveins: $crfpmask, $dm3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:edm = COPY $dm3
    ; CHECK-NEXT: [[MOVXM:%[0-9]+]]:er = MOVXM 28
    ; CHECK-NEXT: [[VNEG_f:%[0-9]+]]:edm = VNEG_f [[COPY]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VNEG_f1:%[0-9]+]]:edm = VNEG_f [[VNEG_f]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VNEG_f2:%[0-9]+]]:edm = VNEG_f [[VNEG_f1]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VNEG_f3:%[0-9]+]]:edm = VNEG_f [[VNEG_f2]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VNEG_f4:%[0-9]+]]:edm = VNEG_f [[VNEG_f3]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VNEG_f5:%[0-9]+]]:edm = VNEG_f [[VNEG_f4]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    %1:edm = COPY $dm3
    %2:er = MOVXM 28
    %3:ercr = COPY $crfpmask
    $crfpmask = COPY %3:ercr
    %4:edm = VNEG_f %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %5:edm = VNEG_f %4:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    %6:ercr = COPY $crfpmask
    $crfpmask = COPY %6:ercr
    %7:edm = VNEG_f %5:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %8:edm = VNEG_f %7:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %9:edm = VNEG_f %8:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %10:edm = VNEG_f %9:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
...

# Test 2 - Test 1 variation with a live clobber.
---
name:            crfpmask_multiple_liveclobber
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $crfpmask, $dm3
    ; CHECK-LABEL: name: crfpmask_multiple_liveclobber
    ; CHECK: liveins: $crfpmask, $dm3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:edm = COPY $dm3
    ; CHECK-NEXT: [[MOVXM:%[0-9]+]]:er = MOVXM 28
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ercr = COPY $crfpmask
    ; CHECK-NEXT: [[VNEG_f:%[0-9]+]]:edm = VNEG_f [[COPY]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[MOVXM1:%[0-9]+]]:er = MOVXM 1
    ; CHECK-NEXT: $crfpmask = COPY [[MOVXM1]]
    ; CHECK-NEXT: [[VNEG_f1:%[0-9]+]]:edm = VNEG_f [[VNEG_f]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $crfpmask = COPY [[COPY1]]
    ; CHECK-NEXT: [[VNEG_f2:%[0-9]+]]:edm = VNEG_f [[VNEG_f1]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VNEG_f3:%[0-9]+]]:edm = VNEG_f [[VNEG_f2]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: [[VNEG_f4:%[0-9]+]]:edm = VNEG_f [[VNEG_f3]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    %1:edm = COPY $dm3
    %2:er = MOVXM 28
    %3:ercr = COPY $crfpmask
    $crfpmask = COPY %3:ercr
    %4:edm = VNEG_f %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %5:edm = VNEG_f %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %6:edm = VNEG_f %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    %7:er = MOVXM 1
    $crfpmask = COPY %7:er
    $crfpmask = COPY %7:er
    $crfpmask = COPY %7:er
    %14:edm = VNEG_f %6:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %8:edm = VNEG_f  %14:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %9:edm = VNEG_f %8:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %10:edm = VNEG_f %9:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
...

# Test 3 - Test 2 variation with two basic blocks.
---
name:            crfpmask_multiple_bb_liveclobber
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: crfpmask_multiple_bb_liveclobber
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $crfpmask, $dm3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:edm = COPY $dm3
  ; CHECK-NEXT:   [[MOVXM:%[0-9]+]]:er = MOVXM 28
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ercr = COPY $crfpmask
  ; CHECK-NEXT:   [[VNEG_f:%[0-9]+]]:edm = VNEG_f [[COPY]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f1:%[0-9]+]]:edm = VNEG_f [[VNEG_f]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[MOVXM1:%[0-9]+]]:er = MOVXM 1
  ; CHECK-NEXT:   $crfpmask = COPY [[MOVXM1]]
  ; CHECK-NEXT:   [[VNEG_f2:%[0-9]+]]:edm = VNEG_f [[VNEG_f1]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   $crfpmask = COPY [[COPY1]]
  ; CHECK-NEXT:   [[VNEG_f3:%[0-9]+]]:edm = VNEG_f [[VNEG_f2]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f4:%[0-9]+]]:edm = VNEG_f [[VNEG_f3]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   $crfpmask = COPY [[COPY1]]
  ; CHECK-NEXT:   [[VNEG_f5:%[0-9]+]]:edm = VNEG_f [[VNEG_f4]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f6:%[0-9]+]]:edm = VNEG_f [[VNEG_f5]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f7:%[0-9]+]]:edm = VNEG_f [[VNEG_f6]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    liveins: $crfpmask, $dm3
    %1:edm = COPY $dm3
    %2:er = MOVXM 28
    %3:ercr = COPY $crfpmask
    $crfpmask = COPY %3:ercr
    %4:edm = VNEG_f %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %5:edm = VNEG_f %4:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    %6:er = MOVXM 1
    $crfpmask = COPY %6:er
    %14:edm = VNEG_f %5:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %7:edm = VNEG_f %14:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %8:edm = VNEG_f %7:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    PseudoJ_jump_imm %bb.1

  bb.1:

    $crfpmask = COPY %3:ercr
    %9:edm = VNEG_f %8:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %10:edm = VNEG_f %9:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %11:edm = VNEG_f %10:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
...

# Test 4 - Test 3 variation but the basic blocks are not in dominating order.
---
name:            crfpmask_multiple_bb_liveclobber_non_dominating_first
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: crfpmask_multiple_bb_liveclobber_non_dominating_first
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $crfpmask, $dm3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:edm = COPY $dm3
  ; CHECK-NEXT:   [[MOVXM:%[0-9]+]]:er = MOVXM 28
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ercr = COPY $crfpmask
  ; CHECK-NEXT:   [[VNEG_f:%[0-9]+]]:edm = VNEG_f [[COPY]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f1:%[0-9]+]]:edm = VNEG_f [[VNEG_f]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[MOVXM1:%[0-9]+]]:er = MOVXM 1
  ; CHECK-NEXT:   $crfpmask = COPY [[MOVXM1]]
  ; CHECK-NEXT:   [[VNEG_f2:%[0-9]+]]:edm = VNEG_f [[VNEG_f1]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   $crfpmask = COPY [[COPY1]]
  ; CHECK-NEXT:   [[VNEG_f3:%[0-9]+]]:edm = VNEG_f [[VNEG_f2]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f4:%[0-9]+]]:edm = VNEG_f [[VNEG_f3]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $crfpmask = COPY [[COPY1]]
  ; CHECK-NEXT:   [[VNEG_f5:%[0-9]+]]:edm = VNEG_f %10, [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f6:%[0-9]+]]:edm = VNEG_f [[VNEG_f5]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   $crfpmask = COPY %12
  ; CHECK-NEXT:   [[VNEG_f7:%[0-9]+]]:edm = VNEG_f [[VNEG_f6]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ercr = COPY $crfpmask
  ; CHECK-NEXT:   [[VNEG_f8:%[0-9]+]]:edm = VNEG_f [[VNEG_f4]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   [[VNEG_f9:%[0-9]+]]:edm = VNEG_f [[VNEG_f8]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   $crfpmask = COPY [[COPY2]]
  ; CHECK-NEXT:   [[VNEG_f10:%[0-9]+]]:edm = VNEG_f [[VNEG_f7]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   $crfpmask = COPY [[COPY1]]
  ; CHECK-NEXT:   [[VNEG_f11:%[0-9]+]]:edm = VNEG_f [[VNEG_f10]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   $crfpmask = COPY [[COPY2]]
  ; CHECK-NEXT:   [[VNEG_f12:%[0-9]+]]:edm = VNEG_f [[VNEG_f11]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
  bb.0.entry:
    successors: %bb.2(0x80000000); %bb.2(100.00%)
    liveins: $crfpmask, $dm3
    %1:edm = COPY $dm3
    %2:er = MOVXM 28
    %3:ercr = COPY $crfpmask
    $crfpmask = COPY %3:ercr
    %4:edm = VNEG_f  %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %5:edm = VNEG_f  %4:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    %6:er = MOVXM 1
    $crfpmask = COPY %6:er
    %7:edm = VNEG_f  %5:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %8:edm = VNEG_f  %7:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %9:edm = VNEG_f  %8:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    PseudoJ_jump_imm %bb.2

  bb.1:
    successors: %bb.3(0x80000000); %bb.3(100.00%)

    $crfpmask = COPY %3:ercr
    %13:edm = VNEG_f %12:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %14:edm = VNEG_f  %13:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %10:ercr
    %15:edm = VNEG_f  %14:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    PseudoJ_jump_imm %bb.3

  bb.2:
    successors: %bb.1(0x80000000); %bb.1(100.00%)

    %10:ercr = COPY $crfpmask
    $crfpmask = COPY %10:ercr
    %11:edm = VNEG_f  %9:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %10:ercr
    %12:edm = VNEG_f  %11:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    PseudoJ_jump_imm %bb.1

  bb.3:

    $crfpmask = COPY %10:ercr
    %16:edm = VNEG_f  %15:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %3:ercr
    %17:edm = VNEG_f  %16:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %10:ercr
    %18:edm = VNEG_f  %17:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
...

# Test 5 - Deadcode elimination.
# %0 = COPY $r0                    |   |    | %0 = COPY $r0
# $1 = COPY $r1                    |   |    | $1 = COPY $r1
# $upssign0 = COPY %0             |   |    | $upssign0 = COPY %0
# %2 = opcode implicit $upssign0  |   |    | %2 = opcode implicit $upssign0
# $upssign0 = MOV 0               |-> to ->| -------------------------------
# $upssign0 = COPY %0             |   |    | -------------------------------
# %3 = opcode implicit $upssign0  |   |    | %3 = opcode implicit $upssign0
# $upssign0 = MOV 0               |   |    | -------------------------------
# $upssign0 = COPY %1             |   |    | $upssign0 = COPY %1
---
name:            crupsign0_redundant_reassignments
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:

    liveins: $r0, $crsat, $p0, $d0, $s3
    ; CHECK-LABEL: name: crupsign0_redundant_reassignments
    ; CHECK: liveins: $r0, $crsat, $p0, $d0, $s3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVXM 0
    %0:er = MOVXM 0
    %1:er = COPY $r0
    %2:ercr = COPY $crsat
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %3:mss = COPY %0:er
    %4:ep = COPY $p0
    %5:ed = COPY $d0
    %6:mbmm, %7:ep, %8:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %9:mbmm, %10:ep, %11:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %12:mbmm, %13:ep, %14:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
...


# Test 6 - Test 5 variation with two basic blocks.
---
name:            upssign0_redundant_reassignments_multiple_bb
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: upssign0_redundant_reassignments_multiple_bb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r1, $crsat, $p0, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $crsat, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_9:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_10:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_11:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_12:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_13:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_14:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]

  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    liveins: $r1, $crsat, $p0, $d0, $s3
    %1:er = COPY $r1
    %2:ercr = COPY $crsat
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %4:ep = COPY $p0
    %6:mbmm, %7:ep, %8:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %9:mbmm, %10:ep, %11:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %12:mbmm, %13:ep, %14:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    PseudoJ_jump_imm %bb.1

  bb.1:
    liveins: $crsat, $d0, $s3
    %15:ercr = COPY $crsat
    $crsat = MOVXM 0
    $crsat = COPY %15:ercr
    $upssign0 = COPY %1:er
    %16:mbmm, %17:ep, %18:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %15:ercr
    %19:mbmm, %20:ep, %21:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = COPY %1:er
...

# Test 7 - Test 6 variation with multiple basic blocks - conditional - and a self loop.
#
# There is a self loop on 1.
#     0 -> 1 -> 2 -> 4
#     |              ^
#     |              |
#     + -> 3 --------+
#
---
name:            upssign0_reassignments_multiple_bb_conditional_with_loop
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: upssign0_reassignments_multiple_bb_conditional_with_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $r1, $crsat, $p0, $r0, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ercr = COPY $crsat
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   PseudoJNZ [[COPY3]], %bb.3
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $crsat, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_9:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_10:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_11:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoJNZ [[COPY3]], %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT:   liveins: $crsat, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_12:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_13:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_14:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_15:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_16:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_17:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $crsat = MOVXM 2
  ; CHECK-NEXT:   $upssign0 = MOVXM 1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT:   liveins: $crsat, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $crsat = COPY [[COPY1]]
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_18:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_19:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_20:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_21:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_22:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_23:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   liveins: $crsat, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $crsat = COPY [[COPY1]]
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_24:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_25:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_26:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_27:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_28:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_29:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY2]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.3(0x40000000), %bb.1(0x40000000); %bb.3(50.00%), %bb.1(50.00%)
    liveins: $r1, $crsat, $p0, $r0, $d0, $s3
    %1:er = COPY $r1
    %2:ercr = COPY $crsat
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %4:ep = COPY $p0
    %6:mbmm, %7:ep, %8:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %9:mbmm, %10:ep, %11:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    %12:er = COPY $r0
    PseudoJNZ %12:er, %bb.3
    PseudoJ_jump_imm %bb.1

  bb.1:
    successors: %bb.1(0x40000000), %bb.2(0x40000000); %bb.1(50.00%), %bb.2(50.00%)
    liveins: $crsat, $d0, $s3
    %13:ercr = COPY $crsat
    $crsat = COPY %13:ercr
    $upssign0 = COPY %1:er
    %14:mbmm, %15:ep, %16:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %13:ercr
    %17:mbmm, %18:ep, %19:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = COPY %1:er
    PseudoJNZ %12:er, %bb.1
    PseudoJ_jump_imm %bb.2

  bb.2:
    successors: %bb.4(0x80000000); %bb.4(100.00%)
    liveins: $crsat, $d0, $s3
    %20:ercr = COPY $crsat
    $crsat = MOVXM 0
    $crsat = COPY %20:ercr
    $upssign0 = COPY %1:er
    %21:mbmm, %22:ep, %23:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %20:ercr
    %24:mbmm, %25:ep, %26:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crsat = MOVXM 2
    $upssign0 = MOVXM 1
    PseudoJ_jump_imm %bb.4

  bb.3:
    successors: %bb.4(0x80000000); %bb.4(100.00%)
    liveins: $crsat, $d0, $s3
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %27:mbmm, %28:ep, %29:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %2:ercr
    %30:mbmm, %31:ep, %32:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 1
    PseudoJ_jump_imm %bb.4

  bb.4:
    liveins: $crsat, $d0, $s3
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %33:mbmm, %34:ep, %35:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $crsat = COPY %2:ercr
    $upssign0 = COPY %1:er
    %36:mbmm, %37:ep, %38:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %4:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    PseudoRET implicit $lr
...

# Test 8 - Test 6 variation #2 with multiple basic blocks, a feedback loop and a self loop.
#
# There is a self loop on 2.
#
#     0 -> 1 -> 2 -> 3 -> 4
#          ^         |
#          |_________v
#
---
name:            upssign0_reassignments_multiple_bb_conditional_with_loop_2
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: upssign0_reassignments_multiple_bb_conditional_with_loop_2
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r1, $p0, $crsat, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_9:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_10:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_11:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_12:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_13:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_14:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   PseudoJNZ [[COPY2]], %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT:   liveins: $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_15:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_16:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_17:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_18:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_19:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_20:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoJNZ [[COPY2]], %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   liveins: $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_21:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_22:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_23:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_24:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_25:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_26:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    liveins: $r1, $p0, $crsat, $d0, $s3
    %1:er = COPY $r1
    $upssign0 = COPY %1:er
    %3:ep = COPY $p0
    %4:mbmm, %5:ep, %6:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    PseudoJ_jump_imm %bb.1

  bb.1:
    successors: %bb.2(0x80000000); %bb.2(100.00%)
    liveins: $d0, $s3
    $upssign0 = COPY %1:er
    %7:mbmm, %8:ep, %9:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    %10:mbmm, %11:ep, %12:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = COPY %1:er
    PseudoJ_jump_imm %bb.2

  bb.2:
    successors: %bb.2(0x40000000), %bb.3(0x40000000); %bb.2(50.00%), %bb.3(50.00%)
    liveins: $r0, $d0, $s3
    $upssign0 = COPY %1:er
    %13:mbmm, %14:ep, %15:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    %16:mbmm, %17:ep, %18:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = COPY %1:er
    %19:er = COPY $r0
    PseudoJNZ %19:er, %bb.2
    PseudoJ_jump_imm %bb.3

  bb.3:
    successors: %bb.1(0x40000000), %bb.4(0x40000000); %bb.1(50.00%), %bb.4(50.00%)
    liveins: $d0, $s3
    $upssign0 = COPY %1:er
    %20:mbmm, %21:ep, %22:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    %23:mbmm, %24:ep, %25:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = COPY %1:er
    PseudoJNZ %19:er, %bb.1
    PseudoJ_jump_imm %bb.4

  bb.4:
    liveins: $d0, $s3
    $upssign0 = COPY %1:er
    %26:mbmm, %27:ep, %28:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    $upssign0 = COPY %1:er
    %29:mbmm, %30:ep, %31:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    PseudoRET implicit $lr
...

# Test 9 - Last Visited Def in %bb.2 doesn't come from an immediate predecessor.
---
name:            upssign0_dead_mi_elim
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: upssign0_dead_mi_elim
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r1, $p0, $crsat, $d0, $s3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $r2, $s3, $d0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r2
  ; CHECK-NEXT:   $upssign0 = COPY [[COPY2]]
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   $upssign0 = MOVXM 0
  ; CHECK-NEXT:   [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY1]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  bb.0.entry:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    liveins: $r1, $p0, $crsat, $d0, $s3
    %0:er = MOVXM 0
    %1:er = COPY $r1
    $upssign0 = COPY %1:er
    %2:mss = COPY %0:er
    %3:ep = COPY $p0
    %4:mbmm, %5:ep, %6:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0

    $upssign0 = MOVXM 0

    PseudoJ_jump_imm %bb.1

  bb.1:
    successors: %bb.2(0x80000000); %bb.2(100.00%)

    %7:er = MOVXM 23
    PseudoJ_jump_imm %bb.2

  bb.2:
    liveins: $r2, $s3, $d0
    %8:er = COPY $r2
    $upssign0 = COPY %8:er
    %9:mbmm, %10:ep, %11:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $upssign0 = MOVXM 0
    %12:mbmm, %13:ep, %14:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %3:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
...

# Test 10
# %10 holds a copy of $crfpmask, but it is invalidated. Make sure uses
# of %10 after the invalidation aren't simplified using $crfpmask.
---
name:            invalidate_copy
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $bmll2, $r0
    ; CHECK-LABEL: name: invalidate_copy
    ; CHECK: liveins: $bmll2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:edm = COPY $bmll2
    ; CHECK-NEXT: [[MOVXM:%[0-9]+]]:er = MOVXM 28
    ; CHECK-NEXT: $crfpmask = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ercr = COPY $crfpmask
    ; CHECK-NEXT: $crfpmask = MOVXM 0
    ; CHECK-NEXT: [[VNEG_f:%[0-9]+]]:edm = VNEG_f [[COPY]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $crfpmask = COPY [[COPY1]]
    ; CHECK-NEXT: [[VNEG_f1:%[0-9]+]]:edm = VNEG_f [[VNEG_f]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    %1:edm = COPY $bmll2
    %2:er = MOVXM 28
    %3:er = COPY $r0
    $crfpmask = COPY $r0
    %10:ercr = COPY $crfpmask
    $crfpmask = MOVXM 0
    %4:edm = VNEG_f  %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %10
    %5:edm = VNEG_f  %4:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
...

# Test 11
# $crfpmask is saved and restored twice around VNEG_f instructions
# Make sure we simplify this to only one vreg for saving and restoring.
---
name:            save_restore_twice
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
  liveins: $bmll2, $r0
    ; CHECK-LABEL: name: save_restore_twice
    ; CHECK: liveins: $bmll2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:edm = COPY $bmll2
    ; CHECK-NEXT: [[MOVXM:%[0-9]+]]:er = MOVXM 28
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ercr = COPY $crfpmask
    ; CHECK-NEXT: $crfpmask = MOVXM 0
    ; CHECK-NEXT: [[VNEG_f:%[0-9]+]]:edm = VNEG_f [[COPY]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $crfpmask = MOVXM 1
    ; CHECK-NEXT: [[VNEG_f1:%[0-9]+]]:edm = VNEG_f [[VNEG_f]], [[MOVXM]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $crfpmask = COPY [[COPY1]]
    %1:edm = COPY $bmll2
    %2:er = MOVXM 28
    %10:ercr = COPY $crfpmask
    $crfpmask = MOVXM 0
    %4:edm = VNEG_f  %1:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %10
    %11:ercr = COPY $crfpmask
    $crfpmask = MOVXM 1
    %5:edm = VNEG_f  %4:edm, %2:er, implicit-def $srfpflags, implicit $crfpmask
    $crfpmask = COPY %11
...



# Test 12 - Remove identity copies of crFPNlfMask (mCRFP Reg  Class aka Control Register Floating Point).
# Transform -
# %0 = COPY $crfpnlfmask               |   |    |   %0 = COPY $crfpnlfmask
# $crfpnlfmask = COPY %0               |   |    |   ---------------------------
# %1 = opcode implicit $crfpnlfmask    |   |    |   %1 = opcode implicit $crfpnlfmask
# $crfpnlfmask = COPY %0               |   |    |   ---------------------------
# %2 = opcode implicit $crfpnlfmask    |   |    |   %2 = opcode implicit $crfpnlfmask
# %10 = COPY $crsat              |-> to ->|   ---------------------------
# $crfpnlfmask = COPY %10              |   |    |   ---------------------------
# %3 = opcode implicit $crfpnlfmask    |   |    |   %3 = opcode implicit $crfpnlfmask
# $crfpnlfmask = COPY %0               |   |    |   ---------------------------
# %4 = opcode implicit $crfpnlfmask    |   |    |   %4 = opcode implicit $crfpnlfmask
---
name:            crFPNlfMask_multiple
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $s3, $r5, $r0
    ; CHECK-LABEL: name: crFPNlfMask_multiple
    ; CHECK: liveins: $s3, $r5, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[INVSQRT_mOptConvDel_mRx:%[0-9]+]]:er = INVSQRT_mOptConvDel_mRx $s3, $r5, implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    ; CHECK-NEXT: [[INVSQRT_mOptConvDel_mRx1:%[0-9]+]]:er = INVSQRT_mOptConvDel_mRx $s3, [[INVSQRT_mOptConvDel_mRx]], implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    ; CHECK-NEXT: [[INVSQRT_mOptConvDel_mRx2:%[0-9]+]]:er = INVSQRT_mOptConvDel_mRx $s3, [[INVSQRT_mOptConvDel_mRx1]], implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    ; CHECK-NEXT: [[INVSQRT_mOptConvDel_mRx3:%[0-9]+]]:er = INVSQRT_mOptConvDel_mRx $s3, [[INVSQRT_mOptConvDel_mRx2]], implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    ; CHECK-NEXT: [[INVSQRT_mOptConvDel_mRx4:%[0-9]+]]:er = INVSQRT_mOptConvDel_mRx $s3, [[INVSQRT_mOptConvDel_mRx3]], implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    ; CHECK-NEXT: [[INVSQRT_mOptConvDel_mRx5:%[0-9]+]]:er = INVSQRT_mOptConvDel_mRx $s3, [[INVSQRT_mOptConvDel_mRx4]], implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    %3:ercr = COPY $crfpnlfmask
    $crfpnlfmask = COPY %3:ercr
    %4:er = INVSQRT_mOptConvDel_mRx $s3, $r5, implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    $crfpnlfmask = COPY %3:ercr
    %5:er = INVSQRT_mOptConvDel_mRx $s3, %4:er, implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    %6:ercr = COPY $crfpnlfmask
    $crfpnlfmask = COPY %6:ercr
    %7:er = INVSQRT_mOptConvDel_mRx $s3, %5:er, implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    $crfpnlfmask = COPY %3:ercr
    %8:er = INVSQRT_mOptConvDel_mRx $s3, %7:er, implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    $crfpnlfmask = COPY %3:ercr
    %9:er = INVSQRT_mOptConvDel_mRx $s3, %8:er, implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
    $crfpnlfmask = COPY %3:ercr
    %10:er = INVSQRT_mOptConvDel_mRx $s3, %9:er, implicit-def $srfpcnvfl2fx, implicit-def $srfpnlf, implicit $crfpcnvfl2fxmask, implicit $crfpnlfmask
...

# Test 13 - Remove identity copies of srups_of (mSRm Reg class aka Status Register).
# Transform -
# %0 = COPY $srUPS_of               |   |    |   %0 = COPY $srUPS_of
# $srUPS_of = COPY %0               |   |    |   ---------------------------
# %1 = opcode implicit $srUPS_of    |   |    |   %1 = opcode implicit $srUPS_of
# $srUPS_of = COPY %0               |   |    |   ---------------------------
# %2 = opcode implicit $srUPS_of    |   |    |   %2 = opcode implicit $srUPS_of
# %10 = COPY $crsat              |-> to ->|   ---------------------------
# $srUPS_of = COPY %10              |   |    |   ---------------------------
# %3 = opcode implicit $srUPS_of    |   |    |   %3 = opcode implicit $srUPS_of
# $srUPS_of = COPY %0               |   |    |   ---------------------------
# %4 = opcode implicit $srUPS_of    |   |    |   %4 = opcode implicit $srUPS_of
---
name:            srups_of_multiple
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $s3, $r5, $r0, $p0, $d0
    ; CHECK-LABEL: name: srups_of_multiple
    ; CHECK: liveins: $s3, $r5, $r0, $p0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_9:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_10:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_11:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_12:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_13:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_14:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_15:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_16:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_17:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %0:ep = COPY $p0
    %1:ercr = COPY $srups_of
    $srups_of = COPY %1:ercr
    %2:mbmm, %3:ep, %4:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $srups_of = COPY %1:ercr
    %5:mbmm, %6:ep, %7:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %8:ercr = COPY $srups_of
    $srups_of = COPY %8:ercr
    %9:mbmm, %10:ep, %11:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $srups_of = COPY %1:ercr
    %12:mbmm, %13:ep, %14:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $srups_of = COPY %1:ercr
    %15:mbmm, %16:ep, %17:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $srups_of = COPY %1:ercr
    %18:mbmm, %19:ep, %20:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
...

# Test 14 - Remove immediate copies that are duplicated.
# Transform -
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   $crupsmode = MOV_scalar_imm11_pseudo 1
# %1 = opcode implicit $crupsmode         |   |    |   %1 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   ---------------------------
# %2 = opcode implicit $crupsmode         |   |    |   %2 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   ---------------------------
# %3 = opcode implicit $crupsmode         |   |    |   %3 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 0  |   |    |   $crupsmode = MOV_scalar_imm11_pseudo 0
# %4 = opcode implicit $crupsmode         |   |    |   %4 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   $crupsmode = MOV_scalar_imm11_pseudo 1
# %5 = opcode implicit $crupsmode         |   |    |   %5 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   ---------------------------
# %6 = opcode implicit $crupsmode         |   |    |   %6 = opcode implicit $crupsmode

---
name:            crupsmode_of_multiple_imm
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $s3, $r5, $r0, $p0, $d0
    ; CHECK-LABEL: name: crupsmode_of_multiple_imm
    ; CHECK: liveins: $s3, $r5, $r0, $p0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_9:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_10:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_11:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_12:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_13:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_14:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_15:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_16:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_17:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %0:ep = COPY $p0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %2:mbmm, %3:ep, %4:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %5:mbmm, %6:ep, %7:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %9:mbmm, %10:ep, %11:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 0
    %12:mbmm, %13:ep, %14:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %15:mbmm, %16:ep, %17:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %18:mbmm, %19:ep, %20:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
...

# Test 15 - Remove immediate copies and normal copies that are duplicated.
# Transform -
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   $crupsmode = MOV_scalar_imm11_pseudo 1
# %1 = opcode implicit $crupsmode         |   |    |   %1 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   ---------------------------
# %2 = opcode implicit $crupsmode         |   |    |   %2 = opcode implicit $crupsmode
# $crupsmode = COPY %1                    |   |    |   $crupsmode = COPY %1 
# %3 = opcode implicit $crupsmode         |   |    |   %3 = opcode implicit $crupsmode
# $crupsmode = COPY %1                    |   |    |   ---------------------------
# %4 = opcode implicit $crupsmode         |   |    |   %4 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   $crupsmode = MOV_scalar_imm11_pseudo 1
# %5 = opcode implicit $crupsmode         |   |    |   %5 = opcode implicit $crupsmode
# $crupsmode = MOV_scalar_imm11_pseudo 1  |   |    |   ---------------------------
# %6 = opcode implicit $crupsmode         |   |    |   %6 = opcode implicit $crupsmode

---
name:            crupsmode_of_multiple_imm_multiple_copies
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r2, $s3, $r5, $r0, $p0, $d0
    ; CHECK-LABEL: name: crupsmode_of_multiple_imm_multiple_copies
    ; CHECK: liveins: $r2, $s3, $r5, $r0, $p0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_3:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_4:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_5:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $crupsmode = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_6:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_7:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_8:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_9:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_10:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_11:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $crupsmode = MOV_scalar_imm11_pseudo 1
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_12:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_13:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_14:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_15:%[0-9]+]]:mbmm, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_16:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_17:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, [[COPY]], $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %0:ep = COPY $p0
    %1:er = COPY $r2
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %2:mbmm, %3:ep, %4:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %5:mbmm, %6:ep, %7:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = COPY %1
    %9:mbmm, %10:ep, %11:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = COPY %1
    %12:mbmm, %13:ep, %14:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %15:mbmm, %16:ep, %17:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $crupsmode = MOV_scalar_imm11_pseudo 1
    %18:mbmm, %19:ep, %20:edc =  VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s3, %0:ep, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
...


