# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s

---
name:            extract_v4i64
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; CHECK-LABEL: name: extract_v4i64
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s64>) = G_AIE_UNPAD_VECTOR [[COPY]](<8 x s64>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[AIE_UNPAD_VECTOR]](<4 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %2:_(<8 x s64>) = COPY $bmll0
    %1:_(<4 x s64>) = G_AIE_UNPAD_VECTOR %2(<8 x s64>)
    %4:_(s32) = G_CONSTANT i32 3
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<4 x s64>), %4(s32)
    %5:_(s32), %6:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %5(s32)
    $r1 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v4i64_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r2

    ; CHECK-LABEL: name: extract_v4i64_dyn
    ; CHECK: liveins: $bmll0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s64>) = G_AIE_UNPAD_VECTOR [[COPY]](<8 x s64>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[AIE_UNPAD_VECTOR]](<4 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %3:_(<8 x s64>) = COPY $bmll0
    %1:_(<4 x s64>) = G_AIE_UNPAD_VECTOR %3(<8 x s64>)
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<4 x s64>), %2(s32)
    %5:_(s32), %6:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %5(s32)
    $r1 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v8i64
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; CHECK-LABEL: name: extract_v8i64
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<8 x s64>) = COPY $bmll0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v8i64_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r2

    ; CHECK-LABEL: name: extract_v8i64_dyn
    ; CHECK: liveins: $bmll0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<8 x s64>) = COPY $bmll0
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v16i64
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0

    ; CHECK-LABEL: name: extract_v16i64
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<16 x s64>) = COPY $cml0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<16 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v16i64_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r2

    ; CHECK-LABEL: name: extract_v16i64_dyn
    ; CHECK: liveins: $cml0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<16 x s64>) = COPY $cml0
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<16 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v64i32
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: extract_v64i32
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<64 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v64i32_dyn
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r1

    ; CHECK-LABEL: name: extract_v64i32_dyn
    ; CHECK: liveins: $dm0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<64 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(s32) = COPY $r1
    %0:_(s32) = G_EXTRACT_VECTOR_ELT %1(<64 x s32>), %2(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...

---
name:            extract_v32i64
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: extract_v32i64
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<32 x s64>) = COPY $dm0
    %2:_(s32) = G_CONSTANT i32 7
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<32 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            extract_v32i64_dyn
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r2

    ; CHECK-LABEL: name: extract_v32i64_dyn
    ; CHECK: liveins: $dm0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %1:_(<32 x s64>) = COPY $dm0
    %2:_(s32) = COPY $r2
    %0:_(s64) = G_EXTRACT_VECTOR_ELT %1(<32 x s64>), %2(s32)
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1

...

---
name:            test_s256_2xs256
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0, $r0
    ; CHECK-LABEL: name: test_s256_2xs256
    ; CHECK: liveins: $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s256>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s256) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s256>), [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[EVEC]](s256)
    %0:_(<2 x s256>) = COPY $x0
    %1:_(s32) = COPY $r0
    %3:_(s256) = G_EXTRACT_VECTOR_ELT %0(<2 x s256>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s512_2xs512
legalized:       false
body:             |
  bb.0.entry:
    liveins: $cml0
    ; CHECK-LABEL: name: test_s512_2xs512
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s512>) = COPY $cml0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s512) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s512>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[EVEC]](s512)
    %0:_(<2 x s512>) = COPY $cml0
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s512) = G_EXTRACT_VECTOR_ELT %0(<2 x s512>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s1024_2xs1024
legalized:       false
body:             |
  bb.0.entry:
    liveins: $dm0, $r0
    ; CHECK-LABEL: name: test_s1024_2xs1024
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s1024>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s1024) = G_EXTRACT_VECTOR_ELT [[COPY]](<2 x s1024>), [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[EVEC]](s1024)
    %0:_(<2 x s1024>) = COPY $dm0
    %1:_(s32) = COPY $r0
    %3:_(s1024) = G_EXTRACT_VECTOR_ELT %0(<2 x s1024>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s256_4xs256
legalized:       false
body:             |
  bb.0.entry:
    liveins: $x0, $r0
    ; CHECK-LABEL: name: test_s256_4xs256
    ; CHECK: liveins: $x0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s256>) = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s256) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s256>), [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[EVEC]](s256)
    %0:_(<4 x s256>) = COPY $y2
    %1:_(s32) = COPY $r0
    %3:_(s256) = G_EXTRACT_VECTOR_ELT %0(<4 x s256>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_s512_4xs512
legalized:       false
body:             |
  bb.0.entry:
    liveins: $dm0, $r0
    ; CHECK-LABEL: name: test_s512_4xs512
    ; CHECK: liveins: $dm0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s512>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s512) = G_EXTRACT_VECTOR_ELT [[COPY]](<4 x s512>), [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[EVEC]](s512)
    %0:_(<4 x s512>) = COPY $dm0
    %1:_(s32) = COPY $r0
    %3:_(s512) = G_EXTRACT_VECTOR_ELT %0(<4 x s512>), %1(s32)
    PseudoRET implicit $lr, implicit %3
...
