# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s


---
name:            test_512_32bit_idx1
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_512_32bit_idx1
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<16 x s32>) = G_BUILD_VECTOR %2:_(s32), %2:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %4:_(<16 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %5:_(<16 x s32>) = G_SHUFFLE_VECTOR %3(<16 x s32>), %4(<16 x s32>), shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    $x0 = COPY %5:_(<16 x s32>)
...

---
name:            test_512_32bit_idx2
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_512_32bit_idx2
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<16 x s32>) = G_BUILD_VECTOR %2:_(s32), %2:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %4:_(<16 x s32>) = G_BUILD_VECTOR %2:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %5:_(<16 x s32>) = G_SHUFFLE_VECTOR %3(<16 x s32>), %4(<16 x s32>), shufflemask(16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16)
    $x0 = COPY %5:_(<16 x s32>)
...

# Invalid Vector for broadcast.
# Not a splat or one-diff splat vector
---
name:            test_512_32bit_invalid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_512_32bit_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_BUILD_VECTOR [[COPY1]](s32), [[COPY1]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[BUILD_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[UV]](s32)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[UV1]](s32), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[IVEC]](<16 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<16 x s32>) = G_BUILD_VECTOR %2:_(s32), %2:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %4:_(<16 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %5:_(<16 x s32>) = G_SHUFFLE_VECTOR %3(<16 x s32>), %4(<16 x s32>), shufflemask(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    $x0 = COPY %5:_(<16 x s32>)
...

---
name:            test_512_64bit
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_512_64bit
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[C]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    %1:_(s64) = G_CONSTANT i64 0
    %2:_(s64) = G_CONSTANT i64 1
    %3:_(<8 x s64>) = G_BUILD_VECTOR %2:_(s64), %2:_(s64), %2:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %2:_(s64)
    %4:_(<8 x s64>) = G_BUILD_VECTOR %1:_(s64), %1:_(s64), %2:_(s64), %1:_(s64), %1:_(s64), %2:_(s64), %1:_(s64), %1:_(s64)
    %5:_(<8 x s64>) = G_SHUFFLE_VECTOR %3(<8 x s64>), %4(<8 x s64>), shufflemask(0, 0, 0, 0, 0, 0, 0, 0)
    $x0 = COPY %5:_(<8 x s64>)
...
---
name:            test_512_8bit
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_512_8bit
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_BROADCAST_VECTOR]](<64 x s8>)
    %10:_(s32) = COPY $r0
    %1:_(s8) = G_TRUNC %10:_(s32)
    %20:_(s32) = COPY $r1
    %2:_(s8) = G_TRUNC %20:_(s32)
    %3:_(<64 x s8>) = G_BUILD_VECTOR %1:_(s8), %2:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %2:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %2:_(s8), %1:_(s8)
    %4:_(<64 x s8>) = G_BUILD_VECTOR %2:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %2:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %2:_(s8), %1:_(s8)
    %5:_(<64 x s8>) = G_SHUFFLE_VECTOR %3(<64 x s8>), %4(<64 x s8>), shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    $x0 = COPY %5:_(<64 x s8>)
...
---
name:            test_256_32bit_valid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_256_32bit_valid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_UNPAD_VECTOR]](<8 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR1]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[AIE_UNPAD_VECTOR1]](<8 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<8 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    %4:_(<8 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    %5:_(<8 x s32>) = G_SHUFFLE_VECTOR %3(<8 x s32>), %4(<8 x s32>), shufflemask(0, 0, 0, 0, 0, 0, 0, 0)
    $wl0 = COPY %5:_(<8 x s32>)
...

# Invalid Vector for broadcast.
# Not a splat vector
---
name:            test_256_32bit_invalid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_256_32bit_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_UNPAD_VECTOR]](<8 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR1]](<16 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_UNPAD_VECTOR]](<8 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<8 x s32>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR1]], [[EVEC1]](s32), [[C]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[IVEC]](<8 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<8 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    %4:_(<8 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    %5:_(<8 x s32>) = G_SHUFFLE_VECTOR %3(<8 x s32>), %4(<8 x s32>), shufflemask(1, 0, 0, 0, 0, 0, 0, 0)
    $wl0 = COPY %5:_(<8 x s32>)
...

---
name:            test_1024_32bit_valid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_1024_32bit_valid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $y2 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %4:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %5:_(<32 x s32>) = G_SHUFFLE_VECTOR %3(<32 x s32>), %4(<32 x s32>), shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    $y2 = COPY %5:_(<32 x s32>)
...

# Invalid Vector for broadcast.
# Not a splat or one-diff splat vector
---
name:            test_1024_32bit_invalid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_1024_32bit_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s32>) = G_BUILD_VECTOR [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[BUILD_VECTOR]](<32 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<16 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[UV]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[UV1]](s32), [[C]](s32)
    ; CHECK-NEXT: $y2 = COPY [[IVEC]](<32 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %4:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %5:_(<32 x s32>) = G_SHUFFLE_VECTOR %3(<32 x s32>), %4(<32 x s32>), shufflemask(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    $y2 = COPY %5:_(<32 x s32>)
...
---
name:            test_2048_32bit_valid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_2048_32bit_valid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<64 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %4:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %5:_(<64 x s32>) = G_SHUFFLE_VECTOR %3(<32 x s32>), %4(<32 x s32>), shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    $dm0 = COPY %5:_(<64 x s32>)
...

# Invalid Vector for broadcast.
# Not a splat or one-diff splat vector
---
name:            test_2048_32bit_invalid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_2048_32bit_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s32>) = G_BUILD_VECTOR [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32)
    ; CHECK-NEXT: [[BUILD_VECTOR1:%[0-9]+]]:_(<32 x s32>) = G_BUILD_VECTOR [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32)
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<64 x s32>) = G_SHUFFLE_VECTOR [[BUILD_VECTOR]](<32 x s32>), [[BUILD_VECTOR1]], shufflemask(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    ; CHECK-NEXT: $dm0 = COPY [[SHUF]](<64 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %4:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32)
    %5:_(<64 x s32>) = G_SHUFFLE_VECTOR %3(<32 x s32>), %4(<32 x s32>), shufflemask(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    $dm0 = COPY %5:_(<64 x s32>)
...
---
name:            test_broadcast_zero_to_v64accfloat
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_zero_to_v64accfloat
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[AIE_BROADCAST_VECTOR]](<64 x s32>)
    %1:_(s32) = G_FCONSTANT float 0.000000e+00
    %0:_(<64 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32)
    $dm0 = COPY %0(<64 x s32>)

...
---
name:            test_broadcast_one_to_v64accfloat
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_one_to_v64accfloat
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<64 x s32>)
    %1:_(s32) = G_CONSTANT i32 1
    %0:_(<64 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32)
    $dm0 = COPY %0(<64 x s32>)

...
---
name:            test_broadcast_const_v2i32_to_v64accfloat
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_const_v2i32_to_v64accfloat
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1311768464867721216
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[C]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s64>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<8 x s64>), [[AIE_BROADCAST_VECTOR]](<8 x s64>), [[AIE_BROADCAST_VECTOR]](<8 x s64>), [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    ; CHECK-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<32 x s64>)
    %1:_(s64) = G_CONSTANT i64 1311768464867721216
    %0:_(<32 x s64>) = G_BUILD_VECTOR %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64),%1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64)
    $dm0 = COPY %0(<32 x s64>)

...
---
name:            test_broadcast_const_v2i32_to_v64accfloat_const_0
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_const_v2i32_to_v64accfloat_const_0
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[C]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: $dm0 = COPY [[AIE_BROADCAST_VECTOR]](<32 x s64>)
    %1:_(s64) = G_CONSTANT i64 0
    %0:_(<32 x s64>) = G_BUILD_VECTOR %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64),%1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64), %1(s64)
    $dm0 = COPY %0(<32 x s64>)

...
---
name:       test_broadcast_constant_0_and_undef_to_v16s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_constant_0_and_undef_to_v16s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:       test_broadcast_constant_0_and_undef_mix_to_v16s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_constant_0_and_undef_mix_to_v16s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_BUILD_VECTOR %1(s32), %2(s32), %1(s32), %2(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:       test_broadcast_to_v16s32_invalid
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_to_v16s32_invalid
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_BUILD_VECTOR [[C]](s32), [[COPY]](s32), [[C]](s32), [[COPY]](s32), [[C]](s32), [[C]](s32), [[DEF]](s32), [[C]](s32), [[DEF]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BUILD_VECTOR]](<16 x s32>)
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = COPY $r1
    %3:_(s32) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_BUILD_VECTOR %1(s32), %2(s32), %1(s32), %2(s32), %1(s32), %1(s32), %3(s32), %1(s32), %3(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %1(s32)
    PseudoRET implicit $lr, implicit %0

...
---
name:       test_broadcast_constant_0_and_undef_to_v32s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_constant_0_and_undef_to_v32s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_IMPLICIT_DEF
    %0:_(<32 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0

...
---
name:       test_broadcast_undef_and_reg_to_v32s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_undef_and_reg_to_v32s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %1:_(s32) = COPY $r1
    %2:_(s32) = G_IMPLICIT_DEF
    %0:_(<32 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0

...
---
name:       test_broadcast_reg_and_undef_to_v32s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_reg_and_undef_to_v32s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %1:_(s32) = G_IMPLICIT_DEF
    %2:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0

...
---
name:       test_broadcast_reg_and_undef_mix_to_v32s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_reg_and_undef_mix_to_v32s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %1:_(s32) = G_IMPLICIT_DEF
    %2:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_BUILD_VECTOR %1(s32), %2(s32), %1(s32), %2(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %1(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0

...
---
name:       test_broadcast_undef_and_constant_0_to_v32s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_undef_and_constant_0_to_v32s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %1:_(s32) = G_IMPLICIT_DEF
    %2:_(s32) = G_CONSTANT i32 0
    %0:_(<32 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0

...
---
name:       test_broadcast_constant_0_and_undef_to_v64s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_constant_0_and_undef_to_v64s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 0.000000e+00
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<64 x s32>)
    %1:_(s32) = G_FCONSTANT float 0.000000e+00
    %2:_(s32) = G_IMPLICIT_DEF
    %0:_(<64 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:       test_broadcast_undef_and_constant_0_to_v64s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_undef_and_constant_0_to_v64s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<64 x s32>)
    %1:_(s32) = G_IMPLICIT_DEF
    %2:_(s32) = G_CONSTANT i32 0
    %0:_(<64 x s32>) = G_BUILD_VECTOR %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %1(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32), %2(s32)
    PseudoRET implicit $lr, implicit %0
...
---
name:       test_shuffle_broadcast_combine_v64s8
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v64s8
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<64 x s8>)
  %1:_(s32) = COPY $r0
  %2:_(<64 x s8>) = G_IMPLICIT_DEF
  %3:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<64 x s8>) = G_SHUFFLE_VECTOR %3:_(<64 x s8>), %2:_, shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v64s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v64s32
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<64 x s32>)
  %1:_(s32) = G_CONSTANT i32 0
  %2:_(<64 x s32>) = G_IMPLICIT_DEF
  %3:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<64 x s32>) = G_SHUFFLE_VECTOR %3:_(<64 x s32>), %2:_, shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v64s32_with_defsrc
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v64s32_with_defsrc
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<64 x s32>)
  %1:_(s32) = G_CONSTANT i32 0
  %2:_(<64 x s32>) = COPY $dm0
  %3:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<64 x s32>) = G_SHUFFLE_VECTOR %3:_(<64 x s32>), %2:_, shufflemask(32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v64s8_und_mask
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v64s8_und_mask
    ; CHECK: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<64 x s8>)
  %1:_(s32) = COPY $r0
  %2:_(<64 x s8>) = G_IMPLICIT_DEF
  %3:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<64 x s8>) = G_SHUFFLE_VECTOR %3:_(<64 x s8>), %2:_, shufflemask(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v16s32
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %2:_(<16 x s32>) = COPY $x0
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_bcst
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_bcst
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %2:_(<16 x s32>) = COPY $x0
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(0, 11, 15, 0, 0, 0, 0, 0, 10, 0, 8, 0, 0, 0, 0, 0)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v16s32_src2_bcst
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src2_bcst
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %2:_(<16 x s32>) = COPY $x0
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %2:_(<16 x s32>), %3:_, shufflemask(16, 16, 16, 17, 18, 20, 31, 16, 16, 16, 16, 16, 16, 16, 24, 25)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_bcst_invalid
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_bcst_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR1]], [[EVEC1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC2]](s64)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[UV1]](s32), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[EVEC3:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[IVEC2:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC1]], [[EVEC3]](s32), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[IVEC3:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC2]], [[UV]](s32), [[C6]](s32)
    ; CHECK-NEXT: [[EVEC4:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C6]](s32)
    ; CHECK-NEXT: [[IVEC4:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC3]], [[EVEC4]](s32), [[C5]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC4]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %2:_(<16 x s32>) = COPY $x0
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(16, 11, 15, 0, 0, 0, 0, 0, 10, 0, 8, 0, 0, 0, 0, 0)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v16s32_src2_bcst_invalid
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src2_bcst_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[UV]](s32)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR1]], [[EVEC1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[UV1]](s32), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC2:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC1]], [[EVEC2]](s32), [[C3]](s32)
    ; CHECK-NEXT: [[EVEC3:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[IVEC3:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC2]], [[EVEC3]](s32), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[EVEC4:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[IVEC4:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC3]], [[EVEC4]](s32), [[C6]](s32)
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC5:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST1]](<8 x s64>), [[C3]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC5]](s64)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[IVEC5:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC4]], [[UV2]](s32), [[C7]](s32)
    ; CHECK-NEXT: [[IVEC6:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC5]], [[UV3]](s32), [[C5]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC6]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %2:_(<16 x s32>) = COPY $x0
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %2:_(<16 x s32>), %3:_, shufflemask(0, 16, 16, 17, 18, 20, 31, 16, 16, 16, 16, 16, 16, 16, 24, 25)
  PseudoRET implicit $lr, implicit %0

...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_invalid
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY1]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR2:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR2]], [[EVEC1]](s32), [[C2]](s32)
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR1]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[EVEC2]](s32), [[C3]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC1]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %6:_(s32) = COPY $r1
  %2:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %6:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(1, 18, 18, 18, 18, 18, 18, 18, 18, 2, 18, 18, 18, 18, 18, 18)
  PseudoRET implicit $lr, implicit %0
...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src1_mask
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src1_mask
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %6:_(s32) = COPY $r1
  %2:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %6:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(1, 15, 15, 15, 15, 15, 15, 15, 15, 2, 15, 15, 15, 15, 15, 15)
  PseudoRET implicit $lr, implicit %0
...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src2_mask
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src2_mask
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %6:_(s32) = COPY $r1
  %2:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %6:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(16, 18, 18, 18, 18, 18, 18, 18, 18, 22, 18, 18, 18, 18, 18, 18)
  PseudoRET implicit $lr, implicit %0
...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src1_mask_undef
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src1_mask_undef
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %6:_(s32) = COPY $r1
  %2:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %6:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(-1, 1, -1, 10, -1, -1, -1, -1, -1, 1, 0, -1, -1, -1, -1, -1)
  PseudoRET implicit $lr, implicit %0
...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src2_mask_undef
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src2_mask_undef
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %6:_(s32) = COPY $r1
  %2:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %6:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(16, 18, -1, 18, 18, 18, 18, 18, 18, 22, -1, 18, 18, 18, 18, 18)
  PseudoRET implicit $lr, implicit %0
...
---
name:       test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src2_mask_undef_invalid
alignment:       16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_shuffle_broadcast_combine_v16s32_src1_and_src2_bcst_src2_mask_undef_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR1:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY1]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR2:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR2]], [[EVEC1]](s32), [[C1]](s32)
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[EVEC2]](s32), [[C2]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[EVEC3:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR1]](<16 x s32>), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC2:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC1]], [[EVEC3]](s32), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[EVEC4:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[C5]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[IVEC3:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC2]], [[EVEC4]](s32), [[C6]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC3]](<16 x s32>)
  %1:_(s32) = COPY $r0
  %6:_(s32) = COPY $r1
  %2:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %1:_(s32)
  %3:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %6:_(s32)
  %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %3:_(<16 x s32>), %2:_, shufflemask(16, 0, -1, 18, 5, 18, 18, 18, 18, 22, -1, 18, 18, 18, 18, 18)
  PseudoRET implicit $lr, implicit %0
...
