# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie2p-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s



# The combiner will try to combine the vector load and the extract to a single scalar load if it is Legal
# or if we are before the legalizer.
---
name:            combine_extracted_vector_load_s16_align2
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: combine_extracted_vector_load_s16_align2
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[PTR_ADD]](p0) :: (load (s16))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](s16)
    %1:_(p0) = COPY $p0
    %2:_(<32 x s16>) = G_LOAD %1:_(p0) :: (load (<8 x s16>) from `ptr null`, align 2)
    %4:_(s32) = G_CONSTANT i32 3
    %7:_(s16) = G_EXTRACT_VECTOR_ELT %2:_(<32 x s16>), %4:_(s32)
    PseudoRET implicit $lr, implicit %7
...


---
name:            combine_extracted_vector_load_s16_IdxZero
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: combine_extracted_vector_load_s16_IdxZero
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s16))
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[LOAD]](s32)
    ; CHECK-NEXT: G_STORE [[AIE_BROADCAST_VECTOR]](<32 x s16>), [[COPY]](p0) :: (store (<32 x s16>) into `ptr addrspace(6) null`, addrspace 6)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %3:_(<8 x s16>) = G_IMPLICIT_DEF
    %5:_(p0) = COPY $p0
    %0:_(<8 x s16>) = G_LOAD %5:_(p0) :: (load (<8 x s16>) from unknown-address, align 4)
    %2:_(<32 x s16>) = G_SHUFFLE_VECTOR %0:_(<8 x s16>), %3:_, shufflemask(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    G_STORE %2:_(<32 x s16>), %5:_(p0) :: (store (<32 x s16>) into `ptr addrspace(6) null`, addrspace 6)
    PseudoRET implicit $lr

...


---
name:            combine_extracted_vector_load_s16_IdxNonZero
alignment:       16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: combine_extracted_vector_load_s16_IdxNonZero
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s16))
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[LOAD]](s32)
    ; CHECK-NEXT: G_STORE [[AIE_BROADCAST_VECTOR]](<32 x s16>), [[COPY]](p0) :: (store (<32 x s16>) into `ptr addrspace(6) null`, addrspace 6)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %3:_(<8 x s16>) = G_IMPLICIT_DEF
    %5:_(p0) = COPY $p0
    %0:_(<8 x s16>) = G_LOAD %5:_(p0) :: (load (<8 x s16>) from `ptr null`, align 4)
    %2:_(<32 x s16>) = G_SHUFFLE_VECTOR %0:_(<8 x s16>), %3:_, shufflemask(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
    G_STORE %2:_(<32 x s16>), %5:_(p0) :: (store (<32 x s16>) into `ptr addrspace(6) null`, addrspace 6)
    PseudoRET implicit $lr

...
