# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s

# Test case where two paired vector extracts are merged (0 and 1).
---
name: paired_0_1
body:             |
  bb.1:
    ; CHECK-LABEL: name: paired_0_1
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<16 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
      %33:_(<32 x s32>) = COPY $y2
      %35:_(s32) = G_CONSTANT i32 0
      %38:_(s32) = G_CONSTANT i32 1
      %34:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %35(s32)
      %37:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %38(s32)
      $r0 = COPY %34
      $r1 = COPY %37
...

# Test case where two paired vector extracts are merged (0 and 1).
---
name: paired_0_1_and_2
body:             |
  bb.1:
    ; CHECK-LABEL: name: paired_0_1_and_2
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<16 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC1]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
    ; CHECK-NEXT: $r2 = COPY [[EVEC]](s32)
      %33:_(<32 x s32>) = COPY $y2
      %35:_(s32) = G_CONSTANT i32 0
      %38:_(s32) = G_CONSTANT i32 1
      %39:_(s32) = G_CONSTANT i32 2
      %40:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %39(s32)
      %37:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %38(s32)
      %34:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %35(s32)
      $r0 = COPY %34
      $r1 = COPY %37
      $r2 = COPY %40
...

# Test case where two paired vector extracts are merged (4 and 5).
---
name: paired_4_5
body:             |
  bb.1:
    ; CHECK-LABEL: name: paired_4_5
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<16 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV1]](s32)
      %33:_(<32 x s32>) = COPY $y2
      %35:_(s32) = G_CONSTANT i32 4
      %38:_(s32) = G_CONSTANT i32 5
      %34:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %35(s32)
      %37:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %38(s32)
      $r0 = COPY %34
      $r1 = COPY %37
...

# Test case where two vector extracts are folded with inverse unmerge.
---
name: paired_5_4
body:             |
  bb.1:
    ; CHECK-LABEL: name: paired_5_4
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<16 x s64>) = G_BITCAST [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<16 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: $r0 = COPY [[UV1]](s32)
    ; CHECK-NEXT: $r1 = COPY [[UV]](s32)
      %33:_(<32 x s32>) = COPY $y2
      %35:_(s32) = G_CONSTANT i32 5
      %38:_(s32) = G_CONSTANT i32 4
      %34:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %35(s32)
      %37:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %38(s32)
      $r0 = COPY %34
      $r1 = COPY %37
...

# Test case where two vector extracts are not merged (odd/odd).
---
name: paired_5_7
body:             |
  bb.1:
    ; CHECK-LABEL: name: paired_5_7
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s32>), [[C1]](s32)
    ; CHECK-NEXT: $r0 = COPY [[EVEC]](s32)
    ; CHECK-NEXT: $r1 = COPY [[EVEC1]](s32)
      %33:_(<32 x s32>) = COPY $y2
      %35:_(s32) = G_CONSTANT i32 5
      %38:_(s32) = G_CONSTANT i32 7
      %34:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %35(s32)
      %37:_(s32) = G_EXTRACT_VECTOR_ELT %33(<32 x s32>), %38(s32)
      $r0 = COPY %34
      $r1 = COPY %37
...
