; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p --stop-after=prologepilog  %s -o - | FileCheck %s


; TCO expected, caller & callee have same number of arguments & same return type & no arguments are passed over stack
define dso_local noundef i32 @_Z5test0ii(i32 noundef %a, i32 noundef %b) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test0ii
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z4funcii, csr_aie2p, implicit $r1, implicit $r2
entry:
  %call = tail call noundef i32 @_Z4funcii(i32 noundef %a, i32 noundef %b)
  ret i32 %call
}

; TCO expected, callee has one extra arguments & same return type & no arguments are passed over stack
define dso_local noundef i32 @_Z5test1i(i32 noundef %a) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test1i
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r2 = nsw ADD_add_r_ri renamable $r1, 10, implicit-def dead $srcarry
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z4funcii, csr_aie2p, implicit $r1, implicit $r2
entry:
  %add = add nsw i32 %a, 10
  %call = tail call noundef i32 @_Z4funcii(i32 noundef %a, i32 noundef %add)
  ret i32 %call
}

; TCO expected, callee has one extra arguments & same return type & no arguments are passed over stack
; Also test the case where the caller has a pointer argument
define dso_local void @_Z5test2PPv(ptr nocapture readonly %args) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test2PPv
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $p1 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (load (p0) from %ir.args, align 4)
  ; CHECK-NEXT:   renamable $p0 = LDA_dms_lda_idx_imm killed renamable $p0, 4 :: (load (p0) from %ir.arrayidx1, align 4)
  ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (load (s32) from %ir.0)
  ; CHECK-NEXT:   renamable $r2 = LDA_dms_lda_idx_imm killed renamable $p0, 0 :: (load (s32) from %ir.2)
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z4funcii, csr_aie2p, implicit $r1, implicit $r2
entry:
  %0 = load ptr, ptr %args, align 4
  %1 = load i32, ptr %0, align 4
  %arrayidx1 = getelementptr inbounds i8, ptr %args, i20 4
  %2 = load ptr, ptr %arrayidx1, align 4
  %3 = load i32, ptr %2, align 4
  %call = tail call noundef i32 @_Z4funcii(i32 noundef %1, i32 noundef %3)
  ret void
}

; TCO expected, caller & callee have same number of arguments & same return type & 1 argument is passed over stack for both caller & callee and the same SF is used
; Caller and callee Stack Arg Area is Same
define dso_local noundef i32 @_Z5test3iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %a7) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test3iiiiiiii
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p0 = MOV_alu_mv_mv_mv_scl $sp
  ; CHECK-NEXT:   $m0 = MOV_PD_imm11_pseudo -4
  ; CHECK-NEXT:   $p0 = PADD_mod_pseudo $p0, killed $m0
  ; CHECK-NEXT:   renamable $r0 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (invariant load (s32) from %fixed-stack.1)
  ; CHECK-NEXT:   ST_dms_sts_idx_imm killed renamable $r0, killed renamable $p0, 0 :: (store (s32) into %fixed-stack.0, align 32)
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z5func1iiiiiiii, csr_aie2p, implicit $r1, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit $r6, implicit $r7
entry:
  %call = tail call noundef i32 @_Z5func1iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %a7)
  ret i32 %call
}

; TCO expected, caller & callee have same number of arguments & same return type & 2 argument is passed over stack for caller & 1 argument for callee and the same SF is used
; Caller has more Stack Arg Area comapred to callee
define dso_local noundef i32 @_Z5test4iiiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %a7, i32 noundef %a8) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test4iiiiiiiii
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p0 = MOV_alu_mv_mv_mv_scl $sp
  ; CHECK-NEXT:   $m0 = MOV_PD_imm11_pseudo -4
  ; CHECK-NEXT:   $p0 = PADD_mod_pseudo $p0, killed $m0
  ; CHECK-NEXT:   renamable $r0 = LDA_dms_lda_idx_imm renamable $p0, 0 :: (invariant load (s32) from %fixed-stack.2)
  ; CHECK-NEXT:   renamable $r16 = LDA_dms_lda_idx_imm renamable $p0, -4 :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   renamable $r0 = nsw ADD_alu_r_rr killed renamable $r16, killed renamable $r0, implicit-def dead $srcarry
  ; CHECK-NEXT:   ST_dms_sts_idx_imm killed renamable $r0, killed renamable $p0, 0 :: (store (s32) into %fixed-stack.0, align 32)
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z5func1iiiiiiii, csr_aie2p, implicit $r1, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit $r6, implicit $r7
entry:
  %add = add nsw i32 %a8, %a7
  %call = tail call noundef i32 @_Z5func1iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %add)
  ret i32 %call
}

; TCO is NOT expected, caller & callee have same number of arguments & same return type & 0 argument is passed over stack for caller & 1 argument for callee
; Caller has less Stack Arg Area comapred to callee and thus TCO is not expected
; TODO : Extend TCO to support this case
define dso_local noundef i32 @_Z5test5iiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5test5iiiiiii
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   ST_dms_sts_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; CHECK-NEXT:   renamable $r0 = nsw ADD_add_r_ri renamable $r7, 10, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $p0 = COPY $sp
  ; CHECK-NEXT:   ST_dms_sts_idx_imm killed renamable $r0, killed renamable $p0, -4 :: (store (s32) into stack - 4, basealign 32)
  ; CHECK-NEXT:   PseudoJL @_Z5func1iiiiiiii, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit $r3, implicit $r4, implicit $r5, implicit $r6, implicit $r7, implicit-def $r0
  ; CHECK-NEXT:   $lr = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; CHECK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %add = add nsw i32 %a6, 10
  %call = tail call noundef i32 @_Z5func1iiiiiiii(i32 noundef %a, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %add)
  ret i32 %call
}

define dso_local noundef i32 @_Z4funcii(i32 noundef %a, i32 noundef %b) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z4funcii
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = nsw ADD_alu_r_rr killed renamable $r2, killed renamable $r1, implicit-def dead $srcarry
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %add = add nsw i32 %b, %a
  ret i32 %add
}

define dso_local noundef i32 @_Z5func1iiiiiiii(i32 noundef %a0, i32 noundef %a1, i32 noundef %a2, i32 noundef %a3, i32 noundef %a4, i32 noundef %a5, i32 noundef %a6, i32 noundef %a7) local_unnamed_addr {
  ; CHECK-LABEL: name: _Z5func1iiiiiiii
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p0 = MOV_alu_mv_mv_mv_scl $sp
  ; CHECK-NEXT:   $m0 = MOV_PD_imm11_pseudo -4
  ; CHECK-NEXT:   $p0 = PADD_mod_pseudo $p0, killed $m0
  ; CHECK-NEXT:   renamable $r0 = LDA_dms_lda_idx_imm killed renamable $p0, 0 :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   renamable $r1 = nsw ADD_alu_r_rr killed renamable $r2, killed renamable $r1, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $r1 = nsw ADD_alu_r_rr killed renamable $r1, killed renamable $r3, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $r1 = nsw ADD_alu_r_rr killed renamable $r1, killed renamable $r4, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $r1 = nsw ADD_alu_r_rr killed renamable $r1, killed renamable $r5, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $r1 = nsw ADD_alu_r_rr killed renamable $r1, killed renamable $r6, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $r1 = nsw ADD_alu_r_rr killed renamable $r1, killed renamable $r7, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $r0 = nsw ADD_alu_r_rr killed renamable $r1, killed renamable $r0, implicit-def dead $srcarry
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %add = add nsw i32 %a1, %a0
  %add1 = add nsw i32 %add, %a2
  %add2 = add nsw i32 %add1, %a3
  %add3 = add nsw i32 %add2, %a4
  %add4 = add nsw i32 %add3, %a5
  %add5 = add nsw i32 %add4, %a6
  %add6 = add nsw i32 %add5, %a7
  ret i32 %add6
}

; TCO is expected, make sure caller local alloc is destroyed before the callee is called as TCO
define dso_local noundef i32 @_Z12testFunctionv() local_unnamed_addr {
  ; CHECK-LABEL: name: _Z12testFunctionv
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $r8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   ST_dms_sts_spill killed $lr, -60, implicit $sp :: (store (s32) into %stack.0)
  ; CHECK-NEXT:   ST_dms_sts_spill killed $r8, -64, implicit $sp :: (store (s32) into %stack.1)
  ; CHECK-NEXT:   $r0 = MOV_RLC_imm11_pseudo 4
  ; CHECK-NEXT:   renamable $r8 = MOV_RLC_imm11_pseudo 100
  ; CHECK-NEXT:   PseudoJL @_Znwj, csr_aie2p, implicit-def $lr, implicit killed $r0, implicit-def $p0
  ; CHECK-NEXT:   ST_dms_sts_idx_imm killed renamable $r8, renamable $p0, 0 :: (volatile store (s32) into %ir.call)
  ; CHECK-NEXT:   renamable $r1 = LDA_dms_lda_idx_imm killed renamable $p0, 0 :: (volatile load (s32) from %ir.call)
  ; CHECK-NEXT:   $r8 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.1)
  ; CHECK-NEXT:   $lr = LDA_dms_lda_spill -60, implicit $sp :: (load (s32) from %stack.0)
  ; CHECK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @_Z7TCOfunci, csr_aie2p, implicit $r1
entry:
  %call = tail call noalias nonnull dereferenceable(4) ptr @_Znwj(i32 noundef 4)
  store volatile i32 100, ptr %call, align 4
  %0 = load volatile i32, ptr %call, align 4
  %call1 = tail call noundef i32 @_Z7TCOfunci(i32 noundef %0)
  ret i32 %call1
}

declare dso_local nonnull ptr @_Znwj(i32 noundef) local_unnamed_addr
declare dso_local noundef i32 @_Z7TCOfunci(i32 noundef) local_unnamed_addr
