# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_bitcast_2xs32_4xs16
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_bitcast_2xs32_4xs16
    ; CHECK: [[DEF:%[0-9]+]]:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:gprregbank(<4 x s16>) = G_BITCAST [[DEF]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<4 x s16>)
    %1:_(<2 x s32>) = G_IMPLICIT_DEF
    %0:_(<4 x s16>) = G_BITCAST %1(<2 x s32>)
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_bitcast_2xs32_s64
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_bitcast_2xs32_s64
    ; CHECK: [[DEF:%[0-9]+]]:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:gprregbank(s64) = G_BITCAST [[DEF]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](s64)
    %1:_(<2 x s32>) = G_IMPLICIT_DEF
    %0:_(s64) = G_BITCAST %1(<2 x s32>)
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_bitcast_s64_2xs32
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_bitcast_s64_2xs32
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(s64) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:gprregbank(<2 x s32>) = G_BITCAST [[COPY]](s64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BITCAST]](<2 x s32>)
    %1:_(s64) = COPY $l0
    %0:_(<2 x s32>) = G_BITCAST %1(s64)
    PseudoRET implicit $lr, implicit %0
...
