# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=FAST %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
...
---
name:            _Z22test_undef_v64bfloat16v
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z22test_undef_v64bfloat16v
    ; GREEDY: [[DEF:%[0-9]+]]:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: $y2 = COPY [[DEF]](<64 x s16>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; FAST-LABEL: name: _Z22test_undef_v64bfloat16v
    ; FAST: [[DEF:%[0-9]+]]:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    ; FAST-NEXT: $y2 = COPY [[DEF]](<64 x s16>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    %0:_(<64 x s16>) = G_IMPLICIT_DEF
    $y2 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            _Z22test_undef_v32accfloatv
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z22test_undef_v32accfloatv
    ; GREEDY: [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: $cml0 = COPY [[DEF]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: _Z22test_undef_v32accfloatv
    ; FAST: [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: $cml0 = COPY [[DEF]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<32 x s32>) = G_IMPLICIT_DEF
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_undef_v32floatv
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z19test_undef_v32floatv
    ; GREEDY: [[DEF:%[0-9]+]]:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: $y2 = COPY [[DEF]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $y2
    ;
    ; FAST-LABEL: name: _Z19test_undef_v32floatv
    ; FAST: [[DEF:%[0-9]+]]:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: $y2 = COPY [[DEF]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $y2
    %0:_(<32 x s32>) = G_IMPLICIT_DEF
    $y2 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            _Z19test_undef_v32acc32v
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z19test_undef_v32acc32v
    ; GREEDY: [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: $cml0 = COPY [[DEF]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: _Z19test_undef_v32acc32v
    ; FAST: [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: $cml0 = COPY [[DEF]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<32 x s32>) = G_IMPLICIT_DEF
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_undef_v16acc64v
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z19test_undef_v16acc64v
    ; GREEDY: [[DEF:%[0-9]+]]:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: $cml0 = COPY [[DEF]](<16 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: _Z19test_undef_v16acc64v
    ; FAST: [[DEF:%[0-9]+]]:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    ; FAST-NEXT: $cml0 = COPY [[DEF]](<16 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<16 x s64>) = G_IMPLICIT_DEF
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_undef_v64acc32v
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z19test_undef_v64acc32v
    ; GREEDY: [[DEF:%[0-9]+]]:accregbank(<64 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: $dm0 = COPY [[DEF]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: _Z19test_undef_v64acc32v
    ; FAST: [[DEF:%[0-9]+]]:accregbank(<64 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: $dm0 = COPY [[DEF]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:_(<64 x s32>) = G_IMPLICIT_DEF
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_undef_v32acc64v
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z19test_undef_v32acc64v
    ; GREEDY: [[DEF:%[0-9]+]]:accregbank(<32 x s64>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: $dm0 = COPY [[DEF]](<32 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: _Z19test_undef_v32acc64v
    ; FAST: [[DEF:%[0-9]+]]:accregbank(<32 x s64>) = G_IMPLICIT_DEF
    ; FAST-NEXT: $dm0 = COPY [[DEF]](<32 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:_(<32 x s64>) = G_IMPLICIT_DEF
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
