# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect %s -verify-machineinstrs -o - | FileCheck %s

# Test that G_CONSTANT i20 values used in addressing intrinsics are mapped to MODRegBank

...
---
name:   phi_with_mixed_uses
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: phi_with_mixed_uses
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s20) = G_PHI [[C1]](s20), %bb.1, [[C2]](s20), %bb.2
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:modregbank(s20) = COPY [[PHI]](s20)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:gprregbank(s32) = G_ANYEXT [[COPY2]](s20)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:modregbank(s20) = COPY [[PHI]](s20)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:modregbank(s20), [[INT2:%[0-9]+]]:modregbank(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), [[COPY]](p0), [[C4]](s20), [[C3]](s20), [[COPY3]](s20), [[C3]](s20), [[C3]](s20), [[C5]](s20), [[C3]](s20)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   $p0 = COPY [[INT]](p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $p0
  bb.0.entry:
    successors: %bb.1, %bb.2
    liveins: $p0, $r0

    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %4:_(s32) = G_CONSTANT i32 0
    %5:_(s32) = G_ICMP intpred(eq), %1(s32), %4
    G_BRCOND %5(s32), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.3
    %2:_(s20) = G_CONSTANT i20 0
    G_BR %bb.3

  bb.2:
    successors: %bb.3
    %6:_(s20) = G_CONSTANT i20 128

  bb.3:
    %7:_(s20) = G_PHI %2(s20), %bb.1, %6(s20), %bb.2
    %8:_(s20) = G_CONSTANT i20 0
    %9:_(s20) = G_CONSTANT i20 64
    %10:_(s20) = G_CONSTANT i20 1
    %11:_(s32) = G_ANYEXT %7(s20)
    %12:_(p0), %13:_(s20), %14:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0(p0), %9(s20), %8(s20), %7(s20), %8(s20), %8(s20), %10(s20), %8(s20)
    $r0 = COPY %11(s32)
    $p0 = COPY %12(p0)
    PseudoRET implicit $lr, implicit $r0, implicit $p0

...
