# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_mul_8x8_8x8T
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $e0, $e1, $x0, $x1
    ; CHECK-LABEL: name: test_mul_8x8_8x8T
    ; CHECK: liveins: $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 780
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<8 x s8>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x1
    %4:_(<8 x s8>) = COPY $e1
    %6:_(s32) = G_CONSTANT i32 780
    %5:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %6(s32)
    PseudoRET implicit $lr, implicit %5

...
---
name:            test_negmul_8x8_8x8T
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $e0, $e1, $x0, $x1
    ; CHECK-LABEL: name: test_negmul_8x8_8x8T
    ; CHECK: liveins: $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 780
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<8 x s8>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x1
    %4:_(<8 x s8>) = COPY $e1
    %6:_(s32) = G_CONSTANT i32 780
    %5:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %6(s32)
    PseudoRET implicit $lr, implicit %5

...
---
name:            test_mac_8x8_8x8TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true


body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e1, $x0, $x1
    ; CHECK-LABEL: name: test_mac_8x8_8x8TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 780
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<8 x s8>), [[COPY4]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x1
    %4:_(<8 x s8>) = COPY $e1
    %5:_(<64 x s32>) = COPY $dm1
    %7:_(s32) = G_CONSTANT i32 780
    %6:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %7(s32)
    PseudoRET implicit $lr, implicit %6

...
---
name:            test_msc_8x8_8x8TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e1, $x0, $x1
    ; CHECK-LABEL: name: test_msc_8x8_8x8TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 780
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<8 x s8>), [[COPY4]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x1
    %4:_(<8 x s8>) = COPY $e1
    %5:_(<64 x s32>) = COPY $dm1
    %7:_(s32) = G_CONSTANT i32 780
    %6:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %7(s32)
    PseudoRET implicit $lr, implicit %6

...
---
name:            test_addmac_8x8_8x8TDv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e1, $x0, $x1
    ; CHECK-LABEL: name: test_addmac_8x8_8x8TDv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 780
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<8 x s8>), [[COPY4]](<64 x s32>), [[COPY5]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x1
    %4:_(<8 x s8>) = COPY $e1
    %5:_(<64 x s32>) = COPY $dm1
    %6:_(<64 x s32>) = COPY $dm2
    %8:_(s32) = G_CONSTANT i32 780
    %7:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %6(<64 x s32>), %8(s32)
    PseudoRET implicit $lr, implicit %7

...
---
name:            test_addmsc_8x8_8x8TDv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e1, $x0, $x1
    ; CHECK-LABEL: name: test_addmsc_8x8_8x8TDv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e1, $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 780
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<8 x s8>), [[COPY4]](<64 x s32>), [[COPY5]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x1
    %4:_(<8 x s8>) = COPY $e1
    %5:_(<64 x s32>) = COPY $dm1
    %6:_(<64 x s32>) = COPY $dm2
    %8:_(s32) = G_CONSTANT i32 780
    %7:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<8 x s8>), %5(<64 x s32>), %6(<64 x s32>), %8(s32)
    PseudoRET implicit $lr, implicit %7

...
---
name:            test_mul_4x8_8x16T
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-LABEL: name: test_mul_4x8_8x16T
    ; CHECK: liveins: $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e3
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 972
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<64 x s8>), [[COPY4]](<8 x s8>), [[COPY5]](<8 x s8>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x2
    %4:_(<64 x s8>) = COPY $x3
    %5:_(<8 x s8>) = COPY $e2
    %6:_(<8 x s8>) = COPY $e3
    %8:_(s32) = G_CONSTANT i32 972
    %7:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %8(s32)
    PseudoRET implicit $lr, implicit %7

...
---
name:            test_negmul_4x8_8x16T
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-LABEL: name: test_negmul_4x8_8x16T
    ; CHECK: liveins: $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e3
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 972
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<64 x s8>), [[COPY4]](<8 x s8>), [[COPY5]](<8 x s8>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x2
    %4:_(<64 x s8>) = COPY $x3
    %5:_(<8 x s8>) = COPY $e2
    %6:_(<8 x s8>) = COPY $e3
    %8:_(s32) = G_CONSTANT i32 972
    %7:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %8(s32)
    PseudoRET implicit $lr, implicit %7

...
---
name:            test_mac_4x8_8x16TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-LABEL: name: test_mac_4x8_8x16TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 972
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<64 x s8>), [[COPY4]](<8 x s8>), [[COPY5]](<8 x s8>), [[COPY6]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x2
    %4:_(<64 x s8>) = COPY $x3
    %5:_(<8 x s8>) = COPY $e2
    %6:_(<8 x s8>) = COPY $e3
    %7:_(<64 x s32>) = COPY $dm1
    %9:_(s32) = G_CONSTANT i32 972
    %8:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %9(s32)
    PseudoRET implicit $lr, implicit %8

...
---
name:            test_msc_4x8_8x16TDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-LABEL: name: test_msc_4x8_8x16TDv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 972
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<64 x s8>), [[COPY4]](<8 x s8>), [[COPY5]](<8 x s8>), [[COPY6]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x2
    %4:_(<64 x s8>) = COPY $x3
    %5:_(<8 x s8>) = COPY $e2
    %6:_(<8 x s8>) = COPY $e3
    %7:_(<64 x s32>) = COPY $dm1
    %9:_(s32) = G_CONSTANT i32 972
    %8:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %9(s32)
    PseudoRET implicit $lr, implicit %8

...
---
name:            test_addmac_4x8_8x16TDv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-LABEL: name: test_addmac_4x8_8x16TDv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 972
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<64 x s8>), [[COPY4]](<8 x s8>), [[COPY5]](<8 x s8>), [[COPY6]](<64 x s32>), [[COPY7]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x2
    %4:_(<64 x s8>) = COPY $x3
    %5:_(<8 x s8>) = COPY $e2
    %6:_(<8 x s8>) = COPY $e3
    %7:_(<64 x s32>) = COPY $dm1
    %8:_(<64 x s32>) = COPY $dm2
    %10:_(s32) = G_CONSTANT i32 972
    %9:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %8(<64 x s32>), %10(s32)
    PseudoRET implicit $lr, implicit %9

...
---
name:            test_addmsc_4x8_8x16TDv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true

body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-LABEL: name: test_addmsc_4x8_8x16TDv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e2, $e3, $x0, $x2, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e3
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 972
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf), [[COPY]](<64 x s8>), [[COPY1]](<8 x s8>), [[COPY2]](<64 x s8>), [[COPY3]](<64 x s8>), [[COPY4]](<8 x s8>), [[COPY5]](<8 x s8>), [[COPY6]](<64 x s32>), [[COPY7]](<64 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s32>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<8 x s8>) = COPY $e0
    %3:_(<64 x s8>) = COPY $x2
    %4:_(<64 x s8>) = COPY $x3
    %5:_(<8 x s8>) = COPY $e2
    %6:_(<8 x s8>) = COPY $e3
    %7:_(<64 x s32>) = COPY $dm1
    %8:_(<64 x s32>) = COPY $dm2
    %10:_(s32) = G_CONSTANT i32 972
    %9:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf), %1(<64 x s8>), %2(<8 x s8>), %3(<64 x s8>), %4(<64 x s8>), %5(<8 x s8>), %6(<8 x s8>), %7(<64 x s32>), %8(<64 x s32>), %10(s32)
    PseudoRET implicit $lr, implicit %9

...
