# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_8xs64
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_8xs64
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(<2 x s32>) = COPY $l0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[COPY]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    %0:_(<2 x s32>) = COPY $l0
    %1:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR %0(<2 x s32>)
    PseudoRET implicit $lr, implicit %1
...

---
name:            test_16xs32
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_16xs32
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %0:_(s32) = COPY $r0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_broadcast_zero_to_v64accfloat
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_broadcast_zero_to_v64accfloat
    ; CHECK: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:accregbank(<64 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<64 x s32>)
    %1:_(s32) = G_CONSTANT i32 0
    %0:_(<64 x s32>) = G_AIE_BROADCAST_VECTOR %1(s32)
    PseudoRET implicit $lr, implicit %0

...
---
name:            test_broadcast_const_v2i32_to_v64accfloat
legalized:       true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_broadcast_const_v2i32_to_v64accfloat
    ; CHECK: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[MV:%[0-9]+]]:gprregbank(s64) = G_MERGE_VALUES [[C]](s32), [[C]](s32)
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:gprregbank(<2 x s32>) = G_BITCAST [[MV]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:accregbank(<32 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<32 x s64>)
    %3:_(s32) = G_CONSTANT i32 0
    %0:_(s64) = G_MERGE_VALUES %3(s32), %3(s32)
    %2:_(<2 x s32>) = G_BITCAST %0(s64)
    %1:_(<32 x s64>) = G_AIE_BROADCAST_VECTOR %2(<2 x s32>)
    PseudoRET implicit $lr, implicit %1

...
