# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
---
name:           test_unmerge_2x256_to_s256
legalized:       true
body:             |
  bb.0.entry:
    liveins: $x0
    ; CHECK-LABEL: name: test_unmerge_2x256_to_s256
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<2 x s256>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(s256), [[UV1:%[0-9]+]]:vregbank(s256) = G_UNMERGE_VALUES [[COPY]](<2 x s256>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](s256), implicit [[UV1]](s256)
    %0:_(<2 x s256>) = COPY $x0
    %1:_(s256), %2:_(s256) = G_UNMERGE_VALUES %0(<2 x s256>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:           test_unmerge_2x256_to_s256_acc
legalized:       true
body:             |
  bb.0.entry:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_unmerge_2x256_to_s256_acc
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<2 x s256>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<2 x s256>) = COPY [[COPY]](<2 x s256>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(s256), [[UV1:%[0-9]+]]:vregbank(s256) = G_UNMERGE_VALUES [[COPY1]](<2 x s256>)
    ; CHECK-NEXT: $wl0 = COPY [[UV]](s256)
    ; CHECK-NEXT: $wl2 = COPY [[UV1]](s256)
    %0:_(<2 x s256>) = COPY $bmll0
    %1:_(s256), %2:_(s256) = G_UNMERGE_VALUES %0(<2 x s256>)
    $wl0 = COPY %1:_(s256)
    $wl2 = COPY %2:_(s256)
...

---
name:           test_unmerge_2x512_to_s512
legalized:       true
body:             |
  bb.0.entry:
    liveins: $y2
    ; CHECK-LABEL: name: test_unmerge_2x512_to_s512
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<2 x s512>) = COPY $y2
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(s512), [[UV1:%[0-9]+]]:vregbank(s512) = G_UNMERGE_VALUES [[COPY]](<2 x s512>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](s512), implicit [[UV1]](s512)
    %0:_(<2 x s512>) = COPY $y2
    %1:_(s512), %2:_(s512) = G_UNMERGE_VALUES %0(<2 x s512>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:           test_unmerge_2x512_to_s512_acc
legalized:       true
body:             |
  bb.0.entry:
    liveins: $cml0
    ; CHECK-LABEL: name: test_unmerge_2x512_to_s512_acc
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<2 x s512>) = COPY $cml0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:accregbank(s512), [[UV1:%[0-9]+]]:accregbank(s512) = G_UNMERGE_VALUES [[COPY]](<2 x s512>)
    ; CHECK-NEXT: $bmll0 = COPY [[UV]](s512)
    ; CHECK-NEXT: $bmll2 = COPY [[UV1]](s512)
    %0:_(<2 x s512>) = COPY $cml0
    %1:_(s512), %2:_(s512) = G_UNMERGE_VALUES %0(<2 x s512>)
    $bmll0 = COPY %1:_(s512)
    $bmll2 = COPY %2:_(s512)
...


---
name:           test_unmerge_2x2048_to_s1024
legalized:       true
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_2x2048_to_s1024
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<2 x s1024>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:accregbank(s1024), [[UV1:%[0-9]+]]:accregbank(s1024) = G_UNMERGE_VALUES [[COPY]](<2 x s1024>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](s1024), implicit [[UV1]](s1024)
    %0:_(<2 x s1024>) = COPY $dm0
    %1:_(s1024), %2:_(s1024) = G_UNMERGE_VALUES %0(<2 x s1024>)
    PseudoRET implicit $lr, implicit %1, implicit %2
...

---
name:           test_unmerge_2x2048_to_s1024_vec
legalized:       true
body:             |
  bb.0.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_unmerge_2x2048_to_s1024_vec
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<2 x s1024>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:accregbank(s1024), [[UV1:%[0-9]+]]:accregbank(s1024) = G_UNMERGE_VALUES [[COPY]](<2 x s1024>)
    ; CHECK-NEXT: $y2 = COPY [[UV]](s1024)
    ; CHECK-NEXT: $y3 = COPY [[UV1]](s1024)
    %0:_(<2 x s1024>) = COPY $dm0
    %1:_(s1024), %2:_(s1024) = G_UNMERGE_VALUES %0(<2 x s1024>)
    $y2 = COPY %1:_(s1024)
    $y3 = COPY %2:_(s1024)
...

---
name:            test_unmerge_v8s64
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_unmerge_v8s64
    ; CHECK: [[COPY:%[0-9]+]]:vregbank(<8 x s64>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(<4 x s64>), [[UV1:%[0-9]+]]:vregbank(<4 x s64>) = G_UNMERGE_VALUES [[COPY]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s64>)
    %0:_(<8 x s64>) = COPY $x0
    %1:_(<4 x s64>), %2:_(<4 x s64>) = G_UNMERGE_VALUES %0(<8 x s64>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_unmerge_v8s64_acc
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_unmerge_v8s64_acc
    ; CHECK: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<8 x s64>) = COPY [[COPY]](<8 x s64>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(<4 x s64>), [[UV1:%[0-9]+]]:vregbank(<4 x s64>) = G_UNMERGE_VALUES [[COPY1]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s64>)
    %0:_(<8 x s64>) = COPY $bmll0
    %1:_(<4 x s64>), %2:_(<4 x s64>) = G_UNMERGE_VALUES %0(<8 x s64>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_unmerge_v8s32
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_unmerge_v8s32
    ; CHECK: [[COPY:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(<4 x s32>), [[UV1:%[0-9]+]]:vregbank(<4 x s32>) = G_UNMERGE_VALUES [[COPY]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s32>)
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<4 x s32>), %2:_(<4 x s32>) = G_UNMERGE_VALUES %0(<8 x s32>)
    PseudoRET implicit $lr, implicit %2
...
