# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_scalarSrc_128
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_scalarSrc_128
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(s128) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<2 x s64>) = G_BITCAST [[DEF]](s128)
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:vregbank(<4 x s64>) = G_AIE_PAD_VECTOR_UNDEF [[BITCAST]](<2 x s64>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<4 x s64>) = COPY [[DEF1]](<4 x s64>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<8 x s64>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<4 x s64>), [[COPY]](<4 x s64>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<8 x s64>) = COPY [[CONCAT_VECTORS]](<8 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY1]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[CONCAT_VECTORS1:%[0-9]+]]:vregbank(<8 x s64>) = G_CONCAT_VECTORS [[AIE_PAD_VECTOR_UNDEF]](<4 x s64>), [[DEF1]](<4 x s64>)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<8 x s64>) = COPY [[CONCAT_VECTORS1]](<8 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT1:%[0-9]+]]:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY2]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: $l0 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    ; CHECK-NEXT: $l1 = COPY [[AIE_SEXT_EXTRACT_VECTOR_ELT1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l0, implicit $l1
    %0:_(s128) = G_IMPLICIT_DEF
    %1:_(<2 x s64>) = G_BITCAST %0(s128)
    %2:_(<4 x s64>) = G_AIE_PAD_VECTOR_UNDEF %1(<2 x s64>)
    %3:_(s32) = G_CONSTANT i32 0
    %4:_(<4 x s64>) = G_IMPLICIT_DEF
    %5:_(<4 x s64>) = COPY %4(<4 x s64>)
    %6:_(<8 x s64>) = G_CONCAT_VECTORS %2(<4 x s64>), %5(<4 x s64>)
    %7:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %6(<8 x s64>), %3(s32)
    %8:_(s32) = G_CONSTANT i32 1
    %9:_(<8 x s64>) = G_CONCAT_VECTORS %2(<4 x s64>), %4(<4 x s64>)
    %10:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %9(<8 x s64>), %8(s32)
    $l0 = COPY %7(s64)
    $l1 = COPY %10(s64)
    PseudoRET implicit $lr, implicit $l0, implicit $l1

...
---
name:            test_scalarSrc_s256
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_scalarSrc_s256
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(s256) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<4 x s64>) = G_BITCAST [[DEF]](s256)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<8 x s64>) = G_CONCAT_VECTORS [[BITCAST]](<4 x s64>), [[DEF1]](<4 x s64>)
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY [[CONCAT_VECTORS]](<8 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    %0:_(s256) = G_IMPLICIT_DEF
    %1:_(<4 x s64>) = G_BITCAST %0(s256)
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<4 x s64>) = G_IMPLICIT_DEF
    %4:_(<8 x s64>) = G_CONCAT_VECTORS %1(<4 x s64>), %3(<4 x s64>)
    %5:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %5(s64)

...
---
name:            test_scalarSrc_s512
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_scalarSrc_s512
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(s512) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s64>) = G_BITCAST [[DEF]](s512)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY [[BITCAST]](<8 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    %0:_(s512) = G_IMPLICIT_DEF
    %1:_(<8 x s64>) = G_BITCAST %0(s512)
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %1(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %3(s64)

...
---
name:            test_scalarSrc_s1024
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_scalarSrc_s1024
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(s1024) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s64>) = G_BITCAST [[DEF]](s1024)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(<8 x s64>), [[UV1:%[0-9]+]]:vregbank(<8 x s64>) = G_UNMERGE_VALUES [[BITCAST]](<16 x s64>)
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY [[UV]](<8 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    %0:_(s1024) = G_IMPLICIT_DEF
    %1:_(<16 x s64>) = G_BITCAST %0(s1024)
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<8 x s64>), %4:_(<8 x s64>) = G_UNMERGE_VALUES %1(<16 x s64>)
    %5:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %3(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %5(s64)

...
---
name:            test_scalarSrc_s2048
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: test_scalarSrc_s2048
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(s2048) = COPY $dm0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY]](s2048)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:accregbank(<16 x s64>), [[UV1:%[0-9]+]]:accregbank(<16 x s64>) = G_UNMERGE_VALUES [[BITCAST]](<32 x s64>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:accregbank(<8 x s64>), [[UV3:%[0-9]+]]:accregbank(<8 x s64>) = G_UNMERGE_VALUES [[UV]](<16 x s64>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:gprregbank(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[UV2]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_SEXT_EXTRACT_VECTOR_ELT]](s64)
    %0:_(s2048) = COPY $dm0
    %1:_(<32 x s64>) = G_BITCAST %0(s2048)
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<16 x s64>), %4:_(<16 x s64>) = G_UNMERGE_VALUES %1(<32 x s64>)
    %5:_(<8 x s64>), %6:_(<8 x s64>) = G_UNMERGE_VALUES %3(<16 x s64>)
    %7:_(s64) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %5(<8 x s64>), %2(s32)
    PseudoRET implicit $lr, implicit %7(s64)

...
---
name:            test__s128_s256_v8
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test__s128_s256_v8
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<4 x s32>) = G_AIE_UNPAD_VECTOR [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[DEF]](<8 x s32>), [[DEF]](<8 x s32>)
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:vregbank(<16 x s32>) = G_AIE_VSHIFT_RIGHT [[CONCAT_VECTORS]], [[DEF1]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:vregbank(<4 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSHIFT_RIGHT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<4 x s32>), implicit [[AIE_UNPAD_VECTOR1]](<4 x s32>)
    %0:_(<8 x s32>) = G_IMPLICIT_DEF
    %1:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %0(<8 x s32>)
    %2:_(s32) = G_CONSTANT i32 16
    %3:_(<16 x s32>) = G_CONCAT_VECTORS %0(<8 x s32>), %0(<8 x s32>)
    %4:_(<16 x s32>) = G_IMPLICIT_DEF
    %5:_(<16 x s32>) = G_AIE_VSHIFT_RIGHT %3, %4, %2(s32)
    %6:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %5(<16 x s32>)
    PseudoRET implicit $lr, implicit %1(<4 x s32>), implicit %6(<4 x s32>)

...
---
name:            test__s128_s256_v16
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test__s128_s256_v16
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<8 x s16>) = G_AIE_UNPAD_VECTOR [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s16>) = G_CONCAT_VECTORS [[DEF]](<16 x s16>), [[DEF]](<16 x s16>)
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:vregbank(<32 x s16>) = G_AIE_VSHIFT_RIGHT [[CONCAT_VECTORS]], [[DEF1]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:vregbank(<8 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_VSHIFT_RIGHT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s16>), implicit [[AIE_UNPAD_VECTOR1]](<8 x s16>)
    %0:_(<16 x s16>) = G_IMPLICIT_DEF
    %1:_(<8 x s16>) = G_AIE_UNPAD_VECTOR %0(<16 x s16>)
    %2:_(s32) = G_CONSTANT i32 16
    %3:_(<32 x s16>) = G_CONCAT_VECTORS %0(<16 x s16>), %0(<16 x s16>)
    %4:_(<32 x s16>) = G_IMPLICIT_DEF
    %5:_(<32 x s16>) = G_AIE_VSHIFT_RIGHT %3, %4, %2(s32)
    %6:_(<8 x s16>) = G_AIE_UNPAD_VECTOR %5(<32 x s16>)
    PseudoRET implicit $lr, implicit %1(<8 x s16>), implicit %6(<8 x s16>)

...
---
name:            test__s128_s256_v32
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test__s128_s256_v32
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<16 x s8>) = G_AIE_UNPAD_VECTOR [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<64 x s8>) = G_CONCAT_VECTORS [[DEF]](<32 x s8>), [[DEF]](<32 x s8>)
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_VSHIFT_RIGHT:%[0-9]+]]:vregbank(<64 x s8>) = G_AIE_VSHIFT_RIGHT [[CONCAT_VECTORS]], [[DEF1]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:vregbank(<16 x s8>) = G_AIE_UNPAD_VECTOR [[AIE_VSHIFT_RIGHT]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<16 x s8>), implicit [[AIE_UNPAD_VECTOR1]](<16 x s8>)
    %0:_(<32 x s8>) = G_IMPLICIT_DEF
    %1:_(<16 x s8>) = G_AIE_UNPAD_VECTOR %0(<32 x s8>)
    %2:_(s32) = G_CONSTANT i32 16
    %3:_(<64 x s8>) = G_CONCAT_VECTORS %0(<32 x s8>), %0(<32 x s8>)
    %4:_(<64 x s8>) = G_IMPLICIT_DEF
    %5:_(<64 x s8>) = G_AIE_VSHIFT_RIGHT %3, %4, %2(s32)
    %6:_(<16 x s8>) = G_AIE_UNPAD_VECTOR %5(<64 x s8>)
    PseudoRET implicit $lr, implicit %1(<16 x s8>), implicit %6(<16 x s8>)

...
---
name:            test__4DstVectors
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test__4DstVectors
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[UV:%[0-9]+]]:vregbank(<16 x s32>), [[UV1:%[0-9]+]]:vregbank(<16 x s32>) = G_UNMERGE_VALUES [[DEF]](<32 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:vregbank(<8 x s32>), [[UV3:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[UV]](<16 x s32>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:vregbank(<8 x s32>), [[UV5:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[UV1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV2]](<8 x s32>), implicit [[UV3]](<8 x s32>), implicit [[UV4]](<8 x s32>), implicit [[UV5]](<8 x s32>)
    %0:_(<32 x s32>) = G_IMPLICIT_DEF
    %1:_(<16 x s32>), %2:_(<16 x s32>) = G_UNMERGE_VALUES %0(<32 x s32>)
    %3:_(<8 x s32>), %4:_(<8 x s32>) = G_UNMERGE_VALUES %1(<16 x s32>)
    %5:_(<8 x s32>), %6:_(<8 x s32>) = G_UNMERGE_VALUES %2(<16 x s32>)
    PseudoRET implicit $lr, implicit %3(<8 x s32>), implicit %4(<8 x s32>), implicit %5(<8 x s32>), implicit %6(<8 x s32>)

...
---
name:            test__8DstVectors
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test__8DstVectors
    ; CHECK: [[DEF:%[0-9]+]]:accregbank(<64 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[UV:%[0-9]+]]:accregbank(<32 x s32>), [[UV1:%[0-9]+]]:accregbank(<32 x s32>) = G_UNMERGE_VALUES [[DEF]](<64 x s32>)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:accregbank(<16 x s32>), [[UV3:%[0-9]+]]:accregbank(<16 x s32>) = G_UNMERGE_VALUES [[UV]](<32 x s32>)
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[UV2]](<16 x s32>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:vregbank(<8 x s32>), [[UV5:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[UV3]](<16 x s32>)
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:vregbank(<8 x s32>), [[UV7:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:accregbank(<16 x s32>), [[UV9:%[0-9]+]]:accregbank(<16 x s32>) = G_UNMERGE_VALUES [[UV1]](<32 x s32>)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[UV8]](<16 x s32>)
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:vregbank(<8 x s32>), [[UV11:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[UV9]](<16 x s32>)
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:vregbank(<8 x s32>), [[UV13:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[COPY3]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV4]](<8 x s32>), implicit [[UV5]](<8 x s32>), implicit [[UV6]](<8 x s32>), implicit [[UV7]](<8 x s32>), implicit [[UV10]](<8 x s32>), implicit [[UV11]](<8 x s32>), implicit [[UV12]](<8 x s32>), implicit [[UV13]](<8 x s32>)
    %0:_(<64 x s32>) = G_IMPLICIT_DEF
    %1:_(<32 x s32>), %2:_(<32 x s32>) = G_UNMERGE_VALUES %0(<64 x s32>)
    %3:_(<16 x s32>), %4:_(<16 x s32>) = G_UNMERGE_VALUES %1(<32 x s32>)
    %5:_(<8 x s32>), %6:_(<8 x s32>) = G_UNMERGE_VALUES %3(<16 x s32>)
    %7:_(<8 x s32>), %8:_(<8 x s32>) = G_UNMERGE_VALUES %4(<16 x s32>)
    %9:_(<16 x s32>), %10:_(<16 x s32>) = G_UNMERGE_VALUES %2(<32 x s32>)
    %11:_(<8 x s32>), %12:_(<8 x s32>) = G_UNMERGE_VALUES %9(<16 x s32>)
    %13:_(<8 x s32>), %14:_(<8 x s32>) = G_UNMERGE_VALUES %10(<16 x s32>)
    PseudoRET implicit $lr, implicit %5(<8 x s32>), implicit %6(<8 x s32>), implicit %7(<8 x s32>), implicit %8(<8 x s32>), implicit %11(<8 x s32>), implicit %12(<8 x s32>), implicit %13(<8 x s32>), implicit %14(<8 x s32>)

...
---
name:            test_s8_s64
alignment:       1
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_s8_s64
    ; CHECK: [[COPY:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:gprregbank(s64) = G_BITCAST [[COPY]](<8 x s8>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:gprregbank(s32) = G_TRUNC [[BITCAST]](s64)
    ; CHECK-NEXT: [[SEXT_INREG:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[TRUNC]], 8
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[UV:%[0-9]+]]:gprregbank(s32), [[UV1:%[0-9]+]]:gprregbank(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:gprregbank(s32) = G_LSHR [[UV]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:gprregbank(s32) = G_SHL [[UV1]], [[C1]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gprregbank(s32) = G_OR [[LSHR]], [[SHL]]
    ; CHECK-NEXT: [[SEXT_INREG1:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[OR]], 8
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:gprregbank(s32), [[UV3:%[0-9]+]]:gprregbank(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR1:%[0-9]+]]:gprregbank(s32) = G_LSHR [[UV2]], [[C2]](s32)
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:gprregbank(s32) = G_SHL [[UV3]], [[C2]](s32)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:gprregbank(s32) = G_OR [[LSHR1]], [[SHL1]]
    ; CHECK-NEXT: [[SEXT_INREG2:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[OR1]], 8
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:gprregbank(s32), [[UV5:%[0-9]+]]:gprregbank(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR2:%[0-9]+]]:gprregbank(s32) = G_LSHR [[UV4]], [[C1]](s32)
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:gprregbank(s32) = G_SHL [[UV5]], [[C]](s32)
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:gprregbank(s32) = G_OR [[LSHR2]], [[SHL2]]
    ; CHECK-NEXT: [[SEXT_INREG3:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[OR2]], 8
    ; CHECK-NEXT: [[UV6:%[0-9]+]]:gprregbank(s32), [[UV7:%[0-9]+]]:gprregbank(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[SEXT_INREG4:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[UV7]], 8
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:gprregbank(s32), [[UV9:%[0-9]+]]:gprregbank(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR3:%[0-9]+]]:gprregbank(s32) = G_LSHR [[UV9]], [[C]](s32)
    ; CHECK-NEXT: [[SEXT_INREG5:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[LSHR3]], 8
    ; CHECK-NEXT: [[UV10:%[0-9]+]]:gprregbank(s32), [[UV11:%[0-9]+]]:gprregbank(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR4:%[0-9]+]]:gprregbank(s32) = G_LSHR [[UV11]], [[C2]](s32)
    ; CHECK-NEXT: [[SEXT_INREG6:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[LSHR4]], 8
    ; CHECK-NEXT: [[UV12:%[0-9]+]]:gprregbank(s32), [[UV13:%[0-9]+]]:gprregbank(s32) = G_UNMERGE_VALUES [[BITCAST]](s64)
    ; CHECK-NEXT: [[LSHR5:%[0-9]+]]:gprregbank(s32) = G_LSHR [[UV13]], [[C1]](s32)
    ; CHECK-NEXT: [[SEXT_INREG7:%[0-9]+]]:gprregbank(s32) = G_SEXT_INREG [[LSHR5]], 8
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SEXT_INREG]](s32), implicit [[SEXT_INREG1]](s32), implicit [[SEXT_INREG2]](s32), implicit [[SEXT_INREG3]](s32), implicit [[SEXT_INREG4]](s32), implicit [[SEXT_INREG5]](s32), implicit [[SEXT_INREG6]](s32), implicit [[SEXT_INREG7]](s32)
    %0:_(<8 x s8>) = COPY $l0
    %1:_(s64) = G_BITCAST %0(<8 x s8>)
    %2:_(s32) = G_TRUNC %1(s64)
    %3:_(s32) = G_SEXT_INREG %2, 8
    %4:_(s32) = G_CONSTANT i32 8
    %5:_(s32), %6:_(s32) = G_UNMERGE_VALUES %1(s64)
    %7:_(s32) = G_LSHR %5, %4(s32)
    %8:_(s32) = G_CONSTANT i32 24
    %9:_(s32) = G_SHL %6, %8(s32)
    %10:_(s32) = G_OR %7, %9
    %11:_(s32) = G_SEXT_INREG %10, 8
    %12:_(s32) = G_CONSTANT i32 16
    %13:_(s32), %14:_(s32) = G_UNMERGE_VALUES %1(s64)
    %15:_(s32) = G_LSHR %13, %12(s32)
    %16:_(s32) = G_SHL %14, %12(s32)
    %17:_(s32) = G_OR %15, %16
    %18:_(s32) = G_SEXT_INREG %17, 8
    %19:_(s32), %20:_(s32) = G_UNMERGE_VALUES %1(s64)
    %21:_(s32) = G_LSHR %19, %8(s32)
    %22:_(s32) = G_SHL %20, %4(s32)
    %23:_(s32) = G_OR %21, %22
    %24:_(s32) = G_SEXT_INREG %23, 8
    %25:_(s32), %26:_(s32) = G_UNMERGE_VALUES %1(s64)
    %27:_(s32) = G_SEXT_INREG %26, 8
    %28:_(s32), %29:_(s32) = G_UNMERGE_VALUES %1(s64)
    %30:_(s32) = G_LSHR %29, %4(s32)
    %31:_(s32) = G_SEXT_INREG %30, 8
    %32:_(s32), %33:_(s32) = G_UNMERGE_VALUES %1(s64)
    %34:_(s32) = G_LSHR %33, %12(s32)
    %35:_(s32) = G_SEXT_INREG %34, 8
    %36:_(s32), %37:_(s32) = G_UNMERGE_VALUES %1(s64)
    %38:_(s32) = G_LSHR %37, %8(s32)
    %39:_(s32) = G_SEXT_INREG %38, 8
    PseudoRET implicit $lr, implicit %3(s32), implicit %11(s32), implicit %18(s32), implicit %24(s32), implicit %27(s32), implicit %31(s32), implicit %35(s32), implicit %39(s32)

...
