# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=COMMON
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=COMMON
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=COMMON

---
name: test_icmp_V16S32
legalized: true
body: |
  bb.0:
    liveins: $x0, $x1

    ; COMMON-LABEL: name: test_icmp_V16S32
    ; COMMON: liveins: $x0, $x1
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x1
    ; COMMON-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<16 x s32>), [[COPY1]]
    ; COMMON-NEXT: $r0 = COPY [[AIE_VECTOR_ICMP]](<32 x s1>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %6:_(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), %0(<16 x s32>), %1
    $r0 = COPY %6(<32 x s1>)
...

---
name: test_icmp_V32S16
legalized: true
body: |
  bb.0:
    liveins: $x0, $x1

    ; COMMON-LABEL: name: test_icmp_V32S16
    ; COMMON: liveins: $x0, $x1
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; COMMON-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:gprregbank(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<32 x s16>), [[COPY1]]
    ; COMMON-NEXT: $r0 = COPY [[AIE_VECTOR_ICMP]](<32 x s1>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), %0(<32 x s16>), %1
    $r0 = COPY %3(<32 x s1>)
...

---
name: test_icmp_V64S8
legalized: true
body: |
  bb.0:
    liveins: $x0, $x1

    ; COMMON-LABEL: name: test_icmp_V64S8
    ; COMMON: liveins: $x0, $x1
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; COMMON-NEXT: [[AIE_VECTOR_ICMP:%[0-9]+]]:gprregbank(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), [[COPY]](<64 x s8>), [[COPY1]]
    ; COMMON-NEXT: $l0 = COPY [[AIE_VECTOR_ICMP]](<64 x s1>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(<64 x s8>) = COPY $x1
    %3:_(<64 x s1>) = G_AIE_VECTOR_ICMP intpred(ne), %0(<64 x s8>), %1
    $l0 = COPY %3(<64 x s1>)
...



