# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK,AIE2P
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK,AIE2P
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK,AIE2PS

---
name:            v16s32Acc_trunc_v16s64_1024
legalized:       true
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: v16s32Acc_trunc_v16s64_1024
    ; AIE2P: [[DEF:%[0-9]+]]:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<16 x s32>) = G_TRUNC [[DEF]](<16 x s64>)
    ; AIE2P-NEXT: $bmll0 = COPY [[TRUNC]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; AIE2PS-LABEL: name: v16s32Acc_trunc_v16s64_1024
    ; AIE2PS: [[DEF:%[0-9]+]]:vregbank(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<16 x s32>) = G_TRUNC [[DEF]](<16 x s64>)
    ; AIE2PS-NEXT: $bmll0 = COPY [[TRUNC]](<16 x s32>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s64>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...
---
name:            v32s16Acc_trunc_v32s32_1024
legalized:       true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: v32s16Acc_trunc_v32s32_1024
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<32 x s16>) = G_TRUNC [[DEF]](<32 x s32>)
    ; CHECK-NEXT: $bmll0 = COPY [[TRUNC]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<32 x s32>) = G_IMPLICIT_DEF
    %0:_(<32 x s16>) = G_TRUNC %1(<32 x s32>)
    $bmll0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $bmll0
...
---
name:            v64s8Acc_trunc_v64s16_1024
legalized:       true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: v64s8Acc_trunc_v64s16_1024
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<64 x s8>) = G_TRUNC [[DEF]](<64 x s16>)
    ; CHECK-NEXT: $bmll0 = COPY [[TRUNC]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %0:_(<64 x s16>) = G_IMPLICIT_DEF
    %1:_(<64 x s8>) = G_TRUNC %0(<64 x s16>)
    $bmll0 = COPY %1(<64 x s8>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            v16s32Vec_trunc_v16s64_1024
legalized:       true
body:             |
  bb.0.entry:
    ; AIE2P-LABEL: name: v16s32Vec_trunc_v16s64_1024
    ; AIE2P: [[DEF:%[0-9]+]]:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2P-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<16 x s32>) = G_TRUNC [[DEF]](<16 x s64>)
    ; AIE2P-NEXT: $x0 = COPY [[TRUNC]](<16 x s32>)
    ; AIE2P-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; AIE2PS-LABEL: name: v16s32Vec_trunc_v16s64_1024
    ; AIE2PS: [[DEF:%[0-9]+]]:vregbank(<16 x s64>) = G_IMPLICIT_DEF
    ; AIE2PS-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<16 x s32>) = G_TRUNC [[DEF]](<16 x s64>)
    ; AIE2PS-NEXT: $x0 = COPY [[TRUNC]](<16 x s32>)
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s64>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_TRUNC %1(<16 x s64>)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name:            v32s16Vec_trunc_v32s32_1024
legalized:       true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: v32s16Vec_trunc_v32s32_1024
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<32 x s16>) = G_TRUNC [[DEF]](<32 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[TRUNC]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s32>) = G_IMPLICIT_DEF
    %0:_(<32 x s16>) = G_TRUNC %1(<32 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...
---
name:            v64s8Vec_trunc_v64s16_1024
legalized:       true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: v64s8Vec_trunc_v64s16_1024
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<64 x s8>) = G_TRUNC [[DEF]](<64 x s16>)
    ; CHECK-NEXT: $x0 = COPY [[TRUNC]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %0:_(<64 x s16>) = G_IMPLICIT_DEF
    %1:_(<64 x s8>) = G_TRUNC %0(<64 x s16>)
    $x0 = COPY %1(<64 x s8>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            v16s16_trunc_v16s32_vec512
legalized:       true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: v16s16_trunc_v16s32_vec512
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:vregbank(<16 x s16>) = G_TRUNC [[DEF]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[TRUNC]](<16 x s16>)
    %0:_(<16 x s32>) = G_IMPLICIT_DEF
    %1:_(<16 x s16>) = G_TRUNC %0(<16 x s32>)
    PseudoRET implicit $lr, implicit %1(<16 x s16>)
...
