# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=FAST %s
---
name:            test_v16acc32
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16acc32
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: $bmll0 = COPY [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_v16acc32
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: $bmll0 = COPY [[COPY]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %0:_(<16 x s32>) = COPY $bmll1
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_v32acc32
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v32acc32
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; GREEDY-NEXT: $cml0 = COPY [[COPY]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_v32acc32
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; FAST-NEXT: $cml0 = COPY [[COPY]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<32 x s32>) = COPY $cml1
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_v64acc32
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v64acc32
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: $dm0 = COPY [[COPY]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_v64acc32
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: $dm0 = COPY [[COPY]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:_(<64 x s32>) = COPY $dm1
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...
---

name:            test_v8acc64
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v8acc64
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll1
    ; GREEDY-NEXT: $bmll0 = COPY [[COPY]](<8 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_v8acc64
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll1
    ; FAST-NEXT: $bmll0 = COPY [[COPY]](<8 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %0:_(<8 x s64>) = COPY $bmll1
    $bmll0 = COPY %0(<8 x s64>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_v16acc64
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16acc64
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; GREEDY-NEXT: $cml0 = COPY [[COPY]](<16 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_v16acc64
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; FAST-NEXT: $cml0 = COPY [[COPY]](<16 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<16 x s64>) = COPY $cml1
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_v32acc64
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v32acc64
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm1
    ; GREEDY-NEXT: $dm0 = COPY [[COPY]](<32 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_v32acc64
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm1
    ; FAST-NEXT: $dm0 = COPY [[COPY]](<32 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:_(<32 x s64>) = COPY $dm1
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_v32acc32_store
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v32acc32_store
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (volatile store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $bmll0 = COPY [[LOAD]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_v32acc32_store
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (volatile store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $bmll0 = COPY [[LOAD]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = COPY $bmll1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    G_STORE %1(<16 x s32>), %2(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %2(p0) :: (volatile dereferenceable load (<16 x s32>))
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_v32acc32_copy
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: test_v32acc32_copy
    ; GREEDY: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:accregbank(<32 x s32>) = G_LOAD [[COPY]](p0) :: (load (<32 x s32>))
    ; GREEDY-NEXT: $cml0 = COPY [[LOAD]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_v32acc32_copy
    ; FAST: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:accregbank(<32 x s32>) = G_LOAD [[COPY]](p0) :: (load (<32 x s32>))
    ; FAST-NEXT: $cml0 = COPY [[LOAD]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(p0) = COPY $p0
    %0:_(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>))
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_v16acc32_spill_reload
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16acc32_spill_reload
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; GREEDY-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD1:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $bmll0 = COPY [[LOAD1]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_v16acc32_spill_reload
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; FAST-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s32>))
    ; FAST-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; FAST-NEXT: [[LOAD1:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $bmll0 = COPY [[LOAD1]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = COPY $bmll1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    G_STORE %1(<16 x s32>), %2(p0) :: (store (<16 x s32>))
    %4:_(<16 x s32>) = G_LOAD %2(p0) :: (dereferenceable load (<16 x s32>))
    G_STORE %4(<16 x s32>), %3(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s32>))
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_v16acc64_spill_reload
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16acc64_spill_reload
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; GREEDY-NEXT: G_STORE [[COPY]](<16 x s64>), [[FRAME_INDEX]](p0) :: (store (<16 x s64>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s64>))
    ; GREEDY-NEXT: G_STORE [[LOAD]](<16 x s64>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s64>))
    ; GREEDY-NEXT: [[LOAD1:%[0-9]+]]:accregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s64>))
    ; GREEDY-NEXT: $cml0 = COPY [[LOAD1]](<16 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_v16acc64_spill_reload
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; FAST-NEXT: G_STORE [[COPY]](<16 x s64>), [[FRAME_INDEX]](p0) :: (store (<16 x s64>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s64>))
    ; FAST-NEXT: G_STORE [[LOAD]](<16 x s64>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s64>))
    ; FAST-NEXT: [[LOAD1:%[0-9]+]]:accregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s64>))
    ; FAST-NEXT: $cml0 = COPY [[LOAD1]](<16 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<16 x s64>) = COPY $cml1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    G_STORE %1(<16 x s64>), %2(p0) :: (store (<16 x s64>))
    %4:_(<16 x s64>) = G_LOAD %2(p0) :: (dereferenceable load (<16 x s64>))
    G_STORE %4(<16 x s64>), %3(p0) :: (volatile store (<16 x s64>))
    %0:_(<16 x s64>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s64>))
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_broadcast_zero_to_v16acc64
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: test_broadcast_zero_to_v16acc64
    ; GREEDY: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast.zero.acc1024)
    ; GREEDY-NEXT: $cml0 = COPY [[INT]](<16 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_broadcast_zero_to_v16acc64
    ; FAST: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast.zero.acc1024)
    ; FAST-NEXT: $cml0 = COPY [[INT]](<16 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.vbroadcast.zero.acc1024)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_get_scd_v64acc32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0

    ; GREEDY-LABEL: name: test_get_scd_v64acc32
    ; GREEDY: liveins: $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.ACC2048), [[COPY]](s32), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_get_scd_v64acc32
    ; FAST: liveins: $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.ACC2048), [[COPY]](s32), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_get_scd_expand_v32acc32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0, $r0

    ; GREEDY-LABEL: name: test_get_scd_expand_v32acc32
    ; GREEDY: liveins: $p0, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>), [[INT1:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.ACC1024.incr), [[COPY]](s32)
    ; GREEDY-NEXT: G_STORE [[INT1]](s32), [[COPY1]](p0) :: (store (s32))
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<32 x s32>) = G_BITCAST [[INT]](<16 x s64>)
    ; GREEDY-NEXT: $cml0 = COPY [[BITCAST]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_get_scd_expand_v32acc32
    ; FAST: liveins: $p0, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>), [[INT1:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.ACC1024.incr), [[COPY]](s32)
    ; FAST-NEXT: G_STORE [[INT1]](s32), [[COPY1]](p0) :: (store (s32))
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<32 x s32>) = G_BITCAST [[INT]](<16 x s64>)
    ; FAST-NEXT: $cml0 = COPY [[BITCAST]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(s32) = COPY $r0
    %2:_(p0) = COPY $p0
    %3:_(<16 x s64>), %4:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.ACC1024.incr), %1(s32)
    G_STORE %4(s32), %2(p0) :: (store (s32))
    %0:_(<32 x s32>) = G_BITCAST %3(<16 x s64>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_get_scd_v32acc32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0

    ; GREEDY-LABEL: name: test_get_scd_v32acc32
    ; GREEDY: liveins: $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.lo), [[COPY]](s32)
    ; GREEDY-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_get_scd_v32acc32
    ; FAST: liveins: $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.lo), [[COPY]](s32)
    ; FAST-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.lo), %1(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            get_scd_v32acc32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0

    ; GREEDY-LABEL: name: get_scd_v32acc32
    ; GREEDY: liveins: $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.hi), [[COPY]](s32)
    ; GREEDY-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: get_scd_v32acc32
    ; FAST: liveins: $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.hi), [[COPY]](s32)
    ; FAST-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.expand.hi), %1(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_get_scd_v16acc32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0

    ; GREEDY-LABEL: name: test_get_scd_v16acc32
    ; GREEDY: liveins: $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.read.acc32), [[COPY]](s32)
    ; GREEDY-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_get_scd_v16acc32
    ; FAST: liveins: $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.read.acc32), [[COPY]](s32)
    ; FAST-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(s32) = COPY $r0
    %0:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.scd.read.acc32), %1(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_sups
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $wl0

    ; GREEDY-LABEL: name: test_sups
    ; GREEDY: liveins: $r0, $r1, $wl0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), [[COPY]](<16 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; GREEDY-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_sups
    ; FAST: liveins: $r0, $r1, $wl0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), [[COPY]](<16 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; FAST-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_ups_to_v16accfloat
legalized:       true
body:             |
  bb.1.entry:
    liveins: $wl0

    ; GREEDY-LABEL: name: test_ups_to_v16accfloat
    ; GREEDY: liveins: $wl0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v16bf16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; GREEDY-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_ups_to_v16accfloat
    ; FAST: liveins: $wl0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v16bf16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; FAST-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s16>) = COPY $wl0
    %0:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v16bf16.to.v16accfloat), %1(<16 x s16>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...

---
name:            accfloat_to_bfp16ebs16
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $dm0

    ; GREEDY-LABEL: name: accfloat_to_bfp16ebs16
    ; GREEDY: liveins: $dm0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64accfloat.to.v64bfp16ebs16), [[COPY]](<64 x s32>)
    ; GREEDY-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; GREEDY-NEXT: $e0 = COPY [[INT1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $e0
    ;
    ; FAST-LABEL: name: accfloat_to_bfp16ebs16
    ; FAST: liveins: $dm0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64accfloat.to.v64bfp16ebs16), [[COPY]](<64 x s32>)
    ; FAST-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; FAST-NEXT: $e0 = COPY [[INT1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $e0
    %1:_(<64 x s32>) = COPY $dm0
    %0:_(<64 x s8>), %4:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64accfloat.to.v64bfp16ebs16), %1(<64 x s32>)
    $x0 = COPY %0(<64 x s8>)
    $e0 = COPY %4(<8 x s8>)
    PseudoRET implicit $lr, implicit $x0, implicit $e0
...


---
name:            accfloat_to_bfp16ebs8
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $dm0

    ; GREEDY-LABEL: name: accfloat_to_bfp16ebs8
    ; GREEDY: liveins: $dm0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64accfloat.to.v64bfp16ebs8), [[COPY]](<64 x s32>)
    ; GREEDY-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; GREEDY-NEXT: $e0 = COPY [[INT1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $e0
    ;
    ; FAST-LABEL: name: accfloat_to_bfp16ebs8
    ; FAST: liveins: $dm0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64accfloat.to.v64bfp16ebs8), [[COPY]](<64 x s32>)
    ; FAST-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; FAST-NEXT: $e0 = COPY [[INT1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $e0
    %1:_(<64 x s32>) = COPY $dm0
    %0:_(<64 x s8>), %4:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64accfloat.to.v64bfp16ebs8), %1(<64 x s32>)
    $x0 = COPY %0(<64 x s8>)
    $e0 = COPY %4(<8 x s8>)
    PseudoRET implicit $lr, implicit $x0, implicit $e0
...

---
name:            bfp16ebs8_to_bfp16ebs16
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $dm0, $x1, $e1

    ; GREEDY-LABEL: name: bfp16ebs8_to_bfp16ebs16
    ; GREEDY: liveins: $dm0, $x1, $e1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64bfp16ebs8.to.v64bfp16ebs16), [[COPY1]](<64 x s8>), [[COPY2]](<8 x s8>)
    ; GREEDY-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; GREEDY-NEXT: $e0 = COPY [[INT1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $e0
    ;
    ; FAST-LABEL: name: bfp16ebs8_to_bfp16ebs16
    ; FAST: liveins: $dm0, $x1, $e1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:gprregbank(<8 x s8>) = COPY $e1
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64bfp16ebs8.to.v64bfp16ebs16), [[COPY1]](<64 x s8>), [[COPY2]](<8 x s8>)
    ; FAST-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; FAST-NEXT: $e0 = COPY [[INT1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $e0
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(<8 x s8>) = COPY $e1
    %0:_(<64 x s8>), %4:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v64bfp16ebs8.to.v64bfp16ebs16), %2(<64 x s8>), %3(<8 x s8>)
    $x0 = COPY %0(<64 x s8>)
    $e0 = COPY %4(<8 x s8>)
    PseudoRET implicit $lr, implicit $x0, implicit $e0
...


---
name:            test_ups_to_v32accfloat
legalized:       true
body:             |
  bb.1.entry:
    liveins: $x0

    ; GREEDY-LABEL: name: test_ups_to_v32accfloat
    ; GREEDY: liveins: $x0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v16float.to.v32accfloat), [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_ups_to_v32accfloat
    ; FAST: liveins: $x0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v16float.to.v32accfloat), [[COPY]](<16 x s32>)
    ; FAST-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<16 x s32>) = COPY $x0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.v16float.to.v32accfloat), %1(<16 x s32>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_mul_elem_64
legalized:       true
body:             |
  bb.1.entry:
    liveins: $y2, $y3

    ; GREEDY-LABEL: name: test_mul_elem_64
    ; GREEDY: liveins: $y2, $y3
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y2
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_mul_elem_64
    ; FAST: liveins: $y2, $y3
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y2
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y2
    %2:_(<64 x s16>) = COPY $y3
    %3:_(s32) = G_CONSTANT i32 60
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_negmul_elem_64
legalized:       true
body:             |
  bb.1.entry:
    liveins: $y2, $y3

    ; GREEDY-LABEL: name: test_negmul_elem_64
    ; GREEDY: liveins: $y2, $y3
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y2
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_negmul_elem_64
    ; FAST: liveins: $y2, $y3
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y2
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y2
    %2:_(<64 x s16>) = COPY $y3
    %3:_(s32) = G_CONSTANT i32 60
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_negmul_elem_32_conf
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $r2, $x0, $x2

    ; GREEDY-LABEL: name: test_negmul_elem_32_conf
    ; GREEDY: liveins: $r0, $r1, $r2, $x0, $x2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY2]](<32 x s16>), [[COPY1]](s32)
    ; GREEDY-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_negmul_elem_32_conf
    ; FAST: liveins: $r0, $r1, $r2, $x0, $x2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY2]](<32 x s16>), [[COPY1]](s32)
    ; FAST-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s16>) = COPY $x2
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %3(<32 x s16>), %2(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_put_mcd
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0

    ; GREEDY-LABEL: name: test_put_mcd
    ; GREEDY: liveins: $bmll0, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.mcd.write.acc32), [[BITCAST]](<8 x s64>), [[COPY1]](s32)
    ; GREEDY-NEXT: PseudoRET implicit $lr
    ;
    ; FAST-LABEL: name: test_put_mcd
    ; FAST: liveins: $bmll0, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; FAST-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.mcd.write.acc32), [[BITCAST]](<8 x s64>), [[COPY1]](s32)
    ; FAST-NEXT: PseudoRET implicit $lr
    %0:_(<16 x s32>) = COPY $bmll0
    %1:_(s32) = COPY $r0
    %2:_(<8 x s64>) = G_BITCAST %0(<16 x s32>)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.mcd.write.acc32), %2(<8 x s64>), %1(s32)
    PseudoRET implicit $lr

...
---
name:            test_lsrs
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $r1

    ; GREEDY-LABEL: name: test_lsrs
    ; GREEDY: liveins: $bmll0, $r0, $r1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), [[COPY]](<16 x s32>), [[COPY1]](s32), [[COPY2]](s32)
    ; GREEDY-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $wl0
    ;
    ; FAST-LABEL: name: test_lsrs
    ; FAST: liveins: $bmll0, $r0, $r1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), [[COPY]](<16 x s32>), [[COPY1]](s32), [[COPY2]](s32)
    ; FAST-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_srs_to_v64uint8
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm0, $r0

    ; GREEDY-LABEL: name: test_srs_to_v64uint8
    ; GREEDY: liveins: $dm0, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 63
    ; GREEDY-NEXT: [[AND:%[0-9]+]]:gprregbank(s32) = G_AND [[COPY1]], [[C1]]
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), [[COPY]](<64 x s32>), [[AND]](s32), [[C]](s32)
    ; GREEDY-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; FAST-LABEL: name: test_srs_to_v64uint8
    ; FAST: liveins: $dm0, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; FAST-NEXT: [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 63
    ; FAST-NEXT: [[AND:%[0-9]+]]:gprregbank(s32) = G_AND [[COPY1]], [[C1]]
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), [[COPY]](<64 x s32>), [[AND]](s32), [[C]](s32)
    ; FAST-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<64 x s32>) = COPY $dm0
    %3:_(s32) = COPY $r0
    %5:_(s32) = G_CONSTANT i32 0
    %6:_(s32) = G_CONSTANT i32 63
    %4:_(s32) = G_AND %3, %6
    %0:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v64.acc32.srs), %1(<64 x s32>), %4(s32), %5(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            test_to_v8float
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; GREEDY-LABEL: name: test_to_v8float
    ; GREEDY: liveins: $bmll0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v16accfloat.to.v8float), [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: $wl0 = COPY [[INT]](<8 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $wl0
    ;
    ; FAST-LABEL: name: test_to_v8float
    ; FAST: liveins: $bmll0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v16accfloat.to.v8float), [[COPY]](<16 x s32>)
    ; FAST-NEXT: $wl0 = COPY [[INT]](<8 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.v16accfloat.to.v8float), %1(<16 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_sub
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2

    ; GREEDY-LABEL: name: test_sub
    ; GREEDY: liveins: $dm1, $dm2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY]](<64 x s32>)
    ; GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY1]](<64 x s32>)
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.sub.conf), [[BITCAST]](<32 x s64>), [[BITCAST1]](<32 x s64>), [[C]](s32)
    ; GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<64 x s32>) = G_BITCAST [[INT]](<32 x s64>)
    ; GREEDY-NEXT: $dm0 = COPY [[BITCAST2]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_sub
    ; FAST: liveins: $dm1, $dm2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY]](<64 x s32>)
    ; FAST-NEXT: [[BITCAST1:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY1]](<64 x s32>)
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.sub.conf), [[BITCAST]](<32 x s64>), [[BITCAST1]](<32 x s64>), [[C]](s32)
    ; FAST-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<64 x s32>) = G_BITCAST [[INT]](<32 x s64>)
    ; FAST-NEXT: $dm0 = COPY [[BITCAST2]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(<64 x s32>) = COPY $dm2
    %6:_(s32) = G_CONSTANT i32 0
    %3:_(<32 x s64>) = G_BITCAST %1(<64 x s32>)
    %4:_(<32 x s64>) = G_BITCAST %2(<64 x s32>)
    %5:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.sub.conf), %3(<32 x s64>), %4(<32 x s64>), %6(s32)
    %0:_(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_add
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2

    ; GREEDY-LABEL: name: test_add
    ; GREEDY: liveins: $dm1, $dm2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[COPY]](<64 x s32>), [[COPY1]](<64 x s32>), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_add
    ; FAST: liveins: $dm1, $dm2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), [[COPY]](<64 x s32>), [[COPY1]](<64 x s32>), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(<64 x s32>) = COPY $dm2
    %3:_(s32) = G_CONSTANT i32 60
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.add.conf), %1(<64 x s32>), %2(<64 x s32>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmac_8x8_8x8
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2

    ; GREEDY-LABEL: name: test_addmac_8x8_8x8
    ; GREEDY: liveins: $dm1, $dm2, $x0, $x2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 8
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<64 x s8>)
    ; GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY2]](<64 x s32>)
    ; GREEDY-NEXT: [[BITCAST3:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY3]](<64 x s32>)
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.addmac.conf), [[BITCAST]](<16 x s32>), [[BITCAST1]](<32 x s16>), [[BITCAST2]](<32 x s64>), [[BITCAST3]](<32 x s64>), [[C]](s32)
    ; GREEDY-NEXT: [[BITCAST4:%[0-9]+]]:accregbank(<64 x s32>) = G_BITCAST [[INT]](<32 x s64>)
    ; GREEDY-NEXT: $dm0 = COPY [[BITCAST4]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_addmac_8x8_8x8
    ; FAST: liveins: $dm1, $dm2, $x0, $x2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x2
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 8
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY]](<64 x s8>)
    ; FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; FAST-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY2]](<64 x s32>)
    ; FAST-NEXT: [[BITCAST3:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY3]](<64 x s32>)
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.addmac.conf), [[BITCAST]](<16 x s32>), [[BITCAST1]](<32 x s16>), [[BITCAST2]](<32 x s64>), [[BITCAST3]](<32 x s64>), [[C]](s32)
    ; FAST-NEXT: [[BITCAST4:%[0-9]+]]:accregbank(<64 x s32>) = G_BITCAST [[INT]](<32 x s64>)
    ; FAST-NEXT: $dm0 = COPY [[BITCAST4]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x2
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %10:_(s32) = G_CONSTANT i32 8
    %5:_(<16 x s32>) = G_BITCAST %1(<64 x s8>)
    %6:_(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %7:_(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:_(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.addmac.conf), %5(<16 x s32>), %6(<32 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:_(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmac_elem_64
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $r1, $y2, $y3

    ; GREEDY-LABEL: name: test_addmac_elem_64
    ; GREEDY: liveins: $dm1, $dm2, $r0, $r1, $y2, $y3
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y2
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY4:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY2]](<64 x s16>), [[COPY3]](<64 x s32>), [[COPY4]](<64 x s32>), [[COPY1]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_addmac_elem_64
    ; FAST: liveins: $dm1, $dm2, $r0, $r1, $y2, $y3
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y2
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY4:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY2]](<64 x s16>), [[COPY3]](<64 x s32>), [[COPY4]](<64 x s32>), [[COPY1]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y2
    %2:_(s32) = COPY $r0
    %3:_(<64 x s16>) = COPY $y3
    %5:_(<64 x s32>) = COPY $dm1
    %6:_(<64 x s32>) = COPY $dm2
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %3(<64 x s16>), %5(<64 x s32>), %6(<64 x s32>), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmsc_8x8_8x8
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2

    ; GREEDY-LABEL: name: test_addmsc_8x8_8x8
    ; GREEDY: liveins: $dm1, $dm2, $x0, $y2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<128 x s8>) = COPY $y2
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 264
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[COPY]](<128 x s8>)
    ; GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY2]](<64 x s32>)
    ; GREEDY-NEXT: [[BITCAST3:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY3]](<64 x s32>)
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.addmsc.conf), [[BITCAST]](<32 x s32>), [[BITCAST1]](<32 x s16>), [[BITCAST2]](<32 x s64>), [[BITCAST3]](<32 x s64>), [[C]](s32)
    ; GREEDY-NEXT: [[BITCAST4:%[0-9]+]]:accregbank(<64 x s32>) = G_BITCAST [[INT]](<32 x s64>)
    ; GREEDY-NEXT: $dm0 = COPY [[BITCAST4]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_addmsc_8x8_8x8
    ; FAST: liveins: $dm1, $dm2, $x0, $y2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<128 x s8>) = COPY $y2
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 264
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[COPY]](<128 x s8>)
    ; FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[COPY1]](<64 x s8>)
    ; FAST-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY2]](<64 x s32>)
    ; FAST-NEXT: [[BITCAST3:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[COPY3]](<64 x s32>)
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.addmsc.conf), [[BITCAST]](<32 x s32>), [[BITCAST1]](<32 x s16>), [[BITCAST2]](<32 x s64>), [[BITCAST3]](<32 x s64>), [[C]](s32)
    ; FAST-NEXT: [[BITCAST4:%[0-9]+]]:accregbank(<64 x s32>) = G_BITCAST [[INT]](<32 x s64>)
    ; FAST-NEXT: $dm0 = COPY [[BITCAST4]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<128 x s8>) = COPY $y2
    %2:_(<64 x s8>) = COPY $x0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %10:_(s32) = G_CONSTANT i32 264
    %5:_(<32 x s32>) = G_BITCAST %1(<128 x s8>)
    %6:_(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %7:_(<32 x s64>) = G_BITCAST %3(<64 x s32>)
    %8:_(<32 x s64>) = G_BITCAST %4(<64 x s32>)
    %9:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I512.ACC2048.addmsc.conf), %5(<32 x s32>), %6(<32 x s16>), %7(<32 x s64>), %8(<32 x s64>), %10(s32)
    %0:_(<64 x s32>) = G_BITCAST %9(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_addmsc_elem_64
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2

    ; GREEDY-LABEL: name: test_addmsc_elem_64
    ; GREEDY: liveins: $dm1, $dm2, $x0, $x2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_addmsc_elem_64
    ; FAST: liveins: $dm1, $dm2, $x0, $x2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x2
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = G_CONSTANT i32 60
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_mac_elem_16
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll1, $x0, $x2

    ; GREEDY-LABEL: name: test_mac_elem_16
    ; GREEDY: liveins: $bmll1, $x0, $x2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<16 x s32>), [[C]](s32)
    ; GREEDY-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_mac_elem_16
    ; FAST: liveins: $bmll1, $x0, $x2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<16 x s32>), [[C]](s32)
    ; FAST-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x2
    %3:_(<16 x s32>) = COPY $bmll1
    %4:_(s32) = G_CONSTANT i32 60
    %0:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC512.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<16 x s32>), %4(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_mac_elem_64
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2

    ; GREEDY-LABEL: name: test_mac_elem_64
    ; GREEDY: liveins: $dm1, $x0, $x2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_mac_elem_64
    ; FAST: liveins: $dm1, $x0, $x2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x2
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = G_CONSTANT i32 60
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC2048.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_mac_elem_16_2
legalized:       true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $r1, $x0, $x2

    ; GREEDY-LABEL: name: test_mac_elem_16_2
    ; GREEDY: liveins: $cml1, $r0, $r1, $x0, $x2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC1024.mac.conf), [[COPY]](<32 x s16>), [[COPY2]](<32 x s16>), [[COPY3]](<16 x s64>), [[COPY1]](s32)
    ; GREEDY-NEXT: $cml0 = COPY [[INT]](<16 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_mac_elem_16_2
    ; FAST: liveins: $cml1, $r0, $r1, $x0, $x2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC1024.mac.conf), [[COPY]](<32 x s16>), [[COPY2]](<32 x s16>), [[COPY3]](<16 x s64>), [[COPY1]](s32)
    ; FAST-NEXT: $cml0 = COPY [[INT]](<16 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s16>) = COPY $x2
    %5:_(<16 x s64>) = COPY $cml1
    %0:_(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC1024.mac.conf), %1(<32 x s16>), %3(<32 x s16>), %5(<16 x s64>), %2(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_msc_4x2_2x8
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3

    ; GREEDY-LABEL: name: test_msc_4x2_2x8
    ; GREEDY: liveins: $dm1, $y2, $y3
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s32>) = COPY $y2
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 2
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.msc.conf), [[COPY]](<32 x s32>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s64>), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_msc_4x2_2x8
    ; FAST: liveins: $dm1, $y2, $y3
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s32>) = COPY $y2
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y3
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm1
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 2
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.msc.conf), [[COPY]](<32 x s32>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s64>), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s32>) = COPY $y2
    %2:_(<64 x s16>) = COPY $y3
    %3:_(<32 x s64>) = COPY $dm1
    %4:_(s32) = G_CONSTANT i32 2
    %0:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I1024.I1024.ACC2048.msc.conf), %1(<32 x s32>), %2(<64 x s16>), %3(<32 x s64>), %4(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_neg
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1

    ; GREEDY-LABEL: name: test_neg
    ; GREEDY: liveins: $dm1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.neg.conf), [[COPY]](<64 x s32>), [[C]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_neg
    ; FAST: liveins: $dm1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 60
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.neg.conf), [[COPY]](<64 x s32>), [[C]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(s32) = G_CONSTANT i32 60
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.neg.conf), %1(<64 x s32>), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_neg_conf
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $r1

    ; GREEDY-LABEL: name: test_neg_conf
    ; GREEDY: liveins: $dm1, $r0, $r1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.neg.conf), [[COPY]](<64 x s32>), [[COPY1]](s32)
    ; GREEDY-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_neg_conf
    ; FAST: liveins: $dm1, $r0, $r1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.neg.conf), [[COPY]](<64 x s32>), [[COPY1]](s32)
    ; FAST-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.ACC2048.accfloat.neg.conf), %1(<64 x s32>), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_exp2_accfloat
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; GREEDY-LABEL: name: test_exp2_accfloat
    ; GREEDY: liveins: $bmll0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.exp2), [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $wl0
    ;
    ; FAST-LABEL: name: test_exp2_accfloat
    ; FAST: liveins: $bmll0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.exp2), [[COPY]](<16 x s32>)
    ; FAST-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.exp2), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_tanh_accfloat
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; GREEDY-LABEL: name: test_tanh_accfloat
    ; GREEDY: liveins: $bmll0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.tanh), [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $wl0
    ;
    ; FAST-LABEL: name: test_tanh_accfloat
    ; FAST: liveins: $bmll0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.tanh), [[COPY]](<16 x s32>)
    ; FAST-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2p.tanh), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            offset_load_acc512
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0
    ; GREEDY-LABEL: name: offset_load_acc512
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (<8 x s64>))
    ; GREEDY-NEXT: $bmll0 = COPY [[AIE_OFFSET_LOAD]](<8 x s64>)
    ;
    ; FAST-LABEL: name: offset_load_acc512
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:accregbank(<8 x s64>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (<8 x s64>))
    ; FAST-NEXT: $bmll0 = COPY [[AIE_OFFSET_LOAD]](<8 x s64>)
    %1:_(p0) = COPY $p0
    %2:_(s20) = G_CONSTANT i20 448
    %0:_(<8 x s64>) = G_AIE_OFFSET_LOAD %1:_(p0), %2:_(s20) :: (load (<8 x s64>))
    $bmll0 = COPY %0:_(<8 x s64>)
...

---
name:            offset_store_acc512
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0
    ; GREEDY-LABEL: name: offset_store_acc512
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: G_AIE_OFFSET_STORE [[COPY]](<16 x s32>), [[COPY1]](p0), [[C]](s20) :: (store (<16 x s32>))
    ;
    ; FAST-LABEL: name: offset_store_acc512
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: G_AIE_OFFSET_STORE [[COPY]](<16 x s32>), [[COPY1]](p0), [[C]](s20) :: (store (<16 x s32>))
    %0:_(<16 x s32>) = COPY $bmll0
    %1:_(p0) = COPY $p0
    %2:_(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:_(<16 x s32>), %1:_(p0), %2:_(s20) :: (store (<16 x s32>))
...
---

name: post-inc-acc512-load
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; GREEDY-LABEL: name: post-inc-acc512-load
    ; GREEDY: liveins: $p0, $r0, $r1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; GREEDY-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<16 x s32>) from stack - 64)
    ; GREEDY-NEXT: [[AIE_POSTINC_LOAD2:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_LOAD3:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[AIE_POSTINC_LOAD1]], [[C]](s20) :: (load (<16 x s32>) from stack - 64)
    ; GREEDY-NEXT: $bmll0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; GREEDY-NEXT: $bmll1 = COPY [[AIE_POSTINC_LOAD2]](<16 x s32>)
    ;
    ; FAST-LABEL: name: post-inc-acc512-load
    ; FAST: liveins: $p0, $r0, $r1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; FAST-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<16 x s32>) from stack - 64)
    ; FAST-NEXT: [[AIE_POSTINC_LOAD2:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_LOAD3:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[AIE_POSTINC_LOAD1]], [[C]](s20) :: (load (<16 x s32>) from stack - 64)
    ; FAST-NEXT: $bmll0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; FAST-NEXT: $bmll1 = COPY [[AIE_POSTINC_LOAD2]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %7:_(s20) = G_TRUNC %1
    %8:_(s20) = G_CONSTANT i20 448
    %9:_(s20) = G_CONSTANT i20 -512
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_CONSTANT i20 32
    %12:_(s20) = G_CONSTANT i20 512
    %13:_(<16 x s32>), %15:_(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>) from stack - 64)
    %14:_(<16 x s32>), %16:_(p0) = G_AIE_POSTINC_LOAD %15, %8 :: (load (<16 x s32>) from stack - 64)
    $bmll0 = COPY %13:_(<16 x s32>)
    $bmll1 = COPY %14:_(<16 x s32>)
...

---
name: post-inc-acc2048-load
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; GREEDY-LABEL: name: post-inc-acc2048-load
    ; GREEDY: liveins: $p0, $r0, $r1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; GREEDY-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:accregbank(<64 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<64 x s32>) from stack - 64, align 64, basealign 256)
    ; GREEDY-NEXT: [[AIE_POSTINC_LOAD2:%[0-9]+]]:accregbank(<64 x s32>), [[AIE_POSTINC_LOAD3:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[AIE_POSTINC_LOAD1]], [[C]](s20) :: (load (<64 x s32>) from stack - 64, align 64, basealign 256)
    ; GREEDY-NEXT: $dm0 = COPY [[AIE_POSTINC_LOAD]](<64 x s32>)
    ; GREEDY-NEXT: $dm1 = COPY [[AIE_POSTINC_LOAD2]](<64 x s32>)
    ;
    ; FAST-LABEL: name: post-inc-acc2048-load
    ; FAST: liveins: $p0, $r0, $r1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; FAST-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:accregbank(<64 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<64 x s32>) from stack - 64, align 64, basealign 256)
    ; FAST-NEXT: [[AIE_POSTINC_LOAD2:%[0-9]+]]:accregbank(<64 x s32>), [[AIE_POSTINC_LOAD3:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[AIE_POSTINC_LOAD1]], [[C]](s20) :: (load (<64 x s32>) from stack - 64, align 64, basealign 256)
    ; FAST-NEXT: $dm0 = COPY [[AIE_POSTINC_LOAD]](<64 x s32>)
    ; FAST-NEXT: $dm1 = COPY [[AIE_POSTINC_LOAD2]](<64 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %7:_(s20) = G_TRUNC %1
    %8:_(s20) = G_CONSTANT i20 448
    %9:_(s20) = G_CONSTANT i20 -512
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_CONSTANT i20 32
    %12:_(s20) = G_CONSTANT i20 512
    %13:_(<64 x s32>), %15:_(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<64 x s32>) from stack - 64)
    %14:_(<64 x s32>), %16:_(p0) = G_AIE_POSTINC_LOAD %15, %8 :: (load (<64 x s32>) from stack - 64)
    $dm0 = COPY %13:_(<64 x s32>)
    $dm1 = COPY %14:_(<64 x s32>)
...

---
name: post-inc-2d-acc-load-bm
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ; GREEDY-LABEL: name: post-inc-2d-acc-load-bm
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[AIE_POSTINC_2D_LOAD:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_2D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_LOAD2:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (load (<16 x s32>))
    ; GREEDY-NEXT: $bmll0 = COPY [[AIE_POSTINC_2D_LOAD]](<16 x s32>)
    ;
    ; FAST-LABEL: name: post-inc-2d-acc-load-bm
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[AIE_POSTINC_2D_LOAD:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_2D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_LOAD2:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (load (<16 x s32>))
    ; FAST-NEXT: $bmll0 = COPY [[AIE_POSTINC_2D_LOAD]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(<16 x s32>), %6:_(p0), %7:_(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    $bmll0 = COPY %5:_(<16 x s32>)
...

---
name: post-inc-3d-acc-load-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ; GREEDY-LABEL: name: post-inc-3d-acc-load-512
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; GREEDY-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; GREEDY-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; GREEDY-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (load (<16 x s32>))
    ; GREEDY-NEXT: $bmll0 = COPY [[AIE_POSTINC_3D_LOAD]](<16 x s32>)
    ;
    ; FAST-LABEL: name: post-inc-3d-acc-load-512
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; FAST-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; FAST-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; FAST-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:accregbank(<16 x s32>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (load (<16 x s32>))
    ; FAST-NEXT: $bmll0 = COPY [[AIE_POSTINC_3D_LOAD]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(s20) = G_CONSTANT i20 5
    %6:_(s20) = G_CONSTANT i20 6
    %7:_(s20) = G_CONSTANT i20 7
    %8:_(<16 x s32>), %9:_(p0), %10:_(s20), %11:_(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<16 x s32>))
    $bmll0 = COPY %8:_(<16 x s32>)

...
---
name:            test_v32acc32_postinc_store
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v32acc32_postinc_store
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; GREEDY-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $bmll0 = COPY [[LOAD]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_v32acc32_postinc_store
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; FAST-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $bmll0 = COPY [[LOAD]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = COPY $bmll1
    %2:_(p0) = COPY $p1
    %3:_(s20) = G_CONSTANT i20 128
    %5:_(p0) = G_AIE_POSTINC_STORE %1(<16 x s32>), %2, %3(s20) :: (store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %5(p0) :: (volatile dereferenceable load (<16 x s32>))
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_v16acc32_spill_reload_postinc
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16acc32_spill_reload_postinc
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; GREEDY-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD1:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $bmll0 = COPY [[LOAD1]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: test_v16acc32_spill_reload_postinc
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; FAST-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (dereferenceable load (<16 x s32>))
    ; FAST-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; FAST-NEXT: [[LOAD1:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $bmll0 = COPY [[LOAD1]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = COPY $bmll1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    %5:_(p0) = COPY $p1
    %6:_(s20) = G_CONSTANT i20 128
    %7:_(p0) = G_AIE_POSTINC_STORE %1(<16 x s32>), %5, %6(s20) :: (store (<16 x s32>))
    %4:_(<16 x s32>) = G_LOAD %7(p0) :: (dereferenceable load (<16 x s32>))
    G_STORE %4(<16 x s32>), %3(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s32>))
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...

---
name: post-inc-acc-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $bmll0
    ; GREEDY-LABEL: name: post-inc-acc-store-512
    ; GREEDY: liveins: $p0, $r0, $r1, $bmll0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY2]](<16 x s32>), [[COPY]], [[TRUNC]](s20) :: (store (<16 x s32>) into stack - 64)
    ;
    ; FAST-LABEL: name: post-inc-acc-store-512
    ; FAST: liveins: $p0, $r0, $r1, $bmll0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY2]](<16 x s32>), [[COPY]], [[TRUNC]](s20) :: (store (<16 x s32>) into stack - 64)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %7:_(s20) = G_TRUNC %1
    %8:_(s20) = G_CONSTANT i20 448
    %9:_(s20) = G_CONSTANT i20 -512
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_CONSTANT i20 32
    %12:_(s20) = G_CONSTANT i20 512
    %13:_(<16 x s32>) = COPY $bmll0
    %19:_(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<16 x s32>) into stack - 64)
...

---
name: post-inc-2d-acc-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; GREEDY-LABEL: name: post-inc-2d-acc-store-512
    ; GREEDY: liveins: $p0, $bmll0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[AIE_POSTINC_2D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_STORE1:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (store (<16 x s32>))
    ; GREEDY-NEXT: PseudoRET implicit $lr
    ;
    ; FAST-LABEL: name: post-inc-2d-acc-store-512
    ; FAST: liveins: $p0, $bmll0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[AIE_POSTINC_2D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_STORE1:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (store (<16 x s32>))
    ; FAST-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(<16 x s32>) = COPY $bmll0
    %6:_(p0), %7:_(s20) = G_AIE_POSTINC_2D_STORE %5, %0, %1, %2, %3, %4 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name: post-inc-3d-vector-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; GREEDY-LABEL: name: post-inc-3d-vector-store-512
    ; GREEDY: liveins: $p0, $bmll0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; GREEDY-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; GREEDY-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (store (<16 x s32>))
    ; GREEDY-NEXT: PseudoRET implicit $lr
    ;
    ; FAST-LABEL: name: post-inc-3d-vector-store-512
    ; FAST: liveins: $p0, $bmll0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; FAST-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; FAST-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (store (<16 x s32>))
    ; FAST-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(s20) = G_CONSTANT i20 5
    %6:_(s20) = G_CONSTANT i20 6
    %7:_(s20) = G_CONSTANT i20 7
    %8:_(<16 x s32>) = COPY $bmll0
    %9:_(p0), %10:_(s20), %11:_(s20) = G_AIE_POSTINC_3D_STORE %8, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...
