# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefixes=COMMON,GREEDY %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefixes=COMMON,FAST %s
---
name:            vconcat_1024_acc64
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll1, $bmll2

    ; COMMON-LABEL: name: vconcat_1024_acc64
    ; COMMON: liveins: $bmll1, $bmll2
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll1
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll2
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<16 x s64>) = G_CONCAT_VECTORS [[COPY]](<8 x s64>), [[COPY1]](<8 x s64>)
    ; COMMON-NEXT: $cml0 = COPY [[CONCAT_VECTORS]](<16 x s64>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<8 x s64>) = COPY $bmll1
    %2:_(<8 x s64>) = COPY $bmll2
    %3:_(<16 x s64>) = G_CONCAT_VECTORS %1(<8 x s64>), %2(<8 x s64>)
    $cml0 = COPY %3(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            vconcat_1024_acc32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll1, $bmll2

    ; COMMON-LABEL: name: vconcat_1024_acc32
    ; COMMON: liveins: $bmll1, $bmll2
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll2
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; COMMON-NEXT: $cml0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<16 x s32>) = COPY $bmll1
    %2:_(<16 x s32>) = COPY $bmll2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    $cml0 = COPY %3(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            vconcat_2048_acc64
legalized:       true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2

    ; COMMON-LABEL: name: vconcat_2048_acc64
    ; COMMON: liveins: $cml1, $cml2
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml2
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<32 x s64>) = G_CONCAT_VECTORS [[COPY]](<16 x s64>), [[COPY1]](<16 x s64>)
    ; COMMON-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<32 x s64>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<16 x s64>) = COPY $cml1
    %2:_(<16 x s64>) = COPY $cml2
    %3:_(<32 x s64>) = G_CONCAT_VECTORS %1(<16 x s64>), %2(<16 x s64>)
    $dm0 = COPY %3(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            vconcat_2048_acc32
legalized:       true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2

    ; COMMON-LABEL: name: vconcat_2048_acc32
    ; COMMON: liveins: $cml1, $cml2
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<64 x s32>) = G_CONCAT_VECTORS [[COPY]](<32 x s32>), [[COPY1]](<32 x s32>)
    ; COMMON-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<64 x s32>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s32>) = COPY $cml1
    %2:_(<32 x s32>) = COPY $cml2
    %3:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    $dm0 = COPY %3(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            vconcat_2048_vec1024
legalized:       true
body:             |
  bb.1.entry:
    ; COMMON-LABEL: name: vconcat_2048_vec1024
    ; COMMON: [[COPY:%[0-9]+]]:vregbank(<32 x s32>) = COPY $y0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s32>) = COPY $y1
    ; COMMON-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[COPY]](<32 x s32>)
    ; COMMON-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[COPY1]](<32 x s32>)
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<64 x s32>) = G_CONCAT_VECTORS [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>)
    ; COMMON-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<64 x s32>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %3:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %2(<32 x s32>)
    $dm0 = COPY %3(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...
---
name:            vconcat_1024_acc512
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: vconcat_1024_acc512
    ; GREEDY: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY2]](<16 x s32>), [[COPY3]](<16 x s32>)
    ; GREEDY-NEXT: $y0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $y0
    ;
    ; FAST-LABEL: name: vconcat_1024_acc512
    ; FAST: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; FAST-NEXT: $y0 = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:_(<16 x s32>) = COPY $bmll0
    %2:_(<16 x s32>) = COPY $bmll1
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    $y0 = COPY %3(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...
---
name:            regbank_concat_vector_indirect_accuse_2048bits
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x0, $x2, $x4, $x6

    ; COMMON-LABEL: name: regbank_concat_vector_indirect_accuse_2048bits
    ; COMMON: liveins: $r0, $r1, $x0, $x2, $x4, $x6
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; COMMON-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x4
    ; COMMON-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x6
    ; COMMON-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; COMMON-NEXT: [[COPY5:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; COMMON-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 18
    ; COMMON-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), [[COPY]](<32 x s16>), [[COPY4]](s32), [[COPY5]](s32)
    ; COMMON-NEXT: [[INT1:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), [[COPY1]](<32 x s16>), [[COPY4]](s32), [[COPY5]](s32)
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<64 x s32>) = G_CONCAT_VECTORS [[INT]](<32 x s32>), [[INT1]](<32 x s32>)
    ; COMMON-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[CONCAT_VECTORS]](<64 x s32>)
    ; COMMON-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY2]](<32 x s16>)
    ; COMMON-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[COPY3]](<64 x s8>)
    ; COMMON-NEXT: [[INT2:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), [[BITCAST1]](<16 x s32>), [[BITCAST2]](<32 x s16>), [[BITCAST]](<32 x s64>), [[C]](s32)
    ; COMMON-NEXT: $dm0 = COPY [[INT2]](<32 x s64>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x2
    %3:_(<32 x s16>) = COPY $x4
    %4:_(<64 x s8>) = COPY $x6
    %5:_(s32) = COPY $r0
    %6:_(s32) = COPY $r1
    %13:_(s32) = G_CONSTANT i32 18
    %7:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %1(<32 x s16>), %5(s32), %6(s32)
    %8:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %2(<32 x s16>), %5(s32), %6(s32)
    %14:_(<64 x s32>) = G_CONCAT_VECTORS %7(<32 x s32>), %8(<32 x s32>)
    %10:_(<32 x s64>) = G_BITCAST %14(<64 x s32>)
    %11:_(<16 x s32>) = G_BITCAST %3(<32 x s16>)
    %12:_(<32 x s16>) = G_BITCAST %4(<64 x s8>)
    %0:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), %11(<16 x s32>), %12(<32 x s16>), %10(<32 x s64>), %13(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            regbank_concat_vector_indirect_accuse_1024bits
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: regbank_concat_vector_indirect_accuse_1024bits
    ; GREEDY: [[DEF:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[DEF1]](<16 x s32>)
    ; GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<16 x s64>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), [[BITCAST]](<16 x s64>), [[DEF2]](s32), [[DEF3]](s32)
    ; GREEDY-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $wl0
    ;
    ; FAST-LABEL: name: regbank_concat_vector_indirect_accuse_1024bits
    ; FAST: [[DEF:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s64>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY [[BITCAST]](<16 x s64>)
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), [[COPY]](<16 x s64>), [[DEF2]](s32), [[DEF3]](s32)
    ; FAST-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    %4:_(<16 x s64>) = G_BITCAST %3(<32 x s32>)
    %5:_(s32) = G_IMPLICIT_DEF
    %6:_(s32) = G_IMPLICIT_DEF
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I256.v16.acc64.srs), %4(<16 x s64>), %5(s32), %6(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            regbank_concat_vector_indirect_accuse_multi_bitcast_1024bits
legalized:       true
regBankSelected: false
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: regbank_concat_vector_indirect_accuse_multi_bitcast_1024bits
    ; GREEDY: [[DEF:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[DEF]](<16 x s32>)
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[DEF1]](<16 x s32>)
    ; GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<32 x s32>) = G_CONCAT_VECTORS [[COPY]](<16 x s32>), [[COPY1]](<16 x s32>)
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<16 x s64>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:accregbank(<32 x s32>) = G_BITCAST [[BITCAST]](<16 x s64>)
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), [[BITCAST1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s32)
    ; GREEDY-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $x0
    ;
    ; FAST-LABEL: name: regbank_concat_vector_indirect_accuse_multi_bitcast_1024bits
    ; FAST: [[DEF:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<32 x s32>) = G_CONCAT_VECTORS [[DEF]](<16 x s32>), [[DEF1]](<16 x s32>)
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<16 x s64>) = G_BITCAST [[CONCAT_VECTORS]](<32 x s32>)
    ; FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[BITCAST]](<16 x s64>)
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[BITCAST1]](<32 x s32>)
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), [[COPY]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s32)
    ; FAST-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %2:_(<16 x s32>) = G_IMPLICIT_DEF
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    %4:_(<16 x s64>) = G_BITCAST %3(<32 x s32>)
    %12:_(<32 x s32>) = G_BITCAST %4(<16 x s64>)
    %5:_(s32) = G_IMPLICIT_DEF
    %6:_(s32) = G_IMPLICIT_DEF
    %0:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.v32.acc32.srs), %12(<32 x s32>), %5(s32), %6(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

#
# %19 = concat
# %11 = bitcast %19
# %14 = mac %11
# %17 = mac %11
#
...
---
name:            regbank_test_multiuser_of_indirect_op
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x0, $x2, $x4, $x6, $x8

    ; COMMON-LABEL: name: regbank_test_multiuser_of_indirect_op
    ; COMMON: liveins: $r0, $r1, $x0, $x2, $x4, $x6, $x8
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x2
    ; COMMON-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x4
    ; COMMON-NEXT: [[COPY3:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x6
    ; COMMON-NEXT: [[COPY4:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x8
    ; COMMON-NEXT: [[COPY5:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; COMMON-NEXT: [[COPY6:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; COMMON-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 18
    ; COMMON-NEXT: [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 2
    ; COMMON-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), [[COPY]](<32 x s16>), [[COPY5]](s32), [[COPY6]](s32)
    ; COMMON-NEXT: [[INT1:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), [[COPY1]](<32 x s16>), [[COPY5]](s32), [[COPY6]](s32)
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<64 x s32>) = G_CONCAT_VECTORS [[INT]](<32 x s32>), [[INT1]](<32 x s32>)
    ; COMMON-NEXT: [[BITCAST:%[0-9]+]]:accregbank(<32 x s64>) = G_BITCAST [[CONCAT_VECTORS]](<64 x s32>)
    ; COMMON-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<16 x s32>) = G_BITCAST [[COPY2]](<32 x s16>)
    ; COMMON-NEXT: [[BITCAST2:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[COPY3]](<64 x s8>)
    ; COMMON-NEXT: [[INT2:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), [[BITCAST1]](<16 x s32>), [[BITCAST2]](<32 x s16>), [[BITCAST]](<32 x s64>), [[C]](s32)
    ; COMMON-NEXT: [[BITCAST3:%[0-9]+]]:vregbank(<32 x s16>) = G_BITCAST [[COPY4]](<64 x s8>)
    ; COMMON-NEXT: [[INT3:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), [[BITCAST1]](<16 x s32>), [[BITCAST3]](<32 x s16>), [[BITCAST]](<32 x s64>), [[C]](s32)
    ; COMMON-NEXT: [[INT4:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), [[INT2]](<32 x s64>), [[INT3]](<32 x s64>), [[C1]](s32)
    ; COMMON-NEXT: $dm0 = COPY [[INT4]](<32 x s64>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x2
    %3:_(<32 x s16>) = COPY $x4
    %4:_(<64 x s8>) = COPY $x6
    %5:_(<64 x s8>) = COPY $x8
    %6:_(s32) = COPY $r0
    %7:_(s32) = COPY $r1
    %15:_(s32) = G_CONSTANT i32 18
    %18:_(s32) = G_CONSTANT i32 2
    %8:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %1(<32 x s16>), %6(s32), %7(s32)
    %9:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I512.ups), %2(<32 x s16>), %6(s32), %7(s32)
    %19:_(<64 x s32>) = G_CONCAT_VECTORS %8(<32 x s32>), %9(<32 x s32>)
    %11:_(<32 x s64>) = G_BITCAST %19(<64 x s32>)
    %12:_(<16 x s32>) = G_BITCAST %3(<32 x s16>)
    %13:_(<32 x s16>) = G_BITCAST %4(<64 x s8>)
    %14:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), %12(<16 x s32>), %13(<32 x s16>), %11(<32 x s64>), %15(s32)
    %16:_(<32 x s16>) = G_BITCAST %5(<64 x s8>)
    %17:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mac.conf), %12(<16 x s32>), %16(<32 x s16>), %11(<32 x s64>), %15(s32)
    %0:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.ACC2048.add.conf), %14(<32 x s64>), %17(<32 x s64>), %18(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            vconcat_512_accUse
legalized:       true
body:             |
  bb.1.entry:
    liveins:
    ; COMMON-LABEL: name: vconcat_512_accUse
    ; COMMON: [[DEF:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; COMMON-NEXT: [[UV:%[0-9]+]]:vregbank(<8 x s32>), [[UV1:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[DEF]](<16 x s32>)
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[UV]](<8 x s32>), [[UV1]](<8 x s32>)
    ; COMMON-NEXT: $bmll0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %2:_(<8 x s32>), %4:_(<8 x s32>) = G_UNMERGE_VALUES %1(<16 x s32>)
    %3:_(<16 x s32>) = G_CONCAT_VECTORS %2(<8 x s32>), %4(<8 x s32>)
    $bmll0 = COPY %3(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...
---
name:            vconcat_512_vecUse
legalized:       true
body:             |
  bb.1.entry:
    liveins:
    ; COMMON-LABEL: name: vconcat_512_vecUse
    ; COMMON: [[DEF:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; COMMON-NEXT: [[UV:%[0-9]+]]:vregbank(<8 x s32>), [[UV1:%[0-9]+]]:vregbank(<8 x s32>) = G_UNMERGE_VALUES [[DEF]](<16 x s32>)
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<16 x s32>) = G_CONCAT_VECTORS [[UV]](<8 x s32>), [[UV1]](<8 x s32>)
    ; COMMON-NEXT: $x0 = COPY [[CONCAT_VECTORS]](<16 x s32>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %2:_(<8 x s32>), %4:_(<8 x s32>) = G_UNMERGE_VALUES %1(<16 x s32>)
    %3:_(<16 x s32>) = G_CONCAT_VECTORS %2(<8 x s32>), %4(<8 x s32>)
    $x0 = COPY %3(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name:            vconcat_2048
legalized:       true
body:             |
  bb.1.entry:
    liveins:
    ; COMMON-LABEL: name: vconcat_2048
    ; COMMON: [[COPY:%[0-9]+]]:vregbank(<32 x s32>) = COPY $y0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[COPY]](<32 x s32>)
    ; COMMON-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[COPY]](<32 x s32>)
    ; COMMON-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<64 x s32>) = G_CONCAT_VECTORS [[COPY1]](<32 x s32>), [[COPY2]](<32 x s32>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<64 x s32>)
    %1:_(<32 x s32>) = COPY $y0
    %0:_(<64 x s32>) = G_CONCAT_VECTORS %1(<32 x s32>), %1(<32 x s32>)
    PseudoRET implicit $lr, implicit %0
...
