# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=FAST %s
...
---
name:            _Z16test_select_argsbDv32_u7__acc32S_
legalized:       true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0

    ; GREEDY-LABEL: name: _Z16test_select_argsbDv32_u7__acc32S_
    ; GREEDY: liveins: $cml1, $cml2, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[COPY1]](<32 x s32>)
    ; GREEDY-NEXT: [[COPY4:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[COPY2]](<32 x s32>)
    ; GREEDY-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY3]], [[COPY4]]
    ; GREEDY-NEXT: $cml0 = COPY [[SELECT]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: _Z16test_select_argsbDv32_u7__acc32S_
    ; FAST: liveins: $cml1, $cml2, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[COPY1]](<32 x s32>)
    ; FAST-NEXT: [[COPY4:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[COPY2]](<32 x s32>)
    ; FAST-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY3]], [[COPY4]]
    ; FAST-NEXT: $cml0 = COPY [[SELECT]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %4:_(s32) = COPY $r0
    %5:_(s32) = G_ASSERT_ZEXT %4, 1
    %2:_(<32 x s32>) = COPY $cml1
    %3:_(<32 x s32>) = COPY $cml2
    %0:_(<32 x s32>) = G_SELECT %5(s32), %2, %3
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z20test_select_localvalbiDv32_aS_
legalized:       true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $wl0, $wl2

    ; GREEDY-LABEL: name: _Z20test_select_localvalbiDv32_aS_
    ; GREEDY: liveins: $r0, $r1, $wl0, $wl2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl0
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl2
    ; GREEDY-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), [[COPY2]](<32 x s8>), [[COPY1]](s32), [[C]](s32)
    ; GREEDY-NEXT: [[INT1:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), [[COPY3]](<32 x s8>), [[COPY1]](s32), [[C]](s32)
    ; GREEDY-NEXT: [[COPY4:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[INT]](<32 x s32>)
    ; GREEDY-NEXT: [[COPY5:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[INT1]](<32 x s32>)
    ; GREEDY-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY4]], [[COPY5]]
    ; GREEDY-NEXT: $cml0 = COPY [[SELECT]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: _Z20test_select_localvalbiDv32_aS_
    ; FAST: liveins: $r0, $r1, $wl0, $wl2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl0
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl2
    ; FAST-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), [[COPY2]](<32 x s8>), [[COPY1]](s32), [[C]](s32)
    ; FAST-NEXT: [[INT1:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), [[COPY3]](<32 x s8>), [[COPY1]](s32), [[C]](s32)
    ; FAST-NEXT: [[COPY4:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[INT]](<32 x s32>)
    ; FAST-NEXT: [[COPY5:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[INT1]](<32 x s32>)
    ; FAST-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY4]], [[COPY5]]
    ; FAST-NEXT: $cml0 = COPY [[SELECT]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %5:_(s32) = COPY $r0
    %6:_(s32) = G_ASSERT_ZEXT %5, 1
    %2:_(s32) = COPY $r1
    %3:_(<32 x s8>) = COPY $wl0
    %4:_(<32 x s8>) = COPY $wl2
    %8:_(s32) = G_CONSTANT i32 1
    %7:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %3(<32 x s8>), %2(s32), %8(s32)
    %9:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acc32.v32.I256.ups), %4(<32 x s8>), %2(s32), %8(s32)
    %0:_(<32 x s32>) = G_SELECT %6(s32), %7, %9
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_select_2048bits
legalized:       true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0

    ; GREEDY-LABEL: name: test_select_2048bits
    ; GREEDY: liveins: $dm1, $dm2, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; GREEDY-NEXT: [[UV:%[0-9]+]]:accregbank(<32 x s32>), [[UV1:%[0-9]+]]:accregbank(<32 x s32>) = G_UNMERGE_VALUES [[COPY1]](<64 x s32>)
    ; GREEDY-NEXT: [[UV2:%[0-9]+]]:accregbank(<32 x s32>), [[UV3:%[0-9]+]]:accregbank(<32 x s32>) = G_UNMERGE_VALUES [[COPY2]](<64 x s32>)
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV]](<32 x s32>)
    ; GREEDY-NEXT: [[COPY4:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV2]](<32 x s32>)
    ; GREEDY-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY3]], [[COPY4]]
    ; GREEDY-NEXT: [[COPY5:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV1]](<32 x s32>)
    ; GREEDY-NEXT: [[COPY6:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV3]](<32 x s32>)
    ; GREEDY-NEXT: [[SELECT1:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY5]], [[COPY6]]
    ; GREEDY-NEXT: [[COPY7:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[SELECT]](<32 x s32>)
    ; GREEDY-NEXT: [[COPY8:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[SELECT1]](<32 x s32>)
    ; GREEDY-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<64 x s32>) = G_CONCAT_VECTORS [[COPY7]](<32 x s32>), [[COPY8]](<32 x s32>)
    ; GREEDY-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<64 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $dm0
    ;
    ; FAST-LABEL: name: test_select_2048bits
    ; FAST: liveins: $dm1, $dm2, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; FAST-NEXT: [[UV:%[0-9]+]]:accregbank(<32 x s32>), [[UV1:%[0-9]+]]:accregbank(<32 x s32>) = G_UNMERGE_VALUES [[COPY1]](<64 x s32>)
    ; FAST-NEXT: [[UV2:%[0-9]+]]:accregbank(<32 x s32>), [[UV3:%[0-9]+]]:accregbank(<32 x s32>) = G_UNMERGE_VALUES [[COPY2]](<64 x s32>)
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV]](<32 x s32>)
    ; FAST-NEXT: [[COPY4:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV2]](<32 x s32>)
    ; FAST-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY3]], [[COPY4]]
    ; FAST-NEXT: [[COPY5:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV1]](<32 x s32>)
    ; FAST-NEXT: [[COPY6:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[UV3]](<32 x s32>)
    ; FAST-NEXT: [[SELECT1:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[COPY5]], [[COPY6]]
    ; FAST-NEXT: [[COPY7:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[SELECT]](<32 x s32>)
    ; FAST-NEXT: [[COPY8:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[SELECT1]](<32 x s32>)
    ; FAST-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:accregbank(<64 x s32>) = G_CONCAT_VECTORS [[COPY7]](<32 x s32>), [[COPY8]](<32 x s32>)
    ; FAST-NEXT: $dm0 = COPY [[CONCAT_VECTORS]](<64 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $dm0
    %4:_(s32) = COPY $r0
    %5:_(s32) = G_ASSERT_ZEXT %4, 1
    %2:_(<64 x s32>) = COPY $dm1
    %3:_(<64 x s32>) = COPY $dm2
    %7:_(<32 x s32>), %8:_(<32 x s32>) = G_UNMERGE_VALUES %2(<64 x s32>)
    %9:_(<32 x s32>), %10:_(<32 x s32>) = G_UNMERGE_VALUES %3(<64 x s32>)
    %11:_(<32 x s32>) = G_SELECT %5(s32), %7, %9
    %12:_(<32 x s32>) = G_SELECT %5(s32), %8, %10
    %0:_(<64 x s32>) = G_CONCAT_VECTORS %11(<32 x s32>), %12(<32 x s32>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_select_64bitElem_acc
alignment:       16
exposesReturnsTwice: false
legalized:       true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0

    ; GREEDY-LABEL: name: test_select_64bitElem_acc
    ; GREEDY: liveins: $cml1, $cml2, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml2
    ; GREEDY-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[COPY1]](<16 x s64>)
    ; GREEDY-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[COPY2]](<16 x s64>)
    ; GREEDY-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[BITCAST]], [[BITCAST1]]
    ; GREEDY-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<16 x s64>) = G_BITCAST [[SELECT]](<32 x s32>)
    ; GREEDY-NEXT: $cml0 = COPY [[BITCAST2]](<16 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_select_64bitElem_acc
    ; FAST: liveins: $cml1, $cml2, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[ASSERT_ZEXT:%[0-9]+]]:gprregbank(s32) = G_ASSERT_ZEXT [[COPY]], 1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml1
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml2
    ; FAST-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[COPY1]](<16 x s64>)
    ; FAST-NEXT: [[BITCAST1:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[COPY2]](<16 x s64>)
    ; FAST-NEXT: [[SELECT:%[0-9]+]]:vregbank(<32 x s32>) = G_SELECT [[ASSERT_ZEXT]](s32), [[BITCAST]], [[BITCAST1]]
    ; FAST-NEXT: [[BITCAST2:%[0-9]+]]:accregbank(<16 x s64>) = G_BITCAST [[SELECT]](<32 x s32>)
    ; FAST-NEXT: $cml0 = COPY [[BITCAST2]](<16 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %4:_(s32) = COPY $r0
    %5:_(s32) = G_ASSERT_ZEXT %4, 1
    %2:_(<16 x s64>) = COPY $cml1
    %3:_(<16 x s64>) = COPY $cml2
    %7:_(<32 x s32>) = G_BITCAST %2(<16 x s64>)
    %8:_(<32 x s32>) = G_BITCAST %3(<16 x s64>)
    %9:_(<32 x s32>) = G_SELECT %5(s32), %7, %8
    %0:_(<16 x s64>) = G_BITCAST %9(<32 x s32>)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z12test_shuffleDv16_u7__acc32S_j
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll1, $bmll2, $r0

    ; GREEDY-LABEL: name: _Z12test_shuffleDv16_u7__acc32S_j
    ; GREEDY: liveins: $bmll1, $bmll2, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll2
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: [[COPY4:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), [[COPY3]](<16 x s32>), [[COPY4]](<16 x s32>), [[COPY2]](s32)
    ; GREEDY-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: _Z12test_shuffleDv16_u7__acc32S_j
    ; FAST: liveins: $bmll1, $bmll2, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll2
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; FAST-NEXT: [[COPY4:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; FAST-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), [[COPY3]](<16 x s32>), [[COPY4]](<16 x s32>), [[COPY2]](s32)
    ; FAST-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = COPY $bmll1
    %2:_(<16 x s32>) = COPY $bmll2
    %3:_(s32) = COPY $r0
    %0:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshuffle), %1(<16 x s32>), %2(<16 x s32>), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z11test_shiftxDv16_u10__accfloatS_ii
legalized:       true
body:             |
  bb.1.entry:
    liveins: $bmll1, $bmll2, $r0, $r1

    ; GREEDY-LABEL: name: _Z11test_shiftxDv16_u10__accfloatS_ii
    ; GREEDY: liveins: $bmll1, $bmll2, $r0, $r1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll2
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; GREEDY-NEXT: [[COPY4:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: [[COPY5:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshift.I512.I512), [[COPY4]](<16 x s32>), [[COPY5]](<16 x s32>), [[COPY2]](s32), [[COPY3]](s32)
    ; GREEDY-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $bmll0
    ;
    ; FAST-LABEL: name: _Z11test_shiftxDv16_u10__accfloatS_ii
    ; FAST: liveins: $bmll1, $bmll2, $r0, $r1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll2
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; FAST-NEXT: [[COPY4:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; FAST-NEXT: [[COPY5:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshift.I512.I512), [[COPY4]](<16 x s32>), [[COPY5]](<16 x s32>), [[COPY2]](s32), [[COPY3]](s32)
    ; FAST-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = COPY $bmll1
    %2:_(<16 x s32>) = COPY $bmll2
    %3:_(s32) = COPY $r0
    %4:_(s32) = COPY $r1
    %5:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2p.vshift.I512.I512), %1(<16 x s32>), %2(<16 x s32>), %3(s32), %4(s32)
    $bmll0 = COPY %5(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
