# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

---
name:            copy_512bit_vec
legalized:       true

body: |
  bb.0:
    liveins: $bmll0
    ; CHECK-LABEL: name: copy_512bit_vec
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s16>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s8>) = COPY $bmll0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<16 x s32>), implicit [[COPY1]](<32 x s16>), implicit [[COPY2]](<64 x s8>)
    %0:_(<16 x s32>) = COPY $bmll0
    %1:_(<32 x s16>) = COPY $bmll0
    %2:_(<64 x s8>) = COPY $bmll0
    PseudoRET implicit $lr, implicit %0, implicit %1, implicit %2
...

---
name:            copy_1024bit_vec
legalized:       true

body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: copy_1024bit_vec
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s16>) = COPY $cml0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<128 x s8>) = COPY $cml0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<32 x s32>), implicit [[COPY1]](<64 x s16>), implicit [[COPY2]](<128 x s8>)
    %0:_(<32 x s32>) = COPY $cml0
    %1:_(<64 x s16>) = COPY $cml0
    %2:_(<128 x s8>) = COPY $cml0
    PseudoRET implicit $lr, implicit %0, implicit %1, implicit %2
...
