# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_vector_256
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 32, alignment: 32}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_vector_256
    ; CHECK: [[COPY:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: G_STORE [[COPY]](<8 x s32>), [[FRAME_INDEX]](p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(p0) = G_FRAME_INDEX %stack.0
    G_STORE %0(<8 x s32>), %1(p0) :: (store (<8 x s32>))
    %3:_(<8 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<8 x s32>))
    PseudoRET implicit $lr
...

---
name:            test_bitcast_256bits
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_bitcast_256bits
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:vregbank(<8 x s32>) = G_BITCAST [[DEF]](<4 x s64>)
    ; CHECK-NEXT: $wl0 = COPY [[BITCAST]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<4 x s64>) = G_IMPLICIT_DEF
    %0:_(<8 x s32>) = G_BITCAST %1(<4 x s64>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            test_concat_128bits
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_concat_128bits
    ; CHECK: [[DEF:%[0-9]+]]:vregbank(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:vregbank(<8 x s32>) = G_CONCAT_VECTORS [[DEF]](<4 x s32>), [[DEF1]](<4 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[CONCAT_VECTORS]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<4 x s32>) = G_IMPLICIT_DEF
    %2:_(<4 x s32>) = G_IMPLICIT_DEF
    %0:_(<8 x s32>) = G_CONCAT_VECTORS %1(<4 x s32>), %2(<4 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0
...
