# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect %s -verify-machineinstrs -o - | FileCheck %s
---
name:   regbankselect_simple
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 8, alignment: 8}
body:             |
  bb.0.entry:
    liveins: $r1, $r2

    ; CHECK-LABEL: name: regbankselect_simple
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r2
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: G_STORE [[COPY]](s32), [[FRAME_INDEX]](p0) :: (store (s32))
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[FRAME_INDEX]], [[C]](s20)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ptrregbank(p0) = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY2]](p0) :: (store (s32))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:gprregbank(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32))
    ; CHECK-NEXT: $r0 = COPY [[LOAD]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(s32) = COPY $r1
    %3:_(s32) = COPY $r2
    %4:_(p0) = G_FRAME_INDEX %stack.0
    G_STORE %2(s32), %4(p0) :: (store (s32))
    %8:_(s20) = G_CONSTANT i20 4
    %7:_(p0) = G_PTR_ADD %4, %8(s20)
    %12:_(p0) = COPY %7(p0)
    G_STORE %3(s32), %12(p0) :: (store (s32))
    %6:_(s32) = G_LOAD %4(p0) :: (dereferenceable load (s32))
    $r0 = COPY %6(s32)
    PseudoRET implicit $lr, implicit $r0

...
