# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck --check-prefix=GREEDY %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck --check-prefix=FAST %s
---
name:            test_v16x32
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16x32
    ; GREEDY: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; GREEDY-NEXT: $lfl0 = COPY [[COPY]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lfl0
    ;
    ; FAST-LABEL: name: test_v16x32
    ; FAST: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; FAST-NEXT: $lfl0 = COPY [[COPY]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %0:_(<16 x s32>) = COPY $lfl1
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v32x32
legalized:       true
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v32x32
    ; GREEDY: [[COPY:%[0-9]+]]:fiforegbank(<32 x s32>) = COPY $lf1
    ; GREEDY-NEXT: $lf0 = COPY [[COPY]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lf0
    ;
    ; FAST-LABEL: name: test_v32x32
    ; FAST: [[COPY:%[0-9]+]]:fiforegbank(<32 x s32>) = COPY $lf1
    ; FAST-NEXT: $lf0 = COPY [[COPY]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lf0
    %0:_(<32 x s32>) = COPY $lf1
    $lf0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $lf0

...


---
name:            test_v32x32_store
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v32x32_store
    ; GREEDY: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (volatile store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $lfl0 = COPY [[LOAD]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lfl0
    ;
    ; FAST-LABEL: name: test_v32x32_store
    ; FAST: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (volatile store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $lfl0 = COPY [[LOAD]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    G_STORE %1(<16 x s32>), %2(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %2(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v32x32_load
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: test_v32x32_load
    ; GREEDY: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:fiforegbank(<32 x s32>) = G_LOAD [[COPY]](p0) :: (load (<32 x s32>))
    ; GREEDY-NEXT: $lf0 = COPY [[LOAD]](<32 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lf0
    ;
    ; FAST-LABEL: name: test_v32x32_load
    ; FAST: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:fiforegbank(<32 x s32>) = G_LOAD [[COPY]](p0) :: (load (<32 x s32>))
    ; FAST-NEXT: $lf0 = COPY [[LOAD]](<32 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lf0
    %1:_(p0) = COPY $p0
    %0:_(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>))
    $lf0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $lf0

...
---
name:            test_v16x32_spill_reload
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16x32_spill_reload
    ; GREEDY: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; GREEDY-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD1:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $lfl0 = COPY [[LOAD1]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lfl0
    ;
    ; FAST-LABEL: name: test_v16x32_spill_reload
    ; FAST: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; FAST-NEXT: G_STORE [[COPY]](<16 x s32>), [[FRAME_INDEX]](p0) :: (store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s32>))
    ; FAST-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; FAST-NEXT: [[LOAD1:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $lfl0 = COPY [[LOAD1]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    G_STORE %1(<16 x s32>), %2(p0) :: (store (<16 x s32>))
    %4:_(<16 x s32>) = G_LOAD %2(p0) :: (dereferenceable load (<16 x s32>))
    G_STORE %4(<16 x s32>), %3(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v16x64_spill_reload
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16x64_spill_reload
    ; GREEDY: [[COPY:%[0-9]+]]:fiforegbank(<16 x s64>) = COPY $lf1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; GREEDY-NEXT: G_STORE [[COPY]](<16 x s64>), [[FRAME_INDEX]](p0) :: (store (<16 x s64>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s64>))
    ; GREEDY-NEXT: G_STORE [[LOAD]](<16 x s64>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s64>))
    ; GREEDY-NEXT: [[LOAD1:%[0-9]+]]:fiforegbank(<16 x s64>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s64>))
    ; GREEDY-NEXT: $lf0 = COPY [[LOAD1]](<16 x s64>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lf0
    ;
    ; FAST-LABEL: name: test_v16x64_spill_reload
    ; FAST: [[COPY:%[0-9]+]]:fiforegbank(<16 x s64>) = COPY $lf1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; FAST-NEXT: G_STORE [[COPY]](<16 x s64>), [[FRAME_INDEX]](p0) :: (store (<16 x s64>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s64>))
    ; FAST-NEXT: G_STORE [[LOAD]](<16 x s64>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s64>))
    ; FAST-NEXT: [[LOAD1:%[0-9]+]]:fiforegbank(<16 x s64>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s64>))
    ; FAST-NEXT: $lf0 = COPY [[LOAD1]](<16 x s64>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lf0
    %1:_(<16 x s64>) = COPY $lf1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    G_STORE %1(<16 x s64>), %2(p0) :: (store (<16 x s64>))
    %4:_(<16 x s64>) = G_LOAD %2(p0) :: (dereferenceable load (<16 x s64>))
    G_STORE %4(<16 x s64>), %3(p0) :: (volatile store (<16 x s64>))
    %0:_(<16 x s64>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s64>))
    $lf0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $lf0

...

---
name:            test_fifo_ld_fill
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: test_fifo_ld_fill
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32)
    ; GREEDY-NEXT: G_STORE [[INT1]](<32 x s32>), %6:ptrregbank(p0) :: (store (<32 x s32>))
    ; GREEDY-NEXT: G_STORE [[INT2]](s32), %7:ptrregbank(p0) :: (store (s32))
    ; GREEDY-NEXT: G_STORE [[INT]](p0), %8:ptrregbank(p0) :: (store (p0), align 4)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $cml0
    ;
    ; FAST-LABEL: name: test_fifo_ld_fill
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32)
    ; FAST-NEXT: G_STORE [[INT1]](<32 x s32>), %6:ptrregbank(p0) :: (store (<32 x s32>))
    ; FAST-NEXT: G_STORE [[INT2]](s32), %7:ptrregbank(p0) :: (store (s32))
    ; FAST-NEXT: G_STORE [[INT]](p0), %8:ptrregbank(p0) :: (store (p0), align 4)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $cml0
    %7:_(p0), %8:_(<32 x s32>), %9:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %4:_(p0), %5:_(<32 x s32>), %6:_(s32)
    G_STORE %8:_(<32 x s32>), %1:_(p0) :: (store (<32 x s32>))
    G_STORE %9:_(s32), %3:_(p0) :: (store (s32))
    G_STORE %7:_(p0), %0:_(p0) :: (store (p0))
    PseudoRET implicit $lr, implicit $cml0

...

---
name:            _Z18test_fifo_st_resetRPDv64_DB8_S0_R12fifo_state_t
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z18test_fifo_st_resetRPDv64_DB8_S0_R12fifo_state_t
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.512.bfp16), %3:ptrregbank(p0), %4:vregbank(<16 x s32>), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
    ;
    ; FAST-LABEL: name: _Z18test_fifo_st_resetRPDv64_DB8_S0_R12fifo_state_t
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.512.bfp16), %3:ptrregbank(p0), %4:vregbank(<16 x s32>), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
  %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.512.bfp16), %5:_(p0), %6:_(<16 x s32>), %7:_(<32 x s32>), %8:_(s32)
...


---
name:            _Z18test_fifo_st_flushRPDv64_DB8_R12fifo_state_t
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z18test_fifo_st_flushRPDv64_DB8_R12fifo_state_t
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32)
    ;
    ; FAST-LABEL: name: _Z18test_fifo_st_flushRPDv64_DB8_R12fifo_state_t
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32)
  %7:_(p0), %8:_(<32 x s32>), %9:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush), %4:_(p0), %5:_(<32 x s32>), %6:_(s32)
...


---
name:            _Z26test_fifo_st_flush_1d_byteRPDv64_DB8_R12fifo_state_ti
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z26test_fifo_st_flush_1d_byteRPDv64_DB8_R12fifo_state_ti
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32), %6:modregbank(s20)
    ;
    ; FAST-LABEL: name: _Z26test_fifo_st_flush_1d_byteRPDv64_DB8_R12fifo_state_ti
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32), %6:modregbank(s20)
  %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d), %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %8:_(s20)
...


---
name:            _Z26test_fifo_st_flush_2d_byteRPDv64_DB8_R12fifo_state_tiiRii
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z26test_fifo_st_flush_2d_byteRPDv64_DB8_R12fifo_state_tiiRii
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d.conv), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32), %7:modregbank(s20), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20)
    ;
    ; FAST-LABEL: name: _Z26test_fifo_st_flush_2d_byteRPDv64_DB8_R12fifo_state_tiiRii
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d.conv), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32), %7:modregbank(s20), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20)
  %16:_(p0), %17:_(<32 x s32>), %18:_(s32), %19:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d.conv), %8:_(p0), %9:_(<32 x s32>), %10:_(s32), %11:_(s20), %12:_(s20), %14:_(s20), %15:_(s20)
...


---
name:            _Z26test_fifo_st_flush_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z26test_fifo_st_flush_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20), %11:modregbank(s20), %12:modregbank(s20), %13:modregbank(s20), %14:modregbank(s20)
    ;
    ; FAST-LABEL: name: _Z26test_fifo_st_flush_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20), %11:modregbank(s20), %12:modregbank(s20), %13:modregbank(s20), %14:modregbank(s20)
  %23:_(p0), %24:_(<32 x s32>), %25:_(s32), %26:_(s20), %27:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d), %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(s20), %15:_(s20), %17:_(s20), %18:_(s20), %19:_(s20), %21:_(s20), %22:_(s20)
...


---
name:            _Z23test_fifo_st_flush_convRPDv64_DB8_R12fifo_state_t
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z23test_fifo_st_flush_convRPDv64_DB8_R12fifo_state_t
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.conv), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32)
    ;
    ; FAST-LABEL: name: _Z23test_fifo_st_flush_convRPDv64_DB8_R12fifo_state_t
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.conv), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32)
  %7:_(p0), %8:_(<32 x s32>), %9:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.conv), %4:_(p0), %5:_(<32 x s32>), %6:_(s32)
...


---
name:            _Z31test_fifo_st_flush_conv_1d_byteRPDv64_DB8_R12fifo_state_ti
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z31test_fifo_st_flush_conv_1d_byteRPDv64_DB8_R12fifo_state_ti
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d.conv), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32), %6:modregbank(s20)
    ;
    ; FAST-LABEL: name: _Z31test_fifo_st_flush_conv_1d_byteRPDv64_DB8_R12fifo_state_ti
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d.conv), %3:ptrregbank(p0), %4:fiforegbank(<32 x s32>), %5:gprregbank(s32), %6:modregbank(s20)
  %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.1d.conv), %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %8:_(s20)
...


---
name:            _Z31test_fifo_st_flush_conv_2d_byteRPDv64_DB8_R12fifo_state_tiiRii
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z31test_fifo_st_flush_conv_2d_byteRPDv64_DB8_R12fifo_state_tiiRii
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32), %7:modregbank(s20), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20)
    ;
    ; FAST-LABEL: name: _Z31test_fifo_st_flush_conv_2d_byteRPDv64_DB8_R12fifo_state_tiiRii
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32), %7:modregbank(s20), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20)
  %16:_(p0), %17:_(<32 x s32>), %18:_(s32), %19:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.2d), %8:_(p0), %9:_(<32 x s32>), %10:_(s32), %11:_(s20), %12:_(s20), %14:_(s20), %15:_(s20)
...


---
name:            _Z31test_fifo_st_flush_conv_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z31test_fifo_st_flush_conv_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d.conv), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20), %11:modregbank(s20), %12:modregbank(s20), %13:modregbank(s20), %14:modregbank(s20)
    ;
    ; FAST-LABEL: name: _Z31test_fifo_st_flush_conv_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d.conv), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20), %9:modregbank(s20), %10:modregbank(s20), %11:modregbank(s20), %12:modregbank(s20), %13:modregbank(s20), %14:modregbank(s20)
  %23:_(p0), %24:_(<32 x s32>), %25:_(s32), %26:_(s20), %27:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.flush.3d.conv), %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(s20), %15:_(s20), %17:_(s20), %18:_(s20), %19:_(s20), %21:_(s20), %22:_(s20)
...


---
name:            _Z18test_fifo_st_resetRP22v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z18test_fifo_st_resetRP22v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.576.bfp16), %3:ptrregbank(p0), %4:vregbank(<64 x s8>), %5:gprregbank(<8 x s8>), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32)
    ;
    ; FAST-LABEL: name: _Z18test_fifo_st_resetRP22v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.576.bfp16), %3:ptrregbank(p0), %4:vregbank(<64 x s8>), %5:gprregbank(<8 x s8>), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32)
  %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.576.bfp16), %6:_(p0), %1:_(<64 x s8>), %2:_(<8 x s8>), %7:_(<32 x s32>), %8:_(s32)
...


---
name:            _Z18test_fifo_st_resetRP23v64bfp16ebs16_unaligned13v64bfp16ebs16R12fifo_state_t
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: _Z18test_fifo_st_resetRP23v64bfp16ebs16_unaligned13v64bfp16ebs16R12fifo_state_t
    ; GREEDY: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.544.bfp16), %3:ptrregbank(p0), %4:vregbank(<64 x s8>), %5:gprregbank(<8 x s8>), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32)
    ;
    ; FAST-LABEL: name: _Z18test_fifo_st_resetRP23v64bfp16ebs16_unaligned13v64bfp16ebs16R12fifo_state_t
    ; FAST: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.544.bfp16), %3:ptrregbank(p0), %4:vregbank(<64 x s8>), %5:gprregbank(<8 x s8>), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32)
  %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.st.push.544.bfp16), %6:_(p0), %1:_(<64 x s8>), %2:_(<8 x s8>), %7:_(<32 x s32>), %8:_(s32)
...




---
name:            pop_unaligned
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1
    ; GREEDY-LABEL: name: pop_unaligned
    ; GREEDY: liveins: $p0, $p1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.unaligned), [[DEF1]](p0), [[DEF2]](<32 x s32>), [[DEF3]](s32)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32)
    ;
    ; FAST-LABEL: name: pop_unaligned
    ; FAST: liveins: $p0, $p1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.unaligned), [[DEF1]](p0), [[DEF2]](<32 x s32>), [[DEF3]](s32)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32)
    %3:_(s20) = G_IMPLICIT_DEF
    %5:_(p0) = G_IMPLICIT_DEF
    %6:_(<32 x s32>) = G_IMPLICIT_DEF
    %7:_(s32) = G_IMPLICIT_DEF
    %8:_(<64 x s8>), %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.unaligned), %5:_(p0), %6:_(<32 x s32>), %7:_(s32)
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11
...

---
name:            pop_544
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1
    ; GREEDY-LABEL: name: pop_544
    ; GREEDY: liveins: $p0, $p1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    ;
    ; FAST-LABEL: name: pop_544
    ; FAST: liveins: $p0, $p1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    %14:_(<64 x s8>) = G_IMPLICIT_DEF
    %15:_(<8 x s8>) = G_IMPLICIT_DEF
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %12:_(<64 x s8>), %13:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.bfp16), %6:_(p0), %7:_(<32 x s32>), %8:_(s32), %14:_(<64 x s8>), %15:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %9, implicit %10, implicit %11, implicit %12, implicit %13
...

---
name:            pop_576
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1
    ; GREEDY-LABEL: name: pop_576
    ; GREEDY: liveins: $p0, $p1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    ;
    ; FAST-LABEL: name: pop_576
    ; FAST: liveins: $p0, $p1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    %14:_(<64 x s8>) = G_IMPLICIT_DEF
    %15:_(<8 x s8>) = G_IMPLICIT_DEF
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %12:_(<64 x s8>), %13:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.bfp16), %6:_(p0), %7:_(<32 x s32>), %8:_(s32), %14:_(<64 x s8>), %15:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %9, implicit %10, implicit %11, implicit %12, implicit %13
...

---
name:            pop_unaligned_1d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0
    ; GREEDY-LABEL: name: pop_unaligned_1d
    ; GREEDY: liveins: $p0, $p1, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.1d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32)
    ;
    ; FAST-LABEL: name: pop_unaligned_1d
    ; FAST: liveins: $p0, $p1, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.1d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32)
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %9:_(s20) = G_IMPLICIT_DEF
    %10:_(<64 x s8>), %11:_(p0), %12:_(<32 x s32>), %13:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.1d.unaligned), %6:_(p0), %7:_(<32 x s32>), %8:_(s32), %9:_(s20)
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13
...

---
name:            pop_544_1d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0
    ; GREEDY-LABEL: name: pop_544_1d
    ; GREEDY: liveins: $p0, $p1, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.1d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    ;
    ; FAST-LABEL: name: pop_544_1d
    ; FAST: liveins: $p0, $p1, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.1d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    %16:_(<64 x s8>) = G_IMPLICIT_DEF
    %17:_(<8 x s8>) = G_IMPLICIT_DEF
    %7:_(p0) = G_IMPLICIT_DEF
    %8:_(<32 x s32>) = G_IMPLICIT_DEF
    %9:_(s32) = G_IMPLICIT_DEF
    %10:_(s20) = G_IMPLICIT_DEF
    %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(<64 x s8>), %15:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.1d.bfp16), %7:_(p0), %8:_(<32 x s32>), %9:_(s32), %10:_(s20), %16:_(<64 x s8>), %17:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15

...

---
name:            pop_576_1d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0
    ; GREEDY-LABEL: name: pop_576_1d
    ; GREEDY: liveins: $p0, $p1, $r0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.1d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    ;
    ; FAST-LABEL: name: pop_576_1d
    ; FAST: liveins: $p0, $p1, $r0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<64 x s8>), [[INT4:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.1d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<64 x s8>), implicit [[INT4]](<8 x s8>)
    %16:_(<64 x s8>) = G_IMPLICIT_DEF
    %17:_(<8 x s8>) = G_IMPLICIT_DEF
    %7:_(p0) = G_IMPLICIT_DEF
    %8:_(<32 x s32>) = G_IMPLICIT_DEF
    %9:_(s32) = G_IMPLICIT_DEF
    %10:_(s20) = G_IMPLICIT_DEF
    %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(<64 x s8>), %15:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.1d.bfp16), %7:_(p0), %8:_(<32 x s32>), %9:_(s32), %10:_(s20), %16:_(<64 x s8>), %17:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15
...

---
name:            pop_unaligned_2d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; GREEDY-LABEL: name: pop_unaligned_2d
    ; GREEDY: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.2d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32), implicit [[INT4]](s20)
    ;
    ; FAST-LABEL: name: pop_unaligned_2d
    ; FAST: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.2d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32), implicit [[INT4]](s20)
    %9:_(p0) = G_IMPLICIT_DEF
    %10:_(<32 x s32>) = G_IMPLICIT_DEF
    %11:_(s32) = G_IMPLICIT_DEF
    %12:_(s20) = G_IMPLICIT_DEF
    %13:_(s20) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(<64 x s8>), %18:_(p0), %19:_(<32 x s32>), %20:_(s32), %21:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.2d.unaligned), %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %12:_(s20), %13:_(s20), %15:_(s20), %16:_(s20)
    PseudoRET implicit $lr, implicit %17, implicit %18, implicit %19, implicit %20, implicit %21

...

---
name:            pop_544_2d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; GREEDY-LABEL: name: pop_544_2d
    ; GREEDY: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:vregbank(<64 x s8>), [[INT5:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.2d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT4]](<64 x s8>), implicit [[INT5]](<8 x s8>), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20)
    ;
    ; FAST-LABEL: name: pop_544_2d
    ; FAST: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:vregbank(<64 x s8>), [[INT5:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.2d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT4]](<64 x s8>), implicit [[INT5]](<8 x s8>), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20)
    %24:_(<64 x s8>) = G_IMPLICIT_DEF
    %25:_(<8 x s8>) = G_IMPLICIT_DEF
    %10:_(p0) = G_IMPLICIT_DEF
    %11:_(<32 x s32>) = G_IMPLICIT_DEF
    %12:_(s32) = G_IMPLICIT_DEF
    %13:_(s20) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %18:_(p0), %19:_(<32 x s32>), %20:_(s32), %21:_(s20), %22:_(<64 x s8>), %23:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.2d.bfp16), %10:_(p0), %11:_(<32 x s32>), %12:_(s32), %13:_(s20), %14:_(s20), %16:_(s20), %17:_(s20), %24:_(<64 x s8>), %25:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %22, implicit %23, implicit %18, implicit %19, implicit %20, implicit %21

...

---
name:            pop_576_2d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; GREEDY-LABEL: name: pop_576_2d
    ; GREEDY: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:vregbank(<64 x s8>), [[INT5:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.2d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT4]](<64 x s8>), implicit [[INT5]](<8 x s8>), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20)
    ;
    ; FAST-LABEL: name: pop_576_2d
    ; FAST: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:vregbank(<64 x s8>), [[INT5:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.2d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT4]](<64 x s8>), implicit [[INT5]](<8 x s8>), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20)
    %24:_(<64 x s8>) = G_IMPLICIT_DEF
    %25:_(<8 x s8>) = G_IMPLICIT_DEF
    %10:_(p0) = G_IMPLICIT_DEF
    %11:_(<32 x s32>) = G_IMPLICIT_DEF
    %12:_(s32) = G_IMPLICIT_DEF
    %13:_(s20) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %18:_(p0), %19:_(<32 x s32>), %20:_(s32), %21:_(s20), %22:_(<64 x s8>), %23:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.2d.bfp16), %10:_(p0), %11:_(<32 x s32>), %12:_(s32), %13:_(s20), %14:_(s20), %16:_(s20), %17:_(s20), %24:_(<64 x s8>), %25:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %22, implicit %23, implicit %18, implicit %19, implicit %20, implicit %21

...

---
name:            pop_unaligned_3d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; GREEDY-LABEL: name: pop_unaligned_3d
    ; GREEDY: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.3d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32), implicit [[INT4]](s20), implicit [[INT5]](s20)
    ;
    ; FAST-LABEL: name: pop_unaligned_3d
    ; FAST: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.3d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32), implicit [[INT4]](s20), implicit [[INT5]](s20)
    %12:_(p0) = G_IMPLICIT_DEF
    %13:_(<32 x s32>) = G_IMPLICIT_DEF
    %14:_(s32) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %18:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %20:_(s20) = G_IMPLICIT_DEF
    %22:_(s20) = G_IMPLICIT_DEF
    %23:_(s20) = G_IMPLICIT_DEF
    %24:_(<64 x s8>), %25:_(p0), %26:_(<32 x s32>), %27:_(s32), %28:_(s20), %29:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.3d.unaligned), %12:_(p0), %13:_(<32 x s32>), %14:_(s32), %15:_(s20), %16:_(s20), %18:_(s20), %19:_(s20), %20:_(s20), %22:_(s20), %23:_(s20)
    PseudoRET implicit $lr, implicit %24, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29
...

---
name:            pop_544_3d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; GREEDY-LABEL: name: pop_544_3d
    ; GREEDY: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF10:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF11:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:vregbank(<64 x s8>), [[INT6:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.3d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20), [[DEF10]](s20), [[DEF11]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[DEF11]](s20), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20), implicit [[INT4]](s20)
    ;
    ; FAST-LABEL: name: pop_544_3d
    ; FAST: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF10:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF11:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:vregbank(<64 x s8>), [[INT6:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.3d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20), [[DEF10]](s20), [[DEF11]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[DEF11]](s20), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20), implicit [[INT4]](s20)
    %32:_(<64 x s8>) = G_IMPLICIT_DEF
    %33:_(<8 x s8>) = G_IMPLICIT_DEF
    %13:_(p0) = G_IMPLICIT_DEF
    %14:_(<32 x s32>) = G_IMPLICIT_DEF
    %15:_(s32) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %20:_(s20) = G_IMPLICIT_DEF
    %21:_(s20) = G_IMPLICIT_DEF
    %23:_(s20) = G_IMPLICIT_DEF
    %24:_(s20) = G_IMPLICIT_DEF
    %25:_(p0), %26:_(<32 x s32>), %27:_(s32), %28:_(s20), %29:_(s20), %30:_(<64 x s8>), %31:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.544.3d.bfp16), %13:_(p0), %14:_(<32 x s32>), %15:_(s32), %16:_(s20), %17:_(s20), %19:_(s20), %20:_(s20), %21:_(s20), %23:_(s20), %24:_(s20), %32:_(<64 x s8>), %33:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %24, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29
...

---
name:            pop_576_3d
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; GREEDY-LABEL: name: pop_576_3d
    ; GREEDY: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF10:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF11:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:vregbank(<64 x s8>), [[INT6:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20), [[DEF10]](s20), [[DEF11]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT5]](<64 x s8>), implicit [[INT6]](<8 x s8>), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20), implicit [[INT4]](s20)
    ;
    ; FAST-LABEL: name: pop_576_3d
    ; FAST: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:gprregbank(<8 x s8>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF10:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF11:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:vregbank(<64 x s8>), [[INT6:%[0-9]+]]:gprregbank(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), [[DEF2]](p0), [[DEF3]](<32 x s32>), [[DEF4]](s32), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20), [[DEF10]](s20), [[DEF11]](s20), [[DEF]](<64 x s8>), [[DEF1]](<8 x s8>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT5]](<64 x s8>), implicit [[INT6]](<8 x s8>), implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](s20), implicit [[INT4]](s20)
    %32:_(<64 x s8>) = G_IMPLICIT_DEF
    %33:_(<8 x s8>) = G_IMPLICIT_DEF
    %13:_(p0) = G_IMPLICIT_DEF
    %14:_(<32 x s32>) = G_IMPLICIT_DEF
    %15:_(s32) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %20:_(s20) = G_IMPLICIT_DEF
    %21:_(s20) = G_IMPLICIT_DEF
    %23:_(s20) = G_IMPLICIT_DEF
    %24:_(s20) = G_IMPLICIT_DEF
    %25:_(p0), %26:_(<32 x s32>), %27:_(s32), %28:_(s20), %29:_(s20), %30:_(<64 x s8>), %31:_(<8 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.pop.576.3d.bfp16), %13:_(p0), %14:_(<32 x s32>), %15:_(s32), %16:_(s20), %17:_(s20), %19:_(s20), %20:_(s20), %21:_(s20), %23:_(s20), %24:_(s20), %32:_(<64 x s8>), %33:_(<8 x s8>)
    PseudoRET implicit $lr, implicit %30, implicit %31, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29

...

---
name:            test_fifo_ld_fillx
legalized:       true
body:             |
  bb.1.entry:
    ; GREEDY-LABEL: name: test_fifo_ld_fillx
    ; GREEDY: [[DEF:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fillx), [[DEF1]](p0), [[DEF2]](<32 x s32>), [[DEF3]](s32), [[DEF4]](<16 x s32>), [[DEF5]](s32)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<16 x s32>)
    ;
    ; FAST-LABEL: name: test_fifo_ld_fillx
    ; FAST: [[DEF:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fillx), [[DEF1]](p0), [[DEF2]](<32 x s32>), [[DEF3]](s32), [[DEF4]](<16 x s32>), [[DEF5]](s32)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](p0), implicit [[INT1]](<32 x s32>), implicit [[INT2]](s32), implicit [[INT3]](<16 x s32>)
    %2:_(s20) = G_IMPLICIT_DEF
    %4:_(p0) = G_IMPLICIT_DEF
    %5:_(<32 x s32>) = G_IMPLICIT_DEF
    %6:_(s32) = G_IMPLICIT_DEF
    %10:_(<16 x s32>) = G_IMPLICIT_DEF
    %11:_(s32) = G_IMPLICIT_DEF
    %7:_(p0), %8:_(<32 x s32>), %9:_(s32), %12:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fillx), %4:_(p0), %5:_(<32 x s32>), %6:_(s32), %10:_(<16 x s32>), %11:_(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %12

...
---
name:            offset_load_fifo512
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0
    ; GREEDY-LABEL: name: offset_load_fifo512
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:fiforegbank(<8 x s64>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (<8 x s64>))
    ; GREEDY-NEXT: $lfl0 = COPY [[AIE_OFFSET_LOAD]](<8 x s64>)
    ;
    ; FAST-LABEL: name: offset_load_fifo512
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:fiforegbank(<8 x s64>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (<8 x s64>))
    ; FAST-NEXT: $lfl0 = COPY [[AIE_OFFSET_LOAD]](<8 x s64>)
    %1:_(p0) = COPY $p0
    %2:_(s20) = G_CONSTANT i20 448
    %0:_(<8 x s64>) = G_AIE_OFFSET_LOAD %1:_(p0), %2:_(s20) :: (load (<8 x s64>))
    $lfl0 = COPY %0:_(<8 x s64>)

...
---
name:            offset_store_fifo512
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0
    ; GREEDY-LABEL: name: offset_store_fifo512
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: G_AIE_OFFSET_STORE [[COPY]](<16 x s32>), [[COPY1]](p0), [[C]](s20) :: (store (<16 x s32>))
    ;
    ; FAST-LABEL: name: offset_store_fifo512
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: G_AIE_OFFSET_STORE [[COPY]](<16 x s32>), [[COPY1]](p0), [[C]](s20) :: (store (<16 x s32>))
    %0:_(<16 x s32>) = COPY $lfl0
    %1:_(p0) = COPY $p0
    %2:_(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:_(<16 x s32>), %1:_(p0), %2:_(s20) :: (store (<16 x s32>))
...

---
name: post-inc-fifo512-load
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1
    ; GREEDY-LABEL: name: post-inc-fifo512-load
    ; GREEDY: liveins: $p0, $r0, $r1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; GREEDY-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<16 x s32>) from stack - 64)
    ; GREEDY-NEXT: [[AIE_POSTINC_LOAD2:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_LOAD3:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[AIE_POSTINC_LOAD1]], [[C]](s20) :: (load (<16 x s32>) from stack - 64)
    ; GREEDY-NEXT: $lfl0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; GREEDY-NEXT: $lfl1 = COPY [[AIE_POSTINC_LOAD2]](<16 x s32>)
    ;
    ; FAST-LABEL: name: post-inc-fifo512-load
    ; FAST: liveins: $p0, $r0, $r1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; FAST-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<16 x s32>) from stack - 64)
    ; FAST-NEXT: [[AIE_POSTINC_LOAD2:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_LOAD3:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[AIE_POSTINC_LOAD1]], [[C]](s20) :: (load (<16 x s32>) from stack - 64)
    ; FAST-NEXT: $lfl0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; FAST-NEXT: $lfl1 = COPY [[AIE_POSTINC_LOAD2]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %7:_(s20) = G_TRUNC %1
    %8:_(s20) = G_CONSTANT i20 448
    %9:_(s20) = G_CONSTANT i20 -512
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_CONSTANT i20 32
    %12:_(s20) = G_CONSTANT i20 512
    %13:_(<16 x s32>), %15:_(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>) from stack - 64)
    %14:_(<16 x s32>), %16:_(p0) = G_AIE_POSTINC_LOAD %15, %8 :: (load (<16 x s32>) from stack - 64)
    $lfl0 = COPY %13:_(<16 x s32>)
    $lfl1 = COPY %14:_(<16 x s32>)
...

---
name: post-inc-2d-fifo-load-bm
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ; GREEDY-LABEL: name: post-inc-2d-fifo-load-bm
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[AIE_POSTINC_2D_LOAD:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_2D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_LOAD2:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (load (<16 x s32>))
    ; GREEDY-NEXT: $lfl0 = COPY [[AIE_POSTINC_2D_LOAD]](<16 x s32>)
    ;
    ; FAST-LABEL: name: post-inc-2d-fifo-load-bm
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[AIE_POSTINC_2D_LOAD:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_2D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_LOAD2:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (load (<16 x s32>))
    ; FAST-NEXT: $lfl0 = COPY [[AIE_POSTINC_2D_LOAD]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(<16 x s32>), %6:_(p0), %7:_(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    $lfl0 = COPY %5:_(<16 x s32>)
...

---
name: post-inc-3d-fifo-load-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ; GREEDY-LABEL: name: post-inc-3d-fifo-load-512
    ; GREEDY: liveins: $p0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; GREEDY-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; GREEDY-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; GREEDY-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (load (<16 x s32>))
    ; GREEDY-NEXT: $lfl0 = COPY [[AIE_POSTINC_3D_LOAD]](<16 x s32>)
    ;
    ; FAST-LABEL: name: post-inc-3d-fifo-load-512
    ; FAST: liveins: $p0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; FAST-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; FAST-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; FAST-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:fiforegbank(<16 x s32>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (load (<16 x s32>))
    ; FAST-NEXT: $lfl0 = COPY [[AIE_POSTINC_3D_LOAD]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(s20) = G_CONSTANT i20 5
    %6:_(s20) = G_CONSTANT i20 6
    %7:_(s20) = G_CONSTANT i20 7
    %8:_(<16 x s32>), %9:_(p0), %10:_(s20), %11:_(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<16 x s32>))
    $lfl0 = COPY %8:_(<16 x s32>)

...
---
name:            test_fifo_postinc_store
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_fifo_postinc_store
    ; GREEDY: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; GREEDY-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $lfl0 = COPY [[LOAD]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lfl0
    ;
    ; FAST-LABEL: name: test_fifo_postinc_store
    ; FAST: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; FAST-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $lfl0 = COPY [[LOAD]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = COPY $p1
    %3:_(s20) = G_CONSTANT i20 128
    %5:_(p0) = G_AIE_POSTINC_STORE %1(<16 x s32>), %2, %3(s20) :: (store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %5(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v16acc32_spill_reload_postinc
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; GREEDY-LABEL: name: test_v16acc32_spill_reload_postinc
    ; GREEDY: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; GREEDY-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; GREEDY-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; GREEDY-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; GREEDY-NEXT: [[LOAD1:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; GREEDY-NEXT: $lfl0 = COPY [[LOAD1]](<16 x s32>)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit $lfl0
    ;
    ; FAST-LABEL: name: test_v16acc32_spill_reload_postinc
    ; FAST: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; FAST-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; FAST-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; FAST-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; FAST-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (dereferenceable load (<16 x s32>))
    ; FAST-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; FAST-NEXT: [[LOAD1:%[0-9]+]]:fiforegbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; FAST-NEXT: $lfl0 = COPY [[LOAD1]](<16 x s32>)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    %5:_(p0) = COPY $p1
    %6:_(s20) = G_CONSTANT i20 128
    %7:_(p0) = G_AIE_POSTINC_STORE %1(<16 x s32>), %5, %6(s20) :: (store (<16 x s32>))
    %4:_(<16 x s32>) = G_LOAD %7(p0) :: (dereferenceable load (<16 x s32>))
    G_STORE %4(<16 x s32>), %3(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...

---
name:            test_fifo_ld_popx
tracksRegLiveness: true
legalized: true
regBankSelected: false
body:             |
  bb.1.entry:
    liveins: $p0, $p1
    ; GREEDY-LABEL: name: test_fifo_ld_popx
    ; GREEDY: liveins: $p0, $p1
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[DEF:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF1:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF2:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF4:%[0-9]+]]:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[DEF5:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; GREEDY-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.popx), [[DEF1]](p0), [[DEF2]](<32 x s32>), [[DEF3]](s32), [[DEF4]](<16 x s32>), [[DEF5]](s32)
    ; GREEDY-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32), implicit [[INT4]](<16 x s32>)
    ;
    ; FAST-LABEL: name: test_fifo_ld_popx
    ; FAST: liveins: $p0, $p1
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[DEF:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF1:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF2:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF4:%[0-9]+]]:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[DEF5:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; FAST-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.popx), [[DEF1]](p0), [[DEF2]](<32 x s32>), [[DEF3]](s32), [[DEF4]](<16 x s32>), [[DEF5]](s32)
    ; FAST-NEXT: PseudoRET implicit $lr, implicit [[INT]](<64 x s8>), implicit [[INT1]](p0), implicit [[INT2]](<32 x s32>), implicit [[INT3]](s32), implicit [[INT4]](<16 x s32>)
    %3:_(s20) = G_IMPLICIT_DEF
    %5:_(p0) = G_IMPLICIT_DEF
    %6:_(<32 x s32>) = G_IMPLICIT_DEF
    %7:_(s32) = G_IMPLICIT_DEF
    %12:_(<16 x s32>) = G_IMPLICIT_DEF
    %13:_(s32) = G_IMPLICIT_DEF
    %8:_(<64 x s8>), %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %14:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.popx), %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %12:_(<16 x s32>), %13:_(s32)
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11, implicit %14
...

---
name: post-inc-acc-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $lfl0
    ; GREEDY-LABEL: name: post-inc-acc-store-512
    ; GREEDY: liveins: $p0, $r0, $r1, $lfl0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; GREEDY-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; GREEDY-NEXT: [[COPY2:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; GREEDY-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY2]](<16 x s32>), [[COPY]], [[TRUNC]](s20) :: (store (<16 x s32>) into stack - 64)
    ;
    ; FAST-LABEL: name: post-inc-acc-store-512
    ; FAST: liveins: $p0, $r0, $r1, $lfl0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; FAST-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; FAST-NEXT: [[COPY2:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; FAST-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY2]](<16 x s32>), [[COPY]], [[TRUNC]](s20) :: (store (<16 x s32>) into stack - 64)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %7:_(s20) = G_TRUNC %1
    %8:_(s20) = G_CONSTANT i20 448
    %9:_(s20) = G_CONSTANT i20 -512
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_CONSTANT i20 32
    %12:_(s20) = G_CONSTANT i20 512
    %13:_(<16 x s32>) = COPY $lfl0
    %19:_(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<16 x s32>) into stack - 64)
...

---
name: post-inc-2d-acc-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $lfl0
    ; GREEDY-LABEL: name: post-inc-2d-acc-store-512
    ; GREEDY: liveins: $p0, $lfl0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; GREEDY-NEXT: [[AIE_POSTINC_2D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_STORE1:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (store (<16 x s32>))
    ; GREEDY-NEXT: PseudoRET implicit $lr
    ;
    ; FAST-LABEL: name: post-inc-2d-acc-store-512
    ; FAST: liveins: $p0, $lfl0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; FAST-NEXT: [[AIE_POSTINC_2D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_STORE1:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (store (<16 x s32>))
    ; FAST-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(<16 x s32>) = COPY $lfl0
    %6:_(p0), %7:_(s20) = G_AIE_POSTINC_2D_STORE %5, %0, %1, %2, %3, %4 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name: post-inc-3d-vector-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $lfl0
    ; GREEDY-LABEL: name: post-inc-3d-vector-store-512
    ; GREEDY: liveins: $p0, $lfl0
    ; GREEDY-NEXT: {{  $}}
    ; GREEDY-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; GREEDY-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; GREEDY-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; GREEDY-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; GREEDY-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; GREEDY-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; GREEDY-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; GREEDY-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; GREEDY-NEXT: [[COPY1:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; GREEDY-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (store (<16 x s32>))
    ; GREEDY-NEXT: PseudoRET implicit $lr
    ;
    ; FAST-LABEL: name: post-inc-3d-vector-store-512
    ; FAST: liveins: $p0, $lfl0
    ; FAST-NEXT: {{  $}}
    ; FAST-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; FAST-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; FAST-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; FAST-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; FAST-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; FAST-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; FAST-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; FAST-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; FAST-NEXT: [[COPY1:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; FAST-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_STORE [[COPY1]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (store (<16 x s32>))
    ; FAST-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(s20) = G_CONSTANT i20 5
    %6:_(s20) = G_CONSTANT i20 6
    %7:_(s20) = G_CONSTANT i20 7
    %8:_(<16 x s32>) = COPY $lfl0
    %9:_(p0), %10:_(s20), %11:_(s20) = G_AIE_POSTINC_3D_STORE %8, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...
