# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s


# Test 1:  The instruction %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
# should be mapped to fiforegbank to avoid copies to and from the vector bank.

---
name:            test_fifo.ld.fill
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_fifo.ld.fill
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %6(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:ptrregbank(p0) = G_PHI [[COPY]](p0), %bb.0, %8(p0), %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gprregbank(s32) = G_PHI [[C]](s32), %bb.0, %10(s32), %bb.1
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, %12(<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), [[PHI1]](p0), [[PHI3]](<32 x s32>), [[PHI2]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    liveins: $p0

    %0:_(p0) = COPY $p0
    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
    %21:_(s32) = G_PHI %4(s32), %bb.0, %29(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
    %27:_(p0), %28:_(<32 x s32>), %29:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %19(p0), %23(<32 x s32>), %21(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 2:  The instruction %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
# should be mapped to. Also map %0:_(p0) = G_IMPLICIT_DEF correctly (also used by FIFO instr through
# phi node.)

---
name:            test_fifo.ld.fill.implicit.ptr
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_fifo.ld.fill.implicit.ptr
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %6(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:ptrregbank(p0) = G_PHI [[DEF]](p0), %bb.0, %8(p0), %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gprregbank(s32) = G_PHI [[C]](s32), %bb.0, %10(s32), %bb.1
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_PHI [[DEF1]](<32 x s32>), %bb.0, %12(<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), [[PHI1]](p0), [[PHI3]](<32 x s32>), [[PHI2]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1

    %0:_(p0) = G_IMPLICIT_DEF
    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
    %21:_(s32) = G_PHI %4(s32), %bb.0, %29(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
    %27:_(p0), %28:_(<32 x s32>), %29:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %19(p0), %23(<32 x s32>), %21(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 3:  The instruction %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %100(<32 x s32>), %bb.1
# should be mapped to accregbank to avoid copies to and from the vector bank.

---
name:            test_acc.vmac
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_acc.vmac
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vregbank(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %6(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:accregbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, %8(<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), [[DEF1]](<32 x s16>), [[DEF1]](<32 x s16>), [[PHI1]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr

  bb.0:
    successors: %bb.1

    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %77:_(<32 x s16>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %100(<32 x s32>), %bb.1
    %100:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %77(<32 x s16>), %77(<32 x s16>), %23(<32 x s32>), %4(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 4:  The instruction  %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
# should not be mapped to accregbank. The result of the PHI node is used by an instruction
# that is considered an `accumulator-use instruction` but the considered result is just a scalar
# pointer.

---
name:            neg_test_acc.vmac_store
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: neg_test_acc.vmac_store
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vregbank(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), [[DEF1]](<32 x s16>), [[DEF1]](<32 x s16>), [[DEF]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %9(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:ptrregbank(p0) = G_PHI [[COPY]](p0), %bb.0, %11(p0), %bb.1
  ; CHECK-NEXT:   G_STORE [[INT]](<32 x s32>), [[PHI1]](p0) :: (store (<32 x s32>))
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:ptrregbank(p0) = G_PTR_ADD [[PHI1]], [[C3]](s20)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    liveins: $p0

    %0:_(p0) = COPY $p0
    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %77:_(<32 x s16>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    %5:_(s20) = G_CONSTANT i20 32
    %100:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %77(<32 x s16>), %77(<32 x s16>), %66(<32 x s32>), %4(s32)
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
    G_STORE %100, %19(p0) :: (store (<32 x s32>))
    %27:_(p0) = G_PTR_ADD %19, %5
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 5:  The instruction  %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
# is also used as PHI input.

---
name:            test_fifo_next_phi.ld.fill
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_fifo_next_phi.ld.fill
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BRCOND [[COPY1]](s32), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %7(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:ptrregbank(p0) = G_PHI [[COPY]](p0), %bb.0, %9(p0), %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gprregbank(s32) = G_PHI [[C]](s32), %bb.0, %11(s32), %bb.1
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, %13(<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), [[PHI1]](p0), [[PHI3]](<32 x s32>), [[PHI2]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:fiforegbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, [[PHI3]](<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[PHI5:%[0-9]+]]:fiforegbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, [[PHI3]](<32 x s32>), %bb.1
  ; CHECK-NEXT:   $lf0 = COPY [[PHI4]](<32 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $lf0, implicit [[PHI5]](<32 x s32>)

  bb.0:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)
    liveins: $p0, $r0

    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BRCOND %1(s32), %bb.2
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
    %21:_(s32) = G_PHI %4(s32), %bb.0, %29(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
    %27:_(p0), %28:_(<32 x s32>), %29:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %19(p0), %23(<32 x s32>), %21(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %70:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %23(<32 x s32>), %bb.1
    %71:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %23(<32 x s32>), %bb.1
    $lf0 = COPY %70:_(<32 x s32>)
    PseudoRET implicit $lr, implicit $lf0,  implicit %71

...

# Test 6:  The instruction %23:_(<16 x s64>) = G_PHI %66(<16 x s64>), %bb.0, %25(<16 x s64>), %bb.1
# should be mapped to fiforegbank. Now we are looking through a bitcast.

---
name:            test_fifo.ld.fill.bitcast
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_fifo.ld.fill.bitcast
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:fiforegbank(<16 x s64>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %6(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:ptrregbank(p0) = G_PHI [[COPY]](p0), %bb.0, %8(p0), %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gprregbank(s32) = G_PHI [[C]](s32), %bb.0, %10(s32), %bb.1
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fiforegbank(<16 x s64>) = G_PHI [[DEF]](<16 x s64>), %bb.0, %12(<16 x s64>), %bb.1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vregbank(<16 x s64>) = COPY [[PHI3]](<16 x s64>)
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:vregbank(<32 x s32>) = G_BITCAST [[COPY1]](<16 x s64>)
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:fiforegbank(<32 x s32>) = COPY [[BITCAST]](<32 x s32>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), [[PHI1]](p0), [[COPY2]](<32 x s32>), [[PHI2]](s32)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:vregbank(<32 x s32>) = COPY [[INT1]](<32 x s32>)
  ; CHECK-NEXT:   [[BITCAST1:%[0-9]+]]:vregbank(<16 x s64>) = G_BITCAST [[COPY3]](<32 x s32>)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    liveins: $p0

    %0:_(p0) = COPY $p0
    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<16 x s64>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
    %21:_(s32) = G_PHI %4(s32), %bb.0, %29(s32), %bb.1
    %23:_(<16 x s64>) = G_PHI %66(<16 x s64>), %bb.0, %25(<16 x s64>), %bb.1
    %24:_(<32 x s32>) = G_BITCAST %23
    %27:_(p0), %28:_(<32 x s32>), %29:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %19(p0), %24(<32 x s32>), %21(s32)
    %25:_(<16 x s64>) = G_BITCAST %28
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 7:  The instruction %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
# should be mapped to fiforegbank.  Now we are looking through a copy.

---
name:            test_fifo.ld.fill.copy
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_fifo.ld.fill.copy
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %6(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:ptrregbank(p0) = G_PHI [[COPY]](p0), %bb.0, %8(p0), %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gprregbank(s32) = G_PHI [[C]](s32), %bb.0, %10(s32), %bb.1
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, %12(<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:fiforegbank(<32 x s32>) = COPY [[PHI3]](<32 x s32>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), [[PHI1]](p0), [[COPY1]](<32 x s32>), [[PHI2]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    liveins: $p0

    %0:_(p0) = COPY $p0
    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
    %21:_(s32) = G_PHI %4(s32), %bb.0, %29(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
    %24:_(<32 x s32>) = COPY %23
    %27:_(p0), %28:_(<32 x s32>), %29:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %19(p0), %24(<32 x s32>), %21(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...


# Test 8:  The instruction %23:_(<64 x s16>) = G_PHI %66(<64 x s16>), %bb.0, %25(<64 x s16>), %bb.1
# should be mapped to accregbank. Now we are looking through a bitcast.

---
name:            test_acc.vmac.bitcast
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_acc.vmac.bitcast
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:accregbank(<64 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vregbank(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %6(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:accregbank(<64 x s16>) = G_PHI [[DEF]](<64 x s16>), %bb.0, %8(<64 x s16>), %bb.1
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:accregbank(<32 x s32>) = G_BITCAST [[PHI1]](<64 x s16>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), [[DEF1]](<32 x s16>), [[DEF1]](<32 x s16>), [[BITCAST]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[BITCAST1:%[0-9]+]]:accregbank(<64 x s16>) = G_BITCAST [[INT]](<32 x s32>)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr

  bb.0:
    successors: %bb.1

    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<64 x s16>) = G_IMPLICIT_DEF
    %77:_(<32 x s16>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %23:_(<64 x s16>) = G_PHI %66(<64 x s16>), %bb.0, %25(<64 x s16>), %bb.1
    %24:_(<32 x s32>) = G_BITCAST %23
    %100:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %77(<32 x s16>), %77(<32 x s16>), %24(<32 x s32>), %4(s32)
    %25:_(<64 x s16>) = G_BITCAST %100
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 9:  The instruction %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %100(<32 x s32>), %bb.1
# should be mapped to accregbank. Now we are looking through a copy.

---
name:            test_acc.vmac.copy
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_acc.vmac.copy
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vregbank(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %6(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:accregbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, %8(<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[PHI1]](<32 x s32>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), [[DEF1]](<32 x s16>), [[DEF1]](<32 x s16>), [[COPY]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr

  bb.0:
    successors: %bb.1

    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %77:_(<32 x s16>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %100(<32 x s32>), %bb.1
    %24:_(<32 x s32>) = COPY %23
    %100:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %77(<32 x s16>), %77(<32 x s16>), %24(<32 x s32>), %4(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 10:  The instruction %23:_(<32 x s32>) = G_PHI %67(<32 x s32>), %bb.0, %100(<32 x s32>), %bb.1
# should be mapped to accregbank. Now we are looking through two copies.

---
name:            test_acc.vmac.copy.copy
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_acc.vmac.copy.copy
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:accregbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[DEF]](<32 x s32>)
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vregbank(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %7(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:accregbank(<32 x s32>) = G_PHI [[COPY]](<32 x s32>), %bb.0, %9(<32 x s32>), %bb.1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:accregbank(<32 x s32>) = COPY [[PHI1]](<32 x s32>)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), [[DEF1]](<32 x s16>), [[DEF1]](<32 x s16>), [[COPY1]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr

  bb.0:
    successors: %bb.1

    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %67:_(<32 x s32>) = COPY %66
    %77:_(<32 x s16>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %67(<32 x s32>), %bb.0, %100(<32 x s32>), %bb.1
    %24:_(<32 x s32>) = COPY %23
    %100:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %77(<32 x s16>), %77(<32 x s16>), %24(<32 x s32>), %4(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...

# Test 11:  The instruction %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
# We need to look to all users to avoid mapping to vector register bank.

---
name:            test_fifo.ld.fill.store
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_fifo.ld.fill.store
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(s32) = G_PHI [[C2]](s32), %bb.0, %7(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:ptrregbank(p0) = G_PHI [[COPY]](p0), %bb.0, %9(p0), %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gprregbank(s32) = G_PHI [[C]](s32), %bb.0, %11(s32), %bb.1
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fiforegbank(<32 x s32>) = G_PHI [[DEF]](<32 x s32>), %bb.0, %13(<32 x s32>), %bb.1
  ; CHECK-NEXT:   G_STORE [[PHI3]](<32 x s32>), [[COPY1]](p0) :: (store (<32 x s32>))
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), [[PHI1]](p0), [[PHI3]](<32 x s32>), [[PHI2]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gprregbank(s32) = G_ADD [[PHI]], [[C1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    liveins: $p0, $p1

    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %4:_(s32) = G_CONSTANT i32 10
    %63:_(s32) = G_CONSTANT i32 1
    %66:_(<32 x s32>) = G_IMPLICIT_DEF
    %3:_(s32) = G_CONSTANT i32 1
    G_BR %bb.1

  bb.1:
    successors: %bb.1(0x04000000), %bb.2(0x7c000000)

    %18:_(s32) = G_PHI %3(s32), %bb.0, %64(s32), %bb.1
    %19:_(p0) = G_PHI %0(p0), %bb.0, %27(p0), %bb.1
    %21:_(s32) = G_PHI %4(s32), %bb.0, %29(s32), %bb.1
    %23:_(<32 x s32>) = G_PHI %66(<32 x s32>), %bb.0, %28(<32 x s32>), %bb.1
    G_STORE %23:_(<32 x s32>), %1:_(p0) :: (store (<32 x s32>))
    %27:_(p0), %28:_(<32 x s32>), %29:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.fifo.ld.fill), %19(p0), %23(<32 x s32>), %21(s32)
    %64:_(s32) = G_ADD %18, %63
    %69:_(s32) = G_ICMP intpred(eq), %64(s32), %4
    G_BRCOND %69(s32), %bb.1
    G_BR %bb.2

  bb.2:
    PseudoRET implicit $lr

...
