# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name:            copy_512bit_acc64
legalized:       true

body: |
  bb.0:
    liveins: $bmll0
    ; CHECK-LABEL: name: copy_512bit_acc64
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<8 x s64>)
    %0:_(<8 x s64>) = COPY $bmll0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_1024bit_acc64
legalized:       true

body: |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: copy_1024bit_acc64
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<16 x s64>)
    %0:_(<16 x s64>) = COPY $cml0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_2048bit_acc64
legalized:       true

body: |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: copy_2048bit_acc64
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<32 x s64>)
    %0:_(<32 x s64>) = COPY $dm0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_512bit_acc32
legalized:       true

body: |
  bb.0:
    liveins: $bmll0
    ; CHECK-LABEL: name: copy_512bit_acc32
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $bmll0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_1024bit_acc32
legalized:       true

body: |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: copy_1024bit_acc32
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<32 x s32>)
    %0:_(<32 x s32>) = COPY $cml0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_2048bit_acc32
legalized:       true

body: |
  bb.0:
    liveins: $cml0
    ; CHECK-LABEL: name: copy_2048bit_acc32
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<64 x s32>)
    %0:_(<64 x s32>) = COPY $dm0
    PseudoRET implicit $lr, implicit %0
...

---
name: copy_exp32
legalized: true

body: |
  bb.0:
    liveins: $el0
    ; CHECK-LABEL: name: copy_exp32
    ; CHECK: liveins: $el0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $el0
    %0:_(s32) = COPY $el0
...

---
name: copy_exp64
legalized: true

body: |
  bb.0:
    liveins: $el0
    ; CHECK-LABEL: name: copy_exp64
    ; CHECK: liveins: $el0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s64) = COPY $e0
    %0:_(s64) = COPY $e0
...
