# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_4x64
legalized:       true
body:             |
  bb.0.entry:
    liveins: $l0, $r0
    ; CHECK-LABEL: name: test_4x64
    ; CHECK: liveins: $l0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<4 x s64>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s64) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:vregbank(<4 x s64>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s64), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_INSERT_VECTOR_ELT]](<4 x s64>)
    %0:_(<4 x s64>) = COPY $wl0
    %1:_(s64) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<4 x s64>) = G_AIE_INSERT_VECTOR_ELT %0(<4 x s64>), %1(s64), %2(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_8x64
legalized:       true
body:             |
  bb.0.entry:
    liveins: $l0, $r0
    ; CHECK-LABEL: name: test_8x64
    ; CHECK: liveins: $l0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<8 x s64>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s64) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<8 x s64>) = COPY [[COPY]](<8 x s64>)
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:accregbank(<8 x s64>) = G_AIE_INSERT_VECTOR_ELT [[COPY2]], [[COPY1]](s64), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[AIE_INSERT_VECTOR_ELT]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<8 x s64>) = COPY $x0
    %1:_(s64) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<8 x s64>) = G_AIE_INSERT_VECTOR_ELT %0(<8 x s64>), %1(s64), %2(s32)
    $x0 = COPY %3
    PseudoRET implicit $lr, implicit $x0
...
---
name:            test_8x32
legalized:       true
body:             |
  bb.0.entry:
    liveins: $l0, $r0
    ; CHECK-LABEL: name: test_8x32
    ; CHECK: liveins: $l0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s64) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:vregbank(<8 x s32>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s64), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_INSERT_VECTOR_ELT]](<8 x s32>)
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(s64) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<8 x s32>) = G_AIE_INSERT_VECTOR_ELT %0(<8 x s32>), %1(s64), %2(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_16x16
legalized:       true
body:             |
  bb.0.entry:
    liveins: $l0, $r0
    ; CHECK-LABEL: name: test_16x16
    ; CHECK: liveins: $l0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s64) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:vregbank(<16 x s16>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s64), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_INSERT_VECTOR_ELT]](<16 x s16>)
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(s64) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<16 x s16>) = G_AIE_INSERT_VECTOR_ELT %0(<16 x s16>), %1(s64), %2(s32)
    PseudoRET implicit $lr, implicit %3
...

---
name:            test_32x8
legalized:       true
body:             |
  bb.0.entry:
    liveins: $l0, $r0
    ; CHECK-LABEL: name: test_32x8
    ; CHECK: liveins: $l0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s64) = COPY $l0
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_INSERT_VECTOR_ELT:%[0-9]+]]:vregbank(<32 x s8>) = G_AIE_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s64), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_INSERT_VECTOR_ELT]](<32 x s8>)
    %0:_(<32 x s8>) = COPY $wl0
    %1:_(s64) = COPY $l0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<32 x s8>) = G_AIE_INSERT_VECTOR_ELT %0(<32 x s8>), %1(s64), %2(s32)
    PseudoRET implicit $lr, implicit %3
...
