# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=COMMON
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=COMMON
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=COMMON
---
name:            test_vec_elem64
legalized: true
body:             |
  bb.1.entry:
   liveins: $bmll0
    ; COMMON-LABEL: name: test_vec_elem64
    ; COMMON: liveins: $bmll0
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<8 x s64>) = COPY [[COPY]](<8 x s64>)
    ; COMMON-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<2 x s64>) = G_AIE_UNPAD_VECTOR [[COPY1]](<8 x s64>)
    ; COMMON-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:vregbank(<4 x s64>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<2 x s64>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit [[AIE_PAD_VECTOR_UNDEF]](<4 x s64>)
    %3:_(<8 x s64>) = COPY $bmll0
    %0:_(<2 x s64>) = G_AIE_UNPAD_VECTOR %3(<8 x s64>)
    %1:_(<4 x s64>) = G_AIE_PAD_VECTOR_UNDEF %0(<2 x s64>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_vec_elem32
legalized: true
body:             |
  bb.1.entry:
   liveins: $bmll0
    ; COMMON-LABEL: name: test_vec_elem32
    ; COMMON: liveins: $bmll0
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; COMMON-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY1]](<16 x s32>)
    ; COMMON-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:vregbank(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<4 x s32>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit [[AIE_PAD_VECTOR_UNDEF]](<8 x s32>)
    %3:_(<16 x s32>) = COPY $bmll0
    %0:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %3(<16 x s32>)
    %1:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF %0(<4 x s32>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_vec_elem16
legalized: true
body:             |
  bb.1.entry:
   liveins: $bmll0
    ; COMMON-LABEL: name: test_vec_elem16
    ; COMMON: liveins: $bmll0
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s16>) = COPY $bmll0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY [[COPY]](<32 x s16>)
    ; COMMON-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<8 x s16>) = G_AIE_UNPAD_VECTOR [[COPY1]](<32 x s16>)
    ; COMMON-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:vregbank(<16 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<8 x s16>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit [[AIE_PAD_VECTOR_UNDEF]](<16 x s16>)
    %3:_(<32 x s16>) = COPY $bmll0
    %0:_(<8 x s16>) = G_AIE_UNPAD_VECTOR %3(<32 x s16>)
    %1:_(<16 x s16>) = G_AIE_PAD_VECTOR_UNDEF %0(<8 x s16>)
    PseudoRET implicit $lr, implicit %1
...
---
name:            test_vec_elem8
legalized: true
body:             |
  bb.1.entry:
   liveins: $bmll0
    ; COMMON-LABEL: name: test_vec_elem8
    ; COMMON: liveins: $bmll0
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s8>) = COPY $bmll0
    ; COMMON-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY [[COPY]](<64 x s8>)
    ; COMMON-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<16 x s8>) = G_AIE_UNPAD_VECTOR [[COPY1]](<64 x s8>)
    ; COMMON-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:vregbank(<32 x s8>) = G_AIE_PAD_VECTOR_UNDEF [[AIE_UNPAD_VECTOR]](<16 x s8>)
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit [[AIE_PAD_VECTOR_UNDEF]](<32 x s8>)
    %3:_(<64 x s8>) = COPY $bmll0
    %0:_(<16 x s8>) = G_AIE_UNPAD_VECTOR %3(<64 x s8>)
    %1:_(<32 x s8>) = G_AIE_PAD_VECTOR_UNDEF %0(<16 x s8>)
    PseudoRET implicit $lr, implicit %1
...
