# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2p -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name: load_vector_4x64
legalized: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_vector_4x64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<4 x s64>) = G_LOAD [[COPY]](p0) :: (load (<4 x s64>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[LOAD]](<4 x s64>)
    %0:_(p0) = COPY $p0
    %1:_(<4 x s64>) = G_LOAD %0 :: (load (<4 x s64>), align 32)
    PseudoRET implicit $lr, implicit %1
...

---
name: store_vector_4x64
legalized: true

body: |
  bb.0:
    liveins: $wl0, $p0
    ; CHECK-LABEL: name: store_vector_4x64
    ; CHECK: liveins: $wl0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<4 x s64>) = COPY $wl0
    ; CHECK-NEXT: G_STORE [[COPY1]](<4 x s64>), [[COPY]](p0) :: (store (<4 x s64>))
    %0:_(p0) = COPY $p0
    %1:_(<4 x s64>) = COPY $wl0
    G_STORE %1, %0 :: (store (<4 x s64>))
...
