# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Constrained-callee variant of the load-into-pointer fold: a
# G_LOAD(s20) whose only user is a G_INTTOPTR feeding the callee
# operand of PseudoJL_IND. The IRTranslator constrains the
# G_INTTOPTR's destination to the `ep` regclass; the combine copies
# the constrained vreg with a COPY from the new p0-typed load
# destination instead of replacing it directly.
#
# RUN: llc -mtriple=aie2ps -run-pass=aie-prelegalizer-combiner \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name: load_inttoptr_into_jl_ind
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: load_inttoptr_into_jl_ind
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load (p0), align 4)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep(p0) = COPY [[LOAD]](p0)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoJL_IND [[COPY1]](p0), csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_LOAD %0:_(p0) :: (load (s20), align 4)
    %2:ep(p0) = G_INTTOPTR %1
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    PseudoJL_IND %2(p0), csr_aie2ps, implicit-def $lr
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    PseudoRET implicit $lr
...
