# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple=aie2ps -run-pass=aie-postlegalizer-custom-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_v16_redundant_conversion_eliminated
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: test_v16_redundant_conversion_eliminated
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), [[INT]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT1]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %0(<16 x s16>)
    %2:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %1(<16 x s32>)
    $wl0 = COPY %2(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...
---
name: test_v32_redundant_conversion_eliminated
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: test_v32_redundant_conversion_eliminated
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32bf16.to.v32accfloat), [[COPY]](<32 x s16>)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), [[INT]](<32 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[INT1]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32bf16.to.v32accfloat), %0(<32 x s16>)
    %2:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %1(<32 x s32>)
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...
---
name: test_accumulator_multiple_uses
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: test_accumulator_multiple_uses
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), [[INT]](<16 x s32>)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT1]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0, implicit $wl0
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %0(<16 x s16>)
    %2:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %1(<16 x s32>)
    $bmll0 = COPY %1(<16 x s32>)
    $wl0 = COPY %2(<16 x s16>)
    PseudoRET implicit $lr, implicit $bmll0, implicit $wl0
...
---
name: test_non_paired_conversion_not_eliminated
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: test_non_paired_conversion_not_eliminated
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %0(<16 x s16>)
    $bmll0 = COPY %1(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...
---
name: test_only_to_bf16_not_eliminated
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_only_to_bf16_not_eliminated
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<16 x s32>) = COPY $bmll0
    %1:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %0(<16 x s32>)
    $wl0 = COPY %1(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...
---
name: test_v16_in_computation_chain
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: test_v16_in_computation_chain
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s16>) = COPY $wl1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), [[COPY1]](<16 x s16>)
    ; CHECK-NEXT: [[FADD:%[0-9]+]]:_(<16 x s32>) = G_FADD [[INT]], [[INT1]]
    ; CHECK-NEXT: [[INT2:%[0-9]+]]:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), [[FADD]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT2]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(<16 x s16>) = COPY $wl1
    %2:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %0(<16 x s16>)
    %3:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %1(<16 x s16>)
    %4:_(<16 x s32>) = G_FADD %2, %3
    %5:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %4(<16 x s32>)
    $wl0 = COPY %5(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...
---
name: test_v16_from_float_conversion_not_eliminated
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_v16_from_float_conversion_not_eliminated
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), [[INT]](<16 x s16>)
    ; CHECK-NEXT: $bmll0 = COPY [[INT1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %0:_(<16 x s32>) = COPY $bmll0
    %1:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %0(<16 x s32>)
    %2:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %1(<16 x s16>)
    $bmll0 = COPY %2(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...
