; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2ps -stop-after=irtranslator -verify-machineinstrs  %s -o - 2>&1 | FileCheck %s
; ModuleID = 't.cpp'
source_filename = "t.cpp"
target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2ps"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16i(i32 noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16i
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[COPY]](s32)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[SITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = sitofp i32 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef i32 @_Z6to_intDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z6to_intDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[EVEC]](s32)
  ; CHECK-NEXT:   $r0 = COPY [[FPTOSI]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptosi half %a to i32
  ret i32 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16j(i32 noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16j
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[UITOFP:%[0-9]+]]:_(s32) = G_UITOFP [[COPY]](s32)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[UITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = uitofp i32 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef i32 @_Z7to_uintDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z7to_uintDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOUI:%[0-9]+]]:_(s32) = G_FPTOUI [[EVEC]](s32)
  ; CHECK-NEXT:   $r0 = COPY [[FPTOUI]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptoui half %a to i32
  ret i32 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16s(i16 noundef signext %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16s
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[COPY]], 16
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[ASSERT_SEXT]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[TRUNC]](s16)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[SITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = sitofp i16 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef signext i16 @_Z8to_shortDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z8to_shortDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOSI:%[0-9]+]]:_(s16) = G_FPTOSI [[EVEC]](s32)
  ; CHECK-NEXT:   [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[FPTOSI]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[SEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptosi half %a to i16
  ret i16 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16t(i16 noundef zeroext %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16t
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[COPY]], 16
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[ASSERT_ZEXT]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[UITOFP:%[0-9]+]]:_(s32) = G_UITOFP [[TRUNC]](s16)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[UITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = uitofp i16 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef zeroext i16 @_Z9to_ushortDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z9to_ushortDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOUI:%[0-9]+]]:_(s16) = G_FPTOUI [[EVEC]](s32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[FPTOUI]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ZEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptoui half %a to i16
  ret i16 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16c(i8 noundef signext %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16c
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[COPY]], 8
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[ASSERT_SEXT]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[TRUNC]](s8)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[SITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = sitofp i8 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef signext i8 @_Z7to_charDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z7to_charDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOSI:%[0-9]+]]:_(s8) = G_FPTOSI [[EVEC]](s32)
  ; CHECK-NEXT:   [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[FPTOSI]](s8)
  ; CHECK-NEXT:   $r0 = COPY [[SEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptosi half %a to i8
  ret i8 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16h(i8 noundef zeroext %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16h
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[ASSERT_ZEXT:%[0-9]+]]:_(s32) = G_ASSERT_ZEXT [[COPY]], 8
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[ASSERT_ZEXT]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[UITOFP:%[0-9]+]]:_(s32) = G_UITOFP [[TRUNC]](s8)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[UITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = uitofp i8 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef zeroext i8 @_Z8to_ucharDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z8to_ucharDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOUI:%[0-9]+]]:_(s8) = G_FPTOUI [[EVEC]](s32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[FPTOUI]](s8)
  ; CHECK-NEXT:   $r0 = COPY [[ZEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptoui half %a to i8
  ret i8 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16l(i32 noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16l
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[COPY]](s32)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[SITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = sitofp i32 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef i32 @_Z7to_longDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z7to_longDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[EVEC]](s32)
  ; CHECK-NEXT:   $r0 = COPY [[FPTOSI]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptosi half %a to i32
  ret i32 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16m(i32 noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16m
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[UITOFP:%[0-9]+]]:_(s32) = G_UITOFP [[COPY]](s32)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[UITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = uitofp i32 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef i32 @_Z8to_ulongDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z8to_ulongDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOUI:%[0-9]+]]:_(s32) = G_FPTOUI [[EVEC]](s32)
  ; CHECK-NEXT:   $r0 = COPY [[FPTOUI]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = fptoui half %a to i32
  ret i32 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16x(i64 noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16x
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[MV]](s64)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[SITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = sitofp i64 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef i64 @_Z11to_longlongDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z11to_longlongDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOSI:%[0-9]+]]:_(s64) = G_FPTOSI [[EVEC]](s32)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[FPTOSI]](s64)
  ; CHECK-NEXT:   $r0 = COPY [[UV]](s32)
  ; CHECK-NEXT:   $r1 = COPY [[UV1]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1
entry:
  %conv = fptosi half %a to i64
  ret i64 %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef half @_Z10to_float16y(i64 noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z10to_float16y
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s32>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[UITOFP:%[0-9]+]]:_(s32) = G_UITOFP [[MV]](s64)
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[UITOFP]](s32), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[IVEC]](<32 x s32>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s16>), [[C]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[EVEC]](s16)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  %conv = uitofp i64 %a to half
  ret half %conv
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef i64 @_Z12to_ulonglongDF16_(half noundef %a) local_unnamed_addr #0 {
  ; CHECK-LABEL: name: _Z12to_ulonglongDF16_
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[C]](s32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[IVEC]](<32 x s16>)
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s32>), [[C]](s32)
  ; CHECK-NEXT:   [[FPTOUI:%[0-9]+]]:_(s64) = G_FPTOUI [[EVEC]](s32)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[FPTOUI]](s64)
  ; CHECK-NEXT:   $r0 = COPY [[UV]](s32)
  ; CHECK-NEXT:   $r1 = COPY [[UV1]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1
entry:
  %conv = fptoui half %a to i64
  ret i64 %conv
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 20.0.0git "}
