# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VINSERT_32_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x2
    ; CHECK-LABEL: name: VINSERT_32_bf
    ; CHECK: liveins: $r0, $r1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY $r1
    ; CHECK-NEXT: [[VINSERT_32_mR29_insert:%[0-9]+]]:vec512 = VINSERT_32_mR29_insert [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_32_mR29_insert]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(<2 x s16>) = COPY $r1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vinsert32.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<2 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VINSERT_64_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0, $r0, $x2
    ; CHECK-LABEL: name: VINSERT_64_bf
    ; CHECK: liveins: $l0, $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VINSERT_64_mR29_insert:%[0-9]+]]:vec512 = VINSERT_64_mR29_insert [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_64_mR29_insert]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(<4 x s16>) = COPY $l0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vinsert64.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<4 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VINSERT_32_bf_c
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VINSERT_32_bf_c
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r1
    ; CHECK-NEXT: [[VINSERT_32_mR29_insert:%[0-9]+]]:vec512 = VINSERT_32_mR29_insert [[COPY]], [[MOV_RLC_imm11_pseudo]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_32_mR29_insert]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = G_CONSTANT i32 4
    %3:gprregbank(<2 x s16>) = COPY $r1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vinsert32.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<2 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VINSERT_64_bf_c
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0, $x2
    ; CHECK-LABEL: name: VINSERT_64_bf_c
    ; CHECK: liveins: $l0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VINSERT_64_mR29_insert:%[0-9]+]]:vec512 = VINSERT_64_mR29_insert [[COPY]], [[MOV_RLC_imm11_pseudo]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_64_mR29_insert]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = G_CONSTANT i32 3
    %3:gprregbank(<4 x s16>) = COPY $l0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vinsert64.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<4 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VINSERT_32_bf_0
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VINSERT_32_bf_0
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r1
    ; CHECK-NEXT: [[VINSERT_32_mIdxImm0_:%[0-9]+]]:vec512 = VINSERT_32_mIdxImm0 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_32_mIdxImm0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %3:gprregbank(<2 x s16>) = COPY $r1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vinsert32.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<2 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VINSERT_64_bf_0
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0, $x2
    ; CHECK-LABEL: name: VINSERT_64_bf_0
    ; CHECK: liveins: $l0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VINSERT_64_mIdxImm0_:%[0-9]+]]:vec512 = VINSERT_64_mIdxImm0 [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VINSERT_64_mIdxImm0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %3:gprregbank(<4 x s16>) = COPY $l0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vinsert64.bf512), %1:vregbank(<32 x s16>), %2:gprregbank(s32), %3:gprregbank(<4 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...
