# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name: smax_s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: smax_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mry8 = COPY $r1
    ; CHECK-NEXT: [[MAX:%[0-9]+]]:mlockid_reg = MAX [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[MAX]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_SMAX %0, %1
    $r0 = COPY %2
...

---
name: smin_s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: smin_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mry8 = COPY $r1
    ; CHECK-NEXT: [[MIN:%[0-9]+]]:mlockid_reg = MIN [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[MIN]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_SMIN %0, %1
    $r0 = COPY %2
...

---
name: umax_s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: umax_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mry8 = COPY $r1
    ; CHECK-NEXT: [[MAXU:%[0-9]+]]:mlockid_reg = MAXU [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[MAXU]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_UMAX %0, %1
    $r0 = COPY %2
...

---
name: umin_s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: umin_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mry8 = COPY $r1
    ; CHECK-NEXT: [[MINU:%[0-9]+]]:mlockid_reg = MINU [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[MINU]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_UMIN %0, %1
    $r0 = COPY %2
...
