# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck --check-prefix=AIE2PS %s
...
---
name: load_s64
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ;AIE2PS-LABEL: name:            load_s64

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[LDA__1:%[0-9]+]]:el = LDA_dml_lda_scalar_L_ld_idx_imm [[COPY_0]], 0 :: (load (s64), align 4)
    ;AIE2PS-NEXT: $l0 = COPY [[LDA__1]]
    ;AIE2PS-NEXT: PseudoRET implicit $lr, implicit $l0

    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s64) = G_LOAD %0 :: (load (s64), align 4)
    $l0 = COPY %1
    PseudoRET implicit $lr, implicit $l0

---
---
name: pre-inc-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $m0
    ;AIE2PS-LABEL: name:            pre-inc-load

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[COPY_1:%[0-9]+]]:edj = COPY $m0
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 10
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ;AIE2PS-NEXT: [[LDA__4:%[0-9]+]]:el = LDA_dml_lda_scalar_L_ld_idx [[COPY_0]], [[COPY_1]] :: (load (s64))
    ;AIE2PS-NEXT: [[LDA__5:%[0-9]+]]:el = LDA_dml_lda_scalar_L_ld_idx [[COPY_0]], [[MOV__2]] :: (load (s64))
    ;AIE2PS-NEXT: [[LDA__6:%[0-9]+]]:el = LDA_dml_lda_scalar_L_ld_idx [[COPY_0]], [[MOV__3]] :: (load (s64))
    ;AIE2PS-NEXT: [[LDA__7:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY_0]], 16 :: (load (p0), align 4)
    ;AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA__4]], implicit [[LDA__5]], implicit [[LDA__6]], implicit [[LDA__7]]

    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %6:modregbank(s20) = G_CONSTANT i20 10
    %7:modregbank(s20) = G_CONSTANT i20 16
    %8:gprregbank(s64) = G_AIE_OFFSET_LOAD %0, %5 :: (load (s64))
    %9:gprregbank(s64) = G_AIE_OFFSET_LOAD %0, %6 :: (load (s64))
    %10:gprregbank(s64) = G_AIE_OFFSET_LOAD %0, %7 :: (load (s64))
    %11:ptrregbank(p0) = G_AIE_OFFSET_LOAD %0, %7 :: (load (p0))
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11

...
---
name: post-inc-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0
    ;AIE2PS-LABEL: name:            post-inc-load

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[COPY_1:%[0-9]+]]:em = COPY $m0
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:em = MOV_PD_imm11_pseudo 10
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ;AIE2PS-NEXT: [[LDA__4:%[0-9]+]]:el, [[LDA__5:%[0-9]+]]:ep = LDA_dml_lda_scalar_L_ld_pstm_nrm [[COPY_0]], [[COPY_1]] :: (load (s64))
    ;AIE2PS-NEXT: [[LDA__6:%[0-9]+]]:el, [[LDA__7:%[0-9]+]]:ep = LDA_dml_lda_scalar_L_ld_pstm_nrm [[LDA__5]], [[MOV__2]] :: (load (s64))
    ;AIE2PS-NEXT: [[LDA__8:%[0-9]+]]:el, [[LDA__9:%[0-9]+]]:ep = LDA_dml_lda_scalar_L_ld_pstm_nrm [[COPY_0]], [[MOV__3]] :: (load (s64))
    ;AIE2PS-NEXT: [[LDA__10:%[0-9]+]]:ep_as_32bit, [[COPY_1]]1:ep = LDA_dms_lda_scalar_ld_pstm_nrm_imm [[COPY_0]], 16 :: (load (p0), align 4)
    ;AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA__4]], implicit [[LDA__6]], implicit [[LDA__8]], implicit [[LDA__10]]

    %0:ptrregbank(p0) = COPY $p0
    %5:modregbank(s20) = COPY $m0
    %6:modregbank(s20) = G_CONSTANT i20 10
    %7:modregbank(s20) = G_CONSTANT i20 16
    %8:gprregbank(s64), %11:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %5 :: (load (s64))
    %9:gprregbank(s64), %12:ptrregbank(p0) = G_AIE_POSTINC_LOAD %11, %6 :: (load (s64))
    %10:gprregbank(s64), %13:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (s64))
    %14:ptrregbank(p0), %15:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (p0))
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %14

...
---
name: post-inc-2d-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0
    ;AIE2PS-LABEL: name:            post-inc-2d-load

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[MOV__1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ;AIE2PS-NEXT: [[MOV__4:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ;AIE2PS-NEXT: [[REG__8:%[0-9]+]]:ed = REG_SEQUENCE [[MOV__1]], %subreg.sub_mod, [[MOV__3]], %subreg.sub_dim_size, [[MOV__2]], %subreg.sub_dim_stride, [[MOV__4]], %subreg.sub_dim_count
    ;AIE2PS-NEXT: [[LDA__5:%[0-9]+]]:el, [[LDA__6:%[0-9]+]]:ep, [[LDA__7:%[0-9]+]]:edc = LDA_2D_dml_lda_scalar_L [[COPY_0]], [[REG__8]] :: (load (s64))
    ;AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA__5]]


    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %5:gprregbank(s64), %6:ptrregbank(p0), %7:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (s64))
    PseudoRET implicit $lr, implicit %5

...
---
name: post-inc-3d-load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $l0
    ;AIE2PS-LABEL: name:            post-inc-3d-load

    ;AIE2PS: [[COPY_0:%[0-9]+]]:el = COPY $l0
    ;AIE2PS-NEXT: [[MOV__1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ;AIE2PS-NEXT: [[MOV__4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ;AIE2PS-NEXT: [[MOV__5:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ;AIE2PS-NEXT: [[MOV__6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ;AIE2PS-NEXT: [[MOV__7:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ;AIE2PS-NEXT: [[MOV__1]]3:edc = COPY [[MOV__5]]
    ;AIE2PS-NEXT: [[MOV__1]]4:edn = COPY [[MOV__6]]
    ;AIE2PS-NEXT: [[MOV__1]]2:eds = REG_SEQUENCE %1, %subreg.sub_mod, [[MOV__4]], %subreg.sub_dim_size, [[MOV__2]], %subreg.sub_dim_stride, %13, %subreg.sub_dim_count, %14, %subreg.sub_hi_dim_then_sub_dim_size, [[MOV__3]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV__7]], %subreg.sub_hi_dim_then_sub_dim_count
    ;AIE2PS-NEXT: [[MOV__1]]5:ep = COPY [[COPY_0]]
    ;AIE2PS-NEXT: [[LDA__8:%[0-9]+]]:el, [[LDA__9:%[0-9]+]]:ep, [[LDA__10:%[0-9]+]]:edcl, [[MOV__1]]1:edch = LDA_3D_dml_lda_scalar_L %15, %12 :: (load (s64))
    ;AIE2PS-NEXT: PseudoRET implicit $lr, implicit [[LDA__8]]

    %0:gprregbank(s64) = COPY $l0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %8:gprregbank(s64), %9:ptrregbank(p0), %10:modregbank(s20), %11:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %5, %6, %7 :: (load (s64))
    PseudoRET implicit $lr, implicit %8
...
