# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Tests for VLDA_UPS combining using the canAdvanceOp fallback path.
#
# When canDelayMemOp fails (e.g., due to an intervening store), we can
# still combine by advancing the combined instruction to the load's position
# if canAdvanceOp succeeds (SideEffectsAreChecked=true).
#
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDA_UPS_advance_intervening_store
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0, $wl0

    ; CHECK-LABEL: name: VLDA_UPS_advance_intervening_store
    ; CHECK: liveins: $p0, $p1, $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY2]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1 [[COPY4]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: VST_dmw_sts_w_st_idx_imm [[COPY3]], [[COPY1]], 0 :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:vregbank(<16 x s16>) = COPY $wl0
    %4:gprregbank(s32) = G_CONSTANT i32 1

    %5:vregbank(<16 x s16>) = G_LOAD %0:ptrregbank(p0) :: (load (<16 x s16>))

    G_STORE %3:vregbank(<16 x s16>), %1:ptrregbank(p0) :: (store (<16 x s16>))

    %6:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %4:gprregbank(s32)

    PseudoRET implicit $lr, implicit %6
...

---
name:            VLDA_UPS_advance_crupsmode_placement
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $wl0

    ; CHECK-LABEL: name: VLDA_UPS_advance_crupsmode_placement
    ; CHECK: liveins: $p0, $p1, $p2, $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY2]], 0 :: (load (s32))
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:es = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1 [[COPY5]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: VST_dmw_sts_w_st_idx_imm [[COPY4]], [[COPY1]], 0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $r1 = COPY [[LDA_dms_lda_scalar_ld_idx_imm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_]], implicit $r1
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:ptrregbank(p0) = COPY $p2
    %3:gprregbank(s32) = COPY $r0
    %4:vregbank(<16 x s16>) = COPY $wl0
    %5:gprregbank(s32) = G_CONSTANT i32 1

    %6:gprregbank(s32) = G_LOAD %2:ptrregbank(p0) :: (load (s32))

    %7:vregbank(<16 x s16>) = G_LOAD %0:ptrregbank(p0) :: (load (<16 x s16>))

    G_STORE %4:vregbank(<16 x s16>), %1:ptrregbank(p0) :: (store (<16 x s16>))

    %8:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %7:vregbank(<16 x s16>), %3:gprregbank(s32), %5:gprregbank(s32)

    $r1 = COPY %6:gprregbank(s32)

    PseudoRET implicit $lr, implicit %8, implicit $r1
...
