# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name:            unpack_I256_to_128lanes_of_I4
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl2

    ; CHECK-LABEL: name: unpack_I256_to_128lanes_of_I4
    ; CHECK: liveins: $r0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign0_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign0 [[COPY]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: $unpacksign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VUNPACK_mv_unpack_w_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s8>) = COPY $wl2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 1
    %0:vregbank(<64 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %1(<32 x s8>), %4(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            unpack_I256_to_64lanes_of_I8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl2

    ; CHECK-LABEL: name: unpack_I256_to_64lanes_of_I8
    ; CHECK: liveins: $r0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign0_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign0 [[COPY]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: $unpacksign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VUNPACK_mv_unpack_w_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s8>) = COPY $wl2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I16.I8), %1(<32 x s8>), %4(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            unpack_I512_to_256lanes_of_I4
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0

    ; CHECK-LABEL: name: unpack_I512_to_256lanes_of_I4
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_x_unpackSign0_:%[0-9]+]]:vec1024 = VUNPACK_mv_unpack_x_unpackSign0 [[COPY]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: $unpacksign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $y2 = COPY [[VUNPACK_mv_unpack_x_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<64 x s8>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 1
    %0:vregbank(<128 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I8.I4), %1(<64 x s8>), %4(s32)
    $y2 = COPY %0(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            unpack_I512_to_128lanes_of_I8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0

    ; CHECK-LABEL: name: unpack_I512_to_128lanes_of_I8
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_x_unpackSign0_:%[0-9]+]]:vec1024 = VUNPACK_mv_unpack_x_unpackSign0 [[COPY]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: $unpacksign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $y2 = COPY [[VUNPACK_mv_unpack_x_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<64 x s8>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 1
    %0:vregbank(<64 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %1(<64 x s8>), %4(s32)
    $y2 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            unpack_I256_to_128lanes_of_I4_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl2

    ; CHECK-LABEL: name: unpack_I256_to_128lanes_of_I4_signed
    ; CHECK: liveins: $r0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign1_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign1 [[COPY]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: $x0 = COPY [[VUNPACK_mv_unpack_w_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s8>) = COPY $wl2
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<64 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %1(<32 x s8>), %2(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            unpack_I256_to_64lanes_of_I8_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl2

    ; CHECK-LABEL: name: unpack_I256_to_64lanes_of_I8_signed
    ; CHECK: liveins: $r0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign1_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign1 [[COPY]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: $x0 = COPY [[VUNPACK_mv_unpack_w_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s8>) = COPY $wl2
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I16.I8), %1(<32 x s8>), %2(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            unpack_I512_to_256lanes_of_I4_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0

    ; CHECK-LABEL: name: unpack_I512_to_256lanes_of_I4_signed
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_x_unpackSign1_:%[0-9]+]]:vec1024 = VUNPACK_mv_unpack_x_unpackSign1 [[COPY]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: $y2 = COPY [[VUNPACK_mv_unpack_x_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<128 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I8.I4), %1(<64 x s8>), %2(s32)
    $y2 = COPY %0(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2

...
---
name:            unpack_I512_to_128lanes_of_I8_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0

    ; CHECK-LABEL: name: unpack_I512_to_128lanes_of_I8_signed
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_x_unpackSign1_:%[0-9]+]]:vec1024 = VUNPACK_mv_unpack_x_unpackSign1 [[COPY]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: $y2 = COPY [[VUNPACK_mv_unpack_x_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<64 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %1(<64 x s8>), %2(s32)
    $y2 = COPY %0(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2

...
