# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            _Z12test_shuffle6v64mx9S_j
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $e2, $e4, $g2, $g4, $r0, $x2, $x4

    ; CHECK-LABEL: name: _Z12test_shuffle6v64mx9S_j
    ; CHECK: liveins: $e2, $e4, $g2, $g4, $r0, $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mggs = COPY $g2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mees = COPY $e2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mggs = COPY $g4
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mees = COPY $e4
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mgs = COPY [[COPY1]].sub_lo_exp
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mes = COPY [[COPY2]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY7]], %subreg.sub_bfp_v256, killed [[COPY8]], %subreg.sub_bfp_g32, killed [[COPY9]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mgs = COPY [[COPY1]].sub_hi_exp
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mes = COPY [[COPY2]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY10]], %subreg.sub_bfp_v256, killed [[COPY11]], %subreg.sub_bfp_g32, killed [[COPY12]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_lo
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mgs = COPY [[COPY4]].sub_lo_exp
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mes = COPY [[COPY5]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY13]], %subreg.sub_bfp_v256, killed [[COPY14]], %subreg.sub_bfp_g32, killed [[COPY15]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_hi
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mgs = COPY [[COPY4]].sub_hi_exp
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mes = COPY [[COPY5]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY16]], %subreg.sub_bfp_v256, killed [[COPY17]], %subreg.sub_bfp_g32, killed [[COPY18]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mexa = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_egx:%[0-9]+]]:mexa = VSHUFFLE_vec_shuffle_egx [[REG_SEQUENCE2]], [[REG_SEQUENCE5]], [[COPY6]]
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mewlv_bis = COPY [[VSHUFFLE_vec_shuffle_egx]].sub_bfp320_lo
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:vec256 = COPY [[COPY19]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:mgs = COPY [[COPY19]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mes = COPY [[COPY19]].sub_bfp_e32
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mewhv = COPY [[VSHUFFLE_vec_shuffle_egx]].sub_bfp320_hi
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:vec256 = COPY [[COPY23]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:mgs = COPY [[COPY23]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mes = COPY [[COPY23]].sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY20]], %subreg.sub_256_lo, [[COPY24]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:mggs = REG_SEQUENCE [[COPY21]], %subreg.sub_lo_exp, [[COPY25]], %subreg.sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mees = REG_SEQUENCE [[COPY22]], %subreg.sub_lo_exp, [[COPY26]], %subreg.sub_hi_exp
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE6]]
    ; CHECK-NEXT: $g0 = COPY [[REG_SEQUENCE7]]
    ; CHECK-NEXT: $e0 = COPY [[REG_SEQUENCE8]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
    %3:vregbank(<16 x s32>) = COPY $x2
    %4:gprregbank(<2 x s32>) = COPY $g2
    %5:gprregbank(<2 x s32>) = COPY $e2
    %6:vregbank(<16 x s32>) = COPY $x4
    %7:gprregbank(<2 x s32>) = COPY $g4
    %8:gprregbank(<2 x s32>) = COPY $e4
    %9:gprregbank(s32) = COPY $r0
    %10:vregbank(<16 x s32>), %11:gprregbank(<2 x s32>), %12:gprregbank(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vshuffle.BFP640.BFP640.BFP640), %3(<16 x s32>), %4(<2 x s32>), %5(<2 x s32>), %6(<16 x s32>), %7(<2 x s32>), %8(<2 x s32>), %9(s32)
    $x0 = COPY %10(<16 x s32>)
    $g0 = COPY %11(<2 x s32>)
    $e0 = COPY %12(<2 x s32>)
    PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0

...
---
name:            _Z12test_shuffle7v128mx4S_j
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $eh2, $eh4, $el2, $el4, $fh2, $fh4, $fl2, $fl4, $gh2, $gh4, $gl2, $gl4, $r0, $wh2, $wh4, $wl2, $wl4

    ; CHECK-LABEL: name: _Z12test_shuffle7v128mx4S_j
    ; CHECK: liveins: $eh2, $eh4, $el2, $el4, $fh2, $fh4, $fl2, $fl4, $gh2, $gh4, $gl2, $gl4, $r0, $wh2, $wh4, $wl2, $wl4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $fl2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fh2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $gl2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gh2
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $el2
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $eh2
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY $wl4
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY $wh4
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:el = COPY $fl4
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:el = COPY $fh4
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:er = COPY $gl4
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:er = COPY $gh4
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:er = COPY $el4
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:er = COPY $eh4
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY]], %subreg.sub_few_bfp_w, [[COPY2]], %subreg.sub_few_bfp_f64, [[COPY4]], %subreg.sub_few_bfp_g32, [[COPY6]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY8]], %subreg.sub_few_bfp_w, [[COPY10]], %subreg.sub_few_bfp_f64, [[COPY12]], %subreg.sub_few_bfp_g32, [[COPY14]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY9]], %subreg.sub_few_bfp_w, [[COPY11]], %subreg.sub_few_bfp_f64, [[COPY13]], %subreg.sub_few_bfp_g32, [[COPY15]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[VSHUFFLE_vec_shuffle_fex:%[0-9]+]]:efexe = VSHUFFLE_vec_shuffle_fex [[REG_SEQUENCE2]], [[REG_SEQUENCE5]], [[COPY16]]
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mfewm = COPY [[VSHUFFLE_vec_shuffle_fex]].sub_bfp384_lo
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:vec256 = COPY [[COPY17]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mfs = COPY [[COPY17]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mgs = COPY [[COPY17]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:mes = COPY [[COPY17]].sub_few_bfp_e32
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mfewm = COPY [[VSHUFFLE_vec_shuffle_fex]].sub_bfp384_hi
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:vec256 = COPY [[COPY22]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mfs = COPY [[COPY22]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:mgs = COPY [[COPY22]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mes = COPY [[COPY22]].sub_few_bfp_e32
    ; CHECK-NEXT: $wl0 = COPY [[COPY18]]
    ; CHECK-NEXT: $wh0 = COPY [[COPY23]]
    ; CHECK-NEXT: $fl0 = COPY [[COPY19]]
    ; CHECK-NEXT: $fh0 = COPY [[COPY24]]
    ; CHECK-NEXT: $gl0 = COPY [[COPY20]]
    ; CHECK-NEXT: $gh0 = COPY [[COPY25]]
    ; CHECK-NEXT: $el0 = COPY [[COPY21]]
    ; CHECK-NEXT: $eh0 = COPY [[COPY26]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0
    %8:vregbank(<8 x s32>) = COPY $wl2
    %9:vregbank(<8 x s32>) = COPY $wh2
    %10:gprregbank(<2 x s32>) = COPY $fl2
    %11:gprregbank(<2 x s32>) = COPY $fh2
    %12:gprregbank(s32) = COPY $gl2
    %13:gprregbank(s32) = COPY $gh2
    %14:gprregbank(s32) = COPY $el2
    %15:gprregbank(s32) = COPY $eh2
    %16:vregbank(<8 x s32>) = COPY $wl4
    %17:vregbank(<8 x s32>) = COPY $wh4
    %18:gprregbank(<2 x s32>) = COPY $fl4
    %19:gprregbank(<2 x s32>) = COPY $fh4
    %20:gprregbank(s32) = COPY $gl4
    %21:gprregbank(s32) = COPY $gh4
    %22:gprregbank(s32) = COPY $el4
    %23:gprregbank(s32) = COPY $eh4
    %24:gprregbank(s32) = COPY $r0
    %25:vregbank(<8 x s32>), %26:vregbank(<8 x s32>), %27:gprregbank(<2 x s32>), %28:gprregbank(<2 x s32>), %29:gprregbank(s32), %30:gprregbank(s32), %31:gprregbank(s32), %32:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2ps.vshuffle.BFP768.BFP768.BFP768), %8(<8 x s32>), %9(<8 x s32>), %10(<2 x s32>), %11(<2 x s32>), %12(s32), %13(s32), %14(s32), %15(s32), %16(<8 x s32>), %17(<8 x s32>), %18(<2 x s32>), %19(<2 x s32>), %20(s32), %21(s32), %22(s32), %23(s32), %24(s32)
    $wl0 = COPY %25(<8 x s32>)
    $wh0 = COPY %26(<8 x s32>)
    $fl0 = COPY %27(<2 x s32>)
    $fh0 = COPY %28(<2 x s32>)
    $gl0 = COPY %29(s32)
    $gh0 = COPY %30(s32)
    $el0 = COPY %31(s32)
    $eh0 = COPY %32(s32)
    PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0

...
---
name:            _Z16test_fifo_ld_popRrPU3AS617v128mx4_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z16test_fifo_ld_popRrPU3AS617v128mx4_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_768_normal_pop_pseudo:%[0-9]+]]:mfexa, [[VLD_POP_768_normal_pop_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_768_normal_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_768_normal_pop_pseudo3:%[0-9]+]]:mrf2a = VLD_POP_768_normal_pop_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[LDA_dms_lda_scalar_ld_idx]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_normal_pop_pseudo]].sub_bfp384_lo
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mfs = COPY [[COPY3]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mgs = COPY [[COPY3]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mes = COPY [[COPY3]].sub_few_bfp_e32
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_normal_pop_pseudo]].sub_bfp384_hi
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY [[COPY8]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mfs = COPY [[COPY8]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mgs = COPY [[COPY8]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mes = COPY [[COPY8]].sub_few_bfp_e32
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_768_normal_pop_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:vec1024 = COPY [[VLD_POP_768_normal_pop_pseudo2]]
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:vec512 = COPY [[COPY13]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY14]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:vec512 = COPY [[COPY13]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY15]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_768_normal_pop_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: $wl0 = COPY [[COPY4]]
    ; CHECK-NEXT: $wh0 = COPY [[COPY9]]
    ; CHECK-NEXT: $fl0 = COPY [[COPY5]]
    ; CHECK-NEXT: $fh0 = COPY [[COPY10]]
    ; CHECK-NEXT: $gl0 = COPY [[COPY6]]
    ; CHECK-NEXT: $gh0 = COPY [[COPY11]]
    ; CHECK-NEXT: $el0 = COPY [[COPY7]]
    ; CHECK-NEXT: $eh0 = COPY [[COPY12]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0
    %8:ptrregbank(p0) = COPY $p0
    %9:ptrregbank(p0) = COPY $p1
    %10:modregbank(s20) = G_CONSTANT i20 128
    %12:ptrregbank(p0) = G_LOAD %8(p0) :: (dereferenceable load (p6) )
    %13:vregbank(<32 x s32>) = G_LOAD %9(p0) :: (dereferenceable load (<32 x s32>) )
    %14:gprregbank(s32) = G_AIE_OFFSET_LOAD %9(p0), %10(s20) :: (dereferenceable load (s32) )
    %29:fiforegbank(<32 x s32>) = COPY %13(<32 x s32>)
    %15:ptrregbank(p0), %16:fiforegbank(<32 x s32>), %17:gprregbank(s32), %18:vregbank(<8 x s32>), %19:vregbank(<8 x s32>), %20:gprregbank(<2 x s32>), %21:gprregbank(<2 x s32>), %22:gprregbank(s32), %23:gprregbank(s32), %24:gprregbank(s32), %25:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP768), %12(p0), %29(<32 x s32>), %14(s32)
    G_STORE %15(p0), %8(p0) :: (store (p6) )
    %30:vregbank(<32 x s32>) = COPY %16(<32 x s32>)
    G_STORE %30(<32 x s32>), %9(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %17(s32), %9(p0), %10(s20) :: (store (s32) )
    $wl0 = COPY %18(<8 x s32>)
    $wh0 = COPY %19(<8 x s32>)
    $fl0 = COPY %20(<2 x s32>)
    $fh0 = COPY %21(<2 x s32>)
    $gl0 = COPY %22(s32)
    $gh0 = COPY %23(s32)
    $el0 = COPY %24(s32)
    $eh0 = COPY %25(s32)
    PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0

...
---
name:            _Z18test_fifo_st_resetPU3AS817v128mx4_unaligned7v128mx4RS1_RDv32_iRi
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $eh0, $el0, $fh0, $fl0, $gh0, $gl0, $p0, $p1, $p2, $p3, $wh0, $wl0

    ; CHECK-LABEL: name: _Z18test_fifo_st_resetPU3AS817v128mx4_unaligned7v128mx4RS1_RDv32_iRi
    ; CHECK: liveins: $eh0, $el0, $fh0, $fl0, $gh0, $gl0, $p0, $p1, $p2, $p3, $wh0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mpfs = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fl0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:el = COPY $fh0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gl0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $gh0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $el0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:er = COPY $eh0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ep = COPY $p2
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ep = COPY $p3
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr26_fifo_st = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY2]], %subreg.sub_few_bfp_w, [[COPY4]], %subreg.sub_few_bfp_f64, [[COPY6]], %subreg.sub_few_bfp_g32, [[COPY8]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[VST_PUSH_768_:%[0-9]+]]:mstfifo, [[VST_PUSH_768_1:%[0-9]+]]:ep_as_32bit_and_mpfs, [[VST_PUSH_768_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_768 [[DEF]], [[REG_SEQUENCE2]], [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfifo_of
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VST_PUSH_768_2]], [[COPY11]], 0 :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VST_PUSH_768_1]], [[COPY9]], 0 :: (store (p8), align 4)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:vec1024 = COPY [[VST_PUSH_768_]]
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:vec512 = COPY [[COPY12]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY13]], [[COPY10]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:vec512 = COPY [[COPY12]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY14]], [[COPY10]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<8 x s32>) = COPY $wh0
    %3:gprregbank(<2 x s32>) = COPY $fl0
    %4:gprregbank(<2 x s32>) = COPY $fh0
    %5:gprregbank(s32) = COPY $gl0
    %6:gprregbank(s32) = COPY $gh0
    %7:gprregbank(s32) = COPY $el0
    %8:gprregbank(s32) = COPY $eh0
    %9:ptrregbank(p0) = COPY $p1
    %10:ptrregbank(p0) = COPY $p2
    %11:ptrregbank(p0) = COPY $p3
    %15:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %16:gprregbank(s32) = G_CONSTANT i32 0
    %12:ptrregbank(p0), %13:fiforegbank(<32 x s32>), %14:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP768), %0(p0), %15(<32 x s32>), %16(s32), %1(<8 x s32>), %2(<8 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(s32), %6(s32), %7(s32), %8(s32)
    G_STORE %14(s32), %11(p0) :: (store (s32) )
    G_STORE %12(p0), %9(p0) :: (store (p8) )
    %17:vregbank(<32 x s32>) = COPY %13(<32 x s32>)
    G_STORE %17(<32 x s32>), %10(p0) :: (store (<32 x s32>) )
    PseudoRET implicit $lr

...
---
name:            _Z18test_fifo_ld_fillxRrP17v128mx4_unalignedR12fifo_state_tii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0, $r1

    ; CHECK-LABEL: name: _Z18test_fifo_ld_fillxRrP17v128mx4_unalignedR12fifo_state_tii
    ; CHECK: liveins: $p0, $p1, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mlockid_reg = COPY $r1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LSHL:%[0-9]+]]:mlockid_reg = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[OR:%[0-9]+]]:mr30_fifo_step_e1 = OR [[LSHL]], [[COPY3]]
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo2:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 192 :: (dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:fifo512 = COPY [[VLD_x_idx_imm_pseudo2]]
    ; CHECK-NEXT: $lfe = COPY [[COPY5]]
    ; CHECK-NEXT: [[VLDB_FILLX:%[0-9]+]]:ep_as_32bit_and_eps, [[VLDB_FILLX1:%[0-9]+]]:eldfiforeg, [[VLDB_FILLX2:%[0-9]+]]:mrf2a = VLDB_FILLX [[OR]], [[OR]], [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY4]], [[LDA_dms_lda_scalar_ld_idx]], implicit-def $lfe, implicit $lfe
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mfifoextra = COPY $lfe
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:vec512 = COPY [[COPY6]]
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY7]], [[COPY1]], 192 :: (store (<16 x s32>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec1024 = COPY [[VLDB_FILLX1]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec512 = COPY [[COPY8]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY9]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec512 = COPY [[COPY8]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY10]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLDB_FILLX2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLDB_FILLX]], [[COPY]], 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %8:gprregbank(s32) = G_CONSTANT i32 6
    %4:modregbank(s20) = G_CONSTANT i20 128
    %6:modregbank(s20) = G_CONSTANT i20 192
    %9:gprregbank(s32) = G_SHL %2, %8(s32)
    %10:gprregbank(s32) = G_OR %9, %3
    %11:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p0) )
    %12:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %13:gprregbank(s32) = G_AIE_OFFSET_LOAD %1(p0), %4(s20) :: (dereferenceable load (s32) )
    %14:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1(p0), %6(s20) :: (dereferenceable load (<16 x s32>) )
    %19:fiforegbank(<32 x s32>) = COPY %12(<32 x s32>)
    %20:fiforegbank(<16 x s32>) = COPY %14(<16 x s32>)
    %15:ptrregbank(p0), %16:fiforegbank(<32 x s32>), %17:gprregbank(s32), %18:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fillx), %11(p0), %19(<32 x s32>), %13(s32), %20(<16 x s32>), %10(s32)
    %21:vregbank(<16 x s32>) = COPY %18(<16 x s32>)
    G_AIE_OFFSET_STORE %21(<16 x s32>), %1(p0), %6(s20) :: (store (<16 x s32>) )
    %22:vregbank(<32 x s32>) = COPY %16(<32 x s32>)
    G_STORE %22(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %17(s32), %1(p0), %4(s20) :: (store (s32) )
    G_STORE %15(p0), %0(p0) :: (store (p0) )
    PseudoRET implicit $lr

...
---
name:            _Z24test_fifo_ld_pop_3d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_tiiRiiiS6_i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4

    ; CHECK-LABEL: name: _Z24test_fifo_ld_pop_3d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_tiiRiiiS6_i
    ; CHECK: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $r3
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ep = COPY $p3
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:er = COPY $r4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:em = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:edn = COPY [[COPY3]]
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm1:%[0-9]+]]:edc_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY4]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:edj = COPY [[COPY5]]
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:edn = COPY [[COPY6]]
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm2:%[0-9]+]]:edc_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY7]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:edj = COPY [[COPY8]]
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:eds = REG_SEQUENCE [[COPY9]], %subreg.sub_mod, [[COPY10]], %subreg.sub_dim_size, [[COPY11]], %subreg.sub_dim_stride, [[LDA_dms_lda_scalar_ld_idx_imm1]], %subreg.sub_dim_count, [[COPY12]], %subreg.sub_hi_dim_then_sub_dim_size, [[COPY13]], %subreg.sub_hi_dim_then_sub_dim_stride, [[LDA_dms_lda_scalar_ld_idx_imm2]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_768_3D_pseudo:%[0-9]+]]:mfexa, [[VLD_POP_768_3D_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_768_3D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_768_3D_pseudo3:%[0-9]+]]:mrf2a, [[VLD_POP_768_3D_pseudo4:%[0-9]+]]:edc_as_32bit_and_edcl, [[VLD_POP_768_3D_pseudo5:%[0-9]+]]:edc_as_32bit_and_edch = VLD_POP_768_3D_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY14]], [[LDA_dms_lda_scalar_ld_idx]], [[REG_SEQUENCE1]]
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_3D_pseudo]].sub_bfp384_lo
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:vec256 = COPY [[COPY15]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mfs = COPY [[COPY15]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mgs = COPY [[COPY15]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mes = COPY [[COPY15]].sub_few_bfp_e32
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_3D_pseudo]].sub_bfp384_hi
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:vec256 = COPY [[COPY20]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mfs = COPY [[COPY20]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mgs = COPY [[COPY20]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mes = COPY [[COPY20]].sub_few_bfp_e32
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_768_3D_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:vec1024 = COPY [[VLD_POP_768_3D_pseudo2]]
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:vec512 = COPY [[COPY25]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY26]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:vec512 = COPY [[COPY25]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY27]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_768_3D_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_768_3D_pseudo4]], [[COPY4]], 0 :: (store (s20), align 4)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_768_3D_pseudo5]], [[COPY7]], 0 :: (store (s20), align 4)
    ; CHECK-NEXT: $wl0 = COPY [[COPY16]]
    ; CHECK-NEXT: $wh0 = COPY [[COPY21]]
    ; CHECK-NEXT: $fl0 = COPY [[COPY17]]
    ; CHECK-NEXT: $fh0 = COPY [[COPY22]]
    ; CHECK-NEXT: $gl0 = COPY [[COPY18]]
    ; CHECK-NEXT: $gh0 = COPY [[COPY23]]
    ; CHECK-NEXT: $el0 = COPY [[COPY19]]
    ; CHECK-NEXT: $eh0 = COPY [[COPY24]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0
    %8:ptrregbank(p0) = COPY $p0
    %9:ptrregbank(p0) = COPY $p1
    %10:gprregbank(s32) = COPY $r0
    %11:gprregbank(s32) = COPY $r1
    %12:ptrregbank(p0) = COPY $p2
    %13:gprregbank(s32) = COPY $r2
    %14:gprregbank(s32) = COPY $r3
    %15:ptrregbank(p0) = COPY $p3
    %16:gprregbank(s32) = COPY $r4
    %17:modregbank(s20) = G_CONSTANT i20 128
    %19:ptrregbank(p0) = G_LOAD %8(p0) :: (dereferenceable load (p6) )
    %20:vregbank(<32 x s32>) = G_LOAD %9(p0) :: (dereferenceable load (<32 x s32>) )
    %21:gprregbank(s32) = G_AIE_OFFSET_LOAD %9(p0), %17(s20) :: (dereferenceable load (s32) )
    %22:modregbank(s20) = G_TRUNC %10(s32)
    %23:modregbank(s20) = G_TRUNC %11(s32)
    %49:modregbank(s20) = G_LOAD %12(p0) :: (dereferenceable load (s20) )
    %26:modregbank(s20) = G_TRUNC %13(s32)
    %27:modregbank(s20) = G_TRUNC %14(s32)
    %50:modregbank(s20) = G_LOAD %15(p0) :: (dereferenceable load (s20) )
    %30:modregbank(s20) = G_TRUNC %16(s32)
    %51:fiforegbank(<32 x s32>) = COPY %20(<32 x s32>)
    %31:ptrregbank(p0), %32:fiforegbank(<32 x s32>), %33:gprregbank(s32), %34:modregbank(s20), %35:modregbank(s20), %36:vregbank(<8 x s32>), %37:vregbank(<8 x s32>), %38:gprregbank(<2 x s32>), %39:gprregbank(<2 x s32>), %40:gprregbank(s32), %41:gprregbank(s32), %42:gprregbank(s32), %43:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP768), %19(p0), %51(<32 x s32>), %21(s32), %22(s20), %23(s20), %49(s20), %26(s20), %27(s20), %50(s20), %30(s20)
    G_STORE %31(p0), %8(p0) :: (store (p6) )
    %52:vregbank(<32 x s32>) = COPY %32(<32 x s32>)
    G_STORE %52(<32 x s32>), %9(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %33(s32), %9(p0), %17(s20) :: (store (s32) )
    G_STORE %34(s20), %12(p0) :: (store (s20) )
    G_STORE %35(s20), %15(p0) :: (store (s20) )
    $wl0 = COPY %36(<8 x s32>)
    $wh0 = COPY %37(<8 x s32>)
    $fl0 = COPY %38(<2 x s32>)
    $fh0 = COPY %39(<2 x s32>)
    $gl0 = COPY %40(s32)
    $gh0 = COPY %41(s32)
    $el0 = COPY %42(s32)
    $eh0 = COPY %43(s32)
    PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0

...
---
name:            _Z24test_fifo_ld_pop_2d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_tiiRii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $r1, $r2

    ; CHECK-LABEL: name: _Z24test_fifo_ld_pop_2d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_tiiRii
    ; CHECK: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:em = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:edn = COPY [[COPY3]]
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm1:%[0-9]+]]:edc_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY4]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:edj = COPY [[COPY5]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:ed = REG_SEQUENCE [[COPY6]], %subreg.sub_mod, [[COPY7]], %subreg.sub_dim_size, [[COPY8]], %subreg.sub_dim_stride, [[LDA_dms_lda_scalar_ld_idx_imm1]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_768_2D_pseudo:%[0-9]+]]:mfexa, [[VLD_POP_768_2D_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_768_2D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_768_2D_pseudo3:%[0-9]+]]:mrf2a, [[VLD_POP_768_2D_pseudo4:%[0-9]+]]:edc_as_32bit = VLD_POP_768_2D_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY9]], [[LDA_dms_lda_scalar_ld_idx]], [[REG_SEQUENCE1]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_2D_pseudo]].sub_bfp384_lo
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY [[COPY10]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mfs = COPY [[COPY10]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mgs = COPY [[COPY10]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mes = COPY [[COPY10]].sub_few_bfp_e32
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_2D_pseudo]].sub_bfp384_hi
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:vec256 = COPY [[COPY15]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mfs = COPY [[COPY15]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mgs = COPY [[COPY15]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mes = COPY [[COPY15]].sub_few_bfp_e32
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_768_2D_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:vec1024 = COPY [[VLD_POP_768_2D_pseudo2]]
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:vec512 = COPY [[COPY20]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY21]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:vec512 = COPY [[COPY20]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY22]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_768_2D_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_768_2D_pseudo4]], [[COPY4]], 0 :: (store (s20), align 4)
    ; CHECK-NEXT: $wl0 = COPY [[COPY11]]
    ; CHECK-NEXT: $wh0 = COPY [[COPY16]]
    ; CHECK-NEXT: $fl0 = COPY [[COPY12]]
    ; CHECK-NEXT: $fh0 = COPY [[COPY17]]
    ; CHECK-NEXT: $gl0 = COPY [[COPY13]]
    ; CHECK-NEXT: $gh0 = COPY [[COPY18]]
    ; CHECK-NEXT: $el0 = COPY [[COPY14]]
    ; CHECK-NEXT: $eh0 = COPY [[COPY19]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0
    %8:ptrregbank(p0) = COPY $p0
    %9:ptrregbank(p0) = COPY $p1
    %10:gprregbank(s32) = COPY $r0
    %11:gprregbank(s32) = COPY $r1
    %12:ptrregbank(p0) = COPY $p2
    %13:gprregbank(s32) = COPY $r2
    %14:modregbank(s20) = G_CONSTANT i20 128
    %16:ptrregbank(p0) = G_LOAD %8(p0) :: (dereferenceable load (p6) )
    %17:vregbank(<32 x s32>) = G_LOAD %9(p0) :: (dereferenceable load (<32 x s32>) )
    %18:gprregbank(s32) = G_AIE_OFFSET_LOAD %9(p0), %14(s20) :: (dereferenceable load (s32) )
    %19:modregbank(s20) = G_TRUNC %10(s32)
    %20:modregbank(s20) = G_TRUNC %11(s32)
    %40:modregbank(s20) = G_LOAD %12(p0) :: (dereferenceable load (s20) )
    %23:modregbank(s20) = G_TRUNC %13(s32)
    %41:fiforegbank(<32 x s32>) = COPY %17(<32 x s32>)
    %24:ptrregbank(p0), %25:fiforegbank(<32 x s32>), %26:gprregbank(s32), %27:modregbank(s20), %28:vregbank(<8 x s32>), %29:vregbank(<8 x s32>), %30:gprregbank(<2 x s32>), %31:gprregbank(<2 x s32>), %32:gprregbank(s32), %33:gprregbank(s32), %34:gprregbank(s32), %35:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP768), %16(p0), %41(<32 x s32>), %18(s32), %19(s20), %20(s20), %40(s20), %23(s20)
    G_STORE %24(p0), %8(p0) :: (store (p6) )
    %42:vregbank(<32 x s32>) = COPY %25(<32 x s32>)
    G_STORE %42(<32 x s32>), %9(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %26(s32), %9(p0), %14(s20) :: (store (s32) )
    G_STORE %27(s20), %12(p0) :: (store (s20) )
    $wl0 = COPY %28(<8 x s32>)
    $wh0 = COPY %29(<8 x s32>)
    $fl0 = COPY %30(<2 x s32>)
    $fh0 = COPY %31(<2 x s32>)
    $gl0 = COPY %32(s32)
    $gh0 = COPY %33(s32)
    $el0 = COPY %34(s32)
    $eh0 = COPY %35(s32)
    PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0

...
---
name:            _Z24test_fifo_ld_pop_1d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_ti
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0

    ; CHECK-LABEL: name: _Z24test_fifo_ld_pop_1d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_ti
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_768_fifo_1d_pop_pseudo:%[0-9]+]]:mfexa, [[VLD_POP_768_fifo_1d_pop_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_768_fifo_1d_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_768_fifo_1d_pop_pseudo3:%[0-9]+]]:mrf2a = VLD_POP_768_fifo_1d_pop_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY4]], [[LDA_dms_lda_scalar_ld_idx]], [[COPY3]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_fifo_1d_pop_pseudo]].sub_bfp384_lo
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mfs = COPY [[COPY5]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mgs = COPY [[COPY5]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mes = COPY [[COPY5]].sub_few_bfp_e32
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mfewm = COPY [[VLD_POP_768_fifo_1d_pop_pseudo]].sub_bfp384_hi
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY [[COPY10]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mfs = COPY [[COPY10]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mgs = COPY [[COPY10]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mes = COPY [[COPY10]].sub_few_bfp_e32
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_768_fifo_1d_pop_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:vec1024 = COPY [[VLD_POP_768_fifo_1d_pop_pseudo2]]
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:vec512 = COPY [[COPY15]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY16]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:vec512 = COPY [[COPY15]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY17]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_768_fifo_1d_pop_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: $wl0 = COPY [[COPY6]]
    ; CHECK-NEXT: $wh0 = COPY [[COPY11]]
    ; CHECK-NEXT: $fl0 = COPY [[COPY7]]
    ; CHECK-NEXT: $fh0 = COPY [[COPY12]]
    ; CHECK-NEXT: $gl0 = COPY [[COPY8]]
    ; CHECK-NEXT: $gh0 = COPY [[COPY13]]
    ; CHECK-NEXT: $el0 = COPY [[COPY9]]
    ; CHECK-NEXT: $eh0 = COPY [[COPY14]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0
    %8:ptrregbank(p0) = COPY $p0
    %9:ptrregbank(p0) = COPY $p1
    %10:gprregbank(s32) = COPY $r0
    %11:modregbank(s20) = G_CONSTANT i20 128
    %13:ptrregbank(p0) = G_LOAD %8(p0) :: (dereferenceable load (p6) )
    %14:vregbank(<32 x s32>) = G_LOAD %9(p0) :: (dereferenceable load (<32 x s32>) )
    %15:gprregbank(s32) = G_AIE_OFFSET_LOAD %9(p0), %11(s20) :: (dereferenceable load (s32) )
    %16:modregbank(s20) = G_TRUNC %10(s32)
    %31:fiforegbank(<32 x s32>) = COPY %14(<32 x s32>)
    %17:ptrregbank(p0), %18:fiforegbank(<32 x s32>), %19:gprregbank(s32), %20:vregbank(<8 x s32>), %21:vregbank(<8 x s32>), %22:gprregbank(<2 x s32>), %23:gprregbank(<2 x s32>), %24:gprregbank(s32), %25:gprregbank(s32), %26:gprregbank(s32), %27:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP768), %13(p0), %31(<32 x s32>), %15(s32), %16(s20)
    G_STORE %17(p0), %8(p0) :: (store (p6) )
    %32:vregbank(<32 x s32>) = COPY %18(<32 x s32>)
    G_STORE %32(<32 x s32>), %9(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %19(s32), %9(p0), %11(s20) :: (store (s32) )
    $wl0 = COPY %20(<8 x s32>)
    $wh0 = COPY %21(<8 x s32>)
    $fl0 = COPY %22(<2 x s32>)
    $fh0 = COPY %23(<2 x s32>)
    $gl0 = COPY %24(s32)
    $gh0 = COPY %25(s32)
    $el0 = COPY %26(s32)
    $eh0 = COPY %27(s32)
    PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0

...
---
name:            _Z17test_fifo_ld_fillRrPU3AS617v128mx4_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z17test_fifo_ld_fillRrPU3AS617v128mx4_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:mrf2a = VLD_FILL_512_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[LDA_dms_lda_scalar_ld_idx]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY [[VLD_FILL_512_pseudo1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY4]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY5]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_FILL_512_pseudo2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_FILL_512_pseudo]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:modregbank(s20) = G_CONSTANT i20 128
    %4:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p6) )
    %5:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %6:gprregbank(s32) = G_AIE_OFFSET_LOAD %1(p0), %2(s20) :: (dereferenceable load (s32) )
    %10:fiforegbank(<32 x s32>) = COPY %5(<32 x s32>)
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %4(p0), %10(<32 x s32>), %6(s32)
    %11:vregbank(<32 x s32>) = COPY %8(<32 x s32>)
    G_STORE %11(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %9(s32), %1(p0), %2(s20) :: (store (s32) )
    G_STORE %7(p0), %0(p0) :: (store (p6) )
    PseudoRET implicit $lr

...
---
name:            _Z18test_fifo_ld_resetRrPU3AS617v128mx4_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z18test_fifo_ld_resetRrPU3AS617v128mx4_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrf2a = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[MOV_RLC_imm11_pseudo]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:mrf2a = VLD_FILL_512_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY [[VLD_FILL_512_pseudo1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY4]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY5]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_FILL_512_pseudo2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_FILL_512_pseudo]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:modregbank(s20) = G_CONSTANT i20 128
    G_AIE_OFFSET_STORE %4(s32), %1(p0), %2(s20) :: (store (s32) )
    %5:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p6) )
    %6:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %10:fiforegbank(<32 x s32>) = COPY %6(<32 x s32>)
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %5(p0), %10(<32 x s32>), %4(s32)
    %11:vregbank(<32 x s32>) = COPY %8(<32 x s32>)
    G_STORE %11(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %9(s32), %1(p0), %2(s20) :: (store (s32) )
    G_STORE %7(p0), %0(p0) :: (store (p6) )
    PseudoRET implicit $lr

...
---
name:            _Z17test_fifo_ld_fillRPU4AS1417v256mx6_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z17test_fifo_ld_fillRPU4AS1417v256mx6_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p14), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:mrf2a = VLD_FILL_512_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[LDA_dms_lda_scalar_ld_idx]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY [[VLD_FILL_512_pseudo1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY4]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY5]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_FILL_512_pseudo2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_FILL_512_pseudo]], [[COPY]], 0 :: (store (p14), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:modregbank(s20) = G_CONSTANT i20 128
    %4:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p14) )
    %5:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %6:gprregbank(s32) = G_AIE_OFFSET_LOAD %1(p0), %2(s20) :: (dereferenceable load (s32) )
    %10:fiforegbank(<32 x s32>) = COPY %5(<32 x s32>)
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %4(p0), %10(<32 x s32>), %6(s32)
    %11:vregbank(<32 x s32>) = COPY %8(<32 x s32>)
    G_STORE %11(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %9(s32), %1(p0), %2(s20) :: (store (s32) )
    G_STORE %7(p0), %0(p0) :: (store (p14) )
    PseudoRET implicit $lr

...
---
name:            _Z18test_fifo_ld_resetRPU4AS1417v256mx6_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z18test_fifo_ld_resetRPU4AS1417v256mx6_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrf2a = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[MOV_RLC_imm11_pseudo]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p14), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:mrf2a = VLD_FILL_512_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY [[VLD_FILL_512_pseudo1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY4]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY5]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_FILL_512_pseudo2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_FILL_512_pseudo]], [[COPY]], 0 :: (store (p14), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:modregbank(s20) = G_CONSTANT i20 128
    G_AIE_OFFSET_STORE %4(s32), %1(p0), %2(s20) :: (store (s32) )
    %5:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p14) )
    %6:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %10:fiforegbank(<32 x s32>) = COPY %6(<32 x s32>)
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %5(p0), %10(<32 x s32>), %4(s32)
    %11:vregbank(<32 x s32>) = COPY %8(<32 x s32>)
    G_STORE %11(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %9(s32), %1(p0), %2(s20) :: (store (s32) )
    G_STORE %7(p0), %0(p0) :: (store (p14) )
    PseudoRET implicit $lr

...
---
name:            _Z18test_fifo_ld_fillxRP16v64mx9_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z18test_fifo_ld_fillxRP16v64mx9_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mr30_fifo_step_e1 = MOVXM_lng_cg 2015
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p0), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo2:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 192 :: (dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:fifo512 = COPY [[VLD_x_idx_imm_pseudo2]]
    ; CHECK-NEXT: $lfe = COPY [[COPY3]]
    ; CHECK-NEXT: [[VLDB_FILLX:%[0-9]+]]:ep_as_32bit_and_eps, [[VLDB_FILLX1:%[0-9]+]]:eldfiforeg, [[VLDB_FILLX2:%[0-9]+]]:mrf2a = VLDB_FILLX [[MOVXM_lng_cg]], [[MOVXM_lng_cg]], [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[LDA_dms_lda_scalar_ld_idx]], implicit-def $lfe, implicit $lfe
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mfifoextra = COPY $lfe
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY4]]
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY5]], [[COPY1]], 192 :: (store (<16 x s32>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec1024 = COPY [[VLDB_FILLX1]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:vec512 = COPY [[COPY6]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY7]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec512 = COPY [[COPY6]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY8]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLDB_FILLX2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLDB_FILLX]], [[COPY]], 0 :: (store (p0), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %14:gprregbank(s32) = G_CONSTANT i32 2015
    %2:modregbank(s20) = G_CONSTANT i20 128
    %4:modregbank(s20) = G_CONSTANT i20 192
    %6:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p0) )
    %7:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %8:gprregbank(s32) = G_AIE_OFFSET_LOAD %1(p0), %2(s20) :: (dereferenceable load (s32) )
    %9:vregbank(<16 x s32>) = G_AIE_OFFSET_LOAD %1(p0), %4(s20) :: (dereferenceable load (<16 x s32>) )
    %15:fiforegbank(<32 x s32>) = COPY %7(<32 x s32>)
    %16:fiforegbank(<16 x s32>) = COPY %9(<16 x s32>)
    %10:ptrregbank(p0), %11:fiforegbank(<32 x s32>), %12:gprregbank(s32), %13:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fillx), %6(p0), %15(<32 x s32>), %8(s32), %16(<16 x s32>), %14(s32)
    %17:vregbank(<16 x s32>) = COPY %13(<16 x s32>)
    G_AIE_OFFSET_STORE %17(<16 x s32>), %1(p0), %4(s20) :: (store (<16 x s32>) )
    %18:vregbank(<32 x s32>) = COPY %11(<32 x s32>)
    G_STORE %18(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %12(s32), %1(p0), %2(s20) :: (store (s32) )
    G_STORE %10(p0), %0(p0) :: (store (p0) )
    PseudoRET implicit $lr

...
---
name:            _Z24test_fifo_ld_pop_3d_byteRPU3AS616v64mx9_unalignedR12fifo_state_tiiRiiiS5_i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4

    ; CHECK-LABEL: name: _Z24test_fifo_ld_pop_3d_byteRPU3AS616v64mx9_unalignedR12fifo_state_tiiRiiiS5_i
    ; CHECK: liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $r3
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ep = COPY $p3
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:er = COPY $r4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:em = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:edn = COPY [[COPY3]]
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm1:%[0-9]+]]:edc_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY4]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:edj = COPY [[COPY5]]
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:edn = COPY [[COPY6]]
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm2:%[0-9]+]]:edc_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY7]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:edj = COPY [[COPY8]]
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:eds = REG_SEQUENCE [[COPY9]], %subreg.sub_mod, [[COPY10]], %subreg.sub_dim_size, [[COPY11]], %subreg.sub_dim_stride, [[LDA_dms_lda_scalar_ld_idx_imm1]], %subreg.sub_dim_count, [[COPY12]], %subreg.sub_hi_dim_then_sub_dim_size, [[COPY13]], %subreg.sub_hi_dim_then_sub_dim_stride, [[LDA_dms_lda_scalar_ld_idx_imm2]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_640_3D_pseudo:%[0-9]+]]:mexa, [[VLD_POP_640_3D_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_640_3D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_640_3D_pseudo3:%[0-9]+]]:mrf2a, [[VLD_POP_640_3D_pseudo4:%[0-9]+]]:edc_as_32bit_and_edcl, [[VLD_POP_640_3D_pseudo5:%[0-9]+]]:edc_as_32bit_and_edch = VLD_POP_640_3D_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY14]], [[LDA_dms_lda_scalar_ld_idx]], [[REG_SEQUENCE1]]
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mewlv_bis = COPY [[VLD_POP_640_3D_pseudo]].sub_bfp320_lo
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:vec256 = COPY [[COPY15]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mgs = COPY [[COPY15]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mes = COPY [[COPY15]].sub_bfp_e32
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mewhv = COPY [[VLD_POP_640_3D_pseudo]].sub_bfp320_hi
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:vec256 = COPY [[COPY19]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:mgs = COPY [[COPY19]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mes = COPY [[COPY19]].sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY16]], %subreg.sub_256_lo, [[COPY20]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mggs = REG_SEQUENCE [[COPY17]], %subreg.sub_lo_exp, [[COPY21]], %subreg.sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mees = REG_SEQUENCE [[COPY18]], %subreg.sub_lo_exp, [[COPY22]], %subreg.sub_hi_exp
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_640_3D_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:vec1024 = COPY [[VLD_POP_640_3D_pseudo2]]
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:vec512 = COPY [[COPY23]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY24]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:vec512 = COPY [[COPY23]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY25]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_640_3D_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_640_3D_pseudo4]], [[COPY4]], 0 :: (store (s20), align 4)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_640_3D_pseudo5]], [[COPY7]], 0 :: (store (s20), align 4)
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE2]]
    ; CHECK-NEXT: $g0 = COPY [[REG_SEQUENCE3]]
    ; CHECK-NEXT: $e0 = COPY [[REG_SEQUENCE4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
    %3:ptrregbank(p0) = COPY $p0
    %4:ptrregbank(p0) = COPY $p1
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %7:ptrregbank(p0) = COPY $p2
    %8:gprregbank(s32) = COPY $r2
    %9:gprregbank(s32) = COPY $r3
    %10:ptrregbank(p0) = COPY $p3
    %11:gprregbank(s32) = COPY $r4
    %12:modregbank(s20) = G_CONSTANT i20 128
    %14:ptrregbank(p0) = G_LOAD %3(p0) :: (dereferenceable load (p6) )
    %15:vregbank(<32 x s32>) = G_LOAD %4(p0) :: (dereferenceable load (<32 x s32>) )
    %16:gprregbank(s32) = G_AIE_OFFSET_LOAD %4(p0), %12(s20) :: (dereferenceable load (s32) )
    %17:modregbank(s20) = G_TRUNC %5(s32)
    %18:modregbank(s20) = G_TRUNC %6(s32)
    %38:modregbank(s20) = G_LOAD %7(p0) :: (dereferenceable load (s20) )
    %21:modregbank(s20) = G_TRUNC %8(s32)
    %22:modregbank(s20) = G_TRUNC %9(s32)
    %39:modregbank(s20) = G_LOAD %10(p0) :: (dereferenceable load (s20) )
    %25:modregbank(s20) = G_TRUNC %11(s32)
    %40:fiforegbank(<32 x s32>) = COPY %15(<32 x s32>)
    %26:ptrregbank(p0), %27:fiforegbank(<32 x s32>), %28:gprregbank(s32), %29:modregbank(s20), %30:modregbank(s20), %31:vregbank(<16 x s32>), %32:gprregbank(<2 x s32>), %33:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP640), %14(p0), %40(<32 x s32>), %16(s32), %17(s20), %18(s20), %38(s20), %21(s20), %22(s20), %39(s20), %25(s20)
    G_STORE %26(p0), %3(p0) :: (store (p6) )
    %41:vregbank(<32 x s32>) = COPY %27(<32 x s32>)
    G_STORE %41(<32 x s32>), %4(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %28(s32), %4(p0), %12(s20) :: (store (s32) )
    G_STORE %29(s20), %7(p0) :: (store (s20) )
    G_STORE %30(s20), %10(p0) :: (store (s20) )
    $x0 = COPY %31(<16 x s32>)
    $g0 = COPY %32(<2 x s32>)
    $e0 = COPY %33(<2 x s32>)
    PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0

...
---
name:            _Z24test_fifo_ld_pop_2d_byteRPU3AS616v64mx9_unalignedR12fifo_state_tiiRii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $p2, $r0, $r1, $r2

    ; CHECK-LABEL: name: _Z24test_fifo_ld_pop_2d_byteRPU3AS616v64mx9_unalignedR12fifo_state_tiiRii
    ; CHECK: liveins: $p0, $p1, $p2, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p2
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:em = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:edn = COPY [[COPY3]]
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm1:%[0-9]+]]:edc_as_32bit = LDA_dms_lda_scalar_ld_idx_imm [[COPY4]], 0 :: (dereferenceable load (s20), align 4)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:edj = COPY [[COPY5]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:ed = REG_SEQUENCE [[COPY6]], %subreg.sub_mod, [[COPY7]], %subreg.sub_dim_size, [[COPY8]], %subreg.sub_dim_stride, [[LDA_dms_lda_scalar_ld_idx_imm1]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_640_2D_pseudo:%[0-9]+]]:mexa, [[VLD_POP_640_2D_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_640_2D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_640_2D_pseudo3:%[0-9]+]]:mrf2a, [[VLD_POP_640_2D_pseudo4:%[0-9]+]]:edc_as_32bit = VLD_POP_640_2D_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY9]], [[LDA_dms_lda_scalar_ld_idx]], [[REG_SEQUENCE1]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mewlv_bis = COPY [[VLD_POP_640_2D_pseudo]].sub_bfp320_lo
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY [[COPY10]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mgs = COPY [[COPY10]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mes = COPY [[COPY10]].sub_bfp_e32
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mewhv = COPY [[VLD_POP_640_2D_pseudo]].sub_bfp320_hi
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:vec256 = COPY [[COPY14]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:mgs = COPY [[COPY14]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mes = COPY [[COPY14]].sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY11]], %subreg.sub_256_lo, [[COPY15]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mggs = REG_SEQUENCE [[COPY12]], %subreg.sub_lo_exp, [[COPY16]], %subreg.sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mees = REG_SEQUENCE [[COPY13]], %subreg.sub_lo_exp, [[COPY17]], %subreg.sub_hi_exp
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_640_2D_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:vec1024 = COPY [[VLD_POP_640_2D_pseudo2]]
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:vec512 = COPY [[COPY18]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY19]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:vec512 = COPY [[COPY18]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY20]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_640_2D_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_640_2D_pseudo4]], [[COPY4]], 0 :: (store (s20), align 4)
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE2]]
    ; CHECK-NEXT: $g0 = COPY [[REG_SEQUENCE3]]
    ; CHECK-NEXT: $e0 = COPY [[REG_SEQUENCE4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
    %3:ptrregbank(p0) = COPY $p0
    %4:ptrregbank(p0) = COPY $p1
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %7:ptrregbank(p0) = COPY $p2
    %8:gprregbank(s32) = COPY $r2
    %9:modregbank(s20) = G_CONSTANT i20 128
    %11:ptrregbank(p0) = G_LOAD %3(p0) :: (dereferenceable load (p6) )
    %12:vregbank(<32 x s32>) = G_LOAD %4(p0) :: (dereferenceable load (<32 x s32>) )
    %13:gprregbank(s32) = G_AIE_OFFSET_LOAD %4(p0), %9(s20) :: (dereferenceable load (s32) )
    %14:modregbank(s20) = G_TRUNC %5(s32)
    %15:modregbank(s20) = G_TRUNC %6(s32)
    %29:modregbank(s20) = G_LOAD %7(p0) :: (dereferenceable load (s20) )
    %18:modregbank(s20) = G_TRUNC %8(s32)
    %30:fiforegbank(<32 x s32>) = COPY %12(<32 x s32>)
    %19:ptrregbank(p0), %20:fiforegbank(<32 x s32>), %21:gprregbank(s32), %22:modregbank(s20), %23:vregbank(<16 x s32>), %24:gprregbank(<2 x s32>), %25:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP640), %11(p0), %30(<32 x s32>), %13(s32), %14(s20), %15(s20), %29(s20), %18(s20)
    G_STORE %19(p0), %3(p0) :: (store (p6) )
    %31:vregbank(<32 x s32>) = COPY %20(<32 x s32>)
    G_STORE %31(<32 x s32>), %4(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %21(s32), %4(p0), %9(s20) :: (store (s32) )
    G_STORE %22(s20), %7(p0) :: (store (s20) )
    $x0 = COPY %23(<16 x s32>)
    $g0 = COPY %24(<2 x s32>)
    $e0 = COPY %25(<2 x s32>)
    PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0

...
---
name:            _Z24test_fifo_ld_pop_1d_byteRPU3AS616v64mx9_unalignedR12fifo_state_ti
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $r0

    ; CHECK-LABEL: name: _Z24test_fifo_ld_pop_1d_byteRPU3AS616v64mx9_unalignedR12fifo_state_ti
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_640_fifo_1d_pop_pseudo:%[0-9]+]]:mexa, [[VLD_POP_640_fifo_1d_pop_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_640_fifo_1d_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_640_fifo_1d_pop_pseudo3:%[0-9]+]]:mrf2a = VLD_POP_640_fifo_1d_pop_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY4]], [[LDA_dms_lda_scalar_ld_idx]], [[COPY3]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mewlv_bis = COPY [[VLD_POP_640_fifo_1d_pop_pseudo]].sub_bfp320_lo
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mgs = COPY [[COPY5]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mes = COPY [[COPY5]].sub_bfp_e32
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mewhv = COPY [[VLD_POP_640_fifo_1d_pop_pseudo]].sub_bfp320_hi
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY [[COPY9]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mgs = COPY [[COPY9]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mes = COPY [[COPY9]].sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY6]], %subreg.sub_256_lo, [[COPY10]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mggs = REG_SEQUENCE [[COPY7]], %subreg.sub_lo_exp, [[COPY11]], %subreg.sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mees = REG_SEQUENCE [[COPY8]], %subreg.sub_lo_exp, [[COPY12]], %subreg.sub_hi_exp
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_640_fifo_1d_pop_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:vec1024 = COPY [[VLD_POP_640_fifo_1d_pop_pseudo2]]
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:vec512 = COPY [[COPY13]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY14]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:vec512 = COPY [[COPY13]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY15]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_640_fifo_1d_pop_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE1]]
    ; CHECK-NEXT: $g0 = COPY [[REG_SEQUENCE2]]
    ; CHECK-NEXT: $e0 = COPY [[REG_SEQUENCE3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
    %3:ptrregbank(p0) = COPY $p0
    %4:ptrregbank(p0) = COPY $p1
    %5:gprregbank(s32) = COPY $r0
    %6:modregbank(s20) = G_CONSTANT i20 128
    %8:ptrregbank(p0) = G_LOAD %3(p0) :: (dereferenceable load (p6) )
    %9:vregbank(<32 x s32>) = G_LOAD %4(p0) :: (dereferenceable load (<32 x s32>) )
    %10:gprregbank(s32) = G_AIE_OFFSET_LOAD %4(p0), %6(s20) :: (dereferenceable load (s32) )
    %11:modregbank(s20) = G_TRUNC %5(s32)
    %12:ptrregbank(p0), %13:fiforegbank(<32 x s32>), %14:gprregbank(s32), %15:vregbank(<16 x s32>), %16:gprregbank(<2 x s32>), %17:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP640), %8(p0), %9(<32 x s32>), %10(s32), %11(s20)
    G_STORE %12(p0), %3(p0) :: (store (p6) )
    %20:vregbank(<32 x s32>) = COPY %13(<32 x s32>)
    G_STORE %20(<32 x s32>), %4(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %14(s32), %4(p0), %6(s20) :: (store (s32) )
    $x0 = COPY %15(<16 x s32>)
    $g0 = COPY %16(<2 x s32>)
    $e0 = COPY %17(<2 x s32>)
    PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0

...
---
name:            _Z16test_fifo_ld_popRPU3AS616v64mx9_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z16test_fifo_ld_popRPU3AS616v64mx9_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_POP_640_normal_pop_pseudo:%[0-9]+]]:mexa, [[VLD_POP_640_normal_pop_pseudo1:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_POP_640_normal_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_640_normal_pop_pseudo3:%[0-9]+]]:mrf2a = VLD_POP_640_normal_pop_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[LDA_dms_lda_scalar_ld_idx]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mewlv_bis = COPY [[VLD_POP_640_normal_pop_pseudo]].sub_bfp320_lo
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mgs = COPY [[COPY3]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mes = COPY [[COPY3]].sub_bfp_e32
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mewhv = COPY [[VLD_POP_640_normal_pop_pseudo]].sub_bfp320_hi
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY [[COPY7]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mgs = COPY [[COPY7]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mes = COPY [[COPY7]].sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY4]], %subreg.sub_256_lo, [[COPY8]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mggs = REG_SEQUENCE [[COPY5]], %subreg.sub_lo_exp, [[COPY9]], %subreg.sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mees = REG_SEQUENCE [[COPY6]], %subreg.sub_lo_exp, [[COPY10]], %subreg.sub_hi_exp
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_POP_640_normal_pop_pseudo1]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec1024 = COPY [[VLD_POP_640_normal_pop_pseudo2]]
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:vec512 = COPY [[COPY11]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY12]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:vec512 = COPY [[COPY11]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY13]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_POP_640_normal_pop_pseudo3]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE1]]
    ; CHECK-NEXT: $g0 = COPY [[REG_SEQUENCE2]]
    ; CHECK-NEXT: $e0 = COPY [[REG_SEQUENCE3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
    %3:ptrregbank(p0) = COPY $p0
    %4:ptrregbank(p0) = COPY $p1
    %5:modregbank(s20) = G_CONSTANT i20 128
    %7:ptrregbank(p0) = G_LOAD %3(p0) :: (dereferenceable load (p6) )
    %8:vregbank(<32 x s32>) = G_LOAD %4(p0) :: (dereferenceable load (<32 x s32>) )
    %9:gprregbank(s32) = G_AIE_OFFSET_LOAD %4(p0), %5(s20) :: (dereferenceable load (s32) )
    %18:fiforegbank(<32 x s32>) = COPY %8(<32 x s32>)
    %10:ptrregbank(p0), %11:fiforegbank(<32 x s32>), %12:gprregbank(s32), %13:vregbank(<16 x s32>), %14:gprregbank(<2 x s32>), %15:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP640), %7(p0), %18(<32 x s32>), %9(s32)
    G_STORE %10(p0), %3(p0) :: (store (p6) )
    %19:vregbank(<32 x s32>) = COPY %11(<32 x s32>)
    G_STORE %19(<32 x s32>), %4(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %12(s32), %4(p0), %5(s20) :: (store (s32) )
    $x0 = COPY %13(<16 x s32>)
    $g0 = COPY %14(<2 x s32>)
    $e0 = COPY %15(<2 x s32>)
    PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0

...
---
name:            _Z17test_fifo_ld_fillRPU3AS616v64mx9_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z17test_fifo_ld_fillRPU3AS616v64mx9_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx:%[0-9]+]]:mrf2a = LDA_dms_lda_scalar_ld_idx [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (dereferenceable load (s32))
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:mrf2a = VLD_FILL_512_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[LDA_dms_lda_scalar_ld_idx]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY [[VLD_FILL_512_pseudo1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY4]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY5]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_FILL_512_pseudo2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_FILL_512_pseudo]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:modregbank(s20) = G_CONSTANT i20 128
    %4:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p6) )
    %5:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %6:gprregbank(s32) = G_AIE_OFFSET_LOAD %1(p0), %2(s20) :: (dereferenceable load (s32) )
    %10:fiforegbank(<32 x s32>) = COPY %5(<32 x s32>)
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %4(p0), %10(<32 x s32>), %6(s32)
    %11:vregbank(<32 x s32>) = COPY %8(<32 x s32>)
    G_STORE %11(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %9(s32), %1(p0), %2(s20) :: (store (s32) )
    G_STORE %7(p0), %0(p0) :: (store (p6) )
    PseudoRET implicit $lr

...
---
name:            _Z18test_fifo_ld_resetRPU3AS616v64mx9_unalignedR12fifo_state_t
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: _Z18test_fifo_ld_resetRPU3AS616v64mx9_unalignedR12fifo_state_t
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrf2a = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[MOV_RLC_imm11_pseudo]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: [[LDA_dms_lda_scalar_ld_idx_imm:%[0-9]+]]:ep_as_32bit_and_eps = LDA_dms_lda_scalar_ld_idx_imm [[COPY]], 0 :: (dereferenceable load (p6), align 4)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 64 :: (dereferenceable load (<16 x s32>), align 128)
    ; CHECK-NEXT: [[VLD_x_idx_imm_pseudo1:%[0-9]+]]:vec512 = VLD_x_idx_imm_pseudo [[COPY1]], 0 :: (dereferenceable load (<16 x s32>) from unknown-address + 64)
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[VLD_x_idx_imm_pseudo1]], %subreg.sub_512_lo, [[VLD_x_idx_imm_pseudo]], %subreg.sub_512_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:ep_as_32bit_and_eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:mrf2a = VLD_FILL_512_pseudo [[LDA_dms_lda_scalar_ld_idx_imm]], [[COPY2]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec1024 = COPY [[VLD_FILL_512_pseudo1]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_hi
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY4]], [[COPY1]], 64 :: (store (<16 x s32>), align 128)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY [[COPY3]].sub_512_lo
    ; CHECK-NEXT: VST_dmx_sts_x_st_idx_imm [[COPY5]], [[COPY1]], 0 :: (store (<16 x s32>) into unknown-address + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx [[VLD_FILL_512_pseudo2]], [[COPY1]], [[MOV_PD_imm11_pseudo]] :: (store (s32))
    ; CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[VLD_FILL_512_pseudo]], [[COPY]], 0 :: (store (p6), align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:modregbank(s20) = G_CONSTANT i20 128
    G_AIE_OFFSET_STORE %4(s32), %1(p0), %2(s20) :: (store (s32) )
    %5:ptrregbank(p0) = G_LOAD %0(p0) :: (dereferenceable load (p6) )
    %6:vregbank(<32 x s32>) = G_LOAD %1(p0) :: (dereferenceable load (<32 x s32>) )
    %10:fiforegbank(<32 x s32>) = COPY %6(<32 x s32>)
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %5(p0), %10(<32 x s32>), %4(s32)
    %11:vregbank(<32 x s32>) = COPY %8(<32 x s32>)
    G_STORE %11(<32 x s32>), %1(p0) :: (store (<32 x s32>) )
    G_AIE_OFFSET_STORE %9(s32), %1(p0), %2(s20) :: (store (s32) )
    G_STORE %7(p0), %0(p0) :: (store (p6) )
    PseudoRET implicit $lr

...
---
name:            _Z14test_to_v64mx4Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: _Z14test_to_v64mx4Dv64_u10__accfloat
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[VCONV_mx4_fp32_:%[0-9]+]]:mfewa = VCONV_mx4_fp32 [[COPY]], implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[VCONV_mx4_fp32_]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mfs = COPY [[VCONV_mx4_fp32_]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mgs = COPY [[VCONV_mx4_fp32_]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mes = COPY [[VCONV_mx4_fp32_]].sub_few_bfp_e32
    ; CHECK-NEXT: $wl0 = COPY [[COPY1]]
    ; CHECK-NEXT: $fl0 = COPY [[COPY2]]
    ; CHECK-NEXT: $gl0 = COPY [[COPY3]]
    ; CHECK-NEXT: $el0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $fl0, implicit $gl0, implicit $el0
    %4:accregbank(<64 x s32>) = COPY $dm0
    %5:vregbank(<8 x s32>), %6:gprregbank(<2 x s32>), %7:gprregbank(s32), %8:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx4), %4(<64 x s32>)
    $wl0 = COPY %5(<8 x s32>)
    $fl0 = COPY %6(<2 x s32>)
    $gl0 = COPY %7(s32)
    $el0 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $wl0, implicit $fl0, implicit $gl0, implicit $el0

...
---
name:            _Z14test_to_v64mx6Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: _Z14test_to_v64mx6Dv64_u10__accfloat
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[VCONV_mx6_fp32_:%[0-9]+]]:mfewa = VCONV_mx6_fp32 [[COPY]], implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[VCONV_mx6_fp32_]].sub_few_bfp_w
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mfs = COPY [[VCONV_mx6_fp32_]].sub_few_bfp_f64
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mgs = COPY [[VCONV_mx6_fp32_]].sub_few_bfp_g32
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mes = COPY [[VCONV_mx6_fp32_]].sub_few_bfp_e32
    ; CHECK-NEXT: $wl0 = COPY [[COPY1]]
    ; CHECK-NEXT: $fl0 = COPY [[COPY2]]
    ; CHECK-NEXT: $gl0 = COPY [[COPY3]]
    ; CHECK-NEXT: $el0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0, implicit $fl0, implicit $gl0, implicit $el0
    %4:accregbank(<64 x s32>) = COPY $dm0
    %5:vregbank(<8 x s32>), %6:gprregbank(<2 x s32>), %7:gprregbank(s32), %8:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx6), %4(<64 x s32>)
    $wl0 = COPY %5(<8 x s32>)
    $fl0 = COPY %6(<2 x s32>)
    $gl0 = COPY %7(s32)
    $el0 = COPY %8(s32)
    PseudoRET implicit $lr, implicit $wl0, implicit $fl0, implicit $gl0, implicit $el0

...
---
name:            _Z14test_to_v64mx9Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm0

    ; CHECK-LABEL: name: _Z14test_to_v64mx9Dv64_u10__accfloat
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[VCONV_mx9_fp32_:%[0-9]+]]:mexa = VCONV_mx9_fp32 [[COPY]], implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mewlv_bis = COPY [[VCONV_mx9_fp32_]].sub_bfp320_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY1]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mgs = COPY [[COPY1]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mes = COPY [[COPY1]].sub_bfp_e32
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mewhv = COPY [[VCONV_mx9_fp32_]].sub_bfp320_hi
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_bfp_v256
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mgs = COPY [[COPY5]].sub_bfp_g32
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mes = COPY [[COPY5]].sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY2]], %subreg.sub_256_lo, [[COPY6]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mggs = REG_SEQUENCE [[COPY3]], %subreg.sub_lo_exp, [[COPY7]], %subreg.sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mees = REG_SEQUENCE [[COPY4]], %subreg.sub_lo_exp, [[COPY8]], %subreg.sub_hi_exp
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $g0 = COPY [[REG_SEQUENCE1]]
    ; CHECK-NEXT: $e0 = COPY [[REG_SEQUENCE2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
    %3:accregbank(<64 x s32>) = COPY $dm0
    %4:vregbank(<16 x s32>), %5:gprregbank(<2 x s32>), %6:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx9), %3(<64 x s32>)
    $x0 = COPY %4(<16 x s32>)
    $g0 = COPY %5(<2 x s32>)
    $e0 = COPY %6(<2 x s32>)
    PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0

...
