# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name:            ACQ_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ;CHECK-LABEL: name:            ACQ_mLockId_reg
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:mlockid_reg = COPY $r1
    ;CHECK-NEXT: ACQ_mLockId_reg [[COPY_0]], [[COPY_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acquire), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            ACQ_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ;CHECK-LABEL: name:            ACQ_mLockId_imm
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: ACQ_mLockId_imm 1, [[COPY_0]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acquire), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            ACQ_COND_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $r2
    ;CHECK-LABEL: name:            ACQ_COND_mLockId_reg
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:mlockid_reg = COPY $r1
    ;CHECK-NEXT: [[COPY_2:%[0-9]+]]:mr23_lock = COPY $r2
    ;CHECK-NEXT: ACQ_COND_mLockId_reg [[COPY_0]], [[COPY_1]], [[COPY_2]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = COPY $r2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acquire.cond), %0:gprregbank(s32), %1:gprregbank(s32), %2:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            ACQ_COND_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ;CHECK-LABEL: name:            ACQ_COND_mLockId_imm
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:mr23_lock = COPY $r1
    ;CHECK-NEXT: ACQ_COND_mLockId_imm 2, [[COPY_0]], [[COPY_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acquire.cond), %2:gprregbank(s32), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ;CHECK-LABEL: name:            REL_mLockId_reg
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:mlockid_reg = COPY $r1
    ;CHECK-NEXT: REL_mLockId_reg [[COPY_0]], [[COPY_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.release), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ;CHECK-LABEL: name:            REL_mLockId_imm
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: REL_mLockId_imm 28, [[COPY_0]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 28
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.release), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_COND_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $r2
    ;CHECK-LABEL: name:            REL_COND_mLockId_reg
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:mlockid_reg = COPY $r1
    ;CHECK-NEXT: [[COPY_2:%[0-9]+]]:mr23_lock = COPY $r2
    ;CHECK-NEXT: REL_COND_mLockId_reg [[COPY_0]], [[COPY_1]], [[COPY_2]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = COPY $r2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.release.cond), %0:gprregbank(s32), %1:gprregbank(s32), %2:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_COND_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ;CHECK-LABEL: name:            REL_COND_mLockId_imm
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r0
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:mr23_lock = COPY $r1
    ;CHECK-NEXT: REL_COND_mLockId_imm 61, [[COPY_0]], [[COPY_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr

    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 61
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.release.cond), %2:gprregbank(s32), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...
