# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            _Z19test_to_v16bfloat16Dv16_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0


    ; CHECK-LABEL: name: _Z19test_to_v16bfloat16Dv16_u10__accfloat
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_:%[0-9]+]]:vec256 = VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16 [[COPY]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: $wl0 = COPY [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z15test_to_v32int8Dv32_u7__acc32ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1


    ; CHECK-LABEL: name: _Z15test_to_v32int8Dv32_u7__acc32ii
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign0_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z16test_to_v32int16Dv32_u7__acc32ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1


    ; CHECK-LABEL: name: _Z16test_to_v32int16Dv32_u7__acc32ii
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z16test_to_v16int16Dv16_u7__acc32ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $r1


    ; CHECK-LABEL: name: _Z16test_to_v16int16Dv16_u7__acc32ii
    ; CHECK: liveins: $bmll0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z16test_to_v16int16Dv16_u7__acc64ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1


    ; CHECK-LABEL: name: _Z16test_to_v16int16Dv16_u7__acc64ii
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign0_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z15test_to_v8int32Dv8_u7__acc64ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $r1


    ; CHECK-LABEL: name: _Z15test_to_v8int32Dv8_u7__acc64ii
    ; CHECK: liveins: $bmll0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v8.acc64.srs), %1(<8 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z16test_to_v16int32Dv16_u7__acc64ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1


    ; CHECK-LABEL: name: _Z16test_to_v16int32Dv16_u7__acc64ii
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z17test_to_v16uint32Dv16_u7__acc64ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $r1


    ; CHECK-LABEL: name: _Z17test_to_v16uint32Dv16_u7__acc64ii
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z16test_to_v32int16Dv32_u7__acc32i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0


    ; CHECK-LABEL: name: _Z16test_to_v32int16Dv32_u7__acc32i
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign1_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z17test_to_v32uint16Dv32_u7__acc32i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0


    ; CHECK-LABEL: name: _Z17test_to_v32uint16Dv32_u7__acc32i
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z16test_to_v16int16Dv16_u7__acc32i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0


    ; CHECK-LABEL: name: _Z16test_to_v16int16Dv16_u7__acc32i
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign1_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z17test_to_v16uint16Dv16_u7__acc32i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0


    ; CHECK-LABEL: name: _Z17test_to_v16uint16Dv16_u7__acc32i
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z16test_to_v16int16Dv16_u7__acc64i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0


    ; CHECK-LABEL: name: _Z16test_to_v16int16Dv16_u7__acc64i
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign1_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z17test_to_v16uint16Dv16_u7__acc64i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0


    ; CHECK-LABEL: name: _Z17test_to_v16uint16Dv16_u7__acc64i
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_w_srs_cm_srsSign0_:%[0-9]+]]:vec256 = VSRS_4x_mv_w_srs_cm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_4x_mv_w_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z16test_to_v16int32Dv16_u7__acc64i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0


    ; CHECK-LABEL: name: _Z16test_to_v16int32Dv16_u7__acc64i
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign1_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z17test_to_v16uint32Dv16_u7__acc64i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0


    ; CHECK-LABEL: name: _Z17test_to_v16uint32Dv16_u7__acc64i
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_x_srs_cm_srsSign0_:%[0-9]+]]:vec512 = VSRS_2x_mv_x_srs_cm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_2x_mv_x_srs_cm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<16 x s64>) = COPY $cml0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z15test_to_v8int32Dv8_u7__acc64i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0


    ; CHECK-LABEL: name: _Z15test_to_v8int32Dv8_u7__acc64i
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign1_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign1 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v8.acc64.srs), %1(<8 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z16test_to_v8uint32Dv8_u7__acc64i
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0


    ; CHECK-LABEL: name: _Z16test_to_v8uint32Dv8_u7__acc64i
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_2x_mv_w_srs_bm_srsSign0_:%[0-9]+]]:vec256 = VSRS_2x_mv_w_srs_bm_srsSign0 [[COPY]], [[COPY2]], implicit-def dead $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $wl0 = COPY [[VSRS_2x_mv_w_srs_bm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<8 x s64>) = COPY $bmll0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v8.acc64.srs), %1(<8 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z19test_to_v32bfloat16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0


    ; CHECK-LABEL: name: _Z19test_to_v32bfloat16Dv32_u10__accfloat
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_conv_mv_x_srs_bf16_:%[0-9]+]]:vec512 = VCONV_bf16_fp32_mv_conv_mv_x_srs_bf16 [[COPY]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: $x0 = COPY [[VCONV_bf16_fp32_mv_conv_mv_x_srs_bf16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %1(<32 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z18test_to_v16float16Dv16_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0


    ; CHECK-LABEL: name: _Z18test_to_v16float16Dv16_u10__accfloat
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mmvbmsrc = COPY $bmll0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[COPY]], %subreg.sub_512_acc_lo
    ; CHECK-NEXT: [[VCONV_fp16_fp32_mv_x_srs_fp16_:%[0-9]+]]:mxa = VCONV_fp16_fp32_mv_x_srs_fp16 [[REG_SEQUENCE]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mwla = COPY [[VCONV_fp16_fp32_mv_x_srs_fp16_]].sub_256_lo
    ; CHECK-NEXT: $wl0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %0:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16float16), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z18test_to_v32float16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0


    ; CHECK-LABEL: name: _Z18test_to_v32float16Dv32_u10__accfloat
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[VCONV_fp16_fp32_mv_x_srs_fp16_:%[0-9]+]]:vec512 = VCONV_fp16_fp32_mv_x_srs_fp16 [[COPY]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: $x0 = COPY [[VCONV_fp16_fp32_mv_x_srs_fp16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), %1(<32 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z17test_to_v32float8Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0


    ; CHECK-LABEL: name: _Z17test_to_v32float8Dv32_u10__accfloat
    ; CHECK: liveins: $cml0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:es = COPY [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[VCONV_fp8_fp32_:%[0-9]+]]:vec256 = VCONV_fp8_fp32 [[COPY]], [[COPY1]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crfp8conf, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %2:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float8), %1(<32 x s32>), %3(s32)
    PseudoRET implicit $lr

...
---
name:            _Z18test_to_v32bfloat8Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0


    ; CHECK-LABEL: name: _Z18test_to_v32bfloat8Dv32_u10__accfloat
    ; CHECK: liveins: $cml0, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:es = COPY [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[VCONV_bf8_fp32_:%[0-9]+]]:vec256 = VCONV_bf8_fp32 [[COPY]], [[COPY1]], implicit-def dead $srf2fflags, implicit $crbf8conf, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:accregbank(<32 x s32>) = COPY $cml0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %2:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bfloat8), %1(<32 x s32>), %3(s32)
    PseudoRET implicit $lr

...
---
name:            _Z16test_to_v32int16Dv32_u7__acc64ii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $r0, $r1


    ; CHECK-LABEL: name: _Z16test_to_v32int16Dv32_u7__acc64ii
    ; CHECK: liveins: $dm0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $srssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSRS_4x_mv_x_srs_dm_srsSign0_:%[0-9]+]]:vec512 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VSRS_4x_mv_x_srs_dm_srsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:accregbank(<32 x s64>) = COPY $dm0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc64.srs), %1(<32 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
