# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name:            VBCST_32_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: VBCST_32_bf
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[VBCST_32_:%[0-9]+]]:vec512 = VBCST_32 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBCST_32_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(<2 x s16>) = COPY $r0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbroadcast32.bf512), %1:gprregbank(<2 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VBCST_64_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0
    ; CHECK-LABEL: name: VBCST_64_bf
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[VBCST_64_:%[0-9]+]]:vec512 = VBCST_64 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBCST_64_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(<4 x s16>) = COPY $l0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbroadcast64.bf512), %1:gprregbank(<4 x s16>)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...
