# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            _Z16test_mul_8x8_8x8Dv64_hS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mul_8x8_8x8Dv64_hS_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMUL_vmul_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VMUL_vmul_vmul_cm_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.mul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_8x8_8x8Dv64_hS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z19test_negmul_8x8_8x8Dv64_hS_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VNEGMUL_vmul_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VNEGMUL_vmul_vmul_cm_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.negmul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_8x8_8x8Dv64_hS_Dv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mac_8x8_8x8Dv64_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMAC_vmac_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmac_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.mac.conf), %4(<32 x s16>), %5(<32 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_8x8_8x8Dv64_hS_Dv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_msc_8x8_8x8Dv64_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VMSC_vmac_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VMSC_vmac_vmul_cm_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmac_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.msc.conf), %4(<32 x s16>), %5(<32 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmac_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.addmac.conf), %5(<32 x s16>), %6(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmsc_8x8_8x8Dv64_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.addmsc.conf), %5(<32 x s16>), %6(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z18test_mul_elem_64_2Dv128_hS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z18test_mul_elem_64_2Dv128_hS_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VMUL_vmul_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMUL_vmul_vmul_cm_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %5:gprregbank(s32) = G_CONSTANT i32 32
    %3:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.mul.conf), %3(<64 x s16>), %4(<64 x s16>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_negmul_elem_64_2Dv128_hS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z21test_negmul_elem_64_2Dv128_hS_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VNEGMUL_vmul_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VNEGMUL_vmul_vmul_cm_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %5:gprregbank(s32) = G_CONSTANT i32 32
    %3:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.negmul.conf), %3(<64 x s16>), %4(<64 x s16>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z18test_mac_elem_64_2Dv128_hS_Dv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z18test_mac_elem_64_2Dv128_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VMAC_vmac_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmac_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 32
    %4:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.mac.conf), %4(<64 x s16>), %5(<64 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z18test_msc_elem_64_2Dv128_hS_Dv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z18test_msc_elem_64_2Dv128_hS_Dv64_u7__acc32
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VMSC_vmac_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_vmac_vmul_cm_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmac_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 32
    %4:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.msc.conf), %4(<64 x s16>), %5(<64 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_addmac_elem_64_2Dv128_hS_Dv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z21test_addmac_elem_64_2Dv128_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 32
    %5:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.addmac.conf), %5(<64 x s16>), %6(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_addmsc_elem_64_2Dv128_hS_Dv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z21test_addmsc_elem_64_2Dv128_hS_Dv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<128 x s8>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 32
    %5:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.addmsc.conf), %5(<64 x s16>), %6(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_mul_conv_8x8_8chDv128_hDv64_h
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z21test_mul_conv_8x8_8chDv128_hDv64_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 64
    ; CHECK-NEXT: [[VMUL_vmul_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VMUL_vmul_vmul_cm_core_Y_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %5:gprregbank(s32) = G_CONSTANT i32 64
    %3:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.mul.conf), %3(<64 x s16>), %4(<32 x s16>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z24test_negmul_conv_8x8_8chDv128_hDv64_h
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z24test_negmul_conv_8x8_8chDv128_hDv64_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 64
    ; CHECK-NEXT: [[VNEGMUL_vmul_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VNEGMUL_vmul_vmul_cm_core_Y_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %5:gprregbank(s32) = G_CONSTANT i32 64
    %3:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %4:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.negmul.conf), %3(<64 x s16>), %4(<32 x s16>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_mac_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $y2



    ; CHECK-LABEL: name: _Z21test_mac_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 64
    ; CHECK-NEXT: [[VMAC_vmac_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_Y_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmac_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 64
    %4:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %5:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.mac.conf), %4(<64 x s16>), %5(<32 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z21test_msc_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $y2



    ; CHECK-LABEL: name: _Z21test_msc_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 64
    ; CHECK-NEXT: [[VMSC_vmac_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VMSC_vmac_vmul_cm_core_Y_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmac_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 64
    %4:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %5:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.msc.conf), %4(<64 x s16>), %5(<32 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z24test_addmac_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32S1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2



    ; CHECK-LABEL: name: _Z24test_addmac_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 64
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_Y_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 64
    %5:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.addmac.conf), %5(<64 x s16>), %6(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z24test_addmsc_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32S1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2



    ; CHECK-LABEL: name: _Z24test_addmsc_conv_8x8_8chDv128_hDv64_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 64
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_Y_X:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_Y_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_Y_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:vregbank(<64 x s8>) = COPY $x0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 64
    %5:vregbank(<64 x s16>) = G_BITCAST %1(<128 x s8>)
    %6:vregbank(<32 x s16>) = G_BITCAST %2(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.addmsc.conf), %5(<64 x s16>), %6(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z17test_mul_4x8_8x16Dv64_hDv128_h
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z17test_mul_4x8_8x16Dv64_hDv128_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 192
    ; CHECK-NEXT: [[VMUL_vmul_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMUL_vmul_vmul_cm_core_X_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %5:gprregbank(s32) = G_CONSTANT i32 192
    %3:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.mul.conf), %3(<32 x s16>), %4(<64 x s16>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_negmul_4x8_8x16Dv64_hDv128_h
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z20test_negmul_4x8_8x16Dv64_hDv128_h
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 192
    ; CHECK-NEXT: [[VNEGMUL_vmul_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VNEGMUL_vmul_vmul_cm_core_X_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %5:gprregbank(s32) = G_CONSTANT i32 192
    %3:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %4:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.negmul.conf), %3(<32 x s16>), %4(<64 x s16>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z17test_mac_4x8_8x16Dv64_hDv128_hDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $y2



    ; CHECK-LABEL: name: _Z17test_mac_4x8_8x16Dv64_hDv128_hDv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 192
    ; CHECK-NEXT: [[VMAC_vmac_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmac_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 192
    %4:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.mac.conf), %4(<32 x s16>), %5(<64 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z17test_msc_4x8_8x16Dv64_hDv128_hDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $y2



    ; CHECK-LABEL: name: _Z17test_msc_4x8_8x16Dv64_hDv128_hDv64_u7__acc32
    ; CHECK: liveins: $dm1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 192
    ; CHECK-NEXT: [[VMSC_vmac_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VMSC_vmac_vmul_cm_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmac_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %6:gprregbank(s32) = G_CONSTANT i32 192
    %4:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %5:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.msc.conf), %4(<32 x s16>), %5(<64 x s16>), %3(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_addmac_4x8_8x16Dv64_hDv128_hDv64_u7__acc32S1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2



    ; CHECK-LABEL: name: _Z20test_addmac_4x8_8x16Dv64_hDv128_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 192
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 192
    %5:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.addmac.conf), %5(<32 x s16>), %6(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_addmsc_4x8_8x16Dv64_hDv128_hDv64_u7__acc32S1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $y2



    ; CHECK-LABEL: name: _Z20test_addmsc_4x8_8x16Dv64_hDv128_hDv64_u7__acc32S1_
    ; CHECK: liveins: $dm1, $dm2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 192
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_X_Y:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<128 x s8>) = COPY $y2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %7:gprregbank(s32) = G_CONSTANT i32 192
    %5:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %6:vregbank(<64 x s16>) = G_BITCAST %2(<128 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.addmsc.conf), %5(<32 x s16>), %6(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_64Dv64_hh
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_hh
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VMUL_vmul_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VMUL_vmul_vmul_cm_core_X_R [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 8
    %6:gprregbank(s32) = G_CONSTANT i32 32
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.mul.conf), %1(<64 x s8>), %4(s32), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_hh
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_hh
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VNEGMUL_vmul_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VNEGMUL_vmul_vmul_cm_core_X_R [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 8
    %6:gprregbank(s32) = G_CONSTANT i32 32
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.negmul.conf), %1(<64 x s8>), %4(s32), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_hhDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_hhDv64_u7__acc32
    ; CHECK: liveins: $dm1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VMAC_vmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_X_R [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4, 8
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 32
    %6:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.mac.conf), %6(<32 x s16>), %5(s32), %3(<64 x s32>), %8(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_hhDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_hhDv64_u7__acc32
    ; CHECK: liveins: $dm1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VMSC_vmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VMSC_vmac_vmul_cm_core_X_R [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4, 8
    %3:accregbank(<64 x s32>) = COPY $dm1
    %8:gprregbank(s32) = G_CONSTANT i32 32
    %6:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.msc.conf), %6(<32 x s16>), %5(s32), %3(<64 x s32>), %8(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_hhDv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_hhDv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_X_R [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_ASSERT_ZEXT %5, 8
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %9:gprregbank(s32) = G_CONSTANT i32 32
    %7:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.addmac.conf), %7(<32 x s16>), %6(s32), %3(<64 x s32>), %4(<64 x s32>), %9(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_hhDv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_hhDv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 32
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_X_R [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_ASSERT_ZEXT %5, 8
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %9:gprregbank(s32) = G_CONSTANT i32 32
    %7:vregbank(<32 x s16>) = G_BITCAST %1(<64 x s8>)
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.addmsc.conf), %7(<32 x s16>), %6(s32), %3(<64 x s32>), %4(<64 x s32>), %9(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_mul_elem_32_32bDv32_tS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z20test_mul_elem_32_32bDv32_tS_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VMUL_vmul_half_vmul_cm_half_core_X_X:%[0-9]+]]:ecml = VMUL_vmul_half_vmul_cm_half_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_vmul_half_vmul_cm_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z23test_negmul_elem_32_32bDv32_tS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z23test_negmul_elem_32_32bDv32_tS_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VNEGMUL_vmul_half_vmul_cm_half_core_X_X:%[0-9]+]]:ecml = VNEGMUL_vmul_half_vmul_cm_half_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_vmul_half_vmul_cm_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z20test_mac_elem_32_32bDv32_tS_Dv32_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z20test_mac_elem_32_32bDv32_tS_Dv32_u7__acc32
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VMAC_vmac_half_vmul_cm_half_core_X_X:%[0-9]+]]:ecml = VMAC_vmac_half_vmul_cm_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_vmac_half_vmul_cm_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z20test_msc_elem_32_32bDv32_tS_Dv32_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z20test_msc_elem_32_32bDv32_tS_Dv32_u7__acc32
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VMSC_vmac_half_vmul_cm_half_core_X_X:%[0-9]+]]:ecml = VMSC_vmac_half_vmul_cm_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_vmac_half_vmul_cm_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z23test_addmac_elem_32_32bDv32_tS_Dv32_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z23test_addmac_elem_32_32bDv32_tS_Dv32_u7__acc32S0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VADDMAC_vaddmac_half_vmul_cm_half_core_X_X:%[0-9]+]]:ecml = VADDMAC_vaddmac_half_vmul_cm_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_vaddmac_half_vmul_cm_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z23test_addmsc_elem_32_32bDv32_tS_Dv32_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z23test_addmsc_elem_32_32bDv32_tS_Dv32_u7__acc32S0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VADDMSC_vaddmac_half_vmul_cm_half_core_X_X:%[0-9]+]]:ecml = VADDMSC_vaddmac_half_vmul_cm_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_vaddmac_half_vmul_cm_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_64Dv64_tt
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_tt
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VMUL_vmul_vmul_cm_core_Y_R:%[0-9]+]]:acc2048 = VMUL_vmul_vmul_cm_core_Y_R [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_vmul_cm_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 16
    %6:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.mul.conf), %1(<64 x s16>), %4(s32), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_tt
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_tt
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VNEGMUL_vmul_vmul_cm_core_Y_R:%[0-9]+]]:acc2048 = VNEGMUL_vmul_vmul_cm_core_Y_R [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_vmul_cm_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 16
    %6:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.negmul.conf), %1(<64 x s16>), %4(s32), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_ttDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_ttDv64_u7__acc32
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VMAC_vmac_vmul_cm_core_Y_R:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_Y_R [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmac_vmul_cm_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4, 16
    %3:accregbank(<64 x s32>) = COPY $dm1
    %7:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.mac.conf), %1(<64 x s16>), %5(s32), %3(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_ttDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_ttDv64_u7__acc32
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VMSC_vmac_vmul_cm_core_Y_R:%[0-9]+]]:acc2048 = VMSC_vmac_vmul_cm_core_Y_R [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmac_vmul_cm_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4, 16
    %3:accregbank(<64 x s32>) = COPY $dm1
    %7:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.msc.conf), %1(<64 x s16>), %5(s32), %3(<64 x s32>), %7(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_ttDv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_ttDv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_Y_R:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_Y_R [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_ASSERT_ZEXT %5, 16
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %8:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.addmac.conf), %1(<64 x s16>), %6(s32), %3(<64 x s32>), %4(<64 x s32>), %8(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_ttDv64_u7__acc32S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_ttDv64_u7__acc32S0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 40
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_Y_R:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_Y_R [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_ASSERT_ZEXT %5, 16
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %8:gprregbank(s32) = G_CONSTANT i32 40
    %0:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.addmsc.conf), %1(<64 x s16>), %6(s32), %3(<64 x s32>), %4(<64 x s32>), %8(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_32Dv32_tt
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_tt
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 74
    ; CHECK-NEXT: [[VMUL_vmul_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VMUL_vmul_vmul_cm_core_X_R [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_vmul_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 16
    %7:gprregbank(s32) = G_CONSTANT i32 74
    %6:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.mul.conf), %1(<32 x s16>), %4(s32), %7(s32)
    %0:accregbank(<32 x s64>) = G_BITCAST %6(<64 x s32>)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_32Dv32_tt
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_tt
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 74
    ; CHECK-NEXT: [[VNEGMUL_vmul_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VNEGMUL_vmul_vmul_cm_core_X_R [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_vmul_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %4:gprregbank(s32) = G_ASSERT_ZEXT %3, 16
    %7:gprregbank(s32) = G_CONSTANT i32 74
    %6:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.negmul.conf), %1(<32 x s16>), %4(s32), %7(s32)
    %0:accregbank(<32 x s64>) = G_BITCAST %6(<64 x s32>)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_32Dv32_ttDv32_u7__acc64
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_ttDv32_u7__acc64
    ; CHECK: liveins: $dm1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 74
    ; CHECK-NEXT: [[VMAC_vmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VMAC_vmac_vmul_cm_core_X_R [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_vmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4, 16
    %3:accregbank(<32 x s64>) = COPY $dm1
    %9:gprregbank(s32) = G_CONSTANT i32 74
    %7:accregbank(<64 x s32>) = G_BITCAST %3(<32 x s64>)
    %8:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.mac.conf), %1(<32 x s16>), %5(s32), %7(<64 x s32>), %9(s32)
    %0:accregbank(<32 x s64>) = G_BITCAST %8(<64 x s32>)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_32Dv32_ttDv32_u7__acc64
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_ttDv32_u7__acc64
    ; CHECK: liveins: $dm1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 74
    ; CHECK-NEXT: [[VMSC_vmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VMSC_vmac_vmul_cm_core_X_R [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_vmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_ASSERT_ZEXT %4, 16
    %3:accregbank(<32 x s64>) = COPY $dm1
    %9:gprregbank(s32) = G_CONSTANT i32 74
    %7:accregbank(<64 x s32>) = G_BITCAST %3(<32 x s64>)
    %8:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.msc.conf), %1(<32 x s16>), %5(s32), %7(<64 x s32>), %9(s32)
    %0:accregbank(<32 x s64>) = G_BITCAST %8(<64 x s32>)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_32Dv32_ttDv32_u7__acc64S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_ttDv32_u7__acc64S0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 74
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_X_R [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_ASSERT_ZEXT %5, 16
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:accregbank(<32 x s64>) = COPY $dm2
    %11:gprregbank(s32) = G_CONSTANT i32 74
    %8:accregbank(<64 x s32>) = G_BITCAST %3(<32 x s64>)
    %9:accregbank(<64 x s32>) = G_BITCAST %4(<32 x s64>)
    %10:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.addmac.conf), %1(<32 x s16>), %6(s32), %8(<64 x s32>), %9(<64 x s32>), %11(s32)
    %0:accregbank(<32 x s64>) = G_BITCAST %10(<64 x s32>)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_32Dv32_ttDv32_u7__acc64S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_ttDv32_u7__acc64S0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mrv16s = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 74
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_X_R:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_X_R [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_ASSERT_ZEXT %5, 16
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:accregbank(<32 x s64>) = COPY $dm2
    %11:gprregbank(s32) = G_CONSTANT i32 74
    %8:accregbank(<64 x s32>) = G_BITCAST %3(<32 x s64>)
    %9:accregbank(<64 x s32>) = G_BITCAST %4(<32 x s64>)
    %10:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.addmsc.conf), %1(<32 x s16>), %6(s32), %8(<64 x s32>), %9(<64 x s32>), %11(s32)
    %0:accregbank(<32 x s64>) = G_BITCAST %10(<64 x s32>)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_64Dv64_8bfloat16S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_8bfloat16S0_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_8bfloat16S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_8bfloat16S0_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_8bfloat16S0_Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_32Dv32_8bfloat16S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_8bfloat16S0_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_8bfloat16S0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_8bfloat16S0_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_8bfloat16S0_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_4x8_8x8Dv32_8bfloat16Dv64_S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_4x8_8x8Dv32_8bfloat16Dv64_S_
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331740
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 50331740
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_4x8_8x8Dv32_8bfloat16Dv64_S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_4x8_8x8Dv32_8bfloat16Dv64_S_
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331740
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 50331740
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331740
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 50331740
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331740
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 50331740
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331740
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 50331740
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_4x8_8x8Dv32_8bfloat16Dv64_S_Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331740
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 50331740
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_64Dv64_8bfloat16Dv64_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_8bfloat16Dv64_DF16_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_8bfloat16Dv64_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_8bfloat16Dv64_DF16_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloatS2_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_8bfloat16Dv64_DF16_Dv64_u10__accfloatS2_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_32Dv32_8bfloat16Dv32_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_8bfloat16Dv32_DF16_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_8bfloat16Dv32_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_8bfloat16Dv32_DF16_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_8bfloat16Dv32_DF16_Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_4x8_8x8Dv32_8bfloat16Dv64_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_4x8_8x8Dv32_8bfloat16Dv64_DF16_
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777308
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 16777308
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_4x8_8x8Dv32_8bfloat16Dv64_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_4x8_8x8Dv32_8bfloat16Dv64_DF16_
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777308
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 16777308
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777308
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 16777308
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777308
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 16777308
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777308
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 16777308
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_4x8_8x8Dv32_8bfloat16Dv64_DF16_Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777308
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 16777308
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_64Dv64_DF16_Dv64_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_DF16_Dv64_8bfloat16
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_DF16_Dv64_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_DF16_Dv64_8bfloat16
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloatS2_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_DF16_Dv64_8bfloat16Dv64_u10__accfloatS2_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_32Dv32_DF16_Dv32_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_DF16_Dv32_8bfloat16
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_DF16_Dv32_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_DF16_Dv32_8bfloat16
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_DF16_Dv32_8bfloat16Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_4x8_8x8Dv32_DF16_Dv64_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_4x8_8x8Dv32_DF16_Dv64_8bfloat16
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554524
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 33554524
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_4x8_8x8Dv32_DF16_Dv64_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_4x8_8x8Dv32_DF16_Dv64_8bfloat16
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554524
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 33554524
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554524
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 33554524
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554524
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 33554524
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554524
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 33554524
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloatS2_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_4x8_8x8Dv32_DF16_Dv64_8bfloat16Dv32_u10__accfloatS2_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554524
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 33554524
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_64Dv64_DF16_S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_DF16_S_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_DF16_S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2, $y3



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_DF16_S_
    ; CHECK: liveins: $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_DF16_S_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_DF16_S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_DF16_S_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $y2, $y3



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_DF16_S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_DF16_S_Dv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_DF16_S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_DF16_S_Dv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $y2, $y3



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_DF16_S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $y2, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:vregbank(<64 x s16>) = COPY $y3
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_32Dv32_DF16_S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_DF16_S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_DF16_S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_DF16_S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_DF16_S_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_DF16_S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_DF16_S_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_DF16_S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_DF16_S_Dv32_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_DF16_S_Dv32_u10__accfloatS0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_DF16_S_Dv32_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_DF16_S_Dv32_u10__accfloatS0_
    ; CHECK: liveins: $cml1, $cml2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<32 x s16>) = COPY $x2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_4x8_8x8Dv32_DF16_Dv64_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_4x8_8x8Dv32_DF16_Dv64_DF16_
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 92
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 92
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_4x8_8x8Dv32_DF16_Dv64_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_4x8_8x8Dv32_DF16_Dv64_DF16_
    ; CHECK: liveins: $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 92
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 92
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 92
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 92
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $x0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 92
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 92
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 92
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 92
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $x0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_4x8_8x8Dv32_DF16_Dv64_DF16_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $x0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 92
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:vregbank(<64 x s16>) = COPY $y2
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %5:gprregbank(s32) = G_CONSTANT i32 92
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_32Dv32_8bfloat16S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_8bfloat16S_
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_8bfloat16S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_8bfloat16S_
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_8bfloat16S_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_8bfloat16S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_8bfloat16S_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_8bfloat16S_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_8bfloat16S_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_8bfloat16S_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_8bfloat16S_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_8bfloat16S_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_32Dv32_8bfloat16DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_8bfloat16DF16_
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_8bfloat16DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_8bfloat16DF16_
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_8bfloat16DF16_Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_32Dv32_DF16_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_DF16_8bfloat16
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_DF16_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_DF16_8bfloat16
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_DF16_8bfloat16Dv32_u10__accfloatS1_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_32Dv32_DF16_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mul_elem_32Dv32_DF16_DF16_
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_negmul_elem_32Dv32_DF16_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0



    ; CHECK-LABEL: name: _Z19test_negmul_elem_32Dv32_DF16_DF16_
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEGMUL_f_vmul_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s16), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mac_elem_32Dv32_DF16_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_mac_elem_32Dv32_DF16_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMAC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_msc_elem_32Dv32_DF16_DF16_Dv32_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $r0, $x0



    ; CHECK-LABEL: name: _Z16test_msc_elem_32Dv32_DF16_DF16_Dv32_u10__accfloat
    ; CHECK: liveins: $cml1, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VMSC_f_vmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmac_elem_32Dv32_DF16_DF16_Dv32_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmac_elem_32Dv32_DF16_DF16_Dv32_u10__accfloatS0_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z19test_addmsc_elem_32Dv32_DF16_DF16_Dv32_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2, $r0, $x0



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_32Dv32_DF16_DF16_Dv32_u10__accfloatS0_
    ; CHECK: liveins: $cml1, $cml2, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_core_X_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s16), %3(<32 x s32>), %4(<32 x s32>), %6(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z16test_mul_elem_64Dv64_8bfloat16S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_8bfloat16S_
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_8bfloat16S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_8bfloat16S_
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_8bfloat16S_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_8bfloat16S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_8bfloat16S_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_8bfloat16S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_8bfloat16S_Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_8bfloat16S_Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_8bfloat16S_Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_8bfloat16S_Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 50331708
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 50331708
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_64Dv64_8bfloat16DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_8bfloat16DF16_
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_8bfloat16DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_8bfloat16DF16_
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_8bfloat16DF16_Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 16777276
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 16777276
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_64Dv64_DF16_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_DF16_8bfloat16
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_DF16_8bfloat16
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_DF16_8bfloat16
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_DF16_8bfloat16Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOVXM_lng_cg:%[0-9]+]]:mrv8 = MOVXM_lng_cg 33554492
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOVXM_lng_cg]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 33554492
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_elem_64Dv64_DF16_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mul_elem_64Dv64_DF16_DF16_
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_elem_64Dv64_DF16_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2



    ; CHECK-LABEL: name: _Z19test_negmul_elem_64Dv64_DF16_DF16_
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %3(s32)
    %4:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s16), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_elem_64Dv64_DF16_DF16_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_mac_elem_64Dv64_DF16_DF16_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_elem_64Dv64_DF16_DF16_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $r0, $y2



    ; CHECK-LABEL: name: _Z16test_msc_elem_64Dv64_DF16_DF16_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %4:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %4(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %5:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_elem_64Dv64_DF16_DF16_Dv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmac_elem_64Dv64_DF16_DF16_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_elem_64Dv64_DF16_DF16_Dv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0, $y2



    ; CHECK-LABEL: name: _Z19test_addmsc_elem_64Dv64_DF16_DF16_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mrv16s = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R [[COPY3]], [[COPY4]], [[COPY]], [[COPY2]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_R]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s16>) = COPY $y2
    %5:gprregbank(s32) = COPY $r0
    %2:gprregbank(s16) = G_TRUNC %5(s32)
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s16), %3(<64 x s32>), %4(<64 x s32>), %6(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mul_8x8_8x89v64float8S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mul_8x8_8x89v64float8S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 20
    ; CHECK-NEXT: [[VMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 20
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.mul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_negmul_8x8_8x89v64float8S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2



    ; CHECK-LABEL: name: _Z19test_negmul_8x8_8x89v64float8S_
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 20
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bf_vmul_bf_core_X_X [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 20
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.negmul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_mac_8x8_8x89v64float8S_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_mac_8x8_8x89v64float8S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 20
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 20
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.mac.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z16test_msc_8x8_8x89v64float8S_Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $x0, $x2



    ; CHECK-LABEL: name: _Z16test_msc_8x8_8x89v64float8S_Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 20
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 20
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.msc.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmac_8x8_8x89v64float8S_Dv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmac_8x8_8x89v64float8S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 20
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 20
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.addmac.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z19test_addmsc_8x8_8x89v64float8S_Dv64_u10__accfloatS0_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $x0, $x2



    ; CHECK-LABEL: name: _Z19test_addmsc_8x8_8x89v64float8S_Dv64_u10__accfloatS0_
    ; CHECK: liveins: $dm1, $dm2, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 20
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_X_X:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:vregbank(<64 x s8>) = COPY $x2
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:accregbank(<64 x s32>) = COPY $dm2
    %5:gprregbank(s32) = G_CONSTANT i32 20
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.addmsc.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_addDv64_u7__acc32S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2



    ; CHECK-LABEL: name: _Z8test_addDv64_u7__acc32S_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VADD_vacc:%[0-9]+]]:acc2048 = VADD_vacc [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VADD_vacc]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %3:accregbank(<32 x s64>) = G_BITCAST %1(<64 x s32>)
    %4:accregbank(<32 x s64>) = G_BITCAST %2(<64 x s32>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.add.conf), %3(<32 x s64>), %4(<32 x s64>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_subDv64_u7__acc32S_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2



    ; CHECK-LABEL: name: _Z8test_subDv64_u7__acc32S_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VSUB_vacc:%[0-9]+]]:acc2048 = VSUB_vacc [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VSUB_vacc]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %3:accregbank(<32 x s64>) = G_BITCAST %1(<64 x s32>)
    %4:accregbank(<32 x s64>) = G_BITCAST %2(<64 x s32>)
    %5:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.sub.conf), %3(<32 x s64>), %4(<32 x s64>), %6(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %5(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_negDv64_u7__acc32
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1



    ; CHECK-LABEL: name: _Z8test_negDv64_u7__acc32
    ; CHECK: liveins: $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[VNEG_vneg:%[0-9]+]]:acc2048 = VNEG_vneg [[COPY]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: $dm0 = COPY [[VNEG_vneg]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:accregbank(<32 x s64>) = G_BITCAST %1(<64 x s32>)
    %3:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.neg.conf), %2(<32 x s64>), %4(s32)
    %0:accregbank(<64 x s32>) = G_BITCAST %3(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_addDv64_u10__accfloatS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2



    ; CHECK-LABEL: name: _Z8test_addDv64_u10__accfloatS_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADD_f_vacc_fp:%[0-9]+]]:acc2048 = VADD_f_vacc_fp [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADD_f_vacc_fp]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.add.conf), %1(<64 x s32>), %2(<64 x s32>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_subDv64_u10__accfloatS_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2



    ; CHECK-LABEL: name: _Z8test_subDv64_u10__accfloatS_
    ; CHECK: liveins: $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VSUB_f_vacc_fp:%[0-9]+]]:acc2048 = VSUB_f_vacc_fp [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VSUB_f_vacc_fp]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:accregbank(<64 x s32>) = COPY $dm2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.sub.conf), %1(<64 x s32>), %2(<64 x s32>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z8test_negDv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm1



    ; CHECK-LABEL: name: _Z8test_negDv64_u10__accfloat
    ; CHECK: liveins: $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEG_f_vneg_fp:%[0-9]+]]:acc2048 = VNEG_f_vneg_fp [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEG_f_vneg_fp]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<64 x s32>) = COPY $dm1
    %2:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.neg.conf), %1(<64 x s32>), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z17test_clr_v64acc32v
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: _Z17test_clr_v64acc32v
    ; CHECK: [[VCLR_vclr:%[0-9]+]]:acc2048 = VCLR_vclr
    ; CHECK-NEXT: $dm0 = COPY [[VCLR_vclr]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.clr.ACC2048.conf)
    %0:accregbank(<64 x s32>) = G_BITCAST %1(<32 x s64>)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z17test_clr_v32acc32v
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: _Z17test_clr_v32acc32v
    ; CHECK: [[VCLR_vclr_half:%[0-9]+]]:ecml = VCLR_vclr_half
    ; CHECK-NEXT: $cml0 = COPY [[VCLR_vclr_half]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.clr.ACC1024l.conf)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            test_add_acc1024
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2



    ; CHECK-LABEL: name: test_add_acc1024
    ; CHECK: liveins: $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY [[COPY1]]
    ; CHECK-NEXT: [[VADD_vacc_half:%[0-9]+]]:ecml = VADD_vacc_half [[COPY2]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc1024 = COPY [[VADD_vacc_half]]
    ; CHECK-NEXT: $cml0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:accregbank(<32 x s32>) = COPY $cml1
    %2:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %3:accregbank(<16 x s64>) = G_BITCAST %1(<32 x s32>)
    %4:accregbank(<16 x s64>) = G_BITCAST %2(<32 x s32>)
    %5:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC1024.add.conf), %3(<16 x s64>), %4(<16 x s64>), %6(s32)
    %0:accregbank(<32 x s32>) = G_BITCAST %5(<16 x s64>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...

---
name:            test_add_accfloat1024
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2



    ; CHECK-LABEL: name: test_add_accfloat1024
    ; CHECK: liveins: $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VADD_f_vacc_half_fp:%[0-9]+]]:ecml = VADD_f_vacc_half_fp [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADD_f_vacc_half_fp]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:accregbank(<32 x s32>) = COPY $cml1
    %2:accregbank(<32 x s32>) = COPY $cml2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.add.conf), %1(<32 x s32>), %2(<32 x s32>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...

---
name:            test_sub_acc1024
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2



    ; CHECK-LABEL: name: test_sub_acc1024
    ; CHECK: liveins: $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY [[COPY1]]
    ; CHECK-NEXT: [[VSUB_vacc_half:%[0-9]+]]:ecml = VSUB_vacc_half [[COPY2]], [[COPY3]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc1024 = COPY [[VSUB_vacc_half]]
    ; CHECK-NEXT: $cml0 = COPY [[COPY4]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:accregbank(<32 x s32>) = COPY $cml1
    %2:accregbank(<32 x s32>) = COPY $cml2
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %3:accregbank(<16 x s64>) = G_BITCAST %1(<32 x s32>)
    %4:accregbank(<16 x s64>) = G_BITCAST %2(<32 x s32>)
    %5:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC1024.sub.conf), %3(<16 x s64>), %4(<16 x s64>), %6(s32)
    %0:accregbank(<32 x s32>) = G_BITCAST %5(<16 x s64>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...

---
name:            test_sub_accfloat1024
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1, $cml2



    ; CHECK-LABEL: name: test_sub_accfloat1024
    ; CHECK: liveins: $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ecml = COPY $cml2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VSUB_f_vacc_half_fp:%[0-9]+]]:ecml = VSUB_f_vacc_half_fp [[COPY]], [[COPY1]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VSUB_f_vacc_half_fp]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:accregbank(<32 x s32>) = COPY $cml1
    %2:accregbank(<32 x s32>) = COPY $cml2
    %3:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.sub.conf), %1(<32 x s32>), %2(<32 x s32>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...

---
name:            test_neg_acc1024
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1

    ; CHECK-LABEL: name: test_neg_acc1024
    ; CHECK: liveins: $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ecml = COPY [[COPY]]
    ; CHECK-NEXT: [[VNEG_vneg_half:%[0-9]+]]:ecml = VNEG_vneg_half [[COPY1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY [[VNEG_vneg_half]]
    ; CHECK-NEXT: $cml0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:accregbank(<16 x s64>) = G_BITCAST %1(<32 x s32>)
    %3:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC1024.neg.conf), %2(<16 x s64>), %4(s32)
    %0:accregbank(<32 x s32>) = G_BITCAST %3(<16 x s64>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...

---
name:            test_neg_accfloat1024
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml1


    ; CHECK-LABEL: name: test_neg_accfloat1024
    ; CHECK: liveins: $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 60
    ; CHECK-NEXT: [[VNEG_f_vneg_half_fp:%[0-9]+]]:ecml = VNEG_f_vneg_half_fp [[COPY]], [[MOV_RLC_imm11_pseudo]], implicit-def dead $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VNEG_f_vneg_half_fp]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:accregbank(<32 x s32>) = COPY $cml1
    %2:gprregbank(s32) = G_CONSTANT i32 60
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.neg.conf), %1(<32 x s32>), %2(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
