# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name:            pack_from_I512_to_64lanes_of_I4
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2

    ; CHECK-LABEL: name: pack_from_I512_to_64lanes_of_I4
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VPACK_mv_pack_w_packSign0_:%[0-9]+]]:vec256 = VPACK_mv_pack_w_packSign0 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: $packsign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $wl0 = COPY [[VPACK_mv_pack_w_packSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<64 x s8>) = COPY $x2
    %2:gprregbank(s32) = COPY $r0
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I512.I4.I8), %1(<64 x s8>), %2(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            pack_from_I512_to_32lanes_of_I8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2

    ; CHECK-LABEL: name: pack_from_I512_to_32lanes_of_I8
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VPACK_mv_pack_w_packSign0_:%[0-9]+]]:vec256 = VPACK_mv_pack_w_packSign0 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: $packsign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $wl0 = COPY [[VPACK_mv_pack_w_packSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = COPY $r0
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I512.I8.I16), %1(<32 x s16>), %2(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            pack_from_I1024_to_128lanes_of_I4
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2

    ; CHECK-LABEL: name: pack_from_I1024_to_128lanes_of_I4
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VPACK_mv_pack_x_packSign0_:%[0-9]+]]:vec512 = VPACK_mv_pack_x_packSign0 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: $packsign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VPACK_mv_pack_x_packSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:gprregbank(s32) = COPY $r0
    %0:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I1024.I4.I8), %1(<128 x s8>), %2(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            pack_from_I1024_to_64lanes_of_I8
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2

    ; CHECK-LABEL: name: pack_from_I1024_to_64lanes_of_I8
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $packsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VPACK_mv_pack_x_packSign0_:%[0-9]+]]:vec512 = VPACK_mv_pack_x_packSign0 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: $packsign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VPACK_mv_pack_x_packSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:gprregbank(s32) = COPY $r0
    %0:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I1024.I8.I16), %1(<64 x s16>), %2(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            pack_from_I512_to_64lanes_of_I4_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2

    ; CHECK-LABEL: name: pack_from_I512_to_64lanes_of_I4_signed
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VPACK_mv_pack_w_packSign1_:%[0-9]+]]:vec256 = VPACK_mv_pack_w_packSign1 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: $wl0 = COPY [[VPACK_mv_pack_w_packSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<64 x s8>) = COPY $x2
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I512.I4.I8), %1(<64 x s8>), %2(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            pack_from_I512_to_32lanes_of_I8_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2

    ; CHECK-LABEL: name: pack_from_I512_to_32lanes_of_I8_signed
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VPACK_mv_pack_w_packSign1_:%[0-9]+]]:vec256 = VPACK_mv_pack_w_packSign1 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: $wl0 = COPY [[VPACK_mv_pack_w_packSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I512.I8.I16), %1(<32 x s16>), %2(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            pack_from_I1024_to_128lanes_of_I4_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2

    ; CHECK-LABEL: name: pack_from_I1024_to_128lanes_of_I4_signed
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VPACK_mv_pack_x_packSign1_:%[0-9]+]]:vec512 = VPACK_mv_pack_x_packSign1 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: $x0 = COPY [[VPACK_mv_pack_x_packSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<128 x s8>) = COPY $y2
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I1024.I4.I8), %1(<128 x s8>), %2(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            pack_from_I1024_to_64lanes_of_I8_signed
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2

    ; CHECK-LABEL: name: pack_from_I1024_to_64lanes_of_I8_signed
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: $crpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VPACK_mv_pack_x_packSign1_:%[0-9]+]]:vec512 = VPACK_mv_pack_x_packSign1 [[COPY]], implicit $crpacksize, implicit $crsat, implicit $packsign1
    ; CHECK-NEXT: $x0 = COPY [[VPACK_mv_pack_x_packSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.pack.I1024.I8.I16), %1(<64 x s16>), %2(s32)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
