# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=aie-preisel-combiner,instruction-select -verify-machineinstrs %s -o - | FileCheck %s

...

---
name:              vextbcstshfl_16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_16
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VEXTBCSTSHFL_16_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_16 [[DEF]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_16_]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<32 x s16>), %3(s32)
    %7:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %5(s32)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vshuffle), %8(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

---
name:              vextbcstshfl_32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_32
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VEXTBCSTSHFL_32_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_32 [[DEF]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_32_]]
    %ptr:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %5:gprregbank(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT %4(<16 x s32>), %3(s32)
    %6:gprregbank(<2 x s16>) = G_BITCAST %5(s32)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbroadcast32.bf512), %6(<2 x s16>)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vshuffle), %8(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

---
name:              vextbcstshfl_64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_64
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VEXTBCSTSHFL_64_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_64 [[DEF]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_64_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %5:gprregbank(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR %4(<16 x s32>), %3(s32)
    %6:gprregbank(<4 x s16>) = G_BITCAST %5(<2 x s32>)
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbroadcast64.bf512), %6(<4 x s16>)
    %8:vregbank(<16 x s32>) = G_BITCAST %7(<32 x s16>)
    %9:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vshuffle), %8(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %9(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...

---
name:              vextbcstshfl_128
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: vextbcstshfl_128
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mr29_insert = MOV_RLC_imm11_pseudo 28
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mlockid_reg = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[VEXTBCSTSHFL_128_:%[0-9]+]]:vec512 = VEXTBCSTSHFL_128 [[DEF]], [[MOV_RLC_imm11_pseudo1]], [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VEXTBCSTSHFL_128_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %2:gprregbank(s32) = G_CONSTANT i32 28
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %4:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %5:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vextract.broadcast128.I512), %4(<16 x s32>), %3(s32)
    %6:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vshuffle), %5(<16 x s32>), %1(<16 x s32>), %2(s32)
    %10:vregbank(<32 x s16>) = G_BITCAST %6(<16 x s32>)
    PseudoRET implicit $lr, implicit %10(<32 x s16>)
...
...
---
name:            _Z15test_shuffle_s8ij
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: _Z15test_shuffle_s8ij
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r1
    ; CHECK-NEXT: [[VBCSTSHFL_8_vec_broadcast_shuffle_x:%[0-9]+]]:vec512 = VBCSTSHFL_8_vec_broadcast_shuffle_x [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VBCSTSHFL_8_vec_broadcast_shuffle_x]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = COPY $r1
    %3:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbcst.shuffle8), %1(s32), %2(s32)
    %0:vregbank(<64 x s8>) = G_BITCAST %3(<16 x s32>)
    $x0 = COPY %0(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z16test_shuffle_s16ij
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: _Z16test_shuffle_s16ij
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r1
    ; CHECK-NEXT: [[VBCSTSHFL_16_vec_broadcast_shuffle_x:%[0-9]+]]:vec512 = VBCSTSHFL_16_vec_broadcast_shuffle_x [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VBCSTSHFL_16_vec_broadcast_shuffle_x]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = COPY $r1
    %3:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbcst.shuffle16), %1(s32), %2(s32)
    %0:vregbank(<32 x s16>) = G_BITCAST %3(<16 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z16test_shuffle_s32ij
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $r0, $r1

    ; CHECK-LABEL: name: _Z16test_shuffle_s32ij
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r1
    ; CHECK-NEXT: [[VBCSTSHFL_32_vec_broadcast_shuffle_x:%[0-9]+]]:vec512 = VBCSTSHFL_32_vec_broadcast_shuffle_x [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VBCSTSHFL_32_vec_broadcast_shuffle_x]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(s32) = COPY $r0
    %2:gprregbank(s32) = COPY $r1
    %0:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbcst.shuffle32), %1(s32), %2(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
---
name:            _Z16test_shuffle_s64Dv2_jj
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $l0, $r2

    ; CHECK-LABEL: name: _Z16test_shuffle_s64Dv2_jj
    ; CHECK: liveins: $l0, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mr29_insert = COPY $r2
    ; CHECK-NEXT: [[VBCSTSHFL_64_vec_broadcast_shuffle_x:%[0-9]+]]:vec512 = VBCSTSHFL_64_vec_broadcast_shuffle_x [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VBCSTSHFL_64_vec_broadcast_shuffle_x]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:gprregbank(<2 x s32>) = COPY $l0
    %2:gprregbank(s32) = COPY $r2
    %0:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vbcst.shuffle64), %1(<2 x s32>), %2(s32)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0

...
