# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_CONV_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_256
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    G_STORE %104, %0 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $cml0
    ; CHECK-LABEL: name: VST_CONV_512
    ; CHECK: liveins: $p0, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmx_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %100:accregbank(<16 x s64>) = COPY $cml0
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    G_STORE %104, %0 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_OFFSET_imm_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_OFFSET_imm_256
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], -128, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], 96, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_OFFSET_imm_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $cml0
    ; CHECK-LABEL: name: VST_CONV_OFFSET_imm_512
    ; CHECK: liveins: $p0, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmx_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmx_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], -128, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmx_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], 256, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<16 x s64>) = COPY $cml0
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_OFFSET_non_imm_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_OFFSET_non_imm_256
    ; CHECK: liveins: $p0, $r0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 120
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx [[COPY3]], [[COPY]], [[COPY2]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx [[COPY3]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx [[COPY3]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %9:modregbank(s20) = G_CONSTANT i20 16
    %12:modregbank(s20) = G_CONSTANT i20 120
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_OFFSET_non_imm_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $cml0
    ; CHECK-LABEL: name: VST_CONV_OFFSET_non_imm_512
    ; CHECK: liveins: $p0, $r0, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 120
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmx_sts_srs_bf16_idx [[COPY3]], [[COPY]], [[COPY2]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmx_sts_srs_bf16_idx [[COPY3]], [[COPY]], [[MOV_PD_imm11_pseudo]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmx_sts_srs_bf16_idx [[COPY3]], [[COPY]], [[MOV_PD_imm11_pseudo1]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %9:modregbank(s20) = G_CONSTANT i20 16
    %12:modregbank(s20) = G_CONSTANT i20 120
    %100:accregbank(<16 x s64>) = COPY $cml0
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_POSTINC_imm_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_POSTINC_imm_256
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[COPY]], 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm1:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm]], -256, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm2:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm1]], 224, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 224
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %0, %8 :: (store (<16 x s16>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %20, %10 :: (store (<16 x s16>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_POSTINC_imm_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $cml0
    ; CHECK-LABEL: name: VST_CONV_POSTINC_imm_512
    ; CHECK: liveins: $p0, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[COPY]], 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm1:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm]], -256, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm2:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm1]], 128, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %10:modregbank(s20) = G_CONSTANT i20 -256
    %11:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<16 x s64>) = COPY $cml0
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %0, %8 :: (store (<16 x s32>))
    %22:ptrregbank(p0) = G_AIE_POSTINC_STORE %106, %20, %10 :: (store (<16 x s32>))
    %23:ptrregbank(p0) = G_AIE_POSTINC_STORE %107, %22, %11 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_POSTINC_non_imm_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_POSTINC_non_imm_256
    ; CHECK: liveins: $p0, $r0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm1:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm [[COPY3]], [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm]], [[MOV_PD_imm11_pseudo]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm2:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm [[COPY3]], [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %9:modregbank(s20) = G_CONSTANT i20 16
    %12:modregbank(s20) = G_CONSTANT i20 256
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<16 x s16>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %19, %9 :: (store (<16 x s16>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %21, %12 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_POSTINC_non_imm_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $cml0
    ; CHECK-LABEL: name: VST_CONV_POSTINC_non_imm_512
    ; CHECK: liveins: $p0, $r0, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 120
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm [[COPY3]], [[COPY]], [[COPY2]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm1:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm [[COPY3]], [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm]], [[MOV_PD_imm11_pseudo]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm2:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm [[COPY3]], [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm1]], [[MOV_PD_imm11_pseudo1]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %9:modregbank(s20) = G_CONSTANT i20 16
    %12:modregbank(s20) = G_CONSTANT i20 120
    %100:accregbank(<16 x s64>) = COPY $cml0
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %19:ptrregbank(p0) = G_AIE_POSTINC_STORE %103, %0, %7 :: (store (<16 x s32>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %105, %19, %9 :: (store (<16 x s32>))
    %24:ptrregbank(p0) = G_AIE_POSTINC_STORE %108, %21, %12 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_2D_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_2D_256
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16_:%[0-9]+]]:ep, [[VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16_1:%[0-9]+]]:edc = VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf16 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %19:ptrregbank(p0), %7:modregbank(s20) = G_AIE_POSTINC_2D_STORE %103, %0, %1, %2, %3, %4 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_2D_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $cml0
    ; CHECK-LABEL: name: VST_CONV_2D_512
    ; CHECK: liveins: $p0, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16_:%[0-9]+]]:ep, [[VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16_1:%[0-9]+]]:edc = VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf16 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %100:accregbank(<16 x s64>) = COPY $cml0
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %19:ptrregbank(p0), %7:modregbank(s20) = G_AIE_POSTINC_2D_STORE %103, %0, %1, %2, %3, %4 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_3D_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_3D_256
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16_:%[0-9]+]]:ep, [[VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16_1:%[0-9]+]]:edcl, [[VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16_2:%[0-9]+]]:edch = VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf16 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %103, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_3D_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $cml0
    ; CHECK-LABEL: name: VST_CONV_3D_512
    ; CHECK: liveins: $p0, $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16_:%[0-9]+]]:ep, [[VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16_1:%[0-9]+]]:edcl, [[VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16_2:%[0-9]+]]:edch = VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf16 [[COPY1]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %100:accregbank(<16 x s64>) = COPY $cml0
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %19:ptrregbank(p0), %8:modregbank(s20), %9:modregbank(s20) = G_AIE_POSTINC_3D_STORE %103, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_insertion_point_256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0, $bmll1
    ; CHECK-LABEL: name: VST_CONV_insertion_point_256
    ; CHECK: liveins: $p0, $bmll0, $bmll1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll1
    ; CHECK-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm [[COPY2]], [[COPY]], [[MOV_PD_imm11_pseudo]] :: (store (<8 x s64>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmw_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[COPY]], 32, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 32
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %101:accregbank(<8 x s64>) = COPY $bmll1
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %101, %0, %8 :: (store (<8 x s64>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %0, %8 :: (store (<16 x s16>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_insertion_point_512
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $cml0, $bmll1
    ; CHECK-LABEL: name: VST_CONV_insertion_point_512
    ; CHECK: liveins: $p0, $cml0, $bmll1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bmll1
    ; CHECK-NEXT: [[VST_dmx_sts_bm_st_pstm_nrm_imm:%[0-9]+]]:ep = VST_dmx_sts_bm_st_pstm_nrm_imm [[COPY2]], [[COPY]], 64 :: (store (<8 x s64>))
    ; CHECK-NEXT: [[VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm:%[0-9]+]]:ep = VST_CONV_bf16_fp32_dmx_sts_srs_bf16_pstm_nrm_imm [[COPY1]], [[COPY]], 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 64
    %100:accregbank(<16 x s64>) = COPY $cml0
    %101:accregbank(<8 x s64>) = COPY $bmll1
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %100:accregbank(<16 x s64>)
    %20:ptrregbank(p0) = G_AIE_POSTINC_STORE %101, %0, %8 :: (store (<8 x s64>))
    %21:ptrregbank(p0) = G_AIE_POSTINC_STORE %104, %0, %8 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_COPY_BITCAST
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_COPY_BITCAST
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: VST_CONV_bf16_fp32_dmw_sts_srs_bf16_idx_imm [[COPY1]], [[COPY]], 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd :: (store (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %100:accregbank(<8 x s64>) = COPY $bmll0
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<8 x s64>)
    %150:vregbank(<8 x s32>) = G_BITCAST %104(<16 x s16>)
    %200:vregbank(<8 x s32>) = COPY %150(<8 x s32>)
    G_STORE %200, %0 :: (store (<8 x s32>))
    PseudoRET implicit $lr
...

---
name:            VST_CONV_COPY_BITCAST_no_single_use_bit_cast
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_COPY_BITCAST_no_single_use_bit_cast
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_:%[0-9]+]]:vec256 = VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16 [[COPY1]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: VST_dmw_sts_w_st_idx_imm [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_]], [[COPY]], 0 :: (store (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_]]
    %0:ptrregbank(p0) = COPY $p0
    %100:accregbank(<16 x s32>) = COPY $bmll0
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<16 x s32>)
    %150:vregbank(<8 x s32>) = G_BITCAST %104(<16 x s16>)
    %200:vregbank(<8 x s32>) = COPY %150(<8 x s32>)
    G_STORE %200, %0 :: (store (<8 x s32>))
    PseudoRET implicit $lr, implicit %150
...

---
name:            VST_CONV_COPY_BITCAST_no_single_use_copy
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $bmll0
    ; CHECK-LABEL: name: VST_CONV_COPY_BITCAST_no_single_use_copy
    ; CHECK: liveins: $p0, $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_:%[0-9]+]]:vec256 = VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16 [[COPY1]], implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crfpconvsat, implicit $crrnd
    ; CHECK-NEXT: VST_dmw_sts_w_st_idx_imm [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_]], [[COPY]], 0 :: (store (<8 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VCONV_bf16_fp32_mv_conv_mv_w_srs_bf16_]]
    %0:ptrregbank(p0) = COPY $p0
    %100:accregbank(<16 x s32>) = COPY $bmll0
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %100:accregbank(<16 x s32>)
    %150:vregbank(<8 x s32>) = G_BITCAST %104(<16 x s16>)
    %200:vregbank(<8 x s32>) = COPY %150(<8 x s32>)
    G_STORE %200, %0 :: (store (<8 x s32>))
    PseudoRET implicit $lr, implicit %200
...
