# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_load_4x16_lo
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1:
    liveins: $wl2
    ;CHECK-LABEL: name:            test_load_4x16_lo

    ;CHECK: [[COPY_0:%[0-9]+]]:vec256 = COPY $wl2
    ;CHECK-NEXT: [[VLDB_1:%[0-9]+]]:vec256 = VLDB_4x16_lo [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VLDB_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0


    %1:vregbank(<8 x s32>) = COPY $wl2
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.load.4x16.lo), %1(<8 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_load_4x16_hi
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1:
    liveins: $wl2
    ;CHECK-LABEL: name:            test_load_4x16_hi

    ;CHECK: [[COPY_0:%[0-9]+]]:vec256 = COPY $wl2
    ;CHECK-NEXT: [[VLDB_1:%[0-9]+]]:vec256 = VLDB_4x16_hi [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VLDB_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0


    %1:vregbank(<8 x s32>) = COPY $wl2
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.load.4x16.hi), %1(<8 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_load_4x32_lo
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1:
    liveins: $wl2
    ;CHECK-LABEL: name:            test_load_4x32_lo

    ;CHECK: [[COPY_0:%[0-9]+]]:vec256 = COPY $wl2
    ;CHECK-NEXT: [[VLDB_1:%[0-9]+]]:vec256 = VLDB_4x32_lo [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VLDB_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0


    %1:vregbank(<8 x s32>) = COPY $wl2
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.load.4x32.lo), %1(<8 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_load_4x32_hi
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1:
    liveins: $wl2
    ;CHECK-LABEL: name:            test_load_4x32_hi

    ;CHECK: [[COPY_0:%[0-9]+]]:vec256 = COPY $wl2
    ;CHECK-NEXT: [[VLDB_1:%[0-9]+]]:vec256 = VLDB_4x32_hi [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VLDB_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0


    %1:vregbank(<8 x s32>) = COPY $wl2
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.load.4x32.hi), %1(<8 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_load_4x64_lo
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1:
    liveins: $wl2
    ;CHECK-LABEL: name:            test_load_4x64_lo

    ;CHECK: [[COPY_0:%[0-9]+]]:vec256 = COPY $wl2
    ;CHECK-NEXT: [[VLDB_1:%[0-9]+]]:vec256 = VLDB_4x64_lo [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VLDB_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0


    %1:vregbank(<8 x s32>) = COPY $wl2
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.load.4x64.lo), %1(<8 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            test_load_4x64_hi
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1:
    liveins: $wl2
    ;CHECK-LABEL: name:            test_load_4x64_hi

    ;CHECK: [[COPY_0:%[0-9]+]]:vec256 = COPY $wl2
    ;CHECK-NEXT: [[VLDB_1:%[0-9]+]]:vec256 = VLDB_4x64_hi [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VLDB_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0


    %1:vregbank(<8 x s32>) = COPY $wl2
    %0:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.load.4x64.hi), %1(<8 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0

...
