# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name:            add2d_byte
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p1, $p2, $r0, $r1, $r2
    ;CHECK-LABEL: name:            add2d_byte

    ;CHECK: [[COPY_0:%[0-9]+]]:ep = COPY $p1
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:er = COPY $r0
    ;CHECK-NEXT: [[COPY_2:%[0-9]+]]:er = COPY $r1
    ;CHECK-NEXT: [[COPY_3:%[0-9]+]]:ep = COPY $p2
    ;CHECK-NEXT: [[COPY_4:%[0-9]+]]:er = COPY $r2
    ;CHECK-NEXT: [[COPY_5:%[0-9]+]]:em = COPY [[COPY_1]]
    ;CHECK-NEXT: [[COPY_6:%[0-9]+]]:edj = COPY [[COPY_4]]
    ;CHECK-NEXT: [[COPY_7:%[0-9]+]]:edn = COPY [[COPY_2]]
    ;CHECK-NEXT: [[LDA__8:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY_3]], 0 :: (load (s32))
    ;CHECK-NEXT: [[COPY_9:%[0-9]+]]:edc = COPY [[LDA__8]]
    ;CHECK-NEXT: [[COPY_1]]4:ed = REG_SEQUENCE [[COPY_5]], %subreg.sub_mod, [[COPY_7]], %subreg.sub_dim_size, [[COPY_6]], %subreg.sub_dim_stride, [[COPY_9]], %subreg.sub_dim_count
    ;CHECK-NEXT: [[PADD_10:%[0-9]+]]:ep, [[COPY_1]]1:edc = PADD_2D_pseudo [[COPY_0]], %14
    ;CHECK-NEXT: [[COPY_1]]2:ep = COPY %11
    ;CHECK-NEXT: [[COPY_1]]3:er = COPY %12
    ;CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY_1]]3, [[COPY_3]], 0 :: (store (s32))
    ;CHECK-NEXT: $p0 = COPY [[PADD_10]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $p0

    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:modregbank(s20) = G_TRUNC %2:gprregbank(s32)
    %7:modregbank(s20) = G_TRUNC %5:gprregbank(s32)
    %8:modregbank(s20) = G_TRUNC %3:gprregbank(s32)
    %9:gprregbank(s32) = G_LOAD %4:ptrregbank(p0) :: (load (s32) , align 4)
    %10:modregbank(s20) = G_TRUNC %9:gprregbank(s32)
    %11:ptrregbank(p0), %12:modregbank(s20) = G_INTRINSIC intrinsic(@llvm.aie2ps.add.2d), %1:ptrregbank(p0), %6:modregbank(s20), %7:modregbank(s20), %8:modregbank(s20), %10:modregbank(s20)
    %18:ptrregbank(s20) = COPY %12:modregbank(s20)
    %13:gprregbank(s32) = G_ZEXT %18:ptrregbank(s20)
    G_STORE %13:gprregbank(s32), %4:ptrregbank(p0) :: (store (s32) )
    $p0 = COPY %11:ptrregbank(p0)
    PseudoRET implicit $lr, implicit $p0
...


---
name:            add2d_constrained_regClass
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p1, $p2, $r0, $r1, $r2
    ;CHECK-LABEL: name:            add2d_constrained_regClass

    ;CHECK: [[COPY_0:%[0-9]+]]:ep = COPY $p1
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:er = COPY $r0
    ;CHECK-NEXT: [[COPY_2:%[0-9]+]]:er = COPY $r1
    ;CHECK-NEXT: [[COPY_3:%[0-9]+]]:ep = COPY $p2
    ;CHECK-NEXT: [[COPY_4:%[0-9]+]]:er = COPY $r2
    ;CHECK-NEXT: [[COPY_5:%[0-9]+]]:em = COPY [[COPY_1]]
    ;CHECK-NEXT: [[COPY_6:%[0-9]+]]:edj = COPY [[COPY_4]]
    ;CHECK-NEXT: [[COPY_7:%[0-9]+]]:edn = COPY [[COPY_2]]
    ;CHECK-NEXT: [[LDA__8:%[0-9]+]]:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY_3]], 0 :: (load (s32))
    ;CHECK-NEXT: [[COPY_9:%[0-9]+]]:edc = COPY [[LDA__8]]
    ;CHECK-NEXT: [[COPY_1]]4:ed = REG_SEQUENCE [[COPY_5]], %subreg.sub_mod, [[COPY_7]], %subreg.sub_dim_size, [[COPY_6]], %subreg.sub_dim_stride, [[COPY_9]], %subreg.sub_dim_count
    ;CHECK-NEXT: [[PADD_10:%[0-9]+]]:ep, [[COPY_1]]1:edc = PADD_2D_pseudo [[COPY_0]], %14
    ;CHECK-NEXT: [[COPY_1]]2:ep = COPY %11
    ;CHECK-NEXT: [[COPY_1]]3:er = COPY %12
    ;CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY_1]]3, [[COPY_3]], 0 :: (store (s32))
    ;CHECK-NEXT: $p0 = COPY [[PADD_10]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $p0

    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:em(s20) = G_TRUNC %2:gprregbank(s32)
    %7:edj(s20) = G_TRUNC %5:gprregbank(s32)
    %8:edn(s20) = G_TRUNC %3:gprregbank(s32)
    %9:gprregbank(s32) = G_LOAD %4:ptrregbank(p0) :: (load (s32) , align 4)
    %10:edc(s20) = G_TRUNC %9:gprregbank(s32)
    %11:ptrregbank(p0), %12:edc(s20) = G_INTRINSIC intrinsic(@llvm.aie2ps.add.2d), %1:ptrregbank(p0), %6:em(s20), %7:edj(s20), %8:edn(s20), %10:edc(s20)
    %18:ptrregbank(s20) = COPY %12:edc(s20)
    %13:gprregbank(s32) = G_ZEXT %18:ptrregbank(s20)
    G_STORE %13:gprregbank(s32), %4:ptrregbank(p0) :: (store (s32) )
    $p0 = COPY %11:ptrregbank(p0)
    PseudoRET implicit $lr, implicit $p0
...

---
name:            add2d_unconstrained_regClass
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ;CHECK-LABEL: name:            add2d_unconstrained_regClass

    ;CHECK: [[COPY_0:%[0-9]+]]:ep = COPY $p1
    ;CHECK-NEXT: [[MOV__1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ;CHECK-NEXT: [[COPY_5:%[0-9]+]]:edj = COPY [[MOV__1]]
    ;CHECK-NEXT: [[COPY_6:%[0-9]+]]:edn = COPY [[MOV__1]]
    ;CHECK-NEXT: [[COPY_7:%[0-9]+]]:edc = COPY [[MOV__1]]
    ;CHECK-NEXT: [[REG__4:%[0-9]+]]:ed = REG_SEQUENCE [[MOV__1]], %subreg.sub_mod, [[COPY_6]], %subreg.sub_dim_size, [[COPY_5]], %subreg.sub_dim_stride, [[COPY_7]], %subreg.sub_dim_count
    ;CHECK-NEXT: [[PADD_2:%[0-9]+]]:ep, [[PADD_3:%[0-9]+]]:edc = PADD_2D_pseudo [[COPY_0]], [[REG__4]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit [[PADD_2]]

    %1:ptrregbank(p0) = COPY $p1
    %2:modregbank(s20) = G_CONSTANT i20 32
    %3:ptrregbank(p0), %4:modregbank(s20) = G_INTRINSIC intrinsic(@llvm.aie2ps.add.2d), %1:ptrregbank(p0), %2:modregbank(s20), %2:modregbank(s20), %2:modregbank(s20), %2:modregbank(s20)
    PseudoRET implicit $lr, implicit %3
...

---
name:            add3d_byte
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ;CHECK-LABEL: name:            add3d_byte

    ;CHECK: [[COPY_0:%[0-9]+]]:ep = COPY $p1
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:er = COPY $r0
    ;CHECK-NEXT: [[COPY_2:%[0-9]+]]:er = COPY $r1
    ;CHECK-NEXT: [[COPY_3:%[0-9]+]]:ep = COPY $p2
    ;CHECK-NEXT: [[COPY_4:%[0-9]+]]:er = COPY $r2
    ;CHECK-NEXT: [[COPY_5:%[0-9]+]]:er = COPY $r3
    ;CHECK-NEXT: [[COPY_6:%[0-9]+]]:ep = COPY $p3
    ;CHECK-NEXT: [[COPY_7:%[0-9]+]]:er = COPY $r4
    ;CHECK-NEXT: [[COPY_8:%[0-9]+]]:em = COPY [[COPY_1]]
    ;CHECK-NEXT: [[COPY_9:%[0-9]+]]:edj = COPY [[COPY_4]]
    ;CHECK-NEXT: [[COPY_10:%[0-9]+]]:edj = COPY [[COPY_7]]
    ;CHECK-NEXT: [[COPY_1]]1:edn = COPY [[COPY_2]]
    ;CHECK-NEXT: [[COPY_1]]2:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY_3]], 0 :: (load (s32))
    ;CHECK-NEXT: [[COPY_1]]3:edc = COPY %12
    ;CHECK-NEXT: [[COPY_1]]4:edn = COPY [[COPY_5]]
    ;CHECK-NEXT: [[COPY_1]]5:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY_6]], 0 :: (load (s32))
    ;CHECK-NEXT: [[COPY_1]]6:edc = COPY %15
    ;CHECK-NEXT: [[COPY_2]]4:eds = REG_SEQUENCE [[COPY_8]], %subreg.sub_mod, [[COPY_1]]1, %subreg.sub_dim_size, [[COPY_9]], %subreg.sub_dim_stride, %13, %subreg.sub_dim_count, %14, %subreg.sub_hi_dim_then_sub_dim_size, [[COPY_10]], %subreg.sub_hi_dim_then_sub_dim_stride, %16, %subreg.sub_hi_dim_then_sub_dim_count
    ;CHECK-NEXT: [[COPY_1]]7:ep, %18:edcl, %19:edch = PADD_3D_pseudo [[COPY_0]], [[COPY_2]]4
    ;CHECK-NEXT: [[COPY_2]]0:ep = COPY [[COPY_1]]8
    ;CHECK-NEXT: [[COPY_2]]1:er = COPY %20
    ;CHECK-NEXT: [[COPY_2]]2:ep = COPY [[COPY_1]]9
    ;CHECK-NEXT: [[COPY_2]]3:er = COPY %22
    ;CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY_2]]1, [[COPY_3]], 0 :: (store (s32))
    ;CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY_2]]3, [[COPY_6]], 0 :: (store (s32))
    ;CHECK-NEXT: $p0 = COPY [[COPY_1]]7
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $p0

    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:gprregbank(s32) = COPY $r3
    %7:ptrregbank(p0) = COPY $p3
    %8:gprregbank(s32) = COPY $r4
    %9:modregbank(s20) = G_TRUNC %2:gprregbank(s32)
    %10:modregbank(s20) = G_TRUNC %5:gprregbank(s32)
    %11:modregbank(s20) = G_TRUNC %8:gprregbank(s32)
    %12:modregbank(s20) = G_TRUNC %3:gprregbank(s32)
    %13:gprregbank(s32) = G_LOAD %4:ptrregbank(p0) :: (load (s32) , align 4)
    %14:modregbank(s20) = G_TRUNC %13:gprregbank(s32)
    %15:modregbank(s20) = G_TRUNC %6:gprregbank(s32)
    %16:gprregbank(s32) = G_LOAD %7:ptrregbank(p0) :: (load (s32) , align 4)
    %17:modregbank(s20) = G_TRUNC %16:gprregbank(s32)
    %18:ptrregbank(p0), %19:modregbank(s20), %20:modregbank(s20) = G_INTRINSIC intrinsic(@llvm.aie2ps.add.3d), %1:ptrregbank(p0), %9:modregbank(s20), %10:modregbank(s20), %11:modregbank(s20), %12:modregbank(s20), %14:modregbank(s20), %15:modregbank(s20), %17:modregbank(s20)
    %30:ptrregbank(s20) = COPY %19:modregbank(s20)
    %21:gprregbank(s32) = G_ZEXT %30:ptrregbank(s20)
    %31:ptrregbank(s20) = COPY %20:modregbank(s20)
    %22:gprregbank(s32) = G_ZEXT %31:ptrregbank(s20)
    G_STORE %21:gprregbank(s32), %4:ptrregbank(p0) :: (store (s32) )
    G_STORE %22:gprregbank(s32), %7:ptrregbank(p0) :: (store (s32) )
    $p0 = COPY %18:ptrregbank(p0)
    PseudoRET implicit $lr, implicit $p0
...

---
name:            add3d_constrained_regClass
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ;CHECK-LABEL: name:            add3d_constrained_regClass

    ;CHECK: [[COPY_0:%[0-9]+]]:ep = COPY $p1
    ;CHECK-NEXT: [[COPY_1:%[0-9]+]]:er = COPY $r0
    ;CHECK-NEXT: [[COPY_2:%[0-9]+]]:er = COPY $r1
    ;CHECK-NEXT: [[COPY_3:%[0-9]+]]:ep = COPY $p2
    ;CHECK-NEXT: [[COPY_4:%[0-9]+]]:er = COPY $r2
    ;CHECK-NEXT: [[COPY_5:%[0-9]+]]:er = COPY $r3
    ;CHECK-NEXT: [[COPY_6:%[0-9]+]]:ep = COPY $p3
    ;CHECK-NEXT: [[COPY_7:%[0-9]+]]:er = COPY $r4
    ;CHECK-NEXT: [[COPY_8:%[0-9]+]]:em = COPY [[COPY_1]]
    ;CHECK-NEXT: [[COPY_9:%[0-9]+]]:edj = COPY [[COPY_4]]
    ;CHECK-NEXT: [[COPY_10:%[0-9]+]]:edj = COPY [[COPY_7]]
    ;CHECK-NEXT: [[COPY_1]]1:edn = COPY [[COPY_2]]
    ;CHECK-NEXT: [[COPY_1]]2:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY_3]], 0 :: (load (s32))
    ;CHECK-NEXT: [[COPY_1]]3:edc = COPY %12
    ;CHECK-NEXT: [[COPY_1]]4:edn = COPY [[COPY_5]]
    ;CHECK-NEXT: [[COPY_1]]5:er = LDA_dms_lda_scalar_ld_idx_imm [[COPY_6]], 0 :: (load (s32))
    ;CHECK-NEXT: [[COPY_1]]6:edc = COPY %15
    ;CHECK-NEXT: [[COPY_2]]4:eds = REG_SEQUENCE [[COPY_8]], %subreg.sub_mod, [[COPY_1]]1, %subreg.sub_dim_size, [[COPY_9]], %subreg.sub_dim_stride, %13, %subreg.sub_dim_count, %14, %subreg.sub_hi_dim_then_sub_dim_size, [[COPY_10]], %subreg.sub_hi_dim_then_sub_dim_stride, %16, %subreg.sub_hi_dim_then_sub_dim_count
    ;CHECK-NEXT: [[COPY_1]]7:ep, %18:edcl, %19:edch = PADD_3D_pseudo [[COPY_0]], [[COPY_2]]4
    ;CHECK-NEXT: [[COPY_2]]0:ep = COPY [[COPY_1]]8
    ;CHECK-NEXT: [[COPY_2]]1:er = COPY %20
    ;CHECK-NEXT: [[COPY_2]]2:ep = COPY [[COPY_1]]9
    ;CHECK-NEXT: [[COPY_2]]3:er = COPY %22
    ;CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY_2]]1, [[COPY_3]], 0 :: (store (s32))
    ;CHECK-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY_2]]3, [[COPY_6]], 0 :: (store (s32))
    ;CHECK-NEXT: $p0 = COPY [[COPY_1]]7
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $p0

    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %4:ptrregbank(p0) = COPY $p2
    %5:gprregbank(s32) = COPY $r2
    %6:gprregbank(s32) = COPY $r3
    %7:ptrregbank(p0) = COPY $p3
    %8:gprregbank(s32) = COPY $r4
    %9:em(s20) = G_TRUNC %2:gprregbank(s32)
    %10:edj(s20) = G_TRUNC %5:gprregbank(s32)
    %11:edj(s20) = G_TRUNC %8:gprregbank(s32)
    %12:edn(s20) = G_TRUNC %3:gprregbank(s32)
    %13:gprregbank(s32) = G_LOAD %4:ptrregbank(p0) :: (load (s32) , align 4)
    %14:edc(s20) = G_TRUNC %13:gprregbank(s32)
    %15:edn(s20) = G_TRUNC %6:gprregbank(s32)
    %16:gprregbank(s32) = G_LOAD %7:ptrregbank(p0) :: (load (s32) , align 4)
    %17:edc(s20) = G_TRUNC %16:gprregbank(s32)
    %18:ptrregbank(p0), %19:edc(s20), %20:edc(s20) = G_INTRINSIC intrinsic(@llvm.aie2ps.add.3d), %1:ptrregbank(p0), %9:em(s20), %10:edj(s20), %11:edj(s20), %12:edn(s20), %14:edc(s20), %15:edn(s20), %17:edc(s20)
    %30:ptrregbank(s20) = COPY %19:edc(s20)
    %21:gprregbank(s32) = G_ZEXT %30:ptrregbank(s20)
    %31:ptrregbank(s20) = COPY %20:edc(s20)
    %22:gprregbank(s32) = G_ZEXT %31:ptrregbank(s20)
    G_STORE %21:gprregbank(s32), %4:ptrregbank(p0) :: (store (s32) )
    G_STORE %22:gprregbank(s32), %7:ptrregbank(p0) :: (store (s32) )
    $p0 = COPY %18:ptrregbank(p0)
    PseudoRET implicit $lr, implicit $p0
...

---
name:            add3d_unconstrained_regClass
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p1, $p2, $p3, $r0, $r1, $r2, $r3, $r4
    ;CHECK-LABEL: name:            add3d_unconstrained_regClass

    ;CHECK: [[COPY_0:%[0-9]+]]:ep = COPY $p1
    ;CHECK-NEXT: [[MOV__1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
    ;CHECK-NEXT: [[COPY_6:%[0-9]+]]:edj = COPY [[MOV__1]]
    ;CHECK-NEXT: [[COPY_7:%[0-9]+]]:edj = COPY [[MOV__1]]
    ;CHECK-NEXT: [[COPY_8:%[0-9]+]]:edn = COPY [[MOV__1]]
    ;CHECK-NEXT: [[COPY_9:%[0-9]+]]:edc = COPY [[MOV__1]]
    ;CHECK-NEXT: [[COPY_10:%[0-9]+]]:edn = COPY [[MOV__1]]
    ;CHECK-NEXT: [[MOV__1]]1:edc = COPY %1
    ;CHECK-NEXT: [[REG__5:%[0-9]+]]:eds = REG_SEQUENCE [[MOV__1]], %subreg.sub_mod, [[COPY_8]], %subreg.sub_dim_size, [[COPY_6]], %subreg.sub_dim_stride, [[COPY_9]], %subreg.sub_dim_count, [[COPY_10]], %subreg.sub_hi_dim_then_sub_dim_size, [[COPY_7]], %subreg.sub_hi_dim_then_sub_dim_stride, %11, %subreg.sub_hi_dim_then_sub_dim_count
    ;CHECK-NEXT: [[PADD_2:%[0-9]+]]:ep, [[PADD_3:%[0-9]+]]:edcl, [[PADD_4:%[0-9]+]]:edch = PADD_3D_pseudo [[COPY_0]], [[REG__5]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit [[PADD_2]]

    %1:ptrregbank(p0) = COPY $p1
    %2:modregbank(s20) = G_CONSTANT i20 32
    %3:ptrregbank(p0), %4:modregbank(s20), %5:modregbank(s20) = G_INTRINSIC intrinsic(@llvm.aie2ps.add.3d), %1:ptrregbank(p0), %2:modregbank(s20), %2:modregbank(s20), %2:modregbank(s20), %2:modregbank(s20), %2:modregbank(s20), %2:modregbank(s20), %2:modregbank(s20)
    PseudoRET implicit $lr, implicit %3
...
