# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDB_UNPACK_I512_I8_I4_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I512_I16_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I16.I8), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I8_I4_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I8.I4), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_signed
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I512_I16_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I16_I8_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I16.I8), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I8_I4_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I8_I4_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I8.I4), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_unsigned
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_dynamic
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s8>))
    ; CHECK-NEXT: $unpacksign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s8>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_dynamic
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $unpacksign0 = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0 [[COPY]], 0, implicit $crunpacksize, implicit $unpacksign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $unpacksign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_imm_unpackSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = COPY $r0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_offset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_offset
    ; CHECK: liveins: $p0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_:%[0-9]+]]:vec512 = VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_idx_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = COPY $m0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_offset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $m0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_offset
    ; CHECK: liveins: $p0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_:%[0-9]+]]:vec1024 = VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1 [[COPY]], [[COPY1]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_idx_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = COPY $m0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_postinc
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_postinc
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1 [[COPY]], 32, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_UNPACK_dmw_ldb_unpack_pstm_nrm_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 32
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s8>), %9:ptrregbank(p0) = G_AIE_POSTINC_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_postinc
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_postinc
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_1:%[0-9]+]]:ep = VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1 [[COPY]], 64, implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_UNPACK_dmx_ldb_unpack_pstm_nrm_imm_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %8:modregbank(s20) = G_CONSTANT i20 64
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>), %9:ptrregbank(p0) = G_AIE_POSTINC_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_2D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_2D
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1_2:%[0-9]+]]:edc = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edn(s20) = G_CONSTANT i20 3
    %13:edc(s20) = G_CONSTANT i20 4
    %5:vregbank(<32 x s8>), %19:ptrregbank(p0), %20:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13 :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_2D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_2D
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1_2:%[0-9]+]]:edc = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edn(s20) = G_CONSTANT i20 3
    %13:edc(s20) = G_CONSTANT i20 4
    %5:vregbank(<32 x s16>), %19:ptrregbank(p0), %20:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13 :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...

---
name:            VLDB_UNPACK_I512_I8_I4_3D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I512_I8_I4_3D
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_:%[0-9]+]]:vec512, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s8>))
    ; CHECK-NEXT: $x0 = COPY [[VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edj(s20) = G_CONSTANT i20 3
    %13:edn(s20) = G_CONSTANT i20 4
    %14:edn(s20) = G_CONSTANT i20 5
    %15:edc(s20) = G_CONSTANT i20 6
    %16:edc(s20) = G_CONSTANT i20 7
    %5:vregbank(<32 x s8>), %19:ptrregbank(p0), %20:modregbank(s20), %21:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13, %15, %14, %16 :: (load (<32 x s8>))
    %7:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %5:vregbank(<32 x s8>), %6:gprregbank(s32)
    $x0 = COPY %7:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VLDB_UNPACK_I1024_I16_I8_3D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLDB_UNPACK_I1024_I16_I8_3D
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_:%[0-9]+]]:vec1024, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_1:%[0-9]+]]:ep, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_2:%[0-9]+]]:edcl, [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_3:%[0-9]+]]:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 [[COPY]], [[REG_SEQUENCE]], implicit $crunpacksize, implicit $unpacksign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: $y0 = COPY [[VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y0
    %1:ptrregbank(p0) = COPY $p0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edj(s20) = G_CONSTANT i20 3
    %13:edn(s20) = G_CONSTANT i20 4
    %14:edn(s20) = G_CONSTANT i20 5
    %15:edc(s20) = G_CONSTANT i20 6
    %16:edc(s20) = G_CONSTANT i20 7
    %5:vregbank(<32 x s16>), %19:ptrregbank(p0), %20:modregbank(s20), %21:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13, %15, %14, %16 :: (load (<32 x s16>))
    %7:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I1024.I16.I8), %5:vregbank(<32 x s16>), %6:gprregbank(s32)
    $y0 = COPY %7:vregbank(<32 x s32>)
    PseudoRET implicit $lr, implicit $y0
...
