# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck -check-prefix=AIE2PS %s


...
---
name: store_s64
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $p0
    ;AIE2PS-LABEL: name:            store_s64

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[COPY_1:%[0-9]+]]:el = COPY $l6
    ;AIE2PS-NEXT: ST_dml_sts_scalar_st_idx_imm [[COPY_1]], [[COPY_0]], 0 :: (store (s64))
    ;AIE2PS-NEXT: PseudoRET implicit $lr

    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s64) = COPY $l6
    G_STORE %1, %0 :: (store (s64))
    PseudoRET implicit $lr

...
---
name: pre-inc-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0, $r1
    ;AIE2PS-LABEL: name:            pre-inc-store

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[COPY_1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo -256
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 248
    ;AIE2PS-NEXT: [[MOV__4:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 256
    ;AIE2PS-NEXT: [[MOV__5:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 10
    ;AIE2PS-NEXT: [[MOV__6:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 16
    ;AIE2PS-NEXT: [[COPY_7:%[0-9]+]]:el = COPY $l0
    ;AIE2PS-NEXT: ST_dml_sts_scalar_st_idx [[COPY_7]], [[COPY_0]], [[MOV__2]] :: (store (s64))
    ;AIE2PS-NEXT: ST_dml_sts_scalar_st_idx [[COPY_7]], [[COPY_0]], [[MOV__3]] :: (store (s64))
    ;AIE2PS-NEXT: ST_dml_sts_scalar_st_idx [[COPY_7]], [[COPY_0]], [[MOV__4]] :: (store (s64))
    ;AIE2PS-NEXT: [[COPY_8:%[0-9]+]]:edj = COPY [[COPY_7]]
    ;AIE2PS-NEXT: ST_dml_sts_scalar_st_idx [[COPY_7]], [[COPY_0]], [[COPY_8]] :: (store (s64))
    ;AIE2PS-NEXT: ST_dml_sts_scalar_st_idx [[COPY_7]], [[COPY_0]], [[MOV__5]] :: (store (s64))
    ;AIE2PS-NEXT: ST_dml_sts_scalar_st_idx [[COPY_7]], [[COPY_0]], [[MOV__6]] :: (store (s64))
    ;AIE2PS-NEXT: ST_dms_sts_scalar_st_idx_imm [[COPY_1]], [[COPY_0]], 16 :: (store (p0), align 4)
    ;AIE2PS-NEXT: PseudoRET implicit $lr

    %0:ptrregbank(p0) = COPY $p0
    %8:ptrregbank(p0) = COPY $p1
    %1:modregbank(s20) = G_CONSTANT i20 -256
    %2:modregbank(s20) = G_CONSTANT i20 248
    %3:modregbank(s20) = G_CONSTANT i20 256
    %5:modregbank(s20) = G_CONSTANT i20 10
    %6:modregbank(s20) = G_CONSTANT i20 16
    %4:gprregbank(s64) = COPY $l0
    G_AIE_OFFSET_STORE %4, %0, %1 :: (store (s64))
    G_AIE_OFFSET_STORE %4, %0, %2 :: (store (s64))
    G_AIE_OFFSET_STORE %4, %0, %3 :: (store (s64))
    G_AIE_OFFSET_STORE %4, %0, %4 :: (store (s64))
    G_AIE_OFFSET_STORE %4, %0, %5 :: (store (s64))
    G_AIE_OFFSET_STORE %4, %0, %6 :: (store (s64))
    G_AIE_OFFSET_STORE %8, %0, %6 :: (store (p0))
    PseudoRET implicit $lr

...
---
name: post-inc-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0, $r1
    ;AIE2PS-LABEL: name:            post-inc-store

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[COPY_1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:em = MOV_PD_imm11_pseudo -256
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:em = MOV_PD_imm11_pseudo 248
    ;AIE2PS-NEXT: [[MOV__4:%[0-9]+]]:em = MOV_PD_imm11_pseudo 256
    ;AIE2PS-NEXT: [[MOV__5:%[0-9]+]]:em = MOV_PD_imm11_pseudo 10
    ;AIE2PS-NEXT: [[MOV__6:%[0-9]+]]:em = MOV_PD_imm11_pseudo 16
    ;AIE2PS-NEXT: [[COPY_7:%[0-9]+]]:el = COPY $l0
    ;AIE2PS-NEXT: [[ST_d_8:%[0-9]+]]:ep = ST_dml_sts_scalar_st_pstm_nrm [[COPY_7]], [[COPY_0]], [[MOV__2]] :: (store (s64))
    ;AIE2PS-NEXT: [[ST_d_9:%[0-9]+]]:ep = ST_dml_sts_scalar_st_pstm_nrm [[COPY_7]], [[COPY_0]], [[MOV__3]] :: (store (s64))
    ;AIE2PS-NEXT: [[ST_d_10:%[0-9]+]]:ep = ST_dml_sts_scalar_st_pstm_nrm [[COPY_7]], [[COPY_0]], [[MOV__4]] :: (store (s64))
    ;AIE2PS-NEXT: [[COPY_1]]5:em = COPY [[COPY_7]]
    ;AIE2PS-NEXT: [[COPY_1]]1:ep = ST_dml_sts_scalar_st_pstm_nrm [[COPY_7]], [[COPY_0]], %15 :: (store (s64))
    ;AIE2PS-NEXT: [[COPY_1]]2:ep = ST_dml_sts_scalar_st_pstm_nrm [[COPY_7]], [[COPY_0]], [[MOV__5]] :: (store (s64))
    ;AIE2PS-NEXT: [[COPY_1]]3:ep = ST_dml_sts_scalar_st_pstm_nrm [[COPY_7]], [[COPY_0]], [[MOV__6]] :: (store (s64))
    ;AIE2PS-NEXT: [[COPY_1]]4:ep = ST_dms_sts_scalar_st_pstm_nrm_imm %1, [[COPY_0]], 16 :: (store (p0), align 4)
    ;AIE2PS-NEXT: PseudoRET implicit $lr

    %0:ptrregbank(p0) = COPY $p0
    %8:ptrregbank(p0) = COPY $p1
    %1:modregbank(s20) = G_CONSTANT i20 -256
    %2:modregbank(s20) = G_CONSTANT i20 248
    %3:modregbank(s20) = G_CONSTANT i20 256
    %5:modregbank(s20) = G_CONSTANT i20 10
    %6:modregbank(s20) = G_CONSTANT i20 16
    %4:gprregbank(s64) = COPY $l0
    %80:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %1 :: (store (s64))
    %81:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %2 :: (store (s64))
    %82:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %3 :: (store (s64))
    %83:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %4 :: (store (s64))
    %84:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %5 :: (store (s64))
    %85:ptrregbank(p0) = G_AIE_POSTINC_STORE %4, %0, %6 :: (store (s64))
    %86:ptrregbank(p0) = G_AIE_POSTINC_STORE %8, %0, %6 :: (store (p0))
    PseudoRET implicit $lr

...
---
name: post-inc-2d-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $m0, $p1, $dc0, $dj0, $dn0
    ;AIE2PS-LABEL: name:            post-inc-2d-store

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[MOV__1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ;AIE2PS-NEXT: [[MOV__4:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ;AIE2PS-NEXT: [[COPY_5:%[0-9]+]]:el = COPY $l0
    ;AIE2PS-NEXT: [[REG__8:%[0-9]+]]:ed = REG_SEQUENCE [[MOV__1]], %subreg.sub_mod, [[MOV__3]], %subreg.sub_dim_size, [[MOV__2]], %subreg.sub_dim_stride, [[MOV__4]], %subreg.sub_dim_count
    ;AIE2PS-NEXT: [[ST_2_6:%[0-9]+]]:ep, [[ST_2_7:%[0-9]+]]:edc = ST_2D_dml_sts_scalar [[COPY_5]], [[COPY_0]], [[REG__8]] :: (store (s64))
    ;AIE2PS-NEXT: PseudoRET implicit $lr


    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edn(s20) = G_CONSTANT i20 3
    %4:edc(s20) = G_CONSTANT i20 4
    %5:gprregbank(s64) = COPY $l0
    %6:ptrregbank(p0), %7:modregbank(s20) = G_AIE_POSTINC_2D_STORE %5, %0, %1, %2, %3, %4 :: (store (s64))
    PseudoRET implicit $lr

...
---
name: post-inc-3d-store
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $l0, $m0, $p1, $dc0, $dj0, $dn0
    ;AIE2PS-LABEL: name:            post-inc-3d-store

    ;AIE2PS: [[COPY_0:%[0-9]+]]:ep = COPY $p0
    ;AIE2PS-NEXT: [[MOV__1:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ;AIE2PS-NEXT: [[MOV__2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ;AIE2PS-NEXT: [[MOV__3:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ;AIE2PS-NEXT: [[MOV__4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ;AIE2PS-NEXT: [[MOV__5:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ;AIE2PS-NEXT: [[MOV__6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ;AIE2PS-NEXT: [[MOV__7:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ;AIE2PS-NEXT: [[COPY_8:%[0-9]+]]:el = COPY $l0
    ;AIE2PS-NEXT: [[MOV__1]]2:eds = REG_SEQUENCE %1, %subreg.sub_mod, [[MOV__4]], %subreg.sub_dim_size, [[MOV__2]], %subreg.sub_dim_stride, [[MOV__6]], %subreg.sub_dim_count, [[MOV__5]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV__3]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV__7]], %subreg.sub_hi_dim_then_sub_dim_count
    ;AIE2PS-NEXT: [[ST_3_9:%[0-9]+]]:ep, [[ST_3_10:%[0-9]+]]:edcl, [[MOV__1]]1:edch = ST_3D_dml_sts_scalar [[COPY_8]], [[COPY_0]], %12 :: (store (s64))
    ;AIE2PS-NEXT: PseudoRET implicit $lr

    %0:ptrregbank(p0) = COPY $p0
    %1:em(s20) = G_CONSTANT i20 1
    %2:edj(s20) = G_CONSTANT i20 2
    %3:edj(s20) = G_CONSTANT i20 3
    %4:edn(s20) = G_CONSTANT i20 4
    %5:edn(s20) = G_CONSTANT i20 5
    %6:edc(s20) = G_CONSTANT i20 6
    %7:edc(s20) = G_CONSTANT i20 7
    %8:gprregbank(s64) = COPY $l0
    %9:ptrregbank(p0), %10:modregbank(s20), %11:modregbank(s20) = G_AIE_POSTINC_3D_STORE %8, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (s64))
    PseudoRET implicit $lr
...
