# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

# Note: BFP640/BFP768 intrinsics and BFP384/BFP640/BFP768 push operations were not included
# because they are not yet implemented in the aie2ps instruction selector.
# These intrinsics are recognized in RegisterBankInfo but lack instruction selection patterns.

---
name:            ld_fill
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: ld_fill
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_FILL_512_pseudo:%[0-9]+]]:eps, [[VLD_FILL_512_pseudo1:%[0-9]+]]:eldfiforeg, [[VLD_FILL_512_pseudo2:%[0-9]+]]:mrf2a = VLD_FILL_512_pseudo [[DEF]], [[DEF1]], [[DEF2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_FILL_512_pseudo]], implicit [[VLD_FILL_512_pseudo1]], implicit [[VLD_FILL_512_pseudo2]]
    %4:ptrregbank(p0) = G_IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = G_IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9
...

---
name:            ld_fillx
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: ld_fillx
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:fifo512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:mr30_fifo_step_e1 = IMPLICIT_DEF
    ; CHECK-NEXT: $lfe = COPY [[DEF3]]
    ; CHECK-NEXT: [[VLDB_FILLX:%[0-9]+]]:eps, [[VLDB_FILLX1:%[0-9]+]]:eldfiforeg, [[VLDB_FILLX2:%[0-9]+]]:mrf2a = VLDB_FILLX [[DEF4]], [[DEF4]], [[DEF]], [[DEF1]], [[DEF2]], implicit-def $lfe, implicit $lfe
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mfifoextra = COPY $lfe
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_FILLX]], implicit [[VLDB_FILLX1]], implicit [[VLDB_FILLX2]], implicit [[COPY]]
    %4:ptrregbank(p0) = G_IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = G_IMPLICIT_DEF
    %10:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %11:gprregbank(s32) = G_IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32), %12:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fillx), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32), %10:fiforegbank(<16 x s32>), %11:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9, implicit %12
...

---
name:            ld_popx
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: ld_popx
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:fifo512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:mr30_fifo_step_e1 = IMPLICIT_DEF
    ; CHECK-NEXT: $lfe = COPY [[DEF3]]
    ; CHECK-NEXT: [[VLDB_POPX:%[0-9]+]]:vec512, [[VLDB_POPX1:%[0-9]+]]:eps, [[VLDB_POPX2:%[0-9]+]]:eldfiforeg, [[VLDB_POPX3:%[0-9]+]]:mrf2a = VLDB_POPX [[DEF4]], [[DEF4]], [[DEF]], [[DEF1]], [[DEF2]], implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mfifoextra = COPY $lfe
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDB_POPX]], implicit [[VLDB_POPX1]], implicit [[VLDB_POPX2]], implicit [[VLDB_POPX3]], implicit [[COPY]]
    %5:ptrregbank(p0) = G_IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %7:gprregbank(s32) = G_IMPLICIT_DEF
    %12:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    %13:gprregbank(s32) = G_IMPLICIT_DEF
    %8:vregbank(<64 x s8>), %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32), %14:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.popx), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %12:fiforegbank(<16 x s32>), %13:gprregbank(s32)
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11, implicit %14
...

---
name:            pop_unaligned
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_512_normal_pop_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_normal_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_normal_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_normal_pop_pseudo3:%[0-9]+]]:mrf2a = VLD_POP_512_normal_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_normal_pop_pseudo]], implicit [[VLD_POP_512_normal_pop_pseudo1]], implicit [[VLD_POP_512_normal_pop_pseudo2]], implicit [[VLD_POP_512_normal_pop_pseudo3]]
    %5:ptrregbank(p0) = G_IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %7:gprregbank(s32) = G_IMPLICIT_DEF
    %8:vregbank(<64 x s8>), %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.512.unaligned), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32)
    PseudoRET implicit $lr, implicit %8, implicit %9, implicit %10, implicit %11
...

---
name:            pop_unaligned_1d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned_1d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VLD_POP_512_fifo_1d_pop_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_fifo_1d_pop_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_fifo_1d_pop_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_fifo_1d_pop_pseudo3:%[0-9]+]]:mrf2a = VLD_POP_512_fifo_1d_pop_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[DEF3]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_fifo_1d_pop_pseudo]], implicit [[VLD_POP_512_fifo_1d_pop_pseudo1]], implicit [[VLD_POP_512_fifo_1d_pop_pseudo2]], implicit [[VLD_POP_512_fifo_1d_pop_pseudo3]]
    %6:ptrregbank(p0) = G_IMPLICIT_DEF
    %7:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %8:gprregbank(s32) = G_IMPLICIT_DEF
    %9:modregbank(s20) = G_IMPLICIT_DEF
    %10:vregbank(<64 x s8>), %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.unaligned), %6:ptrregbank(p0), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32), %9:modregbank(s20)
    PseudoRET implicit $lr, implicit %10, implicit %11, implicit %12, implicit %13
...

---
name:            pop_unaligned_2d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned_2d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_512_2D_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_2D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_2D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_2D_pseudo3:%[0-9]+]]:mrf2a, [[VLD_POP_512_2D_pseudo4:%[0-9]+]]:edc = VLD_POP_512_2D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_2D_pseudo]], implicit [[VLD_POP_512_2D_pseudo1]], implicit [[VLD_POP_512_2D_pseudo2]], implicit [[VLD_POP_512_2D_pseudo3]], implicit [[VLD_POP_512_2D_pseudo4]]
    %9:ptrregbank(p0) = G_IMPLICIT_DEF
    %10:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %11:gprregbank(s32) = G_IMPLICIT_DEF
    %12:modregbank(s20) = G_IMPLICIT_DEF
    %13:modregbank(s20) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %17:vregbank(<64 x s8>), %18:ptrregbank(p0), %19:fiforegbank(<32 x s32>), %20:gprregbank(s32), %21:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.unaligned), %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32), %12:modregbank(s20), %13:modregbank(s20), %15:modregbank(s20), %16:modregbank(s20)
    PseudoRET implicit $lr, implicit %17, implicit %18, implicit %19, implicit %20, implicit %21
...

---
name:            pop_unaligned_3d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: pop_unaligned_3d
    ; CHECK: [[DEF:%[0-9]+]]:eps = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:eldfiforeg = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mrf2a = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VLD_POP_512_3D_pseudo:%[0-9]+]]:vec512, [[VLD_POP_512_3D_pseudo1:%[0-9]+]]:eps, [[VLD_POP_512_3D_pseudo2:%[0-9]+]]:eldfiforeg, [[VLD_POP_512_3D_pseudo3:%[0-9]+]]:mrf2a, [[VLD_POP_512_3D_pseudo4:%[0-9]+]]:edcl, [[VLD_POP_512_3D_pseudo5:%[0-9]+]]:edch = VLD_POP_512_3D_pseudo [[DEF]], [[DEF1]], [[DEF2]], [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLD_POP_512_3D_pseudo]], implicit [[VLD_POP_512_3D_pseudo1]], implicit [[VLD_POP_512_3D_pseudo2]], implicit [[VLD_POP_512_3D_pseudo3]], implicit [[VLD_POP_512_3D_pseudo4]], implicit [[VLD_POP_512_3D_pseudo5]]
    %12:ptrregbank(p0) = G_IMPLICIT_DEF
    %13:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %14:gprregbank(s32) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %16:modregbank(s20) = G_IMPLICIT_DEF
    %18:modregbank(s20) = G_IMPLICIT_DEF
    %19:modregbank(s20) = G_IMPLICIT_DEF
    %20:modregbank(s20) = G_IMPLICIT_DEF
    %22:modregbank(s20) = G_IMPLICIT_DEF
    %23:modregbank(s20) = G_IMPLICIT_DEF
    %24:vregbank(<64 x s8>), %25:ptrregbank(p0), %26:fiforegbank(<32 x s32>), %27:gprregbank(s32), %28:modregbank(s20), %29:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.unaligned), %12:ptrregbank(p0), %13:fiforegbank(<32 x s32>), %14:gprregbank(s32), %15:modregbank(s20), %16:modregbank(s20), %18:modregbank(s20), %19:modregbank(s20), %20:modregbank(s20), %22:modregbank(s20), %23:modregbank(s20)
    PseudoRET implicit $lr, implicit %24, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29
...

---
name:            st_push_512
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_push_512
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_512_dmx_sts_fifo_bare_x:%[0-9]+]]:mstfifo, [[VST_PUSH_512_dmx_sts_fifo_bare_x1:%[0-9]+]]:mpfs, [[VST_PUSH_512_dmx_sts_fifo_bare_x2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_512_dmx_sts_fifo_bare_x [[DEF2]], [[DEF1]], [[DEF]], [[DEF3]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_PUSH_512_dmx_sts_fifo_bare_x1]], implicit [[VST_PUSH_512_dmx_sts_fifo_bare_x]], implicit [[VST_PUSH_512_dmx_sts_fifo_bare_x2]]
    %6:ptrregbank(p0) = G_IMPLICIT_DEF
    %1:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    %7:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %8:gprregbank(s32) = G_IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.512), %6:ptrregbank(p0), %1:vregbank(<16 x s32>), %7:fiforegbank(<32 x s32>), %8:gprregbank(s32)
    PseudoRET implicit $lr, implicit %9, implicit %10, implicit %11
...

---
name:            st_flush
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_normal_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_normal_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_normal_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_normal_flush [[DEF1]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_normal_flush1]], implicit [[VST_FLUSH_normal_flush]], implicit [[VST_FLUSH_normal_flush2]]
    %4:ptrregbank(p0) = G_IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = G_IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9
...

---
name:            st_flush_conv
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush_conv
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_d_normal_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_normal_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_normal_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_d_normal_flush [[DEF1]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_d_normal_flush1]], implicit [[VST_FLUSH_d_normal_flush]], implicit [[VST_FLUSH_d_normal_flush2]]
    %4:ptrregbank(p0) = G_IMPLICIT_DEF
    %5:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %6:gprregbank(s32) = G_IMPLICIT_DEF
    %7:ptrregbank(p0), %8:fiforegbank(<32 x s32>), %9:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.conv), %4:ptrregbank(p0), %5:fiforegbank(<32 x s32>), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7, implicit %8, implicit %9
...

---
name:            st_flush_1d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush_1d
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_fifo_1d_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_fifo_1d_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_fifo_1d_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_fifo_1d_flush [[DEF1]], [[DEF]], [[DEF2]], [[DEF3]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_fifo_1d_flush1]], implicit [[VST_FLUSH_fifo_1d_flush]], implicit [[VST_FLUSH_fifo_1d_flush2]]
    %5:ptrregbank(p0) = G_IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %7:gprregbank(s32) = G_IMPLICIT_DEF
    %8:modregbank(s20) = G_IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20)
    PseudoRET implicit $lr, implicit %9, implicit %10, implicit %11
...

---
name:            st_flush_1d_conv
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush_1d_conv
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_d_fifo_1d_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_fifo_1d_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_fifo_1d_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_d_fifo_1d_flush [[DEF1]], [[DEF]], [[DEF2]], [[DEF3]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_d_fifo_1d_flush1]], implicit [[VST_FLUSH_d_fifo_1d_flush]], implicit [[VST_FLUSH_d_fifo_1d_flush2]]
    %5:ptrregbank(p0) = G_IMPLICIT_DEF
    %6:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %7:gprregbank(s32) = G_IMPLICIT_DEF
    %8:modregbank(s20) = G_IMPLICIT_DEF
    %9:ptrregbank(p0), %10:fiforegbank(<32 x s32>), %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d.conv), %5:ptrregbank(p0), %6:fiforegbank(<32 x s32>), %7:gprregbank(s32), %8:modregbank(s20)
    PseudoRET implicit $lr, implicit %9, implicit %10, implicit %11
...

---
name:            st_flush_2d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush_2d
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_2D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_2D3:%[0-9]+]]:edc = VST_FLUSH_2D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_2D1]], implicit [[VST_FLUSH_2D]], implicit [[VST_FLUSH_2D2]], implicit [[VST_FLUSH_2D3]]
    %8:ptrregbank(p0) = G_IMPLICIT_DEF
    %9:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %10:gprregbank(s32) = G_IMPLICIT_DEF
    %11:modregbank(s20) = G_IMPLICIT_DEF
    %12:modregbank(s20) = G_IMPLICIT_DEF
    %14:modregbank(s20) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %16:ptrregbank(p0), %17:fiforegbank(<32 x s32>), %18:gprregbank(s32), %19:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d), %8:ptrregbank(p0), %9:fiforegbank(<32 x s32>), %10:gprregbank(s32), %11:modregbank(s20), %12:modregbank(s20), %14:modregbank(s20), %15:modregbank(s20)
    PseudoRET implicit $lr, implicit %16, implicit %17, implicit %18, implicit %19
...

---
name:            st_flush_2d_conv
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush_2d_conv
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_d_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_2D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_d_2D3:%[0-9]+]]:edc = VST_FLUSH_d_2D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_d_2D1]], implicit [[VST_FLUSH_d_2D]], implicit [[VST_FLUSH_d_2D2]], implicit [[VST_FLUSH_d_2D3]]
    %8:ptrregbank(p0) = G_IMPLICIT_DEF
    %9:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %10:gprregbank(s32) = G_IMPLICIT_DEF
    %11:modregbank(s20) = G_IMPLICIT_DEF
    %12:modregbank(s20) = G_IMPLICIT_DEF
    %14:modregbank(s20) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %16:ptrregbank(p0), %17:fiforegbank(<32 x s32>), %18:gprregbank(s32), %19:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d.conv), %8:ptrregbank(p0), %9:fiforegbank(<32 x s32>), %10:gprregbank(s32), %11:modregbank(s20), %12:modregbank(s20), %14:modregbank(s20), %15:modregbank(s20)
    PseudoRET implicit $lr, implicit %16, implicit %17, implicit %18, implicit %19
...

---
name:            st_flush_3d
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush_3d
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_3D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_3D3:%[0-9]+]]:edcl, [[VST_FLUSH_3D4:%[0-9]+]]:edch = VST_FLUSH_3D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_3D1]], implicit [[VST_FLUSH_3D]], implicit [[VST_FLUSH_3D2]], implicit [[VST_FLUSH_3D3]], implicit [[VST_FLUSH_3D4]]
    %11:ptrregbank(p0) = G_IMPLICIT_DEF
    %12:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %13:gprregbank(s32) = G_IMPLICIT_DEF
    %14:modregbank(s20) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %17:modregbank(s20) = G_IMPLICIT_DEF
    %18:modregbank(s20) = G_IMPLICIT_DEF
    %19:modregbank(s20) = G_IMPLICIT_DEF
    %21:modregbank(s20) = G_IMPLICIT_DEF
    %22:modregbank(s20) = G_IMPLICIT_DEF
    %23:ptrregbank(p0), %24:fiforegbank(<32 x s32>), %25:gprregbank(s32), %26:modregbank(s20), %27:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d), %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32), %14:modregbank(s20), %15:modregbank(s20), %17:modregbank(s20), %18:modregbank(s20), %19:modregbank(s20), %21:modregbank(s20), %22:modregbank(s20)
    PseudoRET implicit $lr, implicit %23, implicit %24, implicit %25, implicit %26, implicit %27
...

---
name:            st_flush_3d_conv
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins:
    ; CHECK-LABEL: name: st_flush_3d_conv
    ; CHECK: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:edn = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:edc = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:edj = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[DEF3]], %subreg.sub_mod, [[DEF4]], %subreg.sub_dim_size, [[DEF6]], %subreg.sub_dim_stride, [[DEF5]], %subreg.sub_dim_count, [[DEF7]], %subreg.sub_hi_dim_then_sub_dim_size, [[DEF9]], %subreg.sub_hi_dim_then_sub_dim_stride, [[DEF8]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: [[VST_FLUSH_d_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_3D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_d_3D3:%[0-9]+]]:edcl, [[VST_FLUSH_d_3D4:%[0-9]+]]:edch = VST_FLUSH_d_3D [[DEF1]], [[DEF]], [[DEF2]], [[REG_SEQUENCE]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VST_FLUSH_d_3D1]], implicit [[VST_FLUSH_d_3D]], implicit [[VST_FLUSH_d_3D2]], implicit [[VST_FLUSH_d_3D3]], implicit [[VST_FLUSH_d_3D4]]
    %11:ptrregbank(p0) = G_IMPLICIT_DEF
    %12:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    %13:gprregbank(s32) = G_IMPLICIT_DEF
    %14:modregbank(s20) = G_IMPLICIT_DEF
    %15:modregbank(s20) = G_IMPLICIT_DEF
    %17:modregbank(s20) = G_IMPLICIT_DEF
    %18:modregbank(s20) = G_IMPLICIT_DEF
    %19:modregbank(s20) = G_IMPLICIT_DEF
    %21:modregbank(s20) = G_IMPLICIT_DEF
    %22:modregbank(s20) = G_IMPLICIT_DEF
    %23:ptrregbank(p0), %24:fiforegbank(<32 x s32>), %25:gprregbank(s32), %26:modregbank(s20), %27:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d.conv), %11:ptrregbank(p0), %12:fiforegbank(<32 x s32>), %13:gprregbank(s32), %14:modregbank(s20), %15:modregbank(s20), %17:modregbank(s20), %18:modregbank(s20), %19:modregbank(s20), %21:modregbank(s20), %22:modregbank(s20)
    PseudoRET implicit $lr, implicit %23, implicit %24, implicit %25, implicit %26, implicit %27
...
