# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

# Tests for combining VMAC + VADD -> VADDMAC patterns

---
name:            test_vaddmac_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_X_X
    ; CHECK: liveins: $x0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mrv8 = COPY $r0
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.mac.conf), %0(<32 x s16>), %1(<32 x s16>), %2(<64 x s32>), %4(s32)
    %8:accregbank(<32 x s64>) = G_BITCAST %6(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.add.conf), %8(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_Y_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_Y_Y
    ; CHECK: liveins: $y0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mrv8 = COPY $r0
    ; CHECK-NEXT: [[VADDMAC_vaddmac_vmul_cm_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_vaddmac_vmul_cm_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_vaddmac_vmul_cm_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<64 x s16>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.mac.conf), %0(<64 x s16>), %1(<64 x s16>), %2(<64 x s32>), %4(s32)
    %8:accregbank(<32 x s64>) = G_BITCAST %6(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.add.conf), %8(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_X_X
    ; CHECK: liveins: $x0, $x2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mrv8 = COPY $r0
    ; CHECK-NEXT: [[VADDMSC_vaddmac_vmul_cm_core_X_X:%[0-9]+]]:acc2048 = VADDMSC_vaddmac_vmul_cm_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[COPY4]]
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_vaddmac_vmul_cm_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<32 x s64>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.msc.conf), %0(<32 x s16>), %1(<32 x s16>), %2(<64 x s32>), %4(s32)
    %8:accregbank(<32 x s64>) = G_BITCAST %6(<64 x s32>)
    %7:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.add.conf), %8(<32 x s64>), %3(<32 x s64>), %5(s32)
    $dm0 = COPY %7(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_bf16_Y_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmac_bf16_Y_Y
    ; CHECK: liveins: $y0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mrv8 = COPY $r0
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<64 x s16>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.mac.conf), %0(<64 x s16>), %1(<64 x s16>), %2(<64 x s32>), %4(s32)
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.add.conf), %6(<64 x s32>), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmsc_bf16_Y_Y
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $y2, $dm0, $dm1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_bf16_Y_Y
    ; CHECK: liveins: $y0, $y2, $dm0, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mrv8 = COPY $r0
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bf_vmul_bf_core_Y_Y]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:vregbank(<64 x s16>) = COPY $y0
    %1:vregbank(<64 x s16>) = COPY $y2
    %2:accregbank(<64 x s32>) = COPY $dm0
    %3:accregbank(<64 x s32>) = COPY $dm1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.msc.conf), %0(<64 x s16>), %1(<64 x s16>), %2(<64 x s32>), %4(s32)
    %7:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.add.conf), %6(<64 x s32>), %3(<64 x s32>), %5(s32)
    $dm0 = COPY %7(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name:            test_vaddmac_bf16_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $cml0, $cml1, $r0

    ; CHECK-LABEL: name: test_vaddmac_bf16_X_X
    ; CHECK: liveins: $x0, $x2, $cml0, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mrv8 = COPY $r0
    ; CHECK-NEXT: [[VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMAC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMAC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<32 x s32>) = COPY $cml0
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf), %0(<32 x s16>), %1(<32 x s16>), %2(<32 x s32>), %4(s32)
    %7:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.add.conf), %6(<32 x s32>), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %7(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name:            test_vaddmsc_bf16_X_X
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2, $cml0, $cml1, $r0

    ; CHECK-LABEL: name: test_vaddmsc_bf16_X_X
    ; CHECK: liveins: $x0, $x2, $cml0, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ecml = COPY $cml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mrv8 = COPY $r0
    ; CHECK-NEXT: [[VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VMSC_f_vmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X:%[0-9]+]]:ecml = VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X [[COPY2]], [[COPY3]], [[COPY]], [[COPY1]], [[COPY4]], implicit-def dead $srfpflags, implicit $crbf8conf, implicit $crfp8conf, implicit $crfpmask
    ; CHECK-NEXT: $cml0 = COPY [[VADDMSC_f_vaddmac_bf_half_vmul_bf_half_core_X_X]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:accregbank(<32 x s32>) = COPY $cml0
    %3:accregbank(<32 x s32>) = COPY $cml1
    %4:gprregbank(s32) = COPY $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %6:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.msc.conf), %0(<32 x s16>), %1(<32 x s16>), %2(<32 x s32>), %4(s32)
    %7:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC1024.accfloat.add.conf), %6(<32 x s32>), %3(<32 x s32>), %5(s32)
    $cml0 = COPY %7(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...
