# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

...
---
name:            _Z9test_exp2Dv16_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0
    ;CHECK-LABEL: name:            _Z9test_exp2Dv16_u10__accfloat
  
    ;CHECK: [[COPY_0:%[0-9]+]]:acc512 = COPY $bmll0
    ;CHECK-NEXT: [[VEXP_1:%[0-9]+]]:vec256 = VEXP2_bf16 [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VEXP_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0

  
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %0:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.exp2), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
---
name:            _Z14test_exp2_bf20Dv16_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll1
    ;CHECK-LABEL: name:            _Z14test_exp2_bf20Dv16_u10__accfloat
  
    ;CHECK: [[COPY_0:%[0-9]+]]:acc512 = COPY $bmll1
    ;CHECK-NEXT: [[VEXP_1:%[0-9]+]]:acc512 = VEXP2_fp32 [[COPY_0]]
    ;CHECK-NEXT: $bmll0 = COPY [[VEXP_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0

  
    %1:accregbank(<16 x s32>) = COPY $bmll1
    %0:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.exp2.bf20), %1(<16 x s32>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z9test_tanhDv16_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0
    ;CHECK-LABEL: name:            _Z9test_tanhDv16_u10__accfloat
  
    ;CHECK: [[COPY_0:%[0-9]+]]:acc512 = COPY $bmll0
    ;CHECK-NEXT: [[VTAN_1:%[0-9]+]]:vec256 = VTANH [[COPY_0]]
    ;CHECK-NEXT: $wl0 = COPY [[VTAN_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0

  
    %1:accregbank(<16 x s32>) = COPY $bmll0
    %0:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.tanh), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0

...
