# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


# This tests that we don't combine if one of the load's defs (data) is used after the VUNPACK instruction (no single use)

---
name:            VLD_UNPACK_use_after
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLD_UNPACK_use_after
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_pseudo:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_pseudo1:%[0-9]+]]:ep = VLD_w_pstm_nrm_pseudo [[COPY]], [[COPY2]] :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign1_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign1 [[VLD_w_pstm_nrm_pseudo]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VUNPACK_mv_unpack_w_unpackSign1_]], implicit [[VLD_w_pstm_nrm_pseudo]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    %12:vregbank(<32 x s8>) = COPY %25
    PseudoRET implicit $lr, implicit %103, implicit %12
...

# This tests that we don't combine if one of the load's defs (data) is used before the VUNPACK instruction (no single use)

---
name:            VLD_UNPACK_use_between
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLD_UNPACK_use_between
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_pseudo:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_pseudo1:%[0-9]+]]:ep = VLD_w_pstm_nrm_pseudo [[COPY]], [[COPY2]] :: (load (<32 x s8>))
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign1_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign1 [[VLD_w_pstm_nrm_pseudo]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VUNPACK_mv_unpack_w_unpackSign1_]], implicit [[VLD_w_pstm_nrm_pseudo]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %12:vregbank(<32 x s8>) = COPY %25
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %12
...

---
name:            VLD_UNPACK_side_effects_between
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: VLD_UNPACK_side_effects_between
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLD_w_pstm_nrm_pseudo:%[0-9]+]]:vec256, [[VLD_w_pstm_nrm_pseudo1:%[0-9]+]]:ep = VLD_w_pstm_nrm_pseudo [[COPY]], [[COPY2]] :: (load (<32 x s8>))
    ; CHECK-NEXT: $vaddsign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $crunpacksize = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[VUNPACK_mv_unpack_w_unpackSign1_:%[0-9]+]]:vec512 = VUNPACK_mv_unpack_w_unpackSign1 [[VLD_w_pstm_nrm_pseudo]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VUNPACK_mv_unpack_w_unpackSign1_]]
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r0
    %7:modregbank(s20) = G_TRUNC %1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %25:vregbank(<32 x s8>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<32 x s8>))
    %110:gprregbank(s32) = G_CONSTANT i32 11
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.set.ctrl.reg), %110:gprregbank(s32), %1:gprregbank(s32)
    %103:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.unpack.I512.I8.I4), %25:vregbank(<32 x s8>), %102:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103
...
