# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test__sqrtf
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1
    ;CHECK-LABEL: name:            test__sqrtf
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r1
    ;CHECK-NEXT: [[SQRT_1:%[0-9]+]]:mlockid_reg = SQRT_nlf_sqrt [[COPY_0]], implicit-def dead $srfpnlf, implicit $crfpnlfmask
    ;CHECK-NEXT: $r0 = COPY [[SQRT_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $r0


    %1:gprregbank(s32) = COPY $r1
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2ps.sqrtf), %1(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_invf
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1
    ;CHECK-LABEL: name:            test_invf
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r1
    ;CHECK-NEXT: [[INV__1:%[0-9]+]]:mlockid_reg = INV_nlf_inv [[COPY_0]], implicit-def dead $srfpnlf, implicit $crfpnlfmask
    ;CHECK-NEXT: $r0 = COPY [[INV__1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $r0


    %1:gprregbank(s32) = COPY $r1
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2ps.inv), %1(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_invsqrtf
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1
    ;CHECK-LABEL: name:            test_invsqrtf
  
    ;CHECK: [[COPY_0:%[0-9]+]]:mlockid_reg = COPY $r1
    ;CHECK-NEXT: [[INVS_1:%[0-9]+]]:mlockid_reg = INVSQRT_nlf_invsqrt [[COPY_0]], implicit-def dead $srfpnlf, implicit $crfpnlfmask
    ;CHECK-NEXT: $r0 = COPY [[INVS_1]]
    ;CHECK-NEXT: PseudoRET implicit $lr, implicit $r0


    %1:gprregbank(s32) = COPY $r1
    %0:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2ps.invsqrt), %1(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
