# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            _Z20test_mul_4x16_16x16T6v64mx97v256mx9
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7

    ; CHECK-LABEL: name: _Z20test_mul_4x16_16x16T6v64mx97v256mx9
    ; CHECK: liveins: $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mggs = COPY $g0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mees = COPY $e0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY $x5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY $x6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY $x7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mggs = COPY $g4
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mggs = COPY $g5
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mggs = COPY $g6
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mggs = COPY $g7
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mees = COPY $e4
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mees = COPY $e5
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mees = COPY $e6
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mees = COPY $e7
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:mgs = COPY [[COPY1]].sub_lo_exp
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mes = COPY [[COPY2]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY15]], %subreg.sub_bfp_v256, killed [[COPY16]], %subreg.sub_bfp_g32, killed [[COPY17]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_lo
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mgs = COPY [[COPY7]].sub_lo_exp
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mes = COPY [[COPY11]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY18]], %subreg.sub_bfp_v256, killed [[COPY19]], %subreg.sub_bfp_g32, killed [[COPY20]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_hi
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mgs = COPY [[COPY7]].sub_hi_exp
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mes = COPY [[COPY11]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY21]], %subreg.sub_bfp_v256, killed [[COPY22]], %subreg.sub_bfp_g32, killed [[COPY23]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE1]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE2]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_lo
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:mgs = COPY [[COPY8]].sub_lo_exp
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mes = COPY [[COPY12]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY24]], %subreg.sub_bfp_v256, killed [[COPY25]], %subreg.sub_bfp_g32, killed [[COPY26]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_hi
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:mgs = COPY [[COPY8]].sub_hi_exp
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:mes = COPY [[COPY12]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY27]], %subreg.sub_bfp_v256, killed [[COPY28]], %subreg.sub_bfp_g32, killed [[COPY29]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE4]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE6]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_lo
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:mgs = COPY [[COPY9]].sub_lo_exp
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:mes = COPY [[COPY13]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY30]], %subreg.sub_bfp_v256, killed [[COPY31]], %subreg.sub_bfp_g32, killed [[COPY32]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_hi
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:mgs = COPY [[COPY9]].sub_hi_exp
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:mes = COPY [[COPY13]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY33]], %subreg.sub_bfp_v256, killed [[COPY34]], %subreg.sub_bfp_g32, killed [[COPY35]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE8]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE9]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_lo
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:mgs = COPY [[COPY10]].sub_lo_exp
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:mes = COPY [[COPY14]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY36]], %subreg.sub_bfp_v256, killed [[COPY37]], %subreg.sub_bfp_g32, killed [[COPY38]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_hi
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:mgs = COPY [[COPY10]].sub_hi_exp
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:mes = COPY [[COPY14]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE12:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY39]], %subreg.sub_bfp_v256, killed [[COPY40]], %subreg.sub_bfp_g32, killed [[COPY41]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE13:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE11]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE12]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE14:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE10]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE13]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:mgs = COPY [[COPY1]].sub_hi_exp
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:mes = COPY [[COPY2]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE15:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY42]], %subreg.sub_bfp_v256, killed [[COPY43]], %subreg.sub_bfp_g32, killed [[COPY44]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[VMUL_f_vmul_bfp16_:%[0-9]+]]:acc2048 = VMUL_f_vmul_bfp16 [[REG_SEQUENCE]], [[REG_SEQUENCE7]], [[REG_SEQUENCE14]], [[REG_SEQUENCE15]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bfp16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(<2 x s32>) = COPY $g0
    %3:gprregbank(<2 x s32>) = COPY $e0
    %4:vregbank(<16 x s32>) = COPY $x4
    %5:vregbank(<16 x s32>) = COPY $x5
    %6:vregbank(<16 x s32>) = COPY $x6
    %7:vregbank(<16 x s32>) = COPY $x7
    %8:gprregbank(<2 x s32>) = COPY $g4
    %9:gprregbank(<2 x s32>) = COPY $g5
    %10:gprregbank(<2 x s32>) = COPY $g6
    %11:gprregbank(<2 x s32>) = COPY $g7
    %12:gprregbank(<2 x s32>) = COPY $e4
    %13:gprregbank(<2 x s32>) = COPY $e5
    %14:gprregbank(<2 x s32>) = COPY $e6
    %15:gprregbank(<2 x s32>) = COPY $e7
    %16:gprregbank(s32) = G_CONSTANT i32 780
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mul.conf), %1(<16 x s32>), %2(<2 x s32>), %3(<2 x s32>), %4(<16 x s32>), %5(<16 x s32>), %6(<16 x s32>), %7(<16 x s32>), %8(<2 x s32>), %9(<2 x s32>), %10(<2 x s32>), %11(<2 x s32>), %12(<2 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z23test_negmul_4x16_16x16T6v64mx97v256mx9
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7

    ; CHECK-LABEL: name: _Z23test_negmul_4x16_16x16T6v64mx97v256mx9
    ; CHECK: liveins: $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mggs = COPY $g0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mees = COPY $e0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY $x5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY $x6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY $x7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mggs = COPY $g4
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mggs = COPY $g5
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mggs = COPY $g6
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mggs = COPY $g7
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mees = COPY $e4
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mees = COPY $e5
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mees = COPY $e6
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mees = COPY $e7
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:mgs = COPY [[COPY1]].sub_lo_exp
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mes = COPY [[COPY2]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY15]], %subreg.sub_bfp_v256, killed [[COPY16]], %subreg.sub_bfp_g32, killed [[COPY17]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_lo
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mgs = COPY [[COPY7]].sub_lo_exp
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mes = COPY [[COPY11]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY18]], %subreg.sub_bfp_v256, killed [[COPY19]], %subreg.sub_bfp_g32, killed [[COPY20]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_hi
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mgs = COPY [[COPY7]].sub_hi_exp
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mes = COPY [[COPY11]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY21]], %subreg.sub_bfp_v256, killed [[COPY22]], %subreg.sub_bfp_g32, killed [[COPY23]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE1]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE2]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_lo
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:mgs = COPY [[COPY8]].sub_lo_exp
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mes = COPY [[COPY12]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY24]], %subreg.sub_bfp_v256, killed [[COPY25]], %subreg.sub_bfp_g32, killed [[COPY26]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_hi
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:mgs = COPY [[COPY8]].sub_hi_exp
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:mes = COPY [[COPY12]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY27]], %subreg.sub_bfp_v256, killed [[COPY28]], %subreg.sub_bfp_g32, killed [[COPY29]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE4]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE6]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_lo
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:mgs = COPY [[COPY9]].sub_lo_exp
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:mes = COPY [[COPY13]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY30]], %subreg.sub_bfp_v256, killed [[COPY31]], %subreg.sub_bfp_g32, killed [[COPY32]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_hi
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:mgs = COPY [[COPY9]].sub_hi_exp
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:mes = COPY [[COPY13]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY33]], %subreg.sub_bfp_v256, killed [[COPY34]], %subreg.sub_bfp_g32, killed [[COPY35]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE8]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE9]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_lo
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:mgs = COPY [[COPY10]].sub_lo_exp
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:mes = COPY [[COPY14]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY36]], %subreg.sub_bfp_v256, killed [[COPY37]], %subreg.sub_bfp_g32, killed [[COPY38]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_hi
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:mgs = COPY [[COPY10]].sub_hi_exp
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:mes = COPY [[COPY14]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE12:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY39]], %subreg.sub_bfp_v256, killed [[COPY40]], %subreg.sub_bfp_g32, killed [[COPY41]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE13:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE11]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE12]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE14:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE10]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE13]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:mgs = COPY [[COPY1]].sub_hi_exp
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:mes = COPY [[COPY2]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE15:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY42]], %subreg.sub_bfp_v256, killed [[COPY43]], %subreg.sub_bfp_g32, killed [[COPY44]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bfp16_:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bfp16 [[REG_SEQUENCE]], [[REG_SEQUENCE7]], [[REG_SEQUENCE14]], [[REG_SEQUENCE15]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bfp16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(<2 x s32>) = COPY $g0
    %3:gprregbank(<2 x s32>) = COPY $e0
    %4:vregbank(<16 x s32>) = COPY $x4
    %5:vregbank(<16 x s32>) = COPY $x5
    %6:vregbank(<16 x s32>) = COPY $x6
    %7:vregbank(<16 x s32>) = COPY $x7
    %8:gprregbank(<2 x s32>) = COPY $g4
    %9:gprregbank(<2 x s32>) = COPY $g5
    %10:gprregbank(<2 x s32>) = COPY $g6
    %11:gprregbank(<2 x s32>) = COPY $g7
    %12:gprregbank(<2 x s32>) = COPY $e4
    %13:gprregbank(<2 x s32>) = COPY $e5
    %14:gprregbank(<2 x s32>) = COPY $e6
    %15:gprregbank(<2 x s32>) = COPY $e7
    %16:gprregbank(s32) = G_CONSTANT i32 780
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.negmul.conf), %1(<16 x s32>), %2(<2 x s32>), %3(<2 x s32>), %4(<16 x s32>), %5(<16 x s32>), %6(<16 x s32>), %7(<16 x s32>), %8(<2 x s32>), %9(<2 x s32>), %10(<2 x s32>), %11(<2 x s32>), %12(<2 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_mac_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7

    ; CHECK-LABEL: name: _Z20test_mac_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mggs = COPY $g0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mees = COPY $e0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY $x5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY $x6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY $x7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mggs = COPY $g4
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mggs = COPY $g5
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mggs = COPY $g6
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mggs = COPY $g7
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mees = COPY $e4
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mees = COPY $e5
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mees = COPY $e6
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mees = COPY $e7
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mgs = COPY [[COPY1]].sub_lo_exp
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mes = COPY [[COPY2]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY16]], %subreg.sub_bfp_v256, killed [[COPY17]], %subreg.sub_bfp_g32, killed [[COPY18]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_lo
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mgs = COPY [[COPY7]].sub_lo_exp
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:mes = COPY [[COPY11]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY19]], %subreg.sub_bfp_v256, killed [[COPY20]], %subreg.sub_bfp_g32, killed [[COPY21]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_hi
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mgs = COPY [[COPY7]].sub_hi_exp
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mes = COPY [[COPY11]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY22]], %subreg.sub_bfp_v256, killed [[COPY23]], %subreg.sub_bfp_g32, killed [[COPY24]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE1]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE2]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_lo
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mgs = COPY [[COPY8]].sub_lo_exp
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mes = COPY [[COPY12]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY25]], %subreg.sub_bfp_v256, killed [[COPY26]], %subreg.sub_bfp_g32, killed [[COPY27]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_hi
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:mgs = COPY [[COPY8]].sub_hi_exp
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:mes = COPY [[COPY12]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY28]], %subreg.sub_bfp_v256, killed [[COPY29]], %subreg.sub_bfp_g32, killed [[COPY30]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE4]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE6]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_lo
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:mgs = COPY [[COPY9]].sub_lo_exp
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:mes = COPY [[COPY13]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY31]], %subreg.sub_bfp_v256, killed [[COPY32]], %subreg.sub_bfp_g32, killed [[COPY33]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_hi
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:mgs = COPY [[COPY9]].sub_hi_exp
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:mes = COPY [[COPY13]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY34]], %subreg.sub_bfp_v256, killed [[COPY35]], %subreg.sub_bfp_g32, killed [[COPY36]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE8]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE9]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_lo
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:mgs = COPY [[COPY10]].sub_lo_exp
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:mes = COPY [[COPY14]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY37]], %subreg.sub_bfp_v256, killed [[COPY38]], %subreg.sub_bfp_g32, killed [[COPY39]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_hi
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:mgs = COPY [[COPY10]].sub_hi_exp
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:mes = COPY [[COPY14]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE12:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY40]], %subreg.sub_bfp_v256, killed [[COPY41]], %subreg.sub_bfp_g32, killed [[COPY42]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE13:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE11]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE12]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE14:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE10]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE13]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:mgs = COPY [[COPY1]].sub_hi_exp
    ; CHECK-NEXT: [[COPY45:%[0-9]+]]:mes = COPY [[COPY2]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE15:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY43]], %subreg.sub_bfp_v256, killed [[COPY44]], %subreg.sub_bfp_g32, killed [[COPY45]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[VMAC_f_vmac_bfp16_:%[0-9]+]]:acc2048 = VMAC_f_vmac_bfp16 [[COPY15]], [[REG_SEQUENCE]], [[REG_SEQUENCE7]], [[REG_SEQUENCE14]], [[REG_SEQUENCE15]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bfp16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(<2 x s32>) = COPY $g0
    %3:gprregbank(<2 x s32>) = COPY $e0
    %4:vregbank(<16 x s32>) = COPY $x4
    %5:vregbank(<16 x s32>) = COPY $x5
    %6:vregbank(<16 x s32>) = COPY $x6
    %7:vregbank(<16 x s32>) = COPY $x7
    %8:gprregbank(<2 x s32>) = COPY $g4
    %9:gprregbank(<2 x s32>) = COPY $g5
    %10:gprregbank(<2 x s32>) = COPY $g6
    %11:gprregbank(<2 x s32>) = COPY $g7
    %12:gprregbank(<2 x s32>) = COPY $e4
    %13:gprregbank(<2 x s32>) = COPY $e5
    %14:gprregbank(<2 x s32>) = COPY $e6
    %15:gprregbank(<2 x s32>) = COPY $e7
    %16:accregbank(<64 x s32>) = COPY $dm1
    %17:gprregbank(s32) = G_CONSTANT i32 780
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.mac.conf), %1(<16 x s32>), %2(<2 x s32>), %3(<2 x s32>), %4(<16 x s32>), %5(<16 x s32>), %6(<16 x s32>), %7(<16 x s32>), %8(<2 x s32>), %9(<2 x s32>), %10(<2 x s32>), %11(<2 x s32>), %12(<2 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<64 x s32>), %17(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_msc_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7

    ; CHECK-LABEL: name: _Z20test_msc_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mggs = COPY $g0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mees = COPY $e0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY $x5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY $x6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY $x7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mggs = COPY $g4
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mggs = COPY $g5
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mggs = COPY $g6
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mggs = COPY $g7
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mees = COPY $e4
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mees = COPY $e5
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mees = COPY $e6
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mees = COPY $e7
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:mgs = COPY [[COPY1]].sub_lo_exp
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mes = COPY [[COPY2]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY16]], %subreg.sub_bfp_v256, killed [[COPY17]], %subreg.sub_bfp_g32, killed [[COPY18]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_lo
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mgs = COPY [[COPY7]].sub_lo_exp
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:mes = COPY [[COPY11]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY19]], %subreg.sub_bfp_v256, killed [[COPY20]], %subreg.sub_bfp_g32, killed [[COPY21]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_hi
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mgs = COPY [[COPY7]].sub_hi_exp
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mes = COPY [[COPY11]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY22]], %subreg.sub_bfp_v256, killed [[COPY23]], %subreg.sub_bfp_g32, killed [[COPY24]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE1]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE2]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_lo
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mgs = COPY [[COPY8]].sub_lo_exp
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mes = COPY [[COPY12]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY25]], %subreg.sub_bfp_v256, killed [[COPY26]], %subreg.sub_bfp_g32, killed [[COPY27]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_hi
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:mgs = COPY [[COPY8]].sub_hi_exp
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:mes = COPY [[COPY12]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY28]], %subreg.sub_bfp_v256, killed [[COPY29]], %subreg.sub_bfp_g32, killed [[COPY30]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE4]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE6]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_lo
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:mgs = COPY [[COPY9]].sub_lo_exp
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:mes = COPY [[COPY13]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY31]], %subreg.sub_bfp_v256, killed [[COPY32]], %subreg.sub_bfp_g32, killed [[COPY33]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_hi
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:mgs = COPY [[COPY9]].sub_hi_exp
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:mes = COPY [[COPY13]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY34]], %subreg.sub_bfp_v256, killed [[COPY35]], %subreg.sub_bfp_g32, killed [[COPY36]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE8]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE9]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_lo
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:mgs = COPY [[COPY10]].sub_lo_exp
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:mes = COPY [[COPY14]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY37]], %subreg.sub_bfp_v256, killed [[COPY38]], %subreg.sub_bfp_g32, killed [[COPY39]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_hi
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:mgs = COPY [[COPY10]].sub_hi_exp
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:mes = COPY [[COPY14]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE12:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY40]], %subreg.sub_bfp_v256, killed [[COPY41]], %subreg.sub_bfp_g32, killed [[COPY42]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE13:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE11]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE12]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE14:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE10]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE13]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:mgs = COPY [[COPY1]].sub_hi_exp
    ; CHECK-NEXT: [[COPY45:%[0-9]+]]:mes = COPY [[COPY2]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE15:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY43]], %subreg.sub_bfp_v256, killed [[COPY44]], %subreg.sub_bfp_g32, killed [[COPY45]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[VMSC_f_vmac_bfp16_:%[0-9]+]]:acc2048 = VMSC_f_vmac_bfp16 [[COPY15]], [[REG_SEQUENCE]], [[REG_SEQUENCE7]], [[REG_SEQUENCE14]], [[REG_SEQUENCE15]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bfp16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(<2 x s32>) = COPY $g0
    %3:gprregbank(<2 x s32>) = COPY $e0
    %4:vregbank(<16 x s32>) = COPY $x4
    %5:vregbank(<16 x s32>) = COPY $x5
    %6:vregbank(<16 x s32>) = COPY $x6
    %7:vregbank(<16 x s32>) = COPY $x7
    %8:gprregbank(<2 x s32>) = COPY $g4
    %9:gprregbank(<2 x s32>) = COPY $g5
    %10:gprregbank(<2 x s32>) = COPY $g6
    %11:gprregbank(<2 x s32>) = COPY $g7
    %12:gprregbank(<2 x s32>) = COPY $e4
    %13:gprregbank(<2 x s32>) = COPY $e5
    %14:gprregbank(<2 x s32>) = COPY $e6
    %15:gprregbank(<2 x s32>) = COPY $e7
    %16:accregbank(<64 x s32>) = COPY $dm1
    %17:gprregbank(s32) = G_CONSTANT i32 780
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.msc.conf), %1(<16 x s32>), %2(<2 x s32>), %3(<2 x s32>), %4(<16 x s32>), %5(<16 x s32>), %6(<16 x s32>), %7(<16 x s32>), %8(<2 x s32>), %9(<2 x s32>), %10(<2 x s32>), %11(<2 x s32>), %12(<2 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<64 x s32>), %17(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z23test_addmac_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7

    ; CHECK-LABEL: name: _Z23test_addmac_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mggs = COPY $g0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mees = COPY $e0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY $x5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY $x6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY $x7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mggs = COPY $g4
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mggs = COPY $g5
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mggs = COPY $g6
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mggs = COPY $g7
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mees = COPY $e4
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mees = COPY $e5
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mees = COPY $e6
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mees = COPY $e7
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mgs = COPY [[COPY1]].sub_lo_exp
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mes = COPY [[COPY2]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY17]], %subreg.sub_bfp_v256, killed [[COPY18]], %subreg.sub_bfp_g32, killed [[COPY19]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_lo
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:mgs = COPY [[COPY7]].sub_lo_exp
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mes = COPY [[COPY11]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY20]], %subreg.sub_bfp_v256, killed [[COPY21]], %subreg.sub_bfp_g32, killed [[COPY22]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_hi
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mgs = COPY [[COPY7]].sub_hi_exp
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:mes = COPY [[COPY11]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY23]], %subreg.sub_bfp_v256, killed [[COPY24]], %subreg.sub_bfp_g32, killed [[COPY25]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE1]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE2]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_lo
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mgs = COPY [[COPY8]].sub_lo_exp
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:mes = COPY [[COPY12]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY26]], %subreg.sub_bfp_v256, killed [[COPY27]], %subreg.sub_bfp_g32, killed [[COPY28]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_hi
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:mgs = COPY [[COPY8]].sub_hi_exp
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:mes = COPY [[COPY12]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY29]], %subreg.sub_bfp_v256, killed [[COPY30]], %subreg.sub_bfp_g32, killed [[COPY31]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE4]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE6]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_lo
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:mgs = COPY [[COPY9]].sub_lo_exp
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:mes = COPY [[COPY13]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY32]], %subreg.sub_bfp_v256, killed [[COPY33]], %subreg.sub_bfp_g32, killed [[COPY34]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_hi
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:mgs = COPY [[COPY9]].sub_hi_exp
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:mes = COPY [[COPY13]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY35]], %subreg.sub_bfp_v256, killed [[COPY36]], %subreg.sub_bfp_g32, killed [[COPY37]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE8]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE9]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_lo
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:mgs = COPY [[COPY10]].sub_lo_exp
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:mes = COPY [[COPY14]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY38]], %subreg.sub_bfp_v256, killed [[COPY39]], %subreg.sub_bfp_g32, killed [[COPY40]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_hi
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:mgs = COPY [[COPY10]].sub_hi_exp
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:mes = COPY [[COPY14]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE12:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY41]], %subreg.sub_bfp_v256, killed [[COPY42]], %subreg.sub_bfp_g32, killed [[COPY43]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE13:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE11]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE12]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE14:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE10]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE13]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY45:%[0-9]+]]:mgs = COPY [[COPY1]].sub_hi_exp
    ; CHECK-NEXT: [[COPY46:%[0-9]+]]:mes = COPY [[COPY2]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE15:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY44]], %subreg.sub_bfp_v256, killed [[COPY45]], %subreg.sub_bfp_g32, killed [[COPY46]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bfp16_:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bfp16 [[COPY15]], [[COPY16]], [[REG_SEQUENCE]], [[REG_SEQUENCE7]], [[REG_SEQUENCE14]], [[REG_SEQUENCE15]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bfp16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(<2 x s32>) = COPY $g0
    %3:gprregbank(<2 x s32>) = COPY $e0
    %4:vregbank(<16 x s32>) = COPY $x4
    %5:vregbank(<16 x s32>) = COPY $x5
    %6:vregbank(<16 x s32>) = COPY $x6
    %7:vregbank(<16 x s32>) = COPY $x7
    %8:gprregbank(<2 x s32>) = COPY $g4
    %9:gprregbank(<2 x s32>) = COPY $g5
    %10:gprregbank(<2 x s32>) = COPY $g6
    %11:gprregbank(<2 x s32>) = COPY $g7
    %12:gprregbank(<2 x s32>) = COPY $e4
    %13:gprregbank(<2 x s32>) = COPY $e5
    %14:gprregbank(<2 x s32>) = COPY $e6
    %15:gprregbank(<2 x s32>) = COPY $e7
    %16:accregbank(<64 x s32>) = COPY $dm1
    %17:accregbank(<64 x s32>) = COPY $dm2
    %18:gprregbank(s32) = G_CONSTANT i32 780
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.addmac.conf), %1(<16 x s32>), %2(<2 x s32>), %3(<2 x s32>), %4(<16 x s32>), %5(<16 x s32>), %6(<16 x s32>), %7(<16 x s32>), %8(<2 x s32>), %9(<2 x s32>), %10(<2 x s32>), %11(<2 x s32>), %12(<2 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<64 x s32>), %17(<64 x s32>), %18(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z23test_addmsc_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7

    ; CHECK-LABEL: name: _Z23test_addmsc_4x16_16x16T6v64mx97v256mx9Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $e0, $e4, $e5, $e6, $e7, $g0, $g4, $g5, $g6, $g7, $x0, $x4, $x5, $x6, $x7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mggs = COPY $g0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:mees = COPY $e0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vec512 = COPY $x5
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:vec512 = COPY $x6
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:vec512 = COPY $x7
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mggs = COPY $g4
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mggs = COPY $g5
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mggs = COPY $g6
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mggs = COPY $g7
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mees = COPY $e4
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mees = COPY $e5
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:mees = COPY $e6
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mees = COPY $e7
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 780
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mgs = COPY [[COPY1]].sub_lo_exp
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mes = COPY [[COPY2]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY17]], %subreg.sub_bfp_v256, killed [[COPY18]], %subreg.sub_bfp_g32, killed [[COPY19]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_lo
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:mgs = COPY [[COPY7]].sub_lo_exp
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mes = COPY [[COPY11]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY20]], %subreg.sub_bfp_v256, killed [[COPY21]], %subreg.sub_bfp_g32, killed [[COPY22]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:vec256 = COPY [[COPY3]].sub_256_hi
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mgs = COPY [[COPY7]].sub_hi_exp
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:mes = COPY [[COPY11]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY23]], %subreg.sub_bfp_v256, killed [[COPY24]], %subreg.sub_bfp_g32, killed [[COPY25]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE1]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE2]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_lo
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mgs = COPY [[COPY8]].sub_lo_exp
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:mes = COPY [[COPY12]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY26]], %subreg.sub_bfp_v256, killed [[COPY27]], %subreg.sub_bfp_g32, killed [[COPY28]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY29:%[0-9]+]]:vec256 = COPY [[COPY4]].sub_256_hi
    ; CHECK-NEXT: [[COPY30:%[0-9]+]]:mgs = COPY [[COPY8]].sub_hi_exp
    ; CHECK-NEXT: [[COPY31:%[0-9]+]]:mes = COPY [[COPY12]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY29]], %subreg.sub_bfp_v256, killed [[COPY30]], %subreg.sub_bfp_g32, killed [[COPY31]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE4]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE5]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE6]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY32:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_lo
    ; CHECK-NEXT: [[COPY33:%[0-9]+]]:mgs = COPY [[COPY9]].sub_lo_exp
    ; CHECK-NEXT: [[COPY34:%[0-9]+]]:mes = COPY [[COPY13]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY32]], %subreg.sub_bfp_v256, killed [[COPY33]], %subreg.sub_bfp_g32, killed [[COPY34]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY35:%[0-9]+]]:vec256 = COPY [[COPY5]].sub_256_hi
    ; CHECK-NEXT: [[COPY36:%[0-9]+]]:mgs = COPY [[COPY9]].sub_hi_exp
    ; CHECK-NEXT: [[COPY37:%[0-9]+]]:mes = COPY [[COPY13]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY35]], %subreg.sub_bfp_v256, killed [[COPY36]], %subreg.sub_bfp_g32, killed [[COPY37]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE8]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE9]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[COPY38:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_lo
    ; CHECK-NEXT: [[COPY39:%[0-9]+]]:mgs = COPY [[COPY10]].sub_lo_exp
    ; CHECK-NEXT: [[COPY40:%[0-9]+]]:mes = COPY [[COPY14]].sub_lo_exp
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:mewlv_bis = REG_SEQUENCE killed [[COPY38]], %subreg.sub_bfp_v256, killed [[COPY39]], %subreg.sub_bfp_g32, killed [[COPY40]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[COPY41:%[0-9]+]]:vec256 = COPY [[COPY6]].sub_256_hi
    ; CHECK-NEXT: [[COPY42:%[0-9]+]]:mgs = COPY [[COPY10]].sub_hi_exp
    ; CHECK-NEXT: [[COPY43:%[0-9]+]]:mes = COPY [[COPY14]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE12:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY41]], %subreg.sub_bfp_v256, killed [[COPY42]], %subreg.sub_bfp_g32, killed [[COPY43]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE13:%[0-9]+]]:mexs = REG_SEQUENCE [[REG_SEQUENCE11]], %subreg.sub_bfp320_lo, [[REG_SEQUENCE12]], %subreg.sub_bfp320_hi
    ; CHECK-NEXT: [[REG_SEQUENCE14:%[0-9]+]]:eeys = REG_SEQUENCE [[REG_SEQUENCE10]], %subreg.sub_bfp640_lo, [[REG_SEQUENCE13]], %subreg.sub_bfp640_hi
    ; CHECK-NEXT: [[COPY44:%[0-9]+]]:vec256 = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY45:%[0-9]+]]:mgs = COPY [[COPY1]].sub_hi_exp
    ; CHECK-NEXT: [[COPY46:%[0-9]+]]:mes = COPY [[COPY2]].sub_hi_exp
    ; CHECK-NEXT: [[REG_SEQUENCE15:%[0-9]+]]:mewhv = REG_SEQUENCE killed [[COPY44]], %subreg.sub_bfp_v256, killed [[COPY45]], %subreg.sub_bfp_g32, killed [[COPY46]], %subreg.sub_bfp_e32
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bfp16_:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bfp16 [[COPY15]], [[COPY16]], [[REG_SEQUENCE]], [[REG_SEQUENCE7]], [[REG_SEQUENCE14]], [[REG_SEQUENCE15]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bfp16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(<2 x s32>) = COPY $g0
    %3:gprregbank(<2 x s32>) = COPY $e0
    %4:vregbank(<16 x s32>) = COPY $x4
    %5:vregbank(<16 x s32>) = COPY $x5
    %6:vregbank(<16 x s32>) = COPY $x6
    %7:vregbank(<16 x s32>) = COPY $x7
    %8:gprregbank(<2 x s32>) = COPY $g4
    %9:gprregbank(<2 x s32>) = COPY $g5
    %10:gprregbank(<2 x s32>) = COPY $g6
    %11:gprregbank(<2 x s32>) = COPY $g7
    %12:gprregbank(<2 x s32>) = COPY $e4
    %13:gprregbank(<2 x s32>) = COPY $e5
    %14:gprregbank(<2 x s32>) = COPY $e6
    %15:gprregbank(<2 x s32>) = COPY $e7
    %16:accregbank(<64 x s32>) = COPY $dm1
    %17:accregbank(<64 x s32>) = COPY $dm2
    %18:gprregbank(s32) = G_CONSTANT i32 780
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP640.BFP2560.ACC2048.bf.addmsc.conf), %1(<16 x s32>), %2(<2 x s32>), %3(<2 x s32>), %4(<16 x s32>), %5(<16 x s32>), %6(<16 x s32>), %7(<16 x s32>), %8(<2 x s32>), %9(<2 x s32>), %10(<2 x s32>), %11(<2 x s32>), %12(<2 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<64 x s32>), %17(<64 x s32>), %18(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_mul_4x16_16x16T7v128mx67v256mx6
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3

    ; CHECK-LABEL: name: _Z20test_mul_4x16_16x16T7v128mx67v256mx6
    ; CHECK: liveins: $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $fl0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fh0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $gl0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gh0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $el0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $eh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY $wh2
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY $wl3
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY $wh3
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:el = COPY $fl2
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:el = COPY $fh2
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:el = COPY $fl3
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:el = COPY $fh3
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:er = COPY $gl2
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:er = COPY $gh2
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:er = COPY $gl3
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:er = COPY $gh3
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:er = COPY $el2
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:er = COPY $eh2
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:er = COPY $el3
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:er = COPY $eh3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 804
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY]], %subreg.sub_few_bfp_w, [[COPY2]], %subreg.sub_few_bfp_f64, [[COPY4]], %subreg.sub_few_bfp_g32, [[COPY6]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY8]], %subreg.sub_few_bfp_w, [[COPY12]], %subreg.sub_few_bfp_f64, [[COPY16]], %subreg.sub_few_bfp_g32, [[COPY20]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY9]], %subreg.sub_few_bfp_w, [[COPY13]], %subreg.sub_few_bfp_f64, [[COPY17]], %subreg.sub_few_bfp_g32, [[COPY21]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY10]], %subreg.sub_few_bfp_w, [[COPY14]], %subreg.sub_few_bfp_f64, [[COPY18]], %subreg.sub_few_bfp_g32, [[COPY22]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY11]], %subreg.sub_few_bfp_w, [[COPY15]], %subreg.sub_few_bfp_f64, [[COPY19]], %subreg.sub_few_bfp_g32, [[COPY23]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE6]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE7]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:efey = REG_SEQUENCE [[REG_SEQUENCE5]], %subreg.sub_bfp768_lo, [[REG_SEQUENCE8]], %subreg.sub_bfp768_hi
    ; CHECK-NEXT: [[VMUL_f_vmul_bfp13_:%[0-9]+]]:acc2048 = VMUL_f_vmul_bfp13 [[REG_SEQUENCE2]], [[REG_SEQUENCE9]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMUL_f_vmul_bfp13_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<8 x s32>) = COPY $wh0
    %3:gprregbank(<2 x s32>) = COPY $fl0
    %4:gprregbank(<2 x s32>) = COPY $fh0
    %5:gprregbank(s32) = COPY $gl0
    %6:gprregbank(s32) = COPY $gh0
    %7:gprregbank(s32) = COPY $el0
    %8:gprregbank(s32) = COPY $eh0
    %9:vregbank(<8 x s32>) = COPY $wl2
    %10:vregbank(<8 x s32>) = COPY $wh2
    %11:vregbank(<8 x s32>) = COPY $wl3
    %12:vregbank(<8 x s32>) = COPY $wh3
    %13:gprregbank(<2 x s32>) = COPY $fl2
    %14:gprregbank(<2 x s32>) = COPY $fh2
    %15:gprregbank(<2 x s32>) = COPY $fl3
    %16:gprregbank(<2 x s32>) = COPY $fh3
    %17:gprregbank(s32) = COPY $gl2
    %18:gprregbank(s32) = COPY $gh2
    %19:gprregbank(s32) = COPY $gl3
    %20:gprregbank(s32) = COPY $gh3
    %21:gprregbank(s32) = COPY $el2
    %22:gprregbank(s32) = COPY $eh2
    %23:gprregbank(s32) = COPY $el3
    %24:gprregbank(s32) = COPY $eh3
    %25:gprregbank(s32) = G_CONSTANT i32 804
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.mul.conf), %1(<8 x s32>), %2(<8 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(s32), %6(s32), %7(s32), %8(s32), %9(<8 x s32>), %10(<8 x s32>), %11(<8 x s32>), %12(<8 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<2 x s32>), %17(s32), %18(s32), %19(s32), %20(s32), %21(s32), %22(s32), %23(s32), %24(s32), %25(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z23test_negmul_4x16_16x16T7v128mx67v256mx6
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3

    ; CHECK-LABEL: name: _Z23test_negmul_4x16_16x16T7v128mx67v256mx6
    ; CHECK: liveins: $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $fl0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fh0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $gl0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gh0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $el0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $eh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY $wh2
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY $wl3
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY $wh3
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:el = COPY $fl2
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:el = COPY $fh2
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:el = COPY $fl3
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:el = COPY $fh3
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:er = COPY $gl2
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:er = COPY $gh2
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:er = COPY $gl3
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:er = COPY $gh3
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:er = COPY $el2
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:er = COPY $eh2
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:er = COPY $el3
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:er = COPY $eh3
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 804
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY]], %subreg.sub_few_bfp_w, [[COPY2]], %subreg.sub_few_bfp_f64, [[COPY4]], %subreg.sub_few_bfp_g32, [[COPY6]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY8]], %subreg.sub_few_bfp_w, [[COPY12]], %subreg.sub_few_bfp_f64, [[COPY16]], %subreg.sub_few_bfp_g32, [[COPY20]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY9]], %subreg.sub_few_bfp_w, [[COPY13]], %subreg.sub_few_bfp_f64, [[COPY17]], %subreg.sub_few_bfp_g32, [[COPY21]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY10]], %subreg.sub_few_bfp_w, [[COPY14]], %subreg.sub_few_bfp_f64, [[COPY18]], %subreg.sub_few_bfp_g32, [[COPY22]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY11]], %subreg.sub_few_bfp_w, [[COPY15]], %subreg.sub_few_bfp_f64, [[COPY19]], %subreg.sub_few_bfp_g32, [[COPY23]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE6]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE7]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:efey = REG_SEQUENCE [[REG_SEQUENCE5]], %subreg.sub_bfp768_lo, [[REG_SEQUENCE8]], %subreg.sub_bfp768_hi
    ; CHECK-NEXT: [[VNEGMUL_f_vmul_bfp13_:%[0-9]+]]:acc2048 = VNEGMUL_f_vmul_bfp13 [[REG_SEQUENCE2]], [[REG_SEQUENCE9]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VNEGMUL_f_vmul_bfp13_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<8 x s32>) = COPY $wh0
    %3:gprregbank(<2 x s32>) = COPY $fl0
    %4:gprregbank(<2 x s32>) = COPY $fh0
    %5:gprregbank(s32) = COPY $gl0
    %6:gprregbank(s32) = COPY $gh0
    %7:gprregbank(s32) = COPY $el0
    %8:gprregbank(s32) = COPY $eh0
    %9:vregbank(<8 x s32>) = COPY $wl2
    %10:vregbank(<8 x s32>) = COPY $wh2
    %11:vregbank(<8 x s32>) = COPY $wl3
    %12:vregbank(<8 x s32>) = COPY $wh3
    %13:gprregbank(<2 x s32>) = COPY $fl2
    %14:gprregbank(<2 x s32>) = COPY $fh2
    %15:gprregbank(<2 x s32>) = COPY $fl3
    %16:gprregbank(<2 x s32>) = COPY $fh3
    %17:gprregbank(s32) = COPY $gl2
    %18:gprregbank(s32) = COPY $gh2
    %19:gprregbank(s32) = COPY $gl3
    %20:gprregbank(s32) = COPY $gh3
    %21:gprregbank(s32) = COPY $el2
    %22:gprregbank(s32) = COPY $eh2
    %23:gprregbank(s32) = COPY $el3
    %24:gprregbank(s32) = COPY $eh3
    %25:gprregbank(s32) = G_CONSTANT i32 804
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.negmul.conf), %1(<8 x s32>), %2(<8 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(s32), %6(s32), %7(s32), %8(s32), %9(<8 x s32>), %10(<8 x s32>), %11(<8 x s32>), %12(<8 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<2 x s32>), %17(s32), %18(s32), %19(s32), %20(s32), %21(s32), %22(s32), %23(s32), %24(s32), %25(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_mac_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3

    ; CHECK-LABEL: name: _Z20test_mac_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $fl0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fh0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $gl0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gh0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $el0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $eh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY $wh2
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY $wl3
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY $wh3
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:el = COPY $fl2
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:el = COPY $fh2
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:el = COPY $fl3
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:el = COPY $fh3
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:er = COPY $gl2
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:er = COPY $gh2
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:er = COPY $gl3
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:er = COPY $gh3
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:er = COPY $el2
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:er = COPY $eh2
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:er = COPY $el3
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:er = COPY $eh3
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 804
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY]], %subreg.sub_few_bfp_w, [[COPY2]], %subreg.sub_few_bfp_f64, [[COPY4]], %subreg.sub_few_bfp_g32, [[COPY6]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY8]], %subreg.sub_few_bfp_w, [[COPY12]], %subreg.sub_few_bfp_f64, [[COPY16]], %subreg.sub_few_bfp_g32, [[COPY20]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY9]], %subreg.sub_few_bfp_w, [[COPY13]], %subreg.sub_few_bfp_f64, [[COPY17]], %subreg.sub_few_bfp_g32, [[COPY21]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY10]], %subreg.sub_few_bfp_w, [[COPY14]], %subreg.sub_few_bfp_f64, [[COPY18]], %subreg.sub_few_bfp_g32, [[COPY22]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY11]], %subreg.sub_few_bfp_w, [[COPY15]], %subreg.sub_few_bfp_f64, [[COPY19]], %subreg.sub_few_bfp_g32, [[COPY23]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE6]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE7]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:efey = REG_SEQUENCE [[REG_SEQUENCE5]], %subreg.sub_bfp768_lo, [[REG_SEQUENCE8]], %subreg.sub_bfp768_hi
    ; CHECK-NEXT: [[VMAC_f_vmac_bfp13_:%[0-9]+]]:acc2048 = VMAC_f_vmac_bfp13 [[COPY24]], [[REG_SEQUENCE2]], [[REG_SEQUENCE9]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMAC_f_vmac_bfp13_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<8 x s32>) = COPY $wh0
    %3:gprregbank(<2 x s32>) = COPY $fl0
    %4:gprregbank(<2 x s32>) = COPY $fh0
    %5:gprregbank(s32) = COPY $gl0
    %6:gprregbank(s32) = COPY $gh0
    %7:gprregbank(s32) = COPY $el0
    %8:gprregbank(s32) = COPY $eh0
    %9:vregbank(<8 x s32>) = COPY $wl2
    %10:vregbank(<8 x s32>) = COPY $wh2
    %11:vregbank(<8 x s32>) = COPY $wl3
    %12:vregbank(<8 x s32>) = COPY $wh3
    %13:gprregbank(<2 x s32>) = COPY $fl2
    %14:gprregbank(<2 x s32>) = COPY $fh2
    %15:gprregbank(<2 x s32>) = COPY $fl3
    %16:gprregbank(<2 x s32>) = COPY $fh3
    %17:gprregbank(s32) = COPY $gl2
    %18:gprregbank(s32) = COPY $gh2
    %19:gprregbank(s32) = COPY $gl3
    %20:gprregbank(s32) = COPY $gh3
    %21:gprregbank(s32) = COPY $el2
    %22:gprregbank(s32) = COPY $eh2
    %23:gprregbank(s32) = COPY $el3
    %24:gprregbank(s32) = COPY $eh3
    %25:accregbank(<64 x s32>) = COPY $dm1
    %26:gprregbank(s32) = G_CONSTANT i32 804
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.mac.conf), %1(<8 x s32>), %2(<8 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(s32), %6(s32), %7(s32), %8(s32), %9(<8 x s32>), %10(<8 x s32>), %11(<8 x s32>), %12(<8 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<2 x s32>), %17(s32), %18(s32), %19(s32), %20(s32), %21(s32), %22(s32), %23(s32), %24(s32), %25(<64 x s32>), %26(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z20test_msc_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloat
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3

    ; CHECK-LABEL: name: _Z20test_msc_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloat
    ; CHECK: liveins: $dm1, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $fl0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fh0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $gl0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gh0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $el0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $eh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY $wh2
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY $wl3
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY $wh3
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:el = COPY $fl2
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:el = COPY $fh2
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:el = COPY $fl3
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:el = COPY $fh3
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:er = COPY $gl2
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:er = COPY $gh2
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:er = COPY $gl3
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:er = COPY $gh3
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:er = COPY $el2
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:er = COPY $eh2
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:er = COPY $el3
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:er = COPY $eh3
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 804
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY]], %subreg.sub_few_bfp_w, [[COPY2]], %subreg.sub_few_bfp_f64, [[COPY4]], %subreg.sub_few_bfp_g32, [[COPY6]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY8]], %subreg.sub_few_bfp_w, [[COPY12]], %subreg.sub_few_bfp_f64, [[COPY16]], %subreg.sub_few_bfp_g32, [[COPY20]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY9]], %subreg.sub_few_bfp_w, [[COPY13]], %subreg.sub_few_bfp_f64, [[COPY17]], %subreg.sub_few_bfp_g32, [[COPY21]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY10]], %subreg.sub_few_bfp_w, [[COPY14]], %subreg.sub_few_bfp_f64, [[COPY18]], %subreg.sub_few_bfp_g32, [[COPY22]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY11]], %subreg.sub_few_bfp_w, [[COPY15]], %subreg.sub_few_bfp_f64, [[COPY19]], %subreg.sub_few_bfp_g32, [[COPY23]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE6]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE7]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:efey = REG_SEQUENCE [[REG_SEQUENCE5]], %subreg.sub_bfp768_lo, [[REG_SEQUENCE8]], %subreg.sub_bfp768_hi
    ; CHECK-NEXT: [[VMSC_f_vmac_bfp13_:%[0-9]+]]:acc2048 = VMSC_f_vmac_bfp13 [[COPY24]], [[REG_SEQUENCE2]], [[REG_SEQUENCE9]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VMSC_f_vmac_bfp13_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<8 x s32>) = COPY $wh0
    %3:gprregbank(<2 x s32>) = COPY $fl0
    %4:gprregbank(<2 x s32>) = COPY $fh0
    %5:gprregbank(s32) = COPY $gl0
    %6:gprregbank(s32) = COPY $gh0
    %7:gprregbank(s32) = COPY $el0
    %8:gprregbank(s32) = COPY $eh0
    %9:vregbank(<8 x s32>) = COPY $wl2
    %10:vregbank(<8 x s32>) = COPY $wh2
    %11:vregbank(<8 x s32>) = COPY $wl3
    %12:vregbank(<8 x s32>) = COPY $wh3
    %13:gprregbank(<2 x s32>) = COPY $fl2
    %14:gprregbank(<2 x s32>) = COPY $fh2
    %15:gprregbank(<2 x s32>) = COPY $fl3
    %16:gprregbank(<2 x s32>) = COPY $fh3
    %17:gprregbank(s32) = COPY $gl2
    %18:gprregbank(s32) = COPY $gh2
    %19:gprregbank(s32) = COPY $gl3
    %20:gprregbank(s32) = COPY $gh3
    %21:gprregbank(s32) = COPY $el2
    %22:gprregbank(s32) = COPY $eh2
    %23:gprregbank(s32) = COPY $el3
    %24:gprregbank(s32) = COPY $eh3
    %25:accregbank(<64 x s32>) = COPY $dm1
    %26:gprregbank(s32) = G_CONSTANT i32 804
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.msc.conf), %1(<8 x s32>), %2(<8 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(s32), %6(s32), %7(s32), %8(s32), %9(<8 x s32>), %10(<8 x s32>), %11(<8 x s32>), %12(<8 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<2 x s32>), %17(s32), %18(s32), %19(s32), %20(s32), %21(s32), %22(s32), %23(s32), %24(s32), %25(<64 x s32>), %26(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z23test_addmac_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3

    ; CHECK-LABEL: name: _Z23test_addmac_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $fl0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fh0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $gl0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gh0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $el0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $eh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY $wh2
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY $wl3
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY $wh3
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:el = COPY $fl2
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:el = COPY $fh2
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:el = COPY $fl3
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:el = COPY $fh3
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:er = COPY $gl2
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:er = COPY $gh2
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:er = COPY $gl3
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:er = COPY $gh3
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:er = COPY $el2
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:er = COPY $eh2
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:er = COPY $el3
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:er = COPY $eh3
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 804
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY]], %subreg.sub_few_bfp_w, [[COPY2]], %subreg.sub_few_bfp_f64, [[COPY4]], %subreg.sub_few_bfp_g32, [[COPY6]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY8]], %subreg.sub_few_bfp_w, [[COPY12]], %subreg.sub_few_bfp_f64, [[COPY16]], %subreg.sub_few_bfp_g32, [[COPY20]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY9]], %subreg.sub_few_bfp_w, [[COPY13]], %subreg.sub_few_bfp_f64, [[COPY17]], %subreg.sub_few_bfp_g32, [[COPY21]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY10]], %subreg.sub_few_bfp_w, [[COPY14]], %subreg.sub_few_bfp_f64, [[COPY18]], %subreg.sub_few_bfp_g32, [[COPY22]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY11]], %subreg.sub_few_bfp_w, [[COPY15]], %subreg.sub_few_bfp_f64, [[COPY19]], %subreg.sub_few_bfp_g32, [[COPY23]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE6]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE7]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:efey = REG_SEQUENCE [[REG_SEQUENCE5]], %subreg.sub_bfp768_lo, [[REG_SEQUENCE8]], %subreg.sub_bfp768_hi
    ; CHECK-NEXT: [[VADDMAC_f_vaddmac_bfp13_:%[0-9]+]]:acc2048 = VADDMAC_f_vaddmac_bfp13 [[COPY24]], [[COPY25]], [[REG_SEQUENCE2]], [[REG_SEQUENCE9]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMAC_f_vaddmac_bfp13_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<8 x s32>) = COPY $wh0
    %3:gprregbank(<2 x s32>) = COPY $fl0
    %4:gprregbank(<2 x s32>) = COPY $fh0
    %5:gprregbank(s32) = COPY $gl0
    %6:gprregbank(s32) = COPY $gh0
    %7:gprregbank(s32) = COPY $el0
    %8:gprregbank(s32) = COPY $eh0
    %9:vregbank(<8 x s32>) = COPY $wl2
    %10:vregbank(<8 x s32>) = COPY $wh2
    %11:vregbank(<8 x s32>) = COPY $wl3
    %12:vregbank(<8 x s32>) = COPY $wh3
    %13:gprregbank(<2 x s32>) = COPY $fl2
    %14:gprregbank(<2 x s32>) = COPY $fh2
    %15:gprregbank(<2 x s32>) = COPY $fl3
    %16:gprregbank(<2 x s32>) = COPY $fh3
    %17:gprregbank(s32) = COPY $gl2
    %18:gprregbank(s32) = COPY $gh2
    %19:gprregbank(s32) = COPY $gl3
    %20:gprregbank(s32) = COPY $gh3
    %21:gprregbank(s32) = COPY $el2
    %22:gprregbank(s32) = COPY $eh2
    %23:gprregbank(s32) = COPY $el3
    %24:gprregbank(s32) = COPY $eh3
    %25:accregbank(<64 x s32>) = COPY $dm1
    %26:accregbank(<64 x s32>) = COPY $dm2
    %27:gprregbank(s32) = G_CONSTANT i32 804
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.addmac.conf), %1(<8 x s32>), %2(<8 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(s32), %6(s32), %7(s32), %8(s32), %9(<8 x s32>), %10(<8 x s32>), %11(<8 x s32>), %12(<8 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<2 x s32>), %17(s32), %18(s32), %19(s32), %20(s32), %21(s32), %22(s32), %23(s32), %24(s32), %25(<64 x s32>), %26(<64 x s32>), %27(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            _Z23test_addmsc_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloatS1_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $dm1, $dm2, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3

    ; CHECK-LABEL: name: _Z23test_addmsc_4x16_16x16T7v128mx67v256mx6Dv64_u10__accfloatS1_
    ; CHECK: liveins: $dm1, $dm2, $eh0, $eh2, $eh3, $el0, $el2, $el3, $fh0, $fh2, $fh3, $fl0, $fl2, $fl3, $gh0, $gh2, $gh3, $gl0, $gl2, $gl3, $wh0, $wh2, $wh3, $wl0, $wl2, $wl3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:el = COPY $fl0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:el = COPY $fh0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $gl0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $gh0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:er = COPY $el0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $eh0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:vec256 = COPY $wl2
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:vec256 = COPY $wh2
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:vec256 = COPY $wl3
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:vec256 = COPY $wh3
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:el = COPY $fl2
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:el = COPY $fh2
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:el = COPY $fl3
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:el = COPY $fh3
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:er = COPY $gl2
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:er = COPY $gh2
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:er = COPY $gl3
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:er = COPY $gh3
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:er = COPY $el2
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:er = COPY $eh2
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:er = COPY $el3
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:er = COPY $eh3
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc2048 = COPY $dm1
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc2048 = COPY $dm2
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mrv8 = MOV_RLC_imm11_pseudo 804
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY]], %subreg.sub_few_bfp_w, [[COPY2]], %subreg.sub_few_bfp_f64, [[COPY4]], %subreg.sub_few_bfp_g32, [[COPY6]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY1]], %subreg.sub_few_bfp_w, [[COPY3]], %subreg.sub_few_bfp_f64, [[COPY5]], %subreg.sub_few_bfp_g32, [[COPY7]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:mfexa = REG_SEQUENCE [[REG_SEQUENCE]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE1]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY8]], %subreg.sub_few_bfp_w, [[COPY12]], %subreg.sub_few_bfp_f64, [[COPY16]], %subreg.sub_few_bfp_g32, [[COPY20]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY9]], %subreg.sub_few_bfp_w, [[COPY13]], %subreg.sub_few_bfp_f64, [[COPY17]], %subreg.sub_few_bfp_g32, [[COPY21]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE3]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE4]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY10]], %subreg.sub_few_bfp_w, [[COPY14]], %subreg.sub_few_bfp_f64, [[COPY18]], %subreg.sub_few_bfp_g32, [[COPY22]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:mfews = REG_SEQUENCE [[COPY11]], %subreg.sub_few_bfp_w, [[COPY15]], %subreg.sub_few_bfp_f64, [[COPY19]], %subreg.sub_few_bfp_g32, [[COPY23]], %subreg.sub_few_bfp_e32
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:mfexs = REG_SEQUENCE [[REG_SEQUENCE6]], %subreg.sub_bfp384_lo, [[REG_SEQUENCE7]], %subreg.sub_bfp384_hi
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:efey = REG_SEQUENCE [[REG_SEQUENCE5]], %subreg.sub_bfp768_lo, [[REG_SEQUENCE8]], %subreg.sub_bfp768_hi
    ; CHECK-NEXT: [[VADDMSC_f_vaddmac_bfp13_:%[0-9]+]]:acc2048 = VADDMSC_f_vaddmac_bfp13 [[COPY24]], [[COPY25]], [[REG_SEQUENCE2]], [[REG_SEQUENCE9]], [[MOV_RLC_imm11_pseudo]], implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $dm0 = COPY [[VADDMSC_f_vaddmac_bfp13_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<8 x s32>) = COPY $wh0
    %3:gprregbank(<2 x s32>) = COPY $fl0
    %4:gprregbank(<2 x s32>) = COPY $fh0
    %5:gprregbank(s32) = COPY $gl0
    %6:gprregbank(s32) = COPY $gh0
    %7:gprregbank(s32) = COPY $el0
    %8:gprregbank(s32) = COPY $eh0
    %9:vregbank(<8 x s32>) = COPY $wl2
    %10:vregbank(<8 x s32>) = COPY $wh2
    %11:vregbank(<8 x s32>) = COPY $wl3
    %12:vregbank(<8 x s32>) = COPY $wh3
    %13:gprregbank(<2 x s32>) = COPY $fl2
    %14:gprregbank(<2 x s32>) = COPY $fh2
    %15:gprregbank(<2 x s32>) = COPY $fl3
    %16:gprregbank(<2 x s32>) = COPY $fh3
    %17:gprregbank(s32) = COPY $gl2
    %18:gprregbank(s32) = COPY $gh2
    %19:gprregbank(s32) = COPY $gl3
    %20:gprregbank(s32) = COPY $gh3
    %21:gprregbank(s32) = COPY $el2
    %22:gprregbank(s32) = COPY $eh2
    %23:gprregbank(s32) = COPY $el3
    %24:gprregbank(s32) = COPY $eh3
    %25:accregbank(<64 x s32>) = COPY $dm1
    %26:accregbank(<64 x s32>) = COPY $dm2
    %27:gprregbank(s32) = G_CONSTANT i32 804
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.BFP768.BFP1536.ACC2048.bf.addmsc.conf), %1(<8 x s32>), %2(<8 x s32>), %3(<2 x s32>), %4(<2 x s32>), %5(s32), %6(s32), %7(s32), %8(s32), %9(<8 x s32>), %10(<8 x s32>), %11(<8 x s32>), %12(<8 x s32>), %13(<2 x s32>), %14(<2 x s32>), %15(<2 x s32>), %16(<2 x s32>), %17(s32), %18(s32), %19(s32), %20(s32), %21(s32), %22(s32), %23(s32), %24(s32), %25(<64 x s32>), %26(<64 x s32>), %27(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
