# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name:            sups_sign_unsigned_ACC512_VEC256_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: sups_sign_unsigned_ACC512_VEC256_acc32
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_w2b_upsSign0_:%[0-9]+]]:acc512 = VUPS_2x_mv_ups_w2b_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $bmll0 = COPY [[VUPS_2x_mv_ups_w2b_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            sups_sign_signed_ACC512_VEC256_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: sups_sign_signed_ACC512_VEC256_acc32
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_w2b_upsSign1_:%[0-9]+]]:acc512 = VUPS_2x_mv_ups_w2b_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $bmll0 = COPY [[VUPS_2x_mv_ups_w2b_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            sups_sign_dynamic_ACC512_VEC256_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $wl0


    ; CHECK-LABEL: name: sups_sign_dynamic_ACC512_VEC256_acc32
    ; CHECK: liveins: $r0, $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_w2b_upsSign0_:%[0-9]+]]:acc512 = VUPS_2x_mv_ups_w2b_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $bmll0 = COPY [[VUPS_2x_mv_ups_w2b_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            lups_sign_unsigned_ACC512_VEC256_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: lups_sign_unsigned_ACC512_VEC256_acc64
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_w2b_upsSign0_:%[0-9]+]]:acc512 = VUPS_2x_mv_ups_w2b_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $bmll0 = COPY [[VUPS_2x_mv_ups_w2b_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v8.I256.ups), %1(<8 x s32>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<8 x s64>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            lups_sign_signed_ACC512_VEC256_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: lups_sign_signed_ACC512_VEC256_acc64
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_w2b_upsSign1_:%[0-9]+]]:acc512 = VUPS_2x_mv_ups_w2b_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $bmll0 = COPY [[VUPS_2x_mv_ups_w2b_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v8.I256.ups), %1(<8 x s32>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<8 x s64>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            lups_sign_dynamic_ACC512_VEC256_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $wl0


    ; CHECK-LABEL: name: lups_sign_dynamic_ACC512_VEC256_acc64
    ; CHECK: liveins: $r0, $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_w2b_upsSign0_:%[0-9]+]]:acc512 = VUPS_2x_mv_ups_w2b_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $bmll0 = COPY [[VUPS_2x_mv_ups_w2b_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v8.I256.ups), %1(<8 x s32>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<8 x s64>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            sups_sign_unsigned_ACC1024_VEC256_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: sups_sign_unsigned_ACC1024_VEC256_acc32
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_w2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_4x_mv_ups_w2c_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_4x_mv_ups_w2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s8>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I256.ups), %1(<32 x s8>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            sups_sign_signed_ACC1024_VEC256_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: sups_sign_signed_ACC1024_VEC256_acc32
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_w2c_upsSign1_:%[0-9]+]]:acc1024 = VUPS_4x_mv_ups_w2c_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_4x_mv_ups_w2c_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s8>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I256.ups), %1(<32 x s8>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            sups_sign_dynamic_ACC1024_VEC256_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $wl0


    ; CHECK-LABEL: name: sups_sign_dynamic_ACC1024_VEC256_acc32
    ; CHECK: liveins: $r0, $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_w2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_4x_mv_ups_w2c_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_4x_mv_ups_w2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s8>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I256.ups), %1(<32 x s8>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            lups_sign_unsigned_ACC1024_VEC256_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: lups_sign_unsigned_ACC1024_VEC256_acc64
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_w2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_4x_mv_ups_w2c_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_4x_mv_ups_w2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            lups_sign_signed_ACC1024_VEC256_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0


    ; CHECK-LABEL: name: lups_sign_signed_ACC1024_VEC256_acc64
    ; CHECK: liveins: $r0, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_w2c_upsSign1_:%[0-9]+]]:acc1024 = VUPS_4x_mv_ups_w2c_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_4x_mv_ups_w2c_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            lups_sign_dynamic_ACC1024_VEC256_acc64
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $wl0


    ; CHECK-LABEL: name: lups_sign_dynamic_ACC1024_VEC256_acc64
    ; CHECK: liveins: $r0, $r1, $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_w2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_4x_mv_ups_w2c_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_4x_mv_ups_w2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            sups_sign_unsigned_ACC1024_VEC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: sups_sign_unsigned_ACC1024_VEC512_acc32
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_x2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_2x_mv_ups_x2c_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_2x_mv_ups_x2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            sups_sign_signed_ACC1024_VEC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: sups_sign_signed_ACC1024_VEC512_acc32
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_x2c_upsSign1_:%[0-9]+]]:acc1024 = VUPS_2x_mv_ups_x2c_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_2x_mv_ups_x2c_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            sups_sign_dynamic_ACC1024_VEC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x0


    ; CHECK-LABEL: name: sups_sign_dynamic_ACC1024_VEC512_acc32
    ; CHECK: liveins: $r0, $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_x2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_2x_mv_ups_x2c_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_2x_mv_ups_x2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            lups_sign_unsigned_ACC1024_VEC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: lups_sign_unsigned_ACC1024_VEC512_acc64
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_x2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_2x_mv_ups_x2c_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_2x_mv_ups_x2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I512.ups), %1(<16 x s32>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            lups_sign_signed_ACC1024_VEC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: lups_sign_signed_ACC1024_VEC512_acc64
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_x2c_upsSign1_:%[0-9]+]]:acc1024 = VUPS_2x_mv_ups_x2c_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_2x_mv_ups_x2c_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I512.ups), %1(<16 x s32>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            lups_sign_dynamic_ACC1024_VEC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x0


    ; CHECK-LABEL: name: lups_sign_dynamic_ACC1024_VEC512_acc64
    ; CHECK: liveins: $r0, $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_2x_mv_ups_x2c_upsSign0_:%[0-9]+]]:acc1024 = VUPS_2x_mv_ups_x2c_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $cml0 = COPY [[VUPS_2x_mv_ups_x2c_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<16 x s32>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I512.ups), %1(<16 x s32>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            sups_sign_unsigned_ACC2048_VEC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: sups_sign_unsigned_ACC2048_VEC512_acc32
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_x2d_upsSign0_:%[0-9]+]]:acc2048 = VUPS_4x_mv_ups_x2d_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $dm0 = COPY [[VUPS_4x_mv_ups_x2d_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %1(<64 x s8>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            sups_sign_signed_ACC2048_VEC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: sups_sign_signed_ACC2048_VEC512_acc32
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_x2d_upsSign1_:%[0-9]+]]:acc2048 = VUPS_4x_mv_ups_x2d_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $dm0 = COPY [[VUPS_4x_mv_ups_x2d_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %1(<64 x s8>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            sups_sign_dynamic_ACC2048_VEC512_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x0


    ; CHECK-LABEL: name: sups_sign_dynamic_ACC2048_VEC512_acc32
    ; CHECK: liveins: $r0, $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_x2d_upsSign0_:%[0-9]+]]:acc2048 = VUPS_4x_mv_ups_x2d_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $dm0 = COPY [[VUPS_4x_mv_ups_x2d_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<64 x s8>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %1(<64 x s8>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            lups_sign_unsigned_ACC2048_VEC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: lups_sign_unsigned_ACC2048_VEC512_acc64
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_x2d_upsSign0_:%[0-9]+]]:acc2048 = VUPS_4x_mv_ups_x2d_upsSign0 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $dm0 = COPY [[VUPS_4x_mv_ups_x2d_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            lups_sign_signed_ACC2048_VEC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0


    ; CHECK-LABEL: name: lups_sign_signed_ACC2048_VEC512_acc64
    ; CHECK: liveins: $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_x2d_upsSign1_:%[0-9]+]]:acc2048 = VUPS_4x_mv_ups_x2d_upsSign1 [[COPY]], [[COPY2]], implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: $dm0 = COPY [[VUPS_4x_mv_ups_x2d_upsSign1_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            lups_sign_dynamic_ACC2048_VEC512_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $x0


    ; CHECK-LABEL: name: lups_sign_dynamic_ACC2048_VEC512_acc64
    ; CHECK: liveins: $r0, $r1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VUPS_4x_mv_ups_x2d_upsSign0_:%[0-9]+]]:acc2048 = VUPS_4x_mv_ups_x2d_upsSign0 [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $dm0 = COPY [[VUPS_4x_mv_ups_x2d_upsSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:vregbank(<32 x s16>) = COPY $x0
    %2:gprregbank(s32) = COPY $r0
    %3:gprregbank(s32) = COPY $r1
    %0:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0

...
---
name:            test_ups_to_v16accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $wl0


    ; CHECK-LABEL: name: test_ups_to_v16accfloat
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[VCONV_fp32_bf16_mv_mv_w_ups_bf16_:%[0-9]+]]:acc512 = VCONV_fp32_bf16_mv_mv_w_ups_bf16 [[COPY]]
    ; CHECK-NEXT: $bmll0 = COPY [[VCONV_fp32_bf16_mv_mv_w_ups_bf16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %0:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %1(<16 x s16>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            test_ups_to_v32accfloat
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0


    ; CHECK-LABEL: name: test_ups_to_v32accfloat
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[VCONV_fp32_bf16_mv_mv_x_ups_f16_:%[0-9]+]]:acc1024 = VCONV_fp32_bf16_mv_mv_x_ups_f16 [[COPY]]
    ; CHECK-NEXT: $cml0 = COPY [[VCONV_fp32_bf16_mv_mv_x_ups_f16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32bf16.to.v32accfloat), %1(<32 x s16>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
---
name:            _Z23test_ups_to_v16accfloatDv16_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $wl0


    ; CHECK-LABEL: name: _Z23test_ups_to_v16accfloatDv16_DF16_
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mwla = COPY $wl0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY]], %subreg.sub_256_lo
    ; CHECK-NEXT: [[VCONV_fp32_fp16_mv:%[0-9]+]]:mcma = VCONV_fp32_fp16_mv [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mmvbmsrc = COPY [[VCONV_fp32_fp16_mv]].sub_512_acc_lo
    ; CHECK-NEXT: $bmll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:vregbank(<16 x s16>) = COPY $wl0
    %0:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16float16.to.v16accfloat), %1(<16 x s16>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0

...
---
name:            _Z23test_ups_to_v32accfloatDv32_DF16_
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0


    ; CHECK-LABEL: name: _Z23test_ups_to_v32accfloatDv32_DF16_
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[VCONV_fp32_fp16_mv:%[0-9]+]]:acc1024 = VCONV_fp32_fp16_mv [[COPY]]
    ; CHECK-NEXT: $cml0 = COPY [[VCONV_fp32_fp16_mv]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:vregbank(<32 x s16>) = COPY $x0
    %0:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), %1(<32 x s16>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0

...
