# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VEXTBCST_128_vec_extract_broadcast_r
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_128_vec_extract_broadcast_r
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mlockid_reg = COPY $r0
    ; CHECK-NEXT: [[VEXTBCST_128_vec_extract_broadcast_r:%[0-9]+]]:vec512 = VEXTBCST_128_vec_extract_broadcast_r [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[VEXTBCST_128_vec_extract_broadcast_r]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %3:gprregbank(s32) = COPY $r0
    %0:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vextract.broadcast128.I512), %1:vregbank(<16 x s32>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
---
name:            VEXTBCST_128_vec_extract_broadcast_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2
    ; CHECK-LABEL: name: VEXTBCST_128_vec_extract_broadcast_imm
    ; CHECK: liveins: $r0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VEXTBCST_128_vec_extract_broadcast_imm:%[0-9]+]]:vec512 = VEXTBCST_128_vec_extract_broadcast_imm [[COPY]], 1
    ; CHECK-NEXT: $x0 = COPY [[VEXTBCST_128_vec_extract_broadcast_imm]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.vextract.broadcast128.I512), %1:vregbank(<16 x s32>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
