# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VLDA_UPS_2x_acc32_v16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc64_v8_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v8_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v8.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc64_v16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v16_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc32_v32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc64_v16_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v16_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_:%[0-9]+]]:acc1024 = VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmx_lda_ups_x2c_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc64_v32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc64_v32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v32.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc32_v16_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc64_v8_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc64_v8_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v8.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_:%[0-9]+]]:acc1024 = VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmw_lda_ups_w2c_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v64_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0 [[COPY2]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 0
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc32_v16_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<16 x s16>))
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<16 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v64_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $upssign0 = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0 [[COPY3]], [[COPY]], 0, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0 :: (load (<32 x s16>))
    ; CHECK-NEXT: $upssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_imm_upsSign0_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = COPY $r1
    %5:vregbank(<32 x s16>) = G_LOAD %1:ptrregbank(p0) :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc32_v16_offset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $m0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_offset
    ; CHECK: liveins: $p0, $r0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_upsSign1_:%[0-9]+]]:acc512 = VLDA_UPS_2x_dmw_lda_ups_w2b_idx_upsSign1 [[COPY3]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_idx_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %8:modregbank(s20) = COPY $m0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v64_offset
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $m0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_offset
    ; CHECK: liveins: $p0, $r0, $m0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_upsSign1_:%[0-9]+]]:acc2048 = VLDA_UPS_4x_dmx_lda_ups_x2d_idx_upsSign1 [[COPY3]], [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_idx_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %8:modregbank(s20) = COPY $m0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>) = G_AIE_OFFSET_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc32_v16_postinc
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_postinc
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc512, [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1 [[COPY2]], [[COPY]], 32, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_2x_dmw_lda_ups_w2b_pstm_nrm_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %8:modregbank(s20) = G_CONSTANT i20 32
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<16 x s16>), %9:ptrregbank(p0) = G_AIE_POSTINC_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v64_postinc
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_postinc
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_1:%[0-9]+]]:ep = VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1 [[COPY2]], [[COPY]], 64, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_UPS_4x_dmx_lda_ups_x2d_pstm_nrm_imm_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %8:modregbank(s20) = G_CONSTANT i20 64
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %5:vregbank(<32 x s16>), %9:ptrregbank(p0) = G_AIE_POSTINC_LOAD %1:ptrregbank(p0), %8:modregbank(s20) :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc32_v16_2D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_2D
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_:%[0-9]+]]:acc512, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edn(s20) = G_CONSTANT i20 3
    %13:edc(s20) = G_CONSTANT i20 4
    %5:vregbank(<16 x s16>), %19:ptrregbank(p0), %20:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13 :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v64_2D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_2D
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_1:%[0-9]+]]:ep, [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_2:%[0-9]+]]:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edn(s20) = G_CONSTANT i20 3
    %13:edc(s20) = G_CONSTANT i20 4
    %5:vregbank(<32 x s16>), %19:ptrregbank(p0), %20:modregbank(s20) = G_AIE_POSTINC_2D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13 :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_2x_acc32_v16_3D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDA_UPS_2x_acc32_v16_3D
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1_:%[0-9]+]]:acc512, [[VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1_1:%[0-9]+]]:ep, [[VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1_2:%[0-9]+]]:edcl, [[VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1_3:%[0-9]+]]:edch = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<16 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edj(s20) = G_CONSTANT i20 3
    %13:edn(s20) = G_CONSTANT i20 4
    %14:edn(s20) = G_CONSTANT i20 5
    %15:edc(s20) = G_CONSTANT i20 6
    %16:edc(s20) = G_CONSTANT i20 7
    %5:vregbank(<16 x s16>), %19:ptrregbank(p0), %20:modregbank(s20), %21:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13, %15, %14, %16 :: (load (<16 x s16>))
    %7:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %5:vregbank(<16 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...

---
name:            VLDA_UPS_4x_acc32_v64_3D
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: VLDA_UPS_4x_acc32_v64_3D
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crupsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1_:%[0-9]+]]:acc2048, [[VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1_1:%[0-9]+]]:ep, [[VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1_2:%[0-9]+]]:edcl, [[VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1_3:%[0-9]+]]:edch = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1 [[COPY2]], [[COPY]], [[REG_SEQUENCE]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1 :: (load (<32 x s16>))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1_]]
    %1:ptrregbank(p0) = COPY $p0
    %2:gprregbank(s32) = COPY $r0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edj(s20) = G_CONSTANT i20 3
    %13:edn(s20) = G_CONSTANT i20 4
    %14:edn(s20) = G_CONSTANT i20 5
    %15:edc(s20) = G_CONSTANT i20 6
    %16:edc(s20) = G_CONSTANT i20 7
    %5:vregbank(<32 x s16>), %19:ptrregbank(p0), %20:modregbank(s20), %21:modregbank(s20) = G_AIE_POSTINC_3D_LOAD %1:ptrregbank(p0), %10, %11, %12, %13, %15, %14, %16 :: (load (<32 x s16>))
    %7:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %5:vregbank(<32 x s16>), %2:gprregbank(s32), %6:gprregbank(s32)
    PseudoRET implicit $lr, implicit %7
...
