# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_SRS_2x_v16_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v8_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v8_acc64_signed
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v8.acc64.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v32_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc32_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v16_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v16_acc64_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v32_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v32_acc32_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc32.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_2x_v16_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cml0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc64_signed
    ; CHECK: liveins: $cml0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dm_sts_srs_cm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s32>))
    %0:accregbank(<16 x s64>) = COPY $cml0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v16.acc64.srs), %0:accregbank(<16 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s32>), %3:ptrregbank(p0) :: (store (<16 x s32>))
...

---
name:            VST_SRS_4x_v64_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_signed
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_4x_v32_acc64_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v32_acc64_signed
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc64.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_2x_v16_acc32_unsigned
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_unsigned
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY]], [[COPY3]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 0
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_POSTINC_imm_2x_v16_acc32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0
    ; CHECK-LABEL: name: VST_SRS_POSTINC_imm_2x_v16_acc32
    ; CHECK: liveins: $bmll0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_SRS_2x_dmw_sts_srs_bm_pstm_nrm_imm_srsSign1_:%[0-9]+]]:ep = VST_SRS_2x_dmw_sts_srs_bm_pstm_nrm_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 32, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %8:modregbank(s20) = G_CONSTANT i20 32
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    %9:ptrregbank(p0) = G_AIE_POSTINC_STORE %6, %3, %8 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2x_v16_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_2x_v16_acc32_dynamic
    ; CHECK: liveins: $bmll0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<16 x s16>))
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<16 x s16>), %3:ptrregbank(p0) :: (store (<16 x s16>))
...

---
name:            VST_SRS_4x_v64_acc32_dynamic
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0, $r1
    ; CHECK-LABEL: name: VST_SRS_4x_v64_acc32_dynamic
    ; CHECK: liveins: $dm0, $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign0 [[COPY]], [[COPY4]], [[COPY2]], 0, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0 :: (store (<32 x s16>))
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = COPY $r1
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_STORE %6:vregbank(<32 x s16>), %3:ptrregbank(p0) :: (store (<32 x s16>))
...

---
name:            VST_SRS_OFFSET_2x_v16_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0
    ; CHECK-LABEL: name: VST_SRS_OFFSET_2x_v16_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_2x_dmw_sts_srs_bm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 64, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %8:modregbank(s20) = G_CONSTANT i20 64
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_AIE_OFFSET_STORE %6, %3, %8 :: (store (<16 x s16>))
...

---
name:            VST_SRS_OFFSET_4x_v64_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0
    ; CHECK-LABEL: name: VST_SRS_OFFSET_4x_v64_acc32_signed
    ; CHECK: liveins: $dm0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: VST_SRS_4x_dmx_sts_srs_dm_idx_imm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], 128, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %8:modregbank(s20) = G_CONSTANT i20 128
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    G_AIE_OFFSET_STORE %6, %3, %8 :: (store (<32 x s16>))
...

---
name:            VST_SRS_2D_2x_v16_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0
    ; CHECK-LABEL: name: VST_SRS_2D_2x_v16_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1_:%[0-9]+]]:ep, [[VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1_1:%[0-9]+]]:edc = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], [[REG_SEQUENCE]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edn(s20) = G_CONSTANT i20 3
    %13:edc(s20) = G_CONSTANT i20 4
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    %19:ptrregbank(p0), %20:modregbank(s20) = G_AIE_POSTINC_2D_STORE %6, %3, %10, %11, %12, %13 :: (store (<16 x s16>))
...

---
name:            VST_SRS_2D_4x_v64_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0
    ; CHECK-LABEL: name: VST_SRS_2D_4x_v64_acc32_signed
    ; CHECK: liveins: $dm0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo2]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_count
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1_:%[0-9]+]]:ep, [[VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1_1:%[0-9]+]]:edc = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], [[REG_SEQUENCE]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edn(s20) = G_CONSTANT i20 3
    %13:edc(s20) = G_CONSTANT i20 4
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    %19:ptrregbank(p0), %20:modregbank(s20) = G_AIE_POSTINC_2D_STORE %6, %3, %10, %11, %12, %13 :: (store (<32 x s16>))
...

---
name:            VST_SRS_3D_2x_v16_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $p0, $r0
    ; CHECK-LABEL: name: VST_SRS_3D_2x_v16_acc32_signed
    ; CHECK: liveins: $bmll0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1_:%[0-9]+]]:ep, [[VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1_1:%[0-9]+]]:edcl, [[VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1_2:%[0-9]+]]:edch = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], [[REG_SEQUENCE]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<16 x s16>))
    %0:accregbank(<8 x s64>) = COPY $bmll0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edj(s20) = G_CONSTANT i20 3
    %13:edn(s20) = G_CONSTANT i20 4
    %14:edn(s20) = G_CONSTANT i20 5
    %15:edc(s20) = G_CONSTANT i20 6
    %16:edc(s20) = G_CONSTANT i20 7
    %6:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %0:accregbank(<8 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    %19:ptrregbank(p0), %20:modregbank(s20), %21:modregbank(s20) = G_AIE_POSTINC_3D_STORE %6, %3, %10, %11, %12, %13, %15, %14, %16 :: (store (<16 x s16>))
...

---
name:            VST_SRS_3D_4x_v64_acc32_signed
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $dm0, $p0, $r0
    ; CHECK-LABEL: name: VST_SRS_3D_4x_v64_acc32_signed
    ; CHECK: liveins: $dm0, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 1
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 2
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo2:%[0-9]+]]:edj = MOV_PD_imm11_pseudo 3
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo3:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 4
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo4:%[0-9]+]]:edn = MOV_PD_imm11_pseudo 5
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo5:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 6
    ; CHECK-NEXT: [[MOV_PD_imm11_pseudo6:%[0-9]+]]:edc = MOV_PD_imm11_pseudo 7
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:eds = REG_SEQUENCE [[MOV_PD_imm11_pseudo]], %subreg.sub_mod, [[MOV_PD_imm11_pseudo3]], %subreg.sub_dim_size, [[MOV_PD_imm11_pseudo1]], %subreg.sub_dim_stride, [[MOV_PD_imm11_pseudo5]], %subreg.sub_dim_count, [[MOV_PD_imm11_pseudo4]], %subreg.sub_hi_dim_then_sub_dim_size, [[MOV_PD_imm11_pseudo2]], %subreg.sub_hi_dim_then_sub_dim_stride, [[MOV_PD_imm11_pseudo6]], %subreg.sub_hi_dim_then_sub_dim_count
    ; CHECK-NEXT: $crsrsmode = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1_:%[0-9]+]]:ep, [[VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1_1:%[0-9]+]]:edcl, [[VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1_2:%[0-9]+]]:edch = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1 [[COPY]], [[COPY3]], [[COPY2]], [[REG_SEQUENCE]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1 :: (store (<32 x s16>))
    %0:accregbank(<32 x s64>) = COPY $dm0
    %1:gprregbank(s32) = COPY $r0
    %3:ptrregbank(p0) = COPY $p0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %10:em(s20) = G_CONSTANT i20 1
    %11:edj(s20) = G_CONSTANT i20 2
    %12:edj(s20) = G_CONSTANT i20 3
    %13:edn(s20) = G_CONSTANT i20 4
    %14:edn(s20) = G_CONSTANT i20 5
    %15:edc(s20) = G_CONSTANT i20 6
    %16:edc(s20) = G_CONSTANT i20 7
    %6:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %0:accregbank(<32 x s64>), %1:gprregbank(s32), %7:gprregbank(s32)
    %19:ptrregbank(p0), %20:modregbank(s20), %21:modregbank(s20) = G_AIE_POSTINC_3D_STORE %6, %3, %10, %11, %12, %13, %15, %14, %16 :: (store (<32 x s16>))
...
