; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --print-fixed-stack
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o - 2>&1 | FileCheck %s

%struct.v32mx9 = type <{ <8 x i32>, i32, i32 }>
%struct.v64mx9 = type <{ <16 x i32>, <2 x i32>, <2 x i32> }>
%struct.v128mx9 = type <{ <16 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> }>
%struct.v256mx9 = type { <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> }
%struct.v64mx6 = type <{ <8 x i32>, <2 x i32>, i32, i32 }>
%struct.v128mx6 = type { <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 }
%struct.v256mx6 = type { <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32, i32, i32, i32, i32 }

define void @pass_v32mx9_stack( %struct.v32mx9 %v1,  %struct.v32mx9 %v2,  %struct.v32mx9 %v3, %struct.v32mx9 %v4,  %struct.v32mx9 %v5,  %struct.v32mx9 %v6, %struct.v32mx9 %v7,  %struct.v32mx9 %v8,  %struct.v32mx9 %v9, %struct.v32mx9 %v10,  %struct.v32mx9 %v11,  %struct.v32mx9 %v12,  %struct.v32mx9 %v13,%struct.v32mx9 %va1,  %struct.v32mx9 %va2,  %struct.v32mx9 %va3, %struct.v32mx9 %va4,  %struct.v32mx9 %va5,  %struct.v32mx9 %va6, %struct.v32mx9 %va7,  %struct.v32mx9 %va8,  %struct.v32mx9 %va9, %struct.v32mx9 %va10,  %struct.v32mx9 %va11,  %struct.v32mx9 %va12) {
  ; CHECK-LABEL: name: pass_v32mx9_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -28, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -32, size: 4, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -64, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $eh1, $eh2, $eh3, $eh4, $eh5, $eh6, $eh7, $eh8, $eh9, $eh10, $eh11, $el0, $el1, $el2, $el3, $el4, $el5, $el6, $el7, $el8, $el9, $el10, $el11, $gh0, $gh1, $gh2, $gh3, $gh4, $gh5, $gh6, $gh7, $gh8, $gh9, $gh10, $gh11, $gl0, $gl1, $gl2, $gl3, $gl4, $gl5, $gl6, $gl7, $gl8, $gl9, $gl10, $gl11, $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $gl1
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s32) = COPY $el1
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(s32) = COPY $gh1
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(s32) = COPY $eh1
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(s32) = COPY $gl3
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(s32) = COPY $el3
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(s32) = COPY $gh3
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(s32) = COPY $eh3
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(s32) = COPY $gl4
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(s32) = COPY $el4
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(s32) = COPY $gh4
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(s32) = COPY $eh4
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(s32) = COPY $gl5
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(s32) = COPY $el5
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(s32) = COPY $gh5
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(s32) = COPY $eh5
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:_(s32) = COPY $gl6
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:_(s32) = COPY $el6
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:_(s32) = COPY $gh6
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:_(s32) = COPY $eh6
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:_(s32) = COPY $gl7
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:_(s32) = COPY $el7
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:_(s32) = COPY $gh7
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:_(s32) = COPY $eh7
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:_(s32) = COPY $gl8
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:_(s32) = COPY $el8
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:_(s32) = COPY $gh8
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:_(s32) = COPY $eh8
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:_(s32) = COPY $gl9
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:_(s32) = COPY $el9
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:_(s32) = COPY $gh9
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:_(s32) = COPY $eh9
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:_(s32) = COPY $gl10
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:_(s32) = COPY $el10
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:_(s32) = COPY $gh10
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]]:_(s32) = COPY $eh10
  ; CHECK-NEXT:   [[COPY66:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]]:_(s32) = COPY $gl11
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:_(s32) = COPY $el11
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:_(s32) = COPY $gh11
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:_(s32) = COPY $eh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.2, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (s32) from %fixed-stack.1, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}


define void @pass_v64mx9_stack( %struct.v64mx9 %v1,  %struct.v64mx9 %v2,  %struct.v64mx9 %v3, %struct.v64mx9 %v4,  %struct.v64mx9 %v5,  %struct.v64mx9 %v6, %struct.v64mx9 %v7,  %struct.v64mx9 %v8,  %struct.v64mx9 %v9, %struct.v64mx9 %v10,  %struct.v64mx9 %v11,  %struct.v64mx9 %v12,  %struct.v64mx9 %v13) {
  ; CHECK-LABEL: name: pass_v64mx9_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $g0, $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $g0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $e0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s32>) = COPY $x4
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $g4
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $e4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<16 x s32>) = COPY $x6
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $g6
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e6
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s32>) = COPY $x8
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<2 x s32>) = COPY $g8
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<2 x s32>) = COPY $e8
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<16 x s32>) = COPY $x10
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<2 x s32>) = COPY $g10
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<2 x s32>) = COPY $e10
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<16 x s32>) = COPY $x1
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<2 x s32>) = COPY $g1
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $e1
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<16 x s32>) = COPY $x3
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $g3
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $e3
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<16 x s32>) = COPY $x5
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<2 x s32>) = COPY $g5
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(<2 x s32>) = COPY $e5
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<16 x s32>) = COPY $x7
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(<2 x s32>) = COPY $g7
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(<2 x s32>) = COPY $e7
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(<16 x s32>) = COPY $x9
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(<2 x s32>) = COPY $g9
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<2 x s32>) = COPY $e9
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<16 x s32>) = COPY $x11
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(<2 x s32>) = COPY $g11
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(<2 x s32>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.1, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v64mx9 @ret_v64mx9_stack( %struct.v64mx9 %v1,  %struct.v64mx9 %v2,  %struct.v64mx9 %v3, %struct.v64mx9 %v4,  %struct.v64mx9 %v5,  %struct.v64mx9 %v6, %struct.v64mx9 %v7,  %struct.v64mx9 %v8,  %struct.v64mx9 %v9, %struct.v64mx9 %v10,  %struct.v64mx9 %v11,  %struct.v64mx9 %v12,  %struct.v64mx9 %v13) {
  ; CHECK-LABEL: name: ret_v64mx9_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -184, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -192, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -256, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x4
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $g4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $e4
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s32>) = COPY $x6
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $g6
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $e6
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<16 x s32>) = COPY $x8
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $g8
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e8
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s32>) = COPY $x10
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<2 x s32>) = COPY $g10
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<2 x s32>) = COPY $e10
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<16 x s32>) = COPY $x1
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<2 x s32>) = COPY $g1
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<2 x s32>) = COPY $e1
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<16 x s32>) = COPY $x3
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<2 x s32>) = COPY $g3
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $e3
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<16 x s32>) = COPY $x5
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $g5
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $e5
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<16 x s32>) = COPY $x7
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<2 x s32>) = COPY $g7
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(<2 x s32>) = COPY $e7
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<16 x s32>) = COPY $x9
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(<2 x s32>) = COPY $g9
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(<2 x s32>) = COPY $e9
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(<16 x s32>) = COPY $x11
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(<2 x s32>) = COPY $g11
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<2 x s32>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.5)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.4, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.3)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.1, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   $x0 = COPY [[LOAD]](<16 x s32>)
  ; CHECK-NEXT:   $g0 = COPY [[LOAD1]](<2 x s32>)
  ; CHECK-NEXT:   $e0 = COPY [[LOAD2]](<2 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
entry:
  ret  %struct.v64mx9 %v12
}

define void @pass_v128mx9_stack( %struct.v128mx9 %v1,  %struct.v128mx9 %v2,  %struct.v128mx9 %v3, %struct.v128mx9 %v4,  %struct.v128mx9 %v5,  %struct.v128mx9 %v6, %struct.v128mx9 %v7) {
  ; CHECK-LABEL: name: pass_v128mx9_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -40, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -48, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -192, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $g0, $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $g0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $g1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $e0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $e1
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<16 x s32>) = COPY $x3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<2 x s32>) = COPY $g3
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e3
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s32>) = COPY $x4
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<16 x s32>) = COPY $x5
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<2 x s32>) = COPY $g4
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<2 x s32>) = COPY $g5
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<2 x s32>) = COPY $e4
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<2 x s32>) = COPY $e5
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<16 x s32>) = COPY $x6
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<16 x s32>) = COPY $x7
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $g6
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<2 x s32>) = COPY $g7
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $e6
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $e7
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<16 x s32>) = COPY $x8
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<16 x s32>) = COPY $x9
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(<2 x s32>) = COPY $g8
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<2 x s32>) = COPY $g9
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(<2 x s32>) = COPY $e8
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(<2 x s32>) = COPY $e9
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(<16 x s32>) = COPY $x10
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(<16 x s32>) = COPY $x11
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<2 x s32>) = COPY $g10
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<2 x s32>) = COPY $g11
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(<2 x s32>) = COPY $e10
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(<2 x s32>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.5)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.3, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.1, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v128mx9 @ret_v128mx9_stack( %struct.v128mx9 %v1,  %struct.v128mx9 %v2,  %struct.v128mx9 %v3, %struct.v128mx9 %v4,  %struct.v128mx9 %v5,  %struct.v128mx9 %v6, %struct.v128mx9 %v7) {
  ; CHECK-LABEL: name: ret_v128mx9_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -232, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -240, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -248, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -256, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -320, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -384, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -40, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -48, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 8, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 9, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 10, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 11, type: default, offset: -192, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $g3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $e3
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<16 x s32>) = COPY $x4
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<16 x s32>) = COPY $x5
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $g4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<2 x s32>) = COPY $g5
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $e4
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e5
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s32>) = COPY $x6
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<16 x s32>) = COPY $x7
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<2 x s32>) = COPY $g6
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<2 x s32>) = COPY $g7
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<2 x s32>) = COPY $e6
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<2 x s32>) = COPY $e7
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<16 x s32>) = COPY $x8
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<16 x s32>) = COPY $x9
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $g8
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<2 x s32>) = COPY $g9
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $e8
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $e9
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<16 x s32>) = COPY $x10
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<16 x s32>) = COPY $x11
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(<2 x s32>) = COPY $g10
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<2 x s32>) = COPY $g11
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(<2 x s32>) = COPY $e10
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(<2 x s32>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.11
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.11)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.10
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.10)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.9
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.9, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.8
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.8)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.7, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.5)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX8:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX8]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.3, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX9:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD9:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX9]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX10:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD10:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX10]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.1, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX11:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD11:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX11]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   $x0 = COPY [[LOAD6]](<16 x s32>)
  ; CHECK-NEXT:   $x1 = COPY [[LOAD7]](<16 x s32>)
  ; CHECK-NEXT:   $g0 = COPY [[LOAD8]](<2 x s32>)
  ; CHECK-NEXT:   $g1 = COPY [[LOAD9]](<2 x s32>)
  ; CHECK-NEXT:   $e0 = COPY [[LOAD10]](<2 x s32>)
  ; CHECK-NEXT:   $e1 = COPY [[LOAD11]](<2 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x1, implicit $g0, implicit $g1, implicit $e0, implicit $e1
entry:
  ret  %struct.v128mx9 %v7
}

define void @pass_v256mx9_stack( %struct.v256mx9 %v1,  %struct.v256mx9 %v2,  %struct.v256mx9 %v3, %struct.v256mx9 %v4) {
  ; CHECK-LABEL: name: pass_v256mx9_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -8, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -16, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -24, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -32, size: 8, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -40, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -48, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 8, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 9, type: default, offset: -192, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 10, type: default, offset: -256, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 11, type: default, offset: -320, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $g0, $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $x0, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $g0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $g1
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $g3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $e0
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<2 x s32>) = COPY $e1
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e3
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s32>) = COPY $x4
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<16 x s32>) = COPY $x5
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<16 x s32>) = COPY $x6
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<16 x s32>) = COPY $x7
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<2 x s32>) = COPY $g4
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<2 x s32>) = COPY $g5
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<2 x s32>) = COPY $g6
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<2 x s32>) = COPY $g7
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $e4
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<2 x s32>) = COPY $e5
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $e6
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $e7
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<16 x s32>) = COPY $x8
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<16 x s32>) = COPY $x9
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(<16 x s32>) = COPY $x10
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<16 x s32>) = COPY $x11
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(<2 x s32>) = COPY $g8
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(<2 x s32>) = COPY $g9
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(<2 x s32>) = COPY $g10
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(<2 x s32>) = COPY $g11
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<2 x s32>) = COPY $e8
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<2 x s32>) = COPY $e9
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(<2 x s32>) = COPY $e10
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(<2 x s32>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.11
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.11)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.10
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.10)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.9
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.9)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.8
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.8)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.7, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.5, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX8:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX8]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.3, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX9:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD9:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX9]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX10:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD10:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX10]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.1, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX11:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD11:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX11]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v256mx9 @ret_v256mx9_stack(%struct.v256mx9 %v1,  %struct.v256mx9 %v2,  %struct.v256mx9 %v3, %struct.v256mx9 %v4) {
  ; CHECK-LABEL: name: ret_v256mx9_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -328, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -336, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -344, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -352, size: 8, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -360, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -368, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -376, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -384, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 8, type: default, offset: -448, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 9, type: default, offset: -512, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 10, type: default, offset: -576, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 11, type: default, offset: -640, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 12, type: default, offset: -8, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 13, type: default, offset: -16, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 14, type: default, offset: -24, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 15, type: default, offset: -32, size: 8, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 16, type: default, offset: -40, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 17, type: default, offset: -48, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 18, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 19, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 20, type: default, offset: -128, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 21, type: default, offset: -192, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 22, type: default, offset: -256, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 23, type: default, offset: -320, size: 64, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e4, $e5, $e6, $e7, $e8, $e9, $e10, $e11, $g4, $g5, $g6, $g7, $g8, $g9, $g10, $g11, $x4, $x5, $x6, $x7, $x8, $x9, $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x4
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x5
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x6
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x7
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $g4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $g5
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $g6
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $g7
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $e4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<2 x s32>) = COPY $e5
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $e6
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e7
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<16 x s32>) = COPY $x8
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<16 x s32>) = COPY $x9
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(<16 x s32>) = COPY $x10
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(<16 x s32>) = COPY $x11
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<2 x s32>) = COPY $g8
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<2 x s32>) = COPY $g9
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<2 x s32>) = COPY $g10
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<2 x s32>) = COPY $g11
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $e8
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<2 x s32>) = COPY $e9
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $e10
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $e11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.23
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.23)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.22
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.22)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.21
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.21)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.20
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.20)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.19
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.19, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.18
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.18)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.17
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.17, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.16
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.16)
  ; CHECK-NEXT:   [[FRAME_INDEX8:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.15
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX8]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.15, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX9:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.14
  ; CHECK-NEXT:   [[LOAD9:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX9]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.14)
  ; CHECK-NEXT:   [[FRAME_INDEX10:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.13
  ; CHECK-NEXT:   [[LOAD10:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX10]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.13, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX11:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.12
  ; CHECK-NEXT:   [[LOAD11:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX11]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.12)
  ; CHECK-NEXT:   [[FRAME_INDEX12:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.11
  ; CHECK-NEXT:   [[LOAD12:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX12]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.11)
  ; CHECK-NEXT:   [[FRAME_INDEX13:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.10
  ; CHECK-NEXT:   [[LOAD13:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX13]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.10)
  ; CHECK-NEXT:   [[FRAME_INDEX14:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.9
  ; CHECK-NEXT:   [[LOAD14:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX14]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.9)
  ; CHECK-NEXT:   [[FRAME_INDEX15:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.8
  ; CHECK-NEXT:   [[LOAD15:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[FRAME_INDEX15]](p0) :: (invariant load (<16 x s32>) from %fixed-stack.8)
  ; CHECK-NEXT:   [[FRAME_INDEX16:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD16:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX16]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.7, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX17:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD17:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX17]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX18:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD18:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX18]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.5, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX19:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD19:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX19]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX20:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD20:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX20]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.3, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX21:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD21:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX21]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX22:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD22:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX22]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.1, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX23:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD23:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX23]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.0)
  ; CHECK-NEXT:   $x0 = COPY [[LOAD12]](<16 x s32>)
  ; CHECK-NEXT:   $x1 = COPY [[LOAD13]](<16 x s32>)
  ; CHECK-NEXT:   $x2 = COPY [[LOAD14]](<16 x s32>)
  ; CHECK-NEXT:   $x3 = COPY [[LOAD15]](<16 x s32>)
  ; CHECK-NEXT:   $g0 = COPY [[LOAD16]](<2 x s32>)
  ; CHECK-NEXT:   $g1 = COPY [[LOAD17]](<2 x s32>)
  ; CHECK-NEXT:   $g2 = COPY [[LOAD18]](<2 x s32>)
  ; CHECK-NEXT:   $g3 = COPY [[LOAD19]](<2 x s32>)
  ; CHECK-NEXT:   $e0 = COPY [[LOAD20]](<2 x s32>)
  ; CHECK-NEXT:   $e1 = COPY [[LOAD21]](<2 x s32>)
  ; CHECK-NEXT:   $e2 = COPY [[LOAD22]](<2 x s32>)
  ; CHECK-NEXT:   $e3 = COPY [[LOAD23]](<2 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x1, implicit $x2, implicit $x3, implicit $g0, implicit $g1, implicit $g2, implicit $g3, implicit $e0, implicit $e1, implicit $e2, implicit $e3
entry:
  ret  %struct.v256mx9 %v4
}

define void @pass_v64mx6_stack( %struct.v64mx6 %v1,  %struct.v64mx6 %v2,  %struct.v64mx6 %v3, %struct.v64mx6 %v4,  %struct.v64mx6 %v5,  %struct.v64mx6 %v6, %struct.v64mx6 %v7,  %struct.v64mx6 %v8,  %struct.v64mx6 %v9, %struct.v64mx6 %v10,  %struct.v64mx6 %v11,  %struct.v64mx6 %v12,  %struct.v64mx6 %v13,%struct.v64mx6 %va1,  %struct.v64mx6 %va2,  %struct.v64mx6 %va3, %struct.v64mx6 %va4,  %struct.v64mx6 %va5,  %struct.v64mx6 %va6, %struct.v64mx6 %va7,  %struct.v64mx6 %va8,  %struct.v64mx6 %va9, %struct.v64mx6 %va10,  %struct.v64mx6 %va11,  %struct.v64mx6 %va12) {
  ; CHECK-LABEL: name: pass_v64mx6_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -20, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -24, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -32, size: 8, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -64, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $eh1, $eh2, $eh3, $eh4, $eh5, $eh6, $eh7, $eh8, $eh9, $eh10, $eh11, $el0, $el1, $el2, $el3, $el4, $el5, $el6, $el7, $el8, $el9, $el10, $el11, $fh0, $fh1, $fh2, $fh3, $fh4, $fh5, $fh6, $fh7, $fh8, $fh9, $fh10, $fh11, $fl0, $fl1, $fl2, $fl3, $fl4, $fl5, $fl6, $fl7, $fl8, $fl9, $fl10, $fl11, $gh0, $gh1, $gh2, $gh3, $gh4, $gh5, $gh6, $gh7, $gh8, $gh9, $gh10, $gh11, $gl0, $gl1, $gl2, $gl3, $gl4, $gl5, $gl6, $gl7, $gl8, $gl9, $gl10, $gl11, $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $fl0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $fh0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<2 x s32>) = COPY $fl2
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<2 x s32>) = COPY $fh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<2 x s32>) = COPY $fl4
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(s32) = COPY $gl4
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(s32) = COPY $el4
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<2 x s32>) = COPY $fh4
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(s32) = COPY $gh4
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(s32) = COPY $eh4
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<2 x s32>) = COPY $fl6
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(s32) = COPY $gl6
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(s32) = COPY $el6
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(<2 x s32>) = COPY $fh6
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(s32) = COPY $gh6
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(s32) = COPY $eh6
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<2 x s32>) = COPY $fl8
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(s32) = COPY $gl8
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(s32) = COPY $el8
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:_(<2 x s32>) = COPY $fh8
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:_(s32) = COPY $gh8
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:_(s32) = COPY $eh8
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:_(<2 x s32>) = COPY $fl10
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:_(s32) = COPY $gl10
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:_(s32) = COPY $el10
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:_(<2 x s32>) = COPY $fh10
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:_(s32) = COPY $gh10
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:_(s32) = COPY $eh10
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:_(<2 x s32>) = COPY $fl1
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:_(s32) = COPY $gl1
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:_(s32) = COPY $el1
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:_(<2 x s32>) = COPY $fh1
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:_(s32) = COPY $gh1
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:_(s32) = COPY $eh1
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:_(<2 x s32>) = COPY $fl3
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:_(s32) = COPY $gl3
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:_(s32) = COPY $el3
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:_(<2 x s32>) = COPY $fh3
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:_(s32) = COPY $gh3
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:_(s32) = COPY $eh3
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]]:_(<2 x s32>) = COPY $fl5
  ; CHECK-NEXT:   [[COPY66:%[0-9]+]]:_(s32) = COPY $gl5
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]]:_(s32) = COPY $el5
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:_(<2 x s32>) = COPY $fh5
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:_(s32) = COPY $gh5
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:_(s32) = COPY $eh5
  ; CHECK-NEXT:   [[COPY72:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY73:%[0-9]+]]:_(<2 x s32>) = COPY $fl7
  ; CHECK-NEXT:   [[COPY74:%[0-9]+]]:_(s32) = COPY $gl7
  ; CHECK-NEXT:   [[COPY75:%[0-9]+]]:_(s32) = COPY $el7
  ; CHECK-NEXT:   [[COPY76:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY77:%[0-9]+]]:_(<2 x s32>) = COPY $fh7
  ; CHECK-NEXT:   [[COPY78:%[0-9]+]]:_(s32) = COPY $gh7
  ; CHECK-NEXT:   [[COPY79:%[0-9]+]]:_(s32) = COPY $eh7
  ; CHECK-NEXT:   [[COPY80:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY81:%[0-9]+]]:_(<2 x s32>) = COPY $fl9
  ; CHECK-NEXT:   [[COPY82:%[0-9]+]]:_(s32) = COPY $gl9
  ; CHECK-NEXT:   [[COPY83:%[0-9]+]]:_(s32) = COPY $el9
  ; CHECK-NEXT:   [[COPY84:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY85:%[0-9]+]]:_(<2 x s32>) = COPY $fh9
  ; CHECK-NEXT:   [[COPY86:%[0-9]+]]:_(s32) = COPY $gh9
  ; CHECK-NEXT:   [[COPY87:%[0-9]+]]:_(s32) = COPY $eh9
  ; CHECK-NEXT:   [[COPY88:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY89:%[0-9]+]]:_(<2 x s32>) = COPY $fl11
  ; CHECK-NEXT:   [[COPY90:%[0-9]+]]:_(s32) = COPY $gl11
  ; CHECK-NEXT:   [[COPY91:%[0-9]+]]:_(s32) = COPY $el11
  ; CHECK-NEXT:   [[COPY92:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[COPY93:%[0-9]+]]:_(<2 x s32>) = COPY $fh11
  ; CHECK-NEXT:   [[COPY94:%[0-9]+]]:_(s32) = COPY $gh11
  ; CHECK-NEXT:   [[COPY95:%[0-9]+]]:_(s32) = COPY $eh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.3, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.2, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v128mx6_stack( %struct.v128mx6 %v1,  %struct.v128mx6 %v2,  %struct.v128mx6 %v3, %struct.v128mx6 %v4,  %struct.v128mx6 %v5,  %struct.v128mx6 %v6, %struct.v128mx6 %v7,  %struct.v128mx6 %v8,  %struct.v128mx6 %v9, %struct.v128mx6 %v10,  %struct.v128mx6 %v11,  %struct.v128mx6 %v12,  %struct.v128mx6 %v13) {
  ; CHECK-LABEL: name: pass_v128mx6_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -36, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -40, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -44, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -48, size: 4, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -96, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -128, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $eh1, $eh2, $eh3, $eh4, $eh5, $eh6, $eh7, $eh8, $eh9, $eh10, $eh11, $el0, $el1, $el2, $el3, $el4, $el5, $el6, $el7, $el8, $el9, $el10, $el11, $fh0, $fh1, $fh2, $fh3, $fh4, $fh5, $fh6, $fh7, $fh8, $fh9, $fh10, $fh11, $fl0, $fl1, $fl2, $fl3, $fl4, $fl5, $fl6, $fl7, $fl8, $fl9, $fl10, $fl11, $gh0, $gh1, $gh2, $gh3, $gh4, $gh5, $gh6, $gh7, $gh8, $gh9, $gh10, $gh11, $gl0, $gl1, $gl2, $gl3, $gl4, $gl5, $gl6, $gl7, $gl8, $gl9, $gl10, $gl11, $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $fl0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $fh0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $fl2
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $fh2
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<2 x s32>) = COPY $fl4
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<2 x s32>) = COPY $fh4
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(s32) = COPY $gl4
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(s32) = COPY $gh4
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(s32) = COPY $el4
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(s32) = COPY $eh4
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(<2 x s32>) = COPY $fl6
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<2 x s32>) = COPY $fh6
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(s32) = COPY $gl6
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(s32) = COPY $gh6
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(s32) = COPY $el6
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(s32) = COPY $eh6
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(<2 x s32>) = COPY $fl8
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(<2 x s32>) = COPY $fh8
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:_(s32) = COPY $gl8
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:_(s32) = COPY $gh8
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:_(s32) = COPY $el8
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:_(s32) = COPY $eh8
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:_(<2 x s32>) = COPY $fl10
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:_(<2 x s32>) = COPY $fh10
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:_(s32) = COPY $gl10
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:_(s32) = COPY $gh10
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:_(s32) = COPY $el10
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:_(s32) = COPY $eh10
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:_(<2 x s32>) = COPY $fl1
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:_(<2 x s32>) = COPY $fh1
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:_(s32) = COPY $gl1
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:_(s32) = COPY $gh1
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:_(s32) = COPY $el1
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:_(s32) = COPY $eh1
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:_(<2 x s32>) = COPY $fl3
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:_(<2 x s32>) = COPY $fh3
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:_(s32) = COPY $gl3
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:_(s32) = COPY $gh3
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:_(s32) = COPY $el3
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:_(s32) = COPY $eh3
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY66:%[0-9]+]]:_(<2 x s32>) = COPY $fl5
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]]:_(<2 x s32>) = COPY $fh5
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:_(s32) = COPY $gl5
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:_(s32) = COPY $gh5
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:_(s32) = COPY $el5
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:_(s32) = COPY $eh5
  ; CHECK-NEXT:   [[COPY72:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY73:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY74:%[0-9]+]]:_(<2 x s32>) = COPY $fl7
  ; CHECK-NEXT:   [[COPY75:%[0-9]+]]:_(<2 x s32>) = COPY $fh7
  ; CHECK-NEXT:   [[COPY76:%[0-9]+]]:_(s32) = COPY $gl7
  ; CHECK-NEXT:   [[COPY77:%[0-9]+]]:_(s32) = COPY $gh7
  ; CHECK-NEXT:   [[COPY78:%[0-9]+]]:_(s32) = COPY $el7
  ; CHECK-NEXT:   [[COPY79:%[0-9]+]]:_(s32) = COPY $eh7
  ; CHECK-NEXT:   [[COPY80:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY81:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY82:%[0-9]+]]:_(<2 x s32>) = COPY $fl9
  ; CHECK-NEXT:   [[COPY83:%[0-9]+]]:_(<2 x s32>) = COPY $fh9
  ; CHECK-NEXT:   [[COPY84:%[0-9]+]]:_(s32) = COPY $gl9
  ; CHECK-NEXT:   [[COPY85:%[0-9]+]]:_(s32) = COPY $gh9
  ; CHECK-NEXT:   [[COPY86:%[0-9]+]]:_(s32) = COPY $el9
  ; CHECK-NEXT:   [[COPY87:%[0-9]+]]:_(s32) = COPY $eh9
  ; CHECK-NEXT:   [[COPY88:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY89:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[COPY90:%[0-9]+]]:_(<2 x s32>) = COPY $fl11
  ; CHECK-NEXT:   [[COPY91:%[0-9]+]]:_(<2 x s32>) = COPY $fh11
  ; CHECK-NEXT:   [[COPY92:%[0-9]+]]:_(s32) = COPY $gl11
  ; CHECK-NEXT:   [[COPY93:%[0-9]+]]:_(s32) = COPY $gh11
  ; CHECK-NEXT:   [[COPY94:%[0-9]+]]:_(s32) = COPY $el11
  ; CHECK-NEXT:   [[COPY95:%[0-9]+]]:_(s32) = COPY $eh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.7, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.5, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (s32) from %fixed-stack.3, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (s32) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v128mx6 @ret_v128mx6_stack( %struct.v128mx6 %v1,  %struct.v128mx6 %v2,  %struct.v128mx6 %v3, %struct.v128mx6 %v4,  %struct.v128mx6 %v5,  %struct.v128mx6 %v6, %struct.v128mx6 %v7,  %struct.v128mx6 %v8,  %struct.v128mx6 %v9, %struct.v128mx6 %v10,  %struct.v128mx6 %v11,  %struct.v128mx6 %v12,  %struct.v128mx6 %v13) {
  ; CHECK-LABEL: name: ret_v128mx6_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -164, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -168, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -172, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -176, size: 4, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -184, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -192, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -224, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -256, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 8, type: default, offset: -36, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 9, type: default, offset: -40, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 10, type: default, offset: -44, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 11, type: default, offset: -48, size: 4, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 12, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 13, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 14, type: default, offset: -96, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 15, type: default, offset: -128, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh1, $eh2, $eh3, $eh4, $eh5, $eh6, $eh7, $eh8, $eh9, $eh10, $eh11, $el1, $el2, $el3, $el4, $el5, $el6, $el7, $el8, $el9, $el10, $el11, $fh1, $fh2, $fh3, $fh4, $fh5, $fh6, $fh7, $fh8, $fh9, $fh10, $fh11, $fl1, $fl2, $fl3, $fl4, $fl5, $fl6, $fl7, $fl8, $fl9, $fl10, $fl11, $gh1, $gh2, $gh3, $gh4, $gh5, $gh6, $gh7, $gh8, $gh9, $gh10, $gh11, $gl1, $gl2, $gl3, $gl4, $gl5, $gl6, $gl7, $gl8, $gl9, $gl10, $gl11, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $fl2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $fh2
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $fl4
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $fh4
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(s32) = COPY $gl4
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s32) = COPY $gh4
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $el4
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s32) = COPY $eh4
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<2 x s32>) = COPY $fl6
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<2 x s32>) = COPY $fh6
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(s32) = COPY $gl6
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(s32) = COPY $gh6
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(s32) = COPY $el6
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(s32) = COPY $eh6
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(<2 x s32>) = COPY $fl8
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(<2 x s32>) = COPY $fh8
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(s32) = COPY $gl8
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(s32) = COPY $gh8
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(s32) = COPY $el8
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(s32) = COPY $eh8
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(<2 x s32>) = COPY $fl10
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(<2 x s32>) = COPY $fh10
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:_(s32) = COPY $gl10
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:_(s32) = COPY $gh10
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:_(s32) = COPY $el10
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:_(s32) = COPY $eh10
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:_(<2 x s32>) = COPY $fl1
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:_(<2 x s32>) = COPY $fh1
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:_(s32) = COPY $gl1
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:_(s32) = COPY $gh1
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:_(s32) = COPY $el1
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:_(s32) = COPY $eh1
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:_(<2 x s32>) = COPY $fl3
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:_(<2 x s32>) = COPY $fh3
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:_(s32) = COPY $gl3
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:_(s32) = COPY $gh3
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:_(s32) = COPY $el3
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:_(s32) = COPY $eh3
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:_(<2 x s32>) = COPY $fl5
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:_(<2 x s32>) = COPY $fh5
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:_(s32) = COPY $gl5
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:_(s32) = COPY $gh5
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:_(s32) = COPY $el5
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:_(s32) = COPY $eh5
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY66:%[0-9]+]]:_(<2 x s32>) = COPY $fl7
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]]:_(<2 x s32>) = COPY $fh7
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:_(s32) = COPY $gl7
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:_(s32) = COPY $gh7
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:_(s32) = COPY $el7
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:_(s32) = COPY $eh7
  ; CHECK-NEXT:   [[COPY72:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY73:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY74:%[0-9]+]]:_(<2 x s32>) = COPY $fl9
  ; CHECK-NEXT:   [[COPY75:%[0-9]+]]:_(<2 x s32>) = COPY $fh9
  ; CHECK-NEXT:   [[COPY76:%[0-9]+]]:_(s32) = COPY $gl9
  ; CHECK-NEXT:   [[COPY77:%[0-9]+]]:_(s32) = COPY $gh9
  ; CHECK-NEXT:   [[COPY78:%[0-9]+]]:_(s32) = COPY $el9
  ; CHECK-NEXT:   [[COPY79:%[0-9]+]]:_(s32) = COPY $eh9
  ; CHECK-NEXT:   [[COPY80:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY81:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[COPY82:%[0-9]+]]:_(<2 x s32>) = COPY $fl11
  ; CHECK-NEXT:   [[COPY83:%[0-9]+]]:_(<2 x s32>) = COPY $fh11
  ; CHECK-NEXT:   [[COPY84:%[0-9]+]]:_(s32) = COPY $gl11
  ; CHECK-NEXT:   [[COPY85:%[0-9]+]]:_(s32) = COPY $gh11
  ; CHECK-NEXT:   [[COPY86:%[0-9]+]]:_(s32) = COPY $el11
  ; CHECK-NEXT:   [[COPY87:%[0-9]+]]:_(s32) = COPY $eh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.15
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.15, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.14
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.14)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.13
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.13, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.12
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.12)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.11
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (s32) from %fixed-stack.11, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.10
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (s32) from %fixed-stack.10)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.9
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (s32) from %fixed-stack.9, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.8
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (s32) from %fixed-stack.8)
  ; CHECK-NEXT:   [[FRAME_INDEX8:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX8]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.7, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX9:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD9:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX9]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX10:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD10:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX10]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.5, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX11:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD11:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX11]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX12:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX12]](p0) :: (invariant load (s32) from %fixed-stack.3, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX13:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX13]](p0) :: (invariant load (s32) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX14:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX14]](p0) :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX15:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX15]](p0) :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   $wl0 = COPY [[LOAD]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[LOAD1]](<8 x s32>)
  ; CHECK-NEXT:   $fl0 = COPY [[LOAD2]](<2 x s32>)
  ; CHECK-NEXT:   $fh0 = COPY [[LOAD3]](<2 x s32>)
  ; CHECK-NEXT:   $gl0 = COPY [[LOAD4]](s32)
  ; CHECK-NEXT:   $gh0 = COPY [[LOAD5]](s32)
  ; CHECK-NEXT:   $el0 = COPY [[LOAD6]](s32)
  ; CHECK-NEXT:   $eh0 = COPY [[LOAD7]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0
entry:
  ret  %struct.v128mx6 %v12
}

define void @pass_v256mx6_stack( %struct.v256mx6 %v1,  %struct.v256mx6 %v2,  %struct.v256mx6 %v3, %struct.v256mx6 %v4,  %struct.v256mx6 %v5,  %struct.v256mx6 %v6,  %struct.v256mx6 %v7) {
  ; CHECK-LABEL: name: pass_v256mx6_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -4, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -8, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -12, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -16, size: 4, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -20, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -24, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -28, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -32, size: 4, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 8, type: default, offset: -40, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 9, type: default, offset: -48, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 10, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 11, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 12, type: default, offset: -96, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 13, type: default, offset: -128, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 14, type: default, offset: -160, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 15, type: default, offset: -192, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $eh1, $eh2, $eh3, $eh4, $eh5, $eh6, $eh7, $eh8, $eh9, $eh10, $eh11, $el0, $el1, $el2, $el3, $el4, $el5, $el6, $el7, $el8, $el9, $el10, $el11, $fh0, $fh1, $fh2, $fh3, $fh4, $fh5, $fh6, $fh7, $fh8, $fh9, $fh10, $fh11, $fl0, $fl1, $fl2, $fl3, $fl4, $fl5, $fl6, $fl7, $fl8, $fl9, $fl10, $fl11, $gh0, $gh1, $gh2, $gh3, $gh4, $gh5, $gh6, $gh7, $gh8, $gh9, $gh10, $gh11, $gl0, $gl1, $gl2, $gl3, $gl4, $gl5, $gl6, $gl7, $gl8, $gl9, $gl10, $gl11, $wh0, $wh1, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl0, $wl1, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $fl0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $fh0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $fl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $fh1
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(s32) = COPY $gl1
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(s32) = COPY $gh1
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $el1
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s32) = COPY $eh1
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $fl2
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<2 x s32>) = COPY $fh2
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $fl3
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $fh3
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(s32) = COPY $gl3
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(s32) = COPY $gh3
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(s32) = COPY $el3
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(s32) = COPY $eh3
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:_(<2 x s32>) = COPY $fl4
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:_(<2 x s32>) = COPY $fh4
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:_(<2 x s32>) = COPY $fl5
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:_(<2 x s32>) = COPY $fh5
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:_(s32) = COPY $gl4
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:_(s32) = COPY $gh4
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:_(s32) = COPY $gl5
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:_(s32) = COPY $gh5
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:_(s32) = COPY $el4
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:_(s32) = COPY $eh4
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:_(s32) = COPY $el5
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:_(s32) = COPY $eh5
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:_(<2 x s32>) = COPY $fl6
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:_(<2 x s32>) = COPY $fh6
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:_(<2 x s32>) = COPY $fl7
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:_(<2 x s32>) = COPY $fh7
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:_(s32) = COPY $gl6
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:_(s32) = COPY $gh6
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:_(s32) = COPY $gl7
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:_(s32) = COPY $gh7
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:_(s32) = COPY $el6
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:_(s32) = COPY $eh6
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:_(s32) = COPY $el7
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:_(s32) = COPY $eh7
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY66:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:_(<2 x s32>) = COPY $fl8
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:_(<2 x s32>) = COPY $fh8
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:_(<2 x s32>) = COPY $fl9
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:_(<2 x s32>) = COPY $fh9
  ; CHECK-NEXT:   [[COPY72:%[0-9]+]]:_(s32) = COPY $gl8
  ; CHECK-NEXT:   [[COPY73:%[0-9]+]]:_(s32) = COPY $gh8
  ; CHECK-NEXT:   [[COPY74:%[0-9]+]]:_(s32) = COPY $gl9
  ; CHECK-NEXT:   [[COPY75:%[0-9]+]]:_(s32) = COPY $gh9
  ; CHECK-NEXT:   [[COPY76:%[0-9]+]]:_(s32) = COPY $el8
  ; CHECK-NEXT:   [[COPY77:%[0-9]+]]:_(s32) = COPY $eh8
  ; CHECK-NEXT:   [[COPY78:%[0-9]+]]:_(s32) = COPY $el9
  ; CHECK-NEXT:   [[COPY79:%[0-9]+]]:_(s32) = COPY $eh9
  ; CHECK-NEXT:   [[COPY80:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY81:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY82:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY83:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[COPY84:%[0-9]+]]:_(<2 x s32>) = COPY $fl10
  ; CHECK-NEXT:   [[COPY85:%[0-9]+]]:_(<2 x s32>) = COPY $fh10
  ; CHECK-NEXT:   [[COPY86:%[0-9]+]]:_(<2 x s32>) = COPY $fl11
  ; CHECK-NEXT:   [[COPY87:%[0-9]+]]:_(<2 x s32>) = COPY $fh11
  ; CHECK-NEXT:   [[COPY88:%[0-9]+]]:_(s32) = COPY $gl10
  ; CHECK-NEXT:   [[COPY89:%[0-9]+]]:_(s32) = COPY $gh10
  ; CHECK-NEXT:   [[COPY90:%[0-9]+]]:_(s32) = COPY $gl11
  ; CHECK-NEXT:   [[COPY91:%[0-9]+]]:_(s32) = COPY $gh11
  ; CHECK-NEXT:   [[COPY92:%[0-9]+]]:_(s32) = COPY $el10
  ; CHECK-NEXT:   [[COPY93:%[0-9]+]]:_(s32) = COPY $eh10
  ; CHECK-NEXT:   [[COPY94:%[0-9]+]]:_(s32) = COPY $el11
  ; CHECK-NEXT:   [[COPY95:%[0-9]+]]:_(s32) = COPY $eh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.15
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.15, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.14
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.14)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.13
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.13, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.12
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.12)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.11
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.11, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.10
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.10)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.9
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.9, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.8
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.8)
  ; CHECK-NEXT:   [[FRAME_INDEX8:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX8]](p0) :: (invariant load (s32) from %fixed-stack.7, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX9:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX9]](p0) :: (invariant load (s32) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX10:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX10]](p0) :: (invariant load (s32) from %fixed-stack.5, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX11:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX11]](p0) :: (invariant load (s32) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX12:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX12]](p0) :: (invariant load (s32) from %fixed-stack.3, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX13:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX13]](p0) :: (invariant load (s32) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX14:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX14]](p0) :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX15:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX15]](p0) :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v256mx6 @ret_v256mx6_stack( %struct.v256mx6 %v1,  %struct.v256mx6 %v2,  %struct.v256mx6 %v3, %struct.v256mx6 %v4,  %struct.v256mx6 %v5,  %struct.v256mx6 %v6,  %struct.v256mx6 %v7) {
  ; CHECK-LABEL: name: ret_v256mx6_stack
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: -196, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: -200, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 2, type: default, offset: -204, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 3, type: default, offset: -208, size: 4, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 4, type: default, offset: -212, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 5, type: default, offset: -216, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 6, type: default, offset: -220, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 7, type: default, offset: -224, size: 4, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 8, type: default, offset: -232, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 9, type: default, offset: -240, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 10, type: default, offset: -248, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 11, type: default, offset: -256, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 12, type: default, offset: -288, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 13, type: default, offset: -320, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 14, type: default, offset: -352, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 15, type: default, offset: -384, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 16, type: default, offset: -4, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 17, type: default, offset: -8, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 18, type: default, offset: -12, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 19, type: default, offset: -16, size: 4, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 20, type: default, offset: -20, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 21, type: default, offset: -24, size: 4, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 22, type: default, offset: -28, size: 4, alignment: 4, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 23, type: default, offset: -32, size: 4, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 24, type: default, offset: -40, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 25, type: default, offset: -48, size: 8, alignment: 16, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 26, type: default, offset: -56, size: 8, alignment: 8, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 27, type: default, offset: -64, size: 8, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 28, type: default, offset: -96, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 29, type: default, offset: -128, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 30, type: default, offset: -160, size: 32, alignment: 32, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 31, type: default, offset: -192, size: 32, alignment: 64, stack-id: default, 
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true, 
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh2, $eh3, $eh4, $eh5, $eh6, $eh7, $eh8, $eh9, $eh10, $eh11, $el2, $el3, $el4, $el5, $el6, $el7, $el8, $el9, $el10, $el11, $fh2, $fh3, $fh4, $fh5, $fh6, $fh7, $fh8, $fh9, $fh10, $fh11, $fl2, $fl3, $fl4, $fl5, $fl6, $fl7, $fl8, $fl9, $fl10, $fl11, $gh2, $gh3, $gh4, $gh5, $gh6, $gh7, $gh8, $gh9, $gh10, $gh11, $gl2, $gl3, $gl4, $gl5, $gl6, $gl7, $gl8, $gl9, $gl10, $gl11, $wh2, $wh3, $wh4, $wh5, $wh6, $wh7, $wh8, $wh9, $wh10, $wh11, $wl2, $wl3, $wl4, $wl5, $wl6, $wl7, $wl8, $wl9, $wl10, $wl11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $fl2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $fh2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $fl3
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $fh3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(s32) = COPY $gl3
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(s32) = COPY $gh3
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $el3
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s32) = COPY $eh3
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(<8 x s32>) = COPY $wl4
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(<8 x s32>) = COPY $wh4
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:_(<8 x s32>) = COPY $wl5
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:_(<8 x s32>) = COPY $wh5
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:_(<2 x s32>) = COPY $fl4
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:_(<2 x s32>) = COPY $fh4
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:_(<2 x s32>) = COPY $fl5
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:_(<2 x s32>) = COPY $fh5
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:_(s32) = COPY $gl4
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:_(s32) = COPY $gh4
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:_(s32) = COPY $gl5
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:_(s32) = COPY $gh5
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:_(s32) = COPY $el4
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:_(s32) = COPY $eh4
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:_(s32) = COPY $el5
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:_(s32) = COPY $eh5
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:_(<8 x s32>) = COPY $wl6
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:_(<8 x s32>) = COPY $wh6
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:_(<8 x s32>) = COPY $wl7
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:_(<8 x s32>) = COPY $wh7
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:_(<2 x s32>) = COPY $fl6
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:_(<2 x s32>) = COPY $fh6
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:_(<2 x s32>) = COPY $fl7
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:_(<2 x s32>) = COPY $fh7
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:_(s32) = COPY $gl6
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:_(s32) = COPY $gh6
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:_(s32) = COPY $gl7
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:_(s32) = COPY $gh7
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:_(s32) = COPY $el6
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:_(s32) = COPY $eh6
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:_(s32) = COPY $el7
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:_(s32) = COPY $eh7
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:_(<8 x s32>) = COPY $wl8
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:_(<8 x s32>) = COPY $wh8
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:_(<8 x s32>) = COPY $wl9
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:_(<8 x s32>) = COPY $wh9
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:_(<2 x s32>) = COPY $fl8
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:_(<2 x s32>) = COPY $fh8
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:_(<2 x s32>) = COPY $fl9
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:_(<2 x s32>) = COPY $fh9
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:_(s32) = COPY $gl8
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:_(s32) = COPY $gh8
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:_(s32) = COPY $gl9
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:_(s32) = COPY $gh9
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:_(s32) = COPY $el8
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:_(s32) = COPY $eh8
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:_(s32) = COPY $el9
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:_(s32) = COPY $eh9
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:_(<8 x s32>) = COPY $wl10
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]]:_(<8 x s32>) = COPY $wh10
  ; CHECK-NEXT:   [[COPY66:%[0-9]+]]:_(<8 x s32>) = COPY $wl11
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]]:_(<8 x s32>) = COPY $wh11
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:_(<2 x s32>) = COPY $fl10
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:_(<2 x s32>) = COPY $fh10
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:_(<2 x s32>) = COPY $fl11
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:_(<2 x s32>) = COPY $fh11
  ; CHECK-NEXT:   [[COPY72:%[0-9]+]]:_(s32) = COPY $gl10
  ; CHECK-NEXT:   [[COPY73:%[0-9]+]]:_(s32) = COPY $gh10
  ; CHECK-NEXT:   [[COPY74:%[0-9]+]]:_(s32) = COPY $gl11
  ; CHECK-NEXT:   [[COPY75:%[0-9]+]]:_(s32) = COPY $gh11
  ; CHECK-NEXT:   [[COPY76:%[0-9]+]]:_(s32) = COPY $el10
  ; CHECK-NEXT:   [[COPY77:%[0-9]+]]:_(s32) = COPY $eh10
  ; CHECK-NEXT:   [[COPY78:%[0-9]+]]:_(s32) = COPY $el11
  ; CHECK-NEXT:   [[COPY79:%[0-9]+]]:_(s32) = COPY $eh11
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.31
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.31, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.30
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.30)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.29
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.29, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.28
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX3]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.28)
  ; CHECK-NEXT:   [[FRAME_INDEX4:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.27
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX4]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.27, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX5:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.26
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX5]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.26)
  ; CHECK-NEXT:   [[FRAME_INDEX6:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.25
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX6]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.25, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX7:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.24
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX7]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.24)
  ; CHECK-NEXT:   [[FRAME_INDEX8:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.23
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX8]](p0) :: (invariant load (s32) from %fixed-stack.23, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX9:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.22
  ; CHECK-NEXT:   [[LOAD9:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX9]](p0) :: (invariant load (s32) from %fixed-stack.22)
  ; CHECK-NEXT:   [[FRAME_INDEX10:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.21
  ; CHECK-NEXT:   [[LOAD10:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX10]](p0) :: (invariant load (s32) from %fixed-stack.21, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX11:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.20
  ; CHECK-NEXT:   [[LOAD11:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX11]](p0) :: (invariant load (s32) from %fixed-stack.20)
  ; CHECK-NEXT:   [[FRAME_INDEX12:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.19
  ; CHECK-NEXT:   [[LOAD12:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX12]](p0) :: (invariant load (s32) from %fixed-stack.19, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX13:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.18
  ; CHECK-NEXT:   [[LOAD13:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX13]](p0) :: (invariant load (s32) from %fixed-stack.18)
  ; CHECK-NEXT:   [[FRAME_INDEX14:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.17
  ; CHECK-NEXT:   [[LOAD14:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX14]](p0) :: (invariant load (s32) from %fixed-stack.17, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX15:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.16
  ; CHECK-NEXT:   [[LOAD15:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX15]](p0) :: (invariant load (s32) from %fixed-stack.16)
  ; CHECK-NEXT:   [[FRAME_INDEX16:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.15
  ; CHECK-NEXT:   [[LOAD16:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX16]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.15, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX17:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.14
  ; CHECK-NEXT:   [[LOAD17:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX17]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.14)
  ; CHECK-NEXT:   [[FRAME_INDEX18:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.13
  ; CHECK-NEXT:   [[LOAD18:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX18]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.13, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX19:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.12
  ; CHECK-NEXT:   [[LOAD19:%[0-9]+]]:_(<8 x s32>) = G_LOAD [[FRAME_INDEX19]](p0) :: (invariant load (<8 x s32>) from %fixed-stack.12)
  ; CHECK-NEXT:   [[FRAME_INDEX20:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.11
  ; CHECK-NEXT:   [[LOAD20:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX20]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.11, align 64)
  ; CHECK-NEXT:   [[FRAME_INDEX21:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.10
  ; CHECK-NEXT:   [[LOAD21:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX21]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.10)
  ; CHECK-NEXT:   [[FRAME_INDEX22:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.9
  ; CHECK-NEXT:   [[LOAD22:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX22]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.9, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX23:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.8
  ; CHECK-NEXT:   [[LOAD23:%[0-9]+]]:_(<2 x s32>) = G_LOAD [[FRAME_INDEX23]](p0) :: (invariant load (<2 x s32>) from %fixed-stack.8)
  ; CHECK-NEXT:   [[FRAME_INDEX24:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.7
  ; CHECK-NEXT:   [[LOAD24:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX24]](p0) :: (invariant load (s32) from %fixed-stack.7, align 32)
  ; CHECK-NEXT:   [[FRAME_INDEX25:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.6
  ; CHECK-NEXT:   [[LOAD25:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX25]](p0) :: (invariant load (s32) from %fixed-stack.6)
  ; CHECK-NEXT:   [[FRAME_INDEX26:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.5
  ; CHECK-NEXT:   [[LOAD26:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX26]](p0) :: (invariant load (s32) from %fixed-stack.5, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX27:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.4
  ; CHECK-NEXT:   [[LOAD27:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX27]](p0) :: (invariant load (s32) from %fixed-stack.4)
  ; CHECK-NEXT:   [[FRAME_INDEX28:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.3
  ; CHECK-NEXT:   [[LOAD28:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX28]](p0) :: (invariant load (s32) from %fixed-stack.3, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX29:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD29:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX29]](p0) :: (invariant load (s32) from %fixed-stack.2)
  ; CHECK-NEXT:   [[FRAME_INDEX30:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD30:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX30]](p0) :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX31:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD31:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX31]](p0) :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   $wl0 = COPY [[LOAD16]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[LOAD17]](<8 x s32>)
  ; CHECK-NEXT:   $wl1 = COPY [[LOAD18]](<8 x s32>)
  ; CHECK-NEXT:   $wh1 = COPY [[LOAD19]](<8 x s32>)
  ; CHECK-NEXT:   $fl0 = COPY [[LOAD20]](<2 x s32>)
  ; CHECK-NEXT:   $fh0 = COPY [[LOAD21]](<2 x s32>)
  ; CHECK-NEXT:   $fl1 = COPY [[LOAD22]](<2 x s32>)
  ; CHECK-NEXT:   $fh1 = COPY [[LOAD23]](<2 x s32>)
  ; CHECK-NEXT:   $gl0 = COPY [[LOAD24]](s32)
  ; CHECK-NEXT:   $gh0 = COPY [[LOAD25]](s32)
  ; CHECK-NEXT:   $gl1 = COPY [[LOAD26]](s32)
  ; CHECK-NEXT:   $gh1 = COPY [[LOAD27]](s32)
  ; CHECK-NEXT:   $el0 = COPY [[LOAD28]](s32)
  ; CHECK-NEXT:   $eh0 = COPY [[LOAD29]](s32)
  ; CHECK-NEXT:   $el1 = COPY [[LOAD30]](s32)
  ; CHECK-NEXT:   $eh1 = COPY [[LOAD31]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $wl1, implicit $wh1, implicit $fl0, implicit $fh0, implicit $fl1, implicit $fh1, implicit $gl0, implicit $gh0, implicit $gl1, implicit $gh1, implicit $el0, implicit $eh0, implicit $el1, implicit $eh1
entry:
  ret  %struct.v256mx6 %v7
}

