; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --print-fixed-stack
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o - 2>&1 | FileCheck %s

%struct.v32mx9 = type <{ <8 x i32>, i32, i32 }>
%struct.v64mx9 = type <{ <16 x i32>, <2 x i32>, <2 x i32> }>
%struct.v128mx9 = type <{ <16 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> }>
%struct.v256mx9 = type { <16 x i32>, <16 x i32>, <16 x i32>, <16 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> }
%struct.v64mx6 = type <{ <8 x i32>, <2 x i32>, i32, i32 }>
%struct.v128mx6 = type { <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 }
%struct.v256mx6 = type { <8 x i32>, <8 x i32>, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32, i32, i32, i32, i32 }


define void @pass_v32mx9(%struct.v32mx9 %v1) {
  ; CHECK-LABEL: name: pass_v32mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $el0, $gl0, $wl0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v64mx9(%struct.v64mx9 %v1) {
  ; CHECK-LABEL: name: pass_v64mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $g0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $g0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $e0
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v128mx9(%struct.v128mx9 %v1) {
  ; CHECK-LABEL: name: pass_v128mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $g0, $g1, $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $g0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $g1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $e0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $e1
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v256mx9(%struct.v256mx9 %v1) {
  ; CHECK-LABEL: name: pass_v256mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e0, $e1, $e2, $e3, $g0, $g1, $g2, $g3, $x0, $x1, $x2, $x3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $g0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $g1
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $g3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $e0
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<2 x s32>) = COPY $e1
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e3
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v32mx9 @ret_v32mx9(%struct.v32mx9 %v1) {
  ; CHECK-LABEL: name: ret_v32mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $gh0, $wh0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   $wl0 = COPY [[COPY]](<8 x s32>)
  ; CHECK-NEXT:   $gl0 = COPY [[COPY1]](s32)
  ; CHECK-NEXT:   $el0 = COPY [[COPY2]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0, implicit $gl0, implicit $el0
entry:
  ret %struct.v32mx9 %v1
}

define %struct.v64mx9 @ret_v64mx9(%struct.v64mx9 %v1) {
  ; CHECK-LABEL: name: ret_v64mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e2, $g2, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<16 x s32>)
  ; CHECK-NEXT:   $g0 = COPY [[COPY1]](<2 x s32>)
  ; CHECK-NEXT:   $e0 = COPY [[COPY2]](<2 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $g0, implicit $e0
entry:
  ret %struct.v64mx9 %v1
}

define %struct.v128mx9 @ret_v128mx9(%struct.v128mx9 %v1) {
  ; CHECK-LABEL: name: ret_v128mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e2, $e3, $g2, $g3, $x2, $x3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $g2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $g3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $e2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $e3
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<16 x s32>)
  ; CHECK-NEXT:   $x1 = COPY [[COPY1]](<16 x s32>)
  ; CHECK-NEXT:   $g0 = COPY [[COPY2]](<2 x s32>)
  ; CHECK-NEXT:   $g1 = COPY [[COPY3]](<2 x s32>)
  ; CHECK-NEXT:   $e0 = COPY [[COPY4]](<2 x s32>)
  ; CHECK-NEXT:   $e1 = COPY [[COPY5]](<2 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x1, implicit $g0, implicit $g1, implicit $e0, implicit $e1
entry:
  ret %struct.v128mx9 %v1
}

define %struct.v256mx9 @ret_v256mx9(%struct.v256mx9 %v1) {
  ; CHECK-LABEL: name: ret_v256mx9
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $e4, $e5, $e6, $e7, $g4, $g5, $g6, $g7, $x4, $x5, $x6, $x7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x4
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x5
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x6
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<16 x s32>) = COPY $x7
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $g4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $g5
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $g6
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $g7
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<2 x s32>) = COPY $e4
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<2 x s32>) = COPY $e5
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<2 x s32>) = COPY $e6
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<2 x s32>) = COPY $e7
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<16 x s32>)
  ; CHECK-NEXT:   $x1 = COPY [[COPY1]](<16 x s32>)
  ; CHECK-NEXT:   $x2 = COPY [[COPY2]](<16 x s32>)
  ; CHECK-NEXT:   $x3 = COPY [[COPY3]](<16 x s32>)
  ; CHECK-NEXT:   $g0 = COPY [[COPY4]](<2 x s32>)
  ; CHECK-NEXT:   $g1 = COPY [[COPY5]](<2 x s32>)
  ; CHECK-NEXT:   $g2 = COPY [[COPY6]](<2 x s32>)
  ; CHECK-NEXT:   $g3 = COPY [[COPY7]](<2 x s32>)
  ; CHECK-NEXT:   $e0 = COPY [[COPY8]](<2 x s32>)
  ; CHECK-NEXT:   $e1 = COPY [[COPY9]](<2 x s32>)
  ; CHECK-NEXT:   $e2 = COPY [[COPY10]](<2 x s32>)
  ; CHECK-NEXT:   $e3 = COPY [[COPY11]](<2 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x1, implicit $x2, implicit $x3, implicit $g0, implicit $g1, implicit $g2, implicit $g3, implicit $e0, implicit $e1, implicit $e2, implicit $e3
entry:
  ret %struct.v256mx9 %v1
}

define void @pass_v64mx6(%struct.v64mx6 %v1) {
  ; CHECK-LABEL: name: pass_v64mx6
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $el0, $fl0, $gl0, $wl0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $fl0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v128mx6(%struct.v128mx6 %v1) {
  ; CHECK-LABEL: name: pass_v128mx6
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $el0, $fh0, $fl0, $gh0, $gl0, $wh0, $wl0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $fl0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $fh0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define void @pass_v256mx6(%struct.v256mx6 %v1) {
  ; CHECK-LABEL: name: pass_v256mx6
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $eh1, $el0, $el1, $fh0, $fh1, $fl0, $fl1, $gh0, $gh1, $gl0, $gl1, $wh0, $wh1, $wl0, $wl1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY $wh1
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $fl0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $fh0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $fl1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $fh1
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s32) = COPY $gl0
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(s32) = COPY $gl1
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(s32) = COPY $gh1
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(s32) = COPY $el0
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $el1
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s32) = COPY $eh1
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  ret void
}

define %struct.v64mx6 @ret_v64mx6(%struct.v64mx6 %v1) {
  ; CHECK-LABEL: name: ret_v64mx6
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh0, $fh0, $gh0, $wh0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $fh0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $gh0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $eh0
  ; CHECK-NEXT:   $wl0 = COPY [[COPY]](<8 x s32>)
  ; CHECK-NEXT:   $fl0 = COPY [[COPY1]](<2 x s32>)
  ; CHECK-NEXT:   $gl0 = COPY [[COPY2]](s32)
  ; CHECK-NEXT:   $el0 = COPY [[COPY3]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0, implicit $fl0, implicit $gl0, implicit $el0
entry:
  ret %struct.v64mx6 %v1
}

define %struct.v128mx6 @ret_v128mx6(%struct.v128mx6 %v1) {
  ; CHECK-LABEL: name: ret_v128mx6
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh2, $el2, $fh2, $fl2, $gh2, $gl2, $wh2, $wl2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<2 x s32>) = COPY $fl2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<2 x s32>) = COPY $fh2
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   $wl0 = COPY [[COPY]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[COPY1]](<8 x s32>)
  ; CHECK-NEXT:   $fl0 = COPY [[COPY2]](<2 x s32>)
  ; CHECK-NEXT:   $fh0 = COPY [[COPY3]](<2 x s32>)
  ; CHECK-NEXT:   $gl0 = COPY [[COPY4]](s32)
  ; CHECK-NEXT:   $gh0 = COPY [[COPY5]](s32)
  ; CHECK-NEXT:   $el0 = COPY [[COPY6]](s32)
  ; CHECK-NEXT:   $eh0 = COPY [[COPY7]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $fl0, implicit $fh0, implicit $gl0, implicit $gh0, implicit $el0, implicit $eh0
entry:
  ret %struct.v128mx6 %v1
}

define %struct.v256mx6 @ret_v256mx6(%struct.v256mx6 %v1) {
  ; CHECK-LABEL: name: ret_v256mx6
  ; CHECK: fixedStack:
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $eh2, $eh3, $el2, $el3, $fh2, $fh3, $fl2, $fl3, $gh2, $gh3, $gl2, $gl3, $wh2, $wh3, $wl2, $wl3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wh2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY $wl3
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY $wh3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<2 x s32>) = COPY $fl2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<2 x s32>) = COPY $fh2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<2 x s32>) = COPY $fl3
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<2 x s32>) = COPY $fh3
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s32) = COPY $gl2
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(s32) = COPY $gh2
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(s32) = COPY $gl3
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(s32) = COPY $gh3
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(s32) = COPY $el2
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s32) = COPY $eh2
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s32) = COPY $el3
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s32) = COPY $eh3
  ; CHECK-NEXT:   $wl0 = COPY [[COPY]](<8 x s32>)
  ; CHECK-NEXT:   $wh0 = COPY [[COPY1]](<8 x s32>)
  ; CHECK-NEXT:   $wl1 = COPY [[COPY2]](<8 x s32>)
  ; CHECK-NEXT:   $wh1 = COPY [[COPY3]](<8 x s32>)
  ; CHECK-NEXT:   $fl0 = COPY [[COPY4]](<2 x s32>)
  ; CHECK-NEXT:   $fh0 = COPY [[COPY5]](<2 x s32>)
  ; CHECK-NEXT:   $fl1 = COPY [[COPY6]](<2 x s32>)
  ; CHECK-NEXT:   $fh1 = COPY [[COPY7]](<2 x s32>)
  ; CHECK-NEXT:   $gl0 = COPY [[COPY8]](s32)
  ; CHECK-NEXT:   $gh0 = COPY [[COPY9]](s32)
  ; CHECK-NEXT:   $gl1 = COPY [[COPY10]](s32)
  ; CHECK-NEXT:   $gh1 = COPY [[COPY11]](s32)
  ; CHECK-NEXT:   $el0 = COPY [[COPY12]](s32)
  ; CHECK-NEXT:   $eh0 = COPY [[COPY13]](s32)
  ; CHECK-NEXT:   $el1 = COPY [[COPY14]](s32)
  ; CHECK-NEXT:   $eh1 = COPY [[COPY15]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0, implicit $wh0, implicit $wl1, implicit $wh1, implicit $fl0, implicit $fh0, implicit $fl1, implicit $fh1, implicit $gl0, implicit $gh0, implicit $gl1, implicit $gh1, implicit $el0, implicit $eh0, implicit $el1, implicit $eh1
entry:
  ret %struct.v256mx6 %v1
}
