; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2ps -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o - 2>&1 | FileCheck %s --check-prefix=GMIR

; This test verifies that MMOs are created by the IRTranslator for FIFO ld/st
; instructions, and that they survive ISel.

define ptr @test_fifo_fill(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail) {
  ; GMIR-LABEL: name: test_fifo_fill
  ; GMIR: bb.1.entry:
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr, align 1)
  ;
  ; ISEL-LABEL: name: test_fifo_fill
  ; ISEL: VLD_FILL_512_pseudo
  ; ISEL-SAME: :: (load unknown-size from %ir.ptr, align 1)
entry:
  %res0 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %avail)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 0
  ret ptr %ptr0
}

define ptr @test_fifo_pop_unaligned(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail) {
  ; GMIR-LABEL: name: test_fifo_pop_unaligned
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.512.unaligned)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.unaligned)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr0, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.unaligned)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr1, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.unaligned)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr2, align 1)
  ;
  ; ISEL-LABEL: name: test_fifo_pop_unaligned
  ; ISEL: VLD_POP_512_normal_pop_pseudo
  ; ISEL-SAME: :: (load unknown-size from %ir.ptr, align 1)
  ; ISEL: VLD_POP_512_fifo_1d_pop_pseudo
  ; ISEL-SAME: :: (load unknown-size from %ir.ptr0, align 1)
  ; ISEL: VLD_POP_512_2D_pseudo
  ; ISEL-SAME: :: (load unknown-size from %ir.ptr1, align 1)
  ; ISEL: VLD_POP_512_3D_pseudo
  ; ISEL-SAME: :: (load unknown-size from %ir.ptr2, align 1)
entry:
  %res0 = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %avail)
  %ptr0 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %res0, 1
  %buf0 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %res0, 2
  %pos0 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %res0, 3

  %res1 = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr %ptr0, <32 x i32> %buf0, i32 %pos0, i20 16)
  %ptr1 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %res1, 1
  %buf1 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %res1, 2
  %pos1 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %res1, 3

  %res2 = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr %ptr1, <32 x i32> %buf1, i32 %pos1, i20 1, i20 2, i20 3, i20 4)
  %ptr2 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %res2, 1
  %buf2 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %res2, 2
  %pos2 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %res2, 3

  %res3 = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr %ptr2, <32 x i32> %buf2, i32 %pos2, i20 1, i20 2, i20 3, i20 4, i20 5, i20 6, i20 7)
  %ptr3 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } %res3, 1

  ret ptr %ptr3
}

define ptr @test_fifo_pop_BFP640(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail) {
  ; GMIR-LABEL: name: test_fifo_pop_BFP640
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP640)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP640)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr0, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP640)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr1, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP640)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr2, align 1)
  ;
  ; ISEL-LABEL: name: test_fifo_pop_BFP640
entry:
  %res0 = tail call { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %avail)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %res0, 0
  %buf0 = extractvalue { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %res0, 1
  %pos0 = extractvalue { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %res0, 2

  %res1 = tail call { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.1d.BFP640.p0.p0(ptr %ptr0, <32 x i32> %buf0, i32 %pos0, i20 16)
  %ptr1 = extractvalue { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %res1, 0
  %buf1 = extractvalue { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %res1, 1
  %pos1 = extractvalue { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } %res1, 2

  %res2 = tail call { ptr, <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.2d.BFP640.p0.p0(ptr %ptr1, <32 x i32> %buf1, i32 %pos1, i20 1, i20 2, i20 3, i20 4)
  %ptr2 = extractvalue { ptr, <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } %res2, 0
  %buf2 = extractvalue { ptr, <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } %res2, 1
  %pos2 = extractvalue { ptr, <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } %res2, 2

  %res3 = tail call { ptr, <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.3d.BFP640.p0.p0(ptr %ptr2, <32 x i32> %buf2, i32 %pos2, i20 1, i20 2, i20 3, i20 4, i20 5, i20 6, i20 7)
  %ptr3 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } %res3, 0

  ret ptr %ptr3
}

define ptr @test_fifo_pop_BFP768(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail) {
  ; GMIR-LABEL: name: test_fifo_pop_BFP768
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP768)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP768)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr0, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP768)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr1, align 1)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP768)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr2, align 1)
  ;
  ; ISEL-LABEL: name: test_fifo_pop_BFP768
entry:
  %res0 = tail call { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.BFP768.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %avail)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res0, 0
  %buf0 = extractvalue { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res0, 1
  %pos0 = extractvalue { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res0, 2

  %res1 = tail call { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.1d.BFP768.p0.p0(ptr %ptr0, <32 x i32> %buf0, i32 %pos0, i20 16)
  %ptr1 = extractvalue { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res1, 0
  %buf1 = extractvalue { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res1, 1
  %pos1 = extractvalue { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res1, 2

  %res2 = tail call { ptr, <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.2d.BFP768.p0.p0(ptr %ptr1, <32 x i32> %buf1, i32 %pos1, i20 1, i20 2, i20 3, i20 4)
  %ptr2 = extractvalue { ptr, <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res2, 0
  %buf2 = extractvalue { ptr, <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res2, 1
  %pos2 = extractvalue { ptr, <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res2, 2

  %res3 = tail call { ptr, <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.3d.BFP768.p0.p0(ptr %ptr2, <32 x i32> %buf2, i32 %pos2, i20 1, i20 2, i20 3, i20 4, i20 5, i20 6, i20 7)
  %ptr3 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } %res3, 0

  ret ptr %ptr3
}

define ptr @test_fifo_push(ptr noalias align 4 %ptr, <16 x i32> noundef %v) {
  ; GMIR-LABEL: name: test_fifo_push
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.512)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ;
  ; ISEL-LABEL: name: test_fifo_push
  ; ISEL: VST_PUSH_512
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr, align 4)
entry:
  %res0 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr %ptr, <16 x i32> %v, <32 x i32> undef, i32 0)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 0
  ret ptr %ptr0
}

define ptr @test_fifo_push_BFP640(ptr noalias align 4 %ptr, <16 x i32> %v1, <2 x i32> %v2, <2 x i32> %v3) {
  ; GMIR-LABEL: name: test_fifo_push_BFP640
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP640)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ;
  ; ISEL-LABEL: name: test_fifo_push_BFP640
entry:
  %res0 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP640.p0.p0(ptr %ptr, <32 x i32> undef, i32 0, <16 x i32> %v1, <2 x i32> %v2, <2 x i32> %v3)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 0
  ret ptr %ptr0
}

define ptr @test_fifo_push_BFP768(ptr noalias align 4 %ptr, <8 x i32> %v1, <8 x i32> %v2, <2 x i32> %v3, <2 x i32> %v4, i32 %v5, i32 %v6, i32 %v7, i32 %v8) {
  ; GMIR-LABEL: name: test_fifo_push_BFP768
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP768)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ;
  ; ISEL-LABEL: name: test_fifo_push_BFP768
entry:
  %res0 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP768.p0.p0(ptr %ptr, <32 x i32> undef, i32 0, <8 x i32> %v1, <8 x i32> %v2, <2 x i32> %v3, <2 x i32> %v4, i32 %v5, i32 %v6, i32 %v7, i32 %v8)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 0
  ret ptr %ptr0
}

define ptr @test_fifo_push_BFP384(ptr noalias align 4 %ptr, <8 x i32> %v1, <2 x i32> %v2, i32 %v3, i32 %v4) {
  ; GMIR-LABEL: name: test_fifo_push_BFP384
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP384)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ;
  ; ISEL-LABEL: name: test_fifo_push_BFP384
entry:
  %res0 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP384.p0.p0(ptr %ptr, <32 x i32> undef, i32 0, <8 x i32> %v1, <2 x i32> %v2, i32 %v3, i32 %v4)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 0
  ret ptr %ptr0
}

define ptr @test_fifo_flush(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %pos) {
  ; GMIR-LABEL: name: test_fifo_flush
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr0, align 4)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr1, align 4)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr2, align 4)
  ;
  ; ISEL-LABEL: name: test_fifo_flush
  ; ISEL: VST_FLUSH_512_normal_flush
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ; ISEL: VST_FLUSH_512_fifo_1d_flush
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr0, align 4)
  ; ISEL: VST_FLUSH_512_2D
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr1, align 4)
  ; ISEL: VST_FLUSH_512_3D
  ; ISEL-SAME: :: (store unknown-size from %ir.ptr2, align 4)
entry:
  %res0 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %pos)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 0
  %buf0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 1
  %pos0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 2

  %res1 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr %ptr0, <32 x i32> %buf0, i32 %pos0, i20 16)
  %ptr1 = extractvalue { ptr, <32 x i32>, i32 } %res1, 0
  %buf1 = extractvalue { ptr, <32 x i32>, i32 } %res1, 1
  %pos1 = extractvalue { ptr, <32 x i32>, i32 } %res1, 2

  %res2 = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr %ptr1, <32 x i32> %buf1, i32 %pos1, i20 1, i20 2, i20 3, i20 4)
  %ptr2 = extractvalue { ptr, <32 x i32>, i32, i20 } %res2, 0
  %buf2 = extractvalue { ptr, <32 x i32>, i32, i20 } %res2, 1
  %pos2 = extractvalue { ptr, <32 x i32>, i32, i20 } %res2, 2

  %res3 = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr %ptr2, <32 x i32> %buf2, i32 %pos2, i20 1, i20 2, i20 3, i20 4, i20 5, i20 6, i20 7)
  %ptr3 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %res3, 0

  ret ptr %ptr3
}

define ptr @test_fifo_flush_conv(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %pos) {
  ; GMIR-LABEL: name: test_fifo_flush_conv
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.conv)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d.conv)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr0, align 4)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d.conv)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr1, align 4)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d.conv)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr2, align 4)
  ;
  ; ISEL-LABEL: name: test_fifo_flush_conv
  ; ISEL: VST_FLUSH_512_CONV_normal_flush
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr, align 4)
  ; ISEL: VST_FLUSH_512_CONV_fifo_1d_flush
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr0, align 4)
  ; ISEL: VST_FLUSH_512_CONV_2D
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr1, align 4)
  ; ISEL: VST_FLUSH_512_CONV_3D
  ; ISEL-SAME: :: (store unknown-size into %ir.ptr2, align 4)
entry:
  %res0 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %pos)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 0
  %buf0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 1
  %pos0 = extractvalue { ptr, <32 x i32>, i32 } %res0, 2

  %res1 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr %ptr0, <32 x i32> %buf0, i32 %pos0, i20 16)
  %ptr1 = extractvalue { ptr, <32 x i32>, i32 } %res1, 0
  %buf1 = extractvalue { ptr, <32 x i32>, i32 } %res1, 1
  %pos1 = extractvalue { ptr, <32 x i32>, i32 } %res1, 2

  %res2 = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr %ptr1, <32 x i32> %buf1, i32 %pos1, i20 1, i20 2, i20 3, i20 4)
  %ptr2 = extractvalue { ptr, <32 x i32>, i32, i20 } %res2, 0
  %buf2 = extractvalue { ptr, <32 x i32>, i32, i20 } %res2, 1
  %pos2 = extractvalue { ptr, <32 x i32>, i32, i20 } %res2, 2

  %res3 = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr %ptr2, <32 x i32> %buf2, i32 %pos2, i20 1, i20 2, i20 3, i20 4, i20 5, i20 6, i20 7)
  %ptr3 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %res3, 0

  ret ptr %ptr3
}

define ptr @test_fifo_fillx(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail, <16 x i32> %extra_buf, i32 %conf) {
  ; GMIR-LABEL: name: test_fifo_fillx
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fillx)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr, align 1)
  ;
  ; ISEL-LABEL: name: test_fifo_fillx
  ; ISEL: VLDB_FILLX_512
  ; ISEL-SAME: :: (load unknown-size from %ir.ptr, align 1)
entry:
  %res0 = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.fillx.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %avail, <16 x i32> %extra_buf, i32 %conf)
  %ptr0 = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } %res0, 0
  ret ptr %ptr0
}

define ptr @test_fifo_popx(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail, <16 x i32> %extra_buf, i32 %conf) {
  ; GMIR-LABEL: name: test_fifo_popx
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.popx)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr, align 1)
  ;
  ; ISEL-LABEL: name: test_fifo_popx
  ; ISEL: VLDB_POPX_512
  ; ISEL-SAME: :: (load unknown-size from %ir.ptr, align 1)
entry:
  %res0 = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr %ptr, <32 x i32> %buf, i32 %avail, <16 x i32> %extra_buf, i32 %conf)
  %ptr0 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %res0, 1
  ret ptr %ptr0
}

; Address space variants - testing with different address spaces

define ptr @test_fifo_fill_addrspace5(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail) {
  ; GMIR-LABEL: name: test_fifo_fill_addrspace5
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr_as5, align 1, addrspace 5)
entry:
  %ptr_as5 = addrspacecast ptr %ptr to ptr addrspace(5)
  %res0 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) %ptr_as5, <32 x i32> %buf, i32 %avail)
  %ptr0 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %res0, 0
  %ptr0_as0 = addrspacecast ptr addrspace(5) %ptr0 to ptr
  ret ptr %ptr0_as0
}

define ptr @test_fifo_fill_addrspace6(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail) {
  ; GMIR-LABEL: name: test_fifo_fill_addrspace6
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr_as6, align 1, addrspace 6)
entry:
  %ptr_as6 = addrspacecast ptr %ptr to ptr addrspace(6)
  %res0 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) %ptr_as6, <32 x i32> %buf, i32 %avail)
  %ptr0 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %res0, 0
  %ptr0_as0 = addrspacecast ptr addrspace(6) %ptr0 to ptr
  ret ptr %ptr0_as0
}

define ptr @test_fifo_pop_unaligned_addrspace5(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %avail) {
  ; GMIR-LABEL: name: test_fifo_pop_unaligned_addrspace5
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.512.unaligned)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr_as5, align 1, addrspace 5)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.unaligned)
  ; GMIR-SAME: :: (load unknown-size from %ir.ptr0, align 1, addrspace 5)
entry:
  %ptr_as5 = addrspacecast ptr %ptr to ptr addrspace(5)
  %res0 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p5.p5(ptr addrspace(5) %ptr_as5, <32 x i32> %buf, i32 %avail)
  %ptr0 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } %res0, 1
  %buf0 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } %res0, 2
  %pos0 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } %res0, 3

  %res1 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p5.p5(ptr addrspace(5) %ptr0, <32 x i32> %buf0, i32 %pos0, i20 16)
  %ptr1 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } %res1, 1
  %ptr1_as0 = addrspacecast ptr addrspace(5) %ptr1 to ptr

  ret ptr %ptr1_as0
}

define ptr @test_fifo_push_addrspace7(ptr noalias align 4 %ptr, <16 x i32> noundef %v) {
  ; GMIR-LABEL: name: test_fifo_push_addrspace7
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.512)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr_as7, align 4, addrspace 7)
entry:
  %ptr_as7 = addrspacecast ptr %ptr to ptr addrspace(7)
  %res0 = tail call { ptr addrspace(7), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p7.p7(ptr addrspace(7) %ptr_as7, <16 x i32> %v, <32 x i32> undef, i32 0)
  %ptr0 = extractvalue { ptr addrspace(7), <32 x i32>, i32 } %res0, 0
  %ptr0_as0 = addrspacecast ptr addrspace(7) %ptr0 to ptr
  ret ptr %ptr0_as0
}

define ptr @test_fifo_flush_addrspace7(ptr noalias align 4 %ptr, <32 x i32> %buf, i32 %pos) {
  ; GMIR-LABEL: name: test_fifo_flush_addrspace7
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr_as7, align 4, addrspace 7)
  ; GMIR: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d)
  ; GMIR-SAME: :: (store unknown-size into %ir.ptr0, align 4, addrspace 7)
entry:
  %ptr_as7 = addrspacecast ptr %ptr to ptr addrspace(7)
  %res0 = tail call { ptr addrspace(7), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p7.p7(ptr addrspace(7) %ptr_as7, <32 x i32> %buf, i32 %pos)
  %ptr0 = extractvalue { ptr addrspace(7), <32 x i32>, i32 } %res0, 0
  %buf0 = extractvalue { ptr addrspace(7), <32 x i32>, i32 } %res0, 1
  %pos0 = extractvalue { ptr addrspace(7), <32 x i32>, i32 } %res0, 2

  %res1 = tail call { ptr addrspace(7), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p7.p7(ptr addrspace(7) %ptr0, <32 x i32> %buf0, i32 %pos0, i20 16)
  %ptr1 = extractvalue { ptr addrspace(7), <32 x i32>, i32 } %res1, 0
  %ptr1_as0 = addrspacecast ptr addrspace(7) %ptr1 to ptr

  ret ptr %ptr1_as0
}

declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill(ptr, <32 x i32>, i32)
declare { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.fillx(ptr, <32 x i32>, i32, <16 x i32>, i32)
declare { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx(ptr, <32 x i32>, i32, <16 x i32>, i32)
declare { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned(ptr, <32 x i32>, i32)
declare { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned(ptr, <32 x i32>, i32, i20)
declare { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned(ptr, <32 x i32>, i32, i20, i20, i20, i20)
declare { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20)
declare { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640(ptr, <32 x i32>, i32)
declare { ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.1d.BFP640(ptr, <32 x i32>, i32, i20)
declare { ptr, <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.2d.BFP640(ptr, <32 x i32>, i32, i20, i20, i20, i20)
declare { ptr, <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.3d.BFP640(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20)
declare { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.BFP768(ptr, <32 x i32>, i32)
declare { ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.1d.BFP768(ptr, <32 x i32>, i32, i20)
declare { ptr, <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.2d.BFP768(ptr, <32 x i32>, i32, i20, i20, i20, i20)
declare { ptr, <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.3d.BFP768(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20)

declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512(ptr, <16 x i32>, <32 x i32>, i32)
declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP384(ptr, <32 x i32>, i32, <8 x i32>, <2 x i32>, i32, i32)
declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP640(ptr, <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32>)
declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP768(ptr, <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32)
declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush(ptr, <32 x i32>, i32)
declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d(ptr, <32 x i32>, i32, i20)
declare { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d(ptr, <32 x i32>, i32, i20, i20, i20, i20)
declare { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20)
declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv(ptr, <32 x i32>, i32)
declare { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv(ptr, <32 x i32>, i32, i20)
declare { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv(ptr, <32 x i32>, i32, i20, i20, i20, i20)
declare { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20)

declare { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5), <32 x i32>, i32)
declare { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6), <32 x i32>, i32)
declare { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p5.p5(ptr addrspace(5), <32 x i32>, i32)
declare { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20)
declare { ptr addrspace(7), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p7.p7(ptr addrspace(7), <16 x i32>, <32 x i32>, i32)
declare { ptr addrspace(7), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p7.p7(ptr addrspace(7), <32 x i32>, i32)
declare { ptr addrspace(7), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p7.p7(ptr addrspace(7), <32 x i32>, i32, i20)
