; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2PS
; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

%class.float16 = type { half }
define dso_local void @test_get_float16() local_unnamed_addr #0 {
  ; CHECK-LABEL: name: test_get_float16
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[DEF]](s16)
  ; CHECK-NEXT:   $r1 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJ_TCO_jump_imm @ret_float16float16, csr_aie2ps, implicit $r1
entry:
  %call = tail call %class.float16 @ret_float16float16(%class.float16 undef)
  ret void
}
declare dso_local %class.float16 @ret_float16float16(%class.float16) local_unnamed_addr #1

define  void @test_pass_v2half()  {
  ; CHECK-LABEL: name: test_pass_v2half
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<2 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.ret
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r1 = COPY [[DEF]](<2 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v2float16, csr_aie2ps, implicit-def $lr, implicit $r1, implicit-def $r0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<2 x s16>) = COPY $r0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   G_STORE [[COPY]](<2 x s16>), [[FRAME_INDEX]](p0) :: (volatile store (<2 x s16>) into %ir.ret)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %ret = alloca <2 x half>, align 4
  %call = tail call noundef <2 x half> @callee_v2float16(<2 x half> noundef undef)
  store volatile <2 x half> %call, ptr %ret, align 4
  ret void
}
declare  noundef <2 x half> @callee_v2float16(<2 x half> noundef)


define  void @test_pass_v4half()  {
  ; CHECK-LABEL: name: test_pass_v4half
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<4 x s16>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.ret
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $l1 = COPY [[DEF]](<4 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v4float16, csr_aie2ps, implicit-def $lr, implicit $l1, implicit-def $l0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<4 x s16>) = COPY $l0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   G_STORE [[COPY]](<4 x s16>), [[FRAME_INDEX]](p0) :: (volatile store (<4 x s16>) into %ir.ret)
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %ret = alloca <4 x half>, align 8
  %call = tail call noundef <4 x half> @callee_v4float16(<4 x half> noundef undef)
  store volatile <4 x half> %call, ptr %ret, align 8
  ret void
}
declare  noundef <4 x half> @callee_v4float16(<4 x half> noundef)


define void @test_call_v8half() {
  ; CHECK-LABEL: name: test_call_v8half
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.call
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s16>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<8 x s16>) from %ir.call)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s16), [[UV1:%[0-9]+]]:_(s16), [[UV2:%[0-9]+]]:_(s16), [[UV3:%[0-9]+]]:_(s16), [[UV4:%[0-9]+]]:_(s16), [[UV5:%[0-9]+]]:_(s16), [[UV6:%[0-9]+]]:_(s16), [[UV7:%[0-9]+]]:_(s16) = G_UNMERGE_VALUES [[LOAD]](<8 x s16>)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_BUILD_VECTOR [[UV]](s16), [[UV1]](s16), [[UV2]](s16), [[UV3]](s16), [[UV4]](s16), [[UV5]](s16), [[UV6]](s16), [[UV7]](s16), [[DEF]](s16), [[DEF]](s16), [[DEF]](s16), [[DEF]](s16), [[DEF]](s16), [[DEF]](s16), [[DEF]](s16), [[DEF]](s16)
  ; CHECK-NEXT:   $wl2 = COPY [[BUILD_VECTOR]](<16 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v8float16, csr_aie2ps, implicit-def $lr, implicit $wl2, implicit-def $wl0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
  ; CHECK-NEXT:   [[UV8:%[0-9]+]]:_(<8 x s16>), [[UV9:%[0-9]+]]:_(<8 x s16>) = G_UNMERGE_VALUES [[COPY]](<16 x s16>)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %call = alloca <8 x half>, align 16
  %0 = load volatile <8 x half>, ptr %call, align 16
  %call1 = call noundef <8 x half> @callee_v8float16(<8 x half> noundef %0)
  ret void
}

declare  <8 x half> @callee_v8float16(<8 x half> noundef)

define void @_Z21test_call_v16halfv() {
  ; CHECK-LABEL: name: _Z21test_call_v16halfv
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.call
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s16>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<16 x s16>) from %ir.call)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $wl2 = COPY [[LOAD]](<16 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v16float16, csr_aie2ps, implicit-def $lr, implicit $wl2, implicit-def $wl0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %call = alloca <16 x half>, align 32
  %0 = load volatile <16 x half>, ptr %call, align 32
  %call1 = call noundef <16 x half> @callee_v16float16(<16 x half> noundef %0)
  ret void
}

declare  <16 x half> @callee_v16float16(<16 x half> noundef)

define void @test_call_v32half() {
  ; CHECK-LABEL: name: test_call_v32half
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.call
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<32 x s16>) from %ir.call)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $x2 = COPY [[LOAD]](<32 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v32float16, csr_aie2ps, implicit-def $lr, implicit $x2, implicit-def $x0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %call = alloca <32 x half>, align 64
  %0 = load volatile <32 x half>, ptr %call, align 64
  %call1 = call noundef <32 x half> @callee_v32float16(<32 x half> noundef %0)
  ret void
}

declare  <32 x half> @callee_v32float16(<32 x half> noundef)

define void @test_call_v64float16() {
  ; CHECK-LABEL: name: test_call_v64float16
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.call
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<64 x s16>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<64 x s16>) from %ir.call)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $y3 = COPY [[LOAD]](<64 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v64float16, csr_aie2ps, implicit-def $lr, implicit $y3, implicit-def $y2
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y2
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %call = alloca <64 x half>, align 128
  %0 = load volatile <64 x half>, ptr %call, align 128
  %call1 = call noundef <64 x half> @callee_v64float16(<64 x half> noundef %0)
  ret void
}

declare  <64 x half> @callee_v64float16(<64 x half> noundef)


define void @test_call_v128float16() {
  ; CHECK-LABEL: name: test_call_v128float16
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.call
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<128 x s16>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<128 x s16>) from %ir.call, align 128)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $dm1 = COPY [[LOAD]](<128 x s16>)
  ; CHECK-NEXT:   PseudoJL @callee_v128float16, csr_aie2ps, implicit-def $lr, implicit $dm1, implicit-def $dm0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<128 x s16>) = COPY $dm0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  %call = alloca <128 x half>, align 128
  %0 = load volatile <128 x half>, ptr %call, align 128
  %call1 = call noundef <128 x half> @callee_v128float16(<128 x half> noundef %0)
  ret void
}

declare  <128 x half> @callee_v128float16(<128 x half> noundef)
