; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; NOTE: -verify-machineinstrs was removed from the RUN command due to un-implemented methods for AIE2PS
; RUN: llc -mtriple=aie2ps -O0 -stop-after=irtranslator -global-isel %s -o - 2>&1 | FileCheck %s

%struct.bfloat8 = type { i8 }
%struct.v4bfloat8 = type { i32 }
%struct.v8bfloat8 = type { <8 x i8> }
%struct.v16bfloat8 = type { <16 x i8> }
%struct.v32bfloat8 = type { <32 x i8> }
%struct.v64bfloat8 = type { <64 x i8> }
%struct.v128bfloat8 = type { <128 x i8> }
%struct.v256bfloat8 = type { <64 x i32> }



define %struct.bfloat8 @test_bfloat8(%struct.bfloat8 %a) {
  ; CHECK-LABEL: name: test_bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[TRUNC]](s8)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  ret %struct.bfloat8 %a
}

define %struct.bfloat8 @test_bfloat8_morearg(%struct.bfloat8 %a, %struct.bfloat8) {
  ; CHECK-LABEL: name: test_bfloat8_morearg
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[TRUNC]](s8)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  ret %struct.bfloat8 %a
}

define %struct.bfloat8 @test_bfloat8_stack(%struct.bfloat8 %a, %struct.bfloat8, %struct.bfloat8, %struct.bfloat8, %struct.bfloat8, %struct.bfloat8, %struct.bfloat8, %struct.bfloat8, %struct.bfloat8) {
  ; CHECK-LABEL: name: test_bfloat8_stack
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r3
  ; CHECK-NEXT:   [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC [[COPY2]](s32)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $r4
  ; CHECK-NEXT:   [[TRUNC3:%[0-9]+]]:_(s8) = G_TRUNC [[COPY3]](s32)
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $r5
  ; CHECK-NEXT:   [[TRUNC4:%[0-9]+]]:_(s8) = G_TRUNC [[COPY4]](s32)
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $r6
  ; CHECK-NEXT:   [[TRUNC5:%[0-9]+]]:_(s8) = G_TRUNC [[COPY5]](s32)
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $r7
  ; CHECK-NEXT:   [[TRUNC6:%[0-9]+]]:_(s8) = G_TRUNC [[COPY6]](s32)
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (s32) from %fixed-stack.1)
  ; CHECK-NEXT:   [[TRUNC7:%[0-9]+]]:_(s8) = G_TRUNC [[LOAD]](s32)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (s32) from %fixed-stack.0, align 8)
  ; CHECK-NEXT:   [[TRUNC8:%[0-9]+]]:_(s8) = G_TRUNC [[LOAD1]](s32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[TRUNC]](s8)
  ; CHECK-NEXT:   $r0 = COPY [[ANYEXT]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  ret %struct.bfloat8 %a
}

define %struct.v4bfloat8 @test_v4bfloat8(%struct.v4bfloat8 %a) {
  ; CHECK-LABEL: name: test_v4bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   $r0 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
entry:
  ret %struct.v4bfloat8 %a
}


define %struct.v8bfloat8 @test_v8bfloat8(%struct.v8bfloat8 %a) {
  ; CHECK-LABEL: name: test_v8bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $l1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l1
  ; CHECK-NEXT:   $l0 = COPY [[COPY]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $l0
entry:
  ret %struct.v8bfloat8 %a
}

define %struct.v8bfloat8 @test_v8bfloat8_stack(%struct.v8bfloat8 %a, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8, %struct.v8bfloat8) {
  ; CHECK-LABEL: name: test_v8bfloat8_stack
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $l1, $l2, $l3, $l4, $l5, $l6, $l7, $l8, $l9, $l10, $l11, $l12, $l13, $l15
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<8 x s8>) = COPY $l2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s8>) = COPY $l3
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<8 x s8>) = COPY $l4
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<8 x s8>) = COPY $l5
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<8 x s8>) = COPY $l6
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<8 x s8>) = COPY $l7
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(<8 x s8>) = COPY $l8
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(<8 x s8>) = COPY $l9
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(<8 x s8>) = COPY $l10
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(<8 x s8>) = COPY $l11
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(<8 x s8>) = COPY $l12
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(<8 x s8>) = COPY $l13
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(<8 x s8>) = COPY $l15
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.1)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<8 x s8>) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (<8 x s8>) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   $l0 = COPY [[COPY]](<8 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $l0
entry:
  ret %struct.v8bfloat8 %a
}

define %struct.v16bfloat8 @test_v16bfloat8(%struct.v16bfloat8 %a) {
  ; CHECK-LABEL: name: test_v16bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $wl2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl2
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(<16 x s8>), [[UV1:%[0-9]+]]:_(<16 x s8>) = G_UNMERGE_VALUES [[COPY]](<32 x s8>)
  ; CHECK-NEXT:   [[UV2:%[0-9]+]]:_(s8), [[UV3:%[0-9]+]]:_(s8), [[UV4:%[0-9]+]]:_(s8), [[UV5:%[0-9]+]]:_(s8), [[UV6:%[0-9]+]]:_(s8), [[UV7:%[0-9]+]]:_(s8), [[UV8:%[0-9]+]]:_(s8), [[UV9:%[0-9]+]]:_(s8), [[UV10:%[0-9]+]]:_(s8), [[UV11:%[0-9]+]]:_(s8), [[UV12:%[0-9]+]]:_(s8), [[UV13:%[0-9]+]]:_(s8), [[UV14:%[0-9]+]]:_(s8), [[UV15:%[0-9]+]]:_(s8), [[UV16:%[0-9]+]]:_(s8), [[UV17:%[0-9]+]]:_(s8) = G_UNMERGE_VALUES [[UV]](<16 x s8>)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(s8) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_BUILD_VECTOR [[UV2]](s8), [[UV3]](s8), [[UV4]](s8), [[UV5]](s8), [[UV6]](s8), [[UV7]](s8), [[UV8]](s8), [[UV9]](s8), [[UV10]](s8), [[UV11]](s8), [[UV12]](s8), [[UV13]](s8), [[UV14]](s8), [[UV15]](s8), [[UV16]](s8), [[UV17]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8)
  ; CHECK-NEXT:   $wl0 = COPY [[BUILD_VECTOR]](<32 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0
entry:
  ret %struct.v16bfloat8 %a
}

define %struct.v32bfloat8 @test_v32bfloat8(%struct.v32bfloat8 %a) {
  ; CHECK-LABEL: name: test_v32bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $wl2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl2
  ; CHECK-NEXT:   $wl0 = COPY [[COPY]](<32 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $wl0
entry:
  ret %struct.v32bfloat8 %a
}

define %struct.v64bfloat8 @test_v64bfloat8(%struct.v64bfloat8 %a) {
  ; CHECK-LABEL: name: test_v64bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
  ; CHECK-NEXT:   $x0 = COPY [[COPY]](<64 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0
entry:
  ret %struct.v64bfloat8 %a
}

define %struct.v128bfloat8 @test_v128bfloat8(%struct.v128bfloat8 %a) {
  ; CHECK-LABEL: name: test_v128bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $y3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<128 x s8>) = COPY $y3
  ; CHECK-NEXT:   $y2 = COPY [[COPY]](<128 x s8>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $y2
entry:
  ret %struct.v128bfloat8 %a
}

define %struct.v256bfloat8 @test_v256bfloat8(%struct.v256bfloat8 %a) {
  ; CHECK-LABEL: name: test_v256bfloat8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $dm1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm1
  ; CHECK-NEXT:   $dm0 = COPY [[COPY]](<64 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $dm0
entry:
  ret %struct.v256bfloat8 %a
}

define %struct.v256bfloat8 @test_v256bfloat8_stack(%struct.v256bfloat8 %a, %struct.v256bfloat8, %struct.v256bfloat8, %struct.v256bfloat8, %struct.v256bfloat8, %struct.v256bfloat8, %struct.v256bfloat8, %struct.v256bfloat8) {
  ; CHECK-LABEL: name: test_v256bfloat8_stack
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $dm1, $dm2, $dm3, $dm4, $dm5, $dm6, $dm7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<64 x s32>) = COPY $dm2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<64 x s32>) = COPY $dm3
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(<64 x s32>) = COPY $dm4
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(<64 x s32>) = COPY $dm5
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(<64 x s32>) = COPY $dm6
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(<64 x s32>) = COPY $dm7
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<64 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (<64 x s32>) from %fixed-stack.0, align 64)
  ; CHECK-NEXT:   $dm0 = COPY [[COPY]](<64 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $dm0
entry:
  ret %struct.v256bfloat8 %a
}
