; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -O2 -mtriple=aie2ps %s -o - | FileCheck %s

; End-to-end check for sinking a constant vector splat past a call.
;
; The IRTranslator materializes the <32 x i16> splat at the top of the entry
; block.  Because the only use is the loop PHI that sits behind @callee, without
; localization the splat's broadcast would be live across the call, forcing a
; 512-bit vector register to be spilled/reloaded around the call frame.
;
; The AIE2ps pre-legalize pipeline now runs the generic GlobalISel Localizer,
; and AIEBaseTargetLowering::shouldLocalize() opts vector splats in, so the
; broadcast is sunk below the call: the call (jl #callee) is issued first, the
; splat is materialized afterwards (vbcst.16) in the loop preheader, and no
; 512-bit vector register is spilled/reloaded around the call frame.

target triple = "aie2ps"

declare void @callee(ptr)

define <32 x i16> @splat_phi_across_call(ptr %p, i32 %n) {
; CHECK-LABEL: splat_phi_across_call:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; jl #callee; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    paddxm [sp], #64 // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    st r8, [sp, #-60] // 4-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    mov r8, r0 // Delay Slot 1
; CHECK-NEXT:    nopa ; nopb ; nops ; movxm ls, #.LBB0_1; nopv
; CHECK-NEXT:    mova r0, #1; nopb ; movxm le, #.L_LEnd0
; CHECK-NEXT:    max r0, r8, r0
; CHECK-NEXT:    nopa ; nopb ; nops ; add.nc lc, r0, #0; nopm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r2, #7; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vbcst.16 x2, r2; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vmov x0, x2; nopv
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vadd.16 x2, x2, x2; nopv
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    lda lr, [sp, #-64]; nopb ; nops ; nopxm ; nopv // 4-byte Folded Reload
; CHECK-NEXT:    nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 1
entry:
  call void @callee(ptr %p)
  br label %loop

loop:
  %acc = phi <32 x i16> [ splat (i16 7), %entry ], [ %acc.next, %loop ]
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc.next = add <32 x i16> %acc, %acc
  %i.next = add i32 %i, 1
  %c = icmp slt i32 %i.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret <32 x i16> %acc
}
