# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=localizer %s -verify-machineinstrs -o - | FileCheck %s

# These tests show that, once AIE's shouldLocalize() opts vector splats in, the
# generic GlobalISel Localizer sinks a constant vector splat (materialized by
# the IRTranslator at the top of the entry block) down to just before its first
# use. When a call sits between the splat and that use, the splat therefore ends
# up after the call, so its live range no longer crosses the call frame.

---
# A G_BUILD_VECTOR splat of an fp16 constant with one intervening call and the
# first use after the call: both the G_FCONSTANT and the splat are sunk past the
# PseudoJL.
name:            sink_splat_past_one_call
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: sink_splat_past_one_call
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT bfloat 0xRFF80
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $x0 = COPY [[BUILD_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(p0) = COPY $p0
    %1:_(s16) = G_FCONSTANT bfloat 0xRFF80
    %2:_(<32 x s16>) = G_BUILD_VECTOR %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16)
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $p0 = COPY %0(p0)
    PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
# Same shape, but using the target broadcast pseudo (the canonical form after
# the pre-legalizer combiner). The broadcast and its feeding constant are sunk
# past the call.
name:            sink_broadcast_past_call
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: sink_broadcast_past_call
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $x0 = COPY [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %1(s32)
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $p0 = COPY %0(p0)
    PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
# No call follows the splat: it is simply sunk to just before its use.
name:            no_call_after_splat
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: no_call_after_splat
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT bfloat 0xRFF80
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
    ; CHECK-NEXT: $x0 = COPY [[BUILD_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(p0) = COPY $p0
    %1:_(s16) = G_FCONSTANT bfloat 0xRFF80
    %2:_(<32 x s16>) = G_BUILD_VECTOR %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16)
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
# The splat is used before the call: the Localizer sinks it to just before that
# (earlier) use, so it stays before the call - it is never moved across a use.
name:            splat_used_before_call_no_sink
body:             |
  bb.1.entry:
    liveins: $p0, $x0
    ; CHECK-LABEL: name: splat_used_before_call_no_sink
    ; CHECK: liveins: $p0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT bfloat 0xRFF80
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
    ; CHECK-NEXT: $x0 = COPY [[BUILD_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s16) = G_FCONSTANT bfloat 0xRFF80
    %2:_(<32 x s16>) = G_BUILD_VECTOR %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16)
    $x0 = COPY %2(<32 x s16>)
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $p0 = COPY %0(p0)
    PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    PseudoRET implicit $lr
...

---
# A non-splat G_BUILD_VECTOR is not constant-like, so shouldLocalize() leaves it
# (and its register operands) in place: no movement.
name:            non_splat_build_vector_no_sink
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: non_splat_build_vector_no_sink
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16), [[TRUNC]](s16)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $x0 = COPY [[BUILD_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(p0) = COPY $p0
    %3:_(s32) = COPY $r0
    %4:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %3(s32)
    %5:_(s16) = G_TRUNC %4(s32)
    %2:_(<32 x s16>) = G_BUILD_VECTOR %1(s16), %5(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16)
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $p0 = COPY %0(p0)
    PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
# Two intervening calls with the first use after both: the splat is sunk past
# both calls (down to its use).
name:            sink_splat_past_last_of_two_calls
body:             |
  bb.1.entry:
    liveins: $p0
    ; CHECK-LABEL: name: sink_splat_past_last_of_two_calls
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT bfloat 0xRFF80
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = COPY [[COPY]](p0)
    ; CHECK-NEXT: PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $x0 = COPY [[BUILD_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(p0) = COPY $p0
    %1:_(s16) = G_FCONSTANT bfloat 0xRFF80
    %2:_(<32 x s16>) = G_BUILD_VECTOR %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16)
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $p0 = COPY %0(p0)
    PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $p0 = COPY %0(p0)
    PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    $x0 = COPY %2(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
# The original motivating shape: a constant splat materialized at entry-block
# top that feeds a loop PHI (so it would otherwise be live across the call in
# the entry block, i.e. the preheader). The splat's only user is the PHI, so the
# Localizer sinks it to the end of the entry block - after the call and just
# before the branch - rather than duplicating it inside the loop.
name:            sink_splat_past_call_phi_use
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: sink_splat_past_call_phi_use
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s16) = G_FCONSTANT bfloat 0xRFF80
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $p0 = COPY [[COPY]](p0)
  ; CHECK-NEXT:   PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(<32 x s16>) = G_PHI [[BUILD_VECTOR]](<32 x s16>), %bb.0, [[PHI]](<32 x s16>), %bb.1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
  ; CHECK-NEXT:   G_BRCOND [[C1]](s1), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   $x0 = COPY [[PHI]](<32 x s16>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0
  bb.0:
    successors: %bb.1
    liveins: $p0
    %0:_(p0) = COPY $p0
    %1:_(s16) = G_FCONSTANT bfloat 0xRFF80
    %2:_(<32 x s16>) = G_BUILD_VECTOR %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16), %1(s16)
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $p0 = COPY %0(p0)
    PseudoJL &callee, csr_aie2ps, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    G_BR %bb.1

  bb.1:
    successors: %bb.1, %bb.2
    %3:_(<32 x s16>) = G_PHI %2(<32 x s16>), %bb.0, %3(<32 x s16>), %bb.1
    %4:_(s1) = G_CONSTANT i1 true
    G_BRCOND %4(s1), %bb.1
    G_BR %bb.2

  bb.2:
    $x0 = COPY %3(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...
