# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps \
# RUN: -run-pass=dead-mi-elimination,aie-post-select-optimize,dead-mi-elimination \
# RUN: --aie-simplify-crsr-edges=true -verify-machineinstrs %s -o - | FileCheck %s

# Test 1 - Deadcode elimination of redundant srssign0 set/reset.
# $srssign0 = COPY %0             |   |    | $srssign0 = COPY %0
# %2 = opcode implicit $srssign0  |   |    | %2 = opcode implicit $srssign0
# $srssign0 = MOVX 0              |-> to ->| -------------------------------
# $srssign0 = COPY %0             |   |    | -------------------------------
# %3 = opcode implicit $srssign0  |   |    | %3 = opcode implicit $srssign0
# $srssign0 = MOVX 0              |   |    | $srssign0 = MOVX 0
---
name:            srssign0_redundant_reassignments
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r1, $dm0, $s0
    ; CHECK-LABEL: name: srssign0_redundant_reassignments
    ; CHECK: liveins: $r1, $dm0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edm = COPY $dm0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY]]
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY]]
    ; CHECK-NEXT: $x2 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY1]], [[COPY2]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    %1:er = COPY $r1
    %2:edm = COPY $dm0
    %3:es = COPY $s0
    $srssign0 = COPY %1
    $x0 = VSRS_4x_mv_x_srs_dm_srsSign0 %2, %3, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    $srssign0 = MOVX_mvx_cr_imm 0
    $srssign0 = COPY %1
    $x2 = VSRS_4x_mv_x_srs_dm_srsSign0 %2, %3, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    $srssign0 = MOVX_mvx_cr_imm 0
...

# Test 2 - Variation where sign value changes between uses (should NOT eliminate).
---
name:            srssign0_different_values
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $dm0, $s0
    ; CHECK-LABEL: name: srssign0_different_values
    ; CHECK: liveins: $r0, $r1, $dm0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edm = COPY $dm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:es = COPY $s0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY1]]
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    ; CHECK-NEXT: $srssign0 = COPY [[COPY]]
    ; CHECK-NEXT: $x2 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY2]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: $srssign0 = MOVX_mvx_cr_imm 0
    %0:er = COPY $r0
    %1:er = COPY $r1
    %2:edm = COPY $dm0
    %3:es = COPY $s0
    $srssign0 = COPY %1
    $x0 = VSRS_4x_mv_x_srs_dm_srsSign0 %2, %3, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    $srssign0 = MOVX_mvx_cr_imm 0
    $srssign0 = COPY %0
    $x2 = VSRS_4x_mv_x_srs_dm_srsSign0 %2, %3, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    $srssign0 = MOVX_mvx_cr_imm 0
...

# Test 3 - Multiple basic blocks with redundant reassignments.
---
name:            srssign0_redundant_reassignments_multiple_bb
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: srssign0_redundant_reassignments_multiple_bb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r1, $dm0, $s0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:edm = COPY $dm0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:es = COPY $s0
  ; CHECK-NEXT:   $srssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   $x0 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY1]], [[COPY2]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
  ; CHECK-NEXT:   $srssign0 = MOVX_mvx_cr_imm 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   $srssign0 = COPY [[COPY]]
  ; CHECK-NEXT:   $x2 = VSRS_4x_mv_x_srs_dm_srsSign0 [[COPY1]], [[COPY2]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
  ; CHECK-NEXT:   $srssign0 = MOVX_mvx_cr_imm 0
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $r1, $dm0, $s0
    %1:er = COPY $r1
    %2:edm = COPY $dm0
    %3:es = COPY $s0
    $srssign0 = COPY %1
    $x0 = VSRS_4x_mv_x_srs_dm_srsSign0 %2, %3, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    $srssign0 = MOVX_mvx_cr_imm 0

  bb.1:
    $srssign0 = COPY %1
    $x2 = VSRS_4x_mv_x_srs_dm_srsSign0 %2, %3, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    $srssign0 = MOVX_mvx_cr_imm 0
...
