# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=aie-post-select-optimize %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_vst_flush_conv
tracksRegLiveness: true
legalized: true
selected: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0
    ; CHECK-LABEL: name: test_vst_flush_conv
    ; CHECK: liveins: $p0, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_384_CONV_mx6_fp32_:%[0-9]+]]:mstfifo, [[VST_PUSH_384_CONV_mx6_fp32_1:%[0-9]+]]:mpfs, [[VST_PUSH_384_CONV_mx6_fp32_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_384_CONV_mx6_fp32 [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[VST_FLUSH_d_normal_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_normal_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_normal_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_d_normal_flush [[VST_PUSH_384_CONV_mx6_fp32_]], [[VST_PUSH_384_CONV_mx6_fp32_1]], [[VST_PUSH_384_CONV_mx6_fp32_2]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:acc2048 = COPY $dm0
    %2:mpfs = IMPLICIT_DEF
    %3:mstfifo = IMPLICIT_DEF
    %4:mr26_fifo_st = IMPLICIT_DEF
    %8:mstfifo, %7:mpfs, %9:mr26_fifo_st = VST_PUSH_384_CONV_mx6_fp32 %3, %1, %2, %4, implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    %10:mstfifo, %11:mpfs, %12:mr26_fifo_st = VST_FLUSH_normal_flush %8, %7, %9, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

---
name:            test_vst_flush_1d_conv
tracksRegLiveness: true
legalized: true
selected: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0
    ; CHECK-LABEL: name: test_vst_flush_1d_conv
    ; CHECK: liveins: $p0, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_576_CONV_mx9_fp32_:%[0-9]+]]:mstfifo, [[VST_PUSH_576_CONV_mx9_fp32_1:%[0-9]+]]:mpfs, [[VST_PUSH_576_CONV_mx9_fp32_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_576_CONV_mx9_fp32 [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_d_fifo_1d_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_fifo_1d_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_fifo_1d_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_d_fifo_1d_flush [[VST_PUSH_576_CONV_mx9_fp32_]], [[VST_PUSH_576_CONV_mx9_fp32_1]], [[VST_PUSH_576_CONV_mx9_fp32_2]], [[DEF3]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:acc2048 = COPY $dm0
    %2:mpfs = IMPLICIT_DEF
    %3:mstfifo = IMPLICIT_DEF
    %4:mr26_fifo_st = IMPLICIT_DEF
    %8:mstfifo, %7:mpfs, %9:mr26_fifo_st = VST_PUSH_576_CONV_mx9_fp32 %3, %1, %2, %4, implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    %10:em = IMPLICIT_DEF
    %11:mstfifo, %12:mpfs, %13:mr26_fifo_st = VST_FLUSH_fifo_1d_flush %8, %7, %9, %10, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

---
name:            test_vst_flush_2d_conv
tracksRegLiveness: true
legalized: true
selected: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0, $d1
    ; CHECK-LABEL: name: test_vst_flush_2d_conv
    ; CHECK: liveins: $p0, $dm0, $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_256_CONV_mx4_fp32_:%[0-9]+]]:mstfifo, [[VST_PUSH_256_CONV_mx4_fp32_1:%[0-9]+]]:mpfs, [[VST_PUSH_256_CONV_mx4_fp32_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_256_CONV_mx4_fp32 [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[VST_FLUSH_d_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_2D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_d_2D3:%[0-9]+]]:edc = VST_FLUSH_d_2D [[VST_PUSH_256_CONV_mx4_fp32_]], [[VST_PUSH_256_CONV_mx4_fp32_1]], [[VST_PUSH_256_CONV_mx4_fp32_2]], [[COPY1]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:acc2048 = COPY $dm0
    %3:mpfs = IMPLICIT_DEF
    %4:mstfifo = IMPLICIT_DEF
    %5:mr26_fifo_st = IMPLICIT_DEF
    %9:mstfifo, %8:mpfs, %10:mr26_fifo_st = VST_PUSH_256_CONV_mx4_fp32 %4, %1, %3, %5, implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    %12:ed = COPY $d1
    %13:mstfifo, %14:mpfs, %15:mr26_fifo_st, %16:edc = VST_FLUSH_2D %9, %8, %10, %12, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

---
name:            test_vst_flush_3d_conv_chain
tracksRegLiveness: true
legalized: true
selected: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0, $d1
    ; CHECK-LABEL: name: test_vst_flush_3d_conv_chain
    ; CHECK: liveins: $p0, $dm0, $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_384_CONV_mx6_fp32_:%[0-9]+]]:mstfifo, [[VST_PUSH_384_CONV_mx6_fp32_1:%[0-9]+]]:mpfs, [[VST_PUSH_384_CONV_mx6_fp32_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_384_CONV_mx6_fp32 [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[VST_FLUSH_d_normal_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_normal_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_normal_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_d_normal_flush [[VST_PUSH_384_CONV_mx6_fp32_]], [[VST_PUSH_384_CONV_mx6_fp32_1]], [[VST_PUSH_384_CONV_mx6_fp32_2]], implicit-def $srfifo_of
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: [[VST_FLUSH_d_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_3D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_d_3D3:%[0-9]+]]:edcl, [[VST_FLUSH_d_3D4:%[0-9]+]]:edch = VST_FLUSH_d_3D [[VST_FLUSH_d_normal_flush]], [[VST_FLUSH_d_normal_flush1]], [[VST_FLUSH_d_normal_flush2]], [[COPY1]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:acc2048 = COPY $dm0
    %2:mpfs = IMPLICIT_DEF
    %3:mstfifo = IMPLICIT_DEF
    %4:mr26_fifo_st = IMPLICIT_DEF
    %8:mstfifo, %7:mpfs, %9:mr26_fifo_st = VST_PUSH_384_CONV_mx6_fp32 %3, %1, %2, %4, implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    %10:mstfifo, %11:mpfs, %12:mr26_fifo_st = VST_FLUSH_normal_flush %8, %7, %9, implicit-def $srfifo_of
    %13:eds = COPY $d1_3d
    %14:mstfifo, %15:mpfs, %16:mr26_fifo_st, %17:edcl, %18:edch = VST_FLUSH_3D %10, %11, %12, %13, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

---
name:            test_vst_push_multi_use_by_vst_flush
tracksRegLiveness: true
legalized: true
selected: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0, $d1
    ; CHECK-LABEL: name: test_vst_push_multi_use_by_vst_flush
    ; CHECK: liveins: $p0, $dm0, $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_576_CONV_mx9_fp32_:%[0-9]+]]:mstfifo, [[VST_PUSH_576_CONV_mx9_fp32_1:%[0-9]+]]:mpfs, [[VST_PUSH_576_CONV_mx9_fp32_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_576_CONV_mx9_fp32 [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:em = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_d_fifo_1d_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_fifo_1d_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_fifo_1d_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_d_fifo_1d_flush [[VST_PUSH_576_CONV_mx9_fp32_]], [[VST_PUSH_576_CONV_mx9_fp32_1]], [[VST_PUSH_576_CONV_mx9_fp32_2]], [[DEF3]], implicit-def $srfifo_of
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[VST_FLUSH_d_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_d_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_d_2D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_d_2D3:%[0-9]+]]:edc = VST_FLUSH_d_2D [[VST_PUSH_576_CONV_mx9_fp32_]], [[VST_PUSH_576_CONV_mx9_fp32_1]], [[VST_PUSH_576_CONV_mx9_fp32_2]], [[COPY1]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:acc2048 = COPY $dm0
    %2:mpfs = IMPLICIT_DEF
    %3:mstfifo = IMPLICIT_DEF
    %4:mr26_fifo_st = IMPLICIT_DEF
    %8:mstfifo, %7:mpfs, %9:mr26_fifo_st = VST_PUSH_576_CONV_mx9_fp32 %3, %1, %2, %4, implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    %10:em = IMPLICIT_DEF
    %11:mstfifo, %12:mpfs, %13:mr26_fifo_st = VST_FLUSH_fifo_1d_flush %8, %7, %9, %10, implicit-def $srfifo_of
    %17:ed = COPY $d1
    %14:mstfifo, %15:mpfs, %16:mr26_fifo_st, %18:edc = VST_FLUSH_2D %8, %7, %9, %17, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

# Negative test case: VST_FLUSH is not combined into VST_FLUSH_CONV, as it is not a user of VST_PUSH_CONV.
---
name:            test_vst_flush_2d_conv_neg
tracksRegLiveness: true
legalized: true
selected: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $dm0, $d1
    ; CHECK-LABEL: name: test_vst_flush_2d_conv_neg
    ; CHECK: liveins: $p0, $dm0, $d1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc2048 = COPY $dm0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_384_CONV_mx6_fp32_:%[0-9]+]]:mstfifo, [[VST_PUSH_384_CONV_mx6_fp32_1:%[0-9]+]]:mpfs, [[VST_PUSH_384_CONV_mx6_fp32_2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_384_CONV_mx6_fp32 [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ed = COPY $d1
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_FLUSH_2D:%[0-9]+]]:mstfifo, [[VST_FLUSH_2D1:%[0-9]+]]:mpfs, [[VST_FLUSH_2D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_2D3:%[0-9]+]]:edc = VST_FLUSH_2D [[DEF4]], [[DEF3]], [[DEF5]], [[COPY1]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:acc2048 = COPY $dm0
    %3:mpfs = IMPLICIT_DEF
    %4:mstfifo = IMPLICIT_DEF
    %5:mr26_fifo_st = IMPLICIT_DEF
    %9:mstfifo, %8:mpfs, %10:mr26_fifo_st = VST_PUSH_384_CONV_mx6_fp32 %4, %1, %3, %5, implicit-def $srf2bflags, implicit-def $srfifo_of, implicit $crf2bmask, implicit $crrnd
    %12:ed = COPY $d1
    %13:mpfs = IMPLICIT_DEF
    %14:mstfifo = IMPLICIT_DEF
    %15:mr26_fifo_st = IMPLICIT_DEF
    %16:mstfifo, %17:mpfs, %18:mr26_fifo_st, %19:edc = VST_FLUSH_2D %14, %13, %15, %12, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

# Negative test case: VST_FLUSH is not combined into VST_FLUSH_CONV, as its def is VST_PUSH not VST_PUSH_CONV.
---
name:            test_vst_flush_3d_conv_chain_neg
tracksRegLiveness: true
legalized: true
selected: true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $d1, $x0
    ; CHECK-LABEL: name: test_vst_flush_3d_conv_chain_neg
    ; CHECK: liveins: $p0, $d1, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:mpfs = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mstfifo = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:mr26_fifo_st = IMPLICIT_DEF
    ; CHECK-NEXT: [[VST_PUSH_512_dmx_sts_fifo_bare_x:%[0-9]+]]:mstfifo, [[VST_PUSH_512_dmx_sts_fifo_bare_x1:%[0-9]+]]:mpfs, [[VST_PUSH_512_dmx_sts_fifo_bare_x2:%[0-9]+]]:mr26_fifo_st = VST_PUSH_512_dmx_sts_fifo_bare_x [[DEF1]], [[COPY]], [[DEF]], [[DEF2]], implicit-def $srfifo_of
    ; CHECK-NEXT: [[VST_FLUSH_normal_flush:%[0-9]+]]:mstfifo, [[VST_FLUSH_normal_flush1:%[0-9]+]]:mpfs, [[VST_FLUSH_normal_flush2:%[0-9]+]]:mr26_fifo_st = VST_FLUSH_normal_flush [[VST_PUSH_512_dmx_sts_fifo_bare_x]], [[VST_PUSH_512_dmx_sts_fifo_bare_x1]], [[VST_PUSH_512_dmx_sts_fifo_bare_x2]], implicit-def $srfifo_of
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d1_3d
    ; CHECK-NEXT: [[VST_FLUSH_3D:%[0-9]+]]:mstfifo, [[VST_FLUSH_3D1:%[0-9]+]]:mpfs, [[VST_FLUSH_3D2:%[0-9]+]]:mr26_fifo_st, [[VST_FLUSH_3D3:%[0-9]+]]:edcl, [[VST_FLUSH_3D4:%[0-9]+]]:edch = VST_FLUSH_3D [[VST_FLUSH_normal_flush]], [[VST_FLUSH_normal_flush1]], [[VST_FLUSH_normal_flush2]], [[COPY1]], implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:vec512 = COPY $x0
    %2:mpfs = IMPLICIT_DEF
    %3:mstfifo = IMPLICIT_DEF
    %4:mr26_fifo_st = IMPLICIT_DEF
    %8:mstfifo, %7:mpfs, %9:mr26_fifo_st = VST_PUSH_512_dmx_sts_fifo_bare_x %3, %0, %2, %4, implicit-def $srfifo_of
    %10:mstfifo, %11:mpfs, %12:mr26_fifo_st = VST_FLUSH_normal_flush %8, %7, %9, implicit-def $srfifo_of
    %13:eds = COPY $d1_3d
    %14:mstfifo, %15:mpfs, %16:mr26_fifo_st, %17:edcl, %18:edch = VST_FLUSH_3D %10, %11, %12, %13, implicit-def $srfifo_of
    PseudoRET implicit $lr
...
