# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s

---
# Positive test: Basic I512 SRS split pattern
# The 512-bit SRS intrinsic feeding stores should be split into two 256-bit SRS operations
name: test_split_i512_srs_basic
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_basic
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s32>), [[UV1:%[0-9]+]]:_(<32 x s32>) = G_UNMERGE_VALUES %acc(<64 x s32>)
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), [[UV]](<32 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), [[UV1]](<32 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %lo:_(<8 x s32>) = G_BITCAST [[INT]](<32 x s8>)
    ; CHECK-NEXT: %hi:_(<8 x s32>) = G_BITCAST [[INT1]](<32 x s8>)
    ; CHECK-NEXT: G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: G_STORE %hi(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    G_STORE %hi(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
...

---
# Positive test: Stores to different pointers
name: test_split_i512_srs_different_ptrs
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0, $p1


    ; CHECK-LABEL: name: test_split_i512_srs_different_ptrs
    ; CHECK: liveins: $dm0, $r0, $r1, $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr1:_(p0) = COPY $p0
    ; CHECK-NEXT: %ptr2:_(p0) = COPY $p1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<32 x s32>), [[UV1:%[0-9]+]]:_(<32 x s32>) = G_UNMERGE_VALUES %acc(<64 x s32>)
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), [[UV]](<32 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), [[UV1]](<32 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %lo:_(<8 x s32>) = G_BITCAST [[INT]](<32 x s8>)
    ; CHECK-NEXT: %hi:_(<8 x s32>) = G_BITCAST [[INT1]](<32 x s8>)
    ; CHECK-NEXT: G_STORE %lo(<8 x s32>), %ptr1(p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: G_STORE %hi(<8 x s32>), %ptr2(p0) :: (store (<8 x s32>))
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr1:_(p0) = COPY $p0
    %ptr2:_(p0) = COPY $p1

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    G_STORE %lo(<8 x s32>), %ptr1(p0) :: (store (<8 x s32>))
    G_STORE %hi(<8 x s32>), %ptr2(p0) :: (store (<8 x s32>))
...

---
# Negative test: Multiple uses of SRS output (should NOT combine)
name: test_split_i512_srs_multiple_srs_uses
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_multiple_srs_uses
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    ; CHECK-NEXT: %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    ; CHECK-NEXT: G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: G_STORE %hi(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: $x0 = COPY %srs(<64 x s8>)
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    G_STORE %hi(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    $x0 = COPY %srs(<64 x s8>)
...

---
# Negative test: Multiple uses of BITCAST output (should NOT combine)
name: test_split_i512_srs_multiple_bitcast_uses
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_multiple_bitcast_uses
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    ; CHECK-NEXT: %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    ; CHECK-NEXT: G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: G_STORE %hi(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: $x0 = COPY %bitcast(<16 x s32>)
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    G_STORE %hi(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    $x0 = COPY %bitcast(<16 x s32>)
...

---
# Negative test: Missing BITCAST (should NOT combine) - Future improvement?
name: test_split_i512_srs_no_bitcast
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_no_bitcast
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %lo:_(<32 x s8>), %hi:_(<32 x s8>) = G_UNMERGE_VALUES %srs(<64 x s8>)
    ; CHECK-NEXT: G_STORE %lo(<32 x s8>), %ptr(p0) :: (store (<32 x s8>))
    ; CHECK-NEXT: G_STORE %hi(<32 x s8>), %ptr(p0) :: (store (<32 x s8>))
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %lo:_(<32 x s8>), %hi:_(<32 x s8>) = G_UNMERGE_VALUES %srs(<64 x s8>)
    G_STORE %lo(<32 x s8>), %ptr(p0) :: (store (<32 x s8>))
    G_STORE %hi(<32 x s8>), %ptr(p0) :: (store (<32 x s8>))
...

---
# Negative test: Missing UNMERGE (should NOT combine)
name: test_split_i512_srs_no_unmerge
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_no_unmerge
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    ; CHECK-NEXT: G_STORE %bitcast(<16 x s32>), %ptr(p0) :: (store (<16 x s32>))
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    G_STORE %bitcast(<16 x s32>), %ptr(p0) :: (store (<16 x s32>))
...

---
# Negative test: Wrong number of UNMERGE outputs (should NOT combine)
name: test_split_i512_srs_wrong_unmerge_count
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_wrong_unmerge_count
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    ; CHECK-NEXT: %a:_(<4 x s32>), %b:_(<4 x s32>), %c:_(<4 x s32>), %d:_(<4 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    ; CHECK-NEXT: G_STORE %a(<4 x s32>), %ptr(p0) :: (store (<4 x s32>))
    ; CHECK-NEXT: G_STORE %b(<4 x s32>), %ptr(p0) :: (store (<4 x s32>))
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    %a:_(<4 x s32>), %b:_(<4 x s32>), %c:_(<4 x s32>), %d:_(<4 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    G_STORE %a(<4 x s32>), %ptr(p0) :: (store (<4 x s32>))
    G_STORE %b(<4 x s32>), %ptr(p0) :: (store (<4 x s32>))
...

---
# Negative test: UNMERGE outputs not used by stores (should NOT combine)
name: test_split_i512_srs_no_store_use
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1


    ; CHECK-LABEL: name: test_split_i512_srs_no_store_use
    ; CHECK: liveins: $dm0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    ; CHECK-NEXT: %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY %lo(<8 x s32>)
    ; CHECK-NEXT: $wl1 = COPY %hi(<8 x s32>)
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    $wl0 = COPY %lo(<8 x s32>)
    $wl1 = COPY %hi(<8 x s32>)
...

---
# Negative test: Only one output used by store (should NOT combine)
name: test_split_i512_srs_partial_store_use
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_partial_store_use
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %ptr:_(p0) = COPY $p0
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    ; CHECK-NEXT: %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    ; CHECK-NEXT: G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    ; CHECK-NEXT: $wl1 = COPY %hi(<8 x s32>)
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %bitcast:_(<16 x s32>) = G_BITCAST %srs(<64 x s8>)
    %lo:_(<8 x s32>), %hi:_(<8 x s32>) = G_UNMERGE_VALUES %bitcast(<16 x s32>)
    G_STORE %lo(<8 x s32>), %ptr(p0) :: (store (<8 x s32>))
    $wl1 = COPY %hi(<8 x s32>)
...

---
# Negative test: SRS not followed by BITCAST (should NOT combine)
name: test_split_i512_srs_wrong_pattern
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $dm0, $r0, $r1, $p0


    ; CHECK-LABEL: name: test_split_i512_srs_wrong_pattern
    ; CHECK: liveins: $dm0, $r0, $r1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %acc:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: %shift:_(s32) = COPY $r0
    ; CHECK-NEXT: %sign:_(s32) = COPY $r1
    ; CHECK-NEXT: %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    ; CHECK-NEXT: %other:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: %concat:_(<128 x s8>) = G_CONCAT_VECTORS %srs(<64 x s8>), %other(<64 x s8>)
    ; CHECK-NEXT: $y2 = COPY %concat(<128 x s8>)
    %acc:_(<64 x s32>) = COPY $dm0
    %shift:_(s32) = COPY $r0
    %sign:_(s32) = COPY $r1
    %ptr:_(p0) = COPY $p0

    %srs:_(<64 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %acc(<64 x s32>), %shift(s32), %sign(s32)
    %other:_(<64 x s8>) = G_IMPLICIT_DEF
    %concat:_(<128 x s8>) = G_CONCAT_VECTORS %srs(<64 x s8>), %other(<64 x s8>)
    $y2 = COPY %concat(<128 x s8>)
...
