# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner  %s -verify-machineinstrs -o - | FileCheck %s


---
name:            extend_to_256_bits
body:             |
  bb.1:
    ; CHECK-LABEL: name: extend_to_256_bits
    ; CHECK: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $eg0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_PAD_VECTOR_UNDEF]](<8 x s32>)
      %0:_(<4 x s32>) = COPY $eg0
      %1:_(<4 x s32>) = G_IMPLICIT_DEF
      %2:_(<8 x s32>) = G_CONCAT_VECTORS %0, %1
      PseudoRET implicit $lr, implicit %2
...

# Simple case where a 128-bit vector is extended to a 512-bit vector
---
name:            extend_to_512_bits
body:             |
  bb.1:
    ; CHECK-LABEL: name: extend_to_512_bits
    ; CHECK: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $eg0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>)
      %0:_(<4 x s32>) = COPY $eg0
      %1:_(<4 x s32>) = G_IMPLICIT_DEF
      %2:_(<16 x s32>) = G_CONCAT_VECTORS %0, %1, %1, %1
      PseudoRET implicit $lr, implicit %2
...


# Cannot combine: not padded with undef
---
name:            no_combine_not_undef_padded
body:             |
  bb.1:
    ; CHECK-LABEL: name: no_combine_not_undef_padded
    ; CHECK: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $eg0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s32>) = COPY $eg1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s32>) = G_CONCAT_VECTORS [[COPY]](<4 x s32>), [[COPY1]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<8 x s32>)
      %0:_(<4 x s32>) = COPY $eg0
      %1:_(<4 x s32>) = COPY $eg1
      %2:_(<8 x s32>) = G_CONCAT_VECTORS %0, %1
      PseudoRET implicit $lr, implicit %2
...

# Cannot combine: no 128-bit input vector
---
name:            no_combine_no_128_bit_input
body:             |
  bb.1:
    ; CHECK-LABEL: name: no_combine_no_128_bit_input
    ; CHECK: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wh0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>)
      %0:_(<8 x s32>) = COPY $wh0
      %1:_(<8 x s32>) = G_IMPLICIT_DEF
      %2:_(<16 x s32>) = G_CONCAT_VECTORS %0, %1
      PseudoRET implicit $lr, implicit %2
...
