# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner  %s -verify-machineinstrs -o - | FileCheck %s

---
name: shuffle_vector_to_concat_vector1
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l0

    ; CHECK-LABEL: name: shuffle_vector_to_concat_vector1
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s8>) = COPY $r1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s8>) = G_CONCAT_VECTORS [[COPY]](<4 x s8>), [[COPY1]](<4 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<8 x s8>)
    %0:_(<4 x s8>) = COPY $r0
    %1:_(<4 x s8>) = COPY $r1
    %2:_(<8 x s8>) = G_SHUFFLE_VECTOR %0(<4 x s8>), %1(<4 x s8>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_vector_to_concat_vector
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1

    ; CHECK-LABEL: name: shuffle_vector_to_concat_vector
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY]](<8 x s32>), [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = COPY $wl1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<8 x s32>), %1(<8 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %2
...
---
name: shuffle_vector_2x32Src
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l0

    ; CHECK-LABEL: name: shuffle_vector_2x32Src
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $l0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    %1:_(<2 x s32>) = COPY $l0
    %2:_(<2 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<2 x s32>), %2, shufflemask(0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_4x16Src
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l0

    ; CHECK-LABEL: name: shuffle_vector_4x16Src
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s16>) = COPY $l0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](<4 x s16>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<16 x s16>)
    %1:_(<4 x s16>) = COPY $l0
    %2:_(<4 x s16>) = G_IMPLICIT_DEF
    %0:_(<16 x s16>) = G_SHUFFLE_VECTOR %1(<4 x s16>), %2, shufflemask(0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_8x8Src
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $l0

    ; CHECK-LABEL: name: shuffle_vector_8x8Src
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s8>) = COPY $l0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](<8 x s8>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<32 x s8>)
    %1:_(<8 x s8>) = COPY $l0
    %2:_(<8 x s8>) = G_IMPLICIT_DEF
    %0:_(<32 x s8>) = G_SHUFFLE_VECTOR %1(<8 x s8>), %2, shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_2x16Src
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0
    ; CHECK-LABEL: name: shuffle_vector_2x16Src
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s16>) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](<2 x s16>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<16 x s16>)
    %1:_(<2 x s16>) = COPY $r0
    %2:_(<2 x s16>) = G_IMPLICIT_DEF
    %0:_(<16 x s16>) = G_SHUFFLE_VECTOR %1(<2 x s16>), %2, shufflemask(0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_4x8Src
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r0
    ; CHECK-LABEL: name: shuffle_vector_4x8Src
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s8>) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](<4 x s8>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<32 x s8>)
    %1:_(<4 x s8>) = COPY $r0
    %2:_(<4 x s8>) = G_IMPLICIT_DEF
    %0:_(<32 x s8>) = G_SHUFFLE_VECTOR %1(<4 x s8>), %2, shufflemask(0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_all_undef
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_all_undef
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[DEF]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_valid_mask_16_s32
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_valid_mask_16_s32
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65520
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[DEF]], [[COPY]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_valid_mask_32_s16
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_valid_mask_32_s16
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<32 x s16>) = G_AIE_VSEL [[DEF]], [[COPY]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<32 x s16>)
    %1:_(<32 x s16>) = COPY $x2
    %8:_(<32 x s16>) = G_IMPLICIT_DEF
    %0:_(<32 x s16>) = G_SHUFFLE_VECTOR %8(<32 x s16>), %1, shufflemask(0, 33, 2, 35, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_valid_mask_64_s8
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_valid_mask_64_s8
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 5
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<64 x s8>) = G_AIE_VSEL [[DEF]], [[COPY]], [[C]](s64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<64 x s8>)
    %1:_(<64 x s8>) = COPY $x2
    %8:_(<64 x s8>) = G_IMPLICIT_DEF
    %0:_(<64 x s8>) = G_SHUFFLE_VECTOR %8(<64 x s8>), %1, shufflemask(64, 1, 66, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_valid_mask_ordered_indices_with_undef
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_valid_mask_ordered_indices_with_undef
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65520
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[DEF]], [[COPY]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(-1, -1, -1, -1, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_valid_mask_with_undef
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_valid_mask_with_undef
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 64992
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[DEF]], [[COPY]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(0, 1, 2, -1, -1, 21, 22, 23, 24, -1, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_valid_mask_mixed_indices
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_valid_mask_mixed_indices
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65521
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[DEF]], [[COPY]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(16, 1, 2, 3, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_valid_mask_mixed_indices_with_undef
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_valid_mask_mixed_indices_with_undef
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 64465
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[DEF]], [[COPY]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(16, 1, -1, 3, 20, -1, 22, 23, 24, 25, -1, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_invalid_mask
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_invalid_mask
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[DEF]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[DEF1]](s32), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_invalid_mask_with_repeated_index
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_invalid_mask_with_repeated_index
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<16 x s32>) = G_SHUFFLE_VECTOR [[DEF]](<16 x s32>), [[COPY]], shufflemask(0, 1, 2, 3, 16, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 16, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_invalid_mask_with_unordered_indices
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_invalid_mask_with_unordered_indices
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<16 x s32>) = G_SHUFFLE_VECTOR [[DEF]](<16 x s32>), [[COPY]], shufflemask(1, 0, 2, 3, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %8:_(<16 x s32>) = G_IMPLICIT_DEF
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %8(<16 x s32>), %1, shufflemask(1, 0, 2, 3, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_vsel_invalid_s64
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl4, $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_invalid_s64
    ; CHECK: liveins: $r0, $wl4, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<8 x s64>) = G_SHUFFLE_VECTOR [[DEF]](<8 x s64>), [[COPY]], shufflemask(8, 1, 2, 3, 12, 13, 14, 15)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<8 x s64>)
    %1:_(<8 x s64>) = COPY $x2
    %8:_(<8 x s64>) = G_IMPLICIT_DEF
    %0:_(<8 x s64>) = G_SHUFFLE_VECTOR %8(<8 x s64>), %1, shufflemask(8, 1, 2, 3, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_broadcast_vecElem
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1

    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_vecElem
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = COPY $wl1
    %2:_(<8 x s32>) = G_SHUFFLE_VECTOR %0(<8 x s32>), %1(<8 x s32>), shufflemask(2, 2, 2, 2, 2, 2, 2, 2)
    PseudoRET implicit $lr, implicit %2
...
---
name: shuffle_vector_to_extract_broadcast_s16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_s16
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[AIE_SEXT_EXTRACT_VECTOR_ELT:%[0-9]+]]:_(s32) = G_AIE_SEXT_EXTRACT_VECTOR_ELT [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[ASSERT_SEXT:%[0-9]+]]:_(s32) = G_ASSERT_SEXT [[AIE_SEXT_EXTRACT_VECTOR_ELT]], 16
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[ASSERT_SEXT]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<16 x s16>)
    %0:_(<16 x s16>) = COPY $wl0
    %1:_(<16 x s16>) = COPY $wl1
    %2:_(<16 x s16>) = G_SHUFFLE_VECTOR %0(<16 x s16>), %1(<16 x s16>), shufflemask(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
    PseudoRET implicit $lr, implicit %2
...
---
name: shuffle_vector_to_extract_broadcast_vecElem_undef
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1

    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_vecElem_undef
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %0:_(<8 x s32>) = COPY $wl0
    %1:_(<8 x s32>) = COPY $wl1
    %2:_(<8 x s32>) = G_SHUFFLE_VECTOR %0(<8 x s32>), %1(<8 x s32>), shufflemask(2, 2, -1, -1, 2, 2, 2, 2)
    PseudoRET implicit $lr, implicit %2
...
---
name: shuffle_vector_to_extract_broadcast_vecElem_neg_test
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1

    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_vecElem_neg_test
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s64>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s64>) = COPY $wl1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<8 x s64>) = G_SHUFFLE_VECTOR [[COPY]](<4 x s64>), [[COPY1]], shufflemask(3, 2, undef, undef, 3, 3, 3, 3)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<8 x s64>)
    %0:_(<4 x s64>) = COPY $wl0
    %1:_(<4 x s64>) = COPY $wl1
    %2:_(<8 x s64>) = G_SHUFFLE_VECTOR %0(<4 x s64>), %1(<4 x s64>), shufflemask(3, 2, -1, -1, 3, 3, 3, 3)
    PseudoRET implicit $lr, implicit %2
...

# Tests for combining shuffle_vector to extract_subvector
# Test destination vector types with native source vector type (512 bits)
---
name: shuffle_vector_to_extract_subvec_4xs8Dst
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_4xs8Dst
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<4 x s8>) = G_AIE_EXTRACT_SUBVECTOR [[COPY]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<4 x s8>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %0:_(<4 x s8>) = G_SHUFFLE_VECTOR %1(<64 x s8>), %2(<64 x s8>), shufflemask(4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_subvec_2xs16Dst
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_2xs16Dst
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s16>) = G_AIE_EXTRACT_SUBVECTOR [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<2 x s16>)
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %0:_(<2 x s16>) = G_SHUFFLE_VECTOR %1(<32 x s16>), %2(<32 x s16>), shufflemask(0, 1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_subvec_8xs8Dst
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_8xs8Dst
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<8 x s8>) = G_AIE_EXTRACT_SUBVECTOR [[COPY]](<64 x s8>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<8 x s8>)
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %0:_(<8 x s8>) = G_SHUFFLE_VECTOR %1(<64 x s8>), %2(<64 x s8>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_subvec_4xs16Dst
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_4xs16Dst
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<4 x s16>) = G_AIE_EXTRACT_SUBVECTOR [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<4 x s16>)
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %0:_(<4 x s16>) = G_SHUFFLE_VECTOR %1(<32 x s16>), %2(<32 x s16>), shufflemask(4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_subvec_2xs32Dst
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_2xs32Dst
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<2 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<2 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(0, 1)
    PseudoRET implicit $lr, implicit %0
...

# Test not native source vector types
---
name: shuffle_vector_to_extract_subvec_256BitSrc
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_256BitSrc
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<2 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<2 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_subvec_1024BitSrc
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $y0, $y1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_1024BitSrc
    ; CHECK: liveins: $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR [[UV1]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<2 x s32>)
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %0:_(<2 x s32>) = G_SHUFFLE_VECTOR %1(<32 x s32>), %2(<32 x s32>), shufflemask(16, 17)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_subvec_2048BitSrc
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $dm0, $dm1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_2048BitSrc
    ; CHECK: liveins: $dm0, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>), [[UV2:%[0-9]+]]:_(<16 x s32>), [[UV3:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[COPY]](<64 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR [[UV]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<2 x s32>)
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(<64 x s32>) = COPY $dm1
    %0:_(<2 x s32>) = G_SHUFFLE_VECTOR %1(<64 x s32>), %2(<64 x s32>), shufflemask(0, 1)
    PseudoRET implicit $lr, implicit %0
...

# Test undefs and invalid masks for extract_subvector
---
name: shuffle_vector_to_extract_subvec_with_undef
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_with_undef
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<4 x s16>) = G_AIE_EXTRACT_SUBVECTOR [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_EXTRACT_SUBVECTOR]](<4 x s16>)
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %0:_(<4 x s16>) = G_SHUFFLE_VECTOR %1(<32 x s16>), %2(<32 x s16>), shufflemask(4, -1, -1, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_subvec_invalid_extract_insert_elt_valid
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_subvec_invalid_extract_insert_elt_valid
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<8 x s64>) = G_INSERT_VECTOR_ELT [[COPY]], [[EVEC]](s64), [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC]](<8 x s64>)
    %1:_(<8 x s64>) = COPY $x0
    %2:_(<8 x s64>) = COPY $x1
    %0:_(<8 x s64>) = G_SHUFFLE_VECTOR %1(<8 x s64>), %2(<8 x s64>), shufflemask(-1, 5, -1, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...

# Test extract and broadcast a subvector
---
name: shuffle_vector_to_extract_broadcast_subvec_seq_size_2
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_subvec_seq_size_2
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[AIE_EXTRACT_SUBVECTOR]](<2 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(0, 1, 0, 1, 0, 1, 0, 1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_broadcast_subvec_with_undef_start
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_subvec_with_undef_start
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[AIE_EXTRACT_SUBVECTOR]](<2 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(-1, 1, 0, 1, 0, 1, 0, 1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_broadcast_subvec_with_many_undefs
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_subvec_with_many_undefs
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<2 x s32>) = G_AIE_EXTRACT_SUBVECTOR [[AIE_PAD_VECTOR_UNDEF]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[AIE_EXTRACT_SUBVECTOR]](<2 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(0, -1, -1, 1, -1, -1, -1, 1)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_broadcast_subvec_seq_size_2_no_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_subvec_seq_size_2_no_combine
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<8 x s32>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[EVEC1]](s32), [[C2]](s32)
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<8 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[EVEC2]](s32), [[C]](s32)
    ; CHECK-NEXT: [[EVEC3:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC2:%[0-9]+]]:_(<8 x s32>) = G_INSERT_VECTOR_ELT [[IVEC1]], [[EVEC3]](s32), [[C3]](s32)
    ; CHECK-NEXT: [[EVEC4:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[IVEC3:%[0-9]+]]:_(<8 x s32>) = G_INSERT_VECTOR_ELT [[IVEC2]], [[EVEC4]](s32), [[C4]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC3]](<8 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(1, 2, 1, 2, 1, 2, 1, 2)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_extract_broadcast_subvec_seq_size_4
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_subvec_seq_size_4
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[AIE_PAD_VECTOR_UNDEF:%[0-9]+]]:_(<32 x s16>) = G_AIE_PAD_VECTOR_UNDEF [[COPY]](<16 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AIE_EXTRACT_SUBVECTOR:%[0-9]+]]:_(<4 x s16>) = G_AIE_EXTRACT_SUBVECTOR [[AIE_PAD_VECTOR_UNDEF]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[AIE_EXTRACT_SUBVECTOR]](<4 x s16>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<16 x s16>)
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(<16 x s16>) = COPY $wl1
    %0:_(<16 x s16>) = G_SHUFFLE_VECTOR %1(<16 x s16>), %2(<16 x s16>), shufflemask(4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
# The test is not covered by ExtractSubvecBroadcast because we can extract subvectors only of 32- or 64-bit sizes.
---
name: shuffle_vector_to_extract_broadcast_subvec_invalid_exctract_subvec_srcsize
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $dm0, $dm1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_broadcast_subvec_invalid_exctract_subvec_srcsize
    ; CHECK: liveins: $dm0, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<64 x s32>)
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(<64 x s32>) = COPY $dm1
    %0:_(<64 x s32>) = G_SHUFFLE_VECTOR %1(<64 x s32>), %2(<64 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
    PseudoRET implicit $lr, implicit %0
...

# Test G_SHUFFLE_VECTOR to UNMERGE
# Note: G_UNMERGE_VALUES is itself combined to G_AIE_UNPAD_VECTOR
---
name: shuffle_vector_unmerge_lo
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_unmerge_lo
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_unmerge_lo_4_unmerge_outputs
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $y0, $y1
    ; CHECK-LABEL: name: shuffle_vector_unmerge_lo_4_unmerge_outputs
    ; CHECK: liveins: $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>), [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV]](<8 x s32>)
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<32 x s32>), %2(<32 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_unmerge_hi_128
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_unmerge_hi_128
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<4 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<4 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_unmerge_hi_256
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_unmerge_hi_256
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<8 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(8, 9, 10, 11, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_unmerge_hi_512
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $y0, $y1
    ; CHECK-LABEL: name: shuffle_vector_unmerge_hi_512
    ; CHECK: liveins: $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s32>), [[UV1:%[0-9]+]]:_(<16 x s32>) = G_UNMERGE_VALUES [[COPY]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<16 x s32>)
    %1:_(<32 x s32>) = COPY $y0
    %2:_(<32 x s32>) = COPY $y1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<32 x s32>), %2(<32 x s32>), shufflemask(16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_unmerge_hi_1024
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $dm0, $dm1
    ; CHECK-LABEL: name: shuffle_vector_unmerge_hi_1024
    ; CHECK: liveins: $dm0, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<16 x s64>), [[UV1:%[0-9]+]]:_(<16 x s64>) = G_UNMERGE_VALUES [[COPY]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<16 x s64>)
    %1:_(<32 x s64>) = COPY $dm0
    %2:_(<32 x s64>) = COPY $dm1
    %0:_(<16 x s64>) = G_SHUFFLE_VECTOR %1(<32 x s64>), %2(<32 x s64>), shufflemask(16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_subreg_boundary_cross_invalid
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_subreg_boundary_cross_invalid
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<8 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<16 x s32>), [[COPY1]], shufflemask(4, 5, 6, 7, 8, 9, 10, 11)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<8 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(4, 5, 6, 7, 8, 9, 10, 11)
    PseudoRET implicit $lr, implicit %0
...

# Combine G_SHUFFLE_VECTOR into COPY
---
name: shuffle_vector_to_copy_scalar
tracksRegLiveness: true
body:             |
  bb.1:
    ; CHECK-LABEL: name: shuffle_vector_to_copy_scalar
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[C]](s32)
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_CONSTANT i32 1
    %0:_(s32) = G_SHUFFLE_VECTOR %1(s32), %2(s32), shufflemask(0)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_copy_vec
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_copy_vec
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %0
...
# Note: currently not commutable
---
name:            shufflevector_to_copy_commutable
alignment:       4
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $l0, $l1
    ; CHECK-LABEL: name: shufflevector_to_copy_commutable
    ; CHECK: liveins: $l0, $l1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $l1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<2 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<2 x s32>), [[COPY1]], shufflemask(2, 3)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<2 x s32>)
    %0:_(<2 x s32>) = COPY $l0
    %1:_(<2 x s32>) = COPY $l1
    %2:_(<2 x s32>) = G_SHUFFLE_VECTOR %0(<2 x s32>), %1, shufflemask(2,3)
    PseudoRET implicit $lr, implicit %2
...
---
name: shuffle_vector_to_copy_vec_with_undef
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_copy_vec_with_undef
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(0, 1, 2, -1, 4, 5, 6, 7, 8, -1, 10, 11, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_copy_vec_no_combine_extract_insert_elt_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_vector_to_copy_vec_no_combine_extract_insert_elt_combine
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<8 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<8 x s32>) = G_INSERT_VECTOR_ELT [[COPY]], [[EVEC]](s32), [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC]](<8 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 2)
    PseudoRET implicit $lr, implicit %0
...

---
name: shuffle_vector_to_subvec_vsel
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_subvec_vsel
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 254
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[COPY]], [[COPY1]], [[C]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_UNPAD_VECTOR]](<8 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2, shufflemask(0, 17, 18, 19, 20, 21, 22, 23)
    PseudoRET implicit $lr, implicit %0
...
---
name: shuffle_vector_to_subvec_vsel_high
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_subvec_vsel_high
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 126
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[COPY]], [[COPY1]], [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[AIE_VSEL]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[UV1]](<8 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2, shufflemask(8, 25, 26, 27, 28, 29, 30, 15)
    PseudoRET implicit $lr, implicit %0
...
---
# This used to access the Mask out-of-bound
name: shuffle_vector_to_subvec_vsel_wrong_start
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_subvec_vsel_wrong_start
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<8 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<16 x s32>), [[COPY1]], shufflemask(1, 17, 18, 19, 20, 21, 22, 23)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<8 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2, shufflemask(1, 17, 18, 19, 20, 21, 22, 23)
    PseudoRET implicit $lr, implicit %0
...


# Test G_SHUFFLE_VECTOR to UNMERGE+CONCAT
---
name: shuffle_vector_to_unmerge_concat_lo
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_unmerge_concat_lo
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...

---
name: shuffle_vector_to_unmerge_concat_hi
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_unmerge_concat_hi
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[UV1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(8, 9, 10, 11, 12, 13, 14, 15, 8, 9, 10, 11, 12, 13, 14, 15)
    PseudoRET implicit $lr, implicit %0
...


# TODO: We should be able to handle this swap pattern with an unmerge and concat
---
name: shuffle_vector_to_unmerge_concat_lo_hi
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_unmerge_concat_lo_hi
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<8 x s32>), [[AIE_UNPAD_VECTOR]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7)
    PseudoRET implicit $lr, implicit %0
...


---
name: shuffle_vector_to_subvec_broadcast
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_subvec_broadcast
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 0, 1, 2, 3, undef, undef, undef, undef, undef, undef, undef, undef)
    PseudoRET implicit $lr, implicit %2
...


---
name: shuffle_vector_to_subvec_broadcast_large
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $y0, $y1
    ; CHECK-LABEL: name: shuffle_vector_to_subvec_broadcast_large
    ; CHECK: liveins: $y0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s32>) = COPY $y0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>), [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY]](<32 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[UV2]](<8 x s32>), [[UV2]](<8 x s32>), [[UV2]](<8 x s32>), [[UV2]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<32 x s32>)
    %0:_(<32 x s32>) = COPY $y0
    %1:_(<32 x s32>) = COPY $y1
    %2:_(<32 x s32>) = G_SHUFFLE_VECTOR %0(<32 x s32>), %1, shufflemask(16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, undef, 20, 21, 22, undef, 16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, 19, 20, 21, 22, 23)
    PseudoRET implicit $lr, implicit %2
...


---
name: shuffle_vector_to_extract_insert_elt_one_exception_second_input
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_insert_elt_one_exception_second_input
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[COPY1]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[COPY]], [[EVEC]](s16), [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC]](<32 x s16>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x1
    %2:_(<32 x s16>) = G_SHUFFLE_VECTOR %0:_(<32 x s16>), %1:_, shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 32, 9, 10, 11, 12, 13, 14, 15, undef, 17, 18, 19, 20, 21, 22, 23, undef, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_vector_to_extract_insert_elt_one_exception_first_input
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_insert_elt_one_exception_first_input
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[COPY]], [[EVEC]](s16), [[C1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC]](<32 x s16>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x1
    %2:_(<32 x s16>) = G_SHUFFLE_VECTOR %0:_(<32 x s16>), %1:_, shufflemask(0, 1, 2, 3, 17, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, undef, 17, 18, 19, 20, 21, 22, 23, undef, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_vector_to_extract_insert_elt_two_exceptions
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_insert_elt_two_exceptions
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[COPY1]](<32 x s16>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[COPY]], [[EVEC]](s16), [[C1]](s32)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s16) = G_EXTRACT_VECTOR_ELT [[COPY]](<32 x s16>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[IVEC]], [[EVEC1]](s16), [[C2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC1]](<32 x s16>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x1
    %2:_(<32 x s16>) = G_SHUFFLE_VECTOR %0:_(<32 x s16>), %1:_, shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 32, 9, 10, 11, 12, 13, 8, 15, 16, 17, 18, 19, 20, 21, 22, 23, undef, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_vector_to_extract_insert_elt_beyond_max_exceptions_no_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_insert_elt_beyond_max_exceptions_no_combine
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<16 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<16 x s32>), [[COPY1]], shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1, 0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1, 0)
    PseudoRET implicit $lr, implicit %0
...

---
name: shuffle_vector_to_extract_insert_elt_max_exceptions_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_vector_to_extract_insert_elt_max_exceptions_combine
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[COPY]], [[EVEC]](s32), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC1]](s64)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[UV1]](s32), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: [[IVEC2:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC1]], [[UV]](s32), [[C4]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST1]](<8 x s64>), [[C5]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC2]](s64)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK-NEXT: [[IVEC3:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC2]], [[UV3]](s32), [[C6]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[IVEC4:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC3]], [[UV2]](s32), [[C7]](s32)
    ; CHECK-NEXT: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC3:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST2]](<8 x s64>), [[C8]](s32)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC3]](s64)
    ; CHECK-NEXT: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK-NEXT: [[IVEC5:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC4]], [[UV5]](s32), [[C9]](s32)
    ; CHECK-NEXT: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[IVEC6:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC5]], [[UV4]](s32), [[C10]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC6]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x1
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<16 x s32>), %2(<16 x s32>), shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 6, 5, 4, 3, 2, 1, 0)
    PseudoRET implicit $lr, implicit %0
...

# TODO: We should be able to combine using extract+broadcast instead of unmerge+concat for this case
---
name: shuffle_vector_to_subvec_illegal_concat_no_combine
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y0, $eg0
    ; CHECK-LABEL: name: shuffle_vector_to_subvec_illegal_concat_no_combine
    ; CHECK: liveins: $y0, $eg0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $eg0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i20 0
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<16 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<4 x s32>), [[COPY]], shufflemask(2, 3, 2, 3, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef)
    ; CHECK-NEXT: G_STORE [[SHUF]](<16 x s32>), [[C]](p0) :: (store (<16 x s32>), align 32, addrspace 5)
    %2:_(s32) = G_CONSTANT i32 0
    %1:_(<4 x s32>) = COPY $eg0
    %4:_(<16 x s32>) = COPY $x1
    %5:_(p0) = G_CONSTANT i20 0
    %0:_(<16 x s32>) = G_SHUFFLE_VECTOR %1(<4 x s32>), %1, shufflemask(2, 3, 2, 3, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef, undef)
    G_STORE %0(<16 x s32>), %5(p0) :: (store (<16 x s32>) into unknown-address, addrspace 5, align 32)
...


---
name: shuffle_concat_extracted_subvectors_undefs
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_undefs
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR3:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR1]](<4 x s32>), [[AIE_UNPAD_VECTOR2]](<4 x s32>), [[AIE_UNPAD_VECTOR3]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 0, -1, 2, 3, -1, -1, -1, 7, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...


---
name: shuffle_concat_extracted_subvectors_no_undef_at_extractidx
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_no_undef_at_extractidx
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>), [[UV2:%[0-9]+]]:_(<4 x s32>), [[UV3:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR1]](<4 x s32>), [[UV1]](<4 x s32>), [[AIE_UNPAD_VECTOR2]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_concat_extracted_subvectors_undef_at_extractidx
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_undef_at_extractidx
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>), [[UV2:%[0-9]+]]:_(<4 x s32>), [[UV3:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR2:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR1]](<4 x s32>), [[UV1]](<4 x s32>), [[AIE_UNPAD_VECTOR2]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, -1, -1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...


---
name: shuffle_concat_extracted_subvectors_vecToExtract_sameSize1
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_vecToExtract_sameSize1
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<8 x s32>), [[AIE_UNPAD_VECTOR1]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, undef, undef, undef, undef)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_concat_extracted_subvectors_vecToExtract_sameSize2
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_vecToExtract_sameSize2
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR]](<4 x s32>), [[AIE_UNPAD_VECTOR]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 0, 1, 2, 3, undef, 1, 2, 3, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...


---
name: shuffle_concat_extracted_subvectors_vecToExtract_DiffSize1
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_vecToExtract_DiffSize1
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>), [[UV2:%[0-9]+]]:_(<4 x s32>), [[UV3:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<4 x s32>), [[UV5:%[0-9]+]]:_(<4 x s32>), [[UV6:%[0-9]+]]:_(<4 x s32>), [[UV7:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[UV8:%[0-9]+]]:_(<4 x s32>), [[UV9:%[0-9]+]]:_(<4 x s32>), [[UV10:%[0-9]+]]:_(<4 x s32>), [[UV11:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[UV1]](<4 x s32>), [[UV6]](<4 x s32>), [[UV10]](<4 x s32>), [[AIE_UNPAD_VECTOR]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(4, 5, 6, 7, 8, 9, 10, 11, 24, 25, 26, 27, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_concat_extracted_subvectors_vecToExtract_DiffSize2
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_vecToExtract_DiffSize2
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x s32>), [[UV1:%[0-9]+]]:_(<4 x s32>), [[UV2:%[0-9]+]]:_(<4 x s32>), [[UV3:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(<4 x s32>), [[UV5:%[0-9]+]]:_(<4 x s32>), [[UV6:%[0-9]+]]:_(<4 x s32>), [[UV7:%[0-9]+]]:_(<4 x s32>) = G_UNMERGE_VALUES [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR1:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[AIE_UNPAD_VECTOR]](<4 x s32>), [[UV1]](<4 x s32>), [[UV6]](<4 x s32>), [[AIE_UNPAD_VECTOR1]](<4 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[CONCAT_VECTORS]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...



# Exeptions submask is all exceptions
# Instead we combine using broadcast + element inserts for the allowed number of exceptions to the broadcast pattern
---
name: shuffle_concat_extracted_subvectors_nothing_but_exceptions
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_nothing_but_exceptions
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST]](<8 x s64>), [[C]](s32)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[UV1]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[BITCAST1:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST1]](<8 x s64>), [[C1]](s32)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC1]](s64)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[UV2]](s32), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[UV3]](s32), [[C2]](s32)
    ; CHECK-NEXT: [[BITCAST2:%[0-9]+]]:_(<8 x s64>) = G_BITCAST [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[BITCAST2]](<8 x s64>), [[C2]](s32)
    ; CHECK-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[EVEC2]](s64)
    ; CHECK-NEXT: [[IVEC2:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC1]], [[UV4]](s32), [[C]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[IVEC3:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC2]], [[UV5]](s32), [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC4:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC3]], [[UV]](s32), [[C4]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC4]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5)
    PseudoRET implicit $lr, implicit %2
...


---
name: shuffle_concat_extracted_subvectors_numSubvecs_not_powerOf2
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_numSubvecs_not_powerOf2
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<16 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<16 x s32>), [[COPY1]], shufflemask(0, 1, 2, 3, 0, 1, 2, 3, 4, 1, 2, 3, 0, 1, 2, 3)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 0, 1, 2, 3, 4, 1, 2, 3, 0, 1, 2, 3)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_concat_extracted_subvectors_exceptions_not_contiguous_no_combine
alignment:       16
exposesReturnsTwice: false
legalized:       false
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl4, $x2

    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_exceptions_not_contiguous_no_combine
    ; CHECK: liveins: $r0, $wl4, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s64>) = COPY $x2
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<8 x s64>) = G_SHUFFLE_VECTOR [[DEF]](<8 x s64>), [[COPY]], shufflemask(8, 1, 2, 3, 9, 10, 11, 12)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<8 x s64>)
    %1:_(<8 x s64>) = COPY $x2
    %8:_(<8 x s64>) = G_IMPLICIT_DEF
    %0:_(<8 x s64>) = G_SHUFFLE_VECTOR %8(<8 x s64>), %1, shufflemask(8, 1, 2, 3, 9, 10, 11, 12)
    PseudoRET implicit $lr, implicit %0
...

---
name: shuffle_concat_extracted_subvectors_height_not_power2_no_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_height_not_power2_no_combine
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<8 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<8 x s32>), [[COPY1]], shufflemask(1, 2, 3, 4, 1, 2, 3, 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<8 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(1, 2, 3, 4, 1, 2, 3, 4)
    PseudoRET implicit $lr, implicit %0
...

---
name: shuffle_concat_extracted_subvectors_height_in_submask_not_power2_no_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $wl0, $wl1
    ; CHECK-LABEL: name: shuffle_concat_extracted_subvectors_height_in_submask_not_power2_no_combine
    ; CHECK: liveins: $wl0, $wl1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wl1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<8 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<8 x s32>), [[COPY1]], shufflemask(0, 1, 2, 3, 1, 2, 3, 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<8 x s32>)
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl1
    %0:_(<8 x s32>) = G_SHUFFLE_VECTOR %1(<8 x s32>), %2(<8 x s32>), shufflemask(0, 1, 2, 3, 1, 2, 3, 4)
    PseudoRET implicit $lr, implicit %0
...


---
name: vector_shuffle_to_extract_insert_elt_to_broadcast
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vector_shuffle_to_extract_insert_elt_to_broadcast
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[EVEC1]](s32), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0:_(<16 x s32>), %1:_, shufflemask(16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    PseudoRET implicit $lr, implicit %2
...


---
name: vector_shuffle_to_extract_insert_elt_to_broadcast_min_frequency_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vector_shuffle_to_extract_insert_elt_to_broadcast_min_frequency_combine
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY]](<16 x s32>), [[C]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[EVEC]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[EVEC1:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[EVEC1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[EVEC2:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[IVEC1:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC]], [[EVEC2]](s32), [[C1]](s32)
    ; CHECK-NEXT: [[EVEC3:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[IVEC2:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC1]], [[EVEC3]](s32), [[C2]](s32)
    ; CHECK-NEXT: [[EVEC4:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[IVEC3:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC2]], [[EVEC4]](s32), [[C3]](s32)
    ; CHECK-NEXT: [[EVEC5:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC4:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC3]], [[EVEC5]](s32), [[C4]](s32)
    ; CHECK-NEXT: [[EVEC6:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[IVEC5:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC4]], [[EVEC6]](s32), [[C5]](s32)
    ; CHECK-NEXT: [[EVEC7:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[IVEC6:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC5]], [[EVEC7]](s32), [[C6]](s32)
    ; CHECK-NEXT: [[EVEC8:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[COPY1]](<16 x s32>), [[C1]](s32)
    ; CHECK-NEXT: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[IVEC7:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[IVEC6]], [[EVEC8]](s32), [[C7]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC7]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0:_(<16 x s32>), %1:_, shufflemask(17, 17, 17, 17, 17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0)
    PseudoRET implicit $lr, implicit %2
...

---
name: vector_shuffle_to_extract_insert_elt_to_broadcast_min_frequency_no_combine
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vector_shuffle_to_extract_insert_elt_to_broadcast_min_frequency_no_combine
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[SHUF:%[0-9]+]]:_(<16 x s32>) = G_SHUFFLE_VECTOR [[COPY]](<16 x s32>), [[COPY1]], shufflemask(17, 17, 17, 17, 17, 17, 17, 2, 3, 0, 0, 0, 0, 0, 0, 0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[SHUF]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0:_(<16 x s32>), %1:_, shufflemask(17, 17, 17, 17, 17, 17, 17, 2, 3, 0, 0, 0, 0, 0, 0, 0)
    PseudoRET implicit $lr, implicit %2
...
