# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=aie-prelegalizer-combiner  %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_build_vector_128_8bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_128_8bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s8>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s8>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[TRUNC]](s8), [[C]](s32)
    ; CHECK-NEXT: $eg0 = COPY [[IVEC]](<16 x s8>)
    %0:_(s32) = COPY $r0
    %1:_(s8) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s8) = G_TRUNC %2:_(s32)
    %4:_(<16 x s8>) = G_BUILD_VECTOR %1:_(s8), %1:_(s8), %3:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8)
    $eg0 = COPY %4:_(<16 x s8>)
...

---
name:            test_build_vector_128_16bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_128_16bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<8 x s16>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[TRUNC]](s16), [[C]](s32)
    ; CHECK-NEXT: $eg0 = COPY [[IVEC]](<8 x s16>)
    %0:_(s32) = COPY $r0
    %1:_(s16) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s16) = G_TRUNC %2:_(s32)
    %4:_(<8 x s16>) = G_BUILD_VECTOR %3:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16)
    $eg0 = COPY %4:_(<8 x s16>)
...

---
name:            test_build_vector_128_32bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_128_32bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<4 x s32>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: $eg0 = COPY [[IVEC]](<4 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<4 x s32>) = G_BUILD_VECTOR %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32)
    $eg0 = COPY %3:_(<4 x s32>)
...

---
name:            test_build_vector_256_8bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_256_8bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<32 x s8>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<32 x s8>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[TRUNC]](s8), [[C]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[IVEC]](<32 x s8>)
    %0:_(s32) = COPY $r0
    %1:_(s8) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s8) = G_TRUNC %2:_(s32)
    %4:_(<32 x s8>) = G_BUILD_VECTOR %1:_(s8), %1:_(s8), %1:_(s8), %3:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8)
    $wl0 = COPY %4:_(<32 x s8>)
...

---
name:            test_build_vector_256_16bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_256_16bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<16 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s16>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[TRUNC]](s16), [[C]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[IVEC]](<16 x s16>)
    %0:_(s32) = COPY $r0
    %1:_(s16) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s16) = G_TRUNC %2:_(s32)
    %4:_(<16 x s16>) = G_BUILD_VECTOR %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %3:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16)
    $wl0 = COPY %4:_(<16 x s16>)
...

---
name:            test_build_vector_256_32bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_256_32bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<8 x s32>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[COPY]](s32), [[C]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[IVEC]](<8 x s32>)
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r0
    %2:_(<8 x s32>) = G_BUILD_VECTOR %0:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    $wl0 = COPY %2:_(<8 x s32>)
...

---
name:            test_build_vector_256_64bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_256_64bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $l1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[COPY1]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: [[AIE_UNPAD_VECTOR:%[0-9]+]]:_(<4 x s64>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<4 x s64>) = G_INSERT_VECTOR_ELT [[AIE_UNPAD_VECTOR]], [[COPY]](s64), [[C]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[IVEC]](<4 x s64>)
    %0:_(s64) = COPY $l1
    %1:_(s64) = COPY $l0
    %2:_(<4 x s64>) = G_BUILD_VECTOR %1:_(s64), %1:_(s64), %1:_(s64), %0:_(s64)
    $wl0 = COPY %2:_(<4 x s64>)
...

---
name:            test_build_vector_512_8bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_512_8bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<64 x s8>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[TRUNC]](s8), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[IVEC]](<64 x s8>)
    %0:_(s32) = COPY $r0
    %1:_(s8) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s8) = G_TRUNC %2:_(s32)
    %4:_(<64 x s8>) = G_BUILD_VECTOR %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %3:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8)
    $x0 = COPY %4:_(<64 x s8>)
...

---
name:            test_build_vector_512_16bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_512_16bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<32 x s16>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[TRUNC]](s16), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[IVEC]](<32 x s16>)
    %0:_(s32) = COPY $r0
    %1:_(s16) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s16) = G_TRUNC %2:_(s32)
    %4:_(<32 x s16>) = G_BUILD_VECTOR %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %3:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16)
    $x0 = COPY %4:_(<32 x s16>)
...

---
name:            test_build_vector_512_32bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_512_32bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY1]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s32>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[COPY]](s32), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[IVEC]](<16 x s32>)
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r0
    %2:_(<16 x s32>) = G_BUILD_VECTOR %0:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    $x0 = COPY %2:_(<16 x s32>)
...

---
name:            test_build_vector_512_64bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_512_64bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $l1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[COPY1]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<8 x s64>) = G_INSERT_VECTOR_ELT [[AIE_BROADCAST_VECTOR]], [[COPY]](s64), [[C]](s32)
    ; CHECK-NEXT: $x0 = COPY [[IVEC]](<8 x s64>)
    %0:_(s64) = COPY $l1
    %1:_(s64) = COPY $l0
    %2:_(<8 x s64>) = G_BUILD_VECTOR %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %0:_(s64), %1:_(s64), %1:_(s64), %1:_(s64)
    $x0 = COPY %2:_(<8 x s64>)
...

---
name:            test_build_vector_1024_8bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_1024_8bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<128 x s8>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<64 x s8>), [[AIE_BROADCAST_VECTOR]](<64 x s8>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<128 x s8>) = G_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[TRUNC]](s8), [[C]](s32)
    ; CHECK-NEXT: $y2 = COPY [[IVEC]](<128 x s8>)
    %0:_(s32) = COPY $r0
    %1:_(s8) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s8) = G_TRUNC %2:_(s32)
    %4:_(<128 x s8>) = G_BUILD_VECTOR %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %3:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8), %1:_(s8)
    $y2 = COPY %4:_(<128 x s8>)
...

---
name:            test_build_vector_1024_16bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_1024_16bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[COPY]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s16>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<32 x s16>), [[AIE_BROADCAST_VECTOR]](<32 x s16>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<64 x s16>) = G_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[TRUNC]](s16), [[C]](s32)
    ; CHECK-NEXT: $y2 = COPY [[IVEC]](<64 x s16>)
    %0:_(s32) = COPY $r0
    %1:_(s16) = G_TRUNC %0:_(s32)
    %2:_(s32) = COPY $r1
    %3:_(s16) = G_TRUNC %2:_(s32)
    %4:_(<64 x s16>) = G_BUILD_VECTOR %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %1:_(s16), %3:_(s16)
    $y2 = COPY %4:_(<64 x s16>)
...

---
name:            test_build_vector_1024_32bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_1024_32bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY1]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<32 x s32>) = G_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY]](s32), [[C]](s32)
    ; CHECK-NEXT: $y2 = COPY [[IVEC]](<32 x s32>)
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r0
    %2:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %0:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    $y2 = COPY %2:_(<32 x s32>)
...

---
name:            test_build_vector_1024_64bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_1024_64bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $l1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $l0
    ; CHECK-NEXT: [[BITCAST:%[0-9]+]]:_(<2 x s32>) = G_BITCAST [[COPY1]](s64)
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<8 x s64>) = G_AIE_BROADCAST_VECTOR [[BITCAST]](<2 x s32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s64>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<8 x s64>), [[AIE_BROADCAST_VECTOR]](<8 x s64>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<16 x s64>) = G_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY]](s64), [[C]](s32)
    ; CHECK-NEXT: $y2 = COPY [[IVEC]](<16 x s64>)
    %0:_(s64) = COPY $l1
    %1:_(s64) = COPY $l0
    %2:_(<16 x s64>) = G_BUILD_VECTOR %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %0:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64), %1:_(s64)
    $y2 = COPY %2:_(<16 x s64>)
...

# Invalid Vector for broadcast.
# As two of the elements in G_BUILD_VECTOR is different from others, ideally this should not converted into G_AIE_BROADCAST_VECTOR and G_INSERT_VECTOR_ELT
---
name:            test_build_vector_1024_32bit_scl_invalid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_1024_32bit_scl_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<32 x s32>) = G_BUILD_VECTOR [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32)
    ; CHECK-NEXT: $y2 = COPY [[BUILD_VECTOR]](<32 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<32 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    $y2 = COPY %3:_(<32 x s32>)
...
---
name:            test_build_vector_2048_32bit_scl
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_2048_32bit_scl
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[AIE_BROADCAST_VECTOR:%[0-9]+]]:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[COPY1]](s32)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<64 x s32>) = G_CONCAT_VECTORS [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>), [[AIE_BROADCAST_VECTOR]](<16 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 49
    ; CHECK-NEXT: [[IVEC:%[0-9]+]]:_(<64 x s32>) = G_INSERT_VECTOR_ELT [[CONCAT_VECTORS]], [[COPY]](s32), [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[IVEC]](<64 x s32>)
    %0:_(s32) = COPY $r1
    %1:_(s32) = COPY $r0
    %2:_(<64 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %0:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32)
    PseudoRET implicit $lr, implicit %2
...

# Invalid Vector for broadcast.
# As two of the elements in G_BUILD_VECTOR is different from others, ideally this should not converted into G_AIE_BROADCAST_VECTOR and G_INSERT_VECTOR_ELT
---
name:            test_build_vector_2048_32bit_scl_invalid
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_build_vector_2048_32bit_scl_invalid
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<64 x s32>) = G_BUILD_VECTOR [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY]](s32), [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[BUILD_VECTOR]](<64 x s32>)
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %3:_(<64 x s32>) = G_BUILD_VECTOR %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %1:_(s32), %2:_(s32)
    PseudoRET implicit $lr, implicit %3
...
