# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

---
name: smax_s32
legalized: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: smax_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[SMAX:%[0-9]+]]:gprregbank(s32) = G_SMAX [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[SMAX]](s32)
    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(s32) = G_SMAX %0, %1
    $r0 = COPY %2
...

---
name: smin_s32
legalized: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: smin_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[SMIN:%[0-9]+]]:gprregbank(s32) = G_SMIN [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[SMIN]](s32)
    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(s32) = G_SMIN %0, %1
    $r0 = COPY %2
...

---
name: umax_s32
legalized: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: umax_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[UMAX:%[0-9]+]]:gprregbank(s32) = G_UMAX [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[UMAX]](s32)
    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(s32) = G_UMAX %0, %1
    $r0 = COPY %2
...

---
name: umin_s32
legalized: true
body: |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: umin_s32
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[UMIN:%[0-9]+]]:gprregbank(s32) = G_UMIN [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[UMIN]](s32)
    %0:_(s32) = COPY $r0
    %1:_(s32) = COPY $r1
    %2:_(s32) = G_UMIN %0, %1
    $r0 = COPY %2
...
