# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
---
name:            test_v16x32
legalized:       true
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_v16x32
    ; CHECK: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; CHECK-NEXT: $lfl0 = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %0:_(<16 x s32>) = COPY $lfl1
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v32x32
legalized:       true
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_v32x32
    ; CHECK: [[COPY:%[0-9]+]]:fiforegbank(<32 x s32>) = COPY $lf1
    ; CHECK-NEXT: $lf0 = COPY [[COPY]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lf0
    %0:_(<32 x s32>) = COPY $lf1
    $lf0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $lf0

...


---
name:            test_v32x32_store
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_v32x32_store
    ; CHECK: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: G_STORE [[COPY1]](<16 x s32>), [[FRAME_INDEX]](p0) :: (volatile store (<16 x s32>))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: $lfl0 = COPY [[LOAD]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    G_STORE %1(<16 x s32>), %2(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %2(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v32x32_load
legalized:       true
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_v32x32_load
    ; CHECK: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<32 x s32>) = G_LOAD [[COPY]](p0) :: (load (<32 x s32>))
    ; CHECK-NEXT: $lf0 = COPY [[LOAD]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lf0
    %1:_(p0) = COPY $p0
    %0:_(<32 x s32>) = G_LOAD %1(p0) :: (load (<32 x s32>))
    $lf0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $lf0

...
---
name:            test_v16x32_spill_reload
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_v16x32_spill_reload
    ; CHECK: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: G_STORE [[COPY1]](<16 x s32>), [[FRAME_INDEX]](p0) :: (store (<16 x s32>))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: $lfl0 = COPY [[LOAD1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    G_STORE %1(<16 x s32>), %2(p0) :: (store (<16 x s32>))
    %4:_(<16 x s32>) = G_LOAD %2(p0) :: (dereferenceable load (<16 x s32>))
    G_STORE %4(<16 x s32>), %3(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v16x64_spill_reload
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_v16x64_spill_reload
    ; CHECK: [[COPY:%[0-9]+]]:fiforegbank(<16 x s64>) = COPY $lf1
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s64>) = COPY [[COPY]](<16 x s64>)
    ; CHECK-NEXT: G_STORE [[COPY1]](<16 x s64>), [[FRAME_INDEX]](p0) :: (store (<16 x s64>))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (<16 x s64>))
    ; CHECK-NEXT: G_STORE [[LOAD]](<16 x s64>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s64>))
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:vregbank(<16 x s64>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s64>))
    ; CHECK-NEXT: $lf0 = COPY [[LOAD1]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lf0
    %1:_(<16 x s64>) = COPY $lf1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    G_STORE %1(<16 x s64>), %2(p0) :: (store (<16 x s64>))
    %4:_(<16 x s64>) = G_LOAD %2(p0) :: (dereferenceable load (<16 x s64>))
    G_STORE %4(<16 x s64>), %3(p0) :: (volatile store (<16 x s64>))
    %0:_(<16 x s64>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s64>))
    $lf0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $lf0

...

---
name:            offset_load_fifo512
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: offset_load_fifo512
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:vregbank(<8 x s64>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (<8 x s64>))
    ; CHECK-NEXT: $lfl0 = COPY [[AIE_OFFSET_LOAD]](<8 x s64>)
    %1:_(p0) = COPY $p0
    %2:_(s20) = G_CONSTANT i20 448
    %0:_(<8 x s64>) = G_AIE_OFFSET_LOAD %1:_(p0), %2:_(s20) :: (load (<8 x s64>))
    $lfl0 = COPY %0:_(<8 x s64>)

...
---
name:            offset_store_fifo512
legalized:       true
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: offset_store_fifo512
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[COPY2]](<16 x s32>), [[COPY1]](p0), [[C]](s20) :: (store (<16 x s32>))
    %0:_(<16 x s32>) = COPY $lfl0
    %1:_(p0) = COPY $p0
    %2:_(s20) = G_CONSTANT i20 448
    G_AIE_OFFSET_STORE %0:_(<16 x s32>), %1:_(p0), %2:_(s20) :: (store (<16 x s32>))
...

---
name: post-inc-fifo512-load
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1

    ; CHECK-LABEL: name: post-inc-fifo512-load
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; CHECK-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; CHECK-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; CHECK-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; CHECK-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:vregbank(<16 x s32>), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: [[AIE_POSTINC_LOAD2:%[0-9]+]]:vregbank(<16 x s32>), [[AIE_POSTINC_LOAD3:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[AIE_POSTINC_LOAD1]], [[C]](s20) :: (load (<16 x s32>) from stack - 64)
    ; CHECK-NEXT: $lfl0 = COPY [[AIE_POSTINC_LOAD]](<16 x s32>)
    ; CHECK-NEXT: $lfl1 = COPY [[AIE_POSTINC_LOAD2]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %7:_(s20) = G_TRUNC %1
    %8:_(s20) = G_CONSTANT i20 448
    %9:_(s20) = G_CONSTANT i20 -512
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_CONSTANT i20 32
    %12:_(s20) = G_CONSTANT i20 512
    %13:_(<16 x s32>), %15:_(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s32>) from stack - 64)
    %14:_(<16 x s32>), %16:_(p0) = G_AIE_POSTINC_LOAD %15, %8 :: (load (<16 x s32>) from stack - 64)
    $lfl0 = COPY %13:_(<16 x s32>)
    $lfl1 = COPY %14:_(<16 x s32>)
...

---
name: post-inc-2d-fifo-load-bm
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: post-inc-2d-fifo-load-bm
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[AIE_POSTINC_2D_LOAD:%[0-9]+]]:vregbank(<16 x s32>), [[AIE_POSTINC_2D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_LOAD2:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (load (<16 x s32>))
    ; CHECK-NEXT: $lfl0 = COPY [[AIE_POSTINC_2D_LOAD]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(<16 x s32>), %6:_(p0), %7:_(s20) = G_AIE_POSTINC_2D_LOAD %0, %1, %2, %3, %4 :: (load (<16 x s32>))
    $lfl0 = COPY %5:_(<16 x s32>)
...

---
name: post-inc-3d-fifo-load-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0

    ; CHECK-LABEL: name: post-inc-3d-fifo-load-512
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:vregbank(<16 x s32>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (load (<16 x s32>))
    ; CHECK-NEXT: $lfl0 = COPY [[AIE_POSTINC_3D_LOAD]](<16 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(s20) = G_CONSTANT i20 5
    %6:_(s20) = G_CONSTANT i20 6
    %7:_(s20) = G_CONSTANT i20 7
    %8:_(<16 x s32>), %9:_(p0), %10:_(s20), %11:_(s20) = G_AIE_POSTINC_3D_LOAD %0, %1, %2, %3, %4, %6, %5, %7 :: (load (<16 x s32>))
    $lfl0 = COPY %8:_(<16 x s32>)

...
---
name:            test_fifo_postinc_store
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_fifo_postinc_store
    ; CHECK: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY2]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: $lfl0 = COPY [[LOAD]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = COPY $p1
    %3:_(s20) = G_CONSTANT i20 128
    %5:_(p0) = G_AIE_POSTINC_STORE %1(<16 x s32>), %2, %3(s20) :: (store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %5(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...
---
name:            test_v16acc32_spill_reload_postinc
legalized:       true
stack:
  - { id: 0, name: "", type: default, offset: 0, size: 64, alignment: 64}
  - { id: 1, name: "", type: default, offset: 0, size: 64, alignment: 64}
body:             |
  bb.1.entry:

    ; CHECK-LABEL: name: test_v16acc32_spill_reload_postinc
    ; CHECK: [[COPY:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl1
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.0
    ; CHECK-NEXT: [[FRAME_INDEX1:%[0-9]+]]:ptrregbank(p0) = G_FRAME_INDEX %stack.1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY2]](<16 x s32>), [[COPY1]], [[C]](s20) :: (store (<16 x s32>))
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[AIE_POSTINC_STORE]](p0) :: (dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: G_STORE [[LOAD]](<16 x s32>), [[FRAME_INDEX1]](p0) :: (volatile store (<16 x s32>))
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:vregbank(<16 x s32>) = G_LOAD [[FRAME_INDEX1]](p0) :: (volatile dereferenceable load (<16 x s32>))
    ; CHECK-NEXT: $lfl0 = COPY [[LOAD1]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $lfl0
    %1:_(<16 x s32>) = COPY $lfl1
    %2:_(p0) = G_FRAME_INDEX %stack.0
    %3:_(p0) = G_FRAME_INDEX %stack.1
    %5:_(p0) = COPY $p1
    %6:_(s20) = G_CONSTANT i20 128
    %7:_(p0) = G_AIE_POSTINC_STORE %1(<16 x s32>), %5, %6(s20) :: (store (<16 x s32>))
    %4:_(<16 x s32>) = G_LOAD %7(p0) :: (dereferenceable load (<16 x s32>))
    G_STORE %4(<16 x s32>), %3(p0) :: (volatile store (<16 x s32>))
    %0:_(<16 x s32>) = G_LOAD %3(p0) :: (volatile dereferenceable load (<16 x s32>))
    $lfl0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $lfl0

...

---
name: post-inc-acc-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $r0, $r1, $lfl0

    ; CHECK-LABEL: name: post-inc-acc-store-512
    ; CHECK: liveins: $p0, $r0, $r1, $lfl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 448
    ; CHECK-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 -512
    ; CHECK-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 0
    ; CHECK-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 512
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_POSTINC_STORE:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_STORE [[COPY3]](<16 x s32>), [[COPY]], [[TRUNC]](s20) :: (store (<16 x s32>) into stack - 64)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %7:_(s20) = G_TRUNC %1
    %8:_(s20) = G_CONSTANT i20 448
    %9:_(s20) = G_CONSTANT i20 -512
    %10:_(s20) = G_CONSTANT i20 0
    %11:_(s20) = G_CONSTANT i20 32
    %12:_(s20) = G_CONSTANT i20 512
    %13:_(<16 x s32>) = COPY $lfl0
    %19:_(p0) = G_AIE_POSTINC_STORE %13, %0, %7 :: (store (<16 x s32>) into stack - 64)
...

---
name: post-inc-2d-acc-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $lfl0

    ; CHECK-LABEL: name: post-inc-2d-acc-store-512
    ; CHECK: liveins: $p0, $lfl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_POSTINC_2D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_2D_STORE1:%[0-9]+]]:modregbank(s20) = G_AIE_POSTINC_2D_STORE [[COPY2]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]] :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(<16 x s32>) = COPY $lfl0
    %6:_(p0), %7:_(s20) = G_AIE_POSTINC_2D_STORE %5, %0, %1, %2, %3, %4 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name: post-inc-3d-vector-store-512
legalized:       true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $lfl0

    ; CHECK-LABEL: name: post-inc-3d-vector-store-512
    ; CHECK: liveins: $p0, $lfl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 2
    ; CHECK-NEXT: [[C2:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 3
    ; CHECK-NEXT: [[C3:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 4
    ; CHECK-NEXT: [[C4:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 5
    ; CHECK-NEXT: [[C5:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 6
    ; CHECK-NEXT: [[C6:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 7
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fiforegbank(<16 x s32>) = COPY $lfl0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:modregbank(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:modregbank = G_AIE_POSTINC_3D_STORE [[COPY2]](<16 x s32>), [[COPY]], [[C]], [[C1]], [[C2]], [[C3]], [[C5]], [[C4]], [[C6]] :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 1
    %2:_(s20) = G_CONSTANT i20 2
    %3:_(s20) = G_CONSTANT i20 3
    %4:_(s20) = G_CONSTANT i20 4
    %5:_(s20) = G_CONSTANT i20 5
    %6:_(s20) = G_CONSTANT i20 6
    %7:_(s20) = G_CONSTANT i20 7
    %8:_(<16 x s32>) = COPY $lfl0
    %9:_(p0), %10:_(s20), %11:_(s20) = G_AIE_POSTINC_3D_STORE %8, %0, %1, %2, %3, %4, %6, %5, %7 :: (store (<16 x s32>))
    PseudoRET implicit $lr
...

---
name:            test_fifo_ld_fill
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_ld_fill
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %3:_(p0) = G_IMPLICIT_DEF
    %4:_(<32 x s32>) = G_IMPLICIT_DEF
    %5:_(s32) = G_IMPLICIT_DEF
    %6:_(p0), %7:_(<32 x s32>), %8:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fill), %3:_(p0), %4:_(<32 x s32>), %5:_(s32)
    PseudoRET implicit $lr

...

---
name:            test_fifo_ld_fillx
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_ld_fillx
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fillx), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](<16 x s32>), [[DEF4]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %4:_(p0) = G_IMPLICIT_DEF
    %5:_(<32 x s32>) = G_IMPLICIT_DEF
    %6:_(s32) = G_IMPLICIT_DEF
    %10:_(<16 x s32>) = G_IMPLICIT_DEF
    %11:_(s32) = G_IMPLICIT_DEF
    %7:_(p0), %8:_(<32 x s32>), %9:_(s32), %12:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.fillx), %4:_(p0), %5:_(<32 x s32>), %6:_(s32), %10:_(<16 x s32>), %11:_(s32)
    PseudoRET implicit $lr

...

---
name:            test_fifo_ld_popx
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_ld_popx
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:fiforegbank(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:fiforegbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.popx), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](<16 x s32>), [[DEF4]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %5:_(p0) = G_IMPLICIT_DEF
    %6:_(<32 x s32>) = G_IMPLICIT_DEF
    %7:_(s32) = G_IMPLICIT_DEF
    %12:_(<16 x s32>) = G_IMPLICIT_DEF
    %13:_(s32) = G_IMPLICIT_DEF
    %8:_(<64 x s8>), %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %14:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.popx), %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %12:_(<16 x s32>), %13:_(s32)
    PseudoRET implicit $lr
...

---
name:            pop_unaligned
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_unaligned
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.512.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %5:_(p0) = G_IMPLICIT_DEF
    %6:_(<32 x s32>) = G_IMPLICIT_DEF
    %7:_(s32) = G_IMPLICIT_DEF
    %8:_(<64 x s8>), %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.512.unaligned), %5:_(p0), %6:_(<32 x s32>), %7:_(s32)
    PseudoRET implicit $lr
...

---
name:            pop_unaligned_1d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_unaligned_1d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %9:_(s20) = G_IMPLICIT_DEF
    %10:_(<64 x s8>), %11:_(p0), %12:_(<32 x s32>), %13:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.unaligned), %6:_(p0), %7:_(<32 x s32>), %8:_(s32), %9:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_unaligned_2d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_unaligned_2d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %9:_(p0) = G_IMPLICIT_DEF
    %10:_(<32 x s32>) = G_IMPLICIT_DEF
    %11:_(s32) = G_IMPLICIT_DEF
    %12:_(s20) = G_IMPLICIT_DEF
    %13:_(s20) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(<64 x s8>), %18:_(p0), %19:_(<32 x s32>), %20:_(s32), %21:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.unaligned), %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %12:_(s20), %13:_(s20), %15:_(s20), %16:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_unaligned_3d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_unaligned_3d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<64 x s8>), [[INT1:%[0-9]+]]:ptrregbank(p0), [[INT2:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT3:%[0-9]+]]:gprregbank(s32), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.unaligned), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %12:_(p0) = G_IMPLICIT_DEF
    %13:_(<32 x s32>) = G_IMPLICIT_DEF
    %14:_(s32) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %18:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %20:_(s20) = G_IMPLICIT_DEF
    %22:_(s20) = G_IMPLICIT_DEF
    %23:_(s20) = G_IMPLICIT_DEF
    %24:_(<64 x s8>), %25:_(p0), %26:_(<32 x s32>), %27:_(s32), %28:_(s20), %29:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.unaligned), %12:_(p0), %13:_(<32 x s32>), %14:_(s32), %15:_(s20), %16:_(s20), %18:_(s20), %19:_(s20), %20:_(s20), %22:_(s20), %23:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_BFP640
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP640
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<16 x s32>), [[INT4:%[0-9]+]]:gprregbank(<2 x s32>), [[INT5:%[0-9]+]]:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP640), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %12:_(<16 x s32>), %13:_(<2 x s32>), %14:_(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP640), %6:_(p0), %7:_(<32 x s32>), %8:_(s32)
    PseudoRET implicit $lr
...

---
name:            pop_BFP640_1d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP640_1d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<16 x s32>), [[INT4:%[0-9]+]]:gprregbank(<2 x s32>), [[INT5:%[0-9]+]]:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP640), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %7:_(p0) = G_IMPLICIT_DEF
    %8:_(<32 x s32>) = G_IMPLICIT_DEF
    %9:_(s32) = G_IMPLICIT_DEF
    %10:_(s20) = G_IMPLICIT_DEF
    %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(<16 x s32>), %15:_(<2 x s32>), %16:_(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP640), %7:_(p0), %8:_(<32 x s32>), %9:_(s32), %10:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_BFP640_2d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP640_2d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:vregbank(<16 x s32>), [[INT5:%[0-9]+]]:gprregbank(<2 x s32>), [[INT6:%[0-9]+]]:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP640), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %10:_(p0) = G_IMPLICIT_DEF
    %11:_(<32 x s32>) = G_IMPLICIT_DEF
    %12:_(s32) = G_IMPLICIT_DEF
    %13:_(s20) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %18:_(p0), %19:_(<32 x s32>), %20:_(s32), %21:_(s20), %22:_(<16 x s32>), %23:_(<2 x s32>), %24:_(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP640), %10:_(p0), %11:_(<32 x s32>), %12:_(s32), %13:_(s20), %14:_(s20), %16:_(s20), %17:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_BFP640_3d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP640_3d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:vregbank(<16 x s32>), [[INT6:%[0-9]+]]:gprregbank(<2 x s32>), [[INT7:%[0-9]+]]:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP640), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %13:_(p0) = G_IMPLICIT_DEF
    %14:_(<32 x s32>) = G_IMPLICIT_DEF
    %15:_(s32) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %20:_(s20) = G_IMPLICIT_DEF
    %21:_(s20) = G_IMPLICIT_DEF
    %23:_(s20) = G_IMPLICIT_DEF
    %24:_(s20) = G_IMPLICIT_DEF
    %25:_(p0), %26:_(<32 x s32>), %27:_(s32), %28:_(s20), %29:_(s20), %30:_(<16 x s32>), %31:_(<2 x s32>), %32:_(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP640), %13:_(p0), %14:_(<32 x s32>), %15:_(s32), %16:_(s20), %17:_(s20), %19:_(s20), %20:_(s20), %21:_(s20), %23:_(s20), %24:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_BFP768
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP768
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<8 x s32>), [[INT4:%[0-9]+]]:vregbank(<8 x s32>), [[INT5:%[0-9]+]]:gprregbank(<2 x s32>), [[INT6:%[0-9]+]]:gprregbank(<2 x s32>), [[INT7:%[0-9]+]]:gprregbank(s32), [[INT8:%[0-9]+]]:gprregbank(s32), [[INT9:%[0-9]+]]:gprregbank(s32), [[INT10:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP768), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32), %12:_(<8 x s32>), %13:_(<8 x s32>), %14:_(<2 x s32>), %15:_(<2 x s32>), %16:_(s32), %17:_(s32), %18:_(s32), %19:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.BFP768), %6:_(p0), %7:_(<32 x s32>), %8:_(s32)
    PseudoRET implicit $lr
...

---
name:            pop_BFP768_1d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP768_1d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:vregbank(<8 x s32>), [[INT4:%[0-9]+]]:vregbank(<8 x s32>), [[INT5:%[0-9]+]]:gprregbank(<2 x s32>), [[INT6:%[0-9]+]]:gprregbank(<2 x s32>), [[INT7:%[0-9]+]]:gprregbank(s32), [[INT8:%[0-9]+]]:gprregbank(s32), [[INT9:%[0-9]+]]:gprregbank(s32), [[INT10:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP768), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %7:_(p0) = G_IMPLICIT_DEF
    %8:_(<32 x s32>) = G_IMPLICIT_DEF
    %9:_(s32) = G_IMPLICIT_DEF
    %10:_(s20) = G_IMPLICIT_DEF
    %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(<8 x s32>), %15:_(<8 x s32>), %16:_(<2 x s32>), %17:_(<2 x s32>), %18:_(s32), %19:_(s32), %20:_(s32), %21:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.1d.BFP768), %7:_(p0), %8:_(<32 x s32>), %9:_(s32), %10:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_BFP768_2d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP768_2d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:vregbank(<8 x s32>), [[INT5:%[0-9]+]]:vregbank(<8 x s32>), [[INT6:%[0-9]+]]:gprregbank(<2 x s32>), [[INT7:%[0-9]+]]:gprregbank(<2 x s32>), [[INT8:%[0-9]+]]:gprregbank(s32), [[INT9:%[0-9]+]]:gprregbank(s32), [[INT10:%[0-9]+]]:gprregbank(s32), [[INT11:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP768), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %10:_(p0) = G_IMPLICIT_DEF
    %11:_(<32 x s32>) = G_IMPLICIT_DEF
    %12:_(s32) = G_IMPLICIT_DEF
    %13:_(s20) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %18:_(p0), %19:_(<32 x s32>), %20:_(s32), %21:_(s20), %22:_(<8 x s32>), %23:_(<8 x s32>), %24:_(<2 x s32>), %25:_(<2 x s32>), %26:_(s32), %27:_(s32), %28:_(s32), %29:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.2d.BFP768), %10:_(p0), %11:_(<32 x s32>), %12:_(s32), %13:_(s20), %14:_(s20), %16:_(s20), %17:_(s20)
    PseudoRET implicit $lr
...

---
name:            pop_BFP768_3d
tracksRegLiveness: true
legalized: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: pop_BFP768_3d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20), [[INT5:%[0-9]+]]:vregbank(<8 x s32>), [[INT6:%[0-9]+]]:vregbank(<8 x s32>), [[INT7:%[0-9]+]]:gprregbank(<2 x s32>), [[INT8:%[0-9]+]]:gprregbank(<2 x s32>), [[INT9:%[0-9]+]]:gprregbank(s32), [[INT10:%[0-9]+]]:gprregbank(s32), [[INT11:%[0-9]+]]:gprregbank(s32), [[INT12:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP768), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %13:_(p0) = G_IMPLICIT_DEF
    %14:_(<32 x s32>) = G_IMPLICIT_DEF
    %15:_(s32) = G_IMPLICIT_DEF
    %16:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %20:_(s20) = G_IMPLICIT_DEF
    %21:_(s20) = G_IMPLICIT_DEF
    %23:_(s20) = G_IMPLICIT_DEF
    %24:_(s20) = G_IMPLICIT_DEF
    %25:_(p0), %26:_(<32 x s32>), %27:_(s32), %28:_(s20), %29:_(s20), %30:_(<8 x s32>), %31:_(<8 x s32>), %32:_(<2 x s32>), %33:_(<2 x s32>), %34:_(s32), %35:_(s32), %36:_(s32), %37:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.ld.pop.3d.BFP768), %13:_(p0), %14:_(<32 x s32>), %15:_(s32), %16:_(s20), %17:_(s20), %19:_(s20), %20:_(s20), %21:_(s20), %23:_(s20), %24:_(s20)
    PseudoRET implicit $lr
...

---
name:            test_fifo_st_flush
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %4:_(p0) = G_IMPLICIT_DEF
    %5:_(<32 x s32>) = G_IMPLICIT_DEF
    %6:_(s32) = G_IMPLICIT_DEF
    %7:_(p0), %8:_(<32 x s32>), %9:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush), %4:_(p0), %5:_(<32 x s32>), %6:_(s32)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_flush_conv
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush_conv
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.conv), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %4:_(p0) = G_IMPLICIT_DEF
    %5:_(<32 x s32>) = G_IMPLICIT_DEF
    %6:_(s32) = G_IMPLICIT_DEF
    %7:_(p0), %8:_(<32 x s32>), %9:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.conv), %4:_(p0), %5:_(<32 x s32>), %6:_(s32)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_flush_1d
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush_1d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %5:_(p0) = G_IMPLICIT_DEF
    %6:_(<32 x s32>) = G_IMPLICIT_DEF
    %7:_(s32) = G_IMPLICIT_DEF
    %8:_(s20) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d), %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %8:_(s20)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_flush_1d_conv
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush_1d_conv
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d.conv), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %5:_(p0) = G_IMPLICIT_DEF
    %6:_(<32 x s32>) = G_IMPLICIT_DEF
    %7:_(s32) = G_IMPLICIT_DEF
    %8:_(s20) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.1d.conv), %5:_(p0), %6:_(<32 x s32>), %7:_(s32), %8:_(s20)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_flush_2d
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush_2d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %8:_(p0) = G_IMPLICIT_DEF
    %9:_(<32 x s32>) = G_IMPLICIT_DEF
    %10:_(s32) = G_IMPLICIT_DEF
    %11:_(s20) = G_IMPLICIT_DEF
    %12:_(s20) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %16:_(p0), %17:_(<32 x s32>), %18:_(s32), %19:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d), %8:_(p0), %9:_(<32 x s32>), %10:_(s32), %11:_(s20), %12:_(s20), %14:_(s20), %15:_(s20)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_flush_2d_conv
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush_2d_conv
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d.conv), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %8:_(p0) = G_IMPLICIT_DEF
    %9:_(<32 x s32>) = G_IMPLICIT_DEF
    %10:_(s32) = G_IMPLICIT_DEF
    %11:_(s20) = G_IMPLICIT_DEF
    %12:_(s20) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %16:_(p0), %17:_(<32 x s32>), %18:_(s32), %19:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.2d.conv), %8:_(p0), %9:_(<32 x s32>), %10:_(s32), %11:_(s20), %12:_(s20), %14:_(s20), %15:_(s20)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_flush_3d
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush_3d
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %11:_(p0) = G_IMPLICIT_DEF
    %12:_(<32 x s32>) = G_IMPLICIT_DEF
    %13:_(s32) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %18:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %21:_(s20) = G_IMPLICIT_DEF
    %22:_(s20) = G_IMPLICIT_DEF
    %23:_(p0), %24:_(<32 x s32>), %25:_(s32), %26:_(s20), %27:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d), %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(s20), %15:_(s20), %17:_(s20), %18:_(s20), %19:_(s20), %21:_(s20), %22:_(s20)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_flush_3d_conv
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_flush_3d_conv
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:modregbank(s20) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:modregbank(s20), [[INT4:%[0-9]+]]:modregbank(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d.conv), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](s20), [[DEF4]](s20), [[DEF5]](s20), [[DEF6]](s20), [[DEF7]](s20), [[DEF8]](s20), [[DEF9]](s20)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %11:_(p0) = G_IMPLICIT_DEF
    %12:_(<32 x s32>) = G_IMPLICIT_DEF
    %13:_(s32) = G_IMPLICIT_DEF
    %14:_(s20) = G_IMPLICIT_DEF
    %15:_(s20) = G_IMPLICIT_DEF
    %17:_(s20) = G_IMPLICIT_DEF
    %18:_(s20) = G_IMPLICIT_DEF
    %19:_(s20) = G_IMPLICIT_DEF
    %21:_(s20) = G_IMPLICIT_DEF
    %22:_(s20) = G_IMPLICIT_DEF
    %23:_(p0), %24:_(<32 x s32>), %25:_(s32), %26:_(s20), %27:_(s20) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.flush.3d.conv), %11:_(p0), %12:_(<32 x s32>), %13:_(s32), %14:_(s20), %15:_(s20), %17:_(s20), %18:_(s20), %19:_(s20), %21:_(s20), %22:_(s20)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_push_512
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_push_512
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.512), [[DEF]](p0), [[DEF1]](<16 x s32>), [[DEF2]](<32 x s32>), [[DEF3]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %6:_(p0) = G_IMPLICIT_DEF
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.512), %6:_(p0), %1:_(<16 x s32>), %7:_(<32 x s32>), %8:_(s32)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_push_BFP384
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_push_BFP384
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:vregbank(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP384), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](<8 x s32>), [[DEF4]](<2 x s32>), [[DEF5]](s32), [[DEF6]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<2 x s32>) = G_IMPLICIT_DEF
    %3:_(s32) = G_IMPLICIT_DEF
    %4:_(s32) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP384), %6:_(p0), %7:_(<32 x s32>), %8:_(s32), %1:_(<8 x s32>), %2:_(<2 x s32>), %3:_(s32), %4:_(s32)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_push_BFP640
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_push_BFP640
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP640), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](<16 x s32>), [[DEF4]](<2 x s32>), [[DEF5]](<2 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %1:_(<16 x s32>) = G_IMPLICIT_DEF
    %2:_(<2 x s32>) = G_IMPLICIT_DEF
    %3:_(<2 x s32>) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP640), %6:_(p0), %7:_(<32 x s32>), %8:_(s32), %1:_(<16 x s32>), %2:_(<2 x s32>), %3:_(<2 x s32>)
    PseudoRET implicit $lr

...

---
name:            test_fifo_st_push_BFP768
legalized:       true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_fifo_st_push_BFP768
    ; CHECK: [[DEF:%[0-9]+]]:ptrregbank(p0) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:fiforegbank(<32 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF2:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:vregbank(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:vregbank(<8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF6:%[0-9]+]]:gprregbank(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF7:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF8:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF9:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF10:%[0-9]+]]:gprregbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[INT:%[0-9]+]]:ptrregbank(p0), [[INT1:%[0-9]+]]:fiforegbank(<32 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP768), [[DEF]](p0), [[DEF1]](<32 x s32>), [[DEF2]](s32), [[DEF3]](<8 x s32>), [[DEF4]](<8 x s32>), [[DEF5]](<2 x s32>), [[DEF6]](<2 x s32>), [[DEF7]](s32), [[DEF8]](s32), [[DEF9]](s32), [[DEF10]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %6:_(p0) = G_IMPLICIT_DEF
    %7:_(<32 x s32>) = G_IMPLICIT_DEF
    %8:_(s32) = G_IMPLICIT_DEF
    %1:_(<8 x s32>) = G_IMPLICIT_DEF
    %2:_(<8 x s32>) = G_IMPLICIT_DEF
    %3:_(<2 x s32>) = G_IMPLICIT_DEF
    %4:_(<2 x s32>) = G_IMPLICIT_DEF
    %5:_(s32) = G_IMPLICIT_DEF
    %12:_(s32) = G_IMPLICIT_DEF
    %13:_(s32) = G_IMPLICIT_DEF
    %14:_(s32) = G_IMPLICIT_DEF
    %9:_(p0), %10:_(<32 x s32>), %11:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fifo.st.push.BFP768), %6:_(p0), %7:_(<32 x s32>), %8:_(s32), %1:_(<8 x s32>), %2:_(<8 x s32>), %3:_(<2 x s32>), %4:_(<2 x s32>), %5:_(s32), %12:_(s32), %13:_(s32), %14:_(s32)
    PseudoRET implicit $lr

...
