# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=regbankselect %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_fsub_1024
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $cml0, $cml1
    ; CHECK-LABEL: name: test_fsub_1024
    ; CHECK: liveins: $cml0, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[FSUB:%[0-9]+]]:accregbank(<32 x s32>) = G_FSUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $cml0 = COPY [[FSUB]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<32 x s32>) = COPY $cml0
    %1:_(<32 x s32>) = COPY $cml1
    %2:_(<32 x s32>) = G_FSUB %0, %1
    $cml0 = COPY %2(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name:            test_fsub_2048
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $dm0, $dm1
    ; CHECK-LABEL: name: test_fsub_2048
    ; CHECK: liveins: $dm0, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[FSUB:%[0-9]+]]:accregbank(<64 x s32>) = G_FSUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $dm0 = COPY [[FSUB]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:_(<64 x s32>) = COPY $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(<64 x s32>) = G_FSUB %0, %1
    $dm0 = COPY %2(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...
