# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

# ============================================================================
# Category 1: Operand 0 only (Output Accumulator)
# ============================================================================

# UPS operations
---
name: test_acc32_v16_I256_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $wl0, $r0, $r1
    ; CHECK-LABEL: name: test_acc32_v16_I256_ups
    ; CHECK: liveins: $wl0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), [[COPY]](<16 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...

---
name: test_acc32_v32_I256_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $wl0, $r0, $r1
    ; CHECK-LABEL: name: test_acc32_v32_I256_ups
    ; CHECK: liveins: $wl0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I256.ups), [[COPY]](<16 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_acc32_v32_I512_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_acc32_v32_I512_ups
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I512.ups), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_acc64_v16_I256_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $wl0, $r0, $r1
    ; CHECK-LABEL: name: test_acc64_v16_I256_ups
    ; CHECK: liveins: $wl0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I256.ups), [[COPY]](<16 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_acc64_v16_I512_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_acc64_v16_I512_ups
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I512.ups), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v16.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_acc64_v8_I256_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $wl0, $r0, $r1
    ; CHECK-LABEL: name: test_acc64_v8_I256_ups
    ; CHECK: liveins: $wl0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v8.I256.ups), [[COPY]](<16 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s16>) = COPY $wl0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<8 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v8.I256.ups), %1(<16 x s16>), %2(s32), %3(s32)
    $bmll0 = COPY %0(<8 x s64>)
    PseudoRET implicit $lr, implicit $bmll0
...

---
name: test_acc32_v64_I512_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_acc32_v64_I512_ups
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc32.v64.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_acc64_v32_I512_ups
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_acc64_v32_I512_ups
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v32.I512.ups), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s64>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.acc64.v32.I512.ups), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

# Float16/BFloat16 to AccFloat conversions
---
name: test_v16float16_to_v16accfloat
legalized: true
body: |
  bb.1.entry:
    liveins: $wl0
    ; CHECK-LABEL: name: test_v16float16_to_v16accfloat
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16float16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s16>) = COPY $wl0
    %0:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16float16.to.v16accfloat), %1(<16 x s16>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...

---
name: test_v32float16_to_v32accfloat
legalized: true
body: |
  bb.1.entry:
    liveins: $x0
    ; CHECK-LABEL: name: test_v32float16_to_v32accfloat
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), [[COPY]](<32 x s16>)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32float16.to.v32accfloat), %1(<32 x s16>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_v16bf16_to_v16accfloat
legalized: true
body: |
  bb.1.entry:
    liveins: $wl0
    ; CHECK-LABEL: name: test_v16bf16_to_v16accfloat
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s16>) = COPY $wl0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), [[COPY]](<16 x s16>)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s16>) = COPY $wl0
    %0:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v16bf16.to.v16accfloat), %1(<16 x s16>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...

---
name: test_v32bf16_to_v32accfloat
legalized: true
body: |
  bb.1.entry:
    liveins: $x0
    ; CHECK-LABEL: name: test_v32bf16_to_v32accfloat
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32bf16.to.v32accfloat), [[COPY]](<32 x s16>)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.v32bf16.to.v32accfloat), %1(<32 x s16>)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

# CLR operations
---
name: test_clr_ACC1024l_conf
legalized: true
body: |
  bb.1.entry:
    ; CHECK-LABEL: name: test_clr_ACC1024l_conf
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.clr.ACC1024l.conf)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.clr.ACC1024l.conf)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_clr_ACC2048_conf
legalized: true
body: |
  bb.1.entry:
    ; CHECK-LABEL: name: test_clr_ACC2048_conf
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.clr.ACC2048.conf)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %0:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.clr.ACC2048.conf)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

# Stream read operations
---
name: test_scd_read_acc32
legalized: true
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_scd_read_acc32
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.read.acc32), [[COPY]](s32)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(s32) = COPY $r0
    %0:_(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.read.acc32), %1(s32)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...

---
name: test_scd_expand_lo
legalized: true
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_scd_expand_lo
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.lo), [[COPY]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.lo), %1(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_scd_expand_hi
legalized: true
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_scd_expand_hi
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.hi), [[COPY]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.hi), %1(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_scd_expand_ACC1024
legalized: true
body: |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: test_scd_expand_ACC1024
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC1024), [[COPY]](s32), [[COPY1]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC1024), %1(s32), %2(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_scd_ACC2048
legalized: true
body: |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: test_scd_ACC2048
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.ACC2048), [[COPY]](s32), [[COPY1]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_scd_expand_ACC2048
legalized: true
body: |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: test_scd_expand_ACC2048
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC2048), [[COPY]](s32), [[COPY1]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(s32) = COPY $r0
    %2:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC2048), %1(s32), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_scd_expand_ACC1024_incr
legalized: true
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_scd_expand_ACC1024_incr
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>), [[INT1:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC1024.incr), [[COPY]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(s32) = COPY $r0
    %0:_(<16 x s64>), %2:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC1024.incr), %1(s32)
    $cml0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_scd_expand_ACC2048_incr
legalized: true
body: |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: test_scd_expand_ACC2048_incr
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>), [[INT1:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC2048.incr), [[COPY]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(s32) = COPY $r0
    %0:_(<32 x s64>), %2:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.scd.expand.ACC2048.incr), %1(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

# ============================================================================
# Category 2: Operand 1 only (Input Accumulator)
# ============================================================================

---
name: test_mcd_write_acc32
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0, $r0
    ; CHECK-LABEL: name: test_mcd_write_acc32
    ; CHECK: liveins: $bmll0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.mcd.write.acc32), [[COPY]](<8 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:_(<8 x s64>) = COPY $bmll0
    %2:_(s32) = COPY $r0
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.mcd.write.acc32), %1(<8 x s64>), %2(s32)
    PseudoRET implicit $lr
...

# ============================================================================
# Category 3: Operand 2 only (Input Accumulator)
# ============================================================================

# SRS operations
---
name: test_I256_v16_acc32_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0, $r0, $r1
    ; CHECK-LABEL: name: test_I256_v16_acc32_srs
    ; CHECK: liveins: $bmll0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), [[COPY]](<16 x s32>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc32.srs), %1(<16 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_I256_v16_acc64_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0, $r0, $r1
    ; CHECK-LABEL: name: test_I256_v16_acc64_srs
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc64.srs), [[COPY]](<16 x s64>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s64>) = COPY $cml0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_I256_v32_acc32_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0, $r0, $r1
    ; CHECK-LABEL: name: test_I256_v32_acc32_srs
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), [[COPY]](<32 x s32>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<32 x s32>) = COPY $cml0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_I256_v8_acc64_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0, $r0, $r1
    ; CHECK-LABEL: name: test_I256_v8_acc64_srs
    ; CHECK: liveins: $bmll0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bmll0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v8.acc64.srs), [[COPY]](<8 x s64>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<8 x s64>) = COPY $bmll0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I256.v8.acc64.srs), %1(<8 x s64>), %2(s32), %3(s32)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_I512_v16_acc64_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_v16_acc64_srs
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v16.acc64.srs), [[COPY]](<16 x s64>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<16 x s64>) = COPY $cml0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v16.acc64.srs), %1(<16 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name: test_I512_v32_acc32_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_v32_acc32_srs
    ; CHECK: liveins: $cml0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc32.srs), [[COPY]](<32 x s32>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s32>) = COPY $cml0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc32.srs), %1(<32 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name: test_I512_v32_acc64_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $dm0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_v32_acc64_srs
    ; CHECK: liveins: $dm0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc64.srs), [[COPY]](<32 x s64>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s64>) = COPY $dm0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v32.acc64.srs), %1(<32 x s64>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name: test_I512_v64_acc32_srs
legalized: true
body: |
  bb.1.entry:
    liveins: $dm0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_v64_acc32_srs
    ; CHECK: liveins: $dm0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), [[COPY]](<64 x s32>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<64 x s32>) = COPY $dm0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.I512.v64.acc32.srs), %1(<64 x s32>), %2(s32), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

# AccFloat to other type conversions
---
name: test_v16accfloat_to_v16bf16
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_v16accfloat_to_v16bf16
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16bf16), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_v32accfloat_to_v32bf16
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0
    ; CHECK-LABEL: name: test_v32accfloat_to_v32bf16
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), [[COPY]](<32 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s32>) = COPY $cml0
    %0:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bf16), %1(<32 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name: test_v16accfloat_to_v16float16
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_v16accfloat_to_v16float16
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16float16), [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v16accfloat.to.v16float16), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_v32accfloat_to_v32float16
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0
    ; CHECK-LABEL: name: test_v32accfloat_to_v32float16
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), [[COPY]](<32 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<32 x s32>) = COPY $cml0
    %0:_(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float16), %1(<32 x s32>)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name: test_v32accfloat_to_v32float8
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0, $r0
    ; CHECK-LABEL: name: test_v32accfloat_to_v32float8
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float8), [[COPY]](<32 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<32 x s32>) = COPY $cml0
    %2:_(s32) = COPY $r0
    %0:_(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32float8), %1(<32 x s32>), %2(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_v32accfloat_to_v32bfloat8
legalized: true
body: |
  bb.1.entry:
    liveins: $cml0, $r0
    ; CHECK-LABEL: name: test_v32accfloat_to_v32bfloat8
    ; CHECK: liveins: $cml0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bfloat8), [[COPY]](<32 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<32 x s8>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<32 x s32>) = COPY $cml0
    %2:_(s32) = COPY $r0
    %0:_(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v32accfloat.to.v32bfloat8), %1(<32 x s32>), %2(s32)
    $wl0 = COPY %0(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_v64accfloat_to_v64mx4
legalized: true
body: |
  bb.1.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_v64accfloat_to_v64mx4
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<8 x s32>), [[INT1:%[0-9]+]]:gprregbank(<2 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx4), [[COPY]](<64 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<64 x s32>) = COPY $dm0
    %0:_(<8 x s32>), %2:_(<2 x s32>), %3:_(s32), %4:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx4), %1(<64 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_v64accfloat_to_v64mx6
legalized: true
body: |
  bb.1.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_v64accfloat_to_v64mx6
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<8 x s32>), [[INT1:%[0-9]+]]:gprregbank(<2 x s32>), [[INT2:%[0-9]+]]:gprregbank(s32), [[INT3:%[0-9]+]]:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx6), [[COPY]](<64 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<8 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<64 x s32>) = COPY $dm0
    %0:_(<8 x s32>), %2:_(<2 x s32>), %3:_(s32), %4:_(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx6), %1(<64 x s32>)
    $wl0 = COPY %0(<8 x s32>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_v64accfloat_to_v64mx9
legalized: true
body: |
  bb.1.entry:
    liveins: $dm0
    ; CHECK-LABEL: name: test_v64accfloat_to_v64mx9
    ; CHECK: liveins: $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s32>), [[INT1:%[0-9]+]]:gprregbank(<2 x s32>), [[INT2:%[0-9]+]]:gprregbank(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx9), [[COPY]](<64 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:_(<64 x s32>) = COPY $dm0
    %0:_(<16 x s32>), %2:_(<2 x s32>), %3:_(<2 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.v64accfloat.to.v64mx9), %1(<64 x s32>)
    $x0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...

# NLF with AccFloat
---
name: test_exp2_bf20
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_exp2_bf20
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.exp2.bf20), [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $bmll0 = COPY [[INT]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bmll0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.exp2.bf20), %1(<16 x s32>)
    $bmll0 = COPY %0(<16 x s32>)
    PseudoRET implicit $lr, implicit $bmll0
...

---
name: test_exp2
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_exp2
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.exp2), [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.exp2), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name: test_tanh
legalized: true
body: |
  bb.1.entry:
    liveins: $bmll0
    ; CHECK-LABEL: name: test_tanh
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s32>) = COPY $bmll0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.tanh), [[COPY]](<16 x s32>)
    ; CHECK-NEXT: $wl0 = COPY [[INT]](<16 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:_(<16 x s32>) = COPY $bmll0
    %0:_(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2ps.tanh), %1(<16 x s32>)
    $wl0 = COPY %0(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...


# ============================================================================
# Category 4: Operands 0 and 2 (Output + Input Accumulator)
# ============================================================================

# Integer MAC/MUL operations (ACC2048)
---
name: test_I1024_I1024_ACC2048_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_I1024_I1024_ACC2048_mac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I1024_ACC2048_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_I1024_I1024_ACC2048_msc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I1024_ACC2048_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_I1024_I1024_ACC2048_mul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I1024_ACC2048_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_I1024_I1024_ACC2048_negmul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I512_ACC2048_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $x1, $dm1, $r0
    ; CHECK-LABEL: name: test_I1024_I512_ACC2048_mac_conf
    ; CHECK: liveins: $y0, $x1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.mac.conf), %1(<64 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I512_ACC2048_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $x1, $dm1, $r0
    ; CHECK-LABEL: name: test_I1024_I512_ACC2048_msc_conf
    ; CHECK: liveins: $y0, $x1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.msc.conf), %1(<64 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I512_ACC2048_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $x1, $r0
    ; CHECK-LABEL: name: test_I1024_I512_ACC2048_mul_conf
    ; CHECK: liveins: $y0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.mul.conf), %1(<64 x s16>), %2(<32 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I512_ACC2048_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $x1, $r0
    ; CHECK-LABEL: name: test_I1024_I512_ACC2048_negmul_conf
    ; CHECK: liveins: $y0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.negmul.conf), %1(<64 x s16>), %2(<32 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_short_ACC2048_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_I1024_short_ACC2048_mac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.mac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_short_ACC2048_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_I1024_short_ACC2048_msc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.msc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_short_ACC2048_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_I1024_short_ACC2048_mul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.mul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_short_ACC2048_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_I1024_short_ACC2048_negmul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.negmul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_char_ACC2048_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_I512_char_ACC2048_mac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.mac.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_char_ACC2048_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_I512_char_ACC2048_msc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.msc.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_char_ACC2048_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_char_ACC2048_mul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.mul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_char_ACC2048_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_char_ACC2048_negmul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.negmul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I1024_ACC2048_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_I512_I1024_ACC2048_mac_conf
    ; CHECK: liveins: $x0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I1024_ACC2048_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_I512_I1024_ACC2048_msc_conf
    ; CHECK: liveins: $x0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I1024_ACC2048_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_I512_I1024_ACC2048_mul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I1024_ACC2048_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_I512_I1024_ACC2048_negmul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I512_ACC2048_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC2048_mac_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I512_ACC2048_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC2048_msc_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I512_ACC2048_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC2048_mul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.mul.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.mul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I512_ACC2048_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC2048_negmul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.negmul.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.negmul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_short_ACC2048_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_I512_short_ACC2048_mac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.mac.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_short_ACC2048_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_I512_short_ACC2048_msc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.msc.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_short_ACC2048_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_short_ACC2048_mul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.mul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_short_ACC2048_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_I512_short_ACC2048_negmul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.negmul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# Integer MAC/MUL operations (ACC1024)
---
name: test_I512_I512_ACC1024_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC1024_mac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_I512_I512_ACC1024_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC1024_msc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_I512_I512_ACC1024_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC1024_mul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_I512_I512_ACC1024_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC1024_negmul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

# BFloat16 MAC/MUL operations (ACC2048)
---
name: test_bf16_I1024_bf16_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_I1024_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_I1024_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_I1024_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_I1024_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_I1024_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_I1024_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_I1024_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_I1024_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_I1024_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_I1024_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_I1024_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_I1024_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_I1024_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_I1024_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_I1024_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_I1024_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# BFloat16 MAC/MUL operations (ACC1024)
---
name: test_bf16_I512_bf16_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_bf16_I512_bf16_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_bf16_I512_bf16_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I512_bf16_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I512_bf16_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I1024_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I1024_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I1024_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I1024_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I1024_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I1024_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I1024_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I1024_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I512_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I512_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I512_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I512_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I512_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I512_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I512_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I512_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_bf16_I512_fp16_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_bf16_I512_fp16_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I512_fp16_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_bf16_I512_fp16_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I1024_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I1024_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I1024_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I1024_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I1024_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I1024_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I1024_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I1024_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I512_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I512_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I512_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I512_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I512_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I512_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I512_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I512_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

# Float16 MAC/MUL operations (ACC2048)
---
name: test_fp16_I1024_bf16_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_I1024_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_I1024_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_I1024_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_I1024_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_I1024_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_I1024_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_I1024_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_I1024_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(s32), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_I1024_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_I1024_ACC2048_bf_mac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.mac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.mac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_I1024_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_I1024_ACC2048_bf_msc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.msc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.msc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_I1024_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_I1024_ACC2048_bf_mul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.mul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.mul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_I1024_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_I1024_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $y0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.negmul.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.negmul.conf), %1(<64 x s16>), %2(<64 x s16>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# Float16 MAC/MUL operations (ACC1024)
---
name: test_fp16_I512_bf16_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_fp16_I512_bf16_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_fp16_I512_bf16_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I512_bf16_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I512_bf16_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I1024_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I1024_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I1024_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I1024_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I1024_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I1024_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I1024_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I1024_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I512_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I512_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I512_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I512_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I512_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I512_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I512_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I512_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_fp16_I512_fp16_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1
    ; CHECK-LABEL: name: test_fp16_I512_fp16_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I512_fp16_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1
    ; CHECK-LABEL: name: test_fp16_I512_fp16_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(s32), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I1024_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I1024_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I1024_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I1024_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I1024_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I1024_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I1024_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I1024_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $y1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<64 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I512_ACC1024_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I512_ACC1024_bf_mac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.mac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.mac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I512_ACC1024_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I512_ACC1024_bf_msc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.msc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.msc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I512_ACC1024_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I512_ACC1024_bf_mul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.mul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.mul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I512_ACC1024_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I512_ACC1024_bf_negmul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.negmul.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.negmul.conf), %1(<32 x s16>), %2(<32 x s16>), %3(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

# Float8 MAC/MUL operations (ACC2048)
---
name: test_fp8_I512_fp8_I512_ACC2048_bf_mac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $r0
    ; CHECK-LABEL: name: test_fp8_I512_fp8_I512_ACC2048_bf_mac_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.mac.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.mac.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp8_I512_fp8_I512_ACC2048_bf_msc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $r0
    ; CHECK-LABEL: name: test_fp8_I512_fp8_I512_ACC2048_bf_msc_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.msc.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](<64 x s32>), [[COPY3]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.msc.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp8_I512_fp8_I512_ACC2048_bf_mul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_fp8_I512_fp8_I512_ACC2048_bf_mul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.mul.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.mul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp8_I512_fp8_I512_ACC2048_bf_negmul_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $r0
    ; CHECK-LABEL: name: test_fp8_I512_fp8_I512_ACC2048_bf_negmul_conf
    ; CHECK: liveins: $x0, $x1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.negmul.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.negmul.conf), %1(<64 x s8>), %2(<64 x s8>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# Accumulator arithmetic operations
---
name: test_ACC2048_add_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_ACC2048_add_conf
    ; CHECK: liveins: $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.add.conf), [[COPY]](<32 x s64>), [[COPY1]](<32 x s64>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s64>) = COPY $dm1
    %2:_(<32 x s64>) = COPY $dm2
    %3:_(s32) = COPY $r0
    %0:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.add.conf), %1(<32 x s64>), %2(<32 x s64>), %3(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_ACC2048_sub_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_ACC2048_sub_conf
    ; CHECK: liveins: $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.sub.conf), [[COPY]](<32 x s64>), [[COPY1]](<32 x s64>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s64>) = COPY $dm1
    %2:_(<32 x s64>) = COPY $dm2
    %3:_(s32) = COPY $r0
    %0:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.sub.conf), %1(<32 x s64>), %2(<32 x s64>), %3(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_ACC2048_neg_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $dm1, $r0
    ; CHECK-LABEL: name: test_ACC2048_neg_conf
    ; CHECK: liveins: $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<32 x s64>) = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.neg.conf), [[COPY]](<32 x s64>), [[COPY1]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<32 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s64>) = COPY $dm1
    %2:_(s32) = COPY $r0
    %0:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2ps.ACC2048.neg.conf), %1(<32 x s64>), %2(s32)
    $dm0 = COPY %0(<32 x s64>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_ACC2048_accfloat_add_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_ACC2048_accfloat_add_conf
    ; CHECK: liveins: $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.add.conf), [[COPY]](<64 x s32>), [[COPY1]](<64 x s32>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(<64 x s32>) = COPY $dm2
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.add.conf), %1(<64 x s32>), %2(<64 x s32>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_ACC2048_accfloat_sub_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_ACC2048_accfloat_sub_conf
    ; CHECK: liveins: $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.sub.conf), [[COPY]](<64 x s32>), [[COPY1]](<64 x s32>), [[COPY2]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(<64 x s32>) = COPY $dm2
    %3:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.sub.conf), %1(<64 x s32>), %2(<64 x s32>), %3(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_ACC2048_accfloat_neg_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $dm1, $r0
    ; CHECK-LABEL: name: test_ACC2048_accfloat_neg_conf
    ; CHECK: liveins: $dm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.neg.conf), [[COPY]](<64 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s32>) = COPY $dm1
    %2:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.ACC2048.accfloat.neg.conf), %1(<64 x s32>), %2(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# ============================================================================
# Category 5: Operands 0, 2, and 3 (ADDMAC operations)
# ============================================================================

# Integer ADDMAC operations (ACC2048)
---
name: test_I1024_I1024_ACC2048_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I1024_I1024_ACC2048_addmac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I1024_ACC2048_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I1024_I1024_ACC2048_addmsc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I1024.ACC2048.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I512_ACC2048_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $x1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I1024_I512_ACC2048_addmac_conf
    ; CHECK: liveins: $y0, $x1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.addmac.conf), %1(<64 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_I512_ACC2048_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $x1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I1024_I512_ACC2048_addmsc_conf
    ; CHECK: liveins: $y0, $x1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.I512.ACC2048.addmsc.conf), %1(<64 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_short_ACC2048_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_I1024_short_ACC2048_addmac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.addmac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I1024_short_ACC2048_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_I1024_short_ACC2048_addmsc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I1024.short.ACC2048.addmsc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_char_ACC2048_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_I512_char_ACC2048_addmac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.addmac.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_char_ACC2048_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_I512_char_ACC2048_addmsc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.char.ACC2048.addmsc.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I1024_ACC2048_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I512_I1024_ACC2048_addmac_conf
    ; CHECK: liveins: $x0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I1024_ACC2048_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I512_I1024_ACC2048_addmsc_conf
    ; CHECK: liveins: $x0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I1024.ACC2048.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I512_ACC2048_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC2048_addmac_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_I512_ACC2048_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC2048_addmsc_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC2048.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_short_ACC2048_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_I512_short_ACC2048_addmac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.addmac.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_I512_short_ACC2048_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_I512_short_ACC2048_addmsc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.short.ACC2048.addmsc.conf), %1(<32 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# Integer ADDMAC operations (ACC1024)
---
name: test_I512_I512_ACC1024_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC1024_addmac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_I512_I512_ACC1024_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_I512_I512_ACC1024_addmsc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2ps.I512.I512.ACC1024.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

# BFloat16 ADDMAC operations (ACC2048)
---
name: test_bf16_I1024_bf16_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_I1024_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_I1024_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_bf16_I1024_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_bf16_I1024_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.bf16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_I1024_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_I1024_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_bf16_I1024_fp16_I1024_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_bf16_I1024_fp16_I1024_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I1024.fp16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# BFloat16 ADDMAC operations (ACC1024)
---
name: test_bf16_I512_bf16_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_bf16_I512_bf16_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_bf16_I512_bf16_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I1024_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I1024_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I1024_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I1024_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I512_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I512_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_bf16_I512_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_bf16_I512_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.bf16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_bf16_I512_fp16_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_bf16_I512_fp16_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I1024_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I1024_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I1024_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I1024_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I512_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I512_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_bf16_I512_fp16_I512_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_bf16_I512_fp16_I512_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.bf16.I512.fp16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

# Float16 ADDMAC operations (ACC2048)
---
name: test_fp16_I1024_bf16_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_I1024_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_I1024_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_bf16_I1024_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_bf16_I1024_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.bf16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $r0, $r1, $dm1, $dm2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](s32), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(s32) = COPY $r0
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r1
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(s32), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_I1024_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_I1024_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.addmac.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.addmac.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp16_I1024_fp16_I1024_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_fp16_I1024_fp16_I1024_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $y0, $y1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s16>) = COPY $y0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I1024.fp16.I1024.ACC2048.bf.addmsc.conf), %1(<64 x s16>), %2(<64 x s16>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

# Float16 ADDMAC operations (ACC1024)
---
name: test_fp16_I512_bf16_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_fp16_I512_bf16_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_fp16_I512_bf16_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I1024_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I1024_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I1024_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I1024_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I512_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I512_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_bf16_I512_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_bf16_I512_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.bf16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_fp16_I512_fp16_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-LABEL: name: test_fp16_I512_fp16_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $r0, $r1, $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](s32), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(s32) = COPY $r0
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r1
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(s32), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I1024_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I1024_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I1024_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I1024_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $y1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s16>) = COPY $y1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<64 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<64 x s16>) = COPY $y1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I1024.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<64 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I512_ACC1024_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I512_ACC1024_bf_addmac_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.addmac.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.addmac.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

---
name: test_fp16_I512_fp16_I512_ACC1024_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-LABEL: name: test_fp16_I512_fp16_I512_ACC1024_bf_addmsc_conf
    ; CHECK: liveins: $x0, $x1, $cml1, $cml2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<32 x s16>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<32 x s32>) = COPY $cml2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.addmsc.conf), [[COPY]](<32 x s16>), [[COPY1]](<32 x s16>), [[COPY2]](<32 x s32>), [[COPY3]](<32 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $cml0 = COPY [[INT]](<32 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:_(<32 x s16>) = COPY $x0
    %2:_(<32 x s16>) = COPY $x1
    %3:_(<32 x s32>) = COPY $cml1
    %4:_(<32 x s32>) = COPY $cml2
    %5:_(s32) = COPY $r0
    %0:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp16.I512.fp16.I512.ACC1024.bf.addmsc.conf), %1(<32 x s16>), %2(<32 x s16>), %3(<32 x s32>), %4(<32 x s32>), %5(s32)
    $cml0 = COPY %0(<32 x s32>)
    PseudoRET implicit $lr, implicit $cml0
...

# Float8 ADDMAC operations (ACC2048)
---
name: test_fp8_I512_fp8_I512_ACC2048_bf_addmac_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_fp8_I512_fp8_I512_ACC2048_bf_addmac_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.addmac.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.addmac.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...

---
name: test_fp8_I512_fp8_I512_ACC2048_bf_addmsc_conf
legalized: true
body: |
  bb.1.entry:
    liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-LABEL: name: test_fp8_I512_fp8_I512_ACC2048_bf_addmsc_conf
    ; CHECK: liveins: $x0, $x1, $dm1, $dm2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<64 x s32>) = COPY $dm2
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.addmsc.conf), [[COPY]](<64 x s8>), [[COPY1]](<64 x s8>), [[COPY2]](<64 x s32>), [[COPY3]](<64 x s32>), [[COPY4]](s32)
    ; CHECK-NEXT: $dm0 = COPY [[INT]](<64 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<64 x s8>) = COPY $x1
    %3:_(<64 x s32>) = COPY $dm1
    %4:_(<64 x s32>) = COPY $dm2
    %5:_(s32) = COPY $r0
    %0:_(<64 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2ps.fp8.I512.fp8.I512.ACC2048.bf.addmsc.conf), %1(<64 x s8>), %2(<64 x s8>), %3(<64 x s32>), %4(<64 x s32>), %5(s32)
    $dm0 = COPY %0(<64 x s32>)
    PseudoRET implicit $lr, implicit $dm0
...
