# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s

# A loaded pointer whose every use forces it onto a GPR (G_ICMP / pointer
# G_SELECT) is mapped to the GPR bank directly, avoiding a ptr->gpr bridging
# copy. When at least one use dereferences the pointer, it stays on the
# pointer bank.

# G_AIE_OFFSET_LOAD result used only by an equality compare -> GPR bank.
---
name: offset_load_only_icmp
legalized: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: offset_load_only_icmp
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:ptrregbank(p0) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[TRUNC]](s20) :: (load (p0), align 4)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(p0) = COPY [[AIE_OFFSET_LOAD]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[COPY3]](p0), [[COPY4]]
    ; CHECK-NEXT: $r1 = COPY [[ICMP]](s32)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_TRUNC %2
    %4:_(p0) = G_AIE_OFFSET_LOAD %0, %3 :: (load (p0))
    %5:_(s32) = G_ICMP intpred(eq), %4, %1
    $r1 = COPY %5
...

# G_AIE_OFFSET_LOAD result used by two compares -> still GPR bank.
---
name: offset_load_two_icmps
legalized: true
body: |
  bb.0:
    liveins: $p0, $p1, $p2, $r0
    ; CHECK-LABEL: name: offset_load_two_icmps
    ; CHECK: liveins: $p0, $p1, $p2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ptrregbank(p0) = COPY $p2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY3]](s32)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:ptrregbank(p0) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[TRUNC]](s20) :: (load (p0), align 4)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(p0) = COPY [[AIE_OFFSET_LOAD]](p0)
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gprregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[COPY4]](p0), [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:gprregbank(p0) = COPY [[AIE_OFFSET_LOAD]](p0)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:gprregbank(p0) = COPY [[COPY2]](p0)
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(ne), [[COPY6]](p0), [[COPY7]]
    ; CHECK-NEXT: $r1 = COPY [[ICMP]](s32)
    ; CHECK-NEXT: $r2 = COPY [[ICMP1]](s32)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(p0) = COPY $p2
    %3:_(s32) = COPY $r0
    %4:_(s20) = G_TRUNC %3
    %5:_(p0) = G_AIE_OFFSET_LOAD %0, %4 :: (load (p0))
    %6:_(s32) = G_ICMP intpred(eq), %5, %1
    %7:_(s32) = G_ICMP intpred(ne), %5, %2
    $r1 = COPY %6
    $r2 = COPY %7
...

# G_AIE_OFFSET_LOAD result feeding a pointer G_SELECT -> GPR bank.
---
name: offset_load_pointer_select
legalized: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: offset_load_pointer_select
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:ptrregbank(p0) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[TRUNC]](s20) :: (load (p0), align 4)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(p0) = COPY [[AIE_OFFSET_LOAD]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprregbank(p0) = G_SELECT [[COPY2]](s32), [[COPY3]], [[COPY4]]
    ; CHECK-NEXT: $p1 = COPY [[SELECT]](p0)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_TRUNC %2
    %4:_(p0) = G_AIE_OFFSET_LOAD %0, %3 :: (load (p0))
    %5:_(p0) = G_SELECT %2, %4, %1
    $p1 = COPY %5
...

# G_AIE_POSTINC_LOAD: the loaded value (def #0) feeds a compare -> GPR bank,
# while the incremented pointer (def #1) stays on the pointer bank.
---
name: postinc_load_only_icmp
legalized: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: postinc_load_only_icmp
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[AIE_POSTINC_LOAD:%[0-9]+]]:ptrregbank(p0), [[AIE_POSTINC_LOAD1:%[0-9]+]]:ptrregbank(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[TRUNC]](s20) :: (load (p0), align 4)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(p0) = COPY [[AIE_POSTINC_LOAD]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[COPY3]](p0), [[COPY4]]
    ; CHECK-NEXT: $r1 = COPY [[ICMP]](s32)
    ; CHECK-NEXT: $p2 = COPY [[AIE_POSTINC_LOAD1]](p0)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_TRUNC %2
    %4:_(p0), %5:_(p0) = G_AIE_POSTINC_LOAD %0, %3 :: (load (p0))
    %6:_(s32) = G_ICMP intpred(eq), %4, %1
    $r1 = COPY %6
    $p2 = COPY %5
...

# Plain G_LOAD result used only by a compare -> GPR bank (base-class path).
---
name: plain_load_only_icmp
legalized: true
body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: plain_load_only_icmp
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:ptrregbank(p0) = G_LOAD [[COPY]](p0) :: (load (p0), align 4)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(p0) = COPY [[LOAD]](p0)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[COPY2]](p0), [[COPY3]]
    ; CHECK-NEXT: $r1 = COPY [[ICMP]](s32)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(p0) = G_LOAD %0 :: (load (p0))
    %3:_(s32) = G_ICMP intpred(eq), %2, %1
    $r1 = COPY %3
...

# Negative test: a mixed use (compare + dereference) keeps the loaded pointer
# on the pointer bank, since not every use forces it onto a GPR.
---
name: offset_load_mixed_use_stays_ptr
legalized: true
body: |
  bb.0:
    liveins: $p0, $p1, $r0
    ; CHECK-LABEL: name: offset_load_mixed_use_stays_ptr
    ; CHECK: liveins: $p0, $p1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY2]](s32)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:ptrregbank(p0) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[TRUNC]](s20) :: (load (p0), align 4)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprregbank(p0) = COPY [[AIE_OFFSET_LOAD]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gprregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprregbank(s32) = G_ICMP intpred(eq), [[COPY3]](p0), [[COPY4]]
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD1:%[0-9]+]]:gprregbank(s32) = G_AIE_OFFSET_LOAD [[AIE_OFFSET_LOAD]](p0), [[TRUNC]](s20) :: (load (s32))
    ; CHECK-NEXT: $r1 = COPY [[ICMP]](s32)
    ; CHECK-NEXT: $r2 = COPY [[AIE_OFFSET_LOAD1]](s32)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s32) = COPY $r0
    %3:_(s20) = G_TRUNC %2
    %4:_(p0) = G_AIE_OFFSET_LOAD %0, %3 :: (load (p0))
    %5:_(s32) = G_ICMP intpred(eq), %4, %1
    %6:_(s32) = G_AIE_OFFSET_LOAD %4, %3 :: (load (s32))
    $r1 = COPY %5
    $r2 = COPY %6
...

# Negative test: a loaded pointer that is dereferenced stays on the pointer
# bank.
---
name: offset_load_deref_stays_ptr
legalized: true
body: |
  bb.0:
    liveins: $p0, $r0
    ; CHECK-LABEL: name: offset_load_deref_stays_ptr
    ; CHECK: liveins: $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprregbank(s32) = COPY $r0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:modregbank(s20) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:ptrregbank(p0) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[TRUNC]](s20) :: (load (p0), align 4)
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD1:%[0-9]+]]:gprregbank(s32) = G_AIE_OFFSET_LOAD [[AIE_OFFSET_LOAD]](p0), [[TRUNC]](s20) :: (load (s32))
    ; CHECK-NEXT: $r1 = COPY [[AIE_OFFSET_LOAD1]](s32)
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s20) = G_TRUNC %1
    %3:_(p0) = G_AIE_OFFSET_LOAD %0, %2 :: (load (p0))
    %4:_(s32) = G_AIE_OFFSET_LOAD %3, %2 :: (load (s32))
    $r1 = COPY %4
...
