// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-ldst-intrinsic.cpp ------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O1 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2P
// RUN: %clang -O1 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2PS

// AIE2P-LABEL: @_Z22test_pack_v32i8_v32i16Dv32_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.pack.I512.I8.I16(<32 x i16> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z22test_pack_v32i8_v32i16Dv32_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.pack.I512.I8.I16(<32 x i16> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP0]]
//
v32int8 test_pack_v32i8_v32i16(v32int16 v, int sign) {
  return pack(v, sign);
}

// AIE2P-LABEL: @_Z24test_unpack_v32i16_v32i8Dv32_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> [[V:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z24test_unpack_v32i16_v32i8Dv32_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.unpack.I512.I16.I8(<32 x i8> [[V:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_unpack_v32i16_v32i8(v32int8 v) {
  return unpack(v);
}

//
// AIE2P-LABEL: @_Z21test_pack_v64i4_v64i8Dv64_hi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.pack.I512.I4.I8(<64 x i8> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z21test_pack_v64i4_v64i8Dv64_hi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.pack.I512.I4.I8(<64 x i8> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP0]]
//
v64uint4 test_pack_v64i4_v64i8(v64uint8 v, int sign) {
  return pack(v, sign);
}

// AIE2P-LABEL: @_Z23test_unpack_v64i8_v64i4Dv32_DU8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.unpack.I512.I8.I4(<32 x i8> [[V:%.*]], i32 0)
// AIE2P-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z23test_unpack_v64i8_v64i4Dv32_DU8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.unpack.I512.I8.I4(<32 x i8> [[V:%.*]], i32 0)
// AIE2PS-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 test_unpack_v64i8_v64i4(v64uint4 v) {
  return unpack(v);
}

// AIE2P-LABEL: @_Z22test_pack_v64i8_v64i16Dv64_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.pack.I1024.I8.I16(<64 x i16> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z22test_pack_v64i8_v64i16Dv64_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.pack.I1024.I8.I16(<64 x i16> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 test_pack_v64i8_v64i16(v64uint16 v, int sign) {
  return pack(v, sign);
}

// AIE2P-LABEL: @_Z24test_unpack_v64i16_v64i8Dv64_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i16> @llvm.aie2p.unpack.I1024.I16.I8(<64 x i8> [[V:%.*]], i32 0)
// AIE2P-NEXT:    ret <64 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z24test_unpack_v64i16_v64i8Dv64_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i16> @llvm.aie2ps.unpack.I1024.I16.I8(<64 x i8> [[V:%.*]], i32 0)
// AIE2PS-NEXT:    ret <64 x i16> [[TMP0]]
//
v64uint16 test_unpack_v64i16_v64i8(v64uint8 v) {
  return unpack(v);
}

// AIE2P-LABEL: @_Z23test_pack_v128i4_v128i8Dv128_hi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.pack.I1024.I4.I8(<128 x i8> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z23test_pack_v128i4_v128i8Dv128_hi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.pack.I1024.I4.I8(<128 x i8> [[V:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP0]]
//
v128uint4 test_pack_v128i4_v128i8(v128uint8 v, int sign) {
  return pack(v, sign);
}

// AIE2P-LABEL: @_Z25test_unpack_v128i8_v128i4Dv64_DU8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8> [[V:%.*]], i32 0)
// AIE2P-NEXT:    ret <128 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z25test_unpack_v128i8_v128i4Dv64_DU8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <128 x i8> @llvm.aie2ps.unpack.I1024.I8.I4(<64 x i8> [[V:%.*]], i32 0)
// AIE2PS-NEXT:    ret <128 x i8> [[TMP0]]
//
v128uint8 test_unpack_v128i8_v128i4(v128uint4 v) {
  return unpack(v);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv64_DB8_S0_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2:![0-9]+]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7:![0-9]+]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10:![0-9]+]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv64_DB8_S0_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2:![0-9]+]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7:![0-9]+]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10:![0-9]+]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v128int4 * restrict &p, v128int4 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv64_DB8_S0_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11:![0-9]+]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv64_DB8_S0_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11:![0-9]+]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v128int4 * restrict &p, v128int4 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv64_DB8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv64_DB8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v128int4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v128int4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_DB8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_DB8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v128int4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v128int4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_DB8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_DB8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v128int4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v128int4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv64_DU8_S0_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv64_DU8_S0_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v128uint4 * restrict &p, v128uint4 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv64_DU8_S0_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv64_DU8_S0_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v128uint4 * restrict &p, v128uint4 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv64_DU8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv64_DU8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v128uint4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_DU8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_DU8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v128uint4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_DU8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_DU8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v128uint4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv64_aS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv64_aS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64int8 * restrict &p, v64int8 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv64_aS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv64_aS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v64int8 * restrict &p, v64int8 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv64_aR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv64_aR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v64int8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_aR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_aR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64int8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_aR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_aR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64int8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_aR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_aR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64int8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_aR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_aR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64int8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_aR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_aR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64int8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv64_hS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv64_hS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64uint8 * restrict &p, v64uint8 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv64_hS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv64_hS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v64uint8 * restrict &p, v64uint8 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv64_hR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv64_hR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v64uint8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_hR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_hR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_hR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_hR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64uint8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_hR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_hR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_hR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_hR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64uint8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_hR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_hR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv32_sS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv32_sS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v32int16 * restrict &p, v32int16 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv32_sS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv32_sS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v32int16 * restrict &p, v32int16 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v32int16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_sR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_sR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32int16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32int16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_sR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_sR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32int16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32int16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_sR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_sR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32int16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv32_tS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv32_tS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v32uint16 * restrict &p, v32uint16 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv32_tS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv32_tS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v32uint16 * restrict &p, v32uint16 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv32_tR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv32_tR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v32uint16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_tR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_tR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_tR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_tR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32uint16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_tR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_tR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_tR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_tR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32uint16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_tR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_tR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv16_iS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv16_iS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v16int32 * restrict &p, v16int32 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv16_iS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv16_iS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v16int32 * restrict &p, v16int32 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv16_iR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv16_iR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v16int32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_iR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_iR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v16int32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_iR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_iR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v16int32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_iR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_iR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v16int32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_iR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_iR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v16int32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_iR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_iR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v16int32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv16_jS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv16_jS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v16uint32 * restrict &p, v16uint32 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv16_jS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv16_jS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v16uint32 * restrict &p, v16uint32 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv16_jR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv16_jR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v16uint32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_jR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_jR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_jR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_jR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v16uint32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_jR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_jR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_jR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_jR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v16uint32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_jR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_jR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv32_8bfloat16S0_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x bfloat> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv32_8bfloat16S0_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x bfloat> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v32bfloat16 * restrict &p, v32bfloat16 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv32_8bfloat16S0_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x bfloat> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv32_8bfloat16S0_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x bfloat> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v32bfloat16 * restrict &p, v32bfloat16 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv32_8bfloat16R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v32bfloat16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_8bfloat16R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32bfloat16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32bfloat16 * restrict &p, fifo_state_t &s,
                                     int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_8bfloat16R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32bfloat16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32bfloat16 * restrict &p, fifo_state_t &s,
                                     int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_st_resetRrPDv16_fS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_resetRrPDv16_fS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v16float * restrict &p, v16float v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// AIE2P-LABEL: @_Z17test_fifo_st_pushRrPDv16_fS_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_st_pushRrPDv16_fS_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v16float * restrict &p, v16float v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// AIE2P-LABEL: @_Z18test_fifo_st_flushRrPDv16_fR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_st_flushRrPDv16_fR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v16float * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_fR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_fR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v16float * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_fR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_fR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v16float * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_fR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_fR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v16float * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_fR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_fR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v16float * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_fR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_fR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v16float * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2P-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2P-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2P-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv64_DB8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv64_DB8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv64_DB8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv64_DB8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv64_DB8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP4]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv64_DB8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP4]]
//
v128int4 test_fifo_ld_pop(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_DB8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_DB8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v128int4 test_fifo_ld_pop_1d_byte(v128int4 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_DB8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_DB8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP9]]
//
v128int4 test_fifo_ld_pop_2d_byte(v128int4 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP13]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP13]]
//
v128int4 test_fifo_ld_pop_3d_byte(v128int4 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv64_DU8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv64_DU8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv64_DU8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv64_DU8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv64_DU8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP4]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv64_DU8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP4]]
//
v128uint4 test_fifo_ld_pop(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_DU8_R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_DU8_R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v128uint4 test_fifo_ld_pop_1d_byte(v128uint4 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_DU8_R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_DU8_R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP9]]
//
v128uint4 test_fifo_ld_pop_2d_byte(v128uint4 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_DU8_R12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP13]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_DU8_R12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP13]]
//
v128uint4 test_fifo_ld_pop_3d_byte(v128uint4 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1,
                                   int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv64_aR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv64_aR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv64_aR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv64_aR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv64_aR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP4]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv64_aR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP4]]
//
v64int8 test_fifo_ld_pop(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_aR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_aR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v64int8 test_fifo_ld_pop_1d_byte(v64int8 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_aR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_aR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP9]]
//
v64int8 test_fifo_ld_pop_2d_byte(v64int8 *&p, fifo_state_t &s, int off,
                                 int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_aR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP13]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_aR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP13]]
//
v64int8 test_fifo_ld_pop_3d_byte(v64int8 *&p, fifo_state_t &s, int off,
                                 int size1, addr_t &count1, int inc1, int size2,
                                 addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv64_hR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv64_hR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv64_hR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv64_hR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv64_hR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP4]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv64_hR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP4]]
//
v64uint8 test_fifo_ld_pop(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_hR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_hR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v64uint8 test_fifo_ld_pop_1d_byte(v64uint8 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_hR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_hR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP9]]
//
v64uint8 test_fifo_ld_pop_2d_byte(v64uint8 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_hR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP13]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_hR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP13]]
//
v64uint8 test_fifo_ld_pop_3d_byte(v64uint8 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP8]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP8]]
//
v32int16 test_fifo_ld_pop(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_sR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_sR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP9]]
//
v32int16 test_fifo_ld_pop_1d_byte(v32int16 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_sR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP15]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_sR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP15]]
//
v32int16 test_fifo_ld_pop_2d_byte(v32int16 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_sR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP21]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_sR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP21]]
//
v32int16 test_fifo_ld_pop_3d_byte(v32int16 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv32_tR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv32_tR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv32_tR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv32_tR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv32_tR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP8]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv32_tR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP8]]
//
v32uint16 test_fifo_ld_pop(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_tR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_tR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP9]]
//
v32uint16 test_fifo_ld_pop_1d_byte(v32uint16 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_tR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP15]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_tR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP15]]
//
v32uint16 test_fifo_ld_pop_2d_byte(v32uint16 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_tR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP21]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_tR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP21]]
//
v32uint16 test_fifo_ld_pop_3d_byte(v32uint16 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1,
                                   int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv16_iR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv16_iR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv16_iR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv16_iR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv16_iR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP8]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv16_iR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP8]]
//
v16int32 test_fifo_ld_pop(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_iR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_iR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP9]]
//
v16int32 test_fifo_ld_pop_1d_byte(v16int32 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_iR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP15]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_iR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP15]]
//
v16int32 test_fifo_ld_pop_2d_byte(v16int32 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_iR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP21]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_iR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP21]]
//
v16int32 test_fifo_ld_pop_3d_byte(v16int32 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv16_jR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv16_jR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv16_jR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv16_jR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv16_jR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP8]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv16_jR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP8]]
//
v16uint32 test_fifo_ld_pop(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_jR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_jR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP9]]
//
v16uint32 test_fifo_ld_pop_1d_byte(v16uint32 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_jR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP15]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_jR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP15]]
//
v16uint32 test_fifo_ld_pop_2d_byte(v16uint32 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_jR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP21]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_jR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP21]]
//
v16uint32 test_fifo_ld_pop_3d_byte(v16uint32 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1,
                                   int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv32_8bfloat16R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv32_8bfloat16R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv32_8bfloat16R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP8]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP8]]
//
v32bfloat16 test_fifo_ld_pop(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_8bfloat16R12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_8bfloat16R12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP9]]
//
v32bfloat16 test_fifo_ld_pop_1d_byte(v32bfloat16 *&p, fifo_state_t &s,
                                     int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP15]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP15]]
//
v32bfloat16 test_fifo_ld_pop_2d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_8bfloat16R12fifo_state_tiiRiiiS5_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP21]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_8bfloat16R12fifo_state_tiiRiiiS5_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP21]]
//
v32bfloat16 test_fifo_ld_pop_3d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// AIE2P-LABEL: @_Z18test_fifo_ld_resetRPDv16_fR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetRPDv16_fR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v16float *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillRPDv16_fR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillRPDv16_fR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v16float *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popRPDv16_fR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP8]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popRPDv16_fR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP8]]
//
v16float test_fifo_ld_pop(v16float *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_fR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP9]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_fR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP9]]
//
v16float test_fifo_ld_pop_1d_byte(v16float *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_fR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2P-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP15]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_fR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP15]]
//
v16float test_fifo_ld_pop_2d_byte(v16float *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_fR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2P-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2P-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP21]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_fR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP21]]
//
v16float test_fifo_ld_pop_3d_byte(v16float *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2P-LABEL: @_Z18test_fifo_ld_resetPU3AS6Dv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 0)
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP1]], 1
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP1]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP2]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP3]], ptr [[POS_I]], align 64
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z18test_fifo_ld_resetPU3AS6Dv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 0)
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP1]], 1
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP1]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP2]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP3]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v32int16 __aie_dm_resource_b *p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_fillPU3AS6Dv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    store <32 x i32> [[TMP3]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP4]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_fillPU3AS6Dv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP3]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP4]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v32int16 __aie_dm_resource_b *p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// AIE2P-LABEL: @_Z16test_fifo_ld_popPU3AS6Dv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP5]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    [[TMP6:%.*]] = bitcast <64 x i8> [[TMP3]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP6]]
//
// AIE2PS-LABEL: @_Z16test_fifo_ld_popPU3AS6Dv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP6:%.*]] = bitcast <64 x i8> [[TMP3]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP6]]
//
v32int16 test_fifo_ld_pop(v32int16 __aie_dm_resource_b *p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_1d_bytePU3AS6Dv32_sR12fifo_state_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]])
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 2
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 3
// AIE2P-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    [[TMP7:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP7]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_1d_bytePU3AS6Dv32_sR12fifo_state_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP7:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP7]]
//
v32int16 test_fifo_ld_pop_1d_byte(v32int16 __aie_dm_resource_b *p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_2d_bytePU3AS6Dv32_sR12fifo_state_tiiRii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]])
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 0
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 2
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 3
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 4
// AIE2P-NEXT:    [[TMP12:%.*]] = zext i20 [[TMP11]] to i32
// AIE2P-NEXT:    store i32 [[TMP12]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP9]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP10]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    [[TMP13:%.*]] = bitcast <64 x i8> [[TMP8]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP13]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_2d_bytePU3AS6Dv32_sR12fifo_state_tiiRii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 0
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 2
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 4
// AIE2PS-NEXT:    [[TMP12:%.*]] = zext i20 [[TMP11]] to i32
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP9]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP10]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP13:%.*]] = bitcast <64 x i8> [[TMP8]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP13]]
//
v32int16 test_fifo_ld_pop_2d_byte(v32int16 __aie_dm_resource_b *p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// AIE2P-LABEL: @_Z24test_fifo_ld_pop_3d_bytePU3AS6Dv32_sR12fifo_state_tiiRiiiS4_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2P-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2P-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2P-NEXT:    [[TMP7:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2P-NEXT:    [[TMP8:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i20
// AIE2P-NEXT:    [[TMP10:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2P-NEXT:    [[TMP11:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP9]], i20 [[TMP10]])
// AIE2P-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 0
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 2
// AIE2P-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 3
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 4
// AIE2P-NEXT:    [[TMP16:%.*]] = zext i20 [[TMP15]] to i32
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 5
// AIE2P-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2P-NEXT:    store i32 [[TMP16]], ptr [[COUNT1]], align 4
// AIE2P-NEXT:    store i32 [[TMP18]], ptr [[COUNT2]], align 4
// AIE2P-NEXT:    store <32 x i32> [[TMP13]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP14]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    [[TMP19:%.*]] = bitcast <64 x i8> [[TMP12]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP19]]
//
// AIE2PS-LABEL: @_Z24test_fifo_ld_pop_3d_bytePU3AS6Dv32_sR12fifo_state_tiiRiiiS4_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i20
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[INC2:%.*]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP9]], i20 [[TMP10]])
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 0
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 2
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 3
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 4
// AIE2PS-NEXT:    [[TMP16:%.*]] = zext i20 [[TMP15]] to i32
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 5
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP13]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP19:%.*]] = bitcast <64 x i8> [[TMP12]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP19]]
//
v32int16 test_fifo_ld_pop_3d_byte(v32int16 __aie_dm_resource_b *p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_DB8_R12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_DB8_R12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v128int4 test_fifo_ld_popx(v128int4 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_DB8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_DB8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v128int4 test_fifo_ld_popx(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_DU8_R12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_DU8_R12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v128uint4 test_fifo_ld_popx(v128uint4 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_DU8_R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_DU8_R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v128uint4 test_fifo_ld_popx(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_aR12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_aR12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v64int8 test_fifo_ld_popx(v64int8 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_aR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_aR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v64int8 test_fifo_ld_popx(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_hR12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_hR12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v64uint8 test_fifo_ld_popx(v64uint8 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv64_hR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    ret <64 x i8> [[TMP5]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv64_hR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret <64 x i8> [[TMP5]]
//
v64uint8 test_fifo_ld_popx(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv32_sR12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv32_sR12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP10]]
//
v32int16 test_fifo_ld_popx(v32int16 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv32_sR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv32_sR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP10]]
//
v32int16 test_fifo_ld_popx(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv32_tR12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv32_tR12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP10]]
//
v32uint16 test_fifo_ld_popx(v32uint16 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv32_tR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv32_tR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP10]]
//
v32uint16 test_fifo_ld_popx(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv16_iR12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv16_iR12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP10]]
//
v16int32 test_fifo_ld_popx(v16int32 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv16_iR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv16_iR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP10]]
//
v16int32 test_fifo_ld_popx(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv16_jR12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv16_jR12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP10]]
//
v16uint32 test_fifo_ld_popx(v16uint32 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv16_jR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2P-NEXT:    ret <16 x i32> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv16_jR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// AIE2PS-NEXT:    ret <16 x i32> [[TMP10]]
//
v16uint32 test_fifo_ld_popx(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv32_8bfloat16R12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv32_8bfloat16R12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP10]]
//
v32bfloat16 test_fifo_ld_popx(v32bfloat16 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv32_8bfloat16R12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP10]]
//
v32bfloat16 test_fifo_ld_popx(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv16_fR12fifo_state_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2P-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv16_fR12fifo_state_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP10]]
//
v16float test_fifo_ld_popx(v16float *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// AIE2P-LABEL: @_Z17test_fifo_ld_popxRPDv16_fR12fifo_state_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2P-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2P-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2P-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2P-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2P-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2P-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2P-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2P-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2P-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2P-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2P-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP10]]
//
// AIE2PS-LABEL: @_Z17test_fifo_ld_popxRPDv16_fR12fifo_state_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP10]]
//
v16float test_fifo_ld_popx(v16float *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}
