// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-srs-intrinsics.cpp ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2P
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2PS

// AIE2P-LABEL: @_Z10test_ussrsDv32_u7__acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ussrsDv32_u7__acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP0]]
//
v32uint8 test_ussrs(v32acc32 acc, int shft, int sign) {
  return ussrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z15test_ussrs_confDv32_u7__acc32iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ussrs_confDv32_u7__acc32iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_ussrs_conf(v32acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return ussrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv32_u7__acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv32_u7__acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_lsrs(v32acc32 acc, int shft, int sign) {
  return lsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv32_u7__acc32iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv32_u7__acc32iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_lsrs_conf(v32acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv32_u7__acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv32_u7__acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_ulsrs(v32acc32 acc, int shft, int sign) {
  return ulsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv32_u7__acc32iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv32_u7__acc32iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_ulsrs_conf(v32acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
//
  return ulsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv16_u7__acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv16_u7__acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_lsrs(v16acc32 acc, int shft, int sign) {
  return lsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv16_u7__acc32iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv16_u7__acc32iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_lsrs_conf(v16acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv16_u7__acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv16_u7__acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_ulsrs(v16acc32 acc, int shft, int sign) {
  return ulsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv16_u7__acc32iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv16_u7__acc32iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_ulsrs_conf(v16acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return ulsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_ssrsDv16_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_ssrsDv16_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_ssrs(v16acc64 acc, int shft, int sign) {
  return ssrs(acc, shft, sign);
}

//
// AIE2P-LABEL: @_Z14test_ssrs_confDv16_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_ssrs_confDv16_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_ssrs_conf(v16acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return ssrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ussrsDv16_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ussrsDv16_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_ussrs(v16acc64 acc, int shft, int sign) {
  return ussrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z15test_ussrs_confDv16_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ussrs_confDv16_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_ussrs_conf(v16acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return ussrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv16_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv16_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_lsrs(v16acc64 acc, int shft, int sign) {
  return lsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv16_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv16_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_lsrs_conf(v16acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv16_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv16_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_ulsrs(v16acc64 acc, int shft, int sign) {
  return ulsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv16_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv16_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_ulsrs_conf(v16acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return ulsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv8_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv8_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_lsrs(v8acc64 acc, int shft, int sign) {
  return lsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv8_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv8_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <8 x i32> [[TMP2]]
//
v8int32 test_lsrs_conf(v8acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv8_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv8_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <8 x i32> [[TMP0]]
//
v8uint32 test_ulsrs(v8acc64 acc, int shft, int sign) {
  return ulsrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv8_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv8_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <8 x i32> [[TMP2]]
//
v8uint32 test_ulsrs_conf(v8acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return ulsrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_ssrsDv32_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_ssrsDv32_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i8> [[TMP0]]
//
v32int8 test_ssrs(v32acc32 acc, int shft) {
  return ssrs(acc, shft);
}

//
// AIE2P-LABEL: @_Z14test_ssrs_confDv32_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_ssrs_confDv32_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP2]]
//
v32int8 test_ssrs_conf(v32acc32 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ssrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ussrsDv32_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <32 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ussrsDv32_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <32 x i8> [[TMP0]]
//
v32uint8 test_ussrs(v32acc32 acc, int shft) {
  return ussrs(acc, shft);
}

// AIE2P-LABEL: @_Z15test_ussrs_confDv32_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ussrs_confDv32_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_ussrs_conf(v32acc32 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ussrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv32_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv32_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_lsrs(v32acc32 acc, int shft) {
  return lsrs(acc, shft);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv32_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv32_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_lsrs_conf(v32acc32 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv32_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv32_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_ulsrs(v32acc32 acc, int shft) {
  return ulsrs(acc, shft);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv32_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv32_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_ulsrs_conf(v32acc32 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ulsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv16_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv16_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_lsrs(v16acc32 acc, int shft) {
  return lsrs(acc, shft);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv16_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv16_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_lsrs_conf(v16acc32 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv16_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv16_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_ulsrs(v16acc32 acc, int shft) {
  return ulsrs(acc, shft);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv16_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv16_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_ulsrs_conf(v16acc32 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ulsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_ssrsDv16_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_ssrsDv16_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_ssrs(v16acc64 acc, int shft) {
  return ssrs(acc, shft);
}

// AIE2P-LABEL: @_Z14test_ssrs_confDv16_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_ssrs_confDv16_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_ssrs_conf(v16acc64 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ssrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ussrsDv16_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ussrsDv16_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_ussrs(v16acc64 acc, int shft) {
  return ussrs(acc, shft);
}

// AIE2P-LABEL: @_Z15test_ussrs_confDv16_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ussrs_confDv16_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_ussrs_conf(v16acc64 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ussrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv16_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv16_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_lsrs(v16acc64 acc, int shft) {
  return lsrs(acc, shft);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv16_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv16_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_lsrs_conf(v16acc64 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv16_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv16_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_ulsrs(v16acc64 acc, int shft) {
  return ulsrs(acc, shft);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv16_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv16_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_ulsrs_conf(v16acc64 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ulsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z9test_lsrsDv8_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lsrsDv8_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_lsrs(v8acc64 acc, int shft) {
  return lsrs(acc, shft);
}

// AIE2P-LABEL: @_Z14test_lsrs_confDv8_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_lsrs_confDv8_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <8 x i32> [[TMP2]]
//
v8int32 test_lsrs_conf(v8acc64 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return lsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z10test_ulsrsDv8_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <8 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z10test_ulsrsDv8_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <8 x i32> [[TMP0]]
//
v8uint32 test_ulsrs(v8acc64 acc, int shft) {
  return ulsrs(acc, shft);
}

// AIE2P-LABEL: @_Z15test_ulsrs_confDv8_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <8 x i32> [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_ulsrs_confDv8_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <8 x i32> [[TMP2]]
//
v8uint32 test_ulsrs_conf(v8acc64 acc, int shft, crsat_t sat, crrnd_t rnd) {
  return ulsrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z30v32acc64_to_v32int16_ssrs_testDv32_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z30v32acc64_to_v32int16_ssrs_testDv32_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 v32acc64_to_v32int16_ssrs_test(v32acc64 acc, int shft, int sign){
  return ssrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z35v32acc64_to_v32int16_ssrs_conf_testDv32_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z35v32acc64_to_v32int16_ssrs_conf_testDv32_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 v32acc64_to_v32int16_ssrs_conf_test(v32acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sign, sat, rnd);
}
// AIE2P-LABEL: @_Z31v32acc64_to_v32int16_ussrs_testDv32_u7__acc64ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z31v32acc64_to_v32int16_ussrs_testDv32_u7__acc64ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 v32acc64_to_v32int16_ussrs_test(v32acc64 acc, int shft, int sign){
  return ussrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z36v32acc64_to_v32int16_ussrs_conf_testDv32_u7__acc64iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z36v32acc64_to_v32int16_ussrs_conf_testDv32_u7__acc64iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 v32acc64_to_v32int16_ussrs_conf_test(v32acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z37v32acc64_to_v32int16_ssrs_nosign_testDv32_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i16> [[TMP0]]
//
// AIE2PS-LABEL: @_Z37v32acc64_to_v32int16_ssrs_nosign_testDv32_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 v32acc64_to_v32int16_ssrs_nosign_test(v32acc64 acc, int shft){
  return ssrs(acc, shft);
}

// AIE2P-LABEL: @_Z42v32acc64_to_v32int16_ssrs_conf_nosign_testDv32_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z42v32acc64_to_v32int16_ssrs_conf_nosign_testDv32_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 v32acc64_to_v32int16_ssrs_conf_nosign_test(v32acc64 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sat, rnd);
}
// AIE2P-LABEL: @_Z38v32acc64_to_v32int16_ussrs_nosign_testDv32_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z38v32acc64_to_v32int16_ussrs_nosign_testDv32_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 v32acc64_to_v32int16_ussrs_nosign_test(v32acc64 acc, int shft){
  return ussrs(acc, shft);
}

// AIE2P-LABEL: @_Z43v32acc64_to_v32int16_ussrs_conf_nosign_testDv32_u7__acc64ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z43v32acc64_to_v32int16_ussrs_conf_nosign_testDv32_u7__acc64iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 v32acc64_to_v32int16_ussrs_conf_nosign_test(v32acc64 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sat, rnd);
}
// AIE2P-LABEL: @_Z29v64acc32_to_v64int8_ssrs_testDv64_u7__acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z29v64acc32_to_v64int8_ssrs_testDv64_u7__acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP0]]
//
v64int8 v64acc32_to_v64int8_ssrs_test(v64acc32 acc, int shft, int sign){
  return ssrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z34v64acc32_to_v64int8_ssrs_conf_testDv64_u7__acc32iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z34v64acc32_to_v64int8_ssrs_conf_testDv64_u7__acc32iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 v64acc32_to_v64int8_ssrs_conf_test(v64acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sign, sat, rnd);
}
// AIE2P-LABEL: @_Z30v64acc32_to_v64int8_ussrs_testDv64_u7__acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z30v64acc32_to_v64int8_ussrs_testDv64_u7__acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 v64acc32_to_v64int8_ussrs_test(v64acc32 acc, int shft, int sign){
  return ussrs(acc, shft, sign);
}

// AIE2P-LABEL: @_Z35v64acc32_to_v64int8_ussrs_conf_testDv64_u7__acc32iijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z35v64acc32_to_v64int8_ussrs_conf_testDv64_u7__acc32iiDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 v64acc32_to_v64int8_ussrs_conf_test(v64acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sign, sat, rnd);
}

// AIE2P-LABEL: @_Z36v64acc32_to_v64int8_ssrs_nosign_testDv64_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z36v64acc32_to_v64int8_ssrs_nosign_testDv64_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <64 x i8> [[TMP0]]
//
v64int8 v64acc32_to_v64int8_ssrs_nosign_test(v64acc32 acc, int shft){
  return ssrs(acc, shft);
}

// AIE2P-LABEL: @_Z41v64acc32_to_v64int8_ssrs_conf_nosign_testDv64_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z41v64acc32_to_v64int8_ssrs_conf_nosign_testDv64_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 v64acc32_to_v64int8_ssrs_conf_nosign_test(v64acc32 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sat, rnd);
}
// AIE2P-LABEL: @_Z37v64acc32_to_v64int8_ussrs_nosign_testDv64_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <64 x i8> [[TMP0]]
//
// AIE2PS-LABEL: @_Z37v64acc32_to_v64int8_ussrs_nosign_testDv64_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 v64acc32_to_v64int8_ussrs_nosign_test(v64acc32 acc, int shft){
  return ussrs(acc, shft);
}

// AIE2P-LABEL: @_Z42v64acc32_to_v64int8_ussrs_conf_nosign_testDv64_u7__acc32ijj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z42v64acc32_to_v64int8_ussrs_conf_nosign_testDv64_u7__acc32iDU2_DU4_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// AIE2PS-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// AIE2PS-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// AIE2PS-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 v64acc32_to_v64int8_ussrs_conf_nosign_test(v64acc32 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sat, rnd);
}

// AIE2P-LABEL: @_Z19test_to_v16bfloat16Dv16_u10__accfloat(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2p.v16accfloat.to.v16bf16(<16 x float> [[ACC:%.*]])
// AIE2P-NEXT:    ret <16 x bfloat> [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_to_v16bfloat16Dv16_u10__accfloat(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[ACC:%.*]])
// AIE2PS-NEXT:    ret <16 x bfloat> [[TMP0]]
//
v16bfloat16 test_to_v16bfloat16(v16accfloat acc) {
  return to_v16bfloat16(acc);
}
