// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-stream-intrinsics.cpp -----------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===---------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2P
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2PS

// AIE2P-LABEL: @_Z21test_get_scd_v16acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v16acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_get_scd_v16acc32(int en) { return get_scd_v16acc32(en); }

// AIE2P-LABEL: @_Z20test_get_scd_v8acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <8 x i64>
// AIE2P-NEXT:    ret <8 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_get_scd_v8acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <8 x i64>
// AIE2PS-NEXT:    ret <8 x i64> [[TMP1]]
//
v8acc64 test_get_scd_v8acc64(int en) { return get_scd_v8acc64(en); }

// AIE2P-LABEL: @_Z24test_get_scd_v16accfloati(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <8 x i64>
// AIE2P-NEXT:    ret <8 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v16accfloati(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <8 x i64>
// AIE2PS-NEXT:    ret <8 x i64> [[TMP1]]
//
v8acc64 test_get_scd_v16accfloat(int en) { return get_scd_v16accfloat(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v128int4i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v128int4i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v128int4 test_get_scd_v128int4(int en) { return get_scd_v128int4(en); }

// AIE2P-LABEL: @_Z22test_get_scd_v128uint4i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v128uint4i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v128uint4 test_get_scd_v128uint4(int en) { return get_scd_v128uint4(en); }

// AIE2P-LABEL: @_Z20test_get_scd_v64int8i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_get_scd_v64int8i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_get_scd_v64int8(int en) { return get_scd_v64int8(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v64uint8i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v64uint8i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_get_scd_v64uint8(int en) { return get_scd_v64uint8(en); }

//
// AIE2P-LABEL: @_Z21test_get_scd_v32int16i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v32int16i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_get_scd_v32int16(int en) { return get_scd_v32int16(en); }

// AIE2P-LABEL: @_Z22test_get_scd_v32uint16i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v32uint16i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_get_scd_v32uint16(int en) { return get_scd_v32uint16(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v16int32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v16int32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_get_scd_v16int32(int en) { return get_scd_v16int32(en); }

//
// AIE2P-LABEL: @_Z22test_get_scd_v16uint32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v16uint32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_get_scd_v16uint32(int en) { return get_scd_v16uint32(en); }

// AIE2P-LABEL: @_Z24test_get_scd_v32bfloat16i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v32bfloat16i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP1]]
//
v32bfloat16 test_get_scd_v32bfloat16(int en) { return get_scd_v32bfloat16(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v16acc32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 1)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v16acc32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 1)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_get_scd_v16acc32() { return get_scd_v16acc32(); }

// AIE2P-LABEL: @_Z20test_get_scd_v8acc64v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.acc32(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <8 x i64>
// AIE2P-NEXT:    ret <8 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_get_scd_v8acc64v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <8 x i64>
// AIE2PS-NEXT:    ret <8 x i64> [[TMP1]]
//
v8acc64 test_get_scd_v8acc64() { return get_scd_v8acc64(); }

// AIE2P-LABEL: @_Z24test_get_scd_v16accfloatv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v16accfloatv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP1]]
//
v16accfloat test_get_scd_v16accfloat() { return get_scd_v16accfloat(); }

// AIE2P-LABEL: @_Z21test_get_scd_v128int4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v128int4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v128int4 test_get_scd_v128int4() { return get_scd_v128int4(); }

// AIE2P-LABEL: @_Z22test_get_scd_v128uint4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v128uint4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v128uint4 test_get_scd_v128uint4() { return get_scd_v128uint4(); }

// AIE2P-LABEL: @_Z20test_get_scd_v64int8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z20test_get_scd_v64int8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_get_scd_v64int8() { return get_scd_v64int8(); }

// AIE2P-LABEL: @_Z21test_get_scd_v64uint8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v64uint8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_get_scd_v64uint8() { return get_scd_v64uint8(); }

// AIE2P-LABEL: @_Z21test_get_scd_v32int16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v32int16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_get_scd_v32int16() { return get_scd_v32int16(); }

//
// AIE2P-LABEL: @_Z22test_get_scd_v32uint16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v32uint16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_get_scd_v32uint16() { return get_scd_v32uint16(); }

// AIE2P-LABEL: @_Z21test_get_scd_v16int32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v16int32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_get_scd_v16int32() { return get_scd_v16int32(); }

// AIE2P-LABEL: @_Z22test_get_scd_v16uint32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v16uint32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_get_scd_v16uint32() { return get_scd_v16uint32(); }

// AIE2P-LABEL: @_Z24test_get_scd_v32bfloat16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v32bfloat16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP1]]
//
v32bfloat16 test_get_scd_v32bfloat16() { return get_scd_v32bfloat16(); }

// AIE2P-LABEL: @_Z21test_get_scd_v32acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v32acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
v32acc32 test_get_scd_v32acc32(int en) { return get_scd_v32acc32(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v16acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <16 x i64>
// AIE2P-NEXT:    ret <16 x i64> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v16acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <16 x i64>
// AIE2PS-NEXT:    ret <16 x i64> [[TMP2]]
//
v16acc64 test_get_scd_v16acc64(int en) { return get_scd_v16acc64(en); }

// AIE2P-LABEL: @_Z24test_get_scd_v32accfloati(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <32 x float>
// AIE2P-NEXT:    ret <32 x float> [[TMP2]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v32accfloati(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <32 x float>
// AIE2PS-NEXT:    ret <32 x float> [[TMP2]]
//
v32accfloat test_get_scd_v32accfloat(int en){ return get_scd_v32accfloat(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v32int32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v32int32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
v32int32 test_get_scd_v32int32(int en) { return get_scd_v32int32(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v256int4i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v256int4i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v256int4 test_get_scd_v256int4(int en) { return get_scd_v256int4(en); }

// AIE2P-LABEL: @_Z22test_get_scd_v256uint4i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v256uint4i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v256uint4 test_get_scd_v256uint4(int en) { return get_scd_v256uint4(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v128int8i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v128int8i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v128int8 test_get_scd_v128int8(int en) { return get_scd_v128int8(en); }

// AIE2P-LABEL: @_Z22test_get_scd_v128uint8i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v128uint8i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v128uint8 test_get_scd_v128uint8(int en) { return get_scd_v128uint8(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v64int16i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <64 x i16>
// AIE2P-NEXT:    ret <64 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v64int16i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <64 x i16>
// AIE2PS-NEXT:    ret <64 x i16> [[TMP2]]
//
v64int16 test_get_scd_v64int16(int en) { return get_scd_v64int16(en); }

// AIE2P-LABEL: @_Z22test_get_scd_v64uint16i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <64 x i16>
// AIE2P-NEXT:    ret <64 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v64uint16i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <64 x i16>
// AIE2PS-NEXT:    ret <64 x i16> [[TMP2]]
//
v64uint16 test_get_scd_v64uint16(int en) { return get_scd_v64uint16(en); }

// AIE2P-LABEL: @_Z22test_get_scd_v32uint32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 [[EN]])
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v32uint32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I]]
//
v32uint32 test_get_scd_v32uint32(int en) { return get_scd_v32uint32(en); }

// AIE2P-LABEL: @_Z21test_get_scd_v32acc32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v32acc32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I]]
//
v32acc32 test_get_scd_v32acc32() { return get_scd_v32acc32(); }

// AIE2P-LABEL: @_Z21test_get_scd_v16acc64v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.acc32(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <16 x i64>
// AIE2P-NEXT:    ret <16 x i64> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v16acc64v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.acc32(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <16 x i64>
// AIE2PS-NEXT:    ret <16 x i64> [[TMP2]]
//
v16acc64 test_get_scd_v16acc64() { return get_scd_v16acc64(); }

// AIE2P-LABEL: @_Z21test_get_scd_v256int4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v256int4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v256int4 test_get_scd_v256int4() { return get_scd_v256int4(); }

// AIE2P-LABEL: @_Z22test_get_scd_v256uint4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v256uint4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v256uint4 test_get_scd_v256uint4() { return get_scd_v256uint4(); }

// AIE2P-LABEL: @_Z21test_get_scd_v128int8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v128int8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v128int8 test_get_scd_v128int8() { return get_scd_v128int8(); }

// AIE2P-LABEL: @_Z22test_get_scd_v128uint8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v128uint8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP2]]
//
v128uint8 test_get_scd_v128uint8() { return get_scd_v128uint8(); }

// AIE2P-LABEL: @_Z21test_get_scd_v64int16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <64 x i16>
// AIE2P-NEXT:    ret <64 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v64int16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <64 x i16>
// AIE2PS-NEXT:    ret <64 x i16> [[TMP2]]
//
v64int16 test_get_scd_v64int16() { return get_scd_v64int16(); }

// AIE2P-LABEL: @_Z22test_get_scd_v64uint16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <64 x i16>
// AIE2P-NEXT:    ret <64 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v64uint16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I_I]] to <64 x i16>
// AIE2PS-NEXT:    ret <64 x i16> [[TMP2]]
//
v64uint16 test_get_scd_v64uint16() { return get_scd_v64uint16(); }

// AIE2P-LABEL: @_Z21test_get_scd_v32int32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I]]
//
// AIE2PS-LABEL: @_Z21test_get_scd_v32int32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I]]
//
v32int32 test_get_scd_v32int32() { return get_scd_v32int32(); }

// AIE2P-LABEL: @_Z22test_get_scd_v32uint32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.scd.read.vec(i32 1)
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I_I]]
//
// AIE2PS-LABEL: @_Z22test_get_scd_v32uint32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 1)
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I_I_I]]
//
v32uint32 test_get_scd_v32uint32() { return get_scd_v32uint32(); }

// AIE2P-LABEL: @_Z24test_get_scd_v32acc32_loi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.lo(i32 [[EN:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v32acc32_loi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.lo(i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_get_scd_v32acc32_lo(int en) { return get_scd_v32acc32_lo(en); }

// AIE2P-LABEL: @_Z24test_get_scd_v32acc32_hii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.hi(i32 [[EN:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v32acc32_hii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.hi(i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_get_scd_v32acc32_hi(int en) { return get_scd_v32acc32_hi(en); }

// AIE2P-LABEL: @_Z24test_get_scd_v16acc64_loi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.lo(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2P-NEXT:    ret <16 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v16acc64_loi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.lo(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2PS-NEXT:    ret <16 x i64> [[TMP1]]
//
v16acc64 test_get_scd_v16acc64_lo(int en) { return get_scd_v16acc64_lo(en); }

// AIE2P-LABEL: @_Z24test_get_scd_v16acc64_hii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.hi(i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2P-NEXT:    ret <16 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v16acc64_hii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.hi(i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2PS-NEXT:    ret <16 x i64> [[TMP1]]
//
v16acc64 test_get_scd_v16acc64_hi(int en) { return get_scd_v16acc64_hi(en); }

// AIE2P-LABEL: @_Z24test_get_scd_v32acc32_lov(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.lo(i32 1)
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v32acc32_lov(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.lo(i32 1)
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_get_scd_v32acc32_lo() { return get_scd_v32acc32_lo(); }

// AIE2P-LABEL: @_Z24test_get_scd_v32acc32_hiv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.hi(i32 1)
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v32acc32_hiv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.hi(i32 1)
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_get_scd_v32acc32_hi() { return get_scd_v32acc32_hi(); }

// AIE2P-LABEL: @_Z24test_get_scd_v16acc64_lov(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.lo(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2P-NEXT:    ret <16 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v16acc64_lov(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.lo(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2PS-NEXT:    ret <16 x i64> [[TMP1]]
//
v16acc64 test_get_scd_v16acc64_lo() { return get_scd_v16acc64_lo(); }

// AIE2P-LABEL: @_Z24test_get_scd_v16acc64_hiv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.hi(i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2P-NEXT:    ret <16 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_get_scd_v16acc64_hiv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.hi(i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[TMP0]] to <16 x i64>
// AIE2PS-NEXT:    ret <16 x i64> [[TMP1]]
//
v16acc64 test_get_scd_v16acc64_hi() { return get_scd_v16acc64_hi(); }

//
// AIE2P-LABEL: @_Z12test_put_mcdDv16_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32> [[A:%.*]] to <8 x i64>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32> [[A:%.*]] to <8 x i64>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16acc32 a, int en) { put_mcd(a, en); }

//
// AIE2P-LABEL: @_Z12test_put_mcdDv8_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[A:%.*]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv8_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[A:%.*]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v8acc64 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_u10__accfloati(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <8 x i64>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_u10__accfloati(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <8 x i64>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16accfloat a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_DB8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_DB8_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128int4 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_DU8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_DU8_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128uint4 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_ai(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_ai(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64int8 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_hi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_hi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64uint8 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32int16 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32uint16 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[A:%.*]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[A:%.*]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16int32 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_ji(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[A:%.*]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_ji(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[A:%.*]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16uint32 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_8bfloat16i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_8bfloat16i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32bfloat16 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_u7__acc32(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32> [[A:%.*]] to <8 x i64>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_u7__acc32(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32> [[A:%.*]] to <8 x i64>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16acc32 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv8_u7__acc64(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[A:%.*]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv8_u7__acc64(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v8acc64 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_u10__accfloat(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <8 x i64>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_u10__accfloat(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <8 x i64>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16accfloat a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_DB8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_DB8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128int4 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_DU8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_DU8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128uint4 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64int8 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64uint8 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32int16 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32uint16 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[A:%.*]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16int32 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[A:%.*]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[A:%.*]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16uint32 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_8bfloat16(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_8bfloat16(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32bfloat16 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_u7__acc32i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i32> [[A:%.*]] to <16 x i64>
// AIE2P-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP1]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[A]] to <16 x i64>
// AIE2P-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i64> [[TMP2]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP3]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_u7__acc32i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i32> [[A:%.*]] to <16 x i64>
// AIE2PS-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP1]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[A]] to <16 x i64>
// AIE2PS-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i64> [[TMP2]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP3]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32acc32 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_u7__acc64i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i64> [[A:%.*]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP0]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[A]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP1]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_u7__acc64i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i64> [[A:%.*]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP0]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[A]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP1]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16acc64 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32int32 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_DB8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_DB8_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v256int4 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_DU8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_DU8_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v256uint4 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_ai(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_ai(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128int8 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_hi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_hi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128uint8 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64int16 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64uint16 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_ji(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_ji(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN:%.*]])
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32uint32 a, int en) { put_mcd(a, en); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_u7__acc32(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i32> [[A:%.*]] to <16 x i64>
// AIE2P-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP1]], i32 1)
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[A]] to <16 x i64>
// AIE2P-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i64> [[TMP2]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP3]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_u7__acc32(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i32> [[A:%.*]] to <16 x i64>
// AIE2PS-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP1]], i32 1)
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[A]] to <16 x i64>
// AIE2PS-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i64> [[TMP2]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP3]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32acc32 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv16_u7__acc64(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i64> [[A:%.*]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP0]], i32 1)
// AIE2P-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[A]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> [[TMP1]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv16_u7__acc64(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i64> [[A:%.*]], <16 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP0]], i32 1)
// AIE2PS-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i64> [[A]], <16 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.acc32(<8 x i64> [[TMP1]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v16acc64 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_DB8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_DB8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v256int4 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_DU8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_DU8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v256uint4 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128int8 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv128_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv128_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v128uint8 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64int16 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv64_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv64_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v64uint16 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32int32 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z12test_put_mcdDv32_j(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z12test_put_mcdDv32_j(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A:%.*]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    [[SHUFFLE1_I_I_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I_I]], i32 1)
// AIE2PS-NEXT:    ret void
//
void test_put_mcd(v32uint32 a) { put_mcd(a); }

// AIE2P-LABEL: @_Z11test_put_msii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(int val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VAL:%.*]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VAL:%.*]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(int val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbiiRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2:![0-9]+]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbiiRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2:![0-9]+]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(int val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbiRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[VAL:%.*]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbiRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[VAL:%.*]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(int val, bool &success) { put_ms_nb(val, success); }

// AIE2P-LABEL: @_Z11test_put_msji(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msji(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(unsigned int val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msj(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VAL:%.*]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msj(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VAL:%.*]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(unsigned int val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbjiRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbjiRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[VAL:%.*]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(unsigned int val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbjRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[VAL:%.*]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbjRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[VAL:%.*]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP0]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(unsigned int val, bool &success) {
  put_ms_nb(val, success);
}

// AIE2P-LABEL: @_Z11test_put_msDv4_DB8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_DB8_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8int4 val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv4_DB8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_DB8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8int4 val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_DB8_iRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_DB8_iRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v8int4 val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_DB8_Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_DB8_Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v8int4 val, bool &success) { put_ms_nb(val, success); }

// AIE2P-LABEL: @_Z11test_put_msDv4_DU8_i(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_DU8_i(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8uint4 val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv4_DU8_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_DU8_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8uint4 val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_DU8_iRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_DU8_iRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v8uint4 val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_DU8_Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_DU8_Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v8uint4 val, bool &success) { put_ms_nb(val, success); }

// AIE2P-LABEL: @_Z11test_put_msDv4_ai(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_ai(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v4int8 val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv4_a(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_a(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v4int8 val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_aiRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_aiRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v4int8 val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_aRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_aRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v4int8 val, bool &success) { put_ms_nb(val, success); }

// AIE2P-LABEL: @_Z11test_put_msDv4_hi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_hi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v4uint8 val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv4_h(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_h(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v4uint8 val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_hiRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_hiRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v4uint8 val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbDv4_hRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv4_hRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v4uint8 val, bool &success) { put_ms_nb(val, success); }

// AIE2P-LABEL: @_Z11test_put_msDv2_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv2_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v2int16 val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv2_s(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv2_s(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v2int16 val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbDv2_siRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv2_siRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v2int16 val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbDv2_sRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv2_sRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v2int16 val, bool &success) { put_ms_nb(val, success); }

// AIE2P-LABEL: @_Z11test_put_msDv2_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv2_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v2uint16 val, int tlast) { put_ms(val, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv2_t(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv2_t(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v2uint16 val) { put_ms(val); }

// AIE2P-LABEL: @_Z14test_put_ms_nbDv2_tiRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv2_tiRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v2uint16 val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// AIE2P-LABEL: @_Z14test_put_ms_nbDv2_tRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2p.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2P-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z14test_put_ms_nbDv2_tRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[VAL:%.*]] to i32
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 0)
// AIE2PS-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret void
//
void test_put_ms_nb(v2uint16 val, bool &success) { put_ms_nb(val, success); }

// AIE2P-LABEL: @_Z11test_put_msDv4_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v4int32 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_DB8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_DB8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32int4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_DU8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_DU8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32uint4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_aii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_aii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16int8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_hii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_hii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16uint8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv8_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv8_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8int16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv8_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv8_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8uint16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv4_jii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_jii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v4uint32 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv8_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv8_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8int32 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_DB8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_DB8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v64int4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_DU8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_DU8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v64uint4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_aii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_aii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32int8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_hii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_hii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32uint8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16int16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16uint16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv8_jii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv8_jii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[A]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8uint32 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16int32 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv64_DB8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv64_DB8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v128int4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv64_DU8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv64_DU8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v128uint4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv64_aii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv64_aii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v64int8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv64_hii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv64_hii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v64uint8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32int16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32uint16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv16_jii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_jii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[A]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16uint32 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[A]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[A]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[A]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[A]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[A]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[A]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[A]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[A]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[A]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[A]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[A]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[A]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[A]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[A]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[A]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[A]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[A]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[A]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[A]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[A]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[A]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[A]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[A]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[A]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[A]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[A]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[A]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[A]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[A]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[A]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[A]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[A]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32int32 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv128_DB8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv128_DB8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v256int4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv128_DU8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv128_DU8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v256uint4 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv128_aii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv128_aii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v128int8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv128_hii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv128_hii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v128uint8 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv64_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv64_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v64int16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv64_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv64_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v64uint16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_put_msDv32_jii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[A:%.*]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[A]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[A]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[A]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[A]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[A]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[A]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[A]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[A]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[A]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[A]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[A]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[A]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[A]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[A]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[A]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[A]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_jii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[A:%.*]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[A]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[A]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[A]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[A]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[A]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[A]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[A]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[A]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[A]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[A]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[A]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[A]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[A]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[A]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[A]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[A]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[A]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32uint32 a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv64_8bfloat16ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x bfloat> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv64_8bfloat16ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x bfloat> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v64bfloat16 a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv32_fii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A:%.*]] to <32 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_fii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A:%.*]] to <32 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32float a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv32_8bfloat16ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv32_8bfloat16ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v32bfloat16 a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv16_fii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <16 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_fii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A:%.*]] to <16 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_2_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_3_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_4_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_5_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_6_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_7_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_8_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_9_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_10_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_11_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_12_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_13_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I5_14_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16float a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv16_8bfloat16ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv16_8bfloat16ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v16bfloat16 a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv8_fii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[A:%.*]] to <8 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv8_fii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[A:%.*]] to <8 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_3_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_4_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_5_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_6_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8float a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv8_8bfloat16ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv8_8bfloat16ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v8bfloat16 a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv4_fii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A:%.*]] to <4 x i32>
// AIE2P-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2P-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv4_fii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A:%.*]] to <4 x i32>
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_1_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I6_2_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I_I]], i32 0)
// AIE2PS-NEXT:    [[VECEXT_I_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v4float a, int en, int tlast) { put_ms(a, en, tlast); }
// AIE2P-LABEL: @_Z11test_put_msDv2_8bfloat16ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <2 x bfloat> [[A:%.*]] to i32
// AIE2P-NEXT:    tail call void @llvm.aie2p.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2P-NEXT:    ret void
//
// AIE2PS-LABEL: @_Z11test_put_msDv2_8bfloat16ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <2 x bfloat> [[A:%.*]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST:%.*]])
// AIE2PS-NEXT:    ret void
//
void test_put_ms(v2bfloat16 a, int en, int tlast) { put_ms(a, en, tlast); }

// AIE2P-LABEL: @_Z11test_get_ssv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z11test_get_ssv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
int test_get_ss() { return get_ss(); }

// AIE2P-LABEL: @_Z11test_get_ssRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z11test_get_ssRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
int test_get_ss(bool &tlast) { return get_ss(tlast); }

// AIE2P-LABEL: @_Z14test_get_ss_nbRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_get_ss_nbRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
int test_get_ss_nb(bool &success) { return get_ss_nb(success); }

// AIE2P-LABEL: @_Z14test_get_ss_nbRbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z14test_get_ss_nbRbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
int test_get_ss_nb(bool &success, bool &tlast) {
  return get_ss_nb(success, tlast);
}

// AIE2P-LABEL: @_Z15test_get_ss_intv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z15test_get_ss_intv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
int test_get_ss_int() { return get_ss_int(); }

// AIE2P-LABEL: @_Z15test_get_ss_intRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z15test_get_ss_intRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
int test_get_ss_int(bool &tlast) { return get_ss_int(tlast); }

// AIE2P-LABEL: @_Z18test_get_ss_nb_intRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z18test_get_ss_nb_intRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
int test_get_ss_nb_int(bool &success) { return get_ss_nb_int(success); }

// AIE2P-LABEL: @_Z18test_get_ss_nb_intRbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z18test_get_ss_nb_intRbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
int test_get_ss_nb_int(bool &success, bool &tlast) {
  return get_ss_nb_int(success, tlast);
}

// AIE2P-LABEL: @_Z16test_get_ss_uintv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    ret i32 [[TMP1]]
//
// AIE2PS-LABEL: @_Z16test_get_ss_uintv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    ret i32 [[TMP1]]
//
unsigned int test_get_ss_uint() { return get_ss_uint(); }

// AIE2P-LABEL: @_Z16test_get_ss_uintRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z16test_get_ss_uintRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
unsigned int test_get_ss_uint(bool &tlast) { return get_ss_uint(tlast); }

// AIE2P-LABEL: @_Z19test_get_ss_nb_uintRb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_nb_uintRb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
unsigned int test_get_ss_nb_uint(bool &success) {
  return get_ss_nb_uint(success);
}

// AIE2P-LABEL: @_Z19test_get_ss_nb_uintRbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret i32 [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_nb_uintRbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP3]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = lshr i8 [[TMP3]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret i32 [[TMP2]]
//
unsigned int test_get_ss_nb_uint(bool &success, bool &tlast) {
  return get_ss_nb_uint(success, tlast);
}

// AIE2P-LABEL: @_Z18test_get_ss_v8int4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z18test_get_ss_v8int4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2PS-NEXT:    ret <4 x i8> [[TMP2]]
//
v8int4 test_get_ss_v8int4() { return get_ss_v8int4(); }

// AIE2P-LABEL: @_Z18test_get_ss_v8int4Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z18test_get_ss_v8int4Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v8int4 test_get_ss_v8int4(bool &tlast) { return get_ss_v8int4(tlast); }

// AIE2P-LABEL: @_Z21test_get_ss_nb_v8int4Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_nb_v8int4Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v8int4 test_get_ss_nb_v8int4(bool &success) {
  return get_ss_nb_v8int4(success);
}

// AIE2P-LABEL: @_Z21test_get_ss_nb_v8int4RbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_nb_v8int4RbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v8int4 test_get_ss_nb_v8int4(bool &success, bool &tlast) {
  return get_ss_nb_v8int4(success, tlast);
}

// AIE2P-LABEL: @_Z19test_get_ss_v8uint4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v8uint4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2PS-NEXT:    ret <4 x i8> [[TMP2]]
//
v8uint4 test_get_ss_v8uint4() { return get_ss_v8uint4(); }

// AIE2P-LABEL: @_Z19test_get_ss_v8uint4Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v8uint4Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v8uint4 test_get_ss_v8uint4(bool &tlast) { return get_ss_v8uint4(tlast); }

// AIE2P-LABEL: @_Z22test_get_ss_nb_v8uint4Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_nb_v8uint4Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v8uint4 test_get_ss_nb_v8uint4(bool &success) {
  return get_ss_nb_v8uint4(success);
}

// AIE2P-LABEL: @_Z22test_get_ss_nb_v8uint4RbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_nb_v8uint4RbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v8uint4 test_get_ss_nb_v8uint4(bool &success, bool &tlast) {
  return get_ss_nb_v8uint4(success, tlast);
}

// AIE2P-LABEL: @_Z18test_get_ss_v4int8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z18test_get_ss_v4int8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2PS-NEXT:    ret <4 x i8> [[TMP2]]
//
v4int8 test_get_ss_v4int8() { return get_ss_v4int8(); }

// AIE2P-LABEL: @_Z18test_get_ss_v4int8Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z18test_get_ss_v4int8Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v4int8 test_get_ss_v4int8(bool &tlast) { return get_ss_v4int8(tlast); }

// AIE2P-LABEL: @_Z21test_get_ss_nb_v4int8Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_nb_v4int8Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v4int8 test_get_ss_nb_v4int8(bool &success) {
  return get_ss_nb_v4int8(success);
}

// AIE2P-LABEL: @_Z21test_get_ss_nb_v4int8RbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_nb_v4int8RbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v4int8 test_get_ss_nb_v4int8(bool &success, bool &tlast) {
  return get_ss_nb_v4int8(success, tlast);
}

// AIE2P-LABEL: @_Z19test_get_ss_v4uint8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2P-NEXT:    ret <4 x i8> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v4uint8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
// AIE2PS-NEXT:    ret <4 x i8> [[TMP2]]
//
v4uint8 test_get_ss_v4uint8() { return get_ss_v4uint8(); }

// AIE2P-LABEL: @_Z19test_get_ss_v4uint8Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v4uint8Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v4uint8 test_get_ss_v4uint8(bool &tlast) { return get_ss_v4uint8(tlast); }

// AIE2P-LABEL: @_Z22test_get_ss_nb_v4uint8Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_nb_v4uint8Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v4uint8 test_get_ss_nb_v4uint8(bool &success) {
  return get_ss_nb_v4uint8(success);
}

// AIE2P-LABEL: @_Z22test_get_ss_nb_v4uint8RbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <4 x i8> [[TMP3]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_nb_v4uint8RbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <4 x i8>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <4 x i8> [[TMP3]]
//
v4uint8 test_get_ss_nb_v4uint8(bool &success, bool &tlast) {
  return get_ss_nb_v4uint8(success, tlast);
}

// AIE2P-LABEL: @_Z19test_get_ss_v2int16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x i16>
// AIE2P-NEXT:    ret <2 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v2int16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x i16>
// AIE2PS-NEXT:    ret <2 x i16> [[TMP2]]
//
v2int16 test_get_ss_v2int16() { return get_ss_v2int16(); }

// AIE2P-LABEL: @_Z19test_get_ss_v2int16Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <2 x i16> [[TMP3]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v2int16Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <2 x i16> [[TMP3]]
//
v2int16 test_get_ss_v2int16(bool &tlast) { return get_ss_v2int16(tlast); }

// AIE2P-LABEL: @_Z22test_get_ss_nb_v2int16Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <2 x i16> [[TMP3]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_nb_v2int16Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <2 x i16> [[TMP3]]
//
v2int16 test_get_ss_nb_v2int16(bool &success) {
  return get_ss_nb_v2int16(success);
}

// AIE2P-LABEL: @_Z22test_get_ss_nb_v2int16RbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <2 x i16> [[TMP3]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_nb_v2int16RbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <2 x i16> [[TMP3]]
//
v2int16 test_get_ss_nb_v2int16(bool &success, bool &tlast) {
  return get_ss_nb_v2int16(success, tlast);
}

// AIE2P-LABEL: @_Z20test_get_ss_v2uint16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x i16>
// AIE2P-NEXT:    ret <2 x i16> [[TMP2]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v2uint16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x i16>
// AIE2PS-NEXT:    ret <2 x i16> [[TMP2]]
//
v2uint16 test_get_ss_v2uint16() { return get_ss_v2uint16(); }

// AIE2P-LABEL: @_Z20test_get_ss_v2uint16Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <2 x i16> [[TMP3]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v2uint16Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <2 x i16> [[TMP3]]
//
v2uint16 test_get_ss_v2uint16(bool &tlast) { return get_ss_v2uint16(tlast); }

// AIE2P-LABEL: @_Z23test_get_ss_nb_v2uint16Rb(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <2 x i16> [[TMP3]]
//
// AIE2PS-LABEL: @_Z23test_get_ss_nb_v2uint16Rb(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <2 x i16> [[TMP3]]
//
v2uint16 test_get_ss_nb_v2uint16(bool &success) {
  return get_ss_nb_v2uint16(success);
}

// AIE2P-LABEL: @_Z23test_get_ss_nb_v2uint16RbS_(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2P-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2P-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2P-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2P-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2P-NEXT:    ret <2 x i16> [[TMP3]]
//
// AIE2PS-LABEL: @_Z23test_get_ss_nb_v2uint16RbS_(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x i16>
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// AIE2PS-NEXT:    [[FROMBOOL_I:%.*]] = and i8 [[TMP4]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL_I]], ptr [[TLAST:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// AIE2PS-NEXT:    [[FROMBOOL3_I:%.*]] = and i8 [[TMP5]], 1
// AIE2PS-NEXT:    store i8 [[FROMBOOL3_I]], ptr [[SUCCESS:%.*]], align 1, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    ret <2 x i16> [[TMP3]]
//
v2uint16 test_get_ss_nb_v2uint16(bool &success, bool &tlast) {
  return get_ss_nb_v2uint16(success, tlast);
}

// AIE2P-LABEL: @_Z19test_get_ss_v4int32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    ret <4 x i32> [[SHUFFLE_I_I_I]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v4int32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    ret <4 x i32> [[SHUFFLE_I_I_I]]
//
v4int32 test_get_ss_v4int32() { return get_ss_v4int32(); }

// AIE2P-LABEL: @_Z19test_get_ss_v32int4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2P-NEXT:    ret <16 x i8> [[TMP11]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v32int4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2PS-NEXT:    ret <16 x i8> [[TMP11]]
//
v32int4 test_get_ss_v32int4() { return get_ss_v32int4(); }

// AIE2P-LABEL: @_Z20test_get_ss_v32uint4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2P-NEXT:    ret <16 x i8> [[TMP11]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v32uint4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2PS-NEXT:    ret <16 x i8> [[TMP11]]
//
v32uint4 test_get_ss_v32uint4() { return get_ss_v32uint4(); }

// AIE2P-LABEL: @_Z19test_get_ss_v16int8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2P-NEXT:    ret <16 x i8> [[TMP11]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v16int8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2PS-NEXT:    ret <16 x i8> [[TMP11]]
//
v16int8 test_get_ss_v16int8() { return get_ss_v16int8(); }

// AIE2P-LABEL: @_Z20test_get_ss_v16uint8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2P-NEXT:    ret <16 x i8> [[TMP11]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v16uint8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <16 x i8>
// AIE2PS-NEXT:    ret <16 x i8> [[TMP11]]
//
v16uint8 test_get_ss_v16uint8() { return get_ss_v16uint8(); }

// AIE2P-LABEL: @_Z19test_get_ss_v8int16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <8 x i16>
// AIE2P-NEXT:    ret <8 x i16> [[TMP11]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v8int16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <8 x i16>
// AIE2PS-NEXT:    ret <8 x i16> [[TMP11]]
//
v8int16 test_get_ss_v8int16() { return get_ss_v8int16(); }

// AIE2P-LABEL: @_Z20test_get_ss_v8uint16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <8 x i16>
// AIE2P-NEXT:    ret <8 x i16> [[TMP11]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v8uint16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <8 x i16>
// AIE2PS-NEXT:    ret <8 x i16> [[TMP11]]
//
v8uint16 test_get_ss_v8uint16() { return get_ss_v8uint16(); }

// AIE2P-LABEL: @_Z20test_get_ss_v4uint32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    ret <4 x i32> [[SHUFFLE_I_I_I]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v4uint32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    ret <4 x i32> [[SHUFFLE_I_I_I]]
//
v4uint32 test_get_ss_v4uint32() { return get_ss_v4uint32(); }

// AIE2P-LABEL: @_Z19test_get_ss_v8int32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    ret <8 x i32> [[SHUFFLE_I_I_I]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v8int32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    ret <8 x i32> [[SHUFFLE_I_I_I]]
//
v8int32 test_get_ss_v8int32() { return get_ss_v8int32(); }

// AIE2P-LABEL: @_Z19test_get_ss_v64int4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2P-NEXT:    ret <32 x i8> [[TMP16]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v64int4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2PS-NEXT:    ret <32 x i8> [[TMP16]]
//
v64int4 test_get_ss_v64int4() { return get_ss_v64int4(); }

// AIE2P-LABEL: @_Z20test_get_ss_v64uint4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2P-NEXT:    ret <32 x i8> [[TMP16]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v64uint4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2PS-NEXT:    ret <32 x i8> [[TMP16]]
//
v64uint4 test_get_ss_v64uint4() { return get_ss_v64uint4(); }

// AIE2P-LABEL: @_Z19test_get_ss_v32int8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2P-NEXT:    ret <32 x i8> [[TMP16]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v32int8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2PS-NEXT:    ret <32 x i8> [[TMP16]]
//
v32int8 test_get_ss_v32int8() { return get_ss_v32int8(); }

// AIE2P-LABEL: @_Z20test_get_ss_v32uint8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2P-NEXT:    ret <32 x i8> [[TMP16]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v32uint8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <32 x i8>
// AIE2PS-NEXT:    ret <32 x i8> [[TMP16]]
//
v32uint8 test_get_ss_v32uint8() { return get_ss_v32uint8(); }

// AIE2P-LABEL: @_Z20test_get_ss_v16int16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <16 x i16>
// AIE2P-NEXT:    ret <16 x i16> [[TMP16]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v16int16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <16 x i16>
// AIE2PS-NEXT:    ret <16 x i16> [[TMP16]]
//
v16int16 test_get_ss_v16int16() { return get_ss_v16int16(); }

// AIE2P-LABEL: @_Z21test_get_ss_v16uint16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <16 x i16>
// AIE2P-NEXT:    ret <16 x i16> [[TMP16]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v16uint16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <16 x i16>
// AIE2PS-NEXT:    ret <16 x i16> [[TMP16]]
//
v16uint16 test_get_ss_v16uint16() { return get_ss_v16uint16(); }

// AIE2P-LABEL: @_Z20test_get_ss_v8uint32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    ret <8 x i32> [[SHUFFLE_I_I_I]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v8uint32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    ret <8 x i32> [[SHUFFLE_I_I_I]]
//
v8uint32 test_get_ss_v8uint32() { return get_ss_v8uint32(); }

// AIE2P-LABEL: @_Z20test_get_ss_v16int32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    ret <16 x i32> [[VECINS_I_I_I]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v16int32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    ret <16 x i32> [[VECINS_I_I_I]]
//
v16int32 test_get_ss_v16int32() { return get_ss_v16int32(); }

// AIE2P-LABEL: @_Z20test_get_ss_v128int4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP32]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v128int4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP32]]
//
v128int4 test_get_ss_v128int4() { return get_ss_v128int4(); }

// AIE2P-LABEL: @_Z21test_get_ss_v128uint4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP32]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v128uint4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP32]]
//
v128uint4 test_get_ss_v128uint4() { return get_ss_v128uint4(); }

// AIE2P-LABEL: @_Z19test_get_ss_v64int8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP32]]
//
// AIE2PS-LABEL: @_Z19test_get_ss_v64int8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP32]]
//
v64int8 test_get_ss_v64int8() { return get_ss_v64int8(); }

// AIE2P-LABEL: @_Z20test_get_ss_v64uint8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP32]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v64uint8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <64 x i8>
// AIE2PS-NEXT:    ret <64 x i8> [[TMP32]]
//
v64uint8 test_get_ss_v64uint8() { return get_ss_v64uint8(); }

// AIE2P-LABEL: @_Z20test_get_ss_v32int16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP32]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v32int16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP32]]
//
v32int16 test_get_ss_v32int16() { return get_ss_v32int16(); }

// AIE2P-LABEL: @_Z21test_get_ss_v32uint16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP32]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v32uint16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <32 x i16>
// AIE2PS-NEXT:    ret <32 x i16> [[TMP32]]
//
v32uint16 test_get_ss_v32uint16() { return get_ss_v32uint16(); }

// AIE2P-LABEL: @_Z21test_get_ss_v16uint32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    ret <16 x i32> [[VECINS_I_I_I]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v16uint32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    ret <16 x i32> [[VECINS_I_I_I]]
//
v16uint32 test_get_ss_v16uint32() { return get_ss_v16uint32(); }

// AIE2P-LABEL: @_Z20test_get_ss_v32int32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v32int32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
v32int32 test_get_ss_v32int32() { return get_ss_v32int32(); }

// AIE2P-LABEL: @_Z20test_get_ss_v256int4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP64]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v256int4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP64]]
//
v256int4 test_get_ss_v256int4() { return get_ss_v256int4(); }

// AIE2P-LABEL: @_Z21test_get_ss_v256uint4v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP64]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v256uint4v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP64]]
//
v256uint4 test_get_ss_v256uint4() { return get_ss_v256uint4(); }

// AIE2P-LABEL: @_Z20test_get_ss_v128int8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP64]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v128int8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP64]]
//
v128int8 test_get_ss_v128int8() { return get_ss_v128int8(); }

// AIE2P-LABEL: @_Z21test_get_ss_v128uint8v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2P-NEXT:    ret <128 x i8> [[TMP64]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v128uint8v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <128 x i8>
// AIE2PS-NEXT:    ret <128 x i8> [[TMP64]]
//
v128uint8 test_get_ss_v128uint8() { return get_ss_v128uint8(); }

// AIE2P-LABEL: @_Z20test_get_ss_v64int16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <64 x i16>
// AIE2P-NEXT:    ret <64 x i16> [[TMP64]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v64int16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <64 x i16>
// AIE2PS-NEXT:    ret <64 x i16> [[TMP64]]
//
v64int16 test_get_ss_v64int16() { return get_ss_v64int16(); }

// AIE2P-LABEL: @_Z21test_get_ss_v64uint16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <64 x i16>
// AIE2P-NEXT:    ret <64 x i16> [[TMP64]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v64uint16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <64 x i16>
// AIE2PS-NEXT:    ret <64 x i16> [[TMP64]]
//
v64uint16 test_get_ss_v64uint16() { return get_ss_v64uint16(); }

// AIE2P-LABEL: @_Z21test_get_ss_v32uint32v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v32uint32v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
v32uint32 test_get_ss_v32uint32() { return get_ss_v32uint32(); }

// AIE2P-LABEL: @_Z23test_get_ss_v64bfloat16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <64 x bfloat>
// AIE2P-NEXT:    ret <64 x bfloat> [[TMP64]]
//
// AIE2PS-LABEL: @_Z23test_get_ss_v64bfloat16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <64 x bfloat>
// AIE2PS-NEXT:    ret <64 x bfloat> [[TMP64]]
//
v64bfloat16 test_get_ss_v64bfloat16() { return get_ss_v64bfloat16(); }
// AIE2P-LABEL: @_Z21test_get_ss_v32bfloatv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2P-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2P-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2P-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2P-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2P-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2P-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2P-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2P-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2P-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2P-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2P-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2P-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2P-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2P-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2P-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2P-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2P-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <32 x float>
// AIE2P-NEXT:    ret <32 x float> [[TMP64]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v32bfloatv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// AIE2PS-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// AIE2PS-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// AIE2PS-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// AIE2PS-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// AIE2PS-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// AIE2PS-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// AIE2PS-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// AIE2PS-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// AIE2PS-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// AIE2PS-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// AIE2PS-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// AIE2PS-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// AIE2PS-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// AIE2PS-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// AIE2PS-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// AIE2PS-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// AIE2PS-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <32 x float>
// AIE2PS-NEXT:    ret <32 x float> [[TMP64]]
//
v32float test_get_ss_v32bfloat() { return get_ss_v32float(); }

// AIE2P-LABEL: @_Z23test_get_ss_v32bfloat16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <32 x bfloat>
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP32]]
//
// AIE2PS-LABEL: @_Z23test_get_ss_v32bfloat16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP32]]
//
v32bfloat16 test_get_ss_v32bfloat16() { return get_ss_v32bfloat16(); }
// AIE2P-LABEL: @_Z21test_get_ss_v16bfloatv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2P-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2P-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2P-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2P-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2P-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2P-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2P-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2P-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2P-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP32]]
//
// AIE2PS-LABEL: @_Z21test_get_ss_v16bfloatv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// AIE2PS-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// AIE2PS-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// AIE2PS-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// AIE2PS-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// AIE2PS-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// AIE2PS-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// AIE2PS-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// AIE2PS-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    ret <16 x float> [[TMP32]]
//
v16float test_get_ss_v16bfloat() { return get_ss_v16float(); }

// AIE2P-LABEL: @_Z23test_get_ss_v16bfloat16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <16 x bfloat>
// AIE2P-NEXT:    ret <16 x bfloat> [[TMP16]]
//
// AIE2PS-LABEL: @_Z23test_get_ss_v16bfloat16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <16 x bfloat>
// AIE2PS-NEXT:    ret <16 x bfloat> [[TMP16]]
//
v16bfloat16 test_get_ss_v16bfloat16() { return get_ss_v16bfloat16(); }
// AIE2P-LABEL: @_Z20test_get_ss_v8bfloatv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2P-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2P-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2P-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2P-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2P-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2P-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2P-NEXT:    [[TMP16:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <16 x float>
// AIE2P-NEXT:    [[TMP17:%.*]] = shufflevector <16 x float> [[TMP16]], <16 x float> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2P-NEXT:    ret <8 x float> [[TMP17]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v8bfloatv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// AIE2PS-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// AIE2PS-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// AIE2PS-NEXT:    [[TMP16:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <16 x float>
// AIE2PS-NEXT:    [[TMP17:%.*]] = shufflevector <16 x float> [[TMP16]], <16 x float> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// AIE2PS-NEXT:    ret <8 x float> [[TMP17]]
//
v8float test_get_ss_v8bfloat() { return get_ss_v8float(); }

// AIE2P-LABEL: @_Z22test_get_ss_v8bfloat16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <8 x bfloat>
// AIE2P-NEXT:    ret <8 x bfloat> [[TMP11]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_v8bfloat16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <8 x bfloat>
// AIE2PS-NEXT:    ret <8 x bfloat> [[TMP11]]
//
v8bfloat16 test_get_ss_v8bfloat16() { return get_ss_v8bfloat16(); }
// AIE2P-LABEL: @_Z20test_get_ss_v4bfloatv(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2P-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2P-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2P-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2P-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2P-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2P-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <4 x float>
// AIE2P-NEXT:    ret <4 x float> [[TMP11]]
//
// AIE2PS-LABEL: @_Z20test_get_ss_v4bfloatv(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// AIE2PS-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// AIE2PS-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// AIE2PS-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <4 x float>
// AIE2PS-NEXT:    ret <4 x float> [[TMP11]]
//
v4float test_get_ss_v4bfloat() { return get_ss_v4float(); }

// AIE2P-LABEL: @_Z22test_get_ss_v2bfloat16v(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2p.get.ss()
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x bfloat>
// AIE2P-NEXT:    ret <2 x bfloat> [[TMP2]]
//
// AIE2PS-LABEL: @_Z22test_get_ss_v2bfloat16v(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x bfloat>
// AIE2PS-NEXT:    ret <2 x bfloat> [[TMP2]]
//
v2bfloat16 test_get_ss_v2bfloat16() { return get_ss_v2bfloat16(); }
// AIE2P-LABEL: @_Z28test_get_scd_expand_v32acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.scd.expand.ACC1024(i32 [[EN:%.*]], i32 [[POS:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z28test_get_scd_expand_v32acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.scd.expand.ACC1024(i32 [[EN:%.*]], i32 [[POS:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_get_scd_expand_v32acc32(int en, int pos) {
  return get_scd_expand_v32acc32(en, pos);
}
// AIE2P-LABEL: @_Z28test_get_scd_expand_v64acc32ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.scd.expand.ACC2048(i32 [[EN:%.*]], i32 [[POS:%.*]])
// AIE2P-NEXT:    ret <64 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z28test_get_scd_expand_v64acc32ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.scd.expand.ACC2048(i32 [[EN:%.*]], i32 [[POS:%.*]])
// AIE2PS-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_get_scd_expand_v64acc32(int en, int pos) {
  return get_scd_expand_v64acc32(en, pos);
}
// AIE2P-LABEL: @_Z33test_get_scd_expand_v32acc32_incriRi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load i20, ptr [[POS:%.*]], align 4, !tbaa [[TBAA6:![0-9]+]]
// AIE2P-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[TMP0]] to ptr
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <16 x i64>, i32 } @llvm.aie2p.scd.expand.ACC1024.incr(i32 [[EN:%.*]], ptr [[TMP1]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i64>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    store i32 [[TMP3]], ptr [[POS]], align 4
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i64>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i64> [[TMP4]] to <32 x i32>
// AIE2P-NEXT:    ret <32 x i32> [[TMP5]]
//
// AIE2PS-LABEL: @_Z33test_get_scd_expand_v32acc32_incriRi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = load i20, ptr [[POS:%.*]], align 4, !tbaa [[TBAA6:![0-9]+]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[TMP0]] to ptr
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <16 x i64>, i32 } @llvm.aie2ps.scd.expand.ACC1024.incr(i32 [[EN:%.*]], ptr [[TMP1]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i64>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    store i32 [[TMP3]], ptr [[POS]], align 4
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i64>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <16 x i64> [[TMP4]] to <32 x i32>
// AIE2PS-NEXT:    ret <32 x i32> [[TMP5]]
//
v32acc32 test_get_scd_expand_v32acc32_incr(int en, int &pos) {
  return get_scd_expand_v32acc32_incr(en, pos);
}
// AIE2P-LABEL: @_Z33test_get_scd_expand_v64acc32_incriRi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = load i20, ptr [[POS:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2P-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[TMP0]] to ptr
// AIE2P-NEXT:    [[TMP2:%.*]] = tail call { <32 x i64>, i32 } @llvm.aie2p.scd.expand.ACC2048.incr(i32 [[EN:%.*]], ptr [[TMP1]])
// AIE2P-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i64>, i32 } [[TMP2]], 1
// AIE2P-NEXT:    store i32 [[TMP3]], ptr [[POS]], align 4
// AIE2P-NEXT:    [[TMP4:%.*]] = extractvalue { <32 x i64>, i32 } [[TMP2]], 0
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <32 x i64> [[TMP4]] to <64 x i32>
// AIE2P-NEXT:    ret <64 x i32> [[TMP5]]
//
// AIE2PS-LABEL: @_Z33test_get_scd_expand_v64acc32_incriRi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = load i20, ptr [[POS:%.*]], align 4, !tbaa [[TBAA6]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[TMP0]] to ptr
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { <32 x i64>, i32 } @llvm.aie2ps.scd.expand.ACC2048.incr(i32 [[EN:%.*]], ptr [[TMP1]])
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { <32 x i64>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    store i32 [[TMP3]], ptr [[POS]], align 4
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <32 x i64>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = bitcast <32 x i64> [[TMP4]] to <64 x i32>
// AIE2PS-NEXT:    ret <64 x i32> [[TMP5]]
//
v64acc32 test_get_scd_expand_v64acc32_incr(int en, int &pos) {
  return get_scd_expand_v64acc32_incr(en, pos);
}

